### ISSUE TITLE
Add example of ascii fill_include/exclude_names

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#10001]
### Description

To provide better illumination on how `fill_include_names` and `fill_exclude_names` work, add a doc example similar to below:

```
>>> lines = ['a,b,c,d', '1,2,3,4', ',,,']

>>> ascii.read(lines)
<Table length=2>
  a     b     c     d  
int64 int64 int64 int64
----- ----- ----- -----
    1     2     3     4
   --    --    --    --
>>> ascii.read(lines, fill_include_names=['a', 'c'])
<Table length=2>
  a    b     c    d  
int64 str1 int64 str1
----- ---- ----- ----
    1    2     3    4
   --         --     

>>> ascii.read(lines, fill_exclude_names=['a', 'c'])
<Table length=2>
 a     b    c     d  
str1 int64 str1 int64
---- ----- ---- -----
   1     2    3     4
        --         --
```

**Comment by pllim** [comment]
For clarity, why would someone need this feature? Is this something that `pandas` has?

**Comment by taldcroft** [comment]
One use case is where you have a CSV file with empty values indicating missing values, but for a string column you might really want those to be empty strings `""` not masked.  Or maybe you have a file that uses -99 as the missing data indicator for most columns but then -99 occurs as real data in another column.  Without this feature it is a little annoying (though still possible) to read the data in correctly.

The case can be made that this machinery is a bit more complicated than necessary, but since we got an issue report it looks like someone is using it.  :smile:

Pandas has its own complicated system, see the options related to `na` in https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html.

**Comment by kakirastern** [comment]
HI, I would like to work on this issue if it is still open.

**Comment by kakirastern** [comment]
I could for example add an example [here](https://github.com/astropy/astropy/blob/66a2f9322b135ea216b00da5ac3bfc8404b43612/docs/io/ascii/index.rst) at the .rst page for `ASCII`.
