### ISSUE TITLE
mpc format issue with satellites

### ISSUE THREAD

**Issue by JFerreira1994** [astropy/astropy#10004]
Hello,

I was performing a task that required grabbing the MPC observations of several asteroids. I requested that the MPC format was maintained, as this was necessary for me, but there seems to be a bug with the way astropy parses satellite observations within these files. Rather than having one line with the observation and another with the satellite identification, both 80 characters long, astropy instead grabs these as a single 160-character long line, which was causing one of my tools to not read these observations correctly.

The step to reproduce this is quite simple, we just need to use:

obs = MPC.get_observations(Asteroid_number,get_mpcformat=True), and look for any line where the observation is identified with a capital "S".

Please let me know if this is indeed a bug within astropy, or if there is possibly some feature that allows to fix this.

Best regards,
João Ferreira

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by pllim** [comment]
No idea what MPC package is. Did you consult with the MPC maintainers first?

**Comment by JFerreira1994** [comment]
It is the Minot Planet Center query package: astroquery.mpc/astroquery.solarsystem.MPC.

I import it with the line:

from astroquery.mpc import MPC

Astroquery is still affiliated to astropy, correct?

**Comment by pllim** [comment]
Ah, please open an issue at https://github.com/astropy/astroquery/issues . We apologize for any inconvenience caused.
