### ISSUE TITLE
Inconsistent behavior when using float on complex number vs complex quantity

### ISSUE THREAD

**Issue by namurphy** [astropy/astropy#10010]
### Description

Using `float` or `numpy.float` on a complex number results in a `TypeError`.  Using `float` or `numpy.float` on that complex number represented as a dimensionless `Quantity` results in the real part being returned and a `ComplexWarning` being issued.  The consequence is that code using complex numbers and complex quantities may behave differently, so it may be necessary to write separate code to handle complex numbers and complex quantities.  Code that relies on the current behavior for quantities should instead use `numpy.real`. 

### Expected behavior

I would expect that using `float` or `numpy.float` on a complex number represented as a dimensionless `Quantity` would raise a `TypeError` also. 

### Actual behavior

Using `float` on a complex number multiplied with `astropy.units.dimensionless_unscaled` returns the real part while issuing a `ComplexWarning`.

### Steps to Reproduce

```Python
>>> import numpy as np
>>> import astropy.units as u
>>> complex_number = 5 + 6j
>>> complex_quantity = complex_number * u.dimensionless_unscaled

>>> float(complex_number)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert complex to float

>>> float(complex_quantity)  # would expect a TypeError for consistency
/media/Scratch/namurphy/envs/empty_for_astropy/lib/python3.8/site-packages/astropy/units/quantity.py:1077: ComplexWarning: Casting complex values to real discards the imaginary part
  return float(self.to_value(dimensionless_unscaled))
5.0
```

The `TypeError` came from [this line in quantity.py](https://github.com/astropy/astropy/blob/3c88b57e39cbda39b6f604c7472e7b3e40c9d690/astropy/units/quantity.py#L1077).

### System Details

```
Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-glibc2.10
Python 3.8.2 | packaged by conda-forge | (default, Mar  4 2020, 21:29:16) 
[GCC 7.3.0]
Numpy 1.18.1
astropy 4.1.dev703+g3c88b57e3
ModuleNotFoundError: No module named 'scipy'
```

**Comment by mhvk** [comment]
@namurphy - that is an annoying inconsistency, though it originates with numpy, not astropy:
```
float(np.complex_(5 + 6j))                                                                    
/usr/bin/ipython3:1: ComplexWarning: Casting complex values to real discards the imaginary part
  #!/usr/bin/python3
# 5.0
```
So, if we were to make `Quantity` consistent with python, we would become inconsistent with numpy. Since `Quantity` is an `ndarray` subclass, my sense is that that would be worse than just keeping things as they are.

Arguably, best would be for numpy to fix this (if they want to fix it; it is not completely obvious what the right behaviour is). Might it make sense to raise a numpy issue?

**Comment by pllim** [comment]
If you open a Numpy issue, please cross-link to this issue. Thank you!

**Comment by namurphy** [comment]
Thanks!  There was already a similar issue that I replied to: https://github.com/numpy/numpy/issues/13007

I suppose we could close this since it's an upstream issue with NumPy, though another possibility would be adding it at the end of the list of known issues in the docs.  At the very least, people in the future who run into `float` vs `complex` weirdness will at least have this issue to refer to.  Good luck, future scientists of the world!

This issue brought to you by writing tests for edge cases that will probably never happen... :joy_cat:

**Comment by pllim** [comment]
@namurphy , I think documenting it in known issues is a great idea. Would you be interested to open a PR? 😄

**Comment by namurphy** [comment]
> @namurphy , I think documenting it in known issues is a great idea. Would you be interested to open a PR? smile

I just volunteered for something again, didn't I? :scream_cat:

**Comment by namurphy** [comment]
The PR was just merged, so it's now in the docs as a known issue.

**Comment by mhvk** [comment]
Thanks, @namurphy - Since I think this is more or less the best we can do, I'll close this issue.
