### ISSUE TITLE
TST: CI failures with pytest 5.4.0

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10039]
`pytest` 5.4.0 was released today and caused  astropy/pytest-doctestplus#94 . Expect to see failures here until this is fixed or we have to pin `pytest`.

Also: https://github.com/astropy/astropy/issues/10039#issuecomment-599733047

**UPDATE:** Seems like we can either go with astropy/ci-helpers#429 or #10040 for now until `doctestplus` is fixed.

**Comment by bsipocz** [comment]
Oh, well. I pinned the version in ci-helpers, but we don't use ci-helpers any more 🤦‍♀

**Comment by pllim** [comment]
Or... we can bundle `pytest` (again). 😂

**Comment by pllim** [comment]
In fiddling with #10038, I also found that `pytest` 5.4.1 to be incompatible with `pytest-xdist`, causing the 32-bit/parallel job to fail. See pytest-dev/pytest#6925

**Comment by bsipocz** [comment]
Workaround has been merged, and we have an upstream issue opened, so I'm closing this now.

**Comment by pllim** [comment]
Thank you, all!

**Comment by dstansby** [comment]
I'm struggling to follow the chain here, does anyone know what the workaround was that was merged (or the PR it was in?) I'm running onto this same issue in sunpy.

**Comment by bsipocz** [comment]
look at how the pin file (that is hosted in ci-helpers is used in tox.ini)
