### ISSUE TITLE
Sign in for travis changed? How to cancel jobs?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10057]
I used to be able to cancel builds on travis, but somehow am not signed in the right way any more. I only seem to be able to sign into travis via github as myself, which does not give me privilege to cancel jobs, not even on my own PRs. Any suggestion?

**Comment by bsipocz** [comment]
There has been a scheduled maintenance to their databases earlier today, I think you've been caught up in that (https://www.traviscistatus.com/). 

Could you try it again? Everything works for me as usual, and I'm certain we have the same access level for the repos.

**Comment by mhvk** [comment]
OK, signing out and in solved it. Thanks!
