### ISSUE TITLE
Quantity ndmin argument is ignored if constructed from another quantity with convertible unit

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#10063]
### Description
If a `Quantity` is constructed from another quantity that has a different but convertible unit, the `ndmin` argument is ignored.

### Expected behavior
`ndmin` argument is not ignored

### Steps to Reproduce
```python
>>> import astropy.units as u
>>> u.Quantity(u.Quantity(1, 'm'), 'm', ndmin=1).ndim
1
>>> u.Quantity(u.Quantity(1, 'cm'), 'm', ndmin=1).ndim
0
```

**Comment by mhvk** [comment]
@MaxNoe - oops, that's not good!  The relevant code is https://github.com/astropy/astropy/blob/bda418d77d930d7990bbf27779242913ba98a57c/astropy/units/quantity.py#L298-L316

And what you are seeing is a combination of l. 302 and l. 309. Possibly the easiest is simply to remove l.309 (and combine the two `if`s); alternatively, one would have to test also `ndmin` in l.308.

**Comment by MaxNoe** [comment]
I think the `if dtype is None: return value` is the problem, let me see if I can fix it.

**Comment by MaxNoe** [comment]
Sorry, did not realize that you amde a comment identifying the issue below the code. I just didn't see it

**Comment by mhvk** [comment]
No worries!
