### ISSUE TITLE
TimeDatetime does not roundtrip properly

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10064]
Bug reported by Joris Kersten via @kelle:
> I recently noticed that some of my scripts that were developed with Astropy 3 fail with Astropy 4.
The problems seem to be related to tables with Time objects in them. Writing and reading a Table does not work and opening the table in a browser (Firefox in my case) fails.
>
> I wrote two small example scripts, which I attached to this email. These scripts give no error for me with Astropy version 3.2.3 , but do give errors with Astropy version 4.0. I use Windows 10 and Anaconda with Python 3.7 and NumPy 1.18.1 .
>
> First I believed that Time objects created from datetime objects were the cause. Indeed, this is the case that breaks reading the written table. Reading with other Time objects works well. (See script.) However, show_in_browser fails also for t4 = Time('1999-01-01T00:00:00.123456789') objects, but not for # t5 = Time([1, 2, 3], format='unix') objects. So, the problem is wider than just with datetime objects. Also interesting: show_in_browser does not fail if jsviewer=False is set.

```
from datetime import datetime
from astropy.time import Time
from astropy.table import Table

# Time object initiated from datetime objects.
timelist = Time([datetime(2020, 4, 1),
                 datetime(2020, 4, 2),
                 datetime(2020, 4, 3)])

timetable = Table([timelist], names=("timestamp",))

print(timetable)

# The read action below fails with Astropy 4.
timetable.write("DateDatetimeTable.ecsv", format='ascii.ecsv', overwrite=True)
tablefromfile = Table.read("DateDatetimeTable.ecsv", format='ascii.ecsv')
```

Also a problem (not just for `datetime`)
```
timetable.show_in_browser(jsviewer=True)
# AttributeError: 'Time' object has no attribute 'dtype'
```

**Comment by taldcroft** [comment]
The error in `Table.read("DateDatetimeTable.ecsv", format='ascii.ecsv')` is because the `format` is set to `datetime` but then it tries to create a `Time` object using the corresponding ISO strings.  i.e.
```
In [9]: Time('2020-04-01 00:00:00', format='datetime')                                                                                 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/miniconda3/lib/python3.7/site-packages/astropy/time/core.py in _get_time_fmt(self, val, val2, format, scale, precision, in_subfmt, out_subfmt)
    533             try:
--> 534                 return cls(val, val2, scale, precision, in_subfmt, out_subfmt)
    535             except UnitConversionError:

~/miniconda3/lib/python3.7/site-packages/astropy/time/formats.py in __init__(self, val1, val2, scale, precision, in_subfmt, out_subfmt, from_jd)
    145         else:
--> 146             val1, val2 = self._check_val_type(val1, val2)
    147             self.set_jds(val1, val2)

~/miniconda3/lib/python3.7/site-packages/astropy/time/formats.py in _check_val_type(self, val1, val2)
    745             raise TypeError('Input values for {} class must be '
--> 746                             'datetime objects'.format(self.name))
    747         if val2 is not None:

TypeError: Input values for datetime class must be datetime objects
```
I guess we can address this by allowing the datetime format to accept ISO strings on input.

**Comment by mhvk** [comment]
That makes sense. But why did this use to work?

**Comment by mhvk** [comment]
Hmm, the test that I put up there was actually a shortened version of the real one that was sent along - the one I have above fails on 4.0 in exactly the same way as the one sent, but it also fails on 3.2.3, while the test originally sent does not. So, I better paste that in below...

The difference is the creation via a list of times: as a result, the round-tripped table does not actually contain times at all, but just an array of strings. In that sense, this is a bit less of a regression than I thought. I suspect the other error is similarly related to the list of times being turned into an object array.

```
from datetime import datetime
from astropy.time import Time
from astropy.table import Table


# Time object initiated from datetime objects.
t1 = Time(datetime(2020, 4, 1, hour=12, minute=0, second=0, microsecond=0))
t2 = Time(datetime(2020, 4, 2, hour=12, minute=0, second=0, microsecond=0))
t3 = Time(datetime(2020, 4, 3, hour=12, minute=0, second=0, microsecond=0))

timelist = [t1, t2, t3]

# The Time objects below do not produce an error.
# t4 = Time('1999-01-01T00:00:00.123456789')
# timelist = [t4, t4, t4]


timetable = Table([timelist], names=("timestamp",))

print(timetable)
print(type(timetable['timestamp'][0]))
# <class 'astropy.time.core.Time'>

# The read action below fails with Astropy 4.
timetable.write("DateDatetimeTable.ecsv", format='ascii.ecsv', overwrite=True)
tablefromfile = Table.read("DateDatetimeTable.ecsv", format='ascii.ecsv')

print(tablefromfile)
print(type(tablefromfile['timestamp'][0]))
# <class 'str'>
```

**Comment by taldcroft** [comment]
Note that (at least in astropy 4.0) there is an available workaround:
```
timetable.write('out.ecsv', serialize_method={Time: 'jd1_jd2'})
```
With this I am able to read back `out.ecsv` and get the same `Time` object in `datetime` format.

**Comment by mhvk** [comment]
I think the bug with `show_in_browser` is really separate - table cannot be written in `format='jsviewer'` - see #10067. Might be as easy as using `col.info.dtype` instead of `col.dtype`...

**Comment by mhvk** [comment]
Ah, good to know about the work-around. Still, we clearly want to be able to read in tables we have written, so I think you are right that we have to ensure the `datetime` format also understands strings (either only in recreating, or perhaps just generally).

**Comment by taldcroft** [comment]
So modifying your example above:
```
...

# The read action below fails with Astropy 4. 
>>> timetable.write("DateDatetimeTable.ecsv", format='ascii.ecsv', overwrite=True, serialize_method={Time: 'jd1_jd2'}) 
>>> tablefromfile = Table.read("DateDatetimeTable.ecsv", format='ascii.ecsv') 

>>> print(tablefromfile) 
>>> print(type(tablefromfile['timestamp'][0]))                                                                                    
     timestamp     
-------------------
2020-04-01 12:00:00
2020-04-02 12:00:00
2020-04-03 12:00:00
<class 'astropy.time.core.Time'>
     timestamp     
-------------------
2020-04-01 12:00:00
2020-04-02 12:00:00
2020-04-03 12:00:00
<class 'astropy.time.core.Time'>
```

**Comment by taldcroft** [comment]
I'm working on allowing `TimeDateTime` to accept any valid string that can initialize `Time`.

**Comment by mhvk** [comment]
Super! I got the `show_in_browser` one working (I think); see #10068

**Comment by taldcroft** [comment]
> I'm working on allowing TimeDateTime to accept any valid string that can initialize Time.

Which doesn't mean I will succeed... I had been a little worried about breaking the `TimeUnique` pact that only one format can accept a particular format of string input.  So we are saying that `2020-04-03 12:00:00` is a valid input for `datetime` but that is also a valid `iso` format input.  So I tried to put `TimeDateTime` at the end of the formats list, to get things to mostly work, but that is already hacky and fragile.  And it actually breaks some tests in unexpected ways, e.g.:
```
        with pytest.raises(ValueError):
>           t = Time('1999-01-01T00:00:32.123456789(TAI)', scale="utc")
E           Failed: DID NOT RAISE <class 'ValueError'>
```
So I'm not that sure there is a super-easy fix now.

**Comment by taldcroft** [comment]
So maybe plan B of fixing this in `TimeInfo._construct_from_dict` including a special-case for `datetime` format.

**Comment by mhvk** [comment]
Plan B sounds good at least for a short-term fix.

Longer-term, perhaps there could be a bit more logic related to `TimeUnique` - that e.g. strings only get tried by `TimeString` formats if no explicit format is given.

**Comment by mhvk** [comment]
None of the examples at the top fail, so somehow we managed to fix things even while not thinking about this issue. closing.
