### ISSUE TITLE
TST: Big-endian S390 and ARM64 tests failed

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10087]
Saw the failures when checking cron job. Example log as follow.

```
ERROR: Command errored out with exit status 1:
   command: .../bin/python3 .../pep517/_in_process.py get_requires_for_build_wheel /tmp/...
       cwd: /home/travis/build/astropy/astropy
  Complete output (1 lines):
  .../bin/python3: can't find '__main__' module in .../pep517/_in_process.py'
```

This causes error in test collection because `pytest` cannot find `version.py`.

cc @bsipocz and @mhvk 

**Big-Endian S390**

https://travis-ci.org/github/astropy/astropy/jobs/668392445

**ARM64**

https://travis-ci.org/github/astropy/astropy/jobs/668392446

**Comment by bsipocz** [comment]
Interesting. I've seen these before (even made comments about them on slack?/on the PR?), but then they disappeared. And also didn't come up on the 4.0.x branch.

**Comment by pllim** [comment]
Hmm. Just in case, I cleared Travis cache for `master`. We'll see what the next cron job run reports.

**Comment by pllim** [comment]
Update: Still failed -- https://travis-ci.org/github/astropy/astropy/builds/669289125

**Comment by mhvk** [comment]
I'll try to have a look...  Thanks for keeping an eye out!

**Comment by pllim** [comment]
Not sure what you did to fix it but they pass now. Thanks!

https://travis-ci.org/github/astropy/astropy/builds/670616880

**Comment by mhvk** [comment]
I haven't done a thing! But happy to know some issues resolve automagically...
