### ISSUE TITLE
SkyCoord.directional_offset_by only allows a single vector input

### ISSUE THREAD

**Issue by martinjohndyer** [astropy/astropy#10083]
### Description
It would be useful to allow giving `SkyCoord.directional_offset_by` and similar functions multiple vector inputs and have them return ND matrices.

### Expected behavior
Ideally I'd like to be able to offset vector coordinates by multiple angles and directions and get a multidimensional `SkyCoord` back (without needing to loop over anything).

For example, say I have a telescope with a field of view of 10 arcminutes. For a set of points I want to find the extent of the field, i.e. the northernmost/southernmost/easternmost/westernmost point visible, which means offsetting by 10 arcminutes with angles of [0,90,180,270] degrees.

This works for a single coordinate:

```python
>>> from astropy.coordinates import SkyCoord
>>> from astropy import units as u

>>> coord = SkyCoord(0*u.deg, 0*u.deg)
>>> angles = [0, 90, 180, 270]*u.deg
>>> coord.directional_offset_by(angles, 10*u.arcmin)
<SkyCoord (ICRS): (ra, dec) in deg
    [(0.00000000e+00,  1.66666667e-01), (1.66666667e-01,  1.02053756e-17),
     (0.00000000e+00, -1.66666667e-01), (3.59833333e+02, -3.06161268e-17)]>
```

But this isn't currently simple for multiple coordinates. The neatest way of doing that (I think) would be:

```python
>>> coords = SkyCoord([0,10,20,30]*u.deg, [0,10,20,30]*u.deg)
>>> angles = [0, 90, 180, 270]*u.deg
>>> coords.directional_offset_by(angles, 10*u.arcmin)
...
```

Here I'd like back a 4x4 matrix, with each of the four input coordinates moved in the 4 directions. 

### Actual behavior

Right now if you do the above you get back a 4x1 SkyCoord. In this case the 1st point has been moved north, the 2nd point has been moved east etc. It's mapping the `i`th angle to the `i`th coordinate. 
```python
>>> coords = SkyCoord([0,10,20,30]*u.deg, [0,10,20,30]*u.deg)
>>> angles = [0, 90, 180, 270]*u.deg
>>> coords.directional_offset_by(angles, 10*u.arcmin)
<SkyCoord (ICRS): (ra, dec) in deg
    [( 0.        ,  0.16666667), (10.16923775,  9.99995726),
     (20.        , 19.83333333), (29.80755009, 29.99986005)]>
```

And if `len(coords) != len(angles)` then it raises a `ValueError`. If for example I only wanted to move north and south:

```python
>>> coords = SkyCoord([0,10,20,30]*u.deg, [0,10,20,30]*u.deg)
>>> angles = [0, 180]*u.deg
>>> coords.directional_offset_by(angles, 10*u.arcmin)
ValueError: operands could not be broadcast together with shapes (4,) (2,)
```

And likewise if I had more coordinates. This matters for survey telescope trying to operate on a grid of tiles, we might want to pass in several thousand coordinates and find the extent of the FoV at each point.

### Current workaround

Now to be clear the behaviour the function currently has is still useful, so I wouldn't want to break that. And there are also ways around this to do what you want: you can loop over the coordinates or the angles, and then with a bit of reshaping I could get what I was was looking for:

```python
>>> coords = SkyCoord([0,10,20,30]*u.deg, [0,10,20,30]*u.deg)
>>> angles = [0, 180]*u.deg
>>> SkyCoord([coords.directional_offset_by(angle, 10*u.arcmin) for angle in angles]).reshape(len(angles),len(coords)).T
<SkyCoord (ICRS): (ra, dec) in deg
    [[( 0.,  0.16666667), ( 0., -0.16666667)],
     [(10., 10.16666667), (10.,  9.83333333)],
     [(20., 20.16666667), (20., 19.83333333)],
     [(30., 30.16666667), (30., 29.83333333)]]>
```

There would have to be some other option in `directional_offset_by` to return a matrix instead of mapping one-to-one.

And for completeness I believe this could apply to `position_angle` and `separation` too. If you had a set of N coordinates and wanted to find the separation to M targets you'd currently have to loop though one or the other, it would be nice if you could create the matrix instead.

**Comment by pllim** [comment]
Thanks for reporting this! I'll mark as feature request for now but `coordinates` subpackage maintainers will adjust label as necessary.

**Comment by martinjohndyer** [comment]
Thanks. Since I submitted this I've rethought some of it, and I do see the use of the current behaviour. So I've rewritten the issue to hopefully be clearer on what additional functionality would be useful, while also making clear that you can achieve the same thing at the moment if you need to.

**Comment by mhvk** [comment]
@martinjohndyer - the idea in almost everything is that inputs broadcast against each other, so your angles would have to be entered with something like `angles.reshape(angles.shape+(1,)*coord.ndim)` (note, I have not checked that this actually work, but if it doesn't, and I didn't simply mistype, it is a bug!). 

Or, if you know angles are 1D and you want it as the last dimension in the new array, you could do something like `coord[..., np.newaxis].directional_offset_by(angles, 10*u.arcmin)`.

**Comment by StuartLittlefair** [comment]
Exactly as @mhvk suggests...

Martin, to get the exact result in your example case in much less time, try the following:

```python
In [147]: coords.directional_offset_by(angles[:, np.newaxis], 10*u.arcmin).T    
Out[147]: 
<SkyCoord (ICRS): (ra, dec) in deg
    [[( 0.,  0.16666667), ( 0., -0.16666667)],
     [(10., 10.16666667), (10.,  9.83333333)],
     [(20., 20.16666667), (20., 19.83333333)],
     [(30., 30.16666667), (30., 29.83333333)]]>
```

**Comment by martinjohndyer** [comment]
Ah, I should have just asked you in the first place Stu!

That's great, thanks @mhvk & @StuartLittlefair. Happy to close this as unnecessary.
