### ISSUE TITLE
Unclear docs for uncertainty argument to Constant

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#10102]
`astropy.constants.Constant` has an `uncertainty` parameter, which is documented as

> The known uncertainty in this constant’s value.

It isn't clear whether this is a relative or absolute uncertainty however; this should be clarified in the docs.

**Comment by pllim** [comment]
I think it is absolute. Value is taken off the official site. For example:
```python
k_B = CODATA2010('k_B', "Boltzmann constant", 1.3806488e-23, 'J / (K)',
                 0.0000013e-23, system='si')
```

**Comment by cosmicoder** [comment]
I have made a PR on the same.
