### ISSUE TITLE
TST: Still some leftover doctest outputs left

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10133]
A reminder to investigate https://github.com/astropy/astropy/pull/9439#issuecomment-611770982 . These files not cleaned up after a remote data tests on Windows.

```
        Leap_Second.dat
        de421.bsp
        deltat.data
        deltat.preds
```

**Comment by jdavies-st** [comment]
None of these are doctest leftovers.

The correct location for `Leap_Second.dat` is here:
```
astropy/utils/iers/data/Leap_Second.dat
```
Not sure why it is getting pulled into the top level.  Maybe there's a bug in the IERS update code?

Looks like `skyfield` is pulling in the `de421.bsp` ephemeris.

https://github.com/astropy/astropy/blob/5034b40c700304c67d8e53d6cf49e99fe97ac2af/astropy/coordinates/tests/test_solar_system.py#L55

It should be doing so in a `tmpdir` for the test.

And the `deltat` is only used in `_erfa/core` as far as I can tell.  No idea how it is getting written out.

**Comment by pllim** [comment]
@mhvk or @eteq can explain the ERFA one, I hope. Thanks for digging at this, @jdavies-st !

**Comment by mhvk** [comment]
Very weird, even in the very top-level
```
find . -type f -exec grep preds {} \; -print
```
gives nothing!  This may need some more windows-specific investigation...

For `Leap_Second.dat`, might somehow `astropy/utils/iers/data/update_builtin_iers.sh` be executed automatically? (it really shouldn't!)

**Comment by pllim** [comment]
Narrowed all the files down to `pytest astropy/coordinates --remote-data`. Investigating...

**Comment by jdavies-st** [comment]
The `Leap_Second.dat` download can happen automatically on a fresh install in a fresh env, completely unsolicited and has been happing since 4.0 was released.

It was very disconcerting when I saw it happen, because it was happening in code that had an astropy dependency and it was not clear why it was happening.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/issues/10133#issuecomment-613099443

@jdavies-st, maybe you should open a new issue about that. I thought @mhvk said the download won't happen unless the one in package data is outdated. You still see this behavior with the latest dev?

**Comment by jdavies-st** [comment]
Here's your culprit.

```
>>> from astropy.utils.data import clear_download_cache
>>> clear_download_cache()
>>> 
$ pytest astropy/utils/iers/tests/test_leap_second.py --remote-data=any -s -k test_open_leap_seconds_list
=========================================================== test session starts ===========================================================
platform darwin -- Python 3.8.2, pytest-5.3.5, py-1.8.1, pluggy-0.13.1

Running tests with Astropy version 4.1.dev877+g7af398b48.
Running tests in astropy/utils/iers/tests/test_leap_second.py.

Date: 2020-04-13T17:28:44

Platform: macOS-10.13.6-x86_64-i386-64bit

Executable: /Users/jdavies/miniconda3/envs/test/bin/python

Full Python Version: 
3.8.2 (default, Mar 26 2020, 10:43:30) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.18.2
Scipy: 1.4.1
Matplotlib: not available
h5py: not available
Pandas: not available
Cython: 0.29.16
Scikit-image: not available
asdf: 2.5.2

Using Astropy options: remote_data: any.

rootdir: /Users/jdavies/dev/astropy, inifile: setup.cfg
plugins: asdf-2.5.2, arraydiff-0.3, requests-mock-1.7.0, remotedata-0.3.2, openfiles-0.4.0, ci-watson-0.5, xdist-1.31.0, filter-subpackage-0.1.1, hypothesis-5.8.3, forked-1.1.3, doctestplus-0.5.0, astropy-header-0.1.2, cov-2.8.1
collected 31 items / 29 deselected / 2 selected                                                                                           

astropy/utils/iers/tests/test_leap_second.py .Downloading file:/Users/jdavies/dev/astropy/astropy/utils/iers/tests/data/leap-seconds.list
|=====================================================================================================|  10k/ 10k (100.00%)         0s
Downloading file:/Users/jdavies/dev/astropy/astropy/utils/iers/tests/data/leap-seconds.list
|=====================================================================================================|  10k/ 10k (100.00%)         0s
Downloading file:/Users/jdavies/dev/astropy/astropy/utils/iers/tests/data/leap-seconds.list
|=====================================================================================================|  10k/ 10k (100.00%)         0s
.

==================================================== 2 passed, 29 deselected in 0.74s =====================================================
```

**Comment by pllim** [comment]
I think we're seeing two different things. I am running the tests with existing cache.

**Comment by pllim** [comment]
@jdavies-st , what is your `git status` like after?

**Comment by mhvk** [comment]
@jdavies-st - as @pllim notes, this should not happen if the leap-second table is up to date; we do have a separate issue about this possibly unwanted download at https://github.com/astropy/astropy/issues/9479#issuecomment-610663029 (though the surprise is perhaps that the moment `Time` is imported, the check and possible download is done). Do note there what you would like the behaviour to be! (I'm a bit wary of only downloading when needed - though we may have to go there; I must admit I hadn't realized astropy is run with out of date leap second tables that often! It is scary...). 

I do wonder, though, if this may not solve its presence, if on windows the new version is downloaded but not properly put in the cache? (or perhaps the cache is the package directory on windows??)

**Comment by jdavies-st** [comment]
I should note that I've never seen the download put in the top level install dir.  Even after the surprise download.  So `git status` is clean.  So perhaps it going in the wrong spot is a Windows-only issue?

**Comment by mhvk** [comment]
@jdavies-st - the top-level directory turned out to be `skyfield` downloading `Leap_Second.dat` separately, in the tests. I think we can solve that. The larger question is what how to handle out-of-date leap-second tables - whether it helps to move them when `Time` is explicitly used, or somehow check at each invocation whether the table is up to date). Anyway, let's move that discussion to #9497.
