### ISSUE TITLE
Column data reassignment resets description

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#10131]
When column data is reassigned, the original column description is reset to `None`.  I expected that the column description would not change.  Is this a bug?  Is there a way to change column data without changing the description?

```python
>>> from astropy.table import QTable
>>> t = QTable()
>>> t['a'] = np.arange(3)
>>> t['a'].info.description = 'Important data'
>>> print(t['a'].info.description)
Important data

>>> t['a'] = np.arange(3)**2
>>> print(t['a'].info.description)
None
```

**Comment by pllim** [comment]
Wouldn't the description be outdated if you change the column data? Not unreasonable to void it?

**Comment by larrybradley** [comment]
Perhaps.  But should there be some other way (e.g., method/attribute) to change the column data without changing the description?

**Comment by pllim** [comment]
What about `t.meta`?

**Comment by pllim** [comment]
Does it need to be attached to a column?

**Comment by taldcroft** [comment]
Use `t['a'][:] = np.arange(3)**2` for in-place setting.  See also https://astropy.readthedocs.io/en/latest/table/modify_table.html#in-place-versus-replace-column-update

**Comment by larrybradley** [comment]
Thanks, @taldcroft!  Somehow I missed that.
