### ISSUE TITLE
KeyError: 'independent_celestial_slices' (import aplpy)

### ISSUE THREAD

**Issue by stavroulak** [astropy/astropy#10144]
Hello!

I have this error while import aplpy.
<img width="581" alt="Screenshot 2020-04-14 at 7 31 37 PM" src="https://user-images.githubusercontent.com/15180553/79249998-bd9b2400-7e86-11ea-80b0-746b730ad32b.png">
Is there anything I can do?
Thanks for your time!

**Comment by Cadair** [comment]
This is an incompatibility between reproject and astropy 4.0.1. Either upgrade reproject to 0.7 or downgrade astropy to 4.0.0.

see #10084 and https://github.com/astropy/reproject/issues/224

**Comment by stavroulak** [comment]
It's ok. Thank you!
