### ISSUE TITLE
Feature request: auto-generate overview of config items for docs

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10146]
Following up on https://github.com/astropy/astropy/pull/10139#issuecomment-613689521: "it would be really good if searching for "astropy configuration" didn't just return how to do configuration, but also all possible things one can configure. It should be possible to auto-generate a nice list..."

Looking very quickly at https://github.com/astropy/astropy/blob/master/astropy/config/configuration.py, it would seem that just following `ConfigNamespace.__subclass__()` should do the trick (though after loading all astropy modules...).

**Comment by pllim** [comment]
@mhvk , can you please clarify with an example?

**Comment by mhvk** [comment]
I would like to have a page in our docs like below, and hopefully auto-generate so it doesn't get out of date!  Maybe some magic like the units listings is possible?

Configuration items
===============

astropy.io.fits
------------------

enable_record_valued_keyword_cards: ... description ...

astropy.utils.iers
----------------------
auto_max_age : ... description ...

**Comment by saimn** [comment]
I thought the default config file was automatically generated, but actually it is hardcoded here: https://github.com/astropy/astropy/blob/master/astropy/astropy.cfg 
So it has the list of items, but probably outdated (at least some io.fits ones are missing).

**Comment by mhvk** [comment]
Yes, `iers` stuff is missing too, but indeed auto-generating that would be useful, and it should not be difficult to then also include it in the docs.
