### ISSUE TITLE
Error in documentation for Sersic2D

### ISSUE THREAD

**Issue by Russell-Ryan** [astropy/astropy#10150]
### Description

The equation 

Γ(2𝑛)=2𝛾(𝑏𝑛,2𝑛)
on 

https://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.Sersic2D.html

is incorrect.  It should be Γ(2𝑛)=2𝛾(2n,𝑏𝑛).  

EDIT: Changed provided URL to point to `latest`.

**Comment by pllim** [comment]
Hello. Thanks for reporting this! Are you interested to submit a pull request to take credit for fixing it?

**Comment by allardbrain** [comment]
If @Russell-Ryan isn't able to right now, I can take this.

**Comment by pllim** [comment]
Go head, @allardbrain . Thanks!

**Comment by allardbrain** [comment]
Cool, I'll aim to have the PR submitted by 10pm Pacific Time on Friday 4/17.

**Comment by Russell-Ryan** [comment]
Yea, I don’t know how to do any of that... pull request and so on.

Sent from my iPhone

On Apr 16, 2020, at 6:19 PM, Erin Allard <notifications@github.com> wrote:

﻿

Cool, I'll aim to have the PR submitted by 10pm Pacific Time on Friday 4/17.

**Comment by allardbrain** [comment]
Needed to take a break from this, but working on submitting a new PR tonight.
