### ISSUE TITLE
reproject error

### ISSUE THREAD

**Issue by jpwgit** [astropy/astropy#10178]
Hi all, I was re-running some year-old code and came across a problem that I traced to reproject. Looks like this broke in between versions. Can you please check? Thanks

In [4]: from reproject import reproject_interp
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-1623c529c619> in <module>()
----> 1 from reproject import reproject_interp

/anaconda/lib/python3.6/site-packages/reproject/__init__.py in <module>()
     11 
     12 if not _ASTROPY_SETUP_:
---> 13     from .interpolation import reproject_interp
     14     from .spherical_intersect import reproject_exact
     15     from .healpix import reproject_from_healpix, reproject_to_healpix

/anaconda/lib/python3.6/site-packages/reproject/interpolation/__init__.py in <module>()
      3 Routines to carry out reprojection by interpolation.
      4 """
----> 5 from .high_level import *

/anaconda/lib/python3.6/site-packages/reproject/interpolation/high_level.py in <module>()
      3                         unicode_literals)
      4 
----> 5 from astropy.extern import six
      6 
      7 from ..utils import parse_input_data, parse_output_projection

ImportError: cannot import name 'six'

In [5]: from astropy.extern import six
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-0af035833b63> in <module>()
----> 1 from astropy.extern import six

ImportError: cannot import name 'six'

**Comment by bsipocz** [comment]
you need to update reproject, there is no compatibility issues with the latest releases.
