### ISSUE TITLE
Serialization of mixin columns can fail due to unexpected name clashes

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10215]
Simple example:
```
from astropy.coordinates import EarthLocation
from astropy import units as u
from astropy.table import Table
el = EarthLocation([0, 1]*u.deg, [0, 1]*u.deg)
q = [2., 3.]*u.m
t = Table([q, el], names=['x', 'el'])
t.write('a.fits', format='fits', overwrite=True)
Table.read('a.fits').colnames
# ['el']
# Oops, column 'x' disappeared.
```
The column only disappears when its name matches one of the `EarthLocation` components (which is why this was likely not caught earlier; I was trying to save `SphericalRepresentation` in `fits/tests/test_connect.py`, which also saves `lon` and `lat`, and they both disappeared).

The problem is in reading, not writing: `a.fits` does contain `x`. The same happens for `ecsv`, so it is likely in `serialize.py`.

@taldcroft - if you have any immediate clue, let me know.  I'm stuck in zoom for most of the day.

**Comment by mhvk** [comment]
Possibly the problem is one of the deletions in:
https://github.com/astropy/astropy/blob/ccb772fcad2bd0224b92dbf6702eca055aeec832/astropy/table/serialize.py#L254-L277

**Comment by taldcroft** [comment]
I'm looking at this.

**Comment by taldcroft** [comment]
This code is at my limit to understand, especially with the elegant but tricky recursion you put in.  However, I have some insight to the problem (thanks to VS code graphical debugger).  The fix below passes your example and table and io.ascii tests, but seems to cause a lot of fails in ASDF and YAML.  Ugh.  The upshot is that it needed to use the fully-qualified name like `el.x` instead of `x` when constructing the `x` data attribute for `el`.  This relates to the dodgy-but-mostly-working strategy of managing everything in this global `out` pseudo-table which gets fiddled with recursively.
```
--- a/astropy/table/serialize.py
+++ b/astropy/table/serialize.py
@@ -253,13 +253,15 @@ class _TableLite(OrderedDict):
 
 def _construct_mixin_from_columns(new_name, obj_attrs, out):
     data_attrs_map = {}
     for name, val in obj_attrs.items():
         if isinstance(val, SerializedColumn):
             if 'name' in val:
                 data_attrs_map[val['name']] = name
             else:
-                _construct_mixin_from_columns(name, val, out)
-                data_attrs_map[name] = name
+                out_name = f'{new_name}.{name}'
+                _construct_mixin_from_columns(out_name, val, out)
+                data_attrs_map[out_name] = name
 
     for name in data_attrs_map.values():
         del obj_attrs[name]
```

**Comment by mhvk** [comment]
Hey, I thought that was your code! Though `git blame` does assign it to me... Anyway, it looks like my hunch with the deleting is wrong and what you point out makes sense. (I should have a bit more time to look at the new failures in an hour or so - though I'll also need to see why my fix to representations for #9857 has come back to bite us in #10216... (the risks of doing things quickly for a feature freeze...).

**Comment by taldcroft** [comment]
New failures were unrelated, due to ASDF requiring a newer version.  Yay!  PR coming (after the dog walk), at least astropy/io astropy/table and astropy/time are all passing now.

**Comment by mhvk** [comment]
Super!

**Comment by taldcroft** [comment]
See #10222.
