### ISSUE TITLE
io.fits not reading pixel lists

### ISSUE THREAD

**Issue by wkerzendorf** [astropy/astropy#1024]
@iguananaut : I stumbled onto these pixellist fits format (example file https://www.dropbox.com/s/1tp3l8c02w8xvw8/gmos-s_bpm_EEV_22_3amp_v1_mosaic.pl) for bad pixel masks (it seems @perrygreenfield was involved in the creation - http://iraf.noao.edu/plio_1.html). It would be great if `io.fits` could read those - for now iraf can convert them to normal fits files, which is described in the link.

**Comment by astrofrog** [comment]
@chanley @wkerzendorf - do you have any updates on this format? I've marked this issue as a candidate for closing. If there are no more updates or requests for support, I'll close it.

**Comment by embray** [comment]
If nobody can give useful information on what these files are, how they're formatted, and what they're used for then there's nothing to be done...

Nobody else has asked for this either, though as @chanley pointed out there are probably lots of them floating around, and the dependence on IRAF in reading them is not going to be so great for future purposes...

**Comment by chanley** [comment]
Sorry, I haven't been paying much attention to astropy messages in a while.  The only spec information I have been able to find is here:

http://heasarc.gsfc.nasa.gov/docs/software/fitsio/compression/compress_image.html

Specifically in appendix C, section 6.

**Comment by chanley** [comment]
Help file for pixel list support in IRAF:

http://iraf.noao.edu/plio_1.html

**Comment by embray** [comment]
For posterity in case the spec vanishes:

```
The IRAF PLIO (Pixel List I/O) algorithm was developed to store image masks in a compressed form. The performance of this encoding is very good for typical masks consisting of isolated high or low values or extended regions at the same level. The worst case performance occurs when successive pixels have different values. Even in this case the encoding will only require one word (16 bits) per mask pixel, provided either the delta intensity change between pixels is usually less than 12 bits, or the mask represents a zero floored step function of constant height. The worst case cannot exceed npix*2 words provided the mask depth is 24 bits or less.

A good compromise between storage efficiency and efficiency of runtime access, while keeping things simple, is achieved if we maintain the compressed line lists as variable length arrays of type short integer (16 bits per list element), regardless of the mask depth. A line list consists of a series of simple instructions which are executed in sequence to reconstruct a line of the mask. Each 16 bit instruction consists of the sign bit (not used at present), a three bit opcode, and twelve bits of data, i.e.:

        +--+-----------+-----------------------------+
        |16|15       13|12                          1|
        +--+-----------+-----------------------------+
        |  |   opcode  |            data             |
        +--+-----------------------------------------+
The significance of the data depends upon the instruction. The instructions currently implemented are summarized in the table below.
     Instruction     Opcode           Description

        ZN            00        Output N zeros
        HN            04        Output N high values
        PN            05        Output N-1 zeros plus one high value
        SH            01        Set high value, absolute
        IH,DH         02,03     Increment or decrement high value
        IS,DS         06,07     Like IH-DH, plus output one high value
In order to reconstruct a mask line, the application executing these instructions is required to keep track of two values, the current high value and the current position in the output line. The detailed operation of each instruction is as follows:

ZN
Zero the next N (=data) output pixels.
HN
Set the next N output pixels to the current high value.
PN
Zero the next N-1 output pixels, and set pixel N to the current high value.
SH
Set the high value (absolute rather than incremental), taking the high 15 bits from the next word in the instruction stream, and the low 12 bits from the current data value.
IH,DH
Increment (IH) or decrement (DH) the current high value by the data value. The current position is not affected.
IS,DS
Increment (IS) or decrement (DS) the current high value by the data value, and step, i.e., output one high value.
The high value is assumed to be set to 1 at the beginning of a line, hence the IH,DH and IS,DS instructions are not normally needed for boolean masks. If the length of a line segment of constant value or the difference between two successive high values exceeds 4096 (12 bits), then multiple instructions are required to describe the segment or intensity change.
```

**Comment by saimn** [comment]
Given the discussion I think it's safe to close. We can still reopen if someone really need this.

**Comment by pllim** [comment]
c/c @SaraOgaz in case you come across this in your STAK work.

**Comment by perwin** [comment]
Having just come across this and noticing that no one seems to have provided an answer to the question "what are pixel-list files used for?", here's a partial answer. 

The IRAF stsdas.analysis.isophote task "ellipse", which fits ellipses to galaxy isophotes using the algorithm of Jedrzejewski  (1987, MNRAS, 226, 747), accepts masks in pixel-list format; in fact, if the data image filename ends in .imh or .fit (but not .fits) and there is a .pl file with the same base name, the latter will be automatically used as a mask. "Ellipse" is the de-facto standard for fitting galaxy isophotes (the other codes for doing this have never been publicly available), so this is a fairly significant use case. (I have several thousand .pl files sitting around in different directories and disks.)

Happily, "ellipse" will *also* accept integer FITS files as masks using the "dqf" (data-quality file) option, and .pl files can be converted to integer FITS file via the IRAF "imcopy" command, so there is a workaround.

**Comment by pllim** [comment]
@perwin , `ellipse` task has been deprecated; @ibusko had done the work to port it into Python and it will be part of `photutils` after astropy/photutils#532 is merged (c/c @larrybradley).

**Comment by perwin** [comment]
@pllim -- that's nice to hear, actually; I look forward to its being available.
