### ISSUE TITLE
Add equivalency for converting relativistic redshift to velocity

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#10240]
As described in https://github.com/astropy/astropy/pull/10185#discussion_r416867984, it would be useful to have public equivalencies for converting between relativistic redshift and velocity.

**Comment by pllim** [comment]
tl;dr -- Does it depend on cosmological model?

**Comment by adrn** [comment]
I think here we mean a Doppler redshift, not cosmological

**Comment by pllim** [comment]
So, you mean to expand what this can take?

https://github.com/astropy/astropy/blob/60ab27c6da71aa289c7bf0e69121856a03fddc30/astropy/units/equivalencies.py#L437

**Comment by pllim** [comment]
Was just looking for this today. Is there a chance this will happen soon?
