### ISSUE TITLE
DOC: Is ASDF schema page outdated?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10267]
### Description

https://docs.astropy.org/en/latest/io/misc.html#schemas does not include all the schemas in `astropy/io/misc/asdf/data/schemas/astropy.org/astropy/`.

If the page is indeed outdated, how do we ensure it stays in sync going forward?

### Expected behavior

There is a 1-to-1 mapping between schema in package data and the documentation.

### Actual behavior

For example, `transform/units_mapping-1.0.0.yaml` is missing from the list.

cc @nden @cshanahan1 @jdavies-st @eslavich

**Comment by mhvk** [comment]
Changed milestone to 4.1.1 since not release critical (though obviously important to fix!)

**Comment by pllim** [comment]
I'll just remove the milestone. We usually don't milestone issues anyway.

**Comment by eslavich** [comment]
We have a test in asdf-standard that confirms that every schema is linked somewhere in the docs:

https://github.com/asdf-format/asdf-standard/blob/master/tests/test_docs.py#L9

Something like that may be helpful?

**Comment by pllim** [comment]
No longer relevant. It is now `asdf-astropy` package.
