### ISSUE TITLE
Seamless integration of WCS with coordinates

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#10277]
### Description
WCS objects should work with astropy coordinates, i.e. `all_world2pix` should accept a coordinate (vector) on input and `all_pix2world` should return a coordinate object.

Here is an example:
```
from astropy.coordinates import SkyCoord
from astropy import wcs
import astropy.units as u

# For this example, I build a WCS from scratch so that the issue can be run easily
# but in reality I would load a WCS from a fits image
w = wcs.WCS(naxis=2)
w.wcs.crpix = [165.5,-34.7]
w.wcs.cdelt = [-0.066667, 0.066667]
w.wcs.crval = [0, -90]
w.wcs.ctype = ["RA---AIR", "DEC--AIR"]
w.wcs.set_pv([(2, 1, 45.0)])
```
I can do:
```
myobj = SkyCoord(*w.all_pix2world(123, 234, 0), unit=u.deg)
```
but would it not be much easier if the WCS already returned a coodiante?

The same is true the other way around:
```
twhya = SkyCoord.from_name('TW Hya')
w.all_world2pix(twhya.ra.deg, twhya.dec.deg, 0)
```
The following would be a lot more integrated, but fails:
```
w.all_world2pix(twhya, 0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-184-7c8278221f9c> in <module>
----> 1 w.all_world2pix(twhya)

/nfs/melkor/d1/guenther/soft/anaconda/envs/ciao412/lib/python3.7/site-packages/astropy/wcs/wcs.py in all_world2pix(self, tolerance, maxiter, adaptive, detect_divergence, quiet, *args, **kwargs)
   1859                 adaptive=adaptive, detect_divergence=detect_divergence,
   1860                 quiet=quiet),
-> 1861             'input', *args, **kwargs
   1862         )
   1863 

/nfs/melkor/d1/guenther/soft/anaconda/envs/ciao412/lib/python3.7/site-packages/astropy/wcs/wcs.py in _array_converter(self, func, sky, ra_dec_order, *args)
   1310             "dimension, and the origin argument). Instead, {2} arguments were "
   1311             "given.".format(
-> 1312                 self.naxis, self.naxis + 1, len(args)))
   1313 
   1314     def all_pix2world(self, *args, **kwargs):

TypeError: WCS projection has 2 dimensions, so expected 2 (an Nx2 array and the origin argument) or 3 arguments (the position in each dimension, and the origin argument). Instead, 1 arguments were given.

```
### Additional context

We don't want to break backwards compatibility for a function as basic as this one, but we could do the following:

- for `all_world2pix` check if input is an instance of SkyCoord and treat that correctly
- for `all_world2pix`have a keyword like `return_coord_object = True`.

Note that this does not collide with APE14, which adds an WCS interface layer, but does not prohibit lower-level, existing WCS implementations to understand coordinates.

**Comment by astrofrog** [comment]
@hamogu - could you clarify a little further why using the APE 14 API, which already exists on FITS WCS would not be sufficient? I think that the ``w.pixel_to_world`` and ``w.world_to_pixel`` methods which already exist on your object might become the preferred user API, so it's not clear to me what the benefit would be to update the historical API? Note that SkyCoord also has a ``to_pixel`` and ``from_pixel`` method too.

Just to be clear, I agree that we *could* make the change in a backward-compatible way, and we could even delegate in those cases to the APE 14 API behind the scenes - I guess the question is whether we want to do this if it will no longer be the recommended user API?

**Comment by hamogu** [comment]
Mmm. That probably means I should upgrade my coordinate-foo and read the docs again instead of just using the functions that I happen to know.

**Comment by astrofrog** [comment]
Just FYI, there is currently a refactor of the WCS docs in progress in https://github.com/astropy/astropy/pull/10058
