### ISSUE TITLE
Adjust get_body to take into account location on Earth

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10271]
In https://github.com/astropy/astropy/issues/10230#issuecomment-622655253, @mkbrewer noted that our `solar_system._get_apparent_body_position`, which is used in `get_body`, corrects for travel time to the center of the Earth rather than the actual location of the observer. While in general the resulting differences of a ms is not going to affect any of the locations of the planets at a level one likely cares about, the actual travel time is iterated on until it is less than `10 ns`, which is suggesting better precision. And the [docstring for `get_body`](https://docs.astropy.org/en/latest/api/astropy.coordinates.get_body.html#astropy.coordinates.get_body) also seems to suggest the actual location of the observer is used. cc @StuartLittlefair 

Also, crossref https://github.com/astropy/astropy/issues/10230#issuecomment-622659492, in which @ayshih mentions a sunpy routine that calculates light-travel times for an arbitrary observer.

**Comment by mkbrewer** [comment]
More like10 ms.
