### ISSUE TITLE
Issue with custom equivalency involving use of a constant

### ISSUE THREAD

**Issue by cosimoNigro** [astropy/astropy#10273]
### Description

I obtain an incorrect conversion when involving `astropy.constants` (h) in a custom equivalency

### Snippet to reproduce
```python
import astropy.units as u
import numpy as np
from astropy.constants import m_e, h

mec2 = m_e.to("erg", equivalencies=u.mass_energy())
epsilon_equivalencies = [
    (u.Hz, u.Unit(""), lambda x: h * x / mec2, lambda x: x * mec2 / h)
]
nu = np.logspace(23, 28, 10) * u.Hz
# dimensionless energy in electron rest mass energy units
epsilon = (h * nu / mec2).to("")
print("manual conversion: ", epsilon)

epsilon = nu.to("", equivalencies=epsilon_equivalencies)
print("equivalencies conversion: ", epsilon)
```
The output reads
```bash
manual conversion:  [8.09329979e+02 2.90858114e+03 1.04528986e+04 3.75657700e+04
 1.35004377e+05 4.85180576e+05 1.74364858e+06 6.26634810e+06
 2.25200874e+07 8.09329979e+07]
equivalencies conversion:  [8.09329979e-05 2.90858114e-04 1.04528986e-03 3.75657700e-03
 1.35004377e-02 4.85180576e-02 1.74364858e-01 6.26634810e-01
 2.25200874e+00 8.09329979e+00]
```
The difference is a factor `1e-7`, which is exactly the factor between `h` in SI and cgs units.
The issue can be avoided by explicitly converting h in cgs inside the equivalency
```python
epsilon_equivalencies = [
    (u.Hz, u.Unit(""), lambda x: h.cgs * x / mec2, lambda x: x * mec2 / h.cgs)
]
```
Why the equivalency cannot handle the simplification correctly?

### System Details

Darwin-19.4.0-x86_64-i386-64bit
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.1
astropy 4.0.1.post1
Scipy 1.4.1

Have I misunderstood the use of custom equivalencies?
Thank you!

**Comment by pllim** [comment]
I cannot explain why it is this way, but if you look inside

https://github.com/astropy/astropy/blob/8e19d39293261d9fbc1ff8cc173fc95f99c1ccca/astropy/units/equivalencies.py#L105

or any other ones in that file, the functions do explicit conversions to certain units before calculations. So, your casting of `h` to CGS is the way to go.

Maybe @mhvk remembers why or can point to someone who can explain the design. Thanks!

**Comment by mhvk** [comment]
@pllim is right - the conversion functions you provide in equivalencies should not use any quantities or constants themselves - they are used right inside the unit conversion machinery, so if one uses units, the risk is great that you get infinite recursion. In your case, since you convert `m_e` to the cgs "erg" unit, using `h.cgs` is indeed appropriate (if you used "J" it would be `h.si`, obviously).

Note that in your calculation of mec2, you should also use `.to_value` instead of `.to`, for the same reason.

**Comment by mhvk** [comment]
Apart from trouble-shooting, could you suggest a place where we could improve the documentation? There is a relevant bit at the end of https://docs.astropy.org/en/latest/units/equivalencies.html#writing-new-equivalencies, but is this perhaps something that is clear only now that you read our answers? Or did you not find this piece of documentation? Suggestions welcome. (And PRs even more so!)

**Comment by cosimoNigro** [comment]
@mhvk, yes I checked that part of the documentation, not carefully enough though.
On a second look in https://docs.astropy.org/en/latest/units/equivalencies.html#a-slightly-more-complicated-example-spectral-doppler-equivalencies
it is shown that `values` have to be used in the functions specifying the back and forth conversion.
I incorrectly assumed that the custom conversion could handle units simplification, this is why I expected `h * x / mec2` to be automatically reduced to `u.Unit("")`.

Maybe it would help adding a line in the docs specifying that the functions for the custom conversion have to work without units. 

Thank you both (thanks also to @pllim), the issue can be closed.
