### ISSUE TITLE
pix2world which pixel reference system?

### ISSUE THREAD

**Issue by thewoz** [astropy/astropy#10315]
Hi,

I'm try to use the function pix2world. 
what I can not understand is in which pixel reference system I should give the pixels coordinates to convert it

Since for standard the the origin pixel of an image is defined as the pixel (0, 0) in the upper left corner instead in fit format the origin pixel of is defined as pixel (1, 1) in the lower left corner.

in which system I need to pass to pix2world the coordinate of an object?

thanks

**Comment by thewoz** [comment]
I get it.

When you say that `all_pix2world` and `wcs_pix2world` can uses the FITS convention or the other one. Is not only that the first pixels is (1,1) or (0,0) but also that the vertical axis is flipped?
Moreover how I can control the `origin` keyword?
And this is true also for `all_pix2world` and `wcs_pix2world`?

**Comment by nden** [comment]
`all_pix2world` evaluates the entire WCS transform, including distortions.
`wcs_pix2world` evaluates only the core FITS transform, without distortions.
Normally you will call `all_pix2world`. They both accept a keyword `origin` which controls the convention for the first pixel, for example `all_pix2world(x, y, 1)`, where 1 is the origin. Alternatively you can use `all_pix2world(x, y, 0)` to specify that the inputs are 0-based. 

As for the vertical axis - you may be thinking of visualization. In ds9, for example, the first element of the array is in the lower left corner. In matplotlib you can control this. Does this help?

**Comment by thewoz** [comment]
Ok perfect,
I have just three questions:

1) if I open a image with for example Gimp and I take the coordinate of an object, may be `(423,534`) at `all_pix2world(x, y, 0)` I need to pass `all_pix2world(423-0.5, 534-0.5, 0)` since the `(0,0)` in Gimp is the the upper left corner and for AstroPy is the center of the upper left corner.

2) `all_world2pix` and `wcs_world2pix` I can control the `origin` but also here if I'm using the 0-based origin I need to add 0.5 to the resulting coordinates to have a perfect match with what I will seen in the image opened whit Gimp.

3) For the vertical axis what I would like to understand is that if I using a 0-based origin the vertical axis is top down increasing and vice versa if I'm using the 1-based origin the vertical axis is down top increasing

**Comment by thewoz** [comment]
So this is for example the coordinate of the center of the image.
For a standard image program the center have coordinate (3,2) in a 0-based origin  
instead for a FIT with 0-based origin it have (3.5,2.5) coordinate.
Now if I call the `all_world2pix` the answer would be (2.5,1.5) I check this.
So I should ad +0.5 to have a match with the image program

![unnamed](https://user-images.githubusercontent.com/907951/81183457-7b5d9200-8faf-11ea-951d-93961ef1f297.png)

**Comment by nden** [comment]
In the 0-based image system pixel (3, 2) corresponds to (3.5, 2.5) in FITS 1-based system. You will call it with `ra, dec = all_pix2world(3.5, 2.5, 1)`. ra, dec are the world coordinates for your image pixel (3, 2).

**Comment by thewoz** [comment]
ok great!

but what about `all_world2pix`? have the same behaviour of `all_pix2world`?

**Comment by nden** [comment]
Yes, they are consistent. IN that case if `origin=1` the result is 1-based pixel cooridnates.

**Comment by pllim** [comment]
Looks like the question has been sufficiently answered?

**Comment by thewoz** [comment]
Yes for me is closed
Thanks a lot nden
ps: maybe can be useful put this kind of information in the documentation

**Comment by pllim** [comment]
It is kinda explained in https://docs.astropy.org/en/latest/wcs/index.html#loading-wcs-information-from-a-fits-file but if you think it can be done better, please submit a pull request. Thanks!

**Comment by thewoz** [comment]
> In the 0-based image system pixel (3, 2) corresponds to (3.5, 2.5) in FITS 1-based system. You will call it with `ra, dec = all_pix2world(3.5, 2.5, 1)`. ra, dec are the world coordinates for your image pixel (3, 2).

In the AstroPy 0-based image system the pixel (2.5, 1.5) corresponds to (3.5, 2.5) in FITS 1-based system. If I call `ra, dec = all_pix2world(3.5, 2.5, 1)` I will get the world coordinates for my image pixel (2.5, 1.5) not for position pixel (3,2) in the 0-based image system

**Comment by nden** [comment]
If I understood the pictures above correctly, the integer values in the image system correspond to the corner of the pixel while in astropy, both 0- and 1- based, the integer values correspond to the center of the pixel. That's why I had them shifted by .5 px in both directions.

**Comment by thewoz** [comment]
You understood the pictures above correctly. call` ra, dec = all_pix2world(3.5, 2.5, 1)` I will get the world coordinates for the point (2.5, 1.5) in the 0-base AstroPy image system, of course of the (3.5, 2.5) for the 1-base AstroPy image system and also for the point (3,2) in the 0-base image (green in figure) reference system
