### ISSUE TITLE
TimeDelta comparison with float "works"

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10355]
Found by @paulray in https://github.com/nanograv/PINT/pull/702:
```
from astropy.time import TimeDelta

TimeDelta(1) < 10
# True
```
The reason is that `Time` tries to initiate an instance of itself in doing the comparison, so it treats numbers as `days` (default format for `TimeDelta`). I think the easiest is to be a bit less generous and simply only accept for a comparison what we actually know works, i.e., another `Time` or, for `TimeDelta`, a `Quantity`.

p.s. I see the blame is mine - clearly, in 2013, I was too enchanted with duck typing...

https://github.com/astropy/astropy/blob/223d9c38114af67743081eabfe96566067ac8bfe/astropy/time/core.py#L2018-L2027

**Comment by Iamsoto** [comment]
Hi, I'm new here and trying to help out.

Mind if I make an attempt to fix this? The solution  appears not too difficult (for now)

**Comment by pllim** [comment]
@Iamsoto , there is no rule against trying. For a bug fix, usually new test(s) need to be added as well to prevent regression. FYI.

**Comment by mhvk** [comment]
@Iamsoto - indeed, it should not be too difficult, just an explicit check that `other` is a `Quantity`. And, yes, a PR would be very welcome!!

**Comment by Iamsoto** [comment]
Sweet! Thanks guys!

So then I have just two more questions.

1) For clarification, a Time object can _only_ be compared with another Time object.
And a TimeDelta Object can only be compared with another TimeDelta object `or` A Quantity object. Do I understand that right?

2) It looks like a similar behavior occurs with Time and arithmatic. That is: 
```
  	dt1 = datetime(1233, 1, 1, 0, 0)
	t1 = Time(dt1, scale="tai")
        t1 - 1
        >>1232-12-31 00:00:00 
```

Is this expected behavior or should it also be changed? 

Thanks!

**Comment by mhvk** [comment]
@Iamsoto - ah, so you found what looks like another bug already...  Indeed, it would mean replacing all those. 

Though it makes me wonder both whether fixing it will cause regressions that perhaps are not worth it. Let me ping @taldcroft here to see what he thinks about the risk for regression vs the rather bug-prone behaviour (my fault...).

p.s. I checked and with the current code also things like the following work, perhaps unexpectedly:
```
In[12]: Time.now() -[1,2,3]                                                                                                                                 
Out[12]: 
<Time object: scale='utc' format='datetime' value=[datetime.datetime(2020, 5, 20, 0, 12, 42, 877143)
 datetime.datetime(2020, 5, 19, 0, 12, 42, 877143)
 datetime.datetime(2020, 5, 18, 0, 12, 42, 877143)]>

In [13]: Time('J2000') == 'J2000'                                                                                                                            
Out[13]: True

In [14]: Time('J2000') == 'J2001'                                                                                                                            
Out[14]: False
```

But not
```
In [15]: Time('J2000') - 'J2001'
TypeError: unsupported operand type(s) for -: 'Time' and 'str'
```

**Comment by taldcroft** [comment]
@mhvk - ahh.. about the regressions.  We do actually take advantage of this "bug" of allowing float in `Time` arithmetic in CXC code, where the float value is taken as days.  I suspect that other users might have stumbled into this. My inclination is to leave this, for our organization (including engineers and other non-scientist users/developers) it is a feature.  :smile:

**Comment by taldcroft** [comment]
I also think that given the precedent that a plain float for `TimeDelta` is in days, that the current behavior of casting any comparison value with `TimeDelta` is consistent, and maybe even reasonable. 

In my coding I use the pattern of duck-typing / casting *all the time* to allow a variety of input types, i.e.:
```
def do_something(my_time, my_delta_time):
    my_time = Time(my_time)
    my_delta_time = TimeDelta(my_delta_time)
    ...
```

**Comment by paulray** [comment]
I see what you are saying, but given that the SI unit of time is seconds, it is pretty unexpected (to me, at least) that `TimeDelta(1.0)` is a 1 day.

**Comment by mhvk** [comment]
This is tricky; for time differences indeed the logical unit is second, while for absolute times (which are really dates), it is clearly days (second being a derived unit). It is a bit like wondering whether for phases radian, cycles, or dimensionless is the most logical unit... :smiley_cat: 

But I guess the real question now is about the balance between the risk of subtle bugs with the present approach vs breaking existing code by requiring users to be more explicit.

**Comment by pllim** [comment]
Hah. Do we need a "Bug that is actually a feature" label? 😉

**Comment by taldcroft** [comment]
I'm not sure what to say except that the easiest thing is to accept the imperfect status quo and do nothing. 

But I guess I would not object if someone wanted to take the trouble to introduce DeprecationWarnings saying that comparing with floats and/or doing float arithmetic will not work in a couple of releases.

**Comment by Iamsoto** [comment]
Could I do the honors?

**Comment by taldcroft** [comment]
@lamsoto - go for it!

**Comment by Iamsoto** [comment]
Cool! How does a warning like this look like? 

```
def _time_comparison(self, other, op):
        """
        If other is of same class as self, or quantity compare difference in self.scale.
        Otherwise, throw warning
        """
        if other.__class__ is not self.__class__ :
            if not isinstance(other, Quantity):
                warnings.warn("""TimeDelta Comparisons with this object type is deprecated in favor of 
                    manually casting this object to either TimeDelta or Quantity""", AstropyDeprecationWarning)
            
            try:
                other = self.__class__(other, scale=self.scale)
            except Exception:
                # Let other have a go.
                return NotImplemented
```

**Comment by mhvk** [comment]
@Iamsoto - pretty good, though I would for now put the warning *after* the `try/except`, since if the instantiation of the class fails, one probably already gets a `TypeError`, so no need to warn (and in principle this might be a class that can actually deal with `TimeDelta`, in which case there should not be a warning).

Note that I think it might be good to "centralize" this a bit, so you only have to add one warning. It may not be crazy to create a private class method, say `TimeDelta._from_quantity`, which you use everywhere where needed.

**Comment by Iamsoto** [comment]
Ah interesting Makes sense. 
And then the Time class can only compare/ do Arithmatic with other time objects right?

I'll get to work on that

**Comment by mhvk** [comment]
@Iamsoto - hmm, as I think more about this, I am getting closer to @taldcroft's suggestion to just leave things be. For instance, I think you'd still want to allow comparison with `0` (say, `time_delta < 0`) - this is special-cased in `Quantity` as well (it uses `astropy.units.quantity_helpers.converters.can_have_arbitrary_unit`). It may be more profitable to work on another issue....

**Comment by mhvk** [comment]
Yes, indeed. Thanks, @maxnoe! You got two issues with one PR -- and always good to close old issues!
