### ISSUE TITLE
Sphinx directives visible in rendered docs

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#10353]
Neither the example directive commands nor `doctest-requires` should be visible in the rendered docs

https://docs.astropy.org/en/latest/coordinates/satellites.html#astropy-coordinates-satellites

**Comment by pllim** [comment]
Good catch! I think it is something subtle like having the directive after a paragraph with colon or something.

**Comment by ayshih** [comment]
The double colon, specifically, because that signals that the following block is code, even if it's a directive.  The double colons should be changed to single colons.

**Comment by pllim** [comment]
@ayshih , do you plan to have a PR out? Just want to clarify to avoid duplicate work.

**Comment by ayshih** [comment]
No, I wasn't volunteering. =)
