### ISSUE TITLE
BinTableHdu Data is Available at Surprising Times

### ISSUE THREAD

**Issue by medley56** [astropy/astropy#10381]
### Description
HDU data is available at surprising times.

### Expected behavior
I expected that either the HDU data is never available outside the context manager or that `hdus.readall()` would cause the same behavior as accessing `hdus[1].data`. See the attached example.

### Actual behavior

See attached script for an example.

### Steps to Reproduce

```python
import numpy as np
import os
from astropy.io import fits
from astropy.io.fits.hdu.hdulist import fitsopen

filepath = os.path.expanduser("~/Downloads/foo.fits")
c1 = fits.Column(name='a', array=np.array([1, 2]), format='K')
c2 = fits.Column(name='b', array=np.array([4, 5]), format='K')
c3 = fits.Column(name='c', array=np.array([7, 8]), format='K')
t = fits.BinTableHDU.from_columns([c1, c2, c3])
t.writeto(filepath)

print("Let's open that file and then try to access the data.")
with open(filepath, mode='rb') as fo:
    hdus = fitsopen(fo, mode='readonly', lazy_load_hdus=False)
    
try:
    hdus[1].data
except ValueError as e:
    print("That's an exception!")
    print("Ok, cool, so the data isn't available outside of the context manager. Makes enough sense."
          "Maybe setting lazy loading to False doesn't mean exactly what I thought.")

with open(filepath, mode='rb') as fo:
    hdus = fitsopen(fo, mode='readonly', lazy_load_hdus=False)
    hdus[1].data
print("This should raise an exception, right? I mean, I didn't actually _do_ anything")
hdus[1].data
print('Wait... what? Why did that work? Oh, I must have to read all the HDUs before they are available '
      'outside the context manager.')

print('Well, surely we can just read all the HDUS into memory and then they will be accessible outside'
      'of the context manager, right?')
with open(filepath, mode='rb') as fo:
    hdus = fitsopen(fo, mode='readonly', lazy_load_hdus=False)
    hdus.readall()

try:
    hdus[1].data
except ValueError as e:
    print("WUT?")
    raise
```

### System Details

macOS-10.14.6-x86_64-i386-64bit
Python 3.8.2 (default, Apr  3 2020, 16:45:01) 
[Clang 10.0.1 (clang-1001.0.46.4)]
Numpy 1.18.2
astropy 4.0.1.post1
Scipy 1.4.1

**Comment by saimn** [comment]
Yes, I think `lazy_load_hdus` doesn't mean what you think it means. There are several stage of "lazy loading":
- loading HDU objects from the `HDUList`. When `lazy_load_hdus=True` (default) HDU objects are created only when you access them.

**Comment by saimn** [comment]
Yes, I think `lazy_load_hdus` doesn't mean what you think it means. There are several stage of "lazy loading":

- loading HDU objects from the `HDUList`. When `lazy_load_hdus=True` (default) HDU objects are created only when you access them:
```
In [8]: with fitsopen(filepath, lazy_load_hdus=True) as hdul: 
   ...:     pass                                                               
In [9]: len(hdul[0].header)                                                     
Out[9]: 4
In [10]: len(hdul[1].header)                                                    
...
IndexError: HDU not found, possibly because the index is out of range, or because the file was closed before all HDUs were read
```
Here with `lazy_load_hdus=True` the first extension is not loaded. 
And `lazy_load_hdus=False` or `.readall` will force loading all the HDUs when reading the file, *but not the data*.

- then there is a lazy loading of the data. The data is loaded only if you access the `.data` attribute. Which explains why only your second example, with `hdus[1].data`, does not raise an exception. when the data has been loaded it will be accessible after the context manager.

**Comment by medley56** [comment]
@saimn So is there a way to eager load the entire FITS file so it's available outside the context manager for reading (obviously not for writing, that can't work)? I mean, I guess I could iterate through all the HDUs and try to load the data for each one but that feels janky. I figured `.readall()` would do that but it sounds like it only loads the HDU, not the data inside it.

**Comment by saimn** [comment]
In this case I think the simplest would be to do a deepcopy of the HDUList:
```
In [7]: with fits.open('astropy/io/fits/tests/data/test0.fits') as hdul: 
   ...:     hdul = copy.deepcopy(hdul) 
```

**Comment by saimn** [comment]
Closing since I think there is no real bug here.
