### ISSUE TITLE
Spectral Coord tries to convert target to ICRS (even when it can't)

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#10399]
When a spectral coord is constructed with a target (i.e. from the celestial axes of a WCS) but not an observer, and that target coordinate is unable to be transformed to ICRS it errors.

I discovered this in the NDCube test suite, and am currently unable to reproduce on its own. Opening this so I don't forget and so that it blocks 4.1.

**Comment by Cadair** [comment]
For the record this issue seems to not exist with #10398

**Comment by pllim** [comment]
But #10398 is a refactoring. Can that still go into 4.1 in time?

**Comment by Cadair** [comment]
I don't know if that's the best solution for the release, just saying that it fixes it :grinning:

**Comment by astrofrog** [comment]
If it's the only way to fix the issue then #10398 would be a bug fix, right? :thinking:

**Comment by astrofrog** [comment]
Ok so I think https://github.com/astropy/astropy/pull/10400 should fix this and is probably the best fix for 4.1, with #10398 a better fix (but also general refactoring) best left to 4.2.
