### ISSUE TITLE
poisson_confidence_interval with kraft-bourrows-nousek fails with integer input

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#10408]
### Description

The routines for Poisson confidence intervals are made for the Poisson distribution which is relevant when counting something (e.g. photons). Thus, it should work when an integer number
is passed in. 

### Expected behavior

Calculate statistics

### Actual behavior

For N > 100, i.e. when the calculation is run with mpmath, (for N< 100 scipy is used if available), an error is raised when n is an integer. It does work though if n is a float.

### Steps to Reproduce

```
In [1]: from astropy.stats import poisson_conf_interval                                               

In [2]: poisson_conf_interval(n=160, background=154.543, confidence_level=.95, interval='kraft-burrows
   ...: -nousek')                                                                                     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-bfdb3197612a> in <module>
----> 1 poisson_conf_interval(n=160, background=154.543, confidence_level=.95, interval='kraft-burrows-nousek')

~/code/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    533                     warnings.warn(message, warning_type, stacklevel=2)
    534 
--> 535             return function(*args, **kwargs)
    536 
    537         return wrapper

~/code/astropy/astropy/stats/funcs.py in poisson_conf_interval(n, interval, sigma, background, confidence_level)
    751         if np.any(background < 0):
    752             raise ValueError('Background must be >= 0.')
--> 753         conf_interval = np.vectorize(_kraft_burrows_nousek,
    754                                      cache=True)(n, background, confidence_level)
    755         conf_interval = np.vstack(conf_interval)

~/anaconda3/envs/astropy/lib/python3.8/site-packages/numpy/lib/function_base.py in __call__(self, *args, **kwargs)
   2089             vargs.extend([kwargs[_n] for _n in names])
   2090 
-> 2091         return self._vectorize_call(func=func, args=vargs)
   2092 
   2093     def _get_ufunc_and_otypes(self, func, args):

~/anaconda3/envs/astropy/lib/python3.8/site-packages/numpy/lib/function_base.py in _vectorize_call(self, func, args)
   2159             res = func()
   2160         else:
-> 2161             ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
   2162 
   2163             # Convert args to object arrays first

~/anaconda3/envs/astropy/lib/python3.8/site-packages/numpy/lib/function_base.py in _get_ufunc_and_otypes(self, func, args)
   2119 
   2120             inputs = [arg.flat[0] for arg in args]
-> 2121             outputs = func(*inputs)
   2122 
   2123             # Performance note: profiling indicates that -- for simple

~/code/astropy/astropy/stats/funcs.py in _kraft_burrows_nousek(N, B, CL)
   1273                                  'large.')
   1274     if HAS_MPMATH:
-> 1275         return _mpmath_kraft_burrows_nousek(N, B, CL)
   1276 
   1277     raise ImportError('Either scipy or mpmath are required.')

~/code/astropy/astropy/stats/funcs.py in _mpmath_kraft_burrows_nousek(N, B, CL)
   1179     from mpmath import mpf, factorial, findroot, fsum, power, exp, quad
   1180 
-> 1181     N = mpf(N)
   1182     B = mpf(B)
   1183     CL = mpf(CL)

~/anaconda3/envs/astropy/lib/python3.8/site-packages/mpmath/ctx_mp_python.py in __new__(cls, val, **kwargs)
     75         else:
     76             v = new(cls)
---> 77             v._mpf_ = mpf_pos(cls.mpf_convert_arg(val, prec, rounding), prec, rounding)
     78             return v
     79 

~/anaconda3/envs/astropy/lib/python3.8/site-packages/mpmath/ctx_mp_python.py in mpf_convert_arg(cls, x, prec, rounding)
     94                 return a
     95             raise ValueError("can only create mpf from zero-width interval")
---> 96         raise TypeError("cannot create mpf from " + repr(x))
     97 
     98     @classmethod

TypeError: cannot create mpf from 160
```
Note that passing a float works:
```
In [7]: poisson_conf_interval(n=160., background=154.543, confidence_level=.95, interval='kraft-burrow
   ...: s-nousek')                                                                                    
Out[7]: 
array([[ 0.        ],
       [30.30454909]])
```

and so does an integer with a smaller number:
```
In [8]: poisson_conf_interval(n=16, background=15.4543, confidence_level=.95, interval='kraft-burrows-
   ...: nousek')                                                                                      
Out[8]: 
array([[ 0.        ],
       [10.02142828]])
```

### System Details

macOS-10.13.6-x86_64-i386-64bit
Python 3.8.2 (default, Mar 26 2020, 10:43:30) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.1
astropy 4.2.dev24+g441486c8c
Scipy 1.4.1

**Comment by Iamsoto** [comment]
Hi!
new here and trying to help!

It looks like a similar issue was raised with [9596](https://github.com/astropy/astropy/issues/9596)
It was commented that mpf has an issue when background and N are close together...

I will take a look at the source code and see what I can find!

**Comment by hamogu** [comment]
@Iamsoto Welcome! I had forgotten about #9596 although I posted a similar problem there, too. Looking back, I think there are different things going on:
- mpmath has (for good reasons!) different rules for converting integers to floats. Normal python will do that in a simple `2/3 = 2.0/3.0=1.5`. mpmath will not  convert because it could become 1.4999999999). That type of loss of precision is probably OK for astronomers, so we should make sure the function works with integers and floats. I think that's relatively easy.
- The function is not tested enough. We probably need more tests for a larger range of input numbers to make sure we catch things like this. 
- The numerics are really a problem for large numbers (or large differences in numbers). This might need more testing (to select mpmath or scipy in the appropriate cases) and might also mean to change the docs and issue a warning when the function is used outside the range where it works. (The formula is for Poisson statistics. For large numbers, one could use a Gaussian approximation, so this formula does not have to work for arbitrarily large number.) This is more difficult, because it involves, cods, docs, testing and a scientifically based decision what's best to do.

I would suggest to deal with the problem in order, i.e. address the float/integer conversion in a pull request (with some tests) on its own. If you want to delve any further, you can always open a second pull request with more changes, but smaller pull requests are easier to write, easier to review, and faster to merge so don't put too much into your first one!

Thanks for helping and let me know if you run into any problem!

**Comment by Iamsoto** [comment]
I think I got something

`N` is defined as `numpy.int64` when passed to  `def _mpmath_kraft_burrows_nousek(N, B, CL):` 

I'll need to double check, but I believe this happens because of the np.vectorize() function, line 753:
```
conf_interval = np.vectorize(_kraft_burrows_nousek,
                                     cache=True)(n, background, confidence_level)
```

It appears mpmath.mpf cannot convert from np.int64. I wrote an issue about this [here](https://github.com/fredrik-johansson/mpmath/issues/539) 

In the mean time, we can convert the numpy values to their pythonic equivalencies with something like this:
```
    N = mpf(N.item())
    B = mpf(B.item())
    CL = mpf(CL.item())
```
If you think this is a good enough solution, I'll go ahead and make this pull request (with some tests!)

**Comment by hamogu** [comment]
I have to admit that I don't know the answer - if I did know, I would have written a PR myself! But this sounds like a promising lead to me.

So, I suggest that you make a PR with some tests. If the tests pass, then we know it works, if they don't then we see where is fails. Does that make sense?

**Comment by Iamsoto** [comment]
Yep! 

I'll start writing them.
