### ISSUE TITLE
Regression in astropy 4.0.1 with regard to Time objects in Tables

### ISSUE THREAD

**Issue by bastianbeischer** [astropy/astropy#10417]
### Description

The problem is described in https://github.com/nanograv/PINT/issues/651

In particular, the comment https://github.com/nanograv/PINT/issues/651#issuecomment-633543751 contains a small script that can be used to reproduce the problem, which I'll paste below.

Basically it appears that Time instances can't be stored and extracted from a Table as they are. When running the script an error is reported. This problem seems to have been introduced in https://github.com/astropy/astropy/pull/9969. In particular, the problem disappears when commenting these lines:

```python
        # Hack from #9969 to allow passing the location value that has been
        # collected by the TimeAstropyTime format class up to the Time level.
        # TODO: find a nicer way.
        # print(self._time._location)
        if hasattr(self._time, '_location'):
            # from pudb import set_trace; set_trace(paused=True)
            self.location = self._time._location
            del self._time._location
```

This also appears to be related to lists of length 1. When using two elements in the initialization list there is no problem.

### Expected behavior

The script (below) should run without an error.

### Actual behavior

An exception is raised:

```
Traceback (most recent call last):
  File "/home/beischer/.local/lib/python3.8/site-packages/astropy/time/core.py", line 543, in _get_time_fmt
    return cls(val, val2, scale, precision, in_subfmt, out_subfmt)
  File "/home/beischer/.local/lib/python3.8/site-packages/astropy/time/formats.py", line 147, in __init__
    val1, val2 = self._check_val_type(val1, val2)
  File "/home/beischer/.local/lib/python3.8/site-packages/astropy/time/formats.py", line 805, in _check_val_type
    raise TypeError('Input values for {} class must be '
TypeError: Input values for datetime class must be datetime objects

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 25, in <module>
    x = Time(grp['tdb'])
  File "/home/beischer/.local/lib/python3.8/site-packages/astropy/time/core.py", line 430, in __init__
    self._init_from_vals(val, val2, format, scale, copy,
  File "/home/beischer/.local/lib/python3.8/site-packages/astropy/time/core.py", line 485, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale,
  File "/home/beischer/.local/lib/python3.8/site-packages/astropy/time/core.py", line 559, in _get_time_fmt
    raise ValueError(f'Input values did not match any of the formats '
ValueError: Input values did not match any of the formats where the format keyword is optional: {'datetime': TypeError('Input values for datetime class must be datetime objects'), 'ymdhms': ValueError('input must be dict or table-like'), 'iso': TypeError('Input values for iso class must be strings'), 'isot': TypeError('Input values for isot class must be strings'), 'yday': TypeError('Input values for yday class must be strings'), 'datetime64': TypeError('Input values for datetime64 class must be datetime64 objects'), 'fits': TypeError('Input values for fits class must be strings'), 'byear_str': TypeError('Input values for byear_str class must be strings'), 'jyear_str': TypeError('Input values for jyear_str class must be strings'), 'astropy_time': ValueError('cannot broadcast a non-scalar to a scalar array')}
```
### Steps to Reproduce

```python
#!/usr/bin/env python

from astropy.time import Time
from astropy.table import Table, Column
from astropy.coordinates import EarthLocation
import numpy as np

grp = Table()

time_mjd = Time([53801.38605118254], format='mjd', location=EarthLocation.from_geocentric(x=0., y=0., z=0., unit='m'))

# Broken
c1 = Column(name='mjd', data=time_mjd)
grp.add_columns([c1])
time_tdb = Time(grp['mjd'], location=grp['mjd'][0].location)

# # Works
# time_tdb = Time(time_mjd, location=time_mjd[0].location)

tdbs = np.asarray([t for t in time_tdb])

c2 = Column(name='tdb', data=tdbs)
grp.add_columns([c2])

x = Time(grp['tdb'])
```

### System Details

```
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-5.6.15-arch1-1-x86_64-with-glibc2.2.5
>>> import sys; print("Python", sys.version)
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.18.4
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.0.1.post1
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.4.1
```

EDIT: Fix formatting of traceback

**Comment by pllim** [comment]
cc @taldcroft and @mhvk

**Comment by mhvk** [comment]
@bastianbeischer - Thanks very much for reporting. I confirm this on 4.0.1, but it is fixed in current master, almost certainly because of #10113 (which started from me seeing something very similar). The fix should be part of 4.0.2 (to be released more or less together with 4.1, I think; should be within the next month).

If you have time, would you be able to test and see if things work with the 4.1 pre-release?? (would be good to be sure PINT works with it generally...)

**Comment by pllim** [comment]
Please report back to https://github.com/astropy/astropy/wiki/astropy-v4.1-release-candidate-(RC)-Testing if you test with `4.1rc1`. Thanks!

**Comment by bastianbeischer** [comment]
@mhvk Thanks for the quick response. I tried 4.1rc1 and it fixes my small script, but now the PINT tests fail in other places (actually I tried only one test, but it seems related to your #10113 PR):

`
======================================================================
ERROR: test_phase_zero (test_absphase.TestAbsPhase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/beischer/repos/astropy/astropy/coordinates/attributes.py", line 111, in __get__
    out = out._apply(np.broadcast_to, shape=instance_shape,
  File "/home/beischer/repos/astropy/astropy/time/core.py", line 1447, in _apply
    jd1 = apply_method(jd1)
  File "/home/beischer/repos/astropy/astropy/time/core.py", line 1437, in <lambda>
    apply_method = lambda array: method(array, *args, **kwargs)
  File "<__array_function__ internals>", line 5, in broadcast_to
  File "/usr/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/usr/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 120, in _broadcast_to
    raise ValueError('cannot broadcast a non-scalar to a scalar array')
ValueError: cannot broadcast a non-scalar to a scalar array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beischer/repos/PINT/tests/test_absphase.py", line 19, in test_phase_zero
    toas = pint.toa.get_TOAs(timfile)
  File "/home/beischer/.local/lib/python3.8/site-packages/pint/toa.py", line 111, in get_TOAs
    t.compute_posvels(ephem, planets)
  File "/home/beischer/.local/lib/python3.8/site-packages/pint/toa.py", line 1396, in compute_posvels
    ssb_obs = site.posvel(tdb, ephem)
  File "/home/beischer/.local/lib/python3.8/site-packages/pint/observatory/topo_obs.py", line 322, in posvel
    obs_geocenter_pv = gcrs_posvel_from_itrf(
  File "/home/beischer/.local/lib/python3.8/site-packages/pint/erfautils.py", line 245, in gcrs_posvel_from_itrf
    pos, vel = loc.get_gcrs_posvel(t)
  File "/home/beischer/repos/astropy/astropy/coordinates/earth.py", line 692, in get_gcrs_posvel
    gcrs_data = self.get_gcrs(obstime).data
  File "/home/beischer/repos/astropy/astropy/coordinates/earth.py", line 666, in get_gcrs
    itrs = self.get_itrs(obstime)
  File "/home/beischer/repos/astropy/astropy/coordinates/earth.py", line 644, in get_itrs
    return ITRS(x=self.x, y=self.y, z=self.z, obstime=obstime)
  File "/home/beischer/repos/astropy/astropy/coordinates/baseframe.py", line 601, in __init__
    values[fnm] = getattr(self, fnm)
  File "/home/beischer/repos/astropy/astropy/coordinates/attributes.py", line 117, in __get__
    raise ValueError(
ValueError: attribute obstime should be scalar or have shape (), but is has shape (1,) and could not be broadcast.
`

This is with "python -m unittest -q test_absphase.TestAbsPhase" in tests folder of PINT, If that'll allow you to reproduce the problem.

**Comment by mhvk** [comment]
Hmm, very likely due to the same PR, though in this case my guess is that it will be easier to fix it on the PINT end (which would work for older versions of astropy) because in the end there is a real mismatch between the shape of the coordinates and that of the time.

**Comment by taldcroft** [comment]
@bastianbeischer - from this discussion it appears the original issue is fixed in 4.1 so I'm closing. If that is not correct feel free to re-open, and if [this comment](https://github.com/astropy/astropy/issues/10417#issuecomment-636225773) needs an astropy fix then we can open a new issue.

**Comment by paulray** [comment]
I suppose we could fix this on the PINT side, but I don't think astropy should fail in this situation.  Here is an example. I have two `Time`s, one with one element array of values and another with 2. And I have a scalar location.  Getting the posvel for one fails but the other is fine:
```
In [43]: tdb2                                                                                                                                                        
Out[43]: <Time object: scale='tdb' format='pulsar_mjd' value=[53801.38680564 53801.48680564]>

In [44]: tdb                                                                                                                                                         
Out[44]: <Time object: scale='tdb' format='pulsar_mjd' value=[53801.38680564]>

In [45]: loc                                                                                                                                                         
Out[45]: <EarthLocation (882589.65, -4924872.32, 3943729.348) m>

In [47]: loc.get_gcrs_posvel(tdb2)                                                                                                                                   
Out[47]: 
(<CartesianRepresentation (x, y, z) in m
     [(-3595816.13864793, -3476366.52469518, 3946050.5713794 ),
      ( -856685.41636557, -4928846.3472309 , 3944476.74750923)]>,
 <CartesianRepresentation (x, y, z) in m / s
     [(253.513714  , -262.38328374, -0.13982589),
      (359.43018987,  -62.64269759, -0.21235499)]>)

In [46]: loc.get_gcrs_posvel(tdb)                                                                                                                                    
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/env/pint/lib/python3.7/site-packages/astropy/coordinates/attributes.py in __get__(self, instance, frame_cls)
    111                         out = out._apply(np.broadcast_to, shape=instance_shape,
--> 112                                          subok=True)
    113                     else:

~/env/pint/lib/python3.7/site-packages/astropy/time/core.py in _apply(self, method, format, *args, **kwargs)
   1446         if apply_method:
-> 1447             jd1 = apply_method(jd1)
   1448             jd2 = apply_method(jd2)

~/env/pint/lib/python3.7/site-packages/astropy/time/core.py in <lambda>(array)
   1436         if callable(method):
-> 1437             apply_method = lambda array: method(array, *args, **kwargs)
   1438 

<__array_function__ internals> in broadcast_to(*args, **kwargs)

~/env/pint/lib/python3.7/site-packages/numpy/lib/stride_tricks.py in broadcast_to(array, shape, subok)
    181     """
--> 182     return _broadcast_to(array, shape, subok=subok, readonly=True)
    183 

~/env/pint/lib/python3.7/site-packages/numpy/lib/stride_tricks.py in _broadcast_to(array, shape, subok, readonly)
    119     if not shape and array.shape:
--> 120         raise ValueError('cannot broadcast a non-scalar to a scalar array')
    121     if any(size < 0 for size in shape):

ValueError: cannot broadcast a non-scalar to a scalar array

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-46-9b85cb65068f> in <module>
----> 1 loc.get_gcrs_posvel(tdb)

~/env/pint/lib/python3.7/site-packages/astropy/coordinates/earth.py in get_gcrs_posvel(self, obstime)
    690         """
    691         # GCRS position
--> 692         gcrs_data = self.get_gcrs(obstime).data
    693         obsgeopos = gcrs_data.without_differentials()
    694         obsgeovel = gcrs_data.differentials['s'].to_cartesian()

~/env/pint/lib/python3.7/site-packages/astropy/coordinates/earth.py in get_gcrs(self, obstime)
    664         from .builtin_frames import GCRS
    665 
--> 666         itrs = self.get_itrs(obstime)
    667         # Assume the observatory itself is fixed on the ground.
    668         # We do a direct assignment rather than an update to avoid validation

~/env/pint/lib/python3.7/site-packages/astropy/coordinates/earth.py in get_itrs(self, obstime)
    642         # do this here to prevent a series of complicated circular imports
    643         from .builtin_frames import ITRS
--> 644         return ITRS(x=self.x, y=self.y, z=self.z, obstime=obstime)
    645 
    646     itrs = property(get_itrs, doc="""An `~astropy.coordinates.ITRS` object  with

~/env/pint/lib/python3.7/site-packages/astropy/coordinates/baseframe.py in __init__(self, copy, representation_type, differential_type, *args, **kwargs)
    599                 # Validate attribute by getting it.  If the instance has data,
    600                 # this also checks its shape is OK.  If not, we do it below.
--> 601                 values[fnm] = getattr(self, fnm)
    602             else:
    603                 setattr(self, '_' + fnm, fdefault)

~/env/pint/lib/python3.7/site-packages/astropy/coordinates/attributes.py in __get__(self, instance, frame_cls)
    118                         "attribute {} should be scalar or have shape {}, "
    119                         "but is has shape {} and could not be broadcast."
--> 120                         .format(self.name, instance_shape, out.shape))
    121 
    122                 converted = True

ValueError: attribute obstime should be scalar or have shape (), but is has shape (1,) and could not be broadcast.
```

It seems this should work, otherwise if you are working with a variable that is a `Time` with an array of values, you have to always check to make sure it hasn't got a length of 1 before calling the astropy method.  Arrays that can be anything length should not fail if they happen to be length 1, should they?

**Comment by paulray** [comment]
I don't seem to have the power to re-open.

**Comment by mhvk** [comment]
I think we should move this to a 4.1 issue...  @paulray - could you copy your comment in a new one? I'll try to have a look later today.

**Comment by paulray** [comment]
Certainly, should I create a new issue?

**Comment by mhvk** [comment]
Yes, please!
