### ISSUE TITLE
Stop bundling jquery?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10420]
While looking at what makes astropy so big (21MB), I wondered about `jquery` (~1MB). Looking at old issues, I realize it is big in part because we need to include the actual source, but why is it included in the first place? It is used only for `table/jsviewer`, and that ignores the source if one is on-line. Would it not make more sense to just move it to the "extra" packages, so that users who really use this feature a lot *offline* can get it if they want? Or is it difficult to install? (I see a `jquery` on pypi, but that perhaps is not the same thing.)

Ping @taldcroft - for reference, `astropy/table` itself is also ~1 MB...

**Comment by taldcroft** [comment]
I'm ok with not bundling that. Just need to provide some hints on the docs on getting this for offline use.

**Comment by saimn** [comment]
The un-minified files are included because Debian requires that: https://github.com/astropy/astropy/issues/4330 (even if they don't use that files: https://github.com/astropy/astropy/issues/4330#issuecomment-158612719).

**Comment by saimn** [comment]
And once compressed this is not so big:
```
❯ l astropy/extern/jquery/data/js/               
total 876K
-rw-r--r-- 1 sconseil 261K Oct  3  2019 jquery-3.1.1.js
-rw-r--r-- 1 sconseil  85K Oct  3  2019 jquery-3.1.1.min.js
-rw-r--r-- 1 sconseil 437K Oct  3  2019 jquery.dataTables.js
-rw-r--r-- 1 sconseil  81K Oct  3  2019 jquery.dataTables.min.js

❯ gzip astropy/extern/jquery/data/js/*

❯ l astropy/extern/jquery/data/js/    
total 252K
-rw-r--r-- 1 sconseil  78K Oct  3  2019 jquery-3.1.1.js.gz
-rw-r--r-- 1 sconseil  30K Oct  3  2019 jquery-3.1.1.min.js.gz
-rw-r--r-- 1 sconseil 110K Oct  3  2019 jquery.dataTables.js.gz
-rw-r--r-- 1 sconseil  28K Oct  3  2019 jquery.dataTables.min.js.gz
```

Also `jquery` on PyPI is something else, a TurboGears plugin released on 2008.

**Comment by mhvk** [comment]
OK, still I guess the question remains why we ship something that mostly does not get used.
