### ISSUE TITLE
Possible bug in setting shape of Time, Representation, etc.

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10426]
Currently, setting the shape of a `Time` or `Representation` ~`SkyCoord`~ (edit: frames and sky coordinates cannot have their shape set) implies going through all attributes and trying to set their shape in turn, reverting if there is any `AttributeError` for items for which the shapes stride imply that the shape change is not possible. However, one can also get a `ValueError`, which should thus be checked as well. (Note that it is likely difficult to set up a state where this would actually cause a problem, so this does not have high priority)
```
In [5]: np.ones((3, 2)).T.shape = 6,                                            
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-384542aa1cc8> in <module>
----> 1 np.ones((3, 2)).T.shape = 6,

AttributeError: incompatible shape for a non-contiguous array

In [6]: np.ones((3, 2)).T.shape = 1, 2                                          
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-570b08d46880> in <module>
----> 1 np.ones((3, 2)).T.shape = 1, 2

ValueError: cannot reshape array of size 6 into shape (1,2)
```

**Comment by pllim** [comment]
Since the PR is milestoned anyway, I am removing milestone from this issue. FYI.
