### ISSUE TITLE
Kernels allow silent overwriting of arrays

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#10439]
For any `convolution.Kernel2D` subclass (probably 1D also), if you give an `array=` parameter, it will overwrite the underlying array and not populate the kernel as expected.  This shouldn't be allowed.  All subclasses of `Kernel2D` should catch and reject `array=` keywords.

Example:
```
x = np.ones([10,10])
kernel = Airy2DKernel(2)
normalized_ones = Airy2DKernel(2, array=x)
```

`normalized_ones` will not be an Airy2DKernel!

**Comment by keflavich** [comment]
This is potentially a pretty easy fix.

**Comment by JasonS09** [comment]
Hello, I'd like to work in this issue if no one has taken it yet.
