### ISSUE TITLE
Crash when changing vmin and vmax interactively in matplotlib

### ISSUE THREAD

**Issue by bastianbeischer** [astropy/astropy#10435]
### Description
When interactively changing vmin and vmax of an image shown with imshow, using astropy wcsaxes in the Qt5Agg MPLBACKEND figure editor python exits and an exception is raised. This happens with matplotlib 3.2.1.

### Expected behavior
Successful change of vmin and vmax.

### Actual behavior
Crash of python with backtrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/matplotlib/backends/qt_editor/_formlayout.py", line 481, in apply
    self.apply_callback(self.formwidget.get())
  File "/usr/lib/python3.8/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 194, in apply_callback
    axes.set_xlabel(xlabel)
  File "/home/beischer/repos/astropy/astropy/visualization/wcsaxes/core.py", line 471, in set_xlabel
    raise TypeError("set_xlabel() missing 1 required positional argument: 'xlabel'")
TypeError: set_xlabel() missing 1 required positional argument: 'xlabel'
zsh: abort (core dumped)  MPLBACKEND=Qt5Agg python test_mpl.py
```

### Steps to Reproduce

Consider this script:
```python
import numpy as np
import matplotlib.pyplot as plt
from astropy.visualization.wcsaxes.frame import EllipticalFrame
from astropy.io import fits
from astropy.wcs import WCS
from astropy import units as u

data = np.ones((360,720))

header = fits.Header()
header['BITPIX'] = -32
header['NAXIS']  = 2
header['NAXIS1'] = 720
header['CRPIX1'] = 360.5
header['CRVAL1'] = 0.0
header['CDELT1'] = -0.5
header['CTYPE1'] = 'RA---AIT'
header['CUNIT1'] = 'deg'
header['NAXIS2'] = 360
header['CRPIX2'] = 180.5
header['CRVAL2'] = 0.0
header['CDELT2'] = 0.5
header['CTYPE2'] = 'DEC--AIT'

w = WCS(header)
pix_l_min, _ = w.all_world2pix(179.9, 0.0, 0)
pix_l_max, _ = w.all_world2pix(-179.9, 0.0, 0)
_, pix_b_min = w.all_world2pix(0, -89.9, 0)
_, pix_b_max = w.all_world2pix(0,  89.9, 0)

plt.figure()
plt.subplot(projection = w, frame_class=EllipticalFrame)
im = plt.imshow(data, origin='lower', cmap='jet')
ax = plt.gca()
ax.coords.grid(color='black', ls='dotted')
lon = ax.coords[0]
lat = ax.coords[1]
lon.set_axislabel('Right Ascension', color='black')
lat.set_axislabel('Declination', color='black')
lon.set_major_formatter('d')
lat.set_major_formatter('d')
lon.set_ticklabel(color='black')
lat.set_ticklabel(color='black')
lon.set_ticks(spacing = 60 * u.degree, color='black')
lat.set_ticks(spacing = 30 * u.degree, color='black')
im.set_clip_path(ax.coords.frame.patch)
plt.xlim(pix_l_min, pix_l_max)
plt.ylim(pix_b_min, pix_b_max)
plt.show()
```

1. MPLBACKEND=Qt5Agg python test_mpl.py
2. Click on the 'edit axis' button (z-shaped arrow pointing to the top right)
3. Click on 'Images, etc.'
4. Change 'Min. value'
5. Click 'Apply'

### System Details
```
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-5.7.0-arch1-1-x86_64-with-glibc2.2.5
>>> import sys; print("Python", sys.version)
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.18.4
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.1rc1
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.4.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.2.1
```

**Comment by bastianbeischer** [comment]
Note: I added matplotlib to the system details. Might be worth adding to that the issue template since it could be worth knowing for other visualization related issues?

**Comment by pllim** [comment]
> Might be worth adding to the issue template

Sure. Do you want to submit a PR for the template? Thanks!

**Comment by pllim** [comment]
cc @astrofrog and @Cadair

**Comment by bastianbeischer** [comment]
> > Might be worth adding to the issue template
> 
> Sure. Do you want to submit a PR for the template? Thanks!

Yes, done in #10438

**Comment by giang-nghg** [comment]
The problem is in this call in ` matplotlib/backends/qt_editor/_formlayout.py`, line 351:
``` 
value = eval(str(field.text()))
```

In the 2nd reproduce step above:
> 2. Click on the 'edit axis' button (z-shaped arrow pointing to the top right)

The default text of the X label is "None", which will be evaluated to `None` by said line of code.

I don't know the purpose of the `eval` call there, though. If you change the text of the X label to any string, it will also fail at said line, since it will evaluate the string as Python. Can this be considered as an upstream issue from `matplotlib`?

**Comment by dhomeier** [comment]
Confirmed on OS X, and actually on modifying any parameter (including colormap etc.) in the `Images` subpanel (or in the `Axes` subpanel as well, unless you change both X and Y label to valid strings).
Matplotlib's `qt_editor.figureoptions` seems to consider passing `None`to `xlabel`, `ylabel` legit, and in fact the WCS figure is initialised with both set to `None`. Simplest fix seems to have its `set_[xy]label` functions silently accept `None`, too. Maybe a more correct way of handling this would be to somehow map `axes.set_xlabel` to `axes.coords[0].set_axislabel` etc. so the actually visible labels could also be modified in the `Axes` editor...

**Comment by dhomeier** [comment]
> EDIT: It's probably due to this function, in `astropy/visualization/wcsaxes/core.py`, line 491:
> 
> ```
>     def get_xlabel(self):
>         for coord in self.coords:
>             if 'b' in coord.axislabels.get_visible_axes():
>                 return coord.get_axislabel()
> ```
> 
> Following the reproduce steps, the `coord.axislabels.get_visible_axes()` return `['h']` and `['c']` sequentially, so the condition fail and the function return `None`, instead of a `str`, which

Good catch!
This is just the mapping I had been speculating about. Changing those lines to
```
            if ('b' in coord.axislabels.get_visible_axes() or
                'h' in coord.axislabels.get_visible_axes()):
```
```
            if ('l' in coord.axislabels.get_visible_axes() or
                'c' in coord.axislabels.get_visible_axes()):
```
fixes the present case and also allows the `Label` to be set correctly in the `Axes` editor.

> Should the get_xlabel function have a safe default return value?

Either that or the `set_[xy]label` functions should accept `None`, but I think preferably it should handle all possible naming conventions in `coord.axislabels.get_visible_axes` – I have not yet identified where or why the labels are set to `'h'` and `'c'` in this instance, or what other labels might occur.

**Comment by bastianbeischer** [comment]
> > EDIT: It's probably due to this function, in `astropy/visualization/wcsaxes/core.py`, line 491:
> > ```
> >     def get_xlabel(self):
> >         for coord in self.coords:
> >             if 'b' in coord.axislabels.get_visible_axes():
> >                 return coord.get_axislabel()
> > ```
> > 
> > 
> > Following the reproduce steps, the `coord.axislabels.get_visible_axes()` return `['h']` and `['c']` sequentially, so the condition fail and the function return `None`, instead of a `str`, which
> 
> Good catch!
> This is just the mapping I had been speculating about. Changing those lines to
> 
> ```
>             if ('b' in coord.axislabels.get_visible_axes() or
>                 'h' in coord.axislabels.get_visible_axes()):
> ```
> 
> ```
>             if ('l' in coord.axislabels.get_visible_axes() or
>                 'c' in coord.axislabels.get_visible_axes()):
> ```
> 
> fixes the present case and also allows the `Label` to be set correctly in the `Axes` editor.
> 
> > Should the get_xlabel function have a safe default return value?
> 
> Either that or the `set_[xy]label` functions should accept `None`, but I think preferably it should handle all possible naming conventions in `coord.axislabels.get_visible_axes` – I have not yet identified where or why the labels are set to `'h'` and `'c'` in this instance, or what other labels might occur.
> 
> EDIT: looking in `wcsapi.py` the only possible values seem to be `bl` for `RectangularFrame` and `hc` for `EllipticalFrame`; so testing for both as above or explicitly checking for the class in `self.frame_class.spine_names` should have this covered.

What if there are no visible axes at all? The problem also triggers in this case:

```python
import numpy as np
import matplotlib.pyplot as plt
from astropy.visualization.wcsaxes.frame import EllipticalFrame
from astropy.io import fits
from astropy.wcs import WCS
from astropy import units as u

data = np.ones((360,720))

header = fits.Header()
header['BITPIX'] = -32
header['NAXIS']  = 2
header['NAXIS1'] = 720
header['CRPIX1'] = 360.5
header['CRVAL1'] = 0.0
header['CDELT1'] = -0.5
header['CTYPE1'] = 'RA---AIT'
header['CUNIT1'] = 'deg'
header['NAXIS2'] = 360
header['CRPIX2'] = 180.5
header['CRVAL2'] = 0.0
header['CDELT2'] = 0.5
header['CTYPE2'] = 'DEC--AIT'

w = WCS(header)
pix_l_min, _ = w.all_world2pix(179.9, 0.0, 0)
pix_l_max, _ = w.all_world2pix(-179.9, 0.0, 0)
_, pix_b_min = w.all_world2pix(0, -89.9, 0)
_, pix_b_max = w.all_world2pix(0,  89.9, 0)

plt.figure()
plt.subplot(projection = w, frame_class=EllipticalFrame)
im = plt.imshow(data, origin='lower', cmap='jet')
ax = plt.gca()
lon = ax.coords[0]
lat = ax.coords[1]
for axis in [lon, lat]:
  axis.set_axislabel('')
  axis.set_ticks_visible(False)
  axis.set_ticklabel_visible(False)
im.set_clip_path(ax.coords.frame.patch)
plt.xlim(pix_l_min, pix_l_max)
plt.ylim(pix_b_min, pix_b_max)
plt.show()
```

**Comment by dhomeier** [comment]
> What if there are no visible axes at all? The problem also triggers in this case:

I cannot reproduce this with my suggested fix (you need to modify both the `set_` and `get_[xy]labels` functions). Note that setting the label to `''` is  not `None`, but even with `axis.set_axislabel(None)` Matplotlib's `set_text()` will convert this to the empty string.

**Comment by bastianbeischer** [comment]
> > What if there are no visible axes at all? The problem also triggers in this case:
> 
> I cannot reproduce this with my suggested fix (you need to modify both the `set_` and `get_[xy]labels` functions). Note that setting the label to `''` is not `None`, but even with `axis.set_axislabel(None)` Matplotlib's `set_text()` will convert this to the empty string.

Excuse me, I meant /the original problem/ also appears with the second script I sent, I didn't try your suggested fix. Just wanted to point out that the solution should also work in case no axes are visible. It seems your suggested solution works well.

**Comment by dhomeier** [comment]
Thanks for the confirmation. I think since all labels are passed through `set*label` and `set_text` this should ensure they are set to valid values. I will go ahead then and prepare a PR for this.
