### ISSUE TITLE
Don't include developer docs in stable branch

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#10443]
# Accepted Solution

2. Hide the dev docs in stable builds w/ link to the latest, show in dev builds (this is what Sunpy does right now)

# Original Post

This came out of suggestions by both @aarchiba and @Cadair - one issue with the developer documentation at the moment is that the version at 'stable' (the default which people will see) might be out of date by up to 6 months. The easiest solution (which is what SunPy does) would be to basically remove the developer docs in release branches (and therefore the stable branch) and keep the dev docs in 'latest'. Then when going to the stable docs or any fixed release docs, instead of:

<img width="719" alt="Screenshot 2020-06-04 at 14 17 54" src="https://user-images.githubusercontent.com/314716/83761646-7eab7280-a66e-11ea-876b-70cb58998f1a.png">

users would see:

<img width="712" alt="Screenshot 2020-06-04 at 14 19 58" src="https://user-images.githubusercontent.com/314716/83761678-88cd7100-a66e-11ea-8f64-1962aba1a562.png">

and clicking on the link would take them to:

<img width="719" alt="Screenshot 2020-06-04 at 14 17 54" src="https://user-images.githubusercontent.com/314716/83761646-7eab7280-a66e-11ea-876b-70cb58998f1a.png">

in the latest developer docs. Any objections to this?

**Comment by saimn** [comment]
Why not moving it to another independent sphinx documentation ? This would decrease a bit the docs build time. I'm not sure if there would be a lot of references to fix from other parts of the docs though.

**Comment by astrofrog** [comment]
@saimn - that would be my preferred option. I suggested it in [this astropy-dev thread](https://groups.google.com/forum/#!searchin/astropy-dev/splitting$20developer$20docs%7Csort:date/astropy-dev/-CxdKb07t3k/dPCF96xdAAAJ) and got mostly positive feedback, though @eteq had some concerns. But indeed having a separate repo would in my opinion make it easier to manage. The idea of removing the dev docs during branching etc is an additional burden during releases that would be best avoided.

**Comment by taldcroft** [comment]
Fully agreed on making the dev docs a separate repo.  There is of course coupling to astropy master, but it seems like many of the problems and changes are related to packages outside of astropy-core (e.g. pytest). It would make it feel "lighter" to keep the dev docs up to date knowing that one is not going to kick off a full CI run for each commit.  Also this would reduce local sphinx build times significantly, again making it easier to keep the dev docs current.

There was a separate idea of using a Wiki page for the "up-to-the-minute" instructions, but if dev docs were separate then it would feel easy enough to just make those updates right in the sphinx dev docs.

**Comment by astrofrog** [comment]
Another thought - since the project now has 'coordinated' packages, this is a good time anyway to make sure that the dev docs apply equally to those packages.

**Comment by adrn** [comment]
👍 to moving the dev docs to a separate repo!

**Comment by pllim** [comment]
On Slack, there was also a suggestion for using Wiki. Concern was PR won't be merged fast enough to reflect reality, whereas Wiki can be updated in real time.

**Comment by mhvk** [comment]
Hmm, I see the advantage that editing development docs would be much faster, but worry that a separate package would have even less chance of being seen/reviewed -- I fear at least for me knowing what's happening in astropy consists of looking at issues+PRs with "most recently updated" sorting (I've bookmarked [`is:open sort:updated-desc`](https://github.com/astropy/astropy/issues?q=is%3Aopen+sort%3Aupdated-desc+), and I consistently fail to notice that, say, the affiliated package template or, previously, astropy-helpers get changed even though I have packages depending on it.) It also means that if I want to edit it, I have to go clone and install the package - a bridge that just means I'm less likely to do it (a similar hurdle exists for the APEs or astropy web pages). 

My sense would be to just go with the proposal made on top - keep the dev docs properly integrated but always link to the current documentation. Possibly, there is some clever programmatic approach to working around the slow `docs_build` and CI? (there used to be `[docs only]`; not sure if it still works)

p.s. I'm even more against a wiki approach - this is documentation for which consistency is very important -- and, as with other PRs, one often learns a lot from the reviews, making the end result that much better.

**Comment by taldcroft** [comment]
@astrofrog - I see the point of making the dev docs be broadly applicable to all coordinated packages, but I do worry about *requiring* that since it means writing things always in a generic way and *testing* with many / most coordinated packages. I would say to start with a narrower mission and then see where we can take it.

@mhvk - I think there is significant advantage in breaking this into a smaller dedicated docs-only package. I know for myself I always dread any docs update because of build time and waiting so long for CI. About your process for seeing PRs, have you looked into GitHub notifications (beta)?  I recently migrated to using this and it's working really well for me. That will bring up a PR on the dev docs projects if you ask for notifications.

**Comment by mhvk** [comment]
Sorry for being grumpy, but I really have a very strong wish to *not* change structure unless there is a huge benefit - surely, the build time is a technical problem that has other solutions than separating out what logically belongs together.

In general, every change comes with an often large associated cost in having to learn new methods and procedures. E.g., introducing `tox` and getting rid of `astropy-helpers` was a good thing, but one should be serious about the costs: it has certainly cost me hours if not days (as forewarned by @bsipocz in particular), which, yes, eventually I think I may get back in benefits, but that has definitely not happened yet and it is still annoyingly slow if used "correctly" or flaky if not (`git clean -fxd` being needed unreasonably often).  Similarly, we've had very annoying difficulties because of `pytest-astropy` updates (including right now), annoyances which likely wouldn't have been there if we'd this together in astropy proper.  (And I fear in my current grumpy state I'm repelled even by the thought of spending the time to investigate what the e-mail updates from github are, as it seems certain I'd have to fine-tune their filter with no guarantee it would get me what I want. But I am grumpy and appreciate the pointer regardless!)

Anyway, how about we first of all just do what the issue suggested, ensure that the dev docs always point to the latest version? I think we all agree that that is an improvement.

After that, I'd strongly suggest we first fix the dependency mess we've slowly been getting ourselves into (#10342), and think more generally about consolidation (#10352).

**Comment by bsipocz** [comment]
Ideally our webpage provides equal access to all our documentations, with shared search results etc, so it won't really matter where the material live, users will find photutils, reproject, etc functionality just as well as astropy core, or the devdocs. It would be extremely useful for functionality discoverability that would help the idea of the coordinated packages ecosystem.

It was been talked about a couple of times in the past 3 years that doing something like this is doable using the sphinx docs, but then at the last coordination meeting I got the impression that the idea was deemed unimportant and binned  🤷

**Comment by bsipocz** [comment]
@astrofrog's suggestion of removing the pages from non master branches would be very inconvenient, but it would works as a workaround. (we do the inverse already for the what's new pages, that only lives in the branches but not on master). 

The only caveat is that the release docs is and should be different for lts and master as one relies on `astropy-helpers` while the other isn't. For core releasing, we can certainly live without the lts version and do the changes in our heads, but I suspect many people use those docs to make the release for their packages that still relies on the helpers.

**Comment by pllim** [comment]
Also see #10461

**Comment by pllim** [comment]
I think from the discussions above, I see three main requirements that need to be satisfied:

* User should not encounter outdated instructions (especially by default).
* User should be able to easily submit corrections/modifications.
* New solution should not add burden to maintainers.

**Comment by hamogu** [comment]
Unless stuff gets split out (separate repro, wiki), to me personally it would be enough to add a big warning box on the top of the section:
```
.. warning

   Dev docs change frequently. Please ignore what you find here (by definition a released
   version is outdated almost the moment it's released), and look at [hard coded path to devdocs.astropy.org]
```

That way, developers can technically see outdated instructions, but any reasonably developer (and we hope they are) should click on that link and get the up-to-date devdocs instructions. 

Pros: No need to change release procedures, switch out pages etc. Updates to devdocs happen as PR to default astropy just like they do now (no new workflow for maintainers who want to update).

**Comment by astrofrog** [comment]
Yeah adding a warning at the top of relevant pages is a nice solution with minimal effort 👍

**Comment by embray** [comment]
I haven't read this full discussion yet.  I think this is a good idea, but I am :-1: on the idea of putting the developer docs in a separate repository.  I think it will make it far to likely to be even more neglected than they already are (part of my task under my new hat on the project is to improve the developer documentation, and I would much rather do it in such a way that couples more tightly to the development process--what exactly I mean by that is TBD).

Also do the development docs really contribute significantly to the build time?

I think I could easily write a small Sphinx extension or possibly even just a few lines in `conf.py` to achieve this.

**Comment by embray** [comment]
I also like @hamogu's [suggestion](https://github.com/astropy/astropy/issues/10443#issuecomment-668162069).  Such a warning could also be displayed only on stable releases.

**Comment by embray** [comment]
@mhvk 
> Similarly, we've had very annoying difficulties because of pytest-astropy updates (including right now), annoyances which likely wouldn't have been there if we'd this together in astropy proper.

If you get a chance, could you expound on what problems you had due to pytest-astropy updates?  Depending on the details perhaps that is something I can add to my todo list to address.  A large part of my current mission is to do what I can to make grumpy developers a little less grumpy :)

**Comment by mhvk** [comment]
@embray - oops, no idea what that was about, too long ago!! But mostly a general sense to keep things together.

Aside: so you are back!? Wonderful!!

**Comment by embray** [comment]
@mhvk Yeah, I understand completely. I probably wouldn't remember either.  Yes, I still need to make an announcement to the mailing list but I am back under a part-time role as Software Operations Support Specialist, so easing developer frustrations like the one you expressed is exactly under the scope of the position :)

**Comment by astrofrog** [comment]
@embray - if you can find a way to add a warning to non-latest dev docs pages that would be great!

**Comment by taldcroft** [comment]
> I think it will make it far to likely to be even more neglected than they already are 

I'm curious what drives this statement. I personally am distinctly less likely to make a small change to the docs exactly because they live in the core repo and I know that a 2 word change kicks of a 1-hour CI run (unless I can remember the magic commit directive), and building the docs locally is a pain / takes forever.

**Comment by taldcroft** [comment]
About being a pain, the point is that building the astropy core docs successfully requires a number of non-trivial dependencies, not the least being graphviz. I would guess that the mean time for an average astropy user to build the astropy docs cleanly the first time would be at least a couple of hours if not more, and even I (on the very high end of astropy experience but with a lousy memory) find the process time-consuming and sometimes tricky.

**Comment by mhvk** [comment]
@taldcroft - point about CI well taken. What drives my statement is that the other pieces that have been spun off seem to do poorly: at least, I find myself greatly hesitating to do the fork+clone+understand the structure, and the few times that I did (e.g. for `sphinx-automodpi`), the PR that I've made got no reaction whatsoever (as seems to have been the case for other PRs to that module). And as a reviewer, while in astropy I might see a devdocs PR and do a quick review, I would not if they were in another repo.

But it does seem one could have one's cake and eat it, if we introduced a `tox -e devdocs` (perhaps with a corresponding `devdocs` directory)... Indeed, such a split might also make it easier to avoid rendering them for the stable docs.

**Comment by astrofrog** [comment]
I think splitting things out has had benefits and attracted contributions from beyond the project which has been great, and made it easier to fix eg the test plugins to follow pytest without having to release a whole new version of astropy core.

It is true however that some of the PRs to them have been forgotten, which I take the blame for (I’ve been mostly off work for a few months). I’ll try and go through all the different repos soon to make sure there aren’t any PRs in need of action.

**Comment by embray** [comment]
On further thought, I don't know if this requires anything deep.  Just a warning box like like @hamogu suggested at the top of the development docs section with a link to the latest version.  The warning could be omitted in the latest (development) version if that does indeed create confusion.

I don't see how moving it to a separate repository really makes it more likely to contribute to it.  The fear of making minor edits to the documentation causing a CI run can apply to *any* part of the documentation.

**Comment by pllim** [comment]
Okay, let's try the warning box and see what happens. Thanks!

**Comment by pllim** [comment]
But given that this warning only appears as a backport PR, it is something extra the release manager needs to do unless you can find a way to automate it.

**Comment by hamogu** [comment]
I think we can keep it even simpler. We don't want extra work for the release team and we don't want extra automation that potentially needs to be maintained. These are devdocs, so for people willing to think a little bit (if they don't want to think a little, I'm not sure their PRs will be worthwhile anyway). The box can say something like (open to bike-shedding): "Click here to latest developer version of docs (or ignore box if you are already reading that version)".

**Comment by Cadair** [comment]
I just thought I would say that sunpy solved this recently by using a jinja template to conditionally include or exclude the dev guide from the build based on if the build is for a release or not: https://github.com/sunpy/sunpy/pull/4585

**Comment by pllim** [comment]
Ah, so SunPy added this in `docs/conf.py`:

```python
if not is_development:
    exclude_patterns.append('dev_guide/contents/*')
```

Interesting!

**Comment by Cadair** [comment]
That combined with a jinja template to conditionally change the toctree so there were not references to excluded files in it.

**Comment by embray** [comment]
I'm -1 on excluding the whole thing.  I might want to be able to browse the dev guide while in development, in particular if I'm working on the guide itself.  I can and do render it locally of course, but for e.g. sharing things with other people for copy-editing it's useful.  A prominent warning is sufficient.

**Comment by Cadair** [comment]
I am not sure I understand. For sunpy the only time it is excluded from the rendered sphinx documentation is on a release tag, so any development build includes the guide.

**Comment by eteq** [comment]
Summarizing some out-of-band discussion today (incl. @mwcraig @Cadair @bsipocz @saimn @embray @pllim), there's several options to consider

1. Put it in a separate repo
2. Hide the dev docs in stable builds w/ link to the latest,  show in dev builds (this is what Sunpy does right now)
3. Have a warning box at the top in stable builds that says "go here for the latest version" but hide that warning box in dev buils
4. Have a warning box for all builds that links to latest
5. status quo

I'm -1 to option 1, +1 to 2 or 3, +0 to 4, and -0 to 5.

One clarifying question/comment about option 2: in principle if the "latest" is also a stable build, the dev docs are not visible anywhere on RTD.  Our current workflow should basically never have that issue since master is never a tagged release, but it's always *possible* that changes down the line :shrug:

**Comment by embray** [comment]
One other possible option that came up in the infrastructure telecon was to use a bit of `.. html::` to insert some JS to perform a redirect.  @eteq rejected that option over having a link that actually needs to be clicked (I agree), but said JS could also just insert a link, and even delete the rest of the page contents, without having to do anything else in Sphinx.

**Comment by eteq** [comment]
Ah, right, thanks @embray - I *think* that could be an implementation detail of 2, but if anyone wants to think of it as option 6, they can vote on that too (I'm -1 on it)

**Comment by pllim** [comment]
GitHub issue isn't exactly vote friendly... Is there a place where core devs can put this to a vote formally? Is it necessary?

**Comment by eteq** [comment]
@pllim - I didn't mean anything particularly formal, just leave something like what I said where you +1/-1/+0/-0 all of the options.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/issues/10443#issuecomment-767005325

1. 👎 
2. 👍 
3. 👍 
4. 👎 
5. 👎 

In cases where people do need the older instructions, they can achieve with (3) but not (2). We had at least one use case like that where the person was looking for pre-APE 17 instructions for their own package.

**Comment by mwcraig** [comment]
I'm 👍 on 2, 0 on 3, and 👎  on the rest.

**Comment by bsipocz** [comment]
>  in principle if the "latest" is also a stable build, the dev docs are not visible anywhere on RTD

latest is never the stable in the branch workflow, so try not to cover corner cases we never end up in

**Comment by bsipocz** [comment]
I'm on 👍 for option 2, and 👎 for all the rest. Option 3 sounds OK, but people who opened PRs to old branches (using the RTD edit on github option) should have noticed a big warning, too, yet they didn't, so it's hard to believe having a box is enough here.

**Comment by mhvk** [comment]
Similarly, to me, option 2 seems the best, with 3 OK too, and 4 if for some reason 2 and 3 end up being annoying (which should not be the case if sunpy already does 2!)

**Comment by saimn** [comment]
I'm still thinking option 1 is much simpler, so :+1: for option and :-1: for the others.

**Comment by astrofrog** [comment]
+1 for option 1, 3
+0 for option 2
-1 for options 4 and 5

**Comment by pllim** [comment]
**Conclusion:** We have accepted Option 2 at Infrastructure meeting on 2021-02-22. Thanks, everyone!

**Comment by pllim** [comment]
I started working on this and I did realize that by linking stable doc to latest (Option 2), if we change the link in latest, we have to go back and change stable too. How is Sunpy handling such changes, @Cadair ?

**Comment by Cadair** [comment]
If you change the url to one which doesn't exist anymore you can use rtd's redirects.
