### ISSUE TITLE
Keywords' values are not replaced in fits.Header when keywords end in space

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#10479]
### Description
Normally, when a keyword in `astropy.io.fits.Header` is set twice second value replaces previous value of the same keyword. This does not happen when keywords end in space (`' '`)

### Expected behavior
I would expect that setting a keyword value of a keyword like `'KEY '` to 1 (first time) and to 2 (second time), the second value would replace the first value.

### Actual behavior
When setting a keyword value of a keyword like `'KEY '` to 1 (first time) and to 2 (second time), the second value **does not** replace the first value. Instead the header has two cards with the same keyword with two different values (1 and 2 in this case).

### Steps to Reproduce

```python
In [1]: from astropy.io import fits
   ...: print("--- FIRST iteration ---")
   ...: hdr = fits.Header()
   ...: hdr['KEY1'] = 1
   ...: hdr['KEY2 '] = 2
   ...: print(repr(hdr))
   ...: hdr['KEY1'] = 3
   ...: hdr['KEY2 '] = 4
   ...: print("--- SECOND iteration ---")
   ...: print(repr(hdr))
   ...: print("value of 'KEY2 ' is: {}".format(hdr['KEY2 ']))
--- FIRST iteration ---
KEY1    =                    1
KEY2    =                    2
--- SECOND iteration ---
KEY1    =                    3
KEY2    =                    2
KEY2    =                    4
value of 'KEY2 ' is: 2
```
I would expect the value of `'KEY2 '` to be 4 and that there were just one entry for this keyword in the header.

If space character is supported in keyword names (i.e., if it is simply ignored, like `strip()`), then the behavior should be as expected by me. If space at the end is not supported, then I would expect to see a warning like in the following situation:
```python
In [2]: hdr['a#'] = 9
WARNING: VerifyWarning: Keyword name 'a#' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]

In [3]: hdr['a '] = 9  # No warning!

In [4]:
```

### System Details
```
Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.0
astropy 4.2.dev167+g8bdd24b04
Scipy 1.3.2
Matplotlib 3.2.0
```

**Comment by saimn** [comment]
@mcara : Indeed, the keyword is not normalized before checking its existence, which I think is a bug. Proposed fix in #10482.
