### ISSUE TITLE
Sign of gemini_north longitude is incorrect

### ISSUE THREAD

**Issue by bryanmiller** [astropy/astropy#10486]
### Description
The sign of the longitude for gemini_north is wrong.

### Expected behavior
import astropy.coordinates as coord
gn = coord.EarthLocation.of_site('gemini_north')
print(gn.lon)
-155d28m08.5683s

### Actual behavior
import astropy.coordinates as coord
gn = coord.EarthLocation.of_site('gemini_north')
print(gn.lon)
155d28m08.5683s

### Steps to Reproduce
```python
import astropy.coordinates as coord
gn = coord.EarthLocation.of_site('gemini_north')
print(gn.lon)
```

### System Details

Darwin-17.7.0-x86_64-i386-64bit
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.1
astropy 4.0.1.post1
Scipy 1.4.1
Matplotlib 3.1.3

**Comment by pllim** [comment]
Do you have a very old cache? This is fixed already in astropy/astropy-data@96aeaa389f404471314574716e61d640dd7cba95 .

**Comment by bryanmiller** [comment]
Very good. How do I flush the cache?

**Comment by pllim** [comment]
A simply brute-force way is to delete the entire `~/.astropy/cache` directory, but it flushes out everything. If you want to just remove that file, you need to hunt it down; please see https://docs.astropy.org/en/stable/utils/data.html#cache-management .

**Comment by pllim** [comment]
But... if you want to update it without deleting, try download its URL using `astropy.utils.data.download_file(..., cache=True)` .

**Comment by bryanmiller** [comment]
I removed the entire cache and re-ran. Now it is correct. Thanks.

**Comment by bryanmiller** [comment]
Issue already fixed, but an old cache had to be deleted.

**Comment by pllim** [comment]
Glad it works now. Thanks for reporting back, @bryanmiller ! Your solution will help future users running into the same problem.
