### ISSUE TITLE
Ascii table not getting recognized

### ISSUE THREAD

**Issue by SirWindfield** [astropy/astropy#10481]
Hey! I couldn't find an IRC or something similar so this is my bet bet :)
I want to parse [this Z80 instructions table](http://www.z80.info/z80code.txt) using `astropy`. The format is consistent in itself so I thought that it might get recognized but I do get an error telling me that it can't be parsed.

Any tips on how I can resolve this? Is there a way to tell the parser that the cells have the width of the column header row elements? And the spaces inside those cells can just be ignored? 

~~If this is the wrong way to get help~~ It definitely is but I couldn't think of any better channel to be honest, sorry!

**Comment by dhomeier** [comment]
Hi @SirWindfield , there is a mailing list for general support questions, but for any issue of potential general interest, e.g. if the documentation seems not clear enough to help you with your case, or if their might be missing functionality for what you are trying to do, this is also a perfectly acceptable channel.
In your case I think there are two bits of information relevant for following up:

1. What have you tried so far for reading in that table?

2. What exactly do you hope to get as the table content?

On the 2nd question, the table seems to have a regular-enough structure to be read in as a fixed-format input with 5 columns, but except for the 2nd one, which could be parsed as an integer array, being all instruction codes, all you can hope to get is a table with `string`-format columns (which you then may try to further parse and decode, of course). If that's what you are looking for, I suggest to try something like
`Table.read(format='ascii.fixed_width', header_start=1, col_starts=[0, 13, ...], data_start=1, data_end=N)`
– this would tell the reader to ignore the first (1-entry) header line, hopefully infer the correct column starts from the following header line (EDIT: looks like you have to explicitly tell it the column positions), tell it to skip one line before the data rows start (might not be necessary as it would perhaps ignore the empty row anyway), and more importantly, end after `N` valid (5-column) data rows and just ignore the footer following them. For a better overview of the options see https://docs.astropy.org/en/stable/io/ascii/fixed_width_gallery.html
and if this still does not work, feel free to post the results and any error messages here.

**Comment by SirWindfield** [comment]
Maybe I just misunderstood the docs. I thought that by just calling `read` it would try out all tables, I didn't even notice that fixed-width is a thing. I checked the console output of the `read` method and didn't see it there. Maybe I just overlooked it there.

Thanks for help! This will definitely help me out, I appreciate it!

**Comment by dhomeier** [comment]
> Maybe I just misunderstood the docs. I thought that by just calling `read` it would try out all tables,

It does that, but automatically detecting the format will only work for reasonably common and unambiguously identifiable formats. For example in the standard order or resolution the reader will parse the first non-empty, non-comment line and try to interpret it as a header defining the number of columns. That strategy is already bound to fail on the single annotation in your first header line. Therefore the docs recommend to specify details on the format wherever possible.

**Comment by SirWindfield** [comment]
Thanks for clarifying and helping me out on this!
