### ISSUE TITLE
Meaning of empty string keywords in fits.Header

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#10496]
This is mostly a question at this moment (and possibly a bug report) as I simply do not understand the meaning of empty string keywords in `fits.Header`. Here is an example of what I am talking about:

```python
In [38]: from astropy.io import fits
    ...: hdr = fits.Header()
    ...: hdr[''] = 1
    ...: hdr[''] = 2
    ...: hdr[''] = 3
    ...: print(repr(hdr))
        1
        2
        3

In [39]: hdr[' ']
Out[39]: 1

In [40]: hdr['  ']
Out[40]: 1

In [41]: hdr['']
Out[41]: ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.../lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/.../lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395
    396             return _default_pprint(obj, self, cycle)

~/.../lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    682     """A pprint that just redirects to the normal repr function."""
    683     # Find newlines and replace them with p.break_()
--> 684     output = repr(obj)
    685     lines = output.splitlines()
    686     with p.group():

~/.../astropy/astropy/io/fits/header.py in __repr__(self)
   2230
   2231     def __repr__(self):
-> 2232         return '\n'.join(self)
   2233
   2234     def __getitem__(self, idx):

TypeError: sequence item 0: expected str instance, int found
```

First of all it is strange that empty strings (`''`) are allowed as keywords, and then that `Header` stores each value without replacing it, and then that it actually works to get the value using strings with at least one space character (`hdr[' ']`) but it crashes if I actually try to use an empty string as a key (`hdr['']`).

If this is a bug, I am not sure what to report as a bug:
1. allowing setting empty string header keywords (`hdr[''] = 1`);
2. not overwriting existing values;
3. crashing when trying to retrieve `hdr['']`.

### System Details
Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.0
astropy 4.2.dev259+g1a065d5ce
Scipy 1.3.2
Matplotlib 3.2.0

**Comment by saimn** [comment]
With an empty string this is a "blank" keyword, which is just a special kind of comment keyword. 
![image](https://user-images.githubusercontent.com/311639/84787168-a7f7c700-afbb-11ea-9510-9f0e30f5cb82.png)

And `h['']` returns the list of blank cards, same as `h['COMMENT']` or `h['HISTORY']` for comment and history cards. In your case `hdr['']` crashes because values are int, and should be strings instead. And for `hdr[' ']` (with a space) I don't know what that means yet ;).

**Comment by mcara** [comment]
Oh, I forgot! @saimn Thanks!

**Comment by mcara** [comment]
> And for `hdr[' ']` (with a space) I don't know what that means yet ;).

Probably this should not be allowed because it would appear that this is a keyword name containing forbidden characters (space).

I really forgot a bout blank keywords... 🤦

**Comment by mcara** [comment]
> In your case `hdr['']` crashes because values are int, and should be strings instead.

Maybe raise an exception if setting value using a wrong type or convert everything to `str`?

**Comment by saimn** [comment]
Yes indeed, it seems there are a few things to fix here :+1:
