### ISSUE TITLE
IERS cache updates can cause mass downloads on clusters

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#10494]
### Description

When astropy is run on a cluster, many processes operate at once, often nearly simultaneously. If data from the Net is required, all processes are liable to request it nearly simultaneously, which is likely to cause problems. This can usually be detected when a torrent of error and failure messages appear, and prevented by loading the appropriate files into the astropy cache from a single process, up front. A key exception is when the IERS data becomes too old and needs to be refreshed; this is not easy for users to anticipate and can cause surprising problems with a job that ran fine yesterday.

Specifically:

- Request IERS data from astropy in a single process.
- Submit a cluster job that requires that same IERS data from many machines.
- Set the `auto_max_age` configuration variable to `0`.
- Re-submit the same cluster job that requires that same IERS data from many machines.

Probably only detectable after solving #9970 

### Expected behavior

Re-submitted jobs succeed, or fail in some way that the user can understand and that either loads the cache or tells the user how to do this.

### Actual behavior

Many downloads are attempted at once, hammering the server and causing at least some of them to fail, producing exceptions in many jobs describing problems accessing a particular server.

Also triggers concurrency problems even with #10437 - though an extension to that might be able to resolve this issue.

### System Details

```
>>> import platform; print(platform.platform())
Linux-5.4.0-37-generic-x86_64-with-glibc2.29
>>> import sys; print("Python", sys.version)
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.18.4
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.2.dev162+gd0a1e469f
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.4.1
```

**Comment by aarchiba** [comment]
One approach to fixing this would be to invalidate the cache slightly early - that is, early by a random amount (say uniformly distributed up to an hour, or one percent of the timeout). Then the first machine to do it updates the cache and it's unlikely more than a few others decide to before it's finished.

**Comment by aarchiba** [comment]
Better would be to improve the caching mechanism to prevent (discourage) multiple simultaneous downloads, but it's difficult to do this in a way that's robust to cluster concurrency (it appears `os.mkdir` is not atomic, for example) and where interrupted downloads don't jam up the system.

**Comment by pllim** [comment]
Might be related to #10114 as well. There also have been discussions on IERS download behaviors across several different other issues (maybe @mhvk remember which ones).

For now, this might be the safest route (please correct me if I am wrong):

1. On a single machine, download the latest copy you want to use in a way that it is in astropy cache.
2. Populate the shared cache for your cluster with that file.
3. In your jobs, set `astropy.utils.iers.conf.auto_download = False`.

**Comment by aarchiba** [comment]
In fact it's probably solid advice to just set `astropy.utils.iers.conf.auto_download = False` on clusters, as blanket advice. Then have a separate script you run on the head node every week that changes this and updates the IERS tables if necessary.

**Comment by mhvk** [comment]
Agreed. On clusters, you really don't want to be using outside resources at all, so perhaps even `internet=off` (or whatever it was called...). More generally, I guess it would be good to have a brief note for people running on clusters.

**Comment by aarchiba** [comment]
I started documenting this and had an Idea. Which I will add to #10437 as soon as the doc build is clean. I'm not sure we actually had a config option that set `internet=off`? at least it doesn't seem to be in `astropy.utils.data.conf`. So I used `remote_timeout=0` to mean this, both in function arguments and in the config file (and the docs of course).

**Comment by pllim** [comment]
Unfortunately, "internet off" is not what you think it is, see astropy/pytest-remotedata#17 . There might be some stuff in https://github.com/astropy/pytest-remotedata/blob/master/pytest_remotedata/disable_internet.py you can use though.

`remote_timeout=0` might work but it might also be confusing for other maintainers going forward. I'll have to look at the code first to decide.

Thanks for adding the documentation!

**Comment by aarchiba** [comment]
#10437 includes a mechanism for shutting off internet access plus instructions for using it, in particularly on clusters. I think it's reasonable to assume that someone who sees this happen - massive crash of jobs with puzzling network messages - will go looking in the docs and find instructions for how to manage this issue on clusters.

I'd still like to make the Right Thing happen automatically but it's not obvious how. Do we consider this solved?

**Comment by pllim** [comment]
Yes, I think so, given that it was you who opened it. 😉
