### ISSUE TITLE
astropy.units to() function returns value instead of quantity, dropping the unit

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [astropy/astropy#10491]
### Description

Calling the `.to()` function on astropy.units objects returns their value instead of a quantity, silently dropping the unit.
### Expected behavior

```
(astropy.units.km).to(astropy.units.m)
<Quantity 1000. m>
```
### Actual behavior

```
(astropy.units.km).to(astropy.units.m)
1000.0
```
Note also adding `1*` gives a different (correct) result:
```
(1*astropy.units.km).to(astropy.units.m)
<Quantity 1000. m>
```
### Steps to Reproduce

```python
import astropy.units
(astropy.units.km).to(astropy.units.m)
(1*astropy.units.km).to(astropy.units.m)
```

### System Details

```
>>> import platform; print(platform.platform())
Linux-5.6.14-arch1-1-x86_64-with-glibc2.2.5
>>> import sys; print("Python", sys.version)
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.18.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.2.dev259+g1a065d5ce
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.4.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.2.1

```

**Comment by pllim** [comment]
Hello. This is not a bug but a subtle difference between `.to` for `unit` and for `Quantity`.

`<unit>.to(<another unit>)` provides the conversion factor, while `<Quantity>.to<another unit>` provides the converted `Quantity`.

If this clarifies the issue, please close this issue. Thank you.

**Comment by Stefan-Heimersheim** [comment]
Ah I see, I didn't expect that but it is consistent. Thank you!
