### ISSUE TITLE
Inconsistent representation of empty string values in repr(fits.Header)

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#10495]
`repr(fits.Header)` prints different representations for empty or space only string values even though it seems like the values are reported as empty strings.

Here is an example:
```python
In [48]: from astropy.io import fits
    ...: hdr = fits.Header(
    ...:     [
    ...:         ('KEY1', 1),
    ...:         ('KEY2', 2),
    ...:         ('KEY3', 3),
    ...:         ('REFSTR', '123'),
    ...:         ('WSTR0', ''),
    ...:         ('WSTR1', ' '),
    ...:         ('WSTR2', '  '),
    ...:         ('WSTR0-2', '')
    ...:     ]
    ...: )
    ...: print(repr(hdr))
    ...: print(len(hdr['REFSTR']))
    ...: print(len(hdr['WSTR0']))
    ...: print(len(hdr['WSTR1']))
    ...: print(len(hdr['WSTR2']))
    ...: print(len(hdr['WSTR0-2']))
    ...: print("\n=================\n")
    ...: print(hdr.cards)
KEY1    =                    1
KEY2    =                    2
KEY3    =                    3
REFSTR  = '123     '
WSTR0   = ''
WSTR1   = '        '
WSTR2   = '        '
WSTR0-2 = ''
3
0
0
0
0

=================

('KEY1', 1, '')
('KEY2', 2, '')
('KEY3', 3, '')
('REFSTR', '123', '')
('WSTR0', '', '')
('WSTR1', '', '')
('WSTR2', '', '')
('WSTR0-2', '', '')
```
My concern is that string values that _fundamentally_ appear to be all empty strings are represented differently. Particularly, I am referring to:
```
WSTR0   = ''
WSTR1   = '        '
WSTR2   = '        '
WSTR0-2 = ''
```

### System Details
Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.0
astropy 4.2.dev259+g1a065d5ce
Scipy 1.3.2
Matplotlib 3.2.0

**Comment by pllim** [comment]
The logic seems to be caused  by

https://github.com/astropy/astropy/blob/3b0c42f1c4e0352f76f55d98aaad9f2006376fa7/astropy/io/fits/card.py#L922-L950

```python
>>> hdr.cards['WSTR0']._value
''
>>> hdr.cards['WSTR1']._value
' '
>>> hdr.cards['WSTR2']._value
'  '
>>> hdr.cards['WSTR0-2']._value
''
```

```python
>>> hdr.cards['WSTR0'].value
''
>>> hdr.cards['WSTR1'].value
''
>>> hdr.cards['WSTR2'].value
''
>>> hdr.cards['WSTR0-2'].value
''
```

🤷

**Comment by mcara** [comment]
@pllim Good detective work. Thanks! I was just trying to figure out what is going on and why.

**Comment by saimn** [comment]
This behavior is defined in the FITS standard:

![image](https://user-images.githubusercontent.com/311639/84785398-73830b80-afb9-11ea-92b7-0aa949e22049.png)

![image](https://user-images.githubusercontent.com/311639/84785531-96adbb00-afb9-11ea-9b5f-7886ba0a5f8c.png)

And the code doing this is here:

https://github.com/astropy/astropy/blob/3b0c42f1c4e0352f76f55d98aaad9f2006376fa7/astropy/io/fits/card.py#L1207-L1241

**Comment by mcara** [comment]
Thank you @saimn

**Comment by mcara** [comment]
@saimn Do you happen to know how to distinguish null and empty types of strings when looking at values of keywords?

For example, extending my example above, if I wanted to do something like:
```python
hdr2 = fits.Header()
for k, v, c in hdr:
    if v[0] == 'W':
        hdr2[k] = v, c
```
values `v` are always "null strings". So the information of whether a string value is a null string or an empty string seem to be lost. How can this information be recovered (except for @pllim example of using "private" `_value`)?

**Comment by pllim** [comment]
> to distinguish null and empty types of strings

regex? 🤷

**Comment by saimn** [comment]
Yes `.value` is stripping whitespaces, but there is a config item to deactivate this: `conf.strip_header_whitespace`.
