### ISSUE TITLE
deprecate_renamed_argument doesn't pop removed arguments from kwargs

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#10506]
It did behave as expected in astropy 3.1, but not in 3.2+

See some initial discussion in the comment in code, and https://github.com/astropy/astroquery/pull/1700#discussion_r442512997

**Comment by pllim** [comment]
That linked PR is quite intimidating with `+13,595 −442`. Any chance you or @dfm can post a standalone snippet demonstrating the bug? Thanks!

**Comment by bsipocz** [comment]
The comment link points to the line, the problem is basically that removed arguments are removed from `kwargs` in 3.1, which is the expected behaviour I suppose (but it brings to some déjà vu that we had this or similar convo already). This behaviour then changes in 3.2 (at least adorning to CI, I didn't have the time to dig up the code changes). So in 3.2+, the removed args are kept in `kwargs`.

**Comment by saimn** [comment]
Trying to guess from the linked issue, this happens only when an argument is removed, not renamed, so when the "newname" is set to None, i.e. something like this:
```
In [18]: @deprecated_renamed_argument('foo', None, '1.0', arg_in_kwargs=True) 
    ...: def func(**kwargs): 
    ...:     print(kwargs) 

In [19]: func(foo=1)                                                                                     
WARNING: AstropyDeprecationWarning: "foo" was deprecated in version 1.0 and will be removed in a future version.  [warnings]
{'foo': 1}
```
In this case I think it makes sense to pass the old argument through kwargs. This is a deprecation warning, so the argument may still be used in the function while it is deprecated, and if it is not used then that should not be a problem ?

**Comment by pllim** [comment]
> In this case I think it makes sense to pass the old argument through kwargs. This is a deprecation warning, so the argument may still be used in the function while it is deprecated

I agree! So, there's nothing to fix here?

FWIW, there are the tests. And if adding a test for this case would clear things up, then please let me know.

https://github.com/astropy/astropy/blob/e00c60979ef4e0961e06712a0495fbf40166d210/astropy/utils/tests/test_decorators.py#L466
