### ISSUE TITLE
Problem with Gaia query cone search

### ISSUE THREAD

**Issue by afkowalski** [astropy/astropy#10516]
the Gaia cone search query no longer works.  It worked fine yesterday.  I've updated all astropy and astroquery packages.
Here's the error resulting from the example provided by astropy's Gaia query:

import astropy.units as u

from astropy.coordinates import SkyCoord

from astroquery.gaia import Gaia

​

coord = SkyCoord(ra=280, dec=-60, unit=(u.degree, u.degree), frame='icrs')

width = u.Quantity(0.1, u.deg)

height = u.Quantity(0.1, u.deg)

r = Gaia.query_object_async(coordinate=coord, width=width, height=height)

r.pprint()

Created TAP+ (v1.2.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
Created TAP+ (v1.2.1) - Connection:
	Host: geadata.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
500 Error 500:
null

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-2-1e54b4bb6df7> in <module>
      6 width = u.Quantity(0.1, u.deg)
      7 height = u.Quantity(0.1, u.deg)
----> 8 r = Gaia.query_object_async(coordinate=coord, width=width, height=height)
      9 r.pprint()

/anaconda3/envs/hst/lib/python3.6/site-packages/astroquery/gaia/core.py in query_object_async(self, coordinate, radius, width, height, verbose, columns)
    269         """
    270         return self.__query_object(coordinate, radius, width, height,
--> 271                                    async_job=True, verbose=verbose, columns=columns)
    272 
    273     def __cone_search(self, coordinate, radius, table_name=MAIN_GAIA_TABLE,

/anaconda3/envs/hst/lib/python3.6/site-packages/astroquery/gaia/core.py in __query_object(self, coordinate, radius, width, height, async_job, verbose, columns)
    211 
    212             if async_job:
--> 213                 job = self.launch_job_async(query, verbose=verbose)
    214             else:
    215                 job = self.launch_job(query, verbose=verbose)

/anaconda3/envs/hst/lib/python3.6/site-packages/astroquery/utils/tap/core.py in launch_job_async(self, query, name, output_file, output_format, verbose, dump_to_file, background, upload_resource, upload_table_name, autorun)
    441                         job.save_results(verbose)
    442                     else:
--> 443                         job.get_results()
    444                         log.info("Query finished.")
    445         return job

/anaconda3/envs/hst/lib/python3.6/site-packages/astroquery/utils/tap/model/job.py in get_results(self)
    245         else:
    246             # async: result is in the server once the job is finished
--> 247             self.__load_async_job_results()
    248             return self.results
    249 

/anaconda3/envs/hst/lib/python3.6/site-packages/astroquery/utils/tap/model/job.py in __load_async_job_results(self, debug)
    342             check_launch_response_status(resultsResponse,
    343                                          debug,
--> 344                                          200)
    345         self._phase = phase
    346         if phase == 'ERROR':

/anaconda3/envs/hst/lib/python3.6/site-packages/astroquery/utils/tap/conn/tapconn.py in check_launch_response_status(self, response, debug, expected_response_status, raise_exception)
    633             errMsg = taputils.get_http_response_error(response)
    634             print(response.status, errMsg)
--> 635             raise requests.exceptions.HTTPError(errMsg)
    636         else:
    637             return isError

HTTPError: Error 500:
null

**Comment by pllim** [comment]
Hello. Unfortunately, you have opened an issue in the wrong repository. Please report this over at https://github.com/astropy/astroquery/issues . We apologize for any inconvenience caused.
