### ISSUE TITLE
WCS Coordinates on data cube, NAXIS not working

### ISSUE THREAD

**Issue by pearsonkyle** [astropy/astropy#10527]
### Description
Can't select axes to use for WCS information

### Expected behavior
Even specifying `naxis=2` the code searches for keywords corresponding to a third axis

### Steps to Reproduce

```python
import urllib.request
from io import BytesIO
from astropy.io import fits
from astropy.wcs import WCS

# download image into memory
url = 'https://sha.ipac.caltech.edu/applications/Spitzer/SHA/servlet/ProductDownload?DATASET=level1&ID=382262290'
response = urllib.request.urlopen(url)
hdulist = fits.open(BytesIO(response.read()))

# to reproduce bug
wcs = WCS(hdulist[0].header)
wcs = WCS(hdulist[0].header,naxis=2)
```

### System Details

Darwin-19.5.0-x86_64-i386-64bit
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.1
astropy 4.0.1.post1
Scipy 1.5.0
Matplotlib 3.1.3

**Comment by mcara** [comment]
I _believe_ this is because `NAXIS=3` WCSLIB is looking for three axes and hence crashes because `CTYPE3` is not present (as it expects). It seems that `sub()` is applied after the entire WCS is loaded (which it can't).

**Comment by mcara** [comment]
While we (CC: @nden) will be investigating this issue, I propose the following work-around:

```python
from astropy.wcs import WCS, WCSSUB_CELESTIAL
hdr = hdulist[0].header.copy()
hdr.set('ctype3', 'TIME-----SIP', after=hdr.index('CTYPE2'))  # -SIP is added to quiet an incorrect warning
w = WCS(hdr, naxis=(WCSSUB_CELESTIAL, WCSSUB_CELESTIAL))
```

Without adding `-SIP` to this third axis, `astropy.wcs` would issue the following warning:
```
INFO:
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
```
I think this warning should be issued if `ctype` of the final `WCS` object does not have `-SIP` _after_ `naxis=...` has been applied. That is, no warning should be issued if _selected_ axes have good `CTYPE`. CC: @nden

**Comment by mcara** [comment]
Another possible workaround is:
```python
from astropy.wcs import WCS
hdr = hdulist[0].header.copy()
hdr['naxis'] = 2
del hdr['naxis3']
w = WCS(hdr)
```

**Comment by mcara** [comment]
@pearsonkyle What is the reason for having a data cube in an image and a 2D WCS in its header? Is the data cube an image stack with each image having _the same_ WCS as indicated by the 2D WCS in the header?

**Comment by dhomeier** [comment]
It is a timeseries of images, right? So presuming stable pointing, I guess they should have identical WCS.

**Comment by pearsonkyle** [comment]
@dhomeier @mcara it's a time series with pretty short exposures. The images are from the Spitzer Space telescope.

**Comment by mcara** [comment]
This is a bug and a fix was implemented in https://github.com/astropy/astropy/pull/10532

**Comment by pllim** [comment]
@pearsonkyle , if you are able to test our #10532 and confirm whether it fixes your problem or not, that would be nice. Thanks, everyone!

**Comment by pearsonkyle** [comment]
Cheers, everything works. Thanks
