### ISSUE TITLE
leap-second auto-update cache warning in 4.0.1

### ISSUE THREAD

**Issue by jeanconn** [astropy/astropy#10523]
### Description

I'm attempting to update our production environment to use a newer version of astropy and in integration testing my application I get:
```
WARNING: leap-second auto-update failed due to the following exception: RuntimeError('Cache is locked after 5.01 s. This may indicate an astropy bug or that kill -9 was used. If you want to unlock the cache remove the directory /home/jeanconn/.astropy/cache/download/py3/lock. Lock claims to be held by process 43777.',) [astropy.time.core]
```
I first saw the issue with astropy 4.0.1.post1 but still see the warning with the dev version installed via pip per your bug report directions.

From a search in open issues I suppose this may be related to #9970

### Expected behavior

I expected no change in outputs.

### Actual behavior

I received a warning message.

I was not expecting a leap-second or astropy cache related warning.  I note there are no leap seconds in the range of my test or planned for the future.

### Steps to Reproduce

This would take more digging as I'm not sure which piece of the code made the call to astropy that threw out this warning.

### System Details

```
Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0]
Numpy 1.18.5
astropy 4.2.dev319+g7cc204f
Scipy 1.5.0
Matplotlib 3.2.2
```

**Comment by pllim** [comment]
This would be fixed by #10437 because that PR completely removes the lock. If you feel like it, you could install from that PR branch and see if the problem really goes away for your use case. Thanks for reporting this!
