### ISSUE TITLE
TST: Test against system libraries (cfitsio, wcslib, erfa, expat)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10539]
To avoid a repeat of issues like #10534 , where things are broken when package is built against system libraries over the bundled ones.

cc @astrofrog @saimn @nden

**Comment by dhomeier** [comment]
What about `erfa` and `expat`? I had similar problems to #10537 with the include paths for
`ASTROPY_USE_SYSTEM_CFITSIO=1 ASTROPY_USE_SYSTEM_ERFA=1`
– for cfitsio this is solved by #10538, but still need to explicitly pass the path to `erfa.h`.

**Comment by pllim** [comment]
Good catch, @dhomeier ! I have updated the title.

**Comment by mhvk** [comment]
Note that we could use the `s390x` or `arm64` for this -- these are already using `apt` to get dependencies, and one might as well have those dependencies include the system libraries and use those.

**Comment by saimn** [comment]
@mhvk - Yes, I tried that in #10538, but the apt builds are broken : https://travis-ci.org/github/astropy/astropy/builds/705844034

**Comment by mhvk** [comment]
Oops, that's not good! I'll have a look to see if I can fix it. Possibly just a reflection of my poor skills in merging Debian with Ubuntu...

**Comment by mhvk** [comment]
After more hassle than I hoped, the apt-based tests are running again, and the `ASTROPY_USE_SYSTEM_ALL` mostly seems to work, *except* for a test that makes a custom `wcs`; see https://travis-ci.org/github/astropy/astropy/jobs/707078463

Any ideas?

**Comment by pllim** [comment]
Would @olebole know why `89-wcslib-dev_7.3+ds-1_amd64.deb` is missing a `wcsconfig.h`? Or maybe @nden or @mcara have seen this before?

```
astropy/wcs/include/astropy_wcs/astropy_wcs_api.h:4:10: fatal error: wcsconfig.h: No such file or directory
```

**Comment by olebole** [comment]
@pllim this is in `/usr/include/wcslib/wcsconfig.h` ([resp. `/usr/lib/wcslib-7.3/wcsconfig.h`](https://packages.debian.org/sid/amd64/wcslib-dev/filelist)), so you probably need to add a `-I/usr/include/wcslib` to the `CPPFLAGS`.

**Comment by mhvk** [comment]
Indeed, the problem is with the test, which assumes the include file is inside astropy: 
https://github.com/astropy/astropy/blob/0fd0be3c3f119a6d1880f7d8b7ae3d66366f831e/astropy/wcs/tests/extension/setup.py#L34-L40

This ignores work done in `wcs/setup_package.py`, which I think is trying to set oneself up correctly.

**Comment by mhvk** [comment]
I just tried locally: `test_extension` also fails, but I think since this is just a test it is OK to make a relatively easy hack, to use `/usr/include/wcslib` if the astropy-provided `wcslib` is not found. For anybody writing their own extensions, it will at least point them in the right direction.
