### ISSUE TITLE
Backport pyerfa#39 for astropy 4.1

### ISSUE THREAD

**Issue by bnavigator** [astropy/astropy#10535]
As discussed in #10329, the problem described in liberfa/pyerfa#38 is true for the still bundled _erfa directory:

> `erfa_generator.py` uses the locally provided headers and c sources despite PYERFA_USE_SYSTEM_LIBERFA is specified. The way it is described, one would expect that only the global headers form the system's `erfa-devel`, `liberfa-dev` or whatever it is called in the distribution package would be needed. But `erfa_generator.py` is called with `ERFA_SRC` before the check for the library.

So liberfa/pyerfa#39, which closes that issue should probably be backported to astropy and included into the 4.1 release

**Comment by eteq** [comment]
I'm going to try to do a direct backport of just this diff straight to the v4.1.x branch on the theory that we'll want to do a more proper update of `pyerfa` for v4.2. PR incoming shortly, but once that's done we should be sure to make an issue to ensure this actually happens in 4.2.

**Comment by eteq** [comment]
(clarification: After looking at this I realized we *don't* need to worry about this in 4.2 since it's no longer bundled)

**Comment by bnavigator** [comment]
https://build.opensuse.org/package/view_file/home:bnavigator:astropy-rc/python-astropy-rc/astropy-pr10329-unbundle-erfa_4.1rc2.patch?expand=1

**Comment by eteq** [comment]
Done in e60bcf70eff39d6728d3c3bb03ec7c4784663908 for v4.1.x, which should close this!
