### ISSUE TITLE
Add Poisson likelihood fitter

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#1056]
I would like to add a `PoissonLikelihoodFitter` as available e.g. in Sherpa (described [here](http://cxc.cfa.harvard.edu/sherpa/statistics/)) to be able to fit Poisson count data.

A preliminary version can be found here: [class](https://gammapy.readthedocs.org/en/latest/_modules/gammapy/stats/fitting.html#PoissonLikelihoodFitter), [example](https://github.com/gammapy/gammapy/blob/master/examples/poisson_fitting.py).

TODO:

- [ ] Make it work with n-dimensional models and data (currently only supports 1-dimensional)
- [ ] Pass extra arguments along to `scipy.optimize.minimize`.
- [ ] Is this the right way to handle integral models?

cc @nden, @embray Should I try to implement this now and get it into astropy or should I wait for your modeling APE and further structural changes in `astropy.modeling`?

EDIT: the issue description was updated, so some comments below are outdated / irrelevant now.

**Comment by astrofrog** [comment]
+1 to the idea, but removing 1.0 milestone

**Comment by cdeil** [comment]
We're using Sherpa now, so we don't need this in Astropy any more and I don't plan to work on it there.
Closing this old issue.

**Comment by embray** [comment]
Would rather leave issues like this open--just because you don't need it or plan on working on it for Astropy doesn't mean it's not a good issue to keep open.

**Comment by cdeil** [comment]
An issue is mainly useful if there's a chance that it leads to improvements, right?

If it's just a bunch of year-old and outdated discussion keeping it open and making people re-read through it is just annoying.

In this case if someone is interested to implement this in astropy.modeling, they should ignore the discussion here and continue with #3786 .
