### ISSUE TITLE
TST: apt cron jobs (arm64, s390x) failed with erfa not installed

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10561]
`E   ImportError: erfa version 1.7 or later must be installed to use Astropy. erfa is not installed.`

Probably as a result of #10329 .

**Comment by mhvk** [comment]
Hmm, weird, why does it not pull in `pyerfa` via pip? I'll try to have a look...

**Comment by mhvk** [comment]
Since #10555 now passed, I'm fairly sure this will be fixed by it.
