### ISSUE TITLE
TST: matplotlib 3.3.0 broke some tests (cron: OSX, pyinstaller)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10588]
- [x] Push event to `master`, Windows job. (**UPDATE: It fixed itself...** 🤷‍♀️ )
   *  `ax = plt.subplot(1, 1, 1, projection=WCS(TARGET_HEADER))` gives `TclError`; example https://travis-ci.org/github/astropy/astropy/jobs/710075892
   * Linux job passed.
- [x] Cron job for OSX gets 55 failures, which seems to be mostly label related at a glance; example https://travis-ci.org/github/astropy/astropy/jobs/710063986
- [x] Cron job for `pyinstaller` did not even get to the tests and failed with `RuntimeError: Could not find the matplotlib data files`; example https://travis-ci.org/github/astropy/astropy/jobs/710063994

cc @astrofrog and @Cadair

**Comment by pllim** [comment]
p.s. These didn't get caught in the "dev job" due to very specific OS/installer settings.

**Comment by pllim** [comment]
Push to `master` passed again without any action. So, let's keep an eye on the cron job and see if those would go away too... 🤞

**Comment by pllim** [comment]
The two cron job failures are persistent and need to be addressed. Example log from last night: https://travis-ci.org/github/astropy/astropy/builds/711156109

**Comment by astrofrog** [comment]
I've opened a PR to fix the PyInstaller cron job: https://github.com/astropy/astropy/pull/10637

**Comment by astrofrog** [comment]
The MacOS X cron was fixed in https://github.com/astropy/astropy/pull/10634
