### ISSUE TITLE
HDUList does not close file if filename is pathlib.Path

### ISSUE THREAD

**Issue by zonca** [astropy/astropy#10594]
If I write a FITS file and provide the filename as a `pathlib.Path` object, the file is not closed

### How to reproduce

```python
from astropy.io import fits
import pathlib
hdulist = fits.HDUList([fits.PrimaryHDU()])
print("Use pathlib.Path")
hdulist.writeto(pathlib.Path("e.fits"), overwrite=True)
print("Use string")
hdulist.writeto("e.fits", overwrite=True)
```

Running this:

```
python -Wd writeto_path.py
Use pathlib.Path
/home/zonca/zonca/p/software/healpy/healpyvenv/lib/python3.7/site-packages/astropy/utils/decorators.py:535: ResourceWarning: unclosed file <_io.FileIO name='e.fits' mode='wb' closefd=True>
  return function(*args, **kwargs)
Use string
```

### Possible issue

I think the issue is at https://github.com/astropy/astropy/blob/a6a350570aec6600eb907fe9903585dd18dc0874/astropy/io/fits/hdu/hdulist.py#L927
It checks if the input file is `str`, it would be nice to check also for `pathlib.Path`.

**Comment by saimn** [comment]
Fixed in #10599, thanks for the report @zonca.
