### ISSUE TITLE
astropy.test() on Debian 10

### ISSUE THREAD

**Issue by cinaeds** [astropy/astropy#10604]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

### System Details

The system is Debian 10.4 (buster) 64 bit. 

For the software not provided by Debian, the code was compiled by either downloading the lastest version of the code from pypi or github.

The following packages were downloaded from pypi
```
  imread-0.7.4.tar.gz  
  pyamg-4.0.0.tar.gz  
  scikit-image.tar  
  skyfield-1.25.tar.gz 
```
and the following packages were downloaded from github 
```
  astropy  
  extension-helpers  
  pytest-astropy
```
The 
```
  astropy.test() 
```
failed miserably. The log file is enclosed.

So I developed my own test and downloaded the following python3 code from 

  https://docs.astropy.org/en/stable/generated/examples/

namely, 
```
  create-mef.py
  fits-tables.py
  modify-fits-header.py
  plot_fits-image.py
  plot_galactocentric-frame.py
  plot_obs-planning.py
  plot_sgr-coordinate-frame.py
  rv-to-gsr.py
  skip_create-large-fits.py
  split-jpeg-to-fits.py
```
And based on the visual inspection of the web images with the ones I generated - noting I'm farsighted and need glasses, I'm not convinced there's a problem.

Summary of log file follows - can't send the entire log. 

```
Script started on 2020-07-26 16:08:14-07:00 [TERM="xterm-256color" TTY="/dev/pts/7" COLUMNS="86" LINES=
"24"]
cinaed@ampere:~$ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> astropy.test()
================================ test session starts =================================
platform linux -- Python 3.7.3, pytest-6.0.0rc1, py-1.9.0, pluggy-0.13.1

Running tests with Astropy version 4.2.dev449+g28d3cf175.
Running tests in /usr/local/lib/python3.7/dist-packages/astropy-4.2.dev449+g28d3cf175-py3.7-linux-x86_6
4.egg/astropy.

Date: 2020-07-26T16:08:50

Platform: Linux-4.19.0-9-amd64-x86_64-with-debian-10.4

Executable: /usr/bin/python3

Full Python Version: 
3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.16.2
Scipy: 1.1.0
Matplotlib: 3.0.2
h5py: 2.8.0
Pandas: 0.23.3
PyERFA: 1.7.0
Cython: 0.29.2
Scikit-image: 0.18.dev0
asdf: 2.3.2

Using Astropy options: remote_data: none.

rootdir: /usr/local/lib/python3.7/dist-packages/astropy-4.2.dev449+g28d3cf175-py3.7-linux-x86_64.egg/as
tropy
plugins: mock-3.2.0, filter-subpackage-0.1.1, astropy-header-0.1.2, hypothesis-5.23.1, arraydiff-0.3, d
octestplus-0.2.0, localserver-0.5.0, openfiles-0.3.2, cov-2.6.0, remotedata-0.3.1
[astropy.test.log](https://github.com/astropy/astropy/files/4984365/astropy.test.log)

.
.
.
.
=== 71 skipped, 155 xfailed, 44 warnings, 14637 errors in 217.85s (0:03:37) ====
<ExitCode.TESTS_FAILED: 1>
>>> 
```

-- Cinaed

EDIT: Formatting.

**Comment by mhvk** [comment]
@cinaeds - thanks for the report. It is definitely the idea that astropy can be installed without problems - after all, Debian itself ships it. I run Debian myself and usually just use the version shipped with it; for development, I create a virtual environment and just `pip install` within that, i.e., I let `pip` take care of ensuring there is a set of packages with the right versions, etc.

**Comment by pllim** [comment]
Hmm. I thought @olebole applies special patches to the code we ship for Debian?

**Comment by olebole** [comment]
There are a number of patches that are applied; they can be found [in our repository](https://salsa.debian.org/debian-astro-team/astropy/-/tree/master/debian/patches). Many of them are however due to peculiarities of our Policy (f.e. that network is not available during the build, or that we always use system libs instead of the ones shipped with astropy); a few are due to potentially unresolved issues f.e. on arm64 (#9657).
So doing a `pip3 install astropy` followed by a test should work (but this is nothing I test).
The test summary however suggests that there is something basic broken:
> ```
> === 71 skipped, 155 xfailed, 44 warnings, 14637 errors in 217.85s (0:03:37) ====
> ```
That is *zero* success.
@cinaeds - maybe you could add the first "real" error from the log? That would help to see what goes wrong.
Alternatively you also could rename the log file to have the suffix `.txt`; these can be attached to the issue.

**Comment by mhvk** [comment]
@cinaeds - note that we do test against Debian on CI: see `.travis.yml` and in particular https://github.com/astropy/astropy/blob/d65dabbcc3152ad0d4839e696d85e0e4c70d5966/.travis.yml#L52

**Comment by pllim** [comment]
Re: full log -- Try pastebin or Gist or something if GitHub won't let you attach it.

**Comment by cinaeds** [comment]
Actually, now that I think about it,  I was using the web interface at 
the time. I tried to drag and drop and then cut and past and I couldn't 
get it send.  I'll try email.

-- CInaed

**Comment by cinaeds** [comment]
And I misspoke - it looks like it may just be a version problem.

The dots in front of the /opt path are probably disconnected from paths 
- the other paths look correct.

-- Cinaed

**Comment by pllim** [comment]
Is this still a problem?

**Comment by bsipocz** [comment]
I'm closing this now, as the clarification hasn't been posted in the past few months. Please feel free to reopen if it's still an issue, attaching a full log. Thanks!
