### ISSUE TITLE
Inconsistent and "lossy" return values from `SigmaClip`

### ISSUE THREAD

**Issue by jehturner** [astropy/astropy#10605]
### Description
In June 2018, `SigmaClip.__call__` was split into `_sigmaclip_noaxis` and `_sigmaclip_withaxis` branches. The former branch optimizes the simplest cases by removing deviant pixels during processing, whilst the latter [now tracks deviant values by substituting `NaN`s in the data array instead of using a `MaskedArray`](https://github.com/astropy/astropy/commit/96f20287634c40faef7a43e4ee90140010e05652). This has led to a couple of probably-unintended changes in API when using the `axis` parameter:

* With `masked=True` (the default & previous behaviour), the `MaskedArray` that gets returned now has `NaN` values in its main data array. These special values are unnecessary because the corresponding elements are already masked. Moreover, changing them to `NaN` discards useful information about what the masked values were. This is undesirable eg. when plotting the data with deviant values annotated.

* When providing an integer array as input, it gets upcast to `float64`, which also seems unexpected and shouldn't happen implicitly if avoidable.

These are **inconsistent with the behaviour for `axis=None` and for `copy=False`** -- options which shouldn't affect what the return value looks like.

Specifying `masked=False` also produces `NaN`s -- but in that case the behaviour is a documented new form of usage, where `NaN` values are used in place of a mask (and thus the return type has to be some kind of float).

### Expected behavior
I expect to get back a `MaskedArray` that's the same as the input `data` but with a mask attached. I don't expect the output `dtype` or the presence of `NaN` values to depend on the `axis` or `copy` parameters.

### Actual behavior
With `masked=True` and `axis=0`, the `MaskedArray` returned has `NaN` at masked pixels and is upcast to `float64`.

### Steps to Reproduce

Note that `axis=None` and `axis=0` mean exactly the same thing here (clip over the only axis), but they trigger different branches in the code.
```python
import numpy as np
from astropy.stats import sigma_clip

data_in = np.array([-2, 5, -5, -6, 20, 14, 1])

print('In               ', data_in)

data_out = sigma_clip(data_in, sigma=1.5, maxiters=3)

print('\nNoaxis_data      ', data_out.data)
print('Noaxis_mask      ', data_out.mask)

data_out = sigma_clip(data_in, sigma=1.5, maxiters=3, axis=0)

print('\nWithaxis_data    ', data_out.data)
print('Withaxis_mask    ', data_out.mask)

data_out = sigma_clip(data_in, sigma=1.5, maxiters=3, axis=0, copy=False)

print('\nWithaxis_no_copy ', data_out.data)

data_out = sigma_clip(data_in, sigma=1.5, maxiters=3, axis=0, masked=False)

print('\nWithaxis_no_mask ', data_out)
```
```
In                [-2  5 -5 -6 20 14  1]

Noaxis_data       [-2  5 -5 -6 20 14  1]
Noaxis_mask       [False  True False False  True  True False]

Withaxis_data     [-2. nan -5. -6. nan nan  1.]
Withaxis_mask     [False  True False False  True  True False]

Withaxis_no_copy  [-2  5 -5 -6 20 14  1]

Withaxis_no_mask  [-2. nan -5. -6. nan nan  1.]
```

### System Details
Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0]
Numpy 1.17.2
astropy 4.1.dev1967+g02fb00a
Scipy 1.3.1
Matplotlib 3.1.1

### Solution

This can be fixed in 1 line by adding `filtered_data = np.ma.MaskedArray(data, filtered_data.mask, copy=True)` after [L381](https://github.com/astropy/astropy/blob/055c0ad984869538a0d6fa97391ff5486ec922fd/astropy/stats/sigma_clipping.py#L381) of `_sigmaclip_withaxis`. I'm already working on a PR for this same class and can just include the fix there, following any discussion here. Thanks.

**Comment by jehturner** [comment]
@larrybradley, @saimn

**Comment by pllim** [comment]
@jehturner , since you already know how to fix it, are you interested to submit a PR? 😄

**Comment by larrybradley** [comment]
Thanks, @jehturner.  This regression certainly wasn't intended.  Your solution looks good to me.  I would consider this a bug fix, so perhaps it should go in a separate PR (with a regression test).

**Comment by jehturner** [comment]
OK, thanks.

**Comment by jehturner** [comment]
Do you have a target release for this, @pllim / @bsipocz, for the change log? Does it go in, say, both 4.0.2 & 4.1.1 and, if so, do we need to write something in the change log for both releases?

**Comment by jehturner** [comment]
Hang on, I'll just check whether there's something written about that in the latest developer instructions.

**Comment by jehturner** [comment]
No, the instructions don't specifically address that, but I'll need to create the PR before finalizing the change log entry anyway...

**Comment by pllim** [comment]
Re: milestone -- It is @larrybradley 's call. Since this is a bug, it can be in 4.0.x or 4.1.x, depending on whether Larry feels it is applicable or critical enough for LTS or not.

**Comment by jehturner** [comment]
Fine -- either way. It doesn't seem like anyone has complained about this and my related PR will probably go in 4.2, come to think of it.

Sorry if I pinged Brigitta unnecessarily.

**Comment by larrybradley** [comment]
I think this can go in 4.0.2.
