### ISSUE TITLE
Update Zenodo records?

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#10611]
It looks like the last Astropy version with a Zenodo record was v3.0.5 (https://zenodo.org/record/2556700#.XyF4wRNKjUJ). Do we want to upload records for the last few releases, and add "update Zenodo record" to the release procedures? Or are we ok with not updating Zenodo?

**Comment by pllim** [comment]
Zenodo can hook straight into GitHub releases now. Are y'all not using that?

**Comment by mhvk** [comment]
Indeed, all it needs is linking to github and pushing tags for every release.

It would be good for the zenodo text to also include a link to the astropy articles.

**Comment by jdswinbank** [comment]
For the NASA ROSES proposal (https://github.com/astropy/astropy-project/issues/161), I'd like to be able to assert that Zenodo records are created for all releases. Can we make that true?

I note that creating the Zenodo record is already part of the [standard release procedures](https://docs.astropy.org/en/stable/development/releasing.html#post-release-procedures) (step #10), so I think we're covered there.

I'd be happy to do work myself to automate this, but I don't know who has the appropriate credentials: I certainly don't have access.

**Comment by pllim** [comment]
Maybe @astropy/coordinators can assist here. 🤞

**Comment by pllim** [comment]
Zenodo webhook has been fixed. See #11748
