### ISSUE TITLE
ImportError: No module named astropy.io

### ISSUE THREAD

**Issue by WirthmU** [astropy/astropy#10633]
### Description
 I am having troubles running a python script that relies on importing the astropy module.
Astropy has bin installed using pip.

### Actual behavior
```
Traceback (most recent call last):
  File "Astride.py", line 36, in <module>
    from astropy.io import fits
ImportError: No module named astropy.io
```

### Steps to Reproduce

```python
from astropy.io import fits
```

### System Details

```
>>> import astropy; print("astropy", astropy.__version__)
('astropy', u'2.0.16')
```

**Comment by taldcroft** [comment]
@WirthmU - version 2.0 of astropy is very old and no longer supported by the developers. Please upgrade to version 4.0.

**Comment by pllim** [comment]
If `pip` is pulling 2.x, perhaps you are using Python 2? Python 2 has reached end-of-life as well, please use Python 3.
