### ISSUE TITLE
clear_download_cache is sensitive to trailing slash

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10630]
### Description

@aarchiba , `clear_download_cache` appears to be sensitive to trailing slash. Is it a bug or feature? Will fixing this introduce other bugs for other variation of inputs?

This is a follow up issue of #10437.

### Expected behavior

If I tell it to clear `https://domain` whereas I cached the URL as `https://domain/`, there should be no difference.

### Actual behavior

Cached `https://domain/` isn't cleared.

### Steps to Reproduce

```python
>>> from astropy.utils.data import import_file_to_cache, get_cached_urls, clear_download_cache
>>> import_file_to_cache('https://example.com/', 'README.md')
'/path/to/.astropy/cache/download/url/182ccedb33a9e03fbf1079b209da1a31/contents'
>>> get_cached_urls()
['https://example.com/']
>>> clear_download_cache('https://example.com')  # No trailing slash
>>> get_cached_urls()
['https://example.com/']
>>> clear_download_cache('https://example.com/')
>>> get_cached_urls()                                                                          
[]
```

**Comment by aarchiba** [comment]
So I believe that technically the trailing slash makes it a different URL. We do actually pass URLs through `urllib.parse.urlsplit` and its inverse, but the difference between these two URLs is `path=''` versus `path='/'`. According to Google (https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html ), trailing slashes are generically significant but this specific case is guaranteed to be equivalent. I can easily make that happen.
