### ISSUE TITLE
Warning about polar motion of dates in the future seems rather high

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#10645]
### Description
When transforming coordinates far in the future, e.g. 2040, a warning is raised that
coordinates will be imprecise to a level of "10s of arcseconds".

This seems rather much for missing polar motion information, since polar motion seems
to be < 1 arcsecond, see e.g. page 241ff of the Expl. Suppl. to the Astronomical Almanac or the 
IERS online information here: https://www.iers.org/IERS/EN/Science/EarthRotation/PolarMotion.html

### Steps to Reproduce

```python

>>> from astropy.time import Time
>>> from astropy.coordinates import SkyCoord, AltAz, EarthLocation
>>> location = EarthLocation.of_site('Roque de los Muchachos')                                                                            
>>> time = Time('2040-01-01T00:00')                                                                                                       
WARNING: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)" [astropy._erfa.core]
>>> altaz = SkyCoord(alt='70d', az='0d', frame=AltAz(obstime=time, location=location))                                                    
>>> cirs = altaz.transform_to('cirs')                                                                                                     
WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those. This may affect precision at the 10s of arcsec level [astropy.coordinates.builtin_frames.utils]
WARNING: ErfaWarning: ERFA function "apio13" yielded 1 of "dubious year (Note 2)" [astropy._erfa.core]
```

I might be misunderstanding the effect of polar motion, but the approximate algorithms in the Expl. Suppl. also make no mention of polar motion and claim to be accurate to the 1 arcsecond level (p. 298ff, section 7.4.5.1)

**Comment by MaxNoe** [comment]
When plotting the polar motion with `astropy.coordiantes.builtin_frames.utils`, this also is < 1 arcsecond:

![polar_motion](https://user-images.githubusercontent.com/5488440/90121357-2bcff480-dd5c-11ea-89e5-5018063e2aae.png)

**Comment by MaxNoe** [comment]
Maybe its a simple typo and should have read `10ths of arcseconds` instead of `10s of arcseconds`?

**Comment by pllim** [comment]
Wouldn't "tenths" be easier to read? Do we still have a copyeditor?
