### ISSUE TITLE
Coercing data types?

### ISSUE THREAD

**Issue by RyotaInagaki1** [astropy/astropy#10657]
I am wondering if there is a way to coerce an astropy table or astropy column to be of a particular type like how there is in Pandas.
Is there?

**Comment by pllim** [comment]
Are you not able to find the information in https://docs.astropy.org/en/latest/table/index.html ? Also, can you please provide a pandas code snippet?

**Comment by RyotaInagaki1** [comment]
Never mind. I will try my alternatives.

**Comment by taldcroft** [comment]
For example, if you have a table with an int64 column you could coerce to int32 with:
```
t['a'] = t['a'].astype(np.int32)
```
