### ISSUE TITLE
config folder/file not found

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [astropy/astropy#10661]
On a Windows 10 computer, when I issue the command from astropy.config import get_config_dir, I get the following error:

```
C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astropy\config\configuration.py:557:
ConfigurationMissingWarning: Configuration defaults will be used due to FileNotFoundError:2 on
None warn(ConfigurationMissingWarning(msg))
```

But, I have set XDG_CONFIG_HOME=C:\Users<USERID>.astropy\config, where USERID is my user ID, and there is a valid configuration file in that folder.

**Comment by Phillip-M-Feldman** [comment]
Because the import fails, it seems as though there is no way to determine where Astropy is looking for the config folder (or where it got that path from).

**Comment by pllim** [comment]
`C:\Users.astropy\config` -- Is the period supposed to be there?

**Comment by Phillip-M-Feldman** [comment]
I believe that the period should be there, but the text that I entered
somehow got corrupted.  The path should be
`C:\Users\<USERID>\.astropy\config`.

**Comment by saimn** [comment]
Your config file should be in `$XDG_CONFIG_HOME/astropy`.

**Comment by embray** [comment]
As @saimn noted, if `XDG_CONFIG_HOME` is set, the config file would be under `$XDG_CONFIG_HOME/astropy`.  However, `$XDG_CONFIG_HOME` is more of a UNIX standard and doesn't make a lot of sense to use on Windows.  You're better off not setting it at all, since by default `C:\Users\<Username>\.astropy\config` will be the right path for the config files on Windows.

**Comment by pllim** [comment]
@Phillip-M-Feldman , did the answers resolve your issue? If so, please close this issue. If not, please let us know what else isn't working. Thanks!

**Comment by saimn** [comment]
There is maybe another issue if the default (without setting `XDG_CONFIG_HOME`) did not work. And I guess the error message does not help to identify the problem ;) (`FileNotFoundError:2 on None warn(ConfigurationMissingWarning(msg))` is a bit cryptic).

**Comment by pllim** [comment]
On my Windows machine, I never had to set any special variables. I use Miniconda + Git Bash, install astropy (either released or dev) into a non-base environment there, and things Just Work ™️ .

**Comment by Phillip-M-Feldman** [comment]
Here's what I'm seeing:

>>> from astropy import units as u
C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astropy\config\configuration.py:557:
ConfigurationMissingWarning: Configuration defaults will be used due to
FileNotFoundError:2 on None
  warn(ConfigurationMissingWarning(msg))

So, my configuration file is not being found, although it does exist in the
default location.

**Comment by Phillip-M-Feldman** [comment]
The more serious problem for me is that my script dies when it attempts to
import (directly or indirectly) from astropy:

C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astropy\config\configuration.py:557:
ConfigurationMissingWarning: Configuration defaults will be used due to
FileNotFoundError:2 on None
  warn(ConfigurationMissingWarning(msg))
WARNING: CacheMissingWarning: Remote data cache could not be accessed due
to FileNotFoundError:
[WinError 53] The network path was not found: '\\\\<omitted>\\.astropy'
[astropy.utils.data]

Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat
|===========================================| 1.3k/1.3k (100.00%)         0s
WARNING: ConfigurationMissingWarning: Configuration defaults will be used
due to FileNotFoundError:2 on None [astropy.config.configuration]
Traceback (most recent call last):
  File "STK.py", line 49, in <module>
    from poliastro.twobody import Orbit
  File
"C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\poliastro\twobody\__init__.py",
line 1, in <module>
    from .orbit import Orbit
  File
"C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\poliastro\twobody\orbit.py",
line 15, in <module>
    from astroquery.jplhorizons import Horizons
  File
"C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astroquery\jplhorizons\__init__.py",
line 216, in <module>
    from .core import Horizons, HorizonsClass
  File
"C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astroquery\jplhorizons\core.py",
line 1302, in <module>
    Horizons = HorizonsClass()
  File
"C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astroquery\jplhorizons\core.py",
line 86, in __init__
    super(HorizonsClass, self).__init__()
  File
"C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astroquery\query.py",
line 162, in __init__
    paths.get_cache_dir(), 'astroquery',
  File
"C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astropy\config\paths.py",
line 173, in get_cache_dir
    return os.path.abspath(_find_or_create_root_dir('cache', linkto,
rootname))
  File
"C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astropy\config\paths.py",
line 298, in _find_or_create_root_dir
    os.mkdir(innerdir)
FileNotFoundError: [WinError 53] The network path was not found:
'\\\\<omitted>\\UserID\\.astropy'

It is unclear to my why Astropy is searching a network path.

**Comment by embray** [comment]
The warning is bubbling up from this call to `get_config_dir()`: https://github.com/astropy/astropy/blob/be39265ca5c20ed9945d59d7d7e188fa0caacdaa/astropy/config/configuration.py#L574

That's why the warning message says `None`.  Because if an exception occurred at this line, `cfgfn` is `None`.  This alone is definitely a bug.

**Comment by embray** [comment]
@Phillip-M-Feldman Could you please paste the output of

```python
import os, pprint
pprint.pprint(os.environ)
```

from your Python interpreter?  Make sure to censor out anything private that might be in your environment.

I wonder if this is related to #10570.

**Comment by Phillip-M-Feldman** [comment]
I believe that there is a relationship to #10570: The HOME environment
variable isn't used in Windows, and it is probably a bad idea to use
HOMESHARE either because users don't have any control over this variable.
That leaves HOMEPATH, which should always be defined and point to a folder
that exists.

Following is the output that was requested:

(py38) C:\>python
Python 3.8.5 (default, Aug  5 2020, 09:44:06) [MSC v.1916 64 bit (AMD64)]
:: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, pprint
>>> pprint.pprint(os.environ)

environ({'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA':
'C:\\Users\\USERID\\AppData\\Roaming', 'CODE': 'C:\\Phillip\\PM\\Code3',
'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
'COMMONPROGRAMFILES(X86)': 'C:\\Program
Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program
Files\\Common Files',
'COMPUTERNAME': 'ITE00487857', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
'CONDA_DEFAULT_ENV':
'py38', 'CONDA_EXE': 'C:\\ProgramData\\Anaconda3\\Scripts\\conda.exe',
'CONDA_PREFIX':
'C:\\ProgramData\\Anaconda3\\envs\\py38', 'CONDA_PROMPT_MODIFIER': '(py38)
',
'CONDA_PYTHON_EXE': 'C:\\ProgramData\\Anaconda3\\python.exe',
'CONDA_SHLVL': '1', 'DRIVERDATA':
'C:\\Windows\\System32\\Drivers\\DriverData', 'EGO_CONFDIR':
'C:\\LSF_9.1\\conf', 'GDAL_DATA':
'C:\\ProgramData\\Anaconda3\\envs\\py38\\Library\\share\\gdal',
'GEOTIFF_CSV':
'C:\\ProgramData\\Anaconda3\\envs\\py38\\Library\\share\\epsg_csv',
'HOMEDRIVE': 'P:',
'HOMEPATH': '\\', 'HOMESHARE':
'\\\\networkshare\home2\\USERID', 'IMPORTPATH':
'C:\\Phillip\\PM\\Code3\\*', 'LOCALAPPDATA':
'C:\\Users\\USERID\\AppData\\Local', 'LOGONSERVER': '\\\\NG-C30-DC06',
'LSF_ENVDIR':
'C:\\LSF_9.1\\conf', 'MEDIA': 'C:\\pmap\\Media', 'NUMBER_OF_PROCESSORS':
'8', 'OS':
'Windows_NT', 'PATH':
'C:\\ProgramData\\Anaconda3\\envs\\py38;
C:\\ProgramData\\Anaconda3\\envs\\py38\\Library\\mingw-w64\\bin;
C:\\ProgramData\\Anaconda3\\envs\\py38\\Library\\usr\\bin;
C:\\ProgramData\\Anaconda3\\envs\\py38\\Library\\bin;
C:\\ProgramData\\Anaconda3\\envs\\py38\\Scripts;
C:\\ProgramData\\Anaconda3\\envs\\py38\\bin;C:\\PROGRA~1\\Anaconda3;
C:\\PROGRA~1\\Anaconda3\\Library\\mingw-w64\\bin;
C:\\PROGRA~1\\Anaconda3\\Library\\usr\\bin;C:\\PROGRA~1\\Anaconda3\\Library\\bin;
C:\\PROGRA~1\\Anaconda3\\Scripts;C:\\LSF_9.1\\9.1\\bin;C:\\LSF_9.1\\9.1\\lib;C:\\WINDOWS\\system32;
C:\\WINDOWS;C:\\Program
Files\\bin;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program
Files (x86)\\NVIDIA
Corporation\\PhysX\\Common;C:\\Users\\USERID\\.dnx\\bin;C:\\Program
Files\\Microsoft DNX\\Dnvm;C:\\Program Files\\Microsoft SQL
Server\\120\\Tools\\Binn;C:\\Program
Files\\Microsoft SQL Server\\130\\Tools\\Binn;C:\\Program Files
(x86)\\Windows Kits\\10\\Windows
Performance Toolkit;C:\\Program
Files\\MATLAB\\R2017b\\runtime\\win64;C:\\Program
Files\\TortoiseGit\\bin;C:\\Apps\\Git\\cmd;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program
Files\\MiKTeX 2.9\\miktex\\bin\\x64;C:\\Program Files\\PuTTY;C:\\Program
Files\\Intel\\WiFi\\bin;C:\\Program Files\\Common
Files\\Intel\\WirelessCommon;C:\\Program
Files\\Anaconda3;C:\\Program Files\\Anaconda3\\Scripts;C:\\Program
Files\\Anaconda3\\Library\\bin;C:\\Program
Files\\Anaconda3\\Library\\usr\\bin;C:\\Program
Files\\Anaconda3\\bin;C:\\Program
Files\\Anaconda3\\condabin;C:\\Users\\USERID\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program
Files (x86)\\GnuWin32\\bin;.', 'PATHEXT':
'.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
'PROCESSOR_ARCHITECTURE': 'AMD64',
'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 94 Stepping 3,
GenuineIntel', 'PROCESSOR_LEVEL':
'6', 'PROCESSOR_REVISION': '5e03', 'PROGRAMDATA': 'C:\\ProgramData',
'PROGRAMFILES':
'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
'PROGRAMW6432':
'C:\\Program Files', 'PROJ_LIB':
'C:\\ProgramData\\Anaconda3\\envs\\py38\\Library\\share\\proj',
'PROMPT': '(py38) $P$G', 'PSMODULEPATH': 'C:\\Program
Files\\WindowsPowerShell\\Modules;
'C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
'PUBLIC': 'C:\\Users\\Public', 'PYTHON':
'C:\\ProgramData\\Anaconda3\\envs\\py38\\python.exe',
'PYTHONBREAKPOINT': 'ipdb.set_trace', 'PYTHONSTARTUP':
'C:\\Users\\USERID\\PYTHONSTARTUP.py',
'PYTHON_VERSION': '3.8', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:',
'SYSTEMROOT':
'C:\\WINDOWS', 'TEMP': 'C:\\Users\\USERID\\AppData\\Local\\Temp', 'TMP':
'C:\\Users\\USERID\\AppData\\Local\\Temp', 'UATDATA':
'USERDNSDOMAIN': 'M.COM', 'USERDOMAIN': 'M', 'USERDOMAIN_ROAMINGPROFILE':
'M',
'USERNAME': 'USERID', 'USERPROFILE': 'C:\\Users\\USERID', 'VS110COMNTOOLS':
'C:\\Program Files
(x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\', 'VS120COMNTOOLS':
'C:\\Program Files
(x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\', 'VS140COMNTOOLS':
'C:\\Program Files
(x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\', 'WINDIR':
'C:\\WINDOWS'})

**Comment by Phillip-M-Feldman** [comment]
I would love to get some closure on this issue.  It seems as though there
is general agreement that there is a bug of some sort here.

**Comment by pllim** [comment]
@Phillip-M-Feldman , did none of the suggestions above work for you?

**Comment by Phillip-M-Feldman** [comment]
Nothing has worked.   E. M. Bray asked for output from the commands

import os, pprint
pprint.pprint(os.environ)

I provided that output and then heard nothing further.

**Comment by Phillip-M-Feldman** [comment]
I should clarify: I deleted the environment variable XDG_CONFIG_HOME, so
this is no longer a factor.

**Comment by pllim** [comment]
I wasn't sure what @embray intended to do with that info, but #10570 is merged already, so you can try install a dev version of astropy via pip if you think that PR will fix your problem.

```
pip install git+https://github.com/astropy/astropy.git@master
```

Then check you have the dev version:
```python
import astropy
print(astropy.__version__)  # should be 4.2.devNNNNN
```

**Comment by Phillip-M-Feldman** [comment]
I've got the correct version of astropy:

>>> print(astropy.__version__)
4.2.dev560+g679a74a46

But, I'm not seeing any change in the behavior.  Please let me know if
there's anything else that I can do to help diagnose the problem.

**Comment by pllim** [comment]
Why don't you [join Astropy Slack workspace](http://joinslack.astropy.org/) and direct message me there? I think it is easier that way.

**Comment by pllim** [comment]
So, in `astropy`, this is only a warning and doesn't stop anything from running. But `astroquery` promotes it to an exception because `astroquery` likes caching.

And based on this Windows logic:

https://github.com/astropy/astropy/blob/659ea8c708379a3e76f445f50bfbe1e4270ef668/astropy/config/paths.py#L42-L48

It tries to use HOMESHARE (as far as I can see based on what is posted above) and fails because your network drive is unavailable for whatever reason. So, here are my suggestions (better ones are certainly welcome):

1. Define MSYSTEM *and* HOME. Point HOME to some local drive where you want to cache to be stored; **-- OR --**
2. Change HOMESHARE to point to some local drive where you want to cache to be stored.

On my Windows in a Git Bash shell, this is what it looks like for me:

```
$ echo $MSYSTEM
MINGW64
$ echo $HOME
/c/Users/username
```

**Comment by Phillip-M-Feldman** [comment]
After talking to some of our multi-platform developers, I understand the
problem.  I was told that HOMESHARE should be used on Linux, and
USERPROFILE should be used on Windows.  This is apparently a fairly common
mistake for developers who work exclusively on Linux.  Is there any
possibility of getting this changed?  (HOMESHARE is defined on some Windows
machines, but is set via Active Directory and essentially hardwired, so
that users--even with administrative rights--cannot change the value).

**Comment by Phillip-M-Feldman** [comment]
If I go the MSYSTEM and HOME route, how should MSYSTEM be set?  Note that
neither of these is a standard Windows environment variable.

**Comment by pllim** [comment]
**Re: MSYSTEM**

Try set it to `MINGW64` and see if anything breaks. If nothing on your machine is using it, it shouldn't matter what the value is. It just have to exist.

**Re: HOMESHARE vs USERPROFILE**

Fixing this might break some other person's set up, so any fix won't be in a backport anyway (you won't see it released soon). I do agree that maybe the logic should check for all the local stuff first before trying the network. I'll see if I can work out a PR.

We apologize for any inconvenience caused!

**Comment by pllim** [comment]
Also, seems like #8731 might be related.

**Comment by pllim** [comment]
Do you want to see if  #10705 would work for you? With that patch, if MSYSTEM isn't there, it would have checked for HOMEDRIVE + HOMEPATH next, which for your case, it would be `P:\\`.

**Comment by embray** [comment]
On #10705 there was some discussion as to whether all of the messy logic in the [`_find_home`](https://github.com/astropy/astropy/blob/40bd0e487a65f92fd23eeb73738d57cf8a2232ad/astropy/config/paths.py#L17) function could simply be replaced with a call to `os.path.expanduser('~')` on both POSIX systems and Windows.

No consensus was immediately reached on this before the PR was merged, so the use of `os.path.expanduser('~')` was only targeted to the case where `os.name == 'posix'`, so this is of no immediate benefit to @Phillip-M-Feldman .

The open question was whether the behavior of `os.path.expanduser('~')` is also an appropriate default on Windows.  As I explained in the PR, I believe it is, and that all the Windows-specific logic should be removed and delegated to the default behavior provided by Python (rather than checking all these different environment variables ourselves).  I guess this will require a follow-up PR.

**Comment by embray** [comment]
@pllim Oops, I see you opened #10705 for this.  I got my wires crossed since #10705 and #10570 are permutations of each other :)

**Comment by embray** [comment]
With #10705 merged I think we can close this issue.

To summarize:

* By default, on Windows, the astropy config directory will go to `~/.astropy/config` where how `~` is interpreted by default on Windows is documented at: https://docs.python.org/3.7/library/os.path.html#os.path.expanduser

* `HOMESHARE` will not be used when determining the home directory on Windows.

* You can still change the location of the config, even on Windows, by setting `XDG_CONFIG_HOME`, but this should be something like `C:\Users\<Username>\config`, and under that the `C:\Users\<Username>\config\astropy` directory should exist, but the `\astropy` is not part of the environment variable value  (You can use any path you want though, I just used ``C:\Users\<Username>\config` as an example.

@Phillip-M-Feldman Feel free to follow up here if you have any more questions or concerns.

**Comment by Phillip-M-Feldman** [comment]
This is excellent news.  Thanks!

When I search via anaconda.org, the most recent version of astropy that I
see is 4.0.1.post1, which I already have.  How can I install the more
recent version?

**Comment by pllim** [comment]
If you insist to use `conda install` only the version released to `conda`, then I am afraid you have to wait a few months for 4.2. If you are more adventurous, you can try `pip install git+https://github.com/astropy/astropy.git@master`. For the latter, I recommend you try it out in a fresh and independent conda environment first.

**Comment by ReeceHumphreys** [comment]
Stumbled onto this, if you need the latest astropy build from GitHub using pip the command is `pip install git+https://github.com/astropy/astropy.git@main`

**Comment by james8128** [comment]
> Stumbled onto this, if you need the latest astropy build from GitHub using pip the command is `pip install git+https://github.com/astropy/astropy.git@main`

After hours of googling, only your solution could solve my problem.  Thanks a lot

**Comment by neutrinoceros** [comment]
@james8128 did you encounter this issue with astropy 7.0.0 ?
