### ISSUE TITLE
Circular standard deviation

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#10677]
### Description

The [circstats](https://docs.astropy.org/en/stable/stats/circ.html) module includes a function for the circular variance, but not for the standard deviation. It seems trivial to implement, given its definition as `sqrt(-2 * ln(R))` ([sd.circular: Circular Standard Deviation](https://rdrr.io/rforge/circular/man/sd.circular.html))

### Additional context

The implementation could be a simple as:

```
def circstd(data, axis=None, weights=None):
    """ Computes the circular standard deviation of an array of circular data.

    The standard deviation implemented here is based on the definition given by
    [1]_, which is also the same used by the R package 'Circular' [2]_.

    Parameters
    ----------
    data : numpy.ndarray or dimensionless Quantity
        Array of circular (directional) data, which is assumed to be in
        radians whenever ``data`` is ``numpy.ndarray``.
    axis : int, optional
        Axis along which circular variances are computed. The default is to
        compute the variance of the flattened array.
    weights : numpy.ndarray, optional
        In case of grouped data, the i-th element of ``weights`` represents a
        weighting factor for each group such that ``sum(weights, axis)``
        equals the number of observations. See [1]_, remark 1.4, page 22,
        for detailed explanation.

    Returns
    -------
    circstd : numpy.ndarray or dimensionless Quantity
        Circular standard deviation.

    Examples
    --------
    >>> import numpy as np
    >>> from astropy.stats import circvar
    >>> from astropy import units as u
    >>> data = np.array([51, 67, 40, 109, 31, 358])*u.deg
    >>> circstd(data) # doctest: +FLOAT_CMP
    <Quantity 0.5976699855802333>

    References
    ----------
    .. [1] K.V. Mardia. "Statistics of Directional Data".
       Academic Press, London, sec. 26.5, p. 617, 1972.
    .. [2] U. Lund, C. Agostinelli, et al. "Circular Statistics from 'Topics in
       Circular Statistics (2001)'". 2017.
       <https://cran.r-project.org/web/packages/circular/circular.pdf>

    """

    return np.sqrt(-2.0 * np.log(_length(data, 1, 0.0, axis, weights)))
```

**Comment by pllim** [comment]
@larrybradley ?

p.s. Didn't have to open issue first. Since you already wrote the code, you could have submitted it as a PR. 😄

**Comment by Gabriel-p** [comment]
@pllim sorry, yes

**Comment by larrybradley** [comment]
@Gabriel-p  I'm not an expert on circular statistics, but apparently there are two definitions of the circular standard deviation.

from https://www.researchgate.net/publication/38105304_CircStat_a_MATLAB_toolbox_for_circular_statistics:

"Interestingly, multiple quantities have been introduced as analogues to the linear standard deviation. First, the angular deviation is defined as`s = sqrt(2 * (1 − R))`.  This quantity lies in the interval [0, sqrt(2)]. 

Alternatively, the circular standard deviation is defined as `s0 = sqrt(−2 * ln(R))` and ranges from 0 to ∞.

Generally, the first measure is preferred, as it is bounded, but the two measures deviate little (Zar (1999))."

Do you want to open a PR?

**Comment by Gabriel-p** [comment]
@larrybradley I could add an argument to decide between the "circular" and the "angular" standard deviation. What do you think? I can open a PR, sure.

**Comment by larrybradley** [comment]
Sounds good, thanks!
