### ISSUE TITLE
Invalid "rotation_matrix" creation in earth_orientation.py

### ISSUE THREAD

**Issue by malibuSS** [astropy/astropy#10680]
### Description

The "rotation_matrix" call in earth_orientation.nutation_matrix passes in a positional argument "False" where "units" is expected.

### Expected behavior

Expected the creation of a nutation matrix.

### Actual behavior

Traceback (most recent call last):

  File "C:\Magic\projects\python\coordinates\nutation_bug.py", line 36, in <module>
    main()

  File "C:\Magic\projects\python\coordinates\nutation_bug.py", line 25, in main
    nut = earth.nutation_matrix(epoch)

  File "C:\Apps\Anaconda3\lib\site-packages\astropy\coordinates\earth_orientation.py", line 409, in nutation_matrix
    return matrix_product(rotation_matrix(-(epsa + deps), 'x', False),

  File "C:\Apps\Anaconda3\lib\site-packages\astropy\coordinates\matrix_utilities.py", line 67, in rotation_matrix
    angle = Angle(angle, unit=unit)

  File "C:\Apps\Anaconda3\lib\site-packages\astropy\coordinates\angles.py", line 108, in __new__
    return super().__new__(cls, angle, unit, dtype=dtype, copy=copy)

  File "C:\Apps\Anaconda3\lib\site-packages\astropy\units\quantity.py", line 397, in __new__
    value._set_unit(value_unit)

  File "C:\Apps\Anaconda3\lib\site-packages\astropy\coordinates\angles.py", line 130, in _set_unit
    super()._set_unit(self._convert_unit_to_angle_unit(unit))

  File "C:\Apps\Anaconda3\lib\site-packages\astropy\units\quantity.py", line 1726, in _set_unit
    raise UnitTypeError(

UnitTypeError: Angle instances require units equivalent to 'rad', so cannot set it to '0'.
### Steps to Reproduce

```
# -*- coding: utf-8 -*-
from astropy import units as u
from astropy import coordinates as coord
from astropy.coordinates import earth_orientation as earth
from astropy.coordinates import (CartesianRepresentation,
                                 CartesianDifferential)
from astropy.time import Time
from astropy.coordinates.matrix_utilities import (rotation_matrix,
                                                  matrix_product,
                                                  matrix_transpose)

def main():
    epoch = Time("2020-08-26T19:00:00.000", scale='utc', format='isot')
    efr = coord.ITRS(obstime=epoch,
                     x = -2.35668363946753E+07 * u.m,
                     y =  1.19868010003885E+07 * u.m,
                     z =  3.24827797553070E+06 * u.m,
                     v_x = -8.89213597994628E+02 * u.m/u.s,
                     v_y =  3.52042817906612E+02 * u.m/u.s,
                     v_z = -3.15331898432760E+03 * u.m/u.s,
                     representation_type=CartesianRepresentation,
                     differential_type=CartesianDifferential,
                    )

    nut = earth.nutation_matrix(epoch)

    # epsa, dpsi, deps = earth.nutation_components2000B(epoch.jd)  # all in radians
    # nut = matrix_product(rotation_matrix(-(epsa + deps), 'x', unit=u.rad),
    #                      rotation_matrix(-dpsi, 'z', unit=u.rad),
    #                      rotation_matrix(epsa, 'x', unit=u.rad))
    # tod = efr.transform_to(coord.PrecessedGeocentric(obstime=epoch,
    #                                                  equinox=epoch))
    print(f"{nut = }")

if __name__ == "__main__":
    main()
```

```python
# Put your Python code snippet here.
```

### System Details

Windows-10-10.0.18362-SP0
Python 3.8.3 (default, Jul  2 2020, 17:28:51) [MSC v.1916 32 bit (Intel)]
Numpy 1.18.5
astropy 4.0.1.post1
Scipy 1.5.0
Matplotlib 3.2.2

**Comment by mhvk** [comment]
Thanks for reporting! This broke due to #9793, though if it worked before, it was more by accident than anything else. Clearly, our testing is not good enough - indeed, I cannot find a single test for `nutation_matrix`! Actually, looking back, I see there is an open issue about this: #6583....

What I think happened is that we switched to erfa routines for this (which is the standard), but never removed/deprecated the code. Indeed, there are quite a few "TODO: replace w/SOFA equivalent" scattered throughout `earth_orientation.py`... So, I guess for your use case, a question is whether the erfa routines that we now use could also work for you. In particular, maybe `nut06a` or pnm06a` from https://pyerfa.readthedocs.io/en/latest/api.html#functions?

**Comment by mhvk** [comment]
@eteq - looking a bit more at this issue, it seems the whole of `earth_orientation` should really be replaced by calls to `erfa`. Do you remember why it is being used in `fk5` and `fk4` (only places it is imported)?

**Comment by pllim** [comment]
If this is a duplicate, shall we close this and move the discussion to #6583 ?

**Comment by mhvk** [comment]
@pllim - yes, you are right - we should discuss in #6583. @malibuSS - I'll close this, but thanks again for reporting. I hope the work-arounds here and in #6583 are enough to let you continue.
