### ISSUE TITLE
astropy.io ECSV format: missing informations but no error

### ISSUE THREAD

**Issue by ccossou** [astropy/astropy#10704]
### Description

I have a naive question about an ECSV file that I have. I'm sorry if it doesn't turn out usefull but I literally spent 2 hours reading the documentation trying to find something I'm doing wrong. 

It's not the first time I have issues with an ECSV file that seem valid but isn't. 

### Expected behavior
I read an ECSV file. It's read without error or warning but the unit is missing for the first column, I expected either the unit or an error because it's not valid.

Note that I also join a second file that works because I can't understand why one is working and not the other.

### Actual behavior
For column wavelength, unit is None, and I expected micron. No error either.

### Steps to Reproduce
```python
from astropy.io import ascii

# filename = "working_data.txt"
filename = "not_working_data.txt"

d = ascii.read(filename)

d.info()
```

I don't know how to attach an ascii file so here is the data for both files.

not_working_data.txt:
```
# %ECSV 0.9
# ---
# datatype:
# - {name: wavelength, unit: micron, datatype: float64}
# - {name: u1, unit: '', datatype: float64}
# - {name: u2, unit: '', datatype: float64}
# - {name: u3, unit: '', datatype: float64}
# - {name: u4, unit: '', datatype: float64}
# schema: astropy-2.0
#
wavelength  u1        u2        u3        u4
2.50000E+04	7.5859791E-01	7.5859791E-01	7.5859791E-01	7.5859791E-01
2.75000E+04	7.6787710E-01	7.6787710E-01	7.6787710E-01	7.6787710E-01

```

working_data.txt:
```
# %ECSV 0.9
# ---
# datatype:
# - {name: wavelength, unit: micron, datatype: float64}
# - {name: u1, unit: '', datatype: float64}
# - {name: u2, unit: '', datatype: float64}
# schema: astropy-2.0
#
# meta: !!omap
# - {/// PROCESSED (MML) ///}
# - {Limb Darkening Calculations v.1.0.}
# - {DISCLAIMER: If you make use of this code for your research,}
# - {        please consider citing Espinoza & Jordan (2015).}
# - {A100}
wavelength  u1        u2
3.0000   0.08854328  0.23533507
3.6500   0.08424535  0.19314521

```

### System Details

```
Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
Numpy 1.18.1
astropy 4.0
Scipy 1.4.1
Matplotlib 3.1.3
```

**Comment by pllim** [comment]
It worked for me after I replaced all the tabs in `not_working_data.txt` with spaces. You can define your own delimiter if you want though, see https://docs.astropy.org/en/latest/io/ascii/read.html#parameters-for-read

**Comment by ccossou** [comment]
Thanks for the helps, indeed it works. 

Any idea why a problem in the data columns caused the unit to be skipped? Important note that the data where correctly read (so I didn't anticipated that the problem could occurs from those lines)

**Comment by taldcroft** [comment]
@ccossou - sorry you've had a frustrating experience.

For future reference the ECSV specification states that the delimiter must be either the space character or comma character (https://github.com/astropy/astropy-APEs/blob/master/APE6.rst#data-details).  Since it seems you had tabs, I am guessing that you generated the ECSV "by-hand" somehow?

BTW, when I tried to read your not working file, I got this exception which is what I would expect (since it doesn't consider tabs to be a delimiter):
```
InconsistentTableError: Number of header columns (5) inconsistent with data columns (1) at data line 0
Header values: ['wavelength', 'u1', 'u2', 'u3', 'u4']
Data values: ['2.50000E+04\t7.5859791E-01\t7.5859791E-01\t7.5859791E-01\t7.5859791E-01']
```

**Comment by ccossou** [comment]
Thanks for the additionnals infos. 

I did not get such an error and I'm not sure why (using the code I copy/pasted above). Maybe you have the devel version and the exception was added in between.

Since everything works for you and an error is even raised, I see no point in keeping this issue. Thanks for the help, both of you. I'm closing this.

**Comment by pllim** [comment]
@taldcroft , I used 4.2.dev and `io.ascii.read` and did not get that error either. Perhaps you were using `Table.read`?
