### ISSUE TITLE
Add ability to rotate WCSAxes tick labels

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#10717]
As far as I can tell from the [`CoordinateHelper` documentation](https://docs.astropy.org/en/stable/api/astropy.visualization.wcsaxes.CoordinateHelper.html#astropy.visualization.wcsaxes.CoordinateHelper) there's no way to manually rotate the tick labels on a WCSAxes plot. It would be good to have this functionality to e.g. rotate y-axis labels so they are parallel with the axis.

There are a few different ways to do this with normal matplotlib tick labels, listed here: https://www.delftstack.com/howto/matplotlib/how-to-rotate-x-axis-tick-label-text-in-matplotlib/

**Comment by Cadair** [comment]
I think this is probably non-trivial, the line which sets the label angle is [here](https://github.com/astropy/astropy/blob/master/astropy/visualization/wcsaxes/coordinate_helpers.py#L822), but the spine normal_angle is re-computed before draw here: https://github.com/astropy/astropy/blob/master/astropy/visualization/wcsaxes/frame.py#L87 so you can't override it.

**Comment by dstansby** [comment]
Turns out you can already do this with https://docs.astropy.org/en/stable/api/astropy.visualization.wcsaxes.CoordinateHelper.html#astropy.visualization.wcsaxes.CoordinateHelper.set_ticklabel

**Comment by keflavich** [comment]
Example:
```python
ax.coords[0].set_ticklabel(rotation=45, pad=20) # without the pad, this will sometimes overlap with the axis boundary
ax.coords[0].set_ticklabel(rotation='vertical')
```

It would be a good idea to add some of these examples to the narrative docs.  Without this issue coming up as a google hit, I'm not sure I'd have figured it out.
