### ISSUE TITLE
Automatic bounding boxes of inverse models are not re-computed

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#10712]
# Description
For simple models (i.e., `Scale`), the bounding box of the inverse transformation is computed/assigned automatically but appears to be incorrect. Based on what I saw in my limited testing, the bounding box of the inverse transformation is identical to the bounding box of the forward transformation.

### Expected behavior
I expect the bounding box of the inverse transformation to be re-computed so that when inverse transformation is applied to a value within its bounding box, that value would map to the bounding box of the forward transformation. At the very least this should work for simple models.

### Actual behavior
The bounding box of the inverse transformation is identical to the bounding box of the forward transformation. This results in bizarre behavior outlined in the next section.

### Steps to Reproduce (Example: `Scale`)
```python
In [1]: from astropy.modeling.models import Scale, Shift

In [2]: m = Scale(2)

In [3]: m.bounding_box = (1, 5)

In [4]: invm = m.inverse

In [5]: invm.bounding_box
Out[5]: (1, 5)

In [6]: invm(m(4, with_bounding_box=True), with_bounding_box=True)
Out[6]: nan
```

### Steps to Reproduce (Example: `Shift`)
```python
In [7]: m = Shift(10)

In [8]: m.bounding_box = (1, 5)

In [9]: invm = m.inverse

In [10]: invm.bounding_box
Out[10]: (1, 5)

In [11]: invm(m(4, with_bounding_box=True), with_bounding_box=True)
Out[11]: nan
```

### System Details
```python
In [12]: import platform; print(platform.platform())
    ...: import sys; print("Python", sys.version)
    ...: import numpy; print("Numpy", numpy.__version__)
    ...: import astropy; print("astropy", astropy.__version__)
    ...: import scipy; print("Scipy", scipy.__version__)
    ...: import matplotlib; print("Matplotlib", matplotlib.__version__)
Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.19.1
astropy 4.0.1.post1
Scipy 1.5.2
Matplotlib 3.1.1
```

**Comment by pllim** [comment]
Are you trying to apply redshift?

**Comment by pllim** [comment]
Can't tell if this is a feature request or bug, so I'll let @perrygreenfield or @nden decide.

**Comment by jdavies-st** [comment]
Inverses should not have bounding boxes.  Or redshifts!  =)

**Comment by pllim** [comment]
I got a workaround in `synphot` to recalculate X-axis based on presence of redshift but it's very specific to spectrum, in case that is what you are doing.

**Comment by mcara** [comment]
I was designing a simple unit test for something else and it was failing when I thought it shouldn't be failing. I back-traced it to the issue of bounding boxes assigned to inverse models.

**Comment by jdavies-st** [comment]
Yeah, the issue looks to be that for model classes that have inverses auto-defined, the bounding box also gets auto-defined, but incorrectly.  But just because there's an analytical inverse for a model, doesn't mean the bounding box is meaningful.  This is probably the case for any 2D model that is more complex than `Scale` or `Shift`.

Maybe it would be best to not have any bounding box auto-defined on any inverses?  And leave it to the model builder to define them?

**Comment by pllim** [comment]
> Maybe it would be best to not have any bounding box auto-defined on any inverses? And leave it to the model builder to define them?

Sounds reasonable to me. 👍

**Comment by mcara** [comment]
To me too

**Comment by mcara** [comment]
On the other hand, a bounding box, with all the obvious limitations (i.e., sides parallel to the coordinate axes), is a bounding box and people understand its limitations. So, I do not see a big problem with automatic assignment of bounding boxes to inverse transforms.

I think a model should know when it can automatically assign a bounding box to its inverse. For `Scale` and `Shift` this is so easy, it should not be an issue. Even for strange models such as `Sin(x)` the bounding box for its inverse is quite obvious `[-1,1]`. To summarize, it may be helpful if a model could do this automatically when it is straightforward (but it has to be done correctly) and not to assign a box for complicated/controversial things (such as inverse of `ArcSin(x)` - it could be `[0,2pi]` or `[0,4pi]` or `[2pi, 4pi]`, `[-inf, inf]`, etc.)

If this cannot be done consistently, then just not assigning it would be OK too.
