### ISSUE TITLE
CI breakage: Vizier sesame lookup for NGC

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10711]
There are two outstanding CI errors that require upstream fixes. Documenting them here for the record:

- [x] RTD: readthedocs/readthedocs.org#7451 -- @saimn pointed out that readthedocs/readthedocs.org#7442 might resolve this.
- [x] Remote data failure for `name_resolve.py` test -- See #10710 for more information. I have emailed the service provider.

**Comment by pllim** [comment]
RTD should be fixed already.

**Comment by saimn** [comment]
Sesame is back:
```
❯ curl http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/V\?NGC%203642                         
# NGC 3642	#Q426467
#=Vl=VizieR (local):    1     0ms (from cache)
%J 170.5594 +59.0795 = 11:22:14.2  +59:04:46  
%I.0 {NGC} 3642

#====Done (2020-Sep-04,08:52:16z)====
```
I guess we can close this issue.

**Comment by pllim** [comment]
Yes, CDS did reply and said they fixed server issue upstream. 😸
