### ISSUE TITLE
add the Spat unit for solid angles

### ISSUE THREAD

**Issue by ntessore** [astropy/astropy#10721]
### Description

Add the [Spat unit of solid angle](https://en.wikipedia.org/wiki/Spat_(unit)), where 1 Spat = 4 sterad is the angle subtended by the entire sphere. This would make it possible to give "fsky" sky fractions as quantities of solid angle in a not too contrived way.

(Although I do concede that I have also never heard of the "spat" until I came across it just now.)

**Comment by mhvk** [comment]
@ntessore - as the one who added `cycle` quite a while ago, I appreciate this!

Would you be interested in creating a pull request? As you can see from my #1160 for cycle (which includes a few misses on the way...), it is not very tricky. Like for cycles, I think it may make sense not to include prefixes (i.e., no "mSpat"), but if you feel differently, we can discuss.

**Comment by ntessore** [comment]
@mhvk Sure, thanks for asking. I wanted to open a PR but I wasn't sure what else needs changing/testing besides adding the unit. Is following your PR enough?

**Comment by pllim** [comment]
cc @embray in case he can assist on the workflow aspect of things. 😄  Thank you, all!

**Comment by ntessore** [comment]
Thanks everyone, I had the change on disk already and opened #10726 for this discussion. I added the tests I found using a quick grep for `cycle`.
