### ISSUE TITLE
Bug in SkyCoord unit kwarg when distance is specified

### ISSUE THREAD

**Issue by parejkoj** [astropy/astropy#10725]
I believe I've found a bug with the `unit` argument of `SkyCoord`. Specifying `unit` and `distance` to the `SkyCoord` constructor results in a `UnitConversionError`, while providing the ra/dec values as `astropy.units.Quantity` objects does not:

```python
from astropy.coordinates import SkyCoord, Distance
import astropy.units as u

# no error
coord1=SkyCoord(ra=10*u.deg, dec=10*u.deg,
               obstime="J2000",
               pm_ra_cosdec=10*u.mas/u.yr,
               pm_dec=10*u.mas/u.yr,
               distance=Distance(parallax=10*u.mas))

# UnitConversionError: 'pc' (length) and 'deg' (angle) are not convertible
coord2=SkyCoord(ra=10, dec=10, unit="deg"
               obstime="J2000",
               pm_ra_cosdec=10*u.mas/u.yr,
               pm_dec=10*u.mas/u.yr,
               distance=Distance(parallax=10*u.mas))
```

I think this is due to something not getting the correct equivalency somewhere, based on the same error being described on the [equivalency page](https://docs.astropy.org/en/stable/units/equivalencies.html#how-to-convert-parallax-to-distance), but I don't know how.

`astropy.__version__` reports `4.0.1.post1`.

EDIT: Syntax highlighting.

**Comment by astrojuanlu** [comment]
Complete traceback for future reference:

```
>>> from astropy.coordinates import SkyCoord, Distance
>>> import astropy.units as u
>>> coord2=SkyCoord(ra=10, dec=10, unit="deg",
...                obstime="J2000",
...                pm_ra_cosdec=10*u.mas/u.yr,
...                pm_dec=10*u.mas/u.yr,
...                distance=Distance(parallax=10*u.mas))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/Personal/Astropy/astropy/astropy/coordinates/sky_coordinate.py", line 312, in __init__
    skycoord_kwargs, components, info = _parse_coordinate_data(
  File "/home/juanlu/Personal/Astropy/astropy/astropy/coordinates/sky_coordinate_parsers.py", line 245, in _parse_coordinate_data
    valid_components.update(_get_representation_attrs(frame, units, kwargs))
  File "/home/juanlu/Personal/Astropy/astropy/astropy/coordinates/sky_coordinate_parsers.py", line 591, in _get_representation_attrs
    valid_kwargs[frame_attr_name] = repr_attr_class(value, unit=unit)
  File "/home/juanlu/Personal/Astropy/astropy/astropy/units/quantity.py", line 300, in __new__
    value = value.to(unit)
  File "/home/juanlu/Personal/Astropy/astropy/astropy/units/quantity.py", line 689, in to
    return self._new_view(self._to_value(unit, equivalencies), unit)
  File "/home/juanlu/Personal/Astropy/astropy/astropy/units/quantity.py", line 660, in _to_value
    return self.unit.to(unit, self.view(np.ndarray),
  File "/home/juanlu/Personal/Astropy/astropy/astropy/units/core.py", line 987, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/home/juanlu/Personal/Astropy/astropy/astropy/units/core.py", line 918, in _get_converter
    raise exc
  File "/home/juanlu/Personal/Astropy/astropy/astropy/units/core.py", line 903, in _get_converter
    return self._apply_equivalencies(
  File "/home/juanlu/Personal/Astropy/astropy/astropy/units/core.py", line 886, in _apply_equivalencies
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'pc' (length) and 'deg' (angle) are not convertible
```

**Comment by astrojuanlu** [comment]
I think this docstring:

https://github.com/astropy/astropy/blob/aeabab1a50af0d0b1507d03911d6b3cd632bbc37/astropy/coordinates/sky_coordinate.py#L222-L225

is not up to date with the behavior here:

https://github.com/astropy/astropy/blob/aeabab1a50af0d0b1507d03911d6b3cd632bbc37/astropy/coordinates/sky_coordinate_parsers.py#L347-L348

And that's why it's trying to operate `deg` (the inferred unit for `distance`) with `pc` (the real unit of `distance`):

```
>>> Distance(parallax=10*u.mas)
<Distance 100. pc>
```

This, on the other hand, works:

```
>>> coord2=SkyCoord(ra=10, dec=10, unit=("deg", "deg", "pc"),  # Note the three units
...                obstime="J2000",
...                pm_ra_cosdec=10*u.mas/u.yr,
...                pm_dec=10*u.mas/u.yr,
...                distance=Distance(parallax=10*u.mas))
>>> coord2
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, pc)
    (10., 10., 100.)
 (pm_ra_cosdec, pm_dec) in mas / yr
    (10., 10.)>
```

As a quick idea, we could:

- Fix the docstring and only expand the `unit: str` to a list of two values,
- Give a better error message if a scalar `unit` and a unitless `distance` is specified

**Comment by astrojuanlu** [comment]
...however, there are certain cases in which it does make sense to expand a single `str` unit to three values:

```
>>> coord3=SkyCoord(x=10, y=10, unit="km",
...                obstime="J2000",
...                z=Distance(parallax=10*u.mas),
...                representation_type="cartesian")
>>> coord3
<SkyCoord (ICRS): (x, y, z) in km
    (10., 10., 3.08567758e+15)>
```

**Comment by pllim** [comment]
FWIW throwing an error is less surprising, so that gets my vote. Great investigation, @astrojuanlu ! And thanks for reporting, @parejkoj .

**Comment by parejkoj** [comment]
Thanks for the sleuthing, @astrojuanlu ! However, I'm confused by this suggestion:

> Give a better error message if a scalar unit and a unitless distance is specified

In my example, distance is not unitless, it has units of parsec:

```
In [2]: Distance(parallax=10*u.mas)
Out[2]: <Distance 100. pc>
```

Certainly, fixing the docstring is in order, since it currently says that it only applies to LAT and LON, not `distance`. But if `distance` comes in with a unit, I don't think the value of `unit` should be applied to it, no?

**Comment by astrojuanlu** [comment]
> But if distance comes in with a unit, I don't think the value of unit should be applied to it, no?

You're right @parejkoj! In this case the code should definitely work without error, I'd say. Similar to what happens here:

```
In [11]: coord2=SkyCoord(ra=10, dec=0.18 * u.rad, unit="deg",  # ra is unitless, but dec has units
    ...:                 obstime="J2000",
    ...:                 pm_ra_cosdec=10*u.mas/u.yr,
    ...:                 pm_dec=10*u.mas/u.yr)  # No distance                                                                                                                                                                                       

In [12]: coord2                                                                                                                                                                                                                               
Out[12]: 
<SkyCoord (ICRS): (ra, dec) in deg
    (10., 10.31324031)
 (pm_ra_cosdec, pm_dec) in mas / yr
    (10., 10.)>
```

**Comment by astrojuanlu** [comment]
...I am not so sure that this should just work straight away. Notice that cylindrical coordinates also have this sort of problem:

```
In [26]: coord4=SkyCoord(rho=10 * u.m, phi=0.18, z=1 * u.m, unit="deg",
    ...:                 representation_type="cylindrical")                                                                                                                                                                                   
---------------------------------------------------------------------------
UnitConversionError                       Traceback (most recent call last)
<ipython-input-26-08b5d36b9fae> in <module>
----> 1 coord4=SkyCoord(rho=10 * u.m, phi=0.18 * u.deg, z=1 * u.m, unit="deg",
      2                 representation_type="cylindrical")

...

UnitConversionError: 'm' (length) and 'deg' (angle) are not convertible
```

One option would be to "fill the gaps" of the `**kwargs` passed without units, however this would make the behavior of `unit="deg"` and `unit=("deg", "deg", "???")` different: in the former case we would be filling the gaps, in the latter case we would be checking potential overlaps between the elements of `unit=` and any `**kwargs` specified as a `Quantity`. Also, it's not clear what the value is of specifying the unit as text for one parameter and as a `Quantity` for another.

The more I think about this, the more I'm inclined towards **raising an error if `unit=` was passed at the same time as specifying quantities for _any_ of the `**kwargs`**. This is of course the most unforgiving option, and I'd say the easiest one to implement. However, in the docstring of `SkyCoord` there is no example of such mixing and no explanation about the behavior of `unit=` for more complex cases (we already said it's outdated), so I would say this has been undefined behavior so far.

**Comment by astrojuanlu** [comment]
xref: gh-10728

**Comment by mhvk** [comment]
Sort of agree that the error here is actually OK, though I could also live with treating spherical as a special case, where distance can have its own unit. Overall, am not sure it is worth insisting that its either quantities or units - for `Quantity` itself, one can pass in a quantity and a unit, which just means the quantity will be converted to that unit. I think I'd go with just clarifying the docstring...

**Comment by adrn** [comment]
I think I agree with @mhvk and @pllim (I would expect an error here). So, 👍 to clarifying the docstring. One other idea is that we could catch the `UnitConversionError` and add an error message that more precisely points to the error, with a possible solution. Something along the lines of "\<original error message\> This can occur when passing units for some coordinate components when other components are specified as Quantity objects. Either pass a list of units for all components (and unit-less coordinate data), or pass Quantities for all components."

**Comment by parejkoj** [comment]
A clearer error would definitely have helped, as would docstring clarification. @adrn 's suggestion about the error message sounds ideal to me, although it might have taken me some time to determine that `distance` was the parameter that was causing the problem.

In summary, "why not both"?
