### ISSUE TITLE
HDF5 metadata handling

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#10736]
### Description
 
PR #7007 fundamentally changed how astropy creates hdf5 files.

Before, the native way of storing metadata to hdf5, hdf5 attributes were used.
This was a good way for interoperability.

The new way stores a custom, second dataset along the normal dataset with the metadata.
This is a very non standard approach that hurts the interoperability of hdf5 files created through astropy.
It also makes it necessary to copy these metadata datasets when copying datasets, while attributes are automatically included when copying a single dataset.

I think it should be possible to at least optionally use the approach taken before and use normal hdf5 attributes for metadata to improve interoperability.

**Comment by pllim** [comment]
cc @taldcroft and @mhvk

**Comment by MaxNoe** [comment]
Feature request since the current behaviour is intentional.

**Comment by mhvk** [comment]
IIRC, the old method allowed very little to be properly serialized. But if it was nevertheless useful, it would seem fine to allow it as an option.

Ideally, of course, we would make HDF5 a bit more like FITS, in using whatever options it has as much as possible, but having a way to ensure one can round-trip (`astropy_native=True`).

p.s. Even though I've started to use it, I'm very much not an HDF5 expert, so am afraid the most I could do here is help review.

**Comment by taldcroft** [comment]
@MaxNoe - can you please follow the bug report template and provide an example of what you did, what you got and what you expected?  From what I can see I get the expected result by using `serialize_meta=False`.
```
In [1]: astro                                                                                                                                   
astropy=4.2.dev573+gd6bc4e92e.d20200830
In [2]: t = simple_table()                                                                                                                      
In [3]: t.meta['a'] = 'hello'                                                                                                                   
In [4]: t.write('junk.h5', format='hdf5', path='root', serialize_meta=False, overwrite=True)                                                    

(astropy) ➜  astropy git:(time-base) ✗ h5dump junk.h5 
HDF5 "junk.h5" {
GROUP "/" {
   DATASET "root" {
      DATATYPE  H5T_COMPOUND {
         H5T_STD_I64LE "a";
         H5T_IEEE_F64LE "b";
         H5T_STRING {
            STRSIZE 1;
            STRPAD H5T_STR_NULLPAD;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         } "c";
      }
      DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
      DATA {
      (0): {
            1,
            1,
            "c"
         },
      (1): {
            2,
            2,
            "d"
         },
      (2): {
            3,
            3,
            "e"
         }
      }
      ATTRIBUTE "a" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "hello"
         }
      }
   }
}
}
```

**Comment by MaxNoe** [comment]
Than I completely misunderstood the option, the warning and the documentation for that option.

I understood all those points to mean that `serialize_metadata=False` to mean that no metadata is saved at all.

**Comment by taldcroft** [comment]
The current docs in https://docs.astropy.org/en/latest/io/unified.html#metadata-and-mixin-columns are:

"By default, when writing a table to HDF5 the code will attempt to store each key/value pair within the table meta as HDF5 attributes of the table dataset. This will fail as the values within meta are not objects that can be stored as HDF5 attributes. In addition, if the table columns being stored have defined values for any of the above-listed column attributes, these metadata will not be stored and a warning will be issued."

Can you suggest some improvements that would have helped you out?

**Comment by MaxNoe** [comment]
Yes, I interpreted that to mean that all values cannot be stored.

**Comment by taldcroft** [comment]
Once you "require a convention", then you are already on the path to something custom to astropy. Just because it is a simpler convention does not actually solve the interoperability issue because you require custom downstream software to make use of it. Also this ends up being incomplete -- yes, you have handled `unit` but drop `description` and `format` and per-column `meta`. So astropy has taken the approach of just two possibilities:

- Handle only `table.meta` values which can fit into standard HDF5 attributes, with a user warning if meta data are being dropped.
- Handle all `table.meta` and column meta data fully by using a robust convention of serializing to YAML. There is support for YAML parsing in all common languages, so this is fully interoperable.

**Comment by mhvk** [comment]
I had forgotten about the `serialize_meta` option, sorry!

@MaxNoe - if there are widely used conventions on how to store, say, just the unit in the hdf5 file, I don't see a reason we could not support that (if intrusive, perhaps as a string option for `serialize_meta`). But from a quick search, it doesn't seem there is much convergence to a standard: https://forum.hdfgroup.org/t/machine-readable-units-format/5480/42

p.s. I do recall when we implemented `serialize_meta=True` that @taldcroft on purpose went for the extra payload, to avoid space limitations for attributes on the data payload. It is unfortunate that that means a copy of the payload loses the information.

**Comment by taldcroft** [comment]
@mhvk - thanks for bringing up that thread about HDF5 unit support.  From what I see there, they made some progress on defining a specification but did not converge.

Takeaway - if / when HDF5 has adopted a formal convention for units then astropy should definitely support it.

**Comment by taldcroft** [comment]
@MaxNoe, @mhvk - please see #10743. Does this help and suffice to close this issue? We can, in theory, open a new issue to support HDF5 units if there is ever a convention. But I've gotten somewhat less excited about opening placeholder issues like that for things that might never happen.

**Comment by MaxNoe** [comment]
Yes, ok, thanks for clearing up the docs.

**Comment by mhvk** [comment]
Agreed that without an actual convention or even a placeholder convention, there is little point having an issue: it would essentially be to create a convention in another package...
