### ISSUE TITLE
Row iteration over tables with units

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#10735]
### Description
Right now, there seems to be no means to iterate of the rows of a table that includes the units.

Both accessing the `Row` object like in

```
for row in table:
    print(row['x'])
```

and using
```
for x, y, in table.iterrows('x', 'y'):
    print(x, y)
```

Does only yield floats and not quantities with units.

**Comment by taldcroft** [comment]
Are you using QTable?
```
In [1]: astro                                                                   
astropy=4.0.1.post1

In [2]: t = QTable([[1,2] * u.m])                                               

In [5]: for row in t: 
   ...:     print(row['col0'], type(row['col0'])) 
   ...:                                                                         
1.0 m <class 'astropy.units.quantity.Quantity'>
2.0 m <class 'astropy.units.quantity.Quantity'>
```

(In general when possible please provide a reproducible demonstration of the problem in a bug report, thanks!).

**Comment by MaxNoe** [comment]
Now, I just heard of it for the first time! Thanks.
