### ISSUE TITLE
4.1rc2: test_generate_config fails when astropy installed on different disk from test run

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10747]
### Description

```
____________________________ test_generate_config _____________________________

tmp_path = WindowsPath('C:/.../pytest-1/test_generate_config0')

    def test_generate_config(tmp_path):
        from astropy.config.configuration import generate_config
        out = io.StringIO()
>       generate_config('astropy', out)

C:\...\astropy\config\tests\test_configs.py:135:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\...\astropy\config\configuration.py:625: in generate_config
    importlib.import_module(mod.name)
C:\...\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:783: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
C:\...\astropy\convolution\setup_package.py:9: in <module>
    C_CONVOLVE_PKGDIR = os.path.relpath(os.path.dirname(__file__))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = 'C:\\...\\astropy\\convolution'
start = '.'

    def relpath(path, start=None):
        """Return a relative version of a path"""
        path = os.fspath(path)
        if isinstance(path, bytes):
            sep = b'\\'
            curdir = b'.'
            pardir = b'..'
        else:
            sep = '\\'
            curdir = '.'
            pardir = '..'

        if start is None:
            start = curdir

        if not path:
            raise ValueError("no path specified")

        start = os.fspath(start)
        try:
            start_abs = abspath(normpath(start))
            path_abs = abspath(normpath(path))
            start_drive, start_rest = splitdrive(start_abs)
            path_drive, path_rest = splitdrive(path_abs)
            if normcase(start_drive) != normcase(path_drive):
>               raise ValueError("path is on mount %r, start on mount %r" % (
                    path_drive, start_drive))
E                   ValueError: path is on mount 'C:', start on mount 'D:'

C:\...\lib\ntpath.py:703: ValueError
```

**Comment by pllim** [comment]
@embray , do you grok the traceback enough to suggest a fix for this? Looks like Python's `importlib.import_module(mod.name)` chokes on `C_CONVOLVE_PKGDIR` defined in `astropy.convolution` sub-package. My `conda` installation and `~/.astropy` are both in C drive, but I am running the Python session from D drive. It looks like `pytest` created `.hypothesis` and `.pytest_cache` on the D drive folder where I run Python.

**Comment by jdavies-st** [comment]
It looks like there's a mixing of `pathlib.WindowsPath` objects and old-fashioned `os.fspath` here.  Wonder if that could cause an issue.  The test fixture `tmp_path` is providing a `pathlib` object.

**Comment by pllim** [comment]
I cannot reproduce this on dev (but I didn't run the full suite). ❗

**Comment by saimn** [comment]
The problem seems to be that `relpath` cannot work between two different drives, here `C:` for the source code and `D:` for your current working directory. I wonder why `relpath` was used here, using `abspath` instead would fix the issue I guess.

@jdavies-st - In theory `os.path` functions work with `pathlib` objects.

**Comment by pllim** [comment]
The test pass if I run it from editable install, but not from a "real" install from the PyPI tarball. That is...

This works: `pip install -e .`

Does not work: `pip install .`

**Comment by saimn** [comment]
Probably because in editable mode the source files are in `D:` whereas with a normal install they go in the site-packages in `C:` ?

**Comment by pllim** [comment]
That makes sense! If changing `C_CONVOLVE_PKGDIR` to `abspath` doesn't break anything and fixes this, that would be nice. Looks like @jamienoss wrote this back in #7293 . I must not have run the test from non-editable install all these years. 😬  @keflavich , what do you think?

**Comment by keflavich** [comment]
No opinions from me - unfortunately I know little about these configuration files.  I can test on windows now though.

**Comment by pllim** [comment]
> I can test on windows now though

@keflavich , please report back. Thanks!

**Comment by pllim** [comment]
@dhomeier , you are a C-extension expert. Any advise? 😸

**Comment by pllim** [comment]
Turns out this is much bigger than convolution, see #10753 for a potential fix, as @saimn suggested above. Thanks, Simon!

**Comment by dhomeier** [comment]
@pllim my C skills are still solid, I hope, but I never moved on to learn D!
