### ISSUE TITLE
pyinstaller error

### ISSUE THREAD

**Issue by DiamondTop** [astropy/astropy#10761]
error on the below when compling py file on pyinstaller.  command is pyinstaller --noconsole --onefile filename.py

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\leroy\anaconda3\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-IPython.py", line 34, in <module>
    datas += collect_data_files('IPython.extensions', include_py_files=True)
  File "c:\users\leroy\anaconda3\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 712, in collect_data_files
    pkg_base, pkg_dir = get_package_paths(package)
  File "c:\users\leroy\anaconda3\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 506, in get_package_paths
    file_attr = get_module_file_attribute(package)
  File "c:\users\leroy\anaconda3\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 308, in get_module_file_attribute
    raise ImportError('Unable to load module attribute') from e
ImportError: Unable to load module attribute

python code as per below.
==================================
import pandas
import tkinter as tk
from tkinter import filedialog
import os

def analysis():
    path = filedialog.askopenfilename()
    data = pandas.read_excel(path)
    groups = data.groupby('Group')
    table = groups.agg({'Revenue':sum, 'Group': len})
    savename = filedialog.asksaveasfilename()
    savename = savename.split('.')[0] + '.csv'
    table.to_csv(savename)

if __name__ == "__main__":
    window = tk.Tk()
    window.title('Analysis')
    window.geometry("200x150")
    frame = tk.Frame(window)
    frame.grid(row=0, column=0)
    button = tk.Button(frame, text='Generate Table', command=analysis)
    button.grid(row=0, column=1)
    window.mainloop()

**Comment by pllim** [comment]
Hello. There is no usage of astropy anywhere in the report. Did you mean to ask over at `pandas`?

**Comment by DiamondTop** [comment]
no, i do not have a python file named astropy.... 
I am running the pyinstaller my filename is called testing1.py

**Comment by pllim** [comment]
I think there is a misunderstanding. This repository is for `astropy` package, not `pyinstaller` nor `pandas`.

**Comment by pllim** [comment]
Maybe what you want is https://github.com/pandas-dev/pandas/issues

**Comment by DiamondTop** [comment]
ok, thank you.
