### ISSUE TITLE
Move non-astronomy units out of astrophys.py to new misc.py or so

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10769]
Currently, most units are defined in si.py, cgs.py, and astrophys.py. As noted by @adrn in https://github.com/astropy/astropy/pull/10586#issuecomment-698653617, the latter has become a bit of a miscellaneous bunch, including units that are not particular to astronomy at all. It would make sense to move those to a new `misc.py`. Indeed, some are sufficiently obscure that it might be an idea to allow these to be removed from the name space (though they would of course be present by default).

**Comment by pllim** [comment]
@mhvk , would be nice to have a clear list of what goes where here, so if someone else is interested to work on this, they do not have to go digging in past conversation. But if you plan to tackle this yourself, then there is no need to clarify but you should assign yourself to the issue. Thanks!

**Comment by adrn** [comment]
From a closer look: bar, barn, bin, bit, byte, cycle, dalton, pixel, spat, torr
