### ISSUE TITLE
CI update to pytest 6.1 breaks [tool:pytest] config options

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#10773]
### Description
circleci and travis just seem to have updated their pytest to 6.1.0, which fails on all installations on some `setup.cfg` options in `[tool:pytest]`:
`INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: asdf_schema_root`

`INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: qt_no_exception_capture`

### Steps to Reproduce
see https://circleci.com/gh/astropy/astropy/76632 and https://travis-ci.org/github/astropy/astropy/builds/730653402

The failure/fatal warning has been moved to an earlier stage with 6.1, and I could fix this locally by extending #10730.

**Comment by dhomeier** [comment]
> Might be a simple syntax change; I haven't investigated further.

https://docs.pytest.org/en/stable/deprecations.html#pytest-section-in-setup-cfg-files

**Comment by dhomeier** [comment]
Closed by #10730, thanks @pllim!

**Comment by pllim** [comment]
Thank YOU!
