### ISSUE TITLE
DOC: Update/remove command history files

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10777]
I don't think these are rendered anywhere, but if we want to keep them, they should be updated. Otherwise, we should remove them.

* https://github.com/astropy/astropy/blob/master/docs/development/workflow/command_history.rst
* https://github.com/astropy/astropy/blob/master/docs/development/workflow/command_history.sh
* https://github.com/astropy/astropy/blob/master/docs/development/workflow/command_history_with_output.sh

As discussed in https://github.com/astropy/astropy/pull/10756#discussion_r495610425

**Comment by astrojuanlu** [comment]
These files were removed in #10849:

> Also deleted outdated command history and terminal case.

Closing!

**Comment by pllim** [comment]
Ops, my bad for not closing this earlier. Thanks for catching it!
