### ISSUE TITLE
Advertise tox in coding guidelines

### ISSUE THREAD

**Issue by astrojuanlu** [astropy/astropy#10787]
Spotted this in [the coding guidelines](https://docs.astropy.org/en/stable/development/codeguide.html?highlight=flake8#coding-style-conventions):

```
flake8 astropy --count --select=E101,W191,W291,W292,W293,W391,E111,E112,E113,E30,E502,E722,E901,E902,E999,F822,F823
```

however, the pull request template encourages the much simpler `tox -e codestyle`. We should replace it.

**Comment by addddd123** [comment]
Hey i am new here can you tell me what is 'tox -e codestyle' where i can found this template.....

**Comment by DiegoAsterio** [comment]
This issue is already solved inside the repo (?)

https://github.com/astropy/astropy/blob/master/docs/development/codeguide.rst

**Comment by astrojuanlu** [comment]
@DiegoAsterio woops, you are absolutely right. Closing!
