### ISSUE TITLE
Slow coordinate example in documentation build

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#10794]
Looking at pages that could make the documentation build slower than necessary, the coordinate page is the slowest by far (thanks to the `sphinx.ext.duration` extension). This is with a clean repository:
```
====================== slowest reading durations =======================
70.252 coordinates/index
14.204 visualization/wcsaxes/ticks_labels_grid
8.617 timeseries/index
7.544 visualization/wcsaxes/overlays
6.673 stats/ripley
```
And then running again, so with the cache and just a small change to `coordinates/index.rst`:
```
====================== slowest reading durations =======================
73.007 coordinates/index
0.552 api/astropy.coordinates.EarthLocation
```
This lead me to the [Performance tips](https://docs.astropy.org/en/latest/coordinates/index.html#performance-tips) (!), in particular the last example which is running some benchmark to produce a plot (_Transformation of SkyCoord with 100.000 obstimes over 12 hours_). If I remove `performance.inc.rst` then the page takes ~2.5s to build.

Running the last example manually gives:
```
No Interpolation took 0.3208 s
Interpolation with        0 s resolution took 33.4733 s (  0.0x faster) 
Interpolation with        1 s resolution took 9.1881 s (  0.0x faster) 
Interpolation with       10 s resolution took 1.2020 s (  0.3x faster) 
Interpolation with      100 s resolution took 0.3375 s (  1.0x faster) 
Interpolation with     1000 s resolution took 0.2250 s (  1.4x faster) 
Interpolation with    10000 s resolution took 0.1892 s (  1.7x faster) 
Interpolation with   100000 s resolution took 0.1719 s (  1.9x faster) 
CPU times: user 45.4 s, sys: 61.8 ms, total: 45.5 s
Wall time: 45.6 s
```

Could we avoid running this benchmark in the docs build (>1min over the 7/8 min of a build on my laptop) ? Or not run the first two steps, or run this in the benchmark repo ?

**Comment by taldcroft** [comment]
@saimn - excellent sleuthing and I am definitely 👍  on improving docs build times. Could this example be moved out of the core docs and into astropy learn examples and then linked? Or just use a static png of the plot?  

Maybe the simplest of all is just reducing the number of points. Would the example still demonstrate the performance lesson using 10_000 or even 1000 points?

**Comment by astrofrog** [comment]
@saimn how did you find the build times?

**Comment by astrofrog** [comment]
Yeah we could just remove:

```
Interpolation with        0 s resolution took 33.4733 s (  0.0x faster) 
Interpolation with        1 s resolution took 9.1881 s (  0.0x faster) 
```

**Comment by astrofrog** [comment]
But why are we even running this as part of the docs build? I guess the outputs are too noisy to include as a doctest?

**Comment by saimn** [comment]
@astrofrog - the build times for ? 
- To get the slowest pages it's by adding `sphinx.ext.duration` to Sphinx extensions.
- For the example, just running it manually will show the timings.

**Comment by mhvk** [comment]
Hmm, I reviewed #10647 where this part was introduced; sorry that I didn't catch that it was such a time-consuming test! 

I think there is no reason not to use fewer coordinates - the tip is about interpolating in time, so should scale directly with the number of coordinates (but cc @MaxNoe in case). Also, much of the test can only be run with `remote_data`, so every part of the test could be marked as such (I forget if we have a simple way to mark everything rather than adding `# doctest: +REMOTE_DATA` to every line).

**Comment by astrofrog** [comment]
@saimn - I meant the first, I did not know about sphinx.ext.duration, super useful!

**Comment by MaxNoe** [comment]
It's kind of the point of this example that astropy's default behavior is slow here and the real benefit comes when many points are transformed at once. 

I can try to reduce the number of points,  but a somewhat large amount is required for the example (and the plot) to make sense

**Comment by MaxNoe** [comment]
Also i am confused to see your manual output.  The speed ups are far too small and the default way to fast.  
In the PR, the speed up was up to 120x

**Comment by MaxNoe** [comment]
If I reduce the number of points by two orders of magnitude (and also reduce the time duration, to keep the same mean time difference between the points), I get:

```
No Interpolation took 0.8006 s
Interpolation with       0.1 s resolution took 0.2448 s (  3.3x faster) 
Interpolation with       1.0 s resolution took 0.0624 s ( 12.8x faster) 
Interpolation with      10.0 s resolution took 0.0116 s ( 68.8x faster) 
Interpolation with     100.0 s resolution took 0.0062 s (129.1x faster) 
Interpolation with    1000.0 s resolution took 0.0056 s (142.5x faster) 
Interpolation with   10000.0 s resolution took 0.0055 s (145.0x faster) 
Interpolation with  100000.0 s resolution took 0.0056 s (141.9x faster) 
python test.py  3,42s user 0,14s system 30% cpu 11,477 total
```

Should be do that?

**Comment by saimn** [comment]
> It's kind of the point of this example that astropy's default behavior is slow here and the real benefit comes when many points are transformed at once.

Maybe, I don't judge the example itself, but I think the documentation build is not the right place to prove this point.

> Also i am confused to see your manual output. The speed ups are far too small and the default way to fast.
In the PR, the speed up was up to 120x

Indeed, not sure what went wrong, this is what I get now on master:
```
No Interpolation took 24.3814 s
Interpolation with        0 s resolution took 36.9377 s (  0.7x faster) 
Interpolation with        1 s resolution took 10.2022 s (  2.4x faster) 
Interpolation with       10 s resolution took 1.3314 s ( 18.3x faster) 
Interpolation with      100 s resolution took 0.3780 s ( 64.5x faster) 
Interpolation with     1000 s resolution took 0.2607 s ( 93.5x faster) 
Interpolation with    10000 s resolution took 0.2166 s (112.6x faster) 
Interpolation with   100000 s resolution took 0.1967 s (123.9x faster) 
CPU times: user 1min 14s, sys: 240 ms, total: 1min 14s
Wall time: 1min 14s
```
