### ISSUE TITLE
astropy warnings give no information about where the warning was triggered

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#10808]
A typical astropy warning looks like this:
```python
WARNING: AstropyDeprecationWarning: Transforming a frame instance to a frame class (as opposed to another frame instance) will not be supported in the future.  Either explicitly instantiate the target frame, or first convert the source frame instance to a `astropy.coordinates.SkyCoord` and use its `transform_to()` method. [astropy.coordinates.baseframe]
```
From this, there is no way to work out or trace where the warning has come from. This means it is very tricky to understand how to fix the offending code. Compare with a standard python warning, which displays the file and line-number that triggered the warning:
```python
/Users/dstansby/github/astropy/astropy/visualization/wcsaxes/core.py:211: MatplotlibDeprecationWarning: Passing parameters norm and vmin/vmax simultaneously is deprecated since 3.3 and will become an error two minor releases later. Please pass vmin/vmax directly to the norm when creating it.
  return super().imshow(X, *args, origin=origin, **kwargs)
```
This shows both the file and line number that raised the warning, which makes it much easier to understand how to fix the warning. I guess this is therefore a feature request for astropy warnings to also give this information.

**Comment by dstansby** [comment]
I realised that giving the file number/name isn't actually that helpful, as that doesn't link to where in the user code the warning was triggered from.

**Comment by taldcroft** [comment]
One strategy to deal with this problem is turn that warning into an exception using https://docs.python.org/3/library/warnings.html#warnings.filterwarnings. Then you will get a stack trace.

**Comment by astrojuanlu** [comment]
Not sure if this helps, but recently I learned on twitter than setting `stacklevel=2` adds more information:

![Screenshot_2020-10-07 Twitter Publish](https://user-images.githubusercontent.com/316517/95321234-0c0c0700-089b-11eb-922c-42303e14b6d1.png)

**Comment by saimn** [comment]
The problem is that by default Astropy catches its own warnings and redirect them to its logger. And doing that it loses the origin of the warning... To disable this: https://docs.astropy.org/en/latest/logging.html
```
from astropy import log
log.disable_warnings_logging()
```
Then you will see a real warning (instead of a logger warning) with the source file and line. And typically our `deprecated` decorator uses already `stacklevel=2` so it would show the function that made the deprecated call.
