### ISSUE TITLE
Make convolve work with units

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#10811]
### Description

It would be great if one could properly convolve arrays with units. Currently, the units are stripped off:
```python
>>> import numpy as np
>>> import astropy.units as u
>>> from astropy.convolution import convolve
>>> convolve(np.array([1, 4, 5, 6, 5, 7, 8])*u.ph, [0.2, 0.6, 0.2])
array([1.4, 3.6, 5. , 5.6, 5.6, 6.8, 6.2])
```
As the workaround here is simple (`convolve(a.value, kernel) * a.unit`), it is not urgent at all. User code would ofcourse look better if this would be handled by convolve itself.

**Comment by pllim** [comment]
cc @keflavich

**Comment by keflavich** [comment]
Seems like an easy and low-cost feature.  :+1:

**Comment by george-galvin** [comment]
Hey guys, I'm looking to get familiar with this project, I can quickly handle this issue if no-one's working on it :)
