### ISSUE TITLE
Make file paths without checking file exists

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#10816]
The ability to construct file paths relative to a specified package is very nice. One limitation of current functions in `utils.data` is that the file paths must point to existing files.

I've mocked up a simple function that makes paths while only requiring that the `package` argument actually exists.

Something like this might be a useful addition to `utils.data`?

```python
def make_pkg_data_path(*data_name: str, package=None):
    """Get path to file.

    Similar to :func:`~astropy.utils.data.get_pkg_data_filename`, but only
    gets the path to the file, does not check if the file exists.
    The package director must exist.

    Parameters
    ----------
    *data_name : tuple of str
        the path, without folder delimiters (which are platform specific)
        relative to `package`.

        One of the following:

        * The name of a directory included in the source
          distribution.  The path is relative to the module
          calling this function.  For example, if calling from
          ``astropy.pkname``, use ``'data'`` to get the
          files in ``astropy/pkgname/data``.
        * Remote URLs are not currently supported.

    package : str, optional
        If specified, look for a file relative to the given package, rather
        than the default of looking relative to the calling module's package.

    Returns
    -------
    filename : str
        A file path on the local file system corresponding to the data
        requested in ``data_name``.

    """
    fps = list(get_pkg_data_filenames(".", package=package))
    filename = pathlib.Path(fps[0]).parent.joinpath(*data_name)

    return str(filename)
```

**Comment by pllim** [comment]
Probably overkill. There is already a function for this, but unfortunately it is "hidden". Exposing it as public function is a possibility. Not sure why it is hidden. @embray , you were involved in the early days when this was written, do you remember why this function is hidden?

```python
>>> from astropy.utils.data import _find_pkg_data_path
>>> dirname = _find_pkg_data_path('data', package='astropy.io.fits')
>>> dirname
'/path/to/astropy/io/fits/data'
```

**Comment by bsipocz** [comment]
I feel this is a case where the proposed functionality is useful in cases, but probably shouldn't live in astropy when there is a initiative to scale back on the generic utilities stuff.

cc @mhvk, too as one of the proponents of descoping.

**Comment by nstarman** [comment]
Interesting. what is the plan for the existing utilities? Will they be moved to an affiliate package?

If this function already exists, but as a private method, is it more *re*-scoping then adding. 🤞

**Comment by mhvk** [comment]
Indeed, I like having less clutter! That said, the `utils.data` module is special among `utils` in actually having its own section in the documentation, so seems less likely to go somewhere. My own feeling is that if a private function is useful, and all it would take is a slightly more elaborate docstring, we might as well expose it. But no strong feelings either way...

**Comment by pllim** [comment]
I don't have objection to exposing it as public function. Already did that to `is_url`. I guess the original intend of `data.py` was for `astropy` core lib internal use only, but then we started using it for affiliated packages, and now it is widely used.

As for moving it, not sure. I think exposing it is the path of least resistance for now.

**Comment by embray** [comment]
+1 to making it public though I might rename it e.g., to just `get_pkg_data_path`, since "find" is a little confusing and misleading.  There is also already `get_pkg_data_filenames` which can technically be used for this as well.

**Comment by pllim** [comment]
> There is also already `get_pkg_data_filenames` which can technically be used for this as well.

@embray , how exactly? Seems to return empty list when there is no match.

```python
>>> from astropy.utils.data import get_pkg_data_filenames
>>> list(get_pkg_data_filenames('data', package='astropy.utils.tests', pattern='*.ggg'))
[]
>>> list(get_pkg_data_filenames('data', package='astropy.utils.tests'))                         
['/my/path/astropy/utils/tests/data/.hidden_file.txt',
 ...,
 '/my/path/astropy/utils/tests/data/dataurl_mirror']
```

**Comment by embray** [comment]
Why would you put a pattern for which there would be no match?  If you put just the filename as the pattern it will match.  E.g. this works:

```python
>>> list(get_pkg_data_filenames('data', package='astropy.utils.tests', pattern='.hidden_file.txt'))
['/home/embray/src/astropy/astropy/astropy/utils/tests/data/.hidden_file.txt']
```

So you could write:

```python
def get_pkg_data_filename(path, package=None):
    return get_pkg_data_filenames(os.path.dirname(path), package=package, pattern=os.path.basename(path))[0]
```

It's pretty round-about but it works.  A moot point now that we're just making the other existing function public.
