### ISSUE TITLE
Different values for biweight_scale when using axis

### ISSUE THREAD

**Issue by lwpiotr** [astropy/astropy#10820]
### Description

The values produced by astropy.stats.biweight_scale functions on a multidimensional array along the last axis are different for some indices than when calculating astropy.stats.biweight_scale only on a specific index (1D vector from the array)

### Expected behavior
I expected
`astropy.stats.biweight_scale(details[3,5])`
to be equal to 
`astropy.stats.biweight_scale(details, axis=2)[3,5]`

### Actual behavior

The output was 0 in the first case, and some ~0.39 in the second

### Steps to Reproduce

1. Please download the numpy file with the 3D array:
https://mega.nz/file/cd5ASAwT#zjZc5TAn2DMAo58Vld3kqOz29Z-7B7pd_9OR7bPejFU
2. Load the file
details = np.load("details.npy")
3. Execute:
```python
print(astropy.stats.biweight_scale(details[3,5]), astropy.stats.biweight_scale(details, axis=2)[3,5])
```
4. You can check that, for example, index [0,0] produces the same results

### System Details

Tested both on:

Linux-5.8.13-100.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
Python 3.7.9 (default, Aug 19 2020, 17:05:11) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
Numpy 1.17.4
astropy 4.0.1.post1
Scipy 1.2.1
Matplotlib 3.1.3

and on:

Linux-5.8.13-100.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
('Python', '2.7.18 (default, Jul 20 2020, 00:00:00) \n[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]')
('Numpy', '1.16.4')
('astropy', u'2.0.14')
('Scipy', '1.2.3')
('Matplotlib', '2.2.5')

EDIT: Fix formatting to show missing text.

**Comment by pllim** [comment]
Is it possible for you to provide an example that does not require downloading a file from an unfamiliar link? Thanks!

**Comment by lwpiotr** [comment]
Fortunately, the issue also appears if I trim the array (otherwise, what could I do, since I can't attach files here?):

import astropy.stats
a = [[[ 0.22, 0.61,-0.35,-0.13,-0.48, 0.84,-0.22,-0.13, 0.  , 0.  , 0.  , 0.  ,-0.48, 0.35, 0.13, 0.48,-0.35,-0.13,-0.48, 0.35, 0.61,-1.32, 1.54,-0.93, 0.58,-0.22,-0.61, 0.84,-0.22,-0.13, 0.  , 0.  , 0.  , 0.  ,-0.48, 0.84,-0.71, 0.71,-0.22,-0.13, 0.  ,-0.48,-0.13, 1.45,-0.58,-0.26, 0.  , 0.  , 0.  ,-0.48, 0.84,-0.22,-0.13,-0.48, 0.35, 0.13, 0.48,-0.84, 0.71,-0.22,-0.13, 0.  , 0.  , 0.  ,-0.48, 0.84,-0.71, 0.71,-0.22,-0.13,-0.48, 0.84,-0.22,-0.13, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,-0.97, 1.67,-0.45,-0.26, 0.  , 0.  ,-0.97, 1.67,-0.45,-0.74, 0.84,-0.22,-0.13, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,-0.48, 0.84,-0.22,-0.13, 0.  , 0.  , 0.  , 0.  ,-0.48, 0.84,-0.71],  [ 0.84,-0.22,-0.13, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,-0.48, 0.35, 0.61,-0.35,-0.13, 0.  , 0.  ,-0.48, 0.84,-0.22,-0.13, 0.  , 0.  , 0.  ,-0.48, 0.84,-0.22,-0.61, 0.84,-0.71, 0.71,-0.22,-0.13, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,-0.48, 0.35, 0.61,-0.35,-0.13, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,-0.48, 0.84,-0.22,-0.13, 0.  , 0.  , 0.  ,-0.48, 0.84,-0.22,-0.13, 0.  , 0.  ,-0.48, 0.84,-0.22,-0.13, 0.  , 0.  , 0.  , 0.  ,-0.48, 0.84,-0.22,-0.13, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,-0.48]]]

Correct behaviour (same results):
print(astropy.stats.biweight_scale(a[0,0]), astropy.stats.biweight_scale(a, axis=2)[0,0])                                                                                                                                             

Incorrect behaviour (different values):
print(astropy.stats.biweight_scale(a[0,1]), astropy.stats.biweight_scale(a, axis=2)[0,1])

**Comment by pllim** [comment]
Thank you! It must have hit some unhandled edge case or something. Let's expand from your example given in https://github.com/astropy/astropy/issues/10820#issuecomment-706876736 .

```python
>>> import platform
>>> import sys
>>> import numpy as np
>>> import astropy
>>> from astropy.stats import biweight_scale
>>> platform.platform()                                                    
'Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-glibc2.10'
>>> sys.version                                                             
'3.8.3 (default, May 19 2020, 18:47:26) \n[GCC 7.3.0]'
>>> astropy.__version__                                                     
'4.2.dev828+g3df2b3281'
>>> np.__version__                                                          
'1.19.1'
>>> a_00 = np.array([ 
        0.22,  0.61, -0.35, -0.13, -0.48,  0.84, -0.22, -0.13,  0.  ,
        0.  ,  0.  ,  0.  , -0.48,  0.35,  0.13,  0.48, -0.35, -0.13,
       -0.48,  0.35,  0.61, -1.32,  1.54, -0.93,  0.58, -0.22, -0.61,
        0.84, -0.22, -0.13,  0.  ,  0.  ,  0.  ,  0.  , -0.48,  0.84,
       -0.71,  0.71, -0.22, -0.13,  0.  , -0.48, -0.13,  1.45, -0.58,
       -0.26,  0.  ,  0.  ,  0.  , -0.48,  0.84, -0.22, -0.13, -0.48,
        0.35,  0.13,  0.48, -0.84,  0.71, -0.22, -0.13,  0.  ,  0.  ,
        0.  , -0.48,  0.84, -0.71,  0.71, -0.22, -0.13, -0.48,  0.84,
       -0.22, -0.13,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  , -0.97,  1.67, -0.45, -0.26,  0.  ,  0.  , -0.97,
        1.67, -0.45, -0.74,  0.84, -0.22, -0.13,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
       -0.48,  0.84, -0.22, -0.13,  0.  ,  0.  ,  0.  ,  0.  , -0.48,
        0.84, -0.71])
>>> a_01 = np.array([
        0.84, -0.22, -0.13,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.48,
        0.35,  0.61, -0.35, -0.13,  0.  ,  0.  , -0.48,  0.84, -0.22,
       -0.13,  0.  ,  0.  ,  0.  , -0.48,  0.84, -0.22, -0.61,  0.84,
       -0.71,  0.71, -0.22, -0.13,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  , -0.48,  0.35,  0.61, -0.35, -0.13,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  , -0.48,  0.84, -0.22, -0.13,  0.  ,
        0.  ,  0.  , -0.48,  0.84, -0.22, -0.13,  0.  ,  0.  , -0.48,
        0.84, -0.22, -0.13,  0.  ,  0.  ,  0.  ,  0.  , -0.48,  0.84,
       -0.22, -0.13,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  , -0.48])
>>> biweight_scale(a_00)                                                   
0.369981353207096
>>> biweight_scale(a_00, axis=0)                                           
0.369981353207096
>>> biweight_scale(a_01)                                                   
0.0
>>> biweight_scale(a_01, axis=0)                                           
0.28965695337987923
```

**Comment by pllim** [comment]
Okay, I think I traced it to where but I'll have to ask @larrybradley on the why. Continuing from https://github.com/astropy/astropy/issues/10820#issuecomment-707166532 ...

When `axis=None`, it stops here (`axis=None`, `mad=0`, `M=0`):

https://github.com/astropy/astropy/blob/3df2b32810212d97aa754adf0a9cc08c5300e0ee/astropy/stats/biweight.py#L124-L125

But when `axis=1`, it continue on and changed `M` to 1 (`axis=0`, `mad=np.array([0.])` going in but then turns into `array([1.])` coming out of the `if`): 

https://github.com/astropy/astropy/blob/3df2b32810212d97aa754adf0a9cc08c5300e0ee/astropy/stats/biweight.py#L127-L129

**Comment by larrybradley** [comment]
#7737 fixed only the case where MAD=0 due to constant data.  #10912 fixes all cases where MAD=0 (due to constant data or mostly-constant data).
