### ISSUE TITLE
Newcomer docs is outdated

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#10841]
We have Outreachy participants running into astropy install issues when following the docs, so the docs needs some updates:

https://docs.astropy.org/en/latest/development/workflow/git_edit_workflow_examples.html#astropy-fix-example

The following is from the slack thread https://astropy.slack.com/archives/C8U8VGQFM/p1602508591046500, they then have run into the issue of the missing `extension-helpers`:

Please I've run into a block walking through [the worked example for contributing code to Astropy](https://docs.astropy.org/en/latest/development/workflow/git_edit_workflow_examples.html#astropy-fix-example). I'm getting the following error when running pytest on the exercise branch (which has been installed into my virtual environment):
```
ImportError while loading conftest 'C:\Users\Mfonism\Codeville\OSSPython\AstroPy\astropy\astropy\conftest.py'.
..\..\__init__.py:104: in <module>
    _check_requirement('erfa', __minimum_erfa_version__)
..\..\__init__.py:98: in _check_requirement
    raise ImportError(msg)
E   ImportError: erfa version 1.7 or later must be installed to use Astropy. erfa is not installed.
```

Pyerfa does however show up in my virtual environment with pip show pyerfa.
```
Name: pyerfa
Version: 1.7.0
Summary: Python bindings for ERFA
Home-page: https://github.com/liberfa/pyerfa
Author: The Astropy Developers
Author-email: astropy.team@gmail.com
License: BSD 3-Clause License
Location: c:\users\mfonism\codeville\osspython\astropy\astropy\env38\lib\site-packages
Requires: numpy
Required-by: astropy
```

**Comment by Cadair** [comment]
I have been looking into this and following the guide I have been unable to reproduce. I have asked the person who ran into it for more details but if others on different platforms / configurations could test that would be really helpful.

**Comment by bsipocz** [comment]
I think #10849 sufficiently addressed this to close it for now. Thanks!
