### ISSUE TITLE
Complete list of functions that lose units

### ISSUE THREAD

**Issue by astrojuanlu** [astropy/astropy#10845]
> you are right that we should add [`np.full`] to the known issues.  One similarly cannot do `np.zeros`, `np.ones`, and `np.empty`.

_Originally posted by @mhvk in https://github.com/astropy/astropy/issues/10836#issuecomment-707302194_

The list in question: https://docs.astropy.org/en/latest/known_issues.html#quantities-lose-their-units-with-some-operations

**Comment by rpsfonseca** [comment]
I'd like to work on this. I understand that we must add `np.full` to the list mentioned here. But by saying 
> One similarly cannot do np.zeros, np.ones, and np.empty
means those should be also added to the list?

**Comment by pllim** [comment]
Yes. Thank you, @rpsfonseca !
