### ISSUE TITLE
Representation conversion can lose information

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#10879]
### Description

When going from a `CylindricalRepresentation` to a `CartesianRepresentation` and back, the output is different than the input.

### Expected behavior

For the input and output to match (modulo some factor of pi for angles).

### Steps to Reproduce

1. Instantiate a `CylindricalRepresentation` with rho and z = 0
2. Represent as a `CartesianRepresentation`
3. Represent step 2 back as a `CylindricalRepresentation`

```python
coord.CylindricalRepresentation(0 * u.m, 1 * u.rad, 0 * u.m).represent_as(coord.CartesianRepresentation).represent_as(coord.CylindricalRepresentation)
```
Or 

```python
for phi in np.arange(-5, 5) * u.rad:
    print(phi, coord.CylindricalRepresentation(0 * u.m, phi, 0 * u.m).represent_as(coord.CartesianRepresentation).represent_as(coord.CylindricalRepresentation).phi)
```

### System Details

macOS-10.15.7-x86_64-i386-64bit
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ]
Numpy 1.18.4
astropy 4.2.dev849+gc890ff450.d20201008
Scipy 1.4.1
Matplotlib 3.2.1

**Comment by nstarman** [comment]
I'm actually noticing this for a number of other representations where 2 of 3 positions are 0.

For example, `PhysicsSphericalRepresentation` to `CartesianRepresentation` and back using the input `(<Quantity 1. rad>, <Quantity 0. rad>, <Quantity 0. m>)`

**Comment by ayshih** [comment]
The problem with both of your examples is that the radius component is zero, and hence you are seeing the degeneracy where the angle value is irrelevant: all angle values point to the same point (in Cartesian space).  So, the conversion back from Cartesian simply uses the angle values of zero radians because it has no reason to pick a different angle value.  The output appears different, but the vectors are actually the same:
```python
>>> a = coord.CylindricalRepresentation(0*u.m, 1*u.rad, 0*u.m)
>>> print(a)
(0., 1., 0.) (m, rad, m)

>>> b = a.represent_as(coord.CartesianRepresentation).represent_as(coord.CylindricalRepresentation)
>>> print(b)
(0., 0., 0.) (m, rad, m)

>>> (a - b).norm()
<Quantity 0. m>
```

Is this causing an actual problem for you?

**Comment by nstarman** [comment]
@ayshih  Thanks for the diagnostic. 

While mathematically the 0-vector points in all directions, in this case we are losing information by moving through Cartesian coordinates. Some representations, like `UnitSphericalRepresentation`, lose information by design, that should not be the case for the other representations. Converting to/from `CartesianRepresentation` in particular should be a lossless transformation since `CartesianRepresentation` is used in the underlying Representations machinery as the base conversion.

For user-defined Representations this is especially important and we don't mandate that specific conversions be edge-cased. As an example, say we are implementing a [log-polar coordinate system](https://en.wikipedia.org/wiki/List_of_common_coordinate_transformations#Arc-length,_curvature_and_torsion_from_Cartesian_coordinates) + z-axis. This is closely related to cylindrical coordinates. For a a point <0, 1, z> (lpx, lpy, z) we would expect the transformation to cylindrical coordinates to be <0, p/2, z> (rho, theta, phi). However, by going through `CartesianRepresentation` this is not guaranteed and will probably be <0, 0, z>.

**Comment by ayshih** [comment]
I think it'd be possible to modify the `Representation` machinery to preserve this directional information for some conversions but an explicit conversion to `CartesianRepresentation` would inescapably lose this information because it is implemented as just three values (x/y/z).  A comprehensive fix would may require a significant rewriting of the `Representation` code to make it based on four values (3D direction plus distance).

**Comment by nstarman** [comment]
Another fix method might be to add two properties — Lon & lat — and essentially embed a UnitSpherical Representation in the Cartesian representation. These numbers would be recomputed on every call since representations can be modified in-place. Any `from_cartesian` method could then use that information to determine orientation information lost when the distance is 0. The docs would then inform that user-defined representations work as expected for non-zero distances, but to support conversions at the Cartesian origin should use these two properties. This would be a much smaller change to the code.

**Comment by mhvk** [comment]
I don't think this corner case is worth adding complexity for. Representations represent vectors, and a vector of zero length cannot have a meaningful direction, so no physically relevant information can be lost.

**Comment by nstarman** [comment]
@mhvk, that's fine, but maybe just a note in the docstring &/or docs. I had a confusing time debugging a hypothesis test when it caught this.

**Comment by mhvk** [comment]
Sounds good - do you have a suggestion where you would have found this, though?

p.s. Hypothesis is becoming something I both love & hate - it does often uncover "bugs" which are more bugs in one's hypothesis than in the code... (which is still good, of course, but does not make one feel that way).

**Comment by nstarman** [comment]
> p.s. Hypothesis is becoming something I both love & hate - it does often uncover "bugs" which are more bugs in one's hypothesis than in the code... (which is still good, of course, but does not make one feel that way).

pretty much same.

> do you have a suggestion where you would have found this, though?

I've been thinking about that. The best place I've found so far is https://docs.astropy.org/en/stable/api/astropy.coordinates.BaseRepresentation.html#astropy.coordinates.BaseRepresentation.represent_as
