### ISSUE TITLE
Fix or remove io.ascii C reader parallel code

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#10882]
As discussed in #8858, parallel reading with the io.ascii fast C reader is currently broken.

In https://github.com/astropy/astropy/pull/10880 I made the parallel reading option fall back to serial reading for now. I think that we should either fix this in a timely way or remove the parallel code to avoid code rot. I'm milestoning this as v4.2 but we could change to v4.3 if this is too aggressive.

cc @taldcroft @dhomeier @saimn

**Comment by pllim** [comment]
@taldcroft did mention that 4.2 is too aggressive over at https://github.com/astropy/astropy/pull/10880#issuecomment-710021187 , so I took the liberty to move the milestone. FYI

**Comment by pllim** [comment]
I don't see any PR associated with this issue. I am removing the milestone.

**Comment by MridulS** [comment]
Looks like this hasn't been touched in a while, does it make sense to remove the parallel code path to remove dead code?

**Comment by taldcroft** [comment]
I'm not sure of the status in general right now, but if is broken we should take it out rather than try to fix it.

**Comment by MridulS** [comment]
Should there be a deprecation cycle for the `parallel` keyword or it's safe to just remove it? The users were being warned with a warning if they used `parallel=True` in their code.

**Comment by taldcroft** [comment]
Yeah, that warning has been there for 3+ years, so let's jut remove the keyword and get it done.
