### ISSUE TITLE
TST: s390x and arm64 cron jobs fail after switch to travis-ci.com

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10902]
### Description

Since travis-ci.org is going away, we had no choice but to switch to travis-ci.com as instructed. However, after the switch, `s390x` and `arm64` cron jobs started to fail.

Would be nice if we can get this sorted out before release to ensure that no real failures have crept in.

### s390x

Example log: https://travis-ci.com/github/astropy/astropy/jobs/402407537
```
...
Processing triggers for ccache (3.4.1-1) ...
Updating symlinks in /usr/lib/ccache ...
E: Could not configure 'libc6:s390x'. 
E: Could not perform immediate configuration on 'libnss-nis:s390x'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
The command "if [ $SETUP_METHOD == 'apt' ]; then curl https://ftp-master.debian.org/keys/archive-key-10.asc | sudo apt-key add -; echo "deb http://ftp.us.debian.org/debian testing main" | sudo tee -a /etc/apt/sources.list; sudo apt-get -qq update; sudo apt-get install -t testing -y --no-install-recommends ${APT_DEPENDENCIES}; fi" failed and exited with 100 during .
```

### arm64

Example log: https://travis-ci.com/github/astropy/astropy/jobs/402407538

```
...
E: Failed to fetch http://ftp.us.debian.org/debian/pool/main/t/twisted/python3-twisted-bin_18.9.0-11+b1_arm64.deb  Undetermined Error [IP: 208.80.154.15 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 137 MB in 16s (8620 kB/s)
The command "if [ $SETUP_METHOD == 'apt' ]; then curl https://ftp-master.debian.org/keys/archive-key-10.asc | sudo apt-key add -; echo "deb http://ftp.us.debian.org/debian testing main" | sudo tee -a /etc/apt/sources.list; sudo apt-get -qq update; sudo apt-get install -t testing -y --no-install-recommends ${APT_DEPENDENCIES}; fi" failed and exited with 100 during .
```

**Comment by bsipocz** [comment]
Oh, interesting. I'm pinging @mhvk as he set up these originally, and @olebole as the debian expert.

**Comment by bsipocz** [comment]
(and milestone this, as having these failing is a blocker for the release)

**Comment by olebole** [comment]
The one on arm64 looks like a temporary hickup: Debian testing (and unstable) are not completely well-tested and reliable (this the name :-) ). It may happen  that one or the other dependency disappear for a while. I restarted the build and it went further (showing now the same error as on s390x). Looking into the [changelog of libnss-nis](https://tracker.debian.org/media/packages/libn/libnss-nis/changelog-3.1-4) would also suggest that this could be a temporary problem; it may be worth to just wait two more days.

**Comment by mhvk** [comment]
@olebole - hmm, that may be my mistake, of going for testing, though at the time I think neither Ubuntu nor stable had everything needed. I'll check separately whether with the newer Ubuntu things pass...

**Comment by pllim** [comment]
FWIW they have been consistently failing for every cron job run that happened since the switch.

**Comment by olebole** [comment]
As far as I understand the setup procedure here, it takes the default Travis setup (Ubuntu 18.04 "Bionic") and then tries to migrate it to Debian unstable. That is not really a supported procedure (although it often works), and hard to debug. It may be that there are some of the (pre) dependencies not really correct -- they are tested only for a direct migration from one Debian release to the next.

I think the best way to solve this in a robust manner would be to switch to Ubuntu 20.04 "Focal" (which is available in Travis now), if that is enough here. Or, it may at least help to use Focal as the starting point, and update then to Ubuntu 20.10 (which keeps you in the same distribution).

Also, Debian Testing is a "moving target", so something that works today may not work tomorrow. We are currently in the transition for Python 3.9, and once this is done, Python 3.8 will be removed (which would make the setup to fail). It is probably a good idea to have this as part of a test, but in combination with quite exotic systems (which aren't available on the desktop to debug problems) it may be calling for trouble a bit.

**Comment by mhvk** [comment]
@olebole - indeed, I've moved to `Focal` for my own packages and that works. Will make a PR to try that here too. Agreed that really I should not overload from `testing`, but that was required to get things to run before...
