### ISSUE TITLE
astropy 4.1 "error: option --offline not recognized"

### ISSUE THREAD

**Issue by Schamschula** [astropy/astropy#10917]
### Description
When upgrading astropy to version 4.1 under MacPorts I get the error "error: option --offline not recognized"

### Actual behavior

--->  Building py38-astropy

> Executing:  cd "/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_python_py-astropy/py38-astropy/work/astropy-4.1" && /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 setup.py --no-user-cfg --offline --no-git build -j8 --use-system-cfitsio --use-system-expat --use-system-wcslib --use-system-erfa 
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: option --offline not recognized

### Steps to Reproduce

1. I added dependencies on `extension-helpers`, `setuptools_scm` and `toml`
2. updated checksums
3. configure succeeded
4. build failed

### System Details

macOS-10.14.6-x86_64-i386-64bit
Python 3.8.6 (default, Sep 28 2020, 04:45:53) 
[Clang 10.0.1 (clang-1001.0.46.4)]
Numpy 1.19.2
Currently installed: astropy 4.0.3
Scipy 1.5.2
Matplotlib 3.3.0

Full log attached.

[astropy-4.1.log](https://github.com/astropy/astropy/files/5422928/astropy-4.1.log)

**Comment by pllim** [comment]
I think `--offline` was for `astropy-helpers`, which we have removed, so you can probably remove that option too.

Also, not even sure if `setup.py` would work. We use `pyproject.toml`  now, so you can use `pip install`?

**Comment by Schamschula** [comment]
Good catch!

I had a block of code with the arguments for `astropy-helpers`. Moved it to the legacy pinned versions of `astropy` for older versions of Python.

Thank you!
