### ISSUE TITLE
DOC: RTD v1.0 missing

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10918]
### Description

Linkcheck cron job reported a broken link, which I can confirm locally. Turns out RTD build for v1.0 is missing. Why is it missing? Is it intentional?

Example: https://travis-ci.com/github/astropy/astropy/jobs/403619988

```
.../docs/changelog.rst.rst:8078:broken link:
https://docs.astropy.org/en/v1.0/coordinates/index.html#migrating-from-pre-v0-4-coordinates
(404 Client Error: Not Found for url: https://docs.astropy.org/en/older-docs-archive/v1.0/coordinates/index.html)
```

**Comment by bsipocz** [comment]
ok, so it seems that `older-docs-archive` has been changed to `docs-archive`, but still everything is around:
https://docs.astropy.org/en/docs-archive/v1.0/coordinates/index.html

**Comment by bsipocz** [comment]
This is fixed now.
