### ISSUE TITLE
Checksum test on io.fits depends on platform

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10921]
The test `astropy.io.fits.tests.test_checksum.TestChecksumFunctions.test_compressed_image_data_float32` has a part that did not pass on windows:
https://github.com/astropy/astropy/blob/bbb917e7908bb2317e1814489eed6d1fecc49987/astropy/io/fits/tests/test_checksum.py#L276-L280

In #10908 it would found to also fail on `s390` (though puzzling since it had passed before; see https://github.com/astropy/astropy/pull/10908#issuecomment-714503857; in that PR, the test was commented out.

We should understand why the checksum calculation is platform dependent, and either fix the code or, if it is not important, remove the test.

**Comment by neutrinoceros** [comment]
A short update on this: the exact test mentioned in the reported appears to be gone, however `git grep 'if not sys.platform.startswith'` still returns 4 results, 2 of which are in `astropy/io/fits/tests/test_checksum.py`, so this issue is still relevant.

**Comment by saimn** [comment]
Closed by #17484
