### ISSUE TITLE
`vstack` does not preserve dtype of `Quantity` columns

### ISSUE THREAD

**Issue by barentsen** [astropy/astropy#10958]
### Description

When applying `vstack` on two or more `QTable` objects which have an integer `Quantity` column, I find that the `dtype` of that column is unexpectedly converted from int to float.

Minimum example:

```python
>>> from astropy.table import QTable, vstack
>>> from astropy.units import Quantity
>>> tbl = QTable({'x': Quantity([1], dtype=int)})
>>> vstack((tbl, tbl))['x'].dtype
dtype('float64')
```
I expected to see `dtype('int64')` above.

The error does not occur when `Table` is used instead of `QTable`, or when `Column` is used instead of `Quantity`.

### Debugging attempt

My debugger shows that the following line in `_vstack()` returns a Quantity with the incorrect dtype:

https://github.com/astropy/astropy/blob/10d27d8292bafb3ab502f4147dd707473e69af71/astropy/table/operations.py#L1288

...unfortunately I wasn't able to understand the `DataInfo` mechanism sufficiently to understand the origin of this error.

### System Details

I am using today's master branch, i.e.

```python
Python 3.8.6 (default, Oct  8 2020, 14:06:32)
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> print(astropy.__version__)
4.3.dev20+g10d27d829
```

**Comment by pllim** [comment]
Will #10950 fix this too?

**Comment by barentsen** [comment]
@pllim Unfortunately it won't!  I just checked out #10950 and it does not fix the bug/behavior reported here.  I believe this is a separate issue.

**Comment by pllim** [comment]
Thanks for checking, @barentsen !

**Comment by orionlee** [comment]
It does smell like the nature of the problem is similar to #10950: when creating new `Quantity` objects, the `dtype` is not preserved.

**Comment by mhvk** [comment]
@barentsen - like for #10950, I think it is good to be sure what behaviour you would expect. E.g., support we have two integer `Quantity` columns with units of `m` and `km` - such that the final unit is `km` - do you then want to quantities with `m` to be divided by 1000 and truncated? Or should it be an error or warning? 

Right now:
```
from astropy.table import QTable, vstack
qt = QTable([u.Quantity([1033, 26], u.m, dtype=int)], names=['s'])
qt2 = QTable([u.Quantity([1, 2], u.km, dtype=int)], names=['s'])
vstack([qt, qt2])
<QTable length=4>
         s          
         km         
      float64       
--------------------
               1.033
0.026000000000000002
                 1.0
                 2.0
```

**Comment by mhvk** [comment]
p.s. Just to be clear, my general recommendation is not to use integer Quantity to start with!

**Comment by barentsen** [comment]
Thanks for taking the time to respond @mhvk! Your recommendation makes sense to me.

We only really started using `Quantity` to store dimensionless integers in a `QTable` to circumvent a subtle API difference between `Quantity` and `Column` objects, namely, the fact that one uses `Quantity.value` and the other uses `Column.data` to access the underlying data.  It's probably much better to resolve this API difference rather than "abusing" Quantity objects to store integers.

It does beg the question whether `Quantity` objects should convert ints to floats upon object construction, to prevent a user from being surprised about subsequent conversions.

**Comment by mhvk** [comment]
@barentsen - yes, it would be good to make the API more similar. In fact, I recall @taldcroft and I at some point discussing whether `Column` should get a `.value` attribute (not quite sure where anymore). Of course, it is all an unintended consequence of `Table` having gotten so very nicely flexible that it can deal with all kinds of objects...

Note that `Quantity` does convert int to float by default upon construction - this is partially what #10950 was all about! Given that one actually has to make an effort to get int - in your case, how did it happen?

**Comment by mhvk** [comment]
Bit separately, @barentsen and @orionlee, are there specific cases why you use `.data` and `.value`? In general, for both `Column` and `Quantity`, we try to ensure that they do the right thing themselves, i.e., that you would not need to explicitly turn them into plain arrays. I know for `Quantity` things often fails outside of numpy/astropy code (say, scipy fitting, etc.), but if it is inside astropy/numpy, it may be fixable (and I'm on a bit of a mission to make all code unit-aware!)

**Comment by barentsen** [comment]
> Given that one actually has to make an effort to get int - in your case, how did it happen?

Over in the Lightkurve project, we were forcing integer columns to become Quantity objects, just so that we could rely on the `.value` property being available in a consistent way, which we needed when passing data to some non-astropy/numpy functions. Admittedly we didn't realize at the time that it doesn't make much sense for Quantity objects to hold anything other than floats.


> I know for Quantity things often fails outside of numpy/astropy code (say, scipy fitting, etc.), but if it is inside astropy/numpy, it may be fixable

Certainly everything seems to be a lot more seamless today than it was even just 2 years ago.  Thank you!! 🙏 

I opened a PR with further thoughts on the case for `Column.value`: https://github.com/astropy/astropy/pull/10962

Thanks again @mhvk!

**Comment by barentsen** [comment]
(I'm closing this issue because I'm now convinced that we shouldn't be storing integers in Quantity objects in the first place.  Please reopen if anyone disagrees!)
