### ISSUE TITLE
cosmology.Planck18_arXiv_v2 parameter typo?

### ISSUE THREAD

**Issue by lewtonstein** [astropy/astropy#10957]
### Description

The cosmology.Planck18_arXiv_v2.Om0 value is 0.30966
But the value presented in Table 2 of the Planck2018 paper is 0.3111.
Why are they different? Is it a typo?

### Expected behavior

0.3111

### Actual behavior

0.30966

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by pllim** [comment]
I am guessing this is the table? https://www.aanda.org/articles/aa/full_html/2020/09/aa33910-18/T2.html

@aconley , can you please advise? Thanks!

**Comment by aconley** [comment]
Nope, it's correct.  It has to do with the way Omega_m is defined.  Astropy
handles them separately, the table folds them in.  However, the actual
Planck cosmology does not treat them as 'just matter', it assumes a particular
mass, so you wouldn't actually get the same distances if you folded them in.

See the comment in the parameters.py.

**Comment by pllim** [comment]
Ah, thanks! I wonder if this comment needs to be in user-facing doc as well.

https://github.com/astropy/astropy/blob/10d27d8292bafb3ab502f4147dd707473e69af71/astropy/cosmology/parameters.py#L56-L58

**Comment by pllim** [comment]
@lewtonstein , does this answer your question? If there is a way to make the info clearer in the docs, please let us know or open a pull request. Thanks!

I have added a label to auto-close this issue as answered after some time.

**Comment by lewtonstein** [comment]
Yes, I understand now. Thanks a lot!
It would be great if a note is added in the doc about how the
cosmology.Planck18_arXiv_v2.Om0 was calculated based on the values from the
paper.

Cheers,
Teng
