### ISSUE TITLE
Using LombScargle with units crashes when calling autopower()

### ISSUE THREAD

**Issue by andresgur** [astropy/astropy#10960]
### Description

The LombScargle fails to compute ```autpower``` if Times and y values have been passed as ```Quantity``` to ```LombScargle``` . I'm using astropy Version: 4.1 and numpy Version: 1.18.1. See the snippet below
### Code

```python
window_ls = LombScargle(data["Time"] * u.s, np.ones(data["Time"].shape) * u.ct / u.s, fit_mean=False, nterms=1, center_data=False)
frequency_window, power_window = window_ls.autopower(minimum_frequency=minimum_frequency,
                                                         maximum_frequency=0, samples_per_peak=5)
```

### Error
```
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 727, in to_value
    scale = self.unit._to(unit)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 951, in _to
    f"'{self!r}' is not a scaled version of '{other!r}'")
astropy.units.core.UnitConversionError: 'Unit("s")' is not a scaled version of 'Unit(dimensionless)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 1080, in __int__
    return int(self.to_value(dimensionless_unscaled))
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 730, in to_value
    value = self._to_value(unit, equivalencies)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 661, in _to_value
    equivalencies=equivalencies)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 987, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 918, in _get_converter
    raise exc
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 904, in _get_converter
    self, other, self._normalize_equivalencies(equivalencies))
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 888, in _apply_equivalencies
    unit_str, other_str))
astropy.units.core.UnitConversionError: 's' (time) and '' (dimensionless) are not convertible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/agurpide/scripts/swift_scripts/lomb_scargle.py", line 190, in <module>
    samples_per_peak=samples_per_peak)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/timeseries/periodograms/lombscargle/core.py", line 306, in autopower
    maximum_frequency=maximum_frequency)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/timeseries/periodograms/lombscargle/core.py", line 249, in autofrequency
    Nf = 1 + int(np.round((maximum_frequency - minimum_frequency) / df))
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 1082, in __int__
    raise TypeError('only dimensionless scalar quantities can be '
TypeError: only dimensionless scalar quantities can be converted to Python scalars
```
### Problem
in astropy.timeseries.periodograms.lombscargle.core.py
```
        df = 1.0 / baseline / samples_per_peak

        if minimum_frequency is None:
            minimum_frequency = 0.5 * df

        if maximum_frequency is None:
            avg_nyquist = 0.5 * n_samples / baseline
            maximum_frequency = nyquist_factor * avg_nyquist

        Nf = 1 + int(np.round((maximum_frequency - minimum_frequency) / df))
```
The problem I believe is that while ```df``` is a ```Quantity```, ```maximum_frequency``` and ```minimum_frequency``` are not and thus it crashes. Perhaps a solution could be to allow ```autopower``` to accept ```minimum_frequency``` and ```maximum_frequency``` as ```Quantity``` too.

**Comment by pllim** [comment]
Thanks, but can you please provide a fully reproducible code snippet? That is, please also provide a sample of `data` and `minimum_frequency` that can reproduce this error.

**Comment by pllim** [comment]
Looking at the [autopower API doc](https://docs.astropy.org/en/latest/api/astropy.timeseries.LombScargle.html#astropy.timeseries.LombScargle.autopower), I don't think it takes Quantity to begin with.

cc @astrofrog and @bsipocz

**Comment by andresgur** [comment]
sure, for instance:

```import astropy.units as u
from astropy.timeseries import LombScargle
import numpy as np

time_series = np.linspace(0, 100) * u.s
data = np.ones(len(time_series)) * u.ct/u.s
ls = LombScargle(time_series, data)
freq, power = ls.autopower(minimum_frequency=1, maximum_frequency=10)```

**Comment by pllim** [comment]
Ooo... Looks like it is the opposite of API doc, if you give `minimum_frequency` and `maximum_frequency` in Quantity, it works.

**Comment by andresgur** [comment]
I realized my title is a bit misleading, the problem is when using units in ```LombScargle()```, not in ```autopower```

**Comment by pllim** [comment]
According to https://docs.astropy.org/en/latest/timeseries/lombscargle.html (for 4.3.dev), `LombScargle` is supposed to be able to support Quantity, but all the `autopower` examples in doctest used non-Quantity inputs. The original algorithm predated `astropy.units`, I think, so my guess is that this is an oversight when we added Quantity support to it. Will have to wait to see what `timeseries` maintainers say. Thanks for the report!

**Comment by andresgur** [comment]
yes now that you mention it seems like only the doc in autopower is wrong as ```autopower``` works when ```Quantity``` is used for ```minimum_frequency``` and ```maximum_frequency``` . Thanks to you!

**Comment by adrn** [comment]
Not a `timeseries` maintainer, but a `LombScargle` user: This indeed looks like an oversight to me, and I think we should support this!

**Comment by mhvk** [comment]
It does seem a case where the docs just have to be clearer - if you use quantities in constructing LS, you should use quantities throughout...

**Comment by pkopparla** [comment]
Hello, first time contributor here. I added a line to documentation basically saying what mvhk said in the comment above.
