### ISSUE TITLE
DOC: Completely remove deprecated blackbody doc

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10986]
Currently, there is still a mentioned of deprecated blackbody (removed in 4.3) in the docs. This should be completely removed in 5.0.

This should not be done on `master` until 4.3 is branched out.

See https://github.com/astropy/astropy/pull/10972#discussion_r516100422

**Comment by marcinmarculewicz** [comment]
Is it still an open issue? If yes, how can I help?

**Comment by pllim** [comment]
@marcinmarculewicz , thanks for asking. This probably don't need any help for now, as it is slated for 5.0 and we're still working towards 4.3.
