### ISSUE TITLE
Support nulls in ECSV boolean columns?

### ISSUE THREAD

**Issue by mbtaylor** [astropy/astropy#10988]
### Description
The ECSV format is described, and as far as I know defined, in https://github.com/astropy/astropy-APEs/blob/master/APE6.rst. That document does not discuss in any detail the encoding of blank values, but e.g. an empty string value in an `int32`-typed column can be read by the Astropy implementation, and is represented by a masked value.  However an empty string value in a `bool`-typed column causes a read error.  If `file` refers to the following text:

    # %ECSV 0.9
    # ---
    # datatype: [
    #   { name: AA, datatype: int32   },
    #   { name: BB, datatype: bool    },
    #   { name: CC, datatype: float64 },
    # ]
    AA BB CC
    1 True 2.1
    2 False 5.4
    "" "" nan
    9 True -9.9

then `astropy.table.Table.read(file, format='ascii.ecsv')` gives me a `ValueError: Column BB failed to convert: bool input strings must be only False or True`.  This is Astropy 4.0, Python 3.6.

Is this intended behaviour?  There are cases where a boolean column could contain nulls as well as Trues and Falses (I came across this myself when trying to represent certain Gaia data in ECSV - the table in question had boolean columns containing null values, which meant the Astropy reader could not read my ECSV serialisation of the table).  APE6 does say _"Boolean fields are represented as the case-sensitive string False or True"_, but since nulls are not discussed elsewhere (e.g. it doesn't mention nulls in integer columns) it's not clear whether this counts as a declaration that nulls are intentionally outlawed for the `bool` type.

The ECSV I/O handlers I have written for STIL/TOPCAT do work with blanks in `bool`-typed columns.  I request that the Astropy ECSV implementation considers doing the same.

**Comment by pllim** [comment]
Hmm, weird, works with 4.3.dev if I use `io.ascii`:

```python
>>> from astropy.io.ascii import read
>>> s = """# %ECSV 0.9
... # ---
... # datatype: [
... #   { name: AA, datatype: int32   },
... #   { name: BB, datatype: bool    },
... #   { name: CC, datatype: float64 },
... # ]
... AA BB CC
... 1 True 2.1
... 2 False 5.4
... "" "" nan
... 9 True -9.9
... """
>>> t = read(s)
>>> t
<Table length=4>
  AA    BB     CC
int32  str5 float64
----- ----- -------
    1  True     2.1
    2 False     5.4
   --    --     nan
    9  True    -9.9
```

But doesn't work if you use `table`, as reported:
```python
>>> from astropy.table import Table
>>> t2 = Table.read(s, format='ascii.ecsv')
IndexError                                Traceback (most recent call last)
...\astropy\io\ascii\core.py in _convert_vals(self, cols)
   1009                 try:
-> 1010                     converter_func, converter_type = col.converters[0]
   1011                     if not issubclass(converter_type, col.type):

IndexError: list index out of range

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-7-9d03525d08d6> in <module>
----> 1 t2 = Table.read(s, format='ascii.ecsv')

...\astropy\table\connect.py in __call__(self, *args, **kwargs)
     59         descriptions = kwargs.pop('descriptions', None)
     60
---> 61         out = registry.read(cls, *args, **kwargs)
     62
     63         # For some readers (e.g., ascii.ecsv), the returned `out` class is not

...\astropy\io\registry.py in read(cls, format, cache, *args, **kwargs)
    518
    519         reader = get_reader(format, cls)
--> 520         data = reader(*args, **kwargs)
    521
    522         if not isinstance(data, cls):

...\astropy\io\ascii\connect.py in io_read(format, filename, **kwargs)
     16         format = re.sub(r'^ascii\.', '', format)
     17         kwargs['format'] = format
---> 18     return read(filename, **kwargs)
     19
     20

...\astropy\io\ascii\ui.py in read(table, guess, **kwargs)
    373         else:
    374             reader = get_reader(**new_kwargs)
--> 375             dat = reader.read(table)
    376             _read_trace.append({'kwargs': copy.deepcopy(new_kwargs),
    377                                 'Reader': reader.__class__,

...\astropy\io\ascii\core.py in read(self, table)
   1304                                      self.include_names, self.exclude_names)
   1305
-> 1306         table = self.outputter(self.header.cols, self.meta)
   1307         self.cols = self.header.cols
   1308

...\astropy\io\ascii\ecsv.py in __call__(self, cols, meta)
    193     def __call__(self, cols, meta):
    194         # Convert to a Table with all plain Column subclass columns
--> 195         out = super().__call__(cols, meta)
    196
    197         # If mixin columns exist (based on the special '__mixin_columns__'

...\astropy\io\ascii\core.py in __call__(self, cols, meta)
   1063         # Sets col.data to numpy array and col.type to io.ascii Type class (e.g.
   1064         # FloatType) for each col.
-> 1065         self._convert_vals(cols)
   1066
   1067         t_cols = [numpy.ma.MaskedArray(x.data, mask=x.mask)

...\astropy\io\ascii\core.py in _convert_vals(self, cols)
   1026                     last_err = err
   1027                 except IndexError:
-> 1028                     raise ValueError(f'Column {col.name} failed to convert: {last_err}')
   1029
   1030

ValueError: Column BB failed to convert: bool input strings must be only False or True
```

**Comment by mbtaylor** [comment]
Looking at your output, for whatever reason using `io.ascii.read` gives up on treating that column as a `bool` when the blank value is present and makes it into a `str5` instead.  So `io.ascii.read` isn't doing what I'd like to see either.

**Comment by pllim** [comment]
> So `io.ascii.read` isn't doing what I'd like to see either.

@mbtaylor , can you please clarify what exactly you wish to see here? Perhaps share the expected output?

**Comment by mbtaylor** [comment]
Sure.  What I'd expect/like to see is like this:

    >>> from astropy.table import Table
    >>> t2 = Table.read(s, format='ascii.ecsv')
    >>> t2
      AA    BB     CC
    int32  bool float64
    ----- ----- -------
        1  True     2.1
        2 False     5.4
       --    --     nan
        9  True    -9.9
    >>> t2[2][0]
    masked
    >>> t2[2][1]
    masked
    >>> type(t2[1][1])
    <class 'numpy.bool_'>
    >>> type(t2[2][1])
    <class 'numpy.bool_'>

For the `io.ascii.read` option, the BB column header does not report type `bool` and the cell types are not reported as `numpy.bool_`.

**Comment by taldcroft** [comment]
@mbtaylor - this is a good idea. I haven't reviewed the code but I would consider the current behavior to be a bug.

Note that it is possible to represent a masked bool column in the current stable code as shown below, though I understand this is slightly orthogonal to your original request.  See https://docs.astropy.org/en/latest/io/unified.html#table-serialization-methods.
```
In [2]: cb = MaskedColumn([True, False, True], mask=[False, True, False])                                            

In [3]: t = Table([cb])                                                                                              

In [4]: t                                                                                                            
Out[4]: 
<Table length=3>
col0
bool
----
True
  --
True

In [5]: t.write('junk.ecsv', serialize_method='data_mask', overwrite=True)                                           

In [6]: cat junk.ecsv                                                                                                
# %ECSV 0.9
# ---
# datatype:
# - {name: col0, datatype: bool}
# - {name: col0.mask, datatype: bool}
# meta: !!omap
# - __serialized_columns__:
#     col0:
#       __class__: astropy.table.column.MaskedColumn
#       data: !astropy.table.SerializedColumn {name: col0}
#       mask: !astropy.table.SerializedColumn {name: col0.mask}
# schema: astropy-2.0
col0 col0.mask
True False
False True
True False

In [7]: t2 = Table.read('junk.ecsv')                                                                                 

In [8]: t2                                                                                                           
Out[8]: 
<Table length=3>
col0
bool
----
True
  --
True
```

**Comment by taldcroft** [comment]
See #10995 for a fix (which I confirmed works with the file in the description).

**Comment by mbtaylor** [comment]
Great!  Many thanks for quick service.
