### ISSUE TITLE
ecliptic_transforms._true_ecliptic_rotation_matrix() calculates nutation twice

### ISSUE THREAD

**Issue by mkbrewer** [astropy/astropy#11000]
### Description

I noticed that the function `ecliptic_transforms._true_ecliptic_rotation_matrix()` calculates nutation twice. Once in the call to `erfa.pnm06a()` and then again explicitly right afterwards. Calculating nutation is quite expensive, so it would be better to just explictily call the three functions that `erfa.pnm06a()` calls.

### Additional context

What `erfa.pnm06a()` actually does:
```
/* Fukushima-Williams angles for frame bias and precession. */
   eraPfw06(date1, date2, &gamb, &phib, &psib, &epsa);

/* Nutation components. */
   eraNut06a(date1, date2, &dp, &de);

/* Equinox based nutation x precession x bias matrix. */
   eraFw2m(gamb, phib, psib + dp, epsa + de, rnpb);
```

**Comment by mhvk** [comment]
Yes, that very much makes sense. See #11001 for doing just what you recommended (with an extra simplification that would be good to have your eye over!).
