### ISSUE TITLE
Are keys on a io.fits.Header object case insensitive?

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#11031]
The documentation for `astropy.io.fits.Header` does not mention anything about whether keys are case sensitive or insensitive, however the code has the following comment which would suggest the keys are case insensitive
https://github.com/astropy/astropy/blob/3627a7473e7c73f2e46e74157eaa4f078ccb8574/astropy/io/fits/header.py#L1634-L1635

It would be great to work out the sensitiveness of keys, and documented this somewhere in the docstring.

**Comment by pllim** [comment]
By FITS standards, the keys are case insensitive, I think?

**Comment by saimn** [comment]
FITS keywords are uppercase:

> The keyword name shall be a left justified, eight-character,
space-filled, ASCII string with no embedded spaces. All digits
0 through 9 (decimal ASCII codes 48 to 57, or hexadecimal 30
to 39) and upper case Latin alphabetic characters ’A’ through
’Z’ (decimal 65 to 90 or hexadecimal 41 to 5A) are permitted;
lower-case characters shall not be used.
