### ISSUE TITLE
MNT: Get rid of minversion definitions in __init__.py

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11059]
### Description

Do we really need all this stuff in `__init__.py`? It duplicates the info in `setup.cfg` anyway. For the usage in `docs/conf.py`, there is no reason we cannot get that info from `setup.cfg` instead?

https://github.com/astropy/astropy/blob/a995665c06b8d145ba811e3cbc59b0dfb8d20bd6/astropy/__init__.py#L15-L30

### Additional context

If the package being checked has no `__version__`, importing `astropy` will fail. For example: liberfa/pyerfa#60

cc @saimn and @astrofrog @embray

**Comment by embray** [comment]
Hmm...I think it's useful to have in the package in one form or other.  If you want to get it from setup.cfg it is possible at runtime using

```python
import pkg_resources
dist = pkg_resources.get_distribution('astropy')
dist.resources()
```

currently this returns

```
[Requirement.parse('numpy>=1.17'), Requirement.parse('pyerfa')]
```

So I agree with you that we could include *some* of these in `setup.cfg` and get the `__minimum_*_version__` variables that way.  However, some of these are optional dependencies too, and that Astropy doesn't include in its `install_requires`.  (I think we should go ahead and include them in `install_requires` and make them non-optional, but that's a separate debate).

In any case, the `pkg_resources` interface remains somewhat outdated (e.g. it doesn't have a way to query extras that I can find), and there isn't a super easy way to add custom metadata to Python packages.  So it seems that this may still be necessary.

**Comment by astrofrog** [comment]
I'm pretty sure I found a way to query the extras in the past, will investigate!

**Comment by Cadair** [comment]
https://github.com/sunpy/sunpy/blob/e77e0f952032d3fd6a75fda609099341c4fea827/docs/conf.py#L16-L28 Is a way to query the extras.

**Comment by astrofrog** [comment]
Ah yes that's it 😄 

Given that it's possible to do this with standard Python packaging tools, I'm 💯 on getting rid of these variables in ``__init__.py``

**Comment by pllim** [comment]
Anyone knows why `py_version` is returning `None`?
```python
>>> import sys
>>> from pkg_resources import get_distribution
>>> sys.version_info
sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
>>> dist = get_distribution('astropy')
>>> dist.version
'4.2rc1'
>>> dist.py_version  # returns None

```

**Comment by pllim** [comment]
I guess I could get it this way, but seems weird that I need to parse it separately from the other stuff.

```python
>>> import configparser
>>> config = configparser.ConfigParser()
>>> _ = config.read('setup.cfg')
>>> config['options']['python_requires']
'>=3.7'
```

**Comment by saimn** [comment]
There is also [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html) which is meant to replace `pkg_resources` (was added in Python 3.8 I think, and there is a backport):
```
In [1]: import importlib.metadata

In [2]: dist = importlib.metadata.distribution('astropy')

In [3]: dist.metadata['Requires-Python']
Out[3]: '>=3.7'

In [4]: dist.requires
Out[4]: 
['numpy>=1.17',
 'pyerfa',
 'scipy>=1.1; extra == "all"',
 'dask[array]; extra == "all"',
 'h5py; extra == "all"',
 'beautifulsoup4; extra == "all"',
 'html5lib; extra == "all"',
 'bleach; extra == "all"',
 'PyYAML>=3.13; extra == "all"',
 'pandas; extra == "all"',
 'sortedcontainers; extra == "all"',
 'pytz; extra == "all"',
 'jplephem; extra == "all"',
 'matplotlib>=3.0; extra == "all"',
 'mpmath; extra == "all"',
 'asdf>=2.6; extra == "all"',
 'bottleneck; extra == "all"',
 'ipython>=4.2; extra == "all"',
 'pytest; extra == "all"',
 'sphinx; extra == "docs"',
 'sphinx-astropy>=1.3; extra == "docs"',
 'pytest; extra == "docs"',
 'PyYAML>=3.13; extra == "docs"',
 'scipy>=1.1; extra == "docs"',
 'matplotlib>=3.1; extra == "docs"',
 'pytest-astropy>=0.8; extra == "test"',
 'pytest-xdist; extra == "test"',
 'objgraph; extra == "test"',
 'ipython; extra == "test"',
 'coverage; extra == "test"',
 'skyfield>=1.20; extra == "test"',
 'sgp4>=2.3; extra == "test"']
```

**Comment by pllim** [comment]
It'll be a while until our minversion of Python is 3.8. Is it worth the extra complexity to add https://importlib-resources.readthedocs.io/en/latest/index.html as requirement?

**Comment by pllim** [comment]
Have a prototype going at #11076 . 😬

**Comment by saimn** [comment]
https://importlib-metadata.readthedocs.io/en/latest/ (not importlib-resources ;)). It would be a requirement for Python 3.7 only. In the long term it's the package to use as it was designed as a more efficient replacement to `pkg_resources`. (We could also use it for entry points, it should be must faster)

**Comment by mhvk** [comment]
Seems very nice. Could have a switch in `__init__.py` between pkg_resources and importlib.metadata... (see comments in PR)
