### ISSUE TITLE
ENH: Auto-assign reviewers to new pull requests

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11051]
### Description

Use https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners and https://www.astropy.org/team (which is rendered from [roles.json](https://github.com/astropy/astropy.github.com/blob/master/roles.json)) to auto-assign reviewer(s) for new pull requests on this repo.

This file must not be in the root directory, but rather in `.github` sub-directory.

cc @astropy/devops-maintainers 

### Additional context

astropy/astropy-bot#101

**Comment by embray** [comment]
I think at one point @bsipocz raised some possible objection to this, but I don't recall exactly what it was.  It would be worth having that discussion, and maybe broaden it to the mailing list as well.

This is definitely something I would like to do, but I think at a minimum it should be strictly opt-in (e.g. add a flag to the team file indicating that an individual maintainer has opted in to be auto-assigned to issues).

**Comment by taldcroft** [comment]
One issue is that I normally wait until a PR is ready for review before assigning a reviewer. Mostly this applies to my own PR's, but for PR's from other experienced developers I will often wait until getting a review request before really looking at it. I guess now we have draft PR's which helps a bit with that.

The other thing is that the choice of reviewer is not always straightforward, and so I'm not sure that auto-assigning will really help things out.  But who knows.

**Comment by pllim** [comment]
Another option is to have a GitHub Action (or some other automation platform, your choice) that "listens" to PR comments. When certain trigger words are written, it assigns reviewer(s). This way, you can wait till you are ready. 💭

**Comment by bsipocz** [comment]
@embray - my objection was for assigning issues. PRs are, I think, should be assigned, but I agree with the caveats Tom mentioned above. 
What about trying this out but being open to roll it back if to much premature noise is generated, or if indeed to many PRs get misassigned?

**Comment by embray** [comment]
@bsipocz I'd be totally fine with trying it out for PRs only.  I don't see the difference but am fine with limiting the scope to start with anyways.

**Comment by nstarman** [comment]
IMO this hypothetical auto-assigner should only trigger on non-draft PRs (and therefore when they switch from draft to ready-for-review).

**Comment by pllim** [comment]
That is fine. It is already how CODEOWNERS work.

**Comment by pllim** [comment]
We have codeowners file now and it is opt-in.
