### ISSUE TITLE
TST: Are we backporting Actions to 4.0.x, 4.1.x, and 4.2.x?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11050]
Are we backporting Actions to active dev branches?

- [x] 4.0.x -- Is it worth the trouble or do we want to pay Travis for this one? See #11123 
~- [ ] 4.1.x -- Are we ever going to release 4.1.1? If not, then there is no need.~ edit (bsipocz): I've deleted this milestone and moved everything out to either 4.1 (most were in fact released in that one) or in 4.2, right before releasing 4.2
- [x] 4.2.x -- Brigitta did it as part of 4.2 release. edit: it may be partial backport, only backported the first big PR.
- [x] 4.2.x -- optional cleanup  (e.g. move cron jobs to be normal ones) and sync with what is currently in master. See #11122

Also see #10388, #11038, and #11045

**Comment by bsipocz** [comment]
Yes please, we need CI for LTS and the current release branches.

**Comment by pllim** [comment]
I have  #11122 and  #11123 open, so closing this and moving discussions over there.
