### ISSUE TITLE
Coordinate changes when calling apply_space_motion with dt=0

### ISSUE THREAD

**Issue by kerrm** [astropy/astropy#11068]
### Description

Calling apply_space_motion on a SkyCoord with dt=0 results in a small but non-zero coordinate offset.

### Expected behavior

I expected the SkyCoord returned by apply_space_motion(dt=0) to be identical to the original one.

### Actual behavior
The resulting SkyCoord is separated by 0.0002 microarcseconds.  This depends on position and proper motion.  Some test values are identically 0, others are of order 1e-6 microarcsec, while this particular test case is 2e-4.

### Steps to Reproduce

```
from astropy.coordinates import SkyCoord
import astropy.units as u
sc = SkyCoord(ra=187*u.deg,dec=-14*u.deg,pm_ra_cosdec=-62*(u.mas/u.yr),pm_dec=6*(u.mas/u.yr))   
sc.separation(sc.apply_space_motion(dt=0*u.d)).to(u.microarcsecond)
Out[35]: <Angle 0.00019839 uarcsec>
```

Some other positions result in smaller discrepancies:

```
sc = SkyCoord(ra=180*u.deg,dec=20*u.deg,pm_ra_cosdec=100*(u.mas/u.yr),pm_dec=100*(u.mas/u.yr))   
sc.separation(sc.apply_space_motion(dt=0*u.d)).to(u.microarcsecond)                                                               
WARNING: ErfaWarning: ERFA function "pmsafe" yielded 1 of "distance overridden (Note 6)" [astropy._erfa.core]
Out[42]: <Angle 0. uarcsec>
```
```
sc = SkyCoord(ra=180*u.deg,dec=-14*u.deg,pm_ra_cosdec=100*(u.mas/u.yr),pm_dec=100*(u.mas/u.yr))                                   
sc.separation(sc.apply_space_motion(dt=0*u.d)).to(u.microarcsecond)                                                               
Out[44]: <Angle 5.72499843e-06 uarcsec>
```

### System Details

Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core
Python 3.6.8 (default, Aug  7 2019, 17:28:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Numpy 1.17.3
astropy 4.1
Scipy 1.3.1
Matplotlib 3.1.1

**Comment by mkbrewer** [comment]
I suspect that this is rounding error due to the fact that the space motion algorithm is executed in spite of the fact that `dt = 0`. Perhaps a check for this (and  `new_obstime = J2000`) should be done before doing anything.

**Comment by mkbrewer** [comment]
btw, these "errors" are orders of magnitude beyond the accuracy of current theory anyway.

**Comment by kerrm** [comment]
> btw, these "errors" are orders of magnitude beyond the accuracy of current theory anyway.

Yes, it's certainly not by any means a showstopper!  It was simply a bit larger than I expected and so I reported it in just in case it's a symptom of a deeper issue.

**Comment by mhvk** [comment]
@kerrm - I think @mkbrewer is right, and the rounding issues are just because to add proper motions, the coordinates  get converted to cartesian and back, and this can cause rounding errors:
```
In [82]: sc = SkyCoord(ra=187*u.deg,dec=-14*u.deg)

In [83]: sc.ra.radian
Out[83]: 3.263765701229396

In [84]: sc.cartesian.represent_as(UnitSphericalRepresentation).lon.radian
Out[84]: 3.2637657012293957
```

I don't think it is worth to special-case this - people may also apply space motion for an array of time differences, and then `0` in an array would be different from `0` as a scalar.

**Comment by mkbrewer** [comment]
Well, that could be handled in the same way as self transforms are through the use of `numpy.all()`, but perhaps this should wait until an astrometric frame is implemented to handle space motion automatically.

**Comment by kerrm** [comment]
Now that I understand this a bit better, personally I think it's fine to close.

**Comment by mhvk** [comment]
@kerrm - agreed, even though this is a definitely tricky, but it is even trickier to think how to document it in a way that can even be found. Anyway, please do continue to raise issues you encounter, it all helps making astropy better!
