### ISSUE TITLE
Accessing `Quantity.info` dramatically decreases performance of indexing

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#11066]
### Description

After accessing `q.info`, `q.__getitem__` gets slower by a factor of 3 for a quantity with 1000 elements (less for larger, even more for smaller).

### Expected behavior

Accessing some meta information should not affect performance.

### Steps to Reproduce

```python
In [22]: import numpy as np

In [23]: import astropy.units as u

In [24]: q = np.random.normal(size=1000) << u.s

In [25]: mask = q > (0 << u.s)

In [26]: %timeit q[mask]
3.42 µs ± 8.12 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [27]: q.info
Out[27]: 
dtype = float64
unit = s
class = Quantity
n_bad = 0
length = 1000

In [28]: %timeit q[mask]
10.3 µs ± 254 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

```

### System Details
```
Linux-5.8.18-1-MANJARO-x86_64-with-arch-Manjaro-Linux
Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0]
Numpy 1.19.1
astropy 4.1
Scipy 1.5.2
Matplotlib 3.3.2
```

**Comment by mhvk** [comment]
@maxnoe - this is a known problem, though one I would love to solve!  Once `info` has been accessed, the meta-data is stored on the quantity, and is copied in indexing operations, see https://github.com/astropy/astropy/blob/0d4d65f6accc835f286986e80edb1a5f4d4574ce/astropy/units/quantity.py#L415-L419

(Here, the setting of `.info` is not a fast process, as `info` is a descriptor.) Note that the same problem occurs for anything else one can store in a table (`Time`, `SkyCoord`, etc.; see their `_apply` methods), although for those the effect on performance will generally be less noticeable.

Overall, the reason we have this is to help table operations (which is what `.info` was designed for), where the idea was to follow `Column` and carry over things like the name and description. It may well be worth looking into the whole process in more detail, to see whether we perhaps can speed the copying up (e.g., could we get away with a much more shallow copy?) or avoid it altogether in specific cases (like for scalar items, as done for `Time` in #10889).

**Comment by maxnoe** [comment]
Ah, I was wondering why my quantity had info set in the first place. I tried `del q.info` but that raised an error. Is there any way to get rid of an `info`?

**Comment by mhvk** [comment]
`del q.__dict__['info']` 

Though I'm actually not sure why we didn't define `__delete__` - at least if not attached to a parent table, there is no reason not allow deleting the associated information.

**Comment by maxnoe** [comment]
So I found out why my quantity got the `info` set, it is because it was added to a table as some point:

```
>>> from astropy.table import Table
>>> import astropy.units as u
>>> q = [1, 2, 3] * u.s
>>> 'info' in q.__dict__
False
>>> t = Table({'q': q})
>>> 'info' in q.__dict__
True
```

I find this highly surprising, especially together with the performance impact this has!

Is it safe to delete `info` after the table has been created?

**Comment by mhvk** [comment]
If created in the default way, when a copy gets made, one can indeed get rid of `info` afterwards; for `Table(..., copy=False)`, however, `t['q'] is q`, so `info` should stay.

Note that within table, the `.info` attribute has really been a miracle of making all kinds of mixin columns work, so I don't think we really want to change that!

However, it should also be possible to not hinder performance when `info` is just in an all-default state, maybe by tracking whether anything has been set, and, if not, avoid copying it needlessly.  I.e., something along the lines where one would replace the `'info' in self.__dict__` stanza that now determines copying with something like `if self.__dict__.get('info', empty_info) is not empty_info:`. Or  tracking it on an attribute on `info` itself, or perhaps letting truthiness of `info` depend on whether it has changed, so one could just do `if self.__dict__.get('info', False):`... Let me also ping @taldcroft for possible ideas...

**Comment by mhvk** [comment]
@maxnoe - the bug bugged me, and it turned out it was not too difficult to fix (though it took me several hours to understand what was really happening; table indices are something I've still not really wrapped my head around...). See #11077.

**Comment by maxnoe** [comment]
Thanks!

**Comment by mhvk** [comment]
Thanks for noticing! We had some general efforts aimed at performance, but you have been smoking out quite a few cases we missed!!!

**Comment by maxnoe** [comment]
Yeah, we started using astropy units / tables in somewhat performance critical code ...

So I'll probably open some more.

**Comment by taldcroft** [comment]
Though it pains me, in my performance critical code I used the idiom of "create a data structure using Table, then convert to a numpy structured array for the performance bits". There is still no way to match the C-speed when you really need it.

**Comment by mhvk** [comment]
True, just as there is still no match to python/Table when you want ease of use and convenience! We'll just have to keep going, identifying and addressing bottlenecks.
