### ISSUE TITLE
pip install ValueError: path '/home/vsts/work/1/s/astropy/convolution/src/convolve.c' cannot be absolute

### ISSUE THREAD

**Issue by jvickroy** [astropy/astropy#11078]
My system is:

> Microsoft Windows 10 with all current updates
> Python 3.9 (64-bit)
> 

My problem is:

> `pip install astropy`

aborts with the following error:

> `ValueError: path '/home/vsts/work/1/s/astropy/convolution/src/convolve.c' cannot be absolute
[astropy-install.log](https://github.com/astropy/astropy/files/5586686/astropy-install.log)
[astropy-install.log](https://github.com/astropy/astropy/files/5590519/astropy-install.log)
`

Please see the attached log for details.
Your feedback would be appreciated.
Thanks,
/jim

**Comment by pllim** [comment]
Yeah, sorry about that. It has been fixed but not released as stable yet. You can try 4.2rc1 and see. If you need a stable version, for now, downgrade back to 4.0.x until 4.2 is out. Hope this helps!

**Comment by jvickroy** [comment]
Thanks for you quick response.  Astropy 4.2.rc1 successfully installed on my platform!

**Comment by embray** [comment]
User reported success with the fix.
