### ISSUE TITLE
astropy 4.2 can't find erfa 1.7.1

### ISSUE THREAD

**Issue by Schamschula** [astropy/astropy#11093]
### Description
After upgrading to astropy 4.2, using Python 3.7,  a MacPorts user reported that astropy fails to import.
See: https://trac.macports.org/ticket/61660

### Expected behavior

astropy loads.

### Actual behavior

`ImportError: erfa version 1.7 or later must be installed to use Astropy. erfa is not installed.`

However, erfa 1.7.1 is installed. I can reproduce this error on my machine using Python 3.8.
After downgrading to version 4.1, I don't see this error.

### Steps to Reproduce

```python
import astropy
```

### System Details

macOS-10.14.6-x86_64-i386-64bit
Python 3.8.6 (default, Sep 28 2020, 04:45:53) 
[Clang 10.0.1 (clang-1001.0.46.4)]
Numpy 1.19.4
import astropy; print("astropy", astropy.__version__) fails but is version 4.2
Scipy 1.5.4
Matplotlib 3.3.0

**Comment by saimn** [comment]
This has been fixed by erfa 1.7.1.1 (ref https://github.com/liberfa/pyerfa/issues/60).

**Comment by Schamschula** [comment]
Thanks.
I had erfa, rather than pyerfa as dependency. After adding a new py-pyerfa port the problem was solved.
