### ISSUE TITLE
Minor clarifications needed in TETE documentation.

### ISSUE THREAD

**Issue by mkbrewer** [astropy/astropy#11109]
While the documentation for the new TETE frame is excellent and quite thorough, a couple of minor clarifications would be helpful.

> TETE is the apparent coordinate system used by JPL Horizons and is the correct coordinate system to use when combining the right ascension with local apparent sidereal time to calculate the hour angle.

Hour angle here should be "apparent" or "TIRS" hour angle to avoid giving the false impression that this is the observed (or ITRS) hour angle which will only be available when an observed `HADec` frame is implemented (see issue #10239).

> This frame also includes frames that are defined relative to the Earth, but that are offset (in both position and velocity) from the Earth.

Just saying "the Earth" here is a bit misleading. The Moon is offset from the Earth, but an observer's position on the Moon could not be appropriately defined in TETE. Center of the Earth (or geocenter) would be better and the offset should be described as "from the center of the Earth (or geocenter) in the ITRS".

**Comment by mkbrewer** [comment]
@StuartLittlefair @mhvk Could you please take a look at this? I'm sorry that I missed these in the original PR.

**Comment by NikitaTewary** [comment]
If allowed, I would like to fix this issue.
