### ISSUE TITLE
BaseRepresentation.represent_as mentions example that is not there

### ISSUE THREAD

**Issue by astrojuanlu** [astropy/astropy#11106]
I was a bit confused by reading this:

https://github.com/astropy/astropy/blob/0ff46cb5305d288af47bd3de4432c7dc941b33cb/astropy/coordinates/representation.py#L867-L869

Kind of recursive, since the docstring belongs precisely to `astropy.coordinates.BaseRepresentation.represent_as` :sweat_smile:

**Comment by NikitaTewary** [comment]
@astrojuanlu If you could tell me the exact changes to be fixed, I can try to fix this issue

**Comment by mhvk** [comment]
This was added in #10891 - from a quick look, I think it should be as simple as changing the link to `to_cartesian`, but please check.
