### ISSUE TITLE
FITS: Add Header method to calculate data size

### ISSUE THREAD

**Issue by embray** [astropy/astropy#11105]
### Description
Per same discussion with @hickst from #11100, it would be useful for `Header` objects to have a method to calculate the size (in bytes) of the data portion following that header (e.g. in the context of seeking through a stream containing FITS data).

Currently the individual HDU classes have different internal methods for determining the size of the data array when loading it, but this isn't exposed in any consistent, easily usable manner.  When loading HDUs from a file their [`match_header`](https://github.com/astropy/astropy/blob/0ff46cb5305d288af47bd3de4432c7dc941b33cb/astropy/io/fits/hdu/base.py#L56) classmethods are used to determine the appropriate HDU class to represent the HDU of that header.

HDUs could similarly have a classmethod responsible for returning the size of the data given a specific header.  In most cases this is just a matter of multiplying together the `NAXISn` keywords with the `BITPIX`, also taking into account `GCOUNT` and `PCOUNT` as in [`_ValidHDU.size`](https://github.com/astropy/astropy/blob/0ff46cb5305d288af47bd3de4432c7dc941b33cb/astropy/io/fits/hdu/base.py#L937).  It might be useful, however, if this were also exposed as a classmethod which takes an arbitrary `Header` object, so that it can be used to compute the data size of a header without having to create the full HDU object.

**Comment by aaryapatil** [comment]
Is anyone working on this? Seems straightforward to expose the internal data-size calculation using a method in `Header` and a classmethod in `HDU`.

P.S. It has been a while since I touched the `io.fits` code, but I would like to get involved with it again. (I surprisingly enjoy working with this sub-package even if it always seems too difficult 🤯)

**Comment by hickst** [comment]
See the thread on AstroPy SLACK for related information and pointers to various code projects nibbling around the edges of this idea: https://astropy.slack.com/archives/C83KTJ2EM/p1617575712017400

**Comment by Cadair** [comment]
This would be *super* useful. Happy to help test it if someone wants to open a PR!

**Comment by aaryapatil** [comment]
Thanks @hickst and @Cadair! I’ll work on it and open a PR soon :)
