### ISSUE TITLE
PLY generated table handling is a pain

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#1112]
I noticed just now that a recent change (I think #1050 ?  It seems to be PLY-related, anyway, @mdboom) led to astropy now producing a `parsetab.py` file that gets installed into the base namespace.  So we would namespace-collide with any existing `parsetab` package or module, which presumably is a very bad thing (TM). 

So we should figure out how to move `parsetab.py` back into `astropy/extern/*` where it belongs.

**Comment by bsipocz** [comment]
@eteq -  I was totally new to the parsing tables, but with ~10mins of digging around I could figure out how to update them along with the updating the ply library. Since we only need to do this once in every ~2 years, probably this issue can be close now?

**Comment by bsipocz** [comment]
Exercising my newly minted rights, I'm closing this as an issue that will probably be never addressed. As a temp solution the files got included in the repo, and as I said in the previous comment, figuring out how that works is not that difficult. 

Please reopen if you think we need another solution.
