### ISSUE TITLE
Matplotlib plot_date changed the zero point of the dates in >v3.3

### ISSUE THREAD

**Issue by indiajoe** [astropy/astropy#11138]
### Description

`astropy.time.TimePlotDate` returns `Matplotlib plot_date input: 1 + number of days from 0001-01-01 00:00:00 UTC`
But Matplotlib changed the date from which they count in plot_date function to 1970-01-01 UTC since Matplotlib v3.3
See the note here: https://matplotlib.org/api/dates_api.html#matplotlib-date-format
### Expected behavior

```
import matplotlib.pyplot as plt 
from astropy.time import Time 
import numpy as np 
jyear = np.linspace(2000, 2001, 20) 
t = Time(jyear, format='jyear', scale='utc') 
plt.plot_date(t.plot_date, jyear)                  
plt.show()
```
Should plot dates 2000 to 2001 
### Actual behavior

Instead, resulted in a plot showing dates from the year 3969 to 3970 
### Steps to Reproduce

1. Install lastest version of astropy and matplotlib
2. Try the code snippet below

```python
import matplotlib.pyplot as plt 
from astropy.time import Time 
import numpy as np 
jyear = np.linspace(2000, 2001, 20) 
t = Time(jyear, format='jyear', scale='utc') 
plt.plot_date(t.plot_date, jyear)                  
plt.show()
```

### System Details

Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 3.6.6 (default, Aug 13 2018, 18:24:23) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Numpy 1.17.3
astropy 4.1
Scipy 1.5.2
Matplotlib 3.3.3

**Comment by pllim** [comment]
This sounds a little familiar... Are you sure it is not already fixed in `astropy` 4.2? Here is what I get with `astropy` 4.2:

![Screenshot 2020-12-07 094315](https://user-images.githubusercontent.com/2090236/101364557-b4752200-3870-11eb-9d1e-3c6b562b6b95.jpg)

**Comment by indiajoe** [comment]
Oh! Is the documentation also updated. I see the text "Matplotlib plot_date input: 1 + number of days from 0001-01-01 00:00:00 UTC" in  https://docs.astropy.org/en/latest/api/astropy.time.TimePlotDate.html .
I have tried it only on the latest astropy v 4.1 from PyPi

**Comment by pllim** [comment]
PyPI has 4.2 now. Did you do a `pip install astropy -U`?

**Comment by indiajoe** [comment]
Yes, strangely for me, `pip install astropy -U` says 4.1 is latest.

> $ pip install astropy -U 
Requirement already satisfied: astropy in ./Py3NEIDenv/lib/python3.6/site-packages (4.1)
Requirement already satisfied: numpy>=1.16 in ./Py3NEIDenv/lib/python3.6/site-packages (from astropy) (1.17.3)

**Comment by pllim** [comment]
Ah... I think we dropped Python 3.6 for `astropy` 4.2. Would you mind trying Python 3.7 or later? Sorry for any inconvenience caused.

**Comment by pllim** [comment]
p.s. Should have looked at all your reported versions above carefully as you did say Python 3.6 up there. My bad.

**Comment by indiajoe** [comment]
Oh..okay.. no problem. I shall update to python 3.7 or later

**Comment by indiajoe** [comment]
Do you think the documentation of the epoch is correct in https://docs.astropy.org/en/latest/api/astropy.time.TimePlotDate.html?

**Comment by pllim** [comment]
Re: Doc -- Will have to defer to @mhvk .

**Comment by mhvk** [comment]
@indiajoe - @pllim is right, we did fix that for 4.2 in #10876 and this was backported to 4.0.4, the long-term support release, so if you prefer, you can use 4.0.4 under python 3.6. But you are also right that the documentation is now out of date: we clearly forgot to update it...  Sorry that this led to confusion!  Would you be interested in making a PR to adjust it?

**Comment by pllim** [comment]
Hi humans :wave: - this issue was labeled as **Close?** approximately 8 months ago. If you think this issue should not be closed, a maintainer should remove the **Close?** label - otherwise, I will close this issue in 7 days.

*If you believe I commented on this issue incorrectly, please report this [here](https://github.com/pllim/action-astropy-stalebot/issues)*

**Comment by pllim** [comment]
Ops... Bot comment is accurate but I used the wrong API key. 😅
