### ISSUE TITLE
quantity.to_string(precision=<int>) does not produce a string of the quantity with <int> decimals of precision

### ISSUE THREAD

**Issue by pennucci** [astropy/astropy#11131]
### Description

The precision argument to the to_string method of a Quantity object doesn't appear to do what it should.

### Expected behavior

I expect quantity.to_string(precision=<int>) to produce a string of the quantity with <int> decimals of precision.

### Actual behavior

quantity.to_string(precision=<int>) produces a string with the full precision of quantity.

### Steps to Reproduce

```
from astropy import units as u
q = 10.12345 * u.km
print("%s"%q.to_string(precision=1))  # the full precision is printed
```

### System Details

Linux-5.4.0-53-generic-x86_64-with-glibc2.29
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
Numpy 1.17.4
astropy 4.1rc2
Scipy 1.3.3
Matplotlib 3.1.2

**Comment by pllim** [comment]
Seems like it only works if a Numpy array is given.

```python
>>> q = [10.12345] * u.m
>>> print("%s"%q.to_string(precision=1))
[10.1] m
```

Behavior is the same as https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html#numpy.set_printoptions . So even if this is a bug, maybe it is a upstream bug? @mhvk ?

**Comment by ludwigschwardt** [comment]
I've actually also noticed this but in the context of `Angle`... The docstring of `Angle.to_string` states this for the `precision` parameter:
```
If `None`, or not provided, the number of decimal places is determined by the value, and will be between 0-8 decimal places as required.
```

But then this happens:
```Python
>>> from astropy.coordinates import Angle
>>> a = Angle('10:20:30.12345678d')
>>> a.to_string(precision=8)
'10d20m30.12345678s'
>>> a.to_string()
'10d20m30.1235s'   # expected a precision of 8 according to the docs
```

The relevant code is in `astropy.coordinates.angle_utilities.sexagesimal_to_string`:
https://github.com/astropy/astropy/blob/cf31d42ce1af380306dc365621a72a144c687f78/astropy/coordinates/angle_utilities.py#L647

That code is 7 years old, BTW...

I have mooted this issue independently for the [Astropy-SKA Hackathon](https://github.com/orgs/ska-telescope/projects/1) happening today - great to see that someone opened an issue for us :-)

**Comment by jmmaljaars** [comment]
The `precision` remained unused in case the `format` variable evaluated to the default value.  #11145 should fix this. Please note, however, that the "general format" `g` is used rather than the "floating point format" `f`! So once #11145 is merged, the snippet

```
from astropy import units as u
q = 10.12345 * u.km
print("%s"%q.to_string(precision=4))
```

returns
```
10.12 km
```
