### ISSUE TITLE
memmap array to FITS using writeto

### ISSUE THREAD

**Issue by miguelcarcamov** [astropy/astropy#11130]
### Additional context

Hello, I want to write a FITS file of a numpy mmap cube, however I get the following error when trying to assign the cube to the hdu[0].data: "File-like object does not have a write method, required for mode ostream. The question is, is there a function implemented in astropy that I can use to write the memmap cube to a FITS cube? If not, it is possible to implement this?

Cheers

**Comment by pllim** [comment]
Hello. Could you please provide a fully reproducible code snippet and software versions?

Example code to grab versions:
```
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("Numpy", numpy.__version__)
import astropy; print("astropy", astropy.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)
```

**Comment by miguelcarcamov** [comment]
Ubuntu 18.04 Kernel: Linux-3.10.0-1062.9.1.el7.x86_64
Python 3.6.9
GCC 8.4.0
Numpy 1.19.1
Astropy 4.1
Scipy 1.5.4
Matplotlib 3.3.3

**Comment by pllim** [comment]
And a fully reproducible code snippet that can let other people get the same error that you got. Thanks!

**Comment by miguelcarcamov** [comment]
Yep, I am on it

**Comment by miguelcarcamov** [comment]
I realized there was an error in my code. Sorry for opening this issue. 

Cheers.
