### ISSUE TITLE
FloatingPointError in astropy.convolution

### ISSUE THREAD

**Issue by sweeps04** [astropy/astropy#11164]
**Description**
FloatingPointError is raised when checking the overflow behaviour of np.expm1() in astropy/modeling/blackbody.py if np.seterr(over='raise') is run before importing

**Expected behaviour**
No FloatingPointError should be raised

**Actual behaviour**
A FloatingPointError is raised

**Steps to Reproduce**
import numpy as np
np.seterr(over='raise')
import astropy.convolution

**Console output**
 File "C:\Users\me\Desktop\drive-download\6\itafp6.py", line 13, in <module>
    import astropy.convolution

  File "C:\Users\me\anaconda3\lib\site-packages\astropy\convolution\__init__.py", line 4, in <module>
    from .core import *  # noqa

  File "C:\Users\me\anaconda3\lib\site-packages\astropy\convolution\core.py", line 23, in <module>
    from .utils import (discretize_model, add_kernel_arrays_1D,

  File "C:\Users\me\anaconda3\lib\site-packages\astropy\convolution\utils.py", line 5, in <module>
    from astropy.modeling.core import FittableModel, custom_model

  File "C:\Users\me\anaconda3\lib\site-packages\astropy\modeling\__init__.py", line 11, in <module>
    from . import models

  File "C:\Users\me\anaconda3\lib\site-packages\astropy\modeling\models.py", line 18, in <module>
    from .blackbody import BlackBody1D

  File "C:\Users\me\anaconda3\lib\site-packages\astropy\modeling\blackbody.py", line 29, in <module>
    _has_buggy_expm1 = np.isnan(np.expm1(1000)) or np.isnan(np.expm1(1e10))

FloatingPointError: overflow encountered in expm1

**System Details**
Windows-10-10.0.18362-SP0
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Numpy 1.18.5
astropy 4.0.1.post1
Scipy 1.5.0
Matplotlib 3.2.2

**Comment by pllim** [comment]
`blackbody` module has been deprecated. Do you still see this problem with astropy 4.2?

**Comment by sweeps04** [comment]
> 
> 
> `blackbody` module has been deprecated. Do you still see this problem with astropy 4.2?

Yes, I updated but the issue persists.

**Comment by pllim** [comment]
I mean, do you still see this with astropy 4.2 using the new class as documented in https://docs.astropy.org/en/stable/modeling/physical_models.html#blackbody ?

**Comment by dhomeier** [comment]
The new `BlackBody` class does not have this check, so this should definitely not occur with 4.2.

**Comment by sweeps04** [comment]
> 
> 
> The new `BlackBody` class does not have this check, and in 4.2 there is no `import BlackBody1D` from anywhere, so this should definitely not occur.
> EDIT: Sorry, I stand corrected – although `BlackBody1D` is deprecated, it is not yet removed in 4.2, and `models.py` still has
> 
> ```
> from .blackbody import BlackBody1D
> ```
> 
> That's unfortunate of course, since the entire module import fails on a submodule that is not needed and should in fact no longer been used. But the module should only raise a warning; maybe there is a problem due to Windows raising a `FloatingPointError` instead of a `RuntimeError`?
> 
> https://github.com/astropy/astropy/blob/5baaee81449cad0fb2fb0b53136dea81160f7371/astropy/modeling/blackbody.py#L27-L29

Thanks for the inquiry, but I'm fairly new to Python. You think this is a Windows-explicit bug?

**Comment by dhomeier** [comment]
Oh, I missed another detail, which is that the code is only filtering a `RuntimeWarning`, not a `RuntimeError`. That is in fact what the range overflow normally is triggering; the `FloatingPointError` in your case is set off at the Python level, so it has nothing to do with compiler or OS; this is precisely triggered by your `np.seterr(over='raise')` before the import.
So I am not sure if this qualifies as a bug any more; if you are increasing warning levels to exceptions, you have to expect some errors like that.
So the real question is, why do you need to set `np.seterr(over='raise')` in your task, and could you perhaps try to call this sequence, if you really need it?
```
from astropy.modeling.blackbody import BlackBody1D
np.seterr(over='raise')
import astropy.convolution
```

**Comment by pllim** [comment]
Thanks for investigating, @dhomeier ! Since this error can be avoided entirely by not setting `np.seterr(over='raise')` *and* the code in question is deprecated, I propose we close this issue as "won't fix."

**Comment by sweeps04** [comment]
Will do, thanks!

**Comment by sweeps04** [comment]
> Thanks; I hope changing the import order provided a solution for your case, @sweeps04.

Yes it did! Is the issue still gonna be looked at, givrn that it imports depreciated code (if I understood correctly)?

**Comment by dhomeier** [comment]
Thanks! It is good to have a workaround described here that people can still find by searching the issues.
