### ISSUE TITLE
FittingWithOutlierRemoval says "niter" is optional but crashes if niter is None

### ISSUE THREAD

**Issue by chris-simpson** [astropy/astropy#11162]
### Description

The docstring for FittingWithOutlierRemoval says that the parameter "niter" (the maximum number of iterations) is optional, but calling with iter=None causes a crash because the `__call__()` method expects it to be an integer.

I see three solutions, in increasing order of (I think) desirability, so I'm not submitting a PR in case whichever solution I code is not approved.
1. Change the docstring so niter *must* be an integer :)
2. Check if `niter is None` in the `__init__()` or `__call__()` and, if so, set it to a large number instead.  Since #10642 stops iterating once convergence has been reached, one can check whether this number of iterations occurred, in which some sort of "did not converge" flag could be added to the `fit_info`.
3. Allow the loop to iterate infinitely, in principle, but repeatedly check that the solution is converging and break out if it doesn't. I'm not sure this is possible though since `FittingWithOutlierRemoval` is a wrapper for other fitters, whose behaviour may not be well-prescribed.

### Expected behavior

I expected it to iterate to convergence.

### Actual behavior

It crashed.

### Steps to Reproduce

```python
>>> import numpy as np
>>> from astropy import models, fitting
>>> from astropy.stats import sigma_clip
>>> x=np.arange(100)
>>> y = x
>>> m = models.Polynomial1D(degree=1)
>>> f = fitting.FittingWithOutlierRemoval(fitting.LinearLSQFitter(), niter=None, outlier_func=sigma_clip)
>>> m_final = f(m, x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/dev/lib/python3.7/site-packages/astropy/modeling/fitting.py", line 870, in __call__
    for n in range(1, self.niter + 1):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

### System Details

Python 3.7.7 (default, May  6 2020, 04:59:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.19.1
astropy 4.2.dev735+ga83f25b96
Scipy 1.5.2
Matplotlib 3.3.1

**Comment by pllim** [comment]
Thanks for reporting this!

Fixing the doc would be uncontroversial and can be backported.

Implementing `None` support would be "new feature" but also should we really do it? That opens up the door for max recursion reached error. cc @nden , @perrygreenfield , and @mcara

**Comment by pllim** [comment]
p.s. The docstring does say it accepts `niter` as `int` 🤷 

https://github.com/astropy/astropy/blob/2388de9ca4e804fc2be6254c8a7530e87820e180/astropy/modeling/fitting.py#L813

**Comment by perrygreenfield** [comment]
Option 3 seems ill defined as what is the rule for determining when it isn't converging? I would suggest just making a default integer value for niter in the definition. (Not enough to update only the docstring.)

**Comment by mcara** [comment]
What is the bug? Is it that the code does not work with `niter=None`? If so, where is it even implied that this is supported?

**Comment by mcara** [comment]
IMO `optional` does not automatically imply that `None` is allowed as input.

**Comment by perrygreenfield** [comment]
@mcara Agreed. I should look at the code to see what the default is currently. I misread the report.

**Comment by perrygreenfield** [comment]
Correct, I saw that in the code while you were adding that. So yes, just document that it must be an integer is fine.

**Comment by mcara** [comment]
> Correct, I saw that in the code while you were adding that. So yes, just document that it must be an integer is fine.

What do you mean? It is already documented:
```python
niter : int, optional 
```

I do not see any issue with this code and/or documentation. There is no bug, IMO.

**Comment by perrygreenfield** [comment]
Right, I assumed it didn't say that already based on the report. Nothing needs to be fixed in my opinion.

**Comment by mcara** [comment]
> On the other hand, it probably should say what the default is, shouldn't it?

It already does so in the function signature which is what appears to be the approach `astropy` (and most other packages) takes on this.

Here is what I would consider a bug: https://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord optional keyword parameters have the word `optional` but I can't figure out what that value is. This is a bug IMO.

Here is a standard way of documenting things: https://docs.astropy.org/en/stable/api/astropy.time.Time.html#astropy.time.Time which is the same as used here. I see no need to add default value to the documentation. If the default value ever changes - it is more difficult to keep docs in sync with actual values. It is not wrong to do so, but it would be different from the style most of the `astropy` is documented.

See https://numpydoc.readthedocs.io/en/latest/format.html#sections and scroll down to point `#4 Parameters`

**Comment by chris-simpson** [comment]
Fair enough, I've been working with a package where "optional" is defined as `None` is an acceptable value, whereas I do see that `astropy` is consistently using "optional" to mean there exists a default value. Sorry for wasting everyone's time; it's been a long year!

**Comment by pllim** [comment]
No worries, @chris-simpson ! I wasn't aware there exists alternative definition of "optional," so TIL as well.
