### ISSUE TITLE
Error on testing development copy

### ISSUE THREAD

**Issue by parampatidar** [astropy/astropy#11172]
### Description

Getting an error on testing development copy of astropy.

### Expected behavior

There should be no errors or failures.

### Actual behavior

I'm getting following error.
```python
ImportError while importing test module '/home/param/opensource/astropy/astropy/coordinates/tests/test_name_resolve.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
astropy/astropy/coordinates/tests/test_name_resolve.py:21: in <module>
    from pytest_remotedata.disable_internet import no_internet
E   ModuleNotFoundError: No module named 'pytest_remotedata'
```

### Steps to Reproduce

1. Clone the repository 
2. `>> cd astropy`
3. `>> pip install -e .`
4. `>> cd ..`
5. `>> pytest`

### System Details

**platform :** 'Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.10'
**sys :**  '3.8.3 (default, May 19 2020, 18:47:26) \n[GCC 7.3.0]'
**numpy :** '1.19.2'
**astropy :** '4.2.dev1241+g883723e05'

**Comment by saimn** [comment]
As described in https://docs.astropy.org/en/latest/development/testguide.html#testing-dependencies you should install `pytest-astropy` to get our test dependencies, or use `pip install -e .[test]`.

**Comment by parampatidar** [comment]
Thanks, It worked. 
When I was going through the docs [try development version](https://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#test-your-development-copy) pytest plugin was not mentioned there. Should we add a link of testing guide in [here](https://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#test-your-development-copy)

**Comment by saimn** [comment]
It could be useful indeed. Would you like to make the change ?

**Comment by parampatidar** [comment]
Yes I would like to make changes. I'm relatively new to open source and want to start with astropy.
