### ISSUE TITLE
Sersic2D function might build image model incorrectly

### ISSUE THREAD

**Issue by canorve** [astropy/astropy#11178]
I have used the Sersic2D model to simulate the surface brightness of galaxies. I have created the model and added Poisson noise and sky noise. 

Using the input Sersic2D parameters, I had computed the total magnitude of the Sersic model using two methods: 

1) Integrating the Sersic model using this known formula :

`    Ftot = 2*np.pi*(reser**2)*Ie*np.exp(kser)*nser*(kser**(-2*nser))*( scipy.special.gamma(2*nser))*axiser 
`

2)  Integrating the Sersic2D model with dblquad: 

`    Ftot = integrate.dblquad(Sersic2D, 0, 2000,0,2000,args=([A]))
`

These two quantities match. So far so good. The problem is when I compute the magnitude from the model image using apertures with DS9. Of course, I expect some differences, but the mag difference is too high (around ~ 10 mag).  In fact, in my experience, for the input parameters, the created galaxy model is too bright.

I have done this same exercise with Gaussian2D, and I don't have this problem.

**Comment by pllim** [comment]
> when I compute the magnitude from the model image using apertures with DS9

Could you please provide the full workflow, including relevant code and data, so others can reproduce this problem? Have you tried with another visualization tool such as [imexam](https://imexam.readthedocs.io/)?

DS9 could have some implicit assumptions that is out of the control of `astropy` but it is hard to tell right now.

**Comment by BorisHaeussler** [comment]
Sorry to intervene on a comment that wasn't mine. This most likely sounds like a zeropoint (or, connected, exposure time) issue, if the difference is 10 magnitudes!

**Comment by canorve** [comment]
Thanks Boris, 

I have reviewed my code, and there was a problem with the convolution of the galaxy model. Now everything looks fine for this problem.  

Sorry for the inconvenience pllim, I will close this issue now
