### ISSUE TITLE
Astropy.io.fits.writeto cannot save data to new FITS file

### ISSUE THREAD

**Issue by claireskies** [astropy/astropy#11186]
I am attempting to open and adjust several FITS files at a time. I need to change value "1" to "0" and I would like to add one additional comment in the header. 

The original fits files have only one Primary HDU. 

I open both data and header simultaneously with fits.getdata
I normally save files with fits.writeto but this does not work inside my loop 

```
for i in range(0,len(files)):
    image = files[i]
    data,header = fits.getdata(image,header=True)
    new_data=np.empty(shape=[data.shape[0],data.shape[1]])
    for c in range(data.shape[0]):
        for r in range(data.shape[1]):
            if data[c,r]==1.0:
                new_data[c,r]=0.0
            else:
                new_data[c,r]=data[c,r]
    #header["COMMENT1"]='Replaced background ones with zeros'
    hdu=fits.ImageHDU(new_data)
    primary_hdu=fits.PrimaryHDU(header)
    hdul=fits.HDUList([primary_hdu,hdu])
    hdul.writeto(directory+'name'+str(i)+'.fits')
    #
    #fits.writeto(directory+'name'+str(i)+'.fits',new_data,header).  #this used to work outside of a loop``
```

**Comment by claireskies** [comment]
pllim - thank you for the comment! - I want to create a new file for each of the originals. I have adjusted my file_output name to be unique for each file: 

`hdul.writeto(directory+'name'+str(i)+'.fits')`

**Comment by claireskies** [comment]
I am able to adjust the values, and save new fits files with the following loop: 

```
for i in range(0,len(files)):
    image = files[i]
    science=fits.open(image, ignore_missing_end=True)[0]
    data=science.data
    new_data=np.empty(shape=[data.shape[0],data.shape[1]])
    for c in range(data.shape[0]):
        for r in range(data.shape[1]):
            if data[c,r]==1.0:
                new_data[c,r]=0.0
            else:
                new_data[c,r]=data[c,r]
    #header["COMMENT1"]='Replaced background ones with zeros'
    fits.writeto(directory+'name'+str(i+1)+'.fits',new_data)
```

I also need to append a comment to the header before I save. I am having confusion understanding the difference saving a PrimaryHDU and ImageHDU

**Comment by pllim** [comment]
If you do not need multi-extension FITS, you can even save your ImageHDU as the primary. It really depends on how you wish to store your data.

Perhaps you may find https://docs.astropy.org/en/latest/io/fits/index.html and https://learn.astropy.org/tutorials.html?q=filterTutorials+filterfits useful in understanding how to use `astropy.io.fits`.

If you still have problems, you can also explore one of these communication channels: https://www.astropy.org/help.html

Given that your original issue has been resolved, I will mark this as "Close?" and the bot will close it the next time it runs. You may also choose to close this issue manually if you so wish. Thanks!
