### ISSUE TITLE
MNT: Will Dependabot help us?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11189]
### Description

Dependabot automatically checks and bumps upstream dependencies. Sounds useful for Javascript but not sure about Python. I set it up for `astropy` on the fork and it seems to monitor these files by default:

* `pyproject.toml`
* `setup.py`
* `setup.cfg`

I wonder if we can configure it to monitor our bundled external dependencies in `cextern` and `astropy/extern`. 💭 

### Also see

* https://dependabot.com/#how-it-works
* https://dependabot.com/blog/hello-github/

**Comment by saimn** [comment]
For a library like astropy where we aim at the broadest compatibility with dependency versions, I don't think it will be useful. It's mostly useful when you pin package versions, and want to have control on updating versions.

**Comment by pllim** [comment]
Update: This came up when we were discussing hard-pinning here:

https://github.com/astropy/astropy/blob/83ca78b1d185f8ba5181b42fd2d84c28035646ac/pyproject.toml#L5-L6

I think Dependabot can alert us when there are new versions, so we can contemplate about updating the pins. I see that Dependabot is already "active" in this repo but I don't see the YAML, so org admin probably needs to modernize it.

**Comment by embray** [comment]
Why are pinning cython and jinja2 in the first place?
