### ISSUE TITLE
EarthLocation.get_gcrs_posvel broadcasting

### ISSUE THREAD

**Issue by cbassa** [astropy/astropy#11211]
### Description
This is somewhat related to #10422 and #10424 , but for the case of computing GCRS position and velocity where EarthLocation and obstime are arrays of different length. Broadcasting with `obstime=t[:, np.newaxis]` as supported for `AltAz` in https://docs.astropy.org/en/stable/coordinates/#id4 does not work.

### Steps to Reproduce
```import numpy as np

import astropy.units as u
from astropy.time import Time
from astropy.coordinates import EarthLocation

if __name__ == "__main__":
    t = Time(["2020-01-01", "2020-01-02", "2020-01-03"], format="isot")

    lat = [40, 60] * u.deg
    lon = [10, 20] * u.deg

    loc = EarthLocation(lat=lat, lon=lon)
    loc.get_gcrs_posvel(obstime=t)
```

### System Details
Linux-5.10.2-2-MANJARO-x86_64-with-glibc2.32
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0]
Numpy 1.19.4
astropy 4.2
Scipy 1.5.4
Matplotlib 3.3.3

**Comment by cbassa** [comment]
Thanks for posting that error with astropy 4.3.dev @pllim. This was different from what I got with astropy 4.2.
Under astropy 4.3.dev431 broadcasting the time array as `loc.get_gcrs_posvel(obstime=t[:, np.newaxis])` works as expected, so I am closing this issue.

**Comment by mhvk** [comment]
@cbassa - geen probleem! At some point we'll still need to sort out the broadcasting properly!  #11184 is probably the main issue trying to remind us of this...
