### ISSUE TITLE
astropy handles spectral wcs units with logs incorrectly

### ISSUE THREAD

**Issue by aragilar** [astropy/astropy#11215]
It looks either wcslib or astropy's wrapping of it do not handle the units on the wcs object correctly, and instead override the spectral units to metres, when `"WAVE-LOG"` is used (note the change to metres in both the output of `pixel_to_world` and on the `w.wcs` object):

```python
from astropy.wcs import WCS
import numpy as np
from astropy.units import Unit
w0 = 3.57880000000000E+00
w1 = 1.00000000000000E-04
crval = 10 ** w0
cdelt = crval * w1 * np.log(10)
cunit = Unit('Angstrom')
ctype = "WAVE-LOG"
w = WCS(naxis=1)
w.wcs.crval[0] = crval
w.wcs.cdelt[0] = cdelt
w.wcs.ctype[0] = ctype
w.wcs.cunit[0] = cunit
print(w)
# OUT: WCS Keywords
# OUT: Number of WCS axes: 1
# OUT: CTYPE : 'WAVE-LOG'  
# OUT: CRVAL : 3791.4034418330666  
# OUT: CRPIX : 0.0  
# OUT: PC1_1  : 1.0  
# OUT: CDELT : 0.8730029046691138  
# OUT: NAXIS : 0  0
print(w.wcs.cunit)
# OUT: ['Angstrom']
print(w.pixel_to_world(np.arange(10)))
# OUT: [3792.27644474 3793.14944764 3794.02245055 3794.89545345 3795.76845636
# OUT:  3796.64145926 3797.51446217 3798.38746507 3799.26046798 3800.13347088] m
print(w.wcs.cunit)
# OUT: ['m']
### 
```

### System Details
```
>>> import platform; print(platform.platform())
Linux-5.10.0-1-amd64-x86_64-with-glibc2.31
>>> import sys; print("Python", sys.version)
Python 3.9.1 (default, Dec  8 2020, 07:51:42)
[GCC 10.2.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.19.5
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.2
```

**Comment by pllim** [comment]
I don't think `cunit` can take `astropy.units.Unit`, can it?

There was a different issue also related to `wcs` and units at #11173 .

**Comment by mhvk** [comment]
Thanks for reporting! I know too little about `wcs` to know how to address this directly, but just in case @mcara and @nden are not aware, in principle we can support the logarithmic base-10 unit as `u.dex(unit)`. However, I'm not sure how unit assignment in WCS works - if it needs support for writing a log10 unit in a FITS-style header, then we first need to fix #3822 (a long-standing issue, but not one that should be super hard in principle - just one that nobody got around too...). But if `cunit` would just be 'm' and the logarithmic nature is indicated by `WAVE-LOG`, then it should be possible to do it inside `WCS`. Anyway, happy to help look at possible fixes.

**Comment by mcara** [comment]
> It looks either wcslib or astropy's wrapping of it **do not handle the units on the wcs object correctly**, and instead override the spectral units to metres, when `"WAVE-LOG"` is used ...

(my emphasis). What would be _correct_ handling? That is, is the issue in the fact that units are converted to SI?

**Comment by aragilar** [comment]
Logs in WCS (at least in the spectral context) are base-e not base-10 (see WCS paper 3), and my reading of the units section in paper 3 around logs is that the units are not logged, and refer to the final output values.

**Comment by mcara** [comment]
@pllim 

> I don't think `cunit` can take `astropy.units.Unit`, can it

It looks like it can, `str(Unit('Angstrom'))` simply becomes `'Angstrom'`. (hence using `units` is simply redundant)

**Comment by aragilar** [comment]
@mcara wcslib is able to handle (at least based on my cursory glace) both log units and Angstroms, so I think it should be fine.

Correct in this case is the correct values and units (the values appear to be in Angstroms but the units are metres—either the values should be different to be in metres, or the units should be Angstroms).

**Comment by mcara** [comment]
I still cannot understand what is wrong with converting `CTYPE` from `Angstrom` to `m`. Here is what is going on with units and values:

```python
In [1]: from astropy.wcs import WCS
   ...: import numpy as np
   ...: from astropy.units import Unit
   ...: w0 = 3.57880000000000E+00
   ...: w1 = 1.00000000000000E-04
   ...: crval = 10 ** w0
   ...: cdelt = crval * w1 * np.log(10)
   ...: cunit = Unit('Angstrom')
   ...: ctype = "WAVE-LOG"
   ...: w = WCS(naxis=1)
   ...: w.wcs.crval[0] = crval
   ...: w.wcs.cdelt[0] = cdelt
   ...: w.wcs.ctype[0] = ctype
   ...: w.wcs.cunit[0] = cunit
   ...: print(f"\nRequested values:\ncrval: {crval}\ncdelt: {cdelt}\ncunit: {cunit}\n")
   ...: w.wcs.set()
   ...: print(f"\nSet by WCSLIB values:\ncrval: {w.wcs.crval}\ncdelt: {w.wcs.cdelt}\ncunit: {w.wcs.cunit}\n")
   ...:

Requested values:
crval: 3791.4034418330666
cdelt: 0.8730029046691138
cunit: Angstrom


Set by WCSLIB values:
crval: [3.79140344e-07]
cdelt: [8.73002905e-11]
cunit: ['m']
```

From the spectral WCS paper:

> The units for `CRVALka`, `CDELTka`, and `CDk_ ja` are specified by the `CUNITka` keyword as defined in Paper I. These quantities are in normal, non-logarithmic units such as `'Hz'` for `FREQ-LOG` and `'m'` for `WAVE-LOG`.

So, `CUNIT` refers the units of `CRVAL` and `CDELT` and those two, as seen from the example above, have expected (at least by me) numerical values after unit conversion.

**Comment by mhvk** [comment]
Sounds like my comments were not very on-topic, sorry!

**Comment by aragilar** [comment]
The problem is that the conversion is not done correctly:
```
# OUT: [3792.27644474 3793.14944764 3794.02245055 3794.89545345 3795.76845636
# OUT:  3796.64145926 3797.51446217 3798.38746507 3799.26046798 3800.13347088] m
```
Either a) the metres should be Angstroms in the output or b) the values should be much smaller. Whether the answer is in metres or Angstroms isn't important (but the switch that happens implies to me that something is happening that shouldn't).

**Comment by mcara** [comment]
I cannot reproduce your results

```python
In [4]: print(w.pixel_to_world([0, 1]))
[3.79227655e-07 3.79314985e-07] m
```

**Comment by mcara** [comment]
Ah, I see. You need to call `w.wcs.set()` after setting these WCS parameters.

**Comment by aragilar** [comment]
Oh, ok :facepalm:. Thanks for the help @mcara, I didn't realise I needed to use `set()`, and was wondering why I was the first person to find the "bug". I'll read the docs, and see if there's a point where I can add a patch which makes the need for calling `set()` more obvious, so hopefully the next person who tries to do this doesn't make the same mistake I did.

**Comment by mcara** [comment]
From [documentation for `wcsset`](https://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/wcs_8h.html#ae5cc3f5d249755583403cdf54d2ebb91):

> wcsset() recognizes the NCP projection and converts it to the equivalent SIN projection and likewise translates GLS into SFL. It also **translates the AIPS spectral types ('FREQ-LSR', 'FELO-HEL', etc.), possibly changing the input header keywords wcsprm::ctype and/or wcsprm::specsys if necessary.**

On the other hand:
> Note that this routine need not be called directly; it will be invoked by wcsp2s() and wcss2p() if the wcsprm::flag is anything other than a predefined magic value.

So, it is strange that it appears that this is not being detected. I will investigate this a little more and maybe report this upstream if something is not working as expected. However, I remember, in the past, I had to call this manually in my own code after setting `CTYPE` or `CUNIT` so that WCS internal structure is set-up correctly. Maybe the above statement in WCSLIB documentation should be clarified.

**Comment by mcara** [comment]
Alright, reading documentation for [`Wcsprm::flag`](https://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/structwcsprm.html#a35bff8de85e5a8892e1b68db69ca7a68), it seems like if one were to use `WCSLIB` directly (not through `astropy.wcs`) then `flag` should be set to 0 after any of the WCS parameters listed in the link are modified. You do not have access to that flag from `astropy`. However, you can essentially accomplish the same by explicitly calling `w.wcs.set()`. So, I do not see a real problem with how things are set-up in `astropy` but maybe some documentation update is in order.

**Comment by aragilar** [comment]
Would anything bad happen if you called `set()` after each change?

**Comment by mcara** [comment]
I do not think so. The way I would use it would be to modify/set _all_ parameters and then call `set()` once in the end because it is an "expensive" (computationally) operation.

**Comment by mcara** [comment]
OK, I take back my recommendation to call `set()` (though the only issue with calling it that I can see at this moment is performance issue). I looked at the `astropy`'s C wrapper code and I can see that `flag` is set to `0x0` each time one of these parameters is modified. That is, indeed, you should not need to call `set` if set WCS parameters "correctly" so that setting them triggers correct setters.

That is, you should be doing the following:
```python
w.wcs.crval = [crval]
w.wcs.cdelt = [cdelt]
w.wcs.ctype = [ctype]
w.wcs.cunit = [cunit]
```
instead of:
```python
w.wcs.crval[0] = crval
w.wcs.cdelt[0] = cdelt
w.wcs.ctype[0] = ctype
w.wcs.cunit[0] = cunit
```
The difference is the first ("correct"/"standard") approach calls appropriate setters that not only set parameters of the `Wcsprm` structure, but also set the `flag=0` so that `set()` will be called _when needed_ (i.e, before calling pixel->sky coordinate transformation). The second approach modifies elements directly bypassing `astropy`'s wrapper and so it also does not set `flag=0`. Hence, if using your approach, you need to call `set()` after you are done setting these parameters:
```python
w.wcs.set()
```

**Comment by aragilar** [comment]
Is there a reason indexing bypasses the wrapper (I'd imagine there would still need to be the pyfloat to float/double conversion)? I'd imagine you still want `set()` (well, the wcslib equivalent) to be called whenever you modify the structure?

**Comment by pllim** [comment]
I am glad a solution was found. Thanks, @mcara ! @aragilar , if a documentation update is indeed necessary, feel free to re-open the issue or even better, submit a PR. 😸
