### ISSUE TITLE
Model parameter description does not exist

### ISSUE THREAD

**Issue by mdecleir** [astropy/astropy#11230]
### Description
When I try to print the parameter description, I get the following error:
AttributeError: 'Parameter' object has no attribute 'description'

### Expected behavior

According to the documentation, a Parameter object has an attribute description:
https://docs.astropy.org/en/latest/api/astropy.modeling.Parameter.html

### Actual behavior

Output:
```AttributeError: 'Parameter' object has no attribute 'description'```
### Steps to Reproduce

1. Create a model object
2. Print the description of the parameter

```python
from astropy.modeling.powerlaws import PowerLaw1D

func = PowerLaw1D()
print(func.amplitude.description)

```

### System Details

Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 20:58:55) 
[Clang 11.0.0 ]
Numpy 1.16.6
astropy 4.0.3
Scipy 1.6.0
Matplotlib 3.3.3

**Comment by pllim** [comment]
I see it with 4.3.dev too. Looking at this, I wonder if it is a documentation bug or a feature that was never implemented...

https://github.com/astropy/astropy/blob/4b242e6f5465410aa575f844e1a0b81db4534c94/astropy/modeling/parameters.py#L208

cc @nden and @perrygreenfield

**Comment by pllim** [comment]
This does work but the API is more for internal use:

```python
>>> func.amplitude._description
''
>>> func.amplitude.__doc__
''
```

**Comment by mdecleir** [comment]
> This does work but the API is more for internal use:

Thanks. That (_description) does not result in an error indeed, but it returns an empty string, so not really useful.

**Comment by nden** [comment]
There was a good intention to add description to each parameter but it did not materialize.
If anyone is willing to go and fill those in this may be a good contribution.

**Comment by Akshat1Nar** [comment]
I will like to work on this issue, Can someone help me out that what should I actually fill `description` variable in parameters.Parameter with? (I am new to this organisation and open source. I will like to participate in gsoc or outreachy also.)

**Comment by hamogu** [comment]
@Akshat1Nar You'll have to look at each model and see what the parameters mean, e.g. for this model :https://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.Linear1D.html#astropy.modeling.functional_models.Linear1D

the description would be "slope of line" and "intercept". I suggest that you just start with a few simple example and then start a pull request, where we can discuss in detail what to do. (It's easier to discuss that when you open a PR with a concrete suggestion.)
