### ISSUE TITLE
Context manager for handling "bad" units

### ISSUE THREAD

**Issue by aragilar** [astropy/astropy#11246]
Lots of existing data has unit strings which are problematic in some way: plural rather than singular (e.g. "Angstrom" vs "Angstroms"), alternate spellings (e.g. "Angstrom" vs "Angstroem" or "meter" vs "metre", although the latter should probably be allowed), or alternate shortened forms (e.g. "Ang" for "Angstrom"). The options for handing this are not ideal: users could create custom units to allow parsing the strings, though this would cause these problematic strings to propagate; try to do something with the ` UnrecognizedUnit` to correct the units (though this does tend to produce a large number of warnings, which is not ideal); or based on prior experience/knowledge hard code the units (which makes their code less robust to changes/new inputs).

An idea I had would be to have a context manager that allows setting temporary aliases—this avoid the need to define new units, and reduce warning fatigue, and prevent the propagation of bad unit strings. Usage would be something like:
```python
import astropy.units as u
from some_project import DataClass

with u.unit_aliases({"Angstroms": u.AA}):
    data = DataClass.read("some_file.fits")
```

**Comment by taldcroft** [comment]
This seems reasonable. I think this especially applies to FITS, and I wonder if it might make sense to include (within the FITS reader) a set of aliases that are commonly found in the wild. Then use these aliases by default unless strictness is enforced (being liberal on input).

**Comment by pllim** [comment]
What is the expected behavior when someone does this

```python
with u.unit_aliases({"meter": u.AA}):
   # ...
```

or this?

```python
with u.unit_aliases({"kg": u.AA}):
   # ...
```

I feel like this can cause some dangerous bugs if misused...

**Comment by pllim** [comment]
Also, some unit names are ambiguous (e.g., #4359). What if someone writes out data that says "0.1 foo" and someone else reads it thinking "foo" is an alias for something else?

**Comment by taldcroft** [comment]
The unit aliases should raise an exception if the alias is already defined as a unit. If somebody chooses to use `meter` for `u.AA` I don't see that as a problem that we need to worry about. This is basically just a convenience method to temporarily create a new unit in the context block (right?).

**Comment by mhvk** [comment]
@aragilar - this sounds interesting. Currently, thinks like `u.Unit('Angstroms')` already give
`ValueError(... Did you mean Angstrom or angstrom?)` - one option might be to simply allow taking the first option from "did you mean". Would this cover what you need?

In principle, what you want can be sort-of done already with:
```
In [5]: my_ang = u.Unit('Angstroms', u.AA)

In [6]: with u.add_enabled_units([my_ang]):
   ...:     tu = u.Unit('Angstroms')
   ...: 

In [7]: tu
Out[7]: Unit("Angstroms")

In [8]: tu == u.AA
Out[8]: True
```
The above may mostly work but of course it is annoying that the unit does not actually get converted, so when it gets written out, it will still have the wrong name.

I think it should also be possible to extend `u.add_enabled_units` to also take aliased names (could be as simple as adding a `**kwargs` of `alias_name=u.<standard_unit>`; or perhaps something more like what you have, `aliases={...}`). But it needs a bit of a dive into the `_UnitRegistry` class in `astropy.units.core`, in particular, the `add_enabled_units` method: https://github.com/astropy/astropy/blob/aef31beaf10153e3053f8f8515c373d2dd0a7fe1/astropy/units/core.py#L173-L209

**Comment by aragilar** [comment]
The idea is avoid needing to repeatedly write similar variations of code like https://github.com/astropy/specutils/blob/master/specutils/io/default_loaders/sixdfgs_reader.py#L177-L183 (which while not horrible, does throw lots of warnings around the units). If we can parse the units and do the corrections in a localised way (i.e. this doesn't affect other usage of units within the same process), we can keep possible ambiguities to a minimum. The temporary unit in the block is basically what I was thinking of, but I suspect we could probably be a bit smarter around how exactly the flow works.

The target audience of the context manager would library writers/advanced users who are interacting with a known source of bad unit strings (e.g. old surveys for which the files cannot be modified), where using `add_enabled_units` and similar may cause problems in other parts of the code (or simply propagate the bad unit strings), rather than those writing a one-off script.

There's also one final aspect which is nice, in that this effectively documents in code what unit string issues there are in a particular dataset.

**Comment by aragilar** [comment]
I don't know if we'd want some aliases on by default, I think this is best left up to readers of specific formats (e.g. specutils loaders for surveys like SDSS or those on the AAT).

**Comment by mhvk** [comment]
@aragilar - I agree one would want a solution that is temporary and on second thought it is probably a bad idea to overload `add_enabled_units`.

But looking again at its implementation, it should be relatively straightforward to add a `add_unit_aliases` method to the same class (and corresponding exposed function) which just adds aliases like in line 201 and 202 in the link above, but does not add new units. 

Indeed, I think this should not be much work, nor require that much package-specific knowledge (at least for units itself, not completely sure about the interaction with FITS/CDS...), so I labelled it as such. It may well be that the main work may end up being to write suitable tests....

p.s. Just to be sure: in your experience, would allowing automatic guesses be good enough, or does that still miss (or worse, misidentify) too many units?

**Comment by aragilar** [comment]
@mhvk I'm not sure I'm the best person to answer that, the files I come across are from "Australian" optical surveys (i.e. things from the AAT and other SSO telescopes, which are hosted/will be hosted by Data Central), which means I'm likely seeing files from the same group of people/codebases, which likely have the same issues (new surveys I've been pushing back on teams providing bad units, but there's quite a few old surveys where we can't fix them). There might be other trends/usages in other places (I haven't seen "Angstroem", but given it's used in an example in the docs, I'm guessing somewhere uses/used it), so I think at least for now, automatic guessing/default aliases should be avoided (I suspect once we know what's out there in terms of usage by users, a more "quantitative" approach around what aliases to include and not include by default might be reasonable).

**Comment by mhvk** [comment]
@aragilar - OK, makes sense. Overall, I think the approach of adding a new method to `_UnitRegistry` and a corresponding exposed function is the way to go!

**Comment by aragilar** [comment]
Testing the aliasing with some existing data, I've found a usability issue with the context manager: unit formats (other than the generic one) pre-block any units that are not on their allowed list (the case I hit was `astropy.wcs` using `format='fits'`). While this makes sense for `parse_strict="raise"`, for `parse_strict="warn"` or `parse_strict="ignore"`, the aliases are never looked up (as also happens to any usage of `add_enabled_units`, which is mentioned in the warnings), returning `UnrecognizedUnit` instead. Doing a second lookup with the generic loader would allow for aliases (and additional added units) to be used (with a warning raised if need be), but this could be viewed as a breaking change. I'll see if I can finish the PR (which will *not* include the second lookup), but I figured I'd flag this after tracing through most of `astropy.wcs` and `astropy.units` to work out exactly where the parsing without the aliases was happening.

**Comment by mhvk** [comment]
@aragilar - ai, yes, you are right, the general parser is different from the others (CDS, FITS, ...), in using the registry while parsing strings: https://github.com/astropy/astropy/blob/a6347384ffeea47d062bee1f3ea7f60af793d95b/astropy/units/format/generic.py#L443-L444

In contrast, for FITS, one ends up in just checking it is part of the "approved FITS" list: https://github.com/astropy/astropy/blob/a6347384ffeea47d062bee1f3ea7f60af793d95b/astropy/units/format/fits.py#L83-L84

This is a part that predates my involvement, so I hadn't really realized this. I agree that easiest might be to allow a second pass with the generic parser (for the non-string parsing options), but it obviously will need a bit of thought on how to do that, and make sure all formats behave the same (the files seem to have diverged quite a bit, sadly).

It might still make sense to wrap up the context manager first - I feel that is a good step regardless, and one that will help whatever we implement for FITS.
