### ISSUE TITLE
Invalid combination of arguments to BinnedTimeSeries should raise a warning

### ISSUE THREAD

**Issue by aaryapatil** [astropy/astropy#11262]
### Description

I am working on a PR for providing custom binning to `aggregate_downsample` #8584. This led me to test arguments to BinnedTimeSeries, and it seems that when I pass `time_bin_start` as an array and `time_bin_end` as a scalar (uneven contiguous bins) along with an `n_bins` argument, no warning/exception is provided. The functionality is correct, so I wanted to make sure if a warning should be expected here.

### Steps to Reproduce

1. Normal Scenario
```
>>> start = Time([1, 2, 3], format='cxcsec')
>>> end = Time(5, format='cxcsec')
>>> binned = BinnedTimeSeries(time_bin_start=start, time_bin_end=end)
>>> binned
<BinnedTimeSeries length=3>
time_bin_start   time_bin_size   
                       s         
    object          float64      
-------------- ------------------
           1.0 1.0000000000065512
           2.0 0.9999999999969589
           3.0   2.00000000000351
```

2. Unexpected Scenario
```
>>> binned = BinnedTimeSeries(time_bin_start=start, time_bin_end=end, n_bins=10)
>>> binned
<BinnedTimeSeries length=3>
time_bin_start   time_bin_size   
                       s         
    object          float64      
-------------- ------------------
           1.0 1.0000000000065512
           2.0 0.9999999999969589
           3.0   2.00000000000351

```

### Expected behavior
A warning/exception telling the user that `n_bins` is not valid in this scenario.

### System Details
I am using the latest astropy dev version

```
>>> import astropy
>>> astropy.__version__
'4.3.dev434+gf58e9673d.d20210121'
```

**Comment by pllim** [comment]
Docstring at https://docs.astropy.org/en/latest/api/astropy.timeseries.BinnedTimeSeries.html does, "This is only used if both `time_bin_start` and `time_bin_size` are provided and are scalar values."

**Comment by aaryapatil** [comment]
Yes, the doctoring says it clearly. I was just wondering if it would be better to give some warning to the user. If that sounds good, I can make the change.

**Comment by pllim** [comment]
I'll have to defer to @astrofrog .

**Comment by astrofrog** [comment]
I think raising an exception would be sensible

**Comment by aaryapatil** [comment]
Great! I'll get to that.
