### ISSUE TITLE
Installation Issue in development mode (conda virtual environment)

### ISSUE THREAD

**Issue by yogeshsangtani** [astropy/astropy#11270]
### Description

Hello, I am trying to contribute in Astropy, but When I tried to install it in development version as stated in 
https://docs.astropy.org/en/stable/development/workflow/get_devel_version.html#activate-the-development-version-of-astropy
using conda virtual environment it is showing an unexpected error 
`      error: could not create 'build\temp.win-amd64-3.9\Release\Users\Yogesh San
gtani\AppData\Local\Temp\pip-install-uvzg_qpz\cython_40c2cf04bd30442f84a12ffcc83
34c30\Cython\Plex': The filename or extension is too long`

###Dependencies Versions
Python - 3.9.1
cython - 0.29.21
jinja2 - 2.11.2 

Also , It would be much better if the below tutorial describes conda environment installation of Astropy in more explained way.
https://docs.astropy.org/en/stable/development/workflow/virtual_pythons.html#virtual-envs

**Comment by pllim** [comment]
I am not sure if any more explanation would help in this case. I think this is a conda bug, please see conda/conda#7203
