### ISSUE TITLE
Control dtype with ascii.read (converters API needs better doc or refactoring)

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#11278]
I cannot find a way to control the dtype of the output table when reading a file into a `Table`. Consider the following MWE, with 3 numerical columns, while one of them would preferably be kept as a string:

```
>>> from astropy.io import ascii

>>> indata = ("# This is a dummy file\n" 
...           "# with some text to ignore, and a header with column names\n" 
...           "# ra dec objid\n" 
...           "1 2 345\n" 
...           "3 4 456\n") 

>>> ascii.read(indata, format='commented_header', header_start=2, guess=False, fast_reader=False)
<Table length=2>
  ra   dec  objid
int64 int64 int64
----- ----- -----
    1     2   345
    3     4   456

>>> ascii.read(indata, format='commented_header', header_start=2, dtye=('i8', 'i8', 'S10'), guess=False, fast_reader=False)
TypeError: __init__() got an unexpected keyword argument 'dtye'
```

Reading in the same with `np.loadtxt` and then converting to a Table works, but it should ideally be supported directly.

```
import numpy as np
from astropy.table import Table

>>> Table(np.loadtxt('/tmp/a', dtype=[('ra', 'i8'), ('dec', 'i8'), ('objid', 'S10')]))
<Table length=2>
  ra   dec   objid 
int64 int64 bytes10
----- ----- -------
    1     2     345
    3     4     456
```

**Comment by pllim** [comment]
I used [converters](https://docs.astropy.org/en/stable/io/ascii/read.html#converters) when I had to do this a long time ago. And I think it still works? 

```python
>>> converters = {
...     'ra': [ascii.convert_numpy(np.int)],
...     'dec': [ascii.convert_numpy(np.int)],
...     'objid': [ascii.convert_numpy(np.str)]}
>>> t = ascii.read(
...     indata, format='commented_header', header_start=2,
...     converters=converters, guess=False, fast_reader=False)
>>> t
<Table length=2>
  ra   dec  objid
int32 int32  str3
----- ----- -----
    1     2   345
    3     4   456
```

You might have to play around with it until you get the exact data type you want though. Hope this helps!

**Comment by bsipocz** [comment]
Oh, yes, indeed, this is exactly what I need. One minor comment though, it would be helpful to have the word `dtype` somewhere in the docs, as I was searching for `dtype` in that and many other docs pages without any useful results. (maybe it's just me, that case this can be closed without a docs change, otherwise this can be a good "first issue").

It's also not clear what the "previous section" is referred to in ``These take advantage of the convert_numpy() function which returns a two-element tuple (converter_func, converter_type) as described in the previous section.``

**Comment by taldcroft** [comment]
Yes, the `converters` mechanism is not that obvious and a perfect example of overdesign from this 10+ year old package.

It probably would be easy to add a `dtype` argument to mostly replace `converters`. This would pretty much just generate those `converters` at the point when needed.  Thoughts?

**Comment by pllim** [comment]
I agree that the `converters` API could be improved; I have a very old feature request at #4934  , which will be moot if you use a new API like `dtype=[np.int, np.int, np.str]` or `dtype=np.int` (the latter assumes broadcasting to all columns, which might or might not be controversial).

**Comment by taldcroft** [comment]
I've implemented this in a few lines of code. As always the pain is testing, docs etc. But maybe there will be a PR on the way.
```
In [2]: >>> ascii.read(indata, format='commented_header', header_start=2, dtype=('i8', 'i4', 'S10'), guess=False, fast_reader=False)
Out[2]: 
<Table length=2>
  ra   dec   objid 
int64 int32 bytes10
----- ----- -------
    1     2     345
    3     4     456
```

**Comment by bsipocz** [comment]
Thank you, this looks very good to me. I suppose converter is a bit like clobber for fits, makes total sense when you already know about it, but a bit difficult to discover. The only question whether dtype should also understand the list of tuples that include the column name to be consistent with numpy. I don't think that API is that great, still is worth some thinking about.

**Comment by pllim** [comment]
Do we... need an APE? 😸

**Comment by taldcroft** [comment]
I was planning for the `dtype` to be consistent what `Table` accepts, which is basically just a sequence of simple dtypes. It starts getting complicated otherwise because of multiple potentially conflicting ways to provide the names. Allowing names in the dtype would also not fit in well with the current implementation in `io.ascii`.

**Comment by taldcroft** [comment]
@bsipocz - does #13073 work to close this out? Maybe more `dtype`s in the docs?

**Comment by bsipocz** [comment]
I think I like the numpy/pandas API more as it allows to use either `dtype` or `converters`. The latter still doesn't come naturally when one is looking for setting the dtypes, and is still more difficult to discover. But the PR is certainly an improvement as it simplifies the current usage.

**Comment by taldcroft** [comment]
With #13073 the astropy `converters` can be used precisely as the pandas `dtype` dict. So an option is to add a `dtype` arg that is just an alias for `converters`, but that is probably going in the wrong direction for API simplicity.

**Comment by bsipocz** [comment]
I'm all for API simplicity, but also for sharing common/similar API with widely used packages in the ecosystem. And I have the feeling that the `dtype` kwarg is more often used than the `converters` one in those APIs.

The added complexity is already in there as now `converters` accept dtypes, too, but not the convenience to use the accustomed name for it.
