### ISSUE TITLE
Angle formatting doesn't check unit

### ISSUE THREAD

**Issue by aragilar** [astropy/astropy#11280]
`Angle.to_string` with `sep` specified as either `"dms"` or `"hms"` does not check that `sep` matches the unit the angles are in, and instead assumes that units are fine. Therefore, if `"dms"` is used with an angle in hours or `"hms"` is used with an angle in degrees, the string shows the wrong value. A good test case is RA = 7.5252505d, Dec = -2.021007d (both in degrees), where `"hms"` is used for RA and `"dms"` is used for Dec—the output is 7h31m30.8796s, -2d01m15.6316s.

I can see two ways of resolving this: either a warning or error is raised when the units do not match what would be accepted by `sep`, or that the values are converted to the correct units for the separator. 

I first found this in astropy 4.1, but latest master is affected, and I don't see any reason why earlier versions of astropy wouldn't be affected either.

Example code which shows the "hms" and degree case:
```
>>> import astropy.coordinates as coord
>>> a = coord.SkyCoord(ra="7.5252505d", dec="-2.021007d")
>>> a.ra.to_string(sep="hms")
'7h31m30.9018s'
>>> a.dec.to_string(sep="dms")
'-2d01m15.6252s'
>>> 
```

**Comment by pllim** [comment]
Thanks for reporting this!

FWIW, I would say auto-convert is the more intuitive behavior, but if that is too complicated to implement, then raising error is the next best thing.

**Comment by dhomeier** [comment]
```
>>> a.to_string(style='hmsdms')
'00h30m06.0601s -02d01m15.6252s'
```
does it right, so should be possible to implement this for the components.

**Comment by dhomeier** [comment]
I think the difference to `SkyCoord.to_string(style='...')` is that `sep` really just seems to specify a formatting option; it accepts as well
```
a.dec.to_string(sep='hms')
'-2h01m15.6252s'
>>> a.dec.to_string(sep='abc')
'-2a01b15.6252c'
```
so you might be expecting functionality that `coordinates.Angle.to_string()` simply does not offer. I still think it probably would be possible to implement, but needs discussion if it's not rather a documentation issue, and if it should perhaps be instead provided by a `style` kwarg for consistency.

**Comment by aragilar** [comment]
@dhomeier Sure, that's why I suggested throwing an error (or at least a warning) when there's a conflict between what `sep` suggests and the units (as I suspect I'm not the only person who has run into this, there's probably other code silently giving out invalid values). Something like (with the right exceptions/helpful error text):
```
if unit == u.degree and sep == "hms":
    raise Error
elif unit == u.hourangle and sep == "dms":
    raise Error
```
would be enough to catch this in other people's code, and allow users to fix their code.

**Comment by mhvk** [comment]
I agree this is super-confusing, and although it is arguably consistent with the docstring (see below), I think it really is just a bug. I cannot see any case where the example on top would be correct.

My suggestion would be that for the case that `sep` is explicitly given, it sets a corresponding default for `unit` (i.e., convert to hourangle for `hms`, degrees for `dms`, check that unit is deg or hourangle for `:`, and that an error is raised if `sep` is not recognized).

```
       sep : str, optional
            The separator between numbers in a sexagesimal
            representation.  E.g., if it is ':', the result is
            ``'12:41:11.1241'``. Also accepts 2 or 3 separators. E.g.,
            ``sep='hms'`` would give the result ``'12h41m11.1241s'``, or
            sep='-:' would yield ``'11-21:17.124'``.  Alternatively, the
            special string 'fromunit' means 'dms' if the unit is
            degrees, or 'hms' if the unit is hours.
```

**Comment by dhomeier** [comment]
I agree about the confusion, but again would point out that this disables some possible usages supported by the current behaviour and the docstring. Basically, what values of `sep` are we going to recognise that would not raise an error? The example of `-:` would not have been very meaningful to me before I saw it in the docs. Or as a perhaps exotic, but not entirely illogical example, assume someone wanted to use `sep='gms'` (German for 'dms')...
It's fine with me if we do change the API to support only a specific set of international unit symbols (which probably would be ':', '-:' and either 'dms' or 'hms' – perhaps also their uppercase variants?), but I would feel better in using consistent syntax with `SkyCoord.to_string()` (like using `style=` for both).

**Comment by mhvk** [comment]
@dhomeier - you're right, an alternative would be to use `style` - worth thinking through.

Just to be clear about my proposal: no error would be raised if the user passed in explicit `unit` and `sep` arguments, so for your example, safe string conversion would be `angle.to_string(u.hourangle, sep='gms')` -- and one could get the current broken behaviour by `angle.to_string(u.deg, sep='hms'). The idea would be to avoid guessing, and for the hexagesimal formatting options never rely on the unit that the angle happens to have.

**Comment by dhomeier** [comment]
OK, I had missed the part with allowing explicit setting of `unit=` to override the check – that sounds like a sensible solution. If I am understanding right, this would also remove the current `sep='fromunit'` as default (or _only_ if `unit` is explicitly specified)? Would actually make sense as well; I'd find it possibly more logical for the default output to match that of `SkyCoord.to_string()`, i.e. make
```
>>> a.ra.to_string()
'7.52525'
```
(while currently there is no option at all for returning plain floating-point format).

**Comment by mhvk** [comment]
Yes, `unit` would override the check.

I agree a different default might make more sense but fear it may be too late for that - I fear we'd change what likely is the most used mode, of just `angle.to_string()`.

**Comment by dhomeier** [comment]
I agree that changing the default would be quite risky now. But then the second part of
> The idea would be to avoid guessing, and for the hexagesimal formatting options never rely on the unit that the angle happens to have.

would remain the default situation (though it's not really what unit the angle "happens to have", with the default always `u.deg` and anything else explicitly specified by the user).

**Comment by mhvk** [comment]
@dhomeier - hmm, I hadn't quite realized the current behaviour is as specifically targeted to `hourangle` and `degree` as it is:
```
In [8]: Angle(1, 'deg').to_string()
Out[8]: '1d00m00s'

In [9]: Angle(1, 'hourangle').to_string()
Out[9]: '1h00m00s'

In [10]: Angle(1, 'rad').to_string()
Out[10]: '1rad'
# Same for any other angle unit.
```

Not quite sure what to do with that - even less so given that `u.Quantity.to_string()` gives `'1.0 rad'` by default.

But perhaps we can in the first instance fix the issue of happily typesetting angles in degrees as hms...
