### ISSUE TITLE
convolve_models does not work as I would expect for 2D models

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#11311]
### Description

I want to convolve a Sersic profile with a Moffat kernel (and then a Gausian one), to calculate the fraction of light that goes into a fiber area with a certain seeing. From the docs, I would assume that I can do a

```Python
from astropy.modeling.models import Sersic2D, Moffat2D
from astropy.convolution import convolve_models

sersic = Sersic2D()
moffat = Moffat2D()
my_model = convolve_models(sersic, moffat)
```
and then just integrate `∫my_model(r,0)⋅r⋅π⋅dr` (r=0…r_fiber) to get the fraction of light that goes into the fiber. However, the compound model does not behave as expected. For the plain Sersic and Moffat, the plots for different x arrays match perfectly:
```Python
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(3., 10, 0.01)
plt.plot(x, moffat(x, 0))
plt.plot(x, sersic(x, 0))
x = np.arange(4., 10, 0.01)
plt.plot(x, moffat(x, 0))
plt.plot(x, sersic(x, 0))
plt.show()
```
![c1](https://user-images.githubusercontent.com/397223/107370058-ca0dfe80-6ae2-11eb-919f-e380ba5bd456.png)

However, for the convolved model this is not the case:
```Python
x = np.arange(3., 10, 0.01)
plt.plot(x, my_model(x, 0))
x = np.arange(4., 10, 0.01)
plt.plot(x, my_model(x, 0))
plt.show()
```
![c2](https://user-images.githubusercontent.com/397223/107369909-9af78d00-6ae2-11eb-8df8-49d36548181f.png)

Beside of the different value for different starting values, the curve itself is not as smooth as one would expect.

Also, calling the model with single values does not work: `my_model(1,0)` results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/astropy/modeling/core.py", line 2820, in __call__
    return self._evaluate(*args, **kw)
  File "/usr/lib/python3/dist-packages/astropy/modeling/core.py", line 2837, in _evaluate
    return self._apply_operators_to_value_lists(leftval, rightval, **kw)
  File "/usr/lib/python3/dist-packages/astropy/modeling/core.py", line 2706, in _apply_operators_to_value_lists
    return binary_operation(SPECIAL_OPERATORS[op], leftval, rightval)
  File "/usr/lib/python3/dist-packages/astropy/modeling/core.py", line 3520, in binary_operation
    return binoperator(left, right)
  File "/usr/lib/python3/dist-packages/astropy/nddata/decorators.py", line 246, in wrapper
    result = func(data, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/astropy/convolution/convolve.py", line 675, in convolve_fft
    np.max(np.array(arrayshape) + np.array(kernshape))))
  File "<__array_function__ internals>", line 5, in amax
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```
This is also when I try to feed `my_model` into `scipy.integrate.quad()`.

### Expected behavior

I would expect for the convolved model to be consistent with different x arrays, and to be smoothly. Ofcourse, Sersic is a bit nasty in that it may strongly peak at the origin (however, the same happens when I replace Sersic with Gaussian). But maybe there is a better way to calculate the fraction of light that falls into a circular area?

### Actual behavior

See above

### Steps to Reproduce

See above

### System Details
 * Linux-5.10.0-2-amd64-x86_64-with-glibc2.31
 * Python 3.9.1+ (default, Feb  5 2021, 13:46:56) [GCC 10.2.1 20210110]
 * Numpy 1.19.4
 * astropy 4.2
 * Scipy 1.6.0
 * Matplotlib 3.3.4

(all from Debian Testing)

**Comment by pllim** [comment]
Is convolving 2 models here equivalent to `my_model = sersic * moffat`? Because that one doesn't crash, looks smooth, and the evaluation matches for different `x`.

```python
>>> my_model(1, 0)  # Is this the answer?
0.5
```

**Comment by olebole** [comment]
@pllim 
> Is convolving 2 models here equivalent to my_model = sersic * moffat? 

Unfortunately not. It is the convolution of the first model with the second one, a pretty expensive operation (even more in 2D). That's why I was happy if the models would magically do his :-)
