### ISSUE TITLE
print() does not work with CompoundModel

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#11310]
### Description

Trying to print a CompoundModel (from `convolve_models()`) leads to an exception.

### Expected behavior

It is expected that print() always works (and prints someting useful :-) )

### Actual behavior

```
>>> from astropy.modeling.models import Sersic2D, Gaussian2D
>>> from astropy.convolution import convolve_models
>>> m = convolve_models(Sersic2D(), Gaussian2D())
>>> m
<CompoundModel(amplitude_0=1., r_eff_0=1., n_0=4., x_0_0=0., y_0_0=0., ellip_0=0., theta_0=0., amplitude_1=1., x_mean_1=0., y_mean_1=0., x_stddev_1=1., y_stddev_1=1., theta_1=0.)>
>>> print(m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/astropy/modeling/core.py", line 3057, in __str__
    expression = self._format_expression()
  File "/usr/lib/python3/dist-packages/astropy/modeling/core.py", line 3034, in _format_expression
    oper_order = OPERATOR_PRECEDENCE[node.op]
KeyError: 'convolve_fft'
```

### Steps to Reproduce

see above

### System Details

 * Linux-5.10.0-2-amd64-x86_64-with-glibc2.31
 * Python 3.9.1+ (default, Feb  5 2021, 13:46:56) [GCC 10.2.1 20210110]
 * Numpy 1.19.4
 * astropy 4.2
 * Scipy 1.6.0
 * Matplotlib 3.3.4

(all from Debian Testing)

**Comment by pllim** [comment]
Pretty sure it works if you create the compound model outside of convolution, so I marked this as a bug in convolution, rather than modeling. FYI.

**Comment by pllim** [comment]
Hmm... I changed my mind. Could be that this use case was overlooked when @perrygreenfield refactored `modeling` too.

**Comment by pllim** [comment]
```python
>>> m.op
'convolve_fft'
>>> m.right
<Gaussian2D(amplitude=1., x_mean=0., y_mean=0., x_stddev=1., y_stddev=1., theta=0.)>
>>> m.left
<Sersic2D(amplitude=1., r_eff=1., n=4., x_0=0., y_0=0., ellip=0., theta=0.)>
```

**Comment by olebole** [comment]
I just checked that this (as well as #11311) also is an issue of Astropy 3.1.2 (which came with Debian Buster), so it is not the effect of a later re-organization.
