### ISSUE TITLE
Fitting in astropy.modeling much slower in 4.2 than 3.2.3

### ISSUE THREAD

**Issue by karllark** [astropy/astropy#11314]
### Description

The speed of the fitting in astropy.modeling was seen to be significantly slower after astropy 4.0 was released.  This was commented by multiple developers of the [pahfit](https://github.com/PAHFIT/pahfit) package.  This package is a spectral decomposition tool that fits *many* lines and continuum components to NIR/MIR spectra of interstellar matter emission.

### Expected behavior

Similar run times in both version of astropy

### Actual behavior

10x slower when run with astropy 4.2 compared to astropy 3.2.3

**astropy4.2**

(base) [kgordon@grimy pahfit]$ time scripts/run_pahfit --savefig=png pahfit/data/M101_Nucleus_irs.ipac pahfit/packs/scipack_ExGal_SpitzerIRSSLLL.ipac
WARNING: The fit may be unsuccessful; check fit_info['message'] for more information. [astropy.modeling.fitting]
Number of calls to function has reached maxfev = 200.

real	0m32.365s
user	0m33.346s
sys	0m1.471s

**astropy3.2.3**

(astropy323) [kgordon@grimy pahfit]$ time scripts/run_pahfit --savefig=png pahfit/data/M101_Nucleus_irs.ipac pahfit/packs/scipack_ExGal_SpitzerIRSSLLL.ipac
WARNING: The fit may be unsuccessful; check fit_info['message'] for more information. [astropy.modeling.fitting]
Number of calls to function has reached maxfev = 200.

real	0m3.176s
user	0m4.046s
sys	0m1.211s

***notes***
Used two slightly different versions of python (3.7 for astropy 3.2.3 and 3.8 for astropy 4.2) to get the conda environments to be independent.   Clearly not a conda expert yet.  Regardless, testing this with different versions of python give very similar answers.

### Steps to Reproduce

1. Use the [testastropy](https://github.com/karllark/pahfit/tree/testastropy) branch of karllark/pahfit to run the command given above.  This branch works in the two version of astropy tested above

**astropy 4.2 result**

![M101_Nucleus_irs_astropy42](https://user-images.githubusercontent.com/1554536/107393860-3ed43f00-6ac9-11eb-9f69-9f26de9222e0.png)

**astropy 3.2.3 result**

![M101_Nucleus_irs_astropy323](https://user-images.githubusercontent.com/1554536/107393873-409e0280-6ac9-11eb-8873-8e94d8432c78.png)

### System Details

**astropy 4.2 conda environment**

>>> import platform; print(platform.platform())
Linux-5.10.8-100.fc32.x86_64-x86_64-with-glibc2.10
>>> import sys; print("Python", sys.version)
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.20.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.2
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.6.0
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.3.4

**astropy 3.2.3 conda environment**

>>> import platform; print(platform.platform())
Linux-5.10.8-100.fc32.x86_64-x86_64-with-fedora-32-Thirty_Two
>>> import sys; print("Python", sys.version)
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.20.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 3.2.3
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.6.0
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.3.4

**Comment by pllim** [comment]
For completeness, did you try both astropy versions with the same Python version?

**Comment by karllark** [comment]
> For completeness, did you try both astropy versions with the same Python version on the same machine?

Have not managed to do this yet.  I can, but this slowdown has been been seen *since* v4.0, hence under multiple versions of python.  I'll do this and confirm.  Will take a few min.

**Comment by karllark** [comment]
The same behavior is confirmed with python 3.7 and astropy 4.2.

```
[kgordon@grimy pahfit]$ pip install astropy
Collecting astropy
  Downloading astropy-4.2-cp37-cp37m-manylinux1_x86_64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 10.7 MB/s 
Requirement already satisfied: numpy>=1.17 in /home/kgordon/Bin/miniconda3/envs/astropy323/lib/python3.7/site-packages (from astropy) (1.20.1)
Collecting pyerfa
  Downloading pyerfa-1.7.2-cp37-cp37m-manylinux2010_x86_64.whl (702 kB)
     |████████████████████████████████| 702 kB 8.3 MB/s 
Installing collected packages: pyerfa, astropy
Successfully installed astropy-4.2 pyerfa-1.7.2
(astropy323) [kgordon@grimy pahfit]$ time scripts/run_pahfit --savefig=png pahfit/data/M101_Nucleus_irs.ipac pahfit/packs/scipack_ExGal_SpitzerIRSSLLL.ipac
WARNING: The fit may be unsuccessful; check fit_info['message'] for more information. [astropy.modeling.fitting]
Number of calls to function has reached maxfev = 200.

real	0m57.129s
user	0m57.704s
sys	0m1.228s

```

**Comment by karllark** [comment]
Very different results from profiling.  Using snakeviz to view the profiling output.

**astropy 4.2**

![Screenshot from 2021-02-09 11-50-46](https://user-images.githubusercontent.com/1554536/107398014-3847c680-6acd-11eb-846d-0b3045d296f5.png)

**astropy 3.2.3**

![Screenshot from 2021-02-09 11-51-01](https://user-images.githubusercontent.com/1554536/107398077-48f83c80-6acd-11eb-8f00-c382cac3d349.png)

**Comment by pllim** [comment]
Thanks for all the info! @perrygreenfield , any insights on this?

**Comment by perrygreenfield** [comment]
Not yet. I will have to look at their source code to get a better idea of what is going on.

**Comment by dhomeier** [comment]
22127700 calls to `_ConstraintsDict.__setitem__()` does not look healthy.

**Comment by karllark** [comment]
PR #11365 looks much better.  For the record, here is the snakeviz from profiling running with the PR branch.

![Screenshot from 2021-03-08 13-36-41](https://user-images.githubusercontent.com/1554536/110365820-7e803f00-8013-11eb-8f9f-12cb51b6c8de.png)
