### ISSUE TITLE
Table(list_of_dicts) does not work as expected for quantities

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#11327]
### Description

Giving `Table` a list of dicts with quantities results in dtype object with single quantities in each row / column.

### Expected behavior

Detect the quantities and create a column that has dtype float and a unit attached.

### Actual behavior

See description

### Steps to Reproduce

```python
In [1]: from astropy.table import Table

In [2]: import astropy.units as u

In [3]: data = [{'x': 5 * u.m, 'y': 0 * u.m}, {'x': 10 * u.m, 'y': 3 * u.m}]

In [4]: Table(data)
Out[4]: 
<Table length=2>
  x      y   
object object
------ ------
 5.0 m  0.0 m
10.0 m  3.0 m

```

### System Details
```
Linux-5.10.15-1-MANJARO-x86_64-with-glibc2.33
Python 3.9.1 (default, Feb  6 2021, 06:49:13) 
[GCC 10.2.0]
Numpy 1.20.0
astropy 4.2
Scipy 1.6.0
Matplotlib 3.3.4
```

**Comment by maxnoe** [comment]
The "correct" table can currently be achieved by afterwards doing:

```
In [13]: t['x'] = u.Quantity(t['x'].tolist())
In [14]: t['y'] = u.Quantity(t['y'].tolist())
```

**Comment by pllim** [comment]
Why not use `QTable`?

```python
>>> QTable(data)
<QTable length=2>
   x       y   
   m       m   
float64 float64
------- -------
    5.0     0.0
   10.0     3.0
```

**Comment by maxnoe** [comment]
That's probably for another issue, but we found issues with accessing metadata with QTable.

**Comment by pllim** [comment]
I vaguely remember recommending QTable over Table, especially if your data is Quantity. There was even a PR to that effect. Maybe @taldcroft or @mhvk can elaborate.

**Comment by mhvk** [comment]
Indeed, I'd recommend `QTable` - which is essentially the same as `Table` except how it treats columns with units. So, any difference in how `meta` is treated sounds like a bug to me...  Could you open a separate issue for that?

p.s. Doesn't take away from the behaviour here being a bug, of course!

**Comment by taldcroft** [comment]
PR coming...

**Comment by taldcroft** [comment]
See #11329.
