### ISSUE TITLE
astropy.table.join_skycoord issue and workaround

### ISSUE THREAD

**Issue by AstroMike** [astropy/astropy#11334]
### Description

When using astropy.table.join_skycoord it joins on SkyCoord and common fields

### Expected behavior

Since I am providing a join function I do not expect any other fields to be included

### Actual behavior

Joins on the intersection of the common field and SkyCoord

### Steps to Reproduce

Modifying the example from the docs to include a name field

```python
sc1 = astropy.coordinates.SkyCoord([0, 1, 1.1, 2], [0, 0, 0, 0], unit='deg')
sc2 = astropy.coordinates.SkyCoord([0.5, 1.05, 2.1], [0, 0, 0], unit='deg')
n1 = ['a','b','c','d']
n2 = ['e','f','d']

t1 = astropy.table.Table([sc1, n1], names=['sc', 'name'])
t2 = astropy.table.Table([sc2, n2], names=['sc', 'name'])
t12 = astropy.table.join(t1, t2, join_funcs={'sc': join_skycoord(0.2 * u.deg)})
print(t12)
```

returns
```
sc_id   sc_1  name   sc_2 
      deg,deg      deg,deg
----- ------- ---- -------
    2 2.0,0.0    d 2.1,0.0
```

### Workaround

Explicitly adding the 'sc' to the keys parameter

```python
t12 = astropy.table.join(t1, t2, keys='sc', join_funcs={'sc': join_skycoord(0.2 * u.deg)})
print(t12)
```

returns
```
sc_id   sc_1  name_1   sc_2   name_2
      deg,deg        deg,deg        
----- ------- ------ -------- ------
    1 1.0,0.0      b 1.05,0.0      f
    1 1.1,0.0      c 1.05,0.0      f
    2 2.0,0.0      d  2.1,0.0      d
```

### System Details

Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.9 (default, Aug 31 2020, 07:22:35) 
[Clang 10.0.0 ]
Numpy 1.19.2
astropy 4.2
Scipy 1.6.0
Matplotlib 3.3.4

**Comment by pllim** [comment]
Hard to tell if this is a bug or not from https://docs.astropy.org/en/latest/table/operations.html#joining-coordinates-and-custom-join-functions . Looking at the example there, if I rename the `name` of your second table, it works:

```python
>>> t2 = astropy.table.Table([sc2, n2], names=['sc', 'name2'])
>>> astropy.table.join(t1, t2, join_funcs={'sc': join_skycoord(0.2 * u.deg)})
<Table length=3>
sc_id   sc_1  name   sc_2   name2
      deg,deg      deg,deg       
int64  object str1  object   str1
----- ------- ---- -------- -----
    1 1.0,0.0    b 1.05,0.0     f
    1 1.1,0.0    c 1.05,0.0     f
    2 2.0,0.0    d  2.1,0.0     d


```

**Comment by AstroMike** [comment]
Yes, the behaviour you is consistent with the above: if you rename one of the columns, there are then no common column names, so the code can no longer match on those, only on SkyCoord, and the issue disappears. 

But in practice tables very often have common names such as 'name' or 'object' or 'ID' or even 'RA" ... and in that case one would get the (to me) unexpected behaviour that joining on SkyCoord would produce no or fewer matches than if those common keys were not present.  Since user is providing an explicit join func, I would expect the join to be ONLY with that join func .

**Comment by pllim** [comment]
Thanks for the clarification! I'll have to loop in @taldcroft or @mhvk here.

**Comment by taldcroft** [comment]
I think this is expected and correct behavior. In general for a table join if you do not specify the join keys then it will use all keys that are in common between the two tables. In this case that is `sc` and `name`, so it has joined on those two. The `join_funcs` dict only specify how to override the normal exact match join functionality, but it does not say which columns are to be joined.

This does point to improving the docs in the example to include the `keys` argument.

**Comment by taldcroft** [comment]
See #11335.

**Comment by AstroMike** [comment]
Well, from my perspective I was completely baffled for hours ... but maybe that's just me. 

I was expecting exactly what you said  "the join_funcs dict only specifies how to **_override_** the normal exact match join functionality", in other words I expected this to override the usual keys matching.

**Comment by mhvk** [comment]
I'm not surprised you were baffled! I think other people might be baffled, though, if matching a table first failed because a join function was needed, and then when they pass in a nice function, the join no longer includes columns that do not need such a function...

So, what's needed would seem to be better documentation....  Is the change @taldcroft proposes in #11335 at a place where it would have saved you those hours!?!? (E.g., could one usefully add a few words to the docstring of `join` itself?)

**Comment by AstroMike** [comment]
Docs with better examples definitely can't hurt, and the proposed revision has the critical addition ``keys='sc'``.  For those people (most?) who Google for an example and tweak, this will help.

I could quibble and say that the multiple appearances of 'sc' in both keys and the join function seems a bit clunky. But I won't.

So turning to enhancements, I think what the average user wants is a syntax like

```python
t12 = astropy.table.join(t1, t2, sep = 0.2*u.deg)
```
where ``join``  just figures it out: "Oh I see that each table already has a SkyCoord column, let's (only) use those".

**Comment by taldcroft** [comment]
@astromike - the issue with your API enhancement suggestion is that the `sep` keyword is narrowly tailored to one use case, while the `join` function is a very general function for table joins. We also try to avoid guessing the user intent. The "just figures it out" part may end up causing users grief if we haven't anticipated some situation (which becomes more likely with many users). Thus it is generally safer to be explicit.

If you have other constructive suggestions for documentation improvements (PR welcome!) please let us know. Also, please do avoid disparaging and snarky remarks, these are never welcome to the folks devoting their time making astropy work.

**Comment by AstroMike** [comment]
Apologies if my rather lame attempts at light humour came out as snarkiness. Wasn't the intent.
