### ISSUE TITLE
Default logging level is 'INFO', documentation states 'WARNING'

### ISSUE THREAD

**Issue by jwoillez** [astropy/astropy#11348]
The default logging level is 'INFO' as shown here:
https://github.com/astropy/astropy/blob/eceb10c3ed0eb0d33c41d453c5d33750c743b388/astropy/logger.py#L52

But the documentation says 'WARNING':
https://github.com/astropy/astropy/blob/master/docs/logging.rst

Personally, I would prefer to have 'WARNING', to offer two extra levels of debugging.
I can submit a PR if you agree.

**Comment by pllim** [comment]
Yeah, this is weird... Both seem to be from #192 by @astrofrog . An earlier commit there did set default to WARN but later changed to info in the same PR. I think updating the documentation to match is the less controversial way to go, since this has been the behavior for the past 9 years.

**Comment by taldcroft** [comment]
Somewhat related, a little while ago I stumbled on this nice and detailed discussion in matplotlib of logging levels and logging.warning vs warnings.warn.
https://matplotlib.org/3.3.3/devel/contributing.html#using-logging-for-debug-messages

**Comment by jwoillez** [comment]
If we remain at 'INFO' (i.e. not the default of logging), then I would appreciate if we could add a 'VERBOSE' level of some sort. You can check the use case in the astroquery issue I referenced above.

**Comment by pllim** [comment]
You can customize the setting at astroquery level, it is a configuration item...

https://github.com/astropy/astropy/blob/eceb10c3ed0eb0d33c41d453c5d33750c743b388/astropy/astropy.cfg#L62-L67

**Comment by ayshih** [comment]
> If we remain at 'INFO' (i.e. not the default of logging), then I would appreciate if we could add a 'VERBOSE' level of some sort. You can check the use case in the astroquery issue I referenced above.

Finer gradations of logging already possible.  You can log at an integer level between 20 (`INFO`) and 10 (`DEBUG`).  You'd use the number `N` with `logger.log(N, ...)` and with `logger.setLevel(N)`.

**Comment by jwoillez** [comment]
@pllim Indeed, but then we would need to properly derive the astroquery logger from the astropy one, rather than use the astropy one directly. Correct?

**Comment by jwoillez** [comment]
Asking because I also noticed this: https://github.com/astropy/package-template/issues/134

**Comment by pllim** [comment]
I am actually not sure what is the best way to do this. I don't think the logger was originally designed to be used downstream? I mean, there wasn't really any downstream packages 9 years ago to worry about.

However, I don't think just because astroquery wants to use it with a different default is a good enough justification to change it in the core library here.

**Comment by ayshih** [comment]
Again (https://github.com/astropy/astropy/issues/11348#issuecomment-785283586): if the desire is to have a logging level between `DEBUG` and the default Astropy logging level, that can already be done while keeping the default Astropy logging level as `INFO`.

**Comment by jwoillez** [comment]
@pllim Makes sense. I was just surprised to see info() messages appear when they should have not. We will see what we can do on the astroquery side.
@ayshih Indeed, thanks for the suggestion. Sticking with the default levels is probably better, and more familiar to logging users.

**Comment by saimn** [comment]
Using the Astropy logger for another package seems a bad idea, since it would make it impossible to filter logs from a specific package. So it's better to use a logger specific to astroquery, but if you want the extra features from the astropy logger it's possible to replicate the `_init_log` function when you would replace astropy by astroquery:

https://github.com/astropy/astropy/blob/eceb10c3ed0eb0d33c41d453c5d33750c743b388/astropy/logger.py#L97-L103

**Comment by saimn** [comment]
Also the astropy log has currently very little use, a bit in `nddata` and in some scripts, which could explain why nobody complained about the default INFO level ;). Using WARNING by default for a library makes more sense, but for scripts often you want INFO which may be a reason why we have INFO ?

**Comment by ayshih** [comment]
SunPy uses an instance of `AstropyLogger` for its own logger, and apparently we use it more than Astropy does.  I think it's very useful to that we have our default logging level at `INFO`.  We use `INFO` for informational messages that are important enough to show to users by default (i.e., not just during debugging) but aren't actually warnings.

I think there is value in creating a custom `VERBOSE` level that falls between `INFO` and `DEBUG`, and creating a `logger.verbose()` method and overriding `logger.setLevel()` to accept 'VERBOSE' seem like straightforward enhancements.

**Comment by jwoillez** [comment]
@ayshih Thanks a lot for the SunPy reference, very useful. In astroquery, I went for an added TRACE=5 level.

**Comment by pllim** [comment]
So, as far as I can understand this conversation, if we fix the doc, all is well?

**Comment by jwoillez** [comment]
Exactly. Sorry for all the (very useful) noise.

**Comment by pllim** [comment]
@jwoillez , since you caught the error in the first place, do you want to submit a doc fix for the credit? 😸 😉 

p.s. No noise at all. A very useful conversation, indeed!

**Comment by pllim** [comment]
p.p.s. If you think it will benefit the community, a new section on how to inherit the logger wouldn't hurt, though that would be separate PR from the fix.

**Comment by jwoillez** [comment]
@pllim I did not really inherit (as in astroquery being a child of astropy in the logging hierarchy), but followed what was down in SunPy. I had to deal with some interesting side effects in the process. Some modules of astroquery used `logging.getLogger(__name__)` which creates a child of AstropyLogger. Not sure I would want to document this... Other potential developers will eventually find this issue.

**Comment by pllim** [comment]
I see... Do you think an entry in https://github.com/astropy/astropy/blob/master/docs/known_issues.rst would be sufficient?

**Comment by saimn** [comment]
>  I had to deal with some interesting side effects in the process. Some modules of astroquery used logging.getLogger(__name__) which creates a child of AstropyLogger.

@jwoillez - Could you explain the issue ? `logging.getLogger(__name__)` is the recommended way to use logging, because it allows to have a hierarchy of loggers which makes it possible to have for example different levels for different modules. Astropy does not use this because - I think - of the need to set the logger class before calling `logging.getLogger`. So I don't see how `logging.getLogger(__name__)` would create a child of `AstropyLogger` ?

```
In [5]: logging.getLogger('astropy')
Out[5]: <AstropyLogger astropy (INFO)>

In [6]: logging.getLogger('astropy.nddata')
Out[6]: <Logger astropy.nddata (INFO)>
```

**Comment by ayshih** [comment]
@saimn: I don't know if it's precisely what @jwoillez is referring to, but what you just showed is itself a problem: a `Logger` instance (for `astropy.nddata`) is the child of an `AstropyLogger` instance (for `astropy`).  If you actually try to use that child logger, you'll find that it tries to pass the event up to the parent logger for further handling, which causes an error because the parent logger is expecting origin information that the child logger doesn't provide (because it's only a `Logger` instance instead of an `AstropyLogger` instance).
```python
>>> logging.getLogger('astropy.nddata').warn('test')
C:\Users\ayshih\anaconda3\Scripts\ipython:1: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
WARNING---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-d803c2bdc173> in <module>
----> 1 logging.getLogger('astropy.nddata').warn('test')

~\anaconda3\lib\logging\__init__.py in warn(self, msg, *args, **kwargs)
   1393         warnings.warn("The 'warn' method is deprecated, "
   1394             "use 'warning' instead", DeprecationWarning, 2)
-> 1395         self.warning(msg, *args, **kwargs)
   1396
   1397     def error(self, msg, *args, **kwargs):

~\anaconda3\lib\logging\__init__.py in warning(self, msg, *args, **kwargs)
   1388         """
   1389         if self.isEnabledFor(WARNING):
-> 1390             self._log(WARNING, msg, args, **kwargs)
   1391
   1392     def warn(self, msg, *args, **kwargs):

~\anaconda3\lib\logging\__init__.py in _log(self, level, msg, args, exc_info, extra, stack_info)
   1512         record = self.makeRecord(self.name, level, fn, lno, msg, args,
   1513                                  exc_info, func, extra, sinfo)
-> 1514         self.handle(record)
   1515
   1516     def handle(self, record):

~\anaconda3\lib\logging\__init__.py in handle(self, record)
   1522         """
   1523         if (not self.disabled) and self.filter(record):
-> 1524             self.callHandlers(record)
   1525
   1526     def addHandler(self, hdlr):

~\anaconda3\lib\logging\__init__.py in callHandlers(self, record)
   1584                 found = found + 1
   1585                 if record.levelno >= hdlr.level:
-> 1586                     hdlr.handle(record)
   1587             if not c.propagate:
   1588                 c = None    #break out

~\anaconda3\lib\logging\__init__.py in handle(self, record)
    892             self.acquire()
    893             try:
--> 894                 self.emit(record)
    895             finally:
    896                 self.release()

c:\users\ayshih\onedrive\code\astropy\astropy\logger.py in emit(self, record)
    549             else:
    550                 color_print(record.levelname, 'red', end='', file=stream)
--> 551         record.message = f"{record.msg} [{record.origin:s}]"
    552         print(": " + record.message, file=stream)
    553

AttributeError: 'LogRecord' object has no attribute 'origin'
```

**Comment by jwoillez** [comment]
This is exactly the issue I had (missing 'origin' attribute). I also saw one issue with the caplog fixture of pytest, but could not really understand what was going on.

**Comment by saimn** [comment]
Yes OK, it's a child in the sense of the loggers hierarchy, but it's indeed not an `AstropyLogger` instance, because by default `logging.getLogger` returns its own `Logger` object.
One way to deal with that would be to have a custom `getLogger` function, we could even recycle the existing `_init_log` one:
```
def getLogger(name='', init=False):
    orig_logger_cls = logging.getLoggerClass()
    logging.setLoggerClass(AstropyLogger)
    try:
        log = logging.getLogger(name)
        if init:
            log._set_defaults()
    finally:
        logging.setLoggerClass(orig_logger_cls)

    return log
```
