### ISSUE TITLE
MNT: Have a bot to auto-backport as PR

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11340]
When a PR against `master` is merged, it would be desirable to have a bot to automatically open up follow-up PR(s) to backport changes that are just merged against older release branch(es), depending on the relevant PR milestone.

If the automatic backport PR(s) encounter difficulties, such as failed CI or conflicts, the bot should then take follow-up actions (apply special labels or create comments) so that manual intervention can be done.

If possible, we should not "roll our own," but rather look at how other major projects are doing their backports, and see how we can reuse existing solutions. If all fails, @Cadair said he has a special hack that works "half the time"...

It is something we should aim for sooner than later, so I am going to add a milestone to this issue.

**Comment by saimn** [comment]
Some ideas:
- CPython uses https://github.com/python/miss-islington
- Matplotlib and IPython (maybe others as well ?) use https://github.com/MeeseeksBox/MeeseeksDev
- https://mergify.io/features/backports

MeeseeksBox seems nice and can be used just by adding the Github integration : 
```
@MeeseeksDev backport [to] {branch}

If issued from a PR which is merged, attempt to backport (cherry-pick the merge commit)
on an older branch and submit a PR with this backport (on said branch)
```

**Comment by pllim** [comment]
I am not sure about `MeeseeksDev`. It is owned by `MeeseeksBox` and it is basically one developer. CPython or Mergify (looks commercial) might be more sustainable in the long run.

**Comment by Cadair** [comment]
The miss-islington bot is hard coded to cpython by the looks of things, so it would need forking. Given the community already using meeseeks maybe it would be better to contribute there as needed?

**Comment by saimn** [comment]
Re-MeeseeksDev: the maintainer is the core developer of @ipython and @jupyter ;)
And it's also used by pandas, scikit-image and others: https://github.com/meeseeksmachine

**Comment by pllim** [comment]
Core dev or not, it is a single point of failure. Keeps me awake at night.

**Comment by pllim** [comment]
But I can be outvoted. If you say it is so widely used, if this dev leaves, perhaps pandas or something will adopt it. Wall Street people got money after all.

**Comment by pllim** [comment]
UPDATE: At the infrastructure/DevOps tag-up today, we have agreed to try it out with [MeeseeksDev](https://github.com/MeeseeksBox/MeeseeksDev) after this next 4.2.1 release.

**Comment by eteq** [comment]
:+1: to MeeseeksDev - I agree bus-factor of 1 is not great, but seems better than the alternatives :shrug:

**Comment by pllim** [comment]
@mwcraig suggested that maybe it is better if we write our own Action for this. It basically boils down to running some `git` commands and the ability to open PR automatically. I might look into this when I get a chance.

**Comment by pllim** [comment]
Let's forget about the bots for a second, what do **we want** in an automated backport workflow? Does this sound about right (based on what we currently do)?

1. When a PR is merged, check the milestone.
2. If milestone `X.Y.Z` matches an existing branch called `X.Y.x`, do something; otherwise stop here.
3. Grab PR number from event.
4. `git clone <repo URL>`
5. `git fetch origin X.Y.x`
6. `git checkout origin/X.Y.x -b backport-prNNNNN-X.Y.x`
7. `git cherry-pick -m 1 <merge commit SHA>
8. See if there is conflict:
  8.1. If there is conflict, stop here and comment on the PR.
  8.2. If there is no conflict, go to next step.
9. `git push origin backport-prNNNNN-X.Y.x` (I am not sure if bot can fork, so this will be a branch `upstream` here)
10. Open PR with the `backport-prNNNNN-X.Y.x` branch and tag some people to review (PR author + TBD)
11. Post a success comment on the PR.
12. If milestone `X.Y.Z` is LTS (e.g., `4.0.6`), repeat the above for "stable" `X.Y.x` branch too (e.g., `4.2.x`). If we can get the version comparison logic right, we won't need to hardcode anything here unless we change how we name branches, which is very unlikely.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/issues/11340#issuecomment-814306914

@Cadair proposed using labels instead of milestones for backport destinations. Example: sunpy/sunpy#5072 that uses [Cadair/backport](https://github.com/Cadair/backport/).

**Comment by bsipocz** [comment]
Re labels: it sounds more transparent, so we might need it for that. I don't think the milestone math to be an issue though.

**Comment by pllim** [comment]
> dummy user we had for the bot before

AFAIK, `astropy-bot` is an app and not an actual GitHub user account, so it never had the ability to open PR from fork (and we never had the need). For GitHub Action bot, you can have it be an author, but I don't think it has its own fork either, as it is tied to a repo. Is there some other account that I am not aware of?

**Comment by pllim** [comment]
Re: Labels -- @Cadair , so the special backport labels need to be applied *before* the PR is merged, or otherwise nothing happens?

Update 2021-05-04: I updated https://github.com/astropy/astropy/issues/11340#issuecomment-814306914 based on your feedback. Does it look good now?

**Comment by bsipocz** [comment]
@pllim - this one still looks to be a user: https://github.com/astropy-bot? we also has the app with the HAL 9000 avatar.

**Comment by saimn** [comment]
@MeeseeksDev Hello

**Comment by pllim** [comment]
@saimn , how do we proceed from here?

**Comment by nstarman** [comment]
@pllim, is this closed by the meeseeksdev bot?

**Comment by pllim** [comment]
Yes, thanks for the ping. 😸
