### ISSUE TITLE
question from SOFA Board on changes to headers (would affect ERFA)

### ISSUE THREAD

**Issue by scottransom** [astropy/astropy#11346]
Hi All,

Thought I would post this here as well as on the ERFA page in order to get some more eyes.  Feel free to respond on the ERFA page or to email me directly.

Basically the summary is that there are proposed changes to the SOFA headers that would make SOFA easier to use from C++.

Here is the link to the issue:
https://github.com/liberfa/erfa/issues/81

Thanks,

Scott Ransom <sransom@nrao.edu>

**Comment by mhvk** [comment]
Thanks again for checking. I'll close this since astropy itself certainly is not affected, because all bundling is done in `pyerfa` these days. As I wrote over at https://github.com/liberfa/erfa/issues/81, I think there are no issues for that either.
