### ISSUE TITLE
Regeression for Table dtype between 4.0.1 and 4.0.2

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#11347]
```
In [1]: import numpy as np

In [2]: from astropy.table import Table

In [3]: URL = "https://github.com/astroML/astroML-data/raw/master/datasets/sgSDSSimagingSample.fit.gz"

In [4]: data = Table.read(URL)
Downloading https://github.com/astroML/astroML-data/raw/master/datasets/sgSDSSimagingSample.fit.gz
|===========================================================================================================|  23M/ 23M (100.00%)         0s

In[5]: data.dtype
Out[5]: dtype([('ra', '>f8'), ('dec', '>f8'), ('run', '>i2'), ('rExtSFD', '>f8'), ('uRaw', '>f8'), ('gRaw', '>f8'), ('rRaw', '>f8'), ('iRaw', '>f8'), ('zRaw', '>f8'), ('uErr', '>f8'), ('gErr', '>f8'), ('rErr', '>f8'), ('iErr', '>f8'), ('zErr', '>f8'), ('uRawPSF', '>f8'), ('gRawPSF', '>f8'), ('rRawPSF', '>f8'), ('iRawPSF', '>f8'), ('zRawPSF', '>f8'), ('upsfErr', '>f8'), ('gpsfErr', '>f8'), ('rpsfErr', '>f8'), ('ipsfErr', '>f8'), ('zpsfErr', '>f8'), ('type', '>i2'), ('ISOLATED', '>i4')])
```

While with 4.0.2+, I get 
```
dtype([('ra', '>f8', (1,)), ('dec', '>f8', (1,)), ('run', '>i2', (1,)), ('rExtSFD', '>f8', (1,)), ('uRaw', '>f8', (1,)), ('gRaw', '>f8', (1,)), ('rRaw', '>f8', (1,)), ('iRaw', '>f8', (1,)), ('zRaw', '>f8', (1,)), ('uErr', '>f8', (1,)), ('gErr', '>f8', (1,)), ('rErr', '>f8', (1,)), ('iErr', '>f8', (1,)), ('zErr', '>f8', (1,)), ('uRawPSF', '>f8', (1,)), ('gRawPSF', '>f8', (1,)), ('rRawPSF', '>f8', (1,)), ('iRawPSF', '>f8', (1,)), ('zRawPSF', '>f8', (1,)), ('upsfErr', '>f8', (1,)), ('gpsfErr', '>f8', (1,)), ('rpsfErr', '>f8', (1,)), ('ipsfErr', '>f8', (1,)), ('zpsfErr', '>f8', (1,)), ('type', '>i2', (1,)), ('ISOLATED', '>i4', (1,))])
``` 

I assume this is a bug as a change like this should not happen in LTS.

This regression triggered multiple user bug reports downstream in astroML: https://github.com/astroML/astroML/issues/232

**Comment by taldcroft** [comment]
Could be wrong, but I'm going to guess it is #10768, Fix handling of 1-dimensional arrays with a single element in BinTableHDU.

**Comment by pllim** [comment]
What does this mean? Do we have to revert #10768 from 4.0.x branch?

**Comment by taldcroft** [comment]
That file does specify TDIM everywhere:
```
COMMENT No comment.                                                             
TFORM1  = '1D      '                                                            
TDIM1   = '(1)     '                                                            
```
My FITS-fu is not enough to know what the "correct" answer is, but first guess is that the code is now providing the answer that matches the spec.
![image](https://user-images.githubusercontent.com/348089/109032761-f9e90480-7693-11eb-96a1-aaa6638a0b09.png)

**Comment by pllim** [comment]
Let's loop in @maxnoe , @dhomeier , and @saimn then. Thanks!

**Comment by taldcroft** [comment]
Yes, see also #10765. Based on this it seems to me the bug fix is correct and makes sense. We always have this question when a "bug fix" is also an API change and some users may have been depending on the buggy behavior.

@bsipocz - can you fix that FITS file on the astroML site to remove the `TDIMn = '(1)'` headers?

**Comment by maxnoe** [comment]
Hi,

I can only say that we need this fix, I still think that it is the correct behavior according to the spec and based on the fact that if changed, there is no representation for the 1d size 1 arrays.

**Comment by bsipocz** [comment]
> @bsipocz - can you fix that FITS file on the astroML site to remove the TDIMn = '(1)' headers?

Yes, that will in fact work, and will be totally transparent for users. Thanks!

**Comment by saimn** [comment]
The fix indeed changes what is returned but that's because the file was not read correctly before, so I still think it deserves to be in LTS. If you can fix the file that seems a good solution.

**Comment by taldcroft** [comment]
I move to close this, seems resolved to me.

**Comment by dhomeier** [comment]
Agreed; without `TDIMn = '(1)'` it now returns scalar dtypes again, right?

**Comment by taldcroft** [comment]
I'm closing, and @bsipocz or others can re-open if desired.
