### ISSUE TITLE
DOC: Change remote name to upstream

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11383]
There were some discussions on astropy/astropy-project#151 regarding usage of `origin` vs `upstream` (vs `astropy`) as remote name in examples. As @taldcroft pointed out at https://github.com/astropy/astropy-project/issues/151#issuecomment-795924703 and https://github.com/astropy/astropy-project/issues/151#issuecomment-795927271 , `upstream` is the most widely used term, so perhaps it is less confusing if we update our dev docs to use `upstream`.

Example doc (one of many) that is affected: `docs/development/workflow/git_edit_workflow_examples.rst`

@embray , perhaps this can be part of your campaign to improve the dev docs?

**Comment by taldcroft** [comment]
Sorry in advance for going OT again... Is there an issue open for improving the dev docs? I have to say that I was just swept away with joy at seeing the [Contributing to NumPy](https://numpy.org/doc/stable/dev/) page. It is so simple, clean and beautiful looking.  In a matter of a half dozen screenfuls it gives an excellent overview of the whole process from start to finish. It does not get distracted by details down in the weeds, but does later provide an organized set of links to the details. We should take what they have and adapt it for astropy. I'm also envious of their theme and fonts.

**Comment by bsipocz** [comment]
Numpy is just clearly amazing, I love the new website, their highlights and tutorials, the visualisations etc. And they did it very efficiently, with a great documentation team, etc.

**Comment by bsipocz** [comment]
To keep staying OT, scikit-learn also has pretty good on boarding material, their new contributor sprints are very well organized (though I don't know their retention stats, last time I heard there are no miracles out there that generates multiple long term contributors)

**Comment by mhvk** [comment]
:+1: to adapting the numpy guide - they have indeed done a very good job with the new website (although quite a lot broke on the way - but I think our documentation base is quite solid so that's less likely to be a problem for us).

OT: I do use `upstream` though in contrast to the numpy guide I have renamed the main branch to `placeholder` on my fork (which also was a recommendation at some point - not sure it is actually worth it as long as one is not allowed to push to `upstream/main` - which I fear I may be).

**Comment by embray** [comment]
I have some plans for redoing a mass cleanup of the dev docs.  The Numpy one is clearly worth learning from, and adapting slightly to Astropy.

**Comment by embray** [comment]
And yes, I definitely prefer "upstream".
