### ISSUE TITLE
DOC: Stop linking to astropy-notebooks

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11381]
Seems like this only happens in `docs/io/ascii/fast_ascii_io.rst`, namely:

* https://nbviewer.jupyter.org/github/astropy/astropy-notebooks/blob/master/io/ascii/conversion_profile.ipynb
* https://nbviewer.jupyter.org/github/astropy/astropy-notebooks/blob/master/io/ascii/test_converter.ipynb
* https://nbviewer.jupyter.org/github/astropy/astropy-notebooks/blob/master/io/ascii/ascii_write_bench.ipynb
* https://nbviewer.jupyter.org/github/astropy/astropy-notebooks/blob/master/io/ascii/ascii_read_bench.ipynb

If we still need them, is there a reason why we cannot move them to the narrative docs here, so they can be doctest-ed?

xref https://github.com/astropy/astropy/pull/11379#discussion_r590714500

**Comment by eteq** [comment]
Might be good to ask @taldcroft about this, but it seems to me like we can just remove them...

**Comment by eteq** [comment]
Oh, although they *are* benchmarks with results? But :shrug: presumably they are not current anymore either...

**Comment by taldcroft** [comment]
We can just remove them at this point.
