### ISSUE TITLE
New unnecessary warning with updated wcslib

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#11385]
On the current development version of astropy, the simple script below is raising a new warning:
```python
WARNING: FITSFixedWarning: 'datfix' made the change 'Success'. [astropy.wcs.wcs]
```
This was probably introduced by https://github.com/astropy/astropy/pull/11260.

When code is running fine, I don't think any warnings should be raised to indicate this, and I think this is related to some downstream issues we are having with sunpy tests (https://github.com/sunpy/sunpy/issues/5073).

```python
from astropy.wcs import WCS
header = {
    'CRVAL1': 0,
    'CRVAL2': 0,
    'CRPIX1': 5,
    'CRPIX2': 5,
    'CDELT1': 10,
    'CDELT2': 9,
    'CD1_1': 0,
    'CD1_2': -9,
    'CD2_1': 10,
    'CD2_2': 0,
    'NAXIS1': 6,
    'NAXIS2': 6,
    'CUNIT1': 'arcsec',
    'CUNIT2': 'arcsec',
    'CTYPE1': 'HPLN-TAN',
    'CTYPE2': 'HPLT-TAN',
}
WCS(header)
```

**Comment by Cadair** [comment]
There is some discussion on this issue from this comment down: https://github.com/astropy/astropy/pull/11260#issuecomment-796804627

**Comment by pllim** [comment]
I think @dhomeier is going to contact `wcslib` dev about this.
