### ISSUE TITLE
MNT: Remove unused function from tokenizer.c

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11394]
Remove dead code here:

https://github.com/astropy/astropy/blob/382ae7b062f991cf512d9da6f82af583cc1fb174/astropy/io/ascii/src/tokenizer.c#L599-L608

As discussed in #11374 . Thanks to @kokke for catching it, c/c @taldcroft .

**Comment by maggiesam** [comment]
Hi, I just deleted the dead code, the pull request is done.
