### ISSUE TITLE
WCS generation parameter "colsel" does not seem to work

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#11412]
### Description
When reading the WCS from a fits table, "colsel" should allow me to select which columns are actually used to build the WCS. This matters if the table in question has multiple WCS attached to it (for different sets of columns). According to the docstring colsel is a sequence of int to restrict the numbers. However, for any combination of int, I get a `NoWcsKeywordsFoundError: No WCS keywords found in the given header`, even if I select ALL columns.

### Expected behavior

A WCS is build using only the column listed in colsel.

### Actual behavior

For any combination of int, I get a `NoWcsKeywordsFoundError: No WCS keywords found in the given header`, even if I select ALL columns. I tried both 0 indexing (as in Python) and 1 indexing (as the column numbers are in the fits header). The documentation does not say which of those is required.

### Steps to Reproduce

1. Download the fits file attached to [this comment](https://github.com/astropy/astropy/issues/7180#issuecomment-624978278). 
2. `mv evt2.fits.zip evt2.fits`  (The .zip ending is only there to fool GH into allowing me to upload it.)
3. try reading it with any colsel setting you like

```python
from astropy.wcs import WCS
from astropy.io import fits
WCS(fits.getheader('evt2.fits',1), keysel=['pixel', 'image'], colsel=list(np.arange(25, dtype=np.int8)))
```

### System Details

Darwin-19.6.0-x86_64-i386-64bit
Python 3.7.7 (default, Mar 23 2020, 17:31:31) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.19.2
astropy 4.2
Scipy 1.5.2
Matplotlib 3.3.2

CC: @nden @mcara

**Comment by pllim** [comment]
If this bug lies in the underlying `wcslib`, it will need to be fixed upstream... 💭

**Comment by mcara** [comment]
I am not an expert in pixel list WCS, unfortunately. But it does not look like the table has 25 columns, isn't it?

**Comment by hamogu** [comment]
@plim: I don't know if this is a wcslib problem or part of the astropy C code that calls into WCS.

@mcara: That is True. `colsel=[11,12]`, `colsel=[10, 11]`, `colsol=[1,2,3,4,5,6,7,8,9,10,11,12]` etc give the exact same error. It does not seem to matter what I set this parameter to. Anything that's not `None` does not work.

**Comment by mcara** [comment]
Well, `colsel=list(range(1, n))` with `n=15,16,18` "works" (no crash) 😄 , though I am not sure the result is what one would expect. Looking at `astropy`'s code, I doubt this is an issue with `astropy`. My suspicion is that this is either a bug in WCSLIB or the header is not created correctly [which I can't evaluate without learning about pixel list WCS conventions].

**Comment by mcara** [comment]
CC: @perrygreenfield

**Comment by hamogu** [comment]
I'm pretty sure the header is correct - it's just a table (and io.fits reads it just fine as a table). I also looked a bit (but I can't claim to be an expert) into the pixel list wcs and everything I read matches with this header.

**Comment by hamogu** [comment]
Mmm. 15,16, and 18 fail for me like all the other numbers on astropy 4.2:
```
---------------------------------------------------------------------------
NoWcsKeywordsFoundError                   Traceback (most recent call last)
<ipython-input-6-c47878f4b89e> in <module>
----> 1 wcs.WCS(fits.getheader('evt2.fits',1), keysel=['pixel', 'image'], colsel=list(range(1, 18)))

~/anaconda3/envs/ciao/lib/python3.7/site-packages/astropy/wcs/wcs.py in __init__(self, header, fobj, key, minerr, relax, naxis, keysel, colsel, fix, translate_units, _do_set)
    482                 wcsprm = _wcs.Wcsprm(header=header_bytes, key=key,
    483                                      relax=relax, keysel=keysel_flags,
--> 484                                      colsel=colsel, hdulist=fobj)
    485             except _wcs.NoWcsKeywordsFoundError:
    486                 # The header may have SIP or distortions, but no core

NoWcsKeywordsFoundError: No WCS keywords found in the given header
```

**Comment by pllim** [comment]
@hamogu , did you try with 4.3.dev?

**Comment by hamogu** [comment]
I see that wcslib has been updated since, so I'm now trying the current master.

**Comment by mcara** [comment]
Ah, my bad: `16, 17, 19`.

**Comment by mcara** [comment]
Still, this makes no sense (to me). It is just an observation.

**Comment by mcara** [comment]
And I am using `4.2`.

**Comment by pllim** [comment]
Make sure you are not using some system `wcslib` under the hood?

**Comment by hamogu** [comment]
How would I find out? I've tried both a conda installation and `pip install .` form source with identical results.

**Comment by mcara** [comment]
I do not think that matters too much. I know I am using bundles WCSLIB and I get the same results as reported here. Can we learn about the file itself? Who and how created the file? Was it modified (it's WCS is relevant here)?

**Comment by hamogu** [comment]
It's an event file as they are commonly used in X-ray observations. This is a Chandra observation, straight from the archive. I've tried different files and the problem occurs for all Chandra event files that I tried (from the archive or processed locally with CIAO, the Chandra software).

**Comment by mcara** [comment]
Then I wonder how could such a bug (assuming it is a bug) in `colsel` go unnoticed for so long. It must be a feature no one is using.

**Comment by mcara** [comment]
I will contact developer of WCSLIB to report this issue.

**Comment by hamogu** [comment]
@mcara: Thanks! Feel free to put me in CC (hgunther@mit.edu) if you email. I'm happy to help, but I don't understand the C code in astropy that connects between WCS and Python, so it's hard for me to see exactly what's happening on our side vs. on the wcslib side.
