### ISSUE TITLE
On-sky rotations of coordinates with NaN distance are NaN

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11423]
### Description

Coordinate transformations that don't require the distance will return incorrect results if the distance value is set to NaN. This is different than if the value is not specified, presumably because a UnitSpherical representation is being used, while it is not for the NaN case.

### Expected behavior

Coordinate transformations that don't require the distance are not affected by the value of the distance. This is not a problem for most values, but NaN is clearly a special case because 2 * nan / nan = nan, not 2.

**ps. I just noticed this is also true for ``np.inf``.

### Steps to Reproduce

```python
print(coord.ICRS(ra=1*u.deg, dec=2*u.deg).transform_to(coord.Galactic()))  # works
print(coord.ICRS(ra=1*u.deg, dec=2*u.deg, distance=np.NaN*u.pc).transform_to(coord.Galactic()))  # does not
```

### Thoughts on a solution

Maybe for these classes of transformations any NaNs in the distance array could changed to a special value, then be changed back to NaN after the transformation. We kind of need a NaN for which 2 * nan / nan = 2.

Something super hacky that works for transforming from ICRS to Galactic is:

```
c = coord.SkyCoord(ra=[0, 1]*u.deg, dec=[2, 3] * u.deg, distance=[4, np.nan]*u.pc)
distance = c.distance
c.frame._data = c.frame.data.represent_as(coord.UnitSphericalRepresentation)

c = c.galactic
_data = c.frame.data.represent_as(coord.SphericalRepresentation)
_data._distance = distance
c.frame._data = _data
print(c)
```

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ]
Numpy 1.18.4
astropy 4.3.dev678+gc2ae79d5a.d20210324
Scipy 1.4.1
Matplotlib 3.2.1

**Comment by adrn** [comment]
Hi @nstarman! Thanks for bringing this up. As you may already know from looking at the internals, this is because frame data  gets turned into cartesian 3-vectors, so that rotation matrices can be applied simply to the coordinate data to do the transformation. NaN's are greedy, so anything that touches the NaN distance value (i.e. all 3 cartesian components) get turned into NaN values as well, which then get re-represented to spherical and...hence the NaN's appearing in the angle components of the output. 

It's hard to think of a generic solution to this that doesn't require a lot of special casing: It's tempting to want to do something like "if transformation is a rotation, if distance is not finite, put the source on the unit sphere rather than using distance information", but maybe the example transform here is just one in a chain and the next transform requires a distance (e.g., Galactocentric). @eteq @mhvk @StuartLittlefair @astrojuanlu ?

**Comment by mhvk** [comment]
Working around this may be possible, but is there an actual use case? I could see having a catalogue of objects in which some have distances and others have not. In that case, one could have something more like the marker @nstarman suggested, something like "arbitrary distance".

**Comment by nstarman** [comment]
@mhvk. That's my use case exactly. I had a table of coordinates from 2 different catalogs, outer vstacked them, and tried to make a SkyOffsetFrame with a rotation. I like the concept of "arbitrary distance". I recall but can't find a numpy proposal to have two separate types of NaN, one that indicated a lack of information, the other problematic values. 

@adrn Thanks for the explanation. I've been looking at the transforms code. If we want to go the special-case route then I don't think we need to drop the distance information, just restore it after the transformation. This doesn't apply to AffineTransform, but for Static and DynamicMatrix, it should work.

**Comment by mhvk** [comment]
@nstarman - I can see a case for trying to ensure that if it is a pure rotation matrix, it doesn't touch the distances. This could either be in the general transformation machinery, but another option might be to make `.transform()` a method that doesn't exist only on `CartesianRepresentation`. Instead, by default it would go via cartesian, but is overridden for spherical/unitspherical and do not use distance (if the matrix is a rotation matrix - might need some keyword argument or so to indicate that).

**Comment by nstarman** [comment]
> This could either be in the general transformation machinery

Looking in the code, two spots in the transformation machinery stand out to me as places to a) check for a pure rotation matrix and avoid routing through cartesian coordinates and b) expand the special casing from UnitSpherical to just Spherical. I haven't started experimenting with fixes. I need to first sit down and better understand the implementation of the transformation machinery.

https://github.com/astropy/astropy/blob/3b751a04b2970c18fbfbceaa31f19855e5034f95/astropy/coordinates/transformations.py#L1105-L1110

https://github.com/astropy/astropy/blob/3b751a04b2970c18fbfbceaa31f19855e5034f95/astropy/coordinates/transformations.py#L1136-L1139

> another option might be to make .transform() a method that doesn't exist only on CartesianRepresentation

I like this idea as well. My only concern is that custom representations, such as a [log-polar representation](https://en.wikipedia.org/wiki/Log-polar_coordinates), would not immediately benefit.

**Comment by mhvk** [comment]
For custom representations, I don't see how one can very easily benefit - the transformation machinery would also need to know whether the representation is a form of spherical. And if it is really similar, one could inherit from `SphericalRepresentation` rather than `RepresentationBase` and just have the `.tranform()` method. In any case, probably best first to think how most easily to solve the common case of this already quite uncommon example!

**Comment by nstarman** [comment]
I think I figured out a recipe for making the spherical ``.transform`` method.

1.) if the matrix is given in a spherical basis this is very easy. Rotation matrices don't have any off-diagonal elements on the 3rd column. To deal with nan, we just need to do the (2x2) angular matrix and the  distance row separately.

```
        _p = np.stack([self.lon.value, self.lat.value, self.distance.value],
              axis=-1)
        newp = np.empty_like(_p)
        if matrix.shape == (2, 2):
            newp[:, :-1] = np.matmul(matrix, _p[:, :-1].T).T
            newp[:, -1] = _p[:, -1]
        # is it a rotation matrix?
        elif matrix.shape == (3,3) and np.allclose(matrix[:-1, -1], 0):
            # deal with NaN by multiplying the 2x2 first and then the last row
            newp[:, :-1] = np.matmul(matrix[:-1,:-1], _p[:, :-1].T).T
            newp[:, -1] = np.matmul(matrix[-1], _p.T).T
        else:
            newp = erfa_ufunc.rxp(matrix, _p)
        return self.__class__(
            **{k: v * u for v, (k, u) in zip(newp.T, self._units.items())},
            copy=False, differentials=None)
```

2. For a matrix in a Cartesian basis it's a bit more tricky because the change-of-basis matrix from spherical to cartesian and back will have NaN. To resolve this I think I came up with a clever hack: recast the problem into complex numbers with Nan -> 0+1j. Now any use of NaN can be tracked non-destructively by the imaginary component.

**Comment by mhvk** [comment]
The general idea makes sense, but unfortunately the transformation routines all use matrices in a cartesian basis. That said, in those places, we *know* whether the matrix is a rotation matrix or not, so one can simply set an appropriate keyword argument.
