### ISSUE TITLE
Add RadialRepresentation to SphericalRepresentation

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11445]
### Description

When two ``SphericalRepresentation`` are added, the distance components are correctly summed. A SphericalRepresentation + RadialRepresentation could be equivalent to summing two ``SphericalRepresentation``, with the same lon, lat.

Ex:
```
>>> coord.SphericalRepresentation(1*u.rad, 0.2*u.rad, 3) + coord.RadialRepresentation(5)
<SphericalRepresentation (lon, lat, distance) in (rad, rad, )
    (1., 0.2, 8.)>
```

### Additional context

This would be useful for generalizing #11444 to allow for offsets in the transformation machinery to be a RadialRepresentation.

**Comment by mhvk** [comment]
I must admit I do not much like this idea!  So far, the algebra is very explicitly set up such that one always gets the same answer as one would get from converting both arguments to Cartesian, doing the operation, and then converting back. I think that is unambiguous, treating the representations consistently as 3d vectors. 

I don't see any advantage to be able to add anything to all the distances!

**Comment by nstarman** [comment]
On review, I'm inclined to agree.

**Comment by mhvk** [comment]
OK, sounds good. Will close then.
