### ISSUE TITLE
Allow setting astropy cache directory via an environment variable

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#11448]
### Description

In some conditions (e.g. certain HPC clusters or special purpose system users) the home directory of the current user is not writable or even existing.

In that case, astropy raises a couple of warnings due to the cache directory not being writable.

Under such conditions, it would be great, if the location of the cache would be configurable via environment variables, e.g. `ASTROPY_CACHE_DIR=/path/to/my/custom/cache`.

**Comment by saimn** [comment]
This is already planned in #10738

**Comment by maxnoe** [comment]
Awesome

**Comment by saimn** [comment]
Closing this one then.
