### ISSUE TITLE
Seasonal Variations in Altitude Missing

### ISSUE THREAD

**Issue by petschge** [astropy/astropy#11451]
### Description
I am converting the coordinates of a source to Alt-Az and see the expected variations in altitude over the course of a day that are caused by the rotation of Earth. But when I do the conversion over the range of a whole year I would expect to see additional variations due to the tilt of the Earth axis, but I don't.

### Expected behavior
See daily and annual variations in altitude above the horizon for a given source.

### Actual behavior
Only daily variations are seen

### Steps to Reproduce
```python
#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import platform
import astropy
import astropy.units as u
from astropy.coordinates import AltAz, EarthLocation, SkyCoord
from astropy.time import Time

target = SkyCoord(ra=128.83606354*u.deg, dec=-45.17643181*u.deg, frame="icrs")
print(target)

# ALMA
observer = EarthLocation(lat=-23.028999999999996*u.deg, lon=-67.755*u.deg, height=5000.000000000003*u.m)
print(observer)

day  = Time("2021-04-01 00:00") + np.linspace(0, 1, 4*24)*u.day
year = Time("2021-04-01 00:00") + np.linspace(0, 1, 4*24*365)*u.year

altaz = target.transform_to(AltAz(obstime=day, location=observer))
plt.plot(altaz.alt/u.deg)
plt.xlabel("One day")
plt.ylabel("Altitude (deg)")
plt.show()
plt.savefig("astropy_day.png")
plt.close()

altaz = target.transform_to(AltAz(obstime=year, location=observer))
plt.plot(altaz.alt/u.deg)
plt.xlabel("One Year")
plt.ylabel("Altitude (deg)")
plt.savefig("astropy_year.png")
plt.show()
```
![astropy_day](https://user-images.githubusercontent.com/5259880/113053015-1087ed00-9165-11eb-86cb-afee9bcb4a59.png)

![astropy_year](https://user-images.githubusercontent.com/5259880/113053019-11b91a00-9165-11eb-9109-46ace68fb4e7.png)

### System Details
python: 3.7.3
numpy: 1.20.2
astropy: 4.3.dev690+g7811614f8

**Comment by petschge** [comment]
I guess the coordinate transformation itself is correct, but does not include the fact that the source might have the maximum altitude for that 24-hour period during daytime. So I need to filter that separately.

**Comment by dhomeier** [comment]
@petschge when zooming in to the "year" plot at sufficient resolution, I am seeing just the repeating diurnal variations as I would in fact expect them. Since your time increment is not an exact (integer) fraction of a sidereal day, the maxima and minima show some slight fluctuation depending on how close a datapoint you get to the meridian transit every day, but what real _annual_ variations would you expect to see there?
I must admit I don't know how or to what level the variations of the Earth axis orientation from nutation and precession are included in `coordinates`, but they should be far too long term to be visible over just one year, at least in this kind of plot.

**Comment by petschge** [comment]
> what real _annual_ variations would you expect to see there?

As I figured out by now: none. I will of course get the same altitude at meridian transit every day. I was confused because the maximum altitude **during nighttime** will change during the year, depending when in the day the meridian transit happens.

**Comment by dhomeier** [comment]
> As I figured out by now: none. I will of course get the same altitude at meridian transit every day. I was confused because the maximum altitude **during nighttime** will change during the year, depending when in the day the meridian transit happens.

Ah yes, you should be able to see those if you mark the times of dusk and dawn in your plot or somehow use them as a mask.
