### ISSUE TITLE
Misleading behavior in SkyCoord.is_transformable_to()

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#11472]
Elsewhere in SkyCoord, we allow string aliases of the coordinate frames, for example:
```python
>>> import astropy.coordinates as coord
>>> import astropy.units as u
>>> c = coord.SkyCoord(90*u.deg, -11*u.deg)
>>> c.transform_to('galactic')
<SkyCoord (Galactic): (l, b) in deg
    (217.12716293, -16.34634219)>
```
However, in `SkyCoord.is_transformable_to()`, strings fail the test silently, even though the input is technically invalid. 
```python
>>> c.is_transformable_to(coord.Galactic())
True
>>> c.is_transformable_to('galactic')
False
```

We should either add support for turning a string frame alias to a frame class, or raise an exception.

**Comment by srirajshukla** [comment]
We can use `_get_frame_class` to coerce string into an instance?

**Comment by nstarman** [comment]
I use that in some of my personal code. It would be great if it were publicly scoped.

**Comment by nstarman** [comment]
Dropping this in here to remind myself to open a PR when this and #11118 are merged

<img width="1383" alt="Screen Shot 2021-04-13 at 01 18 08" src="https://user-images.githubusercontent.com/8949649/114500492-1d412200-9bf6-11eb-82e3-2c003b3c3b6f.png">
