### ISSUE TITLE
import not working on M1 Mac

### ISSUE THREAD

**Issue by ChopsKingsland** [astropy/astropy#11474]
I am trying to use astroquery on an M1 Mac, and it just doesn't work. Firstly, to install astroquery, I had to open terminal with Rosetta (basically to emulate an Intel Mac, otherwise it wouldn't work). And now, my code won't run... My code is

```
from astroquery.jplhorizons import Horizons

planets = [199, 299, 301, 499, 599, 699, 799, 899, 999]
planetNames = ["Mercury", "Venus", "Moon", "Mars",
               "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]


def getPlanetInfo(planet):
    obj = Horizons(id=planet, location='000', epochs=None, id_type='majorbody')
    eph = obj.ephemerides()
    return eph


eph = getPlanetInfo(planets[planetIndex])
percentageArcAZ = (eph['AZ'][0])/360  # find Azimuth
percentageArcEL = (eph['EL'][0])/360  # find Elevation
stepsNeededAZ = int(percentageArcAZ*512)  # 512 steps is 360degrees
stepsNeededEL = int(percentageArcEL*512)  # 512 steps is 360degrees

```

and the error I'm getting is

```
Traceback (most recent call last):
  File "/Users/*****/Documents/Python/*****/main.py", line 1, in <module>
    from astroquery.jplhorizons import Horizons
  File "/opt/homebrew/lib/python3.9/site-packages/astroquery/__init__.py", line 12, in <module>
    from ._astropy_init import *
  File "/opt/homebrew/lib/python3.9/site-packages/astroquery/_astropy_init.py", line 29, in <module>
    from astropy.config.configuration import (
  File "/opt/homebrew/lib/python3.9/site-packages/astropy/__init__.py", line 248, in <module>
    _initialize_astropy()
  File "/opt/homebrew/lib/python3.9/site-packages/astropy/__init__.py", line 200, in _initialize_astropy
    from .utils import _compiler
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/astropy/utils/_compiler.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /opt/homebrew/lib/python3.9/site-packages/astropy/utils/_compiler.cpython-39-darwin.so: mach-o, but wrong architecture
        /opt/homebrew/lib/python3.9/site-packages/astropy/utils/_compiler.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Comment by pllim** [comment]
I vaguely remember there is some catch trying to use `astropy` on Apple's M1. Maybe @tepickering or @kelle have insights here.

**Comment by pllim** [comment]
Might also help if you tell us how exactly you got `astropy` installed on that system.

**Comment by dhomeier** [comment]
> Might also help if you tell us how exactly you got `astropy` installed on that system.

This is a Brew installation, but are you running the entire environment and Python interpreter inside Rosetta, or should the packages already have been compiled on M1?

**Comment by tepickering** [comment]
looks like the libraries being linked to are not compiled to be universal. the error doesn't say what they are so they could be either M1 or x86-64. need to know the context from which the code was run run (normal shell or from rosetta). also, the homebrew package info should state how they're built.

**Comment by MridulS** [comment]
I think we can close this issue, M series machines have been out for a while and there doesn't seem to be any issue with going through conda/pip to install astropy.

**Comment by neutrinoceros** [comment]
nice catch. For what it's worth I also don't have any issue running on M2.

**Comment by dhomeier** [comment]
Brew/Fink installations are also working without having to resort to Rosetta.
