### ISSUE TITLE
Installation docs page shouldn't start with requirements

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#11507]
@embray and I were just reviewing some parts of the documentation for intimidating lists or walls of text, and we noticed that the first thing shown on the "installation" page are requirements and dependencies for installing astropy (the vast majority of which are *optional* dependencies!). We would guess that most people landing on this page just want to be reassured that they can safely `pip install astropy` or `conda install astropy`. Perhaps we want to change the order of the sections on this page? Right now it is: Requirements, Installing astropy, Building from source. A simple tweak could be to make it: Installing astropy, Requirements, Building from source instead?

**Comment by pllim** [comment]
Sounds reasonable! 👍
