### ISSUE TITLE
Warnings logging doesn't log warnings

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#11500]
### Description

The Astropy logging mechanism provides the `enable_warnings_logging()` function, which is claimed to enable logging of `warnings.warn()` messages. This does not appear to work.

### Expected behavior

Warnings signaled by `warnings.warn` should be recorded in the log.

### Actual behavior

Such warnings do not appear.

### Steps to Reproduce

```python
import warnings
from astropy import log
import astropy.logger
import logging

try:
    log.enable_warnings_logging()
except astropy.logger.LoggingError:
    pass

with log.log_to_file("test.log"):
    log.warning("logger warning")
    warnings.warn("warnings warning")
```

The file `test.log` should contain both "logger warning" and "warnings warning" but it only contains "logger warning".

(The exception handling is because the only way to ensure the astropy warnings logging mechanism is turned on is to call the function and catch the exception if it's already turned on; it is in my completely default setup.)

### System Details

```
>>> import platform; print(platform.platform())
Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-debian-buster-sid
>>> import sys; print("Python", sys.version)
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50)
[GCC 7.5.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.18.5
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.0
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.4.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.0.3
```

**Comment by aarchiba** [comment]
The documentation claims: "Once called, any subsequent calls to warnings.warn() are redirected to this logger and emitted with level WARN." https://docs.astropy.org/en/stable/api/astropy.logger.AstropyLogger.html#astropy.logger.AstropyLogger.enable_warnings_logging

The test suite, by contrast, requires that warnings logging only capture warnings that are a subclass of `AstropyUserWarning`: https://github.com/astropy/astropy/blob/main/astropy/tests/test_logger.py#L94

For our application it would be vastly preferable to capture all warnings.

**Comment by aarchiba** [comment]
Exception logging appears to log only uncaught exceptions, which the documentation does say, but it provides no indication for how or if it is possible for a long-running process to report these if it is actually catching the exception. (For example, if the exception arises in an ipython kernel being run under nbconvert in another python interpreter.)

**Comment by pllim** [comment]
I would need @embray 's expertise on this.

**Comment by saimn** [comment]
> For our application it would be vastly preferable to capture all warnings.

I'm not sure I agree with this (but I'm certainly biased: #11390). The astropy logger (the instance, `astropy.log`) should care only about what is logged from astropy and should not be used by other packages. The astropy logger class can be reused to create a custom logger with the same features, but IMO that's a bad idea (it adds custom attributes which makes it incompatible with a standard use).
If you need a more fancy logging library for your application, there are better alternatives (e.g. https://github.com/Delgan/loguru), and it's not something astropy should provide.

**Comment by aarchiba** [comment]
I know of at least two projects that use Astropy and do all their logging through the Astropy logger, so removing that functionality would be inconvenient.

**Comment by pllim** [comment]
I agree with @saimn here. Perhaps the more correct path forward is to ask those two projects to use a better logger.

**Comment by aarchiba** [comment]
I think if you're going to make that change you'd better make sure the documentation explains that the log system is only for astropy internal use, so that others don't continue using it.

**Comment by pllim** [comment]
Re: Doc -- Very good point! It is public API after all.

**Comment by pllim** [comment]
@aarchiba ,  #11562 is merged to clarify the logger usage. Can we close this? Thanks for bringing this to our attention!

**Comment by pllim** [comment]
Hi humans :wave: - this issue was labeled as **Close?** approximately 4 months ago. If you think this issue should not be closed, a maintainer should remove the **Close?** label - otherwise, I will close this issue in 7 days.

*If you believe I commented on this issue incorrectly, please report this [here](https://github.com/pllim/action-astropy-stalebot/issues)*

**Comment by pllim** [comment]
Ops... Bot comment is accurate but I used the wrong API key. 😅
