### ISSUE TITLE
Azure Pipelines: HTTPError 402 Payment Required for nightly wheel uploads

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11509]
Example log: https://dev.azure.com/astropy-project/astropy/_build/results?buildId=1195&view=logs&j=0ccccc7a-9630-5914-467b-15a9c61f0287&t=be17ddbd-7b38-5c00-8085-5c42f16d9fa6

```
HTTPError: 402 Payment Required from https://pkgs.dev.azure.com/astropy-project/astropy/_packaging/nightly/pypi/upload
```

**Comment by Cadair** [comment]
I thought I fixed this, but turns out that there is a recycle bin where packages go to die, so I have no cleared that out as well. Should hopefully be fixed by the next nightly.

**Comment by astrofrog** [comment]
Is this something that will be done automatically in future?

**Comment by Cadair** [comment]
Yeah I also enabled pruning, however it keeps them in the recycle bin automatically for 30 days, which I think might be enough to kill our limit. There seems to be no available options to disable or reduce this time. So we might have to come up with a script which uses the API to purge the recycle bin if it breaks again.

**Comment by pllim** [comment]
Or... you could switch to Actions...

**Comment by Cadair** [comment]
Yeah GitHub packages doesn't support Python yet, so that's a no: https://docs.github.com/en/packages/learn-github-packages/about-github-packages#supported-clients-and-formats

**Comment by pllim** [comment]
> So we might have to come up with a script

So, should I keep this open until this script is written or this issue is resolved?

**Comment by Cadair** [comment]
It could take sometime for this to crop up again (if it ever does) so let's open a new issue then.

**Comment by Cadair** [comment]
They did not. I didn't know about it until you told me.
