### ISSUE TITLE
DOC: remove references to RandomState

### ISSUE THREAD

**Issue by tupui** [astropy/astropy#11519]
### Description

I propose here to remove from the documentation any reference to `RandomState` and wrong (not best practice) usage of random number generators.

We went through this in SciPy. More on the PR https://github.com/scipy/scipy/pull/13778

Let me know if you would accept this contribution and I would propose to do it 😃 

### Additional context

Since NumPy 1.17 (and as far as I understand, the supported minimal version here is 1.17), the [canonical way](https://numpy.org/doc/stable/reference/random/index.html) to create random numbers is:

```python
import numpy as np
from numpy.random import default_rng
rng = default_rng()
```
And If a seed is to be used. User should not use a common value such as 0 or 123456. This is to prevent bias (everyone is using the same values) and ensure sufficient entropy for the generator. More [details](https://numpy.org/doc/stable/reference/random/bit_generators/index.html#seeding-and-entropy). The good practice (from NumPy's doc) is to generate a seed like this:

```python
from numpy.random import SeedSequence
print(SeedSequence().entropy)
```

Then you can use the value like
```python
rng = default_rng(my_seed_generated_and_not_common_value)
```

**Comment by pllim** [comment]
Hello. We already have #10644 to address this, but unfortunately, it is still awaiting approval and merge.

**Comment by tupui** [comment]
Indeed sorry I don't know how I missed it when searching for it!

**Comment by pllim** [comment]
No worries. I am re-opening this because it is technically not fixed yet. The PR will auto-close this issue when it is merged. Thanks for pinging us!
