### ISSUE TITLE
TST: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11524]
Example log: https://github.com/astropy/astropy/runs/2321021984?check_suite_focus=true

Snippet (one of many): 

```
___________ ERROR collecting astropy/modeling/tests/data/__init__.py ___________
tests/lib/python3.7/site-packages/pytest_doctestplus/plugin.py:206: in collect
    module = self.fspath.pyimport()
tests/lib/python3.7/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
astropy/modeling/__init__.py:10: in <module>
    from . import fitting
astropy/modeling/fitting.py:1764: in <module>
    populate_entry_points(entry_points().get('astropy.modeling', []))
tests/lib/python3.7/site-packages/importlib_metadata/__init__.py:312: in get
    flake8_bypass(self._warn)()
E   DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
```

**Comment by saimn** [comment]
Hmm, so Python 3.10's `entry_points()` will return an `EntryPoints` object and emit the same warning (https://docs.python.org/3.10/library/importlib.metadata.html#entry-points), and `importlib_metadata` is doing things in advance so their last release is already emitting the warning (https://github.com/python/importlib_metadata/issues/298).
I think we can ignore the warning for now, but when Python 3.10 is out we will need to find a way to adapt the code.

**Comment by pllim** [comment]
According to [PEP 619](https://www.python.org/dev/peps/pep-0619/), 3.10.0 final is expected on Monday, 2021-10-04. It is not that far off. Should we address this properly sooner than later?
