### ISSUE TITLE
Avoid very strange SI unit decompositions

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#11532]
Taken from #8398, to just focus on the actual problem:
```
from astropy import units as u

(u.erg/u.s/u.cm**2/u.Angstrom).si
# Unit("1e+07 Pa / s")
```
This decomposition is very unfortunate and it would be nice if it could be more sensible, perhaps by using physical type or so.

EDIT: A specific suggestion might that if a given unit has an associated physical type, then the unit of that physical type is used (which I think is always SI).
EDIT2: the above suggestion doesn't work easily, since the unit system has no direct way to know which one it is:
```
(u.erg/u.s/u.cm**2/u.Angstrom).physical_type
PhysicalType({'power density', 'spectral flux density wav'})
```
Though even `W/m3` would be nicer than `Pa/s`...

**Comment by adrn** [comment]
Thinking about this again in the context of the new `UnitSystem` class PR and the degeneracies you raise about asking to return a unit in a given unit system. I think there are three things we want to support, but I would advocate for having them all go through the `Unit.to_system()` and `Quantity.to_system()` methods (and make the `.si`, `.cgs`, etc. call a specific argument setting of `.to_system()`, if that's not what is already done). I think those cases are (all argument names just for illustration and need to think of better options):

Given a quantity (or unit),
```python
>>> q = 1 * u.mm**2 / u.kyr**2 * u.Mearth
```
I want to convert this quantity/unit...

1.  to the preferred representation in a unit system
    ```python
    >>> q.to_system(u.cgs)
    Unit("59968.6 erg")
    ```

2. to a composition of base units only
    ```python
    >>> q.to_system(u.cgs, bases_only=True)
    Unit("59968.6 cm2 g / s2")
    ```

3. to all sensible combinations of units in the unit system (current `Unit.to_system()` behavior)
    ```python
    >>> q.to_system(u.cgs, bases_only=False, list_all=True)
    [Unit("59968.6 erg")]
    ```

Does that seem sensible @mhvk?

**Comment by mhvk** [comment]
@adrn - `unit.cgs` indeed goes through `to_system()` (and just returns the first entry of the list, which I think is meant to be the "preferred one" as the list is sorted by number of units used).

I agree with your three options, though am less sure about the argument names...
