### ISSUE TITLE
Add support for the DE440 JPL ephemeris

### ISSUE THREAD

**Issue by ayshih** [astropy/astropy#11544]
There is a new JPL ephemeris (DE440, [Park et al. 2021](https://iopscience.iop.org/article/10.3847/1538-3881/abd414)), and JPL HORIZONS has been updated to use it as of today.  `astropy.coordinates.solar_system_ephemeris` should be updated to enable access to DE440 ([114 MB](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de440.bsp)) and DE440s ([31 MB](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de440s.bsp)), in addition to the already-supported DE430 and DE432s.

**Comment by pllim** [comment]
Is this critical for `astropy` 4.3?

**Comment by eteq** [comment]
Not critical, but is "easy" (hopefully not famous last words...), so milestoning 4.3

**Comment by mhvk** [comment]
See #11601 - main question, should this be our new default? (let's discuss over in the PR)
