### ISSUE TITLE
CDS tables can have a ORDER specifier, that is not handled right onow

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#11546]
### Description

In the current main branch, the regex takes care of settings for the NULL value, and #11531 adds functionality for the possibility that a RANGE values is also given. Looking at the spec http://vizier.u-strasbg.fr/doc/catstd-3.4.htx
There is a third possibility: After the NULL, an ORDER specification can also be given.

It's very easy to modify the regex to take care of that, but for testing it would be really helpful to find a real CDS table that has the RANGE actually set.

**Comment by hamogu** [comment]
There is an "official" CDS package at https://github.com/cds-astro/cds.pyreadme/ and we can look how they parse that.

**Comment by bhavyakh** [comment]
I looked at some CDS files from vizier, and I found [this ReadMe file](https://cdsarc.unistra.fr/ftp/I/5/ReadMe) with 'CZC' column having an ORDER specifier. Is it enough for a test case?

**Comment by hamogu** [comment]
Yes! Great, how did you find it? I means, we could make up something, too, if we wanted to test e.g. `+=`, but it's always good to have a "real" case to make sure we did not male a mistake in making it up!

**Comment by bhavyakh** [comment]
I was just randomly searching for files, and it was the second file I found. If it's necessary I can make a script that looks for ReadMe files with '-=' and '+=', I'm sure it won't take much time.

**Comment by hamogu** [comment]
No, I think this is good enough. We don't have to re-write CDS!

**Comment by bhavyakh** [comment]
While looking for CDS files and editing the regex, I came across another possible issue;

In some columns of many CDS files, vis-a-vis.
WDS and Kmag columns of [https://cdsarc.unistra.fr/ftp/I/270/ReadMe](https://cdsarc.unistra.fr/ftp/I/270/ReadMe) 
and in multiple columns of [https://cdsarc.unistra.fr/ftp/I/297/ReadMe](https://cdsarc.unistra.fr/ftp/I/297/ReadMe) 
there is no whitespace for the null value. Therefore, regex treats the adjacent word in the `nullval` capture group, and there's removal of a word from 'descriptiontext'. 

I tested this with the column:
 `117-122  F6.3  mag      Bmag     ?Blue magnitude`
```
>>> r.header.cols[6].description
'magnitude'
>>> r.header.cols[6].null
'Blue'
```
It is relatively easier to solve, should I add an issue about it?

**Comment by hamogu** [comment]
It sounds like you are planning to work on it. If so, you can just fix that at the same time and describe everything you fixed in the towncryer file with the change. If not, please open an issue so that we don't forget!
Thanks!
