### ISSUE TITLE
Print unit in NDData

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11541]
### Description

While discussing #11210 with @mhvk, I noticed that printing NDData with a set unit does not show the unit. While not a bug, my expectation is that the unit would be shown. I don't see any Issues or PRs on this... so maybe it's an intentional design decision?

### Additional context
E.g

```python
>>> from astropy.nddata import NDData; print(NDData([1, 2, 3], unit=u.km))
NDData([1, 2, 3])
```

**Comment by pllim** [comment]
Maybe @mwcraig can advise.

**Comment by saimn** [comment]
Showing the unit seems a good idea :+1:
