### ISSUE TITLE
Docstrings on ``Table.read`` and ``Table.write``

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11554]
### Description

<img width="337" alt="Screen Shot 2021-04-13 at 15 01 34" src="https://user-images.githubusercontent.com/8949649/114606403-36cf8180-9c69-11eb-8242-126c84d3b4b4.png">

 = 😢 

### Additional context

Haven't tested this, but I think they just need a ``__doc__`` attribute.

**Comment by pllim** [comment]
Huh... I have a recollection that @taldcroft attempted a fix, no?

**Comment by taldcroft** [comment]
Not clear what's happening in the sphinx docs. `Table.read?` in IPython gives proper help, and the fix that @pllim may be thinking of is doing `Table.read.help(..)` for full help on parameters for any format.

**Comment by pllim** [comment]
Not sure what's going on there. `read` and `write` doesn't seem to be explicitly implemented under `Table`.

https://docs.astropy.org/en/latest/api/astropy.table.Table.html#astropy.table.Table.read

points to

https://github.com/astropy/astropy/blob/main/astropy/table/connect.py

which are classes, so I am not surprised you see `object` in the API doc...

**Comment by pllim** [comment]
Ahhh... I just found them... Yes, a `__doc__` might work.

https://github.com/astropy/astropy/blob/d3c8efb5fc82d5e9997263829c62ca459647591e/astropy/table/table.py#L594-L596

**Comment by nstarman** [comment]
@pllim @taldcroft.

I've tried a number of things for automatic fixes:
- setting the` __doc__` attribute in `UnifiedReadWriteMethod.__init__`
- setting the` __doc__` attribute on the owner class using `UnifiedReadWriteMethod.__set_name__`
  ```python
  def __set_name__(self, owner, name):
      # transfer docstring from wrapped function to attribute
      setattr(getattr(owner, name), "__doc__", self.func.__doc__)
  ```
- Directly setting __doc__ on the table class.

I wonder if this is actually an automodapi issue. Maybe transfer ?

**Comment by pllim** [comment]
@astrofrog , what do you think?

**Comment by nstarman** [comment]
Now also a problem in #11559.

**Comment by larrybradley** [comment]
See https://github.com/astropy/astropy/pull/11807 for a possible solution.
