### ISSUE TITLE
Backport Table bugfix?

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#11573]
I've discovered a table bug that is present all released versions of astropy:

```python
from astropy.coordinates import SkyCoord
from astropy.table import QTable
import astropy.units as u

coord = SkyCoord([10, 20, 30] << u.deg, [30, 40, 50] << u.deg)
tbl = QTable()
tbl['coord'] = coord
tbl['flux'] = [20., 1., 10] << u.Jy

# this works
tbl.sort('flux')

# write and then read table from ECSV
tbl_fn = 'table_test.ecsv'
tbl.write(tbl_fn, overwrite=True)
tbl2 = QTable.read(tbl_fn)

# this fails
tbl2.sort('flux')
```
```
Traceback (most recent call last):
  File "/Users/lbradley/Desktop/bug/./table_bug.py", line 21, in <module>
    tbl2.sort('flux')
  File "/Users/lbradley/.pyenv/versions/3.9.4/lib/python3.9/site-packages/astropy/table/table.py", line 2981, in sort
    indexes = self.argsort(keys)
  File "/Users/lbradley/.pyenv/versions/3.9.4/lib/python3.9/site-packages/astropy/table/table.py", line 2894, in argsort
    index = get_index(self, names=keys)
  File "/Users/lbradley/.pyenv/versions/3.9.4/lib/python3.9/site-packages/astropy/table/index.py", line 650, in get_index
    for index in table[name].info.indices:
TypeError: 'NoneType' object is not iterable
```

This bug is fixed by https://github.com/astropy/astropy/pull/11077.  While that PR was labeled as a bug, it "seemed not important enough to backport" as it was largely addressing a table performance issue.  

The above example indicates a real bug affecting users, so perhaps #11077 should be backported to the next bugfix release?

CC: @mhvk, @taldcroft

**Comment by pllim** [comment]
#11077 also has API change. Is it possible to only backport the bug fixing part? Or can't you wait for 4.3?

**Comment by larrybradley** [comment]
I'll let the table maintainers decide.  I don't think this particular bug was on their radar for #11077.

**Comment by mhvk** [comment]
Tricky one. My tendency would be too backport if it is relatively easy (I can try). Definitely we did not realize this bug affected writing and reading back. Which is rather surprising!! (Nice sleuthing, @larrybradley, and sorry that this likely took you quite a bit of time to track down...)

**Comment by larrybradley** [comment]
No worries.  After spending the time tracking it down, I thought it good to report it. :smile:

**Comment by larrybradley** [comment]
Works in 4.3
