### ISSUE TITLE
ValueError when using fitting.LevMarLSQFitter() with weights

### ISSUE THREAD

**Issue by bkornpob** [astropy/astropy#11581]
I got an error while trying to use astropy.modeling.fitting. I tried to call this:
```
from astropy.modeling import models,fitting
norder = 2
tx = np.arange(10)
ty = np.arange(10)
tw = np.arange(10)
fitter = fitting.LevMarLSQFitter()
bkg_model = models.Polynomial1D(norder)
tf = fitter(bkg_model,tx,ty,weights=tw)
```
And the error is:
`ValueError: operands could not be broadcast together with shapes (10,) (10,3) `
The code worked fine if 'weights' was not used:
`tf = fitter(bkg_model,tx,ty)`

**Comment by pllim** [comment]
cc @nden and @perrygreenfield

**Comment by WilliamJamieson** [comment]
@bkornpob Can you try running your code using this branch: https://github.com/WilliamJamieson/astropy/tree/tickets/issue-11581. I think this might solve your problem.

Please let me know if you get the results you expected.

**Comment by bkornpob** [comment]
Hi,

Sorry for the late response, I was on vacation last week. I noticed that
you already closed the ticket, so should I update the astropy and that
should work?

Thank you,
Kornpob

**Comment by WilliamJamieson** [comment]
Yes this has been resolved. It should work on the latest version of astropy.
