### ISSUE TITLE
Add narrative documentation on physical types

### ISSUE THREAD

**Issue by namurphy** [astropy/astropy#11588]
### Description

In #11204 we made the `physical_type` attribute of units into instances of the new [`PhysicalType`](https://github.com/astropy/astropy/blob/4a289db09ac1026b038d156c1e1139223a762590/astropy/units/physical.py#L199) class.  Before this, `physical_type` returned a string.  It's now possible to do dimensional analysis along the lines of:
```Python
>>> import astropy.units as u
>>> length = u.m.physical_type
>>> area = u.get_physical_type("area")
>>> length * area
PhysicalType('volume')
```
There are descriptions on how to use physical types in the docstrings for `PhysicalType`, `get_physical_type`, and `UnitBase.physical_type`.  Following a [suggestion](https://github.com/astropy/astropy/pull/11204#pullrequestreview-636754774) in #11204, it would be helpful to add a discussion of physical types in the narrative documentation for `astropy.units`.  

It might be helpful to write out or have a table of all of the names of physical types.  I'm not sure if this would be best in the narrative documentation or in the docstring for `get_physical_type`.

**Comment by nstarman** [comment]
> It might be helpful to write out or have a table of all of the names of physical types. I'm not sure if this would be best in the narrative documentation or in the docstring for get_physical_type.

If it's in the narrative docs we might be able to x-ref to it so that physical types can better be incorporated into docstrings

```
    param : quantity-like [physical type]
```

@adrn,  #11555
