### ISSUE TITLE
Warnings display twice in Jupyter notebooks

### ISSUE THREAD

**Issue by rosteen** [astropy/astropy#11600]
### Description
Previously I was seeing this behavior in both a Jupyter notebook context and in an interactive python session in a terminal, but pulling the most recent `main` branch updates and doing a dev install seems to have fixed the latter case.  I'm still seeing duplicate warning messages (with minor syntax differences between the two) when I use astropy in a notebook,  for example:

```
WARNING: No observer defined on WCS, SpectralCoord will be converted without any velocity frame change [astropy.wcs.wcsapi.fitswcs]
WARNING:astropy:No observer defined on WCS, SpectralCoord will be converted without any velocity frame change
```

I imagine this has something to do with the way the `AstropyLogger` is catching and displaying `warnings.warn` calls.

### Steps to Reproduce

A quick snippet to trigger a warning:
```python
import numpy as np
import astropy.units as u

flux = np.ones(3) * u.Unit("1E-17 erg/s/cm^2/Angstrom")
```

This displays two warnings:
```
WARNING: UnitsWarning: '1E-17 erg/s/cm^2/Angstrom' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
WARNING:astropy:UnitsWarning: '1E-17 erg/s/cm^2/Angstrom' contains multiple slashes, which is discouraged by the FITS standard
```

### System Details

Checking that my notebook is actually using the dev version of astropy:

Python 3.8.8 (default, Feb 24 2021, 13:46:16) 
Numpy 1.20.1
astropy 4.2.dev2287+g8615fc8ca

**Comment by pllim** [comment]
Should have been 4.3.dev now. Did you do a `git fetch upstream --tags`?

**Comment by pllim** [comment]
You must have some custom logger setting somewhere causing this. I cannot reproduce this on my end. I only see one warning.

![Screenshot 2021-04-19 103805](https://user-images.githubusercontent.com/2090236/115254508-68c66500-a0fb-11eb-9b02-6b0379248c4f.jpg)

**Comment by rosteen** [comment]
Ah, I just did a pull not fetch. I have `astropy 4.3.dev1123+g8615fc8ca` after fetching the tags. 

Upon further inspection it looks like you're correct about this originating somewhere other than astropy, I'll close this issue and investigate further. I suspect it's actually a specutils issue...

**Comment by pllim** [comment]
If you turn all warnings into errors, you might get a traceback, though not sure if that would even be useful. Good luck!

**Comment by pllim** [comment]
p.s. Maybe this is why.

https://github.com/astropy/specutils/blob/57dd2b28e5122e00e28333043192d30ec9f78a9d/specutils/__init__.py#L55-L58

**Comment by rosteen** [comment]
> p.s. Maybe this is why.
> 
> https://github.com/astropy/specutils/blob/57dd2b28e5122e00e28333043192d30ec9f78a9d/specutils/__init__.py#L55-L58

That's exactly where I had just started my investigation. Thanks for the tips!

**Comment by saimn** [comment]
To clarify, one line is the warning from `warnings.warn` and the other line is a logging message from the Astropy logger that catches warnings to display them. So not really a duplicate, though this feature doesn't really make sense to me (warnings and logging messages are different things).
