### ISSUE TITLE
Provide an easy way to generate random coordinates spatially uniform distributions

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#11612]
This is a follow-on from #10241 and some related discussion.  While I think we settled there that `zeros` is not that compelling, having a way to randomly sample coordinates *is* - in fact I think several of the tests do this already in various ways.

So this issue is to suggest adding some helper functions to auto-generate random coordinates that are either:

1. uniform on the sky (but without any specific 3D distribution - i.e. `UniformSphericalRepresentation`
2. uniform density in a fixed 3D volume

While we could get away with just, say, 2, and say the user can drop the r-coordinate, I'd advocate for both since there's a factor-of-a-few performance difference (see https://gist.github.com/eteq/2c1b9c5b5ba04cb8d36a8f4df78087b9 for proof of this).

One could argue as in #10241 that this could be a `SkyCoord` `classmethod`, but I'm inclined more towards a regular function.

cc @astrofrog @adrn @mhvk

**Comment by lpsinger** [comment]
Might be good to think about the use cases first. (I happened to write a module a few days ago for [generating _uniform grids_ of SkyCoord objects](https://dorado-scheduling.readthedocs.io/en/latest/reference/skygrid.html), for the purpose of laying out tiles for an all-sky survey.)

**Comment by adrn** [comment]
Oh nice, yea, I've implemented those a few times too! (Maybe an argument that we should add some utilities to do this in `astropy.coordinates.angle_utilities.py` or a new `astropy.coordinates.angle_generators.py` or something?)

In the context of this issue, I think the main use case is in astropy.coordinates tests, when we often need to generate some test coordinates but are agnostic about the specific positions. Having grids like the golden angle spiral is probably even better (as we try to remove random calls from our test suite).

**Comment by adrn** [comment]
Hah, in looking into this a bit more, I found that we have https://github.com/astropy/astropy/search?q=randomly_sample_sphere 😅. But I would vote to make a more public API for this. Simple PR incoming to start discussion...
