### ISSUE TITLE
Where are WCS comparison constants defined?

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#11631]
[`astropy.wcs.Wcsprm.compare`](https://docs.astropy.org/en/stable/api/astropy.wcs.Wcsprm.html?highlight=wcscompare_ancillary#astropy.wcs.Wcsprm.compare) documents a number of constants (e.g. `WCSCOMPARE_ANCILLARY`) that can be used with the `cmp` argument to modify how the comparison between two WCSs is done. It's not clear to me where these are defined however.

I've tried under `astropy.wcs` and `astropy.wcs.Wcsprm`, but maybe I'm missing somewhere? Wherever they are defined should be documented in the docstring of `.compare()`.

**Comment by pllim** [comment]
I think these are copied over from `wcslib`.

https://github.com/astropy/astropy/blob/32019d734d1874dc836f47e2a35c6c57123eb6b8/cextern/wcslib/C/wcs.h#L1979

Maybe @mcara or @dhomeier can confirm, since they been staring at `wcslib` a lot lately.

**Comment by dhomeier** [comment]
That's right; since they are compiled in and linked from either the bundled or a system WCSLIB, it's not really possible to nail down where exactly they are defined. Anyway they are available as `wcs._wcs.WCSCOMPARE_*`.
The docstring is created in `wcs/docstrings.py` if you feel there is room for clarifying this better.

**Comment by dstansby** [comment]
I think a good fix here would be to:

- Import them in to the `astropy.wcs` namespace, so they're more easily discoverable for users
- Document this in the docstring of `.compare()`.

**Comment by dhomeier** [comment]
Agree about updating the docstring; for putting them in the top-level namespace I'll defer to the wcs maintainers. I don't know how much that method is typically used, but then the module already has a number of `wcs.WCS*` constants defined, so three more probably should not add too much clutter.

**Comment by mcara** [comment]
@dstansby Thank you for reporting this!
