### ISSUE TITLE
Substitute deprecated pep517.build in version tagging instructions

### ISSUE THREAD

**Issue by matteobachetti** [astropy/astropy#11632]
### Description

In [the release instructions](https://astropy-astrofrog.readthedocs.io/en/latest/development/releasing.html) the package build is made with

    > python -m pep517.build --source .

This command warns that this is deprecated:

    pep517.build is deprecated. Consider switching to https://pypi.org/project/build/

and should be substituted with:

    python -m build <options> .

**Comment by pllim** [comment]
Looks like on the code side, OpenAstronomy/azure-pipelines-templates#50 is done. So this will be a purely documentation update. Good catch!

**Comment by SauravMaheshkar** [comment]
Hey @pllim this seemed like some low hanging fruit. I opened up a quick [PR](https://github.com/astrofrog/astropy/pull/102).  Did I get it right ?

**Comment by pllim** [comment]
Thanks, @SauravMaheshkar , but unfortunately you opened it in the wrong repository.

**Comment by SauravMaheshkar** [comment]
Huh, but the link mentioned in the issue is of the astrofrog repository and the astropy [releasing docs](https://github.com/astropy/astropy/blob/main/docs/development/releasing.rst) don't seem to have this issue ?

I'm sorry but can you please tell which file / repository to edit instead ?

**Comment by astrojuanlu** [comment]
> At this point if all goes well, the wheels and sdist will be build in the Azure core package pipeline and uploaded to PyPI!

Looks like this process is now automated, and therefore this issue can be closed, since there's nothing left to do. Sorry @SauravMaheshkar for the confusion!

**Comment by SauravMaheshkar** [comment]
Nvm. Thanks for clearing it up 😁

**Comment by eerovaher** [comment]
The last mentions of pep517 in `docs/development/releasing.rst` were removed by e84d2d6475e4791d9798cb86100df7d81057a7bf several months before this issue was even opened.

**Comment by pllim** [comment]
Thanks for bringing this to our attention and the clarification, everyone!
