### ISSUE TITLE
Writing compressed FITS files is slow when multi-threaded

### ISSUE THREAD

**Issue by martinjohndyer** [astropy/astropy#11633]
### Description

We want to save multiple FITS images in parallel, and when multithreading it seems there's a significant time loss when saving compressed images compared to uncompressed (more than you'd expect from just compressing the data - see the examples below).

From a bit of research we found that CFITSIO needs a particular flag set when used in multi-threaded environments (https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node15.html), but it's hard to tell if that's set with the version bundled with Astropy. Even installing CFITSIO separately with the flag enabled and then installing Astropy with `ASTROPY_USE_SYSTEM_CFITSIO=1` seemed to not make any difference to the timing.

### Expected behavior

Writing images in parallel is faster than writing them in serial.

### Actual behavior

When compressing images writing out in parallel using multithreading takes longer than doing the same in serial.

### Steps to Reproduce

1) Setup, create two simple output functions and some test data.

```python
import numpy as np
from astropy.io import fits

def write_fits(image, i):
    hdu = fits.PrimaryHDU(image)
    hdulist = fits.HDUList([hdu])
    hdulist.writeto(f"/tmp/uncompressed_{i}.fits", overwrite=True)

def write_compressed_fits(image, i):
    hdu = fits.CompImageHDU(image)
    hdulist = fits.HDUList([fits.PrimaryHDU(), hdu])
    hdulist.writeto(f"/tmp/compressed_{i}.fits", overwrite=True)

image = np.random.randint(0, 2**8, (8000, 6000)).astype("i2")
```

2) Time the functions, note that writing a compressed file takes ~5x longer than uncompressed.
```python
%time write_fits(image, 1)
# CPU times: user 72.5 ms, sys: 80.8 ms, total: 153 ms
# Wall time: 153 ms

%time write_compressed_fits(image, 1)
# CPU times: user 712 ms, sys: 73.2 ms, total: 785 ms
# Wall time: 785 ms
```

3) Try writing out 8 files in series. Again the compressed case takes ~5x longer, as expected.

```python
%time for i in range(8): write_fits(image, i)
# CPU times: user 477 ms, sys: 604 ms, total: 1.08 s
# Wall time: 1.17 s

%time for i in range(8): write_compressed_fits(image, i)
# CPU times: user 5 s, sys: 546 ms, total: 5.55 s
# Wall time: 5.55 s
```

4) Now using a ThreadPool try writing out the images in parallel. For uncompressed images this reduces the time to ~60% of the above serial case, but when compressing images it actually takes several seconds longer!

```python
from itertools import repeat
from multiprocessing.pool import ThreadPool

with ThreadPool() as pool:
    %time pool.starmap(write_fits, zip(repeat(image),list(range(8))))
# CPU times: user 522 ms, sys: 725 ms, total: 1.25 s
# Wall time: 710 ms

with ThreadPool() as pool:
    %time pool.starmap(write_compressed_fits, zip(repeat(image),list(range(8))))
# CPU times: user 7.09 s, sys: 1.6 s, total: 8.7 s
# Wall time: 7.66 s
```

### System Details

```
Linux-5.4.0-72-generic-x86_64-with-glibc2.29
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
Numpy 1.19.4
astropy 4.2
Scipy 1.6.0
Matplotlib 3.3.3
```

**Comment by saimn** [comment]
Closing, please comment/reopen if there is anything new or if I missed something above.
