### ISSUE TITLE
wcs.pixel_to_world is seriously wrong for Equatorial coordinates.

### ISSUE THREAD

**Issue by Jinhua-He** [astropy/astropy#11636]
python 3.8.5
numpy 1.19.2
astropy 4.0.2

I find that the conversion of pixel positions to RA will dilate the angular size of all pixels by a factor of more than 3! The conversion to DEC is correct, however. 

For example, if I get the WCS from an input fits image that has more than 2500 pixels along each of the two axes through:

wcs = WCS(hdul[0].header)

Using print(hdul_N[0].header), I get the following wcs parameters:

CTYPE1  = 'RA---TAN'           / name of the coordinate axis                    
CTYPE2  = 'DEC--TAN'           / name of the coordinate axis                    
CRPIX1  =         1.300500E+03 / coordinate system reference pixel              
CRPIX2  =         1.630500E+03 / coordinate system reference pixel              
CROTA1  =         0.000000E+00 / coordinate system rotation angle               
CROTA2  =         0.000000E+00 / coordinate system rotation angle               
CRVAL1  =         1.868108E+02 / coordinate value at reference pixel            
CRVAL2  =        -7.153672E+01 / coordinate value at reference pixel            
CDELT1  =        -1.111111E-03 / coordinate increment along axis                
CDELT2  =         1.111111E-03 / coordinate increment along axis                

It means the pixel shape is square, and its size is 0.0011111 degree. Then, I try to convert two pixels that are separated equally in RA and DEC, e.g.,

wcs.pixel_to_world([1000,2000],[1000,2000])

I should expect to get equal separations in both RA and DEC of 1.11111 degree. However, what I get is

<SkyCoord (FK5: equinox=2000.0): (ra, dec) in deg
    [(187.9013224 , -72.2331139 ), (184.40632521, -71.10960646)]>

which means the separation in RA is unexpectedly expanded by a factor of >3. This is totally wrong!!!

Even for the DEC, the separation is 1.12350744 deg, which is still 1.1% larger than the nominal separation. I understand that this should be a projection effect at this high DEC range.

**Comment by Jinhua-He** [comment]
If I show the image with plt.subplot(projection=wcs), the problem can be also seen in the shown axis ticks and cursor coordinates.

**Comment by Jinhua-He** [comment]
I have figured out the reason. It is not a bug. At the high DEC, the RA coordinate becomes highly non-linear function of pixels. I should always use the SkyCoord.separation() method to compute the angular distance on the sky.

**Comment by embray** [comment]
@Jinhua-He Thanks for the update!  Let us know if you still have any problems related to this.
