### ISSUE TITLE
`SkyCoord == str` raises an error, instead of returning `False`

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#11661]
### Description
When doing an equality check between a `SkyCoord` and a `str`, an error is raised.

### Expected behavior
Returns `False`.

### Actual behavior
Raised an error.

### Steps to Reproduce
```python
from astropy import units as u
from astropy.coordinates import SkyCoord
c = SkyCoord(ra=10.625*u.degree, dec=41.2*u.degree, frame='icrs')
print(c == 'my_string')
```

```python
Traceback (most recent call last):
  File "/Users/dstansby/github/sunpy/test.py", line 4, in <module>
    print(c == 'my_string')
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/coordinates/sky_coordinate.py", line 368, in __eq__
    for attr in self._extra_frameattr_names | value._extra_frameattr_names:
AttributeError: 'str' object has no attribute '_extra_frameattr_names'
```

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.9.1 (default, Dec 11 2020, 06:28:49) 
[Clang 10.0.0 ]
Numpy 1.19.3
astropy 4.2.1
Scipy 1.5.4
Matplotlib 3.4.1

**Comment by pllim** [comment]
Not sure if #11663 is the best solution, but it does give you the output you wanted...

**Comment by mhvk** [comment]
From https://github.com/astropy/astropy/pull/11663#issuecomment-829298253:
> This is a big can of worms: should one follow python and always return either True or False, or follow numpy and return an appropriately shaped boolean array, raising an error if, e.g., the shapes of the inputs do not match. Personally, I'm torn!

Ideally, we'd have both, but how?

**Comment by dstansby** [comment]
To fix this particular issue, could one not just put
```python
if not isinstance(value, SkyCorod):
    return False
```
at the beginning of the method?

**Comment by mhvk** [comment]
Or maybe `return NotImplemented` - which would lead to the same effect. That actually seems a good solution, since `SkyCoord` does not know how to prepare to other classes.

**Comment by mhvk** [comment]
(This unlike `numpy`, which just tries to make everything an array.)

**Comment by pllim** [comment]
@dstansby , since it is your idea, do you want to open a PR implementing https://github.com/astropy/astropy/issues/11661#issuecomment-829366618? 😸

**Comment by dstansby** [comment]
👍
