### ISSUE TITLE
Remove all support for VOTable version 1.0

### ISSUE THREAD

**Issue by tomdonaldson** [astropy/astropy#11669]
### Description

`astropy.io.votable` support for VOTable version 1.0 has been very limited for quite some time, with several warnings to that effect already present in the code.  However `astropy.io.votable.VOTableFile.__init__()` still allows `version='1.0'` to be specified.  With Astropy 4.3 a deprecation warning is raised for that case, so in a future release we should raise a `ValueError` instead.

I suspect this loophole is never used, so I don't think a long deprecation period is necessary.

EDIT: Deprecated in `astropy` 4.3, see #11659

**Comment by pllim** [comment]
I wonder if astropy 5.0 is too soon or just right... 👀

**Comment by marcellonascif** [comment]
Hi! I would like to colaborate to this issue. Is it still available for fixes?
Thanks!

**Comment by ManonMarchand** [comment]
Is there a way to see if some services in the VO registry are still returning old VOtables? What about old files in people's workflows? What is gained from the deprecation? Is it impossible to support all VOtables versions from 1.0 to 1.5?

**Comment by tomdonaldson** [comment]
As noted in #15490, I think this issue should have been written with the more limited scope exhibited by the deprecation behavior in #11659.  That is, prevent users from explicitly specifying `version="1.0"` in `VOTableFile.__init__`, but still allow version 1.0 VOTables to be parsed (with validation warnings).  If such VOTables are written back out, they will not be totally valid version 1.0 VOTables due to the missing `<DEFINITIONS>` element which was required in v1.0.  I think that last limitation is fine since the use of v1.0 has been discouraged by the IVOA since v1.1 came out in 2004, and most parsers will accept the missing `<DEFINITIONS>` anyway.
