### ISSUE TITLE
Representing Fields (ie scalar, vector, etc.)

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11667]
### Proposal

Add a new module to coordinates to represent fields — scalar, vector, and tensor — and leverage Astropy coordinates to handle transforming representation types. 2) add a new class ``Field`` to handle collections of fields that share the same set of points. This would leverage ``QTable`` to hold the data, enable easy I/O, and potentially even make the Fields class useful for catalogs.

@mhvk @adrn @taldcroft @eteq 

Current example code : https://github.com/nstarman/astropy/blob/coord_vectorfield/astropy/coordinates/field.py

### Motivation

Any time you have a table of coordinates and a property for each of those coordinates. For scalars, like a gravitational potential field, ``Field`` is just a very convenient way to package the information, but for vectors like the corresponding acceleration field,  transformations between representation types would be extremely nice.

### Implementation

It's a change-of-basis. Astropy's Representation machinery can do it already, it just needed some tweaking for this new use case.

### Potential Future Extensions

Expanding ``Field`` to handle CoordinateFrame transformations on the fields.

### Examples

The basis is ``BaseFieldRepresentation``, which defines the components of a field at a point:
```python
>>> from astropy import table, coordinates as coord, units as u
>>> import numpy as np

>>> points = coord.CartesianRepresentation(x=np.linspace(0, 10) * u.kpc,
...                                        y=np.linspace(-1, -11) * u.kpc,
...                                        z=np.linspace(-3, 3) * u.kpc)
>>> fr = coord.CartesianFieldRepresentation(np.linspace(0, 10) * u.km / u.s**2,
...                                         np.linspace(10, 100) * u.km / u.s**2,
...                                         np.linspace(100, 1000) * u.km / u.s**2,
...                                         points=points)
>>> fr[:3]
<CartesianFieldRepresentation (x, y, z) in kpc | (q1, q2, q3) in km / s2
    [((0.        , -1.        , -3.        ), (0.        , 10.        , 100.        )),
     ((0.20408163, -1.20408163, -2.87755102), (0.20408163, 11.83673469, 118.36734694)),
     ((0.40816327, -1.40816327, -2.75510204), (0.40816327, 13.67346939, 136.73469388))]>
```

Codewise, BaseFieldRepresentation is less than 200 lines of code (excluding docstrings), but could probably be shorter since a fair bit is only lightly modified from ``BaseRepresentationOrDifferential``. It's designed for multiple inheritance so that making new field representations is very easy. For example, this is how I made ``SphericalFieldRepresentation``

```python
class SphericalFieldRepresentation(FieldRepresentationBase, SphericalRepresentation): pass
```

Since ``BaseRepresentationOrDifferential`` (and therefore ``BaseFieldRepresentation``) can be columns in a QTable, this enables the ``Field`` class, which holds in a table: pointes (a Representation) and an arbitrary number of fields, scalar or vector (or hypothetically tensors, if extended). As an example

```python
>>> field = coord.Field(points,
...             mass=1 * u.solMass,  # scalar field
...                 vector=np.c_[np.linspace(0, 10),  # vector field
...                              np.linspace(10, 100),
...                              np.linspace(100, 1000)] * u.km / u.s**2)
>>> field[:5]
```
<img width="579" alt="Screen Shot 2021-04-29 at 12 58 33" src="https://user-images.githubusercontent.com/8949649/116589409-9f199680-a8ea-11eb-86f3-bda05427299a.png">

The Field has both attribute and item access to all the fields in the table.

The Field can be transformed between representation types and it uses the above machinery to not only transform the points, but also all the vector fields (scalar fields are invariant).
```python
>>> Field.fieldtypes
mappingproxy({'mass': 'scalar', 'vector': 'vector'})
```

Showing a transformation:
```python
>>> field.represent_as("spherical").vector[:3]
<SphericalFieldRepresentation (lon, lat, distance) in (rad, rad, kpc) | (q1, q2, q3) in km / s2
    [((4.71238898, -1.24904577, 3.16227766), (-1.83697020e-15, 22.13594362,  -98.03060747)),
     ((4.8802849 , -1.16942764, 3.12598173), ( 2.17922774e+00, 35.53216363, -113.50636578)),
     ((4.99451271, -1.0817616 , 3.12091466), ( 4.19866693e+00, 52.7411567 , -126.82369045))]>
```

**Comment by mhvk** [comment]
@nstarman - this sounds very interesting! I like how it uses both representation and table. I also wonder if this type of approach isn't a better way to handle differentials (which I've never been completely happy with...). But might be good to think through some actual use cases. Perhaps as part of the coordinates get-together? (Obviously, in a bit, let's first get 4.3 out!!)

**Comment by hamogu** [comment]
I guess a `QTable` might be the right data structure for arbitrary fields, but for fields on a regular grid (as in the example above) a `NDArray` might be a more natural choice. But, of course, the `Table` machinery is much more mature and can deal with vectors of coordinates already, while ND data cubes are not as much used and as developed yet.
