### ISSUE TITLE
Expose physical types and list of types in module.

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11678]
Copied from astropy/astropy#11595.

> a good addition to physical.py might be to add each physical type to the module (like how cosmology realizations are added in cosmology/realizations.py) and have a set of all their names.
available_physical_types= _name_physical_mapping.keys() would conveniently stay updated as people define new physical types. Were this implemented, then that would change #11595 (comment) and this PR to use all publicly-scoped functions.

@namurphy, is adding the physical type to the module actually desirable? I think the ``available_physical_types`` is definitely  good, but I'm more on the fence about the first suggestion.

**Comment by namurphy** [comment]
Oh that's interesting!  Would this end up being something like this?
```Python
>>> from astropy.units.physical import length, speed, absement, energy_density
```
Doing something along these lines does sound potentially quite useful, and more in line with how we get units from `astropy.units`.  The example I had ↑ is how I'd personally go about doing this, but with that said, I'm definitely open to other possibilities along these lines.

**Comment by nstarman** [comment]
>Would this end up being something like this? 

Yeah! That's exactly what I was thinking as well.
