### ISSUE TITLE
Simplified interface for reading and writing numpy.arrays in fits

### ISSUE THREAD

**Issue by dov** [astropy/astropy#11671]
### Description

Currently writing and reading a fits file is to complex. E.g. to save a numpy array into a fits file, the simplest way that I have found is doing:

```
def write_fits(ary, filename):
  if os.path.exists(filename):
    os.unlink(filename)
  hdul = fits.HDUList()
  hdul.append(fits.ImageHDU())
  hdul[0].data = ary
  
  hdul.writeto(filename)    
```

I would like to have a simplified interface so that it is as easy as calling the above routine. 

I'm not sure how to call this since this is obviously not a general fits file but a subset of fits for storing np.arrays. So perhaps it can be called `astro.io.fits.array.write_fits()` . Not sure.

### Additional context

It is possible that I missed something and there is a one line solution for loading and saving fits file into np arrays. If so please enlighten me. :-)

**Comment by dov** [comment]
Meanwhile I created my own simplified interface at https://github.com/dov/npfitsio .

**Comment by saimn** [comment]
There are already various levels in the API, e.g. the [convenience functions](https://docs.astropy.org/en/latest/io/fits/#convenience-functions) (`getdata`, `getheader`, `append`, `update`, etc.) provide what you're looking for:
```
fits.writeto('out.fits', data, overwrite=True)
```
It's also possible for a bit more flexibility to write an HDU object:
```
fits.ImageHDU(data=data, name='MYDATA').writeto('out.fits', overwrite=True)
```

**Comment by dov** [comment]
Thanks! This is indeed what I was looking for. I'll close this issue.
