### ISSUE TITLE
Test failure in test_aa_high_precision()

### ISSUE THREAD

**Issue by mkbrewer** [astropy/astropy#11683]
### Description

This is in regards to issue #11527 and PR #11564. At first, I didn't worry too much about the failure as the difference appeared to be small enough to be ascribed to the change in the handling of polar motion introduced in pyerfa 1.7.2. I calculate that differences due to this change should be less than 1 uas and the difference shown in issue #11547 is 8.63433769e-11 degrees or 0.31 uas, but then along came PR #11564 which is evidently showing the following differences:
```
Azimuth 19.62 uas
Elevation 0.85  uas
Distance 38.87 mm
```
These seemed excessively large to me, so I downloaded the latest version of SOFA and reran my test program. The results for the time used in the test are:
```
       Time            Azimuth         Elevation       Distance (m)    DUT1      Xp       Yp
2017-04-06 00:00:00 15.032673509956 50.303110133923 376252883.247239 0.4634343 0.009587 0.384603
```
Here I am including the EOP values to make sure that we are still on the same page in that regard. The differences between this and the previous version of SOFA that I used are:
```
Azimuth 0.252 uas
Elevation -0.018 uas
Distance  0.000 mm
```
Considering the apparent discrepancy, I think it would be worthwhile to revisit the entire 24 hour test. If someone could please run the following script and post the output here, I can take a look at this.

[astropy_topo_test.py.txt](https://github.com/astropy/astropy/files/6411715/astropy_topo_test.py.txt)

**Comment by srirajshukla** [comment]
@mkbrewer 
I ran the `astropy_topo_test.py.txt` file. The output is at [https://gist.github.com/srirajshukla/bafde9050911e9840c590941183481f7](https://gist.github.com/srirajshukla/bafde9050911e9840c590941183481f7)

**Comment by mkbrewer** [comment]
Thanks. I'll take a look at this.

**Comment by mkbrewer** [comment]
OK. For the time used by the test against my original data, I'm seeing:
```
Azimuth 0.3096 uas
Elevation -0.0036 uas
Distance 0.0120 mm
```
After updating SOFA and rerunning my test, I'm seeing:
```
Azimuth 0.0576 uas
Elevation 0.0144 uas
Distance 0.0120 mm
```
This compares favorably to what I saw originally:
```
Azimuth -0.0288 uas
Elevation 0.0036 uas
Distance 0.0120 mm
```
There is no significant divergence over the full 24 hours either, so it looks like there is nothing to be concerned about here. I don't know where the data posted by @pllim in PR #11564 came from, but it doesn't seem to be from the current main branch.

**Comment by mkbrewer** [comment]
For completeness, here is the data from my program after the SOFA update and using JPL DE440, should you wish to switch to that ephemeris:
```
       Time            Azimuth         Elevation       Distance (m)    DUT1      Xp       Yp
2017-04-06 00:00:00 15.032673925087 50.303110036283 376252883.368378 0.4634343 0.009587 0.384603
```

**Comment by mhvk** [comment]
@mkbrewer - thanks so much for checking, and @srirajshukla for running the astropy code. I think it makes sense to update the test to compare with your new-SOFA, DE440 result.

**Comment by pllim** [comment]
The failure I saw before was reported in #11527

**Comment by mkbrewer** [comment]
@pllim Yes, that's the mystery here. In #11527 you reported a difference of  8.63433769e-11 degrees or 0.3108 uas, but then in #11564, this became 19.61955718 uas.

**Comment by pllim** [comment]
The results from my PR was calculated locally on my machine, I think. Do you think I somehow have some outdated DE-what-what file somewhere in the system? I have no idea how this thing work. If you tell me what to update, I can rerun it locally for sanity check.

**Comment by pllim** [comment]
p.s. If updating is the answer, does that mean we need to bump minversion of whatever package that affected my calculations?

**Comment by mkbrewer** [comment]
Well, the JPL DE430 ephemeris was created in 2013 and has never change since, so that's unlikely.

**Comment by mkbrewer** [comment]
Perhaps, your EOP file is different. Please take a look at `astropy.utils.iers.data.eopc04_IAU2000.62-now` and check `x`, `y`, and `UT1-UTC` for April 6th, 2017 to see if they are the same as my `Xp`, `Yp`, and `DUT1`.

**Comment by pllim** [comment]
Okay, so here is what I see in the `eopc04_IAU2000.62-now` file, it is basically the file from `main`, as I did an editable install from source. If there is some API calls for extra checks, please let me know.

```
      Date      MJD      x          y        UT1-UTC       LOD         dX        dY        x Err     y Err   UT1-UTC Err  LOD Err     dX Err       dY Err  
                         "          "           s           s          "         "           "          "          s         s            "           "
     (0h UTC)
2017   4   6  57849   0.009587   0.384603   0.4634343   0.0014635  -0.000063   0.000300   0.000060   0.000046  0.0000179  0.0000132    0.000046    0.000041
```

And then, I run the following manually in a Python session:

```python
>>> import astropy
>>> astropy.__version__
'4.3.dev1480+g0860b7006'
>>> from astropy import units as u
>>> from astropy.coordinates import AltAz, EarthLocation, solar_system_ephemeris
>>> from astropy.coordinates.solar_system import get_body
>>> from astropy.time import Time
>>> lat = -22.959748 * u.deg
>>> lon = -67.787260 * u.deg
>>> elev = 5186 * u.m
>>> loc = EarthLocation.from_geodetic(lon, lat, elev)
>>> t = Time('2017-04-06T00:00:00.0', location=loc)
>>> with solar_system_ephemeris.set('de430'):
...     moon = get_body('moon', t, loc)
...     moon_aa = moon.transform_to(AltAz(obstime=t, location=loc))
>>> TARGET_AZ = 15.032673509886 * u.deg
```

## With jplephem 2.14

```python
>>> moon_aa.az
<Longitude 15.03267352 deg>
>>> moon_aa.az - TARGET_AZ
<Angle 5.44987699e-09 deg>
>>> (moon_aa.az - TARGET_AZ).to(u.uas)
<Angle 19.61955718 uas>
```

# With jplephem 2.15

```python
>>> moon_aa.az
<Longitude 15.03267351 deg>
>>> moon_aa.az - TARGET_AZ
<Angle 8.63433769e-11 deg>
>>> (moon_aa.az - TARGET_AZ).to(u.uas)
<Angle 0.31083616 uas>
```

There is currently no pin on the `jplephem` minversion:

https://github.com/astropy/astropy/blob/0860b70066656682f852c6683a19b6d0b6b82164/setup.cfg#L77

**Comment by mkbrewer** [comment]
@pllim Thanks. That solves the mystery. Looks like a bug in jplephem 2.14 to me.

**Comment by mhvk** [comment]
@pllim, @mkbrewer - very good sleuthing!

@brandon-rhodes - above (https://github.com/astropy/astropy/issues/11683#issuecomment-831471752) found a significant difference between using jplephem 2.14 and 2.15, with DE430. From the changelog, there is nothing obvious that could cause this; do you have any suggestion? If not, it is of course quite possible that the problem is on our side, on how we call jplephem... (and we will see if we can provide a more minimal example, just calling `jplephem`).

**Comment by brandon-rhodes** [comment]
@mhvk — I will update the changelog; there was indeed a single commit that the changelog fails to mention:

https://github.com/brandon-rhodes/python-jplephem/commit/e90ca0fbe2da4b863ce141623c1c76d87e00cb69

It slightly reduces the noise down near the machine precision level, providing a few final digits in which motion is monotonic rather than simply noise. Am I correct in the following two observations?

1. The test result shows the new 2.15 version of jplephem is in closer agreement than the 2.14 version? (That's how, at first glance, I'm interpreting the smaller uas measurement.)
2. That the difference is not physically meaningful? The DE440 residuals for the moon in Figure 4 of [the PDF](https://iopscience.iop.org/article/10.3847/1538-3881/abd414/pdf) show an error of a few cm, which — if the back of my envelope is correct — amounts to an angular uncertainty of `(3 cm / 384.4e6 m) / (2*pi) * 360 * 60 * 60 * 1e6` = 16 uas (taking “a few cm” to be “3 cm” for the sake of concreteness), or around the same size of the difference between test runs.

**Comment by mhvk** [comment]
@brandon-rhodes - thanks for the quick reply! It sounds like this explains the difference. Note that the actual test is not one that promises that the real accuracy is anything like less than a uas, just that if given exactly the same input, two independent implementations of the transformations give the same answer. 

Anyway, it goes to show that even the small improvements are noticed, for better or for worse!  

And bottom line for this PR may be that we slightly relax our constraint for JPLephem < 2.15

p.s. Looking at the commit you linked to: wouldn't you wish there was proper `float128` support in numpy! We've had quite a few similar fixes in `Time`...

**Comment by brandon-rhodes** [comment]
> p.s. Looking at the commit you linked to: wouldn't you wish there was proper float128 support in numpy! We've had quite a few similar fixes in Time...

Yes, indeed! Even `float96` would solve all the problems. I even experimented early on, only to be disappointed in how rarely the type is actually available on modern hardware. Alas.

**Comment by mkbrewer** [comment]
I'd suggest just adding a minimum requirement for jplephem  2.15. The relative error is 3 parts in 10^-10 which is quite a bit above 64 bit precision. That said, I have seen round off errors myself that cause issues well above machine precision.

**Comment by mhvk** [comment]
See #11700 for a fix.

@brandon-rhodes - is there a way to get the version of `jplephem` one has installed? Right now, I do
```
if '**2020 September 2 — Version 2.15**' in jplephem.__doc__:
```
but this is not super-elegant...

**Comment by brandon-rhodes** [comment]
@mhvk — Maybe I should add a `__version__` to it as a convenience? The canonical way to do the check would, I believe, be:
```
import pkg_resources
pkg_resources.get_distribution('jplephem').version
```

**Comment by pllim** [comment]
Re: `__version__` -- I think `pkg_resources` introduces `setuptools` into your runtime dependency? We use `setuptools_scm` here to generate a `version.py` during installation. And within `__init__.py`, we attempt to import it as `__version__`.

Also, I saw this convo too late. I already opened brandon-rhodes/python-jplephem#47 😬

**Comment by brandon-rhodes** [comment]
No problem, having the separate issue helps track the change. I've resolved it; `__version__` should appear with the next release.

**Comment by saimn** [comment]
Re-`pkg_resources`: we replaced it with `importlib.metadata` (#11091)

**Comment by mhvk** [comment]
@saimn - thanks, that is clearly the best solution for now. I think we should be using this inside `utils.minversion` - see #11705.
