### ISSUE TITLE
Avoid filesystem writes when there are no bytes to write.

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#11696]
### Description

https://github.com/astropy/astropy/blob/main/astropy/io/fits/hdu/table.py#L939 which pads FITS binary tables that variable-length columns out to the necessary multiple of 2880, can be triggered even when `data._gap == 0`.  That is, `fileobj.write(b'')` is not a no-op.

This padding may also be needed if a table or image is not itself an exact multiple of 2880 bytes, so it may be possible to trigger this even when there are no variable-length columns.

### Expected behavior

Don't trigger a filesystem write if there is nothing to write:
```python
if data._gap > 0:
    fileobj.write((data._gap * '\0').encode('ascii'))
```

### Actual behavior

The Lustre filesystem has a known issue that is triggered when zero-length writes are attempted.  This bug report is an attempt to provide a workaround, and in general raise consciousness of corner cases that can happen in certain filesystems.

EDIT: Permalink to the code below

https://github.com/astropy/astropy/blob/3f8cf27b87f2e10f7389190971651cd33178bd7d/astropy/io/fits/hdu/table.py#L939

**Comment by srirajshukla** [comment]
can i work on this?

**Comment by saimn** [comment]
@weaverba137 - What problem is caused by this zero-byte write ? It's quite surprising that a `fileobj.write(b'')` could be a problem. 
About padding (which is done here: https://github.com/astropy/astropy/blob/291919677211bfd7e5b430cdc9b8b75fa41f312a/astropy/io/fits/hdu/base.py#L632), it must always be done so there is no real solution here. But a filesystem that cannot handle null bytes seems problematic ...

@srirajshukla - It's not clear what needs to be done, so there may be better issues.

**Comment by weaverba137** [comment]
@saimn I mentioned this in the description:

> The Lustre filesystem has a known issue that is triggered when zero-length writes are attempted. This bug report is an attempt to provide a workaround, and in general raise consciousness of corner cases that can happen in certain filesystems.

I also described this in the HPC working group report.

As far as padding goes, how can you be absolutely certain that the padding will always be of non-zero length?  What if, by coincidence, or by deliberate effort, someone creates an image or table HDU whose data payload is an exact multiple of 2880 bytes?  Now that I think about it, I could easily do this myself to demonstrate.

**Comment by saimn** [comment]
> I also described this in the HPC working group report.

Yes, but you didn't explain here what are the consequences of this zero-byte write. Is that the long write (minutes?) you were mentioning ?

> As far as padding goes, how can you be absolutely certain that the padding will always be of non-zero length?

I'm confused, I was understanding from the description above that padding with null-bytes was also a problem ? But it seems now it would only be a problem if padding is a zero-byte string as well, so if you write an array whose size is a multiple of 2880 bytes ?

**Comment by weaverba137** [comment]
@saimn, I'm sorry if I'm being unclear.  Is this not making sense:

> The Lustre filesystem has a known issue that is triggered when zero-length writes are attempted.

Please let me know exactly the description you are looking for.

> description above that padding with null-bytes was also a problem ?

No, writing out ascii `b'\0'` is not the issue.  It's only if the write is `b''`.  Again, please let me know what you are looking for.

**Comment by saimn** [comment]
I'm just wondering what is the known issue. Is it slow, does it crash, or does the server explodes ? ;) 

> No, writing out ascii b'\0' is not the issue. It's only if the write is b''.

Ok great, so indeed we could also avoid the zero-byte write in the padding code I mentioned above.

**Comment by weaverba137** [comment]
Ah, right, sorry, it results in a significant slowdown, like by a factor of 10.

**Comment by saimn** [comment]
Ok :). So we could indeed easily avoid those two zero-byte writes by checking before if there is something to write. Do you want to submit a PR ?

**Comment by weaverba137** [comment]
@saimn, sorry, I never replied, but yes, I can submit a PR.

**Comment by dhomeier** [comment]
Hi @weaverba137, we may have a volunteer to work on this in a Scipy sprint; just wondering if you had already something coded, or tips how to implement this. Just in case you're reading this before tomorrow noon Eastern.

**Comment by weaverba137** [comment]
In principle the fix is petty simple:
```python
if data._gap > 0:
    fileobj.write((data._gap * '\0').encode('ascii'))
```
The trick will be to write a unit test that exercises this. That's been holding me up.

**Comment by weaverba137** [comment]
By all means go ahead with this volunteer, but the testing aspect should be emphasized.

**Comment by lastephey** [comment]
Hi Ben, thanks for the info. I'm the one who wants to work on this
tomorrow. I'm not sure how to capture this in a unit test, but I can do the
testing on our lustre filesystems at least.

**Comment by dhomeier** [comment]
As I understand the actual bug / performance penalty only shows up on filesystems that we cannot test on CI anyway.
But perhaps it's possible to check with `os.stat(file).st_atime` or perhaps rather `os.stat(file).st_mtime` if the write has been triggered. Might still be tricky enough to set up the test to isolate such a to write or not to write operation.

**Comment by dhomeier** [comment]
I actually thought one could isolate the empty write so measuring `st_mtime` would be somewhat meaningful, but since it would always immediately follow the `_writedata_by_row`, that could be hard.

Kind of a wild idea for setting up a test: create a thin wrapper for `io.open` (or subclass `BufferedRandom`?) with a `write` method that just calls
`nbytes = fh.write` on the original filehandle and then raises for `nbytes == 0` (or directly on `fh.write() == 0`)...

**Comment by lastephey** [comment]
I like your wrapper idea. Which function though? I'm looking around for an `io.open`.

**Comment by dhomeier** [comment]
The Python docs say the standard `open` is in fact an alias to `io.open`; anyway `fits.open` also works with filehandles like
```python
import io
fh = io.open('file.fits', mode='r+b')
hdulist = fits.open(fh, mode='u')
```
so if you replace `fh` with a handle created by such a custom opener, you should be done – ideally ;-)

**Comment by embray** [comment]
> The Lustre filesystem has a known issue that is triggered when zero-length writes are attempted. 

Do you have a reference for this?  I've never heard of anything like this.  Why is a zero-byte write *not* a no-op in this case?  And why would this only impact the astropy.io.fits code specifically (it sounds like this would be a problem for a *lot* of software)?

**Comment by lastephey** [comment]
Ah sorry, I see I responded in the wrong thread:

> I asked one of our NERSC Lustre experts, but there is no public issue or public information about this bug (which is also apparently related to our specific vendor deployment).

> Our lustre/IO expert believes they are not. To our knowledge, astropy is the only library where we've encountered this particular issue at NERSC, although that could be a function of how closely we have explored and profiled DESI's code.
