### ISSUE TITLE
Masked is unhashable

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11706]
### Description

``Masked`` classes are unhashable.

### Expected behavior

It is washable, like the unmasked version.

### Actual behavior

``hash(X)`` returns a TypeError because it is unhashable.

### Steps to Reproduce

```python
from astropy import units as u
from astropy.utils.masked import Masked
MQ = Masked(u.Quantity)
hash(MQ(2 * u.km))  # raises TypeError
```

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ]
Numpy 1.18.4
astropy 4.3.dev1486+gddc6fb76f.d20210505
Scipy 1.4.1
Matplotlib 3.4.1

**Comment by mhvk** [comment]
Numpy arrays also cannot be hashed. Do you particularly want to hash a Masked scalar? (for `Quantity`, this is special-cased)

```
In [4]: hash(np.arange(10.))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/work/scintillometry/psrb1929_fast/python/nut.py in <module>
----> 1 hash(np.arange(10.))

TypeError: unhashable type: 'numpy.ndarray'
```

**Comment by nstarman** [comment]
In #11559 I've been running into an unhashable MaskedConstant, which I can't even figure out how to make. I thought surfacing that Masked in general was unhashable might have the happy effect of solving MaskedConstant.

**Comment by nstarman** [comment]
@mhvk, thanks for the explanation. It makes sense that Masked wouldn't be washable where ndarray isn't... but if Quantity is hashable, it feels like MaskedQuantity should be as well.

**Comment by mhvk** [comment]
@nstarman - only Quantity scalars are hashable, which is to have an analogy with the `np.float64` scalars, etc. (even though the analogy is not perfect, since with a scalar length quantity `q += 1*u.cm` changes the object in-place, while the equivalent for a numpy scalar creates a new object). For the masked class, having a hashable object makes even less sense, I think, since the mask itself is very explicitly meant to be mutable.

**Comment by mhvk** [comment]
I checked and neither `np.ma.masked`, nor a scalar `np.ma.MaskedArray` are hashable. Since the problem that triggered this issue is unrelated, I'll close this for now.
