### ISSUE TITLE
The following Table formats cannot serialize `None`

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11710]
### Description

Formats: asdf, fits (?),
                ~hdf5~ (has no NULL)

### Expected behavior

None should be able to be written (and read).

### Actual behavior

They raise various errors complaining about serialization.

#### asdf

```python
t = table.Table(dict(a=[0], b=[None]))
t.write("temp.asdf", format="asdf", overwrite=True)
```
...
ValueError: Unknown dtype object

#### fits

```python
t = table.Table(dict(a=[0], b=[None]))
t.write("temp.fits", format="fits", overwrite=True)
```
...
ValueError: Illegal format `object`.

#### hdf5

```python
t = table.Table(dict(a=[0], b=[None]))
t.write("temp.hdf5", format="hdf5", overwrite=True)
```
...
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ]
Numpy 1.18.4
astropy 4.3.dev1486+gddc6fb76f.d20210505
Scipy 1.4.1
Matplotlib 3.4.1

**Comment by saimn** [comment]
Why should None be supported if the file format cannot handle it ?

**Comment by nstarman** [comment]
For some of them it might not. I haven't looked deeply into whether this is an Astropy translation issue or the file format itself. 

Looking at ASDF, this appears to be Astropy. I took the example from https://asdf.readthedocs.io/en/stable/asdf/overview.html#creating-files and put in a None. It saves fine.

<img width="497" alt="Screen Shot 2021-05-06 at 13 16 55" src="https://user-images.githubusercontent.com/8949649/117339097-596e4800-ae6d-11eb-8037-ebe7c82e7e57.png">

For HDF5, online docs say there is no native NULL value, so it would seem to be the file format that cannot handle None.

**Comment by pllim** [comment]
When it comes to `asdf`, I need to cc @eslavich or @jdavies-st .

**Comment by eslavich** [comment]
ASDF does support null values in the tree, but not in an ndarray, which is how `Table` is serialized.  Here's a more relevant example:

```python
import asdf
import numpy as np

tree = {
  "array": np.array([None])
}

af = asdf.AsdfFile(tree)

af.write_to('example.asdf')
```

This fails with the same ValueError:

```
ValueError: Unknown dtype object
```

**Comment by nstarman** [comment]
I see, so ASDF cannot serialize numpy object arrays. Does this mean Astropy can't save tables with a Time or other mixin column to ASDF?

**Comment by eslavich** [comment]
astropy implements special support for serializing the mixin column types to ASDF.  A `Time` column is written as an ndarray of values plus additional format and scale fields.

**Comment by jdavies-st** [comment]
`None` is not the same dtype as an integer or float.  If you'd like it to be, you can specify the dtype when you construct the numpy array, and numpy will convert it for you.  (It gets converted to `nan`.)

```
In [1]: import numpy as np

In [2]: np.array((1, 2, None, 3.0))
Out[2]: array([1, 2, None, 3.0], dtype=object)

In [3]: np.array((1, 2, None, 3.0), dtype=float)
Out[3]: array([ 1.,  2., nan,  3.])
```

And to be clear, numpy will allow you to put any object into an array, but the dtype for that array will always be an object.  No serializer will know how to serialize any random object, so it's always good to be explicit.  As an example, I can stuff an astropy WCS object in my numpy array, but I should not expect that to be serializable in a numpy table.

```
In [6]: from astropy.wcs import WCS

In [7]: np.array((1, 2, WCS(), 3.0))
Out[7]: 
array([1, 2, WCS Keywords

             Number of WCS axes: 2
             CTYPE : ''  ''
             CRVAL : 0.0  0.0
             CRPIX : 0.0  0.0
             PC1_1 PC1_2  : 1.0  0.0
             PC2_1 PC2_2  : 0.0  1.0
             CDELT : 1.0  1.0
             NAXIS : 0  0             , 3.0], dtype=object)
```

Workarounds are to explicitly specify dtypes for columns when you construct the table.  If you do so, the `Table` constructor will actually cast these for you as above.

```
In [15]: t = Table(dict(a=[0], b=[None]), dtype=[float, float])

In [17]: t
Out[17]: 
<Table length=1>
   a       b   
float64 float64
------- -------
    0.0     nan
```

And the above will write out just fine to asdf or fits formats.

**Comment by nstarman** [comment]
thanks @jdavies-st for the clear explanation. It sounds like it would be too much of an edge case to specifically support None columns.

**Comment by pllim** [comment]
What's wrong with the good ol' `-999`?

**Comment by pllim** [comment]
Hi humans :wave: - this issue was labeled as **Close?** approximately 3 months ago. If you think this issue should not be closed, a maintainer should remove the **Close?** label - otherwise, I will close this issue in 7 days.

*If you believe I commented on this issue incorrectly, please report this [here](https://github.com/pllim/action-astropy-stalebot/issues)*

**Comment by pllim** [comment]
Ops... Bot comment is accurate but I used the wrong API key. 😅

**Comment by nstarman** [comment]
I suppose we can close this. The problems remain, but I think it's a ``won't-fix`` since the underlying formats don't support the serialization.
