### ISSUE TITLE
`SphericalCircle` should accept a coordinate object for its `center` 

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#11719]
### Description

`astropy.visualization.wcsaxes.SphericalCircle` should accept a coordinate object for its `center` parameter. `center` is a tuple of two angle objects, describing the position on the sky, e.g. RA, DEC. In other words, it's a "coordinate". I suggest the `SphericalCircle` should accept a coordinate object.

### Additional context

I typically use the `SphericalCircle` for mark the position of sources in my image. That means I typically have coordinate objects already. saying `circle=(myobject.ra, myobject.dec)` is not a big deal, but `circle=myobject` is what I would expect to work.

**Comment by hamogu** [comment]
Sure, please go ahead. Do you know how to get started? 
https://docs.astropy.org/en/latest/development/workflow/development_workflow.html has an intro of steps to get the code from git etc. Feel free to ask here or on slack if you need help!

**Comment by AthulJoshi** [comment]
@hamogu I've tried implementing the feature, PTAL whenever you're free :D
