### ISSUE TITLE
Add a way to rotate labels in a wcsaxis plot

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#11721]
### Description

Coordinates can be long as a string, often leading to overlapping labels on the x axes of a wcs acis plot. One way to deal with that problem is the simply leave out some of the labels with `lon.set_ticklabel(exclude_overlapping=True)`, however another way (which I personally would prefer) would be to rotate the labels a bit by e.g. 30 deg. For "normal" matplotlib plots, I can do this with `ax.set_xticklabels(xlabels, rotation= )` or `ax.tick_params(axis='x', labelrotation= )`, but I failed to make that work with wcsaxis plots. Either it can't be done, or I don't know how to get the right object that's the equivalent of the xticklables. I

So, this is a feature request to make that work, or, if it can be done already, to add an example to https://docs.astropy.org/en/latest/visualization/wcsaxes/ticks_labels_grid.html

### Example
I'm not providing a minimal working example with attached image data here, since "rotate the labels" can be really be done with any images, for example those used in the documentation. I'm just attaching one image that shows tha the labels overlap at at least one location for every subplot.
![image](https://user-images.githubusercontent.com/498688/117689017-57ff9100-b187-11eb-9b13-94c39f4bd08e.png)

**Comment by keflavich** [comment]
I also found that label rotation is possible, e.g.,:
```python
ra.set_ticklabel(rotation=45)
```

@hamogu can we close this?
