### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [astropy/astropy#11731]
Problem
---------
On aarch64, pip install astropy builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install astropy should download the wheels from pypi

@saimn,  Please let me know your interest on releasing aarch64 wheels. I can help in this.

Blocked by
------------

* Inability to use OpenAstronomy reusable workflow on a paid runner across different orgs. See https://github.com/OpenAstronomy/github-actions-workflows/issues/227

**Comment by pllim** [comment]
Good news: Astropy org now pays for a private aarch64 runner that could be used to make such a wheel.

Bad news: https://github.com/OpenAstronomy/github-actions-workflows/issues/227

**Comment by astrofrog** [comment]
Oh wait we already publish aarch64 wheels so this can be closed. We just don't test them but that's ok as we have tests in the extras CI so it's likely good enough.

**Comment by pllim** [comment]
Oh yeah... 

https://github.com/astropy/astropy/blob/fe293ffa1a844e51be31abab3e25e3762b451ba4/.github/workflows/publish.yml#L77-L79
