### ISSUE TITLE
Make _fitter_to_model_params public available to all users

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#11735]
When subclassing fitters in order to override the `objective_function` method, one needs to use `_fitter_to_model_params` (or, alternatively implement a long hack). It is unfortunate that this function is "private" (`_`) and this poses some dangers when subclassing this class.

Would it be possible to make it public?

**Comment by WilliamJamieson** [comment]
@mcara, I have also run into this issue a few times, so I have created a PR which makes them public.
