### ISSUE TITLE
Cannot get `separability_matrix` for a custom model

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#11742]
### Description
Trying to get the `separability_matrix` for a `custom_model` fails. In the example below, I have what I believe is a separable model (the outputs each only depend on one input), so the matrix should be the identity matrix.

### Expected behavior
A matrix to be returned (or perhaps a more user friendly error message if this isn't possible).

### Actual behavior
Non-user-friendly error (see below)

### Steps to Reproduce
```python
from astropy.modeling import custom_model
from astropy.modeling.separable import separability_matrix


def my_func(x, y):
    return x**2, y**2


my_model = custom_model(my_func)
my_model.separable = True
my_instance = my_model()
print(my_instance.separable)
print(separability_matrix(my_instance))
```
Output:
```python
True
Traceback (most recent call last):
  File "/Users/dstansby/github/astropy/test.py", line 13, in <module>
    print(separability_matrix(my_instance))
  File "/Users/dstansby/github/astropy/astropy/modeling/separable.py", line 100, in separability_matrix
    separable_matrix = _separable(transform)
  File "/Users/dstansby/github/astropy/astropy/modeling/separable.py", line 309, in _separable
    return _coord_matrix(transform, 'left', transform.n_outputs)
  File "/Users/dstansby/github/astropy/astropy/modeling/separable.py", line 213, in _coord_matrix
    mat[i, i] = 1
IndexError: index 1 is out of bounds for axis 0 with size 1
```
### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.9.1 (default, Dec 11 2020, 06:28:49) 
[Clang 10.0.0 ]
Numpy 1.19.3
astropy 4.3.dev1341+g79fb275ee
Scipy 1.5.4
Matplotlib 3.4.1.post687+gca2abb318.d20210513

**Comment by pllim** [comment]
Maybe @nden or @perrygreenfield can advise.

**Comment by dstansby** [comment]
Ah, it turns out I shouldn't have been creating an instance, since the factory function `custom_model` returns an instance (and not a class). Creating an instance fixes the code.

**Comment by dstansby** [comment]
Ha, I am wrong, but `separabiltiy_matrix` currently just returns `True` when called on an Model class (as opposed to an instance), so I think this is actually still a bug.
