### ISSUE TITLE
Add milli- prefix to Angstrom unit

### ISSUE THREAD

**Issue by byrdie** [astropy/astropy#11745]
### Description

Is there a particular reason that SI prefixes are disabled for the Angstrom unit?
I am working on a project that prefers to describe the dispersion of a spectrograph in milliangstroms per pixel, and not having this unit is becoming tedious.
I realize the Angstrom is not an SI unit, but I think there is an argument to be made to add at least the milli- prefix.

**Comment by embray** [comment]
I do believe this is pretty non-standard, though I also see it is used in some papers, especially related to x-ray spectroscopy.

I'd lean against allowing arbitrary SI units with Angstrom, but I'll let the experts bikeshed over that.  However, in the meantime, you can define your own like:

```python
mAA = def_unit(['milliAngstrom', 'mAA', 'milliangstrom'], 1e-3 * u.AA,
               format={'latex': r'm\mathring{A}', 'unicode': 'mÅ'})
```

Now you can use `mAA` in any calculations with units, and it will work as expected.  However, if you want to do reductions to units of mÅ it might take a bit more finessing.

**Comment by dhomeier** [comment]
> I'd lean against allowing arbitrary SI units with Angstrom, but I'll let the experts bikeshed over that.

I don't think this is arbitrary at all, in my experience it is (or historically has been) fairly standard use in any contexts with corresponding spectral resolution. Might perhaps need some justification why we allow one specific SI prefix, but no others (but certainly would not want to open this to abuse like DÅ or cÅ ;-).

**Comment by mhvk** [comment]
I've seen it too, which I think makes enough of us to enable just the milli prefix. @byrdie - would you be willing to make a PR? Just change the angstrom definition in `astropy/units/si.py` to have the same prefix definition as `bar` in `astropy/units/misc.py`.
