### ISSUE TITLE
Documentation links broken (use latest, not stable, for dev docs)

### ISSUE THREAD

**Issue by mdecleir** [astropy/astropy#11754]
I noticed that certain links to the Astropy documentation, which recently worked, are now broken:
- https://docs.astropy.org/en/stable/development/testguide.html
- https://docs.astropy.org/en/stable/development/codeguide.html
- https://docs.astropy.org/en/stable/testhelpers.html

We use some of those links in the documentation of our own repo's, e.g. here: https://measure-extinction.readthedocs.io/en/latest/

Updating them to "latest" instead of "stable" fixed our problem, but I thought I should put an issue in anyway (as @eteq suggested).

**Comment by mdecleir** [comment]
> I noticed that certain links to the Astropy documentation, which recently worked, are now broken:
> 
> * https://docs.astropy.org/en/stable/development/testguide.html
> * https://docs.astropy.org/en/stable/development/codeguide.html
> * https://docs.astropy.org/en/stable/testhelpers.html
> 
> We use some of those links in the documentation of our own repo's, e.g. here: https://measure-extinction.readthedocs.io/en/latest/
> 
> Updating them to "latest" instead of "stable" fixed our problem, but I thought I should put an issue in anyway.

**Comment by mdecleir** [comment]
(Sorry, I accidentally closed this issue).

**Comment by pllim** [comment]
Moving dev docs to `latest` only was a conscious decision. See #11342 .

You can trying using the "astropy-dev" intersphinx like in #11622 . Maybe @embray can advise.

Not sure what to fix here, except maybe an official memo to the astropy-dev mailing list?

**Comment by embray** [comment]
Ah, we should have set up some redirects when making that move.  Sorry for the hassle @mdecleir 

I've added redirects in readthedocs for all those pages, so that the old links (with `/stable/`) redirect to `/latest/`.  This will be good to keep in mind as well as I work on #11621.  I'll see if I can maintain redirects to any old pages if they get moved around.  The [sphinx-redirects](https://pypi.org/project/sphinx-reredirects) package may help with this as well.

**Comment by pllim** [comment]
Perhaps setting up redirect should be in the dev docs for, uh, docs somewhere? Since this does not happen often, I would often forget this needs to be done when I move docs around in the future.
