### ISSUE TITLE
_BaseDiff evaluates to incorrect boolean

### ISSUE THREAD

**Issue by eigenbrot** [astropy/astropy#11773]
Astropy 4.2.1

Consider the following:
```
>>> h1 = fits.Header()
>>> if fits.HeaderDiff(h1, h1): print('These are the same')
... 
>>> 
```

Nothing is printed. 

The culprit is in `_BaseDiff.__bool__`:
https://github.com/astropy/astropy/blob/e183e398d8bdbbe5c7ccec7a793afed2ecdac4e1/astropy/io/fits/diff.py#L74-L80

Despite the docstring (and other documentation) suggesting that identical objects evaluate to `True` the return value here is `not self.identical`.

I tried making a quick fix to this but it broke 19 tests in `io.fits` so I figured I'd better leave this to the professionals :)

**Comment by pllim** [comment]
Maybe the docstring is wrong. I interpret that when `bool(diff)` is `True`, there is a difference, and `False` when there is no difference (i.e., things are the same). @saimn or @embray , what do you think?

**Comment by saimn** [comment]
Agreed with @pllim !

**Comment by embray** [comment]
Yes, `HeaderDiff(...) is True` means there *is* a difference.  The docstring is wrong.

**Comment by pllim** [comment]
@eigenbrot , are you interested to open a pull request to fix the docstring? Good catch! 😺

**Comment by eigenbrot** [comment]
Yep! My plan is to work on this and #11770. Hopefully somewhat soon. If someone wants to assign this issue to me I'm fine with it!
