### ISSUE TITLE
Redshift Unit

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11784]
### Description

It's a dimensionless unit that useful for redshift-related equivalencies, like redshift-dimensionless, and cosmology-dependent conversions like redshift-temperature, redshift-distance.
From discussion with @mhvk and @adrn. 

Would also be useful for cosmology calculations to return instead of a float.

**Comment by pllim** [comment]
We already have https://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.RedshiftScaleFactor.html#astropy.modeling.functional_models.RedshiftScaleFactor .

**Comment by adrn** [comment]
@pllim ?? Unless I do'nt understand `RedshiftScaleFactor`, I think the context is very different! We're talking about a new dimensionless unit meant to mark that a quantity is a special kind of dimensionless (i.e. a redshift), not a new class or functional form to compute a scale factor from a redshift.

**Comment by pllim** [comment]
Hmm, ok. But how will it work with our redshift model?
