### ISSUE TITLE
`in_observer_velocity_frame` not defined?

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#11780]
Where is `in_observer_velocity_frame` defined?  It shows up several times in fitswcs

https://github.com/astropy/astropy/blob/main/astropy/wcs/wcsapi/fitswcs.py#L505
https://github.com/astropy/astropy/blob/main/astropy/wcs/wcsapi/fitswcs.py#L528
https://github.com/astropy/astropy/blob/main/astropy/wcs/wcsapi/fitswcs.py#L559

but it doesn't appear to be defined anywhere.  Is it autogenerated somewhere, or is this a bug?

Note that this is causing users some actual issues, e.g.:
https://github.com/1054/Crab.Toolkit.CASA/blob/14d6bf1c1a268cad9336d4c7c1583fc892ddab4a/bin/a_dzliu_code_run_linear_mosaic_in_python_2_use_reproject_do_not_use.py#L150

`AttributeError: SpectralCoord instance has no attribute 'in_observer_velocity_frame'`

cc @astrofrog as this affects `reproject` directly, and `spectral-cube` indirectly.  Also, you made the change in https://github.com/astropy/astropy/commit/e541cef2cffbd4d18b02847d6d1418b3b9d86d98.

See also https://github.com/astropy/astropy/pull/10185

**Comment by eteq** [comment]
closing manually because of a missing `#` in #11781 - but to clarify what I think the real problem was here for posterity: I think that method was re-named but the re-naming never got updated!
