### ISSUE TITLE
What to do when `n_outputs` is given to `custom_model`?

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#11791]
In https://github.com/astropy/astropy/pull/11744#discussion_r639075503 an example piece of code was provided that gives `n_outputs` as a parameter to a `custom_model`. This appears to override the [`.n_outputs`](https://docs.astropy.org/en/stable/api/astropy.modeling.Model.html#astropy.modeling.Model.n_outputs) property with a `Parameter` object, which then causes issues with other methods.

So, what should happen when `n_outputs` is passed as a parameter? Should there be a banned/reserved list of parameter names, including `n_outputs`, that error?

```python
from astropy.modeling import custom_model, separability_matrix


@custom_model
def model(x, y, n_outputs=2):
    return x+1, y+1

m = model()
print(m.n_outputs)  
# Parameter('n_outputs', value=2.0)
print(separability_matrix(m))
# Errors, with the error message below
```
```python
Traceback (most recent call last):
  File "/Users/dstansby/github/astropy/test.py", line 11, in <module>
    print(separability_matrix(m))
  File "/Users/dstansby/github/astropy/astropy/modeling/separable.py", line 100, in separability_matrix
    separable_matrix = _separable(transform)
  File "/Users/dstansby/github/astropy/astropy/modeling/separable.py", line 309, in _separable
    return _coord_matrix(transform, 'left', transform.n_outputs)
  File "/Users/dstansby/github/astropy/astropy/modeling/separable.py", line 204, in _coord_matrix
    mat = np.zeros((noutp, model.n_inputs))
TypeError: 'Parameter' object cannot be interpreted as an integer
```

**Comment by pllim** [comment]
cc @nden and @perrygreenfield

**Comment by WilliamJamieson** [comment]
@dstansby I just opened PR #11984 which addresses this issue. I welcome your comments on it.
