### ISSUE TITLE
`fits.getdata` overrides `ext=0` argument

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#11795]
### Description
Reported in the Facebook group:
For an HDUList with empty primary HDU, getdata intransparently returns data from the first extension, even if called explicitly as `fits.getdata(filename, ext=0)`.

### Expected behavior
Should raise an exception or at most return `None` as `hdulist[0]` has no data.

### Actual behavior
Returns data array, which turns out to be `hdulist[1].data`.

### Steps to Reproduce
See above and [Facebook post](https://www.facebook.com/photo/?fbid=2974167039576138)

This is caused by the fallback in
https://github.com/astropy/astropy/blob/c58ad0a6590d591b7b43cbd155b43891e9b44f6e/astropy/io/fits/convenience.py#L193-L206

There are a number of problems with this:
1. The docs state that the extension has to be specified or defaults to the primary HDU only.
2. Defaulting to the first non-empty HDU is reasonable, but only if no other has been explicitly requested, i.e. for the (default) `ext=None`. But since `_getext` already expanded `ext=None` to `extidx=0` that bit of information is lost at that point. Also _if_ looking for an HDU with data, there is no reason not to proceed all the way unto the first non-empty HDU rather than just to no. 1 (although there might be no sensible use case of a FITS file with an empty extension HDU).
3. The exceptions and error messages are misleading; the first states "No data in this HDU." when no HDU exists at that index, the second raises an `IndexError` when in fact there are no data (which probably should be a `ValueError`?).

Since it is not documented, it might make sense to remove that fallback altogether, but as it may still have been used, it could also be fixed and adequately documented (this would probably require saving the original `ext` setting from the `getdata` *args).

### System Details
Confirmed with 4.2.1 on macOS 10.14

**Comment by daria-cara** [comment]
I'd like to work on this issue. I'll make a PR shortly.
