### ISSUE TITLE
Stretched norm behaviour broken on development `Matplotlib`

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#11800]
### Description
Using a stretch norm is different on the development version of `Matplotlib`. The issue (see below for an example) bisects to the following change in Matplotlib: https://github.com/matplotlib/matplotlib/commit/146856b03e85aa4b1becdd89fe1628f98fed2a05, part of https://github.com/matplotlib/matplotlib/pull/20054. It's not clear to me whether this is something that needs to be fixed in Matplotlib, or something needs changing in astropy.

### Steps to Reproduce

```python
import matplotlib.pyplot as plt
import numpy as np

from astropy.visualization import ImageNormalize, AsinhStretch

fig, ax = plt.subplots(figsize=(6, 2))
data = np.atleast_2d(np.linspace(0, 0.9, 10))
# data == [[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]]
im = ax.imshow(data, norm=ImageNormalize(vmin=0, vmax=1, stretch=AsinhStretch()), cmap='prism')
fig.colorbar(im, orientation='horizontal')
plt.show()

```

### Image before Matplotlib change:
![before](https://user-images.githubusercontent.com/6197628/120030999-13ca1880-bff0-11eb-951a-a8580f3c979c.png)

### Image after Matplotlib change:
![after](https://user-images.githubusercontent.com/6197628/120031021-1a589000-bff0-11eb-99f5-089c61f1a4ec.png)

Note how the colorbar is now stretched insetad of the ticks.

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.9.1 (default, Dec 11 2020, 06:28:49) 
[Clang 10.0.0 ]
Numpy 1.19.3
astropy 4.3.dev1547+gb52c40715
Scipy 1.5.4
Matplotlib 3.4.2.post948+g08f4629d91

**Comment by pllim** [comment]
Hmm... How did our devdeps CI not catch this?

**Comment by jklymak** [comment]
Can you explain a little bit more about your "normalization" above?  Your colorbar scale has changed, but the normalization seems completely linear.   e.g. your 0.6 tick has moved up the colorbar in the first image but seems to point to the color that would be 0.6 in a linear normalization. Under a usual normalization I'd expect 0.6 to map to somewhere different in the colormap.  i.e. `Norm(vmin=0, vmax=1)(0.6) != 0.6`

**Comment by jklymak** [comment]
OK, I see now, stretch is somehow stretching the axes scale.  I don't know how you were moving the ticks around with your "stretch" keyword arg, but the usual way to "stretch" an axes like this in matplotlib is to use `ax.set_yscale()`, which now works for colorbars, since matplotlib/matplotlib#20054.    Of course the default scale is the one set by the Norm, but we now support keeping the norm the same and changing the scale of the colorbar, which seems to be exactly what your "stretch" is doing.  To make this work with the unreleased matplotlib I think we would simply need to figure how to make your stretch pass down to set_scale.

**Comment by dstansby** [comment]
Thanks for helping out over here! I've updated the original post with a clearer example, with the data being `[0, 0.1, 0.2, 0.3,...]`. In the first panel the colorbar tick labels correspond to the correct colors, but in the second panel the ticks aren't placed in the right place at all.

It don't think any of the ticks were being moved around by astropy - only `__call__`, `inverse`, `_set_limits` and `__init__` are defined on the `ImageNormalize` class. So I guess before and after Matplotlib was choosing ticks at [0, 0.2...], but now the tick locations aren't being properly set on the colorbar axes.

**Comment by jklymak** [comment]
OK, I was confused by your first plot before the edit.  Sorry.  

I don't understand why this would be the case.  Can we make a quick non-astropy mock-up and move to matplotlib?

**Comment by jklymak** [comment]
Actually thats OK, I can repo...

**Comment by dstansby** [comment]
I take back my previous comment - I have updated the original example again, with a less-perceptually uniform colormap (probably the only time I'd advocate using this!!!), and I have fixed the data generation so it is actually [0, 0.1, 0.2...]. The mapped colors are correct both before and after (this is good!), but the difference is before the ticks are stretched, whereas after the colors are stretched.

So, not as big a problem as I thought it might be (the ticks are 'correct' in both cases), but worth working out if this is a desired behaviour change or not...

**Comment by jklymak** [comment]
No, its definitely broken.  See matplotlib/matplotlib#20324 for an easy-to-see example.  We'll definitely fix on our end, though I'm not sure if we can or want to make it visually the same as before.  But the ticks should point to the right colors ;-)

On astropy's end, you may want to consider creating your norm from a scale, though I note that Matplotlib does not seem to have a public API for that.  But see `colors._make_norm_from_scale`.  If you do that, the colorbar will use the scale's ticker.

**Comment by pllim** [comment]
Re: `colors._make_norm_from_scale` -- Is it advisable to use a "hidden" matplotlib function? Or are you suggesting, we copy-paste the entire code over here?

**Comment by jklymak** [comment]
Probably matplotlib should make the helper public. 

But don't get me wrong we (Ie me) should not have broken this and it will be fixed before release, if not in the next couple days.

**Comment by pllim** [comment]
Thank you for the swift reponses! 🙇

**Comment by jklymak** [comment]
@dstansby or @pllim 95% sure #20327 will work with your Norm the way you expect.  Sorry for the bother, and very *very* much appreciate you testing our dev branch!

**Comment by dstansby** [comment]
I'm still getting the same changed result (the "after" image in the original post) with your PR branch and the `astropy` norm. But, this seems to be because the astropy norms inherit from `Normalize`, which has `self._scale` set to a linear scale.

If I add `self._scale = None` to the `__init__` in astropy norms, the issue is fixed (with https://github.com/matplotlib/matplotlib/pull/20327). But that's private mpl API, so I'm not too sure about doing that in astropy. I think it might be the pragmatic fix for now though?

**Comment by jklymak** [comment]
OK, adding the default to Normalize was my fault actually.  We should prob make the default None, and then if its still None when a colorbar gets drawn it defaults to Linear...

**Comment by pllim** [comment]
I see that matplotlib/matplotlib#20324 is closed. Does that mean this is no longer an issue?

**Comment by jklymak** [comment]
#20327 was merged, so it _should_ fix this.  If not, let us know!

**Comment by pllim** [comment]
@dstansby , can you please confirm?

Also, the way I understood things, there is nothing to do on `astropy` side, correct? Thanks!

**Comment by dstansby** [comment]
To fix there's nothing to do on the astropy side, but if astropy tests against Matplotlib dev a test should probably be added so this kind of bug is caught in the future - initially I found the bug in sunpy tests, and then isolated it to astropy.

**Comment by jklymak** [comment]
See https://github.com/matplotlib/matplotlib/pull/20405

**Comment by pllim** [comment]
@dstansby , are you interested to open a PR here? 😸

**Comment by pllim** [comment]
Looks like upstream was fixed.
