### ISSUE TITLE
WCS pixel_to_world gives unexpected result

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#11808]
### Description

A simple WCS transform using `pixel_to_world` appears to give the wrong answer transforming x,y to RA, Dec by about one CDELT.

Note that I am a complete novice at WCS so maybe I'm just doing something wrong.

### Actual behavior

```
In [43]: evt.wcs                                                                                                                                           
Out[43]: 
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 275.48747676907  64.346729956804  
CRPIX : 32768.5  32768.5  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : -3.6611111111111e-05  3.6611111111111e-05  
NAXIS : 102  2784284

In [46]: evt.wcs.pixel_to_world(32768.5, 32768.5)                                                                                                          
Out[46]: 
<SkyCoord (ICRS): (ra, dec) in deg
    (275.4873922, 64.34676657)>  # WRONG (does not match CRVAL)
```

### Steps to Reproduce

I made the `WCS` object by initializing from the FITS header of a Chandra event file. If it is really required to reproduce then I can do that, but I suspect either I am doing something wrong or that there is an easier way.

### System Details

```
macOS-10.16-x86_64-i386-64bit
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ]
Numpy 1.18.5
astropy 4.2
Scipy 1.5.0
Matplotlib 3.2.2
```

**Comment by pllim** [comment]
`wcslib` was updated in 4.3 (unreleased). Did you test with astropy dev?

**Comment by taldcroft** [comment]
Actually my "novice" statement is relevant since I discovered I was interpreting the variable args in `wcs_pix2world` wrong. It was casting my `False` and `True` to float values that specify the origin (type checking!).

However, the more critical bug that `wcs.pixel_to_world` seems to be giving the wrong answer is still relevant.

**Comment by taldcroft** [comment]
I think this is coming down to the definition of the origin. Maybe the Chandra event file WCS is using an origin of 0 instead of the apparent FITS standard of 1. 

In CIAO and ds9, (32768.5, 32768.5) corresponds exactly to the CRVAL values, while the default in astropy seems to be CRVAL + 1.0 * CDELT. Go figure.

**Comment by mcara** [comment]
I am not sure what is the critical bug here - I get perfect agreement:
```python
In [14]: np.array(w.pixel_to_world_values(32768.5 - 1, 32768.5 - 1)) - w.wcs.crval
Out[14]: array([0., 0.])
```
Notice, I had to subtract 1 pixel because in defining WCS, `CRPIX` is _always_ 1-based while `pixel_to_world()`'s  input coordinates are always 0-based

**Comment by taldcroft** [comment]
What I'll say is that if I use CIAO or DS9 to convert from `x, y` pixel coords to world (RA, Dec), I get the "correct" answer, while blindly using `wcs.pixel_to_world` using a `wcs` object created from a Chandra FITS event file gives the wrong value by one CDELT. 

I am beginning to understand now  this `origin` issue but the question is whether the high-level interface should allow specifying that or whether there should be some indication in the FITS header of the origin?

**Comment by mcara** [comment]
> whether there should be some indication in the FITS header of the origin?

**Comment by mcara** [comment]
> whether there should be some indication in the FITS header of the origin?

No, FITS WCS standard is clear: CRPIX is 1-based. There is no need to specify anything in FITS header.

[Just a wild guess; but those with more historical knowledge will hopefully correct me] The `origin` was likely introduced as a convenience for Python users for whom source coordinates or pixel indices are more likely to be 0-based. 

`pixel_to_world` is a part of "A shared Python interface for World Coordinate Systems" that uses a different convention compared to "native/old" `astropy.wcs.WCS` functions such as `wcs_pix2world` - see pixel convention here https://github.com/astropy/astropy-APEs/blob/main/APE14.rst#pixel-conventions
