### ISSUE TITLE
TST: TestQuantityReshapeFuncs.test_flat_attributes failed with AssertionError on s390x (big-endian)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11804]
Example log: https://github.com/astropy/astropy/runs/2708622607?check_suite_focus=true

Last week's run was successful (https://github.com/astropy/astropy/runs/2653579480?check_suite_focus=true) on 2021-05-24.

```
________________ TestQuantityReshapeFuncs.test_flat_attributes _________________

self = <astropy.units.tests.test_quantity_array_methods.TestQuantityReshapeFuncs object at 0x42b00b16a0>

    def test_flat_attributes(self):
        """While ``flat`` doesn't make a copy, it changes the shape."""
        q = np.arange(6.).reshape(3, 1, 2) * u.m
        qf = q.flat
        # see TestQuantityArrayCopy.test_flat for tests of iteration
        # and slicing and setting. Here we test the properties and methods to
        # match `numpy.ndarray.flatiter`
        assert qf.base is q
        # testing the indices -- flat and full -- into the array
        assert qf.coords == (0, 0, 0)  # to start
        assert qf.index == 0
        # now consume the iterator
        endindices = [(qf.index, qf.coords) for x in qf][-2]  # next() oversteps
>       assert endindices[0] == 5
E       assert 0 == 5

astropy/units/tests/test_quantity_array_methods.py:138: AssertionError
```

Could this be related to #11796 , @mhvk or @nstarman ?

Also see #11783, numpy/numpy#19153

**Comment by nstarman** [comment]
It looks related. That's a strange error. What is s390x?

**Comment by pllim** [comment]
It is one of the architectures we test against in https://github.com/astropy/astropy/blob/main/.github/workflows/ci_cron_weekly.yml

**Comment by mhvk** [comment]
`s390x` is an IBM platform. Main difference is that it is bigendian.

**Comment by mhvk** [comment]
I suspect this may well be a numpy bug - I just do not see how what you exposed in #11796 could cause a problem if a similar test on a numpy array would pass.

Thinking about how to verify this, perhaps one idea is to check whether numpy tests this, and if they do not send a PR to them with a similar test, and see if it passes! ....  except that they do not seem to test on bigendian ... So short of creating one's own virtual big-endian machine with qemu or so, perhaps the easiest would be to experiment on astropy, making a PR and turn on the label "extra CI". Tricky!

**Comment by pllim** [comment]
I think it is fine to use "Extra CI" in `astropy` as a first step, but please mark it as a Draft PR so merge is disabled. Thanks!

**Comment by nstarman** [comment]
I'm getting a pytest error when doing ``>>> pytest astropy/`` on main branch. Can anyone confirm?
Sigh. I guess I'll do a full `tox`

Error: ``ImportError: dynamic module does not define module export function (PyInit__parse_times)``

**Comment by nstarman** [comment]
@pllim @mhvk, let's say it is NumPy. In addition to raising an issue there, is there a flag I can put on that test to skip only on s390x?

**Comment by pllim** [comment]
I guess you could check for it somehow with `sys.platform` but given this cron job is weekly, if things can turn around within a week or two, it is not worth skipping.

**Comment by pllim** [comment]
Looks like numpy/numpy#19153 is marked as a bug and slated to be fixed in Numpy 1.22. So, for now, perhaps we can xfail this test for `numpy<=1.21`?

**Comment by pllim** [comment]
Update: numpy/numpy#19276 is merged but no change on our side should be required.

**Comment by mhvk** [comment]
Yes, hopefully, things will just work with numpy-dev!
