### ISSUE TITLE
Utility function for ftool-style FITS extension specification in astropy.io.fits?

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#1182]
At the moment I'm writing a bunch of FITS command line tools using `astropy` and I'd like to support the ftools-style (or is this in CFITSIO?) way of specifying which extensions to process, i.e. via a string `file_name[extension_name]`.

@iguananaut I think it would it be useful to add a convenience function to `astropy.io.fits` like

```
file_hdu_name = 'file_name[extension_name]'
hdu = fits.get_hdu(file_hdu_name)
```

If the FITS file only contains one HDU then this should also work:

```
file_hdu_name = 'file_name'
hdu = fits.get_hdu(file_hdu_name)
```

Or maybe the behaviour of the `open`, `getdata`, `getheader` functions could be changed so that if `[` and `]` appear in the filename, this is taken as the extension name automatically?

This parsing is really easy to implement, so not a very big deal to write myself, but I think it's maybe common enough to be put in the astropy core?

Here's an example that illustrates what I mean (`fitsdiff` is a command line tool that comes with astropy, `ftdiff` is an [ftool](http://heasarc.gsfc.nasa.gov/ftools/):

```
$ fitsdiff derivedMaps_0.2.fits[Excess] derivedMaps_0.2.fits[Excess]
ERROR: Wildcard pattern 'derivedMaps_0.2.fits[Excess]' did not match any files.
$ ftdiff derivedMaps_0.2.fits[Excess] derivedMaps_0.2.fits[Excess]

              ftdiff V1.36

derivedMaps_0.2.fits[11] <     derivedMaps_0.2.fits[11] > 


No differences
=========================================

**** End of file comparison:  0 differences were found
```

**Comment by embray** [comment]
Here's a very old issue that should either be closed or done something about.  After more consideration, I think this would be good to have in one specific case: It should not exist anywhere in the normal Python APIs (too confusing).  But there are a number of FITS-related command-line utilities included with Astropy, some of which are based on tools from IRAF.  These include:

* `fits2bitmap`
* `fitscheck`
* `fitsdiff`
* `fitsheader`
* `fitsinfo`

I think at the CLI level we could support this syntax very easily.  A single utility function could handle parsing this syntax for all the CLI utilities, though I would not make it a public function.

**Comment by pllim** [comment]
Unless @cdeil still feels strongly about having these commands, I'd say, we close it...
