### ISSUE TITLE
u.format.fits.Fits.to_string() throws the wrong exception with bad argument

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#11825]
### Expected behavior

An bad unit argument in `u.format.fits.Fits.to_string()` should raise a `TypeError` (or a `ValueError` if the type is correct).

### Actual behavior

It raises an `UnboundLocalError`

### Steps to Reproduce

```python
import astropy.units as u

u.format.Fits.to_string(None)
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/astropy/units/format/fits.py", line 137, in to_string
    return s
UnboundLocalError: local variable 's' referenced before assignment
```
Reason is that `astropy/units/format/fits.py` only assign `s` for certain input types (line 110ff):
```python
    @classmethod
    def to_string(cls, unit):
        # Remove units that aren't known to the format
        unit = utils.decompose_to_known_units(unit, cls._get_unit_name)
        parts = []
        if isinstance(unit, core.CompositeUnit):
            […]
            s = ' '.join(parts)
        elif isinstance(unit, core.NamedUnit):
            s = cls._get_unit_name(unit)
     
        return s
```
IMO `utils.decompose_to_known_units()` should raise an exception (currently, it returns `None` as it has the same `if…elif` logic), or this should be done in `Fits.to_string()`. I would even add in both
```python
        else:
            raise TypeError(f'Illegal type {unit.class.name}')
```
so that one still holds when the other is missed :-)

BTW, the list `[core.CompositeUnit, core.NamedUnit]` is also not complete: `u.format.fits.Fits.to_string(u.ABmag)` shows the same behaviour, although `u.ABmag` is an Astropy unit.

### System Details

That is astropy 4.2, but the code didn't change in the main branch.

**Comment by jerobado** [comment]
Hello.

I tried adding the `else` clause as suggested by @olebole as follows:

```python
# ~/fits.py
def to_string(cls, unit):
       ...
    if isinstance(unit, core.CompositeUnit):
       ...
    elif isinstance(unit, core.NamedUnit):
        s = cls._get_unit_name(unit)
    else: # as suggested
        raise ValueError(f'Illegal type {unit}')

    return s

# ~/utils.py
def decompose_to_known_units(unit, func):
    ...
    from astropy.units import core
    if isinstance(unit, core.CompositeUnit):
        new_unit = core.Unit(unit.scale)
        for base, power in zip(unit.bases, unit.powers):
            new_unit = new_unit * decompose_to_known_units(base, func) ** power
        return new_unit
    elif isinstance(unit, core.NamedUnit):
        try:
            func(unit)
        except ValueError:
            if isinstance(unit, core.Unit):
                return decompose_to_known_units(unit._represents, func)
            raise
        return unit
    else: # as suggested
        raise ValueError(f'Illegal type {unit}') # I use ValueError here as per docstring
```
And here is the result:
```
>>> import astropy.units as u
>>> u.format.Fits.to_string(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jerobado/GitHub/astropy/astropy/units/format/fits.py", line 113, in to_string
    unit = utils.decompose_to_known_units(unit, cls._get_unit_name)
  File "/home/jerobado/GitHub/astropy/astropy/units/format/utils.py", line 113, in decompose_to_known_units
    raise ValueError(f'Illegal type {unit}')
ValueError: Illegal type None
>>>
```
Also, what should be in the `class` part in `{unit.class.name}` because I'm encountering a `SyntaxError`
```
  File "/home/jerobado/GitHub/astropy/astropy/units/format/generic.py", line 24, in <module>
    from . import core, utils
  File "/home/jerobado/GitHub/astropy/astropy/units/format/utils.py", line 113
    (unit.class.name)
          ^
SyntaxError: f-string: invalid syntax
```
Your thoughts and guidance are welcome.

**Comment by olebole** [comment]
I think the result looks promising; this is what I would expect. My attempt `unit.class.name` was not tested. Instead of this, you should probably use `{type(unit)}` or `{type(unit).__name__}`.

**Comment by mhvk** [comment]
@jerobado - You'd only need it in one place - and inside `decompose_to_known_units` would be most logical, as that is used by other formats as well.  You'd also need a test case - you can use the example from @olebole on top, and maybe put it in `astropy/units/tests/test_format.py`.
As for the error, since here the type of input is incorrect, `TypeError` would be better.

@olebole - the formats are not really meant to be used on their own (which is why they are not exposed at the top level), but rather through `unit.to_string(format='fits')`. Did you encounter this problem in a higher-level call as well?

**Comment by jerobado** [comment]
Thank you both for the feedback. I'll send a PR shortly.
