### ISSUE TITLE
Single quantities are iterable

### ISSUE THREAD

**Issue by matteobachetti** [astropy/astropy#11824]
### Description

I wrote a function that makes a series of operations based on a value of stellar mass. Inside the function, I have code like:

```
def myfunction(mass):
    if mass > 1 * u.M_sun:
        dothis()
    else:
        dothat()
```
This doesn't work on arrays of masses, so I added a line that, if it the mass is an iterable, uses list comprehension to calculate all the values

```
from collections.abc import Iterable
def myfunction(mass):
    if isinstance(mass, Iterable):
        print(mass)
        return ([myfunction(m) for m in mass])
    (...)
```

### Expected behavior
I expected the function above to return a list of quantities

### Actual behavior

The function fails with `TypeError: 'Quantity' object with a scalar value is not iterable`.
Digging a little, it becomes clear that `isinstance(mass, Iterable)` is returning `True` even for the single values of mass.

### Steps to Reproduce

```python
>>> import astropy.units as u
>>> from collections.abc import Iterable
>>> a = 1 * u.M_sun
>>> isinstance(a, Iterable)
True
```

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ]
Numpy 1.20.1
astropy 4.3.dev815+gcc7f83e30
Scipy 1.6.1
Matplotlib 3.4.1

**Comment by eerovaher** [comment]
This is consistent with how NumPy arrays behave.
```python
>>> import numpy as np
>>> from collections.abc import Iterable
>>> a = np.array(1)
>>> isinstance(a, Iterable)
True
>>> [elem for elem in a]
TypeError: iteration over a 0-d array
```
Checking if a `Quantity` object can actually be iterated can be done with the `astropy.utils.isiterable()` function.

**Comment by pllim** [comment]
If this has been answered to your satisfaction, please close the issue. Thanks!

**Comment by matteobachetti** [comment]
Thanks @eerovaher, ok, I see. Closing!
