### ISSUE TITLE
unit information is lost when slicing by row and column from a table

### ISSUE THREAD

**Issue by jmoldon** [astropy/astropy#11833]
### Description

When accessing a single item of a table, the unit information is lost

### Expected behavior

The unit information should always be preserved. So the result of the slice a single row and column from a `Table` should be an `astropy.units.quantity.Quantity`

### Actual behavior
If you slice a table by a single row and column, the resulting value is a `numpy.float` without units attached. When more than one row is selected, the resulting value correctly has units because it is an `astropy.table.column.Column`

### Steps to Reproduce
code
```python
from astropy.table import Table
from astropy import units as u

table = Table()
table['a'] = [0,1,2,3] * u.deg

print(type(table['a'][0]))
print(table['a'][0])

print(type(table['a'][0:1]))
print(table['a'][0:1])
```

Output
```bash
<class 'numpy.float64'>
0.0
<class 'astropy.table.column.Column'>
 a 
deg
---
0.0
```

### System Details
```bash
Linux-5.4.0-73-generic-x86_64-with-glibc2.10
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0]
astropy 4.2.1
```

**Comment by eerovaher** [comment]
This looks very similar to issue #10735. The recommendation given there (and for many other unit-related issues in tables) is to use `QTable` instead of `Table`.

**Comment by jmoldon** [comment]
Thanks for pointing this out. Since there is a workaround and this issue will not probably trigger a change on `Table` I close the issue to reduce noise. Thanks!

**Comment by pllim** [comment]
If there is any way to make the doc clearer, feel free to suggest. Thanks!
