### ISSUE TITLE
DOC: KingProjectedAnalytic1D reference link broken

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11845]
https://github.com/astropy/astropy/blob/9819e926cb49fbc36019f5e641b563975e56d57c/astropy/modeling/functional_models.py#L2662

https://articles.adsabs.harvard.edu/pdf/1962AJ.....67..471K now gives `ERR_CONNECTION_TIMED_OUT`. Should we replace this link with something else or just remove it? If replacing, with what?

This model (and doc) was added by @nluetzge in #9084 . cc @nden and @astrofrog , who reviewed it.

**Comment by pllim** [comment]
Is https://ui.adsabs.harvard.edu/abs/1962AJ.....67..471K/abstract equivalent?

**Comment by nluetzge** [comment]
Hey @pllim, yes that is the right paper. Thanks for finding it again.
