### ISSUE TITLE
mpldev tests failing

### ISSUE THREAD

**Issue by embray** [astropy/astropy#11841]
The mpldev tests on CircleCI are failing since Friday.  See e.g.: https://app.circleci.com/pipelines/github/astropy/astropy/5881/workflows/f87702cb-4e75-4034-a182-33103ed419d9/jobs/90237

It doesn't seem related to any existing known issues.  I guess something that changed in matplotlib itself.  No crash, just some images that are different, apparently.

I'll look into it if I have time but probably not today.

EDIT: Added more info below

Looks like it started on 2021-06-11 with `Matplotlib: 3.5.0.dev1037+g3cf46cb`.

```
FAILED .../astropy/visualization/wcsaxes/tests/test_images.py::TestBasic::test_curvilinear_grid_patches_image
FAILED .../astropy/visualization/wcsaxes/tests/test_images.py::TestBasic::test_tick_angles
FAILED .../astropy/visualization/wcsaxes/tests/test_images.py::TestBasic::test_tick_angles_non_square_axes
FAILED .../astropy/visualization/wcsaxes/tests/test_transform_coord_meta.py::TestTransformCoordMeta::test_coords_overlay
FAILED .../astropy/visualization/wcsaxes/tests/test_transform_coord_meta.py::TestTransformCoordMeta::test_coords_overlay_auto_coord_meta
FAILED .../astropy/visualization/wcsaxes/tests/test_transform_coord_meta.py::TestTransformCoordMeta::test_direct_init
```

**Comment by pllim** [comment]
The last time this happened, I had to download the artifacts and truths, and then blink them to make sure they are okay. And then replace truths with new artifacts over at `astropy-data`. It is quite a time sink and I have no idea what I am really looking for here. It would be the best if `visualization.wcsaxes` maintainers (@larrybradley , @astrofrog , @Cadair) can take this on.

https://app.circleci.com/pipelines/github/astropy/astropy/5881/workflows/f87702cb-4e75-4034-a182-33103ed419d9/jobs/90237/artifacts

**Comment by pllim** [comment]
Looking at https://github.com/matplotlib/matplotlib/commits/master , a number of PRs are merged that same day. Hard to tell which one was the culprit without a bisect.

Bad: matplotlib/matplotlib@3cf46cb

Good: matplotlib/matplotlib@f4c518e

**Comment by ayshih** [comment]
See sunpy/sunpy#5399 where we spotted it with our figure tests.  The working guess for the minor differences is that it is matplotlib/matplotlib#20363.  (Ignore the more glaring failure that I discuss in that SunPy PR.)

**Comment by pllim** [comment]
Thanks for the info! @eteq is looking into this as part of the 4.3 release process.

**Comment by embray** [comment]
At least it's not just us.

**Comment by pllim** [comment]
I think this was already fixed.
