### ISSUE TITLE
References to older releases described as current in documentation.

### ISSUE THREAD

**Issue by mkbrewer** [astropy/astropy#11859]
### Description

I was reading through some of the documentation when I came across the following in `frames.rst`:

"In this version 3.0, we have only changed the references to this attribute in the documentation. In the next major version, we will issue a deprecation warning. In two major versions, we will remove the `.representation` attribute and `representation=` argument."

You should consider updating this for the 4.3 release. There may be other instances of this sort of thing in the documentation. I haven't gone through all of it, but someone probably should.

**Comment by pllim** [comment]
Yup, still there in https://github.com/astropy/astropy/blame/main/docs/coordinates/frames.rst#L126 (as of 2021-06-21). Looks like @adrn and @eteq added the original text in #6873
