### ISSUE TITLE
sigma_clip does not return a masked array when input is empty

### ISSUE THREAD

**Issue by npirzkal** [astropy/astropy#11850]
### Description

When using sigma_clip() with default parameters (or when selecting masked=True) and passing an empty array to it, sigma_clip returns an empty np.array instead of an empty masked array. The result is that one cannot currently rely on sigma_clip to return a masked array.

### Expected behavior

when given [] as input, sigma_clip should return [] either as a masked_array or as a regular array, depending on the masked option that was used.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by pllim** [comment]
This behavior appears intentional.

https://github.com/astropy/astropy/blob/9819e926cb49fbc36019f5e641b563975e56d57c/astropy/stats/sigma_clipping.py#L596-L597

What is the use case that would require passing in empty list but wants a masked array back? There is no data to clip.

**Comment by npirzkal** [comment]
The use case is that code using sigma_clip needs to be able to rely on whether a masked array is returned or not. A typical use case is one where a user uses something like sigma_clip(a[a>0]) and a[a>0] ends up being an empty array.
Right now, to make code using sigma_clip robust, one needs to get around sigma_clip not returning a consistent array type. Returning an empty array when given an empty array makes sense but making the type of the array that is returned consistent would be better.
