### ISSUE TITLE
Add helpers to convert between different types of uncertainties

### ISSUE THREAD

**Issue by aragilar** [astropy/astropy#11862]
Currently there no easy way to convert from an arbitrary uncertainty class to a different uncertainty class. This would be useful to be able to pass NDData objects to external libraries/tools which assume, for example, that uncertainties will always stored as variances. Here's some really scrappy code I bunged together quickly for my purposes (probably buggy, I need to properly test it), but what are peoples opinions on what's the best API/design/framework for such a system?

```python
from astropy.nddata import (
    VarianceUncertainty, StdDevUncertainty, InverseVariance,
)

def std_to_var(obj):
    return VarianceUncertainty(obj.array ** 2, unit=obj.unit ** 2)


def var_to_invvar(obj):
    return InverseVariance(obj.array ** -1, unit=obj.unit ** -1)


def invvar_to_var(obj):
    return VarianceUncertainty(obj.array ** -1, unit=obj.unit ** -1)


def var_to_std(obj):
    return VarianceUncertainty(obj.array ** 1/2, unit=obj.unit ** 1/2)


FUNC_MAP = {
    (StdDevUncertainty, VarianceUncertainty): std_to_var,
    (StdDevUncertainty, InverseVariance): lambda x: var_to_invvar(
        std_to_var(x)
    ),
    (VarianceUncertainty, StdDevUncertainty): var_to_std,
    (VarianceUncertainty, InverseVariance): var_to_invvar,
    (InverseVariance, StdDevUncertainty): lambda x: var_to_std(
        invvar_to_var(x)
    ),
    (InverseVariance, VarianceUncertainty): invvar_to_var,
    (StdDevUncertainty, StdDevUncertainty): lambda x: x,
    (VarianceUncertainty, VarianceUncertainty): lambda x: x,
    (InverseVariance, InverseVariance): lambda x: x,
}


def convert_uncertainties(obj, new_class):
    return FUNC_MAP[(type(obj), new_class)](obj)
```

**Comment by saimn** [comment]
See also #10128 which is maybe not exactly the same need but related in the sense that there is currently no easy way to get uncertainties in a specific format (variance, std).

**Comment by mhvk** [comment]
Very much from the left field, but in coordinate representations, we deal with this by insisting every representation can be transformed to/from cartesian, and then have a `represent_as` method that by default goes through cartesian. A similar scheme (probably going through variance) might well be possible here.

**Comment by aragilar** [comment]
It sounds like the `represent_as` method via variance would be reasonable, I'll see if I can spend some time coding something up (but if someone else wants to have a go, don't let me stop you).
