### ISSUE TITLE
Sporadic test failures in `test_name_resolve_cache`

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#11868]
### Description
I am seeing inconsistent failures in the above test when `get_icrs_coordinates` is not using the expected URL:

```python
    @pytest.mark.remote_data
    def test_name_resolve_cache(tmpdir):
        from astropy.utils.data import get_cached_urls
    
        target_name = "castor"
    
        temp_cache_dir = str(tmpdir.mkdir('cache'))
        with paths.set_temp_cache(temp_cache_dir, delete=True):
            assert len(get_cached_urls()) == 0
    
            icrs1 = get_icrs_coordinates(target_name, cache=True)
    
            urls = get_cached_urls()
            assert len(urls) == 1
>           assert 'http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/' in urls[0]
E           AssertionError: assert 'http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/' in 'http://vizier.cfa.harvard.edu/viz-bin/nph-sesame/A?castor'

/opt/lib/python3.9/site-packages/astropy/coordinates/tests/test_name_resolve.py:158: AssertionError
```
Apparently the function is somewhat randomly using the Vizier instead of the CDS mirror (this is from a European domain).

### System Details
macOS-10.14.6-x86_64-i386-64bit
Python 3.9.5 (default, May 14 2021, 02:39:23) 
[Clang 11.0.0 (clang-1100.0.33.17)]
Numpy 1.21.0rc2
astropy 4.3rc1
Scipy 1.6.3
Matplotlib 3.3.3

**Comment by pllim** [comment]
Will simply allow either in the comparison be a good enough fix?

**Comment by dhomeier** [comment]
Probably; tbh I have no idea where it gets the sesame server URLs from (or if there could be a 3rd or 4th showing up ;-)

**Comment by pllim** [comment]
Is `assert 'sesame' in urls[0]` too relaxed?

**Comment by dhomeier** [comment]
Actually ` sesame_url` has exactly these two elements, so should probably also test precisely those.

**Comment by dhomeier** [comment]
Is there a generic kind of "assert_or" that would do
```python
assert sesame_url[0] in urls[0] or sesame_url[1] in urls[0]
```
for any length of `sesame_url`?

**Comment by pllim** [comment]
I guess this would also accomplish the same check? Not sure, I don't use science state.

```python
assert urls[0] in sesame_url._value
```

https://github.com/astropy/astropy/blob/7497e0be388e796b7b24a833e31b7c7ffc3ebf49/astropy/coordinates/name_resolve.py#L29-L34

**Comment by nstarman** [comment]
> is there a generic kind of "assert_or" that would do ... for any length of sesame_url?

```python
import operator
any(map(operator.contains, urls, sesame_url))
```

**Comment by dhomeier** [comment]
I think since we are actually checking for identical URL strings (and `urls` is already required to have only a single element), @plim's solution should suffice for this case.

**Comment by pllim** [comment]
Does #11871 work for you?

p.s. I am unable to tag @nstarman as a reviewer, so FYI here. Thanks!
