### ISSUE TITLE
Labels cleanup

### ISSUE THREAD

**Issue by embray** [astropy/astropy#11861]
We've had discussions on slack and elsewhere about the state of labels in this repository.  Some feel that there are too many labels--in other cases, some of the labels are underutilized or not useful.  We might want to have a look at the current labels and see if there are any we can pare down or change to make more useful.  This is sort of a meta-triage issue.

One problem with deleting labels, is they are also deleted from the issues they have been used on, which in some cases can make those issues harder fo find.  But I think there are some labels that might not be serving a significant purpose to begin with.

For starters, the question came up as to how to use the "Priority" labels and whether or not they're useful.  So to start with here are some statistics on the "Priority" labels:

* Priority-Low: issues: 27 open / 75 closed / oldest open: August 2012; PRs: 1 open / 27 closed / oldest open: March 2021
* Priority-Medium: 13 open / 16 closed / oldest open: October 2013; PRs: 0 open / 4 closed
* Priority-High: 1 open / 24 closed / oldest open: May 2019; PRs: 0 open / 11 closed

I didn't take exact numbers, but I also found that many "Priority-High" issues actually took several months or even years to resolve.

Another issue I raised about use of "Priority" issues, especially "Priority-Low" is it's very subjective as to how high a priority an issue is to whom.  And marking an issue raised by a user as "Priority-Low" may give the impression that the issue is *unimportant*, or that the report was not valued (it is, even if it's a minor issue that really is not the highest priority to fix!)

"Priority" labels could be useful when labeling issues in a milestone in order to help plan a release.  Like, we might know that we won't get to every issue in a milestone before its release, but we may wish to prioritize them.  However, another approach to that might just be to remove issues from the milestone when close to the release if they are not *high* priority.  Otherwise, unless someone is actively planning to work on some issue, setting a priority for it doesn't seem to have any effect on how likely it is to actually get done.

So I propose we simply remove the "Priority" labels, as they are not being used in a way that provides any value.

One similar label that seems to have more use is the :fire: label, which we've been using the label critical/blocker issues.  From what I can tell these usually get resolved in a timely manner, out of necessity.  And it's useful for release planning to be able to look at a list of these.

Other labels we could consider for removal:

* analytic_functions: this package was removed in Astropy 3.0.  Removing it means more difficulty (but not a ton) finding old issues related to this package, but do we really need that?
* astropy-helpers-removal: this work is mostly finished, do we still need a label for it?  It still has some open issues, but I think most of those issues could use more generic labels (build/installation/etc.)
* astropy-helpers: ditto, should be obsolete
* CASA-installation: not sure why we need a special label for this.  Maybe at one point it was being actively worked on, but it only has 3 issues/4 PRs and was last used in 2018.  New issues related to this can just go in "installation" I think.
* "new benchmark": How is this to be used?
* "potential fix for 2.0.x": I think this had something to do with Sphinx.  It was used twice.  This is obsolete now, right?
* run-asv: I understand what this is for, but does it actually work? I don't know in ASV how to find the benchmarks for a specific PR.
* "Still Needs Manual Backport": What is this for?  It doesn't look like it's been used.  How is it different from just "Manual Backport"
* unusual-merge-dealt-with: This has been used 5 times on some PRs, last in 2017.  Do we need this?

In any case, I think for all labels we want to keep, there should be documentation in the [maintainer docs](https://docs.astropy.org/en/latest/development/workflow/maintainer_workflow.html) or in any PR review docs as to what each label or set of labels is, and how to use it (the package-specific labels can be grouped together for this, of course).

I realize sometimes we also are adding new labels for things like bot an workflow control.  These should also get added to the documentation if they are actually being used, or at the very least have a description set in GitHub that explains what it is and how it should be used.

Any labels that we can't justify the use of might be ripe for removal.

**Comment by pllim** [comment]
> remove the "Priority" labels

I agree!

> analytic_functions, astropy-helpers-removal, astropy-helpers

These are useful to dig up old stuff from things that have since been retired. We might regret removing these labels one day when some old issue become relevant again in a new way and we need to go archeological digging. Especially the astropy-helpers labels, given some downstream packages have not applied APE 17 yet.

> CASA-installation

Maybe @keflavich knows.

> new benchmark, run-asv

At some point, we were very enthusiastic in keeping [astropy-benchmarks](https://github.com/astropy/astropy-benchmarks) in sync with actual development. Though I don't think we have enough resources to actually make that a reality. And now the benchmark isn't even running. Perhaps @astrofrog or @Cadair can clarify whether these labels can be removed or not.

> potential fix for 2.0.x, Still Needs Manual Backport, unusual-merge-dealt-with

Perhaps @bsipocz remembers their origin and purpose?

> there should be documentation

I agree, though there is always a risk of us forgetting to update and then the doc gets outdated, but I guess it is better than nothing.

**Comment by keflavich** [comment]
we can get rid of CASA-installation.  It probably didn't need a tag anyway.

**Comment by bsipocz** [comment]
> "Priority" labels could be useful when labeling issues in a milestone in order to help plan a release. Like, we might know that we won't get to every issue in a milestone before its release, but we may wish to prioritize them. However, another approach to that might just be to remove issues from the milestone when close to the release if they are not high priority. Otherwise, unless someone is actively planning to work on some issue, setting a priority for it doesn't seem to have any effect on how likely it is to actually get done.

Until we have a fully paid staff, and professional management I would be very very much against putting issues into milestones. We shall only put super critical ones that are release blocker (e.g. incompatibilities with latest numpy type of things), but nothing else. It was super annoying to keep remilestoning stuff that maintainers decided to be high priority critical yet the same maintainers didn't have time to address for years. Also, for core, we supposed to have a time-based release schedule, so there isn't such a thing that a new feature or fix should hold up a release.

**Comment by bsipocz** [comment]
Most of the proposed removals should really be "archived" rather than removed. So maybe renaming them, or put "archived" into their description? I agree with you and @pllim that they still serve the purpose of digging up old stuff, e.g. you could have proposed to remove python2, too, yet it has value to keep around.

>    analytic_functions: this package was removed in Astropy 3.0. Removing it means more difficulty (but not a ton) finding old issues related to this package, but do we really need that?

I would keep

>    astropy-helpers-removal: this work is mostly finished, do we still need a label for it? It still has some open issues, but I think most of those issues could use more generic labels (build/installation/etc.)
>    astropy-helpers: ditto, should be obsolete

 I would certainly keep these, these provide a good resource for the process in addition to he APE17 docs.

>    CASA-installation: not sure why we need a special label for this. Maybe at one point it was being actively worked on, but it only has 3 issues/4 PRs and was last used in 2018. New issues related to this can just go in "installation" I think.

I don't think this should have been created the first place, 👍 to remove.


>     "potential fix for 2.0.x": I think this had something to do with Sphinx. It was used twice. This is obsolete now, right?

It should not have been a label, 🔥 to it

>    run-asv: I understand what this is for, but does it actually work? I don't know in ASV how to find the benchmarks for a specific PR.
>    "new benchmark": How is this to be used?
 
 What about merging these into a "benchmark"?
    
>    "Still Needs Manual Backport": What is this for? It doesn't look like it's been used. How is it different from just "Manual Backport"

not sure why this exists. "Manual Backport" is functional with scripts relying on it, but I don't think this one is needed

>    unusual-merge-dealt-with: This has been used 5 times on some PRs, last in 2017. Do we need this?

Yes, this is useful to mark messed up cases, like when a maintainer thinks better and merges locally rather than follow the workflow of github, or there is a non rebased PR mergin in other PRs, or when the revert button is used...
This one is to be used by the release manager and scripts/bots, maybe putting that into the description is enough for now.

As for the priory labels, I share the frustration of they are useless, I certainly added a few high priority ones to things that should have been fixed for a release and haven't been done, but again I would point back to my previous comment, that we can't reasonably set priorities for other team members in a volunteer organization, so 👍 to remove the labels as they are not at all useful.

**Comment by mhvk** [comment]
Wish one could just "retire" or "hide" labels. Best is just to delete labels for which there is consensus they are of no use (and for that purpose, I agree with every subset of your list).

**Comment by pllim** [comment]
I just send a ticket to GitHub asking about "retiring" labels. I will post update if I hear back from them.

**Comment by bsipocz** [comment]
> installation

installation IMO most of the time user issues, more like helpdesk questions or documentation. I would not put those into `packaging`, but `questions`.

> copyedited

I think it's useless, we need `needs-copyediting` only to indicate what needs to be done with the label removed once it's copyedited.

**Comment by pllim** [comment]
Still no update from GitHub help desk about whether we can archive labels instead of deleting them. The reply does not look promising: *Your ticket was automatically routed to our Developer Support team but our Product team is better suited to help you out. We have forwarded your ticket to the Product team who reads and evaluates all feedback, however we cannot guarantee a response to every submission.*

**Comment by pllim** [comment]
@embray , at the infrastructure tag up today, we decided on the following:

* Given we cannot simply archive a label, just leave them alone for now; no point in renaming any nor deleting most of them, _except_
* We can go ahead and delete _a few_ labels that we absolutely do not need and they do not currently service any purpose. I think we pretty much have the list from discussions above; just need someone to collate them into a (short) list.
* Even though we are keeping most of them, as @tomdonaldson put it, we could "turn the question around" and only document the ones we will actively use going forward in the dev docs.

If you agree, we can go ahead and decide on the few to delete and close this issue out.

**Comment by embray** [comment]
@pllim Sorry I missed the infrastructure meeting (again).  It has turned out to frequently not be a good time for me :/

In any case, I was also going to write a synthesis of the discussion so far.  I'm inclined to agree removing labels is problematic from an archival point of view.  GitHub really *should* have a feature to archive labels: Keep them on existing issues that use them, but remove them from the list of available labels on new issues.

@bsipocz had an idea about somehow marking labels as "archived" e.g. in their description.  

What about, for labels we want to keep, but "retire", we change their name to prefix them with :zzz:.  It means they're snoozed, retired, no longer to be used.  And it will also put them towards the bottom of the label list.  We can also add in their description an advisory that they are archived.

**Comment by embray** [comment]
@bsipocz I also wanted to respond to this:

> Until we have a fully paid staff, and professional management I would be very very much against putting issues into milestones. We shall only put super critical ones that are release blocker (e.g. incompatibilities with latest numpy type of things), but nothing else. It was super annoying to keep remilestoning stuff that maintainers decided to be high priority critical yet the same maintainers didn't have time to address for years.

I love milestones and think they're super useful.  But I agree with you that maybe by default they shouldn't be used outside the context of an actual development plan and schedule for issues added to milestones.  I think they still *should* be used for backported bugfixes, and for new issues for which there is a plan to address them in the immediate term.  But otherwise I'm sympathetic to this viewpoint.

**Comment by embray** [comment]
Ok, to summarize, here are the list of labels I think everyone seems to be in agreement we can *remove*:

* The "Priority" labels (except for :fire:)
* CASA-installation
* "potential fix for 2.0.x"
* "Still Needs Manual Backport"
* copyedited   (I agree this one is not necessary--"needs-copyediting" is useful, but once it's done the "needs-copyediting" can just be removed)

Other changes:

* Merge "new benchmark" and "run-asv" into "benchmark" label (would be nice to get benchmarks going again, but that will be a separate task, and someone dedicated to maintaining it, including some dedicated machines...)
* I will experiment with "snoozing" outdated labels that should no longer be used.

**Comment by embray** [comment]
Done all of the above.  Almost down to 100 labels now :smiley:

**Comment by mhvk** [comment]
Thanks, @embray - I like the :zzz:!

**Comment by pllim** [comment]
Looks good to me. Thank you!

I am going to close this as resolved.

**Comment by pllim** [comment]
p.s. Documenting how to use them is still necessary but I think is out of scope here.
