### ISSUE TITLE
Weird interaction between Astropy and the Pickle module

### ISSUE THREAD

**Issue by MetinSa** [astropy/astropy#11872]
### Description

Using the astropy `si` function on an astropy `quantity` object returns the wrong units after having used the pickle module to read in a dictionary with an astropy `quantity` object.

### Expected behavior

```python
b = 50*u.GHz

print(b.si)
>>>> <Quantity 5.e+10 1 / s>
```
### Actual behavior

```python
b = 50*u.GHz

print(b.si)
>>>> <Quantity 1.35135135 Ci>
```
### Steps to Reproduce

1. Dump a dictionary containing an astropy object to a pickle file
```python
import pickle
import astropy.units as u

a = {'test': 1*u.GHz }
with open('dictionary.pkl', 'wb') as f:
    pickle.dump(a, f)

```

2. In a new file use the `si` function on an astropy object after having loaded the pickled dictionary
```python
import pickle
import astropy.units as u

with open('dictionary.pkl', 'rb') as f:
    a =  pickle.load(f)

b = 50*u.GHz

print(b.si)
>>>> <Quantity 1.35135135 Ci>
```

This only seems to be an issue when the pickled object contains an astropy quantity. Additionally, if you dump and load in the same file, the `si` function works as intended. It appears as if the loading of an astropy object through pickle alters the state of astropy in some way? 

I have tried to use the astropy.io.misc functions `fnpickle` and `fnunpickle` but to no help (I believe these are simply wrappers of the pickle dump and load functions?). 

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:42:56)
[Clang 10.0.1 ]
Numpy 1.19.4
astropy 4.2.1
Scipy 1.5.3
Matplotlib 3.3.3

**Comment by pllim** [comment]
I could reproduce this in 5.0.dev.

`.si` basically returns this:

https://github.com/astropy/astropy/blob/4e30ab8decdc3795915b07595bfac9835891c459/astropy/units/core.py#L1460

Somehow, the way you call things changed the scoring:

https://github.com/astropy/astropy/blob/4e30ab8decdc3795915b07595bfac9835891c459/astropy/units/core.py#L1450

@mhvk , any idea?

**Comment by pllim** [comment]
Expected order:

```python
>>> b.unit.to_system(u.si)
Out[4]:
[Unit("1e+09 / s"),
 Unit("0.027027 Ci"),
 Unit("1e+09 Hz"),
 Unit("1e+09 Bq"),
 Unit("6e+10 / min"),
 Unit("3.6e+12 / h"),
 Unit("8.61641e+13 / sday"),
 Unit("8.64e+13 / d"),
 Unit("6.048e+14 / wk"),
 Unit("1.2096e+15 / fortnight"),
 Unit("3.15576e+16 / a"),
 Unit("3.15576e+16 / yr")]
```

The order after calling `pickle.load`:

```python
>>>  b.unit.to_system(u.si)
[Unit("0.027027 Ci"),
 Unit("1e+09 Hz"),
 Unit("1e+09 Bq"),
 Unit("1e+09 / s"),
 Unit("6e+10 / min"),
 Unit("3.6e+12 / h"),
 Unit("8.61641e+13 / sday"),
 Unit("8.64e+13 / d"),
 Unit("6.048e+14 / wk"),
 Unit("1.2096e+15 / fortnight"),
 Unit("3.15576e+16 / a"),
 Unit("3.15576e+16 / yr")]
```

p.s. Funny how radioactivity snuck in there.

**Comment by mhvk** [comment]
Yes, confirmed! What a weird error. The sorting was a very good clue, and it turns out that after the pickle load, the "score" is 0 for all options, because, somehow, the following is no longer true:
```
u.s in u.si.bases
```
i.e., the "s" unit stored in u.si.bases is now different from that on the module -- which should never happen...

**Comment by mhvk** [comment]
OK, I figured out at least what happens: the privately stored hash of the unit is overwritten. Indeed,
```
In [15]: del u.s._hash

In [16]: u.s in u.si.bases
Out[16]: True
```

A fix should not be too far away...

**Comment by mhvk** [comment]
Fix in #11879. Check locally that it works (don't know how to do it in test, so added some tests that check using the private `_hash` atttribute)

**Comment by mhvk** [comment]
OK, fixed! Thanks @MetinSa for reporting (must have been a strange one to find!) and thanks @pllim for the good sleuthing that really helped to narrow it down - another nice collaboration!

**Comment by MetinSa** [comment]
Thanks @mhvk and @pllim for figuring this out so quickly. It was indeed a strange find!
