### ISSUE TITLE
Consider deprecating and then removing the io.ascii Column.dtype attribute

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#11895]
### Description

In #11892 there was discussion (and at one point code) to deprecate the `io.ascii.core.Column.dtype` attribute, with a plan to remove it. This issue is created to continue that discussion separately from that PR.

I am not in favor of this because it removes the possibility of user-defined readers specifying the exact `dtype` of columns without writing their own `_convert_vals` method in a custom Outputter. Such readers might already exist in the wild.

Readers like CDS and Rdb currently use `Column.type` to specify generic types such as float, int, str, but that mechanism does not allow fine-grained control like `np.int8`. Before the overhaul of ECSV in v4.3 of astropy, the ECSV reader did use the `Column.dtype` to do exactly that.

`Io.ascii` has been out for about 10 years now and has always been advertised as an extensible reader (though `dtype` came later, probably with ECSV). So we should not take this API change lightly as if it were just an internal change.

### Additional context

#11892

**Comment by taldcroft** [comment]
cc: @hamogu @mhvk @bsipocz

**Comment by mhvk** [comment]
I'm a bit more inclined to deprecate, especially since it doesn't seem a single test broke by removing it - and nothing broke by dealing with it incorrectly in a rewrite. This is quite bad, so if we do not solve that by deprecation, we need to properly document and test the attribute. But it depends also whether it is currently documented as existing.

**Comment by taldcroft** [comment]
If you made this change in 4.2 it would have completely broken ECSV. So let's say that someone likes fixed-format and also wants the types to be encapsulated. The make a Reader based on fixed format that creates a file like this:
```
 slot  idx      id     type  sz   p_acq    mag    maxmag   yang     zang    dim   res  halfw
int64 int64   int32    str3 str3 float64 float32 float32 float64  float64  int64 int64 int64
----- ----- ---------- ---- ---- ------- ------- ------- -------- -------- ----- ----- -----
    0     1 1105868016  BOT  8x8   0.980    8.03    9.53   565.19  1127.67    20     1   160
    1     2 1105868064  BOT  8x8   0.962    9.09   10.59  -165.74  1613.36    20     1   160
    2     3 1105869768  BOT  8x8   0.980    7.63    9.13 -2321.01  1256.88    20     1   160
    3     4 1105870024  BOT  8x8   0.981    7.32    8.82 -1299.55   -52.80    20     1   160
```
This would be a pretty easy job to make this custom format with only minimal extra code to set `col.dtype` according to that header line. But if you remove that `dtype` then there is no way to use the existing infrastructure (in particular `TableOutputter._convert_vals`). The user has to re-invent on their own a way of capturing `dtype` during header parsing and make it available later for the outputter. 

That's how ECSV used to work (https://github.com/astropy/astropy/blob/5bce144c6c3e8697496eeab87e689989f1dc5549/astropy/io/ascii/ecsv.py#L176), and this was good. But as part of the big refactor it turned out that a lot of the vanilla TableOutputter was just not applicable so I changed things up.

Note that in current main the ECSV code is still setting `col.dtype` (https://github.com/astropy/astropy/blob/fd06dc134a464bb8c29e7dfe719dc20167182348/astropy/io/ascii/ecsv.py#L198), it just isn't being exposed to `TableOutputter` because that is subclassed for ECSV.

Thus my conclusion that removing support for `Column.dtype` is removing an important piece of functionality for `io.ascii`. Unless we provide a better alternative to that functionality I'll be against removing it.

**Comment by taldcroft** [comment]
BTW, there is a mistake in #11892:
```
old_name = deprecated_attribute('dtype', '5.0')
```
That should be
```
dtype = deprecated_attribute('dtype', '5.0')
```
I predicted with that fix then there will be failures for ECSV.

**Comment by taldcroft** [comment]
Here is a test that should be added:
```
import numpy as np
from astropy.io import ascii
from itertools import cycle


def test_col_dtype_in_custom_class():
    class TestDtypeHeader(ascii.BasicHeader):
        def get_cols(self, lines):
            super().get_cols(lines)
            for col, dtype in zip(self.cols, cycle(np.float32, np.int8)):
                col.dtype = np.float32

    class TestDtype(ascii.Basic):
        """
        Basic table Data Reader with data type alternating float32, int8
        """
        _format_name = 'test_dtype'
        _description = 'Basic table with alternating dtypes'
        header_class = TestDtypeHeader

    txt = """
    a b c
    1 2 3
    """

    t = ascii.read(txt, format='float_always')
    for col, dtype in zip(t.itercols(), cycle(np.float32, np.int8)):
        assert col.dtype.type is dtype
```

**Comment by mhvk** [comment]
OK, sounds like it is the path of at least adding a test!

**Comment by hamogu** [comment]
OK, if we have a test and @taldcroft has a use case (even if that's not currently used), then we don't remove it. It's in there, it's not broken and removing it won't actually save us work right now. In contrast, it would be extra work right now - with the uncertain promise of saving work later. 

So, I vote to close this and leave the attribute in.
