### ISSUE TITLE
Order in which units are presented

### ISSUE THREAD

**Issue by smithis7** [astropy/astropy#11909]
Hi,

I have a quantity `x` that I would like to be presented in units of `erg/(s Hz)` or `erg s^-1 Hz^-1`, as opposed to `erg/(Hz s)` or `erg Hz^-1 s^-1` because of how it looks when rendered in latex, among other reasons. I cannot seem to figure out a way to accomplish this -- is this possible to do? And if so, how?

Another possible solution to my problem is getting the `*` or `\times` symbol to appear when the unit appears in LaTeX, i.e. `erg/(Hz*s)`. Can that be done?

Thank you very much.

**Comment by embray** [comment]
Unfortunately I don't think there is currently a straightforward way to do this.

In composite units, the unit bases always get sorted (for consistency) first by their powers, and then (somewhat arbitrarily) by name.  That happens here: https://github.com/astropy/astropy/blob/d9c58c52acd2bc067a07fa188699357c4eff8da3/astropy/units/core.py#L2330  And it happens that "Hz" comes before "s" lexicographically.

Meanwhile, none of the unit string formatters appear to have a way to control this (for some of the specialized formats, the order might even be prescribed by the format specification).  But maybe there could be a way to specify some custom order priority for units when they're stringified.

**Comment by pllim** [comment]
I think this works albeit a little brute force:

```python
>>> from astropy import units as u
>>> myunit = u.def_unit('myunit', u.Unit('erg/(s Hz)'), format={'generic': 'erg/(s Hz)'})  # add your own formatting
>>> x = 1 * myunit
>>> x
<Quantity 1. erg/(s Hz)>
>>> x.to(u.erg)
<Quantity 1. erg>
```

**Comment by smithis7** [comment]
> I think this works albeit a little brute force:
> 
> ```python
> >>> from astropy import units as u
> >>> myunit = u.def_unit('myunit', u.Unit('erg/(s Hz)'), format={'generic': 'erg/(s Hz)'})  # add your own formatting
> >>> x = 1 * myunit
> >>> x
> <Quantity 1. erg/(s Hz)>
> >>> x.to(u.erg)
> <Quantity 1. erg>
> ```
> 
> p.s. You can then register it into `astropy.units` with `u.add_enabled_units([myunit])`.

This is perfect -- the place we are using this for is hidden pretty deep in our code, so this will do exactly what we need it to do. Thank you very much!

**Comment by pllim** [comment]
Glad to hear! 😸
