### ISSUE TITLE
Questions about API for masked Time

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#11915]
Mostly for @taldcroft, two questions as I'm trying to finish the PR that uses `Masked` inside `Time`:
1. To what extent should we preserve the possibility to get `MaskedArray` as output for `.value`, etc.? (As input, it will be fully preserved.) Options would seem to be
  - Always have `Masked` output.
  - Preserve type of input, i.e., `MaskedArray` in -> `MaskedArray` out (this would not round-trip through disk, though).
  - Have a configuration item, with `MaskedArray`, `Masked`, or 'as_input' or so.
2. Currently, the data underlying any masked input items are replaced with a placeholder - this makes sense in the current implementation, since `jd2` is replaced by `nan` so the original data is corrupted. With `Masked`, this is no longer necessary, and in general the philosophy for `Masked` is that a mask does not indicate data is corrupt but just that data should not be looked at; the class tries to keep data intact (though without trying too hard). So, the question is now what to do. Options:
  - Just keep replacing; masked data is assumed to be crap.
  - Aim to ensure that masked items never lead to warnings or errors, e.g., by replacing only masked non-finite numbers.
  - Do a double trial of time parsing, first with data as they were, and if that does not work, with masked data replaced.
  - Yet another configuration item, perhaps 'replace', 'replace-non-finite', 'nothing'.

p.s. Current implementation at https://github.com/astropy/astropy/compare/main...mhvk:masked-time?expand=1, but that includes the multitude of small bug-fix PRs that I found while implementing it.

**Comment by taldcroft** [comment]
On (1), I wasn't aware of plans to start replacing `MaskedArray` with `Masked(np.ndarray)`, but it sounds like you going there? I'm assuming that your `Masked` output is shorthand for `Masked(np.ndarray)`?

My assumption had been that this transition is not going to happen any time soon, and that the answer to (1) is `MaskedArray` always.

On API, is this going to preserve the current property of `Time` that elements can be masked in-place without changing the object? I.e.
```
>>> t = Time([1, 2], format='cxcsec')                                           

>>> t[0] = np.ma.masked                                                         

>>> t                                                                           
<Time object: scale='tt' format='cxcsec' value=[-- 2.0]>
```

**Comment by taldcroft** [comment]
On (2), my feeling is to go with "Just keep replacing". 

Assuming that the `Masked` class is going to do computations on all the data (including masked), I think it is impossible to never have ERFA warnings or errors for masked data without strictly replacing it up-front. You can have a JD of -1e30 which is certainly finite but will cause an error, and likewise a masked string time of `''` on input should not cause problems IMO. The double parsing just seems complicated and ends up making the behavior less predictable for users.

**Comment by mhvk** [comment]
@taldcroft - on (1), yes, I was hoping to use `Masked(np.ndarray)` also in `Time`, so that it will be the same throughout astropy (for `SkyCoord`, which uses Quantity throughout, `MaskedArray` is not really an option).

I started with `Time` in part to see how intrusive the changes would be, and in part to get a better sense of the API, so I can try to be consistent for `SkyCoord` (I'm still struggling what to do with masked attributes - it is (primarily) `.location` for `Time` but many more for `SkyCoord`).

Of course, also for `Time`, there are a few pieces where `Masked` enables consistency (e.g., `time_delta.to(u.s)`.

Anyway, from your first reaction of "`np.ma.MaskedArray` always", while I want nothing to do with it anymore, it sounds like it should be a configuration option!

On my second question, currently I tried very hard to ensure all tests remained OK and hence kept the "always replace" option. I agree with your arguments for continuing to do that. In any case, if someone really wants to mask and unmask, they can initialize without a mask and apply the mask after.

**Comment by mhvk** [comment]
p.s. Just to be sure, my in-progress PR keeps API, including setting the mask with `np.ma.masked` (as for `Masked` itself). I think essentially all changes to the tests are making them neutral to the class used (`hasattr(result, 'mask')` instead of `isinstance(result, np.ma.MaskedArray)`) and to remove tests of the implementation detail of `jd2` being `nan` for masked elements.

**Comment by mhvk** [comment]
Since we now use `Masked` inside `Time`, this issue can be closed.
