### ISSUE TITLE
Writing a flat array or a column to file produces multiple columns

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#11912]
### Expected behavior
A single column should be written to file as a single column file

### Actual behavior
Multiple columns are produced (one per row)

### Steps to Reproduce

```python
from astropy.io import ascii
xx = np.random.uniform(0, 1, 100)
ascii.write(xx, "test.dat")
```

```python
from astropy.table import Table, Column
xx = np.random.uniform(0, 1, 100)
col = Column(xx)
ascii.write(col, "test.dat")
```

Either method should produce a single column file by default.

### System Details

Linux-5.5.0-050500-generic-x86_64-with-glibc2.27
Python 3.9.4 (default, Apr  9 2021, 16:34:09) 
[GCC 7.3.0]
Numpy 1.20.1
astropy 4.2.1
Scipy 1.6.2
Matplotlib 3.3.4

**Comment by pllim** [comment]
I am not actually sure if `Column` is meant to be used like that. It usually goes with `Table` or `QTable`.

**Comment by mhvk** [comment]
Thanks for the report! As you found, `ascii.write` will assume that any input sequence is one of multiple columns, not checking dimensionality. As @pllim suggested, we'd generally recommend using `Table(...).write(...)`, but `ascii.write` is possible, but you would have to explicitly indicate that there is only 1 column by putting it in a list, as in `ascii.write([col], ...)`.

In principle, for a single `Column`, the intent may be quite obvious and one could think of checking for this, but `io.ascii` is meant to be rather agnostic to other classes in astropy and it would not seem quite worthwhile to me to complicate this fairly deep-down piece of code. 

What is important, though, is to avoid confusion about what input is expected! I do not know what documentation you checked, but if there is anything we could do to make that expectation clearer, do let us know! (Or, even better, make a PR with a documentation update!)

**Comment by Gabriel-p** [comment]
If this is the intended usage, then I'll close the issue. Thanks for explaining it @mhvk!

**Comment by mhvk** [comment]
OK, no problem! The way to think of it is as "anything that can initialize a `Table`" (which is in fact what happens inside).
