### ISSUE TITLE
Import error of Astropy: "erfa version 1.7 or later must be installed to use Astropy. erfa is not installed."

### ISSUE THREAD

**Issue by zjzhang42** [astropy/astropy#11925]
### Description
astropy cannot be imported in ipython3.7. I see a similar issue [here](https://github.com/astropy/astropy/issues/11093#issue-751555006), but I am not sure what are action items here.

### Expected behavior
astropy being imported

### Actual behavior
I see the following error:

```
In [1]: import astropy
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e47bd5b3515c> in <module>
----> 1 import astropy

/opt/anaconda3/lib/python3.7/site-packages/astropy/__init__.py in <module>
     90
     91 _check_requirement('numpy', __minimum_numpy_version__)
---> 92 _check_requirement('erfa', __minimum_erfa_version__)
     93
     94

/opt/anaconda3/lib/python3.7/site-packages/astropy/__init__.py in _check_requirement(name, minimum_version)
     84         msg = (f"{name} version {minimum_version} or later must "
     85                f"be installed to use Astropy. {import_fail}")
---> 86         raise ImportError(msg)
     87
     88     return module

ImportError: erfa version 1.7 or later must be installed to use Astropy. erfa is not installed.
```

### Steps to Reproduce

```python
import astropy
```

### System Details
Darwin-18.7.0-x86_64-i386-64bit

Python 3.7.5 (default, Oct 25 2019, 10:52:18)
[Clang 4.0.1 (tags/RELEASE_401/final)]

Numpy 1.17.4

`import astropy; print("astropy", astropy.__version__)`
I cannot run this, but I know my astropy version is 4.2.1 (based on `pip list`)

Scipy 1.3.1

Matplotlib 3.1.3

**Comment by maxnoe** [comment]
Your erfa version was compiled against a newer version of numpy than you have installed. You can either update numpy or get erfa to be compiled against your version of numpy.

**Comment by dhomeier** [comment]
You are running from a conda installation but mention using `pip` – did you install/upgrade your packages with `pip install` or `conda update`?

**Comment by pllim** [comment]
From your path, you appear to be using Anaconda full installation in its `base` environment. That is not recommended as it comes with a lot of baggage and once you mess it up, you basically have to reinstall. Try Miniconda and always use a non-`base` environment.

**Comment by eerovaher** [comment]
The current installation instructions do not mention Miniconda at all.

**Comment by pllim** [comment]
Well... It was my personal recommendation as a long time conda user... 😬

**Comment by pllim** [comment]
p.s. There is an ongoing work to improve installation doc at #10919

**Comment by embray** [comment]
Environment-specific installation problem, so we can close this right @pllim?  @zjzhang42 can still feel free to provide follow-up information in case there's any way to help them solve their specific problem.
