### ISSUE TITLE
Remove ASDF serialization support from this package (deprecated in v5.1)

### ISSUE THREAD

**Issue by eslavich** [astropy/astropy#11924]
### Description
Over in https://github.com/astropy/asdf-astropy we are re-implementing astropy's ASDF support using the asdf package's new extension API.  Once that package is finalized and released we can remove most ASDF-related code from astropy itself.

`astropy.io.misc.asdf` was deprecated in v5.1:

* #12903
* #12930

TODO:

- Remove `astropy/io/misc/asdf/` tree.
- Remove remaining usage of `astropy.io.misc.asdf` in this package.
- Remove `astropy.io.misc.asdf` docs.
- Replace optional dependency `asdf` with `asdf-astropy` and set appropriate minversion for that.
- Remove `asdf` from `astropy/utils/compat/optional_deps.py`, if possible.
- Remove ignored `asdf` deprecation warnings in `setup.cfg`.
- Update CI matrix accordingly.
- [ ] Also address #11899

**Comment by pllim** [comment]
I think  #11899 is a subset of this work.

**Comment by eslavich** [comment]
I imagine we'll want to move most of that to asdf-astropy documentation and simply link there from here.
