### ISSUE TITLE
Options for improving speed at the cost of precision

### ISSUE THREAD

**Issue by ryanhofmann** [astropy/astropy#11937]
### Description

It's great that astropy can calculate the positions of celestial objects to microarcsecond precision, but not everyone needs that level of accuracy all the time. Sometimes, we just need a quick answer, accurate to the nearest arcsecond, and we don't have time to wait for five extra digits of precision that we'll never use. Case in point, I'm doing some stuff with the effects of atmospheric dispersion on solar observations with DKIST, and I don't need five decimals of precision to know how long I can hold a slit at the same position on the solar disk.

Basically, what I'm asking is, would it be possible to add an option for low-precision calculations? I get that a lot of people who use this library need all that precision and can spare the computational time, but if there was an option to say, "Just calculate it to the nearest arcsecond and let me get on with my day," especially with things like geocentric coordinate transformations, I think a lot of users could benefit. After all, as I rather bluntly put it to my advisor today, you wouldn't use a scalpel to butcher a cow.

### Additional context

If it helps at all, this is the code I'm working with. It's basically a python translation of some old IDL routines my advisor wrote back in '06. The IDL version runs to completion in about 10 seconds. The python version takes 20 minutes. I would be very happy if I could drop a few decimals and get it down to less than a minute.
[python_all.txt](https://github.com/astropy/astropy/files/6794605/python_all.txt)

**Comment by ayshih** [comment]
I think it would be greatly helpful if you could narrow down specific parts of your code that are taking excessively long.  You're already using `ErfaAstromInterpolator`, and I don't know if there could be potential additional approaches for the *general* trading off of accuracy for performance.  For the *specialized* case of Earth-based observations of the Sun, perhaps some shortcuts could be taken, but it's still going to be a lot of computations that you may not need.

I suspect that the IDL version of your code calls specialized routines – e.g., for the the RA/dec of the Sun – that do not perform actual coordinate transformations, but rather use pre-computed numerical approximations with sufficient accuracy for your purposes.  Case in point: you call `sunpy.coordinates.sun.P()` to get the Sun's position angle.  The implementation of that function (which I wrote) uses the transformation framework to its full extent to return a self-consistent answer.  However, the commonly used IDL/SSW routine calculates P using a Meeus-based equation, which of course will be much much faster (as is the precise intent of Meeus's equations).

It may be more appropriate for you to submit a feature request over on SunPy.

**Comment by ryanhofmann** [comment]
Ah, good point. I guess I should have started by asking if there were already specialized approximate routines that I could use. The coordinate transformations are definitely the biggest time sink overall, and now I understand why the `get_sun()` call also takes a while. I know that the IDL `sunpos` routine uses Newcomb's quadratic approximations, and the IDL `eq2hor` routine uses spherical trigonometry for the coordinate transformations, but I don't know how those compare to what astropy uses.

I'm honestly not super familiar with all these numerical routines, so I greatly appreciate your detailed response. I don't suppose you could point me to some more specialized routines in either astropy or sunpy, or at least tell me how to effectively look for them? I'm sure a large part of my problem is that I started with someone else's half-done code and hashed it together from there. I may be a PhD student, but literally 90% of my coding abilities are dependent on Google and StackExchange, so I would greatly appreciate some advice.

Again, thanks so much for your prompt and detailed response. I've already learned a few things from this, and I really want to learn how to use this wonderful package more effectively.

**Comment by pllim** [comment]
Looks like this is either SunPy or dev mailing list discussion topic. I am closing this for now. Thanks!
