### ISSUE TITLE
Coordinates: ``Distance.z`` does not work with vectors

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11949]
### Description

``Distance(something).z`` works, but ``Distance([thing 1, thing 2]).z`` does not because ``astropy.cosmology.z_at_value`` only works on scalars.

### Expected behavior

Broadcasting of arguments.

### Actual behavior

Raises an error

### Steps to Reproduce

```python
import astropy.units as u
from astropy.coordinates import Distance

Distance([10, 15] * u.Gpc).z
```

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.9.5 (default, May 18 2021, 12:31:01) 
[Clang 10.0.0 ]
Numpy 1.20.2
astropy 5.0.dev322+gd5503963c.d20210707
Scipy 1.6.2
Matplotlib 3.3.4

**Comment by pllim** [comment]
Is this related to #11361 as well? I see that you already opened #11778.

**Comment by nstarman** [comment]
#11361 would definitely help! But it introduces a behavior change to ``z_at_value`` by using interpolation tables, so we'll need a more careful examination for how ``Distance.z`` can take advantage of the major speedups in  #11361, while giving the user control over the interpolation table internals. So #11778 is the one to close this.
