### ISSUE TITLE
Discrepancy transforming `SkyCoord` to `AltAz`

### ISSUE THREAD

**Issue by danjampro** [astropy/astropy#11961]
### Description
I have come across a discrepancy that I cannot explain when converting `SkyCoord` (RA/Dec) to `AltAz`.  In short, I get *slightly* but significantly different results using the equation of celestial navigation (as described [here](https://onboardintelligence.com/CelestialNav/Celnav1)) and `SkyCoord.transform_to`.

### Expected behavior
`SkyCoord.transform_to` should match the trigonometric result from the celestial navigation equation.

### Actual behavior
There is a small difference between results.

### Steps to Reproduce
1. Use the online celestial to horizon coordinates calculator available [here](http://www.convertalot.com/celestial_horizon_co-ordinates_calculator.html) to convert location + time + RA/Dec to an Alt/Az:

<img width="491" alt="Screenshot 2021-07-20 at 14 56 25" src="https://user-images.githubusercontent.com/15114252/126264457-7b67f4fa-ecb3-4405-8a95-83c6a62cd380.png">

(Note that this calculator uses your local time as an input, rather than the observer's).

This result is consistent with what I get using my own implementation of the celestial navigation equation.

2. Use `astropy` to do the same calculation:
```
from datetime import datetime
from astropy import units as u
from astropy.time import Time
from astropy.coordinates import AltAz, EarthLocation, SkyCoord

location = EarthLocation(lat=0 * u.deg, lon=0 * u.deg)
skycoord = SkyCoord(ra=0 * u.deg, dec=0 * u.deg)

# Time at longitude = 0 == UTC
time = Time(datetime(2021, 1, 1, 0, 0), scale="utc", location=location)

altaz_frame = AltAz(obstime=time, location=location)
altaz = skycoord.transform_to(altaz_frame)
print(altaz.alt.to_value("deg"), altaz.az.to_value("deg"))

# Prints: -10.59990770524396 270.1166107257178
```
Is there an explanation for this difference? Thanks!

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ]
Numpy 1.20.1
astropy 4.2.1
Scipy 1.6.2
Matplotlib 3.4.2

**Comment by pllim** [comment]
That website had a "copyright" stamp of 2004 (17 years old) and a lot of values are hardcoded but not to a lot of decimal place. Are you sure the results are a good benchmark for accuracy?

I have attached that webpage here for those who want to inspect the Javascript:

[celestial_horizon_co-ordinates_calculator.html.txt](https://github.com/astropy/astropy/files/6848771/celestial_horizon_co-ordinates_calculator.html.txt)

**Comment by ayshih** [comment]
The issue is that you have defined your coordinate in the "wrong" coordinate system.  As you've coded, `skycoord` is in `ICRS`, which is centered at the solar-system barycenter and has no notion of observation time.  What you want is RA/dec in Earth-centered equatorial coordinates.  Try using [True Equator and True Equinox (TETE)](https://docs.astropy.org/en/stable/api/astropy.coordinates.TETE.html) instead:

```python
skycoord = SkyCoord(ra=0 * u.deg, dec=0 * u.deg, frame='tete', obstime=time, location=location)
...
# Prints: -10.863896055280494 269.99991918589484
```

I don't currently have a guess where the remaining discrepancy is coming from.

**Comment by danjampro** [comment]
> That website had a "copyright" stamp of 2004 (17 years old) and a lot of values are hardcoded but not to a lot of decimal place. Are you sure the results are a good benchmark for accuracy?
> 
> I have attached that webpage here for those who want to inspect the Javascript:
> 
> [celestial_horizon_co-ordinates_calculator.html.txt](https://github.com/astropy/astropy/files/6848771/celestial_horizon_co-ordinates_calculator.html.txt)

Hi @pllim, thanks for your reply. I cannot vouch for that website other than to say the results I get from it reasonably (but not exactly) match my implementation. The decimal place issue could be the reason for that minor discrepancy.

**Comment by danjampro** [comment]
> The issue is that you have defined your coordinate in the "wrong" coordinate system. As you've coded, `skycoord` is in `ICRS`, which is centered at the solar-system barycenter and has no notion of observation time. What you want is RA/dec in Earth-centered equatorial coordinates. Try using [True Equator and True Equinox (TETE)](https://docs.astropy.org/en/stable/api/astropy.coordinates.TETE.html) instead:
> 
> ```python
> skycoord = SkyCoord(ra=0 * u.deg, dec=0 * u.deg, frame='tete', obstime=time, location=location)
> ...
> # Prints: -10.863896055280494 269.99991918589484
> ```
> 
> I don't currently have a guess where the remaining discrepancy is coming from.

Hi @ayshih , thanks for your reply! Indeed, using the `tete` frame seems to provide a much more accurate match to the result I get from my implementation of the celestial navigation equations. If you wouldn't mind validating my understanding:

- Start from ICRS RA/Dec coordinate `skycoord_icrs`
- Transform ICRS coordinate into the TETE frame using location and time to get `skycoord_tete`
- The ra/dec pair in `skycoord_tete` are appropriate for use with the celestial navigation equations because the Earth's position and orientation are accounted for.
- Transforming either `skycoord_icrs` or `skycoord_tete` into the `AltAz` frame will give identical results

**Comment by mkbrewer** [comment]
Your understanding is correct. Most of the remaining difference is due to the fact that that calculator uses mean sidereal time, thereby ignoring nutation. Astropy uses apparent sidereal time. The difference is the equation of the equinoxes.

**Comment by mkbrewer** [comment]
Since the problem here is with the calculator rather than Astropy and there has been no further discussion on this issue for nearly three weeks, I believe that this issue should be closed.
