### ISSUE TITLE
cannot import name 'imperials' from 'astropy.units'

### ISSUE THREAD

**Issue by erwanp** [astropy/astropy#11975]
### Description

Our spectroscopy package [radis](https://github.com/radis/radis) depends on Astropy.units. Latest build fetched astropy==4.3 
 and [failed](https://app.travis-ci.com/github/radis/radis/jobs/527018350#L1767) with the following error : 
```
AttributeError: module 'astropy.units' has no attribute 'imperial'
```

- I could find a similar error encountered by @pllim in https://github.com/astropy/astropy/pull/11204#issuecomment-821844588, which helped a lot to yield a fix, below. 
- I trace the error to the change of Imports in #11592 by @namurphy  :  

### Expected behavior

Original code worked : 
```
import astropy.units as u
u.K in (u.K, u.imperial.deg_F)
>>> cannot import name 'imperials' from 'astropy.units'
```

Now I have to update the code to 

```
import astropy.units as u
from astropy.units.imperial import deg_F 
u.K in (u.K, deg_F)
>>> True
```

If this is the expected behavior (and cleaner way to import), this Issue can be closed right away. Hopefully the title will help people that would encounter the same proper to find an easy fix.

**Comment by astrofrog** [comment]
I'm running into the same issue with PyWWT using ``u.imperial``:

```
In [1]: from astropy import units as u

In [2]: u.imperial
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-f25c0008b10d> in <module>
----> 1 u.imperial

AttributeError: module 'astropy.units' has no attribute 'imperial'
```

**Comment by astrofrog** [comment]
I think this is going to require a quick v4.3.1 follow-up

**Comment by dhomeier** [comment]
> from astropy.units.imperial import deg_F
u.K in (u.K, deg_F)

Until then a less intrusive workaround will probably be
```python
import astropy.units.imperial
u.K in (u.K, u.imperial.deg_F)
```

**Comment by pllim** [comment]
Oh, dear! See #11977

**Comment by pllim** [comment]
FYI to packages affected by this: Going forward, we highly recommend adding a CI job to test against astropy dev, or at the very least test the release candidate when it is announced.
