### ISSUE TITLE
Is 4.3 actually released?

### ISSUE THREAD

**Issue by adammcmaster** [astropy/astropy#11999]
This isn't really a bug in astropy per se, so apologies if this isn't the best place to raise this. I'm a little confused about what version of astropy is actually the latest release. The [changelog](https://github.com/astropy/astropy/blob/2216de2614825335cd0e403a04ab718fcfca45cd/CHANGES.rst) says it's 4.2.1 and lists 4.3 as unreleased, and astropy.org also lists 4.2.1 as the latest. However, [PyPi has 4.3 and 4.3.post1](https://pypi.org/project/astropy/#history) both released on 26 July and that also seems to be the latest release on the [docs page](https://docs.astropy.org/en/stable/whatsnew/4.3.html).

I ask because dependabot wants me to bump one of my projects to 4.3.post1 and it's not clear if that's actually a final release or some kind of pre-release version.

**Comment by Cadair** [comment]
Versions on PyPI which aren't a pre-release version (PyPI marks these clearly) are always "official", there are just a few steps which have to happen in the release procedure after a version is pushed to PyPI, which look like they haven't been done yet (i.e. update the changelog on the main branch etc).

In short, yes 4.3.0 final is out, (with a post1 release to fix the documentation build) and you should feel free to start using them.

**Comment by adammcmaster** [comment]
OK great, thank you!

**Comment by pllim** [comment]
4.3.1 is supposed to come out soon too. @eteq ?
