### ISSUE TITLE
SigmaClip to return NaN as bounds when all input array is masked

### ISSUE THREAD

**Issue by ysBach** [astropy/astropy#11992]
### Description

In the doc (e.g., [`sigma_clip`](https://docs.astropy.org/en/stable/api/astropy.stats.sigma_clip.html#astropy.stats.sigma_clip)), it is said that "the minimum and maximum clipping bounds are also returned" if `return_bounds=True`. I just happened to encounter a problem when I want the ``result`` AND the bounds ``low`` and ``upp``.

The simplest example to show this :
```python
import numpy as np
from astropy.stats import sigma_clip

a_allmask = np.ma.array(np.arange(10.), mask=[True]*10)
a = np.ma.array(np.arange(10.), mask=[False]+[True]*9)

for data in [a, a_allmask]:
    res, low, upp = sigma_clip(data, return_bounds=True)
    print(low, upp)
```
This raised ``ValueError``:
```
0.0 0.0
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-b2add72739a4> in <module>
      6
      7 for data in [a, a_allmask]:
----> 8     res, low, upp = sigma_clip(data, return_bounds=True)
      9     print(low, upp)

ValueError: too many values to unpack (expected 3)
```

So it means lower/upper bounds are not returned at all, even though `return_bounds=True`. Maybe better to let it return NaN for both lower/upper bounds if all data is masked for consistency.

**Comment by ysBach** [comment]
(Using astropy ver. 4.2.1)

**Comment by pllim** [comment]
Looks like a bug, as `return_bounds` behavior is not consistent here. Thanks for the report!
