### ISSUE TITLE
Slicing rice compressed image produces file invalid according to cfitsio

### ISSUE THREAD

**Issue by Pharisaeus** [astropy/astropy#12007]
When slicing rice compressed file `.fits.fz` using astropy and saving results to a file I am facing an issue, with reading back the resulting file with tools using cftitsio (eg. `funpack`).

Simple reproduction steps:

```python
infile = "input.fits.fz"
outfile = "invalid.fits.fz"
slices = (slice(0, 100), slice(0, 100))
with fits.open(infile, checksum=True) as hdus:
    hdus[1].data = hdus[1].data[slices]
    hdus.writeto(outfile, overwrite=True, checksum=True)

with fits.open(outfile, checksum=True) as hdus:
    pass
```

You can get the example input file from http://dataportal.eso.org/dataPortal/file/ADP.2016-10-06T13:39:47.172 but I was able to reproduce the same behaviour with other `.fits.fz` files as well, so I don't think it's anything special for this particular file.

`funpack` says:

```
funpack invalid.fits.fz
Error processing file: invalid.fits.fz
  in HDU number 1

FITSIO status = 222: second keyword not BITPIX
Second keyword of the extension is not BITPIX: XTENSION
error copying primary keywords from compressed file
```

However the header itself seems fine, so I suspect it's something else, which is just accidentally triggering this particular cfitsio error.
`fv` can open this file, but attempting to plot or display data table crashes.

Not sure if related, but notice also that I save the file with `checksum=True`, yet opening the output with checksum verification shows invalid checksum and datasum keywords (similar to: https://github.com/astropy/astropy/issues/4587 )

I tested this with astropy `4.0` and then on `4.3post1` on Python 3.7 on Windows and Linux environments, and the results are the same.

**Comment by saimn** [comment]
The checksum issue is probably the same as #4587 indeed.
About the funpack/BITPIX issue, when updating the hdu and writing the file, astropy adds a ZTENSION keyword which moves ZBITPIX to 4th position.
Original file:
```
In [7]: hdul[1]._header['Z*']
Out[7]: 
ZSIMPLE =                    T /                                                
ZIMAGE  =                    T / extension contains compressed image            
ZBITPIX =                  -64 / data type of original image                    
ZNAXIS  =                    2 / dimension of original image                    
ZNAXIS1 =                12772 / length of original image axis                  
ZNAXIS2 =                15658 / length of original image axis                  
ZEXTEND =                    F /                                                
ZTILE1  =                12772 / size of tiles to be compressed                 
ZTILE2  =                    1 / size of tiles to be compressed                 
ZCMPTYPE= 'RICE_1  '           / compression algorithm                          
ZNAME1  = 'BLOCKSIZE'          / compression block size                         
ZVAL1   =                   32 / pixels per block                               
ZNAME2  = 'BYTEPIX '           / bytes per pixel (1, 2, 4, or 8)                
ZVAL2   =                    4 / bytes per pixel (1, 2, 4, or 8)                
```
And after writing:
```
In [8]: hdul.writeto('test.fits.fz', overwrite=True)

In [9]: hdul[1]._header['Z*']
Out[9]: 
ZIMAGE  =                    T / extension contains compressed image            
ZSIMPLE =                    T /                                                
ZTENSION= 'IMAGE   '           / binary table extension                         
ZBITPIX =                  -64 / data type of original image                    
ZNAXIS  =                    2 / dimension of original image                    
ZNAXIS1 =                  100 / length of original image axis                  
ZNAXIS2 =                  100 / length of original image axis                  
ZPCOUNT =                    0 / size of special data area                      
ZGCOUNT =                    1 / one data group (required keyword)              
ZTILE1  =                  100 / size of tiles to be compressed                 
ZTILE2  =                    1 / size of tiles to be compressed                 
ZEXTEND =                    F /                                                
ZCMPTYPE= 'RICE_1  '           / compression algorithm                          
ZNAME1  = 'BLOCKSIZE'          / compression block size                         
ZVAL1   =                   32 / pixels per block                               
ZNAME2  = 'BYTEPIX '           / bytes per pixel (1, 2, 4, or 8)                
ZVAL2   =                    4 / bytes per pixel (1, 2, 4, or 8)                
ZNAME3  = 'NOISEBIT'           / floating point quantization level              
ZVAL3   =                 16.0 / floating point quantization level              
ZHECKSUM= 'cFaIcEXIcEaIcEUI'   / HDU checksum updated 2016-10-25T20:37:21       
ZDATASUM= '648319781'          / data unit checksum updated 2016-04-28T17:06:07 
```

When creating a new HDU (e.g. `fits.CompImageHDU(data=hdul[1].data[:100, :100], compression_type='RICE_1')`) this does not happen because then astropy does not reuse the original header. In this case astropy adds ZEXTENSION but not ZSIMPLE. And it seems the code tries not to have both keyword at the same time, but when reusing the header here this fails somehow.
Also I don't think the standard requires ZBITPIX to be at a specific position or to have only one of ZEXTENSION and ZSIMPLE, so I guess funpack could be more flexible here.

**Comment by Pharisaeus** [comment]
I confirm that dropping one of those keywords seems to solve the problem with `funpack`.

> it seems the code tries not to have both keyword at the same time, but when reusing the header here this fails somehow

I don't see this in the code at all. There is just:

```python
            if 'SIMPLE' in image_header:
                self._header.set('ZSIMPLE', image_header['SIMPLE'],
                                 image_header.comments['SIMPLE'],
                                 before='ZBITPIX')
####
            if 'XTENSION' in image_header:
                self._header.set('ZTENSION', 'IMAGE',
                                 image_header.comments['XTENSION'],
                                 before='ZBITPIX')
```

So there is no such check. One could just do:

```python
            if 'XTENSION' in image_header and 'SIMPLE' not in image_header:
                self._header.set('ZTENSION', 'IMAGE',
                                 image_header.comments['XTENSION'],
                                 before='ZBITPIX')
```

To solve this issue.

I checked and `funpack`/`cfitsio` expects `ZSIMPLE` to be there and it doesn't like having only `ZEXTENSION`.

**Comment by cmarmo** [comment]
Hi all, I have tested the following snippet of code
```py
from astropy.io import fits

infile = 'ADP.2016-10-06T13 39 47.172.fits.fz'
outfile = "invalid.fits.fz"
slices = (slice(0, 100), slice(0, 100))
with fits.open(infile, checksum=True) as hdus:
    hdus[1].data = hdus[1].data[slices]
    hdus.writeto(outfile, overwrite=True, checksum=True)

with fits.open(outfile, checksum=True) as hdus:
    pass
```
with astropy 5.1 (still failing) and the current development version (working).
It seems to me that #13557 fixed this issue too. Am I wrong? Thanks!

**Comment by Pharisaeus** [comment]
@cmarmo I'm afraid not really, at least not completely. While your fix indeed makes funpack not crash anymore, if you try to do `fitsverify` on resulting unpacked file you get:

```
$ fitsverify invalid.fits

              fitsverify 4.20 (CFITSIO V3.470)
              --------------------------------


File: invalid.fits

1 Header-Data Units in this file.

=================== HDU 1: Primary Array ===================

*** Error:    Keyword #6, PCOUNT is not allowed in a primary array.
*** Error:    Keyword #7, GCOUNT is not allowed in a primary array.
*** Warning: Keyword DATE is duplicated in card #11 and card #408.

 411 header keywords

 32-bit integer pixels,  2 axes (100 x 100),

++++++++++++++++++++++ Error Summary  ++++++++++++++++++++++

 HDU#  Name (version)       Type             Warnings  Errors
 1                          Primary Array    1         2

**** Verification found 1 warning(s) and 2 error(s). ****
```

Essentially astropy copies also some other headers from the compressed header, and they should not be there.

The "fix" we're currently using seems to work a bit better (similar trick to what you did, but instead of dropping XTENSION we drop SIMPLE, because this was those additional copied header cards are not causing more issues):

```python
for hdu in hdus[1:]:
    header = hdu.header
    if 'XTENSION' in header and 'SIMPLE' in header:
        header.pop('SIMPLE')
        if 'EXTEND' in header:
            header.pop('EXTEND')
```

This way funpack still works and fitsverify says:

```
$ fitsverify invalid.fits

              fitsverify 4.20 (CFITSIO V3.470)
              --------------------------------


File: invalid.fits

2 Header-Data Units in this file.

=================== HDU 1: Primary Array ===================

 18 header keywords

 Null data array; NAXIS = 0

=================== HDU 2: Image Exten. ====================

 407 header keywords

 32-bit integer pixels,  2 axes (100 x 100),

++++++++++++++++++++++ Error Summary  ++++++++++++++++++++++

 HDU#  Name (version)       Type             Warnings  Errors
 1                          Primary Array    0         0
 2                          Image Array      0         0

**** Verification found 0 warning(s) and 0 error(s). ****
```

Notice, however, that this "fix" has the unfortunate effect of making the resulting file to have 2 extensions instead of just one.

**Comment by cmarmo** [comment]
Thanks @Pharisaeus for digging in.
I can't find in the FITS standard an explicit statement about `PCOUNT` and `GCOUNT` in Primary headers, but indeed fitsverify fails in this case.
I'm offering a Fix in #13753. Feel free to check if it fixes your issue, if you can find some time. Thanks.

**Comment by Pharisaeus** [comment]
@cmarmo thanks for looking into this issue!
With both fixes applied I now get:

```
$ fitsverify invalid.fits

              fitsverify 4.20 (CFITSIO V3.470)
              --------------------------------


File: invalid.fits

1 Header-Data Units in this file.

=================== HDU 1: Primary Array ===================

*** Warning: Keyword DATE is duplicated in card #9 and card #406.

 409 header keywords

 32-bit integer pixels,  2 axes (100 x 100),

++++++++++++++++++++++ Error Summary  ++++++++++++++++++++++

 HDU#  Name (version)       Type             Warnings  Errors
 1                          Primary Array    1         0

**** Verification found 1 warning(s) and 0 error(s). ****
```

Notice that the warning is essentially exactly the same problem, just a different flavour. I suspect that this keyword is present in only one HDU in compressed file, but when astropy saves the file back and creates the compressed HDU it puts all keywords into both HDUs (and later funpack places both values when unpacking the file).
I'm not convinced that trying to blacklist certain header keywords is really a way to go here, because there can be a lot of them, not only those in this one example file.

I wonder if there isn't a way to somehow store the initial list of keywords for each HDU when loading compressed file, and later restore only those particular keywords when saving back the file. Essentially to keep track of the fact that for example PCOUNT and GCOUNT were only present in second HDU, so they should not be inserted into the primary header when we're saving the file back.

**Comment by saimn** [comment]
> I wonder if there isn't a way to somehow store the initial list of keywords for each HDU when loading compressed file, and later restore only those particular keywords when saving back the file. Essentially to keep track of the fact that for example PCOUNT and GCOUNT were only present in second HDU, so they should not be inserted into the primary header when we're saving the file back.

The problem is that the header keywords from the original HDU  and the keywords from the compressed BINTABLE extension are mixed in the same header (great idea !). But that's really a problem for the few keywords specific to primary or extension HDUs, so with #13753 we should be good :crossed_fingers:

**Comment by Pharisaeus** [comment]
> we should be good

as long as someone doesn't care about warnings with duplicated keywords ;)

**Comment by cmarmo** [comment]
> > we should be good
> 
> as long as someone doesn't care about warnings with duplicated keywords ;)

Yes, there is still a warning: it is related to keyword duplication and not to primary / extension keywords, I'd rather to tackle it in a different PR. The issue is perhaps related to #11927 and asks for a bit more of understanding of the current code. Thanks for your patience.

**Comment by saimn** [comment]
I don't see the warning when testing locally with the change from #13753. Can you try again now that it is merged @Pharisaeus  ?

**Comment by cmarmo** [comment]
> I don't see the warning when testing locally with the change from #13753. Can you try again now that it is merged @Pharisaeus ?

I wonder if we are all testing the same file indeed... 
http://dataportal.eso.org/dataPortal/file/ADP.2016-10-06T13:39:47.172 does not throw warnings for me
```
405 header keywords
 
 64-bit double precision pixels,  2 axes (100 x 100), 
 
++++++++++++++++++++++ Error Summary  ++++++++++++++++++++++
 
 HDU#  Name (version)       Type             Warnings  Errors
 1                          Primary Array    0         0     
 
**** Verification found 0 warning(s) and 0 error(s). ****
```

**Comment by Pharisaeus** [comment]
@saimn @cmarmo thank you for all the help! 
The difference is that the script I'm actually using is a bit more complex than the example provided in this ticket, and it actually contains setting values of certain keywords, including 'DATE', which later results in the duplicated keyword warning.

You are correct that the initial code snippet works ok when run with astropy from current main branch. Duplicated keyword happens when you do something like:

```python
        infile = "ADP.2016-10-06T13_39_47.172.fits.fz"
        outfile = "invalid.fits.fz"
        slices = (slice(0, 100), slice(0, 100))
        with fits.open(infile, checksum=True) as hdus:
            import datetime
            primary_header = hdus[0].header
            primary_header['DATE'] = "{:%Y-%m-%dT%H:%M:%S}".format(datetime.datetime.utcnow())
            hdus[1].data = hdus[1].data[slices]
            hdus.writeto(outfile, overwrite=True, checksum=True)
```

Anyway, I confirm that on the current state of main branch, the initial errors with funpack and fitsverify are not present any more.

**Comment by saimn** [comment]
Yes sounds like a funpack issue, which merges the compressed extension header back into the primary HDU: 
```
❯ dfits -x 0 invalid.fits.fz | grep 'DATE\|xtension'
EXTEND  =                    T / FITS dataset may contain extensions
DATE    = '2022-09-28T09:39:34'
====> xtension 1
XTENSION= 'BINTABLE'           / binary table extension
ZIMAGE  =                    T / extension contains compressed image
EXTNAME = 'COMPRESSED_IMAGE'   / name of this binary table extension
DATE    = '2014-01-24T11:08:59' / Date the file was written
DATE-OBS= '2013-12-10T03:08:14.4297'    / Observing date
HIERARCH ESO INS DATE        = '2008-02-15' / Instrument release date (yyyy-mm-d
HIERARCH ESO INS FILT1 DATE  = '2013-12-08T21:34:18' / Filter index time
HIERARCH ESO TEL AO DATE     = '2013-12-10T03:09:18' / Last closed loop aO
HIERARCH ESO TEL AO M1 DATE  = '2013-12-10T03:09:18' / Last M1 update
HIERARCH ESO TEL AO M2 DATE  = '2013-12-10T03:09:22' / Last M2 update
HIERARCH ESO TEL DATE        = 'not set '   / TCS installation date
SOFTDATE= '$Date: 2013-06-21 11:16:50 $' / CIRDR release date


❯ dfits -x 0 invalid.fits | grep 'DATE\|xtension'   
DATE    = '2014-01-24T11:08:59' / Date the file was written
DATE-OBS= '2013-12-10T03:08:14.4297'    / Observing date
HIERARCH ESO INS DATE        = '2008-02-15' / Instrument release date (yyyy-mm-d
HIERARCH ESO INS FILT1 DATE  = '2013-12-08T21:34:18' / Filter index time
HIERARCH ESO TEL AO DATE     = '2013-12-10T03:09:18' / Last closed loop aO
HIERARCH ESO TEL AO M1 DATE  = '2013-12-10T03:09:18' / Last M1 update
HIERARCH ESO TEL AO M2 DATE  = '2013-12-10T03:09:22' / Last M2 update
HIERARCH ESO TEL DATE        = 'not set '   / TCS installation date
SOFTDATE= '$Date: 2013-06-21 11:16:50 $' / CIRDR release date
DATE    = '2022-09-28T09:39:34'
```
