### ISSUE TITLE
to_pandas() from binned timed series with bin_time_start

### ISSUE THREAD

**Issue by bmm936** [astropy/astropy#12014]
### Description

I had a problem with astropy binned time series. I have created such an object using the aggregate_downsample function where I specify the time_bin_start = TimeDelta(-600.,format='sec'). When I try to use the to_pandas() function on this binned time series, I get the following error:
```
  File "C:\Users\bmm93\anaconda3\lib\site-packages\astropy\table\table.py", line 3314, in to_pandas
    kwargs = {'index': out.pop(index)} if index else {}
KeyError: 'time_bin_start'
```
I have not had trouble with to_pandas() before specifying time_bin_start. 

I got response from a user on the 'Python users in Astronomy' Facebook group:
"This looks like astropy 4.0.x, and a real bug at that.
Unfortunately with 4.3 or later I can confirm the same even without specifying `time_bin_start`!
It should work with `to_pandas(index=False)` – can you check if that returns sensible results?
But it would be great if you could submit an issue about this."

I then tried 'to_pandas(index=False)' and I got sensible results. I am using astropy version 4.0.2.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by dhomeier** [comment]
To point out the behaviour in 4.0 and 5.0, current dev gives
```python
>>> tss = timeseries.aggregate_downsample(ts, time_bin_size=5*u.s)
>>> tss.to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/derek/opt/lib/python3.9/site-packages/astropy/table/table.py", line 3744, in to_pandas
    idx = out.pop(index)
KeyError: 'time_bin_start'
```
even without a `time_bin_start` option given, whereas 4.0.2-4.3 have
```python
>>> tss = timeseries.aggregate_downsample(ts, time_bin_size=5*u.s, time_bin_start=input_time[1])
>>> tss.to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.6/site-packages/astropy/table/table.py", line 3310, in to_pandas
    kwargs = {'index': out.pop(index)} if index else {}
KeyError: 'time_bin_start'
```
In both version both workarounds pass, though with different results:
```python
>>> tss.to_pandas(index=False)
   time_bin_start.jd1  time_bin_start.jd2  time_bin_size           a
0           2457470.0            0.021169            5.0    5.333333
1           2457470.0            0.021227            5.0   30.333333
2           2457470.0            0.021285            5.0  135.666667
>>> table.Table(tss).to_pandas()
                     time_bin_size           a
time_bin_start                                
2016-03-22 12:30:29            5.0    5.333333
2016-03-22 12:30:34            5.0   30.333333
2016-03-22 12:30:39            5.0  135.666667
```

**Comment by pllim** [comment]
Sounds like a regression... @taldcroft or @mhvk ?

**Comment by taldcroft** [comment]
Can we get some steps to reproduce?

**Comment by dhomeier** [comment]
Setting the above up with
```python
>>> import numpy as np; from astropy import table, time, timeseries, units as u
>>> input_time = time.Time(['2016-03-22T12:30:30.99', '2016-03-22T12:30:32', '2016-03-22T12:30:33', '2016-03-22T12:30:37', '2016-03-22T12:30:38.5', '2016-03-22T12:30:39', '2016-03-22T12:30:40.5', '2016-03-22T12:30:41.4', '2016-03-22T12:30:42.5'])
>>> 
>>> ts = timeseries.TimeSeries(time=input_time, data=[[1, 2, 13, 24, 25, 42, 103, 102, 202.]], names=['a'])
```

**Comment by taldcroft** [comment]
I think I have a fix, PR coming hopefully.
