### ISSUE TITLE
FITS header verification change from astropy version 4.2 to 4.2.1 (re-opening issue #11815)

### ISSUE THREAD

**Issue by cbethge** [astropy/astropy#12035]
Re-opening #11815. Sorry for doing it by submitting a new issue, I could not reopen the old report myself and could also not comment on it.

#11815 was closed on June 7 as it was supposed to get fixed with astropy version 4.3. I just updated to 4.3 and this is still an issue.

**Comment by pllim** [comment]
I re-opened that other issue for you. :)
