### ISSUE TITLE
Use structured quantities in Representations

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#12030]
Now that #11775 is in, we can start using structured arrays with units! I'm turning some comments from #3777 into feature requests.

> One place where this concept would be useful is for making the `Representation` classes a bit nicer (they are a bit clunky right now IMO). If I recall, they currently store everything internally as Cartesian coordinates? But in principle, if I create a `SphericalRepresentation` it could avoid that conversion step unless necessary and store the position (length, angle, angle) as a single array (or just be an array/recarray subclass). Do you have any thoughts on this @mhvk or @eteq ?

_Originally posted by @adrn in https://github.com/astropy/astropy/issues/3777#issuecomment-239268631_

> @adrn - ... I do think there might be some benefits to using recarray instead, as it would remove some boiler-plate ...

_Originally posted by @mhvk in https://github.com/astropy/astropy/issues/3777#issuecomment-239268631_

**Comment by mhvk** [comment]
Currently, `SphericalRepresentation` stores the angles and the distance as separate arrays (and similarly for all other representations); it may be useful to instead store them as a structured quantity. It would simplify `repr` and perhaps give some speed-ups for transformations (to be checked). For `CartesianRepresentation`, we do track whether a 3-element XYZ array was passed in.

**Comment by adrn** [comment]
> For CartesianRepresentation, we do track whether a 3-element XYZ array was passed in.

Though, will these work off the bat? If not, we may want to make sure they do...
```python
>>> import astropy.units as u
>>> import numpy as np
>>> data1 = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)], dtype=[('x', 'f8'), ('y', 'f8'), ('z', 'f8')]) * u.Unit('pc, pc, pc')
>>> data2 = np.array([([1, 2, 3], ), ([4, 5, 6], )], dtype=[('xyz', '(3,)f8')]) * u.Unit('pc')
>>> coord.CartesianRepresentation(data1)
>>> coord.CartesianRepresentation(data2)
```

**Comment by mhvk** [comment]
Right now, structured arrays definitely do not work. But I agree they should!

**Comment by nstarman** [comment]
I actually think this ends up being a bad idea. We want to use `dataclasses.dataclass` with Quantity fields. See https://github.com/GalacticDynamics/coordinax
