### ISSUE TITLE
config : inconsistent behavior in handling of values of type list

### ISSUE THREAD

**Issue by orionlee** [astropy/astropy#12033]
## Problem

When I want to specify a list as value in [configuration](https://docs.astropy.org/en/stable/api/astropy.config.ConfigItem.html), the behavior seems to be inconsistent and unintuitive.

I will use the existing `css_urls` of `table.jsviewer` as an example. The configuration is:
```
## The URLs to the css file(s) to include.
# css_urls = ['https://cdn.datatables.net/1.10.12/css/jquery.dataTables.css']
```

- The generated config gives the impression that the list should be in the form of a python list, 
- but in practice, using python list will lead to errors. 
- Instead, it expects a kind of comma-separated string.

## Example

For the following code snippets that access the config value, 
```
from astropy.table.jsviewer import conf
print(conf.css_urls)
```

the behavior of reading it: 
- if I uncomment the line in `astropy.cfg`, i.e., specify the value as a list, it results in an error:
```
TypeError: Configuration value not valid:the value "['https://cdn.datatables.net/1.10.12/css/jquery.dataTables.css']" is of the wrong type.
```

- if I specify the value as a comma-separated list, it works. E.g., it works with the following line
```
css_urls = https://cdn.datatables.net/1.10.12/css/jquery.dataTables.css,http://acme.net/foo.css
```

- For a single value, it must end with a comma. E.g., (notice the triling comma at the end. It is neeed)
```
css_urls = https://cdn.datatables.net/1.10.12/css/jquery.dataTables.css,
```

- For a single value, if it does not end with a comma, it also results in an error:
```
TypeError: Configuration value not valid:the value "https://cdn.datatables.net/1.10.12/css/jquery.dataTables.css" is of the wrong type.
```

## Desirable behavior
- If the intent for list-type config item is to accept python list as value, then there are bugs in parsing the config file
- If the intent is to accept a comma-separated string as value, then
  - generated config should not output value as python list
  - requiring an extra trailing comma for single-value case is unintuitive.

## Versions:
- seen in astropy 4.2.1 and 4.1. The issue persists in the current `main`.

---

Reference:
https://github.com/astropy/astropy/blob/f5355161c9df1cb3580a367549501f89f04d80ce/astropy/table/jsviewer.py#L24-L27

**Comment by pllim** [comment]
I think this is a bug of serializing `cfgtype='list'` into `astropy.cfg`. But I am not sure if the fix should be here in

https://github.com/astropy/astropy/blob/20d6808fa5e00d18df518a9e93ca03fcad092fd3/astropy/config/configuration.py#L593

or deeper in the machinery. This is what worked in `~/.astropy/config/astropy.cfg` to define an one-element list (note the trailing comma):

```yaml
## The URLs to the css file(s) to include.
css_urls = https://cdn.datatables.net/1.10.12/css/jquery.dataTables.css,
```

**Comment by pllim** [comment]
p.s. Strictly speaking, `css_urls` should have `cfgtype='string_list'` but that is a separate issue.

https://github.com/astropy/astropy/blob/20d6808fa5e00d18df518a9e93ca03fcad092fd3/astropy/table/jsviewer.py#L27

**Comment by pllim** [comment]
See #12037 for proposed fix.

**Comment by orionlee** [comment]
I also want to make note that currently, if one want so explicitly specify empty list as the value, a comma is needed. E.g., it needs to be: 
```
css_urls = ,
```

**Comment by pllim** [comment]
Huh, the `item = ,` is not intuitive but you are indeed correct. I added that to #12037 as well. Thanks!
