### ISSUE TITLE
No Attribute 'RA'

### ISSUE THREAD

**Issue by hamed-AM** [astropy/astropy#12066]
### Description
Hi
I would like to simply compute Hour Angle for a given R.A and Sidereal Time using astropy.coordinates.angles.RA class as per:

https://kbarbary-astropy.readthedocs.io/en/latest/_generated/astropy.coordinates.angles.RA.html#astropy.coordinates.angles.RA

### Actual behavior
It returns there is no 'RA' attribute for this class:

astropy.coordinates.angles.RA('10.2345d')
AttributeError: module 'astropy.coordinates.angles' has no attribute 'RA'

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by pllim** [comment]
That link you provided is not our documentation. Not sure how you got it. Please consult https://docs.astropy.org/en/stable/coordinates/index.html

**Comment by dhomeier** [comment]
That link above was for an extremely old version.
Note that the current implementation has a `SkyCoord.ra` property for Right Ascension, but made the very unfortunate design choice of using `hourangle` as a method to access simply the given angle in _units_ of hours.
Real support to calculate the Hour Angle seems to only have been added back in #11676, and would probably deserve some better documentation.

For a simpler approximation you might set an `astropy.time.Time` for the appropriate `location` and then use
```python
t.sidereal_time('apparent') - coord.ra
```

**Comment by mkbrewer** [comment]
If you want the apparent hour angle, you should first transform the the ICRS right ascension to the true equator and equinox of date. 
```
coord.transform_to(TETE(obstime=my_time, location=my_location))
```

**Comment by hamed-AM** [comment]
Thank you very much for your replies.

My next step is to calculate Alt Az tracking rates for a given star at my location.

I didn't find any routine in astropy to perform such calculation. Could you also advice on this?

Bests

**Comment by mkbrewer** [comment]
Personally, I'd just create an array of Alt-Az at one second intervals and then use `numpy.diff`, but there may well be a more clever way of going about this that I am  not aware of.

**Comment by hamed-AM** [comment]
> If you want the apparent hour angle, you should first transform the the ICRS right ascension to the true equator and equinox of date.
> 
> ```
> coord.transform_to(TETE(obstime=my_time, location=my_location))
> ```

While trying to transform to true equator and equinox I get this error:
NameError: name 'TETE' is not defined

Trying to import TETE (similar to importing FK5 in doc example) does not affect anything.

**Comment by mkbrewer** [comment]
You must be using Astropy version 4.2 or later in order to use TETE.
