### ISSUE TITLE
Customize astropy logger: timestamp, custom stack info

### ISSUE THREAD

**Issue by vertighel** [astropy/astropy#12080]
### Description

It would be very userful to provide the possibility to add the following features to astropy logger:

- A timestamp option;
- The possibility to extend/reduce stack info: now only the caller function is shown. Enabling or disabling called module, class and method/function would be useful

Example:

`log.date=False`
`log.time=True`
`INFO:    17:06:41 > My Message [ my_module MyClass.my_method ] called by [my_test]`

`log.iso=True`
`log.verbose = 1`
`INFO: 2021-08-20T17:06:41 > My Message [my_test]`

`log.timestamp=False`
`log.verbose = 0`
`INFO: My Message`

 
### Additional context

This would be useful for astropy-based data reduction pipelines.

**Comment by nstarman** [comment]
Thanks @vertighel. While these look very useful, Astropy's logger is intended for internal use only and may (🤞) be deprecated (@embray can comment in more detail). We have a note in the module's docstring to this effect:

```
.. note::
    This module is meant for internal ``astropy`` usage. For use in other
    packages, we recommend implementing your own logger instead.
```

As Astropy is open sourced you are welcome to copy (and attribute) Astropy's logging code!

**Comment by pllim** [comment]
@nstarman is correct. We would advise you use Python's native logging capabilities or a third-party package that specializes in logging. We apologize for any inconvenience caused.

**Comment by nstarman** [comment]
Oops. It looks like the close bot triggers for every added label... Testing

**Comment by pllim** [comment]
Ops... maybe I should temporary disable it until I have time to revisit the stalebot. Sorry about that.

**Comment by nstarman** [comment]
Is the same trigger condition as the Extra CI label?

**Comment by pllim** [comment]
Probably, given they were written by the same person. 😆
