### ISSUE TITLE
Cannot use older versions of constants

### ISSUE THREAD

**Issue by eerovaher** [astropy/astropy#12082]
### Description
The documentation describes how to use an older set of physical constants. I tried to follow this example: https://github.com/astropy/astropy/blob/8f1ae4eb61aee209911234883e462fe0addffeca/docs/units/constants_versions.rst#L16-L21

### Actual behavior

This is what happens since d54a9a360042a8083583ce8ed62bb1adf6448ef7:
```python
>>> import astropy
>>> astropy.physical_constants.set('codata2010')
Traceback (most recent call last):
...
TypeError: set() takes 2 positional arguments but 3 were given
```

### Expected behavior 

This is how it worked in 169fd6e6ec17dfcb91ecee0525d96228556c97ca (the parent of d54a9a360042a8083583ce8ed62bb1adf6448ef7):
```python
>>> import astropy
>>> astropy.physical_constants.set('codata2010')
<ScienceState physical_constants: 'codata2010'>
```

I am not sure if d54a9a360042a8083583ce8ed62bb1adf6448ef7 introduced a bug or if it's the documentation that needs to be updated, but having a completely broken example in the docs is not good either way.

**Comment by pllim** [comment]
Oh no! How did this get past the CI? `coordinates` changes should not have changed `constants` behavior... and #10624 was in since 4.2. 😱

**Comment by nstarman** [comment]
Yikes. That'll need a backport.

**Comment by nstarman** [comment]
Thankfully it's a super easy fix. I'm opening a PR now.

**Comment by nstarman** [comment]
Thanks @eerovaher for the find!
