### ISSUE TITLE
Improve TOC for mixin column section in table docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#12098]
The TOC for the mixin columns in the table docs looks a bit strange, I wonder if some of the section headings are not at the right level? If they are, it might be worth renaming the examples to make them more explicit:

<img width="208" alt="Screenshot 2021-08-20 at 21 59 03" src="https://user-images.githubusercontent.com/314716/130292898-d847681a-5faa-48ad-b98b-6c8f8a96cc8f.png">

**Comment by eerovaher** [comment]
This has been fixed by #12011.

**Comment by astrofrog** [comment]
Great, thanks!
