### ISSUE TITLE
Issue with computing altitude

### ISSUE THREAD

**Issue by pearsonkyle** [astropy/astropy#12101]
### Description

The altitude and airmass values I'm trying to calculate do not match online star charts 

### Expected behavior

I was expecting the air mass to return a value between 1 and 1.2 using the code below. 
 
The data I'm comparing to is this chart: 

https://astro.swarthmore.edu/transits/plot_airmass.cgi?observatory_string=33.356%3B-116.863%3BPST8PDT%3BPalomar%20Observatory&observatory_latitude=33.356&observatory_longitude=-116.863&target=HD%20189733%20b&ra=20:00:43.71&dec=+22:42:39.1&timezone=PST8PDT&jd=2459448.64055302&jd_start=9448.675&jd_end=9448.751&use_utc=0&max_airmass=2.4 

### Actual behavior

The airmass is way too large for what it should be. Am I missing something with my time conversion? 

Leaving time in UTC gives me an airmass around 7, and converting it into local yields -1.8. Neither of those are correct, the real value should be around 1.1

### Steps to Reproduce

```python
import astropy.units as u
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation, AltAz

p200 = EarthLocation.of_site('Palomar')
dec = '+20:00:43.71'
ra = '22:42:39.071'
hd189 = SkyCoord(ra,dec, unit=u.deg)
t = Time(2459448.7114744745, format='jd') # UTC time.    (should be roughly 10PM PST on 08/21/2021)
frame = AltAz(obstime=t, location=p200)
altaz = hd189.transform_to(frame)
airmass = altaz.secz
```

### System Details

macOS-10.15.7-x86_64-i386-64bit
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ]
Numpy 1.19.5
astropy 4.3.dev751+gd41e5e441
Scipy 1.6.2
Matplotlib 3.2.2

**Comment by mkbrewer** [comment]
You should take a closer look at what you have there for coordinates. I'd suggest that what you really want is: 
```
unit=(u.hour, u.deg)
```

**Comment by mkbrewer** [comment]
It also seems that you have the declination and right ascension reversed.

**Comment by pearsonkyle** [comment]
Beautiful! Thanks to both of you for your patience. Had a late-night observation and was obviously out of it at the time of this post. Just user error


The updated code now works as intended
```python

    import astropy.units as u
    from astropy.time import Time
    from astropy.coordinates import SkyCoord, EarthLocation, AltAz

    p200 = EarthLocation.of_site('Palomar')
    ra = '20:00:43.71'
    dec = '+22:42:39.071'
    hd189 = SkyCoord(ra,dec, unit=(u.hour, u.deg))
    t = Time(2459448.7114744745, format='jd') # UTC time.    (should be roughly 10PM PST on 08/21/2021)
    frame = AltAz(obstime=t, location=p200)
    altaz = hd189.transform_to(frame)
    airmass = altaz.secz
```
