### ISSUE TITLE
Cosmology methods eat units of array-like Quantity

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#12127]
Many cosmology methods start with
```
        if isiterable(z):
            z = np.asarray(z)
```
This eats any units, so is unsafe:
```
In [6]: Planck18.Tcmb([0., 1.]*u.m)
Out[6]: <Quantity [2.7255, 5.451 ] K>
```

Probably should be replaced with `u.Quantity(z, u.dimensionless_unscaled).value` (or just `u.Quantity(z, cu.redshift)` though that will be slower).

p.s. Noticed this while looking at some of the PRs.

**Comment by nstarman** [comment]
@mhvk, I think there might be an even simpler solution:  ``np.asarray`` -> ``np.asanyarray``.
This passes Quantity through, unchanged.

**Comment by mhvk** [comment]
Yes, that should work too, indeed.
