### ISSUE TITLE
Pep8 doesn't speak to the walrus

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#12147]
### Description

Pep8speaks doesn't like walrus operators.

### Expected behavior

Now that we are py3.8+ (#11934), this should not trip up the checker.

### Actual behavior

Pep8speaks flags ``:=`` as invalid syntax.

https://github.com/astropy/astropy/pull/12136#issuecomment-912842320

### Steps to Reproduce

Push code with a ``:=`` to astropy.

### System Details

N/A.

**Comment by nstarman** [comment]
@pllim I see this issue has been raised in https://github.com/OrkoHunter/pep8speaks/issues/173
A suggested fix is to use `pycodestyle` over flake8.
Or we could just wait until https://github.com/OrkoHunter/pep8speaks/issues/173 is fixed...

**Comment by pllim** [comment]
If upstream can fix it within reasonable time frame, we can wait?

**Comment by pllim** [comment]
@nstarman , I don't see why we cannot use pycodestyle for pep8speaks, but I'd rather not switching *everything* from flake8 to pycodestyle, does that make sense?

@bsipocz , any advise here?

**Comment by bsipocz** [comment]
flake8 does much more than pycodestyle so there shouldn't be a downgrade switch, the early adoption of walrus doesn't worth it imo. For cases like this, do patch upstream.

**Comment by nstarman** [comment]
Just confirming, pep8speaks only runs on the diff. So a walrus in the codebase wouldn't make future PRs error, right?

**Comment by pllim** [comment]
> So a walrus in the codebase wouldn't make future PRs error, right?

Theoretically, no.

**Comment by nstarman** [comment]
Can confirm it only complains on new PRs. There are now a few walruses in the code and they are not stirring up trouble.

Side note. pep8speaks also complains about positional-only arguments

```python
def function(x, /):
    print(x, "is a positional-only argument")
```

**Comment by nstarman** [comment]
We don't have pep8speaks anymore!
