### ISSUE TITLE
`divide by zero encountered in double_scalars` when converting units using `equivalencies`

### ISSUE THREAD

**Issue by atharva-2001** [astropy/astropy#12164]
### Description

Converting wavelength to frequency using `equivalencies` returns a warning if the wavelength is zero. 
```
/home/atharva/miniconda3/envs/astropy-test/lib/python3.9/site-packages/astropy/units/equivalencies.py:126: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
```
### Expected behavior

The code returns `inf Hz`, but with the warning, which it shouldn't. 

### Steps to Reproduce

```python
import astropy.units as u
a = 0* u.AA
a = a.to(u.Hz, equivalencies=u.spectral())
print(a)
```
Returns:
```
/home/atharva/miniconda3/envs/astropy-test/lib/python3.9/site-packages/astropy/units/equivalencies.py:126: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
inf Hz
```
Any other value apart from zero doesn't cause the warning. 
```py
import astropy.units as u
import math
a = math.inf* u.AA
a = a.to(u.Hz, equivalencies=u.spectral())
print(a) # 0.0 Hz
```
### System Details

```
Linux-5.8.0-55-generic-x86_64-with-glibc2.29
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
Numpy 1.21.2
astropy 5.0.dev828+g23404eeb2
```

**Comment by pllim** [comment]
I don't see anything wrong here. What do you expect from a zero wavelength?

```
c = lambda * nu
nu = c / lambda
```

**Comment by pllim** [comment]
It is dividing by zero. If you do not like the warning, you could handle it using https://docs.python.org/3/library/warnings.html

**Comment by atharva-2001** [comment]
You're right, pardon my ignorance on this topic, but I thought it had something to do with https://github.com/astropy/astropy/issues/7365 or https://github.com/astropy/astropy/pull/11127 
and wondered if the intended result was being displayed. If it is so, this issue can be closed.

**Comment by pllim** [comment]
Let's ping @mhvk to be sure!

**Comment by mhvk** [comment]
@pllim is right - we're just propagating the numpy warning here, and I think that is probably the best thing to do, since it is quite likely to be a bug if the wavelength is zero. 

That is not to say one could not have decided otherwise, and it is always good to think about these issues, so still good to report if something does not feel logical!
