### ISSUE TITLE
np.median drops units if the result is `nan`

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#12165]
As reported by @larrybradley in https://github.com/astropy/astropy/pull/12146#discussion_r707509816:
`np.median` drops the unit on `Quantity` input where the result is `nan`:
```python
>>> import numpy as np
>>> import astropy.units as u
>>> data = np.array([1., 2, np.nan, 3, 4]) << u.km
>>> np.median(data)
nan
>>> np.mean(data)
<Quantity nan km>
>>> np.var(data)
<Quantity nan km2>
```

Note that it works fine on multi-dimensional output:
```
In [6]: np.median([[1, 2], [np.nan, 3]] << u.km, axis=1)
Out[6]: <Quantity [1.5, nan] km>
In [8]: np.median([[1, np.nan], [np.nan, 3]] << u.km, axis=1)
Out[8]: <Quantity [nan, nan] km>
```

**Comment by mhvk** [comment]
At some level, this reflects a problem upstream: while generally the numpy code deals well with subclasses, it seems it does not for this particular case - which I clearly had not noticed, so `np.median` is listed as a "subclass-safe" function at https://github.com/astropy/astropy/blob/23404eeb2caeea315cea89b6cb8b9b2fee4f13be/astropy/units/quantity_helper/function_helpers.py#L82

**Comment by nstarman** [comment]
@mhvk, is this something we could fix with #11893 ?

I'm planning on returning to this soon as my PR for ``to/from_format("astropy.model")`` requires a quantity-aware ``np.vectorized``.

**Comment by mhvk** [comment]
@nstarman - no, it is really a bit of a numpy bug, which we can work around in `function_helpers`.

**Comment by mhvk** [comment]
See https://github.com/numpy/numpy/pull/19869#pullrequestreview-753161759 for the upstream fix.  We could fix it for existing numpy versions if need be.

**Comment by nstarman** [comment]
Would that be in ``combat`` or a ``median``-specific ufunc override?

**Comment by mhvk** [comment]
> Would that be in `compat` or a `median`-specific ufunc override?

I was thinking of a numpy-version dependent override of `np.median` in `units.quantity_helpers.function_helpers`. Obviously, if we go that route, the work-arounds in `stats` can be removed.
