### ISSUE TITLE
ModuleNotFoundError after upgrading astropy to version 4.3.1

### ISSUE THREAD

**Issue by viveikjha** [astropy/astropy#12172]
I am running a code named: PyQSOFit and I encountered an error related to astropy when importing the 'blackbody' model.
This code imports blackbody_lambda from astropy.modeling.blackbody.

I had recently upgraded the astropy module to 4.3.1. I searched the astropy documentation but have not found the 'blackbody_lambda" module so far...although the 'Blackbody' module is there.  The error is attached below. I have not been able to solve it so far. Any help will be really appreciated...
Thanks.
`Traceback (most recent call last): File "fit_the_spectrum.py", line 10, in <module> from PyQSOFit import QSOFit,manygauss,onegauss File "/home/vivek/workhub/asymmetry-work/PyQSOFit.py", line 19, in <module> from astropy.modeling.blackbody import blackbody_lambda ModuleNotFoundError: No module named 'astropy.modeling.blackbody'`

**Comment by eerovaher** [comment]
The [change log](https://docs.astropy.org/en/stable/changelog.html#id12) says that the `astropy.modeling.blackbody` module was removed in version 4.3. You might find [this page](https://docs.astropy.org/en/lts/modeling/blackbody_deprecated.html) helpful for updating your code.
