### ISSUE TITLE
RA/Dec of asteroid SkyCoord from satellite SkyCoord

### ISSUE THREAD

**Issue by nkelhos** [astropy/astropy#12186]
I'm trying to get the RA/Dec of an asteroid when viewed from a particular satellite.  I have the asteroid's 3D coordinates from astroquery.jplhorizons, and I have the satellite's lat/lon/alt from its datafiles.  I think the right way to do this is with astropy.coordinates.SkyOffsetFrame, but I'm not 100% sure.  I have an example script below:

```
#!/usr/bin/env python
from astropy import units
from astropy.time import Time
from astropy.coordinates import SkyCoord
from astropy.coordinates import SkyOffsetFrame
from astropy.coordinates.builtin_frames import CustomBarycentricEcliptic

# asteroid is from jpl-horizons, this is their custom frame
JPLFrame = CustomBarycentricEcliptic( obliquity=84381.448 * units.arcsec )

# mjd times
t = [57170.0187133196,57170.0190600000,57170.0194072222]
t = Time( t, format='mjd' )

# satellite coordinates
fx  = [-6.070489032e+10,-6.070428525e+10,-6.070368123e+10]
fy  = [-1.386698494e+11,-1.38670121e+11,-1.386703998e+11]
fz  = [-20180790.6,-20112703.04,-20041758.69]
sat = SkyCoord( x=fx, y=fy, z=fz, unit='meter', frame=JPLFrame, representation_type='cartesian' )

# asteroid coordinates
tx  = [-6.070621538e+10,-6.070542194e+10,-6.070462727e+10]
ty  = [-1.393267812e+11,-1.393271418e+11,-1.39327503e+11]
tz  = [996027003.3,996027087.2,996027171.1]
ast = SkyCoord( x=tx, y=ty, z=tz, unit='meter', frame=JPLFrame, representation_type='cartesian' )

origin = SkyOffsetFrame(origin=sat)
coord  = ast.transform_to( origin ).transform_to('fk5')

print('asteroid ra/dec (FK5 J2000.0)') 
print('when viewed from satellite:')
for i in range(len(t)) :
  print('%10.6f'%coord.ra.degree[i], '%10.6f'%coord.dec.degree[i], 'deg')
```

I guess I have a few questions:
1) is this the right way to do this?  The language of the [doc page](https://docs.astropy.org/en/stable/coordinates/matchsep.html#sky-offset-frames) makes me a little uncertain that this is what SkyOffsetFrame is actually for...
2) I'm creating 3 SkyOffsetFrames.  Is the transform_to(origin) applying the ith origin to the ith asteroid coordinate (and not just using the first origin for all of them)?
3) Is this the instantaneous RA/Dec, or does this account for the speed of light?

**Comment by adrn** [comment]
Hi @nkelhos 👋 

Thanks for the questions here. We primarily use GitHub issues for tracking new feature requests, bugs, etc., and we are launching a new user forum for questions about functionality or using Astropy code (like these questions). Would you mind posting your question at our new [Astropy Discourse page](https://community.openastronomy.org/c/astropy/8) instead? If not, would you mind if I posted it there on your behalf?

thanks!

**Comment by nkelhos** [comment]
Ah, I'll try to add my next question there.  I've sort of fixed this problem by using the AltAz frame, but its still giving weird results compared to jpl's horizons.
