### ISSUE TITLE
Broken links at module-astropy.visualization

### ISSUE THREAD

**Issue by JonCook** [astropy/astropy#12181]
Hello,

I noticed on the following documentation page:
- https://docs.astropy.org/en/stable/visualization/index.html#module-astropy.visualization

That the links in the diagram are broken. e.g)
- https://docs.astropy.org/en/api/astropy.visualization.LogStretch.html#astropy.visualization.LogStretch

Thanks
Jonathan

**Comment by pllim** [comment]
Clicking on "LogStretch" in https://docs.astropy.org/en/stable/visualization/index.html#classes brings me to https://docs.astropy.org/en/stable/api/astropy.visualization.LogStretch.html#astropy.visualization.LogStretch , which works fine. How did you manage to get that second link without "stable" in it?

**Comment by pllim** [comment]
Ah, I think you have stumbled upon astropy/sphinx-automodapi#48 . This requires a fix over at `sphinx-automodapi` and it is a long-standing bug. For now, avoid clicking on the chart and use the link from API listing instead. We apologize for any inconvenience caused.

**Comment by pllim** [comment]
Also see #4935

**Comment by JonCook** [comment]
Thanks for the update. Sorry if it was already reported.
