### ISSUE TITLE
Backwards incompatibility in fits.open

### ISSUE THREAD

**Issue by melanieclarke** [astropy/astropy#12223]
### Description

The check for a missing SIMPLE card included in astropy v4.3 breaks backwards compatibility in fits.open.  Archival data that contains the SIMPLE keyword, but in an unexpected format, produces an error when opened with default parameters in fits.open.  Prior to v4.3, these files were opened and handled normally.

The associated pull request is: https://github.com/astropy/astropy/pull/10895.

This break in backwards compatibility will require us to change every fits.open command we have that might deal with non-standard archival data.  This is hundreds of lines of code, across many separate packages.  The data cannot easily be changed.

### Expected behavior

fits.open opens files that can be read as FITS without throwing an error by default.

### Actual behavior

The error "No SIMPLE card found, this file does not appear to be a valid FITS file" is produced and the file is not opened as an HDUList.  The SIMPLE card is present and readable, though, and setting ignore_missing_simple=True allows the file to be opened and handled normally.

### Steps to Reproduce

This issues an error with a minimal FITS file containing:
'SIMPLE  =                         T / does conform to FITS standard'

```python
from astropy.io import fits
hdul = fits.open('test.fits')
```

This succeeds:
```python
from astropy.io import fits
hdul = fits.open('test.fits', ignore_missing_simple=True)
```

### System Details

macOS-10.15.7-x86_64-i386-64bit
Python 3.8.2 (default, Mar 26 2020, 10:43:30) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.20.3
astropy 4.3.1
Scipy 1.7.1
Matplotlib 3.4.2

**Comment by kYwzor** [comment]
This occurs because `io.fits` expects this exact sequence of characters to be within the first 30 bytes of the file:
```
SIMPLE  =                    T
```

This check obviously fails if the file's spacing is non-standard. As I mentioned in the pull request, I propose replacing:
https://github.com/astropy/astropy/blob/c6cafcb763c9a2cf6cbbc1989d7fbb6dbdb6932f/astropy/io/fits/hdu/hdulist.py#L1084-L1085
with:
`match_sig = re.match(rb"SIMPLE *= *[T|F]", simple)`

This would still allow `io.fits` to terminate early when no `SIMPLE` card is present at the beginning of the file, while being tolerant of non-standard spacing.

**Comment by saimn** [comment]
```
 'SIMPLE = T / does conform to FITS standard'
```
Well the comment is quite funny since this card doesn't respect the FITS standard :grimacing: 

@melanieclarke - To get a better understanding of how widespread the issue is, do you know how those files were produced ?

**Comment by melanieclarke** [comment]
It is a raw FITS file produced by the EXES instrument on SOFIA.  I can't say how widespread the problem is; prior to v4.3 astropy didn't even issue a warning for the non-standard spacing in the SIMPLE keyword, so I didn't know it was there. It may be as many as most or all EXES files in the SOFIA archive since they were all produced by the same control software.

**Comment by saimn** [comment]
> The value field must be in one of two formats: fixed or free. The **fixed-format is required for values of mandatory keywords** and is recommended for values of all other keywords.

(see https://github.com/astropy/astropy/pull/10895#issuecomment-892560888)

**Comment by maxnoe** [comment]
fitsverify also complains (an error, not a warning):

```
❯ ./fitsverify test_inv.fits
 
              fitsverify 4.20 (CFITSIO V4.000)              
              --------------------------------              
 
 
File: test_inv.fits

2 Header-Data Units in this file.
 
=================== HDU 1: Primary Array ===================
 
*** Error:   SIMPLE   mandatory keyword is not in logical fixed format:
SIMPLE  = T                    / conforms to FITS standard
          -------------------^
 
 5 header keywords
 
 Null data array; NAXIS = 0 
 
=================== HDU 2: BINARY Table ====================
 
 11 header keywords
 
   (1 columns x 3 rows)
 
 Col# Name (Units)       Format
   1 a                    K         
 
++++++++++++++++++++++ Error Summary  ++++++++++++++++++++++
 
 HDU#  Name (version)       Type             Warnings  Errors
 1                          Primary Array    0         1     
 2                          Binary Table     0         0     
 
**** Verification found 0 warning(s) and 1 error(s). ****
```

**Comment by Hiyabiswas** [comment]
when I run this on jupyter notebook for tess data extraction using JULIET:
# Retrieving TESS lightcurves of Qatar-1 from  juliet
times, fluxes, fluxes_errors = juliet.utils.get_all_TESS_data('Qatar-1b')

This result comes:
OSError: No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True

Can anyone pls help me how to solve this error?

**Comment by pllim** [comment]
@Hiyabiswas , this appears to be a problem with the data. Please contact `juliet` people. Thanks.
