### ISSUE TITLE
Can't convert a list of Astropy tables to a NumPy array of tables

### ISSUE THREAD

**Issue by evertrol** [astropy/astropy#12229]
I recently stumbled upon [a StackOverflow question](https://stackoverflow.com/questions/69414829/convert-a-list-of-astropy-table-in-a-numpy-array-of-astropy-table) where someone likes to convert a list of Tables to a NumPy array.
By default, NumPy will convert the Table along the way, resulting in the wrong data structure. 
Using a specific `dtype=object`, however, fails with 
```
ValueError: Datatype coercion is not allowed
```

This error leads directly to the source of `table.__array__()`, which explicitly checks for any `dtype` to be not `None`, which will raise the error.
The reasoning behind that is clear, as given in the comments below. 

But I wonder if an exception is reasonable for `dtype=object` here, and let that pass through. For a single Table, this may be odd, but not necessarily incorrect. And for a list of Tables, to be converted to an array, this may be helpful.

**Comment by taldcroft** [comment]
FYI, here is a fix that seems to work. If anyone else wants to put this (or some variation) into a PR and add a test etc then feel free!
```
(astropy) ➜  astropy git:(main) ✗ git diff
diff --git a/astropy/table/table.py b/astropy/table/table.py
index d3bcaebeb5..6db399a7b8 100644
--- a/astropy/table/table.py
+++ b/astropy/table/table.py
@@ -1072,7 +1072,11 @@ class Table:
         Coercion to a different dtype via np.array(table, dtype) is not
         supported and will raise a ValueError.
         """
-        if dtype is not None:
+        if np.dtype(dtype).kind == 'O':
+            out = np.array(None, dtype=object)
+            out[()] = self
+            return out
+        elif dtype is not None:
             raise ValueError('Datatype coercion is not allowed')
 
         # This limitation is because of the following unexpected result that
```
