### ISSUE TITLE
SkyCoord in Table breaks aggregate on group_by

### ISSUE THREAD

**Issue by krachyon** [astropy/astropy#12249]
### Description, actual behaviour, reproduction
When putting a column of `SkyCoord`s in a `Table`, `aggregate` does not work on `group_by().groups`:

```python
from astropy.table import Table
import astropy.units as u
from astropy.coordinates import SkyCoord
import numpy as np

ras = [10, 20] * u.deg
decs = [32, -2] * u.deg

str_col = ['foo', 'bar']
coords = SkyCoord(ra=ras, dec=decs)

table = Table([str_col, coords], names=['col1', 'col2'])
table.group_by('col1').groups.aggregate(np.mean)
```

 fails with 

```
Traceback (most recent call last):
  File "repro.py", line 13, in <module>
    table.group_by('col1').groups.aggregate(np.mean)
  File "astropy/table/groups.py", line 357, in aggregate
    new_col = col.groups.aggregate(func)
  File "astropy/coordinates/sky_coordinate.py", line 835, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'"
AttributeError: 'SkyCoord' object has no attribute 'groups'
```
This happens irregardless of the aggregation function.

### Expected behavior
Aggregation works, only fails to aggregate columns where operation does not make sense.

### System Details
```
Linux-5.14.11-arch1-1-x86_64-with-glibc2.33
Python 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0]
Numpy 1.21.2
astropy 5.0.dev945+g7dfa1edb2
(no scipy or matplotlib)
```
and
```
Linux-5.14.11-arch1-1-x86_64-with-glibc2.33
Python 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0]
Numpy 1.21.2
astropy 4.3.1
Scipy 1.7.1
Matplotlib 3.4.3
```

**Comment by pllim** [comment]
Hmm. Maybe the logic here needs fixing:

https://github.com/astropy/astropy/blob/bcde23429a076859af856d941282f3df917b8dd4/astropy/table/groups.py#L351-L360

**Comment by taldcroft** [comment]
Mostly finished with a fix for this which makes it possible to aggregate tables that have mixin columns. In cases where the aggregation makes sense (e.g. with Quantity) it will just work. In other cases a warning only.

**Comment by taldcroft** [comment]
See #12825.
