### ISSUE TITLE
When downsampling a timeseries, what to do with point exactly on the border?

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#12246]
In #11266 support for downsampling with uneven bin sizes for added. In that context, a broader discussion item came up that applies to all downsampling and thus was beyond the scope of that specific PR.
Quoting @dhomeier:

> I had some further thoughts about the overlapping and in particular the "marginally overlapping" bins (i.e. data points exactly on the time_bin_start times). At the time it seemed natural that the desired default behaviour would be to assign a point with
ts.time[i] == time_bin_start[j]
to bin j; but actually if we assume ts.time[i] to represent the mean time of an observation (the perennial issue of sample centre vs. sample borders...), it would be just as natural to assign this with weight 0.5 each to time_bin_start[j-1] and time_bin_start[j]. So I think there is justification for a new option to control how these points are handled, but that could actually be extended to cases where ts.time[i] is not exactly on the boundary (and would be distributed with different weights). So, plenty of tasks for a follow-up on this PR.

CC @aaryapatil @astrofrog

See for more details of the discussion
https://github.com/astropy/astropy/pull/11266#issuecomment-865942363

I open this issue to continue the discussion and see if we can reach consensus on what exactly we want to do here.

Personally, I think the current behaviour has a certain simplistic beauty to it. While I see the need for more complex resampling schemes, I'm not sure we would want to stop at what @dhomeier suggested: If half a bin is before and have the bin after the new bon boundary, it seem natural to assign half of the value to the new left and the other half to the new right bin. However, that's only true id the underlying distribution is a constant. If, for example, we look at an exponential decay, more than half of the value should go into the left bin and less into the right bin. Also, any uncertainties will now be correlated between bins.

That's a long way of saying that I think that a reasonable solution is to declare anything that goes beyond the current implementation as "out of scope" for the core package and leave it for more specialized packages with domain knowledge to implement more complex rebinning schemes. Those might be used outside of timeseries, too (e.g. for spectra).

Thus, I label this issue "close?" even though I just opened it, but I'm happy to be convinced otherwise.

**Comment by dhomeier** [comment]
> Personally, I think the current behaviour has a certain simplistic beauty to it. While I see the need for more complex resampling schemes, I'm not sure we would want to stop at what @dhomeier suggested: If half a bin is before and have the bin after the new bon boundary, it seem natural to assign half of the value to the new left and the other half to the new right bin. However, that's only true id the underlying distribution is a constant. If, for example, we look at an exponential decay, more than half of the value should go into the left bin and less into the right bin. Also, any uncertainties will now be correlated between bins.

I tend to agree at this point. While I think one should not assume to have any knowledge of the form of the data below the original sampling frequency (and thus stick to constant, or at most linear interpolation if pressed), `timeseries` should probably first have a more complete model of how to deal with bin specifications (edges vs. centres), e.g. like specutils does for `spectral_axis`, before going down this path any further.
Or maybe putting it another way, if the handling of sub-timestep borders significantly affects the results, one should perhaps not bin the data in the first place (at least not for quantitative work).
