### ISSUE TITLE
Add method to get list of decomposed units

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#12264]
### Description
It's possible to decompose a unit, e.g.
```python
import astropy.units as u
unit = u.m * u.h / u.s
unit.decompose(u.si.bases)
Unit("3600 m")
```
What I want is a way to tell if a particular SI base unit is in the decomposed unit, to see what the dimensions of the unit are (e.g. time, 1D spatial, 2D spatial...). If the decomposed unit was returned as a list (e.g. [3600, Unit('m')]`) then it would be easy to do `u.m in decomposed_units` to check, but I'm not sure if there is an easy way to do this at the moment?

**Comment by eerovaher** [comment]
How about this:
```python
>>> from astropy import units as u
>>> unit = u.m/u.s
>>> unit.bases
[Unit("m"), Unit("s")]
>>> unit.powers
[1, -1]
```

**Comment by dstansby** [comment]
Ah, fabulous! In that case this is a request to have that documented somewhere on https://docs.astropy.org/en/stable/units/decomposing_and_composing.html
