### ISSUE TITLE
Passing parameters norm and vmin/vmax simultaneously is deprecated since matplotlib 3.3

### ISSUE THREAD

**Issue by Firestar-Reimu** [astropy/astropy#12282]
```
MatplotlibDeprecationWarning: Passing parameters norm and vmin/vmax simultaneously is deprecated since 3.3
and will become an error two minor releases later. Please pass vmin/vmax directly to the norm when creating it.

def displayimage(img):
    minv, maxv = np.percentile(img, [5, 95])
    plt.imshow(img, cmap='gray', vmin=minv, vmax=maxv, norm=simple_norm(img, stretch='asinh'), origin='lower')
    plt.show()
```

On [matplotlib.pyplot.imshow](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html?highlight=imshow#matplotlib.pyplot.imshow) it says "It is deprecated to use vmin/vmax when norm is given."

So when using [simple_norm](https://docs.astropy.org/en/stable/api/astropy.visualization.simple_norm.html?highlight=simple_norm) it will give this warning.

**Comment by neutrinoceros** [comment]
I don't see any clear actionable here, and I would suggest to close this issue.


> why a different name against ImageNormalize?

just to give this closure: I'm not sure why the names are different but I suspect that `ImageNormalize` is just following matplotlib's naming conventions, while `simple_norm` might be considered more domain-specific.

**Comment by larrybradley** [comment]
I opened a PR a while back to make the keyword names consistent:  https://github.com/astropy/astropy/pull/15621

**Comment by larrybradley** [comment]
@pllim This really isn't a bug.  The `simple_norm` keywords use the names `min_cut/max_cut` instead of `vmin/vmax`, so all one needs to do is set `min_cut/max_cut`.  #15621 deprecates the `min_cut/max_cut` names in favor of `vmin/vmax` for consistency.
