### ISSUE TITLE
Build aarch64 wheels

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#12297]
Due to the work of @odidev [upstream in the template](https://github.com/OpenAstronomy/azure-pipelines-templates/pull/67) we can easily enable building aarch64 wheels. However, due to the approach of using virtualisation it's too slow to actually put in production and I have had to disable the builds in our config (in #12292 at the time of writing).

I don't know if @odidev or anyone else has any suggestions for a way forward to enabling these again.

**Comment by pllim** [comment]
This is actually a duplicate of https://github.com/astropy/astropy/issues/11731
