### ISSUE TITLE
Add [tools.setuptools_scm] to pyproject.toml

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#12326]
### Description

I noticed that GitHub can't build a dependency graph for astropy at https://github.com/astropy/astropy/network/dependencies because we use a ``setup.cfg`` not ``setup.py`` or  ``pyproject.toml``. Looking at https://pypi.org/project/setuptools-scm/ ``setup.cfg`` and ``setup.py`` are deprecated and ``pyproject.toml`` is the new standard. I haven't looked into the downstream effects, so maybe a @astropy/core-release-maintainers could weigh in, but it seems we should begin transitioning as much as we can to ``pyproject.toml``.

**Comment by Cadair** [comment]
we already specify our build deps in `pyproject.toml` though?

**Comment by nstarman** [comment]
Wonderful. Then this might be as easy as removing ``setup_requires = setuptools_scm`` from `setup.cfg` and adding 
``[tool.setuptools_scm]`` to `pyproject.toml`

**Comment by Cadair** [comment]
I think at the time we added the scm line to setup.py it was still recommended for backwards compat in their docs. @astrofrog  and I are already scheming to see if we can burn the whole setup.py file ;) https://github.com/astropy/extension-helpers/issues/32

**Comment by nstarman** [comment]
When all these ``toml`` related PEPs are done it will be wonderful to have a single configuration file and no setup.py!

**Comment by astrofrog** [comment]
The reason we still specify it in setup.cfg was to support people who want to run python setup.py --version but we could always stop doing that if we wanted

**Comment by Cadair** [comment]
Well the azure pipelines build template does it, so we need to figure that out first ;)

**Comment by saimn** [comment]
`setup.py` and `setup.cfg` are not deprecated. The usage of `setuptools_scm` in `setup.cfg` is deprecated but this is not the same meaning. And using `setup.py` as a cli is also semi-deprecated (https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), but `setup.py` and `setup.cfg` are not (`setuptools` is not going to disappear soon, I think no other packaging library can build binary extensions anyway). The `setup.py` file is already optional since you can use only `setup.cfg` (the develop wasn't supported in that case but this may have been fixed, I think there is a new PEP about the develop mode?).

**Comment by saimn** [comment]
So I guess something to do would be to deprecate our test runner and its usage with `setup.py test`.

**Comment by nstarman** [comment]
Updating name to reflect relevant changes that can be made to `pyproject.toml` relating to `setuptools_scm`

**Comment by Cadair** [comment]
> I think no other packaging library can build binary extensions anyway

meson defo can, as scipy are testing using it. https://labs.quansight.org/blog/2021/07/moving-scipy-to-meson/

> So I guess something to do would be to deprecate our test runner and its usage with setup.py test.

We already deprecated (and disabled) doing `setup.py test`?

> Updating name to reflect relevant changes that can be made to pyproject.toml relating to setuptools_scm

I would like to review a PR for this :wink:

**Comment by saimn** [comment]
> meson defo can, as scipy are testing using it. https://labs.quansight.org/blog/2021/07/moving-scipy-to-meson/

Indeed :+1:

> We already deprecated (and disabled) doing setup.py test?

Running `setup.py test` on astropy shows a message about tox, but we still have the test runner for affiliated packages and I'm sure if there is a deprecation message (or a plan to remove it ?).

**Comment by Cadair** [comment]
I think the test runner is currently used by `astropy.test()`?
