### ISSUE TITLE
memory policy warning in fits with numpy 1.22.0.dev

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#12324]
### Description

See https://github.com/astropy/astropy/runs/4042351752?check_suite_focus=true

```RuntimeWarning: Trying to dealloc data, but a memory policy is not set. If you take ownership of the data, you must set a base owning the data (e.g. a PyCapsule).```

This appears in ``astropy/io/fits/tests/test_image.py``

### Steps to Reproduce

Run the CI with a fix for #12322, e.g. #12323 

### System Details

Python 3.10 CI

**Comment by pllim** [comment]
This is a symptom of a larger problem? Should we open a follow-up issue to un-ignore in the future and fix the real cause?

**Comment by saimn** [comment]
Yes, this is clearly something we should look at and try to fix.
