### ISSUE TITLE
Update the reference for Bayesian Blocks and maybe update the algorithm

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#12327]
A message from Jeff Scargle, the principle author of the Bayesian of this algorithm:

> I just noticed that the reference at
>
> https://docs.astropy.org/en/stable/api/astropy.stats.bayesian_blocks.html#
>
> is to my obsolete paper (the greedy algorithm there has been completely
supplanted by the dynamic programming algorithm in wide use) and described in
>
> The Astrophysical Journal, Volume 764, Issue 2, article id. 167, 26 pp. (2013).
https://arxiv.org/abs/1207.5578
> 
> I try to steer people away from the old algorithm as much as possible;
the new one is exact and optimal -- finds the optimal partition of an exponentially
large search space in quadratic time.
>  it would not hurt to reference
> Bellman too .. 
> Bellman, R.E., Dreyfus, S.E., 1962. Applied Dynamic Programming. Princeton University Press, Princeton. 
> Bellman, R., Roth, R., 1969. Curve fitting by segmented straight lines. J. Amer. Statist. Assoc. 64, 1079–1084.
>
> the first is general on DP, the second is really the germ of the BB algorithm ..

I don't know for sure which algorithm was implemented in `astropy.stats.bayesian_blocks` though. I.e., I'm not sure if this is the newer algorithm but the older citation, vs the older algorithm and the older citation.  So we should either update the citation if it's the former case, or this issue is to implement the newer algorithm if the implementation is currently the older one.

Maybe @jakevdp  @Gabriel-p or @larrybradley (as people who have touched the meat of this algorithm) want to weigh in?

**Comment by jakevdp** [comment]
I believe the implementation uses the newer algorithm, so updating the citation should be sufficient.

**Comment by larrybradley** [comment]
Thanks, @jakevdp.

I'm confused though.  The algorithm does reference the 2013 ApJ paper (but incorrectly uses 2012 for the year):
`Scargle, J et al. (2012) https://ui.adsabs.harvard.edu/abs/2013ApJ…764..167S`

So, I think the actions is to fix the year (2012 -> 2013)?  I can also add the Bellman references.

**Comment by larrybradley** [comment]
I made the changes in #12328.
