### ISSUE TITLE
Writing / reading column with u.dex(u.erg/u.s) to FITS Table not supported

### ISSUE THREAD

**Issue by Knusper** [astropy/astropy#12332]
### Description

I would like to write out a table with `u.dex(u.erg/u.s)` quantities to FITS using `QTable`.  My understanding of the FITS standard is, that the  unit would have to be written `log(erg/s)` in the column description (`TUNIT..`).  However, astropy throws a warning and just writes `dex(erg/s)` into `TUNIT`.   Reading this table then throws an error.

### Expected behavior

Reading and writing QTable from/to FITS with `u.dex(u.erg/u.s) ` should work?  At least when writing such a table in FITS it is completely opaque that we can't read it with QTable later...

### Actual behavior

Reading a QTable  that was written with columns that have `u.dex(u.erg/u.s)`  does not work and throws an error:
`UnitConversionError: Cannot initialize 'DexUnit' instance with function unit 'dex(erg / s)', as it is not equivalent to default function unit 'dex'.`

Writing such a table just throws a (to me) cryptic warning:
`WARNING: UnitsWarning: 'dex(erg / s)' did not parse as fits unit: Unit 'dex' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]`

### Steps to Reproduce

```python
from astropy.table import QTable
from astropy import units as u
t = QTable()
t['a'] = [1,2,3] * u.dex(u.erg/u.s)
t.write('test.fits', format='fits')  # throws a warning
t1 = QTable.read('test.fits')   # doesn't read in the table (error)
```

### System Details

Linux-4.19.0-18-amd64-x86_64-with-debian-10.11
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0]
Numpy 1.20.3
pyerfa 2.0.0
astropy 4.3.1
Scipy 1.7.1
Matplotlib 3.4.2

**Comment by saimn** [comment]
ping @mhvk in case you missed this one.

**Comment by mhvk** [comment]
I fear this is a very long-standing issue - #3822 (I now added the example there). It is not superhard to implement but also not trivial...

**Comment by saimn** [comment]
Closing in favor of #3822 then, thanks @mhvk.
