### ISSUE TITLE
support for clobber in table.write

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astropy#1233]
If an output file already exists table.write gives an error. 

It would be useful if table.write supported the clobber option like fits.writeto

**Comment by taldcroft** [comment]
Re-scheduling to 1.1 since I think this should be a relatively high priority / low-effort enhancement.

**Comment by willettk** [comment]
Adding another request for ```overwrite``` to exist; it'd make the write function much more useful.

**Comment by astrofrog** [comment]
Since no one has opened a PR for this, removing 1.1 milestone

**Comment by saimn** [comment]
`Table.write` appears to have an overwrite keyword for FITS files, so this is cool but not documented (or I didn't find where). So if I understand correctly this is currently specific to FITS, and it should be handled more generally for all table formats ? (and #1298 was an attempt to do this ?)

**Comment by embray** [comment]
In the case of FITS files this is simply because Table.write can pass through options to the underlying writer (if it is a wrapper around another library), in this case being `HDUList.writeto` which has a "clobber" option.  No reason that couldn't be made to apply more generally though.

**Comment by embray** [comment]
#1298 does look like an abandoned attempt at this issue.

**Comment by saimn** [comment]
@embray : actually it doesn't use the clobber option ;)
https://github.com/astropy/astropy/blob/master/astropy/io/fits/connect.py#L221
It is the same for VOTable and HDF5, but `io.ascii` always overwrite the output file:
https://github.com/astropy/astropy/blob/master/astropy/io/ascii/ui.py#L683

**Comment by taldcroft** [comment]
This is still a good idea.  :smile:  One thing that I don't think came up earlier is whether we need a compatibility release for `io.ascii`, during which it will issue a warning when overwriting an existing file but not error out.  Or if the current behavior is considered egregiously wrong and people who are relying on overwriting files (like myself) just have to change.
