### ISSUE TITLE
Register ``latex`` to ``Cosmology.write``

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#12355]
Cosmology can now read and write to files.
It would be nice to register with ``Cosmology.write`` a  method for exporting a Cosmology to a Latex table.
There are good examples of IO with Cosmology at https://github.com/astropy/astropy/tree/main/astropy/cosmology/io
and documentation at https://docs.astropy.org/en/latest/cosmology/io.html#cosmology-io

I'm thinking the ``write_latex(...)`` method would call ``cosmology.io.table.to_table()``, format the table to e.g. make `H0` -> `$H_0 \rm{[Mpc]}$` or something and then call the `QTable.write(..., format='latex')`.

**Comment by Octaves0911** [comment]
Hi, I would like to work on this if no one else is currently on it.

**Comment by nstarman** [comment]
@Octaves0911, that would be great! No one else is currently working on this feature request. If you need any help or have any questions I am happy to help. You can post here, or in the Astropy Slack cosmology channel. We also have documentation to assist in contributing at https://www.astropy.org/contribute.html#contribute-code-or-docs.

**Comment by Octaves0911** [comment]
Thanks a lot I ll work on it and get in touch with you if i have any queries.

**Comment by nstarman** [comment]
@Octaves0911, do you have any questions or need any assistance? I'm happy to help.

**Comment by Maia-jp** [comment]
This issue is still open for contributions?

**Comment by nstarman** [comment]
Yes! It's been quiet here for a while, so we'd be happy for a contribution. I'm happy to help / review a PR!
