### ISSUE TITLE
Doctest failure in 'What's new in 5.0?'

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#12368]
I tried enabling doctests in the 5.0 What's New to make sure all the examples work fine and ran into the following failure:

```
=================================== FAILURES ===================================
______________________________ [doctest] 5.0.rst _______________________________
091 (and enabled by default) to allow for redshift - dimensionless conversions.
092 To convert between redshift and other cosmological distance measures, e.g.
093 CMB temperature or comoving distance, the equivalency ``with_redshift`` is
094 also added.
095 
096     >>> import astropy.units as u
097     >>> import astropy.cosmology.units as cu
098     >>> z = 1100 * cu.redshift
099 
100     >>> z.to(u.dimensionless_unscaled)
UNEXPECTED EXCEPTION: UnitConversionError("'redshift' and '' (dimensionless) are not convertible")
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest 5.0.rst[11]>", line 1, in <module>
  File "/home/runner/work/astropy/astropy/.tox/py39-test-cov/lib/python3.9/site-packages/astropy/units/quantity.py", line 849, in to
    value = self._to_value(unit, equivalencies)
  File "/home/runner/work/astropy/astropy/.tox/py39-test-cov/lib/python3.9/site-packages/astropy/units/quantity.py", line 803, in _to_value
    return self.unit.to(unit, self.view(np.ndarray),
  File "/home/runner/work/astropy/astropy/.tox/py39-test-cov/lib/python3.9/site-packages/astropy/units/core.py", line 1135, in to
    return self._get_converter(Unit(other),
  File "/home/runner/work/astropy/astropy/.tox/py39-test-cov/lib/python3.9/site-packages/astropy/units/core.py", line 1066, in _get_converter
    raise exc
  File "/home/runner/work/astropy/astropy/.tox/py39-test-cov/lib/python3.9/site-packages/astropy/units/core.py", line 1051, in _get_converter
    return self._apply_equivalencies(
  File "/home/runner/work/astropy/astropy/.tox/py39-test-cov/lib/python3.9/site-packages/astropy/units/core.py", line 1027, in _apply_equivalencies
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'redshift' and '' (dimensionless) are not convertible
/home/runner/work/astropy/astropy/docs/whatsnew/5.0.rst:100: UnexpectedException
```

If the example is incorrect, it should be fixed in the v5.0.x branch directly. Otherwise, what could be going wrong?

See https://github.com/astropy/astropy/runs/4081948989?check_suite_focus=true for the full log

**Comment by pllim** [comment]
@nstarman ?

**Comment by nstarman** [comment]
We were discussing this in a slack channel. I think it's a race condition with some other test because neither @astrofrog nor I see this failure when running the file alone.

**Comment by nstarman** [comment]
I can literally only get this error with a full tox run. I really have no idea what is removing the system-wide equivalency. This is thoroughly tested in the cosmology module and even in the cosmology docs. Why the error should pop up later in the docs is mystifying.

**Comment by astrofrog** [comment]
I can reproduce the issue with:

```
tox -e py39-test -- -P units,whatsnew
```

**Comment by astrofrog** [comment]
@mhvk @nstarman the issue is the following example at the end of ``equivalencies.rst`` in the docs:

```
To enable radians to be treated as a dimensionless unit with the
:func:`~astropy.units.set_enabled_equivalencies` function:

  >>> u.set_enabled_equivalencies(u.dimensionless_angles())
  <astropy.units.core._UnitContext object at ...>
  >>> u.deg.to('')  # doctest: +FLOAT_CMP
  0.017453292519943295
```

Note that if I remove this, there is another failure in the what's new which is due to the fact scipy should be defined as a doctest-requires dependency.

@mhvk - how do you suggest we fix the equivalencies example? It's probably not good practice to set equivalencies globally, right? (especially if it removes other build-in ones)

**Comment by nstarman** [comment]
It could be ``u.add_enabled_equivalencies(u.dimensionless_angles())``

**Comment by mhvk** [comment]
Indeed, not good  practice to set it globally, and I see from what follows that is part of the point of the example. But perhaps it is simply the best to give the context-manager enabled example and then state that in principle one can also use it without context manager, but then it affects global state.

**Comment by astrofrog** [comment]
@mhvk @nstarman - would one of you have time to open a PR to fix this? Thanks!
