### ISSUE TITLE
[5.0rc1] - some failures and warnings

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#12378]
### Description

Running unit tests on astropy 5.0rc1 on my Mac produces 3 failures and a bunch of warnings. At first glance the errors seem to be all URL timeouts. I don't recall seeing so many warnings before however. See:

https://gist.github.com/taldcroft/85bd0325f6bd8a3aa13a288c7bdf1071

Please run the following snippet and paste the output below:
```
>>> import platform; print(platform.platform())
macOS-10.16-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.21.3
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.0rc1
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.7.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.4.3
```

**Comment by pllim** [comment]
Warnings are expected if you run `astropy.test()` because it does not respect the warning settings for pytest in `setup.cfg`.

As for the URL errors, you might have just run it during a time of high traffic. Please try again.

**Comment by taldcroft** [comment]
OK, with a few iterations I got those remote tests to eventually pass. With those explanations I'm OK with closing this.
