### ISSUE TITLE
Bug in CompoundModel copy()

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#12370]
`photutils` tests with `astropy` `dev` started failing, and I tracked it down to commit https://github.com/astropy/astropy/commit/afc3f0f7c6fdda53232fd432e3859e882d78b63d (PR https://github.com/astropy/astropy/pull/11942).

The bug is caused by the newly-added `CompoundModel.copy()` method.  Prior to #11942, this method used to be defined by the parent `Model.copy()`, which simply returns `copy.deepcopy(self)`.  The new `CompoundModel.copy()` method initializes a new `CompoundModel`, meaning that any user-added attributes are lost in the copy.

MWE that worked prior to #11942, but now fails with `AttributeError: Attribute "xname" not found`:

```python
from astropy.modeling.models import Gaussian2D, Identity

model = Gaussian2D(100, 25, 25, 5, 5) | Identity(1)
model.xname = 'x_mean'  # user-defined attribute
model_copy = model.copy()
model_copy.xname
```

CC: @WilliamJamieson, @nden, @eteq

**Comment by WilliamJamieson** [comment]
Hmm, this will be an issue. The reason for the change is that the refactored bounding box breaks `deepcopy`, which was what was used before to copy models. I was not very happy with the solution I came up with for fixing this in general. I will look more closely into the problem to see if I can come up with a more elegant solution.
