### ISSUE TITLE
[5.0RC1] exact double comparison in test_spline.py, exposed by Debian/ppc64el

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#12403]
### Description

Some tests in `astropy/modeling/tests/test_spline.py` compare doubles by equal, which not always works. Specifically on the PowerPC 64 Little Endian architecture on Debian, this gives failures

### Expected behavior

Tests should pass :-)

### Actual behavior
```
_________________ TestSpline1D.test_interpolate_fitter[2-None] _________________

self = <astropy.modeling.tests.test_spline.TestSpline1D object at 0x7ffeb53a7a90>
w = None, k = 2

    @pytest.mark.parametrize('w', wieght_tests)
    @pytest.mark.parametrize('k', degree_tests)
    def test_interpolate_fitter(self, w, k):
[...]
        assert (fit_spl.t == spline._eval_args[0]).all()
        assert (fit_spl.c == spline._eval_args[1]).all()
        assert (fitter.fit_info['spline']._eval_args[0] == spline._eval_args[0]).all()
        assert (fitter.fit_info['spline']._eval_args[1] == spline._eval_args[1]).all()
    
        assert spline.get_residual() == fitter.fit_info['resid'] == 0
>       assert (fit_spl(self.x) == spline(self.x)).all()
E       assert False
E        +  where False = <built-in method all of numpy.ndarray object at 0x7ffeb52a9030>()
E        +    where <built-in method all of numpy.ndarray object at 0x7ffeb52a9030> = array([ 0.073...  0.05145015]) == array([ 0.073...  0.05145015])
E             Use -v to get the full diff.all
```
The same happens on `test_smoothing_fitter` (line 1207) and `test_exact_knots_fitter` (line 1267), all fails several times for different parameters.

[Full build log](https://buildd.debian.org/status/fetch.php?pkg=astropy&arch=ppc64el&ver=5.0%7Erc1-1&stamp=1636027474&raw=0)

### Steps to Reproduce

This happens when running on PowerPC 64 bit little endian. 

### System Details

platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
Matplotlib: 3.3.4
Freetype: 2.11.0

Running tests with Astropy version 5.0-rc1.
Running tests in .pybuild/cpython3_3.9/build.

Date: 2021-11-04T11:57:20

Platform: Linux-5.10.0-9-powerpc64le-ppc64le-with-glibc2.32

Executable: /usr/bin/python3.9

Full Python Version: 
3.9.7 (default, Sep 24 2021, 09:43:00) 
[GCC 10.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.5
Scipy: 1.7.1
Matplotlib: 3.3.4
h5py: 3.3.0
Pandas: not available
PyERFA: 2.0.0
Cython: 0.29.24
Scikit-image: not available
asdf: not available
pyarrow: not available

Using Astropy options: remote_data: none.

ARCH_ON_CI: undefined
IS_CRON: undefined

rootdir: /<<PKGBUILDDIR>>, configfile: setup.cfg
plugins: mpl-0.11, remotedata-0.3.2, openfiles-0.5.0, mock-3.6.1, filter-subpackage-0.1.1, doctestplus-0.11.0, cov-3.0.0, astropy-header-0.1.2, arraydiff-0.3, hypothesis-5.43.3

**Comment by astrofrog** [comment]
cc @WilliamJamieson

**Comment by WilliamJamieson** [comment]
This is very disturbing. Since we have the following truth:
```
assert (fit_spl.t == spline._eval_args[0]).all()
assert (fit_spl.c == spline._eval_args[1]).all()
```
Scipy `UnivariateSplines` and the spline model should be using the same scipy code to evaluate their splines. This evaluation depends of `x` (independent variable), `t`/`_eval_args[0]` (the knots), `c`/`_eval_args[1]`, and `degree`/`k` (spline degree).  Thus should run the same (theoretically) deterministic calculation twice and then comparing the results.

This comparison is just proving that `astropy` and `scipy` are producing identical results.

I'll open a PR cleaning up the testing a little bit using numpy's `assert_equal` method. Since I don't have access to your type of machine, if this keeps failing please report the results with the `-v` flag (so that I have an idea of what tolerances to compare values at).

**Comment by olebole** [comment]
With #12414 and verbose tests, I get [this build/test log](https://buildd.debian.org/status/fetch.php?pkg=astropy&arch=ppc64el&ver=5.0%7Erc1-3&stamp=1636097961&raw=0). First failure:
```
_________________ TestSpline1D.test_interpolate_fitter[2-None] _________________

self = <astropy.modeling.tests.test_spline.TestSpline1D object at 0x7fff01e4e820>
w = None, k = 2

    @pytest.mark.parametrize('w', wieght_tests)
    @pytest.mark.parametrize('k', degree_tests)
    def test_interpolate_fitter(self, w, k):
[…]
>       self.check_spline_fit(fit_spl, spline, fitter, 0, 1)

astropy/modeling/tests/test_spline.py:1184: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <astropy.modeling.tests.test_spline.TestSpline1D object at 0x7fff01e4e820>
fit_spl = <Spline1D(knot0=-3., knot1=-3., knot2=-3., knot3=-2.81632653, knot4=-2.69387755, knot5=-2.57142857, knot6=-2.44897959,..., coeff46=0.12950724, coeff47=0.03630973, coeff48=-0.10948153, coeff49=0.05145015, coeff50=0., coeff51=0., coeff52=0.)>
spline = <scipy.interpolate.fitpack2.InterpolatedUnivariateSpline object at 0x7ffe856c3250>
fitter = <astropy.modeling.spline.SplineInterpolateFitter object at 0x7fff01e4e880>
atol_fit = 0, atol_truth = 1

    def check_spline_fit(self, fit_spl, spline, fitter, atol_fit, atol_truth):
        """Check the spline fit"""
        assert_equal(fit_spl.t, spline._eval_args[0])
        assert_equal(fit_spl.c, spline._eval_args[1])
        assert_equal(fitter.fit_info['spline']._eval_args[0], spline._eval_args[0])
        assert_equal(fitter.fit_info['spline']._eval_args[1],  spline._eval_args[1])
    
        assert_equal(spline.get_residual(), fitter.fit_info['resid'])
    
>       assert_equal(fit_spl(self.x), spline(self.x))
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 11 / 50 (22%)
E       Max absolute difference: 1.11022302e-16
E       Max relative difference: 1.94971928e-15
E        x: array([ 0.07397 ,  0.01739 , -0.01106 , -0.029133, -0.146018, -0.068643,
E              -0.040157,  0.115846,  0.051235, -0.149042,  0.075156,  0.026541,
E               0.028369,  0.198834,  0.294563,  0.351544,  0.254555,  0.399325,...
E        y: array([ 0.07397 ,  0.01739 , -0.01106 , -0.029133, -0.146018, -0.068643,
E              -0.040157,  0.115846,  0.051235, -0.149042,  0.075156,  0.026541,
E               0.028369,  0.198834,  0.294563,  0.351544,  0.254555,  0.399325,...

astropy/modeling/tests/test_spline.py:1142: AssertionError

```

**Comment by WilliamJamieson** [comment]
@olebole thats, for that. Looks like is very slight floating point differences that I cannot explain. I changed the offending comparison to a `assert_allclose` in my latest push to the PR. Please let me know if that fixes the test.
