### ISSUE TITLE
Deprecate treat_deprecations_as_exceptions

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#12404]
Follow-up in #12389, where we had to fix our machinery, and where @astrofrog noted it should be possible to do this just with pytest now.

**Comment by pllim** [comment]
Have to make sure downstream packages are okay with this first?

**Comment by pllim** [comment]
2021-12-09 -- I asked astropy-dev for opinions on this. We'll see!

**Comment by astrofrog** [comment]
If we do this we should include a section in our docs explaining how to migrate to the pytest way of doing things.

**Comment by pllim** [comment]
2021-12-16 -- No objection to proceed from infrastructure tag up. We should do this early in 5.1 release cycle.

**Comment by pllim** [comment]
Wow, I totally forgot about #6761. I don't think we can deprecate just this. It makes more sense to deprecate all these together:

* `astropy.io.ascii.tests.common.raises`
* `astropy.tests.helper.catch_warnings`
* `astropy.tests.helper.enable_deprecations_as_exceptions`
* `astropy.tests.helper.raises`
* `astropy.tests.helper.treat_deprecations_as_exceptions`

🔥

**Comment by pllim** [comment]
Looks like @taldcroft added `astropy.io.ascii.tests.common.raises` 10 years ago in #154. 👀
