### ISSUE TITLE
Release blockers for 5.0

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#12430]
This is a meta-issue to capture things that need to be investigated/fixed before the next 5.0 release candidate(s) and the final release. I am deliberately ignoring issues that seem to be related just to tests as opposed to user-facing documentation or actual functionality.

* [X] https://github.com/astropy/astropy/issues/12368
  * fixed by gh-12432
* [x] https://github.com/astropy/astroquery/issues/2194
  * fixed by https://github.com/astropy/astroquery/pull/2196
* [x] https://github.com/astropy/astropy/issues/12431
  * test fixed by https://github.com/astropy/astropy/pull/12437
  * underlying issue fixed by https://github.com/astropy/astropy/pull/12447
* [x] https://github.com/astropy/specutils/issues/893
  * fixed by https://github.com/astropy/astropy/pull/12440
  * also https://github.com/astropy/astropy/pull/12449
* [x] https://github.com/astropy/astropy/issues/12435
  * fixed by https://github.com/astropy/astropy/pull/12454

If people want to highlight other issues that we should consider blockers, please mention them in a comment below and I can review them and add them to the list.

I would also ideally like to see 'What's new' entries for:

* [x] https://github.com/astropy/astropy/pull/11914 (@mhvk?)
  * done in https://github.com/astropy/astropy/pull/12455

But I won't block the release for these - if you don't want to add a 'What's new entry', it just means less chance to showcase your great work :smile:

**Comment by rosteen** [comment]
I just added an update to https://github.com/astropy/specutils/issues/893, have been talking to @WilliamJamieson offline about it.

**Comment by astrofrog** [comment]
Once https://github.com/astropy/astropy/pull/12440 is merged, I think we are good to go on a second release candidate!

**Comment by dhomeier** [comment]
I'd note that although https://github.com/astropy/astropy/issues/12435#issuecomment-962695763 only showed up in a non-affiliated downstream package so far, the lack of support for np.nanfunctions in `Masked` probably has the potential to wreak wider havoc.

**Comment by astrofrog** [comment]
@dhomeier - thanks, added to the list of blockers above.

**Comment by astrofrog** [comment]
@eerovaher noted in https://github.com/astropy/astropy/pull/12451#issuecomment-965168245 that some contributors in the What's New in 5.0 page are incorrectly listed as first time contributors.

**Comment by nstarman** [comment]
Should #12438 be considered a blocker for final version release? Probably not a blocker for rc2.

**Comment by pllim** [comment]
Re: #12438 -- I would say "not really" because it does not affect code functionality and any update can be backported, but up to the release manager.

**Comment by astrofrog** [comment]
It would be nice to resolve that before 5.0 final but I also won't delay the release for that. There is still a bit of time as I am doing a second release candidate.

**Comment by astrofrog** [comment]
Just a reminder to myself that I need to go through and tidy up the What's New page and update the credits.rst page before the final release.

**Comment by astrofrog** [comment]
No blockers, so closing this and proceeding with the release!
