### ISSUE TITLE
`docs/stability.rst` should be updated

### ISSUE THREAD

**Issue by eerovaher** [astropy/astropy#12438]
### Description

`docs/stability.rst` hasn't been touched for quite some time now, and I don't see any open pull requests that would update it. Given that an LTS release is upcoming the file should be reviewed.

**Comment by pllim** [comment]
@astropy/core-release-maintainers , maybe revisiting this page should be in release procedures?

**Comment by bsipocz** [comment]
@pllim - module maintainers should keep it up to date, the release managers have zero jurisdiction on the future API plans.

**Comment by astrofrog** [comment]
I personally think we should now get rid of the document and treat all sub packages as stable and have a higher bar of entry for future code to treat it on the same footing as other code. We could still add a note to specific classes or methods if they are to be considered experimental?

**Comment by pllim** [comment]
👍 to removing the page. I keep forgetting it is there. There are some nice info under "comments" that should be moved to proper subpackage docs, if not already.

p.s. Can `astropy.uncertainty` ever be stable? 😏

**Comment by astrofrog** [comment]
I've just sent an email to astropy-dev soliciting comments about removing the page.

**Comment by mwcraig** [comment]
I agree it is time to remove this

**Comment by mhvk** [comment]
Also agree we can remove it - while some modules may still get major new functionality (`uncertainties`...), I don't think that is particularly useful information, and in any case that could be displayed in the module documentation itself. What counts is whether we can commit to a more or less stable API for whatever we have, which I think is the case.

**Comment by taldcroft** [comment]
Agreed with comments thus far and that we should remove this page.

**Comment by adrn** [comment]
I agree with the idea of removing the page

**Comment by nden** [comment]
👍 removing the page

**Comment by pllim** [comment]
See #12473
