### ISSUE TITLE
Length 1 `Tabular1D` issue

### ISSUE THREAD

**Issue by nabobalis** [astropy/astropy#12465]
We hit an issue with length-1 tables:

```python
In [5]: t = Tabular1D([0]*u.pix, lookup_table=[0]*u.s)

In [6]: t
Out[6]: <Tabular1D(points=(<Quantity [0.] pix>,), lookup_table=[0.] s)>

In [7]: t(0)
/home/stuart/.virtualenvs/sunpy-dev/lib/python3.9/site-packages/scipy/interpolate/interpolate.py:2532: RuntimeWarning: invalid value encountered in true_divide
  norm_distances.append((x - grid[i]) /
Out[7]: nan

In [8]: t = Tabular1D([0,1]*u.pix, lookup_table=[0,1]*u.s)

In [9]: t(0)
Out[9]: 0.0
```

What I am unsure if this is intended behaviour (since I believe a 1 length Table is meaningless) or a bug? 
@Cadair suggests this is intended behaviour as well.

**Comment by pllim** [comment]
I think this is intentional? Basically it farms out the evaluation to `scipy` so to some extend, follows upstream behavior but maybe @nden can confirm.

https://github.com/astropy/astropy/blob/4e2216ae82ce57489b96b4e7e56c7e3cf0fb07d9/astropy/modeling/tabular.py#L235

**Comment by nabobalis** [comment]
>  Is it a serious problem for your application?

I would say no since the plan is to create a new astropy model to handle this special case (https://github.com/sunpy/ndcube/pull/499)

It is just possible that in my code I will end up with 1D Tables due to slicing a bigger object.
