### ISSUE TITLE
DOC: RTD fails with 5 warnings

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#12483]
I thought pytest-doctestplus 0.11.1 would fix this but it did not.  @saimn , any idea?

```
.../docs/uncertainty/index.rst:332: WARNING: line 7 of the doctest for <string> has an invalid option: '+FLOAT_CMP'
```

Also, these also appear now. Maybe caused by new matplotlib release? cc @astrofrog and @Cadair 

```
.../matplotlib/artist.py:docstring of matplotlib.artist.WCSAxes.set:7: WARNING: py:obj reference target not found: ScaleBase
.../matplotlib/artist.py:docstring of matplotlib.artist.WCSAxes.set:7: WARNING: py:obj reference target not found: ScaleBase
.../matplotlib/artist.py:docstring of matplotlib.artist.WCSAxesSubplot.set:7: WARNING: py:obj reference target not found: ScaleBase
.../matplotlib/artist.py:docstring of matplotlib.artist.WCSAxesSubplot.set:7: WARNING: py:obj reference target not found: ScaleBase
```

**Comment by astrofrog** [comment]
Yes the MPL warnings must be related to the Matplotlib 3.5 release

**Comment by saimn** [comment]
No idea about the `FLOAT_CMP` one, it appeared in a build where only the Matplotlib version changed, so maybe related to their new version as well ? (Since it happens in a `.. plot::` directive)

**Comment by dstansby** [comment]
We're seeing a similar issue in sunpy, also inside a `plot` directive. I've opened https://github.com/matplotlib/matplotlib/issues/21668 upstream.
