### ISSUE TITLE
MaskedNDArray: `any()` and `all()` do not match numpy behavior

### ISSUE THREAD

**Issue by barentsen** [astropy/astropy#12480]
### Description

Using AstroPy v5.0rc2, `MaskedNDArray.any()` and `.all()` both return a `MaskedNDArray` by default.  This is inconsistent with NumPy arrays, which `"Return a single boolean unless axis is not None"` (cf. [numpy docstring](https://numpy.org/doc/stable/reference/generated/numpy.any.html#numpy.any)).

I don't think this is a release blocker.  The impact of this inconsistency might be very small.  Perhaps it is even the desired behavior?  I merely happened to notice it while debugging a different issue.

### Steps to Reproduce

```python
>>> import numpy as np
>>> from astropy.utils.masked import Masked
>>> notmasked = np.ones(3, dtype=bool)
>>> masked = Masked(notmasked)
>>> type(notmasked.any())  # numpy returns `True`
numpy.bool_
>>> type(masked.any())   # astropy returns `MaskedNDArray(True)`
astropy.utils.masked.core.MaskedNDArray
```

### System Details

```
macOS-11.6-x86_64-i386-64bit
Python 3.8.6 (default, Jan  7 2021, 11:34:43) 
[Clang 12.0.0 (clang-1200.0.32.28)]
Numpy 1.21.1
astropy 5.0rc2
```

**Comment by mhvk** [comment]
@barentsen - thanks for the feedback; sad to see problems arise in practice, but of course unavoidable - and I really hope `MaskedQuantity` will make a lot of things better too!

For this particular issue, I'm not sure it is worth changing: essentially one would need to special-case the `axis=None` case somehow. I thought hard about the extent to which `Masked` should be compatible with `MaskedArray` and ended up concluding that it should not; see https://docs.astropy.org/en/latest/utils/masked/index.html#utils-masked-vs-numpy-maskedarray

On the other hand, I would like to ensure most things work correctly, so do let me know if this does end to be a problem!

**Comment by barentsen** [comment]
> sad to see problems arise in practice, but of course unavoidable - and I really hope MaskedQuantity will make a lot of things better too!

Thanks so much for your work on `MaskedQuantity`.  I think it's a fabulous new feature!  I don't see any reason to be sad about it =)

>  so do let me know if this does end to be a problem!

I now think opening this issue was overzealous on my part.  I started writing the issue because I thought it triggered a failing unit test, which ended up not being the case.

For all intents and purposes, I don't think there is any practical difference between `True` and `MaskedNDArray(True)`, so one could argue it does not warrant making the code more complicated for.

I'll go ahead and close this issue unless anyone disagrees!
