### ISSUE TITLE
MaskedNDArray cannot be used with matplotlib.scatter (misses the `shrink_mask()` method)

### ISSUE THREAD

**Issue by barentsen** [astropy/astropy#12481]
### Description

While testing AstroPy v5.0rc2, I noticed that Matplotlib's `scatter` function does not accept an AstroPy `MaskedNDArray` object to set the symbol colors via the `c` parameter.  The issue appears to be that NumPy's `MaskedArray` offers a `shrink_mask()` method, while AstroPy's `MaskedNDArray` does not.

### Steps to reproduce

```python
>>> from astropy.utils.masked import Masked
>>> import matplotlib.pyplot as plt
>>> x = Masked([1, 2, 3])
>>> plt.scatter(x, x, c=x)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/ipykernel_38381/3652307469.py in <module>
      2 import matplotlib.pyplot as plt
      3 x = Masked([1, 2, 3])
----> 4 plt.scatter(x, x, c=x)

~/Library/Caches/pypoetry/virtualenvs/lightkurve-HqDeGDfc-py3.8/lib/python3.8/site-packages/matplotlib/pyplot.py in scatter(x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, edgecolors, plotnonfinite, data, **kwargs)
   3066         vmin=None, vmax=None, alpha=None, linewidths=None, *,
   3067         edgecolors=None, plotnonfinite=False, data=None, **kwargs):
-> 3068     __ret = gca().scatter(
   3069         x, y, s=s, c=c, marker=marker, cmap=cmap, norm=norm,
   3070         vmin=vmin, vmax=vmax, alpha=alpha, linewidths=linewidths,

~/Library/Caches/pypoetry/virtualenvs/lightkurve-HqDeGDfc-py3.8/lib/python3.8/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1359     def inner(ax, *args, data=None, **kwargs):
   1360         if data is None:
-> 1361             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1362 
   1363         bound = new_sig.bind(ax, *args, **kwargs)

~/Library/Caches/pypoetry/virtualenvs/lightkurve-HqDeGDfc-py3.8/lib/python3.8/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, edgecolors, plotnonfinite, **kwargs)
   4524         else:
   4525             x, y, s, c, colors, edgecolors, linewidths = \
-> 4526                 cbook._combine_masks(
   4527                     x, y, s, c, colors, edgecolors, linewidths)
   4528         # Unmask edgecolors if it was actually a single RGB or RGBA.

~/Library/Caches/pypoetry/virtualenvs/lightkurve-HqDeGDfc-py3.8/lib/python3.8/site-packages/matplotlib/cbook/__init__.py in _combine_masks(*args)
   1065                 x = np.asanyarray(x, dtype=object)
   1066             if x.ndim == 1:
-> 1067                 x = safe_masked_invalid(x)
   1068                 seqlist[i] = True
   1069                 if np.ma.is_masked(x):

~/Library/Caches/pypoetry/virtualenvs/lightkurve-HqDeGDfc-py3.8/lib/python3.8/site-packages/matplotlib/cbook/__init__.py in safe_masked_invalid(x, copy)
    741     try:
    742         xm = np.ma.masked_invalid(x, copy=False)
--> 743         xm.shrink_mask()
    744     except TypeError:
    745         return x

AttributeError: 'MaskedNDArray' object has no attribute 'shrink_mask'
```

### System Details

```
macOS-11.6-x86_64-i386-64bit
Python 3.8.6 (default, Jan  7 2021, 11:34:43) 
[Clang 12.0.0 (clang-1200.0.32.28)]
Numpy 1.21.1
astropy 5.0rc2
Matplotlib 3.4.3
```

**Comment by pllim** [comment]
Maybe we can chuck this under https://docs.astropy.org/en/latest/known_issues.html , @mhvk ?

**Comment by mhvk** [comment]
This is the one issue that would be great to solve. In `Masked`, there is no `nomask` possibility, so `shrink_mask` is meaningless...

But obviously it would be nice for `Masked` to work properly with matplotlib! Possibly, this would mean ensuring that in the `np.ma.masked_invalid` line above the one that errors, `Masked` instances are actually converted to a `np.ma.MaskedArray` -- though then we may effectively exclude being able to use `MaskedQuantity`...  I'll need to experiment a bit...

p.s. If it is easy to work around in `lightkurve`, for now the best may indeed be to call it a "known issue".

**Comment by mhvk** [comment]
p.s. It is interesting that in matplotlib, the x, y coordinates work fine, but the color has a problem. I noticed that similarly in `plt.errorbar`, it was the error that gave problems, not x, y.

**Comment by mhvk** [comment]
p.p.s. Just adding `def shrink_mask(self): pass` does solve the error. Not super-keen on adding a no-op method, though!

**Comment by barentsen** [comment]
(FWIW: I don't think this minor issue ought to block a v5.0 release from my perspective -- it's easy enough to work around!)

**Comment by dhomeier** [comment]
> EDIT 2: well, display looks correct for `plt.errorbar`, not for `plt.scatter`...

What's not looking correct? Tried this with setting one element of `x.mask` to `True` and without, and in both cases it looked the same for `Masked([1, 2, 3])` and `np.ma.array([1, 2, 3])`.
In fact the `shrink_mask` seems to have no relevance here – although it creates an `np.ma.array` with `a.mask = False` as opposed to the `Masked` with `x.mask = array([False, False, False])`, both have `np.ma.is_masked(x) == False` and will not be added in
https://github.com/matplotlib/matplotlib/blob/49609c36a922baaab25f61f5080fd1eef53604a5/lib/matplotlib/cbook/__init__.py#L1034-L1035

**Comment by mhvk** [comment]
Indeed, in more recent matplotlib, it looks like there is a `try/except` around the `.shrink_mask` operation. So, I agree the issue is solved as far as we are concerned.  But it would actually be good to have a test for this...  Mostly just that the commands work; I don't know that we need to check the output itself.

**Comment by neutrinoceros** [comment]
Ok I'll add a test then. I assume it's okay to skip the test with older versions of Matplotlib ?

**Comment by dhomeier** [comment]
Or xfail, as long as MPLVER <= 3.7 is supported
