### ISSUE TITLE
TST: Refactor the way image-tests-mpldev in CircleCI look for reference dir

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#12495]
https://github.com/astropy/astropy/blob/de53bdc1643d35ae8dcf3d5070f933e314b0747e/astropy/tests/image_tests.py#L16-L19

As a result of this look-up logic, every time `matplotlib` bumps its major/minor version, we have to create a new directory over at `astropy-data` server (e.g., astropy/astropy-data#122) even though the test data did not actually change. This wastes storage space. We need to find a better way to do this.

Currently, without creating a new dir, you get an error like this:

```
UserWarning: Downloading .../3.6.x/test_wcsapi_5d_with_names.png failed: HTTP Error 404: Not Found
```

**Comment by nstarman** [comment]
An intermediate lookup table? Mapping version to directory on astropy-data.
```python
mpl_lookup = {"3.4.1": "folder1", "3.4.2": "folder1", "3.4.3": "folder2"}
```

**Comment by pllim** [comment]
Maybe this can be done as part of #12673
