### ISSUE TITLE
test_showtable fails on armhf (32 bit)

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#12513]
### Description

On Debian, we currently rebuilt all Python packages to include Python 3.10 as supported version. With both Python versions (3.9.9, 3.10), I now see a failure on armhf (ARM 32 bit little endian, like smaller Raspberries).

I think this should have some regexp in the second expected column as well.

### Expected behavior

All tests should pass.

### Actual behavior

```
__________________________________ test_stats __________________________________

capsys = <_pytest.capture.CaptureFixture object at 0xe70d2448>

    def test_stats(capsys):
        showtable.main([os.path.join(FITS_ROOT, 'data/table.fits'), '--stats'])
        out, err = capsys.readouterr()
        expected = ['<Table length=3>',
                    ' name     mean      std    min  max ',
                    '------ --------- --------- ---- ----',
                    'target        --        --   --   --',
                    ' V_mag 12.86666[0-9]? 1.7211105 11.1 15.2']
    
        out = out.splitlines()
        assert out[:4] == expected[:4]
        # Here we use re.match as in some cases one of the values above is
        # platform-dependent.
>       assert re.match(expected[4], out[4]) is not None
E       AssertionError: assert None is not None
E        +  where None = <function match at 0xf77222f8>(' V_mag 12.86666[0-9]? 1.7211105 11.1 15.2', ' V_mag 12.866668 1.7211103 11.1 15.2')
E        +    where <function match at 0xf77222f8> = re.match

astropy/table/tests/test_showtable.py:42: AssertionError
=========================== short test summary info ============================
FAILED astropy/table/tests/test_showtable.py::test_stats - AssertionError: as...
```
[Full test log here](https://buildd.debian.org/status/fetch.php?pkg=astropy&arch=armhf&ver=4.3.1-4%2Bb1&stamp=1637568487&raw=0).

### Steps to Reproduce

Build and test astropy with python 3.9.9 or 3.10.0 on armhf.

### System Details
```
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
Matplotlib: 3.5.0
Freetype: 2.11.0

Running tests with Astropy version 4.3.1.
Running tests in .pybuild/cpython3_3.9/build.

Date: 2021-11-22T07:55:58

Platform: Linux-4.19.0-18-arm64-armv8l-with-glibc2.32

Executable: /usr/bin/python3.9

Full Python Version: 
3.9.9 (main, Nov 16 2021, 10:24:31) 
[GCC 11.2.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.21.4
Scipy: 1.7.1
Matplotlib: 3.5.0
h5py: 3.5.0
Pandas: not available
PyERFA: 2.0.0.1
Cython: 0.29.24
Scikit-image: not available
asdf: not available

Using Astropy options: remote_data: none.
```

Same happens for python 3.10.0+.
I didn't check this for Astropy 5.0 yet, ~~but since the test is unchanged, I expect the same failure~~.

**Comment by eerovaher** [comment]
#12022 updated the output of `Table.info('stats')` and the test in question was updated accordingly. This is what it looks like on main:

https://github.com/astropy/astropy/blob/bf18eb5f1a5cf3b2835c67d3fa303d29b587aa66/astropy/table/tests/test_showtable.py#L29-L37

The output has less decimal places now, so this bug should not be present in `astropy` 5.0.

**Comment by pllim** [comment]
@olebole , can you please test on astropy 5.0 and report back? Thanks!

**Comment by olebole** [comment]
Yes, I can confirm that this does not happen on 5.0.

**Comment by pllim** [comment]
5.0 is the new LTS, so can we consider this resolved without further action?

**Comment by olebole** [comment]
Probably fixing 4.3 is not needed, right? (as it is not LTS)
