### ISSUE TITLE
remove cfitsio 4.0.0 local zlib subdirectory

### ISSUE THREAD

**Issue by rmathar** [astropy/astropy#12515]
cfitsio version 4.0.0 does no longer use a local copy of a zlib but uses the one of the host operating system. So https://github.com/astropy/astropy/tree/main/cextern/cfitsio/zlib directory should be deleted. [That is: the port to cfitsio 4.0.0 was incomplete and kept the obsolete directory.]

**Comment by saimn** [comment]
It was kept on purpose. The purpose of bundling cfitsio is simplify the installation for users so it doesn't make sense to require them to install zlib manually. And zlib is not updated so often. Is there a specific problem motivating this ticket ?

**Comment by rmathar** [comment]
This is a masterly example for code bloating: code that is useless, consumes disk space, is transfered to revision histories, consumes build time etc. It consumes astropy maintenance efforts because each revision of astropy needs to figure out whether it's local zlib has become obsolete. It is misplaced because it gives the wrong impression that the maintainers of of the cfitsio code don't known what they are doing. It (correctly) gives the impression that the maintainers of astropy don't know what they are doing. It leads to to deep but useless thoughts of users of the library (like me) -- complete waste of time -- what for god's sake the astropy maintainers had in mind to add that stuff where it is.
Of course, I'd strongly advise to remove the directory. It is NOT the task of astropy to maintain libraries that every computer operating system has. (As someone once said, you can write an entire operating system in emacs, but that does not mean you ought to do it.)

**Comment by saimn** [comment]
Not sure what lead you to such bad impressions, but for the sake of not wasting more time on this I'm just going to close.
