### ISSUE TITLE
Quantity.__class_getitem__ cannot use super on ndarray.__class_getitem__ on python >=3.10

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#12510]
All PRs are currently failing their python 3.10 + devdeps tests because the interaction between `Quantity.__class_getitem__` and `ndarray.__class_getitem__` is not correct. E.g.,
```
In [2]: u.Quantity[u.m]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-f0c088963c1a> in <module>
----> 1 u.Quantity[u.m]

~/data/mhvk/packages/astropy/astropy/units/quantity.py in __class_getitem__(cls, unit_shape_dtype)
    404         # metadata using Annotated.
    405         if not NUMPY_LT_1_22:
--> 406             cls = super().__class_getitem__((cls, *shape_dtype))
    407         return Annotated.__class_getitem__((cls, unit))
    408 

TypeError: Too few arguments for Quantity
```
It seems that `ndarray.__class_getitem__` cannot be called without an actual `(shape, dtype)`. Those also should be meaningful, meaning that the current test `u.Quantity[u.m, "more"]` would seem to incorrectly associate this "more" with the `ndarray` aspect.
```
In [13]: u.Quantity[u.m, "more"]
Out[13]: typing.Annotated[astropy.units.quantity.Quantity[astropy.units.quantity.Quantity, 'more'], Unit("m")]
```

My sense is to remove the `super()` call... @nstarman??

**Comment by mhvk** [comment]
See #12511 for a PR that implements my suggestion of just not using `NDArray.__class_getitem__` for now.

**Comment by nstarman** [comment]
Sounds good to me. We can re-add it with some tests on python 3.10. and numpy 1.22+.
I also think the ``u.Quantity[u.m, "more"]`` should be changed to fail regardless. As in we should always have the arguments be (unit, shape, dtype) regardless of whether the latter two are functional.

**Comment by pllim** [comment]
Is this resolved?

**Comment by mhvk** [comment]
Also removed `numpy-dev`, but perhaps this is a case for `upstream-fix-required`? @nstarman?

**Comment by mhvk** [comment]
@nstarman - seeing your typing updates in #14286, just a reminder that perhaps this issue can be closed with the subsequent update to the minimum version of numpy (even if we just add something that only works for `not NUMPY_LT_1_22`).

**Comment by neutrinoceros** [comment]
@mhvk that would be https://github.com/astropy/astropy/pull/15706 ?
so, should we just close this one ?

**Comment by mhvk** [comment]
Let's ping @nstarman about this - right now, we are not calling `ndarray.__class_getitem__` ever, which means we cannot indicate a shape or dtype in the typing. Should we change that?

**Comment by nstarman** [comment]
Yes. This kept getting pushed because I think I made a mistake in setting up the type hint. IMO what we should do (explained  https://github.com/nstarman/astropy-APEs/blob/units-quantity-2.0/APE25/report.pdf) is make it `Quantity[ValueType, UnitStuff]`, so one would do `Quantity[NDArray[float], "length"]`.
For backwards compatibility we should override ``__class_getitem__`` and implement a `QuantityU` (or similarly named) GenericAlias that is parametrized only by the unit stuff — akin to how ``numpy.typing.NDArray[dtype]`` drops the shape stuff from `numpy.ndarray[shape, dtype]`.
