### ISSUE TITLE
Astropy.Table.read is limited to int16, but I need larger. How to do this?

### ISSUE THREAD

**Issue by Nestak2** [astropy/astropy#12533]
### Description

`table = Table.read('file.fits', memmap=True)` has only `int16` range for integers, but I need more

### Expected behavior

To be able to read large integers (>100000k) with `astropy.Table.read`, but they got converted into range -32768 to 32767

### Steps to Reproduce

Read in a table that has a column exclusively containing integers larger than 32767:

```
from astropy.table import Table
table = Table.read('file.fits', memmap=True)
```

If you then plot the column you will see that the integers get "wrapped" in the range -32768 to 32767. I created a plot of my column. The values should be monton increasing, but they instead get converted down to the range.

![int16_overflow](https://user-images.githubusercontent.com/16193553/143875912-e8ecb1f0-ab44-4e09-9e0a-935ad87f37a2.png)

### System Details

Linux-5.11.0-40-generic-x86_64-with-glibc2.10
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
Numpy 1.21.2
astropy 3.2.3
Matplotlib 3.4.3
I have no erfa and no scipy package.

How can I allow for larger integers to be read correctly? I was reading the documentation in the links below, but found nothing helpful. Thanks for any suggestions!
https://docs.astropy.org/en/stable/io/fits/api/hdus.html
https://docs.astropy.org/en/stable/io/unified.html

**Comment by saimn** [comment]
Could you explain a bit more (with some code example) what you are trying to achieve ? FITS and Astropy support other integer types, 32 or 64 bits.

**Comment by Nestak2** [comment]
@pllim Yes, I think the `int16` datatype comes from my fits-file. Anyways, I could solve my problem if astropy.table allows me somehow to change the data type of the particular column of interest. But I can't find the option for this. Do you know how?

@saimn Well, what I am trying to do in a narrow sense is to correct a column in a fits file. The column should contain ~335k different integers, each corresponding to a different celestial body as origin for the data. But now it contains only 32767 integers, because of the `int16` format. The fits file itself is very large (~15 GB) and is the product of merger of spectra (flux and wavelength) of ~335k fits files of astronomical spectra I want to investigate. The large fits file is not created with python code, but using the STILTS terminal commands. I can't upload the large fits file here, because it is too large, but [here](https://drive.google.com/file/d/1SZzUJWRGm_D1XzAzkPWdoTEkzdq_OBHI/view?usp=sharing) you can have a look at a small excerpt of the file with data only from 10 bodies/spectra, instead of 335k. In a nutshell - I want to change the data type of one column from int16 to int32 or something else, this would then allow me to correct the values inside. But if you have other suggestions for me feel free to share! tnx

**Comment by pllim** [comment]
I am confused. Why not fix the datatype in the table header itself if it is wrong to begin with?

**Comment by pllim** [comment]
According to this API, I am not sure if you can override the data types:

https://github.com/astropy/astropy/blob/bfb9252df19b0ab7f91d6656eed8850858aea0b4/astropy/io/fits/connect.py#L114

**Comment by saimn** [comment]
Ok, so yes the `int16` is the format your table was written with.
If I understand correctly, you can change the type of your column and then change the values:
```
t = Table.read('table2_stilts.fits')
t['seqcol'] = t['seqcol'].astype(int)
```
This will change the type to `int64`. You could use another type, e.g. `np.int32`.

**Comment by Nestak2** [comment]
@saimn Thanks! Is this written somewhere in the docs or how did you figure it out?
I load my table with `memmap=True`, so
`t = Table.read('table2_stilts.fits', memmap=True)
`
and this happens really quickly.

But when I do 
`t['seqcol'] = t['seqcol'].astype(int)`
my jupyter lab kernel dies after a minute of loading or so. I guess it is because my file is really large (~15GB, 3 columns*150423570 rows). Can I overwrite the data type while reading in the file? Or is there another solution?

**Comment by saimn** [comment]
Columns are just Numpy arrays so you can change their type. However given how memmap works and how FITS files are stored, it's currently impossible to load only one column in memory without loading the entire table. So when you convert the column to `int64` the whole table is loaded. You could use `np.int32` to minimize the extra memory needed, but this doesn't change the need to load the full table.
(Also you are using an old astropy version and I noticed that the memmap feature is broken in recent versions).
