### ISSUE TITLE
Extension names are not being written

### ISSUE THREAD

**Issue by masonng-astro** [astropy/astropy#12530]
Hi, from this minimal working example available from [the tutorial](https://docs.astropy.org/en/latest/io/fits/#creating-a-file-with-multiple-extensions) on handling FITS files, the FITS file is created successfully, but the name of the extension is still "NoName" even though it should be "CUSTOM", as a parameter of fits.BinTableHDU. Advice would be appreciated.

```
from astropy.io import fits
import numpy as np
c1 = fits.Column(name='a', array=np.array([1, 2]), format='K')
c2 = fits.Column(name='b', array=np.array([4, 5]), format='K')
c3 = fits.Column(name='c', array=np.array([7, 8]), format='K')
t = fits.BinTableHDU(name='CUSTOM').from_columns([c1, c2, c3])
t.writeto('table2.fits',overwrite=True)
```

**Comment by saimn** [comment]
`from_columns` is a class method, so it returns a new object, and `BinTableHDU(name='CUSTOM').from_columns([c1, c2, c3])` is basically the same as `BinTableHDU.from_columns([c1, c2, c3])` (which is the normal way to create a `BinTableHDU` from a list of columns).
So to set the extension name you can use either:
```
t = fits.BinTableHDU.from_columns([c1, c2, c3])
t.name = 'CUSTOM'
```
or additional parameters to `from_columns` are passed to `BinTableHDU`, so this would work:
```
t = fits.BinTableHDU.from_columns([c1, c2, c3], name='CUSTOM')
```
