### ISSUE TITLE
Cache large ephemeris files between test runs

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#12564]
I think in principle our new caching machinery allows us to use pre-stored files in CI or in our own testing runs, and it would be nice to start using this especially for really big files such as the JPL ephemeris files. There really is no reason to keep on downloading those from the JPL site!

**Comment by pllim** [comment]
I think this issue is a subset of #8748 . I don't think we figured out exactly how to do this with the free version of GitHub Actions. Actions allows you to store and retrieve artifacts but there are limitations. This definitely needs some R&D investment.

**Comment by mhvk** [comment]
OK, closing in favour of #8748 - thanks for reminding me of that!
