### ISSUE TITLE
Unpickling structured quantities

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#12575]
### Description

Structured quantities cannot be unpickled.

### Expected behavior

If it can be serialized, it can be unserialized.

### Actual behavior

A ``TypeError`` is raised unless `protocol=0` or `1`.

### Steps to Reproduce

```python
import pickle
import astropy.units as u

m_nu = u.Quantity((0, 0, 0.6), unit="(eV, eV, eV)")
serialized = pickle.dumps(m_nu, protocol=2)
pickle.loads(serialized)
```

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.9.5 (default, May 18 2021, 12:31:01) 
[Clang 10.0.0 ]
Numpy 1.21.4
pyerfa 2.0.0.1
astropy 5.1.dev207+gbfb9252df.d20211130
Scipy 1.7.1
Matplotlib 3.3.4

**Comment by nstarman** [comment]
@mhvk, it looks like protocols 0 and 1 are quite different than 2-5.
Might need to change ``get/setstate`` to get those pickle protocols to work?

**Comment by mhvk** [comment]
The current `__reduce__` and `__setstate__` are very old indeed - updates would be a good idea! I don't even know why we wouldn't use `__getstate__`...
