### ISSUE TITLE
WARNING: Tried to get polar motions for times after IERS data is valid (need clearer message in warning on how to set software default)

### ISSUE THREAD

**Issue by mzechmeister** [astropy/astropy#12608]
Currently, I get:
```
WARNING: Tried to get polar motions for times after IERS data is valid.
Defaulting to polar motion from the 50-yr mean for those.
This may affect precision at the 10s of arcsec level [astropy.coordinates.builtin_frames.utils]
```
raised in:
https://github.com/astropy/astropy/blob/698d2e802ffe163439d6ae0eac6ef76083f6e698/astropy/coordinates/builtin_frames/utils.py#L66

Which files do I need to update (and how) to resolve this warning?

The warning message could be made more user friendly.

**Comment by mzechmeister** [comment]
After quite some debugging, I think the problem was caused by an url with is not updated anymore: iers_conf.iers_auto_url = 'https://astroconda.org/aux/astropy_mirror/iers_a_1/finals2000A.all'
I switched to:
iers_conf.iers_auto_url = 'https://datacenter.iers.org/data/9/finals2000A.all'
Probably, I spotted the link here: https://github.com/astropy/astropy/issues/8981#issue-467063969.

Thus the warning could a give hint to check this file.

**Comment by pllim** [comment]
@mhvk , would an extra message to remind user to check `conf.iers_auto_url` completely cover such a problem or can this warning also be triggered by other causes?

**Comment by mhvk** [comment]
Yes, I think we could expand the warning. But we should also move the link back!

**Comment by pllim** [comment]
@mhvk , can you please clarify what you mean by "move the link back"? It's been a while since I looked at that part of the code.

**Comment by pllim** [comment]
@mzechmeister , are you interested to open a PR? https://docs.astropy.org/en/latest/development/workflow/development_workflow.html

**Comment by mzechmeister** [comment]
@pllim, I prefer here to only comment.

**Comment by mhvk** [comment]
@pllim - I have this vague memory that we had to change the link to this `astroconda` one because the regular `finals200A.all` became unavailable. Though I think that was actually a link to some `.mil` site to the astrometry group there. Of course, also fine to just ensure `astroconda` is kept up to date - I'm not sure who's responsible for that, though...

**Comment by pllim** [comment]
I am now confused. We don't point to `astroconda`.

https://github.com/astropy/astropy/blob/b237fbccfe42db4d77f1100e529d21f2569b7b9b/astropy/utils/iers/iers.py#L42

**Comment by mhvk** [comment]
@mzechmeister - now I'm super-confused too - where did your configuration come from? Is that default IERS_A_URL changed in making the conda astropy packages?

**Comment by mzechmeister** [comment]
It seems the problem started with #9427, and, I guess, I used https://github.com/astropy/astropy/issues/8981#issuecomment-523984247  to solve my problem https://github.com/mzechmeister/serval/issues/33#issuecomment-551156361. It's hard to keep track, when the url changes all the time.

**Comment by mhvk** [comment]
OK, that makes sense, and though the URL changes are largely out of our control, I'm sorry it led to your problems! Bottom line, I think, is that it would be useful for the warning message to point to some documentation about how to solve this...

**Comment by pllim** [comment]
All said though, it is recommended that you use the default, because we test it in the CI. We are not responsible for custom settings.
