### ISSUE TITLE
Remove remaining use of distutils

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#12650]
Remaining use of `distutils` again led to test breakage as it is being deprecated, so in #12649 we removed most of the last uses. One further one is in `astropy/version.py`, which probably should also go. With that, one would hope any mention of `distutils` for warnings to ignore in `setup.cfg` could go too.

**Comment by pllim** [comment]
Also see:

* #10578
* #12322

**Comment by mhvk** [comment]
Hmm, seems I should follow instructions and look for previous issues!!  Anyway, at least getting rid of the use of `LooseVersion` in `version.py` should ensure astropy itself doesn't use `distutils` at all any more...
