### ISSUE TITLE
Improve updating test images workflow

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#12673]
I'm working on a PR that changes a test image, and the workflow for updating test images is very long:

1. Download each updated test image from circleCI
2. Rename each test image from `result.png` to the name of the test
3. Fork + clone https://github.com/astropy/astropy-data
4. Make a copy of the test image folder (this is as far as I got)
5. Rename the test image folder with the current timestamp
6. Put each test image in the right folder
7. Open a PR on https://github.com/astropy/astropy-data with the changes
8. Wait for this PR to be merged
9. Update the timestamp in `astropy.tests.image_tests` to point to the new images

In contrast, over in sunpy the process is:
1. Download new hashes of changed `.png` files from circleCI
2. Update the hash file in the PR

It would be great to try and improve the astropy experience - currently working through all these steps is a blocker on me working on some stuff. Some immediate thoughts I had:

- Make sure the new images on circleCI have the right filename (instead of `result.png`) would eliminate step 2
- Since the test data repo is version controlled, make use of that to remove the need to have multiple timestamped folders would eliminate steps 4 + 5
- It should be possible to completely automate the process, such that image tests are allowed to fail in PRs, but if a PR is accepted and merged a CI run on the `main` branch automatically uploads (or opens a PR for) the new reference figures to the astropy data repository.

**Comment by pllim** [comment]
@Cadair has brought this up once in a while. Perhaps he can help you make this possible.

**Comment by pllim** [comment]
This has been resolved by https://github.com/astropy/astropy/pull/13596

**Comment by dstansby** [comment]
❤️
