### ISSUE TITLE
Matplotlib documentation base URL has moved

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#12698]
### Description
It seems the base URL of the docs has changed at some point from https://matplotlib.org/ to https://matplotlib.org/stable/.
Intersphinx links to the old addresses are automatically redirected, but apparently stripped of the section references (the `..#matplotlib.widgets.EllipseSelector` part) in the process.
I could not find any cases of references directly into a section down a page in the core docs (the links still being redirected, but not losing relevant information), but a downstream example together with a fix is presented at https://github.com/astropy/regions/pull/392#issuecomment-1008090707.
So I propose to update the link in `docs/conf.py`

**Comment by pllim** [comment]
Thanks for the heads up. Please see the following PRs:

* #12705
* astropy/sphinx-astropy#52
