### ISSUE TITLE
Missing images for local CSS file

### ISSUE THREAD

**Issue by vilardellsalles** [astropy/astropy#12715]
### Description

Local CSS file [jquery.dataTables.css](https://github.com/astropy/astropy/blob/main/astropy/extern/jquery/data/css/jquery.dataTables.css) refers to [several images](https://github.com/astropy/astropy/blob/main/astropy/extern/jquery/data/css/jquery.dataTables.css#L49). They are the little arrows next to each sortable column. These images exist at the [CDN](http://cdn.datatables.net/), but they are missing in the repo. This makes that arrows are not displayed when using local files. 

### Expected behavior

![image](https://user-images.githubusercontent.com/22243223/148879832-26c24a92-0c7e-40f2-8fb1-ef8b3b5cbb35.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/22243223/148879870-622985f8-f57a-4f4d-b14c-6ad9e56f1656.png)

### Steps to Reproduce

```python
from astropy.table import Table 
t = Table([[1, 2, 3], [4, 5, 6]], names=('a', 'b')) 
t.show_in_browser(jsviewer=True)
```

### System Details

```
>>> import platform; print(platform.platform())
Linux-5.10.76-linuxkit-x86_64-with-glibc2.2.5
>>> import sys; print("Python", sys.version)
Python 3.8.12 (default, Dec 21 2021, 10:45:09) 
[GCC 10.2.1 20210110]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.22.0
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.0
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.7.3
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.5.1
```

**Comment by pllim** [comment]
Unfortunately, `jquery` is a bundled external library. The version we are bundling is very old and looks nothing like what it is today at https://github.com/jquery/jquery/ . A simple copy and paste to update this isn't possible, so we will need someone familiar with this package to first update this from upstream, and if the problem is still there, open an issue or patch upstream.

**Comment by vilardellsalles** [comment]
Apparently, adding the images from the CDN at the proper location solves the issue. I created a pull request, but adding these 5 binary files to the repo might not be the proper solution.
