### ISSUE TITLE
Fix known test failures for astropy.units.quantity

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#1273]
Once #929 is merged, we should try and fix the few known failures in `astropy.units.quantity` (which occur for a few in-place methods).

**Comment by mhvk** [comment]
@astrofrog - removed the milestone. Some of the `xfail`s have in the meantime been solved. I think here the first thing to do would be to enumerate the ones that remain. My guess is that most will fall in the need-to-document category...

**Comment by mhvk** [comment]
Review old issues: ones that we have `xfail` tests for and still go wrong are:
1. `np.ptp(q1, out=q2)` -- see #4442
1. `np.dot`
2. `np.trace` -- needs to be made subclass aware in `fromnumeric.py` by changing `asarray` into `asanyarray` following `diagonal`; see https://github.com/numpy/numpy/pull/6950
3. `np.outer` -- needs to be made subclass aware in `numeric.py` by changing `asarray` into `asanyarray`; if attempting this, one should also change `tensordot` and `cross` there. Probably makes little sense if one doesn't also address `np.dot` and `np.inner`.
4. `np.inner`

**Comment by mhvk** [comment]
Looking at this again, the only ones left are the "matrix"-like operations, `np.dot`, `np.outer`, `np.inner` (and also the related `tensordot` and `cross`). At least `np.dot` will get resolved once the long-delayed `__numpy_ufunc__` is implemented.

**Comment by Juanlu001** [comment]
What's the status of this after https://github.com/astropy/astropy/pull/2583 was merged? This is the result of `np.dot` with latest NumPy and AstroPy:

```python
In [1]: import astropy; astropy.__version__
Out[1]: '2.0.1'

In [2]: import numpy; numpy.__version__
Out[2]: '1.13.1'

In [3]: from astropy import units as u

In [4]: import numpy as np

In [5]: q = 1 * u.m; q
Out[5]: <Quantity 1.0 m>

In [6]: np.dot(q, q)
Out[6]: 1.0
```

**Comment by mhvk** [comment]
In the end, `np.dot` was not overridden with `__array_ufunc__`, as it is not a real ufunc and it was decided to keep things simple for the implementation. Right now, the easiest workaround probably remains `q.dot(q)`, otherwise one can do `q @ q` (python >=3.5), or `from astropy.utils.compat.numpy import matmul; matmul(q, q)` (for actual matrices, that is).

**Comment by Juanlu001** [comment]
Thanks for the prompt response, I guess this is blocked on https://github.com/numpy/numpy/issues/4164 then.

**Comment by mhvk** [comment]
Yes, though perhaps a bit more specifically https://github.com/numpy/numpy/issues/8892
