### ISSUE TITLE
TST: Cosmology broke CI

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#12744]
Can't tell from the run history if it is from #12740 or #12741.

Example logs:

* https://github.com/astropy/astropy/actions/runs/1709793538
* https://github.com/astropy/astropy/runs/4848331765?check_suite_focus=true

Example error:

```
______________ Testw0wzCDM.test_is_equivalent_to_row[astropy.row] ______________

self = <astropy_tests.cosmology.tests.test_flrw.Testw0wzCDM object at 0x7f99ec7d87c0>
cosmo = w0wzCDM(name="ABCMeta", H0=70.0 km / (Mpc s), Om0=0.27, Ode0=0.73, w0=-1.0, wz=0.5, Tcmb0=3.0 K, Neff=3.04, m_nu=[0. 0. 0.] eV, Ob0=0.03)
to_format = <astropy.cosmology.connect.CosmologyToFormat object at 0x7f99ec7320a0>
format = 'astropy.row'

>   ???
E   NameError: name 'Cosmology' is not defined

astropy/cosmology/io/tests/test_row.py:113: NameError
```

@nstarman , any ideas?

**Comment by nstarman** [comment]
I'll address this imminently. It's from the combo of the two most recent cosmology PRs one removed imports the other needed. Safe separately, disastrous together. Is it possible / does it work with the Astropy pipeline to use GitHub's new merge-queue feature? That would make this type of situation impossible and mean every merge-to-main's CI ran to completion.

**Comment by pllim** [comment]
Re: merge-queue -- Feel free to add it to the next dev telecon agenda. Might need org admin to enable it?

**Comment by pllim** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/using-a-merge-queue

*Note: The pull request merge queue feature is currently in limited public beta and subject to change. Organizations owners can request early access to the beta by joining the waitlist.*

Yeah, only org admin can opt to join the waitlist...
