### ISSUE TITLE
astropy_mpl_style visualization causes plt.colorbar() MatplotlibDeprecationWarning in Matplotlib 3.5

### ISSUE THREAD

**Issue by lanemeier** [astropy/astropy#12753]
### Description

The astropy.visualization.astropy_mpl_style dictionary has 'axes.grid' set to True, this triggers a  plt.colorbar() MatplotlibDeprecationWarning message for pyplot.imshow in Matplotlib version 3.5. Examples such as ones found [here](https://docs.astropy.org/en/stable/generated/examples/io/plot_fits-image.html) reference will trigger the warning message.

```
MatplotlibDeprecationWarning: Auto-removal of
grids by pcolor() and pcolormesh() is deprecated since 3.5 and will be removed t
wo minor releases later; please call grid(False) first.
  plt.colorbar()
```

### Expected behavior

No deprecation warning message.
### Steps to Reproduce

1. Install Matplotlib version 3.5
2. Run the following code

```python
import matplotlib.pyplot as plt
from astropy.visualization import astropy_mpl_style
plt.style.use(astropy_mpl_style)

from astropy.utils.data import get_pkg_data_filename
from astropy.io import fits

image_file = get_pkg_data_filename('tutorials/FITS-images/HorseHead.fits')
fits.info(image_file)

image_data = fits.getdata(image_file, ext=0)

plt.figure()
plt.imshow(image_data, cmap='gray')

plt.colorbar()
```

### System Details

Windows-10-10.0.18362-SP0
Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Numpy 1.20.3
pyerfa 2.0.0
astropy 5.0
Scipy 1.7.3
Matplotlib 3.5.0

**Comment by pllim** [comment]
I think this is related to matplotlib/matplotlib#21723 . We have `axes.grid` set to `True`, so not sure why we are even seeing this.

https://github.com/astropy/astropy/blob/ed016c069e47b47369cdd5165665e16b7d65bbfc/astropy/visualization/mpl_style.py#L32

**Comment by lanemeier** [comment]
Thanks for responding so quickly and mentioning this to matplotlib. I can work around it, but I wanted to alert the project about the potential issue with grids in styles.
Users may find the warning concerning. See https://stackoverflow.com/q/69999315/15531842

**Comment by pllim** [comment]
Yes, definitely good to know of these warnings earlier than later. Thanks for the report!

**Comment by pllim** [comment]
I cannot tell if matplotlib/matplotlib#22285 had fixed your problem. Are you able to test out your use case with dev version of matplotlib? Or maybe even better, add a test that would trigger this in our test suite and see which jobs still fail? Thanks!

**Comment by lanemeier** [comment]
I pulled down the latest master matplotlib-3.6.0.dev1433+g9844e9ffad and confirmed that the warning message is gone.

Wish I had more time to add the test into the suite.
