### ISSUE TITLE
Automate benchmarking?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#12767]
Numpy is thinking about adding benchmarks - https://github.com/numpy/numpy/issues/20785

See in particular https://github.com/numpy/numpy/issues/20785#issuecomment-1018200617,
> Inspired by https://labs.quansight.org/blog/2021/08/github-actions-benchmarks/ xarray has added a workflow that you probably can copy/paste pretty easily, see https://github.com/pydata/xarray/pull/5796.

So, it sounds like using github actions is not impossible. But it will need some fairly careful thought to ensure our benchmarks do not take ridiculously long.

**Comment by pllim** [comment]
Also see:

* astropy/astropy-benchmarks#106
* astropy/astropy-benchmarks#102

**Comment by mhvk** [comment]
Hah, I am clearly far behind the times! Feel free to close this - though perhaps it is useful to have an issue in the main repo to get a few more eyes on it...

**Comment by pllim** [comment]
Yes, let's keep this open too. 😸
