### ISSUE TITLE
Can't open paths beginning with ~

### ISSUE THREAD

**Issue by svank** [astropy/astropy#12778]
### Plan

https://github.com/astropy/astropy/pull/13107#issuecomment-1104552457

### Description
`astropy.io.fits` can't open files when the path is given with a `~` representing the home directory, e.g. `fits.getdata("~/data/file.fits")`. Instead, the home directory must be spelled out, e.g. `fits.getdata("/home/sam/data/file.fits")`. This can be fixed by passing paths to `os.path.expanduser`, which should do the right thing across operating systems.

There was some discussion about `expanduser` in #10705, and it looks like the function is now in use for finding the Astropy configuration directory.

There is also [precedent in Sunpy](https://github.com/sunpy/sunpy/blob/main/sunpy/util/io.py#L26), where `expanduser` (as wrapped by `pathlib`) is used for paths passed to Sunpy's `Map` object, so that `sunpy.map.Map("~/data/file.fits")` works. (`Map` is their general object for loading, manipulating and plotting data).

If there's not a reason to avoid adding calls to `os.path.expanduser`, I'm happy to dig into the code and prepare a PR. I'm most interested in the FITS loader, but I might take a look at the rest of `astropy.io`. (The Github search tool doesn't show any uses of `expanduser` there.)

### Expected behavior
`astropy.io.fits.getdata("~/data/file.fits")` loads the file `file.fits` in the `data` directory within the user's home directory.

### Actual behavior
`astropy.io.fits.getdata("~/data/file.fits")` raises `FileNotFoundError: [Errno 2] No such file or directory: '~/data/file.fits'`

### Steps to Reproduce

Attempt to load a FITs file in the user's home directory, giving a path beginning with a `~` representing the path to the user's home directory.

### System Details
Linux-5.13.0-27-generic-x86_64-with-glibc2.31
Python 3.10.1 | packaged by conda-forge | (main, Dec 22 2021, 01:39:05) [GCC 9.4.0]
Numpy 1.22.1
pyerfa 2.0.0.1
astropy 5.1.dev516+g20513ae79
Scipy 1.7.3
Matplotlib 3.5.1

**Comment by pllim** [comment]
This is because `io.fits` farmed it out to built-in `open()` and it does not support `~` either.

https://github.com/astropy/astropy/blob/20513ae79a9100381ec7b61b1a324155c2814086/astropy/io/fits/util.py#L378-L388

```python
>>> open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '~/test_data/jb5g05ubq_flt.fits'
```

**Comment by svank** [comment]
I just took a shot at adding a call to `expanduser` to that bottom-level `fileobj_open` method you pointed out:
```python
def fileobj_open(filename, mode):
    filename = os.path.expanduser(filename)
    return open(filename, mode, buffering=0)
```

This enables the `~` shorthand for `fits.open`, `fits.getdata`, `fits.getheader`, `fits.info`, `fits.writeto`, and `HDUList.writeto` (and surely others), without breaking any tests.

To test the behavior more fully, I hacked up the `FitsTestCase` class in `io/fits/tests/__init__.py`. Its `data()` method takes a filename and returns that filename joined with the absolute path to `io/fits/tests/data`, and it appears to be used throughout the FITS test cases. I had it instead return `~/{filename}`, and I set my $HOME environment variable to that `data` directory. When I do this:
- 125 tests fail without the added `expanduser` call and pass with the added call. (115 raise a `FileNotFoundError`, the remaining 10 are from the tests for the fitscheck, fitsheader, and fitsinfo, where it looks like the underlying script is experiencing the same error)
- 51 tests fail for the expected reason that my crude hack broke them. I checked each, and mostly these failures get a path from that `data()` method and then open it directly with the builtin `open()`, rather than going through an `io.fits` function. These tests shouldn't be expected to pass in this case.

If the `io.fits` tests exercise all the functions that read or write FITS files, I think this suggests that they all go through `fileobj_open`, and this one change would enable `~`-abbreviated paths without breaking anything. 

I'd advocate for supporting these `~`-style paths as a nice convenience feature, especially since it appears to be that one-line addition (at least for the FITS module). If it sounds good, I'll think about how to properly test it and prepare a PR.

**Comment by saimn** [comment]
I'm not sure we want to support this. This is usually something that the user should choose to use or not. E.g. `numpy.genfromtxt` or h5py doesn't support this as well, though pandas does. If we were to support this I think this should also be the case for other astropy `io` functions, `Table.read`, `ascii.read`, etc.

**Comment by saimn** [comment]
Other opinions, maybe @taldcroft @hamogu @dhomeier ?

**Comment by hamogu** [comment]
Sounds useful to me. I would have expected it to work, although I clearly never tried (or I would have found that it fails). In my institute the home directory sits on a remote server and we avoid having any significant data there for performance reasons, thus I never tried. I don't see a drawback - it your path does not include `~` then there is (should be) no change in behavior, so it's not like we break anything. Thus, I don't think it needs to be opt-in, it could just work. I can't think of a case where you have `~/` in a file path (need to be careful not to expand `~/` when the input filename is a URL!) and do **no**want to expand it, but maybe that's just a lack of imagination on my part.

`expanduser` is standard library Python, in other words, stable, well-supported and tested. The only question (and that's something I have thought about very little) is if there is any benefit to go through `pathlib` for any filename that is not a URL instead of patching the current behavior (we do support Pathlib objects in places, but it's not used consistently throughout as one can see by the fact that bugs like #10594 still crop up).

**Comment by dhomeier** [comment]
I agree that this would be a very useful convenience functionality, and very little risk of breakage (also `expanduser` correctly ignores non-existing users, e.g. returning `~gumpy` unchanged if there is no user `gumpy`).
The main point as @saimn raised it is that the behaviour should be consistent; this functionality may not be expected from lower-level I/O like `np.loadtxt`, but if Pandas can support it, I think `astropy.io` could as well – but it should work for all supported formats, so it would function with `Table.read('~/data/spSpec-23.dat')` regardless of the file format.

Looks like much, if not all of `io.ascii` and perhaps even other formats, could be handled by `get_readable_fileobj`
https://github.com/astropy/astropy/blob/314dbe860be368465f302f4bc272f73241794dff/astropy/utils/data.py#L263-L270

**Comment by taldcroft** [comment]
I'd be :+1: on supporting this functionality, with a goal of making it consistent through all the subpackages. As noted `get_readable_fileobj` is a good starting point.

**Comment by svank** [comment]
It sounds like opinions are generally in favor, so I'll find some time to draft a PR, with a goal to add this support throughout `astropy.io`, not just the `fits` module.

I think the only downside with this change (as mentioned by others) would be breakage if users provide a relative path that begins with `~` or `~valid_system_username_here`. That must be specifically a directory (or file without an extension) whose name is exactly one of those keywords---something like `~valid_system_username_here.fits` is not expanded. As others mentioned, this seems like a very rare case, but that small risk of breakage could be avoided by something like:
```python
if not os.path.exists(path):
    path = os.path.expanduser(path)
```
This would allow those unlikely directories named `~` to still be opened as before while supporting `~` expansion in all other cases, though it would deviate from the typical command-line semantics where `~` seems to always be expanded. I'm not sure I'd do it this way if it were up to me, but it's an option if the backwards compatibility seems worth it.

**Comment by pllim** [comment]
Can this issue be closed now? All the affected subpackages are patched, right? Thanks!

**Comment by svank** [comment]
Thanks for wrangling all these PRs!

I was looking through and I think there's one regression test for `nddata` that didn't make it into any of the split-up PRs. There weren't changes in `nddata`, it just gained this tilde-expansion feature because it uses one of the other modules, so getting that regression test merged seems worthwhile. There was also discussion somewhere of adding a "What's New" entry once all the submodules were merged.

I can do those sometime this weekend. Ought they be two separate PRs?

**Comment by pllim** [comment]
Thank YOU for doing the work!

> adding a "What's New"

In regards to What's New: Some are already in v5.1 while some will be in v5.2, so you will have to keep that in mind while writing What's New for v5.2.

> Ought they be two separate PRs?

If they will both be in the same release, I don't see why they have to be separate PRs. I think it is less work to have them both in the same PR but I'll leave it to your good judgement.

**Comment by pllim** [comment]
Thanks again. Un-tilde next time! 😏
