### ISSUE TITLE
Warnings from new `unit_parse_strict='warn'` settings

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#12790]
### Description
#11843 introduced an improved validation setting for non-standard units in FITS headers and made the `'warn'` level the default (contrary to the docstring description). This issues new `UnitsWarning`s in a number of  circumstances like the RTD builds in #12784.

### Expected behavior
The `unit_parse_strict` default should be documented in the `read_table_fits` docstring.

The specific case of the RTD warnings from `timeseries` is probably best addressed by explicitly setting
`Table.read(hdu, format='fits', unit_parse_strict='silent')` in `kepler_fits_reader`, since that function is performing its own custom treatment of nonstandard units (or should this make better use of the `u.add_enabled_units` mechanism as well?)

But we probably should expect a number of similar warnings, possibly treated as errors, to pop up downstream from this change.

### System Details
5.1.devx

**Comment by pllim** [comment]
I think #12788 handled this too.

**Comment by pllim** [comment]
Oh wait, you are not just talking about the RTD log. I re-opened the issue.

**Comment by pllim** [comment]
Removing the milestone though. We usually don't milestone issues unless they block the release.

**Comment by dhomeier** [comment]
No, the errors just don't appear in the 5.0.1 backport since #11843 is on the 5.1 branch.
Also it is not just a docs issue since the warnings will start popping up in anything that uses `read_table_fits` or `Table.read` directly, so it should probably be dealt with before the 5.1 release.

**Comment by saimn** [comment]
>  Also it is not just a docs issue since the warnings will start popping up in anything that uses read_table_fits or Table.read directly, so it should probably be dealt with before the 5.1 release.

Which was the goal of #11843, so I don't see what's the issue to deal with here ? (Apart from the default value mentioned in the docstring which is wrong).

**Comment by dhomeier** [comment]
> > Also it is not just a docs issue since the warnings will start popping up in anything that uses read_table_fits or Table.read directly, so it should probably be dealt with before the 5.1 release.
> 
> Which was the goal of #11843, so I don't see what's the issue to deal with here ? (Apart from the default value mentioned in the docstring which is wrong).

Yes, that was the obvious one I was running into first. The other is that

https://github.com/astropy/astropy/blob/dbb45773367583e88334da98cc93c1eb10f8ab65/astropy/timeseries/io/kepler.py#L58-L74

is already aware of the non-standard units and dealing with them explicitly, so should not transmit the warning on top of that. The question is probably if setting `unit_parse_strict='silent'` and then keeping the existing treatment is the better fix, or if this can make use of #12808. Pinging @nabobalis and @mvhk – would the `unit_format='generic'` option resolve this already?

This could provide an example for downstream how to handle such files properly in the future, which would probably affect every piece of code reading Kepler or TESS data files.

**Comment by saimn** [comment]
There is still the case of `BJD - 2454833` which is not handled here. And even with the "generic" parser, `e` or `pixels` would not be valid units. 
So if those files contain invalid units, I guess that's up to timeseries' maintainers to choose to use `unit_parse_strict='silent'` or not (would make sense since it was the previous behavior), but I don't think that's a fits or units issue :).
