### ISSUE TITLE
ascii.mrt format does not keep column names consistently

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#12804]
While looking at #12803, I tried the new `ascii.mrt` writer to see how much information is carried on, and think there is a problem with names of `Quantity` columns:
```
from astropy.table import QTable
import astropy.units as u
from astropy.io.ascii import Mrt

qt = QTable([np.arange(4)*u.m, ['a', 'b', 'c', 'ddd']], names=['a', 'b'])
print('\n'.join(Mrt().write(qt)))
Title:
Authors:
Table:
================================================================================
Byte-by-byte Description of file: table.dat
--------------------------------------------------------------------------------
 Bytes Format Units  Label     Explanations
--------------------------------------------------------------------------------
1-3  F3.1   m      Unknown Description of Unknown
5-7  A3     ---    b       Description of b      
--------------------------------------------------------------------------------
Notes:
--------------------------------------------------------------------------------
0.0 a  
1.0 b  
2.0 c  
3.0 ddd
```
It seems strange there here the label for the first column is "Unknown" rather than "a".

p.s. Also a bit odd is that there is a default explanaion - why not just leave it empty?

**Comment by hamogu** [comment]
> p.s. Also a bit odd is that there is a default explanaion - why not just leave it empty?

The way I envision using the MRT table writer (and I do, the question is if other people use it that way, too) is to write my data to a file which I then submit to a journal. There will always be pieces in the MRT that will have to be filled in manually, for example the table number might change until the final typesetting by the publisher. Thus, I imagine that filling in some of the meta data (e.g. the table number) is up to the data editors or publishing staff at the journal or at CDS and they hopefully know exactly how to do that. However, the description of each column is going to be written by the authors of the paper. I think that adding in a default text will make it more obvious that something needs to edited here and how that text needs to be formatted (number of spaces before the first word etc.).

I don't think of MRT tables are good data storage for internal projects - ECSV (for any table, unless it's too big to be saved as ASCII) or fits (for large tables with less complex data types or meta-data) are much better for that . Rather, in my mind, an MRT tables is an output comparable to a matplotlib plot where I would also tweak the appearance by hand to add labels, change the position of the legend etc.

**Comment by mhvk** [comment]
Ah, yes, makes sense to make something edit-ready. That leaves the odd thing about the label not being right. Investigating this, I found the problem was that `Column(quantity)` does not copy over the name, so unrelated to MRT. I'll push up a fix.

**Comment by mhvk** [comment]
See #15484 - turns out there was a little buglet in the MRT code as well, which caused other names not to be propagated.
