### ISSUE TITLE
Decrease import time of affiliated packages

### ISSUE THREAD

**Issue by EfremBraun** [astropy/astropy#12801]
I've noticed that astropy-affiliated packages take a long time to import. For example, `from astroquery.heasarc import Heasarc` takes 0.9 seconds on my laptop, and `import pyvo` takes 1.1 seconds. That's a little longer than it takes to import ALL of numpy, scipy, matplotlib, astropy, pandas, sklearn, bokeh, and PySide6.

This can be rather frustrating for certain users (e.g., when these packages are embedded into GUIs where the end-user doesn't know that there's a background Python process importing packages which is what's causing the delay to the application startup).

I looked into why this might be, and I found a package named Tuna (https://github.com/nschloe/tuna; see how to use it for examining imports at https://stackoverflow.com/a/51300944). Here are the results for running the two import statements above:
[tuna - astroquery.log.pdf](https://github.com/astropy/astropy/files/7960199/tuna.-.astroquery.log.pdf)
[tuna - pyvo.log.pdf](https://github.com/astropy/astropy/files/7960200/tuna.-.pyvo.log.pdf).

The biggest single-item contributions to the long import time that I see is that 0.3 seconds is spent importing Dask and 0.17 seconds is spent importing Astropy's TestRunner. I suspect that both of these are unnecessary for most astropy-affiliated packages, and removing them from imports might not be too hard.

Regarding TestRunner:
Affiliated packages are required to have the line `from ._astropy_init import *` in their __init__.py file (ex. https://github.com/astropy/astroquery/blob/main/astroquery/__init__.py and https://github.com/astropy/pyvo/blob/main/pyvo/__init__.py). _astropy_init.py has the line `astropy.tests.runner import TestRunner`. If this is only used for developer testing, I don't think this needs to be imported by users.

Regarding Dask:
I'm not so sure what exactly is going on here. Is Dask actually need for all applications? Generally the FITS files that I'm working with are small, so if Dask is just being used to speed up file reads, I'd be much happier sacrificing the <0.01 seconds that I'm expecting Dask is contributing to reading a FITS file to get rid of the 0.3 seconds that it takes for the import. Is there a way to make this import optional?

**Comment by pllim** [comment]
Hello. `astropy` package and the Astropy Project has no maintenance control over *affiliated* packages. While *coordinated* packages are under the Project's umbrella, each of them has their own set of maintainers. I propose you open an issue for each affected package that you mentioned:

* https://github.com/astropy/astroquery/issues (coordinated)
* https://github.com/astropy/pyvo/issues (affiliated)

I am afraid there is not much we can do for you over here at `astropy`.

Re: `TestRunner` -- It is only useful if you want your users to be able to run `package.test()` for the *installed* package. Otherwise, yes, I agree you can remove it. However, if you want users to be able to run `package.test()`, it is basically a public user API, and therefore not unreasonable to be in `__init__.py`, but also no rules that say you cannot exclude it.

Re: `dask` import in `astropy.io.fits` -- I'll have to defer to @astrofrog and @Cadair since they added that support in #9742. cc @saimn

**Comment by EfremBraun** [comment]
Re: `TestRunner`
Ah, I thought that since `from ._astropy_init import *` was right under the comment `# Affiliated packages may add whatever they like to this file, but should keep this content at the top.` that that import was required of all affiliated packages. Is that not correct?  I see it in MOST of the affiliated packages (just looking at a random 3, of https://github.com/karllark/dust_extinction/blob/master/dust_extinction/__init__.py, https://github.com/aplpy/aplpy/blob/master/aplpy/__init__.py, and https://github.com/cosimoNigro/agnpy/blob/master/agnpy/__init__.py, 2 of the 3 of them have this import, with `TestRunner` then being imported in _astropy_init.py. So I guess that since not ALL of them have it, it's not technically necessary. Anyway, I'll post this on the issue lists of astroquery and pyvo.

**Comment by pllim** [comment]
I think "should" here should be interpreted as "delete if you want, but if you wish to keep it, it has to be on top." 😬

**Comment by astrofrog** [comment]
I think for the dask issue in io.fits we could lazily import it by doing something like

```python
def is_dask_array(array):
    if hasattr(array, 'compute'):
        try:
            from dask.array import Array
            return isinstance(array, Array)
        except ImportError:
            return False
    else:
        return False
```

and using that instead of the ``isinstance`` calls - then it would only import dask if the array object really does look like a dask array.

**Comment by mhvk** [comment]
The import is only done to check whether `data` can be `DaskArray`. More pythonic, I think, would just be to ducktype on anything that looks array-ish (after all, Xarray is probably fine too...) --- see a quick PR at #12805

**Comment by EfremBraun** [comment]
I checked out PR #12805, but the time to run `from astroquery.heasarc import Heasarc` didn't change, and the Tuna log still showed Dask being imported.

**Comment by mhvk** [comment]
OK, that just didn't work. Something along the lines of what @astrofrog suggested at #12806.

**Comment by EfremBraun** [comment]
I'm afraid #12806 is having the same issue as #12805 was: it's still not decreasing the time to run `from astroquery.heasarc import Heasarc`. The `from dask.array import Array as DaskArray` statement in astropy/io/fits/hdu/image.py is still an issue.
