### ISSUE TITLE
[5.0.1] Missing astropy.utils.decorators.wraps lets other packages fail

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#12802]
### Description

I just uploaded astropy 5.0.1 to Debian and experienced two CI failures:

* [aplpy/2.0.3+git2020.05.29-1](https://ci.debian.net/data/autopkgtest/testing/amd64/a/aplpy/18800371/log.gz)
* [pyvo/1.1-1](https://ci.debian.net/data/autopkgtest/testing/amd64/p/pyvo/18800419/log.gz)

Both packages fail with

```
==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
[…]
/usr/lib/python3/dist-packages/aplpy/decorators.py:3: in <module>
    from astropy.utils.decorators import wraps
E   ImportError: cannot import name 'wraps' from 'astropy.utils.decorators' (/usr/lib/python3/dist-packages/astropy/utils/decorators.py)
=========================== short test summary info ============================
```
Both packages are a bit out of date: for APLPy there is no newer version and the patches required for 5.0 were locally applied on the Debian package (see https://github.com/aplpy/aplpy/issues/467), and the version 1.2.1 of PyVO is still not uploaded to Debian (1.1 was however tested to be compatible to Astropy 5.0).

### Expected behavior

Micro version updates should not break anything.

### Actual behavior

See above

### Steps to Reproduce

Run CI tests for PyVO and APLPy with Astropy 5.0.1 installed.

### System Details

* Linux-5.15.0-3-amd64-x86_64-with-glibc2.33
* Python 3.9.10 (main, Jan 16 2022, 17:12:18) 
  [GCC 11.2.0]
* Astropy 5.0.1

**Comment by pllim** [comment]
But you are not supposed to import that from astropy. Use the one in `functools`.

**Comment by olebole** [comment]
I don't know why these packages take it from astropy. PyVO seems to have that changed only recently: https://github.com/astropy/pyvo/pull/283 (and this is in the new PyVO version 1.2.1), and for APLPy I will add it again locally.

**Comment by olebole** [comment]
Added a PR to aplpy: https://github.com/aplpy/aplpy/pull/469

**Comment by pllim** [comment]
Is there really anything we need to fix here? Seems wrong to add it back for 5.0.2.

**Comment by olebole** [comment]
I have no real opinion on that. The two packages will be fixed on Debian, so it is not a problem for us. I just don't know about expectations or setups of others.

**Comment by agy-why** [comment]
As a work around: updating to PyVO 1.2.1 did the job.
