### ISSUE TITLE
Add bot to check the PR checklist

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#12815]
### Description

In the Dev Telecon today we discussed #9676. Building on top of that, the suggestion is to add a CI bot to check that the PR checklist is all checked.
The bot should probably be "allowed-fail".

```
Require PR authors to write “What’s new” for major features? https://github.com/astropy/astropy/issues/9676
Do we want that? Where do we say so? Suggestion: Add to the PR checklist “[ ] What’s new? entry included in PR (if warranted)”?
The discussion in the issue is stalled, so it seems good to bring it up here to make a decision or suggestion on how to proceed.

Next steps:
Open Issue for: Bot for Checklist is completely checked?  Allowed-fail bot
```

**Comment by pllim** [comment]
@saimn , @Cadair , and I discussed this today and we decided that maybe this has crossed the line a little bit. This might discourage contributors from small PRs. There is also a circular problem of the CI checkbox, this check that checks the CI checkbox, and maintainer cannot check the CI checkbox until CI passes but CI won’t pass if the checkbox is not checked. ♻️ 

Therefore, I propose closing this request as won't fix (even though I did suggest it in the first place).
