### ISSUE TITLE
Add Bot to CI for What's-new

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#12814]
### Description

In the Dev Telecon today we discussed #9676. Building on top of that, the suggestion is to add a bot, triggered by the whatsnew-needed tag, to check that there is a what's-new added. Like with the changelog check, the CI should fail if there is not a what's entry.

```
Require PR authors to write “What’s new” for major features? https://github.com/astropy/astropy/issues/9676
Do we want that? Where do we say so? Suggestion: Add to the PR checklist “[ ] What’s new? entry included in PR (if warranted)”?
The discussion in the issue is stalled, so it seems good to bring it up here to make a decision or suggestion on how to proceed.

Next steps:
- Open Issue for: Bot for checking What’s-new entry exists?
```

**Comment by pllim** [comment]
The easiest thing for me to do is to piggyback this check onto the existing changelog entry check bot at [actions-towncrier-changelog](https://github.com/pllim/actions-towncrier-changelog), which I did. Example of it running:

### No what's new needed

#12863

```
PR labels: ['io.fits', ':zzz: Python3']

No "whatsnew-needed" label, skipping What's New entry check
No changelog file was added in the correct directories for PR 12863
```

### What's new entry missing

#12847

```
PR labels: ['units', 'whatsnew-needed']

"whatsnew-needed" present but no What's New entry; please add one.
```

### What's new entry added by PR author

No such example. If you decide to write one for your PR, let me know what the bot says. 😸 🤖

**Comment by pllim** [comment]
@Cadair , @tomdonaldson , and I decided that current implementation is good enough for now. If people are unsatisfied, they can open new issues/PRs. Thanks!
