### ISSUE TITLE
boundary option 'None' cannot be used in astropy.convolution.convolve

### ISSUE THREAD

**Issue by bertrand-faure** [astropy/astropy#12810]
### Description
The 'convolve' function accepts a boundary argument to control how the convolution filter should handle edges. The conservative approach None (values set to zero where the kernel extends beyond the edge of the array) cannot be used because the argument has the default value 'fill' in the function definition.

https://docs.astropy.org/en/stable/api/astropy.convolution.convolve.html#astropy.convolution.convolve

### Expected behavior
`convolve(array, kernel, boundary=None)` should set values to 0 when the kernel extends outside the data.

### Actual behavior
`convolve(array, kernel, boundary=None)` is interpreted as `convolve(array, kernel, boundary='fill')`, so that the documented None value can never be passed to the function.

One way to fix it would be to follow the docstring and use the string 'None'. That requires updating BOUNDARY_OPTIONS = ['None', 'fill', 'wrap', 'extend'] in convolve.py, as well as updating several conditions based on `if boundary is None`.

**Comment by pllim** [comment]
@keflavich , what do you think?

**Comment by keflavich** [comment]
I don't understand the issue: Could you please provide a minimum working example (MWE)?

The function _does_ allow `boundary=None` to be specified and the behavior appears to be as expected:

```python
In [39]: y = np.ones([100,100])

In [40]: k = np.ones([5,5])

In [41]: convolve(y, k, boundary=None)
Out[41]:
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]: convolve(y, k, boundary='fill')
Out[42]:
array([[0.36, 0.48, 0.6 , ..., 0.6 , 0.48, 0.36],
       [0.48, 0.64, 0.8 , ..., 0.8 , 0.64, 0.48],
       [0.6 , 0.8 , 1.  , ..., 1.  , 0.8 , 0.6 ],
       ...,
       [0.6 , 0.8 , 1.  , ..., 1.  , 0.8 , 0.6 ],
       [0.48, 0.64, 0.8 , ..., 0.8 , 0.64, 0.48],
       [0.36, 0.48, 0.6 , ..., 0.6 , 0.48, 0.36]])
```

**Comment by bertrand-faure** [comment]
Hi,

You are right, I'm very sorry for wasting your time. The issue was elsewhere, the rest comes from my misunderstanding on how python would handle passing None as value for an argument with default. I thought that is was equivalent to not passing the argument at all and would result in the default value (here 'fill') to be used. I'll close the issue.
