### ISSUE TITLE
Document reading True/False in ASCII table as bool not str

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#12828]
### Description

#12826 showed a use case for having an ASCII table column consisting of only "True" and "False" be read as `bool` instead of `str` (current behavior). That issue discusses reasons to maintain the current behavior, but there are simple workarounds discussed there that should be brought out to the narrative docs as examples for users.

I'd suggest the following as a recommendation for users:
```
from astropy.io.ascii import convert_numpy
converters = {'*': [convert_numpy(typ) for typ in (int, float, bool, str)]}

# Then for example
dat = Table.read(filename, format='ascii', converters=converters)
```
This new information could go in the existing section on `Converters` in the `io.ascii` read documentation.

### Additional context

#12826

**Comment by pjs902** [comment]
Hi!

I'm wondering if something as simple as this is sufficient or if you think it needs its own example altogether:
```python  
>>> import numpy as np
>>> converters = {'uint_col': [ascii.convert_numpy(np.uint)],
...               'float32_col': [ascii.convert_numpy(np.float32)],
...               'bool_col': [ascii.convert_numpy(bool)]}
>>> ascii.read('file.dat', converters=converters)
```

While we're at it should we update the preceding paragraph

> The type provided to [convert_numpy()](https://docs.astropy.org/en/stable/api/astropy.io.ascii.convert_numpy.html#astropy.io.ascii.convert_numpy) must be a valid [NumPy type](https://numpy.org/doc/stable/user/basics.types.html) such as numpy.int, numpy.uint, numpy.int8, numpy.int64, numpy.float, numpy.float64, or numpy.str.

 to use the regular python types for `string`, `int` and `bool` instead of the deprecated `np.string`, `np.int` and `np.bool`?

**Comment by taldcroft** [comment]
Thanks for looking into this @pjs902. I think the advantage of the original suggested workaround is that it will work for any table regardless of column names. I suspect that in most cases of tables with `True/False` strings, the user wants this applied to every column that looks like a bool.

Definitely :+1: on updating the docs to use regular Python types instead of the deprecated numpy versions.

**Comment by pjs902** [comment]
@taldcroft Sorry if I wasn't clear, I had only changed the column names to make it obvious that we had columns with different types, not suggesting that we require certain column names for certain types, I could switch these back to the original column names which were just `col1`, `col2`, `col3`.

**Comment by taldcroft** [comment]
@pjs902 - I had a mistake in the original suggested workaround to document, which I have now fixed:
```
converters = {'*': [convert_numpy(typ) for typ in (int, float, bool, str)]}
```
With this definition of `converters`, there is no need to specify any column names at all since the `*` glob matches every column name.

**Comment by pjs902** [comment]
@taldcroft Both solutions seem to work equally well, do you think it's better to switch the example in the docs to 

> converters = {'*': [convert_numpy(typ) for typ in (int, float, bool, str)]}

or better to leave the existing pattern as is, just including a boolean example? Something like this:

> converters = {'col1': [ascii.convert_numpy(np.uint)],
  ...      'col2': [ascii.convert_numpy(np.float32)],
  ...       'col3': [ascii.convert_numpy(bool)]}


 I think, for the documentation, I prefer the existing pattern where each column is individually specified as is. In the next paragraph, we explicitly go over the usage of `fnmatch` for matching glob patterns but I'm happy to defer to your judgement here.

**Comment by taldcroft** [comment]
@pjs902 - hopefully you haven't started in on this, because this morning I got an idea to simplify the converter input to not require this whole `ascii.convert_numpy()` wrapper. So I'm just going to fold in this bool not str into my doc updates now.

**Comment by pjs902** [comment]
@taldcroft No worries! Sounds like a much nicer solution!
