### ISSUE TITLE
astropy 5.0 not working with pyinstaller

### ISSUE THREAD

**Issue by EfremBraun** [astropy/astropy#12837]
See pyinstaller/pyinstaller-hooks-contrib#379.

Per #7052 and #8795, I figure this is something @astrofrog might know something about.

**Comment by pllim** [comment]
Do you mean 5.0.1 or the dev version?

**Comment by EfremBraun** [comment]
5.0.1. I'll fix the title to reflect that.

**Comment by EfremBraun** [comment]
A solution was suggested on https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/379. Should I leave that issue open and close this issue?

**Comment by pllim** [comment]
I'll have to defer to @astrofrog . I thought we fixed the pyinstaller stuff before 5.0.1 release but apparently not!

**Comment by bwoodsend** [comment]
[This line](https://github.com/astropy/astropy/blob/314dbe860be368465f302f4bc272f73241794dff/.pyinstaller/run_astropy_tests.py#L5) will mask the issue in your testing. PyInstaller can automatically detect usages of `importlib.metadata` functions if they are used on plain literals but can't track anything more complicated than that so it will fail to collect NumPy's metadata normally because it can't follow through those usages of `minversion(np, ...)` but it will collect the metadata for that test because it says `metadata.version("numpy")` where even PyInstaller can spot it.

**Comment by EfremBraun** [comment]
> [This line](https://github.com/astropy/astropy/blob/314dbe860be368465f302f4bc272f73241794dff/.pyinstaller/run_astropy_tests.py#L5) will mask the issue in your testing. PyInstaller can automatically detect usages of `importlib.metadata` functions if they are used on plain literals but can't track anything more complicated than that so it will fail to collect NumPy's metadata normally because it can't follow through those usages of `minversion(np, ...)` but it will collect the metadata for that test because it says `metadata.version("numpy")` where even PyInstaller can spot it.

Perhaps you're referring to a different issue? This issue is not about any of the test failure issues that are mentioned in #12820 or #12688.

**Comment by bwoodsend** [comment]
No I mean the opposite of test failures. Your `.pyinstaller/run_astropy_tests.py` test will pass despite PyInstaller + astropy being broken because of that line.

**Comment by pllim** [comment]
`pyinstaller` is also broken since `pytest` 7 came out, so if you know how to fix any of these errors, PRs are welcome. In the meantime, we ask for your patience as we wait for @astrofrog to be available. Thanks!

**Comment by pllim** [comment]
I don't see any explicit install of `pyinstaller-hooks-contrib` but I did restart a job over at #12823 in hope that it automatically picks up your new release. This is what I see now: https://github.com/astropy/astropy/runs/5148885367?check_suite_focus=true

```
pytest.PytestAssertRewriteWarning: Module already imported so cannot be rewritten: pytest_mpl
```

**Comment by pllim** [comment]
So, uh, is the suggestion at https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/379#issuecomment-1034140729 purely an upstream fix? Or is that something we also have to put in our CI here?

**Comment by EfremBraun** [comment]
I'm afraid I don't know the inner workings of pyinstaller or astropy well enough to confidently answer that question. But I tested the fix, and adding the lines `datas += copy_metadata('numpy')` and `datas += copy_metadata('astropy')` to the astropy hook at https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-astropy.py does indeed get my program to work. So based on that, I don't think anything would need to be done to the astropy package itself.

**Comment by pllim** [comment]
@EfremBraun , nice! Are you going to submit that as upstream patch then? I'll mark this as pending upstream fix. 🙇‍♀️

**Comment by EfremBraun** [comment]
The issue is I really have no idea why astropy needs those lines to work. It's all magic to me. I'd really prefer someone with an idea of why those lines are actually needed to make the patch...

**Comment by EfremBraun** [comment]
Just put in the pull request (https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/381) after https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/379#issuecomment-1041233974 helped me understand the issue.

**Comment by EfremBraun** [comment]
Should we mark this as closed with the merge of https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/381?

**Comment by pllim** [comment]
I believe the CI job here is fixed too. Thanks again for all the help, @EfremBraun and @bwoodsend !
