### ISSUE TITLE
io.fits cannot properly handle empty variable-length arrays in some scenarios

### ISSUE THREAD

**Issue by kYwzor** [astropy/astropy#12881]
### Description
In some scenarios, `io.fits` may be unable to properly handle a variable-length array (VLA) column if it only contains empty arrays. No warnings or errors are raised while writing such a table to a file, yet `io.fits` may be unable to properly read the resulting file.

### Expected behavior
Being able to have a VLA column with empty arrays, writing that column to a file and then successfully reading it back (round-trip).

### Actual behavior
`io.fits` raises a `ValueError` when trying to read the VLA column.

### Steps to Reproduce

In this specific scenario:
```python
columns = [
    fits.Column(name='integer', format='J', array=(1, 2)),
    fits.Column(name='empty', format='QD', array=([], [])),
]

fits.BinTableHDU.from_columns(columns).writeto('bug.fits', overwrite=True)

with fits.open('bug.fits') as hdus:
    print(hdus[1].columns.formats)
    print(hdus[1].data['integer'])
    print(hdus[1].data['empty'])
```

we get this output:
```python
['J', 'QD(0)']
[1 2]
Traceback (most recent call last):
  (...)
  File "[path]/bugtest.py", line 14, in <module>
    print(hdus[1].data['empty'])
  File "[path]\venv\lib\site-packages\astropy\io\fits\fitsrec.py", line 504, in __getitem__
    return self.field(key)
  File "[path]\venv\lib\site-packages\astropy\io\fits\fitsrec.py", line 719, in field
    converted = self._convert_p(column, field, recformat)
  File "[path]\venv\lib\site-packages\astropy\io\fits\fitsrec.py", line 820, in _convert_p
    dummy[idx] = raw_data[offset:offset + arr_len].view(dt)
  File "[path]\venv\lib\site-packages\numpy\core\records.py", line 484, in __setattr__
    ret = object.__setattr__(self, attr, val)
ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype
```

Surprisingly, if we remove the `integer` column or simply change its format to `'D'`, this bug will not occur, for example:
```python
columns = [
    fits.Column(name='integer', format='D', array=(1, 2)),
    fits.Column(name='empty', format='QD', array=([], [])),
]

fits.BinTableHDU.from_columns(columns).writeto('bug.fits', overwrite=True)

with fits.open('bug.fits') as hdus:
    print(hdus[1].columns.formats)
    print(hdus[1].data['integer'])
    print(hdus[1].data['empty'])
```
correctly outputs:
```python
['D', 'QD(0)']
[1. 2.]
[array([], dtype=float64) array([], dtype=float64)]
```

And even more surprisingly, if we instead add another column with a format `'J'`, this somehow also solves the issue:

```python
columns = [
    fits.Column(name='integer', format='J', array=(1, 2)),
    fits.Column(name='empty', format='QD', array=([], [])),
    fits.Column(name='integer2', format='J', array=(3, 4)),
]

fits.BinTableHDU.from_columns(columns).writeto('bug.fits', overwrite=True)

with fits.open('bug.fits') as hdus:
    print(hdus[1].columns.formats)
    print(hdus[1].data['integer'])
    print(hdus[1].data['empty'])
    print(hdus[1].data['integer2'])
```
correctly outputs:
```python
['J', 'QD(0)', 'J']
[1 2]
[array([], dtype=float64) array([], dtype=float64)]
[3 4]
```
This bug will also not occur if the VLA column isn't completely empty.

I am currently not sure if this bug originates from incorrectly writing the file or just incorrectly reading it (I can't test this right now because I don't have access to an alternative tool for reading FITS). I also have no idea why different columns can impact this very specific scenario of VLA columns... this is extremely weird!

### System Details
Windows-10-10.0.19044-SP0
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Numpy 1.22.2
pyerfa 2.0.0.1
astropy 5.0.1
Scipy 1.7.1

**Comment by kYwzor** [comment]
Short update, I ran the resulting file through `fitsverify `and it got no errors or warnings. I also tried `fv` and it managed to correctly interpret the table. It seems to me that the file is being written correctly, but somehow `io.fits` can't properly read it. I've been trying to figure out why, but I'm not very familiar with the source code, so help is definitely welcome.

**Comment by saimn** [comment]
> I can't test this right now because I don't have access to an alternative tool for reading FITS

Thanks for the detailed issues you reported about VLA, which are clearly not fully supported by Astropy. It would be very interesting to see what it gives with fitsio (https://github.com/esheldon/fitsio, a wrapper for cfitsio).

**Comment by kYwzor** [comment]
Good call on fitsio. Using the `bug.fits` file that I created in the first scenario, and using this code:
```python
f = fitsio.FITS('bug.fits')
print(f[1])
print(f[1].read())
```
we get:

```python
  file: bug.fits
  extension: 1
  type: BINARY_TBL
  rows: 2
  column info:
    integer             i4  
    empty               f8  varray[0]
[(1, array([], dtype=float64)) (2, array([], dtype=float64))]
[path]/venv/lib/python3.10/site-packages/fitsio/hdu/table.py:1280: FITSRuntimeWarning: Column 'empty': Max size is zero: 'QD(0)'. Column '%s': Max size is zero: '%s'. %s
  warnings.warn(mess, FITSRuntimeWarning)
```

So while we do get a warning, it has no problem reading it correctly (while Astropy completely crashes). Interestingly, we get this same warning when trying to read other files that Astropy reads without any issue (for example, the file created in second scenario, which has the 'D' format).
