### ISSUE TITLE
Changes to `ssl` and `concurrent.futures` imports to allow `astropy` to run in `pyodide`

### ISSUE THREAD

**Issue by jobovy** [astropy/astropy#12904]
### Description

[`pyodide`](https://github.com/pyodide/pyodide) is a Python distribution that runs in the browser and thus allows installation-free use of Python and many scientific/data-science packages. `Pyodide` is the base kernel of other projects such as [`jupyterlite`](https://github.com/jupyterlite/jupyterlite) that provide JupyterLab and similar environments that fully run in the browser. Try it out [here](https://pyodide.org/en/stable/console.html)!

`astropy` is packaged as part of `pyodide`, but currently doesn't fully work because some standard-library imports fail in `pyodide`. In particular `import ssl` in

https://github.com/astropy/astropy/blob/41f023995fc2b533deeac84f6fa818a5df04c26e/astropy/utils/data.py#L15

and `import concurrent.futures` in

https://github.com/astropy/astropy/blob/41f023995fc2b533deeac84f6fa818a5df04c26e/astropy/utils/console.py#L17

causes errors in `pyodide` (basically because Python's `_ssl` library and multiprocessing are not supported in the browser currently). Because these are difficult things to fix, I don't think they will be fixed soon in `pyodide`. Because these utility modules are imported elsewhere, they make it that one cannot use things like `astropy.coordinates` in `pyodide`. For example, type `import astropy.coordinates` in the [`pyodide` REPL](https://pyodide.org/en/stable/console.html)!

I just submitted a PR (now merged) to `pyodide` patching the current release of `astropy` to move the offending imports into the few functions that use them. With those patches, all `astropy` sub-modules can be imported and at least  basic`astropy.coordinates` use works (I haven't done a comprehensive test, but everything I've tried that I think should work, works now). This should soon (maybe an hour from now?) be available in the latest version, which you can run [here](https://pyodide.org/en/latest/console.html)!

To avoid having to do these patches for each new `astropy` release, it would be good to fix the issue here. I'm happy to submit a PR, but thought it would be useful to discuss the preferred way before doing so. There are a few options:
1. Move the imports into the functions that use them, like in the patch I made in `pyodide`. There are only two functions in `astropy.utils.data` that use `ssl` and only a single function in `astropy.utils.console` that uses `concurrent.futures`, so it's a pretty simple fix. And when these functions are run on `pyodide`, the error is obvious. The disadvantage is that the imports then become more opaque, because they are no longer at the top of the file (but one could put a comment there pointing this out to avoid future confusion). 
2. Feature test whether these libraries are available and only raise an error in the functions that use them if not. This keeps the top-of-file import, but means that a bit of code has to be included that only really applies to `pyodide` (because standard-library packages should always be available when using a regular Python distribution).
3. Detect whether one is running in `pyodide` and decide on behavior based on that (`import sys; 'pyodide' in sys.modules` detects `pyodide`). This would cleanly show why the imports are done in the way they are done, but requires special code for `pyodide`. Could also check whether the platform is `platform.system() == 'Emscripten'` to detect whether one is running in the browser more generally.

I think 1. is the easiest fix to make, but 2. is a decent alternative. I wouldn't want to do 3., because it's plausible that there would be non-`pyodide`or non-Emscripten-based Python distributions in the browser.

**Comment by pllim** [comment]
@olebole , since you do a lot of patches yourself for Debian, do you have any advice on the best solution for everyone involved? Thanks!

**Comment by olebole** [comment]
In Debian, we have the patches in a [separate subdirectory](https://salsa.debian.org/debian-astro-team/astropy/-/tree/master/debian/patches), which are automatically applied in the build process. These patches are converted from/to a temporary git branch, which is rebased whenever a new upstream release is integrated. That is OK for me, since rebases are relatively rare, and often the rebase can be done automatically. However, this is sometimes one of the time consuming steps for me, and this is probably not feasable here (I also always report my changes back, to keep the number of local patches low).

I would think the best way would be if these imports could be optional, so either option 1 or 2.

**Comment by jobovy** [comment]
> Another option could be that pyiodide provides stubs for the stdlib modules they don't support ([pyodide/pyodide#529](https://github.com/pyodide/pyodide/issues/529)), so at least imports would work and we don't need to add workarounds in every library using ssl/concurrent.

I did ask for the `_ssl` stub in https://github.com/pyodide/pyodide/issues/529 because of `astropy`, but I think the `pyodide` devs prefer to not have stubs, because it leads to problems, and prefer patches to be applied upstream (e.g., https://github.com/pyodide/pyodide/pull/2094).

To me, this seems like a small enough patch to `astropy` that doesn't affect how it runs in Python but vastly increases how much of `astropy` you can just run in your browser.

**Comment by adrn** [comment]
I personally think option 1 would be fine - thanks @jobovy for raising this issue!

**Comment by Cadair** [comment]
For the use of `ssl` in utils.py it actually looks like [this function](https://github.com/astropy/astropy/blob/41f023995fc2b533deeac84f6fa818a5df04c26e/astropy/utils/data.py#L1086) could be refactored so that if a ssl context can't be built (because ssl isn't importable) then it falls back to http. That might make it less likely to error?

**Comment by Cadair** [comment]
(I am also generally pro option 1, but we can probably do more to make the code work if we wanted to)
