### ISSUE TITLE
Convert CCDData to ImageHDU

### ISSUE THREAD

**Issue by kYwzor** [astropy/astropy#12933]
### Description
As far as I can tell, currently there's no way to directly convert a `CCDData` object to an `ImageHDU` object. If we write it to a file using `CCDData.write()` it will always create a file where the first HDU is a `PrimaryHDU` that contains the `CCDData.data`, followed by optionally some `ImageHDU`s that contain mask or uncertainty. If we instead use `CCDData.to_hdu()`, it will return an `HDUList` equivalent to the file it writes with `CCDData.write()`, that is, the `CCDData.data` is stored in the first element of the `HDUList`, which is always a `PrimaryHDU`.

This is somewhat unexpected given that you can already do it the other way around (that is, convert a `ImageHDU` object to a `CCDData` object):

```python
fits.HDUList([
    fits.PrimaryHDU(),
    fits.ImageHDU(data=np.ones((2, 2))),
    fits.ImageHDU(data=np.ones((5, 5)), header=fits.Header({'BUNIT': 'm'})),
]).writeto('test.fits')  # create example file

ccd_image = CCDData.read('test.fits', hdu=2)  # you can successfully read the 5x5 ImageHDU
```
The problem is that if we then want to use this `ccd_image` as an extension to another FITS file, there's no obvious way to get an `ImageHDU` which would allow us to do that.  As far as I can tell, there's also no trivial way to convert a `PrimaryHDU` to a `ImageHDU`. We could manually create a new `ImageHDU` by copying the data from the `PrimaryHDU`, as well as its relevant cards and so on... but this seems unnecessarily complicated.

I propose the following interfaces:

```python
# Option A: add a new parameter to CCDData.to_hdu() for this functionality
hdus = ccd_image.to_hdu(as_image_hdu=True)  # This returns a HDUList where the first element is an ImageHDU instead of a PrimaryHDU

# Option B: create a new convenience function
hdu = fits.ccddata_to_image_hdu(ccd_image) # This returns a single ImageHDU

# Option C: allowing the user to append the image to an existing FITS file
ccd_image.write('test.fits', append=True) # appends original ImageHDU to existing file
```

### Additional context
This seems somewhat similar to the situation with `Table` and `BinTableHDU`. In that case, we can also specify an `hdu` parameter when reading:

```python
fits.BinTableHDU.from_columns([
    fits.Column(name='test', format='J', array=(1, 2))
]).writeto('table.fits')  # creates a new file with a PrimaryHDU followed by this BinTableHDU
t = Table.read('table.fits', hdu=1) # reads the BinTableHDU as a Table
```

From here we can use:

```python
t.write('new_table.fits')  #  creates a new file with a PrimaryHDU followed by the original BinTableHDU
t.write('existing_table.fits', append=True)  # appends original BinTableHDU to existing file
hdu = fits.table_to_hdu(t)  # returns original BinTableHDU
```

**Comment by pllim** [comment]
Maybe it just needs some tune up to write the HDU format that you want instead of a whole new interface.

**Comment by kYwzor** [comment]
Yes, I know that `ccd_data.to_hdu()` already exists (I mentioned it in the first paragraph). My problem with it is that it returns the data as an `HDUList` with a `PrimaryHDU`, not as an `ImageHDU`. This is why I proposed adding an optional parameter to it (option A). Option B and C are basically inspired on the existing interfaces for converting Tables back to `BinTableHDU`s, which also seem good options to me.

**Comment by pllim** [comment]
Yes, I replied before coffee kicked in, sorry. 😅 

My vote is Option A but we should wait to hear from @mwcraig .

**Comment by saimn** [comment]
Option A sounds very useful to me too.

**Comment by mwcraig** [comment]
I agree that Option A sounds good -- thanks for the detailed report and thoughtful suggestions, @kYwzor. Are you interested in writing a pull request to implement this? I would have some time this week to help you out if you are interested.

If not, I should be able to open a PR myself this week.

**Comment by kYwzor** [comment]
I've never contributed to a big package like this, but I can give it a try.

There seems to be consensus for `ccd_data.to_hdu(as_image_hdu=True)`, but I'm not sure that we're all in agreement regarding what exactly this should return. I see essentially three options:

1. Return an `HDUList` where the first element is an empty `PrimaryHDU`, followed by an `ImageHDU` which contains data/headers coming from the `CCDData` object, possibly followed by `ImageHDU`s containing mask and/or uncertainty (if they are present in the `CCDData` object).
2. Same as option 1, but without the `PrimaryHDU` (the first element is an `ImageHDU`).
3. Return just an `ImageHDU` (not an `HDUList`), even if mask or uncertainty exist.

Option 1 is probably more consistent with the usual behavior when returning `HDUList`s (I think when Astropy builds an `HDUList` for the user, it's usually returned in a state that can be directly written to a file). The argument for option 2 is that if you're using `as_image_hdu` you probably don't intend on directly writing the returning `HDUList` to a file (otherwise you'd likely just use the default parameters), so adding a PrimaryHDU may be unnecessary bloat. Although I'm not a fan of option 3, it might be what someone expects from a parameter named "as_image_hdu"... but it would be pretty weird to completely drop mask/uncertainty and to return a different type of obect, so maybe we should have a better name for this parameter.

I think option 1 is probably the best option because if you don't want the PrimaryHDU (option 2) you can easily do that with `hdus.pop(0)` and if you only want the ImageHDU (option 3) you can get it via `hdus[1]`, so it seems like it should fit everyone's needs.

**Comment by pllim** [comment]
From an "outsider" perspective (in terms of `CCDData` usage), I would prefer a solution that is the closest to what `.write()` would have done, but returns the object instead of writing it to a file. You can name the keyword whatever that makes sense to you in that regard. I think that behavior is the least surprising one.

Of course, I don't use it a lot, so I can be overruled.

**Comment by kYwzor** [comment]
Thanks for the help @mwcraig! I've created PR #12962 which hopefully follows the guidelines.
