### ISSUE TITLE
[5.0.2] test_sip_hst fails: additional parameter A_2_2

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#12949]
### Description

When trying to package 5.0.2 for Debian, I observed a failure for  `test_sip_hst()` in that `str(sip)` returns one additional parameter.

### Actual behavior
```
_____________________________________________ test_sip_hst ______________________________________________

    def test_sip_hst():
        """Test SIP against astropy.wcs"""
[…]
        # Test representations
        assert repr(sip) ==\
            "<SIP([<Shift(offset=-2048.)>, <Shift(offset=-1024.)>, " +\
            "<_SIP1D(4, 'A', A_2_0=0.00000855, A_3_0=-0., A_4_0=0., A_0_2=0.00000217, " +\
            "A_0_3=0., A_0_4=0., A_1_1=-0.0000052, A_1_2=-0., A_1_3=-0., " +\
            "A_2_1=-0., A_2_2=0., A_3_1=0.)>, " +\
            "<_SIP1D(4, 'B', B_2_0=-0.00000175, B_3_0=0., B_4_0=-0., B_0_2=-0.00000722, " +\
            "B_0_3=-0., B_0_4=-0., B_1_1=0.00000618, B_1_2=-0., B_1_3=0., " +\
            "B_2_1=-0., B_2_2=-0., B_3_1=-0.)>])>"
>       assert str(sip) ==\
[…]
E       AssertionError: assert 'Model: SIP\n...5487476e-15\n' == 'Model: SIP\n...5487476e-15\n'
E         Skipping 487 identical leading characters in diff, use -v to show
E         -         A_3_1        
E         +         A_2_2                 A_3_1        
E         -         --------------------- ---------------------- ... ---------------------
E         +         --------------------- ---------------------- ... --------------------- ---------------------
E         ?                                                         ++++++++++++++++++++++
E         -         8.551277582556502e-06 -4.730444829222791e-10 ... 1.971022971660309e-15...
E         
E         ...Full output truncated (20 lines hidden), use '-vv' to show

astropy/modeling/tests/test_polynomial.py:356: AssertionError
```
I don't know whether this is similar to #12948 connected to a different line width or a real difference. Since the `assert repr(sip)` passes, this is probably really a problem with the representation in `__str__`.

### System Details

Linux-5.16.0-3-amd64-x86_64-with-glibc2.33
Python 3.9.10 (main, Feb 22 2022, 13:54:07) (also with Python 3.10)
Numpy 1.21.5
pyerfa 2.0.0.1
Scipy 1.7.3
Matplotlib 3.5.1

**Comment by pllim** [comment]
@WilliamJamieson ?

**Comment by WilliamJamieson** [comment]
I cannot replicate this error locally with the same set of packages listed (though I am running on a mac so the system detail is different). I don't think this is a real difference as the `repr(sip)` passes (as you mentioned before).

Note that basic diffing between the `v5.0.1` and `v5.0.2` tags (on the files which should effect this) indicate there are no changes in any modules which might be effecting the test (that I can think of at least).

@olebole, since I cannot exactly replicate your system can you run the above test using the `v5.0.1` tag and report the results?

**Comment by olebole** [comment]
I see the same issue on 5.0.1.

The problem is really the width of the terminal: when I start it in a 80x24 terminal, it works fine while on a bigger one this (and #12948) fail (GNOME-Terminal 3.34.90).

**Comment by WilliamJamieson** [comment]
Hmm what does python return in each case for this `import os; print(os.get_terminal_size())`? We may have to `xfail` or `skip` this (and the other test) in this case.

Its strange that it is having issues with string representation.

**Comment by WilliamJamieson** [comment]
I just reproduced this on MacOs with the `-s` flag. I.e
```
pytest astropy/modeling/tests/test_polynomial.py::test_sip_hst -s
```
Reproduced the bug locally.

**Comment by WilliamJamieson** [comment]
@olebole try #12953 and see if that fixes your bugs. Please leave a review reflecting your findings.
