### ISSUE TITLE
TST: time/tests/test_precision.py failed in pyinstaller (computed error is different depending on the order of the arguments)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#12955]
First failing log (2022-03-13): https://github.com/astropy/astropy/runs/5525474634

Last successful log (2022-03-12): https://github.com/astropy/astropy/runs/5519547613

Looks like this test was added in #10373 . Any idea how to fix, @Zac-HD or @mhvk ? 🙏 

https://github.com/astropy/astropy/blob/c7b0e928e82dc7a4e099124d5223700e5bb4cfe2/astropy/time/tests/test_precision.py#L313-L315

```
____________________________ test_two_sum_symmetric ____________________________

    @given(floats(), floats())
>   def test_two_sum_symmetric(f1, f2):

astropy_tests/time/tests/test_precision.py:314: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

f1 = -3.089785075544792e+307, f2 = 1.7976931348623157e+308

    @given(floats(), floats())
    def test_two_sum_symmetric(f1, f2):
>       np.testing.assert_equal(two_sum(f1, f2), two_sum(f2, f1))
E       AssertionError: 
E       Items are not equal:
E       item=1
E       
E        ACTUAL: nan
E        DESIRED: -9.9792015476736e+291

astropy_tests/time/tests/test_precision.py:315: AssertionError
----------------------------- Captured stdout call -----------------------------
Falsifying example: test_two_sum_symmetric(
    f1=-3.089785075544792e+307, f2=1.7976931348623157e+308,
)
```

**Comment by pllim** [comment]
At a glance, I don't see any version change in numpy, hypothesis, etc. Is this transient? 🤔

**Comment by pllim** [comment]
OK passed now. Sorry for the noise.

**Comment by Zac-HD** [comment]
Looks to me like a genuine failing example, where the computed error is different depending on the order of the arguments:

```python
@example(f1=-3.089785075544792e307, f2=1.7976931348623157e308)
@given(st.floats(), st.floats())
def test_two_sum_symmetric(f1, f2):
    f1_f2 = two_sum(f1, f2)
    f2_f1 = two_sum(f2, f1)
    note(f"{f1_f2=}")
    note(f"{f2_f1=}")
    numpy.testing.assert_equal(f1_f2, f2_f1)
```
```python-traceback
---------------------------------------------- Hypothesis ----------------------------------------------- 
Falsifying explicit example: test_two_sum_symmetric(
    f1=-3.089785075544792e+307, f2=1.7976931348623157e+308,
)
f1_f2=(1.4887146273078366e+308, nan)
f2_f1=(1.4887146273078366e+308, -9.9792015476736e+291)
```

This might have been latent for a while, since it looks like it only fails for args *very* close to the maximum finite float64, but there you are.  You might also take this as an argument in favor of persisting the database between CI runs, to avoid losing rare failures once you find them.

**Comment by pllim** [comment]
Thanks for the clarification, @Zac-HD ! I re-opened the issue and marked it as a real bug.

**Comment by pllim** [comment]
So, it boils down to this:

```python
>>> a = -3.089785075544792e307
>>> b = 1.7976931348623157e308
>>> x = a + b  # 1.4887146273078366e+308
>>> x - a
inf
```

When you flip the order in the test, it basically does this but does not get `inf`:

```python
>>> x - b
-3.089785075544791e+307
```

Looks like an edge case but not sure how to fix.

**Comment by Zac-HD** [comment]
I think there are two reasonable ways to fix this:

1. check for and handle overflow inside the code under test
2. pass `floats(min_value=1e100, max_value=1e100)` (for example), so that we don't try to test with overflow.
