### ISSUE TITLE
Units: automatic conversion to the closest human readable unit

### ISSUE THREAD

**Issue by facero** [astropy/astropy#12951]
### Description

Hi,

I’m a contributor of the astropy-affiliated package [gammapy](docs.gammapy.org), an analysis package for gamma-ray astronomy.
The gamma-ray energy range is open-ended and we use energy units ranging from MeV to PeV energies spanning 9 decades !

In gammapy we use astropy units but can sometime end up with values as E=1.5e6 MeV which is hard to understand from a user point of view. E=1.5 TeV is more readable.

In this [gammapy PR 1](https://github.com/gammapy/gammapy/pull/3752), I proposed a helper function to transform :
`E = [1.54e2*u.GeV, 4300*u.keV, 300.6e12*u.eV]` (astropy unit list)
=> `E=[‘154 GeV’, ‘4.30 MeV’, ‘301 TeV’]` (string representation for label, legends, titles, etc)

Right now, I’m just doing an if/elif test to find the most appropriate unit.
See the full code description [here](https://github.com/gammapy/gammapy/blob/c208e1bd5e5c4144bc3c13bde3892e0cab6eab05/gammapy/utils/units.py#L69).

Is there an easy way to do this with astropy ?
Same issue exists with distance units (nm,cm,m, lyr, Mpc, etc) or time.
Would you see a more astropy/pythonic way to do this ?

Thanks for any suggestions you might have,

**Comment by adonath** [comment]
This could be maybe natively supported by Astropy as a special quantity format option like:

```python3
from astropy import units as u

quantity = u.Quantity("1e5 MeV")

print(f"{quantity:order_to_prefix}")
```
This would be very convenient for users I think...

**Comment by facero** [comment]
This could indeed be very useful for many units (length, time, frequency, energy, mass, etc).
Can this be recorded somewhere as a possible desirable feature ? 
To see if there is some interest and how difficult it is to implement.
(I'm not familiar with how feature request are handled in astropy).

**Comment by mhvk** [comment]
There is an old similar issue, #6913, and an attempt at a solution in #7033. It might be worth trying to revive that. Since it may be best to keep discussion in one place, I'll comment in #6913, and close this new issue.
