### ISSUE TITLE
Distutils' commandline flags are not respected

### ISSUE THREAD

**Issue by Xarthisius** [astropy/astropy#1295]
PR #992 broke the way Gentoo installs multiple version of python packages. We pass `--build-base`, `--build-platlib`, `--build-purelib` etc to control where things are installed but now they're overridden in `AstropyBuildPy.finalize_options`.

**Comment by bsipocz** [comment]
@astrofrog - close or move to the helpers?

**Comment by astrofrog** [comment]
We no longer have AstropyBuildPy in astropy-helpers so this should hopefully work as expected now.
