### ISSUE TITLE
Adding a new CGS unit: Maxwell

### ISSUE THREAD

**Issue by nabobalis** [astropy/astropy#12969]
### Description

Recently, I was trying to parse a unit that's quite commonly used in solar physics: `Mx` (a Maxwell) which is a magnetic flux in CGS.

I was unable to find any discussions or issues about this from a quick search, so would anyone object to me adding it in a PR?

**Comment by mhvk** [comment]
I think it would be OK to add this to `astropy/units/cgs.py` (with Gauss). One potential issue is that it is defined only in the CGS EMU system; on the other hand, that is true for Gauss too.
