### ISSUE TITLE
Feature request: ds9 region writer

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#1297]
For tables with astronomical coordinates, any means to write out as a ds9 regions file would be very useful.  This is the kind of thing I'm likely to work on after proposal deadlines whoosh by, but I wanted an official request in.

It may be necessary to parse a table into a set of Regions as may be defined in photutils at some point, then write those regions out as a ds9 regions file.

Important capabilities:
- allow for different region shapes
- choose which table field to put into the `# text={}` box
- color, font specification

**Comment by keflavich** [comment]
There's an awful example of what I had to do to write a simple set of x,y,c to file using pyregion [here](http://nbviewer.ipython.org/gist/keflavich/19175791176e8d1fb204)

**Comment by saimn** [comment]
I ended up making the same ugly script as @keflavich to convert a table to a region file : https://gist.github.com/saimn/58e12de6c1fcb0318a7a (thanks for the example Adam !)
But this is really not intuitive and not flexible (pyregion doesn't really allow to specify different parameters for each region, you have to write manually the params in the comment string). So at the end there is no real gain to use pyregion for this, compared to writing a simple function that takes a list of coordinates/shape/colors/comments and write it to a file.

Even if it is difficult to make something that handle all cases and features of region files, I think it could be useful to have an utility to write easily a simple region file with common features (as said above: coordinates, shape, color, width, text).

**Comment by pllim** [comment]
You mean, something like this?
```python
from astropy.io import ascii
ascii.write(mytable, format='pyregion')
```

**Comment by saimn** [comment]
I was thinking about an independent function, but it can also be directly an ascii writer. One question if how to handle the varying number of coordinates arguments for different shapes. It is easy with a list of list but can be problematic with a table.

**Comment by taldcroft** [comment]
>  One question if how to handle the varying number of coordinates arguments for different shapes. It is easy with a list of list but can be problematic with a table.

@saimn - remember that a Table column can have object type, at which point you can stuff anything there that you want.

**Comment by bsipocz** [comment]
This is something being worked on as part of https://github.com/astropy/regions, so while it may end up in core in the future, closing the issue here.
