### ISSUE TITLE
Can Table masking be turned off?

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#12981]
### Description

As of Astropy 5, when `astropy.table.Table.read()` encounters values such as `NaN`, it automatically creates a `MaskedColumn` and the whole table becomes a `MaskedTable`.  While this might be useful for individual end-users, it is very inconvenient for intermediate data in pipelines.

Here's the scenario: data are being passed via files and `Table.read()`.  A downstream function needs to replace `NaN` with valid values.  Previously those values could be easily identified (*e.g.* `np.isnan()` and replaced.  However, now additional work is need to look "underneath" the mask, extracting the actual values, replacing them, and then possibly creating a new, unmasked column, or even an entirely new table.

Ideally, a keyword like `Table.read(filename, ..., mask=False)` would disable this behavior, for people who don't need this masking.

**Comment by saimn** [comment]
It looks like I opened a PR for this some time ago (I had almost forgotten) : #12544
