### ISSUE TITLE
Spherical_offset_to dAlt and dAz different depending on from to and to from

### ISSUE THREAD

**Issue by tosaric** [astropy/astropy#13002]
### Description
Probably this is not a bug, but my lack of understanding of spherical_offset_to method, but I hope I can find help and explanation here. I have two points in the sky that have fixed offset in Alt Az angle.

### Expected behavior

When calculating altitude and azimuth angle between these two points during some time range, I am expecting to get the same altitude and azimuth angle irrelevant of if I am using source1.spherical_offset_to(source2) or source2.spherical_offset_to(source1)

### Actual behavior

I am actually getting entirely different results, which best can be seen in the plots(link below).
What am I missing?
Perhaps it has something with Positional_angle?

### Steps to Reproduce

```
from astropy.time import TimeDelta
from astropy.time import Time
from astropy.coordinates import SkyCoord, SkyOffsetFrame, ICRS
from astropy import units as u
import pandas_bokeh
from bokeh.plotting import figure, output_file, save #show
from bokeh.layouts import column, gridplot
from bokeh.io import show
from astropy.coordinates import AltAz
from astropy.coordinates import EarthLocation
ORM = EarthLocation.of_site("Roque de los Muchachos")
source1 = SkyCoord.from_name('Mothallah')
source2 = SkyCoord.from_name("Lambda Arietis")
time = Time('2020-11-22 01:25', scale='utc')
step = 10 # in seconds
source1_alt = []
source1_az = []
source2_alt = []
source2_az = []
ttime = []
for i in range(360): # one hour
    time = time + TimeDelta(step, format='sec')
    ttime.append(time)
    
    aa = AltAz(location=ORM, obstime=time)
    source1_aa = source1.transform_to(aa)
    source2_offset_aa = source1_aa.directional_offset_by(position_angle=60*u.deg, separation=5*u.deg)
    source1_alt.append(source1_aa.alt.deg)
    source1_az.append(source1_aa.az.deg)
    source2_alt.append(source2_offset_aa.alt.deg)
    source2_az.append(source2_offset_aa.az.deg)
    
source1_aa = SkyCoord(alt=source1_alt, az=source1_az, obstime=ttime, frame="altaz", unit="deg")
source2_aa = SkyCoord(alt=source2_alt, az=source2_az, obstime=ttime, frame="altaz", unit="deg")
```

Plots can be seen here :https://ibb.co/zfJyrQ5
You can also reproduce plots:
```
TOOLS = "crosshair,pan,wheel_zoom,xwheel_zoom,ywheel_zoom,box_zoom,undo,redo,reset,tap,save"
dAz_from1to2, dAlt_from1to2= source1_aa.spherical_offsets_to(source2_aa)
dAz_from2to1, dAlt_from2to1 = source2_aa.spherical_offsets_to(source1_aa)

p1 = figure(title="dAlt vs Alt from point1 to point2",tools=TOOLS, output_backend="webgl")
p1.scatter(source1_aa.alt.deg, dAlt_from1to2, color="blue", marker="star", size=7, legend_label="dAlt")
p1.xaxis.axis_label = "Altitude[deg]"
p1.yaxis.axis_label = "dAlt[deg]"
p2 = figure(title="dAz vs Alt from point1 to point2",tools=TOOLS, output_backend="webgl")
p2.scatter(source1_aa.alt.deg,  dAz_from1to2, color="blue", marker="star", size=7, legend_label="dAz")
p2.xaxis.axis_label = "Altitude[deg]"
p2.yaxis.axis_label = "dAz[deg]"

p3 = figure(title="dAlt vs Alt from point2 to point1",tools=TOOLS, output_backend="webgl")
p3.scatter(source1_aa.alt.deg, dAlt_from2to1, color="blue", marker="star", size=7, legend_label="dAlt")
p3.xaxis.axis_label = "Altitude[deg]"
p3.yaxis.axis_label = "dAlt[deg]"
p4 = figure(title="dAz vs Alt from point2 to point1",tools=TOOLS, output_backend="webgl")
p4.scatter(source1_aa.alt.deg,  dAz_from2to1, color="blue", marker="star", size=7, legend_label="dAz")
p4.xaxis.axis_label = "Altitude[deg]"
p4.yaxis.axis_label = "dAz[deg]"
pandas_bokeh.output_notebook()
pandas_bokeh.show(gridplot([[p1, p2], [p3, p4]], width=400, height=350))
```

**Comment by ayshih** [comment]
It sounds like you are expecting `spherical_offsets_to()` to calculate something different than it does.  Here's an illustrative example (in `ICRS`, but is analogous):
```python
>>> import astropy.units as u
>>> from astropy.coordinates import SkyCoord
>>> a = SkyCoord(0*u.deg, 45*u.deg)
>>> b = SkyCoord(90*u.deg, 45*u.deg)
>>> a.spherical_offsets_to(b)
(<Angle 54.73561032 deg>, <Angle 30. deg>)
>>> b.spherical_offsets_to(a)
(<Angle -54.73561032 deg>, <Angle 30. deg>)
```
When you call `a.spherical_offsets_to()`, it reports the "RA" and "declination" offsets in a celestial frame that has been modified such that the celestial equator runs through `a`.  That's why the "RA" offset is not 90 degrees, and the "declination" offset is positive.  `b` is in the northern hemisphere of this modified coordinate frame for `a`.

When you call `b.spherical_offsets_to()`, it reports the "RA" and "declination" offsets in a *different* celestial frame, now modified such that the celestial equator runs through `b`.  Note that the "declination" offset is again positive; `a` is in the northern hemisphere of this modified coordinate frame for `b`.

That's why `a.spherical_offsets_to(b)` and `b.spherical_offsets_to(a)` are not equal and opposite; they are "RA" and "declination" offsets reported in different frames.

I haven't tried your example, but perhaps you'd get what you want if you simply subtracted the `az` and `alt` components rather than using `spherical_offsets_to()`.

**Comment by tosaric** [comment]
> ```python
> >>> import astropy.units as u
> >>> from astropy.coordinates import SkyCoord
> >>> a = SkyCoord(0*u.deg, 45*u.deg)
> >>> b = SkyCoord(90*u.deg, 45*u.deg)
> >>> a.spherical_offsets_to(b)
> (<Angle 54.73561032 deg>, <Angle 30. deg>)
> >>> b.spherical_offsets_to(a)
> (<Angle -54.73561032 deg>, <Angle 30. deg>)
> ```

Thanks for your response, your explanation was really helpful.
If we modify your two points by setting declination to zero, then the RA offset would be 90 degrees. It is similar to the Azimuth difference, where the difference should be divided by cos(Altitude), right?

**Comment by tosaric** [comment]
> I haven't tried your example, but perhaps you'd get what you want if you simply subtracted the `az` and `alt` components rather than using `spherical_offsets_to()`.

I did tried with simple subtraction, but I get even more confusing results. I am still puzzled by it, and I can't understand why, for example I get 33 deg difference in declination when point a have dec=30 and point b has dec=40.  

`a = SkyCoord(ra=0, dec=30, unit="deg")`
`b = SkyCoord(ra=90, dec=40, unit="deg")`
`print(a.spherical_offsets_to(b))`
`    (<Angle 67.23952373 deg>, <Angle 33.82584497 deg>)`
`print(b.spherical_offsets_to(a))`
`    (<Angle -69.63942512 deg>, <Angle 22.52101212 deg>)`
`print("dRA:",((b.ra - a.ra)*np.cos(np.deg2rad(a.dec))).value, "dDec:", (b.dec - a.dec).value)`
`    dRA: 77.94228634059948 dDec: 10.0`
`print("dRA:",((a.ra - b.ra)*np.cos(np.deg2rad(b.dec))).value, "dDec:", (a.dec - b.dec).value)`
`    dRA: -68.94399988070803 dDec: -10.0`
