### ISSUE TITLE
numpy.core.multiarray error when trying to run Astropy (v5.0.3 on Raspberry Pi)

### ISSUE THREAD

**Issue by dave290** [astropy/astropy#13003]
SOLVED: https://github.com/astropy/astropy/issues/13003#issuecomment-1127566210

<hr/>

Hello,

I recently installed Astropy version 5.0.3 on my Raspberry Pi.   I am running Raspbian GNU/Linux 11 (bullseye) and have numpy version 1.19.5 installed.  Astropy installed fine, but when I try to run it I get the error below  (attached a screenshot of the full message:)

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
etc.
etc.
numpy.core.multiarray failed to import

Would you have any suggestions of things I may try?  Thanks!

![2022-03-27-155903_1280x1024_scrot](https://user-images.githubusercontent.com/66441959/160300835-28a8c38d-6a4e-40e8-a5cd-0a6a42e435fd.png)

**Comment by pllim** [comment]
The error came from `erfa`. @mhvk , does this ring a bell to you?

**Comment by mhvk** [comment]
@dave290 - I'm not sure what is happening, though clearly some kind of version conflict. The simplest may be to just install pyerfa (and perhaps astropy) from the raspbian archive - those are more guaranteed to be compatible. Alternatively, install a numpy from pypi?

**Comment by dave290** [comment]
Thank you for the reply.  I'm not sure how to go about installing astropy
or pyerfa from the raspbian archive.  Could you provide a link or direct me
to the site?

**Comment by mhvk** [comment]
Isn't available via `apt-get` or `aptitude`? I use regular Debian and it is definitely included, but I'm not sure what is omitted for Raspbian. It may still be possible to add the regular Debian sources to `apt.sources`.  But I fear I'm a bit out of my league here!

**Comment by dave290** [comment]
Okay, I'll look into that.  I'm also fairly new to Linux and doing these
sorts of things.  I'll let you know.  Thanks.

**Comment by dave290** [comment]
Hi Marten,

I'd like to follow up with some more information about my problem
getting Astropy to run on my Raspberry Pi.  I recently started with a fresh
operating system, Raspian 32-bit GNU/Linux Version 11 Bullseye, debian.
This includes python version 3.9.2 and numpy version 1.19.5

From my home directory, I installed Astropy using the command
$ pip install astropy

Although Astropy was installed, I received a warning that "the scripts
fits2bitmap, fitscheck, fitsdiff, etc, etc ... are installed in
'/home/david/.local/bin' which is not on PATH. Consider adding this
directory to PATH, ..."  (I attached a screenshot of the error message, see
the top of the screenshot)

When I try to run Astropy, I still get a long error message (also attached
in the same screenshot) starting with, "Module compiled against API version
0xe but this version of numpy is 0xd" and ending with "ImportError:
numpy.core.multiarray failed to import."

pyerfa and PyYAML both seem to be installed with Astropy, and were not
present in my system before I installed Astropy.

I'm wondering if I need to somehow modify the path, as per the installation
error message.  If so, how would I do this?

Should I have installed Astropy from a directory other than my home
directory in Linux?

Is there any other thing to check?  I have tried using more up-to-date
versions of numpy.  It doesn't appear that I can add Astropy or pyerfa from
the raspbian archive.

Thank you,
Dave

**Comment by dave290** [comment]
Okay, problem just solved!

Turns out, the latest Raspian OS (bullseye, version 11) has an older
version of numpy built into it, and this was causing the problem with
Astropy.
I had to delete this old version (1.19.5) and upgrade it. Also had to
install libatlas3-base.  Here's what I did:

$ sudo apt update
$ sudo apt remove python3-numpy
$ sudo apt install libatlas3-base
$ sudo pip3 install numpy

$ pip show numpy
  numpy 1.22.3
  location /usr/lib/python3.9/dist-packages

Previously, I tried upgrading numpy, but the newer version was placed in my
local directory, not in root.  When I would run Astropy, it would use the
root version, and I would get an error.  All other items (pyerfa, PyYAML,
packaging, etc) satisfy Astropy requirements.

Dave

**Comment by pllim** [comment]
Glad to hear and thanks for posting the solution here, @dave290 ! I am sure other Raspberry Pi users who run into the same problem would find this very helpful in the future.

**Comment by eerovaher** [comment]
It's best if you let your system package manager (`apt` in your case) take care of system packages and avoid installing any with `pip`. In case the version of a Python package available in the repository of your distribution is too old then you should install that package with `pip` for your user, not at the system level. See e.g. the 'Installing via pip' section at https://scipy.org/install/
