### ISSUE TITLE
Column.value is not documented

### ISSUE THREAD

**Issue by orionlee** [astropy/astropy#13012]
### Description

`Column.value`, an alias of `Column.data`, is not documented.
  https://docs.astropy.org/en/stable/api/astropy.table.Column.html

The alias was introduced back in PR #10962 .

Version: astropy 5.0.3

**Comment by jerobado** [comment]
Hello, I would like to work on this issue.

Will this description be fine? 

**"An alias for the existing ``Column.data`` attribute."**

This will be added as a last entry under <ins>Attributes Summary</ins> and <ins>Attributes Documentation</ins> section in the `Column`'s docs [page](https://docs.astropy.org/en/stable/api/astropy.table.Column.html).

Let me know your inputs.

**Comment by taldcroft** [comment]
Sounds good!

**Comment by jerobado** [comment]
Need a bit of help.

Where can I find [`https://github.com/astropy/astropy/blob/main/docs/api/astropy.table.Column.rst`](https://github.com/astropy/astropy/blob/main/docs/api/astropy.table.Column.rst)?

That page is no longer found. I tried looking in `/docs/table` directory but no avail.

**Comment by taldcroft** [comment]
The API docs are automatically generated. I think the best thing would just be documenting this behavior in the `Column` docstring in the `Examples` section. I notice now that the `data` attribute is also not obviously documented.

The new bit could be as simple as:
```
To access the ``Column`` data as a raw `np.ndarray` object, you can use one of the 
``data`` or ``value`` attributes (which are equivalent)::

  col.data
  col.value
```

For the `MaskedColumn` class you should do the same, with:
```
To access the ``Column`` data as a raw `np.ma.MaskedArray` object, you can use one of the 
``data`` or ``value`` attributes (which are equivalent)::

  col.data
  col.value
```
