### ISSUE TITLE
TST: MatplotlibDeprecationWarning: Auto-removal of overlapping axes is deprecated

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13013]
Some tests failing with dev version of `matplotlib`:

```
matplotlib._api.deprecation.MatplotlibDeprecationWarning:
Auto-removal of overlapping axes is deprecated since 3.6 and will be removed
two minor releases later; explicitly call ax.remove() as needed.
```

Example log: https://github.com/astropy/astropy/runs/5740092234?check_suite_focus=true

Affected tests:

* `astropy/visualization/tests/test_norm.py::test_imshow_norm`
* `astropy/visualization/wcsaxes/tests/test_misc.py::test_slicing_warnings`
* `astropy/visualization/wcsaxes/tests/test_misc.py::test_invalid_slices_errors`
* `astropy/visualization/wcsaxes/tests/test_misc.py::test_repr`
* `astropy/visualization/wcsaxes/tests/test_wcsapi.py::test_sliced_ND_input[wcs_slice0]`

**Comment by tacaswell** [comment]
The fix may be to add `plt.clf()` in the test before adding a second (overlapping) Axes.

**Comment by pllim** [comment]
Thanks! I'll give that a try.

**Comment by pllim** [comment]
Seems to work over at #13016 . Thank you so much, @tacaswell !
