### ISSUE TITLE
Release anchors in the changelog are just numbered top to bottom

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#13038]
### Description

The anchors for the individual releases in the changelog have the form `idX`, which makes linking to specific release notes
go wrong when a new release is added. E.g. This anchor pointed to 5.0.2 before the release of 5.0.4 but now points to 5.0.3:
https://docs.astropy.org/en/stable/changelog.html#id2

### Expected behavior

Use fixed anchor names with the version numbers?

**Comment by pllim** [comment]
@saimn , is this a towncrier fix somewhere?

**Comment by maxnoe** [comment]
Would adding a rst anchor like so work:
```
.. _{{ versiondata.version }}
```
