### ISSUE TITLE
DEV: IERS_B_FILE missing from source checkout

### ISSUE THREAD

**Issue by feilongm** [astropy/astropy#13037]
### Description

I'm trying setting up the development version of Astropy on my laptop (MacOS) following this tutorial https://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#get-devel. Everything works fine until "Test your development copy".
### Expected behavior

According to the tutorial, the expected output should be ![Screen Shot 2022-04-01 at 12 21 32 AM](https://user-images.githubusercontent.com/73732334/161194441-edf0e530-f947-4bb1-a94f-152fd7da28ce.png)
### Actual behavior

It throws me an error "urlopen error Unable to open any source".
![Screen Shot 2022-04-01 at 12 23 41 AM](https://user-images.githubusercontent.com/73732334/161194633-ea29abf8-f3be-44df-8a72-308f25fe56dd.png)

### Steps to Reproduce

I followed this tutorial https://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#get-devel.

```python
# Put your Python code snippet here.
```

**Comment by eerovaher** [comment]
It looks like there is a problem with IERS data, but it is not possible to tell much more from the screenshot you posted. What was the exact command you used to launch the tests and what was the full traceback?

**Comment by feilongm** [comment]
I used pytest. 
============================= test session starts ==============================
platform darwin -- Python 3.8.5, pytest-7.1.1, pluggy-0.13.1

Running tests with Astropy version 5.1.dev701+gf41c1e65e.d20220330.
Running tests in astropy docs.

Date: 2022-04-01T13:53:37

Platform: macOS-10.15.7-x86_64-i386-64bit

Executable: /opt/anaconda3/bin/python3

Full Python Version: 
3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.2
Scipy: 1.5.2
Matplotlib: 3.3.2
h5py: 2.10.0
Pandas: 1.1.3
PyERFA: 2.0.0.1
Cython: 0.29.21
Scikit-image: 0.17.2
asdf: not available
pyarrow: not available

Using Astropy options: remote_data: none.

ARCH_ON_CI: undefined
IS_CRON: undefined

rootdir: /Users/mengfeilong/Desktop/hw6/astropy, configfile: setup.cfg, testpaths: astropy, docs
plugins: xdist-2.5.0, remotedata-0.3.3, forked-1.4.0, astropy-header-0.2.1, mock-3.7.0, hypothesis-6.40.0, filter-subpackage-0.1.1, openfiles-0.5.0, doctestplus-0.12.0, cov-3.0.0, arraydiff-0.5.0
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/opt/anaconda3/lib/python3.8/urllib/request.py:1350: in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
/opt/anaconda3/lib/python3.8/http/client.py:1255: in request
    self._send_request(method, url, body, headers, encode_chunked)
/opt/anaconda3/lib/python3.8/http/client.py:1301: in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
/opt/anaconda3/lib/python3.8/http/client.py:1250: in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
/opt/anaconda3/lib/python3.8/http/client.py:1010: in _send_output
    self.send(msg)
/opt/anaconda3/lib/python3.8/http/client.py:950: in send
    self.connect()
/opt/anaconda3/lib/python3.8/http/client.py:921: in connect
    self.sock = self._create_connection(
/opt/anaconda3/lib/python3.8/site-packages/pytest_remotedata/disable_internet.py:98: in new_function
    raise IOError("An attempt was made to connect to the internet "
E   OSError: An attempt was made to connect to the internet by a test that was not marked `remote_data`. The requested host was: data.astropy.org

During handling of the above exception, another exception occurred:
astropy/utils/data.py:1363: in download_file
    f_name = _download_file_from_source(
astropy/utils/data.py:1167: in _download_file_from_source
    with _try_url_open(source_url, timeout=timeout, http_headers=http_headers,
astropy/utils/data.py:1104: in _try_url_open
    return urlopener.open(req, timeout=timeout)
/opt/anaconda3/lib/python3.8/urllib/request.py:525: in open
    response = self._open(req, data)
/opt/anaconda3/lib/python3.8/urllib/request.py:542: in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
/opt/anaconda3/lib/python3.8/urllib/request.py:502: in _call_chain
    result = func(*args)
/opt/anaconda3/lib/python3.8/urllib/request.py:1379: in http_open
    return self.do_open(http.client.HTTPConnection, req)
/opt/anaconda3/lib/python3.8/urllib/request.py:1353: in do_open
    raise URLError(err)
E   urllib.error.URLError: <urlopen error An attempt was made to connect to the internet by a test that was not marked `remote_data`. The requested host was: data.astropy.org>

The above exception was the direct cause of the following exception:
/opt/anaconda3/lib/python3.8/site-packages/pluggy/manager.py:127: in register
    hook._maybe_apply_history(hookimpl)
/opt/anaconda3/lib/python3.8/site-packages/pluggy/hooks.py:333: in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
/opt/anaconda3/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/opt/anaconda3/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
astropy/conftest.py:65: in pytest_configure
    from astropy.utils.iers import conf as iers_conf
astropy/utils/iers/__init__.py:2: in <module>
    from .iers import *
astropy/utils/iers/iers.py:47: in <module>
    IERS_B_FILE = get_pkg_data_filename('data/eopc04_IAU2000.62-now')
astropy/utils/data.py:654: in get_pkg_data_filename
    return download_file(conf.dataurl + data_name, cache=True,
astropy/utils/data.py:1395: in download_file
    raise urllib.error.URLError(
E   urllib.error.URLError: <urlopen error Unable to open any source! Exceptions were {'http://data.astropy.org/data/eopc04_IAU2000.62-now': URLError(OSError('An attempt was made to connect to the internet by a test that was not marked `remote_data`. The requested host was: data.astropy.org')), 'http://www.astropy.org/astropy-data/data/eopc04_IAU2000.62-now': URLError(OSError('An attempt was made to connect to the internet by a test that was not marked `remote_data`. The requested host was: www.astropy.org'))}>
=========================== short test summary info ============================
ERROR  - urllib.error.URLError: <urlopen error Unable to open any source! Exc...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.44s ===============================

**Comment by pllim** [comment]
Ah yeah. You don't have any IERS leap second table in your cache but we need it even for offline tests. It should have tried to use the bundled copy but it isn't. This is an issue that is being discussed at #9227 along with other things.

For now, run it with `--remote-data=astropy` flag.

**Comment by feilongm** [comment]
Thanks for your reply. However, I'm still getting errors.

(base) 0587341873:astropy mengfeilong$ pytest --remote-data=astropy
============================= test session starts ==============================
platform darwin -- Python 3.8.5, pytest-7.1.1, pluggy-0.13.1

Running tests with Astropy version 5.1.dev701+gf41c1e65e.d20220330.
Running tests in astropy docs.

Date: 2022-04-01T15:19:25

Platform: macOS-10.15.7-x86_64-i386-64bit

Executable: /opt/anaconda3/bin/python3

Full Python Version: 
3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.2
Scipy: 1.5.2
Matplotlib: 3.3.2
h5py: 2.10.0
Pandas: 1.1.3
PyERFA: 2.0.0.1
Cython: 0.29.21
Scikit-image: 0.17.2
asdf: not available
pyarrow: not available

Using Astropy options: remote_data: astropy.

ARCH_ON_CI: undefined
IS_CRON: undefined

rootdir: /Users/mengfeilong/Desktop/hw6/astropy, configfile: setup.cfg, testpaths: astropy, docs
plugins: xdist-2.5.0, remotedata-0.3.3, forked-1.4.0, astropy-header-0.2.1, mock-3.7.0, hypothesis-6.40.0, filter-subpackage-0.1.1, openfiles-0.5.0, doctestplus-0.12.0, cov-3.0.0, arraydiff-0.5.0
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
astropy/utils/data.py:1363: in download_file
    f_name = _download_file_from_source(
astropy/utils/data.py:1167: in _download_file_from_source
    with _try_url_open(source_url, timeout=timeout, http_headers=http_headers,
astropy/utils/data.py:1104: in _try_url_open
    return urlopener.open(req, timeout=timeout)
/opt/anaconda3/lib/python3.8/urllib/request.py:531: in open
    response = meth(req, response)
/opt/anaconda3/lib/python3.8/urllib/request.py:640: in http_response
    response = self.parent.error(
/opt/anaconda3/lib/python3.8/urllib/request.py:563: in error
    result = self._call_chain(*args)
/opt/anaconda3/lib/python3.8/urllib/request.py:502: in _call_chain
    result = func(*args)
/opt/anaconda3/lib/python3.8/urllib/request.py:755: in http_error_302
    return self.parent.open(new, timeout=req.timeout)
/opt/anaconda3/lib/python3.8/urllib/request.py:531: in open
    response = meth(req, response)
/opt/anaconda3/lib/python3.8/urllib/request.py:640: in http_response
    response = self.parent.error(
/opt/anaconda3/lib/python3.8/urllib/request.py:569: in error
    return self._call_chain(*args)
/opt/anaconda3/lib/python3.8/urllib/request.py:502: in _call_chain
    result = func(*args)
/opt/anaconda3/lib/python3.8/urllib/request.py:649: in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
E   urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:
/opt/anaconda3/lib/python3.8/site-packages/pluggy/manager.py:127: in register
    hook._maybe_apply_history(hookimpl)
/opt/anaconda3/lib/python3.8/site-packages/pluggy/hooks.py:333: in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
/opt/anaconda3/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/opt/anaconda3/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
astropy/conftest.py:65: in pytest_configure
    from astropy.utils.iers import conf as iers_conf
astropy/utils/iers/__init__.py:2: in <module>
    from .iers import *
astropy/utils/iers/iers.py:47: in <module>
    IERS_B_FILE = get_pkg_data_filename('data/eopc04_IAU2000.62-now')
astropy/utils/data.py:654: in get_pkg_data_filename
    return download_file(conf.dataurl + data_name, cache=True,
astropy/utils/data.py:1395: in download_file
    raise urllib.error.URLError(
E   urllib.error.URLError: <urlopen error Unable to open any source! Exceptions were {'http://data.astropy.org/data/eopc04_IAU2000.62-now': <HTTPError 404: 'Not Found'>, 'http://www.astropy.org/astropy-data/data/eopc04_IAU2000.62-now': <HTTPError 404: 'Not Found'>}>
=========================== short test summary info ============================
ERROR  - urllib.error.URLError: <urlopen error Unable to open any source! Exc...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.57s ===============================

**Comment by pllim** [comment]
Oh... right. It is not hosted by us. Sorry. Please try `--remote-data` instead.

**Comment by feilongm** [comment]
Hi I'm still getting the same error.

(base) 0587341873:astropy mengfeilong$ pytest --remote-data
============================= test session starts ==============================
platform darwin -- Python 3.8.5, pytest-7.1.1, pluggy-0.13.1

Running tests with Astropy version 5.1.dev701+gf41c1e65e.d20220330.
Running tests in astropy docs.

Date: 2022-04-01T15:32:28

Platform: macOS-10.15.7-x86_64-i386-64bit

Executable: /opt/anaconda3/bin/python3

Full Python Version: 
3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.2
Scipy: 1.5.2
Matplotlib: 3.3.2
h5py: 2.10.0
Pandas: 1.1.3
PyERFA: 2.0.0.1
Cython: 0.29.21
Scikit-image: 0.17.2
asdf: not available
pyarrow: not available

Using Astropy options: remote_data: any.

ARCH_ON_CI: undefined
IS_CRON: undefined

rootdir: /Users/mengfeilong/Desktop/hw6/astropy, configfile: setup.cfg, testpaths: astropy, docs
plugins: xdist-2.5.0, remotedata-0.3.3, forked-1.4.0, astropy-header-0.2.1, mock-3.7.0, hypothesis-6.40.0, filter-subpackage-0.1.1, openfiles-0.5.0, doctestplus-0.12.0, cov-3.0.0, arraydiff-0.5.0
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
astropy/utils/data.py:1363: in download_file
    f_name = _download_file_from_source(
astropy/utils/data.py:1167: in _download_file_from_source
    with _try_url_open(source_url, timeout=timeout, http_headers=http_headers,
astropy/utils/data.py:1104: in _try_url_open
    return urlopener.open(req, timeout=timeout)
/opt/anaconda3/lib/python3.8/urllib/request.py:531: in open
    response = meth(req, response)
/opt/anaconda3/lib/python3.8/urllib/request.py:640: in http_response
    response = self.parent.error(
/opt/anaconda3/lib/python3.8/urllib/request.py:563: in error
    result = self._call_chain(*args)
/opt/anaconda3/lib/python3.8/urllib/request.py:502: in _call_chain
    result = func(*args)
/opt/anaconda3/lib/python3.8/urllib/request.py:755: in http_error_302
    return self.parent.open(new, timeout=req.timeout)
/opt/anaconda3/lib/python3.8/urllib/request.py:531: in open
    response = meth(req, response)
/opt/anaconda3/lib/python3.8/urllib/request.py:640: in http_response
    response = self.parent.error(
/opt/anaconda3/lib/python3.8/urllib/request.py:569: in error
    return self._call_chain(*args)
/opt/anaconda3/lib/python3.8/urllib/request.py:502: in _call_chain
    result = func(*args)
/opt/anaconda3/lib/python3.8/urllib/request.py:649: in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
E   urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:
/opt/anaconda3/lib/python3.8/site-packages/pluggy/manager.py:127: in register
    hook._maybe_apply_history(hookimpl)
/opt/anaconda3/lib/python3.8/site-packages/pluggy/hooks.py:333: in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
/opt/anaconda3/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/opt/anaconda3/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
astropy/conftest.py:65: in pytest_configure
    from astropy.utils.iers import conf as iers_conf
astropy/utils/iers/__init__.py:2: in <module>
    from .iers import *
astropy/utils/iers/iers.py:47: in <module>
    IERS_B_FILE = get_pkg_data_filename('data/eopc04_IAU2000.62-now')
astropy/utils/data.py:654: in get_pkg_data_filename
    return download_file(conf.dataurl + data_name, cache=True,
astropy/utils/data.py:1395: in download_file
    raise urllib.error.URLError(
E   urllib.error.URLError: <urlopen error Unable to open any source! Exceptions were {'http://data.astropy.org/data/eopc04_IAU2000.62-now': <HTTPError 404: 'Not Found'>, 'http://www.astropy.org/astropy-data/data/eopc04_IAU2000.62-now': <HTTPError 404: 'Not Found'>}>
=========================== short test summary info ============================
ERROR  - urllib.error.URLError: <urlopen error Unable to open any source! Exc...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.58s ===============================
(base) 0587341873:astropy mengfeilong$

**Comment by pllim** [comment]
Ah, I see now...

```
astropy/utils/iers/iers.py:47: in
IERS_B_FILE = get_pkg_data_filename('data/eopc04_IAU2000.62-now')
```

https://github.com/astropy/astropy/blob/64fe8fa3b15089caac67c1806f3ce648bdb73791/astropy/utils/iers/iers.py#L47

Check your local directory that correspond to https://github.com/astropy/astropy/tree/main/astropy/utils/iers/data . Looks like somehow your checkout isn't complete?
