### ISSUE TITLE
WCS-TAB segfault after swapaxes when spectral attribute is accessed

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13036]
This is a follow-up of #12946 using the same file that @mcara and I had. Using `wcslib` 7.9 that came with `astropy` 5.0.4 , `swapaxes()` does not crash but the resulting WCS object cannot be used because it segfaults when the `spectral` attribute is accessed.

```python
from astropy.io import fits
from astropy.wcs import WCS

lvl2_file = 'Level2_det_image_seq1_MIRIFULONG_34LONGexp1_s3d.fits'
pf = fits.open(lvl2_file)
w = WCS(pf['SCI'].header, pf)
w2 = w.swapaxes(0, 2)  # No error now
w2.spectral  # segfault
```

My `gdb`-fu is weak, so this is all I got out of it though there is a long backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
... in PyWcsprm_copy ()
   from .../astropy/wcs/_wcs.cpython-39-x86_64-linux-gnu.so
```

https://github.com/astropy/astropy/blob/298ccb478e6bf092953bca67a3d29dc6c35f6752/astropy/wcs/src/wcslib_wrap.c#L629

### More digging

Maybe the hardcoded `WCSSUB_SPECTRAL` is now wrong after swap.

```python
from astropy.wcs import _wcs
print(_wcs.WCSSUB_SPECTRAL)  # 4104
w.sub([4104])  # OK
w2.sub([4104])  # segfault
```

https://github.com/astropy/astropy/blob/323dd7fe288ec3cf1490aafb78cec137db4093a3/cextern/wcslib/C/wcs.h#L1977

**Comment by mcara** [comment]
I will look into it. Thanks for reporting!
