### ISSUE TITLE
Gaia timeseries

### ISSUE THREAD

**Issue by rbaer25** [astropy/astropy#13059]
### Description
The [TimeSeries — Astropy v5.0.4] provides two formats: kepler.fits and tess.fits A format to analyse gaia timeseries could be a useful addition

### Additional context
I am trying to use the time series for light curves of Gaia DR2. 
The Gaia data light curve data are originally in csv format; via topcat I can save them in .fits or votable formats, and I can read and plot them without problems. However they do not work with timeseries. I show a partial screen shot of the format   in topcat. The time is the Onboard time of Gaia.
<img width="981" alt="Screenshot 2022-04-03 at 11 42 17" src="https://user-images.githubusercontent.com/10469522/161726480-b9b8e604-6ba2-446b-93d3-9ac83366ac03.png">

**Comment by pllim** [comment]
Hello! If you know a developer from Gaia project who could contribute to this, it would be awesome. Thanks.

**Comment by dhomeier** [comment]
The original CSV is readable with some curation:
```python
lc = Table.read('Downloads/light_curves_1042504286338226688_1098703830327377408.csv.gz', format='csv')
lc['time'] = Time(lc['time'] + 2455197.5, format='jd')
ts = TimeSeries(lc)
tsg = TimeSeries(lc[lc['band']=='G'])
```
assuming I have interpreted the format specification in the [Datalink documentation](https://gea.esac.esa.int/archive/documentation/GDR2/Gaia_archive/chap_datamodel/sec_dm_datalink_tables/ssec_dm_light_curve.html) correctly, but it would definitely be something worth to have a convenience method for (and possibly also add some additional filter options like above, as it seems the existing files combine photometry from different bands.
Also would be helpful to already know a bit more on the DR3 format – CSV certainly is not the greatest choice for larger datasets – so having a Gaia developer chime in would indeed be helpful.

**Comment by rbaer25** [comment]
Thank you very much for the reply.
Although I can print the 'time' column, the code aborts on NameError: name
'Time' is not defined. I tried various formats, but I could not fix this
issue. Maybe I am missing something basic.
with kind regards
Rudolf

#from astropy forum
from astropy.timeseries import TimeSeries
from astropy.table import Table
lc =
Table.read('/Users/rudolf/gaia/light_curves_1593816944267707008_1645461142863500928.csv',
format='csv')
print (lc['time'])
print(lc['time'].dtype)
lc['time'] = Time(lc['time'] + 2455197.5, format='jd')
ts = TimeSeries(lc)
tsg = TimeSeries(lc[lc['band']=='G'])

       time
------------------
1690.5231740620018
 1690.773330262819
 1690.847334892412
1691.0235078129333
1691.0974914475078
1691.2736154323004
1691.3476483506367
1691.5238006669615
1691.5977774475873
 1691.773958104837
               ...
2084.2271878798665
2118.7128364872415
 2118.786847476039
2151.1961760092495
   2151.2701842026
2177.9371864117843
 2178.011198278194
2213.7263498119423
2235.1494985764225
 2332.570578015724
 2332.644582030186
Length = 133719 rows
float64


NameError                                 Traceback (most recent call
last)<ipython-input-103-51e40749f02b> in <module>      5 print
(lc['time'])      6 print(lc['time'].dtype)----> 7 lc['time'] =
Time(lc['time'] + 2455197.5, format='jd')      8 ts = TimeSeries(lc)
   9 tsg = TimeSeries(lc[lc['band']=='G'])
NameError: name 'Time' is not defined

**Comment by dhomeier** [comment]
> NameError: name 'Time' is not defined

Sorry, I missed the
```python
from astropy.time import Time
```
there!

**Comment by rbaer25** [comment]
Hi Derek
thanks a lot. It works.
with kind regards
Rudolf

**Comment by pllim** [comment]
Closing since it appears resolved. Thanks, all!
