### ISSUE TITLE
Building Documentation: config and/or documentation issue 

### ISSUE THREAD

**Issue by orionlee** [astropy/astropy#13053]
### Description

I tried to build a local documentation following https://docs.astropy.org/en/latest/install.html#builddocs , and found some issue.

- Discrepancy in dependencies: 
  - The conda package `sphinx-astropy` appears to be incompatible with `setup.cfg`
  - I first installed the dependencies using `conda install -c conda-forge sphinx-astropy` suggested in the docs. But the versions installed installed are incompatible with the specifications in https://github.com/astropy/astropy/blob/184f3cba5e84d918246b852571183acc5cddd197/setup.cfg#L96-L98
  - e.g., the sphinx installed via `conda` is v4.5.0 , while `setup.cfg` requires `<4` .

- More robust error reporting in `docs/conf.py`
  - When the doc is built by [VSCode Esbonio](https://marketplace.visualstudio.com/items?itemName=swyddfa.esbonio) extension, it failed silently due to the dependencies incompatibility above.
  - Specifically, the error messages are not shown, even though they are in https://github.com/astropy/astropy/blob/184f3cba5e84d918246b852571183acc5cddd197/docs/conf.py#L54-L56 
  - It appears that VSCode Esbonio does not include stdout from the build in its output.
  - Suggestion: replace `print` with `logging.error` in `docs/conf.py` 

### System Details

```
Windows-10-10.0.22000-SP0
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:21:54) [MSC v.1929 64 bit (AMD64)]
Numpy 1.22.3
pyerfa 2.0.0.1
astropy 5.1.dev767+g323dd7fe2.d20220403
Scipy 1.8.0
Matplotlib 3.5.1
```

**Comment by pllim** [comment]
Re: conda -- Alas, I think the conda recipe ignores the `setup.cfg` pins completely. Maybe @mwcraig can comment here.

Re: logging -- There is a `astropy` logger but I don't use VSCode so I dunno if this is the best solution or to have VSCode somehow display stdout.

**Comment by pllim** [comment]
p.s. We don't like the Sphinx maxversion pin and hoping to remove it soon, if possible. See #13048

**Comment by mwcraig** [comment]
The issue(s) with `conda` are two-fold. One is that the dependencies are specified in a different file than `setup.cfg`. The other issue is that `conda` doesn't have the concept of "optional" installs like `pip` does. 

So, for example, with `pip` you can do `pip install astropy[doc]` and you get the optional dependencies for building the astropy documentation. Unfortunately, `conda` does not have such a thing.

Probably the best bet is to `pip` install for this case. The second best would be to install those dependencies manually: `conda install -c conda-forge sphinx\<4 sphinx-astropy\>=1.6`

You may or may not need the backslashes to make sure the shell doesn't interpret `<` and `>` as input/output redirects.

**Comment by orionlee** [comment]
For conda package `sphinx-astropy` being incompatible with `setup.cfg`, I have 2 suggestions:
- remove the use of conda `sphinx-astropy` package from [documentation](https://docs.astropy.org/en/latest/install.html#builddocs), and just tell people to use `pip` . (As a data point, `pip insteall -e .[doc]` works for me on Windows 11)
- if conda `sphinx-astropy` is still needed, I still think it is to specify the required dependency:
  - We could  generate a conda `requirements.txt` for documentation, e.g., in `docs/requirements.txt` that is the conda-equivalent of the doc section of `setup.cfg`,
  - Instead of telling user to do `conda install -c conda-forge sphinx-astropy`, tell them `conda install -c conda-forge docs/requirements.txt`

---

The incompatibility is not just limited to sphinx, e.g., `Jinja2<3.1` also causes problems. There are probably one or two more but I don't have the error readily in hand.

**Comment by pllim** [comment]
Jinja2 pin is because of Sphinx pin, if the latter is removed, so will the former. FYI.

**Comment by neutrinoceros** [comment]
The first point has been addressed: `sphinx` isn't currently pinned in any way (meanwhile, metadata was moved from `setup.cfg` to `pyproject.toml`).

The second problem, namely, that `stdout` isn't included in some tools' output can be addressed either as suggested (using `logging.error`) or even simply by using `print(..., file=sys.stderr)`. I'll open a PR to close this.
