### ISSUE TITLE
timeseries aggregate_downsample() appears to be significantly slower in Astropy 5

### ISSUE THREAD

**Issue by orionlee** [astropy/astropy#13058]
### Description

TimeSeries `aggregate_downsample()` appears to be significantly slower in Astropy 5 (comparing it with Astropy 4).

For the sample TimeSeries below (20000 data points), doing a `aggregate_downsample(ts, time_bin_size=10*u.minute)` , the elapsed time is roughtly:

- Astropy 4.3.1, Windows 11: < 1 sec
- Astropy 5, Windows 11: ~ 10 sec
- Astropy 5, Windows 11 with WSL2: ~ 7 sec

The astropy in question are installed with `conda`  (`pip` for WSL2).

### Steps to Reproduce
The sample time series and the timing script:

```python
# Test timeseries aggregate_downsample's running time

from astropy.time import Time
from astropy.timeseries import TimeSeries
from astropy import units as u
import numpy as np
from timeit import default_timer as timer

# the scale of a typical TESS 2-minute cadence lightcurve
num_points = 20000
time = Time(2457000 + np.arange(0, num_points) / 24 / 60 * 2, format="jd")
flux = np.ones(num_points)

ts = TimeSeries(time=time, data=dict(flux=flux))

start = timer()
ts_b = astropy.timeseries.aggregate_downsample(ts, time_bin_size=10*u.minute)
end = timer()

print("ts.bin(10 min) elapsed time:", (end - start))
len(ts), len(ts_b)
```

#### Windows 11 + Astropy 4.3.1
```
Windows-10-10.0.22000-SP0
Python  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:21:54) [MSC v.1929 64 bit (AMD64)]
astropy  4.3.1
Numpy  1.22.3
pyerfa  2.0.0.1
Scipy  1.8.0
```

#### Windows 11 + Astropy 5
```
Windows-10-10.0.22000-SP0
Python  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:21:54) [MSC v.1929 64 bit (AMD64)]
astropy  5.0.4
Numpy  1.22.3
pyerfa  2.0.0.1
Scipy  1.8.0
```

#### Windows 11 WSL2 + Astropy 5
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python  3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
astropy  5.0.2
Numpy  1.22.3
pyerfa  2.0.0.1
Scipy  1.8.0
```

**Comment by pllim** [comment]
Somehow @aaryapatil 's name jumped to mind when I try to think of more recent time series changes... I could be misremembering though.

It is unfortunate we don't have the resources to implement benchmarking for PRs yet: astropy/astropy-benchmarks#106

**Comment by dhomeier** [comment]
#11266 and successors certainly come to mind, although I think we did check for all too obvious performance hits.
But that was a fairly complex enhancement, so certainly some things may have crept in.
It's also worth noting that the previous implementation just did not produce very useful (possibly even wrong) binning results in some cases.

**Comment by pllim** [comment]
@orionlee , if you could profile it in a way to see any obvious bottlenecks (e.g., using snakeviz), that would certainly help!

**Comment by orionlee** [comment]
- I can confirm PR #11266 does lead to the performance degradation. See below.
- It'd be great if someone could run the same test on non-Windows platform. to confirm if the degradation happens only on Windows.

---

Degradation source confirmation: I ran the same test script against the commit before #11266 was merged (549404a80) and the commit after it was merged (110e2dd10)

Before #11266:
```shell
(astropy_RO) (astropy_RO) /c/dev/_astropy_RO ((549404a80...))
$python test_binning_time.py
Windows-10-10.0.22000-SP0
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:21:54) [MSC v.1929 64 bit (AMD64)]
Numpy 1.22.3
pyerfa 2.0.0.1
astropy 5.0.dev937+g549404a80.d20220405
ts.bin(10 min) elapsed time: 0.5385730999999998
20000 4000
```

After #11266:
```
(astropy_RO) (astropy_RO) /c/dev/_astropy_RO ((110e2dd10...))
$python test_binning_time.py
Windows-10-10.0.22000-SP0
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:21:54) [MSC v.1929 64 bit (AMD64)]
Numpy 1.22.3
pyerfa 2.0.0.1
astropy 5.0.dev943+g110e2dd10.d20220405
ts.bin(10 min) elapsed time: 10.4164447
20000 4000
```

**Comment by dhomeier** [comment]
Considerable time is apparently spent in the `np.searchsorted` calls, like 25-30 % of the total in
https://github.com/astropy/astropy/blob/f54df76430eac0f67efb1e61be5a31f4c3029b9d/astropy/timeseries/downsample.py#L173
only (and there may be additional calls.
This in turn apparently has a **huge** overhead due to calling the ufunc on the time objects directly – e.g. for the above example, `np.searchsorted(ts.time, ts_b.time_bin_start)` clocks in at some 3 seconds, whereas
`np.searchsorted(ts.time.value, ts_b.time_bin_start.value)` takes about as many milliseconds!
That's a bit disappointing wrt the `Time` objects, but in the `aggregate_downsample` case could probably be fairly easily improved by switching to ndarrays, e.g. using `to_value('unix')`.

**Comment by orionlee** [comment]
Replacing the 2 calls for `Time` with plain objects `np.searchsorted()` cuts down the time considerably. 
- It cuts down the time to run the test from ~10sec to ~1.5sec
- still noticeably slower than the ~0.5sec before the PR (~ 0.5 sec).

---
The change made: 
With #11266, 
https://github.com/astropy/astropy/blob/110e2dd10d7738212f2d016dae5eb2aa996dea83/astropy/timeseries/downsample.py#L169-L174

pass plain array with `.value` to `np.searchsorted()`

```python
    # For time == bin_start[i+1] == bin_end[i], let bin_start takes precedence
    if np.all(bin_start[1:] >= bin_end[:-1]):
        indices_start = np.searchsorted(ts_sorted.time[keep].value,
                                        np.minimum(bin_start, ts_sorted.time[-1]).value)
```

**Comment by orionlee** [comment]
I did an audit of all the additions involving calling numpy functions in the PR, and found another instance that caused some (smaller) degradation.

https://github.com/astropy/astropy/blob/f54df76430eac0f67efb1e61be5a31f4c3029b9d/astropy/timeseries/downsample.py#L165-L166

Replacing the `Time` object comparison with array further cuts down the elapsed time from ~1.5sec to ~1.2sec

```python
        delete_indices = np.where(np.logical_and(ts_sorted.time.value > bin_end[ind].value,
                                                 ts_sorted.time.value < bin_start[ind+1].value))

```

It's a bit different here, in that `Time` objects are not passed to the `np` functions to begin with.

**Comment by dhomeier** [comment]
> It's a bit different here, in that `Time` objects are not passed to the `np` functions to begin with.

Odd, yes – running `np.logical_and(ts_sorted.time > bin_end[ind], ts_sorted.time < bin_start[ind+1])` directly I see no noticeable degradation – interestingly, `np.greater(ts_sorted.time > bin_end[ind])` is much slower again.

**Comment by dhomeier** [comment]
> Replacing the `Time` object comparison with array further cuts down the elapsed time from ~1.5sec to ~1.2sec
> 
> ```python
>         delete_indices = np.where(np.logical_and(ts_sorted.time.value > bin_end[ind].value,
>                                                  ts_sorted.time.value < bin_start[ind+1].value))
> ```

That is in fact fairly relevant as it scales quadratically (more precisely, with `num_points * n_bins`) - see https://github.com/astropy/astropy/pull/13069#issuecomment-1090808276.
As it still involves a Python loop over `n_bins`, which is covering a relevant corner case, but actually not needed at all for standard use cases. Some savings can in fact be gained by encasing the `delete_indices =` in a
`if bin_start[ind+1] > bin_end[ind]:`

**Comment by hippke** [comment]
What about a simpler approach that runs in linear time and is essentially instant for <10^6 data points.
Polishing first and last values and NaNs could be done in a second iteration afterwards.
If you want to keep the API as-is, you'd need to calculate the "factor" from the number of bins requested.
```
def resample(time, flux, factor):
    time_grid = int(len(flux) / factor)
    time_resampled = np.linspace(min(time), max(time), time_grid)
    f = interp1d(time_resampled, time)
    flux_resampled = f(flux)
    return time_resampled, flux_resampled
```
