### ISSUE TITLE
Add ``flake8-docstrings`` plugin to tox CI

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13083]
### Description

It can be configured to check NumPy docstring style.

### Additional context

See bottom of https://flake8.pycqa.org/en/latest/user/using-hooks.html.
It's a very official plugin.

**Comment by pllim** [comment]
Oh dear... I am sure we will get a lot of failures.

**Comment by nstarman** [comment]
Just think of the beautiful docs when we're done 🥺

**Comment by pllim** [comment]
By the time we are done, it is probably time to autodoc from type annotation or something... 🧓

**Comment by nstarman** [comment]
@pllim So true.
Anyway, ruff has docstrings stuff now that we should be using instead.
