### ISSUE TITLE
Error parsing unit from string when exponential is a decimal number

### ISSUE THREAD

**Issue by jianyangli** [astropy/astropy#13127]
### Description

`astropy.units.Unit` failed to parse unit from a string when the exponential is a decimal number.  If does work if the decimal number is in a pair of parentheses.  An example is included below.

### Expected behavior

The unit should be parsed for units like 'm**0.5'.

### Actual behavior

`ValueError` exception is thrown out.

### Steps to Reproduce

```
import astropy.units as u
print(u.Unit('m**(0.5)'))
print(u.Unit('m**0.5'))
```

ValueError: 'm\*\*0.5' did not parse as unit: Syntax error parsing unit 'm\*\*0.5' If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html

### System Details

macOS-10.15.7-x86_64-i386-64bit
Python 3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)]
Numpy 1.22.3
pyerfa 2.0.0.1
astropy 5.0.4
Scipy 1.8.0
Matplotlib 3.5.1

I didn't test this in the current development version because I'm having trouble building the development version in my system.

**Comment by eerovaher** [comment]
`astropy` supports quite a few unit formats (listed [here](https://docs.astropy.org/en/stable/units/format.html#built-in-formats)) and your example does work with the `'ogip'` format:
```python
>>> from astropy import units as u
>>> u.Unit('m**0.5', format='ogip')
Unit("m(1/2)")
```
It doesn't look like there a bug here, you just need to specify what format the unit is written in.

**Comment by jianyangli** [comment]
Aha!  Thank you for pointing out the format keyword!  This is perfect.  No more problems then.  Let me close the issue.
