### ISSUE TITLE
MNT: Remove deprecated dms_to_degrees and hms_to_hours

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13179]
`dms_to_degrees` and `hms_to_hours` (in `astropy.coordinates.angle_formats`) were deprecated in v5.1 (#13162). They can be removed v6.0 or later.

EDIT by MHvK: be sure to also remove `Angle._tuple_to_float` and the tuple-related part in `__new__`.

**Comment by pllim** [comment]
Maybe revisit after #14663

**Comment by pllim** [comment]
I don't think I can remove `hms_to_hours` because this still uses it and that function is not deprecated. Any idea why we have such a situation, @eteq or @mhvk ?

https://github.com/astropy/astropy/blob/9b97d98802ee4f5350a62b681c35d8687ee81d91/astropy/coordinates/angle_formats.py#L501-L505

**Comment by pllim** [comment]
Maybe I can cheat by moving the code from `hms_to_hours` to `hms_to_degrees`.

**Comment by mhvk** [comment]
Anybody who used those would have hit the deprecation warning, so I think we can just go ahead and remove that function too...

**Comment by pllim** [comment]
@mhvk , but coordinates have real failures that I don't know how to fix. Please see https://github.com/astropy/astropy/actions/runs/5908753289/job/16028571403?pr=15205 . It looks like this functionality might be secretly used somewhere else in our own internals?

**Comment by pllim** [comment]
@WilliamJamieson , is the ASDF/Roman stuff also somehow affected by this? Please double check over at #15205. Thanks!
