### ISSUE TITLE
SkyCoord is not reliably iterable

### ISSUE THREAD

**Issue by MrBudgens** [astropy/astropy#13172]
SkyCoord implements __iter__() but cannot be iterated when storing only a single coordinate. This makes it a headache to feed it to code that expects iterables to be, well, iterable. I encountered this while attempting to flatten nested iterables that contained a SkyCoord somewhere within the structure.

# Setup

```python
from collections.abc import Iterable
from astropy.coordinates import SkyCoord
import astropy.units as u
coord = SkyCoord(ra=0*u.deg, dec=0*u.deg)
```

# Test if iterable

```python
isinstance(coord, Iterable)  # True
```

# Attempt to iterate

```python
>>> [x for x in coord]
TypeError: scalar 'SkyCoord' object is not iterable.
```

EDIT: Fixed formatting.

### System Details

Windows-10-10.0.19044-SP0
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Numpy 1.21.5
pyerfa 2.0.0
astropy 5.0.4
Scipy 1.7.3
Matplotlib 3.5.1

**Comment by eerovaher** [comment]
That scalars cannot be iterated is inherited from `numpy`:
```python
>>> from collections.abc import Iterable
>>> import numpy as np
>>> a = np.array(1)
>>> isinstance(a, Iterable)
True
>>> [elem for elem in a]
TypeError: iteration over a 0-d array
```
You can use the [astropy.utils.isiterable()](https://docs.astropy.org/en/stable/api/astropy.utils.misc.isiterable.html#astropy.utils.misc.isiterable) function to check if a `SkyCoord` can actually be iterated:
```python
>>> from astropy.coordinates import SkyCoord
>>> import astropy.units as u
>>> from astropy.utils import isiterable
>>> coord = SkyCoord(ra=0*u.deg, dec=0*u.deg)
>>> isiterable(coord)
False
```
Also note that the following does work:
```python
>>> coord = SkyCoord(ra=[0]*u.deg, dec=[0]*u.deg)
>>> [x for x in coord]
[<SkyCoord (ICRS): (ra, dec) in deg
     (0., 0.)>]

```
