### ISSUE TITLE
MNT: Replace Azure with Actions for release workflow

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13197]
Blocked by:

* #13348

Release workflow already available in Actions over at https://github.com/OpenAstronomy/github-actions-workflows . 

* Close #13194 
* Maybe should revisit #11400 to see if it magically goes away

This should be done by or in collaboration with people who hold the keys to Azure side of things to ensure a smooth transition. cc @astrofrog and @Cadair

**Comment by Cadair** [comment]
I think we are close to having the tools we need to do this, including the nightly wheels (although it will change the URL). This is still a lot of effort to migrate though.

**Comment by pllim** [comment]
I think there are not that many people using the nightly wheels or even aware they exist, so I think the URL change impact would be low.

**Comment by Cadair** [comment]
They get some downloads, I know of a good few repos using them. The issue is there's no real way for us to aid the migration to the new URL, pip will just ignore the URL if we break it and if we don't break it then people will just be getting stale builds.

I am not saying we don't do the migration, but we do need to bear it in mind.

**Comment by ConorMacBride** [comment]
Wheel building succeeded today after timeouts in previous days, but Astropy seems to be out of storage on Anaconda.org https://github.com/astropy/astropy/runs/6735962992?check_suite_focus=true#step:5:72

**Comment by pllim** [comment]
I don't see the storage problem but I see #13348 now.

**Comment by Cadair** [comment]
Where are the nightlies ending up on anaconda.org?

**Comment by ConorMacBride** [comment]
I think they should be [here](https://anaconda.org/astropy/repo?type=pypi) but there's no storage left to upload them.

**Comment by astrofrog** [comment]
Yeah we are using 18Gb of our 3Gb quota... I have emailed continuum to see if they can increase our quota but no reply yet. Are there other options we could use for dev wheels?

**Comment by pllim** [comment]
18 GB? 😱

**Comment by astrofrog** [comment]
Yes to be clear this is all conda packages (no wheels have been uploaded yet)
