### ISSUE TITLE
Documentation on wcslint is missing

### ISSUE THREAD

**Issue by javerbukh** [astropy/astropy#13203]
### Description

Googled "wcslint" and the only astropy related documentation is from a url that starts with `https://het.as.utexas.edu/`. @pllim mentioned this may be a bug here https://github.com/astropy/astropy/pull/10058#issuecomment-1116127275 . 

### Expected behavior

Information on how to use wcslint.

### Actual behavior

Information comes from another source, nothing on the most recent astropy docs.

**Comment by pllim** [comment]
Thanks for reporting this!

@perrygreenfield , @nden , and @mcara all approved #10058 , so maybe they can clarify the situation. 🙏
