### ISSUE TITLE
RTD failure due to plots involving convolution Kernels 

### ISSUE THREAD

**Issue by WilliamJamieson** [astropy/astropy#13209]
### Description

There are RTD failures due to a missing `ndim` in latest PRs, see:

- https://readthedocs.org/projects/astropy/builds/16812769/
- https://readthedocs.org/projects/astropy/builds/16812180/

I believe this may have to do with the latest version of `matplotlib` (https://github.com/matplotlib/matplotlib/releases/tag/v3.5.2) interacting poorly with how plots for `Box1DKernel`, `Gaussian1DKernel`, `RickerWavelet1DKernel`, and `Trapezoid1DKernel` are coded.

Note that a simple attempt at fixing this was tried in #13205; however, I think the fix will be more involved than this.

This is related to matplotlib/matplotlib#22973

**Comment by WilliamJamieson** [comment]
@keflavich do you have any suggestions on how to fix this?

**Comment by pllim** [comment]
I am surprised passing in the whole kernel object even worked in the first place, as matplotlib has no way to know our kernel API. Was it a happy accident that it used to work? Should we really be passing in `.array`? Is this a regression that Matplotlib needs to fix upstream?

https://github.com/astropy/astropy/blob/5ddd6a39a1228da7599e75a71f402b08588dbd67/astropy/convolution/kernels.py#L75-L78

Does this has anything to do with the plot directive working?

https://github.com/astropy/astropy/blob/5ddd6a39a1228da7599e75a71f402b08588dbd67/astropy/convolution/core.py#L169-L182

**Comment by pllim** [comment]
p.s. We cannot release with a broken doc build, so we either need to figure this out fast or pin maxversion of matplotlib for doc build for now.

p.p.s. Maybe @mhvk has insights into the `__array*` magicks?

**Comment by mhvk** [comment]
The `__array__` would certainly explain why it worked before - that is the standard way to define how one wants to be seen in an `np.array(kernel)` call. Given that wish for the kernel to be seen as array-like, adding `.ndim`, as tried in #13205, seems just be the right thing to do. So, if it works, I would go with that!

**Comment by WilliamJamieson** [comment]
Unfortunately, as noted in https://github.com/astropy/astropy/pull/13205#discussion_r864136424. Adding `.ndim` was not sufficient. It seems like `__array__` is no longer working for matplotlib in this case. Any suggestions?

**Comment by keflavich** [comment]
Can you point me to which doc is failing?  I'd think we could just `imshow(kernel.array)` in the docs and call it done, unless it's really important that the `__array__` magic works.

**Comment by WilliamJamieson** [comment]
> Can you point me to which doc is failing? I'd think we could just `imshow(kernel.array)` in the docs and call it done, unless it's really important that the `__array__` magic works.

https://github.com/astropy/astropy/blob/5ddd6a39a1228da7599e75a71f402b08588dbd67/astropy/convolution/kernels.py#L75-L78

and the similar portions of each of the other kernels.

**Comment by saimn** [comment]
I think this is due to https://github.com/matplotlib/matplotlib/pull/22141 (before that `_check_1d` was converting the input to a Numpy array with `np.atleast_1d(x)`). Probably worth a bug report.

**Comment by mhvk** [comment]
Agreed it is worth a bug report. They now check for `to_numpy()` - if a class has `__array__` that arguably should be used as well!

**Comment by WilliamJamieson** [comment]
Reopening so this can be tracked for an upstream fix.

**Comment by mhvk** [comment]
@WilliamJamieson - the difference from your minimal example and the real problem is, I think, that `Kernel` has a `.shape` defined and matplotlib sees this and treats the object as "sufficiently array-like"; without the shape, the object gets coerced to `ndarray`, and that works because of the `__array__` method.

**Comment by WilliamJamieson** [comment]
> @WilliamJamieson - the difference from your minimal example and the real problem is, I think, that `Kernel` has a `.shape` defined and matplotlib sees this and treats the object as "sufficiently array-like"; without the shape, the object gets coerced to `ndarray`, and that works because of the `__array__` method.

@mhvk you are exactly correct. See https://github.com/matplotlib/matplotlib/issues/22973#issuecomment-1117845296 where I just posted a better minimal reproducer. My above comment was me doing a first quick attempt.

**Comment by pllim** [comment]
OK if you want to track but given our pin in `setup.cfg`, this no longer blocks astropy v5.1. Thanks!
