### ISSUE TITLE
Structured column dtype not preserved in serialization

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#13231]
### Description

Round-tripping through ECSV or other formats does not consistently preserve the dtype of a structured column (#12644). The output after round-trip always has the structured column field names alphabetized.

I believe this is related to YAML alphabetizing the keys in a dict (mapping). I suspect that a change in the serialization format is going to be needed, perhaps using a list instead of mapping. Issue # ?? documents that using a field name of `name` breaks things.

cc: @mhvk

### Expected behavior

Dtype should be preserved.

### Steps to Reproduce

Code:

```python
import io
import numpy as np
from astropy.table import Table, Column
dtype = np.dtype([('z', 'f8'), ('x', 'f8'), ('y', 'i4')])
t = Table()
t['c'] = Column([(1, 2, 3), (4, 5, 6)], dtype=dtype)
out = io.StringIO()
t.write(out, format='ascii.ecsv')
print(out.getvalue())
t2 = Table.read(out.getvalue(), format='ascii.ecsv')

print(t['c'].dtype)
print(t2['c'].dtype)
```

Output:
```
# %ECSV 1.0
# ---
# datatype:
# - {name: c.z, datatype: float64}
# - {name: c.x, datatype: float64}
# - {name: c.y, datatype: int32}
# meta: !!omap
# - __serialized_columns__:
#     c:
#       __class__: astropy.table.column.Column
#       data: !astropy.table.SerializedColumn
#         x: !astropy.table.SerializedColumn {name: c.x}
#         y: !astropy.table.SerializedColumn {name: c.y}
#         z: !astropy.table.SerializedColumn {name: c.z}
# schema: astropy-2.0
c.z c.x c.y
1.0 2.0 3
4.0 5.0 6

[('z', '<f8'), ('x', '<f8'), ('y', '<i4')]
[('x', '<f8'), ('y', '<i4'), ('z', '<f8')]
```

### System Details

```
macOS-10.16-x86_64-i386-64bit
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ]
Numpy 1.22.2
pyerfa 2.0.0.1
astropy 5.1.dev956+g1d10de9d45.d20220422
Scipy 1.8.0
Matplotlib 3.5.1
```

**Comment by mhvk** [comment]
Damn, I thought I had covered that: the idea was that the list of columns in the serialized table would be the one that defined the correct order, but that clearly is not the case in your example.

The strange thing is that actually included structured `dtype` with non-alphabetical order on purpose in `io/tests/mixin_columns.py`. But taking just one of the columns from there also fails, though a bit differently:
```
from astropy.io.tests.mixin_columns import su
t['c'] = su
print(t)
out = io.StringIO()
t.write(out, format='ascii.ecsv')
print(out.getvalue())
t2 = Table.read(out.getvalue(), format='ascii.ecsv')
print(t['c'].dtype)
print(t2['c'].dtype)
```
yields
``c [i, f[p0, p1]]
----------------
 (1, (1.5, 1.6))
 (2, (2.5, 2.6))
# %ECSV 1.0
# ---
# datatype:
# - {name: c.i, datatype: int64}
# - {name: c.f.p0, datatype: float64}
# - {name: c.f.p1, datatype: float64}
# meta: !!omap
# - __serialized_columns__:
#     c:
#       __class__: astropy.table.column.Column
#       data: !astropy.table.SerializedColumn
#         f: !astropy.table.SerializedColumn
#           __class__: astropy.table.column.Column
#           data: !astropy.table.SerializedColumn
#             p0: !astropy.table.SerializedColumn {name: c.f.p0}
#             p1: !astropy.table.SerializedColumn {name: c.f.p1}
#         i: !astropy.table.SerializedColumn {name: c.i}
# schema: astropy-2.0
c.i c.f.p0 c.f.p1
1 1.5 1.6
2 2.5 2.6

[('i', '<i8'), ('f', [('p0', '<f8'), ('p1', '<f8')])]
[('f', [('p0', '<f8'), ('p1', '<f8')]), ('i', '<i8')]
```

So, here the output ascii is correct, since the order of the serialized columns is correct, but the order is lost in reading them back. In contrast, in your example the serialized table already has the wrong order.

**Comment by mhvk** [comment]
Sorry, I'm blind: the two problems are exactly the same: the generated `ecsv` files are actually OK in both cases, but something goes bad in reading them in.

**Comment by taldcroft** [comment]
@mhvk - In my example the order in the ECSV `datatype` list is indeed correct, but I don't think of that list as necessarily being an ordered list (or to put it another way, the order of the `datatype` list should not matter). The `__serialized_columns__` data structure should fully specify the table structure, and in my example that is wrong (alphabetized).

The problem in the nested structured column looks bad, but at least that is less likely to occur in the wild, and if it is really just a problem in reading would not be a release blocker. If we have to change the serialization format that could be a blocker.

**Comment by mhvk** [comment]
@taldcroft - my fix uses the order of the columns in the serialized table; the only way I can see of making the `__serialized_columns__` part give the right order is to make `SerializedColumn` be an `!!omap`, but that would be a more breaking change. (I guess the alternative would be to special-case structured columns, or give an explicit list of names, but that seems uglier.)

So, my logic would be that the information in `__serialized_columns__` is a yaml dict with order imposed only by the way the actual columns are stored in the serialized table.

**Comment by mhvk** [comment]
p.s. Note that it is already true that the serialized table determines the order of the columns in the final table; `__serialized_columns__` is sorted alphabetically.
