### ISSUE TITLE
Make object arrays containing Table

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13262]
### Description

Currently the following will error because ``astropy.table.Table`` cannot be put into a numpy array as an object.

```python
>>> import numpy as np
>>> from astropy.cosmology import Planck18
>>> np.array(Planck18.to_format("astropy.table"), dtype=object)
```

The specific error is
```python
raise ValueError('Datatype coercion is not allowed')
```

This makes sense for e.g. ``dtype=int``, but I would expect that any object can be embedded in a numpy array as an object.

So
``` python
>>> tbl = Planck18.to_format("astropy.table")
>>> np.array(tbl, dtype=object)[0] is tbl
True
```

**Comment by nstarman** [comment]
@mhvk, this turns out to be important for followup to #13104.

**Comment by eerovaher** [comment]
This is a duplicate of #12229 and is being worked on in #12743.
