### ISSUE TITLE
Add a ``fit`` method to models

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#1330]
I haven't checked through all the open modeling issues, but I think model classes should have a `fit` method (that would default to one of the fitters, but could also take an argument for the fitter to use). I think the following 'beginner' example could be made simpler if it looked like:

```
>>> g1 = models.Gaussian1DModel(10., stddev=2.1, mean=4.2)
>>> g1.fit(x, y)
```

**Comment by pllim** [comment]
Is this a duplicate of #979?

**Comment by astrofrog** [comment]
No I think they are a bit difference - this is saying models should have a fit method, whereas #979 (I think) is saying there should be a reference to the most recent fitter used.

**Comment by astrofrog** [comment]
Let's close this - we have way too many issues of 'let's keep open just in case' these days, and I agree with @eteq that we've settled on an accepted way to use the fitters.
