### ISSUE TITLE
Turn off automatic vrad to vopt conversion in astropy.io.fits

### ISSUE THREAD

**Issue by kmhess** [astropy/astropy#13307]
### Description

It appears that astropy.io.fits.getheader and astropy.io.fits.open automatically converts data cubes that have 'CTYPE3=VRAD' to 'VELO-HEL'.  It is not obvious that there is a flag or option to turn off this behavior.  This behavior is problematic if it is important but impossible to otherwise know what units the data cube is originally in.

For example, if there are data products created from a cube (say mom1 maps) outside of astropy, and the cube was in the radio convention, but astropy *ALWAYS* says the header of the original data cube is in the optical convention, then the velocities in the moment 1 map can be off my 100s to 1000s of km/s even at relatively low redshift if the wrong convention is assumed.

To solve this isssue, I think it would be best to add an option that allows the user to turn off the automatic conversion.  (In fact, I think "off" should be the default.)

Linked issues raised because it effects other (sometimes widely used) software:

* https://github.com/SoFiA-Admin/SoFiA-2/issues/80
* https://github.com/kmhess/SoFiA-image-pipeline/issues/49#issuecomment-1147260022

**Comment by pllim** [comment]
@keflavich , you deal with radio cubes a lot, right? Any advice here? Thanks!

**Comment by keflavich** [comment]
I fully agree that changing conventions is not acceptable, but I don't think I've seen this happen.  @kmhess can you provide an example?

**Comment by kmhess** [comment]
@keflavich @pllim I might have to apologize here.  I was under the misunderstanding that someone had given me a cube in VRAD.  Now we've checked with what ds9 does, and ds9 and astropy agree.  So, it looks like the majority of the problem may have to be with CARTA doing the conversion on the fly?! (I've added a screen shot below with CARTA on the left; astropy on the right).  However, there is one thing that I think astropy isn't getting right (and may be a common issue): the primary header says that there are three axes, even though CRPIX4, CRPVAL4 CDELT4, CTYPE4 are specified (but ds9 does this as well, so <shrug>). 
<img width="1579" alt="Screen Shot 2022-06-06 at 11 36 29" src="https://user-images.githubusercontent.com/14857798/172178455-c42dd5e8-5415-417b-a819-f78c825ac84f.png">

**Comment by keflavich** [comment]
CARTA does automatically convert units/conventions, but it does so based on user preferences and is configurable.

The presence or absence of CRPIX4, etc, does not imply anything about the shape of the data, just the WCS.  The NAXIS keywords specify the data shape, and they don't have to agree with the wcs shape.  usually disagreement will occur if there is a degenerate axis.

**Comment by pllim** [comment]
So, there is nothing to fix here?

**Comment by kmhess** [comment]
@keflavich Grumble.  Why convert at all?  But that's a discussion for another thread.  I apologize that CARTA's behavior led to my misplaced complaint here.  Sorry!  And yeah, the degenerate axis thing has always been a pain.

**Comment by keflavich** [comment]
The conversion can be convenient if you always want to open in velocity or always in frequency units, but I think CARTA's configuration system still needs more granularity.

Anyway, I'm closing this b/c we've agreed there's no change needed.

**Comment by kmhess** [comment]
@keflavich Even if some believe it's "convenient" for the spectral axes, CASA may still be doing the wrong thing with the spatial axes. https://github.com/CARTAvis/carta-frontend/issues/1877.
I agree it makes sense for the user to be allowed to control the (default) options while viewing the cube itself (in the viewer tool with animation in the desired coordinates for example), however if the header is displayed, it should be *the* header.  Anyway, I'll take this up with them.  Thanks!
