### ISSUE TITLE
wcslint crashes on valid WCS

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13303]
`wcslint` calls an underlying function here:

https://github.com/astropy/astropy/blob/8c0581fc68ca1f970d7f4e6c9ca9f2b9567d7b4c/astropy/wcs/wcs.py#L3430

Looks like all it does is tries to create a `WCS` object with the header and report warnings, so the bug is either inside `WCS` or it is a matter of updating on how validator calls `WCS` in more complicated cases:

https://github.com/astropy/astropy/blob/8c0581fc68ca1f970d7f4e6c9ca9f2b9567d7b4c/astropy/wcs/wcs.py#L3530-L3534

# Examples

File: https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HST/product/jbqf03gjq_flc.fits

```
$ fitsinfo jbqf03gjq_flc.fits
Filename: jbqf03gjq_flc.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     285   ()
  1  SCI           1 ImageHDU       241   (4096, 2048)   float32
  2  ERR           1 ImageHDU        53   (4096, 2048)   float32
  3  DQ            1 ImageHDU        45   (4096, 2048)   int16
  4  SCI           2 ImageHDU       256   (4096, 2048)   float32
  5  ERR           2 ImageHDU        53   (4096, 2048)   float32
  6  DQ            2 ImageHDU        45   (4096, 2048)   int16
  7  D2IMARR       1 ImageHDU        16   (64, 32)   float32
  8  D2IMARR       2 ImageHDU        16   (64, 32)   float32
  9  D2IMARR       3 ImageHDU        16   (64, 32)   float32
 10  D2IMARR       4 ImageHDU        16   (64, 32)   float32
 11  WCSDVARR      1 ImageHDU        16   (64, 32)   float32
 12  WCSDVARR      2 ImageHDU        16   (64, 32)   float32
 13  WCSDVARR      3 ImageHDU        16   (64, 32)   float32
 14  WCSDVARR      4 ImageHDU        16   (64, 32)   float32
 15  HDRLET        1 NonstandardExtHDU     18   (8640,)
 16  HDRLET        2 NonstandardExtHDU     26   (112320,)
 17  WCSCORR       1 BinTableHDU     59   14R x 24C   [40A, I, A, 24A, 24A, 24A, 24A, D, ...]
 18  HDRLET       18 NonstandardExtHDU     26   (112320,)
 19  HDRLET        4 NonstandardExtHDU     26   (112320,)

$ wcslint jbqf03gjq_flc.fits
python: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) ||
((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) &&
((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
```

File: https://github.com/astropy/astropy/blob/main/astropy/wcs/tests/data/tab-time-last-axis.fits

```
$ fitsinfo  tab-time-last-axis.fits
Filename: tab-time-last-axis.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      39   (1, 1, 1)   float64
  1  WCS-TABLE     1 BinTableHDU     13   1R x 1C   [128D]

$ wcslint  tab-time-last-axis.fits
  File ".../astropy/wcs/wcslint.py", line 18, in main
    print(wcs.validate(args.filename[0]))
  File ".../astropy/wcs/wcs.py", line 3531, in validate
    WCS(hdu.header,
  File ".../astropy/wcs/wcs.py", line 466, in __init__
    tmp_wcsprm = _wcs.Wcsprm(header=tmp_header_bytes, key=key,
ValueError: HDUList is required to retrieve -TAB coordinates and/or indices.
```

File:  https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HST/product/iabj01a2q_flc.fits 
(Reported by @mcara)

```
$ wcslint iabj01a2q_flc.fits
INFO:
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
python3(27402,0x118052dc0) malloc: Incorrect checksum for freed object 0x7ff48b84a800:
probably modified after being freed.
Corrupt value: 0x0
python3(27402,0x118052dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by mcara** [comment]
> `wcslint` calls an underlying function here:
> 
> https://github.com/astropy/astropy/blob/8c0581fc68ca1f970d7f4e6c9ca9f2b9567d7b4c/astropy/wcs/wcs.py#L3430
> 
> Looks like all it does is tries to create a `WCS` object with the header and report warnings, so the bug is either inside `WCS` or it is a matter of updating on how validator calls `WCS` in more complicated cases:
> 
> https://github.com/astropy/astropy/blob/8c0581fc68ca1f970d7f4e6c9ca9f2b9567d7b4c/astropy/wcs/wcs.py#L3530-L3534
> 
> # Examples
> File: https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HST/product/jbqf03gjq_flc.fits
> 
> ```
> $ fitsinfo jbqf03gjq_flc.fits
> Filename: jbqf03gjq_flc.fits
> No.    Name      Ver    Type      Cards   Dimensions   Format
>   0  PRIMARY       1 PrimaryHDU     285   ()
>   1  SCI           1 ImageHDU       241   (4096, 2048)   float32
>   2  ERR           1 ImageHDU        53   (4096, 2048)   float32
>   3  DQ            1 ImageHDU        45   (4096, 2048)   int16
>   4  SCI           2 ImageHDU       256   (4096, 2048)   float32
>   5  ERR           2 ImageHDU        53   (4096, 2048)   float32
>   6  DQ            2 ImageHDU        45   (4096, 2048)   int16
>   7  D2IMARR       1 ImageHDU        16   (64, 32)   float32
>   8  D2IMARR       2 ImageHDU        16   (64, 32)   float32
>   9  D2IMARR       3 ImageHDU        16   (64, 32)   float32
>  10  D2IMARR       4 ImageHDU        16   (64, 32)   float32
>  11  WCSDVARR      1 ImageHDU        16   (64, 32)   float32
>  12  WCSDVARR      2 ImageHDU        16   (64, 32)   float32
>  13  WCSDVARR      3 ImageHDU        16   (64, 32)   float32
>  14  WCSDVARR      4 ImageHDU        16   (64, 32)   float32
>  15  HDRLET        1 NonstandardExtHDU     18   (8640,)
>  16  HDRLET        2 NonstandardExtHDU     26   (112320,)
>  17  WCSCORR       1 BinTableHDU     59   14R x 24C   [40A, I, A, 24A, 24A, 24A, 24A, D, ...]
>  18  HDRLET       18 NonstandardExtHDU     26   (112320,)
>  19  HDRLET        4 NonstandardExtHDU     26   (112320,)
> 
> $ wcslint jbqf03gjq_flc.fits
> python: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) ||
> ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) &&
> ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
> Aborted
> ```
> 
> File: https://github.com/astropy/astropy/blob/main/astropy/wcs/tests/data/tab-time-last-axis.fits
> 
> ```
> $ fitsinfo  tab-time-last-axis.fits
> Filename: tab-time-last-axis.fits
> No.    Name      Ver    Type      Cards   Dimensions   Format
>   0  PRIMARY       1 PrimaryHDU      39   (1, 1, 1)   float64
>   1  WCS-TABLE     1 BinTableHDU     13   1R x 1C   [128D]
> 
> $ wcslint  tab-time-last-axis.fits
>   File ".../astropy/wcs/wcslint.py", line 18, in main
>     print(wcs.validate(args.filename[0]))
>   File ".../astropy/wcs/wcs.py", line 3531, in validate
>     WCS(hdu.header,
>   File ".../astropy/wcs/wcs.py", line 466, in __init__
>     tmp_wcsprm = _wcs.Wcsprm(header=tmp_header_bytes, key=key,
> ValueError: HDUList is required to retrieve -TAB coordinates and/or indices.
> ```
> 
> File: https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HST/product/iabj01a2q_flc.fits (Reported by @mcara)
> 
> ```
> $ wcslint iabj01a2q_flc.fits
> INFO:
>                 Inconsistent SIP distortion information is present in the FITS header and the WCS object:
>                 SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
>                 astropy.wcs is using the SIP distortion coefficients,
>                 therefore the coordinates calculated here might be incorrect.
> 
>                 If you do not want to apply the SIP distortion coefficients,
>                 please remove the SIP coefficients from the FITS header or the
>                 WCS object.  As an example, if the image is already distortion-corrected
>                 (e.g., drizzled) then distortion components should not apply and the SIP
>                 coefficients should be removed.
> 
>                 While the SIP distortion coefficients are being applied here, if that was indeed the intent,
>                 for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.
> 
>                  [astropy.wcs.wcs]
> python3(27402,0x118052dc0) malloc: Incorrect checksum for freed object 0x7ff48b84a800:
> probably modified after being freed.
> Corrupt value: 0x0
> python3(27402,0x118052dc0) malloc: *** set a breakpoint in malloc_error_break to debug
> Abort trap: 6
> ```

Nope. _That_ is the bug here:
```python
     WCS(hdu.header,  # should become:
     WCS(hdu.header, hdulist,
```

**Comment by pllim** [comment]
FWIW, my error for WFC3/UVIS with astropy 5.1 is slightly different:

```
$ wcslint iabj01a2q_flc.fits
corrupted size vs. prev_size
Aborted
```

**Comment by mcara** [comment]
Maybe things have changed: I used an old file lying around my file system while yours is likely a fresh baked one with some HAP stuff.

**Comment by mcara** [comment]
Try running `updatewcs.updatewcs(filename, use_db=False)` from `stwcs`.
