### ISSUE TITLE
remove private `_erfa` module

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13313]
Is there a reason we are keeping https://github.com/astropy/astropy/tree/main/astropy/_erfa around?

**Comment by pllim** [comment]
Looks like it is for backward compatibility:

https://github.com/astropy/astropy/blob/c1dd99af0436c2d7f09419bacfa8b03ad29821af/astropy/_erfa/__init__.py#L12

Since #10329 went into v4.2, maybe safe to remove it completely now unless @mhvk disagrees.

**Comment by mhvk** [comment]
Indeed, that should go!
