### ISSUE TITLE
BUG: inheritance diagram is cropped

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#13335]
e.g. for the astropy.time documentation, others may be affected, too. I see it for stable and latest, too and from two browsers.

<img width="788" alt="Screenshot 2022-06-14 at 16 56 50" src="https://user-images.githubusercontent.com/6788290/173708673-81a0a6b0-f978-42a3-b2d9-a866237ee98a.png">

**Comment by pllim** [comment]
Link at https://docs.astropy.org/en/latest/time/index.html#class-inheritance-diagram 

p.s. Oh no! 😱

**Comment by ayshih** [comment]
Ah, Astropy docs are being built with graphviz 2.43.0, which still has the bug

**Comment by ayshih** [comment]
I don't know.  Apparently SunPy docs are also being built with graphviz 2.43.0 on RTD, which explains sunpy/sunpy#5857

**Comment by pllim** [comment]
I asked RTD user support and will update if I hear anything back. 🤞

**Comment by pllim** [comment]
RTD wants to know how to update graphviz on Ubuntu. The distro seems to be grabbing v2 still and Graphviz doc doesn't say how.

**Comment by pllim** [comment]
Is it worth switching RTD build back to conda/mamba just so we can grab the latest graphviz?

https://docs.readthedocs.io/en/latest/guides/conda.html#making-builds-faster-with-mamba

**Comment by ayshih** [comment]
For SunPy, we have switched our RTD build back to conda to resolve this for our docs (sunpy/sunpy#6261)

**Comment by pllim** [comment]
I put this in the agenda to discuss at the next infrastructure tag-up. FYI.

**Comment by pllim** [comment]
@ayshih , this ended up being a fix in Sphinx, right? Can you please cross-link here? Thanks!

**Comment by pllim** [comment]
Oh wait... sorry, I got confused with the other issue. Nvm... 👀
