### ISSUE TITLE
ECSV fails to read null values

### ISSUE THREAD

**Issue by gregreen** [astropy/astropy#13331]
### Description

Loading an ECSV file with a float column that contains any "null" values results in an error: `ValueError: could not convert string to float: 'null'`.

This error is thrown at this line: https://github.com/astropy/astropy/blob/dd8ccdde27858d076b8dbb676364e520ca06f987/astropy/io/ascii/ecsv.py#L340

If you trace back the root of the error, it goes back to this line, where `numpy.array` does not convert "null" to a value (such as `numpy.nan`): https://github.com/astropy/astropy/blob/dd8ccdde27858d076b8dbb676364e520ca06f987/astropy/io/ascii/core.py#L1008

**Comment by dnelson86** [comment]
I fixed this with this beautiful hack, although I suggest something more robust:

```
    def generic_converter(vals):
        if numpy.issubdtype(numpy_type, numpy.integer):
            vals = ['-1' if v == 'null' else v for v in vals]
        else:
            vals = ['nan' if v == 'null' else v for v in vals]
        return numpy.array(vals, numpy_type)
```

**Comment by taldcroft** [comment]
The ECSV format is strictly defined to use an empty field `""` as the indicator of a null value. See  https://github.com/astropy/astropy-APEs/blob/main/APE6.rst#missing-values.

That said, it should actually be possible to read a file with `null` and treat those as missing values as follows. This is not in compliance with the ECSV standard but it can work:
```
>>> from astropy.table import Table

>>> !cat test.ecsv
# %ECSV 1.0
# ---
# datatype:
# - {name: a, datatype: int64}
# - {name: b, datatype: float64}
# - {name: c, datatype: string}
# schema: astropy-2.0
a b c
null 1.0 c
2 2.0 null
3 null e

>>> t = Table.read("test.ecsv", fill_values=[("", "0"), ("null", "0")])

>>> t
<Table length=3>
  a      b     c  
int64 float64 str1
----- ------- ----
   --     1.0    c
    2     2.0   --
    3      --    e
```

**Comment by taldcroft** [comment]
I'm going to mark this as `Close?` since the current behavior matches the expectation for the ECSV format.

**Comment by dnelson86** [comment]
Someone should tell the GAIA DR3 folks, since I believe their ECSV files were written by astropy (?), and thus should ideally be readable by astropy.

**Comment by taldcroft** [comment]
Interesting. Do you have any pointers to such files or information to track that down?

**Comment by taldcroft** [comment]
@mbtaylor - in your implementation of ECSV is there any support for `null` as a missing value indicator?

**Comment by dnelson86** [comment]
The official GAIA files are here: http://cdn.gea.esac.esa.int/Gaia/gdr3/gaia_source/

**Comment by taldcroft** [comment]
And now I see that the docs http://www.star.bris.ac.uk/~mbt/topcat/sun253/inEcsv.html specifically include an example of reading Gaia DR3 ECSV files, so `null` must be supported.

**Comment by taldcroft** [comment]
I'm not sure how the Gaia folks generated these files, but given this major use case out in the wild maybe it is time to formalize `null` in ECSV?

**Comment by taldcroft** [comment]
It's probably not too difficult in the astropy code to tell it to recognize `null` as a null marker for non-string columns. This is already the case for multidimensional array data.

**Comment by mbtaylor** [comment]
My guess is that those gaia files are standard CSV output from the database with a bespoke ECSV header slapped on top.  It is a bit embarrassing that this hasn't been noticed before now, given that:

* it's in violation of the ECSV standard
* reading them with astropy apparently doesn't work(?)
* reading them with stilts/topcat is about twice as slow as it should be
* string-valued columns contain the string "null" where they should have a missing value

So this looks very much like a mistake in the Gaia ECSV file generation. I doubt that those 10Tb of files will be regenerated, but they should at least try not to repeat the mistake next time round (even if the ECSV standard is updated, people may still be using older software).

Shall I file a bug report with the Gaia archive?

**Comment by mbtaylor** [comment]
I've got no objection to updating my parser implementation to recognise "null" as a missing-value marker for non-string columns.  Updating standards is always painful, but if somebody else does that it's OK by me :-).

**Comment by taldcroft** [comment]
Yes, please file a bug report with Gaia.

**Comment by taldcroft** [comment]
I'm having second thoughts about changing astropy. The code change to support allowing `null` for non-string columns is quite small, literally 3 lines. But it turns out that Gaia also uses `null` in string columns, so this fix doesn't really give the correct answer for the Gaia files anyway.

Since Gaia uses `null` exclusively, one can succesfully read these files using Astropy with:
```
t = Table.read("GaiaSource_000000-003111.csv", format='ascii.ecsv', fill_values=("null", "0"))
```
It's quite slow and memory-intensive but it works.

**Comment by taldcroft** [comment]
Even being an obvious advocate of ECSV, I am curious about the choice to write the entire 10 Tb DR3 archive in that format. This really wasn't the intended use case since reading FITS or HDF5 is at least 10 times faster.

**Comment by mbtaylor** [comment]
Although downloading all or much of the Gaia catalogue in flat files is not the generally recommended way to access it, there was a "a recurrent request from the Gaia user community" for this capability.  At DR1 FITS and VOTable were provided alongside CSV, but the cost of writing everything two or three times was considered too much with the later and much larger data releases.  At DR2 the data was in plain CSV; adding the ECSV headers was viewed as a low-cost way to provide metadata and the possibility for more efficient reading at EDR3 and DR3.

I don't know exactly why (E)CSV was chosen as the single output format, but presumably it's because, with all its faults, it can be read by pretty much everything (including human beings).  In particular it can be used as an input format for ingestion to many RDBMS, which is probably the main (sensible) reason that people have for wanting these bulk downloads.

**Comment by taldcroft** [comment]
@mbtaylor - thanks for that background, very helpful.

Would the Gaia folks be amenable to suggestions for documentation updates? I don't know the right contacts. I'd like to put the above workaround into the astropy docs somewhere and have them link to it (`To read these with astropy see [this documentation](URL)`), and also get them to have `ECSV` be a link to the APE-6 ECSV standard.

**Comment by taldcroft** [comment]
I was also thinking about special-casing this case in the ECSV reader, namely they have meta data with `TABLE: gaia_source` that could be used as a signal to enable `null` as the null marker for every column. This would basically be non-impacting for anything else, but it is admittedly a hack. But at least astropy would be able to read these files out of the box.

**Comment by mbtaylor** [comment]
Sure, if you post an update here when there's a documented workaround in Astropy, I can ask for it to be referenced from somewhere relevant in the Gaia archive docs.

It's up to you what if anything you do in the Astropy reader for these files, but switching on Gaia-specific metadata to interpret "null" as a null string is too hacky for me to stomach.  I may well make an update to look out for "null" in numeric columns, which will improve performance but not change behaviour for these files, but strings written "null" will still come out as "null" rather than blank or empty.  I expect that users can work out what's intended if they encounter such values.

**Comment by taldcroft** [comment]
Yeah, I actually wrote out the code for the hack (4 lines) and then didn't like it. I'll just work on a documentation update.

**Comment by mbtaylor** [comment]
I have reported this as DPAC JIRA ticket [C9GACS-869](https://issues.cosmos.esa.int/gaia/browse/C9GACS-869) (link provided for reference - only accessible to DPAC members).

**Comment by taldcroft** [comment]
See https://github.com/astropy/astropy/pull/14270.

**Comment by gregreen** [comment]
I think the best thing to do here is to document the workaround for Gaia DR3 in the Astropy documentation (as #14270 does), and then to make the Gaia DPAC aware of the issue for future releases, so that future releases are compliant with the ECSV standard (or avoid ECSV altogether, given its unsuitability for large datasets).

**Comment by enriqueutrilla** [comment]
After discussing this situation with @mbtaylor in the DPAC Jira, I can confirm that the Gaia bulk download files were generated using an internal tool, not with astropy. And I did try to follow the APE-6 ECSV standard, of course. There might be a misunderstanding in how it is to be applied, though.

As I saw it, the ECSV standard defines an empty string as a default representation for missing data, but doesn't make it mandatory. In particular, it states that "Specialized schemas may choose to use a different convention for missing (or masked) data", so I interpreted that to be optional, and that other markers could be used. 

At that moment, the Gaia Archive was already using ECSV as one of the formats to download data, and was generating "null" for the missing data. Also, the main reason to adopt ECSV in the bulk repository (which is basically a last resort option to access the data if everything else fails) was to have a format that didn't require dedicated tools to be read and that supported the encoding of arrays. The arrays in ECSV are encoded in JSON, which uses null for missing values, so again the consistency seemed to indicate that using "null" was a better option.

I did test the files that the tool generated against both astropy and Topcat, and in both cases they were successfully loaded (once astropy was setup with the `fill_values=("null", "0")` option described above). I took that as confirmation of them being valid ECSV files, in the same way as tab-, or semi-colon-separated files can be valid CSVs even if they require a bit of tweaking in the parser.

There was an issue with boolean columns that had "null" values in astropy 4.0.1.post1, but I did test it again with astropy 5.0.0 and it did work fine, so I took it for further confirmation that it vas possible to use such values and that the problem in 4.0 had been a bug in astropy.


I think that you should decide whether the empty string convention is mandatory or not in ECSV. 

- In the first case it should be clearly stated in the standard, and probably astropy (and maybe other tools such as TOPCAT) should enforce it somehow, e.g. raising an error, or at least a warning, if fill_values is set for an ECSV with anything else than an empty string. 

- In the second case, it would have to be decided how to best support other values. There is already a workaround by setting the `fill_values` argument. I agree that adding some ad-hoc fix based on the name of the table is a terrible idea. But maybe it would be possible to add an extra field in the column metadata indicating the proper fill_values for that column.
Even if it is finally allowed, if using `fill_values` has a large impact in performance and memory requirements, that might need to be documented somewhere. A previous comment mentioned that it did have a large performance impact, but I wasn't really expecting that.

Whatever you decide, we will try to adapt.

**Comment by taldcroft** [comment]
@enriqueutrilla - thanks for the detailed explanation, this is very helpful. First let me say I am very happy that the ECSV format has gained traction to the point where a major project like Gaia chose to distribute data this way. That was certainly the goal 8 years ago!

I agree the current spec for ECSV provides flexibility on the missing values marker but it doesn't provide the necessary infrastructure to readers to know what to expect. This is perhaps a good starting point for discussion on another update to the ECSV standard to be explicit about the missing values marker. With that, let's move discussion over to:

https://github.com/astropy/astropy-APEs/issues/81

**Comment by taldcroft** [comment]
About performance, I suspect that there won't be any performance difference between `""` and `null` if the missing marker is unambiguously specified.

**Comment by mbtaylor** [comment]
Yes, as long as I know what to expect there's no performance problem.

**Comment by eerovaher** [comment]
Does this affect only the bulk Gaia download file or does it also affect the ECSV files produced by the Gaia archive search interface?

**Comment by mbtaylor** [comment]
It's only the bulk downloads. The search interface produces ECSV using different software.

**Comment by mbtaylor** [comment]
FWIW I have updated my implementation to treat anything that doesn't look like a number in a numeric column (including "null" and "nan") the same, and treat it as a missing value. The "null" tokens in Gaia DR3 bulk downloads therefore won't cause any performance degradation (or unintended output) for future versions of TOPCAT/STILTS.  "null" tokens in string columns will still be read as "null" though.

If some future revision of ECSV provides a standard way to document magic missing value tokens, I expect I'll implement it (though personally I don't see a strong requirement for that).
