### ISSUE TITLE
VOTable reading runs into numpy-dev RuntimeError on float overflow

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#13341]
As found in https://github.com/astropy/astropy/issues/13332#issuecomment-1157720703, with numpy dev there are numerous errors - see  https://github.com/astropy/astropy/runs/6918680788?check_suite_focus=true

Those in `votable` boil down to trying to set a float array to `1.0E+45` (`tests/data/regression.xml`, l.181). There is no note for that entry, so I do not know if this is meant to overflow silently to infinity or not. If it is meant to happen, then the votable reader should be adjusted to use `with np.errstate(over='ignore')` in setting elements. If it is fine for the `RuntimeWarning` to be emitted, then the tests should be adjusted to ignore it.

**Comment by pllim** [comment]
That test file was added a looooong time ago, so I have no idea of the original intention. Since @tomdonaldson been working with votable tests most recently, maybe he has an idea which is the correct behavior. 🙏

**Comment by pllim** [comment]
Maybe ignoring it in tests is less controversial? See #13343
