### ISSUE TITLE
Documentation "Defining New Fitter Classes" (in astropy.modeling)

### ISSUE THREAD

**Issue by ycopin** [astropy/astropy#13426]
### Description

The `astropy.modeling` [Defining New Fitter Classes](https://docs.astropy.org/en/stable/modeling/new-fitter.html) example should be updated to match the latest changes:
* https://github.com/astropy/astropy/pull/12585 (2 functions were made public)
* https://github.com/astropy/astropy/pull/12051 `model_to_fit_params` now returns 3 values rather than 2

The last snippet should therefore be rewritten like:
```python
def __call__(self, model, x, y, x_sigma=None, y_sigma=None, **kwargs):
    model_copy = _validate_model(model,
                                 self._opt_method.supported_constraints)

    farg = _convert_input(x, y)
    farg = (model_copy, x_sigma, y_sigma) + farg
    p0, _, _ = model_to_fit_params(model_copy)

    fitparams, self.fit_info = self._opt_method(
        self.objective_function, p0, farg, **kwargs)
    fitter_to_model_params(model_copy, fitparams)

    return model_copy
```

**Comment by pllim** [comment]
cc @WilliamJamieson
