### ISSUE TITLE
QTable equality broken with numpy 1.23

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#13421]
### Description
When updating from numpy 1.22 to numpy 1.23, trying to test for equality with an empty and non-empty table rasies an error

### Expected behavior
`False` to be printed without error. With `numpy 1.22` this is the output:
```python
/Users/dstansby/mambaforge/envs/sunpy/lib/python3.10/site-packages/astropy/table/table.py:3474: FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
  result = self.as_array() == other
False
```

### Actual behavior
With `numpy 1.23`:
```python
Traceback (most recent call last):
  File "/Users/dstansby/github/sunpy/test.py", line 6, in <module>
    print(t1 == t2)
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.10/site-packages/astropy/table/table.py", line 3426, in __eq__
    return self._rows_equal(other)
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.10/site-packages/astropy/table/table.py", line 3474, in _rows_equal
    result = self.as_array() == other
TypeError: Cannot compare structured arrays unless they have a common dtype.  I.e. `np.result_type(arr1, arr2)` must be defined.
```

### Steps to Reproduce
```python
from astropy.table import QTable
import numpy as np

t1 = QTable([np.array([], dtype=float)], names=('a'))
t2 = QTable([np.array([1], dtype=float)], names=('b'))
print(t1 == t2)
```

### System Details

macOS-12.4-arm64-arm-64bit
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:42:03) [Clang 12.0.1 ]
Numpy 1.23.0
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.8.1
Matplotlib 3.5.2

**Comment by mhvk** [comment]
Hmm, I guess we have to put a try/except around that...  cc @taldcroft

**Comment by pllim** [comment]
Maybe this is what @larrybradley and @nden encountered too.

**Comment by dhomeier** [comment]
> Hmm, I guess we have to put a try/except around that... cc @taldcroft

Or explicitly test for matching shapes and dtypes first? What is actually the intended outcome for, say
```python
t1 = QTable([np.array([0], dtype=float)], names=('a'))
t2 = QTable([np.array([0], dtype=float), np.array([2])], names=('a', 'b'))
t1 == t2
```
?

**Comment by mhvk** [comment]
@dhomeier - this inconsistency is why numpy has been giving `FutureWarning` about just returning `False` for quite a while. I think they intend to eventually return a broadcast array of `False`. 

I'd argue for `try/except` just to keep the "normal" path fast (`try/except` is very cheap - indeed, free from python 3.11 onward)

**Comment by pllim** [comment]
> indeed, free from python 3.11 onward

Oh, really? I was told that "except" is expensive. Is that untrue now? 🤯

**Comment by dhomeier** [comment]
Yes, that is probably also the most reasonable result to expect for "row equality" (and the one everyone will be accustomed to now). But it will still require an extra check as long as we are supporting numpy versions that do not raise an error.
In contrast 1.23 also still allows
```python
np.array([0, 1]) == np.array([0, 1, 2])
<stdin>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
False
```
but I guess this will not occur here as only single rows are compared.

**Comment by taldcroft** [comment]
> Oh, really? I was told that "except" is expensive. 

Yes, if the `except` path is taken (exception gets raised) that is expensive, but the `try` is cheap.

**Comment by mhvk** [comment]
Indeed, it is the `try` part that goes from being cheap to being essentially free, so it pays to put the common path inside a `try/except` and have all the costs born by the uncommon path (or error).
