### ISSUE TITLE
Wrong shown version of Astropy

### ISSUE THREAD

**Issue by dutry** [astropy/astropy#13475]
### Description

The version of astropy shown is different with different command line. I have carefully checked the environment, and I think this might be a bug of Astropy. And it sometimes causes errors when other packages have dependence on Astropy.

I use the following command lines in Jupyter Notebook:
```python
>>> !pip show astropy
Name: astropy
Version: 5.1
Summary: Astronomy and astrophysics core library
Home-page: http://astropy.org/
Author: The Astropy Developers
Author-email: astropy.team@gmail.com
License: BSD 3-Clause License
Location: /home/duhc/anaconda3/lib/python3.9/site-packages
Requires: packaging, numpy, PyYAML, pyerfa
Required-by: sdss-marvin, photutils, mgefit, gwcs

>>> import astropy
>>> print(astropy.__version__)
>>> print(astropy.__path__)
4.3.1
['/home/duhc/anaconda3/lib/python3.9/site-packages/astropy']
```
 
### Expected & Actual behavior behavior

We can see, the address of the astropy shown are the same, both are in `/home/duhc/anaconda3/lib/python3.9/site-packages/`, while the version of the astropy is different, 5.1 vs 4.3.1. 

### System Details

Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-glibc2.17
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
Numpy 1.20.3
pyerfa 2.0.0
astropy 4.3.1
Scipy 1.7.1
Matplotlib 3.4.3

**Comment by FlyinTeller** [comment]
Also asked [on SO](https://stackoverflow.com/q/73076289/5012099)

**Comment by pllim** [comment]
Hello. I tend to agree with the SO assessment that this is more of a conda/pip not playing nice with each other rather than a packaging bug.

I also recommend people to not touch the `conda` `base` env but instead work off a created env that you can easily throw away and recreate as needed. I also recommend Miniconda over full Anaconda install (the latter comes with a lot of bloatware and also slow to update compared to `conda-forge` and PyPI).

**Comment by dutry** [comment]
@pllim 
Yes. I have checked that the problem is from the Astropy version embedded in Anaconda, when I use Miniconda instead problem will be solved.

**Comment by pllim** [comment]
Glad you found the cause and thanks for reporting back, @dutry !
