### ISSUE TITLE
Incorrect behavior in vectorized `wcs.world_to_pixel()` with TPV

### ISSUE THREAD

**Issue by pkgw** [astropy/astropy#13509]
### Description

The `wcs.world_to_pixel()` function can give incorrect results when run in vectorized mode with TPV.

### Expected behavior

Results from vectorized mode are the same as in scalar mode.

### Actual behavior

In my vectorized test case, outputs are mostly bogus.

### Steps to Reproduce

Here is a reproduction case — apologies for the length:

```python
from astropy.coordinates import SkyCoord
from astropy import units as u
from astropy.wcs import WCS
import numpy as np

# Create a WCS with a base TAN projection
hdr = {
    "WCSAXES": 2,
    "CRPIX1": 9019.3448,
    "CRPIX2": 9822.9018,
    "PC1_1": -0.00116096,
    "PC1_2": 0.000330426,
    "PC2_1": 0.000330397,
    "PC2_2": 0.00116203,
    "CDELT1": 1.0,
    "CDELT2": 1.0,
    "CUNIT1": "deg",
    "CUNIT2": "deg",
    "CTYPE1": "RA---TAN",
    "CTYPE2": "DEC--TAN",
    "CRVAL1": 337.103834,
    "CRVAL2": 90.0,
    "EQUINOX": 2000.0,
}
wcs_tan = WCS(hdr)

# Create a WCS with TPV distortion terms
hdr.update(
    **{
        "CTYPE1": "RA---TPV",
        "CTYPE2": "DEC--TPV",
        "PV1_0": -0.004862344579,
        "PV1_1": 0.9988506351,
        "PV1_2": 0.0003631415552,
        "PV1_4": -0.000151807543,
        "PV1_5": 0.0003264940806,
        "PV1_6": 1.054162749e-05,
        "PV1_7": 3.71399551e-05,
        "PV1_8": -4.673290603e-06,
        "PV1_9": -8.221049725e-06,
        "PV1_10": -2.048430933e-05,
        "PV1_12": 3.850243018e-06,
        "PV1_13": -3.850788487e-06,
        "PV1_14": -4.402412681e-07,
        "PV1_15": -1.261618912e-06,
        "PV1_16": -3.483007815e-07,
        "PV1_17": -2.971533523e-07,
        "PV1_18": 1.807889219e-07,
        "PV1_19": -2.141983906e-07,
        "PV1_20": 1.168331168e-07,
        "PV1_21": 1.762917378e-07,
        "PV1_22": 1.134792701e-07,
        "PV2_0": -0.005101922485,
        "PV2_1": 1.000314578,
        "PV2_2": 0.0009117987251,
        "PV2_4": 5.178903105e-05,
        "PV2_5": -0.0001677371386,
        "PV2_6": 0.0003132549032,
        "PV2_7": -1.196471938e-05,
        "PV2_8": -2.031118482e-05,
        "PV2_9": 1.334272569e-05,
        "PV2_10": -1.92055231e-05,
        "PV2_12": -3.595935319e-07,
        "PV2_13": 1.634133749e-07,
        "PV2_14": -1.36746203e-06,
        "PV2_15": 1.684772597e-06,
        "PV2_16": -3.050997407e-06,
        "PV2_17": 8.867628883e-08,
        "PV2_18": 1.641951829e-07,
        "PV2_19": -6.17124982e-08,
        "PV2_20": -2.511534806e-08,
        "PV2_21": -5.634176609e-08,
        "PV2_22": 1.882567755e-07,
    }
)
wcs_tpv = WCS(hdr)

# Vector of lats and lons that demonstrate the problem
lats = np.linspace(1.0453819570955787, 1.2938789521827248, 256)
lons = np.linspace(3.7637488459848645, 4.709526042452718, 256)
INDEX = 230

def do_scalar(wcs):
    "Calculate the pixel coordinate of a particular position with scalar evaluation"
    c = SkyCoord(lons[INDEX] * u.rad, lats[INDEX] * u.rad, frame="icrs")
    idx = wcs.world_to_pixel(c)
    return (idx[0].item(), idx[1].item())

def do_vector(wcs):
    "Calculate the pixel coordinate of a particular pixel with vector evaluation"
    c = SkyCoord(lons * u.rad, lats * u.rad, frame="icrs")
    idx = wcs.world_to_pixel(c)
    return (idx[0][INDEX], idx[1][INDEX])

# Without distortions, results are consistent as you would hope:
print("TAN scalar:", do_scalar(wcs_tan))
print("TAN vector:", do_vector(wcs_tan))

# With distortions, results are not consistent:
print("TPV scalar:", do_scalar(wcs_tpv))
print("TPV vector:", do_vector(wcs_tpv))
```

Comparing the result of `wcs.world_to_pixel()` for the scalar versus vector inputs here, it looks like the 0'th element of the array is correct, but the rest are garbage. So, perhaps something is trying to vectorize but not actually initializing anything past the 0'th element?

**Update:** If I run the test repeatedly, the results from the vector-TPV case vary, although they are always around -1. So there is probably some uninitialized memory being read here.

### System Details

```
Linux-5.18.13-200.fc36.x86_64-x86_64-with-glibc2.35
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
Numpy 1.23.1
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.8.1
Matplotlib 3.5.2
```

CC @imbasimba

**Comment by pkgw** [comment]
CC @astrofrog FYI, this is causing `reproject` to give me images that are half NaNs (when they shouldn't be).

**Comment by pllim** [comment]
@pkgw , is there a reproject issue you can link to this issue? Thanks!

**Comment by pkgw** [comment]
@pllim I haven't created one, but can do so if you think that would be appropriate. The underlying issue definitely lives at this layer, but it does lead to incorrect reproject behavior.

**Comment by pllim** [comment]
If there is a specific use case reproject can add to their test suite, it would prevent regression if they also test against astropy dev.

**Comment by mcara** [comment]
I do not believe this is a bug in the software. The issue is rather with your simulation.

```python
    "CRVAL1": 337.103834,
    "CRVAL2": 90.0,
```

but your `lons` range from 215 to 270 _degrees_ and `lats` range from 60 to 74 _degrees_. First this is a very wide range of angles and second min/max values of the ranges are far away from defined CRVALx. One cannot expect [iterative inversion of] distortion models to work this far away from the center of the projection.

Try the following `lons` and `lats` instead:
```python
lats = np.deg2rad(wcs_tan.wcs.crval[1]) - 0.01 * np.linspace(1.0453819570955787, 1.2938789521827248, 256)
lons = np.deg2rad(wcs_tan.wcs.crval[0]) + 0.01 * np.linspace(3.7637488459848645, 4.709526042452718, 256)
```

**Comment by pkgw** [comment]
@mcara Those values are actually relevant to my application; it's a huge photographic plate image. The thing that signifies that this is a bug is that the scalar calculation does work; something about the vectorized version fails. As noted above, it looks like there is some uninitialized memory happening, so I bet that the vectorized code path is somehow not incrementing an index properly or something.

**Comment by mcara** [comment]
You are right. I thought about it (initially) and then by the time I investigated this, I forgot about scalars apparently working. However, there are a couple of issues to consider. First, TPV distortions are not handled by the `astropy` and instead are handled by `WCSLIB`. Second, if there was a bug in indexing within `astropy` hopefully (but there is no guarantee when dealing with memory corruption) we would have seen similar errors for pure TAN.

What you call "works" (for the scalar), it actually works only for _some_ scalars. Try different values of `NPIX` and even though you will not see crazy values, you will get this:

```
python
In [47]: np.rad2deg(lons[:3]), np.rad2deg(lats[:3])
Out[47]:
(array([215.64692402, 215.85943007, 216.07193611]),
 array([59.89597412, 59.95180874, 60.00764337]))

In [48]: wcs_tpv.wcs_pix2world(*wcs_tpv.wcs_world2pix(np.rad2deg(lons[:3]), np.rad2deg(lats[:3]),  0), 0)
Out[48]:
[array([194.97059075, 183.64970819, 183.65008595]),
 array([72.20751313, 74.31158788, 74.31156536])]
```
(in the above example, I simplified things a little and avoided using `SkyCoord` objects, units, and our own iterative solution `all_world2pix` - instead I call directly WCSLIB's function). As you can see the coordinates do not round-trip.

Now, I would like to suggest you try reverting `lons` and `lats` arrays:
```python
wcs_tpv.wcs_world2pix(np.rad2deg(lons[::-1]), np.rad2deg(lats[::-1]),  0)
```
You will see that good values are at the top. So, maybe this is how WCSLIB handles the case when it encounters bad convergence: it just quits computing the rest of the values.

**Comment by mcara** [comment]
I am still looking at how we handle return values from `wcss2p` and I will report back.

**Comment by mcara** [comment]
> Update: If I run the test repeatedly, the results from the vector-TPV case vary, although they are always around -1. So there is probably some uninitialized memory being read here.

You are right. I also re-run this and can confirm this random behavior. I also did some superficial debugging and all results coming from `wcss2p` have `stat` flags set to 0 indicating all values are valid. This essentially avoids our code that sets return values to NaNs if `stat!=0` (indicating that errors have occurred). This indicates that the values that you are seeing are coming directly from WCSLIB "as is". With 99.99% confidence level I believe this is a bug in the WCSLIB, specifically in the `disx2p()` function.

You should report this directly to Mark Calabretta unless you would like me to do that.

Also, please ignore my previous comment - results from reversing the arrays were just as random as not reversing them.

**Comment by pkgw** [comment]
Thanks for digging into this! I'll see if I can create a pure-WCSLIB reproduction case and report it to Mark if so. In the meantime I'd advocate for keeping this issue open until we retire that last 0.01% of uncertainty about where the bug lies. I'll post follow-up comments as I dig in.

**Comment by mcara** [comment]
@pkgw Thank you! I agree with keeping this open.

**Comment by pkgw** [comment]
Noting for posterity: I sent Mark an email about this, CC'ing @mcara.
