### ISSUE TITLE
Ellipse2D() only fitting amplitude

### ISSUE THREAD

**Issue by jegpeek** [astropy/astropy#13505]
### Description

When I fit a simple ellipse with models.fitting it will fit the amplitude, but none of the other parameters in Ellipse2D()

### Expected behavior

It would fit all the parameters!

### Actual behavior

It successfully ran, but only fit the ellipse amplitude. It does seem to do an OK job at that.

### Steps to Reproduce

```
import numpy as np
import matplotlib.pyplot as plt
from astropy.modeling import models, fitting
from astropy.modeling.models import Ellipse2D

#make some random ellipse
e = Ellipse2D(amplitude=100., x_0=20, y_0=30, a=12, b=18,
              theta=0.2)
y, x = np.mgrid[0:50, 0:50]
#add some noise 
emap = e(x, y)+np.random.random([50,50])*100

#fit 
fit = fitting.LevMarLSQFitter()

# initialize a linear model
ellip_init = models.Ellipse2D()
e_init = Ellipse2D(amplitude=1200., x_0=20, y_0=30, a=200, b=900,
              theta=2)

# fit the data with the fitter
fitted_ellip = fit(e_init, x, y, emap)

fitted_ellip
```

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ]
Numpy 1.22.4
pyerfa 2.0.0
astropy 5.1
Scipy 1.7.3
Matplotlib 3.5.2

**Comment by pllim** [comment]
@WilliamJamieson , are you able to advise? Thanks!

**Comment by jegpeek** [comment]
@eteq gave me some comments on this -- he believes it has to do with the mathematical architecture of the problem itself, not astropy. Please stand by while I test his method and then we/you can decide whether to just close this or add some documentation or what?

**Comment by pllim** [comment]
@jegpeek , any update on this? I am marking this as stale since it is not sure what we need to fix here. Thanks!
