### ISSUE TITLE
`CompoundModel` sub-model `setattr` issue

### ISSUE THREAD

**Issue by robelgeda** [astropy/astropy#13534]
### Description

If you add a model to itself and make a new `CompoundModel`, `CompoundModel` does not seem to make copies of the input models before it "combines" them. This is because when you use:

```
setattr(compound_model, param_name, new_value)
```

The param for both models is changed for both instances of the sub-models even if they have different names (i.e "param_name_0" and "param_name_1"). 

### Expected behavior

Setting one param should not cause another to change. 

### Actual behavior

Setting one param in a compound model causes duplicated sub-models to change their params 

### Steps to Reproduce

```
from astropy.modeling import models

model = models.Gaussian1D()
compound_model = model + model
setattr(compound_model, 'mean_0', 10)
```

This will cause both `mean_0` and  `mean_1` to equal `10` though they were initialized to 0!

Please note that even doing the following is not exempt from this error, indicating the issue is not with the `setattr` call

```
compound_model.mean_0 = 10
```

### System Details

```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:06:46) [GCC 10.3.0]
Numpy 1.23.1
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.9.0
Matplotlib 3.5.2
```

**Comment by pllim** [comment]
@WilliamJamieson , any advice? Thanks!

**Comment by WilliamJamieson** [comment]
This is to be expected. Compound model does not copy the inputs.

**Comment by pllim** [comment]
Is this expectation documented though? Can the documentation be improved?

**Comment by robelgeda** [comment]
The thing that is very odd about this issue is that the fitter can set the values independently but the user cannot as mentioned above.

@WilliamJamieson in that case there should be a warning in the operation functions, for example like:

```
def __add__(self, new_model):
    if new_model in self.sub_models:
        warn(".....")
```
 If this is too much of a headache, the warning should actually be an exception (though such exceptions tend to cause more unforeseen harm than good).

**Comment by robelgeda** [comment]
wait this is even more of a problem, in the example above, ie:
```
from astropy.modeling import models

model = models.Gaussian1D()
compound_model = model + model
setattr(compound_model, 'mean_0', 10)
```

`model` also has its values changed! This is not expected behavior. I guess the main point of this ticket is if compound models should copy their inputs?

I would say yes, they should because I have no reason to expect my initial model to be affected by what happens to the compound model. For example if I wanted to compare a model and another compound model with an extra component, this would be an issue. Also the fact that the none-linear fitters can change the values without causing this means that this is not a consistent behavior that can be documented reliably (or at least needs more investigation as to why there is a preference)

**Comment by WilliamJamieson** [comment]
Note I'm traveling and will not have direct access to a computer until Monday.

The behavior you are describing is exactly what is expected. CompoundModel is a container for two models that facilities some binary operation between those models. Applying the operation between two models simply calls the constructor for a CompoundModel with the correct operator described. Since Python passes by reference, this means that the model(s) contained in the CompoundModel are the model outside. You can see this if you check the id of the models and the component models. Indeed, if you were to say stick the models instead in a list or dictionary instead of a CompoundModel object you would expect the exact behavior your seeing from Python. Note the "parameters" of the CompoundModel are essentially pointers at parameters of the constituent models. 

Adding warnings/errors to this process will break things like GWCS, which deals with many models put together using CompoundModel.

Again, since this is normal Python behavior I don't see a strong need to document this; however, I am not opposed to adding documentation for this.

**Comment by robelgeda** [comment]
Thanks for taking the time to reply @WilliamJamieson and we can continue on Monday! Before I log off for the day here are some thoughts...

>The behavior you are describing is exactly what is expected

As a software engineer, I see why you say this is expected (since we are dealing with pointers); but as a user, I find that this is neither trivial nor very helpful. If we are going to stick with this I think we really need to make it clear that `CompoundModel` is not supposed to be a model but an operation facilitator that behaves like a model. 

I can see this being confusing because In the [basics section](https://docs.astropy.org/en/stable/modeling/compound-models.html#basics) of the documentation it says the following:

> an additional way to create **new models** is by combining them using arithmetic expressions. 

> The resulting object g1_plus_2 is itself a **new model**.

These **new model**s need further clarification (as a matter of fact I dont think we define what a `CompoundModel` is). The only thing we have in there that hints at this is 

>  An expression involving two or more compound models results in a new expression that is the concatenation of all involved models’ expressions:

My recommendation is that we add a `important` or `Warning` directive explicitly saying that changes to the compound model parameters lead to changes to parameters in the models that are used to initiate it. And of course define what a `CompoundModel` is in the context you provided.

**Comment by WilliamJamieson** [comment]
This was all documented in the v4.0 release docs, found here: https://docs.astropy.org/en/v4.0/modeling/changes_for_4.html#modeling-major-changes-for-4-0.
