### ISSUE TITLE
Better documentation of `maxiter` parameter in non-linear fitters

### ISSUE THREAD

**Issue by tkillestein** [astropy/astropy#13540]
### Description

For fitters like `LMLSQFitter` inheriting from the `_NonLinearLSQFitter` class, it'd be great if we could improve the documentation to point out the `maxiter`, `acc`, and `epsilon` parameters are exposed when these are called. After some searching through the source code I worked this out, but I couldn't find any references to this in the documentation. Happy to write something for this but unsure about where in the codebase to write it.

**Comment by pllim** [comment]
Thanks for reporting this. Where would *you* try to look for this info in the first place? That would be the best place to start, but maybe @WilliamJamieson can advise as well.

**Comment by WilliamJamieson** [comment]
These are documented right here: https://github.com/astropy/astropy/blob/f4615bfafafa4bf75dd4a6b52de1695c1b9f8ea2/astropy/modeling/fitting.py#L1204-L1236

However, it appears the documentation for `__call__` from `_NonLinearLSQFitter` is not being displayed in the astropy docs for [`LMLSQFitter`](https://docs.astropy.org/en/latest/api/astropy.modeling.fitting.LMLSQFitter.html#astropy.modeling.fitting.LMLSQFitter). Even though it is being displayed for other fitters such as [`SimplexLSQFitter`](https://docs.astropy.org/en/latest/api/astropy.modeling.fitting.SimplexLSQFitter.html#astropy.modeling.fitting.SimplexLSQFitter).

@pllim is there a way to fix the documentation generation to incorporate this?

**Comment by pllim** [comment]
I didn't write the modeling doc stuff, so I don't know on top of my head, sorry. See what is the other fitters doing that this one isn't. Maybe it is excluded because of its "hidden" status with the leading underscore?

**Comment by WilliamJamieson** [comment]
The other fitters define their `__call__` methods directly within their classes rather than within the parent class.
