### ISSUE TITLE
astropy.utils.iers.iers.IERSRangeError: (some) times are outside of range covered by IERS table.

### ISSUE THREAD

**Issue by michealroberts** [astropy/astropy#13550]
### Description

I'm hoping this is a rather simple bug, but I can't seem to reference a specific fix for this.

I am seeing the following warnings in a stack trace:

```
WARNING: CacheMissingWarning: Remote data cache could not be accessed due to OSError: [Errno 30] Read-only file system: '/.astropy' [astropy.utils.data]
WARNING: CacheMissingWarning: Not clearing data cache - cache inaccessible due to OSError: [Errno 30] Read-only file system: '/.astropy' [astropy.utils.data]
WARNING: failed to download ftp://anonymous:mail%40astropy.org@gdc.cddis.eosdis.nasa.gov/pub/products/iers/finals2000A.all and https://datacenter.iers.org/data/9/finals2000A.all, using local IERS-B: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/usr/src/app'] [astropy.utils.iers.iers]
```

Which I believe is then leading to this error:

```
raise IERSRangeError('(some) times are outside of range covered '
astropy.utils.iers.iers.IERSRangeError: (some) times are outside of range covered by IERS table.
```

The working directory of my app is: `/usr/src/app`

So I am wondering what specific directory I can add to this application that will provide a usable temporary directory to this writable section of a containerised application, and what that name should be? Maybe just tmp?

**Comment by pllim** [comment]
`Read-only file system: '/.astropy'` is the main problem here. Please see https://docs.astropy.org/en/stable/config/index.html on how to change the default to point to a place you have write access to.
