### ISSUE TITLE
from astroquery.mast import Observations hangs in Jupyter Notebook

### ISSUE THREAD

**Issue by craiganderson-53546** [astropy/astropy#13563]
I am following a JWST data access tutorial ([here](https://github.com/Kappibw/JWST/blob/main/1_accessing_jwst_data.ipynb)). The first step is to import astropy and astroquery, which appear to succeed. But when I try to reference astroquery.Observations it cannot find the module. When I do the imports from python 3.7 command line the astroquery import works but it also downloads Leap_Seconds.dat which is unexpected. I know it worked because there is no error from the import and I can reference Observations in the next steps. 

The actual execution appears below. Any idea why this behavior exists? How can I get around it?

```
>>> from astroquery.mast import Observations 
Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat |===========================================| 1.3k/1.3k (100.00%) 0s
```

Versions:

- Python 3.7.7 
- astropy 4.0.1.post1 
- astroquery 0.4.6

**Comment by pllim** [comment]
There are several problems here:

1. The tutorial is not an official source supported by STScI. Please follow official tutorials. If you have trouble finding them, please contact `jwsthelp.stsci.edu`.
2. `astropy` has dropped support Python 3.7. Please use a newer Python and also install the latest release of `astropy`.

Not sure if there is anything for us to fix here.

**Comment by eerovaher** [comment]
@craiganderson-53546, it sounds like you have multiple virtual environments, and the one you are trying to follow the tutorial in has an outdated version of `astroquery` installed.

The purpose of downloading the leap second data is described [here](https://docs.astropy.org/en/stable/utils/iers.html).
