### ISSUE TITLE
Astropy table with 2 headers export to pandas

### ISSUE THREAD

**Issue by dan-adi** [astropy/astropy#13566]
I made a simple query using Astroquery, and the table result has 2 headers(one with parameter names, second with units).
When I use table.to_pandas(), the second header in the table is not displayed.
I've tried table.to_pandas(header = [0,1]) but it doesn't work. 
Any suggestions?

**Comment by eerovaher** [comment]
[`Table.to_pandas()`](https://docs.astropy.org/en/stable/api/astropy.table.Table.html#astropy.table.Table.to_pandas) has no `header` argument, so it shouldn't be surprising your attempt didn't work. Have you read the documentation about [Interfacing with the Pandas Package](https://docs.astropy.org/en/stable/table/pandas.html)? If you have read the documentation and still think there is a bug then you will have to post a minimal code example that reproduces it along with the `astropy` version you are using.

**Comment by dan-adi** [comment]
I see, so if the table has 2 headers, I can't export the second header. I'll find a work around. Thanks eerovaher
