### ISSUE TITLE
Incorrect GCRS Docstring

### ISSUE THREAD

**Issue by stephenHartzell** [astropy/astropy#13591]
### Description

I believe the docstring for https://github.com/astropy/astropy/blob/main/astropy/coordinates/builtin_frames/gcrs.py is incorrect. I think it should say "GCRS is distinct form _BCRS_" rather than what is says now:  "GCRS is distinct form _ITRS_"

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by eerovaher** [comment]
This is the docstring in question:
https://github.com/astropy/astropy/blob/8d49de97158c32b69aef95cfbaf301b54593755e/astropy/coordinates/builtin_frames/gcrs.py#L36-L46
There is no mention of ITRS, instead the difference between GCRS and ICRS is discussed. Page 19 of the USNO Circular 179 referenced in the docstring says this:
> The ICRS is itself a specific example of a Barycentric Celestial Reference System, in-
corporating the relativistic metric specified in res. B1.3 of 2000 for solar system barycen-
tric coordinate systems. In other words, the ICRS provides the orientation of the BCRS
axes.

And page 4 includes the following:
> The spatial orientation of the GCRS is derived from that of the BCRS, that is, unless otherwise stated, by the orientation of the ICRS.

There does not seem to be any reason to edit the docstring.
