### ISSUE TITLE
No writer defined for format 'fits' and class 'NoneType'.

### ISSUE THREAD

**Issue by noob-tubem** [astropy/astropy#13618]
### Description

When trying to write a fits table, I am given the above error. The full message is:

```
>>> t = table.Table.write('TEST.fits', format='fits')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/(path)/tools/miniconda3/lib/python3.7/site-packages/astropy/table/connect.py", line 113, in __call__
    registry.write(instance, *args, **kwargs)
  File "/(path)/tools/miniconda3/lib/python3.7/site-packages/astropy/io/registry.py", line 565, in write
    writer = get_writer(format, data.__class__)
  File "/(path)/tools/miniconda3/lib/python3.7/site-packages/astropy/io/registry.py", line 483, in get_writer
    data_format, data_class.__name__, format_table_str))
astropy.io.registry.IORegistryError: No writer defined for format 'fits' and class 'NoneType'.

The available formats are:

Format Read Write Auto-identify
------ ---- ----- -------------
>>>
```

I
### Expected behavior

I expect a fits table to be written with the name I specified

### Actual behavior
Nothing happens aside from the error above.

### Steps to Reproduce
```python
>>> from astropy import table
>>> t = table.Table.read('filename.fits')
>>> z = [0]*2672
>>> c = table.Column(z, name = 'CORR')
>>> t.add_column(c, index = 15)
>>> t = table.Table.write('TEST.fits', format = 'fits')
```

### System Details

>>> import platform; print(platform.platform())
Linux-4.18.0-372.16.1.el8_6.x86_64-x86_64-with-redhat-8.6-Ootpa

>>> import sys; print("Python", sys.version)
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0]

>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.21.5

>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.1

>>> import astropy; print("astropy", astropy.__version__)
astropy 4.0

>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.3.0

>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.1.0
>>>

**Comment by eerovaher** [comment]
`Table.write()` is an instance method, so you would have to call it as
```python
>>> t.write('TEST.fits')
```
See also the [documentation about the Unified I/O Interface](https://docs.astropy.org/en/stable/io/unified.html).
