### ISSUE TITLE
Decide how to handle Python 3.11 table test failure

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#13637]
The [Python 3.11 failure in `test_pprint`](https://github.com/astropy/astropy/pull/13614#issuecomment-1241974434) is apparently due to a change in behavior for `OrderedDict.pop()` (presumably https://github.com/python/cpython/pull/27530). Prior to 3.11 this ends up calling the subclass `__delitem__`. With 3.11 this is no longer the case.
```
class mydict(OrderedDict):
    def __delitem__(self, key):
        print(f"Deleting {key}")
        super().__delitem__(key)


d = mydict()
d["a"] = 1
print(d.pop("a"))
```
In 3.11 this prints only `1` while in 3.8 you also see `Deleting a`.

There are a couple of ways to deal with this.
1. Change relevant instances of `t.columns.pop(key)` to `del t.columns[key]`. In those cases the popped value is not being used anyway so `pop` wasn't really needed.
2. Change the behavior of `pprint_include/exclude_names` so that when if a column is deleted then the include/exclude sets are NOT modified. Some people might consider the current behavior as an unexpected side effect of deleting a column. Changing this behavior would allow removing the [`Columns` class `__delitem__` method](https://github.com/astropy/astropy/blob/5b6619a6ea3428de71a628e6924038b1a872dfd4/astropy/table/table.py#L298) which exists only to handle the `pprint_include/exclude` names.

There are pros/cons for each strategy and I'm on the fence. Thoughts @mhvk or @nstarman ?

**Comment by mhvk** [comment]
I think 3.11 is not out yet, correct? I think they may well want to know about this regression! To me, it certainly seems a bit odd that `__delitem__` is not called when you are `pop`ing something!

As for our own choices, I'd tend to try to keep our behaviour the same: it does seem logical to me that `Table` ensures its include/exclude sets always only contain columns that actually exist. In a way, I see them as something that is almost a property o fhe column, whether to be shown or not (perhaps because you once had it as such!).

**Comment by mhvk** [comment]
I added a quick note to https://github.com/astropy/astropy/issues/13637. May need something more explicit. On the other hand, if `dict` does not do the same, I guess that also means we could not actually move to using `dict` here, so from that perspective perhaps we need to explicitly delete anyway.

**Comment by taldcroft** [comment]
> it does seem logical to me that Table ensures its include/exclude sets always only contain columns that actually exist

Just a point on this is that we purposely didn't enforce a strict connection between the include/exclude sets and columns, and in fact there is no column.info attribute that describes if a column is included or excluded. A key use case is a Table subclass that may initialize the include/exclude sets in `__init__` before any columns exist. In that context this is really a behavior of the Table rather than individual columns.

So in such a case if a Table subclass is set to ignore the `flubber` column, the user might be surprised if they delete and then add-back the column and it starts showing up. And then you start worrying about implementation details like whether the code below will ever call `__delitem__`:
```
# Assume flubber column already exists
t['flubber'] = new_flubber_data
```

**Comment by mhvk** [comment]
Ah, yes, your example of a class with, say, resultts from intermediate calculations makes sense.  And  I wondered about column overrides too...  My tendency might still be to try to stick to the same behaviour as we had, but now quite a bit less obviously...
