### ISSUE TITLE
Table.read('file.fits', format='ascii') does not raise under Python 3.11

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#13670]
### Description
For certain FITS BINTABLE files, with Python 3.11.0rc2 a forced attempt to read them with `format='ascii'` does not raise the expected exception but rather reads the table bytes in as table columns.

### Expected behavior
`io.ascii` should raise something like a `_csv.Error` so a reader can handle the exception to try a different format
(arguably it is not 100% clear whether this really should constitute a bug, since we were explicitly forcing `Table.read()` to treat it as ascii, but currently it is at least problematic due to the inconsistency with earlier Python versions).

### Actual behavior
The FITS file is parsed as an ASCII table of `dtype([('col1', '<U6'), ('col2', '<U1'), ('col3', '<U1'), ... ('col104', '<U3'), ('col105', '<U2880')])`

### Steps to Reproduce
Downloading e.g.
https://github.com/glue-viz/glue/blob/main/glue/tests/data/single_table.fits
or creating a simple example as below.
```python
tb = Table([np.arange(1, 4), np.arange(4, 7)], names=['a', 'b'])
Table.write('single_table.fits')
```
Python 3.10
```python
tab = Table.read('single_table.fits', format='ascii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.10/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/opt/lib/python3.10/site-packages/astropy/io/registry/core.py", line 212, in read
    data = reader(*args, **kwargs)
  File "/opt/lib/python3.10/site-packages/astropy/io/ascii/connect.py", line 18, in io_read
    return read(filename, **kwargs)
  File "/opt/lib/python3.10/site-packages/astropy/io/ascii/ui.py", line 359, in read
    dat = _guess(table, new_kwargs, format, fast_reader)
  File "/opt/lib/python3.10/site-packages/astropy/io/ascii/ui.py", line 526, in _guess
    dat = reader.read(table)
  File "/opt/lib/python3.10/site-packages/astropy/io/ascii/core.py", line 1365, in read
    self.header.get_cols(self.lines)
  File "/opt/lib/python3.10/site-packages/astropy/io/ascii/core.py", line 631, in get_cols
    self.names = next(self.splitter([line]))
  File "/opt/lib/python3.10/site-packages/astropy/io/ascii/core.py", line 489, in __call__
    for vals in csv_reader:
_csv.Error: line contains NUL
```
Python 3.11
```python
Table.read('single_table.fits')
<Table length=3>
  a     b  
int64 int64
----- -----
    1     4
    2     5
    3     6

Table.read('single_table.fits', format='ascii')
<Table length=1>
 col1  col2 col3 col4   col5   col6 col7   col8    col9  col10 ... col96  col97 col98 col99 col100 col101 col102 col103 col104                      col105                     
 str6  str1 str1 str1   str8   str2 str4   str8    str6   str1 ...  str6   str1  str2  str1  str6   str1   str2   str1   str3                      str2880                     
------ ---- ---- ---- -------- ---- ---- -------- ------ ----- ... ------ ----- ----- ----- ------ ------ ------ ------ ------ ------------------------------------------------
SIMPLE    =    T    / conforms   to FITS standard BITPIX     = ... TTYPE2     =    'b     ' TFORM2      =     'K      '    END
```
### System Details
platform linux -- Python 3.11.0rc2
astropy @ git+https://github.com/astropy/astropy@616f382dc9be9f52954841c80f4eed5485a3d1e8
numpy @ git+https://github.com/numpy/numpy@5f94eb858f3e181eccfda2c26db9f0b9167a8156

or same on macOS-12.6-arm64-arm-64bit, or with
astropy 5.1
numpy 1.23.3

**Comment by dhomeier** [comment]
So what's happening here is that `csv.reader`, which previously balked on the `NUL` characters, now happily parses the entire file as a single 3*2880 char line. Since the format was explicitly requested as 'ascii', that might even be considered a features, but the inconsistency with older versions is still a concern.

One could explicitly check in `get_cols()` e.g. for
`len(lines[0]) % 2880 == 0 and first_data_vals[:3] == ['SIMPLE', '=', 'T']`
to still reject a FITS table at this point.
@taldcroft what do you think?

**Comment by pllim** [comment]
Is it really our problem that people pick the wrong parser for the file type resulting in crazy behavior?

**Comment by taldcroft** [comment]
I agree with @pllim - if you explicitly tell astropy to do something non-sensical then we should not expend effort to guard against that. There are plenty of real issues that would benefit more users if they got fixed.

**Comment by dhomeier** [comment]
The case in question is the `glue` data loader in
https://github.com/glue-viz/glue/blob/f8c1e9646e7252aa13f5f58c4838cb9b670875d3/glue/core/data_factories/astropy_table.py#L41-L43
which as a rule makes an initial attempt with the ascii reader, as auto-detecting the ascii formats was broken.

To my surprise this still apparently still applies in many cases; e.g. even the most basic table like
```python
tab = Table([np.arange(1, 4), np.arange(4, 7)], names=['a', 'b'])
tab.write('simple.tab', format='ascii')
open('simple.tab', 'r').read()
'a b\n1 4\n2 5\n3 6\n'
Table.read('simple.tab', guess=True)
astropy.io.registry.base.IORegistryError: Format could not be identified based on the file name or contents, please provide a 'format' argument.
...
```
fails to find an automatic format, while strangely with only `format='ascii'` pretty much all the different cases of no/commented header, column separators etc. are correctly recognised.
So for a very generic reader with little prior information on the data formats it encounters, this is apparently still a relevant case, although it is of course also easily fixable in the custom reader (I do have concerns about putting such a fix into such a low level method as `get_cols` as well).

**Comment by taldcroft** [comment]
> The case in question is the glue data loader

I think that's a bug in glue. If the user provides no prior information about the file then glue should first try reading the file with `Table.read(*args, **kwargs)` (i.e. let the astropy unified I/O work as intended) and *then* try as an ASCII file.

> astropy.io.registry.base.IORegistryError: Format could not be identified based on the file name or contents, please provide a 'format' argument.

I think this exception message is a bit misleading or at least confusing. Some formats, like FITS, will try to inspect the file contents, but others like the ASCII formats are just looking at file names. So for that simple tab file it doesn't know about the `.tab` extension and doesn't bother with any ASCII formats. 

But in this case the exception message does provide exactly the right action for the user, which is to say that the unified I/O is not sure and the user needs to give it some help. I suspect that trying to be more clever would result is all sorts of problems from false positives (i.e. if you always try to run every file through the `io.ascii` guessing, which will happily parse a FITS file).

**Comment by dhomeier** [comment]
Good point about _first_ trying without `format` specified, and _then_ let the `ascii` reader try again. I think that's actually what the comment
> 
    # In Python 3, as of Astropy 0.4, if the format is not specified, the
    # automatic format identification will fail (astropy/astropy#3013).
    # This is only a problem for ASCII formats however, because it is due
    # to the fact that the file object in io.ascii does not rewind to the
    # start between guesses (due to a bug), so here we can explicitly try
    # the ASCII format if the format keyword was not already present. But
    # also more generally, we should first try the ASCII readers.

referred to – you could not easily do two read attempts on the open file. But that should be fixed as of Astropy 4.0 at least, so the above approach would work in principle. I still see some issues doing this in glue's `astropy_table_read`; e.g. one csv test file
```
#a,b
1,2
```
is expected to be read as
```python
<Table length=1>
  a     b  
int64 int64
----- -----
    1     2
```
which is in fact what `Table.read(file, format='ascii')` returns; however in this case the automatic recognition already succeeds and produces
```python
<Table length=1>
  #a    b  
int64 int64
----- -----
    1     2
```
apparently trying the `csv` format prior to `ascii`.
I actually understand the latter, as we generally give the uncommented header version preference to `ascii.commented_header`; but `format='ascii'` doing the opposite here is at least confusing.

**Comment by dhomeier** [comment]
> I think this exception message is a bit misleading or at least confusing. Some formats, like FITS, will try to inspect the file contents, but others like the ASCII formats are just looking at file names. So for that simple tab file it doesn't know about the `.tab` extension and doesn't bother with any ASCII formats.

One reason I am not a fan of file recognition by name suffix. But indeed we did have those discussions about how to make the auto-detection more bullet-proof, but in the end it always was way too much effort to try and anticipate all possible styles.

For `glue` that probably means deciding whether to go along with Astropy's order of preference (like uncommented header first, then commented header, then no header...), likely breaking some existing workflows, or implement its own workarounds for a preference.

**Comment by taldcroft** [comment]
The astropy file identification by file suffix and/or content is reasonably robust and conservative. Only very-well established suffixes are used. See https://docs.astropy.org/en/latest/io/unified.html#built-in-table-readers-writers for a summary.

I will agree that I've always been surprised at how much attention is given to the file name suffix by operating systems and email clients. Seems like MacOS or gmail should be able to figure out that my file or attachment called "blah.backstop" is just plain ASCII and display it accordingly, but instead if it is named "blah.backstop.txt" then it blindly assumes ASCII. But that's what it is...

**Comment by dhomeier** [comment]
Mac OS used to have these things called resource fork even pre-X. ;-)
But then all attention was switched back to suffixes for Win/DOS compatibility...

The main thing that's puzzling me is, in my naïve view 'ascii' is a subformat of all format, 'csv' is a subformat of that, and 'ascii.commented_header' etc. are sub-subformats of the latter. So if auto-detect first decides it is some flavour of 'ascii' and then determines the sub-subformat, I'd expect it to come out with the same result as when I tell it `format='ascii'` right away. 🤔
