### ISSUE TITLE
GWCS: Slicing

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#13691]
How can one slice a GWCS?

See, e.g., https://github.com/astropy/astropy/issues/4669

Specifically, how do you create a new GWCS for a cutout image?  This is needed for visualization (cc @pllim, referencing the above post).

Does nddata already do this?  I hope this is a documentation issue, not a feature request.

Example use case:
```python
hdu = fits.open('filename.fits')[('SCI', 1)]
ww = WCS(hdu.header)
slcs = slice(50, 100), slice(100, 150)
data = hdu.data[slcs]
ax = pl.subplot(projection=ww[slcs])
ax.imshow(data)
```

How can I do _that_ with GWCS?

**Comment by Apple9238** [comment]
Pls don’t send again tq

**Comment by pllim** [comment]
Shouldn't you be asking this over at https://github.com/spacetelescope/gwcs/issues ? If possible, it would have been implemented as a low-level API, no?

**Comment by Cadair** [comment]
I have many thoughts on this but TLDR the answer is this https://github.com/astropy/astropy/blob/main/astropy/wcs/wcsapi/wrappers/sliced_wcs.py#L105

**Comment by pllim** [comment]
Okay, so it is already possible and we can close this issue?

**Comment by keflavich** [comment]
Was this supposed to be in gwcs?  i.e., should gwcs be implementing the `sliced_wcs` low-level wrapper?  I'll cross-post over there.

@pllim no, if it is possible, this is a (imo, high-priority) documentation issue.  If it is not possible now but should be, then we can close it in favor of the space telescope issue.

**Comment by pllim** [comment]
> Was this supposed to be in gwcs?

No idea but let's see what GWCS devs say.

**Comment by Cadair** [comment]
>  should gwcs be implementing the sliced_wcs low-level wrapper

No, the wrapper as currently implemented is completely agonistic to the implementation. It works just as well for `astropy.wcs.WCS` as it does for `gwcs.WCS`.

It would be nice if we could have some implementation specific behaviour to improve usability, but for the moment this works.

**Comment by pllim** [comment]
Okay, I am trying to understand the problem. So, it already works but someone needs to write docs somewhere? Is https://docs.astropy.org/en/latest/wcs/wcsapi.html#slicing-of-wcs-objects insufficient?

**Comment by keflavich** [comment]
What do you mean "this works"?  How do I use it?  Could you provide some sort of example, even if it's not complete?

**Comment by keflavich** [comment]
Specifically, I get the error:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/scratch/local/45915091/ipykernel_22376/3662446182.py in <module>
      2 gwcs1 = asdf.open(f"{basepath}/F187N/pipeline/jw02221001001_03101_00005_nrcb4_cal.fits").tree['meta']['wcs']
      3 
----> 4 gwcs1[35:45, 55:65]

TypeError: 'WCS' object is not subscriptable
```

**Comment by pllim** [comment]
You didn't wrap it in `astropy.wcs.wcsapi.SlicedLowLevelWCS`.

**Comment by keflavich** [comment]
OK, this works:
```python
SlicedLowLevelWCS(gwcs1, slices=[slice(35, 45), slice(55, 65)])
```
or at least doesn't raise an Exception.  And indeed, the documentation does clearly specify:

```
If you are implementing your own WCS class, you could choose to implement __getitem__ and have it internally use [SlicedLowLevelWCS](https://docs.astropy.org/en/latest/api/astropy.wcs.wcsapi.SlicedLowLevelWCS.html#astropy.wcs.wcsapi.SlicedLowLevelWCS). In fact, the [WCS](https://docs.astropy.org/en/latest/api/astropy.wcs.WCS.html#astropy.wcs.WCS) class does this - the example above can be written more succinctly as:
```

I'll ask for that on GWCS.

**Comment by pllim** [comment]
p.s. I never did figure out how to write a `SlicedLowLevelWCS` object back to FITS header but that is a battle for another day...

**Comment by keflavich** [comment]
oof, yikes, @pllim is there another thread on that?  because `fitswcs[5:10,5:10]` returns a FITS WCS object that can be serialized, while `SlicedLowLevelWCS(fitwcs, [slice(5,10), slice(5,10)])` returns a `SlicedLowLevelWCS`....

**Comment by pllim** [comment]
I didn't open an issue because I don't even know how or where to begin with that ask. Maybe @Cadair has idea since I think he wrote the `SlicedLowLevelWCS` ?

**Comment by Cadair** [comment]
There's a lot to unpick here and I can't do it all today while I am not working on my phone.

The only way to slice a gwcs is with `SlicedLowLevelWCS` and no, there's currently no way to serialise it.

**Comment by keflavich** [comment]
I think we've worked out everything except serializing the `SlicedLowLevelWCS`, which should be its own issuse.

Aside: I thought at first `unpick` was shorthand for `unpickle` and that your brain now just works in numpy-object space full time.

**Comment by pllim** [comment]
Stuart's brain is probably serializable to TOML or something. 😝
