### ISSUE TITLE
rm ``_dev``?

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13692]
### Description

What does it still do and can we remove it?

**Comment by pllim** [comment]
@saimn , is the answer "no" then or can we use some newer built-in `setuptools_scm` feature to do the same thing?

**Comment by StanczakDominik** [comment]
I just researched this same issue for plasmapy and no, doesn't seem like this has improved at all! I'd close this issue for now.

**Comment by Cadair** [comment]
yeah, this was a extreme but ultimately needed method of dynamically generating the correct git version when using editable installs.

Unless someone else has an alternative suggestion I am going to close this.
