### ISSUE TITLE
rm pep8speaks

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13693]
### Description

With `black` + `isort` + `pre-commit` I don't think `pep8speaks` does anything.

**Comment by pllim** [comment]
`black` is still being debated, so is this blocked by https://github.com/astropy/astropy-APEs/pull/76 ?

**Comment by nstarman** [comment]
I suppose so. 🤞 it's unblocked.

**Comment by nstarman** [comment]
🎉. ``black`` is in. ``isort`` is almost completely rolled out. ``pre-commit`` flake8 is getting beefed up (I think it already covers all the checks in pep8speaks). Nearly there.
