### ISSUE TITLE
float32 representation of pi/2 is rejected by `Latitude`

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#13708]
### Description

The closest float32 value to pi/2 is by accident slightly larger than pi/2:

```
In [5]: np.pi/2
Out[5]: 1.5707963267948966

In [6]: np.float32(np.pi/2)
Out[6]: 1.5707964
```

Astropy checks using float64 precision, rejecting "valid" alt values (e.g. float32 values read from files):

```

In [1]: from astropy.coordinates import Latitude

In [2]: import numpy as np

In [3]: lat = np.float32(np.pi/2)

In [4]: Latitude(lat, 'rad')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [4], line 1
----> 1 Latitude(lat, 'rad')

File ~/.local/lib/python3.10/site-packages/astropy/coordinates/angles.py:564, in Latitude.__new__(cls, angle, unit, **kwargs)
    562     raise TypeError("A Latitude angle cannot be created from a Longitude angle")
    563 self = super().__new__(cls, angle, unit=unit, **kwargs)
--> 564 self._validate_angles()
    565 return self

File ~/.local/lib/python3.10/site-packages/astropy/coordinates/angles.py:585, in Latitude._validate_angles(self, angles)
    582     invalid_angles = (np.any(angles.value < lower) or
    583                       np.any(angles.value > upper))
    584 if invalid_angles:
--> 585     raise ValueError('Latitude angle(s) must be within -90 deg <= angle <= 90 deg, '
    586                      'got {}'.format(angles.to(u.degree)))

ValueError: Latitude angle(s) must be within -90 deg <= angle <= 90 deg, got 90.00000250447816 deg
```

### Expected behavior

Be lenient? E.g. only make the comparison up to float 32 precision?

### Actual behavior
See error above

### Steps to Reproduce

See snippet above.

### System Details

```
Linux-5.15.65-1-MANJARO-x86_64-with-glibc2.36
Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
Numpy 1.23.3
pyerfa 2.0.0.1
astropy 5.0.1
Scipy 1.9.1
Matplotlib 3.5.2
```

**Comment by nstarman** [comment]
> Be lenient? E.g. only make the comparison up to float 32 precision?

Instead, we could make the comparison based on the precision of the ``dtype`` using something like https://numpy.org/doc/stable/reference/generated/numpy.finfo.html?highlight=finfo#numpy.finfo

**Comment by mhvk** [comment]
That's a funny one! I think @nstarman's suggestion would work: would just need to change the dtype of `limit` to `self.dtype` in `_validate_angles`.

**Comment by maxnoe** [comment]
That wouldn't solve the case where the value is read from a float32 into a float64, which can happen pretty fast due to the places where casting can happen. Better than nothing, but...

**Comment by dhomeier** [comment]
Do we want to simply let it pass with that value, or rather "round" the input value down to the float64 representation of `pi/2`? Just wondering what may happen with larger values in any calculations down the line; probably nothing really terrible (like ending up with inverse Longitude), but...

**Comment by maxnoe** [comment]
This is what I did to fix it on our end:
https://github.com/cta-observatory/ctapipe/pull/2077/files#diff-d2022785b8c35b2f43d3b9d43c3721efaa9339d98dbff39c864172f1ba2f4f6f

**Comment by nstarman** [comment]
Does this keep the numpy dtype of the input?

**Comment by maxnoe** [comment]
No, the point is that this casts to float64.

**Comment by dhomeier** [comment]
> Does this keep the numpy dtype of the input?

If `limit` is cast to `self.dtype` (is that identical to `self.angle.dtype`?) as per your suggestion above, it should.
But that modification should already catch the cases of `angle` still passed as float32, since both are compared at the same resolution. I'd vote to do this and only implement the more lenient comparison as a fallback, i.e. if still `invalid_angles`, set something like
`_half_pi_maxval = (0.5 + np.finfo(np.float32).eps)) * np.pi` and do a second comparison to that, if that passes, set to  `limit * np.sign(self.angle)`. Have to remember that `self.angle` is an array in general...

**Comment by dhomeier** [comment]
> So `Latitude(pi/2, unit=u.deg, dtype=float32)` can become a float64?

`Latitude(pi/2, unit=u.rad, dtype=float32)` would in that approach, as it currently raises the `ValueError`.

**Comment by maxnoe** [comment]
I'll open a PR with unit test cases and then we can decided about the wanted behaviour for each of them

**Comment by maxnoe** [comment]
PR open
