### ISSUE TITLE
TST: s390x doctest failed due to PR 13734 ( Support fixed width ASCII table with header rows for dtype, unit, format, description)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13760]
https://github.com/astropy/astropy/pull/13734 introduced doctests that are failing in s390x job (weekly cron). cc @taldcroft @hamogu @dhomeier 

Example log: https://github.com/astropy/astropy/actions/runs/3125537612/jobs/5070006396

```
______________________ [doctest] fixed_width_gallery.rst _______________________
475   Custom Header Rows with Fixed Width
476 
477 ::
478     >>> from astropy.table.table_helpers import simple_table
479     >>> dat = simple_table(size=3, cols=4)
480     >>> dat["a"].info.unit = "m"
481     >>> dat["d"].info.unit = "m/s"
482     >>> dat["b"].info.format = ".2f"
483     >>> dat["c"].info.description = "C column"
484     >>> ascii.write(
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,3 @@
    -| int64 | float64 |      <U1 | int64 |
    +| int64 | float64 |      >U1 | int64 |
     |     a |       b |        c |     d |
     |     m |         |          | m / s |

.../astropy/docs/io/ascii/fixed_width_gallery.rst:484: DocTestFailure
______________________________ [doctest] 5.2.rst _______________________________
090 ``format``, and ``description``. This is available in the ``fixed_width`` and
091 ``fixed_width_two_line`` formats via the new ``header_rows`` keyword argument::
092 
093     >>> from astropy.io import ascii
094     >>> from astropy.table.table_helpers import simple_table
095     >>> dat = simple_table(size=3, cols=4)
096     >>> dat["b"].info.unit = "m"
097     >>> dat["d"].info.unit = "m/s"
098     >>> dat["b"].info.format = ".2f"
099     >>> ascii.write(
Differences (unified diff with -expected +actual):
    @@ -1,6 +1,6 @@
         a       b   c     d
    -int64 float64 <U1 int64
    +int64 float64 >U1 int64
                 m     m / s
    -        .2f
    +          .2f          
     ----- ------- --- -----
         1    1.00   c     4

.../astropy/docs/whatsnew/5.2.rst:99: DocTestFailure
```

**Comment by taldcroft** [comment]
Ugh, I had a worry that the endianness in `<U1` might cause problems.

**Comment by pllim** [comment]
```diff
    -        .2f
    +          .2f          
```

I cannot tell if this is side effect of the other line (i.e., this will magically go away when the other line is fixed, *or* if s390x somehow prefers right-aligned instead of center.

**Comment by pllim** [comment]
We could just use ellipsis to bypass this but not sure if that will make your doc example worse.

**Comment by hamogu** [comment]
I don't think ellipsis is good for this one. We can instead change the datatype on column "c" to something that works or even easier remove column c from the example altogether. An example of three columns is enough. Maybe that fixed the ".2f" magically. Or we `doctest: +SKIP`. We have tests for this in the tests.

**Comment by taldcroft** [comment]
Yeah, I don't understand what's going on with the `.2f` but I don't think it will magically get fixed. I'm kind of with @hamogu  on just skipping the whole thing. It's just a question of how much time to devote to this relative to the hundred other things that could also get attention.

**Comment by pllim** [comment]
Proposed a fix at https://github.com/astropy/astropy/pull/13766 🤞
