### ISSUE TITLE
Use explicit over star imports

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13785]
> Finding a way to deal specifically with unused import warnings in __init__.py files since it's pretty tedious to have to clutter those files with so many noqas and is such a common thing.

My 2 cents... From my time spent static typing and compiling other libraries, I've found that star imports are better replaced by explicit imports. Pre-commit flake8 checks make sure the `__all__` in `__init__` stays synced with the module content.

__Originally posted by @nstarman in https://github.com/astropy/astropy/pull/13754#issuecomment-1265403770__
See also #13781

**Comment by pllim** [comment]
Sometimes it is unavoidable so I think it really depends on a case-by-case basis and not do a blind clean-up. Also unless something is breaking, I am not sure if time is well spent on this. We have other more urgent things.

**Comment by nstarman** [comment]
I think there are 3 benefits:
1. Essentially we consider anything in `__all__` to be public, but most subpackages also want a flat namespace. Since star imports only import the content of `__all__` many subpackages have modules with `__all__`, which implicitly makes it public. This somewhat defeats out flat namespace. Explicit imports get around this because the code is only public / in an `__all__` once. 
2. IDEs like VSCode pick up on static `__all__` and helpfully suggest imports. Star imports are less good.
3. Static typing. Not yet important for Astropy, but hopefully eventually.

**Comment by olintoeduardo** [comment]
I want to work on this issue, but I have never contributed to the project. Would that be appropriate?
