### ISSUE TITLE
Uses of `pytest`'s `tmpdir` fixture should be replaced with `tmp_path`

### ISSUE THREAD

**Issue by eerovaher** [astropy/astropy#13787]
### Description

Some of the tests involve writing data, and such data should not be stored permanently. `pytest` has two fixtures that provide temporary directories for writing test data: the recommended [`tmp_path`](https://docs.pytest.org/en/stable/how-to/tmp_path.html#the-tmp-path-fixture), which uses [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) from the Python standard library, and the legacy [`tmpdir`](https://docs.pytest.org/en/stable/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures) utilizing [`py.path`](https://py.readthedocs.io/en/latest/path.html), a third party library. The following shell command reveals that many tests in `astropy` still use `tmpdir`:
```shell
git grep --files-with-matches tmpdir -- *tests*
```
All uses of `tmpdir` should be replaced with `tmp_path`, although not all sub-packages have to be updated in a single pull request.

### Sub-packages to update

- [x] `config` #13788
- [x] `coordinates` #13797
- [x] `cosmology` #13847
- [x] `io.ascii` #13876
- [x] `io.fits` https://github.com/astropy/astropy/pull/13879
- [x] `io.misc` (but note that `io.misc.asdf` is deprecated so only `io.misc.tests` is worth updating) #13878
- [x] `io.registry` #13849
- [x] `io.votable` #13850
- [x] `modeling` #13799
- [x] `nddata` #13807
- [x] `samp` #13848
- [x] `table` #13802
- [x] `tests` #13800
- [x] `time` #13801
- [x] `utils` #13874
- [x] `visualization` https://github.com/astropy/astropy/pull/13822
- [x] `wcs` #13796

**Comment by jerobado** [comment]
I run the `git grep --count tmpdir -- *tests*` command and it shows the following files with the number of lines that needs to be updated:

```
astropy/config/tests/test_configs.py:9
astropy/coordinates/tests/test_name_resolve.py:2
astropy/coordinates/tests/test_solar_system.py:2
astropy/cosmology/tests/test_connect.py:6
astropy/cosmology/tests/test_units.py:2
astropy/io/ascii/tests/test_c_reader.py:18
astropy/io/ascii/tests/test_connect.py:18
astropy/io/ascii/tests/test_ecsv.py:7
astropy/io/ascii/tests/test_qdp.py:16
astropy/io/ascii/tests/test_read.py:3
astropy/io/ascii/tests/test_write.py:9
astropy/io/fits/tests/test_connect.py:85
astropy/io/fits/tests/test_convenience.py:2
astropy/io/fits/tests/test_diff.py:12
astropy/io/fits/tests/test_fitsdiff.py:3
astropy/io/fits/tests/test_fsspec.py:2
astropy/io/fits/tests/test_image.py:8
astropy/io/fits/tests/test_table.py:9
astropy/io/misc/asdf/tags/coordinates/tests/test_angle.py:6
astropy/io/misc/asdf/tags/coordinates/tests/test_earthlocation.py:8
astropy/io/misc/asdf/tags/coordinates/tests/test_frames.py:10
astropy/io/misc/asdf/tags/coordinates/tests/test_representation.py:2
astropy/io/misc/asdf/tags/coordinates/tests/test_skycoord.py:25
astropy/io/misc/asdf/tags/coordinates/tests/test_spectralcoord.py:6
astropy/io/misc/asdf/tags/fits/tests/test_fits.py:4
astropy/io/misc/asdf/tags/table/tests/test_table.py:25
astropy/io/misc/asdf/tags/time/tests/test_time.py:10
astropy/io/misc/asdf/tags/time/tests/test_timedelta.py:6
astropy/io/misc/asdf/tags/transform/tests/test_transform.py:42
astropy/io/misc/asdf/tags/transform/tests/test_units_mapping.py:13
astropy/io/misc/asdf/tags/unit/tests/test_equivalency.py:2
astropy/io/misc/asdf/tags/unit/tests/test_quantity.py:4
astropy/io/misc/asdf/tests/test_io.py:6
astropy/io/misc/tests/test_hdf5.py:82
astropy/io/misc/tests/test_pandas.py:2
astropy/io/misc/tests/test_parquet.py:44
astropy/io/misc/tests/test_pickle_helpers.py:8
astropy/io/registry/tests/test_registries.py:11
astropy/io/votable/tests/table_test.py:12
astropy/io/votable/tests/vo_test.py:25
astropy/modeling/tests/test_core.py:2
astropy/nddata/mixins/tests/test_ndio.py:1
astropy/nddata/tests/test_ccddata.py:47
astropy/samp/tests/test_hub_proxy.py:2
astropy/samp/tests/test_standard_profile.py:11
astropy/samp/tests/test_web_profile.py:2
astropy/table/tests/test_jsviewer.py:10
astropy/table/tests/test_mixin.py:6
astropy/table/tests/test_table.py:4
astropy/tests/test_logger.py:10
astropy/time/tests/test_mask.py:6
astropy/time/tests/test_update_leap_seconds.py:4
astropy/utils/iers/tests/test_iers.py:4
astropy/utils/iers/tests/test_leap_second.py:15
astropy/utils/masked/tests/test_table.py:6
astropy/utils/tests/test_data.py:85
astropy/visualization/scripts/tests/test_fits2bitmap.py:13
astropy/visualization/wcsaxes/tests/test_coordinate_helpers.py:2
astropy/visualization/wcsaxes/tests/test_display_world_coordinates.py:9
astropy/visualization/wcsaxes/tests/test_frame.py:6
astropy/visualization/wcsaxes/tests/test_images.py:4
astropy/visualization/wcsaxes/tests/test_misc.py:19
astropy/wcs/tests/test_wcs.py:4
```
This may take a while due to the number of files, but I'm still interested in working on this one.

I'll send a PR for each module for the changes.

**Comment by jerobado** [comment]
@pllim, that is understandable.

I think I'll pick the modules with few number of lines first like `coordinates`, `cosmology`, `modeling` and `wcs` so that the review will be easy on the maintainers.

**Comment by jerobado** [comment]
In `astropy/cosmology/tests/test_units.py` under the `test_equivalencies_asdf()` function, the test fails when using `tmp_path` parameter:

```powershell
================================================================================================================================= FAILURES ==================================================================================================================================
_____________________________________________________________________________________________________________________ test_equivalencies_asdf[with_H0] ______________________________________________________________________________________________________________________

tmp_path = PosixPath('/tmp/pytest-of-jerobado/pytest-185/test_equivalencies_asdf_with_H0'), equiv = <function with_H0 at 0x7f3c2d0e2ee0>, recwarn = WarningsRecorder(record=True)

    @pytest.mark.skipif(not HAS_ASDF, reason="requires ASDF")
    @pytest.mark.parametrize("equiv", [cu.with_H0])
    def test_equivalencies_asdf(tmp_path, equiv, recwarn):
        from asdf.tests import helpers

        tree = {"equiv": equiv()}
>       helpers.assert_roundtrip_tree(tree, tmp_path)

astropy/cosmology/tests/test_units.py:400:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../miniconda3/envs/astropy-contributor/lib/python3.9/site-packages/asdf/tests/helpers.py:172: in assert_roundtrip_tree
    _assert_roundtrip_tree(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

tree = {'equiv': [(Unit("1.47798 littleh"), None)]}, tmpdir = PosixPath('/tmp/pytest-of-jerobado/pytest-185/test_equivalencies_asdf_with_H0')

    def _assert_roundtrip_tree(
        tree,
        tmpdir,
        *,
        asdf_check_func=None,
        raw_yaml_check_func=None,
        write_options={},
        init_options={},
        extensions=None,
        tree_match_func="assert_equal",
    ):

>       fname = str(tmpdir.join("test.asdf")) --> PosixPath object no longer valid here
E       AttributeError: 'PosixPath' object has no attribute 'join'

../../miniconda3/envs/astropy-contributor/lib/python3.9/site-packages/asdf/tests/helpers.py:187: AttributeError
========================================================================================================================== short test summary info ==========================================================================================================================
FAILED astropy/cosmology/tests/test_units.py::test_equivalencies_asdf[with_H0] - AttributeError: 'PosixPath' object has no attribute 'join'
======================================================================================================================= 1 failed, 24 passed in 0.62s ========================================================================================================================
```
This line `fname = str(tmpdir.join("test.asdf"))` raises an error because the argument **tmpdir** is now a pathlib.Path object (PosixPath).

The original type/value of **tmpdir** was:
```Python
tmpdir=local('/tmp/pytest-of-jerobado/pytest-188/test_equivalencies_asdf_with_H0')
```

**Questions**

1. Is `../../miniconda3/envs/astropy-contributor/lib/python3.9/site-packages/asdf/tests/helpers.py:187` a 3rd party library? Are we allowed to make changes here?

2. Should I keep the parameter as is in `test_equivalencies_asdf()` for the meantime or do you have any alternative without touching the 3rd party file?

**Comment by eerovaher** [comment]
>     1. Is `../../miniconda3/envs/astropy-contributor/lib/python3.9/site-packages/asdf/tests/helpers.py:187` a 3rd party library? Are we allowed to make changes here?
>
>     2. Should I keep the parameter as is in `test_equivalencies_asdf()` for the meantime or do you have any alternative without touching the 3rd party file?

`asdf` is indeed a third party library. They have an open issue about replacing usage of `tmpdir` with `tmp_path` (asdf-format/asdf#1204), so submitting a pull request there would be a good idea. However, even when `asdf` has been updated, `astropy` will still be supporting older versions that require `tmpdir`, so it looks to me like we'll have to keep using `tmpdir` in the affected tests.

Maybe @WilliamJamieson can comment more about this.

**Comment by WilliamJamieson** [comment]
There is no current plan to touch `assert_roundtrip_tree` at this time as there is a high chance of disrupting the tests in packages downstream from ASDF.

**Comment by jerobado** [comment]
Thanks @eerovaher and @WilliamJamieson for your response.

I'll skip changing the `test_equivalencies_asdf()` for the meantime.

**Comment by dhomeier** [comment]
Would `tmpdir / "test.asdf"` behave in any way differently from `tmpdir.join("test.asdf")`? At least back to Python 3.7 they return the same `local` afaict.

**Comment by matteobachetti** [comment]
Is a changelog entry needed for each PR in subpackages?

**Comment by pllim** [comment]
This only affects the tests, so I don't think change logs are needed.

**Comment by dhomeier** [comment]
I think some major and infrastructure changes to the tests have been included before, but it's probably not necessary.
Would a single entry with the issue no. (13787.other.rst, rather than any of the PRs) be detected?

**Comment by pllim** [comment]
I don't think `tmpdir -> tmp_path` is major enough to warrant a change log. Nevertheless, I do want to thank @jerobado for doing all these clean-ups!

**Comment by jerobado** [comment]
Thanks @pllim and everyone!

**Comment by pllim** [comment]
Great clean-up so far! 👏 

I did a `grep` and still found some but not sure if they are in scope or not.

```
./docs/conftest.py:36:            tmpdir = request.getfixturevalue('tmpdir')
```

Any reason these were excluded from https://github.com/astropy/astropy/pull/13822 ?

```
./astropy/visualization/wcsaxes/tests/test_images.py:706:    def test_beam_shape_from_args(self, tmpdir):
./astropy/visualization/wcsaxes/tests/test_images.py:721:    def test_beam_shape_from_header(self, tmpdir):
./astropy/visualization/wcsaxes/tests/test_images.py:739:    def test_scalebar(self, tmpdir):
```

Any reason these were excluded from https://github.com/astropy/astropy/pull/13847 ?

```
./astropy/cosmology/tests/test_units.py:396:def test_equivalencies_asdf(tmpdir, equiv, recwarn):
./astropy/cosmology/tests/test_units.py:400:    helpers.assert_roundtrip_tree(tree, tmpdir)
```

**Comment by WilliamJamieson** [comment]
> Any reason these were excluded from #13847 ?
> 
> ```
> ./astropy/cosmology/tests/test_units.py:396:def test_equivalencies_asdf(tmpdir, equiv, recwarn):
> ./astropy/cosmology/tests/test_units.py:400:    helpers.assert_roundtrip_tree(tree, tmpdir)
> ```

The `helpers.assert_roundtrip_tree` used here is technically depending on the test API in ASDF, which currently does not support `tmp_path` (in particular older versions of ASDF will definitely not support `tmp_path` with this function). Hence, this should not be updated.

I really think this test should be moved to `astropy.io.misc.asdf` rather than `astropy.cosmology` as this is clearly an ASDF support test. Then it can be removed with the rest of the `astropy.io.misc.asdf`.

**Comment by pllim** [comment]
Hah, I opened https://github.com/asdf-format/asdf/pull/1216 before I saw your reply above.

**Comment by WilliamJamieson** [comment]
Do we care that once asdf-formate/asdf#1216 is merged/released and this is switched to `tmp_path` this will cause the test to fail if an older version of ASDF is used?

**Comment by pllim** [comment]
If you open a PR to move this test from cosmology to io.misc.asdf , then I will stop caring. 😉

**Comment by WilliamJamieson** [comment]
> If you open a PR to move this test from cosmology to io.misc.asdf , then I will stop caring. 😉

Done in #13904
