### ISSUE TITLE
Add a coordinate object for representing Stokes profiles

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#13790]
Astropy currently provides what the APE 14 WCS API refers to as "High Level" coordinate objects for many different types of coordinates found in astronomical (or solar) WCSes. These include `SkyCoord`, `Time`, `SpectralCoord` and of course `Quantity`. The most common WCS world axis physical type which is missing this treatment is a coordinate object for Stokes polarization profiles.

# Desired Functionality

As specified by Table 29 in the [FITS 4 standard](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf)
![image](https://user-images.githubusercontent.com/1391051/193793124-d3ce2c61-718b-4a03-974a-2c7f0b363691.png)

A WCS Stokes world coordinate uses an integer to represent a specific polarization state. This is a little unique to Stokes as for other world coordinates a numeric value is returned with a physical unit. Here the numerical values returned are categorical.
Given this what I think would be the primary function of the `StokesCoord`[1] class would be to store this numerical <> polarization mapping and allow the user to interact with Stokes coordinates in terms of their more commonly used string representations (i.e. `"I`, `"Q"` etc).

So the most basic thing that should work is this:

```python
mywcs.world_to_pixel(StokesCoord("I"))
```

However, really what I would like to work is this:

```python
mywcs.world_to_pixel("I")
```
as that's a lot more natural. I briefly experimented with this, but I think there might be some type issues to be uncovered if this this going to work properly.

## Prior work

In gWCS I have implemented a [`StokesProfile` class](https://github.com/spacetelescope/gwcs/blob/f4ff623beb575046ddd2e9c5c5016a61d47995d2/gwcs/coordinate_frames.py#L706-L757) which worked until it didn't. The main issue I encountered with that approach is the duality of needing to construct that class from both the string and numerical value inputs (for it to be correctly used by the high level API wrapper it needed to do that).

**Comment by astrofrog** [comment]
I think this would be nice - we'll have to think about how to deal with backward-compatibility for ``pixel_to_world`` presumably. Perhaps the FITS WCS APE 14 wrapper could have a property to control this and we could change the default after a deprecation/warning period?

**Comment by Cadair** [comment]
Oh goodness, I hadn't even considered backwards compatibility on the return types of `pixel_to_world`.

@adamginsburg you might be interested in this issue?
