### ISSUE TITLE
Possible fits memmap bug: memmap just doesn't work.

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#1380]
I'm trying to load some gigantic FITS record tables using `memmap=True`, and I'm getting `error: [Errno 12] Cannot allocate memory`.  

An example session:

```
filename = '/home/sdfits/AGBT12B_221_01/AGBT12B_221_01.raw.acs.fits'
import astropy.io.fits as fits
filefits = fits.open(filename,memmap=True)
data = filefits[2].data[:50]
```

The error is at this line:

```
/users/aginsbur/anaconda/lib/python2.7/site-packages/numpy/core/memmap.py(253)__new__()
--> 253             mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)

ipdb> bytes
23718381056L
ipdb> bytes/1024**2
22619L
ipdb> start
413921280
ipdb> acc
3
```

I don't really know what's going on, but I suspect memmap is improperly deciding on how much data to read.  Any tips on how to further debug?  Is this actually a FITS issue, or a numpy issue?

Details:

```
In [15]: numpy.__version__
Out[15]: '1.7.1'

In [16]: astropy.__version__
Out[16]: '0.2.4'

In [18]: sys.maxint
Out[18]: 9223372036854775807
```

**Comment by saimn** [comment]
Note that with #7597 we no more use `np.memmap`, so it should easier to use other flags if that is useful.

**Comment by astrofrog** [comment]
This can now be closed, as a workaround has been merged in https://github.com/astropy/astropy/pull/7926. ``MAP_NORESERVE`` is not available from Python, so that isn't a solution unfortunately.
