### ISSUE TITLE
TST: Bogus failure from CircleCI Pipeline (ignore it)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13804]
`CircleCI Pipeline — Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.`

I don't know what this is but it does not seem to be preventing the actual CircleCI image tests to run (2 jobs). Just ignore it for now. I think the org admin needs to do something on their side. I don't know which org admin triggered this or why. Nor do I know how to get rid of it from my end. Ideas/help welcome. Thanks!

cc @astropy/coordinators

**Comment by astrofrog** [comment]
Looks like this fixed itself!

**Comment by circleci-snapcode** [comment]
I have the same problem, and have no idea how to fix it. Logging out and back in again does not help. User has access in github...
