### ISSUE TITLE
Add pre-commit hook yesqa?

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13812]
### Description

Flags unnecessary ``noqa``, so they aren't added to the codebase going forward.
@WilliamJamieson, you have more recent experience with pre-commit + flake8. Would this be useful?

### Additional context

https://github.com/asottile/yesqa

**Comment by WilliamJamieson** [comment]
This has the possibility of being very useful especially after the black transition.

The big question I have is does it specifically strip `# noqa: <error code(s)>` if they don't apply?

**Comment by nstarman** [comment]
Looking at the code, it parses the error, so I think so!
