### ISSUE TITLE
flake8 the docstrings?

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13813]
### Description

Examples in the docstrings should be well formatted.
We can add ``flake8-docstrings`` to flake8's dependencies in pre-commit to enforce this.

### Additional context

See https://flake8.pycqa.org/en/latest/user/using-hooks.html#usage-with-the-pre-commit-git-hooks-framework.
There are other flake8 extensions we might enjoy.

**Comment by namurphy** [comment]
I've had good experiences with using [flake8-rst-docstrings](https://github.com/peterjc/flake8-rst-docstrings) too.

Adding flake8 extensions has been one of my favorite strategies for Procrastination Driven Development (PDD).

**Comment by namurphy** [comment]
A related possibility would be to add an autoformatter for docstrings (and even reStructuredText files).  At the moment, I haven't found a reStructuredText/numpydoc autoformatter that I'm happy enough with to add to pre-commit or CI.  I'll probably post what I learn in the future in in https://github.com/PlasmaPy/PlasmaPy/issues/1668 and https://github.com/PlasmaPy/PlasmaPy/issues/1669.

Also worth mentioning is [pydocstyle](https://www.pydocstyle.org/en/stable/).

**Comment by nstarman** [comment]
Ruff implements a lot of pydocstyle, so this would be very easy (to add, not to fix all the docstrings) 
https://github.com/charliermarsh/ruff#pydocstyle-d

**Comment by namurphy** [comment]
A Python linter written in Rust?  I'll have to check it out.  That's way better than my idea for a Python linter written in Fortran!

**Comment by nstarman** [comment]
Ruff is implementing much of this functionality so we can close this issue.
