### ISSUE TITLE
Stale WCSAxes docs (from old wcsaxes package)

### ISSUE THREAD

**Issue by wtbarnes** [astropy/astropy#13826]
I often find myself on the WCSAxes documentation page, but a first google often lands me on this (very stale) page for the standalone WCSAxes package: https://wcsaxes.readthedocs.io/en/latest/index.html.

It would probably good to do some SEO to make sure that people land on https://docs.astropy.org/en/stable/visualization/wcsaxes/index.html when googling "WCSAxes" or at least add a big red banner at the top of the outdated page telling people they should use the updated docs.

Presumably, the RTD page for that the old WCSAxes package can also be deleted.

**Comment by pllim** [comment]
Thanks for reporting this! @astrofrog , are you able to do a redirect from https://readthedocs.org/projects/wcsaxes/ ?

**Comment by astrofrog** [comment]
I'll try and fix this shortly

**Comment by astrofrog** [comment]
I decided to just delete the old documentation pages - there really is no reason to keep them around and anyone with a broken link will easily be able to find the new version.
