### ISSUE TITLE
TST: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13834]
Started seeing this failure in dev job:

```
Numpy: 1.24.0.dev0+934.gdb7414b7f
...
____________________________ TestCore.test_byteswap ____________________________

self = <astropy.io.fits.tests.test_core.TestCore object at 0x7f4c26839690>

    def test_byteswap(self):
        p = fits.PrimaryHDU()
        lst = fits.HDUList()
    
        n = np.zeros(3, dtype='i2')
        n[0] = 1
>       n[1] = 60000
E       DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.
        The conversion of 60000 to int16 will fail in the future.
E       For the old behavior, usually:
E           np.array(value).astype(dtype)`
E       will give the desired result (the cast overflows).

.../astropy/io/fits/tests/test_core.py:56: DeprecationWarning
```

This affected line was copied over from PyFITS and has not been touched for 11 years. Why now, NumPy? 😿 

https://github.com/astropy/astropy/blob/06e66c303ed21114d7b39584ca76dc09c60902ca/astropy/io/fits/tests/test_core.py#L56

**Comment by dhomeier** [comment]
Looks like the suggested replacement should work with our oldest numpy versions as well.

**Comment by pllim** [comment]
Where should this replacement happen? Are you interested in submitting a patch? Thanks!

**Comment by dhomeier** [comment]
Works with numpy 1.18 at least.

**Comment by mhvk** [comment]
Indeed, it is part of numpy trying to be more careful about interacting with python numbers generally, as part of trying to make casting a bit easier to understand: https://numpy.org/neps/nep-0050-scalar-promotion.html
