### ISSUE TITLE
Creating a mixin column in a new table from columns of another table renames columns in original table.

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#13840]
### Description

Consider the following code, where a subset of columns from another table should be included in a new table with new names, prerably without copying the actual payload data:

```python
from astropy.table import QTable, Table
import astropy.units as u


table1 = QTable({
    'foo': [1, 2, 3] * u.deg,
    'bar': [4, 5, 6] * u.m,
    'baz': [7, 8, 9] * u.TeV,
})

print(table1.colnames)
table2 = QTable({
    "new": table1["foo"],
    "name": table1["bar"]
}, copy=False)
print(table1.colnames)
```

If any of the two classes or both are a `Table`, not a `QTable`, the code works as expected.

### Expected behavior

Data in the columns is not copied, but column names in original table stay the same.

```
['foo', 'bar', 'baz']
['foo', 'bar', 'baz']
```

### Actual behavior

Column names do change in both tables:

```
['foo', 'bar', 'baz']
['new', 'name', 'baz']
```

### Steps to Reproduce

See above.

### System Details

```
Linux-5.15.71-1-MANJARO-x86_64-with-glibc2.36
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
Numpy 1.23.3
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.9.1
Matplotlib 3.6.1
```

(also tested with current `main` branch)

**Comment by mhvk** [comment]
Note that it is not specific to `QTable`, but just to any mixin column (and the behaviour not limited to `dict` either):
```
import numpy as np
from astropy.table import Table
from astropy.time import Time
table1 = Table({'t': Time(np.arange(50000., 50004.), format='mjd')})
table2 = Table({'new': table1['t']}, copy=False)
print(f"{table1.colnames=}, {table2.colnames=}")
# table1.colnames=['new'], table2.colnames=['new']
table3 = Table([table1['new']], names=['old'], copy=False)
print(f"{table1.colnames=}, {table2.colnames=}, {table3.colnames=}")
# table1.colnames=['new'], table2.colnames=['old'], table3.colnames=['old']
```

Not completely sure how easy it is to change this behaviour -- can we could on any mixing column to allow `new_instance = cls(old_instance, copy=False)`. The relevant code is https://github.com/astropy/astropy/blob/96dde46c854cd34cf3fd4b485d1250e32a78648e/astropy/table/table.py#L1265-L1270

**Comment by mhvk** [comment]
@taldcroft - I think the solution would be to have something like `Time`'s `replicate()` on all info. The implementation that would work for all astropy classes (I think) is
```
map = mixin.info._represent_as_dict()
map['copy'] = False
new_instance = mixin.info._construct_from_dict(map)
```

Something like this could become part of `col_copy` if it had a `copy` argument.

**Comment by taldcroft** [comment]
@mhvk - not good... unfortunately I'm trying to be mostly on vacation at the moment, but if you have ideas please have a go at trying an implementation.

**Comment by mhvk** [comment]
Actually, this turned out to be quite simple: for the non-copy case, we should use `data[:]` instead of `data` itself - that will create a new instance. It all seems to work -- see #13842
