### ISSUE TITLE
Bump minimum required Numpy to 1.20?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#13872]
Following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), which we adopted in [APE 18](https://github.com/astropy/astropy-APEs/blob/main/APE18.rst), I think we can now require numpy>1.20? If so, it would be good to do this and clean up any Numpy<1.20-related code before the 5.2 feature freeze. I won't have time to do this but if anyone wants to champion it, please go ahead! :smile:

**Comment by pllim** [comment]
Isn't that a little drastic? Jumping from `>=1.18` straight to `>1.20`.

https://github.com/astropy/astropy/blob/81669e052b8b22338dfe5f0f421dbd74e5f97766/setup.cfg#L31

**Comment by astrofrog** [comment]
I think we missed bumping it in the past which is why we would jump two versions - but I wonder if it really matters since we would still be supporting the four most recent major versions, which seems adequate?

In any case, this is what we should do if we follow APE 18 and it would be good to get back on track on the schedule we adopted there.

**Comment by pllim** [comment]
Can this stuff be automated? I keep forgetting to check such things. Like can a bot detect that it is time to bump version and open a PR to do it?

**Comment by astrofrog** [comment]
Well the doing it part is more complex than bumping the requirement in setup.cfg since there might also be old code to remove but at least opening an issue automatically would be good! I think the algorithm should be pretty deterministic.

**Comment by dhomeier** [comment]
`astropy.stats` still has some NP_LT_1_18 ... 😬

**Comment by mhvk** [comment]
See #13885.
