### ISSUE TITLE
Error while using inplace operations with numpy array slice and unitless Quantity

### ISSUE THREAD

**Issue by israelmcmc** [astropy/astropy#13911]
### Description

When doing an in-place operation on a numpy array slice and an unitless Quantity --e.g. `a[1:] += Q`-- I'm getting the following error:
```
 'numpy.ndarray' object has no attribute '_set_unit'
```

`a[1:] = a[1:] + Q` works just fine.

### Expected behavior

The result of `a[1:] = a[1:] + Q` and `a[1:] += Q` should be the same.

### Actual behavior

`'numpy.ndarray' object has no attribute '_set_unit'` error.

### Steps to Reproduce

```python
import numpy as np
from astropy.units import Quantity

a = np.array([0,1,2.])
Q = Quantity([1,2.])

# Works
a[1:] + Q

# Works
a[1:] = Q

# Works
a[1:] = a[1:] + Q

# Doesn't work
a[1:] += Q
```

### System Details

```
Darwin-21.6.0-x86_64-i386-64bit
Python 3.7.7 (default, May  6 2020, 04:59:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.21.6
pyerfa 2.0.0.1
astropy 4.3.1
Scipy 1.7.3
Matplotlib 3.4.2
```

**Comment by mhvk** [comment]
Thanks for reporting. Definitely a bug -- I think I have a fix, though...

**Comment by mhvk** [comment]
See #13913 for a fix.
