### ISSUE TITLE
Unpickled Angle.to_string fails

### ISSUE THREAD

**Issue by acenko** [astropy/astropy#13923]
### Description

Pickling and unpickling an Angle object causes the to_string function to fail claiming hourangle and degree units cannot be represented in sexagesimal notation.

### Steps to Reproduce

```python
import astropy.coordinates
import pickle
ang = astropy.coordinates.Angle(0.25 * astropy.units.hourangle)
pang = pickle.loads(pickle.dumps(ang))
ang.to_string()
# Works: 0h15m00s
pang.to_string()
# Fails: ValueError: 'hourangle' can not be represented in sexagesimal notation
```

### System Details

macOS-10.15.7-x86_64-i386-64bit
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:43:44) [Clang 13.0.1 ]
Numpy 1.23.4
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.9.3
Matplotlib 3.6.1

**Comment by pllim** [comment]
I can reproduce this also with 5.2.dev . @adrn , I vaguely remember you did some work on pickling such things?

**Comment by mhvk** [comment]
Bit of troubleshooting: if one does `%debug` at that point, then `unit is u.hourangle` will return `False`, and thus one misses the branch that should typeset this: https://github.com/astropy/astropy/blob/0c37a7141c6c21c52ce054f2d895f6f6eacbf24b/astropy/coordinates/angles.py#L315-L329

The easy fix would be to replace `is` with `==`, but in princple I think pickling and unpickling the unit should have ensured the unit remains a singleton.

**Comment by mhvk** [comment]
It seems like currently with pickle we guarantee only `IrreducibleUnits`?
```
In [5]: pickle.loads(pickle.dumps(u.hourangle)) is u.hourangle
Out[5]: False

In [6]: pickle.loads(pickle.dumps(u.rad)) is u.rad
Out[6]: True

In [7]: pickle.loads(pickle.dumps(u.deg)) is u.deg
Out[7]: False
```

**Comment by mhvk** [comment]
OK, I think `==` is correct. Will have a fix shortly.
