### ISSUE TITLE
Apply `black` to `astropy.nddata`

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13945]
Apply `black` to `astropy.nddata` according to the process laid out by [APE 20](https://github.com/astropy/astropy-APEs/blob/main/APE20.rst).

**Comment by pllim** [comment]
Do we really need an issue for each subpackage? Can't we make #13942 an epic and track stuff there?

Or I thought we have a project board.

**Comment by nstarman** [comment]
This issue is in the Project board! Projects will track issues and PRs and auto-move them as they progress through the Todo -> doing -> done pipeline.

**Comment by pllim** [comment]
You can create project board cards without making it an issue...

**Comment by nstarman** [comment]
https://github.com/orgs/astropy/projects/10/views/2 
The problem is that this project isn't showing up on Astropy Issues  and PRs (even though they are showing up on the Project!). My cosmology Project is working just fine.

**Comment by pllim** [comment]
What do you mean? I can see it just fine over at #13253

![Screenshot 2022-11-01 102748](https://user-images.githubusercontent.com/2090236/199257272-087c5dde-5270-40a2-b7bd-0aaff7052d33.jpg)

**Comment by nstarman** [comment]
Maybe it's mobile that's broken! I was looking on my phone, and this is what I see ![image](https://user-images.githubusercontent.com/8949649/199257760-e4e7ecfe-720d-4ec3-b6bf-7cc8b24785a5.png)

**Comment by pllim** [comment]
The mobile API can be a pain but shouldn't be a reason to spam the issues list?

**Comment by nstarman** [comment]
> You can create project board cards without making it an issue...

Yes, but then they don't get auto-completed nor are they particularly visible for reviewers. AFAIK GH wants draft -> issue -> PR

**Comment by pllim** [comment]
You can put a link to the project board on your PRs if you want. Otherwise reviewers will get notified when you chose them to review the PR.
