### ISSUE TITLE
New to the open source software and contribution world.

### ISSUE THREAD

**Issue by ChinmayNadgouda** [astropy/astropy#13954]
Hello,

I am a Master's student in Computer Science from the University of Stuttgart, Germany, and currently am attending the course, Simulation Software Engineering (SSE). https://simulation-software-engineering.github.io/homepage/

For this course, we students were asked to select an open-source simulation framework, like Astropy and make a small contribution to get acquainted with such open-source software development tool and their practices.

For this, I am interested in Astropy and am now looking for something to work on. There are no clear expectations as to what this contribution should be. It can be one of the following, a new feature, a tutorial, some documentation or a bug fix.

I am quite new to this field of simulation softwares but eager to learn and would really like to contribute something useful, so can somebody suggest something for me to contribute to, considering me as a novice?

Also, I would like your input and guidance on how to get get started / acquainted with Astropy and understand it better, so that I can give a meaningful contribution.

If no,
Can you point me to something else that I can contribute to in Astropy?

Thanks 😄

**Comment by pllim** [comment]
Hello and thank you for your interest! There is a dev guide at https://docs.astropy.org/en/latest/development/workflow/development_workflow.html . It is quite a read but hopefully helpful to get you started.

We also have issues labeled as "good first issue" at https://github.com/astropy/astropy/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 -- Hopefully one of them would suit your skills and interests?

**Comment by pllim** [comment]
Hi again. It has been many months and I do not see any PRs linked to this issue. Therefore, I am closing this. In the future, if you are interested in contributing for a specific issue, please comment on that issue directly. Thank you.
