### ISSUE TITLE
sys.getrefcount is used unconditionally in io/fits/file.py, but is an implementation detail of CPython

### ISSUE THREAD

**Issue by mattip** [astropy/astropy#13978]
### Description

Over at conda-forge/pysynphot-feedstock#7, there is a failure due to astropy [using sys.getrefcount](https://github.com/astropy/astropy/blob/6400c89e58add0e8b96e00f26dcd48b877c2acc9/astropy/io/fits/file.py#L444) on PyPy. That function is an implementation detail of CPython's reference counting garbage collector and doesn't make sense on PyPy. There is an additional use of getrefcount [here](https://github.com/astropy/astropy/blob/6400c89e58add0e8b96e00f26dcd48b877c2acc9/astropy/io/fits/hdu/base.py#L171)
### Expected behavior

I expected that PR to be mergeable
### Actual behavior

Project tests failed when using `astropy/io/fits/hdu/hdulist.py`
### Steps to Reproduce

I am not sure how pysynphot got to use hdulist.

### System Details

This code is quite old, I don't know why it has not been hit before. It seems to be an attempt to discover if anyone else is holding a reference to the file object.

**Comment by pllim** [comment]
Would something like https://github.com/astropy/astropy/pull/13979 even be correct? 🤷

**Comment by saimn** [comment]
Astropy doesn't officially support PyPy currently. There was some discussion a long time ago (#7768), and I also addressed some issues (#7775) but leaving the refcounting one for later ;). I guess we could reopen this subject, but keeping in mind that we never got any request to support PyPy since the issues I mentioned. The refcount thing could be easy to fix with something like #13979 but there may be other issues, so at least for now building conda packages seems premature.

**Comment by pllim** [comment]
@mwcraig , should we take astropy back out from conda-forge PyPy builds?

**Comment by mwcraig** [comment]
> @mwcraig , should we take astropy back out from conda-forge PyPy builds?

Maybe...it was useful to at least surface the issue. I can look into pulling the release next week, but suspect that doing so will be a bit of a headache since so many things had built on top of it.

**Comment by saimn** [comment]
Amongst other things there may be problems with the C extensions, Cython and ctypes may be OK, but I guess C-extensions using the CPython API are not ? We don't run tests on PyPy so I guess we will know when someone wants to try ;).

**Comment by mattip** [comment]
The refcount issue here actually is not connected with the CPython CAPI, it is a problem with tracking references to open handles (mmapped files) to make sure no-one else is holding them.

**Comment by saimn** [comment]
@mattip - Sure, just mentioning that the refcount issue is probably not the only problem we will have to support PyPy.
