### ISSUE TITLE
ITRF coordinates with RA and DEC coordinates to ICRS or FK5

### ISSUE THREAD

**Issue by miguelcarcamov** [astropy/astropy#13980]
Hello,

There has been a discussion on the [astropy's slack channel](https://astropy.slack.com/archives/C0LAGR5TP/p1667413626294429). Long story short, in some radio measurement sets there are fields (pointings) with RA and DEC and a ITRF frame. In the thread, you can see that astropy has ITRS which is basically the same as ITRF. However, radio measurement sets use RA and DEC for the coordinates and not the earth location. In that sense, could be possible to instantiate a SkyCoord object using a "itrs" frame and RA and DEC coordinates?

Please check this weblinks:
[1](https://physics.stackexchange.com/questions/511706/converting-coordinates-from-celestial-reference-frame-to-terrestrial-reference-f)
[2](https://github.com/casacore/casacore/issues/1107)

Please don't hesitate on asking me for radio measurement sets in order to test this :)

Cheers,

**Comment by eerovaher** [comment]
> could be possible to instantiate a SkyCoord object using a "itrs" frame and RA and DEC coordinates?

Right ascension and declination are celestial coordinates used by equatorial (FK4, FK5) or equatorial-like (ICRF) coordinate frames that are meant to be independent of the rotation of the Earth. ITRS on the other hand is designed to co-rotate with the Earth, so I don't understand what RA and Dec in ITRS are even supposed to mean.

**Comment by miguelcarcamov** [comment]
> > could be possible to instantiate a SkyCoord object using a "itrs" frame and RA and DEC coordinates?
> 
> Right ascension and declination are celestial coordinates used by equatorial (FK4, FK5) or equatorial-like (ICRF) coordinate frames that are meant to be independent of the rotation of the Earth. ITRS on the other hand is designed to co-rotate with the Earth, so I don't understand what RA and Dec in ITRS are even supposed to mean.

I don't know either really @eerovaher. First, I don't know much about coordinate systems. However, we have just noticed that some ALMA measurement sets have fields with reference direction and phase direction with ra and dec in radians, and frame ITRF. I have sent a ticket to the ALMA helpdesk because of this as well because it is very confusing.

**Comment by miguelcarcamov** [comment]
I'm going to close this as I figured out that there is another array on the Measurement Set table named TabRefCodes that tells you which string the field is using. Turns out that was ICRS and not ITRF. Thanks!
