### ISSUE TITLE
Site locations not being recognised by EarthLocation

### ISSUE THREAD

**Issue by CheerfulUser** [astropy/astropy#13998]
### Description
I've run into a problem where the EarthLocation function is not finding data for observatories that are listed in the astropy-data sites.json file. I've attached an example for ASKAP, which is listed on the sites.json starting at line 1209, as of posting. After some checks this problem applies to a number of different sites.

```python
from astropy.coordinates import EarthLocation
EarthLocation.of_site('askap')
```
which returns:
```python 
UnknownSiteException: "Site 'askap' not in database. Use EarthLocation.get_site_names to see available sites."
```

Section for ASKAP in sites.json:
<img width="583" alt="askap_info" src="https://user-images.githubusercontent.com/25831737/200937834-4f5d36fc-4b06-4e29-a8de-0f624afb1802.png">

### System Details
macOS-12.5.1-arm64-arm-64bit
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) 
[Clang 13.0.1 ]
Numpy 1.23.1
pyerfa 2.0.0.1
astropy 5.2.dev969+g094460711.d20221109
Scipy 1.8.1
Matplotlib 3.5.2

**Comment by pllim** [comment]
Is your cache outdated?

**Comment by pllim** [comment]
Try run this locally but add a `cache="update"` maybe?

https://github.com/astropy/astropy/blob/0944607116f373e64e94ce3e5535c49509897c87/astropy/coordinates/sites.py#L139

**Comment by CheerfulUser** [comment]
That solved it, thanks!
