### ISSUE TITLE
Parquet connector does not support writing variable length arrays

### ISSUE THREAD

**Issue by tgoldina** [astropy/astropy#14000]
### Description
When converting column types into PyArrow types, variable length array column (which has `dtype=np.object_`) needs special handling. An example code that recognizes variable length arrays can be found in https://github.com/astropy/astropy/blob/main/astropy/table/meta.py#L240.

### Expected behavior
Writing an astropy Table to a Parquet file with `table.write(filename, format="parquet")` should be successful.

### Actual behavior
If an astropy Table has a variable array column, writing it to a Parquet file triggers an error "ArrowNotImplementedError: Unsupported numpy type 17"

### Steps to Reproduce

1. Create an astropy Table with variable array column, see [example](https://docs.astropy.org/en/stable/io/fits/usage/unfamiliar.html#creating-a-variable-length-array-table).
2. Write this table to a Parquet file.

```python
import numpy as np
from astropy.table import Table, Column

# create a table with variable length array column
col1 = Column(np.array([[45, 56], [11, 12, 13]], dtype=np.object_),
              name='varlen_arr', unit='m')
vlt_tbl = Table([col1])

# write it as a VOTable - OK
vlt_tbl.write("variable_length_tbl.vo", format="votable", overwrite=True)

# write it as a Parquet file - Failure
vlt_tbl.write("variable_length_tbl.parq", format="parquet", overwrite=True)
```

### System Details

macOS-11.6.8-x86_64-i386-64bit
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:43:44) [Clang 13.0.1 ]
Numpy 1.23.3
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.9.1
Matplotlib 3.6.0

**Comment by pllim** [comment]
Does parquet actually support that kind of datatype? https://arrow.apache.org/docs/python/data.html#type-metadata says variable length is only for binary or string but maybe I misunderstood.

**Comment by tgoldina** [comment]
You can define variable length arrays with ListType:
```
import pyarrow as pa

lfloat64 = pa.list_(pa.float64())
lfloat32 = pa.list_(pa.float32())
lint64 = pa.list_(pa.int64())
lint8 = pa.list_(pa.int8())
lbool = pa.list_(pa.bool_())
```

**Comment by pllim** [comment]
Hmm. Parquet was added in https://github.com/astropy/astropy/pull/12215 . Maybe @erykoff can comment.

**Comment by erykoff** [comment]
See PR #14237.  Sorry I didn't have a chance to do anything about this until now.

Meanwhile, I should note that I have not been able to find any documentation on astropy supporting variable-length columns, although it does.  There's only documentation for how to access them with fits.
