### ISSUE TITLE
Julian conversion of BC dates appears incorrect

### ISSUE THREAD

**Issue by cnighswonger** [astropy/astropy#14024]
### Description
Conversion of fits format BC dates to jd format appears incorrect.

### Expected behavior
Correct conversion is expected.

### Actual behavior
Incorrect conversion happens.

### Steps to Reproduce
```python
>>> import numpy as np
>>> from astropy.time import Time
>>> d = Time('-01973-10-21T00:00:00', format='fits', scale= 'utc')
>>> print(d)
-01973-10-21T00:00:00.000(UTC)
>>> print(d.jd)
1000729.5
>>>
```
Checking this against [JPL's Julian date converter](https://ssd-api.jpl.nasa.gov/jd_cal.api?jd=1000729.5&www=1) shows a difference of 14 days.

### System Details
```python
>>> import platform; print(platform.platform())
Windows-7-6.1.7601-SP1
>>> import sys; print("Python", sys.version)
('Python', '2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]')
>>> import numpy; print("Numpy", numpy.__version__)
('Numpy', '1.16.6')
>>> import erfa; print("pyerfa", erfa.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named erfa
>>> import astropy; print("astropy", astropy.__version__)
('astropy', u'2.0.16')
>>> import scipy; print("Scipy", scipy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named scipy
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named matplotlib
>>>
```

**Comment by eerovaher** [comment]
As explained in the [JPL Date/Time Converter API documentation](https://ssd-api.jpl.nasa.gov/doc/jd_cal.html) dates as old as you are considering are given in the Julian calendar. However, the `fits` format you are explicitly using in your code interprets dates in the Gregorian calendar even if they refer to a time before the 1582 calendar reform by Gregory XIII, see page 3 at [Representations of Time Coordinates in FITS](https://arxiv.org/abs/1409.7583). So there is no bug here, the difference in dates you are reporting is the difference between the Julian and Gregorian calendars at the relevant time.
