### ISSUE TITLE
How to join/merge data tables with join_skycoord based on close ra, dec?

### ISSUE THREAD

**Issue by Nestak2** [astropy/astropy#14023]
### Description
I have 2 astronomical tables from 2 different observational surveys, from a fits file and a csv file, that look something like this

```
ra, dec, val_a, val_b, ...
11.11, 22.22, 8, 9, ...
10.10, 20.20, 7, 6, ...
...
```

and this

```
ra, dec, val_x, val_y, ...
44.4, 55.55, 8, 9, ...
15.67, 23.45, 7, 6, ...
...
```

One table contains 15M galaxies and the other 80k. I would like to merge/cross-match the objects in these 2 tables with astropy, as long as corresponding objects have a separation smaller than a threshold distance in degrees. I know how to load the tables into astropy tables. And I know of the existence of [skycoord](https://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord) and the [join_skycoord](https://docs.astropy.org/en/stable/api/astropy.table.join_skycoord.html#astropy.table.join_skycoord) function. But I am not able to apply them, because I don't find anywhere explained how when reading a table I specify skycoord columns or how I can later change the type of the columns to skycoord or how I can merge skycoord columns into my tables. 

Can someone provide me with code that can merge the 2 tables based on the sky coordinates? I would be also thankful for alternatives, that don't utilize astropy. Tnx

**Comment by pllim** [comment]
Hello! If you do not get any response here, please try https://community.openastronomy.org/c/astropy/8 . Thanks,

**Comment by ManonMarchand** [comment]
If you're open to using an other tool you can use astroquery.xmatch 
https://astroquery.readthedocs.io/en/latest/xmatch/xmatch.html

**Comment by eerovaher** [comment]
> ... I don't find anywhere explained how when reading a table I specify skycoord columns or how I can later change the type of the columns to skycoord or how I can merge skycoord columns into my tables.

Assuming `t` is a `QTable` that includes columns `"ra"` and `"dec"` with the correct units then the following adds a `SkyCoord` instance representing the coordinates in ICRS as a new column named `"icrs_skycoord"`:
```python
t["icrs_skycoord"] = SkyCoord(ra=t["ra"], dec=t["dec"], frame="icrs")
```
See also https://docs.astropy.org/en/stable/table/mixin_columns.html
