### ISSUE TITLE
Absolute imports

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#14021]
### Description

In PEP8 absolute imports are preferred over relative ones. I think we should switch, with a pre-commit hook, e.g. https://github.com/MarcoGorelli/absolufy-imports. We can do the whole repo in one go and add a git-blame-ignore if we want, though it's only imports being changed.

A nice explanatory block on the pros and cons of absolute imports from https://realpython.com/absolute-vs-relative-python-imports/#pros-and-cons-of-absolute-imports

> Pros and Cons of Absolute Imports
> Absolute imports are preferred because they are quite clear and straightforward. It is easy to tell exactly where the imported resource is, just by looking at the statement. Additionally, absolute imports remain valid even if the current location of the import statement changes. In fact, PEP 8 explicitly recommends absolute imports.

> Sometimes, however, absolute imports can get quite verbose, depending on the complexity of the directory structure. Imagine having a statement like this:

> from package1.subpackage2.subpackage3.subpackage4.module5 import function6
That’s ridiculous, right? Luckily, relative imports are a good alternative in such cases!

Absolute imports are better at preventing circular dependencies and are more explicit. Also, with `black` causing line wraps absolute imports are frequently equally verbose as the relative import.

**Comment by nstarman** [comment]
Presumably for v5.3.

**Comment by mhvk** [comment]
We did this for the tests, where it made a lot of sense. I'm less sold on things like `__init__.py`, where I think it is very helpful to see at a glance what the local imports are. I'd quite happily get rid of any "level-up" relative imports (`..`), though. Overall, to me readability suggests sticking roughly with what we have.

**Comment by nstarman** [comment]
A prompt response

> Hey @nstarman
> thanks for the suggestion, but no thanks (you're welcome to fork though, this is MIT licensed)

So... maybe we should do that.
