### ISSUE TITLE
Convolution import error with setuptools v65.6.0

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#14025]
[setuptools v65.6.0](https://setuptools.pypa.io/en/latest/history.html#v65-6-0) made a change in their bundled version of distutils, which is breaking the import of the compiled extension in `convolution`, which is done with `numpy.ctypeslib.load_library` (which depends on `numpy.distutils`).
Some of our builds are failing (currently RTD and wheels, but it seems the tox based one are still using the previous version of setuptools, probably because [virtualenv](https://virtualenv.pypa.io/en/latest/changelog.html) did not update yet):
```
Traceback:
../astropy/astropy/test-sdist/lib/python3.11/site-packages/astropy/convolution/convolve.py:28: in <module>
    _convolve = load_library("_convolve", LIBRARY_PATH)
../astropy/astropy/test-sdist/lib/python3.11/site-packages/numpy/ctypeslib.py:137: in load_library
    from numpy.distutils.misc_util import get_shared_lib_extension
../astropy/astropy/test-sdist/lib/python3.11/site-packages/numpy/distutils/__init__.py:26: in <module>
    from . import ccompiler
../astropy/astropy/test-sdist/lib/python3.11/site-packages/numpy/distutils/ccompiler.py:20: in <module>
    from numpy.distutils import log
../astropy/astropy/test-sdist/lib/python3.11/site-packages/numpy/distutils/log.py:4: in <module>
    from distutils.log import Log as old_Log
E   ImportError: cannot import name 'Log' from 'distutils.log' (/home/runner/work/astropy/astropy/test-sdist/lib/python3.11/site-packages/setuptools/_distutils/log.py)
```

Ref https://github.com/numpy/numpy/issues/22623, https://github.com/pypa/setuptools/issues/3693

**Comment by pllim** [comment]
This is affected downstream CIs left and right. We need to patch it up soon with something...

**Comment by Cadair** [comment]
Am I correct in the understanding that the long term answer he is that we need to stop using `numpy.distutils` ?

**Comment by Cadair** [comment]
A short term answer may be to pin down setuptools everywhere?

**Comment by pllim** [comment]
Or maybe refactor that convolution code to not be C-extension? Or have it only emit warning on fail?

**Comment by saimn** [comment]
Pinning setuptools would mean adding it to our dependencies, not great. There are a few other solutions:
- setuptools may revert their patch and deprecate `distutils.log` before removing it
- numpy may move `get_shared_lib_extension` from `numpy.distutils` to maybe `numpy.ctypeslib` 
- we can wrap the C convolution extension with something else, replace `ctypes` with e.g. cython or a pure C extension (first one should be easy, second one requires a bit more work and knowledge)

**Comment by saimn** [comment]
Some projects are only affected when installing. `SETUPTOOLS_USE_DISTUTILS` or pinning in `pyproject.toml` would work in this case. But we use `numpy.ctypeslib.load_library` at runtime, to load the C extension. So I don't think asking users to run their python with `SETUPTOOLS_USE_DISTUTILS=stdlib` is a good solution ;).

**Comment by pllim** [comment]
Just fixing RTD would be a nice first step... 😬

**Comment by pllim** [comment]
FWIW, pinning setuptools just under docs requirements alone is enough to make RTD happy, see https://github.com/spacetelescope/jdaviz/pull/1861

**Comment by astrofrog** [comment]
> Or maybe refactor that convolution code to not be C-extension? Or have it only emit warning on fail?

We could also update the C extension to not be imported via ctypes but use a regular C extension instead as we do elsewhere (such as in io.fits or wcs)

**Comment by astrofrog** [comment]
Ah or via cython as done in https://github.com/astropy/astropy/pull/14035

**Comment by saimn** [comment]
Also setuptools v65.6.1 has just been released, putting back a `disutils.Log` class with a deprecation warning:
https://setuptools.pypa.io/en/latest/history.html#v65-6-1

**Comment by pllim** [comment]
Thanks, all!
