### ISSUE TITLE
astropy.table should support additional metadata (e.g. UCDs)

### ISSUE THREAD

**Issue by aragilar** [astropy/astropy#14036]
### Description
Currently the only metadata you can have for tables/columns are units, names and descriptions. It would be really useful if there was a way to add additional metadata, such as UCDs, utypes, xtypes etc.

**Comment by eerovaher** [comment]
It is already possible to add arbitrary metadata to a table and its columns:
```python
>>> from astropy.table.table_helpers import simple_table
>>> t = simple_table(3)
>>> t.meta
OrderedDict()
>>> t["a"].info.meta
OrderedDict()
```
Or did you have something else in mind?

**Comment by aragilar** [comment]
Ah, cool. Do you know if UCDs etc. are handled such that readers/writers pass through the different astro formats correctly? Would roundtripping through FITS work for a VOTable for example?

**Comment by pllim** [comment]
I don't think there is a full roundtrip support for metadata. At least I don't see it here:

https://github.com/astropy/astropy/blob/252055ef3b9d6be3dd0e7ab3e7b70e1f28b80421/astropy/io/fits/convenience.py#L468

If you are talking about VOTable and `astropy.table.Table`, you would want to look at these:

https://github.com/astropy/astropy/blob/252055ef3b9d6be3dd0e7ab3e7b70e1f28b80421/astropy/io/votable/connect.py#L133

https://github.com/astropy/astropy/blob/252055ef3b9d6be3dd0e7ab3e7b70e1f28b80421/astropy/io/votable/tree.py#L3276

**Comment by eerovaher** [comment]
ECSV has roundtrip support for metadata, I wouldn't know about the other formats out of the top of my head.

**Comment by aragilar** [comment]
Cool. The background for this was I was fixing up by hand some metadata in FITS files originally written by astropy.tables that were going to be ingested into a TAP system, and I couldn't see an obvious way to add UCDs etc. If this comes up again, I'll see if I can create a PR.

**Comment by eerovaher** [comment]
At least the following simple example does work:
```python
>>> from astropy.table import QTable
>>> t = QTable({"a": [0, 1]})
>>> t["a"].info.meta["ham"] = "spam"
>>> t.write("temp.fits")
>>> print(QTable.read("temp.fits")["a"].info.meta)
OrderedDict([('ham', 'spam')])
```
