### ISSUE TITLE
Degrees Celsius should be supported by FITS units

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#14033]
### Description

The FITS standards says that units should follow IAU recommendations. These note that:

> The degree Celsius (`°C` in the original PDF, `oC` in the web page???) is used in specifying temperature for meteorological purposes, but otherwise the kelvin (K) should be used.

However, astropy does not support `u.deg_C` for fits:

```
import astropy.units as u

u.deg_C.to_string("fits") # exception
```

### Additional context
See 
* https://www.iau.org/publications/proceedings_rules/units/
* https://www.iau.org/static/publications/stylemanual1989.pdf

**Comment by maxnoe** [comment]
The question is what is the correct symbol? Is there any precedent? because it cannot be `°C`, as `°` is not in ASCII.

**Comment by mhvk** [comment]
@maxnoe - ideally, we stick with whatever actually is used in the wild. Do you have examples of FITS files that have temperatures in C?

**Comment by maxnoe** [comment]
We have files that use `deg C`, which is parsed by astropy as degree * Coulomb ....

**Comment by maxnoe** [comment]
I asked the fits support office for guidance on this

**Comment by mhvk** [comment]
I think we should be able to special-case that. After all, `deg * C` does not make much sense... Though, really, spaces in the units is pretty bad form!

**Comment by maxnoe** [comment]
I received the following answer:

> Many astronomical observatories record the ambient air temperature or the detector temperature in their FITS data files and I think it is safe to say that most of them use units of Celsius degrees (which is more understandable to most people) rather than pedantically following the recommendation in the FITS Standard to convert to units of Kelvin.  When recording the temperature value in a FITS header keyword they often use a units string of “deg C” or sometimes “Celsius” as in
>
> `CCDTEMP =                18.5 / [deg C] detector temperature in degrees Celsius`
> or
> `CCDTEMP =                18.5 / [Celsius] detector temperature in degrees Celsius`
>
> Hope this helps,

So according to this, we should probably add support for `Celsius` and `deg C` and use `Celsius` in our own output as it is not ambiguous?

**Comment by mhvk** [comment]
Sounds good!
