### ISSUE TITLE
Unnecessary import of astropy.table can slow down load of a FITS file

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#14030]
I am doing a little bit of io.fits benchmarking and one thing I just noticed is [this](https://github.com/astropy/astropy/blob/main/astropy/io/fits/hdu/table.py#L915) import of `astropy.table` can take a significant fraction of the load time of a FITS file even in cases where it isn't needed at all.

The easiest optimisation would be to only try the table import if `data is not None` but someone with a little more imagination might be able to optimise further.

My truncated pyinstrument trace:
```
0.488 <module>  initial_benchmarks_astropy.py:1
├─ 0.207 HDUList.__getitem__  ../../../Git/astropy/astropy/io/fits/hdu/hdulist.py:304
│  └─ 0.207 HDUList._try_while_unread_hdus  ../../../Git/astropy/astropy/io/fits/hdu/hdulist.py:1171
│     └─ 0.207 HDUList._read_next_hdu  ../../../Git/astropy/astropy/io/fits/hdu/hdulist.py:1188
│        └─ 0.207 _BaseHDU.readfrom  ../../../Git/astropy/astropy/io/fits/hdu/base.py:299
│           └─ 0.207 CompImageHDU._readfrom_internal  ../../../Git/astropy/astropy/io/fits/hdu/base.py:382
│              └─ 0.206 CompImageHDU.__init__  ../../../Git/astropy/astropy/io/fits/hdu/compressed.py:403
│                 └─ 0.206 CompImageHDU.__init__  ../../../Git/astropy/astropy/io/fits/hdu/table.py:851
│                    └─ 0.206 <module>  ../../../Git/astropy/astropy/table/__init__.py:1
```

**Comment by saimn** [comment]
The import is needed to find if the object is a `Table`, not sure how to improve that (the `data=None` case is not the main one). Maybe this feature should have been implemented as a class method instead, but not sure how to name it, `BinTableHDU.from_table` seems confusing :sweat_smile:

**Comment by pllim** [comment]
Never put a FITS issue as "good first issue." 😉

**Comment by Cadair** [comment]
> the data=None case is not the main one

It is when you are reading a file? This was the case when I found the issue.

> Never put a FITS issue as "good first issue."

In my opinion there is real benefit to adding `if data is not None:` and if that isn't a "good first issue" I don't know what is.

**Comment by saimn** [comment]
Oh right, when reading a file `data` is set to `DELAYED`, so we could actually improve import time by checking both `None` and `DELAYED`.

**Comment by saimn** [comment]
Let's try with "good first issue" then :)

**Comment by Kaushik-Iyer** [comment]
Should I try to work on this? The large code file scares me though

**Comment by pllim** [comment]
@Kaushik-Iyer , thanks for your interest. If you are not able to make sense of stuff after an hour or two, I would suggest you tackle a different issue.

**Comment by Chris2W** [comment]
I would like to tackle this issue.
