### ISSUE TITLE
Time's plot_date depends on whether matplotlib is installed

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#14080]
Not sure this is strictly a bug, but it certainly is surprising (see very puzzled trail at https://github.com/astropy/asdf-astropy/pull/139):

Without matplotlib installed:
```
from astropy.time import Time
Time("2000-01-01T00:00:00.000").plot_date
# 730120.0
```

With matplotlib installed
```
Time("2000-01-01T00:00:00.000").plot_date
# 10957.0
```

I think this has to do with matplotlib changing its base epoch. But perhaps we should avoid the temptation to guess if matplotlib is not installed? cc @taldcroft.

**Comment by taldcroft** [comment]
Yup, that would be related to the base epoch issue. 
https://github.com/astropy/astropy/blob/27cf81dff23876fa871786d7ee710cb4c120c413/astropy/time/formats.py#L892

At the time the rationale was that they introduced the new `get_epoch()` function, and if that didn't exist (in an older version of matplotlib < 3.3) then using the old base epoch was the right thing.

@mvhk - about avoiding the temptation to guess, what are you thinking there?

**Comment by taldcroft** [comment]
At some level the takeaway here is that the numerical value of `plot_date` is quite connected to the installed matplotlib. So it would be a bad idea to serialize the `plot_date` values.

**Comment by mhvk** [comment]
I was thinking of raising an error if `matplotlib` is not installed... Could be a warning too, I guess, to not break things.

**Comment by mhvk** [comment]
Yes, for serializing this suggests that using `jd1, jd2` is really the way to go.

**Comment by taldcroft** [comment]
I am :-1: on an error since that is likely break some testing somewhere. A warning would not actually solve the problem (of different values depending on matplotlib being available), but it would certainly make it easier to diagnose. And of course warnings turn into errors in most testing, so adding a warning can break testing as well. Sigh.

**Comment by mhvk** [comment]
We could also just change the default...  Presuming the epoch now chosen by matplotlib is pretty stable.

**Comment by taldcroft** [comment]
I thought about that, but astropy still supports matplotlib 3.1+. So that would break for folks using 3.1 or 3.2.

**Comment by mhvk** [comment]
> I thought about that, but astropy still supports matplotlib 3.1+. So that would break for folks using 3.1 or 3.2.

Not necessarily: if `matplotlib` is installed, there is no reason to change the current state. It would only be for the case that `matplotlib` is not installed.

Though to me the ideal state would still seem to be to refuse the temptation to guess. An alternative might be a configuration item, which allows one to give a default if `matplotlib` is not available.

Though perhaps we are just overthinking this... We have not had problems with the current setup until now, so maybe we'll be fine for another 10 years!?

**Comment by taldcroft** [comment]
> Though perhaps we are just overthinking this... We have not had problems with the current setup until now, so maybe we'll be fine for another 10 years!?

Agreed. This is pretty far down in the weeds and definitely low in the priority list of things to do. I'm marking this as `Close?`, but you can feel free to unlabel it if you want to keep this open.

**Comment by mhvk** [comment]
Sounds good.
