### ISSUE TITLE
v5.2rc1 astropy.test also runs tests in astropy.extern if installed in a tox environment

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#14089]
I thought I could be clever and do my affiliated package (`baseband`) and astropy tests at the same time by `tox -e test` in baseband and then get that environment `source .tox/test/bin/activate` and install the release candidate in there. The baseband tests indeed pass, but `astropy.test()` does not: running `astropy.test()`, the tests also go down `astropy.extern`:
```
.tox/test/lib/python3.9/site-packages/astropy/cosmology/tests/test_units.py ...sssssss.ssssssssssss.                                                      [ 31%]
.tox/test/lib/python3.9/site-packages/astropy/cosmology/tests/test_utils.py ...................                                                           [ 31%]
.tox/test/lib/python3.9/site-packages/astropy/extern/configobj/configobj.py F....F..                                                                      [ 31%]
.tox/test/lib/python3.9/site-packages/astropy/extern/configobj/validate.py FF.FFFFFFFFFFF..F.FFFFFFFFFFFFFFF.                                             [ 32%]
```
Clearly, this is not meant to happen!

And indeed, it does not happen in a clean virtual environment, so there is something odd about the `.tox` environment (maybe related to another version of astropy having been installed; or maybe just that `pip` is a pretty terrible package manager?).

Not sure this is worth investigating in any detail, but perhaps someone has a clue what is going on.

**Comment by pllim** [comment]
So like #14088 ?

**Comment by pllim** [comment]
Also, I am curious, do the tests still fail if you run the two different test suites back to back but in some env that is not tox? Like conda env?

**Comment by mhvk** [comment]
In a way, this one is even weirder: why would the selection of what gets tested depend on the environment? But I'm not sure I have the bandwidth to investigate this in any detail -- auto-closing seems appropriate...

**Comment by pllim** [comment]
No idea... somehow it changes the test collection logic. I mean, why are these files even picked up?

```
astropy/extern/configobj/configobj.py
astropy/extern/configobj/validate.py
```

**Comment by mhvk** [comment]
Indeed, it makes no sense! 

I tried a bit more and think it has nothing to do with baseband but perhaps still with `tox`. I can reproduce it partially with (in astropy package directory):
```
tox -e test --notest
source .tox/test/bin/activate
cd ~  # out of source directory
python -c "import astropy; astropy.test(package='extern')"
# but extern gets correctly skipped with: 
python -c "import astropy; astropy.test()"
```

With a bit more testing, though, it does seem the error with the full test suite is all about bad cleanup.

**Comment by pllim** [comment]
Same comment as https://github.com/astropy/astropy/issues/14088#issuecomment-1334112487 -- could be that it is time we retire the test runner altogther. It pre-dated tox.
