### ISSUE TITLE
Error importing io.ascii

### ISSUE THREAD

**Issue by opticallythick** [astropy/astropy#14095]
### Description

Receive an error: "AttributeError: 'NoneType' object has no attribute 'expandtabs'" when importing astropy.io.ascii
Perhaps a docstring not being passed to inspect.py

### Expected behavior

The module would be successfully loaded

### Steps to Reproduce

```python
# other modules import fine
>>> import astropy
>>> import astropy.io
>>> import astropy.io.fits as fits

# ascii does not
>>> import astropy.io.ascii
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.9/site-packages/astropy/io/ascii/__init__.py", line 20, in <module>
    from .basic import (Basic, BasicHeader, BasicData,
  File "/usr/local/anaconda3/lib/python3.9/site-packages/astropy/io/ascii/basic.py", line 42, in <module>
    class Basic(core.BaseReader):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 1159, in __init__
    func.__doc__ += inspect.cleandoc(cls.__doc__).strip()
  File "/usr/local/anaconda3/lib/python3.9/inspect.py", line 632, in cleandoc
    lines = doc.expandtabs().split('\n')

AttributeError: 'NoneType' object has no attribute 'expandtabs'
```

### System Details

Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]
Numpy 1.21.5
pyerfa 2.0.0
astropy 5.0.4
Scipy 1.7.3
Matplotlib 3.5.1

**Comment by pllim** [comment]
Hello! It appears that you are using the base environment of full Anaconda. Can you please try this and see if you can import `astropy.io.ascii`? Thanks!

```
conda create -n astroenv python=3.9
conda activate astroenv
conda install astropy -c conda-forge
```

**Comment by opticallythick** [comment]
I thought I was using a dedicated conda environment, but I ran those commands anyway, with the same error on the import astropy.io.ascii command.

But it turns out that somewhere along the way, the shell environment variable PYTHONOPTIMIZE had been set to 3.
It appears that if this variable is set to any value of 2 or greater, it will cause this error. PYTHONOPTIMIZE=1 works fine. I don't know how this is connected to a docstring error.

```
(astroenv)> export PYTHONOPTIMIZE=1 ; python
Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
>>> import astropy.io.ascii
>>> quit()

(astroenv)> export PYTHONOPTIMIZE=2 ; python
Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
>>> import astropy.io.ascii
...
AttributeError: 'NoneType' object has no attribute 'expandtabs'
```

**Comment by eerovaher** [comment]
Setting [`PYTHONOPTIMIZE`](https://docs.python.org/3.9/using/cmdline.html#envvar-PYTHONOPTIMIZE) to 2 or greater is equivalent to specifying the [`-OO`](https://docs.python.org/3.9/using/cmdline.html#cmdoption-oo) option, which tells Python to discard docstrings. What you are reporting is not a bug in `astropy`, it is a feature of Python.

**Comment by pllim** [comment]
@opticallythick , thanks for tracking it down and reporting back!
