### ISSUE TITLE
v5.2rc1 `_download_file_from_source` does not catch `URLError` on Python 3.10.8 + 3.11.0

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#14091]
### Description
On latest 3.10 and 3.11 Pythons `test_ftp_tls_auto` fails on `download_file(url)` with
>           raise URLError(exp) from exp
> E           urllib.error.URLError: <urlopen error 530 Anonymous sessions must use encryption.>

### Expected behavior
Call to `astropy.utils.data._download_file_from_source(url)` with the default `ftp_tls=None` should revert to `ftp_tls=True` after raising a permission exception.

### Actual behavior
Exception handling has changed in 3.10.8 and 3.11.0 with python/cpython#24938, now raising with the original error message instead of the "ftplib error" expected by `_download_file_from_source`.

Can be fixed by changing https://github.com/astropy/astropy/blob/252055ef3b9d6be3dd0e7ab3e7b70e1f28b80421/astropy/utils/data.py#L1287
to
```python
            if str(e.reason).startswith(("ftp error: error_perm", "530 Anonymous")):
```
As I understand the change in Python, the previous wrapper would also replace the original args with just the error class, so the above fix would not be quite as general as for Python <= 3.10.7; to cover all `error_perm` (= class 500) exceptions, we might simply check for "5" in the second case – within the context of `URLError` this might still be specific enough?

### Steps to Reproduce
```python
astropy.test(package='utils', args='-vk test_ftp_tls_auto', remote_data=True)
```

### System Details
macOS-12.6.1-arm64-arm-64bit
Python 3.10.8 (main, Oct 12 2022, 21:27:37) [Clang 14.0.0 (clang-1400.0.29.201)]
Python 3.11.0 (main, Oct 24 2022, 23:26:06) [Clang 14.0.0 (clang-1400.0.29.201)]
Numpy 1.23.5
pyerfa 2.0.0.1
astropy 5.2rc1
Scipy 1.9.3
Matplotlib 3.5.1

**Comment by pllim** [comment]
Wut...? How did the CI not catch this?

**Comment by dhomeier** [comment]
> @pytest.mark.skipif("CI", reason="Flaky on CI")

😕

**Comment by pllim** [comment]
@dhomeier , do you plan to also submit a PR?

**Comment by dhomeier** [comment]
Working on it.
