### ISSUE TITLE
leap second 2016-12-31T23:59:60 not taken into account in astropy.Time.datetime

### ISSUE THREAD

**Issue by CorentinLouis** [astropy/astropy#14112]
### Description

Dear Astropy developers,

We would like to report a bug when trying to work with a time table that includes the leap second 2016-12-31T23:59:60. 
It seems that Astropy is able to handle the fact that datetime does not support leap seconds for all leap seconds that occur before 2016. But Astropy is not able to handle the leap second 2016-12-31T23:59:60 (see code block below).

Would it be possible to solve this problem? Or is there already a way to solve it?

Kind regards,

```python
In [1]: time_leap_2012 = ['2012-05-30T23:59:60']
In [2]: astrotime_2012_leap = Time(time_leap_2012,format='isot',scale='utc')
In [3]: astrotime_2012_leap.datetime
Out[3]: array([datetime.datetime(2012, 5, 31, 0, 0)], dtype=object)

In [4]: time_leap_2016=["2016-12-31T23:59:60"]
In [5]: astrotime_2016_leap = Time(time_leap_2016,format='isot',scale='utc')
In [6]: astrotime_2016_leap.datetime
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-8b431a330371> in <module>
----> 1 astrotime_2016_leap.datetime

~/opt/anaconda3/lib/python3.8/site-packages/astropy/time/core.py in __getattr__(self, attr)
   1391 
   1392         elif attr in self.FORMATS:
-> 1393             return self.to_value(attr, subfmt=None)
   1394 
   1395         elif attr in TIME_SCALES:  # allowed ones done above (self.SCALES)

~/opt/anaconda3/lib/python3.8/site-packages/astropy/time/core.py in to_value(self, format, subfmt)
    838                 kwargs['out_subfmt'] = subfmt
    839             try:
--> 840                 value = tm._time.to_value(parent=tm, **kwargs)
    841             except TypeError as exc:
    842                 # Try validating subfmt, e.g. for formats like 'jyear_str' that

~/opt/anaconda3/lib/python3.8/site-packages/astropy/time/formats.py in to_value(self, timezone, parent, out_subfmt)
   1009         for iy, im, id, ihr, imin, isec, ifracsec, out in iterator:
   1010             if isec >= 60:
-> 1011                 raise ValueError('Time {} is within a leap second but datetime '
   1012                                  'does not support leap seconds'
   1013                                  .format((iy, im, id, ihr, imin, isec, ifracsec)))

ValueError: Time (array(2016, dtype=int32), array(12, dtype=int32), array(31, dtype=int32), array(23, dtype=int32), array(59, dtype=int32), array(60, dtype=int32), array(0, dtype=int32)) is within a leap second but datetime does not support leap seconds
```

Python 3.8.5
astropy 5.1

**Comment by pllim** [comment]
Thanks for reporting this. I can confirm this still happens in astropy 5.3.dev.

**Comment by eteq** [comment]
Weird.  Hard to say from a quick glance if this is an issue that `Time` is struggling to handle it vs `iers`/`erfa` not recognizing this leap second.  Will need to investigate more.

**Comment by CorentinLouis** [comment]
Thanks for the quick answer. In the mean time, I have found this webpage:

https://docs.astropy.org/en/stable/api/astropy.time.update_leap_seconds.html

    update_leap_seconds
 
    astropy.time.update_leap_seconds(files=None)[[source]](https://docs.astropy.org/en/stable/_modules/astropy/time/core.html#update_leap_seconds)
 
     If the current ERFA leap second table is out of date, try to update it.
 
     Uses [astropy.utils.iers.LeapSeconds.auto_open](https://docs.astropy.org/en/stable/api/astropy.utils.iers.LeapSeconds.html#astropy.utils.iers.LeapSeconds.auto_open) to try to find an up-to-date table. See that routine for the definition of “out of date”.
 
     In order to make it safe to call this any time, all exceptions are turned into warnings,
 

to check if it could come from the `erfa` not recognizing this leap second as suggested by @eteq:
```python
In [1]: from astropy.utils.iers import LeapSeconds

In [2]: LeapSeconds.auto_open()
Out[2]: 
<LeapSeconds length=28>
  mjd    day  month  year tai_utc
float64 int64 int64 int64  int64 
------- ----- ----- ----- -------
41317.0     1     1  1972      10
41499.0     1     7  1972      11
41683.0     1     1  1973      12
42048.0     1     1  1974      13
42413.0     1     1  1975      14
42778.0     1     1  1976      15
43144.0     1     1  1977      16
43509.0     1     1  1978      17
43874.0     1     1  1979      18
44239.0     1     1  1980      19
44786.0     1     7  1981      20
45151.0     1     7  1982      21
45516.0     1     7  1983      22
46247.0     1     7  1985      23
47161.0     1     1  1988      24
47892.0     1     1  1990      25
48257.0     1     1  1991      26
48804.0     1     7  1992      27
49169.0     1     7  1993      28
49534.0     1     7  1994      29
50083.0     1     1  1996      30
50630.0     1     7  1997      31
51179.0     1     1  1999      32
53736.0     1     1  2006      33
54832.0     1     1  2009      34
56109.0     1     7  2012      35
57204.0     1     7  2015      36
57754.0     1     1  2017      37
```
it thus seems that `erfa` recognizes this leap second.

**Comment by pllim** [comment]
So in that table above, 2012 has an entry, but not 2016, instead there are 2015 and 2017. Is that supposed to happen?

**Comment by CorentinLouis** [comment]
> So in that table above, 2012 has an entry, but not 2016, instead there are 2015 and 2017. Is that supposed to happen?

In this table is indicated the day that follow the leap second.
- In 2012, the leap second is `2012-05-30T23:59:60`, so `2017-07-01` is indicated.
- In 2016, the leap second is `2016-12-31T23:59:60`, so `2017-01-01` is indicated.

**Comment by CorentinLouis** [comment]
> I think your 2012 leap second is wrongly defined? It should have been this? But with this change, I get the same error.
> 
> ```python
> time_leap_2012 = ['2012-06-30T23:59:60']
> ```

I was writing the exact same thing. Yes, my 2012 leap second was wrongly defined.

This means that Astropy does not deal with the second leap at all.

**Comment by mhvk** [comment]
Since this is not a bug in astropy, I removed the "bug" label, and instead added "close?" since the problem is with `datetime`, which we cannot fix.

**Comment by pllim** [comment]
I found an example here, FWIW: https://docs.astropy.org/en/stable/time/index.html#id25

**Comment by maxnoe** [comment]
There is an open issue in cpython for handling leap seconds in datetime: https://github.com/python/cpython/issues/67762

**Comment by maxnoe** [comment]
> can't use `astropy.time.Time.datetime` safely

If `datetime.datetime` or `np.datetime64` would support everything we need, there wouldn't be a need for `astropy.time` ... 


The functions are handy for when it's possible to convert, but it's definitely not a bug in astropy.

**Comment by mhvk** [comment]
Indeed, our choice was not to support `datetime` at all, or error on leap seconds when using it. It is annoying but really this needs the python fix.

**Comment by maxnoe** [comment]
Actually, I think there is a bug here!

This:
```
In [1]: time_leap_2012 = ['2012-05-30T23:59:60']
In [2]: astrotime_2012_leap = Time(time_leap_2012,format='isot',scale='utc')
```
Should be an error, as it is an invalid date, but it get's converted to `2012-05-31T00:00:00`

It's only an erfa warning:

```

In [1]: from astropy.time import Time

In [2]: Time("2012-05-30T23:59:60")
/home/maxnoe/.local/anaconda/envs/gammapy-dev/lib/python3.8/site-packages/erfa/core.py:154: ErfaWarning: ERFA function "dtf2d" yielded 1 of "time is after end of day (Note 5)"
  warnings.warn('ERFA function "{}" yielded {}'.format(func_name, wmsg),
Out[2]: <Time object: scale='utc' format='isot' value=2012-05-31T00:00:00.000>
```

**Comment by mhvk** [comment]
I would put accepting seconds beyond 60 generally under "generous on input, strict on output" -- the interpretation certainly is unique, no need to guess. I suspect it was a conscious choice, but I'll let @taldcroft comment on that. In any case, not directly related to this issue except in that it made it less obvious there was a mistake in the second leap second example.

**Comment by taldcroft** [comment]
> I would put accepting seconds beyond 60 generally under "generous on input, strict on output" -- the interpretation certainly is unique, no need to guess. I suspect it was a conscious choice

I don't recall making a conscious choice about a case like this, though it was a long time ago. But what *was* deliberate was delegating to SOFA/ERFA for the core time machinery including validation. In this case the IAU SOFA code decided that a value seconds beyond 60 is a warning and not an error. With only one exception, `pyerfa` sticks to the original SOFA dispositions. In this case:
```
**  Returned (function value):
**               int     status: +3 = both of next two
**                               +2 = time is after end of day (Note 5)
**                               +1 = dubious year (Note 6)
**                                0 = OK
**                               -1 = bad year
**                               -2 = bad month
**                               -3 = bad day
**                               -4 = bad hour
**                               -5 = bad minute
**                               -6 = bad second (<0)
```
If we want to turn status = +2 into an error that is possible in pyerfa, but my inclination is to generally stick with what SOFA decided and let users turn that warning into an exception if they want.
