### ISSUE TITLE
Documenting tests

### ISSUE THREAD

**Issue by embray** [astropy/astropy#1414]
Tests should be better documented in general.  What I mean by that is that individual test functions should, like any other function, have a docstring explaining, well, what that test is supposed to test.

Sometimes the answer to that question is obvious just from looking at the test.  Other times it is certainly not.  Perhaps in particular, any test that was written to demonstrate a bug (i.e. a regression test) ought to have, if nothing else, a link to the issue in which that bug was reported in its docstring.

If you look at the `astropy.io.fits` tests for example, many of them contain docstrings like "Regression test for ..." with a URL to a bug report (many of the `astropy.io.fits` tests are also poorly documented so I'm aware that this can be a pain).

In any case, we should update the documentation for writing tests (and submitting bug fixes with tests) to recommend documenting the test as well.  Time permitting we should also try to back fill descriptions for existing tests, though this could be very time consuming and is hardly critical.

**Comment by bsipocz** [comment]
I agree with the https://github.com/astropy/astropy/issues/1414#issuecomment-48329625 above that keeping a generic issue like this around isn't that much helpful.
Reopen if you feel otherwise.
