### ISSUE TITLE
TST: Include tox pre-prelease in devinfra cron job

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14153]
As suggested by @WilliamJamieson .

https://github.com/astropy/astropy/blob/422eadaa182428ca9842bb3b1f17da9317976253/.github/workflows/ci_cron_weekly.yml#L54

Blocked by:

* https://github.com/astropy/astropy/issues/14143

**Comment by WilliamJamieson** [comment]
I vote we wait until #14139 gets merged before we do this.

**Comment by pllim** [comment]
@WilliamJamieson , I don't quite remember what this is about anymore. Do you? If not, maybe we should just close it?

**Comment by WilliamJamieson** [comment]
Agreed.
