### ISSUE TITLE
CASA instructions in the docs no longer work for CASA 6

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#14151]
Submitted via feedback@astropy.org

As a member of the CASA team, a user pointed out to me that your instructions on how to use astropy inside CASA no longer work:
https://docs.astropy.org/en/stable/install.html

The likely reason is that, as of CASA 6, the CASA tarfile distribution is now built from pip wheels. So rather than trying to run astropy inside CASA, users may want to instead run the modular pip-wheel version of CASA inside the Python environment where also astropy is running (although note that I am not an active astropy user myself).

In case you are interested, our CASA Docs documentation provides instructions on how to install the modular CASA version:
https://casadocs.readthedocs.io/en/stable/notebooks/introduction.html#id1
while an example of how CASA and astropy can operate in a personal environment can be found here:
https://casadocs.readthedocs.io/en/stable/examples/community/casa6_demo.html#View-Images-with-Astropy

**Comment by pllim** [comment]
cc @keflavich

**Comment by keflavich** [comment]
Right, we should just remove the instructions specific to CASA, since those were workarounds for the old version.  Now CASA is just part of a normal python distribution.

**Comment by pllim** [comment]
See #14154
