### ISSUE TITLE
Join tables triggers ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by HealthyPear** [astropy/astropy#14167]
### Description

I have 2 big QTables (7895 rows the first and 390103 the second) that I am trying to join from a series of events.

It appears that I trigger a ValueError only when using a particular file at a particular event, so the issue might be like triggered by something within my data.

I am stuck because I do not know how to debug it more that what I already did which is
- making sure it was happening there and not in many other similar cases
- comparing pairs of events from other files and checking e.g. dtypes, units, etc...

The single tables that fail joining look OK to me.

There are column names in common and the issue gets triggered with any join type.

The traceback is similar to the following,

```python
ValueError                                Traceback (most recent call last)
File /var/folders/2z/142033n17rbfy969s6h4hymw0000gn/T/ipykernel_2009/3533429509.py:1
----> 1 join(wh, phe, join_type="left")

File ~/Applications/mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/table/operations.py:392, in join(left, right, keys, join_type, keys_left, keys_right, uniq_col_name, table_names, metadata_conflicts, join_funcs)
    389     right = Table(right)
    391 col_name_map = OrderedDict()
--> 392 out = _join(left, right, keys, join_type,
    393             uniq_col_name, table_names, col_name_map, metadata_conflicts,
    394             join_funcs,
    395             keys_left=keys_left, keys_right=keys_right)
    397 # Merge the column and table meta data. Table subclasses might override
    398 # these methods for custom merge behavior.
    399 _merge_table_meta(out, [left, right], metadata_conflicts=metadata_conflicts)

File ~/Applications/mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/table/operations.py:1191, in _join(left, right, keys, join_type, uniq_col_name, table_names, col_name_map, metadata_conflicts, join_funcs, keys_left, keys_right)
   1186 # Main inner loop in Cython to compute the cartesian product
   1187 # indices for the given join type
   1188 int_join_type = {'inner': 0, 'outer': 1, 'left': 2, 'right': 3,
   1189                  'cartesian': 1}[join_type]
   1190 masked, n_out, left_out, left_mask, right_out, right_mask = \
-> 1191     _np_utils.join_inner(idxs, idx_sort, len_left, int_join_type)
   1193 out = _get_out_class([left, right])()
   1195 for out_name, dtype, shape in out_descrs:

File astropy/table/_np_utils.pyx:77, in astropy.table._np_utils.join_inner()

ValueError: negative dimensions are not allowed
```

Did any of you ever encounter this error when joining tables?

### Steps to Reproduce

the line which triggers the issue is a simple join like

```python
join(table_A, table_B)
```

with any join type.

### System Details

macOS-11.7.1-x86_64-i386-64bit
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00) 
[Clang 13.0.1 ]
Numpy 1.23.4
pyerfa 2.0.0.1
astropy 5.1.1
Scipy 1.9.3
Matplotlib 3.6.2

**Comment by HealthyPear** [comment]
Another piece of the puzzle:

what I am actually doing is that I have 3 tables A,B,C
- table A contains high-level information about the events, with 2 columns A1 and A2
- for each event in A, B table gets A1 rows
- for each event in A, C table gets A2 rows

now I discovered that the this crashing behaviour happens because there is a "spike" of information.

The screenshot below shows an excerpt of table A with just the event ID, and the A1 and A2 columns.

The event which triggers this behaviour is event number 2735,

<img width="411" alt="image" src="https://user-images.githubusercontent.com/17836610/206878644-c9bd94e6-3577-4c33-b123-43dbbec4252c.png">

Also, all quantities are float64 and I am running on a 64bit machine

**Comment by HealthyPear** [comment]
I have the feeling I might have the same issue described here
https://stackoverflow.com/questions/39130690/value-error-negative-dimensions-are-not-allowed-when-merging

Am I right?....

**Comment by taldcroft** [comment]
@HealthyPear - sorry for the delay. Is there any way that you can provide a reproducible example of this issue? I don't see anything obvious in what you've said and can't go much further on this without a way to reproduce the problem you see locally.

**Comment by neutrinoceros** [comment]
I found a way to reproduce this on my machine
```python
from astropy.table import Table, join
import numpy as np

fac = 1024
nrows = 10192 *fac
ncols = 10192//fac
t0 = Table({f"col{i}": np.random.random_sample(nrows).astype("float64") for i in range(ncols)})
t1 = Table({f"col{i}": np.random.random_sample(nrows).astype("float64") for i in range(ncols)})
tj = join(t0, t1, join_type="cartesian")
```
Note that in my example, the expected resulting table would be *far* larger than what any current day non-HPC computer could hold in RAM, but it doesn't show from the error one gets
```python-traceback
Traceback (most recent call last):
  File "/Users/clm/dev/astropy-project/coordinated/astropy/bugs/14167/t.py", line 10, in <module>
    tj = join(t0, t1, join_type="cartesian")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/table/operations.py", line 413, in join
    out = _join(
          ^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/table/operations.py", line 1245, in _join
    masked, n_out, left_out, left_mask, right_out, right_mask = _np_utils.join_inner(
                                                                ^^^^^^^^^^^^^^^^^^^^^
  File "astropy/table/_np_utils.pyx", line 80, in astropy.table._np_utils.join_inner
ValueError: negative dimensions are not allowed
```

I was able to verify that the real issue was that an internal `int` (implicit int32) was overflowing.
Namely, here
https://github.com/astropy/astropy/blob/207a2e465b012c4422c429d52c337e83c3ddfa02/astropy/table/_np_utils.pyx#L78

So I think the solution is as simple as using `cnp.int64_t` indices everywhere. This makes it so that, in all real life applications, the amount of memory available is the real bottleneck, and with a patch as simple as

```
diff --git a/astropy/table/_np_utils.pyx b/astropy/table/_np_utils.pyx
index b209d591c1..d94745aa67 100644
--- a/astropy/table/_np_utils.pyx
+++ b/astropy/table/_np_utils.pyx
@@ -16,7 +16,7 @@ cimport numpy as np
 np.import_array()
 
 DTYPE = int
-ctypedef np.intp_t DTYPE_t
+ctypedef np.int64_t DTYPE_t
 
 @cython.wraparound(False)
 @cython.boundscheck(False)
@@ -28,8 +28,8 @@ def join_inner(np.ndarray[DTYPE_t, ndim=1] idxs,
     Do the inner-loop cartesian product for np_utils.join() processing.
     (The "inner" is about the inner loop, not inner join).
     """
-    cdef int n_out = 0
-    cdef int max_key_idxs = 0
+    cdef DTYPE_t n_out = 0
+    cdef DTYPE_t max_key_idxs = 0
     cdef DTYPE_t ii, key_idxs, n_left, n_right, idx0, idx1, idx, i
     cdef DTYPE_t i_left, i_right, i_out
     cdef int masked
```

the error you get is now much more clearly about memory !
```
Traceback (most recent call last):
  File "/Users/clm/dev/astropy-project/coordinated/astropy/bugs/14167/t.py", line 10, in <module>
    tj = join(t0, t1, join_type="cartesian")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/table/operations.py", line 413, in join
    out = _join(
          ^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/table/operations.py", line 1246, in _join
    masked, n_out, left_out, left_mask, right_out, right_mask = _np_utils.join_inner(
                                                                ^^^^^^^^^^^^^^^^^^^^^
  File "astropy/table/_np_utils.pyx", line 83, in astropy.table._np_utils.join_inner
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 793. TiB for an array with shape (108922786545664,) and data type int64
```

I'll issue a PR with the proposed patch.
