### ISSUE TITLE
Set numpy docs link for sphinx gallery back to stable

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#14162]
In #14140, where we unpinned sphinx, the numpy link in the gallery was set to devdocs, since stable gave errors. It should be set back. Perhaps with the release of numpy 1.24, the docs will be OK again.  See https://github.com/astropy/astropy/blob/d31499bb3d4d4cf02981c9b7fdd35bc37c62ad54/docs/conf.py#L340-L342

**Comment by pllim** [comment]
We have to backport this (will link to PRs later), so I removed the milestone. I don't think it is release critical.

**Comment by pllim** [comment]
Done in https://github.com/astropy/astropy/pull/14288
