### ISSUE TITLE
Documentation: Alternative way to obtain Astropy from Guix

### ISSUE THREAD

**Issue by Hellseher** [astropy/astropy#14166]
Hi,

I've got a feature request for the next documentation update to include Guix as one the way to install Astropy and related packages. Having it in Guix may help to facilitate reproducible research in astronomy environment as it was successfully utilized in bio-informatics.

- paper :: https://guix.gnu.org/blog/2018/paper-on-reproducible-bioinformatics-pipelines-with-guix/

### Description
Astropy and the whole chain of dependencies were fully packed in Guix  and it might be mentioned in documentation as an alternative reproducible way to install it:
``` shell
# Latest packed version
guix install python-astropy

# In time machine to have 1:1 reproducible environment
guix time-machine --commit=64e130fc6f26ba60d1e3e2c6ce49a57fb181ce0d -- install python-astropy
```
Related packages: https://packages.guix.gnu.org/search/?query=python-astropy

Thanks,
Oleg

**Comment by pllim** [comment]
Hello and thanks for your interest!

I have mixed feelings about this request. On one side, I like to make it easier for users to discover different ways they can get `astropy` but on the other hand, if the distro does not catch up and things start to break, then we will also get open issues that we do not have the capacity or expertise to handle.

We do mention `pip` and `conda` but those are pretty standard Python install commands. We do not tell people how to `apt` or `homebrew` etc. In fact, we recently just removed mention of CASA (#14154). I wonder if such documentation is better served from your side.

However, this is purely my personal opinion and I shall bring your request to the next dev telecon. Stay tuned!

**Comment by hamogu** [comment]
Thank you for reaching out to us.

We discussed this at the [dev telecon](https://docs.google.com/document/d/15JSFh3OMF9Iz6ov3q_xxGO_BL8hRnuse4IMUrqEIvcg/edit#heading=h.y1b7rstf5zlm) and agree with @pllim comments above: We don't have the resources to maintain (which includes testing!) a list of all ways to install astropy. In particular for GUIX, we don't have access to a system to run on and we noted that astropy version 5.2 is not available on GUIX yet, so it might be better for uses to use Python tools like pip anyway in that case.
