### ISSUE TITLE
Confusing result from converting EarthLocation to ITRS relative to itself

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#14173]
### Description

Maybe I misunderstood how `EarthLocation.get_itrs()` and the reference location of ITRS work, but I expected that if I convert an `EarthLocation` to ITRS with the location itself as the reference location for ITRS, I get local coordinates of (0, 0, 0), since I am exactly at the reference point.

### Expected behavior

Transforming an EarthLocation with itself as the reference point results in coordinates 0,0,0

### Actual behavior

Result is actually hundreds of meters away.

### Steps to Reproduce

```
In [9]: from astropy.time import Time

In [10]: from astropy.coordinates import EarthLocation, AltAz, ITRS

In [11]: obstime = Time.now()

In [12]: location = EarthLocation.of_site('Roque de los Muchachos')

In [13]: location.get_itrs(obstime).transform_to(AltAz(obstime=obstime, location=location)).cartesian
Out[13]: 
<CartesianRepresentation (x, y, z) in m
    (169.75511831, 483.89050301, 0.49045424)>>

In [14]: location.get_itrs(obstime).transform_to(ITRS(location=location, obstime=obstime))
Out[14]: 
<ITRS Coordinate (obstime=2022-12-13 14:00:26.910787, location=(5327448.9957829, -1718665.73869569, 3051566.90295403) m): (x, y, z) in m
    (236.17919146, 583.96103847, -83.51893567)>

In [15]: location.get_itrs().transform_to(ITRS(location=location))
Out[15]: 
<ITRS Coordinate (obstime=J2000.000, location=(5327448.9957829, -1718665.73869569, 3051566.90295403) m): (x, y, z) in m
    (128.20165889, 603.20647436, 115.88045621)>
```

What's really confusing me is that giving the same time vs. no time makes a difference.

**Comment by mhvk** [comment]
The underlying problem seems to be the self-transformation from `ITRS` to `ITRS`, which currently goes through `CIRS` (see end of `intermediate_rotation_transforms.py`)
E.g.,
```
import astropy.units as u
from astropy.coordinates import ITRS
itrs = ITRS(6000*u.km, 0*u.km, 0*u.km)
itrs.transform_to(ITRS(location=itrs))
# <ITRS Coordinate (obstime=J2000.000, location=(6000., 0., 0.) km): (x, y, z) in km
#     (-3.12784162e-05, 0.604518, 0.04362523)>
```
I think the dependence on `obstime` is just different round-trip errors. (Note that for differrent `obstime`, one gets very different numbers, because of course the earth has moved.)

Looking in a bit more detail, the biggest error seems to be in self-transform from geocentric CIRS to CIRS with a given location:
```
itrs.transform_to(CIRS())
# <CIRS Coordinate (obstime=J2000.000, location=(0., 0., 0.) km): (ra, dec, distance) in (deg, deg, km)
#     (280.19393585, 1.20600834e-05, 6000.)>
itrs.transform_to(CIRS()).transform_to(CIRS(location=itrs))
# <CIRS Coordinate (obstime=J2000.000, location=(6000., 0., 0.) km): (ra, dec, distance) in (deg, deg, km)
#     (10.19690127, 4.12750731, 0.60609007)>
```
This goes via `ICRS`, so suddenly values are going to be in AU, and rounding errors of order 100s of m are not unexpected.

Now this all just explains why the current scheme gives these rounding errors, not whether we are doing the right thing. Let me ping @StuartLittlefair and @mkbrewer to see whether they can think of a general way to avoid this.

**Comment by eerovaher** [comment]
Isn't this what the documentation at https://docs.astropy.org/en/stable/coordinates/common_errors.html#altaz-calculations-for-earth-based-objects is about?

**Comment by mhvk** [comment]
It may not be quite so easy, since if `obstime` is different, one should take motion of the Earth into account.
```
In [11]: itrs.transform_to(ITRS(location=itrs))
Out[11]: 
<ITRS Coordinate (obstime=J2000.000, location=(6000., 0., 0.) km): (x, y, z) in km
    (-3.12784162e-05, 0.604518, 0.04362523)>

In [12]: itrs.transform_to(ITRS(location=itrs, obstime='J2000.001'))
Out[12]: 
<ITRS Coordinate (obstime=J2000.001, location=(6000., 0., 0.) km): (x, y, z) in km
    (695115.30598932, -645840.40662179, 69982.17477072)>
```

But I think @eerovaher's link provides the answer; it is just that for `ITRS` it is even less intuitive that it is for `AltAz`. Or am I missing something again? (My intuition is definitely bad here....)

**Comment by StuartLittlefair** [comment]
No, I think you are correct, but it opens up the can of worms that there can be an assumption about what coordinates **represent**.

Users probably implicitly imagine that an `ITRS` coordinate represents a thing on or near the Earth's surface. If so, they'll be surprised by the result you show.

In astropy I think we treat all coordinates as referring to some fixed point in space, so that the representation of that point in the ITRS frame changes with obstime, because the Earth is moving.

We could still tweak the ITRS self transform so that it does a cartesian calculation in the special case that the obstime does not change.

**Comment by maxnoe** [comment]
> Users probably implicitly imagine that an ITRS coordinate represents a thing on or near the Earth's surface. If so, they'll be surprised by the result you show.

That's how ITRS is defined....

**Comment by StuartLittlefair** [comment]
No, you are confusing the ITRS frame itself and an astropy SkyCoord or `ITRS` object. 

In astropy we don't make assumptions about what an object **is** based upon the frame it's coordinates are represented in. For example, we don't assume an object in galactic coordinates co-rotates with the galaxy and we don't assume a coordinate in the ITRS frame is fixed on the Earth's surface.

**Comment by maxnoe** [comment]
> In astropy we don't make assumptions 

But you do make an assumption when doing the aberration correction, no? Just a different one.

**Comment by StuartLittlefair** [comment]
For sure, but we don’t change that assumption depending on the frame. Everything is treat as a fixed point in space

**Comment by mhvk** [comment]
> We could still tweak the ITRS self transform so that it does a cartesian calculation in the special case that the obstime does not change.

That might be a reasonable short-cut. 

Though it would not have avoided the confusion here -- and just to be clear, I was very confused too until @eerovaher pointed out this text we added (which I'm pretty sure I reviewed at the time; sigh...).

I wonder if it would help to explicitly mention the difference between `EarthLocation` (actually fixed on earth) and `ITRS` in their respective docstrings.

**Comment by mkbrewer** [comment]
What you  are doing here is transforming geocentric coordinates to topocentric coordinates. That will always include a change in aberration from the point of view of an observer at the center of the Earth to that of an observer on the Earth's surface. If you want this to behave as you expect, you need to set up a proper topocentric ITRS frame as described here: https://docs.astropy.org/en/stable/coordinates/satellites.html

**Comment by mhvk** [comment]
Thinking a bit more, perhaps the `get_itrs` docstring is a good place to mention the difference.

**Comment by mkbrewer** [comment]
Well, I think that this is fairly well documented in the ITRS frame docstring. I suppose there could also be a link there to the example code shown in  `Working with Earth Satellites Using Astropy Coordinates`.

**Comment by mkbrewer** [comment]
I'm actually a bit surprised that this issue was raised given that I explicitly warned about doing this in the ITRS frame docstring.

**Comment by mhvk** [comment]
Yes, the docs and ITRS docstring are good -- though good to remember that the docstring update that you made is not actually in a released version yet, so one doesn't naturally get to see it if one looks at the "stable" documentation or interactively at the docstring.

Still, the problem with ITRS is that the "obvious" way it behaves is actually incorrect: to me at least, the name "International Terrestrial Reference System" doesvery strongly suggest something referenced to the Earth and "thus" fixed to it. Enough that I got it wrong above even though I was involved in the updates!

Anyway, @maxnoe, do you have a suggestion of where a little note might have helped you? Would `get_itrs` indeed be a place where a line of extra information would help?

**Comment by mkbrewer** [comment]
Oh, I thought 5.2 came out yesterday. When I google astropy and look at the documentation, I now see my changes.

**Comment by maxnoe** [comment]
An itrs frame with location set does the aberattion correction apperantly in its `.earth_location` propery, which is even more confusing.

**Comment by maxnoe** [comment]
E.g. this produces an unexpected result:

```
    local_itrs = altaz.transform_to(ITRS(location=altaz.location))
    return local_itrs.earth_location
```

And this works as expected by me:
```
    local_itrs = altaz.transform_to(ITRS(location=altaz.location))
    itrs = ITRS(local_itrs.cartesian + altaz.location.get_itrs().cartesian)
    return itrs.earth_location
```
```

**Comment by mkbrewer** [comment]
I would expect the first result to be (0,0,0). Is that not what you get?

**Comment by mkbrewer** [comment]
Oh, never mind. If those altaz coordinate include a distance, then I  would expect the corresponding earth location to be that distance from the center of the Earth.

**Comment by mkbrewer** [comment]
The thing about topocentric ITRS coordinates is that they are relative to the location of the observer. This works for an `EarthLocation`, an airplane, a satellite, or even a location on the Moon. Really anything that can be said to be co-moving with the Earth. The only difference between an `EarthLocation` and the rest is that an `EarthLocation` has zero velocity wrt the surface of the Earth.

**Comment by mkbrewer** [comment]
Ultimately, however, an observed location in the ITRS is still referenced to the solar system barycenter. While you can transform a topocentric ITRS position to any other topocentric frame at the same location and time, if you change either of those, you will not get the result that you would expect for a position co-moving with the Earth. I was very hesitant to change that behavior. We discussed this in my original PR and decided that it would be best to leave things as they have always been in that regard.

**Comment by mkbrewer** [comment]
I do think that Max has a valid point regarding the `earth_location` attribute. This was an oversight on my part originally. I will submit a (hopefully quick) PR to fix this. Perhaps it could be backported to 5.2.

**Comment by pllim** [comment]
I think this was fixed in https://github.com/astropy/astropy/pull/14180 ?
