### ISSUE TITLE
Astropy units incompatibility with numpy 1.24

### ISSUE THREAD

**Issue by tomdonaldson** [astropy/astropy#14210]
### Description

numpy 1.24 was released on December 18 and seems to have an incompatibility with astropy.  In brief, it's due to new `dtype` and `casting` args [allowed for some numpy functions](https://numpy.org/doc/stable/release/1.24.0-notes.html#casting-and-dtype-keyword-arguments-for-numpy-stack).  Specifically, [astropy's concatenate()](https://github.com/astropy/astropy/blob/87963074a50b14626fbd825536f384a6e96835af/astropy/units/quantity_helper/function_helpers.py#L380) doesn't have the new args [needed by numpy](https://github.com/numpy/numpy/blob/2f64274d360b25d509636897d5d39157080a42cc/numpy/core/shape_base.py#L471).  I've only seen a problem with `concatenate()`, but we should confirm whether other functions are impacted.

### Expected behavior

No exception when plotting something using a transform.

### Actual behavior

Exception when plotting something using a transform:
```
TypeError: concatenate() got an unexpected keyword argument 'dtype'
```

### Steps to Reproduce

With apologies for the less-than-minimal reproducible example, this code (which uses pyvo to gather the data it needs) reproduces the problem on the last line of code which is drawing a red circle around an object on an image.  It utilizes an `fk5` transformation to correctly place the circle.  Without the transformation there is no exception.  

I've confirmed that modifying [astropy's concatenate()](https://github.com/astropy/astropy/blob/87963074a50b14626fbd825536f384a6e96835af/astropy/units/quantity_helper/function_helpers.py#L380) to ignore the extra args allows this code to work, but haven't looked deeply enough to know what we lose by ignoring them.

```python
# Suppress unimportant warnings.
import warnings
warnings.filterwarnings("ignore", module="astropy.io.votable.*")
warnings.filterwarnings("ignore", module="pyvo.utils.xml.*")
warnings.filterwarnings('ignore', '.*RADECSYS=*', append=True)

import matplotlib.pyplot as plt
import numpy as np

# For downloading files
from astropy.utils.data import download_file

from astropy.coordinates import SkyCoord
from astropy.io import fits
from astropy.nddata import Cutout2D
import astropy.visualization as vis
from astropy.wcs import WCS
from astroquery.ipac.ned import Ned

import pyvo as vo

ra = 3.95892
dec = -10.04511
pos = SkyCoord(ra, dec, unit = 'deg')

sdss_image_services = vo.regsearch(keywords=['sloan'], servicetype='image')

#  For now, we know the first match is the right one.
sdss_image_service = [s for s in sdss_image_services if 'SDSS SIAP' in s.short_name ][0]
print(f"{sdss_image_service.short_name=}")

sdss_image_table = sdss_image_service.search(pos=pos, size=0.0, format=None, intersect='covers')
print(f"{len(sdss_image_table['Title'])=}")

for sdss_rband_record in sdss_image_table:
    if 'Sloan Digital Sky Survey - Filter r' in sdss_rband_record.title:
        break
print(sdss_rband_record.title, sdss_rband_record.bandpass_id)

file_name = download_file(sdss_rband_record.getdataurl(), cache=True)
sdss_rband_image=fits.open(file_name)

fig = plt.figure()

ax = fig.add_subplot(1, 1, 1, projection=WCS(sdss_rband_image[0].header))

interval = vis.PercentileInterval(99.9)
vmin,vmax = interval.get_limits(sdss_rband_image[0].data)
norm = vis.ImageNormalize(vmin=vmin, vmax=vmax, stretch=vis.LogStretch(1000))

ax.imshow(sdss_rband_image[0].data, cmap = 'gray_r', norm = norm, origin = 'lower')
trans = ax.get_transform('fk5')
ax.scatter(ra, dec, transform=trans, s=500, edgecolor='red', facecolor='none')

```

### System Details

macOS-12.6.2-x86_64-i386-64bit
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:55:37) 
[Clang 14.0.6 ]
Numpy 1.24.0
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.9.3
Matplotlib 3.6.2

**Comment by tomdonaldson** [comment]
Oops, I think this already may be fixed...

**Comment by tomdonaldson** [comment]
Probably should close this, but I'll add that this came up because I encountered this situation by installing `astropy` using `conda` with the `astropy` channel.  This gave me version `astropy==5.1` which has the above problem now that `numpy==1.24` is released.  Using the default channel with `conda` has the same problem.  Only `conda-forge` seems to have `astropy==5.2`.

**Comment by pllim** [comment]
conda default channel always lags behind and that is beyond our control... but maybe @mwcraig has more info.

**Comment by mwcraig** [comment]
Nothing additional to report -- but should I add an upper bound on numpy for the 5.1 release?

**Comment by pllim** [comment]
> should I add an upper bound on numpy for the 5.1 release?

I guess it does not hurt if that is easy to do. 🙇‍♀️

**Comment by aarchiba** [comment]
> > should I add an upper bound on numpy for the 5.1 release?
> 
> I guess it does not hurt if that is easy to do. bowing_woman

I think that this should allow modern versions of pip to not install incompatible versions of astropy and numpy: https://pip.pypa.io/en/stable/topics/dependency-resolution/#backtracking

Specifying version constraints on dependencies is quite straightforward.
