### ISSUE TITLE
astropy.utils.masked.Masked no longer works with np.median / np.nanmedian with numpy 1.24.0+,  raising TypeError

### ISSUE THREAD

**Issue by orionlee** [astropy/astropy#14236]
### Description
After updating an environment to the latest packages (astropy 5.2, Numpy 1.24.1), `np.median()` / `np.nanmedian()` no longer works with `astropy.utils.masked.Masked`. An error `TypeError: iteration over a 0-d array` is raised (at least in WSL2).

`np.mean()` / `np.nanmean()` still works correctly, however.

The problem seems to be due to changes in numpy. With astorpy 5.2 or 5.1:
- numpy 1.24.0 or later : `TypeError`
- before numpy 1.24.0: okay

Hmm, the issue here might be a duplicate of #14189 (at least related). However, I don't see any mentioning of `TypeError` there, I'm filing it just in case is another numpy 1.24 compatibility issue.

### Workaround

downgrade numpy to 1.23.X or earlier.

### Steps to Reproduce

```python
# Put your Python code snippet here.
import numpy as np

from astropy.utils.masked import Masked
from astropy import units as u
ma = Masked([1., 2., 3., 4.], mask=[False, False, True, False])
np.median(ma)
```

The following error will result:
```python
----> 6 np.median(ma)

File <__array_function__ internals>:200, in median(*args, **kwargs)

File ~/.local/share/virtualenvs/pyaneti-LelG1XGJ/lib/python3.8/site-packages/astropy/utils/masked/core.py:864, in MaskedNDArray.__array_function__(self, function, types, args, kwargs)
    862 dispatched_function = DISPATCHED_FUNCTIONS[function]
    863 try:
--> 864     dispatched_result = dispatched_function(*args, **kwargs)
    865 except NotImplementedError:
    866     return self._not_implemented_or_raise(function, types)

File ~/.local/share/virtualenvs/pyaneti-LelG1XGJ/lib/python3.8/site-packages/astropy/utils/masked/function_helpers.py:592, in median(a, axis, out, **kwargs)
    590 if NUMPY_LT_1_25:
    591     keepdims = kwargs.pop("keepdims", False)
--> 592     r, k = np.lib.function_base._ureduce(
    593         a, func=_masked_median, axis=axis, out=out, **kwargs
    594     )
    595     return (r.reshape(k) if keepdims else r) if out is None else out
    597 else:

TypeError: iteration over a 0-d array
```

Similarly, if `MaskedQuantity` is supplied to `np.median()` instead, e.g., `np.median(ma *u.m)` in the above example, a `TypeError` is raised that seems to suggest the same root cause.

```python
TypeError: 'MaskedQuantity' object with a scalar value is not iterable
```

### System Details

OS: Windows WSL2 / Ubuntu

Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
Numpy 1.24.1
pyerfa 2.0.0.1
astropy 5.2
Scipy 1.9.3
Matplotlib 3.6.2

**Comment by orionlee** [comment]
Oop, I didn't read #14189 carefully enough. It is a duplicate.

**Comment by pllim** [comment]
I have asked @astrofrog if it is possible to do a v5.2.1 soon but given the holidays, please expect delays. Thanks for your patience!

**Comment by orionlee** [comment]
@pllim No worry, It's a nuisance but not a showstopper for now. 
Stepping back a bit, I'm under the impression astropy has been testing against pre-releases of numpy to proactively prevent things like this from happening. What went wrong?

**Comment by pllim** [comment]
I think this must have snuck into 1.24 final release pretty late in their RC cycle. I am pretty sure things were fine (at least not with this error) in RC1. And then I was away for several days between subsequent RC and final release.

Either that, or somehow our numpy version check was buggy for RC version checks.
