### ISSUE TITLE
Presence of SIP keywords leads to ignored PV keywords.

### ISSUE THREAD

**Issue by navii98** [astropy/astropy#14255]
### Description
I am working on updating the fits header for one of our telescopes. We wanted to represent the distortions in SIP convention and the projection to be 'CAR'.
While working on this, I noticed if SIP coefficients are present in the header and/or '-SIP' is added to CTYPEia keywords,
astropy treats the PV keywords (PV1_0, PV1_1 and PV1_2) as "redundant SCAMP distortions".

Earlier I could not figure out why the projection weren't going as I expected, and I suspected a bug in astropy wcs. After talking to Mark Calabretta about the difficulties I'm facing, that suspicion only grew stronger. The header was working as expected with WCSLIB but was giving unexpected behavior in astropy wcs.

The following would be one example header - 
```
header_dict = {
'SIMPLE'  : True, 
'BITPIX'  : -32, 
'NAXIS'   :  2,
'NAXIS1'  : 1024,
'NAXIS2'  : 1024,
'CRPIX1'  : 512.0,
'CRPIX2'  : 512.0,
'CDELT1'  : 0.01,
'CDELT2'  : 0.01,
'CRVAL1'  : 120.0,
'CRVAL2'  : 29.0,
'CTYPE1'  : 'RA---CAR-SIP',
'CTYPE2'  : 'DEC--CAR-SIP',
'PV1_1'   :120.0,
'PV1_2'   :29.0,
'PV1_0'   :1.0,
'A_ORDER' :2,
'A_2_0'   :5.0e-4,
'B_ORDER' :2,
'B_2_0'   :5.0e-4
}
from astropy.io import fits
header = fits.Header(header_dict)
```

### Expected behavior
When you parse the wcs information from this header, the image should be centered at ra=120 and dec=29 with lines of constant ra and dec looking like the following image generated using wcslib - 
![wcsgrid_with_PV](https://user-images.githubusercontent.com/97835976/210666592-62860f54-f97a-4114-81bb-b50712194337.png)

### Actual behavior
If I parse the wcs information using astropy wcs, it throws the following warning -
`WARNING: FITSFixedWarning: Removed redundant SCAMP distortion parameters because SIP parameters are also present [astropy.wcs.wcs]`
And the resulting grid is different.
Code - 
```
import numpy as np
import matplotlib.pyplot as plt
from astropy.wcs import WCS
w = WCS(header)
ra = np.linspace(116, 126, 25)
dec = np.linspace(25, 34, 25)

for r in ra:
    x, y = w.all_world2pix(np.full_like(dec, r), dec, 0)
    plt.plot(x, y, 'C0')
for d in dec:
    x, y = w.all_world2pix(ra, np.full_like(ra, d), 0)
    plt.plot(x, y, 'C0')

plt.title('Lines of constant equatorial coordinates in pixel space')
plt.xlabel('x')
plt.ylabel('y')
```
Grid - 
![image](https://user-images.githubusercontent.com/97835976/210667514-4d2a033b-3571-4df5-9646-42e4cbb51026.png)

The astropy wcs grid/solution does not change whethere we keep or remove the PV keywords.
Furthermore, the astropy grid can be recreated in wcslib, by removing the PV keywords.
![wcsgrid_without_PV](https://user-images.githubusercontent.com/97835976/210667756-10336d93-1266-4ae6-ace1-27947746531c.png)

### Steps to Reproduce

1. Initialize the header
2. Parse the header using astropy.wcs.WCS
3. Plot the graticule
4. Remove the PV keywords and run again
5. You will find the same graticule indicating that PV keywords are completely ignored.
6.  Additionally, the graticules can be compared with the wcsgrid utility of wcslib.

### System Details

Linux-6.0.11-200.fc36.x86_64-x86_64-with-glibc2.35
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
Numpy 1.21.5
pyerfa 2.0.0
astropy 5.1
Scipy 1.7.3
Matplotlib 3.5.1

**Comment by navii98** [comment]
I have seen this issue discussed in https://github.com/astropy/astropy/issues/299 and https://github.com/astropy/astropy/issues/3559 with an fix in https://github.com/astropy/astropy/pull/1278 which was not perfect and causes the issue for me.

https://github.com/astropy/astropy/blob/966be9fedbf55c23ba685d9d8a5d49f06fa1223c/astropy/wcs/wcs.py#L708-L752

I'm using a CAR projection which needs the PV keywords.
By looking at the previous discussions and the implementation above some I propose some approaches to fix this.

1. Check if the project type is TAN or TPV. I'm not at all familiar with SCAMP distortions but I vaguely remember that they are used on TAN projection. Do correct me if I'm wrong.
2. As @stargaser suggested
> SCAMP always makes a fourth-order polynomial with no radial terms. I think that would be the best fingerprint.
Currently, https://github.com/astropy/astropy/pull/1278 only checks if any radial terms are present but we can also check if 3rd and 4th order terms are definitely present.
3. If wcslib supports SCAMP distortions now, then the filtering could be dropped altogether. I'm not sure whether it will cause any conflict between SIP and SCAMP distortions between wcslib when both distortions keyword are actually  present (not as projection parameters). 
@nden @mcara Mark Calabretta suggested you guys might be able to help with this.

**Comment by mcara** [comment]
I am not familiar with SCAMP but proposed suggestions seem reasonable, at least at the first glance. I will have to read more about SCAMP distortions re-read this issue, etc. I did not participate in the discussions from a decade ago and so I'll have to look at those too.

> I'm using a CAR projection which needs the PV keywords.

This is strange to me though. I modified your header and removed `SIP` (instead of `PV`). I then printed `Wcsprm`:

```python
header_dict = {
    'SIMPLE'  : True,
    'BITPIX'  : -32,
    'NAXIS'   :  2,
    'NAXIS1'  : 1024,
    'NAXIS2'  : 1024,
    'CRPIX1'  : 512.0,
    'CRPIX2'  : 512.0,
    'CDELT1'  : 0.01,
    'CDELT2'  : 0.01,
    'CRVAL1'  : 120.0,
    'CRVAL2'  : 29.0,
    'CTYPE1'  : 'RA---CAR',
    'CTYPE2'  : 'DEC--CAR',
    'PV1_1'   :120.0,
    'PV1_2'   :29.0,
    'PV1_0'   :1.0,
}
from astropy.wcs import WCS
w = WCS(header_dict)
print(w.wcs)
```

Here is an excerpt of what was reported:
```
   prj.*
       flag: 203
       code: "CAR"
         r0: 57.295780
         pv: (not used)
       phi0: 120.000000
     theta0: 29.000000
     bounds: 7

       name: "plate caree"
   category: 2 (cylindrical)
    pvrange: 0
```

So, to me it seems that `CAR` projection does not use `PV` and this contradicts (at first glance) the statement _"a CAR projection which needs the PV keywords"_.

**Comment by navii98** [comment]
`PV` keywords are not optional keywords in CAR projection to relate the native spherical coordinates with celestial coordinates (RA, Dec). By default they have values equal to zero, but in my case I need to define these parameters.

**Comment by mcara** [comment]
Also, from https://doi.org/10.1051/0004-6361:20021327 Table 13 one can see that `CAR` projection is not associated with any PV parameters.

**Comment by navii98** [comment]
> Table 13 one can see that CAR projection is not associated with any PV parameters.
Yes, that is true. 
But the description of Table 13 says that it only lists required parameters.

Also, PV1_1, and PV1_2 defines $\theta_0$ and $\phi_0$ which are accepted by almost all the projections to change the default value.

**Comment by mcara** [comment]
Yes, I should have read the footnote to Table 13 (and then Section 2.5).

**Comment by navii98** [comment]
Just commenting out https://github.com/astropy/astropy/blob/966be9fedbf55c23ba685d9d8a5d49f06fa1223c/astropy/wcs/wcs.py#L793
solves the issue for me.
But, I don't know if that would be desirable as we might be back to square one with the old PTF images.

Once the appropriate approach for fixing this is decided, I can try to make a small PR.

**Comment by mcara** [comment]
Looking at the sample listing for TPV - https://fits.gsfc.nasa.gov/registry/tpvwcs.html - I see that projection code is 'TPV' (in `CTYPE`). So I am not sure why we ignore `PV` if code is `SIP`. Maybe it was something that has dealing with pre-2012 FITS convention, with files created by SCAMP (pre-2012). How relevant is this nowadays? Maybe those who have legacy files should update `CTYPE`?

In any case, it looks like we should not be ignoring/deleting `PV` when `CTYPE` has `-SIP`.

It is not a good solution but it will allow you to use `astropy.wcs` with your file (until we figure out a permanent solution) if, after creating the WCS object (let's call it `w` as in my example above), you can run:

```python
w.wcs.set_pv([(1, 1, 120.0), (1, 0, 1.0), (1, 2, 29.0)])
w.wcs.set()
```

**Comment by mcara** [comment]
Your solution proposed above is OK too as a temporary workaround.

**Comment by mcara** [comment]
NOTE: A useful discussion can be found here: https://jira.lsstcorp.org/browse/DM-2883

**Comment by navii98** [comment]
> I see that projection code is 'TPV' (in CTYPE). So I am not sure why we ignore PV if code is SIP. Maybe it was something that was dealing with pre-2012 FITS convention, with files created by SCAMP (pre-2012).

Yes. Apparently pre-2012 SCAMP just kept the CTYPE as `TAN` .

> Maybe those who have legacy files should update CTYPE?

That would be my first thought as well instead of getting a pull request through. But, it's been in astropy for so long at this point.

> Your` solution proposed above is OK too as a temporary workaround.

By just commenting out, I don't have to make any change to my header update code or more accurately the header reading code and the subsequent pipelines for our telescope. By commenting the line, we could work on the files now and later an astropy update will clean up things in the background (I'm hoping).

From the discussion https://jira.lsstcorp.org/browse/DM-2883

> David Berry reports:
> 
> The FitsChan class in AST handles this as follows:
> 
> 1) If the CTYPE in a FITS header uses TPV, then the the PVi_j headers are interpreted according to the conventions of the distorted TAN paper above.
> 
> 2) For CTYPEs that use TAN, the interpretation of PVi_j values is controlled by the "PolyTan" attribute of the FitsChan. This can be set to an explicit value before reading the header to indicate the convention to use. If it is not set before reading the header, a heuristic is used to guess the most appropriate convention as follows:
> 
> If the FitsChan contains any PVi_m keywords for the latitude axis, or if it contains PVi_m keywords for the longitude axis with "m" greater than 4, then the distorted TAN convention is used. Otherwise, the standard convention is used.
> 

This seems like something that could be reasonable and it is a combination of my points 1 and 2 earlier.

If we think about removing `fix_scamp` altogether, then we would have to consider the following - 
1. How does the old PTF fits files (which contains both SIP and TPV keywords with TAN projection) behave with current wcslib.
2. How does other SCAMP fits files work with the current wcslib. I think if the projection is written as `TPV` then wcslib will handle it fine, I have no idea about CTYPE 'TAN'

**Comment by navii98** [comment]
The WCSLIB package ships with some test headers. One of the test header is about SIP and TPV.

>  FITS header keyrecords used for testing the handling of the "SIP" (Simple
>  Imaging Polynomial) and TPV distortions by WCSLIB.
> 
>  This header was adapted from a pair of FITS files from the Palomar Transient
>  Factory (IPAC) provided by David Shupe.  The same distortion was encoded in
>  two ways, the primary representation uses the SIP convention, and the 'P'
>  alternate the TPV projection.  Translations of both of these into other
>  distortion functions were then added as alternates.

In the examples given, the headers have a CTYPE for `RA--TAN-SIP` for SIP distortions and `RA---TPV` for SCAMP distortions. So, as long as the files from SCAMP are of `TPV` CTYPE they should just work.

The file - [SIPTPV.txt](https://github.com/astropy/astropy/files/10367722/SIPTPV.txt)
Also can be found at wcslib/C/test/SIPTPV.keyrec

**Comment by mcara** [comment]
Since I know nothing about SCAMP and do not know how these changes might affect those who do use SCAMP, I would like to hear opinions from those who might be affected by changes to SIP/SCAMP/TPV issue or from those who worked on the original issue: @lpsinger @stargaser @astrofrog

**Comment by lpsinger** [comment]
Man, this takes me back. This was probably my first Astropy contribution.

Is anyone on this PR going to be at AAS in Seattle this week?

**Comment by stargaser** [comment]
I'm attending the AAS in Seattle this week.

> 2. As @stargaser suggested
> 
> > SCAMP always makes a fourth-order polynomial with no radial terms. I think that would be the best fingerprint.
> 
> Currently, #1278 only checks if any radial terms are present but we can also check if 3rd and 4th order terms are definitely present. 3. If wcslib supports SCAMP distortions now, then the filtering could be dropped altogether. I'm not sure whether it will cause any conflict between SIP and SCAMP distortions between wcslib when both distortions keyword are actually present (not as projection parameters).

I think this would be the easiest solution that would satisfy the aims of #1278 to work with PTF files. I'm afraid it will not be possible to modify the headers of PTF files as the project has been over for several years now.

**Comment by navii98** [comment]
>  I'm afraid it will not be possible to modify the headers of PTF files as the project has been over for several years now.

I meant on a user level. Someone who is reading the PTF files can just remove the header keywords. 
Or maybe wcslib just handles it without issue now giving the intended wcs output? That has to be checked though.

**Comment by navii98** [comment]
Does anyone have any thoughts on this about how to proceed?

Also, @stargaser if you have access to the PTF files, could you just try to read them with the `fix_scamp` function removed? This might help us choose what route to take.

**Comment by mcara** [comment]
> > I'm afraid it will not be possible to modify the headers of PTF files as the project has been over for several years now.
> 
> I meant on a user level. Someone who is reading the PTF files can just remove the header keywords. Or maybe wcslib just handles it without issue now giving the intended wcs output? That has to be checked though.

I am of the same opinion. Those who use SCAMP that does not use correct CTYPE should fix the CTYPE manually. It is not that hard. It is impossible to design software that can deal with every possible interpretation of the same keyword.

True, in this case maybe we could have some sort of heuristic approach and "we can also check if 3rd and 4th order terms are definitely present" but really why do it at all? To me, the idea of FITS "standard" is not not have to guess anything, have heuristics, or software switches that tell the code (or "us") how to interpret things in a FITS file. IMO, the point of a standard and "archival format" is that things are unambiguous.

I think if there are no other comments or proposals you should go ahead and make a PR to remove `_fix_scamp()`.
