### ISSUE TITLE
TST: devdeps job failed with AttributeError 'numpy._ArrayFunctionDispatcher' object has no attribute '__code__'

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14287]
This is a known issue upstream. I think we just have to wait it out. Example log: https://github.com/astropy/astropy/actions/runs/3959559829/jobs/6782540850

```
E   AttributeError: 'numpy._ArrayFunctionDispatcher' object has no attribute '__code__'
```

Also see:

* https://github.com/numpy/numpy/pull/23020
* https://github.com/scipy/scipy/issues/17811
* https://github.com/numpy/numpy/issues/23033
* https://github.com/numpy/numpy/pull/23034

**Comment by dhomeier** [comment]
> ```python
> E           astropy.utils.exceptions.AstropyWarning: function 'trapz' is not known to astropy's Quantity. Will run it anyway, hoping it will treat ndarray subclasses correctly. Please raise an issue at https://github.com/astropy/astropy/issues.
> ```

The issue seems to be that with the proposed fix `np.trapz` identifies as `_trapz_orig`, which is not in `function_helpers.SUBCLASS_SAFE_FUNCTIONS`.

**Comment by seberg** [comment]
@dhomeier randomly came here, that is a good point, and maybe means that the other fix (not wrapping, just copying everything over) is better!

**Comment by dhomeier** [comment]
Fixed upstream (see https://github.com/astropy/astropy/actions/runs/3962609858/jobs/6802036555); thanks @seberg!

**Comment by pllim** [comment]
Fixed now.
