### ISSUE TITLE
Ecliptic coordinates missing

### ISSUE THREAD

**Issue by mperrin** [astropy/astropy#1430]
The astropy.coordinates package does not yet support transformation to or from ecliptic coordinates.  While the ecliptic is a bit of a slippery concept at very high precision, it's nonetheless frequently seen and often useful, so I think it makes sense for astropy to support it.  

I may be able to assist with an implementation myself (though am ludicrously overcommitted at the moment, so no promises) but in any case I wanted to ask raise this issue so others working on coordinates can comment.

**Comment by astrofrog** [comment]
This is not going to happen for 1.0 so removing the milestone.

@mtbannister - I'm not sure if you are still interested in helping with this, but if so, do get in touch with @eteq as he will be able to provide information on what needs doing.

**Comment by mtbannister** [comment]
Cheers @astrofrog. @eteq, @ijiraq has also mentioned he would be interested in helping with this issue.

**Comment by astrofrog** [comment]
@mtbannister @ijiraq - thanks!

**Comment by eteq** [comment]
@mtbannister, @ijiraq - if you want some ideas on how to most easily implement this with the frames added in astropy v1.0, I suggest you check out http://www.iausofa.org/2013_1202_C/sofa/sofa_pn.pdf, particularly the diagram on page 6.  (note that v1.0 uses only the "right side" of that transformation, through CIRS).  Depending on exactly how you're meaning to define ecliptic, a few options present themselves:

1. start from GCRS if you want a geocentric ecliptic system, using `astropy._erfa.epv00` to get the sun->earth or bary->earth vector
2. start from ICRS if you want a bary- or heliocentric ecliptic system, using `astropy._erfa.epv00` to get the sun->earth vector and/or the bary->sun vector
3. implement transforms from the "left side" of that diagram to use the "traditional" earth equinox-based approach.
