### ISSUE TITLE
Move skyfield pyinstaller hook

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#14312]
### Description

Found this

```python
# NOTE: this hook should be added to
# https://github.com/pyinstaller/pyinstaller-hooks-contrib
# once that repository is ready for pull requests
```

in https://github.com/astropy/astropy/blob/15cc8f20a4f94ab1910bc865f40ec69d02a7c56c/.pyinstaller/hooks/hook-skyfield.py

**Comment by pllim** [comment]
Isn't this the job for skyfield maintainers?

https://github.com/skyfielders/python-skyfield

**Comment by nstarman** [comment]
Probably, maybe we could open this issue over there.

**Comment by pllim** [comment]
@nstarman , do you want the honors of opening that issue upstream? 😸

**Comment by pllim** [comment]
I opened https://github.com/skyfielders/python-skyfield/issues/830

**Comment by nstarman** [comment]
Thanks! Sorry, didn't get a chance to look at this till now.
