### ISSUE TITLE
QTable units change after creation behaves inconsistently

### ISSUE THREAD

**Issue by HealthyPear** [astropy/astropy#14336]
### Description

Not sure if this is a feature request or a bug fix because in some cases is possible and in others not.
Also, apologies if somewhat it is possible, the docs do not have explicit examples of this.

Creating a QTable an adding/transforming units after its creation (like any Quantity) seems to be either not possible or unstable.

### Expected behavior

What I think would be cool is for QTables to have a `.to()` method that accepts a dictionary of units just like the `units` argument of the Table contructor to add previously inexistent units and transform to equivalent units (raising some unit error otherwise).

so we make a Qtable 

`t = QTable([a, b, c, d],names=('a', 'b', 'c', 'd')`

with e.g. a None, b in meters, c in seconds and d in eV

and we should be able to do this

`t.to({"a":"m", "c":"h"}`

with b and d unchanged,

but not this

`t.to({"a":"m", "c":"m"}`

which should raise a relevant exception.

### How to Reproduce

We can create a QTable like this, like the example on the docs shows,

```python
from astropy.table import QTable
import astropy.units as u
import numpy as np

a = np.array([1, 4, 5], dtype=np.int32)
b = [2.0, 5.0, 8.5]
c = ['x', 'y', 'z']
d = [10, 20, 30] * u.m / u.s

t = QTable([a, b, c, d],
           names=('a', 'b', 'c', 'd'),
           meta={'name': 'first table'})
```

and you can update the tables' units for the columns which do not have a unit

`t = QTable([a, b, c, d],names=('a', 'b', 'c', 'd'),units={"a":"m", "b":"s", "c":"m/s"})`

which by the way allows setting a unit to a column with string arguments, so this should definitely not be possible to do!

But OK a and b now have a unit.

Though if I try to update the unit of "d", even only transforming to an equivalent one like "km/s" I cannot do it,

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [19], line 1
----> 1 t = QTable([a, b, c, d],names=('a', 'b', 'c', 'd'),units={"a":"m", "b":"s", "c":"m/s", "d":"km/s"})

File ~/Applications/mambaforge/envs/astro/lib/python3.10/site-packages/astropy/table/table.py:852, in Table.__init__(self, data, masked, names, dtype, meta, copy, rows, copy_indices, units, descriptions, **kwargs)
    849 if self.masked not in (None, True, False):
    850     raise TypeError("masked property must be None, True or False")
--> 852 self._set_column_attribute('unit', units)
    853 self._set_column_attribute('description', descriptions)

File ~/Applications/mambaforge/envs/astro/lib/python3.10/site-packages/astropy/table/table.py:883, in Table._set_column_attribute(self, attr, values)
    880         value = None
    882 if value not in (np.ma.masked, None):
--> 883     setattr(self[name].info, attr, value)

File ~/Applications/mambaforge/envs/astro/lib/python3.10/site-packages/astropy/utils/data_info.py:231, in ParentAttribute.__set__(self, instance, value)
    227 if instance is None:
    228     # This is an unbound descriptor on the class
    229     raise ValueError('cannot set unbound descriptor')
--> 231 setattr(instance._parent, self.attr, value)

AttributeError: can't set attribute 'unit'
```

### Versions

macOS-11.7.3-x86_64-i386-64bit

Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:54) [Clang 13.0.1 ]

astropy 5.2.1

**Comment by mhvk** [comment]
Hmm, interesting. Part of the problem is that for regular `Column`, `unit` is just seen as another bit of `description` - it can just be anything. For `QTable`, this is no longer the case for numerical columns, since those are represented as `Quantity`. I'm not sure that is easy to change.

On the other hand, I think you are right that your example should work, since all it asks for is to use an equivalent unit -- really the intent of the user is clear here! I think in principle this could be done in `_set_column_attribute`.

One annoyance (and perhaps a reason to ping @taldcroft), is that the behaviour between `QTable` and `Table` would really diverge. Right now, if you run your line with `Table`, you get no error and the unit gets changed, but the values not:
```
Table([a, b, c, d],names=('a', 'b', 'c', 'd'),units={"a":"m", "b":"s", "c":"m/s", "d":"km/s"})
<Table length=3>
  a      b      c      d   
  m      s    m / s  km / s
int32 float64  str1 float64
----- ------- ----- -------
    1     2.0     x    10.0
    4     5.0     y    20.0
    5     8.5     z    30.0
```
Note that again this is not illogical given the idea that for a `Column` the unit is just some piece of information and here it just overrides the unit that came with the `Quantity`. But the result would probably still surprise most...

Still, for `QTable` it may be an idea to override `_set_column_attribute`...

**Comment by taldcroft** [comment]
@mhvk - how about this:
```
(astropy) ➜  astropy git:(main) ✗ git diff
diff --git a/astropy/table/table.py b/astropy/table/table.py
index 8a0932e948..bd9366fde6 100644
--- a/astropy/table/table.py
+++ b/astropy/table/table.py
@@ -919,7 +919,11 @@ class Table:
                     value = None
 
             if value not in (np.ma.masked, None):
-                setattr(self[name].info, attr, value)
+                col = self[name]
+                if attr == "unit" and isinstance(col, Quantity):
+                    self[name] = col.to(value)
+                else:
+                    setattr(self[name].info, attr, value)
```

```
In [4]: t = QTable([[1, 2] * u.km, [1, 2]], units={"col0": u.m, "col1": u.s})

In [5]: t
Out[5]: 
<QTable length=2>
  col0    col1 
   m       s   
float64 float64
------- -------
 1000.0     1.0
 2000.0     2.0

In [6]: t.info
Out[6]: 
<QTable length=2>
name  dtype  unit  class  
---- ------- ---- --------
col0 float64    m Quantity
col1 float64    s Quantity
```

**Comment by mhvk** [comment]
@taldcroft - that looks good to me, and I guess is the easiest and thus probably best solution (instead of overriding `QTable._set_column_attribute`). One question is whether it should be done in-place (`self[name] <<= value` or just `col <<= value`?).

What about the example with `Table` that I noted above? Column "d" is input as a `Quantity`; is it right in that case to still take the unit as just a label that gets attached to the `Column`? I guess in effect it is no different than doing `table["d"].unit = u.km/u.s` after creating the table, so probably OK.

**Comment by taldcroft** [comment]
@mhvk - about using `<<=`, YES! 

I was looking through the docs for how to update the unit of a `Quantity` in-place and couldn't find it. That operator and some of the words like "update a Quantity unit in-place" should be in the `Getting started` section.  Like the average impatient user I didn't see it on the top page and bailed.

**Comment by taldcroft** [comment]
About problems with `Table` and units, I think the current behavior is acceptable and that we should not spend any effort on improving unit handling in `Table` / `Column`. 

If anything I had been wondering about starting to deprecate existing support that makes a `Column` with unit behave as a quasi-Quantity. Basically I think that a `Column` should treat the unit as strictly a label. I think the 98% use case is reading FITS files with `Table` for applications where it really is a string label. But this is separate discussion, maybe one for the coordination meeting.

**Comment by mhvk** [comment]
`<<` is at https://docs.astropy.org/en/latest/units/quantity.html#creating-and-converting-quantities-without-copies - which is listed in the "Using astropy.units" section. I don't really know how to make that better - I think part of the problem is that the docs have gotten so large!

**Comment by taldcroft** [comment]
What about adding one short section to the end of the Getting started that highlights these operators:

The `<<` and `<<=` operators provide an elegant way to change the unit of a `Quantity`, either by returning a new `Quantity` or by doing an in-place update:
```
>>> q << u.cm / u.s
<Quantity 46.875 cm / s>
>>> q <<= u.cm / u.s
>>> q
<Quantity 46.875 cm / s>
```
(This assumes `q = 15.0 * u.m / (32.0 * u.s)` from above).

**Comment by mhvk** [comment]
Hmm, not sure; I already feel that intro section is on the long side. And it is meant for novices, for whom talking about copying may just muddy the waters. Though it does perhaps make sense to have something like that one is not allowed to set the unit after initialization, but can use `<<=` to convert in-place. And arguably this is a bigger deal than the formatting...

Still, I'd be more tempted to clean up the summary of the usage section, which seems rather long and have some entries that could be combined or reordered -- see this screenshot:
![image](https://user-images.githubusercontent.com/2789820/215850692-ec404070-c329-4cec-8b08-5d71bac8e4c0.png)

**Comment by HealthyPear** [comment]
So just to clarify my use case, since you already went deep into the implementation, is about converting an existing QTable to some units (not necessarly specifying all column names) before exporting the table to file.

So I have an in-memory QTable with column / units e.g. `a:m, b:None, c:eV` and before exporting the table to file I need to let the user to change e.g. _c_ from _eV_ to _GeV_, but as a developer I should do it in a way that doesn't need to know in advance  which columns should be converted.
Thus my proposal to use a dictionary which can be shorter than the number of columns - just like when initializing a Table with units (event though I start straight from a QTable)

**Comment by taldcroft** [comment]
Sorry for hijacking this issue with an OT discussion.. but here we are.

@mhvk - I agree that `<<=` is more important than formatting. It is interesting that you state "one is not allowed to set the unit after initialization", but `<<=` is exactly the way to do that, no? So this is important!

**Comment by taldcroft** [comment]
@HealthyPear - your original issue included two distinct topics (1) a feature request related to an existing QTable and (2) a bona fide bug in QTable creation. I have been focused on the bug, and then (3) a follow-on documentation improvement.

About (1), I'm not completely seeing what you want. How is it different from the following two-liner?
```
t = QTable([a, b, c, d],names=('a', 'b', 'c', 'd')
units = {"a":"m", "c":"h"}

def update_units(tbl, units):
    for name, unit in units.items():
        tbl[name] <<= unit

update_units(t, units)
```

**Comment by HealthyPear** [comment]
> @HealthyPear - your original issue included two distinct topics (1) a feature request related to an existing QTable and (2) a bona fide bug in QTable creation. I have been focused on the bug, and then (3) a follow-on documentation improvement.

Yeah I am famous for throwing such curve balls 😋 

> About (1), I'm not completely seeing what you want. How is it different from the following two-liner?
> 
> ```
(I added this)
a = np.array([1, 4, 5], dtype=np.int32)
b = [2.0, 5.0, 8.5]
c = ['x', 'y', 'z']
d = [10, 20, 30] * u.m / u.s
> t = QTable([a, b, c, d],names=('a', 'b', 'c', 'd')
> units = {"a":"m", "c":"h"}
> 
> def update_units(tbl, units):
>     for name, unit in units.items():
>         tbl[name] <<= unit
> 
> update_units(t, units)
> ```

This might be sufficient, but it doesn't actually work (for me at least)

`TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

I guess this would work also from d if e.g. I changed it to km/s, right?

**Comment by HealthyPear** [comment]
Plus if this works, rather than a 2-liner, I would make it a new method!

```python
class Table:

# bla bla

    def update_units(self, new_units):
 
        # bla bla
```

**Comment by mhvk** [comment]
@HealthyPear - I think it is fine if we have at least one way to change units, and the second way you tried, creating a new table with some explicit units given, seems a good and natural way one can do this within the current frameword. @taldcroft and I both agree that that second method should have worked, and I think we have a fix with the change @taldcroft suggested!

Given that the new-table initialization should work, I don't think we really want to add new methods to do the same thing.

**Comment by mhvk** [comment]
@taldcroft - on our OT discussion: I think we converged: we should replace the formatting stuff with `<<=` and move the formatting somewhere inside...

**Comment by taldcroft** [comment]
See https://github.com/astropy/astropy/pull/14357
