### ISSUE TITLE
TST: Coverage upload using OpenAstronomy template sometimes fails

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14347]
See:

* https://github.com/OpenAstronomy/github-actions-workflows/pull/105

Might be related:

* https://github.com/codecov/codecov-action/issues/598

However, CircleCI upload somehow succeeds, so now our codecov erroneously reports only 33% coverage.

https://github.com/astropy/astropy/blob/3510bc2ac78ddaea2459b07834efbd09cee767f8/.circleci/config.yml#L89-L90

If we cannot find a resolution with the OpenAstronomy template, we might have to consider not using it altogether (although no guarantee this would fix the problem if the problem is really upstream). 🤪

**Comment by pllim** [comment]
Oh, right... 😒 

https://www.businesswire.com/news/home/20221129006193/en/Sentry-Acquires-Codecov

**Comment by ConorMacBride** [comment]
Does this look familiar? https://github.com/sunpy/sunpy/actions/runs/4066887065/jobs/7003865938#step:10:39

**Comment by ConorMacBride** [comment]
From reading, it looks like the intermittent issue can be cause by GitHub rate limiting codecov when it tries to auto detect the build from the Actions API, however, installing the codecov app into GitHub should fix this. I think astropy has done this already, so I'm surprised this is an issue.

Anyway, assuming this GitHub API call is the only intermittent issue, a simple fix would be to set `CODECOV_TOKEN` anyway and skip the auto detection.

**Comment by pllim** [comment]
> Does this look familiar?

There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}

Yes, I see that sometimes. However, when that is not happening, it sometimes also complains about 400 coverage.xml not found. If I see the other error again, I'll let you know.

**Comment by pllim** [comment]
I think things have been much better since the token was added.
