### ISSUE TITLE
Add target version and specify docstring style

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#14345]
https://github.com/astropy/astropy/blob/3510bc2ac78ddaea2459b07834efbd09cee767f8/pyproject.toml#L75-L76

**Comment by nstarman** [comment]
Ruff will just work better if we tell it our "intended" python version (for all practical purposes, the minimum supported version) as well as what docstring convention we are using (numpy).

- #14277 will fix the target version specification.

**Comment by pllim** [comment]
Ruff isn't smart enough to grab that from `setup.cfg` and `docs/conf.py`?

**Comment by nstarman** [comment]
Maybe eventually for configuration via pyproject.toml, but probably not ever for other / superseded formats.

**Comment by WilliamJamieson** [comment]
@nstarman, was the docstring style set as part of #14285 in commit ed47e90?

**Comment by nstarman** [comment]
Yes. To numpy

**Comment by eerovaher** [comment]
Both the Python target version and the docstring style have been specified in a way Ruff can understand. https://github.com/astropy/astropy/blob/cc73b24619ce37f2af26a0140bbdda8015ac8265/pyproject.toml#L114-L117
https://github.com/astropy/astropy/blob/cc73b24619ce37f2af26a0140bbdda8015ac8265/pyproject.toml#L181-L182
