### ISSUE TITLE
Weird incompatibility between pytest and pyreadline when running tests with pdb on Windows

### ISSUE THREAD

**Issue by embray** [astropy/astropy#1440]
Issue title is a mouthful, I realize.  I've had an issue for a while now that I've never really dug much into because it's difficult as hell to debug.

But when I run the Astropy tests on Windows with `./setup.py test --pdb` or even with `astropy.test(pdb=True)`, and failure does occur (which should cause pytest to drop into a pdb interactive session) I get an infinite loop of errors in pyreadline.  Depending on what appears to be a race condition I get two different errors.

One of them, which I'm now failing to reproduce, complains about `GetConsoleScreenBufferInfo` expecting an `LP_CONSOLE_SCREEN_BUFFER_INFO` but getting a pointer to `CONSOLE_SCREEN_BUFFER_INFO`--a kind of silly error on ctypes' part considering that `LP_CONSOLE_SCREEN_BUFFER_INFO` _is_ a pointer to a `CONSOLE_SCREEN_BUFFER_INFO` structure.

Anyways, the reason for this is that pyreadline and py._io.terminalwriter (which is used by pytest) both use `GetConsoleScreenBufferInfo` from kernel32.dll, but the latter sets its `argtypes` to `[wintypes.HANDLE, POINTER(CONSOLE_SCREEN_BUFFER_INFO)]` while the former sets it to `[c_void_p, c_void_p]`.  If `py._io` gets there second, then it breaks pyreadline.

I think this is a bug in py.io myself (it would do better to just use the more generic `c_void_p`, but I'm going to bring that up with its devs.

The second problem, however, arises in pyreadline regardless of pytest and is a rather complicated issue.  It looks like:

```
Readline internal error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "c:\Python27\lib\site-packages\pyreadline\rlmain.py", line 569, in readline
    self.readline_setup(prompt)
  File "c:\Python27\lib\site-packages\pyreadline\rlmain.py", line 565, in readline_setup
    self._print_prompt()
  File "c:\Python27\lib\site-packages\pyreadline\rlmain.py", line 468, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
  File "c:\Python27\lib\site-packages\pyreadline\console\console.py", line 314, in write_scrolling
    w, h = self.size()
TypeError: 'NoneType' object is not iterable
```

This is actually a rather complicated bug related to http://bugs.python.org/issue8275.  I haven't found a completely satisfactory workaround yet, though I believe one exists.  I think both these issues can by fixed in Astropy with a little monkey-patching, but I'm going to leave it at that for now since I've found uninstalling pyreadline to work as a temporary workaround.

**Comment by nitrocode** [comment]
Definitely still seeing this in 2016 on Windows 8.1. I only see it with --pdb on. I thought it was a pyreadline issue and this issue looked similar in the pyreadline repo.

Ref: https://github.com/pyreadline/pyreadline/issues/18

**Comment by astrofrog** [comment]
I'm labelling this as 'Close?' - even if this is still an issue with pytest/python, it's not an astropy bug as far as I can tell.
