### ISSUE TITLE
"Uniform" string representations of Astropy Quantities

### ISSUE THREAD

**Issue by jeffcarlin** [astropy/astropy#14424]
### What is the problem this feature will solve?

If I have two Astropy `Quantities` and want to print them to the screen with the same number of digits displayed after the decimal, the formatting provided by the `Quantity.round` method doesn't act as expected if the values differ by a few (or more) orders of magnitude. See the example below.

### Describe the desired outcome

Suppose I have two Astropy `Quantities`: `q1 = 19.4301287 marcsec` and `q2 = 0.0000000237904*u.m`. If I want to print these to the screen with the same number of digits after the decimal (i.e., "19.43" and "2.38e-7"), there doesn't seem to be a straightforward method to do so. For example:

```
q1 = 19.4301287*u.marcsec
q2 = 0.0000000237904*u.m
```

The `Quantity.round` method works for q1, but prints "0.0" for q2:

```
print(q1.round(2), q2.round(2))
```

> 19.43 marcsec 0.0 m

I can use the `Quantity.to_string` method to _sorta_ accomplish what I want:
```
print(q1.to_string(format="latex_inline", precision=4), q2.to_string(format="latex_inline", precision=4))
```
yields ```$19.43 \; \mathrm{marcsec}$ $2.379 \times 10^{-7} \; \mathrm{m}$```, but then I've returned latex strings rather than "pretty-printed" values of the floats.

I recognize that both of these methods are based on `numpy` routines, but would it be possible to modify the Astropy `Quantity.round` method so that it would check the value that's being rounded and return something reasonable for tiny (or huge) values? By "reasonable," I mean to round (or truncate) the number of digits in the _coefficient_ of the scientific notation, while keeping the displayed value in scientific notation. (It does not seem like desired behavior for `q2.round(2)` to return 0.0?)

### Additional context

Maybe altering the `round` method isn't what is needed, but a different method altogether?

**Comment by eerovaher** [comment]
A scalar `Quantity` can already be formatted using the [Python format specification mini-language](https://docs.python.org/3/library/string.html#format-specification-mini-language), as demonstrated in the relevant [`astropy` documentation](https://docs.astropy.org/en/stable/units/format.html#converting-to-strings).
```python
>>> from astropy import units as u
>>> q1 = 19.4301287 * u.marcsec
>>> q2 = 0.0000000237904 * u.m
>>> f"{q1:.2f}"
'19.43 marcsec'
>>> f"{q1:.4g}"
'19.43 marcsec'
>>> f"{q2:.2e}"
'2.38e-08 m'
>>> f"{q2:.3g}"
'2.38e-08 m'
```
It is also possible to use `Quantity.to_string()` without specifying `format="latex_inline"`:
```python
>>> q1.to_string(precision=2)
'19.43 marcsec'
>>> q2.to_string(precision=2)
'2.38e-08 m'
```

**Comment by timj** [comment]
That formatting looks interesting but is it possible to make it be a bit cleverer so it changes the SI prefix rather than using the `e-08`? One great feature of `Quantity` is that it knows the units so a way to make `2.3e-8 m` render as `23 nm` would be great.

**Comment by eerovaher** [comment]
Using some specific unit for the string representation of a `Quantity` regardless of the unit it actually has (as long as it has the same physical type) is already possible with very little effort and without modifying the `Quantity` itself:
```python
>>> from astropy import units as u
>>> q2 = 0.0000000237904*u.m
>>> f"{q2.to(u.nm):.0f}"
'24 nm'
>>> q2.to_string(precision=0, unit=u.nm)
'24. nm'
>>> print(q2)
2.37904e-08 m
```
#6913 is a feature request for automatically determining the appropriate unit of a `Quantity` based on the order of magnitude of its value. The discussion there highlights some of the problems this idea has.

**Comment by mhvk** [comment]
@timj - just to summarize what I felt was the main problem with "human readable units": that it all is easy for single units, but becomes very tricky for composite ones (like `km/s` - if you are at the 1e-3 level, do you want `m/s` or `km/hr`?).

**Comment by timj** [comment]
> if you are at the 1e-3 level, do you want m/s or km/hr?

I'd be fine with 1e-3 km/s becoming 1 m/s -- it's still easier to read than 1e-3 km/s. Changing all the units to try to guess what the user wants seems extremely difficult and not necessary.

**Comment by mhvk** [comment]
How about a more complicated example like `1e-20 erg/s/cm^2/Hz`? I just think this is a bit of a hopeless endeavour, and that, in the end, when the units need to be useful for a paper, one has to choose and just do it, rather than hope the package gives a best "guess".

Anyway, that's just me saying I won't be the one implementing it; if someone else wants to have a stab, that's fine. There even is something to base it on (though that didn't deal with composite units at all).
