### ISSUE TITLE
Time addition is imprecise

### ISSUE THREAD

**Issue by spenczar** [astropy/astropy#14455]
### Description

I was surprised to learn that in Astropy, `Time + N * TimeDelta` does not equal `Time + TimeDelta repeated N times`. This is noticeably different from the behavior of Python's `datetime.datetime` and `datetime.timedelta`.

Concretely:

```python
from astropy.time import Time, TimeDelta
from astropy.units import Quantity

# Make a time (at midnight), and make a 2-hour timedelta.
t = Time("2015-01-01")
dt = TimeDelta(Quantity(120, "minute"))

# If I add 12 * 2 hours, that should be the next day. This assertion passes.
assert (t + 12 * dt) == Time("2015-01-02")

# Instead add 2 hours twelve times:
for i in range(12):
    t = t + dt
# Fails:
assert t == Time("2015-01-02") 

# How far off is it?
print(t - Time("2015-01-02"))
# prints "<TimeDelta object: scale='tai' format='jd' value=-1.1102230246251565e-16>"
```

The equivalent `datetime`-based program has no errors:
```py
import datetime

t = datetime.datetime(2015, 1, 1)
dt = datetime.timedelta(minutes=120)

assert (t + 12 * dt) == datetime.datetime(2015, 1, 2)

for i in range(12):
    t = t + dt
assert t == datetime.datetime(2015, 1, 2)
```

I think this isn't just academic. Seemingly simple functions can become off by one. I was trying to write a function which created 2-hour chunks to span a time region; the last chunk can be truncated:

```python
from astropy.time import Time, TimeDelta

def chunked_time_windows(start: Time, end: Time, chunksize: TimeDelta):
    chunks = []
    chunk_start = start
    while chunk_start < end:
        chunk_end = chunk_start + chunksize
        if chunk_end > end: 
            chunk_end = end
        chunks.append((chunk_start, chunk_end))
        chunk_start = chunk_end
    return chunks
```
This is subtly quite buggy. If you run `chunked_time_windows(Time("2015-01-01"), Time("2015-01-02"), TimeDelta(Quantity(120, "minute")))`, you get a list of 13 chunks, not twelve, and the last is
```<Time object: scale='utc' format='iso' value=2015-01-02 00:00:00.000>,
  <Time object: scale='utc' format='iso' value=2015-01-02 00:00:00.000>
  ```

Those look identical. What's going on?

```
In [31]: last[0] - last[1]
Out[31]: <TimeDelta object: scale='tai' format='jd' value=-1.1102230246251565e-16>
```
They're off by a very small delta at the edge of floating point precision.

### Expected behavior

I'd expect multiplication and addition arithmetic to work with `astropy.time.Time`. More deeply, I'd expect Time to be backed by integers to represent the underlying data, and that any floating point representation would just be a format presented to users, so that floating point arithmetical issues wouldn't crop up when adding Time and TimeDeltas.

### How to Reproduce

see above

### Versions

macOS-12.5-arm64-arm-64bit
Python 3.10.10 (main, Feb 21 2023, 13:27:31) [Clang 14.0.0 (clang-1400.0.29.202)]
astropy 5.2.1
Numpy 1.23.5
pyerfa 2.0.0.1
Scipy 1.10.0
Matplotlib 3.6.3

**Comment by mhvk** [comment]
The difference is that `Time` works with two double-precision floats and thus suffers from rounding errors, just like any work with floating point numbers. The units are days, so anything that is not a power-of-two fraction of a day will cause rounding errors. In your case, by the least significant bit in the double representing the fraction of a day (2**-53=1.1102230246251565e-16).

In contrast, `datetime` works with integers internally, so has no rounding errors, but obviously has other problems: precision set by smallest unit represented, no leap seconds, no timescales, etc.

Unfortunately, this cannot be fixed: we cannot use integers internally as then we would not be able to represent different timescales (which have varying scale differences).

**Comment by spenczar** [comment]
@mhvk Thanks for the response. I agree this doesn't seem fixable. I suspected the answer would be something like what you say, but figured I'd make an issue anyway because I was surprised that nobody else had raised this.

**Comment by mhvk** [comment]
@spenczar - no problem! Always good to raise issues -- and often we can do something about it!!
