### ISSUE TITLE
Writing ECSV table seems to ignore formats of columns depending on write method

### ISSUE THREAD

**Issue by gmduvvuri** [astropy/astropy#14461]
### Description

I was trying to write a more compact version of some columns in an ascii.ecsv table by limiting the precision of floats with ".3e" format and tried multiple approaches: setting the "format" or "info.format" attributes of those columns, and constructing a dict to pass to the formats={"colname" : colformat} keyword in the Table.write(). While the printed output of the table was modified appropriately, the saved file was not. I found a version that did work with the ascii.write() function if I did not specify the ecsv format using the keyword, but using the filename extension, but this difference in behavior does not seem intended.

### Expected behavior

The printed output of the astropy.table.Table should match the saved output of the astropy.table.Table.write(fname, format='ascii.ecsv') with matching column formats.

### How to Reproduce

```
from astropy.io import ascii
from astropy.table import Table

data = [1.341e-15, 1.256e-15]
tb = Table()
tb['a'] = data
print(tb)
tb['a'].format = '.1e'
print(tb)
tb.write('incorrect_output.ecsv', format='ascii.ecsv')
ascii.write(tb, 'also_incorrect_output.ecsv', format='ecsv')
tb.write('also_also_incorrect_output.ecsv')
ascii.write(tb, 'correct_output.ecsv')
```

### Versions

import platform; print(platform.platform())
import astropy; print("astropy", astropy.__version__)

Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid (Windows Subsystem for Linux 1 on Windows 10)
astropy 4.3.1 (tried conda update astropy and it still gave me this version?)

**Comment by pllim** [comment]
astropy 4.3.1 is very old and no longer supported.

What Python version are you using? If it is Python 3.7 or older, you should get a newer Python to get a newer astropy. It should be astropy 5.2.1 now.

**Comment by pllim** [comment]
That said, I can reproduce this behavior in astropy 5.3.dev but I am not sure if it is a bug.

### incorrect_output.ecsv

This is the same content in all the "also" variations.

```
# %ECSV 1.0
# ---
# datatype:
# - {name: a, datatype: float64, format: .1e}
# schema: astropy-2.0
a
1.341e-15
1.256e-15
```

### correct_output.ecsv

This is what you want but it is also not really ECSV. Note the absence of the `#` header. You can actually get this as follows:

```python
tb.write('also_correct_output.txt', format='ascii.basic')
```
```
a
1.3e-15
1.3e-15
```

**Comment by pllim** [comment]
Maybe @hamogu, @dhomeier, or @taldcroft can confirm.

**Comment by hamogu** [comment]
ECSV is intended to be almost the ASCII equivalent of a binary file - all data looks (to the extend possible) the same after saving and re-opening. On the other end, the format of a column is meant for display purposes - you just show the first few digits on the screen, but you know that the binary number in the computer memory is not changed. 

In that sense, this behavior is not a bug - it's an intentional choice. If you want smaller files but don't need keep the full prevision, you should do exactly what you did: Write an ascii file in a different format. Alternatively, you could change the data in memory, e.g. by using numpy functionality to round the numbers so that the actual binary representation is 3.12 and no longer 3.1178393298475756. Once that is done, you should be able to write to ecsv and get files that just say "3.12" in them and are thus smaller.

**Comment by hamogu** [comment]
That said, is there a specific place in e.g. the documentation where you looked and where we could explain that better, @gmduvvuri ?

**Comment by gmduvvuri** [comment]
The use of the formats dict keyword as described here: https://docs.astropy.org/en/stable/io/ascii/write.html

I was under the impression this controlled both display and save output with the current text. Having ECSV be an ascii format analogous to binary makes sense to me so I think you can close this issue (but referencing the feature request for a human-readable ecsv format, this may be a thing to add there)

**Comment by taldcroft** [comment]
I cannot find the PR just now, but we did explicitly change the ECSV writer at some point to always output full precision, echoing what @hamogu said about ECSV being analogous to a binary format like FITS. This avoids pitfalls like wanting the data formatted nicely when viewing it for data analysis (by setting column formats) but then losing precision in the data table when writing to ECSV.

For human-readable output I would recommend a fixed-width format. Recent versions of astropy allow putting some column metadata into the output, see: https://docs.astropy.org/en/stable/io/ascii/fixed_width_gallery.html#custom-header-rows

**Comment by dhomeier** [comment]
> For human-readable output I would recommend a fixed-width format. Recent versions of astropy allow putting some column metadata into the output, see: https://docs.astropy.org/en/stable/io/ascii/fixed_width_gallery.html#custom-header-rows

1. Has the `dtype` entry ("1st line") somehow been lost in that example?
2. There is no way to create a complete ECSV header and prepend it to a fixed-width table, right?

**Comment by taldcroft** [comment]
> Has the dtype entry ("1st line") somehow been lost in that example?

Good catch. The example is correct but the explanation below ("In this example ...") is wrong.
