### ISSUE TITLE
New Quantity warning starting with yesterday's numpy-dev

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#14483]
### Description

Starting today, `photutils` CI tests with `astropy-dev` and `numpy-dev` started failing due a new warning.  I've extracted a MWE showing the warning:

```python
import astropy.units as u
import pytest
from numpy.testing import assert_equal

a = [78, 78, 81] * u.pix**2
b = [78.5, 78.5, 78.625] * u.pix**2
with pytest.raises(AssertionError):
    assert_equal(a, b)
```
The warning is:
```
WARNING: function 'max' is not known to astropy's Quantity. Will run it anyway, hoping it will treat ndarray subclasses correctly. Please raise an issue at https://github.com/astropy/astropy/issues. [astropy.units.quantity]
```

The warning is not emitted with `astropy-dev` and `numpy` stable (1.24.2).

CC: @mhvk

**Comment by pllim** [comment]
We saw this downstream in Jdaviz too. cc @bmorris3

**Comment by mhvk** [comment]
Ha, that's interesting. I guess since they are deprecating `np.a{max|min}`, it is no longer true that `np.max is np.amax`...

**Comment by mhvk** [comment]
The other thing that has changed is that `np.round_` has been deprecated. .. Better check #14484! More there...
