### ISSUE TITLE
Units sometimes don't understand when they should change

### ISSUE THREAD

**Issue by jmason86** [astropy/astropy#14485]
### Description

The `.to()` function returns a float rather than a quantity, which can lead to some unexpected behavior -- particularly if one is assuming that the expected behavior is what is actually happening but the user fails to verify the actual behavior. 

Broader context: 
I'm computing hc/lambda. I'm using astropy constants for h and c. I've been carrying around my wavelengths as an astropy quantity with angstrom units. hc/lambda should end up giving me Joules. 
It is possible to hack around the issue like this: 
```
const.h * const.c / (u.angstrom.to(u.m) * u.m)
> <Quantity 1.98644586e-15 J>
```
but again, a user would only realize a hack like this was necessary if they discovered that `.to()` wasn't retaining units. 

### Expected behavior

```
u.m**2 / u.angstrom.to(u.m)
> <Quantity 1.e+10 m>
```

### How to Reproduce

```
import astropy.units as u

u.m**2
> Unit("m2") # Looks good

u.m**2 / u.m
> Unit("m") # Looks good

u.m**2 / u.angstrom
> Unit("m2 / Angstrom") # okay, that's understandable

u.m**2 / u.angstrom.to(u.m)
> <Quantity 1.e+10 m2> # That's not what I would expect
```

### Versions

astropy version 5.1

**Comment by byrdie** [comment]
While I agree that the behavior of `Unit.to()` is a little surprising given the behavior of `Quantity.to()`, I think the best way to accomplish your goal is to just try and convert your original expression to Joules directly.
```python3
>>> (const.h * const.c / u.angstrom).to(u.J)
<Quantity 1.98644586e-15 J>
```
Does this work for your needs?

**Comment by jmason86** [comment]
That does do the trick, but I just uncovered something since posting the issue that confuses me even more... the expected behavior _does_ occur when I'm using an array: 

```
u.m**2 / (np.array([1, 2, 3]) * u.angstrom).to(u.m)
<Quantity [1.00000000e+10, 5.00000000e+09, 3.33333333e+09] m>
```

I think this inconsistency is even more surprising than my original issue.

**Comment by byrdie** [comment]
That is happening since `np.array([1, 2, 3]) * u.angstrom` is an instance of `astropy.units.Quantity`, but `u.angstrom` is just an instance of `astropy.units.Unit`. The array is not even necessary for that behavior to happen, consider
```python3
>>> u.m**2 / (1 * u.angstrom).to(u.m)
<Quantity 1.e+10 m>
```
In the example above `1 * u.angstrom` is an instance of `astropy.units.Quantity` which is why it works differently from your original example.
