### ISSUE TITLE
Enable GitHub auto-merge for pull requests

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14490]
Feature to introduce: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

What this means:

* A maintainer will have one more option when a pull request is ready to be merged but CI is still running: "Merge via auto-merge"
* We will retire the `merge-when-ci-passes` label by prepending 💤 to it.
* We have to enable branch protection rules for *all* branches, not just `main`.
* We have to agree on a place in the docs to talk about this feature and how to use it properly.

What this feature is *not* for (but there is no way we can automatically enforce them, so these are risks we have to accept):

1. If a pull request requires job(s) that is not required to pass branch protection rules (e.g., allowed to fail job, cron jobs) to pass to be acceptable (say, it touches remote data or has very big changes that need extra checks).
2. If a pull request requires approvals from multiple reviewers and not all the reviews are in but some are happy.
3. Someone with write access uses this feature without realizing the side effects.
4. Someone with write access tries to auto-merge their own pull requests without meeting all the approvals.

Concerns:

* What if someone pushes undesirable code to the pull request after auto-merge is in place? This is not an issue if the author does not have write access already. *"After you enable auto-merge for a pull request, if someone who does not have write permissions to the repository pushes new changes to the head branch or switches the base branch of the pull request, auto-merge will be disabled. For example, if a maintainer enables auto-merge for a pull request from a fork, auto-merge will be disabled after a contributor pushes new changes to the pull request."*
* What if someone set auto-merge on a pull request and another disagrees? If the person who disagrees also has write access, there is an option to disable it. If it is too late, we can revert, though if we find ourselves reverting too often, then we might have to get rid of auto-merge altogether.

Next steps:

- [x] This issue will be sent to maintainers mailing list to solicit feedback. See https://groups.google.com/g/astropy-core-maintainers/c/dx246bIFfdg/m/Jmp1jnaGAQAJ
- [x] If feedback is favorable, this will be implemented, taking into account any feedback comments.
- [ ] If feedback is unfavorable, this issue will be closed without any further action.

**Comment by kelle** [comment]
Could you point to some example PRs which are relevant to this discussion? E.g, a PR or two which could have been auto-merged? Or some where auto-merge would have led to undesirable outcomes?

**Comment by eerovaher** [comment]
As discussed in the dev telecon auto-merge can be very convenient for backports and in situations where we would currently use the `merge-when-ci-passes` label.

**Comment by mhvk** [comment]
I'm in favour - we should just be clear to treat it as equivalent to the current `merge-when-ci-passes` - except now we don't have to rely on someone to remember/half-keep-waiting to press the merge button. I don't recall any situation where in review someone had to remove the `merge-when-ci-passes`, so think we're fine as long as we remain as friendly and careful a bunch as we usually are!

**Comment by pllim** [comment]
> Could you point to some example PRs which are relevant to this discussion? E.g, a PR or two which could have been auto-merged?

https://github.com/astropy/astropy/labels/merge-when-ci-passes (huh, there are actually 2 still open)

> Or some where auto-merge would have led to undesirable outcomes?

This is currently not possible because it is not automated (hence, this proposal to automate it).

**Comment by WilliamJamieson** [comment]
Aside from `main`, we could use `automerge` to effectively automate  merging of the @meeseeksmachine backport PRs on the backport branch with something like: https://github.com/asdf-format/asdf/blob/3c83a49de6ab7455a4cd2bcc4aea65704a582db3/.github/workflows/label.yml#L38-L49. Which would lessen the need for someone to constantly deal with merging the backport PRs. Instead, the majority of them would go through automagically unless an issue crops up in the CI. In this case, I think the total automation of merging automatically generated backport PRs should pose limited risks as the code will have already been fully reviewed in the original PR and automatically generated backports only succeed if cherry-picking the exact changes of the original PR is possible.

I understand we are not a huge fans of using third-party CI workflows, but I don't think it would be too hard to write our own workflow which performs this action.

**Comment by WilliamJamieson** [comment]
> What this feature is _not_ for (but there is no way we can automatically enforce them, so these are risks we have to accept):
> 
> 1. If a pull request requires job(s) that is not required to pass branch protection rules (e.g., allowed to fail job, cron jobs) to pass to be acceptable (say, it touches remote data or has very big changes that need extra checks).

Since auto-merge is something a maintainer (or someone with write access) has to choose to enable, I don't see this as a huge problem because they could just wait for the branch protections to be satisfied and then manually merge the PR.

> 2. If a pull request requires approvals from multiple reviewers and not all the reviews are in but some are happy.

Again, a maintainer can simply wait for the branch protections to pass and then just merge the PR anyways. I feel that in general, the astropy maintainers all have a good working relationship, and in general wait for a consensus to accept a PR to develop before merging anyways.

> 3. Someone with write access uses this feature without realizing the side effects.

This can be mitigated by good documentation.

> 4. Someone with write access tries to auto-merge their own pull requests without meeting all the approvals.

I don't think Github allows you to approve your own pull request (at least it does not let me do this), simply requiring a pull request to be approved by a reviewer as part of the branch protections should make it so that the PR cannot be merged using auto-merge without a 3rd party approval, who could simply disable the auto-merge if they disagree with it.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/issues/14490#issuecomment-1454147228

Since I am the one who do most of the merging of backports nowadays, I am on the fence on this one. Some easy ones I'd like to auto auto-merge, but not necessarily a bigger PR. I am okay with manually enabling auto-merge for backports for now.

**Comment by astrofrog** [comment]
Is there any risk on auto merging backports of any size if the CI passes?

**Comment by saimn** [comment]
Makes sense to use that for backports and to replace `merge-when-ci-passes` so :+1: for me.

**Comment by pllim** [comment]
So, I don't see any objection. Is it a go?

**Comment by pllim** [comment]
Please see https://github.com/astropy/astropy/pull/14647 . I already enabled the option for this repo, but the PR formalizes it.
