### ISSUE TITLE
AttributeError: module 'astropy.coordinates' has no attribute 'representation'

### ISSUE THREAD

**Issue by jortiz12** [astropy/astropy#14492]
Dear Community,

I'm unable to open a QTable as per the following code,
`final_sources3_vel = Table.read(path_step1 + name, format ='ascii.ecsv')`
, with this error message
`AttributeError: module 'astropy.coordinates' has no attribute 'representation'
`
I was oble to open it in the past. Any advice would be much appreciated.

Thxs vm
Jose

**Comment by pllim** [comment]
Hello and thanks for reaching out to us. We would need for information to proceed. Are you able to share the file that cause this error (or part of it that is enough to cause this error)?

What has changed between when it last worked and now? Did you upgrade, switch machine, is the file provided by third-party service, etc?

Also please provide version info:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)
```

**Comment by jortiz12** [comment]
Many thanks, first.
I guess it's to do with the order I load packages. After rearring such order, these are my versions and problem has disappeared.

![imagen](https://user-images.githubusercontent.com/2719866/223672184-79460012-8db7-4a14-a131-b2a76bcaaa49.png)

Kind rgds
Jose

**Comment by pllim** [comment]
Something else you loaded overwrote `astropy.coordinates`? That is scary. Anyway, I am glad the problem went away. Thanks for the update!

**Comment by jortiz12** [comment]
Once again, many thanks for your attention and support.
Jose
