### ISSUE TITLE
numpy.asscalar is removed from numpy release - astropy crashes (v4.0)

### ISSUE THREAD

**Issue by hrkloeck** [astropy/astropy#14506]
### Description

Numpy.asscalar() is removed in v1.23 

release notes: https://numpy.org/doc/stable/release/1.23.0-notes.html#expired-deprecations 

astropy is crashing e.g.

/usr/lib/python3/dist-packages/astropy/units/quantity_helper/function_helpers.py", line 126, in <module>
    np.asscalar,

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by byrdie** [comment]
What version of astropy are you running and would you be able to update it? It looks like this issue has been fixed in astropy 5.0 and later.

**Comment by hrkloeck** [comment]
Hi Roy,

	thanks for the quick reply, I’m running it within a container (which I have not build by myself). Its astropy 4.0, will rebuild the container.

Cheers, Hans
--------------------------------------------------------
Hans-Rainer Klöckner
--------------------------------------------------------
Max-Planck-Institut für Radioastronomie
Auf dem Hügel 69
53121 Bonn
Germany
+49 (0)228 525-338
***@***.***
--------------------------------------------------------
