### ISSUE TITLE
[Bug]: TypeError when changing subplot projection=wcs

### ISSUE THREAD

**Issue by richardon880** [astropy/astropy#14534]
### Description

TypeError when setting subplot projection to wcs. 

### Expected behavior

Expected code to produce below image.
![image](https://user-images.githubusercontent.com/111389724/225383767-27a6bc21-4506-4454-805e-b9cab75c4592.png)

### How to Reproduce

1. Get .fits file for visualisation on wcs axis
2. Plot image with projection=wcs
3. An error occurs.

Below is code from the tutorial example on plotting with WCS Axes. https://docs.astropy.org/en/stable/visualization/wcsaxes/index.html

```python
import matplotlib.pyplot as plt

from astropy.wcs import WCS
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename

filename = get_pkg_data_filename('galactic_center/gc_msx_e.fits')

hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)

plt.subplot(projection=wcs)
plt.imshow(hdu.data, vmin=-2.e-5, vmax=2.e-4, origin='lower')
plt.grid(color='white', ls='solid')
plt.xlabel('Galactic Longitude')
plt.ylabel('Galactic Latitude')```


### Versions

Linux-5.19.0-35-generic-x86_64-with-glibc2.35
Python 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
astropy 5.1
Numpy 1.23.5
pyerfa 2.0.0
Scipy 1.10.0
Matplotlib 3.7.1

**Comment by byrdie** [comment]
Hi @richardon880, thanks for raising this issue. Would you mind posting the full traceback of your error so we can see the circumstances of the error?

**Comment by pllim** [comment]
I think the reply with traceback accidentally became #14535

**Comment by richardon880** [comment]
Upgraded to astropy 5.2.1, it worked as expected. Thanks guys. 
![image](https://user-images.githubusercontent.com/111389724/225591721-6ac779e0-e3f3-4fd9-b90b-5621c426da90.png)
