### ISSUE TITLE
`io.fits.Column` inconsistent round-trip behaviour

### ISSUE THREAD

**Issue by kYwzor** [astropy/astropy#14540]
### Description

For some data types, `io.fits.Column` behaves in a different way when creating a column versus when reading a column from a file. This could lead to subtle mistakes when copying columns from existing files.

(I suspect this might be a consequence of intentional design decisions and not an actual bug, so feel free to explain why this has been done this way)

### Expected behavior

If I create a `ColDefs` object, build a `BinTableHDU` from it, write that table to a file, read it back and access the read `ColDefs` object, I would expect its contents to match the original object.

### How to Reproduce

Let's have a look at how `Column` handles different types of data through the round-trip.
```python
from astropy.io import fits

col1 = fits.Column('floats', format='3D', array=[[1., 2., 3.], [4., 5., 6.]])
col2 = fits.Column('characters', format='3A', array=['ABC', 'DEF'])
col3 = fits.Column('variable', format='QD', array=[[1., 2., 3.], [4.]])

for col in [col1, col2, col3]:
    print(repr(col.array))
```
As expected we get
```
array([[1., 2., 3.],
       [4., 5., 6.]])
chararray(['ABC', 'DEF'], dtype='<U3')
_VLF([list([1.0, 2.0, 3.0]), list([4.0])], dtype=object)
```
Let's write it to a file and read it back:
```python
fits.BinTableHDU.from_columns([col1, col2, col3]).writeto('test.fits', overwrite=True)

with fits.open('test.fits') as hdul:
    for col in hdul[1].columns:
        print(repr(col.array))
```
We get:
```
<astropy.io.fits.column.Delayed object at 0x00000189F8374250>
<astropy.io.fits.column.Delayed object at 0x00000189F8374190>
<astropy.io.fits.column.Delayed object at 0x00000189F8374490>
```
Hmmmm, a bit unexpected that trying to print the array does not force it to load the data, but this is not a big issue. Let's look directly at `data` so that this gets loaded.
```python
    # (continuing within the context above)
    data = hdul[1].data
    print(repr(data['floats']))
    print(repr(data['characters']))
    print(repr(data['variable']))
```
This gets us:
```
array([[1., 2., 3.],
       [4., 5., 6.]])
chararray(['ABC', 'DEF'], dtype='<U3')
_VLF([array([1., 2., 3.]), array([4.])], dtype=object)
```
This looks pretty good, it's essentially what we had saved (bar just a small conversion from `list` to `ndarray` in the VLA case). So we can go back to `columns` which should now be loaded.
```python
    # (continuing within the context above)
    for col in hdul[1].columns:
        print(repr(col.array))
```
Surprisingly we get:
```
array([[1., 2., 3.],
       [4., 5., 6.]])
array([b'ABC', b'DEF'], dtype='|S3')
array([[ 3,  0],
       [ 1, 24]], dtype=int64)
```
The `'floats'` column perfectly survives the round-trip as expected. But now, although the contents of the `'characters'` column are correct, they are unexpectedly formatted as an array of bytes instead of a chararray. And even more surprising, the `'variable'` column no longer contains the data that was stored in it, but instead it contains the two values used in the VLA array descriptor (number of elements and heap offset).
What if we try to copy these columns to a new table?
```python
    # (continuing within the context above)
    tab = fits.BinTableHDU.from_columns(hdul[1].columns)
    for col in tab.columns:
        print(repr(col.array))
```
```
array([[1., 2., 3.],
       [4., 5., 6.]])
chararray(['ABC', 'DEF'], dtype='<U3')
_VLF([array([3., 0.]), array([ 1., 24.])], dtype=object)
```
While both `'floats'` and `'characters'` return to their original intended values, `BinTableHDU` actually deduced that `'variable'` is supposed to be a VLA column whose contents are two arrays of length 2, which is definitely not what we intended. Worryingly this wouldn't raise any warnings and we could write this table to a file without any issue.
____
While this is obviously an unrealistic scenario, I can easily imagine a scenario where someone wants to create a copy of a file where some columns are removed, for example:
```python
with fits.open('test.fits') as hdul:
    cols = hdul[1].columns[1:]  # I want to skip the first column and copy the rest
    tab = fits.BinTableHDU.from_columns(hdul[1].columns)
    tab.writeto('newfile.fits')
```
To me this _looks_ like a very intuitive and simple way of removing a column. Worryingly, this would actually work without any issue as long the file didn't contain any VLA, but would "fail" silently as soon as a VLA column existed.

I understand all of this could be avoided by just using the `BinTableHDU.data` interface, but this still feels like a very counterintuitive design to me. I don't know how this could be avoided, but I'd be interested to know if this IS actually intended and if so why.

### Versions

Windows-10-10.0.19044-SP0
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
astropy 5.2.1
Numpy 1.24.2
pyerfa 2.0.0.1
Scipy 1.10.0
Matplotlib 3.6.3

**Comment by saimn** [comment]
Well, the code to read tables is a bit complicated... :sweat_smile: 
The fact that data/columns can be accessed both with `hdu.data`/`hdu.data.columns` and `hdu.columns` creates a lot of complexity, and bugs (e.g. #6837). On top of that there are many FITS subtleties like VLA and other, some considerations of performance and memory usage (e.g. caching the column values when they must be converted)... All of this evolves since >20 years (PyFITS' first git commit is from 2000 but it was on cvs before: https://github.com/spacetelescope/PyFITS/commit/819760c253af5fe49d348818a6731e28ee817f41), and we're stuck with that unless someone can put a massive effort in a complete rewrite.

**Comment by pllim** [comment]
@perrygreenfield probably remembers the timeline of PyFITS.
