### ISSUE TITLE
A public interface for user requests.

### ISSUE THREAD

**Issue by demitri** [astropy/astropy#1457]
We need a public web form to accept feature/bug requests from users. The GitHub interface is not only too complicated/involved for casual users (requiring at the very least a GitHub account), but multiple requests for the same features will invariably generate duplicate issues. Issues on GitHub should be items written for developers as specific action items, not littered with "it would be nice if...".

We should also have a "voting" system, so that we track how many requests for the same feature have been received, thus letting the actual needs of the community drive (or at least influence) development efforts.

**Comment by astrofrog** [comment]
We now have the astropy.userecho.com site, so I'm going to close this. I've opened https://github.com/astropy/astropy.github.com/issues/142 to make sure we include a prominent link on the website.
