### ISSUE TITLE
AttributeError: Longitude instance has no attribute 'radian' (but only from pytest 🤷 ) with cds.enabled()

### ISSUE THREAD

**Issue by HealthyPear** [astropy/astropy#14580]
### Description

I have a piece of code that crashes unexpectedly during a pytest session and works fine in a separate IPython session,

```python
swgo_plot/plots/sky.py:447: in plot_sky_areas
    lon[k] = sky_coords[k].geocentrictrueecliptic.lon.deg
../../mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/coordinates/sky_coordinate.py:893: in __getattr__
    return self.transform_to(attr)
../../mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/coordinates/sky_coordinate.py:702: in transform_to
    new_coord = trans(self.frame, generic_frame)
../../mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/coordinates/transformations.py:1579: in __call__
    curr_coord = t(curr_coord, curr_toframe)
../../mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/coordinates/transformations.py:1145: in __call__
    return supcall(fromcoord, toframe)
../../mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/coordinates/builtin_frames/icrs_cirs_transforms.py:124: in icrs_to_gcrs
    gcrs_ra, gcrs_dec = atciqz(srepr.without_differentials(), astrom)
../../mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/coordinates/builtin_frames/utils.py:297: in atciqz
    pco = erfa.s2c(srepr.lon.radian, srepr.lat.radian)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Longitude 175. deg>, attr = 'radian'

    def __getattr__(self, attr):
        """
        Quantities are able to directly convert to other units that
        have the same physical type.
        """
        if not self._include_easy_conversion_members:
            raise AttributeError(
                f"'{self.__class__.__name__}' object has no '{attr}' member"
            )

        def get_virtual_unit_attribute():
            registry = get_current_unit_registry().registry
            to_unit = registry.get(attr, None)
            if to_unit is None:
                return None

            try:
                return self.unit.to(
                    to_unit, self.value, equivalencies=self.equivalencies
                )
            except UnitsError:
                return None

        value = get_virtual_unit_attribute()

        if value is None:
>           raise AttributeError(
                f"{self.__class__.__name__} instance has no attribute '{attr}'"
            )
E           AttributeError: Longitude instance has no attribute 'radian'

../../mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/units/quantity.py:1102: AttributeError
```

### Expected behavior

It should work the same in any environment if the package version is the same

### How to Reproduce

From a pdb session triggered by pytest I get that the triggering line is the following

```
-> lon[k] = sky_coords[k].geocentrictrueecliptic.lon.deg
(Pdb) k
0
(Pdb) sky_coords[k]
<SkyCoord (ICRS): (ra, dec) in deg
    (175., -0.5)>
```

indeed if (still inside pytest/pdb) I try to perform the transformation I get,

`(Pdb) sky_coords[k].geocentrictrueecliptic
*** AttributeError: Longitude instance has no attribute 'radian'`

To be sure I try to replicate the issue from scratch in a separate IPython session,

```ipython
In [1]: from astropy import units as u
   ...: from astropy.coordinates import SkyCoord
   ...: c = SkyCoord(ra=10.625*u.degree, dec=41.2*u.degree, frame='icrs')

In [2]: c.geocentrictrueecliptic
Out[2]:
<SkyCoord (GeocentricTrueEcliptic: equinox=J2000.000, obstime=J2000.000): (lon, lat, distance) in (deg, deg, )
    (27.76134106, 33.31188749, 1.)>

In [3]: c.geocentrictrueecliptic.lon.deg
Out[3]: 27.761341057229142
```

### Versions

macOS-11.7.4-x86_64-i386-64bit
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)
[Clang 13.0.1 ]
astropy 5.2.1
Numpy 1.23.4
pyerfa 2.0.0.1
Scipy 1.9.3
Matplotlib 3.6.2
pytest 7.2.0

**Comment by HealthyPear** [comment]
> ```python
> ../../mambaforge/envs/swgo-plot/lib/python3.9/site-packages/astropy/units/quantity.py
> ```

The trigger seems to be `if to_unit is None`.

**Comment by HealthyPear** [comment]
So it seems that the `radian` attribute is not in the current unit registry when the test is running...but not in   a simple IPython session (within the same conda environment, just to make it clearer)

**Comment by HealthyPear** [comment]
Aha.

```
(Pdb) reg.registry["radian"]
*** KeyError: 'radian'
```

This doesn't happen in a fresh, separate IPython session,

```
In [1]: import astropy.units as u

In [2]: reg = u.get_current_unit_registry()

In [3]: reg.registry["radian"]
Out[3]: Unit("rad")
```

**Comment by pllim** [comment]
Obviously our CI isn't catching this. Is there a way to work this into unit test for `astropy`? 🤔

**Comment by HealthyPear** [comment]
Can you reproduce this problem by just defining a Longitude object and defining a pytest function?

Unfortunately, the software on which I am working is not yet public and anyway the code around it is too complex to just extract a smaller piece of it.

**Comment by pllim** [comment]
I cannot reproduce this directly on `astropy`. I put this test within the test suite of my editabke dev install and nothing failed. So maybe some of your downstream settings is messing with your pytest run.

```python
def test_lon_deg():
    c = SkyCoord(ra=10.625*u.degree, dec=41.2*u.degree, frame='icrs')
    assert_allclose(c.geocentrictrueecliptic.lon.deg, 27.761341057229142)
```

**Comment by HealthyPear** [comment]
I don't know if it can help to clarify my situation, but I can share my conda env

[environment_macos.yml.zip](https://github.com/astropy/astropy/files/11080538/environment_macos.yml.zip)

**Comment by HealthyPear** [comment]
By the way also with your simple `test_lon_deg` I can reproduce the issue

**Comment by pllim** [comment]
I am thinking more like whether you have custom `def_unit` or you enabled some non-mainstream unit format or something like that, rather than your Python env.

**Comment by pllim** [comment]
Try that test in a fresh env.

**Comment by HealthyPear** [comment]
Indeed, a fresh env doesn't give me this problem...now I need to understand where is the difference..

**Comment by mhvk** [comment]
From the sidelines: nice sleuthing! and somewhat happy it is not astropy directly, though curious what is the problem, since hopefully we can guard against it.

**Comment by HealthyPear** [comment]
> I am thinking more like whether you have custom `def_unit` or you enabled some non-mainstream unit format or something like that, rather than your Python env.

I think this is it.

In another module, I have defined a class to create an astropy table out of a data format and _outside_ of it I did,

```python
from astropy.units import cds
cds.enable()
```

because I need to work with units such as "GeV/c".

I commented it out and all my test suites ran fine (also the functions related to that module), so I guess that's it.

I should really enable those units from the class constructor if I need it for that class only, am I right?

Thanks for the suggestion!

**Comment by pllim** [comment]
Thanks for the update, @HealthyPear ! 

Would something like this help? https://docs.astropy.org/en/latest/api/astropy.units.add_enabled_units.html#astropy.units.add_enabled_units

**Comment by HealthyPear** [comment]
I could maybe apply this change permanently, but in that case what is the difference between `cds.enable() `and what you suggest?

**Comment by HealthyPear** [comment]
Currently (after the fix) I am not using it as a context manager, just inside the class constructor, so I am assuming that this effect is linked to the scope of the instance (which is what needs the additional units)....am I wrong in assuming this?

**Comment by pllim** [comment]
Unless you undo it in the destructor, I think `cds.enable()` persists throughout the entire session after the first call but maybe @mhvk can confirm.

**Comment by HealthyPear** [comment]
This seems to clash with the fact that my unit-tests suite now fully succeedes.

**Comment by mhvk** [comment]
p.s. I guess we could at least rewrite the docstring along the lines of 
```
This is usually used as ``with cds.enable():`` to enable CDS units only
temporarily, since quite a few astropy classes require the regular
unit system to be in place.
```

**Comment by HealthyPear** [comment]
Maybe we can mention this where the user first finds it (I think I did it from here):
https://docs.astropy.org/en/stable/units/index.html#module-astropy.units.cds

**Comment by mhvk** [comment]
@HealthyPear - yes, that sounds like a good place. Do you want to do it? If not, no worries; I can make a quick PR

**Comment by HealthyPear** [comment]
@mhvk I can do it, but I would like to clear out my use-case, which is to use this feature inside a class.

Right now I am simply doing `cds.enable()` inside the class constructor and all seems to be fine - I don't know the internals of this part of astropy's API, but to me, it seems OK because I would expect this effect to die" with the instance (which in my case triggered the problem from inside a test function).

If this is not correct and it works in my case by chance, what is the right way to do this from within a class?

I think it's worth to add also this use-case to the explanation.

**Comment by HealthyPear** [comment]
Ah damn, now it doesn't work again even inside the constructor!

I definitely need to know how to use this properly then :)

**Comment by mhvk** [comment]
@HealthyPear - I'm actually surprised it works inside your class constructor, since in the end `cds.enable()` changes the units registry, which should not know about your class... So, I think I would do `with cds.enable()` also at the point you need it inside the class.

...

Ah, so that's consistent at least!

**Comment by HealthyPear** [comment]
For a moment it worked, though, I swear! 🤣

**Comment by pllim** [comment]
@HealthyPear , any interest to pursue the doc update mentioned in https://github.com/astropy/astropy/issues/14580#issuecomment-1487009099 ? Thanks!

**Comment by HealthyPear** [comment]
since I stumbled upon this issue again I was thinking: `rad` seems to be always defined, even when `cds` units are enabled, so why don't why just always use `rad` instead of `radians`?

In the specific of this issue what I am suggesting is to modify the API related to this part of the frame conversion,

```
File ~/Applications/mambaforge/envs/pyswgo/lib/python3.11/site-packages/astropy/coordinates/builtin_frames/utils.py:297, in atciqz(srepr, astrom)
    294 ignore_distance = srepr_distance.unit == u.one
    296 # BCRS coordinate direction (unit vector).
--> 297 pco = erfa.s2c(srepr.lon.radian, srepr.lat.radian)
    299 # Find BCRS direction of Sun to object
    300 if ignore_distance:
    301     # No distance to object, assume a long way away
```

so instead of doing `srepr.lon.radian` either:
- always do `srepr.lon.rad`
- or permanently add `radian` to the container registry as an alias to `rad`

what do you think?

**Comment by pllim** [comment]
@HealthyPear , thanks for the update. The only way to find out is to open a draft PR with your changes and see if CI gets green. 😉  Thanks!

**Comment by mhvk** [comment]
I'd vote for using the more limited API (probably faster) of `lon.to_value(u.rad)`, which should always work too, and doesn't rely on the fact that `Angle` tries to interpret unknown attributes as units.
