### ISSUE TITLE
astropy update has caused normalization to be default in the convolve function while your documentation says its not.

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#14609]
### Description

From a user, per email to "feedback@astropy.org":

> Hello astropy group!
>
> Awesome software that I constantly use!!!! It’s amazing 😊
>
> I noticed a later astropy update has caused normalization to be default in the convolve function while your documentation (https://docs.astropy.org/en/stable/api/astropy.convolution.convolve.html) says its not. I only noticed because the function started outputting different results in my code after a few years (I used to use Python3.5.2 but now 3.7), which revisit drill down resulted in this finding and setting normalization to False became required.

### Expected behavior

see description

### How to Reproduce

check docs

### Versions

unclear

**Comment by pllim** [comment]
> I used to use Python 3.5.2 but now 3.7

By being stuck in Python 3.5, user was probably locked into a very old version of `astropy` (the change log does not tell me directly which astropy version dropped Python 3.5 so one has to dig the git blame if one really needs to find out). Now that user upgrades to Python 3.7, suddenly user is many major versions of `astropy` ahead, so behavior change is not unexpected.

> says its not

I cannot find the text in https://docs.astropy.org/en/stable/api/astropy.convolution.convolve.html that says normalization should not happen by default. In fact, `normalize_kernel=True` is stated in the function signature. Did I miss something?

**Comment by pllim** [comment]
Looks like @keflavich changed the default back in https://github.com/astropy/astropy/pull/5782 that was milestoned to `astropy` v2.

**Comment by pllim** [comment]
And while we're in this topic, I would advise user to go beyond Python 3.8. Otherwise, user will not get new releases going forward. Also, if user is a maintainer of a package or pipeline, do test against the dev version of astropy to future-proof the downstream code.

**Comment by hamogu** [comment]
Since it's not an issue with the current version, I'm closing this.
