### ISSUE TITLE
BUG: `deprecated()` is misused in several places

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#14662]
### Description

``since`` is a mandatory arg for `deprecated()`, but it's a string, and therefore when the decorator is used in a way to provide a message (as a positional arg) and and alternative, the message is taken as `since`.
The result is a mismatch of the default message and the alternative for the warning message, and and a misused message in place of the version for the docstring.

Run into it while looking for usage of `alternative`, e.g. in `astropy.coordinates.angle_formats`, but a systemic search and fix would be needed to fix this for all.

```[tasklist]

- [ ] https://github.com/astropy/astropy/pull/14663
- [ ] https://github.com/astropy/astropy/pull/14664
```

**Comment by pllim** [comment]
The `angle_formats` mistake was made in #13162 . I even approved that PR, so clearly it was an oversight on both the author and reviewers side. 😬  Will fix. Good catch!

**Comment by pllim** [comment]
I opened #14663 and #14664 with intention to backport. Though one could argue that fixing them in release branches might break downstream checking, so we should not backport after all. I am open to discussions w.r.t. the need to backport or not.
