### ISSUE TITLE
BUG: change representation of votable.tree.Table vs table.Table

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#14700]
More often than not it's rather confusing (and annoying) that a VOTable and a Table look exactly the same, but obviously, they don't behave the same way and don't have the same methods available, etc.

I would suggest to change the votable case of `<Table length=4>` to something else, e.g. `<VOTable length=4>`.

```
In [53]: import pyvo as vo

In [54]: from astropy.table import Table

In [55]: allwise = vo.regsearch(servicetype='sia', keywords=['allwise'])

In [56]: result = allwise[0].search(pos=(151.1, 2.0), size=0.1)

In [57]: result
Out[57]: 
<Table length=4>
      sia_title        ...    coadd_id  
                       ...              
        object         ...     object   
---------------------- ... -------------
W1 Coadd 1512p015_ac51 ... 1512p015_ac51
W4 Coadd 1512p015_ac51 ... 1512p015_ac51
W3 Coadd 1512p015_ac51 ... 1512p015_ac51
W2 Coadd 1512p015_ac51 ... 1512p015_ac51

In [58]: isinstance(result, Table)
Out[58]: False

In [59]: result.to_table()
Out[59]: 
<Table length=4>
      sia_title        ...    coadd_id  
                       ...              
        object         ...     object   
---------------------- ... -------------
W1 Coadd 1512p015_ac51 ... 1512p015_ac51
W4 Coadd 1512p015_ac51 ... 1512p015_ac51
W3 Coadd 1512p015_ac51 ... 1512p015_ac51
W2 Coadd 1512p015_ac51 ... 1512p015_ac51

In [60]: isinstance(result.to_table(), Table)
Out[60]: True
```

**Comment by pllim** [comment]
Looks like a conscious design choice. Not sure if there is an easy way to change it. Ideas welcome!

https://github.com/astropy/astropy/blob/b3b8295c4b0478558bd0e4c6ec28bf16b90880b8/astropy/io/votable/tree.py#L2422-L2429

**Comment by bsipocz** [comment]
It maybe conscious, or just history, either case I think it maybe also responsible for the occasional confusion and questions we get at the Navo workshops about votable vs table.

I meant to cc @tomdonaldson.

**Comment by pllim** [comment]
Well, maybe we can patch the start of the returned string, like replacing `<Table` with `<VOTable`, if that isn't too hacky.

**Comment by bsipocz** [comment]
Yes, I think that would be an ideal solution.

**Comment by pllim** [comment]
Note to self: To grab VOTable without internet access, can also use this:

```python
from astropy.utils.data import get_pkg_data_filename
fn = get_pkg_data_filename("data/regression.xml", package="astropy.io.votable.tests")
t = parse(fn).get_first_table()
```

And looks like only `repr` is affected.
