### ISSUE TITLE
Meaningful exceptions in convolution

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#14727]
### What is the problem this feature will solve?

Convolution raises bare Exceptions!

https://github.com/astropy/astropy/blob/8381f30c8b38f142a45acd747ac2afbede57db2e/astropy/convolution/core.py#L379-L381

### Describe the desired outcome

Have meaningful errors.
Maybe whip up a quick

```python
class KernelException(Exception):
    """An exception for kernel convolution."""
```

Bare Excepts are a classic anti pattern.

### Additional context

Noticed by Ruff in https://github.com/astropy/astropy/pull/14724

**Comment by nstarman** [comment]
We should do a followup to update the tests from `pytest.raises(Exception)` to `pytest.raises(KernelArithmeticError)`

Also, maybe all the Kernel error classes should have a common base class?

**Comment by larrybradley** [comment]
@nstarman I'm working on a PR to clean up various `convolution` exceptions.  I'll also update the tests from https://github.com/astropy/astropy/pull/14724.
