### ISSUE TITLE
DOC: Clarify that ruff standards in core do not automatically apply to coordinated and affiliated packages

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14737]
Make it clear that the `ruff` checks happening in this repo (core) do not automatically apply to coordinated/affiliated packages (opt-in only).

@weaverba137 , do you have a suggestion on where is the best place in the docs for this? Thanks!

cc @nstarman and @WilliamJamieson

**Comment by weaverba137** [comment]
It seems like there must be a list of other standards that we do or do not hold affiliated packages to, so that would be the logical place. I can try to track that down, but maybe someone already knows where that is.
