### ISSUE TITLE
Create ruff.toml and re-organize the exception codes

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14736]
This came out of Astropy Coordination Meeting 2023. As `pyproject.toml` contains more things related to build, it is better to declutter it by moving ruff settings to its own `ruff.toml`. While we're at it, we should also organize the codes by logical sections so it is easier for future maintainers (e.g., "never un-ignore these ones"). Then we add @nstarman and @WilliamJamieson as codeowners for the new `ruff.toml` file.

**Comment by eerovaher** [comment]
Are we planning to have a permanent `ruff.toml` or is this a temporary solution until our Ruff configuration has stabilized (i.e. the rules that could be enforced are not ignored anymore)?

**Comment by nstarman** [comment]
My hope is the latter.

**Comment by nstarman** [comment]
When we do all the TODOs then the ruff config is relatively short.

**Comment by mhvk** [comment]
If `pyproject.toml` should contain only things related to build, then I guess logically the `black` setup should also move out of it. And arguably CI-related stuff too...

To be honest, I don't really see the point of moving `ruff` out, especially as @nstarman is making steady progress on the `TODO` items... (but realize I wasn't at the discussion - sadly, I've not been able to attend much of the meeting, sorry!).

**Comment by nstarman** [comment]
I think there were 2 desires to temporarily move ruff to its own file. First was that we are going to move setup.cfg to the toml and all the ruff activity was a bit of a distraction. Second is to have the Codeowners auto-review request  be able to distinguish between ruff and not PRs, while both are seeing activity. When there are fewer TODO we should definitely move ruff back to pyproject.toml!

**Comment by mhvk** [comment]
OK, sounds good! Especially since the PR is already there...

**Comment by eerovaher** [comment]
Perhaps it would be better to keep the permanent configuration in `pyproject.toml` and only move the TODO items to `ruff.toml`. I will describe this in more detail in the pull request.
