### ISSUE TITLE
crash/bug when reading table meta-data containing object array written with serialize_meta=True to HDF5 file

### ISSUE THREAD

**Issue by johannesulf** [astropy/astropy#14748]
### Description

Please see the code below that crashes unexpectedly after the first run, i.e. typically at the second run. I'm puzzled by the behavior. Note that the code doesn't crash if a.) `bands` would be a byte string array, b.) `serialize_meta` was False or c.) a table was written where `serialize_meta` was True before reading the table (that's why the first run doesn't crash).

I'm sorry if what I'm doing is not supported. In any case, that the code just crashes with a segmentation fault is puzzling. I've run the code on 2 machines and 3 different virtual environments and they all crashed eventually.

### Expected behavior

No crash and consistent output, i.e. `OrderedDict([('bands', array(['g', 'r', 'i'], dtype=object))])`, when running the code repeatedly.

### How to Reproduce

I ran the following code in a virtual environment on Fedora 38 with python 3.11 and packages installed via pip. Here's the minimal `requirements.txt`.

astropy==5.2.2
h5py==3.8.0
numpy==1.24.3
packaging==23.1
pyerfa==2.0.0.3
PyYAML==6.0

The following code crashes after running the script a second time. In other words, if I run the script once, it works fine and outputs the expected result. But when running it again, it typically crashes with a segmentation fault. Sometimes, the second and later run give a wrong result, i.e. OrderedDict([('bands', array(['R', 'r', 'i'], dtype=object))]).

```python
from astropy.table import Table
import numpy as np
from pathlib import Path

table = Table(np.arange(5))
table.meta['bands'] = np.array(['g', 'r', 'i'], dtype=object)

path = Path('test.hdf5')
if not path.exists():
    table.write(path, serialize_meta=True)
print(Table.read(path).meta)
```

### Versions

Linux-6.2.14-300.fc38.x86_64-x86_64-with-glibc2.37
Python 3.11.3 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230401 (Red Hat 13.0.1-0)]
astropy 5.2.2
Numpy 1.24.3
pyerfa 2.0.0.3

**Comment by mhvk** [comment]
What a strange bug! Weirdly, I cannot reproduce it locally (Debian testing, python 3.11.2, numpy 1.24.2, astropy 5.2.1). Could you cross-check the code you have above? It is the idea that on the second run, the file does not get overwritten, i.e., just executing the `print(Table.read(path).meta)` line multiple times causes problems?

**Comment by johannesulf** [comment]
The main idea is that during the first run, a file is written but not during the second run. Strangely enough, the following code never crashes since a file is always written before reading the table.

```
from astropy.table import Table
import numpy as np
from pathlib import Path

table = Table(np.arange(5))
table.meta['bands'] = np.array(['g', 'r', 'i'], dtype=object)

path = Path('test.hdf5')
table.write(path, serialize_meta=True, overwrite=True)
print(Table.read(path).meta)
```

This is very bizarre and I have no clue what's going on since all I get is a segmentation fault when trying to access the meta-data of the table that was read.

**Comment by johannesulf** [comment]
Finally, here's the result from the second machine I ran the original code on.

```
(env) [jolange@lux-1 lux]$ python mwe.py 
OrderedDict([('bands', array(['g', 'r', 'i'], dtype=object))])
(env) [jolange@lux-1 lux]$ python mwe.py 
OrderedDict([('bands', array(['X', 'r', 'i'], dtype=object))])
(env) [jolange@lux-1 lux]$ python mwe.py 
OrderedDict([('bands', array(['X', 'r', 'i'], dtype=object))])
(env) [jolange@lux-1 lux]$ python mwe.py 
Segmentation fault (core dumped)
(env) [jolange@lux-1 lux]$ 
```

The behavior is slightly different: the first few runs after the first there's an error in what's being read. It only crashes during the 4th run.

Here's the setup for the second machine.

Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
Python 3.8.6 (default, Nov 17 2020, 21:30:26) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
astropy 5.2.2
Numpy 1.23.5
pyerfa 2.0.0.1
Scipy 1.9.3
Matplotlib 3.6.2

Finally, if the OS versions are any helpful. The first machine in the original post is Fedora 38, the third is RHEL 8.2 and the second one described here is CentOS 7.9.

**Comment by pllim** [comment]
Re: segmentation fault

Are you able to get more traceback using `gdb`? 👀

**Comment by johannesulf** [comment]
@pllim I don't have any experience using `gdb` to debug a python program that crashes. If you tell me what to do, I'd be happy to help.

**Comment by pllim** [comment]
Usually it would be something like this. The `.py` file has to be executable from CLI and should contain the code that would reproduce the seg fault. After it crashes, you could use the usual `gdb` commands, e.g., `where`:
```
$ gdb
(gdb) file python
(gdb) run /my/script/that/crashes.py
... # Reproduce the error on the GUI
(gdb) where
```

**Comment by pllim** [comment]
p.s. You might need a version of Python with debug enabled; not sure. I don't run it often enough to remember now.

**Comment by taldcroft** [comment]
@johannesulf - Do you reproduce that error with below (i.e. `str` not `object`)?
```
table.meta['bands'] = np.array(['g', 'r', 'i'], dtype=str)
```

**Comment by johannesulf** [comment]
@taldcroft No, if I use `str` everything works as expected.

**Comment by johannesulf** [comment]
@pllim Weirdly enough, it doesn't crash when running it this way. It always correctly prints the meta-information.

**Comment by taldcroft** [comment]
@johannesulf - one thing is to separate out the `Table.read()` call from accessing and printing `.meta`.

My guess is that the seg fault happens in the HDF5 library table read since that is compiled code and it is unusual to get a seg fault from pure Python.

Since the astropy devs here have not been able to reproduce this, I wonder if you can dig in with our guidance. The place to start is here: https://github.com/astropy/astropy/blob/dd0317de9fff2b5d3b12f6d488ae3ebdf58c3596/astropy/io/misc/hdf5.py#L63

That function is unfortunately written to call itself recursively, but the action starts here:
https://github.com/astropy/astropy/blob/dd0317de9fff2b5d3b12f6d488ae3ebdf58c3596/astropy/io/misc/hdf5.py#L154

If you can make a virtualenv with the same packages but install the dev astropy from git main with `pip install -e ".[all,test_all,docs]"`. Then reconfirm the behavior in that setup. If you know how to do line-by-line tracing with an IDE then do that, otherwise just putting in print statements and re-run to see just where it is crashing.

**Comment by saimn** [comment]
```
❯ python -X faulthandler test.py
Fatal Python error: Segmentation fault

Current thread 0x00007f8b96d44740 (most recent call first):
  File "/home/simon/.pyenv/versions/3.11.0/lib/python3.11/site-packages/numpy/core/arrayprint.py", line 799 in recurser
  File "/home/simon/.pyenv/versions/3.11.0/lib/python3.11/site-packages/numpy/core/arrayprint.py", line 845 in recurser
  File "/home/simon/.pyenv/versions/3.11.0/lib/python3.11/site-packages/numpy/core/arrayprint.py", line 889 in _formatArray
  File "/home/simon/.pyenv/versions/3.11.0/lib/python3.11/site-packages/numpy/core/arrayprint.py", line 546 in _array2string
  File "/home/simon/.pyenv/versions/3.11.0/lib/python3.11/site-packages/numpy/core/arrayprint.py", line 513 in wrapper
  File "/home/simon/.pyenv/versions/3.11.0/lib/python3.11/site-packages/numpy/core/arrayprint.py", line 736 in array2string
  File "/home/simon/.pyenv/versions/3.11.0/lib/python3.11/site-packages/numpy/core/arrayprint.py", line 1484 in _array_repr_implementation
  File "/home/simon/dev/astropy/astropy/test.py", line 11 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, erfa.ufunc, astropy.table._column_mixins, astropy.table._np_utils, yaml._yaml, astropy.io.ascii.cparser, astropy.utils.xml._iterparser, astropy.io.fits._utils, astropy.io.fits._tiled_compression._compression, astropy.time._parse_times, astropy.io.votable.tablewriter, h5py._errors, h5py.defs, h5py._objects, h5py.h5, h5py.h5r, h5py.utils, h5py.h5s, h5py.h5ac, h5py.h5p, h5py.h5t, h5py._conv, h5py.h5z, h5py._proxy, h5py.h5a, h5py.h5d, h5py.h5ds, h5py.h5g, h5py.h5i, h5py.h5f, h5py.h5fd, h5py.h5pl, h5py.h5o, h5py.h5l, h5py._selector (total: 47)
[1]    262237 segmentation fault (core dumped)  python -X faulthandler test.py
```

**Comment by saimn** [comment]
Ok, since the beginning I was wondering how it's possible to dump objects. It seems to work:
```
❯ ipython 

In [1]: import numpy as np
   ...: from astropy.io.misc import yaml

In [2]: a = np.array(['g', 'r', 'i'], dtype=object)

In [3]: yaml.dump(a)
Out[3]: '!numpy.ndarray\nbuffer: !!binary |\n  OERnRXg3MVZBQUFBaGdESHZWVUFBT0NKQWNlOVZRQUE=\ndtype: object\norder: C\nshape: !!python/tuple [3]\n'

In [4]: yaml.load(yaml.dump(a))
Out[4]: array(['g', 'r', 'i'], dtype=object)
```

But this must be because the binary buffer above contain only the memory address of the object been dumped. So once you exit the Python session (or run the test script **in a new shell**) and try to reload it, it crashes, because the memory address no longer exists (or actually points to something else):
```
❯ ipython

In [1]: import numpy as np
   ...: from astropy.io.misc import yaml

In [2]: yaml.load('!numpy.ndarray\nbuffer: !!binary |\n  OERnRXg3MVZBQUFBaGdESHZWVUFBT0NKQWNlOVZRQUE=\ndtype: object\norder: C\nshape: !!python/tuple [3]\n')
Out[2]: [1]    301404 segmentation fault (core dumped)  ipython
```
So the yaml dumper should not allow to dump object arrays.

**Comment by taldcroft** [comment]
@saimn - brilliant!!

So I think the fix is to check for an `object` dtype in these places:
https://github.com/astropy/astropy/blob/d85ce4bb3e8961660857b21618cacb80c267ca91/astropy/io/misc/yaml.py#L112-L113
https://github.com/astropy/astropy/blob/d85ce4bb3e8961660857b21618cacb80c267ca91/astropy/io/misc/yaml.py#L134

For @johannesulf unfortunately this will cause the original code to raise an exception saying (basically) "don't try to serialize an object array".
