### ISSUE TITLE
Move IERS utility function that is HPC-friendly from DESI to astropy

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14757]
### What is the problem this feature will solve?

@weaverba137: In certain environments it is necessary to avoid downloads entirely, and there are configuration items to handle that case. I've written a function that bundles all of the configuration item changes necessary to deactivate downloads and use a one-time downloaded file that can be bundled into your own package, whenever you need it, independent of the one bundled with Astropy. I suggest this can be upstreamed so that more groups can use it.

### Describe the desired outcome

Re-implement https://github.com/desihub/desiutil/blob/main/py/desiutil/iers.py here in `astropy`.

### Additional context

This came out of Astropy Coordination Meeting 2023. See https://github.com/astropy/astropy/issues/14756#issuecomment-1535350498 for more info.

**Comment by weaverba137** [comment]
Thank you for setting that up. I seem to recall that @eteq wanted to discuss this further, so please comment!

**Comment by weaverba137** [comment]
I believe #14819 makes this issue moot. Please close, unless there's a remaining aspect I'm missing.

**Comment by pllim** [comment]
Thank you for the clarification! Will close.
