### ISSUE TITLE
TST: Python 3.12 support 

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14783]
Python 3.12 alpha is out. When the beta comes out, we should at least run an exploratory job with it to make sure we are compatible with the new version of Python.

Since we now use OpenAstronomy template, @ConorMacBride , can the template call Python 3.12 yet?

~If I forget, remind me to change the Python 3.12 label color to be the same as the other Python ones later. Hard to do on phone.~

**Comment by ConorMacBride** [comment]
Yeah, you should be able to specify 3.12-dev in the option: https://github.com/OpenAstronomy/github-actions-workflows#default_python
