### ISSUE TITLE
TST: asdf 3.0.0.dev cannot represent Rotation2D (v5.0.x, v5.2.x, v5.3.x)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14795]
This only happens in v5.2.x and v5.3.x backport branches. I do not see this in `main` (v6.0.dev) but given that we have not even released v5.3 yet, it is concerning. Also see https://github.com/asdf-format/asdf/pull/1464#issuecomment-1539240111

```
_____________________________ [doctest] models.rst _____________________________
943 Serializing a model to disk is possible by assigning the object to ``AsdfFile.tree``:
944 
945 .. doctest-requires:: asdf
946 
947     >>> from asdf import AsdfFile
948     >>> from astropy.modeling import models
949     >>> rotation = models.Rotation2D(angle=23.7)
950     >>> f = AsdfFile()
951     >>> f.tree['model'] = rotation
952     >>> f.write_to('rotation.asdf')
UNEXPECTED EXCEPTION: RepresenterError('cannot represent an object', <Rotation2D(angle=23.7)>)
```

```[tasklist]
- [ ] https://github.com/astropy/astropy/pull/14798
- [ ] https://github.com/astropy/astropy/pull/14801
- [ ] https://github.com/astropy/astropy/pull/14800
- [ ] https://github.com/astropy/astropy/pull/14797
```

**Comment by pllim** [comment]
In v5.0.x (LTS), there is one additional failure: https://github.com/astropy/astropy/actions/runs/4907858228/jobs/8790570838

```
_______________________ test_equivalencies_asdf[with_H0] _______________________

tmpdir = local('/tmp/pytest-of-runner/pytest-0/test_equivalencies_asdf_with_H0')
equiv = <function with_H0 at 0x7f8a37f78680>
recwarn = WarningsRecorder(record=True)

    @pytest.mark.skipif(not HAS_ASDF, reason="requires ASDF")
    @pytest.mark.parametrize("equiv", [cu.with_H0])
    def test_equivalencies_asdf(tmpdir, equiv, recwarn):
        from asdf.tests import helpers
    
        tree = {"equiv": equiv()}
>       helpers.assert_roundtrip_tree(tree, tmpdir)

astropy/cosmology/tests/test_units.py:401: 
...
E       yaml.representer.RepresenterError: ('cannot represent an object', [(Unit("1.47798 littleh"), None)])
```

**Comment by braingram** [comment]
> In v5.0.x (LTS), there is one additional failure: https://github.com/astropy/astropy/actions/runs/4907858228/jobs/8790570838
> 
> ```
> _______________________ test_equivalencies_asdf[with_H0] _______________________
> 
> tmpdir = local('/tmp/pytest-of-runner/pytest-0/test_equivalencies_asdf_with_H0')
> equiv = <function with_H0 at 0x7f8a37f78680>
> recwarn = WarningsRecorder(record=True)
> 
>     @pytest.mark.skipif(not HAS_ASDF, reason="requires ASDF")
>     @pytest.mark.parametrize("equiv", [cu.with_H0])
>     def test_equivalencies_asdf(tmpdir, equiv, recwarn):
>         from asdf.tests import helpers
>     
>         tree = {"equiv": equiv()}
> >       helpers.assert_roundtrip_tree(tree, tmpdir)
> 
> astropy/cosmology/tests/test_units.py:401: 
> ...
> E       yaml.representer.RepresenterError: ('cannot represent an object', [(Unit("1.47798 littleh"), None)])
> ```

The `test_equivalencies_asdf` failure should be fixed by backporting https://github.com/astropy/astropy/pull/13904 to 5.0

The other failure appears to be an oversight in https://github.com/astropy/astropy/pull/14516 which did not also skip the modeling doctest. Does the `doctest-requires` directive allow specifying a version?

**Comment by pllim** [comment]
Have to pin it for the whole RST file for now, like this:

https://github.com/astropy/astropy/blob/eec06978bcf37dba7e998f198003a3b6cbfcfb94/setup.cfg#L158

Are you saying that I should do it like this?

* https://github.com/astropy/astropy/pull/14796

**Comment by braingram** [comment]
> Have to pin it for the whole RST file for now, like this (but not sure how that works for optional dep):
> 
> https://github.com/astropy/astropy/blob/eec06978bcf37dba7e998f198003a3b6cbfcfb94/setup.cfg#L158
> 
> Are you saying that I should not do it like this?
> 
>     * [MNT: Pin asdf<3 in LTS #14796](https://github.com/astropy/astropy/pull/14796)

I am concerned that pinning asdf will cause issues as aside from a few test failures it is compatible. How does the following sound?

1. revert the changes in asdf: https://github.com/asdf-format/asdf/pull/1544
2. backport https://github.com/astropy/astropy/pull/13904 to v5.0
3. skip the failing doctests in v5.2 v5.3 (as is already done for the io.misc.asdf tests: https://github.com/astropy/astropy/pull/14516)
4. reapply the changes in asdf

**Comment by pllim** [comment]
I don't think (1) and (4) are necessary if we can make (2) and (3) work in a few working days. Are you willing to tackle (3) for all three backport branches separately, @braingram ? I don't think auto-backport bot works when a PR is opened against not `main`.

**Comment by braingram** [comment]
Thanks.

I'd be happy to take on 3.

**Comment by braingram** [comment]
@pllim should the backports be opened with `skip-basebranch-check`?

**Comment by pllim** [comment]
Yes, please!

**Comment by pllim** [comment]
All is well again for now but let's cool it down on the asdf side for the next 6 month, yeah? Thanks!
