### ISSUE TITLE
TST: test_fsspec_http also requires requests and aiohttp

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14790]
It is possible to have `fsspec` installed without `requests` or `aiohttp`. When this happens, running the test suite with `--remote-data` flag will cause the following error. I am not sure how best to solve this problem, as these are dependencies of a dependency that is only trigger for that one test. Ideas welcome.

```
...
>   import aiohttp
E   ModuleNotFoundError: No module named 'aiohttp'

.../fsspec/implementations/http.py:11: ModuleNotFoundError

The above exception was the direct cause of the following exception:

self = <astropy.io.fits.tests.test_fsspec.TestFsspecRemote object at ...>

    @pytest.mark.skipif(not HAS_FSSPEC, reason="requires fsspec")
    def test_fsspec_http(self):
        """Can we use fsspec to open a remote FITS file via http?"""
>       with fits.open(self.http_url, use_fsspec=True) as hdul:

.../astropy/io/fits/tests/test_fsspec.py:93:
...
E               ImportError: HTTPFileSystem requires "requests" and "aiohttp" to be installed

.../fsspec/registry.py:245: ImportError
```

**Comment by saimn** [comment]
We have `fsspec[http]` in our `all` requirements which should require requests and aiohttp.

**Comment by pllim** [comment]
But the RC instruction only specify `[test]` requirements.

**Comment by saimn** [comment]
But then why fsspec is installed ?

**Comment by pllim** [comment]
I don't remember. Might be from another package. My env is not a clean env for astropy only; do we only expect people to run RC testing on clean envs?

**Comment by saimn** [comment]
To avoid problems like this a clean env is safer, otherwise it just need some manual intervention to fix the problem ()install `fsspec[http]` or remove `fsspec`).

**Comment by pllim** [comment]
Should we explicitly specify `fsspec[http]` in the `test` section?

**Comment by saimn** [comment]
No, or we should do the same for all optional dependencies in `all`.
The solution to this is `tox` but that doesn't work with the `pip install` and test from the installed package scheme.

**Comment by pllim** [comment]
Okay, fine, we can close as won't fix. I'll just have to remember this for next RC. Thanks for your inputs!
