### ISSUE TITLE
WCS roundripping change with dev version of numpy (1.25+)

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#14806]
### Description

Running the code snipped below using currently released versions of astropy and numpy round trips the `pc1_2` and `pc2_1` keywords. With the devlopment version of numpy the keywords don't roundtrip however. This started happening with the following commit in numpy https://github.com/numpy/numpy/commit/c43ae85bdd44174c0f2867adc85fe94cbc626873, and is causing us some issues downstream in sunpy.

### Expected behavior

The `pc1_2` and `pc2_1` keywords should roundtrip.

### How to Reproduce

```python
from astropy.wcs import WCS

header = {
    'wcsaxes': 2,
    'crpix1': 50.5,
    'crpix2': 120.5,
    'cdelt1': 3.6,
    'cdelt2': 0.477464829275686,
    'cunit1': 'deg',
    'cunit2': 'deg',
    'ctype1': 'HGLN-CEA',
    'ctype2': 'HGLT-CEA',
    'crval1': 0.0,
    'crval2': 0.0,
    'lonpole': 0.0,
    'latpole': 90.0,
    'mjdref': 0.0,
    'date-obs': '2011-02-15T00:00:00.340',
    'rsun_ref': 696000000.0,
    'naxis': 2,
    'naxis1': 100,
    'naxis2': 240,
    'pc1_1': 0.9999999999999999,
    'pc1_2': -0.0,
    'pc2_1': 0.0,
    'pc2_2': 0.9999999999999999,
}

print('pc1_2' in header)
print('pc1_2' in WCS(header).to_header())
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by pllim** [comment]
There is nothing much we can do over here. All we did is to relax the tolerance for our tests. Maybe you should ask the numpy people.

**Comment by dstansby** [comment]
Hold on, maybe I've got this wrong... I'll close for now and re-open if I can confirm this is an issue.

**Comment by dstansby** [comment]
Yeah, sorry for the noise here, this is not an issue in astropy
