### ISSUE TITLE
Latest Anaconda python incompatible with astropy 5.1 & 5.2 (WCSAxes.__init__() got multiple values for argument 'wcs')

### ISSUE THREAD

**Issue by eilatg** [astropy/astropy#14817]
### Description

I was trying to use wcs on an image following the steps in 
https://docs.astropy.org/en/stable/visualization/wcsaxes/index.html 
with astropy v5.1 and anaconda/python v 3.10 but I got an error:
```
WCSAxes.__init__() got multiple values for argument 'wcs'
```
I tried updating astropy to the latest version (5.2) with 'conda update astropy' but this had catastrophic effects of disappearing ipython and jupyter-notebook as well as other "jupyter-" executables from my anaconda3/bin/ directory (I dont understand how this is possible, but I confirmed it twice now). numpy also got corrupted, requiring me to completely uninstall anaconda and re-install it (which revived the astropy 5.1 version, but the wcs issue persists). 

My older computer has python 3.7 and astropy 4.3 and the code works just fine (so I will not be updating on that machine for now) so the issue seems to be compatibility between the two. 

### Expected behavior

The code outlined in https://docs.astropy.org/en/stable/visualization/wcsaxes/index.html  should work but instead the command
```python
plt.subplot(projection=wcs)
```
results in these errors:
```
In [3]: plt.subplot(projection=wcs)
   ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 plt.subplot(projection=wcs)

File ~/anaconda3/lib/python3.10/site-packages/matplotlib/pyplot.py:1311, in subplot(*args, **kwargs)
   1308             break
   1309 else:
   1310     # we have exhausted the known Axes and none match, make a new one!
-> 1311     ax = fig.add_subplot(*args, **kwargs)
   1313 fig.sca(ax)
   1315 axes_to_delete = [other for other in fig.axes
   1316                   if other != ax and ax.bbox.fully_overlaps(other.bbox)]

File ~/anaconda3/lib/python3.10/site-packages/matplotlib/figure.py:743, in FigureBase.add_subplot(self, *args, **kwargs)
    740         args = tuple(map(int, str(args[0])))
    741     projection_class, pkw = self._process_projection_requirements(
    742         *args, **kwargs)
--> 743     ax = projection_class(self, *args, **pkw)
    744     key = (projection_class, pkw)
    745 return self._add_axes_internal(ax, key)

TypeError: WCSAxes.__init__() got multiple values for argument 'wcs'
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by pllim** [comment]
Hello! For completeness, what is your matplotlib version?

Personally, I discourage people from using full Anaconda install. It gets package updates very slowly and comes bloated with a bunch of stuff you don't need that might also prevent package upgrades.

Please try the following (feel free to replace the Python version as long as it is 3.9+) and use whatever env name you like:

```
conda create -n mycleanenv python=3.11 
conda activate mycleanenv
pip install astropy --pre
```

You should get Python 3.11, the latest stable numpy, astropy 5.3rc1, and some other stuff. It does not come with scipy etc, so if you need that too, do a `pip install` whatever you need.

Then, please see if your example would work.

Thank you for your patience!

**Comment by Cadair** [comment]
This appears to be the same / similar to: https://github.com/sunpy/sunpy/issues/6946 which is that matplotlib 3.7.0 and astropy 5.1.0 are incompatible with one another, you need astropy 5.1.1 which has the bug fix for matplotlib 3.7.0 in it.

@eilatg What I would like to clarify is that with a completely clean anaconda installation you are getting version 5.1.0 of astropy and 3.7.0 of matplotlib and run into this error, without running any other install commands?

If that's the case then it's anaconda itself which is shipping an incompatible set of packages (not entirely its fault as there's no metadata to tell them it's broken).

Given all of that, I would think the fix which is likely to be the least disruptive and might actually work is after installing anaconda run `conda install astropy==5.1.1`, that should fix the bug without doing any other major version bumps which might cause the anaconda house of cards to come tumbling down.

---

P.S. like @pllim I also recommend that people don't use full-blown anaconda, install conda with miniconda or miniforge and then make conda envs.

**Comment by eilatg** [comment]
Thanks, @pllim -- this test worked in the mycleanenv. I would like to move it to my main environment (base?). What is it about this that made it work? is it just the pip install astropy --pre? 

The suggestion by @Cadair seemed to fail:

> Collecting package metadata (current_repodata.json): done
>   Solving environment: failed with initial frozen solve. Retrying with flexible solve.
>   Collecting package metadata (repodata.json): done
>   Solving environment: failed with initial frozen solve. Retrying with flexible solve.
>   
>   PackagesNotFoundError: The following packages are not available from current channels:
>   
>     - astropy==5.1.1
>   
>   Current channels:
>   
>     - https://repo.anaconda.com/pkgs/main/osx-64
>     - https://repo.anaconda.com/pkgs/main/noarch
>     - https://repo.anaconda.com/pkgs/r/osx-64
>     - https://repo.anaconda.com/pkgs/r/noarch
>   
>   To search for alternate channels that may provide the conda package you're
>   looking for, navigate to
>   
>       https://anaconda.org
>   
>   and use the search bar at the top of the page.
>

**Comment by eilatg** [comment]
actually, sadly, trying @Cadair's suggestion broke anaconda again. it really hates the interaction between the two. So I am not sure how to proceed.

**Comment by pllim** [comment]
Delete that env, create a new one and try again what worked for you.

> I would like to move it to my main environment (base?)

I wouldn't recommend touching base at all but it is your machine...

What I usually do is I only use Miniconda and I only use base to update conda. I do not install anything extra into base. On my development work, I create a separate env for it. When that env gets broken, I delete it and create a new env. If you mess up the base, it is very hard to recover without having to reinstall conda itself.

**Comment by eilatg** [comment]
OK so Miniconda should serve my typical astrophysicist needs? Shoudl i delete everything and start from scratch again?

I don't really understand environments well enough to know what is even 'base' it just sometimes shows up when I deactivate other environments (i have never intentionally activated it) and so I thought it was some kind of 'home' environment or something like that. Switching to python at this point in my career has been like navigating a maze in the darkness so I apologize for my vague and unsophisticated questions!

**Comment by pllim** [comment]
> typical astrophysicist needs

I do not know what your "typical" is. If you use pipelines from a specific telescope, they should have provided you some instructions on how to create a compatible env. If you are doing some homegrown analysis, then you need to collect your requirements and go from there.

Miniconda gives you just conda. You create env, and then you install what you need.

Anaconda gives you what it thinks you want (which mostly you actually don't need). It has outdated versions and is fragile when you try to update or install more stuff into it.

Ultimately, you decide. Good luck!

**Comment by Cadair** [comment]
There is a legitimate issue with anaconda / defaults that we need to reach out to someone at anaconda about, and that is that the lastest version of astropy available in defaults is 5.1.0 which is incompatible with matplotlib 3.7.0, so **someone using defaults is completely broken**.

---

@eilatg I am sorry that your early forays into Python have run into a pretty awkward bug! Let me try and explain why I recommend what I do.

First, let's clarify some things up front: 

* `conda` is a package manager, and `anaconda` is a scientific python distribution which uses the `conda` package manager, but comes with a large set of packages installed to get people started.
* Conda "environments" or Python's "virtual environments" allow you to have many different isolated sets of packages installed alongside each other an allow you to decide which set you need for a specific task. Back in my research days, I would have an environment setup for each project I was working on, which allowed me to update or install a package for one project without risking breaking a different one.

The other thing to understand is that there are two primary sources for packages that can be installed with conda, these sources are called "channels", there's "defaults" which is maintained by Anaconda Inc. and there's conda-forge which is a community project (the anaconda distribution uses "defaults"). There's more choice and, often, more upto date packages available on conda-forge.

So all that being said, what I recommend is the following:

* **Use [miniforge](https://github.com/conda-forge/miniforge/) to install Python & conda.**: Miniforge, is like a super minimal version of `anaconda` which only installs Python itself and the `conda` command, this gives you all the building blocks you need to install packages yourself. The alternative here is [miniconda](https://docs.conda.io/en/latest/miniconda.html), which is basically the same, with one key difference: *miniforge uses conda-forge and not defaults*.
* **Use environments for everything**: When you have installed miniforge (or miniconda) the "base" environment will have basically nothing installed other than the `python` command and the `conda` command. Rather than installing anything else in the base env, I highly recommend starting a new env and then installing whatever you need in that environment. So if you have used miniforge, the following two commands:
```
$ conda create --name astropy
$ conda install astropy
```
will make a new environment and install the latest version of astropy into it (5.2.2), which is newer than the one available in anaconda/defaults.

Hope that helps clarify what's going on!

**Comment by pllim** [comment]
Never hurts to be explicit if you don't know which channel a package comes from though:

```
conda install astropy -c conda-forge
```

But why not just forget about conda because you can also pip install astropy into conda env... (add a `--pre` flag if you want the pre-release that is currently 5.3rc1)

```
pip install astropy -U
```

**Comment by eilatg** [comment]
I wish I understood enough to be able to answer this question. What I mean
by this is that i dont really have a clear picture of what is the benefit
of having everything duplicated into envs and what exactly "forget about
conda" means.

This whole python world has made me feel utterly stupid for the past
decade. I was a very competent unix/linux admin who enjoyed the command
line and scripting, IRAF, IDL, C, Fortran. The python world just makes no
sense to me... Much as I try, there are so many layers of obscuration that
make it hard to know what is actually happening and things break very
easily.

I will try to follow Stuart's suggestions and see how it goes.

**Comment by cmarmo** [comment]
> I was a very competent unix/linux admin who enjoyed the command line and scripting, IRAF, IDL, C, Fortran

Hi @eilatg, if you are comfortable with linux and you don't plan to work on the source code, may I suggest you to use the packages from the distributions? Linux distributions are able to manage the dependencies in a reasonable way, enough to use the most important features of the library... then you'll have the time (and I'm sure you'll be able to) to familiarize with different environments.
On debian you might want to check the all-in-one [debian-astro suite](https://blends.debian.org/astro/), on Fedora the [Fedora Astronomy spin](https://labs.fedoraproject.org/astronomy/).

**Comment by eilatg** [comment]
well, linux on Mac these days... I don't have a linux machine that is
easily accessible for my day to day research. I guess I was just trying to
explain that I am not computer-illiterate or unaware of how the command
line works. sorry for the confusion.

**Comment by cmarmo** [comment]
> well, linux on Mac these days... I don't have a linux machine that is easily accessible for my day to day research.

... I guess I'm older than you then... ;) so you can definitely do it! :)

**Comment by pllim** [comment]
@eilatg , sorry for being so confusing. The good and also bad thing about Python is that there are many ways to do the same thing. Feel free to follow @Cadair suggestions if they work for you.

**Comment by eilatg** [comment]
Hi Stuart,

Thanks for all of this -- I was pulled away for something else but came
back to this today. Slowly re-building things in what will hopefully be a
more sensible structure. I'll report back if I run into any more problems.
Right now, i realize that installing miniforge3 does not include ipython or
jupyter notebooks so i need to get those first before i can test anything.

**Comment by pllim** [comment]
5.1 and 5.2 are both no longer in active development. Please install 5.3.x from conda-forge. See:

* https://github.com/astropy/astropy/issues/15122
