### ISSUE TITLE
Translate distance to redshift

### ISSUE THREAD

**Issue by Firestar-Reimu** [astropy/astropy#14823]
### What is the problem this feature will solve?

I want to get redshift from comoving distance because there is only distance in simulations, but astropy only have `distance >> redshift` functions

**Comment by pllim** [comment]
@nstarman , should `z` in that example be made more reasonable?

**Comment by nstarman** [comment]
It could be... `z`=1100 is roughly the redshift of recombination, so perhaps instead the example should be beefed up to explain how to round trip the value, using the `z_at_value` kwargs.

**Comment by Firestar-Reimu** [comment]
@pllim But I cannot output a number, instead:

`<Quantity 0.032601912 redshift>`

**Comment by pllim** [comment]
Yes, you can use `to_value` or if you already have the Quantity object, you can access its `.value` property to get just the number.

Is your question resolved, @Firestar-Reimu ?

**Comment by pllim** [comment]
@Firestar-Reimu , would https://github.com/astropy/astropy/pull/14839 help you here?
