### ISSUE TITLE
Projection models do not pickle

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#14849]
### Description

Some of the astropy models, specifically related to projection, cannot be pickled. This is causing issues when trying to use them with multiprocessing/dask for example. I ran across this while trying to parallelize something that uses a GWCS which in turn uses the projection models.

### Expected behavior

Projection models should be picklable

### How to Reproduce

```python
In [2]: from astropy.modeling.models import Pix2Sky_TAN

In [3]: p = Pix2Sky_TAN()

In [4]: from pickle import dumps

In [5]: dumps(p)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 dumps(p)

TypeError: cannot pickle 'astropy.wcs.Prjprm' object
```

### Versions

macOS-13.2.1-arm64-arm-64bit
Python 3.11.2 (main, Mar 23 2023, 23:28:33) [Clang 14.0.0 (clang-1400.0.29.202)]
astropy 6.0.dev172+g04948b016b.d20230519
Numpy 1.24.2
pyerfa 2.0.0.1
Scipy 1.10.0
Matplotlib 3.6.3

**Comment by astrofrog** [comment]
@nden @mcara @perrygreenfield @WilliamJamieson - I'm not sure if it would be best to fix this at the projection class level or actually fixing the pickling of ``Prjprm`` objects. I think the latter would be quite complex based on examples of ``__getstate__`` and ``__setstate__`` I've seen around. I've got a prototype implementation working on having the fix inside astropy.modeling: https://github.com/astropy/astropy/pull/14850 - but running into some issues, see there.

**Comment by pllim** [comment]
@WilliamJamieson , can this be closed now based on your comment at https://github.com/astropy/astropy/pull/14850#issuecomment-1688332347 ?
