### ISSUE TITLE
Reading gzipped FITS file is slow

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#14855]
### Description

Reading a gzipped file can be very slow compared to ungzipping the file in memory before reading it.
https://github.com/saimn/misc-astro/blob/master/astropy/FITS%20compression.ipynb
This is because the code uses the file handler from `gzip.open` to read (and uncompress on the fly) small blocks of bytes, which is much slower than decompressing the whole file at once.
The current behavior is useful to limit the memory usage, but sometimes unpractical when reading big files, where it can be much much slower.
@astrofrog - Should we consider adding a new parameter to decompress the whole file in memory ? This is what I use in my code currently to circumvent this (passing `io.BytesIO(gzip.open(filename).read())` to `fits.open`, see notebook). 

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by astrofrog** [comment]
Yes I think adding a parameter for this would make sense!

**Comment by enthusiastic2003** [comment]
@saimn , just to be clear, where do you want to put the extra parameter?

**Comment by saimn** [comment]
The parameter should be added to `fitsopen` (https://github.com/astropy/astropy/blob/main/astropy/io/fits/hdu/hdulist.py#L46) and propagated to `_try_read_compressed` (https://github.com/astropy/astropy/blob/main/astropy/io/fits/file.py#L500) where the file can be decompressed in memory.
It should maybe also apply to `.zip` and `.bz2` files, not sure (some tests should be made to check).
And we need to find a good name :)

**Comment by saimn** [comment]
Same issue with `bz2` (see updated notebook above).
