### ISSUE TITLE
Drop oldest-supported-numpy from build requirements when numpy 1.25 is released

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14915]
@saimn said, "once 1.25 is out we can put it as minimum version in our build requirements," and drop `oldest-supported-numpy`. `@seberg` has also confirmed separately that this should work. cc @astropy/astropy-project-release-team 

https://numpy.org/devdocs/release/1.25.0-notes.html#by-default-the-exported-numpy-c-api-is-now-compatible-with-numpy-1-19 (https://github.com/numpy/numpy/pull/23528 and https://github.com/numpy/numpy/pull/23872)

https://numpy.org/devdocs/dev/depending_on_numpy.html#for-downstream-package-authors

https://github.com/astropy/astropy/blob/0e4ab57499b49f18f60b87baf5a74d964d6decde/pyproject.toml#L5

**Comment by stefanv** [comment]
https://numpy.org/devdocs/dev/depending_on_numpy.html#build-time-dependency

**Comment by pllim** [comment]
Do we want to do `#define NPY_TARGET_VERSION NPY_1_21_API_VERSION` to match this?

https://github.com/astropy/astropy/blob/23971c55db76a9be073a38a4311ae6e81576d2c9/setup.cfg#L31

**Comment by pllim** [comment]
On the conda-forge side, @mwcraig will have to decipher https://conda-forge.org/docs/maintainer/knowledge_base.html#building-against-numpy when the time comes.

**Comment by pllim** [comment]
Does #14949 look about right or did I totally misunderstood?
