### ISSUE TITLE
Remove or change the documentation for astropy.io.misc.asdf

### ISSUE THREAD

**Issue by nden** [astropy/astropy#14912]
### Description

`astropy.io.misc.asdf` was moved to a separate package, `asdf-astropy`. The documentation in astropy needs to be updated or removed.

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by pllim** [comment]
@nden , can you please be more specific? I thought I removed it in #14668 ? Did I miss something here?

**Comment by nden** [comment]
Oops, yes, you are right. I was looking at a 5.4.dev.... version.
