### ISSUE TITLE
Unexpected Quantity behavior when unit=None

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#14935]
### Description

```python
>>> from astropy.units import Quantity
>>> a = Quantity([1, 2, 3], unit=None)
>>> a.unit is None
False
>>> a.unit

>>> type(a.unit)
astropy.units.core.CompositeUnit
```

In this simple case, shouldn't `a.unit = None`?

CC: @mhvk

**Comment by mhvk** [comment]
This happens because `None` is the default, which gets interpreted as wanting `u.dimensionless_unscaled` if the input has no unit.
```
u.Quantity(1, None).unit is u.dimensionless_unscaled
# True

u.Quantity(1*u.m, None).unit is u.m
# True

```

What would be the use case of having no unit?
