### ISSUE TITLE
Replace flynt with ruff?

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#14934]
### What is the problem this feature will solve?

can we do it?
https://beta.ruff.rs/docs/rules/#flynt-fly

### Additional context

Ping @WilliamJamieson

**Comment by nstarman** [comment]
@WilliamJamieson, does Ruff now cover our Flynt usage?

**Comment by WilliamJamieson** [comment]
I have not been following Ruff very closely recently. Before, it did not cover fixing the `printf` formatting, and ignoring the cases where the `printf` formatting was used in logging statements. Flynt is only being used in the weekly cron and it runs extremely fast, so I don't think it is hurting anything. 

If you think it covers the flynt usage then you can replace/drop it.
