### ISSUE TITLE
Interoperability of Astropy and non-Astropy objects

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#1495]
As I was going through old discussions I came across this:

https://groups.google.com/forum/#!searchin/astropy-dev/interoperability/astropy-dev/19IIxn-_zaQ/AMaqzN3U7TQJ

It seemed there was consensus that we should define an API for interoperability of non-Astropy objects with Astropy (e.g. `__astropy_table__`) similarly to what Numpy (e.g. `__array__`) and Matplotlib (`__as_mpl_axes__`). This issue is just to make sure we don't forget about this, and also to focus any more detailed discussion.

**Comment by pllim** [comment]
`astropy.units` works pretty well with `numpy` nowadays and I haven't seen any comment since 2013. So, the rest is probably never gonna happen.
