### ISSUE TITLE
Consistent Data Types with Quantities

### ISSUE THREAD

**Issue by Alrobbertz** [astropy/astropy#14963]
### What is the problem this feature will solve?

I am seeing inconsistencies in the data types of Quantity objects depending on how they are created. I would like this to be standardized so that I am always sure of the data types of the values in the Quantity. 

### Describe the desired outcome

```python
import numpy as np
import astropy.units as u
(np.arange(5, dtype=np.uint16) * u.Gauss).dtype
```
gives a data type:
```
dtype('float64')
```
while...
```python
u.Quantity(np.arange(5), dtype=np.uint16).dtype
```
gives a data type:
```
dtype('uint16')
```

I would like both of these to be consistent in giving the data type `dtype('uint16')`

**Comment by mhvk** [comment]
This is a recurring issue, where I think there is a clash that seems to miss that Quantities are by their nature not integer - they are supposed to be the same under unit changes, but this is broken by integers (e.g., converting `10 m` to `km`).

In hindsight, I think it would have been best not to support integers at all, but the compromise we have made is that one has to be explicit if one does not want float. If one wants to convert a numpy array to a Quantity and keep its `dtype`, one can do `Quantity(array, dtype=None)` (the default is `dtype=np.inexact`, which will convert to float (keeping complex)).
