### ISSUE TITLE
Error in distance calculations for w0wz Cosmologies

### ISSUE THREAD

**Issue by RyanCamo** [astropy/astropy#14975]
### Description

I believe that the equation used to calculate the de_density_scale in `w0wzcdm.py `is incorrect. 

Line 205 has `return zp1 ** (3.0 * (1.0 + self._w0 - self._wz)) * exp(-3.0 * self._wz * z)`

### Expected behavior

After manually calculating the integral/checking wolfram, I don't think it should be a negative in the exponent and should read: `return zp1 ** (3.0 * (1.0 + self._w0 - self._wz)) * exp(3.0 * self._wz * z)`

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by pllim** [comment]
@nstarman ?

**Comment by nstarman** [comment]
@RyanCamo, thanks for opening the issue! Indeed, that would be an impactful error. Can you please share your Wolfram notebook?

**Comment by RyanCamo** [comment]
Yeah no worries. https://www.wolframcloud.com/obj/05284bb5-e50d-4499-ab2c-709e23e49007

**Comment by nstarman** [comment]
I get the same thing.

<img width="438" alt="Screenshot 2023-06-23 at 22 49 12" src="https://github.com/astropy/astropy/assets/8949649/c1b3cdc3-051a-47d9-8a2a-7fd71cdafb10">

**Comment by nstarman** [comment]
Git says this was introduced in #322. @aconley, this was your PR. I know this was 11 years ago, but perhaps you could take a look.

**Comment by aconley** [comment]
Ryan is correct, it should be a +3.

This probably went detected for so long because nobody would ever use the w0/wz formulation, it's horribly unstable.  w0/wa is almost always a better idea -- w0/wz was just included for completeness.

**Comment by aconley** [comment]
If you want a citation for the +3, it's on the first page of Linder et al. 2003.

**Comment by nstarman** [comment]
Thank you @RyanCamo for noticing and opening the Issue and for @aconley for confirming the mistake!

**Comment by pllim** [comment]
We might do a 5.3.1 soon-ish for a different bug fix, so maybe you don't have to wait so long to get the patch in a release. But if you are not sure about it, feel free to ping us again. Thanks, all!
