### ISSUE TITLE
V5.3 breaking change reading compressed variable word array

### ISSUE THREAD

**Issue by andrew-saydjari** [astropy/astropy#14985]
### Description

In switching from 5.2.2 to 5.3, the FITS reader stoped being able to read the data mask file format from DECam because it throws the following error on the TFORM1 keyword.

`'Invalid TFORM1: PI(33)'`

This breaking change to the FITS reader was not documented as far as I could tell. I did see that there were improvements to the compressed data reader, but this break on version upgrades did not seem to be expected.

### Expected behavior

I expected this very common FITS file used by many in the community to still be read.

### How to Reproduce

Download a DECam ood fits file (for example [here](https://github.com/andrew-saydjari/CloudCovErr.jl/blob/main/test/data/decaps/c4d_170119_085651_ood_r_v1.fits.fz)), try to read in the data.

### Versions

This was run in a CI workflow, but here is the [link](https://github.com/andrew-saydjari/CloudCovErr.jl/actions/runs/5086036764/jobs/9140114475) to the failing run.

**Comment by saimn** [comment]
cc @astrofrog @Cadair, failure happen in the new tile compression code:
```
File ~/dev/astropy/astropy/astropy/io/fits/_tiled_compression/tiled_compression.py:211, in _check_compressed_header(header)
    209             break
    210     else:
--> 211         raise RuntimeError(f"Invalid TFORM1: {header['TFORM1']}")
    213 # Check values
    215 for kw in ["TFIELDS", "PCOUNT"] + [
    216     f"NAXIS{idx + 1}" for idx in range(header["NAXIS"])
    217 ]:

RuntimeError: Invalid TFORM1: PI(54)
```

https://github.com/astropy/astropy/blob/87482ce5d4b02ae24056f5cdd33f61a954f44f94/astropy/io/fits/_tiled_compression/tiled_compression.py#L206-L211

I *think* in VLA column the `1` prefix is optional ?

**Comment by Cadair** [comment]
The FITS 4 spec does indeed say the `r` field is optional if it takes the default value of 1:

![clipboard](https://github.com/astropy/astropy/assets/1391051/9105c1f3-0202-45ec-828d-3ea102171d64)

So this is indeed a bug.

**Comment by astrofrog** [comment]
Fix in https://github.com/astropy/astropy/pull/15001

I think I was misled by this other text in the FITS standard:

<img width="574" alt="Screenshot 2023-06-30 at 07 19 55" src="https://github.com/astropy/astropy/assets/314716/3b0b8215-5b40-4ca2-9b3a-ed6208114ff6">
