### ISSUE TITLE
wcsaxes tests fail with "The collections attribute was deprecated in Matplotlib 3.8"

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15003]
devdeps job is failing for 5 tests with this message:

```
Matplotlib: 3.8.0.dev1437+g3b3fc57f65

matplotlib._api.deprecation.MatplotlibDeprecationWarning:
The collections attribute was deprecated in Matplotlib 3.8 and
will be removed two minor releases later.
```

* astropy/visualization/wcsaxes/tests/test_misc.py::test_no_numpy_warnings[contours]
* astropy/visualization/wcsaxes/tests/test_misc.py::test_grid_type_contours_transform
* astropy/visualization/wcsaxes/tests/test_misc.py::test_contour_return
* astropy/visualization/wcsaxes/tests/test_misc.py::test_contour_empty
* astropy/visualization/wcsaxes/tests/test_misc.py::test_multiple_draws_grid_contours

https://github.com/astropy/astropy/blob/edf7493ec141a9072b5ce3e33071dff66e58bf49/astropy/visualization/wcsaxes/coordinate_helpers.py#L621

https://github.com/astropy/astropy/blob/edf7493ec141a9072b5ce3e33071dff66e58bf49/astropy/visualization/wcsaxes/coordinate_helpers.py#L1126

Any ideas how to fix? @astrofrog @Cadair @dstansby @ayshih 🙏 

Probably from https://github.com/matplotlib/matplotlib/pull/25247

**Comment by dstansby** [comment]
Is there a longer stack trace for the error than posted above? (where perhaps it's easier to see where the warning is coming from)

**Comment by dstansby** [comment]
If it's a `ContourSet` emitting these, https://github.com/matplotlib/matplotlib/pull/25247/files#diff-918125f8b0a3d8085b15096d948f8e005d5dc938ea54501ba3c1f7a36ad74f7f is the MPL changelog entry that has info on how to change code to adapt to this.

**Comment by pllim** [comment]
That change log isn't very helpful for me who is unfamiliar with the code base, but I think I found the PR so looking at their diff, I am trying out https://github.com/astropy/astropy/pull/15004 🤞
