### ISSUE TITLE
TST: test_contour_overlay fails in CircleCI mpldev job

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15029]
Example log: https://app.circleci.com/pipelines/github/astropy/astropy/16397/workflows/59f6588b-cd8c-40b0-b611-00b97736893b/jobs/112984

I don't understand, the difference image shows no difference but the hash is different. What is going on here, @astrofrog and @Cadair ?

https://output.circle-artifacts.com/output/job/65b009f4-252a-490f-a3da-61cb064aa4e0/artifacts/0/results/fig_comparison.html

**Comment by astrofrog** [comment]
If you donwload and stretch the diff PNG, there are two pixels that have changed. Safe to ignore, so just update the hash in the hash files.
