### ISSUE TITLE
Remove IERS auto-update workflow once v6.0.0 is released

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#15030]
Once v6.0.0 is released, we should remove the IERS auto-update workflow since the files will no longer need to be updated in the v5.0.x and v5.3.x branches (updated in https://github.com/astropy/astropy/pull/15013)

**Comment by pllim** [comment]
Someone must have done it. I cannot find that workflow on `main` anymore.

**Comment by neutrinoceros** [comment]
Looks like *you*'re the someone 😅 [#15568](https://github.com/astropy/astropy/pull/15568)

**Comment by pllim** [comment]
Past Self ™️ comes back to haunt me again! Thanks for digging that up. 😸
