### ISSUE TITLE
Publish workflow has "too many arguments" error

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15040]
@saimn found this error during v5.3.1 release:

```
Run if [ -n "test" ];
  if [ -n "test" ];
  then
    echo "CIBW_TEST_EXTRAS=test" >> $GITHUB_ENV
  fi
  if [ -n "pytest -p no:warnings --astropy-header -m "not hypothesis" -k "not test_data_out_of_range and not test_set_locale and not TestQuantityTyping" --pyargs astropy" ];
  then
    echo "CIBW_TEST_COMMAND=pytest -p no:warnings --astropy-header -m "not hypothesis" -k "not test_data_out_of_range and not test_set_locale and not TestQuantityTyping" --pyargs astropy" >> $GITHUB_ENV
  fi
  cat $GITHUB_ENV
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
line 5: [: too many arguments
```

@dhomeier said https://github.com/OpenAstronomy/github-actions-workflows/pull/127 changed `publish.yml` to use `-n "${{ inputs.test_command }}"` and that probably broke our stuff here.

https://github.com/astropy/astropy/blob/92d551a0fbbd3c0d8ea35d58514287f5e1789b07/.github/workflows/publish.yml#L26

**Comment by dhomeier** [comment]
From the way the inputs/environment variables are used, it would probably generally be safer to put all strings in `publish.yml` in single quotes. May not hurt for the Workflows to note this in their `publish.rst` or other docs.

**Comment by pllim** [comment]
Thanks! I opened https://github.com/OpenAstronomy/github-actions-workflows/pull/143 upstream.
