### ISSUE TITLE
TST: Test imports with python -OO flag

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15052]
Sometimes people run stuff with `python -OO` flag and choke on some `astropy` imports. Examples:

* https://github.com/astropy/astropy/pull/3923
* #10361
* #15028 

I am not sure how best to test this in a meaningful way.

**Comment by alchzh** [comment]
pytest can run just fine with `-OO`, so we should just make sure the test suite succeeds.

A few steps need to be taken here:
- [ ] Replace uses of `assert` outside of test cases with the appropriate explicit error raise or logic. Easy to do with ruff.
- [ ] Make sure all `__doc__` manipulation is done after a check that it's not `None`
- [ ] Add a skipif marker to all test cases that check docstrings / `help()`. This is already done in `astropy/utils/tests/test_parsing.py`

Actually, I already have a branch with these changes and everything passing but I'm stuck on the side of the highway at the moment after the bus engine broke down and can't get my mobile hotspot to work.

How many separate PRs would the maintainers like this to be?

**Comment by pllim** [comment]
> How many separate PRs would the maintainers like this to be?

Hard to tell. If you let me know which branch on your fork these changes are in, I can compare and see.

**Comment by alchzh** [comment]
Just got home and pushed this https://github.com/alchzh/astropy/tree/support-OO
