### ISSUE TITLE
pre-commit run gives PermissionError locally on VS Code + Git Bash + Windows 11

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15061]
We recommend people run pre-commit locally but I find it impossible on a VS Code + Git Bash + Windows 11 combo on my laptop. It throws file permission error when the `black` hook make nitpicky code changes to my changes. What are my options here? Does anyone know how to get rid of the permission error? I even had VS Code run in admin mode but no luck.

I can have the pre-commit.ci bot fix it later from the PR but then I have to remember to pull that change back down and squash it out, which is annoying, and wastes CI cycles.

**Comment by WilliamJamieson** [comment]
Sounds like Python does not have permissions to edit the Python files in your astropy clone. Maybe try the solutions in: https://careerkarma.com/blog/python-permissionerror-errno-13-permission-denied/

**Comment by pllim** [comment]
chmod has no effect on WIndows. I also tried unchecking "read-only" from Windows File Manager but it didn't work either and even magically got rechecked. 🤷‍♀️

**Comment by pllim** [comment]
It is not urgent though. I usually use WSL2. Just annoying once in a while when I am stuck with an all-Windows system.

**Comment by pllim** [comment]
@nabobalis gave me the idea to set executable to run as administrator by default (thanks!!!), so this is what I did to fix this problem:

1. Run `which pre-commit` to see which one my env is calling.
2. Find that `pre-commit.exe` in File Explorer, right click, click Properties, select Compatibility tab, check the "run this program as administrator" box, click Apply.
3. Start VS Code as an administrator. Now `pre-commit run` is able to modify affected file(s).
