### ISSUE TITLE
FITS files use too much disk space (but only in one machine)

### ISSUE THREAD

**Issue by talensgj** [astropy/astropy#15086]
### Description

FITS files manipulated or even just copied by astropy see a large increase in allocated disk space. e.g. a file that has ~40 MB allocated before being opened and written to a new file has ~104 MB allocated after despite the contents being unchanged.

### Expected behavior

No significant change in the allocated disk space.

### How to Reproduce

I have been able to reproduce the error only on the machine where I first detected it. I tried testing in a clean conda environment and tested astropy 5.2.1 which first showed the issue as well as astropy-5.3.1 and 5.0.

On this specific machine the following steps reproduce the issue:
conda create -n fitsdebug python=3.9.7
conda activate fitsdebug
pip install -r requirements.txt
python
from astropy.io import fits
```
with fits.open('1-201342_15-red-phot.fits')
    hdul.writeto('test.fits')
```
The attached image shows the output of ls -lsh, where it can be seen that the allocated disk space of the new file is much larger than that for the original file. Making a copy of 'test.fits' with cp returns the allocated size to the expected value for some reason.

[requirements.txt](https://github.com/astropy/astropy/files/12152380/requirements.txt)
![image](https://github.com/astropy/astropy/assets/23314131/9de00104-8574-45da-9162-4c4ffabcb0c8)

### Versions

On the problematic machine:

>>> import platform; print(platform.platform())
Linux-4.19.0-5-amd64-x86_64-with-glibc2.28
>>> import sys; print("Python", sys.version)
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.2.1
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.21.2
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.3
>>> import scipy; print("Scipy", scipy.__version__)
N/A
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
N/A

On my laptop, where I cannot reproduce the issue:
>>> import platform; print(platform.platform())
Linux-5.15.0-76-generic-x86_64-with-glibc2.31
>>> import sys; print("Python", sys.version)
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:23:11) 
[GCC 9.4.0]
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.2.1
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.21.2
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.3
>>> import scipy; print("Scipy", scipy.__version__)
N/A
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
N/A

**Comment by talensgj** [comment]
Considering my inability to reproduce the bug on other machines I'm not sure it's a problem with astropy per se, but I have run out of ideas. Using a different machine is not an option as this is a dedicated machine for the HATPI telescope project.

**Comment by pllim** [comment]
Can you at least upgrade Python on the "problematic" machine to see if this is a Python bug that has been fixed? I see the latest bugfix in 3.9 series is 3.9.17 (not 3.9.7).

**Comment by talensgj** [comment]
Testing with python 3.9.17 produces the same result.

**Comment by pllim** [comment]
By the way, what is the file system? And what is its block size?

**Comment by talensgj** [comment]
It is an xfs file system with a block size of 4096.

**Comment by talensgj** [comment]
Hello Simon,

I've tried these things and found no change in the results. Regardless, it's not like ls -s is reporting discrepant sizes for all FITS files, just the ones manipulated in some way with io.fits. It's also not a small discrepancy between actual and allocated size (like in the 2nd link). We're not talking one or two blocks here, there's more spuriously allocated size than actual content. 

I agree that the problem may not be within io.fits, but it's almost certainly some interplay between io.fits and the system we use, and I wouldn't know where else to ask?

![image](https://github.com/astropy/astropy/assets/23314131/db630c9e-fe6f-4bc2-9520-7f460813ca8b)

**Comment by ayshih** [comment]
That discrepancy between the allocated size and the actual size (presumably) indicates that the file saved by `io.fits` is highly fragmented, and that's consistent with a `cp` of the file defragmenting the file.  So, while `io.fits` is probably writing the file in such a manner as to be prone to fragmentation, the fact that it's affecting only one machine likely means that the free space on that particular machine is excessively fragmented and ought to be defragmented.  There are ways to diagnose the level of fragmentation of an XFS filesystem.

**Comment by talensgj** [comment]
@ayshih I think you're right. I just managed to replicate the issue on a different machine, but only when writing to an xfs partition, writing to ext4 was fine. I'm wondering if it might also have something to do with Dynamic Speculative Preallocation on xfs systems as discussed here:

https://serverfault.com/questions/406069/why-are-my-xfs-filesystems-suddenly-consuming-more-space-and-full-of-sparse-file

I'll ask the administrator of these machines about the xfs settings and the fragmentation state.

**Comment by pllim** [comment]
Glad you figured it out over at the hardware department. I am closing the issue. Thanks for reporting this so others with the same problem would also benefit from this discussion in the future! 😸
