### ISSUE TITLE
DOC: Cosmology section has repeated sub-sections

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15117]
This is a direct follow-up of #15090 . @nstarman , can you please fix this? Thanks!

![Screenshot 2023-08-02 165456](https://github.com/astropy/astropy/assets/2090236/afd1486d-649e-4017-88cf-cbadf2ea3758)

**Comment by nstarman** [comment]
Looks like RTD now picks up on both toctrees in `docs/cosmology/index.rst`.

**Comment by pllim** [comment]
You might want to consider re-organizing it so both the left and right navbars make sense in the new theme when going through the cosmology sections. Thanks!

**Comment by nstarman** [comment]
Yes. I've been reorganizing the I/O docs, but the main landing page needs a re-org too!
