### ISSUE TITLE
BUG: astropy is outdated on Anaconda defaults channel, DO NOT USE

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15122]
We have no control over this. If they finally fix it, please report back here so we can close this issue.

* https://github.com/ContinuumIO/anaconda-issues/issues/13239

# Workarounds

* Install from `conda-forge`
* Install from `pip`

**Comment by astrofrog** [comment]
Maybe we should update the instructions on the astropy homepage to conda install astropy from conda-forge?

**Comment by pllim** [comment]
Both options are there in https://github.com/astropy/astropy/blob/main/docs/install.rst#using-conda .

Are you saying that Anaconda will never care and we should just forget about them?

**Comment by astrofrog** [comment]
I mean the instructions on here:

https://www.astropy.org

we could simply change ``conda install astropy`` to ``conda install -c conda-forge astropy``

**Comment by pllim** [comment]
We could. I always forget we duplicate info over there... Do you wanna update it?

**Comment by Cadair** [comment]
I would argue we should remove the defaults option from our docs completely.

**Comment by richardgmcmahon** [comment]
Can I suggest that the astropy installation page includes:

pip install astropy --upgrade

I went around the conda route and then found this issue:

pip install astropy --upgrade

upgraded me from 5.1 to 5.2 and this got around the numpy dtype issue.

**Comment by skupr-anaconda** [comment]
`astropy 5.3.4` is available on the `main` channel:
https://repo.anaconda.com/pkgs/main/linux-64
astropy-5.3.4-py310ha9d4c09_0.tar.bz2
astropy-5.3.4-py311hf4808d0_0.tar.bz2
astropy-5.3.4-py39ha9d4c09_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-ppc64le
astropy-5.3.4-py310h1fb68da_0.tar.bz2
astropy-5.3.4-py311h4bd771a_0.tar.bz2
astropy-5.3.4-py39h1fb68da_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-aarch64
astropy-5.3.4-py310hf6ef57e_0.tar.bz2
astropy-5.3.4-py311h1976a39_0.tar.bz2
astropy-5.3.4-py39hf6ef57e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-s390x
astropy-5.3.4-py310h4a6df81_0.tar.bz2
astropy-5.3.4-py311hdb88474_0.tar.bz2
astropy-5.3.4-py39h4a6df81_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64
astropy-5.3.4-py310h7b7cdfe_0.tar.bz2
astropy-5.3.4-py311hb3a5e46_0.tar.bz2
astropy-5.3.4-py39h7b7cdfe_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64
astropy-5.3.4-py310hbda83bc_0.tar.bz2
astropy-5.3.4-py311hb9f6ed7_0.tar.bz2
astropy-5.3.4-py39hbda83bc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64
astropy-5.3.4-py310h9128911_0.tar.bz2
astropy-5.3.4-py311hd7041d2_0.tar.bz2
astropy-5.3.4-py39h9128911_0.tar.bz2

**Comment by pllim** [comment]
Thank you!
