### ISSUE TITLE
Ignore RUF015 in tests?

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#15145]
Should we implement or ignore RUF015 (https://beta.ruff.rs/docs/rules/unnecessary-iterable-allocation-for-first-element/) in the tests?

This first arose in https://github.com/astropy/astropy/pull/15143#discussion_r1286277586 and https://github.com/astropy/astropy/pull/15143#discussion_r1286323103

**Comment by mhvk** [comment]
The linked comments go both ways: in favour of enabling it is that `list(iterable)[0]` likely can be done better, but against is that the standard "solution" of `next(iter(iterable))` is substantially less readable (and not great).

**Comment by eerovaher** [comment]
In the particular case that https://github.com/astropy/astropy/pull/15143#discussion_r1286277586 referred to we were able to improve the function by rewriting it. `RUF015` has therefore already proven to be useful and I don't see why we'd want to ignore it.

**Comment by mhvk** [comment]
Is there an option to have it flag but not auto-solve? I really don't think we should do its suggested `next(iterable)`.

**Comment by nstarman** [comment]
> Is there an option to have it flag but not auto-solve? I really don't think we should do its suggested `next(iterable)`.

We have it autofix in the main code because `next(iterable)` is much faster than processing the whole list, but it's ignored in the tests, because some find it less readable. I don't think it's possible to have it be flagged in the tests, only ignored.

**Comment by mhvk** [comment]
OK, then I guess it will just be up to reviewers. Anyway, overall I think it is good to have it on. Indeed, if there are no other instances in the test right now, I think we should just have it on generally.

**Comment by nstarman** [comment]
There are a few instances in the tests. I can open a PR where we decide whether to implement the change or add a ``noqa`` on an individual basis.

**Comment by pllim** [comment]
Is this still an issue?

**Comment by nstarman** [comment]
I don't think so. It's fine to ignore it in the tests.
