### ISSUE TITLE
BUG: month old dev wheel is picked up in testing

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#15146]
Something has gone wrong with the wheel packaging as I noticed that a month old version is picked up an installed instead of the latest wheel. This was spotted as it triggered a numpy deprecationwarning for astroquery, but the same issue exists for photutils testing, too.

https://github.com/astropy/astroquery/actions/runs/5790222259/job/15692877993#step:5:68
```
 Collecting astropy
  Downloading https://pypi.anaconda.org/astropy/simple/astropy/6.0.dev484%2Bgea863dacf/astropy-6.0.dev484%2Bgea863dacf-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 12.4 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.22 in /home/runner/work/astroquery/astroquery/.tox/py311-test-alldeps-devdeps-cov/lib/python3.11/site-packages (from astropy) (2.0.0.dev0)
Requirement already satisfied: pyerfa>=2.0 in /home/runner/work/astroquery/astroquery/.tox/py311-test-alldeps-devdeps-cov/lib/python3.11/site-packages (from astropy) (2.0.0.3)
INFO: pip is looking at multiple versions of astropy to determine which version is compatible with other requirements. This could take a while.
  Downloading https://pypi.anaconda.org/astropy/simple/astropy/6.0.dev365%2Bg92d551a0f/astropy-6.0.dev365%2Bg92d551a0f-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 35.0 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=3.13 in /home/runner/work/astroquery/astroquery/.tox/py311-test-alldeps-devdeps-cov/lib/python3.11/site-packages (from astropy) (6.0.1)
Requirement already satisfied: packaging>=19.0 in /home/runner/work/astroquery/astroquery/.tox/py311-test-alldeps-devdeps-cov/lib/python3.11/site-packages (from astropy) (23.1)
Installing collected packages: astropy
  Attempting uninstall: astropy
    Found existing installation: astropy 5.3.1
    Uninstalling astropy-5.3.1:
      Successfully uninstalled astropy-5.3.1
Successfully installed astropy-6.0.dev365+g92d551a0f
```

https://github.com/astropy/photutils/actions/runs/5758959999/job/15612275794#step:6:52

**Comment by pllim** [comment]
I thought we fixed it today. Did you try to reinstall it without cache? See #15133 by @astrofrog

**Comment by bsipocz** [comment]
This is not a duplicate, as the newly built wheel is identified correctly (see the first download line from the copy pasted log), yet it falls back to the month old one a few lines below.

**Comment by bsipocz** [comment]
Same thing with the freshly restarted photutils build. Note that the first build was done before the wheel building fix was merged, but now it also shows that the version falls back on that one, even though the new one is being found already:

https://github.com/astropy/photutils/actions/runs/5758959999/job/15697373281#step:6:288

**Comment by astrofrog** [comment]
I wonder if there is a way to run pip that will give you reasons why the wheel was incompatible?

**Comment by astrofrog** [comment]
I am investigating a little but in the meantime was curious @bsipocz if you know why the dev deps are installed via explicit pip commands rather than when installing the rest of the dependencies, see e.g. the tox config for reproject:

https://github.com/astropy/reproject/blob/main/tox.ini#L17

**Comment by astrofrog** [comment]
I think the issue is that astropy-iers-data is not included in the nightly wheels repo but the pip command:

```
pip install -U --pre -i https://pypi.anaconda.org/astropy/simple astropy
```

assumes that the ONLY package index to use is the anaconda one. One simple fix is to do:

```
    devdeps: python -m pip install astropy-iers-data
    devdeps: python -m pip install -vvv -U --pre -i https://pypi.anaconda.org/astropy/simple astropy
```

but the cleaner 'proper' fix is to define the dev dependencies similar to what we do in reproject via a pip extras URL:

https://github.com/astropy/reproject/blob/d87a9f8cd3b6e33554e9a91db9d29819d9a22ca8/tox.ini#L17

**Comment by pllim** [comment]
@astrofrog , but `astropy-iers-data` is not the only install requirement, why is it giving such a problem but not the other dependencies?

**Comment by astrofrog** [comment]
@pllim because astropy is first installed from a stable version then overwritten by a developer version and the only difference in dependencies is astropy-iers-data.

**Comment by bsipocz** [comment]
I can't recall exactly why it was the direct pip install, just that there were some issues originally with doing the other way. I'll give it a try to change it to be an extra index.
