### ISSUE TITLE
Cannot recognize CAL (plate carree) projection

### ISSUE THREAD

**Issue by Firestar-Reimu** [astropy/astropy#15151]
### Description

I have a 3D spectral cube, its wcs is

```
WCS Keywords

Number of WCS axes: 3
CTYPE : 'RA---CAR'  'DEC--CAR'  'VOPT'  
CRVAL : 119.987  -12.9875  599954.336374  
CRPIX : 1.0  1.0  -2484.0  
PC1_1 PC1_2 PC1_3  : 1.0  0.0  0.0  
PC2_1 PC2_2 PC2_3  : 0.0  1.0  0.0  
PC3_1 PC3_2 PC3_3  : 0.0  0.0  1.0  
CDELT : -0.0250092  0.0250001  -201.283594733  
NAXIS : 2400  400  992
WCS Keywords
```

but if I draw it in matplotlib

```
from astropy.io import fits
import matplotlib.pyplot as plt
from astropy.wcs import WCS

f = './Orion_DR1_Pre_Release_v1.fits'
hdu = fits.open(f)
w = WCS(hdu[0].header,naxis=2)

plt.subplot(projection=w)
plt.imshow(hdu[0].data[0,:,:])
plt.grid()
plt.show()
```

![Screenshot_20230809_004226](https://github.com/astropy/astropy/assets/65082432/50568bef-7a6f-487e-9f22-59ed97fb8ad5)

The grid should be rectangular

### Expected behavior

> CTYPEi – [string; indexed; default: ' ' (i.e. a linear, undefined
axis)]. Type for the Intermediate-coordinate Axis i. Any coordinate type that is not covered by this Standard or an officially recognized FITS convention shall be taken to be linear.
All non-linear coordinate system names must be expressed
in ‘4–3’ form: the first four characters specify the coordinate
type, the fifth character is a hyphen (‘-’), and the remaining three characters specify an algorithm code for computing
the world coordinate value. Coordinate types with names of
fewer than four characters are padded on the right with hyphens, and algorithm codes with fewer than three characters are padded on the right with blanks11. Algorithm codes
should be three characters.

from https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf

### How to Reproduce

https://www.scidb.cn/en/detail?dataSetId=7fe34782f6ee4284aa22fc68ab8ab6cd the fits image

### Versions

Linux-6.4.8-arch1-1-x86_64-with-glibc2.38
Python 3.11.4 (main, Jul  5 2023, 14:15:25) [GCC 11.2.0]
astropy 5.3.1
Numpy 1.25.0
pyerfa 2.0.0
Scipy 1.10.1
Matplotlib 3.7.1

**Comment by ayshih** [comment]
The "problem" is that your reference coordinate is not at zero declination, which is why your CAR projection is not aligned with standard RA/dec.  The "equator" in your defined projection will go through -13 deg declination at 120 deg RA and through +13 deg declination at 300 deg RA.  That's why the RA/dec grid lines are curved.

You'll need to confirm with the provider whether the reference coordinate is being specified correctly.

**Comment by ayshih** [comment]
Put another way, the "equator" of your defined projection is the first row of pixels given how CRPIX2 is defined, and is not at constant declination given how CRVAL2 is defined.  For the grid to appear rectangular CRVAL2 must be zero, and CRPIX2 then defines where zero declination falls in pixel space, even though it is well outside of your pixel array.

**Comment by Firestar-Reimu** [comment]
Thanks! I will contact the provider about the projection issue.
