### ISSUE TITLE
units fail to cancel in output of some calculations

### ISSUE THREAD

**Issue by JostMigenda** [astropy/astropy#15200]
### Description

I create two quantities with the same value & unit in slightly different ways:
```Python
flux_a = 1 << u.Unit('1/cm')
flux_b = 1 << u.cm**(-1)
```
For `flux_b`, the output of a calculation is then `<Quantity 1.>`, while for `flux_a`, the output of the same calculation varies (apparently randomly?) between `<Quantity 1.>` and `<Quantity 1. cm / cm>`. See screenshot below:

![image](https://github.com/astropy/astropy/assets/16189747/d1078f4a-5ca9-418d-8501-bc73ccf748ad)

Additionally, I have made a [screen recording](https://github.com/astropy/astropy/assets/16189747/ea8e97f9-a3e7-48a6-9b7c-f0cd4c62c9ea) of the same code in a Jupyter notebook. Note that, when I re-run the code multiple times in the same kernel, the output appears to stay the same. It only changes when I restart the kernel.

### Expected behavior

`flux_b` shows the expected behavior: Equal units cancel out every time and are not printed in the output.

### How to Reproduce

1. Create new conda environment with `conda create -n "astropy-test" python=3.11`, then activate it with `conda activate astropy-test`
2. Run `pip install astropy`
3. Run the following code:
```python
import astropy
import astropy.units as u

xsec = 1 << u.cm
flux_a = 1 << u.Unit('1/cm')
flux_b = 1 << u.cm**(-1)

print(astropy.__version__)  # '5.3.2'
print(flux_a == flux_b)  # True
print(f"{flux_a * xsec = }")  # <-- This line varies!
print(f"{flux_b * xsec = }")  # expected behavior
```
4. Quit the interpreter or restart the kernel, if applicable.
5. Repeat 3. and 4. multiple times; note how the third line of output appears to change randomly between `<Quantity 1.>` and `<Quantity 1. cm / cm>`

### Versions

macOS-10.16-x86_64-i386-64bit
Python 3.11.4 (main, Jul  5 2023, 08:41:25) [Clang 14.0.6 ]
astropy 5.3.2
Numpy 1.25.2
pyerfa 2.0.0.3
_[scipy, matplotlib not installed in this conda environment]_

(These versions are from a brand new conda environment specifically created to reproduce this issue. However, I have observed the same thing in an older conda environment running Python 3.9 and AstroPy 5.1.)

**Comment by JostMigenda** [comment]
Some more testing:

* When I change units to different powers of `cm` (or even multiply with other units) I get the same issue. See e.g. the screenshot, which shows the original example I found when running some simulation code, where `xsec = 1 << u.cm**2` and `flux_a = 1 << u.Unit("1/(cm**2 MeV s)")`.¹
![image](https://github.com/astropy/astropy/assets/16189747/5c7ac9d3-38b5-4179-95b6-de2d4319d974)

* However, when I change `cm` to `m` or `km` in the original example, the issue does _not_ appear.

¹ If you were slightly confused by the variable names in the original code example: That’s where they come from. 😉

**Comment by JostMigenda** [comment]
Some good detective work by @Sheshuk in [this comment](https://github.com/SNEWS2/snewpy/issues/267#issuecomment-1729494181): The issue is that `u.Unit("cm")` randomly changes between `u.cgs.cm` and `u.si.cm` and those two are subtly different (whereas e.g. `u.cgs.g` and `u.si.g` are not):
```Python
>>> import astropy.units as u
>>> u.cgs.g is u.si.g
True
>>> u.cgs.cm is u.si.cm
False
>>> u.cgs.cm == u.si.cm
True
```

So, indeed, `import astropy.units as u; print(u.Unit("cm") is u.cgs.cm)` randomly changes; and if it is `False`, then the units `cm / cm` don’t cancel:
<img width="1171" alt="image" src="https://github.com/astropy/astropy/assets/16189747/d9a12b41-5fe7-4d99-af66-26e46f27f655">

**Now, how to fix this?** 

[`u.cgs.cm` is defined](https://github.com/astropy/astropy/blob/b74412ce6359650a6ba3a8800ab865b3f7e31a4a/astropy/units/cgs.py#L15) with a call to `def_unit()` instead of being `u.si.cm`. AFAICT, the only resulting difference is in the `"_represents"` field:
```Python
>>> u.cgs.cm.__dict__
{'_represents': Unit("cm"), '_names': ['cm', 'centimeter'], '_short_names': ['cm'], '_long_names': ['centimeter'], '_format': {}, '__doc__': 'centimeter (cm)', '_hash': -3031953375841410037, '_type_id': (('m', 1),)}
>>> u.si.cm.__dict__
{'_represents': Unit("0.01 m"), '_names': ['cm', 'centimeter'], '_short_names': ['cm'], '_long_names': ['centimeter'], '_format': {}, '__doc__': 'centimeter (cm)', '_hash': -6272434772036495896, '_type_id': (('m', 1),)}
```
Contrast this with:
```Python
>>> u.cgs.g is u.si.g
True
>>> u.cgs.g.__dict__['represents']
Unit("0.001 kg")
```
So it seems to me the extra call to `def_unit()` for `u.cgs.cm` is unnecessary and we could change the definition to `cm = si.cm`? If you agree, I’m happy to submit a PR.

**Comment by mhvk** [comment]
Interesting. I can reproduce it and think you are right about the origin: that we define `cm` twice. This code has been there more or less from the start so we need to be a bit careful. At least, at first I thought we could not get rid of the definition altogether, since in the `cgs` system it seems to be important that `cm` is not some `PrefixUnit`, but actually a named unit: at least, if I just replace the `def_unit` with `cm = si.cm`, everything breaks... 

Note that, similarly, in SI, one sees there is a definition of `kg` first, and then `g` is derived from it. So, a derived unit is fine. And indeed if I define cm separately inside si.py, using `def_unit`, it does seem to work.

I'll think a bit what would be the best approach...

**Comment by mhvk** [comment]
p.s. Introduced in #579

**Comment by mhvk** [comment]
@JostMigenda - thanks again for reporting -- and figuring out what was wrong! See #15368 for a fix.
