### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by psmoros** [astropy/astropy#15212]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@u32i) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by pllim** [comment]
Thank you for reaching out to us! I have created one, please see https://github.com/astropy/astropy/security/policy .

p.s. @astropy/coordinators or @astropy/astropy-project-release-team , if you disagree with the text, please propose updated text as PR(s). Thanks!

p.p.s. @astropy/astropy-project-release-team , should we add updating `SECURITY.md` listing to release procedures?
