### ISSUE TITLE
`TypeError` when comparing TimeDelta and a nan Quantity

### ISSUE THREAD

**Issue by greyskyy** [astropy/astropy#15230]
### Description

Running on python 3.11, comparing a `Quantity` holding a `nan` value to a `TimeDelta` object throws a `TypeError` rather than returning `False`, as expected. (see code in 'How to reproduce'.

I would expect a `Quantity` with a value of `nan` but a time unit to compare just like comparing raw numbers, returning `False`

### Expected behavior

I would expect this to return `False`, similar to other comparisons with `np.nan`

### How to Reproduce

1. Install astropy
2. open an interactive python shell.

```
>>> from astropy.time import TimeDelta
>>> import astropy.units as u
>>> import numpy as np
>>> TimeDelta(5, format="sec") < (np.nan * u.s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'TimeDelta' and 'Quantity'
>>>
>>> TimeDelta(5, format="sec") < u.Quantity(np.nan, unit=u.s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'TimeDelta' and 'Quantity'
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
astropy 5.2.1
Numpy 1.24.1
pyerfa  2.0.0.1
Scipy 1.10.0
Matplotlib  3.6.3

**Comment by mhvk** [comment]
Thanks for reporting! I agree it would be nice if this just worked!

 The underlying problem is that in the comparison, `TimeDelta` tries to turn the quantity into its own type, i.e., `TimeDelta(np.nan * u.s)`, and this fails because `TimeDelta` does not support non-finite numbers. This reminded me there is a long-standing issue about this : #6509 (though that is in part also about a wish to have masked times).

Note that I do think we need something like this to generically introduce the behaviour that all comparisons are falls with it. It would be equivalent to "Not a Time" (NaT) that numpy datetime has.

**Comment by pllim** [comment]
So this is more of a feature request than a bug?

**Comment by mhvk** [comment]
I guess it is a bug that can be solved with a new feature...

**Comment by greyskyy** [comment]
i had hopes that it was something simple and I could whip out a quick PR ... but alas.  It seems more involved. Sounds like a feature request to me.

**Comment by mhvk** [comment]
I have been thinking a bit more too, and in principle, I think in `astropy/time/formats.py`, one could override `_check_val_type` for `TimeDeltaNumeric` and not do the test whether the values are finite. In contrast to `Time`, for `TimeDelta` NaN and infinity are fairly well defined. Not trivial, but also not too deep in the innards.
