### ISSUE TITLE
2 second error on UTC time scale

### ISSUE THREAD

**Issue by haussel** [astropy/astropy#15241]
### Description

The years 1970 and 1971 are not bissextile, so they contain 365 * 24 * 3600 s each. So the expected UTC of 1970-01-01T00:00:00.0 + 2 * 365 * 24 * 3600 s  is  1972-01-01:00:00:00.0. Instead I get 1971-12-31T23:59:58.00 which is 2s short of the correct value. 

1972 is bissextile, and contains 2 leap seconds (on 1972-06-30 and 1972-12-31. So that the expected UTC of 1970-01-01T00:00:00.0 + 24 * 3600 * (2 * 365 + 366) + 2 is 1973-01-01:00:00:00.0

This 2s error propagates to 2023 (which is how I originally found it). 

The behavior of the UTC scale end of 1970 is weird as 1970-01-01T00:00:00.0 + 365 * 24 * 3600 s gives 1970-12-31T23:59:59.054 

### Expected behavior

1970-01-01T00:00:00.0Z + 2 * 365 * 24 * 3600 s  should   give 1972-01-01:00:00:00.0

### How to Reproduce

```python
from astropy import units as u
from astropy.time import Time

date_obs_utc_2 = Time('1970-01-01T00:00:00.0', scale='utc') + 24.0 * 3600.0 * 365.0 * 2.0 * u.s
print(date_obs_utc_2.utc)
# outputs 1971-12-31T23:59:58.000 while 1972-01-01T00:00:00.000 is expected

date_obs_utc_3 = Time('1970-01-01T00:00:00.0', scale='utc') + 24.0 * 3600.0 * (365.0  * 2.0 + 366.0) * u.s + 2. * u.s
print(date_obs_utc_3.utc)
# outputs 1972-12-31T23:59:59.000 while 1973-01-01T00:00:00.000 is expected

date_obs_utc_1 =  Time('1970-01-01T00:00:00.0', scale='utc') + 24.0 * 3600.0 * 365.0 * u.s
print(date_obs_utc_1.utc)
# outputs 1970-12-31T23:59:59.054 which is very weird... 1971-01-01T00:00:00.000 expected
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

macOS-13.4.1-x86_64-i386-64bit
Python 3.9.17 (main, Jun 10 2023, 11:04:38)
[Clang 14.0.3 (clang-1403.0.22.14.1)]
astropy 5.3.1
Numpy 1.24.1
pyerfa 2.0.0.3
Scipy 1.10.1
Matplotlib 3.7.2

**Comment by ayshih** [comment]
Heh, you clearly haven't been initiated on the complexity of historical UTC.  Prior to 1972, UTC seconds were essentially not of a uniform length, and on average slightly longer than the length of a SI second (which is the same as a TAI second, which was defined in 1958).  From 1958 to the end of 1971, there accrued exactly 10 more TAI seconds than UTC seconds.  Leap seconds are the post-1972 solution to stop these confusing changes to the length of a UTC second.

One way to illustrate this complexity is to print out the duration of the final UTC second in 1971 in units of SI seconds:
```python
>>> (Time('1972-01-01T00:00:00') - Time('1971-12-31T23:59:59')).to('s')
<Quantity 1.10775803 s>
```
This includes the final shift of 0.11 seconds in UTC so that the difference between TAI and UTC became exactly an integer number of seconds.

See [this Wikipedia section](https://en.wikipedia.org/wiki/Coordinated_Universal_Time#History) for more information

**Comment by ayshih** [comment]
In other words, for the years in question, two years' worth of SI seconds was slightly shorter than two years' worth of UTC seconds.

**Comment by pllim** [comment]
So, there's nothing to fix here?

**Comment by haussel** [comment]
I disagree. the 2 second shift propagates to 2023. The TAI-UTC value is an integer number of seconds according to NIST from 1970 onward.  Here's an other demonstration:

in Unix, the command:
> date -u -r 1672531200
Sun Jan  1 00:00:00 UTC 2023

This is not UTC, this is POSIX time, without Leap seconds. There are 27 leap seconds between 1970-01-01:00:00:00 UTC (the origin of the POSIX time) and 2023. 

now in astropy:

from astropy.time import Time
from astropy import units as u
delta_utc_t = Time('1970-01-01T00:00:00.000', scale='utc')+1672531200*u.s
delta_utc_t.utc
Out[7]: <Time object: scale='utc' format='isot' value=2022-12-31T23:59:31.000>

so 29 s behind and not 27 s as expected. I stand by my bug report, satrapy UTC is 2 sec off.

**Comment by ayshih** [comment]
> The TAI-UTC value is an integer number of seconds according to NIST from 1970 onward.

Again, see the Wikipedia section that I linked above (or any other references that describe the handling of UTC prior to 1972).  TAI-UTC was not always an integer number of seconds.

The average length of a UTC second was longer than the SI second for 1970 to 1971.  For example, at the start of 1972, TAI and UTC were different by exactly 10 seconds:
```python
>>> Time('1972-01-01T00:00:00', scale='tai').utc
<Time object: scale='utc' format='isot' value=1971-12-31T23:59:50.000>
```
At the start of 1971, TAI and UTC were different by 8.95 seconds:
```python
>>> Time('1971-01-01T00:00:00', scale='tai').utc
<Time object: scale='utc' format='isot' value=1970-12-31T23:59:51.054>
```
That's one way to see that one year's worth of TAI seconds did not actually span a full year's worth of UTC seconds.

Now, I don't know how POSIX time is rigorously defined, but I'd guess that they're counting SI seconds from 1970 (and ignoring leap seconds).  That means that POSIX time is formally 2 seconds off from UTC time at the start of 1970.  The 2-second issue you are seeing is not in Astropy, but in the presumption that POSIX time and UTC are the same at the start of 1970.

**Comment by ayshih** [comment]
By the way, I should clarify that Astropy does its time arithmetic in SI seconds, not in UTC seconds (again, these are unequal only prior to 1972).  So, when you do this:
```python
Time('1970-01-01T00:00:00.0', scale='utc') + 24.0 * 3600.0 * 365.0 * 2.0 * u.s
```
you are actually adding two years' worth of SI seconds to a UTC time.  It's not possible to add two years' worth of UTC seconds.

**Comment by haussel** [comment]
So you are telling me that all the space agencies time accounting is wrong ? Because they add SI seconds from 1970-01-01...

**Comment by haussel** [comment]
I see your point...Indeed when I use slalib formula  for 1970-01-01T00:00:-- https://github.com/Starlink/starlink/blob/master/libraries/sla/dat.f I indeed find a difference TAI-UTC = 8.000082 s

OK this explains why I loose 2 seconds when adding seconds. Thank you I stand corrected.

**Comment by ayshih** [comment]
Well, I don't know about "all the space agencies", but people handling time scales inaccurately is hardly surprising.  People routinely ignore leap seconds because a few seconds of discrepancy isn't worth the hassle for them.  Such people aren't going to lose any sleep about the pre-1972 slight difference in the length of UTC second and SI second.

In my world (solar), those who care more about getting time correct stick with TAI.  Using UTC is perfectly fine as long as leap seconds are accounted for and the reference point for calculations is a time when the difference between TAI and UTC is an integer number of seconds.  In solar, 1979 happens to be a de facto reference year for a certain subset of analysis software.

**Comment by haussel** [comment]
> Now, I don't know how POSIX time is rigorously defined, but I'd guess that they're counting SI seconds from 1970. That means that POSIX time is formally 2 seconds off from UTC time at the start of 1970. The 2-second issue you are seeing is not in Astropy, but in an incorrect assumption that POSIX time and UTC are the same at the start of 1970.

Well, the POSIX standard is very clear that the reference epoch is UTC 1970-01-01T00:00:00.000 and counting SI seconds. So if I understood you correctly, there is between 
UTC 1970-01-01T00:00:00.000 and UTC 1972-01-01T00:00:00.000  365*24*3600 UTC seconds but  365*24*3600 + 2 SI  seconds ... 

Does this sounds right ?

**Comment by ayshih** [comment]
> So if I understood you correctly, there is between UTC 1970-01-01T00:00:00.000 and UTC 1972-01-01T00:00:00.000 2 x365 x 24 x3600 UTC seconds but 2x 365x24x3600 + 2 SI seconds ...
> 
> Does this sounds right ?

Agreed.

> > Now, I don't know how POSIX time is rigorously defined, but I'd guess that they're counting SI seconds from 1970. That means that POSIX time is formally 2 seconds off from UTC time at the start of 1970. The 2-second issue you are seeing is not in Astropy, but in an incorrect assumption that POSIX time and UTC are the same at the start of 1970.
> 
> Well, the POSIX standard is very clear that the reference epoch is UTC 1970-01-01T00:00:00.000 and counting SI seconds.

Actually, now that I reminded myself how POSIX time is defined, they ignore leap seconds.  That means that POSIX seconds may not be SI seconds on any day that includes a leap second, depending on the approach to handle the leap second (e.g., smearing).  This 2-second discrepancy for 1970 to the end of 1971 is just one more thing that you have to account for on top of the explicit leap seconds.

**Comment by ayshih** [comment]
I'll add that Astropy can convert times to/from POSIX time, so that's one way to work in UTC seconds pre-1972:
```python
>>> Time('1970-01-01T00:00:00', scale='utc').unix
0.0
>>> Time(2 * 365 * 24 * 3600, format='unix').isot
'1972-01-01T00:00:00.000'
```
