### ISSUE TITLE
Error when trying to use the transform_to() method in Astropy 5.1

### ISSUE THREAD

**Issue by donkuettel** [astropy/astropy#15243]
### Description

I got a "TypeError: concatenate() got an unexpected keyword argument 'dtype'" when I used the transform_to() method to transform coordinates from one reference frame to another.

### Expected behavior

I expected the transform_to() method to transform coordinates from one reference frame to another without errors.

### How to Reproduce

[py_script.txt](https://github.com/astropy/astropy/files/12467506/py_script.txt)
[error_message.txt](https://github.com/astropy/astropy/files/12467507/error_message.txt)

### Versions

Windows-10-10.0.19041-SP0
Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul 5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)]
astropy 5.1
Numpy 1.24.3
pyerfa 2.0.0
Scipy 1.10.1
Matplotlib 3.7.1

**Comment by pllim** [comment]
Hello. astropy 5.1 is no longer receiving bug fixes. Please upgrade astropy to 5.3.x series and try again.

```
pip install astropy -U
```

Even better if you can try the development version from `main` to make sure that it is not already fixed but just unreleased.

```
pip install -U -i https://pypi.anaconda.org/astropy/simple astropy --pre
```

**Comment by donkuettel** [comment]
Copy. Will report back on results from updating.

**Comment by donkuettel** [comment]
That worked! Sorry for the unnecessary ticket. This is my first foray into astropy, and I didn't realize I was using an old version. Cheers.

**Comment by pllim** [comment]
No worries! Glad a simple update worked for you. 😸
