### ISSUE TITLE
Use explicit imports

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#15257]
### What is the problem this feature will solve?

Not use star imports except in `__init__.py` files.

### Describe the desired outcome

Use explicit imports

### Additional context

For a good summary why star imports are frowned upon: https://github.com/asmeurer/removestar#why-is-import--so-bad

**Comment by pllim** [comment]
I agree but getting rid of this in this codebase is going to create a lot of churn. Please put this on the dev telecon agenda. Thanks!

**Comment by nstarman** [comment]
Actually I think only 1 file is changed!

**Comment by pllim** [comment]
Oh, really? In that case, just open PR. LoL.

**Comment by nstarman** [comment]
@WilliamJamieson, `astropy/modeling/models.py` is the only non-`__init__.py` file that `removestar` found with star imports. Any interest in making the imports explicit?
Couple options: If you're worried about importing all the models, we could add a test of this, checking the ``__all__``. Alternatively, is this file around for historical purposes, vs importing to the top-level? Were you considering deprecating this file?

**Comment by WilliamJamieson** [comment]
I've been considering reorganizing astropy modeling so that models is a proper sub-module where all the pre-defined models live. This would turn models.py into an __init__.py.

**Comment by nstarman** [comment]
There would be no change in API if that happened now, as in just do
```models.py -> models/__init__.py``, keeping the current star imports.

**Comment by WilliamJamieson** [comment]
That would work.

**Comment by WilliamJamieson** [comment]
I'll do it

**Comment by nstarman** [comment]
I guess we can close this!
