### ISSUE TITLE
Perhaps run doctests on a very limited set of versions only?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#15312]
### What is the problem this feature will solve?

We have been bitten several times by `repr` changes out of our control, e.g., the change in number of significant digits for numpy scalars, the inclusion of their type more recently, and a change in `repr` of `OrderedDict` in python 3.12.  In related discussion at numpy @rgommers made the reasonable point that doctests are not meant to be valid for all versions; they are meant to check that documented code works, but insisting that things work over different versions is the task of the test suite. For the doctests, it may make more sense to just test the newest supported versions of our dependencies for each astropy release, and not worry if the outputs are slightly different with older dependencies. We'd then use the same dependencies on RTD as well.

### Describe the desired outcome

We remove the need for work-arounds for version-dependent differences. We just run doctests on for one version combination for a given version of astropy.

Advantages include not spending so much CI time on it.

@olebole asked, however, that if we go this path, we also change our structure so that doctests are not run by default, since this make things easier for packaging (failures in doctests that really should be ignored).

### Additional context

We are in the process of removing the doctests on 32-bit in #15044.

**Comment by pllim** [comment]
Related issues:

* #15044 
* #15095
* #14553

**Comment by ev-br** [comment]
I'll note that there's a way to sidestep all whitespace/repr issues completely, for all versions. 
The main point is to use `np.allclose(eval(want), eval(got))` in the doctest checker.
This is neither hypothetical not new, it's been used used for SciPy in its refguide-check utility for almost a decade, and only slightly less for NumPy. 

The tool has been recently refactored into a standalone package to provide drop-in doctest-compatible functionality in 
https://github.com/ev-br/scpdt/blob/main/scpdt/ (the checker is here: DoctestChecker is https://github.com/ev-br/scpdt/blob/main/scpdt/impl.py#L189). 
Hystorically, we were not using pytest as a runner, and here's a PR to manually run it on scipy, https://github.com/scipy/scipy/pull/16391 , and on numpy https://github.com/numpy/numpy/pull/21962.

Pytest integration work is under development in https://github.com/scipy/scipy/pull/19242.

**Comment by mhvk** [comment]
@ev-br - right now, we've got our own `+FLOAT_CMP` from https://github.com/scientific-python/pytest-doctestplus (which started in astropy) so at least those are covered. But I see the advantage of using `np.allclose(eval(want), eval(got))`: that deals with the repr changes for scalars too.

Overall, I hope these various efforts can be merged!

**Comment by pllim** [comment]
Generally speaking, I am wary of `eval` unless there is a way to sanitize the inputs first. @WilliamJamieson knows how I feel because it just came up in a different context (testing code in Example Gallery that is rotting).

**Comment by ev-br** [comment]
> Overall, I hope these various efforts can be merged!

@mhvk - indeed, I'm on record about it :-) https://github.com/numpy/numpy/issues/21070#issuecomment-1133832331

**Comment by mhvk** [comment]
Closing this issue, since we now only run doctests for `numpy>=2.0` or `python>=3.12` as needed.
