### ISSUE TITLE
Rename astropy.io.votable.tree.Table

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#15358]
Having a class name clash is occasionally unfortunate, and in this issue, I would suggest renaming `astropy.io.votable.tree.Table` to something else. I have `TableElement` in mind, but literarily would be happy with other suggestions, too. And am willing to open a PR for it once there is feedback on the idea.

We did a similar rename in pyvo very recently, see https://github.com/astropy/pyvo/pull/484 and for context https://github.com/astropy/pyvo/issues/477; 

If this is a go ahead, it should land in 6.0

cc @msdemlei @tomdonaldson @andamian

**Comment by andamian** [comment]
I don't see anything wrong with this.

**Comment by bsipocz** [comment]
> I don't see anything wrong with this.

Anything wrong with status quo or with the rename? 😅

**Comment by andamian** [comment]
> > I don't see anything wrong with this.
> 
> Anything wrong with status quo or with the rename? 😅

Friday afternoon - I should close the shop :-).

**Comment by bsipocz** [comment]
> Friday afternoon - I should close the shop :-).

It was such a high ball, I couldn't leave it alone, sorry :). (And should also drop this keyboard, this was a tiring day here, too)

**Comment by pllim** [comment]
I am removing the milestone here. We can track milestone over at https://github.com/astropy/astropy/pull/15372
