### ISSUE TITLE
WinError 1455 .fits readarray()

### ISSUE THREAD

**Issue by demichieldewilde** [astropy/astropy#15353]
### Description

While loading a .fits file (82GB) the error "[WinError 1455] The paging file is too small for this operation to complete." got raised in the function readarry in "...\anaconda3\pkgs\astropy-5.3.3-py311h59ca53f_0\Lib\site-packages\astropy\io\fits\file.py". 

In this function a Note was included explaining the problem:

                        # NOTE: mode='readonly' results in the memory-mapping
                        # using the ACCESS_COPY mode in mmap so that users can
                        # modify arrays. However, on some systems, the OS raises
                        # a '[Errno 12] Cannot allocate memory' OSError if the
                        # address space is smaller than the file. The solution
                        # is to open the file in mode='denywrite', which at
                        # least allows the file to be opened even if the
                        # resulting arrays will be truly read-only.

The included exception did not capture WinError 1455 so I appended folowing code which is almost the same as for the first exception: if exc.errno == errno.ENOMEM and self.mode == "readonly": .....

                     elif exc.winerror == 1455 and self.mode == "readonly": 
                             warnings.warn(
                                "Could not memory map array with "
                                "mode='readonly', because of the error [WinError 1455] The paging file is "
                                "too small for this operation to complete.,\n thus falling back to "
                                "mode='denywrite', which means that "
                                "the array will be read-only",
                                AstropyUserWarning
                            )
                            self._mmap = mmap.mmap(
                                self._file.fileno(),
                                0,
                                access=MEMMAP_MODES["denywrite"],
                                offset=0,
                            )

which solves the problem

### Expected behavior

[WinError 1455] The paging file is too small for this operation to complete.

### Versions

Windows-10-10.0.22621-SP0
Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)]
astropy 5.3.3
Numpy 1.24.3
pyerfa 2.0.0
Scipy 1.10.1
Matplotlib 3.7.1

**Comment by pllim** [comment]
Thank you for reporting and proposing a solution. Are you interested to open a pull request with your patch so you get the credit for fixing it? 😸

**Comment by demichieldewilde** [comment]
Hey,
Thank you very much for your message;
I Would like to try that.
Which is the best way for me to proceed? I am relatively new to github.
I created a new branch on my local repository, but I do not have
permission to push this to the astropy repository [origin].

kind regards,
Michiel De Wilde

**Comment by pllim** [comment]
Hello and thanks for trying! Contributors should contribute via their *fork*, so `origin` should point to your fork, and `upstream` to this repository. Then you open a Pull Request from the branch on your fork.

Would you find this helpful: https://docs.astropy.org/en/latest/development/workflow/development_workflow.html ?

**Comment by saimn** [comment]
What is the value of `exc.errno` for this exception ? Would be easier to add an exception case to the current `exc.errno == errno.ENOMEM` instead of checking a windows specific error.

**Comment by demichieldewilde** [comment]
Hey Simon,

That could but I struggled a bit to do it in that manner. How should it
then be done?
Thanks

Op do 21 sep 2023 om 18:13 schreef Simon Conseil ***@***.***>:

**Comment by saimn** [comment]
@demichieldewilde - if you could just print the value of `exc.errno` when the exception happen, or use a debugger to find the value ? It may not be set to something useful but would be great to check.

**Comment by demichieldewilde** [comment]
@saimn , The value of `exc.errno` is 22  when I load the file. But how should I add this to the current `exc.errno == errno.ENOMEM`?

**Comment by saimn** [comment]
So it's set to `errno.EINVAL`:
```
In [4]: errno.errorcode[22]
Out[4]: 'EINVAL'
```

So I think we can use something like `if exc.errno in (errno.ENOMEM, errno.EINVAL) and ...`
