### ISSUE TITLE
python crash when export wcs(Terrestrial azimuthal perspective) to header 

### ISSUE THREAD

**Issue by niu541412** [astropy/astropy#15362]
### Description

The wcs projection type ["TLON-AZP", "TLAT-AZP"] will cause Python crash.

However, some similar projection keywords work well, e.g.  ["SELN-AZP", "SELT-AZP"], ["TLON-SZP", "TLON-SZP"]. 
 ["TLON-AZP", "TLAT-AZP"] should be allowed wcs type because it's an example in section 7.4.1 of the [official wcs paper](https://www.aanda.org/articles/aa/abs/2002/45/aah3860/aah3860.html).

I've tried to debug it, it seems caused by the WCSlib library, but it's a bit hard for me to figure it out.

Currently, I use  ["SELN-AZP", "SELT-AZP"] to generate a tricky header, then replace keywords: "CTYPE1A" and "CTYPE2A" to  ["TLON-AZP", "TLAT-AZP"] to construct my desired fits. FITS image viewer, e.g. ds9 can read the wcs information correctly. 

### Expected behavior

construct a fits contains the wcs of Terrestrial azimuthal perspective.

### How to Reproduce

1. Get package from pip
2. Then run python
```python
from astropy.wcs import WCS
wA = WCS(naxis=2)
wA.wcs.ctype = ["TLON-AZP", "TLAT-AZP"]
wA.to_header()
```
3. An error occurs.
>/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

### Versions

macOS-12.6.9-x86_64-i386-64bit
Python 3.11.5 (main, Aug 24 2023, 15:23:30) [Clang 14.0.0 (clang-1400.0.29.202)]
astropy 5.3.3
Numpy 1.24.4
pyerfa 2.0.0.3
Scipy 1.11.2
Matplotlib 3.7.3

**Comment by pllim** [comment]
That error came from multiprocessing. Is it possible to debug this using a traceback does not involve multiprocessing? That is, please rerun your stuff with multiprocessing turned off.

**Comment by niu541412** [comment]
After debugging, this is caused by the WCSLIB. The comment length defined for the keyword CTYPE is not enough in some specific projection types.
https://github.com/astropy/astropy/blob/1ae26ae0fcf5b8ffe0563d73be7787e9c835bf0e/cextern/wcslib/C/wcshdr.c#L504C24-L504C24
I've reported this to the author and believe it will be fixed in the next version of WCSLIB.

**Comment by pllim** [comment]
Glad you managed to reach a solution upstream and thanks for reporting back!

We usually try to ship with latest wcslib when it is released. @mcara is very good about that.
