### ISSUE TITLE
Deprecate Time.ptp() method?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#15379]
### What is the problem this feature will solve?

Numpy has ~deprecated~ removed the `ndarray.ptp()` method. This also means the `np.ptp()` function will no longer look for a `.ptp()` method, so will no longer work on `Time`. It seems to make sense to deprecate it on `Time` too (plain removal seems wrong; not sure why numpy didn't deprecate).

### Describe the desired outcome

The `Time` methods that are meant to mimic those of `ndarray` are kept up to date. We also ensure that corresponding numpy functions work on `Time` instances.

### Additional context

See #15378 for other updates related to the removal of `ndarray.ptp()` in numpy 2.0.

**Comment by pllim** [comment]
`AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.`

Looks like it is still possible to call PTP via `np.ptp(arr, ...)` syntax, so maybe that means you don't really have to deprecated `Time.ptp()` unless you want people to use `np.ptp(Time, ...)` instead?

**Comment by mhvk** [comment]
Yes, indeed, one question is whether we should just defer to `np.ptp(time, ...)`. 

Independently, we should ensure the `np.ptp(...)` construction works. In previous `numpy`, it just looked for a `.ptp()` method, but that is removed too, so for numpy >= 2.0, we need to have it supported via `__array_function__`.

**Comment by pllim** [comment]
Maybe this should be discussed in astropy-dev. While numpy has a lot of liberty to break stuff since they going to 2.0, we are not on that route with 6.0.

**Comment by mhvk** [comment]
Agreed that we should not break things willy-nilly, and for `Time`, I would definitely not just remove it, it would need a regular deprecation period.

But the main reason to even consider this is that by removing `.ptp()`, `Quantity` and all its subclasses also loose it (it was not overwritten in most).

Anyway, perhaps first of all just a ping to @taldcroft.

**Comment by olintoeduardo** [comment]
I want to work on this issue, but I have never contributed to the project. Would that be appropriate?

**Comment by taldcroft** [comment]
BTW I'm OK with deprecating that method.

**Comment by mhvk** [comment]
@olintoeduardo - you definitely could, but note that it involves not just deprecating the method (easy) but also ensuring `np.ptp(time)` still works - which means editing `astropy/time/time_helper/function_helpers.py`, plus adjusting/adding tests. This is not quite trivial, and this close to our feature freeze, it may be harder than usual to get help.

Generally, I suggest to start with something that actually bugs you, or that you would like to see improved.

**Comment by olintoeduardo** [comment]
Great! I was taking a look at all references of ptp() in the project, and in astropy/time/core.py there is a definition to another ptp() function with the following description: "This is similar to :meth:`~numpy.ndarray.ptp`, but adapted to ensure that the full precision given by the two doubles ``jd1`` and ``jd2``is used." However this is never used in the project. Should it be removed?
