### ISSUE TITLE
datatype does not still loads as strings are passed in

### ISSUE THREAD

**Issue by promiseibe** [astropy/astropy#15376]
### Description

Datatype does not still loads as a string

### Expected behavior

i expected strings to load as datatypes

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by pllim** [comment]
Hello. Please provide a minimally reproducible code snippet that demonstrate this problem you are having.

It is unclear to me what "datatype" you are referring to and you provided no other information that is useful for further analysis of this problem. I will mark this issue to be closed automatically unless I hear more from you. Thank you.
