### ISSUE TITLE
Warnings about ignored packages

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#15403]
### Description

With the switch from `setup.cfg` to `pyproject.toml` (#15247) the installation log now reports many warnings about ignored packages, e.g.:
```
check.warn(importable)
  /tmp/simon/pip-build-env-990sh2z5/overlay/lib/python3.11/site-packages/setuptools/command/build_py.py:204: _Warning: Package 'astropy.convolution.src' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'astropy.convolution.src' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'astropy.convolution.src' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'astropy.convolution.src' to be distributed and are
          already explicitly excluding 'astropy.convolution.src' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************
```
and same for all `data` directories and other directories that don't have an `__init__.py` file.

It's related to https://setuptools.pypa.io/en/latest/userguide/package_discovery.html and the fact that setuptools now prefers the use of a src-layout (though I don't know why switching from `setup.cfg` to `pyproject.toml` triggers this behavior).
I had this issue with other packages and solved that by using a src-layout but it seems astropy is not ready for that yet.
However we should find a solution and make sure that those directories are bundled in wheels/sdist.
I think the solution is to use namespace=True (i.e. `find_namespace_packages` vs `find_packages`) but this requires more investigation to be sure.

**Comment by pllim** [comment]
If we cannot find a simple solution, we can always undo the affected parts of https://github.com/astropy/astropy/pull/15247 . I think it is risky to move to `src` layout so close to feature freeze. Lots of open PRs will have conflicts.

**Comment by mhvk** [comment]
I'd rather have #15247 reverted than let it lead to yet more needless churn... (But hopefully this has a simple solution...)

**Comment by nstarman** [comment]
I don't think we should revert to use formats that are on the deprecation path, like `setup.cfg`. That seems more problematic than fixing the issue that Python tools have been universally converging on `src`-layout. Thankfully when you change a folder location in git all diffs naturally move on a rebase. Unfortunately all PRs will need to rebase, but pressing the rebase button is really not much of a barrier.

**Comment by mhvk** [comment]
Neither numpy nor scipy use the `src` layout; not sure why we should. 

(Sorry to be a bit grumpy, but for my taste ther recent focus on "esthetics" has rather distracted from actually getting new or improved functionality -- and the result seems, if anything, more things that break CI - I certainly don't envy all what @pllim has to do to keep the show running.)

**Comment by saimn** [comment]
It's only when looking at the full compilation/installation log (from setuptools), which is not shown by default when using tox.

**Comment by pllim** [comment]
Feels wrong to use `find_namespace:` when `astropy` isn't really a namespace package. 💭

**Comment by pllim** [comment]
Would something like https://github.com/astropy/astropy/pull/15422 work for you?

**Comment by mhvk** [comment]
While I find that the ruff style changes are often for the better, I agree with @bsipocz  that they also have caused a lot of extra work, and very much agree that without a really good cause we should not do further refactors that touch most of astropy.

Anyway, thanks @pllim for what looks like a solution to the actual problem!!!

**Comment by saimn** [comment]
@pllim - I think the solution is to use `namespaces = true`
https://setuptools.pypa.io/en/latest/userguide/datafiles.html#subdirectory-for-data-files

Not sure what `include-package-data = false` actually does, since we also use `package-data` (and setuptools-scm's finder).

**Comment by pllim** [comment]
Using namespace setting feels wrong since we do not publish namespace packages. Instead I follow this advice in the text you provided above:

```
or `include-package-data=False` in combination with a more fine grained `package-data` configuration.
```

**Comment by saimn** [comment]
> Using namespace setting feels wrong since we do not publish namespace packages.

We should settle on a solution for this issue, I've read again the docs and would still recommend using `namespaces=true`:

- using `include-package-data=False` (#15422) and relying on `package-data` is indeed possible. It's fine but maintaining `package-data` is not an easy task (it easy to forget adding something there in a PR) and we can avoid that (see below).

- `namespaces=true` is the default behavior, and it was probably also before this warning was added. We are using `data/` directories without an `__init__.py` file so technically those are namespace packages. And I don't think there is anything wrong with using it this way.

- With `include-package-data=True` we could remove all our current `package-data` settings, since setuptools-scm's finder plugin already provides the correct list of files. I proposed this in the pyproject migration PR (https://github.com/astropy/astropy/pull/15247#issuecomment-1703297888, and in particular this commit https://github.com/astropy/astropy/commit/8bdf61e4ff959acb59b1c0c6dbdb8d0574f6a19a which would make the configuration much simpler).

ping @astrofrog in case you missed that discussion.

**Comment by pllim** [comment]
Are you sure `namespaces` is supposed to be used this way to handle package data, and it is not just working by happy accident? If the latter, they might "fix it" in the future and then we will have this same problem again. I don't see how explicitly managing package data is bad. We used to do it with `setup_package.py` everywhere.

**Comment by saimn** [comment]
It's documented in https://setuptools.pypa.io/en/latest/userguide/datafiles.html#subdirectory-for-data-files so seems a valid use case to me.

**Comment by pllim** [comment]
OK in that case, I'll close my PR and let you handle it correctly then. Thanks!
