### ISSUE TITLE
RTD fails with WARNING: undefined label: 'python:bltin-boolean-values'

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15428]
- [ ] Revert https://github.com/astropy/astropy/pull/15433
- [ ] Rebuild doc for v5.3.4

<hr/>

Example log: https://readthedocs.org/projects/astropy/builds/22123170/

```
WARNING: undefined label: 'python:bltin-boolean-values'
```

729 warnings 😱 

This happens out of nowhere, so might have to ask RTD people first.

**Comment by saimn** [comment]
v5.3.4 doc build failed because of that, the build should be restarted when the issue is fixed.

**Comment by pllim** [comment]
I dunno how Python doc gets pushed but basically my patch over there needs to land on https://docs.python.org/3/ as defined in https://github.com/astropy/sphinx-astropy/blob/23f863fde2656c8c3180485326525e6e3d42a578/sphinx_astropy/conf/v2.py#L37

Hopefully a few days? 😬 🤞

**Comment by pllim** [comment]
If you really want the doc to build, we can temporarily disable turning warnings into errors, but still the API doc will be a bit wonky but it would only affect `bool`.

**Comment by saimn** [comment]
Yay not sure how long it can take. To avoid the issue on main we use pin the intersphinx URL to Python 3.11. But for the release we cannot do anything, the build is for the tag.

**Comment by pllim** [comment]
I vaguely remember @astrofrog do some RTD setup magic before to point a broken release doc to something else that is not broken without having to do another release just for the doc. But I don't quite remember what.
