### ISSUE TITLE
html_repr of Table is not horizontally scrollable in jupyter lab, works in notebook (Firefox)

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#15439]
### Description

A table with lots of columns displayed in a jupyter notebook is not scrollable horizontally (tested on firefox on Linux), the same works in the jupyter notebook interface.

This is a bit confusing, since the new notebook interface is also build on the lab components, I think.

Not sure if this is an astropy or a jupyter lab issue, first opening here.

### Expected behavior

Table has a horizontal scrollbar

### How to Reproduce

Open a jupyter notebook in lab and look at the output of a table with lots of columns / long column names.

### Versions

Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
Python 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
astropy 5.3.3
Numpy 1.24.4
pyerfa 2.0.0.3
Scipy 1.11.2
Matplotlib 3.7.3

**Comment by pllim** [comment]
Which Lab version?

**Comment by pllim** [comment]
Works for me on Lab 4.0.5

![Screenshot 2023-10-05 122955](https://github.com/astropy/astropy/assets/2090236/9077ae54-0a99-4de6-a2ec-9c22af14a6c7)

**Comment by saimn** [comment]
I noticed a similar issue with pandas, and here it is : https://github.com/jupyterlab/jupyterlab/issues/14625 (Firefox only it seems)

**Comment by pllim** [comment]
Oh, right. I was using Chrome. So, nothing much we can do here in this package to fix this?

**Comment by MridulS** [comment]
This seems to be fixed upstream in JupyterLab v4.0.7

**Comment by maxnoe** [comment]
Updated from 4.0.5 to the latest 4.0.8 and it works fine! Closing here.
