### ISSUE TITLE
Removal of deprecated code before 6.0 feature freeze

### ISSUE THREAD

**Issue by eerovaher** [astropy/astropy#15455]
### What is the problem this feature will solve?

[Feature freeze for `astropy` 6.0 is scheduled to be in the end of this month,](https://github.com/astropy/astropy/wiki/Release-Calendar) but there's still quite a lot of deprecated functionality in the codebase. Note that [according to APE 2 deprecation warnings should be visible to users for at least a year.](https://github.com/astropy/astropy-APEs/blob/main/APE2.rst#releases-and-backwards-compatibility) From the release calendar it can be seen that [`astropy` 5.1 was released on 2022-05-25 and 5.2 on 2022-12-12](https://github.com/astropy/astropy/wiki/Release-Calendar), so in 6.0 it is only permitted to remove code that was deprecated in `astropy` 5.1 or earlier.

### Describe the desired outcome

The following list contains items that were deprecated in `astropy` 5.1 or earlier as of 1ae27848e23910d6f1383ee47e02a53d8d73b3b3 (i.e. `main` at the time of opening this issue). They are ordered by the `astropy` version they were deprecated in.

- [x] https://github.com/astropy/astropy/pull/15462 https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/timeseries/sampled.py#L156-L157
- [x] https://github.com/astropy/astropy/pull/15463 https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/coordinates/builtin_frames/galactocentric.py#L269-L271
- [x] https://github.com/astropy/astropy/pull/15464 https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/wcs/wcs.py#L2109-L2110
- [x] https://github.com/astropy/astropy/pull/15466 https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/config/configuration.py#L50-L53
- [x] https://github.com/astropy/astropy/pull/15466 https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/config/configuration.py#L777-L782
- [x] https://github.com/astropy/astropy/pull/15467 https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/cosmology/realizations.py#L112-L114
- [x] https://github.com/astropy/astropy/pull/15468 https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/utils/introspection.py#L105-L106
- [x] https://github.com/astropy/astropy/pull/15470 https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/io/ascii/tests/common.py#L83-L84
- [x] https://github.com/astropy/astropy/pull/15461  https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/modeling/fitting.py#L2060-L2064
- [x] https://github.com/astropy/astropy/pull/15461 https://github.com/astropy/astropy/blob/1ae27848e23910d6f1383ee47e02a53d8d73b3b3/astropy/modeling/fitting.py#L2107-L2111

### Additional context

The procedure of removing deprecated functionality should be as follows:

1. Delete the relevant code, including the `@deprecated` decorator.
2. If the deprecation was mentioned in a docstring then update it accordingly.
3. Remove the associated tests that check that deprecation warnings are raised. A simple way to find them is to [run `pytest`](https://docs.astropy.org/en/latest/development/testguide.html#testing-guidelines), which will reveal the tests that started failing because of the removal of deprecated code. 
4. Remove any imports that are no longer needed. Note that if you follow [`astropy` developer guidelines that explain how to use the `pre-commit` framework](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit) then the unnecessary imports can be detected and removed automatically before or at the time of making the commit.
5. [Add a change log entry](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#add-a-changelog-entry) to the API section of the appropriate sub-package.

**Comment by pllim** [comment]
Thanks for putting this list together! Should try not to do these last minute.

**Comment by pllim** [comment]
But if some of these slip another release, also no big deal.

**Comment by pllim** [comment]
I don't think we should tell people this is good first issue and milestone to v6.0 given how close the feature freeze is. I'll leave modeling alone since there is a PR already (though if the author does not respond soon enough, I might just swoop in to wrap it up in time). I will handle the rest.

**Comment by pllim** [comment]
All the components mentioned now have associated PRs, so I am removing milestone from this issue. Thanks again for putting this together.

If you want to do such listing again for v6.1 and beyond, I am all for it as long as it is early in the dev cycle. Thanks!!!!

**Comment by pllim** [comment]
All the items have PRs now. We will track in the PRs from now on since they are milestoned. Thanks!
