### ISSUE TITLE
Consider adding an `indices` arg to some table group operations

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#1545]
@mhvk suggested in #1424 being able to supply an `indices` arg to table grouping functions like aggregate.  This would replicate some of behavior of numpy `reduceat`.  This is to capture this possibility for future consideration.

**Comment by taldcroft** [comment]
This hasn't gotten any traction in 8 years. @mhvk feel free to remove the close? label if you think it is still important.

**Comment by mhvk** [comment]
Indeed, it was a nice idea but doesn't really seem needed (I think `reduceat` is similarly not used a lot in numpy). So, let me just be the closing bot!
