### ISSUE TITLE
DOC: Search bar is broken using pydata-sphinx-theme

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15459]
https://docs.astropy.org/en/latest/search.html?q=WCS# does not give me any results. I see the following errors in the browser console (Chrome on Windows 10).

![Screenshot 2023-10-10 141833](https://github.com/astropy/astropy/assets/2090236/eb3db560-aee1-4bc9-8412-1e19ada1759d)

@drammock , any advice? 🙏

**Comment by drammock** [comment]
strange. I tried both Firefox & Chromium (on Linux) and I can't reproduce the error message in the console (but something is clearly failing, since I get no change in the page --- not even the "no results found" message). Search seems to be working normally on https://pydata-sphinx-theme.readthedocs.io/en/latest/search.html ...

my best guess is that `analytics.js` is erroring, which prevents the search functionality from properly loading?

**Comment by drammock** [comment]
> You mean, something ReadTheDocs injected is messing with the theme? 🤔

IDK where `analytics.js` comes from; is that provided by RTD?  searching in the HTML source of the astropy search page you linked to, `analytics.js` doesn't appear.

**Comment by pllim** [comment]
I did a local build and could not find any `analytics.js`. The search works on locally built pages. Maybe it is time I contact ReadTheDocs.

```
astropy/docs$ find ./ -name "*.js"
./_build/html/_sphinx_design_static/design-tabs.js
./_build/html/_static/documentation_options.js
./_build/html/_static/design-tabs.js
./_build/html/_static/copybutton.js
./_build/html/_static/sphinx_highlight.js
./_build/html/_static/searchtools.js
./_build/html/_static/scripts/bootstrap.js
./_build/html/_static/scripts/pydata-sphinx-theme.js
./_build/html/_static/doctools.js
./_build/html/_static/jquery.js
./_build/html/_static/copybutton_funcs.js
./_build/html/_static/_sphinx_javascript_frameworks_compat.js
./_build/html/_static/language_data.js
./_build/html/_static/clipboard.min.js
./_build/html/_static/vendor/fontawesome/6.1.2/js/all.min.js
./_build/html/searchindex.js
```

**Comment by ericholscher** [comment]
This is likely an issue with our new addons code /cc @humitos. We will take a look at it.

**Comment by pllim** [comment]
Actually I just realized that it might also not be working in the "stable" doc that uses a different theme. Thanks for looking into this!

**Comment by humitos** [comment]
> strange. I tried both Firefox & Chromium (on Linux) and I can't reproduce the error message in the console (but something is clearly failing, since I get no change in the page --- not even the "no results found" message).

I get the same behavior than you. No errors on the console, but not search results either.
 
> my best guess is that `analytics.js` is erroring, which prevents the search functionality from properly loading?

`analytics.js` is one of the new beta addons injected by Read the Docs. However, that error shown in the console does not seem related with the search issue to me.

I need to keep debugging this a little more to understand what's going on because I didn't find anything too obvious yet. I'll keep you updated here about my findings.

**Comment by drammock** [comment]
> that error shown in the console does not seem related with the search issue to me.

but isn't it the case that if `analytics.js` is loaded first *and throws an error* that subsequent JS files won't even be loaded? I'm no JS expert but I think I've encountered that behavior before.

**Comment by humitos** [comment]
We already fixed the issue about the `analytics.js` reported in the console. I'm not able to see it anymore in https://docs.astropy.org/en/latest/

The issue with search not returning any results persists, so it seems to be something different.

**Comment by pllim** [comment]
Hmmm... How do I debug? Because all I know is the search works when I build the same docs locally but it does not on ReadTheDocs. Does not appear matters what theme I use because I think it is also broken on "stable" that still has the old https://github.com/astropy/astropy-sphinx-theme

**Comment by pllim** [comment]
By the way, my Chrome dev console error looks different now. Does this help?

https://docs.astropy.org/en/latest/search.html?q=ggggg

![Screenshot 2023-10-25 090852](https://github.com/astropy/astropy/assets/2090236/886d19bd-f4d7-40ff-a8f4-1b35e4fa596a)

https://docs.astropy.org/en/stable/search.html?q=gggg&check_keywords=yes&area=default

![Screenshot 2023-10-25 090907](https://github.com/astropy/astropy/assets/2090236/3118a6f2-85ec-4bf0-bab6-b1cc8f5665ac)

**Comment by pllim** [comment]
@humitos , any update on this problem from the ReadTheDocs side? Thanks! 🙏

**Comment by humitos** [comment]
One thing that I noticed is that your Sphinx theme is not adding `data-content_root=` attribute to the HTML tag, which seems required for Sphinx 7.2.x:

* It's injected in the `layout.html` at https://github.com/sphinx-doc/sphinx/blob/bb74aec2b6aa1179868d83134013450c9ff9d4d6/sphinx/themes/basic/layout.html#L105
* It's used in the `searchtools.js` at https://github.com/sphinx-doc/sphinx/blob/bb74aec2b6aa1179868d83134013450c9ff9d4d6/sphinx/themes/basic/static/searchtools.js#L65

Can you update the theme to set that attribute and let me know if that makes it work?

I have a testing project called `test-builds` that's using the new beta addons and after installing the `sphinx-rtd-theme==2.0.0rc4` that official supports Sphinx 7.2.x I was able to make the search work properly: https://test-builds.readthedocs.io/en/manual-integrations/search.html?q=config&check_keywords=yes&area=default

Let me know if that example works for you.

**Comment by pllim** [comment]
I don't grok https://github.com/pydata/pydata-sphinx-theme/blob/main/src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html enough to do a PR. @drammock , any advice? Thanks! 🙏

**Comment by pllim** [comment]
@humitos , does not seem to work still. Example: https://docs.astropy.org/en/latest/search.html?q=coordinates

That query shows no results for me. I also do not see anymore warnings/error on browser dev console, just these:

```
[PST]: Set focus on search field.
[PST]: Changed to auto mode using the dark theme. pydata-sphinx-theme.js:54
```

The URL above reported to be built with:

* Sphinx 7.2.6
* PyData Sphinx Theme 0.14.4 that was released last week and theoretically should have the patch of https://github.com/pydata/pydata-sphinx-theme/pull/1559

How do we debug this some more? Hope you can advise. Thanks!

**Comment by pllim** [comment]
So, I just noticed something weird. https://jdaviz.readthedocs.io/en/latest/search.html?q=imviz uses pydata-sphinx-theme also and its search works. The only obvious difference I can see is that `jdaviz` docs does not prompt this but `astropy` latest doc does:

```md
This is the latest development version.
Some features may not yet be available in the published stable version.
Read the [stable version of this documentation](https://docs.astropy.org/en/stable/).
```

I don't remember enabling anything that would pop up `This is the latest development version` in `astropy` docs. How do I turn it off, @humitos ?

**Comment by taldcroft** [comment]
I'm not sure this is only confined to the pydata-sphinx-theme update. Search seems to be broken for older versions of the docs:
https://docs.astropy.org/en/v5.0.6/search.html?q=table&check_keywords=yes&area=default

**Comment by taldcroft** [comment]
If I build the docs locally then search is working on that local build.

**Comment by humitos** [comment]
> So, I just noticed something weird. [jdaviz.readthedocs.io/en/latest/search.html?q=imviz](https://jdaviz.readthedocs.io/en/latest/search.html?q=imviz) uses pydata-sphinx-theme also and its search works

Thanks for pointing this project to me. It helped me to track down the issue a little more and I can confirm this is definitely a Read the Docs issue with the new beta addons. Astropy has the beta addons enabled while that project doesn't. Enabling the beta addons on that project makes the search to not work --so, issue found! 💯 


Now, I need to replicate the issue locally to debug it more deeply and write a fix for it. I opened https://github.com/readthedocs/addons/issues/213 to track this and I added it to my sprint.

**Comment by pllim** [comment]
In that case, can astropy choose to disable the beta addon? How do we do that? I will be happy to enable beta addon on another repo that is less high profile if that helps.

**Comment by humitos** [comment]
> In that case, can astropy choose to disable the beta addon? How do we do that?

Yes, you can opt-in/-out from the new beta addons. I wrote the instructions at https://github.com/astropy/astropy/issues/15114#issuecomment-1731777150

> I will be happy to enable beta addon on another repo that is less high profile if that helps.

I'd appreciate if you keep the beta addon enabled on this repository since it has helped us to find different issues already. I understand if you want to disable it, tho, because of these reasons 😄 

I debug the issue, found the problem and opened a PR for it already. We will be able to release it in the next days 🚀

**Comment by humitos** [comment]
I released a fix for this issue and triggered a new build on your `latest` version of the docs. The search works now! 💪🏼 : https://docs.astropy.org/en/latest/search.html?q=coordinates

To fix this issue in older versions hitting the same issue, triggering a new build on them should fix the problem as well. Let me know 😄

**Comment by pllim** [comment]
Thank you, @humitos ! I am rebuilding stable and if that works, I will close this as resolved. 🙏 🙇‍♀️ 

p.s. I was hoping this fix also would magically address https://github.com/astropy/astropy/issues/15695 but it didn't.

**Comment by pllim** [comment]
p.p.s. OK I can keep the beta addons here for now since this is fixed. But if I cannot figure out why warning isn't showing over at #15695, I might still disable it as one of the things to try, but that isn't related to this issue. Thanks again!

**Comment by pllim** [comment]
Hmm... Search works on stable doc now, but I see this on both latest and stable RTD builds on the main index page. It looks like it should not be there. It was not there before. @humitos , do you know what this is?

![Screenshot 2023-12-13 113221](https://github.com/astropy/astropy/assets/2090236/c1ed0db0-4f76-437c-a89e-78432892453a)

**Comment by drammock** [comment]
that's part of the theme. It should go away if you click it, or (I think) if you hit Escape key.

**Comment by pllim** [comment]
@drammock , thanks for the clarification. But what is it for?

**Comment by pllim** [comment]
Since https://github.com/astropy/astropy/issues/15459#issuecomment-1854273582 is unrelated and search is working, I am closing this issue. But would still be nice to know what is the 🔍 `Hide Search Matches` is for. Thanks!

**Comment by drammock** [comment]
it removes all the highlighting on the search term, like seen here:

![Screenshot 2023-12-13 at 11-04-29 Search - PyData Theme 0 14 5dev0 documentation](https://github.com/astropy/astropy/assets/1810515/88fc6707-639e-45d6-abc1-18fbfc5d79b4)

**Comment by pllim** [comment]
Ah, okay. Thanks!

**Comment by humitos** [comment]
> Hmm... Search works on stable doc now, but I see this on both latest and stable RTD builds on the main index page. It looks like it should not be there. It was not there before. @humitos , do you know what this is?

I don't know what that is or where it comes from. I've never seen it before. In fact, if I go to https://docs.astropy.org/en/latest/ I don't see it there either 🙃
