### ISSUE TITLE
ENH: add votable.parquet as format alias for unified I/O

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#15471]
I think it would be beneficial to enable the sub-formats accepted by write methods to be available for read as well, even when the format is automatically recognized as a top-level one.

The one known example is `votable.parquet`, but there may be others, too, where reading `format='votable` works, but `votable.parquet` doesn't.

```
>>> from astropy.table import Table
>>> Table.read('astropy/io/votable/tests/data/parquet_binary.xml', format='votable')
>>> Table.read('astropy/io/votable/tests/data/parquet_binary.xml', format='votable.parquet')
```

**Comment by pllim** [comment]
I am guessing the original PR was https://github.com/astropy/astropy/pull/15281 ? That is already released, so any oversight is technically a bug, and does not hurt to have a change log?

**Comment by pllim** [comment]
(oops comment on the issue instead of PR, sorry for the noise here.)
