### ISSUE TITLE
--doctest-modules short-circuits --doctest-plus

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#1549]
The astropy pytest plugins defined in astropy.tests.pytest_plugins.py define a module that implements a more advanced version of doctest, enabling features like `__doctest_skip__` and `__doctest_requires__`.

However, one of the plugins does this:

```
def pytest_configure(config):
    doctest_plugin = config.pluginmanager.getplugin('doctest')
    if (doctest_plugin is None or config.option.doctestmodules or not
            (config.getini('doctest_plus') or config.option.doctest_plus)):
        return
```

So if the option `--doctest-modules` is passed to py.test, then `config.option.doctestmodules = True` & the definition of the `DocTestModulePlus` class is skipped.

What is the intended behavior of this if clause?

**Comment by weaverba137** [comment]
Is this still an issue?  Maybe the documentation just needs to be updated?

**Comment by pllim** [comment]
@drdavella , is this still an issue now that `doctest-plus` has moved out to be its own pytest plugin?

**Comment by drdavella** [comment]
Yes, it appears that this logic was unchanged when the plugin was moved to a separate repo: https://github.com/astropy/pytest-doctestplus/blob/c812c7edd207732d2491b0a0f43e027c8db04de3/pytest_doctestplus/plugin.py#L75-L78

**Comment by pllim** [comment]
Moved to astropy/pytest-doctestplus#25
