### ISSUE TITLE
Wheel building CI is run on user forks

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#15510]
### Description

I think this is not intended, but unlike regular CI, wheel building is also run on user branches. This is because the start of `ci_workflows.yml` differs from that of `publish.yml`:
https://github.com/astropy/astropy/blob/d36501b300e9fcf3d386e33c8fdce9f466e2b3a5/.github/workflows/ci_workflows.yml#L3-L10

vs

https://github.com/astropy/astropy/blob/d36501b300e9fcf3d386e33c8fdce9f466e2b3a5/.github/workflows/publish.yml#L3-L9

I think we should make those the same...

**Comment by pllim** [comment]
Specifying branch does not stop the CI from running. You have to turn it off in your fork.

* https://github.com/orgs/community/discussions/26704
* https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow

I think only old forks have this problem. Newer forks have Actions automatically disabled.

**Comment by pllim** [comment]
In some jobs, we have a repo name check but we do not require it for all the jobs because maybe sometimes you want to run some tests in your fork first before opening PR, etc.

https://github.com/astropy/astropy/blob/d36501b300e9fcf3d386e33c8fdce9f466e2b3a5/.github/workflows/publish.yml#L36

**Comment by mhvk** [comment]
OK, thanks. Obviously, I have an "older" fork...  Since my diagnosis was rather badly wrong, I'll close this.
