### ISSUE TITLE
RTD builds fail because of `navigation_with_keys`

### ISSUE THREAD

**Issue by eerovaher** [astropy/astropy#15531]
### Description

The documentation builds on RTD have started failing with the following warning: ``WARNING: The default value for `navigation_with_keys` will change to `False` in the next release. If you wish to preserve the old behavior for your site, set `navigation_with_keys=True` in the `html_theme_options` dict in your `conf.py` file.Be aware that `navigation_with_keys = True` has negative accessibility implications:https://github.com/pydata/pydata-sphinx-theme/issues/1492``. 

See e.g. the build log for the latest commit on `main`: https://readthedocs.org/api/v2/build/22342914.txt

**Comment by pllim** [comment]
Thanks for reporting this! Should be fixed in #15532
