### ISSUE TITLE
Inconsistent kwarg and property names in stretches

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#15534]
Some stretch classes have inconsistently named keyword arguments and properties. For instance:

```
In [33]: ls = LogStretch(a=100)

In [34]: ls.exp
Out[34]: 100
```

In general it is good practice to have these be the same so we really should have ``ls.a``. If we wanted to fix this, I think the best one to change is the property since users are more likely to just set it via the kwarg than via the property.

@larrybradley - should we try and fix/deprecate in time for v6.0.0?

**Comment by larrybradley** [comment]
I should be able to do this by tomorrow.

**Comment by astrofrog** [comment]
Perfect, thank you!
