### ISSUE TITLE
DOC: Broken link in change log fragment

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15550]
`docs/changes/coordinates/15121.feature.rst` currently contains this:

```rst
Support Numpy broadcasting over frame data and attributes. See
:ref:`whatsnew-6.0-broadcasting-frame-attributes`.
```

This links to v6.0 What's New that now only exists in v6.0.x branch, not in v6.1.x (current `main`), resulting in broken RTD build. Example log: https://readthedocs.org/projects/astropy/builds/22389898/

@saimn , how best to fix this without messing up the change log? 🙏 

cc @lpsinger @mhvk from #15121

**Comment by lpsinger** [comment]
See #15551.

**Comment by saimn** [comment]
Hmm yeah it's a bit annoying but with the current procedure the whatsnew page for the current version is missing until the final release.
