### ISSUE TITLE
Rolling reminder: Update active branches in SECURITY.md

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15555]
There is a table in `SECURITY.md` stating which branches we currently accept security reports/patches for. This needs to be updated every time we change the branches we support as per https://github.com/astropy/astropy-APEs/blob/main/APE2.rst and https://github.com/astropy/astropy-APEs/blob/main/APE21.rst .

**Comment by saimn** [comment]
It's already mentioned in [Post-Release procedures](https://docs.astropy.org/en/latest/development/releasing.html#post-release-procedures) so no need for a dedicated issue ?

**Comment by pllim** [comment]
Oh oops, forgot about that. Sorry!
