### ISSUE TITLE
Table.show_in_notebook doesn't work in jupyter lab 3 and up

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#15566]
### Description

When I run `show_in_notebook()` on a table I get a full plain text listing of the table, not a paginated one.

### Expected behavior

Paginated table

### How to Reproduce

1. GEt astropy 5.3.x
2. Then run the code below 
3. No pagination occurs.  There is an error in the javascript browser console, included below the code snippet.

```python
from astropy.table import Table
t = Table()
t['name'] = ['larry', 'curly', 'moe', 'shemp']
t['flux'] = [1.2, 2.2, 3.1, 4.3]
t.show_in_notebook(display_length=2)
```

### javascript console

```
VM157:15 Uncaught ReferenceError: require is not defined
    at <anonymous>:15:1
    at t.attachWidget (jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:1594563)
    at t.insertWidget (jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:1593914)
    at j._insertOutput (jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:925250)
    at j.onModelChanged (jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:922427)
    at m (jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:1560565)
    at Object.l [as emit] (jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:1560225)
    at e.emit (jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:1558470)
    at c._onListChanged (jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:918850)
    at m (jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:1560565)
```

### Versions

```
macOS-13.5.2-arm64-arm-64bit
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]
astropy 5.3.4
Numpy 1.26.0
pyerfa 2.0.1.1
Scipy 1.11.3
Matplotlib 3.8.0
```

**Comment by pllim** [comment]
What are the versions of your Jupyter stack? Also did you try with 6.0.dev? Thanks!

**Comment by saimn** [comment]
I think recent versions of `jupyter notebook` are based on `jupyter lab`, which doesn't use requirejs to load JavaScript libraries...

**Comment by rag-hav** [comment]
Unable to reproduce with 6.0.0 dev

**Comment by taldcroft** [comment]
I can reproduce this on Mac using astropy main 6.1.dev151+g7ab3296cb3 and jupyter lab 3.5.2. However, using VS code notebook the `show_in_notebook()` method works as expected.

**Comment by taldcroft** [comment]
Triage:
- priority-medium

This affects user experience in a particular environment but does not cause a crash or incorrect code results. Users can typically examine the table in a different way if need be.

**Comment by saimn** [comment]
> I got the correct behaviour every time.

@neutrinoceros - hmm do you get a clickable/searchable table ? you can try `t.show_in_browser(jsviewer=True)` which gives an interactive table in a new HTML page, `show_in_notebook` should give the same in the notebook.
And I get the same js error as above (`require is not defined`), because as I said jupyterlab doesn't use requirejs.

**Comment by neutrinoceros** [comment]
>  hmm do you get a clickable/searchable table ? 

@saimn 🤦🏻‍♂️ ... I didn't get that was the problem. In fact I don't get pagination in *any* of the envs I reported yesterday !

> you can try t.show_in_browser(jsviewer=True) which gives an interactive table in a new HTML page

Excellent, thank you !

> And I get the same js error as above (require is not defined), because as I said jupyterlab doesn't use requirejs.

same here. To be exact the error I see in my setup is `ReferenceError: Can't find variable: require` but this seems to be the exact same problem.
