### ISSUE TITLE
KeyError: 'dataURL'

### ISSUE THREAD

**Issue by 0J3lack0** [astropy/astropy#15575]
### Description

Hello, I've been using the 'lightkurve' library that utilizes 'astropy' to download and analyze star data for about 2 years. Today, when I tried to download star data on my personal computer, I encountered an issue. The code I'm using is:
```
import lightkurve as lk
star =  'TIC176281431'
catalogTIC = Catalogs.query_object(star, catalog="TIC", radius=0.001)
search_result = lk.search_lightcurve ( star, mission='TESS', author='SPOC', exptime=120)
lc_tess = search_result[0]
```

The error I received is:

```
/usr/local/lib/python3.10/dist-packages/astropy/table/table.py in __getitem__(self, item)
    262         """
    263         if isinstance(item, str):
--> 264             return OrderedDict.__getitem__(self, item)
    265         elif isinstance(item, (int, np.integer)):
    266             return list(self.values())[item]
KeyError: 'dataURL'
```

I thought the issue might be related to the library on my computer. I updated the libraries (astropy, lightkurve, etc.), but I still get the same error. Later, I tried to run the code on Google Colab, and I encountered the same error. Do you have any ideas about this issue?"

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions
On Colab
Linux-5.15.120+-x86_64-with-glibc2.35
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
astropy 5.3.4
Numpy 1.23.5
pyerfa 2.0.1.1
Scipy 1.11.3
Matplotlib 3.7.1

On my pc
Windows-10-10.0.22621-SP0
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
astropy 5.3.4
Numpy 1.26.0
pyerfa 2.0.0
Scipy 1.11.3
Matplotlib 3.8.1

**Comment by louis-e** [comment]
I do not have a solution to that, but I just want to mention that this error is occuring for me too. Glad to hear I'm not the only one.

**Comment by saimn** [comment]
Seems to be an issue in lightkurve (https://github.com/lightkurve/lightkurve/issues/1377, fixed in https://github.com/lightkurve/lightkurve/pull/1380).
