### ISSUE TITLE
[v6.0.0rc1] docs failure because of dev docs

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#15594]
### Description

The build on the 6.0.0rc1 tag failed :
https://readthedocs.org/api/v2/build/22507043.txt
due to
```
/home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/v6.0.0rc1/docs/index.rst:34: WARNING: toctree contains reference to excluded document 'development/index'
...
/home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/v6.0.0rc1/docs/index.rst:93: WARNING: 'any' reference target not found: development/index
```
probably related to the reorganization of toctree/index pages with the new theme, and the magic happening to exclude dev docs from releases.

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by pllim** [comment]
Oh no, my bad!

https://github.com/astropy/astropy/blob/1ae26ae0fcf5b8ffe0563d73be7787e9c835bf0e/docs/conf.py#L231-L232

**Comment by pllim** [comment]
I think https://github.com/astropy/astropy/pull/15595 will fix this but I dunno how to prove it.

**Comment by saimn** [comment]
> Oh no, my bad!

No worries, it may be my bad as well, and anyway the problem is this complicated and fragile setup to exclude dev docs and having code that is run only on a tagged version. So I guess we will have to make a second rc for this.
