### ISSUE TITLE
Non-Bug: Astropy 6 needs cython 3 to build

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#15616]
### Description

Debian is still on Cython 0.29, so we currently can't build Astropy 6rc1 out of the box. For an experimental package, I could just create the cythonized files manually and add them; this would however not be an option for the release.

I don't think it is worth the effort to "backport" Astropy to be compatible to Cython 0.29 - efforts should be rather put into packaging Cython 3 for Debian; it is anyway required for other packages as well now (@yt-project).

One option could be to revert #15402 in a temporary Debian patch until we got Cython updated; could that work? Or are there other ideas? If not, I would rather delay the Debian packaging of the final Astropy 6 release and see how I can help updating our Cython.

**Comment by pllim** [comment]
To maintain v6.0.x for both Cython 3 and 0.29 at the same time would not be ideal. What is the timeline of getting Cython 3 into Debian? Can this be done in a week or two? Or does it take a few months?

**Comment by olebole** [comment]
Unfortunately, there is no timeline - each Debian Developer is free to plan it as it fits to their schedule. Cython is however team maintaine, so in principle I could prepare a new release as well. However, I did not look into the details yet.
My plan is to "somehow" get the RC packaged (with compromises) to have some feedback, and then to look into how to solve the Cython problem.

**Comment by saimn** [comment]
I guess Cython will be updated soon enough so it's not a problem for normal packaging, but if you want to patch I think all that is needed is to remove the `NPY_NO_DEPRECATED_API` directives.

**Comment by olebole** [comment]
There are plans to upload cython 3.0.5 in the course of transitioning Debian to Python 3.12, so I still wait and have the directives as fallback in mind. Thank you!

**Comment by olebole** [comment]
To keep you up-to-date: Cython 3.0.5 was uploaded to Debian experimental, and Astropy 6.0RC2 builds fine with it. So, we have a clear path :railway_track:

**Comment by saimn** [comment]
Thanks for the update @olebole, closing this ticket then.
