### ISSUE TITLE
IERS 2000A format has changed

### ISSUE THREAD

**Issue by ageofabenius** [astropy/astropy#15618]
### Description

The file format for the 2000A IERS EOP file has changed, as described in this message: https://datacenter.iers.org/data/2/message_490.txt

```
************************************************************************
IERS Message No. 490                                    October 09, 2023
************************************************************************


Changes to IERS EOP xml and csv formats and addition of JSON format


With the implementation of the IERS 2020 C04 system, the parameters
x rate, y rate, sigma x rate, and sigma y rate were also added to this
data series (see IERS Message No. 471).

[...]

The headers of the csv files will be extended for all EOP products by
the mentioned parameters, even if corresponding values are currently
only available for the product "EOP 20 C04 (IAU2000A) - one file
(1962-now)".

[...]

If you process csv files of any EOP products or the xml file of the
product "EOP 20 C04 (IAU2000A) - one file (1962-now)", you should check
if your routines still work correctly with the new format and adapt them
if necessary. For this purpose, we have provided sample files in the new
format at the following address:
https://datacenter.iers.org/products/eop/new_format_examples/

[...]

```

This is causing issues, preventing proper loading of the IERS_A table.

### How to Reproduce

```python
import astropy
from astropy.utils.iers import conf
astropy.utils.iers.IERS_A.open(FILEPATH)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/utils/iers/iers.py", line 278, in open
    cls.iers_table = cls.read(**kwargs)
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/utils/iers/iers.py", line 633, in read
    iers_a = super().read(file, format="cds", readme=readme)
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/io/registry/core.py", line 218, in read
    data = reader(*args, **kwargs)
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/io/ascii/connect.py", line 19, in io_read
    return read(filename, **kwargs)
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/io/ascii/ui.py", line 426, in read
    dat = reader.read(table)
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/io/ascii/cds.py", line 357, in read
    return super().read(table)
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 1464, in read
    table = self.outputter(self.header.cols, self.meta)
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 1183, in __call__
    self._convert_vals(cols)
  File "/home/bdavidson/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 1120, in _convert_vals
    raise ValueError(f"Column {col.name} failed to convert: {last_err}")
ValueError: Column year failed to convert: invalid literal for int() with base 10: 'MJ'
```
A copy of the previous format and new format for reference (file extensions added for GitHub to allow uplink):
[old_finals2000A.all.csv](https://github.com/astropy/astropy/files/13368723/old_finals2000A.all.csv)
[new_finals2000A.all.csv](https://github.com/astropy/astropy/files/13368721/new_finals2000A.all.csv)

### Versions

>>> import platform; print(platform.platform())
Linux-6.2.0-35-generic-x86_64-with-glibc2.35
>>> import sys; print("Python", sys.version)
Python 3.9.10 (main, Jun 13 2022, 14:50:28) 
[GCC 11.2.0]
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.3.4
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.22.0
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.1
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.9.0
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.5.2

**Comment by pllim** [comment]
Hi. Just for completeness, which URL did you download the "new" stuff from?

**Comment by ageofabenius** [comment]
Hi, the new format was downloaded from:

https://datacenter.iers.org/data/csv/finals2000A.all.csv

**Comment by pllim** [comment]
Thanks, but that URL does not match what we pull from here:

https://github.com/astropy/astropy-iers-data/blob/702a075573d490fa8da6da651eac1a5980f30388/astropy_iers_data/__init__.py#L24

https://datacenter.iers.org/data/9/finals2000A.all

@mhvk or @astrofrog , can you please advise? Thanks!

**Comment by ageofabenius** [comment]
Ah, sorry.  My mistake.  I was using the wrong URL.

Re-reading the message (emphasis mine):
> these parameters will also be included in the **xml, csv, and HTML** files
starting November 6, 2023

It looks like this doesn't affect the file at https://datacenter.iers.org/data/9/finals2000A.all.

I can confirm that it does still work properly with https://datacenter.iers.org/data/9/finals2000A.all.
