### ISSUE TITLE
For downstream maintainers: astropy-dev + numpy-dev now also needs pyerfa-dev

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15638]
If you start to see errors like this downstream in a job that pulls in astropy 6.1.dev and numpy 2.0.dev:

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0.dev0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled against NumPy 2.0.
```

You also need to install pyerfa-dev for that job from https://anaconda.org/liberfa/pyerfa like this:

```
pip install -U --pre -i https://pypi.anaconda.org/liberfa/simple pyerfa
```

**Comment by bsipocz** [comment]
Food for thoughts: make it possible to use and import astropy without pyerfa. E.g. in pyvo we don't use it, yet now we need to make sure we include the dev pyerfa in our testing. Having to dive into dev of indirect dependencies is far from elegant, and the only iers usage I see is to turn off the auto download in conftest 🤦‍♀️ 

```
from astropy.utils.iers import conf as iers_conf
iers_conf.auto_download = False
```

**Comment by pllim** [comment]
For completeness, this is when it became required:

* https://github.com/astropy/astropy/pull/10329

**Comment by bsipocz** [comment]
Yes, I agree the problem is more a philosophical one, but nevertheless, issues with iers/erfa is coming back often and result in ugly workarounds at each time.

**Comment by pllim** [comment]
With recent releases, I think this no longer applies.
