### ISSUE TITLE
Fitting CompoundModel with units does not fit to data

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#15656]
### Description

Fitting a compound model with multiplied units does not seem to perform an actual fit.
`test_fit_multiplied_compound_model_with_mixed_units` in fact shows that the init model with unmodified parameters is returned (see https://github.com/astropy/astropy/pull/12475/files#r1406941749).

### Expected behavior

Fitting should return model parameters consistent with the case without units and fitted to the data.

### How to Reproduce

With the example functions from the test:
```python
import numpy as np
from astropy import units as u
from astropy.modeling.models import Linear1D
from astropy.modeling.fitting import LevMarLSQFitter

fitter = LevMarLSQFitter()
x = np.linspace(0, 1, 101) * u.s
y = np.linspace(5, 10, 101) * u.m * u.kg / u.s

m1 = Linear1D(slope=5*u.m/u.s/u.s, intercept=1.0*u.m/u.s)
m2 = Linear1D(slope=0.0*u.kg/u.s, intercept=10.0*u.kg)
truth = m1 * m2
fit = fitter(truth, x, y)

print(truth(x[::10]))
# [10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60.] kg m / s
print(fit(x[::10]))
# [10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60.] kg m / s
print(y[::10])
# [ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ] kg m / s
print(fit.parameters)
# [ 5.,  1.,  0., 10.]
print(fitter.fit_info['nfev'], fitter.fit_info['ierr'])
# 5, 4
print(fitter.fit_info['message'])
# 'The cosine of the angle between func(x) and any column of the
#  Jacobian is at most 0.000000 in absolute value'

# Compare with the results when running with units stripped:

m1_val = Linear1D(slope=5, intercept=1.0)
m2_val = Linear1D(slope=0.0, intercept=10.0)
truth_val = m1_val * m2_val
fit_val = fitter(truth_val, x.value, y.value)

print(truth_val(x.value[::10]))
# [10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60.]
print(fit_val(x.value[::10]))
# [ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]
print(fit_val.parameters)
# [1.84643460e+00 1.84643460e+00 1.30706508e-12 2.70792153e+00]
print(fitter.fit_info['nfev'], fitter.fit_info['ierr'])
# 66 2
print(fitter.fit_info['message'])
# The relative error between two consecutive iterates is at most 0.000000
```
So on the compound model with units the fitter returns after only 5 evaluations with unchanged parameters, but claiming success (ierr=1...4 indicate "solution was found").
Without, after 66 evaluations an exact fit to the input `y` values is found.

I suspect that somewhere in the unit fixes from #12475 the function values from the init model are passed on instead of the input values (to be fitted to), but need further investigation.

### Versions

Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ]
astropy 6.1.dev88+gc5b3fe5b4a.d20231115 (same for 5.3.4)
Numpy 1.26.2
pyerfa 2.0.1.1
Scipy 1.11.4
Matplotlib 3.8.2

**Comment by pllim** [comment]
@dhomeier , we usually do not milestone an issue unless it blocks a release. Does this bug block v6.0.1?

**Comment by dhomeier** [comment]
Probably not. Since no one seems to have noticed in the past 2 years, I doubt that fitting these kind of models is used very much.

**Comment by pllim** [comment]
Just to be sure, @dhomeier , can you please double check? Thanks!

**Comment by dhomeier** [comment]
Will double-check. #16678 does not directly reference this, but it looks like the changes made to `test_compound.py` do address my remarks https://github.com/astropy/astropy/pull/12475/files#r1406941749.
