### ISSUE TITLE
Changing configuration variable ``log_warning``  at run time does not affect logging of warnings (in 0.3dev)

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#1568]
Instead, the value in the configuration file is the value used.

The code below should reproduce the bug as long as there is a configuration file that sets `log_warning`. It flips the value of `log_warning` at runtime and later on generates a warning from `astropy.io.fits` by writing to the same FITS file twice, the second time with `clobber=True`. 

This affects 0.3dev...I didn't try it with 0.2.4.

The expected outcome of this example output depends on the setting of `log_warning` in your config file:
- If `log_warning` is `True` in the config file the script changes it to `False` at runtime and sets up a basic root logger that should never display a message because warnings aren't logged, but it does.
- If `log_warning`is `False` in the config file the script changes it to `True` at runtime and sets up a basic root logger that should display twice--once when I deliberately `warn()` and once when the FITS warning is generated, but it only displays once.

``` python
from astropy.logger import LOG_WARNINGS

import logging

# set log_warnings in config file to True and save it...
if LOG_WARNINGS():
    # try resetting log_warning to false...
    LOG_WARNINGS.set(False)
    # and set up a pithy format for logs
    logging.basicConfig(format='This message SHOULD NOT DISPLAY')
else:
    # try resetting log_warning to true...
    LOG_WARNINGS.set(True)
    # and set up a pithy format for logs
    logging.basicConfig(format='This message SHOULD DISPLAY TWICE')
    logging.warn('Warning')

# generate a warning by writing to a FITS file that
# already exists
import py.path
tmpdir = py.path.local.mkdtemp()
file_path = tmpdir.join('a.fits')
from astropy.io import fits
hdu = fits.PrimaryHDU()
hdu.writeto(file_path.strpath)
# write again with clobber=True to generate a warning
hdu.writeto(file_path.strpath, clobber=True)

# clean up
tmpdir.remove()
```

**Comment by pllim** [comment]
Fast forward 7 years, I cannot find `LOG_WARNINGS` in the code anymore, so is this still relevant? In 4.1.dev, I get:

```
>>> from astropy.logger import LOG_WARNINGS                                                     
ImportError: cannot import name 'LOG_WARNINGS' from 'astropy.logger' (.../astropy/logger.py)
```
