### ISSUE TITLE
MNT: Any objection to using the `no-commit-to-branch` pre-commit hook ?

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#15694]
### Description

disclaimer: maybe people have strong opinions here so I'd rather open an issue first.

`no-commit-to-branch` is part of [the basic hook bundle for `pre-commit`](https://github.com/pre-commit/pre-commit-hooks) and prevents accidentally committing to `main/master/<insert custom branch name>` directly (of course marging is still allowed !). I found myself accidentally committing to `main` locally recently so I was wondering if there was any objection to using this hook ? (I haven't found any historical discussion about it, maybe I didn't look hard enough ?)

Note that committing to `main` is still possible even with `pre-commit` installed locally and this hook included, it just needs to be done consciously as `git commit ... --no-verify`. 

Please let me know if that's an acceptable addition to the pre-commit toolbelt.

**Comment by eerovaher** [comment]
I can't think of a good reason why anyone would want to commit directly to their local `main` branch. However, if it ever happens that someone forgets to create a new feature branch for their work and accidentally commits to `main` instead then that is always trivial to recover from, so this hook wouldn't add much value.

**Comment by neutrinoceros** [comment]
I don't mean to point fingers but I _think_ I saw @pllim committing directly to `main` recently, which is the main reason I'm asking.
>  if it ever happens that someone forgets to create a new feature branch for their work and accidentally commits to main instead then that is always trivial to recover from, so this hook wouldn't add much value.

You're right, recovering isn't complicated, and indeed this hook doesn't bring *much* value, however:
- committing to main is a very common mistake amongst beginners
- I don't consider myself a beginner and I still did it. I think I'm so used to this hook that I instinctively *assume* any repo with `pre-commit` enable has it.

**Comment by pllim** [comment]
Our upstream main branch is protected already. And yes, occasionally I commit directly to fix something that cannot be checked via PRs but it is very rare and requires admin override.

We actually used to ask contributors to delete their fork's main branch right off the bat to avoid such things but it was more trouble than help, so I think we got rid of that after many years. Now there is a sentence in https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#about-names-in-git that says, "As a result, you should never do any work in your main branch, `main`. Always work on a branch instead."

**Comment by pllim** [comment]
I am not a fan of adding more pre-commits for random checks. People actually make PRs from their fork's main branch sometimes (maybe they just found it convenient via the GitHub UI or something). It is not against the law to do so and the contribution might be valid.
