### ISSUE TITLE
TST: astropy.units' tests fail against numpy 2.0 dev 

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#15690]
### Description

See for instance https://github.com/astropy/astropy/actions/runs/7127086443/job/19406282222
It looks like this is caused by new NEP-18 (array functions) compatible functions being introduced these last couple days:
- https://github.com/numpy/numpy/pull/24940
- https://github.com/numpy/numpy/pull/25088
- https://github.com/numpy/numpy/pull/25101
- https://github.com/numpy/numpy/pull/25145
- https://github.com/numpy/numpy/pull/25079
- https://github.com/numpy/numpy/pull/25086

I'm not currently able to tackle this problem as easily as I'd like because of another issue: it seems that nightly wheels for macOS are lagging behind, so this doesn't reproduce trivial on my machine. However I should be able to build numpy from source and provide a fix later today.

**Comment by neutrinoceros** [comment]
Ok here's my script to reproduce this locally even without pre-built binaries

```
set -euxo pipefail

# spin up env
python -m venv .venv
source .venv/bin/activate
python -m pip install -U pip

# build numpy from source
python -m pip install git+https://github.com/numpy/numpy.git

# build pyerfa from source against numpy 2.0 dev
python -m pip install setuptools setuptools_scm wheel jinja2
python -m pip install git+https://github.com/liberfa/pyerfa.git --no-build-isolation

# build astropy
pushd ../../
python -m pip install extension-helpers Cython
python -m pip install -e ".[test]" --no-build-isolation

# run test
pytest astropy/units/tests/test_quantity_non_ufuncs.py -vvv
```

**Comment by pllim** [comment]
Does that mean the segfault is gone?

**Comment by neutrinoceros** [comment]
> Does that mean the segfault is gone?

yes it is. I'm working on adding the missing code in `astropy.units`

**Comment by neutrinoceros** [comment]
quick note that `astropy.units.tests.test_quantity_non_ufuncs.CoverageMeta` just grew some blindspots, as it is currently not able to distinguish `np.linalg.outer` from `np.outer`. I'll probably need to fix that as well to pass CI.
