### ISSUE TITLE
TST: astropy.units completion tests behave differently for functions with unique names

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#15692]
### Description

While working on #15690, I think I found a "vulnerability" in how we test for test completion for NEP 18 (array function) wrapping.
Specifically, the issue is that  `astropy.units.tests.test_quantity_non_ufuncs.CoverageMeta` is currently not able to distinguish tests aim to cover `np.linalg.outer` from the ones that are targeted at `np.outer` because it only care about the function name, not the exact namespace it lives in.
By construction, this will not show up in tests, but I believe it'd be a good idea to make this meta test more robust.

**Comment by neutrinoceros** [comment]
> By construction, this will not show up in tests

I was wrong, it *does* show up. Now let's see why.

**Comment by neutrinoceros** [comment]
related: #15469

**Comment by mhvk** [comment]
I think you are right, we should go to `test_{module_name}_{function_name}` generally (if we really want to be clever, the module name could be an attribute of the test class, but that's an implementation detail).

**Comment by neutrinoceros** [comment]
This is not critical but as I'm neck-deep into the units module these days, I might as well pick it up now !

**Comment by neutrinoceros** [comment]
retitled the issue for posterity
