### ISSUE TITLE
Convertion of some complicated EM Gauss units

### ISSUE THREAD

**Issue by Firestar-Reimu** [astropy/astropy#15722]
### What is the problem this feature will solve?

```
omega_B = c.e.gauss * (0.1 * u.G)/(1e4 * c.m_e.cgs * c.c.cgs)
```
This is the rotate frequency of a $\gamma=10^4$ electron in a $B=0.1\mathrm{G}$ magnetic field:
$\omega_B = \frac{eB}{\gamma mc}$
```
omega_B
Out[24]: <Quantity 175.88200108 Fr G s / (cm g)>
```
This should be equivalent to `175.88200108 Hz`

But: `UnitConversionError: 'Fr G s / (cm g)' and 'Hz' (frequency) are not convertible`

### Describe the desired outcome

Use CGS EM units like `Fr` and `Gauss` as units from `cm, g, s` to calculate, then give the answer as the simplest form. Also in SI units like `Hz J s --> J`. Furthermore, we can have like transformation like `1 s2 Fr G J / (kg m) --> 1e-5 J`

**Comment by mhvk** [comment]
Sadly, this is not an easy problem because the meaning of the franklin/statcoulomb depends on context. We have long wanted to have some type of context manager to solve this - see #4359. It is not an easy problem, though, and it needs someone to find the time to really think through a good API and the implement it...

**Comment by pllim** [comment]
Is this a duplicate of #4359 ?

**Comment by mhvk** [comment]
Yes, at least of the problems before that led to #4359. @Firestar-Reimu - maybe it is an idea to copy your example to #4359 as something one would want to be able to do?

**Comment by Firestar-Reimu** [comment]
Thanks! It is sad to find that it has been 10 years and this problem has not fixed
