### ISSUE TITLE
Use ruff format instead of black pre-commit hook?

### ISSUE THREAD

**Issue by MridulS** [astropy/astropy#15757]
### Blocked by

Modification to https://github.com/astropy/astropy-APEs/blob/main/APE20.rst

* https://github.com/astropy/astropy-APEs/pull/90

### What is the problem this feature will solve?

The [ruff formatter ](https://docs.astral.sh/ruff/formatter/) is in "production-ready beta" now, and it's supposed to be a [99.9% drop in replacement for black](https://docs.astral.sh/ruff/formatter/#black-compatibility). Astropy currently uses ruff for linting and black for formatting with pre-commit hooks, moving to ruff should help removing one hook and also making the codestyle tox step run quickly. I ran the ruff formatter on astropy and it made minimal changes (~35 places).

### Describe the desired outcome

Remove black from pre-commit-hooks and add ruff format.

**Comment by neutrinoceros** [comment]
Hi @MridulS, a migration plan was previously pitched by @eerovaher in November's telecon (see the running notes https://docs.google.com/document/d/15JSFh3OMF9Iz6ov3q_xxGO_BL8hRnuse4IMUrqEIvcg/edit?pli=1#heading=h.h1eip4swqth0)

**Comment by taldcroft** [comment]
For the record I am very much in favor of migrating to ruff to replace black. 

As noted, APE-20 will need modifications. It is too bad we didn't appreciate at the time that APE-20 was about "black formatting" (i.e. a style of formatting) instead of an implementation of black formatting using the `black` package.

**Comment by neutrinoceros** [comment]
@pllim why did you apply the "upstream fix required" label ?

**Comment by pllim** [comment]
Because in https://github.com/astropy/astropy/issues/15757#issuecomment-1862895918 "As noted, APE-20 will need modifications."

**Comment by neutrinoceros** [comment]
Oh I see, I didn't get that APEs were "upstream", but that makes sense !

**Comment by pllim** [comment]
Upstream in a sense that the changes to APE has to be proposed, debated, accepted, and merged first before we can proceed here. 😅

**Comment by taldcroft** [comment]
https://github.com/astropy/astropy-APEs/pull/90

**Comment by pllim** [comment]
Weird that https://github.com/astropy/astropy/pull/16029 didn't auto close this.
