### ISSUE TITLE
BUG: A broken test in table/tests/test_pprint.py

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#15753]
### Description

I discovered that this test was (supposedly by mistake ?) marked as a `pytest.fixture` in #8577, without being used
https://github.com/astropy/astropy/blob/7a7b6ba6a1fc65aeb4585819d3c4e50b97631dda/astropy/table/tests/test_pprint.py#L309-L316

Effectively it's never called, so it may not come as a surprise that removing the decorator reveals that it's in fact not passing.
I suspect a bug is hiding in the code base that should have been caught by this test, or the test is just broken. I will take a deeper look soon.

**Comment by pllim** [comment]
Hmm maybe @broulston could clarify if they are still available? Otherwise looks like @bsipocz and @taldcroft reviewed and approved https://github.com/astropy/astropy/pull/8577 .

**Comment by taldcroft** [comment]
Oops! I think that this:
```
 assert len(out) ==  BIG_WIDE_ARR.shape[0] + 3
```
should be:
```
 assert len(out.splitlines()) ==  BIG_WIDE_ARR.shape[0] + 3
```
Worth fixing!
