### ISSUE TITLE
Remove needless functions from an `io.ascii` test helper file

### ISSUE THREAD

**Issue by eerovaher** [astropy/astropy#15782]
### What is the problem this feature will solve?

A helper file in `io.ascii` tests contains three functions that serve little purpose: https://github.com/astropy/astropy/blob/fefe2261fcf09751d052d80bd8143e72f18f6aea/astropy/io/ascii/tests/common.py#L27-L37

### Describe the desired outcome

The aforementioned functions should be removed and any tests still using them should be updated accordingly. Pull requests targeting one or more functions are welcome.

Potential contributors can have a look at #16644 that removed the helper functions from one file and use that as an example.

### Additional context

`assert_equal()` and `assert_true()` should be inlined, but `assert_almost_equal(a, b)` should be replaced with [`np.testing.assert_allclose(a, b)`](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html#numpy.testing.assert_allclose) instead of `assert np.allclose(a, b)` because the dedicated testing function produces a better error message if the check fails.

### Performed removals

- [ ] `assert_equal()`
- [ ] `assert_almost_equal()`
- [ ] `assert_true()`

**Comment by pllim** [comment]
Looks like @taldcroft added these a long time ago. Are other `io.ascii` maintainers on board with this? I don't see any link to previous discussions.

**Comment by taldcroft** [comment]
Fine by me. I would expect there was a reason for these functions in the days of yore, but I don't see a reason now.

**Comment by Rohit-Pujari** [comment]
Can i solve this issue? (i am a beginner so i will try)

**Comment by pllim** [comment]
@Rohit-Pujari , thank you for your interest! There is no need to ask for permission. But please do read through https://docs.astropy.org/en/latest/index_dev.html if you are new.

**Comment by Rohit-Pujari** [comment]
i have raised the pull request,please inform me what i have did wrong

**Comment by vagish-yadav** [comment]
Hi is this issue still open to resolve !!??

**Comment by eerovaher** [comment]
I re-added the `good first issue` label because now there is an example pull request potential contributors can follow: #16644.
