### ISSUE TITLE
TypeError: unknown ufunc vecdot (9 failures with numpy 2.0.dev)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15784]
New error popped up today in devdeps. Something to do with `vecdot`. 9 failures total.

Example log: https://github.com/astropy/astropy/actions/runs/7303429253/job/19903937084?pr=15783

@mhvk or @neutrinoceros ? 🙏

**Comment by mhvk** [comment]
Yes, that is my https://github.com/numpy/numpy/pull/25416 - I'll make a fix!

**Comment by mhvk** [comment]
#15785 should be a fix...
