### ISSUE TITLE
FERMI LAT data analysis

### ISSUE THREAD

**Issue by NithyaSathyan** [astropy/astropy#15796]
### Description

I have installed fermipy using miniconda python 3.6 version. While doing FERMI LAT analysis using fermipy I encounter an error as follows : 
from astropy.coordinates.angle_utilities import angular_separation
ModuleNotFoundError: No module named 'astropy.coordinates.angle_utilities'
How to fix this

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by neutrinoceros** [comment]
hi @NithyaSathyan
I'm guessing you must be using a version of astropy that's more recent than the example you took inspiration from.
Here's how you'd import this function with current and recent versions:
```python
from astropy.coordinates.angles import angular_separation
```

**Comment by NithyaSathyan** [comment]
Hii..
I haven't installed astropy directly. Instead I installed miniconda for
python 3.9 version for doing the FERMI LAT analysis using fermipy.

**Comment by NithyaSathyan** [comment]
Hii..

from astropy.coordinates.angles import angular_separation

This still gives the same error.

**Comment by neutrinoceros** [comment]
Hi @NithyaSathyan, please provide version information as asked as the end of the bug report form.

**Comment by NithyaSathyan** [comment]
I have installed miniconda python 3.9 version. The version for astropy is
shown to be 6.0.0. My science tools version is 2.2 and fermipy version is
1.2

**Comment by neutrinoceros** [comment]
My first suggestion should work with astropy 6.0.0, so I am confused.

Can you run specifically this ?
`python -c "import astropy; print("astropy", astropy.__version__)"`

**Comment by NithyaSathyan** [comment]
When I run the above said, I get
<module 'astropy' from
'/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/astropy/__init__.py'>
6.0.0

**Comment by NithyaSathyan** [comment]
This is the error message that I get while running the fermipy analysis
script :
WARNING: FITSFixedWarning: RADECSYS= 'FK5 '
the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATEREF to
'2001-01-01T00:01:04.184' from MJDREF.
Set MJD-OBS to 54682.655283 from DATE-OBS.
Set MJD-END to 59852.000000 from DATE-END'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py",
line 5196, in setup
    self._bexp = Map.read(self.files['bexpmap'], hdu=hpxhduname)
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/core.py",
line 240, in read
    return Map.from_hdulist(
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/core.py",
line 308, in from_hdulist
    map_type = Map._get_map_type(hdulist, hdu)
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/core.py",
line 339, in _get_map_type
    header = hdu_list[hdu_name].header
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py",
line 390, in __getitem__
    super().__getitem__, self._positive_index_of(key)
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py",
line 857, in _positive_index_of
    index = self.index_of(key)
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py",
line 839, in index_of
    raise KeyError(f"Extension {key!r} not found.")
KeyError: "Extension 'HPXEXPOSURES' not found."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dell/Documents/1H1914-194/xx.py", line 4, in <module>
    gta.setup()
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py",
line 1087, in setup
    c.setup(overwrite=overwrite)
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py",
line 5198, in setup
    self._bexp = Map.read(self.files['bexpmap'])
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/core.py",
line 240, in read
    return Map.from_hdulist(
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/core.py",
line 315, in from_hdulist
    return cls_out.from_hdulist(
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/wcs/core.py",
line 142, in from_hdulist
    wcs_map = cls.from_hdu(hdu, hdu_bands, format=format)
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/wcs/ndmap.py",
line 88, in from_hdu
    geom = WcsGeom.from_header(hdu.header, hdu_bands, format=format)
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/wcs/geom.py",
line 485, in from_header
    axes = MapAxes.from_table_hdu(hdu_bands, format=format)
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/axes.py",
line 1962, in from_table_hdu
    return cls.from_table(table, format=format)
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/maps/axes.py",
line 1980, in from_table
    from gammapy.irf.io import IRF_DL3_AXES_SPECIFICATION
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/irf/__init__.py",
line 6, in <module>
    from .background import Background2D, Background3D
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/irf/background.py",
line 10, in <module>
    from .core import IRF
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/irf/core.py",
line 17, in <module>
    from .io import IRF_DL3_HDU_SPECIFICATION, IRF_MAP_HDU_SPECIFICATION,
gadf_is_pointlike
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/irf/io.py",
line 4, in <module>
    from gammapy.data.hdu_index_table import HDUIndexTable
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/data/__init__.py",
line 3, in <module>
    from .data_store import DataStore
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/data/data_store.py",
line 15, in <module>
    from .observations import Observation, ObservationChecker, Observations
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/data/observations.py",
line 22, in <module>
    from .event_list import EventList, EventListChecker
  File
"/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/gammapy/data/event_list.py",
line 8, in <module>
    from astropy.coordinates.angle_utilities import angular_separation
ModuleNotFoundError: No module named 'astropy.coordinates.angle_utilities'

**Comment by alchzh** [comment]
You need to install either an gammapy version https://github.com/gammapy/gammapy/issues/4972 or an older astropy version

**Comment by NithyaSathyan** [comment]
Hii..
Will downgrading astropy 6.0  lead to compatibility issues with other
packages or code relying on the newer versions ? If so how can that be done
without other dependencies of fermipy?

**Comment by eerovaher** [comment]
If you want to know what versions of dependencies `fermipy` requires then you need to ask that from `fermipy` developers.

**Comment by eerovaher** [comment]
If you need help with figuring out which versions of `astropy` are compatible with the version of `gammapy` you are trying to use then you should ask that from `gammapy` developers.

**Comment by pllim** [comment]
gammapy is at https://github.com/gammapy/gammapy and looks like it is still pretty active though I do not recognize the current active developers.
