### ISSUE TITLE
Simple change: Make "_summary()" a public method for _ImageBaseHDU and _TableBaseHDU

### ISSUE THREAD

**Issue by jw-echelle** [astropy/astropy#15880]
#### General
Underscored methods tend to be seen as private methods. The _summary() is a very useful but marked as private via "_".
Removing the underscore would give it a less hacky feel when using it.

#### Wish
Remove underscore and therefore mark the method as public.

Thank you for your time.
Kind regards

#### Further thinking
The output of _summary() is very neat when writing GUIs.

**Comment by saimn** [comment]
Hi @jw-echelle ,
Could you explain your usecase and how the information is useful ?
Currently this method returns a variable number of arguments (3 to 7) depending on the HDU class, so I don't think this is a practical format for external usage. We could change it to return something more useful, but it would be useful to have an idea of which information is needed.
