### ISSUE TITLE
TST: one failing test with devdeps (possible bug in numpy dev)

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#15884]
### Description

A test started failing with devdeps. See for example
https://github.com/astropy/astropy/actions/runs/7527698298/job/20488361843?pr=15883

I was able to reproduce this locally with numpy dev, so I suspect the cause might be a bug upstream. I'll bisect this more carefully.

### How to Reproduce

Install numpy dev, then build pyerfa + astropy against it, then
```shell
pytest astropy/utils/masked/tests/test_function_helpers.py::TestSpaceFunctions::test_geomspace
```

### Versions

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
```
```
macOS-14.2.1-arm64-arm-64bit
Python 3.12.0 (main, Oct 27 2023, 11:50:57) [Clang 15.0.0 (clang-1500.0.40.1)]
astropy 6.1.dev313+g295ea9ac79
Numpy 2.0.0.dev0+git20240114.b0371ef
pyerfa 2.0.1.2.dev11+gc498084
```
(Matplotlib not installed)

**Comment by neutrinoceros** [comment]
bisects to https://github.com/numpy/numpy/pull/25441 (ping @mhvk)

**Comment by mhvk** [comment]
Hmm, that's very weird - I know I made the logic of `np.geomspace` a bit better, but am very confused why that would affect `Masked`. Will investigate!

**Comment by pllim** [comment]
It is nice to come back to work and see someone else opened an issue and someone else fixed it. Thanks, all! ❤️
