### ISSUE TITLE
Plotting with wcsaxes does not respect matplotlib's unicode_minus

### ISSUE THREAD

**Issue by ntessore** [astropy/astropy#15898]
### Description

The tick formatter for `wcsaxes` does not respect matplotlib's `axes.unicode_minus` setting, producing ticks with a `U+002d HYPHEN-MINUS` (-) sign instead of the visually more appealing and correct `U+2212 MINUS SIGN` (−).

### Expected behavior

Respect the `axes.unicode_minus` setting (which is the default) and produce typographically correct minus signs.

A simple fix is to run the strings produced by `formatter()` through [`matplotlib.ticker.Formatter.fix_minus()`](https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.Formatter.fix_minus).

### How to Reproduce

Plot any `wcsaxes` plot with negative ticks.

### Versions

macOS-10.16-x86_64-i386-64bit
Python 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
astropy 6.0.0
Numpy 1.26.0
pyerfa 2.0.1.1
Scipy 1.11.3
Matplotlib 3.7.2

**Comment by ntessore** [comment]
I don't have the bandwidth to provide a PR with tests, but here's a simple decorator that applies matplotlib's `Formatter.fix_minus()` to the existing functions.

```py
import functools
from matplotlib.ticker import Formatter

def fix_minus(formatter):
    """Decorator to fix minus signs in formatters."""
    @functools.wraps(formatter)
    def fixed_formatter(*args, **kwargs):
        return list(map(Formatter.fix_minus, formatter(*args, **kwargs)))
    return fixed_formatter

...

class AngleFormatterLocator(BaseFormatterLocator):
    ...

    @fix_minus
    def formatter(self, values, spacing, format="auto"):
        ...

...

class ScalarFormatterLocator(BaseFormatterLocator):
    ...

    @fix_minus
    def formatter(self, values, spacing, format="auto"):
        ...
```

**Comment by neutrinoceros** [comment]
Thank you for reporting this and proposing a fix. I'll open a PR to fix this promptly.
