### ISSUE TITLE
TST: Unpin pluggy<1.4 for CircleCI image jobs when we can

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15944]
- [ ] Revert https://github.com/astropy/astropy/pull/15940
- Also see https://github.com/astropy/astropy/pull/15942

https://github.com/astropy/astropy/blob/71061de8a5a84b8b31faf7c55d30ff65ebc77e8e/tox.ini#L67-L68

### Blocked by

- https://github.com/matplotlib/pytest-mpl/issues/216

**Comment by pllim** [comment]
@ConorMacBride said pytest-mpl just needs a new release. 🤞

**Comment by ConorMacBride** [comment]
Sorry for the delay, pytest-mpl `v0.17.0` has just been released! That should be enough to unpin pluggy.
