### ISSUE TITLE
Empty QTable strips units from newly added row

### ISSUE THREAD

**Issue by Seraf-N** [astropy/astropy#15964]
### Description

When adding quantities to an empty previously created `QTable` using `add_row`, the units are silently stripped and values are added to the table as `float` objects instead of `Quantity` objects.

### Expected behavior

`units` should be maintained when row is added to empty `QTable`, or an error/warning should be raised.

### How to Reproduce

```>>> from astropy.table import QTable
>>> from astropy import unit as u

>>> qtab = QTable(names=['key_1', 'key_2', 'key_3'])
>>> print(qtab)
key_1 key_2 key_3
----- ----- -----

>>> qtab.add_row([1*u.m, 2*u.m, 3*u.m])
>>> qtab.add_row([4*u.m, 5*u.m, 6*u.m])
>>> print(qtab)
key_1 key_2 key_3
----- ----- -----
  1.0   2.0   3.0
  4.0   5.0   6.0
```

**Comment by mhvk** [comment]
The underlying problem is that the empty initialization creates a table with zero-size `Column` (logical), which then get extended by `add_row`. Definitely feel that this should either replace the `Column` with a `Quantity` or raise an error. 

A work-around is to initialize with zero-size quantities:
```
qtab = QTable([np.zeros(0) << u.m]*3, names=['key_1', 'key_2', 'key_3'])
```

**Comment by neutrinoceros** [comment]
I can look into fixing this later this week.

**Comment by neutrinoceros** [comment]
for starters, here's a fixed and self-contained version of the reproducer script
```python
from astropy import units as u
from astropy.table import QTable
qtab = QTable(names=['key_1', 'key_2', 'key_3'])
print(qtab)
print()
qtab.add_row([1*u.m, 2*u.m, 3*u.m])
qtab.add_row([4*u.m, 5*u.m, 6*u.m])
print(qtab)
```

**Comment by neutrinoceros** [comment]
>  Definitely feel that this should either replace the Column with a Quantity or raise an error.

Given that `Table.insert_row` and `Table.add_row` intentionally upgrade columns to masked columns when masked values get inserted, I think it'd be consistent to have similar logic when a Quantity is inserted in a empty column. PR incoming.

**Comment by taldcroft** [comment]
@Seraf-N - you may see a very long discussion related to your issue over in #15971. Where this ended up is the following:

- In the next release of astropy if you try to run your original code it will generate a warning that you are inserting a Quantity into a Column and the unit is being dropped.
- In future releases this might raise an exception but this is not decided.

Right now, what you need to do is to also supply the `units` when initially creating the table. `QTable(names=['key_1', 'key_2', 'key_3'])` creates three `Column`-type columns. This is the default behavior for both `Table` and `QTable`.

If you supply the units then you'll get your expected result:
```
>>> qtab = QTable(names=["key_1", "key_2", "key_3"], units=["m", "m", "m"])
>>> qtab.info
<QTable length=0>
 name  dtype  unit  class  
----- ------- ---- --------
key_1 float64    m Quantity
key_2 float64    m Quantity
key_3 float64    m Quantity

>>> qtab.add_row([1 * u.m, 2 * u.m, 3 * u.m])
>>> qtab.add_row([4 * u.m, 5 * u.m, 6 * u.m])
>>> qtab
<QTable length=2>
 key_1   key_2   key_3 
   m       m       m   
float64 float64 float64
------- ------- -------
    1.0     2.0     3.0
    4.0     5.0     6.0
```

**Comment by mhvk** [comment]
Ah, with @taldcroft mentioning the `units` argument, I wondered "did we have that?" and indeed it is in the docstring for `Table`, but not for `QTable`! So, not so surprising that one didn't know about that... See #16002 for a fix.
