### ISSUE TITLE
TST: CI is currently unstable against pytest 8.0

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#15960]
### Description

pytest 8.0.0 was just released a couple hours ago and despite our efforts to test against the release candidates, it still appears to break CI, but only certain test envs are affected.
I ran an experiment on my for at https://github.com/neutrinoceros/astropy/pull/13, with a no-op patch, so it's clear that failures are unrelated to the change.

I'm not 100% sure that pytest 8.0 is the culprit yet, but it's my primary (and currently, only) suspect.

**Comment by neutrinoceros** [comment]
I'm pretty sure that most of the failures are similar to those I fixed in #15809, the difference being that they happen in tests that require optional dependencies, which explains why they were not caught earlier. Specifically, some unmatched warnings are making causing `astropy/coordinates/tests/test_spectral_coordinate.py::test_spectralcoord_accuracy` to fail.
Let's focus on this part first.

**Comment by neutrinoceros** [comment]
I think we also see a genuine pytest bug, reported upstream https://github.com/pytest-dev/pytest/issues/11872

**Comment by neutrinoceros** [comment]
And `astropy/wcs/tests/test_wcs.py::test_distortion_header` is also broken, but only in wheel builds (?). I couldn't reproduce so far, but I'll try again on Monday.

**Comment by pllim** [comment]
Thanks for taking a stab! I'll look into it until you return.

**Comment by pllim** [comment]
But... how? We been testing with devinfra weekly and sometimes on PRs!

**Comment by pllim** [comment]
Ah, that makes sense. We can only test so much with unreleased stuff. Somehow the predeps job missed these too. Ah, well.
