### ISSUE TITLE
BLD: Cannot build cp310*win_amd64 with OpenAstronomy

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15969]
As a result, we cannot upload new nightly. If upstream cannot be resolved soon, we might need to exclude this combo from build or try to use an older version of OpenAstronomy workflow.

### Blocked by

* https://github.com/pypa/cibuildwheel/issues/1740
* https://github.com/OpenAstronomy/github-actions-workflows/issues/183

**Comment by pllim** [comment]
Looks like the failure is non-deterministic.

**Comment by henryiii** [comment]
Fixed in cibuildwheel 2.16.5, along with macos-14 AS runner support. (the failure was based on the powershell version, which was based on the build image version, which is still rolling out AFAICT).
