### ISSUE TITLE
TST: coverage overhead mostly goes away in Python >= 3.12

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#15975]
`coverage.py` is moving to a much more lightweight profiling method, available in Python 3.12 and which current release of `coverage.py` have an opt-in option for. It'll be the default behaviour sometimes in the future.

I've ran astropy's test suite locally to get a sense of the improvements:

| coverage mode | run time (s) | overhead (%) |
|:-|:-:|:-:|
| None | 227 | 0 |
| 7.4.0 (default method) | 375 | 65 |
| 7.4.0 (new method) | 231 | 2 | 

This is *so* much better that I think it would make sense to just have coverage on all the time instead of having dedicated jobs in `tox.ini` and in CI. However this is not happening before there's at least a nicer interface to use this new method (currently it's controlled by an environment variable and coverage doesn't gracefully fallback in currently-unsupported cases), and even then it'll only apply to Python >= 3.12, so this issue is to serve as a reminder of it when the time comes.

xref: blogpost on this topic by the package author https://nedbatchelder.com/blog/202312/coveragepy_with_sysmonitoring.html

**Comment by pllim** [comment]
It is up to you what template you want to use. I updated the labels. Thanks for the heads up!

**Comment by pllim** [comment]
I don't think we pull in coverage directly. Is it what pytest-cov uses?

**Comment by neutrinoceros** [comment]
yes it is.

**Comment by pllim** [comment]
Is this limitation still true? We use plugins.

*Some things won’t work with sys.monitoring: plugins and dynamic contexts aren’t yet supported, though eventually they will be. Execution will be faster for line coverage, but not yet for branch coverage. Let me know how it works for you.*

**Comment by neutrinoceros** [comment]
What plugins do we use ? I couldn't find any.

**Comment by pllim** [comment]
Does the author mean pytest plugins? We use all the plugins defined here:

https://github.com/astropy/astropy/blob/42b96feb8e42564c30534b5d8c6548d4122feea8/pyproject.toml#L96-L99

https://github.com/astropy/astropy/blob/42b96feb8e42564c30534b5d8c6548d4122feea8/tox.ini#L65

**Comment by pllim** [comment]
I am not sure what counts as dynamic context either.

**Comment by neutrinoceros** [comment]
> Does the author mean pytest plugins?

No, he means coverage plugins. Pytest and coverage are completely independent tools, we just happen to run the latter through an extension to the former (`pytest-cov`), which in most cases is actually not necessary, but I digress.

**Comment by neutrinoceros** [comment]
> I am not sure what counts as dynamic context either.

I'm _assuming_ he means context managers or something related. I will look it up and ask him for clarification if I'm not confident I get it.

**Comment by neutrinoceros** [comment]
So actually it means something else specifically in `coverage`: https://coverage.readthedocs.io/en/7.5.3/contexts.html#dynamic-contexts
In short, it's an option that we don't use.
