### ISSUE TITLE
RickerWavelet1DKernel not usable for convolution

### ISSUE THREAD

**Issue by Andrew-Swan** [astropy/astropy#15976]
### Description

Attempting to use a RickerWavelet1DKernel for convolution fails for widths of about 0.7 or larger (i.e. most reasonable values). The exception thrown is "ValueError: The kernel can't be normalized, because its sum is close to zero. The sum of the given kernel is < 0.01"

The [example in the documentation](https://docs.astropy.org/en/stable/api/astropy.convolution.RickerWavelet1DKernel.html#astropy.convolution.RickerWavelet1DKernel) uses a width of 10, which will fail.

### How to Reproduce

Create a clean conda environment, requesting astropy v6.

```python
from astropy.convolution import convolve, RickerWavelet1DKernel
import numpy as np
x = np.random.random(100)
convolve(x, RickerWavelet1DKernel(0.01)) #OK
convolve(x, RickerWavelet1DKernel(0.1)) #OK
convolve(x, RickerWavelet1DKernel(0.674)) #OK
convolve(x, RickerWavelet1DKernel(0.675)) #Fails
convolve(x, RickerWavelet1DKernel(1)) #Fails
convolve(x, RickerWavelet1DKernel(10)) #Fails
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)

Windows-11-10.0.22631-SP0
Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 07:53:56) [MSC v.1937 64 bit (AMD64)]
astropy 6.0.0
Numpy 1.26.3
pyerfa 2.0.0

**Comment by pllim** [comment]
@keflavich or @larrybradley , are you able to advise? Thanks!

**Comment by larrybradley** [comment]
For kernels with zero (or near-zero) sums, you can pass the `normalize_kernel=False` keyword to the `convolve` or `convolve_fft` function.

**Comment by eerovaher** [comment]
Should the error message mention that?

**Comment by larrybradley** [comment]
I updated the error messages in https://github.com/astropy/astropy/pull/15981
