### ISSUE TITLE
TST: Use macos-14 runner to test M1 macOS wheels

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15974]
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

Today, GitHub is excited to announce the launch of a new M1 macOS runner! This runner is available for all plans, free in public repositories, and eligible to consume included free plan minutes in private repositories. The new runner executes Actions workflows with a 3 vCPU, 7 GB RAM, and 14 GB of storage VM, which provides the latest Mac hardware Actions has to offer. The new runner operates exclusively on macOS 14 and to use it, simply update the `runs-on` key in your YAML workflow file to `macos-14`.

Thanks to @Cadair for the info!

Blocked by:

* https://github.com/actions/setup-python/issues/808

**Comment by hainenber** [comment]
I think this [PR](https://github.com/OpenAstronomy/github-actions-workflows/pull/186) has tackled the issue and since we've pinned most of CI template on `v1`, we're good to go :D

**Comment by pllim** [comment]
Looks like we only use them here:

https://github.com/astropy/astropy/blob/48a792f9d8dc659f428e9c6f0e9e9964a1b60682/.github/workflows/publish.yml#L88-L91

However, I still don't see the OSX ARM64 wheels being tested, so this is still true:

https://github.com/astropy/astropy/blob/48a792f9d8dc659f428e9c6f0e9e9964a1b60682/.github/workflows/publish.yml#L79-L81

The main perceived advantage was that we could finally test these wheels, no? @Cadair or @ConorMacBride ?

**Comment by ConorMacBride** [comment]
That PR hasn't made it into a release yet. Once it does it should just work without any update on astropy's side.

**Comment by pllim** [comment]
Great. @ConorMacBride , can you please comment here once the release is made, so I can check the log again and close this out?

@hainenber , thanks for the ping!

**Comment by ConorMacBride** [comment]
@pllim the release has been made

**Comment by pllim** [comment]
Alas, I already kicked off https://github.com/astropy/astropy/actions/runs/7979290389/job/21786378642 to check https://github.com/astropy/astropy/issues/16076 probably before this release, because I don't see any wheel testing for osx-arm jobs there. I will check again tomorrow and get back to you. Thanks!

**Comment by ConorMacBride** [comment]
Ah, that's a pity! It's still using the default `macos-12` [here](https://github.com/astropy/astropy/actions/runs/7979290389/job/21786378436#step:1:8) but will hopefully be `macos-14` tomorrow!

**Comment by pllim** [comment]
@ConorMacBride , now it picks up macos-14 from OpenAstronomy but as mentioned in #16081 , it is still failing. This is blocking nightly wheel upload for us. Can you just bump Python for macos-14 ? If not, I might have to disable the osx-arm wheels here altogether. See https://github.com/astropy/astropy/actions/runs/8014525872/job/21893275869

`Error: The version '3.9' with architecture 'arm64' was not found for macOS 14.2.1.`

Also, we are dropping Python 3.9 here soon anyway. Is there a reason why you must use Python 3.9?

**Comment by ConorMacBride** [comment]
I'll take a look. The Python 3.9 is what the internal tools use to run. It doesn't affect the Python used for testing/building. I might just be able to remove the version so it uses it latest available.

**Comment by ConorMacBride** [comment]
I've upgraded the Python version for the utils to 3.12. That will fix this issue (and hopefully not cause any other issues!) 

https://github.com/OpenAstronomy/github-actions-workflows/releases/tag/v1.10.1

**Comment by pllim** [comment]
Thanks! Only one way to find out... https://github.com/astropy/astropy/actions/runs/8025465439

**Comment by pllim** [comment]
@ConorMacBride , it is green now but I still don't see the OSX ARM64 wheels being tested in the log: https://github.com/astropy/astropy/actions/runs/8025465439/job/21926176879

**Comment by ConorMacBride** [comment]
Great! I see the tests for arm64 are skipped in pyproject.toml

**Comment by pllim** [comment]
Oh... 🤦
