### ISSUE TITLE
IPAC Table reader does not work out of the box  for tables with `long` columns, e.g.,  ZTF Lightcurve data, on Windows

### ISSUE THREAD

**Issue by orionlee** [astropy/astropy#15989]
### Description

[IPAC Reader](https://docs.astropy.org/en/stable/api/astropy.io.ascii.Ipac.html) on table with `long` columns, e.g., [ZTF](https://irsa.ipac.caltech.edu/docs/program_interface/ztf_lightcurve_api.html) lightcurve data, does not work out of the box on Windows (conda-forge environments).

The codes emit a warning and a cryptic `TypeError`:
```python
WARNING: OverflowError converting to IntType in column oid, reverting to String. [astropy.io.ascii.core]
...
TypeError: converter type does not match column type
```

The workaround is to explicitly declare columns with `long` datatype (`oid` and `filefracday` for ZTF)  as `np.int64` in`QTable.read()` with `converters` argument.

The root cause is #5744 , but it's arguably worse for IPAC tables because:
1. IPAC reader's type check logic raises a cryptic `TypeError` (rather than just converting the column into strings)
2. IPAC reader already knows the relevant columns are `long` from the column type declaration in the ipac table file. So it has the necessary information to make the correspond columns to be explicitly `np.init64`.

### Expected behavior

Users should be able to read IPAC tables with `long` columns without specifying `converters`

### How to Reproduce

```python
import numpy as np
from astropy.table import Table, QTable

# Test reading ZTF lc
tab = QTable.read(
    "https://irsa.ipac.caltech.edu/cgi-bin/ZTF/nph_light_curves?ID=660106400019009&FORMAT=IPAC_TABLE",
    format="ascii.ipac",
    # converters={"oid":np.int64, "filefracday": np.int64},  # uncomment to make it work on Windows
    )
tab
```

The codes would fail with the above warning and `TypeError`
Uncomment the `converters` line would make it work.

### Versions

Windows-10-10.0.22621-SP0
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:01:37) [MSC v.1935 64 bit (AMD64)]
Numpy 1.26.3
pyerfa 2.0.1.1
astropy 6.0.0  (also tested on the latest development version)
Scipy 1.11.4
Matplotlib 3.8.2

**Comment by pllim** [comment]
If fixing https://github.com/astropy/astropy/issues/5744 would also fix this issue, does that make this issue a duplicate? 🤔

**Comment by pllim** [comment]
Or is your patch in #15992 only fixes this issue and not the older one?

**Comment by orionlee** [comment]
PR #15992 only addressed the issue on IPAC here.

I look a quick look at #5744. Addressing it seems to need changes in both Python and C code paths.

**Comment by orionlee** [comment]
Note: the issue is found on Windows. Conceivably, the same problem could arise in some other 32-bit platform, or possibly some non-standard build of numpy, basically on platforms where `np.array([], int)` returns a `np.int32` instead of `np.int64`.

**Comment by pllim** [comment]
Side note on 32-bit: Do Windows really ship 32-bit nowadays? Are you stuck on a really old OS? https://www.pcmag.com/news/microsoft-stops-releasing-32-bit-windows-10-builds-for-new-pcs

If 32-bit Windows is obsolete, maybe this problem will go away on its own eventually when people use 64-bit. 🤷‍♀️

**Comment by pllim** [comment]
OK nevermind. I just had a chance to check. Still a mess in Windows 11 64-bit. https://github.com/astropy/astropy/issues/5744#issuecomment-1930411307

**Comment by pllim** [comment]
Addressed in 16005
