### ISSUE TITLE
BLD: Nightly wheel upload fails due to time formatting error

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16076]
Example log:

```
  File "python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-02-16 04:19:43+00:00' does not match format '%Y-%m-%d %H:%M:%S.%f%z'
Error: Process completed with exit code 1.
```

https://github.com/astropy/astropy/actions/runs/7954387476/job/21712087501

Blocked by:

* https://github.com/OpenAstronomy/publish-wheels-anaconda/issues/8

Has been failing for 4 days. I was not the one who got notified so I didn't realize this until I was checking the log for https://github.com/astropy/astropy/issues/15974 .

**Comment by neutrinoceros** [comment]
I opened https://github.com/OpenAstronomy/publish-wheels-anaconda/pull/9 to try and fix this.
