### ISSUE TITLE
BUG: units are silently dropped when reading a `Table` from a `BinTableHDU` object

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16077]
I'm running a very slightly simplified and self-contained version of the MWE from #15313, reproduced hereafter for convenience
```python
import numpy as np
import astropy.units as u
from astropy.table import Table
from astropy.io import fits

rng = np.random.default_rng()
targetid = rng.integers(0, 2**64, (1, ), dtype=np.uint64)
mag = 1e9 * rng.random((1,), dtype=np.float32)
columns = fits.ColDefs([fits.Column(name='TARGETID', format='K', bzero=2**63, array=targetid),
                        fits.Column(name='FLUX', format='E', array=mag)])
hdu0 = fits.PrimaryHDU()
hdu0.header.append(('EXTNAME', 'PRIMARY', 'extension name'))
hdu0.add_checksum()
hdu1 = fits.BinTableHDU.from_columns(columns, name='BINTABLE', uint=True)
hdu1.header.insert('TFORM2', ('TUNIT2', 'nanomaggy', 'Units for FLUX'), after=True)
hdu1.add_checksum()
hdulist = fits.HDUList([hdu0, hdu1])
hdulist.writeto('demonstrate_maggy.fits', overwrite=True)

t1 = Table.read(hdu1, hdu='BINTABLE')
t2 = Table.read('demonstrate_maggy.fits', hdu='BINTABLE')
```

printing `t1` and `t2` reveals that `t1` seems to have lost units metadata:
```
>>> print(t1)
      TARGETID           FLUX   
       uint64          float32  
-------------------- -----------
11049962027143826759 743222300.0

>>> print(t2)
      TARGETID           FLUX   
                      nanomaggy 
       uint64          float32  
-------------------- -----------
11049962027143826759 743222300.0
```

At a high level, the difference is that, when passed a filename, `read_table_fits` will first read it as a `HDUList`, then recurse
https://github.com/astropy/astropy/blob/48a792f9d8dc659f428e9c6f0e9e9964a1b60682/astropy/io/fits/connect.py#L234-L252
In the nested call, the following special-case code will be run https://github.com/astropy/astropy/blob/48a792f9d8dc659f428e9c6f0e9e9964a1b60682/astropy/io/fits/connect.py#L184
None of this happens if you just pass in a `BinTableHDU`, as is evident from the first listing.

_Originally posted by @neutrinoceros in https://github.com/astropy/astropy/issues/15313#issuecomment-1953918870_

**Comment by neutrinoceros** [comment]
This problem was first discovered by @pllim in https://github.com/astropy/astropy/issues/15313#issuecomment-1718666412

**Comment by saimn** [comment]
Not really a bug, it's just that you're setting the unit in the header, which doesn't propagate to the `Column` object.
Reading the file once it's written would also work when passing the HDU object:
```
In [2]: Table.read(fits.open('demonstrate_maggy.fits')[1])
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
Out[2]: 
<Table length=1>
      TARGETID           FLUX   
                      nanomaggy 
       uint64          float32  
-------------------- -----------
15287561561040601150 652328640.0
```

or the correct way to create the column would be 
```
fits.Column(name='FLUX', format='E', array=mag, unit='nanomaggy')
```
so `hdu1.columns['FLUX'].unit` is actually correct.
