### ISSUE TITLE
No module named 'astropy.visualization'; 'astropy' is not a package

### ISSUE THREAD

**Issue by reinhardwu** [astropy/astropy#16106]
### Description

The following issues occurred while running plod_obs planning. py：
from astropy.visualization import astropy_mpl_style, quantity_support
ModuleNotFoundError: No module named 'astropy.visualization'; 'astropy' is not a package。
May I ask how to handle it? Installed version Astropy6.0.

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
import matplotlib.pyplot as plt
import numpy as np

from astropy.visualization import astropy_mpl_style, quantity_support

plt.style.use(astropy_mpl_style)
quantity_support()

```

### Versions

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
try:
    import scipy
    print("Scipy", scipy.__version__)
except ImportError:
    print("Scipy not installed")
try:
    import matplotlib
    print("Matplotlib", matplotlib.__version__)
except ImportError:
    print("Matplotlib not installed")
```
```
# Copy the result here
Windows-10-10.0.22621-SP0
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Numpy 1.26.4
pyerfa 2.0.1.1
Scipy 1.12.0
Matplotlib 3.8.3
AttributeError: module 'astropy' has no attribute '__version__'

**Comment by neutrinoceros** [comment]
@reinhardwu My best guess is that you may be running a different `python` interpreter than the one used to instal `astropy`, but it's hard to tell with no information on your environment. Could you edit your post and fill in the information requested in the form ?

**Comment by pllim** [comment]
Usually this means one of two things:

1. Installed to the wrong place (as indicated in the comment above); or
2. Installation failed but you missed it in the log.

Given that `pyerfa` is actually installed and only `astropy` pulls that in, at least at some point, `astropy` install was at least attempted in the given env.

Provided these would help us help you:

1. Are you using Powershell or WSL2?
2. Exact command used to install astropy.
3. Full install log with all the fun traceback. If you decide to sanitize the full path in the log, please keep enough for us to see where the env is.

Thank you.

**Comment by ayshih** [comment]
Also check whether you have a subdirectory named `astropy` in your working directory, because by default Python will latch on to that subdirectory and attempt to interpret it as the package rather than finding the proper, installed version of `astropy`.

**Comment by eerovaher** [comment]
I see no evidence that the reported problem was caused by `astropy`.
