### ISSUE TITLE
When iers_degraded_accuracy = error, Astropy reports a warning and not an error (in coordinates)

### ISSUE THREAD

**Issue by IlDordollano** [astropy/astropy#16128]
### Description

iers_degraded_accuracy can be set to "error", "warn" or "silent".

iers_degraded_accuracy = error has the same behavior as iers_degraded_accuracy = warn

### Expected behavior

Expected behavior is log error instead of warning and an uncatched IERSRangeError . As documented here [https://docs.astropy.org/en/stable/utils/iers.html](https://docs.astropy.org/en/stable/utils/iers.html)

> iers_degraded_accuracy:
Some time conversions like UTC -> UT1 require IERS-A Earth rotation data for full accuracy. In cases where full accuracy is not required and downloading the IERS-A is not possible or desired (for instance running on a cluster) then this option can be set to either 'warn' or 'ignore'. The default is 'error' which will raise an exception if full accuracy is not possible for a time conversion, 'warn' will issue a warning, and 'ignore' will ignore the problem and use available IERS-B data.

### How to Reproduce

```python
astropy.utils.iers.conf.iers_degraded_accuracy = "error"
t = Time("2016:001")
t.ut1
```

### Versions

Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
astropy 6.0.0
Numpy 1.26.2
pyerfa 2.0.1.1
Scipy 1.11.4
Matplotlib 3.8.2

**Comment by pllim** [comment]
Are you sure that is going to raise anything? I tried your code with latest dev version and there is not even a warning.

We do test for the config behavior here and it seems to work both in CI and locally:

https://github.com/astropy/astropy/blob/ac2427c9c8fc9b2e0342b726bdda52f88e9510e6/astropy/utils/iers/tests/test_iers.py#L460-L463

**Comment by IlDordollano** [comment]
Sorry, indeed my example was wrong. I need to post a more elaborate example, that gives only warning and does not stop. This is the case where internet is not enabled and times are outside of range covered by IERS table.

```python
import astropy.units as u
import astropy

astropy.utils.data.clear_download_cache()
astropy.utils.data.conf.allow_internet = False
astropy.utils.iers.conf.iers_degraded_accuracy = "error"

time = Time("2024-02-29T17:53:03.605", format="isot", scale="utc")
x = np.array([1, 0, 0])
y = np.array([0, 1, 0])
z = np.array([0, 0, 1])
itrs = ITRS(CartesianRepresentation(x * u.m, y * u.m, z * u.m), obstime=time)
gcrs = itrs.transform_to(GCRS(obstime=time))
```


Running this example, I receive some warnings, but the execution doesn't stop and doesn't send any error for iers_degraded_accuracy:

> WARNING: IERSWarning: failed to download https://datacenter.iers.org/data/9/finals2000A.all: <urlopen error URL https://datacenter.iers.org/data/9/finals2000A.all was supposed to be downloaded but allow_internet is False; if this is unexpected check the astropy.cfg file for the option allow_internet> [astropy.utils.iers.iers]
WARNING: IERSWarning: failed to download https://maia.usno.navy.mil/ser7/finals2000A.all: <urlopen error URL https://maia.usno.navy.mil/ser7/finals2000A.all was supposed to be downloaded but allow_internet is False; if this is unexpected check the astropy.cfg file for the option allow_internet> [astropy.utils.iers.iers]
WARNING: IERSWarning: unable to download valid IERS file, using local IERS-B [astropy.utils.iers.iers]
WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those. This may affect precision at the arcsec level. Please check your astropy.utils.iers.conf.iers_auto_url and point it to a newer version if necessary. [astropy.coordinates.builtin_frames.utils]
WARNING: (some) times are outside of range covered by IERS table. Cannot convert with full accuracy. To allow conversion with degraded accuracy set astropy.utils.iers.conf.iers_degraded_accuracy to "warn" or "silent". For more information about setting this configuration parameter or controlling its value globally, see the Astropy configuration system documentation https://docs.astropy.org/en/stable/config/index.html. Assuming UT1-UTC=0 for coordinate transformations. [astropy.coordinates.builtin_frames.utils]

**Comment by pllim** [comment]
Thank you very much for the complete example. Turns out the bug is in `coordinates`, not `utils.iers`. The warnings you see are coming from https://github.com/astropy/astropy/blob/main/astropy/coordinates/builtin_frames/utils.py that has custom code to bypass your configs. I am not sure if this is intentional or oversight.

For example, in `get_jd12` (but not the only place it happens):

https://github.com/astropy/astropy/blob/73df5922e36931e54ed66a52abc15806c846febc/astropy/coordinates/builtin_frames/utils.py#L114-L117

And this is where the "polar motion" one happens and it does not check for config at all:

https://github.com/astropy/astropy/blob/73df5922e36931e54ed66a52abc15806c846febc/astropy/coordinates/builtin_frames/utils.py#L49

A quick git blame points to @maxnoe and @taldcroft for some of the designs, so hopefully they can clarify or ping those who can.

**Comment by maxnoe** [comment]
I am pretty sure that I didn't touch any code directly related to the warning / error handling there.

Checking the blame, I just slightly changed the wording of the message there

**Comment by pllim** [comment]
I think @eteq is also in the blame somewhere. 😸 

Sorry for the noise, @maxnoe !

**Comment by maxnoe** [comment]
@pllim no problem at all, our software also runs in cluster environments so this issue is definitely relevant to us

**Comment by pllim** [comment]
In the meantime, for the affected use case, you would have to catch those warnings yourselves and promote them to error using https://docs.python.org/3/library/warnings.html

**Comment by IlDordollano** [comment]
@pllim nice workaround thanks!
