### ISSUE TITLE
Improve performance by replacing pow with multiply

### ISSUE THREAD

**Issue by manodeep** [astropy/astropy#16136]
While looking through the C code, I noticed a [reference](https://github.com/astropy/astropy/blob/47a8dac8f1dab6ce592be6048f70140adead4e1d/astropy/stats/src/compute_bounds.c#L45-L47) to `pow` within a `for` loop. `pow` is a slow operation meant for floating point exponents. Since the exponent here is integral (`==2`), this instance of `pow` should be replaced with a multiply. 

Existing code is:

```c
      for (i = 0; i < count; i++) {
        std += pow(mean - data_buffer[i], 2);
      }
```

Better performant code would be:

```c
      for (i = 0; i < count; i++) {
        const double dx = mean - data_buffer[i];
        std += dx * dx;
      }
```

**Comment by MridulS** [comment]
Yeah, that does sound right! I'll try to look into some benchmarking here :)

**Comment by MridulS** [comment]
BTW did some crude benchmarking and the change doesn't really make too much of a difference. I guess the python machinery around the code is slow enough here.

**Comment by manodeep** [comment]
That must be the case. pow would absolutely be slower than a multiply. 

What array lengths did you use for the benchmarks? (Wondering whether the performance improvement only becomes significant for large-N, say >~ million). 

Does it matter if you remove the “const double” line and use (mean - data[i]) * (mean - data[i]) in the rhs? I am assuming the compilation flags contain “-O3” or “-O2 -ftree-vectorize”.  

Regardless, the multiply would be a better code to use anyway, specifically for using less power because of fewer CPU cycles associated with a multiplication compared to a pow.

**Comment by MridulS** [comment]
>  (Wondering whether the performance improvement only becomes significant for large-N, say >~ million).

array with ~500million.

**Comment by manodeep** [comment]
Ohh wow! Never ceases to surprise how big the python overhead is.

**Comment by mhvk** [comment]
I haven't tested this, but it seems plausible that the compiler optimized this away, since it can also see that the exponent is just a constant integer 2.
... OK, let me check on https://godbolt.org/ ...

Indeed, this shows that
```
#include <math.h>
int square(double num) {
    return pow(num, 2);
}
```
does not call `pow` once you turn on optimizations.

**Comment by manodeep** [comment]
@mhvk Yup - good point. And I checked that gcc as far back as 4.8.4, converts the `pow` with a compile-time constant exponent of 2 into a multiply. That optimisation within compilers itself highlights what I was saying - replacing `pow(x, 2)` with `x*x` is always better. But I can also see the viewpoint that may be best to leave the code as is since the compiler is already producing the multiply call anyway.

I had added a for loop on [godbolt](https://godbolt.org/z/7EWzT51Pe) around the `pow` to mimic the actual case within the code and I saw that even with `gcc-13.2` and `-O2` as the compilation flag, the compiler produces `mulsd` - which is the non-vectorised version. If you use `-O2 -ftree-vectorize` or `-O3`, the correct vector call `mulpd` is generated (which should be 2x faster for doubles and 4x faster for floats). 

Even these vector instructions target the old `SSE4` architecture with 128-bit registers, but newer CPUs are available with up to 512 bit vector registers. So, another factor of 4 performance could be gained just based on compiler flags, when running astropy on newer CPUs

**Comment by manodeep** [comment]
I can see on my M2 laptop that the `astropy` compilation has a `-O3` flag but also an odd `-Os` flag which is saying optimise for smaller binary size. The rightmost flag, i.e., `-Os` in this case, overrides the `-O3`. However, according to godbolt, that extra `-Os` makes no difference for code generated by `apple-clang-13.0.0`. 

For code generated by `gcc-13/gcc-12/gcc-11/gcc-10/gcc9/gcc8` that extra `-Os` on the right over-rides the `-O3` on the left and no vector instructions are generated. Might be worthwhile to confirm that `-Os` is not present in the compiler flags for architectures where gcc is used to compile astropy.

The relevant output from my M2 laptop with `apple-clang-13.0.0` 
```sh
  /usr/bin/clang -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -DNPY_TARGET_VERSION=NPY_1_23_API_VERSION -I/private/var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/pip-build-env-89ivcu7t/overlay/lib/python3.11/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c astropy/stats/src/compute_bounds.c -o /var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/tmplimpg8nq.build-temp/astropy/stats/src/compute_bounds.o
  /usr/bin/clang -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -DNPY_TARGET_VERSION=NPY_1_23_API_VERSION -I/private/var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/pip-build-env-89ivcu7t/overlay/lib/python3.11/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c astropy/stats/src/fast_sigma_clip.c -o /var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/tmplimpg8nq.build-temp/astropy/stats/src/fast_sigma_clip.o
  /usr/bin/clang -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -DNPY_TARGET_VERSION=NPY_1_23_API_VERSION -I/private/var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/pip-build-env-89ivcu7t/overlay/lib/python3.11/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c astropy/stats/src/wirth_select.c -o /var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/tmplimpg8nq.build-temp/astropy/stats/src/wirth_select.o
  creating /var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/tmp_mnutqi3.build-lib/astropy/stats
  /usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk /var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/tmplimpg8nq.build-temp/astropy/stats/src/compute_bounds.o /var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/tmplimpg8nq.build-temp/astropy/stats/src/fast_sigma_clip.o /var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/tmplimpg8nq.build-temp/astropy/stats/src/wirth_select.o -o /var/folders/qx/wszc62f97yz8050n6l1k54d4zql7xh/T/tmp_mnutqi3.build-lib/astropy/stats/_fast_sigma_clip.cpython-311-darwin.so
```

**Comment by mhvk** [comment]
Interesting. Our flags may well not be set by us, but rather by `setuptools`... I think overall this is a bit of an argument that going to C is not necessarily better for arrays - the numpy C routines do really try to make use of optimization/vectorizatio (though in this particular case, the code was added because the python/numpy one was rather slow).

Anyway, not sure there is something actionable here - though in principle I'm fine with having a quick PR that removes the use of `pow` just so we do not have to think of it again!

p.s. With this concrete example, I wondered whether writing `double dx = data_buffer[i] - mean;` is actually better, since then in vectorized form it is just one subtraction instead of a negation of the vector and addition - from what I can see in godbolt, it doesn't really matter though.

**Comment by manodeep** [comment]
Opened #16169 with the one-line fix.

**Comment by saimn** [comment]
About compilation flags:
- most users install wheels, where astropy is compiled within some CI/docker image for each platform. I don't know what flags are used here, since the compilation logs are not shown in the wheels jobs (e.g. https://github.com/astropy/astropy/actions/runs/8182690920/job/22374432742#step:7:297). Could a good idea to make cibuildwheel more verbose and check the flags.
- when installing from source and compiling locally, AFAIK the compilation flags are inherited by setuptools/distutils from the flags used to compile the Python you're using (I think from `sysconfig.get_config_vars("CFLAGS")`).
- for SIMD optimizations (`-ftree-vectorize`), this cannot be used in wheels since the same wheel will be installed on many different CPU architectures. Well it's possible and Numpy does it but using some runtime detection of CPU capabilities (https://pypackaging-native.github.io/key-issues/simd_support/), which is too complex for us and the little amount of C code we have (and that doesn't use SIMD instructions anyway). So to benefit from the best performance with our C code and SIMD optimizations with `-ftree-vectorize` it's necessary to install from source, overriding  the compilation flags if necessary (e.g. `CFLAGS='-O3 -march=native -ftree-vectorize' pip install -e . -v`). Could be interesting to benchmark the difference with sigma clipping.

**Comment by manodeep** [comment]
> About compilation flags:
> 
>     * most users install wheels, where astropy is compiled within some CI/docker image for each platform. I don't know what flags are used here, since the compilation logs are not shown in the wheels jobs (e.g. https://github.com/astropy/astropy/actions/runs/8182690920/job/22374432742#step:7:297). Could a good idea to make cibuildwheel more verbose and check the flags.

Since the wheels are built for specific CPU architecture and OS, it might be possible to specify the architecture through `CFLAGS` and that could be the minimum instruction set supported (e.g., OSX + ARM implies at least ARMV8, since the ARMV8 M1 is the first CPU that matches those specs). Though not sure that it will be worthwhile given that performance is not.a primary consideration for astropy. 

> 
>     * when installing from source and compiling locally, AFAIK the compilation flags are inherited by setuptools/distutils from the flags used to compile the Python you're using (I think from `sysconfig.get_config_vars("CFLAGS")`).
> 

It should be possible to add compiler flags through the extra_compile_args right? My understanding is that those flags are whatever was used to compile `python` with, and those tend to be on the conservative side (i.e., no more than `-O2`).


>     * for SIMD optimizations (`-ftree-vectorize`), this cannot be used in wheels since the same wheel will be installed on many different CPU architectures. Well it's possible and Numpy does it but using some runtime detection of CPU capabilities (https://pypackaging-native.github.io/key-issues/simd_support/), which is too complex for us and the little amount of C code we have (and that doesn't use SIMD instructions anyway). So to benefit from the best performance with our C code and SIMD optimizations with `-ftree-vectorize` it's necessary to install from source, overriding  the compilation flags if necessary (e.g. `CFLAGS='-O3 -march=native -ftree-vectorize' pip install -e . -v`). Could be interesting to benchmark the difference with sigma clipping.

`-O3` is effectively `-O2 -ftree-vectorize`. You don't need to have SIMD code in the C code - the `-march` dictates what instructions the compiler will generate. For example,  by default, gcc will emit the  128-bit vector instructions (SSE) from the early 2000's even though 512-bit vector instructions (AVX512) have been around for nearly 7 years now. One thing to do could be to add a README note recommending compiling from source for users (perhaps naming specific sub-packages that rely on C code) that might want a faster astropy. 

Thanks for the link on the simd_support within python packages. While reading that I realise that there is one option missing from that list - using the GCC `target_clones` [function attribute](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-target_005fclones-function-attribute). This should automatically create function multi-versioning and runtime dispatch - though I suspect this would still require the actual function line to be within multiple `#ifdef` conditions for each targeted OS + ISA (e.g., DARWIN + PPC64, DARWIN + x86_64, DARWIN + ARM etc...). 

On a completely unrelated note, while looking at the cibuildwheel logs I noticed that votable validation is printing [warnings](https://github.com/astropy/astropy/actions/runs/8182690920/job/22374435440#step:7:688) but in the end reporting that [all validation passed](https://github.com/astropy/astropy/actions/runs/8182690920/job/22374435440#step:7:928). Is that expected?

**Comment by pllim** [comment]
Re: validation warning

Yes, it is expected. It comes from here:

https://github.com/astropy/astropy/blob/52d2b360dc386c87e4e7a74dfdacd28428a23a30/astropy/io/votable/table.py#L219

Because of tests like this:

https://github.com/astropy/astropy/blob/52d2b360dc386c87e4e7a74dfdacd28428a23a30/astropy/io/votable/tests/test_table.py#L443-L444

Annoying but you shouldn't see it unless `-s` is passed into pytest.
