### ISSUE TITLE
Reminder: adapt `numpy.array_api` test to use `array-api-strict` instead

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16149]
In https://github.com/astropy/astropy/pull/16148 I just went for the quickest fix possible because we have a lot on our plate right now with breaking pytest releases and numpy dev being a fast moving target. When that's settled down, we should adapt this test (`test_array_api_init`)  to use the new home of `numpy.array_api`, namely `array-api-strict`.

Ping @MridulS as the original author of this test :)

**Comment by MridulS** [comment]
Thanks for the tag @neutrinoceros, I think we should just add the dependency to test this out https://github.com/astropy/astropy/pull/16150 :)
