### ISSUE TITLE
Move IERS to a top-level package

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#1620]
As discussed in #1514.

**Comment by mhvk** [comment]
Looking at unlabelled issues per @astrofrog's request: I think this should be considered together with `erfa` (and perhaps GPS routines; #2134). my sense would be that all of those belong either in an `earth` or `lowlevel` sub-module.
Don't know how to label this. Do we need a new label `Organisation`?

**Comment by bsipocz** [comment]
@eteq @astrofrog - Is moving iers to another namespace still a plan? If yes, this would be nice to be done in 2.0 with a deprecation and finalize in 3.0. 

Otherwise close this issue.

**Comment by eteq** [comment]
@bsipocz and I discussed this out-of-band and have closed it b/c it seems like this ship has sailed - it would be breaking a ~4-year API for no clear benefit at this point.
