### ISSUE TITLE
TST: Daily cron with pandas fails with AttributeError: 'SoupStrainer' object has no attribute 'name'

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16251]
Example log: https://github.com/astropy/astropy/actions/runs/8476606825/job/23226375475

pandas 2.2.1 was release back in Feb 23, so not sure why I didn't see this earlier.

```
pandas==2.2.1
...
_________________________ test_read_write_format[html] _________________________
...
    def _parse_tables(self, document, match, attrs):
>       element_name = self._strainer.name
E       AttributeError: 'SoupStrainer' object has no attribute 'name'

pandas/io/html.py:601: AttributeError
```

**Comment by neutrinoceros** [comment]
I took a look, and `pandas` doesn't seem to be the culprit.
Rather, the breaking change appears to be in `beautifulsoup4` `4.13.0b2`, released on March the 20th
Further inspection is needed to assess what to do, but this is where I got so far.

**Comment by neutrinoceros** [comment]
I couldn't find release notes for this beta release, or a changelog, or an existing report at pandas. I'll try to extract a minimal reproducer and report to pandas.

**Comment by neutrinoceros** [comment]
reported upstream at https://github.com/pandas-dev/pandas/issues/58086

**Comment by pllim** [comment]
Thanks for investigating!

**Comment by neutrinoceros** [comment]
The fix seemed simple enough so I also opened a PR upstream https://github.com/pandas-dev/pandas/pull/58100

**Comment by neutrinoceros** [comment]
My fix was just merged. However, we're not pulling in pandas nighties, so it might take a while before CI goes back to green by itself. I think we have three options:
- do nothing and wait it out (might be a while)
- (temporarily) pin beautifulsoup4
- pull pandas nightlies

What would you advise ?

**Comment by pllim** [comment]
That job is for pre-release. Is pandas going to release that fix soon? We can wait a few weeks. If not, then maybe we can check for conflicting pandas + bs4 versions and then xfail it for that combo.

**Comment by neutrinoceros** [comment]
Apparently the next release should be pandas 3.0, and was due today, so I guess it should come out sometimes soon, at least in a pre-release, which would work for this job.

**Comment by neutrinoceros** [comment]
The fix is now backported to pandas 2.2.x, which means it should be available sooner !

**Comment by neutrinoceros** [comment]
@pllim pandas 2.2.2 is out with the fix + numpy 2 compat, and daily cron is green again ! I think we can close this one.

**Comment by pllim** [comment]
So it is. Thanks for the update!

https://github.com/astropy/astropy/actions/runs/8640882810
