### ISSUE TITLE
the distances in astropy.cosmology

### ISSUE THREAD

**Issue by Firestar-Reimu** [astropy/astropy#16278]
### What is the problem this feature will solve?

> abs_distance_integrand(z)
    Integrand of the absorption distance [[1]](https://docs.astropy.org/en/stable/api/astropy.cosmology.FlatLambdaCDM.html#r9419a9076a00-1).
    Parameters:
        zQuantity-like [‘redshift’], [array_like](https://numpy.org/doc/stable/glossary.html#term-array_like), or [Number](https://docs.python.org/3/library/numbers.html#numbers.Number)
            Input redshift.
    Returns:
        X[float](https://docs.python.org/3/library/functions.html#float) or [array](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray)
            The integrand for the absorption distance.
    References
    [[1](https://docs.astropy.org/en/stable/api/astropy.cosmology.FlatLambdaCDM.html#id1)] (1,[2](https://docs.astropy.org/en/stable/api/astropy.cosmology.FlatLambdaCDM.html#id3))
    Hogg, D. (1999). Distance measures in cosmology, section 11. arXiv e-prints, astro-ph/9905116.

But this returns a number without distance dimension.

I tried to manually do the integrand:

$$
l = \frac{c}{H_0} \int_0^{10} \frac{(1+z)^2}{\sqrt{\Omega_{m0}(1+z)^3 + \Omega_{\Lambda0}}}\mathrm{d}z = \frac{380}{9} \frac{c}{H_0} \approx 42.2222 \frac{c}{H_0}
$$

but it is not equal to `cosmo.abs_distance_integrand`

```python
from astropy.cosmology import FlatLambdaCDM
import astropy.constants as c
import astropy.units as u
from scipy.integrate import quad

cosmo = FlatLambdaCDM(H0=70, Om0=0.3)
l = cosmo.abs_distance_integrand(10)
print(l)
l_ = (l * c.c / cosmo.H0).to(u.cm)
print(l_)

def f(z):
    return (1+z)**2 / (0.3*(1+z)**3 + 0.7)**0.5
L, err = quad(f, 0, 10)
print(L)
L_ = (L * c.c / cosmo.H0).to(u.cm)
print(L_)
```

```
6.050000000000001
7.995186205488991e+28 cm
42.222222222222285
5.5797442756397085e+29 cm
```

I can confirm that `L_` is what I need, but I don't know what `l` or `l_` means.

### Describe the desired outcome

Give the distance as quantities with a length dimension like `Mpc`, `m`, `cm`

Or write in the documentation, what is the formula to the distance such as `abs_distance_integrand`

especially how to dimensionless the distance (the factor)

**Comment by pllim** [comment]
@nstarman , since you refactored this module extensively, are you able to advise? Thanks!

**Comment by nstarman** [comment]
See https://people.ast.cam.ac.uk/~pettini/Intro%20Cosmology/Lecture13.pdf Eq 13.1 for the same form of the equation. The difference is a factor of `c`.

**Comment by nstarman** [comment]
I agree that these public functions should be return unit-ful numbers. This is the plan, as part of a move to adhere to https://cosmology.readthedocs.io/projects/api/en/latest/.

**Comment by Firestar-Reimu** [comment]
So does any of you want to explain what `abs_distance_integrand` means? I have no idea what is the link between `L/l` and `c`

@nstarman 

> 6.050000000000001
> 7.995186205488991e+28 cm
> 42.222222222222285
> 5.5797442756397085e+29 cm

**Comment by nstarman** [comment]
I think adding details to the docstring would be more useful.

Just keeping track of quick notes...

`abs_distance_integrand()` is:
$\frac{dl}{dz} = \frac{1+z^2}{E(z)}$

but the more useful method is `abs_distance_integrand_scalar()`, which is the same thing but restricted to scalars and is used by `absorption_distance()` as the argument to `scipy.integrate.quad`.

The correct definition of the absorption distance isn't actually Hogg's Distance Measures in Cosmology (as indicated by `abs_distance_integrand()`) but Equation 4 of https://articles.adsabs.harvard.edu/pdf/1969ApJ...156L...7B, which is cited in the docstring of `absorption_distance()`. Looking at the formal definition, `abs_distance_integrand()` and `absorption_distance()` are both unitless quantities. Really it's the docstrings that need improvement. Everything else appears to be correct.

**Comment by nstarman** [comment]
@Firestar-Reimu, hopefully #16297 helps! I've corrected the docs to point to the right reference, which explains the derivation behind the absorption distance, including that it is a unitless quantity.

**Comment by nstarman** [comment]
@Firestar-Reimu, does https://github.com/astropy/astropy/pull/16297 address your question? Happy to push further PRs if there's more.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/issues/16278#issuecomment-2067932265 -- Does this mean #16297 was sufficient or is more follow-up needed? Thanks!

**Comment by Firestar-Reimu** [comment]
#16297 is good but I think multiply a $cH_0$ to make it a distance quantity is needed

**Comment by nstarman** [comment]
We can document that `c H0` has units of distance, but the method is meant to match the definition, which is unitless.

**Comment by pllim** [comment]
Since more doc is needed, I am re-opening. Thanks!

**Comment by pllim** [comment]
@Firestar-Reimu , does https://github.com/astropy/astropy/pull/16297 look good to you now? Thanks!

**Comment by Firestar-Reimu** [comment]
OK thanks
