### ISSUE TITLE
pypi tar.gz fails

### ISSUE THREAD

**Issue by jcwright77** [astropy/astropy#16292]
### Description

Related to issue #5878
https://files.pythonhosted.org/packages/source/a/astropy/astropy-6.01.tar.gz is not found. Issue starts after 5.1

### Expected behavior

file is found

### How to Reproduce

type url in browser

### Versions

none, tar.gz release is not properly posted. Download works from pypi webpage but some installers rely on above url style to work

**Comment by neutrinoceros** [comment]
Thank you for reporting! Could you clarify which installers you're referring to ? I don't think I've encountered this style yet and I'm not sure what can be done about it from our end.

**Comment by astrofrog** [comment]
Looks like the URL is missing a period in the version number?

**Comment by jcwright77** [comment]
Spack tries to grab the tar.gz file through that pypi url.-johnOn Apr 13, 2024, at 2:50 AM, Clément Robert ***@***.***> wrote:﻿
Thank you for reporting! Could you clarify which installers you're referring to ? I don't think I've encountered this style yet and I'm not sure what can be done about it from our end.

**Comment by jcwright77** [comment]
yes. user error . sorry I though this was like issue #5878 
I had added v 6.0.1 to the recipe to get the latest but typed 6.01 instead
Thanks for pointing that out.
