### ISSUE TITLE
readthedocs failures

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#16301]
### Description

Failures in, e.g., https://readthedocs.org/api/v2/build/24097661.txt
```
docs/io/unified.rst:1091: ERROR: Error with CSV data in "csv-table" directive:
';' expected after '"'

.. csv-table::
    :header: "Format name", "Data Description", "Reader", "Writer"
    :widths: 25, 25, 25, 25
    :delim: ;

    ``pandas.csv``;`CSV <https://en.wikipedia.org/wiki/Comma-separated_values>`__;`read_csv() <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-read-csv-table>`_;`to_csv() <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-store-in-csv>`_
    ``pandas.json``;`JSON <http://www.json.org/>`__;`read_json() <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-json-reader>`_;`to_json() <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-json-writer>`_
    ``pandas.html``;`HTML <https://en.wikipedia.org/wiki/HTML>`__;`read_html() <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-read-html>`_;`to_html() <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-html>`_
    ``pandas.fwf``;Fixed Width;`read_fwf() <https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_fwf.html#pandas.read_fwf>`_;
```

**Comment by pllim** [comment]
https://github.com/sphinx-doc/sphinx 7.3.5 was released 12 hours ago.

**Comment by pllim** [comment]
There is actually a second warning. Maybe it is time we get rid of sphinx-gallery for good...

`pickling environment... WARNING: cannot cache unpickable configuration value: 'sphinx_gallery_conf'`

**Comment by ayshih** [comment]
> There is actually a second warning. Maybe it is time we get rid of sphinx-gallery for good...
> 
> `pickling environment... WARNING: cannot cache unpickable configuration value: 'sphinx_gallery_conf'`

Ongoing discussion here: https://github.com/sphinx-doc/sphinx/issues/12300

**Comment by AA-Turner** [comment]
Note the ``csv-table`` issue is with Docutils: https://github.com/sphinx-doc/sphinx/issues/12302

A

**Comment by pllim** [comment]
Re: `csv-table` -- Thanks! However, I don't see why we need a custom delimiter here, so I switched to comma over at #16304 and that seems to work too.
