### ISSUE TITLE
Use the `tox-oldest` plugin

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#16309]
### What is the problem this feature will solve?

We should get rid of our manual specification of oldest dependencies in `tox.ini` and instead use the constraints from our `pyproject.toml` 

### Describe the desired outcome

tox's `oldestdeps` environment should pull in the oldest version information from `pyproject.toml`. We should only have to specify version info in one place, not in both the `toml` and `tox.ini`.

### Additional context

I asked chat-gpt to solve this:

Got it, you want to use `tox` with your `pyproject.toml` file to create an environment called "oldestdeps" that installs the oldest version of each dependency. You can achieve this by configuring `tox` to use the `tox-oldest` plugin.

Here's how you can do it:

1. **Install `tox-oldest`**:
   First, you need to install the `tox-oldest` plugin:
   ```
   pip install tox-oldest
   ```

2. **Update your `pyproject.toml`**:
   Make sure your `pyproject.toml` contains the dependencies you want to test with. Specify the constraints for each dependency if necessary.

3. **Create a `tox.ini` file**:
   In your project directory, create a `tox.ini` file and configure it to use the `tox-oldest` plugin.

   Example `tox.ini`:
   ```ini
   [tox]
   envlist = oldestdeps

   [testenv]
   deps = tox-oldest

   [testenv:oldestdeps]
   deps =
       tox-oldest
   commands =
       tox-oldest
   ```

4. **Run `tox`**:
   Now you can run `tox` with the specified environment `oldestdeps`:
   ```
   tox -e oldestdeps
   ```

This will create an environment named "oldestdeps" and install the oldest version of each dependency specified in your `pyproject.toml` file. Make sure to review the output to ensure that the correct versions are being installed.

With this setup `tox` will directly use your `pyproject.toml` file for dependency management.

**Comment by astrofrog** [comment]
Next prompt for ChatGPT: could you write the main plugin code for tox-oldest?

**Comment by MridulS** [comment]
Wait can't we do this with https://github.com/astropy/astropy/issues/16201? `--resolution=lowest-direct` is supported by uv and the oldestdep requirements can be spun up on demand with that.

**Comment by nstarman** [comment]
Yes please.
