### ISSUE TITLE
units: `abstractmethod`s for format base class

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#16374]
See original thread at ...
_Originally posted by @neutrinoceros in https://github.com/astropy/astropy/pull/16367#discussion_r1587174079_

**Comment by LucasToscanou** [comment]
Hello, I'm looking to work on a refactoring issue on Astropy. Can I try this one?

**Comment by nstarman** [comment]
Absolutely! We're looking to find methods on UnitBase which are abstract, e.g. raising NotImplemented, but not marked as such.

**Comment by eerovaher** [comment]
Abstract classes have abstract methods the presence of which prevents an abstract class from being instantiated. The `astropy` unit formatter classes are not meant to be instantiated at all, regardless of what they implement, so marking any methods as abstract would be fundamentally misleading. Furthermore, the way `Base.__new__()` is implemented interferes with how [`ABC`](https://docs.python.org/3/library/abc.html#abc.ABC) works, so abstract methods are not useful for the unit formatters in any technical sense either.

The real here question here is whether inheritance is the best way to avoid code duplication between the different formatters or if composition would have been a better pattern. `astropy.units` allows downstream packages to implement their own unit formatters by inheriting from one of ours, so it is stuck with this design, but in the context of Quantity 2.0 this might be worth thinking about.

**Comment by neutrinoceros** [comment]
I agree with this. As far as I understand, Quantity 2.0 doesn't fundamentally requires inheritance, which is great.
