### ISSUE TITLE
TST: What is ASTROPY_ALWAYS_TESTS_FITSIO actually used for?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16407]
I saw this because I don't think quotes work as expected in `tox.ini` but then I realize that this environment variable is used nowhere in the repository even though it is tied to a tox directive that is used in a job. It was added by @Cadair in #14252 with huge diff (`+5,365 −155,245`). @Cadair or @astrofrog , can you please explain what `ASTROPY_ALWAYS_TESTS_FITSIO` is actually used for? If not, can we remove it? Thanks.

https://github.com/astropy/astropy/blob/ddaa50b76ccf54648b8f3349d0e1a44a8e7472ed/tox.ini#L26

https://github.com/astropy/astropy/blob/ddaa50b76ccf54648b8f3349d0e1a44a8e7472ed/.github/workflows/ci_workflows.yml#L70

**Comment by Cadair** [comment]
https://github.com/astropy/astropy/blob/main/astropy%2Fio%2Ffits%2Fhdu%2Fcompressed%2Ftests%2Ftest_fitsio.py#L23

It's used to make that tox factor error if fitsio isn't installed for the fitsio tests

**Comment by pllim** [comment]
I think there is a missing "S" in the code. 

https://github.com/astropy/astropy/blob/ddaa50b76ccf54648b8f3349d0e1a44a8e7472ed/astropy/io/fits/hdu/compressed/tests/test_fitsio.py#L23
