### ISSUE TITLE
Possible speed-ups for `get_grouped_by_powers`

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#16424]
This function uses `.append`. It looks like with a simple helper function (defined externally to this function) we could use a list comprehension instead. I wonder if that would be faster — `append` versus function call overhead.

_Originally posted by @nstarman in https://github.com/astropy/astropy/pull/16392#discussion_r1591049850_

`itertools` has a recipe for this type of dual-list creation loop. Doing two loops at the C-level might be faster than 1 loop with constant appending.

**Comment by goldenphoenix713** [comment]
So I did some ``timeit`` tests with the following function definitions:

```python
import itertools

# The original function
def loop_func(bases, powers):
    positive = []
    negative = []
    for base, power in zip(bases, powers):
        if power < 0:
            negative.append((base, -power))
        elif power > 0:
            positive.append((base, power))
    return positive, negative

# List comprehension
def list_comp_func(bases, powers):
    num_bases = len(bases)
    negative = [(bases[ii], -powers[ii]) for ii in range(num_bases) if powers[ii] < 0]
    positive = [(bases[ii], powers[ii]) for ii in range(num_bases) if powers[ii] > 0]
    return positive, negative
    
# Using itertools.tee
def itertools_func(bases, powers):
    l1, l2 = itertools.tee((x > 0, x) for x in powers)
    positive, negative = ([(x, z) for x, (y, z) in zip(bases, l1) if y],
                          [(x, -z) for x, (y, z) in zip(bases, l2) if not y])
    return positive, negative
```

I then ran the following:

```python
from timeit import timeit
from astropy.units import *

bases = [m, s, kg, A, cd, rad, K, mol]  # All the base SI units
powers = [1, -2, 1, 3, -2, 1, 4, 3]  # Randomly selected powers

x = timeit(stmt=lambda: loop_func(bases, powers))
y = timeit(stmt=lambda: list_comp_func(bases, powers))
z = timeit(stmt=lambda: itertools_func(bases, powers))
```

and got ``x, y, z => 1.045156035979744, 1.1819853900233284, 2.542474016023334``

I've tried converting to numpy arrays, but at some point it still uses a list comprehension or zip, so they end up taking longer than these functions here.

It may be that the append approach might actually be the fastest method if using just python, probably because it's still looping through the arrays once. Even just replacing the ``zip`` in ``loop_func`` with a ``range`` approach 

```python
def loop_range_func(bases, powers):
    positive = []
    negative = []
    num_bases = len(bases)
    for ii in range(num_bases):
        base = bases[ii]
        power = powers[ii]
        if power < 0:
            negative.append((base, -power))
        elif power > 0:
            positive.append((base, power))
    return positive, negative
```
only results in a speed increase to ``0.9854398609895725``, which is not significant.

If someone can come up with a way to do this using a single list comprehension, that might be faster, but I'm unsure how to do that.

**Comment by nstarman** [comment]
Thanks for looking into this!

**Comment by julian-8897** [comment]
@nstarman Hi there, I'm a first time contributor for astropy and would like to look into this if its still available?

**Comment by nstarman** [comment]
Hi @julian-8897! Thanks for your interest in Astropy. While this Issue is still open, I would caution against taking it as a first issue. @goldenphoenix713 did a great job demonstrating why it would probably require some dark magic to make this meaningfully faster. If you're interested in other contributions I'd be happy to suggest open Issues, or new ideas, depending on what in Astropy you're interested in / what your technical background is!

**Comment by julian-8897** [comment]
Hi @nstarman , thanks for the quick response. Ah i see,  I'm open to any suggestions actually! To be honest I haven't used astropy myself yet, but I'm generally interested in helping out with new features or even quality of life improvements. I'm currently an Astrophysics PhD , mostly working on machine learning problems , and previously did my degree in physics/CS. I do have minimal experience in open source contributions , as i helped out a bit with scikit-learn and im currently working on some minor contributions in pyro!

**Comment by nstarman** [comment]
We don't currently have many integrations with scikit-learn. Integrative contributions would be very appreciated!
On pure astropy fronts `astropy.cosmology` has a mostly-broken integration with `astropy.modeling`.
Fixing, testing, and writing tutorials for this feature would be awesome. We aim to make these tutorials citable (https://github.com/astropy/astropy-tutorials/issues/158).
A related idea is an `astropy.cosmology` <-> `pyro` I/O.
QoL improvements could be adding type annotations (e.g. #16562).

**Comment by julian-8897** [comment]
Great, thanks for the suggestion! I'll probably start with something simple like type annotations/DOCs so I can learn how eg. `astropy.cosmology` , `asttropy.modeling` are structured. Would be very useful to have a nice integration with `pyro` or even `numpyro` to use their jax backend.
