### ISSUE TITLE
numpy 2 compat: tests failing with default print options

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16423]
We currently have about 400 tests that don't pass against numpy 2.0 if we remove the following line

https://github.com/astropy/astropy/blob/b2e38be321ac6fb0c844704cbd4be1d1bf511b9b/astropy/conftest.py#L28

90% of the solution is already isolated in #16416, and we can probably extract backportable solutions for the other 10% from #15065. 

I'm seeing ~400 failures (doctests included) on main, 90% of which are resolved by #16416, but not all of what's left are doctests, which, as discussed in #15095, are not critical and can be post-poned to after numpy 2.0.0 final comes out (supposedly this would be for astropy 7.0.0)

Everything that's *not* a doctest, and not already fixed in #16416, should probably be addressed for 6.1.1

Affected modules:
- `coordinates` (1 test) #16427
- `io.fits` (4 tests) #16426
- `io.votable` (15 tests) #16442
- `table` (7 tests) #16433
- `utils` (2 tests) #16426 and #16443

I expect solutions were already found by @mhvk in #15065, so it's mostly a matter of making targeted cherry-picks.

**Comment by neutrinoceros** [comment]
note for later: I think one of the failures we got in `utils` is showing an discrepency between how masked arrays are represented (`repr`) with respect to ordinary arrays in numpy 2.0. This may be something to report upstream but I need to dig further.

**Comment by mhvk** [comment]
Maybe an idea is to merge #15065 for main, and then backport pieces of that? In any case, it seems sensible for me to rebase that...

**Comment by neutrinoceros** [comment]
Actually what I'm finding out thusfar is that the failures I'm pointing to in this issue are *not* resolved by #15065, and require their own solution. Since they are related but separable problems, I don't think we need to discuss this here.

**Comment by pllim** [comment]
Is this issue a duplicate of this?

* https://github.com/astropy/astropy/issues/15095

**Comment by mhvk** [comment]
@neutrinoceros - in rebasing #15065, I found test failures with pandas which are not representation-related. Are those among those you are thinking of? Also, if `bottleneck` is installed, some representations from sigma clipping look different...

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/issues/16423#issuecomment-2103168603

Nevermind, I just saw https://github.com/astropy/astropy/issues/15095#issuecomment-2102815320

**Comment by neutrinoceros** [comment]
re https://github.com/astropy/astropy/issues/16423#issuecomment-2102966432:
I'm now thinking the bug is actually on our side, specifically in `MaskedFormat.__call__`, but I don't have time to fix it just now. VOTable failures are also a puzzle and are possibly related, so I think `utils.masked` should be the next priority. I'll come back to it later today if time allows.

**Comment by neutrinoceros** [comment]
Upon a closer look at #15065, it seems that it already has solutions for both `utils` (d84166e7ce00b5cae8b2503de5b8b8600d5e2180) and `votable` (940e5e74a008b9c053a3883d9c16dbbc9b14f64b).
Unless we changed our minds about waiting for numpy 2.0 final to merge #15065, I think these ought to be cherry-picked and backported. What do you think @mhvk ?

**Comment by mhvk** [comment]
I actually wondered about whether we shouldn't just merge #15065 for main, and then backport the commits that do not have to do with the documentation (i.e., docs for 6.1 stay at numpy < 2.0 format). Though perhaps effectively that is the same amount of work...

**Comment by neutrinoceros** [comment]
I think it's very much a comparable effort and not a big undertaking for us two, but the cherry-picking approach should make reviewing easier. If you agree to it, it shouldn't take me long to finish cherry picking the user-facing parts (only two more PRs).

**Comment by mhvk** [comment]
OK, let's go that route - then #15065 will probably get in when numpy 2.0 is out (just saw rc2 was released).

**Comment by neutrinoceros** [comment]
Done with #16442 and #16443

**Comment by neutrinoceros** [comment]
numpy 2.0 has a release date: https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448

I'd recommend merging the remaining PRs related to this issue and cutting a 6.1.1 release before june 16th
FYI @astrofrog @saimn @mhvk @pllim

**Comment by pllim** [comment]
So is it just https://github.com/astropy/astropy/pull/16427 and #16433 left?

**Comment by neutrinoceros** [comment]
Yes !

**Comment by pllim** [comment]
When they are all in, do we need a follow-up issue to get rid of `without_legacy_printoptions` in the future? Or do we already have such issue?

**Comment by neutrinoceros** [comment]
I don't expect it to get in the way of anyone so it should be very low priority, but I *do* have a personal reminder to clean it up when the time comes.
That said, your phrasing seems to imply that not having an issue isn't an option, so let me open one now :)

**Comment by pllim** [comment]
> imply that not having an issue isn't an option

Well, I can't arrest you or anything... 😸 Thanks for opening the issue! It is good to have it out in the open to show people we're aware of it.

**Comment by neutrinoceros** [comment]
> I can't arrest you or anything

Let's call it making me an offer I can't refuse :)

**Comment by neutrinoceros** [comment]
Alright, everything was merged, let's close this ! thanks !
