### ISSUE TITLE
Describe "phase" parameter in astropy.modeling.functional_models.Sine1D and astropy.modeling.functional_models.Cosine1D

### ISSUE THREAD

**Issue by janerigby** [astropy/astropy#16470]
### What is the problem this feature will solve?

The documentation for astropy.modeling.functional_models.Sine1D should describe the units of the  "phase" parameter. Since it does not, its not clear to the user whether that parameter has the same units of the x-axis (which I would call an x-offset, not a phase), or is it phase in the sense of an angular offset (units of degrees or radians).
 

### Describe the desired outcome

Add description of the "phase" parameter to the documentation of Cosine1D and Sine1D, including units

**Comment by nden** [comment]
Looking at the[ issue](https://github.com/astropy/astropy/issues/3807) and [the code that added it](https://github.com/astropy/astropy/pull/3940), it was meant as an x- offset. I'm labeling this as a good issue for first time contributors.

**Comment by HimalayanSaswataBose** [comment]
May I know, in brief, what exactly needs to be solved? Is it just meant to be a documentation update?

**Comment by janerigby** [comment]
yes, just a documentation update

**Comment by pllim** [comment]
@janerigby , are you satisfied with the doc update proposed in https://github.com/astropy/astropy/pull/16602 ? Thanks!
