### ISSUE TITLE
Donate button redirects to random tech site

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16480]
We have this in `README.rst`:

```rst
.. |Donate| image:: https://img.shields.io/badge/Donate-to%20Astropy-brightgreen.svg
    :target: https://numfocus.salsalabs.org/donate-to-astropy/index.html
```

But https://numfocus.salsalabs.org/donate-to-astropy/index.html redirects to https://www.bonterratech.com/ instead of a page where people can, uh, donate. The link was last updated 5 years ago via https://github.com/astropy/astropy/pull/8512 by @lisamartin72 .

**Comment by pllim** [comment]
I see https://github.com/astropy/astropy.github.com/pull/312 linked to that original PR too, so https://www.astropy.org/contribute.html#contribute-financially is also broken.

**Comment by pllim** [comment]
`tupui` said maybe https://opencollective.com/astropy but the Contribute section is empty. 🤷‍♀️

**Comment by stefanv** [comment]
For NumPy, [we've also linked](https://numpy.org/about/#donate) to OpenCollective. If you are not already an admin on opencollective/astropy, ask Arliss to add you. You can then configure your page to look like https://opencollective.com/numpy or https://opencollective.com/scipy or https://opencollective.com/scikit-image.

**Comment by pllim** [comment]
Nicole from NumFOCUS said to use https://numfocus.org/donate-to-astropy 🤷‍♀️

**Comment by pllim** [comment]
Thanks for the info anyway, @stefanv . Good to know there are alternatives!
