### ISSUE TITLE
`wcs_info_str` doesn't play nice with numpy 2.0 reprs

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#16585]
### Description

https://github.com/astropy/astropy/blob/main/astropy/wcs/wcsapi/utils.py#L36

See this example of how the repr is ugly with numpy 2 in this ndcube PR: https://github.com/sunpy/ndcube/pull/729/files#diff-ebd49ed76e6cc53d57fd47500f57f6227378a7c65189a5ead08dad31f42d7127R20-R41

### How to Reproduce

1. Make a wcs
2. look at output of wcs_info_str

**Comment by neutrinoceros** [comment]
Hum, looks like an oversight in our testing. We should probably tackle it for astropy 6.1.2 . Looking into it now

**Comment by astrofrog** [comment]
Related but separate issue:

```python
In [30]: wcs = WCS(naxis=1)

In [31]: print(wcs)
WCS Keywords

Number of WCS axes: 1
CTYPE : '' 
CRVAL : np.float64(0.0) 
CRPIX : np.float64(0.0) 
PC1_1  : np.float64(1.0) 
CDELT : np.float64(1.0) 
NAXIS : 0  0
```

**Comment by neutrinoceros** [comment]
How ? I can't reproduced this one. Here's what I get locally with astropy (main) and numpy 2.0.1:
```python
>>> from astropy.wcs import WCS
>>> print(WCS(naxis=1))
WCS Keywords

Number of WCS axes: 1
CTYPE : ''
CRVAL : 0.0
CRPIX : 0.0
PC1_1  : 1.0
CDELT : 1.0
NAXIS : 0  0
```
