### ISSUE TITLE
Provide a way to make a copy of a model with different parameter values, or be more flexible with parameter shape

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#16593]
GIven a model with scalar or array parameters, I would like to be able to easily make another model which has different parameter values (either scalar or array), while preserving other things (e.g. constraints, polynomial degree, etc). One can try the naive approach of making a copy of the model and then changing the parameters, but this doesn't always work:

### Common imports

```python
from astropy.modeling.models import Polynomial1D

import numpy as np
```

### Scalar :arrow_forward: Scalar

This case works fine:

```python
poly = Polynomial1D(2, c0=1, c1=3, c2=5)
poly.c0.fixed = True
poly.c1.bounds = [0, 10]

poly2 = poly.copy()
poly2.c0=1.5
poly2.c1=3.2
poly2.c2 = 5.5
```

### Array :arrow_forward:  scalar

```python
poly = Polynomial1D(2, c0=np.ones((10, 10)), c1=np.ones((10, 10)) * 3, c2=np.ones((10, 10)) * 5)
poly.c0.fixed = True
poly.c1.bounds = [0, 10]

poly2 = poly.copy()
poly2.c0=1.5
poly2.c1=3.2
poly2.c2 = 5.5
```

This works ok because scalars are broadcastable to arrays. This is not ideal though as one temporarily has a copy of all the arrays in memory, and if the arrays are big it might be annoying.

### Array :arrow_forward: array

This does not work if the new array shape is not broadcastable to the old one:

```python
poly = Polynomial1D(2, c0=np.ones((10, 10)), c1=np.ones((10, 10)) * 3, c2=np.ones((10, 10)) * 5)
poly.c0.fixed = True
poly.c1.bounds = [0, 10]

poly2 = poly.copy()
poly2.c0=np.arange(5)
```

The error is:

```
InputParameterError: Value for parameter c0 does not match shape or size
expected by model ((5,), 5) vs ((10, 10), 100)
```

### Scalar :arrow_forward: Array

This does not work at all:

```python
poly = Polynomial1D(2, c0=1, c1=3, c2=5)
poly.c0.fixed = True
poly.c1.bounds = [0, 10]

poly2 = poly.copy()
poly2.c0=np.arange(5)
```

the error is:

```
InputParameterError: Value for parameter c0 does not match shape or size
expected by model ((5,), 5) vs ((1,), 1)
```

### Possible solutions

One option would not be to check the dimensions whenever parameters are set, but to instead validate them at the point where the model is called - otherwise it is not possible to change the parameters to have a shape that is not broadcastable to the current one.

Another option would be to have a way to do e.g. ``poly.copy_with_new_parameters(c0=np.arange(5), ...)`` or similar, that is, do a copy but replace the parameter *value* with the ones provided in the method call.

I'm open to other ideas though!

**Comment by nstarman** [comment]
https://github.com/astropy/astropy/pull/15750 would have worked for this.
`replace` is the new paradigm for dataclasses (which `astropy.models` are conceptually, if not in actual code).
`singledispatch` allows for us to make a function in astropy (or better yet a companion utility library), called `replace` that dispatches like this:

```
@singledispatch
def replace(obj: Any, /, **kwargs: Any) -> Any:
    raise NotImplementedError

@replace.register  # a superset of python's dataclasses.replace!
def replace(obj: DataclassInstance, /,  **kwargs: Any) -> DataclassInstance:
    from dataclasses import replace
    return replace(obj, **kwargs)

@replace.register  # it works on anything!
def replace(obj: AstropyModel, /, **kwargs: Any) -> AstropyModel:
    ... whatever mechanism we want
    return newobj
```

**Comment by astrofrog** [comment]
Ok so after digging into this further, it *is* possible to get some of these examples to work by setting the parameter value instead of the top-level parameter, so e.g.:

```
poly = Polynomial1D(2, c0=1, c1=3, c2=5)
poly.c0.fixed = True
poly.c1.bounds = [0, 10]

poly2 = poly.copy()
poly2.c0.value=np.arange(5)
```

works, and if parameters are set with incompatible shapes an error is raised at model evaluation time, which I think is sensible. I guess the question is then should ``Model.__setattr__`` be more permissive to match what is possible by setting ``Parameter.value`` directly?

**Comment by astrofrog** [comment]
See #16710 for a bug that occurs when doing this though
