### ISSUE TITLE
Issues in RTD builds

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#16594]
https://github.com/astropy/astropy/blob/33bb428cc5816e118bba818692846dac2d601b6f/astropy/time/core.py#L1666-L1668

numpy 2.0 doesn't have the p2p attribute, so this is causing docs failures.

**Comment by neutrinoceros** [comment]
Wait wasn't this already solved with #16583 ?

**Comment by nstarman** [comment]
That would be great.
Didn't see that. I was seeing the docs failure in #16562.

**Comment by nstarman** [comment]
Which is still there.

**Comment by neutrinoceros** [comment]
I would assume à rebase would solve this ?

**Comment by jeffjennings** [comment]
Just rebased and it did fix it yes, thank you both! It was very confusing.

**Comment by mhvk** [comment]
Part of the problem was that the issue only appeared when the numpy documentation got updated - which is when the link broke.

Though it would also be helpful if the build log ends with a repeat of the warnings that are raised inside!

Anyway, closing this, since the issue itself seems solved.
