### ISSUE TITLE
DOC: CFITSIO missing from "External C Libraries" section in dev docs

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16623]
As I found out while reviewing https://github.com/astropy/astropy/pull/16561 . See https://github.com/astropy/astropy/pull/16561#discussion_r1655523403

Was the omission intentional?

**Comment by dhomeier** [comment]
It's not strictly bundling the library anymore, only including a small number of sources files. Not clear to me if they will still be needed after #15474, but so far they have not been removed.

**Comment by saimn** [comment]
We now just copy a few files, not the full library, and don't allow building with an external one.
