### ISSUE TITLE
MNT: migration to ruff 0.5.0

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16621]
This blogpost just dropped: https://astral.sh/blog/ruff-v0.5.0#migrating-to-v05
Since there's a migration guide I expect the upgrade might not be smooth enough for a pre-commit.ci bot PR to handle correctly.
In particular these sections might need a careful look:
- https://astral.sh/blog/ruff-v0.5.0#rule-remappings
- https://astral.sh/blog/ruff-v0.5.0#stabilized-rules

However v0.5.0 is not available just yet so I can't confirm or deny there's an actual problem here.

I'll try it out tomorrow unless someone else beats me to it !

**Comment by pllim** [comment]
Thanks for the heads up!

cc @nstarman and @eerovaher 🤞

**Comment by zanieb** [comment]
Let us know if there was anything that made the transition difficult or problems with the stabilized rules!

**Comment by neutrinoceros** [comment]
@zanieb thank you !
Overall nothing really problematic, but we noticed in discussions that [SIM103](https://docs.astral.sh/ruff/rules/needless-bool/) could subtly break API for functions that return a `bool`. For instance
```python
def is_positive(a):
	return a > 0
```
isn't strictly equivalent to
```python
def is_positive(a):
	if a > 0:
		return True
	else:
		return False
```
because the latter guarantees the return type is `bool`, while the former may return a `np.bool` if, for instance `a=np.float64(1.0)`. 
It's good that this particular rule isn't autofixable without `--unsafe-fixes`, but I feel like the reasons *why* it's unsafe to fix is lacking from the documentation.

**Comment by neutrinoceros** [comment]
FYI Ruff 0.6 is out and also has its own migration guide: https://astral.sh/blog/ruff-v0.6.0
