### ISSUE TITLE
AltAz origin is not the same as `location` parameter

### ISSUE THREAD

**Issue by Joshuaalbert** [astropy/astropy#16637]
### Description

This is likely me not understanding something, and not a bug. I was assuming that in AltAz frame that the `location` parameter lines up with the origin of the frame, but that doesn't seem to be the case. Can someone explain why?

### Expected behavior

I expected that the origin of the AltAz frame corresponds to the observing `location`.

### How to Reproduce

```python
import numpy as np
from astropy import time as at, coordinates as ac, units as au

def test_altaz_origin_maps_to_location():
    time = at.Time("2021-01-01T00:00:00", scale='utc')
    location = ac.EarthLocation.of_site('vla')
    coord = ac.AltAz(alt=0. * au.deg, az=0. * au.deg, distance=0.0 * au.m, obstime=time, location=location)
    coord_itrs = coord.transform_to(ac.ITRS(obstime=time))
    location_itrs = location.get_itrs(obstime=time)
    print("Separation:", coord.separation_3d(location_itrs))
    np.testing.assert_allclose(coord_itrs.cartesian.xyz, location_itrs.cartesian.xyz, atol=1e-6 * au.m)
```

### Versions

```
Linux-5.15.0-107-generic-x86_64-with-glibc2.31
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
astropy 6.1.0
Numpy 1.26.4
pyerfa 2.0.1.4
Scipy 1.10.1
Matplotlib 3.7.1
```

**Comment by ayshih** [comment]
This sounds to be the same issue that you previously encountered: https://github.com/astropy/astropy/issues/16317#issuecomment-2068394464

**Comment by Joshuaalbert** [comment]
Ah, I had forgotten that. Thanks for the quick reply!
