### ISSUE TITLE
Returned type of astropy.stats.interval_overlap_length

### ISSUE THREAD

**Issue by bkhelifi** [astropy/astropy#16641]
### What is the problem this feature will solve?

The function interval_overlap_length returns in some cases a TimeDelta instance and not a float as stated in the docstring

### Describe the desired outcome

Either always return a TimeDelta or a float

**Comment by pllim** [comment]
> some cases

Can you please clarify and provide minimally reproducible examples of when it does return the type you want and when it does not? And what astropy version are you using? Thanks!

**Comment by pllim** [comment]
Yes, docstring does say float only.

https://github.com/astropy/astropy/blob/03ed5f81177190532fdcf6c049cd288414c7b3c2/astropy/stats/funcs.py#L1550-L1561 

I guess a strict check can be added but that would be at the cost of performance, which I think is probably important for such a low-level function in `stats`.

Therefore, I agree with you that this issue can be closed. Thank you for reaching out!
