### ISSUE TITLE
Changelog entries for performance improvements

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#16679]
Currently, one can only have feature/bugfix/api changelog entries in sub-packages - there is 'other' but it has to be at the root of the package. However, it's not clear where to put performance improvements. They are not really features, and putting them all in 'other' at the root of the changelog entries is not right because they might be attached to a specific sub-package.

* Option 1: add a new 'perf' changelog type
* Option 2: allow 'other' entries to be in specific sub-packages

We might also run into this in other respects, for examples adding typing hints to public API might be worth mentioning but are not really features. So perhaps Option 2 makes more sense as we can't create types for every single possible type of change?

Does anyone have any thoughts?

**Comment by neutrinoceros** [comment]
I'd vote for *both* options.

**Comment by pllim** [comment]
I think there was a specific reason we disallowed "other" in subpackages, so no point backtracking now? I vote (1).

**Comment by astrofrog** [comment]
I also think we should do at least option 1 for now as that seems uncontroversial.

**Comment by mhvk** [comment]
I think adding a few more possibilities is fine; I'm OK with adding "typing" too. Indeed, could basically follow the labels we have ("docs" might be useful once in a while too).

**Comment by pllim** [comment]
Keep in mind that, to be consistent, for each new category you add, we have to do due diligence and comb through all the fragments for v7.0 and move them to the new categories if applicable.

**Comment by astrofrog** [comment]
Can docs and typing be lumped together? Typing is a type of documentation right?

**Comment by saimn** [comment]
:+1: for adding a performance category.
The "restriction" for `other` comes from before the towncrier epoch, I think the idea was to avoid having a catch-all that people would use too easily. And I think it's a good thing, forcing people to choose if it's a bug or a feature ;). And it's easy now to add some categories, it helps choosing a milestone, it makes the changelog easier to parse. Numpy, Scipy or Pandas have plenty of them (e.g. https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#performance-improvements).
