### ISSUE TITLE
BUG/PERF: defects introduced in #16187

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16693]
Daily cron is currently failing ([example logs](https://github.com/astropy/astropy/actions/runs/9867467912/job/27247890544)), and the error looks a lot like one that slipped in #16187 but was only visible in allowed-failure jobs which is probably why we overlooked it.
I'm going to take a look now but I only have a couple hours on my hands today so in case I don't find a solution quickly, FYI @ayshih, @mhvk

**Comment by neutrinoceros** [comment]
The failing test turned out trivial to fix:
```patch
diff --git a/astropy/utils/iers/tests/test_iers.py b/astropy/utils/iers/tests/test_iers.py
index f1cf188446..4a71364c9d 100644
--- a/astropy/utils/iers/tests/test_iers.py
+++ b/astropy/utils/iers/tests/test_iers.py
@@ -480,7 +480,7 @@ def test_iers_download_error_handling(tmp_path):
                     "malformed IERS table from https://google.com"
                 )
                 assert str(record[2].message).startswith(
-                    "unable to download valid IERS file, using local IERS-A"
+                    "unable to download valid IERS file, using bundled IERS-A"
                 )
```
Now let me see if I can see what's taking so long.

**Comment by mhvk** [comment]
Very quick comment: it may be downloading more recent IERS-A?

**Comment by neutrinoceros** [comment]
That's my assumption, but I'm having a hard time tracking exactly where or why.
A simple way to reproduce the issue locally is to focus on a single test, e.g. ` pytest astropy/coordinates/tests/test_erfa_astrom.py::test_interpolation_nd`  (from 0.2s to 6s locally)

**Comment by neutrinoceros** [comment]
It doesn't look like I'm going to nail it down today, so I've opened the revert PR #16695 so it's available for merging in case we can't find a better fix quickly.

**Comment by ayshih** [comment]
Gah, okay, I'll look into this right now

**Comment by ayshih** [comment]
Auto-downloading is off for most of the test suite, as it should be.  The bug is that I inadvertently broke the storage of the IERS_A+IERS_B table, so every retrieval of that table would recreate the table from the files.  I'll put up a PR shortly.

**Comment by neutrinoceros** [comment]
Awesome. Feel free to include my patch from https://github.com/astropy/astropy/issues/16693#issuecomment-2219816334
