### ISSUE TITLE
Splitting unit and functional tests

### ISSUE THREAD

**Issue by gaehlerm** [astropy/astropy#16727]
### What is the problem this feature will solve?

Hi everyone

I just stumbled over this project. Here are some thoughts of a random guy:

Your project looks great.
But: Your tests are not optimal for several reasons:
- They are slow. Slow tests are not run often. -> separate fast (<10ms) unit tests and slow (>10ms) functional tests such that the unit tests can be run all the time within seconds.
- Unit tests should not read files. Unit tests should not depend on anything. -> store the content of the file as a string in the test code.
- Parametrizing tests looks like a good idea but it makes tests redundant. If one test fails, they all fail. -> I'm not sure if this makes the test coverage better, especially not with ~16 parameters. But it certainly makes the test execution slower.
- The code of a test should be very short, possibly only about 3 lines. -> Write helper funcitons. This also helps to reduce redundancy in the test code.

Of course, it will take quite a while to fix these issues.

### Describe the desired outcome

- The tests should be faster (at least the unit tests) and more stable (not depend on files). All tests should be more maintainable (less copy-paste code). 
- Maybe add a few lines to the testing guidelines?

**Comment by pllim** [comment]
Thank you for your thoughts!

So, at a high level, what would be the next step in your mind after the unit tests and functional tests are split out? The main goal of these tests is to make sure we reduce the risk of bugs being accepted into `main` and release branches. So, in the end, I think we need to run both unit and functional tests regardless.

**Comment by gaehlerm** [comment]
Splitting up the tests is the main thing to do. And if the tests coverage of the unit tests alone is too low, you'll have to write more unit tests. That will be a lot of work. But it will be worth it. Just imagine: you can click a button and it shows you within a few seconds if your code works.

If you have good test coverage with unit tests, it happens rarely that the functional tests find a bug.

I think you have to raise the awareness among the developers that unit tests are the foundation of the testing pyramid, not functional tests.

If you have more questions about my reasoning, I'm writing a book where testing it a part of it. See chapters 18-20, https://github.com/gaehlerm/SoftwareEngineering

**Comment by gaehlerm** [comment]
I did some rough benchmarking. Most tests take more than 10ms and are too slow for being unit tests. But maybe it's still worth puting the "really slow" (>50ms) tests into separate groups of tests and reduce the number of parameters in the parametrized tests. This could already speed up the execution time of the tests considerably.
