### ISSUE TITLE
TST: instability with setuptools 71

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16745]
Opening this for visibility: we're affected by an upstream issue in setuptools 71: https://github.com/pypa/setuptools/issues/4480
[example logs](https://github.com/astropy/astropy/actions/runs/9984799855/job/27594624812)

Note that it *seems* related but I'm not positive it's the exact same bug: between CI and local runs I'm actually seeing different failure modes, but they all seem related to this one bug so I don't think it's worth the effort of disentangling everything yet (hopefully the situation will be much clearer after another prompt bugfix release)

**Comment by pllim** [comment]
Is this weird error related or is it something else?

https://github.com/astropy/astropy/actions/runs/9989982778/job/27609737144?pr=16746

```
>       assert minversion("yaml", "3.1")
E           DeprecationWarning: Implicit None on return values is deprecated and will raise KeyErrors.
```

**Comment by neutrinoceros** [comment]
As far as I understand it seems related: importing the newest setuptools affects (and might break) `importlib.metadata`.

**Comment by pllim** [comment]
Should we pin setuptools for now then?

**Comment by neutrinoceros** [comment]
No need to: 71.0.2 was just released and appears to resolved this.

**Comment by neutrinoceros** [comment]
I've opened https://github.com/scientific-python/pytest-doctestplus/pull/258 to reduce the "attack" surface so we don't pull in setuptools at runtime if we can avoid it.
