### ISSUE TITLE
How to change the type of WCS axis

### ISSUE THREAD

**Issue by Firestar-Reimu** [astropy/astropy#16757]
### What is the problem this feature will solve?

I want to read a FITS file from https://hiverse.alkaidos.cn/ (you can download any one to reproduce this)

But it returns:

```python
from spectral_cube import SpectralCube as sc
file = "00_DEC_-13.0_-3.0__06_RA_60.0_70.0__-600kms_600kms.I.fits"
sc.read(file)
```

```
ValueError: No celestial axes found in WCS
```

So I checked this:

```python
>>> wcs.get_axis_types()
[{'coordinate_type': None, 'scale': 'linear', 'group': 0, 'number': 0},
 {'coordinate_type': None, 'scale': 'linear', 'group': 0, 'number': 0},
 {'coordinate_type': 'spectral', 'scale': 'linear', 'group': 0, 'number': 0}]
```

This indicates that the first 2 axis, which is `RA` and `DEC`, should have `type='celestial'` but now `None`

How can I change them to `celestial` and write it to a new FITS file?

### Describe the desired outcome

make something like `wcs.set_axis_types()`

### Additional context

Maybe this is spectral-cube's fault, as their method is too limited.

**Comment by Firestar-Reimu** [comment]
I found that if I change this:

```python
header['CTYPE1'] = 'RA---CAR'  # originally 'RA--CAR'
header['CTYPE2'] = 'DEC--CAR'  # originally 'DEC-CAR'
```

then the type will be `celestial`, do you have any opinions on this?

**Comment by astrofrog** [comment]
``RA--CAR`` is incorrect and not standard-compliant, which is why there was an issue, and ``RA---CAR`` is indeed correct.

**Comment by pllim** [comment]
So, if I understand correctly, it is the data header that is actually wrong and the data provider should fix? I don't see anything to fix here in `astropy`. Can we close this issue? Thanks!
