### ISSUE TITLE
v6.1.2 has RTD warning and failed doc build

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16764]
Failed with 1 warning: `v6.1.2/docs/install.rst:57: WARNING: undefined label: 'astropy-dev:virtual_envs'`

Solution: Change it to direct URL. It broke due to https://github.com/astropy/astropy/pull/16561 .

I think this blocks v6.1.3. Any fix should be directly to `v6.1.x` branch.

**Comment by neutrinoceros** [comment]
@pllim can we close this now or is there anything left to do ?

**Comment by pllim** [comment]
Oh weird that my PR did not auto close this. Thanks for the ping!
