### ISSUE TITLE
DOC: Linkcheck is broken until matplotlib 3.9.2 is released

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16804]
Backstory: We need `matplotlib>=3.9.1` for doc to build without warning but 3.9.1 was yanked from PyPI due to bad Windows wheel. We worked around that in https://github.com/astropy/astropy/pull/16798 by grabbing matplotlib 3.9.1 from conda-forge for RTD but that still breaks linkcheck that installs exclusively from PyPI. I was willing to accept that temporary breakage rather than forcing `==3.9.1` pin to forcefully grab something that was yanked. So, until matplotlib releases 3.9.2, expect linkcheck to not work. It should "magically" work again when matplotlib releases and we can close this. But we can also remove this:

https://github.com/astropy/astropy/blob/aea0ce95d11a243776629b3fda7b0c43a1dd9ecf/docs/rtd_environment.yaml#L9

**Comment by eerovaher** [comment]
> Backstory: We need `matplotlib>=3.9.1` for doc to build without warning...

Do we? I thought we needed `matplotlib!=3.9.0`.

**Comment by pllim** [comment]
No, I think we did need 3.9.1 to pick up a fix. Please see https://github.com/astropy/astropy/pull/16681

**Comment by eerovaher** [comment]
But that fix is for a problem that was introduced in 3.9.0, so anything older than that shouldn't need it.

**Comment by pllim** [comment]
Okay, let's see... https://github.com/astropy/astropy/pull/16808
