### ISSUE TITLE
TST: Un-ignore __array__ warning when h5py 3.12 is released

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16815]
Wait till https://github.com/h5py/h5py/pull/2416 is released as part of h5py 3.12, then we can remove this that was added in https://github.com/astropy/astropy/pull/16814:

https://github.com/astropy/astropy/blob/c02979aba6ccaa51e0235537d71019d112d3b013/pyproject.toml#L228-L229

cc @neutrinoceros

**Comment by neutrinoceros** [comment]
Do we use h5py on weekly cron ? If so, it might take a bit longer for exotic archs to catch up with PyPI

**Comment by pllim** [comment]
At a glance, I do not think so, but it would be obvious when the PR is out. 😉 

https://github.com/astropy/astropy/blob/main/.github/workflows/ci_cron_weekly.yml
