### ISSUE TITLE
magnetic energy density is not computable in all systems

### ISSUE THREAD

**Issue by johannct** [astropy/astropy#1687]
I am reproducing here the main questions I raised in an astropy-dev email (oct. 2013):
If we stay in SI:

```
In [1]: B=1.*u.T  #B=1 Tesla 
In [2]: H=B/cst.mu0 # H= B/mu0 valid outside of a magnetizable medium
In [3]: H
Out[3]: <Quantity 795774.7154594767 A2 T / N>
In [4]: H.to(u.A/u.m)
Out[4]: <Quantity 795774.7154594767 A / m>
```

First issue (unless I am missing some aspects of the problem) is that it seems more adequate to end up with A/m units for the H-field. But anyway, this yields the energy density:

```
In [5]: rho=0.5*B*H # strict definition of the energy density
In [6]: rho
Out[6]: <Quantity 397887.35772973835 A2 T2 / N>
In [7]: rho.to(u.erg/u.cm**3)
Out[7]: <Quantity 3978873.5772973844 erg / cm3>
```

which is correct (1.e8/8pi) in cgs gaussian units as well (ergs/cm3 and B^2/8pi equivalent computation). The problem is that assigning rho=0.5_B_H does not work in cgs:

```
In [8]: Bcgs=1.e4*u.gauss
In [9]: Hcgs=Bcgs/4./pi # this should really be Hcgs=1.e4*u.oersted or u.Oe as you prefer
In [10]: 0.5*Bcgs*Hcgs # then this would be units G*Oe that should be recognized as compatible with a pressure (or energy-density type) quantity
Out[10]: <Quantity 3978873.577297384 G2>
In [11]: rho_cgs=0.5*Bcgs*Hcgs
```

The last line has G2 units which is not recognized as a pressure-type unit, and the conversion to erg/cm3 fails as well. 
So first of all Oersted should be defined, with an equivalence to A/m rather than G. But ideally we would need a mechanism to account for what G2 really is in cgs gaussian. 
And of course, the more general problem is that there are several EM cgs systems, so my approach above is perhaps overly naïve.

**Comment by mhvk** [comment]
Removing the milestone per @astrofrog's request to leave only critical issues, but it would be good to address this one! @mdboom - would you have a suggestion? It does seem difficult to generalize the problem such that `Guass**2` becomes equivalent both to a pressure and an energy density; after all, how does the code know whether things have been divided by 4π or 8π? Still we probably should at least define `u.Oe`?

**Comment by johannct** [comment]
I still think that the Oersted definition is not the most useful one, as far as I can remember

**Comment by Alkalin** [comment]
That is because you have obtained a value ( 397887.35772973835 ) that means a half of inverse of permeability of free space, and is a virtual length and surface (both of them, is not a mistake).

**Comment by mhvk** [comment]
closing in favour of meta issue #4359
