### ISSUE TITLE
BUG: tables do not deal well with zero-sized string columns

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#16897]
### Description

@saimn [noted](https://github.com/astropy/astropy/pull/16894#issuecomment-2314640002) in #16894 that zero sized data are a problem:
```
import numpy as np
from astropy.io import fits
from astropy.table import QTable, Table
data = np.array([("", 12)], dtype=[("a", "S"), ("b", "i4")])
fits.BinTableHDU(data).writeto("zerodtable.fits", overwrite=True)
t = Table.read("zerodtable.fits")
t

File ~/dev/astropy/astropy/astropy/table/pprint.py:295, in TableFormatter._pformat_col(self, col, max_lines, show_name, show_unit, show_dtype, show_length, html, align)
    283 col_strs_iter = self._pformat_col_iter(
    284     col,
    285     max_lines,
   (...)
    290     outs=outs,
    291 )
    293 # Replace tab and newline with text representations so they display nicely.
    294 # Newline in particular is a problem in a multicolumn table.
--> 295 col_strs = [
    296     val.replace("\t", "\\t").replace("\n", "\\n") for val in col_strs_iter
    297 ]
    298 if len(col_strs) > 0:
    299     col_width = max(len(x) for x in col_strs)

File ~/dev/astropy/astropy/astropy/table/pprint.py:452, in TableFormatter._pformat_col_iter(self, col, max_lines, show_name, show_unit, outs, show_dtype, show_length)
    450 n_header += 1
    451 if dtype is not None:
--> 452     col_dtype = dtype_info_name((dtype, multidims))
    453 else:
    454     col_dtype = col.__class__.__qualname__ or "object"

File ~/dev/astropy/astropy/astropy/utils/data_info.py:100, in dtype_info_name(dtype)
     74 def dtype_info_name(dtype):
     75     """Return a human-oriented string name of the ``dtype`` arg.
     76     This can be use by astropy methods that present type information about
     77     a data object.
   (...)
     98         String name of ``dtype``
     99     """
--> 100     dtype = np.dtype(dtype)
    101     if dtype.names is not None:
    102         info_names = ", ".join(dtype_info_name(dt[0]) for dt in dtype.fields.values())

ValueError: invalid itemsize in generic type tuple
```
This problem is in displaying, not creating the table:
```
t["a"]
<MaskedColumn name='a' dtype='bytes0' length=1>
--
```
The display problem seems a bug in numpy - https://github.com/numpy/numpy/issues/27301 - but one we should work around for now.

Furthermore, `QTable` can read it, but changes the size
```
QTable.read("zerodtable.fits")
<QTable length=1>
  a      b  
bytes1 int32
------ -----
    --    12
```

This turns out to be because in `io`, for table subclasses, one does `QTable(table)` - and with a copy this changes the dtype.

**Comment by SmartManoj** [comment]
@neutrinoceros, Which commit should one use to reproduce this bug?

[Context](https://github.com/astropy/astropy/pull/16894#issuecomment-2661390195)

**Comment by neutrinoceros** [comment]
Any version older than 7.0 should do. Why do you want to reproduced already-solved issues ?

**Comment by SmartManoj** [comment]
It's for the [Kaggle Competition](https://www.kaggle.com/competitions/konwinski-prize) named [Konwinski Prize](https://kprize.ai/).


In that, this commit ee6d087baf301c1d08db92e6e5b6d909d57e6fac is mentioned as a base commit but the bug is not reproducible in this. [Notebook link](https://www.kaggle.com/code/smartmanoj/astropy-astropy-16898-with-net?scriptVersionId=222794558).

**Comment by pllim** [comment]
AFAIK this competition has nothing to do with Astropy Project, nor did we opt in to participate in it. This issue is already resolved. Nothing to fix here.
