### ISSUE TITLE
Request: drop python 3.10 support now (since it will not be needed for 7.0)

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#16900]
### What is the problem this feature will solve?

In a few recent PRs, it would have been handy to just rely on python >=3.11 feature (#16886 -- `Exception.add_note`, #16892 -- `warnings.catch_warnings(action=..., category=...)`. Since by the time of 7.0, we should be dropping support for python 3.10 anyway, how about going ahead and do that in `.dev` now?

### Describe the desired outcome

Less work-arounds.

### Additional context

https://scientific-python.org/specs/spec-0000/#2024---quarter-4, drop support for
> python 	3.10 	released Oct 2021

**Comment by pllim** [comment]
@astropy/astropy-project-release-team , what do you think?

**Comment by pllim** [comment]
Also see: https://github.com/astropy/astropy/labels/Python%203.11

**Comment by neutrinoceros** [comment]
I've opened a draft PR (#16903) to address this, although note that we already have `astropy.utils.exceptions._add_note_to_exception` to compensate for the lack of `Exception.add_note`
