### ISSUE TITLE
Issue when converting 64 bit to 16 bit using BZERO and BSCALE 

### ISSUE THREAD

**Issue by thisisrahulg** [astropy/astropy#16909]
### Description

I have an image that was initially 16-bit data. I have processed it, and it now has 64-bit signed data. I want to convert it back to 16-bit  unsigned to reduce the file size. I am trying to use BZERO and BSCALE headers to convert it back to 16-bit. When I save the BSCALE and BZERO values, they are not reflected in the header. It works for 16-bit signed integers but not for unsigned integers. 

### Expected behavior

```python 
from astropy.io import fits
import numpy as np

def convert_64bit_to_16bit(input_file, output_file):
    # Open the FITS file
    with fits.open(input_file) as hdul:
        # Access the data from the primary HDU
        data = hdul[0].data

        # Find min and max values for scaling
        data_min = np.min(data)

        # Define BZERO and BSCALE
        BZERO = data_min  
        BSCALE = 2
        
        # converting to 16 bit unsigned integer
        scaled_data = ((data - BZERO) / BSCALE).astype(np.uint16)
       
        hdu = fits.PrimaryHDU(data=scaled_data)

        hdr = hdu.header
        #saving the BZERO and BSCALE
        hdr['BZERO'] = BZERO 
        hdr['BSCALE'] = BSCALE # this is 2 as per above

        # Save the new FITS file
        hdu.writeto(output_file, overwrite=True)

convert_64bit_to_16bit('input.fits', 'output.fits')

```
The BSCALE is coming as 1 and BZERO is always 32768.

### How to Reproduce

Take any fits file of 64 bit  and try to convert to 16 bit by scaling using BZERO and BSCALE. Try  both signed and unsigned. Works for signed but not for unsigned.

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
# Paste the result here
```

**Comment by thisisrahulg** [comment]
Thanks for the comment @saimn. The problem I am facing is storing the data as 16-bit unsigned, and when reading the file, the real value should be shown (conversion should happen automatically). What do you think the best way is to tackle this issue?

**Comment by saimn** [comment]
If you really want uint16 then you should just store the uint16 array without dealing manually with bscale/bzero. How to convert from int64 to uint16 is up to you, one option would be to store some scaling factors without other keywords.
