### ISSUE TITLE
Automate updating IERS_B and LeapSecond files whenever a release is made

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#1697]
Just a reminder, so we do not need to do something like #1693 every time.

EDIT: we may also want to consider more generally whether we really want to have this 3 MB file as part of the package, or whether there should be some automatic download upon first use of `UT1` (or sidereal time or local coordinates). 

EDIT: this now also applies to the built-in `LeapSecond.dat` file.

**Comment by mhvk** [comment]
Removed the milestone, as I know I am not the right person to do this. However, this, and the automatic downloading/updating of IERS A are important; see #3274 and discussion therein.

**Comment by mhvk** [comment]
Also see #3275 for the download of IERS A; I guess this issue should strictly be for the automatic update of IERS B with astropy releases.

**Comment by mhvk** [comment]
I fear so.  Indeed, we should now also ensure we always ship with the latest leap-second table...

**Comment by mhvk** [comment]
Yes, good idea...

**Comment by pllim** [comment]
@mhvk , do you want to open a PR, as you would understand the best where we should add that action item in the release time line.

**Comment by pllim** [comment]
We now have https://github.com/astropy/astropy/blob/main/.github/workflows/update_iers.yml . Can we close this?

**Comment by mhvk** [comment]
Closing since we now have our `astropy-iers` package.
