### ISSUE TITLE
TST: oldestdeps and mpl334 jobs are failing in v6.1.x

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16991]
Example oldestdeps log: https://github.com/astropy/astropy/actions/runs/10741970245 (this one used to be green but now red on a rerun)

Example mpl334 log: https://app.circleci.com/pipelines/github/astropy/astropy/22604/workflows/0f63607a-769c-433f-ab6d-1e91ef379d7e/jobs/127110

In the oldestdeps job, it also asks for alldeps and pip freeze does show matplotlib installed. But then the pytest header says matplotlib is unavailable. And pytest failed to start with `ImportError: matplotlib/ft2font.cpython-310-x86_64-linux-gnu.so: undefined symbol: __gcov_merge_add`

Not sure what is going on. pytest 8.3.3 was released today but why would a bug fix release break things like this?

**Comment by pllim** [comment]
From QuLogic (matplotlib dev): I don't think you should be testing Matplotlib 3.3.4 on Python 3.10; it didn't have wheels for that version, so you are building from source

**Comment by neutrinoceros** [comment]
seems like we can close this one now ?

**Comment by pllim** [comment]
Yes, thanks!
