### ISSUE TITLE
TST: test_custom_frame is now flaky

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#17000]
Sometimes it fails like this but then okay again on rerun. 🤷‍♀️  If you look at the diff image when it fails, it is blank.

```
Image comparison test
---------------------
Error: Image files did not match.
  RMS Value: 0.08141969458716157
  Expected:  
    astropy.visualization.wcsaxes.tests.test_frame.TestFrame.test_custom_frame/baseline.png
  Actual:    
    astropy.visualization.wcsaxes.tests.test_frame.TestFrame.test_custom_frame/result.png
  Difference:
    astropy.visualization.wcsaxes.tests.test_frame.TestFrame.test_custom_frame/result-failed-diff.png
  Tolerance: 
    0
==== 1 failed, 54 passed, 10 skipped, 29048 deselected in 109.96s (0:01:49) ====
```

**Comment by neutrinoceros** [comment]
Here's a screenshot for posterity: the visual diff indeed seems blank but the RMS is still non-zero
![Screenshot 2024-09-11 at 21 20 51](https://github.com/user-attachments/assets/1ecb3f3d-6859-401a-808f-cf8c4ad481a2)

**Comment by neutrinoceros** [comment]
Actually it's even worse: sometimes the image comparison pass but the hash comparison doesn't
![Screenshot 2024-09-12 at 09 30 04](https://github.com/user-attachments/assets/a4dbcb2d-f522-41ad-8d47-41a50ecb6c9d)

**Comment by astrofrog** [comment]
The hash comparison is basically requiring exact agreement, and in some cases it's not **exact** at a ridiculously small level so then the baseline image succeeds (this is not uncommon).

I think increasing the tolerance would be acceptable, perhaps to something like 0.5?

**Comment by neutrinoceros** [comment]
we've seen runs failing with 0 RMS. How would an increased tolerance help there ?
