### ISSUE TITLE
Quantity conversion of temperatures via `unit1.to(unit2, value=q)` fails

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#17018]
### Description

With the temperature equivalency enabled, `unit.to()` should be able to handle Quantity conversions between temperature units.
It does not. 
The error is "UnitConversionError: Can only apply 'subtract' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)."

### Expected behavior

It should work, like it does for `Quantity.to()`

### How to Reproduce

```python
with u.add_enabled_equivalencies(u.temperature()):
    q = 2 * u.K
    newq = q.unit.to(u.deg_C, value=q)
```

### Versions

platform
--------
platform.platform() = 'macOS-14.6.1-arm64-arm-64bit'
platform.version() = 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020'
platform.python_version() = '3.12.4'

packages
--------
astropy              7.0.0.dev835+g2e1320edb6
numpy                2.1.0
scipy                1.14.0
matplotlib           3.9.2
pandas               2.2.2
pyerfa               2.0.1.4

**Comment by nstarman** [comment]
Ping @mhvk, this is what we were discussing in the Zoom.
I tried for JAX, but found it doesn't work even for Astropy!

**Comment by mhvk** [comment]
For `unit.to` you have to put in a plain array (i.e., something with the unit stripped, `q.value` in this case). We don't want to slow it down to check whether a `Quantity` was put in...
