### ISSUE TITLE
import kuiper raises a ValueError: numpy.dtype size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by maxsofronov** [astropy/astropy#17037]
### Description

Issue: When trying to import the kuiper function from astropy.stats, I encounter the following error:
`from astropy.stats import kuiper`
`ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject.
`

Context:
- I was using astropy alongside numpy 2.0.2.
- After installing astropy, attempting to import the kuiper function results in the above error, indicating a binary incompatibility between the installed version of numpy and the version used when compiling astropy's C extensions.
- I tried reinstalling astropy with the numpy downgrade to 1.26.4 and clearing the cache

Let me know if you'd like more details about the environment or error trace!

### Expected behavior

The kuiper function should import without errors.

### How to Reproduce

1. Get package from `pip install astropy`
2. Then run `from astropy.stats import kuiper'
3. An error occurs.

### Versions

macOS-14.6.1-arm64-arm-64bit
Python 3.9.6 (default, Feb  3 2024, 15:58:27) 
[Clang 15.0.0 (clang-1500.3.9.4)]
astropy 6.0.1
Numpy 2.0.2
pyerfa 2.0.1.4
Scipy 1.13.1
Matplotlib 3.9.2

**Comment by Ahmed-khalil3** [comment]
maybe this will help
https://bit.ly/4gwC82r
If you don't have the c compliator, install it.(gcc or clang)

**Comment by pllim** [comment]
Usually that is just a warning. Are you turning all warnings into exceptions? We ignore that warning in our test suite.

https://github.com/astropy/astropy/blob/d09ba92c28a0e22c27e7dfcdd2ed45d3bb7fa80d/pyproject.toml#L220-L221

I don't remember the reason now why that happens. I just vaguely remember that we decided it was okay to ignore.

**Comment by pllim** [comment]
Did you try upgrading to astropy 6.1.3 ?

**Comment by maxsofronov** [comment]
@pllim thank you so much for the tip, updating python to 3.12 and astropy to 6.1.3 solved the problem.

**Comment by neutrinoceros** [comment]
> I don't remember the reason now why that happens. 

To whoever this may be useful: this warning shows up when importing a package with extensions that were compiled against a version of numpy that is ABI incompatible with the one that's present at runtime. The way we compile astropy nowadays is supposed to prevent this from happening, *but* we may occasionally see it in CI if we run tests using some old binaries for our optional dependencies. Eventually it should become much rarer and we could probably afford not ignoring this warning now.
