### ISSUE TITLE
ModuleNotFoundError @Astropy

### ISSUE THREAD

**Issue by roykoush** [astropy/astropy#17036]
### Description

I just downloaded astropy using `pip install astropy` command in terminal
Now I opened Jupyter Notebook from a folder that is not in the home folder and when I try to import, an error message shown:
`ModuleNotFoundError                       Traceback (most recent call last)`
`ModuleNotFoundError: No module named 'astropy'`
However, when I am using terminal to run the command `import astropy`, it is working. [I even tried changing the terminal location to the folder I am working in, still working]
So why is it showing error in jupyter notebook?
The problem is faced only when importing astropy library btw.

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
# Paste the result here
```

**Comment by odoyhaha** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by evertrol** [comment]
Related: https://stackoverflow.com/questions/79002104/jupyter-notebook-showing-modulenotfounderror-astropy

**Comment by evertrol** [comment]
Related: https://stackoverflow.com/questions/79002104/jupyterlab-notebook-showing-modulenotfounderror-astropy#79002104

(I.e., same error & question.)

**Comment by pllim** [comment]
Hello. I think we need more info. How did you install the Jupyter stack in the first place? Is your terminal Python in the same env as your Jupyter stack? Is your pip in the same env as your Jupyter stack? When you start your notebook, what was the actual Python kernel that you chose?

astropy was obviously installed but perhaps there was confusion on where you think it went.

Astropy Project is not responsible for how Jupyter is grabbing packages but we can try to help as best we can here.

**Comment by eerovaher** [comment]
The issue reported here was caused by confusion regarding virtual environments, which has nothing to with `astropy`. Furthermore, the Stackoverflow question suggests that this particular user has managed to solve the problem to their satisfaction.
