### ISSUE TITLE
Does Astropy access JPL for ephemeris information

### ISSUE THREAD

**Issue by parthasarathipal** [astropy/astropy#17031]
### Description

Dear Astropy,
I am doing a HAWC data analysis on a computer from the University of Maryland. JPL complained that there are millions of times of hammering coming from UMD. I am using astropy coordinates to convert GPS time to MJD with barycenter correction.  See the following two lines. 
```python
hawc_site = coord.EarthLocation(lat=18.995, lon=-97.308, height=4096)
atime = Time(btime, format="gps", location=hawc_site, scale="tai", out_subfmt="long")
t["mjd"] = atime.mjd
```
Do these lines anyway try to access JPL for any information?
I am running the code millions of times as usual; these requests will be generated millions of times.
Is this the problem???   If you need any more information please ask me.

Partha

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
# Paste the result here
```

**Comment by eerovaher** [comment]
The issue title asks

> Does Astropy access JPL for ephemeris information

The short answer is that [by default it does not, but it can be configured to do so.](https://docs.astropy.org/en/stable/coordinates/solarsystem.html). Normally `astropy` would [cache](https://docs.astropy.org/en/stable/utils/data.html) the ephemerides file so it would only be downloaded once, but if something interferes with caching then `astropy` might indeed be sending many queries.

A simple way for you to proceed with debugging would be to use the [`astropy` configuration system](https://docs.astropy.org/en/stable/config/index.html) to [turn off Internet access](https://docs.astropy.org/en/stable/api/astropy.utils.data.Conf.html#astropy.utils.data.Conf.allow_internet).

**Comment by mhvk** [comment]
By default, it should not query the JPL site, since you are not using ephemerides, unless you (or an underlying library...) explicitly opt in to using ephemerides with `astropy.coordinates.solar_system_ephemerides.set(...)`. However, if your times are current and you are not a little careful, it might hit the leap-second and IERS servers a lot too.

... Oops, I see @eerovaher already answered, and gave the suggestion I was going to give too, of ensuring there is no internet access, so you get a failure if your code (or a library) tries to access the JPL servers.

**Comment by astrofrog** [comment]
Just curious, are there any settings that might be in the astropy config file on disk that might affect this?

**Comment by eerovaher** [comment]
I am not aware of any items in the `astropy` configuration system that would prevent caching the JPL ephemerides.
