### ISSUE TITLE
Edit on github links on the docs do not point to anything useful

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#17044]
### Description

If one looks at a particlar class, e.g., https://docs.astropy.org/en/latest/api/astropy.units.Quantity.html#astropy.units.Quantity
one has an "edit on github" on the right

![image](https://github.com/user-attachments/assets/6507cf7a-8ea1-44d9-941c-5330f951255a)

However, clicking that leads to file-not-found, as it links to https://github.com/astropy/astropy/edit/main/docs/api/astropy.units.Quantity.rst

### Expected behavior

The link to lead back to the relevant github file, at the right position.

### Versions

True for both stable and dev docs.

**Comment by pllim** [comment]
I think it is this issue:

* https://github.com/pydata/pydata-sphinx-theme/issues/1269

**Comment by mhvk** [comment]
I raised this as I had problems with my own (affiliated) package `baseband`, while moving it to `pyproject.toml` and thus having to update `docs/conf.py` too. But there I'm using the old astropy theme, so could fix it easily. That it doesn't work with the new theme at least makes clear why I couldn't see a reason for astropy!

**Comment by pllim** [comment]
I have it on my to-do to investigate a workaround but always something else more important. :(

**Comment by pllim** [comment]
Actually this has been made complicated by the "public API" stuff. `astropy.units.Quantity` is actually in `astropy.units.quantity.Quantity` but I cannot know that from just the input `api/astropy.units.Quantity.html` passed into the doc build stage to build edit URL. Maybe it is easier to disable that feature than to fix it.
