### ISSUE TITLE
Add support for `np.unique` on SkyCoords

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#17042]
### What is the problem this feature will solve?

I need to find duplicate entries in a SkyCoord object. These are not near matches (#14486). These are actual duplicates. These are repeated visits to reference fields for a survey telescope in an observing plan. I'd like to be able to use `np.unique` on SkyCoord objects. `np.unique` currently fails with with the exception `TypeError: '<' not supported between instances of 'SkyCoord' and 'SkyCoord'`.

### Describe the desired outcome

`np.unique` works on SkyCoord objects.

**Comment by pllim** [comment]
Do you have the exact traceback, for future reference? Thanks!

How do you expect this to work if comparing SkyCoords from different frames, etc?

**Comment by eerovaher** [comment]
[`np.unique()`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html) cannot be made to work with `SkyCoord` because the function returns the _sorted_ unique elements of an array, but there is no natural way to sort `SkyCoord` instances.

You should be able to adapt the following example in your code:
```python
>>> import numpy as np
>>> from astropy.coordinates import SkyCoord
>>> sc = SkyCoord([0, 1, 0], [2, 3, 2], unit="deg")
>>> _, indices = np.unique(sc.ra, return_index=True)
>>> sc[indices]
<SkyCoord (ICRS): (ra, dec) in deg
    [(0., 2.), (1., 3.)]>
```

**Comment by pllim** [comment]
I guess if you want exact, you can even do it without numpy.

```python
list(set(list_of_tuples_of_ra_and_dec))
```

**Comment by lpsinger** [comment]
Actually `np.unique(coords.to_table())` works just fine.

**Comment by eerovaher** [comment]
It seems to me that writing a function that would be able to check the uniqueness of the elements of an arbitrary `SkyCoord` would be very complicated, but checking the uniqueness for some given `SkyCoord` can quite simple with the tools already available. I don't think implementing a method for this in `SkyCoord` is worth the effort.
