### ISSUE TITLE
Inconsistent behavior in assigning constant value to a column in case of empty table

### ISSUE THREAD

**Issue by orionlee** [astropy/astropy#17078]
### Description

When assigning a constant value to a column, e.g. `table['col2'] = 1.0`, most of the time it works as expected, that the constant value is broadcasted to the column. But in the case that the table is empty and the column is a new one to be added, a `TypeError: Empty table cannot have column set to scalar value` is raised.

The behavior for statements such as `table['col2'] = 1.0`: 

|                 | Existing column | New Column |
| --------------- | --------------- | ---------- |
| Non empty table | ok              | ok         |
| empty table     | ok              | `TypeError`  |

**Workaround:** assigning with an explicit array, e.g., `table['col2'] = np.full(len(table), 1.0)`, would work for both empty and non-empty tables.

### Expected behavior

I'd expect `table['col2'] = 1.0` work even if the table is empty. 

This might not be considered a bug, as the behavior seems to be a deliberate choice in response to issue #3811 . I feel the inconsistency in the behavior is error prone, however. 

As a reference point, for `pandas` , the similar `data_frame['col2'] = 1.0` works in all cases.

### How to Reproduce

The snippets demonstrate the behavior described in the table above.

```python

from astropy.table import Table

#
# cases non-empty table: all works

# okay - replace a  column by broadcasting a constant
tab = Table(data={"col1": [1.0, 2.0], "col2": [9, 8]})
tab["col1"] = 1.3
print(tab)

# okay - creating a new column by broadcasting a constant
tab = Table(data={"col1": [1.0, 2.0], "col2": [9, 8]})
tab["col3"] = 3.3
print(tab)

#
# cases empty table: creating a new column fails

# okay - replace a column by broadcasting a constant
tab = Table(data={"col1": [], "col2": []})  # empty table
tab["col1"] = 1.3
print(tab)

# failed - create a new column by broadcasting a constant
tab = Table(data={"col1": [], "col2": []})  # empty table
tab["col3"] = 3.3  # TypeError
print(tab)

```

In the last case, creating a new column on an empty table, the `TypeError: Empty table cannot have column set to scalar value` is raised.

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
Windows-10-10.0.22631-SP0
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
astropy 6.1.3
Numpy 2.1.1
pyerfa 2.0.1.4
Scipy not installed
Matplotlib not installed
```

**Comment by orionlee** [comment]
An related inconsistency. In the edge case that a table only has 1 column, it fails in most cases, except the case of creating a new column.

A variation of the test script above, with only 1 column in the table.

```python
from astropy.table import Table

#
# cases non-empty table: only work in creating a new column

# failed - replace a  column by broadcasting a constant
tab = Table(data={"col1": [1.0, 2.0]})
tab["col1"] = 1.3  # TypeError: len() of unsized object
print(tab)  

# okay - creating a new column by broadcasting a constant
tab = Table(data={"col1": [1.0, 2.0]})
tab["col3"] = 3.3
print(tab)

#
# cases empty table: all fail

# failed - replace a column by broadcasting a constant
tab = Table(data={"col1": []})  # empty table
tab["col1"] = 1.3  # TypeError: len() of unsized object
print(tab)

# failed - create a new column by broadcasting a constant
tab = Table(data={"col1": []})  # empty table
tab["col3"] = 3.3  # TypeError: Empty table cannot have column set to scalar value
print(tab)
```

**Comment by pllim** [comment]
Looks like still a problem on latest `main` (v7.0.dev). Traceback of the original problem:

```
File astropy/table/table.py:2136, in Table.__setitem__(self, item, value)
   2132 def __setitem__(self, item, value):
   2133     # If the item is a string then it must be the name of a column.
   2134     # If that column doesn't already exist then create it now.
   2135     if isinstance(item, str) and item not in self.colnames:
-> 2136         self.add_column(value, name=item, copy=True)
   2138     else:
   2139         n_cols = len(self.columns)

File astropy/table/table.py:2437, in Table.add_column(self, col, index, name, rename_duplicate, copy, default_name)
   2434 # Assigning a scalar column to an empty table should result in an
   2435 # exception (see #3811).
   2436 if col.shape == () and len(self) == 0:
-> 2437     raise TypeError("Empty table cannot have column set to scalar value")
   2438 # Make col data shape correct for scalars.  The second test is to allow
   2439 # broadcasting an N-d element to a column, e.g. t['new'] = [[1, 2]].
   2440 elif (col.shape == () or col.shape[0] == 1) and len(self) > 0:

TypeError: Empty table cannot have column set to scalar value
```

**Comment by orionlee** [comment]
In my use case, the actual table is from catalog query result, I want to add a column that has constant values in some cases, e.g.,

```python
# tab: catalog query result
...
tab["display_size"] = 2.0  # add a new column
...
```

The statement `tab["display_size"] = 2.0` works for typical cases with non-empty tables. But when the catalog query result is empty, `TypeError: Empty table cannot have column set to scalar value` is raised.

For empty table case, I'd expect a new column be added with no data, the same behavior as replacing an existing column (and the counterpart in `pandas`).

---

Correction: For the extra edge case where the table only has 1 column, it does not work at the `print()` statement, at least as of astropy v6.1.3:
```python
tab = Table(data={"col1": [1.0, 2.0]})
tab["col1"] = 1.3  
print(tab)  # TypeError: len() of unsized object
```
<details>
<summary>stacktrace</summary>
<code>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 9
      7 tab = Table(data={"col1": [1.0, 2.0]})
      8 tab["col1"] = 1.3  
----> 9 print(tab)  # TypeError: len() of unsized object
     10 # tab["col1"]

File C:\pkg\_winNonPortables\miniforge3\envs\astropy_prod\lib\site-packages\astropy\table\table.py:1655, in Table.__str__(self)
   1654 def __str__(self):
-> 1655     return "\n".join(self.pformat())

File C:\pkg\_winNonPortables\miniforge3\envs\astropy_prod\lib\site-packages\astropy\table\table.py:1984, in Table.pformat(self, max_lines, max_width, show_name, show_unit, show_dtype, html, tableid, align, tableclass)
   1957 @format_doc(_pformat_docs, id="{id}")
   1958 def pformat(
   1959     self,
   (...)
   1968     tableclass=None,
   1969 ):
   1970     """Return a list of lines for the formatted string representation of
   1971     the table.
   1972 
   (...)
   1982 
   1983     """
-> 1984     lines, outs = self.formatter._pformat_table(
   1985         self,
   1986         max_lines,
   1987         max_width,
   1988         show_name=show_name,
   1989         show_unit=show_unit,
   1990         show_dtype=show_dtype,
   1991         html=html,
   1992         tableid=tableid,
   1993         tableclass=tableclass,
   1994         align=align,
   1995     )
   1997     if outs["show_length"]:
   1998         lines.append(f"Length = {len(self)} rows")

File C:\pkg\_winNonPortables\miniforge3\envs\astropy_prod\lib\site-packages\astropy\table\pprint.py:647, in TableFormatter._pformat_table(self, table, max_lines, max_width, show_name, show_unit, show_dtype, html, tableid, tableclass, align)
    644 if col.info.name not in pprint_include_names:
    645     continue
--> 647 lines, outs = self._pformat_col(
    648     col,
    649     max_lines,
    650     show_name=show_name,
    651     show_unit=show_unit,
    652     show_dtype=show_dtype,
    653     align=align_,
    654 )
    655 if outs["show_length"]:
    656     lines = lines[:-1]

File C:\pkg\_winNonPortables\miniforge3\envs\astropy_prod\lib\site-packages\astropy\table\pprint.py:295, in TableFormatter._pformat_col(self, col, max_lines, show_name, show_unit, show_dtype, show_length, html, align)
    283 col_strs_iter = self._pformat_col_iter(
    284     col,
    285     max_lines,
   (...)
    290     outs=outs,
    291 )
    293 # Replace tab and newline with text representations so they display nicely.
    294 # Newline in particular is a problem in a multicolumn table.
--> 295 col_strs = [
    296     val.replace("\t", "\\t").replace("\n", "\\n") for val in col_strs_iter
    297 ]
    298 if len(col_strs) > 0:
    299     col_width = max(len(x) for x in col_strs)

File C:\pkg\_winNonPortables\miniforge3\envs\astropy_prod\lib\site-packages\astropy\table\pprint.py:295, in <listcomp>(.0)
    283 col_strs_iter = self._pformat_col_iter(
    284     col,
    285     max_lines,
   (...)
    290     outs=outs,
    291 )
    293 # Replace tab and newline with text representations so they display nicely.
    294 # Newline in particular is a problem in a multicolumn table.
--> 295 col_strs = [
    296     val.replace("\t", "\\t").replace("\n", "\\n") for val in col_strs_iter
    297 ]
    298 if len(col_strs) > 0:
    299     col_width = max(len(x) for x in col_strs)

File C:\pkg\_winNonPortables\miniforge3\envs\astropy_prod\lib\site-packages\astropy\table\pprint.py:466, in TableFormatter._pformat_col_iter(self, col, max_lines, show_name, show_unit, outs, show_dtype, show_length)
    464 max_lines -= n_header
    465 n_print2 = max_lines // 2
--> 466 n_rows = len(col)
    468 # This block of code is responsible for producing the function that
    469 # will format values for this column.  The ``format_func`` function
    470 # takes two args (col_format, val) and returns the string-formatted
   (...)
    494 #    with the column id and possible_string_format_functions as
    495 #    enclosed variables.
    496 col_format = col.info.format or getattr(col.info, "default_format", None)

TypeError: len() of unsized object
</code>
</details>

**Comment by mhvk** [comment]
Ah, I see your point: the table actually has a length (zero), and one should just add a nothing to it. Hmm, that does make sense. Need to think a bit more!

**Comment by mhvk** [comment]
@taldcroft - I think this question ends up being more for you: what should the behaviour be when a scalar column is set in an empty table. Currently, it errors (see https://github.com/astropy/astropy/issues/17078#issuecomment-2377325081), but @orionlee argues that it is more logical to just "do it": insert a column with the new name that is empty. There definitely is a sense of consistency to that, and, FWIW, if one creates an empty array, one can assign to it in numpy:
```
a = np.empty((0,))
a[...] = 1
```
This also works for `Column`:
```
c = Column(name="a", length=0)
c[...] = 1
c
# <Column name='a' dtype='float64' length=0>
```
So, I suspect that all it would take to make things work is to remove the explicit test. My tendency would be to do that -- less code/checking is usually better.

**Comment by taldcroft** [comment]
@mhvk @orionlee - I agree with changing the behavior in the way you propose. The main issue I can see is getting a reasonable `dtype` for the new column. I haven't looked into the code, but basically we want to use the appropriate dtype from `np.array(scalar_value)` to be consistent with how things work for a non-empty / non-zero-length table.

**Comment by mhvk** [comment]
@taldcroft - I had a quick look at implementing this, and run into a slight hitch, with unknown types. Right now, there is
https://github.com/astropy/astropy/blob/04dfd245ac7815e20908ff7d079f5ad98dd0b2e4/astropy/table/mixins/tests/test_registry.py#L77-L88

Currently, the pre-registration assignment fails only because `SpamData()` is converted to an object dtype column with `shape=()` and the table has nothing in it. However, when I define the table to have data already, no `TypeError` is raised. Should an error be raised? Or is the expected result a new object dtype column with `SpamData()` in each? I ask since presumably one might want `t["a"] = None` to do just that...

**Comment by mhvk** [comment]
@taldcroft - I think the broadcasting actually takes care:
```
In [7]: sc = SkyCoord([0], [1], unit="deg")

In [8]: sc._apply(np.broadcast_to, (0,), subok=True)
Out[8]: 
<SkyCoord (ICRS): (ra, dec) in deg
    []>
```
And I similarly found that most tests that failed where ones where the solution was obvious. The problem case was the mixin one, where `t["a"] = SpamData()` no longer fails.

Anyway, why don't I push where I was and we can discuss there...

**Comment by taldcroft** [comment]
`sc._apply(np.broadcast_to, (0,), subok=True)` seems specific to our implementation of mixin columns. Ideally we should look for a solution that is likely to work with any class adhering to the [mixin protocol](https://docs.astropy.org/en/stable/table/mixin_columns.html#mixin-protocol).

I'm not sure if `np.newaxis` is a generalized thing for the array protocol. What about `some_array[None]`?  I just recently learned that for numpy indexing, `None` is a synonym for `np.newaxis` (but I prefer the latter).
