### ISSUE TITLE
Add in anything RTD is auto-injecting into the html context (By Oct 7)

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#17095]
This is a follow-up from a comment in #17007 - https://github.com/astropy/astropy/issues/17007#issuecomment-2373539274 . 

The short version is that by Oct 7, anything RTD auto-injects into the html_context at build-time for the docs is going away, and we have to manually add it back in, a la  Read https://about.readthedocs.com/blog/2024/07/addons-by-default/ .

**Comment by eteq** [comment]
To be clear, most, and maybe all of this, was already done in #16737 by @pllim , but given #17007 and #17071 which turned out to be due to this, we should make sure  there's nothing we're missing.

**Comment by pllim** [comment]
Thanks for this reminder issue. I also added a milestone to make sure things are working before the next major release.

**Comment by pllim** [comment]
Well, Oct 7 is here. If you all notice anything funky in Astropy project, please report back.

**Comment by pllim** [comment]
If I don't hear back, this issue will auto-close on 7 days unless you show your friend a VHS tape of this issue.
