### ISSUE TITLE
Wheels should not get build if unrelated labels are changed

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#17111]
### Description

As noticed in https://github.com/astropy/astropy/pull/17105#issuecomment-2387078145, when one changes any label (e.g., to make the changelog checker happy or get it to run again), all the wheels get rebuild too. This seems a waste of CI and of time, so ideally we fix it. Not a very high priority, obviously, but as all the other CI doesn't get triggered, hopefully it is not too much work. Note that the "Extra CI" runs do not suffer from this, so maybe the difference in setup with those can give a clue how to fix this.

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
# Paste the result here
```

**Comment by pllim** [comment]
Thanks. Maybe it is a matter of not listening to label event but only for the mandatory wheels job. I can look into it.

> Note that the "Extra CI" runs do not suffer from this

Are you sure? I think all the cron jobs rerun when labels are changed, which annoy me as well, but I can cancel those and they do not block merge.

**Comment by mhvk** [comment]
> Are you sure? I think all the cron jobs rerun when labels are changed, which annoy me as well, but I can cancel those and they do not block merge.

I thought that in the backport in #17015, I did not see them restart. But I'm not really sure any more...

Though I guess that may be different than having the "Extra CI" label on a regular CI job.

**Comment by pllim** [comment]
Backport + Extra CI been wonky lately but that combo also does not happen often enough for me to pin down a pattern. Maybe default `branches` for `pull_request` now does not include non-`main` branches? Not sure.

Anyways, please review https://github.com/astropy/astropy/pull/17115 . Thanks!
