### ISSUE TITLE
Differences between transform_to(AltAz) between Astropy versions 4.0 and 5.3.1

### ISSUE THREAD

**Issue by zigcloud** [astropy/astropy#17110]
### Answered

https://github.com/astropy/astropy/issues/17110#issuecomment-2388836447

### Description

I am trying to do the transfomation from ITRS to topocentric AltAz frame using SkyCoord.transform_to() functionality:
altazCoord = itrsCoord.transform_to(AltAz(obstime=time, location=obsGeoLocation)

The problem encountered is that under Astropy version 4.0 we are receiving different values than under Astropy version 5.3.1. Based on external validator we know that the values from version 4.0 are correct. I assume that some correction or some parts of the transformation was omitted in version 5.3.1 or replaced by other function. Can somebody suggest, what should be added to have equal values under astropy 5.3.1 in comparison to version 4.0?

Example outputs:

Current values - Astropy version 5.3.1
<SkyCoord (AltAz: obstime=60573.003523216925, location=(4053731.93746628, 1260550.54234471, 4744894.08614764) m, pressure=0.0 hPa, temperature=0.0 deg_C, relative_humidity=0.0, obswl=1.0 micron): (az, alt, distance) in (deg, deg, m)
    (169.68730146, 67.35702581, 23624164.67230157)>

### Expected behavior

Expected correct values - Astropy version 4.0
<SkyCoord (AltAz: obstime=60573.003523216925, location=(4053731.93746628, 1260550.54234471, 4744894.08614764) m, pressure=0.0 hPa, temperature=0.0 deg_C, relative_humidity=0.0, obswl=1.0 micron): (az, alt, distance) in (deg, deg, m)
    (169.68410928, 67.35684178, 23624155.6380583)>

### How to Reproduce

# run the bellow code snippet with astropy versions 4.0 and 5.3.1 or the latest. The results will differ, and the 4.0 version is only giving the real values.

from astropy.coordinates import EarthLocation, SkyCoord, AltAz
from astropy.time import Time
import astropy.units as u

time = Time(60573.003523216925, format='mjd', scale='utc')

itrsCoord = SkyCoord(x=23787247.15570922, y=9102499.0451817, z=15098296.92876073, unit='m',
                     representation_type='cartesian', frame='itrs', obstime=time)

obsGeoLocation = EarthLocation(lat=48.372528 * u.deg, lon=17.2736306 * u.deg, height=536.1 * u.m)

altazCoord = itrsCoord.transform_to(AltAz(obstime=time, location=obsGeoLocation))

print(altazCoord)

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
# Paste the result here
```
macOS-14.5-arm64-arm-64bit
Python 3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]
astropy 6.1.4
Numpy 2.1.1
pyerfa 2.0.1.4
Scipy 1.14.1
Matplotlib 3.9.2

**Comment by zigcloud** [comment]
forgot to mention... Code was tested also on the latest Astropy version 6.1.4 giving the exact same results as 5.3.1

**Comment by ayshih** [comment]
Not a bisection down to PR/commit, but the change occurred with 4.3:
* 4.2.1: `(169.68410928, 67.35684178, 23624155.6380583)`
* 4.3.0: `(169.68730146, 67.35702581, 23624164.67230157)`

There were a number of improvements to the accuracy of coordinate transformations with 4.3.0 (see https://docs.astropy.org/en/v6.1.4/changelog.html#id333).  While there could have been a bug introduced, the question for you is how you are confident that your "external validator" is correct.

**Comment by ayshih** [comment]
(@neutrinoceros I'm using conda to fire up astropy 4 instead of building it, hence why I'm limited to releases rather than commits)

**Comment by ayshih** [comment]
I'll note that the angular difference between the two vectors is only 4.5 arcsec, so my guess is that the change is due to #10994, which fixed the handling of stellar aberration for CIRS<->AltAz transformations, which are triggered internally by ITRS<->AltAz transformations.  If that's the case, there's likely no way to simply "toggle" back to the old calculation.

**Comment by zigcloud** [comment]
> Not a bisection down to PR/commit, but the change occurred with 4.3:
> 
> * 4.2.1: `(169.68410928, 67.35684178, 23624155.6380583)`
> * 4.3.0: `(169.68730146, 67.35702581, 23624164.67230157)`
> 
> There were a number of improvements to the accuracy of coordinate transformations with 4.3.0 (see https://docs.astropy.org/en/v6.1.4/changelog.html#id333). While there could have been a bug introduced, the question for you is how you are confident that your "external validator" is correct.

The code is part of the data quality checker for optical observations by comparison ground truth dataset of GNSS satellites positions. The version, which uses astropy==4.0 was validated using 4 months long observation campaign and compared by independent Orbit Determination methods. Understand the scepticism to the "external validator" but from our point of view there is no other chance, just to trust the campaign results. That is why we are searching at least for the way how to reproduce version 4.0 result using newer or latest version.

**Comment by ayshih** [comment]
Okay, fortunately astropy 5.2 introduced topocentric ITRS frames, which allows one to handle stellar aberration in the way you need.  You need to subtract the observer ITRS coordinates from the object ITRS coordinates, and then load the difference into a topocentric ITRS frame for the observer.  This procedure is described in the [docstring for the `ITRS` frame](https://docs.astropy.org/en/stable/api/astropy.coordinates.ITRS.html).  Here's the modified code:
```python
from astropy.coordinates import EarthLocation, SkyCoord, AltAz
from astropy.time import Time
import astropy.units as u

time = Time(60573.003523216925, format='mjd', scale='utc')

obsGeoLocation = EarthLocation(lat=48.372528 * u.deg, lon=17.2736306 * u.deg, height=536.1 * u.m)

itrsCoord = SkyCoord(x=23787247.15570922 * u.m - obsGeoLocation.x,
                     y=9102499.0451817 * u.m - obsGeoLocation.y,
                     z=15098296.92876073 * u.m - obsGeoLocation.z,
                     location=obsGeoLocation,
                     representation_type='cartesian', frame='itrs', obstime=time)

altazCoord = itrsCoord.transform_to(AltAz(obstime=time, location=obsGeoLocation))

print(altazCoord)
```
The result is `(169.68426047, 67.35685156, 23624155.6380583)`, which has the same distance as the astropy <=4.2 answer, but the angles are very slightly different.  Hopefully you can accept the remaining discrepancy (0.2 arcsec instead of 4.5 arcsec).

**Comment by pllim** [comment]
Thank you, all! Since this seems to be answered in https://github.com/astropy/astropy/issues/17110#issuecomment-2388836447 . I will apply a label to automatically close this in 7 days but we can always remove it or reopen if more discussions are needed.

**Comment by zigcloud** [comment]
Thank you guys for fast responses and alternative solution suggestion! Whole code now works as before producing sufficiently accurate data.
