### ISSUE TITLE
Properly support sub-mm through radio kernel normalization

### ISSUE THREAD

**Issue by aconley** [astropy/astropy#1713]
The new kernel classes only properly support optical/near-IR normalization conventions (that the sum/integral of all the pixels in the kernel is unity).  But there is another set of conventions for sub-mm through radio, which is that the peak of the kernel is unity.  

Right now this can be approximated by calling the `normalize` method on the kernel after construction with mode='peak', but this doesn't properly interact with the discretization parameter.  For example, if I use, say, 10x oversampling, in sub-mm/radio mode I want the peak value of the oversampled kernel to be unity, not the value after it is rebinned. This is about a 2-3% error for a typical FWHM/3 map sampling.

So, I would like to request
1) Some sort of support for peak normalization that understands discretization.  That may means it has to happen in `__init__`, rather than `normalize`, if the information about the discretization is gone after construction.
2) Even if it can be implemented in `normalize`, for convenience it would be lovely if there were a normalization option to `__init__`.

I'm happy to do the work if nobody has objections to the idea.

**Comment by keflavich** [comment]
I'm closing this issue until someone else requests it.  It's really easy to normalize a kernel if you want (e.g., `kern = kernel.array / kernel.array.max()`), so there is an easy workaround if this feature is needed.
