### ISSUE TITLE
DOC: Why use astropy Table/QTable over pandas DataFrame

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#17146]
From https://github.com/astropy/astropy/pull/15905#issuecomment-2401962608 

@bsipocz why Table is "better" than pandas (the question comes up regularly)

@taldcroft We should have a FAQ, but for the record (and for your tutorial), Table provides these capabilities that are not in pandas DataFrame:

* Robust support for table and column metadata. This is needed for representing data in file formats like FITS and VOTable.
* Support for N-dimensional column data, for example a table of thumbnail images in a source catalog.
* Support for columns of astropy Time, Quantity, and SkyCoord / Frame objects.
* General support for external "mixin" columns, for instance dask arrays.

**Comment by mhvk** [comment]
If this becomes a kind of comparison page, it would also be good to highlight how to import pandas dataframes into tables, and possibly have a list of things one does on dataframes and their equivalent operations on tables. (If that's relevant -- I don't use pandas so am of little use here!).

**Comment by pllim** [comment]
I do use pandas when I want some quick stats for reports but that need is not often.

**Comment by bsipocz** [comment]
Oh, I know the list above, but the list above gets weaker if working in a notebook we need to switch to a third party tool as conveniences from Table are gutted out (again, with good reason, from the developer pov, I understand why the deprecation happened, but I try to look at it from the users pov now)

**Comment by taldcroft** [comment]
That FAQ still isn't done so I'll try to take a crack at it.

I'm not sure what more to say about this except that tutorials and documentation need to emphasize that the Astropy ecosystem built up since 2011 depends on the unique features of `Table` and `QTable` that are not available in `DataFrame` (pandas or polars).

We can certainly add convenience wrappers in `Table` for things like SQL support.

**Comment by mhvk** [comment]
I think you are right that the main advantage of `QTable` is the flexibility in what it can store. Perhaps the FAQ could focus on how to interoperate? This of course immediately brings up an idea for a PR: could one make the serialization a public method? That way, the user could also serialize to/from pandas (if they keep track of the metadata, not sure if pandas allows storing *any* table metadata).

**Comment by bsipocz** [comment]
> maybe it won't be long before polars is the gold standard

this has definitely started :)

**Comment by neutrinoceros** [comment]
> And of course pandas is no longer the only DataFrame in town, and maybe it won't be long before polars is the gold standard

We might want to adopt [`narwhals`](https://pypi.org/project/narwhals/) as an abstraction layer to get portability across dataframe implementations.
