### ISSUE TITLE
Unknown type name `pthread_mutex_t` when building `astropy` from source

### ISSUE THREAD

**Issue by tieneupin** [astropy/astropy#17201]
### Description

Encountered the following error when trying to build `astropy v6.1.4` from source:
```stdout
      astropy/io/fits/hdu/compressed/src/compression.c:16:1: error: unknown type name 'pthread_mutex_t'
         16 | pthread_mutex_t Fitsio_Lock;
            | ^~~~~~~~~~~~~~~
      error: command 'C:\\msys64\\mingw64\\bin/gcc.EXE' failed with exit code 1
```

### Expected behavior

`astropy` should compile without issue.

### How to Reproduce

1. Started in latest version of MSYS2 (MINGW64) on Windows 10.
2. Installed Python 3.11 in addition to as many relevant compilers as possible:
  - pacman -S
    - base_devel
    - mingw-w64-x86_64-python-pip
    - mingw-w64-x86_64-cmake
    - mingw-w64-x86_64-cfitsio
    - mingw-w64-x86_64-cython
    - mingw-w64-x86_64-gcc-libgfortran
    - mingw-w64-x86_64-gcc-fortran
    - mingw-w64-x86_64-ninja
    - mingw-w64-x86_64-openblas
    - mingw-w64-x86_64-toolchain
3. Built `numpy v1.26.4`, `scipy v1.14.1`, and `pyerfa v2.0.1.4` from source in the MINGW64 environment using `pip install . ` in the cloned repositories.
4. Attempt to install `astropy v6.1.4` by also running `pip install . ` in the cloned repository.

### Versions

N/A, as this is a question related to the installation.

**Comment by pllim** [comment]
Hello. Is there a reason you are not using the provided wheel from PyPI or from conda-forge?

I think v6.1.4 requires numpy 2.0 to build. Can you please try that? Thanks.

**Comment by pllim** [comment]
Ah, thanks for the clarification!  Are you interested to open a pull request with the suggested patch?

**Comment by pllim** [comment]
We just revamped our contributing doc, so hopefully you will find it helpful: https://docs.astropy.org/en/latest/index_dev.html

Thanks and looking forward to it!

**Comment by saimn** [comment]
We no more use the original `fitsio2.h` from cfitsio so maybe this block can be removed, @astrofrog ?

https://github.com/astropy/astropy/blob/e2d4fc65219c9e0712fadea37b77d41180681598/astropy/io/fits/hdu/compressed/src/compression.c#L13-L18

Also should not be executed unless you define `_REENTRANT` (which is a cfitsio thing, which I think we don't use/need).

**Comment by saimn** [comment]
#14252 removed most of our bundled cfitsio, keeping only the small parts we still need, so I think we no more need this. cc @Cadair as well :)

**Comment by astrofrog** [comment]
@saimn - yes I'm pretty sure that block can be removed

**Comment by saimn** [comment]
@tieneupin - which compiling instructions are you referring to ?
