### ISSUE TITLE
TST: testing exotic archs is currently broken

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#17214]
As noted in https://github.com/astropy/astropy/pull/17209#issuecomment-2424985047, weekly cron jobs (specifically `s390x`, `ppc64le` and `armv7`) are failing early, at the "build container" stage.

[example logs](https://github.com/astropy/astropy/actions/runs/11434227222)

This is very likely an upstream issue, and looks a lot like https://github.com/uraimo/run-on-arch-action/issues/155.
Since the discussion there contains pointers for workaround, and given we're 5 days away from a feature freeze, I'll make an attempt at applying the workaround now rather than waiting for the upstream fix.

**Comment by uraimo** [comment]
Hi, please trigger the workflows again (after updating the action release you are pointing to, If it's the pinned one I'm seeing in `ci_cron_weekly.yml`), release 2.8.1 has just been released and that should fix the upstream issue.

**Comment by neutrinoceros** [comment]
thanks a lot @uraimo, indeed this seems to do the trick !
