### ISSUE TITLE
`world_to_array_index` misbehaves if out of bounds because of casting `NaN` to int

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#17227]
### Description

#16328 exposed an issue with `world_to_array_index`:

```python
from astropy.wcs import WCS

wcs = WCS(naxis=2)
wcs.wcs.crpix = (1, 1)
wcs.wcs.set()

wcs.pixel_bounds = [(-0.5, 3.5), None]

print(wcs.world_to_pixel(*wcs.pixel_to_world(5, 5)))
```
```
(array(nan), array(5.))
```
```python
print(wcs.world_to_array_index(*wcs.pixel_to_world(5, 5)))
```
```
[...]/astropy/wcs/wcsapi/high_level_api.py:49: RuntimeWarning: invalid value encountered in cast
  indx = np.asarray(np.floor(np.asarray(value) + 0.5), dtype=int)
(5, -9223372036854775808)
```

### Versions

astropy main

**Comment by Cadair** [comment]
@astrofrog ping

**Comment by pllim** [comment]
Why is this issue milestone? Is it release blocker? If so, who is going to patch it?

**Comment by Cadair** [comment]
yes, I milestoned it because #16328 basically introduced this bug, or certainly aggravated it enough we should fix it.

I am working on my long list of astropy stuff before feature freeze, if I get to this before anyone else does then I will patch it, but hopefully someone else will as I still have a lot on the list.

**Comment by neutrinoceros** [comment]
Happy to give this a try tomorrow ! My own list has just one item this week: make everyone else's list lighter if I can :)
