### ISSUE TITLE
Cannot build Angle from pyarrow array

### ISSUE THREAD

**Issue by hombit** [astropy/astropy#17255]
### Description

`Angle` constructor fails when used with a float `pyarrow` array.

### Expected behavior

Input pyarrow array is wrapped into a numpy array and everything works correctly, just like with `Quantity`

### How to Reproduce

```python
import pyarrow as pa
from astropy.coordinates import Angle

Angle(pa.array([1.1, 2.2]), 'deg')
```

<details><summary>Error</summary>

```
TypeError                                 Traceback (most recent call last)
Cell In[1], line 4
      1 import pyarrow as pa
      2 from astropy.coordinates import Angle
----> 4 Angle(pa.array([1.1, 2.2]), 'deg')

File ~/.virtualenvs/v/lib/python3.12/site-packages/astropy/coordinates/angles/core.py:186, in Angle.__new__(cls, angle, unit, dtype, copy, **kwargs)
    181             angle = u.Quantity(angle, angle_unit, copy=COPY_IF_NEEDED)
    183     elif isiterable(angle) and not (
    184         isinstance(angle, np.ndarray) and angle.dtype.kind not in "SUVO"
    185     ):
--> 186         angle = [Angle(x, unit, copy=COPY_IF_NEEDED) for x in angle]
    188 return super().__new__(cls, angle, unit, dtype=dtype, copy=copy, **kwargs)

File ~/.virtualenvs/v/lib/python3.12/site-packages/astropy/coordinates/angles/core.py:188, in Angle.__new__(cls, angle, unit, dtype, copy, **kwargs)
    183     elif isiterable(angle) and not (
    184         isinstance(angle, np.ndarray) and angle.dtype.kind not in "SUVO"
    185     ):
    186         angle = [Angle(x, unit, copy=COPY_IF_NEEDED) for x in angle]
--> 188 return super().__new__(cls, angle, unit, dtype=dtype, copy=copy, **kwargs)

File ~/.virtualenvs/v/lib/python3.12/site-packages/astropy/units/quantity.py:557, in Quantity.__new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    553 # check that array contains numbers or long int objects
    554 if value.dtype.kind in "OSU" and not (
    555     value.dtype.kind == "O" and isinstance(value.item(0), numbers.Number)
    556 ):
--> 557     raise TypeError("The value must be a valid Python or Numpy numeric type.")
    559 # by default, cast any integer, boolean, etc., to float
    560 if float_default and value.dtype.kind in "iuO":

TypeError: The value must be a valid Python or Numpy numeric type.
```

</details>

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
macOS-15.0.1-arm64-arm-64bit
Python 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)]
astropy 6.1.4
Numpy 2.0.2
pyerfa 2.0.1.4
Scipy 1.13.0
Matplotlib 3.9.0
```

**Comment by neutrinoceros** [comment]
Thanks for reporting. I think it's more of a feature request than a bug since we never claimed support for this use case. It might be part of a broader discussion with supporting the Array API, though I don't know if pyarrow is even supporting this yet.

**Comment by hombit** [comment]
Thank you, @neutrinoceros! I agree with the labeling - sorry for opening a wrong type of issue.

Basically I'd expect `astropy` to call `np.asarray` (or kinda) with my inputs, which `pyarrow` supports.

**Comment by neutrinoceros** [comment]
Calling `np.asarray` specifically would imply conversion to a `np.ndarray` on the fly, which may (or may not, depending on pyarrow's implementation details) require a copy. Just to be clear, would you expect this, or would you expect `Angle` to behave as a container for an arbitrary array type *without* performing a conversion ? I think the latter is what *I* would expect, but it's orders of magnitude more work to achieve.

**Comment by hombit** [comment]
I expect a shallow copy of a data as a numpy array, I do not expect pyarrow to be used as a back-end to `Quantity`. 

`np.asarray(a: pa.Array)` doesn't copy if no nulls present and a compatible dtype is used:

```python
import numpy as np
import pyarrow as pa

pa_array1 = pa.array([1.1, 2.2])

np_array1 = np.asarray(pa_array1)
np_array2 = np.array(pa_array1, copy=False)

assert np_array1.__array_interface__['data'][0] == np_array2.__array_interface__['data'][0], 'numpy address mismatch'

pa_array2 = pa.array(np_array1)
assert pa_array1.buffers()[1].address == pa_array2.buffers()[1].address, 'pyarrow address mismatch'
```

**Comment by neutrinoceros** [comment]
Oh, actually I didn't consider that `Angle` is indeed a subclass of `Quantity`... my "container" alternative scenario is actually just [Quantity 2.0](https://github.com/astropy/astropy-APEs/pull/91), which is indeed a very ambitious project, but one we are actively investing in !

> I do not expect pyarrow to be used as a back-end to Quantity.

but you wouldn't mind if it did, would you ? 😅

**Comment by hombit** [comment]
> Oh, actually I didn't consider that `Angle` is indeed a subclass of `Quantity`... my "container" alternative scenario is actually just [Quantity 2.0](https://github.com/astropy/astropy-APEs/pull/91), which is indeed a very ambitious project, but one we are actively investing in !
> 
> > I do not expect pyarrow to be used as a back-end to Quantity.
> 
> but you wouldn't mind if it did, would you ? 😅

Of course I'm not =)

Here, I’m just guessing that something went wrong between my call to `Angle(pa_array)` and its call to `Quantity.__new__(...)`, because I can run `Quantity(pa.array([1.1, 2.2]), unit='deg')` without any issues.

**Comment by neutrinoceros** [comment]
Actually after looking closely at how `Angle.__new__` works I now believe this is correctly described as a bug. I also have a fix that I'll open a PR for shortly.
