### ISSUE TITLE
If TLMIN4 is a string in a FITS file, should it be converted to the correct datatype in memory?

### ISSUE THREAD

**Issue by DougBurke** [astropy/astropy#17254]
### What is the problem this feature will solve?

Are the TLMIN/MAX values allowed to be strings for a column? I originally wrote this as a bug but it strikes me that this may be the intended behaviour, so I've changed this to a feature request.

If you take unpack [https://github.com/user-attachments/files/17517891/nustarspec.tar.gz] then you get

```
>>> from importlib.metadata import version
>>> version('astropy')
'6.1.1'
>>> version("numpy")
'1.26.4'
>>> from astropy.io import fits
>>> hdus = fits.open("bgd1B_sr.rmf")
>>> hdus[2].header["EXTNAME"]
'MATRIX'
>>> hdus[2].header["TTYPE4"]
'F_CHAN'
>>> hdus[2].header["TUNIT4"]
''
>>> hdus[2].header["TFORM4"]
'PI(116)'
>>> hdus[2].header["TLMIN4"]
'0'
>>> hdus[2].header["TLMAX4"]
'4095'
```

Note that the TLMIN/MAX values are strings rather than integers, which lead to a downstream problem - https://github.com/sherpa/sherpa/issues/2185 - since I had assumed these values would match the TFORM (so integer).

**AHA** - it's stored as a string in the actual file - e.g.

```
 TLMIN4  = '0       '           / Minimum value legally allowed in column 4     
 TLMAX4  = '4095    '           / Maximum value legally allowed in column 4     
```

I did not create this file, so I can not answer why it was written out like this (there are some other issues I have with the FITS representation, but that's not relevant here).

So, I guess the question is whether users would expect the header values - at least for those with some meaning to the FITS standart, like `TLMIN/MAX` - to get converted to sensible types, or left as is?

**Comment by saimn** [comment]
The Standard says "shall contain a number" so yeah I guess a string is not compliant. And the other file in your tarball correctly stores those values as integer.

> So, I guess the question is whether users would expect the header values - at least for those with some meaning to the FITS standart, like TLMIN/MAX - to get converted to sensible types, or left as is?

`io.fits` does a few checks and sometimes fixes for the keywords that are important to read data, but we cannot fix every weird values that are written in files. TLMIN/TLMAX is defined in the Standard but has no special meaning for reading files so it doesn't even appear in the code. So for this one it's up to the user to fix it and complain to people producing those files ;).

**Comment by DougBurke** [comment]
If I started complaining about bad FITS files I'm not sure I'd ever stop ....

Ta for the confirmation of the current behaviour.
