### ISSUE TITLE
pyplot.plot_date is deprecated

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#17317]
Discovered while working on #17316:

`matplotlib.pyplot.plot_date` and `matplotlib.axes.Axes.plot_date` are deprecated, as per [its documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot_date.html#matplotlib.pyplot.plot_date), since matplotlib 3.9, and set to be removed in 3.11 (3.10 is currently in rc, so no need to panic yet).
We're using them only in a couple doctest, but:
1) the replacement (`plot`) doesn't produce identical results out of the box.
For instance (adapted from one of our doctests):

```python
import numpy as np
from matplotlib import pyplot as plt

from astropy import units as u
from astropy.time import Time
from astropy.coordinates import EarthLocation, AltAz, GCRS

time = Time('J2010') + np.linspace(-1,1,1000)*u.min
location = EarthLocation(lon=0*u.deg, lat=45*u.deg)
aa = AltAz(alt=[45]*1000*u.deg, az=90*u.deg, distance=100*u.au,
            radial_velocity=[10]*1000*u.km/u.s,
            location=location, obstime=time)
gcrs = aa.transform_to(GCRS(obstime=time))

fig, ax = plt.subplots()
ax.plot_date(time.plot_date, gcrs.radial_velocity.to(u.km/u.s))
ax.set_ylabel('RV [km/s]')

sfile = "/tmp/test_plot_date.png"
fig.savefig(sfile)
print(f"saved to {sfile}")


fig, ax = plt.subplots()
ax.plot(time.plot_date, gcrs.radial_velocity.to(u.km/u.s))
ax.set_ylabel('RV [km/s]')
sfile = "/tmp/test_plot.png"
fig.savefig(sfile)
print(f"saved to {sfile}")
```
produces:
![test_plot_date](https://github.com/user-attachments/assets/8e64d3d9-2ac1-421a-a09f-eb704c30f2a7)
![test_plot](https://github.com/user-attachments/assets/c7c21727-c11d-4972-81c7-920fcc9d86fe)

at this stage I don't know if this is expected, a bug on our side, or a bug in matplotlib. Further inquiry is needed.

2) `TimePlotDate` is documented as `Matplotlib `~matplotlib.pyplot.plot_date` input` so it'll need to be changed

**Comment by pllim** [comment]
Quick git blame pointed to https://github.com/astropy/astropy/pull/3872 by @mhvk from 9 years ago.

**Comment by mhvk** [comment]
Following the link to the deprecation, the trick seems to be to insert before the `ax.plot` call,
```
ax.xaxis.axis_date()
```

**Comment by trhunter** [comment]
I encountered this same issue when switching to plot().  I found that if I specify a value for the marker parameter, rather than relying on the default value, which is what my code was doing, then the issue is resolved.
