### ISSUE TITLE
Wheel upload is broken

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#17333]
### Description

In addition to #17332, README cannot be rendered as `long_description` because "raw" directive is not allowed. Ref #16822
https://github.com/astropy/astropy/actions/runs/11687472774/job/32546805537

```
ERROR    `long_description` has syntax errors in markup and would not be        
         rendered on PyPI.                                                      
         line 35: Warning: "raw" directive disabled.                            
```

**Comment by pllim** [comment]
FWIW my vote (again) is to remove the image from README.

**Comment by jeffjennings** [comment]
There was a lot of discussion and an eventual CoCo decision to keep the image in the README in #16822. I don't think it should be permanently removed, in contradiction to that decision. I think just rendering the light version is the easiest resolution for the PyPI issue. I'm happy to find a permanent solution afterward.

**Comment by jeffjennings** [comment]
#17338 removes the `raw` HTML call and always displays the light background image - should clear the way for the wheel upload. Sorry for the trouble.

**Comment by pllim** [comment]
@saimn , hopefully works now. Please try again. Thanks, all!

**Comment by saimn** [comment]
Thanks
