### ISSUE TITLE
Grouped table aggregation by sum returns incorrect values for zero-length tables

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#17379]
### Description

Table aggregation by sum does not correctly handle zero-length arrays. Instead, it prints a warning and drops the numerical columns.

Zero-length arrays are not a problem for Numpy...

```pycon
>>> np.sum([])
np.float64(0.0)
>>> np.add.reduce([])
np.float64(0.0)
```

### Expected behavior

The code sample below should produce the following output (and no warnings):

```
<Table length=0>
action duration
 str1  float64 
------ --------
```

### How to Reproduce

```pycon
>>> from astropy.table import Table
>>> import numpy as np
>>> table = Table({
...     "action": np.asarray([], dtype=str),
...     "duration": np.asarray([], dtype=float)
... })
>>> table.group_by("action").groups.aggregate(np.sum)
WARNING: Cannot aggregate column 'duration' with type 'float64': index 0 out-of-bounds in add.reduceat [0, 0) [astropy.table.groups]
<Table length=0>
action
 str1 
------
```

### Versions

```
macOS-14.7.1-arm64-arm-64bit
Python 3.11.10 (main, Sep  7 2024, 05:47:53) [Clang 15.0.0 (clang-1500.1.0.2.5)]
astropy 6.1.5
Numpy 2.1.3
pyerfa 2.0.1.4
Scipy 1.14.1
Matplotlib 3.9.2
```

**Comment by pllim** [comment]
If warning is turned into error, it is from here:

```
File astropy/table/groups.py:396, in TableGroups.aggregate(self, func)
    394         new_col = col.info.groups.aggregate(func)
    395     except TypeError as err:
--> 396         warnings.warn(str(err), AstropyUserWarning)
    397         continue
    399 out_cols.append(new_col)
```

https://github.com/astropy/astropy/blob/a3f20ce33891396a8b754b6a3850272c501a3022/astropy/table/groups.py#L394

**Comment by pllim** [comment]
It really is happening here:

https://github.com/astropy/astropy/blob/a3f20ce33891396a8b754b6a3850272c501a3022/astropy/table/groups.py#L288

```python
func = np.add
par_col = table["duration"]
i0s = np.array([0])
func.reduceat(par_col, i0s)  # Error
```

**Comment by pllim** [comment]
Would something like https://github.com/astropy/astropy/pull/17384 work for you?

**Comment by lpsinger** [comment]
> Would something like #17384 work for you?

No, not if it does not preserve the column name.

**Comment by pllim** [comment]
> does not preserve the column name

I fixed it.
