### ISSUE TITLE
Is `data` attribute type hint for HDUList possible?

### ISSUE THREAD

**Issue by HaoxuanGuo** [astropy/astropy#17406]
### What is the problem this feature will solve?

Line 4 for the following code will not pass type check.

``` python
from astropy.io import fits

hdu = fits.open("test.fits")
column = hdu["SOMETABLE"].data["SOMECOLUMN"] # This line can not pass type check.
```

This code will got a [`reportAttributeAccessIssue`](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportAttributeAccessIssue), because can not access the attribute `data` for type `HDUList`.

### Describe the desired outcome

But, this code will well. type of column is `astropy.io.fits.fitsrec.FITS_rec`, although Pylance can not recognize it.

Is there any method to tell or cheat Pylance to get the correct type of `data` attribute instead of an error?

**Comment by saimn** [comment]
`io.fits` is not typed and there is no plan to add types in the near future. Your type checker should just ignore code that is not typed ? (in your example `hdu` is not typed, nor is `hdu["SOMETABLE"]` etc.).

**Comment by saimn** [comment]
`hdu` is a `HDUList` object  but `hdu["SOMETABLE"]` is a HDU (a subclass of `_BaseHDU`) object. So not sure how Pylance guesses those types but as I said `io.fits` has no type information so you should configure it so it ignores untyped code.
