### ISSUE TITLE
Old FITS_record fails to deepcopy properly

### ISSUE THREAD

**Issue by rmjarvis** [astropy/astropy#17416]
### Description

The unit tests for Piff uncovered an astropy regression related to deepcopying FITS_records.  We have a serialized object that includes a FITS_record.  Then we test that various things work correctly, including deepcopy.  This now fails with astropy version 6.1.5 or 6.1.6.  It works successfully on previous astropy versions.

### Expected behavior

The FITS_record object should roundtrip through `copy.deepcopy` correctly.

### How to Reproduce

1. Get the file "rec.pkl" from https://drive.google.com/file/d/1AL0lqHxV1j_sqXmXgNdD0LeOQSi78fOW/
2. Then run
```
import dill
import copy

with open('rec.pkl', 'rb') as f:
    rec = dill.load(f)

print(type(rec))
print(rec)
copy.deepcopy(rec)
```
3. With astropy 6.1.4, this completes successfully, outputing:
```
<class 'astropy.io.fits.fitsrec.FITS_record'>
(0.005956715713779821, 0.042563978321430454, -3.5926498764935705e-06, 3.2962080888252375e-06, 6.671209769961415e-08, -6.094365871944128e-07, 0.00011001616979678487, 1.0895115340250122e-07, 1.098670007544424e-07, 56543.7, 'S8')
```
With astropy 6.1.5 or 6.1.6, this errors:
```
<class 'astropy.io.fits.fitsrec.FITS_record'>
(0.005956715713779821, 0.042563978321430454, -3.5926498764935705e-06, 3.2962080888252375e-06, 6.671209769961415e-08, -6.094365871944128e-07, 0.00011001616979678487, 1.0895115340250122e-07, 1.098670007544424e-07, 56543.7, 'S8')
Traceback (most recent call last):
  File "/Users/Mike/miniforge3/envs/py3.10/lib/python3.10/site-packages/numpy/core/records.py", line 453, in __getattribute__
    res = fielddict[attr][:2]
KeyError: '_tbsize'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Mike/rmjarvis/Piff/tests/rec.py", line 9, in <module>
    copy.deepcopy(rec)
  File "/Users/Mike/miniforge3/envs/py3.10/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/Mike/miniforge3/envs/py3.10/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/Mike/miniforge3/envs/py3.10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Users/Mike/miniforge3/envs/py3.10/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/Mike/miniforge3/envs/py3.10/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/Users/Mike/miniforge3/envs/py3.10/lib/python3.10/site-packages/astropy/io/fits/fitsrec.py", line 242, in __array_finalize__
    self._tbsize = obj._tbsize
  File "/Users/Mike/miniforge3/envs/py3.10/lib/python3.10/site-packages/astropy/io/fits/fitsrec.py", line 505, in __getattribute__
    return super().__getattribute__(attr)
  File "/Users/Mike/miniforge3/envs/py3.10/lib/python3.10/site-packages/numpy/core/records.py", line 455, in __getattribute__
    raise AttributeError("recarray has no attribute %s" % attr) from e
AttributeError: recarray has no attribute _tbsize. Did you mean: 'itemsize'?
```

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
macOS-14.6.1-arm64-arm-64bit
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:35:25) [Clang 16.0.6 ]
astropy 6.1.6
Numpy 1.26.4
pyerfa 2.0.1.1
Scipy 1.14.0
Matplotlib 3.9.1
```

**Comment by pllim** [comment]
Distributing pickle files are insecure and we do not encourage our developers to download untrusted pickle files. Is there a way to reproduce this bug without pickling? Why is the data not saved as a FITS file?

**Comment by rmjarvis** [comment]
It's a small piece of a much larger structure, which includes a lot of non-astropy.fits items.  I pulled out this one piece as being the relevant bit that doesn't copy properly.  

If you have a different preferred way for me to serialize this, please let me know.  I don't see any serialization function for FITS_record [here](https://docs.astropy.org/en/stable/io/fits/api/tables.html#fits-record), so I'll need a little hand holding about how to get this into a fits file.

If you prefer to work on the underlying Piff unit test (which I doubt, but just in case...), it is [this test](https://github.com/rmjarvis/Piff/blob/releases/1.4/tests/test_wcs.py#L642), which uses [this FITS file](https://github.com/rmjarvis/Piff/blob/releases/1.4/tests/input/D00232418_i_c19_r5006p01_piff-model.fits).

**Comment by pllim** [comment]
On the other hand, it would be unreasonable for us to revert a legit bug fix. Is it an acceptable compromise to pin your pipeline to an older astropy version that works for you?

**Comment by pllim** [comment]
FITS is a file format in itself. I don't think we should support arbitrary pickling usage.

**Comment by rmjarvis** [comment]
I suspect it would be possible to write that in a backwards compatible way.  But I hear you that this is not a priority for you.  I'll try to come up with a workaround.

**Comment by saimn** [comment]
Well pickle is not a long term storage format. There is no guarantee that an object pickled with a given version of a code can be unpickled with a future version.
