### ISSUE TITLE
X11 Connection broke on python script using astropy

### ISSUE THREAD

**Issue by m-schochet** [astropy/astropy#17516]
### Description

Hi! So currently a group I am involved in are making a python script for assisting with planning observations ([RETRHO_priority](https://github.com/paeinovis/RETRHO_priority)). The program has been working absolutely fine on both Windows and MacOS systems, however we've now attempted to use this program on a Ubuntu machine which is causing us errors. We've gone and reported a minor bug that this program brought up with Astroplan issue ([#588](https://github.com/astropy/astroplan/issues/588)) and (#2979), however this is an entirely separate bug we've identified. 

When importing astropy for these functions, theres primarily an error on a call of 

`import astropy.units.format.cds_lextab`

For clarity, the machine is running Linux Mint 21.1, and the versions of the packages used are:

`python==3.13.0`
`astropy==6.1.3`
`astroquery==0.4.8.dev9474`
`astroplan==0.10.1`
`numpy==2.1.3`
`matplotlib==3.9.2`
`pandas==2.2.3`
`pyqt==5.15.0`
`pyqt5-sip==12.13.0`
`pyerfa==2.0.1.4`
`pyvo==1.6`

I have also tried this suggestion on [stackoverflow](https://stackoverflow.com/questions/71010343/cannot-load-swrast-and-iris-drivers-in-fedora-35/72200748#72200748) by placing the line 

`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6`

Into the .bashrc file for this device

The full error verbose end to the message is below
```
import 'prioritylib.printers' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2ee8050>
# /home/rho/Desktop/RETRHO_priority/prioritylib/__pycache__/sorters.cpython-313.pyc matches /home/rho/Desktop/RETRHO_priority/prioritylib/sorters.py
# code object from '/home/rho/Desktop/RETRHO_priority/prioritylib/__pycache__/sorters.cpython-313.pyc'
import 'prioritylib.sorters' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2ee80b0>
import 'prioritylib.initwin' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2ee8110>
import 'prioritylib.setters' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2e7bd70>
import 'prioritylib.helpers' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2e7b5f0>
import 'prioritylib.plots' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2e78e30>
import 'prioritylib' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b348e690>
# /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/__pycache__/netrc.cpython-313.pyc matches /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/netrc.py
# code object from '/home/rho/anaconda3/envs/retrhoplan/lib/python3.13/__pycache__/netrc.cpython-313.pyc'
import 'netrc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2e7a390>
# /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/encodings/__pycache__/ascii.cpython-313.pyc matches /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/encodings/ascii.py
# code object from '/home/rho/anaconda3/envs/retrhoplan/lib/python3.13/encodings/__pycache__/ascii.cpython-313.pyc'
import 'encodings.ascii' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2eea5d0>
# /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/encodings/__pycache__/utf_16_be.cpython-313.pyc matches /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/encodings/utf_16_be.py
# code object from '/home/rho/anaconda3/envs/retrhoplan/lib/python3.13/encodings/__pycache__/utf_16_be.cpython-313.pyc'
import 'encodings.utf_16_be' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2eea990>
# /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/coordinates/angles/__pycache__/angle_lextab.cpython-313.pyc matches /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/coordinates/angles/angle_lextab.py
# code object from '/home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/coordinates/angles/__pycache__/angle_lextab.cpython-313.pyc'
import 'astropy.coordinates.angles.angle_lextab' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2d27d10>
# /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/coordinates/angles/__pycache__/angle_parsetab.cpython-313.pyc matches /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/coordinates/angles/angle_parsetab.py
# code object from '/home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/coordinates/angles/__pycache__/angle_parsetab.cpython-313.pyc'
import 'astropy.coordinates.angles.angle_parsetab' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2d26e70>
# /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/units/__pycache__/cds.cpython-313.pyc matches /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/units/cds.py
# code object from '/home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/units/__pycache__/cds.cpython-313.pyc'
import 'astropy.units.cds' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73b2d274d0>
# /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/units/format/__pycache__/cds_parsetab.cpython-313.pyc matches /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/units/format/cds_parsetab.py
# code object from '/home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/units/format/__pycache__/cds_parsetab.cpython-313.pyc'
import 'astropy.units.format.cds_parsetab' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73ab495bb0>
# /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/units/format/__pycache__/cds_lextab.cpython-313.pyc matches /home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/units/format/cds_lextab.py
# code object from '/home/rho/anaconda3/envs/retrhoplan/lib/python3.13/site-packages/astropy/units/format/__pycache__/cds_lextab.cpython-313.pyc'
import 'astropy.units.format.cds_lextab' # <_frozen_importlib_external.SourceFileLoader object at 0x7f73ab495af0>
The X11 connection broke: Maximum allowed requested length exceeded (code 4)
X connection to :0 broken (explicit kill or server shutdown).
```

### Expected behavior

Ideally, the script would open a python application from the `planning.py` file in the github linked above. This never happens, the X11 error shows up first.

### How to Reproduce

1. **Using a Linux machine**, create a conda environment with the required packages from `requirements.txt` in ([RETRHO_priority](https://github.com/paeinovis/RETRHO_priority))
2. Delete all grid keywords inside the `astroplan/plots/finder.py` file
3. Attempt to open `planning.py` by running
`python -v planning.py`
4. Observe X11 error from above

**Comment by eerovaher** [comment]
If this is a bug in `astropy` then it should be possible reproduce the error without involving `conda` and without having to edit the source code of `astroplan`.

**Comment by pllim** [comment]
`astropy` by itself never tries to open X11. The `planning.py` you pointed to is a `QApplication` and seems like also you are doing a `from lib import *` and have `__pycache__` in your repo. I would recommend to clean up intermediate files from your version control so you can ensure a clean build in the future. Also maybe don't do a star import from lib for easier debugging.

**Comment by m-schochet** [comment]
Much appreciated @eerovaher & @pllim ! 

I will go and work on this on my end, and if I identify any issues with `astropy` specifically will come back here and reopen this report. For the time being this can be closed, so I'll close it as not planned.

**Comment by pllim** [comment]
p.s. You might also wish to explore existing GUI out there and expand upon it with your own plugin rather than writing your own from scratch. For instance, some ground based telescopes write plugins for Ginga:

https://ginga.readthedocs.io/en/stable/dev_manual/index.html

This way, you do not have to implement things that already come with it (e.g., zoom, stretch, and so on).
