### ISSUE TITLE
FITS does not support masked table columns for non-integers

### ISSUE THREAD

**Issue by embray** [astropy/astropy#1764]
In the process of merging the latest PyFITS master into Astropy I had some tests for `astropy.io.fits.connect` failing, specifically `astropy.io.fits.tests.test_connect.TestSingleTable.test_masked`.

The reason is that in PyFITS I recently added more validation for table keywords that was not previously there.  It turns out that the `TNULLn` keywords may only be used for integer columns ('I', 'J', 'K', etc.).  The FITS Standard is, for whatever reason, quite strict about this using the language "the keyword
_must not_ be used if field n is of any other data type".  "Must not" = strict.

If I understand correctly that means we can't reliably round-trip non-integer masked columns.  A workaround may be possible which is why I'm opening an issue for this.

In the meantime, as part of the merge I'm changing the connect code to ensure that only integer masked columns write a `TNULLn` keyword, and I'm commenting out the last two asserts in the `test_masked` test since they will no longer succeed.

**Comment by taldcroft** [comment]
Closed by #7481
