### ISSUE TITLE
Investigate irritating test failures on Windows

### ISSUE THREAD

**Issue by embray** [astropy/astropy#1765]
Currently all the tests are passing for all the Windows XP builds being performed with Jenkins.  However, in almost every test run for the last dozen or so one or two of the configuration "fail" due to the following:

```
============================= test session starts ==============================

platform win32 -- Python 3.1.4 -- pytest-2.4.0



Running tests with Astropy version 0.3.dev6508.

Running tests in astropy.



Platform: Windows-XP-5.1.2600-SP3



Executable: C:\PythonVirtualenvs\python-3.1-numpy-1.6.0\Scripts\python.exe



Full Python Version: 

3.1.4 (default, Jun 12 2011, 15:05:44) [MSC v.1500 32 bit (Intel)]



encodings: sys: utf-8, locale: cp1252, filesystem: mbcs, unicode bits: 15

byteorder: little

float info: dig: 15, mant_dig: 15



Numpy: 1.6.0

Scipy: not available

Matplotlib: not available

h5py: not available



collected 4938 items / 3 skipped
```

...

```

 generated xml file: E:\Builds\astropy-winxp32-multiconfig\workspaces\COMPILER\msvc\NUMPY_VER\numpy-1.6.0\PYTHON_VER\python-3.1\junit.xml 

====== 4687 passed, 242 skipped, 11 xfailed, 1 xpassed in 219.50 seconds =======

error: c:\windows\temp\astropy-test-q0qnox\lib.win32-3.1\astropy\convolution\boundary_extend.pyd: Access is denied

E:\Builds\astropy-winxp32-multiconfig\workspaces\COMPILER\msvc\NUMPY_VER\numpy-1.6.0\PYTHON_VER\python-3.1>exit 1 
Build step 'Execute Windows batch command' marked build as failure
Recording test results
Finished: FAILURE
```

In other words all the tests that are being run pass, but the test script exits with an error condition due to failure to delete this `boundary_extend.pyd` file from the temp testing directory, likely due to a handle being held open to it.  It's a weird timing issue that appears to occur semi-randomly on any of the configurations.  Very annoying.

I can still manually check all the failing builds to see that the tests are indeed passing which is all that really matters, but it's still something worth trying to fix.  I've never seen this issue before...

**Comment by astrofrog** [comment]
I'm going to close this, since we've now moved to AppVeyor, and I've never see this error after the tests have run.
