### ISSUE TITLE
add a configuration item to give a default doc location to find_api_page

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#1782]
In #1779, @mdboom suggested adding a `ConfigurationItem` that lets the user specify the default location to search for the docs used by `astropy.utils.misc.find_api_page`.  I like this, but there's two problems:
- We need to be a bit careful because if a user points to a specific version, and then they upgrade, they're looking at old docs.  So we probably want to print a message warning them if this happens, but it's not obvious how to find the version corresponding to the documentation (it _might_ be somewhere in the intersphinx file that `find_api_page` uses, but I'm not sure).
- Currently, this would cause a circular dependency problem, because `astropy.config` needs `astropy.utils`, but `astropy.utils` imports `misc`.  So somehow that needs to be worked-around (alternatively, a new version of `config` might address this some other way).

For a first attempt, take a look at my [eteq/cfgitem-for-find-api-page](https://github.com/eteq/astropy/tree/cfgitem-for-find-api-page) branch. It doesn't work right now because of the circular dependencies, but it gets the idea across.

cc @astrofrog

**Comment by pllim** [comment]
Is this still necessary?
