### ISSUE TITLE
Make installation instructions a little less daunting

### ISSUE THREAD

**Issue by embray** [astropy/astropy#1807]
Per my comment here: https://github.com/astropy/astropy/pull/1806#issuecomment-28821050

The installation instructions, in particular the section on installing with pip, is laden with numerous warnings and caveats.  Although I believe they are _all_ necessary I wonder if this couldn't be simplified and made a little less daunting.

I don't have an exact answer yet but I'm thinking that a pre-install checklist might be a nice way to go.  Maybe also a little choose your own adventure to lead users on different platforms through the correct steps.

**Comment by bsipocz** [comment]
Closing this in favour of #6154. While the latter is the real duplication, I leave that open as this on is sadly somewhere at the bottom of the issue list by now.
