### ISSUE TITLE
Transparently provide temp dir for doctests

### ISSUE THREAD

**Issue by embray** [astropy/astropy#1821]
As brought up in #1814, there are several doctests that are disabled because they write files to the filesystem, and normally leave little unwanted surprises behind in your current working directory.

It should be easy enough, however, to modify the doctest runner to automatically set up and enter/exit a temp dir before running each test.  Naturally we should make sure none of the doctests try to write to absolute paths.  I'm -1 on any tricky "sandboxing" or anything like that--just make sure all the tests use paths relative to the temp dir and we should be fine.

**Comment by astrofrog** [comment]
#3076 has been closed without merging - if anyone wants to give this a go, see the discussion in #3076.

**Comment by eerovaher** [comment]
The functionality requested in this issue was provided by #9439, but the pull request wasn't linked to this issue at the time so I am closing this manually.
