### ISSUE TITLE
Should our Debian package install a symlink to the C header files?

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#1868]
While addressing #1755, I noticed that the Numpy Debian package installs a symlink from `usr/include/numpy` to `usr/share/pyshared/numpy/core/include/numpy` so that the Numpy headers can be included without worrying about getting a special include path, etc.  We still need #1755 to support the case of installing from source in a virtualenv, etc., but should our Debian package install a symlink like this?

(Mainly a question for @olebole).

**Comment by bsipocz** [comment]
I'm closing this as we don't track Linux packaging issues here, and I'm sure @olebole has now a working solution.

Feel free to reopen if you think the closure is inappropriate.

**Comment by olebole** [comment]
I think this is appropriate. There were many changes in the last 5 years, and if there is an issue with header files in astropy@debian, one should just create a bug report on https://bugs.debian.org.
