### ISSUE TITLE
Random build errors

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#1882]
This may or may not a continuation of #1009 

On some builds, the tests fail with
```
[...]
astropy/io/votable/tests/vo_test.py:71: test_parse_single_table2 PASSED
make[1]: *** [test-python3.3] Error 245
make: *** [build-arch] Error 2
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2
astropy/io/votable/tests/vo_test.py:202: test_regression PASSED
[...]
```
On the current release, this is the case for the Debian build on the "Hurd" kernel, but it also happened elsewhere (powerpc, sparc). The error seems not appear on the same place, and there is not other output connected to it.

I have no two builds with exactly the same environment available yet, however:
* For Hurd, there is 
  * a [succeeding build](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=hurd-i386&ver=0.3-1&stamp=1385827651) for the original package, and 
  * a [failed build](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=hurd-i386&ver=0.3-2&stamp=1386617981) for the package patched with the big-endian changes as noted in #1849 (Hurd is little endian).
* For Powerpc, version 0.2.5, there is 
  * a [build failure](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=powerpc&ver=0.2.5-1&stamp=1382897366) on Debian, 
  * but for the (very similar) Ubuntu distribution, the [build succeeds](https://launchpad.net/ubuntu/+source/python-astropy/0.2.5-1/+build/5169743/+files/buildlog_ubuntu-trusty-powerpc.python-astropy_0.2.5-1_UPLOADING.txt.gz).

**Comment by olebole** [comment]
I just had this problem on x86_64 with 1.0rc1; however not reproducible. Re-running made the trick. So it may either be some hardware problem (however this appears on different machines, and even different platforms), or a very rare racing condition.

**Comment by astrofrog** [comment]
@olebole - have you seed this issue since? If not, I'm tempted to suggest we close this until the error appears in a more systematic way.

**Comment by olebole** [comment]
Looks fine now. Closing it...
