### ISSUE TITLE
Writing a Table to FITS fails if the table contains objects

### ISSUE THREAD

**Issue by barentsen** [astropy/astropy#1906]
The following works fine:

``` Python
from astropy.table import Table
Table([{'col1': None}]).write('/tmp/tmp.txt', format='ascii')
```

whereas the following fails:

``` Python
Table([{'col1': None}]).write('/tmp/tmp.fits', format='fits')
```

with

```
/home/gb/bin/anaconda/lib/python2.7/site-packages/astropy-0.4.dev6667-py2.7-linux-x86_64.egg/astropy/io/fits/column.pyc in _convert_record2fits(format)
   1727         output_format = repeat + NUMPY2FITS[recformat]
   1728     else:
-> 1729         raise ValueError('Illegal format %s.' % format)
   1730 
   1731     return output_format

ValueError: Illegal format object.
```

This behaviour is seen whenever a Table contains an object, i.e. io/fits/column.py does not know how to deal with `dtype('O')`.

I wonder if we want the Table API to write objects to files by their string representation as a default, or otherwise provide a more meaningful error message?

**Comment by astrofrog** [comment]
Not critical for 1.0 so removing milestone (but if someone feels like implementing it in the next few days, feel free to!)
