### ISSUE TITLE
numpy.dot and numpy.cross won't preserve Quantity

### ISSUE THREAD

**Issue by astrojuanlu** [astropy/astropy#1930]
I'm using astropy 0.3 under python 3.3 with numpy 1.8.0, and I found that `np.dot` won't preserve `Quantity`es as inputs:

```
>>> import numpy as np
>>> from astropy import units as u
>>> q = 1 * u.m; q
<Quantity 1 m>
>>> np.dot(q, q)
1
>>> np.sum(q * q)
<Quantity 1 m2>
```

the same happens with `np.cross`:

```
>>> r = [1, 0, 0] * u.m
>>> v = [0, 1, 0] * u.m / u.s
>>> np.cross(r, v)
array([0, 0, 1])
```

**Comment by Juanlu001** [comment]
The original problem, which was that `np.dot` and `np.cross` don't retain the units, still persists with latest NumPy and Astropy. I got a bit lost on how Astropy wanted to workaround the issue or NumPy to provide a better API, could you please give a brief explanation?

**Comment by Juanlu001** [comment]
Thanks @pllim, I lost sight of that part!
