### ISSUE TITLE
FITS reading in Astropy 0.3 with Table

### ISSUE THREAD

**Issue by sr525** [astropy/astropy#1964]
I was using Astropy 0.3 with python 2.7 and doing something similar to the following:

```
for file in files:
    t = Table.read(file)
```

This seems to have a memory leak as the memory used keeps increasing as each table is read in. The same code using atpy.Table instead of Table.read works fine with no continually increase of memory.

**Comment by saimn** [comment]
I think we can close this, the issue is old and a lot of things changed since that (and a quick test gave a very stable memory usage).
