### ISSUE TITLE
Do testing with unicode string inputs to `astropy.io.fits` on Python 2.x

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#1995]
As part of #1962, which tests with and without the "unicode_literals" setting on Python 2, it was noticed that many of the `io.fits` tests fail when passed Unicode strings on Python 2.  I didn't do any further investigation, so it may be the case that these are all things where Unicode simply doesn't make sense.

**Comment by bsipocz** [comment]
Closing this as we're very close to drop pyton2 support in master, and thus it is extremely unlikely to be addressed. Reopen if you think otherwise.
