### ISSUE TITLE
Potentially confusing behavior for np.isscalar with quantities

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2021]
The following example may lead to confusion:

```
In [10]: np.isscalar(3 * u.m)
Out[10]: False

In [11]: (3. * u.m).isscalar
Out[11]: True
```

There may not be any way around this other than monkey-patching `np.isscalar`

cc @mhvk

**Comment by mhvk** [comment]
This still seems a good idea, but not critical for 1.0 so removed that label.

**Comment by mhvk** [comment]
For reference on this idea:
```
class SQ(Quantity, np.generic):
    pass

q = SQ(1, u.m)
np.isscalar(q)
# True
```
Obviously, we'd have to ensure ourselves that any scalar quantity was, in fact, scalar.

**Comment by mhvk** [comment]
But as a counter-argument:
```
np.isscalar(np.array(1))
# False
```
i.e., even numpy array scalars fail the test. So, we might have to carry that distinction between a 0-dimensional array and a real scalar to `Quantity`. Not completely obvious that we really want that...

**Comment by mhvk** [comment]
Not sure this should stay open, given that even an array scalar is not recognized as a scalar, but labeled it as a (fairly tricky and low priority) feature request for now.

**Comment by bsipocz** [comment]
Given the ambiguity  pointed out above I suggest to close this issue. I suspect whenever the behaviour of `np.isscalar(np.array(1))` changes, the behaviour of scalar Quantities will change, too.
