### ISSUE TITLE
Non-deterministic test failures

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#2065]
I've been seeing a lot of this semi-randomly lately:

```
__multicall__ = <MultiCall 0 results, 0 meths, kwargs={'pyfuncitem': <Function 'test_read_through_table_interface'>}>
pyfuncitem = <Function 'test_read_through_table_interface'>
    def pytest_pyfunc_call(__multicall__, pyfuncitem):
        if not __multicall__.execute():
            testfunction = pyfuncitem.obj
            if pyfuncitem._isyieldedfunction():
                testfunction(*pyfuncitem._args)
            else:
                funcargs = pyfuncitem.funcargs
                testargs = {}
                for arg in pyfuncitem._fixtureinfo.argnames:
>                   testargs[arg] = funcargs[arg]
E                   KeyError: 'tmpdir'
```

I think this has to do with the unicode literals testing functionality running the same test twice and "getting lucky" somehow.

**Comment by umasenthil** [comment]
I am seeing a similar error. It is due to parallel execution:
pyfuncitem = <Function 'test_coxph'>

    @hookimpl(trylast=True)
    def pytest_pyfunc_call(pyfuncitem):
        testfunction = pyfuncitem.obj
        if pyfuncitem._isyieldedfunction():
            testfunction(*pyfuncitem._args)
        else:
            funcargs = pyfuncitem.funcargs
            testargs = {}
            for arg in pyfuncitem._fixtureinfo.argnames:
>               testargs[arg] = funcargs[arg]
E               KeyError: 'flchain'

../../mypythonenv/lib/python3.6/site-packages/_pytest/python.py:154: KeyError
It works if I run the same test sequentially

**Comment by drdavella** [comment]
@umasenthil thanks for the report. What version of Python and astropy are you using?

**Comment by umasenthil** [comment]
@drdavella I am using Python 3.6.3. I am not using astropy.
Thanks

**Comment by drdavella** [comment]
@umasenthil if this issue is unrelated to astropy, it would probably be best for you to report it directly to pytest at https://github.com/pytest-dev/pytest/.

**Comment by umasenthil** [comment]
@drdavella Will do. Thanks for the pointers
