### ISSUE TITLE
Add HTTPS for wheels[2].astropy.org

### ISSUE THREAD

**Issue by msabramo** [astropy/astropy#2068]
These wheel repos are super useful -- thank you!!!:

* http://wheels.astropy.org/
* http://wheels2.astropy.org/

Can you add HTTPS support so we can use the following with confidence (and not get pip warnings)?

* https://wheels.astropy.org/
* https://wheels2.astropy.org/

**Comment by Cadair** [comment]
This is pretty much irrelevant now as conda has made the wheelhouse redundant.

**Comment by mwcraig** [comment]
Agreed!
