### ISSUE TITLE
PEP 3151 for v3.0.0

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#2102]
http://docs.python.org/3/library/exceptions.html#OSError

"Changed in version 3.3: EnvironmentError, IOError, WindowsError, VMSError, socket.error, select.error and mmap.error have been merged into OSError."

Does this mean that we have to change all the occurrence of `IOError` to `OSError` in the codes?

**Comment by mhvk** [comment]
standard python3 is now 3.4... Found this after @astrofrog's request to look for label-less issues, but have no idea what to add....

**Comment by pllim** [comment]
@bsipocz , is PEP 3151 a reasonable goal for v3.0?

**Comment by bsipocz** [comment]
Sounds good to me. Milestone the issue for 3.0, so it will be easier not to oversee.

**Comment by pllim** [comment]
Is this something we should also tackle at the coordination meeting?

**Comment by bsipocz** [comment]
@pllim - Though it's not explicitly listed, but this is on Tom's list: https://github.com/astropy/astropy/issues/6234#issuecomment-328292343

I think we would need #6246 merged before this can be done, but I'm not comfortable merging that before seeing an agreement about it.

**Comment by bsipocz** [comment]
@astrofrog @eteq - Would you think adding a label or a new project would be useful for the meeting, or we all try to keep a list of issues to address in mind and try to remember when we're there?

**Comment by astrofrog** [comment]
@bsipocz - I made https://github.com/astropy/astropy/projects/3 - note that this is separate from the 3.0 planning board since not all issues to discuss are necessarily relevant for 3.0.

**Comment by bsipocz** [comment]
Would you prefer to have one "sprint" column, or separate columns for the different sprints? (e.g python2 removal related, package-template fixup, affiliated package docs, etc?)

**Comment by bsipocz** [comment]
@astrofrog - would it be possible to move the project to be an organization project? so then we can add issues to the board from other repos, e.g. helpers and the package_template, too.
