### ISSUE TITLE
Document model constrains in one place only

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#2119]
Currently the way `CONSTRAINTS_DOC` is appended to model docstrings results in messed-up sphinx html output. E.g. for [Gaussian1D](http://docs.astropy.org/en/v0.3/api/astropy.modeling.functional_models.Gaussian1D.html) it's merged into the "see also" section and for [Beta1D](http://docs.astropy.org/en/v0.3/api/astropy.modeling.functional_models.Beta1D.html) it's merged into the "notes" section.

EDIT: The issue described above has been addressed by #2120. We are keeping this issue open because the model constraints docs should only be in one place (e.g. the `ParametricModel` base class) and then linked to from each model as @embray describes below.

**Comment by zdroid** [comment]
@astrofrog @embray This should be closed as the issue doesn't exist anymore.

**Comment by pllim** [comment]
This issue is pretty old and probably superseded by the modeling doc revamp done by @nden and @karllark .

**Comment by pllim** [comment]
Although, reading the original issue again, is the second part still an issue?

"We are keeping this issue open because the model constraints docs should only be in one place (e.g. the `ParametricModel` base class) and then linked to from each model..."

**Comment by pllim** [comment]
Ah, it is done already.

https://github.com/astropy/astropy/blob/f58cf9ff03b8cfdc7ca2135d758f5da55473b78c/astropy/modeling/models.py#L28

Thanks for bringing this to our attention, @zdroid !
