### ISSUE TITLE
Make log file for logger safe for multiple processes

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#213]
As discussed in #192, we should switch to using a kind of rotating log file that is safe for writing by multiple processes. The following is an example:

http://pypi.python.org/pypi/ConcurrentLogHandler/

But this requires dependencies and does not work on Windows (?)

**Comment by pllim** [comment]
Is this still necessary? I hear a lot of complains about caching and reading `astropy.cfg` on clusters but no one has complained about logging.

**Comment by embray** [comment]
Nobody's complained probably now that logging is disabled by default anyways, and most users probably aren't using it to begin with, much less with multiprocessing.

There is a nice [recipe](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes) in the Python docs on how to achieve safe logging to a single file in a multiprocessing scenario.  But there's no obvious way to implement that as the default behavior for the Astropy log, though I could probably come up with something.  However, given that Astropy doesn't supply any multiprocessing primitives of its own to begin with, I think it's a very application-specific problem that doesn't necessarily belong in the core library.

I propose closing this for now, but of course it could be revisited if a need arises.
