### ISSUE TITLE
Pyfits: Incorrect writing of non contiguous data in compressed FITS

### ISSUE THREAD

**Issue by pchanial** [astropy/astropy#2150]
Using astropy 0.3.dev4315, the following code prints False instead of True. If ImageHDU is substituted to CompImageHDU, it works correctly and prints True.

```
orig = np.arange(100, dtype=float).reshape((10, 10), order='f')
primary = fits.PrimaryHDU()
hdu = fits.CompImageHDU(orig)
hdulist = fits.HDUList([primary, hdu])
hdulist.writeto('test.fits', clobber=True)
actual = fits.open('test.fits')[1].data
print np.all(orig == actual)
```

**Comment by cdeil** [comment]
We ran into this issue with Gammapy, see here:
https://github.com/gammapy/gammapy/issues/1346

Minimal test case to reproduce:
```
import numpy as np
from astropy.io import fits

data = np.arange(6).reshape((3, 2)).T

hdu = fits.PrimaryHDU(data)
filename = 'tmp.fits'
hdu.writeto(filename, overwrite=True)
hdu2 = fits.open(filename)[0]

data2 = hdu2.data

print('data:\n', data)
print('data2:\n', data2)
```
gives the incorrect result (i.e. data is different after write / read):
```
data:
 [[0 2 4]
 [1 3 5]]
data2:
 [[0 2 4]
 [1 3 5]]
```
When removing the `.gz`, i.e. writing just to `tmp.fits`, the data comes back OK.

This is very confusing for users, either an error, or making it work via a copy would be preferable.

**Comment by MSeifert04** [comment]
I think I'm blind. I can't see any difference between those two. Could you clarify?

**Comment by cdeil** [comment]
@MSeifert04 - I had copy & pasted the wrong test case and output. I've updated my last comment just now, please refresh.

**Comment by MSeifert04** [comment]
Ah thanks!

That's not good ... I will look into this (although probably not this week) but if it's indeed effort-high (label) raising an exception might make sense. :)

**Comment by cdeil** [comment]
> You might consider passing np.ascontiguousarray(the_input_image) to CFITSIO. It will make a copy only if the data is not C contiguous.

@pchanial - Would that still be your proposed change to `astropy.io.fits` to handle this issue?

**Comment by saimn** [comment]
Reading the discussion above, `np.ascontiguousarray` seems the easiest way to go for now, not the most efficient but at least it would fix this usecase.
