### ISSUE TITLE
Table units are sometimes carried too far

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2169]
The following example demonstrates where the current table behavior with units may be undersirable:

```
In [11]: import numpy as np

In [12]: from astropy.table import Table

In [13]: t = Table()

In [14]: t['flux'] = [1,2,3]

In [15]: t['flux'].unit = 'mJy'

In [16]: t['mag'] = np.log10(t['flux'])

In [17]: print t
flux      mag      
mJy       mJy      
---- --------------
   1            0.0
   2 0.301029995664
   3  0.47712125472
```

In this case, there's no reason that the column 'mag' should have any units. I know we want to refactor how columns with units are handled, but just wanted to raise this since I ran into it today.

cc @mhvk @taldcroft

**Comment by mhvk** [comment]
Closing this since we decided that in regular `Table` instances, units are ignored in mathematical operations. The example correctly raises a `TypeError` for a `QTable`.
