### ISSUE TITLE
Add a `sampleset` property to models

### ISSUE THREAD

**Issue by nden** [astropy/astropy#2190]
It returns a grid of input points specific to a model instance on which the model is sampled reasonably well. Composite models will return a union of the sets of points of individual models. The discussion started on astropy-dev.

**Comment by embray** [comment]
This is partly implemented via bounding boxes in #3909.  The difference is that bounding boxes only give lower and upper bounds on which to evaluate the model--which are obviously points that would be included in the sample set.  But I think it shouldn't be hard, and in fact would be beneficial, to expand the bounding box functionality to allow it to return some arbitrary set of points on which to evaluate the model (then the bounding box itself would just be the lower and upper points in the sample set).

**Comment by pllim** [comment]
I wouldn't call it "arbitrary". Sampleset should be designed to optimally sample the given model. For example, in a Gaussian, it should tightly sample around the peak; For a box, it samples the edges; For a straight line of constant amplitude, it is not applicable (`None`?).

**Comment by embray** [comment]
@pllim For a specific model it wouldn't be arbitrary.  But the general capability would be a property/method similar to bounding_box but that allows an arbitrary number of points in general (as opposed to just bounds).

**Comment by pllim** [comment]
Looks like I am the only one who ever requested it. By now, I am content to keep it over at https://github.com/spacetelescope/synphot_refactor .
