### ISSUE TITLE
Fit float/int representation for progress bar

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2201]
For iterables with sizes that don't require suffixes in the progress bar, it might make more sense to use integers:

```
In [2]: from astropy.utils.console import ProgressBar

In [3]: ProgressBar([1,2,3]) 
|>------------------------------------------| 0.0 /3.0  (  0.00%)
```

Tagging as low-priority and easy in case a GSoC student or other first time contributor wants to give it a try.

**Comment by embray** [comment]
Fixed in #3299 .
