### ISSUE TITLE
Develop Time Series base class

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2205]
We should consider creating a sub-class of `Table` that supports time series - i.e a table with a default Time-based index.

**Comment by wtgee** [comment]
Hi all. I just wanted to check on this issue now that some time has passed. I know that `Table`s have rudimentary support for indices in v1.1 but it still seems like nothing that is time series specific. Is the answer still to use pandas?

**Comment by taldcroft** [comment]
@wtgee and others - now that we have the basic indexing infrastructure which can be used on a Time column, what are the specific methods and functionality that are a top priority?  As a reminder, here is what you can do right now in 1.1:
```
In [20]: t = Table([Time('2000-01-01') + [5,4,3,2,1] * u.day, [1,2,3,4,5]], names=['date', 'val'])

In [21]: t.add_index('date')

In [22]: t
Out[22]: 
<Table length=5>
          date           val 
         object         int64
----------------------- -----
2000-01-06 00:00:00.000     1
2000-01-05 00:00:00.000     2
2000-01-04 00:00:00.000     3
2000-01-03 00:00:00.000     4
2000-01-02 00:00:00.000     5

In [23]: t.loc[Time('2000-01-03 00:00:00.000')]
Out[23]: 
<Row index=3>
          date           val 
         object         int64
----------------------- -----
2000-01-03 00:00:00.000     4

In [24]: t.loc[Time('2000-01-03 00:00:00.000'):Time('2000-01-05 00:00:00.000')]
Out[24]: 
<Table length=3>
          date           val 
         object         int64
----------------------- -----
2000-01-03 00:00:00.000     4
2000-01-04 00:00:00.000     3
2000-01-05 00:00:00.000     2
```

**Comment by wtgee** [comment]
On that recommendation I jumped right in and started using the `Table` class and it suits my purposes fine for now. The issue for me is that I am loading via HDF5 and don't know the explicit paths to the tables stored in the files. I can read them in via pandas and an `HDFStore` and then have access to all the paths as keys and the values as dataframes. From there I don't (yet) have a compelling reason to turn those `DataFrame`s into astropy `Table`s since I already have them loaded. (This is more a generic `Table` issue and not related to the time series question so I don't want to go on that tangent here).

I agree that a good brain-storming of features/subtractions w.r.t pandas time series would be nice but I don't personally have any specific recommendations at this point. Thanks for the recommendation for the `Table` though, I'll start using it where appropriate for time series and see what I might be missing.

**Comment by taldcroft** [comment]
## Excerpt of notes from time series unconference session at PyAstro16

### What do we all want from a time series?

Re-sample (including recalc uncertainties properly), re-bin, time index columns that aren’t necessarily middle of the range but also start and end of bin like a histogram, time shifting or frame conversion, adding and subtracting, append, metadata, support for variable time bins, ability to store some kind of background time series, be monotonically increasing…

### What do we want to do to a time series?

Plot, make a periodogram/power spectrum, do unit conversions between time units/systems (e.g. from different telescopes)

### How would the implementation look?

Sub-class of Table? Separate module that can take a table? Not really any difference practically between these two approaches. Tom envisions the time column as an astropy time object. Does this approach support relative time? Yes, with deltatime concept. Probably makes the most sense as a sub-class of Table.

Steven: the advantage of pandas (over table) is it can do most things we want right out of the box (like rebinning).

Advantage of Table over pandas is units, metadata, fewer dependencies. Matt points out that pandas rebinning won’t let you account for, e.g. weighting as a function of flux or airmass if it’s changing in time.

Some people have performance concerns -- light curves with ~ 1 million timestamps

### What’s the ‘no data’ value? 
For Abbie and Daniela, it’s a zero. Brett and Mike don’t have this problem, but occasionally they want a nan when a cosmic ray hits the detector.

### What’s the minimum an astropy time series table needs for you to use it?

**Stingray**: have evenly-spaced time binning, be able to re-bin, accept counts or count rate, convert between counts and count rate, concatenate, throw a warning for gappy data, how do you handle overlapping timestamps in concatenated data, base class should have multiple columns (but one time column)

**SunPy**: It should be able to sort itself along the time column (in computer speak, maintaining an index that is sorted). Monotonically increasing times (i.e., always be sorted). Re-sampling/interpolation. Adding and subtracting light curves with the same timestamps (Tom says it’s trivial! yay!). Some kind of metadata. Can hold a region of interest object somewhere somehow. Support for variable time bin sizes (so, index is a time range, not a timestamp; need two time columns, time start and time delta/time end? Would index on start time). 

### What should a Lightcurve class do?

- Rebin (including recalculating uncertainties)
- Time index column both middle of bin and bin edges
- Time shifting/frame conversion (is there a WCS standard for time?)
- Should always be sorted
- Handling missing data
- Truncate
- Extend (add two together) → concatenate
- Interpolate to new time stamps
- Add/subtract light curves
- Metadata (need to keep some information about energy ranges etc)
- Regions of interest (in the light curve) or masks?
- Values need units and uncertainties
- Plot itself
- Support for variable time bin sizes
- Might want to have an optional background attribute or method?
- Relative or absolute time?
- Sampling a continuous measurement
- Export to pandas
- Export to csv

**Comment by taldcroft** [comment]
See also https://github.com/Cadair/astropy-APEs/blob/master/APE9.rst.

**Comment by pllim** [comment]
xref astropy/astropy-APEs#12

**Comment by pllim** [comment]
I *think* this is about the new `astropy.timeseries` module, yes?

**Comment by astrofrog** [comment]
Yep!
