### ISSUE TITLE
Unicode angles do not show properly in Matplotlib plots

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2232]
At the moment, plotting a unicode formatted angle in Matplotlib:

```
import matplotlib.pyplot as plt
from astropy.coordinates import Angle

a = Angle(13.43311, 'deg')

fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.text(0.5, 0.5, a.to_string(format='unicode'),
        transform=ax.transAxes, size=36, ha='center')
fig.savefig('test.png')
```

does not work nicely:

![test](https://f.cloud.github.com/assets/314716/2506180/9cd447a6-b3a3-11e3-84af-56e75e41d396.png)

@mdboom - is there a way to get this to work nicely?

**Comment by adrn** [comment]
Since this is font-specific, I think this is a "wont fix" issue - thoughts @astrofrog ?

**Comment by astrofrog** [comment]
Well I think there was a suggestion here to add a latex format option to ``tostring``?
