### ISSUE TITLE
Emacs coding guidelines, no mention of flymake-cursor

### ISSUE THREAD

**Issue by jeanconn** [astropy/astropy#2236]
Should the emacs docs at:

https://github.com/astropy/astropy/blame/master/docs/development/codeguide_emacs.rst#L16

mention that you might also need the flymake-cursor package for this line to work:

https://github.com/astropy/astropy/blame/master/docs/development/codeguide_emacs.rst#L138

?

**Comment by bsipocz** [comment]
Closing as both ``column-marker.el`` and ``flymake-cursor.el`` is mentioned in the current docs.
