### ISSUE TITLE
Write new parameter constraint tests

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2265]
In #2264 I propose removing four unit tests that checked if models with constraints on some parameters correctly passed the parameter values on to fitters in such a way that the constraints are obeyed.  

Since as of #2264 models themselves are no longer directly responsible for that (constraints are just added as _information_ that a fitter can use) these tests need to be reimplemented in the context of use of those models with actual fitters.  Furthermore it would be best to test each type of constraint with all fitters included in `astropy.modeling` that support that type of constraint.  Combinations of constraints should also be better tested.  That would give much better test coverage so that issues like #2235 can be caught.

**Comment by astrofrog** [comment]
@embray - if this won't be done this week, we should remove the milestone. Do you agree?

**Comment by astrofrog** [comment]
Removed milestone since this won't get done in time for 1.0.

**Comment by embray** [comment]
I think this was mostly a reminder-to-self, and I don't really know anymore what I was talking about here.  Many new tests have since been added to `astropy.modeling` including new tests for fitting with constraints.  If there are specific cases that need tests we can add them as they come up.
