### ISSUE TITLE
Quantity: np.nanmax on unitless quantity array with all-nan axis breaks

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#2340]
There is a problem with Quantity's full of nans along an axis:
```
In [21]: x = np.array([[0.2,np.nan,0.3],[0.1,np.nan,0.3],[0.4,np.nan,0.1]]) * u.dimensionless_unscaled

In [22]: x
Out[22]:
<Quantity [[ 0.2, nan, 0.3],
           [ 0.1, nan, 0.3],
           [ 0.4, nan, 0.1]]>

In [23]: np.nanmax(x,axis=0)
Out[23]: <Quantity [ 0., 1., 0.]>

In [26]: np.nanmax(x.value,axis=0)
Out[26]: array([ 0.4,  nan,  0.3])

In [29]: astropy.__version__
Out[29]: '0.4.dev8068'

In [30]: np.__version__
Out[30]: '1.8.1'
```

**Comment by mhvk** [comment]
@keflavich - while checking things that had the 1.0 label, I came across this. As a fix is in, I'd tend to close this. Would you want to add something about this to the known issues page, or do you think this is sufficiently obscure that we should not bother? (don't have time myself...)

**Comment by keflavich** [comment]
@mhvk - I'm OK with closing it without adding a known issue, but it should at least be stated on this page what "latest version of numpy" means, since it is changing over time.  I assume 1.9 is the "solved" version?

**Comment by mhvk** [comment]
@keflavich - I just checked and it seems this has actually been backported to numpy 1.8.2!
```
In [5]: x
Out[5]: 
<Quantity [[ 0.2, nan, 0.3],
           [ 0.1, nan, 0.3],
           [ 0.4, nan, 0.1]]>

In [6]: np.nanmax(x,axis=0)
Out[6]: <Quantity [ 0.4, nan, 0.3]>

In [7]: np.version.version
Out[7]: '1.8.2'
```

**Comment by embray** [comment]
Our minimum required Numpy version is 1.6 though, so this should still be documented as a known issue shouldn't it?

**Comment by mhvk** [comment]
I thought this felt under the "sufficiently obscure that nobody will notice it" (at least until numpy 1.8 is our minimum required version). But if someone wants to test on which versions it does and does not work, and write the documentation, then that is of course better.

**Comment by mhvk** [comment]
With another year gone by, and nobody stepping up to do the docs update, I think "sufficiently obscure that nobody will notice it" has hit us, so I'm closing this.
