### ISSUE TITLE
WCS with lookuptables (tabular)

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#2362]
It appears that lookup table WCS cannot be created with `astropy.wcs` at present.  

http://astropy.readthedocs.org/en/latest/api/astropy.wcs.Tabprm.html#astropy.wcs.Tabprm says a `Tabprm` table cannot be directly instantiated.

This is a feature request or a request for documentation if the functionality already exists.  I'll help with implementation, but I need some direction.  Does anything need to be modified in the C wrapper?  Or is it just the python frontend that needs to be made?  

Does `astropy.wcs` presently know how to write a tabular WCS, or do we need to implement that too?

**Comment by cdeil** [comment]
In Gammapy having a way to construct a lookup table WCS from Python would also be very useful.

Currently we have to handle our spectral log energy axis ourselves, without using `astropy.wcs` ... see [SpectralCube](https://gammapy.readthedocs.org/en/latest/api/gammapy.data.SpectralCube.html) and [LogEnergyAxis](https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.LogEnergyAxis.html).

**Comment by parejkoj** [comment]
This is likely related to #7883 and I think is still an open issue? @nden ?

**Comment by mcara** [comment]
In PR #9641 I implemented support for the `-TAB` algorithm in FITS WCS defined in WCS Paper III.

**Comment by mcara** [comment]
To those (still) interested: https://github.com/astropy/astropy/pull/9641 has been merged and `WCS-TAB` should now be supported in `astropy.wcs`. Please give it a try.

**Comment by pllim** [comment]
Closing as solved. Thanks, @mcara !
