### ISSUE TITLE
Add option to skip files in doctest collection

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#2364]
There should be a way to skip files during doctest collection.

I've given a more detailed description and motivation here:
https://github.com/astropy/astropy/pull/2310#issuecomment-40212486 .

I think `DoctestPlus.pytest_ignore_collect` (see [here](https://github.com/astropy/astropy/blob/master/astropy/tests/pytest_plugins.py#L280)) currently overwrites the normal pytest `collect_ignore` mechanism (see [here](http://pytest.org/latest/example/pythoncollection.html#customizing-test-collection-to-find-all-py-files)), because if I put

```
collect_ignore = ['docs/tutorials/image/sherpa_fit_image.py']
```

in the affiliated package `gammapy/conftest.py` it has no effect (or am I using it incorrectly?).

@embray Is it possible to restore the normal pytest `collect_ignore` functionality ... I think that's exactly what I need here.

**Comment by pllim** [comment]
@cdeil, I stumbled upon this old issue. Did you try using `__doctest_requires__` in those files and see if `doctest` will then skip them if the dependency is not found? See `astropy/visualization/mpl_normalize.py` for an example.

**Comment by bsipocz** [comment]
@cdeil - is this still an issue or you found a workaround that works for you? As @pllim said, one cuurenlty availbale option is ``__doctest_requires__``, but the other one is to skip the file with e.g. ``.. doctest-skip-all``, or part of it with ``__doctest_skip__ ``

**Comment by bsipocz** [comment]
I'm closing this as the suggestion above in the last two commits should cover the use cases.
