### ISSUE TITLE
Preserve call signature in @deprecated

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2367]
And perhaps in other decorators as well.  As mentioned [here](https://github.com/astropy/astropy/pull/2348/files#r11954430) I'm hoping to write a function that can programmatically generate functions with a given call signature.  Once that's done it will be helpful in implementing a version of `functools.wraps` that also preserves the original function's call signature (perhaps with a few caveats, such as limited support for default arguments).

**Comment by pllim** [comment]
I see that #2849 was merged a long time ago. Is this still an issue?
