### ISSUE TITLE
Refactor terminal size handling

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2378]
There are a few little bundles of code buried in the `ProgressBar` class related to determining a command line terminal width where possible.  It would be nice to pull these bits out into separate utility functions that can be used by other code, as there are other functions which output to stdio that could benefit from formatting based on terminal width.  See #821 for example.  Could be useful for printing tables and the like as well.

**Comment by astrofrog** [comment]
This was addressed in #2427
