### ISSUE TITLE
Define color themes

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#244]
To support nice default visuals on both light and dark background screens we should define color themes.  Then routines that use color_print (currently vo and table) should rely on colors from the theme instead of hardwired colors.  The color themes and user-selected theme would be configurable.

**Comment by zdroid** [comment]
How relevant is this? Any color printing in shell has to use shell color codes. That leaves it up to user to style their own terminal accordingly, not up to any specific program.

**Comment by bsipocz** [comment]
I don't feel this is relevant any more, but @taldcroft can comment.

**Comment by adrn** [comment]
I agree with @bsipocz - maybe @taldcroft can reopen if he disagrees :)
