### ISSUE TITLE
Doctests: Automatically make dicts ordered?

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2465]
This one could be really tricky--there are a handful of doctests that sometimes fail for me because, depending on the exact Python version etc. a dict in the test returns its keys in a different order, which later affects some printed results.

I feel like it should be possible, at least in the case of dict literals, to parse the code and replace that dict literal with and ordereddict.

I'm not sure what else to do with these failing tests for now, but at least their intermittent and only on certain platforms.

**Comment by bsipocz** [comment]
I'm closing this with "won't fix" given we are >=3.5 already...

**Comment by pllim** [comment]
I need to bookmark this one as living proof that if one leaves a problem untouched long enough, it will fix itself! :smile:

**Comment by bsipocz** [comment]
I'm pretty sure we had a few others like that, too.

**Comment by tepickering** [comment]
Procrastination pays. It is known.
