### ISSUE TITLE
Handling nested columns in astropy.table

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#2485]
Over on spacetelescope/finf-standard#6, we're discussing the idea of having nested columns in a table, i.e.:

```
coordinate
  ra
  dec
```

Numpy arrays support this with a dtype like:

```
dtype([('coordinate', [('ra', 'f8'), ('dec', 'f8')])])
```

From experimentation, it seems that `astropy.table.Table` doesn't support this at the moment.

@taldcroft: Do you think this is a good idea?  A lot of work?

**Comment by taldcroft** [comment]
With #3011 this will be do-able, but does require some finessing of certain issues.  Clearing the 1.0 milestone now.

**Comment by embray** [comment]
Something like this has been long-since doable now:

```python
>>> dt = np.dtype([('coordinate', [('ra', 'f8'), ('dec', 'f8')])])
>>> x = np.array([((0, 1),), ((2, 3),)], dtype=dt)
>>> t = Table(x)
>>> t
<Table length=2>
coordinate
 void128  
----------
  (0., 1.)
  (2., 3.)
>>> t['coordinate']['ra']
NdarrayMixin([0., 2.])
>>> t['coordinate']
NdarrayMixin([(0., 1.), (2., 3.)], dtype=[('ra', '<f8'), ('dec', '<f8')])
```

The display of such columns is not so perfect (e.g. the dtype is displayed as `void128`) but this can still be supported better with mixin columns.  I propose close?

**Comment by taldcroft** [comment]
Agreed this should be closed now.
