### ISSUE TITLE
Transition Quantity to use ``__array_ufunc__``

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2492]
It looks like we should start preparing the transition to `__numpy_ufunc__` (see e.g. https://github.com/numpy/numpy/issues/4709#issuecomment-43180286) since it will replace `__array_prepare__` etc. in the long term.

@mhvk @mdboom - are either of you interested in trying to investigate this?

**Comment by mhvk** [comment]
Added `upstream fix required` since this is still not in numpy. Also changed title to `__array_ufunc__` -- the likely successor.

**Comment by bsipocz** [comment]
I believe #2583 implemented this, reopen if that's not the case.
