### ISSUE TITLE
dev version number is wrong if in a non-astropy git directory

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#2561]
I noticed this today while running some of the astropy tutorials.  If I went into python from the tutorials directory, and did ``astropy.__version__``, to my surprise it said ``'0.4.dev280'``.  But if I do the same in some other (non-git) directoy, it correctly reported something like ``'0.4.dev8896'``

I think what's happening here is that the version package is getting the git dev# from the local directory, thinking that we're in astropy... but of course that's wrong, because it's not actually in the astropy source dir.  The solution is presumably to check somehow if we're in the astropy directory, and use the local dev# if so, otherwise fall back on the "last generated" scheme.  @embray, does that make sense to you? (I think you wrote the last iteration of the version stuff?)

**Comment by astrofrog** [comment]
I've encountered this in other packages, and I think that we should actually freeze the version number upon installation. What we should do is that the ``version.py`` file that gets copied to ``build`` should have a frozen number or hash, so that it still works as expected if importing from the source tree but in any other circumstance it will no longer try and determine it.

**Comment by embray** [comment]
@astrofrog See https://github.com/astropy/astropy-helpers/issues/133#issuecomment-73618009

**Comment by embray** [comment]
Should be fixed by astropy/astropy-helpers#137.  This can be closed soon as astropy-helpers has been updated in Astropy.

**Comment by astrofrog** [comment]
@embray - are you planning on doing a PR to update astropy-helpers or should @eteq or I do it?

**Comment by embray** [comment]
I will.

**Comment by eteq** [comment]
@embray - are you going to do both 0.4.5 and master/1.0.x?  I can definitely do the latter, but this is now all we're waiting on for the RC.

**Comment by embray** [comment]
Fixed by #3484.

**Comment by embray** [comment]
I have to go, so a similar PR should be made, yes.

**Comment by eteq** [comment]
not yet fixed in master (or 1.0.x), so I'm reopening, but will prepare a PR shortly for that.
