### ISSUE TITLE
A C backend

### ISSUE THREAD

**Issue by vitenti** [astropy/astropy#2590]
Hi, I've been developing a numerical cosmology in C for while now and I just found your project which has several superpositions with I'm doing. The library (NumCosmo https://savannah.nongnu.org/projects/numcosmo/) is developed in C, but as I'm using GObject I get automatic bindings for it in Python (some examples here: http://www.nongnu.org/numcosmo/).

I know that is a rather different direction but if it could be included as a backend of Astropy it could be very helpful for both projects. It has already the python bindings it would just need to be set in a common convention.

The library implements a general concept of parameter, model, modelset, data, dataset, fitting, etc, etc. They are all independent of the cosmology part and can be used in any context. 

It has a several statistical tools ( interactive calculation of mean, sd, var, cov, etc ). Best-fitting, likelihood ratio test, fisher matrix, montecarlo, bootstrap, etc. I'm also implemented a general setting for mcmc to support different samplers.

General serialization/de-serialization routines, so one can save the state of a fitter, model (any object actually), or can send it through the network to run parallelized.  

Numerical differentiation, automatic gradients of the likelihood.

One/bi-dimensional splines (with knot-a-knot boundary conditions) and auto-knots.

In the cosmological part I have cosmological distances, recombination, several cosmological observables (SNIa with covariance, BAO, H(z), WMAP/Planck distance priors, etc). A good support for cluster abundance calculations.

An almost complete implementation of a Boltzmann code (it is ready but the code is not organized and I'm moving to a full gauge-invariant implementation). A sub-set of the Healpix (using fftw as backend).

There are also many other codes but the ones above are well developed.

The test units are in their beginning but I have somewhat general documentation, it needs more examples and step-by-step tutorials.

Thanks, for the attention and any feedback is welcome.

[]
Sandro

**Comment by bsipocz** [comment]
Given the licence differences and the 2.5 years passed since the opening, I wonder whether this issue can be closed?
