### ISSUE TITLE
Delete of a non-existent CompImageHDU header keyword raises KeyError

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#2594]
When attempting to delete a header keyword that does not exist in the header of a compressed ``HDU``, a `KeyError` is raised. This behavior is different from the behavior of `del` method in a "regular" (not compressed) `ImageHDU` which does not raise an exception:
```python
>>> from astropy.io import fits
>>> flt=fits.open('ichx03iaq_flt.fits')
>>> hdu1=fits.ImageHDU(data=flt[1].data,header=flt[1].header)
>>> hdu2=fits.CompImageHDU(data=flt[1].data,header=flt[1].header)
```
**Attempt to delete a non-existent keyword in a compressed `CompImageHDU`:**
```python
>>> del hdu2.header['whatever']
Traceback (innermost last):
  File "<console>", line 1, in <module>
  File "/.../lib/python2.7/.../astropy/io/fits/hdu/compressed.py", line 159, in __delitem__
    raise KeyError("Keyword %r not found." % key)
KeyError: "Keyword 'whatever' not found."
```
**Attempt to delete a non-existent keyword in a regular `ImageHDU`:**
```python
>>> del hdu1.header['whatever']
WARNING: AstropyDeprecationWarning: Deletion of non-existent keyword 'WHATEVER': 
In a future Astropy version Header.__delitem__ may be changed so that this raises a 
KeyError just like a dict would. Please update your code so that KeyErrors are caught 
and handled when deleting non-existent keywords. [astropy.io.fits.header]
```

`CompImageHDU` should be modified to allow delete of non-existent header keywords.

**Comment by embray** [comment]
Apparently I never did fix this.  But per #4429 I would like to remove the deprecated old functionality once and for all, which would make this issue moot.

**Comment by pllim** [comment]
@mcara , a potential fix was made by @bsipocz and merged into master as #5020, can you please check if it fixed your issue here?

**Comment by mcara** [comment]
After 2 and 1/2 years I do not even remember what all this is about... Let me see...

**Comment by mcara** [comment]
I can confirm that deletion of a non-existing keyword on an ``ImageHDU`` triggers ``KeyError`` (not the fix  I was expecting when I reported this issue but see https://github.com/astropy/astropy/issues/2594#issuecomment-45079804):

```python
>>> from astropy.io import fits
>>> flt=fits.open('ichx03iaq_flt.fits')
>>> hdu1=fits.ImageHDU(data=flt[1].data,header=flt[1].header)
>>> hdu2=fits.CompImageHDU(data=flt[1].data,header=flt[1].header)
>>> del hdu2.header['whatever']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../astropy/astropy/io/fits/hdu/compressed.py", line 163, in __delitem__
    raise KeyError("Keyword %r not found." % key)
KeyError: "Keyword 'whatever' not found."
>>> del hdu1.header['whatever']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../astropy/astropy/io/fits/header.py", line 228, in __delitem__
    raise KeyError("Keyword '%s' not found." % key)
KeyError: "Keyword 'WHATEVER' not found."
```

**Comment by pllim** [comment]
Okay then. Considered "fixed". Thanks for checking!
