### ISSUE TITLE
Change check for optional dependencies in tests

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#2603]
The standard way to skip tests that require optional dependencies is to look for `ImportError`: http://docs.astropy.org/en/latest/development/testguide.html#tests-requiring-optional-dependencies

I have a case where the import throws a `RuntimeError` because the optional dependency package is broken. Wouldn't it be better to check for any `Exception` on import when deciding which tests to skip?

I.e. I propose to replace this:

``` python
try:
    import scipy
    HAS_SCIPY = True
except ImportError:
    HAS_SCIPY = False
```

with this everywhere:

``` python
try:
    import scipy
    HAS_SCIPY = True
except Exception:
    HAS_SCIPY = False
```

So the semantics would change from "Skip test if a dependency is not installed" to "Skip test if a dependency is not working".
If we agree this would be an improvement I can turn this into a pull request quickly.

**Comment by bsipocz** [comment]
@cdeil - do you think this is still an issue? I see that in ``requires_dependency`` in gammapy you're also only excepting ImportError.

**Comment by cdeil** [comment]
Closing this old suggestion.

I re-read the discussion above. Overall I'd say putting `ImportError` (as-is now) or `Exception` (what I proposed) is about equally good. In some edge cases one would be better, in other edge cases the other. Most of the time the two will be equivalent. So let's leave as-is.

**Comment by drdavella** [comment]
Now that this issue is closed.....

It seems like using `pytest`'s `importorskip` is superior to either of these solutions. Is there any reason to prefer the `try`/`except` solution given that `pytest` already provides this functionality?

**Comment by saimn** [comment]
@drdavella - There is another discussion in #5543 (the one here is about catching `ImportError` vs `Exception`).

**Comment by pllim** [comment]
If this ever re-opens, I am against catching a general `Exception`. If needed we can catch both `ImportError` and `RuntimeError`.

**Comment by bsipocz** [comment]
I'm very much agree with @pllim, if there is a well defined list of exceptions that we need to catch then we shouldn't except a more generic one.
