### ISSUE TITLE
Document pixel coordinate convention for Astropy

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#2607]
In photutils @kbarbary added a description of the pixel coordinate convention  [here](http://photutils.readthedocs.org/en/latest/photutils/index.html#coordinate-conventions-in-photutils). I think this should be moved to Astropy core now, as it is (I think) uncontroversial but needs to be documented and followed consistently in Astropy core and affiliated packages.

It's not quite clear where to put it though, because it relates to a bit to `astropy.nddata`, `astropy.modeling` and `astropy.wcs`. I think we should make a new `array_coordinate_convention.rst` page and also add some code examples of how to use `np.meshgrid`, `np.indices`, `wcs` etc correctly with `astropy.modeling`, `astropy.nddata` and `astropy.wcs` and mention that one has to use `origin='lower'` with `plt.imshow` to get an "astronomically correctly oriented" image.

@eteq @astrofrog @keflavich @embray Do you think this is a good idea? If yes, where should I put this page?

**Comment by astrofrog** [comment]
This is not critical to 1.0, so removing milestone (but if someone wants to work on this in the next few days, we can include it!)

**Comment by cdeil** [comment]
This exists now here: http://docs.astropy.org/en/stable/wcs/wcsapi.html#pixel-conventions-and-definitions

Closing this old issue from 2014.
