### ISSUE TITLE
Cannot change_name using ColDefs()

### ISSUE THREAD

**Issue by steveehlert** [astropy/astropy#2618]
Hi-

I need to merge together several catalogs/Binary Tables that initially have the same names for every column. However, since they are all in different filters I want to rename the photometry columns for each band. 

In principle, this should be extremely straightforward with the ColDefs.change_name function, but it does not appear to be working right now. 

Here is the code I am trying to run:

from astropy.io import fits as pyfits
fits=pyfits.open("coadd_B_initial.cat")[2]
coldefs=fits.data.columns
coldefs.change_name("MAG_APER","MAG_APER_BBAND")

but when I look at coldefs both before and after this final line the name of the relevant column remains "MAG_APER" no matter what I try. Is there something I am missing about this operation, and is there any reason why it would not work? 

Thanks in advance.

**Comment by embray** [comment]
Fixed by #3283.
