### ISSUE TITLE
Don't use multiple caches for different Python versions

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#2621]
Currently Astropy keeps multiple versions of data files in the cache for different Python versions. I can't imagine a good use case where this makes sense, but it does mean that some users will re-download big files and keep multiple copies on their disk by accident (this is what happened to me in #2596).

So this is a request to change this to not use multiple caches for different Python versions.

As explained by @eteq in  https://github.com/astropy/astropy/issues/2596#issuecomment-45929717 this might require not using the `shelve` module to implement the cache ... he hinted in that comment that there might be other good reason to change this.

**Comment by pllim** [comment]
With Python 2 support dropped, is this still an issue?

**Comment by bsipocz** [comment]
Yeah, I think you're right.
