### ISSUE TITLE
Save multiple Table objects to one FITS file

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#2632]
I have multiple `astropy.table.Table` objects that I'd like to save to one FITS file.

From the docs (see [here](http://astropy.readthedocs.org/en/latest/io/unified.html#fits)) I couldn't figure out how to do this ... for now I create `BinTableHDU` objects by initialising from `table._data` and put those in a `HDUList` ... but there must be a better way for this common task!?

@taldcroft @embray Can you implement and / or document how to do this? (Apologies if I missed it in the docs.)

**Comment by astrofrog** [comment]
This is non-trivial, so removing the milestone since it won't get done for 1.0

**Comment by astrofrog** [comment]
Just for anyone looking at this, there are several things we can do here:

* Make it so that ``Table.write(HDU)`` works
* Make it so that e.g. ``Table.write(HDUList, append=True)`` works

**Comment by cdeil** [comment]
A related issue I ran into again today is that writing all-ascii string columns to FITS in Python 3 silently encodes the characters with zero-padded 4 bytes, i.e. `abc` is stored as `a\x00\x00\x00b\x00\x00\x00c\x00\x00\x00`.

I still don't understand why, but writing the tables to separate FITS files worked:
```python
table1.write('data1.fits')
table2.write('data2.fits')
```
and instead writing the tables to one FITS file didn't work:
```python
hdu_list = fits.HDUList()
hdu_list.append(fits.BinTableHDU(table1.as_array(), name='data1'))
hdu_list.append(fits.BinTableHDU(table2.as_array(), name='data2'))
hdu_list.writeto('data.fits', clobber=True)
```

I didn't manage to reduce this to a useful example / test case, but the crux of the issue is this:
```python
with open('/tmp/data.csv', 'w') as fh:
    fh.write('name\n')
    fh.write('abc\n')

table1 = Table.read('/tmp/data.csv')
print(table1.dtype)
table1.write('/tmp/data.fits', overwrite=True)
table2 = Table.read('/tmp/data.fits')
print(table2.dtype)
```
```
[('name', '<U3')]
[('name', '<U12')]
```

In the I remembered that I had to call this on all tables before converting them to HDUs and everything works:
```
table.convert_unicode_to_bytestring(python3_only=True)
```

I thought I'd mention this here in case someone else runs into similar issues or it might even be useful to call `convert_unicode_to_bytestring` by default when converting `Table` to `HDU` or to issue a warning if there are unicode string columns?

**Comment by embray** [comment]
@cdeil Could you open a separate issue for this, since I don't think it's directly related to this.

**Comment by taldcroft** [comment]
@cdeil - if you open a new issue you could reference this discussion of a real fix for the unicode problem in numpy.  So far this has generated a couple of long discussion but no agreement or action.  Sigh.

http://mail.scipy.org/pipermail/numpy-discussion/2014-July/070586.html

**Comment by embray** [comment]
Although every time that discussion comes up I point out [this solution](https://github.com/embray/PyFITS/blob/c11abd331cff7e177f0fc551188347e529cde92d/lib/pyfits/fitsrec.py#L999) for which I still haven't heard too many downsides.  It's not 100% perfect, but it gets most of the way there for most cases anyone cares about (which is reading and writing some arrays of strings).

**Comment by cdeil** [comment]
@embray OK, I've tried to file a separate issue about the text column to FITS issue: #3311.

**Comment by cdeil** [comment]
I've run into a performance issue [here](https://github.com/gammapy/gammapy/pull/249/files#diff-25f266495d68c172624588a69347a42cR299).

I have two `Table` objects that I want to store in one FITS file.

The code I use is roughly:
```python
table1 = astropy.table.Table(...)
table2 = astropy.table.Table(...)

hdu_list = fits.HDUList()

data = table1.as_array()
header = fits.Header()
header.update(table1.meta)
hdu_list.append(fits.BinTableHDU(data=data, header=header))

data = table2.as_array()
header = fits.Header()
header.update(table1.meta)
hdu_list.append(fits.BinTableHDU(data=data, header=header))
```

Is there a way to store a `Table` in FITS, but avoid the copy that `as_array` is doing?
(that's the performance issue I have, one of my tables is several GB in size.)

Is there a simpler way to convert `table.meta` to a `header`? I was looking through the convenience functions / methods in `fits` and `table`, but couldn't find something. There should be way to make a header from a dict in one line, if not directly in the `BinTableHDU` constructor, no?

**Comment by embray** [comment]
Since the main issue here seems to be to extend the `io.fits`-`Table` connector to allow saving multiple tables, maybe this question would be best addressed in the mailing list or a different issue since it's straying off-topic (I get how it's related to this issue, but I don't want things to get too noisy).

**Comment by taldcroft** [comment]
Sorry to continue the OT question, but just wondering if it you can avoid the memory duplication using the direct FITS table creation interface described at  http://astropy.readthedocs.org/en/latest/io/fits/index.html#creating-a-new-table-file.

In other words if you assemble the `fits.Column` objects from the individual table `Column` objects, does that avoid the copy?  I think that in using the higher-level `fits.BinTableHDU` interface there is no way around creating a copy of all the individual data columns because that routine needs a numpy array (as far as I can tell).

**Comment by embray** [comment]
@taldcroft has the gist of it.  It would be pretty nice if the `from_columns` method worked on `astropy.table.Column` objects too.

**Comment by embray** [comment]
Though it still ends up making a copy, because it has to create a record array to then stuff all the column data into.  But I think this way might result in one fewer copy?  Not sure...

**Comment by stvguest** [comment]
I'm looking at this as part of the SKA/astropy hackathon. I agree with the suggestion to add an append flag that can be used from the table interface. It is indeed straightforward to add it to write_table_fits. Using the append function, performance is similar to writing the same file multiple times:

timeit.timeit(append, number=100)
6.515496399999961
timeit.timeit(write, number=100)
5.795052499999997
