### ISSUE TITLE
allow automodapi to document individual items

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#265]
This was discussed in #219 as item 3.  From @mdboom:

I want to document some classes that aren't listed in the module's `__all__` but are returned from functions in that module. It's helpful to know how the class works, but instantiating the class is a private implementation detail. Having a way of listing additional module members might do the trick. They wouldn't have to be displayed in a separate list. This is a pretty low-priority concern relative to the others. In the end, I've just added the class to `__all__` as a workaround for now.

This could be implemented as an option to automodapi, but the catch is that we want a way to make it apparent that the item is _not_ a public item that is importable. It's not clear what the best way is to do this, though...

**Comment by bsipocz** [comment]
I think this issue should be moved upstream to sphinx-automodapi, isn't it?

**Comment by pllim** [comment]
FWIW there is already a way to do that in Sphinx -- https://stackoverflow.com/questions/1149280/how-can-i-use-sphinx-autodoc-extension-for-private-methods

**Comment by bsipocz** [comment]
@pllim - Wow, that's great. Then I go ahead and closed this here.
