### ISSUE TITLE
Implement coordinates.allclose to find coordinates that are not strictly equal

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2650]
As suggested by @taldcroft in https://github.com/astropy/astropy/issues/2154 it would be nice to have a way to check that two sets of coordinates are essentially the same even if they are not exactly the same to machine precision.

**Comment by adrn** [comment]
This is simple to write with existing functions:
```python
import astropy.units as u
u.allclose(c1.separation(c2), 0*u.deg)
```
so I'm going to close this, but feel free to reopen if you disagree!
