### ISSUE TITLE
ProgressBar makes for huge ipynbs

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#2658]
The progressbar is useful in ipython notebooks, but it can really fill them up with json junk.  I have a workaround-style solution:
https://gist.github.com/keflavich/467b65b5fae7f20d97eb
but there is probably a better way to avoid repeated `'\r'` strings being dumped into the notebook file (they're not visible anyway).

If there's a better way to do this already in place, e.g. by using a different progressbar than `astropy.utils.console.ProgressBar`, then this may just be a documentation issue.

**Comment by astrofrog** [comment]
@keflavich - closing this since we now have the widget version of the progress bar
