### ISSUE TITLE
Add sphinx directive to use +FLOAT_CMP on a block of doctests

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2662]
#2087 added support for a doctest flag `FLOAT_CMP` to parse out and compare floating point values as actual floats.

One thing I found in the course of implementing this is that, while `FLOAT_CMP` should be disabled by default, it is sometimes useful to enable it for a while block of doctests at once.

We've already added a Sphinx directive for marking a whole block of doctests for skipping.  What we might consider is extended the existing directive to support setting arbitrary doctest flags.  Perhaps a `doctest-flags` directive :) 

This would require some cooperation with astropy-helpers as well since that's where the actual Sphinx directives live.

**Comment by bsipocz** [comment]
This has been added as a feature request for `pytest-doctestplus` in https://github.com/astropy/pytest-doctestplus/issues/3, along with a similar directive for `REMOTE_DATA` in https://github.com/astropy/pytest-doctestplus/issues/2.
