### ISSUE TITLE
SLSQPLSQFitter can lead to terrible fits

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2670]
In the course of tweaking some of the modeling tests I found that with _some_ random inputs the `SLSQPLSQFitter` just went off the reservation when fitting to a Gaussian.  The specific test where this was occurring is: https://github.com/astropy/astropy/blob/db9181eeaaa704d17d922476bb7db8d2dbb37bbe/astropy/modeling/tests/test_fitters.py#L274

The arguments that end up being passed to `fmin_slsqp` seemed fine, but the optimizer ends up returning completely off results.  This only happens for some data though. If I change the random seed, for example, I can get a reasonable fit for different random data.  I was also able to work around the problem for now by simply lowering the width of the distribution being drawn from for now.

This might just be an unavoidable failure of the algorithm itself with nothing to be done. But it's so off that it might also be worth investigating.  I tagged this "Upstream Fix Required" since the issue is likely in SciPy code and not Astropy itself.

(Note: This specifically happens with the random seed is `0x1337` and `np.random.normal(0., 8.)` is used.)

**Comment by karllark** [comment]
I think this is fundamental to how fitters (e.g., optimizers work).  When it comes to automated tests, I think the random seed should be fixed so that failures like this are not possible for the automated tests.

**Comment by pllim** [comment]
I thought we fix the seed in all our tests. Is that not true? If seed is fixed already on `master`, should we close this as "won't fix"?

**Comment by karllark** [comment]
If the seed is fixed, then this issue should be closed (marked as won't fix I understand).

**Comment by pllim** [comment]
The seed is fixed here:

https://github.com/astropy/astropy/blob/d87093464ff7912d719bfa4fbd5d0d44742ee1fc/astropy/modeling/tests/test_fitters.py#L370-L371

Closing then. Thanks!
