### ISSUE TITLE
Bug in doctest

### ISSUE THREAD

**Issue by dklaes** [astropy/astropy#2733]
If a certain part of the doc requires e.g. matplotlib, some of the doctest fail. To prevent that, one adds the line ``.. doctest-requires:: matplotlib`` before that piece of code. If between this line and the code itself (e.g. ``import matplotlib.pylab as lab``) is *no* empty line, then only an empty code box appears.

This doesn't work:
<pre><code>.. doctest-requires:: matplotlib
    import matplotlib.pylab as lab</code></pre>

This works:
<pre><code>.. doctest-requires:: matplotlib

    import matplotlib.pylab as lab</code></pre>
    

Just found out at the SciPy Sprint with @embray .

**Comment by souravsingh** [comment]
I think the issue is fixed.

**Comment by embray** [comment]
This issue might just be particular to some Sphinx version.  I haven't confirmed either way.

**Comment by algerdnazgul** [comment]
In any way - we can close this issue as fixed. Only 2 files now has such instructions "doctest-requires:: matplotlib" and all of them with space between lines

**Comment by astrofrog** [comment]
@algerdnazgul - thanks for confirming!
