### ISSUE TITLE
Boolean Table indexing with list has unexpected behaviour

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#2752]
I just tripped over this behaviour of `Table`:
```
>>> import numpy as np
>>> from astropy.table import Table
>>> arr = np.arange(15).reshape(5, 3)
>>> t = Table(arr, names=('a', 'b', 'c'), meta={'keywords': {'key1': 'val1'}})
>>> print(t)
 a   b   c 
--- --- ---
  0   1   2
  3   4   5
  6   7   8
  9  10  11
 12  13  14
>>> mask = [_ not in [3, 9] for _ in t['a']]
>>> mask
[True, False, True, False, True]
>>> print(t[mask]) # this is what I did ... not the result I want
 a   b   c 
--- --- ---
  3   4   5
  0   1   2
  3   4   5
  0   1   2
  3   4   5
>>> print(t[np.array(mask)]) # this is what I wanted
 a   b   c 
--- --- ---
  0   1   2
  6   7   8
 12  13  14
```
Apparently `Table` converts the list of booleans to an array of integers and performs integer indexing, whereas for a numpy array of booleans it performs boolean indexing.

I think this is very error-prone and propose to change the behaviour to perform boolean indexing if the user passes a list of bools.

Also, boolean indexing is not documented at all in the docs as far as I can see (see [here](http://astropy.readthedocs.org/en/latest/table/access_table.html)), should I file a separate issue for that?

cc @taldcroft

**Comment by sunilk747** [comment]
Hello,
I am  new to astropy . I go through the documentation and got a brief idea of it.Now I am thinking of working on this issue.Kindly suggest me how to start.

**Comment by taldcroft** [comment]
@sunilk747 - sounds great.  Please start by reading http://www.astropy.org/contribute.html.  You'll want to follow and understand the relevant links in the "Contribute code or documentation" section.

**Comment by sunilk747** [comment]
I would like to know what does this statement do:-
` 
     descrs = (descr(col) for col in cols
 `
And I go through the `class Row` and `class Table`  .I want to know, are these two classes has something to do with the above issue.If I am wrong please help me a little to get on the right track.

**Comment by embray** [comment]
@sunilk747 In GitHub you can link to a specific line of code in a file but just opening that file in the source browser in GitHub and clicking directly on the line number to the left of that line. Then you can copy the URL for that.  That's much better than just quoting some line of code without even mentioning what file it's in.

**Comment by sunilk747** [comment]
@embray Thanks for your suggestion.As I am new to github and opensource ,I don't have much knowledge of it.I am still learning.I will take care of these things in further comments.

**Comment by bsipocz** [comment]
@taldcroft @mdmueller - Just run into this problem today, and wondering whether this is would be an easy fix by #3915?  At the moment it looks like it doesn't fix it, but given that that is a supermassive PR I'm  hesitating whether it worth to try to find a fix before 1.1 freezes and that one isn't merged.

**Comment by taldcroft** [comment]
@bsipocz - this fell off my radar.  This is an upstream problem in numpy that will be fixed:
```
In [1]: a = np.arange(5)

In [2]: a[[False, True, False, True, False]]
/Users/aldcroft/anaconda/bin/ipython:1: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  #!/bin/bash /Users/aldcroft/anaconda/bin/python.app
Out[2]: array([0, 1, 0, 1, 0])
```

@cdeil - can this be closed?

**Comment by embray** [comment]
Ah, this is about Numpy treating bool arrays and lists of bools equivalently.  I'm glad they're fixing that--I get caught on that sometimes too.
