### ISSUE TITLE
0.4: test_compose_fractional_powers failure on debian/kfreebsd-i386

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#2765]
On Debian/kfreebsd-i386, I just git the following:
```

    def test_compose_fractional_powers():
        x = (u.kg / u.s ** 3 * u.au ** 2.5 / u.yr ** 0.5 / u.sr ** 2)
    
        factored = x.compose()
    
        for unit in factored:
>           assert x.decompose() == unit.decompose()
E           assert Unit("1.54085e+24 kg m(5/2) / (rad4 s(7/2))") == Unit("3.68726e+41 A2 / (rad4 s(5/2))")
E            +  where Unit("1.54085e+24 kg m(5/2) / (rad4 s(7/2))") = <bound method CompositeUnit.decompose of Unit("AU(5/2) kg / (s3 sr2 yr(1/2))")>()
E            +    where <bound method CompositeUnit.decompose of Unit("AU(5/2) kg / (s3 sr2 yr(1/2))")> = Unit("AU(5/2) kg / (s3 sr2 yr(1/2))").decompose
E            +  and   Unit("3.68726e+41 A2 / (rad4 s(5/2))") = <bound method CompositeUnit.decompose of Unit("1.6915e+59 Ry S / (rad4 s(7/2))")>()
E            +    where <bound method CompositeUnit.decompose of Unit("1.6915e+59 Ry S / (rad4 s(7/2))")> = Unit("1.6915e+59 Ry S / (rad4 s(7/2))").decompose

astropy/units/tests/test_units.py:391: AssertionError
```
 * [log file](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=kfreebsd-i386&ver=0.4-3&stamp=1405700993)

This is, however, non-reproducible: It didn't appear on the first two builds on this machine, and it also didn't happen on the RC builds. Since there was also another failure on this platform (test script [died while `astropy/io/votable/tests/vo_test.py:311:` `TestThroughBinary2.test_string_test`](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=kfreebsd-i386&ver=0.4-1&stamp=1405580041)), the build server may have a problem, and not astropy. So, this report may be more for the records :-)

**Comment by astrofrog** [comment]
@olebole - is this still an issue?

**Comment by olebole** [comment]
It seems to work now; at least I didn't get this anymore since I reported here. We could probably close it as "unreproducible".
