### ISSUE TITLE
Run landscape.io analysis for Astropy?

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#2770]
Should we add an [landscape.io](https://landscape.io/) analysis and badge to the README for Astropy? It only takes a few minutes to set up.

I've done this for `Gammapy` and the report is actually pretty useful ... it even detects some broken code that is currently not covered by unit tests through static analysis.
Probably it will be less useful for Astropy where the coverage is very good and the code quality very high, but maybe this could be useful for some affiliated packages.

As an example see the "Health" badge in the [Gammapy README](https://github.com/gammapy/gammapy#gammapy) and click on it to see the report.

**Comment by astrofrog** [comment]
The @landscape-bot started spamming all Astropy PRs yesterday so for now I've just revoked access to the landscape-io bot for the repository, since they have no obvious way of disabling the bot or even removing a package from their service. Hopefully that will be enough to stop it.

**Comment by embray** [comment]
Seems like it might be interesting, but right now isn't configured in such a way as to be totally useful...

**Comment by mdboom** [comment]
@astrofrog Thanks for noticing the spamming and fixing -- I was just about to report that myself.

It also seems that the results are not very accurate -- it reports things as "new" on a PR vs. master that have nothing to do with the PR (haven't figured out yet).

**Comment by astrofrog** [comment]
@mdboom - even on landscape.io the results for astropy change from build to build so I think the fact the results are incorrect are due to that.

**Comment by embray** [comment]
I think it might be worth re-enabling until/whenever someone goes through and disables all the lint checks that are false-positives :)

**Comment by astrofrog** [comment]
@embray - the analysis still works on the website: https://landscape.io/github/astropy/astropy and once that is stable, we can chose to re-enable the bot if we like.

**Comment by cdeil** [comment]
Telling pylint to ignore a ton of fake errors generated because numpy and astropy dynamically populate modules on import isn't hard, but it will probably also remove detections of real issues.

It looks like it's non-trivial, but possible to teach pylint to actually use the dynamically populated modules in it's static (well, not so static any more) code analysis:
http://blog.devork.be/2014/12/pylint-and-dynamically-populated.html

**Comment by bsipocz** [comment]
Quite a lot happened since, and even gammapy seems to stopped using landscape.io, so I suggest to close this issue. There are a few other QA apps on github marketplace, we may consider to opt in one of those (and/or make our flake8 testing more strict as the first step...).

Feel free to reopen if you disagree.
