### ISSUE TITLE
Development workflow guidelines for affiliated packages.

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#2780]
There don't appear to be any explicit development workflow guidelines for affiliated packages, so I guess the default is to follow astropy's own development workflow guidelines.

The first item of http://docs.astropy.org/en/stable/development/workflow/development_workflow.html#astropy-guidelines-for-git says "Don’t use your master branch for anything."  Similar things are said elsewhere in that document.

This could be interpreted overly strictly, & might even make one consider deleting the master branch (I believe this was actually said in earlier versions of this document).  However, I have encountered other developers who are of the opinion that `master` is the main, active development branch in the Subversion `trunk` sense.  This situation should be clarified.

**Comment by weaverba137** [comment]
Is there a reason this is still open?  I can't recall now if I ever submitted a PR as promised.

**Comment by bsipocz** [comment]
Astropy coordinated packages follow the astropy core development guides, the affiliated packages however can set their own workflow, so closing this issue.
