### ISSUE TITLE
Document the branches in the main astropy repository.

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#2781]
Currently there are these branches in the main astropy repository: master, stable, v0.1.x, v0.2.x, v0.3.x, v0.4.x. Besides master, it is not obvious what these branches are used for.

**Comment by adrn** [comment]
@weaverba137 Cleaning up old issues...

Do you still think this is needed?

**Comment by weaverba137** [comment]
I think the documentation described already in this discussion is sufficient, so go ahead & close.

**Comment by MSeifert04** [comment]
I think one could clean up some branches though. There are lots of branches that won't receive backports and if one ever wanted to install an old version there are tags for each release?!

**Comment by adrn** [comment]
That's a new issue!
