### ISSUE TITLE
astropy Table to pandas DataFrame

### ISSUE THREAD

**Issue by mattgiguere** [astropy/astropy#2804]
Is it possible to convert an astropy Table to a pandas DataFrame and vise versa? It would be nice to make use of the features of both tools (e.g., the pandas read_sql/write_sql methods). @eteq

**Comment by Malewhaler** [comment]
> @taldcroft - this may be sort of a bug in pandas, but note the following:
> 
> ```
> >>> f = pandas.DataFrame(randn(100,2),columns=['a','b'])
> >>> t = astropy.table.Table(np.array(f))
> >>> t.colnames
>  ['col0', 'col1']
> ```
> 
> It looks like `array` doesn't correctly convert a `DataFrame` to a numpy structured array... But the other way does work:
> 
> ```
> >>> t = astropy.table.Table(data=randn(100,2),names=['a','b'])
> >>> f = pandas.DataFrame(np.array(t))
> >>> f.columns
> Index([u'a', u'b'], dtype='object')
> ```
> 
> So you can do `astropy` -> `pandas` easily, but not vice-versa... so perhaps a reason to at least accept it in the `Table` initializer.

A way from DataFrame to Table:
t=astropy.table.Table(f.values,names=f.columns)

**Comment by taldcroft** [comment]
> A way from DataFrame to Table:
> t=astropy.table.Table(f.values,names=f.columns)

@Malewhaler - the preferred way from DataFrame to Table is below, which has some options and deals with a few subtleties.
```
t = astropy.table.Table.from_pandas(f)
```
