### ISSUE TITLE
Doctests: --remote-data for .rst files?

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#2830]
http://astropy.readthedocs.org/en/latest/development/testguide.html#skipping-doctests documents how to:
1. Mark tests as remote inline: `# doctest: +REMOTE_DATA`
2. Skip tests within .rst docs: `.. doctest-skip::`, `.. doctest-skip-all`

Is there a way to mark `.. doctest-remote` or `.. doctest-remote-all`?  I think it should be straightforward to add such a thing, but I don't know exactly how to write a new directive.

**Comment by pllim** [comment]
We have this now, right? Can we close this?

**Comment by bsipocz** [comment]
@pllim - I think this issue was never addressed, and we still don't have  a way to flag a block of doctest either with "REMOTE_DATA" or with "FLOAT_CMP".

**Comment by bsipocz** [comment]
This is now upstream in `pytest-doctestplus`, so closing it here. Nevertheless one can see the status in  https://github.com/astropy/pytest-doctestplus/issues/2.
