### ISSUE TITLE
The gnomonic projection of right ascension and declination

### ISSUE THREAD

**Issue by neuronphysics** [astropy/astropy#2847]
Does astropy have a function or library that compute the gnomonic projection of right ascension and declination? Also another function that the inputs would be right ascension and declination and shear of the galaxy (shape distortion) and the output the tangential and cross components of the shear after gnomonic projection?

**Comment by bsesar** [comment]
@astrofrog - what @neuronphysics  probably has in mind is something similar to this function in the STARLINK library

http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?ds2tp.hlp

If there is a function like that in astropy, please let me know :)

Cheers,

Brani

**Comment by astrofrog** [comment]
@neuronphysics @bsesar - the WCS standard describes how we can project world to pixel coordinates assuming various spherical projections, and this is implemented in [astropy.wcs](http://docs.astropy.org/en/stable/wcs/index.html). Here is an example of how one might set up a gnomonic projection (TAN) in Astropy:

```
from astropy.wcs import WCS

wcs = WCS(naxis=2)
wcs.wcs.crpix = [0., 0.]
wcs.wcs.cdelt = [1./3600., 1./3600.]
wcs.wcs.crval = [23.2334, 45.2333]
wcs.wcs.ctype = ["RA---TAN", "DEC--TAN"]
```

The CRPIX, CDELT, CRVAL and CTYPE keywords are standard WCS and are typically found in FITS headers (but here we can create the projection without having to deal with FITS files). You can watch the first five minutes of [this video](https://www.youtube.com/watch?v=ukR5a2TJJt4) for an explanation of what these keywords mean.

Basically the above will allow you to convert world coordinates (RA/Dec in this case) to pixel coordinates, and it is assuming that the projection is centered at 23.2334, 45.2333. The pixel scale is 1"/pixel, and a value of (0,0) in pixel coordinates is centered at 23.2334, 45.2333.

So to convert to pixel coordinates, we can then do e.g.

```
xp, yp = wcs.wcs_world2pix(23.32, 45.222, 0)
```

which gives

```
218.54858187451694 -1.2422010456774355
```

These are pixel values. However, note that we set the pixel scale to 1"/pixel so these are equivalent to arcsecond offset values too. If you wanted the output values in degrees offset you could instead do

```
wcs.wcs.cdelt = [1., 1.]
```

Does this all make sense and address your first question?

For the galaxy shear, I'm not sure if I understand the question correctly - can you clarify?

**Comment by mdboom** [comment]
To add to @astropy's response, `astropy.modeling` also has some transformations that may be relevant.  You'd have to chain them together yourself, but on the other hand you don't have to build FITS headers to initialize it if that's not where you're starting from.

**Comment by adrn** [comment]
Closing this because it is several years old.

@neuronphysics Please re-open this issue or create a new one if it is still relevant. Thanks!
