### ISSUE TITLE
More explicit error if table is sliced with empty iterator

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2856]
In the following example the error that occurs when slicing the table with an empty iterator is pretty obscure:

```
In[ 11]: from astropy.table import Table

In [12]: t = Table()

In [13]: t['a'] = [1,2,3]

In [14]: t[[1,2]]
Out[14]: 
<Table rows=2 names=('a')>
array([(2,), (3,)], 
      dtype=[('a', '<i8')])

In [15]: t[[1]]
Out[15]: 
<Table rows=1 names=('a')>
array([(2,)], 
      dtype=[('a', '<i8')])

In [16]: t[[]]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-7e9394d22394> in <module>()
----> 1 t[[]]

/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9620-py3.4-macosx-10.8-x86_64.egg/astropy/table/table.py in __getitem__(self, item)
    891                 raise ValueError('Slice name(s) {0} not valid column name(s)'
    892                                  .format(', '.join(bad_names)))
--> 893             out = self.__class__([self[x] for x in item], meta=deepcopy(self.meta))
    894             out._groups = groups.TableGroups(out, indices=self.groups._indices,
    895                                              keys=self.groups._keys)

/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9620-py3.4-macosx-10.8-x86_64.egg/astropy/table/table.py in __init__(self, data, masked, names, dtype, meta, copy, rows)
    380 
    381         # Finally do the real initialization
--> 382         init_func(data, names, dtype, n_cols, copy)
    383 
    384         # Whatever happens above, the masked property should be set to a boolean

/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9620-py3.4-macosx-10.8-x86_64.egg/astropy/table/table.py in _init_from_list(self, data, names, dtype, n_cols, copy)
    542             cols.append(col)
    543 
--> 544         self._init_from_cols(cols)
    545 
    546     def _init_from_ndarray(self, data, names, dtype, n_cols, copy):

/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9620-py3.4-macosx-10.8-x86_64.egg/astropy/table/table.py in _init_from_cols(self, cols)
    605         if len(lengths) != 1:
    606             raise ValueError('Inconsistent data column lengths: {0}'
--> 607                              .format(lengths))
    608 
    609         self._set_masked_from_cols(cols)

ValueError: Inconsistent data column lengths: set()
```

I originally was going to suggest that this should return an empty table, but I guess that we can't do this since we rely on the content of the iterator to determine if the user is slicing on rows or columns, right? In that case, it would be good to at least have a more explicit error message.

**Comment by sunilk747** [comment]
@astrofrog I want to work upon this issue.I see some error message's like this [```raise ValueError('Cannot supply both `data` and `rows` values')```](https://github.com/sunilk747/astropy/blob/master/astropy/table/table.py#L218)

and some messages like this [```if len(names) != n_cols or len(dtype) != n_cols:
            raise ValueError(
                'Arguments "names" and "dtype" must match number of columns'
                .format(inp_str))```](https://github.com/sunilk747/astropy/blob/master/astropy/table/table.py#L375).
I want to know the use of ```.format()``` in the above error message.

**Comment by embray** [comment]
On [L375](https://github.com/sunilk747/astropy/blob/master/astropy/table/table.py#L375) that looks like a bug in of itself since it's passing the input string to the error format, but not actually using it in the error message.

**Comment by embray** [comment]
Now that I look at this again, I wonder if slicing a table with an empty list shouldn't just return an empty table.  That's what happens with, say, an ndarray.  Likewise with pandas--indexing a `DataFrame` like `df[[]]` returns an empty `DataFrame` with no columns.  I think that would seem sensible for `Table` too, but I don't know if there was a conscious decision on that...

**Comment by embray** [comment]
@astrofrog 
> we rely on the content of the iterator to determine if the user is slicing on rows or columns, right?

Could you clarify on that?  ISTM it should be possible to still catch a `StopIteration` after the first `next()` on the iterator and somehow return an empty table as a default.

**Comment by embray** [comment]
Oh, I think I see what you're saying--it's not clear whether to return a `Table` with no columns, or a `Table` with the same columns as the original, but no rows?

Hmm, yes.  That is tricky.  I think I'd lean toward just a `Table` with no rows or columns.  In any of those cases `bool(table) is False`--I think code that checks if a the result of a slice is empty (whether there are columns defined or not) should rely on `bool(table)` and not, say, `len(table.columns)` or something...

**Comment by taldcroft** [comment]
I guess I would lean toward a table with no rows but the original columns.

While it's true that you can select columns with a list or tuple, I sort of think of this as a secondary function to selecting rows.  I.e. if I had to choose only one for the API it would definitely be rows.

Maybe another way to think about it is functionality.  If you have `[]` selecting columns, then that is very nearly equivalent to just returning a `Table()` which has no relation to the original.  However, if `[]` is selecting rows, then the returned table has all the original column names and meta.  It would be slightly tricky for a user to generate such a zero-length equivalent table *without* using this empty slice method.  (I know how to do this, but I bet half the users couldn't figure it out quickly).

**Comment by embray** [comment]
That's a good point.  It's a nice way to create a copy of the original table but with no row data.  You lose less information that way, but still also get `bool(table) == False`.

**Comment by taldcroft** [comment]
It sounds like we are converging on something even more useful than a better error message.  Now what about `table[()]`.  Numpy has the interesting convention of returning everything:
```
In [1]: a = np.arange(5)

In [2]: a[()]
Out[2]: array([0, 1, 2, 3, 4])

In [3]: a[[]]
Out[3]: array([], dtype=int64)
```

**Comment by embray** [comment]
Not sure how I feel about that.  I think that's odd and possibly not even right.
Pandas doesn't even allow `dataframe[()]`.  It results in a KeyError.  But I don't think that's right either.  I don't see why slicing with a list or a tuple should ever be different (I can dream up schemes where depending on what type of collection you're using different indexing operations are performed, but I think such schemes are ultimately confusing...)
