### ISSUE TITLE
memory allocation segfault in read_asciitable

### ISSUE THREAD

**Issue by ChrisBeaumont** [astropy/astropy#2877]
The following script inconsistently throws segfaults when using the file https://www.dropbox.com/s/546pjh6i6q66iuk/test.csv

```
from astropy import __version__
print __version__
from astropy.io.ascii.connect import read_asciitable

read_asciitable('test.csv')
```

(whether or not it actually throws a segfault seems to depend on how much memory I'm using elsewhere on  my system). 

One crash report reads:

```
Process:         python [58553]
Path:            /Users/USER/*/python.app/Contents/MacOS/python
Identifier:      com.continuum.python
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  bash [58409]
User ID:         501

Date/Time:       2014-08-20 13:57:06.928 -0400
OS Version:      Mac OS X 10.8.5 (12F45)
Report Version:  10

Interval Since Last Report:          78082 sec
Crashes Since Last Report:           12
Per-App Crashes Since Last Report:   12
Anonymous UUID:                      9F0D1600-F5A2-ABFF-0692-767B75E42AA8

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000114e89000

VM Regions Near 0x114e89000:
    MALLOC_LARGE           0000000114e68000-0000000114e89000 [  132K] rw-/rwx SM=COW  
--> 
    MALLOC_LARGE           0000000114e8c000-0000000114f0c000 [  512K] rw-/rwx SM=PRV  
```

For context, the catalog is 2M rows x 7 columns, 100MB in plaintext, and my machine has 16GB of RAM. Pandas loads the data without problem. Because of this, I suspect that read_asciitable is somewhere allocating an array much larger than it needs to.

**Comment by bsipocz** [comment]
I'm closing this as https://github.com/astropy/astropy/issues/2881 seems to be the perfect follow-up issue to track things not yet addressed here.
