### ISSUE TITLE
Document common recommended editor settings

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2903]
The introduction of the PEP8 tests on Travis has caused a number of new contributors' PRs to fail testing.  Perhaps the most common issues being whitespace related.

I'm OKAY with that because I think it's better than the alternative (PRs filled with pointless whitespace changes).  But I think we should document, or at least link to, some instructions for how contributors should configure their editors, for as many different common editors as people wish to contribute docs for.

This should all be common-sense stuff for Python _in general_--nothing specific to Astropy.  For example, tabs should insert 4 spaces, no exception.  Also instructions for how to automatically strip trailing whitespace from the ends of lines.  Things like that.

**Comment by astrofrog** [comment]
I'm going to close this as we already provide guidelines for emacs and I don't think we want to get in the business of keeping up with all the latest and greatest editors... We now have some basic PEP8 checks in CI.

**Comment by mhvk** [comment]
Agreed with closing this question about editor settings. But should there be a type of "autopep" cleaning done (the whitespace related ones should be quite amenable to automation).
