### ISSUE TITLE
test_web_profile fails with firewall enabled

### ISSUE THREAD

**Issue by sergiopasra** [astropy/astropy#2915]
Not sure which rule of my work machine's firewall makes the test to fail. What is true is that after stopping the firewall the test passes. My system is Linux Fedora 20

Failure log here: http://guaix.fis.ucm.es/~spr/github/astropy041-firewall.txt

**Comment by bsipocz** [comment]
@sergiopasra - Do you still get the failure, or can we close this?

**Comment by sergiopasra** [comment]
@bsipocz let me chek this...

**Comment by sergiopasra** [comment]
Yes, I'm still getting errors with VO web profiles

py.test-2.7 -k '(test_web_profile or TestStandardProfileHTTPSHub or TestStandardProfileHTTPSHubClient)' astropy

============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0

Running tests with Astropy version 1.3.
Running tests in astropy.

Date: 2017-02-20T12:47:44

Platform: Linux-4.9.7-201.fc25.x86_64-x86_64-with-fedora-26-Rawhide

Executable: /usr/bin/python2

Full Python Version: 
2.7.13 (default, Jan 12 2017, 18:46:28) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

encodings: sys: ascii, locale: ANSI_X3.4-1968, filesystem: ANSI_X3.4-1968, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.12.0
Scipy: 0.18.0
Matplotlib: 2.0.0
h5py: 2.6.0
Pandas: 0.19.2
Cython: 0.25.2
Using Astropy options: remote_data.

rootdir: /builddir/build/BUILDROOT/python-astropy-1.3-2.fc26.x86_64/usr/lib64/python2.7/site-packages, inifile: 
collected 11682 items

astropy/vo/samp/tests/test_standard_profile.py EE
astropy/vo/samp/tests/test_web_profile.py F.

==================================== ERRORS ====================================
___________ ERROR at setup of TestStandardProfileHTTPSHub.test_main ____________

self = <astropy.vo.samp.tests.test_standard_profile.TestStandardProfileHTTPSHub object at 0x7f5d7f8ba590>
method = <bound method TestStandardProfileHTTPSHub.test_main of <astropy.vo.samp.tests.test_standard_profile.TestStandardProfileHTTPSHub object at 0x7f5d7f8ba590>>

    def setup_method(self, method):
    
        self.tmpdir = tempfile.mkdtemp()
    
        self.hub = SAMPHubServer(web_profile=False, mode='multiple', pool_size=1,
                                 **self.hub_init_kwargs)
        self.hub.start()
    
        self.client1 = SAMPIntegratedClient(**self.client_init_kwargs)
>       self.client1.connect(hub=self.hub, pool_size=1, **self.client_connect_kwargs)

astropy/vo/samp/tests/test_standard_profile.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/vo/samp/integrated_client.py:184: in connect
    cert_reqs, ca_certs, ssl_version, pool_size)
astropy/vo/samp/hub_proxy.py:128: in connect
    self.ping()
astropy/vo/samp/hub_proxy.py:165: in ping
    return self._samp_hub.ping()
astropy/vo/samp/utils.py:65: in __call__
    response = function(*args, **kwrds)
/usr/lib64/python2.7/xmlrpclib.py:1243: in __call__
    return self.__send(self.__name, args)
/usr/lib64/python2.7/xmlrpclib.py:1602: in __request
    verbose=self.__verbose
/usr/lib64/python2.7/xmlrpclib.py:1283: in request
    return self.single_request(host, handler, request_body, verbose)
/usr/lib64/python2.7/xmlrpclib.py:1311: in single_request
    self.send_content(h, request_body)
/usr/lib64/python2.7/xmlrpclib.py:1459: in send_content
    connection.endheaders(request_body)
/usr/lib64/python2.7/httplib.py:1038: in endheaders
    self._send_output(message_body)
/usr/lib64/python2.7/httplib.py:882: in _send_output
    self.send(msg)
/usr/lib64/python2.7/httplib.py:844: in send
    self.connect()
astropy/vo/samp/ssl_utils.py:62: in connect
    sslconn = ssl.wrap_socket(sock, **kwargs)
/usr/lib64/python2.7/ssl.py:943: in wrap_socket
    ciphers=ciphers)
/usr/lib64/python2.7/ssl.py:611: in __init__
    self.do_handshake()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket object at 0x7f5d7f1a9140>, block = False

    def do_handshake(self, block=False):
        """Perform a TLS/SSL handshake."""
        self._check_connected()
        timeout = self.gettimeout()
        try:
            if timeout == 0.0 and block:
                self.settimeout(None)
>           self._sslobj.do_handshake()
E           error: [Errno 104] Connection reset by peer

/usr/lib64/python2.7/ssl.py:840: error
---------------------------- Captured stdout setup -----------------------------
INFO: Hub set for using SSL. [astropy.vo.samp.hub]
INFO: Hub started [astropy.vo.samp.hub]
________ ERROR at setup of TestStandardProfileHTTPSHubClient.test_main _________

self = <astropy.vo.samp.tests.test_standard_profile.TestStandardProfileHTTPSHubClient object at 0x7f5d823fc2d0>
method = <bound method TestStandardProfileHTTPSHubClient.test_main of <astropy.vo.samp....t_standard_profile.TestStandardProfileHTTPSHubClient object at 0x7f5d823fc2d0>>

    def setup_method(self, method):
    
        self.tmpdir = tempfile.mkdtemp()
    
        self.hub = SAMPHubServer(web_profile=False, mode='multiple', pool_size=1,
                                 **self.hub_init_kwargs)
        self.hub.start()
    
        self.client1 = SAMPIntegratedClient(**self.client_init_kwargs)
>       self.client1.connect(hub=self.hub, pool_size=1, **self.client_connect_kwargs)

astropy/vo/samp/tests/test_standard_profile.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/vo/samp/integrated_client.py:184: in connect
    cert_reqs, ca_certs, ssl_version, pool_size)
astropy/vo/samp/hub_proxy.py:128: in connect
    self.ping()
astropy/vo/samp/hub_proxy.py:165: in ping
    return self._samp_hub.ping()
astropy/vo/samp/utils.py:65: in __call__
    response = function(*args, **kwrds)
/usr/lib64/python2.7/xmlrpclib.py:1243: in __call__
    return self.__send(self.__name, args)
/usr/lib64/python2.7/xmlrpclib.py:1602: in __request
    verbose=self.__verbose
/usr/lib64/python2.7/xmlrpclib.py:1283: in request
    return self.single_request(host, handler, request_body, verbose)
/usr/lib64/python2.7/xmlrpclib.py:1311: in single_request
    self.send_content(h, request_body)
/usr/lib64/python2.7/xmlrpclib.py:1459: in send_content
    connection.endheaders(request_body)
/usr/lib64/python2.7/httplib.py:1038: in endheaders
    self._send_output(message_body)
/usr/lib64/python2.7/httplib.py:882: in _send_output
    self.send(msg)
/usr/lib64/python2.7/httplib.py:844: in send
    self.connect()
astropy/vo/samp/ssl_utils.py:62: in connect
    sslconn = ssl.wrap_socket(sock, **kwargs)
/usr/lib64/python2.7/ssl.py:943: in wrap_socket
    ciphers=ciphers)
/usr/lib64/python2.7/ssl.py:611: in __init__
    self.do_handshake()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket object at 0x7f5d7f395398>, block = False

    def do_handshake(self, block=False):
        """Perform a TLS/SSL handshake."""
        self._check_connected()
        timeout = self.gettimeout()
        try:
            if timeout == 0.0 and block:
                self.settimeout(None)
>           self._sslobj.do_handshake()
E           error: [Errno 104] Connection reset by peer

/usr/lib64/python2.7/ssl.py:840: error
---------------------------- Captured stdout setup -----------------------------
INFO: Hub set for using SSL. [astropy.vo.samp.hub]
INFO: Hub started [astropy.vo.samp.hub]
=================================== FAILURES ===================================
___________________________ TestWebProfile.test_main ___________________________

self = <astropy.vo.samp.tests.test_web_profile.TestWebProfile object at 0x7f5d821c1e90>

    def test_main(self):
    
        self.client1_id = self.client1.get_public_id()
        self.client2_id = self.client2.get_public_id()
    
        self.metadata1 = {"samp.name": "Client 1",
                          "samp.description.text": "Client 1 Description",
                          "client.version": "1.1"}
    
        self.metadata2 = {"samp.name": "Client 2",
                          "samp.description.text": "Client 2 Description",
                          "client.version": "1.2"}
    
        # Check that the clients are connected
    
        assert self.client1.is_connected
        assert self.client2.is_connected
    
        # Check that ping works
    
        self.client1.ping()
        self.client2.ping()
    
        # Check that get_registered_clients works as expected.
    
        assert self.client1_id not in self.client1.get_registered_clients()
        assert self.client2_id in self.client1.get_registered_clients()
        assert self.client1_id in self.client2.get_registered_clients()
        assert self.client2_id not in self.client2.get_registered_clients()
    
        # Check that get_metadata works as expected
    
        assert self.client1.get_metadata(self.client1_id) == {}
        assert self.client1.get_metadata(self.client2_id) == {}
        assert self.client2.get_metadata(self.client1_id) == {}
        assert self.client2.get_metadata(self.client2_id) == {}
    
        self.client1.declare_metadata(self.metadata1)
    
        assert self.client1.get_metadata(self.client1_id) == self.metadata1
        assert self.client2.get_metadata(self.client1_id) == self.metadata1
        assert self.client1.get_metadata(self.client2_id) == {}
        assert self.client2.get_metadata(self.client2_id) == {}
    
        self.client2.declare_metadata(self.metadata2)
    
        assert self.client1.get_metadata(self.client1_id) == self.metadata1
        assert self.client2.get_metadata(self.client1_id) == self.metadata1
        assert self.client1.get_metadata(self.client2_id) == self.metadata2
        assert self.client2.get_metadata(self.client2_id) == self.metadata2
    
        # Check that, without subscriptions, sending a notification from one
        # client to another raises an error.
    
        message = {}
        message['samp.mtype'] = "table.load.votable"
        message['samp.params'] = {}
    
        with pytest.raises(SAMPProxyError):
            self.client1.notify(self.client2_id, message)
    
        # Check that there are no currently active subscriptions
    
        assert self.client1.get_subscribed_clients('table.load.votable') == {}
        assert self.client2.get_subscribed_clients('table.load.votable') == {}
    
        # We now test notifications and calls
    
        rec1 = Receiver(self.client1)
        rec2 = Receiver(self.client2)
    
        self.client2.bind_receive_notification('table.load.votable',
                                               rec2.receive_notification)
    
        self.client2.bind_receive_call('table.load.votable',
                                       rec2.receive_call)
    
        self.client1.bind_receive_response('test-tag', rec1.receive_response)
    
        # Check resulting subscriptions
    
        assert self.client1.get_subscribed_clients('table.load.votable') == {self.client2_id: {}}
        assert self.client2.get_subscribed_clients('table.load.votable') == {}
    
        assert 'table.load.votable' in self.client1.get_subscriptions(self.client2_id)
        assert 'table.load.votable' in self.client2.get_subscriptions(self.client2_id)
    
        # Once we have finished with the calls and notifications, we will
        # check the data got across correctly.
    
        # Test notify
    
        params = random_params(self.tmpdir)
        self.client1.notify(self.client2.get_public_id(),
                            {'samp.mtype':'table.load.votable',
                             'samp.params':params})
    
        assert_output('table.load.votable', self.client2.get_private_key(),
                      self.client1_id, params, timeout=60)
    
        params = random_params(self.tmpdir)
        self.client1.enotify(self.client2.get_public_id(),
                             "table.load.votable", **params)
    
        assert_output('table.load.votable', self.client2.get_private_key(),
                      self.client1_id, params, timeout=60)
    
        # Test notify_all
    
        params = random_params(self.tmpdir)
        self.client1.notify_all({'samp.mtype':'table.load.votable',
                                 'samp.params':params})
    
        assert_output('table.load.votable', self.client2.get_private_key(),
                      self.client1_id, params, timeout=60)
    
        params = random_params(self.tmpdir)
        self.client1.enotify_all("table.load.votable", **params)
    
        assert_output('table.load.votable', self.client2.get_private_key(),
                      self.client1_id, params, timeout=60)
    
        # Test call
    
        params = random_params(self.tmpdir)
        self.client1.call(self.client2.get_public_id(), 'test-tag',
                            {'samp.mtype':'table.load.votable',
                             'samp.params':params})
    
        assert_output('table.load.votable', self.client2.get_private_key(),
                      self.client1_id, params, timeout=60)
    
        params = random_params(self.tmpdir)
        self.client1.ecall(self.client2.get_public_id(), 'test-tag',
                           "table.load.votable", **params)
    
        assert_output('table.load.votable', self.client2.get_private_key(),
                      self.client1_id, params, timeout=60)
    
        # Test call_all
    
        params = random_params(self.tmpdir)
        self.client1.call_all('tag1',
                              {'samp.mtype':'table.load.votable',
                               'samp.params':params})
    
        assert_output('table.load.votable', self.client2.get_private_key(),
                      self.client1_id, params, timeout=60)
    
        params = random_params(self.tmpdir)
        self.client1.ecall_all('tag2',
                               "table.load.votable", **params)
    
        assert_output('table.load.votable', self.client2.get_private_key(),
                      self.client1_id, params, timeout=60)
    
        # Test call_and_wait
    
        params = random_params(self.tmpdir)
        result = self.client1.call_and_wait(self.client2.get_public_id(),
                                            {'samp.mtype':'table.load.votable',
>                                            'samp.params':params}, timeout=5)

astropy/vo/samp/tests/test_standard_profile.py:226: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/vo/samp/integrated_client.py:428: in call_and_wait
    return self.hub.call_and_wait(self.get_private_key(), recipient_id, message, timeout)
astropy/vo/samp/hub_proxy.py:250: in call_and_wait
    timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <astropy.vo.samp.utils._ServerProxyPoolMethod object at 0x7f5d7f86ba10>
args = ('8c49453e-f762-11e6-84e9-989096bea3fc', 'cli#2', {'samp.mtype': 'table.load.votable', 'samp.params': {'parameter1': 'abcde', 'parameter2': 1331, 'verification_file': '/tmp/tmprRnxVA/XCenK0PIDSTBMjdf'}}, 5)
kwrds = {}, proxy = <ServerProxy for 127.0.0.1:34263/RPC2>
function = <[Fault("<Fault 1: '<type \'exceptions.Exception\'>:method "samp.hub.callAndWait.__repr__" is not supported'>") raised in repr()] _Method object at 0x7f5d7f5e18c0>
exc = <Fault 1: 'Timeout expired!'>

    def __call__(self, *args, **kwrds):
        proxy = self.__proxies.get()
        function = getattr_recursive(proxy, self.__name)
        try:
            response = function(*args, **kwrds)
        except xmlrpc.Fault as exc:
>           raise SAMPProxyError(exc.faultCode, exc.faultString)
E           SAMPProxyError: <Fault 1: 'Timeout expired!'>

astropy/vo/samp/utils.py:67: SAMPProxyError
---------------------------- Captured stdout setup -----------------------------
INFO: Hub set to run with Web Profile support enabled. [astropy.vo.samp.hub]
INFO: Hub started [astropy.vo.samp.hub]
--------------------------- Captured stdout teardown ---------------------------
INFO: Hub is stopping... [astropy.vo.samp.hub]
INFO: Hub stopped. [astropy.vo.samp.hub]
--------------------------- Captured stderr teardown ---------------------------
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/builddir/build/BUILDROOT/python-astropy-1.3-2.fc26.x86_64/usr/lib64/python2.7/site-packages/astropy/vo/samp/tests/web_profile_test_helpers.py", line 176, in _serve_forever
    self.hub.server_close()
  File "/builddir/build/BUILDROOT/python-astropy-1.3-2.fc26.x86_64/usr/lib64/python2.7/site-packages/astropy/vo/samp/hub_proxy.py", line 151, in server_close
    self.proxy.server_close()
  File "/builddir/build/BUILDROOT/python-astropy-1.3-2.fc26.x86_64/usr/lib64/python2.7/site-packages/astropy/vo/samp/utils.py", line 67, in __call__
    raise SAMPProxyError(exc.faultCode, exc.faultString)
SAMPProxyError: <Fault 1: '<type \'exceptions.Exception\'>:method "server_close" is not supported'>

**Comment by pllim** [comment]
Are you sure it is still the same problem? This time, the traceback fails with a different message from the original log you posted above.

Past:
```
E     SAMPProxyError: <Fault 403: 'Request of registration rejected by the Hub.'>
astropy/vo/samp/utils.py:72: SAMPProxyError
```

Present:
```
E    SAMPProxyError: <Fault 1: 'Timeout expired!'>
astropy/vo/samp/utils.py:67: SAMPProxyError
...
SAMPProxyError: <Fault 1: '<type 'exceptions.Exception'>:method "server_close" is not supported'>
```

**Comment by sergiopasra** [comment]
Well, I'm not sure. This issue has a few years and the internal code may have changed. If you thing is better to close this and open a new ticket, I can do it

**Comment by astrofrog** [comment]
It looks like the only tests failing here were related to SSL support, which has now been removed in #6201, so closing this.
