### ISSUE TITLE
Further optimize fast CParser class

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#2922]
As noted in #2716, there appear to be opportunities to further optimize the io.ascii fast-reader Cython code in `cparser.pyx`.  This is a placeholder to remember comment.

**Comment by bsipocz** [comment]
@taldcroft - is this still in the plans, or shall we close the issue?

**Comment by taldcroft** [comment]
There is no active plan for this issue or identified pathway.  Closing.
