### ISSUE TITLE
Better handling of non-ASCII encoded data in io.ascii

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#2923]
As noted in #2716 by @embray:

"Though I'm a little less concerned so much about actually reading those encodings than I am about crashes in odd places because decoding to ASCII failed. I wonder if it wouldn't be better to either a) catch/handle encoding errors early and often, or b) just use latin-1 instead and ignore bad characters (or c) use an appropriate error-mode (replace/ignore))."

**Comment by taldcroft** [comment]
See also #3826.

**Comment by saimn** [comment]
Is #5448 sufficient to close this one, @taldcroft ?

**Comment by taldcroft** [comment]
@saimn - yes, we can close this now.
