### ISSUE TITLE
Consider adding a test with clang

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#2943]
A lot of astronomers are using Macs, which normally uses clang instead of gcc as the C compiler. And #2938 demonstrates that there can be critical differences between them.  So this might mean we should add a Travis test that uses clang instead of the default gcc to build the C extensions.  Alternatively, we might change one of the existing tests to use clang (then that test has a dual-purpose, but then there isn't the extra time of yet another build).

I'm not sure exactly how about to do this, though.  The compiler is normally (always?) determined by what compiler built python, as far as I'm aware.  Does anyone know if we can force use of a different compiler for astropy and have it still work?  Or is there some way to convince travis to use a clang-based python instead of the default? @astrofrog @mdboom @embray @mhvk @larrybradley ?

**Comment by astrofrog** [comment]
We accidentally resolved this issue by adding a MacOS X build to Travis. It uses clang:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/105622311/log.txt
