### ISSUE TITLE
Add ability to read jsviewer tables

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#2945]
#2875 added the nice feature of being able to write Tables out as "jsviewer" style html files.  To close the loop, it would be nice if it were possible to _read_ such tables as well.  This would enable neat tricks like sending the table to your collaborators as a link to a server and having them download the data and load it in astropy in one fell swoop just by grabbing the URL.

I might end up just implementing this myself if I find the time, but if anyone else wants to, they can.  Just to check, though, @astrofrog and @taldcroft, is there any particular technical reason there's not currently a reader?

**Comment by taldcroft** [comment]
HTML is now a registered Table reader and the following example now works, which I think closes the original issue to "add ability to read jsviewer tables":
```
In [17]: t = simple_table()                                                     

In [18]: t.write('tmp/junk.html', format='jsviewer')                            

In [19]: Table.read('tmp/junk.html')                                            
Out[19]: 
<Table length=3>
  a      b     c  
int64 float64 str1
----- ------- ----
    1     1.0    c
    2     2.0    d
    3     3.0    e
```
@eteq - closing this, but as always feel free to re-open if there is really more to do.
