### ISSUE TITLE
Issues for next release

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#295]
Below is a list of issues/items to consider changing regarding the release process, based on my experience doing the 0.1 release.
1. I added an instruction about this, but it's sort of in a strange order right now: I think it's good to have whoever is doing the release do a `python setup.py sdist` and then _test_ that it can be unpacked, built, and have the tests succeed.  Right now that comes _after_ the tag is committed, so you'd have to reset the repo to go back and fix problems that it might reveal.  So a better ordering would be to have the releaser first make the changes to the version number, then do an `sdist`, then unpack, build, and test the sdist, and only if that succeeds does it actually commit the release tag.
2. `python setup.py install` is necessary right now (along with the virtualenv), but only because the `zest.releaser` hooks need to be installed.  It seems strange to require an install to do a source release, so if `zest.releaser` is not used in the next round, the install and virtualenv could be eliminated.  In this case, however, it's important to make sure a build happens, because otherwise Cython won't compile the .pyx files to .c (and the .c files are necessary for release).
3. It's confusing that we use `zest.releaser`, but then don't actually use its upload feature.  So it might be good to either put in a hook to have it not try to upload, or dispense with `zest.releaser`
4. Right now, the PyPI entry is registered with my account - it's probably not important right now, but it should probably be changed at some point to be based on the astropy.team e-mail account (I _think_ PyPI lets you designate people as having rights to edit an entry, so we could do that).
5. Items 1-3 above would probably require some major hacking in `zest.releaser`, so it might be easier to write our own self-contained script, and just pull parts of `zest.releaser` where convenient (particularly the PyPI interaction and the version file changes, which we're still using mostly unmodified).
6. We should also add a file in the docs to store public keys for checking releases, and this needs to be added to the release procedures.

@iguananaut - should I assign this to you, or would you prefer not to deal with it?

**Comment by bsipocz** [comment]
This is rather outdated now, and we just have a branch new overhaul of the release procedure in #5640, so I'm closing, though it's a bit tempting to wait until the 5 year anniversary :)
