### ISSUE TITLE
Some (coordinates?) test not restoring global settings

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2962]
Now when I run the `--remote-data` tests, sometimes the following test fails:

```
______________________________________________ test_highlevel_api_remote _______________________________________________

    @pytest.mark.remote_data
    def test_highlevel_api_remote():
        m31icrs = coords.SkyCoord.from_name('M31', frame='icrs')
    
>       assert str(m31icrs) == '<SkyCoord (ICRS): ra=10.6847083 deg, dec=41.26875 deg>'
E       assert '<SkyCoord (I...41.26875 deg>' == '<SkyCoord (IC...41.26875 deg>'
E         - <SkyCoord (ICRS): ra=10.6847083333 deg, dec=41.26875 deg>
E         ?                                ---
E         + <SkyCoord (ICRS): ra=10.6847083 deg, dec=41.26875 deg>

astropy/coordinates/tests/test_api_ape5.py:441: AssertionError
===================== 1 failed, 7970 passed, 119 skipped, 12 xfailed, 3 xpassed in 426.12 seconds ======================
```

One of the doctests is also affected by this:
```
_____________________________ [doctest] index.rst ______________________________
194     <Distance 1.5228602415117989 pc>
195 
196 
197 Finally, the `astropy.coordinates` subpackage also provides a quick way to get
198 coordinates for named objects assuming you have an active internet
199 connection. The `~astropy.coordinates.SkyCoord.from_name` method of |skycoord|
200 uses `Sesame <http://cds.u-strasbg.fr/cgi-bin/Sesame>`_ to retrieve coordinates
201 for a particular named object::
202 
203     >>> SkyCoord.from_name("M42")  # doctest: +REMOTE_DATA +FLOAT_CMP
Expected:
    <SkyCoord (ICRS): ra=83.82208 deg, dec=-5.39111 deg>
Got:
    <SkyCoord (ICRS): ra=83.8220833333 deg, dec=-5.39111111111 deg>

/Users/Shared/Jenkins/Home/workspace/astropy-master-remote-data-osx-10.8-multiconfig/NV/1.7.1/PV/2.7/docs/coordinates/index.rst:203: DocTestFailure
```

per #2961.

Okay, so I go and add a few more digits of accuracy to the repr string.  Then I run that test file by itself and...it fails with the opposite diff.

I don't know what controls the number of digits to display, but it seems like some earlier test is configuring this globally and not setting it back.

**Comment by mhvk** [comment]
Checking for 1.0 issues: Is this still a problem?

**Comment by astrofrog** [comment]
@mhvk - I'm going to guess yes but would be great if someone could try this out again.

I suspect that this is related to https://github.com/astropy/astropy/issues/3071

**Comment by astrofrog** [comment]
It's not critical for 1.0 though. No one should use ``from_name`` for high precision coordinates anyway.

**Comment by bsipocz** [comment]
Sometimes I still see this, though not always.

e.g. log of three consecutive runs are here: https://gist.github.com/bsipocz/39381d726a12e764bc37

**Comment by astrofrog** [comment]
I'm 99% sure this is due to https://github.com/astropy/astropy/issues/3071 which shows that the server used for name resolution changes every time. I think the solution is simply to always use the same server.

**Comment by mhvk** [comment]
Closing this since @astrofrog was confident this is due to #3071
