### ISSUE TITLE
Table.read reads boolean columns as strings

### ISSUE THREAD

**Issue by griffin-h** [astropy/astropy#2974]
If an astropy table has a boolean column and is written to an ascii file, it cannot be read back in as the same table.

``` python
In [1]: from astropy.table import Table

In [2]: t = Table()

In [3]: t['logical'] = [True, False, False, True]

In [4]: t.write('test.txt', format='ascii')

In [5]: t2 = Table.read('test.txt', format='ascii')

In [6]: t2['logical']
Out[6]: 
<Column name='logical' unit=None format=None description=None>
array(['True', 'False', 'False', 'True'], 
      dtype='|S5')
```

It would be good if Table.read could recognize a column filled with only 'True' or 'False' and convert those to booleans instead of strings.

This is similar to #1953/#2226, but probably unrelated since those are for writing to FITS tables.

**Comment by taldcroft** [comment]
Closing this as fixed by ECSV.
