### ISSUE TITLE
InvalidTransformError in astropy.wcs due to invalid unit

### ISSUE THREAD

**Issue by migueldvb** [astropy/astropy#2977]
When I use the `astropy.wcs.WCS` funciton on a header from an image downloaded from the Herschel archive I get the following error:

```
WARNING: FITSFixedWarning: 'celfix' made the change 'In CUNIT1 : Invalid symbol in EXPON context in 'Degrees''. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "./pacs.py", line 117, in <module>
    pmap = Pacsmap(pacsfile(obsid), fn=horizons_file)
  File "/home/mdevalbo/lib/python/hsso-0.1-py3.4.egg/herschel.py", line 352, in __init__
    self.wcs.set()
astropy.wcs._wcs.InvalidTransformError: ERROR 6 in wcs_units() at line 2202 of file wcs.c:
In CUNIT1 : Invalid symbol in EXPON context in 'Degrees'.
```

I think this happens because of the presence of a capital D in the non-standard Degrees unit that is not recognized as a valid alias. Should this alias by case independent to avoid this problem?

**Comment by astrofrog** [comment]
I'm going to close this, because this was an issue with the FITS files. If someone still feels strongly about that, they can report it to the WCSLIB developer.

**Comment by keflavich** [comment]
Found another wild instance:
https://cdsarc.unistra.fr/ftp/VIII/76/lab.fit.gz
```
InvalidTransformError: ERROR 6 in wcs_units() at line 2897 of file cextern/wcslib/C/wcs.c:
In CUNIT3 : Mismatched units type 'charge': have 'm/S', want 'm/s'.
```

**Comment by pllim** [comment]
`m/S` -- surely the uppercase `S` is a typo?

**Comment by keflavich** [comment]
it was in the header as `M/S`.  And it doesn't matter if it was a typo, it's out there in an archived data product.  I had to manually edit the header to fix this, which is ... I guess a fine workaround.

**Comment by pllim** [comment]
I still think throwing error on invalid unit string is the proper thing to do. It is dangerous to silently assume something that turns out to be wrong. Have you contacted the Archive about it?

**Comment by keflavich** [comment]
I agree, we shouldn't silently assume something different!  But it would be nice to have a mechanism to override the units without editing the file on disk.  This isn't a terribly high priority, but it would be useful.

And no, but I'll try contacting Vizier to see what they have to say.  I don't know if they're willing to modify the files provided by astronomers.
