### ISSUE TITLE
Cache/pre-compute representation_info

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2989]
I was spending a little time profiling parts of astropy.coordinates and I was surprised to see that `get_representation_info` gets called 12 times when doing `FK5(3.2 * u.deg, 2.2 * u.deg)`:

```
%prun FK5(3.2 * u.deg, 2.2 * u.deg)
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       12    0.001    0.000    0.001    0.000 baseframe.py:534(_get_representation_info)
      316    0.000    0.000    0.000    0.000 _collections_abc.py:462(__iter__)
      322    0.000    0.000    0.000    0.000 __init__.py:83(__iter__)
        6    0.000    0.000    0.000    0.000 quantity.py:168(__new__)
      207    0.000    0.000    0.000    0.000 {built-in method isinstance}
...
```

In fact, this takes up a significant fraction of the time (80% of the time of initializing a new frame!). So a few questions:
- Why does it get called 12 times?
- Can we simply cache this since it is a class method? (and will in future be a property that depends only on the class)
- Can we even pre-compute this at import time?

cc @eteq @cdeil

**Comment by adrn** [comment]
This was partially implemented by @eteq. If we think there is more to gain from smarter caching, let's create a new issue to discuss!
