### ISSUE TITLE
astropy.wcs: presence of keywords like "PV1_5" causes error

### ISSUE THREAD

**Issue by kbarbary** [astropy/astropy#299]
I have a FITS file with an SIP transformation, and also, a series of keywords of the form `PV?_?` (`PV1_1`, `PV1_2`, etc). The WCS constructor seems to think these are coordinate transformation parameters. Perhaps it is searching for the SIP coefficients by looking for anything of the form `???_?` ?

To reproduce, grab 
http://supernova.lbl.gov/~kbarbary/tmp/PTF_200906253621_i_p_mask_t084123_u012052003_f02_p002899_c07.fits (17MB) (This is the same example file I used in #257).

```
>>> from astropy.io import fits
>>> from astropy import wcs
>>> hdulist = fits.open('PTF_200906253621_i_p_mask_t084123_u012052003_f02_p002899_c07.fits')
>>> w = wcs.WCS(hdulist[0].header)
WARNING: FITSFixedWarning: 'celfix' made the change 'PV1_5 : Unrecognized coordinate transformation parameter'. This FITS header contains non-standard content. [astropy.wcs.wcs]
>>> w.wcs.print_contents()
ERROR: InvalidTransformError: ERROR 6 in wcsset() at line 1561 of file astropy/wcs/src/wcslib/C/wcs.c:
PV1_5 : Unrecognized coordinate transformation parameter.
 [unknown]
```

... or perhaps there is something I don't know about these `PV?_?` keywords. But it looks like they are SCAMP-specific and not intended to interact with wcs or SIP transformations.

**Comment by pkgw** [comment]
A little note on the exact 8th anniversary of the last comment on this issue (!): Astropy added support for TPV a while ago, but I've just discovered that you'll still get these wcslib complaints about an unrecognized `PV1_5` parameter if your header specifies a `TAN` projection type (or presumably anything other than TPV). If that's the case, you need to change `RA---TAN` to `RA---TPV`, etc.

(Discovered with a FITS file from [DASCH](http://dasch.rc.fas.harvard.edu/project.php).)
