### ISSUE TITLE
Saving Time to FITS

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#3000]
The FITS standard has been changed to include ways to store time values and use them in world coordinate systems [1]. This issue is a reminder that we should try to implement it. The storage is particularly relevant once Time values can be stored in tables. 

[1] http://arxiv.org/abs/1409.7583  EDIT: published as http://adsabs.harvard.edu/abs/2015A%26A...574A..36R

**Comment by mhvk** [comment]
Saving `Time` instances as FITS-compliant strings is now supported (#3547) -- remaining is to store them as binary columns with appropriate header information. The binary data can either be two doubles or an offset from a reference time (for which a single double may be good enough).

**Comment by mhvk** [comment]
@embray - I wondered if it would be useful to raise several more specific issues related to this one. E.g., it could include
1. Allow `io.fits` to return `Time` objects for the various `DATE-*` header strings;
2. Allow a header item to be set using a `Time` object;
3. Allow a table `Time` column to be used.

The reason for my wondering is that with well-defined problems, it becomes more likely at least some aspects will be solved. Indeed, if defined really clearly, it may be that the one solving it is not you!

**Comment by embray** [comment]
@mhvk :+1: to all of these.  I think there might already be one for the first two (which are two sides of the same coin).  The third ain't gonna happen until Astropy Table is used for all FITS tables.

**Comment by taldcroft** [comment]
:+1: as well on these options.  Can the third happen when using `Table.read()` to read a FITS table?

Any ideas for how to implement the "allow" part?  Another keyword option?

**Comment by mhvk** [comment]
Summary: high priority, but needs detailed understanding of both `Time` and `io.fits` to do it right. @mhvk happy to work with someone who has the `fits` knowledge (or is able to acquire it...).

**Comment by taldcroft** [comment]
As mentioned in #5626, the astropy Time object has some features not found in the FITS standard (and the converse is most certainly true).  Examples:
- Attributes `location`, `delta_ut1_utc` and `delta_tdb_tt`.  In astropy `Time` these can all be arrays which are broadcastable to the `Time` values.  In the FITS standard `location` is a scalar expressed via keyword(s).  I'm not sure if `delta_ut1_utc` and `delta_tdb_tt` exist at all in the FITS standard.
- The FITS standard appears to only consider three formats, ISO string, JD and MJD.  `Time` allows for many formats like`unix` or `cxcsec`, etc for representing the values.  Some users may explicitly want to serialize their `Time` object in the format of their choosing.

**Comment by mhvk** [comment]
@taldcroft - Nice summary!
* non-scalar location is indeed not possible; I'd count the `delta`'s as recalculable.
* The formats would be mostly a matter of being able to store the user's preferred format as another piece of metadata, since internally we always convert to JD anyway, so there would be little point in converting back to something else (though note that for a binary fits table column, one is allowed to store time as offsets from a reference epoch given by headers, i.e., one *can* actually store things like unix time).

Overall, it seems that we can use the FITS format fairly easily to store actual `Time` values with, and we can properly keep the most important piece of metadata (`scale`).

**Comment by taldcroft** [comment]
> The formats would be mostly a matter of being able to store the user's preferred format as another piece of metadata

Well... for instance if I want to store a time column as `cxcsec`, I really want the floating point numbers to be CXC seconds, not two columns of JD.  But anyway, I basically agree that we want to support the official FITS format (as an option, not as a requirement).

**Comment by mhvk** [comment]
Wouldn't it be fine to store CXC days? This would be trivially possible with the FITS definition... (possibly the second is fine too; have to check the allowed units).

**Comment by taldcroft** [comment]
> Wouldn't it be fine to store CXC days? 

No.  Here at the CXC we have 20+ years of accumulated code that has been developed from the starting requirement that the `TIME` column in a FITS file is expressed in CXC seconds.  Undoubtedly most of those codes are not applying any sort of data model to that column which would respect other FITS keywords, in particular the unit.

This is not particular to the CXC, but is generically the case for "scientist" code.  Another Time format that is a likely use-case for direct serialization to file is `jyear`.  When plotting long term time series using year as the X-axis is certainly an easy option and lots of people do this.  So if I'm sending a data file to my collaborator who uses simple tools (e.g. supermongo, yes I know even young-ish scientists that do), then they would prefer a time column expressed as float years.

So the question is whether we allow users to seamlessly do what they want, or box them into using the FITS standard which the requires an additional translation layer back into their desired format.

This actually relates perfectly to a discussion I have been having with myself (sorry...) about serializing Time to ECSV.   There are two ways you can do it:

1. Store `jd1` and `jd2`, regardless of format.  This reproduces the time values to double-double precision and is the "lossless" version.
1. Store the representation values for the format.  This is lossy but meets common-use needs.

I suspect that in most cases scientists actually want (2), so I would make it the default, but we certainly need to support (1).  Then when we find someone with the required patience/attention to detail, we will add a third option to store in FITS format.  So this would probably end up as another `TimeInfo` attribute like `write_method: 'formatted', 'jd1_jd2', 'fits'`.

**Comment by mhvk** [comment]
@taldcroft - it turns out the fits standard explicitly allows giving the offset from a reference time in a seconds (or any unit, really; their example at the end of 4.1.2 uses seconds), so CXC can be stored that way without problem: just have to set an appropriate reference time in the header (which other software can happily ignore).

I agree with you that for ECSV almost certainly most users would want a format that is easily readable/parsable without astropy, and thus one should use `Time`'s format. For FITS, this is less obvious, at least in general I think most people would not want time strings, but rather know a close to exact value can be reproduced.

**Comment by mhvk** [comment]
Fixed by #6176 thanks to @AustereCuriosity!

**Comment by pllim** [comment]
Being able to save time to FITS may actually saves time! 😉  Thanks!
