### ISSUE TITLE
New astropy.datasets module for example datasets

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3030]
In various affiliated packages (imageutils, photutils, wcsaxes, reproject) we need example datasets to make documentation examples runnable by users without having to download any extra files explicitly. Take a look for example at the WCS example here:

http://wcsaxes.readthedocs.org/en/latest/getting_started.html#initialization

Specifically:

```
hdu = datasets.fetch_msx_hdu()
```

What this does is actually uses the astropy infrastructure to download and cache the dataset seamlessly, and returns an HDU. Since many of the packages that need/use something like this are intended for merging in Astropy, we should think now about having this in the core package.

Just to be clear, I am not suggesting storing any binary files in the core repository, but instead storing the files on http://data.astropy.org and then fetching them on-the-fly as needed.

cc @larrybradley @cdeil @anizami @eteq

**Comment by bsipocz** [comment]
@astrofrog - This now lives under ``astropy.visualization.wcsaxes.datasets`` as concluded in #3150. Are we happy with that, and thus can use this issue, or there are further action items here, like moving that dataset to the ``astropy.datasets`` namespace?

**Comment by bsipocz** [comment]
An `astropy.datasets` subpackage deemed to be controversial/unneccessary in #3150. The datasets are nevertheless are currently available for the tests, and tutorials has since moved on to their own world.
I'm closing this now, but feel free to reopen if you think we in fact need this subpackage.
