### ISSUE TITLE
Quantities become arrays using np.choose

### ISSUE THREAD

**Issue by bnordgren** [astropy/astropy#3035]
I was trying to us np.choose to avoid writing special code to handle the difference between numpy arrays and scalars. I noticed that Quantities go in, but plain numpy arrays come out.
```
x
Out[25]: <Quantity [-0.1, 0.4] d>

np.choose(x<1*u.day, [x,x+1*u.day])
Out[26]: array([ 0.9,  1.4])
```

np.vectorize() has similar issues, but it tends to strip off the units before calling the function on the array elements. Hence, functions written expecting the arguments to be Quantities will fail because the vectorize wrapper turns these arguments into plain python types.

**Comment by mhvk** [comment]
@bnordren - I think this issue was closed by your #3038, so I'm closing this. Feel free to reopen if I'm mistaken.
