### ISSUE TITLE
Feature Request: optionally allow py.test to see the outside world

### ISSUE THREAD

**Issue by aphearin** [astropy/astropy#3057]
The py.test framework is set up so that the code base only knows about its own state. The motivation is to have the results of the test suite be entirely independent of the state of any global variables external to the code. This is almost always a good idea, but in some special cases this is too restrictive. This Issue is a request for astropy to provide the option for specially marked methods of a test suite to access data that is external to the code base being tested.

I have encountered at least one source of motivation to relax the normal py.test framework's requirements. Sometimes, a very large dataset provides the "right answer" that a certain test of the code should be trying to recover. A common example of this would be if one of the goals of a code base is to develop an accurate set of fitting functions to a massive suite of simulated data. In this example, it would be impractical to have to download a fresh copy of the external data before running the test, due to the sheer size of the dataset. So in such a case, what is needed is for the test suite to be able to access the existing local copy of the large dataset. There are probably many ways to skin this cat, though one possibility would be for the py.test framework to move the location of the external dataset along with the code, execute the tests, and then move the dataset back to its original location on disk upon completion of the test suite. 

@eteq

**Comment by cdeil** [comment]
Related discussion: https://groups.google.com/d/msg/astropy-dev/_kaNJXGPwsc/PAxvB6D9QcsJ

**Comment by pllim** [comment]
Lots of things have changed in the past 10 years. I am not sure how relevant this is anymore.
