### ISSUE TITLE
Allow Table.write(..., format='fits') to write to HDU instances

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3058]
It would be nice to be able to write tables to HDU instances, which would allow one to write to several HDU instances that can then be combined with e.g. Image HDU instances before writing out the file.

An alternative would be to make ``BinTableHDU(Table(...))`` work (by 'work' I mean that the units will be correctly set in the HDU object).

**Comment by cdeil** [comment]
@astrofrog - This sounds very similar to #2632 ... should one be closed?

**Comment by astrofrog** [comment]
@cdeil - yes, let's reduce duplication.
