### ISSUE TITLE
Skycoord broadcast error

### ISSUE THREAD

**Issue by ocehugo** [astropy/astropy#3075]
Hello,

It's the second time I faced this error:

```
425             lon, lat = broadcast_quantity(lon, lat)
426         except ValueError:
--> 427             raise ValueError("Input parameters lon and lat cannot be broadcast")
428
429         self._lon = lon
```

and for the second time, I spent too much time thinking why this have been raised. Since Skycoord expect LON/LAT inputs of the same size, this error is raised instead of a error saying you need to provide lon/lat with same sizes.

Edit: forgot to mention that inputs are numpy arrays.

SkyCoord should check for sizes at input, or should meshgrid lon/lat values to ensure they've equal sizes.  I would expect an Indexerror or any other msg that lead me to the wrong sizes of the input arrays. 

howto reproduce:

aa=np.linspace(0,0.1,10)
bb=np.linspace(0,0.1,20)
grid=SkyCoord(ra=aa_u.deg,dec=bb_u.deg)
ValueError: Input parameters lon and lat cannot be broadcast

**Comment by zhenxuanSUN** [comment]
@ocehugo aa and bb size must be the same？
