### ISSUE TITLE
Add sphinx build on Travis with Python 3

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3088]
Once astropy-helpers is updated to 0.4.4 (once it is out) it will be possible to build the docs in Python 3. At that point, it might be worth adding a build to Travis to avoid any regressions.

**Comment by hamogu** [comment]
So, should we add a Python 3 sphinx build on Travis?

**Comment by bsipocz** [comment]
@hamogu - In theory I'm on it (didn't have time in the past week to work on it, but will pick this thread up soon), but there are still some warnings. However I think this issue can be closed as https://github.com/astropy/astropy/issues/4481 supersedes it.

**Comment by astrofrog** [comment]
Closing in favor of https://github.com/astropy/astropy/issues/4481
