### ISSUE TITLE
Times outside of the IERS table shouldn't raise exception.

### ISSUE THREAD

**Issue by bnordgren** [astropy/astropy#3105]
I have code to calculate the daylength. Integral part of the algorithm is to calculate the sidereal time.

Shiny. Except for computing the daylength for 01-Jan-1901. Or in the future.

Could I propose a "default behavior" of using either a table or some empirical formula to estimate delta_ut1_utc when IERS is not available? Chapter 10 of Meeus' Astronomical Algorithms seems to have some suggestions. (Table 10.A and eqns 10.1/10.2)

Is this all that's required to get rid of the exception? I am far from an expert on astronomical time frames. Honestly I don't care what the offset is, because it should be nearly constant between sunrise and sunset on a given day.

Alternatively, is there a SOFA function which already does this, which can maybe be brought forward?

**Comment by taldcroft** [comment]
Discussion converged on the feeling that this is required for Time (feature not bug).  Closing.
