### ISSUE TITLE
``celestial_pixel_scale()`` could return a "better" estimate of scale for non-square pixels

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#3113]
@astrofrog [suggested](https://github.com/astropy/pyregion/pull/54) to raise this issue with ``astropy``. I believe that currently ``celestial_pixel_scale()`` returns the **arithmetic mean** of scales for each axis:  ``scale=1/2*(scale_X+scale_Y)``.

However, current definition is not related in any way to other important quantities such as pixel area. If there are no strong reasons to keep this definition, e.g., if ``astropy`` does not try to mimic the behavior of some other package, I would like to propose to use a definition for the "average" scale such that ``scale**2=pixel area``. This definition works for both square and non-square pixels. Of course this is just one possible definition and other choices may be possible, so it may be worth to discuss this in order to obtain more suggestions.

If proposed definition is adopted, then for non-square (**but orthogonal**) axes, one could use the **geometric mean** ``scale=sqrt(scale_X*scale_Y)`` - a formula used in the old ``pyregion`` package. For non-square **and** non-orthogonal axes, I would suggest using ``scale=sqrt(abs(det(CD)))`` as explained in https://github.com/astropy/pyregion/pull/54 This latest formula is correct (I think) for square and non-square pixels (orthogonal and non-orthogonal) such that ``scale**2=pixel area``.

**Comment by mcara** [comment]
Based on @nden comment above (two scales for each axis) and on the discussion in #3230, I created PR #3304 that replaces `celestial_pixel_scale` with `celestial_pixel_scales` (returns a tuple of pixel scales for each axis). Also #3304 introduces a new `celestial_pixel_area` function that can be used for conversion of fluxes to brightness or for computing a representative pixel scale based as the scale of  a square pixel of the same area as the area of the input WCS pixel.

**Comment by astrofrog** [comment]
Resolved by #3304
