### ISSUE TITLE
Consider exposing ERFA as part of public API

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3123]
This is non-urgent, but it might be worth considering in future whether the ERFA package with the Python wrapers is part of the public API, and if so, we should add an entry to the documentation about it (and an auto-generated API list). But it makes sense to wait until we've ironed out any issues while making use of it in coordinates.

I know there is interest to provide higher level wrappers with more explicit names, but it doesn't mean the lower-level API can't also be available.

**Comment by mhvk** [comment]
Probably worth reviving this given the wrapping of angle operations and spherical functions in #4571. My vote would be for exposure in a separate pyerfa (or so) package which is part of `liberfa`, and which we use as an external package in astropy.

**Comment by bsipocz** [comment]
Closing this in favour of https://github.com/astropy/astropy/issues/9802
