### ISSUE TITLE
Singleton behavior for units not consistent

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3133]
I may be misunderstanding something, but the following is confusing:

```
In [33]: u1 = u.Unit('cm')

In [34]: u2 = u.Unit('cm')

In [35]: u3 = u.cm

In [36]: u1 is u2
Out[36]: True

In [37]: u1 is u3
Out[37]: False
```

I thought that all instances of ``u.cm`` were the same object - and ``u1`` and ``u2`` show we do expect a 'singleton'-type behavior, but then ``u1 is u3`` should return ``True`` too, right?

cc @mdboom @Cadair

**Comment by mdboom** [comment]
I'm closing this, as I think @astrofrog's original expectation, that `is` holds `True`, is not valid, and `==` works fine.
