### ISSUE TITLE
Remove or expand erfa_time aliases

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#3140]
This came from discussion in #2992.  First some background: Before #2992, the `erfa` bindings used in `time` were custom-written, so they had some names that were not the same as the matched `erfa` functions.  In #2992, the ``erfa_time.pyx`` bindings were replaced by a ``erfa_time.py`` module that just re-maps the old names to the corresponding `erfa` names.

So we should either remove these aliases and just change all instances of thema to the `erfa` binding's standard names, *or* we could implement or more complete aliasing scheme for the rest of erfa and then have `time` just import directly from erfa.

This is not critical because everything works now, it just involves some extra indirection that makes the code a bit more confusing to read.

**Comment by mhvk** [comment]
Closed by #4235
