### ISSUE TITLE
Different approach to remote-data tests?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3155]
At the moment we don't run tests that require remote data unless the remote-data option is passed. This means that we don't usually set remote-data on Travis because we are worried that a single timeout will cause the build to fail.

We could consider a slightly different approach. In the default case we would always try tests that require remote data, but if the part that needs the data fails then we skip the test. But if the data is successfully accessed then we proceed with the test. Then we can have a flag that means 'always fail if remote data cannot be downloaded'.

In practice, this will mean that tests with remote data will run _most_ of the time but will just skip if the data is not accessible, but we will more often catch true failures.

One way we could do this is to make it so the `@remote_data` decorator basically checks if the exception raised by the test is some kind of timeout or URL based error. If so, then it decides whether to skip (default) or fail (if the option to do so was specified). It then also lets any other exceptions (indicating true failures) through.

**Comment by pllim** [comment]
@astrofrog, now that Travis CI has remote data test, can we close this?

**Comment by bsipocz** [comment]
@astrofrog - with the enhancements in #5506, this has been resolved and can be closed, isn't it?

**Comment by astrofrog** [comment]
@bsipocz - yes, once #5506 is merged we can close this :)

**Comment by pllim** [comment]
That one is merged, so closing!
