### ISSUE TITLE
Auto-generate erfa.pyx and erfa.py

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#3159]
Right now the ``erfa.pyx`` (and ``erfa.py`` from #3141) are checked in as source code.  These files are entirely auto-generated using  ``cython_generator.py``, so this seems wasteful of repository bandwidth in the event of future changes to the templates or other aspects of the erfa wrappers (incl. e..g, #3137).

Some discussion of this already has happened in #2992, #3134, and #3141 . Most relevant is an issue pointed out by @astrofrog, that this would then imply a *compile-time* dependency on ``jinja2``.  Presumably we could avoid this for releases by having the tarballs include the autogenerated source,  just as we do right now with ``Cython``-generated c code.  I personally don't think it's a big deal to require ``jinja2`` at compile-time, because it's already necessary for sphinx, which developers should all have to build the docs.

It also *might* make sense to include this on ``astropy_helpers`` in a slightly more generic form, allowing *any* ``cython_generator.py`` sort of usage.  Or we could put it only in the core for now and later generalize if there's call for it.

cc @jwoillez @astrofrog @mdboom @mhvk @embray

**Comment by astrofrog** [comment]
This is addressed by https://github.com/astropy/astropy/pull/3166
