### ISSUE TITLE
Docs html page layout issues in small browser window

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#3171]
I noticed that there's a few small docs html page layout issues if you make the browser window small.

Go to http://astropy.readthedocs.org/en/latest/ and make the width of your browser window small ... some elements from the header will start floating into the main section in random places.

Here's a screenshot that illustrates one of the misplaced header elements:
![screen shot 2014-12-02 at 17 42 00](https://cloud.githubusercontent.com/assets/852409/5266628/39a2a58c-7a4b-11e4-8151-72939bb2b18a.png)

Another minor point is that the banner gets stretched and doesn't look nice any more ... e.g. for `photutils` @larrybradley changes this in https://github.com/astropy/photutils/pull/196 .

**Comment by bsipocz** [comment]
A somewhat related issue is that some of the module names are longer than the width of the sidebar (that is fixed). It doesn't change functionality, but looks rather ugly. E.g.:
![screen shot 2015-01-17 at 17 59 04](https://cloud.githubusercontent.com/assets/6788290/5857333/bf71d1a0-a242-11e4-86c6-1a67fa8c8cb5.png)
.

**Comment by embray** [comment]
^ That issue's been around for a while, and affects some other module documentation pages as well.  I'm not sure what the history is to trying to fix it though.

**Comment by eteq** [comment]
(Reopening because this isn't actually in the astropy core yet.)

**Comment by eteq** [comment]
Looks like this is now fixed, so closing!

 See the latest from http://docs.astropy.org/en/latest/visualization/index.html 
![image](https://cloud.githubusercontent.com/assets/346587/12902807/6f0633ec-ce91-11e5-870d-249779568635.png)
