### ISSUE TITLE
Test fails with astropy-0.4.2 in i386; test_grouped_item_access

### ISSUE THREAD

**Issue by sergiopasra** [astropy/astropy#3180]
The test test_grouped_item_access fails in astropy 0.4.2 fails in i386, but no in x86_64

Full details here: http://guaix.fis.ucm.es/~spr/github/astropy042-f22-i386.txt

============================= test session starts ==============================
platform linux2 -- Python 2.7.8 -- py-1.4.26 -- pytest-2.6.4
Running tests with Astropy version 0.4.2.
Running tests in astropy.
Platform: Linux-3.17.4-301.fc21.x86_64-i686-with-fedora-22-Rawhide
Executable: /usr/bin/python
Full Python Version: 
2.7.8 (default, Nov 13 2014, 14:23:11) 
[GCC 4.9.2 20141101 (Red Hat 4.9.2-1)]
encodings: sys: ascii, locale: ANSI_X3.4-1968, filesystem: ANSI_X3.4-1968, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15
Numpy: 1.9.1
Scipy: 0.14.0
Matplotlib: 1.3.1
h5py: 2.3.1

=================================== FAILURES ===================================
___________________________ test_grouped_item_access ___________________________

E           assert [' c    d ', ...', '12.0   6'] == [' c    d ', '...', '22.0   6']
E             At index 3 diff: u' 5.0  18' != ' 6.0  18'
E             Use -v to get the full diff
astropy/table/tests/test_groups.py:275: AssertionError

**Comment by astrofrog** [comment]
@sergiopasra - can this be closed now? (do you still see the issue with the latest releases of astropy?)

**Comment by bsipocz** [comment]
I'm closing this one, please reopen or open a new issue if you run into it again.
