### ISSUE TITLE
travis failure due to disk space running out?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#3197]
A travis failure I had not seen before: no space left on device.
https://travis-ci.org/astropy/astropy/jobs/43729250

I'm restarting, but thought I would raise it, in case there is a way to avoid it in future.

**Comment by pllim** [comment]
I wonder if this is the same problem resurfacing over at https://travis-ci.org/github/astropy/astropy/jobs/683438799 (AMD64 cron job) after all these years.

```
touch: cannot touch '/home/travis/.casher/cache-...': No space left on device
mkdir: cannot create directory '/home/travis/.astropy': No space left on device
```
