### ISSUE TITLE
Include LONGSTR keyword in headers using the CONTINUE card convention

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3205]
According to the [latest documentation](http://fits.gsfc.nasa.gov/registry/continue_keyword.html) for the CONTINUE convention:

> It is recommended that the following keywords be added to the header of any HDU that uses this
> long string convention:
> 
> LONGSTRN= ’OGIP 1.0’                    / The OGIP long string convention may be used.
> COMMENT This FITS file may contain long string keyword values that are
> COMMENT continued over multiple keywords. This convention uses the ’&’
> COMMENT character at the end of a string which is then continued
> COMMENT on subsequent keywords whose name = ’CONTINUE’.
> 
> The presence of the LONGSTRN keyword serves to indicate that long string keywords may be
> present in the FITS file. The value of this keyword gives the name and version number of the specific
> convention that is used, which in this case is the OGIP (Office of Guest Investigator Programs, at
> the HEASARC) long string convention, version 1.0. The value of this keyword is a string so that
> it may be used to give the name of any other convention that the FITS community might adopt.

When reading files this keyword currently will not be used for anything, as there is only one "version" of the convention.  Files using the convention without this keyword should continue to work as normally as well, since the CONTINUE convention existed before addition of this keyword to the convention.  When writing files, if any correctly formatted CONTINUE cards are included in the header this keyword and the associated comments should be appended to the header, though perhaps there should be an option to disable it (or disable the CONTINUE convention entirely, which would be preferable).

**Comment by shwetamore1295** [comment]
@embray If this issue is still open, I would like to fix this.

**Comment by ArthurSampaio** [comment]
i'll take this and try to solve it

**Comment by Nicolopes** [comment]
Hi, @embray! In fact, adding the LONGSTR Keyword in the header is just a recommendation, as the [documentation](https://fits.gsfc.nasa.gov/registry/continue/continue.pdf) explains. This means that you don't need to include it in the header, because if you have any long strings keywords in your FITS file, these will be automatically fitted according to the CONTINUE convention. I made a FITS file for testing and checked this out. Remember also that you can always delete a keyword in the header by using del hdr[1], for instance. You can get more information about this [here](http://docs.astropy.org/en/stable/io/fits/usage/headers.html).

**Comment by embray** [comment]
Of course, it's just a recommendation.  Though one thing I have long disliked about FITS is that there is not a standard way a FITS file can specify exactly what additional conventions outside the standard it is using.  I think it would be nice, given that the documentation for the convention recommends this, to follow the recommendation.  Most FITS readers I know if will just support this convention implicitly, but it is still nice to be explicit that it's being used.

FWIW I wrote the documentation you linked to and the code it documents so I know it already works without this :)

**Comment by Nicolopes** [comment]
So just to be clear, you'd like to explicitly add the information of which conventions the FITS file is using in addition to the standard one. Is that correct?

**Comment by embray** [comment]
OTOH I was just looking at the FITS Standard 4.0 for the first time since it came out (it came out after I stopped working on Astropy regularly) and they now appear to have included CONTINUE cards into the standard.  So maybe this is a moot point.  There's also no convention for specifying which version of the standard a given file conforms to because of the misleading "once FITS always FITS" mantra.  So perhaps this is pointless now.
