### ISSUE TITLE
Wishlist: support JPL ephemerides

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#3219]
As noted in #2244 and #3217, eventually we should support using the JPL ephemerides. A good place to start would be @brandon-rhodes https://github.com/brandon-rhodes/python-jplephem

It needs some mechanism by which a user can opt to download the (large) ephemeris files, as we would not want to include those in `astropy` by default.

**Comment by aarchiba** [comment]
Let me add that providing this would remove a major annoying dependency for the pulsar timing package PINT.

It looks like jplephem is modest in size and requirements; the only concern is what to do about big ephemeris data. de421 at least is in pip, so one could make it an optional dependency, I suppose. Or it could be downloaded as needed, but then where to put it?

There is also "skyfield": http://rhodesmill.org/skyfield/

**Comment by aarchiba** [comment]
For comparison, the skdata is mostly python code but downloads large data files as needed; here is how they arrange it: https://github.com/jaberg/skdata/wiki/Managing-Data

**Comment by Juanlu001** [comment]
skyfield dependes on jplephem anyway, and it is higher level.

Now there are two methods to compute ephemerides: pip-installing de421 and related packages or working with SPK files. Quoting from the PyPI page:

> If you want to use one of these pip-installable ephemerides, you will be using a slightly older API, and will lose the benefit of the efficient memory-mapping that the newer SPK code performs.

de432s is "only" 10 MiB covering from 1950 to 2050, but anyway I agree with @mhvk that a mechanism for the user to download the files would be desirable.

**Comment by brandon-rhodes** [comment]
Note that while `jplephem` will continue to support its own old pip-installable ephemeris format, that the project has now pivoted to also support pure SPICE kernel files through NumPy, so that it can run from standard `.spk` files. See the first few sections of its docs on PyPI:

https://pypi.python.org/pypi/jplephem

In case that helps anyone. :)

**Comment by mhvk** [comment]
@brandon-rhodes - that's great! I think for astropy, it definitely makes most sense to base our work on `jplephem`, and this should make it all the easier.

**Comment by bsipocz** [comment]
This can be closed as #4890 is now merged.

**Comment by mhvk** [comment]
Yay, a very old wishlist item is done!
