### ISSUE TITLE
ascii.read failing on three column text file

### ISSUE THREAD

**Issue by jbochanski** [astropy/astropy#3221]
Hi, 

I tweeted about this yesterday, but ascii read is seg faulting on a generic three column file (wavelength, flux and variance).

```
from astropy.io import ascii
filename = 'some_file.txt'
d= ascii.read(filename, names=['wave','flux','err'])
```

will complete, however if I run:

```
from astropy.io import ascii
filename = 'some_file.txt'
d= ascii.read(filename, names=['wave','flux','err'])
e= ascii.read(filename, names=['wave','flux','err'])
```

the code _usually_ seg faults, with the following error:

> /Users/jbochanski/anaconda/bin/python.app: line 3: 52591 Segmentation fault: 11 /Users/jbochanski/anaconda/python.app/Contents/MacOS/python "$@"

However, there are times that it does complete.  If I add a third or fourth read, then it always seg faults.

Thanks!

**Comment by Sleekery** [comment]
I'm having the same problem. 

Numpy: 1.9.0
Scipy: 0.14.0
Matplotlib: 1.4.0
h5py: 2.3.1

Installed everything via anaconda.  Also running Yosemite.

**Comment by taldcroft** [comment]
@sleekery - as in earlier in the thread can you try an experiment of creating a fresh minimal environment to see if the problem goes away? If it does go away, are there other packages you have installed from source that might be causing a bad interaction? Stuff that might overwrite source or library files from conda.

**Comment by bsipocz** [comment]
This is a very old issue and quite a lot has been fixed with the ascii reader since. I suggest to close it. If anyone run into anything similar again, please open a new issue, sharing their astropy, numpy, and python version, along with the file that causes troubles.
