### ISSUE TITLE
Better support for py.test --debug

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3228]
py.test has a `--debug` option that makes it write a debug log that is sometimes useful when debugging issues with the test runner/test collection.  We can use this fine via our `./setup.py test` command using the `--args` option, so I'm not proposing adding a new command-line argument.

However, it's not apparent that there is any way to control where this debug log is written to.  By default it appears to be written to the testing base dir, which for the Astropy test runner is a temp directory:

```
wrote pytestdebug information to /tmp/astropy-test-k7qd6zhc/lib.linux-x86_64-3.4/pytestdebug.log
```

which once tests are done running no longer exists.  I think if nothing else, the Astropy test runner could check for this file and copy it elsewhere before cleaning up the temp dir.  That, or we could figure out how to make py.test write it elsewhere.

**Comment by AMAN3003** [comment]
@embray i am creating the scripts to add log  messages to file

**Comment by AMAN3003** [comment]
@embray  please review the commit.Do I need to add tests

**Comment by bsipocz** [comment]
`pytest` can now directly be run, and the `pytestdebug.log` file is then put in the main source directory.

I think this is a clear "won't fix" given the current direction of moving away from the custom `setup.py test`.

**Comment by drdavella** [comment]
Agreed. I'll hit the close button.
