### ISSUE TITLE
da2bf588 introduced astropy.table asv regression

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#3233]
Again, I'm not suggesting this _has_ to be resolved...

da2bf588 seems to have introduced a 3-times slow-down in both the masked and non-masked version of the following benchmarks:
- time_hstack
- time_vstack
- time_join_inner
- time_join_outer
- time_item_get_colfirst

It's no surprise that this comes out of that change, and it's probably unavoidable.

**Comment by mdboom** [comment]
@taldcroft: In your opinion, would it make sense to add the above patch (for hstack and friends)?  It seems like it might, given that the number of columns is generally a small number.

**Comment by taldcroft** [comment]
@mdboom - yeah, that would make sense.

**Comment by bsipocz** [comment]
Closing this as #3292 is partially resolved it. We may want to revisit this and reopen once asv is up and running again and this turns out to be an issue with current master.
