### ISSUE TITLE
Fix unit test fails on Windows / Appveyor

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#3242]
When turning on continuous integration for Windows on AppVeyor in #2755 we told it to skip some unit tests that failed.

You can get a full list of these skipped tests in master using this full-text search:
https://github.com/astropy/astropy/search?utf8=%E2%9C%93&q=fails+on+AppVeyor

Here's a list:
- [x] `test_blackbody_scipy` and `test_blackbody_overflow` in `test_blackbody.py`
- [x] `test_setitem_invalid_shape` in `test_flag_collection.py`
- [ ] one test in `astropy.io.fits`
- [x] lots of tests in `astropy.io.ascii`

If someone with access to Windows could try to reproduce and fix these issues, that would be great!

**Comment by cdeil** [comment]
@embray – did you fix the issues listed here completely or partly in #3525?

**Comment by embray** [comment]
I didn't personally notice any of these other issues.  Running the tests on my own machine the only ones that failed were the ascii ones.  Maybe the others were 32-bit issues?

**Comment by embray** [comment]
Hmm--for some reason I thought that when I grepped for APPVEYOR I didn't even see any tests being skipped outside of io.ascii.  Maybe I only grepped within the io.ascii package--not sure.  Those tests don't fail for me locally though.

**Comment by pllim** [comment]
Blackbody tests are fixed in #4393, so I updated the relevant checkbox above. FYI.

**Comment by embray** [comment]
Ah, I forgot about this issue yet again.  I'll have to see if I can debug the FITS one at some point.

**Comment by mwcraig** [comment]
Thanks for the reminder, the flag collection test is no longer skipped.

**Comment by cdeil** [comment]
This search by now comes up empty:
https://github.com/astropy/astropy/search?utf8=%E2%9C%93&q=fails+on+AppVeyor

I'm closing this old issue now.

The task list above still mentions one skipped test in astropy.io.fits.
I'm not sure if it's still the case or not, and I don't know remember how to find it.

**Comment by bsipocz** [comment]
Yes, that last one was resolved in #4565
