### ISSUE TITLE
Verify accuracy of ICRS <-> AltAz transformation

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3244]
Before 1.0 is finally released, this is a reminder that we need to make sure that the ICRS <-> AltAz transformation agrees with other codes.

cc @eteq @cdeil

**Comment by astrofrog** [comment]
@cdeil - have you had a chance to work on the coordinates-benchmark code? It would be good to test it this week so we have some confidence ahead of the release.

**Comment by cdeil** [comment]
Related: https://github.com/astropy/coordinates-benchmark/pull/10

**Comment by cdeil** [comment]
I'll working on this in #3296

**Comment by astrofrog** [comment]
Removing the milestone since I think this is done enough for 1.0, but leaving open in case we want to do more extensive/accurate tests.

**Comment by eteq** [comment]
I'm going to close this on the basis that it was mostly a "changes we want for 1.0" issue, and a fair amount of accuracy testing is in there. If we still think we want more it might be better in an external benchmark, I think?
