### ISSUE TITLE
Support pathlib.Path objects in all file-path-accepting functions

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#3247]
Is there a reason why `fits.open()` and `ascii.read()` can't use `os.path.expanduser()` on input file paths? It would be nice to be able to pass in, e.g., 

```
ascii.read('~/Downloads/whatever.fits')
```

**Comment by adrn** [comment]
I actually now think instead we should make sure that any filename-receiving function accepts `pathlib.Path` objects!

**Comment by taldcroft** [comment]
@adrn - I'm pretty sure this is done, right? From what I can see `Path` objects are accepted everywhere.

**Comment by adrn** [comment]
Yes - looks good! I'll reopen with a specific case where it doesn't work
