### ISSUE TITLE
Releasing an affiliated package with Cython-generated .c files

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#3267]
The instructions for "Releasing an affiliated package" (http://docs.astropy.org/en/latest/development/affiliated-packages.html#releasing-an-affiliated-package) result in a source distribution that does not include any Cython-generated `.c` files (Cython should not be required to build a numbered source package).  This is because of the `git clean -fxd` step(s), which remove any generated files (including the generated `.c` files, which are not tracked).

For the `photutils 0.1` release, I didn't run the `git clean -fxd` step(s), but manually removed all generated files *except* for the generated `.c` files.  Is there a better way to ensure the Cython-generated `.c` files get included in the source distribution?  In any case the astropy docs on releasing an affiliated package need to be updated.

CC:  @embray, @astrofrog

**Comment by embray** [comment]
I think this is partly related to astropy/astropy-helpers#53.  In the meantime it should work if you make sure to run `setup.py build sdist` (this ensures that the build command is run before the sdist command).  Does that do the trick?  There shouldn't be any reason to do anything manually.

The rest of this just sounds like a documentation update, maybe...

**Comment by larrybradley** [comment]
@embray, yes it's the same as astropy/astropy-helpers#53.  `setup.py build sdist` works (packages the `.c` files), but it also packages `.pyc` files.  Is that OK?

**Comment by embray** [comment]
It shouldn't package .pyc files.  You should have a line in your MANIFEST.in like:
```
global-exclude *.pyc *.o
```

**Comment by larrybradley** [comment]
That works, thanks.  In `photutils` (and `package-template`), `MANIFEST.in` has `exclude *.pyc *.o`.  I'll change these to `global-exclude`.  I'll also update the "releasing an affiliated package" docs to use `setup.py build dist` instead of `setup.py dist`.

**Comment by embray** [comment]
Thanks, that would be good for now.

**Comment by embray** [comment]
Should be taken care of by #3295.
