### ISSUE TITLE
Problems with SkyCoord

### ISSUE THREAD

**Issue by nicoywa** [astropy/astropy#3270]
Hi all:

I changed ubuntu 12.04LTS for 14.04LTS  just a few days ago, and i can't import SkyCoord to my scripts,  because my machine drop this message:

name 'SkyCoord' is not defined

The modules of i import are the next ones:

# Modules
import numpy as np
from scipy import stats
from astropy.coordinates import SkyCoord
from astropy import units as u
import pylab as plt
from math import sqrt

And i no have idea why!!!!
Any help will be welcome!
Regards.

**Comment by astrofrog** [comment]
@nicoywa - could you do:

```python
import astropy
print(astropy.__version__)
```

? ``SkyCoord`` is only available in Astropy >= 0.4, so it could be related to that.

**Comment by nicoywa** [comment]
Thanks! 
Now i'm notice that, also im notice im a stupid guy :(
I will close this issue :D
