### ISSUE TITLE
AppVeyor running 32-bit Python?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3276]
On AppVeyor, the header from pytest shows:

```
============================= test session starts ============================= 
platform win32 -- Python 2.7.9 -- pytest-2.5.1 
```

however, in the files to set up the conda environment, etc. there are several mentions of '64'. Should it be running the tests on 64-bit Windows as opposed to ``win32`` as shown above?

cc @Cadair @mwcraig

**Comment by mwcraig** [comment]
Let me know if you want me to take a look, @Cadair

**Comment by Cadair** [comment]
@mwcraig go on then :P I have sunpy shaped problems today!

**Comment by mwcraig** [comment]
@astrofrog -- This can be closed, I think. The platform on which python is running is report in a few places in the py.test output.

This one, at the beginning of test running, comes from `py.test` itself:
```python
============================= test session starts ============================= 
platform win32 -- Python 2.6.9 -- pytest-2.5.1 
```
I'm guessing they use `os.sys.platform`, which on my 64bit windows VM running 64bit anaconda, has value `win32`.

Lower down in the test is the platform that astropy inserts from `platform.platform()`:
```python
Platform: Windows-post2008Server-6.2.9200
```

and then, a little lower down, the full python version:

```python
2.6.9 |Continuum Analytics, Inc.| (unknown, Oct 30 2013, 10:18:50) [MSC v.1500 64 bit (AMD64)]
```

So I think we are actually running 64 bit python on 64 bit windows.

**Comment by astrofrog** [comment]
@mwcraig - just to check, in 64-bit Python, is it normal for Numpy to default to 32-bit ints? (just to make sure I understand)

**Comment by mwcraig** [comment]
@astrofrog -- quick experiment seems to show the answer is "it depends on platform." On my mac, 64-bit, default int is 64-bit. On my windows 64-bit python vm it is 32-bit.

I have no idea if that is supposed to be the "normal" behavior for numpy, though...

**Comment by astrofrog** [comment]
Ok, thanks for checking. I'll go ahead and close this since indeed it does seem to be using 64-bit python (I was confused before because there were failures related to int32 vs int64).

**Comment by embray** [comment]
The value of `sys.platform` has nothing to do with the OS or Python architecture: https://hg.python.org/cpython/file/c16b76c7c8ba/PC/pyconfig.h#l317
