### ISSUE TITLE
Ampersand on the end of last substring with CONTINUE keyword

### ISSUE THREAD

**Issue by hworpel** [astropy/astropy#3282]
According to the [latest version](http://fits.gsfc.nasa.gov/registry/continue_keyword.html) of the CONTINUE convention, the ampersand '&' character should NOT be appended to the last substring. Currently astropy.io.fits appends the ampersand to all substrings, including the last one.

**Comment by embray** [comment]
That is true--the ampersand should not be included on the last CONTINUE card.  Thanks for pointing that out.

**Comment by embray** [comment]
This should be fixed by #3328--thanks @sornars and @hworpel for reporting.
