### ISSUE TITLE
Potential Bug in u.quantity_input

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#3289]
I will test this and write a patch this evening, but I wanted to just raise it here.

Please see sunpy/sunpy#1255.

**Comment by embray** [comment]
Did you intend to close this?

**Comment by Cadair** [comment]
@embray see #3293.

**Comment by embray** [comment]
Issues should only be closed if the PR addressing the issue is merged.

**Comment by Cadair** [comment]
fair enough, as this was just a stub, I thought I would replace it with a more detailed issue in #3293.

**Comment by Cadair** [comment]
This was closed by #3293.
