### ISSUE TITLE
pdf/postscript reader for Table

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3301]
This is very pie-in-the-sky, but also not outside the realm of possibility.

At the Software Carpentry workshop at AAS somebody asked if it was possible to read/write LaTeX tables with Astropy, and I was very pleased to be able to answer "Yes!" and even provide a demonstration.

That got me thinking though--often times there are tables one might want to use that show up in documents, for which one does not have access to the original .tex, and perhaps the author has not been helpful in providing the data directly.  So one would like to be able to scrape the table right off the PDF.  (That said, is this often really a problem in practice?  Maybe it isn't.  I just thought it would be cool...)

Scraping an arbitrary table from an arbitrary PDF is far from trivial and typically requires some manual intervention.  But it can be done.  And for simple tables created from a LaTeX document using pdflatex we could probably implement fairly general handling.  It helps that there are already powerful PDF parsing libraries for Python, so the reader could have options for the user to point out where to look in the file for a specific table they want to read in, and it could then do a bit of guessing (as io.ascii already does) to work out the rest.

I think this could also make a fun GSoC project.

**Comment by astrofrog** [comment]
Definitely very :cake: in the :stars:, but would be awesome!

**Comment by Cadair** [comment]
Cake in the shooting star? :p

**Comment by mdboom** [comment]
Cool idea.  This is the kind of thing I used to do in a former life:

http://gamera.informatik.hsnr.de/

Though, there we were using printed/scanned/historical materials, so it was a harder problem than from clean computer-generated PDFs.

**Comment by embray** [comment]
Great, then I'll assign you @mdboom :D  (j k)

**Comment by hamogu** [comment]
I used to type in tables from PDFs on the past every now and then, but have not done so for quite a while because almost every paper is either available in HTML or in LaTeX from astro-ph. That not to say that this would not be cool, but it's a not too frequent use case with lots of corners.

**Comment by mdboom** [comment]
pdftotext may get us most of the way there.  I just searched on arXiv for the #1 paper with the word "Table" in it (it's not astro), and was able to get this out fully automatically:

```
                                                      τ              α                   β
                  fossil data                    2.0 ± 0.2       1.7 ± 0.3           1.5 ± 0.1
                  NKCS                              ≃1               –                   –
                  Bak and Sneppen                  1 to 23           1                   –
                  Vandewalle and Ausloos        1.49 ± 0.01          –             1.89 ± 0.03
                  Newman and Roberts            2.02 ± 0.03          –                   –
                  Sol´e and Manrubia            2.05 ± 0.06          –             2.05 ± 0.06
                  Amaral and Meyer              1.97 ± 0.05          –                   –
                  Newman                        2.02 ± 0.02     1.03 ± 0.05          1.6 ± 0.1
                  Manrubia and Paczuski          1.9 ± 0.1          ≃2                  ≃2
                  Sibani et al.                       2              1                   –
```

From this, maybe we just need a custom splitter that splits on more-than-one space?  How hard would that be, @taldcroft?

**Comment by hamogu** [comment]
Such a costum splitter should not be too difficult, but we obviously 
need to find a way to deal with non-ASCII characters. In other words, we 
might need an astropy.io.unicode and that is much harder.

**Comment by taldcroft** [comment]
This looks like fixed width, so if possible parsing it that way would be more reliable.  So we probably need some heuristic to guess the column positions or else require those as input up front.  

Right now there is a problem with a two-space delimiter in that the Python reader uses the stdlib `csv` module which only accepts single character delimiters.  The fast C reader also has this limitation, though I'm not sure if that is real or just there to match the Python version.  @mdmueller ?

And the elephant in the room that @hamogu mentioned in unicode, which is badly supported in `csv` for python 2.  Maybe this could be a py3-only feature...

**Comment by hamogu** [comment]
Maybe that'll be a feature to drive people to adopt python 3...

**Comment by mdmueller** [comment]
Just double-checked and the C reader is basically structured on the assumption that the delimiter is one character only; this could be changed, but it would be nontrivial. I'm not familiar with how `csv` works with unicode, but if fixed_width doesn't use `csv` and could work for this then that sounds good to me.

**Comment by astrofrog** [comment]
I'm going to mark this as 'Close?' - I don't think we'll realistically ever get to this given how low this is on the priority list....

**Comment by taldcroft** [comment]
:+1: to close.
