### ISSUE TITLE
Update built-in Cone Search services list?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#3317]
The 10 sites below have been consistently down for a while now with this error:

*ERROR: SQL Exception: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. Contact saicas[at]sai.msu.ru in case of problems*

It does not affect Cone Search functionality but there is also no point checking them nightly with default `astropy.vo.validator` settings.

http://vo.astronet.ru/sai_cas/conesearch?cat=usnob1&tab=main&RA=0&DEC=0&SR=0.1&VERB=3
http://vo.astronet.ru/sai_cas/conesearch?cat=sdssdr7&tab=photoobjall&RA=0&DEC=0&SR=0.1&VERB=3
http://vo.astronet.ru/sai_cas/conesearch?cat=twomass&tab=xsc&RA=0&DEC=0&SR=0.1&VERB=3
http://vo.astronet.ru/sai_cas/conesearch?cat=sdssdr7&tab=specobjall&RA=0&DEC=0&SR=0.1&VERB=3
http://vo.astronet.ru/sai_cas/conesearch?cat=sdssdr7&tab=field&RA=0&DEC=0&SR=0.1&VERB=3
http://vo.astronet.ru/sai_cas/conesearch?cat=sdssdr7&tab=phototag&RA=0&DEC=0&SR=0.1&VERB=3 
http://vo.astronet.ru/sai_cas/conesearch?cat=usnoa2&tab=main&RA=0&DEC=0&SR=0.1&VERB=3 
http://vo.astronet.ru/sai_cas/conesearch?cat=sdssdr7&tab=sppparams&RA=0&DEC=0&SR=0.1&VERB=3 
http://vo.astronet.ru/sai_cas/conesearch?cat=sdssdr7&tab=specphotoall&RA=0&DEC=0&SR=0.1&VERB=3 
http://vo.astronet.ru/sai_cas/conesearch?cat=twomass&tab=psc&RA=0&DEC=0&SR=0.1&VERB=3

**Comment by embray** [comment]
Could this have anything to do with why I've hardly ever been able to get the `--remote-data` tests to pass lately?

**Comment by pllim** [comment]
I don't think so. I never included the services from `astronet.ru` to my tests due to its unreliability. But if you see error messages from `astropy.vo.client` or `astropy.vo.validator`, please let me know so I can investigate.

**Comment by pllim** [comment]
Hmm, those services are up again today...

**Comment by pllim** [comment]
Battle for another day.
