### ISSUE TITLE
Import erfa error

### ISSUE THREAD

**Issue by ehandzo** [astropy/astropy#3326]
Hi,

I just installed Astropy and am attempting to import the module erfa. After I import astropy (no errors) I try

astropy.erfa and satrapy._erfa

and the error I get is "AttributeError: 'module' object has no attribute '_erfa'". Has anyone else encountered this error before? I have Astropy version 1.0.dev11597. Thanks for any help.

**Comment by bsipocz** [comment]
@ehandzo - Modules are not imported automatically when you do ``import astropy``.
Have you tried importing the them like this?

```
import astropy.erfa
import astropy._erfa
```

**Comment by astrofrog** [comment]
Just for info, I renamed ``astropy.erfa`` to ``astropy._erfa`` this evening, so if you are using a fresh developer version, you can import ``_erfa`` as @bsipocz showed

**Comment by mhvk** [comment]
To add to @astrofrog's comment: the reason we are calling it `_erfa` for now is that we do not yet know for sure where this module should live! I.e., its location may still change.
In that respect, out of curiosity, what functionality in `erfa` are you using? I ask because it might be something that we should include in the corresponding astropy objects.

**Comment by embray** [comment]
As already mentioned, #3277 was merged recently which renamed `astropy.erfa` to `astropy._erfa`.

**Comment by ehandzo** [comment]
The erfa module is currently being used in the new pulsar timing package, PINT. To utilize this software I need to have erfa module running.

**Comment by mhvk** [comment]
@ehandzo - great to hear it is being used in PINT; I was very pleased to hear from @scottransom that `Time` could be used to help time pulsars as accurately as with tempo2 (after debugging based on PINT...). If the functionality you need in PINT is something you think is not ultra-specialised, please do raise a new issue asking for it: this is how astropy gets better! (even if sometimes it takes a while...).

**Comment by scottransom** [comment]
@mhvk There are only a couple functions used from erfa: xys00a, c2ixys, erfa.sp00, pom00, era00.  These are used (in pint/erfautils.py) to provide positions and velocities of an observatory at a certain Time referenced in ITRF geocentric coordinates and including polar motion, precession, nutation etc.

I certainly don't mind changing how things are imported in PINT, but I really *do* like the idea of the ERFA routines being easily available (and as a member of the SOFA board, I know that the rest of the board does as well).  And the wrappers for ERFA that are now in astropy are *really* nice.  Kudos.

**Comment by mdboom** [comment]
> as a member of the SOFA board, I know that the rest of the board does as well

Not to beat this dead horse, but if the rest of the board likes the idea of the routines being easily available, they need to change the license.  The whole forking and renaming thing is silly and just creates busy work.

> And the wrappers for ERFA that are now in astropy are really nice.

I believe the long term plan is to make the Python wrappers for ERFA part of their own project outside of astropy, possibly, though TBD, part of the ERFA repo itself.  astropy would then depend on that library.  (There was discussion about this in the issue tracker, but I can't seem to find it now...)

**Comment by scottransom** [comment]
@mdboom I completely agree with you about the license.  I am a relatively new member (about 2 yrs) and I fought hard about this to no avail.  There are strong views about keeping things the way they are by some very important members of the board (who have invested a lot of their own time and efforts into the code).  So I'm not optimistic.

I don't really care if the nice ERFA wrappers are directly part of astropy or are a dependence of astropy.  Either way provides a big benefit for the astro-coder.

**Comment by mhvk** [comment]
@scottransom - sounds like additional reasons to get our `Observatory` class off the ground (cc @eteq).  
As @mdboom notices, ideally we end up with the wrappers in `liberfa` itself, but since this would be packages with `astropy`, it would only change the import path.  (@mdboom, the disucssion was on astropy-dev: https://groups.google.com/forum/#!topic/astropy-dev/qKrxPtNZs2I).

**Comment by embray** [comment]
Definitely :+1: to making SOFA/ERFA routines easily accessible, either through a higher-level interface in Astropy, or more directly through our nice new Numpy-compatible Python wrappers.  I'm definitely in favor of the Python wrappers being technically separate from Astropy, but as @mhvk to the user there's not much difference except for an `import` statement.  (And ostensibly it's one more thing to install, but as I think I argued in that thread the installation issue is mostly irrelevant--if a user can't install it as a separate package they won't be able to install Astropy either.  The rest is mostly a matter of documentation.)

**Comment by eteq** [comment]
I'm actually in favor of them remaining part of astropy, but my thinking was to table a discussion of this until the v1.0 release is out, so that we can actually make whatever changes are necessary right away in the v1.1 development cycle.  So my thinking is that should have a full discussion of this and actually come to a conclusion in maybe a few weeks time.

**Comment by mhvk** [comment]
@eteq - though I think the python bindings should live in `liberfa`, I also agree that we don't need to decide for 1.0 (indeed, I thought this is why we moved to `astropy._erfa`, so that we are not committed either way).

**Comment by embray** [comment]
@mhvk Exactly so (and anyways this issue wouldn't be the place to discuss it ;)
