### ISSUE TITLE
maxiter argument to SLSQPLSQFitter.__call__ broken

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3338]
As pointed out in [this comment](https://github.com/astropy/astropy/pull/3305#issuecomment-70253326), calling an `SLSQPLSQFitter` instances with the optional `maxiter` keyword argument fails, although it is advertised to work in the docs.  This appears to be little more than a simple argument handling bug, and possibly affects other fitter classes as well.

**Comment by nden** [comment]
I'll provide a fix for this shortly.

**Comment by embray** [comment]
This was fixed by #3339.
