### ISSUE TITLE
Update astropy.io.ascii docstrings to use Numpydoc format

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3352]
This is an easy low priority issue in case anyone wants to learn how to contribute - the astropy.io.ascii module contains functions that still have the following docstring format:

```
    :param data_start: line index for the start of data not counting comment lines
    :param data_end: line index for the end of data (can be negative to count from end)
    :param converters: dict of converters
    :param data_Splitter: Splitter class to split data columns
```

(example from ``astropy/io/ascii/ui.py``). It would be good to update these to the numpydoc format that we use, e.g.

```
    Parameters
    ----------
    data : numpy ndarray, dict, list, or Table, optional
        Data to initialize table.
    masked : bool, optional
        Specify whether the table is masked.
    names : list, optional
        Specify column names
    dtype : list, optional
        Specify column data types
```

**Comment by embray** [comment]
:+1: I was wondering about that when I saw @hamogu's recent PR.  Thought maybe I was losing my mind or something :)

**Comment by algerdnazgul** [comment]
I think we can close this issue. Code is upate in astrpy\io\ascii

**Comment by embray** [comment]
@algerdnazgul Thanks for the PR.  We don't close issues though unless a PR to solve that issue is actually *merged* first (which is not to say that yours won't be merged but we have to go through the process first, as there are more than enough PRs that are *not* merged, so closing the issue falsely gives the impression that the issue has actually been fixed in the main repo).

**Comment by algerdnazgul** [comment]
Thanks a lot. I am studying all your processes flow now.

**Comment by taldcroft** [comment]
It's a bit confusing to follow, but since #3367 and #4346 are both merged, it looks like we can close this now.  Any objections?

**Comment by hamogu** [comment]
Given that it's so confusing +1 for closing. If something was missed we can always open a new issue.
