### ISSUE TITLE
WCS.sub fails for unicode string axis specifier in Python 2

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#3356]
@mdboom Is it possible to make [WCS.sub](http://astropy.readthedocs.org/en/latest/api/astropy.wcs.WCS.html#astropy.wcs.WCS.sub) just work for unicode string axis specifiers in Python 2?

I ran into this error on Python 2 after adding
```python
from __future__ import unicode_literals
```
at the top of my file:
https://travis-ci.org/gammapy/gammapy/jobs/48255732#L2870

Here's a simple example that shows the issue I get on Python 2:
```python
>>> from astropy.wcs import WCS
>>> wcs = WCS()
>>> wcs.sub(['longitude'])
<astropy.wcs.wcs.WCS object at 0x10fc44d70>
>>> wcs.sub([u'longitude'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/astropy-1.0.dev11571-py2.7-macosx-10.10-x86_64.egg/astropy/wcs/wcs.py", line 495, in sub
    copy.wcs = self.wcs.sub(axes)
TypeError: axes sequence must contain either strings or ints
```

**Comment by mdboom** [comment]
Good catch.  We try so hard to make `unicode_literals` work in our testing but this one was missed.  I should have a fix shortly.
