### ISSUE TITLE
fast reader sometimes misorders comments

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#3372]
A couple times now I've seen an intermittent failure on the `io/ascii/tests/test_c_reader.py` test called `test_store_comments`.  The specific failure mode is that it sometimes mis-orders "comment 3" to come _before_ "comment 2".  

Unfortunately, I can't figure out how to reproduce this.  And because of that, I can't tell if it's associated with the "parallel" version of the reader or not.  My hunch is yes, as that would explain out-of-order randomess, but I have no easy way to test that.  @taldcroft, do you have any insight here?

**Comment by taldcroft** [comment]
I've seen that failure a number of times but only ever on the first run of tests.  I never got it to happen on the 2nd or 3rd time.  Certainly the parallel stuff is a good place to start looking, but I don't have much further insight.  @mdmueller ?

**Comment by mdmueller** [comment]
Ok I see the problem--it is a parallel issue. I'll open a PR to fix this.

**Comment by astrofrog** [comment]
This should be fixed by https://github.com/astropy/astropy/pull/3414
