### ISSUE TITLE
Unnecessary loss of precision when writing WCS to FITS header

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#3375]
WCSlib currently uses ``%20.12G`` format (see e.g., ``.../cextern/wcslib/C/wcshdr.c``) when writing the header values of the WCS (CRPIX, CRVAL, CD, etc.) to the FITS header. This leads to an _unnecessary_ loss of accuracy (of about 4 digits) in the WCS reconstructed from a FITS file.

**Comment by mdboom** [comment]
Just to fill in some details: For the `G` specifier, the number after the `.` indicates the number of significant digits to include.  The number of digits of precision available in a double is about 16.  I can take this issue up with Mark Calabretta (author of wcslib).

**Comment by mcara** [comment]
@mdboom Please do so. Even though 12 digits appear to be enough for accurate coordinate computations (e.g., RA & DEC) - definitely within the astrometric accuracy of most measurements, for other computations (such as checking of orthogonality of the CD matrix - see, e.g., #3329, and other computations), we loose some accuracy. There is really no cost (well, except for a few bytes) associated with using 16 digit results, so I just think we should start using 16 digits to store WCS information.

**Comment by astrofrog** [comment]
I agree - we should be using 16 digits of precision (if anything, slightly on the larger side than the true precision)

**Comment by nden** [comment]
@mcara, when you get a chance, can you confirm this is fixed now (by #4616)?

**Comment by mcara** [comment]
I just checked the accuracy of the WCS parameter values (``CRPIX``, ``CRVAL``, etc.) and I can confirm that now headers are written out with 14 digits of accuracy.

I still see no reason why we do not write out everything with 16-17 digits as WCSLIB now allows that. I see that you have hardcoded ``precision = WCSHDO_P14``. I wonder if it could be either changed to ``precision = WCSHDO_P16`` (or even 17) or, alternatively, have a precision parameter added to the ``to_header()`` function...

**Comment by nden** [comment]
The `precision = WCSHDO_P14` is only a default value. You can pass any precision to the `relax` keyword. IIRC `WCSHDO_P14` was a compromise and you can always change it by passing one of the allowed values to `relax`. 
I'm also not opposed to adding a `precision` keyword to `to_header`, if someone wants to create a PR. Since there's no loss of precision any more I will close this issue.
