### ISSUE TITLE
TemplateAssertionError build issue with development version

### ISSUE THREAD

**Issue by scottransom** [astropy/astropy#3376]
Hi All

So for the last couple weeks I've been seeing the following build issue on a Linux Ubnutu 12.04.5 system.  I hadn't updated astropy in a couple months previously, so the issue may have been there previously.  I'm using python 2.7.3 and the various python libraries (including numpy 1.6.1) from Ubuntu.

Googling for similar errors didn't give me much of a clue.

Scott
------------------

```
root@nimrod:/usr/local/src/astropy# python setup.py install --prefix=/usr/local
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to astropy.egg-info/requires.txt
writing astropy.egg-info/PKG-INFO
writing top-level names to astropy.egg-info/top_level.txt
writing dependency_links to astropy.egg-info/dependency_links.txt
writing entry points to astropy.egg-info/entry_points.txt
reading manifest file 'astropy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'astropy/utils/misc/data/.hidden_file.txt'
warning: no files found matching '*' under directory 'scripts'
warning: no files found matching '*' under directory 'astropy/sphinx/themes'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'build'
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'astropy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running pre_hook from astropy._erfa.setup_package for build_py command
pre_build_py_hook command hook build_py raised an exception: %s

Traceback (most recent call last):
  File "/usr/local/src/astropy/astropy_helpers/astropy_helpers/setup_helpers.py", line 398, in run_command_hooks
    hook_obj(cmd_obj)
  File "astropy/_erfa/setup_package.py", line 24, in pre_build_py_hook
    preprocess_source()
  File "astropy/_erfa/setup_package.py", line 72, in preprocess_source
    verbose=False)
  File "astropy/_erfa/erfa_generator.py", line 367, in main
    erfa_pyx_in = env.get_template('core.pyx.templ')
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 719, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 693, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 493, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "astropy/_erfa/core.pyx.templ", line 30, in template
    __all__ = [{{ funcs|map(attribute='pyname')|surround("'_","'")|join(", ") }}]
TemplateAssertionError: no filter named 'map'
```

**Comment by astrofrog** [comment]
@scottransom - I wonder if this is a ``jinja2`` version issue. Can you try and upgrade to the latest version of ``jinja2`` to see if it helps?

**Comment by scottransom** [comment]
Yeah, moving from jinja2 2.6 -> 2.7.3 does fix this.  Although that is strange since from what I've found on the 'net is that "map" has been a jinja2 built-in for ages (since v1.x at least).  Strange...

**Comment by astrofrog** [comment]
Very weird - let's leave this open as a reminder to set a minimum version.

**Comment by embray** [comment]
According to the [changelog](http://jinja.pocoo.org/docs/dev/changelog/) the `map` filter was only added in 2.7.  Maybe the map *function* was available as a builtin but not in context as a filter?

**Comment by embray** [comment]
"I marked this as 'Affects-release' as a reminder that the changelog should also be updated to specify the requirement for Jinja2 >= 2.7 (I think it already mentions Jinja2 but not the version requirement).

**Comment by astrofrog** [comment]
Although of course, this should only affect the dev version, i.e. the stable version does not require jinja2

**Comment by embray** [comment]
It's more for me to know if something needs to go in the changelog or not.

**Comment by astrofrog** [comment]
Fixed in d22d877b05c0d11fa1e52b4fa4835fdad383dd8d and 45d5dc5553ceea31f6dc62c9a3904e71566ac4ca

**Comment by eteq** [comment]
Ok, I think this is now fixed by @astrofrog's commits, but lets leave this open as a reminder that they need to be backported to the v1.0.x branch (the script won't see those because they aren't PRs).

**Comment by eteq** [comment]
Alright, this has now been backported to v1.0.x in 2a06fa2d1d74303dc8b6bcf69a6f56b89c9694d1 and a4cc7ce05e9904d40ae51c140e81791f395c465f .  

So I'll close this issue now, although if you think more is needed @scottransom, feel free to re-open.
