### ISSUE TITLE
1.0rc1 cannot be built with the current version of astropy-helpers (0.4.4)

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#3377]
I tried to build the release candidate, but failed with using the current (external) helpers:
If I set
```
[ah_bootstrap]
auto_use = False
```
to use the external helpers, I get
```
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from astropy_helpers.distutils_helpers import is_distutils_display_option
ImportError: No module named distutils_helpers
```
Could you release an updated astropy-helpers package?

**Comment by astrofrog** [comment]
@olebole - the plan was to release astropy-helpers 1.0 just before astropy 1.0. Maybe @eteq or @embray can comment on how we can avoid the situation you describe?

**Comment by olebole** [comment]
Could you create an astropy-helpers 1.0rc?

**Comment by astrofrog** [comment]
@olebole - I'm not sure if it would help, if it was a hidden release on pypi. Let's see what @embray says.

**Comment by olebole** [comment]
I would (need to) create a Debian package for the helper rc, which would not be hidden, but published on Debian experimental, and then use this as build requirement for the astropy rc package (which also would go to Debian experimental). I could also create the experimental helpers package directly from git, but this would require some effort, and it would not make sure that everything finally fits together.

**Comment by embray** [comment]
I had mentioned to @eteq of changing this

```
from astropy_helpers.distutils_helpers import is_distutils_display_option
```

back to 

```
from astropy_helpers.setup_helpers import is_distutils_display_option
```

for now so that there should still be compatibility with the old astropy_helpers.  That will happen before 1.0 final is out.  In the meantime I'm not really sure what to say.

**Comment by eteq** [comment]
#3392 implemented the change @embray mentioned here. @olebole, can you check if that resolved the situation?
