### ISSUE TITLE
Problems with redshifted Gaussian example in compound model docs

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#3391]
One of the model composition examples (see https://astropy.readthedocs.org/en/latest/modeling/compound-models.html#model-composition) implements a `RedshiftedGaussian` model.  However, there are two issues.  First, the Gaussian appears to be *blueshifted* instead of redshifted, assuming the currently unlabeled (it should be labeled) x-axis is wavelength (see https://astropy.readthedocs.org/en/latest/modeling/compound-models-1.png).  The green `z=0` Gaussian appears to be at the largest wavelength (and the line is broadest).

The second issue is more subtle, but important.  Redshifting a spectrum/emission line, etc. involves more than just transforming the wavelengths.  There needs to be a corresponding transformation to conserve flux, e.g. wave' = wave * (1 + z) **and** flux' = flux / (1 + z).  Again looking at the "redshifted" Gaussian figure, notice that the integrated line flux is changing with redshift because the line width is changing.  There needs to be a corresponding amplitude change to conserve integrated flux.

**Comment by pllim** [comment]
1. This was brought up before in #2176 

2. As for preserving flux, it was discussed before among `pysynphot` folks. We couldn't agree on what is the best way to do it (apparently there are two different formula depending on your beliefs; I don't remember the exact details now). So for now, in `pysynphot`, only wavelengths are redshifted. That's probably why the example lacks flux correction, as I contributed the Redshift model.

**Comment by embray** [comment]
I'm a little confused because I labeled the x-axis "energy" but the label doesn't seem to be showing up.  You're right that if it were wavelength it would be wrong.  I think on the flux conservation issue it's fine to just note that this is a simple example model and does not conserve flux, unless someone would like to contribute a specific example that does this.

**Comment by embray** [comment]
If there are different religious beliefs about the correct flux conservation model that's fine too--if there's a model that's simple enough for example purposes we can use that too.  If not, better to keep it simple (or use a different example altogether, if someone would like to contribute it).

**Comment by embray** [comment]
FWIW I based this example off of this: http://heasarc.nasa.gov/xanadu/xspec/xspec11/manual/node40.html#zgauss

**Comment by larrybradley** [comment]
Unfortunately, I don't think redshift is a good example for model composition (but I don't have a good alternative off the top of my head).   The example is evaluating a Gaussian at a redshift wavelength array and then plotting it against the unredshifted wavelength array.  That's not the same thing as redshifting a Gaussian.  Also, the `Redshift` model simply scales the input by `(1 + z)` so it should only take wavelengths as input (not energy, which would scale as `1./(1 + z)`).  I submitted a PR (#3433) to make that more explicit by changing the name to `RedshiftWavelength`.

@pllim For ETC-type work, it probably doesn't matter for you to properly scale the flux because I'm guessing the spectrum is later normalized in some band to the desired flux level.  But in general flux conservation is rather important and you could be asking for trouble...  :smile:

In #3433 I also added a `RedshiftSpectrum` model.

**Comment by embray** [comment]
I think I see.  Though I think it's important to have a good, hopefully useful, and easy to understand example of composition--I've asked every time I discuss this feature for better "real world" examples but nobody has been forthcoming which I find odd.

**Comment by pllim** [comment]
`pysynphot` uses this composition thing a lot. I have a draft at http://stsdas.stsci.edu/astropy_synphot/synphot/index.html , which is very outdated by now, but hopefully will give you some ideas on how your compound models are going to be used.

**Comment by embray** [comment]
@pllim thanks--thought I don't see any examples on there that use a simple composition model :\

**Comment by embray** [comment]
The new synphot is looking pretty great though!

**Comment by pllim** [comment]
Haha, sorry. If it's simple, I wouldn't get paid to maintain `pysynphot`...

**Comment by nden** [comment]
If there's interest in this I can put together an alternative example which chains coordinate transformations to create a simple pixel to sky composite transformation.

**Comment by embray** [comment]
@nden That would also be nice to have *in general* and is certainly welcome.  Though I don't think it would serve as an alternative to this specific example.  My goal there was to have a very simple 1-D model composition example.  Following it up with more complicated 2D examples (there is already one after it involving rotations, for example) is fine but wasn't the purpose of this example.

**Comment by nden** [comment]
@embray That's fine. I take back my suggestion.

**Comment by embray** [comment]
Well, like I said, it would still be nice to have, but up to you.

**Comment by larrybradley** [comment]
I thought of possible "real world" example: deriving reddening/extinction at redshifted (observed) wavelengths for a synthetic spectrum.  Unfortunately there are no reddening laws in `astropy`.  They are defined in `specutils`, but not as `astropy` `Models` (perhaps they should). http://specutils.readthedocs.org/en/latest/specutils/extinction.html

**Comment by embray** [comment]
If I recall correctly that's the plan--I think support for `Quantity` parameters was deemed the critical missing feature there.

**Comment by embray** [comment]
Maybe the existing example is fine for demonstration purposes, but either just needs a different name, or some kind of disclaimer attached to it.  Really it's just evaluating some function on a simple transformation of the coordinates.

**Comment by larrybradley** [comment]
Yeah, for reddening, the units on the input wavelength array are critical.

I can think of examples of *functional* composition, e.g. changing a function of luminosity to a function of magnitude (f(L) -> f(L(m))).  But I'm drawing a blank for *model* composition (where parameters are involved in both models).

**Comment by larrybradley** [comment]
Perhaps you could make a `ShiftedGaussian` using `Shift` instead of `Redshift` for simplicity?

**Comment by embray** [comment]
In this framework the difference between a "function" and a "model" is a bit hazy.  You can have a "model" with no parameters.  It's mostly a semantic difference in how it's used IMO.

**Comment by embray** [comment]
It used to be a little more clearcut in that there was a separate class for `ParametricModel` very much in the statistical sense.  But since parameters became a deep part of the implementation, and because you could define other "models" in the framework that have parameters as well but are other types of mappings like coordinate transformations, then it didn't make a lot of sense code-wise to segregate the concepts.

**Comment by pllim** [comment]
Would something like this make more sense, @larrybradley ? If so, I can submit a PR to *add* this one after the original `RedshiftedGaussian` example:

```python
import numpy as np
from astropy.modeling.models import Redshift, Gaussian1D

x = np.linspace(1000, 5000, 1000)
g0 = Gaussian1D(1, 2000, 200)  # No redshift is same as redshift with z=0

plt.figure(figsize=(8, 3))
plt.plot(x, g0(x), 'g--', label='$z=0$')

for z in (0.2, 0.4, 0.6):
    rs = Redshift(z).inverse
    g = rs | g0
    plt.plot(x, g(x), color=plt.cm.OrRd(z),
             label='$z={0}$'.format(z))

plt.xlabel('Wavelength')
plt.ylabel('Flux')
plt.legend()
```

![figure_1](https://cloud.githubusercontent.com/assets/2090236/14831507/17bd9f7e-0bc4-11e6-9c72-b9beb2e69acc.png)

**Comment by larrybradley** [comment]
@pllim Your example correctly shows that the lines are redshifted, which is an improvement. 😄   However, it is still not conserving energy, e.g. there is more integrated flux at z=0.6 (wider Gaussian with same amplitude) than at z=0.  Perhaps that's not necessary to include for this compound model example though.

**Comment by pllim** [comment]
What is the formula to conserve energy? If it is straighforward, maybe I can find a way to make that another model and chain it with the `|` operator.

**Comment by pllim** [comment]
Okay, how about this?

```python
import numpy as np
from astropy.modeling.models import Redshift, Gaussian1D

x = np.linspace(1000, 5000, 1000)
g0 = Gaussian1D(1, 2000, 200)  # No redshift is same as redshift with z=0

plt.figure(figsize=(8, 5))  # NOTE TO DEV: Changing the dimension from 3 to 5 should show the X label
plt.plot(x, g0(x), 'g--', label='$z=0$')

for z in (0.2, 0.4, 0.6):
    rs = Redshift(z).inverse
    g0.amplitude /= (1 + z)  # Rescale the flux to conserve energy
    g = rs | g0
    plt.plot(x, g(x), color=plt.cm.OrRd(z),
             label='$z={0}$'.format(z))

plt.xlabel('Wavelength')
plt.ylabel('Flux')
plt.legend()
```

![figure_1](https://cloud.githubusercontent.com/assets/2090236/14832872/4d681a72-0bca-11e6-9df0-514fe7236117.png)

**Comment by larrybradley** [comment]
👍

**Comment by embray** [comment]
:+1:

**Comment by embray** [comment]
It was never meant to be a "physical" example--just a demonstration of composing models.  But if this makes it more palatable I'm all for it :)

**Comment by pllim** [comment]
Yikes, there is a fatal mistake in my example above. I shouldn't have used `/=`. Also, might be more elegant to use `Scale` instead of overwriting amplitude like that. I'll update my PR shortly.
