### ISSUE TITLE
Is default RADESYS set correctly by WCS?

### ISSUE THREAD

**Issue by nden** [astropy/astropy#3403]
For a header with `EQUINOX=2000` and missing `RADESYS`, astropy.wcs defines `RADESYS` as `ICRS`, when it should be FK5 if I'm not mistaken.

FITS Paper II states "If the EQUINOX keyword is given it should always be accompanied by RADESYS. However, if it should happen to appear by itself, then RADESYS defaults to FK4 if EQUINOX < 1984.0 or to FK5 if EQUINOX >= 1984.0. RADESYS defaults to ICRS i fboth it and EQUINOX are absent."

Am I right to think the above case defines RADESYS as FK5?
This is a new feature in wcs. Is the logic in wcslib or the wrapper?

**Comment by mdboom** [comment]
The logic is in wcslib.

```c
  /* Set defaults for radesys and equinox for equatorial or ecliptic. */
  if (strcmp(wcs->lngtyp, "RA")   == 0 ||
      strcmp(wcs->lngtyp, "ELON") == 0 ||
      strcmp(wcs->lngtyp, "HLON") == 0) {
    if (wcs->radesys[0] == '\0') {
      if (undefined(wcs->equinox)) {
        strcpy(wcs->radesys, "ICRS");
      } else if (wcs->equinox < 1984.0) {
        strcpy(wcs->radesys, "FK4");
      } else {
        strcpy(wcs->radesys, "FK5");
      }

    } else if (strcmp(wcs->radesys, "ICRS")  == 0 ||
               strcmp(wcs->radesys, "GAPPT") == 0) {
      /* Equinox is not applicable for these coordinate systems. */
      wcs->equinox = UNDEFINED;

    } else if (undefined(wcs->equinox)) {
      if (strcmp(wcs->radesys, "FK5") == 0) {
        wcs->equinox = 2000.0;
      } else if (strcmp(wcs->radesys, "FK4") == 0 ||
                 strcmp(wcs->radesys, "FK4-NO-E") == 0) {
        wcs->equinox = 1950.0;
      }
    }

  } else {
    /* No celestial axes, ensure that radesys and equinox are unset. */
    memset(wcs->radesys, 0, 72);
    wcs->equinox = UNDEFINED;
  }
```

**Comment by mdboom** [comment]
Can you post a copy of the header?  Indeed it seems like it's not following the spec, but the code looks ok, so maybe there's something else going on.  Have you called `wcs.wcs.set()` first?  (You shouldn't need to, as it's called implicitly in a number of places, but that is where the "normalization" happens.)

**Comment by nden** [comment]
Oh, I just realized why this is set to ICRS for HST files. The EQUINOX keyword is in the primary header, and the WCS information in the first extension header. Doh.

**Comment by mdboom** [comment]
Ah -- that would explain it...  I hope the spec doesn't say anything about primary headers operating as fall-back values for extension headers :wink:

**Comment by nden** [comment]
Hell no! However, if the information about the coordinate system is in the primary header and the WCS keywords in the extension, then writing out a default RADESYS will always default to ICRS which may be incorrect.

**Comment by nden** [comment]
I'm closing this since it's a "user issue" :-)

**Comment by embray** [comment]
"validation considered harmful"  mmhm....  :(
