### ISSUE TITLE
test failures in 1.0rc1 with python 3.4.2

### ISSUE THREAD

**Issue by migueldvb** [astropy/astropy#3405]
There are several test failures using python version 3.4.2 on an arch linux system.
The full log of the output from the command `python setup.py test` can be found here:
http://sprunge.us/KjWj

**Comment by astrofrog** [comment]
@migheldvb - can you run the test suite for the latest developer version to check that the BS4 failures are gone?

**Comment by migueldvb** [comment]
@astrofrog, Yes this problem is solved, thanks for the fix. I got again the MemoryError in `test_convolve_fft` but this is on a 4GB RAM machine with about 50% memory usage.

http://sprunge.us/VKBG

**Comment by migueldvb** [comment]
@astrofrog Yes, with #3406 there is no MemoryError.

**Comment by astrofrog** [comment]
Resolved by #3406 and #3411
