### ISSUE TITLE
writeto(sys.stdout) not working on Python 3

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3427]
It's occasionally useful, mostly for debugging purposes, to be able to write HDUs directly to `stdout`.  This works on Python 2.  However, on Python 3 `sys.stdout` is an `io.TextIOWrapper` which the array writer recognizes as a file object so it passes it to `ndarray.tofile()`.  However, `ndarray.tofile()` does not work on these objects, resulting in a crash.

**Comment by sergiovelascom** [comment]
I will try to take a look at this issue

**Comment by embray** [comment]
@sergiovelascom There is already a PR for this in #3501 .  I'm not 100% happy with the current approach, but I think this may be something I need to look into.

**Comment by at88mph** [comment]
I have a similar issue that affects the `append()` method.  When writing to `sys.stdout` in Python 2 or 3, the `astropy.io.fits.convenience._stat_filename_or_fileobj` function is called which then calls the `tell()` method, but this will try to seek, which is illegal for `sys.stdout` and `sys.stdout.buffer` in Python 3.  

Is this a new issue?  Can it be tacked on here?

**Comment by at88mph** [comment]
Thanks @bsipocz.  I ran it with the same results though:
```
  # Log output from my app to see the type of stream.
  DEBUG:root:Output stream is <_io.BufferedWriter name='<stdout>'>
  ...
  ...
  File "/usr/local/lib/python3.7/site-packages/astropy/io/fits/convenience.py", line 606, in append
  File "/usr/local/lib/python3.7/site-packages/astropy/io/fits/convenience.py", line 1049, in _stat_filename_or_fileobj
    loc = filename.tell()
OSError: [Errno 29] Illegal seek
```

**Comment by at88mph** [comment]
In case anyone else runs into this, I ended up hacking my own write-only stream wrapper for the `sys.stdout` stream:
```
class WriteOnlyStream(BufferedRandom):
    def __init__(self, raw):
        # Hack for the constructor as it needs something seekable.
        super(WriteOnlyStream, self).__init__(io.BytesIO())

        self._raw = raw
        self.write_offset = 0
        self.read_offset = 0

    def read(self, size=1):
        raise ValueError('Unreadable stream.  This is write only.')

    def write(self, data):
        written = self._raw.write(data)
        if written:
            self.write_offset += written
        self._raw.flush()
        return self.write_offset

    def tell(self):
        return self.write_offset

    def seek(self, offset):
        raise ValueError('Unseekable stream.  This is write only.')
```

```
output_stream = WriteOnlyStream(sys.stdout)
...
```
