### ISSUE TITLE
Table.write does not preserve whitespace padding when using format='ascii'

### ISSUE THREAD

**Issue by barentsen** [astropy/astropy#3429]
When specifying the format of a column that includes whitespace-padding, the padding is lost when the table is written to a file. For example:

```Python
In [1]: from astropy.table import Table
In [2]: t = Table({'x': [1, 2, 3]})
In [3]: t['x'].format = '{:10d}'
In [4]: print t
    x     
----------
         1
         2
         3
In [5]: import sys
In [6]: t.write(sys.stdout, format='ascii')
x
1
2
3
```

In contrast, padding with a non-whitespace character works fine:
```Python
In [7]: t['x'].format = '{:*>10d}'

In [8]: print t
    x     
----------
*********1
*********2
*********3

In [9]: t.write(sys.stdout, format='ascii')
x
*********1
*********2
*********3
```

The loss of the whitespace padding after `In [6]` comes across as a bug to me?

**Comment by embray** [comment]
Yeah, sounds like it.

**Comment by embray** [comment]
Not exactly clear on where this is happening, but if I'm to guess this should force `strip_whitespace` to false when writing values from columns that are formatted with padding.  Not sure how to make that happen.

**Comment by embray** [comment]
That said, if I just use `strip_whitespace=False` that doesn't quite do what you want either.  So I'm not sure.

**Comment by taldcroft** [comment]
Currently this stripping is an intended feature since in the `basic` format (whitespace delimited), whitespace characters are not significant.  If you use the `fixed_width` writer then whitespace is preserved:
```
In [6]: t.write(sys.stdout, format='ascii.fixed_width')
|          x |
|          1 |
|          2 |
|          3 |
```
What's your use-case?

**Comment by taldcroft** [comment]
(Will likely remove the Bug label pending further discussion).

**Comment by taldcroft** [comment]
And `strip_whitespace=False` is doing what I would expect:
```
In [9]: t.write(sys.stdout, format='ascii.basic', strip_whitespace=False)
x
"         1"
"         2"
"         3"
```
You need the fields in quotes so it can round-trip back.

**Comment by barentsen** [comment]
I was generating input files for use by Daophot, for which there is no writer in Astropy. Using `format='ascii.fixed_width'` combined with `delimiter=''` does work fine and solves my problem, thanks!

Now, I'm not sure if I was being silly by not thinking of trying `ascii.fixed_width`, or whether it really is unexpected behaviour for `ascii` to throw away the whitespaces I asked for? Those whitespaces are of course insignificant at the time of reading, but I only cared about writing a file in my use case.

(If my expectation was indeed silly, I'm happy to have this issue closed!)

**Comment by taldcroft** [comment]
@barentsen - nothing on your end has been silly, these are good questions.  But I do think that the `ascii` format output in this case (with `strip_whitespace=False`) is correct and the behavior should not be changed.  For instance if you use `,` as delimiter this is the result:
```
In [9]: print(t)
   col0    col1
---------- ----
         1    3
         2    4

In [10]: t.write(sys.stdout, format='ascii.basic', strip_whitespace=False, delimiter=',')
col0,col1
         1,3
         2,4
```
The example I showed in the previous comment with `space` as delimiter is also correct, it being the output of the std lib `csv` module that puts a field in quotes if it contains the delimiter.

So there are two "workarounds": 1) `fixed_width` or 2) `t.pformat()`.

For your use case the real fix would be to add a DAOphot writer.  I didn't realize that anyone actually writes in DAOphot format.  :smile:

**Comment by embray** [comment]
:+1:

**Comment by embray** [comment]
Has there been an issue opened for a DAOphot writer?  I feel like it's come up before...

**Comment by taldcroft** [comment]
Just added #3436 to implement a DAOphot writer.

**Comment by barentsen** [comment]
The use case for this (in my case) is to use daophot for list-driven actions, in particular fitting a psf model using an externally determined list of template stars (because daophot's `pstselect` isn't perfect for non-interactive use).

I'm not sure this is a terribly common use case.
