### ISSUE TITLE
Un-xfail wcs tests when wcslib supports version testing

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#3439]
PR #3435 set a couple of tests to xfail unconditionally that really should be conditional on the installed version of wcslib.  For standard source builds of astropy this is a non-issue because the c library is included. But if a system-installed wcslib is used (like for Fedora or Debian packages), the version isn't guaranteed.

@olebole reported that wcslib plans to add a function for getting the library version at runtime in the next release.  So once that's in (hence the "upstream fix required"), we can re-enable the tests turned off in #3435 using that interface.

cc @mdboom

**Comment by embray** [comment]
I suppose this would also include re-enabling `_wcs.__version__` which would be set during module initialization via a call to WCSLIB's version function.

**Comment by embray** [comment]
Has there been any news on this?  Do we know if the updated wcslib is available in Debian yet?

**Comment by mdboom** [comment]
wcslib 5.0 is the first version with the dynamic version function, and it just came out with a beta three days ago.  It will be a while until it's in Debian.  See #3669.

**Comment by olebole** [comment]
I'd recommend to re-enable this as soon as #3669 is merged.
Debian is currently in its last phase before its next release "Jessie" which is planned for 25 Apr, and before this I will not upload wcslib or astropy into unstable/testing. Once we are back to normal work, and after Mark Calabretta made the new wcslib release official, I would first upload this to unstable, and only then a new astropy release.
If needed, I always can temporarily patch this again.

**Comment by embray** [comment]
In that case though, this won't happen for v1.0.x, which is fine.

**Comment by astrofrog** [comment]
Removed milestone since don't think this will happen today

**Comment by bsipocz** [comment]
0c235002b17242096be93a618d1be618b794cb72 has removed these xfails, so closing.
