### ISSUE TITLE
Remove JointFitter

### ISSUE THREAD

**Issue by nden** [astropy/astropy#3445]
What the `JointFitter` does is equivalent to fitting a compound joined `&` model. When The `JointFitter` class should be removed when compound joined models become fittable. This is also related to #3444.

**Comment by embray** [comment]
Agreed.  I think a related issue though is making sure that parameters in a compound model can be properly tied to each other (either with a `tied` constraint, or possibly some other mechanism (I've heard a few ideas about this)).  I think right now that still needs more work, but once the functionality of `JointFitter` truly can be replaced then :+1: on deprecating:arrow_right:removing it.

**Comment by karllark** [comment]
I have a strong use case for a jointfitter.  JWST+Spitzer spectroscopy fitting.  Same wavelengths, different instrumental resolutions.

**Comment by karllark** [comment]
I don't think the jointfitter can be replaced with compound models.  The ability to fit two *overlapping* datasets (say in wavelength) is not something that I can see how to do otherwise.  See PR #12720 for documentation with an example of this.
