### ISSUE TITLE
Astropy test runner doesn't pass KeyboardInterrupt to pytest 

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#3460]
When you run a test session with `py.test` and interrupt it, you get the error traceback and info from the already completed tests. This doesn't seem to happen when you run the astropy test runner, through `setup.py` or otherwise.

See astropy/astropy_helpers#134  @embray

**Comment by embray** [comment]
The thing that's odd about this is that the SIGINT *should* be captured by the child process launched by the test runner.

The other thing that's odd is that while I've seen this kind of behavior before, I can't seem to reproduce it right now.  Usually it works but I've had it not work on occasion.

**Comment by embray** [comment]
D'oh, also, you were right I was wrong.  It only actually runs a subprocess in the `./setup.py test` command provided by astropy-helpers.  It does *not* do that for the normal test runner.  I'll leave this issue open and reopen the one in astropy-helpers.  Sorry for that.

**Comment by embray** [comment]
Would be nice to fix this...
