### ISSUE TITLE
Support conversion from Jy/beam to K

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3463]
At the moment we have a `brightness_temperature` equivalency for converting Jy to K, which requires a beam area. It would be nice to also be able to simply convert `Jy/beam` to `K` without explicitly specifying a beam area.

cc @keflavich

**Comment by keflavich** [comment]
It would be great if we could make it work with the [radio-beam](https://github.com/radio-astro-tools/radio_beam) package, which reads standard beam parameters from FITS headers.

But, @astrofrog, what you've asked for isn't possible, I think - Jy/beam has no meaning without a beam area.

**Comment by astrofrog** [comment]
Ah of course, but so when we do:

```
(3 * u.Jy).to(u.K, equivalencies=u.brightness_temperature(0.01 * u.sr, 3 * u.mm))
```

is it the same as if one did

```
(3 * u.Jy / u.beam).to(u.K, equivalencies=u.brightness_temperature(0.01 * u.sr, 3 * u.mm))
```

? That is, the value in the left is actually per beam but we just don't put it because it's not a real unit? If so, maybe we should seamlessly support the second case too?

**Comment by keflavich** [comment]
Yes, that's essentially right.  What we really want is something like
```
beam = 0.01 *u.sr
(3*u.Jy/beam).to(u.K, equivalencies=u.brightness_temperature(beam, 3*u.mm))
```
and then, when reading from a FITS header with `BUNIT='JY/BEAM'` (capitalized, unfortunately...), the `beam` unit should be parsed from the `BMAJ/BMIN` parameters.

**Comment by keflavich** [comment]
The point is that a `beam` unit should have to be equivalent to `u.sr` to be valid; `u.beam` is just a non-functional placeholder right now.

**Comment by astrofrog** [comment]
Right - I guess that in the mean time, would there be any harm in supporting the placeholder being there, i.e. supporting:

```
(3 * u.Jy / u.beam).to(u.K, equivalencies=u.brightness_temperature(0.01 * u.sr, 3 * u.mm))
```

So the beam area is still passed to ``brightness_temperature`` but the code is more readable because one sees that the quantity on the left is per beam?

**Comment by keflavich** [comment]
I think that's OK, but it's still more explicit and clear (and therefore better?) to use the appropriate beam on both sides, though I note that it doesn't work right now, even with the dimensionless_angles equivalency:
```
beam = 0.01*u.sr
(5*u.Jy/beam).to(u.K, u.brightness_temperature(beam, 5*u.GHz)+u.dimensionless_angles())
```

**Comment by mhvk** [comment]
@keflavich - equivalencies are not recursive, i.e., the test for whether an equivalency can be applied is simply whether the unit of the quantity is equivalent to the input (or output) unit of the equivalency, *without* applying other equivalencies. So, to get this to work, one would have to add an equivalency to the list returned by `brightness_temperature`.
```
    return [(astrophys.Jy, si.K, convert_Jy_to_K, convert_K_to_Jy),
            (astrophys.Jy/astrophys.beam, si.K, convert_Jy_to_K, convert_K_to_Jy)]
```
(note: not sure whether or not this is a good idea)

**Comment by bsipocz** [comment]
🎉  https://github.com/astropy/astropy/pull/5173#issuecomment-239229275 has fixed this.
