### ISSUE TITLE
Quantity.to(u.one) should return a Quantity

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3464]
It looks like ``Quantity.to(u.one)`` returns a float when it should return a dimensionless quantity:

```
In [23]: (u.sr / u.arcsec**2).to(u.one)
Out[23]: 42545170296.1522
```

**Comment by eteq** [comment]
Actually, I think this is expected behavior, @astrofrog.  The following does what you want:
```
In [11]: (1*u.sr / u.arcsec**2).to(u.one)
Out[11]: <Quantity 42545170296.1522>
```
The distinction is that ``(u.sr / u.arcsec**2).to(u.one)`` is converting *units*, not quantities.  And `Unit.to` returns the scale factor, rather than  new unit.

**Comment by embray** [comment]
I'm inclined to agree with @eteq.  `u.one` is itself a unit, so this is no different than, say `u.m.to(u.pc)`.

`u.one` was only added as a shorthand for `u.dimensionless_unscaled`.

**Comment by astrofrog** [comment]
Oops, for some reason I thought I was dealing with a Quantity. Sorry for the noise.
