### ISSUE TITLE
Mention Cython version in the release procedures?

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3473]
We've generally been pretty loose about Cython versions--in large part because I don't think we use many advanced features of Cython that require the bleeding edge.  When building/releasing Astropy we also include a module called `cython_version.py` that saves what version of Cython was used to build the Cython sources.  So at least there is that.

I was just thinking for the sake of consistency we might want to standardize on something for releases.  I haven't investigated enough to have any particular feelings about _what_ we should standardize on.  Maybe just "the most recent release" is good enough.  In which case `pip install Cython --upgrade` should be added to the release instructions.

**Comment by bsipocz** [comment]
@eteq - what do you think about this? Should we add ``pip install --upgrade Cython`` to the release docs and then close this issue?

**Comment by pllim** [comment]
No one has complained about this for 5 years. Shall we just close without action?

**Comment by bsipocz** [comment]
The mention of using the latest cython release for releasing was in the release docs, but got removed at the latest overhaul of infra:
See point 6: https://docs.astropy.org/en/v4.0/development/releasing.html
vs https://docs.astropy.org/en/latest/development/releasing.html

**Comment by pllim** [comment]
Hmm! Looks like @astrofrog removed it in #9726 . Given his availability time frame, I'll keep this open for now until he can respond. There is no rush.

**Comment by bsipocz** [comment]
The other presumption was that  the oldest numpy version was needed to be installed when making the sdist as using newer ones caused some troubles a few times. As I see though it was known only, but never got written down in the release docs.

**Comment by astrofrog** [comment]
We now no longer ship the generated C code so this issue is now moot. Cython gets installed as specified in pyproject.toml automatically when pip installing from source.
