### ISSUE TITLE
Improve scale validation infrastructure in Time

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#349]
The current `Time` code correctly does validation of the input scale in all cases (AFAIK).  But it is done in a somewhat fragile way that should be improved.  

The issue is that in some cases (mostly string formats) the validation needs to be deferred until after the format class has determined whether or not the input values are appropriate.  This is to allow for auto-format detection.  In other formats the scale validation is done in `set_jds()`.  If a new TimeFormat subclass is created the coder needs to know where to do the validation.  So it's not very clean at this point, though as said all existing code does work.

**Comment by mhvk** [comment]
@taldcroft - cleared the milestone here. Agree in principle that this could be improved...
