### ISSUE TITLE
Fix deprecated calls to `log.warn`

### ISSUE THREAD

**Issue by barentsen** [astropy/astropy#3495]
`logger.warn` has been deprecated in favour of `logger.warning` in Python 3.3 (cf. #624).  The code base contains a few lines which have not been updated in this respect.  I've already opened a PR to fix `vo/samp/hub.py` because it triggered a testing failure (cf. #3493), but didn't have time to fix these others yet:

```
$ grep -rnw astropy -e "log.warn("
astropy/io/fits/scripts/fitscheck.py:139:        log.warn('BAD %r %s' % (filename, remainder))
astropy/io/fits/scripts/fitscheck.py:144:                log.warn('MISSING %r .. Checksum not found in HDU #%d' %
astropy/io/fits/scripts/fitscheck.py:148:                log.warn('MISSING %r .. Datasum not found in HDU #%d' %
astropy/io/fits/scripts/fitscheck.py:163:        log.warn('NONCOMPLIANT %r .. %s' %
astropy/io/fits/scripts/fitscheck.py:219:        log.warn('%d errors' % errors)
astropy/vo/samp/hub.py:191:                log.warn("Port {0} already in use. Impossible to run the "
astropy/_erfa/setup_package.py:53:            log.warn('WARNING: The autogenerated wrappers in astropy._erfa '
astropy/_erfa/setup_package.py:67:            log.warn("WARNING: jinja2 could not be imported, so the existing "
astropy/__init__.py:241:            log.warn('You appear to be trying to import astropy from '
```

**Comment by astrofrog** [comment]
For whoever fixes this: we should be using ``warnings.warn`` and include ``AstropyWarning`` as the warning type.

**Comment by barentsen** [comment]
@astrofrog Out of curiosity, what is the difference?

**Comment by embray** [comment]
That actually depends.  Most of the above cases are in shell scripts where `log.warn` is being used to write error messages to stderr and is not a code warning.
Likewise the one in `astropy.__init__` I think was intentional.

**Comment by astrofrog** [comment]
Possible patch in https://github.com/astropy/astropy/pull/3503
