### ISSUE TITLE
Comments of "REMOVE in astropy 0.5"

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#3500]
There are a few  remaining ``# REMOVE in astropy 0.5`` comments in the code (in config, units and utils), I guess those need to be removed.

**Comment by mdboom** [comment]
I think the ones in `config` at least we should wait one more cycle for the affiliated packages to catch up.

**Comment by astrofrog** [comment]
@mdboom - should we do this in 1.1, or wait until 1.2?

**Comment by astrofrog** [comment]
Not critical, so changing milestone to 1.2

**Comment by astrofrog** [comment]
I think this is all done, so closing this.
