### ISSUE TITLE
Setting mask on non-masked column should raise error

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3505]
In the following example, the table is not masked, so I feel that for safety we should raise an ``AttributeError`` for the last statement:

```
In [2]: t = Table()

In [3]: t['a'] = [1,2,3]

In [4]: t['a'].mask = [True, False, True]
```

cc @taldcroft @mhvk

**Comment by taldcroft** [comment]
Agreed.

**Comment by taldcroft** [comment]
Seems like a `__setattr__` on `Column` should do the trick.  It should just look for `item == 'mask'` and raise an exception, otherwise fall through to the super method.  Offhand I don't think there should be any performance implication, but we need to be sure.

**Comment by taldcroft** [comment]
Can leave this open for GSOC PR.

**Comment by sahmed95** [comment]
What message should be issued after AttrributeError is raised ? Will this snippet do the job in astropy/table/column.py ?

```python
def __setattr__(self,item,value):
        if item == "mask":
            raise AttributeError("Setting mask on non-masked column")
        else:
            return super(Column, self).__setattr__(item, value)
```
I got this output with astrofog's test case : 

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    t['a'].mask = [True, False, True]
  File "/home/dev/astropy/astropy/table/column.py", line 780, in __setattr__
    raise AttributeError("Setting mask on non-masked column")
AttributeError: Setting mask on non-masked column

**Comment by royalharsh** [comment]
Changes should be column.py and test_column.py ?

**Comment by mvnnn** [comment]
that issue is still open? i want to work on this.

**Comment by taldcroft** [comment]
@mvnnn - Go ahead.  You can take over from #3522 and #4494.  Both of those were not implemented correctly.
