### ISSUE TITLE
Error creating a Table with a single column

### ISSUE THREAD

**Issue by barentsen** [astropy/astropy#3510]
This works fine:
```Python
In [1]: from astropy.table import Table
In [2]: tbl = Table(names=('a'), dtype=('f'))
```

but this crashes:
```Python
In [3]: tbl = Table(names=('a'), dtype=('f4'))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-b85d131083bd> in <module>()
----> 1 tbl = Table(names=('a'), dtype=('f4'))

/home/gb/dev/astropy/astropy/table/table.py in __init__(self, data, masked, names, dtype, meta, copy, rows)
    302         names = [fix_column_name(name) for name in names]
    303 
--> 304         self._check_names_dtype(names, dtype, n_cols)
    305 
    306         # Finally do the real initialization

/home/gb/dev/astropy/astropy/table/table.py in _check_names_dtype(self, names, dtype, n_cols)
    392             raise ValueError(
    393                 'Arguments "names" and "dtype" must match number of columns'
--> 394                 .format(inp_str))
    395 
    396     def _set_masked_from_cols(self, cols):

ValueError: Arguments "names" and "dtype" must match number of columns
```

... which looks like a cheeky little :beetle:.
(This is using the current master branch on Python 3.4.2.)

**Comment by barentsen** [comment]
Defining `dtype` using a list instead of a tuple doesn't trigger the problem by the way:
```Python
In [4]: tbl = Table(names=('a'), dtype=['f4'])
```

**Comment by taldcroft** [comment]
@barentsen - you fell into a little Python trap, namely hoping that `('f4')` is a tuple, but in fact that is just a string.  In this case the string is iterable and has a length of 2, so the code was fooled.  The following specifies a tuple and works as expected:
```
tbl = Table(names=('a'), dtype=('f4',))
```
Probably the code *should* do some better input validation here and make sure that a genuinely list-like object is passed in.

**Comment by barentsen** [comment]
```Python
In [27]: type(('x'))
Out[27]: str
```
Wow. That is ... surprising!

**Comment by embray** [comment]
Have we had a policy of whether or not to allow comma-separated strings for names like `'a,b,c'`.  In this case a string like `'a'` would still be interpreted as a "list" of names containing a single item.
I'm -0.5 on allowing this functionality at all, as it makes parsing tricky if the user wants, say, a column with a comma in the name (an outlandish corner case but still...).

Just wondering if that idea has been discussed before.  Not sure.

**Comment by taldcroft** [comment]
@embray - I'm also :-1: on allowing comma-separated values where we now require a list.  It just opens up problems, the first of which you just mentioned.

**Comment by taldcroft** [comment]
Closing this issue now since this is not really a problem with astropy Table.  But hopefully someone will do #3511.

**Comment by pllim** [comment]
Yeah, `(x)` is not a tuple but `(x,)` is. That sneaky comma!
