### ISSUE TITLE
Improve validation of inputs for Table

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#3511]
Inspired by #3510, it would be good to have better validation of all inputs when creating a table.

**Comment by sornars** [comment]
What additional validation steps were you thinking of? Most of the init parameters for Table have decent checks - the linked issue is more of a Python syntax issue as currently the names and dtypes parameters both check to see the input is iterable. From what I can imagine, strings are pretty much the only iterable that would fail. Do you simply want to assert that dtypes and name are not strings and raise a more descriptive exception if they are?

The only other potential input validation would be to ensure that the meta parameter is a dictionary before assigning it to self.meta.

**Comment by taldcroft** [comment]
@sornars - I think you have hit it just right, so a more descriptive error message if `dtype` or `names` are strings, and check that `meta` is a dict.
