### ISSUE TITLE
Update release procedures

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#3516]
This issue contains a list of some changes we need to make to the release instructions - I encountered these mainly while doing v1.0 Release Candidates.  @astrofrog can add more for the actual v1.0 release, and once we're done with that I can issue a PR to actually do the updates.
- [ ] Add a step to check that astropy_helpers is up-to-date
- [ ] Note in the step that mentions `git clean -dfx` if you're not doing a completely fresh clone that  astropy_helpers also needs to be cleaned.
- [ ] Remove use of testpypi at all now that pip requires `--pre` to get non-release versions.
- [ ] Change the mention of suggest_backports to point to the astorpy-tools version, and also mention that the magic incantation `https://github.com/astropy/astropy/pulls?q=is%3Apr+is%3Aunmerged++closed%3A%3E%3D2015-01-27+` can be used to check for things that github calls unmerged but were actually manual merges.
- [ ] Change references to  `sdist` -> `build sdist` (for safety's sake - not always necessary, but can be helpful if something's slightly out-of-order)
- [ ] Fix up the description of updating the web site - it's out-of-date and based on the old version of the web site.
- [ ] Update the instructions to use `setup.py upload --sign` when uploading to PyPI.

**Comment by embray** [comment]
The second-to-last bullet point was already addressed in #3295 (in general I always look at the release procedures in the "latest" docs build since I do update it often enough).  :+1: to the rest.

**Comment by embray** [comment]
Another bullet point to add though--before step 17, of creating the test sdist, we should run git clean again.  In a way though this is really a bug in astropy-helpers.  It should check whether the git hash has been updated or not, and write a new version.py if so.

(The issue here is that version.py was already generated in step 7, but after running the release script there is a new git commit for the release itself, and that's the one the githash should *actually* point to.)

**Comment by embray** [comment]
Added another bullet point to sign source releases posted to PyPI, which we haven't done in the past (and that setuptools now makes easy).

**Comment by eteq** [comment]
@astrofrog - do you have anything to add here from the release for 1.0 ?

**Comment by embray** [comment]
Apparently we also need to make sure to get builds posted to binstar.

It would be really great if we could automate many of those post-release steps somehow.

**Comment by eteq** [comment]
@embray - is that possible with zest?  Or should we consider dropping zest and replacing it with our own scripts? (I've tried hacking on the zest stuff a bit but found it a bit complicated...)

**Comment by embray** [comment]
Yes and no, but more the the point I think something like that is outside the scope of any release scripts, and instead is something that should be kicked off more or less automatically when a new release is posted.

**Comment by bsipocz** [comment]
This is being addressed by #5640
