### ISSUE TITLE
time.Time __bool__ and __len__ unexpected behaviour

### ISSUE THREAD

**Issue by mtbannister** [astropy/astropy#3520]
I noticed this behaviour of time.Time in 0.4.4 and was able to replicate it in 1.0:
````python
>>> t = time.Time('2015-01-01')
>>> len(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/time/core.py", line 940, in __len__
    return len(self.jd1)
TypeError: object of type 'float' has no len()
````
For behaviour consistent with the standard Python `datetime.datetime`, `len(t)` should instead throw an `AttributeError`.

This further comes in when one tries:
````python
>>> if t:
...     print(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/time/core.py", line 940, in __len__
    return len(self.jd1)
TypeError: object of type 'float' has no len()
````

For behaviour consistent with `datetime`, `bool(t)` for a `time.Time` would always return `True`.

**Comment by embray** [comment]
Yeah, that should be fixed.  @taldcroft, can you think of any reason a `Time` object would ever be False in a boolean context?  I can't really... it should probably always be True.

**Comment by taldcroft** [comment]
Well in 1.0 you can actually create an empty Time object (don't remember if that was possible before), so in that case you probably want the boolean context to be False.  Right now if you have an array-valued `Time` it returns True.  So the only issue is with a scalar-valued `Time`, where indeed it should return True (and currently raises an exception).  So *that* should be fixed.

About the length, basically `Time` behaves like a numpy array, not `datetime()`.  From this perspective `Time` is doing the right thing by throwing an exception for a scalar-valued object.

**Comment by embray** [comment]
In the case of an "empty" time object ti's basically behaving like a Numpy array right?  Then in that case shouldn't `bool(timeobj)` raise a `ValueError` (regardless of whether it's empty)?

For scalars I agree `bool(timeobj)` should definitely always return True (even if the underlying float values are zero--that's still a valid time :))

**Comment by mhvk** [comment]
@taldcroft - @mtbannister wrote that he was surprised about a `TypeError` being thrown for a scalar Time rather than an `AttributeError`, not that an exception was raised at all. Though I think it is good to stick with what we have, as it follows `numpy` and other numerical constructs (e.g., `len(1.)` also raises a `TypeError`).

I do agree that a scalar time should evaluate to `True`. Since *any* time evaluates to `True` (unlike `ndarray`, where a scalar zero valued one evaluates to `False`), I think also array-valued times should evaluate to `True`. As for the empty one:
```
In [7]: bool(np.array([]))
Out[7]: False
```
so I think an empty `Time ` should evaluate to `False` as well. That is `bool(time)` equals `time.shape != ()`.

**Comment by taldcroft** [comment]
> That is bool(time) equals time.shape != ()

@mhvk - agree on all points, and in fact I wrote almost exactly this but apparently forgot to hit "Comment" before running off to a meeting.

**Comment by mhvk** [comment]
See #3530 for an implementation of `Time.__bool__`.

**Comment by mtbannister** [comment]
@taldcroft re. throwing an exception for a scalar-valued object. Would it be possible to raise a more informative exception? "Scalar-valued time.Time.jd1 rather than vector: type 'float', which has no len()'?

**Comment by mhvk** [comment]
@mtbannister - ok, I added a quick commit to do just that: https://github.com/mhvk/astropy/commit/88963a38ee4af5c0bb0c122387481e1fdaea9e77
