### ISSUE TITLE
Add a new time format that represents time as year, month, day, hour, min, sec arrays

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#3527]
It would be good to be able to initialize a `Time` object from a set of (potentially large) ndarrays containing the year, month, etc.., or likewise get those values out from a `Time` object.  This should be a fairly straightforward format to implement since it is just a very thin wrapper around `erfa_time.dtf_jd` (and vice-versa).

Exact interface TDB in discussion here.  Three possibilities include:
- dict `{'year': year_array, ...}`
- tuple `(year_array, month_array, ...)`
- `Table` object with appropriately named columns

I would vote for `dict`.

Marked as Package-intermediate, but implementing this would mostly be a matter of modifying an existing format, probably `TimeDecimalYear`.

**Comment by astrofrog** [comment]
I guess dict provides more flexibility because one might want to do ``ymd``, ``ymdhms``, ``ymdhm``, etc.

As a side note, I wonder whether there is also a possibility of using Numpy's datetime, that is ``Time`` would accept a ``datetime`` array.

**Comment by taldcroft** [comment]
> I guess dict provides more flexibility because one might want to do ymd, ymdhms, ymdhm, etc.

All of those would be allowed by all the three options.  The only that that dict would allow that tuple would not is where you supply e.g. seconds but not minutes.  But anyway I do think that dict is the easiest and most clear (because every element is explicitly tagged with a label).

I'm not too familiar with numpy datetime apart from vaguely watching the years-long discussions to improve it.  In any case I think that would be distinct from this idea.

**Comment by mhvk** [comment]
I like the idea, but the choices depend a little on what usage one has in mind.  One I can immediately see is getting times out of some table one gets from, say, CDS. Since for that case one cannot guarantee particular names, the interface probably should allow input with a tuple:
```
times = Time((table['jaar'], table['maand'], table['dag']), format='ymd')
```
For output, `tuple` is not so nice, but it becomes better if one uses [named tuple](https://docs.python.org/2/library/collections.html#collections.namedtuple), allowing access via `t.year`, etc.
 
Of course, the above is not unique: one can circumvent the need for a tuple also by simply allowing input with a table or record array as long as the columns are in the right order. Indeed, if so, input would be about as simple as possible::
```
times = Time(table['jaar', 'maand', 'dag'], format='ymd')
```

Anyway, just reasons to wonder whether `dict` is indeed the best format. What other uses are envisioned?

**Comment by taldcroft** [comment]
@mhvk - sure, the way you put it would work fine as well.  In fact there is no reason we necessarily need to choose now between table input vs. tuple since we can reliably detect this on initialization.  For output I like the idea of a named tuple.  [EDIT: but see below]

Do we really need the `format='ymd'` keyword?  If we just insist that the order is fixed, like the function arg: `f(year, month=1, day=1, hour=0, min=0, sec=0)`.

Now I just thought of one little complication regarding the output.  For all the other formats the `value` is something that is indexable in the same way as the input (i.e. has the same shape).  But returning a tuple of ndarrays breaks that idiom, and in particular would break things if the user chose to put that object as a mixin column.  From that perspective returning a `Table` for `value` works better, and in the scalar case the best analog (from user API perspective) would be a Table Row.

Summary:

- For input allow any of the 3 possibilities, tuple, table, dict.  Tuple and table would use order to determine content, while for dict would require the correct key names (year, month, ..).
- For output use a Table for an array-like Time, else Table Row

**Comment by mhvk** [comment]
@taldcroft - agreed that it should be indexable!  That leaves `Table` or `np.recarray`. The advantage of the latter is that it allows field access, but I don't think this outweighs the convenience of using our own astropy class.

**Comment by astrofrog** [comment]
@mjuric - are you interested in taking a stab at this?

**Comment by taldcroft** [comment]
@mhvk - I think `recarray` is somewhat deprecated and has seen only a handful of commits in the last 5 years.  I also think that field access of columns is just a bad idea since you mix your arbitrary column names in with 70-odd other methods/attributes from ndarray.  If you use `dat.some_name` in your code, there is no guarantee in the future that ndarray won't add the `some_name` attribute and break your code.

In any case, this being astropy, `Table` would be the answer.  :smile:

**Comment by mhvk** [comment]
Agreed. The named aspect might actually be more relevant for `Time` itself, but no need to let that distract us here. Another aspect I like about the `Table` that we could easily add columns for the location as well.

Even if the format can be auto-guessed, it does need a name though! So, `times.<what>` yields a table? Maybe `split`?

**Comment by taldcroft** [comment]
`times.ymdhms`?

**Comment by mhvk** [comment]
@taldcroft - one small issue: with a `Table`, indexing of the output will not work for multi-dimensional `Time` instances. In that sense, it may still be best to stick with `ndarray` output (i.e., a structured array). Of course, nothing would stop anyone from doing `Table(times.split)`.

**Comment by taldcroft** [comment]
@mhvk - I must be missing something here.  `Table` can handle any data structure that an `ndarray` structured array can hold (and more!).

**Comment by mhvk** [comment]
@taldcroft - I just meant the indexing: Suppose I define
```
t = Time(np.arange(50000, 50004).reshape(2,2), format='mjd')
```
then I could happily do 
```
t.iso
# array([['1995-10-10 00:00:00.000', '1995-10-11 00:00:00.000'],
#        ['1995-10-12 00:00:00.000', '1995-10-13 00:00:00.000']], 
#       dtype='<U23')
t.iso[0, 1]
# '1995-10-11 00:00:00.000'
```
But with `t.split` returning a `Table`, I could only index the first dimension, i.e., I could not similarly get a single element with `t.split[0, 1]`, but rather I would have to do `t.split['year'][0, 1]` or `t.split[0]['year'][1]`, etc.:
```
table = Table([[[1995, 1995], [1995, 1995]], [[1,2],[3,4]]], names=('year', 'day'))
table[0, 1]
# ValueError: Illegal type <class 'tuple'> for table item access
```
(Possibly we should allow this kind of access, though it would seem tricky...)

**Comment by taldcroft** [comment]
@mhvk - doing `t.split[0, 1]` would not work with a structured array or any of the other proposed alternatives.

BTW, whatever we decide on for a name, I'm :-1: on `split` because it really confuses me every time I see it.  There is the strong association with the string or other *methods* and so I see `t.split[0, 1]` and my brain does a double take.

**Comment by mhvk** [comment]
@taldcroft - actually, with a structured array indexing would work as expected (indeed, the first attempt at vectorising all the `erfa` routines had structured arrays as outputs):
```
t_struct = np.array([[[1995, 1], [1995, 2]], [[1995, 3],[1995,4]]]).view([('year', 'i8'), ('day', 'i8')])
t_struct
# array([[[(1995, 1)],
#         [(1995, 2)]],
#
#        [[(1995, 3)],
#         [(1995, 4)]]], 
#       dtype=[('year', '<i8'), ('day', '<i8')])
t_struct[0, 1]
# array([(1995, 2)], 
#      dtype=[('year', '<i8'), ('day', '<i8')])
```

**Comment by mhvk** [comment]
p.s. Agreed not to call it `t.split` any more! Fine to keep `t.ymdhms` unless we come up with something better.

**Comment by taldcroft** [comment]
@mhvk - yes, I forgot that a structured array can have a top-level shape instead of just columns with a shape.  With that in mind it does seem to make sense to use a structured array in this context.

**Comment by taldcroft** [comment]
Summary:

- High priority, let's do this.
