### ISSUE TITLE
GitHub releases highlights wrong version

### ISSUE THREAD

**Issue by 153957** [astropy/astropy#3528]
Take a look at: https://github.com/astropy/astropy/releases

This prominently highlights version 0.3rc1!
I assume that this is either because of the 'Pre-Release' checkmark,
release notes or the attached package/binary.
Since it is such an old release and not even a full version release,
perhaps the Pre-Release label and package can be removed from it.
That would probably highlight the newer versions better.

**Comment by Cadair** [comment]
It looks like the other tags have not been converted to GH releases.

**Comment by astrofrog** [comment]
Maybe we should simply remove the files for the 0.3 release candidate since it's no longer needed.

**Comment by Cadair** [comment]
@astrofrog you should be able to convert the 1.0.0 tag to a github release under releases, and then it will have priority.

**Comment by 153957** [comment]
@Cadair Which would have to be done for all newer versions as well.
If you do not add any github releases the new releases still show up in correct order and priority (well maybe someone might not see/understand the 'rc' part of a version). And release notes are already available in the docs.

**Comment by astrofrog** [comment]
@Cadair - we don't generally use GitHub releases since all the releases are on PyPI and we don't want to provide tar files for all releases in two different places.

@eteq - what do you think?

**Comment by embray** [comment]
We don't use it, so any files on there should just be removed.

**Comment by Cadair** [comment]
underneath it uses tags, and provides a source tarball per git tag. The large highlighted releases are one that have been punched in through the web UI I think.

**Comment by embray** [comment]
Weird.  I removed the source upload and the title, and it still insists on highlighting that one *shrug*

**Comment by 153957** [comment]
Perhaps you need to 'delete' the release:
https://help.github.com/articles/editing-and-deleting-releases/
The actual git tag should remain. (I hope..)

**Comment by embray** [comment]
That did the trick.  Thanks, @153957 .  I believe if we want to use that feature in the future it's fine, though we should make it part of the release procedure (it could even be automated).  I don't see much point though since being a Python project all releases are posted on PyPI.  I could see this feature being more useful for other types of projects that don't have that sort of infrastructure available to them already.

**Comment by eteq** [comment]
@embray @astrofrog @153957 My feeling right now is agreeing with @embray - github releases fullfill similar needs as PyPI but PyPI is of course better for Python packages.  So I don't see the need to do github releases until there's some critical added value.
