### ISSUE TITLE
[astropy.io.votable.tree] Link class doesn't provide name attribute

### ISSUE THREAD

**Issue by calders** [astropy/astropy#3531]
The VOTable 1.2 standard (ref.: http://www.ivoa.net/documents/VOTable/20091130/REC-VOTable-1.2.html#ToC22) describes that the LINK tag can contain a "name" attribute:

>  In addition to the referencing href attribute and to the naming name and ID attributes (see name and ID), [...]

It seems not supported by astropy:

>  AttributeError: 'Link' object has no attribute 'name'

**Comment by mdboom** [comment]
Indeed, you are correct, though according to the schema, it seems the `name` attribute is an enumerated type on `LINK`, and can only be one of `query`, `hints`, `doc`, or `location`.

I'll work up a PR shortly.

**Comment by mdboom** [comment]
This is Mark Taylor's response on the VOTable mailing list:

> unless anyone wants to argue otherwise, I think the schema should be treated as authoritative here, and the text is at fault. This text was rewritten for VOTable 1.3 (http://code.google.com/p/volute/source/detail?r=1877), and the VOTable 1.3 document no longer mentions any name attribute for LINK.

So, therefore, I'm going to close this bug.  If you want to share your use case, I'm happy to help brainstorm a workaround solution, but I don't think astropy should deviate from the intended standard here.
