### ISSUE TITLE
table.Table.sort() overrides Table.write(names=) arguments

### ISSUE THREAD

**Issue by mtbannister** [astropy/astropy#3532]
Showing this with the example from the docs, as it's shorter than the data table I found this behaviour in:

``` python
t = Table([['Max', 'Jo', 'John'], 
                 ['Miller','Miller','Jackson'], 
                 [12,15,18]], 
                 names=('firstname','name','tel'))
print t
firstname   name  tel
--------- ------- ---
      Max  Miller  12
       Jo  Miller  15
     John Jackson  18
t.sort(['name','firstname'])
print t
firstname   name  tel
--------- ------- ---
     John Jackson  18
       Jo  Miller  15
      Max  Miller  12
```

But when the writer is asked instead to order the columns differently for output, it ignores the keyword.

`````` python
s = StringIO.StringIO() 
t.write(s, names=['tel', 'name', 'firstname'], format='ascii.aastex')
print(s.getvalue())
\begin{deluxetable}{ccc}
\tablehead{\colhead{tel} & \colhead{name} & \colhead{firstname}}
\startdata
John & Jackson & 18 \\
Jo & Miller & 15 \\
Max & Miller & 12 \\
\enddata
\end{deluxetable}````
``````

**Comment by taldcroft** [comment]
@mtbannister - it is admittedly a little confusing, but from the docs:
```
names: list of names corresponding to each data column
    Define the complete list of names for each data column. This will override names 
    determined from the data table (if available). If not supplied then use names from 
    the data table or auto-generated names.
```
So when you are writing a table the `names` argument only serves to override the existing names.  (You can see that this happened in your original example).  This exists because the lower-level routine `astropy.io.ascii.write` can take as input something without column names (i.e. a pure Python list of column arrays).

So what you should be doing in this case is:
```
t['tel', 'name', 'firstname'].write(s, format='ascii.aastex')
```

**Comment by embray** [comment]
I guess that could be reworded to better emphasize that the only purpose of that argument is to provide different column names when writing the table (overriding the existing ones).  I think it *does* say that but it's a bit muddled? (I think the first sentence especially is confusing)

**Comment by cosmicoder** [comment]
Hi! I am trying to make a pull request for the same but I am not able to find the documentation page referred to by @taldcroft. Would anyone be able to point me to it?

**Comment by pllim** [comment]
The issue is 5 years old. Maybe no longer relevant? If you are still interested to pursue this, perhaps try to reproduce the original problem first but with the dev version. Thanks!

**Comment by taldcroft** [comment]
This is just a doc fix here: https://docs.astropy.org/en/latest/io/ascii/write.html#parameters-for-write.

I would suggest:
```
names: list of output column names
    Define the complete list of output column names to write for the data table,
    overriding the existing column names.
```
