### ISSUE TITLE
astropy.__version__ is '1.0' rather than '1.0.0'

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#3539]
This breaks things like this:

```python
LooseVersion(astropy.__version__) >= LooseVersion('1.0.0')
Out[11]: False

astropy.__version__
Out[12]: u'1.0'
```

**Comment by Cadair** [comment]
To be fair, there is some weird behaviour from distutils here:

```python
LooseVersion(u'1.0.0') >= LooseVersion('1.0.0')
Out[16]: True

LooseVersion(u'1.0') >= LooseVersion('1.0.0')
Out[17]: False

LooseVersion(u'1.0') >= LooseVersion('1')
Out[18]: True
```

**Comment by embray** [comment]
Yeah, you should use the version comparison from setuptools instead (see for example https://github.com/astropy/astropy/blob/master/astropy/utils/introspection.py#L148).  Distutils is way old and outdated on this, and only setuptools (currently) supports PEP-440 compatible versions.  FWIW PEP-440 [has to say on this](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers):

>  All numeric components MAY be zero. Except as described below for the release segment, a numeric component of zero has no special significance aside from always being the lowest possible value in the version ordering

I believe there are plans to eventually fix this up on the distutils end now that this is the accepted standard.  But updating distutils is hazardous and undertaken with a great deal of caution.

**Comment by astrofrog** [comment]
@embray - so just to check, we are ok with having the version number be unicode in Python 2.x? (quite unusual, no?)

**Comment by embray** [comment]
It's mostly harmless.  Not too unusual.

**Comment by mdboom** [comment]
@astrofrog does make a good point about Unicode, though.  disutils.version.LooseVersion on Python 2.x has a "shortcoming" that only byte strings are supported...

**Comment by embray** [comment]
Oh, I didn't notice that.

**Comment by embray** [comment]
Seems to work for me?
```python
Python 2.6.9 (unknown, Dec 26 2014, 16:29:10) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.version import LooseVersion
>>> LooseVersion(u'1.2.1') > LooseVersion(u'1.2.0')
True
>>> LooseVersion(u'1.2.1') > LooseVersion('1.2.0')
True
>>> LooseVersion(u'1.2.1') < LooseVersion(u'1.2.0')
False
>>> LooseVersion(u'1.2.1') < LooseVersion('1.2.1')
False
```

I said is much because Python 2 code where `unicode` strings are handled much differently from any other string is uncommon (hence being a common source of mistakes, but not really a problem here...)
