### ISSUE TITLE
io.fits: Corrupted data in saving HDULists

### ISSUE THREAD

**Issue by GJSPagomenos** [astropy/astropy#3540]
After saving an HDU list of 48 FITS BinTableHDU files, reloading this data seems to lead to corruption.

![corrupt5](https://cloud.githubusercontent.com/assets/11162309/6331948/54b6e8e0-bb7a-11e4-95be-14a7414d85e5.JPG)

The error message received is long and seems to lead to a file being saved anyway. The error shown is: "ValueError: mmap length is greater than file size".

![corrupt2](https://cloud.githubusercontent.com/assets/11162309/6332004/a3828ae2-bb7a-11e4-9c08-ebdb4925ff76.JPG)

![corrupt3](https://cloud.githubusercontent.com/assets/11162309/6332007/a7e04656-bb7a-11e4-85ca-e3f613c47999.JPG)

![corrupt4](https://cloud.githubusercontent.com/assets/11162309/6332010/ad19541e-bb7a-11e4-84f5-eae38bed0d23.JPG)

What comes out is a file which is considerably shorter, the individual table names gone.

![corrupt1](https://cloud.githubusercontent.com/assets/11162309/6332024/cfea6f46-bb7a-11e4-914d-b80907ddac46.JPG)

Only these 11 BinTableHDU files exist. The FITS files did not originally follow the standard, so the list (in this example named "nod1") had been modified with "nod1.verify(fix)". 

The code is being run on a virtual Linux system on a Windows computer. The version of Python being used is Enthought Canopy v.1.4.1 (64-bit). The version of Astropy used is v.0.4.4-1.

**Comment by embray** [comment]
Hi @GJSPagomenos.  As I wrote on the SO issue the problem with reading the file is clear, in that the original file was never fully written out in the first place.  Hence the warning that the file has been truncated from its expected size.  In those cases it will try its best to read as much as it can, but beyond a certain point all bets are off.

I would be more interested in where the original file came from and how exactly it was created and written, since "ValueError: mmap length is greater than file size" is unusual for writing a FITS file and I'm not sure how to reproduce it otherwise.

**Comment by GJSPagomenos** [comment]
Hi @embray. Thanks for your replies, it's very much appreciated!

The data originally came from the Spitzer Space Telescope archives as FITS image files, which were then combined and reduced from a program called "SMART" (a Linux-based program designed in IDL). I hope that is useful.

**Comment by embray** [comment]
@GJSPagomenos you wrote "After saving an HDU list of 48 FITS BinTableHDU files" you then got a traceback.  What were the actual steps you took to get to that point?  Does opening the original file as returned by SMART have any issues, or is it corrupt to begin with?

**Comment by GJSPagomenos** [comment]
@embray As far as I am aware, there have been no issues with the SMART program, though I know one of the people who made it so I could definitely ask them whether they have encountered any bugs. I am able to open the image files acceptably, and those that can be read by Astropy seem to be okay.

In terms of actually getting to that stage, the process involved combining several FITS images (in terms of basic calibration data files), "cleaning" them through a process called IRSClean which is also written in IDL, and exporting them as FITS table files from there. These were opened with io.fits and the BinTableHDU components of each of them were appended on to one of the files.

Just thinking (probably naively)... Would this disregard of the FITS header make a difference? It corresponds to one particular table file, so by appending 47 more there may be issues?

In the meantime I shall ask the person who helped create the reduction program.

**Comment by embray** [comment]
In your screenshot there's a line where you wrote:
```python
nod1.writeto('SLnod1a.fits')
```
which resulted in a traceback, and of course a not fully written file.  I'm mostly interested in what `nod1` is and how it was created.

**Comment by embray** [comment]
Is it possible you opened a FITS HDU from another file and then made modifications to its header before reading the data in?

**Comment by embray** [comment]
This makes me think of another design flaw in pyfits' data model (related to the I/O refactoring I've been wanting to do, but a different angle I hadn't really fully considered).  Which is that internally the code uses the contents of the `Header` attached to an HDU to determine how to read that HDU's data.  But if the user is allowed to modify the `Header` at will before any attempt has been made to read that HDU's data, then almost anything can go wrong.

Really the `Header` object exposed to the user to play around with should be completely decoupled with the data structure determined from the original header in the original file.  This also goes back to my desire for a `FITSData` container object.  When opening an HDU this container would be created with all the information needed to read the data from some file.  It may still do so lazily, but it would be able to do so independently of what users subsequently do with that HDU.

**Comment by GJSPagomenos** [comment]
Ah! Sorry!

Right, the name `nod1` was applied to the list starting with the first of the 48 files, its header and table were included. The subsequent files were opened separately and only their BinTableHDU components were appended to `nod1`.

The list started as:

`nod1 = fits.open('J320_SL1.fits')`

subsequent tables were appended using the following technique:

`J320_SL2 = fits.open('J320_SL2.fits')
nod1.append(J320_SL2[1])`

The names were added after the whole list was present. I have noticed that this added a card to each of the BinTableHDUs (41 to 42) but not to the FITS header, as one would expect.

I have looked to see whether it is possible for any changes to have been made to the header from Python. I'm afraid I don't see how it would be possible for me to have modified it before reading the data in... I hope that helps...

**Comment by embray** [comment]
Yes, I think that helps.  When you say "the names were added after the whole list was present" do you mean that you just looped over the HDUList and set `hdu.name`?

It's weird that no other changes were made to the header since I don't see why this would break otherwise, but this gives me something to go on to try to reproduce this.  Something you might try in the meantime is rather than use the HDU objects directly out of the original file, try making a copy of them like:

```python
orig_hdu = J320_SL2[1]
nod1.append(fits.BinTableHDU(header=orig_hdu.header, data=orig_hdu.data)
```

Can say for sure that should *probably work as a workaround.

**Comment by GJSPagomenos** [comment]
Yes, pretty much. I added all the table files and just did "nod1[1].name = 'J320_SL1' " and the like after they were in the list.

Thank you very much for your time and patience, I shall try that tomorrow and let you know how it goes. :)

**Comment by adrn** [comment]
👋 Hi @GJSPagomenos - going through older issues and noticed this. If you still have a problem, could you please reopen this issue?
