### ISSUE TITLE
astropy.io.ascii.read - segmentation fault when using names

### ISSUE THREAD

**Issue by martynbristow** [astropy/astropy#3545]
Hi
I'm trying to run some code which worked on a previous astropy version but now won't work
I'm running astropy 1.0 on python 2.6.6
I'm trying to read a 3 line file and I get a Segmentation Fault.
This ONLY occurs it seems when I use the names keyword.

![dump](https://cloud.githubusercontent.com/assets/3476872/6351093/a4256044-bc30-11e4-8231-94a586785a86.png)

**Comment by martynbristow** [comment]
If anyone has any ideas to fix it would be appreciated.
It seems a major problem :/
I can't use the autoread of the header because the header has a '#' prefix which confuses the allaignment.
I'm going to try and rollback or fudge it

**Comment by astrofrog** [comment]
@martynbristow - what happens if you do simply ``format='tab'`` instead of ``fast_tab``?

cc @taldcroft @mdmueller

**Comment by mdboom** [comment]
Can you provide the file (or just enough of the file) so I can try to reproduce?

**Comment by martynbristow** [comment]
![dump](https://cloud.githubusercontent.com/assets/3476872/6351268/e58285fc-bc31-11e4-88a4-464122906de6.png)

If I use 'tab' i get stupid headers :/ because they are misaligned, i didn't make them.
Line 1 shows i can add each header in by hand but that will be a lot of rehashing because I use this in a few scripts.
The file is http://www.astro.ljmu.ac.uk/~mab/assets/catalog.csv

**Comment by mdboom** [comment]
@martynbristow: Can you try #3546 to see if it addresses your original issue?

**Comment by taldcroft** [comment]
@martynbristow - try this:
```
dat = ascii.read('catalog.csv', delimiter='\t')
dat = Table.read('catalog.csv', format='ascii', delimiter='\t')
```
There is a subtle difference between `format='tab'` and `delimiter='\t'`, namely that the former does not strip leading/trailing whitespace, while the latter does.  In your case you need that leading `\t` stripped.
