### ISSUE TITLE
Improve documentation of WCS.calc_footprint

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3551]
The ``WCS.calc_footprint`` method is very useful but I had to dig into the source code to understand the following:

* What the header is needed for (the header parameter should include a mention of what this is used for - namely to get NAXIS1 and NAXIS2)

* Why the function sometimes returns None without warning/error - basically if the image size is not found it just returns None, but really it should be returning an error saying the size could not be determined.

(not urgent, so this could be done as a GSoC starter project)

**Comment by vortex-ape** [comment]
Should it raise a ValueError or can it simply return a string?

**Comment by astrofrog** [comment]
@vortex-ape - I think it should raise an error, but maybe @mdboom and @nden can confirm?

If so, then the fix looks fine, and it will need an entry in the ``CHANGES.rst`` file (under 1.1, API changes)

**Comment by vortex-ape** [comment]
Is this fine? https://github.com/vortex-ape/astropy/commit/a72da05f67e0150970392a6e2f8dfcba9995b16e

**Comment by vortex-ape** [comment]
Created pull request: https://github.com/astropy/astropy/pull/3557
Sorry, I messed up. I should've studied the git workflow thoroughly.

**Comment by pllim** [comment]
`calc_footprint()` is what I was looking for! But I couldn't find it in the main WCS documentation.

**Comment by algerdnazgul** [comment]
Close issue?

**Comment by pllim** [comment]
Yeah, looks like it.
