### ISSUE TITLE
Mention Table interface in "Creating a New Table File" in FITS docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3552]
When people want to create a simple binary FITS table with no other HDUs, most users should probably just use the `Table` interface in Astropy instead and then write to FITS. Therefore I think in the `io.fits` docs (e.g. here: http://docs.astropy.org/en/stable/io/fits/index.html#creating-a-new-table-file) we should add a note to mention the Table interface, or maybe even provide an example.

(This is not high priority, so could be done as a starter GSoC project)

**Comment by embray** [comment]
:+1: (This is practically a FAQ).

**Comment by vortex-ape** [comment]
@astrofrog Can you review this? https://github.com/vortex-ape/astropy/commit/9ba1f2db49e2455557f883903685c9a73125f15d

**Comment by astrofrog** [comment]
@vortex-ape - what you have is a good start, but please open a pull request so that we can comment on it in detail (pull requests can be updated once opened)

**Comment by vortex-ape** [comment]
@astrofrog Created pull request https://github.com/astropy/astropy/pull/3558

**Comment by embray** [comment]
I don't think this should have been labeled package-novice now that I look.

**Comment by embray** [comment]
Per #3561, it would also be nice to clarify in the docs that even when using the "lower-level" interface it is not strictly necessary to go through the effort of creating `Column` objects manually--that data already in a Numpy array can be used to directly create a FITS table as long as it's in a structured array.  Direct use of the old interface is more of a FITS-ism, and only required in certain cases.

**Comment by vortex-ape** [comment]
@embray - What more benefits can I add?
