### ISSUE TITLE
Allow introspection of equivalencies

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#3563]
When an equivalency is created, if the generator accepted parameters, it is not possible to introspect the returned list to find out how it was created.  For example:

```
In [7]: u.spectral_density(5000*u.AA)
Out[7]:
[(Unit("erg / (Angstrom cm2 s)"),
  Unit("erg / (cm2 Hz s)"),
  <function astropy.units.equivalencies.converter>,
  <function astropy.units.equivalencies.iconverter>),
 (Unit("erg / (cm2 Hz s)"),
  Unit("erg / (cm2 s)"),
  <function astropy.units.equivalencies.converter_fnu_nufnu>,
  <function astropy.units.equivalencies.iconverter_fnu_nufnu>),
 (Unit("erg / (Angstrom cm2 s)"),
  Unit("erg / (cm2 s)"),
  <function astropy.units.equivalencies.converter_fla_lafla>,
  <function astropy.units.equivalencies.iconverter_fla_lafla>),
 (Unit("ph / (Angstrom cm2 s)"),
  Unit("erg / (Angstrom cm2 s)"),
  <function astropy.units.equivalencies.converter_photlam_fla>,
  <function astropy.units.equivalencies.iconverter_photlam_fla>),
 (Unit("ph / (Angstrom cm2 s)"),
  Unit("erg / (cm2 Hz s)"),
  <function astropy.units.equivalencies.converter_photlam_fnu>,
  <function astropy.units.equivalencies.iconverter_photlam_fnu>),
 (Unit("ph / (Angstrom cm2 s)"),
  Unit("ph / (cm2 Hz s)"),
  <function astropy.units.equivalencies.converter_photlam_photnu>,
  <function astropy.units.equivalencies.iconverter_photlam_photnu>),
 (Unit("ph / (cm2 Hz s)"),
  Unit("erg / (cm2 Hz s)"),
  <function astropy.units.equivalencies.converter_photlam_fla>,
  <function astropy.units.equivalencies.iconverter_photlam_fla>),
 (Unit("ph / (cm2 Hz s)"),
  Unit("erg / (Angstrom cm2 s)"),
  <function astropy.units.equivalencies.converter_photnu_fla>,
  <function astropy.units.equivalencies.iconverter_photnu_fla>)]
```

There is no clear way to determine that the reference was `5000 AA`.

This issue affects the `doppler` conventions, `brightness_temperature`, and probably others that are not in the main units class.

A workaround would be to have a thin wrapper of the returned `list` (say, a subclass of list?) that retains some metadata, e.g. a `meta` attribute that would simply store the `args`/`kwargs` used when initializing the equivalency.

cc @astrofrog

**Comment by mhvk** [comment]
Indeed, would be good. See also https://github.com/astropy/astropy/pull/1731#issuecomment-27725811; indeed, your suggestion of a thin class could help solve #1731 (hence, cc @embray) - it would make it quite easy to define equality -- which can be useful, e.g., to check that a given equivalency is included in a list of equivalencies (for parametrized equivalencies, one would simply check that `kwargs` were the same).

**Comment by keflavich** [comment]
Great point.  The equality comparison is something else I've run into recently.

**Comment by embray** [comment]
I think this makes a good case for a container class for equivalencies (i.e. `Equivalency`).  I don't know that it would necessarily need to subclass `list`.  I don't think we really need most `list` methods for equivalencies (though doing away with them would be an API change to be sure, though not one likely to have much affect).   Either way I think this is a good idea.

**Comment by mdboom** [comment]
It's a common and supported use case to be able to combine equivalencies from multiple functions, in order to create a "domain-specific" set of equivalencies that you may always want to be in effect when calling a particular user function, e.g.:

```
u.spectal_densitry(5000 * u.AA) + u.doppler_radio(restfreq)
```

So having a thin wrapper around the list of equivalencies won't work here -- how would you separate the argument passed to `spectral_density` from the argument to `doppler_radio` above, for example?

I think having a special class for each equivalency entry is fine -- which would allow introspecting the original kwargs that led to its creation.  However, I don't think a new container class for a list of equivalencies is strictly necessary or maybe even a good idea.  We still need to be able to combine lists of equivalencies, delete entries, etc. in order to have more than one set of them in effect.

**Comment by embray** [comment]
If that's so then a `list` subclass might be fine after all.  I wasn't sure how common it was to manipulate lists of equivalencies after their creation (beyond concatenating which would still be easy to support...)

**Comment by mhvk** [comment]
Concatenation happens quite frequently in the code (including my function units, which have built-in equivalencies). Even though concatenation would be easy to support, it still seems simplest to just start with subclassing list, so that's covered automatically and other things don't break. Although this might break the ease with which one could evaluate `<so-and-so> in <equivalencies>`.

**Comment by embray** [comment]
Okay.  I'm not thinking anything terribly complicated (and I think neither are you either).  Just something with better built-in reporting capabilities.

**Comment by mhvk** [comment]
Sounds good!  (Indeed, not worth spending too much time.)

**Comment by pllim** [comment]
How about just attaching metadata to Units? If I use 5000 A to convert FLAM to FNU, then the output FNU will simply have some kind of metadata attached to it identifying the 5000 A. You can have any amount of metadata in a Unit, so multiple equivalencies will simply produce a final Unit with multiple entries in its metadata. Just an idea.

**Comment by mhvk** [comment]
On the `unit` I'm not sure, but meta data on the `Quantity` makes sense to me. If only for unrelated things like being able to give a quantity a `name` which is automatically used in plots... One could envisage some form of history being stored.

**Comment by mdboom** [comment]
Ok.  I'm still not sure what subclassing list buys you.  You couldn't get the original arguments that created the list from it anyway, since that list might be a combination of equivalencies from multiple sources.  I do so why having a special class for each equivalency *entry* makes sense, though.

**Comment by embray** [comment]
Ah, okay.  I think I see what you're saying.  Do you think that would be sufficient, @keflavich ?

**Comment by keflavich** [comment]
Yes, any one of these solutions is fine by me (an Equivalency class, or metadata on a quantity) - @embray I'm not sure which solution you were asking about.

One concern with keeping metadata on a quantity is that it is possible to use multiple equivalencies in sequence, e.g. `x.to(u.km/u.s, u.doppler_optical(5*u.AA)).to(u.GHz, u.doppler_optical(100*u.GHz))`, and I can only assume that would require replacing the first equivalency with the second since you can't have two inconsistent equivalencies.  It is then difficult/impossible to know what the original quantity was.  With equivalencies containing metadata, it is the responsibility of the converting program/user to keep track of what's been done.

...actually, that strikes me as a bug: this is meaningless, but it works: `x.to(u.km/u.s, u.doppler_optical(5*u.GHz) + u.doppler_optical(10*u.GHz))` returns

**Comment by mhvk** [comment]
It occurred to me that part of the solution would be to have a function unit and quantity class that has an offset in its definition -- this is a bit like the logarithmic units which are scaled to a particular number. With that, one can also more easily handle degrees C and F. Like for logarithmic quantities, many of the actual arithmetic would loose the offset information, though (e.g., subtracting two temperatures in degrees C would return a temperature difference which no longer has an implied offset).

**Comment by Cadair** [comment]
Note that I have unwittingly implemented what @keflavich suggested in the original comment here in #8252
