### ISSUE TITLE
For fixed with reader, make ``col_ends`` default sensible

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3564]
For the fixed width reader in io.ascii it would be nice to avoid having to do things like

```
col_starts=[0,5,20,32,42,55], col_ends=[5,20,32,42,55,100]
```

By default, one could assume that columns end where the next start, and have the last item default to infinity (or whatever means to the end of the line).

**Comment by britgit** [comment]
Hi @astrofrog I think this is something I'd be able to do as a very new contributor. I've made an attempt at it in my commit above, please let me know what you think. I thought it was sensible to default the end of the last column to be the end of the longest line in the table. I have run astropy.test() in Python 3.4.0 and haven't had any failures.

Should I also add test for the new code? I haven't done so as I don't have any experience writing tests, but looking at the tests in astropy/io/ascii/tests/test_fixedwidth.py I think I should be able to write one. Would I also need to add a changelog entry and any documentation?

**Comment by astrofrog** [comment]
@britgit - thanks for starting to work on this! I'm going to cc @taldcroft so he can participate in the discussion also. I'll take a look at this later today.

**Comment by taldcroft** [comment]
:+1: on the idea.

About implementation, I would just suggest a tweak to what you've done to avoid repeated code:
```
        if self.col_starts is not None and self.col_ends is not None:
            starts = list(self.col_starts)  # could be any iterable, e.g. np.array
            ends = [x + 1 for x in self.col_ends]  # user supplies inclusive endpoint
            if len(starts) != len(ends):
                raise ValueError('Fixed width col_starts and col_ends must have the same length')
            vals = [line[start:end].strip() for start, end in zip(starts, ends)]
        elif self.col_starts is not None and self.col_ends is None:
            # Figure out column end positions from start positions and the length
            # of the longest data line
            starts = list(self.col_starts)
            ends = list(self.col_starts[1:]) # Assume each col ends where the next starts
            end_of_last_col = max(len(s) for s in self.data.data_lines)
            ends.append(end_of_last_col)
            vals = [line[start:end].strip() for start, end in zip(starts, ends)]
```
Instead just have one block:
```
if self.col_starts is not None:
    ...
    if self.col_ends is None:
        ...
    else:
        ...
    ...
```

**Comment by taldcroft** [comment]
Also to make the code slightly easier (for me) to read:
```
max_line_length = max(len(s) for s in self.data.data_lines)
ends = starts[1:] + [max_line_length]
```

**Comment by taldcroft** [comment]
Actually, even better I think you can get away with not even computing `max_line_length`:

```
ends = starts[1:] + [None]
```

Slicing a string like `'abcdef'[3:None]` works.

**Comment by britgit** [comment]
Thanks for the advice, I reorganised the whole if-statement to try to cut down the amount of repeated code. I also added the ability to specify only the column end positions and calculate the starting positions from them. I hope the whole section is more readable now.

**Comment by taldcroft** [comment]
@britgit - this is looking good now.  Time to add some tests, update docs, update CHANGES.rst and make sure tests pass locally with `python setup.py test --package=io.ascii`.  Then push your branch and make a PR.

**Comment by britgit** [comment]
Thanks, I've added two tests and two examples to the docs. I added an entry to the 1.02 API Changes section in CHANGES.rst. Running ``python setup.py test --package=io.ascii`` in Python 2.7.6 and 3.4.0 gave no failures.

**Comment by astrofrog** [comment]
Thanks @britgit!
