### ISSUE TITLE
Tables lose units when written to HDF5 files

### ISSUE THREAD

**Issue by paulray** [astropy/astropy#3567]
If you create a Table with a column that has a  unit, then write it to an HDF5 file, when you read it back in, the units on the column are not preserved.  This would be desirable, and HDF5 supports metadata that could be used for this, I think. Here is a simple demo:

``` python
import numpy
from astropy.table import Table,Column
import astropy.units as u
c = Column(data=numpy.array([1.0,2.0,3.0]),unit=u.m,name='x')
t = Table(data=(c,))
t.write('t.hdf5',path='x')
s = Table.read('t.hdf5',path='x')
print t
print s
```

The output shows that `t` has units, while `s` does not.

**Comment by taldcroft** [comment]
See #3568 for a possible solution.

**Comment by paulray** [comment]
Thanks, that looks great! I'll look forward to using  that functionality once it is merged.  I'll close this issue now, since it is covered by #3568

**Comment by astrofrog** [comment]
Re-opening since we should keep it open until #3568 is definitely merged

**Comment by bsipocz** [comment]
#4103 is addressed this issue, so I'm closing.

To preserve column units as descriptions use the ``serialize_meta=True`` when writing the table out:
http://docs.astropy.org/en/stable/io/unified.html#hdf5
