### ISSUE TITLE
Polynomial model of null degree

### ISSUE THREAD

**Issue by ycopin** [astropy/astropy#3574]
For sake of consistency, would it be possible to allow the `PolynomialModel` to be of degree 0, i.e. constant with a single coefficient? 

Furthermore, while I agree the high-order polynomials are instable, is there a technical reason for a maximum degree of 16?

**Comment by embray** [comment]
I don't see why `degree=0` couldn't be allowed.

I'm not entirely sure why the `degree < 16` limitation is there.  I know there was a reason for it, but @nden might remember better.  My best guess would be that it was a limitation of one of the fitters.  But if so, that limitation should probably be handled on the fitter's end and not in the polynomial class.

**Comment by embray** [comment]
(Note, I've labeled this "Bug", but "technical limitation that was known, but that could probably be worked around" is maybe more accurate :)

**Comment by embray** [comment]
This was fixed in #3589.
