### ISSUE TITLE
BUG lots of errors with numpy development

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#3584]
If one buids under numpy-dev, there are *lots* of failures, many related to a change where `np.allclose` now uses `isclose` internally (https://github.com/numpy/numpy/pull/5590), which, if one uses quantities, means one gets `UnitsError` because `atol` is a number without units and gets added to the difference between the two arguments. This can be solved by adding `atol=0` to all instances (or `.value` to the quantities), but better may be to just use `assert_allclose_quantity`  in all but the `units` test cases.

**Comment by mhvk** [comment]
See #3593 for a resolution for the `allclose` problems. This leaves rather numerous errors in `astropy.io`, which may be due to a different change. @embray?

**Comment by embray** [comment]
I believe the failures in question are already known.

**Comment by mhvk** [comment]
If so, then if #3593 passes, this can be closed. But is there an open issue for the `io` problems?

**Comment by mhvk** [comment]
@embray - for the failures in `astropy.io` with numpy-dev, is there a PR or issue to refer to? Would be good to solve it...

**Comment by astrofrog** [comment]
@mhvk - are the issues you are seeing all reported in either https://github.com/astropy/astropy/issues/3419 or https://github.com/astropy/astropy/issues/2960?

**Comment by mhvk** [comment]
@astrofrog - indeed, all remaining issues now that  are with `io.fits`, and are covered by the issues you mention. I'll thus close this.
