### ISSUE TITLE
time format=isot is broken

### ISSUE THREAD

**Issue by mrawls** [astropy/astropy#3587]
Time is not recognizing input in the isot format. I believe this used to work in v0.4, but I have since updated to v1.0.

```
>>> import astropy
>>> astropy.__version__
u'1.0'
>>> from astropy.time import Time
>>> test = '2012-03-01T13:08:00'
>>> datetime = Time(test, scale='utc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Meredith/Applications/Ureka/variants/common/lib/python2.7/site-packages/astropy/time/core.py", line 198, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File "/Users/Meredith/Applications/Ureka/variants/common/lib/python2.7/site-packages/astropy/time/core.py", line 240, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File "/Users/Meredith/Applications/Ureka/variants/common/lib/python2.7/site-packages/astropy/time/core.py", line 278, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']
>>> datetime = Time(test, scale='utc', format='isot')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Meredith/Applications/Ureka/variants/common/lib/python2.7/site-packages/astropy/time/core.py", line 198, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File "/Users/Meredith/Applications/Ureka/variants/common/lib/python2.7/site-packages/astropy/time/core.py", line 240, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File "/Users/Meredith/Applications/Ureka/variants/common/lib/python2.7/site-packages/astropy/time/core.py", line 278, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match the format class isot
```

**Comment by taldcroft** [comment]
@mrawls - this problem has been seen when there is a mismatched version of the built ERFA library and the astropy source.  In particular this could happen when building from the source repo, and it was always cleared up by cleaning the git repo using `git clean -fdx`  (danger, this cleans everything in the git repo that isn't under version control).

How did you install astropy?

**Comment by embray** [comment]
It looks like @mrawls is using Ureka.  I've seen this problem with Ureka before, where when upgrading a package with pip it sometimes fails to uninstall the old pacakge, and can cause partial overwrites of existing packages and other strangeness.

@cslocum might have better advice, but in the past when I've seen this happen I've suggested just going into `/Users/Meredith/Applications/Ureka/variants/common/lib/python2.7/site-packages/`, deleting everything to do with astropy, and reinstalling with pip.

**Comment by mrawls** [comment]
So weird. Yes, I'm using Ureka, and I did upgrade, because I wanted all the great new stuff in v1.0 ;)

Thanks, completely wiping astropy and reinstalling seems to have fixed the issue. It is annoyingly non-trivial to upgrade Ureka python packages (in my limited experience)!

**Comment by embray** [comment]
@mrawls I think that will improve in the future.  The problem mostly has to do with a the way the packages are built/installed when Ureka itself is built, versus how they are installed/upgraded when using an installer like pip.  I've been talking to the maintainers of Ureka on how this can be improved.

**Comment by embray** [comment]
(I think it also has something to do with that they don't want you upgrading packages in the core, and instead upgrading Ureka itself, rather than messing with the versions of individual packages in such a way that hasn't been tested, and then submitting "bugs" that result from that. But that's just my guess.)

**Comment by mrawls** [comment]
That sounds right. I "upgraded" Ureka itself once when I managed to break pyraf, and I learned that just meant reinstalling everything. Of course that ate all my extra python packages/upgrades/customizations. Frustrating, but glad to hear you and others are talking about making it better!
