### ISSUE TITLE
Manipulating WCS: Failure with GLS/SFL?

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#3588]
I am getting this error:

```
InvalidTransformError: ERROR 7 in wcsset() at line 1760 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameters.
ERROR 4 in celset() at line 399 of file cextern/wcslib/C/cel.c:
Ill-conditioned coordinate transformation parameters
No valid solution for latp for these values of phip, phi0, and theta0.
```

when I try to drop a degenerate axis from a WCS (using https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/wcs_utils.py#L103).  This has caused problems for the specific header mentioned in https://github.com/radio-astro-tools/spectral-cube/pull/192.

@mdboom could you help me figure out how to debug this?  If I drop the axis using `wcs.sub([WCSSUB_CELESTIAL, WCSSUB_SPECTRAL])`, it Just Works, but if I drop the axis using reindex it does not work with the above failure, or this one if I try `celfix`:

```
In [45]: w2.wcs.celfix()
Traceback (most recent call last):
  File "<ipython-input-45-be028e300848>", line 1, in <module>
    w2.wcs.celfix()
ValueError: ERROR 7 in wcsset() at line 1760 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameters.
```

What am I doing wrong in `reindex`?  Is there some other parameter I should be copying over from the old to the new WCS?  As far as I've been able to tell, the two WCSes produced by the two different axis-dropping method are identical, but that can't be right.

**Comment by mdboom** [comment]
The issue is that `reindex` is not copying over the `pv` cards.  "But the header doesn't have any PV cards!", I hear you say.

Here's what's happening:

When the header is parsed, wcslib converts the `GLS` projection to a `SFL` projection, which apparently stores the latitude pole in `PVi_ma` rather than `CRVAL1`.  

So reindex will probably need to do something like this, which is complicated because it has to change the old axis indices to the new axis indices:

```
    pv_cards = []
    for i, j in enumerate(inds):
        for k, m, v in wcs.wcs.get_pv():
            if k == j:
                pv_cards.append((i, m, v))
    outwcs.wcs.set_pv(pv_cards)

    ps_cards = []
    for i, j in enumerate(inds):
        for k, m, v in wcs.wcs.get_ps():
            if k == j:
                ps_cards.append((i, m, v))
    outwcs.wcs.set_ps(ps_cards)
```

But I guess the deepest question is, why is `wcs.sub` insufficient to use?  It seems to do everything `reindex_wcs` does (and more)...

**Comment by keflavich** [comment]
THANKS!  You did indeed hear me say that.  

Why not use sub?  Well, I tried that, thinking exactly as you did.  But there are many other locations in the code where `reindex` is used because the *order* of the axes needs to be changed.  `wcs.sub` kind of allows that, but not with the same API... perhaps in my confusion, I just did not use `wcs.sub` correctly.  If I can rewrite `reindex` to use `wcs.sub` internally, that will probably be best, but for now I'm going the workaround route.

**Comment by mdboom** [comment]
Ah -- indeed I see `wcs.sub` is not working to reorder.  I thought that would work.  I'll look into that...  Ideally, `reindex` could just be written in terms of `sub`.

**Comment by embray** [comment]
Most of pyfits/astropy.io.fits tries to deal exclusively with 0-based indices and (row,column) order.  The only place where it doesn't is if dealing directly with the headers, but I've been going more and more in the direction of discouraging that wherever possible.

I'm not sure if the same approach is practical for WCS though, but it's a thought...

**Comment by mdboom** [comment]
I think here, though, 1-based indexing makes sense, particularly since 0 has special meaning (a new default axis).

**Comment by embray** [comment]
Oh. Great.  :facepalm:

**Comment by keflavich** [comment]
This issue was resolved a long time ago - mdboom's comments addressed the issue I originally raised.
