### ISSUE TITLE
Improve documentation for setting up readthedocs for affiliated packages

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3599]
Not all affiliated package authors may want to host their documentation on RTD.  But many do!  On the [affiliated package documentation](http://docs.astropy.org/en/stable/development/affiliated-packages.html#managing-the-template-files-via-git) for setting up a new package, we do mention the bare minimum to set up RTD under step 15.  But it hasn't always been straightforward, and I believe we have some collective experience on how to get started with RTD, and how to deal with some of the issues that arise, so it would be nice to have a place to collect that.

So I would propose a separate page on setting up RTD that would be linked to from step 15, and perhaps in few other more prominent places.  (I would also leave the text of the aforementioned step 15 as is since it otherwise serves as a nice summary of the bare minimum).

**Comment by astrofrog** [comment]
+1

**Comment by opg7371** [comment]
+1

**Comment by pllim** [comment]
:+1:

**Comment by bsipocz** [comment]
There is some docs provided as part of the package template, and I suppose things got simplified over the years as I can't recall much complaints that said docs is not detailed enough.
