### ISSUE TITLE
bootfunc for astropy.stats.bootstrap can only return 1 value

### ISSUE THREAD

**Issue by ttshimiz** [astropy/astropy#3601]
I'm trying to use the astropy.stats.bootstrap function to estimate confidence intervals for a correlation coefficient. However it looks like the function you input to reduce the resamples can only return one value whereas functions like spicy.stats.spearmanr return both the correlation coefficient and the p-value. When I try to use either spearmanr or pearsonr I get a "ValueError: setting an array element with a sequence." I think this is a fairly easy fix and I'd be happy to submit a pull request. I'm wondering though what the best way to fix this is. Do we want to return everything that the function returns for each resample or only the most important object (i.e. the correlation coefficient)?

**Comment by crawfordsm** [comment]
Thanks for raising this issue  @ttshimiz and please let me know if the recently merged pull request #3628 does not close it for you.
