### ISSUE TITLE
Add a better __repr__ for WCS objects

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3604]
Instances of the `WCS` class in `astropy.wcs` only have the default `__repr__`:

```python
>>> w = astropy.wcs.WCS(header)
>>> w
<astropy.wcs.wcs.WCS at 0x7f43a6ff5ae8>
```

I haven't personally thought out exactly what it *should* display, but I'm sure people who use it regularly could come up with all sorts of things that would enhance this.

**Comment by embray** [comment]
(Note: the `.wcs` *attribute* on `WCS` objects has extensive output, but `WCS` objects themselves could do more)

**Comment by mdboom** [comment]
Yeah -- maybe it could at least display the CTYPE array, and maybe whether it has SIP or image distortion parts -- that's as close to a "short" description as any, I'd guess.

**Comment by astrofrog** [comment]
While we are at it, ``print(wcs)`` returns something that looks like a repr:

```
In [4]: print(wcs)
<astropy.wcs.wcs.WCS object at 0x1056534a8>
```

How about instead printing out something that looks more like a FITS header?

**Comment by nden** [comment]
There's also this method:
```
wcs.printwcs()
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN-SIP'  'DEC--TAN-SIP'  
CRVAL : 5.6305681061800001  -72.054571842800001  
CRPIX : 2048.0  1024.0  
CD1_1 CD1_2 : 1.29058667557984e-05  5.9532024588455501e-06  
CD2_1 CD2_2 : 5.0221519562382498e-06  -1.2645010396976e-05  
NAXIS    : 4096 2048
```
This may be too verbose for a `print` or `repr`but I find it useful for a quick look at the WCS. It lacks distortion information though. It should probably be deprecated if  a proper `print` is written.

**Comment by embray** [comment]
I don't think that's overly verbose.  For some types of objects the guidelines for a terse `__repr__` output make sense, but for something complicated like WCS there's no sense in it.

**Comment by bmorris3** [comment]
@astrofrog - Mind if I take a stab at porting the `wcs.printwcs()` behavior to the `__repr__` method for my GSoC PR?

**Comment by astrofrog** [comment]
@bmorris3 - yes, feel free to open an initial pull request. There may be some more discussion before we converge on an exact format, but for the purposes of opening a PR for GSoC, this is fine (it doesn't have to be merged before the deadline)

**Comment by bmorris3** [comment]
In the above PR, I've created a `__repr__` method that returns the same contents as the `wcs.printwcs()` method. Now when printing an instance of WCS, you get something like: 

```python
>>> print(wcs)
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN-SIP'  'DEC--TAN-SIP'  
CRVAL : 348.15734535550303  -22.674175819346601  
CRPIX : 16.5  16.5  
CD1_1 CD1_2  : -0.00017139538886515001  0.00029601303489825602  
CD2_1 CD2_2  : 0.00029382704485179202  0.00017399550578156  
NAXIS    : 32 32
```

**Comment by embray** [comment]
This can be closed now.  Thanks @bmorris3
