### ISSUE TITLE
Add theta parameter to GaussianKernel2D

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3605]
GaussianKernel2D currently does not take a position angle (as far as I can tell), but it would be good to implement this:

http://docs.astropy.org/en/stable/api/astropy.convolution.Gaussian2DKernel.html#astropy.convolution.Gaussian2DKernel

@adonath - any reason why it should not be included?

**Comment by adonath** [comment]
I'remember that I shortly discussed this with @larrybradley in #2085. For me, the bottom line was that it's a very special use case (I just couldn't think of any common application for this kind of kernels...).
My idea was to use `Model2DKernel` for this cases, which requires just one addtional line of code. I'm not against including a theta or asymmetry parameter, I just don't see the need...

**Comment by astrofrog** [comment]
I had a user ask me how to do this yesterday in the context of convolving an image with a radio astronomy synthesized beam which is an arbitrarily rotated gaussian. There's no reason we can't support it since the parameter can be passed right through to ``Gaussian2D``.

**Comment by larrybradley** [comment]
Also note that `GaussianKernel2D` doesn't even currently take a separate `xstddev` and `ystddev`.  They would also need to be added to make `theta` useful. :smile:  From what I recall, all of the kernels are circularly symmetric, except for `Box2D`.

**Comment by embray** [comment]
There are lots of cases in the modeling package (and by extension the convolution package) where it might be hard to think of a reason someone would want to do that...until they do.  So the general policy has been to not make any arbitrary restrictions just based on "who would need that?" (where we're talking about cases that don't require adding any actual code or complexity)

**Comment by astrofrog** [comment]
Right - to me the kernel classes should basically mirror the model classes, and provide the same arguments for consistency. Of course, one should be able to initialize a GaussianKernel2D with a single size that would apply to both dimensions, and no rotations, but the more general case should be supported too, and would be easy to support.

**Comment by adonath** [comment]
I agree. It would make models and kernels more consistent and there is actually no good reason to not do it...I will work on this and also check others kernels for consistency with models.

**Comment by larrybradley** [comment]
I agree as well (I tried to suggest this back in #2085). :smile:

**Comment by rohitjatana** [comment]
https://github.com/rohitjatana/astropy/pull/1 
i have added theta parameter to gaussionkernel2d.

**Comment by aniketk21** [comment]
@astrofrog I'd like to work on this issue.

**Comment by adonath** [comment]
@aniketk21 The parameters of the `Gaussian2DModels` are documented [here](http://docs.astropy.org/en/stable/api/astropy.modeling.functional_models.Gaussian2D.html#astropy.modeling.functional_models.Gaussian2D). For all parameters there are already sensible default values implemented, so the task is only to correctly pass the parameters from the `Gaussian2DKernel` to the `Gaussian2DModel`, via `**kwargs` and correctly compute the amplitude of the kernel, so that it integrates to unity.

**Comment by aniketk21** [comment]
@adonath can you check this [code](https://github.com/aniketk21/astropy/commit/99c5e333d1a24cf002c98791a2f7f0f92390e7c0)?
