### ISSUE TITLE
Add matplotlib and WCSAxes to list of optional dependencies in install docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3608]
It is used in astropy.visualization.

Also add WCSAxes since it's used when WCS is used as a projection in Matplotlib.

**Comment by mtzhisham** [comment]
i added them, please take a look and merge it if it's valid (my first PR)

**Comment by eteq** [comment]
@mtzhisham - can you point us to the PR?  If you just include the text ``#nnn`` with the number of the PR, it will create a link to the PR in question.

**Comment by mtzhisham** [comment]
PR #3609
