### ISSUE TITLE
Question: votable header - is ID, should be name?

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#3621]
I'm trying to parse this votable:
https://gist.github.com/ab98a382242630d0c089

and the column names are the ID, but I think they should be the name:
```
>>> t.colnames
['1251',
 '1206',
 '1186',
 '1187',
 '1223',
 '1217',
 '1213',
 'Release_date',
 '1216',
 '1225',
 '1238',
 'Observation_date',
 '1260',
 '1240',
 '1234',
 '1182',
 '1263',
 '1264',
 '1254']
```

How do I get it to select the `name` field instead?  Should that not be the default?
Example rows:
```
      <FIELD name="Observation date" datatype="char" unit="" xtype="adql:VARCHAR" arraysize="*" />
      <FIELD name="PI name" datatype="char" ID="1260" ucd="meta.id.PI" xtype="adql:VARCHAR" arraysize="256*">
```

**Comment by keflavich** [comment]
Followup: http://astropy.readthedocs.org/en/latest/io/votable/ clearly says *why* this is happening.  Is there a way to use `name` instead of `ID`, though?

**Comment by mdboom** [comment]
When you convert from a VOTable to an astropy.table.Table, pass `use_names_over_ids=True`, i.e.:

```
from astropy.io.votable import parse_single_table
table = parse_single_table("votable.xml")
table = table.to_table(use_names_over_ids=True)
```

Admittedly, maybe that hint should go in the note about the horrible situation with names vs. ids.  Any thoughts about how to best fix that "documentation bug"?

**Comment by keflavich** [comment]
@mdboom - just put it in that note.  I'll make a branch and ask you to turn it to a PR?

**Comment by mdboom** [comment]
I'll just create a PR -- I'm already half way there anyway.  Thanks.
