### ISSUE TITLE
Mass Functions

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#3625]
Followup of #1754, which was closed without merge.

Mass functions belong in astropy.stats or the affiliated package PopStar.  This issue is to keep track of discussion in that vein.  cc @embray @astrofrog @jluastro

**Comment by bsipocz** [comment]
This feels like affiliated package content to me (not sure which one though). 

I'm adding the "close?" label.

**Comment by keflavich** [comment]
Do we have a good place for this sort of issue, then?  e.g., an astropy-ecosystem issue tracker?  I keep forgetting where our 'ideas tracker' lives...

**Comment by pllim** [comment]
Errr, like the UserEcho thingy that we want to replace?

**Comment by keflavich** [comment]
Yeah, that!  Let's replace that and then move this issue to the replacement.

...can we just have an astropy-ecosystem package and use its issuetracker/project tracker?
(where should we have this conversation?  slack?)

**Comment by pllim** [comment]
We never quite reached a consensus on *how* to replace UserEcho. I feel like that will likely involve a decision by @astropy/coordinators ? :grimacing:

**Comment by keflavich** [comment]
Ahhh, right, this was tabled in the parking lot.

**Comment by jluastro** [comment]
We will be working to get PopStar into an accepted affiliated package in the next few months. Let met know what the conclusion is for how best to track issues in the architecture across affiliated packages and main.

**Comment by bsipocz** [comment]
> We never quite reached a consensus on how to replace UserEcho at Astropy Coordination Meeting 2018. I feel like that will likely involve a decision by @astropy/coordinators ?

maybe we can keep these in cards in an astropy project board, something like "future wishes"? Surely that would only be good for keeping track, but not suitable for discussions, etc.
