### ISSUE TITLE
fits.open to allow opening only one frame from a 3D cube

### ISSUE THREAD

**Issue by sergiovelascom** [astropy/astropy#3630]
When working with large cubes (1000 or 5000) images each it would be nice to be able to open just one of the frames of the cube and not the whole, which usually slows the codes.

**Comment by astrofrog** [comment]
@sergiovelascom - if your cube is not compressed, then ``fits.open`` normally opens cubes with memory-mapping. This means that when you do:

```
hdulist[0].data[400,:,:]
```

it is only reading in the data required from disk. However, if the cube is compressed, it needs to read it all in first. Could you provide more details of how you are opening the FITS files, and accessing slices?

**Comment by embray** [comment]
@astrofrog mmap can fail to provide in some cases--not just compressed data, but also scaled data.  What @sergiovelascom wants is the [`.sections`](http://docs.astropy.org/en/stable/io/fits/usage/image.html#data-sections) interface.  The eventual plan is to make make a specialized FITSData class that would handle cases like this transparently.  But in the meantime the sections interface is for that.

**Comment by embray** [comment]
@astrofrog Also a fair point is that `.sections` won't work for tile-compressed images (ironically, somewhat defeating the purpose of tile-based compression).  But I think there's already an issue for that.
