### ISSUE TITLE
Better visibility / linkage of Astropy project elements

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#3661]
I went to astropy.org looking for information about affiliated packages and for some reason my eyes didn't wander up to the top nav bar and so I didn't find it for a while.  It is also not obvious that affiliated packages exist if you just go the core docs (hidden under Astropy at a glance => Overview).

The situation for Astropy tutorials seems even worse.  I'm not sure how anyone is supposed to know these exist based on astropy.org or docs.astropy.org.  (Again, I might have missed it, but I was actually _looking_, so there is room for improvement.)

The point here is to make it more obvious on astropy.org that this is the Project home page, and the Project is much more than the astropy core package.

Ideas:
- Add sentences to the tagline in http://astropy.readthedocs.org/en/latest/index.html which reads something like: To learn about the Astropy project see `<http://astropy.org>_`.  This includes information about Astropy `tutorials <link>` and `affiliated packages <link>`.  (Note, use the http://astropy.org URL directly instead of as a link href so people see it and know it's there).
- Add "Tutorials" to the astropy.org nav bar.
- Perhaps also add buttons for Affliated Packages and Tutorials next to Current Documentation on the astropy.org index page, or else include something like the above additional sentences in the Astropy project tagline.

**Comment by embray** [comment]
:+1: Maybe this will help drive more development on tutorials again.

**Comment by embray** [comment]
On the topic of giving astropy-tutorials more love, I'm a little concerned about this one: http://www.astropy.org/astropy-tutorials/FITS-header.html  I feel like it's promoting practices that I'd rather users try to avoid.  Maybe that's just me though.

**Comment by eteq** [comment]
@kelle volunteered to work on this at the Lorentz Center workshop

**Comment by bsipocz** [comment]
We also got the feedback, that it's not trivial to see that astropy does e.g. aperture photometry (through photutils). Would it make sense to brainstorm on how to get a better visibility for the affiliated packages? Googling on "photometry python" brings up the related docs page as the first find, but it's clearly not enough. Also the getting started pages and the list of affiliated packages are not on the first page of finds.

**Comment by kelle** [comment]
to be clear, I volunteered to work on adding links to the tutorials from the documentation. 
I think the comment by @embray about FITS-Header should be a new issue.

**Comment by lfulmer** [comment]
Affiliated Packages are linked in the tagline at astropy.readthedocs.io/en/latest/index.html and tutorials are easy to find from astropy.org > Documentation > Tutorials. Issue closed by @adrn .
