### ISSUE TITLE
Improve customization of test report header

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3664]
There have been a couple issues regarding customizing the header info that is displayed at the beginning of test runs; in particular affiliated packages using the same test framework would like to be able to customize the names of the package being reported on, and the names and versions of dependencies, among other things (see #3543, #3157).

Currently the only way to change this is to modify a global variable `PYTEST_HEADER_MODULES` in the pytest_plugins module, so affiliated packages have to import this module and update that variable to customize their test headers.  This is hacky, and also not well documented.

I think we could instead provide options that can be set in setup.cfg to change what is reported here, at least as a starting point.

**Comment by mdboom** [comment]
Is setup.cfg available at run time?  Or are you planning on copying it into the install somehow?

**Comment by embray** [comment]
Oh, good, point. I don't know.  How do affiliated packages currently modify this?  Do they add a conftest.py module?  Maybe the settings can just go there, but still be better documented.

**Comment by mdboom** [comment]
Yeah -- there's a `conftest.py` in the package template.

```
## Uncomment and customize the following lines to add/remove entries
## from the list of packages for which version numbers are displayed
## when running the tests
# try:
#     PYTEST_HEADER_MODULES['scikit-image'] = 'skimage'
#     del PYTEST_HEADER_MODULES['h5py']
# except NameError:  # needed to support Astropy < 1.0
#     pass
```

**Comment by embray** [comment]
Okay, I'll play around with this a bit.  Maybe setup.cfg isn't the way, but it should still be easier to do this.

**Comment by bsipocz** [comment]
This is now working for a while in the whole ecosystem via the display plugin, so I'm closing this issue.
