### ISSUE TITLE
Remove bare except statements

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3682]
There's been some talk lately on the Python mailinglists of removing support for bare except statements entirely from the language.  Granted, I don't think there's any actual movement on this yet, and even if it does happen there will be likely be a length deprecation period.  Still, can't hurt to get ahead of the curve.

I don't personally have any strong feelings about bare excepts, but I think the arguments against them make sense.  At the time of writing I count 89 of these in Astropy + astropy-helpers.  I think in many cases, if an appropriate exception to catch can't be found, it's fine to just `except Exception:`.  This is still good because it will only catch code exceptions, (`ValueError`, `TypeError`, etc.) but not system exceptions like `SystemExit` and `KeyboardInterrupt`.

Just something to keep in mind.

**Comment by pllim** [comment]
This will impact `stsci_python` too.

**Comment by mhvk** [comment]
closed by #5335.
