### ISSUE TITLE
Proposal: adding a `coalesce` function to `table.operations`?

### ISSUE THREAD

**Issue by barentsen** [astropy/astropy#3683]
### Summary

The SQL standard provides the `COALESCE` function, which accepts a list of parameters and returns the first non-NULL value.  I recently implemented this function in Python for use with astropy's `MaskedColumn` objects, because I had a use case for it.  I am now wondering if the operation is common enough to warrant creating a PR for adding it to `table.operations`?
### Example

Imagine a catalogue of stars containing three different estimates of the V-band magnitude, but with some values missing (e.g. non-detections):

``` Python
<Table masked=True length=3>
   V1      V2      V3  
float64 float64 float64
------- ------- -------
   15.7    15.8    15.6
     --      --    22.6
     --    21.5    21.7
```

The `coalesce` function merges multiple columns into one by taking the first non-masked value:

``` Python
In [5]: coalesce([V1, V2, V3])
Out[6]: 
<MaskedColumn name='V1' dtype='float64' length=3>
15.7
22.6
21.5
```

The preference is determined by the order in which the columns are passed on to the function, hence the reverse order produces a different result:

``` Python
In [7]: coalesce([V3, V2, V1])
Out[8]: 
<MaskedColumn name='V3' dtype='float64' length=3>
15.6
22.6
21.7
```
## Question

_Is it worth opening a PR to add the `coalesce` function as a feature, or am I the only one who has ever ran into this use case?_ 

Neither `numpy` or `pandas` appear to offer a feature like this, though the function is part of SQL. A gist showing the initial implementation I have been using is here: https://gist.github.com/barentsen/7450661b124a4b60c482

**Comment by barentsen** [comment]
Oh, I just realize now that an alternative way to achieve this functionality would be to use the `filled` method in a chain:

```Python
V1.filled(V2).filled(V3)
```

However, this doesn't actually work right now because `filled` returns a `Column` rather than a `MaskedColumn`:

```Python
In [77]: V1.filled(V2).filled(V3)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-77-8cfd8d02b8c8> in <module>()
----> 1 V1.filled(V2).filled(V3)

AttributeError: 'Column' object has no attribute 'filled'
```

Any opinions?

**Comment by taldcroft** [comment]
:+1: - this seems like a fine thing (even if slightly obscure), and the code in your gist looks like it's much of the way to a PR. 

I think it's reasonable that `filled()` should return a regular (non-masked) `Column`, so your hopeful workaround is not likely to ever work.

**Comment by mhvk** [comment]
Do think this is a useful feature.  One might consider generalising it to non-masked columns (where masked would be determined with `np.isnan`). 

Out of curiosity, would this do it?
```
np.ma.where(V1.mask, np.ma.where(V2.mask, V3, V2), V1)
```
(think plain `np.where` doesn't work, but didn't test anything)

**Comment by barentsen** [comment]
@mhvk You are a genius. Both `np.ma.where()` and `np.where()` do the trick. This weakens the case for adding `coalesce()` in my opinion.

One might argue that it would nevertheless be nice to have `coalesce()` as a convenience function, but then we should probably be providing this for other aggregate functions as well (`min`, `max`, `mean`, `std`). 

For example, creating a new column containing the mean magnitude, I would currently do this:
```Python
import numpy as np
V = MaskedColumn(np.ma.mean((V1, V2, V3), axis=0), name='V')
```

...but it could be simplified into this:
```Python
from astropy.table import operations
V = operations.mean((V1, V2, V3))
```

Would this be worth adding?

**Comment by mhvk** [comment]
@barentsen - my overall sense is that this is sufficiently easily done with little python snippets that there is little urgency in adding explicit methods. What your examples do show, however, is the use of masked columns -- it would be great if somehow we could have this generally (masked coordinates, quantities, etc.). But `MaskedArray` is really rather a mess. See #1857 for a comment about making our own masked class (including links to an aborted attempt).

**Comment by taldcroft** [comment]
@mhvk - Hmm, I'm kinda more for adding this functionality.  One thing is that even if it can be done with a little Python snippet for 2 or 3 columns, for more than that you basically need to write out a loop or do some tricky recursive implementation.  And even if it is a teeny snippet, that snippet is not something that most astropy users would manage to invent.

I also like the possibility of using `nan` as missing for `Column` objects, except that it starts to open the door to *expecting* that behavior in other contexts.

BTW, not to prematurely optimize, but this simple algorithm seems like a really good candidate for writing with Cython (or numba if we could have that as a dependency).  If you think about unrolling the loops and doing things in a row-wise fashion in the inner loop then it can be both fast and memory efficient.

**Comment by mhvk** [comment]
My comment really was more one of urgency and of priority (e.g., I'd love to see improvements in the integration of `Quantity`, `SkyCoord` and `Time`...). But I can see that, generalized, this could be quite powerful.

On the generalisation and speed: what might give a good combination of speed and ease of writing would be to stack all columns in a single array (say, on a new first axis), and then run a given function on the first axis (i.e., use the optimized code that numpy wrote for us!). For one-dimensional columns, this would be equivalent to:
```
def operations(columns, function):
    combined = np.vstack(columns)
    return function(combined, axis=0)
```
which one could then call as `operations((V1,V2,V3), np.ma.mean)` (or `operations((V1,V2,V3), np.nanmean)`).

With a similar construction, one could also redo the coalesce:
```
def coalesce(columns):
    combined = np.vstack(columns)
    non_masked = np.argmin(combined.mask, axis=1)
    return combined[np.arange(combined.shape[0], non_masked)
```
(this correct returns a masked value if all values are masked, though it is the first one, not the last one). Obviously, one could use the `operations` above with a custom `coalesce` function.

**Comment by barentsen** [comment]
Update: I opened this issue six years ago, but haven't had a need for this feature since then.

There are sufficient tools available to coalesce tables today, e.g. `combine_first()` or `fillna()` in pandas.

I think this issue can be closed!
