### ISSUE TITLE
Allow Quantity to be written as a normal column to a fits file

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#3685]
Following discussion the mailing list: currently, `QTable` will not write `Quantity` columns to fits files, even though those, unlike other `mixin` columns could be written safely.  We probably should lift the restriction specifically for `Quantity`.

**Comment by taldcroft** [comment]
:+1: - just to be clear, there is no other relevant meta for `Quantity` besides the unit?

**Comment by mhvk** [comment]
No, nothing (though I hope that eventually it can have a name even if not used as a column and maybe remember its format too...).

**Comment by mhvk** [comment]
@taldcroft - one easy fix would be to override `Table.has_mixin_columns` for `QTable`, using
```
    @property
    def has_mixin_columns(self):
        """
        True if QTable has any mixin columns other than Quantity subclasses.
        """
        return any(not isinstance(col, (BaseColumn, Quantity))
                   for col in self.columns.values())
```
The logic here would be that for `QTable`, `Quantity` is not really a mixin, but rather its natural column. 

This small change solves the issue and fails only the test that specifically tries to ensure this does not work (`test_io_write_fail`).

One possible issue is that any information about the `Quantity` subclass (`Angle`, `Longitude`, etc.) is lost. To keep that would require saving some metadata after all.

**Comment by pllim** [comment]
I was just trying to do this and realized that I cannot yet... 

```python
>>> tab
<QTable length=6540>
wavelength
 Angstrom 
 float64  
----------
    2000.0
    2001.0
    2002.0
    2003.0
    2004.0
    2005.0
       ...
    7994.0
    7995.0
    7996.0
    7997.0
    7998.0
    7999.0

>>> tab.write('mywaveset.fits')
.../astropy-2.0.dev17497-py3.5-linux-x86_64.egg/astropy/table/table.py in write(self, *args, **kwargs)
   2377         passed through to the underlying data reader (e.g. `~astropy.io.ascii.write`).
   2378         """
-> 2379         io_registry.write(self, *args, **kwargs)
   2380 
   2381     def copy(self, copy_data=True):

.../astropy-2.0.dev17497-py3.5-linux-x86_64.egg/astropy/io/registry.py in write(data, *args, **kwargs)
    516 
    517     writer = get_writer(format, data.__class__)
--> 518     writer(data, *args, **kwargs)
    519 
    520 

.../astropy-2.0.dev17497-py3.5-linux-x86_64.egg/astropy/io/fits/connect.py in write_table_fits(input, output, overwrite)
    206     """
    207 
--> 208     table_hdu = table_to_hdu(input)
    209 
    210     # Check if output file already exists

.../astropy-2.0.dev17497-py3.5-linux-x86_64.egg/astropy/io/fits/convenience.py in table_to_hdu(table)
    453                        if not isinstance(col, table.ColumnClass)]
    454         raise ValueError('cannot write table with mixin column(s) {0}'
--> 455                          .format(mixin_names))
    456 
    457     # Create a new HDU object

ValueError: cannot write table with mixin column(s) ['wavelength']
```

Ah, well!

**Comment by AustereCuriosity** [comment]
I am working on a PR for this and as @mhvk mentioned, changes to has_mixin_columns allows Quantity to be written as a normal column. What to do about the metadata associated with Angle and Longitude? We somehow need to store it in the FITS header right?

**Comment by AustereCuriosity** [comment]
#5910

**Comment by AustereCuriosity** [comment]
#5910

**Comment by AustereCuriosity** [comment]
@hamogu @eteq @taldcroft @mhvk I've opened the pull request #5910. Please do help me out regarding what all should be added as metadata.
