### ISSUE TITLE
compound models ignore polynomial classes' domain

### ISSUE THREAD

**Issue by nden** [astropy/astropy#3699]
@embray Is `prepare_inputs` of orthogonal polynomial classes run when they are part of compound models? 
```
cheb = models.Chebyshev2D(1,1)
cheb.parameters = [1,2,3, 4]
cheb.x_domain=[0, 1024]
cheb.y_domain = [450, 1000]
shift=models.Shift(3)
model = cheb & shift
print(model(1, 2, 1))

(17.0, 4.0)

print(cheb(1, 2), shift(1))

1.61245738636 4.0
```

**Comment by embray** [comment]
I think maybe domain handling should be moved to the `evaluate` instead of `prepare_inputs` if it needs to be a fundamental part of how the polynomial is evaluated.  It would be better though if domains were just supported on all models (an issue I've brought up before with no good resolution).

**Comment by embray** [comment]
Though it also seems that when evaluating a compound model it won't look through all the sub-models and check if they have non-standard `prepare_inputs`; really it should condition the inputs through all possible `prepare_inputs` implementations (and `prepare_outputs` as well).  Might work.
