### ISSUE TITLE
adding circular or spherical distributions to astropy.stats

### ISSUE THREAD

**Issue by astronomeralex** [astropy/astropy#3705]
add circular and spherical distributions and averaging to astropy.stats beyond the very simple things in scipy.stats.morestats.

from pyastro15 astropy.stats unconference session

**Comment by aarchiba** [comment]
This is also suggested for scipy: https://github.com/scipy/scipy/issues/4598 specifically there's a request for a circular distribution object. There already exist circmean, circstd, and circvar.

**Comment by embray** [comment]
This sounds like it might belong in astropy.modeling

**Comment by algerdnazgul** [comment]
Close?

**Comment by crawfordsm** [comment]
Yes this can be closed now.
