### ISSUE TITLE
Line fitting with all the different possible error inputs

### ISSUE THREAD

**Issue by astronomeralex** [astropy/astropy#3710]
should add line fitting with all the different possible error inputs (x, y, correlated, etc) into stats. 

from unconference on astropy.stats at pyastro15

**Comment by eteq** [comment]
@astronomeralex - can you clarify why this belongs in stats?  This is precisely what astropy.modeling is meant for, after all.

**Comment by astronomeralex** [comment]
that's a good point. perhaps this should be a tutorial for modeling, then?

**Comment by embray** [comment]
Maybe this could be a tutorial topic, though the issue statement is awfully vague.  Is there something more you could add to this?

**Comment by kakirastern** [comment]
Just want to confirm that this is still an issue? Has the issue been adequately addressed in the latest stable documentation, say at [http://docs.astropy.org/en/stable/modeling/#models-and-fitting-astropy-modeling](http://docs.astropy.org/en/stable/modeling/#models-and-fitting-astropy-modeling) if not [http://docs.astropy.org/en/stable/stats/#astrostatistics-tools-astropy-stats](http://docs.astropy.org/en/stable/stats/#astrostatistics-tools-astropy-stats) as of February 2019? 

If a tutorial is needed for clarification regarding the modeling, should I open an issue at Learn Astropy instead? If that is the case perhaps this section at [http://docs.astropy.org/en/stable/stats/#see-also](http://docs.astropy.org/en/stable/stats/#see-also) should also be included in the consideration of material covered? 

I could follow up on this if required. 

Please advise.

**Comment by pllim** [comment]
At this point, as the Astropy Project has branched out over the years, this either is more for tutorials *or* specreduce... @eblur and @crawfordsm , what do you think?

**Comment by bsipocz** [comment]
@kakirastern - thanks for catching this.

You are all right, and I feel this has been already covered in http://www.astropy.org/astropy-tutorials/rst-tutorials/Models-Quick-Fit.html?highlight=filtertutorials and maybe also in http://www.astropy.org/astropy-tutorials/rst-tutorials/User-Defined-Model.html?highlight=filtertutorials 
Given the original vagueness I close this issue now. If there is any concrete missing piece in those tutorials, follow-up issues should be opened in that repo.

**Comment by kakirastern** [comment]
You are welcome @bsipocz! I will double check and see if any follow-up tutorial in the Learn Astropy repo is necessary.

**Comment by bsipocz** [comment]
Given the original issue here was very vague I suppose we are all covered for now 😄

**Comment by kakirastern** [comment]
Thanks!
