### ISSUE TITLE
robust image statistics

### ISSUE THREAD

**Issue by astronomeralex** [astropy/astropy#3712]
add robust image statistics someplace in astropy. stats? photutils? ccdproc?

from unconference on astropy.stats at pyastro15

**Comment by eteq** [comment]
@astronomeralex - can you be a bit more specific on what you mean by "robust image statistics"?

**Comment by astronomeralex** [comment]
@eteq -- that's a great question. this was requested by folks at the meeting, but I don't know more than this.

**Comment by pllim** [comment]
Are you sure this is not already addressed by `imutils`?

**Comment by embray** [comment]
I'm not sure opening issues in the bug tracker was the best way to take meeting notes, but whatever :)  Unless someone who was at the meeting can step in and provide more details as to what was discussed on this topic and what belongs in Astropy (as opposed to, say, `imutils` as @pllim brings up or another affiliated package) I think I'll close this one.

**Comment by crawfordsm** [comment]
I think it was @cmccully that mentioned this at the meeting.  And I believe he was referring to the `median_absolute_deviation`, `biweight_location`, and `biweight_midvariance`.   As those are already in `astropy.stats` then I agree with closing this ticket.   If there is anything else that is missing and should be in there, then somone should open another ticket requesting that feature.

**Comment by embray** [comment]
Okay, thanks for the clarification @crawfordsm.  I agree opening a new ticket for specific requests would be best.
