### ISSUE TITLE
Configuration for coveralls not quite right

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3719]
Coveralls is showing the overall coverage changes for various files, but if I want to drill into individual files to see what lines were changed it's failing to get the source for those files.  See for example:

https://coveralls.io/builds/2326977/source?filename=astropy%2Fmodeling%2Fparameters.py

It seems maybe just a slight misconfiguration.

**Comment by bsipocz** [comment]
This seems to be solved now.
