### ISSUE TITLE
Adding super galactic coordinates to astropy.coordinates

### ISSUE THREAD

**Issue by kalgash82** [astropy/astropy#3722]
New function to convert from any coordinate system into super galactic coordinates.
I will implement it

**Comment by embray** [comment]
To be clear, would this mean implementing a new coordinate frame class?

**Comment by astrofrog** [comment]
Yes, this is just a new coordinate class

**Comment by eteq** [comment]
Also it requires implementing a to/from pair of transform functions.  But I'm guessing that (and the class itself) can be mostly copied-and-pasted from Galactic and just updated with the different latitude and longitude (and `l`->`sgl` and `b`->`sgb`).
