### ISSUE TITLE
Improve handling of string/bytes columns in Table pandas converters

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3725]
Once https://github.com/astropy/astropy/pull/3504 is merged, it would be good to improve the handling of e.g. bytes columns which are currently converted to object columns (see e.g. https://github.com/astropy/astropy/pull/3504#discussion_r24937293)

**Comment by taldcroft** [comment]
From 33000 feet, I have a PR on your branch just about ready to solve this.

**Comment by astrofrog** [comment]
Cool! You have internet in a transatlantic flight? :airplane:

**Comment by taldcroft** [comment]
Yup.  $40, but the boss will pay.

**Comment by astrofrog** [comment]
On my side, I'm in a :bullettrain_side:!

**Comment by taldcroft** [comment]
Should be closed by ehttps://github.com/astrofrog/astropy/pull/53/files.
