### ISSUE TITLE
Nicer error for out of disk space when writing a FITS file

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3739]
A user tried to write a file to disk that they didn't have space for and got an exception like this:

```
"/usr/stsci/ssbx/python/lib/python2.7/site-packages/astropy/io/fits/util.py
", line 653, in <lambda>
    write = lambda a, f: a.tofile(f)
IOError: 369098752 requested and 45004992 written
```

Of course, all this means is that they tried to write X bytes and only Y bytes were written where Y < X.  This could happen for a number of reasons, but lack of disk space is by far the most likely culprit.  I believe somewhere in `astropy.utils` there is a utility function to check space on a filesystem being written to.  I wouldn't call that in advance of writing just because in most cases it's unnecessary overhead.  But we could catch exceptions like the one above and _then_ run the disk space check to confirm that that's the culprit (and otherwise still raise an exception but note that the bytes could not be written for an unknown reason).

**Comment by pllim** [comment]
For STScI users, if Central Storage is involved, it might also just be the user quota instead of physical disk space. Are they equivalent here as far as you are concerned?

**Comment by embray** [comment]
Good point. I don't think there's any easy way we can know about the user quota on a shared filesystem.  In that case they'd still get a more vague exception, though part of any fix to this issue should still involve a clearer exception message in this.

**Comment by shwetamore1295** [comment]
I would like to work on this issue. Has this been fixed in [4065]?

**Comment by embray** [comment]
#4065 is almost done. Its author just started school and never had time to put on the finishing touches (as I can well relate to :)  I or someone else will just need to add those finishing touches and merge the PR manually.

**Comment by sathe-aditya** [comment]
Hello, I would like to work on this issue. Could anyone guide me on how to get started? :)

**Comment by MSeifert04** [comment]
@sathe-aditya There is already a recent pull-request to fix this issue (#5550). It's not merged yet but I think it's almost completed.

**Comment by embray** [comment]
@sathe-aditya FWIW you're likely to have better luck if you just fix an issue and make a pull request--you don't have to ask permission (though *do* check that there isn't already an in-progress fix to the problem--you can see this in GitHub right above your comment, where it shows that a PR is referencing this issue).  Make sure also that before asking for help you've read the [contributing guidelines](https://github.com/astropy/astropy/blob/master/CONTRIBUTING.md) and at least some of the documents linked to from there.  Otherwise I'm sure people will be happy to provide guidance, but they are more likely to do so if they've seen some initial effort on your part.

(To be clear, this is not to single you out either--this is general guidance to would-be contributors to almost any open source project.  Rule of thumb: project mantainers are busy, and while generally happy to provide guidance, much happier to when they don't have to take the initiative.)

**Comment by sathe-aditya** [comment]
@MSeifert04 Okay! :)
@embray Thank you. I will keep that in mind! :D

**Comment by pllim** [comment]
#5550 is merged and this issue is now closed. Thank you for your interest anyway!
