### ISSUE TITLE
Add a method to generate a zero-length copy of current table?

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#3742]
Inspired by [discussion on astropy](http://mail.scipy.org/pipermail/astropy/2015-April/003729.html), should we add a method to `Table` that will generate a zero-length copy of a `Table` object?

The implementation is simple.  `return Table(self[:0])`.  I think that's it!

I think this should be an instance method, not a class method since it is predicated on already having a table.

It could be called `zero_length_copy` to be explicit.  We might also add an `max_rows` arg to `copy()` which would default to None (= no limit)?  I'm a little :-1: on `empty_like` because that has a different meaning in numpy (same number of rows, just uninitialized).

**Comment by taldcroft** [comment]
@embray notes:
```
For what it's worth though, I feel like Alexa's original attempt should have
just worked though.  If the original dtype is a multi-field dtype (i.e. has a
non-empty .names attribute, which is true for the dtypes on tables), then it
should be sufficient to create a new table with:

new_table = Table(dtype=orig_table.dtype)

it wouldn't even be necessary to explicitly provide a names= argument, since
those can come from the original table's dtype (although if names= is provided
that should override the names in the dtype as long as it's the correct number
of names).

Having empty_like and such sounds fine too, but I don't see why the above
example shouldn't work...
```

This is a good point.  Although this would not handle a table with mixin columns, in the more usual use case of standard columns it should be made to work.

**Comment by embray** [comment]
Good point about mixin columns; that's a good argument to still have a special method for this.  But yes, just initializing a table with `dtype=` out to generally work (on any subclass too, just using whatever the default `ColumnClass` is).

**Comment by anchitjain1234** [comment]
@taldcroft @embray What implementation has to be followed finally, add new method ``zero_length_copy`` or add new argument ``max_rows`` to ``copy()`` method?

**Comment by taldcroft** [comment]
I like `max_rows`, so why don't you do that.

**Comment by anchitjain1234** [comment]
Thanks @taldcroft.

**Comment by mhvk** [comment]
I'm slightly confused about why one wouldn't just do `table[:0].copy()`?

**Comment by taldcroft** [comment]
The idea is to find a solution that will be more obvious (or guessable) to users.  I am not completely sure that `max_rows` fits the bill, but maybe better than nothing??

**Comment by mhvk** [comment]
Hmm, yes, looking back at the original thread, I can see the confusion, and the thought of passing in a table dtype in the initializer is something I might have guessed as an option myself.  But I think in that case `max_rows` in the `copy` method is not much better. Could we not just add something to the `Table` docstring and the documentation?

**Comment by taldcroft** [comment]
@mhvk - agreed, perhaps just a new example would do the trick.

I think one way to go is to change the section heading of http://docs.astropy.org/en/stable/table/construct_table.html#table-columns from `Table columns` to `From existing table` and then add the example of creating a copy of an existing table that is empty (has no rows) to the end.

I think this is too specific for the `Table` docstring though.

About making the `dtype` initializer work, it's worth noting that I don't see how it can ever work for `QTable` since any units get lost.  I'd rather just say that `dtype` can't be used to make an empty table rather than "it works sometimes, but not in other situations.  Try your luck!"

**Comment by mhvk** [comment]
Agreed that the `dtype` could not work (unless it starts to carry units, which is apparently being thought off, as many numpy developers feel it should be the place for information on what the bytes in the array mean; but that will be quite a while...). I only mentioned I thought it was not illogical to think it would work, since, given subsequent failure, it would then be logical to do `Table?` in `ipython` hoping to find a solution. But you are right that it is probably too specific for `Table.__doc__`.
