### ISSUE TITLE
ah_bootstrap.py broken on setuptools 8.0

### ISSUE THREAD

**Issue by Chekov2k** [astropy/astropy#3745]
I'm using Mac OS X 10.10.3 with a brewed python 2.7.9. If i try to install astropy 1.x using pip or manually I get the following error:

```
Wladimir:astropy-1.0.2 balzer$ python setup.py
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import ah_bootstrap
  File "/Users/balzer/Downloads/astropy-1.0.2/ah_bootstrap.py", line 921, in <module>
    BOOTSTRAPPER = _Bootstrapper.main()
  File "/Users/balzer/Downloads/astropy-1.0.2/ah_bootstrap.py", line 217, in main
    bootstrapper.run()
  File "/Users/balzer/Downloads/astropy-1.0.2/ah_bootstrap.py", line 303, in run
    dist = method()
  File "/Users/balzer/Downloads/astropy-1.0.2/ah_bootstrap.py", line 371, in get_local_directory_dist
    upgrade = self._do_upgrade(dist)
  File "/Users/balzer/Downloads/astropy-1.0.2/ah_bootstrap.py", line 524, in _do_upgrade
    next_version = _next_version(dist.parsed_version)
  File "/Users/balzer/Downloads/astropy-1.0.2/ah_bootstrap.py", line 810, in _next_version
    for part in version:
TypeError: 'Version' object is not iterable
```

The fix for me is to change line 810 in ah_bootstrap.py:

```
        for part in version:
```

to

```
        for part in str(version).split('.'):
```

**Comment by embray** [comment]
@Chekov2k Thanks for the report--could you please let me know what 
```
python -c 'import setuptools; print(setuptools.__version__)'
```
returns for you?  I think this is more an issue with some older setuptools versions than anything else.

**Comment by Chekov2k** [comment]
Here you go

u031055:~ balzer$ python -c 'import setuptools; print(setuptools.__version__)'
8.0

**Comment by embray** [comment]
Thanks for the quick reply.  Yes, I think that would be it.  This is still a bug that should be worked around (the workaround you provided should be a start).  But you can fix this right now by upgrading your setuptools with
```
pip install setuptools --upgrade
```

**Comment by Chekov2k** [comment]
Just did that, didn't realise it was that old. I'm using pip-tools and thought thy would update the setuptools as well...

**Comment by embray** [comment]
@Chekov2k It really isn't *that* old.  But they changed a lot of stuff recently (in particular related to version parsing) and so it's been hard to keep up with support for every different version's quirks :/  I don't know what pip-tools is, but I'll look into it.  Did the upgrade fix it for you?

**Comment by Chekov2k** [comment]
Yes, just removed it and reinstalled via pip 
Works fine now :-)

**Comment by embray** [comment]
Great, thanks for checking.  I'll leave this issue open until the fix is in astropy-helpers.

**Comment by bsipocz** [comment]
Closing this issue as this is about a very old setuptools version, and probably it won't get fixed. Feel free to reopen if you think it's still relevant.
