### ISSUE TITLE
astropy.table.join on different colnames

### ISSUE THREAD

**Issue by AstroMike** [astropy/astropy#3752]
As I understand it, for astropy.table.join to work, the columns in the two tables must have the same colnames.  This means that, for example, you can't join two tables if in one table the colname is 'Name' whereas in the other it is called 'name'. 

Of course, I guess you can workaround by renaming one of the columns but that seems kludgye.

It would be nicer to enter a tuple (leftcol, rightcol), but that is interpreted as a list of all columns on which to join (col1, col2).

**Comment by taldcroft** [comment]
This seems like a reasonable idea.  Right now you can enter a list of column names, so the syntax could be extended to also allow a list that includes 2-tuples.  E.g. `keys=[('name', 'Name'), 'other_key']`.  In your original use-case you would have to do `keys=[('name', 'Name')]` to disambiguate from `keys=('name', 'Name')`, but that seems better than the alternative of adding some keyword args.

The reservations are:

- It will add complexity to an already-complex function that finds the column names mapping when merging a list of tables.  Not a show-stopper but complexity and reliability don't go hand in hand.
- The output column name has to be arbitrarily chosen from either the left or right name.  Presumably the left, but this ambiguity is not nice.

An alternative would be a context manager to temporarily rename table columns.
```
with t2.rename_columns('Name', 'name'):
    t12 = table.join(t1, t2)
```
Just a thought...

**Comment by AstroMike** [comment]
For me the suggested extension works, although as noted there is the subtle approach to making lists of tuples a potential source of errors.

As to the alternative, personally I haven't figured out how to use `with` correctly ....

**Comment by embray** [comment]
I've been bugged by this recently too, but figured it would add just that more complexity, and found it good enough to make a temporary copy with one of the columns renamed.

@AstroMike without diverging into a full explanation of the `with` statement and context managers, what the example @taldcroft gave would do is it would create a temporary *context* wherein one the table `t2`'s columns is renamed for all the code in that context, and then returned to its original name.  In this case the "context" is defined as any code that's indented under the `with` statement--as far as all that code is concerned, the "Name" column in `t2` is now called "name".  When that context is existed it returns back to "Name".  This would just allow forgoing the extra overhead of creating a copy.

**Comment by hamogu** [comment]
-1 to adding any more api complexity. Renaming the column of a table only takes one line of code, and renaming it back a second line. I don't think that even the `with` is really needed. It only saves one line and chances are that you won't find it in the docs when you need it.

**Comment by bsipocz** [comment]
Just need this very feature today. I've given the workaround to the docs in  #4118.

Sadly doing it with ``with``  fails with ``AttributeError``.

**Comment by taldcroft** [comment]
Just wondering aloud.. what about adding a `context_manager` keyword to `rename_columns`.  If `True` than this method would return a context manager object.  E.g.:
```
with t2.rename_column('obj_id', 'name', context_manager=True):
    t12 = join(t1, t2, keys='name')
```
My original suggestion of having `rename_columns()` always return a context manager wouldn't quite work since you a normal call to `rename_columns()` should just return None.

**Comment by bsipocz** [comment]
See more discussion of the same in the duplicate issue https://github.com/astropy/astropy/issues/5470.
