### ISSUE TITLE
Consider changing Time.format attribute to Time.representation (to allow a general .format attribute for astropy classes)

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#3765]
From @mhvk in #3763:

Consider a possible change in name from format to representation (cc'ing @eteq, @astrofrog, @embray, @mdboom in case). One argument for switching to representation now is that all over astropy we could be using format as a string that will be parsed by __format__ by default, i.e., something similar to Column's format. For Time, this probably means that time.format would by default be calculated to contain some combination of representation, outsubfmt, and precision (say {0.fits:.3longdate}).

Note that it does not actually affect the use of Time much at all: really, we would only have to support (possibly indefinitely) the format keyword argument as an alternative to representation. I think very few people would so far have used the format property. But of course this will change with this PR, hence my feeling that we should think carefully now. (On the other hand, to weaken the argument: arguably, the format setter would need to change representation anyway, so perhaps this is not such a big deal. This does make we wonder, though, if the TimeFormat classes are actually the right place to hold jd1, jd2 -- but that definitely is for another time.)

p.s. So far, we are using __format__ in Unit and Quantity only, and there it does not yet have memory of the preferred format via a format attribute -- but this should change for Quantity at least, now that it can be a column in a table.

**Comment by mhvk** [comment]
Just so it's explicit: the milestone is there since this needs a *decision* before 1.10, because with #3763 in place changing name will become even harder.
The short version of the above is that it would be nice if all relevant astropy classes allowed `<astropy-object>.format` to contain a complete format specification for that object.

**Comment by taldcroft** [comment]
One thing to consider is that for mixin columns we'll really need to be using the `obj.info.format` attribute as the object that specifies and maintains the desired output format (or whatever `info` ends up being named).  For classes that astropy owns we can certainly make `obj.format` be a wrapper for `obj.info.format` as a convenience, but in terms of a general API it needs to be `obj.info.format`.

**Comment by taldcroft** [comment]
> The short version of the above is that it would be nice if all relevant astropy classes allowed <astropy-object>.format to contain a complete format specification for that object.

Except that `Time` won't be able to do this for at a couple of years because of LTS for 1.0.

**Comment by embray** [comment]
I'm not sure what you mean here.  The LTS does not in any way impede new development.

**Comment by taldcroft** [comment]
@embray - what I mean is that I think it would be bad if `time_obj.format` had one meaning in astropy 1.0.x (i.e. Time format name like `isot` or `unix`) and a different meaning in 1.2+ (e.g. format specifier like `{0.fits:.3longdate}` as in the example from @mhvk).  In other words repurposing a keyword or attribute seems more problematic than simply renaming it and having the old one disappear.  Since we are intending that some users could be on 1.0.x for 2 years the overlap is worse.

I also think that this API change will be relatively painful compared to the payback (consistent naming with Quantity and SkyCoord).  At least in the context of Table and mixin columns, you would always need to write `obj.info.format`, `obj.info.name`, etc anyway in order to be sure it will work with any mixin class.  So having shortcuts `obj.format` for a select set (Time, Quantity, Skycoord) may not help that much.

This is digressing a bit, but as I think about the `info` object it really can take on the role of a generic metadata container that could be useful even outside the context of Table.  `info` will have a name, description, format, meta, and perhaps UCD, and it should be persistent for at least some operations like slicing.  It's not that you always want all this stuff, but in some circumstances it could be useful, and this machinery can be attached to any object where you can add an attribute (tentatively named `info`).  Part of the point is to reduce the potential for attribute namespace collision by bundling all this under a parent `info`.  It's a reasonable point that `info` might be too generic, but that is a slightly different discussion.

**Comment by mhvk** [comment]
@taldcroft - I think you are right that there are really two questions:
1. Is it worth renaming `format` to `representation` just as that is perhaps the better word, also used in `SkyCoord` and it doesn't have a pythonic connotation?
2. Should we start supporting a `format` property that remembers how the default formatting of the object.

Here, the first is perhaps easier without the second, but also less compelling. For the second, I think you may be right that we could just use the new `info` attribute to hold all this type of meta information (maybe it should just be `meta`...).

**Comment by embray** [comment]
I see, if nothing else from a pedagogical perspective that could get very confusing.

**Comment by eteq** [comment]
I think it's a good idea to start trying to use `representation` instead of `format` for the reason 1 @mhvk gave in his comment two above this one.  But I agree with @taldcroft that a backwards-incompatible switch to `format` being like string formatting is potentially very painful. So for better consistency a middle road might be to deprecate `format` in favor of `representation` but *not* necessarily ever replace it with new functionality - just have it be a perma-deprecation.

**Comment by mhvk** [comment]
I'm happy with that middle road, and am willing to implement it if @taldcroft agrees that this is worth doing. The one difference that would slowly get people to move would be that `representation` would be settable (as in #3763), but `format` would not.

**Comment by taldcroft** [comment]
I think that we as a project need to think really hard about making a major API change to a stable subpackage for which we say "API likely to remain stable for the foreseeable future.".  Breaking that commitment shouldn't be taken lightly.  In this case it seems the benefit is a small improvement in API consistency in having `representation` used in two places instead of one.  To me that doesn't seem worth the pain factor for users.  (Since all are generally agreeing that repurposing `format` to have a different meaning is even worse and so `format` will just be perma-deprecated.)

My original statement on this was that I *wish* that we had used `representation` in the original design but that it wasn't worth changing.  I still believe that so I'm going to say I'm :-1: on this proposal.  Of course that shouldn't stop anyone from arguing why the benefit will exceed the pain.

**Comment by embray** [comment]
Perhaps we could list this as a known wart, and change it in v2.0.  Major version increases are a good place to make big backward-incompatible changes like that.

**Comment by mhvk** [comment]
Actually, I think this thread has convinced me this is not quite worth it. My end-goal was using `format` to store the preferred format of any object, just as Column does, but I think it is more likely this is going to be elsewhere (as will be a name, etc.; maybe in the end `Column.format` will just link to that "elsewhere" as well). Then, given how many times I have used `Time(..., format=<something>)` myself, I think the pain really is not worth it any more.

So, I'll close. Thanks for the patience...
