### ISSUE TITLE
Add the unit 'crab' to astropy.units

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3775]
See http://en.wikipedia.org/wiki/Crab_%28unit%29

**Comment by mdboom** [comment]
It's already defined for the unit formats that require it, but it's sort of problematic to define universally, no?

OGIP has this to say about it:

> Finally the `crab' was commonly used in the early days of X-ray astronomy. However this unit (or more commonly the `millicrab') should be avoided wherever possible as the conversion to more standard specifications of flux density is a function of the spectrum of the source (relative to that of the Crab). Strictly speaking, the same is true regarding the use of stellar `magnitudes' (mag).

CDS defines it as

> 1.43×10–11kg⋅s–3

which I think is different from the definition in the wikipedia article.

In short, it seems the only reasonable thing to do with Crab is to maintain it as a disconnected unit by default, and possibly add a short cut to enable it on some standard definition (such as the one on Wikipedia) if that standard case is common enough to warrant it.

**Comment by mhvk** [comment]
I agree `u.Crab` should only go in as a disconnected unit; there is no standard conversion, so if someone wants to convert, they should set up an equivalency themselves.

**Comment by cdeil** [comment]
In gamma-ray astronomy (as in the olden days of X-ray astronomy) it's common to quote fluxes in Crab units. That's why I've added a [crab_flux](https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.crab_flux.html) and [crab_integral_flux](https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.crab_integral_flux.html) function to Gammapy that can be used to compute Crab differential fluxes at given energies and integral fluxes in given energy bands.

I see two major problems with adding this as a flux unit to Astropy:
* The Crab pulsar and nebula SED is complex and in many parts of the spectrum not very precisely known or even variable. I've got a collection of all non-thermal measured Crab fluxes [here](https://gammapy.readthedocs.org/en/latest/tutorials/crab_mwl_sed/crab_mwl_sed.png). So we'd have to pick one SED model or provide several as I do in Gammapy.
* I think an energy- or wavelength-dependent unit and a different one for differential and integral fluxes doesn't fit in the Astropy units framework?

Maybe this is more something for an SED class (if at all) than a simple unit?

**Comment by cdeil** [comment]
It's funny, this spec mentions the Crab unit, but it doesn't define a value for it:
http://heasarc.nasa.gov/docs/heasarc/ofwg/docs/general/ogip_93_001/ogip_93_001.html

FYI, in case this goes anywhere, in gamma-ray astronomy this is a good reference for Crab SED model and what I put as default in Gammapy:
http://adsabs.harvard.edu/abs/2010A%26A...523A...2M
(gamma-ray astronomy and this paper is not mentioned on the Wikipedia page ... that page should be updated also)

**Comment by mhvk** [comment]
Agree that it is too variable and poorly defined. As I mentioned above, in principle one could still use it if one also defines an equivalency. If for that purpose it helps to have a disconnected unit `u.Crab`, I think we could have that. (Right now, it only exists in `cds` -- `u.Unit('Crab', format='cds')`.

**Comment by embray** [comment]
Could make Crab a *callable* unit in the vein of #1894 (different semantics here, but the point is you could do `u.Crab(wavelength)` and it would return the correct flux unit from the reference spectrum.  We could borrow the `crab_flux` function from GammaPy.

**Comment by mhvk** [comment]
@embray - I don't think that that is a good idea -- callable units should be strictly for units that really are functions of other units. Here, it would seem to make much more sense to use the equivalency with a parameter for that (as we do already to convert λFλ to νFν).

**Comment by cdeil** [comment]
Is it also possible to have integral fluxes, i.e. in bands `(wavelength_lo, wavelength_hi)`?
What about different references (e.g. paper A, B, C and pulsar vs. nebula)?

Even if the answer to this is yes, do the units / quantity experts think this should be defined as units? Or would functions `crab_flux(wavelength)` and `crab_integral_flux(wavelength_lo, wavelength_hi)` that return quantities and then people compute flux ratios for their sources be simpler?

Are something so ill-defined as the Crab SED welcome as a unit in Astropy core?

(I've been wanting to improve the versions in Gammapy to use units and the SED integration method currently is too unstable. Once there is consensus on location and API I can make a PR for Astropy or Gammapy for this.)

**Comment by embray** [comment]
I think all of those options could be supported through a callable unit.  There's no limit to what it could take as arguments.

I don't see why callable units should be strictly for functions of other units.  If it's a function of a *quantity* it just has different semantics than log units, etc.

**Comment by mhvk** [comment]
@cdeil - my tendency would be to have this in Gammapy as I think it depends too much on what one wants. Whether you implement it as an equivalency or a function would be up to you. With an equivalency, one could do things like:
```
with crab_equivalency(reference=..., mission=...):
    nufnu = measurement.to(u.erg/u.cm**2/u.s)
    ...
```
But even so, you would probably first write a conversion function, and then define an equivalency list that simply uses it; for a relatively complicated existing example, see
https://github.com/astropy/astropy/blob/master/astropy/units/equivalencies.py#L86

**Comment by mhvk** [comment]
Thinking more about the "Crab" unit, I realised that of course there is an even more (in)famous example of such an ill-defined unit, viz., "Vega". For that, similarly, one has conventional conversions, but for special cases needs to integrate over a bandpass, etc. I do think that that one also is most easily handled via an equivalency (say, `u.magnitude_zero_point(band='V', reference='bessell')`.

But: one can actually build the equivalency into the unit itself (this is used in the logarithmic units, which have a built-in equivalency between themselves and their physical unit). So, one could envision constructing a Crab unit that would do similarly. Say, something like:
```
import astropy.units as u
class EquivalentUnit(u.IrreducibleUnit):
    def __init__(self, st, equivalencies=[], doc=None,
                 format=None, namespace=None):
        self._equivalencies = []
        for equivalency in equivalencies:
            # replace st with self
            new_equivalency = tuple((self if part == st else part)
                                    for part in equivalency)
            self._equivalencies.append(new_equivalency)

        super(EquivalentUnit, self).__init__(st, namespace=namespace,
                                             doc=doc, format=format)

    @property
    def equivalencies(self):
        return self._equivalencies

    def to(self, other, value=1.0, equivalencies=[]):
        equivalencies += self.equivalencies
        return super(EquivalentUnit, self).to(other, value, equivalencies)

crab = EquivalentUnit('Crab',
                      [('Crab', u.erg/u.cm**2/u.s,
                        lambda x: 2.4e-8 * x,
                        lambda x: x / 2.4e-8)])

(1.*crab).to(u.W/u.m**2)
# <Quantity 2.4000000000000004e-11 W / m2>
(2.4e-11*u.erg/u.cm**2/u.s).to(crab)
# <Quantity 0.001 Crab>
```

Of course, the above example does nothing more than a normal `Unit` would do that just represents a flux of `2.4e-8 * u.erg/u.cm**2/u.s`. But obviously, one can have a much more complicated function than used here.

I do think this would be a nice way to use units, and it would be how I would recommend proceeding in `gammapy` for now. Eventually, like for the vega units, I think we do want to collect those in a special category of units in astropy itself, but it would be better to try how things work in practice first.

**Comment by embray** [comment]
@mhvk That's exactly what I was thinking--I love the `EquivalentUnit` idea.

**Comment by pllim** [comment]
Arghhh... Vega... :ghost:

**Comment by mhvk** [comment]
@embray - OK, now I see more what you were going for. You're right that this is not that dissimilar from how I wrote `u.dex`, `u.mag`, and `u.dB`. Those are units that are disconnected in themselves, but when called set up a function unit that basically works via equivalencies, while at the same time disabling most of the normal unit interactions (cannot sensibly divide and multiply, but can add and subtract). For `Crab` one could have instead default built-in equivalencies, but the option to call the unit with a different set.

BTW, note that at least by default my suggestion only works if `Crab` is not part of a compount unit; it would need some work to allow, e.g., `(1.*u.mCrab('x-ray') * 100. * u.m**2).to(u.W)`

**Comment by embray** [comment]
Yes, I think it could be initialized with some default equivalencies like in your example above, while still be *callable* to allow customization.

**Comment by shwetamore1295** [comment]
@embray @astrofrog If this issue is still open, I would like to work on this issue.

**Comment by pllim** [comment]
Looking at the discussions again, I think it had evolved from being "novice + good first issue" to something else. Can someone summarize what was actually the consensus here? Or do we even need this unit still?

**Comment by mhvk** [comment]
I think it is still a nice idea, but I definitely agree this is not a beginner's issue any more.... I fear that the person who wants to try to implement it will need to read the above and think...

**Comment by cdeil** [comment]
My suggestion would be to not put this in Astropy and just close the issue.

If you implement it it'll be pretty complex: wavelength dependency, spectral equivalencies to have it as a function of energy or frequency or wavelength and most importantly - different reference spectra from the literature. So you'd probably get something complicated, and than it's not so useful to the few Astropy users that would use it, because hard to learn.

Just for reference, here's what we currently have in Gammapy for the very-high-energy gamma-ray part of the Crab spectrum: https://docs.gammapy.org/0.11/api/gammapy.spectrum.CrabSpectrum.html

**Comment by mhvk** [comment]
@cdeil - if you don't think it is useful, then definitely we should not do it (and your arguments make sense). I'll close this issue.
