### ISSUE TITLE
Remove any Python 2.6-specific code and workarounds

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3780]
This includes a number of the 'compatibility' packages. This should be done after v1.1 is out.

**Comment by eteq** [comment]
Note that #4225 updates the *testing* to not run in 2.6, but does not actually remove all the workarounds

**Comment by embray** [comment]
BTW, not that we haven't decided to drop Python 2.6 support anyways, but Nick Coghlan also says stop supporting Python 2.6: http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

**Comment by hamogu** [comment]
@astrofrog: I think you have opened new PRs to remove this stuff, right?
So, is this issue still needed?

**Comment by astrofrog** [comment]
@hamogu - I think it's all done :) (of course, I'm sure I've missed a couple of small things which we'll find in future)
