### ISSUE TITLE
build error with python 2.6.9

### ISSUE THREAD

**Issue by prodev-paris** [astropy/astropy#3801]
I download last astropy version (astropy-1.0.2.tar.gz) from https://pypi.python.org/pypi/astropy
Then after uncompress and untar, I proceed, [as documented](http://www.astropy.org/) , with a `python setup.py install --user` (note that I use `--user` since I want it to be installed locally in my home dirs...).

But I obtain the following errors:
```
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    package_info = get_package_info()
  File "~/astropy-1.0.2/astropy_helpers/astropy_helpers/setup_helpers.py", line 538, in get_package_info
    ext_modules.extend(setuppkg.get_extensions())
  File "astropy/wcs/setup_package.py", line 191, in get_extensions
    generate_c_docstrings()
  File "astropy/wcs/setup_package.py", line 124, in generate_c_docstrings
    from astropy.wcs import docstrings
  File "~/astropy-1.0.2/astropy/wcs/__init__.py", line 28, in <module>
    from . import utils
  File "~/astropy-1.0.2/astropy/wcs/utils.py", line 6, in <module>
    from .. import units as u
  File "~/astropy-1.0.2/astropy/units/__init__.py", line 18, in <module>
    from . import si
  File "~/astropy-1.0.2/astropy/units/si.py", line 214, in <module>
    doc="curie: unit of radioactivity")
  File "~/astropy-1.0.2/astropy/units/core.py", line 2249, in def_unit
    format=format)
  File "~/astropy-1.0.2/astropy/units/core.py", line 1798, in __call__
    raise TypeError("{0} can not be converted to a Unit".format(s))
TypeError: [u'Ci', u'curie'] can not be converted to a Unit
```

$> python --version
Python 2.6.9

**EDIT:**
Note that before trying to install [astropy] I launch several build/install process regarding [healpix], [cfitsio] and [healpy] that may have lead to an unwanted configuration scheme...

**Comment by mdboom** [comment]
It's puzzling that the traceback alternates between relative paths and `~/astropy-1.0.2`.  Do you have your `PYTHONPATH` set to anything?

**Comment by prodev-paris** [comment]
Sorry to not have mentioned that I replace the fullpath with '~' for _clarity_ in the log.

**Comment by mdboom** [comment]
Did you change the relative to full paths?  What I'm concerned about (that indicates some sort of environmental configuration problem) is: `astropy/wcs/setup_package.py` vs `~/astropy-1.0.2/astropy/wcs/__init__.py`

**Comment by embray** [comment]
The fact that something would blow up in the units module during package installation definitely suggests an environment problem, with astropy somehow being imported from multiple paths simultaneously.

**Comment by prodev-paris** [comment]
Oh yes you are right, I was trying to install previously healpix and cfitsio (as explained in doc: ["Building against external Healpix and cfitsio"](https://healpy.readthedocs.org/en/latest/install.html)) then I was coming back to healpy sources and trying to install it! <--- I think the mix comes from this stage!
Now I can't even reproduce the error...
Thanks for your help!

**Comment by mdboom** [comment]
No problem.  Glad to help.

**Comment by embray** [comment]
Looking at this, it might be good for `get_package_info` to catch a wider berth of exceptions that might occur during import and running of setup_package modules so that we can give more helpful messages rather than arbitrary bizarre tracebacks.
