### ISSUE TITLE
Possibly include workarounds for remaining io.fits issues with Numpy 1.10

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3803]
In #3419 I fixed most of the bugs in io.fits with Numpy 1.10.dev.  There is a small remaining issue that will be fixed by numpy/numpy#5921.  If I can finish that PR and get it merged in time then no action is needed and this issue can be closed.  Otherwise we'll have to at least temporarily include a workaround.

**Comment by astrofrog** [comment]
@embray - thanks for your efforts on this! Once all issues are fixed, I think the Travis build for numpy-dev should maybe be upgraded to not be an allowed failure? (so we can catch issues sooner)

**Comment by embray** [comment]
I'm :-1: on that regardless, but it's up to you.

**Comment by astrofrog** [comment]
I guess it'll be brittle if Numpy has bugs introduced so it will be a pain to have all our builds fail. But we need to make sure we keep a good eye on that entry on Travis then to spot issues early. I might right a little daemon that can check the status of that job and email a subset of people the first time that job fails.

**Comment by embray** [comment]
Could just write a separate little script to run that job and intersect its error code, then send an e-mail.  That is, you would call that script from the travis recipe.

**Comment by embray** [comment]
Okay, the fixes have been merged in Numpy so nothing more to do here for now :)

**Comment by embray** [comment]
Also, confirmed that all tests in current master pass against current master of Numpy, at least on Python 2.7.
