### ISSUE TITLE
PowerLaw1D assumes negative power

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3804]
The PowerLaw1D model currently assumes something like y = a \* x *\* -alpha but the default should really be y = a \* x *\* alpha. I'm fitting a positive power-law and it's pretty confusing to have power values returned as negative. People fitting inverse power laws on the other hand will be expecting negative powers.

To maintain backward-compatibility, I would suggest renaming the variable for the power and keeping a reference to `alpha` which would be minus the actual power. The actual power could be called `power`.

cc @embray @nden

**Comment by embray** [comment]
@keflavich is most likely to be able to shed some light on this, as the original implementer of that model.

My guess is that it was inspired by the [powlaw1d](http://cxc.cfa.harvard.edu/sherpa4.4/ahelp/powlaw1d.html) model in Sherpa, which is defined the same way. Though I wonder if this is due to how it's most used in Chandra-related contexts.

**Comment by pllim** [comment]
:+1: to @astrofrog's suggestion

**Comment by keflavich** [comment]
@embray I can't explain what I was thinking exactly, but perhaps I had powerlaw distributions in mind, which require a negative index to be meaningful.  It's equally likely that I was following a convention in some previous iteration of a spectral package, sherpa, xspec, or something, as you said.  Anyway, :+1: to @astrofrog's approach

**Comment by embray** [comment]
That would make sense, in the sense of a distribution.  I feel like this is more generic though.

**Comment by embray** [comment]
@astrofrog Do you think we should outright *deprecate* the current negative alpha parameter?

**Comment by astrofrog** [comment]
@embray - I don't feel strongly about that, so will leave it up to you :)

**Comment by pllim** [comment]
:+1: for deprecation

**Comment by cdeil** [comment]
:-1: on changing this.

There's good reasons to leave it alone:
* Breaking user code is bad, for consistency you'd have to change [all four available powerlaws](http://astropy.readthedocs.org/en/latest/modeling/index.html#module-astropy.modeling.powerlaws)
* No real advantage. Some people expect +, some -. The most common other astro modeling / fitting package, Sherpa, uses the same sign as the current implementation.
* `import this` says "there should be one way to do it". Adding an aliased `power` parameter with opposite sign from `alpha` means half the users will do this, the other half that.
* If this goes in, I might start filing more issues and pull requests to change signs in models, e.g. we should really re-visit the rotation angle directions in 2D models a few times. :-)

**Comment by astrofrog** [comment]
@cdeil - this won't break any user code though as it's easy to provide backward compatibility while removing it from the documentation.

**Comment by embray** [comment]
@cdeil Makes a good point though about it being confusing if there are two ways to provide a power, once of which makes it negative implicitly, and it's easy to get confused.  I don't see much advantage to changing it where it's fine how it's documented.

I think this could go either way though.  If I were doing it over from scratch I would have made the power positive by default.  I also think a lot of useful power laws in physics are going to have a negative exponent anyways.  

Maybe this is something that should be put up to a vote before changing anything.

**Comment by aniketk21** [comment]
@astrofrog If this issue needs to be fixed, I'd like to work on it.

**Comment by pllim** [comment]
Revisiting this now -- I'm thinking maybe we should just close this as "won't fix". That is because all models in the powerlaws module now assume negative alpha, not just 1D. Too much work to justify the end...

**Comment by astrofrog** [comment]
Ok, sounds good. I think as long as the documentation is clear, this is fine. If users start complaining, we can re-assess, but for now it was just me ;)
