### ISSUE TITLE
Sine1D model missing offset

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3807]
The Sine1D model in astropy.modeling is missing a parameter for the horizontal offset, i.e. it should be a * sin(b*x + c)

**Comment by embray** [comment]
I agree--I always felt that a "phase" parameter should be added.

**Comment by sYnfo** [comment]
I would like to look into implementing this, but first I would like to know how do you handle API compatibility? Should the phase parameter be implemented as a named argument with a reasonable default or is it OK to break API compat in master?

**Comment by embray** [comment]
@sYnfo most or all of the current built-in models use keyword arguments for the parameters.  The only thing that would seriously break compatibility would be to change the order of the parameters.  I think the "phase" parameter would make most sense as the third parameter anyways, so adding it won't break anything.

**Comment by embray** [comment]
I guess if it did break anything it would be that the `fit_deriv` would now be returning a third column.  But I'm not too worried about that--if anyone *is* writing code that uses `fit_deriv` directly and uses hard-coded assumptions about its return value will have to be admonished not to.  (Note: Not  that there's any problem with using it directly, but I don't think they should make hard-coded assumptions about the shape of its return value.)

**Comment by sYnfo** [comment]
Oh, perhaps I don't understand how the models are implemented/used, then. My point was that if I change the method definition from e.g. ```def evaluate(x, amplitude, frequency)``` to ```def evaluate(x, amplitude, frequency, phase)```, then anyone using these directly will get TypeError now.

I'll read up on how the models are used.

**Comment by embray** [comment]
@sYnfo Oh, that's a decent point.  But really evaluate isn't meant to be used directly--instead you just call the the model instance like,

```python
s = SineModel(amplitude=1, frequency=1, phase=0)
s(np.linspace(-2 * pi, 2 * pi, 100))
```

One could argue that `evaluate` should be called `_evaluate`, but I can envision cases where it might be useful incorporate a model's evaluate into other functions without using the model class directly, so it's kept as a "public" method.

I wouldn't worry about changing the signature of the `evaluate` so long as we list in the in the API changes in the changelog.  Worse comes to worse it could be given as a keyword arg for now.
