### ISSUE TITLE
Include ability to select existing observatories for EarthLocation

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3813]
It would be nice to have ``EarthLocation.from_name`` and be able to pass observatory names, for example based on the following list:

http://tdc-www.harvard.edu/iraf/rvsao/bcvcorr/obsdb.html

(requested by a user at an Astropy workshop)

**Comment by bsipocz** [comment]
:+1:

what about using the MPC list? There are way more observatories listed, and I guess is a bit more standardized of how to add a new one, etc. http://www.minorplanetcenter.net/iau/lists/ObsCodesF.html

**Comment by mhvk** [comment]
Yes, good idea. Note that the iraf list only seems to include optical observatories. The MPC one is better, but doesn't have height, at least not in the list given (they do seem to ask for height in submitting observatory information).

**Comment by cdeil** [comment]
:+1: to add this.

As an example, I have a list of gamma-ray observatories here:
https://github.com/gammapy/gammapy/blob/master/gammapy/obs/observers.py
That's probably not the format how we want to maintain this though.

* Should this only query a curated list (CSV or JSON file) we in Astropy maintain?
* A separate repo so that anyone can easily contribute additions?
* Is there (in addition or alternatively) a good earth location name resolver on the web, i.e. a SESAME for Earth?

cc team [astroplan](https://github.com/astroplanners/astroplan): @jberlanga @bmorris3 @ejeschke, @adrn @eteq

**Comment by bmorris3** [comment]
Heads up: I'll be working on this for my GSoC project with [astroplan](https://github.com/astroplanners/astroplan), which we might be able to port over to astropy when it's done.

**Comment by eteq** [comment]
To answer @cdeil's questions, btw, I am not aware of any web name resolver, so I'd say it's a curated list that Astropy maintains.  A separate repo would be a lot of pain for not too much gain, I think.

**Comment by bmorris3** [comment]
About this MPC list, @bsipocz - the latitude is not explicitly given, but the parallactic constants: 

> parallax constants (rho cos phi' and rho sin phi', where phi' is the geocentric latitude and rho is the geocentric distance in earth radii)

so we need to know what constant for Earth-radii was being used by the table curator. Any ideas who to ask for this?

**Comment by bsipocz** [comment]
@bmorris3 - not sure whose task to deal with this at MPC and I don't know whether any of the staff has a github account. But they are a friendly group, and I guess your best bet to e-mail Garreth (gwilliams at cfa) and ask him about it.

**Comment by bmorris3** [comment]
Thanks! After some discussion on our end we've opted to play with the [IRAF](http://tdc-www.harvard.edu/iraf/rvsao/bcvcorr/obsdb.html) list instead since that list is exclusive to "major" observatories.

**Comment by bsipocz** [comment]
But then you give a big clean up to  that list right, as there're multipled
entries, as well as ambiguous ones?

**Comment by bmorris3** [comment]
That's the hope. The IRAF list is shorter and will be easier to clean and update than the MPC one.

**Comment by mhvk** [comment]
I think the main downside to that list is that it contains only optical observatories, and I don't quite see the point to delegating maintenance of the list to a project that has no official support (in contrast to MPC, which is an official IAU outfit).

As an alternative, the nautical almanac had a list of observatories as well.
See section J in http://www.willbell.com/almanacs/AstronomicalAlmanac2016.html

However, it is rather unclear if that is publicly available.  But there is a searchable form at  http://asa.usno.navy.mil/SecJ/Observatories.html; I'd guess we could get programmatic access to that list if we asked.

**Comment by bsipocz** [comment]
What I personally don't like in an 'IRAF' like list is the arbitrary string observatory ID. I forsee that it can easily lead to a mess when it'll contain 100s of entries as a mixture of observatories and individual telescopes. However the MPC list may also have it's own problems.

**Comment by bmorris3** [comment]
@mhvk – can you access the USNO list? When I try to do a search I get a server error, so it's unclear to me if that list is really being maintained online.

@bsipocz – Do you think the astropy list should have hundreds of observatories? I think support for the ~50 largest ones should cover >80% of astronomers' needs.

**Comment by bsipocz** [comment]
You're most probably right with the 50 sites, but if you have individual entries per telescopes (as in the current list), then it can be way much bigger (and that's the point where it gets messy I think).

**Comment by mhvk** [comment]
@bmorris3 - I get a server error as well, and another one on the contact page. I've send an e-mail to Eric Barron, who appears to be the maintainer.

More generally, for precision work (say, pulsar timing), one does need coordinates per telescope, not per site.

**Comment by bmorris3** [comment]
@eteq Would you have any interest in humoring @adrn's opinions and reformatting the database as we did in [astroplan](https://github.com/astropy/astroplan/blob/master/astroplan/data/observatories.json)?

**Comment by eteq** [comment]
@bmorris3 - yep, did that in a commit I just pushed up to #4042 .  The beauty is that then we can put exactly the file from astropy/astroplan#105 up on the astropy-data server and have it all work consistently (and then @adrn can even use that server to get the json!)
