### ISSUE TITLE
Warn or Raise Exception when combining Columns with different units

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#3821]
While making `Column` behave fully like a `Quantity` would have backwards compatibility issues, it seems wise to warn or even raise an exception if something is done that would be inconsistent with the units (such as adding two columns with different units; unclear how far to take this, though; warn also on `np.sin(col)` when `col.unit = 'deg'`?). See #3820 for more comments.

**Comment by embray** [comment]
("Needs-clarification" just because it isn't clear yet what the course of action is--definitely agree somethign should be done here).

**Comment by embray** [comment]
BTW I still think it would be cool to allow `column.view(Quantity)` ;)

**Comment by mhvk** [comment]
> BTW I still think it would be cool to allow `column.view(Quantity)`

But that is already possible!  `Quantity.__array_finalize__` does grap the `col.unit` attribute:
```
In [4]: Column([1., 2., 3.], unit='m').view(u.Quantity)
Out[4]: <Quantity [ 1., 2., 3.] m>
```

**Comment by embray** [comment]
Ah, good.  So I think people should do that when they want quantity-like behavior.  Examples in the docs would help but it's standard Numpyish behavior I think.

**Comment by nstarman** [comment]
@mhvk is this still relevant?

**Comment by mhvk** [comment]
Yes, still relevant, though perhaps as we move more and more to `QTable`, it matters less. I guess it is just the extent to which one tries to help people avoid shooting themselves in the foot (like the `np.sin(angle)` example listed above, with `angle` a `Column` with `unit='deg'` -- which will get interpreted as `radian` nevertheless).

And of course since nothing has been done about this without the world coming to an end, we could also chose to close the issue!

**Comment by nstarman** [comment]
> And of course since nothing has been done about this without the world coming to an end,

Agreed that it's lower priority.

Alternative to closing, would it be possible to make a mixin for things that are Quantity-like (like Column) to have an ``__array_ufunc__`` and ``__array_function__`` that just does ``<object> -> Quantity -> numpy function ->  Quantity -> <object>``. Kind of like [ShapedLikeNDArray](https://docs.astropy.org/en/latest/api/astropy.utils.shapes.ShapedLikeNDArray.html#astropy.utils.shapes.ShapedLikeNDArray) but for numpy overrides.
