### ISSUE TITLE
Update astropy.io.fits to use astropy.units

### ISSUE THREAD

**Issue by embray** [astropy/astropy#383]
What exactly this means is a bit unclear as of yet.  For data, eventually we will be switching over to using NDData and Table objects, which will have built-in support for units.  For headers it should be possible to parse out units from comments, where supported, and make them available somehow through the Header interface.

**Comment by mhvk** [comment]
Cleared the milestone. Would be good to have an explicit list of what this entails so we can cross off things as they get implemented.

**Comment by pllim** [comment]
Only @embray can make that list. So if he doesn't make it, say, by v3.0, let's just close this. There is already kinda a workaround using unified I/O.

**Comment by cdeil** [comment]
I don't know if this is the right issue to mention this, but in Gammapy we have these converter functions that copy unit (and ucd) info from `astropy.io.fits.BinTable` to `astropy.table.Table` and the other way around:
* http://docs.gammapy.org/en/latest/_modules/gammapy/utils/fits.html#table_to_fits_table
* http://docs.gammapy.org/en/latest/api/gammapy.utils.fits.fits_table_to_table.html#gammapy.utils.fits.fits_table_to_table

If Astropy core grew that functionality of better interfacing between Table / BinTable (e.g. concerning units), it would be great!

**Comment by saimn** [comment]
These functions are quite similar to [table_to_hdu](http://docs.astropy.org/en/latest/io/fits/api/tables.html#astropy.io.fits.table_to_hdu) and [read_table_fits](https://github.com/astropy/astropy/blob/master/astropy/io/fits/connect.py#L79), which handles units, but not column description and ucd.

**Comment by pllim** [comment]
So theoretically, we just need someone to mash those two into existing FITS/Table unified I/O functions. Who wants to volunteer as a Tribute?

**Comment by mhvk** [comment]
I think we still want to be able to access headers that have units as quantities, so I'll remove the `close?` label, even though I realize that I myself at least will not get around to this any time soon.

**Comment by mhvk** [comment]
Removing the milestone, since no-one had time for 3.0, and it is not clear when this will happen. It remains useful, though!

**Comment by mhvk** [comment]
I've kept this open for a while, but think the issue is in a way both too generic (exactly what should support units) and too specific (we should perhaps integrate fits better generally, so that there is not both `BinTable` and a `Table` class). So, closing this.
