### ISSUE TITLE
Seamless quantity support in IPython

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3834]
IPython's API makes it _somewhat_ easy to support custom syntax for input (in all IPython frontends) via a custom [`InputTransformer`](http://ipython.readthedocs.org/en/latest/config/inputtransforms.html).

This could be used to allow custom syntax where units can be appended seamlessly to numeric literals in Python expressions.  For example

```
>>> 10 m / 9 s
<Quantity 1.1111111111111112 m s>
```

This of course, is not valid Python code.  But it does fit into the Python language unambiguously--that is, a numeric literal followed immediately (with or without whitespace) with a token of one or more alphabetic characters (possibly including parens for supporting log units, etc.) does not conflict with anything existing in the Python language grammar.  (Especially in Python 3, which does away with long literals).

On the backend this converts a literal like `10m` to `Quantity(10, 'm')` so when saving the IPython history to a Python file it will write valid Python code.

I was able to implement a simple prototype of this pretty easily, but it only worked with simple expressions like the one above.  For it to work seamlessly one would have to modify the Python grammar and use this modified grammar to parse inputs.  The added complexity is probably the biggest downside to this.  Another problem is that it's not clear if or how compound units should be supported (I think if they were supported, compound unit expressions would have to go inside parens following the number, otherwise there would be too many ambiguities).

The other downside is that demonstrates syntax that is not valid Python, which could be confusing to Python newcomers.  I don't think that's _too_ much of a problem though; this is a problem that already exists with IPython, when features like shell commands and magics are demonstrated.  Whenever I teach SWC there's usually at least one user who hasn't been using IPython (even though I told them to) and gets confused when a magic doesn't work.  At the same time, people don't seem to have too much trouble accepting that IPython extends the normal Python syntax, once it's explained to them (and documented).

Relatedly, this idea was inspired by an interesting recent discussion on Python-ideas about adding support for custom literals in Python: https://mail.python.org/pipermail/python-ideas/2015-June/033871.html

If that feature were ever implemented it could probably also be used to support quantity literals. But I doubt it will go anywhere.

**Comment by adrn** [comment]
Revisiting this after a long while: I feel like this might be too much magic...

**Comment by pllim** [comment]
Too much magic it is.
