### ISSUE TITLE
Clarify WCS examples

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#3840]
In http://astropy.readthedocs.org/en/latest/wcs/index.html

``` python
# Some pixel coordinates of interest.
pixcrd = numpy.array([[0, 0], [24, 38], [45, 98]], numpy.float_)

# Convert pixel coordinates to world coordinates
# The second argument is "origin" -- in this case we're declaring we
# have 1-based (Fortran-like) coordinates.
world = w.wcs_pix2world(pixcrd, 1)
print(world)
```
1. Is pixel coordinate in the pairs of `[X, Y]` or `[Y, X]`?
2. Why is `origin` set to 1 when `pixcrd` is clearly 0-indexed? I would expect `origin=0` in that case.

**Comment by mdboom** [comment]
> Is pixel coordinate in the pairs of [X, Y] or [Y, X]?

It's  [X, Y].  That's definitely worth noting here.

> Why is origin set to 1 when pixcrd is clearly 0-indexed? I would expect origin=0 in that case.

Good point -- in this case [0, 0] is outside of the original image, so is confusing (though not necessarily wrong).  We should probably just update the example to be [1, 1].

**Comment by pllim** [comment]
@nden answered my questions:

1. It is `[X, Y]`

2. `origin` refers to the origin that the transformation expects, not the origin of my `pixcrd` values. If WCS is read in from FITS header, `origin` is always 1. **But** as I am typing this, I saw a reply from @mdboom that confuses me again.

**Comment by mdboom** [comment]
`origin` is the origin of the pixcrd *values*, not the pixcrd array indices.  FITS WCS usually uses [1, 1] as the origin, since it comes from the Fortran tradition.  So if you wanted to transform the pixel in the upper-left corner of a CCD, you would pass [1, 1] (and set origin to 1).  Many FITS WCS examples and conventions work in this way, so we want to support it.  However, in Python/Numpy (and all C-like languages), the index of the upper-left pixel is [0, 0], so it's probably more natural to use that in those languages.  In that case, you would pass [0, 0] and set origin to 0.  In both cases, the result (which is usually in ra, dec degrees) would be the same.

**Comment by pllim** [comment]
@mdboom , so if I have an exposure from a 2048x2048 detector and I want to calculate for two of the corners, I would do either
```python
pixcrd = numpy.array([[0, 0], [2047, 2047]], numpy.float_)
world = w.wcs_pix2world(pixcrd, 0)
```
**OR**
```python
pixcrd = numpy.array([[1, 1], [2048, 2048]], numpy.float_)
world = w.wcs_pix2world(pixcrd, 1)
```
but **NOT**
```python
pixcrd = numpy.array([[0, 0], [2047, 2047]], numpy.float_)
world = w.wcs_pix2world(pixcrd, 1)
```
?

**Comment by mdboom** [comment]
Yes.

**Comment by pllim** [comment]
One more related question then, if I want output pixel values that Python can use, do I do this below?
```python
pixcrd2 = w.wcs_world2pix(world, 0)  # not 1?
dat = fits.getdata('myimage.fits', 1)
my_pixel = dat[pixcrd2[0][1], pixcrd2[0][0]]
```

**Comment by mdboom** [comment]
Yes.

**Comment by pllim** [comment]
Okay. The documentation definitely needs more clarification. I cannot get this information from it alone.

**Comment by kakirastern** [comment]
Hi @pllim, can I work on this issue?

**Comment by pllim** [comment]
@kakirastern , if you wish.

**Comment by kakirastern** [comment]
Thanks @pllim, PR #8375 has been added to follow up on the issue.

**Comment by kakirastern** [comment]
Sorry @pllim, I thought both examples regarding WCS needed to be changed. So I have just opened another PR (#8376) to follow up on the other example. It was really my bad.

**Comment by pllim** [comment]
@kakirastern , I would prefer for all your changes that address this same issue to be in the same pull request. Is that possible? Thanks!

**Comment by pllim** [comment]
I am sorry that I did not provide this link earlier, but here is the development workflow for this project: http://docs.astropy.org/en/latest/development/workflow/development_workflow.html

**Comment by kakirastern** [comment]
@pllim Thanks so much for the development workflow for the project. I appreciate it. Also, I have updated PR #8375 to address both issues discussed in this conversation previously. Please let me now what you think.
