### ISSUE TITLE
What is the difference between RADECSYS and RADESYSa?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#3846]
I am getting this warning:
```
WARNING: FITSFixedWarning: RADECSYS= 'FK5 ' 
RADECSYS is non-standard, use RADESYSa. [astropy.wcs.wcs]
```
Can I fix it by simply changing the header keyword from `RADECSYS` to `RADESYSa` while keeping all the existing keyword values? Or does `RADESYSa` mean a different kind of WCS transformation?

**Comment by astrofrog** [comment]
the issue is that ``RADECSYS`` (with the C) is not standard and it's saying to use ``RADESYS``. I think the ``a`` refers to the fact that multiple WCS frames can be specified in a file using suffixes. So the key here is not the ``a`` but the fact the ``C`` shouldn't be there.

**Comment by pllim** [comment]
Thanks, @astrofrog . Changing `RADECSYS` to `RADESYS` (without the "a") fixed the warning.
