### ISSUE TITLE
Numpy-dev issues for votable

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#3848]
There have been a number of changes to `MaskedArray` in numpy-dev, and it seems those are resulting in lots of failures in `io.votable` (see, e.g., https://travis-ci.org/astropy/astropy/jobs/66426936). Since numpy 1.10 is supposedly imminent, it would be good to try to resolve... (here's to hoping it is not my numpy PR that caused it...).

**Comment by mhvk** [comment]
The problem was introduced by https://github.com/numpy/numpy/pull/4586 (by me, sigh...); see https://github.com/numpy/numpy/pull/5962 for a solution.

**Comment by embray** [comment]
Well at least you had a quick fix :)

**Comment by mhvk** [comment]
Closing, since the upstream fix was merged.
