### ISSUE TITLE
Intersphinx does not link to submodules

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#3859]
I have this in my `conf.py`:

``` python
intersphinx_mapping = {
    'python': ('http://docs.python.org/', None),
    'numpy': ('http://docs.scipy.org/doc/numpy/', None),
    'scipy': ('http://docs.scipy.org/doc/scipy/reference/', None),
    'matplotlib': ('http://matplotlib.org/', None),
    'astropy': ('http://docs.astropy.org/en/stable/', None)
    }
```

But Sphinx does not generate any link when I do this in my docstring; i.e., I see "astropy.io.fits" highlighted in italics rather than have it linked to the appropriate `astropy` API doc:

``` python
def myfunc():
    """Blah blah `astropy.io.fits` blahblah"""
    blahblah = 1.0
    # blah blah blah
```

**Comment by embray** [comment]
Does it work for any other astropy submodules?  I think this may have to do with the fact that most (if any at all) of the modules themselves don't have an autogenerated API doc page.  For the second-level (or third level in the case of `astropy.io.fits` the doc page for the module is the index of the appropriate doc section, like http://docs.astropy.org/en/stable/io/fits/index.html

I feel like there *was* some way someone cooked up to make module references go to the appropriate page in our docs, but I don't know how it works.

**Comment by embray** [comment]
Hmm. Well it looks like it does manage to resolve the reference internally.  However, it's possible that whatever hack is that makes that work does not properly add the module to the objects.inv cache read by sphinx to make intersphinx work.  So that's worth investigating (likely something that needs to happen in astropy-helpers though).

**Comment by pllim** [comment]
Would be nice if this works. But for now, I can just link to the specific FITS function that I use in my function, or something like that. So, this is not urgent nor a show-stopper.

**Comment by pllim** [comment]
FYI - Changing it to the following gives me a working link to http://docs.astropy.org/en/stable/io/fits/api/files.html#astropy.io.fits.getdata
```python
"""Blah blah :func:`astropy.io.fits.getdata` blahblah"""
```

**Comment by embray** [comment]
Right, individual functions and classes that have a specific API doc page should work fine.  It's just submodules that are treated a little differently.

**Comment by bsipocz** [comment]
Looking at the inventory, I think the the submodule links now exists. Closing this, but @pllim, please feel free to reopen if find it otherwise or found that the links doesn't point to the right location.

**Comment by pllim** [comment]
Yes http://pysynphot.readthedocs.io/en/latest/tutorials.html?highlight=astropy.io.fits links to http://docs.astropy.org/en/stable/io/fits/index.html#module-astropy.io.fits (not the top of the page but good enough).
