### ISSUE TITLE
Add option to input/output column units for fixed width tables

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#386]
Extend the `io.ascii.FixedWidth` reader to include a keyword arg that will specify that there is a row of unit specifiers after the column name specifiers (or at the top of the header if there are no column names).  This will apply for both reading and writing fixed width tables.

This allows for outputting a table to a file in a format like `Table.pprint` with `show_units=True`, and then reading back that table with no information loss.

**Comment by taldcroft** [comment]
Rescheduling for 1.1 since there was interest.

**Comment by astrofrog** [comment]
Will finish off #2869 for 1.2.
