### ISSUE TITLE
[skip ci] should skip coverage too, otherwise CI pass information can be incorrect

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#3875]
If the last commit to a PR has `[skip ci]`, appveyor and travis tests are skipped, but it seems coverage still runs. For that case, the coverage result is used to say that a PR is fine to merge, even if the previous PR had faults; see #3224.

**Comment by astrofrog** [comment]
Sounds like an issue that should be opened with coveralls rather than here?

**Comment by astrofrog** [comment]
I'm going to close this - there's nothing we can do on the astropy side about this.
