### ISSUE TITLE
ascii.latex.AASTex: don't include new line characters after last row of data

### ISSUE THREAD

**Issue by jrka** [astropy/astropy#3888]
Very minor issue: writing a table in AASTex (deluxetable) format includes new line characters at the end of each line, including the last one. This results in a blank line at the end of each table. The last row of a table before "\enddata" should not include the "\\\" characters.

Example:

    from astropy.io import ascii
    from astropy.table import Table
    import sys    
    t = Table([[1,2],[1.234e9,2.34e-12]], names = ('a','b'))
    ascii.write(t,sys.stdout,Writer=ascii.latex.AASTex)

Result: 

    \begin{deluxetable}{cc}
     \tablehead{\colhead{a} & \colhead{b}}
    \startdata
    1 & 1234000000.0 \\
    2 & 2.34e-12 \\
    \enddata
    \end{deluxetable}

Which looks like:
![image](https://cloud.githubusercontent.com/assets/4870555/8362092/c5c2f72a-1b2b-11e5-98e5-d53a2110d9a0.png)

But if you got rid of the "\\\" after 2.34e-12, you'd get:
![image](https://cloud.githubusercontent.com/assets/4870555/8362105/e005836e-1b2b-11e5-9d0d-997302f1d083.png)

**Comment by embray** [comment]
Confirmed, and definitely worth fixing.

**Comment by taldcroft** [comment]
I personally think this is an upstream issue in LaTeX, but I agree we can fix this here.  :smile:

Here is a brutal hack that does the trick.  Can you think of a better way @hamogu ?
```
diff --git a/astropy/io/ascii/latex.py b/astropy/io/ascii/latex.py
index 187cf99..c05e986 100644
--- a/astropy/io/ascii/latex.py
+++ b/astropy/io/ascii/latex.py
@@ -385,6 +385,7 @@ class AASTexData(LatexData):
     def write(self, lines):
         lines.append(self.data_start)
         core.BaseData.write(self, lines)
+        lines[-1] = lines[-1][:-2]  # strip off final '\\' of last data line
         lines.append(self.data_end)
         add_dictval_to_list(self.latex, 'tablefoot', lines)
         lines.append(r'\end{' + self.latex['tabletype'] + r'}')
```

**Comment by taldcroft** [comment]
Oh, does plain LaTeX have the same problem?  The table output has the same final trailing `\\` but I don't know if this is a problem for plain tables.

**Comment by hamogu** [comment]
@taldcroft : I think that's fine. This is a very specialized reader/writer where we can do these "ad-hoc" solutions.
Do you want to convert this into a PR? I would ask you to add a comment to the code above the line that you added that explains what it does. It's not immediately obvious for future maintainers.

Also, I just checked regular LaTeX. That does *not* have this problem; it seems to be specific to ApJ's deluxetable package.

**Comment by taldcroft** [comment]
@jrka - do you want to take a crack at this?  In any case I'm leaving this open as low-hanging fruit for the upcoming astropy sprint at scipy 2015.

**Comment by jrka** [comment]
@taldcroft , since scipy is just next week I'll keep it on the back burner for now. But if no one gets to it, I will do so!

**Comment by shwetamore1295** [comment]
If this issue isn't fixed, can I work on this issue?

**Comment by taldcroft** [comment]
@shwetamore1295 - go for it!

**Comment by anchitjain1234** [comment]
Please check #4561.
