### ISSUE TITLE
Add sample plots to docstrings from built-in models

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3894]
Inspired by https://github.com/astropy/astropy/pull/3889/files#r33375391, I think it would be nice if *most* of the built-in models (in particular the functional and powerlaw models) had similar sample plots in their docstrings.  Some of them could include multiple subplots demonstrating the influence of different parameters to the model.

**Comment by algerdnazgul** [comment]
Close?

**Comment by pllim** [comment]
Yes, looks like it.
