### ISSUE TITLE
Error when setting element from Numpy array to quantity

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3914]
The following example fails:

``` python
In [1]: import numpy as np

In [2]: from astropy import units as u

In [3]: x = np.ones((2,2))

In [4]: x[0,0] = 4 * u.K
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-1edabbf385e2> in <module>()
----> 1 x[0,0] = 4 * u.K

ValueError: setting an array element with a sequence.
```

@mhvk @mdboom - is this a Numpy bug?

I'm using Astropy 1.0.3 and Numpy 1.9.2

**Comment by mhvk** [comment]
In principle, this behaviour is, I think, correct: you can only set an array to a dimensionless quantity, i.e.,
```
x[0, 0] = 1.*u.percent
x
# array([[ 0.01,  1.  ],
#        [ 1.  ,  1.  ]])
```
Though I'm a bit surprised about the exception that you get...

Actually, I think the reason for that is that `numpy` behaves slightly differently if you set an individual element from when you set a slice. Sadly,
```
x[0, :] = 4 * u.K
```
works fine (and there is nothing we can do about it, as far as I know). Maybe for an individual element it tries to go through `float` or so, which we do catch.

Anyway, I think any fixes would have to be in numpy...

**Comment by Cadair** [comment]
I get this "setting element of array with sequence" thing quite a lot, especially when going in and out of other libraries with quantities (mpl for example). Is it not because a scalar quantity is actually an array?

**Comment by embray** [comment]
I agree, you shouldn't be able to assign a quantity as an element of a dimensionless array.  I don't know that there's much we could do about that except to be clear about "don't do that".  One could probably come up with other ways to subtly break ndarray item assignment by assigning RHS objects that Numpy doesn't really know what to do with.

**Comment by keflavich** [comment]
Related question: I think this should work:
```
In [1]: x = (1*u.K, 2*u.K)

In [2]: np.array(x)
Traceback (most recent call last):
  File "<ipython-input-2-152940d1f14f>", line 1, in <module>
    np.array(x)
ValueError: setting an array element with a sequence.
```
where the expected return would be
```
In [3]: (1,2)*u.K
Out[3]: <Quantity [ 1., 2.] K>
```

Is it possible to support that behavior?

**Comment by mhvk** [comment]
@keflavich - not sure that I agree that `np.array((1*u.K, 2*u.K))` should work, certainly not without `subok=True` -- you're really asking `np.array` to do something fairly complicated. I also don't see how we could affect that; as far as I know, there are no hooks one can use to change behaviour depending on the subclass of something inside tuples or lists.

p.s. `u.Quantity((1*u.K, 2*u.K))` does work as expected.

**Comment by keflavich** [comment]
Well, fair enough, it may be difficult or impossible to work around, but I encounter this error fairly often and it makes working with quantities rather tedious.  I've been trying to promote the use of arrays that inherit from `Quantity`s (e.g., in spectral-cube.rtfd.org), but it's a harder sell with these sorts of errors.  I don't think it's unreasonable to expect `np.array((1*u.K, 2*u.K))` to work from a users' perspective, even though it may be difficult or impossible to implement.

**Comment by adrn** [comment]
I'm not sure what this issue is about -- my impression is that the title / original description of this issue is the desired behavior? Could you reopen and clarify or make a new one if you think there is still an issue? @astrofrog
