### ISSUE TITLE
Error with latest wcslib 

### ISSUE THREAD

**Issue by nden** [astropy/astropy#3926]
I see now errors like:

```
 w = wcs.WCS(f[1].header, f)
WARNING: FITSFixedWarning: 'celfix' made the change 'Invalid parameter value'. [       astropy.wcs.wcs]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-7e5ac287bddf> in <module>()
----> 1 w1 = wcs.WCS(f[1].header, f)

.../site-packages/astropy/wcs/wcs.pyc        in __init__(self, header, fobj, key, minerr, relax, naxis, keysel, colsel, fix,        translate_units, _do_set)
    473
    474         if _do_set:
--> 475             self.wcs.set()
    476
    477         for fd in close_fds:

ValueError: ERROR 5 in wcsset() at line 2201 of file cextern/wcslib/C/wcs.c:
Invalid parameter value.
ERROR 4 in linset() at line 657 of file cextern/wcslib/C/lin.c:
Failed to initialize distortion functions.
ERROR 3 in disset() at line 884 of file cextern/wcslib/C/dis.c:
Unrecognized/unimplemented distortion function: Lookup  .
```

@mdboom

I simplified the failing example. Isn't there a test like this?

**Comment by mdboom** [comment]
Hmmm...  I thought I already whacked that mole.  (By making wcslib ignore unknown distortion types).

Can you link me to the offending file?  I can't seem to reproduce with the HST FITS file I have from before...

**Comment by mdboom** [comment]
> Can you link me to the offending file? I can't seem to reproduce with the HST FITS file I have from before...

Actually, I think I have the same file that you're having trouble with, and the following works:

```
In [1]: from astropy.io import fits
In [2]: f = fits.open('j94f05bgq_flt.fits')
In [3]: from astropy import wcs
In [4]: w = wcs.WCS(f[1].header, f)
```

**Comment by nden** [comment]
Yes, it's the same file. I just reinstalled master and it still fails for me. Hmm ...

**Comment by embray** [comment]
I have the same file too, and it seems to work:
```python
In [1]: from astropy.io import fits

In [2]: f = fits.open('j94f05bgq_flt.fits')

In [3]: from astropy import wcs

In [4]: wcs.WCS(f[1].header, f)
Out[4]: 
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN-SIP'  'DEC--TAN-SIP'  
CRVAL : 5.6305681061800001  -72.054571842789997  
CRPIX : 2048.0  1024.0  
CD1_1 CD1_2  : 1.2905625633399721e-05  5.9530912341980287e-06  
CD2_1 CD2_2  : 5.0220581265601002e-06  -1.2644774148201699e-05  
NAXIS    : 4096 2048
```

@nden , did you try `git clean -dfx` and/or uninstalling your old version first?

**Comment by embray** [comment]
It works for me using the branch in #3927 as well.

**Comment by mdboom** [comment]
So, I guess we need to get to the bottom of why it's failing for @nden and not @mdboom and @embray.  Any other things about your environment or previous steps not outlined here?  What platform?

**Comment by nden** [comment]
I just did `git clean -dfx` and installed #3927 in a new virtualenv. I still get the error. I am doing this (remotely) on my Linux desktop, I'm guessing it's the same as yours - RHEL 6.6. I did the virtualenv based on SSBDEV. incidentally SSBDEV is broken in the same way. Is there anything I'm missing?

**Comment by mdboom** [comment]
Ok -- I'm now able to reproduce.  Strange I couldn't before.  Maybe it's somehow intermittent?  Anyway, now that I'm able to reproduce, I can hopefully work on a solution.

**Comment by nden** [comment]
I made up a file with all possible distortions with a size of ~ 100K. If this is not too large for the repository  you can use it as a test for this fix. Let me know and I'll make it available ...

**Comment by mdboom** [comment]
Thanks -- I just created #3931 before seeing your comment.  I took the HST WCS file you referenced and set all the data to zero and gzip compressed it to reduce its size and it got down to 181k.  It sounds like your file would be even better, particularly if it exercises all of the distortion types.  If you point me to it and let me know which headers I should parse to test, I can add that to my pull request (or you can just make a pull request against mine, whichever is easier for you).

**Comment by embray** [comment]
I still can't reproduce..  Why would it be at all intermittent?  What about this code is at all non-deterministic?  Are there any steps to reproduce this other than open the FITS file and read in the WCS?

**Comment by mdboom** [comment]
I have no idea why it would be intermittent -- I just lack any other explanation.  Once I started reproducing it, it's been consistently reproducable.

**Comment by nden** [comment]
@mdboom Just sent an email with the location of the file.

Seems like the only explanation (short of magic) would be that something does not get cleaned in the source code unless you really try to clean it as much as possible. Do you regularly run `git clean ...`? Our nightly builds start with a fresh download of the source code so the problem showed up the day after the PR was merged.
