### ISSUE TITLE
Docs only builds

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3933]
Sometimes it's nice to have Travis build the docs for us, to check for warnings and such.  However, for docs-only changes there's absolutely no reason to re-run the full test suite.  For trivial changes we sometimes ask people to use `[skip ci]` (which I'm still in favor of regardless), but there are still non-trivial doc changes that nonetheless could only possible affect the docs build.

I think a two-pronged approach to this is needed:

1) Check that the _only_ files changed are `.rst` files, or files under `doc/` in general (including things like the Sphinx config).  If so skip all but the docs build.
2) Have a Docs-only label that can be added to PRs that can be checked in the Travis scripts, and cancel non-doc builds if that label is present.  That will allow maintainers who can be sure that something is only a doc build (for example, changes in some docstrings) to control this behavior manually.  Often this won't help for PR contributions that nobody adds the label to before the builds run, but for many cases (including the core maintainers submitting their own PRs) this will save some hassle.

**Comment by mwcraig** [comment]
It would be helpful to skip these builds on appveyor too; I can look into how to do that next week.

**Comment by embray** [comment]
Both of these techniques can work with little more than a PR# and the repository name--we would write a script that implements both of these that the CI rules would run before running any other tests.  Should work fine on AppVeyor.

**Comment by bsipocz** [comment]
Closing this as this needs a machinery in ``ci-helpers``. I've already seen e.g. ``[skip travis]`` done elsewhere, so we can have a ``[docs only]`` or similar that skips everything expect the docs building. Needless to say this won't be a solution for given docs being doctested.
