### ISSUE TITLE
Look at new caching functionality on travis

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#3945]
The new build containers on travis [allow caching](http://docs.travis-ci.com/user/migrating-from-legacy/#How-Do-I-Cache-Dependencies-and-Directories%3F). We should see whether this would speed up builds once #3944 is merged.

**Comment by bsipocz** [comment]
This issue is moved upstream into ``ci-helpers``:
https://github.com/astropy/ci-helpers/issues/207
