### ISSUE TITLE
doctest-skip directive isn't working in docstrings

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#3948]
Is there a way to enable the directive to work in the docstrings, too? 

It works fine in the docs `rst` files, but apparently not in the docstrings as I get this fail with `ccdproc`:
https://travis-ci.org/astropy/ccdproc/jobs/70630227

**Comment by embray** [comment]
I feel like this has come up before, and that there is some specific reason it doesn't work, but I can't remember the details now, so it might be worth investigating.  In part it might have to do with the fact that docstrings aren't necessarily tied to Sphinx.

You can, however, use `__doctest_skip__` in the module: http://docs.astropy.org/en/stable/development/testguide.html?highlight=__doctest_skip__#skipping-doctests

**Comment by bsipocz** [comment]
Yes, I saw examples for ``__doctest_skip__`` in the core. However I couldn't use it, as I wanted to skip only the plotting example parts of a class, and there were other example codes before that. 

Anyway, it's just a few lines, so using ``# doctest: +SKIP`` does the job, it's just not as nice.

**Comment by embray** [comment]
Hmm....now I'm thinking of how I could expand `__doctest_skip__` to call out individual tests or ranges of tests within a docstring.  Might be worth looking into if I can't get the Sphinx directives working.

**Comment by bsipocz** [comment]
The directive still doesn't seem to work in docstrings, but this is now an issue for `pytest-doctestplus`. Could you @astrofrog or @eteq please move the issue to that repo?

**Comment by pllim** [comment]
Manually moved to astropy/pytest-doctestplus#52
