### ISSUE TITLE
Releasing the global interpreter lock (GIL)

### ISSUE THREAD

**Issue by rabernat** [astropy/astropy#3949]
I frequently use astropy's convolution of scipy.ndimage because of its treatment of missing values. I have recently been experimenting with [Dask](http://dask.pydata.org/en/latest/index.html), an awesome new parallel task scheduler for working with numpy arrays. You can achieve huge speedups with dask by mapping operations to chunks of arrays using multiple threads, but only if the mapped function releases the global interpreter lock at the cython level (as do numpy's ufuncs and many other scipy routines).

Astropy functions (at least the convolution functions I looked at), can't benefit from the dask speedup because they don't release the GIL. As a result, with dask they are ~60 times slower than scipy.ndimage in my benchmarks.
http://nbviewer.ipython.org/gist/rabernat/3e2c3645d4666674cf2b

It seems like this would be an easy fix, and I am considering trying it myself. But I thought I would raise the issue here first in case the developers are aware of some reasons why this is not possible with astropy.

My impression is that dask is going to be the next big thing in the scipy ecosystem, so this might be a worthwhile thing to work on.

**Comment by rabernat** [comment]
This was actually easy to implement. My branch (pull request above) now runs ~50 times faster in the example above.

**Comment by embray** [comment]
Fixed by  #3950, thanks again @rabernat
