### ISSUE TITLE
Manipulate multidimensional columns

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astropy#3952]
I have some tables with multidimensional columns. With the expert assistance of one of my 
graduate students I have managed to read the data.

ydata=table['MODEL_MAG'][:,2]

I had tried  ydata=table['MODEL_MAG'][2] which did not work as I expected.

Are their other syntaxes that would work or recommended.

A n-diminensional example would be useful in my opinion.
http://astropy.readthedocs.org/en/latest/table/access_table.html#quick-overview

**Comment by embray** [comment]
`table['MODEL_MAG'][:,2]` would select the third "row" (where by "row" I mean the first axis) of every element in the column.  `table['MODEL_MAG'][2]` would select the third element in the column, in its entirety.  Could you please clarify what it was you expected?

A single column in a table is a Numpy array.  So columns containing N-dimensional elements are Numpy arrays of N+1 dimensions, where the first axis is the table rows themselves, and the remaining axes are the dimensions of the N-d elements.  This is similar to the convention used for, say, image cubes, where the first axis represents each slice, and the second two axes are the rows and columns of each slice.  These are the standard indexing rules for Numpy-like N-d arrays: http://docs.scipy.org/doc/numpy/user/basics.indexing.html

**Comment by richardgmcmahon** [comment]
Hmm, maybe my FITs file has the column with multi-columns rotated by 90 degrees. i.e. columns and rows transposed. I have seen this  before with FITs files created by MWRFITs in IDL. I will look into this more. It might be a few weeks before I get time to dig into this since my immediate problem was to to read the data. I will close this for now.
