### ISSUE TITLE
Allow a BinTableHDU (or, in principle, a TableHDU) to be created from an Astropy Table

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3959]
There is a method called `BinTableHDU.from_columns` that can create a new `BinTableHDU` object from an existing record array or `FITS_rec` object, or a few other types that represent collections of columns.  It's actually called `.from_columns` because really it creates a table from a `fits.ColDefs` object, though if you don't pass in a `ColDefs` it will instantiate a `ColDefs` from the object you do pass in (if possible).  So at the lower level we need a `ColDefs._init_from_table` method or something like that which convert an Astropy table to a `fits.ColDefs` object.  Most of the logic for that probably already exists in the I/O registry connector code.

Incidentally, `BinTableHDU.from_columns` is mostly unnecessary too, since it now works more or less the same to do `BinTableHDU(data=columns)` (the `.from_columns` interface still serves a purpose though, since it allows use cases like adding extra rows, and copying only the column spec but not the data, etc.)  So all these interfaces should work with `Table`.

This won't completely solve full support for Astropy Table in `io.fits`, since that will require getting rid of the `FITS_rec` data structure completely, whereas this would just copy a `Table` into a `FITS_rec`.  But it's a useful step nonetheless, and will help transition.

**Comment by saimn** [comment]
There is now the convenience function `table_to_hdu` (added in #4778), which is not exactly the same thing as what was expected here. Having to use a specific function makes it difficult to discover, so I think it would be useful to be able to instantiate directly from a Table (`BinTableHDU(table)`, which was also suggested by @astrofrog in #4778). Other thoughts about this ?
It should be easy to do, hence I'm updating the labels.

**Comment by pllim** [comment]
> It should be easy to do

Did you volunteer, @saimn ? 😂

**Comment by saimn** [comment]
@pllim - ok ;), I will have a look !
