### ISSUE TITLE
Give Table a _repr_latex_ method?

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#3972]
Having a `_repr_latex_` method on the `Table` object would be really useful for me when using PythonTeX. 

Are there any reasons why this has not / should not be done?

**Comment by embray** [comment]
I guess the only question here (and the problem I have with all `_repr_..._` methods, is what the default formatting options should be.  If we add this we might also want a way to control, via an instance attribute, what the default LaTeX formatting options are for a table (if it doesn't already exist).

**Comment by taldcroft** [comment]
It's not a totally robust or future-proof idea, but the `latexdict` args (http://astropy.readthedocs.org/en/latest/api/astropy.io.ascii.Latex.html#astropy.io.ascii.Latex) that control how a table is formatted into latex could be just stored in the table via `meta['latexdict']`, and `_repr_latex_` would know to look for that to supply defaults.

**Comment by embray** [comment]
Seems good enough to me for starters.

**Comment by taldcroft** [comment]
OK @Cadair you are clear to code!  :smile:

**Comment by taldcroft** [comment]
(And find a way to feel like you are writing your thesis without actually writing it.)

**Comment by Suyog7130** [comment]
Hey, @aaryapatil  and @hamogu, has this issue been worked on before?
There are many open issues marked _Package-novice_ etc. but have had a Pull Request or two.

**Comment by hamogu** [comment]
@Suyog7130 As long as an issue is open, you can work on it. Often, someone tried their hand (e.g. for GSOC applications!) but it did not work out. You can go to the linked pull requests and see what worked, what did not and why it was not finished. However, in this particular case, I don't think anyone has worked on exactly this issue.
