### ISSUE TITLE
problem in building new version of astropy

### ISSUE THREAD

**Issue by neuronphysics** [astropy/astropy#3973]
I tried to build new version of astopy locally in my machine where I don't have root permission and I got following warning and errors

```
building 'astropy._erfa._core' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/anaconda/lib/python2.7/site-packages/numpy/core/include -Icextern/erfa -I/anaconda/include/python2.7 -c astropy/_erfa/core.c -o build/temp.linux-x86_64-2.7/astropy/_erfa/core.o
gcc: error: astropy/_erfa/core.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 4
```

any suggestion to fix the problem would be appreciated !

**Comment by embray** [comment]
How did you obtain the source code and what commands did you use to start the build?
`astropy/_erfa/core.c` is a file that is normally generated during the build process.  The Jinja2 package is required to generate that file, but if you don't have Jinja2 installed there should have been an exception message about that early on.

**Comment by hamogu** [comment]
@neuronphysics Is this still an issue or can we close this?

**Comment by embray** [comment]
Probable environment error.
