### ISSUE TITLE
We should use sphinx.ext.napoleon rather than our shipped numpydoc

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#3974]
As of sphinx 1.3, sphinx includes the napoleon extension for parsing numpy-style docstrings.

Unfortunately, it seems to have migrated from our shipped numpydoc in a number of ways and there is a lot of breakage when switching to it.  However, long term we should be using the standard and maintained version of this extension.

**Comment by embray** [comment]
:+1: I did not know about this.

**Comment by mdboom** [comment]
I didn't know about it either until I tried to build the IPython documentation today -- it's already a hard dependency for them.

From the few things I've tried, it just seems that Napoleon is stricter about the syntax -- haven't found anything truly incompatible yet.

**Comment by embray** [comment]
Could make for a decent sprint / novice project.

**Comment by Cadair** [comment]
I tried to do a simple swap of the two and got a lot of errors. I doubt any of them are very hard to resolve, but it's probably a large mountain to chew through.

**Comment by pllim** [comment]
Weird. I did the same switch in my own package and it was pretty painless.

**Comment by pllim** [comment]
This is really astropy/sphinx-astropy#5 now
