### ISSUE TITLE
Assertion messages when using Quantity or Angle objects and assert_allclose

### ISSUE THREAD

**Issue by mapazarr** [astropy/astropy#3978]
In case of assertion errors on arrays of quantity objects, such as `~astropy.units.Quantity` or `~astropy.coordinates.Angle`, `numpy.testing.assert_allclose` will not show the values, but give a `[repr failed]` message. The assertion method works fine though; it's just the printing of error messages in case the assertion fails, which seems not to be working properly.

For debugging one can use the `.value` methods of these object types. Is this maybe a bug?

Example code:
```python
from numpy.testing import assert_allclose
from astropy.coordinates import Angle
from astropy.units import Quantity

a2 = Angle([0., 0.], 'degree')
b2 = Angle([1., 1.], 'degree')
assert_allclose(a2, b2) # problem
q2 = Quantity([0., 0.], 'm')
r2 = Quantity([1., 1.], 'm')
assert_allclose(q2, r2) # problem
```

output of code using `ipython` for the cases of more than 1 element stored in the asserted objects (i.e. the ones marked as `problem` above):

```
(...)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: [repr failed]
 y: [repr failed]
(...)
```

**Comment by mdboom** [comment]
I can't seem to reproduce.  With your example, I get:

```
(mismatch 100.0%)
 x: Angle(<Angle 0.0 deg>)
 y: Angle(<Angle 1.0 deg>)
```

What version of astropy are you using?

**Comment by mapazarr** [comment]
Ok, I updated the example. The 1-component arrays show the values right, when assert fails (but then the script stops). I now removed them. You should get the problem if you run it now.

I'm using both `1.1.dev12994` and `1.0.3`.

**Comment by mdboom** [comment]
Thanks.  I'm reproducing it now...  Now onto a solution...

**Comment by mhvk** [comment]
Before we monkey-patch this: `assert_allclose` does actually not do unit conversion, so I am not sure it is worth patching it. Instead, one should compare the underlying arrays using `.value`, or, better, use `astropy.tests.helper.assert_quantity_allclose` (which, yes, needs better documentation).  Ideally, of course, one sends a patch up to `numpy` to make `assert_allclose` subclass aware, and once that is in put it in `utils.compat.numpy` for those with older versions of numpy.

```
assert_allclose(b2, b2.to(u.arcmin))
...
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: <Angle [ 1., 1.] deg>
 y: <Angle [ 60., 60.] arcmin>
```

Aside: note from the above that I do not reproduce the initial problem. This is with astropy 1.0.3 and numpy 1.8.2. In numpy-dev, I do have a problem, so something must have changed between. It would seem a bug report to numpy is due...

**Comment by mdboom** [comment]
That makes sense.  I had completely forgotten about `astropy.tests.helper.assert_quantity_allclose` -- that's the better solution.

**Comment by mapazarr** [comment]
OK, I see. Thanks. For the records, I'm using numpy version `1.9.2`.

I'm working with @cdeil in the `~gammapy` associated package. There is also a class to assert on quantities there: `~gammapy.utils.testing.assert_quantity`. I'm not sure if it's worth keeping it?

When looking at the astropy docs here
 http://astropy.readthedocs.org/en/latest/testhelpers.html
I only see a solution for `~Quantity` objects. It would be nice to have an equivalent solution for other objects like `~Angle`, `~Time` `~TimeDelta`.

**Comment by mhvk** [comment]
@mapazarr - `Angle` is a subclass of `Quantity`, so one can use `assert_quantity_allclose` on it. We indeed do not have something similar for `Time` (or `SkyCoord`). It would indeed be nice to have a general astropy version of `allclose` that understands the different astropy classes well enough to do the right comparison.

**Comment by mhvk** [comment]
@mapazarr - I looked at our documentation again and it reminded me that `np.isclose` actually does work -- as long as one gives an explicit `atol`; see http://docs.astropy.org/en/latest/known_issues.html#quantities-float-comparison-with-np-isclose-fails

Still, it would be good to explicitly mention that one should replace `assert_allclose` with `assert_quantity_allclose` -- if you have time for a quick PR, that would be most welcome...

**Comment by cdeil** [comment]
A utility `assert_skycoord_allclose` function would be great to have.
@eteq – I think we discussed this at some point in the past. Does it exist?
@mapazarr – If no, maybe this is your chance at a first PR to Astropy core? :smile: 
(PS: the real work is going through and simplifying all the existing Astropy coordinates tests to use this function, but that could be left for a future second PR.)

**Comment by mhvk** [comment]
It might be no more than `assert np.all(object1.separation(object2) < tolerance)` -- though some care should be taken for 3-D coordinates.

**Comment by astrofrog** [comment]
@mhvk @cdeil - can this issue be closed though, since the original issue reported here is moot?

**Comment by mhvk** [comment]
Yes, I think it can be closed and will do so now. Of course, fine to raise a separate issue on having the option of an `assert_allclose` for `SkyCoord` and `Time`.
