### ISSUE TITLE
Make it easy to re-use astropy.utils.data functionality for other servers

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3985]
As part of a discussion with STScI folk, it became apparent that it would be useful to be able to reuse the functions like `get_pkg_data_filename` in other packages but with a different server. However, currently only one base URL can be used, the one set by the configuration item `dataurl`. Changing that configuration item would not be wise since it needs to be what it is for astropy and affiliated packages.

@embray @mdboom - any ideas? Could we consider having a context manager, or something like this?

**Comment by pllim** [comment]
You can just *temporarily* change `dataurl` using a context manager, right?

**Comment by astrofrog** [comment]
Can you already do that? I couldn't find it in the docs.

**Comment by pllim** [comment]
```python
from astropy.utils import data
with data.conf.set_temp('dataurl', 'ftp://ftp.stsci.edu/crds/blah/blah'):
    data.get_pkg_data_filename(...)
```

**Comment by pllim** [comment]
I use it with `remote_timeout` in Cone Search. See http://astropy.readthedocs.org/en/latest/vo/conesearch/client.html#id2

**Comment by astrofrog** [comment]
Oh, I didn't realize this - maybe we should add an example like this to the config docs?

**Comment by pllim** [comment]
:+1: to adding example. I might have gotten the usage from Mike via private communications.

**Comment by embray** [comment]
I believe there already are examples like this.  I agree that for special cases just changing the value in the config should be fine, but for individual cases temporarily setting the config value is fine too.

**Comment by embray** [comment]
This is mentioned in the testing documentation: http://docs.astropy.org/en/stable/development/testguide.html?highlight=set_temp#testing-configuration-parameters

I suppose it's fair to point out that it's not just for testing.

**Comment by pllim** [comment]
*STScI folks* have not spoken for 4 years now, so I am just closing this one...
