### ISSUE TITLE
get_sun returns vector solution for single time

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy#3998]
@eteq : Is this intended behavior? Shouldn't `get_sun` return a scalar sky coordinate for a scalar time?

```python
>>> time = Time.now()
>>> time.isscalar
True
>>> sun = get_sun(time)
>>> sun.isscalar
False
>>> sun[0]
<SkyCoord (GCRS: obstime=2015-07-22 22:39:14.781846, obsgeoloc=[ 0.  0.  0.] m, obsgeovel=[ 0.  0.  0.] m / s):39:14.781846, obsgeoloc=[ 0.  0.  0.] m, obsgeovel=[ 0.  0.  0.] m / s): (ra, dec, distance) in (deg, deg, AU)
    (122.76730836, 20.02852949, 1.01598715)>
```

**Comment by eteq** [comment]
Hmm, this is definitely not intended, and appears to be a regression in v1.0.3 (i.e., it's correct in v1.0-v1.0.2).

Cant help but think it might be related to #3920 somehow...

**Comment by eteq** [comment]
I bet it's somehow caused by #3750, which was between v1.0.2 and 1.0.3 and touched the relevant functionality - will investigate.
