### ISSUE TITLE
Embed hyperlinks in io.ascii.write html output? 

### ISSUE THREAD

**Issue by tumlinson** [astropy/astropy#4006]
I need to write out the contents of an astropy table to html, using: 

```
ascii.write(sample, 'sample.html', format='html')
```

some cells of the table need to contain hyperlinks, which I can construct via string: 
```
                        urlstring = '<a href="file:///linkpath"> linktext </a>'              
```
the problem is that when the string is written out into HTML, the `<` and `>` characters are converted to `&lt;` and `&gt;`:

``` 
    <td>&lt;a href="file:///linkpath"&gt; linktext &lt;/a&gt;</td>
```
      
How can I have those characters printed into the HTML literally, or otherwise embed links in the html outputs of tables? 

Apologies if this is a noob question, but that's what I am.

**Comment by embray** [comment]
Hmm--looks like the HTML writer always escapes the raw strings for HTML related characters.  However I could see this as an argument for a "raw" mode to just write strings from a table without escaping.  If so, I think this should be enabled on a per-column basis.  

This would require an update to the [`XMLWriter`](https://github.com/astropy/astropy/blob/master/astropy/utils/xml/writer.py#L43) class to allow data to be written to an element without HTML entity escapes.  It would also require an update to the `astropy.io.ascii.html.HTML` class to accept an optional sequence of columns in which to allow raw HTML, and an update to [`HTML.write`](https://github.com/astropy/astropy/blob/master/astropy/io/ascii/html.py#L313) to support that.

I think also as a security concern, insecure tags like `<script>` or `<iframe>` should be disabled even in raw HTML mode, unless explicitly whitelisted (this is why I bumped this up to effort-medium).

**Comment by pllim** [comment]
Meanwhile, `sed` can be used to manually fix the `<a href=...>` and `</a>` tags. http://www.gnu.org/software/sed/manual/sed.html#The-_0022s_0022-Command

**Comment by mrobberto** [comment]
the functionality is present in pandas "to_html" writer. A pandas table "pd" containing html links can be printed to html setting "escape=False"
pd.to_html('fileout.html',escape=False)
Unfortunately, pandas writes vanilla html without sorting headers etc., so it would still be nice to get this added to astropy

**Comment by pllim** [comment]
c/c @taldcroft ?

**Comment by taldcroft** [comment]
Definitely :+1: on the idea.  I've wanted this myself a few times, so a PR would definitely be welcome.

**Comment by taldcroft** [comment]
See #4423 for code.

**Comment by algerdnazgul** [comment]
Close?

**Comment by pllim** [comment]
Yes, thanks.
