### ISSUE TITLE
mpl_style doesn't seem to be displaying in the documentation.

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#4009]
http://docs.astropy.org/en/stable/visualization/index.html#module-astropy.visualization.mpl_style

and because of this, I had forgotten all about it.

**Comment by embray** [comment]
It looks like the docstrings are there, but there's been some problems in the recent past with our automodapi plugin picking up class-level attribute docstrings, and the same likely applies to module-level variables.  astropy/astropy-helpers#116 discusses this some.

Regardless the existence and use of the Astropy matplotlib style deserves to be called out beyond just the API docs, or else it will be hard to find anyway.

**Comment by larrybradley** [comment]
The docs were moved in https://github.com/astropy/astropy/pull/5662.
