### ISSUE TITLE
Constructing table from rows doesn't preserve column names

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4010]
I have a use case where I need to construct a new table from existing row objects (and where I can't use e.g. ``t[1,3,4,5,6]``), but column names are not preserved:

```python
In [1]: from astropy.table import Table

In [2]: t = Table()

In [3]: t['a'] = [1,2,3]

In [4]: t['b'] = ['i','j','k']

In [5]: t2 = Table(rows=[t[0],t[1]])

In [6]: t2
Out[6]: 
<Table masked=False length=2>
 col0  col1
int64 str32
----- -----
    1     i
    2     j
```

Of course, an easy workaround is to do ``t2 = Table(rows=[t[0],t[1]], names=t.dtype.names)`` but maybe we could make this work out of the box?

**Comment by pllim** [comment]
If you want it to work "out of the  box", you also need to consider
```python
t0 = Table()
t0['a'] = [1, 2, 3]
t0['b'] = ['i', 'j', 'k']
t1 = Table()
t1['a'] = [4, 5, 6]
t1['b'] = ['l', 'm', 'n']
t2 = Table(rows=[t0[0], t1[0]])
```

**Comment by taldcroft** [comment]
I agree with @pllim in that I'm not usually too keen on making assumptions like "the first row (instead of the second, or third or last row) should be the one defining column names".

I'm assuming that the original example was a highly simplified version of reality, since for that example the following is preferred and does preserve column names:
```
t2 = t[[0, 1]]
```

**Comment by embray** [comment]
I wouldn't call this a bug.  As it is it seems like the right behavior.

Though I added the Bug label back after more thinking--is it possible to look up a row's parent table?  If so we could allow this if both rows came from the same table, but raise an exception if they didn't (or at the very least if the rows' dtypes don't match).

If we did allow it in the case of same table (or identical dtypes) I'd still warn that this should be done with an index mask instead....

**Comment by astrofrog** [comment]
I only marked this as a bug because I didn't realize it was by design originally :)

I should say that I came across this as a result of the way I wrote my code - of course, once I realized the column names weren't preserved, I refactored the code to use the index mask, but I opened an issue anyway since I think other users may stumble across this and not understand.

Is there a way to efficiently check whether all the rows reference the same column?

**Comment by taldcroft** [comment]
If the rows are from the same table then making a list of `Row` objects to create a new `Table` is generally a bad idea since indexing is so much efficient and idiomatic.  Even if there is a good reason to use a list of Rows it is better to be explicit and include the `names` kwarg.   After all it is pretty darned easy already:
```
Table(rows=[row0, row1, row2], names=row0.colnames)  # or table.colnames
```

**Comment by pllim** [comment]
I agree with @taldcroft here. Guessing the right column names to inherit can open a can of worms.

**Comment by astrofrog** [comment]
@taldcroft - ok, feel free to close!

**Comment by embray** [comment]
>  If so we could allow this if both rows came from the same table, but raise an exception if they didn't (or at the very least if the rows' dtypes don't match).

Any thoughts on this?

**Comment by hamogu** [comment]
Agreed with @taldcroft : Just don't use rows. I never liked the `Row` object in the first place. @embray would work, but the energy is probably better invested int telling users that lists of rows are a bad idea in the first place (for performance).

**Comment by taldcroft** [comment]
OK, I'm closing this now, but as always feel free to re-open if desired.

@hamogu - I wouldn't go that far, there are really good use cases for `Row`, and I can even imagine how @astrofrog might have ended up with a list of rows using idiomatic code, e.g.
```
def is_cool(star):
    return star['temperature'] < 3000 * u.K   # or whatever

stars = QTable.read('nice_stars.fits')
cool_stars = Table(rows=[star for star in stars if is_cool(star)])  # Needs names=stars.colnames
```
Without a `Row` object you wouldn't be able to write something like above.  And row objects are really light now, but not necessarily *fast* for element access.  The implementation below is much faster (like a factor of 1000!) for the table creation part:
```
cool_stars = stars[[star.index for star in stars if is_cool(star)]]
```
