### ISSUE TITLE
Add warning when data is lost when assigning to Table column

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4011]
In the following example, it would be nice to have a warning that warns of data loss:

```python
In [7]: t = Table()

In [8]: t['a'] = ['i','j','k']

In [9]: t['a'] = ['ii','jj','kk']

In [10]: t
Out[10]: 
<Table masked=False length=3>
  a  
str32
-----
    i
    j
    k
```

The workaround is to remove and add the column again, so this could be mentioned in the warning?

**Comment by taldcroft** [comment]
I think this would be technically possible but would adversely impact performance.  In the situation you showed the code would need to pre-convert the right side to a numpy array and compare types.  This wastes memory and time, but more importantly it would set a precedent that the following should also warn:
```
t['a'][5] = 'iii'
```
So now you need to get into `Column.__setitem__` and start injecting Python logic to pre-convert the value to numpy, check the type.

The upshot is that `numpy` has this nice "feature" when assigning strings.  I think we need to choose between performance and protecting the user from something they run into anyway with pure `numpy`.  All in all I'd go with performance here.

**Comment by mhvk** [comment]
Agreed with @taldcroft for `Column` -- but it suggests we may want to have a new column type for strings. Since I think pure python lists are often substantially faster for strings anyway, maybe it could  just be a wrapper for `list`? (can't use `list` directly, since we cannot stick `info` on it)

**Comment by hamogu** [comment]
:+1:  for @taldcroft here. We do it the way numpy does. (But I would like @mhvk 's suggestion, if it works without breaking other stuff. )

**Comment by taldcroft** [comment]
@mhvk - in what way do you mean `list` is faster than numpy arrays for strings?  Do you mean for things like insertion?  Anyway, you can use numpy Object dtype right now for that case (variable length strings as pure Python objects), no?
```
>>> Table([['a', 'abc']], names=['a'], dtype=['O'])
<Table masked=False length=2>
  a   
object
------
     a
   abc
```

**Comment by mhvk** [comment]
@taldcroft - this is just a vague memory, but I remember reading that python/lists are quite well optimized for strings, while numpy is definitely unwieldy with anything string-like.  You're right, though, that numpy object arrays would work too (but probably are slower; on holidays right now, so feeling too lazy too test).

**Comment by taldcroft** [comment]
@mhvk - Just fooling around a little with numpy strings vs Python strings, it seems there is about a 60 ns overhead when using a numpy string with built-ins like `'x' in string` or reg-ex searching.  That can actually be of order 50% of the total time, so I can see at least one way in which numpy strings are slower.

We could certainly make a generic `List`-based mixin, but we'd want some concrete motivation to choose this over a `Column` of objects.

**Comment by taldcroft** [comment]
@astrofrog - as for the original idea of issuing a warning, I don't think that is going to happen.  As always feel free to re-open if you disagree.
