### ISSUE TITLE
Optional parameters in Polynomial models should be indicated as such

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4018]
In the polynomial models, all parameters other than 'degree' are optional and should be indicated as such:

http://docs.astropy.org/en/stable/_modules/astropy/modeling/polynomial.html#Polynomial2D

for example ``x_domain`` should be:

```
x_domain : list or None, optional
```

**Comment by embray** [comment]
Incidentally I'm just in the middle of slightly updating some aspects of the polynomial models (hopefully making them easier to subclass, etc.)  I can try to touch this while I'm at it.

**Comment by embray** [comment]
If no one else gets to it, that is.
