### ISSUE TITLE
Parameter names missing from Polynomial model documentation

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4019]
In the following documentation:

http://docs.astropy.org/en/stable/api/astropy.modeling.polynomial.Polynomial2D.html#astropy.modeling.polynomial.Polynomial2D

There is no mention of what the parameters are called. The answer is `c0_0`, `c0_1` etc. but this should probably be mentioned in the docs.

**Comment by embray** [comment]
Related to what I said in #4018 this will be directly addressed by the updates I'm making.  Funny this came up at the same time I was doing this--complete coincidence.

**Comment by algerdnazgul** [comment]
Task mentioned below is closed. Maybe this needs to be closed too?

**Comment by embray** [comment]
This would be solved by #4018 but that hasn't been merged yet (and may need some reworking anyways...)

**Comment by bsipocz** [comment]
I think this was solved with #4108, please feel free to reopen if you think more action is required.
