### ISSUE TITLE
Implement updated IAU B3 2015 constants if approved 

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4026]
One of the IAU resolutions that may be passed next week is the following:

http://astronomy2015.org/sites/default/files/RESOLUTION%20B3%20-%20nominal%20conversion%20constants.pdf

It defines official values for things like solar radii, etc. so we should update to use these once approved.

**Comment by souravsingh** [comment]
I would like to work on this issue.How do I start?

**Comment by mhvk** [comment]
@souravsingh - the relevant files are `astropy/constants/si.py` and `astropy/units/astrophys.py`. Be sure to including in the constant docstring that these are *nominal* values (hence no uncertainty). I think you may want to add polar radii (to the constants, maybe not the units), though am not sure what name to give...

If you're up to it, I'd also suggest to expand the table in the documentation to include the uncertainty, so it is clear at a glance whether values are measured or nominal. This table is generated in `astropy/constants/__init__.py`.

**Comment by embray** [comment]
Could this lead to differences in numerical results?  We might want to be careful about making such a change, even if it's ultimately for the better.

**Comment by souravsingh** [comment]
In ``astropy/units/astrophys.py`` I found there are no unit for solar effective temperature Assigned within the file.So how do I go on to assigning the unit for it?

**Comment by royalharsh** [comment]
https://github.com/astropy/astropy/pull/4397

**Comment by mhvk** [comment]
Changing the milestone to "Future" since this is not going to happen for 1.3.

**Comment by bsipocz** [comment]
Closing as #6083 added iau2015 constants.
