### ISSUE TITLE
Skip merging metadata for table operations

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#4038]
I wonder if there is a way to skip merging metadata when doing operations with tables. 
E.g. my use case is to deal with the metadata manually when `hstack`ing several tables of the same format/meta sequentially.

If it's indeed not possible at the moment,  would there be any objection to introduce a `meta_skip=False` argument?

cc: @taldcroft

**Comment by taldcroft** [comment]
@bsipocz - are you worried about performance of needlessly doing the merge?  If not you can simply set the final `meta` as you like.
```
t = hstack(tables, metadata_conflicts='silent')
t.meta = my_meta_generator(tables)
```

This does make me notice that the `merge_func` kwarg of `metadata.merge` is being ignored in the high-level table operations:
https://github.com/astropy/astropy/blob/4f75c15d01a818c3db73c546a07127d6c9a6de6d/astropy/utils/metadata.py#L60

So one might add a `metadata_merge_func` argument that let's you specify how metadata gets merged.  Then you could call `hstack` like `hstack(tables, metadata_merge_func=metadata.take_left)`, which will simply give you back the meta for the first table.  In theory you could put in your own merge function that does what you want.

The fact that `merge_func` is invisible in the user API is partly from an unrealized dream of having a fancy class based system for doing custom merging.  That may never happen, but being able to specify how you want to do things directly in the `hstack` (etc) call would be a good thing and pretty simple to do.

**Comment by bsipocz** [comment]
Nope, it's not performance in that sense. 
I'm collecting a few columns from large tables into a new table, but I have to do it incrementally with hstack to avoid reading all of them in the same time and freeze my laptop.  

The column names and the metadata keys are the same for all the tables (the metadata basically only a log of the modeling parameters that were used to generate the results stored in the tables). So I need to keep both left and right metas, and don't mind handling them manually (e.g. using the indices (``table_names``) as new meta keys to keep track which set of columns they belong to, etc), but in this case need to avoid of hstack adding the first one automatically. Right now my workaround is to delete the superfluous keys.

Anyway I like the flexibility ``metadata_merge_func`` offers and will open a PR to put that in.

**Comment by taldcroft** [comment]
And your original `meta_skip` could be done with `metadata_merge_func=None`!

**Comment by embray** [comment]
> The fact that merge_func is invisible in the user API is partly from an unrealized dream of having a fancy class based system for doing custom merging.

How fancy does it need to be really?  All it needs is a class with `__call__` and some means of keeping a registry of merge strategies (so they can be provided as strings).  Heck doesn't even need to be a class--any function with the correct arguments could be added to a registry of merge strategies.

**Comment by embray** [comment]
Or are you talking about something completely different?  Rereading the context I'm not sure now...

**Comment by taldcroft** [comment]
To be honest the details of how the fancy system might be useful are pretty hazy now.  Unless it comes flashing back then we can take this need-driven approach which seems fine to me.

**Comment by bsipocz** [comment]
I literally can't remember this use case and what and why found it problematic, and clearly it was not a thing anyone else was asking for. So I just go ahead and close this issue now.
