### ISSUE TITLE
FITS issue with NED spectrum

### ISSUE THREAD

**Issue by doccosmos** [astropy/astropy#4046]
Attempting to open this spectrum (http://ned.ipac.caltech.edu/spc1/1992/1992ApJS...80..109B/PG_1048-090:S:B_V:bg1992.fits.gz) from NED and look at the header with fits in astropy.io throws a VerifyError:

> from astropy.io import fits
> spec = fits.open("http://ned.ipac.caltech.edu/spc1/1992/1992ApJS...80..109B/PG_1048-090:S:B_V:bg1992.fits.gz")
> spec
[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x101ed1c50>]
>spec.header
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mjg/anaconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 266, in __repr__
    return self.tostring(sep='\n', endcard=False, padding=False)
  File "/Users/mjg/anaconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 639, in tostring
    s = str(card)
  File "/Users/mjg/anaconda/lib/python2.7/site-packages/astropy/io/fits/card.py", line 461, in __str__
    return self.image
  File "/Users/mjg/anaconda/lib/python2.7/site-packages/astropy/io/fits/card.py", line 765, in image
    self.verify('fix')
  File "/Users/mjg/anaconda/lib/python2.7/site-packages/astropy/io/fits/verify.py", line 120, in verify
    raise VerifyError('\n' + '\n'.join(messages))
astropy.io.fits.verify.VerifyError:
Verification reported errors:
Unfixable error: Illegal keyword name 'IRAF-B/P'
Note: PyFITS uses zero-based indexing.

**Comment by mdboom** [comment]
The `/` is an invalid character in a FITS keyword (which must only have digits, uppercase letters A-Z and `-` or `_`).  `astropy.io.fits` has actually read the header just fine despite this, but it tries really hard to write out something that's invalid.

You can correct the keyword by assigning it to something that is valid:

```
spec.header['IRAF-B-P'] = spec.header['IRAF-B/P']
del spec.header['IRAF-B/P']
```

I will also contact the NED maintainers and make them aware of this as it really should be fixed upstream.

**Comment by embray** [comment]
By the way a few things about this:

1) The FITS module *can* read files that contain invalid keywords, in most cases.  But there's a known issue (#887, and I think others) that sometimes the first time you display a header containing invalid keywords you'll get an exception like the one above.  But if you try it again the header *will* display.

2) By default you won't be able to write out a file containing invalid keywords, but it will let you do it anyways if you use the `output_verify='ignore'` option (this can be passed in at several places, but most typically in the `writeto` method or in `close()`.
