### ISSUE TITLE
Affiliated package developer docs

### ISSUE THREAD

**Issue by dkirkby** [astropy/astropy#4054]
Here are a few minor issues I noticed when following the "Managing the template files via git" section in `docs/development/affiliated-packages.rst`:
- Steps 2-4 use the new package name for the code subdirectory (if you use the nice substitution feature) but this isn't set until step 6.
- The file `scripts/script_example` (and the `scripts/` directory) referred to in step 4 are not present in the template package.
- The `git remote add template git@github.com:astropy/package-template.git` instruction in step 12 seems redundant with the `git remote rename origin template` instruction in step 11.

Perhaps the following `CHANGES.rst` should be included in package-template:

```
0.1 (unreleased)
----------------

- No changes yet
```

Finally, should the existing tags of `package-template` be deleted so they don't conflict with release tags of a new affiliated package?

```
% git tag -l
v0.4
v0.4.1
v1.0
```

**Comment by dkirkby** [comment]
One more suggestion -- the following instruction from step 11 uses a deprecated git option:
```
% git branch master --set-upstream upstream/master
The --set-upstream flag is deprecated and will be removed. Consider using --track or --set-upstream-to
Branch master set up to track remote branch master from upstream.
```
The following should work for git >= 1.8:
```
git branch master --set-upstream-to upstream/master
```

**Comment by embray** [comment]
Regarding the missing example script, I talked a bit over in [this comment](https://github.com/astropy/package-template/issues/134#issuecomment-128104233) about the need for documenting some best practices for wrapping library code in command-line scripts.

It would be nice to include a small sample script that demonstrates common features like logging, config file handling, argument parsing, etc. and that demonstrates best practices for using those features.

**Comment by dkirkby** [comment]
I finally got around to the "Releasing an affiliated package" instructions and noticed one more potential issue: step 12 says to `git push --tags origin master` but, based on the earlier instructions, I think this should be `git push --tags upstream master`.

This template is a great resource, by the way!  It really simplifies the task of following best practices for a python project.

**Comment by embray** [comment]
I'd have to double-check the instructions, but I think they're assuming that you've made a separate clone of the project just for the purpose of making a release (as opposed to making a release from your fork, and hence using "upstream" instead of "origin").

That said, I never do this myself and just use "upstream".  In any case, the remote can be named anything you want so perhaps it should clarify that the `git push` should be to whatever remote links to your project's main repo on GitHub or wherever it's hosted (where "origin" would be a common example, or often "upstream" as well).

**Comment by pllim** [comment]
`docs/development/affiliated-packages.rst` no longer exists.
