### ISSUE TITLE
ValueError: join requires masking column

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astropy#4059]
Hi, I am doing a 'outer' join on two FITs files that have been read in as tables and get the error below.

ValueError: join requires masking column 'MODEL_MAG' but column type MaskedColumn does not support masking.

This column has FITS format: 4E so maybe this is an edge case.

An 'inner' join works fine.

regards, richard

**Comment by taldcroft** [comment]
@richardgmcmahon - that's a bug!  This is fixed in #4060.

**Comment by richardgmcmahon** [comment]
thanks

**Comment by taldcroft** [comment]
@richardgmcmahon - we normally leave the bug report issue open until the fix gets reviewed and merged.

**Comment by taldcroft** [comment]
Closed by #4060.
