### ISSUE TITLE
outer joins and finding the 'missing' data

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astropy#4061]
This is mainly a comment and solution check. I executed an left outer join using astropy.table.join and then found it quite a challenge to identify the rows with the missing data. It might be worth docmenting a solution. I spent some time reading about masked data in astropy and numpy.

I suggest the missing data example in join covers locating these rows since this is needed for
large tables.

This is what I did, following guidance in: 

https://astropy.readthedocs.org/en/v1.0.3/table/masking.html
https://astropy.readthedocs.org/en/v1.0.3/table/operations.html#join
```
#add a fill_value
table_lrg_join['TILENAME'].fill_value = 'NullTest'

#test for the filled value
itest= table_lrg_join['TILENAME'].filled() == 'NullTest'

#print results
print(table_lrg_join[itest])
```

**Comment by taldcroft** [comment]
You should simply access the `mask` attribute, which is `True` for any element that is missing.
```
missing = table_lrg_join['TITLENAME'].mask
```
You have a good point that the docs don't explicitly have an example of examining the `mask`.  That would be helpful in both the sections you mentioned.

**Comment by hamogu** [comment]
Since #4062 is merged, should this be closed?
