### ISSUE TITLE
Slicing table rows broken

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4068]
Ex:

``` python
In [7]: t = Table([[1, 2], [3, 4], [5, 6], [7, 8]])

In [8]: t
Out[8]: 
<Table length=2>
 col0  col1  col2  col3
int64 int64 int64 int64
----- ----- ----- -----
    1     3     5     7
    2     4     6     8

In [9]: r0 = t[0]

In [10]: r0
Out[10]: 
<Row 0 of table
 values=(1, 3, 5, 7)
 dtype=[('col0', '<i8'), ('col1', '<i8'), ('col2', '<i8'), ('col3', '<i8')]>

In [11]: r0[2:]
Out[11]: 
<Column name='col2' dtype='int64' length=2>
5
6
```

expected:

```
<Row 0 of table
 values=(5, 7)
 dtype=[('col2', '<i8'), ('col3', '<i8')]>
```

I haven't worked it out fully yet, but it looks like the logic is just slightly faulty.  Same problem occurs for other types of slices.

**Comment by embray** [comment]
Seems to affect release too.

**Comment by taldcroft** [comment]
The problem is that slicing a `TableColumns` object gives back another `TableColumns`, while this line is expected either a `Column`-ish object or a `Table`.
https://github.com/astropy/astropy/blob/7b753b7a81d5af597a4b544e982a158f799da10f/astropy/table/row.py#L47

So if `item` is a slice or a tuple you need something like:
```
self._table.__class__(self._table.columns[item])[self._index]
```

**Comment by embray** [comment]
Oof. I wonder if we can do this somehow without actually creating a new Table object to do it.

**Comment by taldcroft** [comment]
Here's what I just wrote for the patched `__getitem__`:
```python
    def __getitem__(self, item):
        from .table import TableColumns
        value = self._table.columns[item]  # Single column or TableColumns object depending on item

        if isinstance(value, TableColumns):
            # If value is a TableColumns object (e.g. if `item` is a slice)
            # then we make a new lightweight table using those columns
            # and return the corresponding Row.
            table = self._table.__class__()
            table.columns = value
            out = table[self._index]
        else:
            # Otherwise `value` is a column and this returns a scalar value.
            out = value[self._index]

        return out
```
It's not really possible to avoid making a new Table object because the Row object uses a ref to the parent Table in order to be light and fast.  I.e. it provides lazy access to column elements in that row.

**Comment by embray** [comment]
Perhaps instead this could do something like the `FITS_record` class does, whereby row objects have an additional attribute on them representing a mask or slice of columns to take values from.

**Comment by embray** [comment]
I have an idea for that--I'll try it out real quick and report back.

**Comment by saimn** [comment]
I noticed this bug today. @taldcroft , your patch above seems better than nothing, it would be great to have it.
