### ISSUE TITLE
astropy.coordinates.search_around_sky breaks on storekdtree=False

### ISSUE THREAD

**Issue by jeanconn** [astropy/astropy#4082]
astropy.coordinates.search_around_sky doesn't seem to respect a boolean for storekdtree.  This looks inconsistent with the docs.  This following code example works fine if I don't include the storekdtree option and accept the default.

```
cat = SkyCoord([10.076,10.00455], [18.54746, 18.54896], unit='deg')
search_around_sky(cat[0:1], cat, seplimit=astropy.units.arcsec * 60, storekdtree=False)

in search_around_sky(coords1, coords2, seplimit, storekdtree)
    333     kdt1 = _get_cartesian_kdtree(ucoords1, storekdtree)
    334 
--> 335     if hasattr(coords2, storekdtree):
    336         #just use the stored KD-Tree
    337         kdt2 = getattr(coords2, storekdtree)

TypeError: hasattr(): attribute name must be string

```

**Comment by embray** [comment]
Yeah, that looks like a bug.  Thanks for the report.

While we're at it, I wonder if we could rename `storekdtree` to `store_kdtree` or even `store_kd_tree`.  The former isn't a great name for legibility.  I kept reading it as "stored tree".

**Comment by eteq** [comment]
Thanks for this, @jeanconn - #4212 should fix this to allow the usage just as you want here.
