### ISSUE TITLE
Coulomb <-> Statcoulomb equivalency

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#4086]
Is there one?  If not, and I didn't find one in a cursory search, I think we should have one.

**Comment by embray** [comment]
Indeed--I think last time we tried to tackle EM units in CGS the equivalency system didn't even exist yet.  I guess there would have to be a set of equivalencies like `statcoulomb_charge`, `statcoulomb_flux`, etc. (or just one `coulomb_statcoulomb` that takes the context as an argument).

It might be good to somehow incorporate the [cgs constants](https://github.com/astropy/astropy/blob/a7ec04d220e972e0cd43bd9571e8d3a36049c4eb/astropy/constants/cgs.py) into this--i.e. to make sure that `e_esu` is correctly converted to `e` under this equivalency.

**Comment by mhvk** [comment]
closing in favour of #4359
