### ISSUE TITLE
scipy.special.erf function can't be evaluated on Quantities

### ISSUE THREAD

**Issue by aphearin** [astropy/astropy#4092]
Dimensionless quantities raise a "TypeError: Unknown ufunc" exception when the scipy erf function is evaluated on them, prompting the user to raise an Issue on github. 

cc @taldcroft , @eteq

**Comment by embray** [comment]
The Quantity class can't know how to treat units in an arbitrary ufunc, and so has to have that function registered with a function that knows how to handle the units of the input.

We should probably add built-in support for any known ufuncs that are defined in SciPy where applicable.  But given that anyone can in principle implement their own ufuncs, we should also better document how to add to this registry manually (I couldn't find any obvious indication in the docs as to how to do this).

Following the [example for `exp`](https://github.com/astropy/astropy/blob/master/astropy/units/quantity_helper.py#L109), for now you can add support for `erf` like:

```python
>>> from astropy import units as u
>>> from astropy.units.quantity_helper import UFUNC_HELPERS, helper_dimensionless_to_dimensionless
>>> UFUNC_HELPERS[scipy.special.erf] = helper_dimensionless_to_dimensionless
>>> q = u.Quantity(1.0, u.one)
>>> q
<Quantity 1.0>
>>> scipy.special.erf(q)
<Quantity 0.8427007929497148>
```

**Comment by aphearin** [comment]
Thanks, @embray, this is perfectly clear. I just added a rather trivial branch to address this in the docs. Let me know what you think. 

aphearin@SHA ref: f9bdc43d80a8d52b21428edd53a5dd4db25c8319

**Comment by mhvk** [comment]
I didn't even know those functions went through `__array_prepare__`, etc.! I'd be quite happy to add those functions to `quantity_helpers`; we'd only have to make sure that we import scipy within a try/except, since `astropy` should work also without it.

**Comment by embray** [comment]
Right--there could be a big ol' block of helpers for scipy functions (it turns out scipy has defined several of its functions as ufuncs).

**Comment by bsipocz** [comment]
scipy.special.erf is compatible now, as well as a few other functions from scipy.special, thanks to https://github.com/astropy/astropy/pull/6852

**Comment by NathanMuniz18** [comment]
hello guys, can i help on this?

**Comment by neutrinoceros** [comment]
@NathanMuniz18 this issue was solved already. Furthermore, we do not usually assign people to issues. If you want to contribute, you are very welcome to work on any open issue that doesn't already have a linked pull request ! Thanks for offering help, we appreciate it.

**Comment by NathanMuniz18** [comment]
It's my first time contributing in open source, are there any issues that you recommend?

**Comment by neutrinoceros** [comment]
Have a look at https://www.astropy.org/contribute.html to see how we triage issues most suited for the external help. Thanks !

**Comment by NathanMuniz18** [comment]
thanks
