### ISSUE TITLE
SSL certificate related remote test failure in ``get_pkg_data_fileobj`` docstring

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#4106]
```
==================================================== FAILURES =====================================================
________________________________ [doctest] astropy.utils.data.get_pkg_data_fileobj ________________________________
449         ...     fcontents = fobj.read()
450         ...
451 
452     This next example would download a data file from the astropy data server
453     because the ``allsky/allsky_rosat.fits`` file is not present in the
454     source distribution.  It will also save the file locally so the
455     next time it is accessed it won't need to be downloaded.::
456 
457         >>> from astropy.utils.data import get_pkg_data_fileobj
458         >>> with get_pkg_data_fileobj('allsky/allsky_rosat.fits',
UNEXPECTED EXCEPTION: URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)
Traceback (most recent call last):

  File "/sw/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest astropy.utils.data.get_pkg_data_fileobj[3]>", line 2, in <module>

  File "/sw/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()

  File "astropy/utils/data.py", line 197, in get_readable_fileobj
    timeout=remote_timeout)

  File "astropy/utils/data.py", line 1095, in download_file
    raise e

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

astropy/utils/data.py:458: UnexpectedException
```

**Comment by embray** [comment]
The certificate on data.astropy.org seems fine, so this is probably a transient local issue.  Either some outdated root certificates, a problem with your ssl lib, or just a temporary connection problem.  This test is working here.

**Comment by bsipocz** [comment]
Thanks for checking this, I'll try to figure out what went wrong in my local system.

**Comment by embray** [comment]
If you can reproduce it should be possible with `urlopen('https://astropy.stsci.edu/data/allsky/allsky_rosat.fits')` since that's all that's going on under the hood.

**Comment by bsipocz** [comment]
Yes, it fails consistently and both on python2 and 3, but only on my laptop (and I've just migrated my old system, so most probably that messed up something). I've tried to reproduce it on another laptop and a linux box but it doesn't fail. 
I'm sorry for the noise.

**Comment by embray** [comment]
No problem, the issue will be searchable (one hopes) if anyone encounters that in the future.

**Comment by bsipocz** [comment]
For the record: the CA bundle file was under a ``ssl/certs/`` subdirectory on my system, but once I symlinked it directly as ``ssl/cert.pem`` the error went away.

 I think it's a very specific fink bug (opened an issue for that), but I just post this workaround here, too as it wasn't trivial to figure out.
