### ISSUE TITLE
fitsdiff doesn't properly report values with different type by same str()

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4122]
I've seen variations of this come up a few times before.  The problem is that [`report_diff_values`](https://github.com/astropy/astropy/blob/master/astropy/io/fits/diff.py#L1214) converts numeric values to strings before displaying the diff.  So if you have one card that contains the string value `'1.0'`, and one with the float `1.0`, although the cards will be reported as different the report doesn't show a useful diff since both values look the same as strings.

A simple workaround would be to have `report_diff_values` also explicitly report type differences (it should also show the value and/or the diffs of the values, but make explicit when there's a type difference).

**Comment by mwcraig** [comment]
@embray -- looks like this was closed by #4162?

**Comment by embray** [comment]
Yes
