### ISSUE TITLE
NDDataArray instantiation with another instance fails when uncertainty is set

### ISSUE THREAD

**Issue by jehturner** [astropy/astropy#4129]
--> from astropy.nddata import NDDataArray, StdDevUncertainty
    --> n = NDDataArray([1,4,9], uncertainty=StdDevUncertainty([1,2,3]))
    --> o = NDDataArray(n)
    Traceback (innermost last):
    File "<console>", line 1, in <module>
    File "/home/jturner/Ureka/variants/nddata/lib/python2.7/site-packages/astropy-1.1.dev13355-py2.7-linux-x86_64.egg/astropy/nddata/compat.py", line 89, in __init__
    super(NDDataArray, self).__init__(*arg, **kwd)
    File "/home/jturner/Ureka/variants/nddata/lib/python2.7/site-packages/astropy-1.1.dev13355-py2.7-linux-x86_64.egg/astropy/nddata/nddata.py", line 89, in __init__
    self.uncertainty = data.uncertainty
    File "/home/jturner/Ureka/variants/nddata/lib/python2.7/site-packages/astropy-1.1.dev13355-py2.7-linux-x86_64.egg/astropy/nddata/compat.py", line 114, in uncertainty
    if self.unit and value._unit:
    File "/home/jturner/Ureka/variants/nddata/lib/python2.7/site-packages/astropy-1.1.dev13355-py2.7-linux-x86_64.egg/astropy/nddata/compat.py", line 138, in unit
    return self._unit
    AttributeError: 'NDDataArray' object has no attribute '_unit'
    --> 

This happens because L89 of <a href="https://github.com/astropy/astropy/blob/67748f15a39a80d8900b5e1bd4e073df824071af/astropy/nddata/compat.py#L89">compat.py calls `NDData.__init__()`</a>, which <a href="https://github.com/astropy/astropy/blob/67748f15a39a80d8900b5e1bd4e073df824071af/astropy/nddata/nddata.py#L89">calls NDDataArray's uncertainty setter</a>, which <a href="https://github.com/astropy/astropy/blob/67748f15a39a80d8900b5e1bd4e073df824071af/astropy/nddata/compat.py#L114">calls the unit getter</a> when an NDUncertainty is defined, which <a href="https://github.com/astropy/astropy/blob/67748f15a39a80d8900b5e1bd4e073df824071af/astropy/nddata/compat.py#L138">accesses `self._unit`</a>, which isn't set until <a href="https://github.com/astropy/astropy/blob/67748f15a39a80d8900b5e1bd4e073df824071af/astropy/nddata/nddata.py#L93">L93 of nddata.py</a> (just a few lines lower down), nor in <a href="https://github.com/astropy/astropy/blob/67748f15a39a80d8900b5e1bd4e073df824071af/astropy/nddata/compat.py#L87">`NDDataArray.__init__()`</a>.

Also... when instantiating NDDataArray from another instance, the `flags` attribute does not get copied as expected from the input data. The class only <a href="https://github.com/astropy/astropy/blob/67748f15a39a80d8900b5e1bd4e073df824071af/astropy/nddata/compat.py#L101">copies flags if passed directly as a parameter</a> by the user. This attribute should get copied by NDDataArray separately from the `super().__init__()`, since its parent NDData doesn't have flags.

Thanks!

James.

**Comment by jehturner** [comment]
By the way, the check for a `flags` attribute can't be duck-typed, since ndarray uses `flags` for its own purpose. I suppose you could say "if it's a duck but not this duck then copy it" but the odds of receiving an ndarray-like object that's not ndarray seem higher than the odds of receiving an NDDataArray-like object that isn't NDDataArray, so it's probably better just to copy flags `if isinstance(data, self._class_)`, as in NDData itself.

**Comment by embray** [comment]
Fixed by #4130
