### ISSUE TITLE
Instantiating NDData subclass from parent object doesn't copy attributes

### ISSUE THREAD

**Issue by jehturner** [astropy/astropy#4137]
In `NDData.__init__()`</a>, attributes get copied from an existing instance <a href="https://github.com/astropy/astropy/blob/59cbe17ee75a34143bca38d064f561a075ca2099/astropy/nddata/nddata.py#L85">only if it has the same `__class__`</a> as the object being instantiated. Shouldn't this instead do `isinstance(data, NDData)` explicitly? Requiring the same `__class__` prevents instantiating NDDataArray properly from an NDData instance (or a subclass from an NDDataArray etc.), eg.:

    --> a=NDData([1,4,9], uncertainty=StdDevUncertainty([1,2,3]))
    --> print a.uncertainty
    <astropy.nddata.nduncertainty.StdDevUncertainty object at 0x3d8b510>
    --> b=NDDataArray(a)
    --> print b.uncertainty
    None

I'd have thought it would be fair game for NDData's own `__init__` to accept *any* NDData instance and not just whatever sub-class you happen to be creating at the time ;-). Otherwise, it's difficult for sub-classes to delegate their own `__init__` to their parents if they want to be "upwards-compatible" (not sure whether I'm overlooking some other consideration though).

If you agree, this would also imply changing my pull request #4130 to use `NDDataArray` <a href="https://github.com/jehturner/astropy/blob/19f9adb828e14cdee61e6f62077ddd7db7a5639e/astropy/nddata/compat.py#L102">instead of `__class__`</a>. I won't do that before you comment though.

Thanks!

James.

**Comment by mwcraig** [comment]
Hi James, I think you are right, please go ahead and update #4130

**Comment by jehturner** [comment]
OK, I've done that, to address both the issues, and Travis is running on it...

**Comment by embray** [comment]
Fixed by #4130
