### ISSUE TITLE
Voigt1D derivatives

### ISSUE THREAD

**Issue by jrleja** [astropy/astropy#4144]
Hi,

I've been trying to fit Voigt line profiles in Astropy. The LevMarLSQFitter was unable to return reasonable fits to the amplitude or the centroid. I checked into the Voigt1D model source code and noticed that it seems like two of the derivatives are switched in the RETURN call: x0 and amplitude. 

When I switched the first two elements of the returned list in the fit_deriv method of Voigt1D, the returned fit was quite reasonable. I'd suggest changing these around.

Thanks (and thanks for putting so much work into this very useful package!!),
Joel Leja

**Comment by embray** [comment]
Ah, right you are about the derivative.  Thanks for catching that!  (I'm surprised this wasn't caught, considering that this model was implemented since it gave better fits for photoemission lines!)

Is there any chance you could provide some sample data that reproduces the problem?

**Comment by jrleja** [comment]
No problem. The following should reproduce the issue.

import numpy as np
from astropy.modeling import fitting
from astropy.modeling.functional_models import Voigt1D

voi = Voigt1D(amplitude_L=-0.5, x_0=0.0, fwhm_L=5.0, fwhm_G=5.0)
xarr = np.linspace(-5.0,5.0,num=40)
yarr = voi(xarr)

voi_init = Voigt1D(amplitude_L=-1.0, x_0=1.0, fwhm_L=5.0, fwhm_G=5.0)
fitter = fitting.LevMarLSQFitter()
voi_fit = fitter(voi_init, xarr, yarr)
print voi_fit

**Comment by embray** [comment]
@jrleja Excellent, thanks--I was able to confirm this, and that fixing the derivative fixed the fit.
