### ISSUE TITLE
Constant.__repr__ should be updated to say 'uncertainty' not 'error' and 'unit' not 'units'

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4145]
As highlighted in [this StackOverflow question](https://astronomy.stackexchange.com/questions/11769/how-to-get-error-out-of-astropy-constants), it's a bit confusing that the uncertainty on constants is referred to as 'uncertainty' when accessed as an attribute but 'error' in the ``repr`` (similarly 'units' in repr vs 'unit' as attribute). We should update ``__repr__`` to show ``unit=`` and ``uncertainty=``.

**Comment by mhvk** [comment]
closed by #4147
