### ISSUE TITLE
wcs.all_pix2world() fails for axes of length 1

### ISSUE THREAD

**Issue by carlmitchell** [astropy/astropy#4148]
I have a fits image with a 3-dimensional data array and 3-dimensional WCS information, but the third dimension has length 1. I'd like to be able to call wcs.all_pix2world([x,y,np.ones_like(x)],1) for this wcs.

Code to reproduce this:

>>> from astropy.io import fits
>>> from astropy import wcs
>>> hdulist = fits.open('file.fits')
>>> hdulist[0].data.shape
(1, 512, 512)
>>> w = wcs.WCS(hdulist[0].header)
>>> w.all_pix2world([256,256,1],1)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-a4fcbdafe6b6> in <module>()
----> 1 w.all_pix2world([256,256,1],1)

/home/cmitchell/anaconda/lib/python2.7/site-packages/astropy/wcs/wcs.pyc in all_pix2world(self, *args, **kwargs)
   1142     def all_pix2world(self, *args, **kwargs):
   1143         return self._array_converter(
-> 1144             self._all_pix2world, 'output', *args, **kwargs)
   1145     all_pix2world.__doc__ = """
   1146         Transforms pixel coordinates to world coordinates.

/home/cmitchell/anaconda/lib/python2.7/site-packages/astropy/wcs/wcs.pyc in _array_converter(self, func, sky, *args, **kwargs)
   1118             if self.naxis == 1 and len(xy.shape) == 1:
   1119                 return _return_list_of_arrays([xy], origin)
-> 1120             return _return_single_array(xy, origin)
   1121 
   1122         elif len(args) == self.naxis + 1:

/home/cmitchell/anaconda/lib/python2.7/site-packages/astropy/wcs/wcs.pyc in _return_single_array(xy, origin)
   1102             if ra_dec_order and sky == 'input':
   1103                 xy = self._denormalize_sky(xy)
-> 1104             result = func(xy, origin)
   1105             if ra_dec_order and sky == 'output':
   1106                 result = self._normalize_sky(result)

ValueError: object of too small depth for desired array

**Comment by mdboom** [comment]
Try:

```
wcs.all_pix2world(x, y, np.ones_like(x), 1)
```

**Comment by carlmitchell** [comment]
I really could have sworn I had tried that already, but that worked just fine. Thanks!
