### ISSUE TITLE
Plotting Quantity objects with matplotlib

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#4149]
Apparently matplotlib has some support for real units and scaling in plotting: http://matplotlib.org/examples/units/units_scatter.html

Can I use astropy quantities with that?

Note that there was an issue #1881 that had the same title, but aimed to "drop the units" entirely. What I suggest here goes much further.

**Comment by mdboom** [comment]
As of #3981 (and the future 1.1 release), helper functions for this are included in astropy.
