### ISSUE TITLE
Consider adding G*M terms to astropy.constants

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4153]
As pointed out in [this](https://astronomy.stackexchange.com/questions/11769/how-to-get-error-out-of-astropy-constants/11775?noredirect=1#comment16286_11775) comment (which I'm pretty sure is true) it would be good to provide e.g. `G*M_sun` as a constant in additional to just G or M_sun - the reason being that their uncertainties are correlated.

I'm not sure what we would call these constants, but just wanted to raise the idea.

**Comment by mhvk** [comment]
For pulsar timing, one usually defines GM/c^3 (i.e., the solar mass in seconds).

**Comment by mhvk** [comment]
p.s.  `erfam.h` exposes it as a length unit (GM/c^2), which is probably more logical:
```
/* Schwarzschild radius of the Sun (au) */
/* = 2 * 1.32712440041e20 / (2.99792458e8)^2 / 1.49597870700e11 */
#define ERFA_SRS 1.97412574336e-8
```
which we expose as 
```
In [7]: astropy._erfa.SRS
Out[7]: 1.97412574336e-08
```

**Comment by embray** [comment]
:+1:

**Comment by sudk1896** [comment]
@astrofrog g: What do I name this constant ? What about its parameters such as abbreviation and reference parameters. I would work on this.
