### ISSUE TITLE
Overly verbose test result output

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4164]
A minor annoyance I'm finding since the switch to pytest 2.7.3 in #4027 is that during test running the results for each module list the full path to the module, as found it the temporary test directory, rather than a relative path, like:

```
//tmp/astropy-test-k8ciiv35/lib.linux-x86_64-3.4/astropy/_erfa/tests/test_erfa.py .....
//tmp/astropy-test-k8ciiv35/lib.linux-x86_64-3.4/astropy/analytic_functions/tests/test_blackbody.py ....
//tmp/astropy-test-k8ciiv35/lib.linux-x86_64-3.4/astropy/config/tests/test_configs.py .................
//tmp/astropy-test-k8ciiv35/lib.linux-x86_64-3.4/astropy/constants/tests/test_constant.py ........
...
```

as opposed to

```
astropy/_erfa/tests/test_erfa.py .....
astropy/analytic_functions/tests/test_blackbody.py ....
astropy/config/tests/test_configs.py .................
astropy/constants/tests/test_constant.py ........
...
```

The double slash at the beginning is odd too.  It might in some way be related to a new line showing up at the beginning of the test output that wasn't there before:

```
rootdir: /, inifile:
```

**Comment by embray** [comment]
[If this can't be fixed expediently we can change the label to Affects-release and fix it later, but I'm going to take a quick look]

**Comment by embray** [comment]
This doesn't seem to be a problem when I run `astropy.test()` from the interpreter, in the source checkout.  In that case it shows:
```
rootdir: /internal/1/root/src/astropy/astropy, inifile: setup.cfg
```
so for whatever reason I think it's rootdir that doesn't get found correctly when we do the copy into the temp build directory.

**Comment by embray** [comment]
Ah, this explains it: https://pytest.org/latest/customize.html#initialization-determining-rootdir-and-inifile

When we run `./setup.py test` it ends up sending args like:
```python
['/tmp/astropy-test-k8ciiv35/lib.linux-x86_64-3.4/astropy', '/path/to/my/home/src/astropy/astropy/docs', '--doctest-rst']
```
to `pytest.main()`

It should still find `/path/to/my/home/src/astropy/astropy` as the common ancestor directory, but it fails (and ends up finding `/` as the rootdir) due to the use of `/tmp`.  I think we should just make the temp dir relative to the source checkout instead of `/tmp`.

**Comment by embray** [comment]
This is a change that needs to be made in astropy_helpers it seems.

**Comment by mdboom** [comment]
Ah -- good find.  I was so focused on just getting the tests to pass I didn't even notice!

**Comment by mdboom** [comment]
If we make the temp dir relative to the source checkout, won't that clutter the source checkout?  Kind of annoying, and why I'd prefer using `/tmp`.  (Plus, on most modern Linuxes `/tmp` is a ramdisk so it's blazingly fast).  But I can't think of any better solution to the output problem -- we could tell pytest what the rootdir is, but we basically have two roots (one for the code and one for the docs).  We could copy the docs to the tempdir as well and test them from there, I guess...

**Comment by embray** [comment]
It shouldn't clutter the source checkout because the temp dir is deleted at the end of the test run, though it could still be a problem with random crashes, etc.  Though usually that isn't even a problem, since the tests are run in a subprocess.  So as long as the subprocess doesn't take down the parent process as well the temp dir still gets deleted.  I experimented with this a bit and had a hard time getting it to stick around.  So no, clutter not a problem.

The ramdisk issue is a better point though.  That's in part why I left this configurable.  That said, let me dig around a bit more in pytest and see if there's a way to force a particular "rootdir" on it.  I'll also experiment with just copying the docs as well :/

**Comment by mhvk** [comment]
Would a symbolic link to `/tmp/` from the source checkout solve this?

**Comment by mdboom** [comment]
Thanks for allaying my fears about clutter.

**Comment by embray** [comment]
@mhvk It might, but that has a certain "smell" to it that would be better avoided.  Also not cross platform.

**Comment by embray** [comment]
I'm not 100% sure yet, but if you look at some other recent builds, such as the one for #3229, there are coverage report changes all over the map for unrelated reasons.  I suspect it may have something to do with the changes in #4027.  My guess is that the coveragerc file isn't being found correctly.  Need to investigate more though.

**Comment by embray** [comment]
My hope was that if I explicitly set the path of the pytest config file via the `-c` option (i.e. `-c setup.cfg`) then it would just determine the root dir based on that.  But no such luck (though I might propose such a patch).  

In the meantime I'm thinking I may try doing something directly through the pytest config API but I don't know exactly how difficult that would be yet.

**Comment by embray** [comment]
Okay, copying the docs tree into the temporary test location, and a bit of other path shuffling seems to have done the trick for the most part.  I'll have a patch early next week but I'm done for now :)

**Comment by embray** [comment]
Hooray--with this fixed we should probably be able to get builds back on track.  I should be able to release v1.0.5 by next Monday, I hope (I would do it sooner but I'm booked to teach a workshop for the next two days).  Plus these fixes still need to be actually backported to the v1.0.x branch.

**Comment by mhvk** [comment]
Thanks for getting this working again, @embray!

**Comment by embray** [comment]
Looks like this isn't actually fixed yet--I just ran the tests on master and still had this problem.  Looking at the builds for #4178, they still had the problem too actually.  It's possible I somehow didn't incorporate all the changes to astropy-helpers.

**Comment by embray** [comment]
Actually, I see what the problem is.  #4178 incorporates the changes to astropy-helpers from astropy/astropy-helpers#184, where I refactored the test command.  Now the `./setup.py test` command implementation lives in Astropy, and although I updated the backwards-compatibility copy that still lives in astropy-helpers, I didn't update the copy in Astropy itself with the necessary fixes.  So I'll follow up with that.

**Comment by embray** [comment]
Except that's strange...because I haven't merged #4020.  So what I wrote in my last comment can't be the entire story either.

**Comment by embray** [comment]
Okay, I see, I only fixed this for v1.0.x of astropy-helpers, and subsequently only for astropy v1.0.x branch, not against master.  So I'll get this all cleaned up in a few minutes I hope... (aside for however long it takes for the builds to run).

**Comment by embray** [comment]
Fixed for real this time by #4194.

**Comment by embray** [comment]
As @bsipocz points out this is still broken on OSX https://github.com/astropy/astropy/pull/4194#issuecomment-144107101

If you look at the build log for #4194, on Linux everything looks fine, but not on the OSX build: https://travis-ci.org/astropy/astropy/jobs/82570188

I don't know why this would be any different on OSX, but it appears to find different test paths there.

**Comment by embray** [comment]
Turns out the reason we run into problems on OSX is that `tempfile.tempdir` on OSX returns a path, by default, under `/var`.  But on OSX `/var` is usually a symlink to `/private/var`.  However, `tempfile.tempdir` doesn't return the *real* full path with the symlink derferenced.  Later, this gets compared to the full path by py.test, and it fails to find the correct common rootdir for the tests.

This is kinda a bug in py.test too, since when finding the common rootdir for some test paths it should take symlinks into account better.

**Comment by embray** [comment]
(Didn't mean to close.)
