### ISSUE TITLE
Misleading IOError when passing a urlopen object in to fits.open()

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4165]
Per this SO question: http://stackoverflow.com/questions/32643206/how-do-i-open-a-fits-file-from-a-url-in-astropy

As noted in the answers, one can already pass a URL as a string in to `fits.open()` and that will work fine.  A `urlopen` object has never been supported (intentionally) in the first place.  But it could be supported easily so long as the file is opened in readonly (or denywrite) mode.  It just needs to be handled explicitly.  In any case the error message one gets is also misleading:

```
ERROR: IOError: File-like object does not have a 'write' method, required for mode 'ostream'. [astropy.io.fits.file]
```

This happens despite not explicitly requesting 'ostream' mode.

**Comment by SanketDG** [comment]
Do you mean a `Request` object? 

So something like:

```python
>>> import urrlib.request
>>> from astropy.io import fits
>>> obj = urllib.request.Request("http://google.com")
>>> type(obj)
<class 'urllib.request.Request'>
>>> fits.open(obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sanket/astropy/astropy/io/fits/hdu/hdulist.py", line 138, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache, **kwargs)
  File "/home/sanket/astropy/astropy/io/fits/hdu/hdulist.py", line 280, in fromfile
    save_backup=save_backup, cache=cache, **kwargs)
  File "/home/sanket/astropy/astropy/io/fits/hdu/hdulist.py", line 801, in _readfrom
    ffo = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/sanket/astropy/astropy/io/fits/file.py", line 143, in __init__
    self._open_filelike(fileobj, mode, clobber)
  File "/home/sanket/astropy/astropy/io/fits/file.py", line 455, in _open_filelike
    % self.mode)
OSError: File-like object does not have a 'write' method, required for mode 'ostream'.
```

**Comment by embray** [comment]
@SanketDG Probably, though this needs to work on Python 2 as well, so also whatever's returned by `urllib2.urlopen` which I think is something else.  

Really anything with a `read()` method but no `write()` method.

**Comment by lingxz** [comment]
@embray would it be better to explicitly check for the urlopen object in ```fitsopen()```
or in ``` _File()```?

**Comment by embray** [comment]
All the actual I/O details are handled in the `_File` class.  `fitsopen` is purely a UI.

**Comment by AMAN3003** [comment]
@embray is this issue solved if not can i work on this issue

**Comment by embray** [comment]
@AMAN3003 On GitHub, issues / pull requests that are related to each other show up as cross-references when one references the other.  For example, just above your comment you should be able to see two pull requests that reference this issue.  One of this PRs is already merged, and references this issue in passing.  The other, you can see, is already an attempt to work on this issue (which still needs some work, but it's getting there).

Relatedly, we need to do better at setting the "assignee" to an issue that someone is working on.

**Comment by drdavella** [comment]
It appears that this actually already works as expected, at least for the latest version of `astropy`:

```python
import urllib.request
from astropy.io import fits

urlobj = urllib.request.urlopen('file:///path/to/file/that/exists.fits')
with fits.open(urlobj) as fits_handle:
    # go to town ...
```

I added a new unit test demonstrating as much in PR #6378, so hopefully this resolves the issue.

**Comment by pllim** [comment]
Nothing quite feels so good as a bug that resolved itself. :joy:

**Comment by bsipocz** [comment]
@pllim - I'm sure there are still a few hiding in the crowd of the 664 open issues that are solved themselves 😉
