### ISSUE TITLE
astropy.io.fits.HDUList.writeto creates invalid output with uint input

### ISSUE THREAD

**Issue by sbailey** [astropy/astropy#4166]
The following produces an invalid fits file when started from a fresh python session:

```
from astropy.io import fits
import numpy as np

#- Verification fails after first write
hx = fits.HDUList()
hx.append( fits.PrimaryHDU(np.zeros(10)) )
hx.append( fits.CompImageHDU(np.zeros(10).astype(np.uint16), uint=True) )
hx.writeto('blat.fits', clobber=True)
```

This can be checked by re-opening and verifying:

```
fx = fits.open('blat.fits')
fx.verify()

WARNING: VerifyWarning: Verification reported errors: [astropy.io.fits.verify]
WARNING: VerifyWarning: HDU 1: [astropy.io.fits.verify]
WARNING: VerifyWarning:     'TFIELDS' card at the wrong place (card 9). [astropy.io.fits.verify]
WARNING: VerifyWarning: Note: PyFITS uses zero-based indexing.
 [astropy.io.fits.verify]
```

Oddly enough, if you write two files in a row using the same I/O code, the first one is bogus while the second one is valid:

```
from astropy.io import fits
import numpy as np

def write_and_verify(filename):
    hx = fits.HDUList()
    hx.append( fits.PrimaryHDU(np.zeros(10)) )
    hx.append( fits.CompImageHDU(np.zeros(10).astype(np.uint16), uint=True) )
    hx.writeto(filename, clobber=True)
    fx = fits.open(filename)
    fx.verify()
    fx.close()

write_and_verify('blat.fits')  #- fails verification
write_and_verify('foo.fits')   #- succeeds
```

i.e. be careful when debugging this: you have to keep re-starting your ipython session to be able to reproduce the bug, or otherwise it magically starts to "work".

non-uint input seems to work fine.  I haven't found any combination of uint=X and/or verify=Y that produces a valid fits file on the first write when the input data are unsigned.

Using astropy 1.0.4, numpy 1.9, and python 2.7.10 a built by Anaconda for a Mac.

**Comment by embray** [comment]
One thing I can definitely say, for starters, is that the `uint=True` argument should actually *not* be used when creating a new HDU object.  Ideally it should just be ignored altogether in that case.  When you create an HDU with a data array with an unsigned int dtype it will automatically write it out with "pseudo-unsigned int" scaling.  

However when reading a file in, it's ambiguous as to whether scaled data should be read as unsigned ints or not, and so the `uint` argument is really only used internally, when reading a file in, to tell the HDU how to interpret its data.  Ideally it should not be exposed in the API and that's something I'd like to fix.

Nevertheless it seems like something fishy is going on here.

**Comment by sbailey** [comment]
OK, that's good to know.  I was trying uint=True in an attempt to get it to work, thinking that was supposed to be the correct usage.  But the bug appears whether or not uint=True when creating the CompImageHDU, and whether or not it is used when re-opening the file for verification.

**Comment by embray** [comment]
Okay, that helps. I'll investigate.    Is this just with compressed image HDUs?  I've never run across this before.

**Comment by sbailey** [comment]
Yes, this appears only to affect CompImageHDUs.  The following non-compressed image HDU example works fine:

    from astropy.io import fits
    import numpy as np

    #- Verification fails after first write
    hx = fits.HDUList()
    hx.append( fits.PrimaryHDU(np.zeros(10)) )
    ### hx.append( fits.CompImageHDU(np.zeros(10).astype(np.uint16)) )
    hx.append( fits.ImageHDU(np.zeros(10).astype(np.uint16)) )
    hx.writeto('blat.fits', clobber=True)

    fx = fits.open('blat.fits', uint=True)
    fx.verify()

**Comment by embray** [comment]
(By the way, in v1.1 (not out yet) the interpretation of unsigned ints will be the default behavior.)

**Comment by saimn** [comment]
I cannot reproduce the failure with the above examples, hopefully something changed and the bug is fixed :)
@sbailey - could you check on your side if you manage to reproduce, and reopen if this is the case ?
