### ISSUE TITLE
coverage travis job is broken 

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#4175]
See for example https://travis-ci.org/astropy/astropy/jobs/81288975 from #4174

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "astropy/tests/helper.py", line 307, in _save_coverage
    cov._harvest_data()
AttributeError: 'Coverage' object has no attribute '_harvest_data'
```

The `_harvest_data` method from the coverage module has been renamed in coverage 4.0 released today : 

> The private method Coverage._harvest_data is now called Coverage.get_data, and returns the CoverageData containing the collected data.

from https://github.com/nedbat/coveragepy/blob/master/CHANGES.rst

**Comment by cdeil** [comment]
We also got this error on travis-ci for Gammapy today:
https://travis-ci.org/gammapy/gammapy/jobs/81267312#L1465
https://github.com/gammapy/gammapy/pull/357#issuecomment-142011280

I guess this update to coverage 4.0 will broke the Python 2.7 coverage build for most affiliated packages?
What's the best way to fix this quickly?

I think for Gammapy I'll just move the coverage test to Python 3, that should fix it.

**Comment by embray** [comment]
Normally I'd say we should just pin the version.
