### ISSUE TITLE
Issue with astropy.time when importing sunpy.map

### ISSUE THREAD

**Issue by kkozarev** [astropy/astropy#4181]
Hello, I am having an issue with astropy.time when trying to import the map subpackage of sunpy. The following messages result (I already messaged the sunpy developers, who redirected me here):

```
In [1]: from sunpy import map
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-a1adac5bf47a> in <module>()
----> 1 from sunpy import map

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/map/__init__.py in <module>()
      6 
      7 
----> 8 from sunpy.map.mapbase import GenericMap
      9 
     10 from sunpy.map.header import MapMeta

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/map/mapbase.py in <module>()
     23 
     24 import sunpy.io as io
---> 25 import sunpy.wcs as wcs
     26 from sunpy.visualization import toggle_pylab
     27 from sunpy.sun import constants

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/wcs/__init__.py in <module>()
     45 from __future__ import absolute_import
     46 
---> 47 from sunpy.wcs.wcs import *

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/wcs/wcs.py in <module>()
      2 
      3 import numpy as np
----> 4 import sunpy.sun as sun
      5 
      6 import astropy.units

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/sun/__init__.py in <module>()
     13 from __future__ import absolute_import
     14 
---> 15 from sunpy.sun.sun import *
     16 
     17 from . import _constants

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/sun/sun.py in <module>()
     26 
     27 import astropy.units as u
---> 28 from astropy.coordinates import Angle, Longitude, Latitude
     29 
     30 from sunpy.time import parse_time, julian_day, julian_centuries

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/__init__.py in <module>()
     15 from .earth import *
     16 from .transformations import *
---> 17 from .builtin_frames import *
     18 from .name_resolve import *
     19 from .matching import *

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/__init__.py in <module>()
     26 
     27 from .icrs import ICRS
---> 28 from .fk5 import FK5
     29 from .fk4 import FK4, FK4NoETerms
     30 from .galactic import Galactic

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/fk5.py in <module>()
      8                          TimeFrameAttribute, RepresentationMapping)
      9 from ..transformations import DynamicMatrixTransform
---> 10 from .. import earth_orientation as earth
     11 
     12 from .utils import EQUINOX_J2000

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/earth_orientation.py in <module>()
     17 from .. import units as u
     18 
---> 19 jd1950 = Time('B1950', scale='tai').jd
     20 jd2000 = Time('J2000', scale='utc').jd
     21 _asecperrad = u.radian.to(u.arcsec)

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.pyc in __init__(self, val, val2, format, scale, precision, in_subfmt, out_subfmt, location, copy)
    206                 self._set_scale(scale)
    207         else:
--> 208             self._init_from_vals(val, val2, format, scale, copy)
    209 
    210         if self.location:

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.pyc in _init_from_vals(self, val, val2, format, scale, copy)
    248 
    249         # Parse / convert input values into internal jd1, jd2 based on format
--> 250         self._time = self._get_time_fmt(val, val2, format, scale)
    251         self._format = self._time.name
    252 

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.pyc in _get_time_fmt(self, val, val2, format, scale)
    288                 pass
    289         else:
--> 290             raise ValueError('Input values did not match {0}'.format(err_msg))
    291 
    292     @classmethod

ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']

In [2]: sunpy.system_info()
==========================================================
 SunPy Installation Information

==========================================================

###########
 General
###########
Time : Saturday, 19. September 2015 10:12AM UT
System : Darwin
Processor : i386
Arch : 64bit
SunPy : Missing version.py; re-run setup.py
SunPy_git : N/A
OS: Mac OS X 10.10.5 (i386)


###########
 Required Libraries 
###########
Python: 2.7.10
NumPy: 1.9.2
SciPy: 0.16.0
matplotlib: 1.4.3
Astropy: 1.0.4
Pandas: 0.16.2


###########
 Recommended Libraries 
###########
beautifulsoup: 4.3.2
PyQt: 4.11.3
SUDS: 0.6
Sqlalchemy: 1.0.8
Requests: 2.7.0
```

**Comment by taldcroft** [comment]
We've seen this exception before when working with a dev version of astropy that is slightly corrupted by way of a mismatch in the ERFA version.  It looks like you are using a release Astropy (1.0.4) but are you sure your environment is and build is clean?  Can you try a standalone test?

```
$ python
>>> import astropy
>>> astropy.test(package='time')
anaconda/lib/python2.7/site-packages/astropy/time/tests/test_basic.py ..................................................................................
anaconda/lib/python2.7/site-packages/astropy/time/tests/test_comparisons.py ...
anaconda/lib/python2.7/site-packages/astropy/time/tests/test_delta.py ................................................................................
anaconda/lib/python2.7/site-packages/astropy/time/tests/test_guess.py ....
anaconda/lib/python2.7/site-packages/astropy/time/tests/test_pickle.py .
anaconda/lib/python2.7/site-packages/astropy/time/tests/test_precision.py .......x..
anaconda/lib/python2.7/site-packages/astropy/time/tests/test_quantity_interaction.py .............
anaconda/lib/python2.7/site-packages/astropy/time/tests/test_sidereal.py ...................
anaconda/lib/python2.7/site-packages/astropy/time/tests/test_ut1.py ...s
```

**Comment by kkozarev** [comment]
@taldcroft thanks for the quick response. Here's the first part of the output (I have skipped the rest):

>>> import astropy
>>> astropy.test(package='time')
============================== test session starts ===============================
platform darwin -- Python 2.7.10 -- pytest-2.5.1

Running tests with Astropy version 1.0.4.
Running tests in /usr/local/anaconda/lib/python2.7/site-packages/astropy/time.

Platform: Darwin-14.5.0-x86_64-i386-64bit

Executable: /usr/local/anaconda/bin/python

Full Python Version: 
2.7.10 |Anaconda 1.8.0 (x86_64)| (default, Sep 15 2015, 14:29:08) 
[GCC 4.2.1 (Apple Inc. build 5577)]

encodings: sys: ascii, locale: UTF-8, filesystem: utf-8, unicode bits: 15
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.9.2
Scipy: 0.16.0
Matplotlib: 1.4.3
h5py: 2.2.0

collected 115 items / 2 errors 

../../../../../usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_comparisons.py F..
../../../../../usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_delta.py EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
../../../../../usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_guess.py ....
../../../../../usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_pickle.py F
../../../../../usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_precision.py F.FFFFFx..
../../../../../usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_quantity_interaction.py F...FF.......
../../../../../usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_ut1.py F.Fs

===================================== ERRORS =====================================
 ERROR collecting ../../../../../usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_basic.py 
/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_basic.py:17: in <module>
>   from ...coordinates import EarthLocation
/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/__init__.py:17: in <module>
>   from .builtin_frames import *
/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/__init__.py:28: in <module>
>   from .fk5 import FK5
/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/fk5.py:10: in <module>
>   from .. import earth_orientation as earth
/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/earth_orientation.py:19: in <module>
>   jd1950 = Time('B1950', scale='tai').jd
/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:208: in __init__
>           self._init_from_vals(val, val2, format, scale, copy)
/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:250: in _init_from_vals
>       self._time = self._get_time_fmt(val, val2, format, scale)
/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:290: in _get_time_fmt
>           raise ValueError('Input values did not match {0}'.format(err_msg))
E           ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']
 ERROR collecting ../../../../../usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_sidereal.py 
/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_sidereal.py:24: in <module>
>   class TestERFATestCases():
/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_sidereal.py:33: in TestERFATestCases
>       time_ut1.delta_ut1_utc = 24*3600*(time_ut1.tt.jd2-time_tt.jd2)
/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:704: in __getattr__
>           tm._set_scale(attr)
/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:376: in _set_scale
>           jd1, jd2 = conv_func(*args)
E           TypeError: Argument 'in1' has incorrect type (expected numpy.ndarray, got numpy.float64)
____________________ ERROR at setup of TestTimeDelta.test_sub ____________________

self = <astropy.time.tests.test_delta.TestTimeDelta instance at 0x10a08e7a0>

    def setup(self):
>       self.t = Time('2010-01-01', scale='utc')

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_delta.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'Time' object has no attribute '_time'") raised in repr()] SafeRepr object at 0x10a08ec20>
val = '2010-01-01', val2 = None, format = None, scale = 'utc', precision = None
in_subfmt = None, out_subfmt = None, location = None, copy = False

    def __init__(self, val, val2=None, format=None, scale=None,
                 precision=None, in_subfmt=None, out_subfmt=None,
                 location=None, copy=False):
    
        if location is not None:
            from ..coordinates import EarthLocation
            if isinstance(location, EarthLocation):
                self.location = location
            else:
                self.location = EarthLocation(*location)
        else:
            self.location = None
    
        if precision is not None:
            self.precision = precision
        if in_subfmt is not None:
            self.in_subfmt = in_subfmt
        if out_subfmt is not None:
            self.out_subfmt = out_subfmt
    
        if isinstance(val, self.__class__):
            if scale is not None:
                self._set_scale(scale)
        else:
>           self._init_from_vals(val, val2, format, scale, copy)

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:208: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'Time' object has no attribute '_time'") raised in repr()] SafeRepr object at 0x10a098518>
val = array('2010-01-01', 
      dtype='|S10'), val2 = None, format = None
scale = 'utc', copy = False

    def _init_from_vals(self, val, val2, format, scale, copy):
        """
            Set the internal _format, scale, and _time attrs from user
            inputs.  This handles coercion into the correct shapes and
            some basic input validation.
            """
    
        # Coerce val into an array
        val = _make_array(val, copy)
    
        # If val2 is not None, ensure consistency
        if val2 is not None:
            val2 = _make_array(val2, copy)
            try:
                np.broadcast(val, val2)
            except ValueError:
                raise ValueError('Input val and val2 have inconsistent shape; '
                                 'they cannot be broadcast together.')
    
        if scale is not None:
            if not (isinstance(scale, six.string_types) and
                    scale.lower() in self.SCALES):
                raise ScaleValueError("Scale {0} is not in the allowed scales "
                                      "{1}".format(repr(scale),
                                                   sorted(self.SCALES)))
    
        # Parse / convert input values into internal jd1, jd2 based on format
>       self._time = self._get_time_fmt(val, val2, format, scale)

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:250: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'Time' object has no attribute '_time'") raised in repr()] SafeRepr object at 0x10a5d8758>
val = array('2010-01-01', 
      dtype='|S10'), val2 = None, format = 'byear_str'
scale = 'utc'

    def _get_time_fmt(self, val, val2, format, scale):
        """
            Given the supplied val, val2, format and scale try to instantiate
            the corresponding TimeFormat class to convert the input values into
            the internal jd1 and jd2.
    
            If format is `None` and the input is a string-type or object array then
            guess available formats and stop when one matches.
            """
    
        if format is None and val.dtype.kind in ('S', 'U', 'O'):
            formats = [(name, cls) for name, cls in self.FORMATS.items()
                       if issubclass(cls, TimeUnique)]
            err_msg = ('any of the formats where the format keyword is '
                       'optional {0}'.format([name for name, cls in formats]))
        elif not (isinstance(format, six.string_types) and
                  format.lower() in self.FORMATS):
            if format is None:
                raise ValueError("No time format was given, and the input is "
                                 "not unique")
            else:
                raise ValueError("Format {0} is not one of the allowed "
                                 "formats {1}".format(repr(format),
                                                      sorted(self.FORMATS)))
        else:
            formats = [(format, self.FORMATS[format])]
            err_msg = 'the format class {0}'.format(format)
    
        for format, FormatClass in formats:
            try:
                return FormatClass(val, val2, scale, self.precision,
                                   self.in_subfmt, self.out_subfmt)
            except UnitConversionError:
                raise
            except (ValueError, TypeError):
                pass
        else:
>           raise ValueError('Input values did not match {0}'.format(err_msg))
E           ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:290: ValueError
____________________ ERROR at setup of TestTimeDelta.test_add ____________________

self = <astropy.time.tests.test_delta.TestTimeDelta instance at 0x10a6efe60>

    def setup(self):
>       self.t = Time('2010-01-01', scale='utc')

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/tests/test_delta.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'Time' object has no attribute '_time'") raised in repr()] SafeRepr object at 0x10a5e1c20>
val = '2010-01-01', val2 = None, format = None, scale = 'utc', precision = None
in_subfmt = None, out_subfmt = None, location = None, copy = False

    def __init__(self, val, val2=None, format=None, scale=None,
                 precision=None, in_subfmt=None, out_subfmt=None,
                 location=None, copy=False):
    
        if location is not None:
            from ..coordinates import EarthLocation
            if isinstance(location, EarthLocation):
                self.location = location
            else:
                self.location = EarthLocation(*location)
        else:
            self.location = None
    
        if precision is not None:
            self.precision = precision
        if in_subfmt is not None:
            self.in_subfmt = in_subfmt
        if out_subfmt is not None:
            self.out_subfmt = out_subfmt
    
        if isinstance(val, self.__class__):
            if scale is not None:
                self._set_scale(scale)
        else:
>           self._init_from_vals(val, val2, format, scale, copy)

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:208: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'Time' object has no attribute '_time'") raised in repr()] SafeRepr object at 0x10a5e1f38>
val = array('2010-01-01', 
      dtype='|S10'), val2 = None, format = None
scale = 'utc', copy = False

    def _init_from_vals(self, val, val2, format, scale, copy):
        """
            Set the internal _format, scale, and _time attrs from user
            inputs.  This handles coercion into the correct shapes and
            some basic input validation.
            """
    
        # Coerce val into an array
        val = _make_array(val, copy)
    
        # If val2 is not None, ensure consistency
        if val2 is not None:
            val2 = _make_array(val2, copy)
            try:
                np.broadcast(val, val2)
            except ValueError:
                raise ValueError('Input val and val2 have inconsistent shape; '
                                 'they cannot be broadcast together.')
    
        if scale is not None:
            if not (isinstance(scale, six.string_types) and
                    scale.lower() in self.SCALES):
                raise ScaleValueError("Scale {0} is not in the allowed scales "
                                      "{1}".format(repr(scale),
                                                   sorted(self.SCALES)))
    
        # Parse / convert input values into internal jd1, jd2 based on format
>       self._time = self._get_time_fmt(val, val2, format, scale)

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:250: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'Time' object has no attribute '_time'") raised in repr()] SafeRepr object at 0x10a5e53b0>
val = array('2010-01-01', 
      dtype='|S10'), val2 = None, format = 'byear_str'
scale = 'utc'

    def _get_time_fmt(self, val, val2, format, scale):
        """
            Given the supplied val, val2, format and scale try to instantiate
            the corresponding TimeFormat class to convert the input values into
            the internal jd1 and jd2.
    
            If format is `None` and the input is a string-type or object array then
            guess available formats and stop when one matches.
            """
    
        if format is None and val.dtype.kind in ('S', 'U', 'O'):
            formats = [(name, cls) for name, cls in self.FORMATS.items()
                       if issubclass(cls, TimeUnique)]
            err_msg = ('any of the formats where the format keyword is '
                       'optional {0}'.format([name for name, cls in formats]))
        elif not (isinstance(format, six.string_types) and
                  format.lower() in self.FORMATS):
            if format is None:
                raise ValueError("No time format was given, and the input is "
                                 "not unique")
            else:
                raise ValueError("Format {0} is not one of the allowed "
                                 "formats {1}".format(repr(format),
                                                      sorted(self.FORMATS)))
        else:
            formats = [(format, self.FORMATS[format])]
            err_msg = 'the format class {0}'.format(format)
    
        for format, FormatClass in formats:
            try:
                return FormatClass(val, val2, scale, self.precision,
                                   self.in_subfmt, self.out_subfmt)
            except UnitConversionError:
                raise
            except (ValueError, TypeError):
                pass
        else:
>           raise ValueError('Input values did not match {0}'.format(err_msg))
E           ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.py:290: ValueError
________________ ERROR at setup of TestTimeDelta.test_add_vector _________________

**Comment by embray** [comment]
This is a known issue you can fix by uninstalling and reinstalling your copy of Astropy:

http://docs.astropy.org/en/stable/known_issues.html#creating-a-time-object-fails-with-valueerror-after-upgrading-astropy

**Comment by kkozarev** [comment]
Thanks. I have installed astropy through Anaconda. I uninstalled it (conda uninstall astropy) and reinstalled it, but the problem persisted. Should I be looking to remove package files somewhere specific after the uninstall?

**Comment by kkozarev** [comment]
UPDATE: I fixed the issue by uninstalling the Anaconda version of astropy and building it from source. Thanks for the help.
