### ISSUE TITLE
test_socketblocker.py seem to block in Debian CI tests

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#4193]
The latest Debian CI tests [fail with](http://ci.debian.net/data/packages/unstable/amd64/p/python-astropy/20150912_222803.autopkgtest.log.gz)

```
../../usr/lib/python3/dist-packages/astropy/tests/tests/test_socketblocker.py ...E: Caught signal ‘Terminated’: terminating immediately

Session terminated, terminating shell...bash: line 1: 22455 Terminated              /tmp/adt-run.pWQpB0/build.nGt/python-astropy-1.0.4/debian/tests/python3-astropy 2> >(tee -a /tmp/adt-run.pWQpB0/python3-astropy-stderr >&2) > >(tee -a /tmp/adt-run.pWQpB0/python3-astropy-stdout)
 ...terminated.
adt-run [01:22:58]: ERROR: testbed failed: timed out on command "[...]"
```

during the testing with python-3.4. 
This is, however, _only_ during the CI tests. The same test passes during the package build.

**Comment by embray** [comment]
Is it just that test?  That is, do the tests otherwise run if that test is disabled?

**Comment by embray** [comment]
Also is there any way you can run the tests with `--verbose-results` so we can see specifically which test it is, rather than just which test module?  [This test](https://github.com/astropy/astropy/blob/master/astropy/tests/tests/test_socketblocker.py#L70), for example, should already be skipped it seems.

**Comment by embray** [comment]
Oh, I misread, it seems the forkserver test is skipped *except* on Python 3.4.  That might implicate it in this issue then...

**Comment by olebole** [comment]
It seems to be just this one test -- 2.7 succeeds completely, and 3.4 runs until this one (I didn't disable it). Since the test in fact has nothing to do with astropy (but is a test of a python functionality), I would not put too much effort here yet -- I am discussing it on the [Debian mailing](https://lists.debian.org/debian-devel/2015/09/msg00576.html) list as well. It may be well a problem of our CI environment (and/or of Python 3.4).

**Comment by embray** [comment]
Curious.  In the meantime it's fine if you just disable it.

**Comment by bsipocz** [comment]
@olebole - There are a few releases out since you've run into this. Do you think it's still an issue?

**Comment by olebole** [comment]
For the moment, I can't test it, since our CI test platform runs only on [unstable](https://ci.debian.net/packages/p/python-astropy/), and we are in a freeze so that I don't want to upload unrelated changes. Once Stretch is out (later in spring?) I will check, and close the issue if it disappeared.

**Comment by bsipocz** [comment]
@olebole - Would you be able to test this again?

**Comment by olebole** [comment]
OK, took some time: This is unfortunately not fixed with version 2.0. [Here](https://ci.debian.net/data/autopkgtest/unstable/amd64/p/python-astropy/20170711_121322/log.gz) is the actual CI test that times out.

The test succeeds at build time.

**Comment by bsipocz** [comment]
The remote-data plugin has been moved out of core, so this issue should be either closed or moved to https://github.com/astropy/pytest-remotedata/. 
@astrofrog or @eteq - could you please move it?

**Comment by olebole** [comment]
I'd propose to just close it. The tests work fine now; if it really re-appears (I doubt that), then I could make a new issue in pytest-remotedata.
@bsipocz It is great that you go through the issues! Thanks! Obviously, I sometimes lose track on the issues I opened, sorry for that.
