### ISSUE TITLE
empty MaskedColumn defaults to `mask=True`?

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#4206]
I can create an empty column for a table like this: `col = astropy.table.Column(name='col', dtype=float, length=3)` and the column is going to be filled with some default value (0.0 for float). Then, we have `MaskedColumn` which behaves the same way. 
Instead, I want to suggest that a `MaskedColumn` with no data should default to `mask=True`. After all, we usually use masked columns to represent missing data.

```
In [774]: t = Table([['a','b','c']])

In [775]: t.add_column(MaskedColumn(name='col1',dtype=float, length=3))

In [776]: t
Out[776]:
<Table length=3>
col0   col1
str1 float64
---- -------
   a     0.0
   b     0.0
   c     0.0
```
I can manually set `mask=True`, but for empty`MaskedColumn` objects I want to suggest that this should be the default.
```
In [778]: t.add_column(MaskedColumn(name='col2',dtype=float, length=3, mask=True))
INFO: Upgrading Table to masked Table. Use Table.filled() to convert to unmasked table. [astropy.table.table]

In [779]: t
Out[779]:
<Table masked=True length=3>
col0   col1    col2
str1 float64 float64
---- ------- -------
   a     0.0      --
   b     0.0      --
   c     0.0      --
```
@taldcroft

**Comment by taldcroft** [comment]
I can see the logic, but I don't think that the pain of an API break is really worth it for saving 11 characters (`, mask=True`).  In this release we would have some sort of PendingApiChange warning when `mask` is not specified, then change the default in 1.2.  Then the only way to write code that can work on LTS (1.0.x) astropy and current astropy would be to explicitly specify `mask=` whenever creating a MaskedColumn.

I'm also only 50/50 on whether a default of `mask=True` is sensible.  I think of `MaskedColumn` as a normal column that *can* be masked, so in that sense the default for an empty column would be the same in all cases (masked or not).

**Comment by hamogu** [comment]
I wanted to bring it up, but I accept your arguments.

**Comment by taldcroft** [comment]
API stability is a two-edged sword.  It also feels like I'll be developing in Python 2.7 for the foreseeable future...
