### ISSUE TITLE
Question about the docs of astropy.io.fits

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4218]
In the documentation it states (http://astropy.readthedocs.org/en/stable/io/fits/#opening-a-fits-file) that:

The headers will still be accessible after the HDUList is closed. The data may or may not be accessible depending on whether the data are touched and if they are memory-mapped, see later chapters for detail.

Where can I find these later chapters? I even tried looking at the HDUList.close() documentation but could not find any information. Is there just the link or the 'later chapters' missing? Or is it referring to the 'Warning: About memmap'?

**Comment by embray** [comment]
Yeah, I'm not even sure.  That should be rewritten or removed.  Thanks for pointing it out.

**Comment by pllim** [comment]
Fixed in #7474.
