### ISSUE TITLE
wcs fails on import

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy#4230]
I'm using Python 2.7.10, numpy 1.9.3, astropy 1.0.5 on Scientific Linux, and getting the following `ImportError`:
```
In [1]: import astropy.wcs
impor---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version a but this version of numpy is 9
t---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version a but this version of numpy is 9
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/lib/python2.7/site-packages/astropy/wcs/wcs.py in <module>()
     45 from . import _docutil as __
     46 try:
---> 47     from . import _wcs
     48 except ImportError:
     49     if not _ASTROPY_SETUP_:

ImportError: numpy.core.multiarray failed to import
```
but if I import `numpy.core.multiarray`, I have no problems. Any ideas? cc @jlurie @ethankruse

**Comment by astrofrog** [comment]
This is the key error message here:

```
RuntimeError: module compiled against API version a but this version of numpy is 9
```

Seems like Astropy was compiled against and older version of Numpy?

**Comment by bmorris3** [comment]
We've fixed the issue by installing the latest version of numpy (1.10).

**Comment by keflavich** [comment]
I have this issue now trying to *test* against numpy 1.9.  I guess this is related to @mwcraig's e-mails?

My error looks like:
```
cyg ~/repos/spectral-cube median_fix$ conda install -n astropy35 numpy=1.9 astropy
Fetching package metadata: ....
Solving package specifications: ...............
# All requested packages already installed.
# packages in environment at /Users/adam/anaconda/envs/astropy35:
#
astropy                   1.0.4                np19py35_0
numpy                     1.9.3                    py35_0
cyg ~/repos/spectral-cube median_fix$ python -c "import astropy,numpy; print(astropy.__version__,numpy.__version__)"
1.0.4 1.9.3
cyg ~/repos/spectral-cube median_fix$ python setup.py test
RuntimeError: module compiled against API version a but this version of numpy is 9
RuntimeError: module compiled against API version a but this version of numpy is 9
```

The problem persists on a clean install of astropy-dev.

**Comment by mwcraig** [comment]
@keflavich -- if I had to guess that astropy/numpy combination is incorrectly built (by continuum). Will confirm later and report it to them.

**Comment by keflavich** [comment]
Thanks.  This has left me very confused.  I'm not entirely sure, but it may also have something to do with importing `yt`.

**Comment by mwcraig** [comment]
@keflavich -- I wasn't able to reproduce this. Looking at the clip above, is it possible you didn't activate the test environment?

**Comment by keflavich** [comment]
I never activate environments, I just use the full path.  I've since resolved the problem by effectively reinstalling everything.  I still don't understand what caused it, but it may have been a conflict between a `python setup.py develop` build that was done before changing numpy versions, or something along those lines.

**Comment by astrofrog** [comment]
@keflavich - just to make sure I understand, what is the output of ``which python`` in your above example? Have you set conda to auto-switch to new environments?

**Comment by astrofrog** [comment]
Also, if you update the version of Numpy, you need to also re-install all packages built against Python in the same command (e.g. matplotlib, h5py, etc.) - see https://github.com/conda/conda/issues/1841

**Comment by keflavich** [comment]
No, I have not set conda to auto switch.   I have a particular env set on my path, and if I want a different one, I explicitly use the full path to that file (i.e., `/path/to/anaconda/bin/python`).

On the second comment - yeah, that is likely to be the source of the problem.  If I understand right, conda will update any installed packages installed through conda, but if I've installed any from source (e.g., with `develop`), I need to recompile those myself.

**Comment by bmorris3** [comment]
@astrofrog I'm seeing a similar error now in sphinx docs that I'm building for a package that uses the astropy package template. See the failing sphinx [build here](https://readthedocs.org/projects/shampoo/builds/4238986/). Any idea how this error could happen on the Read the Docs machines, which are installing a fresh version of numpy (and scikit-image, where the error stems from)?
