### ISSUE TITLE
hstack of FITS_rec broken

### ISSUE THREAD

**Issue by sbailey** [astropy/astropy#4233]
`np.hstack` of `FITS_rec` objects produces objects that cannot be re-written using `astropy.io.fits`.  Using example files from:

http://portal.nersc.gov/project/cosmo/data/legacysurvey/dr1/tractor/000/tractor-0001m002.fits
http://portal.nersc.gov/project/cosmo/data/legacysurvey/dr1/tractor/000/tractor-0001m005.fits

```
d1 = fits.getdata('tractor-0001m002.fits')
d2 = fits.getdata('tractor-0001m005.fits')
dx = np.vstack([d1, d2])
dx.dtype == d1.dtype                        #- True
dx.shape[0] == d1.shape[0] + d2.shape[0]    #- True

fits.writeto('blat.fits', dx, clobber=True) #- Fails
```
Fails with:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-d60b1e0bb7a6> in <module>()
----> 1 fits.writeto('blat.fits', dx, clobber=True)

/Users/sbailey/anaconda/lib/python2.7/site-packages/astropy/io/fits/convenience.pyc in writeto(filename, data, header, output_verify, clobber, checksum)
    403     """
    404 
--> 405     hdu = _makehdu(data, header)
    406     if hdu.is_image and not isinstance(hdu, PrimaryHDU):
    407         hdu = PrimaryHDU(data, header=header)

/Users/sbailey/anaconda/lib/python2.7/site-packages/astropy/io/fits/convenience.pyc in _makehdu(data, header)
    768         if ((isinstance(data, np.ndarray) and data.dtype.fields is not None)
    769                 or isinstance(data, np.recarray)):
--> 770             hdu = BinTableHDU(data)
    771         elif isinstance(data, np.ndarray):
    772             hdu = ImageHDU(data)

/Users/sbailey/anaconda/lib/python2.7/site-packages/astropy/io/fits/hdu/table.pyc in __init__(self, data, header, name, uint)
    328                                 update_coldefs[k] = bzeros[dtype.itemsize]
    329                             else:
--> 330                                 new_data[k] = data[k]
    331                         self.data = new_data.view(self._data_type)
    332                         # Uck...

ValueError: could not broadcast input array from shape (10122,6) into shape (10122)
```
Explicitly converting `d1` and `d2` into numpy arrays prior to the hstack also doesn't work, resulting in the same error when trying to write it out.

astropy 1.0.4
numpy 1.10.0.post2

**Comment by mhvk** [comment]
@sbailey - don't know if you can test this easily, but does it work on older numpy? There's still work in progress on getting astropy to work with numpy 1.10, and `io.fits` is a hold-out (see #3854; that said, it doesn't look like one of the errors we found there, just checking...).

**Comment by sbailey** [comment]
I have the same problem with numpy 1.9.2.  Using numpy 1.10.0.post2 was part of the attempt to see if the problem had already been fixed.  The example files are publicly downloadable, so others can do tests with their particular combinations of package versions too.

**Comment by embray** [comment]
This isn't going to work in general for the same reasons explained in #3919 and similarly #3073 of which this is just another symptom.  A Numpy builtin like vstack or hstack isn't going to know what to do with the `FITS_rec` internal data structures that track conversion from the native FITS format.

If you want to stack two tables together I recommend using the higher level functionality in `astropy.table`:

```python
from astropy.table import Table, vstack
>>> t1 = Table.read('http://portal.nersc.gov/project/cosmo/data/legacysurvey/dr1/tractor/000/tractor-0001m002.fits')
>>> t2 = Table.read('http://portal.nersc.gov/project/cosmo/data/legacysurvey/dr1/tractor/000/tractor-0001m005.fits')
>>> t3 = vstack((t1, t2))
```

(note, you will get warnings about some of the funky units in those tables but those can generally be ignored).

**Comment by embray** [comment]
I'm going to close this because hstack (or vstack) are never going to work right with `FITS_rec` as such--it's an unfortunate fact of how those functions work.  If I ever get the new data representation for FITS data going it might work better but since there's already a good workaround to use `Table` I think that's where we'll have to leave things for now.

**Comment by sbailey** [comment]
This is unfortunate, for several reasons:
  * isinstance indicates that FITS_rec is a subclass of numpy.ndarray, which would imply that they should be useable by any function operating on ndarrays.  I normally expect subclasses to extend the features of the parent class while preserving all of the parent class functionality.
  * Even casting to a vanilla ndarray produces a munged ndarray that can't be stacked.  Could you provide a way to convert a FITS_rec to an ndarray that has all the functionality of a normal ndarray?  e.g. FITS_rec.toarray() that would create a valid ndarray without the under-the-hood differences of FITS_rec?
  * Table.read() is significantly slower than fits.getdata() for these files.  The amount depends upon the metadata I/O performance and the local processing speed, but on my laptop Table is 2x slower; on the Edison machine at NERSC it is 8x slower.

**Comment by mhvk** [comment]
@sbailey - you're right in thinking subclasses of `ndarray` should behave... Unfortunately, many numpy functions throw away information about subclasses, and `hstack` and `vstack` are among those. In particular, while they keep the class, they remove all subclass-specific information. For the same reason, those [cannot be used] (http://docs.astropy.org/en/latest/known_issues.html#quantities-lose-their-units-with-some-operations) on `Quantity` instances either: one loses the unit. So, really, this is a numpy bug (though one not that easy to solve).

It it quite trivial to convert the stacked frames to ndarray (just do `dx = dx.view(np.ndarray)`), but then you cannot just write it to a fits file anymore, but need to construct a new header.

**Comment by sbailey** [comment]
> It it quite trivial to convert the stacked frames to ndarray (just do dx = dx.view(np.ndarray)), but then you cannot just write it to a fits file anymore, but need to construct a new header.

I may be misunderstanding, but I haven't found any recipe for writing the stacked frame (or any FITS_rec converted back to ndarray) to fits without converting it to a Table first (which is a pretty high overhead operation that is problematic when spinning over TBs of data).  e.g.
```
d = fits.getdata('tractor-0001m002.fits').view(np.ndarray)
type(d)  #- numpy.ndarray
hdu = fits.BinTableHDU(d)  #- fails with same basic problem as original post
```
i.e. I think it is more than just having to recreate a FITS header.

**Comment by embray** [comment]
> e.g. FITS_rec.toarray() that would create a valid ndarray without the under-the-hood differences of FITS_rec?

That's still going to wind up being quite slow because it will have to create a new array in memory and copy into it.  The reasons for this are explained in #3073--the raw data on disk in many FITS tables does not reflect the logical data one actually wants to work with.  If you need high performance manipulations of tabular data I would recommend dumping data out of FITS and into a more appropriate format for that like HDF5.  Use FITS only as a *transport* format.

**Comment by embray** [comment]
> fits.getdata('tractor-0001m002.fits').view(np.ndarray)

When you do a *view* of a Numpy array it's going to directly reflect the underlying raw data buffer.  But for FITS_rec objects the raw data buffer does not often reflect the logical data that you really want to work on, which is why this breaks.  

The only exception is if the data is limited to strings, signed integers, and floating point data of fixed sizes without any linear rescaling.  In those cases, and only those cases, are the raw FITS data and the logical data the same.
