### ISSUE TITLE
Travis random test suite interruptions in io.votable

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#4240]
Travis regularly stops in the middle of `io.votable`, in ways [like] (https://travis-ci.org/astropy/astropy/jobs/85177508):
```
astropy/io/votable/tests/util_test.py ......................

The command "$MAIN_CMD $SETUP_CMD" exited with 245.

Done. Your build exited with 1.
```

Is there anything suspicious in these particular tests? I suspect some type of connection problems. It would be nice to resolve those...

**Comment by embray** [comment]
That can happen when the test takes too long, and Travis times out and kills the process.  So it definitely seems like there's a test in there that should be setting a shorter timeout somehow...

**Comment by mhvk** [comment]
I don't recall that particular test run having taken that long, but sadly it seems that by restarting the old log is overwritten, so I cannot check it.

**Comment by algerdnazgul** [comment]
Have similar probleim in https://travis-ci.org/astropy/astropy/jobs/93095947

**Comment by mhvk** [comment]
@algerdnazgul - thanks for posting your link. Aligning the two:
```
yours: astropy/io/votable/tests/util_test.py ......................
mine:  astropy/io/votable/tests/util_test.py ......................
```
it seems quite clear that it is the same test that is problematic.

**Comment by embray** [comment]
It doesn't make a whole lot of sense...  The *only* function tested in that module is `astropy.io.votable.util.coerce_range_list_param` which is a simple utility function that doesn't access any external resources or have any reason to hang a long time.

More likely if it's hanging it's on the immediate following test: `astropy/io/votable/tests/vo_test.py::test_parse_single_table`, though it still doesn't make a lot of sense.

**Comment by astrofrog** [comment]
Can you run the tests with ``-a "-vs"``?

**Comment by embray** [comment]
We'd probably have to set that up to run in travis--I've never been able to reproduce this locally.  And even then it's very sporadic on travis... :/

**Comment by olebole** [comment]
There were earlier occasional failures of VO tests, reported in #1882.

**Comment by mhvk** [comment]
The random VO table tests are still a problem -- e.g., https://travis-ci.org/astropy/astropy/jobs/100906365

**Comment by embray** [comment]
Yeah I've seen it on occasion too.  I've never seen this happen locally so I remain baffled.

**Comment by mhvk** [comment]
I'm closing this in favour of #4739, which I think is zeroing in a bit better on what the problem might be with the vo test failures (haven't seen them recently myself).
