### ISSUE TITLE
list of cosmology functions in documentation

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#4244]
In a recent conversation, someone pointed that it would be useful to have a quick list reference of the cosmology functions that are available in the package.   A table with each function, link to the function, and brief description of what it does would be very helpful in the docs.

**Comment by souravsingh** [comment]
I would like to work on this

**Comment by crawfordsm** [comment]
If you would @souravsingh , please go ahead and submit a PR and we can discuss this further there

**Comment by astrofrog** [comment]
@crawfordsm - just to check, can you clarify what you mean, since all the methods are advertised here?

http://docs.astropy.org/en/stable/api/astropy.cosmology.FLRW.html#astropy.cosmology.FLRW

I think we deprecated the pure functional interface, correct? (cc @nhmc @aconley)

**Comment by nhmc** [comment]
Yes, the functional interface is deprecated. 

I agree it would be useful to have a list of FLRW methods on the main cosmology doc page. There used to be a list auto-generated from the functions (e.g. http://docs.astropy.org/en/v0.2.1/cosmology/index.html#functions), but that's disappeared now they've been removed.

**Comment by crawfordsm** [comment]
Yes @astrofrog, but something which is just set possible as a table listing the method and a brief description of what the method does.  This should probably be linked to at the start of the cosmo documents so that it is quick and easy to find.   Basically, a cheat sheet for the cosmology package.

**Comment by astrofrog** [comment]
:+1:

**Comment by sudk1896** [comment]
@crawfordsm: Do you also want a list and brief description of all the different classes in the cosmology module (eg. w0wzCDM etc.) or are these different classes , the functions that you want documentation on.

**Comment by sudk1896** [comment]
@crawfordsm : Do you want a list of all the functions /methods that are there in all the different classes present in cosmology ? Is that it ?

**Comment by souravsingh** [comment]
A cheatsheet listing the functions for the cosmology package should be good

**Comment by souravsingh** [comment]
If possible, Can anyone check the PR I have submitted for the issue ? Cc @crawfordsm

**Comment by algerdnazgul** [comment]
There is a problems there. Check for Travis log, plz.

**Comment by bsipocz** [comment]
@algerdnazgul - Travis fail is unrelated, the file in the linked PR is not bundled to the tests/sphinx. Anyway it would be good to know whether there are any plans to do any more work on it there.

**Comment by nzuckman** [comment]
If this issue is still open, I'd like to have a go at it. :)

**Comment by nzuckman** [comment]
Some points I'd like to clarify: 
Should I make a new file that will list and describe each of the functions in the cosmology sub-package? Or, should I add the list of functions as a section in `astropy/docs/cosmology/index.rst` or something similar? 
Also, are there any functions that I should ignore?

**Comment by KING-SID** [comment]
Hey! I want to work on this issue, is it still an active one? How can I work on it if it is?

**Comment by crawfordsm** [comment]
This is still open -- we would like an RST page that lists all the FLRW methods and provides a brief description of what they do.

**Comment by KING-SID** [comment]
On it!

**Comment by algerdnazgul** [comment]
> @algerdnazgul - Travis fail is unrelated, the file in the linked PR is not bundled to the tests/sphinx. Anyway it would be good to know whether there are any plans to do any more work on it there.

I have no plans now

**Comment by KING-SID** [comment]
Hey @algerdnazgul ! Can you please let me know specifically what is needed as I intend to work on it. I see that the page (in the link added below) seems to already have a methods list with a summary for each method. Can you help me understand what is missing?

> @crawfordsm , what is missing with regard to the FLRW methods and method briefs on the [FLRW doc page](http://docs.astropy.org/en/latest/api/astropy.cosmology.FLRW.html#astropy.cosmology.FLRW.lookback_distance)
Are there any missing methods? Can you please guide me on what needs to be solved exactly? Given what is already on the I am unable to understand what updates are needed. Thank you in advance!

**Comment by stscicrawford** [comment]
To clarify, we would like a page as part of the documents with a table listing all the methods available for an FLRW cosmology.  The table should be two columns.  The first column should be the name of the method where the name would be a link to the method on the [FLRW doc page](http://docs.astropy.org/en/latest/api/astropy.cosmology.FLRW.html#astropy.cosmology.FLRW.lookback_distance).  The second column should be a short one sentence description of what the method does.  This page should be linked to from the main cosmology page.   It should be in Restructured Text format.  

The purpose of this page is to provide a quick reference of the information which is provided in more detail on [FLRW doc page (http://docs.astropy.org/en/latest/api/astropy.cosmology.FLRW.html#astropy.cosmology.FLRW.lookback_distance).

**Comment by crawfordsm** [comment]
To clarify, we would like a page as part of the documents with a table listing all the methods available for an FLRW cosmology. The table should be two columns. The first column should be the name of the method where the name would be a link to the method on the [FLRW doc page](http://docs.astropy.org/en/latest/api/astropy.cosmology.FLRW.html#astropy.cosmology.FLRW.lookback_distance). The second column should be a short one sentence description of what the method does. This page should be linked to from the main cosmology page. It should be in Restructured Text format.

The purpose of this page is to provide a quick reference of the information which is provided in more detail on [FLRW doc page](http://docs.astropy.org/en/latest/api/astropy.cosmology.FLRW.html#astropy.cosmology.FLRW.lookback_distance).

**Comment by KING-SID** [comment]
Makes sense, I'll get to the cheat sheet then!

**Comment by KING-SID** [comment]
@crawfordsm I have created the cheat sheet. How do I add it to the repository?

**Comment by crawfordsm** [comment]
Please follow the instructions on how to make a code contribution:
http://docs.astropy.org/en/stable/development/workflow/development_workflow.html

**Comment by nstarman** [comment]
@crawfordsm, would you agree this is resolved by sphinx automodapi in the attributes and methods summary? If so, it would be good to close this issue.

<img width="747" alt="Screen Shot 2021-07-14 at 16 17 48" src="https://user-images.githubusercontent.com/8949649/125687243-76caed76-3fac-4be3-8f4b-45459b931411.png">

**Comment by crawfordsm** [comment]
Agreed.
