### ISSUE TITLE
1.1b1: Failing to clean

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#4245]
When I (twice) run `python setup.py clean -a` on the source tree just checked out from the tarball, I get
```
$ python setup.py clean -a
Unexpected output from `git submodule status`:

Will attempt import from 'astropy_helpers' regardless.
running clean
'build/lib.linux-x86_64-2.7' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
$ python setup.py clean -a
Unexpected output from `git submodule status`:

Will attempt import from 'astropy_helpers' regardless.
WARNING: You appear to be trying to import astropy from within a source checkout without building the extension modules first.  Attempting to (re)build extension modules: [astropy]
Rebuilding extension modules [Failed]
ERROR: An error occurred while attempting to rebuild the extension modules.  Please try manually running `./setup.py develop` or `./setup.py build_ext --inplace` to see what the issue was.  Extension modules must be successfully compiled and importable in order to import astropy. [astropy]
Rebuilding extension modules  \
```
and the then the build python processes are going to eat up all available memory (8 GB RAM + 6 GB swap). Not sure what happens when I just run the `python setup.py build`, however (Debian always does a clean before the actual build).

**Comment by embray** [comment]
I don't think I've ever run the `./setup.py clean` command, or at least not in a long time.  My experience has been that it's not often very useful.

**Comment by embray** [comment]
I can't seem to reproduce this.  Is there anything else worth knowing about the environment?

The memory thing is especially weird.  Is it going in an infinite recursion or something?  Are there lots of git processes being spawned or something?

**Comment by embray** [comment]
Actually, I think I might know the problem.  Are you testing this against astropy-helpers 1.1b1?  It's rather dependent on that.

**Comment by olebole** [comment]
You are right; sorry for that. It was a bit tricky, since it accidentally pulled the stable 1.0.5 version from Debian unstable instead of the 1.1~b1 version from experimental.

**Comment by embray** [comment]
No, I'm sorry. That was easy to miss.
