### ISSUE TITLE
Bayesian blocks gamma_prior() called incorrectly?

### ISSUE THREAD

**Issue by robcross** [astropy/astropy#4252]
```gamma_prior``` is defined as:

    def gamma_prior(self, N, Ntot):
        """
        Basic prior, parametrized by slope gamma.
        See eq. 3 in Scargle (2012)
        """
        if self.gamma == 1:
            return 0
        else:
            return (np.log(1 - self.gamma)
                    - np.log(1 - self.gamma ** (Ntot + 1))
                    + N * np.log(self.gamma))

and it is called in ```fit()``` in the following context:

```
def fit(self, t, x=None, sigma=None):
...
    N = len(t)
    ...
    for R in range(N):
        ...
        A_R = fit_vec - self.prior(R + 1, N)
```

If you look at Scargle's definition (eq. 4, Scargle 2012), astropy ```Ntot``` ~ Scargle's "N" and astropy ```N``` ~ Scargle's N_blocks.

The values being passed into ```N``` and ```Ntot``` are "the number of data points *currently* in the fit" and "the *total* number of data points to be fit".

Looking at Scargle's definitions of these variables, I believe that ```N``` and ```Ntot``` should be "the number of **blocks** currently in this realization of the fit" and "the number of data points *currently* in the fit".

I hope I have explained this correctly. It makes sense to me in that as you add more blocks, the prior probability is decreased, thus incurring a higher penalty as you add more change points. This is tweaked by adjusting gamma.

**Comment by astrofrog** [comment]
cc @jakevdp @astronomeralex

**Comment by jakevdp** [comment]
> Looking at Scargle's definitions of these variables, I believe that N and Ntot should be "the number of blocks currently in this realization of the fit" and "the number of data points currently in the fit".

I think that this is exactly what is implemented in the code. in the line ``self.prior(R + 1, N)``, the ``R + 1`` is the candidate number of blocks being checked, and the ``N`` is the number of points in the dataset.

**Comment by astronomeralex** [comment]
@robcross @jakevdp so, it seems like the code is fine, but the documentation needs to be updated?

**Comment by jakevdp** [comment]
Which part of the documentation do you think needs updating?

**Comment by robcross** [comment]
Hi @jakevdp 

Sorry I had github emails off. 

I think the confusion I have is with scargle's definiation of "cells" and "blocks". I have to get something done first, but I'll take another look in the code and try and explain my concern more clearly. Thanks!

**Comment by robcross** [comment]
@jakevdp 
Hello again! I've been doing some studying and investigations, and I think I've a few major misinterpretations of Scargle's paper in your code.

---

### 1.) The geometrical gamma prior should *always* be used

##### (but not in the way you are currently using it)

All empirical forms of p_0 and ```ncp_prior``` in fact just choose a value of gamma to use. In the first paragraph of page 5, Scargle defines ```ncp_prior``` as the *constant log gamma*, though later in the Figure 1 caption he notes that ```ncp_prior``` is -ln(gamma). Now when I and Scargle talk about ```ncp_prior```, I am also just referring to gamma. The fact that he defines it as a *constant* brings me to my next point. 

If you note in Scargle's code, he simply adds the fitness function of the previous blocks + the current block fitness - ```ncp_prior```. Once you choose a gamma or ```ncp_prior```, this is all you have to do!

Ignoring the normalization constant, Equation 4 shows that the prior is just gamma^{N_blocks}. As long as gamma is less than 1, this prior enforces that as you add more blocks, or change points into the model, you are **penalizing** the fitness of that model, which prevents overfitting.

In Scargle's code, this is just implemented by subtracting this ```ncp_prior```.

The log of the prior is just N_{blocks} ln(gamma) or -N_{blocks} ```ncp_prior```.

So let's think about it this way. The ```best``` variable represents the fitness of all the blocks in the model before adding the newest one on the end.

So for K blocks, ```best``` = SUM_i=0^k(Fit_i) + K ln(gamma).

When you add another block , you can just add the fitness of the new block and subtract an ```ncp_prior``` so that the new fitness = SUM_i=0^k(Fit_i) + Fit_new + (K+1) ln(gamma), of which the max values get saved into ```best``` for a new iteration.

---

### 2) The prior should be constant

The normalization of the prior function should be constant throughout the calculation. It should be a function that only depends on N_blocks.

This brings me back to my post when I opened this issue. You are plugging in essential the current location of the algorithm into variable "N", which should represent the total number of data points in the set. "N" should be a constant in the calculation.

After examining the code and equations for a while, I guessed that the effects could possibly be seen as a location dependent sensitivity in the data set. Since N -> location in your code, a lower value of N will "boost" the prior for the early points (Eq 4).

I ran a quick test, by setting a sensitive value of p_0 and looked at the locations of bin edges in signal free Gaussian noise:

![http://i.imgur.com/ktT7P84.png](http://i.imgur.com/ktT7P84.png)

It turns out that your code is VERY sensitive near the left edge (log scale)!

If you make a modification to the fitness functions to take an ```ncp_prior``` value instead of ```p0``` or ```gamma```, and change 

```
    A_R = fit_vec - self.prior(R + 1, N)
    # to
    A_R = fit_vec - self.ncp_prior
```

Then using a reasonable value of ncp_prior (3.0),
![http://i.imgur.com/JTld84p.png](http://i.imgur.com/JTld84p.png)

You get a uniform distribution of edges as expected.

### 3.) All empirical forms for ncp_prior and p_0 are for **very specific cases**

```ncp_prior = 4 - np.log(73.53 * self.p0 * (N ** -0.478))``` is noted at the conclusion of the "Event Data" section 3.1. I believe that in this case, that equation is only valid for the 1 or 0 Bernoulli type data.

In the last paragraph of Section 3.2, for the Poisson type binned data, he determines the value of ncp_prior to use for a specific p_0 given N data points somehow by looking at the contour plot in Figure 5. I have no idea what this contour plot represents.

in the last paragraph of section 3.3, he describes how to find the appropriate value of ```ncp_prior``` given specifically p_0 = 0.05 for the Gaussian type measures. This is done by finding the intersections in Fig 6 (top) and fitting to a line in Fig 6 (bottom). The inline equation in this last paragraph is only value for p0 = 0.05!

Nowhere in Sections 3.2 and 3.3 is Eq 21 referenced. I believe it is incorrect to use Eq 21 for those measures.

If you want to relate ```ncp_prior``` to a p_0, it seems that unless you are using event data, you must run trials to calibrate it. If your data sizes vary, you need to calibrate as a function of N.

I am still thinking about this 3rd point.

**Comment by jakevdp** [comment]
OK – to be honest, it's been 3 years since I've looked into this paper deeply, and I no longer remember enough about the algorithm to evaluate the points you're making. If you think the code should be changed, then a pull request is probably appropriate.

**Comment by robcross** [comment]
Sure, I'm not sure what to do with the p0 equations, and I'm struggling with github forking, but I'll try to hack away at it a bit.

**Comment by jakevdp** [comment]
One thing though: your point about "the prior should be constant" doesn't make sense to me. What's the use of a prior if it doesn't somehow penalize your likelihood? A constant prior is one particular choice, but in general the prior will (and should!) change with respect to the parameter you're fitting, and thus should affect the fit (that is, the results should look like your first plot under point 2).

**Comment by jakevdp** [comment]
As the code is currently written, you can use a flat prior if you wish. If you make the change you propose above, then you've made it *impossible* for the user to set anything but a flat prior! I don't think this is the correct way to go.

**Comment by jakevdp** [comment]
Maybe @jscargle could comment

**Comment by robcross** [comment]
I didn't word that right, I meant that the normalization of the prior should be constant. The gamma prior is a function of N_blocks. ```ncp_prior``` on the other hand is constant. Every time you add a block, or change point, you subtract ```ncp_prior``` which is basically the difference between the prior for a model with K blocks and the prior for a model with K + 1 blocks. 

For a given data set, the "N" variable is constant, which in your implementation of the p0 prior, is changing throughout a data set.

---

If I make a change, I would enforce this geometrical prior, allowing the user to change ncp_prior or gamma. I need to run a few tests to make sure that p0 for event data acts as expected. For other types of data, I don't know how to approach p0 right now.

**Comment by jakevdp** [comment]
OK – I think I see what you're saying now. Yes, a PR with specific changes would be helpful.

**Comment by robcross** [comment]
Ok, I'll learn some git(hub) this weekend and play around with it. Git's forks, branches and pulls are a little overwhelming coming from SVN :sweat_smile:

**Comment by jakevdp** [comment]
Just to be clear, your main point is that the dependence on number of blocks comes from iteratively adding a constant to the log-likelihood within the algorithm, and so the explicit dependence on ``N_blocks`` doesn't need to be put in there. Is that correct?

Also, I predict that once you tackle the initial learning curve of git, you'll wonder how you ever worked with SVN :smile:

**Comment by robcross** [comment]
Yes, that's correct!

**Comment by jscargle** [comment]
Hi … I am not sure I understand all of this exchange, but I
am sure Jake has said it right.  I hope all of this is explained
in our paper
http://arxiv.org/abs/1207.5578

I think of the parameter ncp_prior as mediating the trade-off
of false positive vs. false negative errors.  It is analogous to
a smoothing parameter -- but of course it does not smooth
block edges or anything else, but can change the number
of blocks.  In good signal-to-noise the blocks (number of
them and their locations) is nearly independent of ncp_prior
over a broad range.  Not so in low S/N.

The choice of the geometric prior is a bit of a kludge … part
of the motivation for it is that it is so simply implanted in
the algorithm.  But don't tell anyone this.  :-)

Cheers, Jeff

Jeffrey D. Scargle
Space Science Division
Mail Stop 245-3
NASA Ames Research Center
Moffett Field, CA 94035-0001

Phone: 650 604 6330
Cell:  415 385 4297
Fax: 650 604 6779
________________________________

**Comment by crawfordsm** [comment]
Thanks everyone for commenting on this.   @robcross if you need some help with the PR or git, I'm happy to help and answer any questions.

**Comment by robcross** [comment]
Hi @jakevdp @crawfordsm 

I think I've managed to fork astropy and commit some changes to it. Can you take a look here:
https://github.com/robcross/astropy/commits/4252

I think this fixes the major issues. Is the warning in my second commit the appropriate way to deal with that?

Also I have not changed any documentation, I will do that tomorrow morning.

I think I'm doing the github thing neat, I see the pull request button on my fork, I'll do that when I fix the documentation. Neat! :octocat: 

Thanks!
