### ISSUE TITLE
v1.0.5 isn't available in astropy-ci-extras?

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#4260]
When I checked whether we can include py3.5 in the photutils testing matrix, it fails when testing against the latest stable astropy. 
It turns out that it's 1.0.4 that comes up as the latest stable but not 1.0.5 that contains the changes for py3.5 support.

I'm opening an issue as am not sure whether new versions should come up available in the conda channel automatically or it needs manual work.

cc @mwcraig @embray 

```
conda install -c astropy-ci-extras --yes numpy=1.9 astropy
```

**Comment by mwcraig** [comment]
@bsipocz -- the problem at the moment is that versions of astropy that continuum doesn't build need to be built more or less manually. I think I'll *finally* have time to burn through a backlog of build items, including this, over the weekend.

**Comment by embray** [comment]
I guess at some point we'll want to automate that somehow.

**Comment by bsipocz** [comment]
@mwcraig - OK, that what I feared. Anyway, don't worry about 1.0.5 anymore as 1.0.6 is out :) However it would be great to have that with the older numpys.

**Comment by mwcraig** [comment]
Hopefully the automating will happen this weekend...need to do a bit of refactor on the conda affiliated builder to decouple the build machinery from the list of things to build, then it will be much easier to automate.

Anyone interested in learning those ropes is welcome to join in ;)

**Comment by eteq** [comment]
1.0.5 is now in (has been for a while, but I just re-noticed this issue now), so I'm closing this.

**Comment by bsipocz** [comment]
Thanks @eteq for the heads up and @mwcraig for doing the updates.

@mwcraig - Some package combinations are unavailable in conda. Is there a repo for ``astropy-ci-extras`` where these can be reported (e.g. numpy 1.10 with python 3.3&2.6)?
