### ISSUE TITLE
Table.as_array() doesn't return a masked_array any more

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#4273]
I couldn't find any trace that this is an intended change, but even it would be I think it's a serious API break and should raise at least a warning (it broke my script and was staring at it for a few hours to figure why I was getting nonsense values).

in 1.0.6:

```
In [32]: print(type(scat))
<class 'astropy.table.table.Table'>

In [33]: scat[cols].as_array()
Out[33]: 
masked_array(data = [(10.728110900623053, nan, nan, nan)
 (12.56170619192868, 15.443797400477882, nan, nan)
 (11.385436027970288, nan, 10.944840709433722, 9.549117086288092) ...,
 (nan, 12.895172023642079, nan, nan)
 (12.71592921914393, 9.422908710637309, nan, 12.225983027418101)
 (10.98627937639113, 13.107785928715826, nan, 15.187083888947438)],
             mask = [(False, False, False, False) (False, False, False, False)
 (False, False, False, False) ..., (False, False, False, False)
 (False, False, False, False) (False, False, False, False)],
       fill_value = (1e+20, 1e+20, 1e+20, 1e+20),
            dtype = [('distance_mod_1', '>f8'), ('distance_mod_2', '>f8'), ('distance_mod_3', '>f8'), ('distance_mod_4', '>f8')])

In [34]: astropy.__version__
Out[34]: u'1.0.6'

In [35]: np.__version__
Out[35]: '1.10.1'
```

in v1.1.x (same as 1.1 beta I believe):

```
In [20]:

print(astropy.__version__)

print(np.__version__)

print(type(scat))

scat[cols].as_array()

1.1.dev13868
1.10.1
<class 'astropy.table.table.Table'>

Out[20]:

array([(nan, nan, nan, 11.697260593852018),
       (nan, nan, nan, 12.368602539041746),
       (nan, nan, 10.77703884802981, nan), ..., (nan, nan, nan, nan),
       (nan, nan, nan, nan), (nan, nan, nan, nan)], 
      dtype=[('distance_mod_1', '<f8'), ('distance_mod_2', '<f8'), ('distance_mod_3', '<f8'), ('distance_mod_4', '<f8')])
```

**Comment by bsipocz** [comment]
Looking at it a bit more, it seems like that my real issue is the that the byte order is different. Using ``keep_byteorder=True`` my results are not messed up any more...

**Comment by taldcroft** [comment]
@bsipocz - the byteorder issue is an API change that is intended to reduce problems that were found converting to pandas and/or writing to HDF5.  What is your use case where changing to native byteorder breaks things?

I don't understand your original example where the masking gets dropped.  Is that something you can reproduce?

**Comment by taldcroft** [comment]
@bsipocz - let me know if you have a table that is masked where `.as_array()` produces a non-masked output.  E.g. if `scat.masked == True` but `.as_array()` is not a `masked_array` then I'll be very worried.

**Comment by bsipocz** [comment]
I couldn't reproduce the problem when I did a quick recheck, and it seems that the two examples didn't have the same input. However I wasn't able properly dig deeper then and am away from the datasets in the last two days. Anyway I'll try to figure out what did I do differently and hopefully see everything worked as expected and I only generated noise regarding the masking/nonmasking.

**Comment by embray** [comment]
I changed this method in #4080, but I don't see clearly how the change would affect masked data.  Though I don't have a deep understanding of masked arrays either.

**Comment by bsipocz** [comment]
It looks like I might have messed up the example to begin with here as no one else run into the same issue in the past couple of years. Closing for now.
