### ISSUE TITLE
NaN reading from FITS files

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#4278]
@embray I've encountered some files that apparently contain 'signalling nans'.  Is it possible to include an option to replace such NaNs with "normal" numpy nans upon reading/writing?  I'm trying to avoid warnings of the sort "invalid value encountered..." that show up when performing *any* operation with signalling nans in numpy.  

Related SO question: http://stackoverflow.com/questions/33369772/numpy-distinguish-convert-between-different-types-of-nan/33371882#33371882

**Comment by embray** [comment]
No, I don't think this would really be the place for something like that.  FITS itself doesn't do anything different with quiet or signaling NaNs.  I think this is more of a Numpy issue.

**Comment by keflavich** [comment]
But `io.fits` is reading the data into numpy arrays and is therefore causing the noise.  Numpy makes it fairly difficult to distinguish signalling and non-signalling NaNs and quite difficult to create arrays with signalling NaNs unless they are read that way from disk.  This feels more like an io problem to me, or at least something that could be most conveniently handled at read time.  

Does the FITS standard say anything about types of NaN?  I'm not sure if it does; if not, I guess technically these are allowed FITS data.

**Comment by embray** [comment]
It does not--it's just returning the data that's in the file, represented accurately.  It's not something that can easily be handled at read time either without looping over all the data.  The fact that this is causing problems at all is an issue particular to Numpy.
