### ISSUE TITLE
Angstrom definition and numerical precision

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#4287]
Is there a reason why `u.angstrom` is defined as `0.1 * u.nm` and not `1e-10 * u.m` ? 
With the current definition I get this:
```
In [2]: (1*u.angstrom).to(u.m).value
Out[2]: 1.0000000000000002e-10

In [3]: (4.75e-7*u.m).to(u.angstrom).value
Out[3]: 4749.999999999999
```

**Comment by saimn** [comment]
I don't know if the way to define the unit is the cause of the loss of precision, and interestingly using a definition of `1e-1 * u.nm` gives the same error, but for context the origin of this issue is that `astropy.wcs` / `wcslib` converts the `cunit` to meters, and with this precision issue it is not possible to get the original values in angstroms.

**Comment by pllim** [comment]
There is no reason not to update the definition if this fixes the permission issue.

**Comment by mhvk** [comment]
The underlying problem is that negative powers of 10 like `0.1` or `1e-10` cannot be represented exactly as floats. In the end, it is a choice about what is more important. E.g., suppose we redefined, then:
```
angstrom = u.Unit(1.e-10*u.m)
(1*angstrom).to(u.m).value
# 1e-10  -> looks better
(1*angstrom).to(u.nm).value
# 0.09999999999999999  -:> but now this one is worse
```
Given this, my tendency would not be to change the definition; it might lead to very slight changes in results that trip someone up while the benefits seem minimal. Instead, it would seem to make more sense to prevent `wcslib` from converting units unless the user explicitly asks for it (but I write this having *no* idea why it is converting -- there may well be a good reason...).

**Comment by pllim** [comment]
@mhvk, can we say that our users are more interested in accuracy at, say, 4000 Angstrom, rather than at, say 1 Angstrom? Or is this not true?

**Comment by mhvk** [comment]
@pllim - I'm not sure it matters, but, yes, X-ray astronomers use angstroms in the 10s range. Anyway, also at 4000 conversion to `nm` is bad if one defines angstrom as `1e-10 m`:
```
In [3]: (4000*u.angstrom).to(u.nm).value
Out[3]: 400.0

In [4]: (4000*angstrom).to(u.nm).value
Out[4]: 399.99999999999994
```
Well... actually, in this case it seems that the proposed new angstrom does not roundtrip better to meters than the existing one, so perhaps another reason not to bother redefining it:
```
In [7]: (4000*angstrom).to(u.m).to(angstrom).value
Out[7]: 4000.0000000000005

In [8]: (4000*u.angstrom).to(u.m).to(u.angstrom).value
Out[8]: 4000.0
```

**Comment by saimn** [comment]
> Instead, it would seem to make more sense to prevent wcslib from converting units unless the user explicitly asks for it (but I write this having no idea why it is converting -- there may well be a good reason...).

Agree but the only issue I found about this (#3658) suggest that it is not possible: it is about the conversion of arcsec to degrees but I guess there is the same thing for wavelength (the conversion is done by `wcs.set()`, so inside wcslib).

> Well... actually, in this case it seems that the proposed new angstrom does not roundtrip better to meters than the existing one, so perhaps another reason not to bother redefining it:

Yes, you're right, I will look for another way to fix my issue, thanks for your answers !
