### ISSUE TITLE
Equivalents for IDL's biweight_mean, resistant_mean, and robust_sigma?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#4294]
I saw IDL's ``biweight_mean``, ``resistant_mean``, and ``robust_sigma`` routines mentioned in #621 but it did not really tell me if these were actually implemented or not under a different name.

**Comment by crawfordsm** [comment]
biweight_mean is biweight_location in astropy.stats.   I think  robust_sigma is biweight_midvariance (astropy names are closer to what they are in the original paper).   I don't think resistant_mean is directly  implemented but is similar to what can be done in sigma_clip.

**Comment by pllim** [comment]
Great! I'll check those out. If they work as expected, I'll close this. Thanks!

**Comment by pllim** [comment]
Minor correction: `sigma_clip` should be `sigma_clipped_stats`

Results are not exactly the same, but around the same ballpark. Thanks!
