### ISSUE TITLE
Docs clarification – --set-upstream

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy#4296]
At #dotastronomy, @skendrew, @astropixie and I noticed that the [docs for contributing to astropy](https://github.com/astropy/astropy/blob/master/docs/development/workflow/development_workflow.rst#connect-the-branch-to-github) there's a suggestion to use `--set-upstream` that has some of us confused. Wouldn't

```
git push origin <branchname>
```

suffice? @astrofrog seems to think so also. Follow the link for the exact context. 

cc @eteq

**Comment by astrofrog** [comment]
cc @mwcraig

**Comment by saimn** [comment]
You can push a new branch with `git push origin <branchname>` but then your local branch is not tracking the remote one, so you need to always use  `git push/pull origin <branchname>`.
With `--set-upstream` your local branch tracks the remote one so you can use  `git push/pull` without the remote and branch names.

**Comment by bsipocz** [comment]
@saimn - Actually you don't need the branchname after the first push. At least I always push without it after having a remote branch:
``git push bsipocz``

Though I always name the branch when doing a force push, just to be sure I'm not messing up other branches accidentally.

**Comment by bsipocz** [comment]
@bmorris3 - For promoting good practice you may want not to use ``origin`` ever, but rename it to the username :)

**Comment by bsipocz** [comment]
@bmorris3 - If anyone is up to updating the page at this section at it may be outdated. At least ``python3 setup.py develop`` seemed to work for multiple people at EuroScipy, but it was never actually double checked.


```
Ideally you should set up a python virtual environment just for this fix; instructions for doing to are at :ref:`virtual_envs`. Doing so ensures you will not corrupt your main astropy install and makes it very easy to recover from mistakes.

Once you have activated that environment you need to install the version of Astropy you are working on. Do that with:

python setup.py develop  # typically python 2.x, not python 3

or:

python3 setup.py install # python 3...
# ...though python3 may be called python3.3 or just python,
# depending on your system.

If you are using python 3 you will need to re-install after making changes to the Astropy source code. Re-installing goes much faster than the initial install because it typically does not require new compilation.
```

**Comment by saimn** [comment]
> @saimn - Actually you don't need the branchname after the first push.

It depends on the `push.default` setting, but with the default value it doesn't work without the branch name.

> At least python3 setup.py develop seemed to work for multiple people at EuroScipy

This section about python2/python3 install/develop is confusing: install and develop both work with python 2 and 3.

**Comment by bsipocz** [comment]
@saimn -Maybe, I never changed the defaults and it still works.

**Comment by mwcraig** [comment]
It would be great to get some pull requests cleaning up some of these issues :).

`--set-upstream` was there for the reasons @saimn indicated, to avoid having to type the name of the remote/branch, especially when pulling in updates from upstream. I don't have any objection to either clarifying it or removing it.

The python 2/3 part is badly out of date; I think it was written before the switch to using `six`. 

In general I think it would be useful to point new users to using environments as quickly as possible; I've used conda environments rather than virtualenv, but in principle either should work.
