### ISSUE TITLE
quantity_support and unit formatter

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#4297]
Quantity support for matplotlib was introduced in #3981, but in the general case it uses the unicode format: https://github.com/astropy/astropy/blob/master/astropy/visualization/units.py#L72
Which gives something ugly with complex units:
![unit](https://cloud.githubusercontent.com/assets/311639/10969823/f1d22df6-83ca-11e5-9548-6192d694ab3c.png)
If I change this line to use the `latex_inline` formatter this is much better:
![unit2](https://cloud.githubusercontent.com/assets/311639/10969765/9c21e7ac-83ca-11e5-9838-c137d691f919.png) ![unit3](https://cloud.githubusercontent.com/assets/311639/10969974/d785e568-83cb-11e5-9f09-1a8076c04edc.png)

It also works with the `latex` formatter, so maybe this should be an option of `quantity_support` ? Should it still be `unicode` by default ? 
*edit*: added image with the latex format

**Comment by embray** [comment]
This sounds like a font issue on your end, but I'm not terribly well versed in those details.

**Comment by embray** [comment]
Actually, I take it back, sorry.  I agree latex_inline would be better as a default.

**Comment by saimn** [comment]
@embray :  See #4313. I guess that using latex is a safer default, but I don't know, maybe unicode could work well in most cases. The main point is that it should be possible to modify the format I think.

**Comment by saimn** [comment]
Closed with #4313
