### ISSUE TITLE
Doppler shift a spectrum with a given radial velocity

### ISSUE THREAD

**Issue by DanielAndreasen** [astropy/astropy#4303]
Hi all,

I have for a long time missed this functionality in `astropy`: to shift a spectrum with a given radial velocity (RV).
The procedure is quite easy:
1. Multiply the wavelength with `(1+rv/c)`.
2. Interpolate the flux to the new wavelength vector.

As for now, I always use [`PyAstronomy`](http://www.hs.uni-hamburg.de/DE/Ins/Per/Czesla/PyA/PyA/index.html) for this. This [function](http://www.hs.uni-hamburg.de/DE/Ins/Per/Czesla/PyA/PyA/pyaslDoc/aslDoc/dopplerShift.html) does the RV shift. I would like to write this function for `astropy` (if it does not exists), but were should it be? I am familiar with pull requests and the github workflow.

Cheers,
Daniel

**Comment by crawfordsm** [comment]
One possible place would be the ['specutils'](https://github.com/astropy/specutils) affiliated package.   This does have a different release cycle than astropy but some of it may be eventually incorporated into astropy.   cc: @wkerzendorf @eteq

**Comment by pllim** [comment]
Some thoughts need to go into units handling. For example, what if wavelengths are given in Hz instead of Angstrom? What if flux is given in ABMAG?

As to where (if not `specutils` as mentioned above)...

1. There is already a `Redshift` model in `astropy.modeling.functional_models`, which is kind of related to this. However, `astropy.modeling` does not support `Quantity` yet.
2. Currently, there are also blackbody functions under `astropy.analytic_functions`. They have `Quantity` support with the intention of being absorbed into `modeling` in the future. So, this could a another possible place too.

**Comment by DanielAndreasen** [comment]
I never even considered that people are using other units than length for a wavelength. Good catch! I'm also not an expert on `Quantity` but it could be a nice feature.

**Comment by andycasey** [comment]
Just a note: Step 2 (interpolation the flux onto the new wavelength vector) is not really necessary and will introduce correlated noise, so it might be worth considering introducing this as an option in the function.

**Comment by wkerzendorf** [comment]
@andycasey depends on if it is observed or not - but yes, one should generally not mess with measured data. 

So these are two issues: How to change the WCS of a spectrum and how to interpolate the flux from one WCS onto another WCS. Both steps are trivial to do if you are writing it for a specific case - making it general and right for all cases not so much. Doing Step 1 is doable with compound models - the driving force behind specwcs and GWCS. For Step 2 - I think the right thing to do is to use is the reproject package. 

Here a quick domain specific solution for now:

```python
from numpy import interp1d

def doppler_shift(spectrum, velocity):
    doppler_factor = np.sqrt((1+velocity/const.c)/(1 - velocity/const.c))
    new_wavelength = spectrum.wavelength * doppler_factor
    new_flux = interp1d(new_wavelength, spectrum.wavelength, spectrum.flux)
    return Spectrum1d.from_array(new_wavelength, new_flux)
```

**Comment by crawfordsm** [comment]
I think there would also be a motivation to also create a new section for generalized astronomy tools that do not fit into an of the existing sections currently available in `astropy`.    This might then need some comment from @astrofrog and @eteq, but there are a lot of little miscellaneous tools that would be useful to have in astropy and might not have a good or obvious home at the moment.   

On the other hand, if you wanted to submit something right away, I think to `specutils` would be the quickest and good place for it.

**Comment by pllim** [comment]
`astropy.astrolib`? :stuck_out_tongue_winking_eye:

**Comment by mhvk** [comment]
@crawfordsm - the problem with large collections of small utilities is that soon the effort required to discover that what one needs exists as a small utility becomes larger than the effort to just write the few lines yourself. I think this is already the case with some of the things we have in `stats`, and believe that for `astropy` proper it is best to concentrate on creating a really solid base, of things that are hard to get right (like coordinates, times, a flexible modelling system, world-coordinate systems, flexible I/O).

But in the things hard to get right does also belong a good way to present spectra, and this certainly includes doppler shifting them and interpolating on new grids when required. I think it would be wonderful to have good support for that in `specutils`, hopefully in a way that uses `astropy.models`.

**Comment by embray** [comment]
I agree with everything @mhvk wrote.

Though there are some minor things that have been requested enough times that it might be worth putting together an astropy.astroutils package or something for routines like that.  Although we also need to do a better job of advertising what capabilities are in affiliated packages, or for that matter what existing affiliated packages are good targets for more application-specific utilities.
