### ISSUE TITLE
i get this type of error while install astropy..please some one help me

### ISSUE THREAD

**Issue by RajuPilani** [astropy/astropy#4316]
/Desktop/GSOC/astropy/astropy $ python setup.py install

running install
running bdist_egg
running egg_info
writing requirements to astropy.egg-info/requires.txt
writing astropy.egg-info/PKG-INFO
writing top-level names to astropy.egg-info/top_level.txt
writing dependency_links to astropy.egg-info/dependency_links.txt
writing entry points to astropy.egg-info/entry_points.txt
reading manifest file 'astropy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'astropy/utils/misc/data/.hidden_file.txt'
warning: no files found matching '*' under directory 'scripts'
warning: no files found matching '*' under directory 'astropy/sphinx/themes'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'build'
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'astropy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running pre_hook from astropy.modeling.setup_package for build_py command
running pre_hook from astropy._erfa.setup_package for build_py command
running build_ext
running pre_hook from astropy.modeling.setup_package for build_ext command
running pre_hook from astropy._erfa.setup_package for build_ext command
error: [Errno 2] Could not find C/C++ file astropy/table/_np_utils.(c/cpp) for Cython file astropy/table/_np_utils.pyx when building extension astropy.table._np_utils. Cython must be installed to build from a git checkout.: 'astropy/table/_np_utils.c'

**Comment by saimn** [comment]
Which version are you trying to install ? For a development version (which seems to be the case) you need Cython and Jinja2 : http://astropy.readthedocs.org/en/latest/install.html#building-from-source

**Comment by RajuPilani** [comment]
thanks @saimn

**Comment by RajuPilani** [comment]
which python version is good for contributing in astropy.

**Comment by saimn** [comment]
Python 3 is probably the best but you can use the version you prefer. Also have a look at http://astropy.readthedocs.org/en/latest/#developer-documentation to get started.

**Comment by embray** [comment]
Over in #3229 I've been working on making Jinja2 and Cython available via setup_requires when one tries to build from a source checkout (some recent changes to astropy-helpers should help enable this too).  But I haven't quite finished the work yet.  Regardless, one should install them when doing Astropy development.
