### ISSUE TITLE
Add dev docs explaining PLY integration

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#4318]
As mentioned in #4300, there are some pieces of `units`  and `coordinates` that use PLY (and lex/yacc) to parse various strings.  However, there is no developer documentation describing how this works and how it should be maintained.  It would be valuable if @mdboom (or perhaps @embray ?) could write a short developer docs page describing how these fit together, so that other contributors can understand how they might be able to help maintain or expand these pieces.

**Comment by embray** [comment]
I think the documentation for PLY itself would be a start...
These modules are just using PLY in a way that is not unusual.

**Comment by eteq** [comment]
@embray - the point is *why* they are used and specifically *where*, and how/when to invoke it. Even if it's standard, the point is that most people who may need to fiddle with these things don't have the time/inclination to master PLY so there should be some information about why they should care and how to get started learning what they need to o know.

**Comment by AMAN3003** [comment]
@eteq could I work on this

**Comment by AMAN3003** [comment]
@eteq @embray please guide me what should i do to write the dev ply docs

**Comment by astrofrog** [comment]
@AMAN3003 - this issue is labelled as ``package-expert``, which means that it requires a lot of knowledge about how we've set up the package, etc. So this issue is more intended as an issue for a core developer. I would suggest sticking to ``package-novice`` issues for now while you familiarize yourself with the project.

**Comment by AMAN3003** [comment]
@astrofrog thank you for you advice.But could you give me a favour ..please include me in development team by assigning little task .I would do me best .I want to develop.little function of the project will also be a golden chance for me

**Comment by eteq** [comment]
Closed by #7174
