### ISSUE TITLE
Fits file handle not closed

### ISSUE THREAD

**Issue by cosmo-ethz** [astropy/astropy#4327]
I'm seeing different behavior when dealing with fits files under OSX and Windows7. Under Windows I get the following error when I try to delete the file after I have opened, read-out, closed it:

`WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:/data/Spec1_20151119_132633.fit'`

This can be reproduced using the following lines:

```python
from astropy.io import fits
import os

hdu_list = fits.open('C:/data/Spec1_20151119_132633.fit', ext=0)
table=hdu_list[1]
frequencies = table.data["FREQUENCY"][0]
hdu_list.close()

os.remove(fits_path)
```
Doing the same thing under OSX 10.9.5 works like a charm. Am I doing something obviously wrong?

Python: 2.7.5
Astropy: 1.0.5

**Comment by embray** [comment]
See the warning in this section of the docs: http://docs.astropy.org/en/stable/io/fits/index.html#working-with-large-files

Admittedly the location of the warning is not obviously connected to your issue but it's the same thing.  You still have a file handle open when you read the data by default.

**Comment by cosmo-ethz** [comment]
@embray  thanks for the reply. I indeed didn't read this section, mainly because I'm working with tiny files and I was not aware that the default behavior is setting memmap to True. Anyway, when explicitly setting `memmap=False` astropy seems to behave the same on both OS.

**Comment by embray** [comment]
@cosmo-ethz Yeah it could have been easy to miss.  Maybe I'll put that warning somewhere more prominent because it's a common misunderstanding.
