### ISSUE TITLE
1.1b1: Sourceless files astropy/table/data/jquery*.js

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#4330]
We had this already (#1992); however the non-minimized source files got lost on commit 87b7239.

Similarly it would be nice to have the source of the [`jquery.dataTables.min.css`](https://github.com/astropy/astropy/blob/master/astropy/extern/css/jquery.dataTables.min.css) file as well.

**Comment by embray** [comment]
Pinging @saimn as author of #4174

**Comment by eteq** [comment]
I think this was just an oversight in #4174 - @saimn probably thought it was better to have the minified versions as that's how `js` code is often distributed for web consumption.  Would be pretty trivial to just switch back to the non-minified versions.

@olebole -  question about this: in #1992 you said there was no debian dataTables but it was coming.  Has this changed?  If yes, would it be acceptable to keep the minified versions in `astropy/extern` (they load faster in browsers and take up less space in the source repo), but have the debian distribution just excise those versions and use the debian-packaged version instead?  Or would that be a lot more work for you?

**Comment by saimn** [comment]
I added only the minified files because it is what users should use when they load a page (it saves more than 500kb), and these files have a mention about the license.
I am happy to add the non-minified versions if it helps, but anyway you will remove it in the debian package in favour of the jquery and datatables package (it [seems](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=719601#85) to be available) ?
For the css I can replace it with the non-minified version as the gain is really small (only 1kb, I probably took the minified one without checking, sorry).

**Comment by olebole** [comment]
The point for me is that the "source" package shall not contain sourceless files. For the installation, the pre-packaged jquery files are used, so I don't need neither the source nor the minified version.
However, *if* there are minified files, the original files are needed as well, so when you provide only the minified version, I have either to remove them (and create a patched tar file), or to add the source files manually -- which may be difficult if I don't know the exact version, or if this specific version is not available anymore. Other Open Source distributions (like Fedora -- @sergiopasra could you comment here?) may have similar requirements.
As long as it does not blow up the size of astropy (gzipped they are ~200kB, compared to ~8MB astropy tar.gz source), I would ask to keep the non-minified version.

**Comment by saimn** [comment]
Ok thanks for @olebole for the explanations, it's fine for me.

**Comment by sergiopasra** [comment]
@olebole Fedora has similar requirements, minified JS has to be build during package construction, with the same minifier used by upstream (if it's possible). This requires the original javascript code.

**Comment by eteq** [comment]
Closed by #4334
