### ISSUE TITLE
Misc FITS documentation bugs

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4332]
Quoting from an e-mail to the mailing list:

I would like to suggest a fix in the documentation under astropy.io.fits, specifically when describing the Column module:

http://docs.astropy.org/en/stable/io/fits/api/tables.html#column

which states that format is not optional but then the hyperlink takes you here:

https://docs.python.org/2/library/functions.html#format

when in reality it should take you here:

http://docs.astropy.org/en/stable/io/fits/usage/table.html#creating-a-fits-table

and also here:

http://docs.astropy.org/en/stable/io/fits/usage/unfamiliar.html#variable-length-array-tables

since the format keyword corresponds to options listed in the latter two links.

In addition, in the Variable Length Array Tables documentation, it doesn't state at all what r=0,1,absent means. In what instance would I use any of these values?

**Comment by astroferreira** [comment]
As this is a very straightforward fix, maybe I could solve this as my first contribution to astropy. In the search for the meaning of r in the TFORM use, I found this FITSIO documentation page

https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/node10.html

stating that r is the vector length, in which the default for FITSIO case is r =1. My guess is that r=0,1 is only valid for binary tables. You can see in the section "Creating a Variable Length Array Table" that the code creates a column with "2I" TFORM keyword for a two dimensional integer column,  meaning that r = 2, contradicting the documentation regarding only r=0,1, absent values.

http://docs.astropy.org/en/stable/io/fits/usage/unfamiliar.html#creating-a-variable-length-array-table

In an attempt to fix this issue, I added links in the Column class documentation to the proper sections and changed the information regarding r in the Variable Length Array Tables documentation.

I don't know if this kind of reference (explicit links) meets astropy's documentation standards, I couldn't find anything regarding this in the development documentation so I used the general information in reST.

**Comment by astroferreira** [comment]
@embray I realized just now that I made a reference to this issue in each commit. Sorry about that.

**Comment by embray** [comment]
@astroferreira The primary reference for all things FITS should be the FITS Standard itself (latest version, 2008): http://fits.gsfc.nasa.gov/fits_standard.html

For variable length arrays the "repeat count" portion of the TFORM keywords is basically not applicable (I don't agree that it should be r=2, because the data represented can have different lengths in each row--the use of two integers to represent the position and size of the data is an artifact of this format).  r=0 is only used for an empty column and can technically appear with any data type, but is rare.

**Comment by astroferreira** [comment]
Thank you very much @embray for the right reference and for all suggestions
in the PR. Indeed, the FITS Standard is very clear about it and I couldn't
agree more about my interpretation mistake. So, in the code following the
discussion about creating a variable length array, wouldn't it be better to
just omit the repeat count from the format argument as it is typically
absent? I ask this because as I'm already editing this section of the
documentation, I could incorporate more fixes in the PR.



2015-12-09 8:47 GMT-08:00 Erik Bray <notifications@github.com>:

> @astroferreira <https://github.com/astroferreira> The primary reference
> for all things FITS should be the FITS Standard itself (latest version,
> 2008): http://fits.gsfc.nasa.gov/fits_standard.html
>
> For variable length arrays the "repeat count" portion of the TFORM
> keywords is basically not applicable (I don't agree that it should be r=2,
> because the data represented can have different lengths in each row--the
> use of two integers to represent the position and size of the data is an
> artifact of this format). r=0 is only used for an empty column and can
> technically appear with any data type, but is rare.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astropy/astropy/issues/4332#issuecomment-163320302>.
>



-- 
Leonardo Ferreira
Graduate Student of Extragalactic Astrophysics
Universidade Federal do Rio Grande
Rio Grande - Brazil

**Comment by embray** [comment]
I wouldn't make a specific recommendation.  Over in your PR I added the suggested text that "it is typically absent".  You could also say "it is typically omitted" if you want to use a more active verb, since that text is about creating variable length array columns.

**Comment by saimn** [comment]
Was fixed by https://github.com/astropy/astropy/commit/cf81712cbacae2b0e88191734584657e4718a4b1 or https://github.com/astropy/astropy/commit/2fceb68a42cfc6d71541ecddaeab38a81ccd5d56 (not sure how this was merged but the fix is there).
