### ISSUE TITLE
Using an ascii reader object to read a table raises an exception, but using ascii.read on the same table doesn't

### ISSUE THREAD

**Issue by waltervrossem** [astropy/astropy#4335]
astropy 1.0.3
numpy 1.9.2
python 2.7.10

As the title states, using an ascii.get_reader object to read a table raises an exception, but reading the same table using ascii.read doesn't.

Using this data http://cdsarc.u-strasbg.fr/viz-bin/Cat?J/ApJS/207/10

The following code runs without an exception, but I also need the column descriptions in the ReadMe file. 
```
table=ascii.read('table2.dat', format='cds', readme='ReadMe')
```
When running the following code:

```
reader = ascii.get_reader(ascii.Cds, readme=readme)
table = reader.read("table2.dat")
```
The following exception is raised.
```
<ipython-input-52-20216f3215db> in <module>()
      1 reader = ascii.get_reader(ascii.Cds, readme=readme)
----> 2 t = reader.read('table2.dat')

C:\Python27\lib\site-packages\astropy\io\ascii\cds.pyc in read(self, table)
    319                     return table
    320         else:
--> 321             return super(Cds, self).read(table)

C:\Python27\lib\site-packages\astropy\io\ascii\core.pyc in read(self, table)
   1074 
   1075         self.data.masks(cols)
-> 1076         table = self.outputter(cols, self.meta)
   1077         if hasattr(self.header, 'table_meta'):
   1078             table.meta.update(self.header.table_meta)

C:\Python27\lib\site-packages\astropy\io\ascii\core.pyc in __call__(self, cols, meta)
    866 
    867     def __call__(self, cols, meta):
--> 868         self._convert_vals(cols)
    869 
    870         # If there are any values that were filled and tagged with a mask bit then this

C:\Python27\lib\site-packages\astropy\io\ascii\core.pyc in _convert_vals(self, cols)
    853                     col.converters.insert(0, convert_numpy(numpy.str))
    854                 except IndexError:
--> 855                     raise ValueError('Column %s failed to convert' % col.name)
    856 
    857 

ValueError: Column RANh failed to convert
```

**Comment by taldcroft** [comment]
@waltervrossem - The difference is that `ascii.read()` supplies a default `fill_values` parameter so that blank fields get turned into missing values.  `ascii.get_reader()` does not have that default since it is a lower-level routine.   The error about `Column RANh failed to convert` is because it encountered a blank field but is expecting an integer.

You can read this table using `get_reader` with:
```
reader = ascii.get_reader(ascii.Cds, readme='ReadMe', fill_values=[('', '0')])
reader.read('table2.dat')
```
However, in most cases you should not need to be using `get_reader`.  Was there a specific reason?

**Comment by waltervrossem** [comment]
Ah I see, I was under the impression that I needed get_reader to also get the descriptions for some reason.

**Comment by taldcroft** [comment]
@waltervrossem - OK, closing this.  `get_reader()` does allow a certain level of customization that isn't possible using `ascii.read()`, but this is mostly for very obscure stuff.
