### ISSUE TITLE
1.1b1: test_ignore_warnings fails on some Debian architectures

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#4336]
Hi,

on Debian MIPS (little endian) [32 bit](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=mips64el&ver=1.1~b1-1&stamp=1448196843) and [64bit](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=mips64el&ver=1.1%7Eb1-1&stamp=1448196843), and [hppa](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=hppa&ver=1.1%7Eb1-1&stamp=1448118007) the `test_ignore_warnings` test fails:

```
_____________________________ test_ignore_warnings _____________________________
    def test_ignore_warnings():
        t = table.Table([[np.nan, np.nan]])
        with warnings.catch_warnings(record=True) as warns:
            t.info('stats', out=None)
>           assert len(warns) == 0
E           assert 2 == 0
E            +  where 2 = len([<warnings.WarningMessage object at 0xffe44132b0>,
                               <warnings.WarningMessage object at 0xffe4413208>])
astropy/table/tests/test_info.py:233: AssertionError
```

Numpy version is 1.9.2 (identical to the build on amd64 where the test succeeds).

**Comment by astrofrog** [comment]
@olebole - could you try seeing what the warnings are? Thanks!

**Comment by olebole** [comment]
Yes, but not quickly. I am on travel this week.

**Comment by embray** [comment]
I'll be surprised if this is really a bug so much as a less than robust test, but we'll see...

**Comment by bsipocz** [comment]
We're about to drop np1.9 support, and this doesn't come up again with the past 2 major releases, so I'm inclined to close it. Please reopen if you still see this issue with 2.0rc1!

**Comment by olebole** [comment]
Although late, I can confirm that this works now on MIPS.
