### ISSUE TITLE
AstropyUserWarning screen output has duplicate in iPython

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#4337]
Is the duplicate warning printout below as expected? I used to only get the first line when I use this in iPython:

```python
In [1]: import warnings
In [2]: from astropy.utils.exceptions import AstropyUserWarning
In [3]: warnings.warn('my warning', AstropyUserWarning)
WARNING: my warning [unknown]
WARNING:astropy:my warning
```

I don't see the duplicate line in Python:

```python
>>> import warnings
>>> from astropy.utils.exceptions import AstropyUserWarning
>>> warnings.warn('my warning', AstropyUserWarning)
WARNING: my warning [unknown]
```

**Comment by embray** [comment]
What version of IPython?

**Comment by embray** [comment]
This kind of issue with duplicate warnings in IPython has come up before (ex: #3198), but it hasn't been reported in a while.  I'm not sure how to reproduce it (it might also have something to do with settings for IPython).

**Comment by pllim** [comment]
Pretty sure I was using SSBDEV version (IPython 2.0.0). But it automagically went away! I'll close this then.

**Comment by embray** [comment]
Feel free to reopen if the problem resurfaces.  Then maybe at least we can figure out what's going on.
