### ISSUE TITLE
Automate testing of table _html_repr_ functionality

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#435]
The current end-to-end test of the table `_html_repr_` functionality relies on manually running an ipython notebook.  Perhaps this could be automated.

**Comment by bsipocz** [comment]
While there is still the ``astropy/table/tests/notebook_repr_html.ipynb`` around, two other files seems to test the html outputs. ``astropy/table/tests/test_pprint.py`` and ``astropy/table/tests/test_jsviewer.py``. 

@taldcroft - Can this be closed now? If yes, do we still need the old ``astropy/table/tests/notebook_repr_html.ipynb`` or can it be removed?

**Comment by taldcroft** [comment]
@bsipocz - I think this can be closed and the notebook removed.

**Comment by bsipocz** [comment]
Thanks. I'll go ahead and open a PR for the removal.
