### ISSUE TITLE
FITS: improve support for column-oriented binary tables

### ISSUE THREAD

**Issue by cschreib** [astropy/astropy#4365]
Column-oriented FITS tables (take a look [here]) can be read and written with the current astropy FITS I/O library, however each field in the resulting python table has an extraneous dimension of size 1. See the example below.

Such kind of file can be generated easily with IDL and mwrfits:
```idl
table = {id:[0,1,2], str:['foo','bar','anotherstring'], f2d:[[0.2,0.3,0.5], [1.5,4.8,-1.5]]}
mwrfits, /create, table, 'table.fits'
```

Reading this table in python:
```python
from astropy.io import fits

table = fits.getdata('table.fits', 1)
table['id'].shape  # (1, 3)    should be (3,)
table['str'].shape # (1, 3)    should be (3,)
table['f2d'].shape # (1, 2, 3) should be (2, 3)
```

PS: I am not as skilled in python as I would like to be, so if you know of a user-friendly way to do the same thing as the IDL code above, but in python, I would be very grateful!

[here]: http://www.star.bris.ac.uk/~mbt/topcat/sun253/outColfits.html

**Comment by embray** [comment]
The column-oriented FITS thing is a (perfectly valid, useful) abuse of what can be done with the FITS format, and is not actually recognized as part of the FITS standard in any unambiguous way, so the extra dimensions are exactly what you would get for a column of one row, with 3 element values in each column.

An easy way to drop 1 length dimensions from the shape of an ndarray is with the squeeze method, like `table['id'].squeeze()`.

You can make an array like this in Numpy using a structured array dtype with multiple-element entries.  There might be an easier way but the most straightforward is something like:

```
>>> col1 = [1, 2, 3]
>>> col2 = [4.0, 5.0, 6.0]
>>> col3 = ['abc', 'def', 'geh']
>>> nrows = len(col1)
>>> dtype = [('col1', (int, nrows)), ('col2', (float, nrows)), ('col3', ((str, 3), nrows))]
>>> arr = np.array([(col1, col2, col3)], dtype=dtype)
>>> arr
array([([1, 2, 3], [4.0, 5.0, 6.0], ['abc', 'def', 'geh'])], 
      dtype=[('col1', '<i8', (3,)), ('col2', '<f8', (3,)), ('col3', '<U3', (3,))])
```

One could write a utility function to make this a bit easier too.

Since I don't think there's really an issue with `io.fits` here I'm going to close the issue, but feel free to follow up with any further questions or comments!

**Comment by embray** [comment]
This has come up before by the way: #1840

Be wary when creating arrays in this format that Numpy has an (IMO buggy) limitation in the allowed size of a data type which limits somewhat the usage of this format with Numpy.  I don't think it can support any more than 2 GB :(  This is mostly an arbitrary limitation though, just in that this usage was never anticipated.  The total size of a dtype could easily be a 64-bit int, though it would require an ABI update.

**Comment by cschreib** [comment]
Ah, good to know... ! In the mean time, I have written a small pair of utility functions that wrap around io.fits and work with simple Python "dicts", which I find simpler to handle in this situation than the Numpy structured array. However the structured array is still used under the hood by io.fits, so the limitation you mention still applies.

My Python knowledge is rather limited, so there is certainly room for improvement.

```python
# pycolfits.py

from astropy.io import fits
import numpy as np

def readfrom(filename, lower_case=False, upper_case=False, **kwargs):
    # Open the file and get HDU list
    hdulist = fits.open(filename, **kwargs)

    # Column-oriented FITS tables have empty primary HDU
    # The actual data is located inside the first HDU
    if len(hdulist) == 1:
        raise RuntimeError('this is not a column-oriented FITS table')

    hdr = hdulist[1].header
    data = hdulist[1].data[0]
    colnames = hdulist[1].data.dtype.names

    # Create columns one by one
    tbl = dict()
    for n in colnames:
        # Store that into the dictionary
        if lower_case:
            cname = n.lower()
        elif upper_case:
            cname = n.upper()
        else:
            cname = n

        tbl[cname] = data[n]

    return tbl

def _get_format_code(v):
    # Convert numpy type code into FITS
    if isinstance(v, str):
        dims = ()
        tdtype = 'S'+str(len(v))
    else :
        if isinstance(v, np.ndarray):
            dims = v.shape
        else:
            dims = ()

        tdtype = v.dtype.str.replace('>','').replace('<','').replace('|','')

    if tdtype[0] == 'S':
        # Strings are handled in a peculiar way in FITS
        # They are stored as multi-dimensional array of bytes
        # and the last dimension is the maximum length of all
        # strings in the array
        strlen = int(tdtype[1:])
        tdtype = 'a'
        dims = dims + (strlen,)

    if len(dims) == 0:
        repeat = ''
        dims = (1,)
    else:
        repeat = str(np.prod(dims))

    tform = repeat+fits.column.NUMPY2FITS[tdtype]
    tdim = '('+','.join(str(d) for d in reversed(dims))+')'

    return tform, tdim

def writeto(filename, data, lower_case=False, upper_case=False, **kwargs):
    # Build the ColDef array
    cols = fits.ColDefs([])
    for colname, value in data.iteritems():
        # Figure out which FITS format to use to store this column
        tform, tdim = _get_format_code(value)

        if lower_case:
            cname = colname.lower()
        elif upper_case:
            cname = colname.upper()
        else:
            cname = colname

        # Add new column to the list
        cols.add_col(fits.Column(
            name=cname,
            format=tform,
            dim=tdim))

    # Create the FITS table in memory
    hdu = fits.BinTableHDU.from_columns(cols, nrows=1, fill=True)
    for colname, value in data.iteritems():
        if lower_case:
            cname = colname.lower()
        elif upper_case:
            cname = colname.upper()
        else:
            cname = colname

        hdu.data[cname] = value

    # Write it on the disk
    hdu.writeto(filename, **kwargs)
```

Usage:
```python
# Create a small catalog with two galaxies!
cat = {
    'id'        : np.array([1,        2,       3]),
    'ra'        : np.array([53.006,   53.008,  52.09]),
    'dec'       : np.array([124.0507, 124.051, 124.04]),
    'z'         : np.array([1.05,     2.6,     0.25]),
    'm'         : np.array([11.2,     10.5,    9.34]),
    'quiescent' : np.array([True,     False,   False])
}

# Write the file
pycolfits.writeto('table.fits', cat, clobber=True)

# Read back the file
cat = pycolfits.readfrom('table.fits')
```
