### ISSUE TITLE
test_conesearch predictions non-deterministically fail

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#4382]
I've been noticing repeated instances of failures for `test_conesearch.py` along the lines of the traceback shown below.  I *suspect* this is because the service sometimes provides different answers depending on which mirror you get/whatever randomness applies to vizier, which yields different predictions.  But it might also be a sign of some sort of transient real error?

Two things I have noticed that may or may not be helpful:
1. non-deterministic.  Sometimes I doesn't happen even if I run the test many times over, other times it's semi-repeatable.  It may also matter what network you're on (which probably helps determine what mirror of the server gets found first?)
2. Seems to mostly (only?) happen on py 3.x

(Note that this is a `remote_data` test, so to try to reproduce it you'll need that)

@pllim, any ideas?

```
_______________ TestConeSearch.test_prediction[center1-radius1] ________________

self = <astropy.vo.client.tests.test_conesearch.TestConeSearch object at 0x7f02f6530748>
center = <ICRS Coordinate: (ra, dec) in deg
    (0.0, 0.0)>
radius = <Quantity 0.8 deg>

    @pytest.mark.parametrize(('center', 'radius'),
                             [((SCS_RA, SCS_DEC), 0.8),
                              (SCS_CENTER, 0.8 * u.degree)])
    def test_prediction(self,  center, radius):
        """Prediction tests are not very accurate but will have to do."""
        t_1, tab_1 = conesearch.conesearch_timer(
            center, radius, catalog_db=self.url,
            pedantic=self.pedantic, verbose=self.verbose)
        n_1 = tab_1.array.size
    
        t_2, n_2 = conesearch.predict_search(
            self.url, center, radius,
            pedantic=self.pedantic, verbose=self.verbose)
    
        assert n_2 > 0 and n_2 <= n_1 * 1.5
>       assert t_2 > 0 and t_2 <= t_1 * 1.5
E       assert (2.450000736077996 > 0 and 2.450000736077996 <= (1.5584416389465332 * 1.5))

astropy/vo/client/tests/test_conesearch.py:182: AssertionError
----------------------------- Captured stdout call -----------------------------
INFO: conesearch_timer took 1.5584416389465332 s on AVERAGE for 1 call(s). [astropy.utils.timer]

```

**Comment by pllim** [comment]
This tests the predicted search time with the actual search time. It is not supposed to be very accurate. And yes, it depends on network latency. The 1.5 factor is arbitrary. 

Not too long ago, I had to reduce the search radius to avoid timeout from the service provider (they put in safe-guard for DoS attacks). This test would have been more accurate for more results (larger radius and longer search time).

I'll have to think about this when I get a chance.

**Comment by eteq** [comment]
Ah, gotcha, @pllim.  I wonder if it should just be changed to not even check for accuracy but rather just make sure it runs and doesn't give impossible answers (like negative time or whatever)?  Not a big deal, but also pretty easy...

**Comment by pllim** [comment]
The question comes down to how do we determine whether the prediction works or not. For instance, does it make sense for us to merely test that it "kinda" runs but does not give any meaningful predictions? ¯\_(ツ)_/¯

**Comment by eteq** [comment]
While it wasn't obvious when these first gotten written, I think the answer is "yes" to just checking if it "kinda runs".  That is, we've found that at least *in this case* those predictions aren't very reliable because of network issues that aren't really possible to predict, so it's not a "failure" if that doesn't work: it's expected behavior.

It would be different for runtime predictions that aren't network-related, though.  I *think* we have some of those, right?  And they pretty much always pass, right?

**Comment by pllim** [comment]
@eteq 

> the answer is "yes" to whether it makes sense to check if it "kinda runs"

Okay. Please try #4386. Since it is spurious and I have never encountered it, I'll need someone else to tell me if the fix works.

>  I think we have some of those, right?

Yes. It is in `utils/tests/test_timer.py`.

> And they pretty much always pass, right?

AFAIK, yes.

**Comment by pllim** [comment]
@eteq , closing this for now. Feel free to re-open if you see it again.
