### ISSUE TITLE
IOErrors all related to samp_hub for py2.7

### ISSUE THREAD

**Issue by stscieisenhamer** [astropy/astropy#4383]
In testing RC1.1, get the following on OS X 10.10.5, conda 3.18.6, python 2.7.11, in a base conda environment:
[rc11_fail_py27.txt](https://github.com/astropy/astropy/files/56169/rc11_fail_py27.txt)

Note: Using the same, but with python3.5.1, all tests pass.

**Comment by pllim** [comment]
I added a note about this in https://github.com/astropy/astropy/wiki/v1.1-RC-testing but I don't know whether if it affects release or not. Please update the entry as needed.

**Comment by embray** [comment]
I think the problem is here: https://github.com/astropy/astropy/blob/master/astropy/vo/samp/hub.py#L191

Instead of `socket.getfqdn()` this should probably just be using `socket.gethostname()`.

However, for some reason on your system these calls are returning different results.  Your machine's local hostname does not match the name that our DNS server has for your machine (the former seems to be "hecatean" while the latter is "inanna2")

**Comment by embray** [comment]
On second thought the line I previously indicated isn't at fault here necessarily--it isn't reached when running the tests without `--remote-data`.  However, the last paragraph above is still the main source of the issue here.

**Comment by eteq** [comment]
Aha, that explanation by @embray makes sense.  I think that's an unusal enough situation that we probably don't need to consider this critical, right @embray and @astrofrog ?

**Comment by embray** [comment]
No.

**Comment by embray** [comment]
Going through the code I'm actually pretty confused now as to how this could happen.  The only way this seems to be possible is if @stscieisenhamer had an old lockfile hanging around that contained an outdated value for `'samp.hub.xmlrpc.url'`.  `remove_garbage_lockfiles` is supposed to take care of this, but there may be a corner case that it missed.

**Comment by embray** [comment]
`remove_garbage_lockfiles` seems to ignore any `OSError`s when deleting the old files.  It's possible that this is failing silently, for example, if a file was created with different permissions such that it now can't be deleted.

**Comment by stscieisenhamer** [comment]
Well, based on the lockfile discussion, and the fact that I could not get ANY python or system utility to reproduce the DNS 'hecatean.stsci.edu', and the fact that under python3 all went fine, I simply re-ran the tests and all worked fine.

Note: 'hecatean' was a name associated with the original version of OS X (10.7 i believe?) from which, through updates, the current 10.10 is running. Also, this has survived two different hardware platforms.

I believe this fits the definition of 'edge case'. Closing.

**Comment by pllim** [comment]
@stscieisenhamer , just curious, did you use `--remote-data`? How did you get all the tests to pass in Python 3.5.1 despite #4378?

**Comment by stscieisenhamer** [comment]
did nothing special. didn't even know that was an issue at the time. just `conda create -n test python=3` for the environment, pip installed and ran tests. still no issue.

**Comment by pllim** [comment]
So I am guessing you did not test the "remote data" tests then. Thanks for the clarification.

**Comment by stscieisenhamer** [comment]
correct. wasn't aware. can do if that's a necessary.

**Comment by pllim** [comment]
Would be nice if you have time, just for completeness.

**Comment by embray** [comment]
Reopening, because the issue of `remove_garbage_lockfiles` is probably relevant, albeit minor.

**Comment by pllim** [comment]
I'll just dump fixing the culprit of this problem in #1983 since it is along the same topic.
