### ISSUE TITLE
Table / group.py error

### ISSUE THREAD

**Issue by hoyleb** [astropy/astropy#4384]
I was getting a compilation error:

I had to change 
line 21 table.py
from . import groups

to
from .groups import TableGroups, BaseGroups, ColumnGroups

and in table.py I have to change all groups.TableGroups to TableGroups

**Comment by pllim** [comment]
More information would be nice, like what version of Python and AstroPy you were using, exact error messages, machine specs, etc.

**Comment by hoyleb** [comment]
Very sorry for my short report.
I was using
astropy.__version__
1.0.7
I'm using Canopy
Python 2.7.6 --  64-bit 
on a macos
10.10.5


But now I uninstalled astropy and reinstalled using pip, and now it works perfectly.

**Comment by pllim** [comment]
Good to hear, @hoyleb . Thanks for letting us know! :+1: :smile:
