### ISSUE TITLE
astropy.wcs does not read ctype correctly in the presence of SIP distortion

### ISSUE THREAD

**Issue by nden** [astropy/astropy#4387]
Here's a failing example using one of the test data files:

```
h = fits.Header.fromfile('astropy/wcs/tests/data/sip.fits')
h['CTYPE*']
 
CTYPE1  = 'RA---TAN-SIP'       / Right ascension, gnomonic projection           
CTYPE2  = 'DEC--TAN-SIP'       / Declination, gnomonic projection      

w = wcs.WCS(h)
w.wcs.ctype
 ['RA---TAN', 'DEC--TAN']
```
It still applies the transformation, it simply deletes `SIP` from ctype.

**Comment by embray** [comment]
Did we ever confirm whether or not it's actually performing the SIP corrections, or if the WCS object is juts misreporting the ctypes?

**Comment by nden** [comment]
It is performing the SIP correction. Only '-SIP'  is missing from ctype.

**Comment by mcara** [comment]
@stargaser @nden

From a recent paper by David L. Shupe et al. ["More Flexibility in Representing Geometric Distortion in Astronomical Images" (2012)](http://authors.library.caltech.edu/36801/1/84511M.pdf): _"For SIP, the “trigger” is the addition of “-SIP” to the existing CTYPE1 and CTYPE2 values. This was proposed during the now-defunct effort to define “Paper IV” on distortion as part of the FITS standard. **Regrettably, this fine idea was later discarded and the FITS standard now states that CTYPEn should be eight characters only.** The advantage of the 12-character CTYPEn of the SIP convention gives it the ability to work not only with gnomonic projections, but with any of the standard projections in Paper II (Ref. 3)."_ (see section 6)

So, now I wonder if "-SIP" should be in the CTYPE at all... I am confused on with regard to what (current?) SIP standard requires.

**Comment by mcara** [comment]
@stargaser @nden 
Also, from the above citation, _"For SIP, the **“trigger”** is the addition of “-SIP” to the existing CTYPE1 and CTYPE2 values."_ It is not clear to me what does "trigger" mean here. Would this "trigger" be in conflict with the behavior of astropy.wcs to apply SIP distortions as mentioned by @nden above even though '-SIP' is missing from the CTYPE?

**Comment by nden** [comment]
@mcara I think this is probably better discussed in a different ticket. The problem here is that astropy.wcs now produces different headers and we need to find why.

**Comment by mcara** [comment]
I understand, but "Regrettably, this fine idea was later discarded and the __FITS standard now states that CTYPEn should be eight characters only__" may be either an explanation for the current behavior or maybe we should not fix the apparent "bug" to comply with FITS standard. I am just pointing out that there is a degree of confusion in all this behavior/statements.

**Comment by embray** [comment]
@mcara If I understand correctly, based on what you wrote and what @nden told me yesterday, as well as from past interaction with this feature, the "WCS Paper IV" on distortion corrections is indeed defunct, and so the FITS Standard has written down *some* specifications that conflict with it (specifically regarding `CTYPEn`).  But because we *do* use this SIP specification we will generally allow this one special case exception to the FITS Standard (if we want to be pedantic we could say that FITS+WCS+SIP is a new format that is a superset of proper FITS).  It's all unfortunate, because we started using SIP, IIUC, before the paper was adopted into the FITS Standard, and under the assumption that it eventually would be.

It's not the only otherwise defunct feature from that paper that we've adopted.  For example PyFITS (and by extension `astropy.io.fits`) uses the "record valued" header card format, that is otherwise not specified anywhere.  But we support this.

**Comment by embray** [comment]
> may be either an explanation for the current behavior or maybe we should not fix the apparent "bug" to comply with FITS standard

I think it's probably an explanation. I do think we should fix it though.  Otherwise it's not explicit and leads to confusion.  SIP corrections can be the one exception we'll allow for `CTYPEn`... :(

**Comment by mcara** [comment]
In light of @embray clarification that we support extra digits (compared to FITS standard) in CTYPE it is clear that this is a bug and that '-SIP' should be added to CTYPE.

**Comment by embray** [comment]
Is there also a round-tripping problem here?  For example if a header with SIP corrections is read in, does the WCS object then re-serialize incorrectly by dropping the `-SIP`?

**Comment by nden** [comment]
I'm pretty sure it's a bug. Here's some more info using the above header:

```
from astropy.wcs import _wcs
wprm = _wcs.Wcsprm(h.tostring())
print(wprn)
 ctype: 0x3e3b190
             "RA---TAN-SIP"
             "DEC--TAN-SIP"
```
However, in an astropy.wcs.WCS object, it's not:
```
w = wcs.WCS(h)
print(w.wcs)
ctype: 0x3e3c7c0
             "RA---TAN"
             "DEC--TAN"
```

**Comment by nden** [comment]
A round-trip test comparing an input and output header should fail. A test comparing WCS objects will not fail.

**Comment by embray** [comment]
@nden @mcara Could one or both of you write some full regression tests for this issue that demonstrate it?  I am surprised it was never caught before...

**Comment by nden** [comment]
`WCS._remove_sip_kw` is stripping CTYPE before passing it to wcslib. This is probably done because we still handle SIP in the wrapper and not in wcslib. I _think_ this is just an oversight and there's no harm in passing the full CTYPE to wcslib but I need to test this. If this is true, it'll be an easy fix. And I'll write some tests for it.
