### ISSUE TITLE
ImportError: cannot import name skycoord_to_pixel

### ISSUE THREAD

**Issue by ywis** [astropy/astropy#4390]
Hi! 
When I input this command in the python console: 
```python
from astropy.wcs.utils import skycoord_to_pixel
ImportError: cannot import name skycoord_to_pixel
```
But
```python
from astropy import wcs
```
works fine

**Comment by pllim** [comment]
@ywis , what version of Astropy are you using?

**Comment by ywis** [comment]
0.4.2

**Comment by pllim** [comment]
That is pretty old. Current stable version is 1.0. I would recommend you upgrade your Astropy and check that the API is still correct at http://docs.astropy.org/en/stable/

**Comment by ywis** [comment]
Yep, that solved the problem.

**Comment by pllim** [comment]
Great!
