### ISSUE TITLE
Error 7 and Error 4 when trying to read a fits file.

### ISSUE THREAD

**Issue by pandasarebest** [astropy/astropy#4407]
Hi there. I have recently had to convert png files to fits, so i did that using the following code:

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import Image
import pyfits
import os
import aplpy
from astropy.io import fits
from astropy import wcs

dir=raw_input('Enter Directory address here:')
os.chdir(dir)
dirlist=os.listdir(dir)
filelist = sorted([s for s in dirlist if ".png" in s])
listlen=len(filelist)
for file in filelist:                   
    img = mpimg.imread('%s' % file)
    imgslice = img[:,:,0]
    imgflip = np.fliplr(imgslice)
    imgrot90 = np.rot90(imgflip)
    imgrot180 = np.rot90(imgrot90)
    hdu = fits.PrimaryHDU(imgslice, )
    filename = file.replace ('.png', '.fits')
    
    
    hdu.header['NAXIS'] = (2, 'Changed from 0, for array dimensions')
    hdu.header['NAXIS1'] = (640)
    hdu.header['NAXIS2'] = (512)
    hdu.header['CTYPE1'] = ('GLON-TAN', 'Using Galactic Longitude')
    hdu.header['CTYPE2'] = ('GLAT-TAN', 'Using Galactic Latitude')
    hdu.header['CRVAL1'] = (100, 'Value on Postion CRPIX1')
    hdu.header['CRVAL2'] = (100, 'Value on Postion CRPIX2')
    hdu.header['CRPIX1'] = (320, 'Pixel Position of CRVAL1')
    hdu.header['CRPIX2'] = (256, 'Pixel Position of CRVAL2')
    hdu.header['CDELT1'] = (-0.000112233, 'Pixel scale of CRPIX1 in Degrees')
    hdu.header['CDELT2'] = (0.00112233, 'Pixel scale of CRPIX2 in Degrees') 
    hdu.header['EQUINOX'] = (2000.0)
    hdu.header['MAGZP'] = (50)
    #hdu.header['BSCALE'] = (0.045777)
    #hdu.header['BZERO'] = (1500)

    hdu.writeto(filename)

And I have used the 'less' command to verufy that the new fits files have all this data.

However when i then try and run some APLpy code, it stops at the astropy/wcs/wcs.py section, with the following errors:

  File "/home/simon/anaconda2/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 448, in __init__
    self.wcs.set()

InvalidTransformError: ERROR 7 in wcsset() at line 1760 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameters.
ERROR 4 in celset() at line 399 of file cextern/wcslib/C/cel.c:
Ill-conditioned coordinate transformation parameters
No valid solution for latp for these values of phip, phi0, and theta0.

If anyone happens to have a good idea as to why these errors are appearing that would be great. I knwo thtat if i create a default fits file without the extra headers it is fine, but these headers are needed to get APLpy to register the fits file as being WCS calibrated.

Thanks in advance for any advice or assistance.

**Comment by nden** [comment]
The value of `CRVAL2` does not look correct. It should be between -90 and 90, right?

**Comment by pandasarebest** [comment]
Thanks for pointing that out to me. I can't believe I didnt spot that.

Now I have the problem that when I sun the next piece of code:

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import Image
import pyfits
import os
import aplpy
from astropy import wcs


dir=('/home/simon/PROJECT/Github/Test/Test1')  #where you saved the fits
os.chdir(dir)
dirlist=os.listdir(dir)

fig = aplpy.FITSFigure('lc_0001c.fits')

fig.show_grayscale()        
fig.set_auto_refresh(True)

fig.show_circles(45,29,10)



I get the error CTYPE3 not found. However I dont call CTYPE3 at any point, and I didnt used to get this error.

**Comment by pandasarebest** [comment]
Successfully rolled back my code, and now everything works fine. Thanks nden for pointing out the stupid mistake i made.
