### ISSUE TITLE
Unable to fetch submodule path astropy_helpers

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#4408]
In my `astropy` fork, I can no longer update `astropy_helpers` after I rebase to dev master. What did I do wrong? :frowning: 

```
$ git submodule update
Unable to fetch in submodule path 'astropy_helpers'
```

**Comment by embray** [comment]
I don't know--if it's still a problem I can come have a look, but this isn't an issue for astropy.

> after I rebase to dev master

When you clone your fork you should delete the 'master' branch in your fork and then `git checkout --track upstream/master` so that you have a 'master' branch that tracks with the upstream repo.

**Comment by pllim** [comment]
I couldn't figure it out either. I deleted my local directory tree and recloned the whole thing. Now the error is gone.

**Comment by pllim** [comment]
By the way, my fork does not have a `master` branch. I renamed it to something else. The setup has worked for me the past few years, so I don't think that was the problem. Anyway, thanks.
