### ISSUE TITLE
Improve "building from source" documentation for Linux

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4411]
I've had at least a few people trying to install Astropy on Linux not realizing that a missing "Python.h" means they need to install the python development package for their system.  The current documentation simply reads 

> You will need a compiler suite and the development headers for Python and Numpy in order to build Astropy. On Linux, using the package manager for your distribution will usually be the easiest route

and then goes on to give lots of OSX-specific instructions.  It does not give any more information for Linux.  In the past I've been hesitant to pile on too much information for Linux because 1) An implicit assumption (often incorrect) that Linux users can be expected to "know what they're dong" and 2) It's hard to give comprehensive instructions for different Linux distros.

However, the existing text is horribly vague even under that rubric.  It should at least mention that most distros have a separate Python development package called either "python-dev" or "python-devel".  It also couldn't hurt to supply examples with apt-get and yum at a minimum.

While we're at it I think that section should also be reorganized.  It should open with some general text, and then be broken into subsections specific to OSX, Linux, and ~~Windows~~.  This will make the section less cluttered, and easier to navigate to the information a specific user needs for their platform.  This will at least address a small part of #1807.

**Update:** As I noted in #4420 there are not any existing build instructions specific to Windows, so implementing this task should not include that, as it's a non-trivial undertaking.  Instead this task should include just:
* [ ] Reorganize the existing text so that OS-specific instructions are corralled into OS-specific subsections, and
* [ ] For the Linux specific section add the aforementioned requirement of installing the OS's Python-dev package.

**Comment by giorgos314** [comment]
This sounds a nice issue I can work on for my first contribution. Should I start? Where should I start from?

**Comment by mhvk** [comment]
@giorgos314 - that would be great!  I think the main thing is simply write down your own experience in setting up astropy for development (for me, it is too long ago to remember the pitfalls I encountered...). While @embray is right that it will not be easy to have something that works for all linux versions, my sense would be that if we cover Debian/Ubuntu and Redhat/CentOS we've covered most.

Some suggestions: do focus on python3; perhaps include the use of virtual environments using `pyvenv`, probably with `--system-site-packages`.

**Comment by giorgos314** [comment]
Perfect, I have a lot of ideas - will submit a PR when ready.

**Comment by embray** [comment]
@mhvk I don't want to add anything to this section on virtualenvs or anything like that.  Just note how to install python-dev packages on deb and rpm based systems (as you suggested) and reorganize the existing test as I indicated in the OP.

**Comment by mhvk** [comment]
Yes, agreed, if only to not add parts there that are not linux specific anyway.

**Comment by giorgos314** [comment]
well, I guess someone else fixed it already.......

**Comment by sudheesh001** [comment]
Sorry about that @giorgos314 I didn't really read through all the comments before starting off, realized it once I finished.

**Comment by giorgos314** [comment]
It's ok :) @sudheesh001

**Comment by embray** [comment]
@sudheesh001 @giorgos314 If one of you wants to work on this issue please see the update to the description which added checkboxes for what should be included in a fix to this.
