### ISSUE TITLE
Path objects not supported in low-level I/O packages

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#4412]
In at least `io.ascii` and `io.fits` (and perhaps `io.votable`) one gets unexpected exceptions if a Python 3 `Path` object is passed as the file name.  This was first noted in #4405, where a partial fix was put in place in the I/O registry layer to translate a `Path` object to a string.

In general a `Path` object should be accepted anywhere a file object is accepted.  At least that would be the theory, with no idea of the difficulty and implications.

**Comment by AMAN3003** [comment]
@taldcroft  Has this issue solved if not can i work on this
