### ISSUE TITLE
Compound model expressions not displayed when printing compound model instances

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4414]
Currently, if you create a compound model class and then print it out, the display of the class shows the expression that was used to create it:

```
<class '__main__.CompoundModel1'>
Name: CompoundModel1
Inputs: ('x',)
Outputs: ('y',)
Fittable parameters: ('amplitude_0', 'mean_0', 'stddev_0', 'amplitude_1', 'mean_1', 'stddev_1')
Expression: [0] + [1]
Components: 
    [0]: <class 'astropy.modeling.functional_models.Gaussian1D'>
    Name: Gaussian1D
    Inputs: ('x',)
    Outputs: ('y',)
    Fittable parameters: ('amplitude', 'mean', 'stddev')

    [1]: <class 'astropy.modeling.functional_models.Gaussian1D'>
    Name: Gaussian1D
    Inputs: ('x',)
    Outputs: ('y',)
    Fittable parameters: ('amplitude', 'mean', 'stddev')
```

Here the expression is shown as `[0] + [1]`, where the numeric indices are used for terseness.  One can then look at the list of components to see what each component of the expression is.  I've long held that this display could be improved, but I don't have a great idea for how, yet.  Please suggest something! 

But anyways the point of this bug is that while the *class* shows the components properly, if you print a compound model instance it doesn't give any useful information about the components:

```
In [23]: TwoGaussians = Gaussian1D + Gaussian1D

In [24]: gg = TwoGaussians(1, 0, 0.1, 1, 0.5, 0.3)

In [25]: print(gg)
Model: CompoundModel2
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Parameters:
    amplitude_0 mean_0 stddev_0 amplitude_1 mean_1 stddev_1
    ----------- ------ -------- ----------- ------ --------
            1.0    0.0      0.1         1.0    0.5      0.3
```

One can certainly print the class of the model like: `print(type(gg))`, but that's rather obtuse.  The model instance should show all the components just as the model class does.

I think this should be easy enough for a novice to fix, with a bit of effort.

**Comment by anchitjain1234** [comment]
I would like to work on this bug.
I am able to replicate it but not able to figure out where code of compound modeling is present. [This](https://github.com/astropy/astropy/blob/master/astropy/modeling/_compound_deprecated.py)  file is related to compound modeling but it is deprecated.

**Comment by embray** [comment]
I think I maybe miscategorized this bug.  It's a low-effort fix because it can mostly reuse code that already exists.  However, it requires some understanding of how to utilize the existing code.  You are of course welcome to still try to figure it out.

[`_CompoundModel`](https://github.com/astropy/astropy/blob/v1.1.1/astropy/modeling/core.py#L2431) should implement its own `__str__` by reusing code from [`Model._format_str`](https://github.com/astropy/astropy/blob/v1.1.1/astropy/modeling/core.py#L1694) and [`_CompoundModelMeta.__repr__`](https://github.com/astropy/astropy/blob/v1.1.1/astropy/modeling/core.py#L1878) (in the latter case, the code that formats the individual components could maybe be split off into a separate method as well, like `_format_components` so that it can be easily reused).

**Comment by anchitjain1234** [comment]
So when ``print(gg)`` is typed it should print all the information present currently also with expression and individual components? 
```
In [23]:  g1 = models.Gaussian1D(1, 0, 0.2)

In [24]:  g2 = models.Gaussian1D(2.5, 0.5, 0.1)

In [25]:  gg = g1 + g2

In [26]:  print(gg)
Model: CompoundModel0
Inputs: (u'x',)
Outputs: (u'y',)
Model set size: 1
Parameters:
    amplitude_0 mean_0 stddev_0 amplitude_1 mean_1 stddev_1
    ----------- ------ -------- ----------- ------ --------
            1.0    0.0      0.2         2.5    0.5      0.1
Expression: [0] + [1]
Components: 
    [0]: <Gaussian1D(amplitude=1.0, mean=0.0, stddev=0.2)>

    [1]: <Gaussian1D(amplitude=2.5, mean=0.5, stddev=0.1)>
```
