### ISSUE TITLE
Add Windows specific build instructions

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4420]
Over in #4411 I recommended improving the "Build from source" instructions to break it up into per-platform subsections, including a section for Windows.

However, as I noted in https://github.com/astropy/astropy/pull/4416#issuecomment-167670065 there are not currently _any_ build instructions for Windows.  Only a handful of us, perhaps myself and maybe @mwcraig have direct experience with this and would be able to write such a section.

In particular it would be nice to have instructions for building within the Anaconda environment, and without it.  And separate instructions for setting up and using MSVC or MinGW.  This is a non-trivial task so I think I'll break it out from #4411 which should only add sections for Linux and OSX based on the text that's already there.

**Comment by mwcraig** [comment]
I can help on the Windows/anaconda/MSVC side. Compiler setup for MSVC is easy two cases these days: python 2.7, and 3.5+. I'd prefer skipping python 3 lower than 3.5 (or maybe just refer people to the setup instructions from the cython wiki) because setup is so convoluted...

**Comment by embray** [comment]
For Python 3 lower than 3.5 I don't think it's so bad--you just need Visual Studio 2010 Express if I recall correctly (I might not though).
I continue to this day to kick myself for not taking copious notes last time I set up my Windows build environment.  In any case I agree that focusing on Python 3.5+ is best, and linking to the Cython docs for others sounds fine.

**Comment by embray** [comment]
@mwcraig It occurs me to now you must be talking about this: https://github.com/astropy/ci-helpers/blob/master/appveyor/windows_sdk.cmd  I guess I didn't think of it as "so bad" since I set this up a while ago.

**Comment by mwcraig** [comment]
@embray -- it isn't the build environment setup so much -- that is necessary in python2 for 64bit builds too. It is more the installation instructions here: http://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/#for-python-3-4

I think you can just install the SDK, which isn't as bad. I made the mistake of installing MSVC 2010, then had to follow (microsoft's!) instructions to uninstall parts then reinstall.

Once you have it installed the actual building isn't easier or harder than other architecture/python version combinations.

**Comment by embray** [comment]
> I think you can just install the SDK, which isn't as bad. I made the mistake of installing MSVC 2010, then had to follow (microsoft's!) instructions to uninstall parts then reinstall.

Same. Incidentally I also got errors when trying to uninstall the the old runtimes too, sending me deeper into a MS knowledge base hole, but eventually worked it out.

**Comment by taldcroft** [comment]
I'm in the process of setting up to build / test on windows (for #6458).  Some instructions would be nice!  :smile:  I have basically zero knowledge of Windows and did roughly:
- Make a Windows 10 virtualbox.
- Install git with git-bash
- Install Miniconda-64 for Windows
- Get confused about running Python on Windows, waste time trying to make it happen within git bash.
- Mess around for a long time trying to figure out something that would work for compiling.  After installing some version of VisualStudio community then I tried building and at this point got the link recommendation for installing Microsoft Visual C++ build tools.
- Success!

**Comment by mwcraig** [comment]
oof....which flavor of python? My experience with getting python 3 going on windows has been relatively painless....

**Comment by pllim** [comment]
On my ancient Windows 7, I installed the full Anaconda thingy and used the Anaconda command prompt. I vaguely remember needing to add some system variables (something like https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653(v=vs.85).aspx). Also had to install some MS Visual C++ Studio thingies (the exact flavor might be OS/hardware dependent).

**Comment by drdavella** [comment]
I'm struggling through this myself and just wanted to mention that this might be a potentially useful resource as well: https://wiki.python.org/moin/WindowsCompilers

**Comment by bsipocz** [comment]
Do we still need this? What do you think @pllim?

**Comment by pllim** [comment]
Hmm... I have always built it inside a `conda` environment. I don't think it is worth beating ourselves up with trying to build it outside of `conda`. Let me try to do this (again) on a new Windows VM that we just got and see.

**Comment by bsipocz** [comment]
Yeah, the "go with conda" sounds good enough to me, and it's less docs to maintain. So feel free to close the issue if you would not mind to have that as an approach.

**Comment by pllim** [comment]
Re: Windows -- I think there's still a manual step of installing MSVC if it is not there, see https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required (I need to contact IT to do that for me, so don't close this issue yet).

Also, I think [Install your branch](https://astropy.readthedocs.io/en/latest/development/workflow/development_workflow.html#install-your-branch) needs to link to [building from source](https://astropy.readthedocs.io/en/latest/development/building.html), in addition to the Windows specific instruction.

**Comment by pllim** [comment]
I added what actually worked for me at #10121
