### ISSUE TITLE
Remove AstropyDeprecationWarning from astropy.fits.header

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#4429]
I would leave this low hanging fruit for a newcomer: the warning in L231 in ``astropy/fits/header.py`` is around for a very long time so the next version (which is also an LTS) seems to be a good place to get rid of it finally.

What do you think @embray? 
(I run into this when testing an affiliated package where deprecations are raised as exceptions during tests, and making the code deal with KeyErrors will not help getting rid of the deprecation warning.)

**Comment by Pratik151** [comment]
@bsipocz  Hello, I am new to Astropy community and would like to contribute. I think this small task is perfect for me. 

So I should remove the warning and raise KeyError?

**Comment by bsipocz** [comment]
@Pratik151 - The KeyError is already there, so you only have to remove the warning and make sure the error is always raised. 
However I would wait for @embray's thoughts about this whole issue before doing any work.

**Comment by Pratik151** [comment]
@bsipocz  Ok got it and I will wait for him before making pull request.

**Comment by embray** [comment]
I agree the warning should be removed and that `del header['MISSING']` should always raise a `KeyError`.

However, I have had some complaints about this change in the past--there was a lot of legacy code that deleted keywords and didn't care if the keyword was there or not.  That code has had to be wrapped in `try/excepts` everywhere.  While I stand by the logic of the change, I can appreciate the desire for a method to delete keywords without caring if they were present.

There is already a `Header.remove` method: https://github.com/astropy/astropy/blob/master/astropy/io/fits/header.py#L1530  I would propose that any outright change in the existing behavior, to always raise KeyErrors, should also include not one but two new optional keyword arguments to `Header.remove`:

`Header.remove(keyword)` -> `Header.remove(keyword, ignore_missing=False, all=False)`

For `ignore_missing=True`, `KeyError`s should be caught and ignored.  For `all=True`, all instances of a given keyword should be removed (not just the first).

**Comment by Pratik151** [comment]
@embray I would like to work on this. So what i understood is : we should remove the warning and always raise KeyError and change the Header.remove such that it includes two new optional arguments as you described. Do we need to change any other things also?

**Comment by embray** [comment]
@Pratik151 I think that's it for now.  Maybe there's also something in the docs that needs updating but I'm not sure.

**Comment by Pratik151** [comment]
Ok. Will look into docs also and send PR for review.

**Comment by embray** [comment]
Thanks @Pratik151

**Comment by embray** [comment]
I was pretty sure there was already an issue about this, but I couldn't find it before.  Here it is: #2594

**Comment by AMAN3003** [comment]
@embray I would like work on this issue

**Comment by AMAN3003** [comment]
@bsipocz  @embray  I am new to Astropy community and would like to contribute

**Comment by Pratik151** [comment]
@AMAN3003  I have already worked on this and it is almost completed I guess.
@embray  can you check #4445  when you have time :) Build will pass once it is restarted I think.

**Comment by bsipocz** [comment]
@AMAN3003 - Great to hear that you're interested in contributing to astropy. The place to start is the contributing page http://www.astropy.org/contribute.html. It has links to the most relevant informations, such as the workflow docs, guidlines, and links to the package novice issues. Please read those docs and then you can use the ``package-novice`` label to look for issues to work on. In most of the cases the issues that are already worked on by someone have links to the relevant PRs.

**Comment by AMAN3003** [comment]
Dear Mam,
Thank you for providing me head start. I want to contribute under you. I
have already read the document. But want some newbie bugs to solve and
contribute under your mentorship.
Thanking you
Aman

**Comment by kshitij10496** [comment]
Is this issue fixed ?

**Comment by Pratik151** [comment]
@kshitij10496  I tried to fix this in #4445 and I think this one is fixed.
