### ISSUE TITLE
Remove default cosmology functionality?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4431]
Since we now no longer have a functional interface in astropy.cosmology, is there still any sense in keeping the `default_cosmology` configuration parameter?

cc @aconley @nhmc

**Comment by aconley** [comment]
I suppose not... we'd probably need to pull it out of cosmology/core.py, but as far as I can tell there's no way to use it anyways.

**Comment by nhmc** [comment]
It's used in astropy.coordinates, and potentially could be used elsewhere. I would say it's worth keeping. It's nice to have an 'official' way to set the cosmology via a configuration file, rather than in code.

**Comment by astrofrog** [comment]
@nhmc - can you clarify where exactly it's used? I tried searching for ``default_cosmology`` and it doesn't appear to be used anywhere?

**Comment by nhmc** [comment]
It seems to be used here:

https://github.com/astropy/astropy/blob/master/astropy/coordinates/distances.py#L102

On Wed, Jan 6, 2016 at 10:48 PM, Thomas Robitaille <notifications@github.com

**Comment by astrofrog** [comment]
@eteq - do you think we should just close this, or do you want to reconsider the fact we have a default cosmology used in astropy.coordinates?
