### ISSUE TITLE
"al" unit conflict

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#4433]
The `astropy.units.cds` module (https://astropy.readthedocs.org/en/stable/units/index.html#module-astropy.units.cds) tries to define an `al` unit as a lightyear (apparently from http://vizier.u-strasbg.fr/cgi-bin/Unit).

However, `u.al` actually returns atto-liters.

I've never used either of these units, but it came up during today's tutorial at the AAS.

cc: @taldcroft, @adrn, @eteq

**Comment by embray** [comment]
I'm not sure, but I believe it cases like this it's necessary to use `cds.al`, not `u.al` directly.

**Comment by embray** [comment]
And to be clear, `astropy.units.__init__` doesn't even import the `cds` units into the main `astropy.units` namespace.  So I think this is as intended.

**Comment by larrybradley** [comment]
Yes, one has to:

```
from astropy.units import cds
cds.al
```

I think the user (and then me) just saw the unit in the table and tried to use it as `u.al`.

**Comment by embray** [comment]
I wonder if the documentation could use clarification as to which units are in the `astropy.units` namespace.  I can see how that would be confusing since each submodule has a separate units table, but there isn't a "main" table listing all the units defined by default in the main namespace.
