### ISSUE TITLE
Change release documentation to use twine instead of setup.py upload

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4434]
It seems that at least part of the "right" solution to [my post-release woes](https://github.com/astropy/astropy/issues/4406#issuecomment-166372262) is to prefer using [twine](https://pypi.python.org/pypi/twine) to upload distributions to PyPI, rather than using `setup.py upload`.

Twine can and should also be used to register distributions (as an alternative to `setup.py register`) though the documentation doesn't make this obvious currently.

This doesn't solve all the issues I ran into, but we should update our documentation to prefer it, and I will work on post-release procedures that use it as well.  I've known about twine for some time, but never used it just because I was using Python versions that use HTTPS by default, as I suspect are @eteq and @astrofrog who are so far the only other people who have made Astropy releases.  But for affiliated package authors as well we should probably switch to recommending twine.

**Comment by bsipocz** [comment]
I'm removing the milestone from this one, but keep it open and in mind. 
The release doc just got updated recently. I remember having some issues when did the my first release and twine came up, if I run into difficulties again then will definitely try to come back to this one.

**Comment by bsipocz** [comment]
I'll come back to it after we finish the release.
Today I had no problems using ``setup.py upload`` for the 2.0rc1 upload. However I could only do the upload with twine on Monday for the helpers 2.0rc1 release.

**Comment by astrofrog** [comment]
Yes, we should really use twine now

**Comment by bsipocz** [comment]
This is already done in #6244 to I'm removing the milestone to avoid bumping into it all the time as I probably won't have time to finish that PR up with other things before 2.0.1.

**Comment by bsipocz** [comment]
Done in #6244
