### ISSUE TITLE
Sometimes creating compound models doesn't preserve parameter.fixed

### ISSUE THREAD

**Issue by sirpercival** [astropy/astropy#4438]
Look what I found. This one is ok:

```
>>> from astropy.modeling import models
>>> a = models.Gaussian1D(mean=10.)
>>> a.mean.fixed = True
>>> b = models.Const1D(2.) + a
>>> b[1].mean.fixed
True
```

This one is not:

```
>>> a = models.Gaussian1D(mean=5.) + models.Gaussian1D(mean=10.)
>>> for x in a: x.mean.fixed = True
>>> a[1].mean.fixed
True
>>> a.mean_1.fixed
True
>>> b = models.Const1D(2.) + a
>>> b[2].mean.fixed
False
>>> b.mean_2.fixed
False
```

Since it works in the first case, the intent is to have the constraints be preserved, correct? My guess is that there's something about making a compound model out of another compound model that loses the fixed attribute setting...

**Comment by nden** [comment]
I don't know if this is in the documentation but constraints are supposed to be set on the compound model parameters, not the sub_models. I can see why this is the case for `tied` constraints. I guess `fixed` and `bounds` could propagate but this is not how it works.

**Comment by sirpercival** [comment]
Then I suppose the error here is that fixed does propagate in the first case. And also this should be noted in the documentation.

I'm wondering if there's an argument to be made to allow passing along of such constraints - maybe when constructing a compound model from "submodels" which are fit separately?

**Comment by mvnnn** [comment]
Doing this type :

>>> from astropy.modeling import models
>>> g1 = models.Gaussian1D(1, 5, 0.2)
>>> g1.mean.fixed = True
>>> g2 = models.Gaussian1D(1, 10, 0.2)
>>> g2.mean.fixed = True
>>> g1_plus_2 = g1 + g2
>>> g1_plus_2[0].mean.fixed
True
>>> b = models.Const1D(2.) + g1_plus_2
>>> b.mean_1.fixed
True
>>> b[2].mean.fixed
True

**Comment by embray** [comment]
Yeah, this *should* work the way @sirpercival is expecting, I think.  This came up before in #3481.  When adding together two basic models the constraints are preserved.  But it seems that when adding a basic model with a compound model (or maybe two compound models?) the constraints are *not* being preserved.

**Comment by embray** [comment]
Ah, I think I see the issue, actually.  @sirpercival's example sets the constraints on a compound model.  If the constraints had been set first on the gaussians, the the compound model was created, this would work.  This has to do with the underlying model tree, and the fact that a compound model instance's constraints are not going to be reflected in the tree.  That's tricky--may have to change how constraint propagation is handled when combining models.

**Comment by mvnnn** [comment]
As i explain above you must need to initially declare mean.fixed = True . if you want to do this after CompoundModel but in CompoundModel you have not mean but only mean_1 and mean_2.etc and if you doing this((for x in a: x.mean.fixed = True)) then it's make only mean_1 and mean_2 = True but it can't make  CompoundModel mean value=True and after doing models((Const1D(2.)+CompoundModel))
so that we definitely get False value.

**Comment by mvnnn** [comment]
Example code...as i explain above
```
>>> from astropy.modeling import models
>>> g1 = models.Gaussian1D(1, 5, 0.2)
>>> g1.mean.fixed = True
>>> g2 = models.Gaussian1D(1, 10, 0.2)
>>> g2.mean.fixed = True
>>> g1_plus_2 = g1 + g2
>>> g1_plus_2[0].mean.fixed
True
```
i doing mean value false here
```
>>> for x in g1_plus_2: x.mean.fixed = False
>>> g1_plus_2.mean_1.fixed
False
```
but still i get True value of mean in b CompoundModel
```
>>> b = models.Const1D(2.) + g1_plus_2
>>> b[2].mean.fixed
True
>>> b.mean_1.fixed
True
```

**Comment by embray** [comment]
@mvnnn You're correct that your example is a workaround that can be used.  But as I explained, this is an artifact of how compound models are stored internally.  It should work both ways.  In particular, parameter constraints should probably be explicitly propagated somehow when two compound model instances are added.

**Comment by sirpercival** [comment]
The reason that I was working with the parameters of the individual models is that in my code, the number of submodels is dynamically determined.

**Comment by mvnnn** [comment]
@embray thanks for clarify me. i will fix that.

**Comment by nden** [comment]
I think this is fixed now:
```
>>> from astropy.modeling import models
>>> a = models.Gaussian1D(mean=10.)
>>> a.mean.fixed = True
>>> b = models.Const1D(2.) + a
>>> b[1].mean.fixed
True

>>> a = models.Gaussian1D(mean=5.) + models.Gaussian1D(mean=10.)
>>> for x in a: x.mean.fixed = True
>>> a[1].mean.fixed
True
>>> a.mean_1.fixed
True
>>> b = models.Const1D(2.) + a
>>> b[2].mean.fixed
True
>>> b.mean_2.fixed
True

```

Closing the issue. Feel free to reopen if other problems exist.
