### ISSUE TITLE
Remove deprecated code in astropy.modeling

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4451]
Some of the code in astropy.modeling is present for backward-compatibility with the old `eval` method, and says ``TODO: Remove sometime after Astropy 1.0 release". Now that 1.1 is out, it might be time to remove this code?

cc @embray @nden

**Comment by embray** [comment]
It can be removed for v1.2.

**Comment by pllim** [comment]
Pushing milestone to 2.0 since 1.3 is theoretically frozen.

**Comment by bsipocz** [comment]
These deprecations and TODOS were removed in #4857 for 1.2, so I'm this now.
