### ISSUE TITLE
Deprecate and eventually remove Python 2 support

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4454]
Python 2 is legacy.  Python 3 is the present and future of Python.  I don't need to repeat the arguments here.

I'm not currently suggesting a timeline for this.  Just that we need to continue doing what we can to push the community away from Python 2 through documentation, tutorials, articles, and social pressure (and technical pressure in less critical areas, such as offering Python-3-only features).

Of course, before we even deprecate Python 2 support there should be an Extra-Long-Term-Support release that guarantees critical bug fixes as needed for institutional users stuck on Python 2.

**Comment by astrofrog** [comment]
The next LTS release will happen in 2017 according to our calendar, and should be supported until the end of 2019. If we exceptionally increase support for that to 3 years instead of 2, we could make the next LTS release the last major release supporting Python 2.x. That means 3 more releases fully supporting Python 2.x (To some extent, there's really no reason why we couldn't stop developing features for Python 2 sooner now that Astropy has a nice large set of features).

**Comment by embray** [comment]
> we can support it until 2020 (the end-of-life date for Python 2.x) and we could make it the last major release supporting Python 2.x

Although much is being done to encourage users at all levels to get off Python 2.7 before the 2020 end-of-life, I wouldn't be surprised if there are still users out there who are on it, and maybe also planning (unfortunately) for continued paid support for Python 2.7.

I suppose we could say "We'll put out new Python 2.7-compatible patch releases if someone is paid to do the work"?

**Comment by Juanlu001** [comment]
Paraphrasing Nick Coghlan, "Stop Supporting Python 2 (for free) (in 2020)"

http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

**Comment by eteq** [comment]
> I suppose we could say "We'll put out new Python 2.7-compatible patch releases if someone is paid to do the work"?

:+1: to this in principal.

It's hard to tell, but there is a bit of a catch in that a fair number of the user-contributors may want to write *new* code in py2.x .  That is, astronomers are notoriously unlikely to keep things up-to-date even if the "dev community" has switched entirely to py 3.  I have no good solution for this and maybe we just have to bite the bullet... but it's something to consider, anyway as the time gets closer.

**Comment by taldcroft** [comment]
astropy-dev conversation:  https://groups.google.com/forum/#!topic/astropy-dev/0pumTIoqV5Q

Python-3 statement: https://python3statement.github.io/

**Comment by embray** [comment]
> It's hard  to tell, but there is a bit of a catch in that a fair number of the user-contributors may want to write new code in py2.x 

They could do that, but if they want to contribute it they'll still have to get it working in Python 3 as well.  By 2020 it should be less of a problem.  Software Carpentry is mostly switched over to teaching Python 3.

**Comment by bsipocz** [comment]
Closing this in favour of #6234. Removal of python2 support will be done in v3.0, and scheduled to be done somewhere midway in the release cycle.
