### ISSUE TITLE
table join fails due to shape mismatch for metadata

### ISSUE THREAD

**Issue by hcferguson** [astropy/astropy#4455]
I tried to join two tables. It failed when trying to merge the metadata. 

One table started out in ascii, the other in hdf5. When I wrote  the ascii table out as hdf5 and read it back in, the table join worked. 

It failed with:

```
...
/Users/hcferguson/anaconda/lib/python2.7/site-packages/astropy/utils/metadata.py in merge(left, right, merge_func, metadata_conflicts)
     97                 elif right[key] is None:
     98                     out[key] = left[key]
---> 99                 elif left[key] != right[key]:
    100                     if metadata_conflicts == 'warn':
    101                         warnings.warn('Cannot merge meta key {0!r} types {1!r} and {2!r}, choosing {0}={3!r}'

ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

Looking at the metadata for the two tables, I see a mismatch in the internal formats:

```
In [35]: t.meta
Out[35]: OrderedDict([('comments', ['', '', '', '', '', '', '', '', ''])])

In [36]: gds.meta
Out[36]: 
OrderedDict([(u'comments', array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', ''], 
      dtype='|S1'))])
```

So I wrote the first table out to an hdf5 file and read it in again with `Table.read(file,format='hdf5')` and now the format matches that of the second table, and the table join works:

```
In [43]: thdf5.meta
Out[43]: 
OrderedDict([(u'comments', array(['', '', '', '', '', '', '', '', ''], 
      dtype='|S1'))])
```

**Comment by hcferguson** [comment]
Correction....it still fails when I try to join the two hdf5 tables, even though their metadata has the same format.

**Comment by hcferguson** [comment]
Succeeds if I just set the comments in the metadata to None:
```
In [26]: thdf5.meta['comments']
Out[26]: 
array(['', '', '', '', '', '', '', '', ''], 
      dtype='|S1')

In [27]: gds.meta['comments']
Out[27]: 
array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', ''], 
      dtype='|S1')

In [28]: thdf5.meta['comments'] = None

In [29]: gds.meta['comments'] = None

In [30]: tt = join(gds,thdf5,keys='ID',metadata_conflicts='warn')
```

**Comment by mhvk** [comment]
Ai, this is because the comments are arrays, and `array1 != array2` returns an array with bools, which cannot be used in an if-statement. I think this will need some rewrite in that comparison in terms of try/except; cc @taldcroft

**Comment by taldcroft** [comment]
In addition to what @mhvk said, there are a few things that need attention:

- Why are there so many blank comments to begin with?  Are those really in the original files?
- It doesn't seem like the HDF5 reader should be returning an np.array of comments.  Metadata should in general use pure Python structures for compatibility.  In this case if you turned the HDF5 comments back into a Python list then it should merge.
- The `!=` operation can fail for other reasons besides returning an array with bools (as in this case where the shape doesn't match), so that definitely needs to be in a try/except.
- The original merge implementation was purposely simple to see what kind of real-life issues would come up.  So here we are.  :smile:

**Comment by embray** [comment]
I am also confused by the presence of arrays in the metadata...

**Comment by embray** [comment]
> The != operation can fail for other reasons besides returning an array with bools (as in this case where the shape doesn't match), so that definitely needs to be in a try/except.

Agreed that *arbitrary* exceptions that occur in metadata comparison (assume anything can happen...) should be handled.

**Comment by taldcroft** [comment]
See #4459 for a possible fix to this.

**Comment by taldcroft** [comment]
@hcferguson - would it be possible to make one or both of your original files available somehow?  I'm just curious about what's going on with all the blank comments.  Or alternately, do you know why they both have all these empty comment lines?

**Comment by hcferguson** [comment]
@taldcroft -- sorry for the delay. I pared them down to a few rows and put them at http://www.stsci.edu/~ferguson/outgoing/  files barro_subset.txt and gds_subset.hdf5. 

```
from astropy.table import Table,join
gds = Table.read('gds_subset.hdf5')
barro=Table.read('barro_subset.txt',format='ascii.sextractor')
barro['ID'] = barro['object']
gb = join(gds,barro,keys='ID')
```

**Comment by astrofrog** [comment]
The latest example sent by @hcferguson  doesn't seem to crash anymore, maybe this can be closed?
