### ISSUE TITLE
Sphinx on python3 does not appear to be able to link to SyntaxWarning

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#4465]
In the context of #4456, I was trying to move the documentation build on travis to python 3.5, but found that sphinx raised a couple of warnings that do not appear on python 2 (see https://travis-ci.org/astropy/astropy/builds/101435099). I confirmed locally that one gets
```
io/votable/references.txt:4: WARNING: py:class reference target not found: SyntaxWarning
io/votable/references.txt:4: WARNING: py:class reference target not found: SyntaxWarning
io/votable/references.txt:4: WARNING: py:class reference target not found: SyntaxWarning
io/votable/references.txt:4: WARNING: py:class reference target not found: RuntimeWarning
io/votable/references.txt:4: WARNING: py:class reference target not found: ValueError
```
This seems to be in the context of creating the description for the classes [1] where the links to those warnings cannot be found and are thus missing. Could there be something wrong in the astropy helper setup? (e.g., `astropy_helpers/sphinx/conf.py` -- definitely not obvious to me...).

[1] http://docs.astropy.org/en/latest/io/votable/api_exceptions.html#exception-utilities

**Comment by mhvk** [comment]
This seems an issue with `astropy-helpers`; see https://github.com/astropy/astropy-helpers/issues/214

**Comment by embray** [comment]
See also https://github.com/astropy/astropy/blob/master/docs/conf.py#L200 and #1221 and https://bugs.python.org/issue11975

**Comment by bsipocz** [comment]
also somewhat related: https://github.com/astropy/astropy-helpers/pull/25

**Comment by mhvk** [comment]
Closing since resolved in `astropy-helpers`
