### ISSUE TITLE
Some Astropy code is definitely not Python 4-compatible

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4477]
Without even knowing what Python 4 will look like, some parts of Astropy are guaranteed to be incompatible, e.g.

```python
    def __lt__(self, other):
        if six.PY3:
            return super(Table, self).__lt__(other)
        elif six.PY2:
            raise TypeError("unorderable types: Table() < {0}".
                            format(str(type(other))))
```

in ``table.py``. On Python 4, no code will get executed.

We should instead use:

```python
if six.PY2:
    # Python 2 code
else:
    # Python 3 code
```

I wrote a short blog post about this: http://astrofrog.github.io/blog/2016/01/12/stop-writing-python-4-incompatible-code/ :)

**Comment by embray** [comment]
:+1: and thanks also for the blog post.   We should start making these changes ASAP as a prerequisite to #4454.

**Comment by embray** [comment]
Also, I don't know when Python 4 will even come out. But I don't think future proofing for Python 4 should be the only argument for this.  

In the past we've written code primarily for Python 2 and forward ported to Python 3.  Although there are some people still developing primarily on Python 2 (and in some cases for good reasons, such as the still not satisfactorily resolved issue of pure-ascii strings in Numpy arrays), we should still aim now to write code that is primarily aimed at Python 3 and backport to Python 2 where necessary.
