### ISSUE TITLE
Remove compatibility layer for astropy.utils.compat.subprocess

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4480]
I think ``astropy.utils.compat.subprocess`` can be deprecated in the same way as some of the other compat modules now that we don't support Python 2.6 anymore. If anyone wants to do this, please feel free to! Be sure to add a deprecation warning and a test as done in https://github.com/astropy/astropy/pull/4464 for example.

**Comment by Pratik151** [comment]
@astrofrog  I would like to work on this. I will remove it and add deprecation warning and also add test as you did for others modules like gzip and argparse.

**Comment by astrofrog** [comment]
Closed in #4483 (merged manually)
