### ISSUE TITLE
Move sphinx build to python3 and latest numpy

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#4481]
As we're moving to python3, the sphinx build should also be on python3 and some care should be taken to ensure that all the references actually go to the python3 documentation. As of this writing, just using an intersphinx link to `docs.python.org/3/objects.inv` has problems. See https://github.com/astropy/astropy-helpers/pull/214

**Comment by mhvk** [comment]
There also is an issue with the latest numpy a warning is raised even on python2

**Comment by bsipocz** [comment]
@mhvk - If this issue is not urgent, you can assign it to me and I'll try to come up with a fix this week (most probably by providing two local complementary inventory, one for each version).

**Comment by mhvk** [comment]
@bsipocz - that would be great!

**Comment by embray** [comment]
Just now seeing this issue.  Sounds like a good idea.

I've mostly had success building the docs on Python 3, modulo a few warnings that I'm sure we can find workarounds for.

**Comment by embray** [comment]
And of course this should be another prerequisite to #4454

**Comment by mhvk** [comment]
Agreed, it mostly works as-is.  Just wanted to split it off from #4456, since there's a bit more needed than just changing `.travis.yml`.

**Comment by bsipocz** [comment]
See #4556 and astropy/astropy-helpers#216 as a solution for this.

**Comment by mhvk** [comment]
Closing in favour of #5135
