### ISSUE TITLE
Allow WCS class to take Image HDU

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4493]
Since the WCS class can take a filename of a FITS file or a header, it makes sense we could also allow it to be initialized from a ``PrimaryHDU`` or ``ImageHDU`` (should be unambiguous).

**Comment by embray** [comment]
Should be straightforward.

**Comment by mcara** [comment]
Do you mean that you do not want to have to write `.header` after and HDU name?

**Comment by embray** [comment]
If I understand correctly that's all this is.

**Comment by mcara** [comment]
What about the fact that when `header` is a string (file name), then `WCS` tries to get WCS from the _primary_ header _only_. Currently there is no way to tell it to load the WCS from a different extension. If WCS constructor had an `ext` parameter to specify the extension, then this would be really useful.

**Comment by nden** [comment]
I agree with @mcara. A useful interface would be

`WCS(f, ext)`, where `f` is a file name or an `HDUList`. This also supports distortions in FITS extensions, so one doesn't have to pass additionally `fobj` to get the distortions as the current interface requires.

**Comment by astrofrog** [comment]
I agree that it would also be nice to be able to specify the HDU, but indeed the original issue here was just to avoid typing ``.header`` on HDU objects.

**Comment by anchitjain1234** [comment]
If anyone else is not working on this bug, I would like to work on it.

**Comment by anchitjain1234** [comment]
Here do we just have to check if ``header`` passed to WCS is of type ``PrimaryHDU`` or ``ImageHDU`` and if it is than change ``header = header.header`` and make ``header_string`` from it?

**Comment by embray** [comment]
That's basically it if I understand correctly.
