### ISSUE TITLE
support complex type in convolve

### ISSUE THREAD

**Issue by elinor-lev** [astropy/astropy#4495]
Currently astropy.convolution.convolve (and convolve_fft) only support real array for the input array/kernel, not complex arrays:

astropy-1.1.dev14145-py2.7-macosx-10.5-x86_64.egg/astropy/convolution/convolve.py:129: ComplexWarning: Casting complex values to real discards the imaginary part
  array_internal = array.astype(float, copy=False)
astropy-1.1.dev14145-py2.7-macosx-10.5-x86_64.egg/astropy/convolution/convolve.py:139: ComplexWarning: Casting complex values to real discards the imaginary part
  kernel_internal = kernel.astype(float)

 It's useful to have it done for complex type as well.

**Comment by embray** [comment]
I'm tempted to call this a bug, but I don't know if it was originally intentional for some reason...

**Comment by embray** [comment]
In part it may be that the Cython code does not explicit support complex values, but it should.  It appears that `convolve_fft` does allow complex inputs and kernels though.

**Comment by elinor-lev** [comment]
Both fft_convolve and convolve2d allow complex, so it's what I'm using for
now. It appears in the code of astropy's version that there are several
places where both the array and kernel are cast into float, so it might be
a feature.
e.g.:

line 120:        array_internal = np.array(array, dtype=np.float)


I tried removing those but with no success. I suspect it doesn't support
complex because of the interpolation used to handle nan's which is why I
want to use it in the first place..

**Comment by embray** [comment]
Right, the Cython code which handles the interpolation was not written to support complex types.  It could be though.  Would take a little elbow grease but nothing hugely complicated that I can think of...

**Comment by keflavich** [comment]
It's not obvious what the use case for convolution of complex arrays is.  If that can be elaborated, there might be incentive to implement this, but this issue has been sitting unaddressed for nearly 3 years, so I'm closing it for now.
