### ISSUE TITLE
1.1+: `TestFittable1DModels::test_input1D` often crash on MIPS architecture

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#4496]
On MIPS, I often get the following output while testing with Python-2.7:
```
astropy/modeling/tests/test_models.py::TestFittable1DModels::test_input1D[model_class1-test_parameters1] PASSED
astropy/modeling/tests/test_models.py::TestFittable1DModels::test_input1D[model_class2-test_parameters2] PASSED
astropy/modeling/tests/test_models.py::TestFittable1DModels::test_input1D[model_class3-test_parameters3] PASSED
astropy/modeling/tests/test_models.py::TestFittable1DModels::test_input1D[model_class4-test_parameters4] PASSED
astropy/modeling/tests/test_models.py::TestFittable1DModels::test_input1D[model_class5-test_parameters5] debian/rules:56: recipe for target 'test-python2.7' failed
```
([`debian/rules`](https://sources.debian.net/src/python-astropy/1.1.1-2/debian/rules/) is actually the Debian Makefile that called the test.) The numbers in `model_class5-test_parameters5` where the crash appears vary, I also already had a [successfull compilation of astropy 1.1](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=mips&ver=1.1-1&stamp=1450010607)
All build logs for MIPS are [here](https://buildd.debian.org/status/logs.php?pkg=python-astropy&arch=mips). The crashes only appear on the big endian machines; for little endian everything for version 1.1+ is [fine](https://buildd.debian.org/status/logs.php?pkg=python-astropy&arch=mipsel).
It is, however, probably not an endianness problem; other big-endian architectures (like s390) compile [without problems](https://buildd.debian.org/status/logs.php?pkg=python-astropy&arch=s390x).

It is not unlikely that this is a problem of our build machines (I already experienced some flakiness there); so the bug report is more for completeness -- and if others observe similar.

**Comment by olebole** [comment]
I investigated this a bit and it seems that it is a [problem with the scipy package on Debian](https://bugs.debian.org/811368).

**Comment by embray** [comment]
Thanks for investigating!

**Comment by AMAN3003** [comment]
@olbole if the issue is not resolve i would like to work on this

**Comment by olebole** [comment]
@AMAN3003 please check out [Debian#811368](https://bugs.debian.org/811368) for this problem: I opened it agains scipy since this was crashing. However, it seems that it is a linux kernel problem -- something with the (missing) floating point emulation on some MIPS CPUs.
So, if you still want to work on this, you should probably get in contact with the Debian developer who changed the bug to the Linux kernel.

**Comment by AMAN3003** [comment]
@olebole  I don't have debian developer in contact

**Comment by olebole** [comment]
Since this problems seems to [fixed on Debian](https://bugs.debian.org/811368), I am going to close it.
