### ISSUE TITLE
NDArithmeticMixin arithmetic fails when wcs.WCS present even if identical

### ISSUE THREAD

**Issue by AnthonyHorton** [astropy/astropy#4499]
The `wcs.WCS` class does not implement the equivalence test functions `__eq__()` and `__ne__()`. Consequently an attempt to test the equivalence of two `WCS` instances reduces to checking identity.  Example:

    In [19]: w = ccd.wcs
    
    In [20]: w2 = copy.deepcopy(w)
    
    In [21]: w == w
    Out[21]: True
    
    In [22]: w == w2
    Out[22]: False

This causes issues with, for example, `nddata.NDArithmeticMixin._arithmetic` which attempts to check that `nddata.NDData` objects have the same WCS before performing arithmetic on them and raises an exception if the check fails.  This effectively prevents any arithmetic on `nddata.NDData` objects that have WCS as this check will always fail unless the two `wcs.WCS` are references to the same instance.  

astropy/ccdproc#204
astropy/ccdproc#283

**Comment by astrofrog** [comment]
I think that strict equality is hard to define, but there is now a ``compare`` method on ``w.wcs`` that can help compare two WCS objects to different degrees of accuracy (added in https://github.com/astropy/astropy/pull/2468). Note that this is a method on ``w.wcs``, not on ``w``.

**Comment by AnthonyHorton** [comment]
Thanks @astrofrog, looks like `nddata.NDArithmeticMixin._arithmetic` should be using `compare` instead of doing `if self.wcs != operand.wcs: raise ValueError("WCS properties do not match")`  Would you agree, @MSeifert04?

**Comment by MSeifert04** [comment]
@astrofrog - Do you mean ``astropy._wcs.Wcsprm.compare``? I'm not quite sure what you mean by ``w.wcs``.

**Comment by astrofrog** [comment]
@MSeifert04 - every ``WCS`` instance has a ``wcs`` attribute:

```
In [5]: from astropy.wcs import WCS

In [6]: w = WCS()

In [7]: w.wcs.compare
Out[7]: <function Wcsprm.compare>
```

**Comment by MSeifert04** [comment]
@astrofrog - Thanks!

**Comment by AnthonyHorton** [comment]
OK, the problem isn't in `wcs` as it does implement a proper equivalence test, it's just in `astropy._wcs.Wcsprm.compare` instead of `__eq__`, I'll edit the issue title to be less misleading.

Meanwhile I've make a minimal change to `NDArithmeticMixin` so that it uses `astropy._wcs.Wcsprm.compare` instead of `__eq__` when `wcs.WCS` objects are present. This fixes the issue I had.

**Comment by astrofrog** [comment]
@AnthonyHorton - the issue with overloading ``__eq__`` is that it wouldn't allow any options to be passed. However, we *could* overload ``__eq__`` and just raise an exception that points users to ``compare``.

**Comment by AnthonyHorton** [comment]
@astrofrog Now that I know about `wcs.Wcsprm.compare` I agree there is no reason to overload `__eq__` in `wcs.WCS` in order to modify its functionality.  Overloading it purely to point naive users such at myself at `compare` is a nice idea though.

**Comment by embray** [comment]
Is there some reason not to implement `__eq__`?  Seems fine to use it as the same as `compare` with the default arguments, which requires the strictest equivalence.  That could still be useful for some cases.

**Comment by MSeifert04** [comment]
I think an easy way to directly access and document a comparison function would be best. I haven't found it myself and even after @astrofrog named the methodname it was quite hard to find.
Since ``__eq__`` isn't included in the documentation I would prefer a ``WCS`` method or (even better if I look at #4272) a convienience function in the ``astropy.wcs`` package that takes two ``WCS`` objects.
