### ISSUE TITLE
ValueError from observing-example-2

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#4500]
Locally I'm getting this error from the docs build for observing-example-2:

```
/Users/deil/code/astropy/docs/coordinates/observing-example.rst:108: WARNING: Exception occurred in plotting observing-example-2
 from /Users/deil/code/astropy/docs/coordinates/observing-example.rst:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "<string>", line 24, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pyplot.py", line 2889, in fill_between
    **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 4670, in fill_between
    X[0] = start
ValueError: setting an array element with a sequence.
```

Downloading [observing-example-2.py](http://astropy.readthedocs.org/en/latest/coordinates/observing-example-2.py) and running it reveals the line that causes the error:

```
$ python observing-example-2.py 
Traceback (most recent call last):
  File "observing-example-2.py", line 24, in <module>
    plt.fill_between(delta_midnight, 0, 90, sunaltazs.alt < -0*u.deg, color='0.5', zorder=0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pyplot.py", line 2889, in fill_between
    **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 4670, in fill_between
    X[0] = start
ValueError: setting an array element with a sequence.
```

It's here: https://github.com/astropy/astropy/blame/master/docs/coordinates/observing-example.rst#L133

This is with matplotlib 1.5.1 and Astropy master, the Python version doesn't seem relevant (same error with Python 2.7, 3.4 and 3.5).

The error doesn't seem to occur on travis-ci currently:  https://travis-ci.org/astropy/astropy/jobs/102747115

**Comment by bsipocz** [comment]
@cdeil - you don't see it in travis as it uses mpl <=1.5.0 for the docs builds as 1.5.1 caused docs build failures in several packages (at least photutils and glue) due to https://github.com/matplotlib/matplotlib/issues/5836.

**Comment by AMAN3003** [comment]
@cdeil @bsipocz @embray Can I give a Try to this solve if the issue has n't yet solved.

**Comment by cdeil** [comment]
@AMAN3003 - Go for it!

If you're new to Astropy development, check out the [developer documentation](http://astropy.readthedocs.org/en/latest/#developer-documentation).

**Comment by AMAN3003** [comment]
@cdeil  Thanks  I am working on this issue.

**Comment by AMAN3003** [comment]
@cdeil I have solved the issue of this error setting an array element with a sequence. but i don't have edit right how should I commmit  my new script could you help

**Comment by AMAN3003** [comment]
@cdeil X[0]=start in _axes.py was generating the error because
start contains the xlice[0],y2slice[0] which returns in this case (-12 h,0 ) (sequence)which cannnot be assigned to a array element as xslice[0] has a two elements with space so we should remove the h i.e u*hours

**Comment by AMAN3003** [comment]
but removing u*hours result in time manipulation error in  times = midnight + (delta_midnight) since
delta_midnight should be time so i multiplied it with u*hours and the warning was resolved

**Comment by cdeil** [comment]
>  i don't have edit right how should I commmit my new script could you help

@AMAN3003 - The way to contribute to Astropy is through a Github pull request. Please read the [Astropy developer documentation](http://astropy.readthedocs.org/en/latest/#developer-documentation)!

Looks like you did figure that out and made a pull request here: #4573.
I'll have a look and comment over there ... it's better if you explain there what that pull request does and maybe how it fixes the issue.

**Comment by AMAN3003** [comment]
@cdeil please review my commit and merge it .it was very hard to fix the bug but I enjoyed .if any mistake was done by me please mention.

**Comment by AMAN3003** [comment]
@cdeil definately s Sir  I have given the explanation please consider it

**Comment by bsipocz** [comment]
@cdeil - I think the observing example got removed/reworked in the new release. Could you close the issue if you also think it's obsolete?

**Comment by cdeil** [comment]
Yes, I think this issue was resolved or became obsolete in the meantime.

@bsipocz @AMAN3003 - Thank you!

**Comment by cdeil** [comment]
@bsipocz - Just now I got this:
https://gist.github.com/cdeil/05af20eb674f2f9dc8ec68187306ff3e

Have you seen those? Do you think they are potential real issues, i.e.
- should `docs/generated/examples/coordinates/plot_obs-planning.py` be marked `remote_data`?
- should `docs/generated/examples/io/split-jpeg-to-fits.py` be marked to require `'Hs-2009-14-a-web.jpg` somehow?

**Comment by bsipocz** [comment]
@cdeil - This is weird no one touched those files in months, I wonder why these weren't caught on travis? Can you open an issue so others will see it?

**Comment by cdeil** [comment]
> Can you open an issue so others will see it?

Before I do.

Can you reproduce the issue locally?
If no, I'll first look for a problem with my setup first some more.

**Comment by bsipocz** [comment]
I didn't see these when doing the docs build yesterday, but it was with py3.4. I started to rerun now with py3.5, will report back in ~15 mins.

**Comment by bsipocz** [comment]
Very weird. I don't see any of the generated examples tested at all when running the tests locally. Did you do a simple ``python3.5 setup.py test``?

```
../docs/development/workflow/terminal_cast.rst .
../docs/development/workflow/virtual_pythons.rst .
../docs/development/workflow/virtualenv_detail.rst .
../docs/io/misc.rst .
../docs/io/registry.rst .
../docs/io/unified.rst .
../docs/io/ascii/base_classes.rst .
../docs/io/ascii/extension_classes.rst .
```

**Comment by astrofrog** [comment]
> Very weird. I don't see any of the generated examples tested at all when running the tests locally

Did that ever work? I thought these only got tested when running ``build_docs``?

**Comment by bsipocz** [comment]
Somehow @cdeil managed to get them tested, see the errors in his gist above.
