### ISSUE TITLE
Why are the Scale and Shift models not Fittable?

### ISSUE THREAD

**Issue by sirpercival** [astropy/astropy#4523]
There's no real reason I can see for this... I guess you could fit `y - x` with a `Const1D` for `Shift`, and `y / x` with a `Const1D` for `Scale`, but it seems counter-intuitive.

**Comment by pllim** [comment]
Why would one need `modeling` to fit these? You can just find the answer by using the math operators, no?

**Comment by embray** [comment]
I don't think there's any real reason.  Those models don't really quite fit with the others in that module and were originally conceived of in a different context (for use in WCSs).

**Comment by sirpercival** [comment]
@pllim Looking for a best-fit scale factor between two spectra, for example? Hopefully in a way that handles outliers nicely?

**Comment by pllim** [comment]
@sirpercival , feel free to submit a PR if you wish to tackle this.

**Comment by Cadair** [comment]
I would agree these would be useful, mainly to make it easier to create composite fittable models.

**Comment by nden** [comment]
It may be useful to have them be `fittable` for the case when they are a part of a compound models.

**Comment by sirpercival** [comment]
@embray is there a reason to keep the non-fittable versions of Scale and Shift for WCS, or could I just replace them with fittable versions?

**Comment by embray** [comment]
@sirpercival There's no reason.  They could just be changed to subclasses of Fittable1DModel.

**Comment by pllim** [comment]
See #4718 (solved).
