### ISSUE TITLE
test_metadata_too_large should be skipped if yaml is not installed

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4528]
Currently, ``test_metadata_too_large`` fails if h5py is installed but not yaml, so the ``skipif`` directive needs to be updated to also include a check of yaml.

**Comment by mirca** [comment]
So, my understanding is to add a ``skipif('not HAS_YAML')`` to ``test_metadata_too_large``. Is that correct?

**Comment by astrofrog** [comment]
you need to keep ``not HAS_H5PY`` so I think you'll need ``not HAS_H5PY or not HAS_YAML``

**Comment by astrofrog** [comment]
Closed by #4530
