### ISSUE TITLE
Better document limited handling of correlated errors in NDData

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#4538]
I'm hoping @MSeifert04 can take care of this one...

There is now limited support for correlated errors in NDData thanks to #4272 but an explanation has not been added to nddata documentation.

**Comment by MSeifert04** [comment]
I have updated my notebook for the tests and uploaded it: https://github.com/MSeifert04/nddatadocs/blob/master/NDData.ipynb . Unfortunatly the visual size of quantities is really small.
I could convert this to a ``.rst`` but I think it's not as easy as just converting the notebook?

**Comment by MSeifert04** [comment]
I haven't forgotten about this but I hesitate to make a PR because there are some open PRs concerning NDData that aren't merged or rejected. As soon as I figure out which ones will make it in the 1.2 release I'll submit the Documentation.

**Comment by MSeifert04** [comment]
I have finally suceeded in making a RTD documentation containing the changed documentation: 

- [nddata.index.rst](http://astropy-mseifer.readthedocs.io/en/tmp_nddata_final/nddata/index.html)
- [nddata.nddata.rst](http://astropy-mseifer.readthedocs.io/en/tmp_nddata_final/nddata/nddata.html)
- [nddata.mixins.index.rst and all pages linked there](http://astropy-mseifer.readthedocs.io/en/tmp_nddata_final/nddata/mixins/index.html)

This documentation is based on all of my merged **and still open** PRs regarding NDData. So I'll need to change the documentation again if any of the PRs is not merged or seriously altered. But it helped me to keep sane and not risking a lot of merge-conflicts.

Still not done is narrative documentation of the NDUncertainty and subclasses and the general subclassing documentation. I think I'll have time this week to complete them.

**Comment by pllim** [comment]
@MSeifert04 , for our sanity here, if possible, perhaps you can list all the "still open PR" numbers here, just so we can keep track going forward? :smile:

**Comment by MSeifert04** [comment]
- [ ] #4787
- [ ] #4789
- [ ] #4797
- [ ] #4799
- [ ] #4827 

Not relevant for documentation:
- [ ] #4828 
- [x] #4809
- [ ] #4788 (well that PR is about the docstrings for classes)

**Comment by MSeifert04** [comment]
So documentation is now done (apart from review) and I did another build on RTD: https://github.com/astropy/astropy/issues/4538#issuecomment-216696038

Should I make a PR so you can comment inline?

**Comment by mwcraig** [comment]
> So documentation is now done (apart from review) and I did another build on RTD: #4538 (comment)

> Should I make a PR so you can comment inline?

Yes, please do.

**Comment by MSeifert04** [comment]
@mwcraig See #4863
