### ISSUE TITLE
Ipython Notebook and EarthLocation representation warning/error

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4542]
I tried to get the ``EarthLocation`` and print the representation of it and it works (it returns the correct representation) but it also raises an Error:

```
from astropy.coordinates import EarthLocation
a = EarthLocation.of_site('Paranal Observatory')
a
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Programming\Anaconda\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339             method = _safe_get_formatter_method(obj, self.print_method)
    340             if method is not None:
--> 341                 return method()
    342             return None
    343         else:

C:\Programming\Anaconda\lib\site-packages\astropy\units\quantity.py in _repr_latex_(self)
   1030                                               style=Latex.format_exponential_notation,
   1031                                               max_line_width=np.inf,
-> 1032                                               separator=',~')
   1033                 latex_value = latex_value.replace('...', r'\dots')
   1034             finally:

C:\Programming\Anaconda\lib\site-packages\numpy\core\arrayprint.py in array2string(a, max_line_width, precision, suppress_small, separator, prefix, style, formatter)
    439         if isinstance(x, tuple):
    440             x = _convert_arrays(x)
--> 441         lst = style(x)
    442     elif reduce(product, a.shape) == 0:
    443         # treat as a null array if any of shape elements == 0

C:\Programming\Anaconda\lib\site-packages\astropy\units\format\latex.py in format_exponential_notation(cls, val)
    103             The value in exponential notation in a format suitable for LaTeX.
    104         """
--> 105         if np.isfinite(val):
    106             m, ex = utils.split_mantissa_exponent(val)
    107 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
<EarthLocation (1946618.261025452, -5467645.090548764, -2642488.447714588) m>
```

I'm using astropy 1.1.1, numpy 1.10.1.

**Comment by AMAN3003** [comment]
@MSeifert04  I am a newbie contributor can i handle this issue.and could you guide me  to 
fix this out

**Comment by AMAN3003** [comment]
@MSeifert04 i am not getting any warning could you .Could you ellaborate where you get this warning.
do you want the warning to be removed.
EarthLocation (1946618.261025452, -5467645.090548764, -2642488.447714588) m>

**Comment by MSeifert04** [comment]
@AMAN3003 - I'm not sure how to fix this. But the problem is only visible when using the ``latex``-formatter, so this is probably only the case for ipython notebooks. 

On the other hand The Error message indicates that the formatter gets a whole array instead of a single value but the ``EarthLocation`` directly subclasses ``Quantity``: which displays nicely and without error. The only difference I found so far is that ``EarthLocation`` uses a ``numpy.array`` with fields (``x``, ``y``, ``z``) instead of a "normal" array.

**Comment by mhvk** [comment]
It seems most likely this is related to `EarthLocation` using a structured array (somewhat of a mistake, in hindsight), and that the iterator over values for `latex` sends the x,y,z groups to the latex formatter, rather than format them one by one.

@AMAN3003 - do go ahead and have a look, but be forewarned that it might be trickier than it seems.  I won't have time this week, but can likely help next week.

**Comment by AMAN3003** [comment]
@mhvk  as I am newbie will I able to fix it? if not then help me to fix it in next week as per comfortable schedules.If you could guide i will definitely  try it. But I did n't receive the value warning in my Ipython notebook instead I get the warning
  https://github.com/AMAN3003/astropy/pull/1
which i already fixed

**Comment by AMAN3003** [comment]
@mhvk  sorry I was eager to fix this issue and didn't waited for your guide and help.But will need indeed in future as i am just a newbie

**Comment by AMAN3003** [comment]
@MSeifert04  please tell whether to use np.any([true,false])----> true 
or np.all([true,false])--->false

**Comment by MSeifert04** [comment]
@AMAN3003 - You need to make a pull request for astropy itself not for your repository. Then the tests are run and it is easy to review it.

**Comment by AMAN3003** [comment]
@MSeifert04 If i was not able make the proper PR request please guide me I am newbie

**Comment by MSeifert04** [comment]
@AMAN3003 - The relevant information to make a PR should be in http://docs.astropy.org/en/latest/development/workflow/development_workflow.html#ask-for-your-changes-to-be-reviewed.

**Comment by MSeifert04** [comment]
@eteq @mhvk Is this fixed now?

**Comment by bsipocz** [comment]
@MSeifert04 - Looks like #5068 is the fix, and is being merged.

**Comment by MSeifert04** [comment]
:+1:
