### ISSUE TITLE
Resource.__repr__ throws an AttributeError no attribute _element_name

### ISSUE THREAD

**Issue by bdilday** [astropy/astropy#4545]
Example:

``` python
from astroquery.vizier import Vizier
c = Vizier.find_catalogs('Kang W51')
print(c)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-5315f3e3adca> in <module>()
----> 1 print(c)

/Users/ben/venv/lib/python3.4/site-packages/astropy/io/votable/tree.py in __repr__(self)
   3017         buff = io.StringIO()
   3018         XMLWriter(buff).element(
-> 3019             self._element_name,
   3020             attrib=w.object_attrs(self, self._attr_list))
   3021         return buff.getvalue().strip()

AttributeError: 'Resource' object has no attribute '_element_name'

```

This has been reported on astroquery also
https://github.com/astropy/astroquery/issues/610

The example shown here,
https://astroquery.readthedocs.org/en/latest/vizier/vizier.html

shows Resource as having no `__repr__` method. I have a fix for the AttributeError issue, but I do not know what behavior is desired. Can somebody clarify?

**Comment by embray** [comment]
It looks like `Resource.__repr__` was first added in #3639.  But this is indeed a bug--nothing that I can see ever sets `_element_name` in the `Resource` class.  It would have to depend on whether it was initialized from a `RESOURCE` tag or a `TABLE` tag since that class appears to represent both.

**Comment by goelakash** [comment]
@embray Can this be solved as follows:

1. Initialise `self._element_name = "TABLE"` in Table `__init__`.
2. In Resource class do
```
if not self._element_name:
    self._element.name = "RESOURCE"
```

This is based on my understanding that the Resource class can either accept an element of Table class, or a pure Resource element, which needs to have its `_element_name` initilialized (like various other classes for eg. Link,Field etc.)

**Comment by bsipocz** [comment]
The original issue is solved, probably by https://github.com/astropy/astropy/pull/5382, so this can be closed.
