### ISSUE TITLE
Explicitly set BeautifulSoup parser to html.parser to avoid warning

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4550]
I'm now seeing the following warning when reading a table with Astropy (using BeautifulSoup in ``astropy.io.ascii.html``:

```
/Users/tom/miniconda3/envs/production35/lib/python3.5/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")
```

This means that ``html.parser`` should be specified in the default case.

Should be easy to fix (leaving as a beginner issue)

**Comment by anchitjain1234** [comment]
@astrofrog I would like to work on this issue.

**Comment by astrofrog** [comment]
@anchitjain1234 - thanks! Please open a pull request with your changes once you have them ready.

**Comment by AMAN3003** [comment]
@astrofrog  and @anchitjain1234  can I also work on this issue

**Comment by raunaqabhyankar** [comment]
is this bug open? In that case i would like to work on it.

**Comment by hamogu** [comment]
Maybe we should file this with bs4?
Presumably they wrote the code with interactive users in mind...
