### ISSUE TITLE
astropy installation problem 

### ISSUE THREAD

**Issue by AMAN3003** [astropy/astropy#4559]
error: [Errno 13] Permission denied: 'astropy.egg-info/dependency_links.txt'
 this is error which is appearing when i tried to install astropy in ubuntu 12.04
![screenshot from 2016-02-03 13 29 14](https://cloud.githubusercontent.com/assets/16108341/12776259/7b9f0cfc-ca7a-11e5-96cd-6da2bb052438.png)

I tried all the stackoverflow and other method but could not install astropy

**Comment by mirca** [comment]
I think you need to install ``jijnja2`` module. After, try ``sudo python setup.py develop``, as well.

**Comment by AMAN3003** [comment]
i have installed jinja2 but still facing the issues

**Comment by mvnnn** [comment]
@AMAN3003 try this ```python3 setup.py install```

**Comment by embray** [comment]
@mirca There is never a good reason to `sudo` anything during development of Astropy, or most Python packages.  They should be using a conda env or a virtualenv, or just run out of the source tree directly--these development styles are described in the astropy docs...somewhere.

@mvnnn Those two commands do completely different things that are largely at odds with each other.  

@AMAN3003 It looks like you've been alternatingly running commands with and without `sudo`.  At some point you ran `./setup.py` with `sudo` and now have generated files in your repository owned by root and not yourself.  You should run `sudo git clean -dfx` to clean these files from your repository and start again.  Don't use `sudo` to run anything.

**Comment by AMAN3003** [comment]
@embray  You were right but first I have to give chmod +x setup.py then run ./setup.py and it work fine thank you.

**Comment by embray** [comment]
@AMAN3003 That's strange, because `setup.py` is already marked executable in the git repository.
