### ISSUE TITLE
Sphinx compatible ascii table output

### ISSUE THREAD

**Issue by kgabor** [astropy/astropy#4590]
Hello,

I could not find a way to print a Table in a sphinx compatible ascii format. The docstring of [FixedWidthTwoLine](http://docs.astropy.org/en/stable/api/astropy.io.ascii.FixedWidthTwoLine.html#astropy.io.ascii.FixedWidthTwoLine) says:

```
      # Pretty-printed table
      +------+------------+
      | Col1 |   Col2     |
      +------+------------+
      |  1.2 | "hello"    |
      |  2.4 | there world|
      +------+------------+
```

but apparently cannot produce this style of output and none of the other formats are understood by sphinx as a [table](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#grid-tables). The top and bottom width markers shall be present for the simple sphinx table formats. Would you consider adding this feature?

Thanks.

**Comment by taldcroft** [comment]
It would be pretty easy to implement this, at least as an output writer.  In the meantime here is a code workaround that should let you generate a table that will parse as a table in Sphinx / ReST:
```
>>> from astropy.io import ascii
>>> from astropy.table import Table
>>> from StringIO import StringIO
>>> out = StringIO()
>>> dat = Table([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
...             names=['alpha', 'beta', 'gamma'])
>>> ascii.write(dat, out, format='fixed_width_two_line', position_char='=')
>>> lines = out.getvalue().splitlines()
>>> lines = [lines[1]] + lines + [lines[1]]
>>> print('\n'.join(lines))
===== ==== =====
alpha beta gamma
===== ==== =====
    1    4     7
    2    5     8
    3    6     9
===== ==== =====
```

**Comment by mvnnn** [comment]
@taldcroft i want to work on this issue.

**Comment by mvnnn** [comment]
i will add ```def PrettyPrint()``` method in ```astropy/astropy/table/table.py``` for print Table as @kgabor mention. i want to make ```def PrettyPrint()``` method for all size of Table. @taldcroft that's right approach ?

**Comment by taldcroft** [comment]
@mvnnn - making a new pretty print method is not the right approach.  It should be a new `io.ascii` reader class `FixedWidthRestructuredText` that can read and write any reStructuredText tables.  This will be moderately difficult to get right.

**Comment by simongibbons** [comment]
I'm just starting to have a go at this [here](https://github.com/simongibbons/astropy/blob/rst_table_printer/astropy/io/ascii/fixedwidth.py)

Whilst the code certainly isn't ready to be included yet I would like some feedback as to how much of the [RST spec for Simple Tables](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#simple-tables) should be implimented.

Currently the writer is working, as for the reader it looks ok apart from supporting overflow in the rightmost column and continuation lines.

**Comment by pllim** [comment]
@simongibbons , feel free to open a pull request with "[WIP]" follow by your own title, where "WIP" means "work in progress".

**Comment by taldcroft** [comment]
@simongibbons - to follow on from the good advice of @pllim, also remember to include `[skip ci]` in each commit message in the WIP branch until it actually has passing tests.

**Comment by taldcroft** [comment]
As for scope of implement the RST spec for tables, I suspect we don't want to go down the rabbit hole of doing everything.  For instance the multi-column support and spanned rows support are tricky.  In particular you will find a lot of breakage currently if you want multiple lines of text in a single column  cell.
E.g.
```
In [2]: t = Table([['asdf\nasdf\nasdf\n', 1], ['asdf', 2]])

In [3]: t
Out[3]: 
<Table masked=False length=2>
      col0       col1 
     str480     str128
--------------- ------
asdf
asdf
asdf
   asdf
              1      2
```
So I would just start with requiring the simplest version of the simple format with no row or column spanning.

**Comment by simongibbons** [comment]
Thanks for the pointers, I've made the PR with support just for the Simple Table with no multicolumn and spanned rows.

**Comment by astrofrog** [comment]
This was done by @simongibbons in https://github.com/astropy/astropy/pull/4812 - thanks!
