### ISSUE TITLE
WCS.to_header issue

### ISSUE THREAD

**Issue by samverstocken** [astropy/astropy#4592]
Hi,

I believe I have encountered an issue with the to_header() function of the WCS class in Astropy.
I experience the problem when converting the header of the attached FITS file to a WCS object and then converting this object back a header, essentially performing the following steps:

from astropy.io import fits
from astropy.wcs import WCS
header = fits.getheader("GALEX_NUV_unbinned.fits")
wcs = WCS(header)
new_header = wcs.to_header()

The 'new_header' has "CDELT1" and "CDELT2" attributes which are both set to unity, and the corresponding unit is supposedly "deg". This is plain wrong, and completely confuses DS9 for example, when matching the original image with the new image (header replaced by the new header) "by WCS".

[GALEX_NUV_unbinned.fits.zip](https://github.com/astropy/astropy/files/124574/GALEX_NUV_unbinned.fits.zip)

**Comment by nden** [comment]
According to the FITS WCS standard, if the `CD` keywords are present, `CDELT` keywords have values of 1. It appears the original header is wrong, as CDELTs have values different from 1, which is only allowed if you have a `PC` matrix. In this case wcslib sees there is a `CD` matrix and correctly sets all CDELTs to 1.

**Comment by samverstocken** [comment]
Thanks for the clarification!

**Comment by saimn** [comment]
This is related to #1084: `to_header` always use `PC`, with `CDELT=1`. Your original header has both `CDELT` and `CD`, but in this case `CDELT` are ignored. Also ds9 has no issue with this new header, maybe there were a bug before ?

**Comment by samverstocken** [comment]
Oh, I upgraded Ds9 from version 7.3 to version 7.4 and the images are matched perfectly now :)
Thanks for the responses!
