### ISSUE TITLE
Auto-detect ECSV files

### ISSUE THREAD

**Issue by dkirkby** [astropy/astropy#4596]
Currently, the format must always be specified when reading an ECSV file, e.g.

```
table = astropy.table.Table.read('data.ecsv', format='ascii.ecsv')
```

This issue is a suggestion to auto-detect the ECSV format for files with the .ecsv extension.

**Comment by cdeil** [comment]
👍

**Comment by nimitbhardwaj** [comment]
This is perhaps the duplicate of #6265
