### ISSUE TITLE
importing astropy takes very long

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4598]
I'm using astropy 1.1.1 and Windows10 with python 3.5 (Anaconda installation). I always dismissed it in the past but everything that imports astropy takes very long on my computer:

```
%time import astropy
Wall time: 1.62 s
Wall time: 1.63 s
Wall time: 1.62 s
Wall time: 1.61 s
Wall time: 1.62 s
%time from astropy.nddata import NDData
Wall time: 7.05 s # fluke(?)
Wall time: 3.38 s
Wall time: 3.52 s
Wall time: 3.39 s
```

I'm not sure what is causing this and I don't know how one would profile something like this.

**Comment by pllim** [comment]
What about starting Python itself? Does that seem normal, or also too long? How does the same imports compare in another OS (if you happen to have the same machine partitioned for different OSes)?

Regarding time difference in the two different import statements:
http://stackoverflow.com/questions/17605659/why-does-it-take-longer-to-import-a-function-from-a-module-than-the-entire-modul

**Comment by MSeifert04** [comment]
Starting ``IPython`` takes quite long but starting ``Python`` is very fast (but ``import astropy`` is also slow there). The ``%time`` tests were done in ``IPython`` so maybe there is a connection (is this a known problem or a corrupted installation?).

I've compared it to other imports:

```
numpy: Wall time: 281 ms
scipy.ndimage: Wall time: 813 ms
numba: Wall time: 4.11 s
matplotlib.pyplot: Wall time: 953 ms
```

I don't have another OS avaiable currently.

**Comment by pllim** [comment]
On RedHat Linux with Anaconda, I also see that starting IPython is slower than Python itself. That is probably expected given IPython has more bells and whistles.

Timing the imports in IPython, like you did, but on my machine:
```python
In [1]: %time import astropy
CPU times: user 560 ms, sys: 1.05 s, total: 1.61 s
Wall time: 6.57 s

In [2]: %time import astropy
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 10 µs

In [3]: %time from astropy.nddata import NDData
CPU times: user 611 ms, sys: 91 ms, total: 702 ms
Wall time: 4.02 s

In [4]: %time from astropy.nddata import NDData
CPU times: user 1e+03 µs, sys: 0 ns, total: 1e+03 µs
Wall time: 21.9 µs
```

My guess is that it takes time for Astropy to import all the other stuff that it imports at start up. But once everything is imported, it is no longer an issue for subsequent imports. Not sure what we can really do about this. Maybe someone with more expertise on this can comment.

**Comment by astrofrog** [comment]
Just to add another datapoint:

```python
In [1]: %time import astropy
CPU times: user 479 ms, sys: 109 ms, total: 589 ms
Wall time: 821 ms
```

**Comment by pllim** [comment]
@astrofrog , what is your machine specs? Your time looks much better!

**Comment by astrofrog** [comment]
MacOS X 10.8 with Python 3.5. But I think the main thing that matters here is that I have an SSD disk. However, it still takes almost a second.

**Comment by MSeifert04** [comment]
@pllim Yes subsequent imports are very fast but I'm not sure it's the imports that make ``import astropy`` that slow. I noticed quite a few decorators. I'm not sure if they are all applied when importing astropy but maybe they are the bottleneck.

But maybe the best solution is buying a faster computer. :-)

**Comment by pllim** [comment]
Hmm, given that SSD disk is a lot faster than regular HDD, perhaps this is really a hardware limitation?

**Comment by MSeifert04** [comment]
Still the imports of numpy, scipy are a lot faster (5-10 times faster than astropy) that is what's bothering a bit.

And I made sure I always used a "fresh kernels" for the timings.

**Comment by astrofrog** [comment]
Ah, I think it's to do with setting up the units. We should do some more detailed profiling to check.

**Comment by bsipocz** [comment]
@pllim - I don't think it has anything to do with hdd hardware, testing on a very old server I don't see any outstandingly slow number:

```
In [1]: %time import astropy
^[[ACPU times: user 544 ms, sys: 77 ms, total: 621 ms
Wall time: 778 ms

In [2]: %time import astropy
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 14.8 µs

In [3]: %time import astropy
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 19.1 µs

In [4]: %time import astropy
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 15 µs

In [5]: %time import astropy
CPU times: user 1 ms, sys: 0 ns, total: 1 ms
Wall time: 25 µs
```

**Comment by pllim** [comment]
@bsipocz , what are the specs of this server? Does it use SSD?

**Comment by bsipocz** [comment]
Nope, old stuff only (~7years). Also the /home is network mounted, which would only add to slowness. I'll try to dig out the spec.

**Comment by bsipocz** [comment]
I couldn't dig out the HDD specs, the cpu is a Xeon E5520. When I get home I can test it on a non SSD mac and linux laptop, too. 
Also this was with python2.7, I don't have a working py3 on it yet.

Can it be a windows specific issue?

**Comment by MSeifert04** [comment]
@bsipocz - Your scipy import takes 1/8 of the time of the astropy-import. So it's roughly the same difference. Of course windows might slow things down especially depending on the ``Path`` and ``Anaconda``. But it's nice to see the difference between scipy and astropy is roughly the same.

**Comment by MSeifert04** [comment]
@astrofrog - Do you know how one could profile an ``import`` in a meaningful way? There are a lot of function (almost all of them very fast) calls during ``import astropy`` and most of them are lookups (relative and absolute imports).

**Comment by pllim** [comment]
Here is my attempt at profiling the import.
```python
>>> import cProfile
>>> import pstats
>>> cProfile.run('import astropy', 'prof_import.stats')
>>> stats = pstats.Stats('prof_import.stats')
>>> stats.strip_dirs()
>>> stats.sort_stats('cumulative')
>>> stats.print_stats(10)
Mon Feb 15 11:44:49 2016    prof_import.stats

         774642 function calls (762338 primitive calls) in 2.812 seconds

   Ordered by: cumulative time
   List reduced from 2816 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        4    0.025    0.006    2.983    0.746 __init__.py:7(<module>)
        1    0.002    0.002    2.817    2.817 <string>:1(<module>)
        2    0.002    0.001    1.575    0.787 logger.py:2(<module>)
        1    0.010    0.010    1.571    1.571 console.py:5(<module>)
        1    0.004    0.004    1.063    1.063 __init__.py:86(_check_numpy)
       26    0.127    0.005    0.993    0.038 __init__.py:1(<module>)
        2    0.019    0.009    0.877    0.438 __init__.py:11(<module>)
        3    0.007    0.002    0.789    0.263 __init__.py:10(<module>)
        1    0.007    0.007    0.710    0.710 misc.py:6(<module>)
        2    0.003    0.001    0.692    0.346 __init__.py:9(<module>)
```
You can also visualize it, for example, with https://github.com/jrfonseca/gprof2dot 
```
gprof2dot.py -f pstats prof_import.stats | dot -Tpng -o output.png
```
![output](https://cloud.githubusercontent.com/assets/2090236/13055391/0aedc0c2-d3dd-11e5-9ebd-13e0fd85f704.png)

**Comment by MSeifert04** [comment]
@pllim Thanks for that Graph, I cannot get the ``dot`` command working (some configuration problem) but inspecting yours there is >20% of the time going into units and >10% into ``re.compile``. Very informative :+1: 

Not sure if one should/could speed those up without making some submodules lazy...

**Comment by pllim** [comment]
Regarding units... @mhvk ?

**Comment by mhvk** [comment]
I guess it is slightly strange that units are loaded at all if one just does `import astropy` -- it might be good to have a bit closer look at what actually happens in `astropy/__init__.py` (I tried a bit but got lost quickly, and am too stressed for time to do more soon).

**Comment by pllim** [comment]
Looking at `astropy/__init__.py`, my hunch is that `units` is imported during
```python
test = TestRunner.make_test_runner_in(__path__[0])
```
where it invokes `astropy.utils.introspection.find_current_module(depth=2)`.

However, changing this will break the test structure. So should we just mark this as "won't fix"?

**Comment by MSeifert04** [comment]
I have no objections if you want to close this issue. I just thought it might be worth mentioning since it struck me as rather long. No need to change anything if it may break things.

**Comment by mhvk** [comment]
@pllim - but why then is `nddata` not imported?

**Comment by pllim** [comment]
@mhvk , good point! My hunch could be wrong. Here is another way to interpret the run time (see attached text file). Having the file path listed could help provide more hints.

[prof_import_cumtime.txt](https://github.com/astropy/astropy/files/141195/prof_import_cumtime.txt)

And if you just filter out everything but `units` related entries:

[prof_import_cumtime_units.txt](https://github.com/astropy/astropy/files/141197/prof_import_cumtime_units.txt)

**Comment by saimn** [comment]
`units` is imported by `utils.console` but used only in `human_file_size` so it could be moved to a local import. With this change, the import time on my laptop is ~ 900/950ms before, and ~650/700ms after.

**Comment by mhvk** [comment]
@pllim, @saimn - OK, very helpful! So, units takes about 1/4 of the time, which seems a lot (though a large number of entries get generated).
It might be worth making the import local, though in the end very little of astropy does not use units, so it would just delay the delay. Probably better to focus on trying to shorten the time a bit.

**Comment by saimn** [comment]
@mhvk Yes, it is probably pointless to avoid importing something like `units`, which is widely used. It can still speedup some imports like `io.fits`.

**Comment by mhvk** [comment]
Indeed, no reason `io.fits` should become slow because of `unit`. Although in the hopefully not too distant future, there may well be more units on on `wcs`, table columns, etc.

**Comment by pllim** [comment]
There is another suggestion at #4638.

**Comment by mhvk** [comment]
Just for reference here, the content of #4638:
> Right now astropy.utils.console unconditionally import IPython, which can cause a substantial overhead in the importing time. It would be good to check before if we are in non interactive mode, discarding the IPython import if this the case, and saving some cpu cycles.

This seems like a no-brainer, though I think it might best be done one step higher up, i.e., not importing `console` when one is not interactive (the `ipython` one still is useful too).

**Comment by saimn** [comment]
Indeed `utils.console` imports both units (for `human_file_size`) and IPython, so it would be good to avoid importing this module. 
`utils.console` is imported by the logger module, which needs only `color_print` for the stream logger. So one option would be move the `utils.console` import to a local import in `StreamHandler`. This way the import would be delayed until the logger is actually used. 
Another option could be to move the color-related stuff from `utils.console` to another module. 

With the first option, my import time goes down from ~480ms to ~250ms. The second option needs a bit more work, but is also cleaner and more robust on the long term I guess.

**Comment by pllim** [comment]
Moving functions out of a module breaks existing API and is not backward compatible. Is it worth the trouble for that import time that only happens once per session?

**Comment by saimn** [comment]
`utils.console` could import the moved functions to maintain backward compatibility. It needs more tests but it seems to be a significant improvement (almost x2 on my case, with a fast ssd).

**Comment by pllim** [comment]
@saimn , since you already did the work, why not just submit a PR? :wink:

**Comment by saimn** [comment]
@pllim - Yes, will do. After looking more in detail the second option is not possible anyway.

**Comment by pllim** [comment]
Is this still an issue?

```
In [1]: %time import astropy
CPU times: user 104 ms, sys: 36.4 ms, total: 141 ms
Wall time: 140 ms
```

**Comment by bsipocz** [comment]
@pllim - Even if this is not an issue any more, having a simple import benchmark may make some sense. We can either leave this open, or rather open an issue in the benchmark repo?

**Comment by pllim** [comment]
@bsipocz , I added this to project planning board, so perhaps a collective decision could be made at the next telecon?

**Comment by nschloe** [comment]
I just updated [tuna](https://github.com/nschloe/tuna) to support the new Python 3.7 import time profiles. Might be helpful for you. Simply run
```
python3.7 -X importtime -c "import astropy" 2> out.log
tuna out.log
```
to get
![fireshot capture 2 - tuna - http___localhost_8000_](https://user-images.githubusercontent.com/181628/42135687-9fd27670-7d4e-11e8-9378-c48a98f88ab8.png)

**Comment by mhvk** [comment]
See also https://github.com/numpy/numpy/issues/11457 for the numpy import time. What is the `pkg_resources` part?

**Comment by astrofrog** [comment]
@nschloe - I just tried tuna and got:

```
$ tuna out.log 
Invalid timing data Sun Jul  1 17:36:25 2018    out.log
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/py37/bin/tuna", line 11, in <module>
    sys.exit(main())
  File "/Users/tom/miniconda3/envs/py37/lib/python3.7/site-packages/tuna/cli.py", line 13, in main
    start_server(args.infile, args.browser)
  File "/Users/tom/miniconda3/envs/py37/lib/python3.7/site-packages/tuna/main.py", line 58, in start_server
    data = read(prof_filename)
  File "/Users/tom/miniconda3/envs/py37/lib/python3.7/site-packages/tuna/main.py", line 15, in read
    stats = pstats.Stats(prof_filename)
  File "/Users/tom/miniconda3/envs/py37/lib/python3.7/pstats.py", line 96, in __init__
    self.init(arg)
  File "/Users/tom/miniconda3/envs/py37/lib/python3.7/pstats.py", line 112, in init
    self.get_top_level_stats()
  File "/Users/tom/miniconda3/envs/py37/lib/python3.7/pstats.py", line 141, in get_top_level_stats
    for func, (cc, nc, tt, ct, callers) in self.stats.items():
AttributeError: 'int' object has no attribute 'items'
```

Any idea what that could be due to?

**Comment by astrofrog** [comment]
By the way, running this with e.g. ``astropy.coordinates`` or ``astropy.time`` is instructive too, and I think there are definitely places we should try and optimize.

**Comment by mhvk** [comment]
Import times are a common comment in our user survey (e.g., by @olebole). Giving this a high-priority label.

**Comment by mhvk** [comment]
For at least a little bit of help for importing `astropy.units` where one has `scipy` installed, see #7636

**Comment by mhvk** [comment]
From https://github.com/astropy/astropy/issues/4598#issuecomment-401611577, another fairly big deal is `pkg_resources` - as far as I can see we only use it for minimum version checks; for numpy and python this is overkill.

**Comment by mhvk** [comment]
See #7647 for another speed-up PR; removing the import of `pkg_resources` really helps! `import astropy` goes from 0.28 to 0.16 s (and it is not as if we use it much elsewhere in the code).

**Comment by pllim** [comment]
Have we sped it up enough to close this yet?

**Comment by bsipocz** [comment]
Adding the import benchmarks should be a thing sooner rather than later, so I'm adding this reminder issue to the milestone.

**Comment by s2t2** [comment]
how to fix though?

**Comment by s2t2** [comment]
I'm trying to `conda update -all` as advised in the [Anaconda docs](https://www.anaconda.com/blog/keeping-anaconda-date), but it can't get past the step where it updates this "pytest-astropy" package, because it's taking so long. 

Do you know how to fix this?

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/issues/4598#issuecomment-655830752

Whatever Anaconda tells you, as a user to another user, never do `conda update --all` especially if your environment is old and very bulky. Only update what you need or create a fresh environment. But, if you insist, you can try `conda uninstall pytest-astropy` and then proceed and see what happens. 🤞 

Some people also only `conda install` non-Python stuff and grab all the Python packages from PyPI using `pip install`. That would cause less pain when you `conda update` this and that, but it has its own cons too. So, choose your poison and good luck!

**Comment by s2t2** [comment]
Thanks. I think the point though is the specific part of that process that updates this package is very slow. It did eventually finish though...

**Comment by pllim** [comment]
@s2t2 , thanks for the clarification but not sure what we can do here as that is conda resolver algorithm and is out of our control.
