### ISSUE TITLE
Support vstack of Quantity columns

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#4599]
Prompted by email on astropy-dev, this is a reminder to provide support for vstack of Quantity columns in a QTable.

**Comment by astrofrog** [comment]
@taldcroft - this missed 1.2 unfortunately, but I'm adding the 1.3 milestone to make sure we do it for that

**Comment by mhvk** [comment]
Feature requests are probably best milestoned as "Future" until someone is actually assigned to do it... Removing this from 1.3.

**Comment by mhvk** [comment]
Should be fixed by #5811

**Comment by mhvk** [comment]
closing since fixed by #5841
