### ISSUE TITLE
'Config' object has no attribute '_conftest'

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#4607]
Following on https://github.com/astropy/astropy/issues/4256#issuecomment-183411214 and https://github.com/astropy/astropy/pull/4349, I'm still seeing issues with conftest.  I can reproduce this on one of my own computers, but not another.  The [error](https://travis-ci.org/keflavich/image_registration/jobs/109002223#L575):

```
==================================== ERRORS ====================================
_____ ERROR collecting lib.linux-x86_64-2.7/image_registration/conftest.py _____
/home/travis/miniconda/envs/test/lib/python2.7/site-packages/astropy/tests/pytest_plugins.py:120: in collect
    module = self.config._conftest.importconftest(self.fspath)
E   AttributeError: 'Config' object has no attribute '_conftest'
==================== 9458 passed, 1 error in 31.27 seconds =====================
```

**Comment by astrofrog** [comment]
@keflavich - are you using the latest master? I don't see that line on line 120 of ``pytest_plugins.py``, so I'm wondering if somehow you are still using an old astropy version?

**Comment by keflavich** [comment]
...strange, this is happening on .travis.  Maybe the wrong version is being installed?

**Comment by astrofrog** [comment]
In the header, it says ``Running tests with Astropy version 1.0.4.``

**Comment by astrofrog** [comment]
And I suspect your ``runtests.py`` script was generated from a recent py.test

**Comment by astrofrog** [comment]
@keflavich - why not use the normal ``python setup.py test`` mechanism for affiliated packages which uses the bundled py.test from astropy?

**Comment by keflavich** [comment]
....am I not?  that's not intentional; I thought I had copied that from package-template

**Comment by astrofrog** [comment]
@keflavich - the setup.py file is very different to the package template, and uses ``runtests.py`` to run the tests rather than the command provided by the astropy-helpers. I think you aren't using astropy-helpers at all?

**Comment by keflavich** [comment]
are you looking at the py3 branch?

**Comment by astrofrog** [comment]
Ah no sorry. Will look again at that branch later.

**Comment by astrofrog** [comment]
@keflavich - somehow it's using a recent version of pytest, not the version bundled with astropy 1.0.4. Try removing ``pytest`` from ``CONDA_DEPENDENCIES``

**Comment by keflavich** [comment]
aha, that's probably it!  Thanks @astrofrog - I'll close this if it fixes the issue.   That also (kind of) explains why I can reproduce the problem on some but not all machines.

**Comment by keflavich** [comment]
This is the version being used:
https://travis-ci.org/keflavich/image_registration/jobs/109145825#L489

it looks like it  is a too-recent version, but I don't know why.

**Comment by astrofrog** [comment]
@keflavich - not sure, but it shouldn't matter in the end, if you always use the bundled one internally in your package (the installed pytest shouldn't be getting used)

**Comment by keflavich** [comment]
@astrofrog ok - any ideas why `python setup.py test` is not using the bundled internal variant?

**Comment by astrofrog** [comment]
@keflavich - I'll look into it :)

**Comment by astrofrog** [comment]
@keflavich - I can't reproduce the issue locally... very strange!

**Comment by keflavich** [comment]
@astrofrog - the issue is resolved by doing `from astropy.tests.helper import pytest` instead of `import pytest`:
https://github.com/keflavich/image_registration/pull/8
now the remaining failures on that issue are just normal python3 migration bugs.

**Comment by bsipocz** [comment]
Is that right that this makes any testing that uses LTS incompatible with pytest3? 

E.g. for astroquery we need pytest3 to get the python3.6 builds pass (due to a pytest/unittest issue mentioned in #5917): https://travis-ci.org/astropy/astroquery/jobs/216084609
