### ISSUE TITLE
verblevel keyword of SLSQPLSQFitter() unrecognized

### ISSUE THREAD

**Issue by neilzim** [astropy/astropy#4611]
In modeling.fitting, the documentation for **SLSQPLSQFitter()** specifies a **verblevel** keyword argument to control the level of console output:

> 0-silent 1-print summary upon completion, 2-print summary after each iteration

However, when **SLSQPLSQFitter()** passes this keyword on to scipy's **fmin_slsqp()**, as in

`fit_ellipse = fitting.SLSQPLSQFitter()`
`ellipse_sol_try1 = fit_ellipse(ellipse_init, xx, yy, thresh_map, verblevel=0, epsilon=0.5)`

will trip an error since the keyword is unrecognized by fmin_slsqp(). Looking up the fmin_slsqp() interface, the correct keyword to set the verbosity level is **disp**:
[http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.fmin_slsqp.html](http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.fmin_slsqp.html)

It appears that in at least one old astropy version (v0.3), verblevel was handled properly, since it initializes an intermediate parameter named disp. This coversion to give fmin_slsqp() the disp keyword seems to have been dropped.

In any case, one can get the expected behavior by using the disp keyword directly in the caller:
`ellipse_sol_try1 = fit_ellipse(ellipse_init, xx, yy, thresh_map, disp=0, epsilon=0.5)`

**Comment by pllim** [comment]
@embray ?
