### ISSUE TITLE
Add table functionality to remove duplicate rows

### ISSUE THREAD

**Issue by evertrol** [astropy/astropy#4617]
I'd like to suggest functionality to remove duplicate rows from a Table, similar to Pandas' [`drop_duplicates`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop_duplicates.html).

This would *not* be the same functionality as `table.operations.unique`. In particular, I'd like to have the `keep=False` option that Pandas has: remove *all* rows from a table if they are duplicates (so only rows that have no duplicate in the original table are left). 
A use case for this would be rows where filtering on one key results in duplicates, but including a related key (which should be the same for duplicates) doesn't not result in duplicates, thus indicating an error. All duplicate rows should then be removed if there is no way to trace back the original.

Just like `unique`, this would be a convenience function using grouping functionality.
A basic implementation could look like (not thoroughly tested):

    grouped_table = table.group_by(keys)
    if keep == 'first':
        cleaned_table = grouped_table[grouped_table.groups.indices[:-1]]
    elif keep == 'last':
        cleaned_table = grouped_table[grouped_table.groups.indices[1:]-1]
    else:
        cleaned_table = vstack([table for table in grouped_table.groups if len(table) == 1])
(anything else would be the same as for `unique`.)

Any thoughts on this?

As an aside: would it be an option to have `unique` and optionally `remove_duplicate_rows` as methods to `Table`? In which case there may be reason to have an `inplace` keyword.

**Comment by pllim** [comment]
See #4632

**Comment by taldcroft** [comment]
Closed by #4632.
