### ISSUE TITLE
error message converting to/from dimensionless_unscaled unit

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4621]
Today I got the error

```
>>> u.dimensionless_unscaled.to(u.m)
UnitConversionError: '' (dimensionless) and 'm' (length) are not convertible
```

which is perfectly fine but the error message is a bit strange ``''`` is the representation of ``dimensionless_unscaled``? I also noticed ``u.dimensionless_unscaled.to_string()`` returns ``''``. Would it be possible to somehow give dimensionless_unscaled some kind of string-representation that isn't printed when printing a dimensionless_unscaled quantity like ``a=5*u.dimensionless_unscaled``?

**Comment by pllim** [comment]
Personally, I am against changing the definition of `u.dimensionless_unscaled` at this point. As a `units` user myself, I am used to `''` being `u.dimensionless_unscaled`. And I have seen people use `Unit('')` to define it in their codes.

**Comment by mhvk** [comment]
@MSeifert04 - Looking through old unit issues, I came across this one. My sense echoes @pllim -- that by now it is a bit too late to change. Also, any implementation seems tricky and possibly confusing.  So, I'll close this.  But for your amusement: check this [TODO](https://github.com/astropy/astropy/blob/master/astropy/units/quantity.py#L1004).
