### ISSUE TITLE
zest.releaser hooks should be limited to astropy

### ISSUE THREAD

**Issue by reinout** [astropy/astropy#4633]
I'm the author of zest.releaser and recently an issue got posted: https://github.com/zestsoftware/zest.releaser/issues/168

Basically, someone released his own package and got bitten by a zest.releaser hook from astropy. Something wrong with python 2/3 unicode/str types.

I assume the astropy hook is only meant for releasing astropy itself? In that case you could do something like at the top of your entry point function https://github.com/zestsoftware/zest.releaser/blob/6.6.2/zest/releaser/preparedocs.py#L16

    if data['name'] != 'astropy':
        # We're available everywhere, but we're only intended for
        # astropy internal usage.
        return

Would that make sense? (Or otherwise, could you look at https://github.com/zestsoftware/zest.releaser/issues/168 to see if there's something else?)

**Comment by eteq** [comment]
@reinout - Oh, interesting - didn't realize this sort of conflict might come up.  I think the quick fix you suggested here is probably the path of least resistance at least for now - we'll try to get that into the next maintenance releases.

**Comment by eteq** [comment]
OK, I think #4650 should fix this, @reinout.  Looks to me like it was just an oversight.

**Comment by reinout** [comment]
Thanks! I'll close the issue right away.
