### ISSUE TITLE
Should Table(rows=...) preserve column order if using OrderedDicts?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4667]
When initializing a table with `Table(rows=...)`, if the first item is an OrderedDict, should we preserve the column order? For instance:

``` python
In [1]: from astropy.table import Table

In [2]: from collections import OrderedDict

In [3]: row = OrderedDict()

In [4]: row['b'] = 1

In [5]: row['a'] = 0

In [6]: row
Out[6]: OrderedDict([('b', 1), ('a', 0)])

In [7]: t = Table(rows=[row])

In [8]: t
Out[8]: 
<Table length=1>
  a     b  
int64 int64
----- -----
    0     1
```

**Comment by taldcroft** [comment]
The example certainly seems like unexpected behavior, so I'd be open to changing it.  The first issue is whether there is a better way than simple type checking for `OrderedDict` subclasses.  The second is that this will be an API change as well, so we have to careful about it.  I guess in general users that have previously been accepting alphabetical column ordering are somewhat unlikely to actually care about order, but you never know...

**Comment by taldcroft** [comment]
cc @adrn

**Comment by astrofrog** [comment]
> And maybe in Python 3.7 all normal dict will be guaranteed by the language to retain the order

My understanding of this was actually that this would only be the case for dictionaries made from ``**kwargs`` but not *all* dictionaries.

I personally think checking the first row as a special case would already be better than the current behavior.

**Comment by taldcroft** [comment]
> My understanding of this was actually that this would only be the case for dictionaries made from **kwargs but not all dictionaries.

The CPython implementation of `dict` in 3.6 is actually ordered, but that they don't guarantee it as part of the language and one should not count on it in the future.  Empirically `dict` is now ordered in 3.6, but not in previous versions:
```
In [1]: from random import randint
In [2]: b = list(set([randint(1, 10000000000) for _ in range(10000)]))
In [3]: a = {k: k*2 for k in b}
In [4]: list(a) == b
True
```
See also: https://stackoverflow.com/questions/39980323/dictionaries-are-ordered-in-python-3-6

So sadly we can't use this in production code for a while.

**Comment by taldcroft** [comment]
> I personally think checking the first row as a special case would already be better than the current behavior.

It sounds like you don't buy my argument about (1) keeping the behavior predictable and (2) explicit vs. implicit.  Hmm.

**Comment by astrofrog** [comment]
In my view, if someone is using an ordereddict, it is probably a deliberate choice, hence why I was arguing for this special case. I doubt anyone will read the docs close enough to find ``t = Table(rows=rows, names=list(rows[0]))``, even though I agree it's the most explicit solution.

**Comment by taldcroft** [comment]
OK, I see your point.  It should be an easy patch so if someone writes this I would approve.

**Comment by broulston** [comment]
@taldcroft @astrofrog is this still an issue? If so I’d like to work on it!

**Comment by bsipocz** [comment]
To me it still looks like an issue.
