### ISSUE TITLE
inconsistency after deleted columns

### ISSUE THREAD

**Issue by Doidel** [astropy/astropy#4674]
I noticed after deleting some columns from a FITS_rec (e.g. `v.columns.del_col('SIGAMP')`) there are some inconsistency issues in FITS_rec:

```
def __setitem__(self, key, value):
        ...
        if isinstance(value, FITS_record):
            for idx in range(self._nfields):
                self.field(self.names[idx])[key] = value.field(self.names[idx])
```

Here `self.dtype.names` and `self._nfields` still have the original (deleted) column names, while `self.names` doesn't. This leads to an error in the above code (out of bounds) when `idx` grows larger than `self.names`.

I haven't checked whether this issue also appears in other occasions.

Thanks and kind regards

**Comment by pllim** [comment]
Hi. Using the latest dev version, can you provide a code snippet of an example usage that encountered this? Thanks.

**Comment by Doidel** [comment]
Yes, I uploaded a zip containing the code and a fits file here: http://www.filedropper.com/testcasedelcolumns_1
or, alternatively, here is the code snippet alone:
```
from __future__ import print_function
from astropy.io import fits

if __name__ == "__main__":
    hdu_list = fits.open('visibilitybag_photon.fits', memmap=False)
    v = hdu_list[1].data

    v.columns.del_col('HARM')
    v.columns.del_col('SIGAMP')
    v.columns.del_col('TYPE')
    v.columns.del_col('UNITS')
    v.columns.del_col('ATTEN_STATE')
    v.columns.del_col('COUNT')

    #vislist._nfields = len(vislist.names)  # workaround for FITS_rec bug, https://github.com/astropy/astropy/issues/4674
    ##vislist.dtype.names = tuple(vislist.names)

    # For demonstrating purposes: Replacing last FITS_record with first FITS_record
    v[len(v) - 1] = v[0]
```

**Comment by saimn** [comment]
Closing in favor of #3647
