### ISSUE TITLE
Test failures with numpy 1.11 and up

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#4677]
Currently, tests with 1.11 fail some of the table info tests because of a behaviour in how "object" arrays are treated by numpy, in particular what it means to do `np.sum(time-array)`. See https://github.com/numpy/numpy/issues/7393

**Comment by eteq** [comment]
It looks to me like numpy/numpy#7393 is fixed now - so can we close this?  (Not sure where you saw the failing tests, @mhvk)

**Comment by mhvk** [comment]
Yes, the 1.11 problems are fixed, so closing (I saw the failures when looking at `dev` and realised they were in 1.11 as well; still some failures in `dev` remaining...).
