### ISSUE TITLE
Make modeling render function convert to float

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#4681]
As first mentioned in https://github.com/astropy/astropy/pull/4570#issuecomment-188304005, the `render` function doesn't convert to float like evaluating a model does.  @patti indicated in in https://github.com/astropy/astropy/pull/4570#issuecomment-188399531 that this was an oversight and should be fixed, so this is a reminder to do that.

I'm currently tagging it as 1.2, as this is nominally a behavior change.  But I'm open to being convinced that this is actually a "bug" if others think that's more appropriate.

cc @nden  @patti

**Comment by aniketmkulkarni** [comment]
@eteq I'd like to work on this. Can you give me a starting point on this problem?

**Comment by eteq** [comment]
Well, first make sure you understand the issue as posed in https://github.com/astropy/astropy/pull/4570#issuecomment-188304005 and answered in https://github.com/astropy/astropy/pull/4570#issuecomment-188399531 .  Based on that, I *think* the key is just to convert the inputs to the ``render`` function to be ``float`` (using the ``astype`` numpy method).  But @patti might have more insight?

**Comment by aniketk21** [comment]
@eteq I'm a little confused about this issue. @patti can you provide more insight to it?

**Comment by patti** [comment]
@aniketk21 Yep, it should be a quick fix. We need to make sure both the inputs and parameters are converted to `float`, e.g. [core.py#L1429](https://github.com/astropy/astropy/blob/master/astropy/modeling/core.py#L1429) and [core.py#L1207](https://github.com/astropy/astropy/blob/master/astropy/modeling/core.py#L1207).

**Comment by pkrskr** [comment]
Hi,

I see that @aniketk21 also worked on this issue and solved it, although it is still showing as open. I'm new to Astropy and trying to contribute. I worked on this issue as it was basic enough for me to get an idea of the workflow. After updating the code, I checked that the tests in [#4570](https://github.com/astropy/astropy/pull/4570#issuecomment-188304005) are working correctly and also confirmed that astropy.test('modeling') works fine. I wonder why the Travis build fails with an Unsupported Locale Error for Python 2.7 though.

**Comment by aniketk21** [comment]
@pkrskr, @patti and @eteq haven't reviewed my code yet, so it is showing as open.
Regarding the `Unsupported Locale Error`, many PRs are failing Travis CI builds with this error.
See: #4710 #4711 #4702

**Comment by pkrskr** [comment]
@aniketk21 Thanks for letting me know! The error did seem like something not related to the changes I made. I'll look at some other issues I can contribute to now.

**Comment by nden** [comment]
Fixed in #4681.
