### ISSUE TITLE
astropy_helpers not found in offline mode

### ISSUE THREAD

**Issue by eatdust** [astropy/astropy#4685]
Hi there,
astropy-1.1.2 does not build/install in offline mode due to the above mentioned error. In other words, that bug prevent its packaging on all linux distro :-/

Thanks!
cheers,
Chris.

---

python ./setup.py --offline install
Cannot initialize the astropy_helpers submodule in --offline mode; this requires being able to clone the submodule from an online repository.

If the problem persists consider installing astropy_helpers manually using pip
(`pip install astropy_helpers`) or by manually downloading the source archive,
extracting it, and installing by running `python setup.py install` from the
root of the extracted source code.

[chris@cp3wks01 astropy (master)]$ python ./setup.py --offline build
Cannot initialize the astropy_helpers submodule in --offline mode; this requires being able to clone the submodule from an online repository.

If the problem persists consider installing astropy_helpers manually using pip
(`pip install astropy_helpers`) or by manually downloading the source archive,
extracting it, and installing by running `python setup.py install` from the
root of the extracted source code.

**Comment by astrofrog** [comment]
@eatdust - I think you also have to include the ``--no-git`` option. Arguably (I think we've discussed this in the past), ``--no-git`` should be the default in ``--offline`` mode. Can you confirm whether adding ``--no-git`` helps?

**Comment by eatdust** [comment]
Yes, Thank you!!!
There is still something weird as that message still shows up with --offline --no-git if one removes:
astropy.egg-info
and:
[build]
use_system_libraries=1

But provided I do not remove eggs, compilation goes fine [astropy-1.1.2 is landing on mageia 6 :)]
Cheers.

**Comment by astrofrog** [comment]
@eatdust - thanks for packaging astropy for mageia!

i'm not 100% sure why the egg-info file is needed, but this is related to https://github.com/astropy/astropy-helpers/issues/221

cc @eteq

**Comment by jamienoss** [comment]
Hi all,
Is this not a case of lacking documentation leading to user error? I would have thought the [Obtaining the source packages](https://github.com/astropy/astropy/blob/master/docs/install.rst#obtaining-the-source-packages) section of `docs/install.rst` should include the command `git submodule update --init --recursive`. I understand that the bootstrapper does this for you (without the --recursive), however,  perhaps you don't wish to build at all but just want to navigate the src. Trying to build without a complete src tree is only one step away from doing so without the clone, i.e. having none of the source at all. Users unfamiliar with git may not be aware of submodules at all, I think this should be in the docs.
_c.f._ #6975

**Comment by jhunkeler** [comment]
Changing the current clone command in the documentation to `git clone --recursive git://github.com/astropy/astropy.git` initializes all submodules in the project automatically.

* `--recursive` appeared in `git-1.6.5` (2009/10/10)
* `--recurse-submodules` appeared in `git-1.7.5` (2011/04/23)

In `git >=1.7.5` the `recursive` flag is aliased internally to `recurse-submodules`.

**Comment by mhvk** [comment]
This seems like a very small addition that will save people pain later; any takers for making a quick PR to the docs?

**Comment by bsipocz** [comment]
#7009 addressed the documentation need here, I don't think we can do much more.

Reopen in the helpers repo if you think otherwise.
