### ISSUE TITLE
axis argument in mad_std

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#4688]
An axis argument should be added to mad_std in astropy.stats

**Comment by astroferreira** [comment]
Is there anyone already looking forward to solve this? If not, I could go for it.

**Comment by crawfordsm** [comment]
It's unclaimed so far, so please feel free to submit a pull request

**Comment by MSeifert04** [comment]
@crawfordsm - This can be closed since #4688 is merged.

**Comment by pllim** [comment]
I think so, but feel free to reopen if you feel otherwise.

p/s: I think there is a need to add a `mad_max()` function.

**Comment by crawfordsm** [comment]
+1 :)
