### ISSUE TITLE
Jinja2 undeclared as dependency on Astropy installation page

### ISSUE THREAD

**Issue by sharadmirani** [astropy/astropy#4704]
I get the following error while trying to compile Astropy on an Ubuntu 14.04 machine:

   Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
   Freezing version number to astropy/version.py
   running build
   running build_py
   running pre_hook from astropy.modeling.setup_package for build_py command
   pre_build_py_hook command hook build_py raised an exception: %s
   
   Traceback (most recent call last):
     File "/home/nouser/dev/astropy/astropy_helpers/astropy_helpers/setup_helpers.py", line 289, in run_command_hooks
       hook_obj(cmd_obj)
     File "astropy/modeling/setup_package.py", line 61, in pre_build_py_hook
       preprocess_source()
     File "astropy/modeling/setup_package.py", line 111, in preprocess_source
       from jinja2 import Environment, FileSystemLoader
   ImportError: No module named jinja2

I guess jinja2 should be included as a non-strict dependency here: http://docs.astropy.org/en/stable/install.html

**Comment by astrofrog** [comment]
@sharadmirani - it is currently listed in the section on building from source:

http://docs.astropy.org/en/stable/install.html#prerequisites

The jinja2 requirement only applies to developer versions, not stable versions.

**Comment by sharadmirani** [comment]
@astrofrog Also, while trying to compile Astropy from source, I get the following error

Error compiling Cython file:
------------------------------------------------------------
...
    char *next_field(tokenizer_t *self, int *size)
    char *get_line(char *ptr, int *len, int map_len)
    void reset_comments(tokenizer_t *self)

cdef extern from "Python.h":
    int PyObject_AsReadBuffer(object obj, const void **buffer, Py_ssize_t *buffer_len)
                                                    ^
------------------------------------------------------------

astropy/io/ascii/cparser.pyx:96:53: Expected ')', found '**'
building 'astropy.io.ascii.cparser' extension
creating build/temp.linux-i686-2.7/astropy/io/ascii
creating build/temp.linux-i686-2.7/astropy/io/ascii/src
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c astropy/io/ascii/cparser.c -o build/temp.linux-i686-2.7/astropy/io/ascii/cparser.o -Wp,-w -Wno-unused-function
astropy/io/ascii/cparser.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1

My setup is an Ubuntu 14.04 PC with Cython v0.15.1. What could be the issue here?

**Comment by sharadmirani** [comment]
@astrofrog Also, while trying to compile Astropy from source, I get the following error

```
Error compiling Cython file:
------------------------------------------------------------
...
    char *next_field(tokenizer_t *self, int *size)
    char *get_line(char *ptr, int *len, int map_len)
    void reset_comments(tokenizer_t *self)

cdef extern from "Python.h":
    int PyObject_AsReadBuffer(object obj, const void **buffer, Py_ssize_t *buffer_len)
                                                    ^
------------------------------------------------------------

astropy/io/ascii/cparser.pyx:96:53: Expected ')', found '**'
building 'astropy.io.ascii.cparser' extension
creating build/temp.linux-i686-2.7/astropy/io/ascii
creating build/temp.linux-i686-2.7/astropy/io/ascii/src
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c astropy/io/ascii/cparser.c -o build/temp.linux-i686-2.7/astropy/io/ascii/cparser.o -Wp,-w -Wno-unused-function
astropy/io/ascii/cparser.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1
```
My setup is an Ubuntu 14.04 PC with Cython v0.15.1. What could be the issue here?

**Comment by astrofrog** [comment]
@sharadmirani - I think it might be a Cython version issue - can you try upgrading to see if that helps? I think we might have to raise our minimum required version of Cython.

**Comment by astrofrog** [comment]
Cython 0.19+ is now required. I opened an issue here: https://github.com/astropy/astropy/issues/4705
