### ISSUE TITLE
Update required version of Cython in installation docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4705]
It looks like Astropy dev now requires Cython >= 0.19 to build (up from 0.15 previously), so this needs to be updated in the installation docs. Leaving this as an easy issue in case anyone is interested in practicing the workflow.

@taldcroft - this appears to be due to the Cython code in ``io.ascii`` - updating the minimum required version is fine, right?

**Comment by pkrskr** [comment]
Hi,
I'm new to Astropy and trying to contribute. This seems like a small issue that would get me introduced to the workflow. I shall try and add the update to the installation files. Let me know if there's something specific I must do.

**Comment by kvyh** [comment]
If this is still outstanding, I will try to solve it.

**Comment by bsipocz** [comment]
@kvyh - There are already two PRs to solve this issue, you can see the references for them above your comment.

**Comment by eteq** [comment]
This was resolved by the combination of #4710 and #4719
