### ISSUE TITLE
Make Shift and Scale models fittable

### ISSUE THREAD

**Issue by nden** [astropy/astropy#4718]
There's no reason the `Shift` and `Scale` models should not be fittable.
Set the the `fittable` attribute to `True`.
(Good for a first github PR.)

**Comment by Cadair** [comment]
Should this be labelled `package-novice`?

**Comment by nden** [comment]
Thanks @Cadair. I was looking for the right label and missed it.

**Comment by pkrskr** [comment]
I suppose this comes down to just adding the fittable attribute (as True) in the definition of the Scale and Shift models?

**Comment by pllim** [comment]
Also please add tests and change log.

**Comment by pkrskr** [comment]
Okay, can you help me understand how tests are to be added?

**Comment by pkrskr** [comment]
I just found this [test-guide](http://docs.astropy.org/en/stable/development/testguide.html). Will follow the guidelines described there.

**Comment by pkrskr** [comment]
Please find the fix for this here: #4721
