### ISSUE TITLE
setting header_start when reading commented ascii files skips real data

### ISSUE THREAD

**Issue by karllark** [astropy/astropy#4728]
When reading a commended_header ASCII file with the Table.read command and header_start set to a non-zero value, a header_start number of data lines are skipped.  This results in less data than expected in the resulting table object.  Currently, the solution is to set explicitly set 'data_start=0'.  It makes more sense if data_start=0 is the default behavior instead of data_start=header_start.

pseudo code:
from astropy.table import Table

filename = ascii file with 10 comment lines where the column names are given on the last
   comment line (e.g. line 10)

this results in a table that is missing the first 9 lines of data

Table.read(filename, format="ascii.commented_header", header_start=9)

this results in a table that has all the expected data (no skipped data lines)

Table.read(filename, format="ascii.commented_header", header_start=9, data_start=0)

**Comment by pllim** [comment]
@karllark , can you please provide a snippet of the table, or attach the file here? Or provide a link to the data file?

**Comment by karllark** [comment]
Here is a file that should reproduce the issue.

http://www.stsci.edu/~kgordon/tmp.dat

**Comment by pllim** [comment]
Thanks, @karllark .

c/c @taldcroft

**Comment by taldcroft** [comment]
@karllark - which version of astropy are you using?  I cannot reproduce using master or 1.1.  I think this should have been fixed in https://github.com/astropy/astropy/pull/3054.

**Comment by taldcroft** [comment]
@karllark reports that he was using an older version.  Closing.
