### ISSUE TITLE
astropy.io.fits.FITS_record.setfield does not work as expected (astropy version 1.1.2-1)

### ISSUE THREAD

**Issue by mauriceleutenegger** [astropy/astropy#4732]
According to the online documentation, 
http://docs.astropy.org/en/stable/io/fits/api/tables.html,
the expected calling syntax is:
setfield(field, value)

But according to the help file for the installed library:
setfield(...)
    a.setfield(val, dtype, offset=0)
which is the syntax specified in the numpy record array documentation. 

The documentation for the installed library correctly documents the behavior of the function, while the online documentation is not correct.

This numpy version of setfield is usable in principle, but it requires the user to know about the structure of the FITS_record array, instead of simply naming the field the user would like to modify. The function would be more useful if it behaved as in the online documentation.

**Comment by pllim** [comment]
Not sure if I understand. FITS record is not equivalent to Numpy.

**Comment by bsipocz** [comment]
Also please note @mauriceleutenegger that the preferred way to manipulate fits table data is though the Table package and not via the FITS record.

**Comment by saimn** [comment]
I think there is a confusion between the `FITS_record` and `FITS_rec` classes:

- When you read a FITS table you get a `FITS_rec` object, which inherits from `np.recarray`. `FITS_rec` does not redefine `setfield` so it inherits this method from `recarray`, with the `a.setfield(val, dtype, offset=0)` signature. And as it is inherited, this method is not present in Astropy's documentation.

- If you get a row from this table, you then get a `FITS_record` object, which does not inherit from `recarray` but also provide a `setfield` method with a slightly different signature (`setfield(field, value)`). This is the one you see in the docs.

**Comment by pllim** [comment]
Yeah, that makes sense now. Thanks, @saimn !

**Comment by mauriceleutenegger** [comment]
@saimn : Thanks for the clarification - I was indeed confusing the behavior of <code>FITS_record</code> and <code>FITS_rec</code>.

@bsipocz : I agree that Table provides a better way to accomplish the equivalent operation:
<code>mytable.replace_column ('column_name', new_values)</code>

Thanks for your help!

**Comment by pllim** [comment]
Okay, closing this.
