### ISSUE TITLE
Problem with compound models using AiryDisk2D

### ISSUE THREAD

**Issue by jenniferyee** [astropy/astropy#4752]
Hi,

(re-post from the astropy mailing list. Response below.)

I am trying to fit a PSF with an Airy function. If I use AiryDisk2D alone,
it works fine, but if I try to create a compound model, for example a
constant+AiryDisk2D, the compound model cannot be evaluated because it has
"no attribute _rz". Is this a bug? Does anyone know how to fix it? (Note I
have no problems creating compound models with Gaussian2D).

Example code and full error message below.

python version: 2.7.5
numpy version:  1.10.4
astropy version:  1.1.2

Thanks,

Jennifer

EXAMPLE CODE:

from astropy.modeling import models

class Airy_with_Background(models.Const2D+models.AiryDisk2D):
    pass

x,y = np.mgrid[:200,:200]
airy_init = Airy_with_Background()
airy_init(x,y)

ERROR MESSAGE:

Traceback (most recent call last):
  File "test_airy.py", line 20, in <module>
    airy_init(x,y)

  File "/Path/lib/python2.7/site-packages/astropy/modeling/core.py", line
407, \
in __call__
    __call__, args, [('model_set_axis', None)])

  File "/Path/lib/python2.7/site-packages/astropy/modeling/core.py", line
403, \
in __call__
    return super(cls, self).__call__(*inputs, **kwargs)

  File "/Path/lib/python2.7/site-packages/astropy/modeling/core.py", line
708, \
in __call__
    outputs = self.evaluate(*chain(inputs, parameters))

  File "/Path/lib/python2.7/site-packages/astropy/modeling/core.py", line
2514,\
 in evaluate
    return self.__class__.evaluate(*args)

  File "/Path/lib/python2.7/site-packages/astropy/modeling/core.py", line
1997,\
 in evaluate
    result = cls._evaluate(inputs, params)

  File "/Path/lib/python2.7/site-packages/astropy/modeling/utils.py", line
448,\
 in <lambda>
    g(inputs, params)))

  File "/Path/lib/python2.7/site-packages/astropy/modeling/core.py", line
2438,\
 in <lambda>
    (evaluate(*chain(inputs, islice(params, n_params))),)

  File
"/Path/lib/python2.7/site-packages/astropy/modeling/functional_models.py\
", line 1622, in evaluate
    r = np.sqrt((x - x_0) ** 2 + (y - y_0) ** 2) / (radius / cls._rz)

AttributeError: type object 'AiryDisk2D' has no attribute '_rz'
-----------------------

Hi Jennifer,

Could you file an issue on github.
AiryDisk2D defines one of the class attributes inside the __init__ function.
This was done to work around a problem with older versions of scipy and python3.
Perhaps drop support for those older versions.

Meanwhile if you don't have to inherit from the model classes you can do something like

model = Const2D() + AiryDisk2D()

and evaluate and fit this model.

Cheers,
Nadia

**Comment by pllim** [comment]
@larrybradley ?

**Comment by larrybradley** [comment]
@pllim This is simply a repost from the astropy mailing list.

@jenniferyee Thanks again for reporting this.  I fixed this issue in #4720.  The fix will appear in the next Astropy release (`1.1.3`).  If you want to use it now, you'll have to install Astropy from the latest git master.

**Comment by pllim** [comment]
A'right, a'right, a'right! Closing.
