### ISSUE TITLE
Parse a votable with missing 'datatype' attribute?

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#4755]
The following votable:
http://simbad.u-strasbg.fr/simbad/sim-script?submit=submit+script&script=votable+test1+%7BMAIN_ID+rv_value+rvz_error+%7D%0D%0Avotable+open+test1%0D%0Aquery+id+BD%2B44+4548%0D%0Aquery+id+*+eta+car%0D%0Avotable+close

truncates the `RVZ_ERROR` column to 1 character.  This is happening because the line
```
<FIELD ID="RVZ_ERROR" name="RVZ_ERROR" precision="3" unit="km.s-1">
```

gets parsed into
```
<FIELD ID="RVZ_ERROR" arraysize="1" datatype="char" name="RVZ_ERROR" precision="3" unit="km / s"/>
```

i.e., only 1 character is being read.  The "correct" data type is `float`.  So, two questions:
 * Is this a correctly specified VOTable, and astropy is making an incorrect default assumption?  Or is the votable invalid?
 * Given that such votables exist, is there a way to correctly parse them in astropy?

Actually, I can now answer the first.  From the [VOTable specifications](http://www.ivoa.net/documents/VOTable/20130920/index.html), section 4.1:
```
• The datatype, which expresses the nature of the data that is described as one of the permitted primitives (see Table 1 and their exact meaning in section 6). This attribute determines how data are read and stored internally; it is required.
```
so unless the default data type is floating point (it doesn't seem to be), the table is incorrectly specified.

**Comment by pllim** [comment]
There is a `volint` command you can use to see if the VO table is valid. In this case, it is not. Particularly, see the `E10` line:

```html
$ volint your_vo_table.xml 
Validation report for ...

3: W22: The DEFINITIONS element is deprecated in VOTable 1.1.
  Ignoring
<DEFINITIONS>
^

4: W27: COOSYS deprecated in VOTable 1.2
<COOSYS ID="COOSYS" equinox="2000" epoch="J2000" system="ICRS"/>
^

15: E10: 'datatype' attribute required on all 'FIELD' elements
<FIELD ID="RVZ_ERROR" name="RVZ_ERROR" precision="3" unit="km.s-1">
^

15: W47: Missing arraysize indicates length 1
<FIELD ID="RVZ_ERROR" name="RVZ_ERROR" precision="3" unit="km.s-1">
^

20: W46: char value is too long for specified length of 1
<TR><TD>BD+44  4548</TD><TD>-0.39</TD><TD>0.09</TD></TR>

```

**Comment by astrofrog** [comment]
@keflavich - I would recommend first contacting the CDS folk to report this issue, and I would be against including workarounds in Astropy unless there is really no way it can be fixed upstream.

**Comment by astrofrog** [comment]
I'm going to ping @tboch in case he can point the relevant CDS developers to this issue.

**Comment by keflavich** [comment]
Sorry, I should have mentioned - this has already been reported to CDS.

**Comment by keflavich** [comment]
The Simbad-specific issue has been fixed upstream, thanks to quick support from CDS.

**Comment by astrofrog** [comment]
Ok, great! Let's close this since the workaround is no longer needed (and we should keep workarounds to a minimum)
