### ISSUE TITLE
Emphasize NDDataArray in user docs?

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#4756]
I think that most users (as opposed to developers) who are looking in the NDData documentation are actually looking for the `NDDataArray` class.  The current `NDData` object and docs seem largely aimed at developers instead of typical users.  

As someone who hasn't worried much about `NDData` (for lack of personal need), I was surprised the Getting Started docs do not start with a simple _useful_ example like reading a generic FITS image (with or without WCS), plotting it, modifying a keyword, modifying some pixel values, and writing back to file.  In reading the docs I initially got the impression that the only way to do this was to define my own class with the appropriate mixins.  There is just one reference to `NDDataArray` in the docs, offered almost as an aside.  

Part of this is to continue pushing the idea of the unified I/O interface where the data file format (e.g. FITS or HDF5) is not emphasized so much as the data object (Table or NDData).

So what about starting the Getting Started with a section which is the most common use case that utilizes `NDDataArray`, and then perhaps using `NDDataArray` in more of the subsequent examples where it might make sense.  Or perhaps explicitly split into Basic Usage and Developer Usage sections?

**Comment by mwcraig** [comment]
Goal is to get a PR open to address by Monday evening...

**Comment by mwcraig** [comment]
Also, this PR is relevant: #6173
