### ISSUE TITLE
Error in unit conversion from solar masses to kg

### ISSUE THREAD

**Issue by iw381** [astropy/astropy#4763]
It seems that the unit conversion from solar masses has a wrong factor of 10^6.
`u.MsolMass.to(u.kg)` results in `1.9891e+36` instead of 1.9891e+30.

**Comment by pllim** [comment]
That is because you prepended the `M` (mega) to the unit. The correct way is:

```python
>>> u.solMass.to(u.kg)
1.9891e+30
```

**Comment by pllim** [comment]
If that solves your problem, please close this issue. Thanks!

**Comment by iw381** [comment]
Oh yeah, that was stupid! Sorry for that...
Thanks!

**Comment by pllim** [comment]
@iw381 , no worries. The `M` is easy to miss.

**Comment by archer81** [comment]
Hi! I have a similar query on this unit. 

I converted it to cgs unit with other units (solMass, M_sun).
![image](https://cloud.githubusercontent.com/assets/4904478/20690265/d31532f8-b60c-11e6-95cc-a2c911350860.png)

As you can see this figure, the difference in numbers does not differ by 10^6.

Could you please check the value of u.msolMass?
