### ISSUE TITLE
wcslint makes suggestion that will produce non-spec FITS file

### ISSUE THREAD

**Issue by demitri** [astropy/astropy#4765]
I recently came across [this page](http://docs.astropy.org/en/stable/wcs/#validating-the-wcs-keywords-in-a-fits-file) that notes `wcslint` reports:

```
- RADECSYS= 'ICRS ' / Astrometric system
  RADECSYS is non-standard, use RADESYSa.
```

The FITS specification does not allow lowercase letters in keywords. `wcslint` should be updated to not make this recommendation.

**Comment by astrofrog** [comment]
I think the a is more of a wildcard here? I think this should actually say ``RADESYS or RADESYSa`` though. Or maybe ``RADESYS (optionally with a WCS key as suffix)``

**Comment by demitri** [comment]
I was reading a message from someone that alerted me to this, and they took it literally (which is understandable). The 'a' was converted to 'A', which, while valid, wasn't what was intended. Perhaps a link to a page that goes into detail would be appropriate here?

**Comment by astrofrog** [comment]
I agree, something like that would make sense.

**Comment by pllim** [comment]
c/c @nden

**Comment by nden** [comment]
I see how this can be confusing for someone not familiar with the details of the FITS WCS standard,
The error message comes from the `wcslib` library, not from `astropy` but we could ask the author to change the error message. Is this acceptable?

```
RADECSYS is non-standard, use RADESYS (optionally with an alternate WCS key, e.g. RADESYSA)
```

**Comment by astrofrog** [comment]
@nden - yes, that would be perfect

**Comment by pllim** [comment]
I think this has been resolved a while ago?
