### ISSUE TITLE
Formatting example on coordinates page is misleading

### ISSUE THREAD

**Issue by hcferguson** [astropy/astropy#4767]
The third example in the documentation on formatting coordinates is misleading.
http://docs.astropy.org/en/stable/coordinates/formatting.html

It supposedly converts to SDSS names. However it is using RA in degrees rather than HMS. 

Fix -- Change:
```
c.ra.to_string(sep='', precision=2, pad=True)
```
To:
```
p.ra.to_string(unit='hour',decimal=False,sep='',precision=2,pad=True)
```

**Comment by pllim** [comment]
@eteq , do you wish to clarify? It seems like you added this example in d33efa1d4ba.

**Comment by eteq** [comment]
My clarification: it's definitely wrong! ;)
