### ISSUE TITLE
Implement zscale stretch

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4773]
See [this](http://iraf.net/forum/viewtopic.php?showtopic=134139) thread for details on how to implement this. If I understand correctly, this should be implemented as an interval class since it should ultimately return a min/max for scaling.

**Comment by saimn** [comment]
We use an implementation of zscale which can be found at several places (used also in Ginga) but seems to be based on the one of stsci_python/numdisplay:
https://trac.stsci.edu/ssb/stsci_python/browser/stsci_python/trunk/numdisplay/lib/stsci/numdisplay/zscale.py?rev=19347
So I guess this code could be used in Astropy (and moved to an interval class), as numdisplay's license is BSD ?

**Comment by astrofrog** [comment]
@saimn - yes, since the licenses are compatible that would be an option!

**Comment by pllim** [comment]
c/c @parejkoj

**Comment by parejkoj** [comment]
I have an implementation from @ctslater already checked in to the lupton_rgb branch I'm working on (where I needed this):

https://github.com/parejkoj/astropy/blob/luptonRGB/astropy/visualization/lupton_rgb.py#L38

**Comment by saimn** [comment]
@astrofrog - Can be closed.

**Comment by astrofrog** [comment]
Thanks!
