### ISSUE TITLE
Why ImageNormalize is not importable from astropy.visualization ?

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#4775]
Having to import `ImageNormalize` from `astropy.visualization.mpl_normalize` is cumbersome, is there any reason why it is not available directly from `astropy.visualization` ? 
It seems originally matplotlib was required to import this module, this may be a reason ?
cc @astrofrog

**Comment by astrofrog** [comment]
Right - because it depends on Matplotlib and only Numpy is a required dependency of Astropy

**Comment by saimn** [comment]
@astrofrog - As there is now a stub if matplotlib is missing, it seems it is no more an issue.

**Comment by larrybradley** [comment]
@saimn The `ImageNormalize` class is a subclass of `matplotlib.colors.Normalize`.  To prevent import errors in case `matplotlib` is not installed, `mpl_normalize` defines an empty `Normalize` class, but `ImageNormalize` will not work (it will raise an `ImportError`).  This is necessary because `matplotlib` is not a required dependency of `astropy`.

**Comment by larrybradley** [comment]
Reopen if you still have questions.

**Comment by saimn** [comment]
Hmm ok, this is really a minor API issue, so no problem. But just in case I was not clear above, if matplotlib is missing, the stub `ImageNormalize` will raise an `ImportError` only if it is instanciated. So this allows it to be imported from `astropy.visualization` without needing matplotlib.

**Comment by larrybradley** [comment]
@saimn I looked at this more closely and indeed you are correct!  I submitted a PR to address this:  https://github.com/astropy/astropy/pull/5491.  Of course `matplotlib` is required to build the docs without warnings (not only for this PR).

**Comment by saimn** [comment]
Great, thanks @larrybradley !
