### ISSUE TITLE
FK5 to ICRS conversion not consistent with SIMBAD

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4794]
Not necessarily an Astropy bug, but I noticed that on SIMBAD, the ICRS and FK5 coordinates are the same to 6 decimal places when given in degrees:

http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+centauri&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id

However, if I put the decimal coordinates in ICRS into Astropy and check the FK5 coordinates, I get something slightly different:

```python
In [27]: c_icrs = SkyCoord(219.900850 * u.deg, -60.835619 * u.deg, frame='icrs')

In [28]: c_icrs.to_string(precision=6)
Out[28]: '219.900850 -60.835619'

In [29]: c_icrs.fk5.to_string(precision=6)
Out[29]: '219.900867 -60.835617'
```

I don't have time to investigate this more (including testing in other packages), but could some coordinates experts weigh in on whether one would expect ICRS and FK5 to be different at this level of precision? (cc @eteq @tboch @timj @dsberry)

**Comment by taldcroft** [comment]
FWIW, do things in sexigesimal (as per the obvious values in the linked page) produces the same sort of discrepancy:
```
In [86]: c = SkyCoord('14:39:36.204 -60:50:08.23', unit='hr,deg')

In [87]: c.to_string('hmsdms')
Out[87]: u'14h39m36.204s -60d50m08.23s'

In [88]: c.fk5.to_string('hmsdms')
Out[88]: u'14h39m36.208s -60d50m08.2242s'
```

**Comment by astrofrog** [comment]
Ah I had forgotten that I changed the default values in SIMBAD to appear in decimal for me :laugh:

**Comment by dsberry** [comment]
AST gives exactly the same values as Astropy to 6 dp:

```

#include <stdio.h>
#include "ast.h"
main(){
   double x1, y1, x2, y2;

   AstSkyFrame *icrs = astSkyFrame("System=ICRS,Epoch=2000,equinox=J2000");
   AstSkyFrame *fk5 = astSkyFrame("System=FK5,Epoch=2000,equinox=J2000");
   AstFrameSet *icrs2fk5 = astConvert( icrs, fk5, " " );
   x1 = 219.900850*AST__DD2R;
   y1 = -60.835619*AST__DD2R;
   astTran2( icrs2fk5, 1, &x1, &y1, 1, &x2, &y2 );
   printf( "%f %f\n", x2*AST__DR2D, y2*AST__DR2D );
}

```

**Comment by astrofrog** [comment]
@dsberry - can you paste the output just for reference? Thanks!

**Comment by dsberry** [comment]
219.900867 -60.835617

Not very interesting :-)

**Comment by astrofrog** [comment]
@dsberry - thanks!

I've emailed CDS to ask for comments.

**Comment by astrofrog** [comment]
Here is the response from CDS:

> For the coordinate conversion from ICRS to FK5, SIMBAD uses an internal tool available here (binaries only):
http://cds.u-strasbg.fr/resources/doku.php?id=astropos
Looking at the code, the tool uses the same orientation for ICRS and FK5 axis at epoch 2000.
I guess because "...ICRS is nominally consistent with the FK5 for the mean equinox and equator of the standard epoch J2000".
See e.g. "The Hipparcos and Tycho Catalogues" document (Vol.3 p. 416) available here:
http://www.rssd.esa.int/SA/HIPPARCOS/docs/vol3_all.pdf
It has not been updated since then.

> The differences between FK5 and ICRS are below the internal accuracy of FK5 (~50-80 mas).

**Comment by astrofrog** [comment]
I'm going to close this since I don't think there is anything wrong with the Astropy code as such, and the CDS folk also said:

> We plan to update the tool.

So things might change in future.
