### ISSUE TITLE
Remove Redshift class when it is deprecated long enough

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#4817]
It was renamed in v1.2 via #3672. I think @embray said deprecated things can be removed after 2 major releases? So that means it is disappearing in 1.4?

**Comment by pllim** [comment]
Is it safe to remove `Redshift` in v2.0, @mhvk ?

**Comment by bsipocz** [comment]
If it was deprecated in 1.2, it would be really nice to get rid of it in 2.0 so we don't tag it along in the next LTS.

**Comment by bsipocz** [comment]
Changed milestone, as decision has to be made before 2.0.

**Comment by mhvk** [comment]
I think this can indeed be removed -- this has been a while and seems a different case from changing a keyword in an often used function -- and people who support both 1.3 and 2.0 can use the new name.
