### ISSUE TITLE
Table read from FITS file takes 2x the memory it should

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4829]
I created a table with:

``` python
import numpy as np
from astropy.table import Table

N = 10000000

t = Table()
t['b'] = [np.float32(1.3)] * N
t['c'] = [4.4] * N

t.write('table.fits', overwrite=True)
```

Then read it with:

``` python
import time
from astropy.table import Table
time.sleep(3)
t = Table.read('table.fits')
time.sleep(3)
```

and profiled this with `psrecord`:

![table](https://cloud.githubusercontent.com/assets/314716/14949862/50024eae-1045-11e6-961c-0ff732369483.png)

The memory usage before reading is 54.574MB and after is 283.590MB which means that the net memory gain is 229.016MB. However, the FITS table is 114MB, and based on how we created the table, we would expect the memory usage to be `10000000 * 12 / 1024**2 = 114.44MB`. So for some reason, the memory usage is twice as large as it should be. There must be a reference to the data that is not getting removed correctly.

It may be that this is due to memory mapping being used, but I haven't checked yet. In any case, reading a FITS table through Table.read should probably disable memory mapping since we are reading the whole table anyway.

**Comment by MSeifert04** [comment]
Actually this looks like somewhere there is something weird happening. 

```
import time
import psutil
from astropy.table import Table

def read_table():
    t = Table.read('table.fits')
    return psutil.virtual_memory().percent

mem = []
for _ in range(10):
    #time.sleep() # similar with sleeping
    mem.append(read_table())

mem  # [62.7, 65.6, 68.4, 71.3, 74.2, 62.6, 65.5, 68.4, 71.3, 74.2]
```

![png1 image 640 x 480 pixels](https://cloud.githubusercontent.com/assets/14200878/18413375/71741e6e-77a6-11e6-825d-c9b79dae5daf.png)

This doesn't exactly look like a memory leak (notice the drop) but given that a function stack is cleared upon exit it's weird that the memory increases constantly.

**Comment by astrofrog** [comment]
I've narrowed this down to a memory leak in FITS_rec. The following code:

```python
import time
import numpy as np
from astropy.io.fits.fitsrec import FITS_rec

data = np.recarray(shape=(10000000,), dtype=[('b', '>f4'), ('c', '>f8')])
data['b'] = 2.3
data['c'] = 5.4

data = data.view(FITS_rec)
data = data.view([('b', '>f4'), ('c', '>f8')])

time.sleep(2)

data = data.ravel()

import gc
gc.collect()

time.sleep(2)
```

has the following memory footprint over time:

![simple](https://cloud.githubusercontent.com/assets/314716/21259622/207ea8f6-c37a-11e6-9596-4c4f30df6ba8.png)

The increase around t=3 seconds happens at the ``data.ravel()`` call. The two calls to ``view`` are necessary to reproduce this issue.

**Comment by MSeifert04** [comment]
Are you sure it's a memoryleak? Maybe it's just circular references (so python only clears them if it really needs memory) Does calling `gc.collect()` clear the memory?

**Comment by astrofrog** [comment]
Sorry yes I think it's some kind of reference issue (was using the term memory leak loosely)

**Comment by astrofrog** [comment]
So investigating this further:

* When doing ``data = data.view(FITS_rec)`` a ``data._coldefs`` is created (as expected)

* When doing ``data = data.view([('b', '>f4'), ('c', '>f8')])`` ``data._coldefs`` hasn't changed, and checking ``id(data._coldefs[0].array)``, the arrays contained inside the ``_coldefs`` are the same as before

* When doing ``data.ravel()``, first ``FITS_rec.__array_finalize__`` is called and at the end of that call  ``id(data._coldefs[0].array)`` is still the same. However, in the rest of the ``ravel()`` call, something happens and ``id(data._coldefs[0].array)`` changes, and at that point there are (according to ``pympler``) two leftover references to Numpy arrays.

I don't have time to investigate this further, but it would be great to figure this out.

@MSeifert04 @embray - any ideas?

**Comment by astrofrog** [comment]
@MSeifert04 - ah sorry I just understood your question. I'm pretty sure it's a real issue because this is causing me to run out of memory when I shouldn't be. If Python only cleared the memory if needed, it should be doing so but isn't.

**Comment by astrofrog** [comment]
Hmm, on further examination if may just indeed be something to do with how the memory is freed, so not sure if there really is an issue. I still don't understand why the memory usage blows up in my particular use case, but don't have time to investigate further.

**Comment by astrofrog** [comment]
Ok, so I think I've convinced myself that the issue with ``FITS_rec`` is real:

```
import time
import numpy as np
from astropy.io.fits.fitsrec import FITS_rec

datasets = []

for iter in range(20):

    time.sleep(0.5)

    data = np.recarray(shape=(10000000,), dtype=[('b', '>f4'), ('c', '>f8')])
    data['b'] = 2.3
    data['c'] = 5.4

    data = data.view(FITS_rec)
    data = data.view([('b', '>f4'), ('c', '>f8')])
    data = data.ravel()

    datasets.append(data)

    import gc
    gc.collect()

time.sleep(2)
```

gives:

![latest](https://cloud.githubusercontent.com/assets/314716/21261701/f774f612-c384-11e6-976c-72e25b1dcf3e.png)

Each array should take up 114MB so in total it should take 2280MB but appears to take twice that.

Now if I do the same with just ``Table.read`` I *don't* see the extra memory if I call it multiple times (like in @MSeifert04's example).

Now if I compress the table to force the memory mapping to be disabled:

```
import time
import numpy as np
#from astropy.io.fits.fitsrec import FITS_rec
from astropy.table import Table

datasets = []

for iter in range(20):

    time.sleep(0.5)

    t = Table.read('table_s.fits.gz')
    t['b'].sum()
    t['c'].sum()

    datasets.append(t)

    import gc
    gc.collect()

time.sleep(2)
```

it does once again take up too much memory but not quite as much as before:

![read_orig](https://cloud.githubusercontent.com/assets/314716/21261897/275d760a-c386-11e6-9c8a-04461fb867d1.png)

I'm confused...

@MSeifert04 - what do you think?

**Comment by astrofrog** [comment]
Well now I feel stupid. The original issue I had was actually not related to this at all. I have long string columns in the FITS table and because I use Python 3 they were being blown up to unicode, making them 4x larger than needed. I'm now using ``t.convert_unicode_to_bytestring()`` to get around this.

So there are two things to consider here:

* Are any of the memory increases in my latest comment above worth investigating more, since at least in the example of the compressed table this could be a real problem?

* What can we do to make the fact that FITS string columns get converted to unicode be more obvious, especially for large tables. Should Table.read maybe have an argument that indicates whether to use bytes or unicodes (either for the FITS format, or more generally).

**Comment by embray** [comment]
That would do it.  There are already open issues about the unicode problem, at least one of which I know has a patch I started but never published. (I didn't bother searching).  That said, it should not be "4x larger"--`str` on Python 3 (current versions) chooses an internal representation based on the highest codepoint in the string.  So if it's all ASCII it will still be represented internally as ASCII.

**Comment by astrofrog** [comment]
@embray - Table seems to default to using 4x the memory required for ASCII:

```python
In [7]: from astropy.table import Table

In [8]: t = Table()

In [9]: t['a'] = ['hello']

In [10]: t['a'].nbytes
Out[10]: 20
```

**Comment by embray** [comment]
Oh right, duh, I forgot we're using Numpy arrays, where that remains an open problem, yes.

**Comment by embray** [comment]
I did a quick look around, and found the old prototype I came up with for handling this:

https://github.com/embray/PyFITS/blob/c11abd331cff7e177f0fc551188347e529cde92d/lib/pyfits/fitsrec.py#L999

It's an `ndarray` subclass where, if the underlying dtype is a byte string (e.g. `dtype('S<n>')`) then rather than try to convert it to a full `dtype('U<n>')` array it just has an attached encoding that it uses whenever extracting individual strings out of the array, or when doing comparisons and string operations and the like.  It's just a prototype but IIRC it worked pretty well--for example ASCII strings worked well, as well as UTF-8 data.  It probably needs better error-handling though--for example surrogateescape handling would ensure that all data in a string array can round-trip to unicode and back even if not all the data in an array matches the specified encoding.

**Comment by astrofrog** [comment]
@embray - thanks! I wonder whether it might make more sense/easier to implement this at the level of the Table class, specifically using a mix-in column, rather than at the io.fits level? (since in the long term we had wanted to use Table more in io.fits).

**Comment by astrofrog** [comment]
I've opened an issue about the Numpy array subclass and mixin column ideas: https://github.com/astropy/astropy/issues/5618

**Comment by astrofrog** [comment]
Ok, so just to close the loop on the original issue here, I think the reason I went down the rabbit hole of the memory leak is because I was using a machine with 100Gb of RAM, and so I think Python was just not bothering to clear the memory because there was so much available. I read many tables in a loop and the memory went up to 24Gb then finally stagnated there. I'm going to go ahead and close this issue and open other more specific ones if I can find examples where the memory actually reaches the maximum value and crashes the computer.

**Comment by MSeifert04** [comment]
> I was using a machine with 100Gb of RAM

okay, I didn't expected you had so much RAM avaiable 😮
