### ISSUE TITLE
Failure in test_non_C_locale_with_fast_reader

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4832]
@taldcroft - I'm seeing the following test failure on MacOS X with Python 3.5 - I think this is a test you added recently? Do you know why it might be failing?

```
_______________________________________________ test_non_C_locale_with_fast_reader ________________________________________________

    @pytest.mark.skipif('not HAS_DE_LOCALE')
    def test_non_C_locale_with_fast_reader():
        """Test code that forces "C" locale while calling fast reader (#4364)"""
        current = locale.setlocale(locale.LC_ALL)
    
        try:
            locale.setlocale(locale.LC_ALL, str('de_DE'))
    
            for fast_reader in (True, False, {'use_fast_converter': False}, {'use_fast_converter': True}):
                t = ascii.read(['a b', '1.5 2'], format='basic', guess=False,
                               fast_reader=fast_reader)
>               assert t['a'].dtype.kind == 'f1'
E               assert 'f' == 'f1'
E                 - f
E                 + f1

test_read.py:1150: AssertionError
```

**Comment by cdeil** [comment]
I also see this fail with Python 3.4 and 3.5 on Mac where I have:
```
encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
```

I don't see it on Python 2.7 on Mac where I have:
```
encodings: sys: ascii, locale: UTF-8, filesystem: utf-8, unicode bits: 15
```

On Python 2, I see these other errors (`LookupError: unknown encoding`):
https://gist.github.com/cdeil/bc52c4adb4eac85949bf20dbeb602494
Should I report those separately?

**Comment by astrofrog** [comment]
@cdeil - yes, I think it makes sense to report the unknown encoding separately

**Comment by astrofrog** [comment]
@taldcroft - any idea what is causing this?

**Comment by taldcroft** [comment]
@astrofrog - sorry, I have no clue what's happening.  I'm just your average mono-lingual American with no direct `locale` experience.  I can take a look at some point, but I don't have a lot of time right now.

**Comment by astrofrog** [comment]
@taldcroft - I guess what confuses me is I don't understand what a kind of ``f1`` is - I thought ``kind`` was always a single character? What the test returns ``f`` actually makes sense to me?

**Comment by taldcroft** [comment]
@astrofrog - I agree with you there and have no idea why the test would be passing with `f1` in the assertion.  Maybe this is an upstream bug that got fixed with Python 3.4 or a newer version of numpy?

**Comment by astrofrog** [comment]
@taldcroft - interestingly, this doesn't fail on Travis with numpy-dev though...

**Comment by saimn** [comment]
It is related to #4363. I think there are a couple of issues with this block:
```
+try:
+    locale.setlocale(locale.LC_ALL, 'de_DE')
+except:
+    HAS_DE_LOCALE = False
+else:
+    HAS_DE_LOCALE = True
```

- If it fails for some reason but the user has the `de` locale, the original locale is not restored
- This file has a `# TEST_UNICODE_LITERALS` header, which is used by a pytest plugin to test with unicode_literals [1], which means that `locale.setlocale(locale.LC_ALL, u'de_DE')` fails on Python 2. That's why `locale.setlocale(locale.LC_ALL, str('de_DE'))` is used in other places. So I wonder if the test was actually always skipped in travis.

[1] "This class treats a given test .py file as a pair of .py files where one has __future__ unicode_literals and the other does not."

**Comment by astrofrog** [comment]
@saimn - good point! And that might also explain the German error message here: https://github.com/astropy/astropy/issues/4896

**Comment by astrofrog** [comment]
I think the block should be:

```
try:
    locale.setlocale(locale.LC_ALL, 'de_DE')
except:
    HAS_DE_LOCALE = False
else:
    HAS_DE_LOCALE = True
finally:
    locale.setlocale(locale.LC_ALL)
```

or something similar. If the user selects to run another test, then the locale will also never get reset even if the DE locale is present.

**Comment by saimn** [comment]
@astrofrog - Indeed, a german error message is probably not a coincidence :laughing: 
I have started a (light) Travis build in #4955 with the correct setlocale, it should fail (it does locally if I replace de_DE with fr_FR).

**Comment by saimn** [comment]
Is there a way to tell pytest to skip a test from inside the test ? I will check.

**Comment by pllim** [comment]
Oh, so my machine is not unpatriotic after all! Good detective work, @saimn! 

Do you have to skip the test? I know you can mark it as xfail inside a test with `pytest.xfail('message')`.

**Comment by saimn** [comment]
@plim - Actually I'm trying in #4955 to make sure that the test is run, as I think that until now it was always skipped (on Travis). 

Also, about the "kind" issue, which seems real: `f` seems to be the correct kind (it should be a character code: http://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.kind.html). Now which #4955 I get all the builds failing on this test.

**Comment by astrofrog** [comment]
Fixed by https://github.com/astropy/astropy/pull/4955 - thanks @saimn!
