### ISSUE TITLE
Trying to understand model_set_axis

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#4843]
```python
>>> from astropy.modeling import models
>>> c = models.Const1D([1,2], n_models=2)
>>> c(4000, model_set_axis=False)
array([ 1.,  2.])
>>> c([4000], model_set_axis=False)
array([[ 1.],
       [ 2.]])
```

Why would `c(4000, ...)` give a different answer than `c([4000], ...)`? Is this a bug or a feature?

**Comment by astrofrog** [comment]
Interesting - I would have thought you would get your second output with ``[[4000]]`` not ``[4000]``

**Comment by pllim** [comment]
@astrofrog , I think the magic is `model_set_axis=False`. It broadcasts the same input value to both sets of models in that model instance. The second answer is correct (or at least what I expected) in the sense that it returns result for both model parameters.

**Comment by nden** [comment]
@plim I think modeling returns output of the same shape as the input. When input is a scalar , n scalars are returned, if input is a list, then n lists are returned.

**Comment by pllim** [comment]
@nden , ah okay. I guess either way, `result[0]` and `result[1]` would separate the results properly. So, that's good enough for me.

p.s. My username has *two* l's. Poor Patrick Lim is getting random notifications...
