### ISSUE TITLE
Importing astropy raises ImportError with ipython < 1.0

### ISSUE THREAD

**Issue by duncanmmacleod** [astropy/astropy#4845]
If you have IPython < 1.0 the `IPython.version_info` tuple isn't present [[link](https://github.com/ipython/ipython/blob/rel-0.13.2/IPython/__init__.py)], and `import astropy` throws this exception:

``` python
/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/__init__.py in <module>()
    282 
    283 if not _ASTROPY_SETUP_:
--> 284     from .logger import _init_log, _teardown_log
    285 
    286     log = _init_log()

/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/logger.py in <module>()
     15 from .extern.six import PY3, text_type
     16 from .utils import find_current_module
---> 17 from .utils.console import color_print
     18 from .utils.exceptions import AstropyWarning, AstropyUserWarning
     19 

/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/utils/console.py in <module>()
     36     IPythonIOStream = None
     37 else:
---> 38     from IPython import version_info
     39     ipython_major_version = version_info[0]
     40 

ImportError: cannot import name version_info
```

While this might seem a corner-case, ipython 0.13.1 is the default version on debian 7 so it probably hits a few more than just me.

My naive quick-fix patch to avoid requiring astropy 1.0 is as follows:

``` diff
diff --git a/astropy/utils/console.py b/astropy/utils/console.py
index 4945c9b..a820cab 100644
--- a/astropy/utils/console.py
+++ b/astropy/utils/console.py
@@ -31,11 +31,11 @@ except ImportError:
     pass
 try:
     get_ipython()
-except NameError:
+    from IPython import version_info
+except (NameError, IndexError):
     OutStream = None
     IPythonIOStream = None
 else:
-    from IPython import version_info
     ipython_major_version = version_info[0]

     try:
```

I'll happily form that as a PR if that is preferred to a version requirement.

**Comment by pllim** [comment]
My IPython is 4.2, this seems pretty old...

**Comment by duncanmmacleod** [comment]
@pllim you are correct, but as I noted above ipython 0.13 is the default on debian 7, which was only superseded last year. Large-scale computing centres (such as we have in the [LSC](//ligo.org)) are typically slow to upgrade their OS, meaning this problem could hit a decent number of people. Plus, the fix is trivial.

**Comment by MSeifert04** [comment]
Ipython 1.0 release was [2013](http://ipython.org/news.html#ipython-1-0). They seem to have a more very frequent majore releases. But I wouldn't try to support it given that they announced "some significant API reorganisations". Is it just the `IPython.version_info`?

**Comment by astrofrog** [comment]
If it's just a small change, then I'm fine with supporting this. CASA also uses an old IPython version (even to this date) and it'd be nice to maintain compatibility.

**Comment by pllim** [comment]
@duncanmmacleod , I agree with others that if this version check is the only blocker, then a PR is fine.

**Comment by duncanmmacleod** [comment]
ok, I'll put together a PR that works around this for IPython < 1.0. One quick q, is there a reason to use `IPython.version_info`, rather than just `IPython.__version__`?

**Comment by MSeifert04** [comment]
@duncanmmacleod before you try could you check if units (and mpl-styles) work with the old IPython? I'd rather have an Error up front instead of Errors during execution.

`__version__` is a string, you need to parse and compare it carefully. `version_info` is a tuple that can be simply compared using `>` or `<`. So whenever possible use `version_info`. `__version__` should always be only a fallback option.

**Comment by duncanmmacleod** [comment]
@MSeifert04, I ran the astropy test suite (`python setup.py test`) end-to-end and got a few failures, none of which seemed related to ipython. Not sure if you're looking for something more specific.

**Comment by pllim** [comment]
Huh... Why would there be any failure at all? I think the core maintainers are pretty rigorous in making sure the tests pass before merging a PR.

**Comment by pllim** [comment]
If you enable Travis CI on your fork, you can have the test suites run on that branch (before submitting a PR) and link the failed build here.

**Comment by bsipocz** [comment]
@MSeifert04m @duncanmmacleod  - with ``__version__`` comparison we tend to use ``distutils.version.LooseVersion`` in several places.  Why not use it here, too? (@larrybradley may have some objections as I think he introduces the usage of ``version_info``).

**Comment by duncanmmacleod** [comment]
@pllim, I get a different set of non-zero errors on different machines. I think related to the numpy version. If I set up a virtualenv on Mac OS X with Python 2.7.11 and numpy 1.11.0, I get 6 failures. See attached [failures.txt](https://github.com/astropy/astropy/files/250841/failures.txt).

**Comment by bsipocz** [comment]
(@duncanmmacleod -  just as a side note: you can use [gist](https://gist.github.com/) for posting these kind of logs).

**Comment by pllim** [comment]
The failures are from ERFA and C parser for ASCII fast writer.

**Comment by MSeifert04** [comment]
I didn't mean test-suite failures. 

I just thought if it fails this early with `IPython < 1.0` there might be more (hidden) problems when representing units or special styles in an interactive IPython (< 1.0) session. I don't think there are any tests using such an old IPython version. I don't know where the IPython functions are used and where they might be incompatible. And I think having this Error at the beginning which clearly indicates that IPython might be incompatible then having cryptic warnings later in the session when displaying for example a `Quantity` or when using some other IPython functionality.

**Comment by larrybradley** [comment]
@bsipocz I don't recall why I used `version_info`, but that was before I started using `distutils.version.LooseVersion` for version checking.  `LooseVersion` should work fine.

(wow, `ipython 0.13` is *really* old)

**Comment by bsipocz** [comment]
Is this still an issue that needs to be addressed or can be closed?

**Comment by bsipocz** [comment]
This issue is about a rather old ipython, so I'm closing. Feel free to reopen if running into it again.
