### ISSUE TITLE
flush, close, writeto crashing python after editing data

### ISSUE THREAD

**Issue by nrgolovich** [astropy/astropy#4853]
I have a R and G band subaru fits image, and I'm trying to generate an exposure weighted R/G average frame to use for a RGB fits cube. The files are large, but not exceptionally so (130 MB each).

I made a copy of the G band image to be edited, but at the start it's identical to the g image. 

``` python
>>> import astropy.io.fits as fits
>>> g=fits.open('G.fits')
>>> r=fits.open('R.fits')
>>> gr_mean=fits.open('gr_mean.fits',mode='update')
>>> gr_mean[1].data = (g[1].data+r[1].data)/2
>>> gr_mean.flush()
Python(3926,0x7fff73ba5000) malloc: *** error for object 0x7fb638d36b10: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort
```

I verified that the data manipulation worked before I tried to write the file back. I get the same error on two machines. This error seems to be above python. Other people get it in the terminal and even upon opening finder. Their solution related to disk utility permissions. This didn't help me. 

I'm curious where python and astropy is coming into play here.

**Comment by pllim** [comment]
What if you use `gr_mean.close()` instead of `flush()`? Do you see the same error?

**Comment by nrgolovich** [comment]
I get the same error from flush(), close(), and writeto()

**Comment by pllim** [comment]
Using my own 10x10 fake data, I cannot reproduce your error. Are you able to reproduce this error consistently using other files? What are the outputs for `r.info()`, `g.info()`, and `gr_mean.info()`?

**Comment by pllim** [comment]
Also, info on your system and software versions (Python, Astropy, Numpy, etc) might be useful as well.

**Comment by nrgolovich** [comment]
Python: 2.7.11
Astropy: 1.1.2
Numpy: 1.11.0

>>> r.info()
Filename: R.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU       8   ()              
1    COMPRESSED_IMAGE  CompImageHDU     60   (14522, 14106)   float32   

>>> g.info()
Filename: gr_mean.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU       8   ()              
1    COMPRESSED_IMAGE  CompImageHDU     66   (14522, 14106)   float32   

>>> gr_mean.info()
Filename: gr_mean.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU       8   ()              
1    COMPRESSED_IMAGE  CompImageHDU     66   (14522, 14106)   float32   


I can't reproduce it with simpler fits images that aren't compressed with only a single extension.

Perhaps it is related to the image being compressed?

**Comment by astrofrog** [comment]
@nrgolovich - could you provide a copy of the FITS files you are using? (e.g. via dropbox or google drive).

**Comment by pllim** [comment]
I looked at the current issues with compressed FITS data and I see a bunch of them -- known bugs with RICE compression, planned but unimplemented enhancements/fixes, etc. So, this could be tied to some of those but I cannot pinpoint which one(s) with the info given thus far.

A shot in the dark -- I wonder if #4585 would be useful for this case.

**Comment by nrgolovich** [comment]
@astrofrog - I sent them to your email via google drive. Thanks!

**Comment by saimn** [comment]
@nrgolovich - Would it be possible for you to test this with a recent astropy version, or to provide the file to reproduce ?

**Comment by astrofrog** [comment]
Unfortunately I no longer have access to the files, and due to lack of activity and inability to reproduce this I think we should just close. However @nrgolovich if you are still able to send the files all these years later, please feel free to re-open!
