### ISSUE TITLE
Cannot import name Planck15

### ISSUE THREAD

**Issue by mayurisrao** [astropy/astropy#4865]
Hi
 I'm trying to get the hmf package running which seems to need Planck15 from the astropy.cosmology package. I made sure to upgrade to the latest astropy version with pip. But I am unable to import Planck15. Other cosmologies like WMAP9, Planck13 etc.. import fine without any trouble. Am I missing anything here?
 I'm using python version 2.7.3 on jupyter notebook.
Thanks in advance. 
Cheers.
Mayuri

**Comment by simongibbons** [comment]
What is the output when you run this?

    import astropy
    print astropy.__version__

I only ask as `Planck15` has been part of astropy since v1.1 and given it is just a dict of values I can't see any reason why it wouldn't be importable.

**Comment by astrofrog** [comment]
@mayurisrao - just mentioning your username to make sure you get a notification about this - as @simongibbons suggested, it's likely you have an old version of astropy. Could you confirm?

**Comment by mayurisrao** [comment]
Hi
You're right! I found that while I have upgraded to the latest astropy release (1.1.2) on my computer, the astropy that jupyter notebook imports is still 1.0.5! Looks like something to get working. Thanks a lot!
- cheers

**Comment by astrofrog** [comment]
@mayurisrao - thanks for confirming!
