### ISSUE TITLE
Add .wcs attribute to FITS HDUs

### ISSUE THREAD

**Issue by embray** [astropy/astropy#4866]
I don't know why we haven't just done this sooner.  If I were to wager a guess it was that we were waiting for generalized WCS but really until that becomes available this is such a low-hanging fruit.

Currently to get a WCS from a FITS header one has to manually 

```
from astropy.wcs import WCS
wcs = WCS(hdul[ext].header)
```

etc.  It would be trivial to add a `.wcs` attribute to HDU objects (specifically `_ImageBaseHDU`--maybe not all HDU types).  This didn't exist originally because the old PyWCS was not a dependency of PyFITS.  But I see no reason not to add this convenience now, especially since it's such a common operation, and adding a well-documented `.wcs` attribute would make it very easy to find.

This should of course be a property (perhaps `lazyproperty`? Thought the cached WCS would have to be invalided if the header is modified).  There should also be reasonable error-handling if the header does not contain a valid WCS.

**Comment by adivijaykumar** [comment]
Hi, I'd like to work on this.

Just so I am sure I understand this correct, the goal is to write have .wcs like hdu[ext].wcs which lets us get the WCS directly. Correct?

**Comment by pllim** [comment]
@adivijaykumar , yes. However, as noted above, just for image HDU and only if the WCS is valid.

**Comment by pllim** [comment]
@nden and I agree over at #5690 that this is a "won't fix" issue.

**Comment by embray** [comment]
I think it's worth fixing as a convenience; @mwcraig seemed to think it was worthwhile to have something for this here: https://github.com/astropy/astropy/pull/5690#issuecomment-274706981

I agree it requires more discussion though.  It might be better if it were a method instead of a property since, as @nden pointed out, a property is probably too simple for the general case, and it's not clear what the behavior should be for a property (would changes to the header update the existing `.wcs` property? Cause a new one to return next time `.wcs` is accessed?  ???

The point of this was just to provide a more convenient method to get a WCS for an image, that didn't require additional imports.

**Comment by adivijaykumar** [comment]
So shall we try to implement this as a convenience, even if it requires discussion? I am ready to devote time to this (it is a convenience which I would like while using astropy :D )

Please let me know.
