### ISSUE TITLE
astropy-dev install

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#4869]
The installation of the development astropy is different than regular astropy (ie installation of cython required as well as a few other packages).   It would be useful to have an easy way to install all the requirements for the developer package via pip or conda. 

For example, we could have an astropy-all package that installed all the affiliated packages and an astropy-dev that installed all the requirements to develop astropy.

**Comment by bsipocz** [comment]
I somewhat like the idea of ``astropy-all`` in the form as it was suggested on the mailing list. However I think there should be a discussion what to include, as including all the affiliated packages in there may be a bit too much. At the moment the are 28 packages listed as affiliated, and this number is growing, which is good. But many of them are very specific for a topic, and I as a user may prefer not to have everything.

From the dev prospective as mentioned in this issue, I don't see much sense in an ``astropy-all``. For core development one doesn't need any of the affiliated packages (let alone all), and for affiliated dev one needs to use the dev version of the given package and not a release, and maybe a few dependencies. However there is a high chance that those dependencies are already there in a dev version.

**Comment by MSeifert04** [comment]
I understood it as something along the lines of an automatic ``dependencies=[ scipy h5py PyYAML matplotlib pytz scikit-image pandas pytest-pep8 coverage cython jinja2 wcsaxes babel docutils sphinx graphviz numpydoc]`` for the astropy-dev bundle to include everything from building dev, testing dev and building dev-documentation and (almost?) all optional dependencies.

**Comment by eteq** [comment]
I do like the idea of `astropy-dev` - I frequently find myself conda installing those and wishing for an alias or similar.

**Comment by mwcraig** [comment]
So you can try this, which I'm happy to move over to the astropy conda channel once I figure out how to do that:

`conda env create mwcraig/astropy-dev-py3`

**Comment by bsipocz** [comment]
I think that using `options.extras_require` has solved this issue, no one can easily install everything with:
`pip install astropy[all,test,doc]`
