### ISSUE TITLE
Generalize CartesianRepresentation.transform to support broadcasting

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4878]
At the moment, CartesianRepresentation.transform takes a single 3x3 transformation matrix. It would be nice to generalize this so that it can be a higher dimensional object that can be broadcast with the underlying representation data (note that the representation data can be N-dimensional).

See https://github.com/astropy/astropy/pull/4860 for some ideas of implementation that might support this broadcasting, but it's important to make sure that the performance is not made worse for small or large arrays.

**Comment by mhvk** [comment]
Would be fixed by #5104.

**Comment by mhvk** [comment]
Closing, since #5104 should have fixed this.
