### ISSUE TITLE
Examples of NDData in Documentation 

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#4891]
As mentioned in  #4799, it would be useful to have examples of where and how NDData is used even if those examples are links  to affiliated packages. This includes, for example, how readers/writers can be created and how masks or uncertainties are handled. 

Some places where it is used includes `ccdrpoc.CCDData`, `specutils.Spectrum1D`, `sunpy.GenericMap`, and `SpectralCube.SpectralCube`.

**Comment by crawfordsm** [comment]
This is also potentially relevant to #4876

**Comment by mhvk** [comment]
This effectively is a feature request, so labelled it as such and moved the milestone to "Future", since there is no-one assigned to take care of it.

**Comment by mwcraig** [comment]
Related to #4756, and perhaps to #6173.

Re-milestoned with intent to update documentation in the next few days.

**Comment by mwcraig** [comment]
Note: SpectralCube does not actually use NDData
