### ISSUE TITLE
two copies of `six` in extern?

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#4914]
While looking at something else, I just noticed that there seem to be two copies of `six` in `astropy/extern`... One as `astropy/extern/six.py`, and the other as `astropy/extern/bundled/six.py`.  They seem to be the same version, and neither have been touched in ~two years... Any idea why this is,  @sergiopasra @mdmueller @astrofrog @embray?  Perhaps one of them should be removed? (and if so, which?)

**Comment by astrofrog** [comment]
The ``extern/six.py`` file is just a layer that selects between the bundled version in ``bundled`` or the system one.

**Comment by mhvk** [comment]
I checked in my version and definitely the two files are different, so closing...
