### ISSUE TITLE
emu unit

### ISSUE THREAD

**Issue by p3trus** [astropy/astropy#4918]
Is there an ambiguity of the `emu` unit? I just know it as a unit of magnetic moment ([see](https://www.qdusa.com/sitedocs/UnitsChart.pdf)). The way I know it

```
1 emu = 1 erg/gauss = 1e-3 A m^2
```

I tried

``` python
from astropy import units as u
u.emu.to(u.A * u.m**2)
```

which resulted in a `UnitconversionError`.

**Comment by pllim** [comment]
I am not familiar with this unit, but looks like @embray added it via 68f574cded9094 . And it might be related to https://en.wikipedia.org/wiki/Abampere

**Comment by p3trus** [comment]
A little bit more research at [wiki](https://en.m.wikipedia.org/wiki/Centimetre%E2%80%93gram%E2%80%93second_system_of_units) Shows that emu has indeed different meanings.
> Also, lack of unique unit names leads to a great confusion:
> thus "15 emu" may mean either 15 abvolts, or 15 emu units of electric dipole moment,
> or 15 emu units of magnetic susceptibility, sometimes (but not always) per gram, or per mole.

**Comment by pllim** [comment]
@p3trus , so this looks like just general confusion? You can always define your own units.

http://astropy.readthedocs.io/en/stable/units/combining_and_defining.html
http://astropy.readthedocs.io/en/stable/api/astropy.units.def_unit.html#astropy.units.def_unit

**Comment by bsipocz** [comment]
I've also looked into this a bit in the weekend, and it's very confusing. ``EMU`` to me looks more like a unit system than a unit itself. So what about removing/deprecating ``'emu'`` from the alternatives list of ``u.Bi``, so anyone wanting to use either EMU current or charge won't fall in the trap of using the other by accident.

**Comment by pllim** [comment]
@embray , since you added it, do you have a preference in deprecating `emu`?

**Comment by p3trus** [comment]
@pllim It was not a general confusion, the code example was oversimplified. I had an error at a place where I didn't expect it. I could read in all magnetisation data files without a problem. Later in the calculations, it crashed. I would prefer not having ambiguous units. After all having units is to avoid errors not create them.

**Comment by mhvk** [comment]
In case anyone is keen to do work to support the various cgs EM systems, see #4359...

**Comment by bsipocz** [comment]
@embray @mhvk - Do you have any pro or con for deprecating ``u.emu``, or at least give a warning when someone trying to use it? If there is no objections, I can open a PR and maybe we can still include it in 1.2 so the final removal can be done in 2.0?

cc @astrofrog @eteq

**Comment by mhvk** [comment]
I guess the only issue that might arise is when an external table uses the unit. I certainly have not encountered such tables myself, and would guess they are rare inside astronomy. Furthermore, I guess in that case the unit would be unclear anyway, so am happy to deprecate.

**Comment by pllim** [comment]
@p3trus , `u.emu` will no longer be accessible by default due to the confusion (in dev and in v2.0 release). Please use `u.Bi` or its other aliases. `u.deprecated.emu` is available but not recommended.
