### ISSUE TITLE
HRCS cannot be converted to other coordinate systems

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#4922]
While looking into heliocentric coordinates in the context of the `plan94` work (#4920), I thought I would try initializing `HRCS` coordinates, but it seems those cannot be tranformed into any other frame: only grcs -> hcrs is defined, not the reverse. Is this intentional?

**Comment by StuartLittlefair** [comment]
This isn't intentional. 

I'll add some transforms to make this possible on Monday.

**Comment by mhvk** [comment]
This can be closed when #4929 is merged.

**Comment by mhvk** [comment]
Fixed by #4929.
