### ISSUE TITLE
Travis PEP8 check: Include E291, E293

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4923]
PEP8 - E291 and E293 are about "trailing whitspaces" and "blank lines containing whitespaces".

The problem is that I have this option in my editor that removes all of these whitespaces on save. So I regularly find myself pushing a commit where the editor removed lots of those in unrelated parts of the code and I've seen some others who have the same problem. So I wanted to ask if these tests could be included in the PEP8 travis check.

**Comment by bsipocz** [comment]
I have an open PR dealing with these, but didn't want to noise the feature freeze with updates to it.

**Comment by astrofrog** [comment]
I'm confused, it looks like we already include these:

https://github.com/astropy/astropy/blob/master/setup.cfg#L38

although at the time they were called ``W291`` and ``W293``. Are they called ``E`` now?

**Comment by MSeifert04** [comment]
Upon reflection I think it mostly (always) happens to me in `Changes.rst`. If the PEP test just scans `.py` files that could explain it.

**Comment by taldcroft** [comment]
I recently had a build failure due to trailing whitespace, so I thought our current PEP8 checks this.  I also have auto-trim in my emacs setup, but it only trims lines that I'm actually editing.  

@MSeifert04 - can you configure your editor that way?  Maybe it will be a non-issue if @bsipocz does her PR.

**Comment by MSeifert04** [comment]
@taldcroft Unfortunatly there is no such option for my editor of choice. 

And I've just checked the pytest works fine, it's just `.rst` files that aren't checked. Probably not worth the effort, I'll see if I can disable the auto-trim in not-`.py` files.

**Comment by mhvk** [comment]
Given how sensitive `.rst` files seem to be to wrong indentation, etc., it might not be bad to have automatic tests on those too.

**Comment by astrofrog** [comment]
I'm going to close this in favor of https://github.com/astropy/astropy/issues/5731, which I just opened (otherwise the name and description of this issue are misleading)
