### ISSUE TITLE
Bayesian block warning during documentation build

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4927]
When building the documentation, I'm seeing some warnings that come from the bayesian blocks code:

```
WARNING: p0 does not seem to accurately represent the false positive rate for event data. It is highly recommended that you run random trials on signal-free noise to calibrate ncp_prior to achieve a desired false positive rate. [astropy.stats.bayesian_blocks]
```

Does this mean that there are issues with our examples?

cc @jakevdp

**Comment by jakevdp** [comment]
This was added by @robcross – if I recall it was reflective of some tests he personally ran.

**Comment by jakevdp** [comment]
Here's the commit message: https://github.com/astropy/astropy/commit/969446239709f539ce878e6e9e5be5a4ad3c03c8

**Comment by jakevdp** [comment]
I don't know much more than that.

**Comment by pllim** [comment]
To be fair, that is not the *only* warnings issued during doc build that has nothing to do with the doc.

**Comment by bsipocz** [comment]
These warnings should be cleared up for v2.0 as sphinx 1.6+ will fail on these warnings. IMO we shouldn't include examples in the docstring that generate warnings.

Also this code part needs revising, as p0=None gives a big error:``TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'``

```
    def __init__(self, p0=0.05, gamma=None, ncp_prior=None):
        if p0 is not None and gamma is None and ncp_prior is None:
            warnings.warn('p0 does not seem to accurately represent the false '
                          'positive rate for event data. It is highly '
                          'recommended that you run random trials on signal-'
                          'free noise to calibrate ncp_prior to achieve a '
                          'desired false positive rate.', AstropyUserWarning)
        super(Events, self).__init__(p0, gamma, ncp_prior)
```

**Comment by bsipocz** [comment]
@robcross - Would you have some time to have a look at these warnings that are issued during docs building? It would be great to include examples that doesn't have this warning.

**Comment by bsipocz** [comment]
The warning has be caught during docs build, but nevertheless it would be great to revisit the examples and only have ones that makes sense.

**Comment by pllim** [comment]
The problem was calling the histogram function (method?) in the doctest without providing some kind of init that makes the package happy.

**Comment by jakevdp** [comment]
I think the current examples are the ones that make sense – the warning, if I remember correctly, is due to the fact that @robcross found the standard parameter for estimating false positive rate provides a poor estimate for some data. There's not really any way to create an example that does not include this warning.

TBH, I think the best approach is to remove the warning entirely, and rather put some discussion of the issue in the documentation.

**Comment by astrofrog** [comment]
IMHO, warnings should be things that users should be able to act on and remove. It sounds like this indeed should be a documentation/docstring thing, but could also include a logging.info message.

**Comment by robcross** [comment]
Hello! Sorry, my notifications weren't popping up right...

I've been working with bayesian blocks for a while now. I can take a look at this and I have some ideas to redo the examples, but I can't really work on it for a couple weeks. I have a lot on my plate at the moment.
