### ISSUE TITLE
Inconsistencies in Celestial frame rotation classes

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#4932]
Due to changes implemented in https://github.com/astropy/astropy/pull/4881, I think there are some inconsistencies in the behavior and/or documentation of `astropy.modeling.rotations.RotateNative2Celestial` and `astropy.modeling.rotations.RotateCelestial2Native` models. The documentation says that ``lon``, ``lat``, and ``lon_pole`` are the parameters of the models. However there are several things that seem to be in disagreement with the documentation.

1. First of all, ``lon``, ``lat``, and ``lon_pole`` are no longer reported as parameters:
    ```python
>>> from astropy.modeling import rotations
>>> n2c = rotations.RotateNative2Celestial(lon=20, lat=56, lon_pole=20)
>>> print(repr(n2c))
<RotateNative2Celestial(phi=-70.0, theta=-34.0, psi=-110.0)>
>>> print(n2c)
Model: RotateNative2Celestial
Inputs: (u'phi', u'theta')
Outputs: (u'alpha', u'delta')
Model set size: 1
Parameters:
     phi  theta  psi  
    ----- ----- ------
    -70.0 -34.0 -110.0
    ```

2. This is very confusing as the constructor takes ``lon``, ``lat``, and ``lon_pole`` (and the documentation clearly states that these are the "parameters" of the model) while the model itself is using different parameters (``phi``, ``theta``, ``psi``) and these parameters have very different values from the values set by me in the constructor. In addition, `param_names` attribute also shows ``phi``, ``theta``, ``psi`` as being "parameters":
    ```python
>>> from astropy.modeling import rotations
>>> n2c = rotations.RotateNative2Celestial(lon=20, lat=56, lon_pole=20)
>>> n2c.param_names
('phi', 'theta', 'psi')
>>> n2c.parameters
array([-1.22173048, -0.59341195, -1.91986218])
    ```
Why are parameter values so different from what I set them to be (20 deg, 56 deg)?

3. My old code that was using pre-https://github.com/astropy/astropy/pull/4881 `astropy.modeling.rotations.RotateNative2Celestial` and `astropy.modeling.rotations.RotateCelestial2Native` models started crashing because 
    ```python
>>> n2c.lat.value
Traceback (innermost last):
  File "<console>", line 1, in <module>
AttributeError: 'numpy.float64' object has no attribute 'value'
    ```
This clearly indicates that ``lat`` does not behave like a parameter. This seems to be related to the following code in `RotateNative2Celestial` that tries to mimic the old behavior of `RotateNative2Celestial`:
    ```python
    @property
    def lat(self):
        return self.theta + 90
    ```
As the result, ``lat`` (and ``lon``, ``lon_pole``) lose their property of being model parameters:
    ```python
>>> n2c.theta
Parameter('theta', value=-34.0)
>>> n2c.theta + 90
56.0
>>> # Note that adding a number to a parameter (see above) returns a number
    ```

Overall, it seems that due to the changes in https://github.com/astropy/astropy/pull/4881, it is very difficult to work with `RotateNative2Celestial` and `RotateCelestial2Native` models as their true parameter names (``phi``, ``theta``, ``psi``) no longer correspond to the parameters used at instantiation of either model class (``lon``, ``lat``, and ``lon_pole``) and the values of the true parameters are different from the values of the parameters ``lon``, ``lat``, and ``lon_pole`` used at instantiation.

**Comment by nden** [comment]
@mcara The user parameters to both classes are `lon`, `lat`, `lon_pole`. It is true that these are not instances of `astropy.modeling.parameters.Parameter`. The user facing parameters correspond to `CRVAL1`, `CRVAL2` and `lonpole` (which is usually computed) but these are mathematically **not** the Euler angles needed to rotate the two spheres. The code converts internally to the Euler angles `phi`, `theta`, `psi`. Having to use `lon`, `lat` and `lon_pole` in my opinion is less confusing to an end user than having to use the true Euler angles. 

This is the explanation. The question is what can be done to improve this?
We could add `__repr__` and `__str__` to these classes to prevent printing out the Euler angles and print out the `lon`, `lat`, `lon_pole` values.

Obviously your code has to be changed to not access `.value` (not sure why you need that anyway).

Do you have any other suggestions?

**Comment by mcara** [comment]
> _Obviously your code has to be changed to not access ``.value`` (not sure why you need that anyway)._

There are several reasons why I do not like using parameters themselves:
```python
>>> # 1
>>> from astropy.modeling import rotations
>>> n2c = rotations.RotateNative2Celestial(lon=20, lat=56, lon_pole=20)
>>> float(n2c.theta)
Traceback (innermost last):
  File "<console>", line 1, in <module>
TypeError: float() argument must be a string or a number
>>>
>>> # 2
>>> import math
>>> math.sin(math.radians(n2c.theta))
Traceback (innermost last):
  File "<console>", line 1, in <module>
TypeError: a float is required
>>>
>>> # 3
>>> print("theta={}".format(n2c.theta))
theta=Parameter('theta', value=-34.0)
>>> print("theta={}".format(n2c.theta.value))
theta=-34.0
```

> _We could add ``__repr__`` and ``__str__`` to these classes to prevent printing out the Euler angles and print out the ``lon``, ``lat``, ``lon_pole`` values._

It is true we could do that, but we should also do something about ``.param_names`` and ``.parameters`` (why does ``parameters`` have values so different from what I set them to be?) and possible other attributes would need some special treatment.

Stil, fundamentally, ``lon``, ``lat``, ``lon_pole`` will not be a ``Parameter`` and then this whole model becomes a mess.

> _Do you have any other suggestions?_

I would suggest not to inherit from neither ``_SkyRotation`` nor ``EulerAngleRotation``. Instead, ``RotateNative2Celestial`` should inherit directly from ``Model`` (having true parameters ``lon``, ``lat``, ``lon_pole``) and create a ``EulerAngleRotation`` object when it is initialized. Then it should implement an ``evaluate`` method which could be a simple copy of the ``evaluate`` from ``_SkyRotation`` except instead of calling ``evaluate`` of the super,
```python
alpha, delta = super(_SkyRotation, self).evaluate(phi, theta, lon, lat, lon_pole)
```
have something like:
 ```python
alpha, delta = self._euler_angle_rot.evaluate(phi, theta, lon, lat, lon_pole)
```

There will be an issue that when (true) parameters ``lon``, ``lat``, ``lon_pole`` will change, ``phi``, ``theta``, and ``psi`` will need to be recomputed. That can be dealt with using parameter setters - see https://github.com/astropy/astropy/issues/4586

**Comment by nden** [comment]
@mcara I don't like the way this turned out either. But given the limited hours I had to finish it before the freeze I didn't come up with anything better. I am working now on a slightly different version which will solve most of the interface problems. 

@pllim My understanding is that the assignee is the one who reviews a PR. You keep assigning me calls which I work on which is a bit confusing.

**Comment by pllim** [comment]
@nden, this is not a PR but an issue that you might be able to address, so I thought assigning you was the right thing to do. Feel free to unassign yourself if otherwise. Thanks.

**Comment by nden** [comment]
@pllim Right, it's an issue and it is the right thing to do. Thank you!

**Comment by mcara** [comment]
Solved in https://github.com/astropy/astropy/pull/4940
