### ISSUE TITLE
ASCII read converters don't take lambda function

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#4934]
I use `ascii.read()` to read a text file containing simple table data. The data by default is interpreted as integer but I want to cast them as float. There are 10 columns, so I have to do this:

``` python
import numpy as np
from astropy.io import ascii

converters = {'col1': [ascii.convert_numpy(np.float)],
              'col2': [ascii.convert_numpy(np.float)],
              'col3': [ascii.convert_numpy(np.float)],
              'col4': [ascii.convert_numpy(np.float)],
              'col5': [ascii.convert_numpy(np.float)],
              'col6': [ascii.convert_numpy(np.float)],
              'col7': [ascii.convert_numpy(np.float)],
              'col8': [ascii.convert_numpy(np.float)],
              'col9': [ascii.convert_numpy(np.float)],
              'col10': [ascii.convert_numpy(np.float)]}

tab = ascii.read(inputfile, converters=converters, ...)
```

I tried to be lazy and use the following instead but it does not work, although it is theoretically equivalent:

``` python
from collections import defaultdict

converters = defaultdict(lambda: [ascii.convert_numpy(np.float)])
```

Why does it not work? Is there a more elegant way (that works) to read data in as float by default?

**Comment by pllim** [comment]
@taldcroft , maybe you know?

**Comment by simongibbons** [comment]
I think it is because the converters are accessed with with a `get` method from the user supplied dictionary [see here](https://github.com/astropy/astropy/blob/master/astropy/io/ascii/core.py#L928).

The default factory of `defaultdicts` only come into play when keys are accessed through `__getitem__`.

**Comment by pllim** [comment]
@simongibbons , thanks!

I guess the next question is would it make sense to expand `io.ascii` to support `defaultdict`?

**Comment by taldcroft** [comment]
#11892 provides a way to do this via unix-style wildcards. Closing this in favor of that method.

**Comment by pllim** [comment]
Wow, thanks for tackling this old issue!
