### ISSUE TITLE
Sphinx class inheritance diagrams not linking classes correctly

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4935]
Blocked by

- [ ] sphinx 7.2, see https://github.com/sphinx-doc/sphinx/pull/10614#issuecomment-1673719472
- [ ] sphinx-automodapi 0.16 with https://github.com/astropy/sphinx-automodapi/pull/172

<hr/>

In class inheritance diagrams the links to the classes are broken. For example [here](http://astropy.readthedocs.io/en/latest/wcs/index.html#class-inheritance-diagram).

The problem seems to be that these links don't include the branch, for example:
- Link: http://astropy.readthedocs.io/en/api/astropy.wcs.NoSolutionError.html#astropy.wcs.NoSolutionError does not work
- but http://astropy.readthedocs.io/en/latest/api/astropy.wcs.NoSolutionError.html#astropy.wcs.NoSolutionError (with the latest) does.

Not sure if this is astropy related. If not could you point me in the right direction?

**Comment by bsipocz** [comment]
This is a duplicate for astropy/photutils#345. One fix was done in https://github.com/sphinx-doc/sphinx/pull/2484, but there are issues with it and I haven't got time yet to get back to it. However it's on my list to do before 1.2.

**Comment by larrybradley** [comment]
@bsipocz Any update on this?

**Comment by bsipocz** [comment]
@mirca @dpshelio - I can't remember whether you find any workarounds for this, or just the one I had the PR in sphinx?

**Comment by mirca** [comment]
@bsipocz We ended up implementing the same solution you thought.

**Comment by Cadair** [comment]
Crikey have these really been broken for this long, shows you how much attention I pay.

**Comment by bsipocz** [comment]
@mirca - ouch, I though you've found a patch for https://github.com/astropy/sphinx-automodapi that would make it work again.

**Comment by amcnicho** [comment]
I noticed another instance of this issue ([docs/coordinates/index.rst](https://github.com/astropy/astropy/blob/master/docs/coordinates/index.rst#referenceapi) is affected) and also realized that the links in the generated inheritance diagrams are only missing the branch name. I checked [the build page](https://readthedocs.org/projects/astropy/builds/) and it seems that sphinx_automodapi is apparently run without `graphviz` explicitly installed:
```
python3.6 -mvirtualenv --system-site-packages /home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest 
/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/bin/python -m pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/astropy/.cache/pip pip 
/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/bin/python -m pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/astropy/.cache/pip -I Pygments==2.3.1 setuptools==41.0.1 docutils==0.14 mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<1.1
```
This is contrary to instructions in [the documentation](https://sphinx-automodapi.readthedocs.io/en/latest/index.html#quick-start), which state `graphviz` as a dependency for inheritance diagrams. Could a fix for this issue be as straightforward as updating the CI system to ensure that library is installed before documentation builds?

**Comment by embray** [comment]
Just rediscovered this issue when using Astropy as a nice demonstration of class inheritance diagrams.  I can't believe this has been broken for 6 years :exploding_head: 

I'll have a look into it.

**Comment by ayshih** [comment]
I've put up a PR (astropy/sphinx-automodapi#152) that finally fixes this bug

**Comment by ayshih** [comment]
Upon further testing, I discovered that the true bug is in Sphinx after all, and has nothing to do with sphinx_automodapi.  See sphinx-doc/sphinx#10576

**Comment by ayshih** [comment]
I'll point out that even after Sphinx accepts the bugfix for current releases, the Astropy docs are currently being built against a rather old version of Sphinx.  You'll almost certainly need to undo the `sphinx<4` pin (see #11725) to get working inheritance diagrams.

**Comment by pllim** [comment]
Update: We have unpinned Sphinx in #14140

**Comment by ayshih** [comment]
The bug fixes have been merged upstream (https://github.com/sphinx-doc/sphinx/pull/10614 and https://github.com/astropy/sphinx-automodapi/pull/172), so will presumably show up in respective new releases, but there will potentially be an incompatibility between our theme and the next release of Sphinx (see pydata/pydata-sphinx-theme#1404).

**Comment by ayshih** [comment]
It took over seven years, but this issue can finally be closed!  Proof: https://docs.astropy.org/en/latest/time/ref_api.html#class-inheritance-diagram (which also correctly links to the Python docs if you click on the `tzinfo` box)

**Comment by pllim** [comment]
Thank you, @ayshih !!!
