### ISSUE TITLE
No difference between RotateCelestial2Native and RotateNative2Celestial?

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#4938]
I was playing around with these two models `astropy.modeling.rotations.RotateNative2Celestial` and `astropy.modeling.rotations.RotateCelestial2Native` and I do not see any difference between them:

```python
>>> from astropy.modeling import rotations
>>> n2c = rotations.RotateNative2Celestial(lon=20, lat=56, lon_pole=20)
>>> c2n = rotations.RotateCelestial2Native(lon=20, lat=56, lon_pole=20)
>>> n2c(15, 25)
(191.23272897093648, 58.78612311737761)
>>> c2n(15, 25)
(191.2327289709365, 58.78612311737761)
>>> # NOTE: n2c evaluates to the same angle as c2n!!!
>>> c2n(*c2n(15, 25))
(15.000000000000009, 24.999999999999993)
>>> c2n(*n2c(15, 25))
(14.999999999999993, 24.999999999999993)
>>> n2c(*n2c(15, 25))
(14.99999999999998, 24.999999999999993)
```

What is the point of having two different models that evaluate to the same thing?

**Comment by nden** [comment]
Hint: Try also `EulerAngleRotation` with the appropriate inputs.

**Comment by mcara** [comment]
Instead of trying to figure out what are the "appropriate inputs" to , let me try to repeat my test using pre-https://github.com/astropy/astropy/pull/4881 version of `astropy`:

```python
>>> import astropy
>>> astropy.__version__
u'1.2.dev14976'
>>> from astropy.modeling import rotations
>>> n2c = rotations.RotateNative2Celestial(lon=20, lat=56, lon_pole=20)
>>> c2n = rotations.RotateCelestial2Native(lon=20, lat=56, lon_pole=20)
>>> n2c(15, 25)
(191.2327289709365, 58.78612311737761)
>>> c2n(15, 25)
(-168.7672710290635, 58.78612311737761)
```
So, in the past these two models used to be different but they are not different any longer. However, if you say this is how things should be and regression tests have not detected anything - then maybe that is how things should be.

@philhodge @eteq You have reviewed https://github.com/astropy/astropy/pull/4881. What do you think about this issue?

**Comment by mcara** [comment]
If both `RotateNative2Celestial` and `RotateCelestial2Native` are supposed to evaluate to identical values for identical arguments, then what is the point of having two distinct model classes?

**Comment by philhodge** [comment]
On 05/17/2016 02:31 PM, Mihai Cara wrote:
> If both |RotateNative2Celestial| and |RotateCelestial2Native| are 
> supposed to evaluate to identical values for identical arguments, then 
> what is the point of having two distinct model classes?

In general, they're not supposed to.  I get the same (or nearly the 
same) output when the lon and lon_pole arguments are the same, but not 
otherwise, e.g.:

 >>> n2c = rotations.RotateNative2Celestial(lon=81, lat=56, lon_pole=81)
 >>> c2n = rotations.RotateCelestial2Native(lon=81, lat=56, lon_pole=81)
 >>> n2c(37., 84.)
(89.36531270558771, 60.05931517695784)
 >>> c2n(37., 84.)
(89.36531270558773, 60.05931517695784)

 >>> n2c = rotations.RotateNative2Celestial(lon=20, lat=56, lon_pole=30)
 >>> c2n = rotations.RotateCelestial2Native(lon=20, lat=56, lon_pole=30)
 >>> n2c(15, 24)
(174.8721096903736, 56.16467847598726)
 >>> c2n(15., 24.)
(201.40915746401382, 57.79043168824408)

**Comment by mcara** [comment]
@philhodge Even for this case something is different compared to the old version:

```python
>>> import astropy
>>> astropy.__version__
>>> from astropy.modeling import rotations
>>> n2c = rotations.RotateNative2Celestial(lon=20, lat=56, lon_pole=30)
>>> c2n = rotations.RotateCelestial2Native(lon=20, lat=56, lon_pole=30)
>>> n2c(15, 25)
(174.39321400283808, 57.129400847524494)
>>> c2n(15, 25)
(-158.7672710290635, 58.78612311737761)
```
Notice -158.7672710290635 -> 201.40915746401382 which is probably a good thing.

Then the question is, are ``RotateNative2Celestial`` and ``RotateCelestial2Native`` not to be used when ``lon=lon_pole``.

**Comment by mcara** [comment]
And if ``RotateNative2Celestial`` and ``RotateCelestial2Native`` can be used with ``lon=lon_pole``, then which result is correct: old one (see https://github.com/astropy/astropy/issues/4938#issuecomment-219807819) or the new result (both models return the same value)?

**Comment by philhodge** [comment]
On 05/17/2016 02:21 PM, Mihai Cara wrote:
> >>>  astropy.__version__
> u'1.2.dev14976'
> >>>  from  astropy.modelingimport  rotations
> >>>  n2c=  rotations.RotateNative2Celestial(lon=20,lat=56,lon_pole=20)
> >>>  c2n=  rotations.RotateCelestial2Native(lon=20,lat=56,lon_pole=20)
> >>>  n2c(15,25)
> (191.2327289709365,58.78612311737761)
> >>>  c2n(15,25)
> (-168.7672710290635,58.78612311737761)

The first elements in the output from n2c and c2n actually are the same, 
it's just that 360 should have been added to the c2n value:

 >>> 191.2327289709365 - -168.7672710290635
360.0

Phil

**Comment by mcara** [comment]
@philhodge Yes, I know, that is why I said: _"Notice -158.7672710290635 -> 201.40915746401382 **which is probably a good thing**."_

**Comment by mcara** [comment]
When ``lon==lon_pole``, equations (2) and (5) in http://www.aanda.org/articles/aa/abs/2002/45/aah3860/aah3860.html essentially become "the same" (in form) hence identical values.
