### ISSUE TITLE
wcs bounds_check broken if called before the first wcs transformation

### ISSUE THREAD

**Issue by amaurea** [astropy/astropy#4957]
If `wcs.bounds_check` is called before the first coordinate transformation, regardless of its arguments, the output of the following transformations will be `NaN`. Performing a single transformation before calling it avoids the problem, and results in correct behavior. The example below illustrates this. Uncomment the commented line to go from broken to correct behavior:

    from astropy.wcs import WCS
    wcs = WCS(naxis=2)
    wcs.wcs.ctype = ["RA---CAR","DEC--CAR"]
    wcs.wcs.cdelt = [10,10]
    wcs.wcs.crval = [-90,90]
    wcs.wcs.crpix = [10,1]

    #wcs.wcs_pix2world(0,0,0)
    wcs.wcs.bounds_check(False, False)

    for i in range(40):
            x, y = i, 0
            ra, dec = wcs.wcs_pix2world(x,y,0)
            print "%2d %8.3f %8.3f %8.3f %8.3f" % (i, x, y, ra, dec)

With the first `wcs_pix2world` in place, this should print `NaN` for every output coordinate. After uncommenting, every line should be valid.

I guess that wcslib is not properly initialized before the first coordinate transformation is performed.

**Comment by pllim** [comment]
What version of Astropy are you using? Knowing that can pinpoint whether this is something that is already addressed or not in later versions.

**Comment by mcara** [comment]
I think everything is working as it is supposed to work. After defining a WCS you should call [wcs.Wcsprm.set()](http://docs.astropy.org/en/stable/api/astropy.wcs.Wcsprm.html#astropy.wcs.Wcsprm.set) **if you will not be calling a coordinate conversion function**.

Documentation for this function states: _"Note that this routine need not be called directly; it will be invoked by ``p2s`` and ``s2p`` if necessary. Some attributes that are based on other attributes (such as ``lattyp`` on ``ctype``) may not be correct until after ``set`` is called."_ Well, the problem in your example is that you are calling ``bounds_check`` on an object that was not yet initialized (=set) => who know how the bounds end up being set-up (based on who knows what ``ctype``).

Thus I do not view this as a bug or a problem in the code but rather improper usage. Possibly, this behavior should be better explained/documented in the documentation.

Here is your example modified to initialize the WCS before the call to ``bounds_check``:

```python
>>> from astropy.wcs import WCS
>>> wcs = WCS(naxis=2)
>>> wcs.wcs.ctype = ["RA---CAR", "DEC--CAR"]
>>> wcs.wcs.cdelt = [10, 10]
>>> wcs.wcs.crval = [-90, 90]
>>> wcs.wcs.crpix = [10, 1]
>>> wcs.wcs.set()
>>> wcs.wcs.bounds_check(False, False)
>>> for i in range(40):
>>>     x, y = i, 0
>>>     ra, dec = wcs.wcs_pix2world(x, y, 0)
>>>     print("{:d} {} {} {} {}".format(i, x, y, ra, dec))
```
