### ISSUE TITLE
Table documentation and "broken" links to pandas

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4968]
I've just noticed that links to pandas do not work. For example [here](http://docs.astropy.org/en/stable/api/astropy.table.Table.html#astropy.table.Table.to_pandas) or [here](http://docs.astropy.org/en/stable/api/astropy.table.Table.html#astropy.table.Table.from_pandas).

I'm not sure if that needs fixing and if it does if one should not attempt to link (double backticks instead of single ones) or include pandas to the intersphinx-conf.py.

**Comment by bsipocz** [comment]
@MSeifert04 - #4556 already takes care of it.
