### ISSUE TITLE
Why are you using lightweight tags for releases?

### ISSUE THREAD

**Issue by jhunkeler** [astropy/astropy#4969]
If I execute `git describe` I see this:

```bash
$ git describe
v1.0rc1-3660-g8d56e05
```

I can _maybe_ see applying a lightweight tag for tracking a commit you don't care about (like a checkpoint), but for a proper release it makes little sense. I only care about this because I'm building astropy automatically on a daily basis. Not having relevant version data attached to my conda packages is not very appealing: `astropy-v1.0rc1.dev3660-npXXXpyXX_0`

Can your team please switch back to using annotated tags for releases? 

**Additional data:**

```bash
$ git describe --debug
searching to describe HEAD
finished search at 02b923b5f9cf3db6a59450ad7c17abb9a2a9fae8
 annotated       3660 v1.0rc1
 annotated       5965 v0.4
 annotated       5989 v0.4rc2
 annotated       6063 v0.4rc1
 annotated       8845 v0.3rc1
 annotated       8974 v0.3b1
 annotated      12570 v0.2
 annotated      12583 v0.2rc1
 annotated      12631 v0.2b2
 annotated      12716 v0.2b1
traversed 13925 commits
v1.0rc1-3660-g8d56e05
```

```bash
$ git tag
v0.1
v0.2
v0.2.1
v0.2.2
v0.2.3
v0.2.4
v0.2.5
v0.2b1
v0.2b2
v0.2rc1
v0.3
v0.3.1
v0.3.2
v0.3b1
v0.3rc1
v0.4
v0.4.1
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
v0.4rc1
v0.4rc2
v1.0
v1.0.1
v1.0.2
v1.0.3
v1.0.4
v1.0.5
v1.0.6
v1.0.7
v1.0.8
v1.0.9
v1.0rc1
v1.0rc2
v1.1
v1.1.1
v1.1.2
v1.1b1
v1.1rc1
v1.1rc2
```

**Comment by juliantaylor** [comment]
the tags are signed and annotated, the problem is that they are performed on the maintenance branches so they are not reachable from master. `v1.0rc1` is the latest reachable tag. You will have to find another way to version your dev packages.

**Comment by jhunkeler** [comment]
I'll just keep doing what I'm doing then.

```
When the fox hears the rabbit scream he comes a-runnin', but not to help.

                                                          - Thomas Harris
```
