### ISSUE TITLE
Table sorting with Time object dtype column fails

### ISSUE THREAD

**Issue by kgabor** [astropy/astropy#4981]
The following code crashes on Ubuntu 14.04 LTS system python3, pip installed astropy:
[EDIT (by @taldcroft): the segfault is/was an upstream bug in numpy, fixed in numpy 1.10.4]

```
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.10.1'
>>> from astropy.time import Time
>>> from astropy.table import Table
>>> import astropy
>>> astropy.__version__
'1.1rc1'
>>> B=Table([[0,0,0],['bkgnd_level','bkgnd_madrms ','det_Nstars'],
...               Time(['2018-01-01T12:00:10.000','2018-01-01T12:00:10.000','2018-01-01T12:00:10.000'])],
...              names=('ImageNum','Name','UtcTime')
... )
>>> B.sort(keys=['UtcTime','ImageNum','Name'])
Segmentation fault (core dumped)
```

It took about 2-3 sec on my computer until it fails. The failure was not systematic, with a one character shorter, str12, 'Name' column ('bkgnd_madrms ' -> ,'bkgnd_madrms') the crash did not happen. Instead, I got the same error as following an upgrade below. 

Please also note that the crash happens with other, non Time object dtype columns (a boost::python object that supports comparisons), too. I could not reproduce the failure with strings + ints columns only.

After pip upgrade, I receive the following error:

```
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.11.0'
>>> from astropy.time import Time
>>> from astropy.table import Table
>>> import astropy
>>> astropy.__version__
'1.1.2'
>>> B=Table([[0,0,0],['bkgnd_level','bkgnd_madrms ','det_Nstars'],
...               Time(['2018-01-01T12:00:10.000','2018-01-01T12:00:10.000','2018-01-01T12:00:10.000'])],
...              names=('ImageNum','Name','UtcTime')
... )
>>> B.sort(keys=['UtcTime','ImageNum','Name'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gkovacs/.local/lib/python3.4/site-packages/astropy/table/table.py", line 2203, in sort
    col[:] = col.take(indexes, axis=0)
TypeError: 'Time' object does not support item assignment
>>> 
```

**Comment by taldcroft** [comment]
This is an unfortunate limitation of the `Time` class right now.  Once a `Time` object is created it is considered "immutable".  This allows for various performance and coding optimizations, but it is recognized that this is a problem in several contexts.

The plan is to change this behavior but in the meantime one can use this workaround:
```
idx = B.argsort(keys=['UtcTime','ImageNum','Name'])
B = B[idx]
```

**Comment by kgabor** [comment]
Do you think that the segfault above is also related to the Time object assignment or it was an independent bug in the sorting ?

**Comment by taldcroft** [comment]
@kgabor - tough to say.  When you say "After pip upgrade..", what exactly did that change?

**Comment by kgabor** [comment]
@taldcroft - astropy and numpy only were upgraded as shown above. I am just wondering whether the underlying numpy sorting had problems with object dtype element comparisons in some, actually hard to reproduce cases. If you think that astropy table does not do C-style direct memory access, I may try to reproduce the crash simply with numpy arrays.

**Comment by taldcroft** [comment]
@kgabor - Yes, there is no C-style direct memory access in the astropy code path for the `sort` method.  One possible source of problems is that `sort` calls `argsort` which calls `Table.as_array()` which will convert a `Time` column into a numpy object array of individual `Time` objects.  Then that structured array gets sorted.  At least that is my recollection of the process.  Maybe something goes awry there?

**Comment by taldcroft** [comment]
@kgabor - I did a little playing around and discovered that the segfault is strictly related to the numpy version.  I ran your code with a recent astropy dev (1.2.dev15457) using numpy version 1.9, 1.10.1, and 1.11.  Both 1.9 and 1.11 are fine (using my suggested `argsort` workaround) while 1.10.1 gives a segfault.

It's quite possible this is related to https://github.com/numpy/numpy/issues/6922 which was fixed in 1.10.4.

**Comment by kgabor** [comment]
@taldcroft - Thanks for the investigation.

**Comment by pllim** [comment]
So, can we close this?

**Comment by astrofrog** [comment]
It sounds like this can indeed be closed :)
