### ISSUE TITLE
Differences in fits.Header initialization from another header compared to initialization from a dictionary

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#5005]
I think it is widely believed (see https://github.com/astropy/astropy/issues/4648#issuecomment-191116508, https://github.com/astropy/astropy/issues/4990#issuecomment-223061098) that a `fits.Header` behaves like a dictionary. Recently, support for initialization of `fits.Header` from Python dictionaries was added (`fits.Header` was already supporting initialization from _another_  header object) - see https://github.com/astropy/astropy/pull/4663.

In light of conversations in https://github.com/astropy/astropy/issues/4990, I would like to bring your attention to the following differences in initializing from a `fits.Header` vs a true dictionary: When a header is initialized from another header, the new header object is a shallow copy of the original header.

``` python
>>> from astropy.io.fits.header import Header
>>> d1 = {'a': 1, 'b': 2}
>>> h1 = Header(d1)
>>> h1
A       =                    1                                                  
B       =                    2                                                  
>>> d1['a'] = -1
>>> h1
A       =                    1                                                  
B       =                    2                                                  
>>> h2 = Header(h1)
>>> h2
A       =                    1                                                  
B       =                    2                                                  
>>> h1['a'] = -1
>>> h2
A       =                   -1                                                  
B       =                    2                                                  
```

It is not obvious what would have been the original intention behind these differences in implementation of initialization from dict vs. `fits.Header`. For the very least, I believe, this is worth documenting.

**Comment by pllim** [comment]
@MSeifert04 , since you implemented #4663, do you have any comment on this behavior?

**Comment by MSeifert04** [comment]
I actually implemented the behaviour of ``dict(dict())`` (which makes a copy). I'm not really sure if I had tested it against ``Header(Header())``. But it would be (almost) impossible to "fix" it in a way that wouldn't do a copy.

@mcara Do you think a short comment is sufficient or should the behaviour be changed?

**Comment by mcara** [comment]
@MSeifert04 I don't know. This kind of goes with these discussions about ``.copy()``. I feel that both a dictionary and a ``fits.Header`` should be treated equally since in many ways these are "similar" objects. For this reason, I think ``Header(Header)`` should behave like ``dict(dict)``. I know it is hard to modify your code to behave like old ``Header(Header)`` but I do not think this is necessary. I think ``Header(Header)`` should behave like ``Header(Header.copy())``. However, I wonder if this will break any existing code @embray ?

**Comment by MSeifert04** [comment]
Not sure if this issue is really resolved. In the end I didn't make the hard change from shallow copy -> deep copy but only optionally enabled it.

**Comment by pllim** [comment]
@mcara , feel free to re-open if the new option is not enough.
