### ISSUE TITLE
Error opening ECSV table with empty boolean column

### ISSUE THREAD

**Issue by samverstocken** [astropy/astropy#5009]
Hi,

I am experiencing an annoying bug with the Table class.
When I save an empty Table with an arbitrary number of columns, where at least one column is of boolean type, with the ascii.ecsv format, re-opening this table will result in the following error: "ValueError: Column column_name failed to convert".
This does not happen if there is no column of type 'bool'.

**Comment by taldcroft** [comment]
Fix in #5010.

**Comment by samverstocken** [comment]
Thanks!
