### ISSUE TITLE
Quantity initialization speed

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5034]
I just find it interesting that `Quantity(...)` is a little faster than `arr * unit`, as illustrated below. Feel free to close if this is not worth addressing.

```python
In [1]: import numpy as np

In [2]: import astropy

In [3]: from astropy import units as u

In [4]: astropy.__version__
Out[4]: u'1.2.dev15605'

In [5]: a = np.arange(10000)

In [6]: %timeit a * u.AA
The slowest run took 4.30 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 44.7 µs per loop

In [7]: %timeit u.Quantity(a, u.AA)
The slowest run took 4.09 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 35.2 µs per loop

In [8]: %timeit a * u.AA
10000 loops, best of 3: 44.4 µs per loop

In [9]: %timeit u.Quantity(a, u.AA)
10000 loops, best of 3: 35.4 µs per loop
```

**Comment by mhvk** [comment]
@pllim - there is more work in the `array * unit` case: first `cPython` calls `array.__mul__`, which returns `NotImplemented` as it doesn't know how to handle units. Then, `unit.__rmul__` is called, which ends up returning `Quantity(array, unit)`. 
Note that there are two further slowdowns: you make an array of `int`, which get converted to `float64` by default, and also gets copied (indeed, there was quite a long discussion in #3174 whether it might be possible to have some context manager with which one could set whether or not data is copied by default).

```
In [2]: a = np.arange(10000)
# Note: a is integer here!
In [3]: %timeit a * u.AA
10000 loops, best of 3: 27.9 µs per loop

In [4]: %timeit u.Quantity(a, u.AA)
10000 loops, best of 3: 20.9 µs per loop

In [5]: %timeit u.Quantity(a, u.AA, copy=False)
10000 loops, best of 3: 15.4 µs per loop

In [6]: a = np.arange(10000.)
# Now use reals
In [7]: %timeit a * u.AA
10000 loops, best of 3: 18.8 µs per loop

In [8]: %timeit u.Quantity(a, u.AA)
100000 loops, best of 3: 12.2 µs per loop

In [9]: %timeit u.Quantity(a, u.AA, copy=False)
100000 loops, best of 3: 6.54 µs per loop
```

**Comment by pllim** [comment]
Interesting. Thanks for the clarification, @mhvk! I wonder if this is worth pointing out in the doc because most examples use the `*` notation, which is incidentally the slowest right now. But then again, maybe no one cares about 19 µs vs 7 µs.

**Comment by mhvk** [comment]
@pllim - given #3174, I think it is important to document it somewhere. I made a minimal change in #5035. Let me know what you think.
