### ISSUE TITLE
Table row element is not a Quantity

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5042]
Using the following file:
[ztable.txt](https://github.com/astropy/astropy/files/305477/ztable.txt)

```python
In [1]: from astropy.io import ascii

In [2]: tab = ascii.read('ztable.txt', format='ecsv')

In [3]: tab
Out[3]: 
<Table length=3>
      id            ra            dec       
                   deg            deg       
    str13        float64        float64     
------------- ------------- ----------------
MOS_1_010_133 359.996992846 0.00394170958794
MOS_1_010_135 359.988641919 0.00562150075824
MOS_1_010_137 359.990036305 0.00564101286996

In [4]: row = tab[0]

In [5]: row
Out[5]: 
<Row index=0>
      id            ra            dec       
                   deg            deg       
    str13        float64        float64     
------------- ------------- ----------------
MOS_1_010_133 359.996992846 0.00394170958794

In [6]: row['ra']
Out[6]: 359.99699284600001  # deg is missing!
```

Is this a bug or intentional?

**Comment by mhvk** [comment]
This reflects that fact that table `Column` objects are not `Quantity`, and their unit is generally ignored (and removed if a single element is taken). [There is a long argument about back-wards compatibility behind this...]

If you read the table using `QTable` -- which I at least would recommend using over `Table` any time you do not need masks -- do things work OK? (i.e., `tab = QTable.read('ztable.txt', format='ecsv')`)

**Comment by pllim** [comment]
Yes, that works. Thanks!
