### ISSUE TITLE
Equivalencies don't work with squared values

### ISSUE THREAD

**Issue by steven-murray** [astropy/astropy#5044]
Hi,

Thanks for the awesome package. Just wondering if there's a reason that the following doesn't work:

```
import astropy.units as u
a = 1 * u.Jy**2
a.to(u.K**2, equivalencies=u.brightness_temperature(...))
```

i.e. it works in Janksy, but not when it's squared. Is there a trivial way to make this work?

Cheers,
Steven

**Comment by mhvk** [comment]
@steven-murray - thanks!  `units` and `Quantity` were definitely what got me hooked to astropy!

As for the equivalencies: the reason squares, etc., do not work is partially a wish to ensure that unwanted conversions still raise an error -- which seems best done by making things work only for particular physical types -- and partially that it is not all that easy to implement. As it [works now](https://github.com/astropy/astropy/blob/master/astropy/units/core.py#L814), the code goes through every pair of `from` and `to` units in an equivalency, trying whether the input and output can be converted to those, and if so, use the associated function to make the leap to the equivalent unit. It would not be that easy to add support for ignoring the power to which the unit is raise.

Anyway, my own sense is that it is better to keep using equivalencies only for well-defined physical properties, so in your case, you would have to make sure you are actually converting something that is a "brightness temperature". (Indeed, in that respect, I'm curious what brought this up; did you perhaps have a variance in brightness temperature?)

p.s.  If you look closely at the linked code, you'll see that there is one exception: `dimensionless_angles` allows conversion for any power of `u.rad`; but this is very much treated as a special case.

**Comment by steven-murray** [comment]
@mhvk -- thanks for the quick and helpful reply! 

Yes, my physical case is a variance (in Jy), in particular a power spectrum of the EoR 21cm signal. I actually have Jy^2 . MHz^2 and need to convert to mK^2 . Mpc^6 . h^-6 via cosmological transforms. 

So is my best bet then to add a specific rule for Jy^2 into the equivalency list? I've done this, but then I also have the problem that it doesn't seem to decompose the units, so if I pass Jy^2 . MHz^2, it can't convert the Jy^2 part and leave the MHz alone, it just throws an error. I could add a rule for the MHz^2 part as well, but then I really might as well just be writing a simple function to convert  the units myself, since I have to do everyone myself anyway. 

Any thoughts?

**Comment by mhvk** [comment]
@steven-murray - This sounds sufficiently complicated that I think it will help any other users of your code much more if you just explicitly convert! (the equivalencies are nifty, but personally I think they should be used sparingly, mostly to help convert input/output;).

**Comment by mhvk** [comment]
I'm closing this as I don't see an easy-to-understand way to add the functionality.
