### ISSUE TITLE
DOC: duplicated table on unified file read/write page

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#5046]
There are two tables with the possible formats on the page of  `http://docs.astropy.org/en/stable/io/unified.html`, one for everything and one for the ascii ones.

I think it would be nice to merge them into the first one (http://docs.astropy.org/en/latest/io/unified.html#built-in-table-readers-writers), but keeping the description column from the other one (and write the one liner for the non ascii ones).

Also what about removing the deprecated ones from the list, they are deprecated for a while now so it seems sensible to remove them from the docs.

**Comment by jpowerwa** [comment]
Pull request created: https://github.com/astropy/astropy/pull/5112

This is my first astropy docs contribution, and I hope it meets expectations. Feedback very welcome, of course.

**Comment by bsipocz** [comment]
This was indeed done, so closing the issue.
