### ISSUE TITLE
IERS URL timing out

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy#5059]
The IERS tables that describe Earth's orientation ordinarily get downloaded from this URL stored in the `utils.iers` module:

```
In [18]: from astropy.utils import iers

In [19]: iers.IERS_A_URL
Out[19]: 'http://maia.usno.navy.mil/ser7/finals2000A.all'
```

At present (and maybe for some time now), [the above URL](http://maia.usno.navy.mil/ser7/finals2000A.all) times out always. I found from the [IERS webpage](https://www.iers.org/IERS/EN/DataProducts/EarthOrientationData/eop.html) that there's an alternative server which is serving the table appropriately [here](http://toshi.nofs.navy.mil/ser7/finals2000A.all), at 

```
http://toshi.nofs.navy.mil/ser7/finals2000A.all
```

This is causing a bunch of mysterious IERS warnings and errors in astroplan. Should we switch [the hard-coded URL in astropy](https://github.com/astropy/astropy/blob/1862f243b2f7a6dc0accf44a15f0ba7fb93069df/astropy/utils/iers/iers.py#L40) to the backup URL until the normal server is restored?

I checked to see if the IERS webpage maintainers have an email address that we can contact, but they left only a phone number on the webpage (for the adventurous: 202-762-1518). 

cc @eteq (@kvyh – heads up, astroplan tests may fail due to this problem even if the code you wrote is fine)

**Comment by pllim** [comment]
Could I be seeing the same thing at [#5051(comment)](https://github.com/astropy/astropy/pull/5051#issuecomment-225082155)? c/c @taldcroft , @mhvk

**Comment by bmorris3** [comment]
That's possible, @pllim. The debugging discussion happening in that thread is similar to the one I was having in my own head a few minutes ago.

**Comment by mhvk** [comment]
The URL seems to work again (just pasted it in my browser). The fact that you are getting "mysterious IERS warnings" does suggest though that the IERS code may need to handle the timeouts more graciously, or have warnings that make clearer what is happening.

**Comment by pllim** [comment]
For unreliable test, perhaps mark it as `xfail` under certain conditions? In this case, it would be a timeout error or `HTTPError`.

**Comment by taldcroft** [comment]
Well I certainly hope we have not erred in automatically using the IERS web site.  

However, please do note that it is easy to opt out of this behavior and return to handling IERS-related transforms manually.  See http://astropy.readthedocs.io/en/latest/utils/iers.html.  In particular the configuration parameters section and subsequent sections talk about how to disable auto-download or do things manually.

**Comment by taldcroft** [comment]
It would be technically feasible to try a backup website if the primary fails.  I don't know enough about their redundancy to know if that is actually valuable or if it would just mean taking twice as long to fail.

**Comment by astrofrog** [comment]
We could always use data.astropy.org as a mirror?

**Comment by taldcroft** [comment]
Can we set a cron job to keep data.astropy.org up to date?

**Comment by astrofrog** [comment]
I'm sure we could - I guess the question is just on which server to set up the cron job.

**Comment by eteq** [comment]
@bmorris3 - can you clarify where in the IERS web site it points you to there?  All the links I saw there (in admittedly a cursory glance) are at ``datacenter.iers.org``... which @mhvk investigated and got an official answer from the IERS folks that it is a mirror that of the ``maia`` copy.  I wonder if *that* should be the fallback, rather than ``toshi``?

**Comment by taldcroft** [comment]
@eteq et al. - do you think adding support for fallback sites is release-critical?  I think I know how to do it, but it's a question of whether we (1) *should* do this, and (2) if it is in 1.2.

**Comment by bmorris3** [comment]
@eteq – [the IERS webpage](https://www.iers.org/IERS/EN/DataProducts/EarthOrientationData/eop.html) directs you to [this webpage at the `datacenter.iers.org` address](https://datacenter.iers.org/web/guest/eop/-/somos/5Rgv/product/6), which provides these URLS as the "Source:"
```
http://maia.usno.navy.mil/ser7/ [ser7.dat]

Alternative server:
http://toshi.nofs.navy.mil/ser7/
```

**Comment by mhvk** [comment]
I think the `datacenter.iers.org` would be a good enough backup. I don't think it makes much sense to add yet another copy at `data.astropy.org`.

That said, most important would seem to be to have a sufficiently informative error message; I'm fine with just sticking to one server.

**Comment by astrofrog** [comment]
@taldcroft - I think a fallback mechanism and a better error if both fail would make sense. If you think you can do this in the next couple of hours, I can delay the release candidate - I would really like to get the RC out today or tomorrow morning at the very latest.

**Comment by taldcroft** [comment]
@astrofrog - I agree with @mhvk that this can wait.  I think that the existing warning would be sufficient for programmatic use, it's just that emitted warnings don't show up in testing.  And the situation that you encountered today is really just a problem in testing.  It failed because the real IERS-A file was already loaded and it didn't pick up the stubbed version for testing.

**Comment by pllim** [comment]
@bmorris3 is this still an issue? The last update was in 2016, so just want to make sure.

**Comment by pllim** [comment]
Does #8308 address this as well?

**Comment by mhvk** [comment]
Agreed with @pllim that #8308 addresses at least the basic point here, so closing. Probably best to open a new issue if there are still problems.
