### ISSUE TITLE
Warning message mentioning PyFITS

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#5062]
The ``astropy.io.fits.verify`` (https://github.com/astropy/astropy/blob/ffc0a89b2c42fd440eb19bcb2f93db90cab3c98b/astropy/io/fits/verify.py#L112) appends a message saying that ``PyFITS`` uses "zero-based indexing". Is this some historical artifact or is it common to refer to astropy.io.fits as pyfits?

**Comment by astrofrog** [comment]
astropy.io.fits used to be pyfits - but any reference to pyfits should now be updated to mention astropy.io.fits
