### ISSUE TITLE
cannot import name solar_system_ephemeris

### ISSUE THREAD

**Issue by niyuan1** [astropy/astropy#5101]
Following instructions on [http://docs.astropy.org/en/latest/coordinates/solarsystem.html#astropy-coordinates-solarsystem](url), I've crashed at `from astropy.coordinates import solar_system_ephemeris`, which gives `ImportError: cannot import name solar_system_ephemeris`. In the end, I want to use get_moon but that also gives ImportError. I don't know what's wrong, is there some dependency I'm missing?

My astropy.test() results are attached 

[test.txt](https://github.com/astropy/astropy/files/316253/test.txt)

**Comment by pllim** [comment]
Are you using the dev version of Astropy? I think those are new.

**Comment by MSeifert04** [comment]
@niyuan1 That was a feature added in astropy 1.2 so you cannot use it with 1.1.2.

You need to install the latest (either manually install from the master-branch of astropy) or the release candidate from pip to use the `solar_system_ephemeris`.

**Comment by niyuan1** [comment]
Yes, that did the trick! I did need a newer build, thanks very much.
