### ISSUE TITLE
Notes on release process following v1.2 and v2.0

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5120]
Here are some small things to fix based on my v1.2 release notes:
- [x] Step 4 (running tests) should be done **after** Step 7 (changing branch)
- [x] In step 20, we should use the branch name not the version (which are slightly different)
- [x] When updating the astropy website (point 23), if this is a new major release, we should add a new entry in the 'previous versions' of the docs
- [x] For releases that come after release candidates, we should make it clear that the title of the changelog section should be **replaced**, and the RC section headings should not be kept
- [x] Since it's easy to do, the latest 'stable' version of astropy in ci-helpers should be updated, so probably worth mentioning (though this could also be done by the ci-helpers once the release is announced)
- [x] We should mention that announcement emails need to be prepared, and give a list of mailing lists to email - this should include the step of adding the announcement to the astropy web site
- [x] For release candidates, we should mention that a wiki page should be created to collect test results
- [x] The release candidate instructions mention to ignore steps 21 and above, but step 22 (RTD) should be done for RCs
- [ ] In step 15, this won't run the tests with all the optional dependencies installed, so we should probably change that
- [ ] We should maybe recommend a set of additional tests to run when branching or making an RC - for example we often get reports from 32-bit linux systems, and issues that come from running tests twice in the same session. We might want to suggest these are done as soon as feature freeze, to have more time to work on those issues.
- [ ] We should add a mention in the feature freeze section of the release instructions to note that the "Release final vx.y" issue should get created at the time of feature freeze

EDIT (by bsipocz): Other suggestions based on 2.0 experience. The above list needs revision as we've already updated the release docs after the 1.3 release, so I expect most of it is either covered already or outdated (the numbering is definitely outdated). There are also a few new points worth discussing:

 - [ ] - point 12&13 could be moved to the bottom as there is no development going on on a bugfix branch anyway, so both the version and changelog can be dealt with once everything is ready and we're just waiting for the conda packages to being built
 - [ ] - if we keep building the wheels as part of the release, point 25 needs to be done before the wheels as they need to know about the new version tag
 - [x] - changelog script doesn't know about minor releases, be careful with backports after major releases (e.g. 3.0.1 PRs are already been merged, but 3.0 is not yet out, then hold up backporting the 3.0.1 ones until 3.0  is released from the branch)
 - [x] - remove mention of `suggest_backports.py` and update with the current suite of scripts.
 - [x] - mention that we now have `twine check`:  which can be used to make sure (amongst other things) that the rst that will be used on PyPI is fine 
 - [x] - add notes about having the latest Cython version when releasing, just to have a procedure that can be followed. e.g. `pip install Cython --upgrade` can be a step as suggested in https://github.com/astropy/astropy/issues/3473

**Comment by eteq** [comment]
> Step 4 (running tests) should be done after Step 7 (changing branch)

Actually maybe it's really that it should be split into two?  The first part of step 4 is "check travis", which is still useful to do before doing anything else.

>  For releases that come after release candidates, we should make it clear that the title of the changelog section should be replaced, and the RC section headings should not be kept

Maybe instead we should just not add the "rc" at all? (In that case we want to point that out in the release instructions, though)

> The release candidate instructions mention to ignore steps 21 and above, but step 22 (RTD) should be done for RCs

Oops, that's because I added an item at the top and didn't update in below.  I wonder if there's a way to reference step numbers in sphinx and have it number correctly?  Should look into that so that this doesn't keep happening...

> In step 15, this won't run the tests with all the optional dependencies installed, so we should probably change that

Maybe just say to ``pip install -r pip-requirements-dev``? Although it maybe should be tested *both* ways, because ``pip-requirements-dev`` includes things like Cython and jinja2 which are not necessarily "typical user".

>  We should maybe recommend a set of additional tests to run when branching or making an RC - for example we often get reports from 32-bit linux systems, and issues that come from running tests twice in the same session. We might want to suggest these are done as soon as feature freeze, to have more time to work on those issues.

A good idea in pricipal, but it might be really hard to do this in practice.  Or were you thinking to tell people to do some custom travis thingie or something?.

**Comment by bsipocz** [comment]
Following the release process for the helpers I run into the following error with PyPI during ``python setup.py build sdist register upload``. I propose to break that line up for more steps, doing a build and then upload separately. I remember that @eteq mentioned this or a similar problem while @astrofrog said that it still worked for him for other projects, but I can't find that issue/repo to check the exact details.

```
Registering astropy-helpers to https://upload.pypi.org/legacy/
Server response (410): This API is no longer supported, instead simply upload the file.
```

**Comment by astrofrog** [comment]
@bsipocz - what's weird is that I do get that error, but it works anyway

**Comment by astrofrog** [comment]
But if it's not working in some cases, should we switch to using ``twine``?

**Comment by bsipocz** [comment]
Nothing happens for me, though I don't have a ``~/.pypirc`` file. Maybe that's the source of my problem? https://packaging.python.org/distributing/#uploading-your-project-to-pypi

**Comment by astrofrog** [comment]
@bsipocz - ah yes, I do have a .pypirc file. Have you tried using twine instead?

**Comment by bsipocz** [comment]
Not yet, first trying the manual registration.

**Comment by bsipocz** [comment]
OK, twine is flawless.

**Comment by bsipocz** [comment]
Weirdly enough, I've run into the same upload issue to day with the helpers release, but it hasn't come up when I did the core releases. Anyway, probably most of these posts were addressed in the latest update of the release docs by Erik, but nevertheless I'll go through the list after 2.0 and add the missing points in order to be able to close off this one.

**Comment by eteq** [comment]
From slack discussion (by way of @astrofrog): `twine check` should be added to the steps.

**Comment by bsipocz** [comment]
@eteq - it's on the list already :)

**Comment by eteq** [comment]
Oops, I was looking top-down instead of bottom-up!

**Comment by eteq** [comment]
Maybe our immediate post-release assignment is to actually finish off this issue...

**Comment by pllim** [comment]
Step 20 is not Step 20 anymore, so no idea what you talking about. Do you still remember?

**Comment by bsipocz** [comment]
Sure, I suppose it can all be digged up. Hopefully by the release. Or the coordination meeting.

**Comment by pllim** [comment]
I am working on addressing some of these, but... 

> We might want to suggest these are done as soon as feature freeze, to have more time to work on those issues.

I don't see any good place in release procedures to list out things that needs to be done right after feature freeze. By the time someone gets to "how to release" page, it is too late.

**Comment by pllim** [comment]
Also not clear what is "point 12&13 could be moved to the bottom," so I'll leave that one alone for now.
