### ISSUE TITLE
issue with newline on Windows when writing ASCII table

### ISSUE THREAD

**Issue by calders** [astropy/astropy#5126]
When I run the following code:

``` python
>>> rows = [{"a":1},{"a":3}]
>>> t = Table(rows=rows)
>>> t.write("test.csv", format="ascii.csv")
```

the output looks like this:

```
a

1

3

```

(including the newlines)
I'm using Windows 7 and astropy 1.2.

**Comment by astrofrog** [comment]
For the record, the workaround was to pass a file object to ``t.write`` that was opened in binary mode.

**Comment by bsipocz** [comment]
We run into this same issue with https://github.com/astropy/astroquery/pull/894 where the writer is called as ``enlevels.write(f, format='ascii.no_header')``. 

I'll check whether can hack our current writer to use the suggested workaround.

**Comment by bsipocz** [comment]
@astrofrog - How did that workaround work? I got the error 
```
E           TypeError: a bytes-like object is required, not 'str'
```

**Comment by astrofrog** [comment]
I'm not sure if I was using Python 2 or 3, so that may make a difference.

**Comment by bsipocz** [comment]
Yes, on python2 the write doesn't raise an error, but then it doesn't seem to work either as the file only contains a whitespace when read back with normal python open/read, and with Table.read() it raises a ValueError.
```
ValueError: Inconsistent data column lengths: set([])
```

**Comment by saimn** [comment]
I think this is the same as #5299 so can be closed.

**Comment by bsipocz** [comment]
Indeed, however I suggest to close the other one as that was opened later and has less discussion.

**Comment by ysBach** [comment]
Encountered the problem and just found this issue.
Although it reproduces the original table when I read the table by ``test_read = Table.read('test.csv')``...

**Comment by astrofrog** [comment]
I just ran into this today!
