### ISSUE TITLE
Accuracy of get_sun function

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5130]
There was a report on the astropy mailing list that the get_sun may be giving incorrect results:

https://mail.scipy.org/pipermail/astropy/2016-May/004208.html

We should investigate this to determine if this is due to approximations we make, or if there is a real bug.

**Comment by StuartLittlefair** [comment]
I can't post on the mailing list, but this seems to be using an older version of astropy.

Also, ```get_sun``` returns coordinates in a GCRS frame, and you wouldn't expect the ra and dec of the Sun to be exactly zero in that frame. Using astropy v1.2 I find:

```python
In [1]: t=Time('2016-03-20 4:30:00')
In [2]: sun = coord.get_body('sun',t, ephemeris='jpl')
In [3]: sun.transform_to(coord.GeocentricTrueEcliptic(equinox=t))
Out[3]: 
<SkyCoord (GeocentricTrueEcliptic: equinox=2016-03-20 04:30:00.000): (lon, lat, distance) in (deg, deg, km)
    (359.99987074, -0.00017033, 148985306.52542835)>
```

**Comment by eerovaher** [comment]
I looks to me like this issue is safe to close without making any changes to `astropy`.
