### ISSUE TITLE
FITS ASCII table null value

### ISSUE THREAD

**Issue by philhodge** [astropy/astropy#5134]
Using Python 2.7.5; numpy version '1.9.1'; astropy version u'1.2.dev15800'.

astropy.io.fits apparently can't use a null string (I also tried a blank string with non-zero length) as the null value for an integer column in an ASCII table.  This was originally reported by Eric Jensen for a FITS file retrieved from the VizieR archive, hosted by the CDS, Strasbourg.  Here is an example.

Create an ASCII table containing an integer column::

```
>>> import numpy as np
>>> import astropy.io.fits as fits
>>> fd = fits.HDUList(fits.PrimaryHDU())
>>> x = np.arange(5, dtype=np.int32)
>>> c1 = fits.Column(name='x', format='I8', array=x, ascii=True)
>>> hdu = fits.TableHDU.from_columns([c1])
>>> hdu.header['tnull1'] = ' '
>>> fd.append(hdu)
>>> fd.writeto("ascii_null.fits")
```

Then I used tedit in the tables package in iraf to change the value in the third row from 2 to the null value.  Use od to see the last part of the file, including the keyword that defines the null value (the keyword value is two adjacent quotes)::

```
$ od -j 3760 -A d -c ascii_null.fits
0003760   T   N   U   L   L   1           =       '   '
0003776
*
0003840   E   N   D
0003856
*
0005760                               0                               1
0005776                                                               3
0005792                               4
0005808
*
0008640
```

fitsverify does not show any warnings or errors in this table::

```
$ fitsverify ascii_null.fits

              fitsverify 4.16 (CFITSIO V3.350)
              --------------------------------


File: ascii_null.fits

2 Header-Data Units in this file.

=================== HDU 1: Primary Array ===================

 5 header keywords

 Null data array; NAXIS = 0

==================== HDU 2: ASCII Table ====================

 13 header keywords

   (1 columns x 5 rows)

 Col# Name (Units)       Format
   1 x                    I8

++++++++++++++++++++++ Error Summary  ++++++++++++++++++++++

 HDU#  Name (version)       Type             Warnings  Errors
 1                          Primary Array    0         0
 2                          ASCII Table      0         0

**** Verification found 0 warning(s) and 0 error(s). ****
```

astropy.io.fits can't read the data::

```
>>> fd = fits.open("ascii_null.fits")
>>> print("{}".format(fd[1].data.field("x")))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/stsci/ssbdev/python/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 727, in field
    converted = self._convert_other(column, field, recformat)
  File "/usr/stsci/ssbdev/python/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 897, in _convert_other
    field = self._convert_ascii(column, field)
  File "/usr/stsci/ssbdev/python/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 869, in _convert_ascii
    (exc, indx + 1))
ValueError: invalid literal for int() with base 10: ''; the header may be missing the necessary TNULL1 keyword or the table contains invalid data
```

**Comment by pllim** [comment]
@embray , is this an issue with FITS standards?

**Comment by embray** [comment]
It looks like a bug in [`_convert_ascii`](https://github.com/astropy/astropy/blob/01d98073c117026fc7bdd3f558a3ecb5c2a75b5e/astropy/io/fits/fitsrec.py#L863)

The `np.array()` call is trying to convert an array of string-representations of integers to an array of actual integers.  It's hitting on a value `''` (empty-string) which does not convert to an integer.  So it looks like the logic in that method is failing to replace the `TNULL1` value with `'0'` in the array of strings.  Not sure the exact line where it's failing.
