### ISSUE TITLE
Windows compiler internal error with astropy dev 

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#5137]
I get a strange `An internal error has occurred in the compiler` error on appveyor when trying to install the dev version of astropy here:

https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.456/job/k8jqubgw94fyyr99#L2277

The very same commit passed all the tests before ([~7 days ago](https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.449/job/5ah9rwcy0dyo15ps)). There wasn't much change in master since then, and I can't see any that would cause this. 
So it would be great if someone could check it to help decide whether it's an astropy or a compiler or a conda issue.

**Comment by mwcraig** [comment]
FWIW, I'd bet it is changes to conda (v4.1.2 last week vs v4.1.4 this week) that broke things....

**Comment by bsipocz** [comment]
I've tried to run it with conda 4.1.2 and it still fails:
https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.457/job/n7r4sh7qgfvk41f6

**Comment by bsipocz** [comment]
(This whole stuff came up in the PR where I try to pin conda to 4.1.3  due to another set of failures.)

**Comment by mwcraig** [comment]
Yeah, saw that issue on conda/conda, closed the browser tab immediately :).

One other possibility is that it is a change in appveyor itself is causing issues (see http://www.appveyor.com/updates). If pinning the astropy commit and the conda version doesn't fix, maybe open an issue here: https://github.com/appveyor/ci/issues

I can try to reproduce locally later...sounds like it is basically running python setup.py install (or test) that triggers the fail?

**Comment by bsipocz** [comment]
Yes, it fails during the install:

```
if ($env:ASTROPY_VERSION -match "dev") {
   Invoke-Expression "${env:CMD_IN_ENV} pip install git+https://github.com/astropy/astropy.git#egg=astropy --upgrade --no-deps"
}
```

where

```
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
```

**Comment by bsipocz** [comment]
Also, now I see that the astropy builds are started to fail, too 2 days ago.

**Comment by mwcraig** [comment]
I've been able to reproduce this locally now. The issue is with Visual Studio 2015 Update 3, installed on appveyor on June 27. Before I upgraded my local machine the compilation was fine. Afterwards, I get the same error we see on appveyor...any idea where to report microsoft compiler bugs :)

**Comment by mwcraig** [comment]
And, a quick look at the MS bug reporting site indicates we are not alone in hitting the specific error message (C1001) after applying Update 3. No clue what the underlying issue is.

**Comment by mwcraig** [comment]
For reference: appveyor/ci#890

In the meantime, @bsipocz, I think this needs to be worked around. It should be specific to python 3.5 because earlier versions of python use a different compiler, so maybe just allow that fail?

**Comment by astrofrog** [comment]
Could we pin the version of visual studio via ci-helpers?

**Comment by mwcraig** [comment]
Don't think so, but check appveyor/ci#890 (I think) in case appveyor has a
workaround.

Changing it locally means reverting to an earlier restore point before the
upgrade.

On Wed, Jun 29, 2016 at 5:45 PM, Thomas Robitaille <notifications@github.com

**Comment by bsipocz** [comment]
Thanks @mwcraig for the investigation. I've opened a PR with your suggestion of how to use the previous VS version.

**Comment by bsipocz** [comment]
Closing as this is dealt with/worked around in ci-helpers. If reoccurs should be reported upstream.
