### ISSUE TITLE
Unable to compute RA and Dec coordinates with HST _flc.fits image using astropy.wcs

### ISSUE THREAD

**Issue by saundraalbers** [astropy/astropy#5144]
When I attempt to create a wcs object to convert pixel coordinates into RA and Dec, such as,

`hdulist = fits.open('IMAGE_flc.fits')`
`w = wcs.WCS(hdulist[1].header, fobj = hdulist)`
`world = w.wcs_pix2world(X data, Y data, 1)`

I get the error below. I'm curious if anyone has any experience finding RA and Dec coordinates with flc images.

`Traceback (most recent call last):
  File "/Users/saundra/code/research/savio/wcs_test.py", line 25, in <module>
    w = wcs.WCS(hdulist[1].header, fobj=hdulist) `
 ` File "/Users/saundra/anaconda2/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 419, in __init__
    det2im = self._read_det2im_kw(header, fobj, err=minerr)`
 ` File "/Users/saundra/anaconda2/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 693, in _read_det2im_kw
    if i == header[dp + '.AXIS.{0:d}'.format(i)]:`
  `File "/Users/saundra/anaconda2/lib/python2.7/site-packages/astropy/io/fits/header.py", line 151, in __getitem__
    card = self._cards[self._cardindex(key)]`
  `File "/Users/saundra/anaconda2/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1717, in _cardindex
    raise KeyError("Keyword %r not found." % keyword)`
`KeyError: "Keyword u'D2IM1.AXIS.1' not found."`

**Comment by astrofrog** [comment]
@saundraalbers - could you provide a copy of the file you are trying to convert coordinates for?

**Comment by saundraalbers** [comment]
Thank you for the response. I requested the files from the archive just a few weeks ago so I'm not sure if that's the problem. One of the images can be found in the link below.

https://drive.google.com/folderview?id=0BzDcTYnInpVvRTQyRFZKWktDSkE&usp=sharing

Thanks again!

**Comment by pllim** [comment]
@saundraalbers , I downloaded a fresh copy of `jc2z01faq_flc.fits` from the Archive directly this morning and I cannot reproduce your error:

```python
>>> from astropy.io import fits
>>> from astropy import wcs
>>> hdulist = fits.open('jc2z01faq_flc.fits')
>>>  w = wcs.WCS(hdulist[1].header, fobj=hdulist)
>>> w
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN-SIP'  'DEC--TAN-SIP'  
CRVAL : 260.17485357173621  57.902643009268523  
CRPIX : 2048.0  1024.0  
CD1_1 CD1_2  : -7.4318514136891e-06  1.12454883545311e-05  
CD2_1 CD2_2  : 1.16827032834335e-05  8.2969720116191308e-06  
NAXIS    : 4096 2048
>>> world = w.wcs_pix2world([100, 200], [100, 100], 1)
>>> world
[array([ 260.18253756,  260.1811403 ]), array([ 57.87221847,  57.87338682])]
```

**Comment by pllim** [comment]
Looking at my fresh copy and your file, there are a lot of differences (see attached `fitsdiff` result), so there must be some intermediate processing that you are not telling us.

[image_diff.txt](https://github.com/astropy/astropy/files/350191/image_diff.txt)

**Comment by saundraalbers** [comment]
Okay, yeah. I used that image as a reference file to run photometry so the added keywords must have thrown it off. Thank you very much for your help.
