### ISSUE TITLE
Deprecate build_sphinx in favor of build_docs?

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#5157]
We currently have two commands to build the documentation that do the same thing (or, will once #5156 is merged):

    python setup.py build_docs
    python setup.py build_sphinx

Right now `AstropyBuildDocs` subclasses `AstropyBuildSphinx` and is really just an alias.  As discussed in #5156, we could switch this so that `AstropyBuildDocs` is the primary command and add a deprecation warning to `AstropyBuildSphinx`.

This issue is paired with astropy/astropy-helpers#245 - a changelog entry needs to be added in here for the deprecation, but the actual code needs to be changed in astropy-helpers.

Travis config files should also be changed to use build_docs.

**Comment by pllim** [comment]
:+1:

**Comment by bsipocz** [comment]
If this needs changes in the helpers, would you mind opening an issue there, too?

**Comment by adrn** [comment]
@bsipocz See astropy/astropy-helpers#245
