### ISSUE TITLE
rename_columns function

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astropy#5159]
I would like to suggest that tt would be useful if there was a function to rename a list of columns. Some other table function have plurals:

e.g.

remove_column(name)     Remove a column from the table.
remove_columns(names)   Remove several columns from the table.

remove_row(index)   Remove a row from the table.
remove_rows(row_specifier)  Remove rows from the table.

rename_column exists and it would be useful to have a rename_columns function too.

An example operation would be something like:

table.rename_columns(colnames, colnames + "_SUFFIX")

or:

new_colnames = [colname + "_new" for colname in colnames]
table.rename_columns(colnames, new_colnames)

Another example is where all the columns are renamed to upper case modulo case insensitive collisions

**Comment by pllim** [comment]
I recently looked for something like `rename_columns` too but just ended up using `rename_column` in a loop. Personally, unless `rename_columns` has great performance improvement or something over `rename_column` in a loop, it is just more of a convenience thing...

**Comment by richardgmcmahon** [comment]
From a user perspective; this convenience has high value; also rename_column() could be considered  special case of rename_columns() :)

I have come across from IDl and I am used to the using: RENAME_TAGS() which is the
equivalent command  for an IDL table/structure.

see: https://github.com/esheldon/sdssidl/tree/master/pro/struct

**Comment by mhvk** [comment]
I don't know that the convenience over writing a loop is quite worth it, but this is not difficult to implement and a PR is certainly welcome. That said, even more welcome would be a bit of refactoring of the existing `replace_column` to ensure it also works on `Quantity`, `Time`, `SkyCoord`, etc., columns. I think with the introduction of the `info` attribute, this should not be too difficult either.

**Comment by taldcroft** [comment]
@mhvk - just to be clear I think you mean `rename_column`.  I got confused for a it.

**Comment by patniharshit** [comment]
I could give it a go if this is still required.

**Comment by mtl-akash-patel** [comment]
Here's my attempt at tackling the issue: https://github.com/astropy/astropy/pull/5795
