### ISSUE TITLE
Sorting a table with unique values (bug?)

### ISSUE THREAD

**Issue by mirca** [astropy/astropy#5167]
```
>>> arr = np.ones(15).reshape(5, 3)
>>> t = Table(arr, names=('a', 'b', 'c'))
>>> t
<Table length=5>
   a       b       c   
float64 float64 float64
------- ------- -------
    1.0     1.0     1.0
    1.0     1.0     1.0
    1.0     1.0     1.0
    1.0     1.0     1.0
    1.0     1.0     1.0
>>> x = t.sort('c')
>>> x is None
True
```

Should this be considered a bug? A thought the natural behavior could be
```
>>> x is t
True
```

This is for sure a silly example, but I think of the case when one wants to sort a table without actually knowing anything about its entries.

cc @taldcroft @mhvk

**Comment by MSeifert04** [comment]
I don't think this is a Bug. Sorting happens in-place without returning something (python just returns `None`). This is "normal" sorting behaviour in python-methods see also `list.sort`, `numpy.ndarray.sort`. There are however functions that return copies: `sorted` and `numpy.sort` which `astropy.table` is lacking.

Or did I misunderstand your post?

**Comment by mirca** [comment]
I think you're right @MSeifert04. Thanks for the clarification!

**Comment by pllim** [comment]
Hmm. Is there an equivalent of `sorted()` then that returns a copy? Just curious.
