### ISSUE TITLE
How to handle license transfer?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5168]
This discussion started with #5132 in regards to PyFITS license. But I think we should apply the same rules to all affected licenses to be consistent.
1. When Astropy "absorbs" a package, does the package keep the original license or use Astropy license? They both might be BSD but the copyright owners are different.
2. If the latter, how do we acknowledge that the package came from somewhere else with a different license?

c/c @perrygreenfield @eteq @astrofrog @taldcroft @kelle

**Comment by astrofrog** [comment]
My personal opinion is that any code that is merged in, with the exception of code in extern or cextern, should be under the Astropy BSD license. But per the terms of the license of the code we merge in, we should definitely include a note about where that code came from and the original license. So for example astropy.io.fits should be astropy-BSD licensed, but we should retain a statement that say that this was adapted from PyFITS, and give the PyFITS license.

**Comment by pllim** [comment]
> but we should retain a statement

Just to clarify... Insert that statement in *all* the `*.py` files inside `astropy/io/fits` ? What about if the code is modified under Astropy PR or a new module is added -- The statement is not needed in that case?
