### ISSUE TITLE
3D Gaussian Kernel

### ISSUE THREAD

**Issue by rasmi** [astropy/astropy#5169]
Hi all,

I'm using astropy.convolve and I'd like to generalize the [Gaussian2DKernel](https://github.com/astropy/astropy/blob/b13e1fae3c8fe91483b109c76ba358231766df85/astropy/convolution/kernels.py#L91) to 3 dimensions. There doesn't seem to be a generic Kernel3D class. Can anyone describe how this might be done? I'd be glad to submit a PR if the process is straightforward enough.

Thanks!

**Comment by rasmi** [comment]
@bsipocz @larrybradley @keflavich @pllim  Any thoughts? I tried creating a 3D gaussian kernel, then convolving it with my field (with astropy and scipy methods), but my result seems off -- I get these bizarre wave patterns. I also tried using [scipy.ndimage.filters.gaussian_filter](https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.ndimage.filters.gaussian_filter.html) and ended up with similar results, so I'm not sure if I'm actually doing this correctly or just wrong in multiple ways.

![](https://github.com/rasmi/deviant-cosmology/raw/master/plots/convolution/density_slice_smoothed_RD0000.png)

**Comment by keflavich** [comment]
Could you show what you've done to get this?  I'd think a 3D gaussian kernel would be a very straightforward extension of the 2D.  Also, are you using astropy.convolution or something else for the convolution step?

**Comment by larrybradley** [comment]
@rasmi As @keflavich points outs, it should be easy to extend a 2D Gaussian to a 3D Gaussian.  Also note that convolving with an `n`-dimensional Gaussian can be separated into `n` 1D Gaussian convolutions (one along each axis).  In fact, that's what `scipy.ndimage.filters.gaussian_filter` does.

**Comment by rasmi** [comment]
Thanks for chiming in @keflavich and @larrybradley. You're right -- this seems like it shouldn't be as complicated as I'm making it out to be. My script is [here](https://github.com/rasmi/deviant-cosmology/blob/master/scripts/convolve.py). I also took a [different approach](https://github.com/rasmi/deviant-cosmology/blob/4f6b4886c01c92cfe3987d4a66e25ba84ecebf86/scripts/convolve.py) where I created my own Gaussian kernel and convolved it with fftconvolve, and the results had a similar wave pattern. I also took a 2D slice and used astropy's Convolve2D with the built-in 2D Gaussian Kernel, and that gave similarly periodic patterns. Could it be that this is correct, and I'm just visualizing it incorrectly? Here's my original field and some more sample convolution outputs. They just don't look like a smoothed version of the field. I'm expecting more of a blur of the original, not this odd wave pattern.
![density_slice_rd0000](https://cloud.githubusercontent.com/assets/2267370/17488850/44ebd320-5d69-11e6-8f13-41b54636b43b.png)
![density_smoothed_slice_rd0000](https://cloud.githubusercontent.com/assets/2267370/17488868/52c7f05a-5d69-11e6-8475-a7e524a74a4d.png)
![density_slice_smoothed_rd0000](https://cloud.githubusercontent.com/assets/2267370/17488878/5e8507e8-5d69-11e6-8fcd-797b52f972b4.png)

Regardless, if you describe the process of making a 3D Kernel (and you think it would be a meaningful addition to astropy), I would be glad to write the code and submit a PR.

**Comment by mhvk** [comment]
@rasmi - the result looks decidedly odd. In testing, I find it often best to just start with a case where I know the answer. In your case, you might start with creating an 3-d input array that is all zeros except for one point somewhere in the middle. For that case, you should obviously get your Gaussian out.

Note that the difficulty will depend a little on what exactly you want to do. As @larrybradley mentions, for straight gaussian convolution, you can split it in 3 1-D convolutions. But if your gaussian can be elliptical with axes not aligned with the grid, then it is trickier.

**Comment by keflavich** [comment]
The kernel you've written looks reasonable to me.  The results you're getting do not.

Is it possible these are coming from an incorrect `reshape`?  It looks like your data have gotten misaligned or shifted prior to convolution.

**Comment by rasmi** [comment]
Okay, I feel foolish. Thanks @keflavich, it turns out my reshaping was incorrect. I used yt's covering_grid option to return the data in original 3D form, and scipy.ndimage.filters.gaussian_filter ended up working fine. I suppose this whole extending a kernel to 3D is unnecessary then, since scipy's n-dimensional convolution works fine. Thanks everyone for your help!
