### ISSUE TITLE
Kernel normalization criterion too harsh for 32 bit FITS files

### ISSUE THREAD

**Issue by samverstocken** [astropy/astropy#5176]
Hi,

In an attempt to resolve an Astropy warning that I'm getting constantly when doing convolutions, 
"Kernel is not normalized, therefore ignore_edge_zeros and interpolate_nan will be ignored", I found out that this normalization criterion (sum - 1.0) is set to a value too small for 32 bit kernel arrays. In line 443 of astropy/convolution/convolve.py, the following is used:

 if np.abs(kernel.sum() - 1) < 1e-8

Whereas the smallest difference between 1.0 and the next floating point number in 32-bit representation is actually 1.1920928955078125e-07. Well, I assume it is, because I always got this same number as the difference between the sum of the kernel and unity, and searching this number in Google (https://www.google.be/search?q=1.1920928955078125e-07&oq=1.1920928955078125e-07&aqs=chrome..69i57.210j0j7&sourceid=chrome&ie=UTF-8) provides many hits, mostly codes that define this number as some kind of 'epsilon' for floats.

Due to all kinds of possible differences in the numerical libraries, python package versions, etc. on two different systems that I was using the same kernel FITS file on, I always got the warning on one system and never got the warning on the other system (for the exact same 32-bit FITS file!).

I thought this was worth mentioning, so maybe the lower limit of 1e-8 could be increased or the criterion could be adjusted for the specific representation of the array data.

**Comment by pllim** [comment]
I think perhaps we can move that `1e-8` to an optional keyword (`epsilon`?) in the function API. In my work porting over old IRAF stuff, which hardcoded limits like that, that is an approach I used.

**Comment by samverstocken** [comment]
Thanks for your reply! Your suggestion would certainly be helpful.

**Comment by pllim** [comment]
@samverstocken , would you be interested to submit a PR?

**Comment by samverstocken** [comment]
I've created a pull request, not sure if/how I can add it to this thread somehow..

**Comment by samverstocken** [comment]
#5177

**Comment by pllim** [comment]
Thanks!

**Comment by keflavich** [comment]
Closed by #5177.
