### ISSUE TITLE
Make keyword argument names follow documented conventions

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#5188]
I noticed that the new [LombScargle](http://docs.astropy.org/en/latest/api/astropy.stats.LombScargle.html#astropy.stats.LombScargle) class accepts a kwarg `nterms` (number of terms), but [this function](http://docs.astropy.org/en/latest/api/astropy.stats.akaike_info_criterion_lsq.html#astropy.stats.akaike_info_criterion_lsq) wants `n_params` and `n_samples`. 

Similarly, [match_coordinates_sky](http://docs.astropy.org/en/latest/api/astropy.coordinates.match_coordinates_sky.html#astropy.coordinates.match_coordinates_sky) takes `matchcoord` and `catalogcoord`, but [get_constellation](http://docs.astropy.org/en/latest/api/astropy.coordinates.get_constellation.html#astropy.coordinates.get_constellation) takes `short_name`. 

I'd find it useful if we picked some conventions to follow for naming function arguments across the whole astropy package and document this by adding a section to the [Coding Guidelines](http://docs.astropy.org/en/latest/development/codeguide.html#coding-style-conventions). But,  I recognize that it might be annoying to deprecate a bunch of keyword arguments across the package. What do you think?

**Comment by pllim** [comment]
Theoretically elegant but realistically hard to enforce. Getting existing API to adhere generates a bunch of work with no real gain (except warnings and API changes). Getting future API to adhere requires package maintainers to be aware of such a rule and enforce it, which might not be possible given the number/time we have. Just a thought.

**Comment by mhvk** [comment]
For `Time` and `Table`, we did deprecate names that later were felt to be non-standard (e.g., `Table` had plurals in quite a few of the keyword names), but it definitely is quite a bit of work. I think it would be good to have more uniformity in the subpackages at least, and it may not be bad to add something to the coding guidelines (but would those be read...).

**Comment by bsipocz** [comment]
hmm, this is borderline, but if we want it, it may still make it for 4.0. 

However, as nothing has happened about it in the past 3 years (including a full LTS cycle), we might just want to close it as a won't fix?

What do you think?

**Comment by pllim** [comment]
Doing this for the whole core package is a stretch. I propose we close this like @bsipocz suggested above and open issues for affected APIs on a case-by-case basis.
