### ISSUE TITLE
travis failures as scipy circmean no longer equal to astropy's

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5198]
Recent travis builds are failing on `test_circstats.test_circmean_against_scipy`. This may be because `scipy` has changed how its version works (I haven't investigated, but there was a recent scipy release).

@mirca - could you check what is happening? Ideally, I think the test should be rewritten so that it works for all versions. I would also suggest not to use random input data.

**Comment by mirca** [comment]
@mhvk Sure! I'm gonna look into it this afternoon

**Comment by bsipocz** [comment]
This is an upstream scipy bug, and they are working on it. https://github.com/scipy/scipy/issues/6420

I would simply suggest to limit the scipy version to <0.18 for now, it's easy for CI, but maybe also for the code, threat 0.18 scipy the same as a missing scipy.

**Comment by mhvk** [comment]
My suggestion would be to rewrite the test so that it uses input that is known to work for all versions of scipy.

**Comment by bsipocz** [comment]
@mhvk - But then it would still be buggy from the user side. Maybe emit a warning if they're using scipy 0.18?

**Comment by mhvk** [comment]
@bsipocz - why would it be buggy? astropy's version of the statistics made by @mirca does not have these problems.

**Comment by bsipocz** [comment]
Oh, ignore me then.  I blindly assumed that scipy is used, but now I see that we are only testing against it, sorry about it. @mirca for the win.
