### ISSUE TITLE
Incorrect order of corners in calc_footprint?

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#5200]
@OlgaVorokh and I noticed a possible bug in the order of the corners in calc_footprint:
http://docs.astropy.org/en/latest/_modules/astropy/wcs/wcs.html#WCS.calc_footprint

The docstring says:
> The order is counter-clockwise starting with the bottom left corner.
which implies this order:
"bottom left", "bottom right", "top right", "top left"

The code contains this:
```
corners = np.array([[1, 1],
                                [1, naxis2],
                                [naxis1, naxis2],
                                [naxis1, 1]], dtype = np.float64)
```
which we think corresponds to:
"bottom left", "top left", "top right", "bottom right"
because naxis1 is connected to left and right, and naxis2 is connected to top and bottom.

At least that's how it appears when opening the image in ds9.

PS: We're adding a similar method to the `gammapy.image.SkyImage` class, that's when we noticed this issue.  https://github.com/gammapy/gammapy/pull/642

cc @nden

**Comment by nden** [comment]
@cdeil Docstring corrected now. Thanks.

**Comment by cdeil** [comment]
@nden - Thank you!
