### ISSUE TITLE
Table.__init__ with Mapping

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#5212]
Would it be possible to lower the restrictions of `Table.__init__` (https://github.com/astropy/astropy/blob/master/astropy/table/table.py#L320) to `collections.Mapping` instead of `dict`?

That would allow customized mappings to be used, especially if one subclasses `Mapping` or `UserDict` instead of `dict`. Both of them do not evaluate to `True` currently:

```
>>> isinstance(collections.UserDict(), dict)
False
```

while they are considered as instance of `collections.Mapping`:

```
>>> isinstance(collections.UserDict(), collections.Mapping)
True
```

**Comment by taldcroft** [comment]
I don't see any problem with this offhand.

**Comment by MSeifert04** [comment]
ok, I'll just try to make a PR and try to change it.

Thank you for the very fast answer!
