### ISSUE TITLE
remote_data does not apply in the example gallery

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#5217]
This came up in discussion of #5210, although it's not really directly related.  The basic question is: should we have  the remote data machinery apply to the sphinx examples, and if so, how?  Right now it effectively applies to the whole documentation because the doctests run, and they will catch any situation where the internet is accessed without the `remote_data` flag being used.  But the sphinx example gallery bypasses this because it isn't recognized as part of the doctests.  

My preference I think is to leave it as-is.  The argument for that restricting remote_data would render some of the examples non-functional.  For example, the coordinates example uses `SkyCoord.from_name` as a critical element.  So with `remote_data` off the whole example would have to be skipped.  And the sphinx build is _not_ generally assumed to be non-internet - the intersphinx machinery requires the internet, and we let that run on e.g. travis without complaint.

cc @astrofrog @adrn @bsipocz

**Comment by bsipocz** [comment]
I agree with you to leave this as is. If there is a remote issue somewhere the docs build will be incomplete anyway, so we either invent a workaround or wait for it to be resolved.

**Comment by eteq** [comment]
If there are no other opinions in another couple weeks I'll just close this as not needed, then.

**Comment by astrofrog** [comment]
@eteq - I agree with you, I don't think we should worry about this. Since it's been a couple of months, I'll just close this.
