### ISSUE TITLE
URL in Sagittarius Coordinate Example

### ISSUE THREAD

**Issue by kadrlica** [astropy/astropy#5220]
The example for defining a new coordinate frame using the Sgr Stream has a broken link to David Law's web resource. David has moved to STScI, but it looks like the resource didn't move with him?

The astropy example is located here:
https://github.com/astropy/astropy/blob/dc6a382e7dcf394bb4c017f3552c6f6a2f8a5aa2/examples/coordinates/plot_sgr-coordinate-frame.py#L31

The broken URL is here:
http://www.astro.virginia.edu/~srm4n/Sgr/

**Comment by adrn** [comment]
Ah, yep. I just sent him email.
