### ISSUE TITLE
SkyCoord slow to import

### ISSUE THREAD

**Issue by sdjohnson-astro** [astropy/astropy#5222]
I recently wrote a few command line tools for converting coordinates but found that they are noticeably slow to run. The runtime is dominated by importing SkyCoord from astropy.coordinates which takes nearly 2 seconds (for reference, this is a new installation of astroconda running on my MacBook Pro retina w/ 2.7 GHz i7 processor, 16 GB of ram, and an SSD). For comparison, imports from standard libraries such as numpy or UnivariateSpline from scipy.interpolate takes ~0.15 seconds. Is there any way to speed up the import of SkyCoord?

**Comment by MSeifert04** [comment]
@sdjohnson-astro Which version of astropy do you use? The import time was sped up for astropy 1.2 but it's still not as fast as numpy/scipy. 

See also #4598.

**Comment by sdjohnson-astro** [comment]
I am using Astropy version 1.2.1

Thanks for the super fast reply!

**Comment by pllim** [comment]
Like @MSeifert04 said, there is already a related issue like this. What if you simply do `import astropy`? Is it the same kind of slowness?

**Comment by sdjohnson-astro** [comment]
`import astropy` takes 0.5 seconds. Significantly faster than the 2 seconds it takes to import SkyCoord from astropy.

**Comment by pllim** [comment]
If you are feeling adventurous, you can profile the offending import statement and post some results here. See https://docs.python.org/3/library/profile.html

**Comment by pllim** [comment]
And to make sure that this is not already solved since the release, you can also try the `dev` version from `master`.

**Comment by astrofrog** [comment]
@sdjohnson-astro - can you test ``import astropy.units``?

**Comment by MSeifert04** [comment]
Just for convenience these import times can be tested from the command line with 
`python -m timeit -n 1 -r 1 "from astropy.coordinates import SkyCoord"` (which takes 5-6s on my machine)

**Comment by pllim** [comment]
Interesting. Using the latest `dev` myself. The first time I run @MSeifert04 's command, it took 4.83 sec. But subsequent calls was about 1.87 sec each.

**Comment by pllim** [comment]
@astrofrog , `python -m timeit -n 1 -r 1 "import astropy.units"` gave me about 925 msec. But that is after I already ran the `SkyCoord` import test several times.

**Comment by sdjohnson-astro** [comment]
Thanks for the tip.

@astrofrog importing astropy.units takes 0.8 seconds on my laptop.

I don't know enough about astropy to make much of the profiling results at first glance. The profile results are attached if anyone wants to take a look.
[SkyCoord_profile.txt](https://github.com/astropy/astropy/files/406936/SkyCoord_profile.txt)

I will try out the latest `dev` myself, but from @pllim it looks like the import time is still non-negligible.

**Comment by MSeifert04** [comment]
@pllim The first time python encounteres new `.py` files it generates `__pycache__` and `.pyc` files. This will account for the longish "first" import.

**Comment by pllim** [comment]
@sdjohnson-astro , thanks for the log. But it is hard to diagnose without full path to the filenames, and would be nice to sort them by `cumtime`.

**Comment by sdjohnson-astro** [comment]
@pllim A version sorted by cumulative time is attached. I am not sure how to get the full path to filenames with cProfile. Is there an option in the documentation that I am missing?

Thanks!

[import_SkyCoord_profile.txt](https://github.com/astropy/astropy/files/407096/import_SkyCoord_profile.txt)

**Comment by pllim** [comment]
Thanks, @sdjohnson-astro . I think the listed filenames are unique enough that we don't need the full path. From your log:

```
        1    0.001    0.001    1.505    1.505 baseframe.py:6(<module>)
        1    0.000    0.000    1.500    1.500 earth.py:2(<module>)
        1    0.003    0.003    1.499    1.499 __init__.py:25(<module>)
        1    0.000    0.000    1.448    1.448 fk5.py:3(<module>)
        1    0.000    0.000    1.418    1.418 utils.py:6(<module>)
        1    0.001    0.001    1.417    1.417 iers.py:10(<module>)
```

Maybe @eteq or @taldcroft wish to chime in?

**Comment by sdjohnson-astro** [comment]
@pllim Importing `SkyCoord` also takes 2 seconds on my computer when using the latest 'dev'.

**Comment by pllim** [comment]
@sdjohnson-astro , thanks for checking! I see `iers.py` listed. I wonder if it is something to do with some kind of initialization there...

**Comment by eerovaher** [comment]
I ran the following with the current `astropy` development version (0e379d8dfbfa601739721b797a4d69b6ba63d6ac):
```shell
python -X importtime -c "from astropy.coordinates import SkyCoord"
python -X importtime -c "import numpy"
```
The difference in the reported times was roughly a factor of 3, much less than the more than an order of magnitude difference reported in this issue. I haven't bothered looking up any commits that might have contributed towards faster importing, but it does seem like this issue is no longer relevant.

**Comment by sdjohnson-astro** [comment]
This is a blast from the past! Yes, my understanding is that a decent amount of effort went into speeding things up under the hood some time ago.




-----------------------------------
Sean D. Johnson (he/him)
Assistant Professor & LSA Collegiate Fellow
Department of Astronomy
University of Michigan
***@***.***
