### ISSUE TITLE
Numpy dev error: reloading numpy is not supported

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5228]
https://github.com/numpy/numpy/pull/7853 ensured that a `RuntimeError` is raised when it is attempted to reload numpy. This causes the travis builds with numpy-dev to fail. See, e.g., https://travis-ci.org/astropy/astropy/jobs/150913830. Not immediately clear where we are attempting to reload numpy (but we shouldn't!).

**Comment by MSeifert04** [comment]
this is probably more a astropy-helpers issue (https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/utils.py#L74)

**Comment by mhvk** [comment]
Fixed by https://github.com/numpy/numpy/pull/7941
