### ISSUE TITLE
indexing of astropy coordinate object is 25 times slower than indexing the cartesian representation

### ISSUE THREAD

**Issue by dsavransky** [astropy/astropy#5233]
Basic issue:  I have skycoord objects containing arrays of coordinates and need to extract the Cartesian coordinates for a subset of these objects.  It turns out that indexing the skycoord object and then converting to Cartesian coordinates takes at least 25 times longer than converting the entire array of coordinates to Cartesian representation and then indexing.

Sample code to reproduce:

```
from astropy.coordinates import SkyCoord
from astropy import units as u
import numpy as np

c = SkyCoord(ra=np.random.uniform(size=100)*u.rad, dec=np.random.uniform(size=100)*u.rad,distance=np.random.uniform(size=100)*u.pc)

ind = 50

%timeit res = c[ind].cartesian.xyz
%timeit res = c.cartesian[ind].xyz
%timeit res = c.cartesian.xyz[:,ind]
```

On Mac OS 10.10.5, python 2.7.12, ipython 5.0.0, astropy v1.2, results are:

100 loops, best of 3: 14.9 ms per loop
1000 loops, best of 3: 636 µs per loop
1000 loops, best of 3: 566 µs per loop

**Comment by pllim** [comment]
@dsavransky , you could also profile the code for each of those commands and post the results here. They would help diagnose the bottleneck. Thanks.

**Comment by dsavransky** [comment]
The fundamental bottleneck is the indexing of the original object:

%timeit c[ind]
100 loops, best of 3: 14 ms per loop

**Comment by pllim** [comment]
I mean, more specifically, profiling would identify exactly where the bottleneck is in the codes.

**Comment by dsavransky** [comment]
Sorry.  Being slow today.  Here's:
cProfile.run('c[ind]',filename='skycoords_index.cprof') 

[skycoords_index.cprof.zip](https://github.com/astropy/astropy/files/413340/skycoords_index.cprof.zip)

**Comment by pllim** [comment]
Thanks. I was thinking more like below but I could extract that from your file.

```python
>>> import pstats
>>> p = pstats.Stats('skycoords_index.cprof')
>>> pp = p.strip_dirs()
>>> pp.sort_stats('cumulative').print_stats(15)
...
         25444 function calls (24032 primitive calls) in 0.025 seconds

   Ordered by: cumulative time
   List reduced from 168 to 15 due to restriction <15>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.025    0.025 <string>:1(<module>)
        1    0.000    0.000    0.025    0.025 sky_coordinate.py:238(__getitem__)
        1    0.000    0.000    0.021    0.021 sky_coordinate.py:189(__init__)
       24    0.001    0.000    0.020    0.001 sky_coordinate.py:37(FRAME_ATTR_NAMES_SET)
        1    0.000    0.000    0.019    0.019 sky_coordinate.py:257(_parse_inputs)
      404    0.001    0.000    0.018    0.000 baseframe.py:628(get_frame_attr_names)
      414    0.002    0.000    0.017    0.000 collections.py:50(__init__)
        1    0.000    0.000    0.017    0.017 sky_coordinate.py:1409(_parse_coordinate_arg)
 1907/577    0.001    0.000    0.016    0.000 {getattr}
       19    0.000    0.000    0.016    0.001 sky_coordinate.py:411(__getattr__)
      414    0.001    0.000    0.015    0.000 _abcoll.py:548(update)
     1100    0.001    0.000    0.011    0.000 baseframe.py:630(<genexpr>)
      696    0.001    0.000    0.010    0.000 baseframe.py:201(__get__)
      168    0.001    0.000    0.008    0.000 baseframe.py:302(convert_input)
       24    0.000    0.000    0.003    0.000 quantity.py:779(__eq__)
```

**Comment by pllim** [comment]
I think the info above should be able to get `coordinates` maintainers started on a solution, if possible.

**Comment by bsipocz** [comment]
Without looking into the details this reminds me of this issue: https://github.com/astropy/astropy/issues/3323

**Comment by adrn** [comment]
Which I believe is also related to #5022!

**Comment by mhvk** [comment]
It may be that the larger problem is that every time a completely new `SkyCoord` is constructed, without properly reusing the fact that here we already know all the ingredients are OK.

Note that as I made slicing/reshaping better for representations (#4123) I found there were quite a few places were data were unnecessarily copied, thus giving easy options to optimize performance. It is likely the same will hold here, but it requires going through things carefully (probably starting with `baseframe` rather than `SkyCoord`).

**Comment by adrn** [comment]
It's still slower to index on coordinates, but the numbers are much better! Now with current master:
```
371 µs ± 103 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
87.1 µs ± 19.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
39 µs ± 1.65 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
