### ISSUE TITLE
New sofa version is out

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5234]
Posting also on astropy as we should keep up to date and I'm not sure who's watching `liberfa` -- it is relevant for the 2016-dec-31 leap second, as well as for changing the deflection of light near the sun -- it may be possible to remove the workarounds (cc @StuartLittlefair, @eteq).

**Comment by StuartLittlefair** [comment]
Great! Yes - once this new version is rolled into astropy we will be able to remove the workarounds put in place.

**Comment by pllim** [comment]
When I read "new sofa", this is what crossed my mind:

![double decker sofa](https://i.ytimg.com/vi/5c7q0UAIIX4/maxresdefault.jpg)

Sorry for the off-topic post.

**Comment by mhvk** [comment]
With the new `erfa` version merged (https://github.com/liberfa/erfa/pull/35), I think it now explicitly needs to be included in astropy. @astrofrog, @eteq - I don't know how to go about that...

**Comment by mhvk** [comment]
@eteq, @astrofrog, I have lost track of where this is, but it seems astropy is not yet shipping with the new erfa, correct? We should have that in place before the next point release, as it includes a leap second...

**Comment by mhvk** [comment]
With #5418 merged, we're up to date with SOFA again, so closing...
