### ISSUE TITLE
ReadTheDocs build timing out

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5244]
The docs builds are timing out (since 2 weeks ago) - the build time suddenly jumped, but I don't think it was anything that changed in the actual docs.

**Comment by mhvk** [comment]
This is well after we moved to python3?!

**Comment by astrofrog** [comment]
No, we only switched the main builds to Python 3 yesterday when merging that PR, this was 2 weeks before that.

**Comment by astrofrog** [comment]
Huh actually it's not failing with a real error:

https://readthedocs.org/projects/astropy/builds/4317365/

**Comment by pllim** [comment]
I think this might be caused by the same problem causing #5230. Did you wipe the RTD build first *several* times before rebuilding?

**Comment by mhvk** [comment]
@astrofrog - do you think #5249 will have fixed the time-outs as well? If so, this can be closed.

**Comment by astrofrog** [comment]
Yes, builds are passing again :)
