### ISSUE TITLE
Include brief descriptions of affiliated packages in registry table

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#5252]
It would be useful if there were short descriptions of each affiliated package in the registry table here: http://www.astropy.org/affiliated/

I wonder if this is something we can insert automatically using the "Summary" from pypi?

**Comment by astrofrog** [comment]
@adrn - can you open an issue here instead? https://github.com/astropy/astropy.github.com - thanks!

**Comment by adrn** [comment]
Done! astropy/astropy.github.com#116
