### ISSUE TITLE
Dynamically create list of available writers/readers to speed up import?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5264]
In #5262, @MSeifert04 found that about 16% of the time needed to import `SkyCoord` is spent in `io.registry`, in creating nicely formatted tables (68 times) for use in `_update__doc__`, i.e., to provide the list of available formats in the docstrings. Now it is great to have this available, but since it is unlikely that it is needed in a typical session, we could save a lot of import time by creating it dynamically. It seems this should not be too hard...

**Comment by taldcroft** [comment]
@mhvk - interesting question.  I confess I don't know how to lazy-generate a function docstring.  For instance `Table.read` has a `__doc__` attribute that is currently created at import time.  So I don't know how to delay creating that until the user accesses `Table.read.__doc__`.  Maybe it's simple and I just am not seeing it.

**Comment by mhvk** [comment]
Make `__doc__` a property?? It seems one can...
```
class A():
    @property
    def __doc__(self):
        if not hasattr(self, '_doc'):
            print('evaluating')
            self._doc = 'haha, no doc'
        return self._doc
     
a = A()
a?
# evaluating
# Type:        A
# String form: <__main__.A object at 0x7f9e764e8390>
# Docstring:   haha, no doc
a?
# Type:        A
# String form: <__main__.A object at 0x7f9e764e8390>
# Docstring:   haha, no doc
```

**Comment by taldcroft** [comment]
What about for a class method?

**Comment by taldcroft** [comment]
BTW, here is a relevant SO question from 6 years ago.  Check out the author.  :smile:

http://stackoverflow.com/questions/2693883/dynamic-function-docstring

**Comment by saimn** [comment]
I came to this some time ago when looking for optimizations in `astropy.table`, but I didn't find a way to generate dynamically the docstring.
But maybe, a simple solution would be to move this formats table to a dedicated method, `Table.help_formats` or something else, and simply have `Table.read`'s docstring mention this method. This would also make it more explicit that the list of formats is dynamic. I think it is not too much hassle for users to have to use this method.

**Comment by mhvk** [comment]
> BTW, here is a relevant SO question from 6 years ago. Check out the author.

:smiley: 

It does seem like it should be a little easier than that, but anyway, maybe for now we just go with the simple optimization in #5262, and leave this open for future thought. There may be lower-hanging fruit in `units`...

**Comment by mhvk** [comment]
Closing, since I think #5275 is a better, less complicated solution.
