### ISSUE TITLE
Output html for table?

### ISSUE THREAD

**Issue by gkanarek** [astropy/astropy#5269]
Is there a way to output the html for a Table without having to open a browser (via show_in_browser)? I'd like to embed a Table in a webpage, and make use of Datatables.select.

I tried hacking my own version of Table.show_in_browser:

    import cStringIO as StringIO
    import numpy as np

    def get_table_html(table, max_lines=5000, jsviewer=False, 
                       jskwargs={'use_local_files': True},
                       tableid=None, table_class="display compact",
                       show_row_index=True):
        output = StringIO()
        for col in table.colnames:
            if np.issubdtype(table[col].dtype, float):
                table[col].format = "%8.3f"
            css = """\
    body {font-family: sans-serif;}
    table.dataTable {width: auto !important; margin: 0 !important;}
    .dataTables_filter, .dataTables_paginate {float: left !important; margin-left:1em}
    th, td {padding: 15px; text-align: left;}
    table, th, td {border: 1px solid black;}
    """
        if jsviewer:
            if show_row_index:
                displ = table._make_index_row_display_table(show_row_index)
            else:
                displ = table
            displ.write(output, format='jsviewer', css=css,
                        max_lines=max_lines, jskwargs=jskwargs,
                        table_id=tableid, table_class=table_class)
        else:
            table.write(output, format='html')

        return output.getvalue()

However, doing this creates a full page's worth of html boilerplate, which makes embedding this in a page very difficult without doing some html processing to remove said boilerplate. If I _don't_ remove it, then I have much less control over the table.

Any suggestions? Can this be a feature in a future version? I can't imagine why it hasn't already been implemented...

**Comment by saimn** [comment]
See #4058 and the last comment in it. The open question is how to handle the Javascript and css assets. Should the generated HTML depend on the css and js files from Astropy ?

**Comment by taldcroft** [comment]
@gkanarek - would this help?
```
In [8]: t = simple_table()

In [9]: t.pformat(html=True)
Out[9]: 
[u'<table id="table4510929744">',
 u'<thead><tr><th>a</th><th>b</th><th>c</th></tr></thead>',
 u'<tr><td>1</td><td>1.0</td><td>c</td></tr>',
 u'<tr><td>2</td><td>2.0</td><td>d</td></tr>',
 u'<tr><td>3</td><td>3.0</td><td>e</td></tr>',
 u'</table>']
```

**Comment by gkanarek** [comment]
@taldcroft it did indeed help, though I ended up going with something else entirely for my particular use case. Thanks!

**Comment by pllim** [comment]
Can we close this then?
