### ISSUE TITLE
How to make a table with missing data from scratch?

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#5283]
In the last few days I've been working a lot with table data with missing values, and it was / is pretty painful. Partly that's probably ignorance on my part what's possible, partly probably things could be better supported from Astropy.

In https://github.com/gammapy/gamma-cat I have table data maintained in YAML files for easy editing / diffing. Basically I have a few bool, int, float and string columns, with missing values and want to make an Astropy Table for that.

Here's a standalone example (not showing the reading of YAML data into Python objects, just using list of dicts of row data directly):

``` python
rows = [
 {'a': True, 'b': 42, 'c': 42.42, 'd': 'spam'}, # all fields present
 {           'b': 42, 'c': 42.42, 'd': 'spam'}, # missing bool `a`
 {'a': True,          'c': 42.42, 'd': 'spam'}, # missing int `b`
 {'a': True, 'b': 42,             'd': 'spam'}, # missing float `c`
 {'a': True, 'b': 42, 'c': 42.42             }, # missing string `d`
]
```

How can I make a Table with that data with the missing values masked?

``` python
>>> from astropy.table import Table
>>> Table(rows=rows)
ValueError: Row 3 has no value for column c
```

For now I have some code that fills the missing data into the dicts before making the table:

```
MISSING_VAL = dict(
    bool=False,
    integer=-999,
    number=np.nan,
    string='',
)
```

I didn't write the code yet to create the mask to make this a masked table, this is ugly.

@taldcroft or anyone - This should be a common use case with a simple way to make the table, no?
What's a good way to do it?

**Comment by taldcroft** [comment]
@cdeil - I agree your example should work.  The current code takes the conservative path of validating the inputs for error in the data, but we need a mechanism to allow for missing data like this.  That could either mean changing the default behavior or adding a keyword.

**Comment by taldcroft** [comment]
BTW, a one-liner workaround if you have pandas installed is:
```
Table.from_pandas(DataFrame(rows))
```

**Comment by saimn** [comment]
:+1: , we also have some ugly code for this, so it would be nice to have it handled directly by `Table`.

**Comment by dyq0811** [comment]
Hi, just an idea related to the missing data/np.nan. It might be useful to have a function that can filter out missing data/np.nan with respect to multiple columns/rows, or a function that can output a subtable without missing data/np.nan in specified columns/rows.

When I tried to plot data from a gigantic Astropy table, I have to do a plenty of procedures to clean the np.nan/missing data entries, as they cannot be plotted by matplotlib. For a small amount of columns/rows, I simply use a boolean mask such as table[np.isnan(table["RV_gaia"])==0]. But when I need to deal with many columns/rows, I have to write several masks or an iteration that goes through each entry (which is really slow).

Excuse me if there have been good ways to do this ;)

**Comment by taldcroft** [comment]
@dyq0811 - good idea, and it is just recently (mostly) done in #8468!

**Comment by dyq0811** [comment]
Hello, I would like to work on this issue and am trying to start from detecting where the values are missing. Any suggestion is most welcomed. One thing I am unsure is that should I assume we have a complete list of keys of the dictionary?

```
import numpy as np
import collections

def missing_row_indices(rows, names):
    # Initiate a dict to store indices of rows with missing column(s)
    masks = collections.defaultdict(list)

    for index in range(len(rows)):
        missing_names = names[[(k not in rows[index]) for k in names]]
        if missing_names.size > 0:
            for name in missing_names:
                masks[name].append(index)
    return masks
```

```
rows = [
 {'a': True, 'b': 42, 'c': 42.42, 'd': 'spam'}, # all fields present
 {           'b': 42, 'c': 42.42, 'd': 'spam'}, # missing bool `a`
 {'a': True,          'c': 42.42, 'd': 'spam'}, # missing int `b`
 {'a': True, 'b': 42,             'd': 'spam'}, # missing float `c`
 {'a': True, 'b': 42, 'c': 42.42             }, # missing string `d`
]

# Assume we have a complete list of the names (?)
names = np.array(['a', 'b','c', 'd'])

# Test
>>> missing_row_indices(rows, names)
>>> defaultdict(list, {'a': [1], 'b': [2], 'c': [3], 'd': [4]})
```

**Comment by taldcroft** [comment]
@dyq0811 - you can assume that `names_from_data` is complete and then work within the existing implementation (`_init_from_list_of_dict`) more closely.  Most of what you need is already being done, so it's almost just one different line for the detection:
```
    masks = collections.defaultdict(list)

    for name in names_from_data:
        cols[name] = []
        for i, row in enumerate(data):
            try:
                cols[name].append(row[name])
            except KeyError:
                # WAS : raise ValueError('Row {0} has no value for column {1}'.format(i, name))
                masks[name].append(i)
```

**Comment by dyq0811** [comment]
@taldcroft Should I fill the missing entries directly to `cols` according to the dtype or make use of `self.MaskedColumn` and `self.masked`?
```
    def _init_from_list_of_dicts(self, data, names, dtype, n_cols, copy):
        names_from_data = set()
        for row in data:
            names_from_data.update(row)

        cols = {}
        masks = collections.defaultdict(list)
        for name in names_from_data:
            cols[name] = []
            for i, row in enumerate(data):
                try:
                    cols[name].append(row[name])
                except KeyError:
                    masks[name].append(i)

        if all(name is None for name in names):
            names = sorted(names_from_data)
        self._init_from_dict(cols, names, dtype, n_cols, copy)
        return
```

**Comment by taldcroft** [comment]
Here are some more hints and untested code that might or might not work.  :smile:

```
def _init_from_list_of_dicts(self, data, names, dtype, n_cols, copy):
    MISSING = object()  # Unique new object
    names_from_data = set()
    for row in data:
        names_from_data.update(row)

    cols = {}
    missing_indexes = collections.defaultdict(list)
    for name in names_from_data:
        cols[name] = []
        for idx, row in enumerate(data):
            try:
                cols[name].append(row[name])
            except KeyError:
                missing_indexes[name].append(idx)
                cols[name].append(MISSING)

    if missing_indexes:
        first_vals = {}
        for name in names_from_data:
            for val in cols[name]:
                if val is not MISSING:
                    first_vals[name] = val
                    break

        # Now you need to set all the missing values from `missing_indexes[name]`
        # to `first_vals[name]`

        # Next you need to call self._set_masked(True).  I'm not sure if this can be
        # done here or after `self._init_from_dict()`.

    if all(name is None for name in names):
        names = sorted(names_from_data)

    self._init_from_dict(cols, names, dtype, n_cols, copy)

    if missing_indexes:
        for name, indexes in missing_indexes.items():
            self[name].mask[indexes] = True

    return
```

**Comment by dyq0811** [comment]
@taldcroft Thank you! I modified the code as the following (add one indentation and several lines of code). Sorry I don't understand why we want to fill the missing entries with first values?
```
def _init_from_list_of_dicts(self, data, names, dtype, n_cols, copy):
    MISSING = object()  # Unique new object
    names_from_data = set()
    for row in data:
        names_from_data.update(row)

    cols = {}
    missing_indexes = collections.defaultdict(list)
    for name in names_from_data:
        cols[name] = []
        for idx, row in enumerate(data):
            try:
                val = row[name]
            except KeyError:
                missing_indexes[name].append(idx)
                val = MISSING
            cols[name].append(val) # Add indentation

    if missing_indexes:
        first_vals = {}
        for name in names_from_data:
            for val in cols[name]:
                if val is not MISSING:
                    first_vals[name] = val
                    break
    # Replace object with first values
    for name in names:
        for index in missing_indexes[name]:
            cols[name][index] = first_vals[name]

    if all(name is None for name in names):
        names = sorted(names_from_data)

    self._init_from_dict(cols, names, dtype, n_cols, copy)
    # I guess it's safer to set the property after initialization?
    self._set_masked(True)

    if missing_indexes:
        for name, indexes in missing_indexes.items():
            self[name].mask[indexes] = True

    return
```

**Comment by taldcroft** [comment]
@dyq0811 - I think it's time for a PR!  You should put in the new code and add tests.

About the `first_vals`, I would suggest trying to use your original plan of `b''` and see what happens.
