### ISSUE TITLE
ECSV support for missing values?

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#5284]
I have tables with missing values (see #5283 for an example) and would like to read / write them to disk.

ECSV (see [astropy.io.ascii.Ecsv](http://docs.astropy.org/en/stable/api/astropy.io.ascii.Ecsv.html) and [APE](https://github.com/astropy/astropy-APEs/blob/master/APE6.rst)) comes to mind
But as far as I can see, it doesn't support missing values.

@taldcroft - Do you think it's possible / worth the effort to add it?

Alternatively, and as a short-term solution -- are there any utility functions or best practice to handle missing values?

I'm thinking convert to list or dicts (see #5283 example) and remove the masked entries, and store that using JSON or YAML using my own helper function. Is that a good idea or is there a better way?

**Comment by taldcroft** [comment]
@cdeil - there is support for missing values, though not automated nor absolutely 100% reliable (because it uses a sentinel for missing values that could in theory occur accidentally for non-missing values).  But this should work for you:
```
In [14]: t = simple_table(masked=True)

In [15]: t.write('out.ecsv', format='ascii.ecsv', fill_values=[(ascii.masked, '__MISSING__')])

In [16]: cat out.ecsv
# %ECSV 0.9
# ---
# datatype:
# - {name: a, datatype: int64}
# - {name: b, datatype: float64}
# - {name: c, datatype: string}
a b c
__MISSING__ 1.0 c
2 2.0 __MISSING__
3 __MISSING__ e

In [17]: t2 = Table.read('out.ecsv', format='ascii.ecsv', fill_values=[('__MISSING__', '0')])

In [18]: t2
Out[18]: 
<Table masked=True length=3>
  a      b     c  
int64 float64 str1
----- ------- ----
   --     1.0    c
    2     2.0   --
    3      --    e
```

**Comment by taldcroft** [comment]
@cdeil -with #5347 merged can we close this?

**Comment by hamogu** [comment]
@taldcroft With your recent work on a new version of ECSV, can we close this?

**Comment by taldcroft** [comment]
Yes!
