### ISSUE TITLE
How do ASCII columns get written with the correct width in FITS binary tables?

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#5288]
FITS binary tables that contain unicode columns get written row-by-row, and unicode columns are converted item-by-item using `numpy.char.encode(item, 'ascii')`.  This returns a byte array, but with a size that differs from the width of the original array.

Here is a highly simplified example:

```python
>>> foo = ['ELG']*5 + ['BLAT']*5
>>> bar = np.array(foo)
>>> bar
array(['ELG', 'ELG', 'ELG', 'ELG', 'ELG', 'BLAT', 'BLAT', 'BLAT', 'BLAT',
       'BLAT'], 
      dtype='<U4')
>>> np.char.encode(bar[0], 'ascii')
array(b'ELG', 
      dtype='|S3')
>>> with open('foo.dat', 'wb') as f:
...     np.char.encode(bar[0], 'ascii').tofile(f)
... 
```
This writes 3 bytes, not 4, which is the correct width of the column.

**Comment by MSeifert04** [comment]
strictly speaking this one would be a numpy-bug (if this behaviour is not intended).

I guess this is related to https://github.com/astropy/astropy/issues/5280#issuecomment-243926940?

**Comment by weaverba137** [comment]
I think I answered my own question, see PR #5291.  This can be closed if there are no other questions.

**Comment by pllim** [comment]
Note: Active PR is #5296
