### ISSUE TITLE
textnormal not rendered properly in HTML

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5292]
For example: http://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.Box1D.html#astropy.modeling.functional_models.Box1D

![screenshot](https://cloud.githubusercontent.com/assets/2090236/18171766/18d2dab0-7031-11e6-9b54-c8fae307de74.png)

**Comment by MSeifert04** [comment]
I think the math formulas are based on MathJax and that doesn't have `textnormal`. Could you check if `text` works? It should be identical?!

I haven't read through it but there was some discussion about it in https://groups.google.com/forum/#!msg/mathjax-users/JC7L3lX54s4/poMq9iniAQAJ
