### ISSUE TITLE
Box1D formula doc is wrong?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5293]
In [Box1D](http://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.Box1D.html#astropy.modeling.functional_models.Box1D), I see this:

![screenshot](https://cloud.githubusercontent.com/assets/2090236/18172194/85a985f2-7032-11e6-8763-ff5c0bcf05be.png)

Shouldn't it actually be `x0 - w/2 <= x <= x0 + w/2`? Am I going crazy here? I don't think my math is *that* rusty...

**Comment by MSeifert04** [comment]
This could also affect [Box2D](http://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.Box2D.html#astropy.modeling.functional_models.Box2D)

**Comment by MSeifert04** [comment]
The source code agrees with you:

```
# 1D
        return np.select([np.logical_and(x >= x_0 - width / 2.,
                                         x <= x_0 + width / 2.)],
                         [amplitude], 0)

# 2D
        x_range = np.logical_and(x >= x_0 - x_width / 2.,
                                 x <= x_0 + x_width / 2.)
        y_range = np.logical_and(y >= y_0 - y_width / 2.,
                                 y <= y_0 + y_width / 2.)
```

**Comment by pllim** [comment]
Thanks for confirming, @MSeifert04 ! :tada:
