### ISSUE TITLE
fits.PrimaryHDU ignores BITPIX when called with a header

### ISSUE THREAD

**Issue by gkanarek** [astropy/astropy#5295]
When constructing a PrimaryHDU that contains no data, the default value for `BITPIX` is set to 8. This is true even when PrimaryHDU is passed a header with an existing BITPIX keyword.

Once this value is set, it's impossible to change without directly editing the `hdu._bitpix` attribute (setting `hdu.header['BITPIX'] = 16` has no effect, for example). Whenever the header is verified or updated, the value is reset to the stored `hdu._bitpix` value, and since there's never any data associated with the header, there's no reason for the HDU to think otherwise.

This wouldn't be a problem (there's no data for the FITS header to argue with, after all), except that some pipelines will crash with the wrong BITPIX. Since there's no FITS standard value for BITPIX when no data is associated with a header, there's never any warning or error, and the BITPIX value is changed silently.

At the very least, some kind of warning or information is essential. A better way to set the BITPIX value for an HDU with no data is probably important, especially when the HDU is passed an existing header.

**Comment by pllim** [comment]
Why would a pipeline crash with `BITPIX=8`? Could you please clarify? AFAIK, `BITPIX` is handled behind the scenes and not something that users or pipelines should worry about.

**Comment by embray** [comment]
The assertion that a BITPIX value can crash some pipelines was never followed up on.  The rest is kind of deliberate--users should not be manually editing the BITPIX keyword, by design (see #3837).

Setting BITPIX and other structural keywords should really be done by setting the data.  This can in fact be done even for a data-less HDU:

```python
>>> with fits.open('tmp.fits', mode='update') as hdul:
...     hdul[0].data = np.array([], dtype=np.int16)
... 
>>> fits.getheader('tmp.fits')
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                   16 / array data type                                
NAXIS   =                    1 / number of array dimensions                     
NAXIS1  =                    0                                                  
EXTEND  =                    T  
```
