### ISSUE TITLE
Improve numeric Table / io.ascii output precision

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#530]
In `Table` column output  there is some loss of precision possible because when no column format is specified then the output defaults to `str`, which doesn't round-trip for full precision doubles.   This affects `io.ascii.write` because that uses the `Table` formatting machinery.   See #526 which was the genesis of this issue.

From Python 2.7, `repr` is a good choice for numbers because it makes the output the smallest possible that is consistent with a binary value.  But for previous python versions I believe `repr` will generate a lot of `0.9999999999234232` where users would expect `1.0`.   @astrofrog has data indicating most astropy users are on Python 2.7 or later.

``` python
In [44]: t = Table([[1.000000000000056789]], names=['a'])

In [45]: print t
 a 

---
1.0

In [46]: t
Out[46]: 
<Table rows=1 names=('a')>
array([(1.0000000000000568,)], 
      dtype=[('a', '<f8')])

In [47]: from astropy.io import ascii

In [48]: ascii.write(t)
a
1.0
```

**Comment by taldcroft** [comment]
Pushing to 1.1 since I would still like to do this, somehow.

**Comment by astrofrog** [comment]
Removing milestone since not 1.1-critical

**Comment by taldcroft** [comment]
This seems to be OBE.
```
In [9]: t = Table([[1.000000000000056789]], names=['a'])

In [10]: print(t)
        a         
------------------
1.0000000000000568
```
