### ISSUE TITLE
Numpy dev error: indexing with boolean problems in sigma_clip

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5303]
Current builds with numpy-dev are failing for several tests of `sigma_clip`. See, e.g., https://travis-ci.org/astropy/astropy/jobs/157213150

I haven't looked very carefully at what happens, but it may be that some of these are problems in `MaskedArray` rather than our routines. In that case, we should report upstream...

**Comment by mhvk** [comment]
@MSeifert04 - thanks for investigating.  It seems clear this is an upstream problem, so I labelled it as such. 

Your numpy issue: https://github.com/numpy/numpy/issues/8015
Possible fix: https://github.com/numpy/numpy/pull/8016

**Comment by mhvk** [comment]
@taldcroft - there also is an error in `table.tests.test_info` that I must say I don't quite understand (and which I think is unrelated to the masked array problems): https://travis-ci.org/astropy/astropy/jobs/157213150#L2685

**Comment by mhvk** [comment]
@pllim - yet another error that seems to be appearing with numpy dev is that index values should be integer, but in `analytic_functions.tests.test_blackbody` a `logspace` with `1e6` elements is used -- just make this an integer...

**Comment by mhvk** [comment]
@pllim - I thought I might as well just push the fix myself, since it was a trivial one; see #5304.

**Comment by MSeifert04** [comment]
@mhvk Thank you for cross-linking it. :+1:

**Comment by mhvk** [comment]
@taldcroft - a bit more looking showed that the problem with the no-longer-caught warnings is due to https://github.com/numpy/numpy/pull/7148 -- there, a stack-level change means that the warning now is reported to come from our own module rather than from `numpy.lib.nanfunctions`. This likely means `IGNORE_WARNINGS` has to be adapted......  OK, see #5305

**Comment by mhvk** [comment]
Just for the record, this issue can be closed if https://github.com/numpy/numpy/pull/8016, #5304, and #5305 are merged.

**Comment by MSeifert04** [comment]
@mhvk FWIW: All your linked issues are closed.

**Comment by mhvk** [comment]
Yes, indeed!  I was still looking at `ChainMap` so forgot to close this one....  But will do so now.
