### ISSUE TITLE
Dictionary will be ordered in Python 3.6

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5320]
As mentioned in https://mail.python.org/pipermail/python-dev/2016-September/146327.html

Something to keep in mind for the future.

**Comment by mhvk** [comment]
Hmm, that thread specifically states that `**kwargs` and `cls.__dict__` will be guaranteed to be ordered, and that `dict` itself will be in `CPython`, but is not guaranteed to be in all python implementations.

But `**kwargs` would be a really nice one already...

**Comment by pllim** [comment]
I guess that depends on, "We might also implement these tricks in CPython, so dict will be ordered as well!"

**Comment by MSeifert04** [comment]
Am I right that the first beta for python 3.6 is scheduled for next monday? (https://www.python.org/dev/peps/pep-0494/#schedule)

**Comment by pllim** [comment]
Looks like it.

**Comment by astrofrog** [comment]
@pllim - thanks for the heads-up! I would suggest closing this to avoid having too many issues, since I don't think this will cause any issues and is certainly backward-compatible.

**Comment by MSeifert04** [comment]
Maybe it's worth it to add the python 3.6 beta (or nightly build) to CI and verify if all the changes are really backward-compatible.
