### ISSUE TITLE
Non-actionable warnings in astropy (specifically io.fits and units)

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#5332]
I have some production code where I added reading in a CIAO X-ray event file and it now generates a warning each time:

```
UnitsWarning: The unit 'angstrom' has been deprecated in the FITS standard. Suggested: nm (with data multiplied by 0.1).
```

Why are we issuing this warning?  A substantial fraction of FITS files are generated by some other person or institution and there is nothing to be done about this warning except add code to suppress it.  In my case this warning is causing a red flag every day to come up in our processing status board, so I really _have_ to suppress it.

Maybe if people really want to _opt in_ to these warnings it could be done via a configuration setting?

**Comment by astrofrog** [comment]
I agree that these warnings are a bit annoying to have by default (also incidentally I believe the angstrom warning is actually in error - https://github.com/astropy/astropy/issues/2933)

**Comment by astrofrog** [comment]
On the other hand, it might be necessary to emit warnings about units that get dropped or can't be parsed when reading a table so the user understands why the units aren't set properly?

**Comment by astrofrog** [comment]
The VO table warnings are particularly annoying when using notebooks - all VO tables produce warnings and many of them are harmless and nothing the user can do anything about.

**Comment by taldcroft** [comment]
I may be in the minority, but I think that there should be separation of file validation (as in conforming to the "standard", whatever that might actually be) and just reading a file.  The following does work according to my expectation but there is just some unsolicited and unwanted validation of my personal FITS file.
```
In [2]: t = simple_table()

In [3]: t['a'].unit = 'jabberwockies'

In [4]: t
Out[4]: 
<Table length=3>
      a          b     c  
jabberwockies             
    int64     float64 str1
------------- ------- ----
            1     1.0    c
            2     2.0    d
            3     3.0    e

In [5]: t.write('junk.fits')

In [8]: Table.read('junk.fits')
WARNING: UnitsWarning: 'jabberwockies' did not parse as fits unit: At col 0, Unit 'jabberwockies' not supported by the FITS standard.  [astropy.units.core]
Out[8]: 
<Table length=3>
      a          b     c  
jabberwockies             
    int64     float64 str1
------------- ------- ----
            1     1.0    c
            2     2.0    d
            3     3.0    e

In [9]: qt = QTable(t)

In [10]: qt
Out[10]: 
<QTable length=3>
      a          b     c  
jabberwockies             
   float64    float64 str1
------------- ------- ----
          1.0     1.0    c
          2.0     2.0    d
          3.0     3.0    e

In [11]: qt['a']
Out[11]: <Quantity [ 1., 2., 3.] jabberwockies>
```
So having a `parse_strict` flag for all readers that defaults to `silent` seems a good idea to me, with other options being `warn` and `raise`.  This would turn off all warnings like this.  It might be useful to have the default actually be a configuration variable so pedantic users (production environments?) can choose to be picky in a global sense.  (This name and allowed values is of course what is in the `Unit` constructor).

`votable` already has a `pedantic` flag and associated config var that can just be True/False.  So details of how to most nicely fit this into existing APIs would need to be worked out.

**Comment by astrofrog** [comment]
Actually to be fair, I think there should be a warning when you *write* the file, otherwise we are encouraging people to produce non-compliant files. But I agree things should be quieter when reading. I do think having validation during writing makes sense. In other words, I think we should be very forgiving on reading, but strict on writing (though not so strict as to error).

**Comment by taldcroft** [comment]
@astrofrog - agreed about warning on write and the general "strict on outputs and liberal on inputs" philosophy (robustness principle).

**Comment by mhvk** [comment]
It would seem that the machinery to silence the warnings is in place, as the `Unit` constructor has a `parse_strict` argument. It would seem to be just be a matter of setting that to a user-configurable default in the fits reader.

I also agree that the writer should emit a warning.

**Comment by mhvk** [comment]
(I removed the `units` label as this is really just a fits issue -- and I'm trying to cut down on the number of issues for `units`...).

**Comment by saimn** [comment]
The angstrom warning was removed in #5929. 
Is it useful to keep this issue open as the discussion is a bit more general ?

**Comment by bsipocz** [comment]
We still have a few of similar type of warnings (at least they look similar, but maybe we just need to fix the docs), even in our own docs build:

https://travis-ci.org/astropy/astropy/jobs/243350170#L4835

**Comment by pllim** [comment]
Just the ones at the end?
```
.../astropy/table/column.py:1233: MaskedArrayFutureWarning: setting an item on a masked array which has a shared mask will not copy the mask and also change the original mask array in the future.
Check the NumPy 1.11 release notes for more information.
  ma.MaskedArray.__setitem__(self, index, value)
```
```
WARNING: p0 does not seem to accurately represent the false positive rate for event data. It is highly recommended that you run random trials on signal-free noise to calibrate ncp_prior to achieve a desired false positive rate. [astropy.stats.bayesian_blocks]
```
```
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
```
```
WARNING: FITSFixedWarning: LONPOLE2= 180.000000000 /lonpole 
invalid alternate code, keyword resembles LONPOLEa but isn't. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: LATPOLE2= 0.00000000000 /latpole 
invalid alternate code, keyword resembles LATPOLEa but isn't. [astropy.wcs.wcs]
```

**Comment by bsipocz** [comment]
Yes, the latter three. 

The stat one is  more serious and we need to fix or get rid of the example (#4927), as that warning is actually not one of these "non-actionable ones" and breaks tests when using pytest 3.1.1 and sphinx 1.6.2

**Comment by saimn** [comment]
This issue is about io.fits and units ;), so none of the warning above are related. Now that angstrom is fixed, I think the more general case is what @taldcroft called the "strict on outputs and liberal on inputs philosophy". But I think there was also a PR related to this ?

**Comment by saimn** [comment]
Ah that's #5675. So with this I think the issue can be close. @taldcroft ?

**Comment by bsipocz** [comment]
The ``VerifyWarning`` is coming from io.fits

**Comment by pllim** [comment]
> But I think there was also a PR related to this ?

I think @bsipocz is trying to solve one in #6140 ?

**Comment by bsipocz** [comment]
I need to get #4927 sorted out in one way or the other for #6140, but the others are not critical for the sphinx build, thus I though they are covered with this issue.

**Comment by pllim** [comment]
Just on the `MaskedArrayFutureWarning`, when I hack test helper to turn all warnings into errors and test the `table` sub-package, there are 160 failures... :scream:

**Comment by pllim** [comment]
So, does anyone want to tackle the `table` and `io.fits` warnings? If there are no takers, I'll try it tomorrow (Friday).

**Comment by saimn** [comment]
About `MaskedArrayFutureWarning` we just need to wait Numpy 1.14 (the Numpy PR has been delayed twice but finally merged, see #5060). If it really needs to be removed, the best is to filter it...

**Comment by mhvk** [comment]
Indeed, we should not worry about the `MaskedArrayFutureWarning` -- it is just a warning that we should ensure we will not be bitten by the future behaviour, not one that things will necessarily break.

**Comment by saimn** [comment]
Ok, closing since the `io.fits` and `units` warnings were addressed in #5675 .
About the `VerifyWarning` I tried yesterday to find its origin, without success. @bsipocz , is there an issue related to this one ?

**Comment by bsipocz** [comment]
@saimn - No, I don't think so. Also it's a rather low priority as only a cosmetic issue, the warning doesn't cause any failure for us.

**Comment by pllim** [comment]
Okay, I'll move on to something else then. :smile:
