### ISSUE TITLE
Travis doc build failure: No module named 'PyQt4'

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5340]
I just merged #5335, which had passed travis without issues, but now the merge build errors out with:
```
from PyQt4 import QtCore, QtGui
ImportError: No module named 'PyQt4'
```

See https://travis-ci.org/astropy/astropy/jobs/160641762
(I tried restarting, but that didn't help). 

cc @astrofrog, @bsipocz

**Comment by MSeifert04** [comment]
see https://github.com/astropy/astroquery/pull/749 for a solution that worked for astroquery.

**Comment by MSeifert04** [comment]
Could be related to https://github.com/ContinuumIO/anaconda-issues/issues/1068

**Comment by mhvk** [comment]
Sounds like that would be it!  Thanks for investigating...

**Comment by astrofrog** [comment]
The easy fix is just to pin ``pyqt`` to ``pyqt==4``

**Comment by pllim** [comment]
Should we close this now the PR is merged?

**Comment by MSeifert04** [comment]
If there are no further problems with #5361 this can be closed too.
