### ISSUE TITLE
test_circmean_against_scipy is an inconsistent test

### ISSUE THREAD

**Issue by texadactyl** [astropy/astropy#5343]
astropy/stats/tests/test_circstats.py (testing against scipy.stats.circmean function) gets inconsistent results. When run as intended, as part of the test() function, it always fails.  When run in a loop of a small program, I see success ~1/2 of the time:

``` python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
import numpy as np
#from numpy.testing import assert_equal
#from numpy.testing.utils import assert_allclose
#from astropy import units as u
import scipy.stats
#from astropy.tests.helper import pytest
#from astropy.stats.circstats import _length, circmean, circvar, circmoment, circcorrcoef
from astropy.stats.circstats import circmean
#from astropy.stats.circstats import rayleightest, vtest, vonmisesmle

counter = 1
max_counter = 100
successes = 0
failures = 0

def test_circmean_against_scipy( arg_counter ):
    # testing against scipy.stats.circmean function
    data = np.random.uniform(-np.pi, np.pi, size=(100, 5))
    print ("test_circmean_against_scipy: data with %d elements" % len(data))
    #print (list(data))
    answer1 = scipy.stats.circmean(data, np.pi, -np.pi)
    print ("test_circmean_against_scipy: scipi answer = {%f}" % answer1)
    answer2 = circmean(data)
    print ("test_circmean_against_scipy: circmean answer = {%f}" % answer2)
    #assert_equal(np.around(answer1, 2), np.around(answer2, 2))
    if(np.around(answer1, 2) != np.around(answer2, 2)):
        print("*** MATCH %d FAILED ***" % arg_counter)
        return False
    else:
        print("$$$ MATCH %d SUCCEEDED $$$" % arg_counter)
        return True

while counter < max_counter:
    if( test_circmean_against_scipy( counter ) ):
        successes = successes + 1
    else:
        failures = failures + 1
    counter = counter + 1

print( "# successes = %d" % successes )
print( "# failures = %d" % failures )
```

**Comment by mirca** [comment]
@texadactyl Thanks for reporting! I'm going to take look into this soon.

**Comment by mirca** [comment]
@texadactyl By the way, which Scipy version are you using?

**Comment by texadactyl** [comment]
Numpy: 1.11.0
Scipy: 0.18.0
Matplotlib: 1.5.3
h5py: 2.6.0
Pandas: 0.18.1

**Comment by texadactyl** [comment]
Attached is a zip file of a log by running the full test()
[test_astropy.log.zip](https://github.com/astropy/astropy/files/479188/test_astropy.log.zip)

**Comment by mirca** [comment]
@texadactyl Hi, sorry for the delay.

Your samples are being draw from a uniform distribution with support  ``(-pi, pi)`` and in ``Scipy``  ``circmean`` function calling you modified the parameters ``high`` and ``low`` to ``pi`` and ``-pi``, respectively. That makes your samples to be shifted by ``pi`` (if you would like to check, it's [here](https://github.com/scipy/scipy/blob/v0.18.1/scipy/stats/morestats.py#L2673)), which does not happen in ``Astropy`` ``circmean``. Now, from the fact that ``cos(x + pi) = -cos(x)``, it follows that ``Scipy`` ``circmean``, in your example, will always return a mean angle in the range ``(-2pi, 0)``. ``Astropy`` ``circmean``, on the other hand, will always return a mean angle in the range ``(-pi, pi)`` no matter the range of your input samples.

``Astropy`` ``circmean`` is equivalent to ``Scipy's`` for the default values of ``high`` and ``low``, i.e., ``2pi`` and ``0``, respectively. I should have stated that. 

Would you like to open a PR for improving the docstrings or even implementing the boundary range capability? =D

**Comment by texadactyl** [comment]
@mirca  Hi, no need to worry about delay in responding.  I am not stopped by anything.  And I am not trying to make work for you!  (-:

Let me explain how I got to observing the anomalous behaviour that I reported.  Yes, I should have done this in the beginning.

I was here: http://docs.astropy.org/en/stable/install.html i.e. just after installing Astropy and the prerequisites - mostly out of curiosity.

I then created the 2-line test_astropy.py from the suggestion in the section entitled "Testing an installed Astropy":

```
import astropy
astropy.test()
```

That small Python program produced the test_astropy.log file whose zip I attached above.  I did nothing but execute it.  So, it is not my personal example, it is from that web page and I was following the suggestion there: "The tests should run and print out any failures, which you can report at the Astropy issue tracker".  
 
Of course, being a software engineer myself, that made me curious as to why astropy.test() was consistently failing the test_circmean_against_scipy() assertion.  So, I found the v0.18 source code in my local pip library and isolated it.  That is the full source above in the first message.  I simply replaced the assertion statement with conditional print statements, threw out the peer testing procedures (they all passed), and called test_circmean_against_scipy() repeatedly from a main program.  Please note that the original source code of circmean and scipy being tested is unaltered.

I saw that the "here" link [https://github.com/scipy/scipy/tree/v0.18.1/scipy/stats](url) implies a new version (v0.18.1) for Astropy.  Maybe this version has a fix for the astropy.test() suite?

Again, this is not urgent.  I am not stopped at any thing and, actually, I am busy with my own development at the moment.  I will definitely get back to Astropy in the near future.

If you would like me to try a fix, please let me know.
If you are busy too, don't worry about it.

Thanks for writing back so quickly.

**Comment by texadactyl** [comment]
I do see what you mean about the shift.   This is why it passes 1/2 the time!  

It looks like an issue in the test suite source code as part of the astropy package.  Let me look at this in a bit.

**Comment by mirca** [comment]
@texadactyl I'm sorry! I misunderstood your point!
@mhvk I think we solved that test in #5203, don't we?

**Comment by texadactyl** [comment]
The solution for est_circmean_against_scipy() was simple:
````
    answer1 = scipy.stats.circmean(data)
    answer2 = circmean(data)
    # Compare answer1 to answer2.  Never fails any more.
````

It matters not how the data array is generated.  One just has to compute the mean the same way for both answers before comparison.

**Comment by mhvk** [comment]
>  @mhvk I think we solved that test in #5203, don't we? Can we backport #5203 to 1.2?

That one should get backported automatically, since its milestone is 1.0.11.

**Comment by texadactyl** [comment]
Question: how do changes get propagated to pip libraries?  Thanks.

**Comment by bsipocz** [comment]
Closing this issue the fix has been merged and released.
