### ISSUE TITLE
Deprecation warnings cause test suite to not run with Python 3.6

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5344]
In order to get the test suite to run with Python 3.6.0b1, one has to comment out:

```
enable_deprecations_as_exceptions(include_astropy_deprecations=False)
```

in `astropy/conftest.py`. If this is not done, there are deprecation warnings such as:

```
/Users/tom/miniconda3/envs/py36/lib/python3.6/site-packages/_pytest/config.py:338: in _importconftest
    mod = conftestpath.pyimport()
/Users/tom/miniconda3/envs/py36/lib/python3.6/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
astropy/table/__init__.py:28: in <module>
    from .column import Column, MaskedColumn
astropy/table/column.py:15: in <module>
    from ..utils.console import color_print
E   DeprecationWarning: invalid escape sequence '\['
```

that occur. When running the tests with `python setup.py test`, the warnings are no very easy to see, so instead I recommend doing:

```
python setup.py build_ext --inplace
py.test astropy
```

to debug this. Does anyone have time to look into it?

**Comment by pllim** [comment]
Looks like it is related to [Deprecate invalid escape sequences in str/bytes in Python 3.6](https://bugs.python.org/issue27364).

**Comment by pllim** [comment]
I don't know how to install Python 3.6 via `conda`, but my suspicion is that the error came from `_color_text()` in `utils/console.py`:

```
return '\033[{0}m{1}\033[0m'.format(color_code, text)
```

**Comment by bsipocz** [comment]
I believe this must have been solved a while ago.
