### ISSUE TITLE
Only send Jenkins build failure notification for the commit that broke the build

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#535]
In the last days I have been getting emails from Jenkins for every commit anyone makes, because this build is broken:
https://jenkins.shiningpanda-ci.com/astropy/job/astropy-master-debian-py2.7-numpy-dev/874/changes

This is not useful, because I didn't break the build (I just made one small change to the documentation) and if it doesn't stop I'll set up a rule that deletes all email from the `astropy` Jenkins, which is bad should I contribute something in the future which actually brakes a Jenkins build.

Can you please change the Jenkins configuration so that notifications are only sent for the one commit that broke the build?

**Comment by devikirankhode** [comment]
Have you solved it by any chance?

**Comment by alexeyvip** [comment]
+ to @devikirankhode

**Comment by Gopi07nath** [comment]
Agree with @alexeyvip

**Comment by pllim** [comment]
We no longer use Jenkins on this repo. Please send your request upstream to Jenkins.
