### ISSUE TITLE
Old versions of the docs in search engines

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5367]
At the moment, Google sometimes returns results that point to e.g the v0.2 documentation - see e.g.:

https://twitter.com/jakevdp/status/781259020032147456

One way to deal with this is to do what yt did and make it so that only the stable docs are available at http://docs.astropy.org (not at http://docs.astropy.org/en/stable), and make sure all pages refer to the 'canonical' version of the docs: https://bitbucket.org/yt_analysis/yt/pull-requests/1693/docs-add-canonical-link-for-documentation/diff - this apparently stops search engines from indexing the non-canonical pages. However, there are I think several challenges here:
- We need to go back and re-build all the versions of the docs so that they all include this reference to the canonical version. Not unfeasible, but just means adding a commit in every maintenance branch.
- We would still break old links to the docs. However, we could in principle set up redirects so that all the old URLs still resolve to astropy.readthedocs.io/... - we can probably auto-generate these redirects, but just to say that this is not just a matter of flicking a switch.

One thing that's not clear to me with the canonical solution is what happens if you do select to browse an old version of the docs.

We do have to do _something_ though - it's pretty annoying to have v0.2 results show up in Google!

Another thing we could consider is to have a far more obvious banner at the top of the page that takes up the top third of the page that says 'you are viewing an old version' - but that won't stop Google indexing it.

cc @ngoldbaum (who suggested this on Twitter)

**Comment by ngoldbaum** [comment]
I don't think you need to rebuild old docs builds, we didn't need to.

**Comment by pllim** [comment]
If the version is not in LTS (like 0.2), we don't have to support it, right? With LTS, as long as we're pushing out bug fixes, logic follows that we also have to take care of the doc. Just a thought.

**Comment by ngoldbaum** [comment]
Also I think if you just made `http://docs.astropy.org/en/stable` the canonical URL, you wouldn't need to update any links.

**Comment by astrofrog** [comment]
This was addressed in https://github.com/astropy/astropy/issues/7967
