### ISSUE TITLE
Table I/O with sextractor format

### ISSUE THREAD

**Issue by kuntzer** [astropy/astropy#5384]
Loading a SExtractor output file mode fails depending on column order in the output SExtractor file. Namely, if some parameters that has several entries (like FLUX_RADIUS or ASSOC_VECTOR) is last in the SExtractor configuration, loading fails.

A following minimal example for loading some data is:

    import astropy.table as T
    assoc = T.Table.read("out_sextractor.dat", format='ascii.sextractor')

When the data is (e.g.)

    #   1 X_IMAGE                Object position along x                                    [pixel]
    #   2 Y_IMAGE                Object position along y                                    [pixel]
    #   3 VECTOR_ASSOC           ASSOCiated parameter vector                               
    #   6 FLAGS                  Extraction flags                                          
      25    50     26.1        50.1         1   0
      60    122     60.3     122.7      4   0

The command succeeds. However, when we have the same columns minus the FLAGS, i.e.:

    #   1 X_IMAGE                Object position along x                                    [pixel]
    #   2 Y_IMAGE                Object position along y                                    [pixel]
    #   3 VECTOR_ASSOC           ASSOCiated parameter vector                               
      25    50     26.1        50.1         1   
      60    122     60.3     122.7      4   

loading the file fails and this error is thrown: 

    astropy.io.ascii.core.InconsistentTableError: Number of header columns (3) inconsistent with data columns (5) at data line 0
    Header values: ['X_IMAGE', 'Y_IMAGE', 'VECTOR_ASSOC']
    Data values: ['25', '50', '26.1', '50.1', '1']

**Comment by Jerry-Ma** [comment]
What version of astropy are you using? It should have been fixed since v1.1.3, see https://github.com/astropy/astropy/pull/4603

Here is the output on my machine:

    In [8]: import astropy

    In [9]: astropy.__version__
    Out[9]: u'1.2.1'

    In [10]: from astropy.table import Table

    In [11]: a = Table.read('test.sex', format='ascii.sextractor')

    In [12]: a
    Out[12]: 
    <Table length=2>
    X_IMAGE Y_IMAGE VECTOR_ASSOC VECTOR_ASSOC_1 VECTOR_ASSOC_2
      pix     pix                                             
     int64   int64    float64       float64         int64     
    ------- ------- ------------ -------------- --------------
         25      50         26.1           50.1              1
         60     122         60.3          122.7              4

    In [13]:

**Comment by kuntzer** [comment]
I was using version v1.1.2, somehow I forgot to upgrade. It works perfectly now.
