### ISSUE TITLE
Links in inheritance diagram are broken

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5392]
This affects both `stable` and `latest` builds. For example in http://astropy.readthedocs.io/en/latest/wcs/index.html or http://astropy.readthedocs.io/en/stable/wcs/index.html , scroll down to "Class Inheritance Diagram" (near the bottom) and click on any of the boxes in the diagram.

If you click on "WCS", it links to http://astropy.readthedocs.io/en/api/astropy.wcs.WCS.html#astropy.wcs.WCS (broken). The correct links are http://astropy.readthedocs.io/en/latest/api/astropy.wcs.WCS.html#astropy.wcs.WCS (latest) or http://astropy.readthedocs.io/en/stable/api/astropy.wcs.WCS.html#astropy.wcs.WCS (stable).

I used WCS as an example, but this problem is global. For instance, you will also see broken links in `modeling`'s inheritance diagrams.

**Comment by MSeifert04** [comment]
Duplicate of #4935?

**Comment by pllim** [comment]
Yes... thanks for pointing that out. :sweat_smile:
