### ISSUE TITLE
Reading (a particular type of) votables gives error

### ISSUE THREAD

**Issue by aplavin** [astropy/astropy#5397]
Here is an example votable I can't read with astropy: http://vospace.esac.esa.int/vospace/sh/265c9a2292e138d1a5e11aaa742bb78a4c9ed6?dl=1 , but there are a lot of them of such kind.
So, you can download the table, unpack (to get a *.vot file) and try to read:

``` python
astropy.table.Table.read('1475831383991O.vot', format='votable')
# gives OSError: Not a gzipped file (b'\r\n')
```

and trying another way:

``` python
astropy.io.votable.parse_single_table('1475831383991O.vot')
# same error
```

So, anyway to deal with this and open the table?

**Comment by pllim** [comment]
First of all, try renaming the extension from `.vot` to `.xml`. Does it work now? If not, then run `volint` check on the file.

**Comment by pllim** [comment]
Also, which Astropy version are you using?

**Comment by astrofrog** [comment]
It looks like 1475831383991O.vot is actually a gzipped file?

```
$ mv 1475831383991O.vot 1475831383991O.vot.gz
$ gunzip 1475831383991O.vot.gz
$ $ head 1475831383991O.vot 
<VOTABLE version="1.3" xmlns="http://www.ivoa.net/xml/VOTable/v1.3">
<RESOURCE type="results">
<INFO name="QUERY_STATUS" value="OK"/>
<INFO name="ADQL_QUERY" value="select * from gaiadr1.variable_summary" />
<INFO name="CAPTION" value="If you use public Gaia DR1 data in your paper, please take note of our guide on how to acknowledge and cite Gaia DR1: http://gaia.esac.esa.int/documentation/GDR1/Miscellaneous/sec_credit_and_citation_instructions.html" />
<TABLE>
<FIELD datatype="long" name="solution_id" ucd="meta.id;meta.version">
<DESCRIPTION>solution_id</DESCRIPTION>
</FIELD>
<FIELD datatype="long" name="source_id" ucd="meta.id;meta.main">
...
```

If so, the extension is incorrect.

**Comment by aplavin** [comment]
@pllim 
I use the latest version - it says 1.2.1.
And changind extension doesn't work - gives the same error; I tried also format='ascii', but it doesn't help.

**Comment by aplavin** [comment]
@astrofrog 
oh, this seems to help with my issue - now this and other similar files open successfully. I actually had no idea what votable format looks like, so it didn't surprised me when I saw it's binary (gzipped) file. And the error message say almost the opposite - i.e. "Not a gzipped file" :)

Thanks!

**Comment by astrofrog** [comment]
Glad this helped! Before we close this, we should report this to the VO table providers though - I don't think this is normal!

**Comment by pllim** [comment]
VO table is supposed to be XML file. I don't know why this one came as gzip. Good catch, @astrofrog !

**Comment by astrofrog** [comment]
@aplavin - how did you get the link for this table in the first place? Which query service did you use?

**Comment by aplavin** [comment]
@astrofrog 
well, I used the service at http://gea.esac.esa.int/archive/ (GAIA program data) - after logging in there one can save query results as votables, which appear at VOSPACE tab.

**Comment by astrofrog** [comment]
Ok, so for anyone from ESA reading this (I'll forward the issue to them), it looks like the following link:

http://vospace.esac.esa.int/vospace/sh/265c9a2292e138d1a5e11aaa742bb78a4c9ed6?dl=1

returns a zip file. Inside that zip file is a file called ``1475831383991O.vot`` which is **not** a VO table but instead appears to contain a gzip archive that then contains the VO table. The double compression seems weird, but if this is intentional, then the file inside the zip file should be called ``1475831383991O.vot.gz`` not ``1475831383991O.vot``.

**Comment by astrofrog** [comment]
I'm going to close this since this is not an Astropy issue, but @aplavin, it would be great if you could report this to the GAIA helpdesk. Thanks!
