### ISSUE TITLE
Memory leak in compressionmodule.c

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5399]
As reported by @PierreAstier in spacetelescope/PyFITS#110. Suggested fix (for Numpy > 1.7) is in [this comment](https://github.com/spacetelescope/PyFITS/issues/110#issuecomment-251710362).

p.s. ~~It is yet unclear to me whether~~ that fix also applies to Numpy == 1.7. (EDIT: See comment below.)

**Comment by saimn** [comment]
`PyArray_ENABLEFLAGS` can be used with Numpy 1.7:
https://docs.scipy.org/doc/numpy/reference/c-api.array.html#c.PyArray_ENABLEFLAGS
