### ISSUE TITLE
Reshaping SkyCoord

### ISSUE THREAD

**Issue by gregreen** [astropy/astropy#5404]
It would be very convenient to be able to reshape the coordinate arrays inside a `SkyCoord` object. Ideally, this would be an in-place reshape, similar to returning a view of an array in `numpy`.

Currently, the only way I know how to reshape an arbitrary `SkyCoord` object is to copy (`ra`, `dec`), (`l`, `b`), etc. into a flat numpy array, and then to create a new `SkyCoord`. However, something like the following would be much more efficient:

    import numpy as np
    import astropy.units as u
    from astropy.coordinates import SkyCoord
    
    ra = np.random.random((10,10)) * 360.
    dec = np.random.random((10,10)) * 180. - 90.
    coords = SkyCoord(ra*u.deg, dec*u.deg, frame='icrs')
    
    # Reshape in place (hopefully this can be achieved by changing some strides)
    coords.shape = (100,)
    
    # Or return a view (which doesn't copy any data)
    coords_view = SkyCoord.reshape((10,10))

**Comment by mhvk** [comment]
This is being worked on -- see #5254!

**Comment by mhvk** [comment]
p.s. For now, #5254 just implements returning a new view.

**Comment by mhvk** [comment]
I'm closing this since #5254 has been merged. In principle, in-place is possible too, but slightly tricky (see https://github.com/astropy/astropy/blob/master/astropy/time/core.py#L504 for how it is done in `Time`); I don't think I'll get to that any time soon, but a PR is most welcome.
