### ISSUE TITLE
Evaluating an array with a FittableModel

### ISSUE THREAD

**Issue by eas342** [astropy/astropy#5405]
I followed the example of creating a simple linear model with astropy modeling.
http://docs.astropy.org/en/stable/modeling/new.html#a-full-example-of-a-linemodel

The model works fine on a scalar input. However, if I try and input an array, I get a ValueError: total size of new array must be unchanged.

    simpleModel = LineModel(1,0)
    x = np.array([1,2])
    simpleModel(x)
This does not happen with the `models.Linear1D()` model.

**Comment by mirca** [comment]
@eas342 Thanks for pointing that out!
