### ISSUE TITLE
astropy.io.fits corrupting FITS files

### ISSUE THREAD

**Issue by mommermi** [astropy/astropy#5413]
I am having a problem I can absolutely not explain. Running a script that modifies fits headers multiple times over a fits file will corrupt the file eventually. For instance, the following script:

```
from astropy.io import fits

filename = 'lmi.0110.fits'

for i in range(10):
    hdulist = fits.open(filename, mode='update')

    print 'update', i
    hdulist[0].header[('test%d' % i)] = ('test', 'more test')

    hdulist.flush()
    hdulist.close()
```

run over this [image ](http://134.114.60.45/tmp/lmi.0110.fits) will result in a missing end card IOError after 5 iterations:

> Traceback (most recent call last):
>   File "test.py", line 8, in <module>
>     hdulist = fits.open(filename, mode='update')
>   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 139, in fitsopen
>     return HDUList.fromfile(name, mode, memmap, save_backup, cache, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 281, in fromfile
>     save_backup=save_backup, cache=cache, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 839, in _readfrom
>     hdu = _BaseHDU.readfrom(ffo, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/base.py", line 423, in readfrom
>     **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/base.py", line 483, in _readfrom_internal
>     header = Header.fromfile(data, endcard=not ignore_missing_end)
>   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 451, in fromfile
>     padding)[1]
>   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 520, in _from_blocks
>     raise IOError('Header missing END card.')
> IOError: Header missing END card.

The corrupted file will look like [this](http://134.114.60.45/tmp/lmi.0110_corrupted.fits).

This problem has only occured on my laptop after I installed a clean version of Lubuntu 16.04. It works perfectly fine on a different machine (with the same version of astropy, 1.2.1) and it has worked fine on the same machine before the new installation. I was wondering if there are any dependencies that aren't met, which are not reported to me (there are no warning/error during the installation of astropy)?

I am thankful for any help,
Michael

**Comment by mommermi** [comment]
Quick update: I installed anaconda and that does not show this erroneous behavior on the same machine. Hence, I believe that the problem is caused by an installation issue. 

I can close this issue unless somebody is interested in finding out what caused this conflict. Not sure if this has any legacy value...

**Comment by pllim** [comment]
@mommermi , thanks for the update. You can close this. If anyone else has the same issue, it will still show up in a search.
