### ISSUE TITLE
Table doc needs meta comments instructions

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5416]
Someone asked me how to write out comment lines to ASCII file and I had to dig into a change log entry, then into the associated PR, and then look at the actual source code to figure it out. Something like this should be more obvious in the doc, maybe [here](http://docs.astropy.org/en/latest/table/construct_table.html):

``` python
# This will turn into comment lines in output ASCII file unless
# comment=False is explicitly set in write().
t.meta['comments'] = ['here is my explanatory text. this table is made with '
                      'this and that, and i also did some other stuff',
                      'second comment line']
```

**Comment by taldcroft** [comment]
There is documentation of this, but not an explicit example and it is a bit hidden.  See the `comment` parameter in http://docs.astropy.org/en/stable/io/ascii/write.html#parameters-for-write.

**Comment by pllim** [comment]
Good to know. Thanks, @taldcroft ! c/c @bhilbert4

**Comment by ritwickdsouza** [comment]
I will work on this. So do i just add an example under the comment part ? Or do something else ?

**Comment by taldcroft** [comment]
@ritwickdsouza - probably a new section in the Writing tables page with an example.  Your initial exercise is to scan the page and find a sensible place to put it.
