### ISSUE TITLE
Numpy-dev failures in master as of 2016-10-18

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5419]
As reported by https://travis-ci.org/astropy/astropy/jobs/168654883 . I got it to pass a week or two ago after fixing Cone Search test, but it is failing from other packages now, so must be related to some PRs merged since then.

**Comment by mhvk** [comment]
Really weird, it looks like some of the problems are due to numbers being formatted differently, possibly because a default format gets set in some remote-data test.

**Comment by mhvk** [comment]
Most errors are actually due to a change in numpy-dev, which causes record arrays to be formatted differently: https://github.com/numpy/numpy/pull/8160

**Comment by pllim** [comment]
In that case, what is the best way to fix this? Is there a "only run this doctest if numpy is version such and such"?

**Comment by mhvk** [comment]
It turns out there is another numpy-dev issue as well (`allcose(np.nan, np.nan)` no longer returns `True`), so I think best is to have a PR that fixes this.  Working on it...

**Comment by mhvk** [comment]
@astrofrog - on these "allowed failures" -- would it be possible to autogenerate an e-mail (or issue?) if something is merged in master that fails?

**Comment by mhvk** [comment]
See #5423 for what hopefully will fix the remaining numpy-dev problems...

**Comment by bsipocz** [comment]
@mhvk - I believe it's possible, remind me about it please in a week time (or open an issue somewhere, I can be assigned).

**Comment by bsipocz** [comment]
So for the first look it's seems possible to get e-mails/gitter/slash/etc notifications, but they will be sent out based on the whole travis status and not individual builds. 
I'll contact travis to confirm this, and to point to us to a workaround if there is any.

**Comment by astrofrog** [comment]
@mhvk @bsipocz - what about using something like https://gist.github.com/astrofrog/061aed7312da223f76ba38e096981780 as a cron job? (maybe showing only the message when it fails)

**Comment by astrofrog** [comment]
Looks like this can be closed - we should open a new issue if there are other failures. Thanks @mhvk!
