### ISSUE TITLE
Add feature: rotate spherical coordinate

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#542]
Once #471 gets merged I want to add code to rotate a given point on the sphere around a given center by a given angle.

Should this be implemented as an independent function

```
def rotate(point, center, angle)
```

or a `SphericalCoordinatesBase` method?

```
SphericalCoordinatesBase.rotate(center, angle)
```

I think it's very easy to implement with numpy:
- Transform `center` to `point` system
- Convert `center` and `point` 3D cartesian vectors
- Compute rotated `point` vector using Rodrigues formula ( http://en.wikipedia.org/wiki/Rodrigues%27_rotation_formula )
- Convert rotated `point` vector back to spherical coordinates.

@eteq Is this a welcome addition?

**Comment by astrofrog** [comment]
I've removed the 1.0 milestone since there is no progress on this.

**Comment by AMAN3003** [comment]
@cdeil  i would like to work on this issue if it's not closed please provide me relevant link on how to develop rotation function

**Comment by bsipocz** [comment]
I wonder whether this one is solved with the shiny new Astrometric frames?

**Comment by eteq** [comment]
yes, I'd say this case is covered by the `SkyOffsetFrame` machinery, so closing.  But can be re-opened if not!
