### ISSUE TITLE
test_erfa_planet fails on i386

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#5425]
On 32 bit x86, `TestPositionKittPeak.test_erfa_planet` fails by newer returning.
I could locate the loop in [this loop in `solar_system.py`](https://github.com/astropy/astropy/blob/master/astropy/coordinates/solar_system.py#L412). The absolute value of `delta_light_travel_time` here jumps between 7.91119372419e-11 AU s / m, 7.91011123661e-11 AU s / m, and 1.08248758387e-14 AU s / m.
Python version is 2.7.12, erfa 1.3.0. This didn't happen before (with Python 2.7.12rc1, erfa 1.2.0).

Full build log [here](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=i386&ver=1.2.1-1%2Bb1&stamp=1477058939&file=log)

Unfortunately, I have no tests in between, so it may be anything... I also just had another mystic regression on i386 (with the CPL library), so it is not excluded that it is caused by the C compiler (gcc-6.2.0) or so. But if anyone could have a look to the mentioned loop and could give some advise?

**Comment by pllim** [comment]
Will this be solved by #5418?

**Comment by olebole** [comment]
No -- vice versa it may be a cause.
On Debian we have unbundled erfa, and we already use version 1.3.0 (but didn't in the last build, which succeeded).

**Comment by mhvk** [comment]
@olebole - thanks for the detailed report! The one thing that may have changed with erfa 1.3 is how near-the-sun is treated. Does the test hang for `body='sun'`? 

I also wonder whether there is some `float32` vs `float64` problem (given that this breaks on 32 bit). One possible test would be to see if the problem goes away if you change `np.float` to `np.float64` at https://github.com/astropy/astropy/blob/master/astropy/units/quantity.py#L299. Though it would seem strange if this would not have caused problems before...

cc @StuartLittlefair

**Comment by olebole** [comment]
I made another test with erfa-1.2 and then the build succeeds. There are also a number of errors that were hidden by the lockup in `test_erfa_planet`:
```
__ ERROR collecting lib.linux-x86_64-2.7/astropy/time/tests/test_sidereal.py ___
astropy/time/tests/test_sidereal.py:24: in <module>
    class TestERFATestCases():
astropy/time/tests/test_sidereal.py:34: in TestERFATestCases
    assert np.allclose(time_ut1.tt.jd2 - time_tt.jd2, 0., atol=1.e-14)
E   assert <function allclose at 0xf6f210d4>((-0.4999999999999999 - 0.5), 0.0, atol=1e-14)
E    +  where <function allclose at 0xf6f210d4> = np.allclose
E    +  and   -0.4999999999999999 = <Time object: scale='tt' format='jd' value=2453735.5>.jd2
E    +    where <Time object: scale='tt' format='jd' value=2453735.5> = <Time object: scale='ut1' format='jd' value=2453736.5>.tt
E    +  and   0.5 = <Time object: scale='tt' format='jd' value=2453736.5>.jd2
```
and a number of failures like:

```
```astropy/coordinates/tests/test_solar_system.py:141: AssertionError
________________________ TestSubFormat.test_epoch_times ________________________

self = <astropy.time.tests.test_basic.TestSubFormat instance at 0xecf8e56c>
[...]
        for scale in ('utc', 'tt'):
            t = Time('2000:001', scale=scale)
            t2 = Time(t.unix, scale=scale, format='unix')
>           assert getattr(t2, scale).iso == '2000-01-01 00:00:00.000'
E           assert '1999-12-31 00:00:00.000' == '2000-01-01 00:00:00.000'
E             - 1999-12-31 00:00:00.000
E             + 2000-01-01 00:00:00.000

astropy/time/tests/test_basic.py:681: AssertionError
_____________________________ test_fits_year10000 ______________________________

    def test_fits_year10000():
        t = Time(5373484.5, format='jd', scale='tai')
        assert t.fits == '+10000-01-01T00:00:00.000(TAI)'
        t = Time(5373484.5 - 365., format='jd', scale='tai')
        assert t.fits == '9999-01-01T00:00:00.000(TAI)'
        t = Time(5373484.5, -1./24./3600., format='jd', scale='tai')
>       assert t.fits == '9999-12-31T23:59:59.000(TAI)'
E       assert '9999-12-30T23:59:59.000(TAI)' == '9999-12-31T23:59:59.000(TAI)'
E         - 9999-12-30T23:59:59.000(TAI)
E         ?          ^
E         + 9999-12-31T23:59:59.000(TAI)
E         ?          ^
```
and more in the `time` submodule, which all go away with the builtin erfa. So, erfa or its interface to astropy is probably the cause; however erfa itself passes all of its own tests.

The problem is not "just" a 32/64 bit problem. On all other 32-bit architectures (arm, mips, powerpc), the tests succeed. I will, however, also do your ( @mhvk ) tests.

**Comment by olebole** [comment]
@mhvk - I did the tests (just replacing `"mercury"` with `"sun"` and `np.float` --> `np.float64`) and they didn't help. I am however working with astropy-1.2.1, so the line number for the latter differs a bit from your.

**Comment by StuartLittlefair** [comment]
The issues with light travel time may be a knock on effect of applying the solar deflections twice; once within erfa and once within our own wrappers for ```aticq```. 

I'll look into it this afternoon.

**Comment by StuartLittlefair** [comment]
I haven't made much progress with this, except to confirm that it's not the changes made to ERFA in V1.3.0 for directions towards the Sun which are in error; we are too far from the solar limb when these tests are run for that to matter.

I don't have access to i386 architecture to run tests, which is hampering me somewhat, but I get consistent behaviour using astropy 1.2.1, the latest astropy or the @mhvk's PR to use erfa 1.3.0.

@olebole some of the other tests which are failing, for example the ```test_fits_year10000``` are independent of ```erfa``` and are just re-formatting the time object into some Y-M-D type format. The fact that these tests are failing make me wonder that there is some issue with your C compiler or Python installation.

**Comment by olebole** [comment]
Yea, it is still mystic to me as well. Here is what I tested:
* erfa-1.2 externally passes, even if newly built
* erfa-1.3 externally locks up: both with the package that is in Debian as well as with a newly built package
* erfa internally (just without `--use-system-erfa`) works
* erfa internally with updating to 1.3 works

I will repeat the two external builds to see that I didn't make a mistake there (like the wrong package chosen), but otherwise I have no idea what is going on there. However, the patch (in `ldsun.c`) is one that is significant for `test_erfa_planet.py`, right?

Is the erfa interface completely independent of whether erfa is built externally or internally?

**Comment by olebole** [comment]
I think I found the cause; it is (probably) really a compiler issue. Between erfa-1.2.0 and 1.3.0, in the Debian package the `CFLAGS` changed a bit (mainly `-O2` was re-added), and the gcc-6.2 compiler seems to be a bit buggy at i386 (another bug [here](https://github.com/liberfa/erfa/issues/33)). Resetting the compiler flags back (removing `-O2`) succeeds completely.

**Comment by mhvk** [comment]
A very strange bug (seems like a precision issue, since it is at the 1e-8 level); I hope the bug in gcc can be found.  Since it does seem a gcc issue, I added the "upstream fix required" label. Is there something we can do in `erfa` to help ensure this doesn't bite people?

**Comment by olebole** [comment]
The only thing I could imagine is to extract these cases as tests to era.

**Comment by olebole** [comment]
After some discussion of the problem with @juliantaylor, I'd like to put my conclusions here as well as a copy:

 The function `eraStarpv()` is quite inaccurate because of [`sqrt(1.0 - betr*betr - bett*bett) - 1.0`](https://github.com/liberfa/erfa/blob/2fd66489dfa61e119bf50c4ed1db80db6ba3e9f9/src/starpv.c#L183), if `betr` and `bett` are very small. In the test case of astropy, they are ~10^-8, which translates into an accuracy of only ~8 digits.  Astropy however seems to need a higher accuracy in [this loop](https://github.com/astropy/astropy/blob/2cb4567eff9d09540e76024a54653c593d4a41c8/astropy/coordinates/solar_system.py#L412) when handling ephemerides.
IMO, there are two things needed/possible here:
 * [the mentioned code line](https://github.com/liberfa/erfa/blob/2fd66489dfa61e119bf50c4ed1db80db6ba3e9f9/src/starpv.c#L183) should be changed for small values of `betr` and `bett` (use polynom instead of square root in this case, or similar). This should be discussed with upstream. Or at least the limited precision should be documented.
 * Astropy should not assume that the precision of `eraStarpv()` is very high, and change the [loop](https://github.com/astropy/astropy/blob/2cb4567eff9d09540e76024a54653c593d4a41c8/astropy/coordinates/solar_system.py#L412) accordingly. I will copy my comments to astropy/astropy#5425 as well.

The point here is IMO that the x87 FPU does not give wrong results, but just different ones. Both results are as expected within the accuracy, the 64-bit results are just more predictable. This gives us the chance to find exactly such problems, and therefore I would vote against just setting `-mfp=sse` or such. Instead, i386 CI tests would be quite useful.

**Comment by StuartLittlefair** [comment]
@olebole can you explain more why you believe precision in ```eraStarpv``` to be an issue? The test case which gets caught in an infinite loop should never call that particular routine...

**Comment by olebole** [comment]
Oops, I am starting to mix up things here.
liberfa/erfa#33 has nothing to do with the problem here; I just mentioned it here because it is another bug that arises in erfa when `-O2` is switched on on i386. It is not the cause, so my previous comment is nonsense -- the specific problem is different.

**Comment by olebole** [comment]
I digged into it a bit deeper, and indeed the problem is different here: In this case, the problem is not coordinates, but time.
Simple test (when all goes OK, f.e. erfa compiled with `-O0`):
```
>>> from astropy.time import Time
>>> from astropy import units
>>> t = Time('2014-09-25T00:00')
>>> print t - 1000 * units.s
2014-09-24T23:43:20.000
>>> print t - 1100 * units.s
2014-09-24T23:41:40.000
```
When erfa is compiled with `-O2`:
```
>>> from astropy.time import Time
>>> from astropy import units
>>> t = Time('2014-09-25T00:00')
>>> print t - 1000 * units.s
2014-09-24T23:43:20.000
>>> print t - 1100 * units.s
2014-09-25T23:41:40.000
```
So, somehow, subtraction of time gets confused here. The never-ending loop that causes this issue recalculates the time in each iteration, which then causes the problem.

**Comment by mhvk** [comment]
That sounds much closer to the problem found in #5466 -- internally, when you subtract some number of seconds from a `UTC` time, it gets converted to `TAI`, then the seconds are substracted, and then the time is converted back to `UTC` -- so the problem must be in the UTC<->TAI conversion, like in #5466, which would pin it down to `utctai` or `taiutc`. Since the problem depends on how much you subtract, it has to be the latter one.  If it is easy to do, could you confirm with:
```
print t.tai - 1100 * units.s
# 2014-09-24T23:43:55.000
print (t.tai - 1100 * units.s).utc
# 2014-09-24T23:43:20.000 -> should be different for -O2
print Time('2014-09-24T23:43:55.000', scale='tai').utc
# 2014-09-24T23:43:20.000 -> should be different for -O2
```

Looking at `taiutc`, I see an iteration at https://github.com/liberfa/erfa/blob/master/src/taiutc.c#L83 -- though it is hard to see how it could really hurt.

**Comment by olebole** [comment]
Here are the results:
```
>>> print t.tai - 1100 * units.s
2014-09-24T23:42:15.000
>>> print (t.tai - 1100 * units.s).utc
2014-09-25T23:41:40.000
>>> print Time('2014-09-24T23:43:55.000', scale='tai').utc
2014-09-24T23:43:20.000
```
So, the second print is different. Checking the conversion (on the `-O2` lib):
```
>>> import astrop._erfa as erfa
>>> erfa.taiutc(2456925.0, 0.4876736111111111)
(array(2456925.0), array(1.4872685185185186))
```
which is different without optimization:
```
>>> erfa.taiutc(2456925.0, 0.4876736111111111)
(array(2456925.0), array(0.4872685185185185))
```

**Comment by mhvk** [comment]
Great detective work!

> So, the second print is different. 

Which is because I copied & pasted wrong... The last one should have been
```
print Time('2014-09-24T23:42:15.000', scale='tai').utc
```

Anyway, I think it doesn't matter too much any more -- it is now clear where the problem lies.

**Comment by mhvk** [comment]
The fix is now in SOFA, so once we have a new erfa version, this can hopefully be closed.

**Comment by rmathar** [comment]
In SOFA version 13 of 2014-04-20 the square root expression was changed to an equivalent expression which suffers less from canellation of digits, see http://www.iausofa.org/current_changes.html

**Comment by olebole** [comment]
Yea, they are not really carefully acknowledging where they got the solution from :-(
The patch was done in liberfa/erfa#41 and sent to upstream later, and one would usually expect that this origin is mentioned somewhere in SOFA (Announcement, Changelog, `THANKS` file or whatever). But IAU is different...

**Comment by mhvk** [comment]
Indeed, it has been a bit sad that we even had to go the erfa route in the first place, instead of realising that it was *good* that people wanted to use the code and that that would mean bugs would be found. But in fairness, I don't think the people who work on IAU committees get all that much credit from the community for their often thankless tasks. On a more positive note, perhaps we should specifically include feedback upstream in the astropy paper 2...
