### ISSUE TITLE
Test on 32 bit?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5426]
A bug failure on 32-bit `i386` found by @olebole in #5418 made me wonder whether it is possible to test more broadly on travis. We already do macos, could we perhaps change one of the "old python, old numpy" configurations to run on 32 bit? (No idea whether this is possible... Semi-randomly pinging @bsipocz, @MSeifert04, @astrofrog)

**Comment by MSeifert04** [comment]
There seems to be a simple trigger in AppVeyor: [`PYTHON_ARCH`](https://github.com/astropy/astropy/blob/master/appveyor.yml#L10). Not sure about Travis.

**Comment by astrofrog** [comment]
I tried some experiments here: https://github.com/astropy/ci-helpers/pull/65 but it was a pain to set up on Travis. Maybe someone else can try this?

**Comment by juliantaylor** [comment]
numpy has 32 bit travis tests by bootstrapping a 32 bit ubuntu, see the setup_chroot in tools/travis-test.sh
it adds a couple minutes overhead but its not too bad.
thought do you have enough C code to make this worthwhile?
