### ISSUE TITLE
Cython failures on _np_utils.pyx

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5437]
Both travis and appveyor are failing their builds on `astropy/table/_np_utils.pyx`. In https://github.com/astropy/astropy/pull/5418#issuecomment-256500524, @MSeifert04 noticed that for appveyor it is related to a cython version change. Anyone have suggestions??

**Comment by astrofrog** [comment]
We could pin the Cython version for now. Can anyone reproduce this locally?

**Comment by cdeil** [comment]
You mean this fail, right?
https://travis-ci.org/astropy/astropy/jobs/170934448#L1642
```
error: unknown file type '.pyx' (from 'astropy/table/_np_utils.pyx')
```

I don't see the fail with Astropy master and Cython 0.24.1.
The build log doesn't contain the Cython version used (can this be added, please?).
Is it Cython 0.25?

**Comment by astrofrog** [comment]
The Cython version is inside the part of the log related to ci-helpers:

```
    cython-0.25                |           py35_0         2.6 MB
```

But it could be indeed added to the py.test header.

**Comment by astrofrog** [comment]
I see the failure locally with Cython 0.25

**Comment by saimn** [comment]
> I see the failure locally with Cython 0.25

Same here. Though I don't have the issue with another project which uses cython and not astropy-helpers.

**Comment by saimn** [comment]
There is already Cython 0.25.1 which appears to fix the issue.
https://github.com/cython/cython/blob/master/CHANGES.rst#0251-2016-10-26
I guess it is related to *"The distutils extension Cython.Distutils.build_ext has been reverted, temporarily, to be old_build_ext to give projects time to migrate. The new build_ext is available as new_build_ext."*

**Comment by eteq** [comment]
Hopefully conda will update the bundled Cython ASAP and then we can close this, but maybe if it isn't fixed within a day we should temporarily pin the version to 0.24.x?

**Comment by MSeifert04** [comment]
Did someone mention the problem in the anaconda/conda issue tracker? Often they provide the new build/version very fast ... if they know it's causing problems.

**Comment by MSeifert04** [comment]
At least for Windows cython 0.25.1 is avaiable now. Could be worth restarting on test (maybe #5214? 😄) to see if it's working again.

**Comment by mhvk** [comment]
Travis now has been updated as well, so closing this.
