### ISSUE TITLE
'Edit page on github' broken for some pages

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#5457]
For example, this one:

http://docs.astropy.org/en/stable/generated/examples/io/skip_create-large-fits.html

which links to 404:
https://github.com/astropy/astropy/tree/v1.2.x/docs/generated/examples/io/skip_create-large-fits.rst

**Comment by keflavich** [comment]
I think this may be specific to generated docs from examples

**Comment by bsipocz** [comment]
#8258 was supposed to make those links go away, yet someone still run into the issue today:
```
I found a minor typo in the astropy docs but when I click to view it on github, the link is incorrect (github says the page isn't found). Does anywhere know where I can suggest a fix?
```

If the latter is followed up, then this issue can be closed, too.

**Comment by bsipocz** [comment]
OK, so the complaint is not for `edit-on-github` but for the github links from RTD that is different. So I'm going ahead and close this issue, and open a new for the new problem.
