### ISSUE TITLE
Copying astropy objects

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#546]
Being able to make an independent copy of a given object is generally useful for almost all objects.

The use case I have in mind is this: I often write functions that take an input object (a Time, Coordinate, Table, HDU, WCS, ...) and I want to change some attributes without having to know or care about all other attributes, and return a modified version, leaving the input object unchanged.

One example is #542, where I wanted to copy and modify a Coordinate but didn't know how to do it ...

Python programmers are usually familiar with the `copy(x)` and `deepcopy(x)` functions from the Python standard library [copy module](http://docs.python.org/3/library/copy.html).

This would be one option for astropy, we would have to add `__copy__()` and `__deepcopy__()` for classes where the default Python behaviour wouldn't work (I haven't tried calling `copy` and `deepcopy` for many astropy objects, so who knows, maybe this already works very well everywhere?) but in any case we should test and document it for end-users if this is the standard way to work in astropy.

The alternative is to add `.copy(self)` and / or `.deepcopy(self)` or `copy(self, deep=True)` methods to most classes. Some `astropy` classes like `astropy.units.quantity.Quantity` or `astropy.wcs.wcs.Wcs` do this already:
http://docs.astropy.org/en/latest/search.html?q=copy

Many others, like e.g.  `astropy.table.Table` or `astropy.coordinates.GalacticCoordinate`  don't have a `copy(self)` method.

There is one class, `astropy.time.Time`, which calls `deepcopy` [replicate](http://docs.astropy.org/en/latest/_generated/astropy.time.core.Time.html?#astropy.time.core.Time.replicate).

What do we want for `astropy`?

If others think this is an important topic we could try to hash out a proposal here and then put it on `astropy-dev` mailing list or as an `astropy-api` pull request?

The most important point I think would be to hash out the semantics of `copy` and `deepcopy` for each case and how to write unit tests in a generic way so that the effort of adding this to all astropy objects remains small.

**Comment by nstarman** [comment]
Solved by #16887

**Comment by neutrinoceros** [comment]
Good point. Should we close this one as duplicate then ?

**Comment by pllim** [comment]
Did we close a three digit issue after 12 years? I had to do a double take! 👏
