### ISSUE TITLE
pytest yield tests are deprecated

### ISSUE THREAD

**Issue by opoplawski** [astropy/astropy#5465]
WC1 /builddir/build/BUILDROOT/python-astropy-1.2.1-4.fc26.i386/usr/lib/python2.7/site-packages/astropy/io/votable/tests/vo_test.py yield tests are deprecated, and scheduled to be removed in pytest 4.0

**Comment by pllim** [comment]
This looks like a subset of #5277.

**Comment by bsipocz** [comment]
I believe this has been solved as astropy now compatible with the latest pytest version. Please reopen if you still run into this issue.
