### ISSUE TITLE
discretize_model with non-integer ranges

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5472]
The following example:

```python
from astropy.modeling.models import Gaussian2D
from astropy.convolution import discretize_model

g = Gaussian2D(1, 0, 0, x_stddev=3.4, y_stddev=5.5, theta=40.)
beam = discretize_model(g,
                        x_range=[-5.5, 5.5],
                        y_range=[-5.1, 5.2],
                        mode='oversample', factor=100)
```

causes the following exception:

```
Traceback (most recent call last):
  File "debug.py", line 8, in <module>
    mode='oversample', factor=100)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/convolution/utils.py", line 168, in discretize_model
    return discretize_oversample_2D(model, x_range, y_range, factor)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/convolution/utils.py", line 259, in discretize_oversample_2D
    values = np.reshape(values, shape)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 225, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged
```

So the question is, is the function designed to only work with integer values in ``x_range`` and ``y_range``? This would make sense, but in that case we should do some input validation to avoid issues like that, and make sure the docstring specifies the integer requirement.

cc @adonath @cdeil

**Comment by adonath** [comment]
@astrofrog Yes, that's indeed a bug and it's even worse, because e.g. if you specify `factor=1` it returns an off-centered beam, because `np.arange(-5.1, 5.2)` (see code [here](https://github.com/astropy/astropy/blob/master/astropy/convolution/utils.py#L245)) yields a non integer grid, which introduces a subpixel shift of up to 1/2 pixel.

See this example:
```
from astropy.modeling.models import Gaussian2D
from astropy.convolution import discretize_model

g = Gaussian2D(1, 0, 0, x_stddev=3.4, y_stddev=5.5, theta=40.)
beam = discretize_model(g,
                        x_range=[-5.5, 5.5],
                        y_range=[-5.1, 5.2],
                        mode='oversample', factor=1)
plt.imshow(beam, interpolation="None")
```
![beam](https://cloud.githubusercontent.com/assets/3715928/20305627/c198a6ee-ab36-11e6-858f-395f30dd0e72.png)

One solution could be to specify the shape of the array instead of the `x_range` and `y_range`.  Or round `x_range` and `y_range` to the nearest integers.

**Comment by astrofrog** [comment]
I think the shape wouldn't be enough since if the model is centered at the origin, you need to be able to start at negative positions. The different solutions are:

1. Allow only integers (and 'round' floats like 3.0) in ``x_range`` and ``y_range`` (no auto-rounding)
2. Require the shape to be specified in addition to the range. For instance, one could request a model discretized between -122 and 33 in x using 8 discrete bins (so the range is no longer used to determine the size)
3. Change discretize_model to take an origin for the lower left hand corner and an array shape (the origin could be a non-integer position)

Option 2 would actually be the most general, and we could make it backward compatible by saying that if the range consists of integers or rounded floats then the shape defaults (if not specified) to what we are doing now.

**Comment by eteq** [comment]
In some out-of-band discussion with @astrofrog, we concluded #5472 doesn't fully fix this because it allows integer ranges still.  And I think we agreed the option 2 from above is better.  But #5472 is still an improvement in the current behavior, so it's in for 1.3!

**Comment by keflavich** [comment]
Brief update:
```
In [1]: %paste
from astropy.modeling.models import Gaussian2D
from astropy.convolution import discretize_model

g = Gaussian2D(1, 0, 0, x_stddev=3.4, y_stddev=5.5, theta=40.)
beam = discretize_model(g,
                        x_range=[-5.5, 5.5],
                        y_range=[-5.1, 5.2],
                        mode='oversample', factor=100)

## -- End pasted text --
Traceback (most recent call last):
  File "<ipython-input-1-2120acda1cd6>", line 8, in <module>
    mode='oversample', factor=100)
  File "/Users/adam/miniconda3/lib/python3.7/site-packages/astropy/convolution/utils.py", line 164, in discretize_model
    raise ValueError("The difference between the upper an lower limit of"
ValueError: The difference between the upper an lower limit of 'y_range' must be a whole number.
```

`an` -> `and`, but... should this issue remain open?

**Comment by pllim** [comment]
@keflavich , you wanna open PR to fix the typo? 😉

**Comment by neutrinoceros** [comment]
The typo was fixed in https://github.com/astropy/astropy/pull/10696
I don't think there's any actionable left on this issue and I'd recommend to close it.
