### ISSUE TITLE
[1.2.1] does not work with wcslib 4.24

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#5476]
Astropy still should work with wcslib 4.24 (at least the CHANGES.rst dosn't mention a change), it does not. This makes backporting to older (Debian) versions difficult.
Quoting from the [original Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844525) (Sergio Gelato):

> In trying to backport this version of astropy to jessie, I discovered that it doesn't build against wcslib-dev 4.24 as advertised in debian/control.
>
> The reason is that astropy/wcs/src/wcslib_wrap.c and astropy/wcs/wcs.py both refer to WCSHDO_P14 which was only introduced in wcslib 5.13.  Incidentally, that means the statement in astropy/wcs/wcs.py that "versions 5.8 and later on the 5.x series are known to work" is of questionable accuracy; I guess upstream will need to be told.
>
> Browsing through version control I see that this broke in astropy 1.1.2. (I'll probably backport 1.1.1 instead, since my actual requirement is (>= 1.0) and upgrading wcslib in jessie risks breaking other things.)

It would be nice if 4.24 is still supported. If not, please document this,

**Comment by MSeifert04** [comment]
I think this was mentioned in https://github.com/astropy/astropy/blob/master/CHANGES.rst#other-changes-and-additions-3, because of some Bugfix:

> Fixed a bug that caused WCS objects with a high dynamic range of values for certain parameters to lose precision when converted to a header. This occurred for example in cases of spectral cubes, where a spectral axis in Hz might have a CRVAL3 value greater than 1e10 but the spatial coordinates would have CRVAL1/2 values 8 to 10 orders of magnitude smaller. This bug was present in Astropy 1.1 and 1.1.1 but not 1.0.x. This has now been fixed by ensuring that all WCS keywords are output with 14 significant figures by default. [#4616]

This by no means resolves the issue, just mentioned it because the parameter `WCSHDO_P14` is important (at least for that bugifx).

**Comment by bsipocz** [comment]
@nden - In order to close this issue, could you please add a comment to the changelog for the minimum wcslib requirement we have for 2.0, in case there was a change? 

The latest entry about the minimum required version was done in 1.1 saying that it's either 4.24+ or 5.8.

**Comment by nden** [comment]
@bsipocz The latest wcslib included in astropy 2.0 does not require changing the minimum wcslib version. However, I am not sure what the correct requirement before that was. It looks like, based on this issue, that the correct minimum requirement should be wcslib 5.14.

**Comment by bsipocz** [comment]
@eteq - shall we state somewhere that 5.14 is required and 4.x is not supported any more?

**Comment by olebole** [comment]
Since our "stable" version (Stretch, which would be the primary target for backports) has 5.16, and we even have a backportof 5.16 to "oldstable" = Jessie, I would be fine with that (speaking however just for Debian).

**Comment by bsipocz** [comment]
Added 5.14 as minimum version, directly to the changelog, so closing this now.
