### ISSUE TITLE
iterable SkyCoord objects

### ISSUE THREAD

**Issue by nden** [astropy/astropy#5481]
I expect a SkyCoord object of a single location to fail the `isiterable` test:

```
s = coord.SkyCoord(1, 2, unit=(u.deg, u.deg))
s.isscalar
Out[106]: True

utils.isiterable(s)
Out[107]: True

it = iter(s)
next(it)
...
TypeError: scalar 'UnitSphericalRepresentation' object is not subscriptable.

```
It works correctly with SkyCoord object of arrays of locations.
It also works correctly with Quantity objects.

**Comment by mhvk** [comment]
Indeed, that's a bug: it should define a `__iter__` method. I think this can be done quite nicely as part of `ShapedLikeNDArray`, which means some code in `Time` can be removed...  PR in progress...

**Comment by mhvk** [comment]
For a fix, see #5482. It is nice in that it just generalizes what `Time` did already to all classes using `ShapedLikeNDArray`. One issue is that because that has been introduced for 1.3, any backport to 1.0 will have to be done independently. My own sense would be not to bother...

**Comment by mhvk** [comment]
#5482 should have fixed this, so closing!

**Comment by nden** [comment]
@mhvk Thanks.

**Comment by dobos** [comment]
As of version 5.2.2, `isinstance(SkyCoord(10, 10, unit=u.degree), Iterable)` still evaluates to `True`, yet implements no ˙__iter__` nor `__len__`.

**Comment by pllim** [comment]
The original post used `astropy.utils.isiterable`. The original problem is not a problem any longer. You are comparing to `collections.abc.Iterable`. Please open a new issue, @dobos . Thank you!
