### ISSUE TITLE
Is ``zscale.zscale`` private

### ISSUE THREAD

**Issue by montefra** [astropy/astropy#5499]
Hallo,

I am updating a library I maintain with some collegues and I'm deprecating our copy of zscale in favour of the astropy one.

The official documentation talks only about the [``ZScaleInterval``](http://docs.astropy.org/en/stable/api/astropy.visualization.ZScaleInterval.html) class.
Upon inspection I see that the class does little more than calling ``astropy.visualization.zscale.zscale`` function (except for the extra ``__call__`` method from the base class.)

Is the ``zscale`` function implementation to be considered as private? Is this why it is missing from the documentation?

**Comment by saimn** [comment]
Indeed, it is not private (you can already import it from `astropy.visualization.zscale`), but the function is not imported in `astropy.visualization`. So it does not appear in the docs, and I think it is an oversight. There is no reason why it should not be used directly instead if the higher level interval classes.

**Comment by montefra** [comment]
>  it is not private (you can already import it from astropy.visualization.zscale)

in python there is nothing really private. It's matter of convention and, in part, how you document the code.

Do you want me to do a PR to import zscale into the ``astropy.visualisation`` module?

**Comment by saimn** [comment]
> Do you want me to do a PR to import zscale into the astropy.visualisation module?

👍 for me, but we should ask to @larrybradley or @astrofrog

**Comment by larrybradley** [comment]
Is there any reason you want to use `astropy.visualization.zscale.zscale` over `astropy.visualization.ZScaleInterval`?  They do the same exact thing.  And if you want to use it directly, you can always import it:  `from astropy.visualization.zscale import zscale`.

I think the only reason they are separate is because the `zscale.py` module is under a different license.  If that weren't the case, the `zscale.zscale` code would all be within the `ZScaleInterval` class.

@astrofrog?

**Comment by astrofrog** [comment]
@larrybradley - the license is not important since I think it's also BSD? However, I'd like to avoid having two ways to call the same function if possible, so would also like to understand why ZScaleInterval is not sufficient?

**Comment by larrybradley** [comment]
@astrofrog  If there's no restriction because of the license, then I'll create a PR to simply put the `zscale.zscale` code in `ZScaleInterval`.  I completely agree that we shouldn't have a separate function and class that does the same thing.

**Comment by pllim** [comment]
FWIW, `zscale` is a lot easier to type than `ZScaleInterval` :sweat_smile:

**Comment by astrofrog** [comment]
@larrybradley - if the license was not compatible, we wouldn't be able to include in astropy. Note that if you do move the code into ZScaleInterval then you should still put the note about the original license inside that class.

@pllim - true, but I think we need to make sure we encourage consistency here

**Comment by larrybradley** [comment]
@pllim We had that discussion back when the `visualization` subpackage was created and it won out over the shorter name`viz`.   😃

**Comment by nden** [comment]
If this helps, the original license on zscale was BSD. Not sure why numdisplay has its licence on that file.

**Comment by larrybradley** [comment]
Thanks, @nden.  I'll remove the numdisplay license too.  PR in progress....

**Comment by astrofrog** [comment]
Note that BSD still requires that you acknowledge the original copyright of the code i think, so don't remove it completely.

**Comment by larrybradley** [comment]
OK.

**Comment by saimn** [comment]
About the licence, the addition of NUMDISPLAY_LICENSE.rst was based on the Pyfits example, which is also BSD but with a licence file. I think the purpose is only to keep the copyright statement, as Astropy does not include these copyrights in the source code. See #4776 for more details.

**Comment by astrofrog** [comment]
The answer is 'yes', it was private, and the standalone function no longer exists (#5514)

**Comment by montefra** [comment]
@larrybradley, @astrofrog : thank you for clarifying.

I'll act accordingly.
