### ISSUE TITLE
Suggestion: remove bundled py.test version

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5509]
Once https://github.com/astropy/astropy/issues/5277 is fixed, we should seriously consider no longer vendoring py.test with Astropy. As of py.test 3.x, the ``--genscript`` option which we use to make the bundled version is no longer supported, so in the long term we will be stuck with the version we have. This may then cause incompatibilities in future with plugins, and future Python versions.

**Comment by bsipocz** [comment]
👍 on the idea, but we have to be super careful with the removal as per policy most of the affiliates are using the bundled version.

**Comment by Cadair** [comment]
Are there any changes you make to pytest? If not the only change would be a upgrade of pytest version?

**Comment by astrofrog** [comment]
@bsipocz - indeed, we would need to have a phase-out period and a compatibility import

@Cadair - we don't change anything in pytest, but there are a number of issues with 3.x to fix first

**Comment by cdeil** [comment]
I think this is a good idea to remove the bundled `pytest` version from Astropy core.

Packaging has improved a lot, and having it separate will allow affiliated packages to do the pytest 2 -> 3 transition at their own pace.

What's needed here to make progress?
Further discussion on astropy-dev if there's consensus first?

Or if everyone agrees it's a better long-term solution, maybe even a small docs change and "what's new" entry for 1.3 saying that this is the plan and affiliated packages are encouraged to change their setup / imports is possible to get this going?

**Comment by astrofrog** [comment]
I would say to move forward we need to check for objections on the list.

(another package we might want to consider unbundling is six - it's in the conda defaults channel and is also trivial as a pip dependency)

**Comment by Cadair** [comment]
@embray told me that we need bundled six so that `egg_info` works

**Comment by bsipocz** [comment]
What about not worrying much about six in the next 6 month, and then we can remove it for good for v3.0 when we drop py2 support?

**Comment by astrofrog** [comment]
@bsipocz - yeah, good point, we can actually remove ``six`` altogether in less than a year! 🎉

**Comment by Cadair** [comment]
wooo, Python 3 only wooo

**Comment by pllim** [comment]
Until Python 4 anyway :stuck_out_tongue:

**Comment by adrn** [comment]
:+1: to this idea!

@pllim Then we'll have to bundle `twelve`!

**Comment by mhvk** [comment]
#5670 suggests we really need to start going on removing the bundled pytest; was a mailing list message sent? In the meantime, I guess the first priority would be to get the test suite to work with pytest 3.

**Comment by astrofrog** [comment]
I think the first step should actually be for us to stop using the bundled version internally, but keeping it there with a deprecation warning. Then in 2.0 we don't use the bundled py.test, and in the following version we remove it altogether.

**Comment by bsipocz** [comment]
Closing as this was done in #5694
