### ISSUE TITLE
Unit prefixes seem not to be documented

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#5511]
I was hunting for the [binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix) in the units package and could not find them in the docs. I then dug them out of the code: https://github.com/astropy/astropy/blob/master/astropy/units/core.py#L2164 

It seems that none of the prefixes are in the API docs at all?

**Comment by pllim** [comment]
I agree with you. There is a table that states which unit is prefix-enabled or not, but there is no clear documentation on what prefix is actually supported.

**Comment by mhvk** [comment]
Agreed, there should definitely be a little section, probably in `docs/units/standard_units.rst` about prefixes (see http://docs.astropy.org/en/latest/units/standard_units.html; likely best before the section on the dimensionless unit). 

The only actual units binary prefixes are used for are `bit` and `byte` (in `units/astropys.py`). If one wanted this to appear automatically, one would have to adjust the automatic table creation (routines in `units/utils.py`), which is a bit less simple (and arguably overkill).

**Comment by pllim** [comment]
Yeah, auto creation is overkill (and would also require labels to be upgraded to package-expert and effort-medium). :joy:

**Comment by ritwickdsouza** [comment]
Hi, I'm new here. If no one is doing this I will give it a try. What are the things that needs to be mentioned under the section ?

**Comment by mhvk** [comment]
@ritwickdsouza - thanks for offering to help!  Essentially, as noted at the top, currently the documentation does not mention what prefixes are available in general, and specifically not that we support the binary prefixes for bit and byte. See https://github.com/astropy/astropy/issues/5511#issuecomment-263338420 for where I think this should go.

p.s.  We're in the middle of feature freeze, so responses may be a bit slot.

**Comment by ritwickdsouza** [comment]
So I was going through the code and realized that binary_prefixes is just declared and not being used anywhere (See https://github.com/astropy/astropy/blob/master/astropy/units/core.py#L2196), it selects si_prefixes by default.

**Comment by MSeifert04** [comment]
@ritwickdsouza It depends on the system, a short grep returned (besides other occurrences):

- https://github.com/astropy/astropy/blob/master/astropy/units/astrophys.py#L155 
- https://github.com/astropy/astropy/blob/master/astropy/units/cds.py#L42

**Comment by ritwickdsouza** [comment]
@vibhorgupta96 Ahh my bad. I didn't get time to pull request because of finals.

**Comment by pllim** [comment]
Fixed in #5683 and rendered as http://astropy.readthedocs.io/en/latest/units/standard_units.html#prefixes
