### ISSUE TITLE
Value of u.msolMass

### ISSUE THREAD

**Issue by archer81** [astropy/astropy#5517]
Hi! I have a query on this unit. 

I converted it to cgs unit with other units (solMass, M_sun).
![image](https://cloud.githubusercontent.com/assets/4904478/20690265/d31532f8-b60c-11e6-95cc-a2c911350860.png)

As you can see this figure, the difference in numbers does not differ by 10^6.

Could you please check the value of u.msolMass?

**Comment by mhvk** [comment]
`msolMass` would be milli-solar-mass, so the results seem correct. Did you mean `MsolMass`? (I'd recommend not using the prefixes at all in this case...).

**Comment by archer81** [comment]
Oh. I see. 
I realized u.msolMass, u.MsolMass, u.GsolMass, u.PsolMass in units of astropy now. 
![image](https://cloud.githubusercontent.com/assets/4904478/20691431/3c6180de-b614-11e6-85f5-b5647b2285d3.png)

Thanks for your reply.
