### ISSUE TITLE
WCS slicing gives TypeError (used to work)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5522]
@mcara wrote some WCS manipulation codes for me that used to work but are now broken with the latest dev version. Relevant snippets below.

```python
# Shrink the image
data = zoom(data, zoom_factor)

# Adjust WCS

slice_factor = 1 / zoom_factor
old_wcs = wcs.WCS(hdr)  # To account for distortion, add "pf" as 2nd arg

# Supress RuntimeWarning about ignoring cdelt because cd is present.
with warnings.catch_warnings():
    warnings.simplefilter('ignore', RuntimeWarning)
    # Update if cropping
    new_wcs = old_wcs.slice((np.s_[::slice_factor], np.s_[::slice_factor]))
```

```
Traceback (most recent call last):
...
  File ".../stginga/utils.py", line 349, in scale_image
    (np.s_[::slice_factor], np.s_[::slice_factor]))
  File ".../astropy-1.3.dev16480-py3.5-linux-x86_64.egg/astropy/wcs/wcs.py", line 2983, in slice
    nitems = len(builtins.range(self._naxis[wcs_index])[iview])
TypeError: slice indices must be integers or None or have an __index__ method
```

How do I make it work again?

**Comment by MSeifert04** [comment]
> How do I make it work again?

Convince @nden and @astrofrog that #5455 should be merged. 😄

**Comment by astrofrog** [comment]
Seriously though, what is wrong with simply requiring:

```
slice_factor = int(1 / zoom_factor)
```

? @pllim - does that solve your issue?

More often than not, floating point indices are bugs/unintended. Numpy are even phasing those out and being strict about them. Why should we go in the opposite direction?

**Comment by MSeifert04** [comment]
For any `zoom_factor >= 1` the ``int(1 / zoom_factor)`` will be 0 and thus leave an "empty" wcs.

**Comment by astrofrog** [comment]
@MSeifert04 I agree but in that case, what does slicing with slice e.g. ``slice(None, None, 0.3)`` mean?

**Comment by astrofrog** [comment]
(since @pllim wrote ``# Shrink the image`` I am assuming zoom_factor is < 1 in her use case)

**Comment by pllim** [comment]
Yes, for my case, using `int(1 / zoom_factor)` seems to work. I cannot comment on `zoom_factor > 1`. I just use the code written by someone else as-is. I'm glad the fix for my case in simple. Thanks!

**Comment by pllim** [comment]
Although... it might not be accurate but should not be a problem for my use case.

```python
>>> 1 / 0.22
4.545
>>> int(1 / 0.22)
4
```

**Comment by MSeifert04** [comment]
@astrofrog I think that's another case of WCS without image and WCS with image. If you zoom _with interpolation_ the new points might be floating point indices of the original array (not sure if `scipy.ndimage.zoom` qualifies) and the value of that index is calculated by interpolation. If you now slice the `WCS` with integers you'll truncate the real index and loose accuracy.

**Comment by astrofrog** [comment]
@MSeifert04 - thanks for the clarification - let's discuss this further in https://github.com/astropy/astropy/pull/5455. I'm open to the idea of allowing floating point slicing **but** I think we need to have a separate class for WCS and WCS + NAXIS given the very different behaviors (see latest comment in #5455)

**Comment by MSeifert04** [comment]
I think #5455 should be merged (not necessarily as-is) just to remain backwards-compatible, so better to discuss this in #5461?
