### ISSUE TITLE
Update extern js modules

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#5523]
I'm looking into to see what's worth updating in the extern module. In #4334 @saimn pointed out that dataTables 1.10.9 is not the latest, and since then v1.10.12 is out, too.
Similarly jquery has 1.12.3 instead of 1.11.3, but more importantly there is also the 2.x release family that removes some compatibility hack for older IEs. 

Tests pass locally for both version combinations, but since my js experience is rather limited I'm opening this issue before any PRs to see the opinions about this. The diff are rather significant, ~20K lines, so probably leaving everything as is the best approach.

cc people who were involved in the previous PRs @saimn @astrofrog @taldcroft @eteq

**Comment by saimn** [comment]
👍 to update these libs, however the tests can just test that the expected HTML code has been generated, it cannot test if it is working correctly. So some functional tests should be done manually ;-)
Looking at the [release notes](https://cdn.datatables.net/1.10.10/), the only thing that worries me is the "reworking on the CommonJS and AMD loaders" which are used to get dataTable loaded in the notebook. Do you have a branch that can be tested ?
And about jQuery, there is even a 3.x version !

**Comment by bsipocz** [comment]
Yes, I've a WIP branch, will clean it up tomorrow and ping you. Good to know about the 3.x, it isn't yet listed on the [download page](https://datatables.net/download/index) of dataTables from where I got the updates.

**Comment by bsipocz** [comment]
@saimn - Probably it's too late to get this to 1.3, but anyway the branches with the updates are these:

jquery 3.1.1 and datatables 1.10.12:
   https://github.com/bsipocz/astropy/tree/extern_update_js_3.1.1

jquery 2.2.3 and datatables 1.10.12
  https://github.com/bsipocz/astropy/tree/extern_update_js_2.2.3

**Comment by saimn** [comment]
@bsipocz - I have tested the branch with jQuery 3.1.1 and didn't find any issue (except one unrelated, #5562). Note that jQuery is used only in `show_in_browser` as the notebook already embed its own version. And using jQuery 3 instead of 2 should be fine as I don't think we need to support old versions of Internet Explorer ...
