### ISSUE TITLE
Where is the lab coat?!

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5524]
I don't see it listed at http://astropy.logosoftwear.com/ anymore. :sob: 

p.s. Is this the right repo to file merchandise issues?

**Comment by perrygreenfield** [comment]
I suspect that they somehow eliminated the particular lab coat that I selected. They do still seem to have lab coats as choices in general so I'll have to update that.

**Comment by pllim** [comment]
Still no lab coat listed. I give up. Closing this to make @bsipocz happy.

**Comment by bsipocz** [comment]
Maybe reopen in the website repo, the merchandise is more part of the astropy project than astropy core, doesn't it?
