### ISSUE TITLE
Check Table MaskedColumn for future change in MaskedArray

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5530]
In numpy 1.13, MaskedArray views will start to share the mask with the item viewed rather than get a new copy (https://github.com/numpy/numpy/pull/5580). In many ways, this is much more logical, and I *think* it should pose no issues for `MaskedColumn`, but we should check. In particular, we should ensure that in any copy, the mask actually does get copied.

**Comment by mhvk** [comment]
See https://github.com/astropy/astropy/issues/2997#issuecomment-264126499 for the types of warnings one may get from numpy while the change in behaviour is still being prepared

**Comment by mhvk** [comment]
Actually, as pointed out by @saimn, there was already an issue for this: #5060. So, I'll close this here.

**Comment by bsipocz** [comment]
Maybe add the ``duplicate`` label, too?

**Comment by mhvk** [comment]
Done.
