### ISSUE TITLE
Dubious year and junk message when accessing horoscope

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#5539]
Sorry, wrong repo. 😅

**Comment by bsipocz** [comment]
I'm afraid you've spoiled it, this feature never meant to be exposed to the issue tracker...

**Comment by MSeifert04** [comment]
I'm sorry.

**Comment by bsipocz** [comment]
I'm just joking, check the date on the log/blame :)

**Comment by MSeifert04** [comment]
Agreed, I should have checked that earlier. 😆

**Comment by astrofrog** [comment]
@MSeifert04 - but um, if the functionality is broken, tell @eteq :)

**Comment by pllim** [comment]
Your horoscope today: There might be doubt and confusion in your work today.
