### ISSUE TITLE
No catalog 'Two Micron All Sky Survey (2MASS) 1' found

### ISSUE THREAD

**Issue by nespinoza** [astropy/astropy#5546]
Hi,

 So, I'm using Astropy 1.2.1, and I'm getting this error when trying to do a conesearch using 2MASS. I found out that 2MASS is actually not in the list of catalogs (i.e., if I do:

```
from astropy.vo.client import conesearch
conesearch.list_catalogs()
```

2MASS is not on the list). Checking the VO daily checks (http://stsdas.stsci.edu/astrolib/vo_databases/) it appears 2MASS is not on the conesearch_good.json list for some reason, which should be the problem...

**Comment by pllim** [comment]
The service you are seeking is down -- http://wfaudata.roe.ac.uk/twomass-dsa/DirectCone?DSACAT=TWOMASS&DSATAB=twomass_psc&ra=0&dec=0&sr=0.01

That is beyond the control of Astropy or STScI. You will need to contact the external service provider directly.

**Comment by bsipocz** [comment]
@nespinoza - Have you considered using astroquery for querying 2MASS? You can do it actually with a few different modules, I think I would suggest trying irsa first (http://astroquery.readthedocs.io/en/latest/irsa/irsa.html). There are a few examples on the docs page about it.

Other modules that has access to 2mass includes: ibe, vizier, skyview, and possibly others.

**Comment by nespinoza** [comment]
@bsipocz: great idea. I actually changed that part of my code to work now with IRSA directly for querying 2MASS and works like a charm. Thanks for the suggestion!

**Comment by pllim** [comment]
Hmm. I wonder if Cone Search is superseded by one of those affiliated packages. If so, maybe we can consider "retiring" it?

**Comment by bsipocz** [comment]
@pllim - I never used conesearch. Does it give access to only that 7 catalogues listed at the docs page? 

Are you also behind hosting the catalogues at STScI, or it's totally independent and should be treated as any other upstream catalogue service dependency? If the latter, then probably it's a good idea to start a discussion deprecating things and pointing people towards astroquery.

cc @keflavich

**Comment by pllim** [comment]
> Does it give access to only that 7 catalogues listed at the docs page?

Not *only*, as everything is configurable in the package. By default, yes but the list itself can change day by day depending on availability. A short explanation available at http://docs.astropy.org/en/latest/vo/conesearch/index.html#default-cone-search-services .

> Are you also behind hosting the catalogues at STScI

I manage the list, but I have no control over the actual service providers. The original idea is to have a stable list of services vetted to be reliable but that proves hard to do in real life.

I am definitely interested in more discussion but this seems to be going off-topic here, so let's discuss that somewhere else. I'll open a new issue shortly.

**Comment by pllim** [comment]
See #5558 for the discussion not related to the original issue.

And since @nespinoza found an alternative, and there is nothing I can do in regards of the service outage, I am closing this issue.
