### ISSUE TITLE
WCSAxes images missing

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5549]
The WCSAxes docs are missing the generated images:

http://docs.astropy.org/en/latest/visualization/wcsaxes/index.html

Haven't had a chance to look into it (won't have time before Monday)

**Comment by tanayag** [comment]
Hi! I am new to astropy, and I wanna contribute, 
I am up to this issue, should I add the generated code images to source code or what?
can you guide me?

**Comment by astrofrog** [comment]
This seems to be working now, so closing this.

@tanayag - sorry, looks like there is nothing to do here :)
