### ISSUE TITLE
QTable mixin columns formatting

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#5566]
Changing the format of a `QTable` `Quantity` mixin column results in the unit being displayed in the column output.  Example:

```
from astropy.table import QTable
import astropy.units as u

t = QTable()
t['a'] = np.arange(1, 5) * np.pi * u.km
t['a'].info.format = '0.3f'
print(t)
    a    
    km   
---------
 3.142 km
 6.283 km
 9.425 km
12.566 km
```

The column is still correctly a `Quantity` array:
```
print(t['a'])
[  3.14159265   6.28318531   9.42477796  12.56637061] km
```

so this appears to be an issue only in table output representation.  Is this a bug or am I doing something wrong?

cc: @taldcroft

**Comment by larrybradley** [comment]
Sorry, it looks like this is already fixed in master.

**Comment by awa5114** [comment]
Please see my related issue: https://github.com/astropy/astropy/issues/9853
