### ISSUE TITLE
Change make_lupton_rgb narrative docs to not use reproject

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#5570]
As @parejkoj, @astrofrog and I discussed #5535 in and later out-of-band, a better approach for the narrative docs in #5535 might be to:

- [x] Add the reprojected files to data.astropy.org
- [x] Have the test download those, and not use reproject at all
- [x] Un-skip it in the doctest
- [ ] Write an astropy tutorial that demonstrates the combination of `SkyCoord`, `astroquery`, `reproject`, and `make_luptin_rgb` to actually do the whole thing.
- [ ] Link to that tutorial from the docs

That will keep the example in `astropy.visualization` focused on `make_lupton_rgb` while still showing a whole worked example for a real practical use case.

**Comment by parejkoj** [comment]
I'm not sure I have time to get to this during the rest of this week, particularly the full SkyCoord+astroquery+reproject tutorial. The current version of the docs I wrote assumes the user has downloaded the files separately, with links to the files, but shows them the rest of the steps, so it's most of the necessary steps, I think. I'm not sure where SkyCoord comes into it.

I'd be happy to help someone redo the worked example in the lupton_rgb docs.

**Comment by eteq** [comment]
@parejkoj because this is docs-only it's not especially urgent until the actual release (which is *next* friday).  I'd say if you think you (or someone else) can, do the first 3 for the 1.3 release, and then the tutorial can be done later as time allows?

**Comment by bsipocz** [comment]
Closing this as the docs changes were already made. For the tutorials part see astropy/astropy-tutorials#119
