### ISSUE TITLE
I've written a new useful representation

### ISSUE THREAD

**Issue by Joshuaalbert** [astropy/astropy#5577]
Hello,

I've created an East North Up (ENU) representation that may be useful to others. 
Do you want to incorporate it?

**Comment by taldcroft** [comment]
Can you give a bit more detailed description?  Do you have this already as working code in astropy?  If so I would suggest making a PR so we can look at the code.

**Comment by adrn** [comment]
Closing this, since @Joshuaalbert has an open PR at #5706, so it seems a decision was made!
