### ISSUE TITLE
names vs colnames

### ISSUE THREAD

**Issue by ghost** [astropy/astropy#5579]
Hi, this is a small thing but it always throws me off.  When I initialize a table, as in the example on http://docs.astropy.org/en/stable/table/, 

```
>>> t = Table(rows=data_rows, names=('a', 'b', 'c'), meta={'name': 'first table'},
...           dtype=('i4', 'f8', 'S1'))
```
The columns are named with the parameter 'names'.  But should I want to pull out the column names later, I need to access them using 'colnames',

```
>>> t.colnames
['a', 'b', 'c']
```

Is it possible to make this consistent?

**Comment by mhvk** [comment]
I think I agree in principle, though in practice it would have to be an addition rather than a replacement to maintain backward compatibility, and it is not obvious to me that's worth it. Just in case it jogs memory better, a short-term solution may be to try to use `t.keys()` (which I find easier as it is the same as for `dict`).

**Comment by taldcroft** [comment]
Yes, this could be considered a mistake in the original API.  As @mhvk said we would not take away `colnames` for a very long time, so I would ask to just accept this imperfection.

**Comment by astrofrog** [comment]
Is there any reason why we can't add ``names`` and remove ``colnames`` from the docs but never deprecate it? I mean it's possible to define a new API without deprecating the old one but simply not advertising it.

**Comment by taldcroft** [comment]
I suppose so, but I am slightly leary of leaving unused/undocumented cruft in the API.  People still discover things by introspection or by looking at other code.

**Comment by bsipocz** [comment]
I would suggest to close this as a won't fix. `colnames` is well established, documented and used all over and there was no update to this discussion for 2+ years.

**Comment by taldcroft** [comment]
I agree, closing.
