### ISSUE TITLE
test_mode_pil_image fails for standard PIL

### ISSUE THREAD

**Issue by mirca** [astropy/astropy#5590]
``test_mode_pil_image`` in ``io/fits/tests/test_utils.py`` fails if ``PIL`` comes from http://www.pythonware.com/products/pil/ (which is the version available in conda if one does ``conda install pil``).

The failure is:
```
====================================== FAILURES =======================================
__________________________ TestUtilMode.test_mode_pil_image ___________________________

self = <astropy.io.fits.tests.test_util.TestUtilMode object at 0x1145e75d0>

    @pytest.mark.skipif("not HAS_PIL")
    def test_mode_pil_image(self):
        img = np.random.randint(0, 255, (5, 5, 3)).astype(np.uint8)
        result = Image.fromarray(img)
    
        result.save(self.temp('test_simple.jpg'))
        # PIL doesn't support append mode. So it will allways use binary read.
>       with Image.open(self.temp('test_simple.jpg')) as fileobj:

test_util.py:61: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=5x5 at 0x1143DDFC8>
name = '__exit__'

    def __getattr__(self, name):
        if name == "__array_interface__":
            # numpy array interface support
            new = {}
            shape, typestr = _conv_type_shape(self)
            new['shape'] = shape
            new['typestr'] = typestr
            new['data'] = self.tostring()
            return new
>       raise AttributeError(name)
E       AttributeError: __exit__

/Users/jvmirca/anaconda3/envs/python2.7/lib/python2.7/site-packages/PIL/Image.py:512: AttributeError
```
This seems to occur because  the ``Image`` class does not support context manager.
However, this test is green when ``PIL`` comes from [pillow](https://github.com/python-pillow/Pillow/), because they added support for context manager for ``Image`` here https://github.com/python-pillow/Pillow/pull/551

So, I wonder what can we do, maybe add an entry on [Know Issues](http://docs.astropy.org/en/latest/known_issues.html)? 

P.S.: This failure was reported by @patniharshit on the Astropy's gitter channel.

**Comment by saimn** [comment]
PIL is dead, since a long time (last release in 2009!), and well replaced by Pillow, which is now used in most linux distributions I guess. Here it's in Anaconda which is more surprising,  @patniharshit do you know how you got PIL installed instead of PIllow ?
Anyway, I don't think there is something to do on Astropy's side, especially as Pillow is used only for some unit test.

**Comment by MSeifert04** [comment]
I always thought pillow and pil are the same. 😅

I think the best way would be to update the `HAS_PIL` to test for pillow instead of for PIL directly. Wouldn't it?

**Comment by saimn** [comment]
They are almost the same: Pillow is a fork of PIL, it still uses the PIL namespace and the API is the same. One of the initial goal was the Python 3 compatibility. So I think we can just ignore the old PIL.

**Comment by patniharshit** [comment]
>  @patniharshit do you know how you got PIL installed instead of PIllow ?

@saimn its been a long time, I was trying to set up astropy then but I don't remember much now. I am ok with closing the issue if you feel like that.

**Comment by saimn** [comment]
@patniharshit - Thanks for your feedback! So let's close for now, we can still reconsider if someone else falls in this trap.
