### ISSUE TITLE
Update release instructions based on 1.3 experiences

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#5600]
A note for us to take care of this during/after release (mostly for @astrofrog as the other release maintainer) :

* When doing RCs, the steps about changing the version to ``.dev`` should be skipped (and the changelog entry additions)
* More generally, it might make sense to *not* add changelog sections in the maintenance branch?  Instead just keep track during backports. (need to think about this more - it might be more or less annoying than the current scheme...)
* ``setup.py register`` and ``setup.py upload`` no longer work!  Need to update instructions to do manual registration and upload.  Or switch to using twine (https://pypi.python.org/pypi/twine)

**Comment by astrofrog** [comment]
@eteq - huh, but I've been using register and upload for other packages. I get warnings, but it still works.

**Comment by eteq** [comment]
FYI, turns out upload works but not register.

**Comment by Cadair** [comment]
+1 for twine. It's much more secure.

**Comment by bsipocz** [comment]
@eteq - I did a manual registering but even after that the upload didn't work for the helpers release, so +1 for mentioning twine.

**Comment by bsipocz** [comment]
#5640 and follow-up PRs addressed most of this issue, so I'm closing. We can always improve the release docs after each release...
