### ISSUE TITLE
Flip output of make_rgb_lupton by default

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5611]
At the moment, when using the ``filename`` option of ``make_rgb_lupton``, the PNG/JPEG output files are flipped the wrong way vertically (@cdeil and @parejkoj started discussing this in https://github.com/astropy/astropy/pull/5535#issuecomment-267145197). FITS files are stored with the bottom-left origin pixels first, and other formats typically put the top right origin first. At the moment, if I open PNG/JPEG output in any viewer, the output is flipped compared to the original FITS files in any FITS viewer.

We should fix the default before 1.3 IMO.

**Comment by parejkoj** [comment]
Thanks for making an issue for this. Adding `origin='lower'` works for me for both png and jpeg files, giving a file with the same orientation as ds9.

**Comment by parejkoj** [comment]
If people are happy with this, I'll remake the example images for the docs and what's new page and make a PR for them in astropy-data.
