### ISSUE TITLE
Bug in Table vstack with bytes columns

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5617]
The following example shows that successive calls to vstack increase the length of the string column by 3 bytes each time:

```python
In [1]: from astropy.table import Table, vstack

In [2]: t = Table()

In [3]: t['a'] = [1,2,3]

In [4]: t['b'] = b'hello'

In [5]: t2 = vstack([t,t])

In [6]: t2
Out[6]: 
<Table length=6>
  a     b   
int64 bytes8
----- ------
    1  hello
    2  hello
    3  hello
    1  hello
    2  hello
    3  hello

In [7]: t2 = vstack([t2,t])

In [8]: t2
Out[8]: 
<Table length=9>
  a      b   
int64 bytes11
----- -------
    1   hello
    2   hello
    3   hello
    1   hello
    2   hello
    3   hello
    1   hello
    2   hello
    3   hello

In [9]: t2 = vstack([t2,t])

In [10]: t2
Out[10]: 
<Table length=12>
  a      b   
int64 bytes14
----- -------
    1   hello
    2   hello
    3   hello
    1   hello
    2   hello
    3   hello
    1   hello
    2   hello
    3   hello
    1   hello
    2   hello
    3   hello
```

**Comment by taldcroft** [comment]
Hmm, that's not good.  
cc: @taldcroft (to keep this on my radar)

**Comment by bsipocz** [comment]
I wish @github would introduce the feature that allows us to put issues on todo lists.

**Comment by MSeifert04** [comment]
@bsipocz There are ["Projects"](https://github.com/astropy/astropy/projects) - maybe that could be utilized instead?

**Comment by bsipocz** [comment]
@MSeifert04 - I meant something like a personal todo/wish list, that is a bit less strict than assigning the issue (if assigned it means to me that someone is already working on it or highly expected to work on it).  This list would be private in my mind, and the only purpose is to keep track issues I'm interested in/meant to work on some point, but no promises and I don't mind if someone else gets there first and fixes them. Currently I'm saving such issues in a browser tab collection which is a rather messy business. 
I've raised this feature request, but as always GH didn't say they would do it, and it seems like Tom could use a feature like this, too :)

**Comment by MSeifert04** [comment]
oups, sorry I totally misunderstood you then.

**Comment by taldcroft** [comment]
This looks like an upstream bug in numpy on Python 3:
```
In [24]: np.array([np.bytes_(b'ab')])
Out[24]: 
array([b'ab'], 
      dtype='|S5')

In [25]: np.array([b'ab'])
Out[25]: 
array([b'ab'], 
      dtype='|S2')

In [29]: x = np.array([b'ab'])[0]
In [30]: np.array([x])
Out[30]: 
array([b'ab'], 
      dtype='|S5')
```
While on Python 2 one gets the expected result:
```
In [2]: np.array([np.bytes_(b'ab')])
Out[2]: 
array(['ab'], 
      dtype='|S2')
```
I have a workaround ready.

**Comment by taldcroft** [comment]
See: https://github.com/numpy/numpy/issues/8403
