### ISSUE TITLE
bug in discretize_integrate_2d

### ISSUE THREAD

**Issue by oczoske** [astropy/astropy#5627]
I'm using astropy v.1.2.1 under python 3.4.2.

The function ``astropy.convolution.utils.discretize_integrate_2d`` evaluates the model with x and y inversed. The example below evaluates an elliptical Gaussian with ``mode='oversample'`` and ``mode='integrate'``. As can be seen, ``mode="integrate"``  transposes the model (but not the array). The reason is that ``scipy.integrate.dblquad`` (used in ``discretize_integrate_2d``) takes as its first argument a function where "y must be the first argument and x the second argument.", which is opposite to the call for the astropy model (``Fittable2DModel.__call__``). A possible fix is to replace the first argument of ``dblquad`` with ``lambda y, x: model(x, y)``. 

Reproducible example:

    import matplotlib.pyplot as plt
    from astropy.modeling.models import Gaussian2D
    from astropy.convolution.utils import discretize_model

    model = Gaussian2D(1., 10., 10., 6., 3., 0.)
    gauss_oversample = discretize_model(model, (0, 20), (0, 25), mode="oversample")
    gauss_integrate = discretize_model(model, (0, 20), (0, 25), mode="integrate")
    plt.subplot(121)
    plt.imshow(gauss_oversample, origin='lower', interpolation='none')
    plt.subplot(122)
    plt.imshow(gauss_integrate, origin='lower', interpolation='none') 
    plt.show()

**Comment by pllim** [comment]
Looks like it is still a problem in `dev`:

![figure_1](https://cloud.githubusercontent.com/assets/2090236/21317218/2bc7b0ae-c5d2-11e6-9902-ec73e11739d8.png)

**Comment by adonath** [comment]
@oczoske Thanks! Looks like an obvious bug to me...I'll take a look at #5634 now.
