### ISSUE TITLE
Failures in stats tests with numpy prerelease (1.12)

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#5629]
See https://travis-ci.org/astropy/astropy/jobs/185341963

@crawfordsm @larrybradley @astronomeralex

**Comment by eteq** [comment]
Looking at https://docs.scipy.org/doc/numpy-dev/release.html, I see "MaskedArray takes view of data and mask when slicing" that *might* be the relevant bit?

**Comment by mhvk** [comment]
The first error is definitely a bug in numpy: https://github.com/numpy/numpy/issues/8409

**Comment by mhvk** [comment]
The second error is also due to the same bug: the median of the array of ones is found to be two, with a standard deviation of zero, which means all elements are masked.
However, the code should in principle at least work rather than raise an error; see #5635.

**Comment by mhvk** [comment]
The numpy issue should be once https://github.com/numpy/numpy/pull/8414 is merged.

**Comment by bsipocz** [comment]
This has been long solved.
