### ISSUE TITLE
Update known_configs in astropy.config?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5641]
Looks like we have been forgetting to update:

```python
    # Now determine if it matches the md5sum of a known, unedited
    # config file.
    known_configs = set([
        '7d4b4f1120304b286d71f205975b1286',  # v0.3.2
        '5df7e409425e5bfe7ed041513fda3288',  # v0.3
        '8355f99a01b3bdfd8761ef45d5d8b7e5',  # v0.2
        '4ea5a84de146dc3fcea2a5b93735e634'   # v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5
    ])
```

in astropy.config. Or was this only for old versions before the astropy.config refactoring? I think this is used to replace the astropy config file with a more recent version if there are new config items in a release.

If we're supposed to update this at every release we should add a step in the release instructions.

If we're not supposed to update it anymore then we should clarify the comment in the code.

**Comment by saimn** [comment]
It seems to be only for old versions, given the docstring comment:

>    - An exact match to a "legacy" version of the config file prior to
      Astropy 0.4, when APE3 was implemented and the config file
      contained commented-out values by default.

Since this change, config files have only comments by default, which is checked before checking the md5 sum.

**Comment by pllim** [comment]
Based on what @saimn said above, there is no action required?

**Comment by saimn** [comment]
Yes I think it can be closed.
