### ISSUE TITLE
StreamingHDU issue

### ISSUE THREAD

**Issue by darkstar007** [astropy/astropy#5652]
Hi,

I'm running Debian unstable on 64 bit machines (and hence this is version 1.3 of astropy) and have come across an issue with StreamingHDU  on 2 out of the 3 machines!

This is the test program:

```python
#!/usr/bin/env python

import numpy as np
import astropy.io.fits as fits

n1 = 2048
n2 = 2048
n3 = 50
hdu = fits.PrimaryHDU()
hdr = hdu.header

hdr['NAXIS'] = (3, 'its a movie')
hdr['NAXIS1'] = (n1, 'number of n1 samples')
hdr['NAXIS2'] = (n2, 'number of n2 samples')
hdr['NAXIS3'] = (n3, 'number of frames in movie')
hdr['BITPIX'] = (-32, 'np.float32')

print hdr
shdu = fits.StreamingHDU('test_shdu.fits', hdr)

data = np.zeros((n1, n2), np.float32)

for f in xrange(n3):
    data[:,:] = f
    print 'Doing frame', f, data.nbytes
    shdu.write(data)

shdu.close()
```

On two of the machines, it fails with:

```
Doing frame 25 16777216
Traceback (most recent call last):
  File "./test_stream_fits.py", line 26, in <module>
    shdu.write(data)
  File "/usr/lib/python2.7/dist-packages/astropy/io/fits/hdu/streaming.py", line 174, in write
    raise IOError('Attempt to write more data to the stream than the '
IOError: Attempt to write more data to the stream than the header specified.
```

If I look at the output (using ds9) when the program fails, then every odd numbered frame is filled with zero, and the even frames are 1,2,3,......24. So it seems to be writing an additional empty image out before it writes the actual data. I suspect its incidental, but the two machines it fails on are both Intel, and the one it does work on is AMD.

Any suggestions, or is it a real bug?

Thanks,

Matt

**Comment by pllim** [comment]
Since it does work on one machine but not another, I'll label it as bug for now. What Numpy version are you using? Also, do you see the same problem using Python 3 (if possible)?

c/c @olebole , @embray

**Comment by darkstar007** [comment]
The numpy version is: 1.12.0b1

Running it as python3 works on the AMD and the one Intel machine I currently have running. (Python2 version is 2.7.12, python3 is 3.5.2+).

**Comment by olebole** [comment]
I can confirm this; however I am using Debian Testing and still have there: numpy 1.11.2, astropy 1.2.1, Python 2.7.13rc1. So it is not a regression. Python 3 works for me as well.
The system is an Intel core, 64 bit OS (the "platform-i386" tag may be misleading since it would suggest 32 bit; maybe platform-x86 would be better?)

**Comment by embray** [comment]
This has never really been a well supported or tested feature in the first place.

**Comment by saimn** [comment]
It seems this was the last bug labeled "Python 2", and since it works with Python 3 I guess we can close!
