### ISSUE TITLE
Update milestones?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5663]
Remove 1.2.2 and change 1.3.0 to 1.3.1?

**Comment by bsipocz** [comment]
I think it should rather be: close 1.2.2 and 1.3.0 and 1.0.11 and open new ones, 1.3.1 and 1.0.12, and move all remaining open issues under the released ones.

**Comment by eteq** [comment]
Done - thanks for the ping, @pllim  and @bsipocz !
