### ISSUE TITLE
problems importing astropy.time in astropy 1.3

### ISSUE THREAD

**Issue by mfacorcoran** [astropy/astropy#5676]
When I try to import astropy.time in astropy I get the following error

```
dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/_erfa/_core.so, 2): Symbol not found: _eraEceq06
```

which seems to be a problem with _erfa/_core.so

does anyone else have this problem?  Anyone know how to solve it?  I tried uninstalling and re-installing both erfa and astropy but that didn't help

I'm using mac OS 10.11.6, astropy version 1.3.0; python 2.7, macports 2.3.5

I downgraded to astropy 1.2 (the previous version) and do not have this problem

full import error is below

thanks

Mike

```
In [1]: import astropy.time
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-388419f2a22a> in <module>()
----> 1 import astropy.time

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/time/__init__.py in <module>()
    1 # Licensed under a 3-clause BSD style license - see LICENSE.rst
----> 2 from .formats import *
    3 from .core import *

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/time/formats.py in <module>()
   13
   14 from .. import units as u
---> 15 from .. import _erfa as erfa
   16 from ..extern import six
   17 from ..extern.six.moves import zip

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/_erfa/__init__.py in <module>()
    2 try:
    3     # The ERFA wrappers are not guaranteed available at setup time
----> 4     from .core import *
    5 except ImportError:
    6     if not _ASTROPY_SETUP_:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/_erfa/core.py in <module>()
   41
   42 import numpy
---> 43 from . import _core
   44
   45 # TODO: remove the above variable and the code using it and make_outputs_scalar

ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/_erfa/_core.so, 2): Symbol not found: _eraEceq06
Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/_erfa/_core.so
Expected in: flat namespace
in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/_erfa/_core.so
```

**Comment by pllim** [comment]
Did the compiler throw any warnings or errors when you were re-installing Astropy and ERFA in the problematic setting?

**Comment by mfacorcoran** [comment]
No - No compiler errors

Mike

**Comment by cdeil** [comment]
@mfacorcoran - That was a problem I introduced in Macports when I updated Astropy to 1.3, but forgot to update Erfa to 1.3 (10 days ago, see https://github.com/macports/macports-ports/pull/131). Apologies! It was fixed in https://github.com/macports/macports-ports/pull/133 six days ago.

Can you please try to update, the issue should be resolved now.

I always use these commands:
```
sudo port selfupdate
port outdated
sudo port -p upgrade outdated
```

Also -- Python 3.6 is out and many packages are already available. If you don't have to stick with Python 2.7, give it a try!
:-)
```
sudo port install py36-astropy
```

**Comment by mfacorcoran** [comment]
Thanks Chris that worked!  appreciate the fast response

cheers

Mike

**Comment by cdeil** [comment]
@mfacorcoran - Great. Can you close this GH issue or is there something left to do?

**Comment by mfacorcoran** [comment]
Done!

cheers

Mike
