### ISSUE TITLE
Navigation sidebar missing on latest docs

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#5679]
The Astropy docs always had a navigation sidebar.
When I now go to http://astropy.readthedocs.io/en/latest/index.html it is no longer there and it's hard to navigate around the docs. I haven't checked locally.

Does someone else see the same thing? Was this an intentional change or is it a bug?

cc @bsipocz

**Comment by bsipocz** [comment]
Very weird, I definitely remember it was there 3 days ago when I was pointing to things in the dev guide.

**Comment by bsipocz** [comment]
@cdeil - Building locally I still see the sidebar. Even though it says "passed" maybe something went wrong on RTD. Could you try to wipe and rebuild the latest one?

**Comment by cdeil** [comment]
For reference, the last build for `latest` is this one: http://readthedocs.org/projects/astropy/builds/4871018/

**Comment by cdeil** [comment]
I wiped `latest` just now and started a new build:
https://readthedocs.org/projects/astropy/builds/4872087/

**Comment by cdeil** [comment]
So wiping didn't help. The issue is still present with `latest` and `stable`.

Looking at the source of some old docs: `view-source:http://docs.astropy.org/en/v1.0.2/getting_started.html`
I see that this HTML has been generated:
```
<div class="sphinxsidebar">
        <div class="sphinxsidebarwrapper"><h3>Page Contents</h3>
<ul>
<li><a class="reference internal" href="#">Getting Started with Astropy</a><ul>
<li><a class="reference internal" href="#importing-astropy">Importing Astropy</a></li>
<li><a class="reference internal" href="#getting-started-with-subpackages">Getting started with subpackages</a></li>
<li><a class="reference internal" href="#command-line-utilities">Command-line utilities</a></li>
</ul>
</li>
</ul>
        </div>
      </div>
```

Looking at the HTML of `stable` or `latest`, this content is missing:
`view-source:http://docs.astropy.org/en/stable/getting_started.html`

I'll try to see if I can reproduce the issue locally now.
@astrofrog - Maybe you could try as well?

**Comment by bsipocz** [comment]
Still very weird as the docs for other packages using the same css, js features, and old sphinx are still looking ok (e.g. astroquery was last built 15hrs ago).

**Comment by pllim** [comment]
The timeline mentioned somewhat coincided with me wiping both latest and stable builds (several times in a row) and rebuilding them to investigate the missing PDF/epub documents (before I realized those were disabled on purpose). I didn't change any settings otherwise. In the affiliated package doc still appear good, if you wipe the build several times and rebuild, do you see the same problem?

**Comment by bsipocz** [comment]
@pllim - Wiped and rebuilt for astroquery, but it still works. So the timeline for the regression point may be longer than the one I thought above.

**Comment by cdeil** [comment]
I'll try to reproduce the issue locally now by using conda and making an env with the commands from the log: https://readthedocs.org/projects/astropy/builds/4872087/

**Comment by cdeil** [comment]
I managed to reproduce the issue locally by executing a (slightly modified) version of the commands that are executed on RTD.
```
# To debug this issue: https://github.com/astropy/astropy/issues/5679#issuecomment-271168455
# Commands from https://readthedocs.org/projects/astropy/builds/4872087/
#
# Get a fresh Astropy git clone (or run `git clean -fdx`) and then:
conda env create --name latest --file .rtd-environment.yml
conda install --yes --name latest sphinx==1.3.5 Pygments==2.1.1 docutils==0.12 mock pillow==3.0.0 sphinx_rtd_theme==0.1.7 "alabaster>=0.7,<0.8,!=0.7.5"
python -m pip install -U mkdocs==0.15.0 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext commonmark==0.5.4 recommonmark==0.1.1
conda env update --name latest --file .rtd-environment.yml
git clean -fdx
python setup.py install --force
cd docs
cat conf.py
# This doesn't work locally: sphinx.errors.SphinxError: Builder name readthedocs not registered
# http://docs.readthedocs.io/en/latest/builds.html
# python -m sphinx -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
python -m sphinx -T -E -b html -d _build/doctrees-readthedocs -D language=en . _build/html
#python -m sphinx -T -b json -d _build/doctrees-json -D language=en . _build/json

grep sphinxsidebar _build/html/index.html 
# Not found, bug reproduced.
```

I still don't have a clue what the origin of the problem is.
The last commit at https://github.com/rtfd/readthedocs-sphinx-ext is from June 2016, no recent change there.
Have there been recent changes in Astropy or astropy-helpers on Sphinx-related code?
Does anyone know where the code is that's supposed to generate the `sphinxsidebar`?

I have to go now, but I can try and debug this some more later tonight.

**Comment by bsipocz** [comment]
@cdeil - I think this does the sidebar: ``astropy_helpers/sphinx/themes/bootstrap-astropy/static/sidebar.js``

The helpers definitely wasn't changed since the release around mid Dec.

**Comment by cdeil** [comment]
I think `sidebar.js` is a static file that's only copied over, and it's there:
http://astropy.readthedocs.io/en/latest/_static/sidebar.js

The problem is that the sidebar content isn't filled into the HTML page.

Over at `view-source:http://docs.astropy.org/en/latest/index.html` I saw:
```
</div><generator object macro at 0x7fd0a68c2570>
```

After some more searching around I found https://github.com/sphinx-doc/sphinx/issues/3314 .
So it's a bug in either Jinja or Sphinx (depending on your point of view), that is present with Jinja 2.9.1 or 2.9.2, and will be fixed in the future Jinja 2.9.3 release: https://github.com/pallets/jinja/blob/master/CHANGES

The Sphinx guys downgrade Jinja as a temp workaround: https://github.com/sphinx-doc/sphinx/commit/23d74ddbe6a1f79d15051c70663dbabef628be26

**Comment by cdeil** [comment]
The Jinja patch release will come very soon.
I suggest we just wait a bit, instead of spending time to implement workarounds.

**Comment by cdeil** [comment]
The Jinja issue was introduced in the 2.9 release one day ago, and fixed an hour ago in the 2.9.3 release: https://pypi.python.org/pypi/Jinja2/2.9.3
I'm not sure which Jinja is run on ReadTheDocs, probably one from Anaconda and we'll have to wait a bit until they update to 2.9.3.

**Comment by bsipocz** [comment]
I've triggered building latest and stable, and the sidebars are now back. Thanks for all the investigating @cdeil!

(As a side note I'm not sure why I was allowed to trigger builds, I should not have any permissions on RTD for astropy)

**Comment by bsipocz** [comment]
@cdeil - Apparently RTD reinstall the latest versions of jinja2 and doesn't use the one from conda (where the latest is still 2.8.1)

**Comment by cdeil** [comment]
@bsipocz - Thanks!

I'm closing this issue now.
All OK and nothing left to do.

If someone finds this issue in the future: it's probably because you have `jinja2` version 2.9.0 to 2.9.2. Update to Jinja 2.9.3 or later to fix it. If your package manager doesn't have that, you can `pip install jinja -U` to get the latest stable `jinja2`.

**Comment by pllim** [comment]
@bsipocz , maybe you are part of the `astropy` account on RTD?

**Comment by astrofrog** [comment]
Huh no @bsipocz isn't listed as a maintainer. Interesting!

**Comment by pllim** [comment]
But "astropy" is and I don't know if that is a group account or not.

**Comment by bsipocz** [comment]
@pllim - afaik I'm not part of that group either. There are only 3 projects listed when I log into RTD: astropy4cambridge, astroquery, photutils.

**Comment by pllim** [comment]
Hmm. It is a mystery to me then, but in this case, it works in our favor. :sweat_smile:

**Comment by bsipocz** [comment]
Or do you think that as photutils is listed under astropy, too it somehow inherits some of the access rights? Btw triggering new builds is the only thing I can do, e.g. neither the wipe or admin buttons are shown.

We saw similar inconsistencies before on travis, where I can cancel any builds, not just my own, but cannot restart them. This is true for at least the core and some older affiliates (ccdproc, specutils, etc*), but not newer ones like e.g. astroplan even though it also lives under astropy.

* these are also shown on the left sidebar under "my repositories"
