### ISSUE TITLE
Should wcsaxes import trigger matplotlib.pyplot import?

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#5680]
I see that at the moment
```
python -c 'import astropy.visualization.wcsaxes'
```
triggers a `matplotlib.pyplot` import and a GUI window popping up.

@astrofrog - Is this intentional? Is it possible / wouldn't it be better to avoid this?

What if there's library code or pipeline scripts that wants to import `astropy.visualization.wcsaxes`, but doesn't want to `import matplotlib.pyplot` and all the stuff that entails (like setting a backend and by default popping up a GUI window)?

**Comment by astrofrog** [comment]
@cdeil - I can't reproduce this at the moment (but not saying I don't believe you, my local setup is weird...). There are no pyplot imports in astropy.visualiation.wcsaxes. However we do have other matplotlib imports, which are needed. Which version of Matplotlib are you using?

**Comment by saimn** [comment]
Importing `matplotlib.pyplot` should not open a window unless these is a `plt.figure` call, or maybe with some configuration option ?
But I think there is indeed a `matplotlib.pyplot` import in `astropy.visualization.wcsaxes` with the `pytest.importorskip` call [here](https://github.com/astropy/astropy/blob/master/astropy/visualization/wcsaxes/__init__.py#L6).

**Comment by astrofrog** [comment]
@saimn - ah right maybe that's it, I thought that would only get run if pytest was being run, but I might be wrong. I think we need to fix that so that it only runs during actual testing, or it could probably be changed to just be 'matplotlib'.

**Comment by saimn** [comment]
@astrofrog - Unless I'm missing some pytest magic, I think it is always executed. Which means that if I install astropy 1.3 in a new env without matplotlib, I get a `Skipped` exception from pytest:
```
❯ conda create -n astrotest astropy
❯ source activate astrotest
(astrotest) ❯ python -c 'import astropy.visualization.wcsaxes'
Traceback (most recent call last):
  File "_pytest.runner", line 490, in importorskip
ModuleNotFoundError: No module named 'matplotlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/simon/miniconda3/envs/astrotest/lib/python3.6/site-packages/astropy/visualization/wcsaxes/__init__.py", line 6, in <module>
    pytest.importorskip("matplotlib.pyplot")
  File "_pytest.runner", line 492, in importorskip
  File "_pytest.runner", line 468, in skip
Skipped: could not import 'matplotlib.pyplot'
```
So this statement should be moved to the test files I guess.

**Comment by cdeil** [comment]
> Importing matplotlib.pyplot should not open a window unless these is a plt.figure call, or maybe with some configuration option ?

This is what I use:

```
$ which python
/opt/local/bin/python
$ python --version
Python 3.5.2
$ python -c 'import matplotlib; print(matplotlib.get_backend())'
MacOSX
$ python -c 'import matplotlib; print(matplotlib.__version__)'
2.0.0rc2
```

I think it's always been like that (with Python 2, older MPL versions), that with the default `MacOSX` backend a window pops up when I `import matplotlib.pyplot`. Maybe some other Mac user can confirm or deny?

---

FYI: in Gammapy I just always set the non-interactive `agg` backend:
https://github.com/gammapy/gammapy/blob/1ae81c6b6460a1a4de92ead008e14c91424ed54d/gammapy/conftest.py#L53
Has been working for us for a while without any issue reported.
Not sure if that might be an idea worth discussing for Astropy.

**Comment by cdeil** [comment]
I checked locally and can confirm that @saimn is correct.

If I uncomment this line:
```
pytest.importorskip("matplotlib.pyplot")
```
then
```
python -c 'import astropy.visualization.wcsaxes'
```
no longer makes a MPL GUI window pop up.

**Comment by saimn** [comment]
> I think it's always been like that (with Python 2, older MPL versions), that with the default MacOSX backend a window pops up when I import matplotlib.pyplot. Maybe some other Mac user can confirm or deny?

This is weird, because the window should not even pop up with a `plt.figure` call if you are not in interactive mode (or pylab). In non-interactive mode you have to call `plt.show` to make the window appear.

**Comment by cdeil** [comment]
http://matplotlib.org/faq/usage_faq.html#non-interactive-example

> Nothing happened–or at least nothing has shown up on the screen (unless you are using macosx backend, which is anomalous). 

:-)

**Comment by astrofrog** [comment]
@cdeil - what if you change the statement to:

```python
pytest.importorskip("matplotlib")
```

Any luck then?

**Comment by larrybradley** [comment]
@astrofrog `pytest.importorskip("matplotlib")` seems to fix this.

BTW, I can (semi-)reproduce this issue only if I use a non-conda environment (e.g. pure pip) and the `macosx` backend.  I say "semi-reproduce" because I see the process start, but the window doesn't actually appear.

**Comment by cdeil** [comment]
Yes, changing to
```python
pytest.importorskip("matplotlib")
```
does fix this issue.

I didn't run the whole test suite, just 
```
python -c 'import astropy.visualization.wcsaxes'
```

So is this the only change needed? Should I attach a commit here or will someone else make a PR?

**Comment by cdeil** [comment]
Ah, I see there's #5684 by @astrofrog already. 👍
