### ISSUE TITLE
Improve HTML rendering of table length information

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5685]
Currently, when looking at a Table in a notebook, the ``Table length`` part still looks like a non-HTML representation. It would be nice to include that information without the ``<``/``>`` and maybe e.g. in italics?

<img width="910" alt="screen shot 2017-01-10 at 09 03 11" src="https://cloud.githubusercontent.com/assets/314716/21800086/ec0d81d4-d713-11e6-8b8c-50fac9e4aa61.png">

**Comment by saurvs** [comment]
Hello, I'm new to astropy and I'd like to fix this issue.

**Comment by duncanmmacleod** [comment]
I think this was resolved by #5705.

**Comment by saimn** [comment]
@duncanmmacleod - :+1:
