### ISSUE TITLE
Documentation tests are no longer run by default

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5695]
While trying to get pytest 3.x to work (#5688), I noticed that some of the `rst` files do not pass even with current master (i.e., the built-in pytest). The problem seems to be that currently *none of the doctests* get run. E.g., a recent travis log [1] shows only test files, while older ones also show regular python files with doctests as well as the rst files [2]. So, somehow they are getting omitted... (or am I missing something totally dumb?!?!?)

[1] recent log, no doctests: https://travis-ci.org/astropy/astropy/jobs/191377361
[2] older log, includes doctests: https://travis-ci.org/astropy/astropy/jobs/158108205

**Comment by pllim** [comment]
I would say that merging #5688 would automatically fix this.

**Comment by mhvk** [comment]
Agreed, but I'd still like to understand why the tests were no longer run. Also, ideally we'd ensure this doesn't recur. So cc @bsipocz and @astrofrog.

**Comment by pllim** [comment]
When did we last update the bundled pytest? Did it coincide with doctest disappearing?

**Comment by pllim** [comment]
So... going through all the master builds on Travis, the last time doctest was run was in https://travis-ci.org/astropy/astropy/jobs/190178481 as part of https://travis-ci.org/astropy/astropy/builds/190178474, right before #5678 was merged. I restarted one of the jobs in https://travis-ci.org/astropy/astropy/builds/190406525. If my suspicion is correct, this one will not have doctest.

**Comment by pllim** [comment]
Just as I suspected... https://travis-ci.org/astropy/astropy/jobs/190406534 does not have doctest for the first time. I think the mistake here is introducing pytest 3.x feature in #5678, which is not ready for the transition yet. It was necessary for testing with pytest 3.x locally (at the hack day) but it should not be propagated to master until bundled version is removed. I propose changing `[tool:pytest]` back to `[pytest]` in current master and re-introduce the change in #5688. What do you think?

**Comment by mhvk** [comment]
@pllim - nice tracking down! I agree we need to undo the change in `setup.cfg`.
