### ISSUE TITLE
new_table()

### ISSUE THREAD

**Issue by mhardcastle** [astropy/astropy#5704]
Commit 1c3e876, now in v1.3 removes the deprecated astropy.io.fits.new_table() function. As this breaks legacy code that imports astropy.io.fits as pyfits and does table operations, I'm not convinced this was the right thing to do; but in any case an announcement of this change should surely have gone in the v1.3 changelog?

**Comment by saimn** [comment]
The removal of old Header interface and a few other deprecated functions is listed in [1.3 > API Changes > astropy.io.fits](http://docs.astropy.org/en/latest/changelog.html#id6). `tdump` and `tcreate` are mentioned there, but it seems that I forgot `new_table`, sorry about that.

**Comment by pllim** [comment]
Just for the record, it was removed in #5310. [APE2](https://github.com/astropy/astropy-APEs/blob/master/APE2.rst) describes Astropy's release policy, including removal of deprecated codes.

I thought we also solicited feedback/objection to the removal a while back in Astropy mailing list but I can't seem to find that now.

In regards to updating the changelog, @eteq , what is the policy here? Should it be part of 1.3.1 or 1.3.0 + backporting?

**Comment by pllim** [comment]
@mhardcastle , if you still needs to use the deprecated stuff that is now removed, you can pin Astropy to 1.2.x until you are ready for the transition.

@mhvk, perhaps the discussion about [Collect deprecations for LTS](https://groups.google.com/forum/#!topic/astropy-dev/0ZK3k5EcvvA) should also be extended to removal of deprecated codes?

**Comment by bsipocz** [comment]
@pllim - Erik will elaborate on it, but I think we need to add ``new_table()`` to the list of removed functions in the changelog under section 1.3.0. However there is no way to backport to a release, so it will be released in v1.3.1. 
The mailing list e-mail you were looking for was probably this one: https://groups.google.com/forum/#!topic/astropy-dev/Hoj8mANEc7w

The APE2 says that the deprecation period should be at least one release. However there are nominally 3 releases between LTS releases, my vote would be to follow the APE and remove things more often than LTS. E.g. the ``new_table()`` function was deprecated a while ago in v0.4, 2.5 years ago.

So overall I think it's good to be more flexible about code removal than about the deprecations (the reason there was to ease the compatibility workarounds for affiliates that usually try to support both stable and LTS, and deliberately fail their tests at deprecations).

**Comment by mhardcastle** [comment]
@pllim Sure. In general I am happy to have the latest version of astropy. However, when it breaks something widely used, I expect to be able to see in advance that it's going to be a problem, or if not to easily be able to see the change in the release notes. Saying that end users should be reading the development mailing lists isn't really realistic.

In this case the first I knew about it was that a widely used piece of code, part of the LOFAR tree, broke at a very inconvenient place on two systems simultaneously -- because two separate sysadmins had done a pip upgrade on some other package that pulled in astropy v1.3. The solution to the problem is trivial -- though who knows how long it will take to propagate back into LOFAR releases -- but understanding what had happened would have been much easier with the correct information in the release notes.

**Comment by astrofrog** [comment]
@mhardcastle - just to check, did you see deprecation warnings about that function in previous versions? Normally there should have been deprecation warnings for several versions before it was removed, but if the deprecation warnings weren't working properly, then indeed it wouldn't be fair to just remove it.

**Comment by mhvk** [comment]
@mhardcastle - we were obviously amiss in not having a note about this in the change log -- apologies!

@bsipocz - I think this issue does make me tend to agree with @pllim that perhaps we should move deprecations as much as possible to major version changes. (Now in practice, for the next two that won't matter much, since they are 2.0 and 3.0...) Though really the main thing would be to try to ensure that we only remove features at LTS boundaries (i.e., only add stuff in between).

**Comment by pllim** [comment]
Just for the record, there **was** a deprecation warning. See below (done in Python 2.7 but that should not matter):

```python
>>> import numpy as np
>>> import astropy
>>> from astropy.io import fits
>>> astropy.__version__
u'1.2.1'
>>> a1 = np.array(['NGC1001', 'NGC1002', 'NGC1003'])
>>> a2 = np.array([11.1, 12.3, 15.2])
>>> col1 = fits.Column(name='target', format='20A', array=a1)
>>> col2 = fits.Column(name='V_mag', format='E', array=a2)
>>> cols = fits.ColDefs([col1, col2])
>>> tbhdu = fits.new_table(cols)
WARNING: AstropyDeprecationWarning: The new_table function is deprecated and may
 be removed in a future version.
        Use :meth:`BinTableHDU.from_columns` for new BINARY tables or
:meth:`TableHDU.from_columns` for new ASCII tables instead. [astropy.utils.decorators]
```

**Comment by bsipocz** [comment]
@mhvk - What about API changes then or dropping old numpy support? One could use the same argument to not change API as it may brake legacy code, and that also comes without any warnings. 

That said, either way I'm happy to go ahead, just slightly happier when there is less deprecated stuff in there to tip-toe around for years.

**Comment by mhvk** [comment]
I think in this particular case the problems is actually that we didn't deprecate fast enough -- we should have removed it in 1.0! See https://github.com/astropy/astropy-APEs/pull/20 for what my proposed strategy is.

I do think this implies we should avoid API breaks in between LTS, but I feel a bit less restrained about numpy support (as long as we support a numpy version at least as old as the LTS version).

**Comment by mhvk** [comment]
p.s. Just to get back to the main point here: really, we should have had a note in the release about the removal of `new_table`.

**Comment by saimn** [comment]
For `new_table` there was indeed a deprecation warning since version 0.4 (and it can be replaced directly with `BinTableHDU.from_columns`). It should be added to the changelog (*edit*: thanks for doing it @bsipocz !).

@mhardcastle :
> because two separate sysadmins had done a pip upgrade on some other package that pulled in astropy v1.3

Note that the behavior of pip also changed recently as it now upgrades dependencies by default (https://github.com/pypa/pip/pull/3972). This can lead to some surprises, not only with Astropy (for instance newer Numpy versions will raise an error if you index arrays with floating values).
