### ISSUE TITLE
DOC: mention the astropy (possibly astropy-ci-extras) conda channels in docs

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#5707]
I think we don't yet mention it anywhere that the ``astropy`` conda channel exists and that most affiliated packages are available there. 
We may also want mention that non-default version combinations of astropy can be found in the ``astropy-ci-extras`` channel (this would also close https://github.com/astropy/package-template/issues/94).

cc @mwcraig

**Comment by pllim** [comment]
Maybe also explain the difference of `astropy` and `conda-forge` channels?

**Comment by mwcraig** [comment]
Both suggestions make sense, I think. I'm hoping to (finally) migrate most of the actually building for conda-channel-astropy over to conda-forge over the next month or so. Just found out about this, which should make mirroring quite a bit easier: https://github.com/MaxPoint/conda-mirror

**Comment by bsipocz** [comment]
We mention the conda channel now in the affiliated packages docs: https://www.astropy.org/affiliated/index.html

and we stopped using astropy-ci-extras, so I close this issue.
