### ISSUE TITLE
Numpy prerelease test is not actually running

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5709]
For example, see [this Travis CI job](https://travis-ci.org/astropy/astropy/jobs/192608011) on the recent master test suite that passed.

```
Package plan for installation in environment /home/travis/miniconda/envs/test:

The following packages will be downloaded:

    package                    |            build

    ---------------------------|-----------------

    mkl-2017.0.1               |                0       128.2 MB

    numpy-1.11.3               |           py35_0         6.7 MB

    ------------------------------------------------------------

                                           Total:       134.9 MB

The following NEW packages will be INSTALLED:

    mkl:   2017.0.1-0   

    numpy: 1.11.3-py35_0

DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
```

The last statement is **red** but the test is somehow marked as passed (green).

**Comment by astrofrog** [comment]
I think that the prerelease job doesn't run if there is no prerelease? @bsipocz?

**Comment by bsipocz** [comment]
Yes, prerelease should give a green travis result without running the tests when there is no prerelease available.
I'm about to upgrade the numpy version in ci-helpers once 1.12 is available on conda (it was released a few days ago).

**Comment by pllim** [comment]
Ah, okay. Thanks for the clarifications!
