### ISSUE TITLE
SkyCoord failure to warn with mixed input

### ISSUE THREAD

**Issue by k-gilbert** [astropy/astropy#5716]
When using SkyCoord, if one makes a typo and mixes coordinate input, such as (typo in RA):

```python
In: m31_radec = ['00:42:44.3s +41:16:09']
In: c_m31 = SkyCoord(m31_radec, unit=(u.hourangle, u.deg))
```

SkyCoord happily produces the output:
```python
In: print c_m31
<SkyCoord (ICRS): (ra, dec) in deg
    (0.00019786, 41.26916667)>
```

When it should be:
```python
In: m31_radec = ['00:42:44.3 +41:16:09']
In: c_m31 = SkyCoord(m31_radec, unit=(u.hourangle, u.deg))
In: print c_m31
<SkyCoord (ICRS): (ra, dec) in deg
    (10.68458333, 41.26916667)>
```

cc @eteq

**Comment by mhvk** [comment]
Oddly, `Angle('00:42:44.3s', unit='hourangle')` correctly raises an exception, so this seems `SkyCoord` specific.

**Comment by bsipocz** [comment]
The first example now raises a similar error as the ``Angle`` one in @mhvk's example, so I suggest to close this issue. 
 
```
ValueError: ('Cannot parse first argument data "[\'00:42:44.3s\']" for attribute ra', UnitsError("Can not parse '(0.0, 42, 44.3)' as unit 'arcsec'",))
```

@eteq @adrn @mhvk - Please reopen if you think the ``'00:42:44.3s'`` string should be parsed as a valid one.
