### ISSUE TITLE
Pickle test on constants all set to xfail

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5719]
Looking over #5694, I noticed that `constants.tests.test_pickle` runs tests that are all set to fail. This is mostly a reminder to understand why this is, and whether something needs to be changed.

**Comment by pllim** [comment]
Tracked this to #1947 by @ktchrn

**Comment by mhvk** [comment]
OK, thanks. So, this was set to `xfail` by design just so we could later investigate. Which this issue is then a nice reminder of!

**Comment by stargaser** [comment]
Reported in #9139. I tried un-xfailing the second test and I confirmed that the problem is the same as in that issue. I am inclined to treat this as a missing feature, and milestone it for v4.0.

**Comment by stargaser** [comment]
cc @Juanlu001 who filed #9139

**Comment by pllim** [comment]
Thanks for looking into this, @stargaser !
