### ISSUE TITLE
Validate changelog syntax during CI

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5731]
As discussed in https://github.com/astropy/astropy/issues/4923, we should validate the changelog syntax during the continuous integration (for example checking for extraneous whitespace, or indentation issues). However, I think we should maybe wait until we determine if we are going to use a YAML format first since this will change how the validation is done.

**Comment by bsipocz** [comment]
@astrofrog - Most of the syntax is now checked by astropy-bot. Is that good enough for this, or would you prefer to solve the whitespace checking, too?

**Comment by astrofrog** [comment]
This is fine, we can always add whitespace stuff to the bot if we want.
