### ISSUE TITLE
Bug when accessing table row with numpy scalar array

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5742]
I think the following should work:

```python
In [1]: from astropy.table import Table

In [2]: t = Table()

In [3]: t['a'] = [1,2,3]

In [4]: import numpy as np

In [5]: idx = np.array(1)

In [6]: t[idx]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-7a7507ea0a28> in <module>()
----> 1 t[idx]

/Users/tom/Dropbox/Code/Astropy/astropy/astropy/table/table.py in __getitem__(self, item)
   1209                                              keys=self.groups._keys)
   1210             return out
-> 1211         elif ((isinstance(item, np.ndarray) and len(item) == 0) or
   1212               (isinstance(item, (tuple, list)) and not item)):
   1213             # If item is an empty array/list/tuple then return the table with no rows

TypeError: len() of unsized object
```

We should treat scalar arrays as normal Python scalars here.

**Comment by astrofrog** [comment]
By the way, this came up because ``match_coordinates_sky`` can return scalar arrays when only one coordinate is matched.

**Comment by mhvk** [comment]
easiest probably to replace `len(item) == 0` with `item.size == 0`.

**Comment by Mar-tian** [comment]
Hello, I am new to open source and would like to take a shot at resolving issues in astropy. I have a brief idea about contributing from the astropy docs. Is it fine if I work on this one?

**Comment by astrofrog** [comment]
@Mar-tian - yes, feel free to try and open a pull request to fix this!

**Comment by janga1997** [comment]
@astrofrog I would like to claim this issue, as the previous poster hasn't responded in days. Is it okay?

**Comment by bsipocz** [comment]
@janga1997 - There isn't really a thing of claiming an issue, none of them are reserved for anyone. If there is no open PR for them, then the best approach is to start work on it, and open a PR with a fix.

**Comment by janga1997** [comment]
@bsipocz Working on it right now then.
