### ISSUE TITLE
Windows ascii (and Table) fails on integer data that can't be represented as int32 (but could be as int64)

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#5744]
For example:

```
ascii.read("""num,ra,dec,radius,mag
100000000000000000,32.23222,10.1211,0.8,18.1
2,38.12321,-88.1321,2.2,17.0
""")
```

gives the following warnings:

```
WARNING: OverflowError converting to IntType in column num, reverting to String. [astropy.io.ascii.fastbasic]
WARNING:astropy:OverflowError converting to IntType in column num, reverting to String.
```

However the first line could be easily interpreted as `int64`:

```
ascii.read("""num,ra,dec,radius,mag
100000000000000000,32.23222,10.1211,0.8,18.1
2,38.12321,-88.1321,2.2,17.0
""")['num'].astype(np.int64)
```

Could the default integer type (I know that's a mess on windows) be set to int64?

**Comment by MSeifert04** [comment]
I found the problem when looking into https://github.com/astropy/astroquery/issues/835

**Comment by saimn** [comment]
The code should already use long integers, so I guess you're on a 32 bits system ?

**Comment by MSeifert04** [comment]
no, but windows 64 bit uses 32bit integers almost everywhere 😅

**Comment by saimn** [comment]
Ah fun 😆 
The code could probably be modified to use `long long` and `strtoll`.

**Comment by bsipocz** [comment]
Hah, I've just run into these again in CI: https://github.com/astropy/astroquery/runs/2525021918?check_suite_focus=true

**Comment by orionlee** [comment]
This patch could solve the issue for pure Python code path (`fast_reader=False`):
https://github.com/orionlee/astropy/commit/9d4ba65e9e5b43f3d9f7b7fcfdef63b997861280

Presumably, something similar needs to be done for C code path as well.

**Comment by pllim** [comment]
In 2024, still a problem even on modern 64-bit Windows 11 (x64).

**Comment by orionlee** [comment]
I figured out the necessary changes needed for C code path as well (basically using `long long` as saimn suggested). 

There are two options. I'd like to get some feedback before proceeding further.
1. Make all integers column to be of types `np.int64` by default, the behavior of current astropy on most platforms, but not Windows.
2. Retain current behavior (`np.int64` on most platforms, `np.int32` on Windows), but when large integers are detected due to OverflowError, make the column to be of type `np.int64` . (https://github.com/orionlee/astropy/commit/9d4ba65e9e5b43f3d9f7b7fcfdef63b997861280 implements it for Python code path).

Option 1 would make astropy's default behavior more consistent across platforms.
Option 2 might have an advantage that on a given platform, astropy's default behavior is consistent with that of numpy. Specifically, on Windows, numpy's integer array is by default `np.int32`. Option 2 would keep astropy Table's integer columns to also be `np.int32`, and fallbacks to `np.int64` only when there are large values.

**Comment by pllim** [comment]
> There are two options.

Personally I think consistency is good, so my vote is Option 1. But I would like to hear what others think, e.g., @saimn @mhvk @taldcroft @hamogu @dhomeier et al.

**Comment by orionlee** [comment]
`pandas` use `np.int64` by default on Windows as well (option 1 behavior).

```python
import pandas as pd; from io import StringIO

df = pd.read_csv(StringIO("""num,cadence,mag
100000000000000000,1,13.1
987,2,13.2
"""))
for c in df.columns:  print(c, df[c].dtype)
```
It gives:
```
num int64
cadence int64
mag float64
```

**Comment by pllim** [comment]
Given that we have `to_pandas` and `from_pandas`, that gives a very strong case to go with Option 1. Thanks for checking!

**Comment by eerovaher** [comment]
> `pandas` use `np.int64` by default on Windows as well (option 1 behavior).

Is that always true or does that depend on the `pandas` version?

**Comment by taldcroft** [comment]
I would vote for option 1 to be consistent. One thing to consider is that numpy 2.0 is changing the default int on 64-bit platforms  to be int64. If we wait until astropy requires numpy >= 2.0 then I think we get this for free (meaning any downstream breakages are due to numpy not astropy).

**Comment by mhvk** [comment]
I was going to mention numpy 2.0 as well...  My sense would be to fix it in the first major version that includes support numpy 2.0 (i.e., 6.1), possibly only when numpy 2.0 is used (though I don't know if that's easy in the C version). 

Independently, the discussion suggests we should go ahead and merge #15992 which is an actual bug fix that can be backported to 6.0.4 (the data tells that one should use long and the fix ensures we do not ignore that).

**Comment by orionlee** [comment]
Hmm, it sounds like `numpy` v2 would solve the problem for pure Python code path, but I don't think it solves the C (Cython) code path.

Specifically, in the C parser, it tries to convert the integer values to `long` (32 bits on windows), e.g.,:
https://github.com/astropy/astropy/blob/575eb8c3101757f540de5be385b3e89b3073ef5b/astropy/io/ascii/cparser.pyx#L714

To make it work for 64 integers, it needs to convert to `long long` or `int64_t` instead.

---

For reference, another point where the C code path needs to be changed is to ensure the `numpy` array is also 64 bit integer type (replace `np.int_` with `np.int64`) :

https://github.com/astropy/astropy/blob/575eb8c3101757f540de5be385b3e89b3073ef5b/astropy/io/ascii/cparser.pyx#L676

**Comment by orionlee** [comment]
For pandas use `np.int64` by default on Windows: it is the case for both `v1.5.3` and `v2.1.4` .
