### ISSUE TITLE
Why does Travis build log have misalignment?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5756]
Is it just me or does anyone else see this? The misaligned column is annoying because the test setup gets cut off and I cannot see the full text. I am using Firefox on RHEL6. Also see the same thing using Firefox on Windows 7.

![screenshot-1](https://cloud.githubusercontent.com/assets/2090236/22470300/d39b4f84-e79c-11e6-9303-77213263af36.png)

**Comment by bsipocz** [comment]
@pllim - This should be reported directly to travis, I think astropy has nothing to do with it.

**Comment by bsipocz** [comment]
(btw I see the same for a while now, but in other repos, too.)

**Comment by pllim** [comment]
Okay. Moved this to travis-ci/travis-ci#7245. Thanks for the reply!
