### ISSUE TITLE
fitsdiff reports a difference in number of cards even when keyword is ignored

### ISSUE THREAD

**Issue by sevenslices** [astropy/astropy#5757]
Take the case that two FITS files are identical except for one keyword TEST that is present in foo.fits but not in bar.fits. When fitsdiff is run with TEST in the ignore_keywords list, fitsdiff still exits with an error reporting that the number of header cards is different, even though that extra card contains the header keyword that is to be ignored. I would expect that because TEST is in the ignore_keywords list, it would not be counted in the number of cards either.
```
% fitsdiff -k IRAF-TLM bar.fits foo.fits

 fitsdiff: 1.2.1
 a: bar.fits
 b: foo.fits
 Keyword(s) not to be compared:
  IRAF-TLM
 Maximum number of different data values to be reported: 10
 Data comparison level: 0.0

Primary HDU:

   Headers contain differences:
     Headers have different number of cards:
      a: 81
      b: 82
     Extra keyword 'TEST'   in b: 1
% echo $?
1
```
```
% fitsdiff -k IRAF-TLM,TEST bar.fits foo.fits

 fitsdiff: 1.2.1
 a: bar.fits
 b: foo.fits
 Keyword(s) not to be compared:
  IRAF-TLM TEST
 Maximum number of different data values to be reported: 10
 Data comparison level: 0.0

Primary HDU:

   Headers contain differences:
     Headers have different number of cards:
      a: 81
      b: 82
% echo $?
1
```

**Comment by pllim** [comment]
@SaraOgaz , since you are working on this anyway, FYI.

**Comment by saimn** [comment]
The current behavior seems fine to me: with `--ignore-keywords/-k` you can avoid to compare the *content* of a given card (or a list of cards), but it does not change the number of cards in each header. So I don't think the reported number of cards should be modified. 
Other thoughts on this ?

**Comment by pllim** [comment]
I agree with @saimn , although it is a bit annoying there is no way to ask it to ignore the counts. For instance:
```python
>>> from astropy.io import fits
>>> hdu1 = fits.ImageHDU([0])
>>> hdu2 = fits.ImageHDU([0])
>>> hdu1.header['TEST'] = 1
>>> diff = fits.HDUDiff(hdu1, hdu2, ignore_keywords=['TEST'])
>>> print(diff.report())

 Headers contain differences:
   Headers have different number of cards:
    a: 7
    b: 6

>>> diff.identical  # Even if I don't care about the difference in this case
False
```
However, technically, the report above is correct. Just because you ignored a keyword does not mean the two headers are identical. So to report them as identical would be misleading. If you don't care about the number of cards, you can look into the other `diff` attributes instead of relying on the default report:
```python
>>> diff.diff_headers.diff_keyword_count
(7, 6)
>>> diff.diff_headers.diff_keywords
()
>>> diff.diff_headers.diff_duplicate_keywords
{}
>>> diff.diff_headers.diff_keyword_values
defaultdict(<function astropy.io.fits.diff.<lambda>>, {})
>>> diff.diff_headers.diff_keyword_comments
defaultdict(<function astropy.io.fits.diff.<lambda>>, {})
```
Therefore, I am closing this as "won't fix".
