### ISSUE TITLE
votable providing null string value, zeros getting chopped off

### ISSUE THREAD

**Issue by SaraOgaz** [astropy/astropy#5765]
Hi,

My colleague (@rjavila) has run into what might be a bug with the votable package.. I've tried to track it down but I kind of ended up going in circles..

He's setting up a votable column (actually multiple, but all have the same problem) and adding the values info as follows:

``f160w_mag = tree.Field(myvotable,name='F160W',datatype='double',ucd='phot.mag;em.IR.H',unit='mag',width='6',precision='3')``

``f160w_mag.values = tree.Values(myvotable, f160w_mag,null='-99.000')``

The problem is when he then writes out the votable to an xml file the .000 get's chopped off to .0:

`` <FIELD ID="f160w_mag" datatype="double" name="f160w_mag" precision="3" ucd="phot.mag;em.IR.H" unit="mag" width="6">
    <VALUES null="-99.0"/>``

It seems like it might be an issue of python rounding, assuming it gets converted from string->double->string (not sure if that's happening here)

**Comment by pllim** [comment]
Please provide a full working snippet of the code that can reproduce this problem. Side note: I think `width` needs to be 7, not 6, counting the period.

**Comment by pllim** [comment]
Also, which Astropy version is this?

And just curious, why not use unified I/O in Astropy Table (http://docs.astropy.org/en/stable/io/unified.html)?

**Comment by SaraOgaz** [comment]
@pllim I was going to ask him the same thing tomorrow, :D

**Comment by rjavila** [comment]
Hi all, I'm attaching the code I've been using to generate my VOtables. I'm using astropy version 1.2.1. 

I don't use unified I/O because it doesn't give me what I want. I need to create a VOtable that has all the bells and whistles (usage of UCD, GROUP and VALUES elements, etc) and I can't do that with unified I/O.

About the precision, I had considered the period, but not the negative sign.  


`

from astropy.io.votable import tree
from astropy.io import ascii
import sys
import numpy as np

def make_votables():

    with open('../onlycluster.txt','r') as f1:
        targlist = f1.read()
    targlist = targlist.splitlines()

    for infile in targlist:

        print('Working on {}'.format(infile))
        #Implement catalog reading here
        filepath = '/grp/websites/relics.stsci.edu/private/{}/final_processing/catalogs/IR_detection/{}.cat'.format(infile,infile)
        catalog = ascii.read(filepath,format='sextractor')


        # Create a new VOTable file...
        myvotable = tree.VOTableFile()

        # ...with one resource...
        myresource = tree.Resource()
        myvotable.resources.append(myresource)

        # ... with one table
        datatable = tree.Table(myvotable,nrows=len(catalog),name=infile)
        myresource.tables.append(datatable)


        ID = tree.Field(myvotable,name='ID',datatype='int',ucd='meta.id;meta.main')
        RA = tree.Field(myvotable,name='RA',datatype='double',ucd='pos.eq.ra;meta.main',unit='deg',width='10',precision='6')
        Dec = tree.Field(myvotable,name='Dec',datatype='double',ucd='pos.eq.dec;meta.main',unit='deg',width='10',precision='6')
        f435w_mag = tree.Field(myvotable,name='F435W',datatype='double',ucd='phot.mag;em.opt.B',unit='mag',width='6',precision='3')
        f435w_magerr = tree.Field(myvotable,name='F435W err',datatype='double',ucd='stat.error;phot.mag;em.opt.B',unit='mag',width='6',precision='3')
        f606w_mag = tree.Field(myvotable,name='F606W',datatype='double',ucd='phot.mag;em.opt.V',unit='mag',width='6',precision='3')
        f606w_magerr = tree.Field(myvotable,name='F606W err',datatype='double',ucd='stat.error;phot.mag;em.opt.V',unit='mag',width='6',precision='3')
        f814w_mag = tree.Field(myvotable,name='F814W',datatype='double',ucd='phot.mag;em.opt.I',unit='mag',width='6',precision='3')
        f814w_magerr = tree.Field(myvotable,name='F814W err',datatype='double',ucd='stat.error;phot.mag;em.opt.I',unit='mag',width='6',precision='3')
        f105w_mag = tree.Field(myvotable,name='F105W',datatype='double',ucd='phot.mag;em.opt.Y',unit='mag',width='6',precision='3')
        f105w_magerr = tree.Field(myvotable,name='F105W err',datatype='double',ucd='stat.error;phot.mag;em.opt.Y',unit='mag',width='6',precision='3')
        f125w_mag = tree.Field(myvotable,name='F125W',datatype='double',ucd='phot.mag;em.opt.J',unit='mag',width='6',precision='3')
        f125w_magerr = tree.Field(myvotable,name='F125W err',datatype='double',ucd='stat.error;phot.mag;em.opt.J',unit='mag',width='6',precision='3')
        f140w_mag = tree.Field(myvotable,name='F140W',datatype='double',ucd='phot.mag;em.opt.JH',unit='mag',width='6',precision='3')
        f140w_magerr = tree.Field(myvotable,name='F140W err',datatype='double',ucd='stat.error;phot.mag;em.opt.JH',unit='mag',width='6',precision='3')
        f160w_mag = tree.Field(myvotable,name='F160W',datatype='double',ucd='phot.mag;em.IR.H',unit='mag',width='6',precision='3')
        f160w_magerr = tree.Field(myvotable,name='F160W err',datatype='double',ucd='stat.error;phot.mag;em.IR.H',unit='mag',width='6',precision='3')
        bright_mag = tree.Field(myvotable,name='bright_mag',datatype='double',ucd='phot.mag',unit='mag',width='6',precision='3')
        bright_magerr = tree.Field(myvotable,name='bright_magerr',datatype='double',ucd='stat.error;phot.mag',unit='mag',width='6',precision='3')
        zb = tree.Field(myvotable,name='zb',datatype='double',ucd='src.redshift.phot',width='5',precision='3')

        f435w_mag.values = tree.Values(myvotable,f435w_mag,null='-99.000')
        f606w_mag.values = tree.Values(myvotable,f606w_mag,null='-99.000')
        f814w_mag.values = tree.Values(myvotable,f814w_mag,null='-99.000')
        f105w_mag.values = tree.Values(myvotable,f105w_mag,null='-99.000')
        f125w_mag.values = tree.Values(myvotable,f125w_mag,null='-99.000')
        f140w_mag.values = tree.Values(myvotable,f140w_mag,null='-99.000')
        f160w_mag.values = tree.Values(myvotable,f160w_mag,null='-99.000')
        bright_mag.values = tree.Values(myvotable,bright_mag,null='-99.000')

        datatable.fields.extend([ID,
                                 RA,Dec,
                                 f435w_mag,f435w_magerr,
                                 f606w_mag,f606w_magerr,
                                 f814w_mag,f814w_magerr,
                                 f105w_mag,f105w_magerr,
                                 f125w_mag,f125w_magerr,
                                 f140w_mag,f140w_magerr,
                                 f160w_mag,f160w_magerr,
                                 bright_mag,bright_magerr,
                                 zb])

        datatable.create_arrays(nrows=len(catalog))

        for i in np.arange(len(catalog)):

            datatable.array[i] = (catalog['id'][i],
                                  catalog['RA'][i],
                                  catalog['Dec'][i],
                                  catalog['f435w_mag'][i],
                                  catalog['f435w_magerr'][i],
                                  catalog['f606w_mag'][i],
                                  catalog['f606w_magerr'][i],
                                  catalog['f814w_mag'][i],
                                  catalog['f814w_magerr'][i],
                                  catalog['f105w_mag'][i],
                                  catalog['f105w_magerr'][i],
                                  catalog['f125w_mag'][i],
                                  catalog['f125w_magerr'][i],
                                  catalog['f140w_mag'][i],
                                  catalog['f140w_magerr'][i],
                                  catalog['f160w_mag'][i],
                                  catalog['f160w_magerr'][i],
                                  catalog['bright_mag'][i],
                              catalog['bright_magerr'][i],
                              catalog['zb'][i]
                             )

        #myvotable.to_xml('/grp/websites/relics.stsci.edu/private/avila_testing/20170127/catalogs/abell1763.xml')
        myvotable.to_xml('{}.xml'.format(infile))



`

**Comment by pllim** [comment]
I did a quick test. It appears that even when `NULL` seems truncated, the actual value stored in table (see `<TD>`) is the correct format. Can you please confirm this?

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Produced with astropy.io.votable version 2.0.dev17772
     http://www.astropy.org/ -->
<VOTABLE version="1.2" xmlns="http://www.ivoa.net/xml/VOTable/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ivoa.net/xml/VOTable/v1.2">
 <RESOURCE type="results">
  <TABLE>
   <FIELD ID="F160W" datatype="double" name="F160W" precision="3" ucd="phot.mag;em.IR.H" unit="mag" width="7"/>
   <DATA>
    <TABLEDATA>
     <TR>
      <TD>  0.000</TD>
     </TR>
    </TABLEDATA>
   </DATA>
  </TABLE>
  <TABLE>
   <FIELD ID="F160W" datatype="double" name="F160W" precision="3" ucd="phot.mag;em.IR.H" unit="mag" width="7">
    <VALUES null="-99.0"/>
   </FIELD>
   <DATA>
    <TABLEDATA>
     <TR>
      <TD>-99.000</TD>
     </TR>
    </TABLEDATA>
   </DATA>
  </TABLE>
 </RESOURCE>
</VOTABLE>
```

**Comment by rjavila** [comment]
That is correct, but that is not the problem. The null value has to be exactly as what appears on the data table because in VOtables the comparison is done as a string.  So the xml writer needs to respect what I told it to write.

Roberto


On Feb 3, 2017, at 12:54 PM, P. L. Lim <notifications@github.com<mailto:notifications@github.com>> wrote:


I did a quick test. It appears that even when NULL seems truncated, the actual value stored in table (see <TD>) is the correct format. Can you please confirm this?

<?xml version="1.0" encoding="utf-8"?>

<VOTABLE version="1.2" xmlns="http://www.ivoa.net/xml/VOTable/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ivoa.net/xml/VOTable/v1.2">
 <RESOURCE type="results">
  <TABLE>
   <FIELD ID="F160W" datatype="double" name="F160W" precision="3" ucd="phot.mag;em.IR.H" unit="mag" width="7"/>
   <DATA>
    <TABLEDATA>
     <TR>
      <TD>  0.000</TD>
     </TR>
    </TABLEDATA>
   </DATA>
  </TABLE>
  <TABLE>
   <FIELD ID="F160W" datatype="double" name="F160W" precision="3" ucd="phot.mag;em.IR.H" unit="mag" width="7">
    <VALUES null="-99.0"/>
   </FIELD>
   <DATA>
    <TABLEDATA>
     <TR>
      <TD>-99.000</TD>
     </TR>
    </TABLEDATA>
   </DATA>
  </TABLE>
 </RESOURCE>
</VOTABLE>

**Comment by pllim** [comment]
Just for the record, the data type is set as double, so null is converted to double. It is deliberately done in the code and does not appear to be a bug. @rjavila is going to investigate how the comparison is being done on his side.

**Comment by pllim** [comment]
Offline discussions came to the conclusion that Astropy is not the cause of the bug.
