### ISSUE TITLE
Midpoint RA DEC

### ISSUE THREAD

**Issue by rankinstudio** [astropy/astropy#5766]
This may be covered, but I can't seem to find docs on it. 

Is there a quick way in astropy to calculate the midpoint of two different sets of RA / DEC coordinates? 

This is extremely helpful when you are dealing with fast moving objects in astrometry that streak across the image over a few arc minutes.

Thanks!

**Comment by mhvk** [comment]
@rankinstudio - you need to be a bit careful, since at larger separations the question becomes slightly ill-defined (which is why, e.g., we do not allow substraction or averaging of `SkyCoord`). However, you *can* do arithmetic on the actual representations [1]:
```
In [9]: sc = SkyCoord(ra=np.arange(10.)*u.deg, dec=np.arange(10.)*u.deg)

In [10]: sc.data
Out[10]: 
<UnitSphericalRepresentation (lon, lat) in deg
    [( 0.,  0.), ( 1.,  1.), ( 2.,  2.), ( 3.,  3.), ( 4.,  4.),
     ( 5.,  5.), ( 6.,  6.), ( 7.,  7.), ( 8.,  8.), ( 9.,  9.)]>

In [11]: sc.data.mean()
Out[11]: 
<SphericalRepresentation (lon, lat, distance) in (rad, rad, )
    ( 0.07834183,  0.07863809,  0.99749838)>

In [13]: midpoint = (sc.data[0] + sc.data[1])/2.

In [14]: midpoint
Out[14]: 
<SphericalRepresentation (lon, lat, distance) in (rad, rad, )
    ( 0.00872598,  0.00872698,  0.99992385)>
```

[1] http://docs.astropy.org/en/latest/coordinates/representations.html#vector-arithmetic

**Comment by rankinstudio** [comment]
The separations I'm talking about are for asteroid streaks in images that are on the order of a few arc minutes at most. We've successfully identified artsats by getting start and end point measurements from the streaks with functions in excel for a straight line mid-point. 

Can you show me an example for these two coordinates?

BEGIN1		C2017 01 22.173924 05 28 55.32 +52 26 46
END1		C2017 01 22.173924 05 29 25.49 +52 34 01.3	

Appreciated!

**Comment by mhvk** [comment]
Here's what should work:
```
points = SkyCoord(['05 28 55.32 +52 26 46', '05 29 25.49 +52 34 01.3'], unit=(u.hourangle, u.deg))
points
# <SkyCoord (ICRS): (ra, dec) in deg
#     [( 82.2305    ,  52.44611111), ( 82.35620833,  52.56702778)]>
midpoint = SkyCoord(points.data.mean(), representation='unitspherical', frame=points)
midpoint
# <SkyCoord (ICRS): (ra, dec) in deg
#     ( 82.29326771,  52.50658609)>
# check with horrible points:
points = SkyCoord([1., 359.], [0., 0.], unit='deg')
SkyCoord(points.data.mean(), representation='unitspherical', frame=points)
# <SkyCoord (ICRS): (ra, dec) in deg
#     ( 0.,  0.)>
points = SkyCoord([10., 190.], [89., 89.], unit='deg')
SkyCoord(points.data.mean(), representation='unitspherical', frame=points)
# <SkyCoord (ICRS): (ra, dec) in deg
#     ( 270.,  90.)>
```

**Comment by rankinstudio** [comment]
Thanks!!!

**Comment by pllim** [comment]
Should the doc be expanded? If not, I think we can close this?

**Comment by mhvk** [comment]
I think slightly longer-term, the way to do this would be to calculate the separation and position angle between the two points, and then go halfway using #5727...

Anyway, I'll close this now; @rankinstudio - as always, if you can think of a good way to describe the question and solution in the documentation (i.e., a way that would have helped *you* to figure it out), please do let us know (or even better, make a pull request!).

**Comment by nealmcb** [comment]
Thanks!
For any other `astropy` newbies who run across this, prefix the above code blocks with:

```python
from astropy.coordinates import SkyCoord
from astropy import units as u
```

@mhvk Can you talk some more about how _at larger separations the question becomes slightly ill-defined_?
And for big separations (e.g. 66 degrees in the example I'm looking at), how much difference might it make?

**Comment by mhvk** [comment]
My comment about ill-defined was mostly about exactly what one wants, which was not completely clear. With the suggested procedure, one has a problem only if the points are on opposite sides!

**Comment by eteq** [comment]
Leaving a snippet for those who might stumble upon this via google.  You can now solve this problem like so:
```
pa = sc1.position_angle(sc2)
sep = sc1.separation(sc2)
midpoint_sc = sc1.directional_offset_by(pa, sep/2)
```
