### ISSUE TITLE
Travis states a build failed even when it succeeded???

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5767]
I am getting messages after merging that a build of master failed, only to find that if I look at the log, nominally failed builds seem actually to have succeeded.

E.g., https://travis-ci.org/astropy/astropy/builds/198012568 shows many failures, but, e.g., https://travis-ci.org/astropy/astropy/jobs/198012578 shows that the build did pass all tests.

Any idea what is going on? cc @bsipocz, @astrofrog

**Comment by bsipocz** [comment]
@mhvk - This is very weird. I think we should report it to support@travis-ci.com. Would you send them an e-mail?

**Comment by bsipocz** [comment]
@mhvk - No need to write the e-mail, as I had to follow up on the issues we had yesterday with travis support, so have included this one in there, too.

**Comment by bsipocz** [comment]
I think we can close this here, the xref for the travis issue is this: https://github.com/travis-ci/travis-ci/issues/7264

Support said this:
```
We've started rolling out a new worker v2.6.2 which, unfortunately, seems to be causing this 
mismatch on some `sudo: false` builds like https://travis-ci.org/astropy/astropy/jobs/198012570.

We're rolling back to a previous worker version as quickly as we can, and we'll be posting updates
 on the GitHub issue tracking this situation: https://github.com/travis-ci/travis-ci/issues/7264
```

**Comment by mhvk** [comment]
@bsipocz - thanks for the quick follow-up!
