### ISSUE TITLE
Add GitHub topics to main repo

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#5771]
A new GitHub feature: https://github.com/blog/2309-introducing-topics

**Comment by bsipocz** [comment]
I've though about this, too for affiliates. Would be nice to have a general guideline about the suggested topics, should add the pypi keywords, or come up with something else?

**Comment by Cadair** [comment]
just all the affiliated packages having the 'astropy' topic would be useful.

**Comment by bsipocz** [comment]
@Cadair - I think it may also be useful to have ``astropy-affiliated`` for the affiliated packages, I've added it for astroquery and photutils, (as there are random packages tagged already with astropy).

**Comment by bsipocz** [comment]
Some topic were added at some point, so closing this, more can be added if needed but we don't need to keep this issue open for that
