### ISSUE TITLE
Remove deprecated stuff for v3.0

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5774]
This is a follow-up of

* #5761 -- Completely remove the deprecated "clobber" keyword for v3, as discussed. Users must switch to "overwrite" keyword now.
* #6191 -- Completely remove `analytic_functions` sub-package. Users must switch to modeling for blackbody.
* #6200 -- Completely remove `GaussianAbsorption1D` model. Users can construct such a thing by subtracting `Gaussian1D` from desired continuum model (e.g., `Const1D`).

**Comment by bsipocz** [comment]
@pllim @eteq - What about creating the 3.0 milestone now? There are already a few issues out there that will be relevant for that only, and I think it would be very helpful to milestone the asap to lower the chance of getting lost in the noise of open issues.

**Comment by pllim** [comment]
@bsipocz , looks like @astrofrog added the milestone (thanks, Tom!).

Also, I added "Last-before-release" tags here and in #5773. Is that correct?

**Comment by MSeifert04** [comment]
I would actually vote for removing `clobber` in 4.0 or 3.2. The deprecation is only active for 1 (not-bugfix) release now that it's hidden. I'm not sure but I thought the procedure was 2 (or 3 releases) before a deprecated feature is removed.

**Comment by bsipocz** [comment]
@MSeifert04 - I think it should be fine to remove it in 3.0. 3.0 will have significantly large changes, like the removal of python2, so people should be careful before upgrading to it. Yet anyone wanting to use clobber, they are able to do so for 2 more years on the 2.x LTS.

**Comment by bsipocz** [comment]
@pllim - Thanks for adding the tag. For #5773 it it critical, here it shouldn't matter much.
