### ISSUE TITLE
Deprecate analytic_functions subpackage

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5780]
It is not needed anymore after models support Quantity, as Blackbody will be over at models.

**Comment by cheekujodhpur** [comment]
@pllim What is the update on this? Since I can't find Blackbody in models yet. 

I recently needed to use it, so I am interested in adding it if nobody is working on it.

**Comment by bsipocz** [comment]
@cheekujodhpur - Moving blackbody to modeling is a quite complicated task and one that is being worked on. 
When done, it will be released in 2.0 over the summer. The deprecation of ``analytic_functions`` will happen in the same release, and will be finally removed in 3.0. 
However 2.0 will be a LTS release, so if you need to use blackbody now, I suggest to go ahead and use ``analytic_functions``.

**Comment by cheekujodhpur** [comment]
@bsipocz Is anyone already working on it? I already wrote [this](https://gist.github.com/cheekujodhpur/7fe40a87b6732a0d864ab8146bb8c096) .
I was wondering if it is possible for me to help add it to modeling

**Comment by bsipocz** [comment]
@cheekujodhpur -As I said it's a complicated task, and while I'm not a maintainer of modeling am almost certain that cross using  ``analytical_functions`` is not a suitable solution.

See relevant issues and PRs about it, e.g. #3852 and #4855.

If you are interested in contributing I suggest to start with issues that are labelled as [``package-novice``](https://github.com/astropy/astropy/labels/Package-novice).

**Comment by astrofrog** [comment]
The blackbody function stuff is already taken care of in https://github.com/astropy/astropy/pull/4855

**Comment by pllim** [comment]
As noted above, blackbody model will be a part of an existing PR that incorporates units in models. As for deprecating `analytic_functions`, it is on *my* to-do list when the time is right. I plan to do it in a similar fashion as #5904. So maybe I will just assign to myself.

**Comment by bsipocz** [comment]
@pllim - and for the blackbody deprecation, I would argue that we may indeed need to do a "last before release" approach, as affiliates may actually use it while also supporting LTS.

**Comment by pllim** [comment]
Noted. Thanks!
