### ISSUE TITLE
QTable should pass all Table tests that do not involve masking

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5785]
This implies getting other issues to work, e.g., `vstack` of `Quantity` (#4599)

EDIT: to clarity, the hope is to get all tests on `Table` that do not involve any masking to work on `QTable` as well. This would presumably only imply that quantity columns can do everything that a regular `Column` can (except turning itself into a masked version).

**Comment by taldcroft** [comment]
The issue title is a bit too broad and taken literally can't be done.  A key limitation now is the lack of a masked `Quantity`.  Many of the high-level operations require a functioning masked column to support missing data, so those are out.  Also, it isn't precisely `QTable` but presence of a mixin columns which don't support all `Column`/`MaskedColumn` functionality which is the issue.

So what about renaming this issue "Improve support for Quantity table columns".  This allows for issues that are not strictly the fault of the table package.

Apart from `vstack`, what other issues come up with `Quantity` columns?  I guess one known (and easily fixed) limitation is outputting to FITS.

**Comment by mhvk** [comment]
I now narrowed it down to "pass all tests that do not involve masking". I think that should be do-able.

On `vstack` -- if we abandon masking (i.e., no proper `outer` join), then I think even most mixin columns should just work, as one can already do, e.g., `Time([t1,t2, t3])` and have those concatenated (though I think it is not safe with different locations).

**Comment by taldcroft** [comment]
`Time` and `SkyCoord` objects are not mutable nor expandable in-place, unlike `Column`.  (OK, `SkyCoord` can be updated in place, but it is discouraged and we make it purposely hard).  So there is a large-ish subset of tests that require mutability.

I agree that working to improve mixin column functionality is a high priority, but making a blanket request like "just make everything without masking work" sort of makes the job too big to even want to start.

And again, it has nothing to do with `QTable` per se, but rather mixin columns.  It so happens you cannot use Quantity as a mixin without QTable, but if you only used columns without units then indeed most if not all table tests would pass with QTable.

**Comment by taldcroft** [comment]
Maybe we need a new astropy "project" for "Improve compatibility of Table mixin columns".  Then break it down into manageable bits like addressing specific issues (vstack, outputting to FITS, high-level operations where possible, add QTable to standard set of table_types in testing, etc).

**Comment by mhvk** [comment]
@taldcroft - the goal of this particular issue is not meant to be as big as you think: I'd hope to have all `Table` tests that use regular `Column` to also work on `QTable` that uses `Quanttiy` (and regular `Column` for strings, if needed). I think that is do-able.

Definitely, the real mixin columns are not meant to be part of this -- I shouldn't have brought it up (I was just excited about the possibility to stack tables that way).

**Comment by mhvk** [comment]
For a good start at getting `QTable` to pass all regular `Table` tests, see #5821

**Comment by mhvk** [comment]
#5841 ensured Table and QTable are now equivalent in support for joining, etc., so closing.
