### ISSUE TITLE
Deprecate ambiguous units

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5793]
E.g. emu #4918, possibly there are others; prefixed solar, earth, and jupiter mass in #5661.

This issue is for discussion about ways to deprecate (prefixed) units.  A first possible implementation (#5787), which emitted warnings on importing `units` was deemed too drastic, since the whole point is that most of those units are rarely if ever used.

A suggestion by @pllim was to move deprecated units to a separate module (say, `units.deprecated`. This has the advantage that if code still really needs it, one can imagine being able to do `with u.decprecated.enable()` just like one can do `with u.imperial.enable()`. It might also be possible to not just remove a unit altogether from the `astropy.units` namespace, but first replace it with something that will emit a warning when used but otherwise behaves like the unit. (Perhaps easier would be just to raise an exception, telling what to do to solve it).

**Comment by eteq** [comment]
@mhvk - #5661 amd #5906 are in, so I *think* this can be closed, right?

**Comment by mhvk** [comment]
Yes, I think this is done -- we now have a nice system in place!
