### ISSUE TITLE
SIP warnings issued for legitimate WCS

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#5801]
Due to PR https://github.com/astropy/astropy/pull/4814, now ``astropy.wcs`` issues warnings about inconsistent WCS descriptions when, e.g., ``CTYPEn`` does not contain ``-SIP`` postfix but ``SIP`` header keywords are detected.

However, in some cases, it is OK to have ``CTYPEn`` without ``-SIP`` while ``SIP`` coefficients are present in the header. As an example, in the attached file
[hdr.txt](https://github.com/astropy/astropy/files/770364/hdr.txt) there are two WCSes present: the default one with correct ``CTYPE`` (with ``-SIP``) and an alternative WCS (with "key"='O') that does not have SIP. This is a typical situation with many HST images: the "original" (key: 'O') WCS uses IDCTAB to describe distortion instead of SIP and so its ``CTYPE`` correctly does not contain ``-SIP`` postfix.

When attempting to read this alternate WCS, a long message is displayed even though I know that the alternative WCS that is being loaded does not have SIP.

Here is an example. Try loading WCS with ``key='O'`` from the ``hdr.txt`` file above:
```python
>>> from astropy import wcs
>>> from astropy.io import fits
>>> h = fits.Header.fromtextfile('hdr.txt')
>>> wcs.WCS(h, key='O')
INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 201.8223868  -47.506507390000003  
CRPIX : 420.0  424.5  
CD1_1 CD1_2  : 4.2416960000000003e-06  1.191962e-05  
CD2_1 CD2_2  : 1.1915419999999999e-05  -4.2282270000000001e-06  
NAXIS : 800  800
```

In my opinion the code should detect that a WCS is being loaded from an alternate WCS and suppress this message. However, in other cases it could be that the default WCS is the one that is not supposed to have ``SIP`` but the alternate WCS has SIP. Because the situation related to SIP is so complicated and because there are no "alternate" SIP keywords (such as, e.g.,  ``A_ORDERO``, ``A_ORDERA``, etc.), it is not clear to which of the WCSes in the header do the SIP coefficient belong. For this reason, I think the "info" message introduced in https://github.com/astropy/astropy/pull/5239 should be removed as it is correct only for a subset of cases and in many other cases it is unnecessary.

**Comment by pllim** [comment]
I thought all these were debated over and over again a long time ago. :see_no_evil:

**Comment by nden** [comment]
@pllim Yes, indeed!

@mcara `astropy.wcs` as a general library, it can only detect and warn about inconsistent headers. There's no way to know what the intention was. Telescope/instrument specific implementations should be addressed by the calling software, in this case stwcs. I'm going to close this and we can move the discussion to stwcs.
