### ISSUE TITLE
minversion should return true for a final release if required version is `1.00dev`

### ISSUE THREAD

**Issue by kain88-de** [astropy/astropy#5814]
I'm trying to update the conda-forge package with numpy 1.12, https://github.com/conda-forge/astropy-feedstock/pull/7

This fails because of the function call `minversion('numpy', '1.12dev')`.  There is a type Error in the final comparison. I assume `parse_version` doesn't strip the dev. I would be nice if `minversion` would allow that `minversion('package', '1.00dev')` returns true if the release version of the package is installed.

**Comment by astrofrog** [comment]
In the short term, that comparison should be changed to not have the dev anyway since Numpy 1.12 is out, and in the long term we should also prevent this kind of issue.

**Comment by kain88-de** [comment]
The numpy version is already fixed in master. This would help only in future releases that work check for  numpy 1.13dev before it's released.
