### ISSUE TITLE
Small issues with docstring for sigma_clipped_stats

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5822]
There are a couple of issues with the docs for [sigma_clipped_stats](http://docs.astropy.org/en/stable/api/astropy.stats.sigma_clipped_stats.html#astropy.stats.sigma_clipped_stats):

* The docstring keeps referring to an image but really the function can be used on n-dimensional arrays

* The return values are not median and standard deviation if cenfunc and stdfunc are not median and std

**Comment by larrybradley** [comment]
I updated the docs in https://github.com/astropy/astropy/pull/5834.

Regarding the second point, the return values actually are the median and standard deviation of the sigma-clipped array.  The `cenfunc` and `stdfunc` keywords are used only to determine how the data are sigma clipped.

**Comment by crawfordsm** [comment]
Closing this as it was addressed in the comment and pull request
