### ISSUE TITLE
Multi VO services

### ISSUE THREAD

**Issue by abeelen** [astropy/astropy#5830]
Following the [documentation](http://docs.astropy.org/en/stable/vo/conesearch/client.html), I was trying to use the `~astropy.vo.client.vos_catalog.call_vo_service` routine to make a conesearch on a list of services which are not present in the default cone search services list, namely a bunch of CDS/Vizier cone search services.

Using  `vos_catalog.VOSCatalog` I created a custom database with 3 conesearch services, which I passed to `vos_catalog.call_vo_service`. However, only the first matching service result is returned, instead of the naively expected 3 results. It seems that this is a built-in feature of [call_vo_service]( https://github.com/astropy/astropy/blob/master/astropy/vo/client/vos_catalog.py) [Line 871].

I was wondering if this was a wanted feature or if I could wrap-up a small PR to return a dictionary or a list of `~astropy.Table.table`.

Similarly `~astroquery` returns a custom `~astroquery.utils.commons.TableList` ordered list, but I wonder if the equivalent type exist or will exist in `astropy.table`.

**Comment by pllim** [comment]
@abeelen , the feature you want is documented in that same page, but a little buried towards the end. Look for "*To obtain results from all the services above:*" in the document and you should see something like:

```python
>>> with data.conf.set_temp('remote_timeout', 30):
...     all_gsc_results = conesearch.search_all(c, sr, catalog_db=gsc_cats)
```

If this answers your question, feel free to close the issue. Thank you.

**Comment by abeelen** [comment]
Indeed, thanks @pllim sorry for the disturbance... I guess `call_vo_service` was not the method I wanted... Any reason `call_vo_service` and `conesearch` have different behavior ?

**Comment by pllim** [comment]
@abeelen , `call_vo_service` is intended to be a more general function, applicable to other VO services, not just Cone Search. Originally, there was a plan to add more API to other kind of VO services here but that never came to fruition.
