### ISSUE TITLE
Deleting a Table's row does not work

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#5832]
While looking at #5772 I noticed this:
```python
In [2]: t = Table(data=[[1,2,3],[4,5,6]])

In [3]: t
Out[3]: 
<Table length=3>
 col0  col1
int64 int64
----- -----
    1     4
    2     5
    3     6

In [4]: del t[1]

In [5]: t
Out[5]: 
<Table length=3>
 col0  col1
int64 int64
----- -----
    1     4
    2     5
    3     6
```
So here `del t[1]` does nothing. It should at least raise an exception if this operation is not supported, but I think it makes sense to support the same options as getitem/setitem ? (Which should be easy to do with `remove_row(s)`).

**Comment by taldcroft** [comment]
Ah, good catch.  I think it should be pretty straightforward to implement a `__delitem__` method on Table that calls `remove_row(s)` (depending on the `item` type, e.g. scalar, array, slice).

**Comment by janga1997** [comment]
@saimn I would like to work on this too. But can we finish up on #5772 ? I would really to get it done and dusted and then move on to this issue, since you say its straightforward.

**Comment by saimn** [comment]
@janga1997 - Ok, it makes sense. For #5772 you will need a maintainer's review, maybe @taldcroft ;-)

**Comment by janga1997** [comment]
@saimn One last thing before I get to work on this. 
the operation `del t[idx]` should only work for deleting row(s), and not `del t[1][idx]` removing columns?

And why does `remove_<columns/rows>` doesn't support other iterables like tuple, but only list?
