### ISSUE TITLE
CircleCI removes version number

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#5840]
I'm investigating whether we are also affected by this issue https://github.com/scikit-learn/scikit-learn/issues/8058, and run into the inconvenience that not only circle ci doesn't list the SHA of the master head, but our testing header is also truncate the version number (while e.g. travis doesn't).
I'm leaving this issue here in case anyone fancies to dig into it. 

example from  https://circleci.com/gh/astropy/astropy/866:
```
platform linux2 -- Python 2.7.6, pytest-2.8.3, py-1.4.30, pluggy-0.3.1

Running tests with Astropy version 2.0.dev.
Running tests in lib.linux-i686-2.7/astropy docs.
```

**Comment by firedranzer** [comment]
@bsipocz I this issue still open.

**Comment by bsipocz** [comment]
Yes, it's still an issue, and also the other thing that's mentioned in the scikit-learn thread. To address this, I think you need to dig a bit into the circle ci particulars (that I'm not familiar with) and preferably set it up to run on your fork for debugging.

**Comment by kakirastern** [comment]
@bsipocz Is anyone working on this? If not, can I have a try?

**Comment by bsipocz** [comment]
@kakirastern  - I'm not sure this is still an issue. If you check the latest logs and everything looks fine please let us know to close this issue. (Actually this is the perfect case for issue triaging, finding the ones like this that (most probably) should be closed).

**Comment by kakirastern** [comment]
Yup, will investigate further and make sure it is no longer an issue for us. But it is highly likely to have already been resolved... Will report back soon.

**Comment by kakirastern** [comment]
I checked the log file, the following is an example output from a CIRCLE CI check:

```
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.2.0, py-1.7.0, pluggy-0.8.1

Running tests with Astropy version 3.2.dev23794.
Running tests in astropy docs.

Date: 2019-02-03T21:52:04

Platform: Linux-4.4.0-141-generic-x86_64-with-redhat-5.11-Final

Executable: /opt/python/cp37-cp37m/bin/python

Full Python Version: 
3.7.2 (default, Feb  1 2019, 11:33:59) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.16.1
Scipy: 1.2.0
Matplotlib: not available
h5py: not available
Pandas: not available
Cython: 0.29.4
astropy_helpers: 3.2.dev1093
Using Astropy options: remote_data: none.

rootdir: /tmp/astropy-test-6xq_5s1n/lib/python3.7/site-packages, inifile: setup.cfg
plugins: xdist-1.26.1, remotedata-0.3.1, openfiles-0.3.2, forked-1.0.1, doctestplus-0.2.0, arraydiff-0.3
gw0 [12072] / gw1 [12072] / gw2 [12072] / gw3 [12072]
.................x..x......x..x......................................... [  0%]
...................................................x....x............... [  1%]
........................................................................ [  1%]
........................................................................ [  2%]
...s...........................................xxxxxxx.............x.... [  2%]
.......................x....x..x........................................ [  3%]
........................................................................ [  4%]
........................................................................ [  4%]
........................................................................ [  5%]
........................................................................ [  5%]
```

**Comment by kakirastern** [comment]
So you can see that the version numbers of some dependencies are still not showing on CIRCLE CI checks and is listed as `not available`. 

And, I don't seem to be able to find the SHA of the master head listed anywhere in the same check output. 

So this issue might still need some attention and work.

**Comment by bsipocz** [comment]
@kakirastern - thank you. This all looks good to me, the astropy version is showing as expected. The rest of the test header depends on what individual CI builds install as dependencies.

**Comment by bsipocz** [comment]
(The interest here is only on the 2nd line of the report).

**Comment by kakirastern** [comment]
Thanks, @bsipocz !
