### ISSUE TITLE
Computation of types for columns of Table

### ISSUE THREAD

**Issue by arogozhnikov** [astropy/astropy#5847]
The following behavior looks wrong to me:
```
import numpy
from astropy.table import Table
from astropy import units

t = Table(dict(x=numpy.arange(1, 1000 + 1)))
t['x'].unit = units.second
print t['x'].unit # s
t['y'] = t['x'] / t['x']
print t['y'].unit # prints s, but this is dimensionless
t['z'] = 1 / t['x']
print t['z'].unit # prints s, but this is s^{-1}
```

same operations with scalars work well. Is it a bug?

Astropy == 1.3, mac os x.

**Comment by bsipocz** [comment]
You may want to use ``QTable`` rather than ``Table`` as it handles Quantities as you've expected.

http://docs.astropy.org/en/stable/table/mixin_columns.html#quantity-and-qtable

**Comment by bsipocz** [comment]
I'm closing this issue now, but please feel free to reopen in case you run into issues not covered by the docs.

**Comment by arogozhnikov** [comment]
@bsipocz 
thanks, I've missed this in documentation. Are you going to fix this in future releases, or it will be left for backward compatibility?

Shall I expect worse performance if I always use QTable instead of Table?

**Comment by bsipocz** [comment]
I'm not sure what you mean by fixing it, I'm not aware of plans to deprecate ``Table`` in the near future. 

There are also some features that are doable with Table but not yet with QTable. However, if you're doing these kind of arithmetic and expect the unit of the columns to play along, you should use QTable.
