### ISSUE TITLE
Match catalog frames should use exact catalog frame

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5857]
In #5722 it was noted that the fact that `transform_to` overrides default frame attributes is sometimes problematic. The fix for position angle and separation is in #5762, but there @taldcroft realised that catalog matching would also be affected. It turns out the transformation to the catalog frame is done twice, both in the `SkyCoord.match*` method, and in `matching.py`. So, one has to be chosen and that one should gain a `merge_attributes=False` flag.

Ideally, we still do this for 1.3.1, but not essential, so milestone can be moved if need be.

**Comment by cheekujodhpur** [comment]
Hi, I am interested in working on this. 

In my opinion, we should choose the functions in matching.py to do the transform as they are lower level functions in terms of calling hierarchy.  `SkyCoord.match*` should not have to worry about this.

What do you think? Should I go ahead with this, and we discuss this over a PR?

**Comment by mhvk** [comment]
@cheekujodhpur - great that you are interested! I think the argument against doing it in the function is one of "separation of concerns" - it helps if at the lowest level one is very specific about what is acceptable input, and the function only does one thing. But in this case, since the matching functions are exposed and documented, we cannot change them arbitrarily: so your suggestion is the one to go with.

**Comment by srirajshukla** [comment]
Is this issue still open? Can I work on it?
