### ISSUE TITLE
1.0.x branch is missing from RTD

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#5861]
Looking at the latest RTD builds for astropy it seems that the 1.0.x branch, and the new v1.0.12 is missing. 

cc-ing @pllim @astrofrog as they have access to rtd

**Comment by pllim** [comment]
There are both there now. The log indicated there were built about 6.5 hours ago.

1.0.12
https://readthedocs.org/projects/astropy/builds/5108075/

1.0.x
https://readthedocs.org/projects/astropy/builds/5108074/

**Comment by pllim** [comment]
latest and 1.3.x failed due to remote data problem. I restarted latest, do you want me to rebuild 1.3.x?

**Comment by bsipocz** [comment]
@pllim - Sorry, I should have closed the issue after Erik had sorted my access, off github.
