### ISSUE TITLE
Converting RA/DEC in deg to hms contains min==60 or sec==60

### ISSUE THREAD

**Issue by astrophyzie** [astropy/astropy#5873]
I have a long list of RA/DEC coordinates in degrees that I want to convert to HH:MM:SS, DD:MM:SS using SkyCoord.  When doing this, I found many instances where the MM or SS is equal to 60 seconds, which causes errors further down the pipeline.  How do I ensure this does not happen on the conversion?

Thanks!

**Comment by mhvk** [comment]
Can you give a specific single example? This sounds like a bug, possibly due to rounding...

**Comment by astrophyzie** [comment]
Looked into this further... it was my bug, which was due to rounding!  Thanks!
