### ISSUE TITLE
Astropy Units with pandas

### ISSUE THREAD

**Issue by JWDobken** [astropy/astropy#5876]
Is there a method to pass the Units (`from astropy import units as u`) to a pandas Series or DataFrame?

**Comment by pllim** [comment]
AFAIK, `pandas` is not aware of Astropy units. IMHO this is more of a question for `pandas` developer. But maybe @taldcroft or @mhvk can correct me if I am wrong.

**Comment by taldcroft** [comment]
I don't believe that pandas is unit-aware.  This is a reason you should be using astropy for your end-to-end analysis.  :smile:  And @pllim is correct that this would be a pandas feature request.

**Comment by JWDobken** [comment]
OK thanks for the answer

I send a request to the pandas community:
https://github.com/pandas-dev/pandas/issues/15698

could you help me to get some attention to it?
