### ISSUE TITLE
Behavior of 'fitsopen' for a non-standard FITS file

### ISSUE THREAD

**Issue by mohanagr** [astropy/astropy#5877]
**AstroPy v2.0**
**Test file used** :- `io/fits/tests/data/test0.fits` (Contains 4 Image extensions)
### Background

I was trying to generate a non-standard FITS file to test the compliance fixing fixing of `fitscheck` script. 
which is why I tried to delete a required keyword `EXTEND` from PrimaryHDU. This was not possible because astropy tries hard to not let such a thing happen. This is what I tried :-

```
>>> import astropy.io.fits as pf
>>> hlist = pf.open('./data/test0.fits', mode='update')
>>> del hlist[0].header['EXTEND']
>>> hlist.writeto('./data/test0.fits', output_verify='ignore', overwrite=True)
>>> hlist.close(output_verify='ignore') # Will call fits/cards.py:image
```
and
```
>>> import astropy.io.fits as pf
>>> hlist = pf.open('./data/test0.fits', mode='update')
>>> del hlist[0].header['EXTEND']
>>> hlist.flush(output_verify='ignore') # Will call fits/cards.py:image
```
As mentioned in the comment `fits/cards.py:image` has a hardcoded call to `_Verify.verify` with option to `fix+warn`. Hence I think it is not possible to generate a non-standard file via astropy.

### The Issue
I replaced the `EXTEND` card by a blank using a text editor and opened it again.
```
>>> import astropy.io.fits as pf
>>> hlist = pf.open('./data/test0.fits', mode='update')
>>> hlist[0].header['EXTEND']
True
```
**The original file remains the same.**
-  IMO since it fixes the standard violation while _opening_ but that is not reflected in the actual file, there is no way to know if the original file is actually FITS compliant. 
-  `fitscheck` script checks compliance by _first opening the file_ (when the keyword is already added!) and then checking for compliance. (One of the tests include checking for EXTEND keyword which will obviously return True now). Which is why it too can't detect that EXTEND is missing.

**Comment by mohanagr** [comment]
Someone see to this? I think this is a bug.

**Comment by pllim** [comment]
Personally, I think it is a good thing that `astropy.io.fits` makes it hard for someone to violate the FITS standards and try to fix the obvious violation(s). But I am not familiar enough with the original intention of the behaviors to make any meaningful decision here. This will have to be deferred until we have a proper maintainer for FITS package (or until someone else decides to chime in).

If your intention is to obtain a non-compliant FITS file for testing, I have plenty to give you...

**Comment by MSeifert04** [comment]
I think it's fine that `fits` tries to fix small "inaccuracies". There are lots of small issues with a lot of FITS files and it's annoying to get huge amounts of warnings/verification fails.

**Comment by mohanagr** [comment]
@MSeifert04 @pllim That's the point. They are not fixed silently. The file isn't updated.

**Comment by MSeifert04** [comment]
@mohanagr ok, maybe the issue you posted was too confusing then. What happens when you do what? And how does it differ from what you expected?

**Comment by mohanagr** [comment]
@MSeifert04 I tried to explain the issue in the __issue__ part. When an incorrect file is opened, the missing keyword is added but that isn't reflected in the original file.

**Comment by MSeifert04** [comment]
I got that but what did you expect to happen? I certainly wouldn't expect that the header is modified when I didn't modify it.

**Comment by saimn** [comment]
This `EXTEND` keyword is indeed added to the primary HDU when other HDUs are read (https://github.com/astropy/astropy/blob/master/astropy/io/fits/hdu/hdulist.py#L1164). This may seem unexpected, but as usual with `io.fits` there must be a good reason why it is done. And there are probably other keywords that can be modified to produce a non-compliant file to test the `fitscheck` script. 
Also looking at the standard, `EXTEND` is optional, so removing it should not produce an invalid file !

**Comment by MSeifert04** [comment]
> This may seem unexpected, but as usual with io.fits there must be a good reason why it is done.

optimistic or sarcastic? 😄

**Comment by saimn** [comment]
@MSeifert04 - Just realistic, from my experience there is always a good reason 😉

**Comment by mohanagr** [comment]
@saimn I think EXTEND keyword is mandatory if the FITS file has extensions. (https://archive.stsci.edu/fits/fits_standard/node39.html#SECTION00941000000000000000)

**Comment by saimn** [comment]
@mohanagr - It's an old version of the standard (which may explain why the code enforce the creation of this keyword). With [version 3.0](https://fits.gsfc.nasa.gov/standard30/fits_standard30aa.pdf) this keyword is optional:

> This keyword is only advisory, so its presence with a  value T does not require that the FITS file contains extensions, nor does the absence of this keyword necessarily imply that the file does not contain extensions. Earlier versions of this standard stated that the EXTEND keyword must be present in the primary header if the file contained extensions, but this is no longer required

**Comment by MSeifert04** [comment]
So the verification seems to be testing for pre-3.0 standard (with respect to `EXTEND`)?

**Comment by saimn** [comment]
@MSeifert04 - Not sure what you mean, the header is valid with or without the `EXTEND` card. 
However the code treats `EXTEND` as a mandatory keyword (following the old standard), for instance https://github.com/saimn/astropy/blob/master/astropy/io/fits/hdu/image.py#L1030

**Comment by saimn** [comment]
As discussed above, `EXTEND` is quite a particular keyword (see also #5883), and there is no point in allowing to write a non-standard file. Hence closing.
