### ISSUE TITLE
import astropy.io.fits fails

### ISSUE THREAD

**Issue by gshennessy** [astropy/astropy#5878]
I have a RH 7 machine, which I attempted to install astropy via pip.
The package built and installed, but fails in use.
```
[gsh@lin2v56ad-03 ~]$ python
Python 2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy.io.fits
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/astropy/io/fits/__init__.py", line 70, in <module>
    from . import convenience
  File "/usr/lib64/python2.7/site-packages/astropy/io/fits/convenience.py", line 72, in <module>
    from ...units.format.fits import UnitScaleError
  File "/usr/lib64/python2.7/site-packages/astropy/units/__init__.py", line 20, in <module>
    from . import astrophys
  File "/usr/lib64/python2.7/site-packages/astropy/units/astrophys.py", line 46, in <module>
    def_unit(['lyr', 'lightyear'], (_si.c * si.yr).to(si.m),
  File "/usr/lib64/python2.7/site-packages/astropy/constants/constant.py", line 45, in wrapper
    self.unit.to(inst.unit)
  File "/usr/lib64/python2.7/site-packages/astropy/units/quantity.py", line 787, in unit
    return self._unit
  File "/usr/lib64/python2.7/site-packages/astropy/utils/decorators.py", line 722, in __get__
    val = self.fget(obj)
  File "/usr/lib64/python2.7/site-packages/astropy/constants/constant.py", line 165, in _unit
    return Unit(self._unit_string)
  File "/usr/lib64/python2.7/site-packages/astropy/units/core.py", line 1836, in __call__
    raise ValueError(msg)
ValueError: 'm / (s)' did not parse as unit: local variable 'sig' referenced before assignment
>>> 
```

I have two other RH 7 machines where astropy works correctly. I have not been able to figure out why
one fails, while two work fine.

**Comment by pllim** [comment]
What was your installation/build log? How is your `PYTHONPATH` set on this machine?

**Comment by gshennessy** [comment]
[root@lin2v56ad-03 ~]# pip install  -i https://pypi.org/simple/ astropy
Collecting astropy
  Using cached https://files.pythonhosted.org/packages/35/ea/87856b4e6c3018603830e865f82352c347446127370f61dad29bf0236cd3/astropy-1.3-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: numpy>=1.7.0 in /usr/lib64/python2.7/site-packages (from astropy)
Installing collected packages: astropy
Successfully installed astropy-1.3

**Comment by gshennessy** [comment]
I don't have PYTHONPATH defined

**Comment by pllim** [comment]
It is using a cached download of Astropy, which is not very informational. Try do `pip uninstall astropy` several times until it complains about "package not found" and then do `pip install astropy`.

**Comment by gshennessy** [comment]
I did about a dozen "pip uninstall astropy" but it still grabbed the cached download, which I agree isn't helpful. I downloaded the source of astropy-1.3, and did a build:
[root@lin2v56ad-03 astropy-1.3]# python setup.py build
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    package_info = get_package_info()
  File "/opt/local/src/astropy-1.3/astropy_helpers/astropy_helpers/setup_helpers.py", line 401, in get_package_info
    ext_modules.extend(setuppkg.get_extensions())
  File "astropy/wcs/setup_package.py", line 252, in get_extensions
    generate_c_docstrings()
  File "astropy/wcs/setup_package.py", line 126, in generate_c_docstrings
    from astropy.wcs import docstrings
  File "/opt/local/src/astropy-1.3/astropy/wcs/__init__.py", line 30, in <module>
    from .wcs import *
  File "/opt/local/src/astropy-1.3/astropy/wcs/wcs.py", line 50, in <module>
    from ..io import fits
  File "/opt/local/src/astropy-1.3/astropy/io/fits/__init__.py", line 70, in <module>
    from . import convenience
  File "/opt/local/src/astropy-1.3/astropy/io/fits/convenience.py", line 72, in <module>
    from ...units.format.fits import UnitScaleError
  File "/opt/local/src/astropy-1.3/astropy/units/__init__.py", line 20, in <module>
    from . import astrophys
  File "/opt/local/src/astropy-1.3/astropy/units/astrophys.py", line 46, in <module>
    def_unit(['lyr', 'lightyear'], (_si.c * si.yr).to(si.m),
  File "/opt/local/src/astropy-1.3/astropy/constants/constant.py", line 45, in wrapper
    self.unit.to(inst.unit)
  File "/opt/local/src/astropy-1.3/astropy/units/quantity.py", line 787, in unit
    return self._unit
  File "/opt/local/src/astropy-1.3/astropy/utils/decorators.py", line 722, in __get__
    val = self.fget(obj)
  File "/opt/local/src/astropy-1.3/astropy/constants/constant.py", line 165, in _unit
    return Unit(self._unit_string)
  File "/opt/local/src/astropy-1.3/astropy/units/core.py", line 1836, in __call__
    raise ValueError(msg)
ValueError: 'm / (s)' did not parse as unit: local variable 'sig' referenced before assignment

**Comment by pllim** [comment]
What was the exact URL for your source download? The traceback does look weird. If the source was downloaded from a PyPi website, the person who did the release there need to address this.

**Comment by gshennessy** [comment]
https://pypi.python.org/packages/51/88/c8c4355ff49f40cc538405e86af3395e76a8f9063a19cc5513a7c364d36d/astropy-1.3.tar.gz#md5=bf4c8a033a7085fbc9ec604eebbdbdc5

**Comment by gshennessy** [comment]
Is there a different place that astropy can be downloaded?

**Comment by gshennessy** [comment]
Interestingly the download page also says the file can be downloaded from https://pypi.python.org/packages/source/a/astropy/astropy-1.3.tar.gz, but that gives a file not found error.

**Comment by eteq** [comment]
> Interestingly the download page also says the file can be downloaded from https://pypi.python.org/packages/source/a/astropy/astropy-1.3.tar.gz, but that gives a file not found error.

Thanks for catching that, @gshennessy !  I just fixed it now in pypi - the correct link is now https://pypi.io/packages/source/a/astropy/astropy-1.3.tar.gz due to changes in how PyPI is laid out.

**Comment by eteq** [comment]
@gshennessy - these two look suspicious to me:

> File "astropy/wcs/setup_package.py", line 252, in get_extensions
File "astropy/wcs/setup_package.py", line 126, in generate_c_docstrings

They seem odd because all the other parts of the traceback are ``/opt/local/src/...``, but those two are not.  This makes me wonder if what's happening here is that you have an already-existing install that's causing trouble.

Are you using the system python, or some other python?  If you're using something like conda, the easiest thing to try is to create a completely fresh virtual environment and try it there. Or if you know how to do this, you could try installing conda or just straight-up python (and numpy) and seeing if it builds sucessfully there.  If so, then it's definitely some conflict in the path for the system python.

(Am suggesting these steps because we need to rule out problems unique to that one machine before investigating problems with the uploaded tarball itself.)

**Comment by gshennessy** [comment]
I am using the system python. I am not using conda. I'd really not installing conda, since it isn't approved at my workplace. I'm  trying to build from /usr/local/src, which for disk space reasons is a symbolic link to /opt/local/src. I'm currently pretty sure that there is no other astropy installed,

**Comment by pllim** [comment]
@gshennessy , what do you see when you do the following?
```python
>>> import sys
>>> sys.path
```

**Comment by gshennessy** [comment]
It will take me till Monday to be able to answer this.

**Comment by gshennessy** [comment]
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python2.7/site-packages/d2to1-0.2.12.post1-py2.7.egg', '/usr/lib/python2.7/site-packages/stsci.distutils-0.3.7-py2.7.egg', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/healpy-1.10.3-py2.7-linux-x86_64.egg', '/usr/lib64/python2.7/site-packages/pyds9-1.9.dev0-py2.7-linux-x86_64.egg', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages', '/usr/lib/python2.7/site-packages']

My apologies for being tardy on this.

**Comment by pllim** [comment]
I see a mix of `/usr/lib` and `/usr/lib64`. Is one a symlink of the other? If not, you might have a problem of different versions of Astropy being installed on both and Python getting confused.

Also, do you have write permission to those directories?

**Comment by gshennessy** [comment]
My /usr/lib and /usr/lib64 are not symlinks of another. 

I can elevate privileges to obtain write permission to those directories.

**Comment by bsipocz** [comment]
@gshennessy - Is this install issue has been resolved now? If it's still problematic, you may want to try to switch to use conda environments instead?

**Comment by gshennessy** [comment]
I switched to anaconda python, and have had no problem since then.

**Comment by bsipocz** [comment]
Thanks @gshennessy for confirming. Closing this then.
