### ISSUE TITLE
Backward-incompatible change to astropy.utils.exceptions.AstropyUserWarning?

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#5886]
During a recent test of my astropy-affiliated package against the LTS release, 1.0.12, I got a TypeError related to the number of arguments passed to a helper function used by astropy.utils.exceptions.AstropyUserWarning.

https://travis-ci.org/weaverba137/pydl/jobs/213120916

How can I work around this?

**Comment by MSeifert04** [comment]
That's actually something in `pytest.recwarning` that fails. For the python 3.6 release I replaced the `recwarns` with the `astropy.tests.helper.catch_warnings`-contextmanager. I don't think that's astropy-related.

**Comment by weaverba137** [comment]
Interesting.  It is strange though that this fails only with astropy=LTS.  If it was a change to pytest, why isn't it failing on every version?

**Comment by MSeifert04** [comment]
Does it work with `catch_warnings`? I'm guessing it's because the pytest versions differ:

```
platform linux -- Python 3.6.0 -- py-1.4.30 -- pytest-2.7.3  # failing test
platform linux -- Python 3.6.0, pytest-2.8.3, py-1.4.30, pluggy-0.3.1  # working test
```

However if `catch_warnings` works there is no immediate reason to go into the rabbit hole (of fixing outdated upstream packages).

**Comment by weaverba137** [comment]
Yes, it does.  I've already replaced recwarn with it.  Seems like I was only using recwarn in one place anyway.

**Comment by MSeifert04** [comment]
ok! I'm glad it worked :)
