### ISSUE TITLE
Mention of renaming master to something else

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#5888]
I'm afraid we don't mention it anywhere in our docs that it's good practice to rename the local (user fork) ``master`` to something else like ``placeholder``, ``trailing`` or similar and it leads to confusions with new contributors (e.g. https://github.com/astropy/astropy/pull/5885#issuecomment-287881017).

**Comment by pllim** [comment]
Huh. Pretty sure that in the past, we linked to http://matthew-brett.github.io/pydagogue/gh_delete_master.html to do exactly that, because I have `placeholder` all over the place in my own forks.

**Comment by bsipocz** [comment]
That's a good one. It must have been removed quite a long time ago as I've never seen it but run into this issue of "but my master is up-to-date, oh but you mean astropy/master?" during my first rebase when was told to get rid of it.

**Comment by pllim** [comment]
It was mentioned way back in http://docs.astropy.org/en/v0.3.2/development/workflow/development_workflow.html#deleting-your-master-branch but was removed since then.

**Comment by bsipocz** [comment]
Ahh, I was just about lucky to get my setup before the big rewrite and removal of this recommendation (https://github.com/astropy/astropy/pull/1712#r8596533).

I think it would be nice to have it back, every year with GSoC we got these issues of "master is not astropy/master". Maybe the recommendation of "Never work on master but a feature branch" could be rephrased: "Never work on your placeholder/trailing/hacking branch".

**Comment by bsipocz** [comment]
cc @mwcraig and @eteq as they were involved in the original discussion.

**Comment by mwcraig** [comment]
I'm fine with adding something back in....essentially, we've conducted the experiment of leaving it out and found that it causes problems.

The other mistake I've seen people making is starting to work on their master rather than a branch. Not the end of the world, but not pleasant to fix.

**Comment by bsipocz** [comment]
Yes, they clearly don't ready the docs (as the "never work on master" and "don't use your master for anything" are clearly stated in there).

**Comment by mhvk** [comment]
+1 to putting placeholder back (I also have it for every package and am really glad I do...).
