### ISSUE TITLE
Table indexing cannot be used to update a table

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#5913]
If I have an index on a column, I can use it to retrieve a list of rows with `.loc`, but then it seems there is no way to update the corresponding rows in the source table:
```python
In [1]: %astropy
Numpy 1.12.0
Astropy 2.0.dev18049

In [2]: t = Table([list('abcde'), list(range(5))])

In [3]: t
Out[3]: 
<Table length=5>
col0  col1
str1 int64
---- -----
   a     0
   b     1
   c     2
   d     3
   e     4

In [4]: t.add_index('col0')

In [5]: t.loc[['a', 'c']]
Out[5]: 
<Table length=2>
col0  col1
str1 int64
---- -----
   a     0
   c     2

In [6]: t.loc[['a', 'c']]['col1'] = 10

In [7]: t
Out[7]: 
<Table length=5>
col0  col1
str1 int64
---- -----
   a     0
   b     1
   c     2
   d     3
   e     4
```
I can understand this because it uses Numpy's fancy indexing which makes a copy, but then something that would be useful is a way to get the list of indices of these rows in the source table. It is computed (https://github.com/astropy/astropy/blob/master/astropy/table/index.py#L818) but currently it's not possible to retrieve this. Maybe with a `TableLoc.get_indices` method or something similar ?
ping @taldcroft

**Comment by taldcroft** [comment]
@saimn - sorry, missed this earlier.

Does pandas have an API for doing this kind of thing?  If possible we should re-use their API.

**Comment by taldcroft** [comment]
It should be possible to make a corresponding `__setitem__` that is basically the same code (so most of the current `__getitem__` it would be factored out to a private method), then end with
```
self.table[rows] = value
```

**Comment by taldcroft** [comment]
This is actually pretty easy and most of the effort would be in writing tests and a minor doc update.  Any takers??

**Comment by saimn** [comment]
@taldcroft - But what could be supported with `__setitem__` is to set a list of rows, which is not so practical (i.e. with the example above, `t.loc[['a', 'c']] = [('a',2), ('cc', 10)]` ?) And currently it seems this is not possible even without indexes, `t[[0,2]] = [('a',2), ('cc', 10)]` raises an error.

**Comment by sushobhana** [comment]
i would like to work on this !

**Comment by sushobhana** [comment]
@saimn @taldcroft - won't it be logical if the `__setitem__() ` changes only the value of the key column  if it's just a list of elements(as in `t.loc[['a', 'c']] = ['b','c']`?). And changes the whole row if it's a list of rows as in `t.loc[['a', 'c']] = [('a',2), ('cc', 10)]`.And we can solve `t[[0,2]] = [('a',2), ('cc', 10)]` this error by using a for loop since it accepts updation for a single row as in  `t[0] = [('a',2)]`

**Comment by sushobhana** [comment]
@saimn - i tried reproducing `In [6]: t.loc[['a', 'c']]['col1'] = 10` raises an error, says the right side must be iterable...then again i tried with `In [6]: t.loc[['a', 'c']]['col1'] = [10,20]` ,this time it does not show an error but the table 't' does not get updated 
But upon `In [6]: t.loc['a']]['col1'] = 10`, this runs without error and the table 't' gets updated..
I think apart from defining a `__setitem__()` in the `TableLoc` class we need to fix this issue in `Table` class
![screenshot from 2017-11-03 19-55-25](https://user-images.githubusercontent.com/22423652/32378610-3347b4a0-c0d1-11e7-9a37-e1cab132821b.png)
![screenshot from 2017-11-03 19-56-19](https://user-images.githubusercontent.com/22423652/32378611-338a5634-c0d1-11e7-95ad-a4bf71a34cb4.png)

**Comment by saimn** [comment]
Having the possibility to do `t.loc[['a', 'c']] = [('a',2), ('cc', 10)]` would already be good, though not easy to manipulate. 
So I would be in favor of having a way to get the indices, what do you think about this @taldcroft ?

**Comment by taldcroft** [comment]
@saimn - coming back to this after a break I see the merit in being able to get the indices directly.

For API what about `t.loc_indices[['a', 'c']]`.  This would return the row index values and follow the API of `t.loc`.

**Comment by saimn** [comment]
You're right about `get_indices()`, it makes more sense to use the same syntax as `.loc`, so :+1: to `t.loc_indices[['a', 'c']]` !

**Comment by sushobhana** [comment]
@taldcroft Sorry for replying late!..I was unwell.

Before all this discussions i tried to solve of my own.
i have changed the class TableLoc to this:
(here i have refactored the `__getitem()` and created a `__get_row()` function and added a `__setitem()` function)(Or should i make a TableLocIndices class inherited from the TableLoc class and add the `__setitem()` there?


`class TableLoc:`
   ` '''
   A pseudo-list of Table rows allowing for retrieval
    of rows by indexed column values.`

    Parameters
    ----------
    table : Table
        Indexed table to use
    '''

    def __init__(self, table):
        self.table = table
        self.indices = table.indices
        if len(self.indices) == 0:
            raise ValueError("Cannot create TableLoc object with no indices")

    def __get_row(self, item):
        '''
                Retrieve Table rows indexes by value slice.

                Parameters
                ----------
                item : column element, list, ndarray, slice or tuple
                    Can be a value of the table primary index, a list/ndarray
                    of such values, or a value slice (both endpoints are included).
                    If a tuple is provided, the first element must be
                    an index to use instead of the primary key, and the
                    second element must be as above.
        '''

        if isinstance(item, tuple):
            key, item = item
        else:
            key = self.table.primary_key

        index = self.indices[key]
        if len(index.columns) > 1:
            raise ValueError("Cannot use .loc on multi-column indices")

        if isinstance(item, slice):
            # None signifies no upper/lower bound
            start = MinValue() if item.start is None else item.start
            stop = MaxValue() if item.stop is None else item.stop
            rows = index.range((start,), (stop,))
        else:
            if not isinstance(item, (list, np.ndarray)):  # single element
                item = [item]
            # item should be a list or ndarray of values
            rows = []
            for key in item:
                rows.extend(index.find((key,)))
        return rows

    def __getitem__(self, item):
        '''
        Retrieve Table rows by value slice.

        Parameters
        ----------
        item : column element, list, ndarray, slice or tuple
            Can be a value of the table primary index, a list/ndarray
            of such values, or a value slice (both endpoints are included).
            If a tuple is provided, the first element must be
            an index to use instead of the primary key, and the
            second element must be as above.
        '''
        rows = self.__get_row(item)

        if len(rows) == 0:  # no matches found
            raise KeyError('No matches found for key {0}'.format(item))
        elif len(rows) == 1:  # single row
            return self.table[rows[0]]
        return self.table[rows]

    def __setitem__(self, key, value):
        '''
                Retrieve Table rows by value slice.

                Parameters
                ----------
                key : column element, list, ndarray, slice or tuple
                    Can be a value of the table primary index, a list/ndarray
                    of such values, or a value slice (both endpoints are included).
                    If a tuple is provided, the first element must be
                    an index to use instead of the primary key, and the
                    second element must be as above.

                value : New values of the row elements.
                      Can be a list of tuples/lists to update the row.
        '''

        rows = self.__get_row(key)
        if len(rows) == 0:  # no matches found
            raise KeyError('No matches found for key {0}'.format(key))
        elif len(rows) == 1:  # single row
            self.table[rows[0]] = value
        else:  # multiple rows
            for i,row in enumerate(rows):
                self.table[row] = value[i]
`

**Comment by saimn** [comment]
@sushobhana - can you open a pull request with your changes ? I will be much easier to comment on.

**Comment by sushobhana** [comment]
@saimn  ok!!..yeah!

**Comment by sushobhana** [comment]
@saimn kindly check it and send me your valuable feedback!
#6831
