### ISSUE TITLE
Move main astropy license to root of repository

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5914]
I think we should put our primary license at the root of the repository. In addition to making it clearer which license is our main one, GitHub will do nice things like make it explicit what the license is and do something like this:

<img width="851" alt="screen shot 2017-03-27 at 17 44 38" src="https://cloud.githubusercontent.com/assets/314716/24367597/1c6d160e-1315-11e7-9b20-e739935a8eda.png">

**Comment by astrofrog** [comment]
If we do that we should figure out what to rename the ``licenses`` folder to

**Comment by pllim** [comment]
"other_licenses"?

**Comment by bsipocz** [comment]
what about symlinking the main license back to the licenses folder (or from there into the root). How does github react to that?

**Comment by pllim** [comment]
http://stackoverflow.com/questions/954560/how-does-git-handle-symbolic-links

One of the comment says FAT does not support symlinks. Is that a deal breaker?

**Comment by astrofrog** [comment]
I would avoid symlinks. I think it's fine to have our main license at the root and licenses of original software separate.

**Comment by dpshelio** [comment]
Soft link doesn't work, I've just tested in a repository https://github.com/dpshelio/recipes

**Comment by pllim** [comment]
Is "for_lawyers" too snarky?

**Comment by MSeifert04** [comment]
Why not just put a real copy of the License in the root directory? It's not as if it's changed often (it says the license is only valid till 2016 😄). 

By the way, is there any requirement for the years on the license (seems like unnecessary maintenance effort)?

**Comment by bsipocz** [comment]
Good question about the year, I've noticed it's outdated on Sunday when looking for a licence for ci-helpers.

**Comment by astrofrog** [comment]
Let's update the year for now. I would avoid duplication just because we should have a single license, if there is ever any divergence (accidentally) then it'll cause headaches. Maybe we don't have to rename ``licenses``. The most important here is that we move the main license to the root.

**Comment by dpshelio** [comment]
The link could be done in the different direction though. A link from the license directory to the root.

**Comment by astrofrog** [comment]
I really want to avoid having licenses in two places even via a symlink

**Comment by Cadair** [comment]
putting a `README` in the licences folder should be enough to explain that the license for the main package is in the root of the directory.

**Comment by pllim** [comment]
@Cadair , I had exactly the same thought!

**Comment by bsipocz** [comment]
@astrofrog - Are you doing this license move, or do you want me to do so? (I already have a license updating branch for a few repos, but haven’t yet opened PRs).
