### ISSUE TITLE
np.random.uniform broken with units

### ISSUE THREAD

**Issue by joergdietrich** [astropy/astropy#5916]
With numpy-1.12
```
In [12]: np.random.uniform(u.Quantity(10, u.deg), u.Quantity(11, u.deg))
Out[12]: -1.0
```
This used to work up to 1.11.3 and returned a number between 10 and 11.

I'm reporting this here first before deciding whether this should be reported upstream or fixed in astropy.

**Comment by pllim** [comment]
What version of Astropy?

**Comment by mirca** [comment]
I see the same thing with ``astropy 1.3.1`` and ``numpy 1.12.1``

**Comment by joergdietrich** [comment]
At least 1.3 and 1.2.

**Comment by astrofrog** [comment]
cc @mhvk

**Comment by mhvk** [comment]
Did it used to return a number or a Quantity with units of degree? If the latter, I think this is an upstream regression. Note that this goes via Cython code in `random/mtrand/mtrand.pyx`, making it a bit less easy than is normally the case to see what is going on.

**Comment by joergdietrich** [comment]
As I said, a number.

**Comment by mhvk** [comment]
> As I said, a number.

In that case, I would argue it was broken before, even if it returned something, so it is not a regression. Note that currently there is some work going on in numpy to, e.g., support broadcasting (https://github.com/numpy/numpy/pull/6938) and possibly rewrite more generally (https://github.com/numpy/numpy/issues/8833). This might thus be a good time to chime in and argue that it would be nice to support this properly.

**Comment by joergdietrich** [comment]
I would agree that I was lucky that it worked before. However, silently returning -1 for everything is certainly not the right thing to do either. Apart from the on-going discussions that you referenced above, this looks like a numpy bug to me. Would you agree?

**Comment by mhvk** [comment]
@joergdietrich - I checked myself and on my system I do get an error, and if I then try again, it hangs. So, there definitely is something fishy in the numpy implementation. I raised an issue mentioning both our cases: https://github.com/numpy/numpy/issues/8865

**Comment by cdeil** [comment]
In Gammapy I fixed the same issue today. We were calling into `np.random.RandomState.uniform` with a quantity and it was returning garbage output without raising an error:
```python
>>> import numpy as np
>>> import astropy.units as u
>>> random_state = np.random.RandomState(0)
>>> random_state.uniform(0, 1*u.yr, 10)
array([-0.5488135 , -0.71518937, -0.60276338, -0.54488318, -0.4236548 ,
       -0.64589411, -0.43758721, -0.891773  , -0.96366276, -0.38344152])
```
I'm on Python 3.5 and Numpy 1.12.1 and still see the issue.

Can anyone confirm that this (going via `np.random.RandomState.uniform` instead of `np.random.uniform`) is also fixed by https://github.com/numpy/numpy/pull/8883 ?

Assuming it's fixed on the Numpy side and there's no action item for Astropy: close this issue?

**Comment by adrn** [comment]
@cdeil To answer your numpy question, I'm pretty sure `numpy.random.uniform` just calls `numpy.random.RandomState.uniform`:
https://github.com/numpy/numpy/blob/c90d7c94fd2077d0beca48fa89a423da2b0bb663/numpy/random/mtrand/mtrand.pyx#L5145

**Comment by mhvk** [comment]
I checked on numpy master and both examples now error instead of giving nonsense.  Obviously, it would still be nicer if they returned the right thing, but at least this issue is solved, so I'll close it.

**Comment by cdeil** [comment]
@mhvk - Thank you very much for all your work on the Astropy and Numpy internals to make life better for all of us!
