### ISSUE TITLE
issue with astropy.io.votable.converters

### ISSUE THREAD

**Issue by smoh** [astropy/astropy#5936]
Hi, I encounter a bug using pyvo TAPService (ccing @RayPlante just in case), but this seemed like something to be fixed on astropy.io.votable, so I raise an issue here.

https://gist.github.com/anonymous/0a7383ed6a2f815cbfd16204bda8bc20

The bug is that while parsing the list of tables from Simbad TAP Service, it will complain `DOUBLE` as unknown datatype, and while raising this error, it will raise another AttributeError because the instance of `astropy.io.votable.tree.Field` has no `ID` attribute. It seems to me that the simplest solution is to lowercase all datatypes before looking up in converter dictionary.

**Comment by pllim** [comment]
1. What version of Astropy are you using?
2. Is your VO table actually valid? Try run `volint` on it and look for warnings/errors.

**Comment by smoh** [comment]
1. 1.3
2. Actually, now that I look at it again, it is not a votable but another specification VOSI. I realize pyvo is only trying to use get_converter as utility to parse this, and not exactly passing the right class(`astropy.io.votable.tree.Field`) either (https://github.com/pyvirtobs/pyvo/blob/master/pyvo/tools/vosi.py#L257-L266) so I'll redirect this to pyvo.
