### ISSUE TITLE
units.Quantity length

### ISSUE THREAD

**Issue by gregreen** [astropy/astropy#5937]
When ``units.Quantity`` is a scalar, it still has a ``'__len__'`` attribute, but calling it generates an error. For code that's meant to work with different types of objects, this is troublesome. For example, take the following function, meant to work with lists, tuples, numpy arrays, floats, ints, and many other types:

    def get_length_safe(x):
        if hasattr(x, '__len__'):
            return len(x)
        return 1

This code will return ``1`` for scalars, and ``len(x)`` for array-like types. But this code breaks with ``units.Quantity``. For example:

    import units as u
    r = 10. * u.m
    get_length_safe(r)

The above returns the error:

    TypeError: 'Quantity' object with a scalar value has no len()

In my own code, I've had to modify the ``get_length_safe`` function to treat ``units.Quantity`` as a special case. It would be possible to use a ``try``/``except`` block. However, it would be nice if ``units.Quantity`` behaved like other classes, where ``hasattr(x, '__len__')`` is a sure sign that an object has a valid ``len()`` attribute.

**Comment by mhvk** [comment]
@gregreen - I see your point, but consistency is a difficult thing: `Quantity` is a subclass of `np.ndarray` and we are consistent with its behaviour:
```
len(np.array(1))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-93918941671b> in <module>()
----> 1 len(np.array(1))

TypeError: len() of unsized object
```
One reason for this is that typically in python anything that has a length can be indexed, but scalars cannot be indexed, so from this perspective they fundamentally do not have length one. Of course, python scalars signal this by having no `__len__` method, but this is not so easy to have the presence of an attribute depend on what is stored in a given instance of a single class.

In any case, I think overall your solution of a `try/except` block is in fact the correct one.

But the best solution also depends on what you actually want to do with the length. Could you elaborate?

**Comment by gregreen** [comment]
@mhvk - Ah, I wasn't aware that shape `()` numpy arrays behaved that way. There are a number of ways around this, so it's best to just keep consistency with how numpy does things.

What I wanted to do with the length was to bail if an input `Quantity` was longer than a certain threshold. The `try/except` block works for that purpose (or, alternatively, `np.prod(x, dtype='i8')`, which works for `np.array(1.)`).

**Comment by mhvk** [comment]
@gregreen - ok, makes sense; you could do something like:
```
if getattr(x, 'shape', ()):
    return x.shape[0]
else:
    return 1
```

**Comment by mhvk** [comment]
@gregreen - I'll close this as I think we reached a conclusion here; feel free to reopen if you have a different suggestion.

**Comment by gregreen** [comment]
I'll also just mention that `x.size` works for a scalar quantity. I'm not sure why that didn't occur to me earlier.
