### ISSUE TITLE
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x7

### ISSUE THREAD

**Issue by ljones29** [astropy/astropy#5939]
Hello all,

Last Friday I started getting runtime errors out of the blue when trying to work with astropy tables, e.g.:

```python
from astropy.table import Table
import matplotlib.pyplot as plt

if __name__ == "__main__":
    filein = Table.read("foo.txt",format="ascii")
    #etc`
```
where etc here means various plots. The full error I receive when trying to run this from the terminal is:
```
> RuntimeError: module compiled against API version 0xa but this version of numpy is 0x7
Traceback (most recent call last):
  File "prob1.py", line 4, in <module>
    from astropy.table import Table
  File "/usr/local/lib64/python2.7/site-packages/astropy/table/__init__.py", line 43, in <module>
    from .column import Column, MaskedColumn
  File "/usr/local/lib64/python2.7/site-packages/astropy/table/column.py", line 20, in <module>
    from . import groups
  File "/usr/local/lib64/python2.7/site-packages/astropy/table/groups.py", line 11, in <module>
    from .index import get_index
  File "/usr/local/lib64/python2.7/site-packages/astropy/table/index.py", line 42, in <module>
    from ..time import Time
  File "/usr/local/lib64/python2.7/site-packages/astropy/time/__init__.py", line 2, in <module>
    from .formats import *
  File "/usr/local/lib64/python2.7/site-packages/astropy/time/formats.py", line 15, in <module>
    from .. import _erfa as erfa
  File "/usr/local/lib64/python2.7/site-packages/astropy/_erfa/__init__.py", line 4, in <module>
    from .core import *
  File "/usr/local/lib64/python2.7/site-packages/astropy/_erfa/core.py", line 43, in <module>
    from . import _core
ImportError: numpy.core.multiarray failed to import
```
The only other possible point of interest is that the callbacks listed above are not the same directory I get when doing a `help(numpy)`, which says that the numpy package is in `/usr/lib64/python2.7/site-packages/numpy/__init__.py`. Any other program that uses astropy tables, even ones that I haven't touched in months and previously worked, also result in this error.

I'm running OSX 10.10.5 Yosemite and Python 2.7.6 with numpy v1.7.1 and astropy 1.3.1. I have no permissions to install new versions of packages, so doing a pip install or sudo install to update numpy is not possible. If there's any information I forgot that would help in finding a solution, please let me know.

Thank you,
Logan

**Comment by pllim** [comment]
How did you install Astropy? Why is it not in the same path as Numpy? Why do you have both paths registered? Do you use PYTHONPATH?

What shows up when you do this?
```python
>>> import sys
>>> sys.path
```

**Comment by ljones29** [comment]
I'm using a machine/setup supplied to me by my department. I don't have any knowledge of when, where, how, and why things are installed and registered the way they are; all I know is that prior to last Friday, python did not give me any complaints. Doing an `echo $PYTHONPATH` returns a blank line.

sys.path returns this:

> ['', 
'/usr/local/lib/python2.7/site-packages/pyfits-3.0.8-py2.7-linux-i686.egg', 
'/usr/local/lib/python2.7/site-packages', 
'/usr/local/lib/python2.7/site-packages/agpy-0.1.2-py2.7.egg', 
'/usr/local/lib/python2.7/site-packages/Jinja2-2.7.2-py2.7.egg', 
'/usr/local/lib/python2.7/site-packages/MarkupSafe-0.18-py2.7-linux-x86_64.egg', 
'/usr/lib/python27.zip', 
'/usr/lib64/python2.7', 
'/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk', 
'/usr/lib64/python2.7/lib-old', 
'/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages', 
'/usr/local/lib64/python2.7/site-packages', 
'/usr/local/lib/python2.7/site-packages', 
'/usr/local/lib64/python2.7/site-packages', 
'/usr/local/lib64/python2.7/site-packages/pyfits-3.0.8-py2.7-linux-x86_64.egg', 
'/usr/local/lib64/python2.7/site-packages/astrolib.coords-0.39.4-py2.7-linux-x86_64.egg', 
'/usr/local/lib64/python2.7/site-packages/scikits_image-0.7.1-py2.7-linux-x86_64.egg', 
'/usr/local/lib64/python2.7/site-packages/nose-1.3.0-py2.7.egg', 
'/usr/local/lib64/python2.7/site-packages/singledispatch-3.4.0.3-py2.7.egg', 
'/usr/local/lib64/python2.7/site-packages/setuptools-34.3.3-py2.7.egg', 
'/usr/local/lib/python2.7/site-packages', 
'/usr/lib64/python2.7/site-packages/gtk-2.0', 
'/usr/lib/python2.7/site-packages']

where I've taken the liberty of separating each element onto its own line for readability.

**Comment by pllim** [comment]
Thanks for the readability! Unfortunately, this seems like an issue you should sort out with your system admin. The admin should either install the correct Numpy where Astropy is installed, or install Astropy where the correct Numpy is installed. Then rebuild Astropy.

Someone can correct me if I am wrong but I think the underlying problem here is the C codes that the Python layer calls. C has to be compiled against the correct libraries or very bad things may happen.

**Comment by bsipocz** [comment]
> I'm running OSX 10.10.5 Yosemite and Python 2.7.6 with numpy v1.7.1 and astropy 1.3.1. I have no permissions to install new versions of packages, so doing a pip install or sudo install to update numpy is not possible. If there's any information I forgot that would help in finding a solution, please let me know.

@ljones29 - Have you tried to do  a ``pip install --user``? I believe you are always allowed to do that and it usually takes precedent over the system wide installs.
