### ISSUE TITLE
FYI: Auto cancel PR builds

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5940]
I think we need https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation , given sometimes a WIP PR can have multiple builds waiting due to successive commit pushes. I turned on the feature for PR (not branch). FYI. c/c @bsipocz @astrofrog 

If you don't have an issue with this change, please close the issue.

**Comment by bsipocz** [comment]
We already have this turned on (see @astrofrog e-mail on the dev list from december). If you still see builds not being cancelled ping the travis folks over at https://github.com/travis-ci/beta-features/issues/8 (can also ping me).
We don't have it turned on for pushes atm, though I think it would be useful there, too.

**Comment by pllim** [comment]
Huh. It was off when I checked this morning. That's why I turned it on and posted this. Are we talking about the same feature?

![untitled](https://cloud.githubusercontent.com/assets/2090236/24636474/7916545e-18a8-11e7-800d-5e48076108e3.png)

**Comment by bsipocz** [comment]
That's strange. Either someone turned it off at some point,  or they've
changed it when went to public beta with it. Anyway thanks for spotting it
and turning back on.

**Comment by pllim** [comment]
> Either someone turned it off at some point, or...

@bsipocz , I just found out that (in another repo) if you turn it on *and* also modify something else (like adding environment variables) in the same "session", for whatever reason (a bug?), it does not register that you turned the feature on albeit saving the variables. So I had to refresh the settings page and turn it on again without changing anything else. Perhaps that was why it was off for Astropy earlier?

**Comment by bsipocz** [comment]
It was definitely functioning, but that was before it became public. I also had some problem with it in astroquery where it stopped working, though it was still turned on in the settings page. However that was reported and sorted out via travis support.
