### ISSUE TITLE
How to read in FITS primary header into Astropy Table metadata?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5947]
Someone asked me this and I have no idea. @taldcroft ?

I have a FITS binary table with these extensions:
```
No.    Name         Type      Cards   Dimensions   Format
  0  PRIMARY     PrimaryHDU      23   ()      
  1  OSCN        BinTableHDU     98   6R x 19C   [4A, 1I, 1I, 1I, 1I, 1I, 1I, 1I, 1I, 1I, 1I, 1I, 1I, 67A, 1I, 1I, 1I, 1I, 1I]
```

How do I get `Table.read(..., format='fits')` to read in the primary header as metadata? By the way, this is a common format for FITS table at STScI.

**Comment by saimn** [comment]
It is not possible (the `Table` object is constructed from the `BinTableHDU` one, which contains the column definitions). Not sure how this could be improved ?

**Comment by saimn** [comment]
I thought there was an old discussion on this but I cannot find it: I remember having the same kind of issue when reading and writing a FITS table with `Table.read` and `Table.write`, and losing the primary header in the result file. 
Another issue related to the FITS/Table interface is #2632, thought not exactly the same issue.

**Comment by pllim** [comment]
@saimn , this is maybe a specialized subset of #2632 since it is about writing multiple object but one of the object is just a header with no data. So, should we just mark this as "won't fix" and close?

**Comment by saimn** [comment]
@pllim - probably, I don't really see how it could be supported directly with the `Table` interface, but it's something that should be included in a more general FITS/Table interface discussion.
