### ISSUE TITLE
different behaviors of transform_to in coordinates package

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#5949]
I've just noticed that `SkyCoords` and `BaseCoordinateFrame` have slightly different  behavior when using `transform_to`: 

    >>> from astropy import coordinates as coord
    >>> from astropy import units as u
    >>> ra=163.6136 
    >>> dec=-11.784
    >>> c=coord.SkyCoord(ra=ra*u.degree, dec=dec*u.degree)
    >>> c.transform_to('fk5')
    <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg
    (163.61360732, -11.78400398)>
    >>> f=coord.FK5(ra=ra*u.degree, dec=dec*u.degree)
    >>> f.transform_to('fk5')
    Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/Users/crawford/anaconda/lib/python3.5/site-packages/astropy/coordinates/baseframe.py", line 848, in transform_to
     raise ConvertError(msg.format(self.__class__, new_frame.__class__))
     astropy.coordinates.errors.ConvertError: Cannot transform from <class 'astropy.coordinates.builtin_frames.fk5.FK5'> to <class 'str'>

It appears that `SkyCoord.transform_to` will accept a str representation of the class name where as `BaseCoordinateFrame.transform_to` will not (and as is stated in the doc strings for both functions).   This was raised in some older documentation code for astroquery that would make it appear that this functionality was once similar, so I wanted to check if removing it was intentional or if it would be worthwhile to submit a fix.

**Comment by adrn** [comment]
@crawfordsm Hmm, I don't remember `BaseCoordinateFrame` subclasses ever accepting a string? I think the general rule of thumb is that interaction with the `BaseCoordinateFrame` subclasses is meant to be more explicit, whereas `SkyCoord` can do more magic for you. But as to whether you should submit a PR implementing this, I don't have a strong opinion -- @eteq?

**Comment by adrn** [comment]
I think this may have been a error in the astroquery documentation, and the current functionality is intentional, so closing this. Reopen if you disagree!
