### ISSUE TITLE
Quantity constructor does not accept 'nan'

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#5956]
'nan' is a valid Python float but is not a valid argument to the quantity constructor. The same applied for 'inf' and '-inf'.
```python
 ❯ u.Quantity('nan', 'deg')
TypeError: Cannot parse "nan" as a Quantity. It does not start with a number.

 ❯ u.Quantity(float('nan'), 'deg')
<Quantity nan deg>
```

**Comment by bsipocz** [comment]
@Cadair - using ``np.nan`` rather than the string ``'nan'`` works fine, though I agree that it would be nice to have the latter one working, too.

**Comment by Cadair** [comment]
I am reading the value out of a fits header rather than doing it directly.
