### ISSUE TITLE
Print quantity in LaTeX: How to get exponents with `\times`?

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#5964]
I'll describe the behaviour I expected to find somewhere in formatting quantities. Looking though the code, it seems that all the building blocks are there at some point, so I don't know if my inability to get the output I'm looking for is due to mission documention (in that case I suggest to add an example), if it's a bug or a missing feature.
Let's say I have a quantity like this (the actual number is the result of a lengthy computation that does not matter here):
```
import astropy.units as u
dens = 1671146780.5671113 * u.cm**(-3)
```
Now, I want to format that in LaTeX, so that I can include the result in an article I write:
Just typing "dens" in an IPython notebook already looks pretty good (can't paste that in here, because I don't know how to put MathJax into githu markdown).
Next, I try this:
```
print('The density is {0}'.format(dens))
The density is 1671146780.5671113 1 / cm3
```
Unit is not formatted and I clearly have too many digits. OK, so I follow the docs and find this:
```
print('The density is {0.value} {0.unit:latex_inline}'.format(dens))
The density is 1671146780.5671113 $\mathrm{cm^{-3}}$
```
Mmm. Close, but I need the unit in inline format to include it in the text and I do not want all those digits on the number. Next:
```
print('The density is {0.value:5.1e} {0.unit:latex_inline}'.format(dens))
The density is 1.7e+09 $\mathrm{cm^{-3}}$
```
That's better, but the value should not have an "e" in it.
Looking through the code, I find "_repr_latex_". The underscore indicates that I'm not supposed to call that directly, but I could not find a way to get this through e.g. to_string or any similar method, so I just try it anyway:
```
dens._repr_latex_()
'$1.6711468 \\times 10^{9} \\; \\mathrm{\\frac{1}{cm^{3}}}$'
```
Now, instead of "e09" I get the proper "\times 10^9" than I'm looking for, but the unit is `latex` and not `latex_inline` again and the value has too many digits.
The source code of `_repr_latex_` indicates that it reads `np.set_printoptions`, but I don't see any change
```
np.set_printoptions(precision=2)
dens._repr_latex_()
'$1.6711468 \\times 10^{9} \\; \\mathrm{\\frac{1}{cm^{3}}}$'
```

Is there any way in the formatting machinery to get this output:
`1.7  \\times 10^{9} \\; \\mathrm{cm^{-3}}`? It seems all the building blocks are there, but I did not get it to work.
For now, I'll just print the result to screen and then type it off into my LaTeX text instead of generating the number automatically. I just have to remember to update it if I change the calculation.

@mhvk

**Comment by mhvk** [comment]
Sadly, we simply do not yet have the right tools. `_repr_latex_` is really for use in `ipython` notebook, which is why that looks quite good. That it doesn't use `precision` is a bug, though... see #5965

I think what would needed more generally is to mimic `Unit` a bit more closely, and define a `to_string` method, which would include ensuring we can also represent complex numbers, etc. (see #5071). This should not be hard, but is not a trivial fix either...

**Comment by mhvk** [comment]
These days, the following works:
```
dens.to_string(format='latex', precision=2)
# '$1.7 \\times 10^{9} \\; \\mathrm{\\frac{1}{cm^{3}}}$'
```
which seems close enough to close the issue...
