### ISSUE TITLE
Quantity._repr_latex_ should respect np.printoptions

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5965]
As noted by @hamogu, the docstring to `Quantity._repr_latex_` states that it respects `np.printoptions`, but this turns out not to be true:
 ```
dens = 1671146780.5671113 * u.cm**(-3)
dens._repr_latex_()
'$1.6711468 \\times 10^{9} \\; \\mathrm{\\frac{1}{cm^{3}}}$'
```
The source code of `_repr_latex_` indicates that it reads `np.set_printoptions`, but I don't see any change
```
np.set_printoptions(precision=2)
dens._repr_latex_()
'$1.6711468 \\times 10^{9} \\; \\mathrm{\\frac{1}{cm^{3}}}$'
```

Looking through the code path, things get sent to `split_mantissa_exponent`, but that does nothing with `np.print_options`.

Fixing this may be as simple as using `np.array2string` instead of formatting using the python format logic.

**Comment by aleksandr-bakanov** [comment]
Hi @mhvk 
Can you review [this PR](https://github.com/astropy/astropy/pull/6412)?
