### ISSUE TITLE
RICE compression options ignored in io.fits.CompImageHDU?

### ISSUE THREAD

**Issue by schlafly** [astropy/astropy#5969]
I was trying to compress some FITS images using astropy and found that quantize_level seems to be ignored when using RICE compression.

e.g., some minimal code (which, warning, will write some files im1.fits, im2.fits, and im3.fits...):
```python
from astropy.io import fits
import scipy, numpy
im1 = scipy.misc.ascent() + numpy.random.randn(512, 512)*10
fits.ImageHDU(im1).writeto('im1.fits')
fits.CompImageHDU(im1, compression_type='RICE_1', quantize_method=1, quantize_level=-1, dither_seed=5).writeto('im2.fits')
fits.CompImageHDU(im1, compression_type='RICE_1', quantize_method=1, quantize_level=-100, dither_seed=5).writeto('im3.fits')
im2 = fits.getdata('im2.fits')
im3 = fits.getdata('im3.fits')
numpy.all(im2 == im3)  # True, but expected False?
```
My impression is that im3.fits should be much smaller than im2.fits, and that im2 and im3 should be quite different, one having been quantized with a step size of 100 and the other having been quantized with a step size of 1.  Instead the images are identical.  Compressing with fpack -q -100 and fpack -q -1 indeed produces images with very different sizes.

Relatedly, if I change the compression_type to GZIP_1, quantize_method has an effect, and one sees clearly smaller images with quantize_level = -100 than with quantize_level = -1.  

So as far as I can tell, the quantize_level argument is not being properly processed for RICE compression.

**Comment by pllim** [comment]
What version of Astropy, Numpy, and SciPy are you using?

What happens when you do `fitsdiff im2.fits im3.fits`?

What do you see when you do `ls -lh im?.fits`?

**Comment by schlafly** [comment]
> What version of Astropy, Numpy, and SciPy are you using?

astropy 1.2.1, but I've looked at 1.3 as well.  numpy 1.11.0, scipy 0.17.1; I've also checked scipy 0.18.1.

> What happens when you do fitsdiff im2.fits im3.fits?

```
 fitsdiff: 1.2.1
 a: im2.fits
 b: im3.fits
 Maximum number of different data values to be reported: 10
 Data comparison level: 0.0

No differences found.
```
Though the headers are in fact different and have ZVAL3 set to -1 or -100, as appropriate.

> What do you see when you do ls -lh im?.fits?

```
-rw-r--r-- 1 schlafly finkbeiner_lab 2.1M Apr 17 23:01 im1.fits
-rw-r--r-- 1 schlafly finkbeiner_lab 248K Apr 17 23:01 im2.fits
-rw-r--r-- 1 schlafly finkbeiner_lab 248K Apr 17 23:01 im3.fits
```

**Comment by pllim** [comment]
Thanks for the additional details. 🙏 @embray 🙏

**Comment by saimn** [comment]
It seems that the `NOISEBIT` value (quantization level) is not parsed when the compression type is RICE_1 or HCOMPRESS_1:
https://github.com/astropy/astropy/blob/master/astropy/io/fits/src/compressionmodule.c#L632
which is not consistent with the Python code:
https://github.com/astropy/astropy/blob/master/astropy/io/fits/hdu/compressed.py#L1219

Changing the if clause in the C code seems to work, and produce a im3.fits that is smaller than im2.fits. @embray ?
