### ISSUE TITLE
Quantity arrays do not play nice with Bokeh server

### ISSUE THREAD

**Issue by gkanarek** [astropy/astropy#5970]
Hello all,

I'm trying to use `astropy.units` in conjunction with apps run via Bokeh server. Specifically, I'm storying Quantity arrays as attributes in a controller class which handles all the computations and callbacks; however, whenever the Bokeh server tries to serialize the entire session as JSON, it returns an error. The server looks for instances of `numpy.ndarray` (which Quantity arrays are), and calls `tolist()`, which for Quantities returns a `NotImplementedError`.

Any suggestions?

**Comment by pllim** [comment]
@mhvk ?

**Comment by mhvk** [comment]
I don't think we can easily change `tolist()`, but perhaps there is another hook to ensure serialization as json? In particular, there is some work on making a custom json encoder in #5471; this has stalled a bit as  @taldcroft hoped to have a more general(izable) scheme in place -- which works for yaml (#5486).

Overall, I think the pieces are in place to make this work, at least if there is another hook than `tolist()`.

**Comment by mhvk** [comment]
I'm closing this as I think we would need more information and/or a concrete example to make progress. @gkanarek - please do feel free to re-open if this remains an issue or you have a work-around that can be shared.
