### ISSUE TITLE
Should document better how QTable, Table interaction with info and mixin columns

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5976]
Following discussion in https://github.com/gammapy/gammapy/issues/980 with @cdeil: it would be very helpful to document how to best interact with the various column types in `Table` and `QTable`. In particular, e.g., that by accessing information via `info` (such as `info.name`, `info.description`, `info.meta`), one can ensure that code, if appropriate, can be agnostic to the type of column it is dealing with. 

Similarly, we should perhaps make clearer how one can construct one's own mixin column type using a suitable `info` property.

Milestoning this 2.0 since I think it is important that this be clear.

p.s. It may be best to do this after #5910 and #5841 have been merged, i.e., when `QTable` is essentially equivalent to `Table` except for not supporting masks.

p.p.s. EDIT there may be a somewhat larger issue here, in that for people who really want to use astropy it might be helpful to have some overview description of how things are implemented. This certainly holds for `Quantity`...

**Comment by larrybradley** [comment]
This was also suggested in #5658.

**Comment by mhvk** [comment]
Thanks @larrybradley  - I am closing this one now in favour of #5658 (I copied my initial comment there).
