### ISSUE TITLE
 The C compiler used to compile Python gcc-4.2, and which is normally used to compile C extensions, is not available.

### ISSUE THREAD

**Issue by MachineAlfr** [astropy/astropy#5977]
Running `pip install --upgrade astropy` throws:
```
The C compiler used to compile Python gcc-4.2, and
which is normally used to compile C extensions, is not
available. You can explicitly specify which compiler to
use by setting the CC environment variable, for example:
    
    CC=gcc python setup.py <command>
    
or if you are using MacOS X, you can try:
    
    CC=clang python setup.py <command>
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-mwnzXX/astropy/
```

I found a workaround by linking gcc-4.2 to clang: `sudo ln -s /usr/bin/clang /usr/bin/gcc-4.2` 
I was wondering why the installer is trying to compile with a c compiler that is no longer supported on OS X and is pretty outdated on other systems. 

Successful and unsuccessful logs attached. 
[astropy-install-successful.txt](https://github.com/astropy/astropy/files/963013/astropy-install-successful.txt)
[astropy-install-unsuccessful.txt](https://github.com/astropy/astropy/files/963014/astropy-install-unsuccessful.txt)

**Comment by astrofrog** [comment]
@bsmith18 - did you try the suggested workaround? I think it might work with pip too, so:

CC=clang pip install astropy --upgrade

Any luck?

**Comment by bsmith18** [comment]
I just linked gcc-4.2 to clang and got it to install but my question is why is astropy still using gcc-4.2? Why not just use the system's default gcc or do a version check on gcc at compilation?

**Comment by astrofrog** [comment]
@MachineAlfr - astropy is not specifically using gcc-4.2, it just uses whatever compiler Python was compiled with (this is how Python packages normally compile C extensions).

**Comment by MachineAlfr** [comment]
I thought that was the case too, but why did I have to link gcc-4.2 to clang in order for pip to install astropy? Without this, I got the error above.

**Comment by pllim** [comment]
On some Macs, "gcc" is just an alias for "clang", hence your need for linking. I don't use Mac myself but I have heard of such black magic from my colleagues who have to build C pipeline on Macs.

**Comment by MachineAlfr** [comment]
The thing is, I didn't link "gcc" to "clang", I had to specifically link "gcc-4.2" to "clang". I first tried linking "gcc" to "clang" but I still got the above error. This indicates to me that the installer was calling "gcc-4.2" to compile, and it even says this in the above error. I do not have gcc-4.2 installed on my Mac, which is also why pip threw this error. I usually update all my python libraries with pip, but only astropy gave me this error.

**Comment by sosey** [comment]
The default on Mac is just clang, gcc is just a copy of it I believe, not a link even. Double check that it's calling what you think it's calling
```
bash-3.2$ which gcc
/usr/bin/gcc
bash-3.2$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix


bash-3.2$ clang --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by MachineAlfr** [comment]
I have gcc installed with macports version 4.9.4. I have clang version 7.0.2 from Xcode. I think the installer was calling "gcc-4.2", not "gcc" nor "clang". If it called gcc it should have installed just fine, but I think it was calling "gcc-4.2".

**Comment by astrofrog** [comment]
As mentioned above, the reason it is calling gcc-4.2 is because Python was compiled with that specific compiler. In any case, it would be good to know if the recommended workaround of doing e.g. ``CC=clang pip install astropy`` works.

**Comment by MachineAlfr** [comment]
You're right about the original compiler being gcc-4.2. Running `sys.version` in python gives `[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]`. But that doesn't resolve why astropy was the only package that couldn't install without aliasing. For your suggestion, that command works in bash just fine, not in other shells though.

**Comment by astrofrog** [comment]
@MachineAlfr - which other packages did you install that correctly identified the compiler? (just so we can see how they deal with this)

**Comment by MachineAlfr** [comment]
I uninstalled astropy and pymc for example with `sudo pip uninstall astropy pymc,` then deleted my gcc-4.2/clang link. I reinstalled both with `sudo pip install pymc astropy` and pymc installed fine, but I get the same error for astropy. This is only one out of several packages that installed fine though. I can list others if needed.

**Comment by pllim** [comment]
Sometimes you need to uninstall several times if you have many older versions installed via `pip`. Also, is pip pulling it "fresh" from Internet, or somehow accessing a cached download?

**Comment by MachineAlfr** [comment]
It does download the latest version each time according to the output. When I uninstall astropy and I can't import it in python so I'm assuming it uninstalled correctly.

**Comment by pllim** [comment]
The full fresh installation log and error message might help further investigation. And maybe also a log of a successful package for comparison. You can attach them to this issue as text files.

**Comment by MachineAlfr** [comment]
I updated my original posts with the logs from pip when installing with and without the linking mentioned above.

**Comment by pllim** [comment]
This is funny... Number one Google search result gave me #2011, which is a very old issue with the same problem. No solution there except with the `ln -s` that you already do.

The actual compiler check is in `astropy-helpers` as [_adjust_compiler()](https://github.com/astropy/astropy-helpers/blob/527f03605ca72cc3c8fef8b4f7dbc591d22a4e23/astropy_helpers/commands/build_ext.py#L327).

**Comment by pllim** [comment]
Unless someone has an idea how to fix this, I propose we mark this as "won't fix" and move on. Since @mdboom and @embray couldn't figure it all those years ago, I am not very optimistic.
