### ISSUE TITLE
iers auto_download not working

### ISSUE THREAD

**Issue by germanschnyder** [astropy/astropy#5979]
I'm trying to avoid the download of iers data table, but is not working whatsoever:´

```
$ pip freeze | grep astropy
astropy==1.3.2

$ python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.time import Time
>>> from astropy.utils import iers
>>> iers.conf.auto_download = False
>>> t = Time('2016:001')
>>> t.ut1
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|==============================>------------| 2.2M/3.1M (71.39%) ETA    10s
```

Any clues ?

**Comment by eteq** [comment]
@germanschnyder - can you clarify what exactly the *problem* is here?  That is, you want it to *not* download, or the download isn't working correctly?

The main point here is that the ``.ut1`` conversion *cannot* be done without the information in the IERS files.  So it's not clear to me what your intended behavior is.

**Comment by germanschnyder** [comment]
Thanks for the response. 
Maybe i'm assuming something wrong here. I want it to not download the updated table, since I'm processing data before of the astropy release I'm using. 
From the documentation I understood that there is already a table with up-to-date values included on the distro, so I assumed that if i specify this flag it won't download it again.

**Comment by pllim** [comment]
Might be a bug of `IERS_Auto` ignoring the config setting. I can reproduce this behavior in a different way:
```python
>>> from astropy.utils import iers
>>> iers.conf.auto_download = False
>>> tab = iers.IERS_Auto.open()  # Should default to B but...
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|==========================================| 3.1M/3.1M (100.00%)         2s
```

@taldcroft ?

**Comment by pllim** [comment]
Workaround this for now by doing the following:
```python
>>> from astropy.utils import iers
>>> iers.conf.iers_auto_url = 'broken_link'
>>> from astropy.time import Time
>>> t = Time('2016:001')
>>> t.ut1
WARNING: failed to download broken_link, using local IERS-B: unknown url type: 'broken_link' [astropy.utils.iers.iers]
<Time object: scale='ut1' format='yday' value=2016:001:00:00:00.082>
```

**Comment by taldcroft** [comment]
Ugh, sorry.  If you do the following it should work without having to get a failed download first:
```
from astropy.utils.data import clear_download_cache
clear_download_cache()  # to be sure it is really working

from astropy.utils import iers
iers.conf.auto_download = False
iers.conf.iers_auto_url = None
from astropy.time import Time
t = Time('2016:001')
t.ut1
```
