### ISSUE TITLE
WCSaxes does not modify the tick formatting to make tick labels bold

### ISSUE THREAD

**Issue by astro-fermi** [astropy/astropy#5983]
Hi,
I am trying to plot a test statistic map from a fits file. I am using MAC Sierra and python 2.7. 
My input code is as follows
```python
import scipy.ndimage as ndimage
from matplotlib.cm import register_cmap, cmap_d
from matplotlib import pyplot as plt
from astropy.io import fits
from astropy.wcs import WCS
from astropy.nddata import Cutout2D
from astropy import units as u
from matplotlib import rc, rcParams
import numpy as np
rc('text',usetex=True)
rc('font',**{'family':'serif','serif':['Computer Modern']})
rcParams['text.latex.preamble'] = [r'\boldmath']

ds9b = {'red': lambda v : 4 * v - 1, 
        'green': lambda v : 4 * v - 2,
        'blue': lambda v : np.select([v < 0.25, v < 0.5, v < 0.75, v <= 1],
                                      [4 * v, -4 * v + 2, 0, 4 * v - 3])}
register_cmap('ds9b', data=ds9b)
cmap = plt.cm.get_cmap('ds9b')

name='XXXX'
image_file='TSMAP.fits'
RA_radio=1.431711E+02
DEC_radio=5.310925E+01
RA_gamma=143.135398743
DEC_gamma=53.0875594636
R95=0.04            # in degrees
R95=R95*20      # convert to pixel system, 1 pixel=0.05 degree

w = WCS(image_file)
x_rad,y_rad=w.all_world2pix(RA_radio,DEC_radio,0)
x_gam,y_gam=w.all_world2pix(RA_gamma,DEC_gamma,0)

hdu = fits.open(image_file)[0]
wcs = WCS(hdu.header)
position = (x_gam,y_gam)
size=200
cutout = Cutout2D(hdu.data, position, size)
fig=plt.figure()
ax = fig.add_subplot(1,1,1, projection=wcs)
cax1=ax.imshow(cutout.data, origin='lower', cmap=cmap)
cax = ndimage.gaussian_filter(hdu.data, sigma=2, order=0)
cax = ax.imshow(cax,origin='lower', cmap=cmap)
cbar=fig.colorbar(cax1)
cbar.ax.set_ylabel(r'{\bf Test Statistic}', fontsize=16)
cbar.ax.tick_params(labelsize=16)
lon = ax.coords[0]
lat = ax.coords[1]
circle1=plt.Circle((x_gam,y_gam),R95,color='k',fill=False, lw=1)
fig.gca().add_artist(circle1)
ax.scatter([x_rad],[y_rad], c='r', s=40, marker='+',
           transform=ax.get_transform(WCS(hdu.header)),
           label=r'{\bf radio position}')
ax.scatter([x_gam],[y_gam], c='limegreen', s=40, 
           marker='x',transform=ax.get_transform(WCS(hdu.header)),
           label=r'{\bf optimized $\gamma$-ray position}')
leg=ax.legend(loc='upper right', scatterpoints = 1, markerscale=2.,fontsize=16)
leg.get_frame().set_alpha(0.0)
for text in leg.get_texts():
    plt.setp(text, color = 'w')

lon.set_axislabel(r'{\bf Right Ascension}', fontsize=16)
lat.set_axislabel(r'{\bf Declination}', fontsize=16)

lon.set_ticks(size=6, color='white')
lat.set_ticks(size=6, color='white')

lon.set_major_formatter('d')
lat.set_major_formatter('d')

lon.set_ticklabel(size=18)
lat.set_ticklabel(size=18)
lon.display_minor_ticks(True)
lat.display_minor_ticks(True)
lat.set_minor_frequency(5)

ax.set_title(r'{\bf %s}' %name, fontsize=16)
plt.savefig('%s_TSMAP.eps' %name, format='eps', dpi=600, bbox_inches='tight')
```
As can be seen, I can make axes labels bold using the latex style {\bf }. However, when trying to do the same with tick labels (using set_major_formatter), it throws the error
ValueError: Invalid format: {\bf d}

Please help in this regard and please let me know if I need to provide more information.

**Comment by pllim** [comment]
This seems more like a matplotlib issue than an Astropy one.

**Comment by vaidehiratna** [comment]
Well, I also tried the following

from matplotlib.ticker import FormatStrFormatter
majorFormatter1 = FormatStrFormatter(r'{\bf %d}')
lon.set_major_formatter(majorFormatter1)
lat.set_major_formatter(majorFormatter1)

But I get the following error
Traceback (most recent call last):
  File "TSMAP_1.py", line 75, in <module>
    lon.set_major_formatter(majorFormatter1)
  File "/Library/Python/2.7/site-packages/wcsaxes-0.7.dev617-py2.7.egg/wcsaxes/coordinate_helpers.py", line 173, in set_major_formatter
    raise NotImplementedError()  # figure out how to swap out formatter
I believe the issue has something to do with angular coordinates being defined in WCSaxes. I have used similar commands in other plots (plotting x vs y) and I am able to get the desired results without any problem.

Hope this information will help in rectifying the issue.

**Comment by pllim** [comment]
`wcsaxes` is now part of Astropy but it seems like you are using an old installation when it was a separate package. Uninstall it.

**Comment by vaidehiratna** [comment]
I just did that and ran the script again. Unfortunately, the error persists.

Traceback (most recent call last):
  File "TSMAP_1.py", line 75, in <module>
    lon.set_major_formatter(majorFormatter1)
  File "/Library/Python/2.7/site-packages/astropy-1.3.2-py2.7-macosx-10.12-intel.egg/astropy/visualization/wcsaxes/coordinate_helpers.py", line 202, in set_major_formatter
    raise NotImplementedError()  # figure out how to swap out formatter
NotImplementedError

**Comment by pllim** [comment]
Now, there is something we can work with. Thanks!

**Comment by bsipocz** [comment]
@pllim @astrofrog - Given that wcsaxes is quite a large submodule with its own issues, I took the liberty and created a ``visualization.wcsaxes`` label following the logic of the ``io`` and the ``vo`` modules.

**Comment by astrofrog** [comment]
I'll investigate soon

**Comment by astrofrog** [comment]
@astro-fermi I think this should be addressed by https://github.com/astropy/astropy/pull/7961 and available in the latest version of the astropy core package, but feel free to open a new issue if you are still having issues.
