### ISSUE TITLE
Version of FITS-tools incompatible with pip

### ISSUE THREAD

**Issue by HackerMD** [astropy/astropy#5984]
When installing the `FITS-tools` package (https://pypi.python.org/pypi/FITS_tools/0.0.dev258) via pip, the version is not correctly handled.

```
pip install FITS-tools==0.0dev258
```

```
Collecting FITS-tools==0.0dev258
  Downloading FITS_tools-0.0.dev258.tar.gz (207kB)
    100% |████████████████████████████████| 215kB 1.1MB/s
  Requested FITS-tools==0.0dev258 from https://pypi.python.org/packages/56/60/b235a9fc82d9fdaa096049dc4f1791640e78c0ce62f4fed7b6fccdcbaeb3/FITS_tools-0.0.dev258.tar.gz#md5=79e377f0667b3f795b6df10c608c2d25, but installing version None
```

When I then freeze the environment, I get a different, incorrect version, which cannot be installed:

```
pip freeze
```

```
FITS-tools==0.0.dev0
```

**Comment by saimn** [comment]
The repository to report an issue with FITS_tools is here: https://github.com/keflavich/FITS_tools
I guess the "Home Page" link on PyPI is the reason why you reported your issue here ? ping @keflavich

**Comment by HackerMD** [comment]
> The repository to report an issue with FITS_tools is here: https://github.com/keflavich/FITS_tools

Ok. Created the issue there.

> I guess the "Home Page" link on PyPI is the reason why you reported your issue here ?

Yes.
