### ISSUE TITLE
compound models do not scale well with complexity

### ISSUE THREAD

**Issue by perrygreenfield** [astropy/astropy#5985]
The current implementation of compound models essentially replicate all parameter instances at every level of the expression tree. This effectively results in the number of parameter instances increasing roughly with the square of the number of class instances times (assuming roughly even distribution of parameters with model instances). This is not an idle worry. Some JWST WCS models involve nearly 100 model components and almost 300 parameters. This leads to over 10 thousand parameter instances and huge memory usage, and consequent time instantiating the model (significant fractions of an hour for MOS cases). This basically renders the current implementation impractical for such complex models.

One could try to optimize this with the existing implementation, but there is no simple way to make the user interface transparent if python expressions are to be used to create compound models. I have tried an alternate implementation of compound models that I will submit a PR soon for comments.

**Comment by nden** [comment]
`CompoundModel` was reworked  in v 4.0 essentially fixing this issue.
