### ISSUE TITLE
`fits.writeto()` discards header input for non-image data

### ISSUE THREAD

**Issue by dmopalmer** [astropy/astropy#5988]
When I use `fits.writeto(filename,data=data, header=header)`, the header information is not included in the output file's header.

I make a minimal FITS file:
```python
import numpy as np
from astropy.io import fits
data=np.zeros((5,),dtype=[('x',np.float),('y',np.int)])
h_in = fits.Header()
h_in['ANSWER']=(42.0,'LTU&E')
fname='/tmp/foo.fits'
fits.writeto(fname,data=data,header=h_in,clobber=True)
h_out=fits.getheader(fname,ext=1)
h_in,'------------------------------------------------',h_out
```
and the output header doesn't have the `ANSWER` field that was passed to the `writeto()`:
```
(ANSWER  =                 42.0 / LTU&E                                          ,
 '------------------------------------------------',
 XTENSION= 'BINTABLE'           / binary table extension
 BITPIX  =                    8 / array data type
 NAXIS   =                    2 / number of array dimensions
 NAXIS1  =                   16 / length of dimension 1
 NAXIS2  =                    5 / length of dimension 2
 PCOUNT  =                    0 / number of group parameters
 GCOUNT  =                    1 / number of groups
 TFIELDS =                    2 / number of table fields
 TTYPE1  = 'x       '
 TFORM1  = 'D       '
 TTYPE2  = 'y       '
 TFORM2  = 'K       '                                                            )
```

The `ANSWER` field is also not in extension 0.

On the other hand, if I make an image FITS file, the header data is retained:

```python
image = np.zeros((10,10),dtype=np.float)
fname='/tmp/foo_image.fits'
fits.writeto(fname,data=image,header=h_in,clobber=True)
h_out_image=fits.getheader(fname,ext=0)
h_out_image
```
which has `ANSWER` in the ext=0 header:
```
SIMPLE  =                    T / conforms to FITS standard
BITPIX  =                  -64 / array data type
NAXIS   =                    2 / number of array dimensions
NAXIS1  =                   10
NAXIS2  =                   10
ANSWER  =                 42.0 / LTU&E
```

This is in astropy 1.3.2 .

Work-around:
```
hdu = fits.BinTableHDU(data=data, header=h_in)
hdu.writeto(fname, clobber=True)
fits.getheader(fname,ext=1)
```
gives a file with the `ANSWER` in the header.

**Comment by saimn** [comment]
Indeed, the header is not used when creating the HDU:
https://github.com/astropy/astropy/blob/master/astropy/io/fits/convenience.py#L1024
Passing the header to `BinTableHDU` (and `ImageHDU`) should be enough.

**Comment by pllim** [comment]
@saimn , passing header into `ImageHDU` in `_makehdu` is not necessary, as it is already inserted into primary header for image higher up.

**Comment by pllim** [comment]
Potential fix in #6042.

@dmopalmer , please replace your "clobber" keywords with "overwrite", as the former is deprecated.

**Comment by saimn** [comment]
@saimn - Ah yes, in this case (for `.writeto()`) the image HDU is not used.

**Comment by pllim** [comment]
@saimn , did you just pinged yourself? >_>

**Comment by saimn** [comment]
oops 😁
