### ISSUE TITLE
Sphinx test failing with deprecation warning

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5992]
It has been failing for the past several builds, so can hardly be transient. I suspect this is the culprit:

```
DeprecationWarning: Old configuration for backreferences detected 
using the configuration variable `mod_example_dir`
```

Example failed build: https://travis-ci.org/astropy/astropy/jobs/226804941

@adrn?

**Comment by mhvk** [comment]
Wow, you actually found what is going on! I scrolled through a very similar log and had no idea what caused the problem...

Aside: it would be nice to get rid of the warnings about wrong ticksize and sampling too.

**Comment by pllim** [comment]
Found the culprit -- sphinx-gallery/sphinx-gallery#227 . Working on a PR.
