### ISSUE TITLE
Astropy units do not convert correctly with `np.array`

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#6008]
Compare:

```python
>>> import astropy.units as u
>>> import numpy as np
>>> a = 3600 * u.s
>>> b = 1 * u.h
>>> ratio = a / b
>>> float(ratio)
1.0
>>> np.array(ratio)
array(3600.0)
```

**Comment by pllim** [comment]
Not sure if this is a bug... By casting Numpy array, you are effectively throwing away unit information. The proper way to do this is to cast it to unitless first.

```python
>>> ratio
<Quantity 3600.0 s / h>
>>> x = ratio.to(u.dimensionless_unscaled)
>>> x
<Quantity 1.0>
>>> np.array(x)
array(1.0)
```

**Comment by pllim** [comment]
Although `float()` did do that for you... @mhvk ?

**Comment by mhvk** [comment]
@MaxNoe - as @pllim noted, `np.ndarray` specifically just takes the base values and turns it into an array; it is equivalent to `ratio.view(np.ndarray)`. I don't think this can be solved without breaking other things -- lots of `np.asarray` in the numpy code, and in some places we manage to get our units back correctly. Given this, I removed the `bug` label. I guess the main question is whether it would help to document this, and, if so, where.

p.s. I guess what could be argued is that for `float` we should similarly have just passed on the value. The difference is that with `float` we do have an easy way to override what it does (via `__float__`).

p.p.s. In my usage, I've found that by far the easiest is just to continue using quantity everywhere, i.e., convert as little as possible to/from arrays/scalars.

**Comment by MaxNoe** [comment]
Sorry but no.

Breaking `float` in the same way `np.array` is broken is just wrong. I don't know how, but other unit libraries get this done correctly:

I do not know if this is solvable. There should at least be a warning if this happens. 

FYI: https://pypi.python.org/pypi/Pint/ suffers from the same problem

**Comment by mhvk** [comment]
@MaxNoe - can you point me to a library that does convert to dimensionless when doing `np.array(quantity)`? I suspect the do not subclass `ndarray` and use __array__` to force dimensionless, but I'd be interested in seeing if that is indeed the case (even though, as said, I'm not sure that even if we could do it, we would, since it would, I think, break quite a lot of other parts).

**Comment by pllim** [comment]
Shall we mark this as "won't fix" and close?

**Comment by pllim** [comment]
p.s. And maybe with a note in the docs saying that this is not supported?

**Comment by bsipocz** [comment]
👍 to add this to the known issues and close

**Comment by pmplewa** [comment]
This works as expected though:
```python
>>> np.array([ratio])
array([ 1.])
```

**Comment by pllim** [comment]
@mhvk can you comment on why `np.array([ratio])` works? Is it one of your `ufunc` magic?

**Comment by pllim** [comment]
Documentation update in #6048

**Comment by mhvk** [comment]
It must be that if it is inside a list, `np.array` doesn't first check whether something is array-like, but just tries `int`, `float`, etc., on it. But I'd need to look at the source code to be sure... In any case, it is not general -- it does not work for quantity arrays:
```
In [2]: q = np.arange(10)*u.percent

In [3]: np.array([q])
Out[3]: array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [4]: q = 1 * u.percent

In [5]: np.array([q])
Out[5]: array([ 0.01])
```
