### ISSUE TITLE
Make `Mapping` and `Identity` fittable"models

### ISSUE THREAD

**Issue by nden** [astropy/astropy#6012]
Currently `Mapping` and `Identity` are not "fittable" . This makes compound models whic include them not "fittable".  @jehturner

**Comment by jehturner** [comment]
@pllim has fixed the `fittable` attribute in #6018 (thanks) but there are still cases where compound models including Mapping or Identity don't work, for some other reason:
```
from astropy.modeling.models import *
from astropy.modeling.fitting import *
import numpy as np

fitter = LevMarLSQFitter()

# Using order (1, 1) here doesn't change anything:
simple = Chebyshev2D(2, 2)
compound = Mapping((0, 1, 1)) | Chebyshev2D(2, 2) & Identity(1) \
           | Mapping((0,), n_inputs=2)

y, x = np.mgrid[0:3, 0:3]
z = x + y

simple_fit = Mapping((0, 1, 1)) | fitter(simple, x, y, z) & Identity(1) \
             | Mapping((0,), n_inputs=2)
simple_z = simple_fit(x, y)
print(simple_z)

# [[ -3.75941525e-31   1.00000000e+00   2.00000000e+00]
#  [  1.00000000e+00   2.00000000e+00   3.00000000e+00]
#  [  2.00000000e+00   3.00000000e+00   4.00000000e+00]]

compound_fit = fitter(compound, x, y, z) 
compound_z = compound_fit(x, y)
print(compound_z)

# [[ 0.  0.  0.]
# [ 0.  0.  0.]
# [ 0.  0.  0.]]
```
Even if I initialize the starting `Chebyshev2D` model with, say, `c0_1=0.9` and `c1_0=1.0`, the fitter doesn't change the coefficients at all (when they should end up at 1.0).

**Comment by jehturner** [comment]
I think the remaining problem here is quite a general one for compound models in more than one co-ordinate. Simpler cases like `Identity(2) | Chebyshev2D(2, 2)` also fail to set any coefficients, even though `Chebyshev2D(2,2)` does work with the same fitter on the same data. I suppose I'll put in a new issue for this?

**Comment by pllim** [comment]
> I suppose I'll put in a new issue for this?

This issue is closed, so you can mention this in one of your already open issues (if relevant) or open a new one.
