### ISSUE TITLE
Introduce `Model.separable`

### ISSUE THREAD

**Issue by nden** [astropy/astropy#6013]
Add a new boolean attribute, `separable` to simple models. `Model.separable` will indicate whether the inputs to a model are separable or not. This is used in GWCS to compute the separability of axes, e.g. spectral and spatial.

**Comment by pllim** [comment]
@nden , which models exactly? The issue is kind of vague on actual implementation details.

**Comment by nden** [comment]
@pllim I don't see why not add the attribute to all models although the ones I am currently interested in are those used in gwcs - polynomials, rotations, projections. If the axes are independent/separable then the attribute is set to True.

**Comment by cdeil** [comment]
If you add it, maybe call it `is_separable`, to make it a little clearer that it's a boolean property?

**Comment by pllim** [comment]
@cdeil , it makes sense but probably not applicable in this case since in `core.py`, there is already precedence of `linear=True`, `fittable=False`, etc (boolean variables without `is_` prefix).
