### ISSUE TITLE
We need a documentation page for how to use the "greater documentation ecosystem"

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#6017]
It should be prominent on the main page and should describe the vision for the documentation, examples gallery, and tutorials.

cc @eblur @kelle @eteq

**Comment by bsipocz** [comment]
Is this an issue for the astropy core, or more like to the main webpage? I feel the latter and thus suggest to move the issue to that repo.

**Comment by pllim** [comment]
Manually moved to astropy/astropy.github.com#311
