### ISSUE TITLE
MatrixTransforms could become AffineTransforms to support MatrixTransform + offset

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#6022]
We could imagine abstracting most of the current `MatrixTransform`'s into `AffineTransform`'s with 0 offset. This would allow us to specify more of the transformations using simple matrix algebra. This would (a) make the velocity frame transformations easier to implement without needing to do numerical differentiation through the transform paths, and (b) it might speed up some of the current function transforms (which I think can mostly be implemented as affine transformations instead). 

cc @eteq @mhvk

**Comment by mhvk** [comment]
Anything to avoid numerical differentiation...  But not quite knowing where/how this would be used, I cannot comment much -- do you have a specific example?

**Comment by adrn** [comment]
One example would be the `ICRS` to `Galactocentric` transformation. Forget about velocity frame corrections for a second and just think about the basis orientation. Right now the transform is implemented as a `FunctionTransform` because it involves a rotation and an offset / origin shift so it can't be either of the `MatrixTransform`'s. Because of this, we can't easily transform velocities to the `Galactocentric` orientation because the transform returns an instantiated frame. If we went with affine transformations instead, the transform could have a `.matrix` or whatever attribute that we could pull out to do differential transformations. There might be a thinko here, but @eteq thinks that's the case for many of the `FunctionTransform`'s.

**Comment by adrn** [comment]
Just brainstorming here, and this might be crazy, but we could imagine using the same transform functions for position and velocity transforms and allowing the `AffineTransform` class to have different offsets for representations vs. differentials. For example, sticking with `Galactocentric`, converting a position alone would rotate and shift to the Galactic center. Converting a velocity could do the same rotation, but would then shift by removing LSR + Solar velocity vectors (defined as frame attributes).

**Comment by mhvk** [comment]
Ah, yes, that makes sense; an expanded transform class that has associated "differential transformations" would seem to help here. I'll need to look a bit more closely at the current implementation to think how this could be done.

**Comment by adrn** [comment]
This was added in #6218
