### ISSUE TITLE
Add permissions check to setup.py

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#6035]
This idea was suggested by @bsipocz in https://github.com/astropy/astropy/pull/5640#issuecomment-289449179 - the idea is that in some part of the build process, ``setup.py`` should ensure that the permissions are correct for various relevant files.  An example of how this can bite us is in #5912 , which required a new release (1.3.2) to fix. 

One thing I don't understand (maybe @bsipocz or @cdeil or others can clarify): how would we do this automatically?  Do we just want to ensure all files are all-readable?  It's at least *possible* that someone *meant* to put a specific file with a specific set of permissions for a good reason, right? If so, then it might be that this should be something the "sdist" command triggers, or something like that.  Or even just a doc change to tell the release manager to run some tool to check this.

**Comment by bsipocz** [comment]
I'm closing this probably should be done in  astropy-helpers where there is already a related issue for it https://github.com/astropy/astropy-helpers/issues/294
