### ISSUE TITLE
add molar mass equivalency

### ISSUE THREAD

**Issue by parkus** [astropy/astropy#6040]
I think the equivalency between amu and g/mol should be shipped along with the other predefined equivalencies in future versions. (Sorry I'm lazy and didn't want to fork, modify, pull request, etc...)

Something like
`molar_mass = [(u.u, u.g/u.mol, lambda x: x, lambda x: x)]`

I used just `lambda x: x` instead of `lambda x: x*const.N_A/u.mol` for better numerical accuracy, as I believe that 1 amu = 1 g/mol [by definition](https://en.wikipedia.org/wiki/Unified_atomic_mass_unit) and the latter produced a very small difference.

**Comment by parkus** [comment]
Though perhaps if the two are identical by definition then this doesn't even belong in equivalencies and is just a conversion that should happen automatically?

**Comment by pllim** [comment]
I found this formula in http://physics.nist.gov/cuu/pdf/nonsi_2006.pdf
```
1 u = 1 g/mol / N_A
```
So, effectively in Astropy, it can be the following?
```python
>>> from astropy import units as uc
>>> from astropy import constants as const
>>> 1 * (u.g / u.mol) / const.N_A
<Quantity 1.6605389210321898e-24 g>
>>> x = 1 * u.u
>>> x.to(u.g)
<Quantity 1.6605389209999996e-24 g>
```

**Comment by parkus** [comment]
Yes, it can. Are you saying it shouldn't be an equivalency shipped with Astropy? I have no strong opinion, it's just one that I've been working with a lot lately. 

Also, I realized if `1 u = 1 g/mol / N_A` is added, then the more fundamental `1 mol = N_A` should be as well.

**Comment by mhvk** [comment]
Hmm, at first I thought this was trivial, but reading NIST further, `mol` is by definition a fundamental unit in SI, which only has meaning if one also specifies a type of substance; so that suggests it should be left as is. I think the equivalency may in fact be the way to go (note that you don't have to give the functions if the two units in the list are equivalent without further scaling).

**Comment by pllim** [comment]
@mhvk , are you talking about adding a *new* equivalency in Astropy, or simply *documenting* that it can be done as such without code change?

**Comment by mhvk** [comment]
Definitely document it, but I think this is a general enough one that we might as well have it as a new equivalency. @parkus - now that you've got "pre-approval", would you be up to making a PR?

**Comment by parkus** [comment]
I'm torn, as my delayed reply suggests. I want to contribute, but I'm in the "throes of dissertating" (for my phd) currently, and I suspect that this, although it should probably only take me a few hours, will more likely end up burning a day I don't have because I am a github noob and have only made one other PR years ago. So I think I should decline

**Comment by mhvk** [comment]
@parkus - no problem, this will not be that much work! I'll label it as "novice", since the solution is essentially described in this thread.

**Comment by katipallya** [comment]
I'd like to get this done!

**Comment by katipallya** [comment]
@mhvk I see no equivalences for amounts of substances in equivalencies.py. Am I missing something here, or does an entire function need to be added?

**Comment by mhvk** [comment]
@katipallya - yes, you would need to add a new equivalency, add one or two tests in `astropy/units/tests/equivalencies.rst` and describe it in the documentation `docs/units/equivalencies.rst` (tests and documentation can be quite brief, since this is a simple equivalency, that doesn't even need functions).
