### ISSUE TITLE
Remove old "known_issues" from docs

### ISSUE THREAD

**Issue by kelle** [astropy/astropy#6049]
Lots of very old "known issues" listed in the docs

http://docs.astropy.org/en/latest/known_issues.html  (updated stable-->latest)

**Comment by pllim** [comment]
FYI -- In this case, it does not matter but whoever opening a PR should really be looking at http://docs.astropy.org/en/latest/known_issues.html , which reflects the `master`.

"stable" reflects the last public release.

**Comment by pllim** [comment]
Perhaps we can wait till v3.0? My reasoning is because then we can also remove Python 2 issues.

**Comment by bsipocz** [comment]
What about doing it before every release? Some of the known issues might go away occasionally. E.g. astropy 0.2 stuff can be removed, etc.

**Comment by pllim** [comment]
@bsipocz , sure. In that case, it has to be part of the release procedures.

**Comment by pllim** [comment]
Or... contributing instructions... Wherever is appropriate.

**Comment by bsipocz** [comment]
Hmm, maybe not part of releasing, but as I recall there a release checklist before (in issues), that involved writing the ``what's new``, etc.

**Comment by pllim** [comment]
Well, there is a "whatsnew needed" tag...
