### ISSUE TITLE
Reduce file size for lupton_rgb examples

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6062]
At the moment, the ``docs/visualization/lupton_rgb.rst`` docs rely on downloading 60MB of data, which is clearly unecessary given the final resolution of the image produced. This is painful on airport WiFi... We should reduce the size of the FITS files to no more than 1MB each at the very most.

**Comment by bsipocz** [comment]
Clearly an oversight, thanks for spotting it.

**Comment by giang-nghg** [comment]
@bsipocz I'd like to fix this but I don't quite understand the issue. Does it mean we should change the parameters for `make_lupton_rgb` to generate smaller images in the example?

**Comment by astrofrog** [comment]
@giang-nghg - I fixed this in https://github.com/astropy/astropy-data/commit/5b0de07e441c5966c0497ef23836f5cdf532c099 (it required changes in another repository which is not well documented so I thought it would be easier to just do). This involved shrinking a bunch of FITS files.
