### ISSUE TITLE
ddof option for sigma_clipped_stats

### ISSUE THREAD

**Issue by ysBach** [astropy/astropy#6066]
**Situation**
Currently the `sigma_clipped_stats` returns the standard deviation given by something like "sqrt of variance / number of data", i.e., `sqrt( sum((x - mean(x))**2)/len(x)) )`. 

**Suggestion**
I think it's better to put an option to get `sqrt( sum((x - mean(x))**2)/(len(x)-ddof)) )`, with `ddof=1` for most cases.

**Justifying the Suggestion (1): Theory**
The unbiased estimator of the population variance *when we are estimating **both** mean and variance* has `len(x)-1` in the denominator rather than `len(x)` [1-3]. The "uncorrected" `std` can have meaning when we are dealing with sample that are from normal (this is the only case which justifies the use of the uncorrected `std`, AFAIK).

In short, what we have to use for estimating **both** mean and standard deviation is this "corrected" value (which is mostly the case for me, but not very sure for other astronomical fields). It's also called the Bessel correction. To estimate the standard deviation, not variance, we still need some case-by-case mathematical trick (no general solution can be obtained: see the last part of [1] and the last sentence of [3]). But the most widely used way is to divide the variance by `len(x)-1` [3], and just take a square root to find the sample standard deviation (`s`) and make a "Student-t" statistic.

**Justifying the Suggestion (2): Practical**
I think it is quite bothersome to obtain the "corrected" `std` from user's side, because the number of clipped data (the `len(x)`) is not given as output. 

**Suggestion (Concept Sketch)**
So I suggest to add one optional keyword to `sigma_clipped_stats`, say `ddof`, with default value `0` (for backward compatibility) and change
```
std = np.ma.std(data_clip, axis=axis)
```
to
```
std = np.ma.std(data_clip, axis=axis, ddof=ddof)
```
from `sigma_clipped_stats`.

The documentation might contain some docstring like
```python
'''
    ddof : int, optional
        The Delta Degrees of Freedom for `numpy.std`. The output standard
        deviation will be corrected by a factor `N/(N-ddof)`, where `N` is
        the total number of sigma-clipped data. Use `ddof=0` when the data
        are surely from Gaussian normal distribution. Otherwise, use 
        `ddof=1` to obtain an unbiased variance estimator for inferring
        the standard deviation. 
'''
```

**References**
(I referred only those accessible from on-line)
[1] [This wiki section](https://en.wikipedia.org/wiki/Unbiased_estimation_of_standard_deviation#Background)
[2] The "caveat 3" of [this wiki section](https://en.wikipedia.org/wiki/Bessel%27s_correction#Caveats) 
[3] Paragraph 2 of [this numpy documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html)

**Comment by larrybradley** [comment]
Thanks, @ysBach.  Added in #6207.
