### ISSUE TITLE
Simplify python interface to liberfa

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6073]
This may also go into `erfa` itself, but it should be possible to simplify the generation of the python interface to erfa, possibly doing away with the large template, and possibly auto-generating the files on the fly (thus reducing the memory load and speeding up initialization for those who do not use `Time` and `SkyCoord` enough to care about `erfa`).

These ideas were partially implemented in #3181, but that project got stalled.  This is a reminder to think about this...

**Comment by embray** [comment]
One possibility would be to use the existing generfa script (or whatever it's called) to just generate the interface specifications and from that use cffi/ctypes to actually supply the interface.

**Comment by mhvk** [comment]
With the ufunc wrappers, no longer as relevant and, anyway, should now be done in `pyerfa` - https://github.com/liberfa/pyerfa/issues/37
