### ISSUE TITLE
Table comments metadata headache when writing to both FITS and ASCII

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6079]
This is a follow-up of #6055.

`t.meta['comments']` does not translate well to FITS header. It creates
```
COMMENTS= 'Blah blah'
```
when I really want
```
COMMENT = 'Blah blah'
```

but when I use `t.meta['COMMENT']`, it works for FITS but ASCII output does not include it as a comment line.

**Comment by saimn** [comment]
For the second example I think you mean `COMMENT Blah blah`, i.e. the "real" fits comment. For fits, it works transparently with `COMMENT` because setting this in the fits header will convert it to a comment card. For `io.ascii`, `t.meta['comments']` must be a list but you can also set a string and it will crash when writing the file (with fits both string and list work).

**Comment by pllim** [comment]
Actually in the code, it is set to a list anyway, and FITS is okay with that. But I can't get past `COMMENT` vs `COMMENTS` in the FITS header.

**Comment by taldcroft** [comment]
Yes, I think this is a bug in the connect code, specifically [this section](https://github.com/astropy/astropy/blob/878184fb3f987f325b44687f9eda27f577330c92/astropy/io/fits/convenience.py#L525) that handles `meta`.  It should be special-casing `'comments'` and converting that to `comment`.  I think from there it would get correctly written out with a list of `COMMENT` fields.

Perhaps in the try/except below you could do:
```
if key == 'comments':
    key = 'comment'
table_hdu.header.append((key, item))
```
To be clear, the standard for astropy Table meta is that `comments` a special key that is a list of comments.  This should round-trip through file formats which support comments.

**Comment by saimn** [comment]
Right, but then the same should be done in the reading code: https://github.com/astropy/astropy/blob/878184fb3f987f325b44687f9eda27f577330c92/astropy/io/fits/connect.py#L167

**Comment by taldcroft** [comment]
I unassigned myself as this is not fundamentally a Table issue and does not require much expertise to fix.

**Comment by giang-nghg** [comment]
I made a fix following @taldcroft and @saimn suggestions. Please review if there's anything missing. Thank you.
