### ISSUE TITLE
_UnitRegistry doesn't know about physical types of composite units

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#6093]
I just found a bug in `astropy.units` that significantly hampers the functionality added in #3847 ...

Apparently, the `_UnitRegistry` object doesn't know about physical types of composite units:

```python
>>> from astropy.units import get_current_unit_registry
>>> ureg = get_current_unit_registry()
>>> ureg.get_units_with_physical_type(u.m)
{Unit("ym"),
 Unit("zm"),
 Unit("am"),
 Unit("yearthRad"),
 Unit("yjupiterRad"),
 Unit("ysolRad"),
...etc
```

But doing the same for, e.g.,:
```python
>>> ureg.get_units_with_physical_type(u.m/u.s)
set()
>>> ureg.get_units_with_physical_type(u.kg/u.m**3)
set()
```

I think the concept of "physical type" could use an overhaul, but that is a big change and should probably get pushed to v3.0. But for v2.0, we need to find a solution to support these physical type lookups from the unit registry. This might require some hacking of the `_UnitRegistry.add_enabled_units()` method.

BTW: We didn't see this in the tests for #3847 because the physical types I used all resolved to irreducible units.

cc @mhvk

**Comment by adrn** [comment]
BTW: for combinatoric reasons, it's no obvious to me how to actually "fix" this...e.g., for a speed, any valid length unit / any valid time unit would be an equivalent speed unit. Only gets worse for momentum, energy, and other composite units with several irreducible components.

**Comment by mhvk** [comment]
@adrn - I think the easiest fix for #3847 is to directly convert the physical type to a unit (possibly, via a `Unit._from_physical_type_id` classmethod? or just in your `quantity_input`). Something like:
```
bases = [u.Unit(base) for base, _ in physical_type_id]
powers = [power for _, power in pt]
if len(physical_type_id) == 1 and powers[0] == 1:
    unit = bases[1]
else:
    unit = u.CompositeUnit(1, bases, powers)
```

**Comment by adrn** [comment]
@mhvk good idea!

**Comment by mhvk** [comment]
p.s. I don't really know what to do about the larger question: as you write, it becomes a combinatorial explosion. My own sense is that it is better first to get the systems in place, so that it becomes possible to get a *preferred* unit for a given physical type. I have never found myself needing a list of *possible* units...

**Comment by mhvk** [comment]
@adrn - I'll remove the 2.0 milestone from this, since I don't think we have a good solution, while the reason for hurry is solved in #6095.

**Comment by adrn** [comment]
Yes, sounds good!

**Comment by mhvk** [comment]
closing given the combinatorial explosion mentioned in-line
