### ISSUE TITLE
Integrate Python 3 compatibility functions

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#61]
The Python 3 compatibility hacks in wcs, vo and fits should be merged.  This will also form the basis for use by future code.

Since io.fits aka pyfits probably has the largest amount of this kind of stuff, it probably makes sense to do this after fits is merged in.

**Comment by astrofrog** [comment]
Would be nice to do, but not critical for 1.0 so removing milestone.

**Comment by bsipocz** [comment]
I'm closing this now as there is light at the end of the tunnel already as we will get rid of py2 from master in a few months. Removing python 2 related stuff is a slightly different issue.
