### ISSUE TITLE
Handle (title, name) in dtype when initializing Table from an ndarray

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#610]
Currently the Table class will drop the `title` if an input ndarray specifies titles for column dtypes (see [1](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html#specifying-and-constructing-data-types) for spec).  This stems from using `data.dtype.names` as the source of the array field names if not provided explicitly.

This is related to issue #525 and PR #609.  This issue is partly a placeholder to decide how to handled this.  As noted by @mdboom it might not be trivial to correctly handle all cases, but at the least a warning might be issued indicating that title info is being lost.

cc\ @astrofrog

**Comment by bsipocz** [comment]
I think this is obsolete now and can be closed. 

@taldcroft?

**Comment by taldcroft** [comment]
Yes, obsolete now, or at least nobody has been bothered by this in 6 years.
