### ISSUE TITLE
Typo in add_enabled_units error?

### ISSUE THREAD

**Issue by duncanmmacleod** [astropy/astropy#6101]
I think I've come across a typo in an error message in [`astropy.units._UnitRegistry.add_enabled_units`](https://github.com/astropy/astropy/blob/v1.3/astropy/units/core.py#L200) (astropy-1.3 from pip):

```python
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/units/core.py", line 203, in add_enabled_units
    "enabling them.".format(st))
ValueError: Object with name 'h' already exists in namespace. Filter the set of units to avoid name classes before enabling them.
```

Should this error read 

> Filter the set of units to avoid name *clashes* before enabling them

? If so I can easily post a PR to fix.

**Comment by pllim** [comment]
Sure, your suggestion makes sense. Thanks!
