### ISSUE TITLE
Have a Quantity.set_unit method

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6106]
From discussion in #6098, it appeared it might be nice to have `set_unit` method, probably with an argument that allows one of:
1. Change the unit only if it doesn't require changing the values (eg., `km/s` -> `m/ms`; but also, with equivalencies set, `radian` -> `dimensionless`.
2. Change the unit and adjust values in-place if necessary.
3. Override the unit.

I'm not complete sure whether we want (3) at all, since at some level the whole point of `Quantity` is never to do this. In the docstring, we could still mention that if one really wants this, all one has to do is
```
q = q / q.unit * new_unit
```
(which is quite fast, as no copies of the data get done)

An alternative to (2) would be to have an `inplace` (or `out`) argument for `Quantity.to`.

**Comment by ngoldbaum** [comment]
I noticed this while trying to make a benchmark comparing `unyt` (a new library I'm working on based on `yt.units`), `Pint` and `astropy.units`. For what it's worth, both `Pint` and `unyt` support in-place conversions via `ito` and `convert_to_units`, respectively.

I'll let you know more about the benchmark results once they're ready :)

**Comment by mhvk** [comment]
Thanks for letting me know! My main hesitance really is that in actual use I've found I rarely if at all need specific units - the important thing is that units are properly tracked! But if we go for it, we might as well try to use a consistent method name.

Anyway, would be good to hear about benchmarks. For `Quantity`, please do be sure to use numpy >=1.13, as with `__array_ufunc__` `np.sin`, `np.exp`, etc., are about twice as fast.

**Comment by ngoldbaum** [comment]
Yup, to keep the codebase simple I'm just requiring numpy >= 1.13 for now.

**Comment by mhvk** [comment]
closing since we now can do in-place change of units via `q <<= <new_unit>`
