### ISSUE TITLE
Have default `repr` for [Q]Table show column classes

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6107]
In #6098, @taldcroft suggested (https://github.com/astropy/astropy/issues/6098#issuecomment-302536830) that it might be useful to have the default `repr` for tables show the classes of any mixin columns.

**Comment by apooravc** [comment]
@mhvk So we've to show the class of a column only when an instance of QTable is called and the column has a defined unit. I tried adding another `yield` statement under `if show_unit:` in `_pformat_col_iter` in for latter case but it's yielding also cases where unit is not defined. I also tried checking if `self` is instance of QTable by trying to `import QTable` there, it says it can't.

**Comment by mhvk** [comment]
@apooravc - I must admit I don't quite recall the various reasons; it may be @taldcroft suggestion was to list non-`Column` classes. But perhaps an even better (and easier?) solution would be to generally list all column classes, except in the case that all columns have the same class.

**Comment by taldcroft** [comment]
Yeah, let's try to move forward on this and find something that will work.  Of course we don't want to make the output too cluttered with redundant info that can make the table repr *less* easy to read.

But maybe we should not try to be too clever, and just show the column class for any mixins, i.e. anything but Column and MaskedColumn?

**Comment by mhvk** [comment]
A quick look at this PR with a "novice" showed it was not that trivial to find *what* to change. 
From a quick look, I would guess the changes are all in `pprint.TableFormatter`. In particular, it would seem `_pformat_col` would get a new `show_cls` argument that, if `True`, adds the class name in a separate row (can be modeled on `show_unit`), replacing standard `Column` and `MaskedColumn` with an empty string. And then `_pformat_table` would need the same argument, with a default of `None` - for this case, it would set `show_unit` to `True` if there are any mixin columns and if those are not all the same.

**Comment by yashkmr99** [comment]
I'd like to work on this if its not taken.

**Comment by yashkmr99** [comment]
Hi, I'd like to work on this if its not taken. I might need help though.

**Comment by taldcroft** [comment]
@yashkmr99 - I actually agree with @mhvk that this was probably mislabeled.  I suspect the final code change won't be that big, but I wrote most of the code and I'm not immediately sure what has to be done.  Can I suggest you head on over to #8522?  That will be relatively straightforward!
