### ISSUE TITLE
Proposal to add mentor-available label for open issues

### ISSUE THREAD

**Issue by sosey** [astropy/astropy#6110]
I would like to propose adding a "mentor-available" label for use with issues. This would be in addition to the package-*  level labels. It would create positive reinforcement for contributors, especially for new contributors, or those new to astronomy, who are interested in being a part of the project. 

Mentors would not necessarily have to be package maintainers, but they would agree to provide a positive and guiding experience for contributors tackling the issue that they have agreed to mentor.

**Comment by bsipocz** [comment]
While the motivation for this is great, I'm -1 on introducing it to this repo due to logistic concerns. 
 - Can we guarantee that mentor volunteers will be available long term on an issue (as we all know issues tend to stay open for a very long time), or even at the moment (in a few days) when a new contributor shows up? 
 - Another issue is that only maintainers can add and remove labels, so keeping track of this is probably not the best use of their time.

Also I feel that we were very supportive to any newcomers who picked up a package-novice issue (even when flooded with PRs by aspiring gsoc students), can't really see that it will be better with adding more labels. 

On the other hand, if there is anyone out there willing to mentor, I suggest to either watch the repo or subscribe to individual issues they willing to mentor, so they get notified and can step in when there is any related activity.

**Comment by mhvk** [comment]
@sosey - I think I agree with @bsipocz about the practicality of your specific suggesion, but feel we should do something... Right now, we urge people starting on a `package-novice` item to contact `astropy-dev` for help (see http://docs.astropy.org/en/latest/development/workflow/development_workflow.html); might it be an idea to add the alternative of requesting help from one of the sub-package maintainers by at-marking them? (If so, we need to add a link to that page, and ensure our github ids are listed there). That may feel a bit less intimidating that mailing a list.

At a very minimum, I guess we could explain that if one writes in an issue that one is willing to work on it, the people who raised and commented on the issue will be automatically notified -- I don't think this is all that obvious if one hasn't used github before.

**Comment by sosey** [comment]
I think these are good points and appreciate all your comments.  If labels are not the best way to go, then I think updating the documentation to make it a little more clear that positive support will always be provided would be good. The specific contributors I was thinking of were those who felt they couldn't judge where their ability level really was, or became frustrated because they wanted to make a contribution but had become discouraged personally because they felt their questions might be too basic, or feel that asking for help is a failure.   I've heard that the current wording we have could be improved in this respect.  I was trying to think of a proactive way of combating this which was a little less obtuse to those unfamiliar with the astropy packages or github, or who are looking to help solve issues which were opened by others (for example during sprints). Sometimes it can be  a bit daunting to email a "dev" list. Perhaps a combination of updating the docs as suggested by @mhvk, in addition to  adding a link or friendly text about contributing to the readme on the git master - even just a link to here: http://www.astropy.org/contribute.html would help.  People who would like to take a more proactive role as a mentor could also make a comment on the issue to that affect, which is a little more visible and encouraging than just watching the repo and takes away some  of the decision process of 'who should I contact for help'. Adding a comment also gives someone the ability to put a time frame around their offer, for example "sprinting at scipy! anyone who would like to work on this issue can find me <>". Especially for devs attending sprints, offering to collaborate directly with someone interested in working on any level of issue can be beneficial to both parties.

**Comment by mhvk** [comment]
@sosey - I like the idea of the link on contributing in `README.rst`. Do you want to make a PR implementing the suggestions?

**Comment by pllim** [comment]
Maybe the "project" feature can be used for a sprint... 🤔

**Comment by bsipocz** [comment]
Good idea. However the "project" is also only editable by maintainers.

**Comment by sosey** [comment]
@bsipocz re sprinting, yah.  Anyways, sure, i'll submit a PR for the `README.rst` update.
