### ISSUE TITLE
Numpy dev tests failing horribly on Travis

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6114]
https://travis-ci.org/astropy/astropy/jobs/235568942

Feel free to close if this is a duplicate of something else.

**Comment by saimn** [comment]
Same as #6086 I think.

**Comment by pllim** [comment]
Ah, okay. For some reason, I thought that was related to Numpy pre-released tests that are now allowed to fail (temporarily). I will close this. Thanks!

**Comment by bsipocz** [comment]
@pllim - #6090 addresses these failures, but @mhvk suggested to hold that back for a bit as numpy upstream may change things back.

**Comment by pllim** [comment]
@bsipocz should we allow numpy dev to fail for now, then?

**Comment by bsipocz** [comment]
It's allowed to fail on pushes, but not on cron builds. I think it's fine this way, but if it bothers you, it can be move it to the allowed failures, too.

**Comment by pllim** [comment]
No, that's fine. It was just a bit shocking to see 5 failed builds in a row on `master` at a glance.

**Comment by mhvk** [comment]
Yes, discussion is still on-going at https://github.com/numpy/numpy/pull/9143 and https://github.com/numpy/numpy/pull/9139...
