### ISSUE TITLE
Sphinx build package requirements are incomplete

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#6120]
The listed [requirements for building the sphinx docs ](http://astropy.readthedocs.io/en/latest/install.html#building-documentation) are incomplete:  

- Sphinx (and its dependencies) 1.0 or later
- Graphviz
- Astropy-helpers (Astropy and most affiliated packages include this as a submodule in the source repository, so it does not need to be installed separately.)
- Pillow
- (optional) sphinx-gallery

At the very least one also needs PyYaml and presumably matplotlib (for the plot directives), but maybe more?  Here is `pip-requirements-doc`:
```
Cython>=0.21
jinja2
pyyaml
scipy
pandas
h5py
beautifulsoup4
bleach
jplephem

# below here are used only for tests
skyfield
mpmath
```
This does not include matplotlib which I find confusing, but anyway, someone who understands the doc building process in detail could probably update the list of requirements in the sphinx docs.

**Comment by bsipocz** [comment]
@taldcroft - I'm not sure we use the ``pip-requirements-doc`` anywhere, so it's very likely that it can go out of sync. In theory the full list is available in ``.rtd-environment.yml``

**Comment by taldcroft** [comment]
Ah, that's very useful!  One curiosity is that I got an import error when I tried to build without PyYaml installed.  Does that seem right?

**Comment by taldcroft** [comment]
Do we formally support building docs on Py2 now?  It is not tested...

**Comment by bsipocz** [comment]
@taldcroft - It should still work I believe, but to save on CI time we don't build it.  The RTD build uses python 3.5, too. I'm not sure whether we formally say we don't support it, but probably don't guarantee it either. Pinging @eteq for this.

**Comment by bsipocz** [comment]
Re pyyaml: indeed it's listed for the travis build as dependency:
``'Cython jinja2 scipy h5py matplotlib pyyaml scikit-image pandas pytz beautifulsoup4 ipython mpmath'``

It looks like that RTD installs mkdocs and thus PyYAML independently of our env file, thus we never run into these issues.

**Comment by bsipocz** [comment]
I think, I've misread this issue at the first time and now wonder whether you indeed though about the RTD install, or rather the docs page. If the latter, then in my reading, you need all the optional dependencies AND in addition the 4/5 things listed there.

As for the RTD requirement file, I've not copied the same dependency list we use for travis, so even when some of these are not used in the docs examples we are self consistent.

**Comment by bsipocz** [comment]
good find @pllim, I would have though we've fixed this.
