### ISSUE TITLE
Table unicode sandwich follow-up: changelog and What's New clarification

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#6138]
From https://github.com/astropy/astropy/pull/5700#issuecomment-304972159 :

I guess one possibility then would be to indicate in the changelog and What's New that if comparison with str instead of bytes is a problem -- and bytes is really more logical -- to raise an issue rather than necessarily change one's code.

**Comment by pllim** [comment]
Trying to get the low hanging fruits marked for v2. See #6214.
