### ISSUE TITLE
Give to_value methods to Column ~and TimeDelta~?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6148]
Inspired by https://github.com/astropy/astropy/pull/6137#issuecomment-305306197: now that `Quantity` gained a `to_value` method, which turned out to be quite valuable, should `TimeDelta` and `Column` acquire the same method, so they can duck-type for quantities in more situations. Probably, no reason not to.

EDIT: `TimeDelta.to_value` was done in #8762

**Comment by eteq** [comment]
👍  for `TimeDelta` ... less sure about `Column`, though: I wonder if instead we should tell everyone to use `QTable` if they want that functionality, rather than making `Column` more franken-Quantity?

**Comment by taldcroft** [comment]
I agree completely with the comment by @eteq.  I would even go so far as to consider deprecating `Column.to` eventually and making `Column` less of a franken-Quantity.  Definitely when `Quantity` supports masking and can do anything in a table which `Column` can do, then we should deprecate and finally remove `Column.to`.

**Comment by mhvk** [comment]
I think I also agree, Column really is not meant to be like a Quantity, while TimeDelta in many ways is a Quantity with time units that just happens to have internal state and be much more precise. It has been very useful for me to be able to treat it as such, i.e., have `q / td` produce a quantity. So, probably giving it a `to_value` as well is fine.

**Comment by mhvk** [comment]
`TimeDelta.to_value` now exists (#8762); `Column.to_value` remains to do...

**Comment by mhvk** [comment]
I'll close this issue as we've done `TimeDelta.to_value`, which everyone agreed was a good idea, and there also seemed to be consensus that the remaining item, `Column.to_value`, was *not* a good idea,
