### ISSUE TITLE
Update installation documentation 

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#6154]
One suggestion made in #6051 was to update the installation section of the documentation to focus on anaconda for new users; see https://github.com/astropy/astropy/pull/6051#issuecomment-301335291 for the one idea for doing that. It was clear this topic needed more discussion, so was dropped in #6051.

The purpose of this issue is to remind to update the installation documentation at some point..

**Comment by pllim** [comment]
I doubt anyone is going to get this done by tomorrow, so removing milestone.

**Comment by bsipocz** [comment]
@pllim - docs and bugfixes can be backported before the actual release.

**Comment by bsipocz** [comment]
This is actually a duplication of #1807, but I go ahead and close that one as it's burried under tons of other issues.

**Comment by kakirastern** [comment]
Hi @KING-SID, I have opened a PR #8385 to address this issue regarding the development workflow parts... Maybe this issue is overlapping with Issue #7287 as well as Issue #8289, as the installation with Python 2.x is being phased out and Python 3.x is now the default version?

**Comment by kakirastern** [comment]
@KING-SID So a PR can be opened that deals with installation issues in other areas of the [AstroPy website](http://www.astropy.org/), as long as it is not part of development workflow... at least for now, as I am working on it.

**Comment by KING-SID** [comment]
Hey @kakirastern , thanks for letting me know. I just wanted to clarify that I am focusing on this page: [http://docs.astropy.org/en/stable/install.html] and not the development work flow, so don't worry about that. I believe we are working on two different things as you are working on the development workflow documentation and I am working solely on the installation of the astropy package for first time users. Let me know if I misunderstood what you said.

**Comment by kakirastern** [comment]
Hi @KING-SID, sure... but I am not sure if the installation details only shows up on the "installation" page at [https://astropy.readthedocs.io/en/latest/install.html](https://astropy.readthedocs.io/en/latest/install.html) and the "development workflow" pages (there are at least three actually: [How to make a code contribution](https://astropy.readthedocs.io/en/latest/development/workflow/development_workflow.html), [Try the development version](https://astropy.readthedocs.io/en/latest/development/workflow/get_devel_version.html#get-devel), and [A worked example](https://astropy.readthedocs.io/en/latest/development/workflow/git_edit_workflow_examples.html#astropy-fix-example)... I think there are some details on the [Astropy landing page](http://www.astropy.org/) too, which might require looking into. 

I am actually amazed by how much overlapping regarding installation there is in the docs for the latest version.

**Comment by KING-SID** [comment]
Hey @kakirastern I'm a bit lost here. The "installation" page and "development workflow" pages that you referenced are of the latest version (v3.2dev1968), and I was simply looking to improve the Installation page for the stable v3.1 , I don't suppose that this is of much help given that v3.2 is being worked on and a lot of the issues are solved in that, but I think it would be a helpful update for the time being until the new version is released so that any new users that join before the latest release will find it easier to install the package. What are your thoughts on this?

**Comment by bsipocz** [comment]
@KING-SID - If you are preparing for GSoC, I suggest to look for another issue to fix, there are plenty to choose from.

Also as minor background info: for any dev docs please refer to [http://docs.astropy.org/en/latest/install.html](url). Docs updates typically end up in the next bugfix release (e.g. 3.1.2), thus there is no point "fixing" stable.

**Comment by KING-SID** [comment]
@bsipocz  Thanks for the heads up!

**Comment by kakirastern** [comment]
Hi, can I help by updating the installation docs as suggested in [https://github.com/astropy/astropy/pull/6051#issuecomment-301335291](https://github.com/astropy/astropy/pull/6051#issuecomment-301335291)?

**Comment by astrojuanlu** [comment]
If [@taldcroft suggestion of putting conda first and pip second](https://github.com/astropy/astropy/pull/6051#issuecomment-301335291) still stands, then https://docs.astropy.org/en/latest/install.html#using-conda should come before https://docs.astropy.org/en/latest/install.html#using-pip.

**Comment by CosmicTiger** [comment]
Assign to me this issue. I'll work on it.

**Comment by embray** [comment]
The installation page for SciPy is nice and pretty succinct: http://scipy.github.io/devdocs/getting_started.html  One thing I might do is emphasizing venv as an option when using pip, or `pip install --user`.  Not sure.

**Comment by SauravMaheshkar** [comment]
Should this issue still be open ?

**Comment by mwcraig** [comment]
I *think* it should still be open since https://github.com/astropy/astropy/pull/10919 was never merged. Will try to take a look on Thursday.

**Comment by exitflynn** [comment]
HI there! So... should the issue still be open? :P

**Comment by astrojuanlu** [comment]
Been almost 6 years since opening the issue. Is the stance of the project still that conda should come first? In https://github.com/astropy/astropy/pull/10919 there was some debate about it. If it has to be done, essentially #10919 should be repeated. If not, this issue should be closed IMO.

**Comment by pllim** [comment]
Hah, I really don't want another debate on pip vs conda... I'll slap a "Close?" label on this issue and see what happens. Thanks for the ping. 😉

**Comment by mwcraig** [comment]
I think it is fine to close -- happily, binary distributions are much more widely available now outside of conda.
