### ISSUE TITLE
enable_deprecations_as_exceptions doesn't raise AstropyDeprecationWarnings

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#6166]
astropy issues a few AstropyDeprecationWarnings but these are not caught in affiliates due to some bugs, even when using ``enable_deprecations_as_exceptions`` as discussed here: https://github.com/astropy/ccdproc/pull/507#issuecomment-306910781

**Comment by pllim** [comment]
This explains why `drizzlepac` failed at some point but my deprecation detection script didn't catch it prior. 😱

**Comment by bsipocz** [comment]
Yes, this is a weird one, as I remember the ``clobber`` vs ``overwrite`` deprecation raised quite a few exceptions.

**Comment by bsipocz** [comment]
I'm inclined to tag it as 2.0, as it would be great to get this sorted out asap to help packages deal with the new deprecations coming out of 2.0

**Comment by pllim** [comment]
I'll have a look today but I can't guarantee I'll find the culprit.

**Comment by MSeifert04** [comment]
Maybe this has to do with **when** the deprecation is issued. For `gzip` this was during test-collection phase while `overwrite` happened inside a test.

**Comment by bsipocz** [comment]
@pllim - I'm quite short on time in the coming days, but can promise to spend time on this before the release, unless of course you find the issue by then.

**Comment by bsipocz** [comment]
@MSeifert04 - Yes, that's an option. Would be great to see more logs. Do you remember when you saw the photutils one you mentioned earlier? @pllim do you have logs for drizzlepack?

**Comment by pllim** [comment]
There are logs somewhere, but I'll have to dig around.

**Comment by MSeifert04** [comment]
@bsipocz I guess it was https://github.com/astropy/photutils/pull/471#issuecomment-281082070. But now that I had a look I don't know if that really was related to this.

**Comment by pllim** [comment]
Do you think this is somehow caused by http://bugs.python.org/issue21724 (*resetwarnings doesn't reset warnings registry*)? I see a lot of calls to `warnings.resetwarnings()` in `treat_deprecations_as_exceptions()`.

**Comment by pllim** [comment]
I think @MSeifert04 is right. For example, look at https://travis-ci.org/spacetelescope/synphot_refactor/jobs/240915918 .

There is a `WARNING: AstropyDeprecationWarning: Something is old [synphot.utils]` on Line 503 (the import was done on top of a module) but tests reported as passing.

**Comment by pllim** [comment]
I am removing v2 milestone on this one. I think it needs more data for viable conclusion.

**Comment by bsipocz** [comment]
Indeed. Also this will be a bugfix, so no rush to get into 2.0, 2.0.1 will be just as good.

**Comment by bsipocz** [comment]
Hmm, this is now definitely works as I'm in fact unable to ignore these  warnings.
