### ISSUE TITLE
Docstring bugs in a few Ecliptic classes

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#6189]
Both `BarycentricTrueEcliptic` and `HeliocentricTrueEcliptic` incorrectly list their input argument names as `l` and `b`, when they should be `lon` and `lat`. See, e.g., [here](http://docs.astropy.org/en/latest/api/astropy.coordinates.BarycentricTrueEcliptic.html#astropy.coordinates.BarycentricTrueEcliptic). This requires a very simple documentation fix. I'll get to this by the feature freeze if no one else fixes it in the mean time...

**Comment by pllim** [comment]
PR incoming shortly.

**Comment by pllim** [comment]
See #6212
