### ISSUE TITLE
Add lookup and fill methods to NDData or Histogram

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#619]
Would it make sense to add lookup and fill methods to NDData or to create a `Histogram` sub-class?

The use cases I have in mind are:
- Given an image and a list of float pixel coordinates (e.g. source positions from SExtractor), `look up` the values of the pixels corresponding to those pixel coordinates. This is nontrivial to get right without a 0.5 or 1 pixel shift.
- Given an image and a list of world coordinates, `look up` the corresponding pixel values. This would probably be implemented by converting to pixel coordinates and then calling lookup on these, but it would be be convenient for the user to simply give world coordinates and not have to think about the pixel coordinate definition (where is `(0,0), (0.5,0.5), (1,1)`).
- Given an image with coordinates `RA, DEC` or spectrum with coordinate `Energy` or cube with coordinates `GLON, GLAT, Energy` and a list of coordinates, `fill` the image/spectrum/cube with these events.
- As for `lookup`, it would be nice if `fill` would either accept pixel or world coordinates.

Some background: in high-energy physics or X-ray and gamma-ray astronomy data typically either consists of event lists (e.g. each photon has a reconstructed position and energy). It is common to have millions or billions of events and to run binned analyses by histogramming the events first, which is what `fill` does, so this should be as fast as possible.
It might actually make sense to think about creating a separate `NDHistogram` class as an `NDData` subclass, with functionality similar to what the high-energy physicists use
http://root.cern.ch/download/doc/3Histograms.pdf
but aware of FITS pixel coordinate binning convention and world coordinates.

**Comment by astrofrog** [comment]
+1 to the idea, but removing the 1.0 milestone

**Comment by wkerzendorf** [comment]
@cdeil any news on this for imageutil. If you think it will live there we can close this issue here (for now).

**Comment by astrofrog** [comment]
imageutils is no longer very useful at the moment because a lot of it has been merged into astropy core. So I'm -1 on putting this in imageutils.

**Comment by cdeil** [comment]
FYI: implementing this is planned for week 1 (last week of May) of @mapazarr's GSoC. So any thoughts on use cases that should be supported or API now are very welcome!

Maybe implement the bare-bones functionality in functions that take `coordinates`, `data` and `wcs` as input and then expose the functionality also as methods on `NDData` for convenience in the cases where the user has an `NDData` object?

**Comment by astrofrog** [comment]
Just for information, there are now two functions in ``astropy.wcs.utils`` that will do most of the first two: ``skycoord_to_pixel`` and ``pixel_to_skycoord`` (but you may want to wrap them at a higher level).

I don't have any strong feelings about the API at the moment. It might be safest to implement these as functions in ``astropy.nddata`` for now since the bar is pretty high to get something as a method on the core ``NDData`` class (the use cases you describe are specifically for celestial and celestial + spectral data, not completely arbitrary data).

**Comment by mwcraig** [comment]
@cdeil -- would you object to this being closed?

**Comment by cdeil** [comment]
@mwcraig - OK, closing this issue.

We have this functionality in Gammapy, somewhat specific to our application.

If in the future there's interest to have a lookup or fill methods or generally histogramming functionality in Astropy core by others, we can always re-open the feature request / discussion where it can fit and how exactly it should work (i.e. interact with WCS-based or simple binned axes).
