### ISSUE TITLE
Docstring of Onu(self, z)

### ISSUE THREAD

**Issue by rainwoodman** [astropy/astropy#6196]
The docstring of Onu(self, z) claims it returns the energy density of massless neutrino. The implementation uses Ogamma * nu_relative_density(z), suggesting it is actually the energy density of all neutrinos. 

It may need some clarifications.

**Comment by rainwoodman** [comment]
Here are the relevant lines of source code:

https://github.com/astropy/astropy/blob/master/astropy/cosmology/core.py#L684

https://github.com/astropy/astropy/blob/master/astropy/cosmology/core.py#L789

**Comment by aconley** [comment]
You are correct.

**Comment by aconley** [comment]
That should fix it.  Thanks for pointing this out rainwoodman!
