### ISSUE TITLE
CompImageHDU doc example

### ISSUE THREAD

**Issue by SaraOgaz** [astropy/astropy#6220]
I was recently trying to use CompImageHDU and had to poke through tests to see how it should be used, although it looked like it returned an HDU object from the doc page, I wasn't 100% sure that's how it was meant to be used since it's class doc page doesn't specify.  So, are people okay with me adding a short doc example (I was thinking [here?](http://docs.astropy.org/en/stable/io/fits/#working-with-compressed-files)) of how to create and saveout your compressed image file?

**Comment by pllim** [comment]
Doc enhancement is always welcome. PR away!

**Comment by saimn** [comment]
There is a small example [here](http://docs.astropy.org/en/stable/io/fits/usage/unfamiliar.html#creating-a-compressed-image-hdu) but maybe a bit hidden at the end of the section.  It could be moved at the beginning of the [section](http://docs.astropy.org/en/stable/io/fits/usage/unfamiliar.html#compressed-image-data) ?

And the section you are [linking](http://docs.astropy.org/en/stable/io/fits/#working-with-compressed-files) is mostly about gzip-like compressed file. Maybe the sentence "Files that use compressed HDUs within the FITS file are discussed in Compressed Image Data." could be in a note block ?

**Comment by SaraOgaz** [comment]
I will add a link like you suggested and submit a PR.  I never found that section before because it's not in the menu side bar (how I normally navigate the docs).  In fact, I didnt' even know there were additional sections of docs down at the bottom of [this page](http://docs.astropy.org/en/stable/io/fits/#). Maybe I should file a separate issue talking about that...
