### ISSUE TITLE
Truncation of floats using Table.read() on .fits files (increase default formatting?)

### ISSUE THREAD

**Issue by petehague** [astropy/astropy#6229]
Loading the same fits file 2 different ways

`x = fits.open("results.fits")`

and

`x = Table.read("results.fits", format="fits", hdu=1)`

The latter method (which I would prefer to use for other reasons) sometimes rounds floating point values in the table to 6 significant figures. Oddly it doesn't do this if a specific cell is indexed i.e.

`x['ra'][0]`

returns the correct value, but listing the entire column

`x['ra']`

shows the rounded value for the same cell. When I hstack() this table with another and write it, the rounded value appears in the output. 

Furthermore, floating point values that I manually insert in the table (in the portion I attack with hstack()) are not rounded in the output file.

**Comment by pllim** [comment]
Can you please attach the file (or give a link for download) and give a standalone example code to reproduce your problem and the outputs you see. This is because others may or may not see what you are experiencing.

**Comment by petehague** [comment]
I reproduced the error using only those commands I posted, from the Python console. As for the file, I can't really publish it - but its a fairly ordinary fits table. The type of the column is 'E' i.e. single precision float. When I tried it on another column of type 'D' (double precision) the rounding was to 12 significant figures.

**Comment by bsipocz** [comment]
If you can't provide the fits file, could you build up a mock one, or just a fraction of your file that also shows the issue? Also could you provide the outputs you see? As @pllim said a standalone script would be rather useful for reproducibility.

**Comment by petehague** [comment]
I'll put something together. I'll just add that subtracting the values that you see in the fits.open version from the ones in the Table.read version gives 0.0, so it appears the internal representation is fine - its that for some reason the Table module applies formatting to the number even when writing to a binary file

**Comment by pllim** [comment]
Please also provide the FITS header. Formatting in FITS table is represented in some `Txxxx` keywords (can't remember exact spelling on top of my head but I know them when I see them).

**Comment by astrofrog** [comment]
I think this is just related to the default Column formatting, which does not show all decimal places:

```
In [15]: import numpy as np

In [16]: from astropy.table import Table

In [17]: t = Table()

In [18]: t['pi'] = np.array([np.pi], dtype=np.float32)

In [19]: t
Out[19]: 
<Table length=1>
   pi  
float32
-------
3.14159

In [20]: t['pi']
Out[20]: 
<Column name='pi' dtype='float32' length=1>
3.14159

In [21]: t['pi'][0]
Out[21]: 3.1415927
```

Maybe this means we should increase the default formatting precision a little for Column? (cc @taldcroft )

**Comment by astrofrog** [comment]
@petehague - by the way, you can customize the format as follows:

```
In [30]: t['pi'].format = "{0:.30g}"

In [31]: t
Out[31]: 
<Table length=1>
           pi           
        float32         
------------------------
3.1415927410125732421875
```

**Comment by petehague** [comment]
Yes, I figured this was a formatting issue - the problem is that ascii formatting does not make sense when writing floats to a binary file. I should reiterate - when I read .fits files produced by the module in other programs, the actual values (not the displayed, formatted versions) are rounded in the same way as the values displayed in Python are.

It seems to me that the Table module was written firstly to produce readable fixed with ascii tables, and then had support for .fits added later without changing a behaviour that doesn't work in the new context.

**Comment by AustereCuriosity** [comment]
"When I hstack() this table with another and write it, the rounded value appears in the output." By this do you mean that you manually checked the FITS file, in which you've written the table, for the data and found it to be rounded off or just the formatted output?

**Comment by pllim** [comment]
>  actual values (not the displayed, formatted versions) are rounded in the same way as the values displayed in Python are

Is this even a desirable behavior? I wouldn't want my actual values to be rounded in any way.

**Comment by petehague** [comment]
That is what seemed to be happening, yes. I'm trying to put together a short script + fits file to reproduce the bug.

**Comment by petehague** [comment]
I've been unable to replicate the problem myself with a new file, so it may be the case that this is not being caused by astropy, and may be something else in my original files and scripts. Sorry for the inconvenience - I will close this issue for now on the assumption its my code causing the problem.

**Comment by pllim** [comment]
@petehague , thanks for the update. If you ever get to the bottom of this, feel free to post your findings despite this issue being closed so that others with the same problem will find it. :smiley:
