### ISSUE TITLE
What's new is missing from front docs page

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#6231]
In the latest reshuffle of docs in #6051 the "what's new" section got removed. There is one link to the full changelog further down at the page, but I think it would be good to have a direct link to the latest ``what's new``, too otherwise it's pointless for us to write it if it's hidden away. 

cc @kelle @eteq

**Comment by kelle** [comment]
The "what's new" link is featured bigly on the home page:
http://www.astropy.org/. I personally don't think of the "What's New" as being part of the core documentation but rather, part of the promotional materials. That said, I think it's worth having a link here as well. BUT, I  would prefer this page not need to be updated with every release...maybe the link could read "What's new in the latest version?" and then just link to the Major Release History page? http://docs.astropy.org/en/stable/whatsnew/index.html 

Is this a reasonable compromise?

**Comment by mwcraig** [comment]
I actually like a fairly prominent whats-new link on the main doc page....I've been looking at several other projects lately getting ready for a tutorial I'm presenting at scipy and the projects that make it hard to get to the release notes/whats new are kind of frustrating. 

My understanding is that this is only updated once every point release, so the maintenance burden seems low (and is part of the release to-do list, I assume).

**Comment by bsipocz** [comment]
@kelle - I know my case is not representative, but I never go to the astropy.org site (nor to similar sites of other projects I'm already using), but straight to the documentation. Having an easily findable changelog/release notes/what's new is then a very kind gesture and saves me the need to dig in the source code.

Changes to the front page of the docs will almost always happen in major releases as we add and deprecate modules, so I don't see the issue with changing the what's new bit, too. (Note, that his only happens for feature releases, once in every ~6 months).
