### ISSUE TITLE
Clarify astronomical context for Ripley's K function

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#6232]
In #5712 @mirca implemented Ripley's K function.  It would be useful if the `astropy.stats` docs had just a bit more about what that's used for in an astronomical context, so that readers understand why its in `astropy.stats`.

This is not critical for 2.0 but it would be nice (hence my milestoning)

**Comment by bsipocz** [comment]
@mirca - in addition to this clarification, the references in the docs page should be sorted out, too and be cited within the text. New sphinx gets very picky on uncited references, and we definitely want to avoid failing builds:
https://travis-ci.org/astropy/astropy/jobs/244587718#L3437

**Comment by mirca** [comment]
@bsipocz oh sure!

**Comment by bsipocz** [comment]
For the missing reference, the current workaround is this one https://github.com/astropy/astropy/pull/6140/commits/3e235bd7849336514ba9679176b47f772be13cea

**Comment by crawfordsm** [comment]
The first part of #5139, the two point correlation function,  has not yet been included, which I think is a bit more familiar to astronomers, but still any extra docs giving some more context to it would be useful.

**Comment by bsipocz** [comment]
@eteq - would the example cited in #6252 enough to close this, or you prefer to have more docs on it?

**Comment by mirca** [comment]
@bsipocz I would prefer to leave this open because I think #6252 is too simplistic, but @eteq decides =)

**Comment by eteq** [comment]
@mirca - I would have said #6252 seems sufficient, actually.  I guess it really depends on whether you think you (or someone else) can provide more useful context or a worked example that's not too complex.  But if that's not easy, I think we can close this - #6252 passes the "why is it in `astropy.stats`" test I'd say.

I'll leave the final call to @crawfordsm, though, as maintainer of `stats`.

**Comment by bsipocz** [comment]
I'm moving this forward to 2.0.1, but please close if you think the current docs is sufficient.

**Comment by bsipocz** [comment]
It's not very useful rolling this along the milestones, removing it now, but indeed would be great to address it for 3.0

**Comment by crawfordsm** [comment]
There was still another bit of code to add from #5139 which would, I think, give the spatial statistics package some more context.   Until that is added, I think that this is fine and closing this for now.
