### ISSUE TITLE
Turn Astropy deprecations into exceptions in Astropy tests

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6255]
Prompted by #6251 , I think we should turn our own `AstropyDeprecationWarning` into exceptions, which is currently not done. There is no reason we should allow usage of deprecated Astropy code within Astropy itself when we ask everyone else to switch.

This is as simple editing `astropy/conftest.py` to have the following instead:
```python
enable_deprecations_as_exceptions(include_astropy_deprecations=True)
```

**Comment by MSeifert04** [comment]
Did you check how many tests fail then?

**Comment by pllim** [comment]
> Did you check how many tests fail then?

Not yet (also afraid to...) as Sphinx 1.6 support takes priority right now.

**Comment by bsipocz** [comment]
I have the feeling that it has history and was disabled for a reason, but haven't yet digged up the details.

**Comment by MSeifert04** [comment]
Well, I guess it would be a good idea to always catch deprecations in the tests. I just assume it's too much effort - that was the reason why I asked for the number of "failures". Maybe you could just turn it on and make a PR. I just doubt it will be "effort-low" :)

In the end it would be beneficial to catch these too ( 👍 for the proposal). That would make removal of deprecated features easier and also estimating the "cost of deprecation".

**Comment by bsipocz** [comment]
@MSeifert04 - let's see how it goes: https://travis-ci.org/bsipocz/astropy/builds/245579002

**Comment by pllim** [comment]
Hmm. What a dilemma. :thinking: 
```
===== ERRORS =====
______ ERROR collecting lib.linux-x86_64-3.5/astropy/vo/samp/__init__.py _______
astropy/vo/samp/__init__.py:7: in <module>
    AstropyDeprecationWarning)
E   astropy.utils.exceptions.AstropyDeprecationWarning: The astropy.samp module has now been moved to astropy.samp
===== warnings summary =====
```

**Comment by bsipocz** [comment]
Yes, that's what I feared, either we live with the warnings or go with ugly hacks to avoid a few of them during testing.

**Comment by pllim** [comment]
Okay, maybe I should just close this issue as "won't fix" and we'll just deal with it on a case-by-case basis. At the very least, maintainers should make sure a PR also removes deprecated code throughout Astropy codebase when something is deprecated in Astropy itself.

**Comment by mhvk** [comment]
I'm re-opening this given #6934, which shows that we cannot just assume that deprecation warnings from astropy will be caught in all pieces; stuff is just too interconnected for that.

From the above, it sounds like we may need a different subclass of deprecation warning that we suppress, which we use for stuff that gives a warning already on import.

**Comment by pllim** [comment]
@mhvk , given that you propose we remove the functionality altogether at https://github.com/astropy/astropy/issues/9690#issuecomment-559154730 , I am closing this again as won't fix.

**Comment by mhvk** [comment]
Yes, makes sense - I think you definitely set up all that is needed already!
