### ISSUE TITLE
Auto-identify ECSV tables in Table.read

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6265]
We should add an identifier for the ECSV format in the unified I/O infrastructure - ECSV files are easy to recognize since they start with ``# %ECSV`` (identifiers don't have to be based on the filename, but could be on first few bytes).

**Comment by nimitbhardwaj** [comment]
I would like to work on this issue

**Comment by pllim** [comment]
As @nimitbhardwaj pointed out (good catch), this is a duplicate and will be closed in favor of the original request.

@nimitbhardwaj , if this is your first contribution, we recommend that you pick an issue marked as "package-novice" first to get familiarized with the contributing process. However, nothing stops you from tackling this anyway. FYI.

**Comment by nimitbhardwaj** [comment]
Yes, I seems to be a novice to this project, but i had some experience in the opensource, and I found the position of this issue where it is located in the code, there is a function identify_format in io/registry.py, it returns the format if no kwarg format is given, we need to adjust it so it returns the format for .ecsv files, it is possible to figure out by seeing the file, i try to do it.
