### ISSUE TITLE
Update sphinx-gallery minversion on Travis when appropriate

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6266]
As mentioned in https://github.com/bsipocz/astropy/pull/3#issuecomment-310465771, once sphinx-gallery/sphinx-gallery#255 is included in a proper release, `sphinx-gallery` minimum version requirement can be updated to get rid of `RemovedInSphinx17Warning` for `app.status_iterator()` in the Sphinx build test on Travis.

Also see #6140.

**Comment by pllim** [comment]
Upstream fix was merged in sphinx-gallery/sphinx-gallery#250 and that was back in June. So, this is no longer an issue, @bsipocz ?

**Comment by bsipocz** [comment]
Oh, good catch. 

I've updated the min version to 0.1.11 in c560ecde72881a46804040e644b4e4e53a960945 for the sphinx 1.6.1 compatibility as I didn't remembered that we also need sphinx-gallery/sphinx-gallery#250, and that's landed in 0.1.12. Opening a new PR to close this.

**Comment by pllim** [comment]
Thanks!
