### ISSUE TITLE
doctest_plus = disabled in setup.cfg doesn't have intended effect

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6268]
In ``setup.cfg`` for the core package and the package template, ``doctest_plus = enabled`` enables doctest-based testing. However, setting this to ``doctest_plus = disabled`` does not disable it - only the *absence* of that line altogether disables it. This is because ``pytest_plugins.py`` simply includes ``config.getini('doctest_plus')`` in a boolean expression, rather than checking if it is also set to ``disabled``. Basically, at the moment, one could set ``doctest_plus = banana`` and it would work. Do we want to standardize on actual option values such as disabled/enabled? or false/true? (or both?)

**Comment by bsipocz** [comment]
+1 to get it cleaned up and only enable it with 'enabled' and 'true'.

**Comment by bsipocz** [comment]
btw I see it as a bug, so we should get a fix in 2.0

**Comment by astrofrog** [comment]
(maybe we should also make it case-insensitive)
