### ISSUE TITLE
Remove masking of MaskedArrayFutureWarning

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6285]
Undo #6261 when it is no longer emitted by Numpy and that Numpy version becomes the minimum required version for Astropy.

cc @mhvk @taldcroft

**Comment by astrofrog** [comment]
Since this issue may be open for a long time and we might forget about it, I think it might be more useful to settle on a convention for writing in the code when something can be dropped when a specific Numpy or Python version is not supported anymore.

**Comment by pllim** [comment]
Let's wait till after release. RC is coming out, right?

**Comment by pllim** [comment]
Are we there yet? @mhvk ?

**Comment by mhvk** [comment]
I think that particular warning is not there in 1.14 any more, but does seem to be there in 1.13, so I guess we'll have to wait until 1.14 is our minimum required version.

**Comment by pllim** [comment]
So, theoretically, when Numpy 1.16 is out, then 1.14 would be our min version?
