### ISSUE TITLE
Unit ignores 'parse_strict' keyword when format is 'vounit'

### ISSUE THREAD

**Issue by astrogreen** [astropy/astropy#6302]
The units package doesn't seem to do any validation when the format is 'vounit' other than occasionally issuing warnings.
```python
>>> import astropy.units as units

>>> units.Unit("Angstroem")
ValueError: 'Angstroem' did not parse as unit: At col 0, Angstroem is not a valid unit. Did you mean Angstrom or angstrom?

>>> units.Unit("Angstroem", format='vounit')
Unit("Angstroem")

>>> units.Unit("Angstroem", format='vounit', parse_strict='raise')
Unit("Angstroem")

```

I would expect the vounit formatting to require that the unit string match the VO standard? I also note that the signature for `unit.Unit` does not actually have a `parse_strict` keyword (I thought this would be an error.)

Furthermore, it seems that the unit created using the 'vounit' format is not "unrecognized":
```python
>>> u = units.Unit("Angstroem", format='vounit')

>>> isinstance(u, units.UnrecognizedUnit)
False
>>> type(v)
astropy.units.core.IrreducibleUnit

```

Other formats, such as 'fits' and 'cds' seem to behave as expected.

**Comment by pllim** [comment]
The actual logic is in the `_parse_unit()` method within `vounit.py`. That part of the code has not been touched for years and was mainly written by @mdboom who is no longer working on this.

As for `parse_strict`, it is defined in [__call__() of unit's metaclass](https://github.com/astropy/astropy/blob/master/astropy/units/core.py#L1749).

@mhvk -- What do you think?

**Comment by mhvk** [comment]
Definitely a bug! Thanks for reporting, @astrogreen. If you are up to investigating this further, a PR would obviously be very welcome! (Though this is not trivial code.)

**Comment by pllim** [comment]
There are more recent discussions over at #13017 , so I am closing this as duplicate.
