### ISSUE TITLE
Random table-related failures in travis

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#6308]
I've been noticing some intermittent test failures in Travis that look like this one: ~~https://travis-ci.org/astropy/astropy/jobs/248490122~~  https://gist.github.com/db072db462ca32e3802abdcc9104cfa2 (had to re-start the original build to merge something #6306)

The proximate error is a ``TypeError: only dimensionless scalar quantities can be converted to Python scalars`` in `TestVStack.test_col_meta_merge_inner[QTable]`, but given that they are intermittent it seems like there must be some underlying problem that's not directly related to that test (since it ).

Note that this was noticed in #6047, although that was closed because, as I said, it seems to appear intermittently on travis... 

@mhvk or @taldcroft - do either of you have any clue what might be triggering this?

**Comment by eteq** [comment]
Also, just in case that log disappears or is restarted or whatever, I've put a backup copy of the failing log here: https://gist.github.com/db072db462ca32e3802abdcc9104cfa2

**Comment by saimn** [comment]
I think this is the failure discussed in #6291 ?

**Comment by pllim** [comment]
I think so. I knew it looked familiar.

**Comment by taldcroft** [comment]
This is definitely a duplicate so closing.

**Comment by eteq** [comment]
My bad!  I saw #6047 and thought that was the only one...
