### ISSUE TITLE
Make +FLOAT_CMP default and/or move it upstream?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6312]
Possibly more for astropy helpers, but our doctests are currently littered with `doctest: +FLOAT_CMP` instances. Should we make this the default. Also, this came up in numpy, where it was wondered why we don't move this upstream [1]. That seems reasonable... (that, arguably, is more of an astropy_helpers issue, but I know I'll get more exposure here...).

[1] https://github.com/numpy/numpy/pull/9139#issuecomment-312241621

**Comment by bsipocz** [comment]
Actually ``FLOAT_CMP`` belongs to astropy core and not astropy-helpers, as it's defined as part of ``astropy.tests``. Anyway, there are plans to remove all  the tests related stuff from core in the future (e.g. #5770), but that doesn't help resolve the code littering issues.

That said, I'm not sure why it never made it upstream, tagging @embray as the original author.

**Comment by rgommers** [comment]
As I noted on the numpy list, moving upstream means into the stdlib, which is probably not helpful in resolving anything (although in the really long term a useful action). A separate doctest-like runner would be more useful.

**Comment by bsipocz** [comment]
There is also another related feature request https://github.com/astropy/astropy/issues/2662

**Comment by embray** [comment]
In this case "upstream" could be interpreted not literally as upstream, but as a separate package from astropy itself.

**Comment by pllim** [comment]
Should we move this to `astropy/pytest-doctestplus` repo?

**Comment by drdavella** [comment]
It's already upsteram. See https://github.com/astropy/pytest-doctestplus/issues/10 for discussion about whether it should be default.
