### ISSUE TITLE
pending=True in deprecated should actually emit AstropyPendingDeprecationWarning

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6313]
Follow-up of #5761 , where a `pending=True` keyword was added to `deprecated_renamed_argument` decorator. Currently, the deprecation warning is completely suppressed, which was necessary at the time for `clobber`. But now that is behind us (with 2.0 almost released), I wonder if the correct behavior should be that `pending=True` emits `AstropyPendingDeprecationWarning` instead; This would also then be more consistent with `deprecated` decorator. :thinking: 

c/c @MSeifert04

**Comment by MSeifert04** [comment]
I think I've tested it and the `PendingDeprecation` still results in an Exception with the tests if `enable_deprecations_as_exceptions(include_astropy_deprecations=True)` is set.

I don't remember everything but the point of the change was to temporarily disable the breaking tests because of the deprecation.

**Comment by pllim** [comment]
@MSeifert04 , yes `include_astropy_deprecations=True` will cause even pending warning to emit exception and I understand why you did not do this back then. All I am saying is now that *that issue* was behind us, maybe we can have `pending` keyword do the *proper* thing. Unless you don't think `pending` emitting `AstropyPendingDeprecationWarning` is the proper thing to do?

**Comment by pllim** [comment]
Or perhaps you think `include_astropy_deprecations=True` should not include `AstropyPendingDeprecationWarning`? I am actually not sure what `AstropyPendingDeprecationWarning` is used for, as I always just go straight to `AstropyDeprecationWarning`.

**Comment by MSeifert04** [comment]
> Or perhaps you think include_astropy_deprecations=True should not include AstropyPendingDeprecationWarning? 

I haven't thought that far - but that sounds sensible to me.

**Comment by pllim** [comment]
c/c @drdavella into this discussion since he took on the `pytest` stuff.

**Comment by pllim** [comment]
Short of changing the `AstropyPendingDeprecationWarning` inheritance, I am not sure how to do this in a clean way. Not sure if this battle is worth fighting anymore. Since I am the only one who ever brought it up, let's just close this one...
