### ISSUE TITLE
2.0rc1: TestConvolve2D.test_non_normalized_kernel[None] fails on s390x

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#6324]
On IBM zSystems, the test `TestConvolve2D.test_non_normalized_kernel[None]` fails:
```
self = <astropy.convolution.tests.test_convolve_fft.TestConvolve2D object at 0x3ff792f8780>
boundary = None

    @pytest.mark.parametrize(('boundary'), BOUNDARY_OPTIONS)
    def test_non_normalized_kernel(self, boundary):
    
        x = np.array([[0., 0., 4.],
                      [1., 2., 0.],
                      [0., 3., 0.]], dtype='float')
    
        y = np.array([[1., -1., 1.],
                      [-1., 0., -1.],
                      [1., -1., 1.]], dtype='float')
    
        z = convolve_fft(x, y, boundary=boundary, nan_treatment='fill',
                         normalize_kernel=False)
    
        if boundary in (None, 'fill'):
            assert_array_almost_equal_nulp(z, np.array([[1., -5., 2.],
                                                        [1., 0., -3.],
>                                                       [-2., -1., -1.]], dtype='float'), 10)
E           AssertionError: X and Y are not equal to 10 ULP (max is 4.36849e+18)

astropy/convolution/tests/test_convolve_fft.py:574: AssertionError
_______________ TestConvolve2D.test_non_normalized_kernel[fill] ________________

self = <astropy.convolution.tests.test_convolve_fft.TestConvolve2D object at 0x3ff78380b00>
boundary = 'fill'

    @pytest.mark.parametrize(('boundary'), BOUNDARY_OPTIONS)
    def test_non_normalized_kernel(self, boundary):
    
        x = np.array([[0., 0., 4.],
                      [1., 2., 0.],
                      [0., 3., 0.]], dtype='float')
    
        y = np.array([[1., -1., 1.],
                      [-1., 0., -1.],
                      [1., -1., 1.]], dtype='float')
    
        z = convolve_fft(x, y, boundary=boundary, nan_treatment='fill',
                         normalize_kernel=False)
    
        if boundary in (None, 'fill'):
            assert_array_almost_equal_nulp(z, np.array([[1., -5., 2.],
                                                        [1., 0., -3.],
>                                                       [-2., -1., -1.]], dtype='float'), 10)
E           AssertionError: X and Y are not equal to 10 ULP (max is 4.36849e+18)

astropy/convolution/tests/test_convolve_fft.py:574: AssertionError
```
This is a platform with 64-bit big endian (which is quite unusual).
Full log [here](https://buildd.debian.org/status/package.php?p=python-astropy&suite=experimental).
_Addition:_ Same problem on [PowerPC 64 bit big endian](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=ppc64&ver=2.0%7Erc1-1&stamp=1499199661&raw=0), [32 bit big endian](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=powerpc&ver=2.0%7Erc1-1&stamp=1499200777&raw=0) and [64 bit little endian](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=ppc64el&ver=2.0~rc1-1&stamp=1499201096&raw=0).
All platforms were fine with 1.3.3.

**Comment by bsipocz** [comment]
cc @keflavich - probably we just need to change the 10 ULP as we did for windows?

**Comment by keflavich** [comment]
Yeah, I guess so?  I don't understand when it says "10^18 ULP", since that implies a much bigger difference than we're (probably?) seeing here.

How can we test this?

**Comment by astrofrog** [comment]
@olebole - could you easily run this test with ``--pdb`` and print out the value of ``z`` before the last comparison?

**Comment by astrofrog** [comment]
As I suspected, this is because one of the values is 1e-16 instead of 0:

<img width="601" alt="screen shot 2017-07-07 at 10 11 58" src="https://user-images.githubusercontent.com/314716/27951453-e7a6a538-62fc-11e7-9548-13801b964554.png">

PR forthcoming
