### ISSUE TITLE
make dev version aware setup_requires 

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#6352]
We shouldn't include jinja2 and cython in ``setup_requires`` for the released version, but keep them there for development ones. 

We just make sure to set the value based on the version string.

Once it's done remove them for conda-forge, too https://github.com/conda-forge/astropy-feedstock/issues/13
(though that PR has to be done for the new release, not before)

**Comment by firedranzer** [comment]
Hi @bsipocz . I want to take this issue.I'm new to this organisation .Please guide my way through this issue.

**Comment by astrofrog** [comment]
@firedranzer - thanks for your interest in contributing! As a rule of thumb, please don't ask the person opening the issue to guide you through all the steps to fix it. Instead, head over to http://www.astropy.org/contribute.html - there is a lot of information there as well as links to guidelines on how to contribute. If there are certain specific aspects of the issue you don't understand, it's completely find to ask of course.

**Comment by firedranzer** [comment]
Thank you @astrofrog for the help. I wanted to get familiar to the codebase of this organisation and a walkthrough would be great.

**Comment by bsipocz** [comment]
@firedranzer - thanks for your interest! If you're keen to getting familiar with the astropy codebase, I suggest to look at the other issues, too as this one is purely about packaging and not about astropy itself. We use the [``package-novice``](https://github.com/astropy/astropy/issues?q=is%3Aissue+is%3Aopen+label%3APackage-novice) label to identify issues that are thought to be the most suitable for new contributors to tackle.
