### ISSUE TITLE
Hide warnings when running astropy.test()

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6353]
When running astropy.test(), all the warnings from tests are shown - for ``python setup.py test`` this doesn't happen because we have ``addopts = -p no:warnings`` in ``setup.cfg``. We need to figure out if we want to add that option by default in the actual test runner, or at least give people instructions for hiding them.

**Comment by pllim** [comment]
Maybe with a `warnings.simplefilter()` context manager?

**Comment by bsipocz** [comment]
you can always have a ``pytest.ini`` with 
```
[pytest]
filterwarnings =
    error
    ignore::UserWarning
```

**Comment by bsipocz** [comment]
We currently hide the warnings and have open PRs (#7928) to show them (to be merged once most of them got fixed/worked around.
So I think there is no need to keep this issue open, but feel free to reopen if you think otherwise.
