### ISSUE TITLE
Move test runner out of astropy core

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#6362]
It's possible that other projects (e.g. [asdf](https://github.com/spacetelescope/asdf)) want to make use of astropy's test runner without having a hard dependency on astropy core. Would it make sense to move the test runner to `astropy_helpers` or even to a completely separate repository? I found some discussion about this [here](https://github.com/astropy/astropy-helpers/issues/125) but I didn't see any issues explicitly addressing a change.

**Comment by bsipocz** [comment]
This is a duplicate, work has already been started in #5770

**Comment by pllim** [comment]
Yes, this issue has already been discussed elsewhere. I thought about it from time to time... We had a GSoC proposal to implement each option as separate pytest plugins, which I think is a good idea but need some dedicated resources to make it happen.

**Comment by drdavella** [comment]
Oops, I was just searching for the wrong terms. I'll take a look and see if this is something I can help with.

**Comment by bsipocz** [comment]
@pllim - The hard limit for this is 3.0, as we've already removed the deprecated compatibility code from the helpers, but tagged it for 3.0 to not put extra burden for packages such as asdf ;) https://github.com/astropy/astropy-helpers/pull/314#issuecomment-310910031

**Comment by pllim** [comment]
@drdavella , if you can somehow charge ASDF WBS for this work, that would be awesome... But if you work on in charging to WBS, chances are the packages would be "required" to live in `spacetelescope` instead of your own GitHub or `astropy`. Food for thought.

**Comment by bsipocz** [comment]
Can you add non stsci people to have commit rights to a spacetelescope repo? If yes, that even that requirement shouldn't be an issue I guess? Even then, should it be the original, or a fork is enough?
