### ISSUE TITLE
[ECSV] Error on reading tab-separated columns

### ISSUE THREAD

**Issue by chbrandt** [astropy/astropy#6367]
* Python 2.7.12 :: Anaconda custom (64-bit)
* astropy.__version__ : 1.3.2

Error: ECSV reader seems to get confused with tab-separated columns.

I have the following data file:
`sample.ecsv`
```
# %ECSV 0.9
# ---
# datatype:
# - name: e_ref
#   unit: TeV
#   datatype: float64
# - name: dnde
#   unit: ph / (m2 TeV s)
#   datatype: float64
# - name: dnde_errn
#   unit: ph / (m2 TeV s)
#   datatype: float64
# - name: dnde_errp
#   unit: ph / (m2 TeV s)
#   datatype: float64
#
e_ref	dnde		dnde_errn	dnde_errp
0.291	1.20E-007	2.80E-008	2.80E-008
0.427	6.10E-008	1.00E-008	1.00E-008
0.628	2.20E-008	4.40E-009	4.40E-009
0.922	4.30E-009	1.70E-009	1.70E-009
```

Notice the (white) space between the table columns are `tab`-spaces (`\t`)

Reading it with the following lines give me back the error message below:
```
from astropy.table import Table
t = Table.read('sample.ecsv', format='ascii.ecsv')
```
Error message:
```
ValueError: column names from ECSV header ['e_ref', 'dnde', 'dnde_errn', 'dnde_errp'] do not match names from header line of CSV data ['e_ref\tdnde\t\tdnde_errn\tdnde_errp']
```
Thanks.

**Comment by pllim** [comment]
When I copy and paste your table, the header row actually has a mix of spaces and tabs; i.e., there are actually spaces between "e_ref" and "dnde". Adding `delimiter="\s"` should solve your problem.

**Comment by pllim** [comment]
By the way, I was using the astropy 2.0 series, so upgrading your astropy might also help.

**Comment by larrybradley** [comment]
The ECSV format allows only a space or a comma as delimiters:

https://github.com/astropy/astropy-APEs/blob/master/APE6.rst
https://github.com/astropy/astropy/blob/master/astropy/io/ascii/ecsv.py#L54

**Comment by chbrandt** [comment]
Sure @pllim , we should close. 

What I'm doing is: before reading the files with astropy, I check and clean them from such mixture of tabs and spaces; which is kind of "wrong", but it happens. I wonder now how can I write an extension to astropy's ascii.read interface, in such a way my extension would handle only this very particular step (to shrink the multiple-&-mixtured whitespaces), and leave everything else to astropy it self.
Once I saw a document talking about how to write a parser to be used by "astropy's read" engine, but that was about a entire (new) file format parsing. The other way around --as far as I can see-- would be to inherit some ECSV Reader class and overwrite to "read" function; but then I don't know how to tell Astropy "Hey! Use this class here while reading those ecsv files".

If you, guys, could point me to the direction where I could most seamlessly extend such functionatily I would be most grateful.
Thanks

**Comment by pllim** [comment]
Does the following not work for you? It worked when I read your file.
```python
t = Table.read('sample.ecsv', format='ascii.ecsv', delimiter='\s')
```

**Comment by taldcroft** [comment]
I can replicate the success using `delimiter='\s'`.  That is not *exactly* expected behavior because as @larrybradley noted tabs should not be allowed.  But it turns out that the `\s` delimiter is really just a special-case that fixes the input line before splitting.

**Comment by taldcroft** [comment]
@chbrandt - about wanting to tell Astropy "Hey! Use this class here while reading those ecsv files", YES you can do that.

The `Inputter` class in a reader is responsible for getting the input.  The [base inputter class](https://github.com/astropy/astropy/blob/07e2711656847c4e6786f3e66d4ffb59cb66c281/astropy/io/ascii/core.py#L262) has a `process_lines` method that you can override to do your bidding.  In short, something like this should work:
```
class MyEcsvInputter(ascii.core.BaseInputter):
    def process_lines(lines):
        new_lines = []
        for line in lines:
            new_line = # do something
            new_lines.append(new_line)
        return new_lines

class MyEcsv(ascii.ecsv.Ecsv):
    _format_name = 'myecsv'
    _description = 'Custom Enhanced CSV'
    inputter_class = MyEcsvInputter
```

**Comment by chbrandt** [comment]
@pllim Yes, it does. Perfect.

@taldcroft Great, will look into it.

Thank you.
