### ISSUE TITLE
sip to_header with key option issue.

### ISSUE THREAD

**Issue by fockez** [astropy/astropy#6370]
wcs to_header function with key does not support SIP well. First, SIP parameters don't have key in the end, so cannot keep more than one set of SIP. second, when read back, the SIP will raise with error "Header has SIP keywords without CRPIX keywords" because it's looking for the "CRPIX1" and "CRPIX2" keywords but not "CRPIX1a".
But SIP has key like BP_ORDER does not fit to add ending key.

**Comment by nden** [comment]
@fockez The assumption here is that alternate WCSs use the same distortion model. So one would never need to save more than one set of SIP coefficients in the header. And as you pointed out the `BP_ORDER` cannot be saved with a `key`. I believe the read error is a bug and will look into it.

**Comment by fockez** [comment]
@nden Thank you for you rapid reply. The reason of why we keep multiple sets of WCS is that, we are reducing images in several automatic pipeline. So keep the tracks of these results will helpful for tracing back the issues during the pipeline. But that's ok too. I believe the reading bug is line 1109 to 1114 of wcs.py, changing "CRPIX1" to "CRPIX1" + wcskey.

**Comment by nden** [comment]
@fockez If you have the time to submit a PR that be great as I won't be able to do this until Tue.
