### ISSUE TITLE
np.append with units

### ISSUE THREAD

**Issue by ashill** [astropy/astropy#6376]
I'm having an issue where units get stripped whenever I use np.append. Every way I can think of, the unit of the numpy array becomes uninitialized after I use np.append, and if I try to add the unit to the array after it becomes uninitialized, np.append crashes. Example:

>Python 2.7.12 |Anaconda 2.4.0 (x86_64)| (default, Jul  2 2016, 17:43:17) 
```python
import numpy as np
import astropy
astropy.__version__
```
>u'2.0'
```python
np.__version__
```
>'1.13.1'
```python
from astropy import units as u
array = np.array([])*u.m
array
```
><Quantity [] m>
```python
np.append(array, 5*u.m)
```
><Quantity [ 5.] (Unit not initialised)>
```python
np.append(array, 5)
```
><Quantity [ 5.] (Unit not initialised)>
```python
np.append(array, 5)*u.m
```
>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "~/anaconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 1028, in __mul__
>    return self._new_view(self.copy(), other * self.unit)
>TypeError: unsupported operand type(s) for *: 'IrreducibleUnit' and 'NoneType'

The output I expect from these commands (except the one in which 5 does not have specified units) is
><Quantity [ 5.] m>

**Comment by MSeifert04** [comment]
That definitely looks like a Bug but I think fixing `np.append` for Quantity is probably not worth it (I think that function is a damn nuisance).

**Comment by pllim** [comment]
Workaround for now:
```python
>>> np.append(array.value, 5) * u.m
<Quantity [ 5.] m>
```

**Comment by bsipocz** [comment]
@ashill - This is a known behaviour of a few numpy operations and has already been featured here: http://docs.astropy.org/en/latest/known_issues.html#quantities-lose-their-units-with-some-operations

**Comment by ashill** [comment]
OK, thanks @pllim for the workaround and @bsipocz for pointing out that it's that known issue.
