### ISSUE TITLE
How to calculate blackbody for older version of constants?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6383]
I have tests failing because of the constants update that affected blackbody calculation in #6083. Setting `from astropy.constants import astropyconst13 as const` does not help in this situation. Is there a way to tell the blackbody function to use an older version of constant?

**Comment by pllim** [comment]
@stargaser , any advise? :(

**Comment by stargaser** [comment]
Would the solution that Duncan Macleod [described here](https://mail.python.org/pipermail/astropy/2017-July/004248.html) work?

**Comment by stargaser** [comment]
The numbers change when I change the constants...here's part of my IPython session:

```
In [2]: from astropy.modeling.blackbody import BlackBody1D

In [3]: import astropy.constants as const

In [4]: from astropy.constants import (si, astropyconst13)

In [5]: import astropy.units as u

In [7]: BlackBody1D(5000*u.K)(1.4*u.micron)
Out[7]: <Quantity 1.8846840014534117e-15 erg / (cm2 Hz s)>

In [8]: const.sigma_sb = si.sigma_sb = astropyconst13.sigma_sb

In [9]: const.h = si.h = astropyconst13.h

In [10]: const.k_B = si.k_B = astropyconst13.k_B

In [11]: BlackBody1D(5000*u.K)(1.4*u.micron)
Out[11]: <Quantity 1.884683089624424e-15 erg / (cm2 Hz s)>
```

**Comment by stargaser** [comment]
Oh I see. In astropy 1.3 there was the `analytic_functions` subpackage where `blackbody_nu` and `blackbody_lambda` were defined. 

I installed astropy v1.3 in a conda environment and verified I can reproduce the v1.3 `blackbody_nu` output by changing `const.sigma_sb`, `const.h` and `const.k_b` as above.

**Comment by pllim** [comment]
Thanks, that looks promising. Is there a proper way to "reset" those constants to their original values (i.e., from latest astropy)? Ideally, I would have used a `with` context manager but it is not available here.

**Comment by stargaser** [comment]
It seems to work to set the values back to the astropyconst20 ones, e.g.

```
from astropy.constants import astropyconst20
const.sigma_sb = si.sigma_sb = astropyconst20.sigma_sb
const.h = si.sigma.h = astropyconst20.h
const.k_B = si.k_B = astropyconst20.k_B
```

There has been some discussion of making a context manager, still desired by @mhvk if I understand correctly. The versioning work in Astropy 2.0 could be the foundation for that.

**Comment by mhvk** [comment]
Yes, I worried this would not be so easy...  Here, the black body function uses the constants, so one is in luck, but on other places, something will use a unit that is defined via a constant, and then this trick will not work.  But as noted by @stargaser, what is implemented now at least provides the foundation for doing the more complicated thing.

**Comment by pllim** [comment]
Putting that incantation in `setup_module` for `pytest` is not working for me. Let's keep this open for now until I can figure this out on my side. Thanks!

**Comment by pllim** [comment]
Small typo in the solution above -- `const.h = si.sigma.h = astropyconst20.h` should be `const.h = si.h = astropyconst20.h`. Otherwise, this works for me. Thank you!
