### ISSUE TITLE
WCSAXES not found error of CCDData

### ISSUE THREAD

**Issue by ysBach** [astropy/astropy#6386]
I have downloaded a random r-band image from SDSS DR12 ( [image search](https://dr12.sdss.org/fields/name?name=ngc+1132) and [download link](https://dr12.sdss.org/sas/dr12/boss/photoObj/frames/301/6572/6/frame-g-006572-6-0210.fits.bz2)) and saved as "ngc1132_r.fits".
I wanted to load this image but the ``CCDData`` gave ``KeyError``:

```python
from astropy.nddata import CCDData
from astropy.io import fits
from astropy.wcs import WCS

ccd = CCDData.read('data/ngc1132_r.fits')
```

The following is the error message:
```
WARNING: FITSFixedWarning: RADECSYS= 'ICRS ' / International Celestial Ref. System 
the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
Traceback (most recent call last):

  File "<ipython-input-28-06a8bd5b201d>", line 1, in <module>
    ccd = CCDData.read('data/ngc1132_r.fits', unit='adu')

  File "/home/ysbach/anaconda3/lib/python3.6/site-packages/astropy/nddata/mixins/ndio.py", line 29, in read
    return io_registry.read(cls, *args, **kwargs)

  File "/home/ysbach/anaconda3/lib/python3.6/site-packages/astropy/io/registry.py", line 531, in read
    data = reader(*args, **kwargs)

  File "/home/ysbach/anaconda3/lib/python3.6/site-packages/astropy/nddata/ccddata.py", line 521, in fits_ccddata_reader
    hdr, wcs = _generate_wcs_and_update_header(hdr)

  File "/home/ysbach/anaconda3/lib/python3.6/site-packages/astropy/nddata/ccddata.py", line 419, in _generate_wcs_and_update_header
    del new_hdr[k]

  File "/home/ysbach/anaconda3/lib/python3.6/site-packages/astropy/io/fits/header.py", line 226, in __delitem__
    raise KeyError("Keyword '{}' not found.".format(key))

KeyError: "Keyword 'WCSAXES' not found."
```

The original file seems to have correct WCS and the following code works without any problem:

```python
from astropy.io import fits
from astropy.wcs import WCS

hdul = fits.open('data/ngc1132_r.fits')
w = WCS(hdul[0].header)
```

What does it mean by the ``KeyError`` of ``CCDData``? Should I just use ``astropy.io.fits`` than ``CCDData`` in this case?

**Comment by nden** [comment]
This appears to be a bug in ccddata. It's attepmting to delete a keyword which is not in the header.

**Comment by ysBach** [comment]
BTW-- I just found the same code works perfectly if I use ``ccdproc.CCDData``.
I thought ``astropy.nddata.CCDData`` is identical to ``ccdproc.CCDData`` but it seems not :o ...

**Comment by mwcraig** [comment]
@ysBach -- thanks for reporting this!

**Comment by mwcraig** [comment]
The reason it doesn't show up in `ccdproc.CCDData` is that we never actually removed the WCS keywords from the header. That meant it was possible to have the header and the WCS object in conflict with each other, because you could change them indpendently.

**Comment by bsipocz** [comment]
@ysBach - I wonder when you say that the same code worked for ccdproc.CCDData, you've never actually seen a unit related error? What is the version of you ccdproc and astropy in that case?

```
ValueError: 'nanomaggy' did not parse as unit: At col 0, nanomaggy is not a valid unit. 
```

**Comment by ysBach** [comment]
@bsipocz Oh, sorry for giving you confusion. I put ``unit='ADU'`` (just to avoid ``ValueError`` and see what happens).
