### ISSUE TITLE
Wrong Earth radius

### ISSUE THREAD

**Issue by Juanlu001** [astropy/astropy#6391]
As part of #6083 `astropy.constants` was updated, and in particular a new value for the Earth radius, called `"Nominal Earth equatorial radius"` and equal to `6.3568e6` was added:

https://github.com/astropy/astropy/blob/v2.0/astropy/constants/iau2015.py#L95

However, according to "IAU 2015 Resolution B3 on Recommended Nominal Conversion Constants for Selected Solar and Planetary Properties":

https://arxiv.org/abs/1510.07674

![screenshot-2017-7-24 - 1510 07674 pdf](https://user-images.githubusercontent.com/316517/28540393-7f1ce650-70b5-11e7-85f5-e8901b7ae6ec.png)

the nominal equatorial radius of the Earth is 6.3781e6 m and the nominal polar radius of the Earth is 6.3568e6. Which means that, either the variable should read `"Nominal Earth polar radius"` or the value should be changed to `6.3781e6`.

Also, from the same report:

"If equatorial vs. polar radius is not explicitly specified, it should be understood that nominal terrestrial radius refers specifically to [equatorial], following common usage".

**Comment by stargaser** [comment]
@Juanlu001 - thank you for catching this. It was my intention to use the nominal equatorial radius and apparently I took the polar value by accident.

**Comment by eteq** [comment]
@stargaser - I think this is clearly enough a bug that you can just fix this for 2.0.1 and not have the old one be "versioned".  

If it were a bit less explicit (e.g. "Earth radius"), it's debatable and might want to be versioned, but this is pretty clearly just a typo.
