### ISSUE TITLE
Automatically pass arguments from python setup.py test to pytest

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6392]
At the moment, only a subset of pytest command-line arguments are available for ``python setup.py test``, and the rest need to be passed by ``-a``, e.g. ``python setup.py test -a "-x"``. It would be nice to simply pass any unrecognized arguments to pytest for simplicity.

**Comment by drdavella** [comment]
I wouldn't mind looking at this one. It would go in hand nicely with #5806.

**Comment by drdavella** [comment]
@astrofrog I'm not sure if you had a particular approach in mind for this, but after thinking about it for a little while I think it's going to be pretty difficult to implement. It seems like it would require intercepting the argument parsing for the `AstropyTest` command. It's possible this could be done with some metaclass magic, but it won't be pretty and may involve reimplementing argument handling logic, unless I can find it in the API for `setuptools` or `distutils`.

I'll keep thinking about it a bit but just wanted to see if you had any concrete ideas in mind when you opened the issue.

**Comment by bsipocz** [comment]
I suppose this is a "won't fix". 
Please reopen if we change direction and come back to enhance our own test  runner instead of moving away from it.
