### ISSUE TITLE
Template Docs: 'packagename' replacer broken?

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#6396]
I just tried to use http://docs.astropy.org/en/stable/development/affiliated-packages.html?packagename=multicomponentfitting

and found that <packagename> are still left as <packagename> in the code blocks, e.g.:

![image](https://user-images.githubusercontent.com/143715/28635543-3e2a1b42-71f8-11e7-9972-cee3f634db76.png)

**Comment by bsipocz** [comment]
Thanks @keflavich, it indeed looks broken, e.g. it still works with 1.3.3:

http://docs.astropy.org/en/v1.3.3/development/affiliated-packages.html?packagename=multicomponentfitting

**Comment by bsipocz** [comment]
On the other hand this docs is quite outdated, I wonder whether we have an ETA of moving things over to the template? @Cadair?

**Comment by bsipocz** [comment]
The package template docs has been moved out of core, so closing this issue here.
