### ISSUE TITLE
Should/could HDUList.info() report constant array extensions (from STScI)?

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy#6401]
I have a fits file that uses constant arrays for some of its extensions. When using ``HDUList.info()`` the following is returned:

```
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU     229   ()              
1    SCI         ImageHDU        95   (534, 512)   float32   
2    ERR         ImageHDU        49   ()              
3    DQ          ImageHDU        41   ()
```

This implies that the ``ERR`` & ``DQ`` extensions are empty, however, this is not entirely the case. When reading the header for the ``ERR`` extension the array exists as a constant array.

```
NPIX1   =                  534 / length of constant array axis 1                
NPIX2   =                  512 / length of constant array axis 2                
PIXVALUE=        4.0400000E+00 / values of pixels in constant array     
```

This has recently lead to some confusion in believing that these arrays were not populated by [HSTCAL](https://github.com/spacetelescope/hstcal). I was wondering if perhaps ``HDUList.info()`` could display this info?

From what has been explained to me (sorry I haven't checked) these keywords and their use as a constant array is __not__ a FITS standard but that this is just an STScI convention. I can understand that this might be _the_ road blocker in this request, but here it is none the less.

**Comment by pllim** [comment]
AFAIK this is specific to HSTCAL. If that's the case, such functionality is more appropriate in stsci.tools or the like.

**Comment by pllim** [comment]
Or if IRAF catfits reports it differently from fitsinfo, then it might fall into STAK

cc @SaraOgaz

**Comment by SaraOgaz** [comment]
Well, we're not doing a separate catfits thing for STAK, fitsinfo was deemed a good enough substitute...

**Comment by MSeifert04** [comment]
Is it possible to share one "affected" file?

**Comment by pllim** [comment]
Here is the file. Remember to remove the fake ".txt" extension before opening; I had to add it so I can upload.
[jacnd8qlq_raw.fits.txt](https://github.com/astropy/astropy/files/1188243/jacnd8qlq_raw.fits.txt)

```python
>>> from astropy.io import fits
>>> pf = fits.open('jacnd8qlq_raw.fits')
>>> pf.info()
Filename: jacnd8qlq_raw.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     216   ()      
  1  SCI           1 ImageHDU        97   (534, 512)   int16 (rescales to uint16)   
  2  ERR           1 ImageHDU        49   ()      
  3  DQ            1 ImageHDU        43   ()      
>>> pf[2].data  # returns None, FITS does not recognize this as valid array
>>> pf[2].header['PIXVALUE']
0.0
```

A workaround for STScI people who needs to read this into Astropy outside of HSTCAL:
```python
>>> import numpy as np
>>> err_array = np.empty((pf[1].header['NAXIS2'], pf[1].header['NAXIS1']))
>>> err_array.fill(pf[2].header['PIXVALUE'])
>>> err_array
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])
```

**Comment by MSeifert04** [comment]
@pllim Thanks but it gives me an `The request signature we calculated does not match the signature you provided. Check your key and signing method.` error and Firefox complains about a possible XSS attempt.

**Comment by MSeifert04** [comment]
Okay, it worked with Chrome. Sorry for the noise.

**Comment by saimn** [comment]
So, this seems very specific to HST/STScI, I don't see how or why it could be supported in `HDUList.info()` ? I mean, from the FITS point of view the data is empty. Maybe there are other tools at STcI that could be better suited for this ?

**Comment by MSeifert04** [comment]
I wouldn't mind having some constant array extensions (could save a lot of hard drive space) but I don't think `io.fits` would be the best place for these. But that would be more suitable in a dedicated package or `io.registry`.

**Comment by pllim** [comment]
I agree. Thank you for all your feedback. I will close this and consult with STScI on where the best place for such an utility would be.
