### ISSUE TITLE
Possible bug in fitting with multidimensional arrays

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6403]
This is a bug report received via feedback@astropy.org - unfortunately the email of the submitter no longer works, but I'll put this here in case the bug is still present:

---

I have juste upgraded to astropy 1.3.2

in modeling.fitting, line 600:

```python
full_deriv = (np.ravel(weights) * np.array(model.fit_deriv(x, y, *model.parameters)).T).T
```

gives me an error, when using the LevMarLSQFitter(), with Gaussian2D models, and weights.
For instance, with XX, YY, im and W being all 32x32 numpy array:

```python
    fitter=fitting.LevMarLSQFitter()
    fit = fitter(myGaussianModel, XX, YY, im, weights=W)

    /home/samuel/Apps/anaconda2/lib/python2.7/site-packages/astropy/modeling/fitting.py in _wrap_deriv(params, model, weights, x, y, z)
        598                 full_deriv = np.ravel(weights) * np.array(model.fit_deriv(x, *model.parameters))
        599             else:
    --> 600                 full_deriv = (np.ravel(weights) * np.array(model.fit_deriv(x, y, *model.parameters)).T).T
        601                                

    ValueError: operands could not be broadcast together with shapes (1024,) (32,32,6)
```

In astropy 1.1.2, this line was different:

```python
	full_deriv = np.array(model.fit_deriv(x, y, *model.parameters))
```
and I didn't get any error.

**Comment by nden** [comment]
I can't reproduce this with current master. What are the shapes of all input arrays? In general, they should be the same. 
@kne42 If you still feel this is a bug please post a short example showing the shape of the arrays.

**Comment by mirca** [comment]
I don't see this error either.

**Comment by trmrsh** [comment]
Hi, I have run into exactly this problem, and I don't think it is to do with array shapes. I think there is a genuine bug. It happens when using weights and trying to fix a parameter. I have X, Y and weights arrays all with shape (41,41), and when trying to fit a 2D gaussian plus a constant (5 parameters), but holding the FWHM fixed I got:

 File "XXX/3.4.6/lib/python3.4/site-packages/astropy/modeling/fitting.py", line 736, in _wrap_deriv
    full_deriv = (np.ravel(weights) * np.array(model.fit_deriv(x, y, *model.parameters)).T).T
ValueError: operands could not be broadcast together with shapes (1681,) (41,41,5)

**Comment by nden** [comment]
@trmrsh Could you post your failing example here.

**Comment by trmrsh** [comment]
Its hard to encapsulate as it part of a much larger piece of code, but first I rolled my own model (I tried a compound model but it did not seem to work well for me):

    class Gaussian(Fittable2DModel):
        constant = Parameter()
        height = Parameter()
        xcen = Parameter()
        ycen = Parameter()
        fwhm = Parameter()

        EFAC = np.sqrt(8.*np.log(2.))

        @staticmethod
        def evaluate(x, y, constant, height, xcen, ycen, fwhm):
            rsq = (x-xcen)**2+(y-ycen)**2
            return constant+height*np.exp(-rsq/(2.*(fwhm/Gaussian.EFAC)**2))

        @staticmethod
        def fit_deriv(x, y, constant, height, xcen, ycen, fwhm):

            # intermediate time savers (but each the same dimension as x and y)
            xoff = x-xcen
            yoff = y-ycen
            rsq = xoff**2 + yoff**2
            alpha = 1/(2.*(fwhm/Gaussian.EFAC)**2)

            # derivatives
            d_constant = np.ones_like(x)
            d_height = np.exp(-alpha*rsq)
            d_xcen = (2*alpha*height)*d_height*xoff
            d_ycen = (2*alpha*height)*d_height*yoff
            d_fwhm = (2*alpha*height/fwhm)*d_height*rsq

            return [d_constant, d_height, d_xcen, d_ycen, d_fwhm]

Then used it in:

    # x & y are 1D arrays
    x = wind.x(np.arange(wind.nx))
    y = wind.y(np.arange(wind.ny))
    X, Y = np.meshgrid(x, y)

    # generate weights
    weights = 1./np.sqrt(read**2+np.maximum(0,wind.data)/gain)

    # create symmetric 2D Gaussian model
    gauss = Gaussian(sky, height, xcen, ycen, fwhm)

    # set a minimum for fwhm
    gauss.fwhm.min = fwhm_min

    # fix the FWHM
    gauss.fwhm.fixed = True

    # Lev-Marq fitting
    fitter = fitting.LevMarLSQFitter()

    # run the fit
    fit = fitter(gauss, X, Y, wind.data, weights=weights)


This results in the problem, which I do not encounter if I do not fix the FWHM. Sorry as I realise this is not a proper example.

**Comment by nden** [comment]
@trmrsh I can reproduce this now. Thanks for the example.
