### ISSUE TITLE
Coverage can't pull file contents

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#6406]
When I try to open the coverage report for a PR (say https://coveralls.io/builds/12624484/source?filename=astropy%2Fio%2Ffits%2Ffile.py) I just see an error message:

```
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API. 
```

**Comment by bsipocz** [comment]
github had issues this afternoon, maybe it's related. I don't see the error.

**Comment by MSeifert04** [comment]
You're right. Now it's working.
