### ISSUE TITLE
Need better error when trying to run parallel tests without pytest-xdist

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#6414]
Not to be confused with #2871. I tried running the following command:
`./setup.py test -j 2`

This resulted an error:
> running test
running build
running build_py
running pre_hook from astropy._erfa.setup_package for build_py command
running pre_hook from astropy.modeling.setup_package for build_py command
running build_ext
running pre_hook from astropy._erfa.setup_package for build_ext command
running pre_hook from astropy.modeling.setup_package for build_ext command
building 'astropy._compiler' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ddavella/miniconda3/envs/astropy-pytest/include/python3.6m -c astropy/_compiler.c -o build/temp.linux-x86_64-3.6/astropy/_compiler.o
gcc -pthread -shared -L/home/ddavella/miniconda3/envs/astropy-pytest/lib -Wl,-rpath=/home/ddavella/miniconda3/envs/astropy-pytest/lib,--no-as-needed build/temp.linux-x86_64-3.6/astropy/_compiler.o -L/home/ddavella/miniconda3/envs/astropy-pytest/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/astropy/_compiler.cpython-36m-x86_64-linux-gnu.so
skipping 'astropy/table/_np_utils.c' Cython extension (up-to-date)
skipping 'astropy/table/_column_mixins.c' Cython extension (up-to-date)
skipping 'astropy/io/ascii/cparser.c' Cython extension (up-to-date)
skipping 'astropy/cosmology/scalar_inv_efuncs.c' Cython extension (up-to-date)
skipping 'astropy/convolution/boundary_none.c' Cython extension (up-to-date)
skipping 'astropy/convolution/boundary_fill.c' Cython extension (up-to-date)
skipping 'astropy/convolution/boundary_wrap.c' Cython extension (up-to-date)
skipping 'astropy/convolution/boundary_extend.c' Cython extension (up-to-date)
skipping 'astropy/stats/lombscargle/implementations/cython_impl.c' Cython extension (up-to-date)
usage: -c [options] [file_or_dir] [file_or_dir] [...]
-c: error: unrecognized arguments: -n 2
  inifile: /tmp/astropy-test-a2t8rjyj/setup.cfg
  rootdir: /tmp/astropy-test-a2t8rjyj

Ironically, I stumbled across this while looking at #5806.

Incidentally, it would be nice if using `-j/--parallel` without an argument defaulted to "use all cores" instead of having to provide a negative number argument. This would be more in line with the way that `make` works. However, I suspect that the argument parsing logic in `setuptools` is too brittle to handle this.

**Comment by bsipocz** [comment]
I wonder when was the last time it worked, I suspect long time ago as cannot recall we ever used it for any of the testings. 

If it's seriously broken, beyond repair, what about removing it altogether?

**Comment by drdavella** [comment]
It looks like if I install `pytest-xdist` then it actually "works". So at the very least there should be some better error handling.

However, by "works" I mean I get a lot of scary errors in the test collection phase.

**Comment by astrofrog** [comment]
It used to work and it'd be nice to get it working again, as it's actually also a good way to identify issues that might appear in multi-threaded uses of astropy.

**Comment by astrofrog** [comment]
The reason we didn't test it on the CI is because it didn't work well on Travis, but CircleCI has the ability to assign multiple cores to a job, so we could maybe test it there (we didn't have CircleCI last time I tried to run --parallel on the CI)

**Comment by astrofrog** [comment]
@drdavella - would you be interested in trying to add a fix to have a better error message if pytest-xdist is not installed? (we already do this for e.g. coverage)

**Comment by astrofrog** [comment]
I'm seeing the same kind of issue as described in #2871 btw. I'm going to leave some comments in that issue relevant to trying to fix things.

**Comment by drdavella** [comment]
@astrofrog yes I can improve the error message.

I can't successfully run the tests in parallel. I get errors along the lines of the following:
> ERROR collecting gw0
Different tests were collected between gw1 and gw0. The difference is:
[snip]

Also I see a lot of the warnings mentioned in #6025 even though I've never encountered those before.

**Comment by astrofrog** [comment]
Yes the issue is basically when there is a non-deterministic order to the test collection, for instance if we use parametrize with a dictionary or something like that. There's something about the fixtures in test_iau_fullstack that is causing issues, though it could very well be a pytest bug. I also see the import warnings from #6025 when running the tests.

I think we should try and get this fixed and maybe start running in parallel on one of the CI setups. Someone needs to try and dig deeper into why those coordinate tests are failing. I can try and look into it in the near future if no one else is interested (but @drdavella, feel free to take a look if you like a challenge!)

**Comment by drdavella** [comment]
The only clue I saw about the `test_iau_fullstack` tests is they appear to be the only tests in astropy that are using module-level test fixtures.

**Comment by astrofrog** [comment]
@drdavella - bingo, the following minimal example causes failures:

```python
import pytest


@pytest.fixture(scope="module", params=['A', 'B'])
def fa(request):
    return request.param


@pytest.fixture(scope="module", params=['A', 'B'])
def fb(request):
    return request.param


def test_it(fa, fb):
    pass
```

```
pytest test.py  -n 4
```

I can try reporting it to pytest-xdist

**Comment by astrofrog** [comment]
Reported here: https://github.com/pytest-dev/pytest-xdist/issues/198

**Comment by astrofrog** [comment]
Let's keep https://github.com/astropy/astropy/issues/2871 as the issue for the non-deterministic tests, and I'll rename this issue to be about having a better warning when trying to run without pytest-xdist.
