### ISSUE TITLE
Decide on astropy_native for writing FITS files from tables with Time columns

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#6427]
As a follow-on to #6176, decide what should be done when *writing* a table that has native Time column(s) (mixins).

EDIT - was based on a misunderstanding of current behavior, see below and mostly ignore this.

The question is about potential breakage and always adhering to the FITS standard to the extent possible.  Options include:
- Have an `astropy_native` option like in read(), with default being:
   - False (as in #6176) for continuity with current behavior
   - True - likely breaks some code in the wild.  This is a definite API change.
- Different name for the option, but same concept
- Don't have the option at all.  I'm :-1: on this because it is likely to break code without any easy way (even with code changes) to maintain current behavior.

**Comment by taldcroft** [comment]
@cdeil - comments from the gammapy perspective appreciated.  You mentioned previously being happy that this is back-compatible, but I wasn't sure if that was for reading or for writing.

**Comment by mhvk** [comment]
Note this is about *writing* - what code could break? Or do you mean that what used to cause an exception now passes?

**Comment by mhvk** [comment]
Just to be clear:  as implemented, #6176 is *not* continuity with current behaviour but an API change: if `astropy_native=False` (default), the time column is converted to a regular column and stored, while in current master this raises an exception. I think this is the worst of both worlds, and strongly disagree with this  being the default. Indeed, I think it should not even be an option, at least in #6176.

Given the above, in my opinion, the only choice right now is whether we explicitly give the users the option to ensure an error is raised on a `Time` mixin column.

**Comment by taldcroft** [comment]
@mhvk - *oops*, I had it in my mind that the current behavior (2.0) is to write out the column as the formatted value, not to raise an exception.

With this I agree to remove `astropy_native` in writing, but replace it by having the code pay attention to `TimeInfo.serialize_method['fits']`, which defaults to `'jd1_jd2'` but can be set to `'formatted_value'`.  Sound OK?

**Comment by mhvk** [comment]
Yes to both; good idea to use `serialize_method` again!

**Comment by cdeil** [comment]
Reading over the discussion above, I think there are no backwards-compat concerns here and you two seem to agree on a good way to improve the writing, no?
(unsubscribing from notifications now, ping me again if I might be able to help with feedback from the user perspective)

**Comment by mhvk** [comment]
closing since I think we converged here.
