### ISSUE TITLE
Document better which models currently support units

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6432]
Currently, in http://astropy.readthedocs.io/en/latest/modeling/units.html , it only says "some models like ...", which is very cryptic. Is there a place where I can get the exact list of models that support units without code-diving?

My motivation is that I would like to remove my own hack to support units for some selected models and use the built-in one, so a complete list would be helpful for me to determine which of my own hack can be removed.

@astrofrog or @nden ?

**Comment by astrofrog** [comment]
I agree this should be clarified. I think most models do support it, except , Legendre, Hermite, and a few other polynomial ones. I don't have time to dig in right now, so if anyone has a chance to check, feel free to!
