### ISSUE TITLE
Clearer naming of velocities in coordinates?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6434]
Inspired by #6425: would it make sense to have a default name for velocities in coordinates that is clearer than, e.g., `d_phi`? This comes directly from the `Differential`, where it is logical, since the differential need not be a first-order time derivative. But for coordinates, the velocities are known to be first-order time derivatives, and perhaps a better name is useful. Right now, we translate names for common frames, but not for less common ones (such as cylindrical in #6425). One could imaging having a standardized "default" translation, such as, `d_X_dt` suggested by @jobovy in #6425. Or be a bit fancier, and translate everything that has units of length/time as `v_X` and everything that has angle/time as `pm_X`.

@adrn, @eteq?

EDIT: independently, we should what is done is documented more clearly.

**Comment by Juanlu001** [comment]
As I stated in https://github.com/astropy/astropy/issues/6436, it's weird that I instantiate a reference frame using `v_{x,y,z}` and then get `d_{x,y,z}` back after transformation. Both `d_X_dt` and `v_X`/`pm_X` sound good to me (although "angular velocity", `w` or omega are more common than "proper motion" in engineering). However, I would still try to be consistent with the input naming.

**Comment by jobovy** [comment]
I also think it's odd to refer to quantities as a 'proper motion' if they aren't actual proper motions on the celestial sphere. Especially so because one cannot convert proper motions x distance to velocities without using a unit equivalency. So I think it would be better to return quantities as angular velocities that can be simply converted to linear velocities by multiplying by the radius and asking for the output in one's preferred units.

**Comment by mhvk** [comment]
@jobovy - the equivalency will be needed for any angular velocity, unless we drop the 'radian' from it - but then it is not obvious it is an angular velocity any more. I think this is actually fine - it is OK to be forced to realize you are using a small-angle approximation.

**Comment by mhvk** [comment]
Update: the plan with @eteq and @adrn is going to "Or be a bit fancier, and translate everything that has units of length/time as `v_X` and everything that has angle/time as `pm_X`." WIth the addition of an automatic `cos{Y}` if needed.  These are just default names, still overridden for particular combinations of frames and representations.

**Comment by mhvk** [comment]
See #6856 for a fix
