### ISSUE TITLE
Better document bolometric_flux for BlackBody1D

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6456]
Currently in `BlackBody1D` model
```python
temperature = Parameter(default=5000, min=0, unit=u.K)
bolometric_flux = Parameter(default=1, unit=u.erg / u.cm ** 2 / u.s)
```
but to get it to produce the same result as `blackbody_nu` function, I need to give the reverse of normalization used in the model evaluation (see https://gist.github.com/pllim/babea1d1337da665740439887c5b6f5f)
```python
bolometric_flux = const.sigma_sb * temperature ** 4 / np.pi
```

I can see how setting the latter as default is problematic because it depends on the other parameter, `temperature`. At the very least, this should be better documented, perhaps in `BlackBody1D` docstring. What do you think, @astrofrog ?

**Comment by shilpi1958** [comment]
@pllim I would like to work on this issue. I know the physics but   can't understand the problem properly. Can you please explain it a bit. Thanks :)

**Comment by kakirastern** [comment]
Hi, is this issue still open? If so, can I work on it?

**Comment by kakirastern** [comment]
I can certainly add a docstring or two to give the normalization 
```
fac = constant.sigma_sb * temperature ** 4 / numpy.p
```
as an extra step, so that the `blackbody` model would produce the same result as the `blackbody_nu` function upon evaluation. So I would add the following lines as well to fill in the gaps (which are from your link in [https://github.com/astropy/astropy/issues/6456#issue-251354540](https://github.com/astropy/astropy/issues/6456#issue-251354540)):
```
w = np.arange(3000, 3100, 10) * u.AA
>>> bb_astro = _models.BlackBody1D(t, bolometric_flux=fac)
>>> bb_astro(w)
```
Is this what you wanted? I can certainly open a PR for it...

**Comment by kakirastern** [comment]
So if I do the following: 
```
>>> import numpy as np
>>> from astropy import units as u
>>> from astropy.modeling.blackbody import blackbody_nu
>>> blackbody_nu(w,t).si
<Quantity [2.40339754e-09, 2.44947680e-09, 2.49604354e-09, 2.54309638e-09,
           2.59063389e-09, 2.63865453e-09, 2.68715672e-09, 2.73613877e-09,
           2.78559895e-09, 2.83553543e-09] kg / (rad2 s2)>
```

It mirrors what you do without invoking `blackbody_nu` as:
```
>>> import numpy as np
>>> from astropy import constants as const
>>> from astropy import units as u
>>> from astropy.modeling import models as _models
>>> t = 5500 * u.K
>>> fac = const.sigma_sb * t ** 4 / np.pi
>>> fac
<Quantity 16516273.034342945 W / m2>
>>> w = np.arange(3000, 3100, 10) * u.AA
>>> bb_astro = _models.BlackBody1D(t, bolometric_flux=fac)
>>> bb_astro(w)
<Quantity [  2.40339754e-09,  2.44947680e-09,  2.49604354e-09,
             2.54309638e-09,  2.59063389e-09,  2.63865453e-09,
             2.68715672e-09,  2.73613877e-09,  2.78559895e-09,
             2.83553543e-09] W / (Hz m2)>
```

**Comment by pllim** [comment]
Yes, you got it, @kakirastern !

**Comment by kakirastern** [comment]
Sure, will get on with it...

**Comment by kakirastern** [comment]
PR #8495 opened to address this Issue.
