### ISSUE TITLE
Representation median

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6463]
It would be nice if Representation.median existed in the same way as Representation.mean. It would also be nice to expose nan-friendly versions of this. This makes me wonder though if it wouldn't be better to simply expose the ``_apply`` method in some way?

**Comment by mhvk** [comment]
Hmm, but taking a median assumes one has a way to order, and how can one order 3-dimensional vectors? Ideally, any ordering would be independent of the orientation of the axes, but I don't think this is possible. Indeed, this is also why I did not implement `.min()` and `.max()` when I added `.mean()`. (Note that the same problem happens for complex numbers, and numpy's arbitrary choices have led to quite a bit of confusion - avoid the temptation to guess and all that!)

**Comment by astrofrog** [comment]
Good point, I hadn't thought of that. Shall I close this issue?

**Comment by mhvk** [comment]
> Shall I close this issue?

Probably, yes, though if you have the energy maybe it is an idea to add a line or two to the documentation? It would be near http://docs.astropy.org/en/latest/coordinates/representations.html#vector-arithmetic - though I had sufficient trouble re-finding this that perhaps nobody else uses representations for vectors!

**Comment by astrofrog** [comment]
I'll close this - let's add something if someone else asks the same question (I'm not convinced they will!)
