### ISSUE TITLE
CFITSIO rather out of date

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6475]
We bundle CFITSIO v. 3.35 (from `cextern/cfitsio/changes.txt`) from June 2013, but the library is now up to 3.41 (Nov 2016), with the log stating there were a number of significant bug fixes [1]. We probably should update our version. Separately, rather than quieting compilation warnings, it would long-term be more helpful to upstream patches...

[1] https://heasarc.gsfc.nasa.gov/fitsio/fitsio.html

**Comment by pllim** [comment]
Tentatively milestoning this to v3 since this would be nice to have in the next release. But we can also re-milestone if no one has time to do it.

**Comment by mhvk** [comment]
Encouraging is that in Debian the newest version does not give any problems (see https://github.com/astropy/astropy/pull/6474#issuecomment-324423960), so hopefully this will not be much work...

**Comment by MSeifert04** [comment]
I think we only use the compression module there. Would be interesting to see the diff. Anyone interested in making an experimental PR if just updating CFITSIO works?

**Comment by olebole** [comment]
In the past, there were some problems with newer cfitsio, which are however solved now: #4646 and #4647. Build and CI tests for astropy on Debian always run with the installed version of cfitsio, so I do not expect any problems here. Last full run [here](https://ci.debian.net/data/autopkgtest/unstable/amd64/p/python-astropy/20170822_032522/log.gz). Other OSs may differ, however.

**Comment by olebole** [comment]
You may also check Macports; they also use a separate cfitsio version... cc @cdeil

**Comment by mhvk** [comment]
See #6477 for an attempt to update cfitsio.

**Comment by saimn** [comment]
Done with #6477, thanks @mhvk
