### ISSUE TITLE
Travis on merge-to-master is failing because of numpy-dev

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6480]
The merge commits to travis seem to fail consistently. I have to admit I just ignored them, thinking it was likely a URL error or so, but at least at https://travis-ci.org/astropy/astropy/builds/268645439?utm_source=email&utm_medium=notification it is due to a numpy-dev branch that fails (and does not seem to be an "allowed failure"). Is this intended? Is it that the `cron` version somehow gets run?
cc @bsipocz, @astrofrog

**Comment by bsipocz** [comment]
If I recall, the idea was that we should always allow the numpy-dev build to fail for PRs, as those failures will most likely be unrelated and usually requires someone more involved either in astropy or numpy to do the fixes. 

But if we let them fail always, it's very likely that there will be a delay noticing the possible issues, thus the they are run once a day from cron, so we can get out notification e-mail.

However those style changes are seems to be stalled in numpy-dev, holding up #6090, and now permanently failing the travis cron job. 

I think it's fine not to run them from cron temporarily until the styles are decided and fixed upstream.

**Comment by mhvk** [comment]
Yes, agreed with that logic. I think the main reason I was puzzled was that I thought the e-mails I was getting were related to failures of PRs I merged. I'll close this issue for now.
