### ISSUE TITLE
fits.getdata returns NaNs

### ISSUE THREAD

**Issue by Amarchuk** [astropy/astropy#6485]
Hi,

I am using astropy 2.0.1, Python 2.7. When I try to get FITS data into array ([fits file link](http://www.mpia.de/THINGS/Data_files/NGC_628_NA_MOM2_THINGS.FITS)) by 

```python
from astropy.io import fits
image_data = fits.getdata('NGC_628_NA_MOM2_THINGS.FITS')
```
I get numpy array full of NaNs

```python
array([[[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
         [ nan,  nan,  nan, ...,  nan,  nan,  nan],
         [ nan,  nan,  nan, ...,  nan,  nan,  nan],
         ..., 
         [ nan,  nan,  nan, ...,  nan,  nan,  nan],
         [ nan,  nan,  nan, ...,  nan,  nan,  nan],
         [ nan,  nan,  nan, ...,  nan,  nan,  nan]]]], dtype=float32)
```

Open as HDU list 
```python
hdu_list = fits.open('NGC_628_NA_MOM2_THINGS.FITS')
image_data = hdu_list[0].data
```
return the same result. But SAOImage ds9 can successfully open and show data.

**Comment by MSeifert04** [comment]
That image just has a lot `nan`s at the edges. It looks okay though:

```
from astropy.io import fits
import matplotlib.pyplot as plt

data = fits.getdata('C:/Users/Admin/Downloads/NGC_628_NA_MOM2_THINGS.FITS')
plt.imshow(np.squeeze(data), origin='lower', cmap='gray')
```

![png image 573 x 429 pixels](https://user-images.githubusercontent.com/14200878/29786433-6ed34e1a-8c2b-11e7-9bbd-9f6fd16adb19.png)

**Comment by Amarchuk** [comment]
Ooops, my fault.
@MSeifert04 Thanks a lot for this super-fast answer!

**Comment by MSeifert04** [comment]
No problem. Good luck with the data :)
