### ISSUE TITLE
Consider adding a Time scale of LOCAL (or None)

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6487]
The FITS standard allows for a `Time` scale of `LOCAL`, for free-running clocks and simulations. In principle, it would not be difficult to support this in `Time` - it could be a scale that cannot be converted to any other, and to which only `TimeDelta` with `scale=None` could be added.

**Comment by vermashresth** [comment]
Hi @mhvk
This seems an old issue but I would like to work on this. I have some doubts.
Is it allowed for other time scales to be converted to local time scale? And for writing all the special cases of LOCAL time scale, should we explicitly specify conditions of time scale being LOCAL in _set_scale or write it somewhere else?

**Comment by mhvk** [comment]
@vermashresth - sure, a contribution would be welcome. As you saw on top, I had thought only about converting LOCAL to other timescales -- which should never be allowed. I think that similarly we should not allow conversion of other time scales to local; we should treat it as a clock which is in itself precise but for which we do not know the scale, hence we cannot convert from or to it.

As for implementation, having a quick look again, I think we actually need a 'local' scale both for `Time` and `TimeDelta`. For the latter, it is relatively easy: you just add another set to the ones already known `LOCAL_SCALES = ('local',)` and then add that to `TIME_DELTA_TYPES`. For `Time`, it is a bit more involved since there you need to add similar machinery, i.e., you'd need to rename `TIME_SCALES` to something like `STANDARD_TIME_SCALES`, define a `TIME_TYPES` dict with that and `LOCAL_SCALES`, and then make a new `TIME_SCALES` equals `TIME_TYPES.keys()` -- and then of course adapt the code inside as well to use this.

p.s. I should add that this is really not that easy an issue; please only proceed if you are fairly certain you can do it. In particular, I will not have much time to give detailed advice in the coming months, so cannot help iterate multiple times.

**Comment by vermashresth** [comment]
Hi! @mhvk 
I have made a PR and the required valid operations for `local` time scale work now. But a lot of tests iteratively test over all scale types and now not all of them are valid, thus they fail. Should we change names so that they are still tested over the old `TIME_SCALES` which is now `STANDARD_TIME_SCALE` or make changes inside the tests?

**Comment by mhvk** [comment]
@vermashresth - great! I moved discussion to #7122.

**Comment by mhvk** [comment]
fixed by #7122
