### ISSUE TITLE
FITS: BSCALE and BZERO incorrectly passed to `_get_scaled_image_data` as strings

### ISSUE THREAD

**Issue by darthoctopus** [astropy/astropy#6495]
When attempting to get data from a compressed FITS file, the following error message is returned:

```
In [3]: f[0].data
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    733         try:
--> 734             return obj.__dict__[self._key]
    735         except KeyError:

KeyError: 'data'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-3-4d446759185c> in <module>()
----> 1 f[0].data

/usr/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    734             return obj.__dict__[self._key]
    735         except KeyError:
--> 736             val = self.fget(obj)
    737             obj.__dict__[self._key] = val
    738             return val

/usr/lib/python3.6/site-packages/astropy/io/fits/hdu/image.py in data(self)
    241             return
    242 
--> 243         data = self._get_scaled_image_data(self._data_offset, self.shape)
    244         self._update_header_scale_info(data.dtype)
    245 

/usr/lib/python3.6/site-packages/astropy/io/fits/hdu/image.py in _get_scaled_image_data(self, offset, shape)
    762 
    763             if self._orig_bscale != 1:
--> 764                 np.multiply(data, self._orig_bscale, data)
    765             if self._orig_bzero != 0:
    766                 data += self._orig_bzero

TypeError: Cannot cast ufunc multiply output from dtype('<U32') to dtype('float64') with casting rule 'same_kind'

```

On closer inspection, `_orig_bscale` and `_orig_bzero` are strings:

```
In [4]: f[0]._orig_bscale
Out[4]: '1'

In [5]: f[0]._orig_bzero
Out[5]: '32678'
```

Setting them to numerical data types corrects the problem:
```
In [6]: f[0]._orig_bzero = int(f[0]._orig_bzero); f[0]._orig_bscale=1;

In [7]: f[0].data
Out[7]: 
array([[  1.14178994e+09,   1.14174180e+09,   1.14178692e+09, ...,
          1.14177555e+09,   1.14176252e+09,   1.14176269e+09],
       [  1.14178447e+09,   1.14175783e+09,   1.14179378e+09, ...,
          1.14178843e+09,   1.14178280e+09,   1.14178793e+09],
       [  1.14179994e+09,   1.14175323e+09,   1.14178306e+09, ...,
          1.14177499e+09,   1.14179656e+09,   1.14178030e+09],
       ..., 
       [  1.14178683e+09,   1.14178459e+09,   1.14181058e+09, ...,
          1.14179567e+09,   1.14178244e+09,   1.14178743e+09],
       [  1.14173216e+09,   1.14176669e+09,   1.14176456e+09, ...,
          1.14174040e+09,   1.14174955e+09,   1.14174253e+09],
       [  1.14173425e+09,   1.14169651e+09,   1.14172604e+09, ...,
          1.14175629e+09,   1.14176928e+09,   1.14176658e+09]])
```

**Comment by pllim** [comment]
Which version of Astropy are you using? How are the keywords actually defined in your FITS header?

**Comment by darthoctopus** [comment]
I'm using astropy 2.0.1 from PyPI. The keywords are defined in the FITS header as follows:

```
BZERO   = '32678   '           /Offset data range for unsigned short            
BSCALE  = '1       '           /Default scaling factor
```

The behaviour I have pointed out above does not manifest when I remove the quotes from the FITS header manually.

**Comment by pllim** [comment]
I don't know whether it is a bug or feature that FITS does not auto-convert BZERO and BSCALE from string to number. Perhaps the header does not even follow FITS convention, but I'll leave that for someone who is familiar with the FITS standards.

**Comment by saimn** [comment]
From the FITS standard, the BZERO and BSCALE values *field shall contain a floating-point number*.

**Comment by saimn** [comment]
So the file is invalid, but there are other keywords (NAXIS iirc) for which `io.fits` tries to fix the value. The same could be done, or we simply close the issue ? Where does this file come from ?

**Comment by pllim** [comment]
> `io.fits` tries to fix the value

I thought I had seen a PR like that but I can't seem to find it.

**Comment by saimn** [comment]
@pllim - #5935 ? (That's the one I was thinking about)

**Comment by pllim** [comment]
Yes, that's the one. There is now a precedent but it is also a slippery slope. We don't want to start auto-fixing all kinds of malformed headers. I guess it is your and @MSeifert04 's call as current `io.fits` maintainers.

**Comment by darthoctopus** [comment]
The FITS files in question appear to have been generated by IDL. To the extent that it's predictable enough to be fairly easy for me to correct automatically, I would not mind either outcome, although obviously getting astropy to attempt to fix them would make my life a lot more convenient.

For what it's worth, ds9 also chokes on these FITS files.

**Comment by saimn** [comment]
> We don't want to start auto-fixing all kinds of malformed headers.

I totally agree with you @pllim , we should stick to the standard, and ask the producers of these files to fix them. 

@darthoctopus - If you know who produced this file and how, it could be good to report this upstream ? 

Shall we close this now ?

**Comment by MSeifert04** [comment]
I actually wouldn't mind to try to convert these to "floats" or "ints" before outright rejecting them as strings. But I can see where "fixing all kinds of malformed headers" would be bad.

So I'm -0 on this.

**Comment by pllim** [comment]
Alright, looks like there is general agreement to let the file maker fix it upstream, so closing then. Thanks for reporting this anyway, @darthoctopus !
