### ISSUE TITLE
Automatically install dependencies for build_docs

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#6496]
It would be nice if this was possible. It may be possible to do this using `extras_require` in `setup.py`, but more investigation is needed. The dependencies for `build_docs` appear to be `sphinx`, `matplotlib`, and `pyyaml`. I'm not sure whether there are specific version requirements or not.

[This section](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies) of the `setuptools` documentation may (or may not) be relevant.

**Comment by pllim** [comment]
The dependencies for doc are listed in `pip-requirements-doc`. That is what is fed into RTD.

**Comment by pllim** [comment]
Building docs is not something users or half the contributors do, as we already check Sphinx build in Travis CI. However, we do request it from time to time. Personally, I don't feel strongly one way or another.

**Comment by drdavella** [comment]
You can assign me if you want and I'll think about it for a bit and then eventually close it if it seems like too much work.

**Comment by taldcroft** [comment]
Would this imply automatically installing stuff if I do a `python setup.py build_docs`?  I'd be a bit hesitant on that because it seems like a potentially unexpected consequence of building part of astropy.  Personally it drives me crazy that setuptools will (by default) start installing/updating dependencies without *asking* first.

**Comment by drdavella** [comment]
@taldcroft, that was the intent, yes but I'll back off if it seems like there's too much resistance. Personally I find it more bothersome when I run a command in a clean environment but repeatedly get unhandled exceptions due to missing dependencies.

**Comment by MSeifert04** [comment]
Sorry to say but I don't like it. I always found it quite annoying that `setup.py` builds use `pip` to install packages, especially when in a `conda` environment and you would prefer to `conda install` them (faster and almost garantueed not to mess up the environment).

**Comment by drdavella** [comment]
I'm happy to close this issue since it's really not a big deal. It makes me curious about your development workflows though: I often find myself creating new environments for reproducing issues and/or testing, and it's a little annoying to not have dependencies installed automatically. I manage this pretty well with conda but I don't really see an issue with having the project I'm working on install its own dependencies.

**Comment by MSeifert04** [comment]
I think there has been a discussion on the requirements for dev-builds, doc-builds, test-builds in the past. I can't find the issue right now but I think we included several requirement files and these can be manually passed to pip with `pip install -r pathtofile`.

**Comment by MSeifert04** [comment]
I think there has been a discussion on the requirements for dev-builds, doc-builds, test-builds in the past. I can't find the issue right now but I think we included several requirement files and these can be manually passed to pip with `pip install -r pathtofile`.

**Comment by saimn** [comment]
tox can be useful also to quickly setup a specific environment for docs or tests (and there is already a config file in Astropy's repository). It's not much used now I think because it doesn't support conda, but with binary wheel packages it's also now fast to setup a new virtualenv.
