### ISSUE TITLE
Update `io.fits` docs to reflect `memmap=True` default

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#6497]
As a spinoff from discussion in #6491, the documentation for `io.fits` do not make it obvious that the default for `memmap` is `True`.  The `open()` docstring just says `None` (which is more typically the same as `False` for a bool), and the `Getting Started` narrative docs don't mention the default `True` behavior.

**Comment by saimn** [comment]
Thanks for opening the issue! While looking for other issues I found #4196 which is the same, though the title and description are less clear. I will close the other one.

**Comment by mkenne15** [comment]
I've attempted to update the docs to reflect this (it might not be up to standard though, this is my first attempt at contributing).

**Comment by ayush1999** [comment]
@saimn @taldcroft  Is this issue still open?

**Comment by mkenne15** [comment]
I believe it still is (the docs don't reflect memmap=True by default). I did try to address this, but am only getting started with editing astropy and ran into issues.

**Comment by ayush1999** [comment]
@mkenne15 Oh. As far I could understand, we need to change the documentation to give the default value of `memmap` as true, in io.fits files. What am I missing?

**Comment by mkenne15** [comment]
So that's what I tried, but when I went to recompile astropy with the new documentation it kept failing, and I had no idea why.

**Comment by sushobhana** [comment]
hi @taldcroft ..if anyone is not working i would like to fix this.

**Comment by lfulmer** [comment]
This seems like it's closed. Can you confirm, @adrn ?

**Comment by bsipocz** [comment]
@lfulmer - Sadly the docs still doesn't mention the default. However adding that can be a suitable first time PR if you're interested.

**Comment by lfulmer** [comment]
Yep! I got it.
