### ISSUE TITLE
Update needed for affiliated package release guide, PyPI upload step

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy#6506]
I'm following along with the guide for releasing affiliated packages and came across a new error: 
```
Submitting dist/astroplan-0.3.tar.gz to https://pypi.python.org/pypi

Upload failed (410): Gone (This API has been deprecated and removed from legacy PyPI in 
favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/).
For more information about migrating your use of this API to PyPI.org,
please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. 
For more information about the sunsetting of this API, please see 
https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)
```

When I figure out how to fix this, I'll make a PR to astropy with updated instructions.

**Comment by bsipocz** [comment]
@bmorris3 - There may be already another issue for this opened (cannot dig it up now), but long story short: check the astropy release guide for now (which was recently updated) and use twine to upload.

**Comment by bmorris3** [comment]
Found it, this problem came up in #5120.
