### ISSUE TITLE
XDG_CONFIG_HOME failing silently caused confusion

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6511]
I ran into a group who would have benefited from #5899. However, since that is not yet possible, they tried to set two different directories for different versions of Astropy to run in parallel on the same file system on the same cluster. Otherwise, they run into a problem of `astropy.cfg` getting corrupted by the parallel attempts to write it.

Despite instructions at http://astropy.readthedocs.io/en/latest/config/index.html that says, "... if you’ve set the environment variable `XDG_CONFIG_HOME` and the `$XDG_CONFIG_HOME/astropy` directory exists, it will instead be there," they set `XDG_CONFIG_HOME` that included the "astropy" sub-directory. As a result, the check for `$XDG_CONFIG_HOME/astropy` failed (because it was really looking for `$XDG_CONFIG_HOME/astropy/astropy`) and fell back silently to the default `~/.astropy/config`, which caused a lot of confusion.

Suggestion: If `XDG_CONFIG_HOME` is defined but the desired directory is not found, raise an exception (too much?) or at least emit a warning.

**Comment by saimn** [comment]
> they set XDG_CONFIG_HOME that included the "astropy" sub-directory

You mean `XDG_CONFIG_HOME=$HOME/.config/astropy` ? This would cause many software to look at their config inside this directory.
The way I read this page is that you should set `XDG_CONFIG_HOME=$HOME/.config` and create the `$HOME/.config/astropy` directory (imo it should be created automatically in this case, but maybe it was not done to avoid breaking compatibility).

**Comment by pllim** [comment]
> You mean `XDG_CONFIG_HOME=$HOME/.config/astropy` ? 

Not exactly. What actually happen was
```bash
export XDG_CONFIG_HOME=/some/nondefault/dir/astropy
```
but the correct command should have been
```bash
export XDG_CONFIG_HOME=/some/nondefault/dir
```

**Comment by pllim** [comment]
> it should be created automatically in this case

That would help too. Not creating that first also caused silent default-ing and confusion.

**Comment by pllim** [comment]
> This would cause many software to look at their config inside this directory

Sure. But that was not the source of the problem reported.

**Comment by saimn** [comment]
> but the correct command should have been
   export XDG_CONFIG_HOME=/some/nondefault/dir

Exactly

> Sure. But that was not the source of the problem reported.

No indeed, but that was just to explain the effect of changing `XDG_CONFIG_HOME`.

**Comment by pllim** [comment]
For more background, the affected party was a very specific pipeline workhorse. So, other software config files are not really an issue there. Setting `XDG_CONFIG_HOME` correctly (without the "astropy" in string) did solve the problem but setting it incorrectly initially caused a lot of confusion due to the lack of verbosity.

**Comment by pllim** [comment]
If #10090 is accepted, then this won't really be an issue anymore because there will be a workaround.
