### ISSUE TITLE
Test files tripping up antivirus software 

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#6520]
Two files from the test suite, astropy/utils/tests/data/invalid.dat.gz and astropy/utils/tests/data/invalid.dat.bz2 are triggering warnings for some virus scanning software. Both are small files that are deliberately corrupt to ensure that the package data readers can handle corrupt files.

The fix is to generate those files at test time.

From an email from @msarahan:

> Astropy's test data is tripping up some virus scanners:
﻿> SWEEP virus detection utility
> Version 5.27.0 [Linux/AMD64]
> [snip]
> Could not check
> astropy-0.2.1-np16py26_0.tar.bz2/Bzip2/Lib/site-packages/astropy/utils/tests/data/invalid.dat.gz
(corrupt)

**Comment by mwcraig** [comment]
I *think* I did the milestone/labels correctly...

**Comment by bsipocz** [comment]
I can see that upsetting antivirus is an unplanned side-effect and thus threat any PRs for it as a bugfix for the LTS branch.

**Comment by pllim** [comment]
I guess in theory you could open a valid version, corrupt it somehow and write it back out within test setup, and then run the test.  However, will Python even allow writing a corrupt buffer? Are there notes on how they were generated? My past experience with intentionally producing non-compliant files involved editing it by hand in a text editor. :thinking:

**Comment by pllim** [comment]
Another option is to move them to the Astropy data server and then mark the test(s) as remote test(s). This way, antivirus will not find them, but then the test(s) will be at the mercy of server connection.

**Comment by drdavella** [comment]
@pllim it shouldn't be difficult to create a corrupt version of the file. Just overwriting the first few bytes with random data should be sufficient.

**Comment by pllim** [comment]
Note: @drdavella volunteered for this, so I assigned to him.

**Comment by mwcraig** [comment]
For the tests  its important that each file start with the right there bytes (whatever the first three bytes currently are). Those mark the files a gzip or bzip, and they are used to test handling of file which appear to be compressed but actually are not.

There is nothing corrupt about the files themselves, they are perfectly valid as binary. However, they masquerade a compressed tarballs when they really are not. The virus scanner gets mad, I think, because it reads the first few bytes, tried to uncompress it for scanning, the uncompress fails, so it thinks the files are corrupt.

**Comment by drdavella** [comment]
I'm about to open a PR for this fix. It's worth pointing out that if we create these files on the fly, the most sensible thing to do is to create them in a temporary directory provided by `pytest`. However, this means we are no longer really testing "local data", and so we can't use `get_pkg_data_fileobj` to read the files in the test. However, we _can_ still use `get_readable_fileobj` since it doesn't care whether the file is "local" or not. As long as this is okay with everyone, I think we're good.

**Comment by pllim** [comment]
> As long as this is okay with everyone

That is fine by me. When you create it on-the-fly, it is strictly speaking no longer part of package data.
