### ISSUE TITLE
Should proj_plane_pixel_area return a Quantity?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6523]
At the moment, the ``astropy.wcs.proj_plane_pixel_area`` function returns a value in square degrees, but just as a value. I think we really should be returning a Quantity to avoid confusion. However, breaking backward compatibility may be problematic if we suddenly start returning Quantity. Maybe we could deprecate and rename the function to avoid nasty surprises? Or we could add a variant of the function that returns a quantity? The same applies to ``proj_plane_pixel_scales``.

**Comment by nden** [comment]
How about adding a boolean keyword `with_units=False` as default?

**Comment by astrofrog** [comment]
Yes, sounds reasonable

**Comment by pllim** [comment]
But at some point, is there plan to change default to `with_units=True`?

**Comment by astrofrog** [comment]
If we were ever going to change it, then the sooner the better. I don't know how much people are using this function in the wild though.

**Comment by mhvk** [comment]
For something like square degree where I think one might logically expect square arcsec, a unit seems good! 
But a keyword argument seems rather strange and superfluous - it really only would be for backwards compatibility.

Since quite a few of these utilities only take `wcs` as input, might an alternative be to make these methods (or properties?) on `WCS` itself, and have those methods always return a unit? They could use the function internally if need be, or one could let the functions call the method (and perhaps eventually deprecate them).

**Comment by pllim** [comment]
3 years later, I asked this question today and almost opened a new issue. Returning `Quantity` would be very nice indeed.

**Comment by astrofrog** [comment]
I like @mhvk's suggestion of basically changing the API and deprecating the old one to minimise impact on users. But agreee that quantities would be nice.

**Comment by nden** [comment]
👍 to @mhvk's suggestion

**Comment by mcara** [comment]
I am against deprecating old functions because of unnecessary performance loss. Fundamentally this function calls old code and add units just to have them stripped away. For the very least, there should be an option to return just the value using "native" units - the ones specified in `CUNIT`.

**Comment by pllim** [comment]
> Fundamentally this function calls old code and add units just to have them stripped away.

Not sure if I understand. Stripped away by what?

**Comment by pllim** [comment]
> there should be an option to return just the value using "native" units

Isn't it what it is already doing?

**Comment by mcara** [comment]
by my code that needs just the value.

**Comment by mcara** [comment]
> > there should be an option to return just the value using "native" units
> 
> Isn't it what it is already doing?

Don't you want to deprecate/remove the code that is doing just that?

**Comment by pllim** [comment]
> by my code that needs just the value

In that case, use the function in `utils`. I am not deprecating it. No one is stopping you.

Marten suggested it, but I decided against it in the implementation. If you look at the diff, there is no deprecation.

**Comment by mcara** [comment]
Phew!

**Comment by mhvk** [comment]
@mcara - now even more convinced my suggestion was wrong! @pllim's PR gives the best of both worlds.
