### ISSUE TITLE
input_units in model does not work?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6524]
I am trying to use `input_units` as specified in http://astropy.readthedocs.io/en/stable/modeling/units.html#input-units but I can't get it to work. What am I doing wrong?

```python
from astropy import units as u
from astropy.modeling import models as _models

class MyConst1D(_models.Const1D):
    @property
    def input_units(self):
        return {'x': u.Jy}
```

```python
>>> m = MyConst1D(1 * u.m)  # Expected error but none raised!
>>> m.input_units
{'x': Unit("Jy")}
>>> print(m)
Model: MyConst1D
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Parameters:
    amplitude
        m    
    ---------
          1.0

>>> m.amplitude
Parameter('amplitude', value=1.0, unit=m)
```

**Comment by astrofrog** [comment]
``m = MyConst1D(1 * u.m)`` is not calling the model, it is initializing it - you do get an error if calling ``m(...)`` with something that isn't ``Jy``.

**Comment by pllim** [comment]
Haha... yes. I must be very confused when I wrote that. I do also have a question about `return_units` but it is at https://github.com/astropy/astropy/issues/6505#issuecomment-326683323 . Closing this one.
