### ISSUE TITLE
[WIP] Fix unit support in tabular models

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6528]
Fix #6525 

This is an idea on how to fix it but I have yet to actually run the tests. Will do so next week.

TODO:
- [ ] Test the idea.
- [ ] Add change log to 2.0.3.

**Comment by pllim** [comment]
Ops!!! Sorry, was meant to open a PR. :joy:

**Comment by bsipocz** [comment]
@pllim - you should be able to convert an issue to a PR with https://github.com/astropy/astropy-tools/blob/master/issue2pr.py  (definitely works for own issue-->PR, I've never tried to convert someone else's issue to a PR, but saw others doing it before)

**Comment by pllim** [comment]
Oh yeah. I didn't think of that but will definitely keep it in mind for next time. Thanks!
