### ISSUE TITLE
Regression with Column and units ?

### ISSUE THREAD

**Issue by abeelen** [astropy/astropy#6532]
When running this simple code
```
from astropy import units as u
from astropy.table import Column

a = Column([1,2,3], unit='Hz')
b = 2*u.Hz
```

comparison between a & b will fail with astropy 2.0.x (tested both with 2.7 & 3.5):
* `print(a<b)` return a `UnitsError: Can only apply 'less' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)`
* `print(b<a)` return the expected array

Moreover when units are different `b = 2*u.MHz`, both will fail
* `print(a<b)` return the same `UnitsError`
* `print(b<a)` return an `AttributeError: 'Column' object has no attribute 'value'`

With astropy 1.3.3, only the last test would fail with the same exception.

**Comment by mhvk** [comment]
That is odd, and definitely unintended. There seem to be two bugs involved, the first that the comparison doesn't let the `Quantity` take precedence, and the second that the `Quantity` comparison tries to access `.value` in `__array_ufunc__`. I'm not sure about the former, but the latter should be quite easy to fix.

**Comment by mhvk** [comment]
Looking over old issues... The easy-to-fix part is fixed in current master, but `Column` still doesn't give `Quantity` precedence for comparison operators.
