### ISSUE TITLE
Astropy units with fractional powers are stored incorrectly

### ISSUE THREAD

**Issue by 1313e** [astropy/astropy#6537]
I noticed a problem when trying to store an astropy.unit in a variable that is raised to a fractional power.
If this fractional power cannot be written in terms of 'a/b' with b<=10, astropy will try to approximate the power by assigning it a power that does satisfy this rule.
So, for example,
```
>>> import astropy.units as apu
>>> A = pow(2*apu.kg, 11./14.)
>>> print(A)
```
will give me `1.7239456 kg^(7/9)`.
The value '2' was raised to the correct power, because it could be calculated immediately.
However, the unit 'kg' is not raised to the correct power.
Instead of raising it to the power of '11/14', it is raised to the power of '7/9'.
And although these two numbers are very similar, this of course doesn't work when dealing with units.

I discovered this problem because I was dealing with powers like '24/79', '11/14' and '-3/20'.
The final result should be unitless if all units along the way are stored and used correctly.
However, the final result had a really weird unit that had a power that was something like '14/41875179'.
Something that is practically zero, but not completely.

So, is this a memory issue or can this be fixed or...?

As for the software information: I tried this on Python 2.7, 3.4, 3.5 and 3.6.
I am using AstroPy version 2.0.2.
And, all other packages are up-to-date to cope with this version of AstroPy.

**Comment by Arafatk** [comment]
Internally astropy converts the fractions to integers back and forth. 
Best way is to use fraction 

```
import astropy.units as apu
from fractions import Fraction
A = pow(2*apu.kg, (11/14))
B = pow(2*apu.kg, (2/1))
C = A * B
print("A =", A," B =", B, " C =" ,C)


A = pow(2*apu.kg, Fraction(11,14))
B = pow(2*apu.kg, Fraction(2,1))
C = A * B
print("A =", A," B =", B, " C =" ,C)
```

Output 
```
A = 1.7239456424939554 kg(7/9)  B = 4.0 kg2  C = 6.895782569975822 kg(25/9)
A = 1.7239456424939554 kg(11/14)  B = 4.0 kg2  C = 6.895782569975822 kg(39/14)
```

I think this solves the issue so please close it.

**Comment by pllim** [comment]
Thanks! I am closing as it seems resolved. Feel free to re-open if you have other related questions.

**Comment by astroduff** [comment]
Hey all, can I reopen this? It seems like this is a VERY significant bug that might cause some headaches when the solution (i.e. implementing the fraction package under the hood) could so easily fix this and avoid users having these issues?

**Comment by pllim** [comment]
Hello, @astroduff . The original issue was for a specific use case with astropy 2.x. Feel free to open a new issue with your use case and its full description. You can always cross-reference back to this issue if necessary.

**Comment by astroduff** [comment]
Done.

**Comment by 1313e** [comment]
@pllim I am currently using AstroPy 3.1.2 and it still has the same problem.

**Comment by pllim** [comment]
Is the solution proposed at https://github.com/astropy/astropy/issues/6537#issuecomment-328858001 insufficient?

**Comment by pllim** [comment]
Anyway, looks like @mhvk is on it at #9279 . Thanks for re-raising the issue, everyone!

**Comment by 1313e** [comment]
> Is the solution proposed at [#6537 (comment)](https://github.com/astropy/astropy/issues/6537#issuecomment-328858001) insufficient?

It is theoretically speaking sufficient, but how many users of AstroPy will know about it?
When using units in AstroPy, it should be normal to expect that I can raise any unit to any power, and it will work properly.
I am actually quite surprised nobody ever raised this issue before I did 2 years ago, and nobody ever did since.

**Comment by pllim** [comment]
The fanciest unit I use is `erg / s / Angstrom / cm / cm`. Don't think I ever tried to do `kg^(11/14)`. 😅

**Comment by 1313e** [comment]
@pllim Well, as I mentioned in my original post above, I had to use some very weird units back then for a university exercise.
