### ISSUE TITLE
bintrees (optional dependency for table indexing) isn't actively developed anymore

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#6539]
The home page of `bintrees` (https://pypi.python.org/pypi/bintrees) advises people to use `sortedcontainers` instead. Given that it's just an optional dependency there is no rush to actually make the change happen (fast) but it could be an additional improvement.

**Comment by bsipocz** [comment]
I've provisionally added this to the 3.0 milestone. Should be easy to do, and since the requirement for ``bintrees`` wasn't really documented, we can probably just switch to ``sortedcontainers`` straight away (or at least do a double fallback, sortedcontainers-->bintrees-->pure python from astropy)

**Comment by MSeifert04** [comment]
Unfortunately it is [documented](http://docs.astropy.org/en/stable/table/indexing.html#engines). A bit hard to spot without CTRL+F

**Comment by MSeifert04** [comment]
cc: @taldcroft

**Comment by MSeifert04** [comment]
@taldcroft also mentioned that `bintrees` can't be easily serialized. It could be worth checking out if that's also a problem with `sortedcontainers`.

**Comment by mhvk** [comment]
Removing milestone, though it would still seem good to address.

**Comment by grantjenks** [comment]
Hi, I'm the author of `sortedcontainers`. Can I help?

For reference, `sortedcontainers` supports serialization using Pickle. The data types: sorted list, sorted dict, and sorted set also subclass the Sequence, Mapping, and Set abstract base classes so they work with lots of Python APIs.

If I created a pull request, would you want bintrees support removed?

I think another "engine" could be added using `sortedcontainers`. Would that be the right way to go?

**Comment by taldcroft** [comment]
I wonder if it would be possible and make sense to just change in the internal implementation of `FastBST` and/or `FastRBT` to use `sortedcontainers` instead of `bintrees`.  If this can be done with no other API changes then I think we could remove bintrees without deprecation.  I haven't looked into this code much, it was written by a GSoC student years ago, so I don't really know off hand.

BTW @grantjenks, `sortedcontainers` looks great, I'll keep this in mind for other projects!

**Comment by pllim** [comment]
With #7574 merged, can we replace `bintrees` in `pip` requirements doc with `sortedcontainers`?

https://github.com/astropy/astropy/blob/62eeb3cc8e4355dd8840659594a0915e28700e3b/pip-requirements-dev#L9

**Comment by saimn** [comment]
Should we deprecate bintrees or just remove it ? (ref #9016)

**Comment by pllim** [comment]
I echo @saimn's question at https://github.com/astropy/astropy/issues/6539#issuecomment-512968520 . @taldcroft and @mhvk , when can we drop support for `bintrees`?

**Comment by mhvk** [comment]
I've never used it, so am the wrong person to ask. It does seem that basically the plan was followed here and we just forgot to do the final step, of removing bintrees!
