### ISSUE TITLE
Should HDUList implement 'get' and 'keys'?

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#6543]
The fact that `HDUList` allows ~~headers~~ HDUs to be retrieved not only by numeric index but also by extension name means it behaves in some ways like a `dict`. However, unlike `dict`, given an instance of `HDUList`, there is no `get` method to conditionally retrieve an HDU by key only if it exists. The `__contains__` method is already implemented (which allows for statements like `'NAME' in hdulist`), so it seems perfectly natural to provide a `get` method as well.

In addition, it might be useful to provide a `keys` method which would return a list of the names of all of the extensions.

**Comment by drdavella** [comment]
Feel free to assign this issue to me if it seems like a reasonable feature.

**Comment by pllim** [comment]
> `HDUList` allows headers to be retrieved

Like how? Header is contained within an individual HDU. HDU list does not have a header. I am confused. Maybe provide a code snippet of how you envision this to work?

**Comment by MSeifert04** [comment]
The `HDUList` is more a sequence than a mapping. So just from the interface POV I would say: No.

But if you could provide an actual use-case that would be helpful. I can't think of any use-case for `get`.

**Comment by drdavella** [comment]
@pllim I think I had a lapse of terminology: it should say `HDU`.

> The HDUList is more a sequence than a mapping. So just from the interface POV I would say: No.
@MSeifert04 that may be true of the underlying implementation but the interface already allows it to be accessed as a pseudo-mapping, so I don't think that's really an argument against adding these methods.

Code example:
```python
from astropy.io import fits
hdulist = fits.open('some_file.fits')
foobar = hdulist.get('FOOBAR')
if foobar:
    # do something to process this HDU
```

Admittedly this is more for convenience than anything but it's a fairly minor feature request and is very much in line with the functionality that already exists for `hdulist`.

**Comment by saimn** [comment]
I'm not convinced, imo `get` is useful if you have a sensible default value and can avoid the following `if`. 

About `keys`, `HDUList` is an hybrid between list and dict, and keys are not necessarily unique or can be missing. So I'm not sure we should make it look more like a dict, because it will be confusing to have several occurrences or empty strings in the result of `keys`, isn't it ?

**Comment by MSeifert04** [comment]
I couldn't have put it better than @saimn and I tried ... for the last 10 minutes.

**Comment by drdavella** [comment]
> I'm not convinced, imo get is useful if you have a sensible default value and can avoid the following if.

This is a fair point.

> About keys, HDUList is an hybrid between list and dict, and keys are not necessarily unique or can be missing. So I'm not sure we should make it look more like a dict, because it will be confusing to have several occurrences or empty strings in the result of keys, isn't it ?

My main point here is that although HDUs can be accessed by name, given an `HDUList`, there is not a great way to determine which values can be used as 'keys'. Maybe calling this method `keys` is misleading then, since it doesn't behave the same way that it would for `dict`. But wouldn't something along these lines still be useful?

**Comment by MSeifert04** [comment]
> But wouldn't something along these lines still be useful?

In my opinion that's the wrong incentive. I don't think one should implement things that *could* be useful but rather implement things that are *actually* needed.

**Comment by drdavella** [comment]
@MSeifert04 you've made a case that for various reasons these features don't make sense and I can accept that. However, I opened this issue because I would find both of these things useful in code that I'm actually working on. I can also say that they would both be useful when working with `HDUList` objects in an interactive environment.

**Comment by drdavella** [comment]
Hmm, `HDUList.info` is useful, although it still doesn't provide a list of extension names that can be used programmatically. I'm willing to drop this at this point though.

**Comment by saimn** [comment]
@drdavella - For interactive use `HDUList.info()` gives more context (EXTNAME, EXTVER was added recently, shape etc). For *my* use it's the most practical, but it's always useful to think about other options we could add, thanks for making suggestions ;)
