### ISSUE TITLE
Sorting a Table with index fails

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#6545]
```python
In [1]: %astropy
Numpy 1.13.1
Astropy 3.0.dev19860

In [2]: t = Table([[1,3,2], [6,4,5]], names=('a', 'b'))

In [3]: t.add_index('a')

In [4]: t.sort('a')

In [5]: t.sort('b')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-e7e0172e4efe> in <module>()
----> 1 t.sort('b')

~/lib/astropy/astropy/table/table.py in sort(self, keys)
   2462
   2463         for col in self.columns.values():
-> 2464             col[:] = col.take(indexes, axis=0)
   2465
   2466         if sort_index is not None:

~/lib/astropy/astropy/table/column.py in __setitem__(self, index, value)
    935
    936         # update indices
--> 937         self.info.adjust_indices(index, value, len(self))
    938
    939         # Set items using a view of the underlying data, as it gives an

~/lib/astropy/astropy/utils/data_info.py in adjust_indices(self, index, value, col_len)
    502         for key, val in zip(keys, value):
    503             for col_index in self.indices:
--> 504                 col_index.replace(key, self.name, val)
    505
    506     def slice_indices(self, col_slice, item, col_len):

~/lib/astropy/astropy/table/index.py in replace(self, row, col, val)
    537     def replace(self, row, col, val):
    538         if not self._frozen:
--> 539             self.index.replace(self.orig_coords(row), col, val)
    540
    541     def copy(self):

~/lib/astropy/astropy/table/index.py in replace(self, row, col_name, val)
    336         key = [c[row] for c in self.columns]
    337         key[self.col_position(col_name)] = val
--> 338         self.data.add(tuple(key), row)
    339
    340     def replace_rows(self, col_slice):

~/lib/astropy/astropy/table/sorted_array.py in add(self, key, row)
     73                              'unique index'.format(key))
     74         self.data.insert_row(pos, key)
---> 75         self.row_index = self.row_index.insert(pos, row)
     76
     77     def _get_key_slice(self, i, begin, end):

AttributeError: 'numpy.ndarray' object has no attribute 'insert'
```
After playing a bit to reproduce, it seems related to sorting a column after sorting the column with an index.
cc @taldcroft

**Comment by MSeifert04** [comment]
Sorry for being off-topic, but how can I make that `%astropy` magic work?

**Comment by MSeifert04** [comment]
Just to add something constructive here: The `sort`ing works if you use `t.add_index('a', engine=astropy.table.BST)`

**Comment by bsipocz** [comment]
@MSeifert04 - it's a custom magic of @saimn, https://ipython.org/ipython-doc/3/config/custommagics.html

**Comment by saimn** [comment]
Yep, IPython magic for common imports, mine is [here](https://github.com/saimn/dotfiles/blob/master/ipython/profile_default/startup/10-mystartup.py#L21) :wink: 

@MSeifert04 - thanks for the odea of using the `BST` engine, good to know.

**Comment by taldcroft** [comment]
Well this looks like a real bug...

About the `BST` engine, note that by default it is pure-Python and thus will be memory intensive and generally slow.  If you install the `bintrees` package it will make available `FastRBT` and `FastBST` options and you can try those.

**Comment by MSeifert04** [comment]
Yes, I know about the `bintrees` package. In fact I opened a PR and issue about it recently: #6538, #6539  😄 

However I don't have it installed and since it's not actively developed **and** untested in the test suite and the docs say that the default is usually faster I'm not gonna try. However it might be interesting to test if that issue also affects the `bintrees` engines.

**Comment by bsipocz** [comment]
I've run into this today, even wrote up a new issue ;)

(also can confirm that the new `SCEngine`, so really is an issue only for `SortedArray`)

**Comment by saimn** [comment]
Thanks @taldcroft , good to see this finally resolved :)
