### ISSUE TITLE
Compound models do not respect unit support

### ISSUE THREAD

**Issue by nmearl** [astropy/astropy#6553]
While unit and quantity support works very well in individual models, compound models do not seem to care about the unit attributes defined in the individual models composing it.

```python
In [38]: class TestModel(Fittable1DModel):
    ...:     input_units = {'x': u.m}
    ...:
    ...:     @property
    ...:     def input_units_equivalencies(self):
    ...:         return {'x': [(u.m, u.kg, lambda x: x ** 2, lambda x: x ** 0.5)]}
    ...:
    ...:     def evaluate(self, x):
    ...:         return x
    ...:

In [39]: res = TestModel()(np.arange(10) * u.kg)

In [40]: res.unit == u.m
Out[40]: True

In [41]: res = (TestModel() + TestModel())(np.arange(10) * u.kg)

In [42]: res.unit == u.m
Out[42]: False
```

**Comment by pllim** [comment]
Did you try enforcing `return_units`? http://astropy.readthedocs.io/en/latest/modeling/units.html#return-units

**Comment by nmearl** [comment]
That's a different use case (wanting inputs in a particular unit vs. wanting outputs in a certain unit), but is equally ignored in compound models.

**Comment by pllim** [comment]
`res.unit` is an output unit and theoretically would be addressed by `return_units`. That is how I interpreted your snippet anyway.

**Comment by nmearl** [comment]
I understand, but the idea is that the `evaluate` method should expect quantities in the units specified by `input_units`, and convert them before the body of the method is run. In this case, since evaluate is not *doing* anything to the quantity (and a `return_units` is not defined), `res.unit` should return the unit specified by `input_units`.

Of course, the issue still stands (i.e. compound models not respecting unit support) in the case of ` return_units`; but even if `return_units` *had* worked, that specific use case doesn't solve the snippet's use case, or solve the issue as a whole.

**Comment by astrofrog** [comment]
@nmearl - just for info, this is fixed by https://github.com/astropy/astropy/pull/6952

**Comment by pllim** [comment]
@astrofrog , does this mean we can close this issue now?

**Comment by Cadair** [comment]
#6952 isn't merged yet, but this can be closed when it's merged
