### ISSUE TITLE
Numpy thinking about float comparison doctest runner

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6554]
Mostly an alert to those interested (@astrofrog, @bsipocz?): over at numpy, there is discussion about having an runner for doctests that compares float numbers, a bit like ours, but also with some differences. I think we could eventually move ours over, but possibly even better would be to move it upstream.

See https://github.com/numpy/numpy/pull/9674

**Comment by pllim** [comment]
I wonder if they will throw in `rtol` and `atol` in such a doctest while they are at it! :wink:

**Comment by bsipocz** [comment]
This sounds exciting, I'm definitely 👍 to move ours upstream (even if it's just upstream to numpy). 
Based on previous comments, I believe @embray (the original author of FLOAT_CMP) is also OK with this idea.

Related issue: https://github.com/astropy/astropy/issues/6312 and somewhat related: https://github.com/astropy/astropy/issues/2662

**Comment by mhvk** [comment]
Thanks for  the links - turns out this was put to python-ideas already by @kdavies4 with Coghlan concluding it was a good idea [1]. I'm suggesting to pursue this in the numpy issue...

[1] https://mail.python.org/pipermail/python-ideas/2014-August/028559.html

**Comment by bsipocz** [comment]
Now that  the plugin has been moved out to`pytest-doctestplus` I suggest to close this issue here. Any issues/suggestions/improvement can be contributed to https://github.com/astropy/pytest-doctestplus/

**Comment by mhvk** [comment]
OK, opened a new issue there: https://github.com/astropy/pytest-doctestplus/issues/55

**Comment by mhvk** [comment]
p.s. Problem of course is that while I file issues there, the chance that I am reminded of an issue there is near zero...

**Comment by bsipocz** [comment]
Sometimes I have a browse through the issues I have opened all around, the github menubar is a big help with that. But otherwise agree it's quite out of the way.

Looking at the numpy issues it's not clear to me what their preferred way, provide the standalone tool or work their/scipy's approach into a pytest plugin. Maybe it's time to advertise our standalone plugins more widely so others will more likely check it out and join forces there?
