### ISSUE TITLE
Consider moving astropy-specific schemas and tags from ASDF to astropy core

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#6560]
ASDF is a data format that is capable of serializing arbitrary Python objects. While any ASDF file can be reconstructed in memory using basic Python types (strings, lists, dicts), it is often useful to recreate the original object. Currently, ASDF maintains schemas (data type definitions) and tags (implementations of serialization) for various astropy objects. It would be useful to move the astropy-specific schemas and tags to astropy, where they can be maintained and testing in parallel with the corresponding objects.

@eteq

**Comment by pllim** [comment]
Labeling as `io.misc` for now because we don't have an `asdf` label (and doesn't have a reason to yet). Also milestoning to v3 but we can re-milestone based on coordination meeting discussions.
