### ISSUE TITLE
Delete branches for versions that don't get backports anymore

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#6563]
Currently we have several branches that will never get any backports anymore:

- master
- v2.0.x
- stable
- v1.3.x Updated 4 months ago by bsipocz
- v1.0.x Updated 4 months ago by bsipocz
- v1.2.x Updated 9 months ago by eteq
- v1.1.x Updated a year ago by astrofrog
- v0.4.x Updated 2 years ago by embray
- v0.3.x Updated 3 years ago by embray
- v0.2.x Updated 4 years ago by embray
- v0.1.x Updated 5 years ago by mdboom 

Except for the first 3 none of them will ever get backports. Even if someone would be interested old versions are still available using the release tags.

So my suggestion would be to remove all branches except `master`, `2.0.x` and `stable`.

**Comment by pllim** [comment]
xref #2781

**Comment by bsipocz** [comment]
This seems to be a rather scary idea, as the bugfix tags are not living on the branches we would keep, and also numpy and scipy keeps their old branches. 
But this a rather groundless feeling, so I'm happy if we decide either way.

**Comment by MSeifert04** [comment]
> the bugfix tags are not living on the branches we would keep

Would that mean these tags get "lost" or would that otherwise make problems?

I'm asking out of curiosity, mainly because I haven't thought about that.

**Comment by bsipocz** [comment]
According to SO the tags will keep the history alive without the branches, but this is something we should double/triple check.

**Comment by MSeifert04** [comment]
hm, I don't feel particular strong about the branch removal. It's just "slightly" annoying currently. 

I was just thinking about times when there are more astropy versions around. But if there's any chance this might backfire we probably shouldn't do it.

**Comment by bsipocz** [comment]
I milestone this as there is no point having the issue around open. We just need to make a decision. 

I would keep our branches, but it seems that there is no unified view on this, numpy, scipy, scikit-learn are having their branches around, while as I see mpl got rid of its 1.*.x.

**Comment by astrofrog** [comment]
I vote to keep them because history and stuff.

**Comment by bsipocz** [comment]
I'm on  the side of keeping them, too. (I keep everything anyway, so having a few around for astropy doesn't seem to be an issue to me).

**Comment by MSeifert04** [comment]
Sounds fine. Let's keep them!

**Comment by bsipocz** [comment]
One good idea I've just seen in scipy is that there  is another layer/dir between master and the version branches, "maintanence".
I'm not sure how git would react to move an existing branch, whether  the tags stay or not,  but that's something we may want to do to move the old non active ones to "legacy" or similar.
