### ISSUE TITLE
Improvements to changelog

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6564]
### Background

At the coordination meeting in NY we discussed whether the changelog could be stored in a separate format and whether it could be e.g. auto-generated from merged pull requests.

We eventually decided that a lot of these ideas would require a lot of extra engineering and also having spoken to @bsipocz, it seems the 2.0 release happened without any big issues related to the changelog, so it seems the issues we used to get in the past are gone now that @astropy-bot diligently  checks each PR for consistency. Our decision was that for now, instead of working on developing a whole new format and process we should simply try and improve interactions with the bot to better help users get the changelog entry right

### Proposal

Several ideas were discussed for improving the bot interactions with pull requests:

* If the ``CHANGES.rst`` file has not been changed at all, the bot could detect this and tell the user it would be great if they added a changelog entry, and could give an example of what a changelog entry should look like and explain how to decide where to put it in the file and remind them to add the PR number.

* If the PR does include a changelog entry but no PR number, the bot could mention that the contributor could add the PR number.

* We could have an option that if we push a PR with ``[#...]`` or similar as the PR number, the bot could automatically fill out the PR number and push a new commit to add the PR number

And as a fallback, maintainers can also simply edit the PR through GitHub to add the PR number themselves.

cc @eteq @taldcroft - is this an accurate recollection of our discussion?

**Comment by pllim** [comment]
> edit the PR through GitHub 

But... doesn't that create a merge commit? ;-p

**Comment by bsipocz** [comment]
no, if commits by maintainers are allowed, it'll just directly add one more commit on it.

**Comment by mhvk** [comment]
Am all in favour of not changing custom. That said, has there been any discussion of moving to a more numpy-like scheme, where part of the changelog is auto-generated (e.g., bug fixes just use the first line of the commit, which has to start with `BUG` - a consequence of this, though, is that PRs are greatly encouraged to be just one commit (a quite healthy habit, I find).

More practically, in our scheme I guess it suggests another option: that if a commit includes a `fixes #....`, the astrobot automatically inserts an entry in `CHANGES.rst` (at least the moment the milestone is set).

**Comment by pllim** [comment]
> PRs are greatly encouraged to be just one commit

I don't think that is going to happen based on #6536 discussions.

**Comment by taldcroft** [comment]
I'm :-1: on solutions that automatically propagate content (beyond PR number) from commits or PR comments into the changelog.  

The entry in the changelog should be carefully worded and aimed at *users*.  It may be a long paragraph in some cases.  This is really different from a commit message.  Another problem with commit message is that the original committer may not know this rule, or may not have experience to write a good user-facing description of the bug being solved.

Overall the discussion at the coordination meeting was that since the introduction of the bot to make sure there is a changelog entry, that there is not really such a big problem with our current system and we don't *need* to devote resources to any complex/fancy bot solutions related to the changelog.

**Comment by mhvk** [comment]
OK, fair enough. In numpy, this ends up being left to the release manager, but it is fair to spread that burden! 

The one really useful feature mentioned above would be automatic propagation of the PR number - it is just unnecessary extra work to find out what the number is going to be (although on the other hand it is perhaps also silly to litter the commit history with meaningless ones; but that is arguably better solved by just squashing before merging, which is a separate discussion).

**Comment by embray** [comment]
I believe this is now resolved by #11351.  In a sense the changelog *is* being generated from PRs, but using towncrier stubs.
