### ISSUE TITLE
Add astropy.dynamics or remove astropy.cosmology

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6567]
This was brought up during NY coordination meeting between @adrn and @eteq . One suggestion was to move `cosmology` out to an affiliated package. Another suggestion is that if we decide to keep `cosmology` in core, why is there not a `dynamics` sub-package?

p.s. Feel free to close if this is not worth an issue. I thought I should just document this here, just in case we wish to pursue.

**Comment by adrn** [comment]
Some things that might be sufficiently general that other packages could use: 

* a generic object for representing phase-space coordinates (positions + velocities, accelerations, etc. in the same object)
* utilities for orbit integration

**Comment by tmcclintock** [comment]
Just curious, but what is the context for this refactoring? What would be in ```dynamics``` and why would that preclude ```cosmology``` from being in core?

**Comment by mhvk** [comment]
I'm against moving or deprecating cosmology - it may not be quite as fundamental as `Time` constructs, or coordinate precession, etc., but in my opinion definitely falls in that category of basic infrastructure requited to do astronomy (this even though I don't use it regularly myself; but I am really happy to know that if for some reason I get a redshift for a FRB or so, astropy will just be there to tell me luminosity distance, etc.).

Arguably, though, it is in the wrong section in the documentation: it might be more logical in "data structures and transformations" than grouped with statistics, convolution, and visualization.

**Comment by astrofrog** [comment]
I suggest we close this issue as we don't actually have serious plans to remove astropy.cosmology in any way at this point and it will just confuse people.
