### ISSUE TITLE
test that fail due to URLS

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#6573]
On a recent test I had, there were test fails due to trying to access a URL that were unrelated to the pull request.  Some way of ignoring those tests when they are not related or replacing that with a safe failure would be helpful.   I'll add an example in the next comment. 

The test command that led to this:
Test command: python setup.py test --coverage --remote-data=astropy -a "--mpl"

cc. @drdavella @bsipocz

**Comment by crawfordsm** [comment]
=================================== FAILURES ===================================
__________________________ TestBasic.test_plot_coord ___________________________
args = (<astropy.visualization.wcsaxes.tests.test_images.TestBasic object at 0x7f6e32e1fef0>,)
kwargs = {}
baseline_dir = 'http://data.astropy.org/testing/astropy/2017-07-12T14:12:26.217559/1.5.x/'
baseline_remote = True
inspect = <module 'inspect' from '/home/travis/miniconda/envs/test/lib/python3.6/inspect.py'>
fig = <matplotlib.figure.Figure object at 0x7f6e32e160b8>
filename = 'test_plot_coord.png', result_dir = '/tmp/tmp584noput'
test_image = '/tmp/tmp584noput/test_plot_coord.png'
    @wraps(item.function)
    def item_function_wrapper(*args, **kwargs):
    
        baseline_dir = compare.kwargs.get('baseline_dir', None)
        if baseline_dir is None:
            if self.baseline_dir is None:
                baseline_dir = os.path.join(os.path.dirname(item.fspath.strpath), 'baseline')
            else:
                baseline_dir = self.baseline_dir
        else:
            if not baseline_dir.startswith(('http://', 'https://')):
                baseline_dir = os.path.join(os.path.dirname(item.fspath.strpath), baseline_dir)
    
        baseline_remote = baseline_dir.startswith('http')
    
        with plt.style.context(style), switch_backend(backend):
    
            # Run test and get figure object
            import inspect
            if inspect.ismethod(original):  # method
                # In some cases, for example if setup_method is used,
                # original appears to belong to an instance of the test
                # class that is not the same as args[0], and args[0] is the
                # one that has the correct attributes set up from setup_method
                # so we ignore original.__self__ and use args[0] instead.
                fig = original.__func__(*args, **kwargs)
            else:  # function
                fig = original(*args, **kwargs)
    
            if remove_text:
                MplImageComparisonTest.remove_text(fig)
    
            # Find test name to use as plot name
            filename = compare.kwargs.get('filename', None)
            if filename is None:
                filename = item.name + '.png'
                filename = filename.replace('[', '_').replace(']', '_')
                filename = filename.replace('/', '_')
                filename = filename.replace('_.png', '.png')
    
            # What we do now depends on whether we are generating the
            # reference images or simply running the test.
            if self.generate_dir is None:
    
                # Save the figure
                result_dir = tempfile.mkdtemp(dir=self.results_dir)
                test_image = os.path.abspath(os.path.join(result_dir, filename))
    
                fig.savefig(test_image, **savefig_kwargs)
                plt.close(fig)
    
                # Find path to baseline image
                if baseline_remote:
>                   baseline_image_ref = _download_file(baseline_dir + filename)
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pytest_mpl/plugin.py:204: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pytest_mpl/plugin.py:50: in _download_file
    u = urlopen(url)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:223: in urlopen
    return opener.open(url, data, timeout)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:532: in open
    response = meth(req, response)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:642: in http_response
    'http', request, response, code, msg, hdrs)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:570: in error
    return self._call_chain(*args)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:504: in _call_chain
    result = func(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <urllib.request.HTTPDefaultErrorHandler object at 0x7f6e5f04eef0>
req = <urllib.request.Request object at 0x7f6e3480dd68>
fp = <http.client.HTTPResponse object at 0x7f6e34839ac8>, code = 502
msg = 'Bad Gateway', hdrs = <http.client.HTTPMessage object at 0x7f6e348391d0>
    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
E       urllib.error.HTTPError: HTTP Error 502: Bad Gateway
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:650: HTTPError
__________________ TestBasic.test_tick_angles_non_square_axes __________________
args = (<astropy.visualization.wcsaxes.tests.test_images.TestBasic object at 0x7f6e34034da0>,)
kwargs = {}
baseline_dir = 'http://data.astropy.org/testing/astropy/2017-07-12T14:12:26.217559/1.5.x/'
baseline_remote = True
inspect = <module 'inspect' from '/home/travis/miniconda/envs/test/lib/python3.6/inspect.py'>
fig = <matplotlib.figure.Figure object at 0x7f6e3490b550>
filename = 'tick_angles_non_square_axes.png', result_dir = '/tmp/tmp77r2y_zt'
test_image = '/tmp/tmp77r2y_zt/tick_angles_non_square_axes.png'
    @wraps(item.function)
    def item_function_wrapper(*args, **kwargs):
    
        baseline_dir = compare.kwargs.get('baseline_dir', None)
        if baseline_dir is None:
            if self.baseline_dir is None:
                baseline_dir = os.path.join(os.path.dirname(item.fspath.strpath), 'baseline')
            else:
                baseline_dir = self.baseline_dir
        else:
            if not baseline_dir.startswith(('http://', 'https://')):
                baseline_dir = os.path.join(os.path.dirname(item.fspath.strpath), baseline_dir)
    
        baseline_remote = baseline_dir.startswith('http')
    
        with plt.style.context(style), switch_backend(backend):
    
            # Run test and get figure object
            import inspect
            if inspect.ismethod(original):  # method
                # In some cases, for example if setup_method is used,
                # original appears to belong to an instance of the test
                # class that is not the same as args[0], and args[0] is the
                # one that has the correct attributes set up from setup_method
                # so we ignore original.__self__ and use args[0] instead.
                fig = original.__func__(*args, **kwargs)
            else:  # function
                fig = original(*args, **kwargs)
    
            if remove_text:
                MplImageComparisonTest.remove_text(fig)
    
            # Find test name to use as plot name
            filename = compare.kwargs.get('filename', None)
            if filename is None:
                filename = item.name + '.png'
                filename = filename.replace('[', '_').replace(']', '_')
                filename = filename.replace('/', '_')
                filename = filename.replace('_.png', '.png')
    
            # What we do now depends on whether we are generating the
            # reference images or simply running the test.
            if self.generate_dir is None:
    
                # Save the figure
                result_dir = tempfile.mkdtemp(dir=self.results_dir)
                test_image = os.path.abspath(os.path.join(result_dir, filename))
    
                fig.savefig(test_image, **savefig_kwargs)
                plt.close(fig)
    
                # Find path to baseline image
                if baseline_remote:
>                   baseline_image_ref = _download_file(baseline_dir + filename)
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pytest_mpl/plugin.py:204: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pytest_mpl/plugin.py:50: in _download_file
    u = urlopen(url)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:223: in urlopen
    return opener.open(url, data, timeout)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:532: in open
    response = meth(req, response)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:642: in http_response
    'http', request, response, code, msg, hdrs)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:570: in error
    return self._call_chain(*args)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:504: in _call_chain
    result = func(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <urllib.request.HTTPDefaultErrorHandler object at 0x7f6e5f04eef0>
req = <urllib.request.Request object at 0x7f6e341b2198>
fp = <http.client.HTTPResponse object at 0x7f6e34311358>, code = 502
msg = 'Bad Gateway', hdrs = <http.client.HTTPMessage object at 0x7f6e34a385f8>
    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
E       urllib.error.HTTPError: HTTP Error 502: Bad Gateway
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:650: HTTPError
_______________________ TestBasic.test_ticks_regression ________________________
args = (<astropy.visualization.wcsaxes.tests.test_images.TestBasic object at 0x7f6e340d3860>,)
kwargs = {}
baseline_dir = 'http://data.astropy.org/testing/astropy/2017-07-12T14:12:26.217559/1.5.x/'
baseline_remote = True
inspect = <module 'inspect' from '/home/travis/miniconda/envs/test/lib/python3.6/inspect.py'>
fig = <matplotlib.figure.Figure object at 0x7f6e34a5d7f0>
filename = 'test_ticks_regression_1.png', result_dir = '/tmp/tmplkh28tfc'
test_image = '/tmp/tmplkh28tfc/test_ticks_regression_1.png'
    @wraps(item.function)
    def item_function_wrapper(*args, **kwargs):
    
        baseline_dir = compare.kwargs.get('baseline_dir', None)
        if baseline_dir is None:
            if self.baseline_dir is None:
                baseline_dir = os.path.join(os.path.dirname(item.fspath.strpath), 'baseline')
            else:
                baseline_dir = self.baseline_dir
        else:
            if not baseline_dir.startswith(('http://', 'https://')):
                baseline_dir = os.path.join(os.path.dirname(item.fspath.strpath), baseline_dir)
    
        baseline_remote = baseline_dir.startswith('http')
    
        with plt.style.context(style), switch_backend(backend):
    
            # Run test and get figure object
            import inspect
            if inspect.ismethod(original):  # method
                # In some cases, for example if setup_method is used,
                # original appears to belong to an instance of the test
                # class that is not the same as args[0], and args[0] is the
                # one that has the correct attributes set up from setup_method
                # so we ignore original.__self__ and use args[0] instead.
                fig = original.__func__(*args, **kwargs)
            else:  # function
                fig = original(*args, **kwargs)
    
            if remove_text:
                MplImageComparisonTest.remove_text(fig)
    
            # Find test name to use as plot name
            filename = compare.kwargs.get('filename', None)
            if filename is None:
                filename = item.name + '.png'
                filename = filename.replace('[', '_').replace(']', '_')
                filename = filename.replace('/', '_')
                filename = filename.replace('_.png', '.png')
    
            # What we do now depends on whether we are generating the
            # reference images or simply running the test.
            if self.generate_dir is None:
    
                # Save the figure
                result_dir = tempfile.mkdtemp(dir=self.results_dir)
                test_image = os.path.abspath(os.path.join(result_dir, filename))
    
                fig.savefig(test_image, **savefig_kwargs)
                plt.close(fig)
    
                # Find path to baseline image
                if baseline_remote:
>                   baseline_image_ref = _download_file(baseline_dir + filename)
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pytest_mpl/plugin.py:204: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pytest_mpl/plugin.py:50: in _download_file
    u = urlopen(url)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:223: in urlopen
    return opener.open(url, data, timeout)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:532: in open
    response = meth(req, response)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:642: in http_response
    'http', request, response, code, msg, hdrs)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:570: in error
    return self._call_chain(*args)
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:504: in _call_chain
    result = func(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <urllib.request.HTTPDefaultErrorHandler object at 0x7f6e5f04eef0>
req = <urllib.request.Request object at 0x7f6e34408fd0>
fp = <http.client.HTTPResponse object at 0x7f6e34408d68>, code = 502
msg = 'Bad Gateway', hdrs = <http.client.HTTPMessage object at 0x7f6e34408b70>
    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
E       urllib.error.HTTPError: HTTP Error 502: Bad Gateway
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:650: HTTPError
= 3 failed, 10205 passed, 107 skipped, 88 xfailed, 3 xpassed in 560.97 seconds =

**Comment by pllim** [comment]
FWIW -- This sounds tricky to me. Sometimes you think it is not related but turns out to be some unexpected connection (e.g., you unearthed a corner case of some underlying common "utils"). Was this failure transient? If it is a one-time thing, there is probably not much we can do. If it is persistent, it might be a bug.

**Comment by eteq** [comment]
@crawfordsm - can you clarify if you mean this for local vs. CI?  For CI I think this is very difficult, but locally there might be something to be done.  But the first question is: given @pllim's point above, why not instead just limit which *test* you are running?

**Comment by saimn** [comment]
That comes from the mpl plugin, which *I think* download reference images from the Astropy server to compare these images with the ones generated in tests. And sometimes the server does not respond.

**Comment by bsipocz** [comment]
@crawfordsm - would the suggestion above of running local tests only for the affected module work for you? 

In terms of CI, I'm afraid we have to live with this or figure out a backup server (e.g. all this data is also stored at github, so I can imagine a fallback to that URL if the astropy server gives an urlerror). Turning off parts of the testing that seems unrelated is just a big can of worms and kills the main principle of running CI at the first place.

**Comment by astrofrog** [comment]
I wonder if the mirror stuff in https://github.com/astropy/astropy/pull/5547 is really working in this case - it seems unlikely both URLs would fail. Maybe when we run tests we should output more information about which URLs are being accessed?

**Comment by astrofrog** [comment]
Actually I'm pretty sure in this case the mirror isn't being used - because the error happens when pytest-mpl is accessed with:

```
baseline_dir = 'http://data.astropy.org/testing/astropy/2017-07-12T14:12:26.217559/1.5.x/'
```

So I think the fix here is to actually make pytest-mpl support mirrors and add ``data2.astropy.org`` as a mirror.

**Comment by astrofrog** [comment]
I think this will be fixable once we have https://github.com/matplotlib/pytest-mpl/pull/59. I think that adding the GitHub server as a mirror will likely solve this (since the likelihood of both servers - including GitHub - being down is very low)

**Comment by bsipocz** [comment]
Well, if github is down, we're probably not pushing commits, and travis isn't starting builds either...

**Comment by bsipocz** [comment]
@astrofrog - will you do a new pytest-mpl release, or shall we switch to use the dev version instead?

**Comment by astrofrog** [comment]
I'll do a new release, but probably won't get to it until Monday.

**Comment by astrofrog** [comment]
In the mean time a new version of pytest-mpl was released so this shouldn't be an issue anymore.
