### ISSUE TITLE
Should Quantity copy as a default?

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#6578]
This is something that came up in #3174 and was re-raised by @astrofrog in discussions at the coordination meeting this week. Should the default Quantity creation be `copy=True` or `copy=False`? Currently, it's `copy=True`. Should this copy `data`?
```python
import numpy as np
import astropy.units as u

data = np.arange(10000)
a = data * u.m
```

**Comment by adrn** [comment]
I think the point is that, though it uses the multiplication operator, it *isn't* multiplication - it's like "association" of a unit with an array.

**Comment by adrn** [comment]
(I'll let @astrofrog comment, but his gut was to introduce a new operator)

**Comment by astrofrog** [comment]
Another option:

```
from astropy.units import nocopy as unc
```

**Comment by MSeifert04** [comment]
> I think the point is that, though it uses the multiplication operator, it isn't multiplication - it's like "association" of a unit with an array.

I thought associating an array with a unit was `Quantity(data, unit='m', copy=False)`. I can see why no-copy on multiplication may seem attractive but even overloaded operators in Python (like `%` on strings or `/` on `pathlib.Path`) create new objects, they don't change existing ones.

I know that least-astronishment seems counterproductive for performance here but just because one can do something it doesn't mean it should. Don't we have an `asquantity` function (like `numpy.asarray`) that tries to avoid copies if possible? That would seem like a far better option than to import a `nocopy`, using a `config` or making multiplication in-place.

**Comment by saimn** [comment]
I think it should *not* copy by default, in my mind the operation is just attaching a unit to the data. But I remember ~1 year I was about to raise this issue and found an older issue explaining the current behavior. I think by @mhvk but I will try to find it.

**Comment by saimn** [comment]
This is a recurrent discussion : #3174  #5034 #5035 :wink:

**Comment by mhvk** [comment]
The conclusion from the discussion in #3174 was that we should probably implement a context manager that sets the default for the `copy` argument. I think that is cleaner than using another operator (e.g., `value | unit`), in that it clearly shows what is being changed. `with u.no_copy(): ...`

PR welcome...

**Comment by adrn** [comment]
Right, but the proposal here is re-opening the discussion of default behavior: to not copy by default.  Then, the context manager would be unnecessary because, e.g., `a = (15*u.m).copy()`

**Comment by mhvk** [comment]
I'm :-1: on not copying by default, as it breaks expectations of how python operators behave. Also, I think `a * u.m` and `a * (1.*u.m)` should behave identically, i.e., neither should return a view of `a`.

**Comment by astrofrog** [comment]
The issue with a context manager is that it affects code inside functions that may be called and may cause weird side effects as a result, so that doesn't seem safe to me.

**Comment by mhvk** [comment]
> The  issue with a context manager is that it affects code inside functions  that may be called and may cause weird side effects as a result, so that  doesn't seem safe to me.

Allowing people to change the default if they really feel it helps them in what can be, if they're careful, a suitably limited context, would seem less problematic than forcing a change of default on them!

Am I missing the point of the issue, though?!

**Comment by mhvk** [comment]
I should perhaps add that currently
```
data *= u.m
```
does actually turn `data` into a `Quantity`, but also makes a copy. It may be possible to make the default `False` for that case (at least for numpy >=1.13), though of course then:
```
data = np.arange(10)
q = data
q *= u.m
q[5] = 100 * u.cm
```
will affect `data` as well.

**Comment by mhvk** [comment]
Actually, the example at the top is a good reason for copying: as written, `data` are integer, and one generally really does *not* want any quantities be integers. Though to protect against that, a copy would already be made even if the default were `copy=False`, just to get the float dtype....

**Comment by astrofrog** [comment]
> Allowing people to change the default if they really feel it helps them in what can be, if they're careful, a suitably limited context, would seem less problematic than forcing a change of default on them!

I agree - I think that neither the context manager nor changing the default are the right solution though. I think cleaner solutions would include:

###  A custom operator:

```
>>> array | u.m / u.s
```

### A way to indicate that units should be used in no copy mode

For example an underscore suffix:

```
>>> array * u.m_
```

### A sub-package that behaves like units but without copy

```
>>> from astropy.units import units as u
>>>  array * u.m
```

or

```
>>> from astropy.units import units as un
>>> array * un.m
```

(the latter if we don't want to cause confusion when reading code without looking at imports)

**Comment by MSeifert04** [comment]
What's wrong with just using `u.Quantity(array, unit=whatever, copy=False)`?

**Comment by astrofrog** [comment]
@MSeifert04 - it is very verbose!

**Comment by astrofrog** [comment]
Anyway I guess I should probably have commented on https://github.com/astropy/astropy/issues/3174...

**Comment by astrofrog** [comment]
Shall we stop discussing here and continue in #3174?

**Comment by adrn** [comment]
Yep! Sorry for making a duplicate - though I'm going to change the name of #3174 to be more relevant to the discussion
