### ISSUE TITLE
Truth values of quantities

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#6580]
This is just a small gotcha about the truth value of quantities:

```
>>> import astropy.units as u
>>> bool(0)
False
>>> bool(0 * u.dimensionless_unscaled)
True
```

**Comment by MSeifert04** [comment]
Interesting, it seems like all `Quantities` are `True`.

**Comment by mhvk** [comment]
Indeed. For regular quantities, one could still argue that `0` should be `False`, but what about a logarithmic quantity? Should zero magnitude be `False`? Note furthermore that for anything but scalars, it becomes very unclear what `__bool__` means.

One question is whether it isn't better to just error on trying to get a `bool` out instead of returning `True`.

**Comment by lpsinger** [comment]
> Note furthermore that for anything but scalars, it becomes very unclear what __bool__ means.

We should follow Numpy's example:

```
>>> import numpy as np
>>> bool(np.asarray(0))
False
>>> bool(np.asarray([0]))
False
>>> bool(np.asarray([0, 0, 0]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by lpsinger** [comment]
> Interesting, it seems like all Quantities are True - intentionally.

It would be better to turn an zero quantity into `False` or unconditionally raise an exception, because `0 * u.dimensionless_unscaled` looks too much like `0`.

**Comment by mhvk** [comment]
I think we cannot quite follow `numpy` because of logarithmic units (or, e.g., degrees Celsius) where `0` is not special. But I agree with raising an exception instead of always returning `True` (what *is* the point of that!).

**Comment by MSeifert04** [comment]
Exception sounds good to me. But maybe make that a deprecation or futurewarning before. It could be that someone actually used that....

**Comment by maxnoe** [comment]
I just got a warning for this, that actually was a bug. It seems this was deprecated almost 5 years ago in version 3.0. 

Shouldn't we remove this now?

**Comment by pllim** [comment]
This is an issue. Do you mean the stuff in https://github.com/astropy/astropy/pull/6590 ?

**Comment by maxnoe** [comment]
I mean that the decision in this issue was that this should be first deprecated, then removed. I am asking if we reached "then"

**Comment by pllim** [comment]
Yes, you have reached it. 😸
