### ISSUE TITLE
Unicode guidelines update ?

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#6581]
I discovered the "Unicode guidelines" and with it the `astropy.conf.unicode_output` config item and the `assert_follows_unicode_guidelines` test helper.
http://docs.astropy.org/en/latest/development/codeguide.html#unicode-guidelines

I guess part of this is no more needed, but not sure about the unicode with "only 7-bit characters" ?

**Comment by bsipocz** [comment]
I'm milestoning this to 3.0, as it would be great to decide either way by then.

**Comment by saimn** [comment]
Note that #6566 remove the `__unicode__` mentions, so here the question is to know if it is still useful to have "7-bit characters" output. It's probably not as Python use more and more UTF-8 by default (for instance https://docs.python.org/3/whatsnew/3.6.html#pep-528-change-windows-console-encoding-to-utf-8).

**Comment by mhvk** [comment]
Removing milestone, as it doesn't seem like this will happen for 3.0

**Comment by embray** [comment]
I believe the test as currently written is still relevant and makes sense.  There are several issues that go into unicode output (especially to terminals) beyond just how well Python supports it.  Availability of fonts, what terminal is being used, what encoding / code page the user's environment is configured for, etc.    Unfortunately, even in this day and age, it's a bit dicey to assume unicode support in all program output by default.

**Comment by mhvk** [comment]
@embray - I agree that we cannot quite assume full unicode support (e.g., I tried to use strikethrough for my Masked class, but found that in terminals it did not work). I think the documentation explains it quite well, so would suggest deciding to keep everything as is. Of course, if so, there is little point to keep this issue open!

**Comment by pllim** [comment]
Hi humans :wave: - this issue was labeled as **Close?** approximately a month ago. If you think this issue should not be closed, a maintainer should remove the **Close?** label - otherwise, I will close this issue in 7 days.

*If you believe I commented on this issue incorrectly, please report this [here](https://github.com/pllim/action-astropy-stalebot/issues)*

**Comment by pllim** [comment]
Ops... Bot comment is accurate but I used the wrong API key. 😅
