### ISSUE TITLE
Remove python2 from the examples

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#6585]
This should be done in prep for the v3.0 release, we shouldn't teach legacy usage!

cc @kelle @pllim

**Comment by pllim** [comment]
Maybe tackle this after #6556 and #6566 are merged? It is not "legacy" until we remove the support in the first place.

**Comment by bsipocz** [comment]
Yes, totally agree, it was just triggered by the code showed on the screen during this sprint...
