### ISSUE TITLE
Table.read registry for google sheets

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#6587]
It would be really useful to have the functionality of being able to pass a URL to the Table.read function that was to a google sheet and then have that read in the sheet to an astropy.table.  So to have something like this work: 
    
     Tables.read('https://google_sheet/', format='google sheet') 

Even having something that works assuming that it is just a basic csv structure (square table, frozen rows are the header, just numerical values and not any functions) would be something very useful. 

Adding it as an issue as something I'd be interested in working on when I have some free time, but raising it as a reminder and in case anyone else can work on it before hand.

**Comment by pllim** [comment]
Nitpick: Avoid space in format name. Maybe `google_sheet`? Also, I wonder how formulas and linked cells are going to work with this. Do you get the formula/cell name or contents?

**Comment by astrofrog** [comment]
Note that we could do this for excel spreadsheets too. The main issue I've encountered in the past is make it so that headers work properly (i.e. detecting whether headers are present or not). But maybe we could have some way of saying e.g. ``headers='A1:G1', data='A2:G100'``.

**Comment by xennygrimmato** [comment]
@crawfordsm I am interested in working on this issue.

**Comment by swapsha96** [comment]
@astrofrog I would like to work on this. Could you please suggest a sample would look like considering the problem you mentioned? I think this can be done using Pandas and I would like to work on it.

**Comment by asifmallik** [comment]
If no one is working on this currently, I would like to take this up

**Comment by bsipocz** [comment]
@asifmallik - Please go ahead, we haven't received any PRs for this yet.

**Comment by himanshupathak21061998** [comment]
I want to work on this issue. My approach will be something like this :-https://towardsdatascience.com/how-to-access-google-sheet-data-using-the-python-api-and-convert-to-pandas-dataframe-5ec020564f0e

**Comment by pllim** [comment]
@himanshupathak21061998 , thank you for the link. However, I am a little wary of solution that requires I/O of secret credentials in plain text, especially if it is not officially from Google Sheets dev. I see Google has [Python Quickstart](https://developers.google.com/sheets/api/quickstart/python) but I am not sure how updated it is.

In general, I am also worried about the maintenance cost we're signing ourselves up going forward as Google API changes upstream.
