### ISSUE TITLE
Remote access without remote_data mark

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#6588]
During the test, I git the following warning:
```
coordinates/tests/test_sky_coord.py::test_repr_altaz
  /usr/lib/python3/dist-packages/astropy/utils/iers/iers.py:584: AstropyWarning:
 failed to download http://maia.usno.navy.mil/ser7/finals2000A.all, using local IERS-B:
 <urlopen error An attempt was made to connect to the internet by a test that was not marked `remote_data`. The requested host was: maia.usno.navy.mil>
    .format(conf.iers_auto_url, str(err))))
```

**Comment by pllim** [comment]
I get this sometimes too and in my case, it is usually transient. Would be nice to fix up the logic so a more meaningful error is raised instead.

**Comment by olebole** [comment]
Hmm, is the error message misleading? I thought that just the mark is missing? (I however got quite a number of those warnings)

**Comment by pllim** [comment]
Is it persistent for you?

**Comment by pllim** [comment]
@bmorris3 and @mhvk (tagged based on `git blame`), do you know if `test_repr_altaz` in `astropy/coordinates/tests/test_sky_coord.py` should use `@remote_data`? Why does it attempt to connect to internet via `utils.iers`? Is it supposed to?

**Comment by mhvk** [comment]
I bet it is trying to download a recent `IERS-A` table. It should be possible to avoid this by either changing the date or explicitly turning internet off, but I forgot exactly how (and don't have time to investigate...), so cc @taldcroft 

p.s. It also reminds me we should update the standard `IERS-B` table...

**Comment by bsipocz** [comment]
These tests got the remote_data mark in https://github.com/astropy/astropy/pull/8033. 

Please reopen/open a new issue if you run into this again with the latest astropy.
