### ISSUE TITLE
Cannot create SkyCoord array from list of SkyCoord in certain frames

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#6597]
```python
>>> from astropy.coordinates import SkyCoord
>>> frame = 'galactic'
>>> c1 = SkyCoord(1, 3, unit='deg', frame=frame)
>>> c2 = SkyCoord(2, 4, unit='deg', frame=frame)
>>> sc1 = SkyCoord([c1, c2])
AttributeError: 'SkyCoord' object has no attribute 'ra'
```

This fails for all frames where the `SkyCoord` list items do not have a RA/Dec, e.g. galactic, supergalactic, altaz, etc.

**Comment by pllim** [comment]
Did you cut out the full traceback? Please put it back in, as it is useful.

**Comment by eteq** [comment]
I was able to reproduce the problem - it's a bit tricky to fix but am working on it.
