### ISSUE TITLE
Astropy can't handle 32 bit, single channel FITS correctly

### ISSUE THREAD

**Issue by kecsap** [astropy/astropy#6611]
I tested the stable and bleeding-edge version in python 2 & 3, same results. Here it is a simple FITS, created by astrometry.net's solve-field command:

https://www.dropbox.com/s/veo707ejydb43zj/example.fits?dl=0

If I run a simple:

import sys
from astropy.io import fits

hdulist = fits.open("example.fits")
hdulist.writeto("example_new.fits")
hdulist.close()

...the saved new FITS file is incorrect and reporting -64 bit depth etc.:

https://www.dropbox.com/s/z8j84aohqrt8npy/example_new.fits?dl=0

**Comment by kecsap** [comment]
@astrofrog: Why does it convert to 64 bit by default? Can I force to keep 32 bit?

Ah, sorry, I see now that -64 is valid for BITPIX field.

**Comment by kecsap** [comment]
Ok, I close this issue. If I open the FITS file only for update to add new entries to the header, it does not convert the data to 64 bit. It is enough for me.

**Comment by saimn** [comment]
It's because your file has BSCALE and BZERO keywords, and they are not preserved. You can use `do_not_scale_image_data=True` to be sure it does not happen, if it's only to modify the header, but I think it's a bug.

```
❯ fitsdiff example.fits example_new.fits

 fitsdiff: 3.0.dev20121
 a: example.fits
 b: example_new.fits
 Maximum number of different data values to be reported: 10
 Relative tolerance: 0.0, Absolute tolerance: 0.0

Primary HDU:

   Headers contain differences:
     Headers have different number of cards:
      a: 127
      b: 125
     Extra keyword 'BSCALE' in a: 1.0
     Extra keyword 'BZERO'  in a: 2147484000.0
     Keyword BITPIX   has different values:
        a> 32
        b> -64
```

**Comment by saimn** [comment]
After verification, the current behavior is expected:
http://docs.astropy.org/en/latest/io/fits/appendix/faq.html#why-is-an-image-containing-integer-data-being-converted-unexpectedly-to-floats
So you can either use `do_not_scale_image_data` to avoid the scaling, or use `.scale('int32')` to scale back the data before writing.
