### ISSUE TITLE
Adjust CircleCI image to better find 32-bit failures

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6616]
@matthew-brett reported in https://github.com/astropy/astropy/pull/6557 a 32-bit issue. The reason we have the CircleCI testing is to catch this kind of issue on 32-bit Python, but for some reason this didn't get picked up. So we need to investigate why that is, and how we can make sure we catch this kind of issue sooner.

This is our docker file: https://github.com/astropy/astropy-docker/blob/master/32bit-py3/Dockerfile (there is also one for py2 with an older Numpy version). Anyone know why we didn't catch this issue sooner? (@matthew-brett?)

**Comment by matthew-brett** [comment]
Is it possible you were using a version of numpy >= 1.10 for testing?  The problem only occurs for earlier numpy.

**Comment by astrofrog** [comment]
Now yes, but until a couple of weeks ago we used Numpy 1.9 with this docker container: https://github.com/astropy/astropy-docker/tree/master/32bit-py2 - and this still didn't get picked up...

**Comment by bsipocz** [comment]
I think now we're much better to pick up the 32bit failures, at least there wasn't any that came up during the last two RC testing but not during CI.

Feel free to open if you think otherwise.

**Comment by astrofrog** [comment]
Yeah we now use the same container as for wheels, so it's been a lot better!
