### ISSUE TITLE
Handle cache if loading it fails

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6620]
See #3755 for implementation discussions. That PR was originally meant to address #3754 but also covered some larger issue.

**Comment by StephenWeber** [comment]
So, if I'm reading #3755 correctly, the implementation requests are:
* Convert cache to use built-in sqlite as storage
* if the cache index can't be loaded, delete it and start over
* don't delete downloaded files

Are those still correct, and are there any more requirements? I also found #24 which has some good code (with a few adjustments to be made) but uses `anydbm` which isn't mentioned in #3755.

**Comment by pllim** [comment]
Probably irrelevant after the big refactoring in 4.0.
