### ISSUE TITLE
super calls with arguments

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#6630]
I touched a lot of `super` calls in #6629 and #6613 but there are several remaining occurences that haven't been using the current class as first argument and/or the "bound argument" (first argument of the method) as second argument.

I believe lots of them are actually bugs but some of these look intentional. It could be worthwhile to revisit the remaining ones, just to exclude potential bugs and in case it was accidental to remove the obsolete arguments.

**Comment by pllim** [comment]
Do you happen to have notes on where the remaining ones are?

**Comment by MSeifert04** [comment]
Not sure if that's still correct but I have this list:

```
coordinates\angles.py 535
coordinates\angles.py 659
coordinates\representation.py 2576
coordinates\tests\test_regression.py 390
extern\bundled\six.py 105
extern\bundled\six.py 126
extern\bundled\six.py 141
io\ascii\ipac.py 27
io\ascii\ipac.py 34
io\ascii\latex.py 339
io\ascii\latex.py 437
io\fits\verify.py 129
io\fits\hdu\compressed.py 1424
modeling\core.py 369
modeling\core.py 416
modeling\parameters.py 100
modeling\polynomial.py 392
modeling\polynomial.py 498
modeling\polynomial.py 701
table\column.py 315
table\index.py 402
tests\command.py 53
tests\helper.py 292
tests\helper.py 296
tests\helper.py 320
tests\helper.py 339
tests\pytest_plugins.py 224
tests\runner.py 130
tests\runner.py 512
tests\tests\test_socketblocker.py 21
tests\tests\test_socketblocker.py 26
time\core.py 121
time\core.py 878
units\format\base.py 16
```

**Comment by bsipocz** [comment]
I've removed the package-novice tag, as for this one has to have some idea about the intentions for those calls, as @MSeifert04 said above they may very well be a bug or there for a reason.

**Comment by MSeifert04** [comment]
I also found the script:

```
import pathlib
import re

astropy_dir = ...
for filepath in pathlib.Path(astropy_dir).glob('**/*.py'):
    for lineno, line in enumerate(filepath.open(encoding='utf-8')):
        if re.search(r'super\(\w', line):
            print(filepath.relative_to(astropy_dir), lineno)
```

**Comment by pllim** [comment]
Okay, retagged to "expert" (but for an expert, shouldn't take long to determine whether it is bug or not, so also modified the "effort" tag).

**Comment by mhvk** [comment]
Removing milestone -- not sure what we can do right now. Would be good to update the list with calls that have not been checked.
