### ISSUE TITLE
Unexpected behavior with SkyCoord.separation method

### ISSUE THREAD

**Issue by petigura** [astropy/astropy#6633]
Dear Astropy, 

Thanks for such a useful project!

I noticed an unexpected behavior when computing separations between two sets of SkyCoords. When one of the SkyCoods is an array and the other is a single value,  `array.separation(value)` produces the correct result but `value.separation(array)` does not.  Here's a simple example involving computing the distance between the Kepler field and the moon.

Cheers,

Erik

```python
%pylab inline
from astropy.time import Time
import astropy.coordinates
from astropy.coordinates import SkyCoord, EarthLocation
from astropy import units as u

loc = EarthLocation.of_site('KPNO')

t0 = Time('2017-01-01 00:00:00', scale='utc')
t = t0 + np.arange(0.,365,1) * u.day
moon = astropy.coordinates.get_moon(t,location=loc)
kepler = SkyCoord('19h22m', '+44d30m', frame='icrs')

sep = moon.separation(kepler)
plot(t.datetime, sep.degree)

sep = kepler.separation(moon)
plot(t.datetime, sep.degree)
```

![image](https://user-images.githubusercontent.com/694371/31048675-011d5cce-a5d7-11e7-878b-fe6ab65a9c82.png)

**Comment by adrn** [comment]
Hi Erik --

FYI: I updated your comment above to add `loc = EarthLocation.of_site('KPNO')` (which was undefined before) - the exact site doesn't really matter, just need some Earth location to pass to `get_moon()`. 

In any case, yes, I can confirm that I see what you see in the plot! No immediate answer, but will take a look.

cc @eteq @mhvk

**Comment by adrn** [comment]
On second thought, I have an idea for what's going on, but haven't yet looked at `.separation()` to be sure (will get back to you shortly). 

`get_moon()` returns the Moon's position in the [GCRS](http://docs.astropy.org/en/latest/api/astropy.coordinates.GCRS.html#astropy.coordinates.GCRS) frame, which is axis-aligned with the ICRS frame but is centered on the Earth's center of mass. I suspect that when you do `moon.separation(kepler)`, it's converting the `kepler` ICRS position to the GCRS frame, then computing the separation in this time-dependent frame. When you do `kepler.separation(moon)`, it's converting the GCRS `moon` position to the ICRS frame, and computing the separation there. It's not immediately obvious to me why the resulting curves look the way they do, but this small test seems to confirm: if I do this instead

```python
sep = moon.transform_to(coord.ICRS).separation(kepler)
plt.plot(t.datetime, sep.degree, marker='', linestyle='-', color='r')

sep = kepler.separation(moon)
plt.plot(t.datetime, sep.degree, marker='', linestyle='--')
```
I get:
![image](https://user-images.githubusercontent.com/583379/31050882-dcd79c44-a626-11e7-9160-7f31198ac9d5.png)

**Comment by StuartLittlefair** [comment]
@adrn is right. It may not be particularly intuitive - I’ve been bitten by this myself in the past - but this is the expected, and I think correct, behaviour. 

```posA.separation(posB)``` calculates the separation of A and B, *in the frame of object A*. The mistake is to think that ```separation``` gives the separation on the sky, when it does not.

**Comment by petigura** [comment]
Thanks for looking into this! If this is the expected behavior than that's great. It might help others if the docs were a little more explicit about this.

- The get_moon docstring doesn't say anything about the coordinates being in the GCRS frame.
- I imagine that calculating target/moon and target/sun separations is a pretty common use-case of the astropy package, so if the separation method is counter intuitive, this should be stated explicitly.

Cheers,

Erik

**Comment by adrn** [comment]
I totally agree! This is a documentation fail. Thanks for bringing this up!

**Comment by ricozan** [comment]
I just want to clarify that when dealing with the moon and a target, e.g for preparing observations one should use:

moon.separation( target )

thanks! I was also puzzled by this and I'm glad I found this post.
