### ISSUE TITLE
pip install astropy ignore numpy version requirement

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#6650]
This should not be possible, when 2.0.2 has a minimum numpy dependency of >=1.9.0.

Currently this minimum version is supposed to be included in ``setup.py``'s ``setup_requires`` and ``install_requires``, but via ``__init__.py``. Failing this install early is I think the desirable approach.

```
pip2.7 install astropy==2.0.2 numpy==1.8.2
Collecting astropy==2.0.2
  Downloading astropy-2.0.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (7.7MB)
    100% |████████████████████████████████| 7.7MB 131kB/s 
Collecting numpy==1.8.2
  Downloading numpy-1.8.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl (12.0MB)
    100% |████████████████████████████████| 12.1MB 87kB/s 
Requirement already satisfied: pytest>=2.8 in /sw/lib/python2.7/site-packages (from astropy==2.0.2)
Requirement already satisfied: py>=1.4.33 in /sw/lib/python2.7/site-packages (from pytest>=2.8->astropy==2.0.2)
Requirement already satisfied: setuptools in /sw/lib/python2.7/site-packages (from pytest>=2.8->astropy==2.0.2)
Installing collected packages: numpy, astropy
Successfully installed astropy-2.0.2 numpy-1.8.2
```

**Comment by cosmoscalibur** [comment]
This is a `pip` issue when you use explicit installation of a dependecy (any package suffer this).

**Comment by cosmoscalibur** [comment]
@bsipocz  First of all, what is your necessity to install numpy with explicit version when astropy has the required version?  
Version used in the pip call override the version used in setup or requirement file. You need to install astropy after install numpy to update numpy version.

**Comment by bsipocz** [comment]
I agree with @pllim that this is hardly an astropy issue, and based on the comment above is actually a feature. (I can't remember now what I wanted to achieve, probably just tried to provoke to get the error from astropy that I installed a non supported numpy version)
