### ISSUE TITLE
Is/was stats.lombscargle.implementations.utils.add_at public API?

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#6661]
I removed this `np.add.at` wrapper function in #6642 based on the assumption that it wasn't needed anymore and not public API (I couldn't find it in the docs). @taldcroft recently said that "we should be more careful when removing or altering public API", so I wanted to ask if that function needs to be re-added with a deprecation or if removing it was okay.

**Comment by crawfordsm** [comment]
My suspicion is it is fine to remove, but I'll cc @jakevdp just in case.

**Comment by jakevdp** [comment]
I think it's fine to remove it – I never meant it to be public API, it's obsolete now that we don't need to support older numpy versions, and users would really have to dig to find and use it.

**Comment by MSeifert04** [comment]
Thank you for the confirmation. I'll close the issue then.
