### ISSUE TITLE
The brightness temperature equivalence is confusing

### ISSUE THREAD

**Issue by smaret** [astropy/astropy#6663]
The `astropy.units.equivalencies.brightness_temperature()` is very confusing. According to the documentation, it defines a conversion between Jy/beam and the brightness temperature in Kelvins. It is defined as:
![capture d ecran 2017-10-05 a 11 53 38](https://user-images.githubusercontent.com/95471/31221405-e40ad9c2-a9c3-11e7-9d80-7a026d686ae2.png)
where S_nu the flux density, usually expressed in Jy/sr. The documentation also says that the beam area is essential for this computation: the brightness temperature is inversely proportional to the beam area. 

However, by definition, the brightness temperature does *not* depends on the beam size: it is simply defined as the temperature of a black body with the same flux density (note that equation above is only valid in the Rayleigh-Jeans approximation). It is *not* inversely proportional to the beam area (there is perhaps a confusion with the beam temperature, which is a different thing).

I think this equivalence should define a conversion between Jy/sr (or equivalent units) to Kelvins, which does not depend on the beam. The beam is only needed to convert between Jy/sr and Jy/beam, but this is straightforward.

cc @keflavich

**Comment by keflavich** [comment]
See https://github.com/astropy/astropy/pull/5173.  I agree.

**Comment by smaret** [comment]
> See #5173

Thanks. I'll have a look at your PR to see if I can help.

**Comment by smaret** [comment]
Closed with #5173.
