### ISSUE TITLE
The "weights" parameter when calling a fitter is missing in the documentation

### ISSUE THREAD

**Issue by hopehhchen** [astropy/astropy#6666]
While there is a "`weights`" parameter when calling a fitter in `astropy.modeling`, it is not in [the documentation](http://docs.astropy.org/en/stable/api/astropy.modeling.fitting.LinearLSQFitter.html#astropy.modeling.fitting.LinearLSQFitter) nor on [the page where people are pointed to](http://docs.astropy.org/en/stable/modeling/fitting.html) from the main `astropy.modeling` documentation page.  Is there a reason why?

**Comment by MSeifert04** [comment]
Thanks for the report. I'm working on this :)
