### ISSUE TITLE
Is the modeling registry necessary?

### ISSUE THREAD

**Issue by nden** [astropy/astropy#6673]
The `astropy.modeling` package keeps a registry of all classes that inherit from `Model`. It appears it is not used by anything internally at the moment. There's a note in the PR that added that it may be potentially useful for fitting in GUIs.

The problem is that when models are combined a new `CompoundModelxx` **class** is created and this class, and its submodel instances, are also added to the registry , making the memory grow up. 

Does anyone see a use for the registry? If not, I'd like to remove it. At the very least I think `CompoundModel` classes should not be registered. Any opinions?

**Comment by pllim** [comment]
@ibusko uses `modeling` for fitting in GUI, so if he doesn't use it, it is unlikely anyone does.
