### ISSUE TITLE
Build_docs command crashes (segfaults?)

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#6677]
When trying to use `python setup.py build_docs` I get the following error (Windows 10, Python 3.5, astropy master, libpng 1.6.32, sphinx 1.6.3, conda environment).

```
updating environment: 1061 added, 0 changed, 0 removed
libpng error: Write Error visualization/lupton_rgb
Sphinx Documentation subprocess failed with return code 3221226505
```

I suspect it's not really astropy specific but I don't know how to debug such an issue and find out where it really belongs but it currently prevents me from building the astropy docs locally. 😄

**Comment by saimn** [comment]
The `make_lupton_rgb` function has an option to save the result to a file, using `matplotlib.image.imsave` (which I guess use Pil/Pillow). And the example in the documentation is saving an image, which is probably useless btw. So I guess you have an installation issue or bug with image file saving via matplotlib (and pillow?).

**Comment by MSeifert04** [comment]
Yeah, I'm struggling a bit to find out where the error happened. I tried various combinations of `libpng`, `matplotlib` and `sphinx` already but couldn't find out where it happens. And I don't get my Visual studio to hook into the crash, so I don't get any tracebacks.

**Comment by saimn** [comment]
`build_docs` uses a subprocess to run Sphinx, which makes it difficult to debug. But I think running directly the [lupton_rgb](http://docs.astropy.org/en/latest/visualization/lupton_rgb.html) example should give the same error.

**Comment by pllim** [comment]
If what @saimn suggested doesn't work for you, to get a traceback from seg fault, I use [GDB](https://www.gnu.org/software/gdb/). Although I never tried it on Windows, but it claims to support Windows.

Don't have my Windows today. If you still have problem tracing this next week, give me a ping.

**Comment by drdavella** [comment]
@saimn this is like the test runner, which also uses a subprocess to run pytest. I understand this was necessary at one time, but the pytest case now seems needlessly complicated. I wonder if the sphinx case could be simplified as well.

**Comment by astrofrog** [comment]
On a related note, I'm not sure we've ever actually tested the docs building on Windows before!

**Comment by bsipocz** [comment]
> The make_lupton_rgb function has an option to save the result to a file, using matplotlib.image.imsave (which I guess use Pil/Pillow). And the example in the documentation is saving an image, which is probably useless btw.

@MSeifert04 - could you try out that removing saving the image would solve the building issue? If yes, then we should definitely remove/skip it from the example.

**Comment by MSeifert04** [comment]
@bsipocz How would I do that?

**Comment by bsipocz** [comment]
? 
In docs/visualization/lupton_rgb.rst remove the filename kwargs and try to build the docs locally, hoping that the build won't crash.

**Comment by MSeifert04** [comment]
Indeed, just a simple example like

```
import numpy as np
import matplotlib.image

matplotlib.image.imsave("ngc6976-default.jpeg", 
                        np.random.randint(0, 100, (50, 100, 3)).astype(np.uint8), 
                        origin='lower')
```

segfaults on my computer.

When I removed the `filename=` argument from the examples it was possible to build the documentation.

**Comment by bsipocz** [comment]
what about switching to use plt.savefig instead of image.imsave? that one seems to be used in wcsaxes?

**Comment by saimn** [comment]
Just an idea: could you try with "ngc6976-default.png" and "ngc6976-default.jpg" to see what happens ? You have an error with libpng above, though it should save a jpg file, that looks weird. 

Also this feature is tested but even if matplotlib is installed (so many not on Appveyor?) and with a png filename. And `matplotlib.image.imsave` uses `savefig` unless the extension is png!

**Comment by MSeifert04** [comment]
`.png` and `.jpg` also segfault with an `libpng error: Write Error` and immediate segfault.

I just made a PR to see if it works on AppVeyor. Maybe it's more a problem with my computer, not with `mpl` or `astropy`.

**Comment by saimn** [comment]
@drdavella : 
> @saimn this is like the test runner, which also uses a subprocess to run pytest. I understand this was necessary at one time, but the pytest case now seems needlessly complicated. I wonder if the sphinx case could be simplified as well.

I forgot to answer: I think here it is just to make sure that Astropy is built, and that astropy_helpers is importable. Nothing really fancy but the straightforward way to do that is to use a subprocess, which hides other sphinx features and makes it difficult to debug.

**Comment by saimn** [comment]
From http://matplotlib.org/users/installing.html:

> Pillow (>=2.0): for a larger selection of image file formats: JPEG, BMP, and TIFF image files;

Otherwise it seems that libpng is used directly. Not sure if it is an installation issue or a matplotlib one ;)

**Comment by MSeifert04** [comment]
Okay, it's not related to my computer (#6708 failed too) and there seems to be an issue about it https://github.com/ContinuumIO/anaconda-issues/issues/6535.

I guess for now I just use my local workaround given that it's an upstream-issue and (hopefully) fixed soon.

**Comment by mingwandroid** [comment]
Any chance of testing with this new package?:

`conda update -c c3i_test2 libpng`

**Comment by MSeifert04** [comment]
@mingwandroid Yes, that fixes the segfaults I encountered here. 👍

**Comment by bsipocz** [comment]
> I just made a PR to see if it works on AppVeyor. Maybe it's more a problem with my computer, not with mpl or astropy.

@MSeifert04 - Still, it would be nice not to generate those files also to avoid them showing up as untracked after building the docs...
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/visualization/ngc6976-default.jpeg
	docs/visualization/ngc6976.jpeg

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by MSeifert04** [comment]
The fixed build is now available  in the default conda channel 🎉. It fixes both issues so I'm closing this.
