### ISSUE TITLE
EOP in Python (Precession Nutation)

### ISSUE THREAD

**Issue by shbhuk** [astropy/astropy#6680]
Hi,
I am looking for a way to query the IERS bulletin and obtain the Earth Orientation Parameters in Python. The analogue of the IDL [hprstatn.pro](https://harrisgeospatial.com/docs/hprstatn.html) procedure.

Just checking if this is implemented in some form in Astropy. I know that I can query the IERS bulletin and obtain the table, but is the final product already done? 

My end goal is to obtain the x,y,z,vx,vy,vz of an observatory wrt the barycenter taking into consideration these movements.

**Comment by StuartLittlefair** [comment]
Hi @shbhuk 

```EarthLocation.get_gcrs_posvel``` does do (almost) what you require. The only thing not in there is IERS corrections to precession/nutation (```dX_2000A```, ```dY_2000A``` in the IERS tables). Comparison to PINT reveals that these make a difference at the 2m and 1/1000th of a cm/s level, which shouldn't be an issue for most people.

HOWEVER, I've found a bug in that routine (#6697) which limits the accuracy to the m/s level. I'll issue a PR for that bug soon.

**Comment by StuartLittlefair** [comment]
Also Fixes #6680?

Depends on the precision required by the end user.

**Comment by shbhuk** [comment]
On comparison of the PINT routine and `EarthLocation.get_gcrs_posvel ` we are observing a difference of about 0.5-0.6 m/s . We would ideally like of the order of mm/s.
