### ISSUE TITLE
Update emacs setup docs to recommend flycheck instead of flymake

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6681]
Partially a reminder to myself, but if anybody else has already done it and thus can help, do let me know!

Currently, we recommend an emacs setup using flymake, pyflakes, and pep8 for syntax checking [1], but these are no longer developed (I noticed because I get warnings about syntax errors for `metaclass=...` arguments to class definitions). Instead, the recommendation is to use `flycheck` [2] with `flake8` (which we're also using on travis). We should update the documentation (and I need to update my setup...).

[1] http://docs.astropy.org/en/latest/development/codeguide_emacs.html
[2] http://www.flycheck.org/en/latest/

**Comment by bsipocz** [comment]
Duplicate of #6568?

**Comment by mhvk** [comment]
Yes, closing...
