### ISSUE TITLE
Document install system

### ISSUE THREAD

**Issue by embray** [astropy/astropy#671]
As mentioned in #668, it would be nice to have some documentation, possibly including a small flow chart, explaining the steps that occur in the installation.

For the most part it's actually more straightforward than it may appear, especially with the recent refactoring done. But there are a few seemingly unusual hacks intended to circumvent design shortcomings in distutils that are worth further explanation.

**Comment by eteq** [comment]
This is no longer relevant given that the machinery has evolved a lot and is now mostly in the helpers
