### ISSUE TITLE
How to make the ticks inward of the frame in WCSaxes?

### ISSUE THREAD

**Issue by astrosumit** [astropy/astropy#6735]
Hi,
I was trying to display a fits file using WCSAxes. In my earlier version of matplotlib and WCSAxes, the ticks were appearing inward of the image frame. But, when I updated my astropy and matplotlib, the ticks are appearing outward of the frame. I tried direction='in' keyword, but it is not working with WCSAxes. My other images created through other software have inward ticks, so I want consistency in all the images. My input code is as follows:
```python
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm 
from astropy.io import fits
from astropy.wcs import WCS
from astropy import units as u
from astropy.visualization.wcsaxes import SphericalCircle

hdu = fits.open('newimage.fits')[0]
imdata = hdu.data
hdr = hdu.header
imdata[0,:,:].shape
wcs = WCS(hdr,relax=False)
w=wcs.celestial
clf()
fig = plt.figure(1)
ax = fig.add_subplot(111, projection=w, aspect='equal')
ax.tick_params(axis='both', which='both', direction='in')

ax.imshow(imdata[0,:,:], cmap='gray_r', vmin=4, vmax=8, norm=LogNorm(), origin='lower',alpha=1.0,aspect=1)
```

**Comment by rlpitts** [comment]
I'm having the same problem. I tried going through ax.coords['ra'].set_ticks() but it has no direction kwarg, and I get "AttributeError: 'CoordinateHelper' object has no attribute 'set_tick_params'" if I replace "set_ticks" with "set_tick_params" or just "tick_params". But what this tells me is that it's taking all information about ticks and axis labels from an Astropy module called CoordinateHelper. All its attributes and their functionality are listed here http://docs.astropy.org/en/stable/api/astropy.visualization.wcsaxes.CoordinateHelper.html Basically, it'll let you format the labels, changing the spacing, hide ticks, etc, but it won't let you change whether the ticks point in or out.

**Comment by astrofrog** [comment]
Try the following:

```
import matplotlib as mpl
mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['ytick.direction'] = 'in'
```

Does this work for you?

**Comment by astrofrog** [comment]
(I will see if we can also add it as a method on CoordinateHelper)

**Comment by astrosumit** [comment]
Thanks @astrofrog for your suggestions. But, none of these methods to control the direction of the ticks is working for me...

**Comment by astrofrog** [comment]
@astronunit - which version of astropy are you using? You can find out with:

```
python -c 'import astropy; print(astropy.__version__)'
```

**Comment by astrosumit** [comment]
I am using Astropy version: 2.0.2

**Comment by astrofrog** [comment]
@astrosunit - can you try running just:

```
from astropy.wcs import WCS

import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['ytick.direction'] = 'in'

wcs = WCS()

ax = plt.subplot(1,1,1, projection=wcs)

ax.tick_params(axis='both', which='both', direction='in')
plt.savefig('test.png')
```

and letting me know if the ``test.png`` file has inward or outward-facing ticks?

**Comment by astrosumit** [comment]
yes... the test.png file has inward facing ticks..

**Comment by astrofrog** [comment]
@astrosumit - ok, but if you put:

```
import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['ytick.direction'] = 'in'
```

before the code to make the plot with WCSAxes, it doesn't work?

**Comment by astrosumit** [comment]
No... It is working for me. I am showing you my image below:
![continuum](https://user-images.githubusercontent.com/32801912/33372537-61714dfc-d524-11e7-9e0b-d816d852f5ba.png)

**Comment by astrofrog** [comment]
@astrosumit - ah, great that it works! I thought you had mentioned higher up that it wasn't working.

**Comment by astrosumit** [comment]
Actually, initially I was using the lines:
mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['ytick.direction'] = 'in'
in between the code, not at the top of the code... That is why it was not working. Now, everything is fine. Thank you very much for giving me your valuable time...

**Comment by rlpitts** [comment]
This worked for me:

```
import matplotlib as mpl
import matplotlib.pyplot as plt
#...
mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['ytick.direction'] = 'in'

ax.tick_params(axis='both', which='both', direction='in')
```
Thank you so much!

**Comment by astrofrog** [comment]
Ok, great!

We should keep this open as we should add this to the docs and also make ``tick_params`` work correctly (currently it has no effect)

**Comment by astrofrog** [comment]
@astrosumit @rlpitts - just FYI you will be able to use ``tick_params`` in Astropy v3.1 once released (very shortly)
