### ISSUE TITLE
Install in development mode fails for subsequent "calls"

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#6739]
Normally the C extensions don't change much and it's rarely useful to call `python setup.py develop` or `python setup.py build_ext --inplace` multiple times. But I'm currently working on changing extensions and I noticed that it fails if I don't remove the `_compiler????.pyd` file before building them:

```
$ python setup.py develop
...
LINK : fatal error LNK1104: Datei "\astropy\_compiler.cp35-win_amd64.pyd" cannot be opened
error: command 'link.exe' failed with exit status 1104
```

If I remove that file and then call it again it works.

**Comment by MSeifert04** [comment]
Probably windows specific. Files that cannot be opened sounds like windows file-protection...

**Comment by drdavella** [comment]
Here's a possibly relevant link (no pun intended) to a [description of the linker error]
(https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1104).

**Comment by pllim** [comment]
Yes, definitely Windows-specific as `pyd` is like `dll` file (https://docs.python.org/3/faq/windows.html#is-a-pyd-file-the-same-as-a-dll).

**Comment by drdavella** [comment]
What version of setuptools are you using? This issue in `setuptools` might be relevant: https://github.com/pypa/setuptools/issues/694

**Comment by MSeifert04** [comment]
I use setuptools 36.5.0 (conda build py35h21a22e4_0). I'll have a look at those links. It seems like it's related to the `setuptools` issue, but that should be fixed, right?

**Comment by embray** [comment]
This is probably obsolete anyways, and not a problem for Astropy to solve.

One possibility was that you were re-compiling but also running the code in an interactive session in a separate window.  In that case it's not possible to remove/replace the in-use DLL and the linker will get a permission error when it attempts to do so.
