### ISSUE TITLE
Feature request: convert longitude values to timezones

### ISSUE THREAD

**Issue by astrojuanlu** [astropy/astropy#676]
In an Astrodynamics course I am following I had the need to do some operations on times and dates: handle time zones, find out sidereal times, position observers according to time measurements, etc. One of the key operations I have to perform is: given the longitude (we usually neglect irregular timezones, hence no need for latitude) of an observer, find out its time zone (also given a particular timezone, find out the longitude of the central meridian). Anyone else thinks Astropy would be suitable for this? I found some web services with this purpose, but having this functionality in this Python package would be ideal. I think it is also available in a package named astral (http://pypi.python.org/pypi/astral/).

EDIT: the `good first issue` refers to the `docs` part of this issue - what would be needed is to find where best to put the example given in https://github.com/astropy/astropy/issues/676#issuecomment-623138161

**Comment by embray** [comment]
As mentioned [here](https://github.com/astropy/astropy/pull/3424/files#r24036086) I think it will be nice to have full timezone support in general.  This specific issue is certainly one interesting use case.  But there are also simpler ones like, it should be possible to specify the timezone that a time is given in, either given manually as a UTC offset in hours, or from a timezone name.  Not sure exactly where the best place is for that to go.  Having pytz as an at least optional requirement seems likely.  There have also been on/off talks about including pytz in the stdlib, though I don't know what the latest news on that is.  It always gets held up in discussions about how to provide updates to the Olson database.

**Comment by embray** [comment]
Ah, the last word on that seems to be that Guido was for the idea, and there *is* a [PEP](https://www.python.org/dev/peps/pep-0431/).  It just hasn't gone anywhere...

**Comment by Juanlu001** [comment]
@embray And its last update was two years ago... Is there anything preventing astropy from asking for pytz as an optional requirement?

**Comment by embray** [comment]
No, I don't think so.  I checked in on the PEP and it seems that the only holdup has been Lennart simply not having time to work on the implementation, and I guess nobody else desperate enough for it to take up the slack.  I don't see any problem, in the meantime, with making pytz an optional dependency for timezone support (or even mandatory if it becomes too much of a pain to keep the feature optional).

**Comment by mhvk** [comment]
We should do this. A first baby step has been taken, with `Time` no longer ignoring time-zone information in `datetime` objects (#3160). Next might be ensuring we can handle timezone information in `iso` times. Beyond that, this may be something that needs to be included in `EarthLocation` (used by `Time` and `Coordinates` internally). Indeed, this may help to keep it fairly non-intrusive and optional.

**Comment by Juanlu001** [comment]
Was this partly addressed in #3217?

**Comment by mhvk** [comment]
@Juanlu001 I think #3217 ensures that some of the pieces are in place, but there will need to be a link to actual timezone information (from the above discussion, via `pytz`, though I have never used this myself). It does need some thought on how to actually implement it, in particular on whether timezone information is something passes on separately to `Time`, part of `EarthLocation`, or something else entirely.

As I noted above, timezone information in `datetime` objects is now used in initialising `Time` objects to convert to `UT`, but it is otherwise discarded.

**Comment by embray** [comment]
For what it's worth, it sounds like Lennart Regebro is trying to get timezone support in the standard library going again (basically as a port of pytz), so anyone who's seriously interested in timezone support may want to help out with that effort too: https://mail.python.org/pipermail/python-dev/2015-April/139071.html

**Comment by Juanlu001** [comment]
PEP 0431 has been withdrawn. https://github.com/python/peps/commit/89a7ad75b74c1451c36c13ede11395d97836f491

**Comment by embray** [comment]
Yeah, I saw some of that discussion.  That doesn't mean timezone support in the stdlib is dead (if nothing else there is still an intent to make timezone db management part of the stdlib).  But that particular approach to handling ambiguous times in the datetime library had to be abandoned.

**Comment by adrn** [comment]
This is actually a nontrivial problem...some timezones have holes.

One possibility is we can add a method to `EarthLocation` that calls [pytzwhere](https://github.com/pegler/pytzwhere) if it is installed. What do people think about that? 

cc @eteq

**Comment by Juanlu001** [comment]
Sounds good to me!

**Comment by adrn** [comment]
Actually, it looks like this package is better maintained: https://github.com/MrMinimal64/timezonefinder

But I wonder what our policy is about adding functionality with an optional, ~semi-maintained dependency. Another option is to add a section to the docs "how to get a timezone from an earthlocation" or something like that. We could then say that `timezonefinder` is one option, and show to use that and `pytz`. 

Any thoughts @astrofrog?

**Comment by adrn** [comment]
And for completeness, as mentioned above, there is also the option of required an internet connection and just querying the Google timezone API

**Comment by mhvk** [comment]
I think this would be nice to have, but not essential (most observations are given in UT anyway). So, maybe first document how to do it with an optional dependence, and then consider whether/how to add it to `EarthLocation`.

**Comment by astrofrog** [comment]
Just out of curiosity, how do these packages deal with daylight savings times in different time zones? (or is the idea that time zones have different names depending on DST?).

**Comment by bsipocz** [comment]
@taldcroft - for CI this shouldn't be an issue once we figure out and set up the caching. On my list, but not near enough to the top to get it done any time soon. However others already expressed their interest of having this in ci-helpers, so I'm hopeful.

**Comment by adrn** [comment]
Going through old issues: I would be ok with adding `.get_timezone()` or `.timezone` to `EarthLocation`, making use of [timezonefinder](https://github.com/MrMinimal64/timezonefinder) and adding it as an optional dependency. The file it depends on is now "only" 40MB :)

**Comment by bsipocz** [comment]
Would the changes in the standard library in 3.9 be any help with this? https://www.python.org/dev/peps/pep-0615

**Comment by mhvk** [comment]
My gut sense is that this only needs documentation - and even that is not very urgent since nobody has posted here how to do it. I worry it would seve few use cases where it would be useful programmatically, and for one-off harder to discover than to just google, especially if the one off implies downloading 40 MB that is already somewhere on my computer anyway. 

Though if it indeed gets in the standard library (which would use system data), I'd be less hesitant.

**Comment by adrn** [comment]
Fine with that too - my comment was mainly to express that if someone else came by and found this and wanted to implement, I wouldn't say no. But, good point, maybe best to just add an example to the docs of how to do something specific, like:
```python
import datetime
import pytz
from timezonefinder import TimezoneFinder
import astropy.coordinates as coord
from astropy.time import Time

target = coord.SkyCoord.from_name('albireo')
loc = coord.EarthLocation.of_site('Apache Point Observatory')
tz_name = TimezoneFinder().timezone_at(lng=loc.lon.degree, 
                                       lat=loc.lat.degree)
tz = pytz.timezone(tz_name)

dt = datetime.datetime(2020, 5, 3, 18, 0, 0, 
                       tzinfo=tz) + datetime.timedelta()
obstime = Time(dt) + np.linspace(0, 12, 256) * u.hour

altaz = coord.AltAz(location=loc, obstime=obstime)
airmass = target.transform_to(altaz).secz
```

**Comment by mhvk** [comment]
Hey, now it's almost there! Adding `docs` and `good first issue`...

**Comment by astrojuanlu** [comment]
[This code excerpt](https://github.com/astropy/astropy/issues/676#issuecomment-623138161) seems to be a bit too short to appear as part of the [astropy.coordinates examples](https://docs.astropy.org/en/stable/generated/examples/index.html#astropy-coordinates) just by itself, so in my view prospective contributors should add detailed explanations, nice plots, and a bit of storytelling as done in the other examples.

On the other hand, as Astropy now requires Python >= 3.6, we should use https://pypi.org/project/backports.zoneinfo/ instead of pytz.

**Comment by astrofrog** [comment]
@astrojuanlu we could even add backports.zoneinfo as a dependency only for Python 3.9 and then use the built-in module already with 3.9.

**Comment by astrojuanlu** [comment]
After reviewing the concerns raised in #11150 about the extra dependencies, I came back to read the original text of the issue (<sub><em>Youth, divine treasure, you pass with no return</em></sub>), which says:

> One of the key operations I have to perform is: given the longitude [...] of an observer, find out its time zone

Given that we decided against adding a `.get_timezone()` to `EarthLocation`, that adding this small example requires two extra dependencies, and that the original request is solved entirely by `timezonefinder`, I am not sure this is worth adding any more.

**Comment by pllim** [comment]
> I am not sure this is worth adding any more

Okay then. I have added the "Close?" label, so this will be closed as won't fix the next time bot runs unless there are objections. Still, it is possible to add it in Astropy Tutorial if desired (maybe should ask the Learn team)?

> *Youth, divine treasure, you pass with no return*

Wut...?

**Comment by astrojuanlu** [comment]
>> _Youth, divine treasure, you pass with no return_

> Wut...?

A free-form translation of [this poem](https://en.wikisource.org/wiki/Page%3ADar%C3%ADo_-_Eleven_Poems.djvu/57) after I realized that I opened this issue 7 years ago when I was a student and had just discovered Astropy 🙈
