### ISSUE TITLE
Deprecate catch_warnings and raises in favor of pytest machinery?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6761]
For example, some `catch_warnings` can be replaced with `pytest.warns` (see https://docs.pytest.org/en/latest/warnings.html#warns). As a result, do we still need warning related functionality in `astropy/tests/helper.py`?

**Comment by mhvk** [comment]
I've wondered too whether pytest has caught up with our custom machinery; it would certainly be nice to be as compliant as possible in our tests.

**Comment by pllim** [comment]
Started an attempt at #10504
