### ISSUE TITLE
Compiling C extensions with --std=c99

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#6762]
It would be nice to use more modern C standards in extension code. Is there any reason we can't update to use `c99`? The compilers on travis at least seem to be old enough that providing this flag explicitly is required.

cc @MSeifert04

**Comment by MSeifert04** [comment]
Just a point to remember: VC still doesn't support _complete_ C99 so we probably can't use all of C99 even if it would work for gcc. 😕

**Comment by embray** [comment]
I believe we can close this.  With one exception (code that uses WCSLIB currently uses `-std=gnu99` we don't explicitly compile with any one specific C standard, opting instead for the default supported by the compiler.

On my laptop's GCC for example, I have `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0` which defaults to `-std=gnu11` for C code, and everything compiles fine.  Setting `-std=c99` works too.  But we don't have a strict decision on this and it may also depend on what external library code is being compiled into extension modules as well.
