### ISSUE TITLE
Add column to fits file without loading fits file into memory?

### ISSUE THREAD

**Issue by cassandra-sh** [astropy/astropy#6764]
In #6649 I brought up an issue when adding columns using the somewhat misleading add_cols() function. I received very helpful assistance, with the recommendation that I use
`fits.BinTableHDU.from_columns(f[1].columns + column)`
(which as an aside must actually be f[1].columns.columns, as f[1].columns returns a ColDefs object)
or
`fits.BinTableHDU.from_columns(f[1].columns.add_col(column))`
These functions seem to only work by loading the columns from f[1] into memory first, and then constructing a while new HDU table there.

I happen to be running astropy on a large enough dataset such that loading all of the columns into memory is actually not practical. When I run this code, my memory spikes as the columns are loaded and the program crashes:

```
  File "/scr/depot0/csh4/py/codes/ver1/corrset/builder.py", line 217, in add_column
    hdu[1] = fits.BinTableHDU.from_columns(hdu[1].columns.add_col(col))

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 126, in from_columns
    data = FITS_rec.from_columns(coldefs, nrows=nrows, fill=fill)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/fitsrec.py", line 330, in from_columns
    data = np.recarray(nrows, dtype=columns.dtype, buf=raw_data).view(cls)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/fitsrec.py", line 244, in __array_finalize__
    self._coldefs = ColDefs(self)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/column.py", line 1189, in __init__
    self._init_from_array(input)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/column.py", line 1249, in _init_from_array
    dim=dim)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/column.py", line 583, in __init__
    array = self._convert_to_valid_data_type(array)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/column.py", line 1100, in _convert_to_valid_data_type
    return np.where(array == 0, ord('F'), ord('T'))

MemoryError
```

Is there a way to modify an HDU table in place, without having to reload the whole thing? Thanks.

p.s. I can make a minimum working example on request, but it would vary from system to system. My current code works for a smaller data set, so I'm not sure an example is necessary. Perhaps a more useful diagnostic would be a timestamped plot of the RAM usage over time, which I can make if someone wants.

Other info: 
conda 4.3.25
astropy 2.0.2
python 3.6.1
numpy 1.13.1
spyder 3.2.1

My OS is Springdale Linux
Release 6.9 (Pisa)
GNOME 2.28.2
Kernel Linux 2.6.32-696.10.1.el6.x86_64
with 16 GB RAM

Small data set that worked just fine: 1.6 GB
Large data set that had problems: 3.7 GB

**Comment by cassandra-sh** [comment]
Here's the memory usage during the code. Marked points are


```
coldef = hdu[1].columns.add_col(col)
```
and
```
hdu[1] = fits.BinTableHDU.from_columns(coldef)
```
and the crash.

![memory_problem_astropy](https://user-images.githubusercontent.com/32488447/31730312-92746c5e-b3ff-11e7-8355-3f38dcb9f8a1.png)

**Comment by adrn** [comment]
👋 Cassandra

I haven't tested this, but one thought is to create a [memory-mapped](https://en.wikipedia.org/wiki/Mmap) file with the right column structure but full of temporary / empty values, and then fill it with the values from the file you actually want. Traveling today but will try to come up with a minimal demo of what I mean. (I'll be back in Peyton on Friday if you want to chat about this)

**Comment by kakirastern** [comment]
Hi, am triaging and would like to check and see if the issues discussed above have been addressed adequately yet (perhaps via private correspondence)? Should this Issue be kept open if not? 

Please advise. Thanks!

**Comment by mhvk** [comment]
@kakirastern - if you cannot find anything about this in the documentation, then I think it is not addressed. It would seem a useful entry for a "tips & tricks" section...

**Comment by kakirastern** [comment]
@mhvk Yup, that's a very good suggestion. Will see if I can follow this up further.

**Comment by saimn** [comment]
There is something similar in the FAQ (http://docs.astropy.org/en/latest/io/fits/appendix/faq.html#how-can-i-create-a-very-large-fits-file-from-scratch), but this is about creating a large file from scratch, and is already not completely obvious for a table. The issue here is more complex, as adding a column means resizing the file and reorganizing the data. So I doubt that we can find a generic solution.

**Comment by kakirastern** [comment]
Yes, in the [How can I create a very large FITS file from scratch?](http://docs.astropy.org/en/latest/io/fits/appendix/faq.html#how-can-i-create-a-very-large-fits-file-from-scratch) section, it is recommended to do the following: 

> For large, heavy-duty table data it might be better too look into using HDF5 through the PyTables library. The Astropy Table interface can provide an abstraction layer between different on-disk table formats as well (for example for converting a table between FITS and HDF5).

> PyTables makes use of Numpy under the hood, and can be used to write binary table data to disk in the same format required by FITS. It is then possible to serialize your table to the FITS format for distribution.

And in the section just above in the FAQ, [How do I open a very large image that won’t fit in memory?, (http://docs.astropy.org/en/latest/io/fits/appendix/faq.html#how-can-i-create-a-very-large-fits-file-from-scratch)), it is recommended to do the following: 

> [astropy.io.fits.open](http://docs.astropy.org/en/latest/io/fits/api/files.html#astropy.io.fits.open) has an option to access the data portion of an HDU by memory mapping using mmap. In Astropy this is used by default.

> What this means is that accessing the data as in the example above only reads portions of the data into memory on demand. For example, if I request just a slice of the image, such as hdul[0].data[100:200], then just rows 100-200 will be read into memory. This happens transparently, as though the entire image were already in memory. This works the same way for tables. For most cases this is your best bet for working with large files.

> To ensure use of memory mapping, just add the memmap=True argument to fits.open. Likewise, using memmap=False will force data to be read entirely into memory.

So what is lacking is maybe an example or two...

**Comment by kakirastern** [comment]
I don't have the data set of the size required to write up an example. So unless someone can supply me with such data, I will have to pass the Issue to someone who has them and is willing to add the example to the FAQ section...
