### ISSUE TITLE
Confusion with obstime: Should it go to the frame or the SkyCoord?

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#6769]
Hi,

I'm implenting coordinate transformations for a cherenkov telescope and I need to define our detector frame and the transformations to AltAz.

I'm confused, what the best practice for `obtime`s is and how to preserve them using a `FunctionTransform`.

Any help or guidance would be appreciated.

**Comment by mhvk** [comment]
Basically, if the frame needs an `obstime`, it should go on the frame. But frames should not carry more information than they need for themselves, so or any transformation to a frame that does not need the `obstime` (like ICRS), the `obstime` gets stored on the `SkyCoord` so that it isn't lost.

**Comment by MaxNoe** [comment]
So if I need obstime and location to convert to a fixed coordinate system like ICRS, it should go with the frame?

**Comment by MaxNoe** [comment]
If you could spare the time, could you maybe look if this makes sense to you?

https://github.com/fact-project/pyfact/blob/obstime/fact/coordinates/camera_frame.py

**Comment by mhvk** [comment]
I think this looks right, but let me cc @eteq and/or @adrn, since they have implemented more frames.
