### ISSUE TITLE
Table with mixed whitespace and tabs worked in 2.0.2, but fails now

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#6770]
The following code works in 2.0.2:
```
from astropy.table import Table
tabtxt = ['1 2\t3','1 2\t3']
Table.read(tabtxt, format='ascii.no_header', names=['a','b','c'])
```
but fails in the current master.
Git bisect lead me to this commit: https://github.com/astropy/astropy/commit/1d14eff6756371f12970b3a6f8939d752cb2b793 but I can't quite figure out why that caused the change.

In any case, I think this is a significant API change which was probably unintentional.

@bsipocz made that commit as part of a larger python2/3 cleanup
@taldcroft

**Comment by MSeifert04** [comment]
One change was 

```
-        if delimiter == r'\s':
-            delimiter = ' '
+        if self.delimiter == r'\s':
+            self.delimiter = ' '
```

Probably because it alters the instance attribute itself.

**Comment by bsipocz** [comment]
Oops, totally unintentional. And we will need to have a test for it to make sure it won't happen again. I'll try to open a fix for it during the weekend.
