### ISSUE TITLE
Can't not writeto complex type arrays

### ISSUE THREAD

**Issue by Hypnus1803** [astropy/astropy#6778]
Hello everyone, I am trying to write a fits file where the data is an array dtype complex64 and I am getting the error: self._bitpix = DTYPE2BITPIX[data.dtype.name]  KeyError: 'complex64'. Can anyone say me if there is a solution. Thanks!!!

**Comment by MSeifert04** [comment]
complex isn't supported by `io.fits` currently and it's not "supported" by the FITS standard (like boolean arrays). If you're just interested in a workaround, you could store real an imaginary part in seperate HDUs and combine them when reading:

```
from astropy.io import fits

def store_complex_array(filename, arr):
    real = arr.real
    imag = arr.imag
    hdul = fits.HDUList([fits.PrimaryHDU(), fits.ImageHDU(real), fits.ImageHDU(imag)])
    hdul.writeto(filename)

def read_complex_array(filename):
    with fits.open(filename) as hdul:
        return hdul[1].data + hdul[2].data * 1j
```

which can be used like this:

```    
import numpy as np

arr = np.array([1,2,3,4]) + 2j
store_complex_array('complex.fits', arr)
read_complex_array('complex.fits')
```

**Comment by saimn** [comment]
Closing as @MSeifert04 gave the reason why it doesn't work and a useful workaround.

**Comment by keflavich** [comment]
Following this up because a colleague asked: while astropy.io.fits doesn't support complex numbers, the FITS standard does specify how you're supposed to story them.  In the [latest standards document](https://fits.gsfc.nasa.gov/fits_standard.html), section 8.5, this text & table:
![image](https://user-images.githubusercontent.com/143715/229236705-e8e54af6-1b0b-4624-8042-29579adb67c3.png)

![image](https://user-images.githubusercontent.com/143715/229236556-2cee54e4-ffdc-4ff3-bbec-23eb1f490c9e.png)
show that you are supposed to add an extra dimension of length 2 and specify its `CTYPE` as `COMPLEX`.

**Comment by pllim** [comment]
@keflavich , do you want me to re-open this or you want to open a new follow-up issue?

**Comment by keflavich** [comment]
I was posting this mostly for information, but it's a bit of an open question: do we want astropy.io.fits to fully implement the FITS standard?  Is there anything in the wild that _does_ implement this part of the standard, or is it one of those specs without even a reference implementation?  I think it's a nice goal to add this, in which case probably reopening is the right approach, but given a typical demand rate of 1 ask/5 years, it's not a high priority, so we could just leave it closed until more people chime in.

**Comment by saimn** [comment]
Interesting but this raises some questions: this is described as a coordinate, using CTYPE, so this should probably be managed by `wcs`. `io.fits` doesn't deal with `CTYPE` currently, adding an exception for this case doesn't seem a good idea. Imagine a 2D array of complex values, where one would want to use also celestial coordinates. 
It also seems that the other "Conventional-coordinate", `STOKES`, is already managed by `wcs`.

**Comment by keflavich** [comment]
Yes, I agree this is mostly a WCS thing.  But if we really wanted to support complex data type IO into/out from numpy complex arrays, we would need some integration with io.fits.
