### ISSUE TITLE
Matplotlib 2.1 breaks Bayesian Blocks histogram

### ISSUE THREAD

**Issue by jakevdp** [astropy/astropy#6786]
You can see this difference between the [stable](http://docs.astropy.org/en/stable/visualization/histogram.html#bayesian-models) and [latest](http://docs.astropy.org/en/latest/visualization/histogram.html#bayesian-models) astropy docs:

With matplotlib 2.0:

![histogram-3](https://user-images.githubusercontent.com/781659/31948972-08a7c1fa-b88d-11e7-8ab3-6727070f7e1d.png)

With matplotlib 2.1:

![histogram-3-1](https://user-images.githubusercontent.com/781659/31948982-0b8038a8-b88d-11e7-85af-264768379b8c.png)

I suspect matplotlib has somehow changed the internals of how the ``normed=True`` machinery works, in a way that only manifests if bins are unequal sized.

**Comment by jakevdp** [comment]
I'll try to investigate whether this is a deliberate change in matplotlib, and how we might adapt the astropy code if necessary.

**Comment by jakevdp** [comment]
Seems to be somehow related to matplotlib introducing the ``density`` argument to replace the ``normed`` argument, due to some changes in how numpy handles these arguments upstream. I'll wait for advice from the matplotlib devs before doing any fix.

**Comment by jakevdp** [comment]
This is definitely a bug in matplotlib 2.1, and a fix is in the works. Shall we close this issue, or wait until the matplotlib fix goes through?

**Comment by pllim** [comment]
IMHO this sounds serious enough of an effect that maybe we should leave it open for now. We wouldn't want `stats` users to be unaware of this until `matplotlib` fix is in. But I shall defer to @bsipocz or other maintainers.

**Comment by bsipocz** [comment]
Yes, we tend to keep issues open until the upstream fix is merged.

**Comment by crawfordsm** [comment]
I'd also suggest to leave it open for the time being until it is fixed upstream, but @jakevdp can you reference the relevant matplotlib issues if possible here?

**Comment by bsipocz** [comment]
@crawfordsm - It's already cros refed above, and following back that to the fixes, it seems that those are done, too. Thanks @jakevdp for the quick and thorough investigating.

**Comment by jakevdp** [comment]
Fixes & regression tests are now merged into the 2.1.x matplotlib branch, and this will be fixed in the next bugfix release (I'm not certain when that is planned).
