### ISSUE TITLE
suggest_backports.py issues

### ISSUE THREAD

**Issue by embray** [astropy/astropy#681]
I'm working now on backporting a lot of the merged PRs for v0.2.x.  It's mostly going smoothly but I need to document a few issues that have cropped up:

1. There was apparently a manual merge of #629, though the script still picked that up as a merged PR. However, it failed to return the correct merge commit for that PR. Instead it returned the SHA for the last commit before the merge.  I'm not sure why that is but I suspect it could have something to do with how github handles the events on manually merged PRs.

2. If one runs the script multiple times between tags it still lists commits that have already been cherry-picked and backported. It's not clever enough to filter out all PRs that have already been backported. In particular, this can happen when commit message comparison fails, because sometimes when cherry-picking there will be a merge conflict, which causes the autogenerated commit message to append a list of files that conflicted.  This part of the commit messages needs to be ignored.

3. Turns out walking commits is even more subtle than I thought; I naively assumed GitHub's API would just automatically list commits in the order that they're shown in GitHub's GUI. But alas we have to write our own code to handle DAG walking.

**Comment by astrofrog** [comment]
Moved to https://github.com/astropy/astropy-tools/issues/10
