### ISSUE TITLE
TimeDelta includes some methods that don't apply

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6828]
It looks like ``TimeDelta`` includes some methods it probably shouldn't. For example ``TimeDelta.now()`` doesn't make sense, and maybe ``TimeDelta.light_travel_time``.

**Comment by mhvk** [comment]
@taldcroft - these methods are inherited directly from `Time`. To avoid this, should we have a `TimeBase` from which both `Time` and `TimeDelta` inherit? It is rather painful in that then `isinstance(..., Time)` will no longer catch a `TimeDelta`. But I'm not sure how else to solve this.

**Comment by Cadair** [comment]
Could some combo of ABCs and subclass hooks fix the `isinstance(..., TIme)` work?

**Comment by taldcroft** [comment]
Good point.  The only question is if we are getting into "perfect is the enemy of good" territory (unless @Cadair can produce the appropriate magic).

**Comment by astrofrog** [comment]
@mhvk - just to check, why should ``isinstance(..., Time)`` catch ``TimeDelta``? Those are two quite different things, so in fact ``isinstance(..., Time)`` returning ``False`` for ``TimeDelta`` seems like a feature to me :)

**Comment by astrofrog** [comment]
Just to clarify my comment, here's what I get with the datetime module:

```python
In [3]: from datetime import datetime

In [5]: dt1 = datetime.now()

In [6]: dt2 = datetime.now()

In [7]: dt2 - dt1
Out[7]: datetime.timedelta(0, 4, 731509)

In [8]: isinstance(dt2 - dt1, datetime)
Out[8]: False

In [9]: isinstance(dt1, datetime)
Out[9]: True
```

There's really no reason ``TimeDelta`` should be as a subclass of ``Time``.

**Comment by mhvk** [comment]
@astrofrog - I agree with you that conceptually they're different and it makes sense to have a `TimeBase`. It is just that this may break code, as it is not how it is implemented...
