### ISSUE TITLE
Vertical image orientation flip in fits2bitmap

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#6841]
I find that `fits2bitmap` results in images that have the output vertical orientation flipped wrt. how the FITS image appears by default in DS9.

@larrybradley - Is this on purpose or by accident? Change orientation to match?

To reproduce:
```
wget http://data.astropy.org/tutorials/FITS-images/HorseHead.fits
fits2bitmap HorseHead.fits
```
With `ds9 HorseHead.fits` the horsie is looking up:
![ds9](https://user-images.githubusercontent.com/852409/32725247-9c5d902c-c874-11e7-912c-8ace7767f9ad.png)

With `open HorseHead.png`, i.e. the `fits2bitmap` output, the horsie is looking down:
![fits2bitmap](https://user-images.githubusercontent.com/852409/32725272-b2ae84a8-c874-11e7-9a07-340f4abfda5d.png)

**Comment by saimn** [comment]
Indeed, the script should use `origin='lower'` to respect the FITS convention.

**Comment by larrybradley** [comment]
That was definitely not intentional.  I'm changing it now.
