### ISSUE TITLE
astropy in casa - issue with numpy

### ISSUE THREAD

**Issue by anneklitsch** [astropy/astropy#6842]
installing astropy in casa 4.7.2 ( pip.main(['install','astropy','--user']) ) gives following error during import: 

ImportError: Numpy version 1.9.0 or later must be installed to use Astropy

installing astropy 1.3.3 in casa 4.7.2 ( pip.main(['install','astropy==1.3.3','--user']) ) gives no error when loading, but the following 2 errors when running astropy.test()

RuntimeError: module compiled against API version 9 but this version of numpy is 7

ImportError: numpy.core.multiarray failed to import

importing numpy in casa imports numpy version 1.7.2

my system path is: 
['', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7', '/home/aklitsch/.local/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/site-packages', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python27.zip', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/plat-linux2', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/lib-tk', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/lib-old', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/lib-dynload', '/home/aklitsch/.local/lib/python2.7/site-packages', '/home/aklitsch/.local/lib/python2.7/site-packages/PIL', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/site-packages/IPython/Extensions', '/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/site-packages', '/home/aklitsch/.casa/ipython']

could there be an issue with my path and the wrong version of numpy being imported?

EDIT: Reformatted the paths for easy reading:
```
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7
/home/aklitsch/.local/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/site-packages
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python27.zip
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/plat-linux2
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/lib-tk
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/lib-old
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/lib-dynload
/home/aklitsch/.local/lib/python2.7/site-packages
/home/aklitsch/.local/lib/python2.7/site-packages/PIL
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/site-packages/IPython/Extensions
/scratch-ssd/opsw/alma/casa-release-4.7.2-el6/lib/python2.7/site-packages
/home/aklitsch/.casa/ipython
```

**Comment by keflavich** [comment]
It looks like astropy's most recent version is not compatible with the old version of numpy distributed with CASA 4.7.2.

One option is to update to CASA 5.1.  The other is to install an older version of astropy, but I'm not sure which versions are compatible with numpy 1.7.2; we don't (yet?) have a chart describing that.

**Comment by pllim** [comment]
The PR that dropped Numpy 1.7 support was #6006 by @mhvk . It was milestoned for Astropy 2.0. So theoretically, Astropy 1.x should still be compatible with Numpy 1.7.

**Comment by bsipocz** [comment]
Whenever a version is dropped, there is an entry in the changelog. I agree that it's as handy as a summary, but is still better than digging up issues ;)

**Comment by pllim** [comment]
Superseded by #7818
