### ISSUE TITLE
scipy.special.erf incompatible with astropy.units.Quantity

### ISSUE THREAD

**Issue by kyleaoman** [astropy/astropy#6843]
Attempting to call scipy.special.erf on a Quantity object yields the following:
```
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import astropy.units as u
>>> from scipy.special import erf
>>> erf(1. * u.dimensionless_unscaled)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Software/users/modules/7/software/anaconda3/5.0.1/lib/python3.6/site-packages/astropy/units/quantity.py", line 621, in __array_ufunc__
    converters, unit = converters_and_unit(function, method, *inputs)
  File "/Software/users/modules/7/software/anaconda3/5.0.1/lib/python3.6/site-packages/astropy/units/quantity_helper.py", line 465, in converters_and_unit
    .format(function.__name__))
TypeError: Unknown ufunc erf.  Please raise issue on https://github.com/astropy/astropy
>>> import astropy
>>> astropy.__version__
'2.0.2'
>>> np.__version__
'1.13.3'
```
It would be nice to support the error function, as it is not especially obscure.

**Comment by pllim** [comment]
Hi. What is your `scipy` version?

**Comment by kyleaoman** [comment]
scipy 0.19.1

**Comment by pllim** [comment]
Thank you. I am unaware that this was ever supported, so I will mark this as "feature request". Perhaps @mhvk could provide more details.

**Comment by kyleaoman** [comment]
Fair enough. I didn't check carefully whether this only applies to erf, or other scipy.special functions. Probably worth supporting them all as they come up from time to time.

**Comment by mhvk** [comment]
Yes, we should support them, and in fact have issues reminding us that we should: #4092 and #6390. I'm going to close this one, as it is a duplicate...  See #4092 for a work-around.  And if you have time to implement this in `quantity_helpers`, that would be great. I once started but was discouraged by the large number of functions, but really we should have this!

**Comment by kyleaoman** [comment]
I might actually have time to do this this week, I'll take a look. When you attempted this before, did you compile a list of functions requiring attention? Would be useful to get me started if you did.

**Comment by mhvk** [comment]
I wish... #6390 has some links. Since all issues raised so far were about `erf`, let's start there....
