### ISSUE TITLE
Observatory site location

### ISSUE THREAD

**Issue by shbhuk** [astropy/astropy#6847]
Hi,
Does the `EarthLocation.of_site(obsname)` support multiple telescopes at a single observatory and the coordinates for that? Is there any plan in the future for that?

Eg. The various CTIO telescopes. Or VLA, or VLT for that matter.

**Comment by bsipocz** [comment]
The observatory sites json file is hosted in the https://github.com/astropy/astropy-data repository. The machinery can support multiple telescopes, the most straightforward way is to use different names.

**Comment by bsipocz** [comment]
@shbhuk - If you are interested in contibuting these coordinates, could you open an issue in the ``astropy-data`` repository? I think it would be useful to have them in that file, but the decision is not mine to make.

**Comment by shbhuk** [comment]
I would recommend this for the CTIO telescopes and Gemini South - 
https://arxiv.org/pdf/1210.1616.pdf
