### ISSUE TITLE
Physical types in units could be improved

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#6864]
For other contexts (specifically in `astropy.coordinates`, where we the `Unit*` representation and differential classes), it would be useful to have a concept of `dimensional_unscaled` units (compare
 to `dimensionless_unscaled`). But it occurred to us that this is actually a physical type! It may be that we want to make the physical types in astropy.units into objects themselves that behave like dimensional but unscaled units that cancel and combine properly.

cc @mhvk

**Comment by adrn** [comment]
A little more context: in coordinates, there is currently a conceptual difference between not passing a distance and not passing a velocity component (e.g., radial velocity). For the former, the representation is perceived as "`Unit*`", meaning the distance is assumed to be `1 dimensionless`. If a radial velocity is not passed, but the velocity is re-represented to cartesian, it interprets the radial velocity as being `0 km/s` (or 0 with specific velocity units). That is, with the above example, if you re-represent the representation to cartesian, it has dimensionless units. But, if you re-represent the velocity to cartesian, the resulting object has scaled velocity units.

I think ultimately we'd really like the unit distance to be something like `1 length(unscaled)` and the radial velocity (in the case where it is not passed) to be `0 velocity(unscaled)` so that the resulting cartesian velocity object becomes `velocity(unscaled)` as a way to be more explicit to the user.

**Comment by adrn** [comment]
Also, BTW, this is related to #6293

**Comment by mhvk** [comment]
This is still a very good idea! Also related to @nstarman's problems with having a catalogue in which only for some objects the distance is known.

**Comment by nstarman** [comment]
That might solve the UnitSpherical case!

**Comment by mhvk** [comment]
Indeed, the "abitrary_length" unit would solve `UnitSpherical` - but one would not be able to mix and match.

**Comment by nstarman** [comment]
@adrn, close?

**Comment by adrn** [comment]
Solved with the new `PhysicalType` machinery!
