### ISSUE TITLE
Start checking for component name-frame attribute overlaps at frame class creation

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#6870]
In some discussion with @adrn out-of-band, we realized a curious corner case in creating `SkyCoord` objects.  Right now, when a `SkyCoord` is created, the initializer looks for keywords that are frame attributes of *any* frame in the frame transform graph, and takes those up as frame attributes.

The problem is: what if there is a name collision between a frame attribute and a *component* name? E.g. if a user defines a new frame class with frame attribute `l`, which collides with the galactic longitude `l`.  Then the user tries to create a `SkyCoord` in the `Galactic` frame, the `l` keyword gets assigned as a possible *frame attribute* rather than the galactic longitude `l`.  The workaround is to instead provide `Representation` objects and never use `l` as a component, but that's ugly and most users wouldn't know enough about the class heirarchies to do that.

@adrn's suggestion (which I think I agree with) is to just have the metaclass for frame classes to check if there are name collisions and raise an error if they happen.  That way we're never in this situation, at the cost that if someone really *does* have a good reason for using the frame attribute name `l`, they are stuck.

**Comment by mhvk** [comment]
Is this a problem beyond the `SkyCoord` initializer? If not, my sense would be that we should solve it there, not with a blanket prohibition.

**Comment by eteq** [comment]
@mhvk - just to close the look on this: yes, it could still be a problem even at the frame-level, because component names and frame attributes are both defined at the frame level, not the `SkyCoord` level.

**Comment by eteq** [comment]
Oh, that is to say, it's *much worse* for `SkyCoord` because a `SkyCoord` can have *any* of the frame attributes, but in generally I'd say still will be generally confusing if there are collisions between frame attributes (e.g. `coord.ra` would be very confusing to see if "ra" here is a frame attribute, even if it isn't technically wrong for an individual frame)

**Comment by adrn** [comment]
And hence #6871!
