### ISSUE TITLE
instructions for updating from Astropy 1.x to Astropy 2.x in Anaconda

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astropy#6874]
I am using conda on OSX and when I follow the conda installation instructions here it seems to 
not update to 2 but leaves me with 1.x. See below.

I think there is some missing magic incantation needed in the docs?

http://docs.astropy.org/en/stable/install.html#anaconda-python-distribution

```
rgm@Richards-MBP-2(~){126}> conda update astropy
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/rgm/anaconda2:
#
astropy                   1.2.1               np111py27_0
```

**Comment by richardgmcmahon** [comment]
On further investigation I tried:

conda install astropy=2.0
Fetching package metadata .................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - astropy 2.0*
  - lsst-sims-utils -> astropy >=1.1.2,<1.3

Maybe the update is being blocked.

OK I had to:
conda uninstall lsst-sims-utils
conda uninstall lsst-astropy-eups-configs

Then conda update astropy worked:

rgm@Richards-MBP-2(~){135}> conda update astropy
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /Users/rgm/anaconda2:

The following packages will be UPDATED:

    astropy: 1.2.1-np111py27_0 --> 2.0.2-py27h87cc2bd_4

**Comment by richardgmcmahon** [comment]
Still it might be useful to add something like if conda update does not get the newest version try conda install astropy=2.0 since the blocker than becomes visible. Maybe there was a verbose mode for conda update astropy that I could have tried.

**Comment by bsipocz** [comment]
I wonder whether the lsst package has pinned the astropy version into a conda pin file (it's in the environment's ``conda-meta/`` directory, in your case `/`Users/rgm/anaconda2/conda-meta/pinned``) or they have just changed the behaviour of the conda version resolver as in the past it didn't use to take into account downstream requirements.

There is indeed a ``--verbose`` option for ``conda update`` that may hint on this issue.

To skip all dependency checking, and install the very latest version, you can use the ``--force`` option for ``conda update``.

**Comment by astrofrog** [comment]
I guess we could create a 'known issue' for 'conda won't update astropy to the latest version' and just say to specify the version manually to show conflict info.

**Comment by bsipocz** [comment]
This is normal conda behaviour that does affect all conda packages not at all astropy specific. I suggest to close this issue.

If you disagree please open a PR instead with the proposed piece of documentation.
