### ISSUE TITLE
HTML download of docs yields very old version

### ISSUE THREAD

**Issue by bwinkel** [astropy/astropy#6886]
When I use the little button (lower right corner) on RTD to download the (zipped) version of the docs, it delivers a very old version (v1.1.dev14587 when doing it on "latest" and 1.0.4 for "stable"). The same is true for the PDF (same version numbers), but I figure that the PDF rendering was stopped on purpose. I usually look into the manual online, but was asked by a friend who searched for something to use on his machine locally.

**Comment by bsipocz** [comment]
I suspect that removing the downloadable html is an unwanted side effect of https://github.com/astropy/astropy/issues/5677#issuecomment-271132773, and providing the zip shouldn't really take up much build time as the html files are generated anyway. 

However it may be an upstream RTD issue.

**Comment by bsipocz** [comment]
We have removed the downloads, so this issue I supposed is worked around.
