### ISSUE TITLE
Header.keys() method does not give keywords of header

### ISSUE THREAD

**Issue by ysBach** [astropy/astropy#6898]
I want to get all the header keywords as a single python list.

The [documentation](http://docs.astropy.org/en/stable/io/fits/index.html) describes
> To get a list of all keywords, use the Header.keys() method just as you would with a dict:
>```
>>>> prihdr.keys()
>['SIMPLE', 'BITPIX', 'NAXIS', ...]
>```

But the following code does not give the expected results:

```python
from astropy.io import fits
from astropy.utils.data import download_file
import astropy
print(astropy.__version__)
# 2.0.2

fits_file = download_file('http://data.astropy.org/tutorials/FITS-Header/input_file.fits',
                          cache=True)
testhdr = fits.getheader(fits_file, 0)

print(type(testhdr))
# astropy.io.fits.header.Header

testhdr.keys()
# <generator object Header.__iter__ at 0x7f9715b343b8>
```

The header has following contents:
```
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  100                                                  
NAXIS2  =                  100                                                  
EXTEND  =                    T                                                  
OBJECT  = 'KITTEN  '    
```

**Comment by saimn** [comment]
As stated in the documentation, it follows the dict interface which is different between Python 2 and 3 (*use the Header.keys() method just as you would with a dict*). On Python 2 `.keys()` returns a list (and the documentation was written at that time), but on Python 3 `.keys()` returns a generator. If you want a list you can simply call `list(prihdr.keys())`, and the documentation should be updated to use this as well:
```
>>> list(prihdr.keys())
['SIMPLE', 'BITPIX', 'NAXIS', ...]
```

**Comment by pllim** [comment]
The documentation is already updated in dev -- http://docs.astropy.org/en/latest/io/fits/index.html

Can we close this then?

**Comment by ysBach** [comment]
@saimn Oh! That's it! Thanks :)
Closing it.

**Comment by saimn** [comment]
Ah indeed I forgot to check the master branch documentation, thanks @pllim !
