### ISSUE TITLE
Example of re-stuffing updated wcs into fits file in cutout tools doc

### ISSUE THREAD

**Issue by SaOgaz** [astropy/astropy#6911]
Hi,

I think it would be really useful to have an example added in  [this doc](http://docs.astropy.org/en/latest/nddata/utils.html) of pulling a fits file, doing the cutout with wcs, and restuffing the updated cutout and wcs back into the fits file.

**Comment by SaraOgaz** [comment]
Or maybe it would be more appropriate to live [here] (http://docs.astropy.org/en/latest/wcs/index.html)? There's a section for loading wcs information from a fits file, but nothing on putting that wcs back into the fits file to update.

**Comment by Vital-Fernandez** [comment]
I would like to write an example such as the one you are asking. This is what I did:

```
import numpy as np
from matplotlib import pyplot as plt
from astropy.io import fits
from astropy.wcs import WCS
from astropy.utils.data import download_file
from astropy.nddata import Cutout2D
from astropy import coordinates, units as u

#Import Horsehead Nebula example image from the tutorials database
fits_file = 'http://data.astropy.org/tutorials/FITS-images/HorseHead.fits'
image_file = download_file(fits_file, cache=False)

# Load the image and the world coordinates from the header
hdu = fits.open(image_file)[0]
wcs = WCS(hdu.header)

# Get Horsehead Nebula coordinates
horsehead_coord = coordinates.SkyCoord.from_name('Horsehead Nebula')

# Defining new image pixel size
sizeTrim = (400*u.pixel, 400*u.pixel)

# Making the cutout using the wcs
cutout = Cutout2D(hdu.data, position=horsehead_coord, size=sizeTrim, wcs=wcs)

# Update image data from the cutout
hdu.data = cutout.data

# Update the WCS from the cutout
hdu.header.update(cutout.wcs.to_header())

# Replace original image by the new "trimmed" version
hdu.writeto(image_file, overwrite=True)

# Load the new image
hdu = fits.open(image_file)[0]
wcs = WCS(hdu.header)

# Plot the image
fig = plt.figure()
fig.add_subplot(111, projection=wcs)
plt.imshow(wcs.data, origin='lower', cmap=plt.cm.viridis)
plt.xlabel('RA')
plt.ylabel('Dec')
plt.show()
```
The new image is saved and it replaces the old one with no issues. However, once I try to load the new wcs, I get this error:

```
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
WARNING: FITSFixedWarning: 'celfix' made the change 'Invalid parameter value'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "wcs_testing.py", line 38, in <module>
    wcs = WCS(hdu.header)
  File "python2.7/site-packages/astropy/wcs/wcs.py", line 504, in __init__
    self.wcs.set()
ValueError: ERROR 5 in wcsset() at line 2213 of file cextern/wcslib/C/wcs.c:
Invalid parameter value.
ERROR 4 in linset() at line 665 of file cextern/wcslib/C/lin.c:
Failed to initialize distortion functions.
ERROR 3 in disset() at line 977 of file cextern/wcslib/C/dis.c:
Unrecognized/unimplemented distortion function: TPD  
```

Sorry this is my first time trying to contribute to another project :)

**Comment by bsipocz** [comment]
@Vital-Fernandez - Thanks for your interest.
For contributions please read the development guidelines: http://docs.astropy.org/en/latest/development/workflow/development_workflow.html#how-to-make-a-code-contribution

One of the issues can be that you don't have the latest development version. First please update it (note that astropy now requires python 3.5 or newer, it won't work with python 2.7).
Also, if you come up with a solution or suggestion like the one above, please open a pull request with it rather than pasting code into a comment. That will allow the maintainers to review and comment on it.

**Comment by larrybradley** [comment]
Added in #7328.
