### ISSUE TITLE
Re-export 'convolution-example.png' as PDF with machine readable text

### ISSUE THREAD

**Issue by sladen** [astropy/astropy#6917]
Currently 'figures/convolution-example.png' contains pre-rendered text.  This could probably be easily re-exported as PDF containing bitmaps + machine readable/renderable text.

(Unfortunately this also appears to be the only image without source code to regenerate it, which possibly explains why this has not been done already).

**Comment by bsipocz** [comment]
Wrong repo, presumably you refer to the figure in the paper here.

**Comment by sladen** [comment]
This issue was moved to astropy/astropy-v2.0-paper#48
