### ISSUE TITLE
Affiliated package test failures against v2.0.2 release

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#6919]
The root cause of this issue has already been addressed in https://github.com/astropy/astropy/pull/6605 and has been backported to `v2.0.x` in #6609. However, these fixes have not yet made it to stable releases.

The problem is that now the default version of `pytest` distributed by `conda` includes `hypothesis` as a dependency. This means that testing against the stable release version will cause doctests to fail until the release of `v2.0.3`.

**Comment by bsipocz** [comment]
Reminder for self: before doing 2.0.3, make sure to test a few affiliates, 1) with ``pytest-astropy`` installed, 2) using the latest pytest

**Comment by mhvk** [comment]
Just in case other people with packages based on the current affiliated templates look here: the trick may be to add `PYTEST_VERSION=3.2` to any test that involves astropy LTS for now. I guess is the more reason to try to ensure we make minimal modifications to pytest...

**Comment by bsipocz** [comment]
@mhvk - This will be worked around very soon in ci-helpers, so no need to modify the travis config from the affiliate side (however locally, yes, the workaround may be to stick with an older pytest)

**Comment by mhvk** [comment]
OK, that's great. I'll revert my fix once ci-helpers is updated (is there a way to know this is happening? I think I signed up for an affiliated mailing list, but don't think I ever get messages...)

**Comment by bsipocz** [comment]
atm the discussion is on slack. The regression started this morning when the previous pytest version limitation was lifted, this second issue was an independent one that got under the radar until now.

**Comment by mhvk** [comment]
Ah, I hadn't appreciated the regression was *that* recent! I'm afraid I cannot handle slack; e-mail is distracting enough (and the e-mails from slack when I'm mentioned are the worst of all - totally non-informative, and no way to even get to the point of the discussion where I'm mentioned).

**Comment by bsipocz** [comment]
#6918 has fixed this.
