### ISSUE TITLE
Running tests directly from pytest is still broken on v2.0.x

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#6936]
The problem with running tests directly with the `pytest` command was reported in #6424. It was fixed for 3.0 as a consequence of #6606.

However, this still doesn't work for the `v2.0.x` series, even though we have backported some testing-related changes. I don't think this is worth addressing at this point, but I am making an issue here as a record for posterity. Feel free to close.

cc @bsipocz

**Comment by pllim** [comment]
I agree that this is not worth pursuing.
