### ISSUE TITLE
tabledump is broken when the output file is not specified

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#6937]
It seems that previously an HDU could access to its parent HDUList with a `_HDUList__file` attribute, and this was used to get the `filename`. I think the simplest solution would be to make the output file mandatory (`datafile`).

```
In [3]: fits.tabledump('astropy/io/fits/tests/data/tb.fits')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-c48651aaf53f> in <module>()
----> 1 fits.tabledump('astropy/io/fits/tests/data/tb.fits')

~/dev/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    485                         # one with the name of the new argument to the function
    486                         kwargs[new_name[i]] = value
--> 487             return function(*args, **kwargs)
    488 
    489         return wrapper

~/dev/astropy/astropy/io/fits/convenience.py in tabledump(filename, datafile, cdfile, hfile, ext, overwrite)
    888             # TODO: Really need to provide a better way to access the name of
    889             # any files underlying an HDU
--> 890             root, tail = os.path.splitext(f._HDUList__file.name)
    891             datafile = root + '_' + repr(ext) + '.txt'
    892 

AttributeError: 'HDUList' object has no attribute '_HDUList__file'
```

**Comment by ricardogando** [comment]
Hi @saimn, 
Using `ext=1`, 
`root, tail = os.path.splitext(f._file.name)`
produces `datafile` as
> 'astropy/io/fits/tests/data/tb_1.txt'

Is that the expected output?
If I understand correctly, you could have different filenames under the HDUlist? 
That is why one does not use the input filename as a reference for output? 
Thanks,
Ricardo

**Comment by saimn** [comment]
Oh indeed, I should have look at the code yesterday but it was too late :sleeping: 
So my guess above was inexact, `f` is the HDUList object. And the issue is probably that the current `_file` attribute was previously a private one `__file` which would explain the use `_HDUList__file` due to the name mangling.

So the fix is just to replace with `_file`. And to add a unit test with it :wink: 

>  If I understand correctly, you could have different filenames under the HDUlist? That is why one does not use the input filename as a reference for output?

There is only one input filename, `HDUlist._file.name`, but as you can have multiple table HDUs you have to choose which one to dump, with `ext`, and either give an output name (`datafile`) or get a file with `{input_name}_{ext}.txt`.

**Comment by vermashresth** [comment]
@saimn I am a beginner. Can I take up this issue?

**Comment by saimn** [comment]
@vermashresth - maybe check with @ricardogando if he started to work it, but otherwise it fine by me.

**Comment by ricardogando** [comment]
@vermashresth I am going through this issue with a student and would like to close the astropy contribution cycle with him. Unfortunately, I could not finish it during office hours last week. Would you mind taking another issue? I certainly do not claim ownership over issues and if you have or would to like to work on it, please go ahead.

**Comment by vermashresth** [comment]
@ricardogando Sure! No problem. I will try some other issue.

**Comment by macicco** [comment]
Hi everyone,

I am working on issue #7015 , and I repeated the tabledump testing, and the same error from this issue ocurred again! Noting that I did the astropy fetch and getting the latest version, and I am working on ENV astropy. 

`~/anaconda3/envs/ENV/lib/python3.6/site-packages/astropy/io/fits/convenience.py in tabledump(filename, datafile, cdfile, hfile, ext, overwrite)
    877             # TODO: Really need to provide a better way to access the name of
    878             # any files underlying an HDU
--> 879             root, tail = os.path.splitext(f._HDUList__file.name)
    880             datafile = root + '_' + repr(ext) + '.txt'
    881 

AttributeError: 'HDUList' object has no attribute '_HDUList__file'


`

**Comment by pllim** [comment]
@macicco , just to be sure, what is your `astropy.__version__`?

**Comment by macicco** [comment]
is that:

'astropy.version
Out[15]: <module 'astropy.version' from '/home/decicco/anaconda3/envs/ENV/lib/python3.6/site-packages/astropy/version.py'>'

in fact, is not dev version...

**Comment by macicco** [comment]
I did again all steps for environment develop, and I installed the astropy version: '3.0.dev20734'
I am under my-own-astropy and again after running the code : 



fits.tabledump('/home/decicco/Documents/GitHub/astropy/astropy/io/fits/tests/data/tb.fits')

~/Documents/GitHub/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    485                         # one with the name of the new argument to the function
    486                         kwargs[new_name[i]] = value
--> 487             return function(*args, **kwargs)
    488 
    489         return wrapper

~/Documents/GitHub/astropy/astropy/io/fits/convenience.py in tabledump(filename, datafile, cdfile, hfile, ext, overwrite)
    888             # TODO: Really need to provide a better way to access the name of
    889             # any files underlying an HDU
--> 890             root, tail = os.path.splitext(f._HDUList__file.name)
    891             datafile = root + '_' + repr(ext) + '.txt'
    892 

AttributeError: 'HDUList' object has no attribute '_HDUList__file'

In [6]: astropy.__version__
Out[6]: '3.0.dev20734'

**Comment by saimn** [comment]
@macicco - It seems that your master branch is not synchronized with astropy's master branch.

**Comment by macicco** [comment]
How do I do that?

**Comment by macicco** [comment]
'
decicco@catatau:~/Documents/GitHub/astropy$ git remote
astropy
macicco
decicco@catatau:~/Documents/GitHub/astropy$ git fetch --all
Fetching macicco
Fetching astropy
decicco@catatau:~/Documents/GitHub/astropy$ git branch -a
  bugfix-for-issue-7015
  bugfix-for-issue-7164
  bugfix-for-issuse-6937
  buxfix-for-issue-6760
  master
* my-own-astropy
  remotes/astropy/LTS
  remotes/astropy/lts
  remotes/astropy/master
  remotes/astropy/stable
  remotes/astropy/v0.1.x
  remotes/astropy/v0.2.x
  remotes/astropy/v0.3.x
  remotes/astropy/v0.4.x
  remotes/astropy/v1.0.x
  remotes/astropy/v1.1.x
  remotes/astropy/v1.2.x
  remotes/astropy/v1.3.x
  remotes/astropy/v2.0.x
  remotes/astropy/v3.0.x
  remotes/macicco/HEAD -> macicco/master
  remotes/macicco/bugfix-for-issue-7015
  remotes/macicco/bugfix-for-issue-7164
  remotes/macicco/bugfix-for-issuse-6937
  remotes/macicco/buxfix-for-issue-6760
  remotes/macicco/master
  remotes/macicco/stable
  remotes/macicco/v0.1.x
  remotes/macicco/v0.2.x
  remotes/macicco/v0.3.x
  remotes/macicco/v0.4.x
  remotes/macicco/v1.0.x
  remotes/macicco/v1.1.x
  remotes/macicco/v1.2.x
  remotes/macicco/v1.3.x
  remotes/macicco/v2.0.x
'

**Comment by macicco** [comment]
and :
' decicco@catatau:~/Documents/GitHub/astropy$ git remote -v
astropy	git://github.com/astropy/astropy.git (fetch)
astropy	git://github.com/astropy/astropy.git (push)
macicco	git@github.com:macicco/astropy.git (fetch)
macicco	git@github.com:macicco/astropy.git (push)
decicco@catatau:~/Documents/GitHub/astropy$ 

 '

**Comment by bsipocz** [comment]
@macicco - Please have a look at this page, it summarizes the major points: http://docs.astropy.org/en/stable/development/workflow/development_workflow.html

**Comment by macicco** [comment]
Yes I did, I followed all the steps, and I changed form /master to my -own-astropy, as suggested.

**Comment by pllim** [comment]
@macicco , to do the actual sync-ing, if you haven't already, in your desired branch:
```
git fetch astropy master
git rebase astropy/master
```

You must repeat this for each outdated branch, if you have multiple active ones that you are working on.

**Comment by macicco** [comment]
Done!

:~/Documents/GitHub/astropy$ git fetch astropy master
From git://github.com/astropy/astropy
 * branch            master     -> FETCH_HEAD
:~/Documents/GitHub/astropy$ git rebase  astropy/master
First, rewinding head to replay your work on top of it...
Fast-forwarded my-own-astropy to astropy/master.
decicco@catatau:~/Documents/GitHub/astropy$

**Comment by macicco** [comment]
YEAH ! No error !!
