### ISSUE TITLE
SigmaClip no more present

### ISSUE THREAD

**Issue by stefanocovino** [astropy/astropy#6939]
Apparently one of the examples of the documentation does not work anymore:
```
from astropy import stats

data = [1, 5, 6, 8, 100, 5, 3, 2]
stats.sigma_clip(data, sigma=2, iters=5)  
```
is fine.
While:
```
sigclip = stats.SigmaClip(sigma=2, iters=5)
```
doesn't.

**Comment by saimn** [comment]
Can you confirm the issue is with 2.0.2 ? (As you mentioned in https://github.com/astropy/photutils/issues/633)
It works for me on master.

**Comment by saimn** [comment]
And works for me as well on a fresh venv with Astropy 2.0.2
Are you sure you are importing the correct astropy (if you have multiple installations) ?

**Comment by stefanocovino** [comment]
> Il giorno 07 dic 2017, alle ore 10:59, Simon Conseil <notifications@github.com> ha scritto:
> 
> And works for me as well on a fresh venv with Astropy 2.0.2
> Are you sure you are importing the correct astropy (if you have multiple installations) ?
> 
> 

Hi,

indeed it is weird.

Instaling astropy with conda everything works fine. If I do the same installing the package via, e.g., easy_install then I see the problem. And it does not seem to be related to the astropy version. It is the same if I try with the old 1.3 version, for instance.

	Stefano

**Comment by larrybradley** [comment]
The `SigmaClip` class was introduced in `astropy 2.0`.  It did not exist in `astropy 1.3`.  Please check your `astropy` version within python:

```
>>> import astropy
>>> print(astropy.__version__)
```

**Comment by larrybradley** [comment]
@stefanocovino  This appears to be an installation mismatch issue.  Please reopen if you are still having problems.
