### ISSUE TITLE
Open files test failure on latest build

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#6942]
The latest build on `master` has a [test failure](https://travis-ci.org/astropy/astropy/jobs/313192636) from `pytest-openfiles`.

I just released a new version `pytest-astropy`. While there haven't been any substantive changes to `pytest-openfiles` since the last release, `pytest-astropy` now includes `pytest-mpl` as a dependency, which includes `matplotlib` as  a dependency.

The test matrix does not explicitly install `matplotlib` during the `--open-files` test run, so I think this test failure is real but it has never been exposed before. It may be that we just need a way to suppress it though if it is not actually coming from Astropy itself.

**Comment by pllim** [comment]
Maybe we just need to call `buff.close()` in https://github.com/astropy/astropy/blob/master/astropy/visualization/tests/test_units.py#L21 ?

**Comment by pllim** [comment]
Update: `buff.close()` has no effect. Sorry for the noise!

**Comment by pllim** [comment]
Removing `pytest-mpl` from `pytest-astropy` fixed the problem.
