### ISSUE TITLE
Make units be consistent with versioned constants

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#6948]
This motivation for this issue is fixing a subtle but important inconsistency that can now appear because constants are versioned (new feature in v2.0).  The basic problem is that some units are effectively tied to constants.  For example `units.solMass` exists, but so does `constants.M_sun`.  Right now with the default units they are consistent, but *if* someone uses the constant versioning machinery to update e.g. M_sun, they become inconsistent.

There are a couple possible fixes here:
* Tie the units to the constant values so that if a particular constant is set as the "current" version, the unit is assumed to have that value (I think that is more "right" but probably requires subtle and/or major changes to `units`).
* Make unit conversion factors versionable, and provide helper functions or just instructions for how to sync them up (possibly easier, but means manual intervention is required).

**Comment by mhvk** [comment]
This is somewhat tricky, as unit definitions cascade down - one would effectively need the ability to reload `units` (or whole of astropy?). And of course even before that to reload `constants` itself. It may be easier to have a configuration item that states which constants are loaded by default (now: `codata2014`, `iau2015`).

**Comment by stargaser** [comment]
I am going to try the suggestion from @mhvk to make a configuration item for the versions of constants that are loaded when `units` or `constants` are first imported. Shooting for 3.2 which means having a PR open by April 5th, 2019.
