### ISSUE TITLE
Fitters are missing documentation on __call__

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6958]
See here:

<img width="720" alt="screen shot 2017-12-09 at 16 07 35" src="https://user-images.githubusercontent.com/314716/33797205-d5a8c680-dcfb-11e7-867b-444e46dea72f.png">

``__call__`` does have a docstring. I think the ``@fitter_unit_support`` decorator needs to be adapted to use ``wraps`` from astropy not from functools as I think the one from ``astropy.utils`` preserves docstrings.

**Comment by MSeifert04** [comment]
I thought I fixed that... I don't remember the PR anymore but the latest docs seem fine: http://docs.astropy.org/en/latest/api/astropy.modeling.fitting.SLSQPLSQFitter.html#astropy.modeling.fitting.SLSQPLSQFitter

**Comment by MSeifert04** [comment]
Ah, here it is: https://github.com/astropy/astropy/pull/6675

**Comment by astrofrog** [comment]
Ah I was looking at the stable docs. Thanks!
