### ISSUE TITLE
Speed up testing

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6961]
A major hindrance while trying to get astropy tests to work with numpy 1.14 has been how *slow* our test suite is. I picked out one test in nddata where an 1e8 array was created for no reason at all, but it would be good to go through tests in the different modules and check whether they really need to be so slow, in particular checking whether one really needs the number of elements chosen.

EDIT: another major hindrance is how long it takes for tests even to start. Numpy is *far* faster. Is this really needed?

**Comment by saimn** [comment]
Agreed, I even started trying to find the slow tests some time ago (and I think I have a branch somewhere), and I added the `--durations` option for pytest (#6294) but it seems to have disappeared.

**Comment by bsipocz** [comment]
>and I added the --durations option for pytest (#6294) but it seems to have disappeared.

@saimn - That was an unintentional side effect of #6246, I'm opening a PR to add it back.

**Comment by saimn** [comment]
Thanks to @bsipocz, with #6963 the slowest tests are here:
https://travis-ci.org/astropy/astropy/jobs/314336725#L5015

**Comment by astrofrog** [comment]
> EDIT: another major hindrance is how long it takes for tests even to start. Numpy is far faster. Is this really needed?

The issue here is that we need to build and install astropy to a temporary directory every time the tests are run. You can get better performance by doing:

```
python setup.py build_ext --inplace
pytest astropy
```

**Comment by drdavella** [comment]
It's worth mentioning that if all of your dependencies are installed to your working environment, and if you don't mind rebuilding any extensions manually, you can now run tests directly from `pytest`, which should eliminate a lot of the overhead seen here.

**Comment by bsipocz** [comment]
This may be naturally be addressed if we start moving to azure, but in the meantime I'm removing the milestone.

**Comment by mhvk** [comment]
This issue is rather generic, so even though it is arguably time again to look at the slowest tests and see if they really need to be that slow, I'm closing....
