### ISSUE TITLE
sidereal_time IERSError is breaking pytest

### ISSUE THREAD

**Issue by Joshuaalbert** [astropy/astropy#6972]
In pull request #6882 I implement a feature that requires Local Sidereal Time, which I create using its definition as the local meridean in celestial frame using an AltAz to define the zenith then transforming to ICRS:
```
lst = AltAz(alt=90*u.deg,az=0*u.deg,location=uvw_frame.location,obstime=uvw_frame.obstime).transform_to(ICRS).ra
```
This works fine, however @eteq noted that I could use the `Time.sidereal_time` function.

After switching to,

```
lst = uvw_frame.obstime.sidereal_time('mean',longitude=lon).to(u.radian).value
```

Pytest is failing at that line with the below error.
```
IERSRangeError: (some) times are outside of range covered by IERS table.
```
It happens in function `_check_interpolate_indices(self, indices_orig, indices_clipped, max_input_mjd)`

**However, this works in the shell:**
```
time = at.Time("2017-01-26T17:07:00.000",format='isot',scale='utc')
lst = time.sidereal_time('mean',10*u.deg)
```

The only difference is this line, so could there be an issue with pytest handling warnings?

**Comment by mhvk** [comment]
@Joshuaalbert - yes, by default, `Time` warns if one is outside of range. One can either catch those warnings and decide to ignore them, or, easier and in my opinion totally OK for a test, use a time in the test that is safely within the range for which astropy comes with IERS data (say, somewhere in 2005 or so).

**Comment by Joshuaalbert** [comment]
works
