### ISSUE TITLE
Solar motion default

### ISSUE THREAD

**Issue by balbinot** [astropy/astropy#6973]
On the "what is new"  page for 2.0

http://docs.astropy.org/en/stable/whatsnew/2.0.html

There is an example showing conversion of ICRS to Galactocentric (with velocities). The solar motion is set to 

`v_sun = coord.CartesianDifferential([10, 244, 7.])*u.km/u.s`

`astropy.coordinates.Galactocentric` uses a left-handed convention (x increases from the galactic centre to the Sun). In that case the U component of v_sun should be negative 

`v_sun = coord.CartesianDifferential([-10, 244, 7.])*u.km/u.s`

and the resulting `v_x` is equal to `-U`. The example is not wrong, but is its misleading to someone trying to compute Galactic UVW from ICRS coordinates.

I noticed this while comparing UVW from galpy with UVW from astropy.

**Comment by adrn** [comment]
`Galactocentric` is right-handed: x increases from the Sun to the Galactic center, y increases in the direction of rotation. The Sun sits at `[-galcen_distance, 0, 0]` (where by default `galcen_distance = 8.3 kpc`. See below:

```python
import astropy.coordinates as coord
import astropy.units as u
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 8, 8) * u.kpc
c = coord.SkyCoord(u=x, v=0*u.kpc, w=0*u.kpc, 
                   representation='cartesian',
                   frame='galactic')
gc = c.transform_to(coord.Galactocentric)

print(c)
print(gc)
```
returns:
```
[ 0.          1.14285714  2.28571429  3.42857143  4.57142857  5.71428571
  6.85714286  8.        ] kpc
[-8.29995608 -7.15710498 -6.01425388 -4.87140278 -3.72855168 -2.58570058
 -1.44284948 -0.29999838] kpc
```

**Comment by balbinot** [comment]
Ok I switched it up, sorry. No issue here! ;)

**Comment by adrn** [comment]
No worries! Is there anywhere we could document this better that would have helped you? We're always looking for ways to make this clearer.

**Comment by balbinot** [comment]
ICRS accepts uvw as input, it would make sense as representing it in that way on the output. Since it is not I had the suspicion that v_x, v_y, v_z != U, V, W.

All checks out now, the confusion actually started with galpy which uses left-handed and inputs the solar motion as -U, V, W.
