### ISSUE TITLE
Add `git submodule update --init --recursive` to "Obtaining the source packages" of docs/install.rst

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy#6975]
This is a spin-off from #4685, in particular [this comment](https://github.com/astropy/astropy/issues/4685#issuecomment-351160249)

Whilst the `astropy_helpers` folder/submodule is fetched when built (via `ah_boostrap.py`) I believe it should be explicitly stated within the install docs as a step to obtaining the _complete_ source package from github.

**Comment by bsipocz** [comment]
The submodule is dead, so this is not relevant any more.
