### ISSUE TITLE
tests for Kuiper statistics

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#6979]
From @mhvk on #6565:

@crawfordsm - the test here is one of the slowest of our suite. Does it really make sense to repeatedly test that the statistics produced by the routine are correct? Instead of running a routine 30000 times, I would think it makes more sense to check that for one or two realizations you get exactly the right answer (or, if that is not available, that the answer doesn't change from the routine that did have the right statistics, which we have now tested...). Given the same answer, the statistics cannot change, after all.

**Comment by crawfordsm** [comment]
Fully agree that this should be taken care of and will look into speeding up these.  The tests probably are overly specified.    

Do we have a good link to how to test the speed of the tests?

**Comment by bsipocz** [comment]
I'm not aware that pytest offers anything else natively than listing the N slowest test with ``-a "--durations=N"``.
