### ISSUE TITLE
Inconsistent results for GCRS to ITRS transformation

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#6986]
I am getting very different results for a GCRS to ITRS transformation depending upon whether or not I pass the default `obstime` value to the ITRS initializer. Here's an example.

First some imports...

```python
>>> from astropy.coordinates import GCRS, ITRS, SkyCoord
>>> from astropy.time import Time
>>> from astropy import units as u
```

Then I create a GCRS  sky coordinate...

```!python
>>> t = Time('2017-08-10')
>>> gcrs = GCRS(obstime=t)
>>> c = SkyCoord(200*u.deg, 10*u.deg, frame=gcrs)
```

Now I create two ITRS frames that ostensibly have equal `obstime` values:

```python
>>> itrs1 = ITRS()
>>> itrs1.obstime
<Time object: scale='utc' format='jyear_str' value=J2000.000>
>>> itrs2 = ITRS(obstime=Time('J2000'))
>>> itrs2.obstime
<Time object: scale='utc' format='jyear_str' value=J2000.000>
>>> assert itrs1.obstime == itrs2.obstime
```

But when I perform the transformation, I get different values!

```python
>>> c.transform_to(itrs1).spherical
<SphericalRepresentation (lon, lat, distance) in (deg, deg, )
    ( 241.55194873,  9.90953611,  1.)>
>>> c.transform_to(itrs2).spherical
<SphericalRepresentation (lon, lat, distance) in (deg, deg, )
    ( 279.53899958,  9.9980265,  1.)>
>>> assert (c.transform_to(itrs1).spherical.lon ==
...         c.transform_to(itrs2).spherical.lon)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AssertionError
```

What's going on here?

**Comment by fgrollier** [comment]
The answer lies in the `.transform_to` method's docstring :

> The precise frame transformed to depends on ``merge_attributes``.
If `False`, the destination frame is used exactly as passed in.
But this is often not quite what one wants.  E.g., suppose one wants to
transform an ICRS coordinate that has an obstime attribute to FK4; in
this case, one likely would want to use this information. Thus, the
default for ``merge_attributes`` is `True`, in which the precedence is
as follows: (1) explicitly set (i.e., non-default) values in the
destination frame; (2) explicitly set values in the source; (3) default
value in the destination frame.

In your case you should set the `merge_attributes` parameter to `False` when calling the method on `icrs1` to get the same result in both cases.

**Comment by lpsinger** [comment]
Thanks. My mistake.
