### ISSUE TITLE
WCS Cutout2D wrong ticks

### ISSUE THREAD

**Issue by Amarchuk** [astropy/astropy#6997]
Hi all,

thanks for your efforts on development, it is really helpful! I have a question related to WCS.

I try to work with [this NGC628 FITS file](http://www.mpia.de/THINGS/Data_files/NGC_628_NA_MOM0_THINGS.FITS) from THINGS survey. ds9 and original paper ([this one](http://iopscience.iop.org/article/10.1088/0004-6256/136/6/2563/pdf)) show similar coordinate grid. But when I try to plot centar part of it useing `Cutout2D` by myself, I get wrong xaxis and yaxis labels. Interesting that the full fits plotted using matplotlib and wcs projection show correct ticks grid.

Minimal working example:

```python
from astropy.io import fits
from astropy.wcs import WCS
from astropy.coordinates import SkyCoord
import astropy.units as u
from astropy.nddata import Cutout2D

data = fits.getdata('NGC_628_NA_MOM0_THINGS.FITS')
w = WCS('NGC_628_NA_MOM0_THINGS.FITS', naxis=2)
position= SkyCoord('24.1763715249  15.7865508568', frame='fk5', unit='deg', equinox='J2000.0')
size = u.Quantity((106, 314), u.arcsec)
cutout = Cutout2D(np.squeeze(data), position, size, wcs=w)
fig = plt.figure(figsize=[24, 8])
ax = fig.add_subplot(1, 1, 1, projection=w)
lon = ax.coords[0]
lat = ax.coords[1]
lon.set_major_formatter('hh:mm:ss')
lat.set_major_formatter('dd:mm:ss')
plt.imshow(cutout.data, origin='lower', cmap='gist_yarg')
plt.show()
```

astropy 2.0.1, python 2.7, windows 7

**Comment by pllim** [comment]
@larrybradley , does your recent PR that is related to axis flipping fix this? (I can't seem to find it presently.)

**Comment by larrybradley** [comment]
@pllim, no, it's unrelated to that PR.

**Comment by larrybradley** [comment]
@Amarchuk  To display the cutout image, you need to use the WCS for the cutout.  You are using the WCS of the original image.

Replace this line:
```
ax = fig.add_subplot(1, 1, 1, projection=w)
```
with this:
```
ax = fig.add_subplot(1, 1, 1, projection=cutout.wcs)
```

**Comment by Amarchuk** [comment]
Thanks @larrybradley  - this is definitely the case! It looks much better now. 

I have another related question - actually try to cut the same region from different fits which all from different surveys. Use their CRVAL as cutout position and use the same size like in snippet above. It seems like the ticks shift noticeably between different cutouts: 

<img src="https://raw.githubusercontent.com/Amarchuk/2FInstability/master/data/ngc628/hi_dens_cutout.png" height="250">

<img src="https://raw.githubusercontent.com/Amarchuk/2FInstability/master/data/ngc628/co_dens_cutout.png" height="250">

<img src="https://raw.githubusercontent.com/Amarchuk/2FInstability/master/data/ngc628/star_dens_cutout.png" height="250">

I expect to see the ticks near the same place on every image (probably shifted to one pixel because of rounding). But they are not as you can see. What it can be? Is it probably because 
> If size is in angular units, the cutout size is converted to pixels using the pixel scales along each axis of the image at the CRPIX location. Projection and other non-linear distortions are not taken into account

but I am not sure.

**Comment by larrybradley** [comment]
I would use only one sky coordinate value as the central position for all of the images (assuming the images are WCS aligned).  If these images came from different surveys, I wouldn't necessarily expect them all to have the same CRVAL.  If they have different CRVALs, then you are effectively making cutouts from (slightly) different regions.

**Comment by Amarchuk** [comment]
@larrybradley It also helps, thanks. But I can't understand - I think that CRVAL is a position of the FITS center and since I want to extract the same area on images from different survey I should use their CRVAL.

**Comment by larrybradley** [comment]
CRVAL (and CRPIX) is just a reference value/pixel for the coordinate system.  It actually can be anywhere (including not even in the image!).  Generally it is defined near the image center, but there's no requirement for that.  If the images are WCS aligned, then using a single sky coordinate value for the cutout center and size will give you the same exact cutout region.

**Comment by Amarchuk** [comment]
Ok, I get it. Final thanks!
