### ISSUE TITLE
Developer documentation: write "HOW TO" about package data in affiliated packages.

### ISSUE THREAD

**Issue by kbarbary** [astropy/astropy#700]
Affiliated packages for various subfields of astronomy are likely to include package data specific to the subfield. It would be nice to have a step-by-step "HOW TO" (with an example) in the developer documentation on the proper way to include such data.

There are currently guidelines on package data and configuration [here](http://astropy.readthedocs.org/en/latest/development/codeguide.html#data-and-configuration). The process is fairly obvious for small data (<100kb), but it is not exactly clear how to extend the outlined process to a third-party server for the affiliated package. One might be able to figure it out by reading the docs for `astropy.config` and `astropy.utils.data`, but it would be nice to have a simple example that shows the following:
1. Adding a default configuration file for the affiliated package (wherein the `dataurl` for the affiliated package is set)
2. How to appropriately name your data files on the server side.
3. A simple class or function in the affiliated package that uses the data.

The documentation might also address some related questions that came up for me regarding data file sizes:

**Related question 1:** How big is too big? (for even the externally hosted data scheme) Specifically, I'm thinking here of the SFD dust maps, which are ~200MB.

**Related question 2:** Is/should/could there be a way to install or cache files somewhere other than the user's home directory? (1) For a system-wide install used by multiple users, you might want to only have one copy of the package data. (2) Also, on some systems, disk quotas in home directories are quite small and data is meant to reside elsewhere (or should the user just set `XDG_CACHE_HOME` accordingly in this case?)

**Comment by pllim** [comment]
This is rather old... And shouldn't this be in `package-template`?

**Comment by bsipocz** [comment]
@pllim - The package template is still in the middle of the big overhaul. I suggest to keep this one open here at least until we move the template related docs over to the template.

**Comment by bsipocz** [comment]
No news other than it should be written up by someone. 

Maybe this can live in the best practices part of the FAQ @pllim envisioned the other day?

**Comment by pllim** [comment]
cc @astropy/coordinators

**Comment by bsipocz** [comment]
> Should we move this issue to the package-template repo?

Yes, I think it would be great to move it there.

**Comment by pllim** [comment]
I can't see the magic "move issue" button and I don't have patience to wait for someone to do it, so here it is: astropy/package-template#398
