### ISSUE TITLE
NUMPY2FITS Limited types 

### ISSUE THREAD

**Issue by Acrisel** [astropy/astropy#7005]
Hello,

To automatically create formats from numpy arrays to fits columns, i used NUMPY2FITS to translate dtypes for fits formats. A problem uccurs when dtype is numpy types (e.g. np.float64) instead of type tags(e.g, "f8").  

To allow this t work, locally I expended NUMPY2FIT as follows:
```
NUMPY2FITS.update({
        'bool_': NUMPY2FITS['u1'],  # Boolean (True or False) stored as a byte
        'int_': NUMPY2FITS['i8'],  # Default integer type (same as C long; normally either int64 or int32)
        'intc': NUMPY2FITS['i8'],  # Identical to C int (normally int32 or int64)
        'intp': NUMPY2FITS['i8'],  # Integer used for indexing (same as C ssize_t; normally either int32 or int64)
        'int8': NUMPY2FITS['i1'],  # Byte (-128 to 127)
        'int16': NUMPY2FITS['i2'],  # Integer (-32768 to 32767)
        'int32': NUMPY2FITS['i4'],  # Integer (-2147483648 to 2147483647)
        'int64': NUMPY2FITS['i8'],  # Integer (-9223372036854775808 to 9223372036854775807)
        'uint8': NUMPY2FITS['u1'],  # Unsigned integer (0 to 255)
        'uint16': NUMPY2FITS['u2'],  # Unsigned integer (0 to 65535)
        'uint32': NUMPY2FITS['u4'],  # Unsigned integer (0 to 4294967295)
        'uint64': NUMPY2FITS['u8'],  # Unsigned integer (0 to 18446744073709551615)
        'float_': NUMPY2FITS['f8'],  # Shorthand for float64.
        'float16': NUMPY2FITS['f2'],  # Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
        'float32': NUMPY2FITS['f4'],  # Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
        'float64': NUMPY2FITS['f8'],  # Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
        'complex_': NUMPY2FITS['c16'],  # Shorthand for complex128.
        'complex64': NUMPY2FITS['c8'],  # Complex number, represented by two 32-bit floats (real and imaginary components)
        'complex128': NUMPY2FITS['c16'],  #    Complex number, represented by two 64-bit floats (real and imaginary components)
    })
```

I am wondering if this should better to be done in the core fits column.py.

Best regards,

**Comment by saimn** [comment]
I can see how it would be practical to have this, but I think that `NUMPY2FITS` should not be modified as it seems to be used mostly to validate the data internally.
There are also other internal functions related to this like `_dtype_to_recformat` which gives the fits format corresponding to a Numpy dtype:
```
In [4]: _dtype_to_recformat(np.float)
Out[4]: ('f8', 'f', dtype('float64'))

In [5]: _dtype_to_recformat(np.float32)
Out[5]: ('f4', 'f', dtype('float32'))

In [6]: _dtype_to_recformat(np.int8)
Out[6]: ('i1', 'i', dtype('int8'))

In [7]: _dtype_to_recformat(np.int_)
Out[7]: ('i8', 'i', dtype('int64'))

In [8]: _dtype_to_recformat(np.intc)
Out[8]: ('i4', 'i', dtype('int32'))

In [9]: _dtype_to_recformat(np.intp)
Out[9]: ('i8', 'i', dtype('int64'))
```
This function is actually doing `dt.base.kind + str(dt.base.itemsize)`, which gives mostly the same results as your mapping (with a difference for `np.intc`). Maybe you should use this instead ? (Not sure if an helper function doing this would be useful ?)

**Comment by Acrisel** [comment]
Yes; this absolutely does the trick!

Thank you so much!

Best regards,

**Comment by saimn** [comment]
I think the creation of columns could be simplified by guessing the format from the numpy dtype, so I looked in the old PyFITS repository and found https://github.com/spacetelescope/PyFITS/issues/77 which is the same idea. I will open a new issue from this one.
