### ISSUE TITLE
Add tests and fix bugs in tabledump and tableload

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#7015]
Follow-up to #6937. We should test that these functions work (and that `tableload` can load files saved with `tabledump`). Currently the `cdfile` option for `tabledump` is broken (and this file is needed to use `tableload`):
```
In [7]: fits.tabledump('astropy/io/fits/tests/data/tb.fits', 'foo.txt', hfile='hfile.txt', cdfile='cdfile.txt', overwrite=True)
WARNING: Overwriting existing file 'foo.txt'. [astropy.io.fits.hdu.table]
WARNING: Overwriting existing file 'hfile.txt'. [astropy.io.fits.hdu.table]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-0fcce33a4feb> in <module>()
----> 1 fits.tabledump('astropy/io/fits/tests/data/tb.fits', 'foo.txt', hfile='hfile.txt', cdfile='cdfile.txt', overwrite=True)

~/dev/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    485                         # one with the name of the new argument to the function
    486                         kwargs[new_name[i]] = value
--> 487             return function(*args, **kwargs)
    488 
    489         return wrapper

~/dev/astropy/astropy/io/fits/convenience.py in tabledump(filename, datafile, cdfile, hfile, ext, overwrite)
    894 
    895         # Dump the data from the HDU to the files
--> 896         f[ext].dump(datafile, cdfile, hfile, overwrite)
    897     finally:
    898         if closed:

~/dev/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    485                         # one with the name of the new argument to the function
    486                         kwargs[new_name[i]] = value
--> 487             return function(*args, **kwargs)
    488 
    489         return wrapper

~/dev/astropy/astropy/io/fits/hdu/table.py in dump(self, datafile, cdfile, hfile, overwrite)
   1106         # Process the column definitions
   1107         if cdfile:
-> 1108             self._dump_coldefs(cdfile)
   1109 
   1110         # Process the header parameters

~/dev/astropy/astropy/io/fits/hdu/table.py in _dump_coldefs(self, fileobj)
   1292             attrs = ['disp', 'unit', 'dim', 'null', 'bscale', 'bzero']
   1293             line += ['{:16s}'.format(value if value else '""')
-> 1294                      for value in (getattr(column, attr) for attr in attrs)]
   1295             fileobj.write(' '.join(line))
   1296             fileobj.write('\n')

~/dev/astropy/astropy/io/fits/hdu/table.py in <listcomp>(.0)
   1292             attrs = ['disp', 'unit', 'dim', 'null', 'bscale', 'bzero']
   1293             line += ['{:16s}'.format(value if value else '""')
-> 1294                      for value in (getattr(column, attr) for attr in attrs)]
   1295             fileobj.write(' '.join(line))
   1296             fileobj.write('\n')

ValueError: Unknown format code 's' for object of type 'int'
```
(this is another side-effect from aaaa6fb56f - #5432, `%s` was converting to a string if needed, but `{:s}` does not do that, cc @bsipocz :wink: )

**Comment by bsipocz** [comment]
I really should not touch fits...

**Comment by macicco** [comment]
Hello,

I am trying to fix it , ok?

**Comment by saimn** [comment]
@macicco - Ok, great. Don't hesitate to ask if you need some guidance. (Reading #6976 should provide some context)

**Comment by macicco** [comment]
Yes I will need for sure, if you guys could tell me some good tips, I ll appreciate !

**Comment by macicco** [comment]
While testing, the 'hfile.txt' was not produced.

**Comment by pllim** [comment]
@macicco , could you please clarify? How exactly did you test it?

**Comment by macicco** [comment]
just repeated : 

fits.tabledump('astropy/io/fits/tests/data/tb.fits', 'foo.txt', hfile='hfile.txt', cdfile='cdfile.txt', overwrite=True)

using ipython in the same directory of .../tb.fits

**Comment by pllim** [comment]
@macicco , did you see any error message? It is not produced because of the error reported above.

**Comment by saimn** [comment]
Yes "hfile" cannot be produced since it breaks before with "cdfile".

**Comment by macicco** [comment]
Ok, so the core problem could be

'  line += ['{:16s}'.format(value if value else '""') ' ,

**Comment by macicco** [comment]
Hi !

I did a change on line 1249 of table.py as follows:

from : line += ['{:16s}'.format(value if value else '""') '

to :

line += ['{:16s}'.format(str(value) if value else '""') '...

The error disappeared and  after testing fits.tableload, the files were reunited again, no error.

**Comment by macicco** [comment]
Hi I created a new test for tabledump called: 
.../io/fits/tests/test_tabledump.py, 

after rebasing, I did py.test, and there was no error.

test_tabledump.py:
`# Licensed under a 3-clause BSD style license - see PYFITS.rst


import os
import warnings
import unittest
import pytest
import numpy as np

from ....io import fits
from ....table import Table
from .. import printdiff
from ....tests.helper import catch_warnings

from . import FitsTestCase

class TestConvenience(FitsTestCase):

    def test_tabledump(self):
        """
        Regression test for https://github.com/astropy/astropy/issues/6937
        """
        # test without datafile
        filename = self.data('tb.fits')
        fits.tabledump(filename)
        assert os.path.isfile(self.data('tb_1.txt'))
        os.remove(self.data('tb_1.txt'))

        # test with datafile
        fits.tabledump(filename, datafile=self.temp('test_tb.txt'))
        assert os.path.isfile(self.temp('test_tb.txt'))

        # test with cdfile, hfile
        """
        test for https://github.com//astropy/astropy/issues/7015
        """
        fits.tabledump(filename, datafile=self.temp('test_tb.txt'), \
        hfile=self.temp('hfile.txt'), cdfile=self.temp('cdfile.txt'),\
        overwrite=True )
        assert os.path.isfile(self.temp('hfile.txt'))
        assert os.path.isfile(self.temp('cdfile.txt'))
        hdump = fits.tableload(self.temp('test_tb.txt'),\
        hfile=self.temp('hfile.txt'), cdfile=self.temp('cdfile.txt'))
        assert os.path.isfile(self.temp('test_tb.txt'))
        hdump.writeto(self.temp('tableb_tb.fits'))
        assert printdiff(self.temp('tableb_tb.fits'), filename) is None
`

**Comment by bsipocz** [comment]
@macicco - Please don't dump patches here in the issue, but when you have a solution for an issue open a PR and just reference the issue there. It would make review easier and the whole process orders of magnitude cleaner.

**Comment by macicco** [comment]
@bsipocz , sorry!

**Comment by sbrice** [comment]
Hi, so what's the status of this?

**Comment by bsipocz** [comment]
@sbrice - still looks unfixed.

**Comment by MohsenQazi** [comment]
@bsipocz @saimn - Could you please give me more information?
I want to know that, what is the error after @macicco PR? same error as above (`ValueError: Unknown format code 's' for object of type 'int'`) or a new one?!

**Comment by saimn** [comment]
@MohsenQazi - There was no PR so the issue is still the same I guess.

**Comment by MADECICCO** [comment]
I need more time to work on this issue. Sorry.
