### ISSUE TITLE
Geolocation issue

### ISSUE THREAD

**Issue by ramsinghdayal** [astropy/astropy#7018]
I have two .fits files, in one .fits file, there is information about data and other .fits file have information about latitude and longitude. So how can I overlay latitude longitude grid on data using astropy ?

**Comment by bsipocz** [comment]
@ramsinghdayal - Thank you for your interest in astropy. Unfortunately, GitHub issues are meant for bug reports or feature requests. For general usage questions like this, please consider using one of the forums listed in http://www.astropy.org/help.html, such as the mailing list or the Facebook group.  There will be more people to assist you there.
