### ISSUE TITLE
Streamline context managers between units and constants

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7021]
See https://github.com/astropy/astropy/pull/7008#issuecomment-353173867 as suggested by @mhvk below:

[`set_enabled_constants` is] in analogy with `u.set_enabled_units`. Eventually, we might then also have `add_enabled_constants`... Indeed, is there room for re-using some of the units constants machinery?

**Comment by bsipocz** [comment]
@stargaser - what is the status of this? Does the newly merged `ScienceState` addresses this? If now, would this be in the scope to be address by 4.0?

**Comment by stargaser** [comment]
The discussion in #8866 is leaning towards deprecating the context manager for constants. If that's the final decision, I think we can close this issue.

The comment was to have `set_enabled_constants` and `add_enabled_constants` analogously to unit's `u.set_enabled_units` and `u.add_enabled_units`. I don't think we can do this with the new `ScienceState` classes for constants versions. The main reason is that the version change has to happen before any import of constants or units, so it doesn't seem possible to make a context manager work.

We ought to get @mhvk's opinion before closing this one...

**Comment by mhvk** [comment]
I agree that I do not see how we can make `set_enabled_constants` possible. So, closing.
