### ISSUE TITLE
Add "extragalactic" and "galactic" unit systems

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#703]
#579 added the `to_system` functionality to `units`.  This provides an easy way to convert units between `cgs` and `si`.  A nice addition would be to also support `galactic` and `extragalactic` unit systems.  These systems would be like `cgs`, but with the natural length scale in `kpc` or possibly `Mpc` for `extragalactic` and `pc` for `galactic`, and with `km/s` the natural velocity scale.

This _may_ require more work, because `km/s` is not an irreducible unit.  But I haven't looked closely enough to know how one might do this with the `to_system` logic.

cc @mdboom

**Comment by mhvk** [comment]
Just for the record: with #2559, the above `(1./(10.*u.Gyr)).decompose((u.Mpc, u.km/u.s))` does not work.

**Comment by adrn** [comment]
Sorry this totally fell off of my radar. It's something I deal with all the time, though long ago I just accepted it and adapted all of my code to work in the system (kpc, Myr, Msun). This lets me use `decompose()` everywhere, but it would be kind of cool if we had some kind of specialized support for decomposing into composite units, e.g.

    >>> (15*u.imperial.mi / u.s).decompose([u.km/u.s, u.kpc, u.Myr])
    <Quantity 24.14016 km / s>

Of course, the showstopper is the question of what to do with something like `<Quantity 15.0 mi2 / s3>`... I wonder if it would be useful enough to match on physical type of the decomposing system, and if no explicit match is found, take the base units? Something like:

    >>> (15*u.imperial.mi / u.s).decompose(bases=[u.kpc, u.Myr], composite_bases=[u.km/u.s])

(BTW @mhvk I was just found a copy of your thesis in my office...not sure what the universe is trying to tell me)

**Comment by mhvk** [comment]
But then again, maybe adding too many bells & whistles is not good either... 

Funny how this habit of printing many copies of one's thesis influences things. And scary to think I still use optimal extraction code I developed at the time (which, who knows, may at some point enter specutils in a python incarnation...).

**Comment by adrn** [comment]
@mhvk Totally agree -- oops, I didn't mean to imply that the above belongs in the core, just bringing it up for discussion!

**Comment by mhvk** [comment]
Understood -- in principle, I think it would be good if the example I gave would work, i.e., one could decompose into any bases with which it is possible to construct the unit given.

**Comment by adrn** [comment]
FYI: I implemented something like this [in one of my own packages](http://gary.adrian.pw/en/latest/units.html) as a trial implementation / demo of one possible way to do this. In my `UnitSystem` object, you can override base unit combinations by specifying composite units. For example, this unit system would always convert down to combinations of base units:

    >>> usys = UnitSystem(u.kpc, u.Myr, u.Msun, u.radian)
    >>> (15*u.km/u.s).decompose(usys)
    <Quantity 0.015340682475805617 kpc / Myr>

But this has a specified representation for 'speed'-like units, so it doesn't return kpc/Myr:

    >>> usys2 = UnitSystem(u.kpc, u.Myr, u.Msun, u.radian, u.km/u.s)
    >>> usys2.decompose(15*u.km/u.s)
    <Quantity 15.0 km / s>

(note: I chose not to monkey-patch the `.decompose()` method on `Quantity`, thats why this special method call is on the unit system instead).

The `UnitSystem` then acts like a dictionary for physical types (which, right now, are strings):

    >>> usys['speed']
    Unit("kpc / Myr")
    >>> usys2['speed']
    Unit("km / s")

If the (non-base) physical type wasn't specified on creation, it puts together the base units:

    >>> usys['pressure']
   Unit("solMass / (kpc Myr2)")

**Comment by jobovy** [comment]
I'm looking into using the Units framework for [galpy](https://github.com/jobovy/galpy) and stumbled on this issue; obviously having a ``galactic`` unit system would make that support much easier!

I only glanced through the thread, but wouldn't many of the issues raised her be resolved by *not* having time as a fundamental unit (i.e., just have length and velocity; similar t WD_units in NEMO)? If you use ``kpc`` and ``km/s``, the derived time unit would be ~Gyr.

Also don't see how there can be any argument against ``kpc`` as the appropriate length unit for galaxies (there's fewer than 1 star / pc^3 near the Sun...). And Gyr is much closer to the dynamical time than ``Myr``...

**Comment by adrn** [comment]
Closed to discuss the broader issue in #11525
