### ISSUE TITLE
Deprecate `representation` in frames and SkyCoord

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#7032]
More background on this in #6873.  There the old `representation` and `differential_cls` attributes/keyword arguments were shifted to `representation_type` and `differential_type`.  The stated plan there is to deprecate the "old" attributes in v3.1, and then switch to raising errors in 3.2.  This issue is for just the deprecation step.

**Comment by vermashresth** [comment]
Hi @eteq 
I would like to work on this but I have some doubts. Should we use the  `deprecated` decorator or directly the AstropyDeprecationWarning. And for SkyCoord, the representation property calls representation in `frame` which itself has to be deprecated. So will doing it for just `frame` be fine? Also, should I just follow the TODO comments for deprecate written in #6873 ?

**Comment by bsipocz** [comment]
@eteq - did this happen? If not, do you still plan to do it in 3.1? Otherwise please re-wise milestone.

**Comment by cdeil** [comment]
Related: #6873.

With Astropy master we now get this `ValueError` in the Gammapy tests:
https://travis-ci.org/gammapy/gammapy/jobs/453698975#L2829
```
ValueError: Both `representation` and `representation_type` were passed to a frame initializer. Please use only `representation_type` (`representation` is now pending deprecation).
```

@eteq @adrn - Is this intentional to break callers that used `representation` or by accident?

What change should we do to our code to keep support for Astropy 2.x and 3.x? Some version-dependent checks? Or is there a way to write this code that works with both old and new version without having to do Astropy version checking in the implementation?

https://github.com/gammapy/gammapy/blob/d71e4692462dd17359488bad49a473949b423a5e/gammapy/data/pointing.py#L140-L144

**Comment by eteq** [comment]
@cdeil - does something like this work?:
```
if astropy.version.major >= 3:
    SkyCoord(..., representation_type=...)
else:
    SkyCoord(..., representation=...)
  
```
from your example it looks to me like that *should* do the job, but I could be missing some subtlety!

**Comment by cdeil** [comment]
I had put this:
```
        if astropy_version >= "3.1":
            kwargs = {"representation_type": "unitspherical"}
        else:
            kwargs = {"representation": "unitspherical"}

        return SkyCoord(xyz_new, frame=altaz_frame, unit="deg", **kwargs)
```

This works, I just thought there might be a way to make such a SkyCoord that doesn't need a version check.

If not:  `representation_type` was introduced in `3.0 and I should change to `if astropy.version.major >= 3` ?

**Comment by eteq** [comment]
@cdeil - The *intent* was for `representation` to keep working through 3.1 at least. I'm a bit confused how your error came to be... possibly @adrn has some insight here?  So it may be there's actually a separate bug here that's sort of "masked" by the addition of `representation_type`.  But what you've done here is a good workaround regardless.

But yes, `representation_type` was in 3.0 . But if this is indeed a bug perhaps the bug is in master, in which case your code above is sort of a workaround for the bug...
