### ISSUE TITLE
AltAz frame gives a different local meridean depending on latitude

### ISSUE THREAD

**Issue by Joshuaalbert** [astropy/astropy#7046]
## Context

I was looking into why `Time.sidereal_time` gives a different LST from the definition of RA of the local merdiean. This is clearly seen in the MCVE.

Note: The definition of the local sidereal time is:
```
The local apparent sidereal time at a given location is defined as the
 hour angle of the vernal equinox at that location: it has the same 
value as the right ascension of any celestial body that is crossing
 the local meridian at that same moment.

At the moment when the vernal equinox crosses the local meridian, 
local apparent sidereal time is 00:00. Greenwich apparent sidereal
 time (GAST) is the hour angle of the vernal equinox at the prime 
meridian at Greenwich, London.
```

I do not understand why the RA of a celestial body at the zenith is not giving the same as the LST function. This raises concerns right away.
I then noticed that if I change the latitude for AltAz that the resultant RA of the zenith changes (note refraction should be turned off by default and I assume this is true). This should definitely not happen.

## MCVE

```
import astropy.time as at
import astropy.coordinates as ac
import astropy.units as au

def _altaz_lst(time,location):
    local_meridean = ac.AltAz(alt=90*au.deg,az=0*au.deg,location=location,obstime=time)
    return local_meridean.transform_to(ac.ICRS).ra.hourangle

def _lst(time,location):
    lon = location.to_geodetic().lon
    return time.sidereal_time('apparent',lon).hourangle
    
    
lon = 10*au.deg
lat = 50*au.deg
height=0*au.m
location = ac.EarthLocation(lon=lon,lat=lat,height=height)
time = at.Time("2005-01-01T00:00:00.000",format='isot',scale='utc')

print("lst from Time.sidereal_time:", _lst(time,location))
# lst from Time.sidereal_time: 7.382769438709385

lat = 50*au.deg
location = ac.EarthLocation(lon=lon,lat=lat,height=height)
print("lst from def and AltAz:",_altaz_lst(time,location))
# lst from def and AltAz: 7.375968394833289

lat = 0*au.deg
location = ac.EarthLocation(lon=lon,lat=lat,height=height)
print("lst from def and AltAz:",_altaz_lst(time,location))
#lst from def and AltAz: 7.378240161641947
```

**Comment by StuartLittlefair** [comment]
Is it due to aberration?

**Comment by Joshuaalbert** [comment]
@StuartLittlefair by aberration do you mean refraction in the AltAz frame? It is off by default.

**Comment by StuartLittlefair** [comment]
Hi Joshua, 

Sorry for slow response time - no, I mean the apparent shift in position due to motion of the frame of reference.

**Comment by Joshuaalbert** [comment]
That could be the case, since the local sidereal time depdends on latitude. `v/c` would depend on your distance from Earth's axis. In that case, there is actually a difference between the hour angle of the local meridian and sidereal time. I must think about which definition I should use in the UVW coordinate system, or go ask someone.

**Comment by Joshuaalbert** [comment]
I sent an email to Mark Calabretta who helped design the WCS. Let's see.

**Comment by adrn** [comment]
This is the kind of issue I point people at when they say "why is there so much code in astropy coordinates - aren't astronomical coordinate systems simple?" 😄

**Comment by jrthorstensen** [comment]
I believe I understand the problem.  In _altaz_lst, you seem to ask for the ICRS coordinates of the meridian, which is basically J2000; that's if I'm interpreting this correctly:

return local_meridean.transform_to(ac.ICRS).ra.hourangle

The LST will be the RA of the meridian in the equinox of date, not the ICRS (unless you're observing at J2000).   Furthermore, a line of constant RA in the ICRS is not even parallel to the meridian at dates other than J2000.  So if you ask for the ICRS RA of the meridian at different declinations as you do, you get different answers.  I was able to reproduce your results using JSkyCalc, to limited precision because JSkyCalc only reports the LST and hour angle to the nearest second.

**Comment by jrthorstensen** [comment]
A quick question, sorry if this isn't the right forum -- does astropy.coordinates offer an easy transformation to coordinates of the epoch of date?  If you could do that, you should get sensible results.

**Comment by Joshuaalbert** [comment]
I have discussed with some VLBI people who really require precise descriptions of the UVW system, and my answer is that indeed the proper UVW system is with respect to the LST, i.e. the rotation period of the Earth. The reason is that in the synthesis imaging step timing errors of a ns are important, and the rotation period depends on the local sidereal time.

@jrthorstensen Thanks for your post. I do appreciate your idea. Celestial mechanics are very important to understand. Indeed, LST depends on the current epoch which cannot be compared to another epoch without coordinate transport. It also seems to take into account aberration.
Running the above code at `2000-01-01T00:00:00.000` produces slightly different results:
```
lst from Time.sidereal_time: 6.664618939540326
lst from def and AltAz at lon,lat=0,0: 6.664229048844216
lst from def and AltAz at lon,lat=0,50: 6.6641668971682915
```
The difference between the first two is ~1e-4 which is presumably due to abberation.

Also, in astropy you can transform to another frame via `coordinates.transform_to(frame)`. You just have to define the frame.

**Comment by Joshuaalbert** [comment]
I'll close this now because my question was answered elsewhere and is stated above.
