### ISSUE TITLE
NDDataRef cannot be imported

### ISSUE THREAD

**Issue by Trimilur** [astropy/astropy#7048]
from astropy.nddata import NDDataRef
ImportError: cannot import name NDDataRef

**Comment by mwcraig** [comment]
@Trimilur -- thanks for reporting the issue. Could you provide a little more detail so that I can try to reproduce the error? Please let me know:

+ What version of astropy you are using
+ What version of Python
+ What OS
+ How you installed python (anadconda, canopy, system python, homebrew, ...)

**Comment by Trimilur** [comment]
Damn :( I fee so sorry for this report. I was investigating and  I realized that I am probably using the wrong version of astropy (1.1.1)

I was just confused that specutils works "fine" on my setup but is dependend on NDDataRef what is not introduced with 1.1.1

Python 2.7.5, system
Scientific Linux

Sorry for the report

**Comment by MSeifert04** [comment]
Yes, `NDDataRef` was added in 1.2 (http://docs.astropy.org/en/stable/changelog.html#id153), so you have to update astropy if you need it.

**Comment by mwcraig** [comment]
@Trimilur -- never any need to apologize for  opening a bug report. They always make me :grinning: because it means someone is a) using the software and b) finds it useful enough to take the time to report. So really you made my day twice....new confirmed user and no problem to fix!
