### ISSUE TITLE
Incorrect result when slicing a row by multiple columns

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7049]
In the following example:

```
In [1]: from astropy.table import Table

In [2]: t = Table()

In [3]: t['a'] = [1,2,3]

In [4]: t['b'] = [3,4,5]

In [5]: row = t[0]

In [6]: row['a', 'b']
Out[6]: 
<Column name='a' dtype='int64' length=3>
1
2
3
```

I would either expect an error for ``row['a','b']`` or I would expect the same as:

```
In [7]: t['a', 'b'][0]
Out[7]: 
<Row index=0>
  a     b  
int64 int64
----- -----
    1     3
```

**Comment by vermashresth** [comment]
@astrofrog I would like to work on this. Should we just add another case for list type item in `__getitem__` of [row.py](https://github.com/astropy/astropy/blob/master/astropy/table/row.py#L40:L41) ?

**Comment by saimn** [comment]
Probably the same as #4068 ?

**Comment by vermashresth** [comment]
@saimn Yes! that would do. But if we don't want to create another table here's what I thought
```python
def __getitem__(self, item):
        if isinstance(item,slice):
            return self._table[self._table.colnames[item]][self._index]
        elif isinstance(item,tuple):
            return self._table[item][self._index]
        else:
            return self._table.columns[item][self._index]
```
This covers the case of tuple as in this issue as well as the case of slicing in #4068. Is it better to use colnames or is making a new table fine?

**Comment by saimn** [comment]
@vermashresth - No idea on the best option here, but @taldcroft probably knows better than me ;)

**Comment by vermashresth** [comment]
Hi! @taldcroft
Can you please suggest what would be the best approach here?

**Comment by taldcroft** [comment]
@vermashresth - I started thinking about how to solve it this morning, and couldn't be sure of a workable approach without writing code.  Once I got there I just wrote the tests to be done with this.  Sorry...
