### ISSUE TITLE
fitsheader as an alternative to dfits+fitsort ?

### ISSUE THREAD

**Issue by jwoillez** [astropy/astropy#7055]
At the moment if I run `fitsheader -t -e 0 -k "KEYWORD1" -k "KEYWORD2" *.fits`, I obtain something that looks like this:

    |   filename | hdu |  keyword | value |
    | file1.fits |  0  | KEYWORD1 |     1 |
    | file1.fits |  0  | KEYWORD2 |     2 |
    | file2.fits |  0  | KEYWORD1 |     1 |
    | file2.fits |  0  | KEYWORD2 |     3 |
    | file3.fits |  0  | KEYWORD1 |     1 |
    | file3.fits |  0  | KEYWORD2 |     4 |

Which is not very convenient to compare the values of some keywords across multiple files.
I would like to find a way to get the output to look like the following, which is the behavior of the good old `fits` and `fitsort` tools:

    |   filename | KEYWORD1 | KEYWORD2 |
    | file1.fits |        1 |        2 |
    | file2.fits |        1 |        3 |
    | file3.fits |        1 |        4 |

If the hdu index of the keywords matters, the format could be tweaked to the following:

    |   filename | 0:KEYWORD1 | 0:KEYWORD2 |
    | file1.fits |          1 |          2 |
    | file2.fits |          1 |          3 |
    | file3.fits |          1 |          4 |

I am happy to implement this (assuming that something equivalent is not already available), but wanted to have some feedback first.

**Comment by saimn** [comment]
I am all for it, actually I was planning to open the same issue ;-)

`fitsheader --table`'s current output is really not convenient, having something more similar to dfits+fitssort would be much better. But should we replace `--table`'s output or create a new flag ? (Is someone using and liking the current output ?)

There are maybe other things that could be taken from dfits+fitssort ? Like the use of dot as separator for HIERARCH keywords ? (i.e. `-k ESO.DPR.TYPE`)

**Comment by pllim** [comment]
c/c @SaraOgaz since she had previously attempted something similar (I think).

**Comment by SaraOgaz** [comment]
This would be great to have! Consider this a second request.  In favor of just replacing --table's output instead of adding it as a secondary flag option (if I'm interpreting your comment correctly @saimn)

**Comment by jwoillez** [comment]
How about not changing the `--table` behavior, but switching to the `dfits+fitsort` format as soon as more than one fits file is provided without the `--table` flag?
Then only `fitsheader *.fits` would have the new format.
To recover the old behavior, one would have to call `fitsheader` one file at a time.

@saimn I can make `fitsheader` support the dot notation for HIERARCH as well.

**Comment by saimn** [comment]
@SaraOgaz - Yes, that's the question. I think we could replace `--table`'s output, as it is probably not widely used, but there is always a risk of breaking someones's workflow.

@jwoillez - Having two different outputs for the same option seems weird. I think we should either replace `--table` or add a new flag, not mixing the two formats.

**Comment by jwoillez** [comment]
The suggestion was in order to keep the number of options to a minimum, this being a command line utility. For me there is a difference between inspecting one single fits where you are interested in a key/value dump, and multiple fits where you want to compare things between keywords.

Or we can go simply go for a new utility.

**Comment by saimn** [comment]
> For me there is a difference between inspecting one single fits where you are interested in a key/value dump, and multiple fits where you want to compare things between keywords.

Agreed with this, but I still think it is a bad idea to have a different output depending on the number of files. For instance it would make it painful to write a shell script using fitsheader's output. Having one more flag is not a problem imo, if we really want to keep the current behavior.

**Comment by jwoillez** [comment]
How about `-s --sort` for this flag, to honor the memory of `fitsort`?
Would it be OK to systematically use Table.pprint() for the output of the result?

**Comment by jwoillez** [comment]
We could also let `-s --sort` accept a parameter to sort the result along the specified column.

**Comment by saimn** [comment]
To specify the format `--sort` is probably too confusing, users may expect that it sorts the header in some way (and having this option could be useful indeed). Maybe `--fitsort` ? 
About `Table.pprint()`, the current `--table` format already uses a `Table`, so it seems logical to use it for the new format as well.

**Comment by pllim** [comment]
It is starting to sound like that we might need an APE for this... 😉

**Comment by jwoillez** [comment]
Last question. How do we handle the case where we process multiple HDUs? In the initial example, I suggested to prepend the HDU index to the keyword, in order to differentiate between keywords coming from different HDUs within a single file. Is there a use case where one would want to compare repeating keywords in different HDUs of a single file? Then the HDU index could be amended to the filename, making different HDUs of a single file behave like different files. Thoughts?

**Comment by jwoillez** [comment]
The second case would give results that look like:

    |    filename  |  MJD-OBS |
    | file1.fits:0 | 57947.17 |
    | file1.fits:1 | 57947.27 |
    | file1.fits:2 | 57947.37 |

**Comment by saimn** [comment]
My preference goes for your first example, putting the HDU index with the keyword (and only if the extension is not specified in the command line ?). Because I think it's more common to have different keywords in the HDUs, but no sure ?
