### ISSUE TITLE
TST: Enable xfail_strict by default?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7065]
If tests marked as `xfail` start to pass again, I propose that we treat them as failures.Otherwise, they are overlooked. These could be failures that have since been fixed or failures that don't fail in all conditions. In the latter case, it is cleaner to provide exact conditions for the `xfail` instead of marking `xfail` blindly.

xref: #7056 , #6665 

Relevant `pytest` doc: https://docs.pytest.org/en/latest/skipping.html

p.s. I couldn't find an easy way to just enable `xfail_strict` in, say, RC1 installed from `pip` as `pytest` does not provide command line argument for that.

**Comment by bsipocz** [comment]
This is a very useful idea, thanks @pllim for raising it.

**Comment by giang-nghg** [comment]
@pllim Hi, not sure if this is enough to fix it? https://github.com/astropy/astropy/pull/7194

If it is, please help me on where in CHANGES.rst to put a changelog entry, thanks!

**Comment by bsipocz** [comment]
@giang-nghg - The only tricky point in this is that the test will fail for all passing xfails, so you also need to include the more exact conditions in your PR.
