### ISSUE TITLE
Reduce number of versions on RTD

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7067]
The number of versions in the RTD menu is a little silly:

<img width="314" alt="screen shot 2018-01-11 at 09 25 04" src="https://user-images.githubusercontent.com/314716/34818016-7a73655c-f6b1-11e7-8a34-393774f821bb.png">

Do we really need to keep all these, or just the latest bugfix release in each release series?

**Comment by mhvk** [comment]
Last bug-fix release sounds reasonable

**Comment by taldcroft** [comment]
Agreed, last bug-fix in each series.  But at least one of each full release is useful.

**Comment by bsipocz** [comment]
hmm, I believe @astrofrog, you were logged in to rtd when made this screenshot? I mean I see only these versions, and also recall a step in the release procedure to change the previous release to "protected", so it doesn't get listed in there, but any direct links pointing to it will still work in the future.
![image](https://user-images.githubusercontent.com/6788290/34911457-ef59826c-f8c2-11e7-93a8-a0c874ac209d.png)

**Comment by astrofrog** [comment]
@bsipocz - you are right! I was logged in, my bad.
