### ISSUE TITLE
Importing units breaks Matplotlib plotting functionality

### ISSUE THREAD

**Issue by michaelaye** [astropy/astropy#7076]
See https://github.com/geopandas/geopandas/issues/636 

but basically, when I first do

```python
from astropy import units as u
```
before

```python
import geopandas
from shapely.geometry import Point
s = geopandas.GeoSeries([Point(1,0), Point(2,0)])
s.buffer(10).plot()
```

then the automatic plotting of the shapely Polygons is broken.

MPL version: 2.1.1
Python: 3.6 
Astropy: 2.0.3

Using inside Jupyter notebook, all packages via conda-forge.

**Comment by pllim** [comment]
Is it just `from astropy import units as u` or any `astropy` related imports breaks the plotting feature?

**Comment by pllim** [comment]
AFAIK all the `matplotlib` stuff is in `astropy.visualization`.

**Comment by michaelaye** [comment]
So, it get's even weirder:

1. All fine when I do:
* import astropy
* from astropy import stats
* from astropy import convolution

Now here's the kicker:
When I first do `from astropy import stats` and THEN `from astropy import units` it's NOT broken??

**Comment by pllim** [comment]
That is indeed perplexing.

Do you have a custom `matplotlibrc` file that somehow uses `astropy_mpl_style` or any unusual customization? Does disabling that file fix the problem? (I am asking this question that was asked to me for another problem and it worked for me, so why not give it a try here?)

Does `geopandas` use things like `astropy.visualization.units.quantity_support()`?

My recommendation for now is to document this under "known issues" for `geopandas`.

**Comment by michaelaye** [comment]
Oh, i just realized that this is machine-dependent for me, so I take this is a rotten set-up. will report back...

**Comment by michaelaye** [comment]
so, unfortunately I didn't have the time to fully investigate, but a full reinstall of my conda env removed this bug! Very weird.
