### ISSUE TITLE
astropy.stats sigma clipping is slow due to use of cenfunc=np.ma.median

### ISSUE THREAD

**Issue by Vb2341** [astropy/astropy#7086]
While using `astropy.stats.sigma_clipped_stats` I noticed a huge increase of runtime.  I've run on a single 4k x 2k (pixel) image, as well as roughly 1000 20 x 20 cutouts from the same image.  Compared to using `scipy.stats.sigmaclip` (and then doing the statistics myself) I noticed a performance change of at least a factor 10 (astropy's implementation being slower).  I did some digging using the 4k x 2k image and found some interesting results.

Instead of using `sigma_clipped_stats` I switched to `astropy.stats.sigma_clip` to have a more apples to apples comparison to scipy's `sigmaclip`.  One thing to note is that scipy's `sigmaclip` uses `np.mean` to estimate the central value, whereas astropy's `sigma_clip` uses `np.ma.median` to estimate the central value.  So let's look at the performance of the two directly compared:

### The Bad

```python
from astropy.stats import sigma_clip as astropy_clip
from scipy.stats import sigmaclip as scipy_clip

# data is a 4k x 2k FITS image (an HST WFC3/UVIS image of a star cluster)

%timeit astropy_clip(data)
%timeit scipy_clip(data, low=3., high=3.) # set the low and high clip levels to 3 sigma 
# to match astropy's default values
```

Which yields:
```
1 loop, best of 3: 9.91 s per loop
1 loop, best of 3: 789 ms per loop
```

Ouch.

### The Good

If we play around with the `cenfunc` parameter of astropy's clipping, we can see why there's such a large discrepancy:
```python
%timeit astropy_clip(data, cenfunc=np.ma.median)
%timeit astropy_clip(data, cenfunc=np.ma.mean)
%timeit astropy_clip(data, cenfunc=np.median)
%timeit astropy_clip(data, cenfunc=np.mean)
```

Yields:
```python
1 loop, best of 3: 9.99 s per loop # cenfunc=np.ma.median
1 loop, best of 3: 1.54 s per loop # cenfunc=np.ma.mean
1 loop, best of 3: 2.17 s per loop # cenfunc=np.median
1 loop, best of 3: 1.49 s per loop # cenfunc=np.mean
```

Since `mean` is a much faster operation, this isn't entirely surprising.  What did surprise me is the slow down from the masked array implementation of the median.  I'm thinking doing whatever necessary operations on the masked array to take the median (sorting or whatever else) slow the computation down a lot.  In my case, I don't need to use masked arrays, or even the median, so I'm getting away with using `scipy.stats.sigmaclip` for now.  That said, using the non-masked array version (`np.median`) has performance that's at least close to the `np.mean` versions (less than 50% longer.  

### The Ugly
It should be noted that these are still not exactly apples to apples cases as, scipy's clipping iterates until no more points are clipped (convergence).  This is not necessarily true for astropy's clpping.  The default is to stop at 5.  Iterating to convergence seems to increase the runtime again by a factor of ~2.5, but obviously this depends on the sigma level, and data specfically.

**Comment by pllim** [comment]
Thank you for the detailed report! I am milestoning this to 3.1, the performance release, for obvious reason.

**Comment by astrofrog** [comment]
I ran into this today too

**Comment by crawfordsm** [comment]
Thanks @Vb2341 for this information.  Just for your information, convergence is also possible by setting `iters=None`, which would give a more direct comparison between the two. 

The `stats.sigma_clip` provides additional functionality as compared to `scipy.stats.sigmaclip`, but it would be useful to add a subset of this information into the documentation.  So my suggested to do list would be:
- [ ] Update doc string with a more informative pointer to `scipy.stats.sigmaclip`
- [ ] Update the user docs with more information about optimization and why a user may choose one over the other
- [ ] Review the code to see if in the most comparable version there is any way to optimize its performance while not limiting the functionality

**Comment by larrybradley** [comment]
@Vb2341 I significantly refactored the sigma clipping functions in #7478 to no longer use masked arrays internally.  For a 2048x4096 array, the new code is ~11.6x faster on my machine (with `bottleneck` installed).

There is also a detailed note in the docs stating that in the limited case where "... your data is a `ndarray` (i.e. not masked) with no invalid values and you want to use the mean as the centering function with axis=None and iterate to convergence" that `scipy.stats.sigmaclip` is faster than the equivalent settings in astropy.
