### ISSUE TITLE
Custom time format can't handle bidirectional conversions

### ISSUE THREAD

**Issue by jmason86** [astropy/astropy#7092]
There's an [example (the third one) in the docs for creating custom time formats, but it only seems to work in one direction](http://docs.astropy.org/en/stable/time/#writing-a-custom-format). Here, a time format called ```unix_leap``` is created that just changes the scale from utc to tai. The example then shows how you can convert from an ISO string to the new format, like this: 
```
t = Time('2000-01-01')
t.unix_leap
>>> 946684832.0
```
But if you then try to do the reverse operation using the normal syntax, it crashes: 
```
t2 = Time(946684832.0, format='unix_leap')
>>> ValueError: Input values did not match the format class jd

During handling of the above exception, another exception occurred:
....
ScaleValueError: Cannot convert from 'unix_leap' epoch scale 'tai'to specified scale 'tai', got error:
Input values did not match the format class jd
```

I also tried the second example, which creates a custom year day of year format, and that one does work bidrectionally. One difference I noticed is that in this second example, the custom class is subclassed (up a couple levels) from ```TimeUnique``` but the ```unix_leap``` example is (correctly) not. So maybe there's a hint in what may be going wrong?

**Comment by ayshih** [comment]
This now works – although I don't know with which release – so this issue can be closed.
