### ISSUE TITLE
New einsum failure from numpy-dev

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#7110]
While #7105 fixed one of the `einsum`-related issues, a separate one seems to have appeared in `numpy-dev`.  See https://travis-ci.org/astropy/astropy/jobs/331959806#L5209 for an example of it in action.

@mhvk @saimn - any ideas on whether this is related to the `optimize` changes or if it is something else?

**Comment by mhvk** [comment]
I don't think the numpy-side fixes have been merged yet. See https://github.com/numpy/numpy/pull/10352. I think the idea is that for 1.14.1, the default for `optimize` will revert to `False`, and that for 1.15 the bugs get ironed out...

**Comment by bsipocz** [comment]
So we shouldn't wait for this in the release?

**Comment by mhvk** [comment]
I think it pretty much guaranteed not to be in numpy 1.14.1, so this should not hold up 3.0.

**Comment by eteq** [comment]
@mhvk Ah, I misunderstood and thought the optimize was going to be fixed in 1.14.1...  So should we be worried still that `numpy-dev` is failing? That is, it *shouldn't* be failing if optimize=False is the deafult... In #7105 I specifcally singled out 1.14, *not* 1.14.x .  Should that be changed or do you think we can trust numpy 1.14.1 will be compatible in the ``optimize=False`` sense?

**Comment by mhvk** [comment]
@eteq - as far as I understand it, the default is going to be `optimize=False` for 1.14.1 onward, in which case our code should just work; by 1.15, the default may change back to `True`, but only when this bug is not present any more.

**Comment by pllim** [comment]
Haven't seen this in a while even with 1.16.dev, so closing.
