### ISSUE TITLE
ascii.write formats does not recognize size of column

### ISSUE THREAD

**Issue by cristobal-sifon** [astropy/astropy#7118]
Specifying `formats` in `ascii.write` produces numbers with the desired number of decimal places but not the total size of the column. For instance,
```python
print('astropy {0}'.format(astropy.__version__))
x = [np.random.uniform(-10,10,3),
    ('first_row', 'second_row', 'third_row_long_name')]
names = ('a','b')
formats = {'a': '%5.2f', 'b': '%20s'}
ascii.write(x, 'test.txt', names=names, formats=formats, overwrite=True)
!more test.txt
```
produces
```
astropy 2.0.3
a b
-5.47 first_row
9.81 second_row
-6.93 third_row_long_name
```
Instead I'd expect the file to look like this:
```
a b
-5.47            first_row
 9.81           second_row
-6.93  third_row_long_name
```

**Comment by pllim** [comment]
Hi. You can try to also include `format='fixed_width'` option in your `write()`. Supported formats are listed at http://docs.astropy.org/en/stable/io/ascii/index.html#id1 . This may also be useful: http://docs.astropy.org/en/stable/io/ascii/fixed_width_gallery.html

**Comment by cristobal-sifon** [comment]
fair enough, that works, thanks.
