### ISSUE TITLE
Magellanic coordinates

### ISSUE THREAD

**Issue by DanielLenz** [astropy/astropy#7119]
I've recently been working with Magellanic coordinates and was wondering if anyone was working on implementing this coordinate set in astropy.

The connection to the Galactic coordinate system is presented in [Nidever, Majewski, & Burton (2008)](http://adsabs.harvard.edu/abs/2008ApJ...679..432N). Additionally, there's a brief summary on the transformation [here](http://www.atnf.csiro.au/people/Tobias.Westmeier/tools_coords.php).

**Comment by adrn** [comment]
Hey @DanielLenz. I think this coordinate system might be too specific to go in to astropy (thoughts @eteq?). But, I have some other stream coordinate frames implemented in [gala](gala.adrian.pw) as astropy frames. I'd be happy to add the Magellanic coordinates to that package, if you'd be interested in contributing over there?

**Comment by DanielLenz** [comment]
Sure, let's do that instead!
