### ISSUE TITLE
Test failures on release 3.0rc2

### ISSUE THREAD

**Issue by aphearin** [astropy/astropy#7123]
Reporting two failures:

1. `test_of_address` in astropy/coordinates/tests/test_earth.py
2. `test_transform_to_nonscalar_nodata_frame` in astropy/coordinates/tests/test_frames.py

The `test_of_address` failure appears to be the same as #7057, and at the time of test execution I didn't find the other failure reported on [the wiki](https://github.com/astropy/astropy/wiki/v3.0-RC-testing), but maybe I just missed it. 

[failure_summary.txt](https://github.com/astropy/astropy/files/1667986/failure_summary.txt)

**Comment by bsipocz** [comment]
Thanks @aphearin.  Most of the RC1 failures in the wiki has been addressed.

**Comment by pllim** [comment]
@aphearin , I saw the second error testing RC1 as well but I thought it was resolved in #7105 ? Do you happen to be using Numpy dev?

**Comment by aphearin** [comment]
@pllim - I was using numpy 1.14 and scipy 1.0.0

**Comment by pllim** [comment]
Can you please check to see if #7105 fix is in your RC2 installation?

**Comment by aphearin** [comment]
I'm a bit under water today @pllim but I will check as soon as I come up for air.

**Comment by bsipocz** [comment]
@pllim - #7105 was included in 3.0rc2, but that failure looks very much like the one travis picks up with numpy dev, weird that we don't pick it up with the np 1.14 test.

**Comment by pllim** [comment]
@aphearin , I ran RC2 tests on my machine (xref #7130). I see `test_of_address` failure as before, but I don't see `test_transform_to_nonscalar_nodata_frame`. I have Numpy 1.14.0 and Scipy 1.0.0 as well.

**Comment by bsipocz** [comment]
On a 14.04 ubuntu VM, with python 3.6, np 1.4 and scipy 1.0, I also only see the first failure but not the second one.
