### ISSUE TITLE
Test failure with test_blackbody_scipy on 32-bit

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7129]
I'm seeing the following failure on the new 32-bit CircleCI set-up (#7126):

```python
_____________________________ test_blackbody_scipy _____________________________
[gw2] linux -- Python 3.6.4 /opt/python/cp36-cp36m/bin/python

    @pytest.mark.skipif('not HAS_SCIPY')
    def test_blackbody_scipy():
        """Test Planck function.
    
        .. note:: Needs ``scipy`` to work.
    
        """
        flux_unit = u.Watt / (u.m ** 2 * u.um)
        wave = np.logspace(0, 8, 100000) * u.AA
        temp = 100. * u.K
        with np.errstate(all='ignore'):
            bb_nu = blackbody_nu(wave, temp) * u.sr
        flux = bb_nu.to(flux_unit, u.spectral_density(wave)) / u.sr
    
        lum = wave.to(u.um)
        intflux = integrate.trapz(flux.value, x=lum.value)
        ans = const.sigma_sb * temp ** 4 / np.pi
>       np.testing.assert_allclose(intflux, ans.value, rtol=0.01)  # 1% accuracy

astropy/modeling/tests/test_blackbody.py:73: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x_id = True, y_id = False, hasval = 'nan'

    def chk_same_position(x_id, y_id, hasval='nan'):
        """Handling nan/inf: check that x and y have the nan/inf at the same
            locations."""
        try:
            assert_array_equal(x_id, y_id)
        except AssertionError:
            msg = build_err_msg([x, y],
                                err_msg + '\nx and y %s location mismatch:'
                                % (hasval), verbose=verbose, header=header,
                                names=('x', 'y'), precision=precision)
>           raise AssertionError(msg)
E           AssertionError: 
E           Not equal to tolerance rtol=0.01, atol=0
E           
E           x and y nan location mismatch:
E            x: array(nan)
E            y: array(1.804934)

/opt/python/cp36-cp36m/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py:706: AssertionError
```

@pllim - do you fancy investigating this? If you don't have time, I can take a look.

**Comment by pllim** [comment]
I see that it is not the only failure nor the only subpackage to fail under 32-bit. For this particular case, my hunch is that one or more values in `bb_nu` are NaNs, which causes `trapz` to spit out a NaN. This means one (or more) of the steps in `blackbody_nu` have overflow problem under 32-bit.

**Comment by pllim** [comment]
Update: After investigating within the CircleCI instance, here is the source of the problem: Somehow in 32-bit, `np.expm1` behaves as if `_has_buggy_expm1` is `True`, however, `_has_buggy_expm1` is set to `False` (L116 failed to catch it). As a result, for this test case, `boltzm1` in `blackbody_nu` contains both `np.inf` *and* `np.nan`, but the `np.nan` is not changed back to `np.inf` because the logic to fix it at `if _has_buggy_expm1` is skipped. And this is what eventually causes `trapz` to return a NaN, which causes the test to fail.

Proposed (hacky) solution: If 32-bit is detected, force `_has_buggy_expm1 = True` regardless.

I welcome more elegant solution(s) from people more knowledgeable than me about Numpy's 32-bit behaviors. Hope this helps.

**Comment by astrofrog** [comment]
@pllim - thanks for figuring this out! I followed up and found that we can trigger the bug on 32-bit with:

```
In [7]: np.expm1(1e10)
/opt/python/cp36-cp36m/bin/ipython:1: RuntimeWarning: overflow encountered in expm1
  #!/opt/_internal/cpython-3.6.4/bin/python3.6
/opt/python/cp36-cp36m/bin/ipython:1: RuntimeWarning: invalid value encountered in expm1
  #!/opt/_internal/cpython-3.6.4/bin/python3.6
Out[7]: nan
```

so I think we should update the ``_has_buggy_expm1`` to include an ``or`` statement to check if ``np.expm1(1e10)`` is ``nan``?

**Comment by astrofrog** [comment]
Note that ``np.expm1(1e20)`` works, it's just values in a specific range around 1e10 that don't work...

**Comment by astrofrog** [comment]
By the way, another solution is simply to assume it can be buggy on ANY platform and always do those checks for NaNs (not just 32-bit). Maybe a bit extreme?

**Comment by pllim** [comment]
@astrofrog , I thought your suggestion in https://github.com/astropy/astropy/issues/7129#issuecomment-361333843 was platform agnostic anyway, or did I misunderstand? Just adding that check regardless shouldn't hurt that much, so 👍 .
