### ISSUE TITLE
Bug in rounded negative sexagesimal output

### ISSUE THREAD

**Issue by jrthorstensen** [astropy/astropy#7141]
There is a bug in sexagesimal_to_string in astropy.coordinates.angle_utilities.
If a coordinate is negative, and is rounded by carrying a 60 up to the next field, the
sign is not handled correctly.   For example:
```python
>>> from astropy import coordinates as coo

>>> coo.angle_utilities.sexagesimal_to_string((-0.,59,59))
u'-0:59:59'
>>> coo.angle_utilities.sexagesimal_to_string((-0.,59,59),precision=0)
u'1:00:00'
>>> coo.angle_utilities.sexagesimal_to_string((-1.,59,59),precision=0)
u'0:00:00'
>>> coo.angle_utilities.sexagesimal_to_string((-2.,59,59),precision=0)
u'-1:00:00'
```
Apparently the value of the 'degrees' field is incremented even if it's negative.

This can be handled by splitting out the sign explicitly and making everything
positive at first (extending what is done presently with the minute and second fields
to the degree field as well), doing the formatting, and then tacking on the minus or 
plus sign at the end as needed.  

It might be worth carrying a sign explicitly in the sexagesimal representation.  This
other problem then could be avoided:
```python
>>> coo.angle_utilities.sexagesimal_to_string((-0,30,30),precision=0)
u'0:30:30'
```
... the integer -0 has the sign stripped away.

EDIT: Code formatting.

**Comment by mhvk** [comment]
@jrthorstensen - yikes, not good that something like that isn't caught by our tests. And your suggested fix makes sense. I'll try to have a PR shortly.

**Comment by mhvk** [comment]
ps. Am still using skycalc regularly - thanks!

**Comment by mhvk** [comment]
See #7148 for a fix.
