### ISSUE TITLE
New FITS table column attributes break existing code

### ISSUE THREAD

**Issue by stscirij** [astropy/astropy#7145]
Change in behaviour of binTableHDU.fromcolumns:

Version 2.0.3: passing a header containing keywords with names like "TCRPX2" to from_columns creates an hdu object with these keywords in the header

Version 3.dev: passing a header with such keywords results in them not making it to the header of the output

This code demonstrates:

```python
#! /usr/bin/env python
import astropy
from astropy.io import fits
import numpy as np

def test_fromcolumns():
    print(astropy.__version__)
    cd = create_column_descriptions()
    header = create_header()

    print("Header that is input to fits.BinTableHDU.from_columns:")
    print(header)

    hdu = fits.BinTableHDU.from_columns(cd, header)

    print("Header of hdu object returned from fits.BinTableHDU.from_columns:")
    print(hdu.header)

    return

def create_column_descriptions():
    col = []
    col.append(fits.Column(name="TIME", format="1E", unit="s"))
    col.append(fits.Column(name="RAWX", format="1I", unit="pixel"))
    col.append(fits.Column(name="RAWY", format="1I", unit="pixel"))
    cd = fits.ColDefs(col)

    return cd

def create_header():
    hdr = fits.Header()
    hdr['RA'] = (1.581250000000E+00, 'RA of reference aperture center ')
    hdr['DEC'] = (2.020277777778E+01, 'Declination of reference aperture center')
    hdr['TCTYP2'] = ('RA---TAN', 'axis type for dimension 1')
    hdr['TCTYP3'] = ('ANGLE   ', 'axis type for dimension 2')
    hdr['TCRVL2'] = (-999.0, 'sky coordinates of 1st axis')
    hdr['TCRVL3'] = (-999.0, 'sky coordinates of 2nd axis')
    hdr['TCRPX2'] = (1.0, 'axis1 pixel of tangent plane direction')
    hdr['TCRPX3'] = (1.0, 'axis2 pixel of tangent plane direction')
    hdr['TALEN2'] = (16384, 'length of axis 1')
    hdr['TALEN3'] = (1024, 'length of axis 2')
    hdr['TC2_2'] = (0.0, 'partial of first axis coordinate w.r.t. x')
    hdr['TC2_3'] = (0.0, 'partial of first axis coordinate w.r.t. y')
    hdr['TC3_2'] = (0.0, 'partial of second axis coordinate w.r.t. x')
    hdr['TC3_3'] = (0.0, 'partial of second axis coordinate w.r.t. y')
    hdr['TCUNI2'] = ('angstrom', 'units of first coordinate value')
    hdr['TCUNI3'] = ('deg     ', 'units of second coordinate value')

    return hdr

```

Edit: Added syntax highlighting.

**Comment by stscirij** [comment]
https://github.com/astropy/astropy/pull/6359
This PR changed the behaviour

**Comment by stscirij** [comment]
Possibly related to #6806

**Comment by pllim** [comment]
c/c @taldcroft @saimn @mhvk

**Comment by mhvk** [comment]
Hmm, yes, it may be that the machinery that tries to identify a column as a time is misbehaving. cc @aaryapatil.

**Comment by eteq** [comment]
Also, for context, note that this code breaks some of the HST pipelines, so it stands to reason it breaks other pipelines that use these keywords somehow.  So it's a significant regression, but I think it's "Affects-dev" because the issue states it's fine in 2.0.4 but breaks things in 3.x

**Comment by aaryapatil** [comment]
@mhvk I think you’re right. I am speculating that these keywords are being eaten up while creating fits columns, and are not making it to the header. I’ll look into it. Most probably, will be a minor change.

**Comment by saimn** [comment]
Previously these keywords (TCTYP, TCUNI, TCRPX, TCRVL) were simply ignored by `io.fits`, but since #6806 they are managed as other similar column keywords. Which means that their presence and value depend on the corresponding `Column` attribute, and that `io.fits` takes care of writing these keywords with the correct column number and order. 
So, it's indeed annoying that it breaks a pipeline (and that we didn't foresee this), but I don't think that's something we can fix in `io.fits`. I mean, I don't see how the code could be modified to be "backward compatible", and we cannot remove these keywords from the `Column` attributes without losing other features. So, sad to say, but the best solution I see is to fix the pipeline, using the column attributes (something like `fits.Column(name="RAWX", format="1I", unit="pixel", coord_type="RA---TAN", coord_ref_point=1., coord_ref_value=-999.)` *should* produce the correct header).

**Comment by stscirij** [comment]
I see that these keywords were added to the list of 'protected' keywords that aren't propagated, but did they need to be column attributes?  Since the keywords have a numeric identifier at the end of the keyword name to link them to a specific column number, what extra functionality do you get by making them column attributes?


On Feb 2, 2018 8:11 AM, Simon Conseil <notifications@github.com> wrote:

Previously these keywords (TCTYP, TCUNI, TCRPX, TCRVL) were simply ignored by io.fits, but since #6806<https://github.com/astropy/astropy/issues/6806> they are managed as other similar column keywords. Which means that their presence and value depend on the corresponding Column attribute, and that io.fits takes care of writing these keywords with the correct column number and order.
So, it's indeed annoying that it breaks a pipeline (and that we didn't foresee this), but I don't think that's something we can fix in io.fits. I mean, I don't see how the code could be modified to be "backward compatible", and we cannot remove these keywords from the Column attributes without losing other features. So, sad to say, but the best solution I see is to fix the pipeline, using the column attributes (something like fits.Column(name="RAWX", format="1I", unit="pixel", coord_type="RA---TAN", coord_ref_point=1., coord_ref_value=-999.) should produce the correct header).

**Comment by saimn** [comment]
`Column` attributes are the only way in `io.fits` to manage these column-related keywords. Thanks to this the column keywords are properly numbered (and ordered), and they are also used when the file is read. Without that you cannot be sure that the keywords are well synchronized with the table columns (what happens if you insert or remove a column in your case ?). 


```
In [1]: %astropy
Numpy 1.14.0
Astropy 3.1.dev21263

In [2]:     col = []
   ...:     col.append(fits.Column(name="TIME", format="1E", unit="s"))
   ...:     col.append(fits.Column(name="RAWX", format="1I", unit="pixel", coord_type='RA---TAN', coord_ref_point=1, coord_ref_value=-999))
   ...:     col.append(fits.Column(name="RAWY", format="1I", unit="pixel", coord_type='ANGLE', coord_ref_point=1, coord_ref_value=-999))
   ...:     cd = fits.ColDefs(col)
   ...: 
   ...: 

In [3]: cd
Out[3]: 
ColDefs(
    name = 'TIME'; format = '1E'; unit = 's'
    name = 'RAWX'; format = '1I'; unit = 'pixel'; coord_type = 'RA---TAN'; coord_ref_point = 1; coord_ref_value = -999
    name = 'RAWY'; format = '1I'; unit = 'pixel'; coord_type = 'ANGLE'; coord_ref_point = 1; coord_ref_value = -999
)

In [5]: fits.BinTableHDU.from_columns(cd).header
Out[5]: 
XTENSION= 'BINTABLE'           / binary table extension                         
BITPIX  =                    8 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                    8 / length of dimension 1                          
NAXIS2  =                    0 / length of dimension 2                          
PCOUNT  =                    0 / number of group parameters                     
GCOUNT  =                    1 / number of groups                               
TFIELDS =                    3 / number of table fields                         
TTYPE1  = 'TIME    '                                                            
TFORM1  = '1E      '                                                            
TUNIT1  = 's       '                                                            
TTYPE2  = 'RAWX    '                                                            
TFORM2  = '1I      '                                                            
TUNIT2  = 'pixel   '                                                            
TCTYP2  = 'RA---TAN'                                                            
TCRPX2  =                    1                                                  
TCRVL2  =                 -999                                                  
TTYPE3  = 'RAWY    '                                                            
TFORM3  = '1I      '                                                            
TUNIT3  = 'pixel   '                                                            
TCTYP3  = 'ANGLE   '                                                            
TCRPX3  =                    1                                                  
TCRVL3  =                 -999                                                  

In [6]: fits.BinTableHDU.from_columns(cd).writeto('test.fits')             

In [8]: hdu = fits.open('test.fits')[1]

In [9]: hdu.columns
Out[9]: 
ColDefs(
    name = 'TIME'; format = '1E'; unit = 's'
    name = 'RAWX'; format = '1I'; unit = 'pixel'; coord_type = 'RA---TAN'; coord_ref_point = 1; coord_ref_value = -999
    name = 'RAWY'; format = '1I'; unit = 'pixel'; coord_type = 'ANGLE'; coord_ref_point = 1; coord_ref_value = -999
)

In [11]: hdu.columns[1].coord_ref_value
Out[11]: -999
```

**Comment by stscirij** [comment]
I agree that adding these as column attributes does indeed give you that functionality, but it seems to me to have crossed a line from generic column properties (units, display format etc) to application-specific (i.e. with wcs functionality).  A case can be made for any column property to become an attribute, and then developers are going to be in the position of always playing catch-up as to whether their quantities should be in the header or the attributes.  I don't have a good solution to this other than perhaps to allow propagation of header keywords if they don't match a regex made from actual column attributes rather than the full superset of possible attributes.

Robert J.


On Feb 2, 2018 8:53 AM, Simon Conseil <notifications@github.com> wrote:

Column attributes are the only way in io.fits to manage these column-related keywords. Thanks to this the column keywords are properly numbered (and ordered), and they are also used when the file is read. Without that you cannot be sure that the keywords are well synchronized with the table columns (what happens if you insert or remove a column in your case ?).

In [1]: %astropy
Numpy 1.14.0
Astropy 3.1.dev21263

In [2]:     col = []
   ...:     col.append(fits.Column(name="TIME", format="1E", unit="s"))
   ...:     col.append(fits.Column(name="RAWX", format="1I", unit="pixel", coord_type='RA---TAN', coord_ref_point=1, coord_ref_value=-999))
   ...:     col.append(fits.Column(name="RAWY", format="1I", unit="pixel", coord_type='ANGLE', coord_ref_point=1, coord_ref_value=-999))
   ...:     cd = fits.ColDefs(col)
   ...:
   ...:

In [3]: cd
Out[3]:
ColDefs(
    name = 'TIME'; format = '1E'; unit = 's'
    name = 'RAWX'; format = '1I'; unit = 'pixel'; coord_type = 'RA---TAN'; coord_ref_point = 1; coord_ref_value = -999
    name = 'RAWY'; format = '1I'; unit = 'pixel'; coord_type = 'ANGLE'; coord_ref_point = 1; coord_ref_value = -999
)

In [5]: fits.BinTableHDU.from_columns(cd).header
Out[5]:
XTENSION= 'BINTABLE'           / binary table extension
BITPIX  =                    8 / array data type
NAXIS   =                    2 / number of array dimensions
NAXIS1  =                    8 / length of dimension 1
NAXIS2  =                    0 / length of dimension 2
PCOUNT  =                    0 / number of group parameters
GCOUNT  =                    1 / number of groups
TFIELDS =                    3 / number of table fields
TTYPE1  = 'TIME    '
TFORM1  = '1E      '
TUNIT1  = 's       '
TTYPE2  = 'RAWX    '
TFORM2  = '1I      '
TUNIT2  = 'pixel   '
TCTYP2  = 'RA---TAN'
TCRPX2  =                    1
TCRVL2  =                 -999
TTYPE3  = 'RAWY    '
TFORM3  = '1I      '
TUNIT3  = 'pixel   '
TCTYP3  = 'ANGLE   '
TCRPX3  =                    1
TCRVL3  =                 -999

In [6]: fits.BinTableHDU.from_columns(cd).writeto('test.fits')

In [8]: hdu = fits.open('test.fits')[1]

In [9]: hdu.columns
Out[9]:
ColDefs(
    name = 'TIME'; format = '1E'; unit = 's'
    name = 'RAWX'; format = '1I'; unit = 'pixel'; coord_type = 'RA---TAN'; coord_ref_point = 1; coord_ref_value = -999
    name = 'RAWY'; format = '1I'; unit = 'pixel'; coord_type = 'ANGLE'; coord_ref_point = 1; coord_ref_value = -999
)

In [11]: hdu.columns[1].coord_ref_value
Out[11]: -999

**Comment by eteq** [comment]
@stscirij, can you clarify exactly *which* of these keywords you consider to be the problem? That might make your last point clearer.

@saimn - it *is* a problem if this is a backwards incompatible change and it's not in the changelog as such. And usually for these sorts of things we have at least one major release with a deprecation warning. Might it be possible to pass through the keywords for 3.0 but raise deprecation warnings if they are used, and then remove in 3.1?

**Comment by astrofrog** [comment]
Is there a way we could make it so that accessing column-specific keywords in a header would dynamically fetch values from ``Column`` so that these are always in sync?

**Comment by saimn** [comment]
> A case can be made for any column property to become an attribute, and then developers are going to be in the position of always playing catch-up as to whether their quantities should be in the header or the attributes.

Yes, this is a tough problem given the number of possible column attributes. This makes me think about https://github.com/spacetelescope/PyFITS/issues/82 which was proposing to support arbritrary column attributes mapped to a `T*` keyword:

> This made me wonder whether it may be useful to support arbitrary keyword arguments in the constructor that would also create the corresponding FITS T* header keyword, e.g. a ucd argument would generate a TUCD header keyword for the column with the given str value, and a comm argument would generate a TCOMM header keyword for the column with the given str value etc.

This may be a solution, as the general paradigm in `io.fits`is that the user should manage the header by itself.

**Comment by saimn** [comment]
@eteq - Yes, I think we missed the backwards incompatibility change introduced by this PR, so the changelog should be updated. However I see no easy way to have a deprecation period. 

@astrofrog - That's probably a case where something like #7013 could be useful. But that's certainly not easy to do ...

**Comment by stscirij** [comment]
The specific keywords that are causing me a problem are in the test I posted: TCTYP2, TCTYP3, etc.  You will also notice that the TC2_2 and similar keywords are passed, but I can imagine that someone will at a later date decide that these should be column attributes and make another backward incompatible change.  That's why I'm raising this - it doesn't affect me THAT much and I can work around it, but it does seem like a) a line was crossed between making generic column attributes and application-specific column attributes that opens the door for ANY future properties to become attributes and b) the keywords are dropped silently from the header with no indication to the user of anything untoward.  It took me 3 days to track down why these keywords were disappearing from the headers of the files in my tests.  Also c), it was a backward incompatible change so I'd need release-specific code (or some try-except blocks) to make my code work under both astropy 2 and 3.
Sorry to bring this up so close to a release but I only just figured out the source of my differences yesterday.

**Comment by eteq** [comment]
@saimn - maybe I'm missing something, but why not revert to the 2.x behavior of not stripping the keywords, but then modify `Header.__getitem__` to raise a deprecation warning for those specific keywords?  Or alternatively, leave things alone in the keywords themselves, but modify `Header.__getitem__` to special-case those `T*` keywords?

I'm thinking @stscirij's case might be a "canary in a coal mine" - even if that particular case can be worked around easily, other users/pipelines might not be aware of this and all of a sudden have something break without a clue why.  This is to be avoided in feature releases if at all possible (as it tends to lead to a lot of user anger/unwillingness to upgrade...).

There's also the general "philosophical" problem that @stscirij points out that *some* of these keywords still make it through, so it's hard for the user to ever understand which are which.  Deprecating (or simply rolling back for 3.0.x) gives time to actually come up with a better guide for that without delaying the release...

**Comment by astrofrog** [comment]
*Possible* solution in https://github.com/astropy/astropy/pull/7153

**Comment by mhvk** [comment]
I like @astrofrog's approach of updating columns using the header passed in (am commenting here to keep the discussion together). It should also prevent future problems, where `from_columns(columns, header)` applies column information in the header to the columns if they do not already have that information.

**Comment by mhvk** [comment]
@stscirij - aside: in agreement that this is a major regression - thanks for reporting, now at least we have a chance to have it fixed before the real 3.0 is released!

**Comment by stscirij** [comment]
I ran my regression test with the fix and did indeed get some deprecation warnings. However the test still failed because the comments of the affected keywords aren't being propagated. This seems unavoidable under this scheme as the comment goes with the attribute, not the column.

**Comment by bsipocz** [comment]
I wonder how it would be possible to collect/trigger these kind of testings for the RCs. I've added a couple of affiliated packages to the bottom of the wiki, but knowing the test status for these critical pipelines would be very valuable, too.
