### ISSUE TITLE
TableDataDiff weirdness.

### ISSUE THREAD

**Issue by SaOgaz** [astropy/astropy#7154]
So I was trying to use `TableDataDiff` and ran into something a bit unusual.  There's a mis-match between the documentation on usage and the actual code, and I suspect the actual code needs to be changed to match the documentation.

The docs here: http://docs.astropy.org/en/stable/io/fits/api/diff.html say that the a and b input parameters for `TableDataDiff` behave just like the class `FITSDiff`, but the actual code never takes the a and b inputs and pulls out the binary table data, but attempts to reference it as binary table data.  If I ignore the documentation and feed `TableDataDiff` the binary tables directly it works as expected.

Now looking at the rest of the tailored diff functions, they all seem to want a and b to match `FITSDiff` style parameters (a string or a HDUList).  

I'm using stable release but it looks like latest is the same.

**Comment by saimn** [comment]
Just to be sure, you mean that `TableDataDiff` doesn't work with file names ? 
Looking quickly at the code, it seems that only `FITSDiff` reads files, but indeed all the HDU-specific classes take HDU objects as input. So in my understanding it's more a documentation issue.

**Comment by SaraOgaz** [comment]
Ahh, weird, I could have sworn when I was looking at the code that some of them added to the init to take in string filenames.  In that case, I suggest the doc string NOT just say "See `FITSDiff` for explanations of the initialization parameters.", and more clearly define the `a`  and `b` parameters for each version.

**Comment by abigailStev** [comment]
Pinging myself to fix this in the coming weeks.
