### ISSUE TITLE
Deprecate (and later remove) InheritDocstrings

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7167]
As mentioned by @saimn in https://github.com/astropy/astropy/issues/7162#issuecomment-363812024 , this feature is finally implemented upstream by Sphinx. When Sphinx minversion `>=1.7`, `InheritDocstrings` can be deprecated, to be removed in a future release afterwards.

sphinx-doc/sphinx#4126
sphinx-doc/sphinx#4129
https://github.com/sphinx-doc/sphinx/blob/0fb832baa54a791bbca0be620bad47b6c69b680c/CHANGES#L1326-L1327 -- In case of missing docstring try to retrieve doc from base classes (ref: sphinx-doc/sphinx#3140)

**Comment by bsipocz** [comment]
we  might be able to do this in 4.0, assuming we choose  a new enough min version of sphinx to support.

**Comment by pllim** [comment]
Looking at actual implementation at sphinx-doc/sphinx#4012 , the inheritance should "just work" without much messing around? 🤔

**Comment by pllim** [comment]
See #8881
