### ISSUE TITLE
Exception logging tests failing in ipython

### ISSUE THREAD

**Issue by embray** [astropy/astropy#717]
On both Astropy master and on the v0.2.x branch, when I run `astropy.test()` from an IPython prompt I get failures in the `test_exception_logging` and `test_exception_logging_origin` tests.

Based on what I can tell from the debugging I've done so far, upon first import the exception logging hook _does_ get installed properly through the IPython exception handling mechanisms.  But somewhere in the course of the tests (and this happens even when just testing the 'tests' package) `sys.excepthook` is being reset to the original built in hook.

**Comment by pllim** [comment]
We don't ask people to run test suite in IPython anyway for RC testing. I think @eteq is going to test if this is really still a problem to begin with, but if it is, maybe close it anyway as "won't fix".

**Comment by eteq** [comment]
This issue no longer exists as of the latest version of everything. But given the way this code interacts, I don't want to *promise* this forever, so I'm going to make a quick PR to re-word some of the items and that should close this issue.
