### ISSUE TITLE
Update paper 2 citation to accepted version

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#7171]
This issue is a reminder to update the citation file's reference to the 2018 Astropy paper to point to the final journal version, rather than the arXiv version.  The paper was still under review as of the 3.0.0 release so it was judged worth including the link to the arXiv at that time (#7158), but to be updated whenever there is a peer-reviewed journal to link to.

cc @bsipocz

**Comment by dstansby** [comment]
Bump to this now the paper seems to be out (congratulations 🎉 ). It would also be nice to add the refereed doi to the arXiv preprint.

**Comment by pllim** [comment]
Fixed by #7778 ?

**Comment by bsipocz** [comment]
Yes, indeed.
