### ISSUE TITLE
HDUList pop lazy loading problem

### ISSUE THREAD

**Issue by SaraOgaz** [astropy/astropy#7185]
pop on HDUList only works if you do something that circumvents the lazy loading on the FITS file.  Looked at this with @drdavella and he whipped up a new pop for the HDUList class.

**Comment by SaraOgaz** [comment]
Probably a separate issue, but has the same consequence for doing slices, and any other list built-ins actually...

**Comment by saimn** [comment]
I was confused between the issue and PR for the milestone, sorry!

**Comment by saimn** [comment]
> Probably a separate issue, but has the same consequence for doing slices, and any other list built-ins actually...

Slicing works (I tried without printing the hdulist list this time :smile: but maybe I miss use case?), but it is indeed possible that not all list methods work. Inheriting from `MutableSequence` could solve this more naturally, maybe something to investigate.

**Comment by SaraOgaz** [comment]
Double checked, slicing works if it's a single slice.  But there's a weird bug if you try to add two slices where it turns the object from an HDUlist to a regular list.

**Comment by ritiek** [comment]
> But there's a weird bug if you try to add two slices where it turns the object from an HDUlist to a regular list.

Just like I mentioned in https://github.com/astropy/astropy/issues/7211#issuecomment-366424404, we should also be able to fix this bug by overriding the `+` operator:

```python
class HDUList(list, _Verify):
    ...
    def __add__(self, hdulist):
        new_hdulist = self[:]
        new_hdulist.extend(hdulist)
        return new_hdulist
    ...
```

For example:
```python
>>> type(HDUList() + HDUList())
astropy.io.fits.hdu.hdulist.HDUList
```
