### ISSUE TITLE
quantity_helper causes RTD build to fail downstream

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7195]
#6852 somehow causes RTD failures for packages that has `from astropy import units` in the code, from which docstring needs to be rendered. Example: https://readthedocs.org/projects/ginga/builds/6742266/

**Comment by saimn** [comment]
Which version of scipy is used in the Ginga build ? I don't see it in the rtd-pip-requirements packages, so it probably use the system one which is probably too old (`scipy.special.loggamma` requires scipy 0.18)

**Comment by pllim** [comment]
OK I'll pin it and report back. Thanks!

**Comment by pllim** [comment]
Looks like spacetelescope/stsynphot_refactor@bd849d9 fixed its build. Thank you!

**Comment by saimn** [comment]
Good, so this means that scipy>=0.18 is now required for Astropy 3.0, maybe it should be mentioned in the docs.

**Comment by pllim** [comment]
Sounds fair. I'll open a separate issue for that. Thanks again!
