### ISSUE TITLE
DOC: scipy>=0.18 is needed for astropy 3.0

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7196]
This was found out by @saimn in #7195 and should be clearly documented.

xref https://docs.scipy.org/doc/scipy/reference/release.0.18.0.html#scipy-special-improvements

**Comment by bsipocz** [comment]
and also added to CI as we can't really state the minimum versions of optional dependencies in setup.py, or can we?

**Comment by pllim** [comment]
No, I don't think you can pin optional dependencies in `setup.py`. You can add it as a *comment* but it won't be enforced.

**Comment by apooravc** [comment]
So the requirement should be added in `docs/install.rst`, right? I'm not sure where to add in CI.

**Comment by guillochon** [comment]
This is causing issues for me, my RTD build does not include scipy at all in its requirements: https://readthedocs.org/projects/mosfit/builds/6774753/. Workaround is to just block astropy>=3 in my docs reqs right now, which is not ideal.

**Comment by pllim** [comment]
Yes, I agree that forcing `scipy` dependency on RTD build is not ideal. Given that `scipy` is an *optional* dependency of `astropy`, this should not happen. I'll think of a fix.

**Comment by saimn** [comment]
Scipy 0.18.0 was released on 25 Jul 2016, which is not so old, so indeed I think we should support older versions.

**Comment by pllim** [comment]
@guillochon -- #7219 is merged, so the RTD woes with `scipy < 0.18` should be gone when 3.0.1 is out. In the meantime, the interim solution is to use `astropy < 3` (like you did) or add `scipy>=0.18` to your RTD requirements. We apologize for any inconvenience caused.

**Comment by guillochon** [comment]
I <3 this solution @pllim, thanks!
