### ISSUE TITLE
Unit tests try to write to installed library directory

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#7201]
Some of the `astropy.io.fits` unittests try to write to a file in the installed library. This fails if one tries to run the test suite without write access to them, f.e. as an ordinary user for a system wide installation.

This makes the [continuous integration test](https://ci.debian.net/packages/a/astropy/unstable/amd64/) of Astropy in Debian fail. From the [test log](https://ci.debian.net/data/autopkgtest/unstable/amd64/a/astropy/20180214_211941/log.gz):
```
________________________ TestConvenience.test_tabledump ________________________

self = <astropy.io.fits.tests.test_convenience.TestConvenience object at 0x7fb86e205dd8>

    def test_tabledump(self):
        """[...]"""
        # test without datafile
        filename = self.data('tb.fits')
>       fits.tabledump(filename)

/usr/lib/python3/dist-packages/astropy/io/fits/tests/test_convenience.py:149: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3/dist-packages/astropy/utils/decorators.py:487: in wrapper
    return function(*args, **kwargs)
/usr/lib/python3/dist-packages/astropy/io/fits/convenience.py:896: in tabledump
    f[ext].dump(datafile, cdfile, hfile, overwrite)
/usr/lib/python3/dist-packages/astropy/utils/decorators.py:487: in wrapper
    return function(*args, **kwargs)
/usr/lib/python3/dist-packages/astropy/io/fits/hdu/table.py:1103: in dump
    self._dump_data(datafile)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <astropy.io.fits.hdu.table.BinTableHDU object at 0x7fb86c084f60>
fileobj = '/usr/lib/python3/dist-packages/astropy/io/fits/tests/data/tb_1.txt'

    def _dump_data(self, fileobj):
        """[...]"""
    
        if not fileobj and self._file:
            root = os.path.splitext(self._file.name)[0]
            fileobj = root + '.txt'
    
        close_file = False
    
        if isinstance(fileobj, str):
>           fileobj = open(fileobj, 'w')
E           PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/astropy/io/fits/tests/data/tb_1.txt'

/usr/lib/python3/dist-packages/astropy/io/fits/hdu/table.py:1214: PermissionError
___________________ TestFileFunctions.test_open_file_handle ____________________

self = <astropy.io.fits.tests.test_core.TestFileFunctions object at 0x7fb86e2351d0>

    def test_open_file_handle(self):
        # Make sure we can open a FITS file from an open file handle
        [...]
        # Opening without explicitly specifying binary mode should fail
        [...]
    
        # All of these read modes should fail
        for mode in ['r', 'rt', 'r+', 'rt+', 'a', 'at', 'a+', 'at+']:
            with pytest.raises(ValueError):
>               with open(self.data('test0.fits'), mode=mode) as handle:
E               PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/astropy/io/fits/tests/data/test0.fits'

/usr/lib/python3/dist-packages/astropy/io/fits/tests/test_core.py:613: PermissionError
```

**Comment by pllim** [comment]
One way to get around this is to provide a `datafile=self.temp('tb_1.fits')` option, which would write it to a temporary directory instead. However, that changes the intention of the test.

Another way is to catch `PermissionError` and then set it to `xfail`.

**Comment by pllim** [comment]
For the second one, I think all you can do is catch `PermissionError` and set it to `xfail`, unless `pytest.raises` can accept more than one error name with OR condition (this is not clear from `pytest` documentation.

**Comment by saimn** [comment]
Or the fits file should be copied to the temp directory to avoid this issue.

**Comment by mangalagb** [comment]
Hello, I am new to astropy. I'm picking up this bug to work on.

**Comment by mangalagb** [comment]
Has this issue been fixed? The failure does not occur in the latest continuous integration test log.

**Comment by olebole** [comment]
Do you mean in Debian/Ubuntu? No, I just [disabled the tests](https://salsa.debian.org/debian-astro-team/astropy/blob/8b8364dc8404f4875986e79222887e00a8bef577/debian/patches/Mark-all-known-test-failures-as-xfail.patch#L11-36) until an upstream solution is found. This is how I usually deal with bugs in the test framework. When you have a working pull request, I will replace the disabling with your patch.

**Comment by mangalagb** [comment]
I am running the test_convenience.py test as 
```python3 setup.py test -t astropy/io/fits/tests/test_convenience.py --args "-s"```. 

I confirmed that it is not being run as root (My ```os.getuid()``` is non-zero). Yet I get no errors in the method. Is this because as mentioned in the documentation "Note also that this test runner(setup.py test) actually installs astropy into a temporary directory and uses that for running the tests. "?

If so, when I try to run as ```astropy.test(test_path='astropy/io/fits/tests/test_convenience.py')```, I get ```ImportError: cannot import name 'cparser'``` which tells me that setup.py is required to parse and include C files.

Can I have some help with this?

**Comment by olebole** [comment]
I run the tests within astropy:
```
import astropy
res = astropy.test()
exit(res)
```

**Comment by mangalagb** [comment]
I do the exact same thing and I still get ```cannot import name 'cparser'```
Am I missing some dependency?
![screen shot 2018-03-07 at 7 21 50 pm](https://user-images.githubusercontent.com/2840376/37125986-fe52bfe2-223c-11e8-94b8-2f2bd2b5e45f.jpg)

**Comment by olebole** [comment]
Did you install astropy with `python3 setup.py install ...` before?

**Comment by mangalagb** [comment]
Doing this has solved my issue. Thanks a lot.
