### ISSUE TITLE
KeyError when converting a Table to a VOTableFile and back

### ISSUE THREAD

**Issue by funbaker** [astropy/astropy#7203]
Astropy version: latest/3.0

I'm generating a VOTableFile from a Table instance for testing purposes in pyvo.

```
def _votablefile():
    table = Table([
        [23, 42, 1337],
        ['Illuminatus', "Don't panic, and always carry a towel", 'Elite']
    ], names=('1', '2'))

    table['1'].meta['ucd'] = 'foo;bar'

    table['2'].meta['utype'] = 'foobar'

    votablefile = VOTableFile.from_table(table)

    return votablefile
```

When calling ``to_table()`` on this ``VOTableFile``, a ``KeyError`` is raised because it can't find the implicity generated column name '_1':

I guess this is because ``array.dtype.names`` is not updated in the else branch below:

https://github.com/astropy/astropy/blob/dc5be7efb50c7a52e33871ca0624374fa709a8a2/astropy/io/votable/tree.py#L2853-L2874

**Comment by pllim** [comment]
Did it work in older version?

**Comment by pllim** [comment]
How exactly are you calling `to_table`? `VOTableFile` itself does not have a `to_table` method.

Also, the `to_table` method does have a `use_names_over_ids` keyword option, which you can set to `True` to avoid the pesky `else` logic block.

**Comment by funbaker** [comment]
The latest version i can get pytest running is v2.0.3, and it doesn't work there too.

I mean ``to_table()`` from ``astropy.io.votable.tree.Table``, sorry.

``use_names_over_ids`` would propably work (and is the only option for now), but i also would need to overwrite the default behaviour in order to get it working, and this feels like a bad idea.

I will try to fix it with updating ``array.dtype.names`` and create a PR afterwards for discussion.

**Comment by pllim** [comment]
The reason I asked was because I got the `KeyError` at `get_first_table`, not `to_table`, so I am not sure how you got that far. Yes, a PR sounds good. Thank you!

**Comment by funbaker** [comment]
Closed because merged
