### ISSUE TITLE
HDUList.copy() returns a list

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7211]
Currently ``HDUList.copy()`` returns a list rather than an ``HDUList``:

```python
In [1]: from astropy.io.fits import HDUList

In [2]: hdulist = HDUList()

In [3]: hdulist.copy()
Out[3]: []

In [4]: type(_)
Out[4]: list
```

This is with Python 3.6.

**Comment by drdavella** [comment]
This might be related to another issue reported in #7185 where adding two `HDUList`s also produces a `list` instead of another `HDUList`.

**Comment by ritiek** [comment]
We should be able to fix this specific case by overriding `list.copy()` method with:
```python
class HDUList(list, _Verify):
    ...
    def copy(self):
        return self[:]
    ...
```

And the result:
```python
>>> type(HDUList().copy())
astropy.io.fits.hdu.hdulist.HDUList
```
