### ISSUE TITLE
Refactor modeling code

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7220]
Originally https://github.com/astropy/astropy/pull/7204#issuecomment-367093577

I guess I should mention that I am working on a large update to models (first to see if it works; I didn't want to get bogged down in discussions about whether this or that behavior or feature was right). I can summarize that elsewhere. My initial work was to change how parameters worked, and it turned out that the current implementation of compound models was essentially inconsistent with that, I folded in the new approach to compound models I had discussed with some. But in working with the unit unit [yes] tests I saw there were some problems with units and so started thinking about those (making no changes so far).

But I'll take this as an opportunity to state my opinion on how units should work (as well as I understand them). This is often different than the current unit behavior or plans for unit behavior.

First, a general statement about priorities. To me, by far the most important use for units is convenience in use in evaluating models. [break to get my armor on] I would give support for units in fitting relatively low priority. In fact, I'd suggest dropping support for use with fitting.

Here are some proposals for changing behavior of units in the current package:

At the parameter level:

I find the current raw_unit naming to be confusing. I'd suggest changing that to internal_unit. That is to say, unit is what the user supplies, internal_unit is the value in the unit system the Parameter expects (dealt with through the _setter and _getter methods. The model evaluation expects to use the internal_unit representation. Currently the most common use of this is conversion between degrees and radians (degrees for the user, radians internally). This is basically just a naming issue.

One thing I think should change is that it should not be possible to assign new units to a Parameter instance (E.g. this currently works:
```python
g = Gaussian1D(1 * u.J, 1 * u.m, 0.1 * u.m)

g.amplitude = 2 * u.s
g.mean = 2 * u.Jy
```
I can't see the justification for allowing this. If a model with different unit support is needed, make a new one, don't mutate an existing one. Seems like this is asking for trouble.

At the models level:

* input_units is not required (it can be None), but if it is supplied, output_units must be supplied (I'm suggesting that instead of returned_units for consistency with other uses of the name in the code). It cannot be changed once instantiated (the model code can override this if it wants if it knows that there is a direct relation between some parameters and the input).
* get rid of input_units_strict. Always convert to input_units
* get rid of input_units_dimensionless. Allowing this when units are expected is likely to cause many errors of usage. Just force people to be explicit with the inputs if input_units exists
* output_units can be changed after instantiation

Regarding enforcement of unit consistency. Basically I'm suggesting that there isn't any in instantiation. People should be free to mix parameters with units and those without (Gaussian1D is a good example where amplitude does not need to have units even if mean and stddev do. Likewise the user is free to define input_units or output_units to be inconsistent with the model and parameters. And they are free to provide Parameter units that are inconsistent. These sorts of errors will raise an exception on evaluation. We should provide tools in the classes or package to make it easy to identify what caused the error and where it would have happened in a compound expression. I would like to avoid loading the code with lots of analysis about what is consistent (or unnecessary test evaluations) or be overly restrictive about what is permitted.

c/c @nden

**Comment by nden** [comment]
Resolved in #8769
