### ISSUE TITLE
sigma_clip fails when given a tuple for the axis parameter

### ISSUE THREAD

**Issue by jehturner** [astropy/astropy#7227]
The `astropy.stats.sigma_clip` function has an `axis` parameter "like the `numpy` functions", which gets passed through to the back-end `cenfunc` and `stdfunc`. Unlike those numpy functions, however, `sigma_clip` fails when the value is a *tuple* of axis numbers. This is consistent with its own documentation, but differs from the "standard" numpy behaviour and prevents useful applications such as clipping model sets or the planes of an IFU datacube etc.

Eg. compare with https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html.

I have a fix for this in #7199 (which I'll push once I have this issue number). From a quick check, this introduces an overhead of no more than ~5% for a tiny (3x4) array -- only when `axis` is not the default of `None` -- and negligible overhead for a larger (512x4176) array. 

PS. This is needed as part of the solution for #6819.

**Comment by jehturner** [comment]
It looks like there are also other functions in `stats` with an `axis` parameter that assume the value is an integer. I'm already going down a rabbit hole fixing one thing after another in `modeling` though and don't plan to change any other stats functions right now (especially when I'm not using them)... I would argue that handling more general `axis` values in `sigma_clip` is an important case and it's better to have that now than to wait for consistency everywhere. In particular, we need to be able to exclude the `model_set_axis` when clipping model sets (in >= 2D), because each model needs its own stats and looping over them takes 10x as long (and it's already slow before that).

It's debatable whether this is a bug, since the behaviour was consistent with its documentation, but it does block standard numpy functionality that one might reasonably expect to work (and the docs themselves say "(like the numpy functions)").

**Comment by saimn** [comment]
I did something similar for mad_std and median_absolute_deviation in #5835, and thought that sigma_clip already handles multi-dimensional axis but apparently not. So :+1: for me.

**Comment by jehturner** [comment]
This is fixed in master by #7199.
