### ISSUE TITLE
Tries to regenerate units/format/generic_lextab.py (which may be readonly)

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#7228]
I am not sure whethere that is a real bug, or I made a mistake when creating the Debian package of 2.0.4/3.0: Sometimes, I now get [warnings like](https://ci.debian.net/data/autopkgtest/unstable/amd64/p/python-drizzle/20180221_205055/log.gz):
```
WARNING: yacc table file version is out of date
WARNING: Couldn't create 'astropy.units.format.generic_parsetab'. [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/astropy/units/format/generic_parsetab.py'
WARNING: Couldn't write lextab module 'astropy.units.format.generic_lextab'. [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/astropy/units/format/generic_lextab.py'
```
This happens when I try to use an (read-only) installed astropy, in this case from [python-drizzle](https://github.com/spacetelescope/drizzle).
This seems to be not really specific to 2.0.4/3.0 as an [earlier test](https://ci.debian.net/data/autopkgtest/unstable/amd64/p/python-drizzle/20180220_160335/log.gz) did not show this behaviour. The difference between the two is an upgrade of PLY from 3.9 to 3.11.

**Comment by astrofrog** [comment]
@olebole - the tables were generated with 3.10, so I think it could be a version mismatch since you are using 3.11

**Comment by olebole** [comment]
So, are they version dependent and should be regenerated with every new version?

**Comment by astrofrog** [comment]
@olebole - I think that they get regenerated if the PLY version doesn't match the version stored in the generated files.

**Comment by olebole** [comment]
@astrofrog sure; however this is not possible when astropy is installed system wide. Is this a problem or will it work with the old version?

**Comment by astrofrog** [comment]
@olebole - I'm not sure, does the test suite pass despite the warnings? I think the correct fix is probably to pin the dependency on PLY 3.10 to avoid getting mismatched versions.

**Comment by astrofrog** [comment]
Just to clarify, these warnings come from PLY itself and are beyond our control: https://github.com/astropy/astropy/blob/a92043d2d42cc0ab04b2c3a25cc4dff9ba025da3/astropy/extern/ply/yacc.py#L1986

**Comment by olebole** [comment]
@astrofrog The test in python-drizzle passes. I opened an issue at ply to check with them.

**Comment by bsipocz** [comment]
Oh, nice. Now that we've just updated to 3.10, they are out with 3.11...

**Comment by olebole** [comment]
It appears that has a Debian specific solution (which creates a versionized dependency on ply), so there is nothing to do for astropy now.
