### ISSUE TITLE
Add extra formats to fits IO column objects?

### ISSUE THREAD

**Issue by SaraOgaz** [astropy/astropy#7230]
Let me start this with saying I have NO idea if this is the right solution for the other work I need to do.  I was wondering if we could expand the fits2numpy and numpy2fits formats to include the following formats defined in the TDISPn values (taken from Fortran). 

https://github.com/astropy/astropy/blob/8ad19c68ddbc2ac33eaf90c1ff988991bbdcc745/astropy/io/fits/column.py#L40

This is to work on #7226  where I'm trying to get the TDISPn keywords from a FITS binary table header to read into the FITS table `Column.format` attribute.

The Valid TDISPn formats are here (the ones that aren't currently working are O,Z,F,G (octal, hexadecimal, floatingpoint(fixed decimal), general)

![](https://user-images.githubusercontent.com/311639/36552360-f65822f2-17f9-11e8-8836-cc6a5e2f96dd.png)

**Comment by mhvk** [comment]
@SaraOgaz - I think those are strictly for the way the content is stored (float32, int8, etc.), not for the mapping of display format. Indeed, this seems true generally, though there is a note in l.968 stating:
```
        # TODO: Add full parsing and validation of TDISPn keywords
```

**Comment by mhvk** [comment]
I think it would indeed have to be in the `TODO` section, and writing a properly formatted `format` attribute for the table `Column`. The translation must be available elsewhere already, since, e.g., Vizier tables use a format definition that also relies on FORTRAN formats...  Since the `cds` reader was written by @taldcroft, maybe he has suggestions... .. .. aside: there is a `fortranformat` package, but it seems overkill here.

**Comment by taldcroft** [comment]
Sorry to disappoint, but the implementation in the CDS reader is very bare-bones and probably not helpful.  It only pays attention to the type for a few cases (E, I, A, F), and ignores formatting info.  See the `get_type_map_key()` method here:

https://github.com/astropy/astropy/blob/e6d1a9e4775544a18e06fb965d0d7b6afac6edf4/astropy/io/ascii/cds.py#L25

**Comment by mhvk** [comment]
OK, that is not so helpful indeed. But one nice thing is that this can very easily be done in stages. E.g., for `F`, `E`, and `G`, really all that's needed is to move the format letter to the end and make it lower case.  And for the simplest form of `I` (without the `.w`), one just replaces it with a `d` at the end. (At least, I think that is true... Maybe a closer look at `fortranformat` is warranted

**Comment by SaraOgaz** [comment]
I'm *pretty* sure astropy wouldn't want to make the `fortranformat` stuff a dependency, it looks like it hasn't been updated since 2014.  I'm going try and write something from scratch and see how difficult it is.  Won't know about the weird/tricky formats until I try.

**Comment by SaraOgaz** [comment]
Content moved to PR @7226.  It was decided that there was too many unresolved issues to do this at the moment.

**Comment by pllim** [comment]
xref #7226
