### ISSUE TITLE
quantity_allclose can not be imported without pytest installed

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#7235]
```python
>>> from astropy.tests.helper import quantity_allclose
  File "/opt/miniconda/envs/clean/lib/python3.6/site-packages/astropy/tests/helper.py", line 14, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

Is this a recent change? I feel these "all close" helpers should be somewhere else? I am happy to PR this if people agree.

**Comment by drdavella** [comment]
I agree. In my opinion, code should go in `astropy.tests` only if it is intended to only ever be used in  test code. Other functions that have applications in actual 'production' code should probably be put in `astropy.utils`.

If you move these functions somewhere else, it's probably still a good idea to allow them to be imported through `astropy.tests.helper` to preserve API compatibility.

**Comment by pllim** [comment]
`quantity_allclose` should actually be moved to `units` (not `utils`) if you want to move it anywhere.

Although, I wonder we should leave a `assert_quantity_allclose` in the test helper, to be analogous with `numpy.testing`. :thinking:

**Comment by pllim** [comment]
p.s. The current one in helper would need to be deprecated first, not completely removed.

**Comment by rohanrajpal** [comment]
I'll take this up.This would be my first bug fix, so would take a little more time than usual simple fixes take.

**Comment by rohanrajpal** [comment]
i shall ask my doubts here?or on the mailing list?

**Comment by bsipocz** [comment]
@rohanrajpal - If it's related to this issues, it's best to keep it in here. If it's related on setting up the developer environment, etc, you may want to ask on the slack channel or here.

**Comment by rohanrajpal** [comment]
@pllim @drdavella @Cadair  from what i can understand from this discussion 
There are two things that either have to be moved or edited
one is 'quantity_allclose',and the other is 'assert_quantity_allclose' in astropy.tests.helper
What do you exactly mean by deprecated ,should the assert function remain and the other one moved to units.
And in which file in units shall i make changes?

**Comment by pllim** [comment]
> What do you exactly mean by deprecated

Use the `@deprecated` decorator on the function to be deprecated. See http://docs.astropy.org/en/latest/api/astropy.utils.decorators.deprecated.html#astropy.utils.decorators.deprecated .

> And in which file in units shall i make changes?

@mhvk , what do you think? Should we move `quantity_allclose` to `astropy/units/quantity_helper.py` or `astropy/units/utils.py`?

> And as a test...

`from astropy.tests.helper import quantity_allclose` would now raise `AstropyDeprecationWarning` but `from astropy.units.??? import quantity_allclose` would not have any error.

**Comment by mhvk** [comment]
I agree with only moving `quantity_allclose`; `assert_*` belongs in `testing` (though it might as well be in a file that does not require `pytest` -- but let's leave that for another PR).

For `quantity_allclose`, I would probably move it to `quantity.py` -- as is, both `utils.py` and `quantity_helper.py` are specifically for in-module helpers that are not meant to be exposed.

I would move the helper function`_unquantify_allclose_arguments` to `utils.py`

One question before it is done: should it just become `allclose` (i.e., in typical usage, one would have `u.allclose(q1, q2)`)? It is such a simple front-end to `allclose` -- and does work with regular arrays as well -- that one could do it like that.

**Comment by Cadair** [comment]
:+1: for `u.allclose` would also be nice to have `u.isclose` which is pretty trivial as long as `unquantify_allclose_arguments` is along for the ride.

**Comment by rohanrajpal** [comment]
@pllim i did deprecate the function but the` import pytest` command is still there and still gives the error 
```
>>> from astropy.tests.helper import quantity_allclose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rohan/gsoc/astropy/astropy/tests/helper.py", line 13, in <module>
    import pytest
ImportError: No module named 'pytest'

```
I tried finding the pytest file and it seems be somewhere else ,not in the same folder as helper.py

@mhvk I have successfully moved the `quantity_allclose` to quantity.py and the command `astropy.units.quantity import quantity_allclose` passes without any errors or warnings

**Comment by rohanrajpal** [comment]
Alright, I fixed the pytest error(didn't install it properly).Now I'm getting a deprecation warning when I try to use that imported function.
Anything besides this that requires a fix?

**Comment by Cadair** [comment]
@rohanrajpal I would open a PR so we can comment on your changes and see what else (if anything) needs to be done.

**Comment by rohanrajpal** [comment]
you would review it right, don't I have to make a pull request?

**Comment by pllim** [comment]
@rohanrajpal , right, *you* will be the one making the pull request if you are still interested to tackle this.

Yes, I think `ImportError` would still be a problem for the *deprecated* `quantity_allclose` (but if `pytest` is installed, it would then raise a deprecation warning). However, `quantity_allclose` that is moved to the new location would not have `ImportError` nor warning.

In fact, to minimize code duplication, you can have the *deprecated* function simply calls the one at new location.

Hope this clarifies the matter.

**Comment by dstansby** [comment]
Does anyone know which version(s) this is fixed in?

**Comment by pllim** [comment]
Try 3.0.2 or later.
