### ISSUE TITLE
Add support for FITS FOREIGN convention

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#7239]
The [FOREIGN convention](https://fits.gsfc.nasa.gov/registry/foreign.html) is used to encapsulate arbitrary files or sets of files inside of a FITS HDU. It is a registered convention and is well documented.

While it is not widely used, I have a particular use case in mind, and it would be useful if Astropy provided support for processing FOREIGN HDUs. Right now, when reading a file with a FOREIGN HDU, Astropy interprets it as a `NonstandardExtHDU`, which is perfectly reasonable. However, I don't believe there is currently any way to create and/or validate a FOREIGN HDU using Astropy.

Before I actually do the work and submit a PR, I want to make sure this is a reasonable feature request. The main question is whether Astropy is okay with being on the hook for fully supporting the FOREIGN convention.

**Comment by saimn** [comment]
If there is a registered convention then yes sure, it seems reasonable to support this.
I also saw recently that there is the FitsHDU class which does something very similar (XTENSION=FITS):
https://github.com/astropy/astropy/blob/master/astropy/io/fits/hdu/nonstandard.py

**Comment by drdavella** [comment]
@saimn yes the `FITS` convention is very similar, but it's technically not general enough for my purposes.

Implementing this may require some refactoring of the `NonstandardExtHDU`, which I hope will lead to a bit cleaner code.

**Comment by drdavella** [comment]
Closing since there is not currently sufficient motivation to support the entire convention within Astropy. It turns out that I can implement a subset of the functionality within my own package. Feel free to reopen in the future if this would be useful for anyone else.
