### ISSUE TITLE
Implement low-level API from APE 14 in astropy.wcs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7245]
Now that APE 14 is accepted:

https://github.com/astropy/astropy-APEs/blob/master/APE14.rst

we should build a wrapper for ``WCS`` that exposes the low-level API, or implement the low-level API directly on the WCS object.

**Comment by Cadair** [comment]
:+1: for implementing the API right on `wcs.WCS`.

**Comment by pllim** [comment]
Any chance this can make it in 3.1? If so, we should add to project board. :clap:

**Comment by astrofrog** [comment]
I'm going to take a stab at starting this.

**Comment by pllim** [comment]
Isn't this done already?

**Comment by astrofrog** [comment]
It is - good catch!
