### ISSUE TITLE
False positive: "WARNING: VerifyWarning: Invalid 'BLANK' keyword in header."

### ISSUE THREAD

**Issue by malikolivier** [astropy/astropy#7253]
## How to reproduce

Load the following test FITS file containing a *BLANK* value set to "1" in its header (appended .txt to upload it on github):
[test.mob.fits.txt](https://github.com/astropy/astropy/files/1774998/test.mob.fits.txt)

```py
from astropy.io import fits
fits.open('test.mob.fits.txt')
```

The following warning will be printed.

```
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
```

## Expected behaviour

The FITS standard says that *BLANK* shall be an integer [[1](https://heasarc.gsfc.nasa.gov/docs/fcg/standard_dict.html)].
The FITS standard defines an integer as "An integer consists of a `+' (hexadecimal 2B) or `-' (hexadecimal 2D) sign, followed by one or more ASCII digits (hexadecimal 30 to 39), with no embedded spaces." [[2](http://archive.stsci.edu/fits/fits_standard/node33.html#SECTION00923000000000000000)]

The FITS file I attached should be compliant, as such no warning should be printed.

## Versions

- Python: 3.6.3
- astropy: 3.0
- OS: Ubuntu 17.10

[1] https://heasarc.gsfc.nasa.gov/docs/fcg/standard_dict.html
[2] 5.2.3 Integer Number: http://archive.stsci.edu/fits/fits_standard/node33.html#SECTION00923000000000000000

**Comment by saimn** [comment]
As stated in the warning message, *The 'BLANK' keyword is only applicable to **integer** data*. Your data is float (BITPIX  = -32), hence the warning.
Also from the FITS standard, section 5.3:
> The BLANK keyword should not be used when
BITPIX = -32 or -64; rather, the IEEE NaN should be
used to represent an undefined value.
