### ISSUE TITLE
TypeError when using astropy.io.votable.validate( ... , xmllint=True) 

### ISSUE THREAD

**Issue by mmebsout** [astropy/astropy#7255]
When xmllint = True, 
validation goes through **astropy.io.votable.table.py** line 306 
```
 if xmllint and os.path.exists(filename):
        from ...utils.xml import validate

        if votable is None:
            version = "1.1"
        else:
            version = votable.version
        success, stdout, stderr = validate.validate_schema(
            filename, version)
```
Where **astropy.utils.xml.validate.py** validate_schema is called with schema_file as the votable version - like "1.1" for example
`validate_schema(filename, schema_file):`
```
    base, ext = os.path.splitext(schema_file)
    if ext == '.xsd':
        schema_part = '--schema ' + schema_file
    elif ext == '.dtd':
        schema_part = '--dtdvalid ' + schema_file
    else:
        raise TypeError("schema_file must be a path to an XML Schema or DTD")
```
Thing being that xml.validate.py validate() is expecting a ".xsd" or a ".dtd" and throws a TypeError exception line 42 otherwise. 

table.py should be calling **astropy.io.votable.xmlutil.py** validate_schema() instead. 
`validate_schema(filename, version='1.1'): ...`

**Comment by pllim** [comment]
Does it work when you simply type `volint <filename>` in the command line? Also, just for clarity, which Astropy version are you using? Thank you.

**Comment by mmebsout** [comment]
I have astropy 2.0.1

and I run python script.py in the command line
```
import astropy.io.votable
astropy.io.votable.validate(source="file.xml", xmllint=True)
```
------------------
But indeed, when I use volint file.xml in the command line I don't get the error. 
I don't get any xmllint validation message though I'm not sure how to check that.

Here is the feed :
```
$ volint file.xml 2>1

Validation report for file.xml

3: W22: The DEFINITIONS element is deprecated in VOTable 1.1.
  Ignoring
<DEFINITIONS>
^

4: W27: COOSYS deprecated in VOTable 1.2
  <COOSYS ID="J2000" equinox="J2000." epoch="J2000." system="eq_FK5"/>
  ^

13: W06: Invalid UCD 'POS_EQ_RA_MAIN': Unknown word 'POS_EQ_RA_MAIN'
        <FIELD name="RAJ2000" ucd="POS_EQ_RA_MAIN" ref="J2000" data...
        ^

18: W06: Invalid UCD 'POS_EQ_DEC_MAIN': Unknown word
  'POS_EQ_DEC_MAIN'
        <FIELD name="DECJ2000" ucd="POS_EQ_DEC_MAIN" ref="J2000" da...
        ^

53: W06: Invalid UCD 'ID_MAIN': Unknown word 'ID_MAIN'
        <FIELD name="ID" ucd="ID_MAIN" datatype="char" arraysize="*">
        ^

65: W30: Invalid literal for float 'SPT-CL'.  Treating as empty.
                <TD>SPT-CL J0000-4356</TD>
                    ^

65: W30: Invalid literal for float 'J0000-4356'.  Treating as empty.
                <TD>SPT-CL J0000-4356</TD>
                    ^
```

**Comment by pllim** [comment]
Astropy 2.0.1 is not the latest release but I doubt it is relevant here. I'll investigate and get back to you. Thanks for the report!

**Comment by pllim** [comment]
@mmebsout , I agree with your assessment. In fact, in `vo_test.py`, it was noted that, "We can't test xmllint, because we can't rely on it being on the user's machine." Therefore, that logic path is never tested (see coverage at https://coveralls.io/builds/15819347/source?filename=astropy%2Fio%2Fvotable%2Ftable.py).

Do you want to open a PR to fix this, so your contribution is credited properly?

**Comment by mmebsout** [comment]
@pllim Thank you, I didn't consider it but I guess I should. It would give me the opportunity to learn something in the process I'm sure, and maybe contribute more efficiently next time. I should have a PR submitted before this week-end.

**Comment by pllim** [comment]
@mmebsout , thank you. I hope http://astropy.readthedocs.io/en/latest/#developer-documentation would help you along.

**Comment by mmebsout** [comment]
@pllim I'm sure it will. Thanks!
