### ISSUE TITLE
astropy.modeling.functional_models.Voigt1D --- negative values

### ISSUE THREAD

**Issue by fSchreier** [astropy/astropy#7256]
Recently I became aware of the Voigt function implementation in astropy,
and noticed that it is based on a simple approximation (sum of Lorentzians).
I have always been a bit sceptical w.r.t. this kind of approximations,
and my tests clearly confirm this, i.e. when the Lorentz width is much smaller than the Gauss width, the McLean Voigt profile becomes negative !!!
(See the attached python scripts)

In view of the dozens of Voigt and complex error functions available,
I am really surprised of the current astropy implementation.
As an alternative I would recommend rational approximations,
in particular by Humlicek, Weideman, or the combination thereof
(see also https://atmos.eoc.dlr.de/tools/lbl4IR/index.html).
Scipy's wofz function is clearly suitable for benchmark accuracy tests,
but I would not recommend it for "number crunching".

Derivatives: Evaluating the Voigt function as the real part of the complex error function also provides the derivatives, so there is no need to manually differentiate whatever approximation.

With best regards,
Franz Schreier 

[voigt_astropy.py.txt](https://github.com/astropy/astropy/files/1776004/voigt_astropy.py.txt)
[voigt_mcLean.py.txt](https://github.com/astropy/astropy/files/1776005/voigt_mcLean.py.txt)

[wofz-mcLean.pdf](https://github.com/astropy/astropy/files/1776026/wofz-mcLean.pdf)

**Comment by fSchreier** [comment]
Dear Tom,

thanks for reopening this issue.
Actually I already wanted to contact you for the proper handling of this issue
(as already mentioned, I am not an experienced github user).

First, the title/subject could be made more precise, e.g. by adding something like
"negative values".
And, in my view, this is simply a bug (due to the bad approximation),
but when uploading this issue Friday afternoon I did not see any way to tag the issue accordingly.
Finally, the "voigt_astropy.py.txt" attachment is not really well documented/commented,
and the 'third' attachment (wofz-mcLean.pdf added later) is showing up at the very top of the page.

Greetings
Franz

**Comment by bsipocz** [comment]
@fSchreier - Thanks for opening the issue. You can edit both the title and the description even after opening if you feel something was not described accurately enough. I've moved the attachment to the bottom. 
However it's usually more useful (easier to quick check it) to include the example codes in the issue text itself than in an attachment.

Labelling/tagging is then usually done my the submodule maintainers.

**Comment by perrygreenfield** [comment]
@fSchreier - Thanks for pointing out some much better algorithms! Admittedly the original version was supplied quickly in response to a workshop example showing the need for a Voigt function. Little research was done looking for the ideal implementation. Do you have any guidance on the relative performance of the two cases you plot? If the penalty for the more accurate algorithm (hum1wei32a) isn't great, that's what we probably go with (though if much different we could supply both).

**Comment by fSchreier** [comment]
For a performance assessment of the `hum1wei32a' (and the slightly less accurate `hum1wei24a`) 
approximation see my JQSRT papers published 2011 and 2017.
There you will also find a discussion of requirements (accuracy, range of x, y) for atmospheric 
radiative transfer.

Humlicek-Weideman vs McLean:

I haven't tested the McLean code w.r.t. speed (I don't see any value to test a code delivering 
negative values).  In view of the four divisions I would expect its about a factor 4 slower than the 
Humlicek-Weideman combination that need just one division per function value.
(Well, one could 'optimize' McLean by combining the fractions, but ....)

Weideman's rational approximation is applicable in the entire x,y complex plane
(i.e. no need for conditional branches) BUT for small y<<1 a high degree polynomial is required.
And for large |x|+y the Voigt is almost a Lorentz (hence the substitute by Humlicek's approximation I).

Scipy's wofz implementation appears to be faster than Weideman for a single x,y value,
but is a factor 2.5 slower for an array of values.
However this x=linspace(-5.,5.,1001) example is not realistic for 'real applications' where x can be 
as large as 10000 or more.

https://doi.org/10.1016/j.jqsrt.2010.12.010
https://doi.org/10.1016/j.jqsrt.2016.08.009

**Comment by fSchreier** [comment]
In brief:
scipy.special.wofz is very accurate and surprisingly fast, but
* Four to six significant digits accuracy is good enough for most applications
* Humlicek (1982) combined with Weideman (1994) or Humlicek (1979) is faster
* Implementation:  about ten lines of code

For the details see:
Optimized Implementations of Rational Approximations for the Voigt and Complex Error Function.
JQSRT 112(6), 1010–1025, 2011; doi: 10.1016/j.jqsrt.2010.12.010

Computational Aspects of Speed-Dependent Voigt Profiles.
JQSRT, 187, 44–53, 2017;  doi: 10.1016/j.jqsrt.2016.08.009

Comments on the Voigt function implementation in the Astropy and SpectraPlot.com packages.
JQSRT, 213, 13–16, 2018;  doi: 10.1016/j.jqsrt.2018.03.019;  arXiv:1806.10338

The Voigt and complex error function: Humliceks rational approximation generalized.
MNRAS 2018;  doi: 10.1093/mnras/sty1680;  arXiv:1806.11560
