### ISSUE TITLE
Revisit workarounds and skipped tests when numpy-1.14.2 is available

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#7258]
PR #7234 fixed the numpy-related test failures that were documented in #7214. However, some of these changes were just temporary workarounds or skipped tests, so they should be addressed once `numpy-1.14.2` is released (assuming it actually fixes these issues).

**Comment by astrofrog** [comment]
I wonder if it would make sense to xfail those tests *only* for ``NUMPY_EQ_141`` so that this automatically triggers failures when Numpy 1.14.2 is out.

**Comment by pllim** [comment]
#7267 and #7276 addressed everything *except* for `docs/io/fits/usage/unfamiliar.rst`.
