### ISSUE TITLE
Table Latex reader should ignore [top/mid/bottom-rule]

### ISSUE THREAD

**Issue by michaelaye** [astropy/astropy#7260]
The very handy Latex to astro-table reader has a problem with the rules that every good LaTex table has, which are, at least these days, top-, mid-, and bottomrule.
It would be handy if the reader could filter for this automatically, so that we wouldn't have to fix the LaTex code before the read attempt.

Version I'm using: 3.0 on macOS 10.12.6, Python 3 via conda-forge.

**Comment by pllim** [comment]
Hi. Could you please provide an example of a problematic table, and also what exactly that you need filtered? Thanks.

**Comment by hamogu** [comment]
The latex reader takes a `ignore_latex_commands` argument. Anything listed in there will be interpreted as a comment line (=ignore) the the reader, see: https://astropy.readthedocs.io/en/latest/api/astropy.io.ascii.Latex.html#astropy.io.ascii.Latex

The default for that is defined here: https://github.com/astropy/astropy/blob/master/astropy/io/ascii/latex.py#L313
It would be very easy to add a few more LaTeX commands to that list.

**Comment by michaelaye** [comment]
ah, thank you @hamogu , should I create a PR?

**Comment by hamogu** [comment]
That would be great!

**Comment by michaelaye** [comment]
Let's see if I can manage. The steep contribution curve of astropy is famous among GitHubbers... ;)

**Comment by hamogu** [comment]
Let me know if you are stuck somewhere and I'm happy to help along the way!

**Comment by hamogu** [comment]
This was solved in #7349.
