### ISSUE TITLE
WCS projection using ALTRVAL instead of standard axis keywords

### ISSUE THREAD

**Issue by julie-davis** [astropy/astropy#7268]
I have a Position Velocity diagram that was created with CASA. As such, the header contains CRVAL/CRPIX/CDELT/etc keywords for offset, stokes parameter, and frequency. It also lists an ALTRVAL and ALTRPIX, which gives the reference values for velocity. However, when I print my WCS object, it only recognizes the three axes of offset, stokes, and frequency, so my plotted PV diagram is has frequency instead of velocity on the y-axis. Is there some way I can get it to recognize and use the ALTRVAL instead, so my y-axis is velocity?  

I am a beginner python user and was pointed here, apologies if this is not the appropriate venue for this question.

**Comment by pllim** [comment]
Hi. AFAIK, CASA does its own distribution, no? I am not sure what Astropy version it is using. Can you please check your Astropy version? And if possible, provide a complete code snippet to reproduce your problem. Thanks.

**Comment by pllim** [comment]
Thanks for the info. c/c @astrofrog @nden

**Comment by nden** [comment]
@julie-davis I am not familiar with keywords named `ALT*`. Are these custom keywords (project specific)? As far as I know they are not in the FITS standard.
If the goal is to have an alternate WCS in the header, as described in, I think, WCS Paper I, then you need to append a key (any character in the English alphabet) to the standard WCS keywords to create the alternate WCS. Then the WCS object is created by passing the key to the initializer:

wcsobj = wcs.WCS(header, key='A') 

if 'A' was chosen as the alt key. But may be I misunderstand.

**Comment by julie-davis** [comment]
@nden The FITS file was written out by CASA. I imagine it has an internal routine that knows how to use that ALTRVAL keyword, as displaying this file in CASA displays the proper axes. I have googled endlessly to try and figure out how CASA does this, but to no avail. The help tickets for CASA are incredibly backlogged, hence my questions here.

**Comment by julie-davis** [comment]
I have resolved this issue, and am writing for any future viewers of the question:
When writing the fits file out using CASA, one must use exportfits using the "velocity=True" option. This assigns velocity to the third NAXIS, CTYPE3, which is read by WCS. Frequency references then become the ALTRVAL. It would still be helpful to know how to access that ALTRVAL for WCS projection purposes, but for the time being, the issue is solved.
