### ISSUE TITLE
Astropy fitting strips parameter units

### ISSUE THREAD

**Issue by nmearl** [astropy/astropy#7277]
In general, models preserver their units in their `evaluate` methods:

```python
from astropy.modeling.models import Gaussian1D
import astropy.units as u

class Gaussian(Gaussian1D):
    def evaluate(self, x, amplitude, mean, stddev):
        print(x)
        print(mean)
        print(stddev)
        print(amplitude)
        
        return super(Gaussian, self).evaluate(x, amplitude, mean, stddev)

g1 = Gaussian(mean=3 * u.micron, stddev=1 * u.micron, amplitude=1)
g1(np.arange(10) * u.Angstrom)
```

```
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] Angstrom
[3.] micron
[1.] micron
[1.]
```

However, when using a fitter, the units on all arguments to the `evaluate` method are stripped:

```python
fitter = LevMarLSQFitter()

x = np.arange(10) * u.Angstrom
y = g1(x)

fit_g1 = fitter(g1, x, y)
```

```
[0.     0.0001 0.0002 0.0003 0.0004 0.0005 0.0006 0.0007 0.0008 0.0009]
[3.]
[1.]
[1.]
```

This makes it impossible to do `Quantity`-based calculations inside the `evaluate` method without first converting all arguments to their `Quantity` versions.

**Comment by nden** [comment]
@nmearl I know it's been a while since this issue was filed but hopefully you can get back to this. It os true that astropy.fitting strips units internally while fitting a model with units. It does so after converting to the same units. At the end it attaches them to the fitted model and the initial model is not modified since the fitter works on a copy. Do you actually see a fit crash or produce incorrect results?

**Comment by nmearl** [comment]
In the case that a defined model's `evaluate` method expects parameters to be quantities, the fitting will trigger a crash when the values are not quantities, hence:

> This makes it impossible to do Quantity-based calculations inside the evaluate method without first converting all arguments to their Quantity versions.

The user has to re-convert the inputs to quantities with appropriate units in that case. It's sounding like that just may be the limitation of the model/fitting machinery in astropy.

**Comment by nden** [comment]
Right, this is a design decision. If you define a model with units you need the inputs to be Quantities. Otherwise you don't know if they are correct. I guess there can be a model where it doesn't matter and in those cases `input_units_allow_dimensionless` is set to `True` but Gaussian is not one of them.

I am going to close this but feel free to reopen if you feel this is a problem.

**Comment by nden** [comment]
@nmearl Are you saying it ought to be supported?

**Comment by nmearl** [comment]
Correct. Even if the fitting needs to remove the units on the parameters, the `evaluate` method should still be called with quantities. So, while the fitter can use the unit-less parameters, the body of the `evaluate` method should still be fed the quantity objects to preserve calculations that relied on being given quantity objects.

**Comment by perrygreenfield** [comment]
I'm not sure the example illustrates what is happening. Are you saying the fit model that is returned has parameters that aren't quantities? (I ask since the example doesn't appear to show what I expect. I would expect to see the original set of parameters with quantities since y is the result of an evaluation, then every time the fitter evaluates I also expect to see them printed. What I would like to see is the returned model and the state of its parameters. I wonder if the discussion above is not referring to the same idea of behavior, so we should be very explicit about it.

**Comment by nden** [comment]
Sorry, I don't follow. Perhaps you should have a failing example which shows the problem and what you expect to happen.

**Comment by nmearl** [comment]
Sorry, this is becoming overly complicated for what amounts to a simply convenience wish, and thanks for addressing this. Note that I have since created workarounds for all this, but just to clarify this particular issue...

Essentially: an `evaluate` method may have internal calculations that depend on the parameters being given as `Quantity` objects. This is preserved when calling the model by itself, but in the case of the model being used in a fitter, where the unit information is stripped, the `evaluate` method must convert the parameters to quantity objects explicitly.

The problem that arises is that the fitting machinery goes through and converts all the sub-model parameters to the unit of the input. This just means that I have to be sure that I not only re-convert the units to `Quantity` objects explicitly in the `evaluate` method, but that, depending on if the units have been stripped and converted by the fitter, the `evaluate` method has to be aware that the _value_ of the parameter will change. E.g. In calling the model directly, the `mean` is given in `micron`s. However, if I call a fitter that has `input_units` defined to be `Angstrom`, the _value_ of the parameter would be given in `Angstrom`.

```python
In [86]: class Gaussian(Gaussian1D):
   ....:         @property
   ....:         def input_units(self):
   ....:                 if self.mean.unit is not None:
   ....:                         return {'x': u.Angstrom}
   ....:                 return None

   ....:         def evaluate(self, x, amplitude, mean, stddev):
   ....:                 print('Amplitude', amplitude)
   ....:                 print('Mean', mean)
   ....:                 print('Stddev', stddev)
   ....:                 return super().evaluate(x, amplitude, mean, stddev)
```

```python
In [87]: x = np.arange(10) * u.Angstrom
In [88]: g1 = Gaussian(mean=3 * u.micron, stddev=1 * u.micron, amplitude=1)
In [89]: g1(x)
        Amplitude [1.]
        Mean [3.] micron
        Stddev [1.] micron
```

```python
In [93]: fit_g1 = fitter(g1, x, y)
        Amplitude [1.]
        Mean [30000.] # Unitless value converted to Angstrom
        Stddev [10000.]
```

Providing the `evaluate` method with parameters in the units expected (and as `Quantity`s) would be really helpful.

**Comment by nden** [comment]
Thanks for the clarification. Just to confirm I understand correctly - you would like to attach units to the parameters and inputs every time the model is evaluated during the iterative fitting and then remove them before the optimization algorithm is run. The unitless model evaluation is done in the objective function. 

I am curious what is the specific use case you have in mind. Are you overwriting the objective function? If so what is the reason? Are you using a different statistic?

**Comment by nmearl** [comment]
That's right. My use case is probably extreme particular. In general, I have a complex compound model that represents a spectrum. The input to this spectrum can be given in either velocity or wavelength (hence I can't set a single `input_units` value). This is necessary because if the spectrum represents a set of single ions distributed in velocity space, then converting everything to `Angstrom` would make them all appear on top of each other, and the fitter would fail. Likewise, if the spectrum is composed of multiple difference ions with no velocity offsets, the `x` input would need to be in `Angstrom`, otherwise they would all appear on top of each other in velocity space.

The `evaluate` method in the internal sub models all need to be aware of the `x` input in order to properly handle the fitting to the profiles. In the same vein, I can't simply assume that the unit-less parameters passed in the fitter are *always* `Angstrom` or *always* `km/s`.

I hope this clears my use case up a bit.

**Comment by nden** [comment]
@nmearl IIRC we discussed this use case at the coordination meeting. Should this be closed now?

**Comment by nmearl** [comment]
@nden Ah, sorry, did we? Could you refresh my memory a bit on what the conclusion we came to? 😅

**Comment by nden** [comment]
After a discussion with @nmearl we decided this should be closed.
