### ISSUE TITLE
Documentation of trying development has python2-only stuff

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#7287]
In http://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#activate-the-development-version-of-astropy, it is suggested to run `python setup.py develop` and it is noted that this is for python2 only. Since we moved to python3, this should be adjusted (to be tested: does this work on python3 now? if not, replace with code showing how to do it in a virtual environment)

**Comment by emilydeibert** [comment]
This does not work on Python3 right now---I am using Python3 and when I follow the linked instructions the development version will only activate in the distribution directory, but not outside.

**Comment by kakirastern** [comment]
Hi, is it okay for me to work on this issue in preparation for my GSoC 2019 application?

**Comment by mhvk** [comment]
@kakirastern - yes, definitely OK. But please read the discussion in a previous attempt (#7295) and check for yourself what actually works (ideally on different machines). Specifically, there were suggestions to change the shebang on `setup.py` to `python3` and use `./setup.py` or to use `pip install -e .`

Note that the main way this PR allows you to show skills for GSoC is by exploring the above issues yourself (it is clear that making the changes to the text is not difficult).

**Comment by mhvk** [comment]
OK, great!  But at least on my machine I'd need to do `pip3 ...` - a shebang would be `#! /usr/bin/python3`. Anyway, trials are the way forward.

**Comment by pllim** [comment]
Wait... Is this still an issue after @astrofrog 's rewrite in #8198 ? @astrofrog , that said, does `python setup.py develop -u` at the end still applies?

**Comment by mhvk** [comment]
@pllim - Looking at the current documentation at http://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#get-devel I see it indeed has changed. But it still has a warning about things not being possible in python3. If this is true, then the whole section should be removed. But I think it is not true, and that it is possible to pip-install under ones own user directory (with `-u` indeed).

Anyway, @kakirastern, given that the documentation discusses something that supposedly does not work on python3, which is the only python version we support, there definitely is still work to do!

**Comment by bsipocz** [comment]
Hmm, I supposed we've addressed this issue with https://github.com/astropy/astropy/pull/8289. If there is still some python3 incompatibility mentioned that most probably should be just simply removed.

@kakirastern - If you are willing to open a PR for that removal that would be great. The assumptions are that everything should work for you locally with Python 3 (aka `python` :) ), so the only stuff in the PR is the removal of those notes about incompatibility.

**Comment by bsipocz** [comment]
> OK, great! But at least on my machine I'd need to do pip3 ... - a shebang would be #! /usr/bin/python3. Anyway, trials are the way forward.

Well, `pip` can be aliased/linked to `pip3` this point, and leave `pip2` as the exception :)

**Comment by kakirastern** [comment]
@bsipocz Sure, I am willing to open a PR for the removal of outdated contents, i.e. "those notes about incompatibility". Do you think I should also add some comments about aliasing `python3` to `python` and `pip3` to `pip`, respectively? (Sort of like a reminder for people to check their computing setup. Maybe not everyone is aware of it.)

**Comment by bsipocz** [comment]
Yes, mentioning the aliasing sounds like a good compromise. Thank you.

**Comment by kakirastern** [comment]
Yup, proposed adding implicit aliasing reference in PR #8385...

**Comment by mhvk** [comment]
fixed a long time ago by #8385
