### ISSUE TITLE
Astropy development version installation fails without PyYAML installed

### ISSUE THREAD

**Issue by emilydeibert** [astropy/astropy#7296]
I followed [these](http://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#activate-development-astropy) instructions but the install failed because I did not have PyYAML installed. I believe that PyYAML should not be necessary for the installation to work; however if it is perhaps this should be noted in the installation instructions? I am using Python 3.6.1.

**Comment by pllim** [comment]
`pyyaml` is listed under https://github.com/astropy/astropy/blob/master/pip-requirements-dev .

By the way, where did you obtain your instructions, is it at http://astropy.readthedocs.io/en/latest/development/workflow/get_devel_version.html ? We have to make sure we update the one that people are actually using. Thanks for reporting this!

**Comment by emilydeibert** [comment]
Yes, those are the instructions I am following. Thank you!

**Comment by pllim** [comment]
Proposed solution (other maintainers feel free to chime in): Under "'Activate' the development version of astropy" section, add instructions for `pip install -r pip-requirements-dev` before `python setup.py develop`.

**Comment by saimn** [comment]
There is already `setup_requires` in the setup file, which contains Cython and Jinja2. 
PyYAML should probably not be required (or should be listed there too), what error do you get @emilydeibert ?
