### ISSUE TITLE
Improve visibility of how to cite / attribute Astropy

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#7297]
A few suggestions:
* Add an "Attribution" section to the main repo README that provides some basic info about how to cite Astropy, and links to either the CITATION file or the [Acknowledging Astropy](http://www.astropy.org/acknowledging.html) page
* Add a functional `astropy.__citation__` or `astropy.__bibtex__` variable. See also #3114 and the bug in #6126, but in v3.0 I get an empty string when I do `astropy.__bibtex__`. (astroML and a few other packages use `__citation__`)
* Update [Acknowledging Astropy](http://www.astropy.org/acknowledging.html) page to recommend using new `\software{}` tag in AAS journals, and the standard acknowledgement for others.

cc @kelle

**Comment by kelle** [comment]
I was also thinking we make a function that returns how to cite things. E.g. 'Cite('matplotlib')'

**Comment by adrn** [comment]
I actually think that this is something we could propose to Python itself, a new builtin function:
```python
>>> import astropy
>>> citation(astropy)
...bibtex entry
```
(i.e. it just looks for `astropy.__citation__`).

But I don't think that function belongs in astropy.

**Comment by adrn** [comment]
(taking this discussion into email with a wider group, but will report on conclusions)

**Comment by jameshowison** [comment]
Important stuff.  I was wondering why your top level CITATION file is a symbolic link?  https://github.com/astropy/astropy/blob/master/CITATION

http://citeas.org finds that file (starting with astropy.org but doesn't know how to follow or process it.

Consider adding a CODEMETA or CITATION.cff file?  https://citation-file-format.github.io/  https://codemeta.github.io/

**Comment by bsipocz** [comment]
@jameshowison - It was changed to a symlink to avoid duplication with `astropy/CITATION`. Having the CITATION being available in installed versions is rather important, but the top level one isn't being installed. 
(In the next release `astropy.__citation__` will work).

Also, have a look at https://github.com/adrn/makecite, it's actually super conveniently goes through the code stack to look for packages to cite. It would be super nice to eventually merge the databases with citeas.org.

**Comment by bsipocz** [comment]
Actually there is already an issue about the integration: https://github.com/adrn/makecite/issues/3, and there were a few more ideas that didn't get implemented during the summer.

**Comment by pllim** [comment]
Is this resolved yet? Anything else that needs to be done still?

**Comment by jameshowison** [comment]
Well, I think it's up to citeas to figure out how to follow the symbolic
link to your CITATION file. You won't be the only repo with sub-directories
like that.  @caseydm any thoughts on how we can do that, can it be done via
the API?  (Also a one word search for `astropy` fails, any ideas on that?)

For the astropy.__citation__ will there be a way to get this without
installing the package (ie R citation method always points to the
DESCRIPTION file)?

**Comment by bsipocz** [comment]
obviously `astropy.__citation__` won't work without installing, but we keep the `CITATION` file in the main repo exactly for the purpose to help other tools to pick up the citation information. It needs to be in the subdir  for the method to work for installations, but if there is any standard like thing already been universally agreed, please let us know.

Given that there are issues with the symlink for some windows systems, we're about to change the top level file to contain the link to one with information stored in.

**Comment by caseydm** [comment]
Hi James. I found if you use the Github API to fetch a symlink'd file, it [follows the link](https://developer.github.com/v3/repos/contents/#response-if-content-is-a-symlink) and places the content in a certain field in the API response. So that is set up now and working on the CiteAs API. The only issue is we do not receive the path of the linked file, so the file path that is linked on CiteAs is still the original CITATION file.

In the case of Astropy, it finds the DOI that is mentioned in the CITATION file then uses that to build the citation.

Also, a bug came up with the google search functionality and I was able to resolve that. So key word search is working normally again.

**Comment by jameshowison** [comment]
Awesome.  Thanks all for helping us get symlink following set up!
Searching "astropy" on citeas.org now brings up your requested 2018
citation.

FWIW, we grab the first DOI found in the CITATION file and then use the DOI
API to get the citation info (so we don't go via the ADS link at the top of
your CITATION file).

**Comment by bsipocz** [comment]
@jameshowison @caseydm - would https://github.com/astropy/astropy/pull/9675 still work for your machinery?

**Comment by jameshowison** [comment]
Hmmm, that would appear as a CITATION file without a DOI (or bibtex), but I
think we could simply make a rule that when processing a CITATION file that
otherwise seems a dead-end follow the first link in the file.  That would
take us to the lower CITATION file and we'd be fine.

CiteAs.org is all about figuring out current practices and adapting to
them, so assuming it makes sense to @caseydm within the codebase it works
for me.

(back of my mind says perhaps this should be a redirect (like a 301 or
meta-refresh) but that's likely wrong in the pip install context and
definitely don't do that just for us :)

--James

**Comment by bsipocz** [comment]
Yes, we get rid of the symlink as it causes all kind of issues on windows, and would rather avoid duplicating file content (as mentioned above the canonical one has to be in the source to be packaged up for usage from the python prompt)

**Comment by caseydm** [comment]
Yes we can detect a simple URL in that file and follow it to retrieve the content. I'll probably filter by detecting a minimal amount of text, plus the presence of keywords in  the URL.

**Comment by bsipocz** [comment]
@adrn - some of the stuff in the original description have been fixed. Would you mind to have another look and open a PR with the missing bits, so we can close this issue for 4.0?

**Comment by astrochun** [comment]
Had a thought about citation and checked on whether `astropy` has a CITATION.CFF, which is becoming the standard for ensuring proper attribution/citation. I didn't see it in `main` nor do I see CITATION.CFF even mentioned in this issue.

For reference, the schema to ensure that the GitHub repo will have both APA and BibTeX: https://citation-file-format.github.io/

**Comment by pllim** [comment]
Is there anything left to be done? Looks like all the items in the original post are addressed by now?
