### ISSUE TITLE
Unexpected value in Table when applying `fill_value` to entire table

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#7307]
Consider this simple example:

```
from astropy.io import ascii

data = ascii.read("test.dat", fill_values=[('INDEF', '0')])
data.fill_value = 99.9999  # <-- Here's the issue
data = data.filled()
```

with a `test.dat` file composed of:

```
16        1035.22  1041.09    24.54     0.30     1.39     0.30     1.80     0.30     2.26     0.30     1.14     0.30     0.28     0.30   0.2884
127        824.57  1105.52    25.02     0.29     0.87     0.29     1.30     0.29     2.12     0.29     0.66     0.29     0.10     0.29   0.2986
182       1015.83   904.93    INDEF     0.28     1.80     0.28     1.64     0.28     2.38     0.28     1.04     0.28     0.06     0.28   0.3271
185       1019.15  1155.09    24.31     0.28     1.40     0.28     1.78     0.28     2.10     0.28     0.87     0.28     0.35     0.28   0.3290
192       1024.80  1045.57    24.27     0.27     1.24     0.27     2.01     0.27     2.40     0.27     0.90     0.27     0.09     0.27   0.3328
197       1035.99   876.04    24.10     0.27     1.23     0.27     1.52     0.27     2.59     0.27     0.45     0.27     0.25     0.27   0.3357
198       1110.80  1087.97    24.53     0.27     1.49     0.27     1.71     0.27     2.33     0.27     0.22     0.27     0.00     0.27   0.3362
1103      1168.39  1065.97    24.35     0.27     1.28     0.27     1.29     0.27     2.68     0.27     0.43     0.27     0.26     0.27   0.3388
```

The above code stores `data` as:

```
col1   col2    col3   col4 col5 col6 ... col11 col12 col13 col14 col15 col16 
---- ------- ------- ----- ---- ---- ... ----- ----- ----- ----- ----- ------
  16 1035.22 1041.09 24.54  0.3 1.39 ...   0.3  1.14   0.3  0.28   0.3 0.2884
 127  824.57 1105.52 25.02 0.29 0.87 ...  0.29  0.66  0.29   0.1  0.29 0.2986
 182 1015.83  904.93 1e+20 0.28  1.8 ...  0.28  1.04  0.28  0.06  0.28 0.3271
 185 1019.15 1155.09 24.31 0.28  1.4 ...  0.28  0.87  0.28  0.35  0.28  0.329
 192  1024.8 1045.57 24.27 0.27 1.24 ...  0.27   0.9  0.27  0.09  0.27 0.3328
 197 1035.99  876.04  24.1 0.27 1.23 ...  0.27  0.45  0.27  0.25  0.27 0.3357
 198  1110.8 1087.97 24.53 0.27 1.49 ...  0.27  0.22  0.27   0.0  0.27 0.3362
1103 1168.39 1065.97 24.35 0.27 1.28 ...  0.27  0.43  0.27  0.26  0.27 0.3388
```

notice the `1e+20` value in the third row of `col4` where a `99.9999` should be. If instead I use:

    data['col4'].fill_value = 99.9999
    data = data.filled()

then the data is properly filled. But I don't want to apply `fill_value` to a single column, I want to apply it to the entire Table. Is this behaviour intended?

**Comment by saimn** [comment]
`.fill_value` for an entire table would work only if all columns have a type compatible with the fill value, so I guess it's the reason why `fill_value` must be defined per column. But note that you can use `data.filled(99.9999)` to use the fill value for the entire table.

**Comment by Gabriel-p** [comment]
`data.filled(99.9999)` works as expected, thank you @saimn 

I still believe the behaviour of `fill_value` is confusing when applied to a whole Table. There's nothing to indicate that such a value (1e+20) will appear. If this is not how `fill_value` should be used, then it should not work on Tables, only Columns.

**Comment by alquerque** [comment]
I suggest to make the fill_value field as private as possible and having a get_fill_value function to get it.

Decorators can be used as in https://docs.python.org/2/library/functions.html#property

**Comment by saimn** [comment]
> I still believe the behaviour of fill_value is confusing when applied to a whole Table. There's nothing to indicate that such a value (1e+20) will appear. If this is not how fill_value should be used, then it should not work on Tables, only Columns.

I think the confusion comes from setting `data.fill_value` though it actually does nothing, `fill_value` is not a `Table` attribute. So instead the column uses its default fill_value, which is 1e20 for float columns (and this is inherited from Numpy I think).
Is there a place in the docs that suggest this should work ? (Just to know if this is a documentation issue)

**Comment by Gabriel-p** [comment]
> Is there a place in the docs that suggest this should work ? (Just to know if this is a documentation issue)

My point is that if `fill_value`  is not meant to work on Tables then it should not work on Tables. Right now it *does* something, and it does so silently. There should be at least a warning issued instead of masking the table using a value that is nothing like the one being set.

**Comment by saimn** [comment]
> My point is that if fill_value is not meant to work on Tables then it should not work on Tables. Right now it does something, and it does so silently.

No, it does nothing. You are setting an attribute which is simply not used (I may be wrong, but this is what I understand from the code).

**Comment by Gabriel-p** [comment]
You are correct that `fill_value` is not generating the issue here. The issue is with the `.filled()` attribute. Just these line

    data = data.filled()

is enough to generate that `1e20` value.

**Comment by hamogu** [comment]
Looking back at this,  it seems that there is no issue here (and that's presumably why the discussion stopped). Setting "fill_value" on a table does nothing about the values,  just like setting "fill_val" or "ergfdfh" would not do anything.  We don't want to prevent users from adding attributes with any name they like.

On the other hand,  when filling the table it fills it with the default value since nothing different is specified for the columns. So that's how it should be.
