### ISSUE TITLE
[Feature Request] Equivalent of strftime for astropy.time.Time

### ISSUE THREAD

**Issue by vn-ki** [astropy/astropy#7309]
Right now the only way to format output is to define a custom format(which is an overkill for simple formatting). A function like `strftime`([python](https://docs.python.org/3/library/datetime.html#datetime.date.strftime)) would simplify this process greatly.

If this method or a similar one does not exist already, I would like to work on adding this. If someone could give some guidance it would be super useful.

**Comment by mhvk** [comment]
Like for `datetime`, I think the logical place for this to live is in a new `__format__`. But I think it would be good to be explicit about what you might actually hope would happen. E.g., `Time` can be an array; what should be the output? 

Also, perhaps more directly of help, for scalar `Time`, the following does work:
```
Time.now().datetime.strftime('%a')
# 'Mon'
```

But for an array this fails:
```
Time(50000, np.arange(10), format='mjd').datetime.strftime('%a')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-6ecd7286c9d7> in <module>()
----> 1 Time(50000, np.arange(10), format='mjd').datetime.strftime('%a')

AttributeError: 'numpy.ndarray' object has no attribute 'strftime'
```
because numpy arrays of datetime do not have this function either.

**Comment by mhvk** [comment]
p.s. I'd be :-1: on any formatting that still relies on `%`.

**Comment by vn-ki** [comment]
> p.s. I'd be :+1: on any formatting that still relies on %.

What kind of formatting do you think suits `Time` the best?

**Comment by mhvk** [comment]
Python-style, i.e., `{...:..}` - https://docs.python.org/2/library/string.html#format-string-syntax

**Comment by vn-ki** [comment]
After looking into it, I suggest we use `format_spec `. I guess that was the way you were going too.

`datetime` uses `format_spec` in the following manner (taken from [python docs](https://docs.python.org/2/library/string.html#format-examples)).
```python
>>> '{:%Y-%m-%d %H:%M:%S}'.format(datetime(2010, 7, 4, 12, 15, 58))
'2010-07-04 12:15:58'
``` 

Since you don't want to use `%` notation we would have to decide on a easy and expressful syntax for format string.

My suggestion is to make the spec sheet explicit. Ex:
```python
>>> '{:year-month-day hours:minutes:seconds}'.format(Time(<something>))
```
But I have no experience in this field nor I do not know what the needs of the community is. What do you think?

**Comment by mhvk** [comment]
@vn-ki - I do not use `datetime` myself, and am not really sure what actually is wanted here; I really think we need to think about formatting of arrays and different formats more generally before worrying about details for a specific Time format, especially as for `datetime` itself there is a trivial work-around.

Also, as I noted in the other thread, I am very short of time, and fear this is low enough on my priority list that I'm going to unsubscribe from this thread. Again cc @taldcroft in case he feels differently.
