### ISSUE TITLE
convolve boundary=None segfaults with kernel larger than array

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy#7310]
The following code segfaults.
```python
import faulthandler
import astropy.convolution
import numpy as np

faulthandler.enable()

image = np.random.random(11)
ker = astropy.convolution.Gaussian1DKernel(20,x_size=41)

astropy.convolution.convolve(image, ker, boundary=None)
```
This is due to the following code ([src](https://github.com/astropy/astropy/blob/6e433c62d4714238c186cdd1d45eabbe9c3b77c5/astropy/convolution/boundary_none.pyx#L33-L43)):
```cython
...
cdef  unisgned int i, ii
...
for i in range(wkx, nx - wkx):
...
```
Since `i` is unsigned `nx - wkx` yields a very large and positive number for `wkx > nx`. If `i` were signed this would not be a problem and no iteration would occur and the func would simply return an empty array. However, `unsigned` is totally needed here since it is used to access `conv[i]`.

This is fixed by #7293 by adding a check in [convolve](https://github.com/jamienoss/astropy/blob/e11e8b2e28aa86fb6d1d83cd9f06dc338d90aac8/astropy/convolution/convolve.py#L253-L265):
```Python
...
    # For boundary=None only the center space is convolved. All array indices within a
    # distance kernel.shape//2 from the edge are completely ignored (zeroed).
    # E.g. (1D list) only the indices len(kernel)//2 : len(array)-len(kernel)//2
    # are convolved. It is therefore not possible to use this method to convolve an
    # array by a kernel that is larger* than the array - as ALL pixels would be ignored
    # leaving an array of only zeros.
    # * For even kernels the correctness condition is array_shape > kernel_shape.
    # For odd kernels it is:
    # array_shape >= kernel_shape OR array_shape > kernel_shape-1 OR array_shape > 2*(kernel_shape//2).
    # Since the latter is equal to the former two for even lengths, the latter condition is complete.
    if boundary == None and not np.all(array_shape > 2*pad_width):
        raise KernelSizeError("for boundary=None all kernel axes must be smaller than array's - "
                              "use boundary in ['fill', 'extend', 'wrap'] instead.")
...
```
and the [C code for boundary=None](https://github.com/jamienoss/astropy/blob/e11e8b2e28aa86fb6d1d83cd9f06dc338d90aac8/astropy/convolution/boundary_none_direct.c#L159-L161):
```c
...
const unsigned _wkx = _nkx / 2;
if (!(_nx > 2*_wkx))
       return;
...
```

**Comment by pllim** [comment]
Hi. Ideally, a bug fix would be a separate PR,  but I'll leave it to the maintainer to decide.

**Comment by jamienoss** [comment]
@pllim 
I'm all cool with this, wouldn't want to smuggle code :wink:

**Comment by pllim** [comment]
It is simply because bug fix release is separate from a main release like 3.1. :smile:

**Comment by jamienoss** [comment]
@pllim ok, in that case, I can still keep my code as is and just fix this in master explicitly if we want it fixed sooner than 3.1.

**Comment by pllim** [comment]
@keflavich , any preference?

**Comment by keflavich** [comment]
Submit this fix as a PR and then we can decide if/where to backport it?  But could you clarify, what are you asking my preference on?

**Comment by pllim** [comment]
> what are you asking my preference on?

On whether to have this fix as separate PR. But looks like you have answered it. Thanks!

**Comment by keflavich** [comment]
Ahhh, yes, OK.  This is independent of #7293 so yes, separate PR.
