### ISSUE TITLE
NDData & pickling

### ISSUE THREAD

**Issue by abeelen** [astropy/astropy#7315]
With the introduction of `weak_ref` for uncertainty in NDData (see #4862 ), any object derived from this class can not be pickled using the standard `pickle` library :
```
from astropy.nddata import NDDataArray, StdDevUncertainty
import numpy as np
import pickle

ndd = NDDataArray(np.ones((2,2)), uncertainty=StdDevUncertainty(np.ones((2, 2))))
pickle.dumps(ndd)
```
will fail, preventing the use of NDData object in arguments of `multiprocessing.map` function. Using alternative pickling like `import dill as pickle` can circumvent this, and I believe this should be noted in the documentation.

**Comment by pllim** [comment]
c/c @mwcraig and @MSeifert04

**Comment by MSeifert04** [comment]
Since the `weakref` is just to avoid circular dependencies it should be easily possible to override this. Maybe it's possible using `__getstate__` alone. I'm a bit busy this week (& weekend) so if noone else wants I'll look into this soon-ish.
