### ISSUE TITLE
initialize Table with numpy array and column names

### ISSUE THREAD

**Issue by cristobal-sifon** [astropy/astropy#7320]
Initializing a `Table` with a numpy array crashes when passing column names, and gives a weird error message. The following
```python
print('astropy v{0}; numpy v{1}'.format(astropy.__version__, np.__version__))
data = random.random((5,10))
names = ['col{0}'.format(i) for i in range(len(data))]
Table(data, names=names)
```
produces
```
astropy v3.0.1; numpy v1.14.2

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-5d2d540b4498> in <module>()
      3 names = ['col{0}'.format(i) for i in range(len(data))]
----> 4 Table(data, names=names)

~/anaconda3/lib/python3.6/site-packages/astropy/table/table.py in __init__(self, data, masked, names, dtype, meta, copy, rows, copy_indices, **kwargs)
    403         names = [fix_column_name(name) for name in names]
    404 
--> 405         self._check_names_dtype(names, dtype, n_cols)
    406 
    407         # Finally do the real initialization

~/anaconda3/lib/python3.6/site-packages/astropy/table/table.py in _check_names_dtype(self, names, dtype, n_cols)
    616             raise ValueError(
    617                 'Arguments "names" and "dtype" must match number of columns'
--> 618                 .format(inp_str))
    619 
    620     def _set_masked_from_cols(self, cols):

ValueError: Arguments "names" and "dtype" must match number of columns
```

The only change needed to make this work is to turn `data` into a list:
```python
print('astropy v{0}; numpy v{1}'.format(astropy.__version__, np.__version__))
data = list(random.random((5,10)))
names = ['col{0}'.format(i) for i in range(len(data))]
Table(data, names=names)
print('Good!')
```
produces
```
astropy v3.0.1; numpy v1.14.2
Good!
```
None of this happens if I skip the `names` kwarg:
```python
data = random.random((5,10))
Table(data)
print('Good!')
```
works just fine.

I checked that the error also appears if both the data and the column names are numpy arrays.

**Comment by saimn** [comment]
Your `range(len(data))` creates 5 column names, though `Table(data)` creates a table with 10 columns. If you turn data into a list, then you get 5 columns, and it works. So it depends on what are your rows and columns.

**Comment by cristobal-sifon** [comment]
That sounds very strange. I can also bypass the error by doing:
```python
data = random.random((5,10))
names = np.array(['col{0}'.format(i) for i in range(len(data))])
Table(list(data), names=names)
```
which means that whether `data` is a list or a numpy array has no impact on `names`. Furthermore, both of the following return `True`:
```python
len(data) == len(names)
np.array_equal(data, list(data))
```
It is true though, that if I do
```python
data = random.random((5,10))
names = np.array(['col{0}'.format(i) for i in range(data.shape[1])])
Table(data, names=names)
```
it does work. It doesn't make a lot of sense though, given all of the above. Why do numpy arrays have this special treatment compared to lists?

**Comment by gsoni22** [comment]
The Following is work fine
Table(list(data), names=names)

**Comment by saimn** [comment]
With `Table(list(data)` the data is a list of 5 columns with 10 elements. But with `Table(data)` it is an array with 5 rows and 10 columns, so not the same thing.
http://docs.astropy.org/en/latest/table/construct_table.html#numpy-homogeneous-array

**Comment by cristobal-sifon** [comment]
OK, it is what it is. Might I ask though, out of sincere curiosity, why do you treat lists and numpy arrays differently?

**Comment by saimn** [comment]
I think

**Comment by saimn** [comment]
Sorry for the previous message.
I think the reason (and answer) is that Table is column-oriented, so by default it expects a list of columns. And Numpy arrays maps by default to a list of rows. But you can also give a list of rows to Table with `rows=...`. You may also be interested by this section for the rationale: http://docs.astropy.org/en/latest/table/construct_table.html#data

**Comment by cristobal-sifon** [comment]
gotcha. Thanks for taking the time.
