### ISSUE TITLE
Suppressing verify warnings when opening a fits file

### ISSUE THREAD

**Issue by amunozj** [astropy/astropy#7347]
Hi guys,  I'm sorry if this is not the right place, but I'm not being able to silence the verify warnings when opening a fits file and it's driving me nuts.  Does anyone know how to do this?  

I'm basically trying to find a way so that this message doesn't show every time I open a file:

"WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]"

thanks a lot!

**Comment by saimn** [comment]
You can find some explanations about python warnings here: http://docs.astropy.org/en/latest/warnings.html
To filter specifically VerifyWarning, you can use something like this:
```
from astropy.io.fits.verify import VerifyWarning
warnings.simplefilter('ignore', category=VerifyWarning)
```
Closing as there are other channels better suited for getting help: http://www.astropy.org/help.html
