### ISSUE TITLE
 astropy.io.votable.writeto: support for file overwrite

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astropy#7354]
from a table i/o unification point of view and user convenience it would be useful if

astropy.io.votable.writeto supported file overwrite.

**Comment by pllim** [comment]
Theoretically speaking, in terms of unified I/O, you wouldn't need to dig so far into `io.votable`, as it would have been handled in the `table` level. But yes, would be nice to have the unified I/O work as expected in the first place. xref #7352

**Comment by pllim** [comment]
`overwrite` does appear to work in https://github.com/astropy/astropy/issues/7352#issuecomment-379281722 . If that solves your usage issue, I'll set this to "won't fix", as I don't see any benefit in duplicating effort but at a lower level in the code.

**Comment by richardgmcmahon** [comment]
OK, overwite works for me as indicated in your example for Table.write. I think that astropy.io.votable.writeto quitely overwrites. I'll close this since the linked issue really is solved by documentation that coveres the binary votable format.
