### ISSUE TITLE
Astropy import conflicts with Spyder User Module Reloader

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#7363]
Something in the import framework fails when importing `astropy` multiple times in a `Spyder` Ipython console, using the builtin `runfile()` with the reload option of its `User Module Reloader` (UMR) enabled. Minimal way to reproduce the issue on various versions from Spyder 2.3.5.2-3.1.2, Ipython 3.2.2-5.1.0 and Astropy 1.1.1-2.0.5 under SuSe Linux or Ubuntu:
```
Python 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
Type "copyright", "credits" or "license" for more information.

IPython 3.2.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

In [1]: cd ~/routines/python/cosmo
/data/derek/routines/python/cosmo

In [2]: cat ap.py
# Test script for astropy reload bug

import astropy

In [3]: runfile('ap.py')

In [4]: runfile('ap.py')
Reloaded modules: astropy.utils, astropy.extern.configobj.configobj, astropy.config.affiliated, astropy, astropy.extern.plugins.pytest_remotedata, astropy.extern, astropy.utils.introspection, astropy.config, astropy.extern.six, astropy.extern.bundled, astropy.utils.decorators, astropy._compiler, astropy.extern.plugins, astropy.config.configuration, astropy.extern.configobj, astropy.extern.bundled.six, astropy.config.paths, astropy.extern.configobj.validate, astropy.utils._compiler, astropy.tests, astropy.cython_version, astropy.version, astropy.tests.runner, astropy.utils.misc, astropy.logger, astropy.utils.codegen, astropy.utils.exceptions, astropy.extern.plugins.pytest_remotedata.disable_internet

In [5]: runfile('ap.py')
Reloaded modules: astropy.utils, astropy.extern.configobj.configobj, astropy.config.affiliated, astropy, astropy.extern.plugins.pytest_remotedata, astropy.extern, astropy.utils.introspection, astropy.config, astropy.extern.six, astropy.extern.bundled, astropy.utils.decorators, astropy._compiler, astropy.extern.plugins, astropy.config.configuration, astropy.extern.configobj, astropy.extern.bundled.six, astropy.config.paths, astropy.extern.configobj.validate, astropy.utils._compiler, astropy.tests, astropy.cython_version, astropy.version, astropy.tests.runner, astropy.utils.misc, astropy.logger, astropy.utils.codegen, astropy.utils.exceptions, astropy.extern.plugins.pytest_remotedata.disable_internet
Traceback (most recent call last):

  File "<ipython-input-5-9b9f963d0dcf>", line 1, in <module>
    runfile('ap.py')

  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "ap.py", line 3, in <module>
    import astropy

  File "/data/derek/lib64/python2.7/site-packages/astropy/__init__.py", line 287, in <module>
    log = _init_log()

  File "/data/derek/lib64/python2.7/site-packages/astropy/logger.py", line 100, in _init_log
    log._set_defaults()

  File "/data/derek/lib64/python2.7/site-packages/astropy/logger.py", line 484, in _set_defaults
    self.disable_warnings_logging()

  File "/data/derek/lib64/python2.7/site-packages/astropy/logger.py", line 253, in disable_warnings_logging
    if warnings.showwarning != self._showwarning:

AttributeError: 'NoneType' object has no attribute 'showwarning'
```
With slightly more complex scripts the error will be triggered already on the second `runfile()`. Adding `astropy` to the list of modules excluded from UMR in the preferences avoids the issue.

A bit more context for those with access can be found in the [Python users in Astronomy](https://www.facebook.com/groups/astropython/permalink/2071549339756412) Facebook group.

**Comment by pllim** [comment]
I notice that you are using Python 2, which we have dropped support of in our 3.0 release. In addition, astropy 1.x is rather old. Do you still see the problem with Astropy 3.x in Python 3?

**Comment by dhomeier** [comment]
The above example was using astropy 2.0.5, the originally reported case 2.0. The Linux system I have access to does not have Python 3 development headers installed, so I could not update there to Astropy 3.x, but the same issue showed up with Python 3.4 + Astropy 1.2.1.

**Comment by pllim** [comment]
`if warnings.showwarning != self._showwarning:` + `'NoneType' object has no attribute 'showwarning'` implies that somehow `import warnings` didn't happen the second time in your `runfile` command. What happens if you add `import warnings` before `import astropy` in your `ap.py`? (If this has been suggested and tried on FB, I apologize for the repetition.)

**Comment by drdavella** [comment]
Some googling with terms like `User Module Reloader` and `NoneType` gives me the sense that this is a `Spyder` issue, and not an issue specific to astropy.

**Comment by drdavella** [comment]
For example, a similar issue was reported here: https://github.com/EMS-TU-Ilmenau/fastmat/issues/27

**Comment by dhomeier** [comment]
Thanks, that could provide useful information - I had only found an older issue about silencing the reload messages altogether.
I think it is entirely possible, even likely, that the bug is on the `Spyder` side, but thought maybe someone familiar with the `Astropy` import mechanism could shed some light on the problem.
In any case the exception does not show up with just any type if import.

**Comment by drdavella** [comment]
@dhomeier thanks for the information. I'm inclined to close this since it does seem like a `Spyder` issue. Based on the similar issues that I found, it also sounds like it is only a problem with `Spyder` when using Python 2.

**Comment by dhomeier** [comment]
The second example occurred using `Python 3`, so I'd suggest to add a note on this somewhere in the documentation - the workaround is easy enough to implement and should not have any drawbacks, unless someone wants to work on `Astropy` code itself in `Spyder` (which does not appear to be the case ;-).

**Comment by drdavella** [comment]
@dhomeier yes of course, sorry I missed that. Regardless, `astropy-1.2.x` is no longer being supported, so unless you can show that this happens with a more recent version of astropy in a Python3 `Spyder` environment, I would still argue that no action needs to be taken.

**Comment by dhomeier** [comment]
I would argue that as long as `Python 2` is still supported, and still the only available version for many users (especially beginners like the OP), this should be sufficient to include a warning/recommendation.
But I will ask our sysadmin to install the `python3-devel` package on the system next and try to update to `astropy-2.0.5` for `Python 3`.

**Comment by bsipocz** [comment]
@dhomeier - For Python 3, you already have 3.0.1

**Comment by pllim** [comment]
Why use `pip3.4`? Why not `pip3.6` or the like?

**Comment by dhomeier** [comment]
Because it is not available on that system - when I wrote "current highest version" I meant `python-3.4.6` is the released version on openSUSE Leap 42.3.

**Comment by pllim** [comment]
Ah, okay. Thanks for the clarification. A quick search brought me to this Gist with instructions to install Python 3.6 on that distro -- https://gist.github.com/antivanov/01ed4eac2d7486a170be598b5a0a4ac7 . Is this an acceptable workaround for you?

**Comment by dhomeier** [comment]
Thanks, seems a bit excessive just to prove if a bug that _may_ have disappeared in `3.x` still exists, but having a `Python 3.6` environment could still come in useful.
The installation of `3.6.5` has succeeded so far, but to use it I will need to get the `python3-virtualenv` package to be installed.

**Comment by dhomeier** [comment]
OK, I found that `Spyder` just did not reload `astropy` on my Mac because it skips all modules installed under the system path. After disabling that, I could reproduce the crash under MacOS in `Python 2.7.14` for `astropy 2.0.5`. Whereas under both `3.5.5` and `3.6.5` the `Spyder` reload works for `astropy` versions from `1.2.1` to `3.0.1`.
Makes it likely that `Python 3` in general is indeed not affected by the bug - my guess is the `import _compiler` error under Linux was rather caused by the library being compiled under an older OS version, although I don't understand then why the import succeeded the first two times...

**Comment by pllim** [comment]
Thank you for investigating! If you feel like this is useful to be documented under http://astropy.readthedocs.io/en/latest/known_issues.html , PR is welcome.

**Comment by dhomeier** [comment]
Pushed to #7374.
