### ISSUE TITLE
Add astropy_helpers version info to the test header

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#7385]
to make my life easier when debugging packages with helpers related issues

**Comment by pllim** [comment]
This might be more complicated than I thought.

* astropy_helpers are not actually installed with astropy; that is, I cannot find it in the installation directory of astropy.
* helpers are apparently only used during setup and disappear after that.

The true fix might need to go on the helpers side. For instance, during setup, helpers would write its own version in the package `version.py`.
