### ISSUE TITLE
Inverse variance equivalent of astropy.nddata.StdDevUncertainty

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#7405]
I frequently have to work with spectroscopic data that expresses uncertainty in terms of inverse variance, but I can't find the equivalent of `astropy.nddata.StdDevUncertainty`. I propose to add such a class if no such feature or branch already exists.  See also spacetelescope/specviz#355.

**Comment by bjweiner** [comment]
See https://github.com/astropy/astropy/pull/6971 ?

**Comment by saimn** [comment]
#6971 added `VarianceUncertainty` and `InverseVariance`, so I think this can be closed ?
