### ISSUE TITLE
I/O performances monitoring

### ISSUE THREAD

**Issue by QLeB** [astropy/astropy#7406]
When copying a fits file using astropy, we do not see the corresponding read operations.
The used scripts is the following:

```
from astropy.io import fits

hdulist = fits.open('input/foo.fits', mode='readonly')
hdulist.writeto('output/foo.fits')
hdulist.close()
```

/proc/PID/io and strace reports a few MB read while the fits file is larger than 10 GB. How is the fits file copying managed by astropy, and how does it read the input file?

**Comment by pllim** [comment]
Does this section answer your question -- http://astropy.readthedocs.io/en/stable/io/fits/index.html#working-with-large-files ?

**Comment by QLeB** [comment]
Not really, I tried with both with memmap=True and memmap=False, the result is the same. And in both cases the file has to be read at some point... or maybe I missed some point.

**Comment by saimn** [comment]
If the data was not loaded before writing, it is read as a byte array and written to the file with numpy's `.tofile` method. So you should see bytes read in /proc/PID/io (I do see bytes corresponding to the file size).

**Comment by QLeB** [comment]
Thank you for the details. Would you have an example of script + fits file so that I can reproduce it ? In all the tests I did, for 1 GB fits file, /proc/PID/io reported a wchar of the fits file size, but rchar was only a few MB.
