### ISSUE TITLE
Parallax equivalency shouldn't allow negative parallax, or set those to NaN!

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#7408]
Right now:
```python
>>> (-10*u.mas).to(u.pc, u.parallax())
-100 pc
```
Which leads to some really weird behavior if you pass in positions and distances!
```python
>>> coord.ICRS(ra=150*u.deg, dec=-11*u.deg,
...            distance=(-10*u.mas).to(u.pc, u.parallax()),
...            pm_ra_cosdec=10*u.mas/u.yr,
...            pm_dec=10*u.mas/u.yr)
<ICRS Coordinate: (ra, dec, distance) in (deg, deg, pc)
    (330., 11., 100.)
 (pm_ra_cosdec, pm_dec) in mas / yr
    (10., 10.)>
```

Note the change in ra, dec! Still debugging *why* this happens...

**Comment by mhvk** [comment]
@adrn - I think the conversion is actually correct! But it would be good to catch negative distances. Possibly, all that is required is to ensure they actually use the `Distance` class (would need to be in the frame initializer)

**Comment by adrn** [comment]
I think it has to happen at the `Representation` level. Right now, `SphericalRepresentation` only returns a distance using a view of the internal `Quantity` object that stores the distance data, and the view doesn't enforce rules in the `Distance` initializer, for example:

```python
>>> Distance(-100*u.pc)
ERROR: ValueError: Distance must be >= 0.  Use the argument 'allow_negative=True' to allow negative values. [astropy.coordinates.distances]
>>> (-100*u.pc).view(coord.Distance)
<Distance -100.0 pc>
```

So the question is, do we want to stuff the distance data into a `Distance` object in the `SphericalRepresentation` initializer?

**Comment by mhvk** [comment]
Maybe easiest is to replace the `view` with `Distance(self._distance, copy=False)`?

I guess a more general question is how we should deal with large tables of coordinates where some parallaxes are negative...

**Comment by mhvk** [comment]
In the latter respect, perhaps the equivalency is the right place? We could set the distance for any negative parallax to `inf`...

**Comment by eteq** [comment]
@mhvk - as something quick for feature freeze to partially get at this, perhaps your last suggestion could be done? (since that might be a near-trivial one-off)

**Comment by eteq** [comment]
In some slack discussion with @adrn... Actually probably a negative parallax should yield `NaN` rather than `inf`.

**Comment by astrofrog** [comment]
@eteq - it's worth thinking about this in the context of ``Distribution`` - i.e. if you create a distribution for a parallax from a normal distribution which would occasionally create negative values. I think NaN would be easier to filter out from stats, so I agree NaN makes more sense than Inf.

**Comment by mhvk** [comment]
Agreed on `NaN` being better than my earlier suggestion of `inf`; explicit is better than implicit and all that.
