### ISSUE TITLE
Cutout2D: Inconsistent array convention (needs documentation)

### ISSUE THREAD

**Issue by msgordon** [astropy/astropy#7414]
The ordered pair convention for Cutout2D is inconsistent and somewhat surprising.  While the `position` argument is specified as `(x, y)`, the `size` argument is reversed.  From the documentation:

> If `size` has two elements, they should be in `(ny, nx)` order.

  While the `(y, x)` order is standard convention for most numpy/scipy functions, it is not intuitive to specify the position and size in reverse order from each other within the same function call.

**Comment by pllim** [comment]
This might be one of those "the ship has sailed" kind of things, but I'll let @mwcraig , @crawfordsm , or @MSeifert04 chime in.

**Comment by bsipocz** [comment]
Adding the label as per the comment above.

**Comment by mwcraig** [comment]
@larrybradley may have opinions here too...

**Comment by hamogu** [comment]
I agree that it's probably too late to change, but at least we should make it more obvious in the docs that this is inconsistent. (And add it to the list of things we'll break if we ever do a python2->python3 style backwards-breaking step).

**Comment by pllim** [comment]
> And add it to the list of things we'll break if we ever do a python2->python3 style backwards-breaking step

@hamogu , can you please clarify? What does `x, y` ordering have to do with PY2-PY3 transition? Also, we already removed PY2 support in `master`, so everything breaks in PY2 now unless you stick to v2.x series.

**Comment by pllim** [comment]
Ah, gotcha! For now, I'll mark this as a documentation issue.

**Comment by SG004** [comment]
I am extraordinarily new at this, but I would like to make a pull request for this, if you'd let me.

**Comment by astrofrog** [comment]
@SG004 - yes feel free to open a pull request! As noted in the comments above, this is about clarifying things in the documentation not changing the behavior of Cutout2D

**Comment by larrybradley** [comment]
To play devil's advocate 😈 , what would you want to change?  Input *positions* (not *indices*!), especially for a 2D array, are commonly expected to be in `(x, y)` order and that agrees with the API of other packages (e.g. `matplotlib`, `photutils`).  Similarly, shape or size parameters are usually expressed (e.g. `scipy` and `numpy` functions) in axis (e.g. `(y, x)`) order.  I agree that this is a potential source of confusion and it should be very well documented, but I think the API is actually consistent with other packages/functions with regard to the inputs.  I can't think of any other function offhand where both position and size/shape are inputs.

**Comment by msgordon** [comment]
You're right that the position and shape orderings are not inconsistent with conventions in other libraries.  However, the original reason for my post is that I can't remember any library where the orderings are mixed within the same function call.  From the discussion here, it sounds like a potential solution is a very clear warning bubble or something.
