### ISSUE TITLE
Async operations in astropy

### ISSUE THREAD

**Issue by manodeep** [astropy/astropy#7418]
This might be more of an APE than an issue but are there any plans for creating `async` functions?

`async` operations are available in `python >= 3.4` (I think) and are an efficient way of parallelizing slow tasks in chunks. Here is python3 docs for [asyncio](https://docs.python.org/3/library/asyncio-task.html)

**Comment by astrofrog** [comment]
I don't think there's any reason no too - I guess the question is what the implications are, whether we have to maintain sync and async versions of different functions or whether it's not much code overhead. Indeed an APE might be needed.

**Comment by manodeep** [comment]
I think having to maintain two separate code-bases (or using source loading and modifications) might be required. 

From what I have heard, once you write async operations, everything needs to be async. 

Perhaps make a separate affiliated package that provides some asyncio tools for now?

**Comment by pllim** [comment]
I am adding the "needs clarification" label simply to indicate it awaits specs in the aforementioned APE. :smiley:

**Comment by saimn** [comment]
It is not clear to me, where this could be useful, and how it can be an "efficient way of parallelizing slow tasks in chunks" ? I mean, asyncio - for instance - is not the right tool to parallelize cpu-intensive tasks.

**Comment by pllim** [comment]
Following your mantra of "don't do this if you don't have to", I would also like to inquire of exactly which part of Astropy do you wish to make async?

**Comment by manodeep** [comment]
I am not the expert in `async`; however, `asyncio` is almost certainly going to be an improvement while reading and processing files. 

@saimn Generally speaking, `async` is preferred where there is some large latency involved -- previously, this would be network comm or disk io. However, even with cpu-intensive tasks, processes are expensive to spawn, while `async` ops are cheaper **and** do not un-necessarily waste cpu time. 

@pllim I wish for all of astropy to be async starting with astropy.io. Just note that I am not offering to do any of it. My earlier talk with @bsipocz and @eteq seemed to imply that `async` was not on the astropy development horizon -- hence this issue.

**Comment by saimn** [comment]
@manodeep - AFAIK, asyncio does not support disk IO (https://github.com/python/asyncio/wiki/ThirdParty#filesystem) though there may be workarounds. So it can be useful for network IO, but it is imo a limited use case of Astropy, and other than that coroutines doing computation with Astropy will just block the event loop. Processes are expensive but it is not the same thing, they allow to do parallel computations, which is not the case for asyncio (or multi-threading with Python in general, except if you call some C code that release the GIL)

**Comment by manodeep** [comment]
@saimn I am not sure. Seems to me that `os.pread` with chunks should be `async`-able. But not quite sure

Writing in C/Cython definitely helps with releasing the GIL and using `OpenMP/pthreads` but that's not necessarily always available

**Comment by Cadair** [comment]
asyncio in Python is still single-threaded and can't be used to parallelize compute. It would be possible to use asyncio to do things like parallel file downloads or possibly parallel file IO if the support is there.

It would be theoretically possible for someone to write a multi-processing library (using multiple python processes or similar muti-threaded primitives) and use the `async def` and `async await` language features of Python 3.5 to provide a nice interface for doing it, but that isn't asyncio.

**Comment by manodeep** [comment]
@Cadair I am not sure I understand. You should be able to `async/await` many `os.pread` function calls, for instance. 

Let me back up -- my intention was to initiate a conversation about async ops in astropy, since I did not hear any plans about `async`. How that exactly is implemented, or a discussion about semantics of `asyncio` vs `async` might be something for slightly farther down the line.  Does that make sense?

Or perhaps, the rough consensus amongst core developers is that `async` is not getting into `astropy` in the near future.

**Comment by Cadair** [comment]
@manodeep I don't mean to come off hostile here, I think that given the focus of the 3.1 cycle in astropy on performance, it's a worthwhile discussion to have. Also, I only have limited experience with async / asyncio in regards to using it for HTTP requests in projects related to file downloading and Matrix. I would be interested to know if you have suggestions of how async code could speed up either operations internal to astropy or how providing a coroutine API to users would help them in various situations.

The main issue I have is that I don't personally see very many places in astropy where using *asyncio* would be appropriate. I am working on a parallel file downloader, with the intention of SunPy using it ([parfive](https://github.com/Cadair/parfive)) something like this could be useful for the file downloading utils in astropy, or something more web-download focused like astroquery.

As for file IO, I would expect that astropy wouldn't need to support asyncio for you to be able to use it with file IO. If you could do an asyncio version of `open()` and then call `io.fits` inside a coroutine, I would think that would be all you need. I haven't ever looked into file IO with asyncio though, so I don't know. From my experience with asyncio I would expect you to be opening many files in parallel to get a benefit from using asyncio.

**Comment by bsipocz** [comment]
> something more web-download focused like astroquery.

we already try to deal with raw http responses via async methods, I suppose any more than that needs to be supported from the server side anyway but then we better switch to use vo tools internally anyway.

**Comment by Cadair** [comment]
asyncio is good for any interaction over the network where you are doing more than one thing at once, as you can continue processing something while you wait for a server to do something or for a network buffer to fill up with data. It dosen't actually require serverside support to be advantageous.

**Comment by manodeep** [comment]
@Cadair Yeah I did feel attacked a bit over there. Thanks for clarifying! I know its always hard to get the tone correctly in plain text...

What I understand of `async` is close to what is explained on this [SO item](https://stackoverflow.com/questions/4024056/threads-vs-async). But like you said, async works best on high-latency tasks. I was thinking of working on supercomputers and lustre file systems, where individual files are likely to be stored across multiple storage units and there multiple parallel async calls should absolutely speed up the reads. With async implementations, you are probably not going to get large benefits on personal laptops (but hopefully no performance penalties either) but then those same async ops should produce significant speedups on supercomputers. 

I would be hesitant to implement existing astropy routines as async, I think async and sync are two different paradigms of coding and those two should preferably not mix. 

In terms of user-experience, what are the tasks that the average astropy user does -- do they deal with lots of little files, or do they deal with a few large files etc. Do you guys have a rough idea?

And yeah, overlapping communication and compute is a standard strategy for improving performance in MPI codes.

**Comment by bsipocz** [comment]
@manodeep - Usage information (especially to figure out what the average user is like) is a very tough thing to get. I'm happy to collect any ideas how to get that info, or what questions to ask (but as it's offtopic here, either shoot me an e-mail or use the #performance channel on slack).

**Comment by manodeep** [comment]
@bsipocz Yup you are absolutely right.

**Comment by pllim** [comment]
Re: usage info -- Is this something we can obtain from the performance survey that @taldcroft sent out a while ago? (We sent it out, right?)

**Comment by bsipocz** [comment]
@pllim - I've though the exact same thing yesterday, and the survey hasn't been sent out yet. Though the current one is deliberately kept short, so I didn't see a way how to ask any of these questions. Maybe you want to raise this before it's sent out?

**Comment by pllim** [comment]
Now after 7 years, with dask and what-nots, is this issue still relevant?

**Comment by manodeep** [comment]
Hey thanks for cleaning up. The issue is certainly not relevant any more - closing!

**Comment by astrofrog** [comment]
Yes SAMP does seem a relevant use case for async

**Comment by pllim** [comment]
You can but also note that there is a long standing plan to move SAMP to PyVO:

* https://github.com/astropy/astropy/issues/9763

cc @tomdonaldson
