### ISSUE TITLE
Request: Add FITSDiff-like functionality for Tables

### ISSUE THREAD

**Issue by stsci-hack** [astropy/astropy#7442]
The comparison of FITS files with FITSDiff provides users with a flexible interface to work with a variety of FITS files with considerable control of what gets compared resulting in a reasonably concise report.  Unfortunately, not all use of astropy results in FITS files that can take advantage of these capabilities.   The alternative solution comes back to Python's difflib provides a *nix-like comparison of random ASCII files which can result in awkwardly long and hard-to-decipher outputs.

With all the work done to provide enhanced functionality for Astropy Tables, having a FITSDiff-like comparator for tables would, ideally, expand on Table's 'set_difference' to also report on additional differences in a manner similar to what FITSDiff produces.  This would enable testing to produce more consistent and easier-to-interpret reports for both FITS binary files as well as Astropy Table objects.   For example, FITSDiff reports missing or additional column names, as well as differences in values found in the rows of the table.  FITSDiff also reports on differences in the metadata (header values) for the table and formats all the differences in an organized manner.  This level of functionality does not appear to be possible with the current Table package. 

Admittedly, this request does not come with specifics, but is just intended to serve as a starting point for the discussion on implementing this additional functionality.

**Comment by pllim** [comment]
Turns out I might have found a solution in `astropy.io.fits.diff`.

```python
from astropy.io.fits.diff import report_diff_values
report_diff_value(table1, table2)  # table1 = Table.read(...)
```

PR is forthcoming to move `report_diff_value` out of FITS into a more generic sub-package (`utils`). From there, it is a matter of documentation update to use it for tables, I think. :crossed_fingers:

**Comment by bsipocz** [comment]
#7444 exposed the existing functionality to the public API as well as added documentation on it, so I'm closing this issue now.
