### ISSUE TITLE
Extraneous \mathrm in LaTeX formatted Angle

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7454]
In the following example, the ``\mathrm`` isn't needed - is this a bug or is there a reason that it's included?

```python
In [1]: from astropy import units as u

In [2]: from astropy.coordinates import Angle

In [3]: a = Angle(2.3, 'deg')

In [4]: newdeg = u.def_unit('custom_degree', represents=u.degree, format={'latex': r'^\circ'})

In [5]: a.to_string(unit=newdeg, precision=0, decimal=False, format='latex', sep='fromunit')
Out[5]: '$2\\mathrm{^\\circ}$'
```

**Comment by pllim** [comment]
Did you try `git blame`? :smile:

**Comment by astrofrog** [comment]
I don't know if it's a regression though

**Comment by mhvk** [comment]
Looking through issues assigned to me: agreed that this is a bit strange, but I think it is mostly to ensure units are always in roman type. If we were to remove this, e.g., units of micro-arcsec and hour, Rsun, etc., would all look different (or would need to have an explicit `mathrm` included in their string). Seems more effort than it is worth...
