### ISSUE TITLE
Space between value and unit

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7455]
Currently, ``Angle.to_string`` doesn't include a space between the value and unit:

```python
In [30]: from astropy.coordinates import Angle

In [31]: a = Angle(3, 'deg')

In [32]: a.to_string(unit='mas')
Out[32]: '1.08e+07mas'
```

I think there are cases where it would make sense to allow a space to be included, so this is a feature request to add a boolean keyword argument to optionally add a space.

Note that Quantity does include a space by default so maybe actually we should just change the default and not add an option?

```python
In [17]: str(3 * u.mas)
Out[17]: '3.0 mas'
```

**Comment by pllim** [comment]
:+1: for consistency between Quantity and Angle (by having space as default).

However, if you worry about backward compatibility, maybe instead add an option for "old style" (without space), but would that be useful for anyone?

**Comment by astrofrog** [comment]
Well the one place where we *don't* want a space is when using a symbol, e.g. ``3.4"``

**Comment by pllim** [comment]
Re: symbol -- Nothing some `regex` wouldn't fix... :wink: (*show self to door*)

**Comment by larrybradley** [comment]
@astrofrog I think we should use a space by default (probably the most common use case), and then add a boolean keyword argument to optionally not include a space (e.g. `3.4"`).

**Comment by astrofrog** [comment]
I agree!

**Comment by daspartho** [comment]
can i work on this

**Comment by Telomelonia** [comment]
> 👍 for consistency between Quantity and Angle (by having space as default).
> 
> However, if you worry about backward compatibility, maybe instead add an option for "old style" (without space), but would that be useful for anyone?

@pllim I have implemented your idea in the PR attached; please see to it.
