### ISSUE TITLE
Refactor utils.diff.report_diff_values

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7468]
@mcara suggested some refactoring in https://github.com/astropy/astropy/pull/7444#issuecomment-387896174 . While you are at it, also maybe investigate whether https://github.com/astropy/astropy/pull/7444#discussion_r186866768 is possible without breaking regression.

p.s. As long as this gets in for 3.1, it is considered "affects dev" and does not need a change log. This is a direct follow up of #7444.

**Comment by mcara** [comment]
Hm... 'Package-novice' ... thanks!

**Comment by pllim** [comment]
Ahaha... At first I thought since everything was hashed out back in #7444 comments, it would be easy job, but now I am not so sure... I'll update the label. :sweat_smile:

**Comment by mcara** [comment]
It's ok, don't modify it. It was a joke.

**Comment by mcara** [comment]
It is certainly not expert level, except for figuring out how a 25-element array can have 625 differences.

**Comment by pllim** [comment]
Nothing is ever easy with FITS, so just in case...
