### ISSUE TITLE
Using fixed_width makes ascii.write() hang for a large Table

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#7477]
I have a Table with ~200 columns and ~40000 rows. Any of these statements write the file (~50 Mb) in about 22 seconds:

```
ascii.write(table_dat, output='temp.dat', overwrite=True)
ascii.write(table_dat, output='temp.dat', overwrite=True, delimiter=' ')
ascii.write(table_dat, output='temp.dat', overwrite=True, delimiter=' ', fill_values=[(ascii.masked, '--')])
ascii.write(table_dat, output='temp.dat', overwrite=True, delimiter=' ', fill_values=[(ascii.masked, '--')], formats={'d_a': '%.4f'})
```
If I try to use this one:

    ascii.write(table_dat, output='temp.dat', overwrite=True, format='fixed_width')

it just sits there doing nothing for minutes (until I shut it down). I can upload the Table as a `pickle()` object if someone wants to test this.

**Comment by taldcroft** [comment]
@Gabriel-p - humm, I can't seem to reproduce the problem.  I made a table with ~200 columns and 40000 rows, with an even mixture of int, float, and string columns.  The write time was about 32 sec on my Mac (with an old physical disk drive).  It was linear with the number of rows.

Can you try reducing the rows and see if it is a memory issue?  `ascii.write(table_dat[:1000], ..)`, `ascii.write(table_dat[5000:], ..)`.

Here is exactly what I did:
```
In [40]: i = np.arange(40000)

In [41]: f = np.arange(40000, dtype=np.float)

In [42]: s = np.array(list(range(40000)), dtype='U')

In [43]: t = Table([i, f, s] * 67)

In [44]: len(t)
Out[44]: 40000

In [45]: len(t.colnames)
Out[45]: 201

In [46]: time ascii.write(t, 'junk.dat', format='fixed_width', overwrite=True)
CPU times: user 30.4 s, sys: 884 ms, total: 31.3 s
Wall time: 31.7 s
```

**Comment by taldcroft** [comment]
BTW, worth checking memory during your fixed width write that hangs.  If you get into swapping for some reason then things can bog down completely.

**Comment by Gabriel-p** [comment]
It's not a memory (or CPU) problem, I checked. The Table [I attach](https://github.com/astropy/astropy/files/2015305/temp_6min.dat.zip) took ~6 min to generate using

    ascii.write(n_table, output='temp.dat', overwrite=True, format='fixed_width')

but only ~5 sec if I use

    ascii.write(n_table, output='temp.dat', overwrite=True, format='csv')

**Comment by pllim** [comment]
> took ~6 min to generate

Try run that in a profiler. Usually the bottleneck becomes obvious.

**Comment by saimn** [comment]
```
In [6]: %time ascii.write(t, output='temp.dat', overwrite=True, format='csv')
CPU times: user 1.35 s, sys: 32.8 ms, total: 1.38 s
Wall time: 1.39 s

In [7]: %time ascii.write(t, output='temp.dat', overwrite=True, format='fixed_width')
CPU times: user 1min 26s, sys: 319 ms, total: 1min 26s
Wall time: 1min 26s
```
csv has a fast (C) writer I think, but not all formats have a fast version. That 's probably the reason ?

**Comment by Gabriel-p** [comment]
@pllim I'll do that and paste the results here.

@saimn you clearly have a much faster laptop than mine, but I think that your results confirm what I'm seeing?

**Comment by saimn** [comment]
@Gabriel-p - Yes, the ratio between the 2 formats is similar. And this is indeed because by default the csv format use a fast writer, coded in C:
```
In [6]: %time ascii.write(t, output='temp.dat', overwrite=True, format='csv', fast_writer=True)
   ...: 
CPU times: user 1.24 s, sys: 39.9 ms, total: 1.28 s
Wall time: 1.28 s

In [7]: %time ascii.write(t, output='temp.dat', overwrite=True, format='csv', fast_writer=False
   ...: )
CPU times: user 1min 30s, sys: 172 ms, total: 1min 30s
Wall time: 1min 30s
```

**Comment by Gabriel-p** [comment]
That settles the issue then, I'll close it. Thank you both!
