### ISSUE TITLE
Unit test tries to write to installed library directory

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#7479]
This is a re-incarnation of #7201: 

One `astropy.io.fits` unittest tries to write to a file in the installed library. This fails if one tries to run the test suite without write access to them, f.e. as an ordinary user for a system wide installation.

This makes the [continuous integration test](https://ci.debian.net/packages/a/astropy/unstable/amd64/) of Astropy in Debian fail. From the [test log](https://ci.debian.net/data/autopkgtest/unstable/amd64/a/astropy/313486/log.gz):
```
___________________ TestFileFunctions.test_open_file_handle ____________________

self = <astropy.io.fits.tests.test_core.TestFileFunctions object at 0x7f5ef3304b00>

    def test_open_file_handle(self):
        # Make sure we can open a FITS file from an open file handle
        with open(self.data('test0.fits'), 'rb') as handle:
            with fits.open(handle) as fitsfile:
                pass
    
        with open(self.temp('temp.fits'), 'wb') as handle:
            with fits.open(handle, mode='ostream') as fitsfile:
                pass
    
        # Opening without explicitly specifying binary mode should fail
        with pytest.raises(ValueError):
            with open(self.data('test0.fits')) as handle:
                with fits.open(handle) as fitsfile:
                    pass
    
        # All of these read modes should fail
        for mode in ['r', 'rt', 'r+', 'rt+', 'a', 'at', 'a+', 'at+']:
            with pytest.raises(ValueError):
>               with open(self.data('test0.fits'), mode=mode) as handle:
E               PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/astropy/io/fits/tests/data/test0.fits'

/usr/lib/python3/dist-packages/astropy/io/fits/tests/test_core.py:613: PermissionError
```
Pinging @mangalagb (who was so keen to fix #7201) to have a look here as well?

**Comment by saimn** [comment]
This was added by @drdavella almost one year ago, so why does it fail only now ? Did you change the test setup ?
Also it's Python's `open`, not `fits.open`, so the issue is just that opening a file in read-write mode (`r+` etc.) is not possible if the file is read-only. So maybe we can just skip the write modes if the file is not writeable ?

**Comment by saimn** [comment]
Otherwise we can copy the file in the temp directory.

**Comment by olebole** [comment]
I had the test disabled up to now because of #7201, so in fact it was not a recent regression. Reopening that one would probably have been better, sorry.
For copying, there is already something in #7305, which just could be extended.

**Comment by drdavella** [comment]
It seems to me that this is maybe a sign that the custom test harness in the `fits` subpackage is less than ideal and we should be using `pytest` fixtures for temporary directories instead.

**Comment by astrofrog** [comment]
Yes I think it's time to switch io.fits to use ``tmpdir``...

**Comment by saimn** [comment]
fits' `self.temp` method is the same as `tmpdir` basically, what is missing is a helper method (or fixture, but switching to pytest fixtures is a lot of work) which copies a data file to the temp dir and return the temp path.

**Comment by mangalagb** [comment]
Sorry @olebole was out of town and did not keep up with the emails. Looks like this issue is closed. I'll pick up something else.
