### ISSUE TITLE
Inconsistent documentation of `bounds` parameter in modeling classes

### ISSUE THREAD

**Issue by swapsha96** [astropy/astropy#7492]
Currently to set `bounds` parameter in `Lorentz1D` class takes a dictionary with parameter name as key and min, max as _both_ tuple and list. But in docs, it is not mentioned clearly. The detail is also different in its base class. I have put the sections below:

![screen shot 2018-05-23 at 23 23 13](https://user-images.githubusercontent.com/14021461/40443525-37d72526-5ee4-11e8-86a6-e4c0a93419c6.png)
**Description in `Lorentz1D1 doc page**

![screen shot 2018-05-23 at 23 23 58](https://user-images.githubusercontent.com/14021461/40443529-3ec67b52-5ee4-11e8-930e-95f8162f3dc9.png)
**Desctription in base class**

As @astrofrog suggested, it should be either `{parameter_name: (min, max)}` or `{parameter_name: value}`

@pllim suggested adding example(s) for the same in the documentation.

I would like to work on this.

**Note:** I used the parameter and it supports both tuple and list as value.

**Comment by pllim** [comment]
PR is welcome! And hopefully http://astropy.readthedocs.io/en/latest/development/workflow/development_workflow.html would help you along in the workflow. Thank you.
