### ISSUE TITLE
Commit #efaa3b3 breaks rendering of legends

### ISSUE THREAD

**Issue by giacomov** [astropy/astropy#7504]
Commit efaa3b3 breaks the plotting of legends:

```python
import astropy.units as u
from astropy import visualization
visualization.quantity_support()

import matplotlib.pyplot as plt

fig, sub = plt.subplots()

sub.plot([1,2,3] * u.m, [4,5,6] * u.s, label='test')

sub.set_xlim([0 * u.m, 3*u.m])

sub.legend(loc='best')

# This crashes
plt.show()
```
This is the error:
```
  File "/home/giacomov/work_env/local/lib/python2.7/site-packages/astropy/visualization/units.py", line 86, in convert
    return [v.to_value(unit) for v in val]
AttributeError: 'float' object has no attribute 'to_value'
```

The culprit is this code, added with efaa3b3 : 
```python
elif isinstance(val, list):
    return [v.to_value(unit) for v in val]
```
The error is triggered because the legend tries to find the coordinate to draw itself, providing a list of coordinates that does not contain units.

Indeed, I believe this can be fixed by using  a recursive approach:

```python
elif isinstance(val, list):
    return [MplQuantityConverter.convert(v, unit, axis) for v in val]
```

so that the checks contained in `convert` are applied to each member of the list.

I tested that this fixed the problem reported above.

**Comment by dstansby** [comment]
Ahh sorry about this! @giacomov which versions of astropy and Matplotlib are you using? I cannot reproduce this using the `master` branches of both, but I *suspect* that your code will work with a certain minimum version of Matplotlib.

**Comment by dstansby** [comment]
Yep, I can reproduce the error on mpl `2.1` because the improved unit handling requires https://github.com/matplotlib/matplotlib/pull/10206 , which went into Matplotlib `2.2`. @giacomov if possible you can fix the problem by upgrading Matplotlib to >= 2.2 for now.

@pllim does astropy have a minimum Matplotlib requirement? If it's >= 2.2 then this bug can be considered fixed, if not I can look into a workaround for versions < 2.2

**Comment by dstansby** [comment]
👍 I'll try and put together a patch

**Comment by giacomov** [comment]
Thanks! 

The fix I propose above (using recursion on the list) fixes the problem for me, it should also work in general since it just applies the same logic you apply on a single value to each element of the list.
