### ISSUE TITLE
Output log in circleci too long to read in browser

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#7511]
e.g. https://circleci.com/gh/dstansby/astropy/46?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The output log is *really* long, so long that you have to download it to get to the end. There must be a ~~verbose~~ quiet option that can be thrown in there somewhere to shorten the log.

**Comment by Cadair** [comment]
I don't think there is much you can do on the circleci side.

**Comment by dstansby** [comment]
I think the problem is the bit where astropy gets installed fresh prints lots of lines. Maybe that bit could be made quiet?

**Comment by pllim** [comment]
FWIW I downloaded that log for #7510 and it is 611 KB. The traceback is rather long as well due to `pytest` deprecation warnings everywhere.
