### ISSUE TITLE
An ignore_hdus parameter in FITSDiff would be useful

### ISSUE THREAD

**Issue by jdavies-st** [astropy/astropy#7516]
A very useful feature of fitsdiff would be the ability to ignore certain HDUs within the FITS file(s) that you don't want to compare, much like `ignore_keywords` does for header keywords.  These could be specified by either their FITS name (and version), or perhaps number or type.  Name seems the most sensible though.

So say I had two FITS files that were identical except for an extra extension that had some runtime-dependent processing info in it named "TELEM" of type BinTableHDU, and I'd like to ignore it when doing the fitsdiff:
```
fitsdiff --ignore_hdus=TELEM file1.fits file2.fits
```

**Comment by pllim** [comment]
What if there is a `('TELEM', 1)` and a `('TELEM', 2)`? What should be the expected behaviour? Should it be allowed to check `('TELEM', 1)` but not `('TELEM', 2)`?

**Comment by jdavies-st** [comment]
In the command above, I might expect it to ignore all `TELEM` HDUs.  Not sure how one would pass versions in the list of HDUs, or in a wildcard.  Is that done elsewhere in the FITS library?

**Comment by pllim** [comment]
Certain FITS options do accept wildcard, but I don't remember what is where now. @SaOgaz , since you added that `printdiff` thingy not too long ago, do you remember?

**Comment by saimn** [comment]
It's true that it's annoying when one FITS has one more HDU which breaks the assumption that both files have exactly the same HDUs. So :+1: from me for `--ignore_hdus` (with a comma-separated list of HDU names ? or should it be `--ignore_hdu` which could be added multiple times ? ).

**Comment by jdavies-st** [comment]
Maybe a first crack at this would implement a simple `--ignore_hdu_names` switch that would take a comma-separated list of HDU names, much like `--ignore_keywords` currently does.  It could also take unix file system-type wildcards too, which again is also implemented in `--ignore_keywords`.

I think being able specify versions - i.e. compare `['SCI', 1]` but ignore ['SCI', 2]` - might have limited use cases?  Certainly my use case for this is to just be able to compare two FITS files which have a single HDU that I know changes from one processing run to the other, but I would still like to diff the FITS outputs, ignoring those differences.

**Comment by saimn** [comment]
`--ignore_hdus` with a list of HDU names seems the best solution to me, as it mimics the behavior of `--ignore_keywords`. Not sure how we could support extension numbers instead of names, as the numbers to ignore may not be the same in both files, so supporting only names seems good for now. 
And for HDUs with multiple versions (('TELEM', 1), ('TELEM', 2)), we could imagine having a special syntax to ignore only a specific HDU (`--ignore_hdus=TELEM:1`) ?

**Comment by jdavies-st** [comment]
Perhaps the most general case and simplest enhancement is what you suggest above and to ignore all 'TELEM' extensions?  This would certainly encompass my own use cases.

Not sure about a special syntax.  Obviously one can't easily use `--ignore_hdus=TELEM,1` as the comma is already in use.  At least not without some hairy parsing.  I'm happy to just ignore the EXTVER issue for now and implement based on HDU NAME.

**Comment by saimn** [comment]
> I'm happy to just ignore the EXTVER issue for now and implement based on HDU NAME.

Fine for me too !
