### ISSUE TITLE
Document the details of the performance enhancement from #7324

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#7521]
#7324 created a substantial speedup in the coordinate-matching functionality.  In https://github.com/astropy/astropy/pull/7324#issuecomment-392382719 @ideasrule  gave a good set of tests (suggested by @adrn) on this enhancement.  We should probably find someplace to record the results of these tests.  These could be put in as benchmarks on airspeed velocity?  Or possibly just documented in the coordinates docs?  Open to ideas...

**Comment by bsipocz** [comment]
Those should definitely be added to https://github.com/astropy/astropy-benchmarks

**Comment by pllim** [comment]
Shouldn't this be an issue or PR over at `astropy-benchmarks` instead?

**Comment by eteq** [comment]
Got point @pllim

**Comment by bsipocz** [comment]
Well, the "document the enhancement" part definitely belongs here, and the performance docs should be populated before 3.1, so I'm reopening.

**Comment by bsipocz** [comment]
@eteq - the matching improvements seem to be left out from the what's new summary. Do you still plan to include or shall we just close this issue?
