### ISSUE TITLE
Make scalar Time hashable

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#7532]
PR #7531 needs a hashable scalar time in order to index a table with a Time column using the  `sortedcontainers` package.  This is intended as a replacement for `bintrees` which is no longer maintained.

A zero-order implementation to get started is below.  This doesn't address a difference in `location` (but maybe not needed anyway?).  The nominal requirement for hash is *"The only required property is that objects which compare equal have the same hash value"*.  Since time values with different scales can be equal, it isn't immediately obvious to me how to implement this.  In theory maybe transform to TAI and hash `(jd1, jd2)`.  This of course could be expensive and performance killing for table indexing.

Thoughts @mhvk?
```
diff --git a/astropy/time/core.py b/astropy/time/core.py
index c99f913..ee7571d 100644
--- a/astropy/time/core.py
+++ b/astropy/time/core.py
@@ -789,6 +789,11 @@ class Time(ShapedLikeNDArray):
         self._time.jd1[item] = value._time.jd1
         self._time.jd2[item] = value._time.jd2
 
+    def __hash__(self):
+        if self.ndim != 0:
+            raise TypeError("unhashable type: '{}'".format(self.__class__.__name__))
+        return hash((self.jd1, self.jd2, self.scale))
+
     def light_travel_time(self, skycoord, kind='barycentric', location=None, ephemeris=None):
         """Light travel time correction to the barycentre or heliocentre.

**Comment by vn-ki** [comment]
SunPy needs `Time` to be hashable too! I had asked in slack group and was going to create an issue for this here, but forgot.

**Comment by mhvk** [comment]
@taldcroft - how much of a performance degradation is it to include location as well? Most of the time that will just be `None`, so I'd think that would be fast. And if it is set, one probably should include it...

I do agree that we have to include the scale; we cannot quite guarantee that scales exactly roundtrip anyway.

p.s.  I think you'd also need to include the mask.

**Comment by taldcroft** [comment]
@mhvk - I think we're on the same page.  I was actually surprised to see that, for at least one test case, times do round trip through scale transforms.
```
In [2]: t = Time(1.2234234234234324234, format='cxcsec')
In [4]: t2 = Time(1.2234234234234324234, format='cxcsec')
In [5]: t == t2
Out[5]: True

In [10]: for scale in t.SCALES:
    ...:     assert getattr(t, scale) == t
    ...:     
```
Maybe this doesn't hold in all cases.  And of course the scale matters for whether two times compare equal:
```
In [60]: t.location = EarthLocation(1e6*u.m, 0*u.m, 0*u.m)

In [61]: t2.location = EarthLocation(0*u.m, 0*u.m, 0*u.m)

In [62]: t == t2
Out[62]: True

In [63]: t.tdb == t2.tdb
Out[63]: False
```
So making a hash implementation that is precisely rigorous about giving the same hash for two objects which compare equal seems slightly non-trivial.  In fact, **impossible** since our time equality is not commutative:
```
In [64]: t == t2.tdb
Out[64]: True

In [65]: t.tdb == t2
Out[65]: False
```
So maybe we just go the simple route and hash `(jd1, jd2, scale, location)`, where `location` is made into a hashable version of the `location` attribute.  This will work for the use case of indexing, and comparing hash ids for elements of the same Time array.

**Comment by taldcroft** [comment]
And yes, something with the mask.

**Comment by mhvk** [comment]
@taldcroft - plan sounds good to me.

**Comment by mhvk** [comment]
Is this still needed? Note that `ndarray` are not hashable by default, so care has to be taken with `jd1` and `jd2` (scalars probably fine)

**Comment by Cadair** [comment]
SunPy could still make use of this if it were to exist. We already do a [cheap version of it](https://github.com/sunpy/sunpy/blob/master/sunpy/net/vso/attrs.py#L165) where we needed to.

**Comment by taldcroft** [comment]
See #8912
