### ISSUE TITLE
DOC: PyPI release edit instruction needs updating

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7534]
I don't think this works with new PyPI website anymore:

>Go to https://pypi.python.org/pypi?:action=pkg_edit&name=astropy and ensure that only the most recent releases in each actively maintained release line are not marked hidden. For example, if v1.2.2 was just released, v1.2.1 should be hidden. This is so that users only find the latest bugfix releases.
>
>Do not enabled “Auto-hide old releases” as that may hide bugfix releases from older release lines that we may still want to make available.

Can this whole step be removed, @bsipocz ?

**Comment by bsipocz** [comment]
Oh, yes, sure. We can chuck this to the rest of the need to be updated stuff in #5120 if you like, or can be addressed separately.

**Comment by pllim** [comment]
#5120 is too ambitious for me, as I don't have personal experience releasing `astropy` itself, but rather using your instructions for my own packages. However, I fixed this particular one at #7535.
