### ISSUE TITLE
Remove numpy hack in io.fits when Numpy minversion is 1.12

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7545]
I stumbled upon `io/fits/_numpy_hacks.py`, which has a comment that says it can be retired when numpy/numpy#6430 is merged. That Numpy fix was incorporated into Numpy 1.12, which means we can remove this hack when our `minversion` for Numpy is 1.12.

(I am tempted to set this to novice but I probably shouldn't.)

**Comment by bsipocz** [comment]
Given https://github.com/astropy/astropy/pull/7058, I'm milestoning this 3.1 to not to forget about it.

**Comment by astrofrog** [comment]
The best approach would probably be to modify the source code to explicitly have ``NUMPY_LT_112`` so that we can then search/replace whenever we update the minimum Numpy version.

**Comment by astrofrog** [comment]
This is not 'upstream fix required' since the fix has already been made, right?

**Comment by pllim** [comment]
Oh, I guess you don't need that label... I just wanted something to indicate that this depends on upstream changes but I guess it is unnecessary given the milestone.

**Comment by pllim** [comment]
> modify the source code to explicitly have NUMPY_LT_112

Seems unnecessary now, as @mhvk has removed it as part of #7058 :tada:
