### ISSUE TITLE
Possible bug with TNULL value being changed on FITS binary table to Astropy table roundtrip

### ISSUE THREAD

**Issue by SaOgaz** [astropy/astropy#7555]
I'm pretty sure this is my last `Tables` bug **crosses fingers**.

So once again, I'm in Astropy version 3.1.dev21825.

When I round trip a FITS binary table that has some columns with a TNULL keyword set, all the TNULL keyword values and all data that had the TNULL data value in the table, get changed to `999999`.  This only happens when I add (or update) a whole row at once.  This includes my final test that I'll post below where I add a new row, remove the new row, and save out the file.

It does NOT happen when I update a single value, change any of the masking, or add a new column.

Here's the code used to do the roundtrip and the fitsdiff output from the original vs the round tripped file:

```
def round_trip(filename, ext=1):
    with fits.open(filename) as fits_file:
        tab = Table.read(filename, hdu=ext)
        tab.add_row(tab[-1])
        tab = tab[:-1]
        new_tab = fits.table_to_hdu(tab)
        fits_file[ext] = new_tab
        fits_file.writeto(filename.replace(".fits","_rt.fits"), 
                          overwrite=True)
```

Fitsdiff:
![screen shot 2018-06-11 at 11 43 28 am](https://user-images.githubusercontent.com/5287848/41242144-c31fa3e2-6d6c-11e8-9424-dcc48ab2bcfb.png)

![screen shot 2018-06-11 at 11 43 40 am](https://user-images.githubusercontent.com/5287848/41242150-c57c81fa-6d6c-11e8-8c1c-f3e9f8f6b2b5.png)

![screen shot 2018-06-11 at 11 44 01 am](https://user-images.githubusercontent.com/5287848/41242153-c7463e22-6d6c-11e8-83de-e3cbf5c19a46.png)

**Comment by saimn** [comment]
Is it possible to have a look at your FITS file ? It could be something with unsigned integers, which could explain which the TNULL values are converted.

**Comment by SaOgaz** [comment]
Sure, what's the best way to get that to you?

**Comment by pllim** [comment]
Box?

**Comment by SaOgaz** [comment]
Does this work for you @saimn? https://stsci.box.com/s/q3ds53zpek45i9t2pmsclgm9k0wyutgx

**Comment by saimn** [comment]
@SaOgaz - No, it requires an account.

**Comment by pllim** [comment]
@saimn , do you see an interface to sign up?

**Comment by saimn** [comment]
@pllim - Yes:
![capture d ecran de 2018-06-15 22-39-37](https://user-images.githubusercontent.com/311639/41488564-0b0b9944-70ed-11e8-8a49-459f38152b94.png)

**Comment by SaOgaz** [comment]
Shared @saimn, sorry for the hassle :/

**Comment by saimn** [comment]
@SaOgaz - no problem ;)

So the fill values are changed by the `tab.add_row(tab[-1])` line:
```
In [1]: %astropy
Numpy 1.14.5
Astropy 3.1.dev21990
t
In [2]: t = Table([[1, 2, 3], [0.1, 0.2, 0.3]], names=['x', 'y'], masked=True)

In [3]: t['x'].fill_value
Out[3]: 999999

In [4]: t['x'].fill_value = -1234

In [5]: t['x'].fill_value
Out[5]: -1234

In [6]: t.add_row(t[-1])

In [7]: t['x'].fill_value
Out[7]: 999999
```

**Comment by SaOgaz** [comment]
@saimn, I might have time to try and fix it this week or next. Can't make any promises though.

**Comment by saimn** [comment]
For reference, there was a similar issue with indexing in #4707
