### ISSUE TITLE
Cutout2D tutorial: Add example to save cutout

### ISSUE THREAD

**Issue by kusmic** [astropy/astropy#7557]
I have only done this with the SkyCoord technique, but the tutorial put on the website to create a cut-out with Cutout2D creates an error: the sizes of the large and small arrays are mismatched. However, I did find the correct way through Stack Exchange and it is very different to the tutorial. I would suggest updating the tutorial for the sake of new up-and-coming astronomers, such as me. Here is the Stack Exchange solution: https://stackoverflow.com/questions/33512681/splicing-image-array-fits-file-using-coordinates-from-header

**Comment by pllim** [comment]
Hi. Could you please elaborate which tutorial you are referring to? If it is something from http://astropy-tutorials.readthedocs.io/en/latest/ , please open an issue at https://github.com/astropy/astropy-tutorials/issues instead.

**Comment by kusmic** [comment]
My apologies, I didn't communicate well. It wasn't the tutorial, but the image utilities in the documentation: http://docs.astropy.org/en/stable/nddata/utils.html

Essentially, attempting to save the cutout always brought up an error, mainly without clarity on how to do it. Maybe specifying that the cutout should be treated like a regular FITS object, such as needing to call it's data like: example.data; however, it wasn't clear.

**Comment by pllim** [comment]
Just want to clarify: So, your problem is not that the existing example gives you error, but a request to add additional documentation to save out the cutout object, correct?

**Comment by kusmic** [comment]
Right. My apologies, I was not clear and I thought I was saying it originally. It was a tiring day.

**Comment by pllim** [comment]
Feel free to open a PR to add that said example if you wish. Thanks for the clarification.

**Comment by RebecaMelo** [comment]
I would like to take this issue if it's ok.
First, when you try to save the cutout object, using the example, it gives you an error. Where exactly in the tutorial can I find a save function that gives this error?

So the idea is put an example for saving the cutout object as a fits file, right?

**Comment by RebecaMelo** [comment]
Do you have a link or some tutorial to update the documentation?

**Comment by kusmic** [comment]
Yes, I believe this would be good. It was on Stack Exchange, but the title
doesn't immediately match what a new astronomer might be looking for. They
may overlook this.

https://stackoverflow.com/questions/33512681/splicing-image-array-fits-file-using-coordinates-from-header

**Comment by larrybradley** [comment]
Added in #7328.
