### ISSUE TITLE
Include units in Table column descriptions

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#756]
This was discussed briefly in #683 - it would be nice if the basic 'ascii' output from Table also included units information, when present.  E.g., writing a table with  `t.write('filename', format='ascii')` where the columns have units should give something like:

```
#distance time
#meter second
1.2 3.4
5.6 7.8
```

**Comment by taldcroft** [comment]
From @eteq: 

> So I'm perfectly happy to close it when/if APE6 gets merged as it is indeed superceded completely in that case. But perhaps it should be left until then?

APE6 and ECSV are merged and well-established now.  Do you think there is a still a need to create a new ASCII table format that puts units in the second line of a fixed-width table?

**Comment by taldcroft** [comment]
Well, I realized that I just closed #4743 as a dup of this one, so maybe it needs to stay open?  Or reopen that one and close this?

**Comment by adrn** [comment]
IMO, trying to impose a standard for writing/reading units from plain ascii tables is not worth it and will be violated by free-floating ASCII tables more often than it is supported. So, given that ECSV is an option now, I would vote to close this issue.

**Comment by eteq** [comment]
I think I agree with @adrn here, so I'm going to close this.  Note there's a more focused version of this issue I'm still interested in, but I'll make a separate issue and link to here since it's more actionable.
