### ISSUE TITLE
TST: DeprecationWarning elementwise comparison failed

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7587]
https://travis-ci.org/astropy/astropy/jobs/395114777 all failed with similar errors. Looks like #2483 that happened 4 years ago.

```
TypeError: ufunc 'equal' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('bool')
...

E       DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
.../numpy/ma/core.py:4000: DeprecationWarning

===== 11 failed, 10980 passed, 100 skipped, 106 xfailed in 393.36 seconds ======
```

@mhvk ?

**Comment by mhvk** [comment]
Hmm, I get immediate payback for my https://github.com/numpy/numpy/pull/11282. Will investigate.

**Comment by mhvk** [comment]
Definitely a problem with my PR (i.e., upstream) - fix at https://github.com/numpy/numpy/pull/11405

**Comment by mhvk** [comment]
@pllim - thanks for the quick alert!

**Comment by mhvk** [comment]
Should be fixed now!

**Comment by pllim** [comment]
Indeed https://travis-ci.org/astropy/astropy/jobs/395423691 is all green. Thanks for the quick fix!
