### ISSUE TITLE
Equivalency for flux

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7593]
Currently we have flux density but there's none that I can find to convert, say, ph/cm^2/s to erg/cm^2/s. Did I miss something? If I were to implement it, is it okay to stick it in spectral_density or should it go somewhere new? What should I name the new one? spectral_nondensity? spectral_flux? spectral_integrated_flux?

**Comment by astrofrog** [comment]
There was some discussion in https://github.com/astropy/astropy/pull/692

**Comment by pllim** [comment]
@astrofrog , the discussions at some point mentioned that it makes sense to have `photon -> erg` equivalency but not `fnu -> nu * fnu`. Do you agree that `ph/cm^2/s -> erg/cm^2/s` falls under `photon -> erg` category? Although strictly speaking, ` ph/cm^2/s` is not a flux *density* (no per Angstrom), so might be misleading to include in `spectral_density`? :thinking:

**Comment by pllim** [comment]
I kinda need this, so I'll take a stab at this by making a completely new equivalency for a start and see where it goes...

**Comment by pllim** [comment]
Update: Looking at the code again, and seeing what others added over the years, I think it is the easiest to attach this new conversion as an extra line to `spectral_density`.
