### ISSUE TITLE
name for MDM Observatory in astropy.coordinates.EarthLocation

### ISSUE THREAD

**Issue by jrthorstensen** [astropy/astropy#7600]
The name string for MDM observatory should be changed from "Michigan-Dartmouth-MIT Observatory" to "MDM Observatory".  The consortium has reorganized several years and the official name is now "MDM Observatory", where the acronym does not stand for anything.  (I have been the president of the MDM Observatory Corporation for about a decade, so I'm a primary source.)

**Comment by dhilipsiva** [comment]
Created a PR for this issue here: https://github.com/astropy/astropy-data/pull/51

**Comment by eteq** [comment]
Merged astropy/astropy-data#51 - thanks @jrthorstensen and @dhilipsiva !
