### ISSUE TITLE
ModuleNotFoundError: No module named 'astropy.io'; 'astropy' is not a package

### ISSUE THREAD

**Issue by mutanthumb** [astropy/astropy#7601]
Hi-
I just installed astropy using the WHL package and am trying to extract headers from a fits file. I'm following along with your instructions here: http://docs.astropy.org/en/stable/importing_astropy.html#getting-started-with-subpackages

I'm using Python3 and Atom as my text editor and am getting this error:
```
Traceback (most recent call last):
  File "astropy.py", line 1, in <module>
    import astropy
  File "/Users/sborda/Desktop/API_tests/astropy.py", line 2, in <module>
    from astropy.io import fits
ModuleNotFoundError: No module named 'astropy.io'; 'astropy' is not a package
```
Any advice would be appreciated.
Thanks.

**Comment by pllim** [comment]
1. Start a new terminal.
2. Go into a Python session.
3. Try `import astropy`. What do you see now?

**Comment by pllim** [comment]
p.s. Make sure `astropy` was installed in the same installation directory tree as your Python installation.

**Comment by mutanthumb** [comment]
If I installed this via pip wheel where is the default install location?

**Comment by pllim** [comment]
`which pip` might give you an idea. In addition to that, check your `PATH` and `PYTHONPATH`.

**Comment by mutanthumb** [comment]
Just checked astropy is now in: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages

**Comment by mutanthumb** [comment]
Got it, it's working now. Thanks!
