### ISSUE TITLE
CCDData cannot read Hubble Space Telescope FITS image

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7608]
Astropy 3.0.3 and Python 3.6:
```python
>>> from astropy.nddata import CCDData
>>> ccd = CCDData.read('jb5g05ubq_flt.fits')
...
...\astropy\nddata\nddata.py in __init__(self, data, uncertainty, mask, wcs, meta, unit, copy)
    205 
    206         if unit is not None:
--> 207             unit = Unit(unit)
    208 
    209         if copy:

...\astropy\units\core.py in __call__(self, s, represents, format, namespace, doc, parse_strict)
   1796                            .format(s, format_clause, str(e)))
   1797                     if parse_strict == 'raise':
-> 1798                         raise ValueError(msg)
   1799                     elif parse_strict == 'warn':
   1800                         warnings.warn(msg, UnitsWarning)

ValueError: 'ELECTRONS' did not parse as unit: At col 0, ELECTRONS is not a valid unit. Did you mean electron?
```
The underlying problem is that `BUNIT` in HST image has unit string that is not supported by `astropy.units`. However, I also cannot single-handedly change 26 years of Hubble history. What is the middle ground here? Or is `CCDData.read()` simply incompatible with HST?

**Comment by MSeifert04** [comment]
You can pass in the `unit` explicitly:

```
CCDData.read(jb5g05ubq_flt.fits', unit='electron')
```

**Comment by pllim** [comment]
Thanks! What if I want to read in `ext=4`? I don't see any option to specify extensions...

**Comment by pllim** [comment]
(I also see that `unit` is documented at API doc. My bad!)

**Comment by MSeifert04** [comment]
You can pass in the `hdu` (http://docs.astropy.org/en/stable/api/astropy.nddata.fits_ccddata_reader.html#astropy.nddata.fits_ccddata_reader): `CCDData.read(..., hdu=4)`?

**Comment by pllim** [comment]
Yay, this works. Thanks!
```python
ccd = CCDData.read('jb5g05ubq_flt.fits', hdu=4, unit='electron')
```
Although `hdu` is not documented at all at http://docs.astropy.org/en/latest/api/astropy.nddata.CCDData.html under "Parameters". Bug or feature? :wink: 

Thanks again!

**Comment by MSeifert04** [comment]
The `read` method documentation is mentioned in the methods section (although a bit ugly because it's not overridden);

![unbenannt](https://user-images.githubusercontent.com/14200878/42116678-a7f93494-7bf8-11e8-9fd3-dec08df6081a.png)

**Comment by MSeifert04** [comment]
> Bug or feature? 😉

Good question ... is "both" a valid answer? 😄

**Comment by pllim** [comment]
Hah! Fair enough. Thanks!!!

**Comment by MSeifert04** [comment]
I think it's actually worth keeping this issue open (or open new issues) because the exception during CCDData.read with invalid unit could be more helpful and it's probably worthwhile to merge the two method enumerations...

**Comment by astrofrog** [comment]
I think more generally, we've raised the idea in the past of being more forgiving on input and strict only on output. This seems like a good example of why. I think this should just read in an if the user accesses the unit it would return an unrecognizedunit('ELECTRONS')

**Comment by pllim** [comment]
OK I re-opened and mark this as doc issue.

**Comment by pllim** [comment]
I think #7612 solved my predicament, as the error message is helpful now. Closing this and moving larger philosophical discussions to #7619. Thanks, everyone!
