### ISSUE TITLE
Table read-in for SExtractor-like files fails if index starts at 0

### ISSUE THREAD

**Issue by kdpenner** [astropy/astropy#7620]
I have an ASCII file with the following header:

```
# 0   NAME                  VLAHFF-JHHMMSS.SS+DDMMSS.S
# 1   RA                    deg
# 2   DEC                   deg
# 3   SIGMA_RA              arcsec
# 4   SIGMA_DEC             arcsec
# 5   INT_FLUX_S            uJy
# 6   SIGMA_INT_FLUX_S      uJy
# 7   PEAK_FLUX_S           uJy/beam
```

etc., with a total of 56 columns.  It's not a SExtractor file but it's like one.  The following command almost works:
```python
la = Table.read('file.cat', format = 'ascii.sextractor')
```
I get the following error:
```python
astropy.io.ascii.core.InconsistentTableError: Number of header columns (57) inconsistent with data columns (56) at data line 0
```
If I renumber the header to begin with "1 NAME" the read-in works properly.

**Comment by pllim** [comment]
Despite Python being 0-indexed, file format itself might not be (especially if it has existed back in, say, IRAF days). The example shown in http://docs.astropy.org/en/stable/api/astropy.io.ascii.SExtractor.html#astropy.io.ascii.SExtractor in consistent with your fix, so I am closing this issue. Feel free to re-open if you feel otherwise. Thanks.

**Comment by kdpenner** [comment]
I'm unsure if you intended the first sentence to relate to the second.

For a file with a large number of columns, renumbering either by hand or by using a regex is a pain.  If it's simple to expand the SExtractor class to include a header that is 0 indexed, I think it should be done.

**Comment by astrofrog** [comment]
@kdpenner - where does the file you have come from?

**Comment by kdpenner** [comment]
It's from a collaborator.  He created a catalog using PyBDSM.  I'm unsure if what I have is the default output of PyBDSM or if the header information was printed using some script.

Looking at the relevant code for astropy.io.ascii.SExtractor, it might be easy to create a new format by copying sextractor.py and replacing instances of "variable + 1" with "variable".
