### ISSUE TITLE
commented_header format fails if column names are duplicated

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#7624]
The command:

    ascii.read(test_file, format='commented_header')

works for `test_file`:

```
#dummy    dummy1
0            0
```

but fails for:

```
#dummy    dummy
0            0
```

with

```
astropy.io.ascii.core.InconsistentTableError: 
ERROR: Unable to guess table format with the guesses listed below:
```

**Comment by pllim** [comment]
When a table has two columns with the same name, how do you query it? What is the behavior that you expect here?

**Comment by Gabriel-p** [comment]
Ideally I would expect either:

1. an automatic renaming, eg adding an underscore to a duplicated column name, with a Warning that some columns have been renamed, or
1. a more understandable error message, something like "Duplicated column names found"

As it is, I had to spend several minutes before I figured out what the problem was when reading a file with duplicated column names.

**Comment by taldcroft** [comment]
@Gabriel-p - just wondering if you tried the next suggested step in the exception output:
```
************************************************************************
** ERROR: Unable to guess table format with the guesses listed above. **
**                                                                    **
** To figure out why the table did not read, use guess=False and      **
** appropriate arguments to read().  In particular specify the format **
** and any known attributes like the delimiter.                       **
************************************************************************
```
This gives something that, while not perfect, might have nudged you in the right direction to get the answer in faster than a few minutes (i.e. it says the number of names and columns is not matching):
```
ValueError: Arguments "names" and "dtype" must match number of columns
```

Do you have any suggestions that would make it more clear to follow this advice in the exception error message?

One other thing we can take as an action is to update that message to suggest `fast_reader=False`.  Had you done this, voila!
```
In [8]: dat = ascii.read(['# dummy dummy', '1 2'], format='commented_header', fast_reader=False, guess=False)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-cdbc32fb5392> in <module>()
----> 1 dat = ascii.read(['# dummy dummy', '1 2'], format='commented_header', fast_reader=False, guess=False)
...
    810         columns = table.TableColumns((col.info.name, col) for col in cols)

ValueError: Duplicate column names
```

**Comment by taldcroft** [comment]
See #7637.

**Comment by Gabriel-p** [comment]
I did not try the `guess=False` recommendation, but honestly I'm not sure the `ValueError: Arguments "names" and "dtype" must match number of columns` message would've helped much.

The `ValueError: Duplicate column names` message on the other hand is precisely what I was taking about. A simple and clear message indicating what is wrong. Thank you @taldcroft! If you don't mind I'll just close this issue now.
