### ISSUE TITLE
Velocities in SkyCoord

### ISSUE THREAD

**Issue by mkounkel** [astropy/astropy#7627]
Is support for proper motions and RVs in SkyCoord only in the version for Python 3? I am trying to run the example from the documentation, but it results in an error of 

ValueError: Velocity data is currently only supported in the coordinate frame objects, not in SkyCoord. See the velocities documentation page for more information: http://docs.astropy.org/en/stable/coordinates/velocities.html

Nothing on that page sheds any light to the workaround.

**Comment by adrn** [comment]
Hi @mkounkel --

Yes, starting with version 3, Astropy is Python 3-only and that functionality was added with version 3. In version 2, you can still use velocities but only through the frame classes (http://docs.astropy.org/en/v2.0.x/coordinates/velocities.html).
