### ISSUE TITLE
Creation of composite units is relatively slow

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#7630]
Something that came up in our survey of user experience of performance; note that #7549 already helped quite a bit, but more may be possible. Before anything else probably needs:
1. [ ] Check our benchmarks;
2. [ ] Determine bottlenecks by profiling.
3. [ ] Carefully check whether all the checks during creation are in fact necessary.

**Comment by pllim** [comment]
I added a "sprint" label in hope that we could sprint on this, say, at Astropy coordination meeting or something. :crossed_fingers:

**Comment by astrofrog** [comment]
One thing that could lead to performance issues is that it seems that when doing:

array * unit * unit

it seems this is evaluated as (astropy * unit) * unit, but I think things would be faster if we did astropy * (unit * unit) since this would only copy the data once. Example:


```python
In [6]: import numpy as np

In [7]: x = np.arange(10000000)

In [8]: %timeit x * u.m
52.9 ms ± 702 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [9]: %timeit x * u.m / u.s
82.4 ms ± 5.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [10]: %timeit x * (u.m / u.s)
55 ms ± 954 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Is there a way we can influence the priority of how things are evaluated?

**Comment by saimn** [comment]
@astrofrog - I don't think you can influence this, there is the same (almost) issue with numpy arrays, `2 * 3 * arr` is faster than `arr * 2 * 3`.

**Comment by saimn** [comment]
But there is this old idea of having a simpler notation to avoid copy when creating a quantity: #3174

**Comment by mhvk** [comment]
In numpy, there is a hack to look at reference counts to see whether one is dealing with just a temporary argument, so that an operation can be done in-place. See https://github.com/numpy/numpy/pull/7997. But I think this only works in C.

As @saimn notes, there is the idea of a special notation or in-place - the conclusion of that issue was (I think) to have a context manager in which in-place is automatic.

At the very least we should mention in the performance section that, ideally, one combines units first.

**Comment by pllim** [comment]
What about `100 * u.m / (10 * u.s)`? Is `(100 / 10) * (u.m / u.s)` also faster? (Can't check that myself right now.) If so, is it worth the decrease in readability (i.e., should we encourage such notation)?

**Comment by mhvk** [comment]
@pllim - it is faster, but I would say we should not encourage it. I do think it makes some sense to encourage putting parentheses around unit combinations for increased performance.

**Comment by mhvk** [comment]
Now added a commit where I used `_error_check=False` in cases where the inputs are obviously fine.

**Comment by mhvk** [comment]
#7649 may now contain most of the low-hanging fruit.

**Comment by mhvk** [comment]
closing since most of the work was done
