### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#7631]
One comment in the user survey suggested the web documentation and examples were often out of date. It is probably time to start going through and check.

**Comment by pllim** [comment]
Is `doctest` insufficient? I thought we test most of our examples both in core and in tutorials. :thinking:

**Comment by bsipocz** [comment]
This is simply not true. A one off example here and there maybe slip through via a `doctest-skip`, but it cannot happen *'often'* as doctest is running on the docs. 

My suspicion is that the user regularly ends up in some version miss-matches, google searches still sometimes return docs for old versions higher up than the docs for the 'stable' version, etc.

**Comment by mhvk** [comment]
I don't think it is necessarily that an example is wrong, but that it no longer reflects "best practice" - certainly, for the `Table` vs `QTable` difference there may be room for improvement. It might well be a good idea to go through the documentation and see if it still best serves its purpose.

**Comment by pllim** [comment]
Added a "sprint" label in case we want to do a doc sprint at some point...

**Comment by bsipocz** [comment]
I'm adding the milestone as ideally the docs should be checked whether still makes sense before a release and examples should be updated/removed when necessary. 
On the other hand, this is basically a standard maintenance task, so we probably don't really need the issue to be kept open.

**Comment by mhvk** [comment]
Indeed, it is somewhat of a maintenance task.  Perhaps something we can check going along with the lovely copy-edits of @lglattly.

**Comment by lglattly** [comment]
I think I can help with this! I'm assisting @jonathansick with a new examples gallery project, where I'll be flagging all of the documentation examples as I edit so that we can easily see all of the examples we have. When they are all reviewed to evaluate them for use in the gallery, maybe this would be a good time to double check that none are out of date?

**Comment by mhvk** [comment]
This is too general, closing.
