### ISSUE TITLE
Printing unit labels slow?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#7632]
From the user survey, it was noted that printing units used TeX formatting, which made it slow. (This is somewhat of a placeholder; I have asked for clarification.)

**Comment by astrofrog** [comment]
I wonder if this was related to https://github.com/astropy/astropy/issues/6995

**Comment by astrofrog** [comment]
@mhvk - did you ever hear back about this?

**Comment by mhvk** [comment]
No, I didn't, so will close this issue.
