### ISSUE TITLE
Thread-safety of astropy

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#7633]
In our user survey, @stargaser mentioned that configuration with multithreading was a problem if different versions of astropy were being ran. This reminded me that perhaps we need to check a bit better if our procedures are thread-safe.

Note: not sure there is an actual issue here!

**Comment by mhvk** [comment]
Closing since we did make some improvements, and this is too general.

**Comment by pllim** [comment]
For future reference, there were some PRs to improve thread-safety here and there: https://github.com/astropy/astropy/pulls?q=is%3Apr+is%3Amerged+thread+safe
