### ISSUE TITLE
DOC: Add example to invert SkyCoord spherical offset transformations

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7634]
This is from Astropy mailing list: https://mail.python.org/pipermail/astropy/2018-July/004432.html . Someone just have to spend a few hours putting this together nicely in the doc. :smile: 

Original request:

> The astropy documentation provides a very useful example of how to compute the offset between 2 SkyCoord positions at http://docs.astropy.org/en/stable/coordinates/matchsep.html?highlight=spherical_offsets#separations. 
> Specifically, the example for "spherical_offsets_to" in that section of documentation shows how to derive a delta RA and delta Dec for those source positions.  In my case, though, I already have the delta RA and delta Dec from an astrometric solution for that observation and want to apply those deltas to the source positions to reproduce the astrometric catalog positions.  So, the operation I am really interested in would be the inverse of this example where those deltas would be applied to the "bright_star" SkyCoord position to reproduce (within machine precision) the "faint_galaxy" position in RA and Dec.

Provided solution:

> Here’s a potential solution using a SkyOffsetFrame, building on the spherical_offsets example you linked to:
``` python
>>> from astropy.coordinates import SkyCoord, SkyOffsetFrame, ICRS
>>> bright_star = SkyCoord('8h50m59.75s', '+11d39m22.15s', frame='icrs')
>>> faint_galaxy = SkyCoord('8h50m47.92s', '+11d39m32.74s', frame='icrs')
>>> dra, ddec = bright_star.spherical_offsets_to(faint_galaxy)
>>> star_frame = SkyOffsetFrame(origin=bright_star)
>>> my_galaxy = SkyCoord(lon=dra, lat=ddec, frame=star_frame)
>>> galaxy_coord = my_galaxy.transform_to(ICRS)
>>> galaxy_coord.separation(faint_galaxy)
<Angle 1.5902773407317588e-15 deg>
>>> galaxy_coord.to_string('hmsdms')
'08h50m47.92s +11d39m32.74s’
```
> although with limitations, e.g. “galaxy_coord.spherical_offsets_to(faint_galaxy)” raises an exception about two non-matching frames.

c/c @stsci-hack and @stargaser

**Comment by eteq** [comment]
Note that @stsci-hack and I had a discussion about this.  What's on the mailing list (and above here) is a good start, but it turns out the "bigger" problem was one of *adjusting* a WCS frame on the basis of a known offset in some other field.  The solution for that was to cast your image’s WCS into a SkyOffsetFrame, create a new SkyOffsetFrame with the appropriate tweaks to get the two frames to line up, insert the coordinates into that *second* frame, and then send it back to RA/Dec. 

That sounds pretty complicated in words, but it was ~5-10 lines of (pseudo-)code on the whiteboard.  I think @stsci-hack is planning to implement this and hopefully then we can included it as a doc example once we're sure it's working.

**Comment by shilpi1958** [comment]
Hi, I would like to work on this issue! Is it still open?

**Comment by pllim** [comment]
@shilpi1958 , from https://github.com/astropy/astropy/issues/7634#issuecomment-404951044 , this looks like a PR will come from @stsci-hack some time in the future.

**Comment by shilpi1958** [comment]
Oh okay.

**Comment by pllim** [comment]
@shilpi1958 , @eteq or @stsci-hack would be the best people to answer your question. We apologize for any confusion caused.

**Comment by tjgalvin** [comment]
Just wondering what the status of this is. I have used this to add delta angles to a `SkyCoord`, which then needs to be used with the `spherical_offsets_to` method of another `SkyCoord` position. This is something that was flagged as 'will raise an error' in the original post in the mailing list. Any suggestions to get around this?

**Comment by adrn** [comment]
I think this has since been solved on the page: https://docs.astropy.org/en/latest/coordinates/matchsep.html#offsets
