### ISSUE TITLE
warnings_to_ignore kward for enable_deprecations_as_exceptions()

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#7635]
To ignore deprecation warnings coming from e.g. numpy (via another dependency, so we don't have any power to fix them), the only way with the current machinery is to either ignore everything coming from numpy, or to list the warning in `warnings_to_ignore_by_pyver` for each and every python versions being supported. 

I feel it would be nicer and cleaner to have one more kwarg, that is python version agnostic to list all of these warnings.

What do you think @pllim?

**Comment by pllim** [comment]
I thought about that too... Will have a look.

**Comment by bsipocz** [comment]
Actually listing the warnings in `warnings_to_ignore_by_pyver` didn't work in that particular case, the only way to avoid them by ignore the whole module, both for `numpy` and `sherpa` (the deprecated usage was in both cases in sherpa, once for numpy once for astropy, but it wasn't enough to just ignore sherpa).

**Comment by pllim** [comment]
You mean you ended up using this logic block to bypass?
```python
    # This ignores all deprecation warnings from given module(s),
    # not just on import, for use of Astropy affiliated packages.
    for m in _warnings_to_ignore_entire_module:
        for w in _all_warns:
warnings.filterwarnings('ignore', category=w, module=m)
```
I don't see why we can't add option to ignore a particular warning message from given module(s)...

**Comment by bsipocz** [comment]
Yes, somehow these numpy ones (https://github.com/sherpa/sherpa/pull/470) ended up raising weird SystemErrors (e.g. https://travis-ci.org/gammapy/gammapy/jobs/402308521#L4188), and it didn't mattered what warning message I ended up adding to `warnings_to_ignore_by_pyver`.  Same happened when tried to ignore the clobber vs overwrite messages, so it's entirely possible that I didn't used it properly anyway.
