### ISSUE TITLE
DOC: Release calendar to have reverse chronological order

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7640]
Rearrange https://github.com/astropy/astropy/wiki/Release-Calendar so that the latest release is on top because that is what people care most when they go to that page. Any objection? @bsipocz ?

**Comment by bsipocz** [comment]
Sure thing, sounds good to me.

**Comment by pllim** [comment]
Done. And just for the record, here is how I did it:
```python
s = """<copy and paste from wiki>"""
lines = s.split('\n')
lines.reverse()
print('\n'.join(lines))
# copy and paste back to wiki
```
