### ISSUE TITLE
Make @quantity_input pass over arguments with non-unit annotations

### ISSUE THREAD

**Issue by namurphy** [astropy/astropy#7661]
The `@astropy.units.quantity_input` decorator currently raises an exception if an argument has an annotation that cannot be converted to a unit.  This has the side effect that type hint annotations and annotations used by different decorators cannot be used in functions decorated by `@quantity_input`.

Here is a minimal example (using Astropy 3.0.2):
```Python
>>> import astropy.units as u

>>> @u.quantity_input
... def f(x: u.m, y: str) -> u.m:
...    return x

>>> f(1 * u.m, 'x')
TypeError: <class 'str'> can not be converted to a Unit
```

My suggestion would be for `@quantity_input` to skip arguments with annotations that are not units or cannot be converted to units.  However, if the annotation is a string that cannot be converted to a unit, then I would propose raising a `TypeError` (or maybe a `u.UnitsError` or a `u.UnitConversionError`) since there could be a typo in a string that could have been intended to be a unit.

Thanks!
-Nick

**Comment by mhvk** [comment]
This seems like a good idea. Could be inside a `try/except` or perhaps one should explicitly omit trying the unit conversion for anything of the class that is used for type hints (if there is one). cc @Cadair.

**Comment by namurphy** [comment]
The use case I had in mind was for compatibility with PlasmaPy's `@particle_input` decorator, which works on arguments that are annotated with our `Particle` class.  We aren't able to use both `@quantity_input` and `@particle_input` at the same time because `@quantity_input` will raise exceptions for the arguments annotated with `Particle`.  If `@quantity_input` were to ignore non-unit annotations, then we would be able to use `@quantity_input` a lot more frequently in the package.

Besides this issue, I really like `@quantity_input` and am really glad that it's in `astropy.units`!

**Comment by Cadair** [comment]
When originally written we tried to duck type `quantity_input` to be unit implementation agnostic. This and other changes made since it was originally written have led to moving further away from this.

That said, I think this is a very good idea, and we should  implement it, but try not to make it too astropy units specific in the implementation.

**Comment by maciekgroch** [comment]
Hey, 

I am dealing with exactly the same issue: one of the parameters of my function is not an astropy quantity because of which I am not able to use typing hints. Is there any progress on the issue?

I am using Python 3.7 and astropy 3.2.1

THanks for help.

**Comment by likewei92** [comment]
I just ran into the same issue. Here's my attempt to fix it: https://github.com/astropy/astropy/pull/8984

I copied the tests and docs from @ritiek

**Comment by likewei92** [comment]
@mhvk @Cadair @adrn could you help to take a look at the PR now? :)
