### ISSUE TITLE
Migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#7669]
We have a big warning on our circleCI page about it stopping to work after the 31st of August, unless we migrate to their new version.

I expect it to be quite simple to do the transition but then it would be good to do all the astropy coordinated projects together (and even maybe open reminder issues for the rest of the affected affiliated packages) and that's a bit of legwork.

**Comment by bsipocz** [comment]
Ohh, great. There is still work to do at the CircleCI CS, shouldn't really issue the warning then (as it doesn't give it indeed for astropy/regions):
<img width="1304" alt="screen shot 2018-07-20 at 13 30 51" src="https://user-images.githubusercontent.com/6788290/43002600-46833276-8c21-11e8-8f2b-4928af7abbd3.png">

**Comment by pllim** [comment]
I don't understand why new PRs still don't kick off CircleCI runs.

**Comment by astrofrog** [comment]
I've turned it off and on again, let's see if that helps

**Comment by astrofrog** [comment]
I think the migration comment is just for everyone

**Comment by bsipocz** [comment]
My issue is that the warning is there for astropy/astropy, but not for astropy/regions.

**Comment by astrofrog** [comment]
I think the warning was present if at least one branch still used the old config. Anyway I think we can ignore this.

**Comment by bsipocz** [comment]
Oh, that may explain things. Anyway I've closed this as all the repos are working even though the migration has happened upstream.
