### ISSUE TITLE
Travis OSX tests

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy#7680]
Why are there no Travis OSX tests?

In addition, the initial test that sets ``compiler: clang`` ([src](https://github.com/astropy/astropy/blob/master/.travis.yml#L122)), wouldn't this be better to test against the conda installed version of clang? I'm not aware of any Linux flavor shipping with clang anyhow. Is there one?

**Comment by bsipocz** [comment]
@jamienoss - Long story short: we do have the clang test in place of an OSX one, as with this setup we caught all the issues we had with osx before without being stuck in that queue.
Also, we have an osx one, running from a daily cron on master, so even in the case something slips through, it's caught next day after the merge (but it never caught anything).
Hope this answers the question.
