### ISSUE TITLE
Update AppVeyor build to VS2017?

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy#7683]
We are currently testing on ``Visual Studios 2015 update 2`` as indicated [here](https://github.com/astropy/astropy/blob/master/appveyor.yml#L26).
```yml
...
os: Visual Studio 2015 Update 2
...
```
This seems to require an explicit request to use this OS, i.e. it is not in the canonical build list, _c.f._ https://github.com/appveyor/ci/issues/1197

Just prompting the question of whether it's time to update?

**Comment by bsipocz** [comment]
Yeah, we stuck with that version as there were issues with the subsequent ones. So if it works we can update, but need to be careful here.

cc @mwcraig

**Comment by jamienoss** [comment]
Out of curiosity, which subsequent versions? I couldn't find anything in the original PR (https://github.com/astropy/astropy/pull/5172) explicitly stating the reason for the change.

**Comment by jamienoss** [comment]
...or was it just update 3?

**Comment by bsipocz** [comment]
e.g. https://github.com/astropy/astropy/pull/5141, https://github.com/appveyor/ci/issues/890

**Comment by mwcraig** [comment]
I can try a newer version of vs in the next day or two (am on the road)

**Comment by mwcraig** [comment]
Just a heads up that I might not have wifi up to the task of downloading VS2017 for a couple more days.

It looks like @jamienoss's appveyor build succeeded, though. I'd be game for updating based on that alone.  VS2017 should, in principle work for python >=3.5. In that version the way that Python was built on windows was changed to avoid locking the compiler version.

**Comment by bsipocz** [comment]
@mwcraig - with that note I've updated the milestone on the change and don't plan to backport it for the bugfixes (and won't be changing it for the wheels/conda either until 3.1)
