### ISSUE TITLE
Gateway timeout for http://maia.usno.navy.mil/ser7/finals2000A.all

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7690]
This may be a transient problem in which case this issue can be closed, but I'm getting the following warnings when building the docs for Astropy:

```
WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all, using local IERS-B: <urlopen error timed out> [astropy.utils.iers.iers]
```

**Comment by astrofrog** [comment]
Working again!

**Comment by pllim** [comment]
Note: If this keeps happening, please report it upstream. Thanks!
