### ISSUE TITLE
sigma_clipped_stats fails with quantity input

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#7700]
Just what the title says really:
```
>>> stats.sigma_clipped_stats(np.random.randn(100)*u.kpc)
...
UnitConversionError: 'kpc(1/2)' and 'kpc' (length) are not convertible

During handling of the above exception, another exception occurred:
...
UnitConversionError: Can only apply 'subtract' function to quantities with compatible dimensions
```
Whereas I *expected* ``<Quantity [0.03102944, 0.13463141, 1.07249346] km>`` (or maybe ``(<Quantity 0.03102944 km>, <Quantity 0.13463141 km>, <Quantity 1.07249346 km>)``)

**Comment by pllim** [comment]
cc @larrybradley

**Comment by crawfordsm** [comment]
This seems to have been fixed in the latest release with the refactor of sigma_clip, but a test should probably be added.
