### ISSUE TITLE
New release supporting Python 3.7?

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#7701]
Version 3.0.3 has [a number of test failures](https://buildd.debian.org/status/fetch.php?pkg=astropy&arch=amd64&ver=3.0.3-3%2Bb1&stamp=1532780025&raw=0) with Python 3.7, which is used in Debian since a few weeks.

Since it seems that these problems are fixed in git: would it be possible to make another maintenance release?

**Comment by bsipocz** [comment]
Yes, I'm literarily in the middle of making the release.

**Comment by olebole** [comment]
To take this opportunity: thank you so much for your organizational work! I feel very well supported with my goals (Debian)!

**Comment by lupinix** [comment]
Same for Fedora, thanks!

**Comment by olebole** [comment]
Thanks @bsipocz! 3.7 is out, so closing this issue.
