### ISSUE TITLE
Error in testing development copy.

### ISSUE THREAD

**Issue by sudz123** [astropy/astropy#7713]
Hi! I am trying to test astropy development version '3.1.dev22297' . My machine is a Mac OS Sierra , and I am running on python 3.6. While testing the development package using 'python setup.py test' I have come across a bunch of errors : 
![screen shot 2018-08-07 at 10 21 58 pm](https://user-images.githubusercontent.com/18459822/43790406-208ec40e-9a90-11e8-939f-c217cd5650b4.png)

These are just few of the errors.
- Is this due to the fact that I am connected to the net via a proxy server? If so, should I ignore these errors? 
- If not what should I do?
Thanks !

**Comment by pllim** [comment]
cc @astrofrog

**Comment by bsipocz** [comment]
@sudz123 - do you still see this error? I recall that some similar ones are coming up occasionally on CI, but they are of transient nature and go away.

**Comment by bsipocz** [comment]
Closing as no more follow-up on this.

Reopen if we run into it again.
