### ISSUE TITLE
Cannot use mode='update' when opening Fits files

### ISSUE THREAD

**Issue by sguillot** [astropy/astropy#7714]
I am experiencing a crash when using the mode='update' option to open a fits file on Ubuntu 14.04 with Python 3.6.5 (from anaconda), together with numpy 1.15.0 and astropy 2.0.7.  It seems that the mode='update' option is not recognised.

For example:
```
import astropy.io.fits as pyfits
hdu1 = pyfits.open('myfile.fits')
print(len(hdu1[1].data))
```
works fine, but 
```
hdu1 = pyfits.open('myfile.fits',mode='update')
print(len(hdu1[1].data)) 
```
crashes with the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 739, in __get__
    val = self.fget(obj)
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 350, in data
    data = self._get_tbdata()
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 171, in _get_tbdata
    self._data_offset)
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 480, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 270, in readarray
    dtype=np.uint8)
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OSError: [Errno 22] Invalid argument
```

However, I do not have this problem on OSX with the same python and packages versions!

**Comment by saimn** [comment]
I cannot reproduce locally, it could be something with the system (32bits ?) and file size (is it big?). Can you share the file, or enter in a debugger and print `bytes`, `acc`, and `start` ?

**Comment by sguillot** [comment]
Thanks for the help.  The system is 64 bits. But the file is small. In fact, this same problem happens with a tiny fits file (the example in the astropy doc).  Below is the output of the python debugger. I am attaching the code and fits file that I used to debug. In this test code, I first open the fits file in the default mode and print `self.mode`, `bytes`, `acc` and `start`. Then I do the same with the file opened in "update" mode.

```
sguillot$ python -m pdb test_pyfits.py

> /test_pyfits.py(1)<module>()
-> import astropy.io.fits as pyfits
(Pdb) b /home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py:269
Breakpoint 1 at /home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py:269
(Pdb) b /home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/numpy/core/memmap.py:264
Breakpoint 2 at /home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/numpy/core/memmap.py:264
(Pdb) c

> /home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py(269)readarray()
-> memmap = Memmap(self._file, mode=MEMMAP_MODES[self.mode],
(Pdb) pp self.mode
'readonly'
(Pdb) c

> /home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/numpy/core/memmap.py(264)__new__()
-> mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
(Pdb) pp bytes
8640

(Pdb) pp acc
3

(Pdb) pp start
0
(Pdb) c

> /home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py(269)readarray()
-> memmap = Memmap(self._file, mode=MEMMAP_MODES[self.mode],
(Pdb) pp self.mode
'update'
(Pdb) c

> /home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/numpy/core/memmap.py(264)__new__()
-> mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
(Pdb) pp bytes
8640

(Pdb) pp acc
2

(Pdb) pp start
0

(Pdb) c
```

And the crash report is the same as I posted initially.
Let me know if you can identify what can be wrong...because I don't see.

**Comment by saimn** [comment]
Weird, the values seems correct, and I cannot reproduce with your example of course. It seems to be caused by the `acc` value (`mmap.ACCESS_WRITE`), but I have no idea why it could fail.

**Comment by pllim** [comment]
Since I noticed the `import astropy io.fits as pyfits`, on the off chance you have an older copy of `pyfits` (not the one in Astropy) installed anywhere in your PYTHONPATH, please uninstall it. I had seen weird things happen in the past when people have both `pyfits` and `import astropy.io.fits as pyfits` in their thingies. In addition to that, try your script in a fresh `conda` environment and see if it helps.

**Comment by sguillot** [comment]
I noticed something when I run scripts that make use of numpy. I get the following warning:
```
/home/sguillot/Softwares/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
```
But I don't know if it is related or not...Any thoughts?

**Comment by pllim** [comment]
So, it looks like you are using the `base` conda environment, is that correct? What if you create a fresh environment like this?
```
conda create -n myenv cython numpy scipy astropy
```
Then `source activate myenv` and run the script? Also make sure you are not pinning Python to another installation in your script.
