### ISSUE TITLE
memmap option bug/logic issue in astropy.io.fits 

### ISSUE THREAD

**Issue by drhay53** [astropy/astropy#7717]
In helping someone debug an exception thrown when they tried to use the memmap option using `astropy.io.fits.open`, I noticed what I think is a bug in the logic for throwing the exception. In `astropy.io.fits.file.py`, the `_strict_memmap` attribute is set based on the user's value passed at construction, but then after that it is defaulted to True, which means `_strict_memmap!=True` but `memmap==True`:
    
    self.strict_memmap = bool(memmap)
    memmap = True if memmap is None else memmap

This means that in `astropy.io.fits.hdu.image.py`, the exception in `_get_scaled_image_data` is only thrown if the user passed `memmap=True`, but they can try to force it to run by not passing any memmap value at all.

        try:
            if self._file.strict_memmap:
                raise ValueError("Cannot load a memory-mapped image: "
                                 "BZERO/BSCALE/BLANK header keywords present. "
                                 "Set memmap=False.")
        except AttributeError:  # strict_memmap not set
            pass

The other logic here is that if no scaling is required, (i.e. BZERO=0 and BSCALE=1), then the user should still be able to use memmap, right? Their other option may be to remove BZERO and BSCALE from the headers completely (though I haven't traced that logic through the code), which seems like a bad solution to encourage since these are FITS standard keywords (edit: though they're reserved and not mandatory).

I'm not sure exactly what the intended behavior here is, but I suspect that memmap should be defaulted to True before `_strict_memmap` is set so that the exception is thrown, then the exception should only be thrown if `BZERO!=0` and `BSCALE!=1`

**Comment by saimn** [comment]
The idea is, when setting *explicitly* `memmap=True`, to be sure that memmap is actually used without loading the full array in memory (#2298). But if BZERO=0 and BSCALE=1 then you should not reach this exception (you may need to use `ignore_blank`), see line 713:

https://github.com/astropy/astropy/blob/18c4c13fcc5d2907c236ff3a3a9875c78e5a69c4/astropy/io/fits/hdu/image.py#L712-L724

However maybe the exception message should tell to use `memmap=None` (which is the default value, and memap is used by default).

**Comment by saimn** [comment]
Closing since I think that my explanation above makes sense, and there is nothing to change on Astropy side. Please reopen if this is still an issue.

**Comment by Luvideria** [comment]
I don't get why bscale and bzero are required to have specific values to use memmap...
