### ISSUE TITLE
Astropy plugin cache_dir option collides with pytest option

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#7720]
The pytest plugin provided in `astropy.tests.plugins.config` provides an option called `cache_dir` that is used for customizing the location of the Astropy cache during test runs.

However, this collides with an option that pytest itself provides that is used for managing its own cache.

This is an unfortunate state of affairs. We really ought to change the option name in our own plugin, but this is a fairly significant API change. Would it be subject to the general rules for deprecation/removal?

This was first reported in https://github.com/astropy/astropy-helpers/issues/401.

**Comment by bsipocz** [comment]
I feel we can be more relaxed with deprecating/API change for the infrastructural things we provide. So I would say go ahead with a fix (that we may even backport to 2.0.x) without even a deprecation.
