### ISSUE TITLE
hdf5 reader shouldn't complain for missing path for single table files

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#7725]
the hdf5 reader issues large amount of warnings for the missing `path` parameter even when the input file has one table. 

Maybe in that case the reader could stay silent? Also, maybe we can subclass the generic `AstropyUserWarning` to something like `AstropyUserIOWarning`, so warnings coming from other modules are not silenced off if the user gets annoyed by the IO warnings.

**Comment by astrofrog** [comment]
I agree!
