### ISSUE TITLE
Bug in Cutout2D for even cutout size

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7730]
The following script:

```python
import numpy as np
from astropy.wcs import WCS
from astropy.coordinates import SkyCoord
from astropy.nddata.utils import Cutout2D

wcs = WCS(naxis=2)
wcs.wcs.ctype = ['RA---TAN', 'DEC--TAN']
wcs.wcs.crpix = 3.5, 3.5
wcs.wcs.crval = [0, 45]
wcs.wcs.cdelt = [-1, 1]

array = np.arange(36).reshape((6, 6)).astype(float)

coord = SkyCoord(0., 45, unit='deg', frame='icrs')

cutout = Cutout2D(array, coord, (6, 6), wcs=wcs, mode='partial')

print(cutout.data)
```

should ideally return the same array as the input array, but instead returns:

```
[[nan nan nan nan nan nan]
 [ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]
```

That is, the y axis is shifted, suggesting there are rounding issues.

I think the issue is in:

```
    edges_min = [_round(pos + 0.5 - small_shape / 2. + _offset(small_shape))
                 for (pos, small_shape) in zip(position, small_array_shape)]
    edges_max = [_round(pos + 0.5 + small_shape / 2. + _offset(small_shape))
                 for (pos, small_shape) in zip(position, small_array_shape)]
```

The problem is that for an even array with shape (6,6), the center is at (2.5, 2.5) so ``pos`` is 2.5, ``pos + 0.5 - small_shape / 2.`` is then integer, but ``_offset`` makes it be a .5 value which makes the rounding non-deterministic - I think things work properly if we just remove ``_offset(small_shape)``.

cc @larrybradley

**Comment by larrybradley** [comment]
Thanks, @astrofrog.  So it appears the bug is actually in the `overlap_slices` function, which `Cutout2D` calls.

**Comment by cdeil** [comment]
cc @adonath since we currently use Cutout2D in Gammapy.
