### ISSUE TITLE
Transforming velocities to Galactocentric frame fails

### ISSUE THREAD

**Issue by thevorpalblade** [astropy/astropy#7743]
Converting a SkyCoord object with a velocity to the Galactocentric frame fails with a units error.
Possibly related to [7028](https://github.com/astropy/astropy/issues/7028)
Here's a MWE:
```
import time
import astropy
from astropy import coordinates as coord
now = = astropy.time.Time(time.time(), format='unix')
earth = coord.get_body_barycentric_posvel("earth", time.time())
earth_coord = coord.SkyCoord(earth)
```
Now
`earth_coord.galactic `
works as expected but 
`earth_coord.galactocentric`
throws a UnitConversionError.

I'm using astropy version 3.0.4 and numpy version 1.15.0 with python 3.7 under archlinux.

**Comment by StuartLittlefair** [comment]
Hi @thevorpalblade 

The underlying issue here is that you are not initialising ```earth_coord``` correctly. ```coord.get_body_barycentric_posvel("earth", time.time())``` returns a tuple with a ```(position, velocity)``` pair - and you only need to use the former to initialise the ```SkyCoord``` if you don't care about the Earth's velocity.

```python
earth = coord.get_body_barycentric_posvel("earth", time.time())
print(earth)
(<CartesianRepresentation (x, y, z) in AU
    ( 0.85080917, -0.496287, -0.21523737)>, <CartesianRepresentation (x, y, z) in AU / d
    ( 0.00902499,  0.0132133,  0.00572864)>)
```

If you do care about the Earth's velocity, you need to create a ```CartesianRepresentation``` that has velocities attached to it, and use *that* to create the ```SkyCoord```, as outlined [here](http://docs.astropy.org/en/stable/coordinates/representations.html#astropy-coordinates-differentials). I've attached a full example below, and fixed a couple of bugs in the example above at the same time...

```python
from astropy.time import Time
from astropy import coordinates as coord

now = Time.now()
earth = coord.get_body_barycentric_posvel("earth", now)
ediff = coord.CartesianDifferential(earth[1].xyz)
earth_with_diff = earth_with_diff = earth[0].with_differentials(ediff)
earth_coord = coord.SkyCoord(earth_with_diff)

print(earth_coord.galactocentric)
<SkyCoord (Galactocentric: galcen_coord=<ICRS Coordinate: (ra, dec) in deg
    ( 266.4051, -28.936175)>, galcen_distance=8.3 kpc, galcen_v_sun=( 11.1,  232.24,  7.25) km / s, z_sun=27.0 pc, roll=0.0 deg): (x, y, z) in AU
    ( -1.71198883e+09,  0.4803782,  5569149.02897594)
 (v_x, v_y, v_z) in km / s
    (-14.58330208,  237.19349024, -6.23382472)>
```

**Comment by thevorpalblade** [comment]
Ah great, this is very helpful! I'll definitely use this pattern in my code going forward.
I'm rather surprised that `get_body_barycentric_posvel` returns a tuple of position and velocity rather than a `CartesianRepresentation` with an attached differential (although this would not have been surprising if I'd read the docs more carefully...)

I think doing so would follow the principle of least surprise from a user perspective, but would break backwards compatibility with existing code, I suppose. I'll leave these types of design decisions to wiser heads than mine :-)

One other thing I noticed was that when I (in error) made a `SkyCoord` out of the tuple of (position, velocity), the resulting `SkyCoord` had units of `(ra, dec, distance) in (deg, deg, AU / d)`,
which is correct for neither the position nor the velocity. This might just be a case of Garbage in Garbage out, but might it be worth checking for units consistency? Should this be a different bug report, or is it just more correct behavior that I don't understand?

**Comment by StuartLittlefair** [comment]
No problem @thevorpalblade. You're right of course, ```get_body_barycentric_posvel``` should more naturally return a ```CartesianRepresentation``` with velocities. Unfortunately it pre-dates the work on including velocities in representations and the project is rightly cautious about API-breaking changes...

It could be worth filing an issue regarding the ```SkyCoord``` initialisation. Whilst the supplied argument is not correct, the initialisation arguably shouldn't silently do the wrong thing!

**Comment by thevorpalblade** [comment]
Great! Makes sense to close this issue then :-)
