### ISSUE TITLE
Integrate with dask

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7748]
From performance survey, "Integrate with `dask` (arrays and tables) to allow out-of core and distributed computation."

http://dask.pydata.org

**Comment by astrofrog** [comment]
This is quite broad, but I guess this means for example that we should be able to use dask arrays as e.g. columns of tables, or in ``Time``, ``NDData``, or ``SkyCoord``? It could also mean making sure that various functions (e.g. sigma clipping) can work with dask arrays. I think we should probably just pick a few example cases and make sure those work.

**Comment by pllim** [comment]
@astrofrog , yes, indeed. Perhaps pick one that is most useful for distributed computing and go from there? I am guessing `Table`?

**Comment by astrofrog** [comment]
Does the performance survey result give any examples where this doesn't work currently?

**Comment by Cadair** [comment]
There is at least one issue with the `__repr__` on `NDData` which causes the array to be densified if you give it a dask array otherwise i have had a lot of success with using `NDData` with dask.

**Comment by keflavich** [comment]
A possibly low-hanging piece that I suggest prioritizing is reading data with `io.fits` into delayed-read dask arrays.

**Comment by keflavich** [comment]
Also, this issue should be linked to https://github.com/astropy/astropy/issues/8227, so now it is.

**Comment by pllim** [comment]
I think there are some support now. Should we close this?
