### ISSUE TITLE
DOC: Broadcasting example for coordinates

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7749]
As kindly provided by @StuartLittlefair via performance survey:

https://gist.github.com/StuartLittlefair/18a5c5271b099945a00a03454d9c34c2

Now that there is a performance section in the docs (#7592), this can go there.

**Comment by SG004** [comment]
I'm not quite sure what is being asked here, other than taking what is in the link and putting it in the performance section of the coordinate docs. Am I correct in this thinking if so I'd like to make a pull request to do just that.

**Comment by pllim** [comment]
@SG004 , yes, that was the idea, unless @eteq or @adrn have objections.
