### ISSUE TITLE
Automatically use spell checker in Sphinx

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7752]
I'm not sure how feasible this would be, but we should consider using a spellchecker for our Sphinx documentation. For example, the [sphinxcontrib-spelling](https://sphinxcontrib-spelling.readthedocs.io/) package provides a way to automate this (note that one of their dependencies is deprecated, but I think they are working on replacing it). It's possible to specify a list  of correctly spelt words as a text file, and I'm hoping they ignore any code content.

**Comment by pllim** [comment]
But, but, US English, right? :wink:

**Comment by astrofrog** [comment]
I did this for glue - what I found is that the easiest way is to first run the spelling check, then to use a Python script to extract the misspelt words from ``_build/spelling/output.txt``, to put them through ``sorted(set(words))`` to get a sorted list, and outputting that to ``spelling_wordlist.txt``, then to go though that list and remove any mis-spellings, and as you do that, to search and fix those words in the docs.

**Comment by bsipocz** [comment]
> I did this for glue - what I found is that the easiest way is to first run the spelling check, then to use a Python script to extract the misspelt words

and you mean to run it on the diff only, right?

**Comment by astrofrog** [comment]
Not sure how easy it is to run it on just the diff. It might not be too slow to do it on the full docs just after the docs html build.

**Comment by astrofrog** [comment]
Just as an example, this is what I added to the Makefile for glue:

https://github.com/glue-viz/glue/pull/1837/files#diff-f3644bba251750c9ec4a2361d6cc59eb

You can then easily run ``make spelling``. The thing I was mentioning about extracting misspelt words was just for the first time to get this up and running.

**Comment by bsipocz** [comment]
So you mean to also maintain a dictionary extension? Otherwise it would be quite overwhelming as there are quite a few non dictionary but valid words we use that the spellchecker picks up every time.

**Comment by bsipocz** [comment]
> You can then easily run make spelling. The thing I was mentioning about extracting misspelt words was just for the first time to get this up and running.

Oh, OK, I misunderstood this then a lot.

**Comment by astrofrog** [comment]
@bsipocz - If needed, I can open an initial PR soon setting up the infrastructure based on what I did in glue.

**Comment by pllim** [comment]
I think we do now, thanks to @namurphy !
