### ISSUE TITLE
URLopen error failed to download. (Astropy, Kepler Data)

### ISSUE THREAD

**Issue by PieterMey** [astropy/astropy#7756]
I'm trying to get data from a FITS file 'kplr002304168-2009131105131'. I'm trying to the following code that was suggested by Astropy. 

`from astropy.io import fits`

`fits_image_filename = fits.util.get_testdata_filepath('kplr002304168-2009131105131_llc.fits')`

Unfortunately, I receive the following error message 
-->
URLError: <urlopen error Failed to download io/fits/tests/data/kplr002304168-2009131105131_llc.fits from the following repositories:
  - http://data.astropy.org/
  - http://www.astropy.org/astropy-data/>
<--
The full error is attached in a picture.
![screen shot 2018-08-22 at 12 34 11 pm](https://user-images.githubusercontent.com/42606953/44458837-ba935600-a607-11e8-8f97-dbbfe16d34e9.png)

**Comment by drdavella** [comment]
Hi @PieterMey, thanks for your question. Does `kplr002304168-2009131105131.fits` happen to be a file that you have locally? It does not appear to be part of Astropy's test data set.

If so, you can try opening it with this command:

```python
from astropy.io import fits

my_file = fits.open('kplr002304168-2009131105131.fits')
```

**Comment by pllim** [comment]
`get_testdata_filepath()` is only used by tests to get their data. I agree with @drdavella to try `fits.open()` instead. In addition, please help us improve the documentation by telling us where you saw the said suggestion. Thanks!

**Comment by MSeifert04** [comment]
I guess the "suggestion" is my fault. It's included in many parts of the fits documentation so it can be tested. 😓 The command can only be used to load files included in the astropy package or the astropy web pages.

**Comment by MSeifert04** [comment]
I think this comes down to a misunderstanding about what the `get_testdata_filepath` is for. It's very present in the narrative documentation so we can test the documentation and that user can also run these examples without having to download files. However it includes the name "testdata" so it should be pretty clear that it's only for testdata... Not sure what should or could be done here.

**Comment by astrofrog** [comment]
What about making the error message clearer to include a sentence that says something like 'Note that this function is only intended to be used to get files from ...'

**Comment by pllim** [comment]
> What about making the error message clearer

Sure! Against my own advice, I have marked this FITS issue as "good first issue". 🙈

**Comment by bsipocz** [comment]
> Sure! Against my own advice, I have marked this FITS issue as "good first issue". 🙈

you're fine, this is utils really, not fits ;)

**Comment by abhinuvpitale** [comment]
can this be solved by using a try and throws before the return in the get_testdata_filepath in util.py in astropy/io/fits, to check if the directory exists and catch the urlopen error?

That should also be a good place to add that comment about not using this function for anything else.

**Comment by pllim** [comment]
> can this be solved by using a try and throws

I wasn't envisioning any code change. Perhaps start with clarifying in the documentation where this function is used first and see how things go?

**Comment by abhinuvpitale** [comment]
@pillm - Its first used [here](http://docs.astropy.org/en/stable/io/fits/index.html)
and further two more times on the same page, thus causing the misunderstanding.

I am guessing that is what should be changed.

**Comment by pllim** [comment]
> I am guessing that is what should be changed

I agree! Looking forward to your PR. 😄

**Comment by abhinuvpitale** [comment]
I am not sure if a entry to changelog is needed here, let me know I will make the same !
@pllim

**Comment by Anne-Andresen** [comment]
Hi 
If its a local file  for your own data, you could use the following:
data= astropy.io.fits.open('path/filename.fits.gz')
