### ISSUE TITLE
PermissionError WinError32 using CCDData.read on Windows 10

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7757]
Specs: Astropy 3.0.4, Numpy 1.15.0, Python 3.6.6, `conda`, Git Bash, Windows 10, MSC v.1900 64 bit (AMD64)

```python
from astropy.nddata import CCDData
filename = 'https://astropy.stsci.edu/data/photometry/spitzer_example_image.fits'
ccd = CCDData.read(filename, numhdu=0)
```

```
Downloading https://astropy.stsci.edu/data/photometry/spitzer_example_image.fits
|===========================================| 2.1M/2.1M (100.00%)         2s
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)

~\Miniconda3\envs\py36\lib\site-packages\astropy\nddata\mixins\ndio.py in read(c
ls, *args, **kwargs)
     25         formats.
     26         """
---> 27         return io_registry.read(cls, *args, **kwargs)
     28
     29     def write(self, *args, **kwargs):

~\Miniconda3\envs\py36\lib\site-packages\astropy\io\registry.py in read(cls, for
mat, *args, **kwargs)
    528     finally:
    529         if ctx is not None:
--> 530             ctx.__exit__(*sys.exc_info())
    531
    532     return data

~\Miniconda3\envs\py36\lib\contextlib.py in __exit__(self, type, value, tracebac
k)
     86         if type is None:
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:
     90                 return False

~\Miniconda3\envs\py36\lib\site-packages\astropy\utils\data.py in get_readable_f
ileobj(name_or_obj, encoding, cache, show_progress, remote_timeout)
    316             fd.close()
    317         for fd in delete_fds:
--> 318             os.remove(fd.name)
    319
    320

PermissionError: [WinError 32] The process cannot access the file because it is
being used by another process: 'C:\\Users\\username\\AppData\\Local\\Temp\\tmp9j3hqa1c'
```

The weird thing is that I cannot reproduce when calling `get_readable_fileobj` nor `fits.open` directly.

@MSeifert04 , since you use Windows too, have you encountered this? Anyone?

**Comment by MSeifert04** [comment]
Puh, never seen this error with `read` but I haven't used it to download files ... yet.

**Comment by MSeifert04** [comment]
The error also happens to me when I run it locally with astropy master. My guess is that something in the download-machinery still holds the file while it's being "opened".

**Comment by pllim** [comment]
I also tried the following but did not get errors:

```python
from astropy.io import fits
pf = fits.open(filename)
```

and

```python
from astropy.utils.data import get_readable_fileobj
with get_readable_fileobj(filename) as pf:
    pass
```

**Comment by MSeifert04** [comment]
Is a memmap error. `CCDData` opens the file in memmap mode so the file is not actually closable.

If you use 

```
from astropy.nddata import CCDData
filename = 'https://astropy.stsci.edu/data/photometry/irac_ch2_flight.fits'
ccd = CCDData.read(filename, numhdu=0, memmap=False, unit='adu')
```

it works.

**Comment by pllim** [comment]
Oh, yes, `memmap=False` fixed it. Thanks!

What is odd? I was going to close this until you said something is odd.

**Comment by MSeifert04** [comment]
It works if I use it on a local file so something in the download-machinery makes a difference. Not sure if it's fixable - maybe it's just that the download hangs onto the file for a few milliseconds too long.

Maybe using `memmap=True` could be sensible for `CCDData`... I regularly run into problems with that and `CCDData`.

**Comment by pllim** [comment]
Hmm, if it is not fixable, should we close this or keep it open as a doc update of known issue?

**Comment by saimn** [comment]
It seems that the file is deleted once it is opened by the CCDData object, which Windows do not like. But one question is why the file is deleted: from what I can see the cache should be used by default, so the file should not be deleted.

**Comment by saimn** [comment]
Oh that's because the `io.registry` downloads the file when it doesn't know the format, and doesn't use the cache by default. So using `ccd = CCDData.read(filename, numhdu=0, format='fits')` goes directly into `fits.open` which use the cache by default.

**Comment by pllim** [comment]
Well, the problem is addressed for me, so I am okay with closing this, unless you want to keep it open for doc update. Your call. Thanks again!

**Comment by pllim** [comment]
Wait, just to clarify... Are you saying that if I use `format='fits'`, then I don't need to set `memmap=False`?

**Comment by pllim** [comment]
Confirmed that https://github.com/astropy/astropy/issues/7757#issuecomment-415592313 fixed both caching and permission error. No `memmap=False` needed.
