### ISSUE TITLE
hist breaks when range of input data is very large

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#7758]
When `hist` is given a large range of values and the `freedman` bin method is chosen memory use grows rapidly, (15GB when I killed the kernel after a few minutes), CPU usage jumps to 100%  and the histogram is never plotted even if the number of data points is small.

This case below reproduces the behavior on my computer; I don't think there is anything special about the set of numbers below, just that the range needs to be large. Note that only 10 points need to be histogrammed.

```python
import numpy as np

from astropy.visualization import hist

data = [ 9.99999914e+05, -8.31312483e-03,  6.52755852e-02,  1.43104653e-03,
             -2.26311017e-02,  2.82660007e-03,  1.80307521e-02,  9.26294279e-03,
             5.06606026e-02,  2.05418011e-03]
hist(data, bins='freedman')
```

I've seen this issue in both astropy 2.0.8 and 3.0.4 both in Python 3.6.

**Comment by pllim** [comment]
We don't usually milestone issues anymore. FYI.

**Comment by mwcraig** [comment]
Oops, thanks for letting me know. Accidentally tagged the wrong sub package initially too 🙄

**Comment by bsipocz** [comment]
@mwcraig - No worries, I don't think we've written this up anywhere yet. We can still milestone issues that are release critical, or we really mean to fix for a given release (so whoever doing a release can have a better idea what others meant to include, etc.)

**Comment by abhinuvpitale** [comment]
I am not sure how this a astropy issue, I think it should be with matplotlib !

**Comment by mwcraig** [comment]
@abhinuvpitale -- I agree that there is also a matplotlib issue. I would argue the astropy issue is that for reasonable inputs to `hist` with at least the  `freedman` method of auto-selecting bins, `hist` generates unreasonable output. 

I noticed the issue initially in trying to make a histogram of pixel values in an astronomical image. The image happens to have some odd values in it, but I imagine other people will hit the same thing. 

The test case above uses several GB of memory to try to histogram 10 data points which seems very wrong...

I do agree that a user who explicitly sets a large number of bins (say `bins=1000000`) is something we don't need to engineer for.

**Comment by abhinuvpitale** [comment]
I tried debugging the code and trying to find which part is taking the longest time.
The [line 62]( https://github.com/astropy/astropy/blob/master/astropy/visualization/hist.py#L62) is where it crashes. Trying to figure out why!
Let me know if you have any opinion on the same @mwcraig 

![image](https://user-images.githubusercontent.com/22462548/45401320-fae16500-b604-11e8-8977-ea6563ea557d.png)

**Comment by bsipocz** [comment]
I think you're both right. The stats part of the function indeed works, and it's mpl that at the end breaks. But, for @mwcraig's input of 10 number, `histogram(data, bins='freedman')` returns with 26327333 bins (and all but 4 of those bins are empty of course).

**Comment by bsipocz** [comment]
Actually doing `'knuth'` is even worse (I've need to cancel running it), only `'scott'` does something acceptable for this data. 

I haven't looked into the definitions in detail, but suspect it may be the natural consequence of the assumption each binning method has (e.g. that the data is approximately Gaussian, etc) and that is very much not right for the test data you've provided above.

**Comment by abhinuvpitale** [comment]
Should the documentation be updated to mention the same? @bsipocz

**Comment by bsipocz** [comment]
Oh, I meant to include a link to the docs here, I think it's covered there already, but @mwcraig can confirm whether he has seen this page or not:

http://docs.astropy.org/en/stable/visualization/histogram.html

Given that the problematic data points are very much outlying artefacts rather originate from the underlying distribution of data, the solution for the case above probably would be to either set the `range` kwarg manually, or sigma clip the data before histograming it. We may consider adding a new optional kwarg for it, but I feel it would open more cans of worms than issues it solve.

**Comment by astrofrog** [comment]
I think we should probably have an upper limit of bins above which we raise a warning about the number of bins being used...

**Comment by abhinuvpitale** [comment]
@astrofrog I think the problem is with the data points rather than the number of bins. So therefore we should put either manually set the `range` kwarg or somehow catch the warning earlier and display it based on data!

**Comment by bsipocz** [comment]
@abhinuvpitale - What you mean the problem is with the data points? 10 data points shouldn't be an issue but the 20M bins.

@astrofrog - I like the idea of the warning, but it may better belong to matplotlib given that it's the plotting that chokes on it? Do you have a suggestion what number we should use as upper limit?

**Comment by astrofrog** [comment]
I think we should just check at what point Matplotlib takes too long to compute the histogram - that is, what number of bins causes Matplotlib to take ~1 second with only a few data points.

**Comment by abhinuvpitale** [comment]
@bsipocz - I meant that the error is because of the data points that are not typically Gaussian, hence matplotlib generates a lot of bins while computing the hist! 
But yes, I think checking at what point matplotlib chokes is a better way to throw a warning rather checking the data points as suggested by @astrofrog

**Comment by bsipocz** [comment]
@abhinuvpitale - The bins are computed by astropy and passed as those large arrays to mpl.

**Comment by abhinuvpitale** [comment]
Got it! Apologies for the confusion!
[Here](https://github.com/astropy/astropy/blob/master/astropy/stats/histogram.py#L152), right?

**Comment by mwcraig** [comment]
*sigh* 

It turns out there are multiple issues that should probably be addressed, only one of which is exposed by this test case:

+ When a large number of patches is generated, matplotlib takes forever to plot them. That is the issue demonstrated by the example code above. This has a semi-elegant fix if many of the bins contain zero items; simply eliminate all of the empty bins, which can be done in a few lines of code using scipy.
+ As currently implemented `np.histogram` is calculated *twice*: once explicitly in `astropy.histogram` and a second time in `matplotlib.hist` (see [this code from hist](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L6568)). I don't see a good fix for that immediately. Well, actually, I do. We can do the bin calculation in `astropy.hist` and not bother to call `astropy.stats.histogram`, or do our own histogram drawing. The former is probably the way to go. We only call histogram to get the bins right now
+ astropy's bin-finding algorithms can be very slow if the number of bins is large, essentially because of [lines like this](https://github.com/astropy/astropy/blob/master/astropy/stats/histogram.py#L211). That is another argument in favor of refactoring astropy's `hist` to calculate the bin widths internally before doing the actual histogram.

**Comment by mwcraig** [comment]
> I think we should just check at what point Matplotlib takes too long to compute the histogram

Around 1,000 bins (with 10 data points)
