### ISSUE TITLE
rst files are no longer tested

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#7762]
The current version of the testing setup does no longer test any of the code in the `doc/` folder, and thus the code in the documentation could be out-of-date and we did not know.
I noticed this for an affiliated package and originally opened it as an issue for `sphinx-doctestplus` at https://github.com/astropy/pytest-doctestplus/issues/24 but at this time it's not clear if it needs to be resolved in astropy itself, astropy-helpers, sphinx-doctestplux, travis-ci or upsteam in pytest.
In any case, it seems that pytest 3.5.x works in full, pytest 3.6.x runs the tests, and I don't know what would happen on pytest 3.7 because that has another bug causing infinite recursion in the test detection. Thus travis-ci currently freezes the pytest version to 3.6.

This probably effects all packages that use the astropy test infrastructure (I checked astropy, photutils and marxs), but I won't open separate issues for each an every infrastructure package and each and every affiliated package. This issue and the link to https://github.com/astropy/pytest-doctestplus/issues/24 with more details will have to suffice.

**Comment by hamogu** [comment]
From: @drdavella in #7764
(Copied over here for ease of reading.)
This was originally reported in astropy/pytest-doctestplus#24, although I believe the name of that issue is misleading. Git bisect led me to 10359e4, which was part of #7463. Unfortunately, that means that this has been happening for quite some time, and it appears to affect any affiliated package that uses the test runner.

More investigation required, but hopefully this will be easy to resolve.

**Comment by hamogu** [comment]
@drdavella Thansk for finding this. I'm looking into the astropy code and will let you know what I find.

**Comment by drdavella** [comment]
@bsipocz you can go for it 👍

**Comment by hamogu** [comment]
@bsipocz : If you see it, go for it. I had an idea, but that did not solve it so it's all yours now.

**Comment by hamogu** [comment]
However, I disagree with @drdavella notion that the pytest verison is a red herring. I setup a new conda environment with astropy and all dependencies, and the doc/rst were not tested. Then, I downgraded pytest from 3.6 to 3.5 in that same environment, so I should be using the same version of astropy, astropy-helpers etc. and still, just this change in pytest version made is work. 
It's of course possible that there is more than one solution and it can be fixed on the astropy side to work for any version of pytest and the fact that the current astropy version tests the docs with pytest 3.5 is an accident. (Or not an accident. @bsipocz probably developed #7463 with the then-current version of pytest.)

**Comment by drdavella** [comment]
@hamogu it's possible that the `pytest` version is related. The reason I claimed that it was not is that I isolated the offending commit using `git bisect` in an environment with `pytest==3.5` installed. So I saw both working and not working behavior in the same environment, entirely dependent on the version of Astropy installed.

However, there are a lot of moving pieces here, so it's possible that changes to `pytest` are involved.

**Comment by bsipocz** [comment]
the issue was that I didn't test #7463 without specifying the module names as it takes ages, so missed out the fact that the path for the docs wasn't added back for that case. Now I'm waiting for the tests to run locally.
Now sure what caused the pytest version dependence, changes in #7463 should be agnostic to versions.

**Comment by pllim** [comment]
Deja vu! We went through doctest breakage before when switching from `pytest` 2.x to 3 (#5695).

**Comment by bsipocz** [comment]
here we can't really blame pytest though ;)

**Comment by bsipocz** [comment]
Fix is there in #7767, no need to wait for the full CI to pass.

**Comment by drdavella** [comment]
@hamogu I just created a new environment with `pytest==3.5` and the latest astropy and ran the tests, and the doc tests did not run. I'm not sure what the difference is between our environments, but as long as #7767 works for you, I'm willing to call it a fix.

**Comment by hamogu** [comment]
In my project the doctests still don't run, with either pytest 3.5 or 3.6 and the master astropy. However, the important thing for this issue is that it works in astropy again. I'll have to find out what's different in my setup. Not sure why I saw them running before, nor do I understand why they are not run now with the @bsipocz fix in place.

**Comment by pllim** [comment]
Are you somehow caching on Travis and using an older Astropy that you thought? I am also not sure if there is a lag between a merge into `master` and this command that `ci-helpers` use:
```
$PIP_INSTALL git+https://github.com/astropy/astropy.git#egg=astropy --upgrade --no-deps
```

**Comment by pllim** [comment]
@hamogu , if you install Astropy dev manually and run your project's tests locally, does it work?

**Comment by hamogu** [comment]
@pllim No, I'm testing locally with the current master. I can go into the `docs` directory and run `pytest` there, so it's not about missing dependencies.

**Comment by pllim** [comment]
And doctests are back on `master` and passing! https://travis-ci.org/astropy/astropy/jobs/419745266

**Comment by bsipocz** [comment]
hmm, this is getting rather odd. Out of interest, do they run with astropy 3.0.2?

**Comment by pllim** [comment]
`pip` + `conda` = :fire:
