### ISSUE TITLE
Error from test_locale in astropy/wcs/tests/test_wcsprm.py

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#7780]
With Python 3.7 and pytest 3.7.3 the `test_locale` in `astropy/wcs/tests/test_wcsprm.py` is failing:
```
E       ValueError: unknown locale: UTF-8
```
Full log: https://gist.github.com/cdeil/ec17433218bb2f2075b8c9361be69dcc

Here's what I have:
```
$ python
Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.resetlocale(locale.LC_NUMERIC)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/software/anaconda3/envs/astropy37/lib/python3.7/locale.py", line 614, in resetlocale
    _setlocale(category, _build_localename(getdefaultlocale()))
  File "/Users/deil/software/anaconda3/envs/astropy37/lib/python3.7/locale.py", line 568, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/deil/software/anaconda3/envs/astropy37/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
>>> locale.LC_NUMERIC
4
>>> locale.getlocale(locale.LC_NUMERIC)
(None, None)
```

This was added by @embray and reviewed by @mhvk in #4362 .

I don't understand the locale handling there, maybe one of you or someone else that knows about locale can fix this?

**Comment by saimn** [comment]
This seems to be an issue with your system configuration. What is the output of `locale` on your system, and are you setting some value for `LANG` in your `.bash_profile` or similar ? 

Some links that can help:
https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python (you should probably set only `LANG`, not `LC_ALL`, but not sure)
*A locale name is typically of the form language[_territory][.codeset][@modifier]* (from https://jlk.fjfi.cvut.cz/arch/manpages/man/setlocale.3).

**Comment by cdeil** [comment]
This is what I have:
```
(astropy37) hfm-1804a:gammapy deil$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
Is it possible to rewrite that test to be more robust, even if my locale settings are broken?

**Comment by astrofrog** [comment]
See http://docs.astropy.org/en/stable/known_issues.html#locale-errors-in-macos-x-and-linux

**Comment by astrofrog** [comment]
I'm going to close this since this is already documented as a known issue (not an astropy bug)
