### ISSUE TITLE
Serialization of times to FITS format strings

### ISSUE THREAD

**Issue by timj** [astropy/astropy#7781]
I've just been pointed to http://docs.astropy.org/en/stable/time/ and I see that FITS format strings are being generated as `2010-01-01T00:00:00.000(UTC)` but reading the FITS time standard I can't see any evidence that there is an expectation that this format is acceptable for time headers such as `DATE-OBS`. Am I misreading [Rots et al 2015](http://adsabs.harvard.edu/abs/2015A%26A...574A..36R)? Section 4.1.2 of that paper uses that syntax to show how one time can have three different answers but none of the examples use that format. FITS uses the `TIMESYS` header to indicate the time scale.  Can you point me at some part of the standard that is explicit about this?  We noticed at LSST because we were using `astropy.time` and the `fits()` method (documented at http://docs.astropy.org/en/stable/api/astropy.time.TimeFITS.html#astropy.time.TimeFITS ) to generate values in some FITS headers and all our tooling broke trying to parse them since we considered them non-standard. Any help appreciated.

This seems to have been added to astropy in #3547.

**Comment by timj** [comment]
I'm sorry, I see now that this is a duplicate of #5329 but it is still not clear to me that Rots et al is saying what the current implementation implies it is saying.

**Comment by mhvk** [comment]
@timj - I looked at Rots et al. again, and, like you, cannot see any explicit text that states the timescale should be appended. I don't really know why I thought it was the case when I implemented this in #3547 - the only reason I can think of is that the text itself is littered with times with the scale in parentheses, but it now looks like that was just done to help keep examples brief.

Anyway, for `Time` itself, this perhaps does not matter that much (indeed, it is somewhat handy to be able to make the distinction from `isot`, and I worry that changing it would break more than it would solve) - I guess what would really help for you, however, is to ensure we do not write this to the fits headers, but rather ensure `TIMESYS` is properly set (or whatever the relevant keyword for a table, etc.).

**Comment by timj** [comment]
In some sense it is indeed useful having a string that tells you the information. The confusion is calling it `fits()`.  Maybe we could add a new method `fitshdr()` or something? Then make it clear that is the form to use when writing to a FITS header and also to recommend TIMESYS?

**Comment by pllim** [comment]
Should we close this as duplicate and move the rest of the conversation back to #5329 ?

**Comment by astrofrog** [comment]
Fixed in https://github.com/astropy/astropy/pull/7870
