### ISSUE TITLE
Timeline for removal of deprecated astropy.tests.pytest_plugins

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#7782]
Importing from `astropy.tests.pytest_plugins` was officially deprecated in the 3.0 release, but has been maintained for backwards compatibility (see #6606 and specifically c16c2fa). 

However, the discussion on https://github.com/astropy/pytest-doctestplus/issues/22 seems to indicate that imports of the form `from astropy.tests import pytest_plugins` are definitively broken with recent versions of `pytest`.

This raises a question: should we move forward with the removal of the `astropy.tests.pytest_plugins` submodule earlier than we would for other deprecations?

cc @nicoddemus

**Comment by nicoddemus** [comment]
@drdavella thanks for including me.

Just a small note: this has been broken for quite awhile actually, not only on recent pytest versions. I tested with `3.1` for example and get the same error. This reproduces the issue:

```python
class pytest_plugins: pass
```

```
λ pytest foo.py
============================= test session starts =============================
platform win32 -- Python 3.6.5, pytest-3.1.0, py-1.5.3, pluggy-0.4.0
...
=================================== ERRORS ====================================
___________________________ ERROR collecting foo.py ___________________________
_pytest\runner.py:157: in __init__
    self.result = func()
_pytest\runner.py:328: in <lambda>
    lambda: list(collector.collect()),
_pytest\python.py:401: in collect
    self.session._fixturemanager.parsefactories(self)
_pytest\fixtures.py:1048: in parsefactories
    holderobj = node_or_obj.obj
_pytest\python.py:204: in fget
    self._obj = obj = self._getobj()
_pytest\python.py:398: in _getobj
    return self._importtestmodule()
_pytest\python.py:445: in _importtestmodule
    self.config.pluginmanager.consider_module(mod)
_pytest\config.py:409: in consider_module
    self._import_plugin_specs(getattr(mod, 'pytest_plugins', []))
_pytest\config.py:412: in _import_plugin_specs
    plugins = _get_plugin_specs_as_list(spec)
_pytest\config.py:462: in _get_plugin_specs_as_list
    "list/tuple of strings for plugin names. Given: %r" % specs)
E   _pytest.config.UsageError: Plugin specs must be a ','-separated string or a list/tuple of strings for plugin names. Given: <class 'foo.pytest_plugins'>
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.28 seconds ===========================
```

**Comment by drdavella** [comment]
@nicoddemus thanks. I suspected as much but it sounded like @cdeil started seeing the error just very recently, so I wasn't very sure. I'm not familiar enough with `gammapy` to know whether something changed recently or not.

**Comment by drdavella** [comment]
Also, to be clear, imports of the form `from astropy.tests import pytest_plugins as plugins`, etc. are safe. So there's a workaround, but I'd still be in favor of removing this sooner rather than later.

**Comment by pllim** [comment]
See #7786

**Comment by astrofrog** [comment]
Can we easily check on GitHub for any use of the deprecated API and fix it so that we can remove it?

**Comment by drdavella** [comment]
Those queries still bring up a lot of false hits since it also brings up safe imports of `pytest_plugins`. Too bad we can't' just use a regex...

**Comment by pllim** [comment]
Even "safe imports" will break if we remove the `pytest_plugins` module from here, right?

**Comment by drdavella** [comment]
Gah yes, of course. 👍

**Comment by nicoddemus** [comment]
With pytest 3.8 users will be able to see [this warning](https://github.com/astropy/astropy/blob/master/astropy/tests/pytest_plugins.py#L25) now (thanks to https://github.com/pytest-dev/pytest/pull/3931), so perhaps this can wait a few more months to give users a chance of changing their imports? 

Also, instead of removing it right away, the warning can be changed to an error, and then eventually removed in a future release. That's how we plan to handle deprecations on pytest.

**Comment by bsipocz** [comment]
@pllim - for the github projects we can open mass PRs to change the imports. The real question is how many projects using this that are not on github. And how much we should care for those (given that this is purely an infrastructure question).

**Comment by bsipocz** [comment]
Actually this issue became an error on the LTS branch now that pytest 4.0 is out. What should we do? Limit the version number of pytest in `setup.py` to be 4.0?

https://travis-ci.org/astropy/astropy/jobs/458963326#L4336

**Comment by pllim** [comment]
Oh, dear. Should we bet on people who are stuck with LTS (2.x) are also stuck with older `pytest`?

**Comment by bsipocz** [comment]
I suppose that's the only solution as we are not suppose to remove any API from LTS. 

I suspect the only up-to-date users of LTS is the CI for the affiliated packages ;)

**Comment by bsipocz** [comment]
@drdavella @astrofrog - do you think we can remove this in 3.1, or we need to keep it in the for 3.2 or even for 4.0?

My milestoning to 2.0.10 is moot now that we won't remove this from the LTS branch, but rather added an upper limit for the supported pytest version.

**Comment by drdavella** [comment]
I'm in favor of removing as soon as possible, but I guess I feel a little less conservative than most about this kind of thing.

**Comment by pllim** [comment]
@drdavella , your past self seems to disagree -- https://github.com/astropy/astropy/pull/7786#issuecomment-433916573

**Comment by drdavella** [comment]
@pllim at that time it was not clear (or I was not paying attention) that this would be completely broken by `pytest-4.0` and/or when exactly 4.0 would be released. So in light of that information, I think it should be removed as soon as possible.

**Comment by astrofrog** [comment]
> I suspect the only up-to-date users of LTS is the CI for the affiliated packages ;)

Or any Python 2 users/developers, right?
