### ISSUE TITLE
realize_frame does not accept representation_type

### ISSUE THREAD

**Issue by astrojuanlu** [astropy/astropy#7784]
I wanted to create a new frame using data coming from elsewhere, so `realize_frame` is exactly the method I needed. However, despite the name of its only parameter `representation_type`, the final `representation_type` of the result is the one coming from the default of the coordinate frame:

```
In [9]: ICRS().realize_frame(representation_type=CartesianRepresentation(1, 0, 0, unit='km'))
Out[9]: 
<ICRS Coordinate: (ra, dec, distance) in (deg, deg, km)
    (0., 0., 1.)>

In [10]: _.representation_type
Out[10]: astropy.coordinates.representation.SphericalRepresentation
```

In fact, `BaseCoordinateFrame.realize_frame` just calls `_replicate`, passing `representation_type` as `data`, which makes more sense, and `_replicate` does allow the user to override the default `representation_type`:

```
In [14]: ICRS()._replicate(data=CartesianRepresentation(1, 0, 0, unit='km'),
    ...: representation_type="cartesian")
Out[14]: 
<ICRS Coordinate: (x, y, z) in km
    (1., 0., 0.)>
```

I suggest that

* `BaseCoordinateFrame.realize_frame` parameter is renamed to `data` (which is less confusing),
* that it sets the `representation_type` using the class of the data,
* or alternatively that allows the user to override the `representation_type` in the proper sense:

```
In [2]: ICRS().realize_frame(data=CartesianRepresentation(1, 0, 0, unit='km'))
Out[2]: 
<ICRS Coordinate: (x, y, z) in km
    (1., 0., 0.)>
```

**Comment by astrofrog** [comment]
@eteq @adrn - can you comment on this?

**Comment by eteq** [comment]
Thanks for pinging on this in #7923, @Juanlu001 - this touches on the subtle distinction that `data` can be *any* representation type, but `representation_type` is sort of the "view" into that data.  

So with that pattern in mind, I think we should do your first suggestion (change it to `data`) but *not* the other two. There's two reasons for that:
1. `realize_frame` is used internally in a lot of places assuming that it does *not* change the representation type, rather that the defaults for the frame should be used
2. I think it's good to have a way for `realize_frame` to just set the data and *not* the `representation_type`.  You can always manually set the type by just doing ``coord.representation_type = CartesianRepresentation`` after all.

That said, a compromise might be to add a boolean keyword `set_representation_cls`.  Then your example would still be the almost-as-simple case of `ICRS().realize_frame(data=CartesianRepresentation(1, 0, 0, unit='km'), True)`.  I think I'm sort of +0 to this idea, but I think it could be implemented in #7923 (along with the change to `data`)

**Comment by adrn** [comment]
I'm neutral on the issues raised. Happy to change the kwarg to `data` if we go with @eteq's suggestion.

**Comment by eteq** [comment]
OK, to summarize a short discussion on slack: I think we agreed to switch to `data` for #7923 but leave for 3.2 the question of whether to add an additional argument or otherwise update the behavior.

**Comment by astrojuanlu** [comment]
We identified this issue as a soft blocker to address #6435 and #10253 without disrupting current users too much. @mhvk we can either add a `representation_type` to `realize_frame`, that will then be passed to `._replicate`, or just accept arbitrary `**kwargs` (which would essentially be the same as making `._replicate` public, if I understand correctly). What do you think?

**Comment by mhvk** [comment]
My sense would be to just add `**kwargs` since that is what the "inverse", `replicate_without_data`, does as well.

**Comment by astrojuanlu** [comment]
xref: gh-10727
