### ISSUE TITLE
[Feature Request] Exponential1D model

### ISSUE THREAD

**Issue by ysBach** [astropy/astropy#7792]
I found there are polynomial models but not exponential models in [astropy's modeling](http://docs.astropy.org/en/stable/modeling/index.html).

What about including `Exponential1D` and `Exponential2D`?

**Comment by eteq** [comment]
Hmm, technically you can get exponentials by using the sersic model with n=1 ... Or even by doing linear fits on logarithmic data.  But I see the point that sometimes you just want the most natural model.

Just to make sure we're saying the same thing, though, @ysBach, you mean this, right:

1d: ``y = A * exp(x/x0)``
2d: ``z = A * exp((x**2+y**2)/r0)``

?

One could imagine the x and y in the 2D case having rotation/scale baked in, but I'm inclined to say instead you should make a compound model with rotation and scale to do that?

**Comment by swapsha96** [comment]
@eteq @ysBach Please have a look at this. Similarly, I will write for 2D models if this is correct. Please let me know. Do I create PR for this?

# Exponential and Logarithmic models using Astropy modeling


```python
from astropy.modeling import Fittable1DModel, Parameter
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline
```


```python
class Logarithmic1D(Fittable1DModel):
    amplitude = Parameter()
    x_0 = Parameter()

    @staticmethod
    def evaluate(x, amplitude, x_0):
        return amplitude*np.log(x/x_0)

    @staticmethod
    def fit_deriv(x, amplitude, x_0):
        d_amplitude = amplitude
        return [d_amplitude]

    @property
    def inverse(self):
        new_amplitude = x_0
        new_x_0 = amplitude
        return Exponential1D(amplitude=new_amplitude, x_0=new_x_0)


class Exponential1D(Fittable1DModel):
    amplitude = Parameter()
    x_0 = Parameter()

    @staticmethod
    def evaluate(x, amplitude, x_0):
        return amplitude*np.exp(x/x_0)

    @staticmethod
    def fit_deriv(x, amplitude, x_0):
        d_amplitude = amplitude/x0
        d_x_0 = x0
        return [d_amplitude, d_x_0]

    @property
    def inverse(self):
        new_amplitude = x_0
        new_x_0 = amplitude
        return Logarithmic1D(amplitude=new_amplitude, x_0=new_x_0)
```


```python
# Parameters of the models
x_0 = 1
amplitude = 1

# Generating data
x = np.linspace(0.1, 10., 200)
model_1 = Exponential1D(amplitude, x_0)
y_1 = model_1(x)
model_2 = Logarithmic1D(amplitude, x_0)
y_2 = model_2(x)

# Plot the data
plt.figure(figsize=(8,6))
plt.plot(x, y_1, label='Exponential')
plt.legend()

plt.figure(figsize=(8,6))
plt.plot(x, y_2, label='Logarithmic')
plt.legend()
```




    <matplotlib.legend.Legend at 0xb1971bef0>




![output_3_1](https://user-images.githubusercontent.com/14021461/45290478-516b7800-b50d-11e8-9549-269be322a87f.png)




![output_3_2](https://user-images.githubusercontent.com/14021461/45290485-54feff00-b50d-11e8-8f85-3c4fb9ce766e.png)




```python
print(np.allclose(x, model_1.inverse(model_1(x))))
print(np.allclose(x, model_2.inverse(model_2(x))))
```

    True
    True

**Comment by astrofrog** [comment]
cc @nden

**Comment by nden** [comment]
@swapsha96 Can you come up with sensible defaults for the parameters? Otherwise this looks good to me. Could you make a PR and add them to `functional_models.py` ? It's easier to comment on PRs. Also please include tests in `test_models.py`.

@ysBach Are the expressions in the `evaluate` methods above what you expect?

**Comment by ysBach** [comment]
@nden @swapsha96 Sorry for the late reply! They look good and are what I expected :)

**Comment by jbkalmbach** [comment]
Hi,

I am going to pick up this issue from the code that was provided in the PR and see if I can finish it off if nobody has any complaints. @swapsha96 ?

**Comment by karllark** [comment]
Just looking for an exponential model in modeling.   Great to see the PR and looking forward to using it.
