### ISSUE TITLE
TST: ImportError: cannot import name 'ellipkm1'

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7796]
Re #7791 -- Not so fast, @mhvk ... 😬 

```
_________ ERROR collecting astropy/units/tests/test_quantity_ufuncs.py _________
ImportError while importing test module '/tmp/astropy-test-uwepvpw7/lib/python3.6/site-packages/astropy/units/tests/test_quantity_ufuncs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
astropy/units/tests/test_quantity_ufuncs.py:1045: in <module>
    from scipy import special as sps
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/scipy/special/__init__.py:642: in <module>
    from .basic import *
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/scipy/special/basic.py:15: in <module>
    from ._ufuncs import (ellipkm1, mathieu_a, mathieu_b, iv, jv, gamma,
E   ImportError: cannot import name 'ellipkm1'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
```

https://travis-ci.org/astropy/astropy/jobs/424019371

**Comment by mhvk** [comment]
Ah, I had that locally and thought it was just some stupid problem with my setup. Very weird...

**Comment by astrofrog** [comment]
See https://github.com/scipy/scipy/issues/9220 - fix in progress

**Comment by astrofrog** [comment]
Also the actual fix is at https://github.com/numpy/numpy/pull/11880

**Comment by mhvk** [comment]
fix is merged so hopefully things will soon work...

**Comment by pllim** [comment]
I restarted https://travis-ci.org/astropy/astropy/builds/424719106 , let's see. 🤞

**Comment by pllim** [comment]
Okay, we're back at `TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'` that is a known issue already for `modeling`. Thanks for the quick fix, y'all!
