### ISSUE TITLE
Please backport commit #e5ce1e3b0210

### ISSUE THREAD

**Issue by matteobachetti** [astropy/astropy#7802]
Commit e5ce1e3b0210 has a very small bugfix that would be great to backport in the earlier versions of Astropy: `from validate import VdtMissingValue` -> `from .validate import VdtMissingValue`

```
  File "/Users/meo/anaconda/envs/basie3/lib/python3.6/site-packages/basie/rich_validator.py", line 312, in validate
    res = conf.validate(rich_validator, preserve_errors=True)
  File "/Users/meo/anaconda/envs/basie3/lib/python3.6/site-packages/astropy/extern/configobj/configobj.py", line 2167, in validate
    from validate import VdtMissingValue
ModuleNotFoundError: No module named 'validate'
```

**Comment by pllim** [comment]
That commit was from #7537 ,  which was milestoned to 2.0.8, which should have been released already in Aug 2018. Is that not sufficient for your use case? What Astropy version are you using?

**Comment by matteobachetti** [comment]
It's a code that needs to be run on Python 2.6, so only pretty old versions of astropy can be used :(.

**Comment by bsipocz** [comment]
@matteobachetti - I'm very sorry, but we do not support older than LTS releases, thus nothing will be officially backported to a version that still supports 2.6. Your workaround can be to locally patch it with the fix.

**Comment by matteobachetti** [comment]
Ok, will do.
