### ISSUE TITLE
WCS: missing error check for zero coordinates (ncoord)

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy#7804]
[src](https://github.com/astropy/astropy/blob/master/astropy/wcs/src/pipeline.c#L101-L108)
```c
int
pipeline_all_pixel2world(
    pipeline_t* pipeline,
    const unsigned int ncoord,
    const unsigned int nelem,
    const double* const pixcrd /* [ncoord][nelem] */,
    double* world /* [ncoord][nelem] */) {

...

if (has_wcs) {
    buffer = mem = malloc(
        ncoord * nelem * sizeof(double) + /* imgcrd */
        ncoord * sizeof(double) +         /* phi */
        ncoord * sizeof(double) +         /* theta */
        ncoord * nelem * sizeof(double) + /* tmp */
        ncoord * nelem * sizeof(int)      /* stat */
        );

    if (buffer == NULL) {
      status = wcserr_set(
        PIP_ERRMSG(WCSERR_MEMORY), "Memory allocation failed");
      goto exit;
    }
...
```

Shouldn't there be a check for ``ncoord > 0`` before being used for allocation size? ``malloc`` can still accept a zero size so I'm not sure if this intentional or a bug? _c.f._ https://en.cppreference.com/w/c/memory/malloc

> _"If size is zero, the behavior is implementation defined (null pointer may be returned, or some
non-null pointer may be returned that may not be used to access storage, but has to be passed to free)."_

This trips up in the subsequent call to ``wcsp2s`` [here](https://github.com/astropy/astropy/blob/master/astropy/wcs/src/pipeline.c#L144)  with the following error ([src](https://github.com/astropy/astropy/blob/master/cextern/wcslib/C/wcs.c#L2645-L2649)):
```c
...
/* Sanity check. */
  if (ncoord < 1 || (ncoord > 1 && nelem < wcs->naxis)) {
    return wcserr_set(WCSERR_SET(WCSERR_BAD_CTYPE),
      "ncoord and/or nelem inconsistent with the wcsprm");
  }
...
```

Inspecting the values a this point for my example ``ncoord == 0``. (BTW: it's a good idea for errors to print values and boundaries.)

This is a similar error as reported in https://github.com/astropy/astropy/issues/4973 _"Don't raise an error if passing zero coordinates to WCS"_, excpet that it is in ``wcsp2s`` and not ``wcss2p``.

```
InconsistentAxisTypesError: ERROR 4 in wcsp2s() at line 2647 of file cextern/wcslib/C/wcs.c:
ncoord and/or nelem inconsistent with the wcsprm.
```

**Comment by jamienoss** [comment]
@nden any ideas?

**Comment by jamienoss** [comment]
Regarding the ``malloc(0)`` behavior, for the implementation case that a null ptr is returned, the subsequent error check `` if (buffer == NULL)`` _"Memory allocation failed"_ would be, at least, a misleading error.

This makes me think that this wasn't intentional and is a bug, due to the variation in behavior.

**Comment by jamienoss** [comment]
```
---------------------------------------------------------------------------
InconsistentAxisTypesError                Traceback (most recent call last)
<ipython-input-3-cafd5a7e002f> in <module>()
      2 test = TestReprojectDrizzle()
      3 test.setup_method(None)
----> 4 test.test_array_wcs_header()

~/dev/reproject/build/lib.macosx-10.7-x86_64-3.6/reproject/tests/test_high_level.py in test_array_wcs_header(self)
     72         assert exc.value.args[0] == "Need to specify shape since output header does not contain complete shape information"
     73 
---> 74         self.func_to_test((self.array_in, self.wcs_in), self.header_out_size)
     75 
     76     def test_array_wcs_wcs(self):

~/dev/reproject/build/lib.macosx-10.7-x86_64-3.6/reproject/tests/test_high_level.py in func_to_test(self, *args, **kargs)
     86 class TestReprojectDrizzle(Reproject):
     87     def func_to_test(self, *args, **kargs):
---> 88         return reproject_drizzle(*args, **kargs)
     89 
     90 INPUT_HDR = """

~/dev/reproject/build/lib.macosx-10.7-x86_64-3.6/reproject/drizzle/high_level.py in reproject_drizzle(input_data, output_projection, shape_out, hdu_in, scale, pixel_fraction, kernel, exposure_time, units)
     87                               scale=scale, pixel_fraction=pixel_fraction,
     88                               kernel=kernel, exposure_time=exposure_time,
---> 89                               units=units)

~/dev/reproject/build/lib.macosx-10.7-x86_64-3.6/reproject/drizzle/core.py in _reproject_drizzle(array, wcs_in, wcs_out, shape_out, scale, pixel_fraction, kernel, xmin, xmax, ymin, ymax, exposure_time, units)
     45                                                             kernel=kernel, fill_value="NaN", weight=None,
     46                                                             xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax,
---> 47                                                             exposure_time=exposure_time, units=units)
     48 
     49     # If a value was not NaN but now is, it was added by drizzle indicating that

~/dev/drizzle/build/lib.macosx-10.7-x86_64-3.6/drizzle/drizzle.py in drizzle(image, in_wcs, out_wcs, scale, pixel_fraction, kernel, fill_value, weight, xmin, xmax, ymin, ymax, exposure_time, units)
    687     container.add_image(image, in_wcs, inwht=weight,
    688                         xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax,
--> 689                         expin=exposure_time, in_units=units)
    690 
    691     return container.outsci, container.outwht, container.outcon

~/dev/drizzle/build/lib.macosx-10.7-x86_64-3.6/drizzle/drizzle.py in add_image(self, insci, inwcs, inwht, xmin, xmax, ymin, ymax, expin, in_units, wt_scl)
    383                             xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax,
    384                             pixfrac=self.pixfrac, kernel=self.kernel,
--> 385                             fillval=self.fillval)
    386 
    387 

~/dev/drizzle/build/lib.macosx-10.7-x86_64-3.6/drizzle/dodrizzle.py in dodrizzle(insci, input_wcs, inwht, output_wcs, outsci, outwht, outcon, expin, in_units, wt_scl, wcslin_pscale, uniqid, xmin, xmax, ymin, ymax, pixfrac, kernel, fillval)
    175 
    176     # Compute the mapping between the input and output pixel coordinates
--> 177     pixmap = calc_pixmap.calc_pixmap(input_wcs, output_wcs)
    178 
    179     #

~/dev/drizzle/build/lib.macosx-10.7-x86_64-3.6/drizzle/calc_pixmap.py in calc_pixmap(first_wcs, second_wcs)
     42     idxmap = idxmap.reshape(first_naxis2 * first_naxis1, 2)
     43 
---> 44     worldmap = first_wcs.all_pix2world(idxmap, 1)
     45 
     46     if second_wcs.sip is None:

//anaconda/lib/python3.6/site-packages/astropy/wcs/wcs.py in all_pix2world(self, *args, **kwargs)
   1278     def all_pix2world(self, *args, **kwargs):
   1279         return self._array_converter(
-> 1280             self._all_pix2world, 'output', *args, **kwargs)
   1281     all_pix2world.__doc__ = """
   1282         Transforms pixel coordinates to world coordinates.

//anaconda/lib/python3.6/site-packages/astropy/wcs/wcs.py in _array_converter(self, func, sky, ra_dec_order, *args)
   1254             if self.naxis == 1 and len(xy.shape) == 1:
   1255                 return _return_list_of_arrays([xy], origin)
-> 1256             return _return_single_array(xy, origin)
   1257 
   1258         elif len(args) == self.naxis + 1:

//anaconda/lib/python3.6/site-packages/astropy/wcs/wcs.py in _return_single_array(xy, origin)
   1238             if ra_dec_order and sky == 'input':
   1239                 xy = self._denormalize_sky(xy)
-> 1240             result = func(xy, origin)
   1241             if ra_dec_order and sky == 'output':
   1242                 result = self._normalize_sky(result)

InconsistentAxisTypesError: ERROR 4 in wcsp2s() at line 2647 of file cextern/wcslib/C/wcs.c:
ncoord and/or nelem inconsistent with the wcsprm.
```

**Comment by jamienoss** [comment]
This is also an issue in [pipeline_pix2foc](https://github.com/astropy/astropy/blame/master/astropy/wcs/src/pipeline.c#L199).

**Comment by nden** [comment]
@jamienoss Do you have a use case which raises an error? As I mentioned in #4973 if you call the astropy.wcs methods you won't get an error. The request there (and the subsequent fix) was to return the empty arrays. Or is this a "good practice" type PR?

**Comment by nden** [comment]
I see. Drizzle probably links to the C code.

**Comment by nden** [comment]
The question is do you need wcs to raise an error or return the empty input in drizzle?

**Comment by jamienoss** [comment]
So the entry point is ``astropy.wcs. all_pix2world()`` from [here in Drizzle](https://github.com/spacetelescope/drizzle/blob/master/drizzle/calc_pixmap.py#L44).

```
~/dev/drizzle/build/lib.macosx-10.7-x86_64-3.6/drizzle/calc_pixmap.py in calc_pixmap(first_wcs, second_wcs)
     42     idxmap = idxmap.reshape(first_naxis2 * first_naxis1, 2)
     43 
---> 44     worldmap = first_wcs.all_pix2world(idxmap, 1)
     45 
     46     if second_wcs.sip is None:

//anaconda/lib/python3.6/site-packages/astropy/wcs/wcs.py in all_pix2world(self, *args, **kwargs)
   1278     def all_pix2world(self, *args, **kwargs):
   1279         return self._array_converter(
-> 1280             self._all_pix2world, 'output', *args, **kwargs)
   1281     all_pix2world.__doc__ = """
   1282         Transforms pixel coordinates to world coordinates.

//anaconda/lib/python3.6/site-packages/astropy/wcs/wcs.py in _array_converter(self, func, sky, ra_dec_order, *args)
   1254             if self.naxis == 1 and len(xy.shape) == 1:
   1255                 return _return_list_of_arrays([xy], origin)
-> 1256             return _return_single_array(xy, origin)
   1257 
   1258         elif len(args) == self.naxis + 1:

//anaconda/lib/python3.6/site-packages/astropy/wcs/wcs.py in _return_single_array(xy, origin)
   1238             if ra_dec_order and sky == 'input':
   1239                 xy = self._denormalize_sky(xy)
-> 1240             result = func(xy, origin)
   1241             if ra_dec_order and sky == 'output':
   1242                 result = self._normalize_sky(result)

InconsistentAxisTypesError: ERROR 4 in wcsp2s() at line 2647 of file cextern/wcslib/C/wcs.c:
ncoord and/or nelem inconsistent with the wcsprm.
```

__However__ this is for astropy v3.0.4 and your fix (#7746) is currently only in master, as v2.0.9 hasn't been released yet.

When using master (57de423b74cdf596754ab8ad09890d4a207a25e3) I no longer get this error, I do get another though but it's in drizzle and seems unrelated enough to not be covered in this issue.

Either way, there are the above bugs in ``astropy/wcs/src/pipeline.c``.

**Comment by jamienoss** [comment]
>The question is do you need wcs to raise an error or return the empty input in drizzle?

I think this type of question is better suited to the type of issue in #4973. I know I've kinda introduced them both in this issue, so sorry for the confusion but this issue should really only be about the bugs fixed by #7806 and others similar.

**Comment by jamienoss** [comment]
>>The question is do you need wcs to raise an error or return the empty input in drizzle?
>
>I think this type of question is better suited to the type of issue in #4973. I know I've kinda introduced them both in this issue, so sorry for the confusion but this issue should really only be about the bugs fixed by #7806 and others similar.

Sorry, unless you're asking me whether the guard should raise an error or just return, in which case, I have no idea, I'm not familiar enough with ``astropy.wcs`` to answer that broader design question.

**Comment by nden** [comment]
@jamienoss I was asking what drizzle needs.

**Comment by jamienoss** [comment]
@nden 
>  I was asking what drizzle needs.

I have no idea at this point, I'm looking into the other issues that I have with drizzle (or what I'm doing wrong with it).

That being said, I don't really understand the rationale for the question, sorry. I would have thought that what we do regarding #7806 should be totally agnostic to drizzle's "needs", especially concerning this bug in question (``malloc(0)``). You either raise, recover, or return; the latter two I don't know enough about the wcs design to know that the rest of the wcs code can trivially handle ``pipeline_all_pixel2world()`` and ``pipeline_pix2foc()`` _just_ returning or returning an empty array of the same shape etc (I doubt recovery is an option or even good design).

In #7806 I decided to raise simply on the grounds that those two funcs already do so for ``nelem != 2`` (actually one raises and the other asserts, I hadn't noticed the second until later and just stuck with the raise - I still think this would be better discussed in the PR, btw).

> I have no idea at this point,

Well, maybe some, I expect that raising will require minimal if any, changes to handle the raise from wcs. The alternatives would probably require propagating changes in drizzle.

Either way, what ever WCS decides to do that then impacts drizzle, should be dealt with in drizzle, no?

**Comment by jamienoss** [comment]
BTW I don't yet even know that what I am doing is not "user error", that I'm trying to use drizzle incorrectly and that therefore whether drizzle needs _any_ code changes in ``astropy.wcs``. The relation to drizzle and this bug is completely circumstantial - that I noticed it whilst looking for something else.

**Comment by nden** [comment]
@jamienoss Agreed that the relation to drizzle is circumstantial.
I'm not very familiar with this code and am looking through it trying to figure out in what conditions one can run into this bug in current master (which is why I asked about the use case). I think after #7746
calling `wcs.all_pix2wordl` and `wcs.all_world2pix` will never go through this path in the code since it will always return the empty array at the python level. So yes, strictly speaking it is a bug but it can't be reached.

OTH a call to `wcs.wcs.p2s(np.zeros((0,2)), 1)` goes through a different code path, calls directly wcslib's `wcsp2s` and raises the error:
```
InconsistentAxisTypesError: ERROR 4 in wcsp2s() at line 2647 of file cextern/wcslib/C/wcs.c:
ncoord and/or nelem inconsistent with the wcsprm.
```
This is done in `wcslib_wrap.c` [PyWcsprm_p2s](https://github.com/astropy/astropy/blob/master/astropy/wcs/src/wcslib_wrap.c#L1186) where `ncoord` is initialized to 0 and passed as `int` so there's no memory allocation. So I think that code path is safe as well.

Does this seem correct to you?

**Comment by jamienoss** [comment]
>OTH a call to wcs.wcs.p2s(np.zeros((0,2)), 1) goes through a different code path, calls directly wcslib's wcsp2s and raises the error:

Yeah, that seems safe, I'm only worried about the ``malloc(0)``.

> Does this seem correct to you?

All seems right to me at quick glance. I wouldn't doubt you anyhow, even if you're unfamilar with this code you're still inifintely more familiar than I am.

>So yes, strictly speaking it is a bug but it can't be reached.

You're right, post #7746 this bug can't be reached from the wcs methods, however, for something as trivially fixed as this, I don't think it matters. Especially since you're only considering, here, the _current_ instance of the code base and not the future. It should be fixed regardless. If the concern of reachability is determining the impact of this bug, i.e. pre #7746 what did this bug mess up, that's a good point and maybe something for someone (SHOTGUN NOT ME!) to hunt down. Knowing this might determine which min version gets fixed and possibly any other notifications to users, if any, etc.

#7746 is set for >=v2.0.9,  is this the oldest maintained version? If so, the hunt suggested above prob. doesn't matter.

**Comment by jamienoss** [comment]
> #7746 is set for >=v2.0.9, is this the oldest maintained version? If so, the hunt suggested above prob. doesn't matter.

Actually, this might not be true, I guess someone might want to know if this could have passed all the way through, without any error, and have been unknowingly responsible for given users bogus results.

If you want my test case that hit this, let me know and I'll put it together for you - it's dev code in reproject & drizzle.

**Comment by nden** [comment]
Agreed this should be fixed. If your use case is different from calling `all_pix2world` or `all_world2pix`, yes, please post it here. I don't worry too much about how spread this could have been because it's a bit of a superficial use case which came up (I think) recently when we started writing tools that use these functions. It's unusual to call those methods with empty arrays.

Before this is merged, could you change  the error message to `WCSERR_BAD_PIX`?
