### ISSUE TITLE
Bayesian Blocks Algorithm - Understanding Buckets

### ISSUE THREAD

**Issue by andrewcz** [astropy/astropy#7821]
Hi All,
Really like the library and appreciate all the hard work of the
 contributors.
I have a question regarding Bayesian blocks.
Consider the algorithm puts data automatically into buckets.
Is there a way to structure a query so that two columns are produced, one with the value of the
series and one with the corresponding bucket it was placed into.
For example, if the algorithm produces 7 buckets then the output is -

value            **bucket**
34                    **1**
66                    **2**
100                **5**
23                   **3**
45                   **7**
32                    **2**
45                     **5**

These would be columns of a pandas data frame?
Then this column could then be used in a multiclass classification algorithm.

Many thanks for your help.
Best,
Andrew

**Comment by pllim** [comment]
cc @jakevdp 🙏

**Comment by jakevdp** [comment]
Bayesian Blocks only returns the bin edges; you can find bin membership for each point quickly with ``np.searchsorted``:

```python
import numpy as np
import pandas as pd
from astropy.stats import bayesian_blocks

np.random.seed(0)
values = np.concatenate([np.random.rand(100), 0.5 * np.random.rand(100)])
bins = bayesian_blocks(values)
data = pd.DataFrame({'value': values,
                     'bucket': np.searchsorted(bins, values)})
```

**Comment by andrewcz** [comment]
Amazing!!
Thank you so much, Jake, for your generous guidance.
So, just to confirm how would I use the post-processing step with the below example - 

import warnings
import numpy as np
import matplotlib.pyplot as plt
from astropy.visualization import hist

# generate some complicated data
rng = np.random.RandomState(0)
t = np.concatenate([-5 + 1.8 * rng.standard_cauchy(500),
                    -4 + 0.8 * rng.standard_cauchy(2000),
                    -1 + 0.3 * rng.standard_cauchy(500),
                    2 + 0.8 * rng.standard_cauchy(1000),
                    4 + 1.5 * rng.standard_cauchy(1000)])

# truncate to a reasonable range
t = t[(t > -15) & (t < 15)]

# draw histograms with two different bin widths
fig, ax = plt.subplots(1, 2, figsize=(10, 4))

fig.subplots_adjust(left=0.1, right=0.95, bottom=0.15)
for i, bins in enumerate(['knuth', 'blocks']):
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')  # Ignore bayesian block p0 warning
        hist(t, bins=bins, ax=ax[i], histtype='stepfilled',
             alpha=0.2, density=True)
    ax[i].set_xlabel('t')
    ax[i].set_ylabel('P(t)')
    ax[i].set_title('hist(t, bins="{0}")'.format(bins),
                    fontdict=dict(family='monospace'))



many thanks and best,
Andrew

**Comment by jakevdp** [comment]
something like this:
```python
counts, bins, patches = hist(t, bins=bins, ...)
buckets = np.searchsorted(bins, t)
```

**Comment by andrewcz** [comment]
Amazing! Thank you so much, Jake!

Just one more brief question, if I want to consider fewer blocks in my histogram how to a fit the function so that there a wider blocks for my data?  Would I fit a higher threshold?

Will experiments to see if the blocks are a good fit for multiclass classification.
This issue can now be considered closed.
Many thanks all for your generous contributions.
Best,
Andrew

**Comment by pllim** [comment]
Thanks, @jakevdp !

**Comment by andrewcz** [comment]
Apologies @jakevdp.
I was wondering if you could give a brief comment in regards to options on making the bins wider on the histogram. Hence making fewer buckets on the plot. I was reading the Bayesian blocks function uses a fit of the data, so hence would a stricter fit mean fewer blocks on the histogram?
Many thanks.
Andrew

**Comment by jakevdp** [comment]
Bayesian blocks chooses bin edges based on changepoints in the data density, so it doesn't really make sense to ask for wider bins within that model. You could maybe adjust the parameters within the function to change the threshold for identifying changepoints, but I'm not sure what the best approach would be.

**Comment by andrewcz** [comment]
Hi Jake!
Amazing! thank you!
I was just wondering if there is a quick way to change the threshold in the function?
Many thanks,
Best,
Andrew

**Comment by jakevdp** [comment]
I don't know

**Comment by andrewcz** [comment]
Cheeers Jake!
Thank you :).
Have and an amazing day!
Best,
Andrew
