### ISSUE TITLE
Move astropy.tests.plugins.display out as standalone?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7823]
I find that plugin is generally useful even if a package does not depend on Astropy. What do you think? cc @drdavella

**Comment by pllim** [comment]
Never mind. Now that I dig around a bit more, I don't think this is worth it.

https://docs.pytest.org/en/latest/example/simple.html#adding-info-to-test-report-header

**Comment by bsipocz** [comment]
But this link is super useful for me in a package that doesn't (yet) use astropy testing, so thank you very much for digging it up. I'm still not sure whether it's worth switching, but getting the test header sorted is now won't be a big selling point.

**Comment by drdavella** [comment]
So here's a related question: if `pytest` provides this natively, then why not just use that rather than maintaining a custom plugin?

**Comment by pllim** [comment]
> why not just use that rather than maintaining a custom plugin

Good question. If we use this not as a plugin, on the affiliated side of things, provide that as a template should "solve" the problem. Backward compat though is different story...

**Comment by pllim** [comment]
@drdavella , if you think https://github.com/astropy/astropy/issues/7823#issuecomment-422002201 is worth pursuing, please open anew issue. Thanks!

**Comment by bsipocz** [comment]
I guess the answer is "for historical reasons" 😄

**Comment by drdavella** [comment]
Actually I looked, and the plugin already uses this mechanism and makes it a bit easier for the end user, so I don't think we need to change anything.

**Comment by drdavella** [comment]
@astrofrog, yes you're right. I hadn't looked closely enough before I made my first comment.
