### ISSUE TITLE
MNT: Remove unused imports from code base

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7824]
When I open up some code here and there, my `flake8` checker complains of unused imports. However, I don't know whether they are done on purpose or not. There needs to be a clean-up campaign where sub-package maintainers weed out unused imports or put in a comment on why they are needed.

p.s. Weeding out unused variables in this same campaign is a plus.

**Comment by astrofrog** [comment]
Once these are removed, we should add the code for unused import to the pycodestyle things we check.

**Comment by drdavella** [comment]
This would be a job for the truly insane, but what about at the same time making sure that all imports are ordered according to PEP8 recommendations:

> Imports should be grouped in the following order:
> 
> Standard library imports.
Related third party imports.
Local application/library specific imports.
You should put a blank line between each group of imports.

We could then add this check to pycodestyle as well.

**Comment by pllim** [comment]
> This would be a job for the truly insane

If we divide and conquer over say, several sprints, should be doable? Given some complains about our imports here, this is not an unreasonable clean-up?

> making sure that all imports are ordered according to PEP8 recommendations

Look who is OCD now! I vaguely remember @astrofrog saying that he likes his imports by alphabetical order or by line length? :trollface:

**Comment by drdavella** [comment]
Like @astrofrog, I like to order by line length _within_ groups (I guess we're OCD in the same way 😉), but I think PEP8 ordering should be respected whenever possible.

**Comment by Cadair** [comment]
Not insane at all: https://isort.readthedocs.io/en/latest/ assuming one automates it :wink: 

and 
https://github.com/sunpy/sunpy/blob/master/setup.cfg#L50

**Comment by Cadair** [comment]
The sunpy isort config (we haven't run it on the whole codebase yet, mainly pending a way to keep it sorted) sorts by import length of the package you are importing from (not total line length) and splits into

* standard lib
* thrid party
* astropy
* sunpy

with a line break between them as PEP 8 says.

**Comment by Cadair** [comment]
@pllim might have goaded me into #7827

**Comment by SG004** [comment]
I have a question. Would the Optimize Imports function in the Pycharm IDE be sufficient for optimizing the imports?

**Comment by bsipocz** [comment]
@SG004 - There is actually an open issue for this already. This actually turned out to not being a good first issue as one needs to be very careful and check for any conflicts with the all the other open PRs.

**Comment by nstarman** [comment]
I believe this issue can be closed? F401 detects unused imports!

**Comment by pllim** [comment]
Good to know. Thanks! 😸
