### ISSUE TITLE
Undefined variable m in configobj.py

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7825]
https://github.com/astropy/astropy/blob/e925369a6cc054596fde643261e634012002c0c0/astropy/extern/configobj/configobj.py#L142-L145

`flake8` complains about "undefined variable 'm'". Not sure if this is a bug or maybe `m` is mysteriously defined globally somewhere.

**Comment by drdavella** [comment]
I think `flake8` should ignore the entire `extern` directory.

**Comment by pllim** [comment]
But that missing `m` bothers me. If I were to report this upstream, where should I report it? https://github.com/DiffSK/configobj seems to have diverged?

**Comment by bsipocz** [comment]
According to upstream, `Builder` is dead code and thus has been removed (https://github.com/DiffSK/configobj/commit/841f4c23795f3137bcacc6cad040fc5a1f4efd19, https://github.com/DiffSK/configobj/issues/61#issuecomment-182150884).
There is no new release for configobj though for a couple of years, and I've double checked and we indeed use the latest version. 
So while I agree it's disturbing, we need to let this go ;)

**Comment by bsipocz** [comment]
> https://github.com/DiffSK/configobj seems to have diverged?

the just didn't do a release for a while, but I guess you can try to ping them to do one.

**Comment by pllim** [comment]
Thanks for the gem in https://github.com/astropy/astropy/issues/7825#issuecomment-422134487 , @bsipocz ! 

```python
# XXX: There is no 'm' anywhere?! (and the name really sucks)
```

Fine, fine. (Never thoughts I would see Elsa in this repo. She's everywhere!)

**Comment by pllim** [comment]
p.s. Looks like DiffSK/configobj#160 already has multiple requests for a new release. Ah, well.

**Comment by bsipocz** [comment]
Ohh, good to see another proof that my memory is leaking (I didn't remember being down this road already https://github.com/DiffSK/configobj/issues/160#issuecomment-394854556)
