### ISSUE TITLE
IRAF <-> astropy translation document

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#783]
We should have an "IRAF->astropy" document on par with the https://www.cfa.harvard.edu/~jbattat/computer/python/science/idl-numpy.html  IDL->numpy translation.

The categories I have in mind:
- geometric transforms & WCS transforms (astropy + skimage?)
- stellar photometry (photutils, python wrapper of daophot?)
- catalog matching (IRAF ccxymatch, python... ?)
- graphical interaction (pyds9)
- GUI fitting of generic models (pymodelfit?)

Please add to this list as you see fit, and perhaps we can figure out where the document belongs.

**Comment by SaraOgaz** [comment]
It looks like I can't edit the assignees for this, but I'd like to put myself on this, since I'm now technically getting paid to make sure this gets done...

**Comment by pllim** [comment]
Hmm... It won't let me assign to you...

**Comment by mwcraig** [comment]
ping @astropy/coordinators to please add @SaraOgaz as a contributor so she can be assigned.

@SaraOgaz -- let me know if you need help. I don't much about IRAF, but am one of the ccdproc devs and am reasonably familiar with photutils. One of the things to keep in mind is that the IRAF functionality is distributed across several packages.

**Comment by kelle** [comment]
I just added @SaraOgaz as a "contributor" with Write permission to this repo. Hopefully that'll do the trick.

**Comment by mwcraig** [comment]
Thanks, but no luck yet...also, I think permissions should be read, not write. The core maintainers group has write permissions...

**Comment by kelle** [comment]
changed to "read". it says Awaiting Response from Sara.

**Comment by pllim** [comment]
Okay, I assigned her successfully. Thanks!

**Comment by bsipocz** [comment]
Does this transition docs belongs here in the core package, or maybe a better fit is the astropy.org website, or the tutorials? If either of the latters, maybe the issue can be reopened there?

**Comment by pllim** [comment]
FWIW, @SaraOgaz started something like this at http://stak-notebooks.readthedocs.io/en/latest/ .

**Comment by SaraOgaz** [comment]
Oh man, I totally forgotten I had taken this issue.  Yeah, like @pllim noted, we have the notebooks going in the stak-notebooks repo, but I know CSI is also planning on tackling the more workflow style notebooks.  I haven't checked in with them about that for a while.

**Comment by SaraOgaz** [comment]
I should add, the plan is to publicize this repo by the end of the year to the general public.  Probably before then to some smaller groups of people to get feedback.

**Comment by bsipocz** [comment]
Sure, I wasn't looking for the finalized solution, just plainly triaging issues to find the ones that don't really belong to astropy core, but to separate efforts, so I could close them.

**Comment by pllim** [comment]
My vote is to close this issue. If Astropy organization want to tackle this in addition to what STScI is already doing, then it is more appropriate as an issue at `astropy-tutorials` repo anyway.
