### ISSUE TITLE
Broadcasting quantities

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#7832]
Currently, when broadcasting a `Quantity`, the result is a bare `ndarray`. Consider the following basic example:

```python
>>> import numpy as np
>>> from astropy import units as u
>>> q = [x for x in range(10)] * u.AA
>>> q
<Quantity [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.] Angstrom>
>>> np.broadcast_to(q, (4, 10))
array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
```

This isn't a *huge* deal, because I could have just done the following:
```python
>>> np.broadcast_to(q, (4, 10)) * q.unit
```

But it's annoying and redundant. It would be nice if `Quantity` handled this automatically. I'm not sure whether there's some kind of magic method we can add to `Quantity` to handle this properly? Otherwise maybe something like `astropy.units.quantity.broadcast_to`?

**Comment by mhvk** [comment]
@drdavella - the trick is to add `subok=True` - a result of my own annoyance at this quite a while ago (see https://github.com/numpy/numpy/pull/4622) - unfortunately, I couldn't convince numpy to do this by default... (this may get solved with the planned `__array_function__` interface; https://github.com/numpy/numpy/pull/11189)

Do close if this resolves the issue (or add to documentation, though I'm not sure where that would logically go)

**Comment by drdavella** [comment]
@mhvk thanks, that is very useful, but also very unintuitive (or at least not obvious). I'll see if I can add an example to the documentation.
