### ISSUE TITLE
Add Anaconda dist. compiler builds to travis tests

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy#7833]
As of Anaconda 5.0, their distributed packages, which includes astropy, are built with their own compilers ([ref](https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html
)). Perhaps we should be testing the builds with these compilers instead of or alongside the Travis ones (which are those from OSX and Ubuntu OS distributions)?

**Comment by jamienoss** [comment]
Breadcrumb: [Travis compiler doc](https://docs.travis-ci.com/user/languages/c/)

**Comment by bsipocz** [comment]
I don't think we ever had any problems regarding where the anaconda folks couldn't build astropy, but that doesn't mean we can't do this as an extra measure.

**Comment by jamienoss** [comment]
> I don't think we ever had any problems regarding where the anaconda folks couldn't build astropy

Yeah, I'm with you. The extra test really only makes fails our problem and not theirs which is prob. already true anyhow.

I was just thinking that if we're going to test against any compiler toolchain and runtime library suite that it should probably be the one that the package gets built by and distributed with, that's all.

There might be some merit in briefly mentioning (reminding) the anaconda build toolchain change to our developer community, assuming it hasn't already.

**Comment by bsipocz** [comment]
With #8307 in mind I close this issue as we never had any feedback from the Anaconda folks that they run into issues when packaging astropy.
