### ISSUE TITLE
"known issues" doctests should be run

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#7837]
In https://github.com/astropy/astropy/pull/7834#discussion_r218922328, it was noted that the file `known_issues.rst` has all its doctests skipped. This seems a bad idea: we should in fact test that the issues still exist (i.e., that the examples given give the wrong answer) and that the workarounds work. In particular, I have some hope some of the issues will disappear with future numpy versions - the doctests will then give us a heads-up so that we can insert version numbers and eventually remove the text.

**Comment by astrofrog** [comment]
One thing to note is that we'll want to still keep a known issue even if it's fixed in the very latest Numpy, since people may be slow to upgrade.

**Comment by SG004** [comment]
Is all that is being asked here, is to remove the doctest-skip-all at the top of the known_issue.rst file? I'd like to make a PR, but am curious as to exactly what I should do

**Comment by mhvk** [comment]
@SG004 - thanks! And, yes, basically it is removing the `doctest-skip-all` but of course you'd need to check that the doctests actually pass!  Some may be, e.g., numpy-version dependent, in which case they should still be skipped (and, if relevant, there should be a note about when the problem was solved). In practice, I think you'd remove it and test/adjust locally until all tests pass, and then submit the PR to see if there are any version dependencies via the travis automated testing.

**Comment by bsipocz** [comment]
@SG004 - "known issues" provides workarounds for many of the issues, as well as some of them are very specific to scenarios that our CI not necessary cover. So as @mhvk said above, it needs some tweaking to make sure everything passes.

**Comment by nzuckman** [comment]
Created a PR for the issue here:  astropy/astropy#8193

**Comment by astrojuanlu** [comment]
https://github.com/astropy/astropy/pull/8193 was merged, can this be closed?

**Comment by astrofrog** [comment]
Looks like it!
