### ISSUE TITLE
Have a way for "unitless" models to specify convertible units

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#7840]
Over in astropy/specutils#333 we've run into the problem that `Chebyshev1D` (like many polynomial models) doesn't support units. 

While I understand the reasoning there, I think there should be a mechanism by which this can be bypassed.  By that I mean the user should be able to say "the input units are X" and "the output units are Y", basically such that the eval ends up being:
```
def evaluate(self, x, ...):
    unitlessx = x.to(self.input_unit)
    unitless_result = self.real_evaluate(x, ...)
    return unitless_result.to(self.return_unit)
```
Mathematically this could also be thought of as an alternate model g that has the property `g = A f(x/B)`, where A are the return units and B are the input units.  But I think it's more awkward to express it as a combination of models vs just building unit conversions in.

More broadly, this should be an optional capability that *all* models have if they don't have specific units.  This supports use cases like arbitrary polynomial-fitting or spline-fits where the units of the model matter, but really just need to be "whatever the data set used for fitting is".

@nden @astrofrog @brechmos-stsci - any opinions?  I have ideas on how we might implement this, but don't want to go down that road if there's something obvious I'm missing about why this shouldn't work.

**Comment by pllim** [comment]
For now, you can subclass that model in your package and apply units as you see fit. See https://github.com/spacetelescope/synphot_refactor/blob/master/synphot/models.py for examples.

**Comment by eslavich** [comment]
@mhvk @eteq I opened #9936 with a proposal for addressing this.  I'd like to get notes on it before adding tests, can you take a look and let me know what you think?
