### ISSUE TITLE
Add python 3.7 MacOS wheels

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#7841]
It would be nice if some python 3.7 wheels could be added to PyPi for MacOS (as I type this pip is currently compiling astropy for me) - https://pypi.org/project/astropy/#files

**Comment by bsipocz** [comment]
Some of the 3.7 builds were indeed failing on travis so not all os flavour got one built. I've restarted hoping it's some self resolving issue. Otherwise would you mind to have a look at https://github.com/MacPython/astropy-wheels to figure out a fix?

**Comment by bsipocz** [comment]
This has been fixed in the meantime.
