### ISSUE TITLE
Is Pytest 3.1 really required?

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#7843]
There is [some interest in "backporting" astropy to Debian Stretch](https://github.com/poliastro/poliastro/issues/453#issuecomment-424807619), which comes with pytest 3.0.6.
In principle, we could also backport pytest, but only the current version (3.6.4), which pulls a long chain of new dependencies, which all would need to be packported. 

Therefore: Is the >=3.1 dependency strong? Or can we (maybe excluding some tests) still use pytest 3.0.6?

**Comment by drdavella** [comment]
The short answer is yes, it is really required. There are some tests in the suite that make use of `pytest.param`, which was only introduced in 3.1. Also, the `pytest-astropy` packages have a dependency on 3.1 as well, so you would not be able to use those.

It's maybe possible to rewrite the tests that use `pytest.param` in a different way. But I believe there's some other infrastructure that would need to change since `pytest-astropy` is a test dependency.

Personally I'm not really keen on the idea of downgrading the dependency since it would make it even more difficult to take advantage of new `pytest` features in the future. But I won't stand in the way if others disagree.

Thoughts from @bsipocz, @astrofrog?

**Comment by bsipocz** [comment]
And it is also required so the header in setup.cfg is not skipped though that's totally irrelevant after distro packaging.

**Comment by olebole** [comment]
OK, so we probably can't have a backport of astropy to Debian Stretch unless someone also backports pytest and its dependencies. I even have a solution how to prevent such a problem in future (since it is obviously a good idea to use the latest features of the dependencies instead of re-implementing or avoiding them).
It usually not a problem to just backport one or two more packages; if some more central infrastructure is involved, things become more complicated.
This is (probably) also a problem of the other distributions; therefore just adding @sergiopasra (Fedora) and @mboquien (Archlinux) -- do you have an idea here? Do you (plan to) do backports? How do you deal with dependencies then?

**Comment by Juanlu001** [comment]
If I understood correctly, astropy does not specify a minimum version of pytest-astropy (omission?) and older versions only depend on pytest >= 2.8:

https://github.com/astropy/astropy/blob/d099cfe5c69e6f10dc760446505b08b017a5aaf1/setup.py#L86-L88

https://github.com/astropy/pytest-astropy/blob/572635e181d10affa6e64ef4d2c1d8d1070a2717/setup.py#L45-L46

**Comment by drdavella** [comment]
@Juanlu001 yes, that seems right. I don't think there's any need at the moment to express a minimum version of `pytest-astropy` in `astropy`, though that may not always be true in the future.

While I realize that this would be a lot more work for you, it seems like backporting `pytest` could potentially be a very useful service for the rest of the Debian community.

**Comment by olebole** [comment]
@drdavella 
>it seems like backporting pytest could potentially be a very useful service for the rest of the Debian community.

I totally agree here. We just need a volunteer ;-)

**Comment by sergiopasra** [comment]
@olebole The older pytest in Fedora is 3.2 (Fedora 27), so no problem with us

**Comment by Juanlu001** [comment]
@olebole what about taking a less demanding route and backport an older version of pytest which is recent enough to serve astropy? Perhaps this way fewer dependencies will need to be backported. 3.2, as in Fedora, sounds good to me.

**Comment by olebole** [comment]
The problem here is the Debian backporting policy, which limits the backports to what we actually have in testing (and then asks to keep it up-to-date). This is clearly our home-made problem; and backporting pytest would probably also help others; however I am afraid that it will not happen soonisch.

**Comment by pllim** [comment]
So I think the **answer** is "yes but we need people to do it but we probably won't find anyone to do it. I think we can close this issue or do Debian or Fedora have plans to do such things?
