### ISSUE TITLE
FITS append/update is broken in Python 3.x

### ISSUE THREAD

**Issue by at88mph** [astropy/astropy#7854]
When appending to a FITS file using the `astropy.io.fits.append()` method, there is an error in Python 3.x.

Running the attached script in 2.7.x is fine (`astropy` is required):
`python github_issue.py`

Running it with 3.5, 3.6, or 3.7 results in:
`python github_issue.py`

```
  File "github_issue.py", line 19, in <module>
    github_issue()
  File "github_issue.py", line 13, in github_issue
    new_hdul.writeto(test_file_handle, overwrite=True)
  File "/usr/local/lib/python3.7/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 854, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/usr/local/lib/python3.7/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/astropy/io/fits/file.py", line 136, in __init__
    "handle mode '{}'".format(mode, objmode))
ValueError: Requested FITS mode 'ostream' not compatible with open file handle mode 'update'
```

**Comment by at88mph** [comment]
Here is the test code as I can't upload a Python file.

```python
import tempfile
import numpy as np
from astropy.io import fits


def github_issue():
    file_path = tempfile.NamedTemporaryFile().name

    with open(file_path, 'wb+') as test_file_handle:
      hdu1 = fits.PrimaryHDU()
      hdu2 = fits.ImageHDU()
      new_hdul = fits.HDUList([hdu1, hdu2])
      new_hdul.writeto(test_file_handle, overwrite=True)
      test_file_handle.close()

    with open(file_path, 'ab+') as append_test_file_handle:
      fits.append(filename=append_test_file_handle, data=np.empty((4,4)))

github_issue()
```

**Comment by drdavella** [comment]
It's possible that this is a bug or an oversight. However, the workaround is to change `wb+` in the first `open` call to simply `wb`. Using `wb+` implies `mode='update'` in FITS, whereas the current semantics of `writeto` imply `mode='ostream'`, which corresponds to `wb`.

**Comment by drdavella** [comment]
This assumption is encoded here:

https://github.com/astropy/astropy/blob/848c8fa21332abd66b44efe3cb48b72377fb32cc/astropy/io/fits/hdu/hdulist.py#L915-L919

It's possible that we could try to be a bit smarter about handling the mode here.

**Comment by drdavella** [comment]
Hmm, that change was enough to make things work for me. What versions of Astropy are you using?

**Comment by at88mph** [comment]
I meant in my application.  I extracted the important parts into the test.

One thing I did differently in the test code above was to use `wb` to issue a `writeto()` first, then to the append.  My application is just opening an empty file for `ab+`, which is when I got the error above.

So the test code would instead be:
```python
import tempfile
import numpy as np
from astropy.io import fits


def github_issue():
    _, file_path = tempfile.mkstemp(prefix='test_file_', suffix='.fits')

    with open(file_path, 'ab+') as append_test_file_handle:
      fits.append(filename=append_test_file_handle, data=np.empty((4,4)), overwrite=False, output_verify='silentfix', checksum=False)

github_issue()
```

Then you see the error with 3.x.

**Comment by drdavella** [comment]
Hmm, okay that does seem like a bug, then. Interestingly enough, it works fine if you do something like `file_path = 'test.fits'`, presumably because the file does not exist yet.

**Comment by drdavella** [comment]
I'll try to submit a PR to fix this shortly.

In the meantime, I wonder if you would consider not using `mkstemp` and instead just allowing `fits.append` to create a new file in the temporary directory?

**Comment by at88mph** [comment]
Thanks @drdavella.  Generating a file name and letting `fits.append` create it does work but only if I use `ab` and NOT `ab+`, which is odd since the `+` is what's supposed to signal a creation.  Weird.

**Comment by at88mph** [comment]
Sorry, I mean leave off the `+` for Python 3 only.

**Comment by drdavella** [comment]
@at88mph the issue title implies that `fits.update` is also affected. If that's the case, can you provide an example failure of that as well?

**Comment by at88mph** [comment]
I don't use the update feature, sorry.  The original update error above was from the test itself not properly setup.  That was my error.

I will test the PR soon.  Thank you!
