### ISSUE TITLE
millbar units?

### ISSUE THREAD

**Issue by timj** [astropy/astropy#7861]
Is there a reason that astropy.units has "bar" but disables prefixes? In lots of weather stations the units are in mbar. DECam data headers use mbar and I'd like to be able to read the header value and directly assign units of mbar rather than scaling by 1000 first (defeating the purpose of quantity to a certain extent). The fix is trivial (add `prefixes=True` to the bar definition) so I wonder if this omission was deliberate.

**Comment by pllim** [comment]
Unless @mdboom or @mhvk remembers, I am not sure. It could be there was a conflict with other units when prefixes were allowed, allowing prefixes was violating some sort of astronomical standards, or an oversight due to lack of demand (until now).

**Comment by mhvk** [comment]
Also no real knowledge of the background, but my guess would be that it was a sense that `bar` is never used with prefixes - which is true except for `mbar`.  I don't see any reason not to use the prefixes or at least include  `mbar`, i.e., use `prefixes=[(['m'], ['milli'], 1.e-3)]`.

**Comment by mhvk** [comment]
fixed by #7863
