### ISSUE TITLE
Unable to read in big csv file

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#7871]
This is most probably related to #7628

Given a large, [19G csv file](https://www.kaggle.com/c/PLAsTiCC-2018/data), and I'm unable to read it using astropy only.

When using the defaults naively, I run into a Segfault pretty quickly (within a minute):
```
from astropy.table import Table
testd=Table.read('test_set.csv')
```
Opting out of the fast reader, and turning of guessing etc, it's still running now after 50 mins, already eating up substantial amount of memory, so I'm killing it:

```
119752 bsipocz   20   0  204.2g 197.6g  14628 R  99.3 39.2  49:00.38 ipython   
117282 bsipocz   20   0   33.9g  29.7g  19440 S   0.0  5.9   9:48.62 ipython     
```

The second session above is the one where the file was read in using pandas. Converting that DataFrame to Table then of course works nicely.

**Comment by bsipocz** [comment]
(This is actually quite unfortunate as the starter kit for this kaggle suggest people to use astropy to read in the files.)

**Comment by taldcroft** [comment]
Have you tried reading in chunks?

https://astropy.readthedocs.io/en/latest/io/ascii/read.html#reading-large-tables-in-chunks

**Comment by astrofrog** [comment]
If chunks works better, can we automatically use chunks above a given file size? (are there downsides?)

**Comment by astrofrog** [comment]
Also I wonder whether we might want to have a ``format='pandas.csv'`` reader that does @bsipocz's workaround behind the scenes?

**Comment by bsipocz** [comment]
It took a while to read in which chunks, but it worked and now the overall memory print is smaller than it was with the pandas reader yesterday (as long as the numbers by `top` than be trusted).
```
 76724 bsipocz   20   0   24.8g  20.5g  15292 S   0.0  4.1 522:32.90 ipython 
```

**Comment by bsipocz** [comment]
On the other hand, I really don't see how to sensibly choose the file size above which we automatically switch to chunks, e.g the 19G on this machine with 500G+ memory shouldn't have been such a big deal to read in.

**Comment by astrofrog** [comment]
Am I reading it correctly that it took 9 hours??

**Comment by bsipocz** [comment]
no, I started it after I got in the office, so should be somewhere more like between 5-50 mins?

I'm restarting it with a timeit this time :)

**Comment by bsipocz** [comment]
@astrofrog - This is extremely weird:
```
In [13]: t=process_time()                                                                                               

In [14]: tbl = Table.read('test_set.csv', format='csv', guess=False, 
    ...:                  fast_reader={'chunk_size': 100 * 1000000})                                                    
process_time() -t    




Out[15]: 33521.331425633
```

**Comment by bsipocz** [comment]
for pandas it took ~9-10 mins to read in the file.

**Comment by saimn** [comment]
I did some testing using `data_end` to limit the number of lines, it is quite fast with 100_000_000 lines, and the files is only 4x more, but then it segfaults.This reminds me  #5319, maybe some variable with a wrong type.

```
❯ python test.py 10_000_000
Reading 10000000 lines
6.242653131484985 sec.
9999999 lines

❯ python test.py 100_000_000
Reading 100000000 lines
69.68614959716797 sec.
99999999 lines

❯ python test.py 200_000_000
Reading 200000000 lines
Fatal Python error: Segmentation fault

Current thread 0x00007fcac2ed5700 (most recent call first):
  File "/home/conseil/lib/astropy/astropy/io/ascii/fastbasic.py", line 128 in read
  File "/home/conseil/lib/astropy/astropy/io/ascii/ui.py", line 404 in read
  File "test.py", line 18 in <module>
[1]    14149 segmentation fault  python test.py 200_000_000
```

**Comment by taldcroft** [comment]
For files that fit in memory, the fast reader should be within a factor of two of pandas.  So I'm a bit perplexed.  One thing is that csv format is actually special because it handles missing values at the end, i.e. fewer commas.  The basic format with comma delimiter is a different parser and might be faster.

**Comment by ajtanskanen** [comment]
This is what trying to open test_set.csv on a Macbook Pro (2015, 16 GB, OSX 10.14) looks like:

> Python(3685,0x11259b5c0) malloc: can't allocate region
> *** mach_vm_map(size=18446744073608888320) failed (error code=3)
> Python(3685,0x11259b5c0) malloc: *** set a breakpoint in malloc_error_break to debug
> Segmentation fault: 11

That is a quite large malloc size.

**Comment by saimn** [comment]
So with a small fix I'm able to load the file (PR to come):
```
❯ python test.py
324.1676182746887 sec.
453653104 lines
```
Quite fast actually!
The issue is that the array storing the column length uses an integer. This file has a lot of lines, and the array size gets too big for a 32 bits integer.
