### ISSUE TITLE
Add build against developer version of Matplotlib

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7881]
We've run into a few issues in the past where changes in Matplotlib cause breakage in e.g. WCSAxes. It would be good to have a Matplotlib dev build - though maybe we can just do that as part of the Numpy-dev build if we are worried about adding too many configurations.

**Comment by bsipocz** [comment]
👍 for the idea, and also 👍 to fold it into the numpy dev build.

**Comment by bsipocz** [comment]
(although it makes me wonder how to deal with the baselines, I suspect that there are will be some genuine changes in the dev version, so do we keep adding dev baselines whenever something has changed there? If yes, can we come up with a robust way to do it?)

**Comment by astrofrog** [comment]
We could just run without the image tests, which would at least pick up API changes. But if we want to do image tests, we could simply update the latest baseline rather than adding a new one (until that baseline is used in a released version)

**Comment by bsipocz** [comment]
Yes, either way is fine for me.

**Comment by bsipocz** [comment]
Well, #7886 has solved this I think, so closing it.
