### ISSUE TITLE
fits.append() does not support documented fits.open() kwargs

### ISSUE THREAD

**Issue by at88mph** [astropy/astropy#7882]
According to the `append()` documentation, it supports the `kwargs` that are supported in the `open()` function:
http://docs.astropy.org/en/stable/io/fits/api/files.html#astropy.io.fits.append

However, I tried to use the `scale_back` `kwarg` value, but got this error:
```
TypeError: writeto() got an unexpected keyword argument 'scale_back'
```

To reproduce:
```
import tempfile
import numpy as np
from astropy.io import fits


def github_issue():
    _, file_path = tempfile.mkstemp(prefix='test_file_', suffix='.fits')

    with open(file_path, 'ab+') as append_test_file_handle:
      fits.append(filename=append_test_file_handle, data=np.empty((4,4)), overwrite=False, output_verify='silentfix', checksum=False, scale_back=True)

github_issue()
```

**Comment by drdavella** [comment]
@saimn I think this means we're going to need to pass `**kwargs` through `writeto` after all, although I did come up with a more elegant solution to the mode problem in #7856.

**Comment by saimn** [comment]
Hmm, the docstring says that kwargs are passed to `fits.open`, not `writeto`, but the code actually pass kwargs to `writeto` and only if the file does not exist... Anyway, passing kwargs to `fits.open` would be easy, and I think that it is really the right thing to do, not passing it to `writeto`. 

Btw @at88mph, you should use `fits.append(filename=file_path, ...)`, there is no need to open the file yourself and bother with the mode. Or if you need to do more with the file, use `fits.open` and `HDUList.append`.

And finally, passing `scale_back` to `fits.append` would do nothing: `scale_back` is useful only when reading scaled data, and saving it. But here `fits.append` will create a new unscaled HDU.

**Comment by at88mph** [comment]
Thanks @saimn.  It receives a file-like object now to support streaming to an HTTP response later as part of a service, so I don't want it to create a file.  The file creation is just for testing.

The `scale_back` was an attempt at re-adding the `BZERO` and `BSCALE` headers back in after I performed a cutout.  I've set `do_not_scale_image_data=True` in my `fits.getdata()`, and I need to put those headers back into the output.  Simply setting them doesn't work, so I assume something is sanitizing them somehow in the `write`.

**Comment by drdavella** [comment]
@saimn this is a doc bug then, right? And it's still kind of a bug since `**kwargs` don't get passed through in the case that an open file object is passed as the argument to `append`, but only when a filename is given.

**Comment by saimn** [comment]
@at88mph - Ok but I think that there is a confusion between the different keywords: 
- `scale_back` means that an HDU that has been read, and scaled, must be scaled back when writing, using the original BZERO and BSCALE.
- `do_not_scale_image_data` means that when reading HDUs, the data will not be scaled. And when saving, the original BZERO and BSCALE are also kept with the unscaled data.
- But here you want to append a new HDU, so none of these keywords apply for this HDU (though they can be useful for the other HDUs if you are appending to a file with multiple scaled HDUs). To create a new HDU with scaling, you have to use `HDU.scale`: http://docs.astropy.org/en/latest/io/fits/usage/image.html#writing-scaled-image-data

**Comment by saimn** [comment]
@drdavella - I think that the only issue is that `kwargs` is not passed to `fits.open`. Then when passing a file object it should handle the arguments, at least I guess so.

**Comment by kakirastern** [comment]
Hi, I am triaging and am checking to see if indeed this is still an ongoing issue, and found that if I run
```
import tempfile
import numpy as np
from astropy.io import fits

_, file_path = tempfile.mkstemp(prefix='test_file_', suffix='.fits')
```
and then open with the following
```
fits.open(file_path)
```
I would get the error `OSError: Empty or corrupt FITS file`. 

Next, I try to run the following on an existing non-empty 2D FITS file:
```
fits.append('/Users/kastern/Desktop/Astropy/moment1_copy.fits', np.ones((32,16)), overwrite=False, output_verify='silentfix', checksum=False, scale_back=True) 
```
Then no error is thrown.

**Comment by at88mph** [comment]
Hello.  My test case above still fails with version 3.1 (hash: 743055cada122d6da8704ad28452806690679ef5).  This issue is not holding me up anymore as I've worked around it for now, but the bug persists.

Thanks!

**Comment by kakirastern** [comment]
I think @drdavella was right about the Issue previously. See https://github.com/astropy/astropy/issues/7882#issuecomment-429383739.

Yeah, seems like there is some bug when passing the `kwargs` (supposedly including the `scale_back` parameter) to the `fits.writeto()` method as documented [here](http://docs.astropy.org/en/latest/cosmology/index.html#functions) with the `**kwargs` argument as stated in the [API documention](http://docs.astropy.org/en/stable/_modules/astropy/io/fits/convenience.html#append) for the `fits.append` function somehow doesn't work... Think a possible way to fix the bug might be in the way the `fits.writeto()` method is defined. 

Maybe I can experiment with this and open a PR to follow up. Let me play around with the idea first...

**Comment by kakirastern** [comment]
@drdavella Should I include some clarification in the docs to clarify the issue in a new PR? (I will only do so if I have your blessing.)

**Comment by kakirastern** [comment]
Sorry @saimn, neglected to add your handle in the previous https://github.com/astropy/astropy/issues/7882#issuecomment-466577185. It was truly my bad. I tend to think it is some "docs bug" or missing documentation in this regard. Should I update the relevant info with a new PR? It makes sense that an empty or corrupt input FITS file should have no 'scale_back' attribute. 

I can follow up with a PR and use very explicit language so that there would be no confusion. Please advise.

**Comment by saimn** [comment]
Looking at this with fresh eyes, I think that there are several things to do, because the inner function that is used is not always the same:

- if the file does not exist, `writeto` is used, and kwargs are passed here. The only option that can be used here is `output_verify`. We can keep it like this and document this properly.

- if the file exists, and filename is a string, `fits.open` is used. Here we need to pass kwargs.

- if the file exists, and filename is a file object, there is no additional argument to pass. We could maybe check that kwargs is empty and raise a warning if it is not empty ?

**Comment by kakirastern** [comment]
@saimn Sounds like a good plan! Will follow up with a PR soon.
