### ISSUE TITLE
SkyCoord.from_name() query fails 

### ISSUE THREAD

**Issue by amendochka** [astropy/astropy#7889]
Hello,

I was trying to use `SkyCoord.from_name()` and it has been failing for various objects randomly (i.e. seems to work for some but not for others).

Here is an example:
```
m33 = SkyCoord.from_name('M33')
print(m33)
```

And I get this error:

```
NameResolveError: All Sesame queries failed. Unable to retrieve coordinates. See errors per URL below: 
 http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/A?M33: Request took longer than the allowed 10.0 seconds
http://vizier.cfa.harvard.edu/viz-bin/nph-sesame/A?M33: Request took longer than the allowed 10.0 seconds 
```

Any insights on this? Is this a matter of a connection timeout with the database? Thanks in advance!

**Comment by amendochka** [comment]
Query seems to work now, but I wonder if there is a workaround if this happens in the future!

**Comment by adrn** [comment]
Hi @amendochka - did you end up resolving this? I agree with @pllim that this was likely to blame on the web service. But if you are still seeing this, please do reopen! Thanks!
