### ISSUE TITLE
Develop uncertainties framework for NDData

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#789]
As has been discussed in a variety of settings, we should decide on a framework for representing uncertainties in `NDData`.  Currently the only thing in there is std/var, and we should develop a framework that allows specifying more complex error distributions if desired. (and this _will_ be needed for #448).

This framework also should include a reasonably generic way of specifying how to propogate errors when `NDData` objects are combined or otherwise operated on.  This was one of the major reasons for having `NDData` in the first place, after all.

**Comment by wkerzendorf** [comment]
This is being "done" for Quantities through `UQuantity` for now. Furthermore, NDData is being restructured. Should we close this issue for now @eteq ?

**Comment by mwcraig** [comment]
Agree with @wkerzendorf...two years further on and we still aren't really any closer to a generic framework.
