### ISSUE TITLE
TimeDelta precision issue?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7898]
In the following example, I was a bit surprised to see that ``TimeDelta`` is not exactly 3 seconds - is this expected?

```python
In [4]: (Time('2016-03-22T12:30:34') - Time('2016-03-22T12:30:31')).sec 
Out[4]: 3.000000000000469
```

**Comment by lrm25** [comment]
I did some work on #7899.  Similar to that, the code is converting the values to TAI scale, which is probably resulting in the slight difference.

**Comment by mhvk** [comment]
Looking at this after being alerted via #7899: this is much more simply a rounding issue (get the same answer also when giving `scale='tai'`), resulting from the fact that times are stored internally as integer and fractional day (relative to nearest noon), so effectively what happens is:
```
In [31]: Time('2016-03-22T12:30:34', scale='tai').jd2 * 24 * 3600
Out[31]: 1833.9999999999957

In [32]: Time('2016-03-22T12:30:31', scale='tai').jd2 * 24 * 3600
Out[32]: 1830.9999999999952

In [33]: (Time('2016-03-22T12:30:34', scale='tai').jd2 - Time('2016-03-22T12:30:31', scale='tai').jd2) * 24 * 3600
Out[33]: 3.000000000000469
```

I'll close as this is not fixable. (Might be good to document, but if so best to just open a new issue.)
