### ISSUE TITLE
Quantity objects with nan values get duplicated in sets

### ISSUE THREAD

**Issue by namurphy** [astropy/astropy#7901]
When creating a [`set`](https://docs.python.org/3/tutorial/datastructures.html#sets) out of multiple `numpy.nan` objects, it will return a `set` with only one `numpy.nan` object within it.
```Python
>>> from numpy import nan
>>> {nan, nan}
{nan}
```
However, if we try to create a set out of multiple `Quantity` objects that have the same units but values of `numpy.nan`, then the `set` will contain multiple `Quantity` objects.  (Here I chose `attojansky` as the funniest unit I could think of, in lieu of #5927.)
```Python
>>> from astropy.units import attojansky
>>> {nan * attojansky, nan * attojansky}
{<Quantity nan aJy>, <Quantity nan aJy>}
```
I would have expected that the result be a set containing only one `Quantity`: `{<Quantity nan aJy>}`. 

One possibility would be to make it so that a `Quantity` with a value of `numpy.nan` be equal to itself.  However,  `numpy.nan` does not equal itself, so this change could lead to some inconsistencies or unexpected behavior.
```Python
>>> nan == nan
False
```
[This also reminds me of the quote from [The Prisoner](https://en.wikipedia.org/wiki/The_Prisoner)..."I an NaN, I am a free man!"]

Cross-references: #5420, #5424

**Comment by namurphy** [comment]
My use case in https://github.com/PlasmaPy/PlasmaPy/pull/404 was testing that three namedtuples were identical to each other, when the namedtuples could potentially contain a `Quantity` with a value of `numpy.nan`.  In case anyone else runs into the same situation in the future, my workaround was to convert each of the namedtuples to a `str`, put all of the new `str` objects into a `set`, and then make sure that the `set` contains one element.

**Comment by mhvk** [comment]
I'm not sure what to do about this, as a similar problem also occurs with `ndarray`:
```
a = np.array(nan)
{a, a}
# TypeError: unhashable type: 'numpy.ndarray'
```
Indeed, the above suggests that `Quantity` should not be hashable in the first place (since it can be changed in-place).

**Comment by MSeifert04** [comment]
Using NaN in sets/dicts is more or less undefined behavior because these data structures rely on equality (but `np.nan != np.nan`) but on the other hand some NaN instances reference the same instance (`np.nan is np.nan`). It's not really a bug, that's just how Python (or better CPython) works:

```python
>>> {np.nan, np.nan}  # same instance
{nan}

>>> set(np.array([np.nan, np.nan]))  # different instances when iterated over
{nan, nan}
```
