### ISSUE TITLE
Some issues with coordinates docstrings on representation

### ISSUE THREAD

**Issue by smoh** [astropy/astropy#7911]
I found a couple of issues with coordinates docstring on representation using `Galactic` frame. Codes to reproduce the issues summarized [here](https://gist.github.com/smoh/640c35352a477dfd5e930f6e0df2c7a2).

1. That the differentials must be at least 1/time and there is no unitless time (although there is unitless length) should be noted somewhere, and the error message printed when they are not can be improved?
2. Current docstring templating gives wrong information about initializing `Galactic` frame with the cartesian representation.

**Comment by adrn** [comment]
Thanks - agreed that these issues are documentation bugs!

**Comment by smoh** [comment]
Since you labeled it effort-low, I'd like to have a go with some guidance if needed. But I understand it may be really simple and quick for someone more familiar to take care of it.

To me, it didn't seem that trivial since this is right now hardcoded in `base_doc` and it needs to be broken down. It actually seemed best do generate doc by referencing `frame_specific_representation_info` but not sure if this is possible.

**Comment by pllim** [comment]
@adrn , please be more specific with the labels -- "effort low" for what expertise level? 😄

**Comment by bsipocz** [comment]
Well, without any other labelling I think it's a good assumption is that it's the effort level of the person doing the labelling :trollface:

**Comment by smoh** [comment]
I came across a possible related issue (#7458) and leave a comment for future reference.

**Comment by astrojuanlu** [comment]
After #9064, (1) was fixed:

```
In [9]: ICRS( 
   ...:   x=1, y=2, z=3, 
   ...:   v_x=1, v_y=2, v_z=3, 
   ...:   representation_type=r.CartesianRepresentation, 
   ...:   differential_type=r.CartesianDifferential, 
   ...: )                                                                                                                                                                                                                                     
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-916f1fc2c13a> in <module>
----> 1 ICRS(
      2   x=1, y=2, z=3,
      3   v_x=1, v_y=2, v_z=3,
      4   representation_type=r.CartesianRepresentation,
      5   differential_type=r.CartesianDifferential,

~/Personal/Astropy/astropy/astropy/coordinates/baseframe.py in __init__(self, copy, representation_type, differential_type, *args, **kwargs)
    580                     current_diff_unit = differential_data._units[f'd_{comp}']
    581                     if not current_diff_unit.is_equivalent(current_repr_unit / u.s):
--> 582                         raise ValueError(
    583                             "Differential data units are not compatible with"
    584                             "time-derivative of representation data units")

ValueError: Differential data units are not compatible withtime-derivative of representation data units
```

(oops, that missing whitespace!)

and (2) was addressed by adding a note on checking `frame_specific_representation_info` and `representation_info`. I think this issue can be closed, if others think there's still something to be done here please feel free to reopen.
