### ISSUE TITLE
TST: numpy dev failures for visualization

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7912]
Example log: https://travis-ci.org/astropy/astropy/jobs/442639772

Snippets:
```
astropy/visualization/scripts/tests/test_fits2bitmap.py
astropy/visualization/tests/test_norm.py
astropy/visualization/wcsaxes/tests/test_frame.py
astropy/visualization/wcsaxes/tests/test_images.py
E       DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
```
```
astropy/visualization/wcsaxes/tests/test_images.py
E       ValueError: need at least one array to concatenate
```

cc @astrofrog @mhvk

**Comment by pllim** [comment]
I guess the `np.asscalar` one can be fixed similarly as #7880

**Comment by bsipocz** [comment]
@pllim - this deprecation is actually coming from mpl rather than astropy, so I suppose we need to add it to the exceptioon list, or live with it for a while: https://travis-ci.org/astropy/astropy/jobs/442639772#L4409

**Comment by bsipocz** [comment]
(actually it has already been fixed in upstream mpl, so only a matter of time when the error is going away in our CI)

**Comment by pllim** [comment]
@bsipocz , I am not convinced that the Matplotlib PR also addressed `ValueError: need at least one array to concatenate`. What do you think?

**Comment by bsipocz** [comment]
Ohh, indeed, I was too hasty here and didn't notice that other issue. But I cannot see any more `np.asscalar` in mpl master. I'm adding back the labels then, and I'm sorry about the mess I caused.

**Comment by pllim** [comment]
No worries! Good catch on the matplotlib one.
