### ISSUE TITLE
Infrastructure to run only TEST_READ_HUGE_FILE tests

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#7916]
Should a test run involving running the TEST_READ_HUGE_FILE files part of the release procedure? If yes, it would be really nice to have an easy way to run just these tests but not the rest (though I suppose the extra ~+10 min shouldn't make a big difference).

If this has to be part of the procedure, please add it to the release docs. Making sure these tests pass shortly before a release is cut is rather important.

**Comment by astrofrog** [comment]
What are the requirements for this test in terms of disk space, time, and memory?

**Comment by bsipocz** [comment]
We currently have 2 of these, the order of ~10G should be enough? https://github.com/astropy/astropy/pull/7885#discussion_r226107929

**Comment by saimn** [comment]
I just ran the other test, so both create a 2.3Gb file, and I saw a peak of memory at 10.8Gb. Running both tests took ~5min (though this will depend on your hard-drive). So if there requirements are fine to run this during the release procedure, it is good to have. To run only those tests:
```
TEST_READ_HUGE_FILE=1 pytest -sv astropy/io/ascii/tests/test_c_reader.py -k big_table
```

**Comment by pllim** [comment]
Also https://github.com/astropy/astropy/pull/7941#issuecomment-431964991
