### ISSUE TITLE
Create equivalent of quantity_support() for plotting Time objects

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7930]
We [provide](http://docs.astropy.org/en/stable/units/quantity.html#plotting-quantities) a ``quantity_support()`` context manager that allows quantities to be seamlessly passed to Matplotlib. It would be nice to have something equivalent for ``Time`` objects, including if possible date/time formatting of the relevant axis.

**Comment by mhvk** [comment]
fixed by #8782
