### ISSUE TITLE
Add narrative documentation for new nddata uncertainty types

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#7959]
Also need to add a what's new entry for the change.

**Comment by bsipocz** [comment]
I'm milestoning as this issue has to be done for the release.

**Comment by mwcraig** [comment]
Also fix this docstring line (it isn't true anymore): https://github.com/astropy/astropy/blob/master/astropy/nddata/nduncertainty.py#L137

This one too: https://github.com/astropy/astropy/blob/master/astropy/nddata/nduncertainty.py#L148

**Comment by mwcraig** [comment]
Oops, this was closed by #8072

**Comment by mwcraig** [comment]
sorry, re-opening. I'll fix those docstrings this evening.
