### ISSUE TITLE
Add a helpful error message or way to pass in a key for from_address

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#7960]
As discussed in #7867, Google closed down non-API keyed access to the google maps address service.  This was fixed in master in #7918, but in a way that's not easily backportable. For the LTS branch we should do one of two things:

1. (Easy) Add a helpful error message that basically just says "sorry, google shut this down. You'll just have to manually get a lat/lon, or upgrade to astropy 3.1"
2. (Harder) Adapt the code in #7918 for passing a google API key, allowing users to get their own API keys and get back the functionality.

I have no strong opinion which one gets done other than that at least one of them gets done ASAP so that users don't get stuck with an obscure non-actionable error in the LTS branch any longer than necessary.

This should be implemented as a PR direct to the 2.x branch, *not* master, since #7918 fixed master in a not-easily-backportable way.

**Comment by pllim** [comment]
Easy way is merged. Do you want to close or keep it open in case you still want the hard way?

**Comment by bsipocz** [comment]
I'm removing the milestone and it's not critical for the release any more. Feel free to close it if you're happy with the current solution in the LST branch.

**Comment by eerovaher** [comment]
`astropy` version 2 has been unsupported for a long time now, so the issue of backporting patches to it has become obsolete.
