### ISSUE TITLE
Proposed solution for indexing of old RTD pages by search engines

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7967]
*Note: this is a complement to https://github.com/astropy/astropy/issues/7794 in which we discussed that we need a custom robots.txt to prevent indexing of old tags. This issue proposes an alternative solution*

### Background

In https://github.com/astropy/astropy/pull/7909, @dasdachs made it so that new versions of the docs on RTD have a meta tag:

```html
<meta name="robots" content="noindex, nofollow">
``` 

if the version is not ``latest`` nor ``stable``. This is good and works for the v2.0.x, v3.0.x, stable, and latest branches. It will also work for any new tagged version we release in future.

However, it doesn't solve the problem for all the old tagged versions we have. Most noticeably, v0.2.1 seems to always appear near the top in Google searches, which is frustrating. One solution is to retag all the releases to add a commit that adds the meta tag, but I don't think we want to re-tag all the versions, so that's not an option.

### Suggested approach

The key to the solution here is that RTD supports redirect patterns. Here's what I suggest we do:

**Preparing the astropy repository**

To start off, we make an ``archive`` branch in the astropy repository that is an empty branch (i.e. does not share history with ``master``), and we create a ``docs/`` folder, which then contains an ``archive/`` folder. In this folder, we place a static version (html, not rst) of all the problematic tagged versions that exist. Note that we don't need to build these, we can just web scrape them with e.g.

```bash
wget -r -np docs.astropy.org/en/v0.2.2/
```

We then edit the Sphinx configuration to include:

```python
html_extra_path = ['archive']
```

in it, which will cause any folder inside archive to get copied to the output ``_build/html`` directory. 

Next up, we edit (with a script) all the html files inside ``archive/`` to include the meta tag:

```html
<meta name="robots" content="noindex, nofollow">
```

We then commit and publish the docs with RTD. Note that the build will be quite fast since it's just copying static files.

Now at this point you're probably thinking *Jeez tom, isn't that a lot of files to include in a branch of the main repo? Each version is several tens of Mb, so isn't that like a Gb in total?* I'm glad you asked - in fact I skipped over some details above. The archive folder can actually be a submodule that points to another repository! Let's look at a real test case. I've made the following repository:

https://github.com/astropy/archived-documentation

which contains the static files. I've then made a repo with the sphinx configuration as described above, and archive is a submodule:

https://github.com/astrofrog/test-rtd/tree/archive/docs
(this would be the archive branch of the astropy repo)

*How do you know this works?* I hear you ask. 🤔 

Well, take a look at:

https://astrofrog-test-rtd.readthedocs.io/en/v0.2.1/

And notice the redirect!

**ReadTheDocs configuration**

Next up, we edit the RTD configuration. We set up a redirect for each tagged version that looks like this:

<img width="623" alt="screen shot 2018-10-25 at 10 27 53" src="https://user-images.githubusercontent.com/314716/47490532-d520c000-d840-11e8-85c4-924bd766ca6e.png">

As you can guess, this causes /en/v0.2.1/<anything> to redirect to /en/archive/v0.2.1/<anything>

Once the redirects are in place for all tagged versions, we remove the existing builds of the tags from RTD. And that's it!

### Frequently asked questions

**Isn't that going to be a lot of work to do?**

Not really - we can script the wget job above for each tag, and then script the insertion of the meta tags. The longest part will be setting up the redirects for a few dozen tagged versions (each one has to be done individually) but that will take ~10 min at most?

**Isn't that going to be a lot of work to maintain?**

Nope! This is a one-off affair, as new tagged versions will include the meta tag by default, so won't need this approach. This is purely for existing old tagged versions at this point in time.

**But won't this mean the versions won't show up in the list of versions in the pop up menu when visiting docs.astropy.org?**

It does, but that might not be a bad thing. Have you seen what that thing looks like at the moment??

<img width="321" alt="screen shot 2018-10-25 at 10 34 02" src="https://user-images.githubusercontent.com/314716/47491614-19ad5b00-d843-11e8-9ea2-ff0aa068fb80.png">

Instead of the old tagged versions, there will be an 'archive' version that users can click on. We could populate the index.rst file of the archive branch to include links to all the archived versions and explain these are all old versions and are kept for reproducibility.

**Are there other benefits to this?**

I'm glad you asked! One benefit is that if we ever need to make other kinds of changes in future to old published versions, this is a good mechanism to do so. Also we don't have to wait for RTD to implement support for custom ``robots.txt``.

### Thoughts/suggestions welcome!

I'm happy to do the work if we decide it's a good idea. Note that we can also first test with a single tagged version if people would be more comfortable with that.

**Comment by pllim** [comment]
Will it increase the size of the distributed tarball when people do `pip install astropy`? Tarball size came up because of a question of AWS charges (totally unrelated to this project itself but I am curious). 😬 

> Also we don't have to wait for RTD to implement support for custom `robots.txt`.

Does it also mean that once RTD implements the support, this method will be retired? If so, will it be complicated to undo?

**Comment by astrofrog** [comment]
> Will it increase the size of the distributed tarball when people do pip install astropy? Tarball size came up because of a question of AWS charges (totally unrelated to this project itself but I am curious). 😬

No - this lives completely in a separate branch of the repo so doesn't get included in the tar file

> Does it also mean that once RTD implements the support, this method will be retired? If so, will it be complicated to undo?

To be completely honest if it's all working fine by then, then there wouldn't be much point in switching over again. But yes if we wanted to start re-building v0.2 properly again we'd likely run into issues.

**Comment by pllim** [comment]
Another question is if we switch away from RTD completely, is this still a viable solution?

**Comment by astrofrog** [comment]
@pllim - I don't think this will make it any more difficult to change to another solution. If we self-host, then we have control over all the files anyway. If we host on a service that requires us to do all the builds via their service, then we'll need to do a similar solution anyway otherwise it's going to be fun to have to try re-building the docs for every single past tag and figure out all the sphinx etc versions required. So In a way this makes it *easier* to transition to another service if anything.

**Comment by pllim** [comment]
I have no objection to this then.

> if we wanted to start re-building v0.2 properly again we'd likely run into issues

I would say that that chance of any need of re-building v0.2 doc is very, very slim.

**Comment by eteq** [comment]
I have several questions:

* Jeez tom, isn't that a lot of files to include in a branch of the main repo? Each version is several tens of Mb, so isn't that like a Gb in total?
* How do you know this works?
* Isn't this going to be a lot of work to do?
* Isn't this going to be a lot of work to maintain?
* But won't this mean the versions won't show up in the list of versions in the pop up menu when visiting docs.astropy.org?
* Are there other benefits to this?

**Comment by eteq** [comment]
Translation of https://github.com/astropy/astropy/issues/7967#issuecomment-434492099 : this is a great idea and thanks for your thoroughness in investigating it @astrofrog! :wink:

Ok now for a few minor real suggestions:
* Instead of "archive" on RTD maybe "pre2.0"? I'm thinking it'll be confusing for there to be an arbitrary set of versions in the archive vs RTD, whereas "pre20" makes it clear where the archive ends and RTD begins.
* Instead of "archive" on the github branch, perhaps "docs_archive" or similar?
* Why even bother with the "archive" branch of the astropy repo at all instead of just having a totally independent docs repo and point to that? Or is that an RTD restriction?

**Comment by astrofrog** [comment]
> Instead of "archive" on RTD maybe "pre2.0"? I'm thinking it'll be confusing for there to be an arbitrary set of versions in the archive vs RTD, whereas "pre20" makes it clear where the archive ends and RTD begins.

I don't have strong opinions on the name, though note that this will include some tagged 2.0.x releases (but not the 2.0.x branch which is fine as we are still updating it) so ``pre2.0`` isn't quite right. Note that we can always choose to add more tagged releases in future if we run into other issues that need to be fixed in a certain way - this is why I though just ``archive`` would make sense - it ill be clear in the dropdown menu on RTD which versions are available, and people would presumably only go to archive if they couldn't find what they needed?

> Instead of "archive" on the github branch, perhaps "docs_archive" or similar?

👍 

> Why even bother with the "archive" branch of the astropy repo at all instead of just having a totally independent docs repo and point to that? Or is that an RTD restriction?

RTD won't allow us to build from two repos to astropy.readthedocs.org

**Comment by eteq** [comment]
Basically, all sounds good then. I have one bikeshedding item to continue below... But that shouldn't stop #8060.

`archive` vs `pre20` - good point re: the 2.0.x tags, I forgot about that.  If it's definitely only going to be visible in RTD, what about `older`?  Then the RTD dropdown would show something like "latest, stable, vx.y.z,..., older", which is perhaps a bit clearer that it's just something like "the versions that are older than those shown here"?

**Comment by astrofrog** [comment]
Just for info, I've now populated the ``docs-archive`` branch (with #8060 and a few subsequent tweaks) and the docs archive is online at http://docs.astropy.org/en/docs-archive/ - no forwarding set up yet though.

**Comment by bsipocz** [comment]
One issue (that I'm not sure how easy to hack around) is that the links to the newer versions are broken. See e.g. the link in the big red note at the top of this page: http://docs.astropy.org/en/docs-archive/v2.0.7/index.html

**Comment by bsipocz** [comment]
(Otherwise 🎉 🍾 for making this happen :) )

**Comment by astrofrog** [comment]
Another issue is that searching is broken in the archive - to some extent that's probably ok because otherwise some pages will appear 40 times in the results! But maybe I should find a way to hide the search box?

**Comment by astrofrog** [comment]
Note to self: I need to check what files could have been missed by wget-ing the old docs by doing it for a newer version and comparing it to a local build.

**Comment by astrofrog** [comment]
@eteq:

> archive vs pre20 - good point re: the 2.0.x tags, I forgot about that. If it's definitely only going to be visible in RTD, what about older? Then the RTD dropdown would show something like "latest, stable, vx.y.z,..., older", which is perhaps a bit clearer that it's just something like "the versions that are older than those shown here"?

Unfortunately the RTD name has to match the git branch name, so we need a name that is clear in both cases. So what about 'older-docs-archive'?

**Comment by astrofrog** [comment]
@bsipocz - I think I fixed the warning in https://github.com/astropy/astropy/commit/01a3dcec64c0f3dfc150511b6a978ae3c95a4b48 - it should now correctly link to docs.astropy.org/en/stable, e.g.:

http://docs.astropy.org/en/docs-archive/v0.2.1/index.html

Note that you may have to force refresh as this requires changes in the CSS.

**Comment by astrofrog** [comment]
I've now included the following files in the documentation archive:

```
.buildinfo
objects.inv
searchindex.js
```

which means that if anyone is linking to an old version for intersphinx, it will still work, and also it looks like the searching works now! (within each version - the search at the top-level page just searches the top-level page, which I think is best this way)

**Comment by astrofrog** [comment]
So at this point, I think we just need to agree on what the name of the branch should be (I suggest ``older-docs-archive``) and then we can set up the redirects (if we agree on this approach)

**Comment by astrofrog** [comment]
Branch created: https://github.com/astropy/astropy/tree/older-docs-archive

**Comment by astrofrog** [comment]
And the RTD build: http://docs.astropy.org/en/older-docs-archive/

**Comment by bsipocz** [comment]
@astrofrog - Do your last two comments mean that we can close this issue?

**Comment by astrofrog** [comment]
@bsipocz - no, I still have to set up the redirects, but I didn't want to do that until I got explicit approval that we can move ahead with this. This is the point where things aren't reversible, because I'm going to have to wipe the builds for the existing tags on RTD for the redirects to work.

So just to be explicit, @eteq and @bsipocz - shall I go ahead with this?

**Comment by bsipocz** [comment]
I'm 👍 on this.

**Comment by eteq** [comment]
I'm :+1: on this too. One thought though: maybe we should grab a backup if the site just in case before you wipe? I.e. just a recursive `wget` or similar

**Comment by astrofrog** [comment]
Ok, will do - that's actually how I made the existing archive, but I'll do it again for good measure

**Comment by astrofrog** [comment]
I've set up the redirects for all versions up to v1.0.13. I'll take a break and see if that works, before proceeding with some of the more recent versions.

**Comment by astrofrog** [comment]
The v0.2.1 results are gone! Now there are 1.2 results ;) I've now added the remaining redirects, so I'm going to close this issue since it's implemented and seems to be working.
