### ISSUE TITLE
astropy.io.fits issues incorrect warning messages

### ISSUE THREAD

**Issue by RAShaw-sci** [astropy/astropy#7986]
When reading a FITS file with one BINTABLE extension, astropy emits warning messages that are incorrect, while fitsverify shows no warnings or errors (see attached). I suspect that astropy.io.fits does not support BINTABLES containing spectra, with flux, wavelength, etc. stored as cell arrays, where the WCS is stored in extension header keywords. If that is so, the warning messages (the keywords are invalid or follow an unrecognized or non-standard convention) are incorrect. 

[fitsheader_eta-uma.txt](https://github.com/astropy/astropy/files/2520471/fitsheader_eta-uma.txt)

[fitsverify_eta-uma.txt](https://github.com/astropy/astropy/files/2520470/fitsverify_eta-uma.txt)

**Comment by saimn** [comment]
I think the warning is actually correct, and is not because of these keywords which are read correctly, but because of the extra space before the = delimiter (if I believe the header shown by fitsverify).

```
  63 | TFORM4  = '70000I  '           / Data type for col 4
  64 | TTYPE4  = 'GRPOS   '           / Name for col 4
  65 | TUNIT4  = ''                   / Units for col 4
  66 | 
  67 |                                / Dispersion relation
  68 | 1CTYP2   = 'WAVE'              / Type of world coordinate, axis 1
  69 | 1CRPX2   =                 1.0 / Reference pixel, axis 1
  70 | 1CRVL2   =             950.002 / World coordinate at reference pixel, axis 1
  71 | 1CDLT2   =               0.002 / Change in world coord per pixel, axis 1
  72 | 1CUNI2   = 'Angstrom'          / World coordinates unit, axis 1
  73 | 1SPEC2   = 'HELIOCEN'          / Spectral reference system
  74 | END     
```

**Comment by saimn** [comment]
I'm closing since I think that the reason for the warnings was identified, please reopen if I'm wrong here.
