### ISSUE TITLE
Cosmologies used in equivalencies

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8002]
The thermodynamic temperature equivalency appears to default to the Planck 2015 cosmology value:

```python
    if T_cmb is None:
        from ..cosmology import Planck15
        T_cmb = Planck15.Tcmb0
```

whereas in the ``with_H0`` equivalency added in https://github.com/astropy/astropy/pull/7970, the default cosmology is used:

```python
    if H0 is None:
        from .. import cosmology
        H0 = cosmology.default_cosmology.get().H0
```

and this is currently WMAP9. This seems inconsistent, so can we try and make things more consistent for the 3.1 release? (I see this as bug-like, so I think it can be addressed after feature freeze).

Note that this is related to https://github.com/astropy/astropy/issues/8003 - if we change the default cosmology to Planck 2015, then we can change the ``thermodynamic_temperature`` equivalency to use the default cosmology without changing results (for now).

**Comment by eteq** [comment]
Hmm. I agree that they should be consistent, and I think it's much more consistent to change `thermodynamic_temperature` to use the default cosmology.

That said, I have some misgivings about #8003 - will put thoughts there.  But I created #8005 to switch `thermodynamic_temperature` over.
