### ISSUE TITLE
Add the Planck18 (full mission) cosmological parameters

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#8006]
It looks like no one got around to adding the 2018 Planck mission final results to `cosmology`.  So those should probably be added!

(Ideally for 3.1, although that would require CoCo approval since it's post feature-freeze)

**Comment by aconley** [comment]
I was waiting for them to be accepted, which as far as I can tell they aren't yet.  But they should definitely be added.

**Comment by eteq** [comment]
Ah, makes sense @aconley. Given the slightly awkward timing with the astropy release, do you think we should wait on this for v3.2 then, or put what's in the arXiv papers in now and live dangerously in case something changes in the accepted paper?

**Comment by aconley** [comment]
I would feel comfortable adding it as an option, but I would probably hold
off on making it the default.

Can you imagine what reviewing one of these papers must be like?

**Comment by aconley** [comment]
@eteq - Still want to try for 3.1?

**Comment by astrofrog** [comment]
I feel like it'd be better to just wait for 3.2 - otherwise people will definitely start using it without reading the docs and realize the values aren't final and might change.

**Comment by bsipocz** [comment]
@eteq @aconley - do you know whether the paper is accepted yet? If not I suggest to move the issue to the next milestone (with the note that we may need to change it become default in the next release, it being an LTS one).

**Comment by aconley** [comment]
Doesn't look like it, unfortunately.  So, yes, we should probably move
milestones.

**Comment by pllim** [comment]
So I guess paper still in limbo? Moving milestone again.

**Comment by aconley** [comment]
Yup, as are a bunch of other Planck 2018 results.
