### ISSUE TITLE
Make posterior not a "constraint"

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#8012]
#7558 added `prior` and `posterior` as "constraints" for model parameters.  While that's an expedient way to allow for experimentation with this approach, it's not quite right because, formally, a posterior is not so much a "constraint" as much as a "result" for a parameter.

Hopefully #7945 will clear this up for 3.2 by making it so that constraints don't need special status.  But if it does not, we should consider either re-wording "constraints" to something more like "parameter attribute thingies" or similar.

(Milestoning 3.2 because I think this is a priority to make a decision on this by then, even if it's just a decision to leave it alone.)

**Comment by bsipocz** [comment]
I've also added this to the project board to trigger decision a bit before the next feature freeze ;)

**Comment by nden** [comment]
Moving this to 4.0 with the refactored modeling.

**Comment by nden** [comment]
Fixed by #8769. `prior` and `posterior` were removed from `Model.constraints` and can be added as parameter attributes now.
