### ISSUE TITLE
Cannot run doctests on a single rst file with --test-path option

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#8030]
I used to be able to run the doctests in a single `rst` file using the test runner `-t` (`--test-path`) option, e.g.:

`python setup.py test -t docs/overview.rst`

Unexpectedly, this command now runs *all* of the doctests.  The `-t` option still works as expected for a single python module.

Also, the `-t` option states that it "May also be an absolute path".  When I used an absolute path to an `rst` file, I got "ERROR: not found (no name '`<fullpath>`' in any of [])".  When I used an absolute path to a `py` file, I got two `KeyError`s from `pytest`.

**Comment by pllim** [comment]
Should this be moved to [pytest-doctestplus](https://github.com/astropy/pytest-doctestplus)? cc @drdavella

**Comment by drdavella** [comment]
Recognizing that we've had this discussion elsewhere, and at the risk of being a :trollface:, what are the chances that we could deprecate the test runner in favor of using `pytest` directly?

**Comment by bsipocz** [comment]
> Chances are 100% if you open a PR and tests pass.

and the tests for downstream packages using the astropy test runner ;)

**Comment by eteq** [comment]
I can confirm this bug.  I can also confirm that I am a hipster, because I noticed this bug several days before @larrybradley but didn't report it.  So I was into this bug before it was cool.

**Comment by drdavella** [comment]
To make sure @larrybradley retains primacy in this vital matter, I need to admit that he told me about it last week and I forgot to pursue it then. Sorry to steal your hipster cred, @eteq.

**Comment by bsipocz** [comment]
Well, you've found it and didn't do anything about it, is well, not cool in any sense ;)

**Comment by pllim** [comment]
Don't everyone trying to take the blame all at once. There is a lot of `git blame` to go around. :trollface:

**Comment by embray** [comment]
I actually ran into this problem, ironically, using pytest directly, and when I searched for it this was the first result.  It actually appears to be a problem with doctest-plus, because when I disabled doctest-plus the problem went away, so I will open an issue over there (doctest-plus used to be part of the main astropy package, and probably still was when this issue was opened).

**Comment by embray** [comment]
Nevermind, rookie shell mistake.  I ran `--doctest-glob=*.rst` instead of `--doctest-glob='*.rst'`.
