### ISSUE TITLE
Test egg install

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy#8050]
In relation to https://github.com/astropy/astropy/issues/8032, as a consequence of #7293, it is evident that the test suite does not include coverage of egg builds and installs. This should probably be added.

**Comment by jamienoss** [comment]
The test should ideally be across all platforms.

**Comment by eerovaher** [comment]
Egg is a deprecated format and [it is not even possible to upload an egg to PyPI anymore](https://blog.pypi.org/posts/2023-06-26-deprecate-egg-uploads/).
