### ISSUE TITLE
TST: Pinning max numpy version broke numpy-dev build

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8051]
Relevant log: https://travis-ci.org/astropy/astropy/jobs/448451307 (the build right before the merge of #8041 was business as usual; I checked)

So, pinning it in `setup.py` breaks our numpy-dev CI, but unpinning it breaks our RTD build. @mhvk , when is Numpy 1.15.4 coming out? :grimacing: 

For the release, I am guessing successful RTD build is more important. :woman_shrugging: 

Also see #7943

**Comment by bsipocz** [comment]
Nice catch @pllim that `!=` is a workaround for this one, too.
