### ISSUE TITLE
Fix consistency between install docs and package requirements list

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8058]
I'm sure we had issues about this in the past, but the docs and the now cleaned up `pip-requirements` files got out of sync again as it got discovered in https://github.com/astropy/astropy/pull/8048

There still seems to be a bit of discrepancies between the install docs and the requirement files, we'll need to fix these before the release:

In `install.rst` but not in any of the pip-requirements files:

 -   `xmllint`
 -   `soretedcontainers`
 -   `setuptools`
 -   `objgraph`

Listed in one of the pip-requirements but not in install.rst.

  -  `coverage`
  -  `skyfield`
  -  `pytest-xdist`
  -  `pytest-mpl`
  -  `ipython`
  -  `pillow`

Some of these are clearly there for testing purposes, so we probably don't need to list them, but then we don't need to list e.g. setuptools either.

**Comment by pllim** [comment]
xref #8042 and #8043

**Comment by bsipocz** [comment]
Thank you @pllim for the cross references. Those two PRs indeed fixed most of the inconsistencies from here.

**Comment by pllim** [comment]
* `xmllint` is a command line tool, so not in `pip` requirements.
* `sortedcontainers` were included in #8042 

To be addressed in #8156:

* `setuptools`
* `objgraph`
* `pytest-astropy`
* `coverage`
* `skyfield`
* `pytest-xdist`
* `pytest-mpl`
* `ipython`
* `pillow`
