### ISSUE TITLE
MNT: Remove numpy !=1.15.3 pin when 1.15.4 is out

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8063]
This is a follow up of https://github.com/astropy/astropy/pull/8043#discussion_r230244725

When Numpy 1.15.4 is out and available in default `conda` channels for the main OSes that we support, we have to remove the pin in:

* `setup.py`
* `pip-requirements`
* Installation doc (`install.rst`)

**Comment by mhvk** [comment]
1.15.4 has been released: https://mail.python.org/pipermail/numpy-discussion/2018-November/078913.html

**Comment by pllim** [comment]
Thanks, @mhvk ! We should wait a few days for it to get propagated across `conda`-land.

**Comment by pllim** [comment]
Note: Checked this morning and still didn't see 1.15.4 in `conda`.

**Comment by Cadair** [comment]
if you pinned `!=` why do you have to remove it? Surely it will just install 1.15.4 if there?

**Comment by pllim** [comment]
Re: why -- The argument was that we never pin bugfix like this, so no reason to start now. (Link to original comment for this request in my original post.)
