### ISSUE TITLE
Let deprecated decorater take user-defined deprecation warning

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8078]
As requested by @bsipocz . Currently, the `deprecated` decorator only emits `AstropyDeprecationWarning` or `AstropyPendingDeprecationWarning`. It would be nice if these warnings can be overridden by an user option.

https://github.com/astropy/astropy/blob/0725a5cbd756e6301d0aa79cc049d60882b8c57d/astropy/utils/decorators.py#L112-L116

**Comment by saimn** [comment]
There is an interesting project that I wanted to mention earlier, and it seems a good occasion to do so:
https://docs.openstack.org/debtcollector/latest/user/usage.html
https://github.com/openstack/debtcollector
It handles all the kind of deprecations that we support in `astropy.utils.decorators` and more, like renaming a class, or specifying the removal version, and it is possible to specify the warning category:
https://docs.openstack.org/debtcollector/latest/reference/index.html#debtcollector.deprecate
It seems to be an officially supported openstack package.

**Comment by pllim** [comment]
It has Apache license. Is that a deal breaker?

**Comment by saimn** [comment]
I think it is ok, it is not a viral license (https://github.com/openstack/debtcollector/blob/master/LICENSE).

**Comment by pllim** [comment]
Something for the @astropy/coordinators to think about? 😸

**Comment by Cadair** [comment]
Apache is compatible with BSD 3-Clause, there should be no issues.

**Comment by bsipocz** [comment]
I'm happy with either of the solutions (least like adding a new dependency to my package, unless it's really a standard used by most other packages, which is not yet the case, both numpy and scikit-learn and astropy ships their own deprecation decorator/solution).

But is there is an "official" guideline that multiple affiliated packages would follow I'm more than happy to go with it being it any of the solutions suggested above (e.g. so I could avoid end up in a situation to maintain multiple, equally OK approaches for the same problem in separate packages).

**Comment by bsipocz** [comment]
This has been done in #8178
