### ISSUE TITLE
Does convolve_fft(quiet) do anything?

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy#8087]
The only refs are that in the def sig and the docstring.

https://github.com/astropy/astropy/blob/master/astropy/convolution/convolve.py#L386
https://github.com/astropy/astropy/blob/master/astropy/convolution/convolve.py#L497

**Comment by pllim** [comment]
Not that I can see but maybe @keflavich can confirm.

**Comment by keflavich** [comment]
Looks like they're leftovers from a previous change.

However, you could add them as an option in
https://github.com/astropy/astropy/pull/8088
i.e., quiet/silence/unverbose those warnings optionally

**Comment by keflavich** [comment]
This has been resolved - the `quiet` keyword no longer exists.  Not sure when it was solved, but it was a while back.
