### ISSUE TITLE
Cython FutureWarning language_level not set

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8102]
When I installed Astropy 3.2.dev23273 on Windows 10, Python 3.7.1 [MSC v.19124)], and Cython 0.29, I see the following warning. This is just one of them. This seems to affect multiple sub-packages. 
```
C:\...\Cython\Compiler\Main.py:367:FutureWarning:
    Cython directive 'language_level' not set, using 2 for now (Py2).
    This will change in a later release!
    File: C:\...\astropy\astropy\table\_np_utils.pyx
```

Perhaps this is related to cython/cython#2565. Do we need to do anything on our side?

**Comment by saimn** [comment]
This is a new warning from Cython 0.29: https://cython.readthedocs.io/en/latest/src/changes.html#id7
I guess we could safely use `language_level=3` (https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html).

**Comment by bsipocz** [comment]
PR to include this in 3.1?

**Comment by pllim** [comment]
I'm on it.
