### ISSUE TITLE
Deprecation warning in compilation re: PyUnicode_GetSize

### ISSUE THREAD

**Issue by anntzer** [astropy/astropy#8113]
Probably doesn't matter too much, but compiling astropy (on Py3.7) gets (in particular) the following deprecation warning:
```
astropy/io/votable/src/tablewriter.c: In function ‘write_tabledata’:
astropy/io/votable/src/tablewriter.c:274:17: warning: ‘PyUnicode_GetSize’ is deprecated [-Wdeprecated-declarations]
                 str_len = PyUnicode_GetSize(str_val);
                 ^~~~~~~
In file included from ../../../miniconda3/include/python3.7m/Python.h:80,
                 from astropy/io/votable/src/tablewriter.c:12:
../../../miniconda3/include/python3.7m/unicodeobject.h:793:24: note: declared here
 PyAPI_FUNC(Py_ssize_t) PyUnicode_GetSize(
                        ^~~~~~~~~~~~~~~~~
```
(tablewriter.c is a handwritten C-extension, and PyUnicode_GetSize (https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_GetSize) is deprecated since Py3.3 (looking at the sources).

**Comment by pllim** [comment]
There are so many C compilation warnings across the board that I don't even know where to start. But this one should probably be addressed. Do you feel like submitting a PR? 😄

**Comment by anntzer** [comment]
If I don't have anything better to do, some day :p

**Comment by saimn** [comment]
Good catch. And there is another occurrence in `astropy/utils/xml/src/iterparse.c`, 
```sh
❯ rg PyUnicode_GetSize
astropy/io/votable/src/tablewriter.c
274:                str_len = PyUnicode_GetSize(str_val);

astropy/utils/xml/src/iterparse.c
1187:        input_len = PyUnicode_GetSize(input_coerce);
```
