### ISSUE TITLE
WCS should accept / return coordinates objects

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#812]
It might be nice to build in support so that conversions _from_ world coordinates accept any Astropy coordinates object and conversions _to_ world coordinates return a coordinates object as well (once `Angle` and other coordinate object accept arrays) . For example:

```
>>> worldcoords = coord.ICRSCoordinates([[151.1241, 11.134], [12.4123, -41.1231]], unit=(u.deg, u.deg))
>>> wcs.wcs_world2pix(worldcoords)
...
```

I also hate the function names in `wcs` but I'm not sure there's anything we can do about that..

**Comment by bsipocz** [comment]
Isn't this solved now? 

cc: @adrn @astrofrog

**Comment by adrn** [comment]
I haven't been following...

**Comment by bsipocz** [comment]
Isn't this solved now by #2885? 

cc: @adrn @astrofrog

**Comment by bsipocz** [comment]
I very much still feel that `wcs.utils.skycoord_to_pixel(coord, wcs)` and `wcs.utils.pixel_to_skycoord(x, y, wcs)` do implement this feature, so suggest to close the issue.

**Comment by astrofrog** [comment]
Yes but more importantly it's now implemented in the APE 14 WCS API!

http://docs.astropy.org/en/stable/wcs/wcsapi.html
