### ISSUE TITLE
Error in astropy.test()

### ISSUE THREAD

**Issue by bijiaqing** [astropy/astropy#8124]
Hi,

I ran the test function and got things below. How can I help with my astropy? Thanks!

```
================================================================== ERRORS ==================================================================
______________________________ ERROR collecting .local/lib/python2.7/site-packages/astropy/tests/__init__.py _______________________________
.local/lib/python2.7/site-packages/_pytest/runner.py:212: in __init__
    self.result = func()
.local/lib/python2.7/site-packages/_pytest/runner.py:272: in <lambda>
    call = CallInfo(lambda: list(collector.collect()), "collect")
.local/lib/python2.7/site-packages/_pytest/python.py:443: in collect
    self.session._fixturemanager.parsefactories(self)
.local/lib/python2.7/site-packages/_pytest/fixtures.py:1301: in parsefactories
    holderobj = node_or_obj.obj
.local/lib/python2.7/site-packages/_pytest/python.py:248: in fget
    self._obj = obj = self._getobj()
.local/lib/python2.7/site-packages/_pytest/python.py:440: in _getobj
    return self._importtestmodule()
.local/lib/python2.7/site-packages/_pytest/python.py:493: in _importtestmodule
    self.config.pluginmanager.consider_module(mod)
.local/lib/python2.7/site-packages/_pytest/config/__init__.py:498: in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
.local/lib/python2.7/site-packages/_pytest/config/__init__.py:501: in _import_plugin_specs
    plugins = _get_plugin_specs_as_list(spec)
.local/lib/python2.7/site-packages/_pytest/config/__init__.py:554: in _get_plugin_specs_as_list
    "list/tuple of strings for plugin names. Given: %r" % specs
E   UsageError: Plugin specs must be a ','-separated string or a list/tuple of strings for plugin names. Given: <module 'astropy.tests.pytest_plugins' from '/home/jiaqing/.local/lib/python2.7/site-packages/astropy/tests/pytest_plugins.pyc'>
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================== 11 skipped, 1 error in 21.87 seconds ===================================================
```

**Comment by bijiaqing** [comment]
And I also want to know how can I use astropy in Python3. Because currently I can only import astropy in my Python2.7 code, it will show ModuleNotFoundError if I do the same thing in Python3.7.\

I am totally new to python&linux, so I really need detailed steps on this. Thank you very much!

**Comment by pllim** [comment]
Please see http://www.astropy.org/ for installation instructions. There is nothing much we can do if your Python installation is giving you trouble. I would suggest trying Miniconda (https://conda.io/miniconda.html) for clean(er) and separate Python environments. Hope this helps and thank you for your interest!

**Comment by kakirastern** [comment]
Hi @pllim, I am having some problems with the same test as well. Upon running `python setup.py test` in the "astropy" directory on my own machine, I obtain the following output results from the test:

============================= test session starts ==============================
platform darwin -- Python 3.7.1, pytest-4.0.2, py-1.7.0, pluggy-0.8.0

Running tests with Astropy version 3.2.dev23780.
Running tests in astropy docs.

Date: 2019-01-28T03:42:32

Platform: Darwin-18.2.0-x86_64-i386-64bit

Executable: /usr/local/opt/python/bin/python3.7

Full Python Version: 
3.7.1 (default, Nov 28 2018, 11:51:47) 
[Clang 10.0.0 (clang-1000.11.45.5)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.15.4
Scipy: 1.2.0
Matplotlib: 3.0.2
h5py: 2.8.0
Pandas: 0.23.4
Cython: 0.29.3
astropy_helpers: 1.3.1
Using Astropy options: remote_data: none.

rootdir: /private/var/folders/fd/c__kfpsj2wsc9bm3dphp3gvw0000gn/T/astropy-test-b7_quing/lib/python3.7/site-packages, inifile: setup.cfg
plugins: openfiles-0.3.2, arraydiff-0.3, doctestplus-0.2.0, remotedata-0.3.1
collected 12336 items / 3 errors / 28 skipped                                  

==================================== ERRORS ====================================
_______________ ERROR collecting astropy/vo/client/conesearch.py _______________
.eggs/pytest_doctestplus-0.2.0-py3.7.egg/pytest_doctestplus/plugin.py:107: in collect
    module = self.fspath.pyimport()
/usr/local/lib/python3.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/private/var/folders/fd/c__kfpsj2wsc9bm3dphp3gvw0000gn/T/astropy-test-b7_quing/lib/python3.7/site-packages/astropy/vo/client/conesearch.py", line 14
E       from .async import AsyncBase
E                 ^
E   SyntaxError: invalid syntax
_________ ERROR collecting astropy/vo/client/tests/test_conesearch.py __________
astropy/vo/client/tests/test_conesearch.py:15: in <module>
    from .. import conesearch, vos_catalog
E     File "/private/var/folders/fd/c__kfpsj2wsc9bm3dphp3gvw0000gn/T/astropy-test-b7_quing/lib/python3.7/site-packages/astropy/vo/client/conesearch.py", line 14
E       from .async import AsyncBase
E                 ^
E   SyntaxError: invalid syntax
_________ ERROR collecting astropy/vo/client/tests/test_conesearch.py __________
/usr/local/lib/python3.7/site-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python3.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:668: in _load_unlocked
    ???
<frozen importlib._bootstrap>:638: in _load_backward_compatible
    ???
/usr/local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:295: in load_module
    six.exec_(co, mod.__dict__)
astropy/vo/client/tests/test_conesearch.py:15: in <module>
    from .. import conesearch, vos_catalog
E     File "/private/var/folders/fd/c__kfpsj2wsc9bm3dphp3gvw0000gn/T/astropy-test-b7_quing/lib/python3.7/site-packages/astropy/vo/client/conesearch.py", line 14
E       from .async import AsyncBase
E                 ^
E   SyntaxError: invalid syntax
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
===================== 28 skipped, 3 error in 42.99 seconds =====================

So these 3 errors are supposed to be syntax errors. Is it a similar problem, or is it something separate from @bijiaqing's issue?

**Comment by bsipocz** [comment]
@kakirastern - While your version number looks right, somehow your dev environment has files that had been removed a while ago.  Does 'astropy/vo' come up as untracked files?

To clean your repo checkout you can use `git clean -dfx`. Be careful though and save the extra files you want to keep somewhere else as it removes all untracked files.

**Comment by kakirastern** [comment]
Thanks, @bsipocz. I have run `git clean -dfx` and it did indeed get rid of all the errors. So now I have only `1 failed, 11748 passed, 474 skipped, 65 xfailed in 264.12 seconds` instead, with no errors, and the following partial output at the top:

```
============================= test session starts ==============================
platform darwin -- Python 3.7.1, pytest-4.0.2, py-1.7.0, pluggy-0.8.0

Running tests with Astropy version 3.2.dev23780.
Running tests in astropy docs.

Date: 2019-01-28T04:39:39

Platform: Darwin-18.2.0-x86_64-i386-64bit

Executable: /usr/local/opt/python/bin/python3.7

Full Python Version: 
3.7.1 (default, Nov 28 2018, 11:51:47) 
[Clang 10.0.0 (clang-1000.11.45.5)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.15.4
Scipy: 1.2.0
Matplotlib: 3.0.2
h5py: 2.8.0
Pandas: 0.23.4
Cython: 0.29.3
astropy_helpers: 1.3.1
Using Astropy options: remote_data: none.

rootdir: /private/var/folders/fd/c__kfpsj2wsc9bm3dphp3gvw0000gn/T/astropy-test-h7o2972q/lib/python3.7/site-packages, inifile: setup.cfg
plugins: openfiles-0.3.2, arraydiff-0.3, doctestplus-0.2.0, remotedata-0.3.1
collected 12260 items / 28 skipped...                                           
```

So the test was not able to be brought to fruition (100%) due to "astropy/vo" coming up as "untracked files" indeed.

**Comment by pllim** [comment]
When things look messed up like this, I usually recommend installing `miniconda`, create a fresh new environment, and test your Astropy installation over there.

**Comment by kakirastern** [comment]
@pllim Thanks for the feedback! I have been using `anaconda` though, so maybe it is worth a try to use `miniconda` instead? Let me look into it.

**Comment by pllim** [comment]
@kakirastern , ah, if you are already using Anaconda, then you don't have to install miniconda, but instead create new env using `conda` command. Your executable `/usr/local/opt/python/bin/python3.7` does not indicate that you are using it though.

**Comment by MSeifert04** [comment]
You can also create environments with the conda from anaconda. No need to install miniconda and anaconda.

**Comment by kakirastern** [comment]
Thanks, noted. So now let me find out why the executable is the wrong path... Could be something about the ".bash_profile" file on my Mac. Will get back soon.

**Comment by kakirastern** [comment]
Think I have fixed the problem, as the "test session starts" output is now as follows:

```
============================= test session starts ==============================
platform darwin -- Python 3.7.1, pytest-4.1.1, py-1.7.0, pluggy-0.8.1

Running tests with Astropy version 3.2.dev23780.
Running tests in astropy docs.

Date: 2019-01-29T02:04:19

Platform: Darwin-18.2.0-x86_64-i386-64bit

Executable: /anaconda3/envs/astropy-dev/bin/python3

Full Python Version: 
3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 10:30:07) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.15.4
Scipy: 1.2.0
Matplotlib: 3.0.2
h5py: 2.9.0
Pandas: 0.24.0
Cython: 0.29.3
astropy_helpers: 1.3.1
Using Astropy options: remote_data: none.

rootdir: /private/var/folders/fd/c__kfpsj2wsc9bm3dphp3gvw0000gn/T/astropy-test-gvfoww25/lib/python3.7/site-packages, inifile: setup.cfg
plugins: openfiles-0.3.2, arraydiff-0.3, doctestplus-0.2.0, remotedata-0.3.1
collected 12260 items / 28 skipped                                             
```

**Comment by pllim** [comment]
@kakirastern , can you please clarify a bit more -- Are you still seeing the same error with a fresh conda environment?

**Comment by kakirastern** [comment]
Was able to get rid of the remaining failure on my machine by applying the tip found at [https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python](https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python), which is specific to macOS... So everything is okay now. And now the final output of `python3 setup.py test` is now as follows: 

`=========== 12060 passed, 302 skipped, 67 xfailed in 337.52 seconds ============`

**Comment by bsipocz** [comment]
@kakirastern - Glad to hear. 

I'm going ahead of closing this issue as there isn't much todo items here.
