### ISSUE TITLE
ImageNormalize does not update the minor ticks of the colorbar

### ISSUE THREAD

**Issue by fpavogt** [astropy/astropy#8126]
Hello astropy-gurus,

I'm ramping up my use of `WCSAxes` in an attempt to distance myself from aplpy for a specific set of plots for which I need fine control. In doing so, I'm struggling getting the minor ticks on the colorbar right, when I use `ImageNormalize()`. The major ticks get updated and set properly, but the minor ticks seem unaffected.

Relevant or not, I note that I set the minor ticks "on" in my plots via a dedicated matplotlib style file and `xtick.minor.visible: True`, etc ...

![minor-ticks](https://user-images.githubusercontent.com/13974615/48493421-8a281600-e80a-11e8-953e-1a47a6f165a2.png)

Running astropy 3.0.4, matplotlib 3.0.0, python 3.6. I have not found other reports of this behaviour (yet?). 

MWE:
```
from astropy.wcs import WCS
import astropy.visualization as astrovis
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec 

plt.close(1)
fig = plt.figure(1, figsize = (bifus_m.fig_width, fig_height))
   
# Set the scene with gridspec
gs = gridspec.GridSpec(2,1, height_ratios=[0.2, 1],
                                       width_ratios = [1], left =0.1, right = 0.95, bottom = 0.1, top = 0.9, 
                                       wspace = 0.02, hspace = 0.02)
# set the axes  
ax1 = plt.subplot(gs[1,0], projection=WCS(header))
# What is the normalization ?
norm = astrovis.ImageNormalize(data, 
                                  interval = astrovis.PercentileInterval(pmin,pmax),
                                  stretch = astrovis.AsinhStretch())
   
# Plot the image
im = ax1.imshow(data, origin = 'lower', interpolation = 'nearest', cmap = mycmap,
                            norm = norm)
   
# Deal with the colorbar
ax0 = plt.subplot(gs[0,0])

cb = plt.colorbar(cax = ax0, mappable=im, orientation='horizontal', ticklocation = 'top')
cb.set_label(cblabel, labelpad = 10)
ax0.tick_params(axis='x', which='major', pad = 5) # Bring the tick labels clsoer

```

**Comment by astrofrog** [comment]
Thanks for the bug report! Investigating...

**Comment by astrofrog** [comment]
I think this is a Matplotlib bug - I've opened https://github.com/matplotlib/matplotlib/issues/12808

**Comment by bsipocz** [comment]
It seems that the upstream issue has been solved (the issue was originally closed a duplicate, but the examples in there seems to be working now). 
Without the data referenced above I can't reproduce the example above, so feel free to reopen if it still not working as expected.
