### ISSUE TITLE
Determine the root cause of the is_equivalent_frame change and document it

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#8138]
astropy/astroplan#382 is showing a single test failure that appeared in astropy v3.1rc1.  This is odd because it seems to be in a place that wasn't obviously modified in 3.1.  But it could be some subtle thing related to some of the preformance improvements.

At any rate, whether it's a bug that needs fixing or a subtle behavior change, in either case it should be either fixed or documented in the changelog/what's new.

**Comment by eteq** [comment]
Turns out this may be a "real" failure: looking more deeply at astropy/astroplan#382, it turns out the real problem lies in `is_equivalent_frame` returning False in a case where it looks like it should return True.  Trying to work up a simple test case of this...

cc @adrn

**Comment by bsipocz** [comment]
@eteq - I suppose this has been fixed now, can you confirm and close or remilestone?

**Comment by eteq** [comment]
Yes, fixed by #8218 (apparently my wording in the commit message was too amgiuous for github...)
