### ISSUE TITLE
Find root cause of representation deprecation warnings all over coordinates

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#8139]
In the 3.1rc1, we are now getting deprecation warnings almost everywhere in coordinates.  I see it at `SkyCoord` creation, frame class creation, and `repr`, which are pretty fundamental.

This leads me to suspect we missed converting `representation` to `representation_type` somewhere deep in the machinery (like a getattr or something).  Just need to hunt it down.

Really, this is my bad from #8119... Worse case scenario we can just revert that PR before the final 3.1 release and delay the deprecation of the keyword for another version.

cc @adrn

**Comment by astrofrog** [comment]
The easiest way to debug this would be to just turn deprecation warnings into errors :)

**Comment by adrn** [comment]
Yea there's a bunch of missed `.representation` places, but looks like it's an easy fix. Will have a PR shortly.

**Comment by eteq** [comment]
Turns out it was a lot of root causes.  Or, alternatively, #8140 makes me realize how much of an epic fail I had in #8119 🐑 ...

**Comment by bsipocz** [comment]
Well, this is why we have RC testing 😄
