### ISSUE TITLE
v3.1rc1 - votable failures

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#8142]
Full log in https://gist.github.com/saimn/a823d4223dcd09ffc5fa03627d9b8249

```
astropy/io/votable/tests/vo_test.py::test_validate FAILED                [ 33%]
astropy/io/votable/tests/vo_test.py::test_validate_xmllint_true PASSED   [ 66%]
astropy/io/votable/tests/vo_test.py::test_validate_path_object FAILED    [100%]
```

**Comment by saimn** [comment]
@pllim - yes, on Debian.
```
❯ xmllint --version
xmllint: using libxml version 20904
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ICU ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib Lzma 
```

**Comment by pllim** [comment]
@olebole , is this one of the tests you already disabled in the distro? `votable` has not been touched much since the last release...

**Comment by pllim** [comment]
FWIW mine is
```
xmllint: using libxml version 20908
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid
HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ICU ISO8859X Unicode Regexps
Automata Expr Schemas Schematron Modules Debug Zlib Lzma 
```

I tried digging into the validator code but can't find anything obvious.

**Comment by astrofrog** [comment]
Looks like it's due to ``…`` (single-character) being used for ellipsis. I wonder if that depends on your locale. What are your locale settings?

**Comment by astrofrog** [comment]
So just to clarify, this isn't anything to do with votable fundamentally, just the fact that if the user has set local configuration that is different from the default, the tests may fail. So we somehow need to ensure that during testing, the configuration file is ignored.

**Comment by astrofrog** [comment]
By the way, this may happen only when running tests directly with pytest, I need to check

**Comment by saimn** [comment]
Well guessed @astrofrog, it seems that I did set the `unicode_output` setting in my config file ! 
I tested both directly with pytest and with the setup.py.

**Comment by pllim** [comment]
See #8154
