### ISSUE TITLE
Testing header should show helpers_version of the package rather than astropy

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8147]
E.g `photutils` has the helpers `v3.1rc1` yet the tests header here report `2.0.7` . That is the one in the astropy version (LTS) being tested against.

https://travis-ci.org/astropy/photutils/jobs/456102941

```
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
Running tests with photutils version 0.6.dev194.
Running tests in photutils docs.
Date: 2018-11-16T19:25:39
Platform: Linux-4.14.12-041412-generic-x86_64-with-debian-jessie-sid
Executable: /home/travis/miniconda/envs/test/bin/python
Full Python Version: 
3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]
encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15
Numpy: 1.13.1
Scipy: 1.1.0
Matplotlib: 2.2.2
Cython: 0.29
Astropy: 2.0.9
scikit-image: 0.14.0
scikit-learn: 0.20.0
astropy_helpers: 2.0.7
Using Astropy options: remote_data: none.
```

**Comment by pllim** [comment]
Not sure if it is a bug or feature, the code does explicitly grab helpers version from `version.py` that is in Astropy, not the calling package:

https://github.com/astropy/astropy/blob/392d36b39b96f356140c14dbc78d66a33e7bce75/astropy/tests/plugins/display.py#L99

Maybe a better way forward is not to rely on `display.py` but to insert a template of [pytest_report_header](https://docs.pytest.org/en/latest/example/simple.html#adding-info-to-test-report-header) in package template and allow individual package to customize it however they like. Just a thought.

**Comment by bsipocz** [comment]
I see it as a bug that is there for historic reason of the display originally was written astropy core in mind.

**Comment by bsipocz** [comment]
Actually it would be nice to be able to easily remove listing the helpers, too, but I suspect this can be solved more easily once the original issue here is tackled (e.g. if not testing astropy it should check for the local helpers and only report the version if the helpers is used at all...)
