### ISSUE TITLE
Ignore user config when running tests

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8154]
https://github.com/astropy/astropy/issues/8142#issuecomment-439483781

*So just to clarify, this isn't anything to do with votable fundamentally, just the fact that if the user has set local configuration that is different from the default, the tests may fail. So we somehow need to ensure that during testing, the configuration file is ignored.* -- @astrofrog

**Comment by saimn** [comment]
Thanks for opening the issue @pllim. I edited the title as it is about the user config file, not the locale.
