### ISSUE TITLE
DOC: MatplotlibDeprecationWarning examples.directory is deprecated

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8157]
Saw this when testing `astropy` with `matplotlib` 3.0.2. No time to investigate where it is coming from right now.
```
C:\...\matplotlib\__init__.py:886: MatplotlibDeprecationWarning:
examples.directory is deprecated; in the future, examples will be
found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
```

**Comment by pllim** [comment]
Perhaps related: ioam/holoviews#3058

**Comment by GbengaOdesanmi** [comment]
Am having this same error, can someone please help on how to solve this.
MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))

**Comment by gauravkoradiya** [comment]
same error:
MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))

**Comment by pllim** [comment]
Looks like this is something upstream.

https://github.com/matplotlib/matplotlib/pull/12658#issuecomment-497013309
