### ISSUE TITLE
VOTable binary2 file reads back in with only one row

### ISSUE THREAD

**Issue by stargaser** [astropy/astropy#8162]
I have encountered a case where a VOTableFile that writes out correctly in tabledata format, apparently writes only one row in binary2 format. Furthermore, `validate` reports that the binary2 file is fine. The STILTS `votlint` checker from Starlink finds the 1-row problem.

To reproduce:
```python
from astropy.utils.data import download_file
from astropy.io.votable import parse, validate

tabledata_file = download_file('http://web.ipac.caltech.edu/staff/shupe' +
                               '/firefly_testdata/tabledata-wide.xml',
                               cache=True)

print('validating downloaded file:')
validate(tabledata_file)
votablefile = parse(tabledata_file)
print('tabledata format: shape is ', votablefile.get_first_table().array.shape)

intermediate_name = 'tabledata-wide.xml'
votablefile.to_xml(intermediate_name, tabledata_format='tabledata')
print('validating the table when written as tabledata format:')
validate(intermediate_name)
int_votablefile = parse(intermediate_name)
print('tabledata format: shape is ', int_votablefile.get_first_table().array.shape)

outname = 'binary2-wide.xml'
int_votablefile.to_xml(outname, tabledata_format='binary2')

print('validating binary2 output:')
validate(outname)

vobinary2 = parse(outname)
print('binary2 format: shape is ', vobinary2.get_first_table().array.shape)
```

STILTS `votlint` passes the tabledata versions. For the binary2 file it reports:
```
ERROR (l.4047, c.314415): Stream ended during data read; done 2/4
ERROR (l.4047, c.314415): End of stream while reading 1134821376 elements (probable stream corruption)
ERROR (l.4047, c.314415): Streaming error java.io.EOFException
ERROR (l.4055, c.11): Row count (1) not equal to nrows attribute (49)
``` 

EDIT: Syntax highlighting

**Comment by stargaser** [comment]
I have found a circuitous way to make the binary2 output ultimately work, but it involves making copies of the table and writing it out and reading it back in. See [this LSST issue comment](https://jira.lsstcorp.org/browse/DM-16518?focusedCommentId=179730&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-179730).

**Comment by pllim** [comment]
Hi. Not sure if I understand the problem. I downloaded your http://web.ipac.caltech.edu/staff/shupe/firefly_testdata/tabledata-wide.xml , then I did this:

```python
from astropy.table import Table
t1 = Table.read('tabledata-wide.xml', format='votable')
t1.write('binary2-wide.xml', format='votable', tabledata_format='binary2')
```

Things seem to work:
```
$ volint binary2-wide.xml
Validation report for binary2-wide.xml

astropy.io.votable found no violations.
```

AFAIK, there was never a requirement that `volint` has to report the same stuff as Starlink. At least, within Astropy, things are self-consistent. You mentioned that things don't appear to work as expected after inserting some data but that case was not presented above. Please present your real use case and also the expectations. Thanks!

**Comment by pllim** [comment]
> that is the problem

Can you please provide code snippet with the data to illustrate that? (Just need enough for others to reproduce this problem.) Thank you!

**Comment by stargaser** [comment]
Here is a code snippet to illustrate the problem:
```
from astropy.io.votable import parse
vt1 = parse('http://web.ipac.caltech.edu/staff/shupe/firefly_testdata/tabledata-wide.xml')
vt1.to_xml('binary2-vo-wide.xml', tabledata_format='binary2')
vt2 = parse('binary2-vo-wide.xml')
vt2.get_first_table().to_table()
```
There is only one row in table `vt2` when there are 49 in the original table.

Thank you for the tip about the unified i/o interface. This code works:
```
from astropy.table import Table
t1 = Table.read('http://web.ipac.caltech.edu/staff/shupe/firefly_testdata/tabledata-wide.xml', format='votable')
t1.write('binary2-wide.xml', format='votable', tabledata_format='binary2')
t2 = Table.read('binary2-wide.xml', format='votable')
```

There is something about having the table as an `astropy.table.Table` that makes this work.

**Comment by pllim** [comment]
@stargaser , if the unified I/O works for you, then I propose we close this as "won't fix". I don't see any good reason to use the less user-friendly `votable` API when there is alternative. If you are curious though, the unified I/O layer between `Table` and `votable` is in `astropy/io/votable/connect.py`. Please close the issue if you agree. Thanks!

**Comment by stargaser** [comment]
One more item for the use case. I need to attach some metadata to the table. I have been doing this using the `Info` attribute of the VOTable object.

When I use the unified i/o interface, I don't see these items in `t1.meta`. Should I expect to find them there?

**Comment by stargaser** [comment]
I think #7759 is referring to global `Infos`. In my case, I am using `Infos` attached to the first table. These are read when I use `parse` from `astropy.io.votable` and they are written out when I use `to_xml`. As far as I can tell, they are not read by the unified i/o interface.

The example table http://web.ipac.caltech.edu/staff/shupe/firefly_testdata/tabledata-wide.xml contains the table-specific `Info` items.

**Comment by stargaser** [comment]
I think this issue could be closed, and the part about `Infos` could be noted under #7759 or could be a separate issue. I am not sure which option is better.

**Comment by pllim** [comment]
Indeed metadata is not well supported in the unified I/O interface. I am not sure if I have time to look into this. But I am of the opinion that if we were to spend time fixing this issue up, the effort is better spent on implementing metadata support than figuring out why `votable.parse` etc did not behave the same as unified I/O. If LSST would like to provide resource to implement metadata support, I would be happy to help with the onboarding process!

**Comment by pllim** [comment]
@stargaser , okay. I'll tack on your metadata problem onto #7759. Thank you!
