### ISSUE TITLE
norm's behavior with NaN and masked values

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#8165]
It seems that recently the behavior of astropy's norms (or most the way it interacts with matplotib) changed, and now NaN values and masked values are not displayed with the NaN color (when `clip=True` which is the default) as it used to be. 

For instance with NaNs:
![image](https://user-images.githubusercontent.com/311639/48803610-b237dd80-ed12-11e8-9d5d-2f5f808f5d66.png)

And with masked values:
![image](https://user-images.githubusercontent.com/311639/48803813-499d3080-ed13-11e8-8325-e9e2e3de63af.png)

I don't have this behavior (the middle image) if I test on an old py2 env with Astropy 2.0.7 and matplotlib 2.2.2.
I didn't find a recent change in Astropy that could explain this, so I guess that something changed in matplotlib. But still I wonder why the mask is dropped here (@astrofrog - I think you introduced this) when `clip` is True:
https://github.com/astropy/astropy/blob/f7db70d21b1b9b10124314202a835a4485ebf695/astropy/visualization/mpl_normalize.py#L92-L97

**Comment by saimn** [comment]
Maybe not clear above: removing the `mask = False` line mentioned above fixes the issue, though I don't know if this is the correct fix.

**Comment by Knusper** [comment]
On a slightly related note, I find it quite confusing that the `clip` defaults in `matlplotlib.Normalize` to `False` (which is imho a reasonable default), wheras in astropy's `ImageNormalize` it defaults to `True`.
Moreover, the behavior of `clip` with respect to masked values should be documented.

**Comment by pllim** [comment]
cc @larrybradley and @astrofrog
