### ISSUE TITLE
Tests are not picked up for pytest >=3.7 on LTS

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8177]
For some yet unknown reason the tests are not picked up by the test collection only the rst files from the narrative documentation on the LTS branch when using pytest 3.7+

I think at least understanding, preferable fixing, this is critical for the release.

```
================================================= test session starts ==================================================
platform darwin -- Python 3.7.0, pytest-3.7.4, py-1.6.0, pluggy-0.7.1

Running tests with Astropy version 2.0.10.dev19739.
Running tests in astropy docs.

Date: 2018-11-24T13:44:00

Platform: Darwin-17.7.0-x86_64-i386-64bit

Executable: /usr/local/opt/python/bin/python3.7

Full Python Version: 
3.7.0 (default, Sep 18 2018, 18:47:22) 
[Clang 9.1.0 (clang-902.0.39.2)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.15.4
Scipy: 1.1.0
Matplotlib: 3.0.2
h5py: 2.8.0
Pandas: 0.23.4
Cython: 0.28.5
astropy_helpers: 3.1rc1
Using Astropy options: remote_data: none.

rootdir: /private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/astropy-test-l155hvv3/lib/python3.7/site-packages, inifile: setup.cfg
plugins: cov-2.6.0, arraydiff-0.2
collected 168 items                                                                                                    

docs/changelog.rst .                                                                                             [  0%]
docs/credits.rst .                                                                                               [  1%]
docs/getting_started.rst .                                                                                       [  1%]
docs/importing_astropy.rst .                                                                                     [  2%]
...
...
docs/whatsnew/2.0.rst .                                                                                          [ 99%]
docs/whatsnew/index.rst .                                                                                        [100%]

============================================== 168 passed in 8.68 seconds ==============================================
```

cc @dan @eteq @astrofrog

**Comment by bsipocz** [comment]
And before you ask, running `py.test` is not a solution either, actually the situation there is even worse:
```
✔ ~/munka/devel/astropy [v2.0.x L|✚ 1⚑ 14] $ py.test astropy
================================================= test session starts ==================================================
platform darwin -- Python 3.7.0, pytest-3.7.4, py-1.6.0, pluggy-0.7.1

Running tests with Astropy version 2.0.10.dev19739.
Running tests in astropy.

Date: 2018-11-24T13:53:05

Platform: Darwin-17.7.0-x86_64-i386-64bit

Executable: /usr/local/opt/python/bin/python3.7

Full Python Version: 
3.7.0 (default, Sep 18 2018, 18:47:22) 
[Clang 9.1.0 (clang-902.0.39.2)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.15.4
Scipy: 1.1.0
Matplotlib: 3.0.2
h5py: 2.8.0
Pandas: 0.23.4
Cython: 0.28.5
astropy_helpers: 3.1rc1
Using Astropy options: remote_data: none.

rootdir: /Users/bsipocz/munka/devel/astropy, inifile: setup.cfg
plugins: cov-2.6.0, arraydiff-0.2
collected 0 items                                                                                                      

============================================= no tests ran in 2.15 seconds =============================================
```

**Comment by bsipocz** [comment]
I've narrowed down the issue to be `astropy/tests/pytest_plugins.py` related. Removing importing it in conftest.py the test collection works again. 

So while I suppose this also needs a workaround for #7782 as we can't leave the affiliates in this broken state.

**Comment by astrofrog** [comment]
This is actually fixed in pytest 4.0. It looks like the commit that broke things was 2b1410895e9ac30c4f08e9a701017cce65a9717b and the one that fixed it was f8b944dee0b59bdc483ce505738ea1cb3a57a5b4. I think it's ok to simply say that we don't support pytest >=3.7,<4 on LTS since it's a real pytest bug.

**Comment by drdavella** [comment]
Also @bsipocz just wanted to mention that using the `pytest` command is not and will not be supported on LTS, so it's not surprising that it did not work for you.

**Comment by bsipocz** [comment]
This has been documented and master is working, so I'm closing the issue as a won't fix.

**Comment by msyriac** [comment]
Since pytest is now on 4.3.0 and according to @astrofrog , this issue doesn't appear for >4.0, could I request the maintainers to consider requiring versions >4.0 rather than <3.7?

**Comment by pllim** [comment]
@msyriac , unfortunately, we do not have grand plans for LTS (`astropy<3`), just critical bug fix at this point, and this is not considered a critical bug. However, if you find that `astropy>=3` is not compatible with latest `pytest`, then please open a new issue.

**Comment by bsipocz** [comment]
There are other issues with pytest 4.0+ that would require API change for the LTS which by definition can't be done.

**Comment by msyriac** [comment]
Got it. Requiring astropy>=3 is an option, but this means dropping Python 2 support in our project right? (I am all for removing Python 2 support, but just wanted to make sure this is a necessary consequence).

**Comment by pllim** [comment]
> this means dropping Python 2 support in our project right?

Yes, basically.
