### ISSUE TITLE
Test model derivatives

### ISSUE THREAD

**Issue by nden** [astropy/astropy#8181]
Some of the tests of model derivatives in `test_models`  use parameter values of `1s` and `0es` which can hides errors in the derivative computation. Expand the tests with other values as suggested in [this comment](https://github.com/astropy/astropy/pull/8108#issuecomment-441474195)

**Comment by karllark** [comment]
This could be done automatically by numerically differentiating and checking versus the supplied analytic solution.

**Comment by nden** [comment]
It looks like this is already done in test_models.py, `Fittable1DTester` and `Fittable2DTester`
