### ISSUE TITLE
Segmentation fault when importing EllipticalFrame

### ISSUE THREAD

**Issue by smeingast** [astropy/astropy#8195]
Hey there. I am using astropy/wcslib provided via MacPorts and since the latest updates a few days ago I get the error

`Segmentation fault: 11`

when I import an EllipticalFrame via

`from astropy.visualization.wcsaxes.frame import EllipticalFrame`

Let me know if you guys need more info. thanks!

**Comment by bsipocz** [comment]
Would you please confirm what version of wcslib your MacPorts has? I suspect this is due to https://github.com/macports/macports-ports/pull/3026.

**Comment by smeingast** [comment]
Indeed, it seems related. I am using wcslib 6.2 and astropy 3.0.5. I have this issue on 3 different computers. When I reactivate wcslib 5.17 with my previous astropy installation 3.0.4, everything is in order.

**Comment by bsipocz** [comment]
I'm afraid we can't do anything about it in astropy. The new release (v3.1) will be compatible. Frankly the cleanest solution for you would be to switch to conda or pip install python packages rather than using macports so you have a better control of the version numbers.

**Comment by smeingast** [comment]
Thanks for the suggestions, but Macports actually gives a lot of control over version numbers. For example, I can just activate an older version of wcslib to fix the issue temporarily (which is what I just did). I will wait with upgrading wcslib to 6.x until astropy 3.1. 

Also thanks for replying so quickly!! :)
