### ISSUE TITLE
Use nightly wheels for dev testing (matplotlib)

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8197]
Numpy has nightly wheels built, as well as matplotlib, and  scipy has weekly. 

We may want to use them for testing. This can probably be done seamlessly in ci-helpers once we figure out how make it fail safe (and where the wheels are uploaded). Currently this is just a theory as the MacPython infrastructure seems to be broken for a number of packages.

**Comment by bsipocz** [comment]
And once this figured out, we do the same for astropy by providing a dev wheel for our own downstream packages.

**Comment by bsipocz** [comment]
Testing against nightly builds got favoured at the coordination meeting, so I tentatively milestones this for 3.2. 
This may need a bit of coordination with the upstream packages to figure out where they build their nightly, and whether that's stable enough for us to use. 
Ideally this can be a hackday project, etc.

**Comment by pllim** [comment]
Numpy already uses nightly (weekly) wheel. We don't test against scipy dev, so I think only matplotlib is left. I'll update the title.
