### ISSUE TITLE
Failures on numpy dev job

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#8199]
We've been seeing a few new test failures on the job against numpy-dev. Not sure if this is a bug upstream or something we need to fix. An example of the failure can be found [here](https://travis-ci.org/astropy/astropy/jobs/461723067#L1947).

**Comment by drdavella** [comment]
Actually one of the issues is clearly an internal API change, but the failure is coming from `skimage`.

**Comment by mhvk** [comment]
That `IndexError` looks like an upstream bug to me.
...
It is.
...
See https://github.com/numpy/numpy/pull/12464

Does that mean both issues are "upstream fix required"?

**Comment by pllim** [comment]
> Does that mean both issues are "upstream fix required"?

Indeed, it does. Thanks, @mhvk !

**Comment by bsipocz** [comment]
Ideally for that job we should use the dev version of all our dependencies, but for that #8197 is needed. After a decision, I'm happy to try and sprint figuring out the details.

**Comment by pllim** [comment]
No longer an issue.
