### ISSUE TITLE
Implement King Model

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#8208]
Sort of a sub-issue of #981... But the King Model (http://adsabs.harvard.edu/full/1966AJ.....71...64K) is a widely-used model in astronomy that might be worth implementing in the core.

**Comment by eteq** [comment]
cc @nluetzge

**Comment by nluetzge** [comment]
Yesss! So I have a python implementation of a King and a Wilson Model, but the program is solving a differential equation and then does some projection and this takes a while. So the models are slow. What I usually do is I create a library of models and just use this for the fit. Any way this can be implemented with astropy?

**Comment by pllim** [comment]
I am not sure if this qualifies as "package novice". The contributor does need to understand how to implement new models. 🤔

**Comment by bsipocz** [comment]
But it can still be a "good-first-issue", what do you think? Not an effort-low one is we take into account that it has to start with getting some understanding of modeling.

**Comment by pllim** [comment]
OK I changed the labels a bit. How about now?

**Comment by ludoro** [comment]
Hello everyone! 

I would love to try my hand at this. Do you have some resources on getting started? 
I have tried reading the article posted but I do not understand what I have to implement.

**Comment by nluetzge** [comment]
Hi @ludoro  I have a code that creates King and Wilson model. I also have the derivation of the equations written down if you are interested. Its a combination of what is described in Galactic Dynamics (Binney&Tremaine) Equations (4-130) to (4-132) and then converting this in a set of two coupled equations and solving it. Let me know if you are interested in this I'm happy to provide my code as a starting point if you can put it in the right framework.

**Comment by ludoro** [comment]
Yes, I am definitely interested in taking a look at that, thank you!

**Comment by ludoro** [comment]
Not sure, maybe dropbox?

**Comment by nden** [comment]
@nluetzge If you want you can create a PR with a simple class outline and including your code as an `evaluate` function. In this way you will get the credit for it and @ludoro will get the credit for putting it in the modeling framework. Of course, any other way works too.

**Comment by nluetzge** [comment]
Sure I can do this do you have an example ow the class should look like? My model is already in a class format.

**Comment by nden** [comment]
Any of the classes in `modeling/functional_models.py` can serve as an example. Let me know if you have questions.

**Comment by nluetzge** [comment]
Trying to work on this for tomorrow's PyAstro hack day.

**Comment by teuben** [comment]
I'm looking at quite a few "king" references in NEMO (some old ones in fortran), but I think the more novel approach to the slow integrator problem you mentioned is to do this computation once, and store the table to be re-used for later re-use if you need to generate the actual "random" points. An example of this is in mkommod , using the OsipkovMerrittModel approach. I found an example of creating and reading in plummer.c and mkommod.c in https://github.com/teuben/nemo/tree/master/src/nbody/init

**Comment by nluetzge** [comment]
In order for me to learn how to construct `astropy.models` I'm implementing a very simple version of the King model at the moment. I take the analytical solution from here: https://pythonhosted.org/Astropysics/coremods/models.html altho we still have to verify where this equation comes from. And I'm calling it `KingProjectedAnalytic1D` for now.

**Comment by teuben** [comment]
Ah yes, I came from a different angle, irrelevant for now. I was thinking via AMUSE.

**Comment by nluetzge** [comment]
So I put in the PR but I'm still not 100% where this analytic equation comes from. I will know more when @eteq is back and can look up where it comes from. In the meantime I was comparing this analytic solution to my code that produces the full King model. I'm attaching some plots. It looks like as long as W0 (the central potential) is smaller than 8, they kind of agree. For models beyond this things are getting crazy. 

That being said, I can't guarantee that the model I have (the full King model) is correct because I wrote it to fit somebody's data but I never had another person's model to compare it to.

[compare_models_W0min0.30_W0max15.00.pdf](https://github.com/astropy/astropy/files/3458998/compare_models_W0min0.30_W0max15.00.pdf)
[compare_models_W0min0.30_W0max8.00.pdf](https://github.com/astropy/astropy/files/3459001/compare_models_W0min0.30_W0max8.00.pdf)

**Comment by nden** [comment]
@eteq Can this ticket be closed now that @nluetzge's model is in or did you have a different equation in mind?
