### ISSUE TITLE
Major user-facing classes should link to the relevant parts of the narrative docs

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#8211]
Suggestion by @timj at the astropy coordination meeting 2018.  Proximate cause was for `SkyCoord` and `Quantity`, but really it probably applies to `Time`, `Table`, etc.

Basically, for users who start by playing with code via `help`/`?` and/or reading docstrings (or e.g. the `pydoc` command), it's hard to understand some of the more conceptually complex classes.  So there should be links to the narrative documentation in them so they know where to go to get higher-level help.

**Comment by taldcroft** [comment]
Good idea.  This also partially solves a long-time annoyance that the narrative docs or docstrings often link to the class doc (i.e. when you see `Table` in the docs it is typically a link to the Table class API doc).  But often the user needs the Table narrative docs at that point, not the class API.
