### ISSUE TITLE
Allow table cartesian join with no common column

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8220]
From user Igor Bukanov on Astropy feature request page:

Currently table join operations requires to have a common column in the tables. That prevents to form a Cartesian product of tables. The later is handy if one wants to calculate something based on data from unrelated tables.

**Comment by moon05** [comment]
Hi! By Cartesian Join are we thinking of something like this shown in the following link?
https://www.tutorialspoint.com/sql/sql-cartesian-joins.htm
I can give this a try. Would also appreciate any advice while implementing this or any kind of things I might have to be aware of.

**Comment by taldcroft** [comment]
Sure, that link is the right thing.  Here is a strawman code that can guide the implementation:
```
>>> t1 = simple_table()
>>> t2 = simple_table()
>>> t1_tmp = t1.copy(copy_data=False)
>>> t2_tmp = t2.copy(copy_data=False)
# Col name that doesn't exist, better to choose a bunch of random letters
>>> tmp_key = '__table_cartesian_join_temp_index__'  
>>> t1_tmp[tmp_key] = 0
>>> t2_tmp[tmp_key] = 0
>>> t12 = table.join(t1_tmp, t2_tmp, join_type='outer', keys=tmp_key)
>>> del t12[tmp_key]
>>> t12
<Table length=9>
 a_1    b_1   c_1   a_2    b_2   c_2 
int64 float64 str1 int64 float64 str1
----- ------- ---- ----- ------- ----
    1     1.0    c     1     1.0    c
    1     1.0    c     2     2.0    d
    1     1.0    c     3     3.0    e
    2     2.0    d     1     1.0    c
    2     2.0    d     2     2.0    d
    2     2.0    d     3     3.0    e
    3     3.0    e     1     1.0    c
    3     3.0    e     2     2.0    d
    3     3.0    e     3     3.0    e
```
I would suggest to allow a new value of `'cartesian'` for the `join_type` keyword argument in the `join()` function.

**Comment by moon05** [comment]
Alright sounds good. Thanks for the guidance! I will take a look and ask more questions.
Also in #8468, I think a doctsring wasn't passing the test cases because I called `ascii.read` in it, and `ascii` in turn calls `Table`. So any suggestion on how to bypass that kind of things, if it happens in this one?
