### ISSUE TITLE
Rewrite NDData.__repr__ to avoid reading whole array into memory

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#8228]
Ping @Cadair; the line that causes the issue is https://github.com/astropy/astropy/blob/master/astropy/nddata/nddata.py#L235

**Comment by saimn** [comment]
I tried and could not reproduce. @mwcraig - Do you remember if this was fixed somewhere ? Should we close ?

**Comment by mwcraig** [comment]
I do not recall....if we can't reproduce it I think it is fine to close.

**Comment by saimn** [comment]
@Cadair: maybe you remember the issue ?
