### ISSUE TITLE
Feature Request: ipython extension 

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#823]
Inspired by http://www.southampton.ac.uk/~fangohr/blog/physical-quantities-numerical-value-with-units-in-python.html in particular, it would be great to have astropy-ipython integration via an extension.

Some discussion on astropy-dev:
https://groups.google.com/d/topic/astropy-dev/7d7TnT-fQLA/discussion

As @eteq points out, the simple unit syntax introduced in the `PhysicalQuantity` extension isn't particularly beneficial because astropy already supports a very short syntax (though I'd argue the `u.m` example looks too much like `um` for micron... maybe an argument against using the extension's approach).  

However, there may be other ways in which an ipython extension could improve astropy usability.  This issue or the astropy discussion list would be a good place to mention those.

**Comment by adrn** [comment]
No longer relevant? Reopen if you disagree
