### ISSUE TITLE
SkyCoord and ICRS API has inconsistent requirements

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8239]
`SkyCoord(ra, deg, unit=u.deg)` works but `ICRS(ra, deg, unit=u.deg)` does not. What's up with the inconsistent API?

```python
>>> import astropy
>>> from astropy import units as u
>>> from astropy.coordinates import SkyCoord, ICRS
>>> astropy.__version__
'3.1rc2'
>>> ra = 0
>>> deg = 0
>>> SkyCoord(ra, deg, unit=u.deg)
<SkyCoord (ICRS): (ra, dec) in deg
    (0., 0.)>
>>> ICRS(ra, deg, unit=u.deg)
UnitTypeError: Longitude instances require units equivalent to 'rad', but no uni
t was given.
>>> ICRS(ra * u.deg, deg * u.deg)
<ICRS Coordinate: (ra, dec) in deg
    (0., 0.)>
```

**Comment by adrn** [comment]
This was a design decision: `SkyCoord` is the flexible initializer, the frame classes only take `Quantity` objects. Would it help to explain this more explicitly in [this docs page](http://docs.astropy.org/en/latest/coordinates/skycoord.html)? e.g., right now it just says "The SkyCoord class is more flexible with inputs to accommodate a wide variety of user preferences and available data formats." but it could give an example of the differences.

**Comment by shilpi1958** [comment]
Hi! I am shilpi. Can I work on this issue?

**Comment by adrn** [comment]
Hi @shilpi1958 -- sure! That sounds good: I would recommend editing the line that says 

> The SkyCoord class is more flexible with inputs to accommodate a wide variety of user preferences and available data formats.

To instead say something like 

> The SkyCoord class is more flexible with inputs to accommodate a wide variety of user preferences and available data formats, whereas the frame classes expect to receive Quantity-like objects with angular units.

Feel free to open a pull request!

**Comment by shilpi1958** [comment]
Hey! I made a pull request. Let me know if it's fine :)
