### ISSUE TITLE
Add bitplanes to NDData

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#8243]
There is functionality for interpreting bitfields in NDData, but we currently do not have a class or item for a bitfield (or bitplane or bitflag or bitsets)

- bit to name dictionary 
- possible behavior: ability to combine bitfields with different sets of names
- being able to use bit names or bit values
- clarify bitvalue vs bit id (3rd bit position vs value of 8)
- changes the total allow range of bits allowed
- ability to be used in tables

**Comment by bsipocz** [comment]
I remove the milestone as it's unrealistic to assume this will be implemented and merged by Friday.

**Comment by bsipocz** [comment]
Removing milestone as it won't materialize and being reviewed in 1.5days.

**Comment by saimn** [comment]
@mcara - Should we close this one ? (Following your comment in https://github.com/astropy/astropy/pull/10095#issuecomment-615433404)

**Comment by mcara** [comment]
I believe #10095 completely addressed almost all points in the issue in a way or another (maybe except last two as I do not know what they mean). I think this can be closed.
