### ISSUE TITLE
ABmag not documented on units page

### ISSUE THREAD

**Issue by parejkoj** [astropy/astropy#8244]
The `ABmag` unit is mentioned twice on the [logarithmic units page](http://docs.astropy.org/en/stable/units/logarithmic_units.html), but has no documentation and is not even mentioned on the [main units page](http://docs.astropy.org/en/stable/units/index.html).

@pllim made sure that the new [photometry units documentation](https://18336-2081289-gh.circle-artifacts.com/0/home/circleci/project/docs/_build/html/units/index.html#module-astropy.units.photometric) got into the release.

@mhvk was mentioned as who to contact about getting ABmag documented there.

**Comment by mhvk** [comment]
Indeed, we now at least include http://docs.astropy.org/en/latest/units/index.html#module-astropy.units.photometric - but that doesn't mention any of the `mag*` actual logarithmic units.

A trivial change would be to add a sentence in the docstring of `photometric.py` to note that all those units have corresponding `mag*` entries. Next, I think the easiest additional thing to do is to also auto-generate its docstring in `logarithmic.rst`. And, finally, add some more descriptive text there.

**Comment by parejkoj** [comment]
While attempting to do the first part (adding docs to `photometric.py`), it appears the names aren't consistent (`M_bol` vs. `ABmag`).

**Comment by KING-SID** [comment]
Hey, I wanted to know if this issue had been solved? Let me know as I'd like to take it on!

**Comment by mhvk** [comment]
@KING-SID - this issue was indeed solved by #8287 - we just forgot to close it!
