### ISSUE TITLE
TST: Add link checking in Sphinx build

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8254]
As suggested in https://github.com/astropy/astropy/pull/8249#discussion_r240029657 so that we can ensure links are not broken in the docs.

**Comment by SG004** [comment]
Hey I'd like to try this. I've researched into sphinx and now understand its purpose and how to use it, for the most part. However I do not know where I would place the "make linkcheck" command. Where in the sphinx build would I add the link checking?

**Comment by bsipocz** [comment]
@SG004 - The sphinx building is done on circleCI, so once you have a working setup locally, you can start adding it to those config files.

There was one try years ago (https://github.com/astropy/astropy/pull/2907), it could be a place to start (as well as checking on other projects' configs that do this themselves).
