### ISSUE TITLE
Consider whether we can add a RTD build on CircleCI

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8269]
The RTD build process is well described here:

https://docs.readthedocs.io/en/latest/builds.html

and relies on a Docker image. This means that in principle we could try and replicate the RTD build process in CircleCI to make it easier to catch issues early (the kind that I fixed in #8268).

It might be interesting to experiment with that?

**Comment by pllim** [comment]
This is not the only way though. One can enable RTD on one's Astropy fork as well.

**Comment by astrofrog** [comment]
Indeed, but that's more manual work, and I'm pretty sure CircleCI would be faster. There may also be PRs that don't appear to touch stuff that should matter but still break RTD (for which we'd not test on our forks first).

**Comment by astrofrog** [comment]
Anyway, this is just an idea in case it's easy to do :)

**Comment by pllim** [comment]
Let's just wait for RTD PR builder.
