### ISSUE TITLE
Problem with the `littleh` part of unit equivalencies?

### ISSUE THREAD

**Issue by dr-guangtou** [astropy/astropy#8271]
In the newly added `littleh` equivalencies: http://docs.astropy.org/en/stable/units/equivalencies.html#unit-equivalencies 

We notice that the implementation of `littleh` seems to be wrong, as highlighted in the following figure:

![screen shot 2018-12-12 at 12 59 23](https://user-images.githubusercontent.com/7539807/49902062-c2c20c00-fe17-11e8-8368-66c294fc067d.png)

If `distance = 100 Mpc/h`, and `h=0.7`, should it be equivalent to 140 Mpc, instead of 70Mpc? 

I can reproduce this so it is not a typo...

**Comment by eteq** [comment]
(I removed the `cosmology` label b/c this is not actually part of the cosmology package - it's really just units)

**Comment by eteq** [comment]
Thanks for catching this @dr-guangtou - indeed it's definitely wrong - was write in an earlier version, but somehow got flipped around in the process of a change of the implementation.  

marking this for 3.1.1, as it's a pretty major "wrongness"

**Comment by dr-guangtou** [comment]
Thanks for the quick response!  The credit for catching this bug goes to Peter Behroozi but he is not on Github, so...

I definitely think this is a great idea! Looking forward to the next correct version
