### ISSUE TITLE
Error creating magnitude units with `<<` or u.Quantity

### ISSUE THREAD

**Issue by parejkoj** [astropy/astropy#8272]
The [notes linked](http://docs.astropy.org/en/latest/units/index.html#astropy-units-performance) from the 3.1 changelog suggest using `<<` instead of `*` for a performance boost, but that gives me an error if I try to make a magnitude unit. But that doesn't work for magnitude units:

```
In [18]: x << u.ABmag                                                           
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-350729cf31e7> in <module>
----> 1 x << u.ABmag

TypeError: unsupported operand type(s) for <<: 'numpy.ndarray' and 'MagUnit'
```

I wonder if this is related to the fact that you can't directly create a `u.Quantity` with magnitude units:

```
In [46]: u.Quantity(x, u.ABmag)                                                 
---------------------------------------------------------------------------
UnitTypeError                             Traceback (most recent call last)
<ipython-input-46-efd4fb281543> in <module>
----> 1 u.Quantity(x, u.ABmag)

~/dev/astropy/astropy/units/quantity.py in __new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    382 
    383         value = value.view(cls)
--> 384         value._set_unit(value_unit)
    385         if unit is value_unit:
    386             return value

~/dev/astropy/astropy/units/quantity.py in _set_unit(self, unit)
    609                 raise UnitTypeError(
    610                     "{0} instances require {1} units, not {2} instances."
--> 611                     .format(type(self).__name__, UnitBase, type(unit)))
    612 
    613         self._unit = unit

UnitTypeError: Quantity instances require <class 'astropy.units.core.UnitBase'> units, not <class 'astropy.units.function.logarithmic.MagUnit'> instances.
```

Reading through #5851 suggested `u.Quantity(x, u.ABmag, subok=True)`, which does work, but I never would have figured that out without finding that ticket. If we really can't create a `u.Quantity` by default for magnitude units, can we at least have the exception suggest `subok=True`?

Possibly related: #6897 and #5851

**Comment by mhvk** [comment]
@parejkoj - thanks for reporting. Having written both `<<` and magnitude units, I should have been the first to notive this was not working! The reason it is not is simple: the functional unit and quantity classes did not gain new `__lshift__` definitions. Any interest in trying to add it? (Follow #7734 for `FunctionUnitBase` and `FunctionQuantity` in `units/function/core.py` and add tests.) If not, no worries, I'll get to it (eventually...).

**Comment by pllim** [comment]
@parejkoj , with #8290 merged, is this issue resolved or is there something else?

**Comment by parejkoj** [comment]
I think that should take care of it, yes.
