### ISSUE TITLE
Astropy banner missing from main docs page

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#8277]
On http://docs.astropy.org/en/latest/, the main astropy banner is not appearing for me:
![image](https://user-images.githubusercontent.com/583379/49954067-8bae3200-fecd-11e8-9da1-a25ed78c0cc0.png)

**Comment by pllim** [comment]
Me neither. Tried on Windows 10 + Chrome and Linux + Firefox.

**Comment by pllim** [comment]
Why is it linking to `_images`? Those files are in `_static`...

```html
<img src="_images/astropy_banner.svg" onerror="this.src='_images/astropy_banner_96.png'; this.onerror=null;" width="485"/>
```
