### ISSUE TITLE
Cannot get to old version of the documentation on RTD

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#8288]
When I try navigating to an old version of the documentation at https://astropy.readthedocs.io/en/stable/ using the menu un the lower right, I get a page not found error, screenshot below.

The url I get to after clicking the link for v3.0.5 is http://docs.astropy.org/en/v3.0.5/

![maze_found___read_the_docs](https://user-images.githubusercontent.com/1147167/50034956-263d6c80-ffc5-11e8-9788-a180de48aeb9.png)

**Comment by bsipocz** [comment]
OK, version is building. Thanks for the report, and sorry about the inconvenience.

**Comment by mwcraig** [comment]
No problem!

**Comment by bsipocz** [comment]
Now it works.

**Comment by mwcraig** [comment]
It looks like `v2.0.9` isn't available and `v2.0.10` doesn't show up at all...

**Comment by bsipocz** [comment]
😱

**Comment by mwcraig** [comment]
The older-docs-archive doesn't work either....in good news, I'm heading out for the evening so I won't notice anything else 😬

**Comment by astrofrog** [comment]
Here is a list of versions in the older-docs-archive:

http://docs.astropy.org/en/older-docs-archive/

That list is static (only for docs prior to October 2018) and any new versions should be accessed the normal way using 

http://docs.astropy.org/en/<version>/
