### ISSUE TITLE
Wish: setup.py clear the cache during installation 

### ISSUE THREAD

**Issue by texadactyl** [astropy/astropy#8297]
I went to Anaconda/Python3.  Astropy is a different version than I was using before when I was using pip3.  My ```$HOME/.astropy/cache/download/py3/``` was left over and I thought nothing of it.

When I I ran the simple program from issue #5238 with cache=True, I got the same symptoms; when running with cache=False, no worries.  

In Spyder, I followed the stack trace and discovered that the problem-some url was a binary file from the cache, causing shelve to try to use dbm.gnu to open it and failed with the same message as in issue #5328: ```error: db type is dbm.gnu, but the module is not available```

The simple work-around: delete the cache contents.  This could be done as part of astropy's setup.py execution.  Opinions?

Yes, I still do not know why shelve barfed on a binary file.  Probably something else amiss in my Xubuntu 18.04.1 LTS.

**Comment by pllim** [comment]
Thanks for reporting this and documenting a solution that worked for you. However, this solution might not be generic enough to be applied to *everyone* at installation. There are situations where one does not wish to clear download cache when one re-installs or upgrades Astropy. Others feel free to chime in.

**Comment by texadactyl** [comment]
It turns out that dbm/__init__.py whichdb() selected "dbm.gnu" based on a binary file having no extension.  See:

**Comment by texadactyl** [comment]
Thanks for your quick response.  I understand your point.

It turns out that dbm/init.py whichdb() selected "dbm.gnu" based on a binary file having no extension. See the following around line 171:
```
    # Check for GNU dbm
    if magic in (0x13579ace, 0x13579acd, 0x13579acf):
        return "dbm.gnu"
```

Probably, the cached file was built using dbm.gnu and my choices (based on ```$HOME/anaconda3/lib/python3.7/dbm/```) are dumb, gnu, or ndbm.

gnu.py on my system is:

```
"""Provide the _gdbm module as a dbm submodule."""

from _gdbm import *
# no executable code.
# no _gdbm module either
```

**Comment by pllim** [comment]
Great! If you think that has been resolved, please close the issue. Otherwise, we welcome a suggested patch via pull request. Thanks again.

**Comment by texadactyl** [comment]
Also, it sounds like dbm/__init__.py should default to ndbm
