### ISSUE TITLE
Bad hardlink in 3.1 source tarball

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#8299]
Thanks for all the work put into this version; unfortunately I did not have time to test the release candidates. Unpacking the source (on Linux) results in the following error:
```
> tar xf astropy-3.1.tar.gz
tar: astropy-3.1/astropy/CITATION: Cannot hard link to `astropy-3.1/CITATION': Operation not permitted
tar: Exiting with failure status due to previous errors
```
Everything except for the link in `astropy/` is present, so `setup.py build` subsequently fails with
```
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    import astropy
  File "/beegfs/home/hd/hd_hd/hd_qc666/build/python/astropy-3.1/astropy/__init__.py", line 274, in <module>
    __citation__ = __bibtex__ = _get_bibtex()
  File "/beegfs/home/hd/hd_hd/hd_qc666/build/python/astropy-3.1/astropy/__init__.py", line 267, in _get_bibtex
    with open(citation_file, 'r') as citation:
FileNotFoundError: [Errno 2] No such file or directory: '/beegfs/home/hd/hd_hd/hd_qc129/build/python/astropy-3.1/astropy/CITATION'
```
This requires manually running ` ln -s ../CITATION` from the `./astropy/` subdir before the build proceeds.

**Comment by pllim** [comment]
The symlink was added in #7718 . There was discussions on it in that PR.

**Comment by dhomeier** [comment]
Thanks for the reference; a search for "link" on github had not produced anything. So is the situation that symlinks are broken on Windows and hardlinks are broken on Unix, or is this just the aftermath of some github quirk?

**Comment by dhomeier** [comment]
Looks like creating the tarball with `--hard-dereference` will produce an actual copy of the file in `astropy/CITATION`; that should at least keep the issue from the user.
The hard link actually appears to be only a problem of the specific cluster file system, not with Unix/Linux in general.

**Comment by pllim** [comment]
Thank you very much for investigating and posting the solution here! Do you think an entry to "known issues" section would sufficiently address this?

**Comment by dhomeier** [comment]
I think so. In principle only the person or bot creating the tarball would have to know the latter solution, and otherwise anyone building from source would likely figure out how to manually create the link themselves, but it cannot hurt to have it documented.

**Comment by pllim** [comment]
@dhomeier , would you be interested to open a PR to address this then? :smile: :pray:

**Comment by dhomeier** [comment]
I guess I can hardly refuse the offer at this point. Just need to get back to my other machine with a hopefully reasonably up-to-date git clone - trying to update from the April 2018 state on my office machine is throwing me into a merge conflict nightmare.
Also I am thinking the best solution might be to have `setup.py sdist` create the tarball with the correct options, but I am in an even bitterer war with setuptools and have no idea how to effect this.

**Comment by pllim** [comment]
@dhomeier , feel free to ping one of us on Astropy Slack if you need help with resolving conflicts. Also @drdavella , @astrofrog , or @Cadair might have something to say about desire to improve `setup.py`.

**Comment by dhomeier** [comment]
Thanks. I've dug a bit into the setuptools documentation, but it seems pretty clear that they do not pass any options to `sdist` apart from `'formats'`, `'keep-temp'` and `'dist-dir'`.
But it's less clear how the download files on pypi.org have been created; in my local git repo `CITATIONS` **is** a softlink to `astropy/CITATIONS` rather than a hardlink the other way round.
Unfortunately I cannot test what kind of tarball `setup.py sdist` would create from my Mac, since setup from git is broken there for quite some time (some weird problem with setup.py apparently spawning too many subprocesses and running out of threads...). Waiting to get the git clone on the Linux machine back to a healthy state...

**Comment by saimn** [comment]
@dhomeier - Is your setup issue similar to https://github.com/astropy/astropy-helpers/issues/207 ?

**Comment by dhomeier** [comment]
@saimn - thanks, yes! I vaguely remembered I could temporarily fix it by removing some build or cache directories. I have a two-level structure of `astropy_helpers/astropy_helpers` as well as `astropy_helpers/astropy_helpers.egg-info`, but when I'm removing any of those now I just get a forced re-download and then the same failure:
```
> python3.6 setup.py sdist                                                                                                              
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
Fatal Python error: PyThreadState_Get: no current thread
Segmentation fault
```

**Comment by dhomeier** [comment]
Well, indeed the tarball in the GitHub [releases](https://github.com/astropy/astropy/releases) has the same soft link 
`astropy-3.1/CITATION -> astropy/CITATION` rather than the hard
`astropy-3.1/astropy/CITATION link to astropy-3.1/CITATION`.
Maybe it's more of a pypi issue.

**Comment by dhomeier** [comment]
That's in fact strange - I've now tested this with the 3.1 and 3.1.1 releases and the latest `HEAD` on Linux, and `setup.py sdist` actually lets this always end up as a **soft link** in the tarball, although it reports tons of messages about creating hard links...
```
making hard links in astropy-3.2.dev23748...
hard linking .astropy-root -> astropy-3.2.dev23748
hard linking CHANGES.rst -> astropy-3.2.dev23748
hard linking CITATION -> astropy-3.2.dev23748
hard linking LICENSE.rst -> astropy-3.2.dev23748
hard linking README.rst -> astropy-3.2.dev23748
hard linking ah_bootstrap.py -> astropy-3.2.dev23748
hard linking pip-requirements -> astropy-3.2.dev23748
hard linking setup.cfg -> astropy-3.2.dev23748
hard linking setup.py -> astropy-3.2.dev23748
hard linking astropy/CITATION -> astropy-3.2.dev23748/astropy
```
when only `CITATION` comes out as a (_soft_) link at all:
```
-rw-r-----  1 derek 342746 Jan 16 23:39 CHANGES.rst
lrwxrwxrwx  1 derek     16 Dec  6 10:01 CITATION -> astropy/CITATION
```
Thus my speculation that pypi.org is creating their tarballs somewhat differently.
Maybe distutils just has a different concept of hard link than Unix in general.

But anyway, not much we can do about the actual thing either way, so I'll go ahead at last with a PR to document this in `known_issues.rst`.

**Comment by pllim** [comment]
> I'll go ahead at last with a PR to document this 

@dhomeier , did you ever get the chance to open that PR? If so, please cross-ref here. Thanks!

**Comment by dhomeier** [comment]
@plim, sorry haven't done so yet. I no longer have access to the cluster using BeeGFS and thus cannot test anything, but I checked that the 3.2.3 tarball still contains the hardlink. So assuming `setup` still requires both instances of `CITATION`, I suppose I can document the current state of things and the workaround of manually creating the link. Unfortunately I cannot investigate now if the same problem pops up when installing from source using pip, and how to fix the link in that case - installing explicitly from the GitHub release should probably do.

Wondering if `known_issues.rst` is actually the best place to put this, or rather the `Building from Source` section in `install.rst`...

**Comment by pllim** [comment]
> Wondering if...

Hmm, not sure. I'll let others weigh in.
