### ISSUE TITLE
IERS data url is down and backup not used

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#8304]
The download URL for IERS data is down: http://maia.usno.navy.mil/ser7/finals2000A.all

however, there is a backup still working here: http://toshi.nofs.navy.mil/ser7/finals2000A.all

Would it be possible to add a solution that also trys the backup server like it is done for other downloads?

**Comment by pllim** [comment]
cc @taldcroft

**Comment by mhvk** [comment]
Might this also be why currently travis tests of `iau_full_stack` are stalling? If so, we definitely need to change those - at least, I thought that for our normal tests we do not download anything from outside of astropy.

**Comment by pllim** [comment]
IERS_B_URL is working and appears to be the default. I wonder why this is happening... :thinking: 
```python
# by default for IERS class, read IERS-B table
IERS.read = IERS_B.read
```

**Comment by pllim** [comment]
Haha, @mhvk ! Incidentally, I marked that test as requiring remote data in #8033 (it is not correctly marked as so) but it is not merged yet.

**Comment by pllim** [comment]
I'll see if I can hack something quick for this since it appears to be affecting everything...
