### ISSUE TITLE
no parallax in apply_space_motion ?

### ISSUE THREAD

**Issue by patkel** [astropy/astropy#8310]
Hi, apply_space_motion in v3.1 does not seem to include expected motion due to parallax, 
although I may be doing something wrong.

There's an example below which I put together.  The ra and dec change when I 
include proper motion, but when the proper motion is set to zero there is no change 
in coordinates (although I think there ought to be because the distance is 0.1 parsecs). Best Pat

```
import astropy.units as u
from astropy.time import Time
from astropy.coordinates import ICRS, Galactic, FK4, FK5
from astropy.coordinates import SkyCoord                    
                                                                  
ra_deg, dec_deg = 177.398584, 22.396684
                                                                  
coords = SkyCoord(ra_deg*u.degree, 
                 dec_deg*u.degree, 
                 distance=(0.1*u.pc).to(u.pc, u.parallax()),
                 pm_ra_cosdec=0*u.mas/u.yr, 
                 pm_dec=0*u.mas/u.yr,
                 radial_velocity = 0 * u.km/u.s,
                 obstime=Time('2015-01-01 00:00:0'),
                 frame='icrs',
                 )

print(coords.ra, coords.dec)
new_obstime = Time(53005, format='mjd')
a = coords.apply_space_motion(new_obstime=new_obstime) 
print(a.ra, a.dec)
```

**Comment by StuartLittlefair** [comment]
I believe this is correct. Your coordinates are in the ICRS frame, whose origin is at the solar system barycentre. If there is no proper motion, this star's position will remain fixed *in this frame*.
