### ISSUE TITLE
ncp_prior referenced before assignment in Bayesian Blocks

### ISSUE THREAD

**Issue by javier-iaa** [astropy/astropy#8317]
There is a bug in the bayesian blocks algorithm of astropy.stats. It's not a big deal so I show you below how to solve it directly.

When I call:
```python
bayesian_blocks(tt, ff, sig, fitness='measures', ncp_prior=ncpp)
```

I get:
```
Traceback (most recent call last):

  File "<ipython-input-29-9adfe04a2714>", line 1, in <module>
    bayesian_blocks(tt, ff, sig, fitness='measures',ncp_prior=ncpp)

  File "bayesian_blocks.py", line 154, in bayesian_blocks
    return fitfunc.fit(t, x, sigma)

  File "bayesian_blocks.py", line 373, in fit
    A_R = fit_vec - ncp_prior

UnboundLocalError: local variable 'ncp_prior' referenced before assignment
```
You can fix this just by changing:
```python
        if self.ncp_prior is None:
            ncp_prior = self.compute_ncp_prior(N)
```
adding an else sentence
```python
        else:
            ncp_prior = self.ncp_prior
```
EDIT: Text formatting

**Comment by pllim** [comment]
Thanks, @javier-iaa . If you already have the fix, for proper credit, I would recommend that you submit your proposed patch as a proper pull request. Please refer to http://docs.astropy.org/en/latest/development/workflow/development_workflow.html

**Comment by javier-iaa** [comment]
I'll do that. I'm pretty new to github so this will be nice practice. Thanks!
