### ISSUE TITLE
ImportError for astropy.time / erfa / numpy.core.multiarray with Python 2.7 / Astropy==2.0.11

### ISSUE THREAD

**Issue by timstaley** [astropy/astropy#8330]
Hi folks,

I've come across a slightly odd one recently, it seems astropy 2.0.11 on Python 2 has an import error regarding the erfa/_core.so module and numpy?

Steps to reproduce, on an Ubuntu 18 system:

```
mkvirtualenv -python2 astropy2.0.11-test
pip install astropy
python -c "import astropy.time"


```
Gives:

> ImportError: No module named _multiarray_umath
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/staley/.virtualenvs/astropy2.0.11-test/local/lib/python2.7/site-packages/astropy/time/__init__.py", line 2, in <module>
>     from .formats import *
>   File "/home/staley/.virtualenvs/astropy2.0.11-test/local/lib/python2.7/site-packages/astropy/time/formats.py", line 15, in <module>
>     from .. import _erfa as erfa
>   File "/home/staley/.virtualenvs/astropy2.0.11-test/local/lib/python2.7/site-packages/astropy/_erfa/__init__.py", line 4, in <module>
>     from .core import *
>   File "/home/staley/.virtualenvs/astropy2.0.11-test/local/lib/python2.7/site-packages/astropy/_erfa/core.py", line 42, in <module>
>     from . import _core
> ImportError: numpy.core.multiarray failed to import
> 

Note, a workaround of installing 2.0.10 seems to run OK.

**Comment by mhvk** [comment]
There seems to be a problem with `numpy`, really; does `python -c "import numpy" work? If that also fails, then it might be that astropy is pulling in a non-functioning version of numpy.

**Comment by pllim** [comment]
I can't even test this on my machine. `pip install astropy` requires Microsoft Visual C++ 9.0 that I don't have. However, `conda install astropy` works and does not give `ImportError`. My `conda list` for Python 2.7.15:

```
# packages in environment at C:\...\Miniconda3\envs\py2tmp:
#
# Name                    Version                   Build  Channel
astropy                   2.0.11           py27hc997a72_0
atomicwrites              1.2.1                     <pip>
attrs                     18.2.0                    <pip>
backports                 1.0                        py_2    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
colorama                  0.4.1                     <pip>
colorama                  0.4.1                      py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
funcsigs                  1.0.2                     <pip>
ipython                   5.8.0                    py27_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
more-itertools            5.0.0                     <pip>
numpy                     1.15.4                    <pip>
pathlib2                  2.3.3                 py27_1000    conda-forge
pickleshare               0.7.5                 py27_1000    conda-forge
pip                       18.1                     py27_0
pluggy                    0.7.1                     <pip>
prompt_toolkit            1.0.15                     py_1    conda-forge
py                        1.7.0                     <pip>
pygments                  2.3.1                      py_0    conda-forge
pytest                    3.6.4                     <pip>
python                    2.7.15               hcb6e200_5
scandir                   1.9.0           py27h0c8e037_1000    conda-forge
setuptools                40.6.3                   py27_0
simplegeneric             0.8.1                      py_1    conda-forge
six                       1.12.0                    <pip>
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.26.0               h0c8e037_0
traitlets                 4.3.2                 py27_1000    conda-forge
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.32.3                   py27_0
win_unicode_console       0.5                   py27_1000    conda-forge
wincertstore              0.2              py27hf04cefb_0
```

**Comment by mhvk** [comment]
This may be the same error @astrofrog found in another context, and reported to the numpy mailing list at http://numpy-discussion.10968.n7.nabble.com/Issue-with-setup-requires-and-1-16-release-candidates-td46600.html

**Comment by timstaley** [comment]
> This may be the same error @astrofrog found in another context, and reported to the numpy mailing list at http://numpy-discussion.10968.n7.nabble.com/Issue-with-setup-requires-and-1-16-release-candidates-td46600.html

@mhvk - that's an interesting possible cause, thanks! I'll investigate a bit further when I get a chance.

**Comment by astrofrog** [comment]
Yes I'm 99% sure this is the same issue. I doubt we'll get a new release of astropy out before Numpy 1.16 is released (which will make this problem go away for now) but we should definitely add a ``pyproject.toml`` file anyway declaring numpy as a build-time dependency since this is the new way to do things.

**Comment by astrofrog** [comment]
@timstaley - this shouldn't happen with recent versions of pip as the wheel for astropy should be used. What version of pip do you have?

**Comment by timstaley** [comment]
Happy to report this is now working fine again - through no action of mine(!), cf
https://travis-ci.org/timstaley/voevent-parse/builds/475841302
https://travis-ci.org/timstaley/voevent-parse/builds/476133219
So I don't know if it was on the astropy side or the numpy side or just down to the fickle small gods of Python package management, but I'm grateful either way ;)
