### ISSUE TITLE
QTable dtype not preserved on quantity columns

### ISSUE THREAD

**Issue by mcbeth** [astropy/astropy#8334]
If I attribute a column with a unit, than the datatype of the column is lost.  I've tried on Astropy 3.0.8, 2.0.3, and 1.2.1.  On astropy 1.2.1 (you probably don't care), I cannot pull the astype trick to fix the dtype afterwards, with the error "Value not scalar compatible or convertible to an int, float or complex array"

```
import astropy
import astropy.table
import numpy
import sys

print('Python version: '+sys.version)
print('Astropy version: '+astropy.version.version)
print('Numpy version: '+numpy.version.version)

a = astropy.table.QTable()
b = astropy.table.QTable.Column(data=numpy.zeros(1,dtype=numpy.uint8),name='Crazy',dtype=numpy.uint8,unit='m')
a.add_column(b)
# I would expect the dtype to be uint8
# If I do not set the unit above, it will be
print(repr(a))

a['Crazy'] = a['Crazy'].astype(numpy.uint8)
print(repr(a))
```

I've tried it on two setups
```python2 foo.py
Python version: 2.7.15+ (default, Oct  2 2018, 22:12:08)
[GCC 8.2.0]
Astropy version: 2.0.8
Numpy version: 1.15.0
<QTable length=1>
 Crazy
   m
float64
-------
    0.0
<QTable length=1>
Crazy
  m
uint8
-----
    0
```

```python3 foo.py
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
Astropy version: 3.0.3
Numpy version: 1.15.0
<QTable length=1>
 Crazy
   m
float64
-------
    0.0
<QTable length=1>
Crazy
  m
uint8
-----
    0
```

**Comment by mhvk** [comment]
Indeed, by default `Quantity` casts all input to float (since this makes most sense for anything with units), and thus happens when you add a `Column` item to your table. If you want to override this, you can do:
```
a['Crazy'] = astropy.units.Quantity(numpy.zeros(1,dtype=numpy.uint8), dtype=numpy.uint8)
```

Or, equivalently,
```
b = astropy.units.Quantity(numpy.zeros(1,dtype=numpy.uint8), dtype=numpy.uint8)
a.add_column(b, name='Crazy')
```

**Comment by mcbeth** [comment]
It is clear to me that I went too far in simplifying the example.  
```
b = astropy.units.Quantity([0]*astropy.units.m,dtype=numpy.uint8)
c = astropy.table.QTable.Column(data=b,dtype=numpy.uint8,name='Crazy')
a.add_column(c)
```
b will have the right dtype, c will have the right dtype, a['Crazy'] will not.
Thank you for your inputs, and the suggested alternate paths.
None of them work on the machine where we're stuck on 1.2.1, but that's a fight we'll keep having with IT and not your problem.

I understand the reasoning behind Quantity being a float by default and wholeheartedly support that.  
I'm not sure I understand overriding the user's expressly stated intent, particularly, since integer units can make sense.  I'll readily admit I have not thought through all the implications of allowing such a thing
