### ISSUE TITLE
thermodynamic_temperature equivalency: doc misleading

### ISSUE THREAD

**Issue by dcrichton** [astropy/astropy#8335]
The documentation for this equivalency incorrectly states that it is between thermodynamic temperature in K and Jy/beam when it is actually between K and Jy/sr.

This is also incorrectly stated in the changelog for v3.1.

I'm happy to provide a pull request fixing this but I'm not sure if the changelog should also retroactively be changed.

**Comment by pllim** [comment]
@abeelen , can you please comment on the `/beam` vs `/sr` in the doc since you authored the original PR in #7054 ? @bsipocz should be able to comment on the change log policy.

**Comment by abeelen** [comment]
@dcrichton you are right, the header of the docstring state Jy/beam, where it should be a properly defined brigthness unit, as in the doctest. In principle it could work, but the beam area has to be defined somewhere... Sorry for the trouble. 

If you could provide a PR for this, it would be great !

**Comment by bsipocz** [comment]
If it's only a change of 'beam' vs 'sr' in the docs, then I suppose we can look at it as a typo and should also fix the original changelog entry.
