### ISSUE TITLE
The matching catalogues doctests are skipped in docs

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8342]
There is no apparent reason stated (neither could @adrn fine something on it), so if possible we need to enable doctest running for `docs/coordinates/matchsep.rst`

**Comment by SG004** [comment]
I would like to try and fix this issue. I just have a few questions.
Where would I find the place where the doctest is run for all of the files? I'd like to confirm that it isn't being run. I see in circleCI setup.cfg file under `[tool:pytest]` that `doctest_plus = enabled`. 
Is the doctest run on circleCI?

**Comment by bsipocz** [comment]
Doctest is running on all CI-s (and also when you run `python setup.py test` locally)

Here the issue is that some code are skipped being tested using the `doctest: +SKIP` directive in the documentation file referred in description above.
