### ISSUE TITLE
Implement Issue and PR templates

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8350]
As suggested by @brechmos-stsci , it might be beneficial to give users a check list when they open a new issue or a new pull request (the latter should be consistent with existing dev guide). A first draft could be obtained from existing sources, for example https://www.talater.com/open-source-templates .

For instance, choosing new issue, bug + feature request, and backend brought me to https://www.talater.com/open-source-templates/#/page/98

```
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:
```

**Comment by mhvk** [comment]
Note that numpy has installed something that ensures that this template is what you get to see if you click their "new issue" button or create a PR.  I'm not quite sure how they did this, but it might at least send you in the right direction.

**Comment by mhvk** [comment]
p.s. I should perhaps add that the first thing I do when I do anything with numpy is to delete the template...  Still, I do think it is useful to give a sense of what makes a useful issue/PR - just don't go overboard.

**Comment by pllim** [comment]
@agarwalrounak , thank you for your interest, but only admins can make those templates. Perhaps you could provide the text to go into the template if you want, but an admin would have to go into the repo settings and click Community to add the templates.

**Comment by bsipocz** [comment]
sunpy also have templates, but I agree with @pllim, that this may not be the ideal first issue to work on (we usually label them as `good first issue` or `package-novice`.

**Comment by MSeifert04** [comment]
I think what @mhvk means is what we also have in ccdproc as file Templates (https://github.com/astropy/ccdproc/tree/master/.github).

**Comment by bsipocz** [comment]
I vaguely remembered I saw this one in astropy land, too 😊

**Comment by agarwalrounak** [comment]
@pllim I don't think that only admins can make those templates. All we have to do is create files named `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md`, and store them in `.github` folder but as @bsipocz mentioned, I should perhaps solve a `good first issue` and then move to this one.

**Comment by pllim** [comment]
@agarwalrounak , ah, I was thinking about the web interface.

**Comment by bsipocz** [comment]
We just need to do it now. A good issue to fix over a sprint day, etc.

**Comment by bsipocz** [comment]
Don't forget to link to the awesome but somehow hidden PR example @mwcraig has put together here: https://docs.astropy.org/en/latest/development/workflow/git_edit_workflow_examples.html#astropy-fix-example
