### ISSUE TITLE
Clang warnings: unknown warning option '-Wno-format-overflow'  '-Wno-misleading-indentation';

### ISSUE THREAD

**Issue by yurivict** [astropy/astropy#8366]
```
warning: unknown warning option '-Wno-misleading-indentation'; did you mean '-Wno-binding-in-condition'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-format-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
```

**Comment by pllim** [comment]
Hello. Can you please give more context? If you see this during `python setup.py install` step and it comes from external package(s) that we bundle, there is little we can do about it.  Also, please give the exact steps and OS info to reproduce the messages reported. Thank you.

**Comment by saimn** [comment]
These options are used in the cfitsio extension:
https://github.com/astropy/astropy/blob/51c619e5ffe7aaf748e7c34d08c6336762decc74/astropy/io/fits/setup_package.py#L40-L47
but only when using the bundled cfitsio. 
Linux distribution packages are usually using their own cfitsio, you would probably want to do the same for FreeBSD ? http://docs.astropy.org/en/latest/install.html#external-c-libraries

**Comment by yurivict** [comment]
```
$ ikos-scan -vvv make
[.] Running make -e
ikos-scan-c++ -O2 -pipe -fno-omit-frame-pointer -c x.cpp
[.] Running clang++ -O2 -pipe -fno-omit-frame-pointer -c x.cpp
error: unknown argument: '-faddrsig'
*** Error code 1
```

**Comment by yurivict** [comment]
Sorry, it was for a wrong project.

**Comment by kakirastern** [comment]
Hi, I am doing a bit of triaging and noticed that this Issue appear to have been settled. Should this be closed?

**Comment by kakirastern** [comment]
Thanks @yurivict!

**Comment by yurivict** [comment]
You're welcome!
