### ISSUE TITLE
Make the License name in README.rst URL to the License

### ISSUE THREAD

**Issue by agarwalrounak** [astropy/astropy#8378]
[README.rst](https://github.com/astropy/astropy/blob/master/README.rst) mentions that `Astropy is licensed under a 3-clause BSD style license - see the LICENSE.rst file.`
`3-clause BSD style license` could be linked to https://opensource.org/licenses/BSD-3-Clause and `LICENSE.rst` could link to https://github.com/astropy/astropy/blob/master/LICENSE.rst

Additionally, we could also link `docs/install.rst` in [README.rst](https://github.com/astropy/astropy/blob/master/README.rst) to https://github.com/astropy/astropy/blob/master/docs/install.rst. It would make it easy to navigate to the required file.

**Comment by agarwalrounak** [comment]
I think this should be a `good first issue` and I would like to work on it.

**Comment by pllim** [comment]
I think the README is meant for people who downloaded the tarball and reading it in unrendered format. At least the way those files are presented in the text made me think so. If that is the case, adding extra markups for linking is just going to make the unrendered version harder to read. 🤷‍♀️

**Comment by bsipocz** [comment]
I don't think we want to do any linking to an outside BDS-3 template, after all we have our own licence file. Whether to link that from the README or not I don't have strong opinions about, but slide to agree with @pllim. Whoever looks at the rendered README on github can just scroll up for the licence file, and others looking into it from the tarball can gain nothing with it being marked up.

**Comment by bsipocz** [comment]
For good first issues I would suggest to look at the currently labeled ones. Relevant links:

https://github.com/astropy/astropy/labels/good%20first%20issue
https://github.com/astropy/astropy/labels/Package-novice

**Comment by kakirastern** [comment]
Hi, I am doing a bit of triaging and noticed that this Issue appears to have been settled, at least on the surface. Should this be closed for the time being?

**Comment by bsipocz** [comment]
Thank you @kakirastern, indeed this can be closed!

**Comment by kakirastern** [comment]
@bsipocz You are welcome. (Trying to help push down the total issues count, hopefully am not being too helpful.) 

Cheers! 😃

**Comment by bsipocz** [comment]
> Trying to help push down the total issues count

🎉  I can't applaud enough for that effort. Thanks!
