### ISSUE TITLE
Ode0 check in LambdaCDM._elliptic_comoving_distance_z1z2 

### ISSUE THREAD

**Issue by montanari** [astropy/astropy#8388]
Hi,

I think that the [following line](https://github.com/astropy/astropy/blob/62c73d847f98c87319b98260053711165ae6982a/astropy/cosmology/core.py#L1794):
```python
elif (0 < b) and (b < 2) and self._Om0 > self.Ol0:
```
should be replaced by
```python
elif (0 < b) and (b < 2) and self._Om0 > self._Ode0:
```
( `self.Ol0` is not defined).

Best,
Francesco

**Comment by bsipocz** [comment]
@montanari - would you be interested in opening a PR for it? It will also need a regression test, an example where the current code is failing but that works as expected with the fix. Thank you.

**Comment by montanari** [comment]
Sure, done.

Francesco
