### ISSUE TITLE
astropy units for blackbody_lambda does not do proper si conversion

### ISSUE THREAD

**Issue by ysBach** [astropy/astropy#8398]
If I run the following code, it correctly converts the unit "bar" to SI:
```python
from astropy import units as u

test = 1 * u.bar
print(test)
print(test.si)
# 1.0 bar
# 100000.0 N / m2
```

But for ``blackbody_lambda``, it fails to convert the result to correct si unit:
```python
from astropy import units as u
from astropy.modeling.blackbody import blackbody_lambda

testB = blackbody_lambda(1 * u.um, 100 * u.K)
print(testB)
print(testB.si)
print(testB.to('N/s/m^2/sr'))
# 3.8960173143757327e-56 erg / (Angstrom cm2 s sr)
# 3.896017314375732e-54 bar / (rad2 s)
# 3.896017314375732e-49 N / (m2 s sr)
```
That is, astropy does not convert ``bar`` to ``N/m^2`` (which gives factor of 10^5 difference).

I tested with some other complicated combinations, e.g., ``test = 1 * u.cm * u.bar / u.sr * u.erg``, but the SI conversion worked just fine.
Maybe the failure is only for ``blackbody_lambda``..?

**Comment by MSeifert04** [comment]
Thank you for the report @ysBach , just a quick question: what astropy version are you using?

**Comment by ysBach** [comment]
@MSeifert04 Oh, sorry. I am using version 3.1.1:
```python
import astropy
print(astropy.__version__)
# 3.1.1
```

**Comment by pllim** [comment]
I don't think this is a bug in blackbody per se. The SI conversion maps `J / m3` to `Pa` (and `bar` is `1e5 * Pa`). When we're talking about flux, it makes more sense to have `testB.si` return something like `J / (m3 rad2 s)`, no? For now, you can force this manually:

```python 
>>> testB.to(u.J / (u.m ** 3 * u.s * u.rad ** 2))
<Quantity 3.89601731e-49 J / (m3 rad2 s)>
```

p.s.Astronomy calculating flux in SI units? That's crazy talk!

**Comment by kakirastern** [comment]
Hi, I am triaging and noticed that some level of closure might have been reached... Should this issue be closed for now and a new issue be opened should a similar problem arise? 

I second @pllim's observation: This does not look like a bug to me, but rather some kind of rigidity in the default units adopted in the `.si` units conversion mechanism. Maybe in the future some sort of flexibility could be introduced to the overarching scheme of unit conversion to suit the user's needs better? But that would be a separate issue.

**Comment by pllim** [comment]
@mhvk, what do you think?

**Comment by mhvk** [comment]
I do think this `.si` decomposition is not particularly helpful, even if it is not strictly a bug.  @kakirastern is correct that it arises from the `unit` system: basically it picks whatever equivalent unit combination has the fewest number of bases. Though it could have been `W / (m3 rad2)`, which would be better (but apparently comes by later).

Possible ways to resolve: might help to just shift around units in `si.py` (i.e., move "POWER" before "PRESSURE"), at least on python >=3.6, where things go by insertion order. Worth a try...

Alternatively, we could define "preferred decompositions", perhaps by physical type, i.e., if something has a physical type other than "unknown", we use the corresponding unit. Not exactly sure what the physical type would have to be, though.

**Comment by pllim** [comment]
@mhvk , but adding a preference system is like naming a favorite child. It is tough to make everyone happy.

**Comment by mhvk** [comment]
Very much so. Though `bar/rad2` just doesn't make sense! If someone has the time, I'd do the swap of power and pressure in `si.py` and see if that helps...

**Comment by pllim** [comment]
@mhvk , I did the swap locally, installed my patch, but it made no difference.

**Comment by mhvk** [comment]
Hmm, puzzling. I guess I misunderstood how ordering works for equal number of units.

**Comment by karllark** [comment]
This is definitely a units issue, not a modeling issue.  At a minimum, the modeling tag should be removed.  Reading through the comments, it also sounds like this might be a preference decision and the issue could probably be closed.

```
import astropy.units as u

tunit = 1.0 * u.erg / (u.cm ** 2 * u.AA * u.s * u.sr)
print(tunit)
print(tunit.si)
print(tunit.to('N/s/m^2/sr'))
```
Results in:
> 1.0 erg / (Angstrom cm2 s sr)
> 99.99999999999999 bar / (rad2 s)
> WARNING: UnitsWarning: 'N/s/m^2/sr' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
> 9999999.999999998 N / (m2 s sr)

**Comment by mhvk** [comment]
Indeed, it is a `units` issue - I removed `modeling`. I guess it is mostly about the default rule for simplifying units for `.si` breaking down for flux density. I think it would be best to somehow go through `physical_type`, but right now `tunit.unit.physical_type` gives 'unknown', so that needs work.  Anyway, will leave the issue open for now.

**Comment by mhvk** [comment]
Cross reference #6093 - that the units registry doesn't know about composite units well enough.

**Comment by dhomeier** [comment]
And in `cgs` it's converting to Barye – which quite correctly is `dyne/cm**2`, but I bet is qualified to cause even more confusion...
```
>>> tunit.si
Unit("100 bar / (rad2 s)")
>>> tunit.cgs
Unit("1e+08 Ba / (rad2 s)")
```

**Comment by mhvk** [comment]
closing in favour of #11532 since the example on top does not work any more and the discussion about modeling is a bit misleading.
