### ISSUE TITLE
use of with_calib in EsoClass retrieve_data

### ISSUE THREAD

**Issue by markneeser** [astropy/astropy#8399]
Hi All,

I am interested in using the calSelector functionality in EsoClass retrieve_data.

According to the documentation,

retrieve_data(datasets, continuation=False, destination=None, with_calib='none', request_all_objects=False)

with “with_calib” being either none, raw, or processed for the calibration data associated
with the requested dataset.

However, when using retrieve_data I get an "unexpected keyword argument" error:

data_files = eso.retrieve_data(submit_files, destination=down_dir, continuation=False, with_calib=‘raw')

TypeError: retrieve_data() got an unexpected keyword argument ‘with_calib’

Has this parameter been removed or renamed?

Best of thanks,

Mark

**Comment by pllim** [comment]
I think this should be posted over at https://github.com/astropy/astroquery/issues
