### ISSUE TITLE
Support for APE 14 in WCSAxes

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8409]
This is one of the features listed for 3.2 from Astropy Coordination Meeting 2018.

**Comment by pllim** [comment]
@astrofrog , any chance of this happening before feature freeze?

**Comment by astrofrog** [comment]
Nope, not going to happen unfortunately.

**Comment by Cadair** [comment]
This is effectively blocked on #8546 right?

**Comment by astrofrog** [comment]
Yes, and I'll have time to finish that PR but not then make the changes needed in WCSAxes for 3.2
