### ISSUE TITLE
Move periodogram modules stats to timeseries

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8410]
1. Create `astropy.timeseries`
2. Move periodogram modules over from `astropy.stats` (with backward compatibility for a time), which includes `bls` and `LombScargle`
3. ???
4. Profit!

**Comment by bsipocz** [comment]
@jakevdp, as well as others - Do you have any thoughts on the namespace `LombScargle` should be available from one this refactoring is done?

1) - ``from astropy.timeseries import LombScarge``
2) - ``from astropy.timeseries.periodograms import LombScargle``?

**Comment by larrybradley** [comment]
@bsipocz  How about both (using `__init__`)?   BTW, `lombscarge` and `bts` are both currently subpackages (not modules) under `stats`.

**Comment by bsipocz** [comment]
Honestly either way is fine by me, and only pushing to get a decision as then I can update the imports in the astroML textbook (so users don't get deprecation warnings for the new edition).

**Comment by larrybradley** [comment]
@jakevdp should chime in.  I don't have a strong opinion.

**Comment by jakevdp** [comment]
Sounds fine either way. Are there plans to add more timeseries functionality? Would Bayesian Blocks go in the timeseries module as well?

**Comment by bsipocz** [comment]
The main part will be the TimeSeries class, and we plan to move the two periodograms. Not sure moving the bayesian blocks would make much sense, they are more generic stats tools then these.

**Comment by pllim** [comment]
I think on Slack, @astrofrog said that he will work on this for 3.2 after #8540 is merged?

**Comment by astrofrog** [comment]
I'll try, I'll try...
