### ISSUE TITLE
New SpectralQuantity class

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8411]
Someone wrote down "SpectralQuantity?" in the notes for features to aim for in 3.2 at Astropy Coordination Meeting 2018. I am not very sure what this means. Please elaborate.

**Comment by astrofrog** [comment]
This is discussed in https://github.com/astropy/specutils/issues/422

**Comment by pllim** [comment]
@astrofrog , okay thanks... but how is that issue in `specutils` related to Astropy 3.2 release?

**Comment by astrofrog** [comment]
I think the plan was to implement it in specutils first then transfer it over to the core package whenever it's functional.

**Comment by pllim** [comment]
> whenever it's functional

Is all this gonna happen by April? If not, then we shouldn't aim for 3.2 for this one.
