### ISSUE TITLE
Issue with WCS.wcs.cunit equality

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8415]
The ``WCS.wcs.cunit`` attribute uses a class called ``UnitListProxy`` - and it seems that class doesn't correctly define ``__eq__``:

```
In [47]: wcs = WCS(naxis=2)

In [48]: wcs.wcs.cunit = ['deg', 'm/s']

In [49]: wcs.wcs.cunit == wcs.wcs.cunit
Out[49]: False
```

I think this should be treated as a bug.

**Comment by himanshupathak21061998** [comment]
@astrofrog I want to resolve this bug but I can't able to find definition of class UnitListProxy can you please give some elaboration about this class

**Comment by astrofrog** [comment]
@himanshupathak21061998 - the class is defined in https://github.com/astropy/astropy/blob/master/astropy/wcs/src/unit_list_proxy.c (it's written in C)
