### ISSUE TITLE
Can set func-units (e.g., dex) in Table/Column but not retrieve them

### ISSUE THREAD

**Issue by bwinkel** [astropy/astropy#8424]
First of all, thanks for the awesome `units` sub-package. I use it a lot.

Unfortunately, I keep running into trouble when using logarithmic units (i.e., function units). For example, I would like to use logarithmic units in a `astropy.table.Table`. I can set them without problems, but not retrieve them with the `.quantity` property:

```python
from astropy.table import Table
from astropy import units as u


a = [1., 4., 5.]
b = [2.0, 5.0, 8.2]
t = Table([a, b], names=('a', 'b'))

t['a'].unit = 's'
t['b'].unit = u.dex(u.AA)

t['a'].quantity
# <Quantity [1., 4., 5.] s>
t['b'].quantity
# UnitTypeError: Quantity instances require <class 'astropy.units.core.UnitBase'> units, 
# not <class 'astropy.units.function.logarithmic.DexUnit'> instances.
```

I guess, this has to do with the fact that logarithmic units are not a base class of `UnitBase`.

**Comment by bsipocz** [comment]
@bwinkel - Have you considered using `QTable` rather than `Table`?

That way both your columns would be `Quantities` natively:

```
In [1]: from astropy.table import QTable
   ...: from astropy import units as u
   ...: 
   ...: 
   ...: a = [1., 4., 5.]
   ...: b = [2.0, 5.0, 8.2]
   ...: t = QTable([a, b], names=('a', 'b'))
   ...: 
   ...: t['a'].unit = 's'
   ...: t['b'].unit = u.dex(u.AA)
   ...: 
   ...: 

In [2]: t['a']
Out[2]: <Quantity [1., 4., 5.] s>

In [3]: t['b']
Out[3]: <Dex [2. , 5. , 8.2] dex(Angstrom)>
```

**Comment by bwinkel** [comment]
Hi @bsipocz, that's a good point. For my use case, I could also work with `QTable`, indeed. (The reason why I chose `Table` in the first place was, that I couldn't figure out how to set the format for `QTable` columns.)

Nevertheless, I would still consider it a (minor!) bug that it doesn't work with `Table`, because one can assign function units, they are correctly shown in the `repr` string, and the documentation also doesn't mention that the `quantity` property is restricted to those that are basing `UnitBase`. Since it seems easy to fix (see my PR) - at least if the proposed solution is not entirely stupid for some reason - it couldn't hurt to solve the issue?

**Comment by mhvk** [comment]
Agreed both that `QTable` is the way to go and that, nevertheless, this is a bug.
