### ISSUE TITLE
Masked table writing to ecsv seems very slow

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#8443]
I did some profiling of the ecsv writer in this notebook: https://gist.github.com/98f17dae0bb43f569a09f737a57f5bd7 / https://nbviewer.jupyter.org/gist/eteq/98f17dae0bb43f569a09f737a57f5bd7.  

The gist of that (get it?) is that it appears that ECSV file-writing is at least an order-of-magnitude slower if there are masked columns.  This makes even medium-sized data sets like standard Gaia tables almost impossible to work with: even a few thousand lines can take tens of minutes to write out, while in at least some cases only seconds are required for non-ecsv formats. 

@mhvk or @taldcroft - any insight into the origin of this slowness?

**Comment by taldcroft** [comment]
Sigh.  Will investigate...

**Comment by mhvk** [comment]
I suspect it may have to do with `MaskedArray` itself - for its `__repr__`, it turns an array into an object array, so that it can replace individual elements with an instance that has a repr of "--". This definitely is not fast...

Independently, why use a text format in an analysis path? Wouldn't a loss-less binary format be more appropriate?

**Comment by taldcroft** [comment]
For reference here is a minimal demonstration of the issue:
```
x = np.arange(10000, dtype=float)
tm = Table([x], masked=True)
t = Table([x])
```
Then:
```
In [23]: time tm.write('tm.ecsv', overwrite=True)
CPU times: user 502 ms, sys: 3.09 ms, total: 505 ms
Wall time: 504 ms

In [24]: time t.write('t.ecsv', overwrite=True)
CPU times: user 54.5 ms, sys: 1.53 ms, total: 56.1 ms
Wall time: 55.1 ms
```
The output files are identical (by diff).

**Comment by taldcroft** [comment]
Yes, appears to be the MaskedArray repr.  Even more minimally:
```
In [27]: time y = [str(x) for x in tm['col0']]
CPU times: user 416 ms, sys: 1.23 ms, total: 417 ms
Wall time: 416 ms

In [28]: time y = [str(x) for x in t['col0']]
CPU times: user 9.26 ms, sys: 202 µs, total: 9.46 ms
Wall time: 9.45 ms
```
Zounds.

**Comment by taldcroft** [comment]
So you can recover the non-masked performance (mostly) by telling the writer to serialize masked data with two columns (the data and the mask).  Then it uses the non-masked version of data and it is fast(er).
```
In [39]: time tm.write('tm.ecsv', overwrite=True, serialize_method='data_mask')
CPU times: user 76.2 ms, sys: 3 ms, total: 79.2 ms
Wall time: 78.2 ms
```
The annoying caveat is that the code tries to be clear and not bother with the separate mask column if the mask is `False` everywhere.  So if the data column is masked but there are no masked elements, it falls through to the standard MaskedArray repr and is slow.  So I could probably put in code to work around that and serialize the array data `tm['col0'].data.data` in that case.
