### ISSUE TITLE
Table performance issues: more meta and sorting 

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8452]
A simple `Table.sort` call results in **6** deep copies of the meta being made.  It stems a bit from the liberal use of code like `self[keys]`, which seems elegant and lightweight but in fact does a meta deep copy and a bunch more.  Even a simple `argsort` just blindly does `self[keys]` (triggering another deepcopy) even for the most common case when `keys` is just a single column.
```
t = simple_table()
t.meta = {1:2, 3:4, 5:6, 7:8, 9:10}
t.sort('a')
```
Related to #8404.  I am working with tables that have a lot of stuff in meta and this is making a problem.  This is really annoying me and will hopefully result in some more PRs.

**Comment by himanshupathak21061998** [comment]
@taldcroft To solve this I need to replace `self[keys]` in `argsort()` and `sort()`

**Comment by taldcroft** [comment]
@himanshupathak21061998 - I haven't looked into `argsort()` and `sort()` in detail nor done profiling. Getting rid of some `self[keys]` is low-hanging fruit that might help, particularly with a large meta dict.  But of course profiling is key to make sure that the added code complexity is worth it.

**Comment by himanshupathak21061998** [comment]
@taldcroft Ok so after replacing I will do some profiling can I do this before GSOC announcement. Sorry for late reply
