### ISSUE TITLE
Negative powers in Lomb-Scargle periodogram

### ISSUE THREAD

**Issue by warrickball** [astropy/astropy#8454]
I've been using Astropy's Lomb-Scargle periodogram for some time but just run into an unexpected scenario. I've attached a simple series of 19440 points of Gaussian noise ([WN_1000_timeseries.txt](https://github.com/astropy/astropy/files/2901007/WN_1000_timeseries.txt)), generated using `1000*numpy.random.randn(19440)`. When I compute the Lomb-Scargle periodogram, however, the second-last element has negative power. I was under the impression that this wasn't possible but I appreciate that I may well be wrong, in which case this issue can be resolved by me understanding the LS periodogram better!

The timeseries is attached and this snippet of code produces the negative value for me.

```python
import numpy as np
from astropy.stats import LombScargle

y = np.loadtxt('WN_1000_timeseries.txt')
f, p = LombScargle(np.arange(len(y), dtype=float), y, center_data=False).autopower(normalization='psd', samples_per_peak=1, nyquist_factor=1)
print(p[-2]) # -2493.908823582499
```

I'm running Python 3.7.2 on Fedora 29, with NumPy 1.16.0 and Astropy 3.1.2.

**Comment by bsipocz** [comment]
cc @jakevdp

**Comment by jakevdp** [comment]
The default computational approach is an approximation that speeds the algorithm from ``O[N^2]`` to ``O[N log N]``, at the expense of not producing exact results. For values close to zero, this approximation can lead to negative powers.

If exact results are important to you, you can specify the ``method`` argument of the ``autopower`` function to something other than ``"fast"``.

**Comment by mhvk** [comment]
@warrickball - did this answer your question? If so, could you suggest a place where the documentation might be improved which you would have found?

**Comment by astrofrog** [comment]
Would it make sense to emit a warning if a negative power is returned, with a message to the effect that this can happen in the fast mode and to try another one?

**Comment by jakevdp** [comment]
I'm -1 on using a warning. The experience with the Bayesian Blicks warning has showed us that it confuses an order of magnitude more users than it helps.

**Comment by warrickball** [comment]
@jakevdp's explanation answers the question, so I don't mind if someone closes this.

I'd have appreciated a note on the precision of the `fast` method though. Personally, I might expect such a description at least in the [Periodogram algorithms](http://docs.astropy.org/en/stable/stats/lombscargle.html#periodogram-algorithms) section. If the `fast` method is commonly used (I haven't experimented with how `auto` decides), then it might be worth mentioning more prominently too (e.g. in the lead text of the [Lomb-Scargle page](http://docs.astropy.org/en/stable/stats/lombscargle.html)).

It also looks like getting negative power is a bit of bad luck. I've generated about a dozen more sequences of white noise without getting negative power but now that I'm aware of the approximate nature of the `fast` method, I'll stick to the others. I seem to get fractional differences between `fast` and `cython` of order ~1 per cent at the high frequency end, and clearly scaling with frequency. e.g.

```python
import numpy as np
import matplotlib.pyplot as pl
from astropy.stats import LombScargle

y = np.random.randn(19440)
t = np.arange(len(y), dtype=float)
fslow, pslow = LombScargle(t, y).autopower(normalization='psd', samples_per_peak=1, nyquist_factor=1, method='cython')
ffast, pfast = LombScargle(t, y).autopower(normalization='psd', samples_per_peak=1, nyquist_factor=1, method='fast')
pl.loglog(fslow, np.abs(pfast/pslow-1.))
```

Thanks!

**Comment by mhvk** [comment]
Agreed with not having warnings. 

@warrickball - I like your suggestions for places where the documentation could be improved, and also think it would be helpful to have a sense of what uncertainties one gets from the fast method (note that 1% in the power is amply good enough for most purposes - powers are chi2 distributed and their uncertainties generally will be substantially larger than 1%). Would you be willing to make a PR to do this? (It is not that hard, though if you haven't done it before a bit of a learning curve.) Alternatively, could you open a new issue with this suggestion? This is a good first issue for people who want to contribute.

**Comment by warrickball** [comment]
@mhvk I'm happy to try to make a PR to add the documentation. I'm familiar with GitHub and have made one or two PRs so I've hopefully already climbed some of the learning curve.

FWIW, I also found the "extirpolation" parameter that (partly) controls the approximate FFT mesh (keyword arg `M` in [extirpolate](https://github.com/astropy/astropy/blob/master/astropy/stats/lombscargle/implementations/utils.py#L14)) via `LombScarge.autopower(..., method_kwds={'trig_sum_kwds': {'Mfft': 4}})`. Using `{'Mfft': 16}` seems to decrease the uncertainties everywhere.

**Comment by jakevdp** [comment]
For what it's worth, I don't think 1% inaccuracies at high frequencies are worth worrying about. In practice, the signal at such frequencies is so dominated by aliasing effects that a 1% inaccuracy is not going to make any substantive difference in the interpretation of periodograms.

**Comment by mhvk** [comment]
@warrickball - great! Looking forward to it!
