### ISSUE TITLE
3.1.2 on pypi: signature missing

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#8455]
Hi,

there is the new bugfix release available on PyPI, but the signature is missing. Could it be added? It would be nice to ensure the integrity of the package.

Best

Ole

**Comment by pllim** [comment]
AFAIK it is impossible to add a signature after the fact.

**Comment by bsipocz** [comment]
Hmm, this is weird. 
Could you check again? I've redid the signing and upload, but don't see where the signatures are accessible on the new interface (https://pypi.org/project/astropy/3.1.2/#files)

**Comment by olebole** [comment]
@bsipocz I use a debian service for download, which takes the data from the Pypi JSON API. Looking into the [JSON](https://pypi.org/pypi/astropy/json), I still find `has_sig: false` (and an upload date 2019-02-24T01:15:57).
For simplicity, could you attach the signature to this issue? I could take it from here as well ;-)

**Comment by bsipocz** [comment]
I needed to zip it otherwise github complained the file type is not being supported.

[astropy-3.1.2.tar.gz.asc.gz](https://github.com/astropy/astropy/files/2902210/astropy-3.1.2.tar.gz.asc.gz)

**Comment by olebole** [comment]
@bsipocz Thank you! This helped me (and the version + signature is now uploaded to Debian).

**Comment by bsipocz** [comment]
I'm sorry about this, not exactly sure how/why I didn't sign it as I always do.

**Comment by bsipocz** [comment]
(I'm also closing this as I don't think there is much we can do. I tried to upload the signature but as @pllim said it looks like it's not possible now after the fact).
