### ISSUE TITLE
Consider making warnings PEP 565 compliant

### ISSUE THREAD

**Issue by Juanlu001** [astropy/astropy#8465]
[PEP 565](https://www.python.org/dev/peps/pep-0565/), accepted in 3.7, redefined the semantics of several types of warnings. In particular:

> For library and framework authors that want to ensure their API compatibility warnings are more reliably seen by their users, the recommendation is to use a custom warning class that derives from `DeprecationWarning` in Python 3.7+, and from `FutureWarning` in earlier versions.

Which means that `AstropyDeprecationWarning` is maybe not as visible as we think, and perhaps it should derive from `FutureWarning` in Python < 3.7.

**Comment by pllim** [comment]
Oh, looks like we were too ahead of our times?

Or... if we keep this open long enough such that our minversion of Python is 3.7, we can just close this without action. :trollface:

**Comment by mhvk** [comment]
My vote would be to let python catch up with us...

**Comment by bsipocz** [comment]
> My vote would be to let python catch up with us...

and it wouldn't be the first time :trollface:

**Comment by bsipocz** [comment]
I'm 👎 on hacking in anything for Python <3.7 now, much of our downstream ecosystem relies on `enable_deprecations_as_exceptions`, changing to subclass from `FutureWarning` rather than from DeprecationWarning may cause issues there.

**Comment by bsipocz** [comment]
I'm closing this now. Our machinery is now catching both type of warnings, and there is no inclination to change the behaviour of our deprecations based on the python version we're using.
