### ISSUE TITLE
WCSAxes get_coords_overlay does not accept 'pixel' as argument and has no docstring

### ISSUE THREAD

**Issue by kgabor** [astropy/astropy#8466]
I'm trying to add both pixel and WCS coordinates to a plot with [this example file](https://raw.githubusercontent.com/lsst-dm/diffimTests/astropy_7180/astropy_7180/test.fits). 
Following the examples in the WCSAxes documentation, I tried:

```python
from astropy.io import fits
from astropy.wcs import WCS
import matplotlib.pyplot as plt

hdu = fits.open('test.fits')[1]

wcs = WCS(hdu.header)

plt.subplot(projection=wcs)
plt.imshow(hdu.data, origin='lower')
ax=plt.gca()
ax.coords['ra'].set_ticklabel_position('l')
ax.coords['ra'].set_axislabel('RA')

ax.get_coords_overlay('pixel')
```
(Please note the 'RA" label misplacement relates to #7180 .)

It gives a ValueError:
```
/wcsaxes/core.py in get_coords_overlay(self, frame, coord_meta)
    414         else:
    415             if coord_meta is None:
--> 416                 coord_meta = get_coord_meta(frame)
    417             transform = self._get_transform_no_transdata(frame)
    418             coords = CoordinatesMap(self, transform=transform,

/wcsaxes/utils.py in get_coord_meta(frame)
    109         frame = frame_transform_graph.lookup_name(frame)
    110         if frame is None:
--> 111             raise ValueError("Unknown frame: {0}".format(initial_frame))
    112 
    113     if not isinstance(frame, BaseCoordinateFrame):

ValueError: Unknown frame: pixel
```

Though WCSAxes.get_coords_overlay does not have any docstring, the code and the docs of get_transform suggests that it should support _pixel_ as a coords overlay.

**Comment by pllim** [comment]
Just for the record, what are your Python, astropy, numpy, matplotlib, etc versions?

**Comment by kgabor** [comment]
python: 3.6.6, numpy: 1.14.5, matplotlib: 2.2.2, astropy: 3.0.3

**Comment by pllim** [comment]
Gotta code dive a bit but it appears `'pixel'` is not one of the options.
```python
>>> from astropy.coordinates.baseframe import frame_transform_graph
>>> frame_transform_graph.get_names()
['precessedgeocentric',
 'cirs',
 'altaz',
 'galactic',
 'galacticlsr',
 'hcrs',
 'gcrs',
 'galactocentric',
 'supergalactic',
 'itrs',
 'fk4noeterms',
 'heliocentrictrueecliptic',
 'icrs',
 'lsr',
 'barycentrictrueecliptic',
 'fk4',
 'fk5',
 'geocentrictrueecliptic']
```

@astrofrog ?

**Comment by bsipocz** [comment]
Without looking at the source code suggested it was based on this docstring: http://docs.astropy.org/en/stable/api/astropy.visualization.wcsaxes.WCSAxes.html#astropy.visualization.wcsaxes.WCSAxes.get_transform

**Comment by pllim** [comment]
Definitely can use more helpful doc here.
