### ISSUE TITLE
Tighten flake8 check

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8470]
I would like to get the flake8 test to be a bit more strict so we would avoid adding unused imports, etc.
There is less and less low hanging fruits in core, so asking to set up some good measures for a consistent code style shouldn't be as big an issue now as it was a couple of years ago.

https://github.com/astropy/astropy/pull/8469

**Comment by pllim** [comment]
Unused imports should be removed rather carefully, though. I vaguely remember some were added on purpose for one reason or another.

**Comment by bsipocz** [comment]
Yes,  I don't mean to do this blindly, but once the current warnings are cleared with "noqa" statements, then adding the check would make sense.
