### ISSUE TITLE
reference plane in heliocentrictrueecliptic

### ISSUE THREAD

**Issue by mzechmeister** [astropy/astropy#8476]
When I calculate the heliocentric coordinates of Earth, I obtain non-zero latitudes:
```python
from astropy.time import Time
from astropy.coordinates import get_body

get_body('earth', Time(range(1999, 2099, 10), format='decimalyear')).heliocentrictrueecliptic.lat
```
returns
```
<Latitude [ 0.00031358, -0.00108112, -0.00268567, -0.00366414, -0.00466174,
           -0.00604799, -0.00773513, -0.00874755, -0.00982753, -0.01100577] deg>
```

The center of the coordinate system is the Sun as given in doc (http://docs.astropy.org/en/stable/api/astropy.coordinates.HeliocentricTrueEcliptic.html#astropy.coordinates.HeliocentricTrueEcliptic).

But what is reference plane? I would expect that the Earth or the barycenter of Earth-Moon are in this plane and therefore have zero latitude. But it seem this is not exactly the case.
So why is the latitude decreasing?

**Comment by pllim** [comment]
@adrn ?

**Comment by fardal** [comment]
This is no substitute for an authoritative answer, but I speculate that it's precession of the ecliptic plane.

**Comment by StuartLittlefair** [comment]
@fardal is along the correct lines.

The plane of the ecliptic, and the equinox (where the equator and ecliptic meet) both move with time to due to precession and nutation of the Earth, and motion of the ecliptic plane. The ```HeliocentricTrueEcliptic``` has an ```equinox``` parameter, which is used to calculate the position of the ecliptic and the equinox. It defaults to J2000.0 if not specified.

You should use the same time for the equinox as you used for the calculation of the Earth's position. Thus, the following code give latitudes which are much closer to 0. 

```python
In [1]: from astropy.time import Time 
In[2]: from astropy.coordinates import get_body, HeliocentricTrueEcliptic

In [3]: earth = get_body('earth', Time(range(1999, 2099, 10), format='decimalyear'))                                                                    
WARNING: ErfaWarning: ERFA function "dtf2d" yielded 7 of "dubious year (Note 6)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "utctai" yielded 7 of "dubious year (Note 3)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "taiutc" yielded 7 of "dubious year (Note 4)" [astropy._erfa.core]

In [4]: earth.transform_to(coord.HeliocentricTrueEcliptic(equinox=earth.obstime)).lat.to(u.arcsec)                                                    
Out[4]: 
<Latitude [ 0.67514231,  0.17964243, -1.05137553, -0.06849807,  0.9102648 ,
            0.40595321, -1.07390513, -0.25250452,  0.47781654,  0.68298045] arcsec>
```

**Comment by mzechmeister** [comment]
Thanks. It seems to be the explanation.
