### ISSUE TITLE
FixedWidthNoHeader table not splitting on first data line

### ISSUE THREAD

**Issue by fardal** [astropy/astropy#8485]
Is the following routine giving correct behavior?  Output:

``` 
A   B   C 
--- --- ---
  1   2   3
  4   5   6
 A   B   C 
--- --- ---
1 2   3  --
4 5   6  --
```
I thought the `fixed_width_no_header` reader was supposed to split the first data line, but it appears to be splitting the first line instead.

I'm using python 3.6.5, numpy 1.14.5, astropy 3.1.1.

In case this is a bug, I wonder about io/ascii/core.py line 1163, `self.header.get_cols(self.lines)`

```
def testsplit():
    kwds = dict(data_start=1, data_end=3,
                     delimiter=' ', names=['A','B','C'], 
                     format='fixed_width_no_header')
    foo = """x y z
1 2 3
4 5 6
"""   
    print(ascii.read(foo, **kwds))

    foo = """AAA y z
1 2 3
4 5 6
"""
    print(ascii.read(foo, **kwds))
```

**Comment by bsipocz** [comment]
ping @hamogu  @taldcroft

**Comment by hamogu** [comment]
I agree, that looks like a bug. With `data_start=1`, it should not matter at all what's in line 0. Do you want to try a pull request to fix it? If you try and need help along the way, let me know.
