### ISSUE TITLE
Adding/subtracting ABmag Quantities loses the "type" of magnitude

### ISSUE THREAD

**Issue by parejkoj** [astropy/astropy#8487]
The following code raises a `UnitConversionError`, because it appears the math operation lost track of the "type" of magnitude. `fluxMag` and `color` are both `ABmag`, so I would expect their difference to also be an ABmag.

```python
import numpy as np
import astropy.units as u

# color = np.random.random(5)*u.ABmag
color = 10*u.ABmag
flux = 10000
fluxMag = (flux*u.nJy).to(u.ABmag)
diff = fluxMag - color
print(color, fluxMag, diff)
print(diff.to(u.nJy))
```
prints the following, and then raises:
```
10.0 mag(AB) 21.4 mag(AB) 11.399999999999999 mag
...
astropy.units.core.UnitConversionError: '' (dimensionless) and 'nJy' (spectral flux density) are not convertible
```

If the `-` is changed to `+`, the exception is different:

```
10.0 mag(AB) 21.4 mag(AB) 31.4 mag(AB2)
...
astropy.units.core.UnitConversionError: 'AB2' and 'nJy' (spectral flux density) are not convertible
```

**Comment by pllim** [comment]
For the record, what are the Python, Astropy, and Numpy versions used?

**Comment by parejkoj** [comment]
Sorry about that!

python 3.3.6
numpy 1.14.5
astropy 3.0.3

**Comment by pllim** [comment]
@mhvk ?

**Comment by mhvk** [comment]
@parejkoj - this behaviour is as expected: if you add two magnitudes with a unit, you are effectively multiplying the physical quantities and thus their units, while if you substract, you are dividing them. So, for the subtraction, the result is dimensionless and hence you get a regular `mag` output; similarly, if you look carefully at the addition, you'll see that the result has units of `mag(AB2)`, i.e., it is a magnitude of a quantity that has units of AB**2.

See also the section on [arithmetic](http://docs.astropy.org/en/latest/units/logarithmic_units.html#arithmetic-and-photometric-applications) in the documentation.

Hope this helps!

**Comment by parejkoj** [comment]
Yes, I'm an idiot. Classic PEBCAK. In my case, `color` is a dimension less magnitude (duh!), so the code should have read:

```
color = 10*u.mag
flux = 10000
fluxMag = (flux*u.nJy).to(u.ABmag)
diff = fluxMag - color
print(color, fluxMag, diff)
print(diff.to(u.nJy))
```

I don't normally think of magnitudes as having units, but AB magnitudes absolutely do. I wonder if the resulting error message could make this more obvious for the slower among us (like me)?

**Comment by mhvk** [comment]
OK, no worries - I've certainly done similarly...

On the error message: I guess you are right, within the `Magnitude` (or perhaps `LogQuantity` class) error path we could special-case the dimensionless magnitude to a regular unit case, and add something like "Did you perhaps subtract magnitudes so the unit got lost?". But I'm not quite sure what exactly it would be - PR very welcome!!

**Comment by parejkoj** [comment]
I looked into this a little bit during the coworking hour this morning, but I can't figure out where such a customized exception would live. I would suggest appending your text above to the end of the regular exception message.

**Comment by mhvk** [comment]
Possibly would make most sense as a `try/except` around the trial to convert to a regular unit: https://github.com/astropy/astropy/blob/master/astropy/units/function/core.py#L256

**Comment by parejkoj** [comment]
PR #8519 is an attempt at making the message better. I will try to clean it up to merge at the next coworking morning telecon.
