### ISSUE TITLE
Typo in catalog matching documentation

### ISSUE THREAD

**Issue by kadrlica** [astropy/astropy#8490]
The catalog matching documentation [here](http://docs.astropy.org/en/stable/coordinates/matchsep.html#matching-catalogs) and [here](https://github.com/astropy/astropy/blob/master/docs/coordinates/matchsep.rst#matching-catalogs) has the following block:
```
>>> max_sep = 1.0 * u.arcsec
>>> idx, d2d, d3d = c.match_to_catalog_3d(catalog)
>>> sep_constraint = idx < max_sep
>>> c_matches = c[sep_constraint]
>>> catalog_matches = c[idx[sep_constraint]]
```
I'm pretty sure the third line should be something like:
```
>>> sep_constraint = d2d < max_sep
```
and the fifth line should be:
```
>>> catalog_matches = catalog[idx[sep_constraint]]
```
It looks like this example is a fairly new addition [here](https://github.com/astropy/astropy/commit/44a86dc3acbcbc055f07a439503d2a98954d9cff). I'll submit a PR, but pinging @johnnygreco and @eteq for confirmation.

**Comment by johnnygreco** [comment]
Oops, yes `d2d < max_sep` is correct. Thanks!

**Comment by kadrlica** [comment]
Thanks @johnnygreco. I think there is also a typo in the fifth line (I've edited my earlier post).

**Comment by johnnygreco** [comment]
Indeed, that's an important one. Nice catch!
