### ISSUE TITLE
Temperature Conversion

### ISSUE THREAD

**Issue by CyberDrudge** [astropy/astropy#8504]
How to convert between temperatures? It seems to do something with `units.temperature()` but i cant find any example of it, can someone please guide me how can i convert from Kelvin to Celsius or vice-versa.

**Comment by damian-anslik** [comment]
`
from astropy import units as u
`
`
x = 0*u.Celsius
`
`
x_Kelvin = x.to(u.K, equivalencies = u.temperature())
`

**Comment by CyberDrudge** [comment]
@damian-anslik Thanks for the quick reply. Wont it be better if we add an example like this in the docs?

**Comment by pllim** [comment]
Feel free to add a new section to http://docs.astropy.org/en/latest/units/equivalencies.html .

**Comment by yashkmr99** [comment]
Hi! I'd like to take this for my first issue if it's not taken.

**Comment by CyberDrudge** [comment]
@yashkmr99 I was thinking to add this, but you can take it. Go ahead.

**Comment by Himanshu-Garg** [comment]
Is anyone doing this

**Comment by bsipocz** [comment]
@Himanshu-Garg - There are already 2 other people interested in this very recently, please give them a chance in the next couple of days to open a PR. In the meantime I suggest you look at the other `package-novice` issues.

**Comment by yashkmr99** [comment]
I've edited the respective .rst file and have got `sphinx-astropy` already installed. When I try `python setup.py build_docs`, it says:

> Extension error:
Could not import extension sphinx_gallery.gen_gallery (exception: No module named 'matplotlib')
Sphinx Documentation subprocess failed with return code 2

**Comment by pllim** [comment]
This was done in #8508
