### ISSUE TITLE
astropy.nddata.utils.add_array fails when small_array has shape with length equal to large_array

### ISSUE THREAD

**Issue by Onoddil** [astropy/astropy#8513]
Before passing to ``astropy.nddata.utils.overlap_slices``, ``astropy.nddata.utils.add_array`` checks for the larger array being larger than the smaller array by ``if all(large_shape > small_shape for (large_shape, small_shape) in zip(array_large.shape, array_small.shape)):``. However, I think this should likely be ``large_shape >= small_shape`` to allow for equal size array adding. 

``overlap_slices`` can handle equal shape arrays, but ``add_array`` cannot:

```
from astropy.nddata.utils import overlap_slices, add_array
import numpy as np
a = np.arange(30).reshape(5, 6)
b = overlap_slices(a.shape, a.shape, tuple((q - 1)/2 for q in a.shape))
print(np.all(a == a[b[0]]))
c = add_array(a, a, tuple((q-1)/2 for q in a.shape))
```
giving ``True`` and ``ValueError: Can't add array. Small array too large.``.

Was there a deliberate decision to enforce ``add_array`` not being able to add two arrays when one length is equal between both arrays, or can this be updated?

**Comment by bsipocz** [comment]
I don't get the ValueError any more, and based on the changelog this indeed has been fixed by #9118
