### ISSUE TITLE
Using io.ascii in other projects

### ISSUE THREAD

**Issue by Sup3rGeo** [astropy/astropy#8515]
Hi,

I would like to use astropy's `io.ascii` module in a testing tool to read tables with the bdd format:

![](https://i.stack.imgur.com/ap99V.png)

However I would not like to make the whole astropy as a dependency for this tool.

I am not very familiar with licenses, can I just copy the `ascii` module into my project? In that case what should I do concerning licenses?

Also, it seems that this package was once an independent one in pypi (https://pypi.org/project/asciitable/), which seems a very good idea to me. I wonder why it was decided to move it integrally into astropy?

Thanks!

**Comment by taldcroft** [comment]
@Sup3rGeo - `io.ascii` is deeply integrated with the rest of the `astropy` core package.  You are free by license to just copy the code into your module (keeping the license intact), but it won't work without the rest of `astropy`.  In particular the output of `io.ascii` is an astropy `Table`.  The ability to take full advantage of the core `astropy` was the original driver for integration.

With modern packaging (wheels, conda), you should not worry too much about installing the full `astropy` package for a test.  It's quite fast and easy, much faster than messing around with decoupling `io.ascii`.

**Comment by astrofrog** [comment]
Just to echo what @taldcroft said, installing astropy is very fast and we've deliberately made it so that it has very few required dependencies (basically only Numpy), so I would highly recommend just adding astropy as a dependency. If you have concerns about doing that, I'd be very interested to hear them to see if there is anything we can do alleviate them.

**Comment by Sup3rGeo** [comment]
Hi guys, thanks for the answer! In the end I decided to read the table using `pandas` (which as already a dependency) to a DataFrame and using `tabulate` to write back to text.

I will close this ticket.
