### ISSUE TITLE
Reverse Table sort 

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#8522]
It would often be practical to be able to reverse the sort of Table. It is doable with `.argsort` but having a shortcut parameter would be handy. Something like `Table.sort(..., reverse=True)`? In pandas the option is `ascending`, which is True by default.

cc @taldcroft

**Comment by taldcroft** [comment]
Plan:
- [ ] Add  a `reverse` keyword arg to `argsort` and `sort`.
- [ ] Write tests for both, using existing tests of these methods as starting points.
- [ ] Verify in particular that the behavior for a [table that has been indexed](https://astropy.readthedocs.io/en/latest/table/indexing.html) is correct.

**Comment by saimn** [comment]
sort is already broken for tables with indices (#6545), but it can probably be tested with other engines.

**Comment by yashkmr99** [comment]
Hi, I'd like to try my hands on this but I'm not sure if I'd be able to write tests without some help. Also, the plan should consist of adding this to documentation too, right?

**Comment by electricSamarth** [comment]
v,opsd c dm./

**Comment by smitj23** [comment]
I want to try this out. Anyone else attempting this?

**Comment by smitj23** [comment]
Is this till open? Anyone else working on it?

**Comment by yashkmr99** [comment]
Hi @smitj23 
I was working on it and I have only got the 'writing tests' part remaining. I suggest you to kindly look for some other issue. Thanks.
