### ISSUE TITLE
Python 3.7 / SkyView: error: db type is dbm.gnu, but the module is not available

### ISSUE THREAD

**Issue by hectorcanovas** [astropy/astropy#8523]
In Python 3.7 (OSX): 
img = SkyView.get_images("XX YY", survey=survey, radius=1*u.degree, cache=False)

Gives me the following error, no matter if cache = False or cache = True.
** Any help/advice with this would be greatly appreciated!:

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-6-82cdeaec6eb0> in <module>
      9 
     10     for label in labels:
---> 11         img = SkyView.get_images("181.6 -76.4", survey=label, radius=1*u.degree, cache=False)
     12         img[0][0].writeto(ndir + '/' + np.str(label.replace(' ', '_')) + '.fits')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astroquery/skyview/core.py in get_images(self, position, survey, coordinates, projection, pixels, scaling, sampler, resolver, deedger, lut, grid, gridlabels, radius, height, width, cache, show_progress)
    205                                                  cache=cache,
    206                                                  show_progress=show_progress)
--> 207         return [obj.get_fits() for obj in readable_objects]
    208 
    209     @prepend_docstr_nosections(get_images.__doc__)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astroquery/skyview/core.py in <listcomp>(.0)
    205                                                  cache=cache,
    206                                                  show_progress=show_progress)
--> 207         return [obj.get_fits() for obj in readable_objects]
    208 
    209     @prepend_docstr_nosections(get_images.__doc__)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astroquery/utils/commons.py in get_fits(self)
    363         and return the file parsed as FITS HDUList
    364         """
--> 365         filedata = self.get_string()
    366 
    367         self._fits = fits.HDUList.fromstring(filedata)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astroquery/utils/commons.py in get_string(self)
    419         if not hasattr(self, '_string'):
    420             try:
--> 421                 with self._readable_object as f:
    422                     data = f.read()
    423                     self._string = data

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py in __enter__(self)
    110         del self.args, self.kwds, self.func
    111         try:
--> 112             return next(self.gen)
    113         except StopIteration:
    114             raise RuntimeError("generator didn't yield") from None

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/utils/data.py in get_readable_fileobj(name_or_obj, encoding, cache, show_progress, remote_timeout)
    190             name_or_obj = download_file(
    191                 name_or_obj, cache=cache, show_progress=show_progress,
--> 192                 timeout=remote_timeout)
    193         fileobj = io.FileIO(name_or_obj, 'r')
    194         if is_url and not cache:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/utils/data.py in download_file(remote_url, cache, show_progress, timeout)
   1010         if cache:
   1011             # We don't need to acquire the lock here, since we are only reading
-> 1012             with shelve.open(urlmapfn) as url2hash:
   1013                 if url_key in url2hash:
   1014                     return url2hash[url_key]

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shelve.py in open(filename, flag, protocol, writeback)
    241     """
    242 
--> 243     return DbfilenameShelf(filename, flag, protocol, writeback)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shelve.py in __init__(self, filename, flag, protocol, writeback)
    225     def __init__(self, filename, flag='c', protocol=None, writeback=False):
    226         import dbm
--> 227         Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
    228 
    229 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dbm/__init__.py in open(file, flag, mode)
     89     elif result not in _modules:
     90         raise error[0]("db type is {0}, but the module is not "
---> 91                        "available".format(result))
     92     else:
     93         mod = _modules[result]

error: db type is dbm.gnu, but the module is not available

**Comment by pllim** [comment]
Looks like you meant to open this at `astroquery`, not `astropy`.
