### ISSUE TITLE
numpy.int64 doesn't decompose input

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#8527]
I didn't see this in the known issues, but @abonaca and I noticed that with numpy 1.15.4 + astropy 3.1.2:

```python
>>> np.int64((15*u.km) / (15*u.imperial.foot))
1
>>> np.int((15*u.km) / (15*u.imperial.foot))
3280
```

Any thoughts @mhvk?

**Comment by MSeifert04** [comment]
Was `np.int` intentional? Because `np.int` is just Pythons normal `int` type.

**Comment by mhvk** [comment]
@MSeifert04 is right: the difference is that `np.int` just equals python's `int`, which goes through `__index__`, while `np.int64`, `np.int_`, etc., do not go through `__index__` - this also means there sadly is little we can do (except suggest people use `int(...)` if they need an integer).

**Comment by mhvk** [comment]
This requires an upstream fix, though that is tricky enough that we better just document it for now...

**Comment by adrn** [comment]
Whoops, yes, I meant `np.int_` but it was late :) - makes more sense now, but yes, we should at least document this. Thanks @MSeifert04 and @mhvk!

**Comment by disha012** [comment]
I would like to take up this issue, but, I can't figure out where exactly in docs should this be mentioned. Someone please help.

**Comment by pllim** [comment]
@disha012 , known issues are documented at https://github.com/astropy/astropy/blob/master/docs/known_issues.rst . You need to know RST formatting to tackle this issue.
