### ISSUE TITLE
Unnecessary copy in sort, idea about column slicing

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8529]
Performance note, code here uses `self[keys]`, which makes a copy of the data in keys. 

https://github.com/astropy/astropy/pull/8528/files#diff-ac0b34aa951558de733e86f5156c4102L2416

It is more cumbersome, but can be written:
```
self.__class__([self.columns[key] for key in keys], copy=False)
```

In general `self[keys]` should probably have started life off as a no-copy column "slice".  It could be worth adding a keyword to `Table.as_array` to allow selecting a subset of column names.

**Comment by himanshupathak21061998** [comment]
I want to work on this issue

**Comment by pranavastro** [comment]
Can I work on this ?

**Comment by astrofrog** [comment]
@himanshupathak21061998 - please feel free to give it a go!

@pranavastro - maybe let's wait to see if @himanshupathak21061998 can work on it first.

**Comment by himanshupathak21061998** [comment]
I think

> https://github.com/astropy/astropy/pull/8528/files#diff-ac0b34aa951558de733e86f5156c4102L2416

It should lead to this `data = self[keys].as_array()`
I am working on as_array() and adding keyword

**Comment by bsipocz** [comment]
Has been added in #8532
