### ISSUE TITLE
Remove restriction of not copying for init Table from dict 

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8538]
Currently there is a restriction against initializing a Table from dict with copy=False.

https://github.com/astropy/astropy/blob/5c799ebc1e23131f08d36499c276e07cfc7d483e/astropy/table/table.py#L749

This is a relic of when Table was represented by a numpy structured array underneath and can be removed now.

**Comment by broulston** [comment]
Hi, I'd like to take do this as my first contribution. Am I understanding correctly that since now you can use copy=False, that the check just needs to be removed?

**Comment by taldcroft** [comment]
Closed by #8541
