### ISSUE TITLE
Panning/zooming a wcs plot broken with (unreleased) Matplotlib 3.1.0

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#8545]
### Description
Zooming or panning a plot with a wcs projection is broken with the current master branch of Maptlotlib, that should shortly be released as version `3.1.0`. I am aware that this is not the best bug report, but I thought I'd leave it anyway as a placeholder for fixing at some point.

**This might  be an upstream Maptlotlib issue.**

### Steps to Reproduce

1. Install Matplotlib master branch
2. Run the following code:
```python
from matplotlib import pyplot as plt
from astropy.io import fits
from astropy.wcs import WCS
from astropy.utils.data import get_pkg_data_filename

filename = get_pkg_data_filename('tutorials/FITS-images/HorseHead.fits')

hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)

fig = plt.figure()
fig.add_subplot(111, projection=wcs)
plt.imshow(hdu.data)
plt.show()
```
3. Try to zoom/pan

Error message is:
```python
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 743, in array_split
    Ntotal = ary.shape[axis]
AttributeError: 'NoneType' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/cbook/__init__.py", line 216, in process
    func(*args, **kwargs)
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/backend_bases.py", line 2791, in press_pan
    if (x is not None and y is not None and a.in_axes(event) and
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/axes/_base.py", line 2126, in in_axes
    return self.patch.contains(mouseevent)[0]
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/patches.py", line 144, in contains
    Path, np.split(vertices, idxs), np.split(codes, idxs))), {}
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 850, in split
    res = array_split(ary, indices_or_sections, axis)
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 745, in array_split
    Ntotal = len(ary)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 743, in array_split
    Ntotal = ary.shape[axis]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by MSeifert04** [comment]
There is no astropy in the traceback. Is this an astropy issue?

**Comment by astrofrog** [comment]
I guess the question is whether this works correctly without ``projection=wcs``?

**Comment by dstansby** [comment]
Creating a figure without `projection=wcs` works fine.

**Comment by pllim** [comment]
But we test against matplotlib dev, how did we not catch this earlier? :scream: 

https://travis-ci.org/astropy/astropy/builds/514641901

**Comment by dstansby** [comment]
I don't think Matplotlib `3.1` has any pip installable release candidates yet so that might be why (unless the tests install the bleeding edge `master` branch)?

**Comment by pllim** [comment]
Theoretically, we should be testing against the `master` branch:

https://github.com/astropy/ci-helpers/blob/3761efd421c6de850dfb56b714bc93b0ac2df8e4/travis/setup_dependencies_common.sh#L611-L613

**Comment by dstansby** [comment]
Maybe it's because the bug depends on user interaction (ie. panning/zooming) with a plot?

**Comment by pllim** [comment]
> the bug depends on user interaction

Might very well be. In that case, not sure how to add that to the CI. Also, what Matplotlib backend are you using?

**Comment by dstansby** [comment]
I'm using the `QT5Agg` backend.

**Comment by dstansby** [comment]
Doing a bit of investigating, this bisects to https://github.com/matplotlib/matplotlib/pull/10776 in Matplotlib

**Comment by dstansby** [comment]
This is fixed upstream now.

**Comment by astrofrog** [comment]
@dstansby - thanks for tracking this down!
