### ISSUE TITLE
 Typo in rv-to-gsr documentation

### ISSUE THREAD

**Issue by mtlam** [astropy/astropy#8550]
Apologies from before, I went down the wrong github rabbit hole.

On line 95 of examples/coordinates/rv-to-gsr.py:

    gal = icrs.transform_to(coord.Galactic)

should be

    gal = c.transform_to(coord.Galactic)

**Comment by algo-circle** [comment]
Hello there!
I am working on this issue. It will be resolved soon and I will make a PR for it.

**Comment by adrn** [comment]
Thanks @mtlam and @algo-circle - this is indeed a typo.
