### ISSUE TITLE
TST: Plugin 'xdist' could not be loaded

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8555]
This failure started to happen today for multiple PRs. Example: https://travis-ci.org/astropy/astropy/jobs/515865515

```
pluggy.manager.PluginValidationError: Plugin 'xdist' could not be loaded: (pytest 3.7.4 (/home/travis/miniconda/envs/test/lib/python3.6/site-packages), Requirement.parse('pytest>=4.4.0'))!
```

**Comment by saimn** [comment]
I had the same issue today, it seems that the latest version of pytest-xdist requires pytest>=4.4.0.
I fixed the issue by removing pytest-xdist ;)

**Comment by saimn** [comment]
https://github.com/pytest-dev/pytest-xdist/blob/9fcf8fa636bc69ee6cac9348a6ec20c87f2bb5e4/setup.py#L3

**Comment by sansagara2** [comment]
I had this issue when running a pytest setup. Solved it by upgrading to the latest `pytest-xdist`. `pip install pytest-xdist`.

**Comment by sansagara** [comment]
I had this issue when running a pytest setup. Solved it by upgrading to the latest `pytest-xdist`. `pip install pytest-xdist`.
