### ISSUE TITLE
Bayesian blocks returns a single edge

### ISSUE THREAD

**Issue by zkurtz** [astropy/astropy#8558]
I stumbled on an edge case which is causing problems in my app. First, here's an example of expected behavior:

```python
import numpy as np
from astropy.stats import bayesian_blocks

np.random.seed(0)
values = np.concatenate([np.random.rand(100), 0.5 * np.random.rand(100)])
bins = bayesian_blocks(values)

assert values.min() == bins[0]
assert values.max() == bins[-1]
```
These assertions pass successfully. However, they fail for this edge case:
```python
values = np.array([1,1,1,1,1,1,1,1,2])
bins = bayesian_blocks(values)
bins    # produces array([1.])
```
The "edge" in this case turns out to be the difference between 7 and 8 ones. Deleting just one 1 gives
```python
values = np.array([1,1,1,1,1,1,1,2])
bins = bayesian_blocks(values)
bins    # produces array([1., 2.])
```

EDIT: Snippet formatting

**Comment by pllim** [comment]
Just for the record, what Python, Numpy, and Astropy versions are you using? Thanks for reporting this. If you have a patch, PR is welcome.

**Comment by zkurtz** [comment]
> python 3.7.3
> numpy 1.16.2
> astropy 3.1.2

Also replicated the issue with
> python 3.7.3
> numpy 1.16.2
> astropy 3.2.dev24033
