### ISSUE TITLE
Angle parsing: allow NESW

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#8565]
To specify latitudes and longitudes, it would be really helpful if the angle parsing would
accept specifying N/S, E/W directions. (e.g. as used by wikipedia)

At the moment, this raises an error:

```
In [1]: from astropy.coordinates import Angle                                             
In [2]: Angle('45°55′12″N')
    ValueError: Invalid character at col 9 in angle '45°55′12″N'                                                           
```

**Comment by mhvk** [comment]
:+1: - it needs adapting of the `_AngleParser` class in `angle_utilities.py` - which is not terribly easy but doable and quite stand-alone. I think it would also make sense to ensure that in `Latitude` and `Longitude` only the relevant characters are recognized - which may be a bit trickier. Possibly best might be for the angle parser to return Latitude and Longitude if those letters are present.

**Comment by mhvk** [comment]
I labeled this as a good first issue and package novice, since one doesn't have to know much about astropy itself. But those and "effort low" are true only if one is not a novice to python and understands how parser/lexer systems work.

**Comment by MaxNoe** [comment]
I started looking into this

**Comment by Raahul-Singh** [comment]
Hi I would like to work on this. I am a new developer. Can this be assigned to me?

**Comment by mhvk** [comment]
@Raahul-Singh - contributions are more than welcome!  But we generally do not assign issues to people until there is a concrete PR. (Please do note my comment above about needing to understand the parser/lexer system)

**Comment by Raahul-Singh** [comment]
@mhvk  - 
Thank you for replying. I've spent the last couple of days reading about regex and parser-lexer systems (just the basics for now, I'm afraid). The problem I'm facing is understanding the hierarchy of code in the coordinates module. Do you have any suggestions as to where I should start as a base and build my understanding? I do not want to simply write a new function or modify an existing one without understanding the dataflow. Anyway, thanks again for replying!!

**Comment by mhvk** [comment]
@Raahul-Singh - as @MaxNoe notes, the relevant part is in the `_AngleParse` - the letters would be equivalent to signs (and should probably exclude there being signs as well). I'd strongly recommend first writing some tests!

**Comment by Yoiro** [comment]
Hi @Raahul-Singh , are you still working on this? I'd also like to give it a try

**Comment by Raahul-Singh** [comment]
Hi @Yoiro, I am on it, but I'm facing some difficulties with the parser. Please go ahead and try!

**Comment by DShivansh** [comment]
@MaxNoe does North and South to **DMS** notation change anything or are both the same thing as I cannot find anything similar on google like is there any conversion formula or code.
Please help.

**Comment by MaxNoe** [comment]
@DShivansh 
It's basically a sign.
North is positive latitude, South negative. East is positive longitude, West ist negative longitude.

So `28°45'N`,  `17°53'W` would translate to `28° 45'`, `-17°53'`.

**Comment by DShivansh** [comment]
@MaxNoe oh so N and E are positive and S and W are negative?

**Comment by DShivansh** [comment]
@mhvk I tried to work on this problem and I did something like this

```python
        def t_UINT(t):
            r'\d+[NnSsEeWw]?'

            multiplier = 1
            if t.value[-1] == 'N' or t.value[-1] == 'n' or t.value[-1] == 'E' or t.value[-1] == 'e':
                multiplier = 1
            if t.value[-1] == 'S' or t.value[-1] == 's' or t.value[-1] == 'W' or t.value[-1] == 'w':
                multiplier = -1
            t.value = int(t.value)*multiplier
            return t
```

but I don't know why lexer is not considering the end of regex **[NnSsEeWw]?** and is only passing 
the number for tokenizing can you please tell me what am I doing wrong.

**Comment by mhvk** [comment]
Parsers and lexers are rather tricky - they are much more in pieces than what you have. The implementation would, I think, be a bit like `SIGN`, i.e., add a new `DIRECTION` (or so) to tokens, define a `t_DIRECTION` and add new entries wherever sign is used (`g_generic, etc.). I hope this allows you to figure it out!

**Comment by DShivansh** [comment]
@mhvk I was able to run the lexer but I think there is some problem with my grammar definition can you please help me out with that.
```python
        def p_sign(p):
            '''
            sign : SIGN
                 | DIRECTION
                 |
            '''
            if len(p) == 2:
                if not p[0]:
                    p[0] = float(p[1])
                else:
                    p[0] *= float(p[1])
            else:
                p[0] = 1.0
```

following error comes for the input **'45°55′12″N'**

PLY: PARSE DEBUG START

State  : 0
Stack  : . LexToken(UINT,45,1,0)
Action : Reduce rule [sign -> <empty>] with [] and goto state 7
Result : <float @ 0x1149113f0> (1.0)

State  : 7
Stack  : sign . LexToken(UINT,45,1,0)
Action : Shift and goto state 13

State  : 13
Stack  : sign UINT . LexToken(DEGREE,'°',1,2)
Action : Shift and goto state 24

State  : 24
Stack  : sign UINT DEGREE . LexToken(UINT,55,1,3)
Action : Shift and goto state 31

State  : 31
Stack  : sign UINT DEGREE UINT . LexToken(MINUTE,'′',1,5)
Action : Shift and goto state 38

State  : 38
Stack  : sign UINT DEGREE UINT MINUTE . LexToken(UINT,12,1,6)
Action : Shift and goto state 26

State  : 26
Stack  : sign UINT DEGREE UINT MINUTE UINT . LexToken(SECOND,'″',1,8)
Action : Reduce rule [ufloat -> UINT] with [12] and goto state 42
Result : <float @ 0x115f9da90> (12.0)

State  : 42
Stack  : sign UINT DEGREE UINT MINUTE ufloat . LexToken(SECOND,'″',1,8)
Action : Shift and goto state 45

State  : 45
Defaulted state 45: Reduce using 31
Stack  : sign UINT DEGREE UINT MINUTE ufloat SECOND . None
Action : Reduce rule [dms -> sign UINT DEGREE UINT MINUTE ufloat SECOND] with [1.0,45,'°',55,'′',12.0,'″'] and goto state 3
Result : <tuple @ 0x115f7eeb0> (((45.0, 55, 12.0), Unit("deg")))

State  : 3
Defaulted state 3: Reduce using 2
Stack  : dms . None
Action : Reduce rule [angle -> dms] with [<tuple @ 0x115f7eeb0>] and goto state 1
Result : <tuple @ 0x115f7eeb0> (((45.0, 55, 12.0), Unit("deg")))

State  : 1
Stack  : angle . LexToken(DIRECTION,'1',1,9)
ERROR: Error  : angle . LexToken(DIRECTION,'1',1,9)


P.S. I turned on the debug mode to get the states.

**Comment by mhvk** [comment]
I meant to suggest that you define a new `l_DIRECTION` token and then use it similarly to `SIGN`, but you cannot simply add it (except if direction is given at the start of an angle). It is probably good to think through how the parsing would actually happen.

p.s. Will sign off a bit for now - if this is too tricky, just leave this issue for someone who has a bit more experience with parsers/lexers.

**Comment by DShivansh** [comment]
@mhvk I have defined the `l_DIRECTION`

```python
        def t_DIRECTION(t):
            r'[NnSsEeWw]$'
            if t.value[-1] == 'N' or t.value[-1] == 'n' or t.value[-1] == 'E' or t.value[-1] == 'e':
                multiplier = '1'
            if t.value[-1] == 'S' or t.value[-1] == 's' or t.value[-1] == 'W' or t.value[-1] == 'w':
                multiplier = '-1'

            t.value = multiplier
            return t
```

p.s. I really want to understand parsers and lexers hence I am trying my best to get the concept in my head by solving this issue if someone else solved it then also I can find out where I was doing the error

**Comment by MaxNoe** [comment]
@DShivansh Here is a brilliant talk by David Beazly you might find interesting: https://www.youtube.com/watch?v=zJ9z6Ge-vXs

**Comment by mhvk** [comment]
@DShivansh - I think you mostly will need to now use the new direction token inside `p_generic`, etc.

**Comment by DShivansh** [comment]
> @DShivansh - I think you mostly will need to now use the new direction token inside `p_generic`, etc.

ok

**Comment by DShivansh** [comment]
@mhvk I need to only implement this when the instance is str?
I have implemented this feature for str instance, are there any other instances for which I need to implement this features?

**Comment by mhvk** [comment]
Only for `str`, indeed. If you have something that (mostly) works, so make a PR including some tests - much easier to discuss on the basis of actual code!

**Comment by DShivansh** [comment]
@mhvk have submitted a pr  #9859 pleas look into that.
