### ISSUE TITLE
Remove deprecated io.ascii Reader/Writer and unified I/O interfaces

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8567]
The `Reader` / `Writer` keywords for `io.ascii.read/write` have been deprecated for quite a while.

Likewise Unified I/O formats like `aastex` (instead of `ascii.aastex`) have been deprecated for quite a while.

The 4.0 release would be a good time to clean this up!

**Comment by bsipocz** [comment]
@taldcroft  - Is this still on the table?

**Comment by taldcroft** [comment]
Sure, but I probably don't have time to do it.

**Comment by pllim** [comment]
I started to look into it, but it does not appear to be a simple "just remove the deprecated code" kind of thing. Plain removal of `Reader` from `get_reader()` resulted in horrible test failures, so I am guessing `get_reader` itself needs to be removed as well? This is too involved for me and does not look like anyone else has time, so I am moving the milestone.

**Comment by taldcroft** [comment]
Indeed.  Agreed on moving the milestone.

**Comment by bsipocz** [comment]
I suppose this is off the table for 4.1, so I'm remilestoning.

**Comment by pllim** [comment]
@taldcroft , should we move the milestone again?

**Comment by bsipocz** [comment]
No point in dragging this through the milestones, the issue is not critical. 
It is deprecated now for a while, so the removal can happen in any milestone, if 4.3 is a descoping release then it's ideal, otherwise the 5.0 LTS is good too.
