### ISSUE TITLE
Add Table.pprint_all() and pformat_all() methods

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8576]
Add new `Table` methods `pprint_all()` and `pformat_all()` which are exactly the same as `pprint()` and `pformat()` except that the defaults are `max_width=-1` and `max_lines=-1`.

It's always bugged me that it is somewhat difficult to see the whole table (but of course there is a very good reason that is not the default).

**Comment by broulston** [comment]
Hi @taldcroft, I’d like to take this on!
