### ISSUE TITLE
Improve error message when trying to create an empty table from an empty list

### ISSUE THREAD

**Issue by samaloney** [astropy/astropy#8579]
Trying to create an empty table from an empty list leads to a cryptic error message
```
from astropy.table import Table
Table([])
. . . 
ValueError: Inconsistent data column lengths: set()
```
while `Table([[]])` works.

The most straightforward solution would probably add a check to the start of the https://github.com/astropy/astropy/blob/d871698a015a198162e35033a1b8f15016ef8797/astropy/table/table.py#L770
but looking at the source code it seems that at least one of `data`, `names`, `dtype` or `rows` must be a non-empty list/dict so it might be more useful to check this at the very start of the `__init__`?

**Comment by samaloney** [comment]
Slightly related to https://github.com/astropy/astropy/issues/4567 and https://github.com/astropy/astropy/issues/3811

**Comment by himanshupathak21061998** [comment]
To solve this we only need to change the error message or adding a feature so that ``Table([])`` is accepted.

**Comment by bsipocz** [comment]
https://github.com/astropy/astropy/pull/8647 will fix this.
