### ISSUE TITLE
RA HMS string formatting is wrong?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8581]
http://docs.astropy.org/en/latest/coordinates/formatting.html

```python
>>> from astropy.coordinates import ICRS
>>> from astropy import units as u
>>> c = ICRS(187.70592*u.degree, 12.39112*u.degree)
>>> str(c.ra) + ' ' + str(c.dec)
'187d42m21.312s 12d23m28.032s'
```

@hcferguson stated that it should be 'h' for RA and not 'd'?

**Comment by bsipocz** [comment]
what about `to_string('hmsdms')`?

```
>>> from astropy.coordinates import SkyCoord
>>> from astropy import units as u
>>> c = SkyCoord(187.70592*u.degree, 12.39112*u.degree)
>>> c.to_string('hmsdms')
'12h30m49.4208s +12d23m28.032s'
```

**Comment by mhvk** [comment]
Two reasons:

1. `Longitude` tries to be smart and use the input units:
```
In [8]: coord.Longitude((187.70592*u.degree).to(u.hourangle)).to_string()
Out[8]: '12h30m49.4208s'

In [9]: coord.Longitude(187.70592*u.degree).to_string()
Out[9]: '187d42m21.312s'
```

2. Someone who shall remain unnamed assumed that users want degrees by default for all coordinates. I much prefer hours myself (as well?), but right now one doesn't have a choice; see #6184

Until (2) is solved, one is stuck with @bsipocz's suggestion...

**Comment by adrn** [comment]
I think we can close this, because the formatting isn't "wrong": it was a design decision to use the input unit, and not assume a default because astronomers have different wants and needs (case in point: @mhvk prefers hours, I prefer degrees 😄).

**Comment by pllim** [comment]
> astronomers have different wants and needs

But, but, this is ASTROpy... :trollface: 

Anyways, yeah, I didn't know I can format it in the other way. Thanks, @bsipocz !

**Comment by mhvk** [comment]
@adrn - the design decision for angles is logical - it uses the input unit. For `SkyCoord`, arguably it is not, as it forces a preference upon the user. But that is a different issue...

**Comment by adrn** [comment]
@mhvk Yes, I agree!

**Comment by bsipocz** [comment]
> Anyways, yeah, I didn't know I can format it in the other way. Thanks, @bsipocz !

string parsing leaves you some kind of PTSD so it's easier to remember ;)
