### ISSUE TITLE
Allow astropy.table.join to be used with TimeSeries objects

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8586]
Currently we can't use ``astropy.table.join`` with TimeSeries objects because it only works with non-mixin columns. It would be nice to investigate whether we can get it to work since combining multiple time series in this way would be useful (see https://github.com/astropy/astropy/pull/8540#discussion_r275618617 for an initial discussion)

**Comment by bsipocz** [comment]
I have a deja vu here, and will try to dig up whether it was discussed in another issue or I started to work on it somewhere...

**Comment by bsipocz** [comment]
This has been done!
