### ISSUE TITLE
Converting scalar SkyCoord to length-1 SkyCoord array

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#8593]
I have an use case (in `photutils`) of putting `SkyCoord` objects in a `QTable`.  However, there is an edge case where the `SkyCoord` object could either be scalar (only 1 detected source) or contain an array of coordinates (many detected sources).  The issue is that scalar objects (including `SkyCoord`) cannot be added as a table column.  So I tried `np.atleast_1d(skycoord)`, but that returns a length-1 `ndarray` whereas I want a length-1 `SkyCoord` array (so the table column is always a SkyCoord object regardless of whether it contains 1 or many sources).  So my workaround is a bit ugly:  `SkyCoord(np.atleast_1d(skycoord))`:

```python
>>> import numpy as np
>>> from astropy.coordinates import SkyCoord

>>> sc = SkyCoord(10, 10, unit='deg')  # but could also contain an array of coords
>>> sc1 = np.atleast_1d(sc)
>>> sc1  # not what I want
array([<SkyCoord (ICRS): (ra, dec) in deg
    (10., 10.)>], dtype=object)

>>> sc2 = SkyCoord(np.atleast_1d(sc))
>>> sc2  # good!
<SkyCoord (ICRS): (ra, dec) in deg
    [(10., 10.)]>
```

`sc1` and `sc2` produce different table columns:
```python
>>> from astropy.table import QTable
>>> tbl = QTable()
>>> tbl['col1'] = sc1
>>> tbl['col2'] = sc2
>>> tbl
                       col1                             col2  
                                                          deg,deg 
-------------------------------------------------- ---------
<SkyCoord (ICRS): (ra, dec) in deg
    (10., 10.)>                                     10.0,10.0
```

I always want the column to be a `SkyCoord` object (in the case of 1 or many objects).

I discussed this a bit offline with @eteq and he suggested adding a `atleast_nd(dim)` method to `SkyCoord` objects to turn a scalar `SkyCoord` into a one-element n-dimensional `SkyCoord` array (I like this suggestion).

**Comment by larrybradley** [comment]
The same issue is true for `Time` objects.

**Comment by mhvk** [comment]
The underlying issue is that the table is empty, so it is trying to determine the length from that first data points, and scalar objects do not have a length.

As noted in #8607, there is actually a work-around, though it uses a private method from `ShapedLikeNDArray`: 
```
sc1 = sc._apply(np.atleast_1d)
```

I think given that I've used it regularly inside astropy (e.g., with `np.broadcast_to`) and given the example here, we probably should make this a public method.

Longer term, with the new `__array_function__` protocol that numpy is introducing (experimental now, generally available in 1.17), we can make those shape-changing functions "just work".

**Comment by eteq** [comment]
(moved from #8607):

Now on the actual idea: I think it is wrong to make np.atleast_1d work here - atleast_1d specifically yields ndarrays, not more complex objects like a SkyCoord.

But the real problem is the user-perspective @larrybradley is channeling in #8593. I don't think users would ever discover even a public SkyCoord.apply(np.atleast_1d) as a solution to the problem @larrybradley was actually posing, and similar re: the newaxis trick (because atleast1d and ndmin exist).

We could make our own utility functions *like* `np.atleast_1d`, but I think that's just as un-discoverable.  So that was the motivation for `atleast_nd` as a method on `ShapedLikeNDArray`.

**Comment by mhvk** [comment]
I think we should separate issues here: one issue is trying to create a table with a scalar; the following also doesn't work:
```
t = QTable()
t['a'] = 1
# TypeError: len() of unsized object
```
One could argue that in this case what the user wants is very clear, and just create a length-1 table.

A separate question is to what extend and how we should support array-like operations on our classes. `ShapedLikeNDArray` is meant to make our classes more like `ndarray` by providing similar methods. I personally do not see any reason not to let relevant numpy shape-changing functions work as well; indeed, it is very much the purpose of `__array_function__` to allow anything that looks like an array in some way to reuse numpy functions [1]. 

And of course it is exactly what @larrybradley tried! (Which is not strange: `np.reshape(sc, (-1,))` *does* work already! So, if we can make all numpy shape changing functions "just work", what is wrong with that? To me, it seems much cleaner than adding all those functions as methods (which really are not that discoverable for things like `SkyCoord`: `dir(sc)` gives quite a lot of items already...)

[1] http://www.numpy.org/neps/nep-0018-array-function-protocol.html

**Comment by eteq** [comment]
I didn't realize `np.reshape` already works. That does make the argument stronger... But I guess I'm not convinced that's the right behavior at all for conplex objects like `SkyCoord`? But I guess the fact that @larrybradley tried it is evidence that it *is* a natural thing for a user?

I'm less sold on `t['a'] = 1`, though. I think that's dangerously JavaScript-y in that types get switched  Willy-nilly. I see *lots* of bugs that amount to the user thinking something's an array when it's actually a scalar (or vice versa) and it's a Good Thing:TM: that numpy refuses the temptation to guess and catches that...

**Comment by mhvk** [comment]
I'm also not sure I would want scalars to be recognized automatically...

**Comment by bsipocz** [comment]
I suspect this might have been solved, at least now both produces the same table columns:
```
In [2]: >>> import numpy as np 
   ...: >>> from astropy.coordinates import SkyCoord 
   ...:  
   ...: >>> sc = SkyCoord(10, 10, unit='deg')  # but could also contain an array of coords 
   ...: >>> sc1 = np.atleast_1d(sc) 
   ...: >>> sc1  # not what I want                                                                                                                                             
Out[2]: 
array([<SkyCoord (ICRS): (ra, dec) in deg
    (10., 10.)>], dtype=object)

In [3]: >>> sc2 = SkyCoord(np.atleast_1d(sc)) 
   ...: >>> sc2  # good!                                                                                                                                                       
Out[3]: 
<SkyCoord (ICRS): (ra, dec) in deg
    [(10., 10.)]>

In [4]: >>> from astropy.table import QTable 
   ...: >>> tbl = QTable() 
   ...: >>> tbl['col1'] = sc1 
   ...: >>> tbl['col2'] = sc2 
   ...: >>> tbl                                                                                                                                                                
Out[4]: 
<QTable length=1>
   col1      col2  
 deg,deg   deg,deg 
  object    object 
--------- ---------
10.0,10.0 10.0,10.0
```

Please reopen if I misunderstood the purpose here.

**Comment by mhvk** [comment]
Arrggh, that reminds me of #8610 - really would be lovely if `np.atleast_1d` just worked, and with `__array_function__`, it can...

**Comment by larrybradley** [comment]
@bsipocz One part of this was solved, i.e. adding `sc1` to `Table` looks OK now.  However, `np.atleast_1d` still doesn't work on `SkyCoord`.

**Comment by mhvk** [comment]
Yes, part of #8610. In principle, the `atleast_*` are trivial, but ideally we have a look through more numpy functions to see if they make sense.
