### ISSUE TITLE
Allow specifying the order of operations in AffineTransform

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#8601]
At present, the `AffineTransform` class in `astropy.coordinates` assumes that the order of transformations is "rotation then offset," but we should probably allow this to be set. Alternatively, we could support rotations on either end of the offset (i.e., rotate-offset-rotate) and have the rotations default to `np.eye()`. This would help speed up some of the `FunctionTransformWithFiniteDifference` transformations in the ecliptic frames (see #8394).

**Comment by bsipocz** [comment]
My reading based on #8606 that this can be closed. Reopen if I misunderstood.
