### ISSUE TITLE
Default inner mask values to white 

### ISSUE THREAD

**Issue by manurare** [astropy/astropy#8603]
Working with the SunPy library I have reached code from AstroPy and I have realized that the default color for masked pixels in an image is white. I would like to know if this is an intended behaviour -because when I think of masks I think of black patches- or if it's a bug. 

In the first image it is depicted the default behaviour of the _mlp_normalize.py_ file where the mask is filled in white. Whereas in the second one I changed the inner mask to be black

![bad](https://user-images.githubusercontent.com/43776720/56437451-cbec4980-62df-11e9-8f72-e3df10a094cf.png)
![good](https://user-images.githubusercontent.com/43776720/56437453-cdb60d00-62df-11e9-8005-0c802440cba6.png)

**Comment by pllim** [comment]
On an image without the Sun, it is actually dominated by dark background. So I guess the real question is if this masking thing can be customized by user?

**Comment by manurare** [comment]
Yes that should be the question. But in SunPy they are only having into consideration the default masking by AstroPy. Therefore, how should I address to them this? Should we make a modification on AstroPy code to customize the color of the masks?

**Comment by pllim** [comment]
Do you have a snippet to reproduce your problem?

**Comment by manurare** [comment]
This is the [issue](https://github.com/sunpy/sunpy/issues/3007) I am referring to. The reason why the mask is white is because the _Map_ SunPy object created to represent the sun image is using a norm which is an _ImageNormalize_ instance from AstroPy and they would like it to be black.

**Comment by pllim** [comment]
From sunpy/sunpy#3007 , it seems like the consensus is fixing it downstream at Sunpy without affecting Astropy. If that is the case, please close this issue.
