### ISSUE TITLE
Implicit dtype conversion happening when indexing CartesianRepresentation

### ISSUE THREAD

**Issue by Juanlu001** [astropy/astropy#8614]
When a `CartesianRepresentation` object is created from a `np.float32` object, indexing it automatically upgrades it to `np.float64`.

Normal behavior:

```
In [83]: xyz = np.array([[1, 0, 0], [0.9, 0.1, 0]])

In [84]: CartesianRepresentation(xyz.astype(np.float32), xyz_axis=-1, unit="km").xyz.dtype
Out[84]: dtype('float32')

In [85]: CartesianRepresentation(xyz.astype(np.float32), xyz_axis=-1, unit="km").xyz[0].dtype
Out[85]: dtype('float32')
```

However, when indexing the representation object itself:

```
In [86]: CartesianRepresentation(xyz.astype(np.float32), xyz_axis=-1, unit="km")[0].xyz.dtype
Out[86]: dtype('float64')
```

*Not to be confused* with #8613, which also changes the dtype but probably because of the internal conversion to `Quantity`:

```
In [87]: CartesianRepresentation(xyz.astype(np.float16), xyz_axis=-1, unit="km").xyz.dtype
Out[87]: dtype('float64')
```

**Comment by mhvk** [comment]
Tricky one. First, just to show not all is bad, if one uses a slice, things work as expected:
```
CartesianRepresentation(xyz.astype(np.float32), xyz_axis=-1, unit="km")[:1].xyz.dtype
Out[32]: dtype('float32')
```

I.e., this is specific to scalars: inside `representations._combine_xyz`, the code does `y.to_value()` which returns a python float. Then, `np.stack` takes these floats and turns then into `float64`. See https://github.com/astropy/astropy/blob/master/astropy/coordinates/representation.py#L86

One could solve this by adding `dtype = x.dtype` up front and then `np.stack(...).astype(dtype, copy=False)`

Note, though, that this problem will disappear: now that `np.stack` can work on quantities directly (#8808), this whole piece of code can be simplified and will work correctly.

**Comment by mhvk** [comment]
Labeling this as a bug. Could also be solved by `Quanity` just not returning python scalars in the first place - see #8871

**Comment by mhvk** [comment]
See #8876 for how the actual fix looks like (I closed #8871 since one might as well discuss code along with the question of whether to make the change at all).

**Comment by mhvk** [comment]
@Juanlu001, this bug at least is fixed. Still cannot have coordinate transformations at lower precision, but perhaps that will come too.

**Comment by Juanlu001** [comment]
Thanks a lot @mhvk! Indeed I think this will cover the confusing cases at least
