### ISSUE TITLE
Some ERFA ufuncs do not work with float32

### ISSUE THREAD

**Issue by Juanlu001** [astropy/astropy#8615]
I found one particular function in ERFA which does not accept float32 values, although there are probably more:

```
In [3]: xyz = np.array([[1, 0, 0], [0.9, 0.1, 0]])

In [4]: _erfa.p2s(xyz)
Out[4]: 
(array([0.        , 0.11065722]),
 array([0., 0.]),
 array([1.        , 0.90553851]))

In [5]: _erfa.p2s(xyz.astype(np.float32))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-cbd078a35d7c> in <module>()
----> 1 _erfa.p2s(xyz.astype(np.float32))

~/.miniconda36/envs/py37/lib/python3.7/site-packages/astropy/_erfa/core.py in p2s(p)
  18187 
  18188     """
> 18189     theta, phi, r = ufunc.p2s(p)
  18190     return theta, phi, r
  18191 

RuntimeError: no relevant input found; should not happen!
```

This issue manifests itself in quite strange ways:

```
In [97]: icrs = ICRS(CartesianRepresentation(xyz.astype(np.float32), xyz_axis=-1, unit="km"))

In [98]: q = icrs.spherical
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-98-73fe0562a4ab> in <module>()
----> 1 q = icrs.spherical

~/.miniconda36/envs/py37/lib/python3.7/site-packages/astropy/coordinates/baseframe.py in spherical(self)
   1661         # TODO: if representations are updated to use a full transform graph,
   1662         #       the representation aliases should not be hard-coded like this
-> 1663         return self.represent_as('spherical', in_frame_units=True)
   1664 
   1665     @property

~/.miniconda36/envs/py37/lib/python3.7/site-packages/astropy/coordinates/baseframe.py in represent_as(self, base, s, in_frame_units)
   1072                 diff = data.differentials['s']  # TODO: assumes velocity
   1073             else:
-> 1074                 data = self.data.represent_as(representation_cls)
   1075 
   1076             # If the new representation is known to this frame and has a defined

~/.miniconda36/envs/py37/lib/python3.7/site-packages/astropy/coordinates/representation.py in represent_as(self, other_class, differential_class)
    688             if other_class is not self.__class__:
    689                 # The default is to convert via cartesian coordinates
--> 690                 new_rep = other_class.from_cartesian(self.to_cartesian())
    691             else:
    692                 new_rep = self

~/.miniconda36/envs/py37/lib/python3.7/site-packages/astropy/coordinates/representation.py in from_cartesian(cls, cart)
   1664         p = cart.get_xyz(xyz_axis=-1)
   1665         # erfa p2s: P-vector to spherical polar coordinates.
-> 1666         return cls(*erfa_ufunc.p2s(p), copy=False)
   1667 
   1668     def norm(self):

~/.miniconda36/envs/py37/lib/python3.7/site-packages/astropy/units/quantity.py in __array_ufunc__(self, function, method, *inputs, **kwargs)
    461 
    462         # Call our superclass's __array_ufunc__
--> 463         result = super().__array_ufunc__(function, method, *arrays, **kwargs)
    464         # If unit is None, a plain array is expected (e.g., comparisons), which
    465         # means we're done.

RuntimeError: no relevant input found; should not happen!
```

which comes from here:

https://github.com/astropy/astropy/blob/9bffef18249f802792a81800a44efc038ca3ac4c/astropy/_erfa/ufunc.c.templ#L625-L626

And, in my case, was difficult to spot because iterating by value *did* work, see #8614.

**Comment by mhvk** [comment]
@Juanlu001 - the erfa functions are internally all written in doubles, so in that sense the calculations will always be done in double precision (and you'll thus get doubles out). But I'm surprised the values aren't automatically converted by the ufunc. ... 

Looking at the code surrounding the error message, it looks like I just assumed it was double input; this probably is fixable. That said, the whole check on last dimension 3 is no longer needed in numpy 1.16; could you check things work for that?

**Comment by kyleaoman** [comment]
Running into essentially the same issue:

```
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.coordinates import CartesianRepresentation, SphericalRepresentation
>>> CR = CartesianRepresentation(np.array([1, 2, 3], dtype='f4') * U.m)
>>> SphericalRepresentation.from_cartesian(CR)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/users/koman/.conda/envs/koman/lib/python3.7/site-packages/astropy/coordinates/representation.py", line 1666, in from_cartesian
    return cls(*erfa_ufunc.p2s(p), copy=False)
  File "/Users/users/koman/.conda/envs/koman/lib/python3.7/site-packages/astropy/units/quantity.py", line 463, in __array_ufunc__
    result = super().__array_ufunc__(function, method, *arrays, **kwargs)
RuntimeError: no relevant input found; should not happen!
>>> import astropy
>>> astropy.__version__
'3.1.2'
>>> import numpy
>>> numpy.__version__
'1.16.2'
```

**Comment by mhvk** [comment]
Hmm, I can reproduce this, but on astropy and numpy master it does work. So, in principle, this will be solved in astropy 3.2, where I removed the hack for ensuring input had three dimensions. However, as the default pip packages are compiled with the lowest supported numpy version, which is 1.15, this will really work only if one compiles astropy oneself with numpy >=1.16.

If it is important, this may be fixable also for lower numpy versions.

I should add, though, that even in the fixed version this will auto-convert float32 to float64 as needed by the erfa functions, but it will *not* auto-convert back. So, in your example above the spherical representation will have float64 coordinates.

The latter may be fixable as well, but would need writing float32 wrappers for all relevant erfa functions in `_erfa/ufunc.c.templ` and ensuring that this is only done for functions where it makes sense (e.g., *not* the time functions). This is quite a bit of work, though if people are interested, I can help guide it. 

But perhaps good first to be sure there are good use cases! @Juanlu001, @kyleaoman - did you just happen to run into it and do not care if float32 becomes float64, or are you trying to save memory for very large arrays of coordinates?

**Comment by kyleaoman** [comment]
In my case the underlying array being given to the coordinates comes from an hdf5 file, and I think (?) that when that gets read into a numpy array it preserves whatever precision was stored in the file. I'm using this for simulation particle coordinates, so the arrays can be large (>10^9) and I care somewhat about the memory consumption. I guess I'd advocate for promoting to double, but issuing a warning when that happens, if that's straightforward.

**Comment by Juanlu001** [comment]
> In my case the underlying array being given to the coordinates comes from an hdf5 file

Exactly the case of the person that originally told me about this. I don't know the implications of promoting the types, and if it's not too difficult to keep consistency, then I'd prefer it I guess.

**Comment by mhvk** [comment]
OK, sounds like we should at least try to accept `float32` as input for the coordinate classes, which I think means fixing my dimension equals 3 kludge. For representations, arguably one should stay in `float32`. Will need some thought on how to do that, but arguably that is a different issue.

**Comment by mhvk** [comment]
Just accepting `float32` was not too hard, though I really had to think about my previous code (the true ufunc internals remain tricky!). See #8759.

**Comment by pllim** [comment]
@Juanlu001 and @kyleaoman , now that #8759 is in `master`, please check if your use case now works with the latest `master`. Thanks!

**Comment by Juanlu001** [comment]
Checked, thanks @mhvk @pllim! :+1:
