### ISSUE TITLE
Using WCS to give separation from given coordinates - in arcseconds

### ISSUE THREAD

**Issue by Ragadeepika-Pucha** [astropy/astropy#8623]
Hi,

I am trying to make an image with the X and Y axis to be the separation of the a given coordinate in  arcseconds. I know how to get the separation using SkyCoord, but what to do if I want to use the wcs object - which I can then put into the 'projection' keyword while making the plot.

Thank you,
Raga

**Comment by pllim** [comment]
Please see https://astropy.readthedocs.io/en/stable/visualization/wcsaxes/index.html .
