### ISSUE TITLE
Unified IO docs table is broken

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8627]
It used to be nice, but now something is broken:
http://docs.astropy.org/en/stable/io/unified.html#built-in-table-readers-writers vs http://docs.astropy.org/en/latest/io/unified.html#built-in-table-readers-writers

Incidentally there are new docs build issues that may be also related:

```
Warning, treated as error:
/home/circleci/project/build/lib.linux-x86_64-3.6/astropy/timeseries/sampled.py:docstring of astropy.timeseries.TimeSeries.read:51:Malformed table.
Text in column margin in table line 2.

=========== ==== ===== =============
    Format   Read Write Auto-identify

=========== ==== ===== =============
    ..

kepler.fits  Yes    No            No
    tess.fits  Yes    No            No

=========== ==== ===== =============
Sphinx Documentation subprocess failed with return code 2
Exited with code 2
```

<img width="808" alt="Screen Shot 2019-04-23 at 21 09 50" src="https://user-images.githubusercontent.com/6788290/56631936-5698b580-660c-11e9-9003-4d89a207755d.png">

<img width="794" alt="Screen Shot 2019-04-23 at 21 10 00" src="https://user-images.githubusercontent.com/6788290/56631935-5698b580-660c-11e9-9d0e-37082afa5a44.png">

**Comment by bsipocz** [comment]
ping @astrofrog for the timeseries part of the issue

**Comment by pllim** [comment]
For the table column width, I think it is #8631 and possibly addressed in spacetelescope/sphinx-asdf#13 ?

**Comment by astrofrog** [comment]
Looks like this is fixed? http://docs.astropy.org/en/latest/io/unified.html#built-in-table-readers-writers

**Comment by bsipocz** [comment]
Yes, indeed it was the same issue as #8631
