### ISSUE TITLE
CSS issue in API docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8631]
Recently there has been a change in the formatting of the API docs which means that the text is squashed into thin columns:

<img width="731" alt="Screenshot 2019-04-24 at 09 39 25" src="https://user-images.githubusercontent.com/314716/56645115-f38f3900-6674-11e9-8da5-85f3ee3c3713.png">

I'll investigate to see what could be causing this.

**Comment by astrofrog** [comment]
The culprit is the sphinx-asdf extension, which was added in https://github.com/astropy/astropy/pull/8526, and which overrides the style for the ``table`` tag. I'll open a PR there to fix it but we might have to also patch it here if we can't get a new release of sphinx-asdf out in time.

**Comment by astrofrog** [comment]
See https://github.com/spacetelescope/sphinx-asdf/pull/13

**Comment by pllim** [comment]
I merged your PR over there. What kind of release you looking for? Currently it only has RC.

**Comment by pllim** [comment]
Try again -- `sphinx-asdf` 0.1.0rc8 is now on PyPI.

**Comment by bsipocz** [comment]
Do you think that #8627 is the same issue?

**Comment by pllim** [comment]
> same issue?

That is my hunch, but only one way to find out.

**Comment by astrofrog** [comment]
RTD build underway: https://readthedocs.org/projects/astropy/builds/8961189/

**Comment by pllim** [comment]
Seems normal to me now; What do you think? https://docs.astropy.org/en/latest/timeseries/index.html

**Comment by bsipocz** [comment]
On circleCI it looks OK to me: https://30137-2081289-gh.circle-artifacts.com/0/home/circleci/project/docs/_build/html/api/astropy.timeseries.TimeSeries.html#astropy.timeseries.TimeSeries.read

**Comment by astrofrog** [comment]
RTD looks good too - https://docs.astropy.org/en/latest/timeseries/index.html
