### ISSUE TITLE
memory allocation problem in testLinearLSQFitter

### ISSUE THREAD

**Issue by bodewits** [astropy/astropy#8641]
Looking for help - running the astropy test and it fails on the test_fitters.py with the message:
```
Python(93292,0x1162225c0) malloc: can't allocate region
*** mach_vm_map(size=18446744071986823168) failed (error code=3)
Python(93292,0x1162225c0) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
```
What's driving that size?
astropy 3.1.2

**Comment by pllim** [comment]
Hi. Can you please give more info? What is the hardware architecture? How did you install `astropy`? What command you used to run the test?

**Comment by bodewits** [comment]
Thank you - I tested several underlying packages and resolved the problem by updating numpy.
