### ISSUE TITLE
a potential discrepancy between astropy.coordinates documentation and code

### ISSUE THREAD

**Issue by jvo203** [astropy/astropy#8645]
There seems to be discrepancy between documentation at http://docs.astropy.org/en/stable/coordinates/galactocentric.html and the actual results from the Python code. I have re-implemented the transform_to -> galactocentric in Julia (before the final implementation in C/C++) by copying/pasting the equations from the astropy documentation. But the only way to get an agreement between Julia and Python is by inverting the sign of \delta_GC or modifying the R₁ matrix so that it uses the clockwise rotation as all the remaining matrices do. It is very confusing...

A sample Python code:
```python
import numpy as np
import astropy.coordinates as coord
import astropy.units as u

c1 = coord.ICRS(ra=89.014303*u.degree, dec=13.924912*u.degree,
                distance=(37.59*u.mas).to(u.pc, u.parallax()),
                pm_ra_cosdec=372.72*u.mas/u.yr,
                pm_dec=-483.69*u.mas/u.yr,
                radial_velocity=0.37*u.km/u.s)
print(c1)

gc1 = c1.transform_to(coord.Galactocentric)
print(gc1)
```
Output:
```
<ICRS Coordinate: (ra, dec, distance) in (deg, deg, pc)
    (89.014303, 13.924912, 26.6028199)
 (pm_ra_cosdec, pm_dec, radial_velocity) in (mas / yr, mas / yr, km / s)
    (372.72, -483.69, 0.37)>
<Galactocentric Coordinate (galcen_coord=<ICRS Coordinate: (ra, dec) in deg
    (266.4051, -28.936175)>, galcen_distance=8.3 kpc, galcen_v_sun=(11.1, 232.24, 7.25) km / s, z_sun=27.0 pc, roll=0.0 deg): (x, y, z) in pc
    (-8325.6359106, -6.48258878, 24.50348514)
 (v_x, v_y, v_z) in km / s
    (28.46188771, 157.93916086, 17.65189313)>
```
The Julia code (copy and paste from astropy.coordinates documentation):
```julia
ra = 89.014303
dec = 13.924912
ω = 37.59

α = deg2rad(ra)
δ = deg2rad(dec)
d = 1000.0 / ω

pmra = 372.72
pmdec = -483.69
radial_velocity = 0.37

η = deg2rad(58.5986320306)
αGC = deg2rad(266.4051)
δGC = deg2rad(-28.936175)#the sign in the rotation matrix as per documentation seems to be inverted; cannot understand the root cause of the problem
dGC = 8300
xGC = [1, 0, 0]
z = 27
θ = asin(z / dGC)

r_icrs = d * [cos(α) * cos(δ), sin(α) * cos(δ), sin(δ)]

R₁ = Matrix(undef, 3, 3)
R₁[1,1] = cos(δGC)
R₁[1,2] = 0
R₁[1,3] = - sin(δGC)
R₁[2,:] = [0 1 0]
R₁[3,1] = sin(δGC)
R₁[3,2] = 0
R₁[3,3] = cos(δGC)
println("R₁:", R₁)

R₂ = Matrix(undef, 3, 3)
R₂[1,1] = cos(αGC)
R₂[1,2] = sin(αGC)
R₂[1,3] = 0
R₂[2,1] = - sin(αGC)
R₂[2,2] = cos(αGC)
R₂[2,3] = 0
R₂[3,:] = [0 0 1]
println("R₂:", R₂)

R₃ = Matrix(undef, 3, 3)
R₃[1,:] = [1 0 0]
R₃[2,1] = 0
R₃[2,2] = cos(η)
R₃[2,3] = sin(η)
R₃[3,1] = 0
R₃[3,2] = - sin(η)
R₃[3,3] = cos(η)
println("R₃:", R₃)

R = R₃ * R₁ * R₂
println("R:", R)

R = Matrix(undef, 3, 3)
R[1,1] = cos(αGC) * cos(δGC)
R[1,2] = cos(δGC) * sin(αGC)
R[1,3] = - sin(δGC)
R[2,1] = cos(αGC) * sin(δGC) * sin(η) - sin(αGC) * cos(η)
R[2,2] = sin(αGC) * sin(δGC) * sin(η) + cos(αGC) * cos(η)
R[2,3] = cos(δGC) * sin(η)
R[3,1] = cos(αGC) * sin(δGC) * cos(η) + sin(αGC) * sin(η)
R[3,2] = sin(αGC) * sin(δGC) * cos(η) - cos(αGC) * sin(η)
R[3,3] = cos(δGC) * cos(η)
println("R:", R)

H = Matrix(undef, 3, 3)
H[1,1] = cos(θ)
H[1,2] = 0
H[1,3] = sin(θ)
H[2,1] = 0
H[2,2] = 1
H[2,3] = 0
H[3,1] = - sin(θ)
H[3,2] = 0
H[3,3] = cos(θ)
println("H:", H)

r = R * r_icrs - dGC * xGC
rGC = H * r

println("distance:", d)
println("r_icrs:", r_icrs)
println("r:", r)
println("rGC:", rGC)
```
The output:
```
R₁:Any[0.875159 0 0.483835; 0 1 0; -0.483835 0 0.875159]
R₂:Any[-0.0627017 -0.998032 0; 0.998032 -0.0627017 0; 0 0 1]
R₃:Any[1 0 0; 0 0.52103 0.853538; 0 -0.853538 0.52103]
R:Any[-0.054874 -0.873437 0.483835; 0.545899 0.37949 0.746982; -0.836052 0.305115 0.455984]
R:Any[-0.054874 -0.873437 0.483835; 0.545899 0.37949 0.746982; -0.836052 0.305115 0.455984]
H:Any[0.999995 0 0.00325301; 0 1 0; -0.00325301 0 0.999995]
distance:26.60281989890928
r_icrs:[0.444194, 25.8172, 6.40197]
r:[-8319.48, 14.822, 10.425]
rGC:Any[-8319.4, 14.822, 37.4883]
```
The values (x, y, z) in pc (-8325.6359106, -6.48258878, 24.50348514) obtained from Python do not agree with rGC. However, if one either changes the sign of  δGC = - deg2rad(-28.936175) or applies a clockwise rotation convention in the R₁ matrix as per the following
```
R₁[1,1] = cos(δGC)
R₁[1,2] = 0
R₁[1,3] = sin(δGC)
R₁[2,:] = [0 1 0]
R₁[3,1] = - sin(δGC)
R₁[3,2] = 0
R₁[3,3] = cos(δGC)
```
then Julia gives the answer in a perfect agreement with Python:
```
R₁:Any[0.875159 0 -0.483835; 0 1 0; 0.483835 0 0.875159]
R₂:Any[-0.0627017 -0.998032 0; 0.998032 -0.0627017 0; 0 0 1]
R₃:Any[1 0 0; 0 0.52103 0.853538; 0 -0.853538 0.52103]
R:Any[-0.054874 -0.873437 -0.483835; 0.494111 -0.444829 0.746982; -0.867665 -0.198078 0.455984]
R:Any[-0.054874 -0.873437 -0.483835; 0.494111 -0.444829 0.746982; -0.867665 -0.198078 0.455984]
H:Any[0.999995 0 0.00325301; 0 1 0; -0.00325301 0 0.999995]
distance:26.60281989890928
r_icrs:[0.444194, 25.8172, 6.40197]
r:[-8325.67, -6.48259, -2.58004]
rGC:Any[-8325.64, -6.48259, 24.5035]
```
The question is: is the documentation correct or is the astropy code correct? On a related note, would you be able to add to the documentation the detailed equations for converting velocities to (v_x, v_y, v_z) as well? The documentation only gives detailed steps (matrices, values) for (x, y, z) but says nothing about the corresponding velocities.

Version information:
Julia Version 1.1.0 (2019-01-21)
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
```
pip install astropy
Collecting astropy
  Downloading https://files.pythonhosted.org/packages/2a/b7/0302d5e0f9acd31515db6b4cb8e5a8de9fbd432b6af1e51a420e935febf5/astropy-2.0.12-cp27-cp27mu-manylinux1_x86_64.whl (6.1MB)
    100% |████████████████████████████████| 6.1MB 265kB/s 
Collecting pytest<3.7,>=2.8 (from astropy)
  Downloading https://files.pythonhosted.org/packages/d8/e9/73246a565c34c5f203dd78bc2382e0e93aa7a249cdaeba709099eb1bc701/pytest-3.6.4-py2.py3-none-any.whl (196kB)
    100% |████████████████████████████████| 204kB 5.8MB/s 
Collecting numpy>=1.9.0 (from astropy)
  Downloading https://files.pythonhosted.org/packages/e1/72/179a78b565ecf01fe98dab6417581d30acac15c2d93c49f93169ebea99b1/numpy-1.16.3-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 97kB/s 
Collecting setuptools (from pytest<3.7,>=2.8->astropy)
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
    100% |████████████████████████████████| 583kB 2.5MB/s 
Collecting py>=1.5.0 (from pytest<3.7,>=2.8->astropy)
  Downloading https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 10.2MB/s 
Collecting more-itertools>=4.0.0 (from pytest<3.7,>=2.8->astropy)
  Downloading https://files.pythonhosted.org/packages/2f/9d/dcfe59e213093695f108508af1214cf9cd95cc5489e46877ec5cb56369e5/more_itertools-5.0.0-py2-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 9.0MB/s 
Collecting funcsigs; python_version < "3.0" (from pytest<3.7,>=2.8->astropy)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting six>=1.10.0 (from pytest<3.7,>=2.8->astropy)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest<3.7,>=2.8->astropy)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting atomicwrites>=1.0 (from pytest<3.7,>=2.8->astropy)
  Downloading https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting pluggy<0.8,>=0.5 (from pytest<3.7,>=2.8->astropy)
  Downloading https://files.pythonhosted.org/packages/f5/f1/5a93c118663896d83f7bcbfb7f657ce1d0c0d617e6b4a443a53abcc658ca/pluggy-0.7.1-py2.py3-none-any.whl
Installing collected packages: setuptools, py, six, more-itertools, funcsigs, attrs, atomicwrites, pluggy, pytest, numpy, astropy
Successfully installed astropy-2.0.12 atomicwrites-1.3.0 attrs-19.1.0 funcsigs-1.0.2 more-itertools-5.0.0 numpy-1.16.3 pluggy-0.7.1 py-1.8.0 pytest-3.6.4 setuptools-41.0.1 six-1.12.0
```

**Comment by jvo203** [comment]
As an extra, here is the output from Python 3.6.7 (default, Oct 22 2018, 11:32:17)
python3 coords.py 
<ICRS Coordinate: (ra, dec, distance) in (deg, deg, pc)
    (89.014303, 13.924912, 26.6028199)
 (pm_ra_cosdec, pm_dec, radial_velocity) in (mas / yr, mas / yr, km / s)
    (372.72, -483.69, 0.37)>
<Galactocentric Coordinate (galcen_coord=<ICRS Coordinate: (ra, dec) in deg
    (266.4051, -28.936175)>, galcen_distance=8.3 kpc, galcen_v_sun=(11.1, 232.24, 7.25) km / s, z_sun=27.0 pc, roll=0.0 deg): (x, y, z) in pc
    (-8325.6359106, -6.48258878, 24.50348514)
 (v_x, v_y, v_z) in km / s
    (28.46188771, 157.93916086, 17.65189313)>

It seems to be the same as under Python 2 and an older version of astropy. But again there seems to be a discrepancy between documentation (copy/paste to Julia) and the actual results from running astropy...

Version info in Python 3:
 pip3 install astropy
Collecting astropy
  Downloading https://files.pythonhosted.org/packages/7a/f8/2867a9f5c97881985ee98aa19bd89ca357a4395ee7582e3c9c5ca308f1f3/astropy-3.1.2-cp36-cp36m-manylinux1_x86_64.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 311kB/s 
Collecting numpy>=1.13.0 (from astropy)
  Downloading https://files.pythonhosted.org/packages/c1/e2/4db8df8f6cddc98e7d7c537245ef2f4e41a1ed17bf0c3177ab3cc6beac7f/numpy-1.16.3-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 111kB/s 
Installing collected packages: numpy, astropy
Successfully installed astropy-3.1.2 numpy-1.16.3

**Comment by adrn** [comment]
From a quick comparison of the [documentation page](http://docs.astropy.org/en/stable/coordinates/galactocentric.html) and the [implementation in code](https://github.com/astropy/astropy/blob/master/astropy/coordinates/builtin_frames/galactocentric.py), it looks like there might be a sign error in the latex definition of R1. To match what is in the code, I think it should actually be:
```latex
\boldsymbol{R}_1 &= \begin{bmatrix}
         \cos\delta_{\rm GC}& 0 & -\sin(-\delta_{\rm GC})\\
         0 & 1 & 0 \\
         \sin(-\delta_{\rm GC})& 0 & \cos\delta_{\rm GC}\end{bmatrix}
```
or
![image](https://user-images.githubusercontent.com/583379/56855630-2ea49d00-68ff-11e9-8dc8-97a1f6d723fb.png)

**Comment by adrn** [comment]
To clarify, I believe this is a documentation bug, not a code bug: We have tests to verify that the code implementation is correct (or at least reproduces  `Galactic` coordinates with the correct parameters set).

**Comment by jvo203** [comment]
Hello Adrian,

Thank you for a quick response. OK will make the final C/C++ code match what astropy does (not what the documentation says!).

Finally, it would be really helpful if the documentation were to be updated with the equations for getting the velocities as well. It would really really help!

Regards,
Chris

**Comment by pllim** [comment]
@jvo203 , we certainly would welcome PR to fix up the doc. Thanks!

http://docs.astropy.org/en/latest/development/workflow/development_workflow.html

**Comment by jvo203** [comment]
Unfortunately I am "just" a programmer lacking an in-depth knowledge necessary to fully understand what is going on "behind the scenes" in the coordinate transformations... Sorry!

**Comment by pllim** [comment]
@jvo203 , if the fix suggested by @adrn in https://github.com/astropy/astropy/issues/8645#issuecomment-487323858 is what worked for you, then you can issue a patch with that. 😄
