### ISSUE TITLE
Should extern be private?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8652]
As brought up by @saimn in https://github.com/astropy/astropy/pull/8315#issuecomment-487753725

*something to think about codes bundled in `astropy.extern`, maybe this should be private to avoid having other packages relying on it.*

**Comment by mhvk** [comment]
It seems to me there are so few packages in there that it is not quite worth it. Also, it is nice for affiliated packages to use the same system as astropy, and, e.g., rely on its `configobj`. I do think, though, that it would be good to add an explicit note to the module docstring that packages in there can be removed (as will happen with `six` in 4.0).

**Comment by mhvk** [comment]
Now read #8315 in more detail: still feel the right thing is to keep it public. It wouldn't be that great if all those hundreds of packages had bundled `six` themselves. (In hindsight, we should have added the deprecation warning in 3.1, though!). Also, for things other than `six`, I'd bet this is much less of an issue.

**Comment by saimn** [comment]
>  It wouldn't be that great if all those hundreds of packages had bundled six themselves.

It would have been easier if all those packages used six as a dependency ;). 

I agree that there is nothing to change right now, but it is something to keep in mind for the next time someone is tempted to bundle a package in astropy.
