### ISSUE TITLE
API change issue label?

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8655]
Could we add a new Label `API change`?  This would serve as a reminder about where changelog entries should be included and for reviewers to be extra careful.  Also it can be used for proposed ideas / discussions that would include an API change.

**Comment by bsipocz** [comment]
Great idea, I've added one.

**Comment by pllim** [comment]
FYI -- I think anyone with write access can create labels. I don't think there is a policy to ask for permission first as long as you are not doing anything funky. 😉
