### ISSUE TITLE
Improve Table equality (API change)

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8656]
As @mcara has noted in #8647, table equality (`__eq__`) is currently less useful than it could be.  The current code was driven by the early version of `Table` that was internally represented as a structured array.  Equality testing assumes the `other` object is a table-like object and the return value is a 1-d array representing equality of each table row.

Pandas mostly gets things right and can serve as a model.  (Pandas handling of missing values in equality is not great though, it just says "False" instead of "missing").  It does element-wise comparison if `self` and `other` are both DataFrames that have the same number of rows and same column names.  For a row or column name mismatch it raises an exception.  If `other` is a scalar it likewise does element-wise comparison.
```
In [39]: t = simple_table()

In [40]: tp = t.to_pandas()

In [41]: tp == tp
Out[41]: 
      a     b     c
0  True  True  True
1  True  True  True
2  True  True  True

In [42]: tp == 2
Out[42]: 
       a      b      c
0  False  False  False
1   True   True  False
2  False  False  False
```
This would be a substantial API change and there is really no way to do it gradually or by deprecation.  We could have a new method e.g. `rows_equal(self, other)` that replicates the current behavior so that there would be a drop-in replacement for the current `==` behavior.

Interestingly, pandas does column broadcasting in the case of a list `other`:
```
In [50]: tp == [1, 2, 2]
Out[50]: 
       a      b      c
0   True   True  False
1   True   True  False
2  False  False  False
```

**Comment by taldcroft** [comment]
@bsipocz - are we considering 4.0 to be "open-season" for substantial API changes?  I have a lot of ideas... 😈

**Comment by bsipocz** [comment]
It'll be LTS, so yes I suppose it's as "open-season" as it ever gets.

**Comment by mcara** [comment]
Out of curiosity, how does an `Effort-high` looks like?

**Comment by himanshupathak21061998** [comment]
@taldcroft Can I work on this issue?:relaxed:

**Comment by taldcroft** [comment]
On vacation, back next week.  This takes a little thinking to get right..
