### ISSUE TITLE
_erfa assertion error with 3.2rc1 using numpy 1.16

### ISSUE THREAD

**Issue by sosey** [astropy/astropy#8672]
>     def test_output_dim_3_signature():
>         if NUMPY_LT_1_16:
>             assert erfa_ufunc.c2i00a.signature == "(),()->(d3, d3)"
>         else:
>            assert erfa_ufunc.c2i00a.signature == "(),()->(3, 3)"
>  E           AssertionError: assert '(),()->(d3, d3)' == '(),()->(3, 3)'
>  E             - (),()->(d3, d3)
>  E             ?         -   -
>  E             + (),()->(3, 3)
> 
>  /miniconda3/envs/imexam/lib/python3.7/site-packages/astropy/_erfa/tests/test_erfa.py:14: >  AssertionError

Platform: Darwin-17.7.0-x86_64-i386-64bit
Full Python Version: 
3.7.2 (default, Dec 29 2018, 00:00:04) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.16.2
Scipy: 1.2.1
Matplotlib: 3.0.3
h5py: 2.9.0
Pandas: 0.24.2
Asdf: 2.4.0.dev1734
Cython: 0.29.6
Scikit-image: 0.14.2
astropy_helpers: 3.2rc1
Using Astropy options: remote_data: any.

**Comment by pllim** [comment]
I see this error too on Windows 10 with Python 3.7.1 and Numpy 1.16.2.

**Comment by eteq** [comment]
@sosey - can you confirm how you built this?  Was it the standard ``pip install astropy==3.2rc1``?

**Comment by sosey** [comment]
yup

**Comment by sosey** [comment]
I can try again later tonight or tomorrow if you like

**Comment by pllim** [comment]
@eteq , mine was using `pip install astropy==3.2rc1` but I have to admit that I did that on top of an existing conda env and did not try with a fresh env.

**Comment by mhvk** [comment]
It would seem somehow the version check for numpy failed; presumably, in your environment, the following will hold:
```
In [14]: from astropy.utils.compat import NUMPY_LT_1_16

In [15]: NUMPY_LT_1_16
Out[15]: False
```
Yet, the erfa parts seem to have been built assuming an earlier version of numpy. Did you perhaps update the numpy version after installing astropy?

**Comment by sosey** [comment]
I don't remember do that. Just to be clean, I just created a new environment with py3.7, installed numpy, installed pytest-astropy, pip install astropy==3.2rc1, and reran the tests. This is what I get:

`1 failed, 11259 passed, 773 skipped, 69 xfailed, 2445 warnings in 200.65 seconds`

================================================================= FAILURES ==================================================================
________________________________________________________ test_output_dim_3_signature ________________________________________________________

    def test_output_dim_3_signature():
        if NUMPY_LT_1_16:
            assert erfa_ufunc.c2i00a.signature == "(),()->(d3, d3)"
        else:
>           assert erfa_ufunc.c2i00a.signature == "(),()->(3, 3)"
E           AssertionError: assert '(),()->(d3, d3)' == '(),()->(3, 3)'
E             - (),()->(d3, d3)
E             ?         -   -
E             + (),()->(3, 3)

/miniconda3/envs/test-astropy/lib/python3.7/site-packages/astropy/_erfa/tests/test_erfa.py:14: AssertionError
============================================================= warnings summary ==============================================================
/miniconda3/envs/test-astropy/lib/python3.7/importlib/_bootstrap.py:219
  /miniconda3/envs/test-astropy/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)


with

platform darwin -- Python 3.7.3, pytest-4.4.2, py-1.8.0, pluggy-0.11.0

Running tests with Astropy version 3.2rc1.
Running tests in /miniconda3/envs/test-astropy/lib/python3.7/site-packages/astropy.

Date: 2019-05-15T11:32:57

Platform: Darwin-17.7.0-x86_64-i386-64bit

Executable: /miniconda3/envs/test-astropy/bin/python

Full Python Version: 
3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.16.3
Scipy: not available
Matplotlib: not available
h5py: not available
Pandas: not available
Cython: not available
Scikit-image: not available
astropy_helpers: 3.2rc1
Using Astropy options: remote_data: any.

rootdir: /miniconda3/envs/test-astropy/lib/python3.7/site-packages/astropy
plugins: remotedata-0.3.1, openfiles-0.3.2, doctestplus-0.3.0, arraydiff-0.3

**Comment by mhvk** [comment]
So, I think the problem is that the wheels for astropy are compiled with one version of numpy and then run on another. One solution would be to provide numpy-version dependent packages, another simply to revert #8309 and only re-apply that once we support only numpy >=1.16.

@bsipocz - suggestions?

**Comment by bsipocz** [comment]
This is very very weird, and I cannot reproduce locally. Before reverting I would suggest try to find a someone else, too for whom this is failin, just to rule out it being some yet unexplained local setup issue.

**Comment by pllim** [comment]
@bsipocz oe @eteq , if you want to look at this in person, I can reproduce the failure on my (gasp) Windows 10 laptop running this with 3.2rc1:

```python
import astropy
astropy.test(package='_erfa')
```

**Comment by sosey** [comment]
I also ran this with numpy 1.13 and 1.15 on my setup with python 3.6, and got no error...but I did get the error with python 3.6 and 1.16.0, 1.16.2, and 1.16.3

**Comment by bsipocz** [comment]
Oh, nevermind me, I actually see it on my laptop, but was testing the units package rather than _erfa.
One should never test, let alone comment on github after a conference dinner...

**Comment by dhomeier** [comment]
@mhvk as I understand it a build with numpy < 1.16 basically reproduces the situation before #8309 anyway in using `D3Fix` and creating `"(d3)"` signatures, with only the newly added `test_output_dim_3_signature` failing once running with numpy 1.16. So the numpy <= 1.15 -> 1.16 problems should just as well be circumvented by skipping that test (apart perhaps from performance penalties)...
This won't work the other way round as `ufunc` already fails on import with the newer signatures. And a separate problem that turned up in #8671 is that a number of C files get either the <= 1.15 declaration `PyObject *numpy = PyImport_ImportModule("numpy.core.umath");` or the 1.16 version `PyObject *numpy = PyImport_ImportModule("numpy.core._multiarray_umath");` in `numpy/__ufunc_api.h` from whatever numpy version is installed at *compile time* (via `numpy/arrayobject.h` -> `ndarrayobject.h` - `__ufunc_api.h`. Again this poses no problem when upgrading numpy from 1.15 to 1.16 since the older module is still supported, but if a package built on numpy 1.16 is installed with an older numpy version, the `multiarray` error will break import of `io.ascii`, `_erfa`, `modeling`, `stats`, `table` and `timeseries`!
I've got no idea how to get around this other than the numpy-version-dependent packages you suggested, or perhaps adding our own copy of the numpy 1.15 headers to always build against the old interface until < 1.16 support is ended (sounds ugly though). Or we could decide, as @pllim has pointed out, that downgrading numpy after installation is an extremely unlikely situation (but I am concerned that it could still pop up when binary packages are distributed).

**Comment by mhvk** [comment]
@dhomeier - I think your analysis makes sense. I think going forward this is perhaps mostly a packaging question: I think it is reasonable to always compile with the lowest version of the packages we depend on (perhaps we do that already; @bsipocz?). As you note, in that case all that is needed is to remove or adjust the test for the signature. Probably removal is fine, since really one should not test an implementation detail - the code should just work!

**Comment by astrofrog** [comment]
I think Numpy only guarantees compatibility going forward, so the recommended approach is to always build with the oldest Numpy you can. Indeed, any package (not just astropy) which has C extensions that use Numpy will break if compiled with Numpy 1.16 and used with an older version. Our wheels should already be compiled with the oldest version we can.

So is the main issue here that what matters for the ``test_output_dim_3_signature`` test is *not* what the runtime version of Numpy is, but what the version used to build is?

**Comment by mhvk** [comment]
Is there a way to access what numpy version one built with? Possibly the simplest here is simply to remove the test - I arguable should never have added it, as it tests implementation details.

**Comment by bsipocz** [comment]
As far as I know we don't use any customization on top of the default wheel and conda package building, so it really should have been done using numpy 1.13. If now that's an upstream bug in the recipes:
https://github.com/MacPython/astropy-wheels
https://github.com/conda-forge/astropy-feedstock

**Comment by astrofrog** [comment]
@mhvk - I agree that removing the test might make sense, as long as we are testing that the functions behave correctly. I'm not aware of any way to check what Numpy version the package was built with - we could in theory add something like this to astropy-helpers, but I still favor simply removing the test.

**Comment by mhvk** [comment]
@astrofrog - OK, I've made a quick PR removing the test - see #8733.

For the reverse error, I guess in principle it would be nice for astropy to warn upon importing it we're running on a numpy version that is lower than that with which we're compiled, but that seems a separate, less critical issue (#8734)

**Comment by dhomeier** [comment]
I think in most cases users will find out soon enough, but it would probably still be helpful to to give a more specific warning than `ImportError: numpy.core.multiarray failed to import`.

And the packaging of the tar files should be adapted to not include the generated `_erfa/ufunc.c` (or always include one generated with numpy < 1.16 by default).

**Comment by bhazelton** [comment]
I'm seeing something that I believe is related to this issue in the Travis OSX builds for a repo I work on. We install numpy and astropy (and several other packages) via conda, resulting in numpy 1.15.4 and astropy 3.2 being installed. When astropy.time is imported I get the following error:

```
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from pyuvdata import version  # noqa (pycodestyle complains about import below code)
  File "/Users/travis/build/RadioAstronomySoftwareGroup/pyuvdata/pyuvdata/__init__.py", line 16, in <module>
    from .uvdata import *  # noqa
  File "/Users/travis/build/RadioAstronomySoftwareGroup/pyuvdata/pyuvdata/uvdata.py", line 19, in <module>
    from astropy.time import Time
  File "/Users/travis/miniconda/envs/testenv/lib/python3.6/site-packages/astropy/time/__init__.py", line 2, in <module>
    from .formats import *
  File "/Users/travis/miniconda/envs/testenv/lib/python3.6/site-packages/astropy/time/formats.py", line 16, in <module>
    from astropy import _erfa as erfa
  File "/Users/travis/miniconda/envs/testenv/lib/python3.6/site-packages/astropy/_erfa/__init__.py", line 3, in <module>
    from .core import *
  File "/Users/travis/miniconda/envs/testenv/lib/python3.6/site-packages/astropy/_erfa/core.py", line 40, in <module>
    from . import ufunc
ValueError: expect dimension name at position 1 in "(3),(3),(),()->(3)"
```

You can see the full log here if you like: https://travis-ci.org/RadioAstronomySoftwareGroup/pyuvdata/jobs/541939356

**Comment by bsipocz** [comment]
@bhazelton - thanks, we're aware of the issue, but no solution yet. As a workaround I would suggest to pip install astropy instead of conda install. (The issue also not around when numpy 1.16 is used).

**Comment by bhazelton** [comment]
Ok, thanks! With this issue closed, I wasn't sure if it was known that it continued to be a problem. Is there a more appropriate issue to watch? I see the reference to #8734 above, but after reading it I wasn't sure if fixing that issue would fix mine.

**Comment by bsipocz** [comment]
Good point, I'm afraid we never migrated the panicking thread off from slack to github issues. I'm reopen https://github.com/astropy/astropy/issues/8671 as that's a tiny bit cleaner issue (and has the same error as we see on CI.
