### ISSUE TITLE
writing a basic ascii table from QTable is broken

### ISSUE THREAD

**Issue by mcbeth** [astropy/astropy#8680]
```python
from astropy.table import QTable,Column
import astropy.units as u
q = QTable()
q['dt'] = [1,2,3]*u.s
q.write('foo.txt',format='ascii.no_header',delimiter=',',formats={'dt':'%.18f'})
```

The write call throws an exception with "Quantity object has no name member"

If I look in `_set_col_formats` in `io/ascii/core.py`
it says
```python
if col.info.name in self.formats:
   col.info.format = self.formats[col.name]
```

That second line probably should say "col.info.name" instead.  A similar change would need to be made in the fast writer

EDIT: Syntax highlighting

**Comment by pllim** [comment]
From your Slack message, you said this exact code used to work in Astropy 1.2.4? If not, please provide the snippet that worked in Astropy 1.2.4. Thanks.

**Comment by pllim** [comment]
Thanks for the report!

Looking into this more, looks like `col.name` works with `Table` but not `QTable`. However, `col.info.name` works with both.

@taldcroft or @mhvk , what is the proper patch here? Should `QTable` support `col.name` or do we change usage to `col.info.name`?

**Comment by mcbeth** [comment]
On Thu, May 09, 2019 at 07:21:56AM -0700, P. L. Lim wrote:
>    From your Slack message, you said this exact code used to work in Astropy
>    1.2.4? If not, please provide the snippet that worked in Astropy 1.2.4.
>    Thanks.

Yes, that exact code worked on 1.2.4

Jeff

-- 
"The man who does not read good books has no advantage over 
 the man who cannot read them."
 -- not Mark Twain, maybe a southen librarian in 1910

**Comment by taldcroft** [comment]
Changing to `col.info.name` is the correct patch.  Going through the `info` attribute is the generalized version that works for both mixins (e.g. Quantity) and normal Columns.

**Comment by pllim** [comment]
@mcbeth , do you want to go ahead and submit a PR with the suggested patch?

http://docs.astropy.org/en/stable/development/workflow/development_workflow.html

**Comment by taldcroft** [comment]
I can also probably make a quick fix if @mcbeth does not have time.

**Comment by pllim** [comment]
First come, first serve! We are open-source and open-development after all. :wink:

**Comment by mcbeth** [comment]
My main hesitation would be that I haven't dug through the fast writer far enough to figure out how to make the same change there.  I guarantee that @taldcroft will be quicker.
