### ISSUE TITLE
3.2rc1 SkyCoord.from_name('UMa II') does not work

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8684]
```python
>>> from astropy.coordinates import SkyCoord
>>> SkyCoord.from_name('Uma II')  # Or 'UMa II'
NameResolveError: Unable to find coordinates for name 'Uma II'
```

but a subsequent call with a different star worked

```python
>>> SkyCoord.from_name('Uma I')  # Or 'UMa I'
<SkyCoord (ICRS): (ra, dec) in deg
    (158.72, 51.92)>
```

So, I don't think this is a network problem, but rather `'Uma II'` not in their database anymore?

**Comment by bsipocz** [comment]
Good catch. Shall we just change the example to "Mizar"? Stars with old ancient names doesn't disappear or renamed unlike newly discovered dwarf galaxies 😉

**Comment by bsipocz** [comment]
(I'm opening a PR)

**Comment by pllim** [comment]
Ops, sorry, @bsipocz , I didn't see your comment before attempting a fix myself.

**Comment by bsipocz** [comment]
Weird, UMa II is still there: http://simbad.u-strasbg.fr/simbad/sim-basic?Ident=NAME+UMa+II+Galaxy

But then for testing the constellation resolver it's irrelevant what is and is not a valid string for simbad. I'm fine with either of the PRs opened to solve the failure.

**Comment by pllim** [comment]
> Weird, UMa II is still there

Is this a name resolver bug after all? @eteq and @adrn ? Should `SkyCoord` be able to look up Simbad?

**Comment by bsipocz** [comment]
No, I believe it's not a bug anywhere (definitely not with us) but simply a change on the of simbad. When you type in `UMa II` in their webform it also return nothing, but if you say `NAME UMa II Galaxy` then it has something.
