### ISSUE TITLE
3.2rc1 setup.py fails with external astropy_helpers

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#8698]
When I am using external astropy helpers , the `setup.py` commands hang endlessly trying to rebuild the extension modules.
Steps to reproduce on Debian Buster:

 * install python3-astropy-helpers (3.1.1)
 * install the source tarball from pypi
 * set `setup.cfg`/`[ah_bootstrap]`/`auto_use = False`
 * run `setup.py`
```
$ python3 setup.py --offline clean 
WARNING: You appear to be trying to import astropy from within a source checkout without building the extension modules first.  Attempting to (re)build extension modules: [astropy]
Rebuilding extension modules / ... [Ctrl-C hit] [Failed]
ERROR: An error occurred while attempting to rebuild the extension modules.  Please try manually running `./setup.py develop` or `./setup.py build_ext --inplace` to see what the issue was.  Extension modules must be successfully compiled and importable in order to import astropy. [astropy]
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from astropy_helpers.setup_helpers import setup
ImportError: cannot import name 'setup' from 'astropy_helpers.setup_helpers' (/usr/lib/python3/dist-packages/astropy_helpers/setup_helpers.py)
```
`setup.py develop` gives the same error.
The script was starting more and more `python` instances, and filled the memory (I stopped by hitting Ctrl-C after ~24GB).
This does not happen when using the internal helpers, and not having the Debian package installed.

**Comment by bsipocz** [comment]
Hmm, this is quite bad, but not surprising. The new helpers has been significantly refactored and simplified API wise. Is there any chance that you could try the top of the 3.2.x branch from the helpers? I'm happy to tag a 3.2rc1 there and also push it to PyPI.

**Comment by bsipocz** [comment]
(I don't expect any major hiccups when updating the helpers for packages that are already happy with the 3.1.1 version, but @astrofrog can confirm or refute this)

**Comment by olebole** [comment]
I can confirm that it works with the helpers from git, so an updated astropy-helpers would make it.

**Comment by astrofrog** [comment]
Yeah this was just because astropy-helpers v3.2 isn't released yet, so I think it won't require any action here.

**Comment by dhomeier** [comment]
I had a similar problem when running any setup.py command without the `--offline` flag in the plain source from PyPI (no modifications in `setup.cfg`, no external `astropy_helpers` installed; Python 3.5.1 on Red Hat 4.8.5-4) - spawning up to ~2000 python subprocesses before I put an end to it.

**Comment by olebole** [comment]
@astrofrog Astropy 3.2 should accompanied by an updated helpers release.

**Comment by bsipocz** [comment]
@olebole - yes, it will be. I plan to release the helpers a bit before astropy proper.

**Comment by astrofrog** [comment]
Hmm I can reproduce this issue, and it looks like the reason for this is because:

```
$ more astropy_helpers/astropy_helpers/version.py
# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2018-12-31 23:55:32 UTC
from __future__ import unicode_literals
import datetime

version = "3.1"
githash = "9f82aac6c2141b425e2d639560f7260189d90b54"

...
```

gives 3.1 as the astropy-helpers version, which means that then ah_bootstrap.py tries to auto-update to 3.1.1, causing the issue. If astropy-helpers had 3.2rc1 as the version, it wouldn't auto-update.

So it looks like there was a genuine issue in the 3.2rc1 source distribution.

**Comment by saimn** [comment]
Hmm, this relates to something I never understood with astropy-helpers (https://github.com/astropy/astropy-helpers/issues/207#issuecomment-160774086): it looks like both `version.py` and the files in the .egg-info directory are never updated:
```
❯ head astropy_helpers/astropy_helpers/version.py
# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2017-06-03 22:59:22.541083
from __future__ import unicode_literals
import datetime

version = "1.3.1"
githash = "70b09af7e4f6b8a4e409412a913ff2adb05c12b7"


major = 1
minor = 3
```
Yes, this is with an up-to-date master branch. And the same for `astropy_helpers.egg-info` (the file date is the same as `version.py`):
```
❯ l astropy_helpers/astropy_helpers.egg-info
total 20K
-rw-r--r-- 1 simon    1  3 juin   2017 dependency_links.txt
-rw-r--r-- 1 simon    1  3 juin   2017 not-zip-safe
-rw-r--r-- 1 simon 3,0K  3 juin   2017 PKG-INFO
-rw-r--r-- 1 simon 3,5K  3 juin   2017 SOURCES.txt
-rw-r--r-- 1 simon   16  3 juin   2017 top_level.txt

❯ grep Version astropy_helpers/astropy_helpers.egg-info/PKG-INFO
Metadata-Version: 1.1
Version: 1.3.1

```

**Comment by bsipocz** [comment]
yes, version.py never updates, but it should all work as expected after a git clean.

> So it looks like there was a genuine issue in the 3.2rc1 source distribution as it was packaged with astropy-helpers 3.1.

I probably made a mistake by not git cleaning the helpers directory, too.

**Comment by eteq** [comment]
Hmm, this probably means we should do an rc2 to at least confirm the problem goes away, right?

**Comment by olebole** [comment]
For me, the problem happened when I did **not** use the astropy-helpers that come with astropy. I set `[ah_bootstrap] auto_use=False` in `config.cfg` and use the helpers provided as a package.

**Comment by bsipocz** [comment]
I'll get the helpers release out this week, maybe even tonight assuming DB has decent wifi....

**Comment by bsipocz** [comment]
@olebole - the helpers 3.2 version is on pypi, so this should ideally be solved now. I'm also pushing 3.2rc2 to pypi any time now (waiting for CI and wheels).

**Comment by olebole** [comment]
Thank you @bsipocz! So, close this?

**Comment by bsipocz** [comment]
If it indeed solved the issue, yes please.
