### ISSUE TITLE
tight_layout() doesn't work properly on plots with a WCSAxes projection

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#8703]
A Matpltolib `Axes` created with `projection=wcs` does not play well with Matplotlib's `tight_layout()` method, that is supposed to re-size elements of a figure such that there are no overlapping labels/axes etc.

Consdier the following example:
```python
import matplotlib.pyplot as plt

from astropy.wcs import WCS
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename

filename = get_pkg_data_filename('galactic_center/gc_msx_e.fits')

hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)

fig = plt.figure(figsize=(8, 6))
n = 2
for i in range(n):
    projection = wcs
    # projection = None
    plt.subplot(n, 1, i + 1, projection=projection)
    # plt.imshow(hdu.data, vmin=-2.e-5, vmax=2.e-4, origin='lower')
    plt.grid(color='white', ls='solid')
    plt.xlabel('Galactic Longitude')
    plt.ylabel('Galactic Latitude')
    plt.title('WCSAxes plot')

fig.tight_layout()
plt.show()
```
**`projection=None`, no tight_layout:**
![Figure_1](https://user-images.githubusercontent.com/6197628/57730604-ba088700-7690-11e9-92b1-689c40cc3f76.png)
**`projection=None`, with tight_layout:**
![Figure_1](https://user-images.githubusercontent.com/6197628/57730646-d73d5580-7690-11e9-8875-63e92e5506ce.png)
(note how this re-organises things nicely)
**`projection='wcs'`, no tight_layout:**
![Figure_1](https://user-images.githubusercontent.com/6197628/57730714-fe942280-7690-11e9-98b2-c827b64aabaa.png)
**`projection='wcs'`, with tight_layout:**
![Figure_1](https://user-images.githubusercontent.com/6197628/57730759-123f8900-7691-11e9-9bbd-2e2fae288151.png)
Note how things actually get worse!

- astropy 3.1.2
- Matplotlib 3.0.3

**Comment by pllim** [comment]
Is this related to https://github.com/astropy/astropy/issues/8678#issuecomment-491523170 ?

**Comment by dstansby** [comment]
I don't think so, that is only a problem on Matplotlib dev (post version `3.0.3`), whereas this is an issue on a version of Maptlotlib (`3.0.3`) that predates that change.

**Comment by astrofrog** [comment]
I have some ideas :)

**Comment by astrofrog** [comment]
A workaround for now is to call:

```
fig.canvas.draw()
```

before

```
fig.tight_layout()
```

Basically the fundamental issue is that ``get_tightbbox`` actually requires the figure to be drawn once before it returns correct results. We should probably find a way to avoid this - but in the mean time we could overload ``tight_layout`` in ``WCSAxes`` and just force a draw first.

**Comment by dstansby** [comment]
For reference, some simpler code to reproduce this:
```python
import matplotlib.pyplot as plt

from astropy.wcs import WCS
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename

filename = get_pkg_data_filename('galactic_center/gc_msx_e.fits')

hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)

fig = plt.figure(figsize=(8, 6))
axs = [fig.add_subplot(2, 1, i, projection=wcs) for i in [1, 2]]

fig.tight_layout()
plt.show()
```

**Comment by dstansby** [comment]
As I slowly descend into madness trying to work this out, a note that the end goal to get this working is to have `TickLabels` and `AxisLabels` have their own `get_tight_bbox()` methods that can calculate their own Bboxes. This is going to need a **lot** of refactoring, but I suspect in the long run it should significantly tidy up the WCSAxes code.
