### ISSUE TITLE
How to cutou2D a large image to .png patches, keeping reference on my initial fits image?

### ISSUE THREAD

**Issue by rasputin1917** [astropy/astropy#8704]
Hi all,

I have an huge `.fits` image which I would like to cut to smaller patches converting at the same time the patch  in a `.png` form. 

This `.png` image, I would like to know how do I give it a reference to the initial huge image.

For example, if I choose a `(x,y)` point at my` .png` patch, I would like to know where exactly it is located in the initial `.fits` image

Please any ideas?

**Comment by bsipocz** [comment]
Hi @rasputin1917!

This question would be perfect to be asked on the other forums that have thousands of users with diverse approaches. They are listed on this page: https://www.astropy.org/help.html

**Comment by saimn** [comment]
Maybe with [PyAVM](https://github.com/astrofrog/pyavm) ? APLpy has some support for this: https://aplpy.readthedocs.io/en/stable/fitsfigure/howto_avm.html

I'm closing the issue since this does not concern astropy directly.
