### ISSUE TITLE
UnicodeDecodeError during fits.Header.fromfile()

### ISSUE THREAD

**Issue by astromancer** [astropy/astropy#8711]
MWE:
```
import numpy as np
from astropy.io import fits

fn = 'test.fits'
data = np.random.randn(1, 1)
hdu = fits.HDUList(fits.PrimaryHDU(data))
hdu.writeto(fn, overwrite=True)
header = fits.Header.fromfile(fn)
```

produces:

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-32a656c8e40e> in <module>
      6 hdu = fits.HDUList(fits.PrimaryHDU(data))
      7 hdu.writeto(fn, overwrite=True)
----> 8 header = fits.Header.fromfile(fn)

/usr/local/lib/python3.6/dist-packages/astropy/io/fits/header.py in fromfile(cls, fileobj, sep, endcard, padding)
    445 
    446             return cls._from_blocks(block_iter, is_binary, sep, endcard,
--> 447                                     padding)[1]
    448         finally:
    449             if close_file:

/usr/local/lib/python3.6/dist-packages/astropy/io/fits/header.py in _from_blocks(cls, block_iter, is_binary, sep, endcard, padding)
    474         # Read the first header block.
    475         try:
--> 476             block = next(blocks)
    477         except StopIteration:
    478             raise EOFError()

/usr/local/lib/python3.6/dist-packages/astropy/io/fits/header.py in block_iter(nbytes)
    437             def block_iter(nbytes):
    438                 while True:
--> 439                     data = fileobj.read(nbytes)
    440 
    441                     if data:

/usr/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 2883: invalid start byte
```

However, opening the file in binary mode seems to work:
```
with open(fn, 'rb') as fp:
    header = fits.Header.fromfile(fp)
```

**Comment by astromancer** [comment]
Probably can be fixed by modifying this line to open files in binary mode? 
https://github.com/astropy/astropy/blob/eb20883bed9f815a0db177c4fd1474ab4077cfa1/astropy/io/fits/header.py#L438

**Comment by bsipocz** [comment]
@astromancer - Please open a PR if you think you have the fix.

**Comment by pllim** [comment]
I wonder if #8707 would naturally address this... 🤔

**Comment by astromancer** [comment]
@pllim  I don't think so since the example above errors out while reading the file before reaching the `Header.fromstring` method.

**Comment by pllim** [comment]
Now that I look at this more, I don't think `fromfile` does what you think it does. At least inferred from your example, you should use `header = fits.getheader(fn)` (I checked; that works). There is a chance that `fromfile(filepointer)` worked in your case by coincidence. Also, in the code, it seems that it opens in text mode on purpose:

https://github.com/astropy/astropy/blob/eb20883bed9f815a0db177c4fd1474ab4077cfa1/astropy/io/fits/header.py#L435-L438

**Comment by astromancer** [comment]
Interesting.  I somehow missed that code comment about newline handling even though it was right there staring me in the face.  
The reason I was using `fromfile` rather than `getheader` is because I'm dealing with FITS files that tend to be rather large in size - often > 1Gb. `getheader` reads the entire file, which can be quite slow for large files, whereas `fromfile` breaks out as soon as it finds the END card in the header.  
I don't entirely understand the point about handling newlines, but I guess this may be a platform dependent / python 2 vs 3 thing?

**Comment by pllim** [comment]
@astromancer , can you please try `getheader` with `astropy` 3.2rc1 and see if it is performant now due to #8502 ?

**Comment by saimn** [comment]
`Header.fromfile` should work with a FITS file, as well as with a txt file which is probably the reason why the file is opened in text mode. The problem with the text mode is that it is buffered, and if the header is smaller than the buffer size - which is the case with the default buffer size - it will read and decode data bytes.
Opening in binary mode will work only if you make a special case for reading from txt files. 

> getheader reads the entire file, which can be quite slow for large files, 

`getheader` should not be slower, and in particular it doesn't load the data until you access it. Maybe a difference, which was solved a few years ago, is that before the lazy loading all HDUs were parsed when opening a file with `fits.open`.

**Comment by astromancer** [comment]
Indeed!  @pllim: I did a performance test using a pretty big FITS file (1.75 Gb: small header, large data array), and the results are quite similar for v3.1 vs 4.0dev:
```
astropy version: 3.1
'getheader'    : 1.047 ± 0.022 ms
'fromfile'     : 0.221 ± 0.007 ms
```
```
astropy version: 4.0.dev24604
'getheader'    : 1.060 ± 0.169 ms
'fromfile'     : 0.206 ± 0.010 ms
```

Both functions run within about a millisecond which is great!  `getheader` is about x5 times slower, but since it is still very fast this is actually not an issue for me.  In my mind I still had the idea that `getheader` was a lot slower (~30 s or more), which I guess was the case for large files prior to the lazy loading feature was implemented as @saimn points out.

Code used for the speed test:
```python
import os
import sys
from timeit import Timer

import numpy as np
from astropy.io.fits import Header, getheader
from astropy.version import version


def fromfile(_):
    with open(_, 'rb') as fp:
        return Header.fromfile(fp)

#
filename = sys.argv[1]
assert os.path.exists(filename)

print('astropy version:', version)
print(f'File size: {(os.path.getsize(filename) / 1e9):.3f} Gb')

r, n = 10, 100
headers = []
for name in ('getheader', 'fromfile'):
    func = eval(name)
    timer = Timer(f'{name}(filename)',
                  globals={'filename': filename, name: func})
    δt = timer.repeat(r, n)
    μ, σ = np.divide([np.mean(δt), np.std(δt)], n) * 1000
    print(f'{name!r:<15}: {μ:.3f} ± {σ:.3f} ms')

    headers.append(func(filename))

h1, h2 = headers
assert h1 == h2
```

**Comment by pllim** [comment]
Thanks for checking! Since #8713 doesn't quite pass the CI yet and this is no longer and issue for you, I propose we close this issue *and* the PR. What say you?

**Comment by astromancer** [comment]
Yes, I'll use `getheader` from now on!

**Comment by astromancer** [comment]
I closed this before realising @embray had done some additional work on the PR.  Keeping open for now.

**Comment by saimn** [comment]
`getheader` does a bit more than `Header.fromfile` so it is expected than there is a small difference, but it is small enough. Thanks for the timings!
