### ISSUE TITLE
astropy.test() show many errors

### ISSUE THREAD

**Issue by 12Asmaa** [astropy/astropy#8729]
hello,

I am trying to install astropy to work with FITS files but when i run the line:
`astropy.test()`

I get a lot of lines and finally this line below appears:
`6 failed, 10960 passed, 338 skipped, 82 xfailed, 2 xpassed, 2946 warnings in 165.46 seconds`

i am using anaconda's prompt

what should I do regarding this issue?

one more question: where can I get a good documentation for this package?

**Comment by pllim** [comment]
Documentation is available at http://docs.astropy.org/en/stable/ . You could choose to post your test log with the traceback of failed tests. Or if you have a very limited use case for `astropy.io.fits` (i.e., to open and read a regular FITS format) and it is working for you, then you may also choose to forget about those failures.

**Comment by dhomeier** [comment]
In particular, if working with FITS files is your primary or exclusive use case, you might check if any of the 6 failed tests affect that part of Astropy, or simply re-run the tests for this module only with more detailed output:
` astropy.test(package='io.ascii', args='-v')`
But in general, reports on failures in specific setups are of course welcome.

**Comment by astrofrog** [comment]
@12Asmaa could you show us the full output of the tests? (You could copy it to gist.github.io)

**Comment by bsipocz** [comment]
I'm closing as there was no update provided. 

Feel free to reopen with linking to a gist to share the output.
