### ISSUE TITLE
Error in ConfigParser.py code: invalid syntax

### ISSUE THREAD

**Issue by 12Asmaa** [astropy/astropy#8730]
what is wrong in this code? (specifically line 433)
when i try to run a setup.py file for the package (astropy) at the line 433 is shows invalid syntax.

[ConfigParser.txt](https://github.com/astropy/astropy/files/3196734/ConfigParser.txt)

**Comment by pllim** [comment]
Can you please edit your post so that it is more comprehensible? You may use https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet to point straight to the file and LOC in question. Also, please tell us what you *think* is wrong with it and how you think it should be corrected. Thank you for your cooperation.

**Comment by astromancer** [comment]
Your probably trying to install with python 2.7.  

> "Note that the Astropy 3.x series is the first to only support Python 3"
    - [https://www.astropy.org/announcements/release-3.0.html](url)

**Comment by 12Asmaa** [comment]
> Are you trying to install with python 2.7?
> 
> > "Note that the Astropy 3.x series is the first to only support Python 3"
> > - [https://www.astropy.org/announcements/release-3.0.html](url)

No, I am working with pyhton3.7

**Comment by astrofrog** [comment]
@12Asmaa - could you show us the output of:

```
python --version
python setup.py build
```

Thanks!

**Comment by 12Asmaa** [comment]
@astrofrog 

1) The version is:
```
(base) C:\Users\32248\astropy>python --version
Python 3.6.8 :: Anaconda, Inc.
```

2) The second command's output is:
```
(base) C:\Users\32248\astropy>python setup.py build
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
WARNING: You appear to be trying to import astropy from within a source checkout without building the extension modules first.  Attempting to (re)build extension modules: [astropy]
C:\Users\32248\astropy\astropy\utils\console.py:61: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.

  from ipykernel.iostream import OutStream
Rebuilding extension modules [Done]
ERROR: An error occurred while attempting to rebuild the extension modules.  Please try manually running `./setup.py develop` or `./setup.py build_ext --inplace` to see what the issue was.  Extension modules must be successfully compiled and importable in order to import astropy. [astropy]
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from astropy_helpers.setup_helpers import setup
ImportError: cannot import name 'setup'
```

**Comment by 12Asmaa** [comment]
@astromancer 

I have removed all other Python versions and now i am only using 3.6 from Anaconda terminal.
