### ISSUE TITLE
Add `to_value` for `TimeDelta`

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#8732]
It would be very convienit, if `TimeDelta` also would support `to_value` like `Quantities` do,

e.g.

```
>>> TimeDelta(1 * u.day).to_value(u.s)
86400.0
```

**Comment by mhvk** [comment]
@MaxNoe - indeed, I've had the same problem, that I wanted to use the faster `to_value` but then stopped myself from being able to use `TimeDelta` - see #8762 for the very easy fix.
