### ISSUE TITLE
Warn if running on older numpy than astropy is compiled with?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#8734]
Currently, if one builds and installs with numpy >=1.16, but then attempts to run astropy with numpy < 1.16, several modules will not work (e.g., `_erfa`). Should we emit a warning upon importing astropy in this situation? It would mean to somehow keep track of the numpy version used to build (e.g., by writing an `check.py` file as part of the build and installation).

**Comment by astrofrog** [comment]
Any package with C extensions that depends on Numpy is going to have the same issue (I've seen this with a number of them). I'm reluctant to add yet more astropy-specific layers of infrastructure, especially if we are trying to phase out astropy-helpers in future - maybe it would be better to solve this issue in a way that can work for all packages using Numpy C extensions?

**Comment by dhomeier** [comment]
To repeat my comment on #8672, a more informative warning than `ImportError: numpy.core.multiarray failed to import` would certainly be user-friendly. A relatively easy solution might be on `__init__` to `try:` e.g. `from _erfa.core import ufunc` and on failure print a warning that one seems to have an incompatible numpy version installed?

**Comment by mhvk** [comment]
@dhomeier - agreed, though also agree with @astrofrog that if we solve this at the numpy level, it will help more people. Also, this problem is much less likely to bite people: if you are installing astropy yourself, you will presumably be using it with the numpy version you are installing it with!

That said, I think we're not talking about extending astropy helpers, but rather adding extra code in `__init__`, in particular in its `_check_numpy` function - in principle, we could put a try/except around an import of `_erfa.ufunc` there.

**Comment by dhomeier** [comment]
@mhvk - pretty much what I had in mind; perhaps testing first for `minversion(numpy, __minimum_numpy_m_umath__)`, where `__minimum_numpy_m_umath__ = '1.16.0'` would be the version that's guaranteed to already support the newer `_multiarray_umath` module.

**Comment by eteq** [comment]
I like the idea @dhomeier and @mhvk are proposing here (and agree it doesn't need to involve the helpers), but I don't think it actually needs to be in `astropy/__init__.py`, does it? Isn't it sufficient to do it at the top of `_erfa/__init__.py`?  That way we don't inject an immediate on-import requirement of the erfa imports.

**Comment by astrofrog** [comment]
We’ll need to be careful about not catching exceptions due to the extension not being compiled at all (e.g. in a dev checkout)

**Comment by dhomeier** [comment]
I was wondering if there was a way to penetrate directly to the more specific
```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```
in the numpy import, but could not find a way to access it at the Python level.
I also found one module error that did not go through the `_erfa.ufunc` import route:
```
>>> import astropy.stats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python3.7/site-packages/astropy/stats/__init__.py", line 14, in <module>
    from .funcs import *
  File "/sw/lib/python3.7/site-packages/astropy/stats/funcs.py", line 22, in <module>
    from . import _stats
  File "__init__.pxd", line 918, in init astropy.stats._stats
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by bsipocz** [comment]
Since we moved to 1.16+, and in the era of NEP29, we might not need this?

**Comment by mhvk** [comment]
Yes, I think this can be closed. Thanks!
