### ISSUE TITLE
Generalize release procedure docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8746]
Currently the release procedures in the dev docs have some bits that are quite specific to the core package, such as having release branches. It would be good to try and clean this up and generalize it to make it clear which steps are optional if not using branches, and also to make it clearer that the instructions can apply to any package in the Astropy ecosystem.

**Comment by bsipocz** [comment]
There is this page here to be used for non-branching case: http://docs.astropy.org/en/latest/development/astropy-package-template.html

**Comment by astrofrog** [comment]
Ah, great! In that case I'll close this :)

**Comment by pllim** [comment]
Oh, I did not know about that page. Thanks for pointing it out, @bsipocz !

**Comment by bsipocz** [comment]
it's not as detailed and up to date as the main release procedure page, so I always default to consult the latter when I need it...
