### ISSUE TITLE
Make coordinates.solar_system_ephemeris accept local ephemeris file

### ISSUE THREAD

**Issue by rhandberg** [astropy/astropy#8750]
`astropy.coordinates.solar_system_ephemeris.set()` currently (version 3.1) has the possibility of accepting one of the presets (e.g. 'builtin', 'de430') or an URL pointing to another ephemeris to use. But if I have an ephemeris already downloaded to a local file, it does not allow me to pass the path to this local file to use.

It doesn't work to specify the local file in URL format either i.e. "`file://path/to/file.bsp`".

My suggestion would be to either make it possible to specify a local file either using the URL format specified above or allowing to pass the path to the local file directly.

**Comment by pllim** [comment]
Yes, that is a reasonable request and should be supported IMHO. It looks like this logic below does not yet support a local data file:

https://github.com/astropy/astropy/blob/33962dddfa675c439638ed5e85a607711df8c31f/astropy/coordinates/solar_system.py#L158-L172

The workaround for now, I guess, is to upload your data file to the internet, so it can be downloaded back and cached... 😬

**Comment by Cadair** [comment]
or just run `python -m http.sever` in the directory it is in so you can put in a `localhost:8000` url?!

**Comment by pllim** [comment]
@Cadair , you mean `http.server` or `http.severe`? :trollface:

**Comment by mhvk** [comment]
Very much in favour - this was an oversight in the implementation. Possibly the way to go would be to do the `download_file(value)` only in the branch where a URL is detected, and otherwise just try `SPK.open(value)` directly.

@rhandberg - would you be able to try this, and perhaps make a PR?

**Comment by rhandberg** [comment]
@mhvk - I'll give it a try... PR coming soon!
