### ISSUE TITLE
DOC: include estimated accuracy of built-in solar system ephemeris calculations

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8751]
According to the SOFA docs page, the accuracy of the [default algorithm in astropy calculations](http://docs.astropy.org/en/stable/coordinates/solarsystem.html) is:
```
**  5) The algorithm is due to J.L. Simon, P. Bretagnon, J. Chapront,
**     M. Chapront-Touze, G. Francou and J. Laskar (Bureau des
**     Longitudes, Paris, France).  From comparisons with JPL
**     ephemeris DE102, they quote the following maximum errors
**     over the interval 1800-2050:
**
**                     L (arcsec)    B (arcsec)      R (km)
**
**        Mercury          4             1             300
**        Venus            5             1             800
**        EMB              6             1            1000
**        Mars            17             1            7700
**        Jupiter         71             5           76000
**        Saturn          81            13          267000
**        Uranus          86             7          712000
**        Neptune         11             1          253000
```
It would be nice to have these numbers immediately shown in the docs to evaluate whether it is necessary to use more accurate methods.  That was my first question on getting to the page, as I need about a few arcsec for Jupiter.

**Comment by jgf5013** [comment]
@taldcroft - would like to take this for my first issue if that's alright. Will work on the PR in the meantime.

**Comment by taldcroft** [comment]
Great!

**Comment by mhvk** [comment]
Good idea! @jgf5013 - note that the position of the `Earth` is calculated with a more accurate routine than that used for the other planets; check the comments in `cextern/erfa/epv00.c`.

**Comment by jgf5013** [comment]
I've read through most of the conventions/guidelines, got all the dependencies etc. installed and am working on building the documentation to make sure what I'm adding to `docs/coordinates/solarsystem.rst` gets built right but the `python setup.py build_docs` command is taking a really long time. Any suggestions for how to speed that up? The process has been running for ~20 minutes and I'm only a little over 54% through the 'reading sources...' section
```
reading sources... [ 55%] api/astropy.time.TimeUnix
reading sources... [ 55%] api/astropy.time.TimeYearDayTime
reading sources... [ 55%] api/astropy.time.TimezoneInfo
```

Also, @mhvk - can you give a little more detail on what you'd like me to make reference to in [cextern/erfa/epv00.c](https://github.com/astropy/astropy/blob/master/cextern/erfa/plan94.c)? I don't see any comments there related to accuracy of the measurement for Earth. Could very well just be missing something...

Finally, are there any standards for branch naming conventions? I didn't see any.

Thanks!

**Comment by pllim** [comment]
Re: Doc build -- It taking some time to build is a known issue; xref #7080 😬 . FWIW, once it went through the first pass, unless you clean the built files, subsequent builds will only rebuild modified files and will take shorter time to complete. And if you absolutely can't get it to complete on your machine, then you can skip building the docs locally and rely on our CircleCI job to do it for you.

**Comment by pllim** [comment]
Re: Branch naming standards -- There is no rule on what to name your feature branch, but preferably something descriptive enough but concise, and does not violate our code of conduct.

**Comment by mhvk** [comment]
@jgf5013 - in https://github.com/astropy/astropy/blob/master/cextern/erfa/epv00.c (note that you linked to plan94 above), you'll see comments about the precision under note 4. I would just put a note in your text that for the Earth proper the built-in ephemeris uses a more accurate routine, and then give the corresponding numbers. (If this is unclear, maybe just push your branch up to your own github fork and point us to it or even just do the PR.)

**Comment by jgf5013** [comment]
Ah, yea, good call, mhvk, I meant to link  epv94. Building the docs for me is still taking way too long (I've restarted it a few times but the current run is about 60 minutes in and for the last 45 it's been hanging on the section below.
```
computation time summary:
    - ..\examples\io\split-jpeg-to-fits.py: 0 sec
    - ..\examples\io\skip_create-large-fits.py: 0 sec
    - ..\examples\io\plot_fits-image.py: 0 sec
    - ..\examples\io\modify-fits-header.py: 0 sec
    - ..\examples\io\fits-tables.py: 0 sec
    - ..\examples\io\create-mef.py: 0 sec
    - ..\examples\coordinates\rv-to-gsr.py: 0 sec
    - ..\examples\coordinates\plot_sgr-coordinate-frame.py: 0 sec
    - ..\examples\coordinates\plot_obs-planning.py: 0 sec
    - ..\examples\coordinates\plot_galactocentric-frame.py: 0 sec
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 1168 added, 0 changed, 0 removed
C:\Users\jgf50\AppData\Roaming\Python\Python37\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
reading sources... [ 95%] uncertainty/index
```
If anyone wants to take this that can do it faster, please by all means do. If not, I'll try removing some of the sub-doc folders (especially `docs/uncertainty`) before running next time. Will obviously not commit those removals. If that doesn't work, I'll look into CircleCI as pllim suggested. Sorry again this is taking a while. Clearly my first astropy issue...

**Comment by mhvk** [comment]
Hmm, I hadn't build the documentation for a long time, but it definitely has gotten rathesubstantiallyr slow, with a second part in which actual calculations seem to be done particularly bad. Still, it did finish within ~15 minutes (on my admittedly very nice laptop), which suggests there is something wrong on yours.

My suggestion would be to push your work to your own fork first, and we can have a look, perhaps identifying any obvious problems for the docs before making a real PR.

**Comment by mhvk** [comment]
@pllim - off-topic, but is rebuilding the docs still faster a second time for you? For me, I recall the "reading sources" part to be much faster, but it doesn't seem to be like that any more.

**Comment by pllim** [comment]
@mhvk , I think some performance examples got in. I vaguely remember recommending skipping those, as they take up time to run due to the nature of the doc, but I think they got merged without being skipped anyway. I think @saimn has a way to smoke out the slowest running doctest ?

**Comment by jgf5013** [comment]
@mhvk - I couldn't actually build it (`python setup.py build_docs`) until I removed the `/whatsnew` and `/uncertainty` folders. Since doing that, the build runs in a little under 25 minutes on my somewhat crappy laptop (2 AMD cores, 4 logical processors, Windows 10 OS) without any other major processes running. The _reading sources_ step takes up a large majority of the time.
Anyway, got it building now so I'll correct my formatting issues and send the PR tomorrow afternoon Eastern Time.

**Comment by mhvk** [comment]
@jgf5013 - you are definitely supposed to be able to build without removing anything! I think this is well worth raising a separate issue; fine to just copy/summarize what was written here. We may want to have a docs build on windows to prevent issues like this (if we don't already...)

**Comment by jgf5013** [comment]
Okay, I will create an issue for that this afternoon. I'm trying to push my changes now, following the instructions on [Condensed example of contributing code to Astropy](https://docs.astropy.org/en/stable/development/workflow/command_history.html) but getting the error below. Any idea why I'm getting this?

```
PS C:\workspace\astropy\astropy> git push --set-upstream jgf5013 i-8751-ss-ephemeris-accuracies
remote: Permission to astropy/astropy.git denied to jgf5013.
fatal: unable to access 'https://github.com/astropy/astropy.git/': The requested URL returned error: 403
```

Also, I'm used to setting up branches, etc. and contributing directly into origin repo, not setting up a separate remote origin (_jgf5013_, in my case). Is this still the recommended approach? I suppose that's fairly common in open source source control?

**Comment by mhvk** [comment]
@jgf5013 - it looks like your `jgf5013` is defined wrong. You can check with
```
git remote -v
```
what things point at (and adjust with `git remote` as well; see `git remote --help`)

**Comment by jgf5013** [comment]
Ah, yup!! Thanks @mhvk! PR submitted. I didn't see any way to right-align the table values with sphinx other than switching to raw html with css or using some sphinx plugins. Let me know if you'd like me do either of those.

Thanks again!

**Comment by saimn** [comment]
@pllim :
> I think @saimn has a way to smoke out the slowest running doctest ?

Not really, sadly. There is the `--durations` flag which reports the slowest tests, it works for doctest in rst files as well but reports only the total time for the files:
```
❯ pytest --remote-data=any --doctest-rst docs/ --durations=10 -vv
...
================================== slowest 10 test durations ==================================
9.36s call     docs/wcs/wcsapi.rst
8.78s call     docs/coordinates/frames.rst
4.92s call     docs/timeseries/index.rst
0.88s call     docs/visualization/normalization.rst
0.66s call     docs/units/decomposing_and_composing.rst
0.58s call     docs/time/index.rst
0.57s call     docs/coordinates/performance.inc.rst
0.51s call     docs/coordinates/index.rst
0.28s call     docs/timeseries/bls.rst
0.22s call     docs/coordinates/velocities.rst
================================= 200 passed in 30.92 seconds =================================

```

**Comment by saimn** [comment]
Reading the discussion above, I think that the docs build is slow for various reasons: many files, with a lot of code examples, figures, etc. Not sure if there is a way with Sphinx to identify the slowest parts.

**Comment by saimn** [comment]
@jgf5013 - Are you using matplotlib 3.1.0 ? This would explain the slowness when building the docs, especially for `uncertainty/index`. This page took 30min and 9.5Gb of RAM for me with matplotlib 3.1! This will be fixed in their next release.

**Comment by jgf5013** [comment]
Ah. Yup!
```
C:\workspace\astropy\astropy>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.__version__
'3.1.0'
>>>
```
