### ISSUE TITLE
DeprecationWarning: elementwise comparison failed in Quantity

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8752]
Looking at #7928 , there are a lot of warnings like this:

```
astropy/nddata/mixins/tests/test_ndarithmetic.py::...
  .../astropy/units/quantity.py:858: DeprecationWarning: elementwise comparison failed;
this will raise an error in the future.
    return super().__ne__(other)
```

Which brought me to

https://github.com/astropy/astropy/blob/33962dddfa675c439638ed5e85a607711df8c31f/astropy/units/quantity.py#L855-L860

Perhaps `try ... except ...` is not working as expected? Why not use [catch_warnings](https://docs.python.org/3/library/warnings.html#warnings.catch_warnings)? @mhvk , do you know?

**Comment by mhvk** [comment]
I should really get rid of that altogether, and may even have a branch somewhere. Though in `Time` at least, I found that this ended up being a poor implementation there... (#8355).

**Comment by mhvk** [comment]
Hmm, indeed, I do have an old branch. Checking whether it is still viable...
