### ISSUE TITLE
Fits memmap, "buffer is too small for requested array" Error

### ISSUE THREAD

**Issue by luojing1211** [astropy/astropy#8766]
Hi Astropy developers, 
I am reading a big fits file using memmap method. However, I got a TypeError. has anyone seen this before? What is the correct way to read a big file (> 2GB)?

Thank you. 
Useage:
```
>>> x = fits.open("big_fits_file.fits", memmap=True)
>>> x
[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x7fc1830c9908>, <astropy.io.fits.hdu.table.BinTableHDU object at 0x7fc1830cf128>]
>>> x[1].data[0]
TypeError                                 Traceback (most recent call last)
<ipython-input-87-2cd5f5ec1899> in <module>()
----> 1 x[1].data[0]

~/Projects/astropy/astropy/utils/decorators.py in __get__(self, obj, owner)
    742                 return val
    743             else:
--> 744                 val = self.fget(obj)
    745                 obj.__dict__[self._key] = val
    746                 return val

~/Projects/astropy/astropy/io/fits/hdu/table.py in data(self)
    404     @lazyproperty
    405     def data(self):
--> 406         data = self._get_tbdata()
    407         data._coldefs = self.columns
    408         data._character_as_bytes = self._character_as_bytes

~/Projects/astropy/astropy/io/fits/hdu/table.py in _get_tbdata(self)
    170         else:
    171             raw_data = self._get_raw_data(self._nrows, columns.dtype,
--> 172                                           self._data_offset)
    173             if raw_data is None:
    174                 # This can happen when a brand new table HDU is being created

~/Projects/astropy/astropy/io/fits/hdu/base.py in _get_raw_data(self, shape, code, offset)
    473                               offset=offset)
    474         elif self._file:
--> 475             return self._file.readarray(offset=offset, dtype=code, shape=shape)
    476         else:
    477             return None

~/Projects/astropy/astropy/io/fits/file.py in readarray(self, size, offset, dtype, shape)
    332 
    333                 return np.ndarray(shape=shape, dtype=dtype, offset=offset,
--> 334                                   buffer=self._mmap)
    335             else:
    336                 count = reduce(operator.mul, shape)

TypeError: buffer is too small for requested array
```

**Comment by saimn** [comment]
Hi @luojing1211 ,

Reading big files is supported, you're using the correct way.
Could you give more information about your system and astropy version ?
Also cold you try with `memmap=False` ?

**Comment by luojing1211** [comment]
Astropy version: '3.2.dev24009'
system info:
Memory 15.4 GiB
Processor Intel® Xeon(R) W-2123 CPU @ 3.60GHz × 8 
OS: Intel® Xeon(R) W-2123 CPU @ 3.60GHz × 8 

If I run without the memmap, the kernel will crash.

**Comment by saimn** [comment]
You mean the Python kernel ?
Can you run `fits.info("big_fits_file.fits")` to have more details on the file ? If you can share the file (with a private link if needed), I can have a look.

**Comment by luojing1211** [comment]
Hi Simon, 
Yes, it was Python Kernel. 
The input file inform:
Filename: /hdd/fits_data/big_fits_file.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      57   ()      
  1  SUBINT        1 BinTableHDU     74   660R x 17C   [1D, 1D, 1D, 1D, 1D, 1D, 1D, 1E, 1E, 1E, 1E, 1E, 128E, 128E, 512E, 512E, 65011712B]   
WARNING: File may have been truncated: actual file length (2153476096) is smaller than the expected size (42911176320) [astropy.io.fits.file]

This is a part of our data set, I will have to ask permission to share the data with you.

**Comment by pllim** [comment]
What are the values of the following?

```python
>>> x._file.memmap
>>> x._file._mmap_available
>>> x._file._mmap
```

**Comment by saimn** [comment]
@luojing1211 - Are you sure that the file is not truncated ? Can you read it with another fits library like [fitsio](https://github.com/esheldon/fitsio) ?

**Comment by luojing1211** [comment]
@pllim 
This is the result I have:
```
print(x._file.memmap)
print(x._file._mmap)
print(x._file._mmap_available)
True
None
True
```

**Comment by mhvk** [comment]
@saimn - your suggestion makes sense - @luojing1211 just mentioned to me offline that the file was the last of a series and it is at least conceivable that the recording was stopped mid-way to writing it. We'll check that first.

**Comment by luojing1211** [comment]
I had a test with a complete file and it runs without error. Thank you.

**Comment by srinadh99** [comment]
I'm getting the same issue when using getdata, would someone suggest on how to fix this.
x= fits.getdata("jdba2sooq_flc.fits") i'm using and its showing 
"TypeError: buffer is too small for requested array"

**Comment by pllim** [comment]
@srinadh99 , that is a HST/ACS image. First, make sure your file is not corrupted. Then, make sure you are using the latest version of Astropy. Maybe also make sure you are not still using Python 2. If you still have problem, please contact STScI Help Desk at https://stsci.service-now.com/hst

**Comment by mhvk** [comment]
@srinadh99 - just to be clear, for us the issue was a corrupted file.

**Comment by thriveth** [comment]
I am getting the same error with a MUSE cube. The file opens fine in DS9 and QFitsView, so I don't... suppose? That it is corrupted?

**Comment by saimn** [comment]
@thriveth - It's the most likely reason. Maybe DS9 and QFitsView handle this nicely as they only read some wavelength planes. Could you try `fitsinfo` (command-line) or `fits.info()` (Python) on your file ?

**Comment by thriveth** [comment]
It was indeed corrupted. Sorry for the noise.

**Comment by awesomecosmos** [comment]
Hi there, I am also getting a ```TypeError: buffer is too small for requested array```. My file is not corrupt, as it can be read using ```fits.getdata(myfile)```, and produces the following output:
```
array([[33819, 41545, 43468, ..., 33848, 32395,   906],
       [36881, 42472, 41093, ..., 34009, 34370, 25881],
       [40477, 42894, 42697, ..., 34583, 35464, 28418],
       ...,
       [47095, 46065, 46288, ..., 40629, 39980, 40556],
       [45819, 46896, 45066, ..., 39947, 40941, 40205],
       [46460, 45709, 46772, ..., 40839, 39890, 39803]], dtype=uint16)
```
Any idea as to what could be causing the issue? I am updated to the latest version of Astropy (v.4.2.1). Many thanks in advance.

**Comment by saimn** [comment]
`fits.getdata` reads only the first data unit, it could be that your file has more HDU and is truncated ? Could run `fitsinfo yourfile.fits` or share it ?

**Comment by suvenduat** [comment]
I am having the same issue while trying to append some keywords to the header using astropy.io.fits. 
WARNING: File may have been truncated: actual file length (2100032) is smaller than the expected size (2102400) [astropy.io.fits.file]

and the error:
TypeError: buffer is too small for requested array

The files can be viewed using DS9 without any issue.

I got the following from fitsinfo:
fitsinfo J0114p1325_R_300_1024x1024_4.fits
WARNING: File may have been truncated: actual file length (2100032) is smaller than the expected size (2102400) [astropy.io.fits.file]
Filename: J0114p1325_R_300_1024x1024_4.fits
No. Name Ver Type Cards Dimensions Format
0 PRIMARY 1 PrimaryHDU 29 (1024, 1024) int16 (rescales to uint16)
I posted this issue here:
https://github.com/astropy/astropy/issues/13356

Any solution? I can post the code here that I using to append.

**Comment by Ektasai** [comment]
Hi,
I am facing a similar issue while trying to read an AstroSat LAXPC event (.evn) file using astropy.
Here is the code I am using:
```python
hdul = fits.open("/content/lxp2level2.evn")
hdul.info()
``` 
I get the following warning:
```python
WARNING: File may have been truncated: actual file length (23040) is smaller than the expected size (106729920) [astropy.io.fits.file]
WARNING:astropy:File may have been truncated: actual file length (23040) is smaller than the expected size (106729920)
Filename: /content/lxp2level2.evn
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      37   ()      
  1  LAXPC_MODE_EA    1 BinTableHDU     47   8893052R x 4C   [D, I, B, B]   
``` 
When I try to access the data:
```python
data = hdul[1].data
``` 
I get errors like:
```python
- "buffer is too small for requested array"
- - "cannot reshape array"
``` 
My questions:
1. Is this error always due to file corruption/truncation?
2. Is there any way to safely read partial data from such a file?
3. Are there recommended settings in astropy to handle such cases?

I also tried:
fits.open(..., memmap=False, ignore_missing_end=True)
but still faced reshape errors.

Any guidance would be very helpful.

Thanks.

**Comment by pllim** [comment]
Does this "evn" follow FITS standard? Are you using the correct package? Please contact the mission help desk.

**Comment by Ektasai** [comment]
> Does this "evn" follow FITS standard? Are you using the correct package? Please contact the mission help desk.

Yes, the .evn file appears to follow the FITS standard, as the header begins with SIMPLE = T.

I am currently using astropy.io.fits, and the same code works correctly for a barycenter-corrected file. However, it fails for this particular file with truncation and reshape-related errors.

Because of this, I am unsure whether the issue is due to file corruption/incomplete download or something specific to this dataset. I would appreciate any guidance on how to proceed. (I believe there is should be no problem with the downloading)

**Comment by saimn** [comment]
Giving the size difference in the error message (`actual file length (23040) is smaller than the expected size (106729920)`), yes it seems the file is truncated and you're missing most of the data. Did you try downloading again ?

**Comment by Ektasai** [comment]
yes i did
