### ISSUE TITLE
stats.bayesian_blocks false alarm probability doesn't correspond to the asked parameter

### ISSUE THREAD

**Issue by mdebony** [astropy/astropy#8768]
Hi,

I'm currently using stats.bayesian_blocks with the fitness event. Due to the warning in this case I run some test.
I have generated randomly generated events lists using an exponential distribution for determining the dt between events. I have used different number of events and scale of the exponential distribution.
I have tested with a p0 = 0.01 and with 102400 events lists. 

I obtained an effective false alarm probability of 0.0045 +/- 0.0002.

I've read the previous discussions on this subject where it was said there might be a problem with the calibration.
How I can make a valid calibration ?

Thanks,

**Comment by pllim** [comment]
Hi. Can you please link to the "previous discussions" mentioned?

@jakevdp , if you could chime in, that would be really appreciated. Thanks! 🙏

**Comment by mdebony** [comment]
I've looked at these issues concerning this warning: https://github.com/astropy/astropy/issues/6922, https://github.com/astropy/astropy/issues/5826, https://github.com/astropy/astropy/issues/4927

**Comment by jakevdp** [comment]
The false alarm probability was calibrated empirically as part of the Scargle paper that proposed the method. I would expect that if you use different simulation parameters to check it, you would find a different result. I'd suggest taking a look at the paper to see where your experiments differ from theirs: https://arxiv.org/abs/1207.5578

**Comment by mdebony** [comment]
Thanks I'll try to do it that way.
