### ISSUE TITLE
FITS Selecting Records in a Table

### ISSUE THREAD

**Issue by CA4GitHub** [astropy/astropy#8772]
The Astropy guide http://docs.astropy.org/en/stable/io/fits/usage/table.html#selecting-records-in-a-table shows 2 methods for updating the HDU data.
The 2nd method does an update in-place.
I noticed this method can rearrange the keys returned by hdu.header.keys().

Why does this happen?

Where in the source code does this happen?

I don't believe this happens for the 1st method for updating the HDU data.  Thus, the 2 examples shown don't result in identical HDU objects.

**Comment by pllim** [comment]
I just ran those examples with astropy 4.0.dev24705 and I don't see the difference. In fact, `fitsdiff newtable.fits newtable2.fits` says no difference found. Can you please post a snippet of the actual code that you ran and show us the output that you see? Thanks.

**Comment by CA4GitHub** [comment]
The problems I see are with a FITS file I'm building & not the file in the example on the link.  I've also tested using `astropy.__version` = 2.0.12 with python 2 and `astropy.__version` = 3.0.4 with python 3.

The difference I'm seeing is in the order of the BinTableHDU header keys.  Specifically some of the TTYPEx, TFORMx, and TUNITx.  For all TTYPEx, TFORMx, and TUNITx for x>38, the second print statement has moved them to the end (i.e. printed last).  Interestingly, TFIELDS is 38 even though the `hdul[1].header.keys` shows TTYPEx, TFORMx, and TUNITx for 1 <= x <= 61.

`maskOfRowsToKeep = hdul[1].data[keyToThreshold] <= threshold
print(hdul[1].header.keys)
hdul[1].data = hdul[1].data[maskOfRowsToKeep]
print(hdul[1].header.keys)`

The 2 print statements are identical if the assignment becomes `hdul[1].data = hdul[1].data`.
The 2 print statements are not identical if the assignment becomes `hdul[1].data = hdul[1].data[:]`

It appears the assignment operator (i.e. =) is causing some issues.

The following example also results in the print statement showing different results:
`maskOfRowsToKeep = hdul[1].data[keyToThreshold] <= threshold
print(hdul[1].header.keys)
temp = hdul[1].data.copy()
hdul[1].data = temp
print(hdul[1].header.keys)`

**Comment by pllim** [comment]
@CA4GitHub , is it possible for you to share a full working example to illustrate the problem you are seeing? It is hard to know what is happening with only bits and pieces. Also I recommend trying either the dev version or 3.2rc1 .

**Comment by saimn** [comment]
I could not reproduce either, please share an example to reproduce the issue.
