### ISSUE TITLE
Astropy:docs contains an error in catalog matching examples

### ISSUE THREAD

**Issue by emmam42** [astropy/astropy#8796]
This example for coordinate matching seems to have an error on [astropy:docs](http://docs.astropy.org/en/stable/coordinates/matchsep.html#astropy-coordinates-matching) where in the third line, "idx < max_sep" should be "d2d < max_sep" as it should be that the distance between the objects should be less than the maximum separation, not the index of the match. 

`
>>> max_sep = 1.0 * u.arcsec 
>>> idx, d2d, d3d = c.match_to_catalog_3d(catalog) 
>>> sep_constraint = idx < max_sep 
>>> c_matches = c[sep_constraint] 
>>> catalog_matches = c[idx[sep_constraint]] `

**Comment by adrn** [comment]
Yes, this is an error! But it is already fixed in the latest documentation pages:
http://docs.astropy.org/en/latest/coordinates/matchsep.html#astropy-coordinates-matching
Thanks for catching this!
