### ISSUE TITLE
implement data.astropy.org server with version hashes

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#88]
The current `config.data` package expects to be looking in `data.astropy.org` to find remote data files... and such a server does not yet exist.  It should carry necessary data that we don't want in the source code, and should also support specific versions of files via `data.astropy.org/hash/395dd6493cc584df1e78b474fb150840`.

**Comment by astrofrog** [comment]
http://data.astropy.org now works but we've not got the infrastructure to do the hash stuff (and not sure we've needed it yet). Not high priority so removing milestone.

@astronomeralex - sorry for not replying sooner! In the end we are using a server at STScI so we should be ok in terms of computational resources.

**Comment by astronomeralex** [comment]
@astrofrog -- that's fine. this dropped off my radar. glad everything worked out.

**Comment by pllim** [comment]
I think it is time for me to move http://stsdas.stsci.edu/astrolib/vo_databases/ (for `astropy.vo.client` and `astropy.vo.validator`) to a proper place in `data.astropy.org`. How do I accomplish this?

**Comment by astrofrog** [comment]
@pllim - you can add files to data.astropy.org by adding them to the following repository:

https://github.com/astropy/astropy-data

Every time a commit is made, the repo is synced to the website.

**Comment by pllim** [comment]
@astrofrog , my data files change every night. They are output files from nightly run of `vo.validator` to validate a selected list of 30 Cone Search providers. Is there no way for direct upload or something? By the time someone merges the PR, the files might be outdated already.

**Comment by pllim** [comment]
Is this still relevant? @jhunkeler manages the server currently at STScI.

**Comment by pllim** [comment]
Six years have passed. Now there are technologies like `git lfs`, so we definitely should not re-invent the wheel.

**Comment by eteq** [comment]
@pllim - I agree that git lfs is the way to go if/when we need to.  The main problem right now is that that costs 💰 , and the current server is free...

**Comment by astrofrog** [comment]
Is there really still a use case for doing the hash stuff anyway? We've gone this far without it, so maybe worth just closing this issue?

**Comment by pllim** [comment]
> We've gone this far without it, so maybe worth just closing this issue?

Sure!
