### ISSUE TITLE
Negative FWHM in Moffat1D

### ISSUE THREAD

**Issue by simontorres** [astropy/astropy#8801]
I'm making an application to get the best focus for an instrument. I'm using a Moffat1D model to fit the profile and for some reason gamma is negative (which does not matter and I assume it is correct) but when I get the FWHM is negative as well, which as far as I know does not make sense in astronomical images (or any). It seems to me that there is a mistake regarding the formula, see this comment:  https://github.com/astropy/astropy/pull/6027#issuecomment-300380649

from the second-last to the last line 
![CodeCogsEqn](https://user-images.githubusercontent.com/3878895/58985877-4a2a7f80-87aa-11e9-9572-a6559bf92b81.gif)
and thus  (should be)
![CodeCogsEqn_fwhm](https://user-images.githubusercontent.com/3878895/58986494-7eeb0680-87ab-11e9-9ce2-e43854de238f.gif)

and using the notation in [astropy's documentation](http://docs.astropy.org/en/stable/api/astropy.modeling.functional_models.Moffat1D.html#astropy.modeling.functional_models.Moffat1D) the FWHM should be:

![CodeCogsEqn_astropy_fwhm](https://user-images.githubusercontent.com/3878895/58986584-b8237680-87ab-11e9-8933-a6214a29def2.gif)

Hopefully someone has  a better insight in this, I will workaround this making `gamma` absolute value always.

I can make a PR if this is really something worth doing.

# reference plot and model

![moffat_fitted](https://user-images.githubusercontent.com/3878895/58985082-89f06780-87a8-11e9-855f-f8eacda3d8f5.png)

The model

```
Model: Moffat1D
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Parameters:
      amplitude       x_0          gamma         alpha    
    ------------- ------------ -------------- ------------
    248.392233095 2065.9401953 -90.3411844413 1161.3273732
```

**Comment by pllim** [comment]
@ysBach, what do you think?

**Comment by ysBach** [comment]
@pllim Sorry for not being respondent for few days.
I think @simontorres is absolutely right. 

Due to the squaring, the sign of the "core" parameter (``gamma`` of astropy = ``alpha`` of IRAF = R of Moffat's original work) does not matter in Moffat profile calculation, but it does for the current FWHM calculation...

**Comment by pllim** [comment]
@simontorres , pull request is welcome. Please refer to http://docs.astropy.org/en/stable/development/workflow/development_workflow.html . Thank you!
