### ISSUE TITLE
Make RTD requirements configurable

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8820]
We're experiencing RTD timeouts that are for some weird reason correlating with mpl 3.1 (but some builds with that version passed). 
So as a temporary workaround it would  be nice to pin the version number.  However due to  recent refactors there is no separate RTD dependency config file, but `docs` and `all` are picked up from `setup.cfg`.

It would be very awkward to limit the version number in there when the whole issue is an upstream  third party problem.  So I suggest  to bring back the separate file to configure out docs deployment.

@astrofrog?

**Comment by bsipocz** [comment]
(I managed to get a build for 3.2, but temporarily retagging the release, so for now we're good, but there hasn't been a valid built on latest the master branch for quite a while as a result of this issue).

**Comment by pllim** [comment]
**Crazy idea**

READTHEDOCS is True inside RTD build ([ref](https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-behavior-for-read-the-docs)). So when that is detected, we invoke special installations using `subprocess` inside `setup(app)` function in `docs/conf.py` (or is it too late to install stuff at that point?). 😬

**Comment by bsipocz** [comment]
__crazy idea 4__

Bring back the good old `requirements.txt`  or `rtd_requirements.txt` file.
