### ISSUE TITLE
FITS table WCS keywords deprecation warning from BinTableHDU.from_columns()

### ISSUE THREAD

**Issue by stscirij** [astropy/astropy#8830]
Related to #7145
When creating a new FITS table from a header and a `coldefs` object, a deprecation warning is thrown if the header contains any of the keywords that are now set using column attributes (`{'TCTYP', 'TCUNI', 'TCRPX', 'TCRVL', 'TCDLT', 'TRPOS'}`).  The warning is:
```python
warnings.warn("The following keywords are now recognized as special "
                                      "column-related attributes and should be set via the "
                                      "Column objects: {0}. In future, these values will be "
                                      "dropped from manually specified headers automatically "
                                      "and replaced with values generated based on the "
"Column objects.".format(keys), AstropyDeprecationWarning)
```
Does this mean that this will only happen when using `from_columns()` (or `_TableBaseHDU.__init__`, which is where the warning is generated)?  If I create a table with no WCS attributes to the columns, will I always be able to then subsequently set the attributes of the columns either by adding a T keyword to the header or by setting `column.attribute = value`?  

Thanks in advance for any insight

EDIT: Formatting

**Comment by pllim** [comment]
cc @taldcroft, @mhvk, or @aaryapatil

**Comment by saimn** [comment]
This warning is only shown when creating a BinTableHDU manually with `.from_columns`, with the special case added in #7157 which prevents the deletion of these keywords when you provide a header.
But otherwise, these are `Column` attributes and should always be used via their corresponding attribute.

**Comment by mhvk** [comment]
Is there a way to adapt the warning so that it is clearer what to do? Perhaps a link to a relevant section of the documentation?

**Comment by stscirij** [comment]
It's all a bit confusing at the moment.  I ALWAYS get the deprecation warning when using BinTableHDU.from_columns(), even if I do the 'right' thing:

In [1]: from astropy.io import fits                                                                               
In [2]: cols = []                                                                                                 
In [3]: cols.append(fits.Column(name="RAWX", format="1I", unit="pixel"))                                          
In [4]: cols.append(fits.Column(name="RAWY", format="1I", unit="pixel", coord_type='ANGLE', coord_ref_point=1))   
In [5]: header = fits.Header()                                                                                    
In [6]: cd = fits.ColDefs(cols)                                                                                   
In [7]: hdu = fits.BinTableHDU.from_columns(cd, header)                                                           
WARNING: AstropyDeprecationWarning: The following keywords are now recognized as special column-related attributes and should be set via the Column objects: TCRPXn, TCTYPn. In future, these values will be dropped from manually specified headers automatically and replaced with values generated based on the Column objects. [astropy.io.fits.hdu.table]

I didn't put any keywords in the header at all, and only set column attributes, and still got the deprecation warning.

I'm trying to write code that doesn't trigger the deprecation warning, and it seems that it's impossible if I want the new column attributes.

**Comment by saimn** [comment]
@stscirij - Indeed, I think that's a mistake, see #8838.

**Comment by pllim** [comment]
@stscirij , you should not see the warnings anymore in `master`, thanks to patch from @saimn .
