### ISSUE TITLE
MNT: Revert PR 8818 when minversion of matplotlib is 3.2

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8832]
In `astropy/visualization/units.py`, as added in #8818 

```python
    # NOTE: in matplotlib >=3.2, subclasses will be recognized automatically,
    # and once that becomes our minimum version, we can remove this,
    # adding just u.Quantity itself to the registry.
```

**Comment by pllim** [comment]
After a year, the minversion seems to be 2.1

https://github.com/astropy/astropy/blob/bf5fa75f068c7adc56a67bec1b4f29decced96f0/setup.cfg#L68

so this is going to take a while...

**Comment by pllim** [comment]
When can we drop support for matplotlib 3.1 -- @astrofrog ?

**Comment by astrofrog** [comment]
Probably could do it now as it's 3 years old?
