### ISSUE TITLE
Complex amplitudes in models

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy#8833]
I have a _complex_ problem that I'm hoping someone can help me fix. 

I have the first `N` complex terms of the Fourier transform of a 1D data series, which can be used to reconstruct an approximation of the original data series. I would like to represent the approximation using astropy models, which can be achieved using Euler's formula and a combination of `Sine1D` models. However, I need to construct a combination of `Sine1D` models which have complex amplitudes, like this: 

```python
import numpy as np
from astropy.modeling import models

fft = np.array([1323.05768443  +0.j        , -473.6786725 -120.72642364j,
       -199.59351462-147.75512434j,  -11.8952061  -41.34435797j,
         26.37171375 +56.57267775j,  -10.34686085 +61.77508734j,
        -26.32020494 +18.12691033j,    8.11154341  -6.89937425j,
         18.11907541  -6.4711258j ,    9.37345637  +9.30265208j])

N = 100 
n = np.arange(len(fft))
k = np.arange(N)[:, np.newaxis] 

m = models.Sine1D(frequency=k/N, phase=1/4) + models.Sine1D(amplitude=1j, frequency=k/N, phase=0)
```
Presently this raises an issue because the amplitude is expected to be convertable to a float. Is there any way around that?

**Comment by perrygreenfield** [comment]
Any reason you can't cast the model as a combination of sin and cos with real amplitudes?

**Comment by bmorris3** [comment]
I may have just figured it out... if you wrap the complex amplitude in `u.Quantity()` it seems to be working just fine?

**Comment by bmorris3** [comment]
The above mentioned hack only allows you to initialize the model, when computing arithmatic with the models, the real part of the amplitudes is taken.

RE @perrygreenfield -- the only thing preventing me from recasting it is my lack-of cleverness. I'll give it a shot!

**Comment by perrygreenfield** [comment]
@bmorris3 Yes, I'm afraid the assumption of real floats is baked fairly deep in the design. Supporting complex numbers in addition is probably a major change (the interface to fitting would now have to figure out two different types). And generally, it is possible to expose the real and imaginary values as explicit parameters with some work.

**Comment by bmorris3** [comment]
@perrygreenfield I found a solution to my problem [by recasting it as a real-valued-only problem](https://github.com/bmorris3/tynt/blob/master/tynt/core.py#L73-L78).

**Comment by perrygreenfield** [comment]
Excellent! Thanks for working around this.
