### ISSUE TITLE
Ecliptic frames do not have loopback transformations

### ISSUE THREAD

**Issue by ayshih** [astropy/astropy#8835]
Is there an intentional reason that the ecliptic frames (and some others) do not have loopback transformations?  When I want to change equinox or observation time and I neglect to explicitly transform through ICRS or some other frame, I get momentarily confused by the no-op.

**Comment by adrn** [comment]
cc @Juanlu001 @eteq

**Comment by Juanlu001** [comment]
I don't think there is a reason, we should implement them.

**Comment by Juanlu001** [comment]
Related question: https://github.com/astropy/astropy/issues/8996
