### ISSUE TITLE
CDS reader fails on masked columns (CSP DR3)

### ISSUE THREAD

**Issue by djperrefort** [astropy/astropy#8856]
I recently downloaded data from the Carnegie Supernova Project using Vizier and tried to parse the files using the CDS reader in astropy version 3.1.2. Multiple files ended up parsing incorrectly or failed entirely.

Data tables and readme are available at the following link under the "FTP" tab: (http://cdsarc.u-strasbg.fr/viz-bin/cat/J/AJ/154/211)[http://cdsarc.u-strasbg.fr/viz-bin/cat/J/AJ/154/211]

Some files fail to parse (Tables 2 and 3):
```
>>> from astropy.io import ascii
>>> 
>>> readme = 'ReadMe'
>>> r = ascii.get_reader(ascii.Cds, readme=readme)
>>> r.read('table2.dat')

ValueError: Column Dm15(tem)1 failed to convert: could not convert string to float: '---'
```

The first table fails in a different way. The function executes, but there is a column that is empty even though the column is not empty in the file:
```bash
>>> t = r.read('table2.dat')
>>> 
>>> # The n_Host column should not be empty
>>> t['Host', 'n_Host'][:5]

<Table length=5>
     Host     n_Host
    str28      str1 
------------- ------
      NGC 799       
    UGC 12158       
     NGC 6928       
    UGC 11816       
ARP 327 NED04  
```

It would seem that the data that is supposed to be in this column is erroneously put into the next column in the table.

**Comment by taldcroft** [comment]
For the first example, it appears the ReadMe specification does not follow the CDS standard.  In particular this bit:
```
--------------------------------------------------------------------------------
   Bytes Format Units   Label      Explanations
--------------------------------------------------------------------------------
   1-  6  A6    ---     SN         Supernova identifier
   8- 12  F5.3  mag     Dm15(tem)1 [0.734/2.256]? {Delta}m_15_(B) value
                                    determined from the template fits (G1)
```
The `?` needs to be `?=---` to specify that `---` is used as the NULLVAL.  See http://vizier.u-strasbg.fr/doc/catstd-3.4.htx#NULL

Astropy allows a slightly looser version of this where it can be `?=-` and that will allow `-`, `--`, `---`, or `----`.  But still the file needs to say that dashes are used to indicate missing values.

If I modify the `ReadMe` file to meet the specification then table2 reads in as expected:
```
Byte-by-byte Description of file: table2.dat
--------------------------------------------------------------------------------
   Bytes Format Units   Label      Explanations
--------------------------------------------------------------------------------
   1-  6  A6    ---     SN         Supernova identifier
   8- 12  F5.3  mag     Dm15(tem)1 ?=- {Delta}m_15_(B) value
                                    determined from the template fits (G1)
  14- 18  F5.3  mag   e_Dm15(tem)1 ? 1{sigma} uncertainty in 
                                   Dm15(tem)1
  20- 28  A9    ---     Subtype1   Spectral subtype (1)
  30- 33  A4    ---     Subtype2   ?=- Wang et al. (2009, J/ApJ/699/L139) spectral
                                    classification (2)
  35- 36  A2    ---     Subtype3   ?=- Branch et al. (2006PASP..118..560B) spectral
                                    classification (3)
  38- 39  I2    ---     Nopt       [2/59] Number of nights with optical
                                    photometry
  41- 42  I2    ---     NIR        [0/33] Number of night(s) with near-IR
                                    photometry
  44- 48  F5.1  d       Tspec      ?=- Epoch of the spectrum (4)
--------------------------------------------------------------------------------
```
I'm not sure offhand the leading `[0.734/2.256]` is supposed to be allowed.

**Comment by djperrefort** [comment]
That fixed it. Thanks so much!
