### ISSUE TITLE
Deprecate constants context manager

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8866]
As stated in the diff of #8517:

```
The context manager may be used at any time in a Python session, but it
uses the prior version only for `astropy.constants`, and not for any
other subpackage such as `astropy.units`.
```

due to this warning (removed in the aforementioned PR):

```
Units such as ``u.M_sun`` will use the current version of the
corresponding constant. When using prior versions of the constants,
quantities should be constructed with constants instead of units.
```

With `ScienceState` enabled for `constants` and `units`, perhaps the `constants` context manager is more confusing than helpful now? Should we deprecate it and ask users to use `ScienceState` exclusively? Or is there still a need for context manager?

cc @stargaser and @mhvk

**Comment by mhvk** [comment]
I agree that we might as well deprecate it. One can always import a specific constant from the old module, and, as you say, it is just likely to lead to confusion.

**Comment by pllim** [comment]
And since we are not supposed to deprecate stuff in LTS (if I remember @bsipocz correctly), this will have to wait till 4.1?

**Comment by mhvk** [comment]
My addendum to APE 2 - https://github.com/astropy/astropy-APEs/pull/20 - was exactly the reverse: that LTS is the right time to add deprecation warnings, since most people will not be supporting two LTS at the same time.

**Comment by bsipocz** [comment]
> And since we are not supposed to deprecate stuff in LTS (if I remember @bsipocz correctly), this will have to wait till 4.1?

imo LTS is not the best place to add a new experimental API as then we need to  stuck with it for quite a while. but LTS is the best place to clean up APIs, deprecate and remove stuff, and to clear up previous deprecations.

**Comment by stargaser** [comment]
I agree that this context manager likely just causes confusion. I'm in favor of deprecation.

**Comment by pllim** [comment]
I am having second thoughts. As discovered in https://github.com/astropy/astropy/issues/8920#issuecomment-505593304 , I can only set the `ScienceState` once per session. This means that `ScienceState` cannot completely replace the context manager functionality. Am I missing something here?

**Comment by mhvk** [comment]
I think the problem that units do not get changed along with the constants means the old manager is just too risky. It was better than having nothing, but not better than the new one, even if it means you have to run separate python sessions. To me, it just seems it no longer serves a sensible purpose: if people really want to use the old constants, nothing stops them from doing `import constants.astropy20 as const`.

**Comment by pllim** [comment]
@mhvk , the case brought up in #8920 is that people tried to import `astropyconst20` but `M_sun` is still wrong (i.e., it uses CODATA 2018 anyway). But since the context manager also does not solve that problem, I guess we can proceed with this deprecation.

**Comment by mhvk** [comment]
Yes, that's right...

**Comment by mhvk** [comment]
Changed the title to reflect our conclusion: that we should deprecate the context manager.

**Comment by pllim** [comment]
I'll take a stab at this when I get the chance. But if someone else get to this first, please comment here so we don't duplicate effort.
