### ISSUE TITLE
Idea: use automatic list of dependencies for pytest display plugin

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8867]
Currently, the pytest display plugin we have shows a fixed set of packages in the pytest header, and allows other packages using the astropy test runner to configure this. I would like to suggest an alternative which would remove the need for packages to customize this, which is to show the list of all direct dependencies by default. With the following code:

```python
from pkg_resources import working_set


def list_dependency_versions(name):

    pkg = working_set.by_key['astropy']

    requirements = pkg.requires(pkg.extras)

    for req in sorted(requirements, key=lambda x: x.name.lower()):
        if req.name in working_set.by_key:
            req_pkg = working_set.by_key[req.name]
            print(f" {req.name}: {req_pkg.version}")
        else:
            print(f" {req.name}: Not installed")


list_dependency_versions('astropy')
```

I can get:

```
 asdf: Not installed
 beautifulsoup4: 4.7.1
 bintrees: Not installed
 bleach: 3.1.0
 bottleneck: 1.2.1
 coverage: Not installed
 h5py: 2.9.0
 html5lib: Not installed
 ipython: 7.5.0
 ipython: 7.5.0
 jplephem: Not installed
 matplotlib: 3.1.0
 mpmath: 1.1.0
 numpy: 1.16.4
 objgraph: Not installed
 pandas: 0.24.2
 pytest: 4.6.2
 pytest-astropy: 0.5.0
 pytest-mpl: Not installed
 pytest-xdist: Not installed
 pytz: 2019.1
 PyYAML: Not installed
 scikit-image: Not installed
 scipy: 1.3.0
 skyfield: Not installed
 sortedcontainers: Not installed
 sphinx-astropy: Not installed
```

We could still keep the option to override this in other packages if we want, but at least this should make it so that in practice it should never be needed - and we could actually remove it from the package template and just document how to do it in the package-template docs since it should be rare. If people are on board with the idea, I could update the pytest display plugin to do something like this.

(related thought: is there a reason the display plugin is still in astropy rather than a plugin package?)

**Comment by astrofrog** [comment]
Actually one thing that would be helpful is if someone who uses conda could check whether the above code works for them?

**Comment by pllim** [comment]
Ooooo I like this idea! I was find the manual configuration of what dependency version to display a little clunky.

**Comment by hamogu** [comment]
:+1:

**Comment by bsipocz** [comment]
> (related thought: is there a reason the display plugin is still in astropy rather than a plugin package?)

As I remember the only reason was that it seemed to be a small thing that Dan wasn't sure would be generally helpful at the point when he did the big factoring out. However I use the display in non astropy templated packages, it's the best thing since slice bread, but then we never got to the point of removing it.

**Comment by bsipocz** [comment]
on-topic: I would be on board with this if we also keep the manual way working (this can be a bit way too verbose, at the end of the day one can always go back to the install steps to double check the version of obscure dependencies). 
E.g. I think none of the pytest plugins need to be displayed (they are listed at the bottom of the header anyway), neither coverage, etc.

**Comment by pllim** [comment]
I think a separate plugin is overkill because `pytest` has clear example on how to customize header in `conftest.py` at https://docs.pytest.org/en/latest/example/simple.html#adding-info-to-test-report-header

Example in template might be sufficient?

**Comment by pllim** [comment]
> someone who uses conda could check whether the above code works for them

@astrofrog , check how exactly? Do you want an actual `pytest` run with that patch? Or simply copy and paste that code in a Python session?

**Comment by astrofrog** [comment]
Just copy/paste into python session :)

**Comment by pllim** [comment]
With this:
```
$ conda --version
conda 4.6.14
$ python --version
Python 3.7.1
```

I get this:
```
 asdf: 2.3.2
 beautifulsoup4: 4.7.1
 bintrees: Not installed
 bleach: 3.1.0
 bottleneck: 1.2.1
 coverage: 4.5.2
 h5py: 2.8.0
 html5lib: 1.0.1
 ipython: 6.5.0
 ipython: 6.5.0
 jplephem: Not installed
 matplotlib: 3.0.0
 mpmath: Not installed
 numpy: 1.16.3
 objgraph: Not installed
 pandas: 0.24.2
 pytest: 4.0.2
 pytest-astropy: 0.5.0
 pytest-mpl: Not installed
 pytest-xdist: Not installed
 pytz: 2018.5
 PyYAML: Not installed
 scikit-image: 0.14.1
 scipy: 1.1.0
 skyfield: Not installed
 sortedcontainers: 2.1.0
 sphinx-astropy: 1.1.1
```

Nitpick: The leading whitespace nags at me.

**Comment by pllim** [comment]
Why is `ipython` repeated twice?

**Comment by astrofrog** [comment]
@pllim:

> I think a separate plugin is overkill because pytest has clear example on how to customize header in conftest.py at https://docs.pytest.org/en/latest/example/simple.html#adding-info-to-test-report-header

On the flip side, having a separate plugin makes it much easier for all the astropy packages to be able to opt in to using this plugin without requiring customization of the ``conftest.py`` file. I personally would use this plugin for many other packages, including glue.

Not sure why ipython is repeated twice, but easy to fix.

@bsipocz:

Regarding not including the test dependencies, this is actually trickier than it sounds because we  would have to explicitly hard-code them to not be shown.

**Comment by astrofrog** [comment]
By the way, the display could be made more compact when there are more than a certain number of dependencies:

```
asdf: 2.3.2                   objgraph: Not installed
beautifulsoup4: 4.7.1         pandas: 0.24.2
bintrees: Not installed       pytest: 4.0.2
bleach: 3.1.0                 pytest-astropy: 0.5.0
bottleneck: 1.2.1             pytest-mpl: Not installed
coverage: 4.5.2               pytest-xdist: Not installed
h5py: 2.8.0                   pytz: 2018.5
html5lib: 1.0.1               PyYAML: Not installed
ipython: 6.5.0                scikit-image: 0.14.1
ipython: 6.5.0                scipy: 1.1.0
jplephem: Not installed       skyfield: Not installed
matplotlib: 3.0.0             sortedcontainers: 2.1.0
mpmath: Not installed         sphinx-astropy: 1.1.1
numpy: 1.16.3                 
```

**Comment by pllim** [comment]
:-1: on multi-column. I like my `grep` result to be clean. :stuck_out_tongue_closed_eyes:

**Comment by bsipocz** [comment]
I'm also 👎 on multi columns as well as having all the testing infrastructure, but maybe a grep should solve that. My worry is that if astropy have this many, what will happen with other packages that actually have dependencies? The whole point of a readable compact header would loose the point (changes in e.g. bottleneck is never really an issue when  trouble shooting,  so it all just adds noise). 

Also, what happens with transitive dependencies? Packages can say that they require astropy and then not list numpy. Yet numpy needs to be in this list.

**Comment by bsipocz** [comment]
(I'm still on board of separating it out into a new plugin, and happy to help with it if you need any)

**Comment by pllim** [comment]
Re: plugin -- I found https://github.com/pytest-dev/pytest-metadata but I don't think that is quite the same.

**Comment by astrofrog** [comment]
> My worry is that if astropy have this many, what will happen with other packages that actually have dependencies?

But astropy does have a lot of dependencies - just to be clear, I'm only listing dependencies that are inside setup.py/setup.cfg - I'm not going all the way down the dependency tree. Astropy does actually have quite a lot of optional dependencies compared to the average package.

> Also, what happens with transitive dependencies? Packages can say that they require astropy and then not list numpy. Yet numpy needs to be in this list.

Yes that is a good point, and I feel like Numpy is a special case that could be listed by default (along with e.g scipy and matplotlib). I don't think I've ever seen a package that imports astropy but does not import numpy though? (meaning it should declare numpy as a dependency).

**Comment by bsipocz** [comment]
Well, but then many packages are not declaring their optional dependencies at all, and I saw tons of ci/setup.py setups where dependencies were silently assumed (as they are already a declared dependency of declared dependencies).

**Comment by hamogu** [comment]
We might have to run the tests first (at least as far as possible) and then get the list of all modules that are imported at that point from `sys.modules.keys()`. That does not catch modules that are not imported, but it does get modules that are dependencies of dependencies. (And don't try that in ipython or the list is endless even before astropy is imported). For discussion see: https://stackoverflow.com/questions/4858100/how-to-list-imported-modules

**Comment by bsipocz** [comment]
@hamogu - I think  it's still valuable to list `Not installed` for optional dependencies that are not installed. And for the full comprehensive list one could always set `DEBUG=True` in travis and get the full list from conda, etc.

**Comment by hamogu** [comment]
@bsipocz The more I think about it, the more I like a hand-curated list like we have now...

**Comment by pllim** [comment]
> many packages are not declaring their optional dependencies at all

I'm guilty of this sometimes. I rely on `astropy` to pull in `numpy` for me. 😅

**Comment by astrofrog** [comment]
> I'm guilty of this sometimes. I rely on astropy to pull in numpy for me. sweat_smile

For me that's an argument for the automated list - as then people might fix this kind of outrageous behavior!

**Comment by bsipocz** [comment]
> For me that's an argument for the automated list - as then people might fix this kind of outrageous behavior!

they won't, many hardly edit the template defaults (thus my recent change in the template of having the header opt-out rather than opt-in)

**Comment by astrofrog** [comment]
I think I’m on the losing side, so feel free to close :) (splitting out the display plugin is a separate issue I think)

**Comment by bsipocz** [comment]
There must be a middle ground somewhere that doesn't involve much more hacking that the proposal above?

**Comment by astrofrog** [comment]
I think the best course of action would be to close this and focus first on splitting out the plugin into a separate package, and make it easier to configure without requiring ``conftest.py``, then once that's done we could consider whether it makes sense to generalize in the way that I was suggesting here or something similar (but we don't have to).
