### ISSUE TITLE
set_coord_type in WCSAxes should take Quantity for the wrap angle

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8868]
Currently ``CoordinateHelper.set_coord_type`` in WCSAxes takes the wrap angle as a float, but it would be better to take it as a ``Quantity``. We'll likely need to deprecate float inputs (rather than just removing).

**Comment by dubeyaayush07** [comment]
I would like to work on this issue, as this is my first time contributing here I would really appreciate if someone could point me in the right direction

**Comment by tabshaikh** [comment]
@astrofrog so would we like to do something like issue a warning when the datatype of coord_wrap is not `Quantity` to depreciate this
```if type(coord_wrap)!=Quantity:
        warnings.warn("set_coord_type() function takes input coord_wrap of type Quantity")
```
