### ISSUE TITLE
Question: Update contact info

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#8873]
This most likely is no longer valid:

https://github.com/astropy/astropy/blob/b750a0e6ee76fb6b8a099a4d16ec51977be46bf6/astropy/wcs/setup_package.py#L4

What should it be?

**Comment by bsipocz** [comment]
I would think we should remove it  altogether and direct all contacts to github issues/central astropy e-mail/etc.

**Comment by pllim** [comment]
@nden ?

**Comment by bsipocz** [comment]
But then `wcs` is the only subpackage with a `CONTACT` and `EMAIL` field. 🤷‍♀

**Comment by nden** [comment]
Now that this is under `astropy` do we need an email contact in this module?

**Comment by nden** [comment]
I mean 👍 for removing them.

**Comment by mcara** [comment]
OK
