### ISSUE TITLE
Make astropy.utils.release usable by affiliated packages

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#888]
At the moment, `astropy.utils.release` contains several instances of:

```
    if data['name'] != 'astropy':
        return
```

which makes it usable only by the Astropy core package. Removing these checks and adding

```
# Set up release hooks for package
entry_points = {}
for hook in [('prereleaser', 'middle'), ('releaser', 'middle'),
             ('postreleaser', 'before'), ('postreleaser', 'middle')]:
    hook_ep = 'zest.releaser.' + '.'.join(hook)
    hook_name = 'packagename.release.' + '.'.join(hook)
    hook_func = 'astropy.utils.release:' + '_'.join(hook)
    entry_points[hook_ep] = ['%s = %s' % (hook_name, hook_func)]
```

(and adding `entry_points` to the call to `setup()`) seems to work, so I was wondering if there is a way to write `astropy.utils.release` that doesn't require checking the package name? Is the risk that if we get rid of the check, _any_ package's release will call Astropy?

**Comment by bsipocz** [comment]
@astrofrog @eteq - Hmm, what is this ``astropy.utils.release`` anyway? It seems to be deprecated for a while, so what about removing it for 2.0, and closing this issue, too?
