### ISSUE TITLE
MNT: Move utils.timer to astroquery

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8898]
@saimn and @astrofrog has brought up that https://github.com/astropy/astropy/blob/master/astropy/utils/timer.py is only used by `astroquery.vo_conesearch` (used to be `astropy.vo.conesearch`) and nothing else in the core, and thus should be moved to `astroquery`.

1. Do the move and deprecate the one in `astropy`.
2. Remove it from `astropy` after a deprecation period.

~Is Step 1 a good thing for 4.0?~

**Progress**

- [x] Move code to `astroquery` -- astropy/astroquery#1508 -- get it merged
- [x] Deprecate the functions here. Remove the user-facing doc. -- #9038 
- [ ] Open follow-up issue to completely remove the functions after a deprecation period. Also add a note to remove the static PNG from doc.

**Comment by bsipocz** [comment]
We also need to make sure there is no wider usage out in the wild, after all the functionality is in the public API.

If we move and deprecate then yes, 4.0 is a good time to do it.

**Comment by pllim** [comment]
FWIW, a quick search on GitHub does not show that `timer` is used outside of `conesearch`.
