### ISSUE TITLE
Local development/testing issue: precessedgeocentric-1.0.0.yaml': No such file or directory 

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#8903]
After some runs either installing or testing I'll hit an exception like this:

```
running pre_hook from astropy._erfa.setup_package for build_py command
copying astropy\..\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\astropy\io\misc\asdf\data\schemas\astropy.org\astropy\coordinates\frames\precessedgeocentric-1.0.0.yaml -> build\lib.win-amd64-3.7\astropy\..\build\lib.w
in-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\astropy\io\misc\asdf\data\schemas\astropy.org\astropy\coordinates\frames
error: could not create 'build\lib.win-amd64-3.7\astropy\..\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\astropy\io\misc\asdf\data\schemas\astropy.org\astropy\coordinates\frames\precessedgeocentric-1.0.0.yaml': No suc
h file or directory
```

I'm mostly using `python setup.py develop` or `test` or `install`. But after a few of those (not exactly sure how many) I'll hit this exception and cannot proceed. I then clean and rebuild, which is inconvenient and time-consuming. 

It could be some windows or conda thingy or I'm just using the wrong commands?

**Comment by pllim** [comment]
@MSeifert04 , I see similar error too on Windows in similar situations. I wonder if this is worth reporting upstream to the `setuptools` people. 🤔

**Comment by MSeifert04** [comment]
Ah, that feels so great that I'm not alone. 😄 

> I wonder if this is worth reporting upstream to the setuptools people.

Ah, I thought it may be a problem with our code or customizations. If it isn't then we should report it there. Is that a file that should be copied by manifest or package-includes? I'm a bit outdated with the current state of the repo 😓

**Comment by pllim** [comment]
I dunno, maybe @eteq or @adrn know what this `coordinates\frames\precessedgeocentric-1.0.0.yaml` is used for.

**Comment by bsipocz** [comment]
hmm, that's an `asdf` thingy, living here?:
`./astropy/io/misc/asdf/data/schemas/astropy.org/astropy/coordinates/frames/precessedgeocentric-1.0.0.yaml`

**Comment by MSeifert04** [comment]
Hm, interestingly the directory structure is very odd: `astropy\astropy\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7` that probably shouldn't go that deep. Maybe it's missing an anchor directory?!

**Comment by bsipocz** [comment]
🤷‍♀ something odd is definitely going on with the schemas. I also would like to see this being picked up by appveyor, failing for the both of you but not on CI hints that our test coverage is not ideal.

**Comment by pllim** [comment]
@jdavies-st , any idea?

**Comment by MSeifert04** [comment]
Just to provide another data point: I also found out when it "breaks". It happens when the path becomes too long `astropy\astropy\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7\build\lib.win-amd64-3.7`. This is a common issue with Windows, however it shouldn't start to build this deeply nested structure at all.

**Comment by MSeifert04** [comment]
> I also would like to see this being picked up by appveyo

Given my current understanding we would need to run a lot of install/develops/tests after one another to create that deep folder structure. I think that's probably annoying and hard to test with CI.

**Comment by jdavies-st** [comment]
Between builds you can do a `git clean -xdf`.  That said, it looks like the windows builds are nesting the builds.  That's bad.

**Comment by pllim** [comment]
Do you think it is a side effect of hard-coding slashes in here?

https://github.com/astropy/astropy/blob/bc404ff5842f405d3658911757615cbd4fc590bd/astropy/setup_package.py#L9-L16

It was implemented by @astrofrog in #8413 .

**Comment by astrofrog** [comment]
I have a Windows machine which I'll have access to tomorrow, I can see if I can reproduce this issue.

**Comment by astrofrog** [comment]
@pllim - the issue wasn't the / but the lack of root prefix for the path (so it was matching that pattern in the whole repo). See https://github.com/astropy/astropy/pull/9039 for a fix.

**Comment by jdavies-st** [comment]
Yeah, this happens on MacOS platform too. I just built it a few times and end up with nested builds.
```
$ pwd
~/dev/astropy
$ ls ./build/lib.macosx-10.7-x86_64-3.7/build/lib.macosx-10.7-x86_64-3.7/build/lib.macosx-10.7-x86_64-3.7/
astropy/

```
Good catch.
