### ISSUE TITLE
TST: Mirror pandas intersphinx

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8915]
`html-doc` job on CircleCI is failing like this: https://circleci.com/gh/astropy/astropy/35218

```
failed to reach any of the inventories with the following issues:
intersphinx inventory 'http://pandas.pydata.org/pandas-docs/stable/objects.inv' not fetchable
    due to <class 'requests.exceptions.ConnectionError'>:
    HTTPConnectionPool(host='pandas.pydata.org', port=80):
    Max retries exceeded with url:
    /pandas-docs/stable/objects.inv (Caused by NewConnectionError...
    ... [Errno 110] Connection timed out')
Sphinx Documentation subprocess failed with return code 2
Exited with code 2
```

@Cadair thinks it is related to https://news.ycombinator.com/item?id=20262214 . @bsipocz suggested that we can mirror it as a workaround.

**Comment by bsipocz** [comment]
Hmm, now I'm having second thoughts about this. Looking at the "mirror" we have, it's apparent that the versions are horribly outdated (https://github.com/astropy/astropy-data/tree/gh-pages/intersphinx). Also the whole issue has been quickly resolved. Shall or shan't I go ahead  and add pandas there, too?

**Comment by pllim** [comment]
> Shall or shan't I 

If it is not broken anymore, there is no point. I'll just close this issue. Thanks for checking!

p.s. The outdated mirrors is a separate problem though and maybe we should discuss that over at `astropy-data`?
