### ISSUE TITLE
.set_axis_off() doesn't work with WCSAxes

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#8919]
`ax.set_axis_off()` should turn off all the axis annotations, but it doesn't do anything on a `WCSAxes`:

```python
import matplotlib.pyplot as plt

from astropy.wcs import WCS
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename

filename = get_pkg_data_filename('galactic_center/gc_msx_e.fits')

hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)

fig = plt.figure()
ax1 = plt.subplot(2, 1, 1, projection=wcs)
ax2 = plt.subplot(2, 1, 2)
for ax in [ax1, ax2]:
    ax.set_axis_off()
    ax.plot([0, 1], [0, 1])

plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/6197628/60092396-da6f3b00-973e-11e9-9fa5-327924209395.png)

**Comment by astrofrog** [comment]
@dstansby - it should be easy to overload this and do the right thing behind the scenes and hide the frame and coordinates. Do you want to try and fix this in a pull request? 😄

**Comment by dstansby** [comment]
Are there good reasons why the labels are all just manually added `Text` objects, instead of being actual tick labels (which I think would play nicely with a lot of the default `Axes` methods when it comes to working with ticks/labels)?

**Comment by astrofrog** [comment]
@dstansby - I found that using the default tick/labeling framework in Matplotlib was not flexible enough to allow arbitrary spines and e.g. arbitrarily rotated tick labels. In addition, we need a stronger decoupling of the concept of an x/y axis from the world coordinates in WCSAxes. However, if you can find a way to re-use some of the default Matplotlib infrastructure to do this, that would be great!
