### ISSUE TITLE
astropyconst20 and the CODATA version

### ISSUE THREAD

**Issue by nabobalis** [astropy/astropy#8920]
With the changes with the default CODATA values, we seem to have a minor doctest failure. I am unsure if its my lack of understanding of how units and constants versions work underneath.

So within our `constants.py` we import the astropy constants like so:
```python
import astropy.constants.astropyconst20 as astrocon
```
and we set our mass value (among others) like so.
```python
physical_constants['mass'] = astrocon.M_sun
```

When we check the mass value it reports that it uses the CODATA 2018 whereas I thought that `astropyconst20` would be CODATA 2014. 

```python
>>> from sunpy.sun import constants
>>> constants.get('mass')
<<class 'astropy.constants.iau2015.IAU2015'> name='Solar mass' value=1.988409870698051e+30 uncertainty=4.468805426856864e+25 unit='kg' reference='IAU 2015 Resolution B 3 + CODATA 2018'>
```

I am unsure if it a bug or something we screwed up inside SunPy.

**Comment by pllim** [comment]
Did you try the `ScienceState` that @stargaser implemented in #8517 ?

```python
>>> from astropy import physical_constants
>>> physical_constants.set('codata2014')
<ScienceState physical_constants: 'codata2014'>
>>> from astropy import constants as const
>>> const.M_sun
<<class 'astropy.constants.iau2015.IAU2015'> name='Solar mass' value=1.9884754153381438e+30 uncertainty=9.236140093538353e+25 unit='kg' reference='IAU 2015 Resolution B 3 + CODATA 2014'>
```

**Comment by nabobalis** [comment]
Yes that did work. However it triggered the import error if astropy.units is already imported with parts of our test suite (which is an issue SunPy needs to fix separately). 

But I guess my question is, should using `astropyconst20` load up `codata2014` or `codata2018`? Or is that something i need to set using by doing `physical_constants.set('codata2014')`?

**Comment by bsipocz** [comment]
> However it triggered the import error if astropy.units is already imported with parts of our test suite (which is an issue SunPy needs to fix separately)

We also need to fix that for the astropy test suite 😅  xref: #8781

**Comment by nabobalis** [comment]
> > However it triggered the import error if astropy.units is already imported with parts of our test suite (which is an issue SunPy needs to fix separately)
> 
> We also need to fix that for the astropy test suite 
> 
> If you have a better suggestion than the on in #8781, please do let me know.

Yeah, for the doctests, I can't see a better way. 

The issue for us with that import check is that we will have code that goes
```python
import astropy.units as u

import sunpy.sun.constants as con
```
which will trigger that import error (if we set the version inside sunpy).

**Comment by pllim** [comment]
Halfway down the doc at https://astropy.readthedocs.io/en/latest/constants/index.html , it says the following:

*The astronomical and physical constants are combined into modules with names like astropyconst13, astropyconst20, and astropyconst40 for different versions. However, importing these prior version modules directly will lead to inconsistencies with other subpackages that have already imported astropy.constants.*

So, I think what you encountered is a known issue.

**Comment by nabobalis** [comment]
Ah ok, so for the time being I should replace any  imports of `astropy.constants` to fix it?

**Comment by nabobalis** [comment]
Thanks @pllim.

**Comment by pllim** [comment]
I am not sure myself. In an interactive session, I am unable to switch the `ScienceState` again after I set it the first time. Is this by design, @stargaser ?

**Comment by stargaser** [comment]
Because of the circular way that `astropy.constants` and `astropy.units` depend on one another, we were only able to implement the version-setting to work on the very first import.

I'm concerned about the behavior of `M_sun` when imported from the `astropyconst20` module, because the calculation is using `G` from CODATA2018. Reopening this issue to think about it...also cc @mhvk

**Comment by pllim** [comment]
If `astropyconst20` is not working as expected, should we get rid of it altogether? It is an option to deprecate this along with the context manager (xref #8866).

**Comment by mhvk** [comment]
I think what is happening is that when one loads values from `iau2015`, the ones that involve `codata.G` get calculated on the spot. This works beautifully when one uses the `astropyconst20` science state, since `codata` is set correctly to `codata2014`, but not if `constants` has already been loaded, since then the most recent `codata.G` is used.

This does not seem easy to change in an automatic fashion. But it would be trivial to just copy the relevant definitions of `M_sun`, `M_jup` and `M_earth` to `astropyconst20` itself. This is not super-elegant, but I think it is OK, since all the packages involved are fixed.

**Comment by stargaser** [comment]
Defining `M_sun`, etc directly in `astropyconst20.py` would be an acceptable solution.

**Comment by pllim** [comment]
See #9027 for a proposed fix.
