### ISSUE TITLE
add example in units docs to include parallax angle to parsec 

### ISSUE THREAD

**Issue by kelle** [astropy/astropy#8921]
Add another example in the [units docs for equivalencies](https://docs.astropy.org/en/stable/units/equivalencies.html) showing how to go from a parallax in mas to a distance in pc. My student @elena-mitra and I figured it out, with the assistance of @eblur , but I think an explicit example would be very helpful.

**Comment by eblur** [comment]
@kelle Can you review the updates I made in PR #8991

**Comment by mhvk** [comment]
fixed by #8991
