### ISSUE TITLE
unit support in modeling.polynomial.SIP 

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#8923]
I was working through the simple gWCS example in https://gwcs.readthedocs.io/en/latest/#getting-started and wanted to add SIP polynomials to the transformation. Unfortunately, while other models used in gWCS seem to support units, `SIP` appears to not support units.

**Comment by mcara** [comment]
CC: @nden @perrygreenfield

**Comment by eslavich** [comment]
@mcara  I opened #9936 with a proposal for addressing this.  I'd like to get notes on it before adding tests, can you take a look and let me know what you think?
