### ISSUE TITLE
Building docs hangs during Reading source [..] and keeps chewing CPU

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8928]
(This is slightly a repeat of https://github.com/astropy/sphinx-astropy/issues/21 where I had this problem).

I just did the experiment of following the instructions at:
https://astropy.readthedocs.io/en/latest/install.html#building-documentation

I made a clean conda python=3.7 environment and a fresh astropy clone and did:
```
conda install -c astropy sphinx-astropy
# then conda installed cython, pytest, pyyaml, scikit-image, and scipy
python setup.py build_docs
```
This churns away until getting to near the end of Reading sources, showing 99%.  Then it just hangs forever doing something at 100% CPU until I kill it.  I waited up to 1.5 hours once.

I saw some traffic like this earlier.  I never had this problem before...

**Comment by taldcroft** [comment]
And in fact in my "dirty" astropy dev environment with a hodge-podge of packages from different eras installed, the docs build just fine.  Hrrm..

BTW, this is on Mac high-sierra.

**Comment by bsipocz** [comment]
Part of this is a documentation issue, `pip install -e .[docs]` is missing from the instructions to get the doc dependencies  installed.

The other part is I believe related to a mpl bug, could you try to install `matplotlib<3.1`? I'll try to dig up the xref for it.

**Comment by bsipocz** [comment]
https://github.com/astropy/astropy/issues/7080 has some comments on it, and in fact we limited  mpl  version in the CI runs to have a passing build.

**Comment by taldcroft** [comment]
OK, downgrading to mpl 3.0.2 fixed this, closing, thanks!
