### ISSUE TITLE
How to tell FITS to not delay the header?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8931]
Follow up of #8502 -- What if I don't want the delayed header loading. How do I turn it off? Is turning it off possible?

**Comment by saimn** [comment]
Currently turning it off is not possible. The idea was that it should not be needed. And I'm not sure if the use case of `stsci.tools` is sufficient to justify this code, I think that you could achieve the same result differently (the main problem is to keep the compatibility with the previous astropy versions).

**Comment by pllim** [comment]
> sufficient to justify this code

I agree it is not. But... *historical reasons*. Anyway, I was just exploring options. Thanks!
