### ISSUE TITLE
TST: CircleCI 32-bit job is broken

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8934]
Example log from `master`: https://circleci.com/gh/astropy/astropy/35792

There are 96 failures. One of them:

```
astropy/coordinates/tests/test_frames.py:522: AssertionError
______________________________ test_dynamic_attrs ______________________________
[gw3] linux -- Python 3.5.7 /opt/python/cp35-cp35m/bin/python

    def test_dynamic_attrs():
        from astropy.coordinates.builtin_frames import ICRS
        c = ICRS(1*u.deg, 2*u.deg)
        assert 'ra' in dir(c)
        assert 'dec' in dir(c)
    
        with pytest.raises(AttributeError) as err:
            c.blahblah
>       assert "object has no attribute 'blahblah'" in str(err)
E       assert "object has no attribute 'blahblah'" in '<ExceptionInfo AttributeError tblen=2>'
E        +  where '<ExceptionInfo AttributeError tblen=2>' = str(<ExceptionInfo AttributeError tblen=2>)
```

**Comment by pllim** [comment]
Could be related to `pytest` 5.0 release if they changed the `str(e)` behavior when you catch the exception in `pytest.raises()`. To test that theory, you can roll back to `pytest` 4.x series in 32-bit container and see if the tests pass again. 🤷‍♀

**Comment by dhomeier** [comment]
This seems to be the relevant [change](https://github.com/pytest-dev/pytest/issues/5412). Looks like the solution would be to substitute with `str(e.value)`.
I've tested this on a local pytest 5.0.0 installation, which raised the same errors for `test_angles.py`, and it did work (and also works back with pytest 3.10.1).

A quick grep shows that 63 of our tests already have that syntax, which only leaves 90-119 to fix (not sure about the 20-something that do not appear to throw errors). 💯

**Comment by bsipocz** [comment]
Thank you @dhomeier. Since you've already made the changes, would you mind opening a PR?
