### ISSUE TITLE
TST: Tests failed with Numpy DeprecationWarning about np.broadcast_arrays

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8935]
Example log from `master` from the `numpy-dev` job: https://api.travis-ci.org/v3/job/552167685/log.txt

```
DeprecationWarning: Numpy has detected that you (may be) writing to an array with
overlapping memory from np.broadcast_arrays. If this is intentional
set the WRITEABLE flag True or make a copy immediately before writing.
```

215 failures total

xref numpy/numpy#12609

**Comment by mhvk** [comment]
@pllim - this warning was meant to show only when we are *actually* trying to write to a broadcast array - which we should *never* do. So, I think we should only look at the actual cases where the warning is given. 

From the log file, it looks like there is only a single problem somewhere in the `LombScargle` implementation, which we probably can fix by looking carefully at that code.

**Comment by pllim** [comment]
There are also some from BLS too. Unfortunately, I won't have time to investigate further for now. Someone familiar with the `timeseries` stuff feel free to take a stab. 🙏

**Comment by bsipocz** [comment]
I'll try to find some time looking into those this weekend.

**Comment by mhvk** [comment]
Looking into this more, I've concluded it is really an upstream issue: https://github.com/numpy/numpy/issues/13929

**Comment by mhvk** [comment]
See #8965 for an alternative solution that explicitly marks arrays as `read-only`

**Comment by pllim** [comment]
Fixed, thanks to @mhvk !
