### ISSUE TITLE
Proposal for helping keep __array_function__ overrides in sync

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#8937]
With the introduction of `__array_function__`, we've had to override a number of numpy implementations so that the functions would work correctly with `Quantity`. In #8900, @astrofrog commented "I have a slight concern that given the amount of code we are copying from Numpy, it's not clear how we'll be able to easily keep track of fixes to bugs in the copied Numpy code."

Fixes and bugs are very difficult, but another issue, addition of functionality via new arguments, is something we could perhaps address. In particular, we could ensure that our overrides in `units/quantity_helpers/function_helpers.py` do not to use `*args, **kwargs` at all, but rather spell out the signature. With that, one could write an inspection tool that checks whether signatures still match, and that is run as part of the tests (in particular against `numpy-dev`).

**Comment by mhvk** [comment]
Done by #15710

**Comment by neutrinoceros** [comment]
thanks for connecting the dots !
