### ISSUE TITLE
display units without simplifying fractions?

### ISSUE THREAD

**Issue by brandondube** [astropy/astropy#8940]
I work with a lot of power spectral density data that has units of nm^2 / (cy/mm)^2.  This can be reduced/converted to nm^2 mm^2, or several other equivalent representations.  The cy/mm notation is what falls directly out of the math, so I would like to write it this way.  Is there a way to prevent the `to_string` formatters from simplifying the unit?  Or is it already simplified at this point?

Also, is it possible to display `cy` instead of `cycle`?

**Comment by mhvk** [comment]
@brandondube - I think that would be tricky. Any time one makes a composite unit, the parts are taken apart, so while the code keeps `nm` and `mm` separately, it does not know any more that `cy` and `mm` belong together:
```
In [27]: from astropy import units as u
In [28]: unit = u.nm**2 / (u.cy/ u.mm)**2

In [29]: unit
Out[29]: Unit("mm2 nm2 / cycle2")

In [30]: unit.bases
Out[30]: [Unit("mm"), Unit("nm"), Unit("cycle")]

In [31]: unit.powers
Out[31]: [2, 2, -2]
```

So, as you were guessing, by the time you do `to_string`, it is already too late (it would also be difficult given also, we try to ensure that any string can round-trip).

**Comment by mhvk** [comment]
Actually, there seems to be a work-around, if you define a new unit of `cy/mm`:
```
from astropy import units as u
cypmm = u.def_unit('(cy/mm)', u.cy / u.mm)
unit = u.nm**2 / cypmm**2
unit
# Unit("nm2 / (cy/mm)2")
print(unit.to_string('unicode'))
   nm²   
 ────────
 (cy/mm)²
```
I should add that I'm far from sure whether this `/` in the unit isn't going to break anything... (and, hey, I'm one of the maintainers of `units`...)

**Comment by brandondube** [comment]
Thanks for the comment!  Since there is a chance for subtle bugs, I think I'll just deal with the unit being re-expressed.
