### ISSUE TITLE
Make sidebar TOC sticky and visible through out the document

### ISSUE THREAD

**Issue by smoh** [astropy/astropy#8941]
Hi, I was looking at various documentations of astropy-related projects which uses astropy sphinx theme and have a suggestion. I thought it might have come up already but couldn't find any. It is related to #8922 but not exactly the same issue.

Is it possible to make the sidebar sticky and have its own scroll as in [here](https://docs.python.org/2/reference/expressions.html#primaries) in python 2.7 docs? Right now, when we scroll down, the sidebar scrolls down with the content quickly becomes invisible letting its navigation utility not so useful except at the beginning.

Oddly, python 3 docs sidebar also scrolls down with content and there is a relevant thread here: https://github.com/python/python-docs-theme/issues/20

I don't know enough css/javascript to gauge how easy/hard it is but it would be so nice.
(I thought this issue belongs here than astropy-sphinx repo but please feel free to move it if appropriate).

**Comment by bsipocz** [comment]
Thanks @smoh, indeed this would be a useful feature. As you said though it belongs to the theme repo, so suggest to move it.  ping @eteq or @astrofrog to actually do the move.

**Comment by pllim** [comment]
Which one is the theme repo? `github.com` or `automodapi`?

**Comment by bsipocz** [comment]
It's https://github.com/astropy/astropy-sphinx-theme. But it needs an admin (or someone having write access to both repos) to be moved over.

**Comment by pllim** [comment]
I just manually transferred it to astropy/astropy-sphinx-theme#11 since this is over a week old already. 😬
