### ISSUE TITLE
New wavelength unit or Quantity

### ISSUE THREAD

**Issue by brandondube** [astropy/astropy#8952]
Often, we would like to use units of "waves" in optics and astronomy, where a wave is a wavelength of light and just a reference length.  For example, the Cartesian units for the focal plane of a telescope are often expressed as lambda / D, and optical surfaces and wavefronts often use waves as the unit for optical path differences.

It would be nice to see `u.wave` as a new unit or Quantity.  I am not very familiar with the behind-the-scenes in the units module, but I think all that has to happen is store the reference length for the wavelength on the instance and define equivalencies or some other mechanism to convert to the base unit of that equivalence?

For example, something like `wvl = u.wave(ref_len = 632.8 * u.nm)` to define the wavelength of a HeNe laser.

Is this something of interest to the Astropy developers?  If so, what are the basics of the units module for me to get to work on a PR?

**Comment by mhvk** [comment]
@brandondube - thanks for the suggestion!  But could you give a bit more detail about what exactly you would want? Perhaps a snippet of a calculation with what you would hope would happen?

From your text above, I see two different uses, one where you have a unit of length that you only later fill in (by passing in a relevant `lambda`), the other where you have a new given unit of length. For the latter, are there things beyond just defining a new unit?
```
wvl = u.Unit('HeNe', 632.8 * u.nm)
```
(or use `u.def_unit`)

For the former, one can do things like what we already do for [`u.count` and `u.pixel`](https://github.com/astropy/astropy/blob/master/astropy/units/astrophys.py#L140), which are standalone unit that get real meaning only by, e.g., using an equivalency.

**Comment by brandondube** [comment]
Sure -- for the application/what I would want:

Interferometers measure optical path difference in units of waves and you might want to convert to a physical length, e.g.

```python
import numpy as np

from astropy import units as u

wvl = u.Unit('HeNe', 632.8 * u.nm)
phase = np.random.rand(100, 100) * wvl

phase_as_um = phase << u.um
```

I would also like the unit printout/repr/str to use `λ`.

Actually, it looks like `wvl = u.Unit('λ', 632.8 * u.nm)` does what I want already!

**Comment by mhvk** [comment]
OK, relative to an already known wavelength, it works well!  Good to know.

I'm intrigued also by the idea to calculate in units of wavelength that is only filled in later, i.e., in usage that is a bit more `pixel`, `photon`, or `count`. Right now, one can do something like:
```
wvl = u.def_unit(['wave', 'wavelength'], format={'unicode': 'λ', 'latex': r'\lambda'})
q = np.arange(1., 10.) * wvl
q
# <Quantity [1., 2., 3., 4., 5., 6., 7., 8., 9.] wave>
1/q
# <Quantity [1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
#            0.16666667, 0.14285714, 0.125     , 0.11111111] 1 / wave>
```
For conversion, one would then have to use equivalencies:
```
equivs = [(wvl, u.Unit(632.8 * u.nm)), (wvl**-1, u.Unit(632.8 * u.nm)**-1)]
q.to(u.cm, equivalencies=equivs)
# <Quantity [6.3280e-05, 1.2656e-04, 1.8984e-04, 2.5312e-04, 3.1640e-04,
#            3.7968e-04, 4.4296e-04, 5.0624e-04, 5.6952e-04] cm>
(1/q).to(1/u.cm, equivalencies=equivs)
# <Quantity [15802.78128951,  7901.39064475,  5267.59376317,  3950.69532238,
#             3160.5562579 ,  2633.79688158,  2257.54018422,  1975.34766119,
#             1755.86458772] 1 / cm>
```
An annoyance in the above is that one has to specify every possible unit combination in the equivalencies; it would be nice if there were some way to specify "just replace every instance of the given unit with another one" (something we have only for `dimensionless_angles`, which allows to add/remove `radian` to every power wanted).

**Comment by mhvk** [comment]
More concretely, is there a place in the documentation which, if only it had the right sentence or two, would have pointed you in the right direction for the simpler case, with a known unit?

**Comment by brandondube** [comment]
Sorry -- looks like this fell off my radar over the holiday.  The [top-level page of the docs](https://docs.astropy.org/en/stable/units/) is quite long.  There's only a single link in the [usage](https://docs.astropy.org/en/stable/units/#using-astropy-units) section to [combining and defining units](https://docs.astropy.org/en/stable/units/combining_and_defining.html) which doesn't cover an advanced usage of `def_unit` (with latex, unicode, etc, formatters).  I didn't see any examples for using the `u.Unit` syntax either.

I think the size of the top-level page, it would be beneficial to adjust the ToC so it split into basic / intermediate / advanced usage and move the ToC higher up the page so improve its visibility.
