### ISSUE TITLE
Dependency on SciPy 

### ISSUE THREAD

**Issue by zemogle** [astropy/astropy#8956]
When running `astropy.coordinates.sky_coordinate.match_to_catalog_sky` I had an error because SciPy `spatial` was not installed. One of the really nice things about `astropy` was that there is no dependency except `numpy`. It seems a shame if the full might of `scipy` is needed for this one function. If there are other instances of `from scipy import...` statements maybe its time to bite the bullet and include it as a dependency.

**Comment by bsipocz** [comment]
scipy is an optional dependency for many subpackages, but it might not always be mentioned in the docstring of the specific functions which need to be fixed.

**Comment by smoh** [comment]
I am just commenting but the docstring does correctly mention scipy is need for these function/method and scipy is needed in order to build KDTree, which numpy just does not have. Optional dependency on scipy seems like a logical thing than to write an astropy's KDTree especially since there may be other modules in astropy that might need scipy for something else.

**Comment by bsipocz** [comment]
@zemogle - in this case scipy is indeed noted in the docstrings, but not on the narrative docs. Have you read either of those docs? If yes could you please suggest where would it have been useful to see that this functionality depends on scipy?

**Comment by zemogle** [comment]
Actually I didn't read either. astropy is being used by my collaborator in some analysis code. I'm trying to make the code easier to install and use. As SciPy wasn't an explicit dependency I missed it. The error made it obvious that it was needed. I just hadn't realised that SciPy was even an optional dependency, which is what surprised me.

**Comment by bsipocz** [comment]
@zemogle - astropy in fact has many optional dependencies: http://docs.astropy.org/en/latest/install.html
