### ISSUE TITLE
Handling test exception messages

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#8959]
When converting checks for expected error messages in `ExceptionInfo` instances to `str(excinfo.value)` calls in #8949 I found a couple of checks that had to keep the `str(e)` syntax. The actual reason for this was not the type of exception but the calling method, with the latter cases using a plain `try: ... except:` construct like:
```
        try:
             fits.open(self.temp('foobar.fits'))
        except OSError as e:
            assert 'No such file or directory' in str(e)
```
where `e` is the `Exception` itself, rather than the `ExceptionInfo` that `pytest.raises(...) as e` returns. Probably should not have been surprising as `ExceptionInfo` is a pytest-specific class.
So this form produces the expected result with `str()` but does not have a `value` method.
Still this might cause confusion when adding or editing tests; I see three options to proceed:

1. Leave those tests as they are, as everything works for now.

2. Check against `e.args[0]` instead, to be a bit more specific (although `ExceptionInfo` has an `args` method as well.

3. Convert to `pytest.raises` wherever possible, which allows for more concise code as well, e.g. the above test would become
```
        with pytest.raises(OSError, match='No such file or directory') as excinfo:
            fits.open(self.temp('foobar.fits'))
```

In any case I propose to recommend the 3rd variant in a yet-to-be-written section on testing exceptions in the developer guidelines.

**Comment by dhomeier** [comment]
`pytest.raises` also ensures that exceptions that are never raised are not missed, as is currently the case in `units/tests/test_format.py::test_deprecated_did_you_mean_units`:
```
    try:
        u.Unit('ANGSTROM', format='vounit')
    except ValueError as e:
        assert 'angstrom (deprecated)' in str(e.value)
        assert '0.1nm' in str(e.value)
        assert str(e.value).count('0.1nm') == 1
```
(missing an `else: self.fail('An exception should have been raised.')`...)
```
>>> u.Unit('ANGSTROM', format='vounit')
WARNING: UnitsWarning: Unit 'ANGSTROM' not supported by the VOUnit standard. Did you mean 0.1nm, Angstrom (deprecated) or angstrom (deprecated)? [astropy.units.format.vounit]
Unit("ANGSTROM")
```

**Comment by dhomeier** [comment]
Actually I believe the error is on the side of `vounit.py`; have been trying to figure out what their
```
_custom_unit_regex = re.compile(r"^((?!\d)\w)+$")
...
            if not cls._custom_unit_regex.match(unit):
                raise ValueError()
```
check is supposed to test, but I doubt that this is the intended behaviour:
```
>>> u.Unit('Angstrm', format='vounit')
WARNING: UnitsWarning: Unit 'Angstrm' not supported by the VOUnit standard. Did you mean 0.1nm, Angstrom (deprecated) or angstrom (deprecated)? [astropy.units.format.vounit]
Unit("Angstrm")
>>> u.Unit('JABBRWCK', format='vounit')
WARNING: UnitsWarning: Unit 'JABBRWCK' not supported by the VOUnit standard.  [astropy.units.format.vounit]
Unit("JABBRWCK")
>>> u.Unit('log10', format='vounit')
WARNING: UnitsWarning: Unit 'log' not supported by the VOUnit standard.  [astropy.units.format.vounit]
Unit("log10")
>>> u.Unit('3pence', format='vounit')
WARNING: UnitsWarning: Unit 'pence' not supported by the VOUnit standard.  [astropy.units.format.vounit]
Unit("3 pence")
```
Anyway the test did not catch it.

**Comment by pllim** [comment]
I think there are two different issues here:

1. Refactor how exception is caught in tests to make them more consistent. -- FWIW I actually prefer to leave them as-is. As you said, they work currently, so compared to all the other things we need to fix, these don't appear to be high priority. But then again, if someone has the time to make a PR, why not?
2. An actual bug in `vounit`. -- I think this is the same as #6302

**Comment by dhomeier** [comment]
1. In the case of `test_deprecated_did_you_mean_units` it did not work, since the purpose of the test certainly was to ensure that a `ValueError` is raised. I actually only found half a dozen or so instances where `try:` is used instead of `pytest.raises`, so the scope is modest.

2. Yes, somehow I missed #6302, but it is not just ignoring the default `parse_strict='raise'`, but is not returning an `UnrecognizedUnit` instance with either option. Already had some vague approaches for solving it, only I was not sure up to now what really was the desired behaviour, or what @mdboom intended to check with the `regex.match` in [76c2b72](https://github.com/astropy/astropy/commit/76c2b72a9004da7ff644d8ec5c049d4a821e2bf4#r34198954). I'll put this in a separate PR.
