### ISSUE TITLE
Add Table `zip_columns` method for faster row iteration

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8962]
One way to substantially improve performance when iterating over rows is to avoid explicit use of `Row` for access.  Instead of:
```
for row in tbl:
   function(row['a'], row['b'], row['z'])
```
Do:
```
for a, b, z in zip(tbl['a'], tbl['b'], tbl['z']):
   function(a, b, z)
```
This is much faster because it ends up using C-level iteration instead of a lot of Python code to make a `Row` and then access it.

In many cases of iterating over table rows, one only cares about a small subset of the column values.  So we can make the above nicer with:
```
for a, b, z in tbl.zip_columns('a', 'b', 'z'):
   function(a, b, z)
```

~~One question is if the name is confusing.  Technically it should be called `zip_columns`, but I'm not sure that would make more sense to the average user.~~ [Changed to `zip_columns`].

@himanshupathak21061998 - this might be a good straightforward table performance issue to try.

**Comment by himanshupathak21061998** [comment]
Sure, I will try to fix this.

**Comment by saimn** [comment]
This seems a great idea, I frequently use this to iterate on column values. 
About the name, I think I prefer `zip_columns` which is closer to what it actually does (calling zip on given columns). `iterrows` is more confusing because there are several possible way to iterate on rows: it could return `Row` object, or just a tuple, or a dict.

**Comment by taldcroft** [comment]
@saimn - I hear you about the name, I'm just wondering about the median user and how familiar is `zip`.  My thoughts often go to tab completion, seeing `iterrows` in the list next to `itercols`, and then `t.iterrows?`.  I'm not super concerned about potential ambiguity in the output since it is so easy to discover the answer.  If you are reading code then `for a, c, e in tbl.iterrows('a', 'c', 'e'):` gives you are pretty strong clue about what's happening.

That said, I can go either way, esp. if others weigh in.

One thing that occurred to me is that `tbl.iterrows()` could be short-hand for `tbl.iterrows(*tbl.colnames)`, i.e. zip over all the columns.

**Comment by mhvk** [comment]
On the name: I'd agree with @saimn that I would actually expect to get `Row` objects out, just like `itercols` gives `Column` objects. Maybe `itervalues`?

Alternatively, would it be possible to improve the table iteration generally, by improving how `Row` works? E.g., if I now do
```
t = Table([np.arange(3.), np.ones(3)], names=['a', 'b'])
a,b  = t[1]
```
it works, but inside `Row.__getitem__`, it has to pass through a `try/except` and ends up at [what is supposed to raise an exception](https://github.com/astropy/astropy/blob/master/astropy/table/row.py#L57) - it might be that just by checking for an integer `item`, we'd speed things up considerably. Or possibly have a `Row` subclass specifically for iteration.

**Comment by taldcroft** [comment]
On the name it looks like `zip_columns` wins.  @himanshupathak21061998 please change accordingly.

**Comment by taldcroft** [comment]
About the `a, b = t[1]`, that's very interesting!  I never actually thought about how that works, and didn't consider that code pathway.  So yes, that could probably be made much faster.

I don't think it changes the utility of `zip_columns`, which will be faster anyway and also addresses the common case of just wanting a few columns from a wider table.

**Comment by mhvk** [comment]
Agreed - `zip_columns` is useful regardless - it also helps make sure the columns are zipped in an explicit order.
