### ISSUE TITLE
match_to_catalog_sky should raise a nicer error when the match or catalog coordinates have nan values

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#8985]
I believe this is related to this [SO question](https://stackoverflow.com/questions/55319837/how-to-fix-index-error-when-trying-to-match-catalogs-using-astropy-coordinates) filed a few months ago.

Basically, `match_to_catalog_sky()` is throwing an `IndexError` and I can't figure out why. I'm using  `Python 3.7.3` and `astropy 3.1.2`.

Here's the code to reproduce it ([data files](https://github.com/astropy/astropy/files/3388200/data.zip)):

```
from astropy.io import ascii
from astropy.coordinates import SkyCoord
from astropy import units as u

d1 = ascii.read('c1.dat')
ra_obs, dec_obs = d1['ra'], d1['dec']
d2 = ascii.read('c2.dat')
ra_qry, dec_qry = d2['ra'], d2['dec']

c1 = SkyCoord(ra_obs, dec_obs, unit=(u.degree, u.degree))
c2 = SkyCoord(ra_qry, dec_qry, unit=(u.degree, u.degree))

idx, d2d, d3d = c1.match_to_catalog_sky(c2)
```

The full traceback is:

```
$ python test.py
/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/angles.py:642: RuntimeWarning: invalid value encountered in less
  if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):
/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/angles.py:642: RuntimeWarning: invalid value encountered in greater_equal
  if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):
/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/angles.py:529: RuntimeWarning: invalid value encountered in less
  if np.any(angles.value < lower) or np.any(angles.value > upper):
/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/angles.py:529: RuntimeWarning: invalid value encountered in greater
  if np.any(angles.value < lower) or np.any(angles.value > upper):
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    idx, d2d, d3d = c1.match_to_catalog_sky(c2)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/sky_coordinate.py", line 1045, in match_to_catalog_sky
    storekdtree='_kdtree_sky')
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/matching.py", line 154, in match_coordinates_sky
    idx, sep2d, sep3d = match_coordinates_3d(newmatch_u, newcat_u, nthneighbor, storekdtree)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/matching.py", line 83, in match_coordinates_3d
    sep2d = catalogcoord[idx].separation(matchcoord)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/utils/misc.py", line 940, in __getitem__
    return self._apply('__getitem__', item)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/baseframe.py", line 1476, in _apply
    new._data = apply_method(self.data)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/baseframe.py", line 1447, in apply_method
    return value._apply(method, *args, **kwargs)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/representation.py", line 780, in _apply
    rep = super()._apply(method, *args, **kwargs)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/coordinates/representation.py", line 263, in _apply
    apply_method(getattr(self, component)))
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/astropy/units/quantity.py", line 1035, in __getitem__
    out = super().__getitem__(key)
IndexError: index 22670 is out of bounds for axis 0 with size 22670
```

**Comment by smoh** [comment]
I think it's because you have nan entries in c2. Not sure if this was also the cause for the SO question but it seems to work fine once you clean nans in c2.


```python
clean = (~np.isnan(c2.ra) & ~np.isnan(c2.dec))
print(len(c2), clean.sum(), len(c2)-clean.sum())
c2_clean = c2[clean]
```

    22670 12660 10010



```python
idx, d2d, d3d = c1.match_to_catalog_sky(c2_clean)
```

The nan entries seems to completely mess up KDTree build from them making it return dist=inf and idx=(lenth of catalogcoord). Not sure if this was handled in previous versions of astropy.

**Comment by Gabriel-p** [comment]
Thank you @smoh! I should've caught that.

Shouldn't astropy throw a more descriptive error message? This error is quite obscure. I'll leave this open a few days to see if I get some input on this, if not I'll just close it.

Cheers

**Comment by smoh** [comment]
Yea, a simple input validation within the function sounds like a good idea.

**Comment by adrn** [comment]
Yes, agreed! Do either of you want to try implementing that? I think you could just check for `np.isnan()` in the sky coordinates (for `match_to_catalog_sky`) and in any component (for `match_to_catalog_3d`) and raise a nicer `ValueError`.

**Comment by Gabriel-p** [comment]
How about something like this?

```
for coords in (matchcoord, catalogcoord):
    if (~np.isnan(coords.ra) & ~np.isnan(coords.dec)).sum() > 0:
        raise ValueError(
            'The catalogs for coordinate matching cannot contain '
            'nan values.')
```

**Comment by Gabriel-p** [comment]
How about something like this?

    for coords in (matchcoord, catalogcoord):
        if (np.isnan(coords.ra) | np.isnan(coords.dec)).sum() > 0:
            raise ValueError(
                'The catalogs for coordinate matching cannot contain '
                'nan values.')

**Comment by smoh** [comment]
Hmm, the snippet looks fine please go for it if you want to try.

Just a couple of concerns:
- I think it might be better to check this right before the KDTree is built but not earlier e.g., after line 147 in matching.py so that it deals with being called from any other coordinate frames (e.g., Galactic) seamlessly. I think in this case, we should check `.lon` `.lat` (or maybe even lower level internal storage variable of the data itself). My worry is the snippet as is will not fix anything for other coordinate frames (which can have different convention for longitude and latitutde like `l` and `b` for Galactic).
- Because it's the same routine for `match_coordinates_3d`, it occurs to me that maybe we want to add check to that as well.

**Comment by smoh** [comment]
(Oops, just saw @adrn mentioned `_3d` methods already)
