### ISSUE TITLE
Rewrite WCSLIB wrapper in Cython?

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#8989]
I just now for the first time looked at the WCSLib wrapper in  #8988.

The Python C API and having to do reference counting manually is difficult to understand and maintain, no? (like me, most devs and contributors don't know the Python C API or don't know it well)

Has rewriting this wrapper in Cython been discussed before?
Does anyone think it would be a useful thing to do?

**Comment by MSeifert04** [comment]
It depends a lot on the number of people (maintainers/contributors) familiar with Cython or C and the C-API. In some sense you have to know the C-API too if writing Cython (but not as much).

Rewriting it requires someone who is at least "good" in both technologies to avoid introducing bugs or differences (depends also on how well-tested the C wrapper currently is).

**Comment by cdeil** [comment]
@nden - thoughts?

(feel free to close directly if you don't think it's a good idea, or just not going to happen because it's not worth the effort)

**Comment by nden** [comment]
I'm not sure whether it's a good or bad idea. Given that `wcs` still does not have a formal maintainer and the amount of testing this work will require, I think it's not worth it at the moment. I also agree with @MSeifert04's thoughts above.

**Comment by cdeil** [comment]
Just to explain where this suggestion is coming from: at EuroPython this year there was a lot of talk about issues and possible changes with the Python C API, and e.g. the clear message in 
https://github.com/vstinner/talks/blob/master/2019-EuroPython/python_performance.pdf was  to use Cython.

I personally don't like Cython much, with this mix of Python & C and being a new language. But Cython taking care of refcounting and always getting it right is a huge plus. I think fewer and fewer people will know that Python C API well and can maintain non-trivial Python C API code, given that now Cython and Numba exist.

That said, I can completely understand that it doesn't make sense to rewrite this interface now. Closing this issue for now. Could be something worth considering as long-term solution, some time in the coming years.
