### ISSUE TITLE
Consistent scheme for file/directory locking

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#90]
We should have a function/class in `utils` that can be used to lock files or directories to enable thread/process-safe file access. @mdboom pointed out  http://code.google.com/p/pylockfile/ as a good place to look for the way we want to do this (perhaps even just pull it into extern).

Once this is done, these packages (and possibly others I'm not aware of) should be updated to use it:
- astropy.config.data
- astropy.config.configs (maybe?)
- astropy.vo
- astropy.io.fits (not yet in master)

**Comment by astrofrog** [comment]
Removing 1.0 milestone since there has been no work on this recently and this is not critical.

**Comment by pllim** [comment]
> astropy.io.fits (not yet in master)

Yeah. Let's close this!
