### ISSUE TITLE
TST: visualization tests consume too much memory?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9002]
In looking at #7928 , I see the following warnings in `astropy.visualization` tests:

```
RuntimeWarning: More than 20 figures have been opened.
Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained
until explicitly closed and may consume too much memory.
(To control this warning, see the rcParam `figure.max_open_warning`).
```

Is this the right place to configure `max_open_warning`? Or is there another way to explicitly close the figures (https://matplotlib.org/2.1.0/api/_as_gen/matplotlib.pyplot.close.html)? @astrofrog ?

https://github.com/astropy/astropy/blob/fb13ac3afb498441bf9ad12a6e61247bfe172e8d/astropy/conftest.py#L37-L39

Example Travis CI log: https://travis-ci.org/astropy/astropy/jobs/559217591

Example test emitting the warning:
```
astropy/visualization/tests/test_units.py::test_nested
  .../astropy/visualization/tests/test_units.py:114: RuntimeWarning:
More than 20 figures have been opened. Figures created through the
pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly
closed and may consume too much memory. (To control this warning,
see the rcParam `figure.max_open_warning`).
    fig = plt.figure()
```

**Comment by dstansby** [comment]
I ran the figure tests yesterday locally and didn't see these warnings, so would recommend closing this?

**Comment by pllim** [comment]
Sure, I forgot about this and I don't see us ignoring it in `setup.cfg`. Thanks for the ping!
