### ISSUE TITLE
Cannot read some non-standard FITS files

### ISSUE THREAD

**Issue by aplavin** [astropy/astropy#9003]
I'm trying to read a fits file and get its header and contents, but no matter what I do `astropy` gives me errors:

```python
with fits.open(Path('J0721+7120_C_2014_02_18_pet_vis.fits').open('rb')) as f:
    f['PRIMARY'].header['RA']

---------------------------------------------------------------------------
VerifyError                               Traceback (most recent call last)
<ipython-input-44-e7947a571936> in <module>
      1 with fits.open(Path('J0721+7120_C_2014_02_18_pet_vis.fits').open('rb')) as f:
----> 2     f['PRIMARY'].header['RA']

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/header.py in __getitem__(self, key)
    152             return card.rawvalue
    153 
--> 154         value = card.value
    155         if value == UNDEFINED:
    156             return None

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/card.py in value(self)
    283             value = self._value
    284         elif self._valuestring is not None or self._image:
--> 285             value = self._value = self._parse_value()
    286         else:
    287             if self._keyword == '':

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/card.py in _parse_value(self)
    765         if m is None:
    766             raise VerifyError("Unparsable card ({}), fix it first with "
--> 767                               ".verify('fix').".format(self.keyword))
    768 
    769         if m.group('bool') is not None:

VerifyError: Unparsable card (RA), fix it first with .verify('fix').
```

```python
with fits.open(Path('J0721+7120_C_2014_02_18_pet_vis.fits').open('rb')) as f:
    f.verify('fix')

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-ed0088ff4893> in <module>
      1 with fits.open(Path('J0721+7120_C_2014_02_18_pet_vis.fits').open('rb')) as f:
----> 2     f.verify('fix')

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/verify.py in verify(self, option)
     71             return
     72 
---> 73         errs = self._verify(opt)
     74 
     75         # Break the verify option into separate options related to reporting of

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in _verify(self, option)
   1191 
   1192         # the first (0th) element must be a primary HDU
-> 1193         if len(self) > 0 and (not isinstance(self[0], PrimaryHDU)) and \
   1194                              (not isinstance(self[0], _NonstandardHDU)):
   1195             err_text = "HDUList's 0th element is not a primary HDU."

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in __len__(self)
    226     def __len__(self):
    227         if not self._in_read_next_hdu:
--> 228             self.readall()
    229 
    230         return super().__len__()

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in readall(self)
    767         Read data of all HDUs into memory.
    768         """
--> 769         while self._read_next_hdu():
    770             pass
    771 

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in _read_next_hdu(self)
   1137                                 fileobj.seek(offset, os.SEEK_SET)
   1138 
-> 1139                         hdu = _BaseHDU.readfrom(fileobj, **kwargs)
   1140                     except EOFError:
   1141                         self._read_all = True

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py in readfrom(cls, fileobj, checksum, ignore_missing_end, **kwargs)
    326         hdu = cls._readfrom_internal(fileobj, checksum=checksum,
    327                                      ignore_missing_end=ignore_missing_end,
--> 328                                      **kwargs)
    329 
    330         # If the checksum had to be checked the data may have already been read

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py in _readfrom_internal(cls, data, header, checksum, ignore_missing_end, **kwargs)
    462                     del new_kwargs[key]
    463 
--> 464         hdu = cls(data=DELAYED, header=header, **new_kwargs)
    465 
    466         # One of these may be None, depending on whether the data came from a

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/table.py in __init__(self, data, header, name, uint, ver, character_as_bytes)
    851 
    852         super().__init__(data, header, name=name, uint=uint, ver=ver,
--> 853                          character_as_bytes=character_as_bytes)
    854 
    855     @classmethod

~/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/table.py in __init__(self, data, header, name, uint, ver, character_as_bytes)
    370         if not (isinstance(self._header[0], str) and
    371                 self._header[0].rstrip() == self._extension):
--> 372             self._header[0] = (self._extension, self._ext_comment)
    373 
    374         # Ensure that the correct EXTNAME is set on the new header if one was

TypeError: '_BasicHeader' object does not support item assignment
```

The example file can be downloaded from `http://astrogeo.org/images/J0721+7120/J0721+7120_C_2014_02_18_pet_vis.fits`.

`astropy.__version__ = '3.2.1'`

**Comment by MSeifert04** [comment]
The `RA` keyword is indeed invalid. It's `07:21:53.448479` which probably should be `'07:21:53.448479'` (a string). There are several other invalid keyword values in there.

Do you know who created the FITS file? This seems highly non-standard (although probably automatically fixable).

**Comment by aplavin** [comment]
But isn't `verify('fix')` supposed to fix this kind of issues? If I'm not mistaken, earlier versions of `astropy` could read this file and run `verify` on it. At least on the surface the difference seems related to https://github.com/astropy/astropy/commit/e74726b49fe100a3595b7a52fd0624df405fa2d5.

I do know who created those files, but they are very unlikely to be fixed. Also those files are routinely read without issues by other astronomical software, and (as I remember) could be opened by older `astropy` versions as well.

**Comment by saimn** [comment]
The problem is that the file uses A3DTABLE extensions, which are not standard but is a registered name treated like a BINTABLE (and that is not supposed to be used anymore). And when creating the HDU object, it attempt to replace the extension name with BINTABLE, which cannot be done with the new `_BasicHeader` (which suppose that headers are not modified during the HDU creation). And of course this is a special case that was not tested.

![Capture d’écran de 2019-07-16 11-46-10](https://user-images.githubusercontent.com/311639/61284538-7250c980-a7bf-11e9-8f73-5777016e9578.png)

https://github.com/astropy/astropy/blob/cfbb7e52cadc66ec0212f6a3bf67f1c44a6ae0f5/astropy/io/fits/hdu/table.py#L370-L372

I need to think about the best solution, that could be just moving these lines into `_verify` (which seems to work), or we could just keep the A3DTABLE name.

**Comment by saimn** [comment]
Just a precision: when using `f['PRIMARY'].header['RA']` it fails because RA is invalid but does not read the A3DTABLE extensions. But then `f.verify('fix')` runs the verification on all HDUs which trigger the issue with the extension name. If you need only to access the first extension you can verify only this one with `f['PRIMARY'].verify('fix')`.

**Comment by aplavin** [comment]
Indeed, `f['PRIMARY'].verify('fix')` works as you say. However, it doesn't help with reading other tables: e.g. `f['AIPS FQ']` throws same exception, and obviously `f['AIPS FQ'].verify('fix')` does as well. I cannot even print the information about fits file, `print(f)` and `print(f.info())` throw exceptions.

**Comment by aplavin** [comment]
Any ideas how to read such files until the regression is fixed? Like monkeypatching something, or somehow using whatever header class was there before BasicHeader?

**Comment by pllim** [comment]
Well, a hacky way is to write your own preprocessing script to sanitize the data files before calling `astropy.io.fits`... But maybe @saimn has a better idea.

**Comment by saimn** [comment]
@aplavin - See  #9012 for a proposed fix.

**Comment by aplavin** [comment]
Thanks a lot for that prompt response and fix! I installed latest astropy by running `pip install git+https://github.com/astropy/astropy` and it can read all the files from that dataset.
