### ISSUE TITLE
TST: CircleCI HTML job broken because pytest.org is down

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9033]
`html-docs` job is broken with

```
Warning, treated as error:
failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.pytest.org/en/stable/objects.inv' not fetchable ...
Sphinx Documentation subprocess failed with return code 2
Exited with code 2
```

Example log: https://circleci.com/gh/astropy/astropy/38083

**Comment by pllim** [comment]
@bsipocz , do you think it is worth changing `intersphinx` to point to https://pytest.readthedocs.io/en/latest/objects.inv ?

**Comment by bsipocz** [comment]
Sounds reasonable. I suppose they don't plan to move out from RTD any time soon anyway.

**Comment by pllim** [comment]
See #9037
