### ISSUE TITLE
Sphinx warnings on local build and not on CI

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#9040]
I did a fresh install of Anaconda with Python 3.7.3, Sphinx 2.1.2, and ran the docs build with current astropy master. I get a number of warnings that don't seem to appear on circleCI:
```
WARNING: toctree references unknown document 'api/astropy.units.function.logarithmic.m_bol'
/Users/apricewhelan/projects/astropy/build/lib.macosx-10.7-x86_64-3.7/astropy/visualization/wcsaxes/core.py:docstring of astropy.visualization.wcsaxes.WCSAxes.get_tightbbox:40: WARNING: py:obj reference target not found: matplotlib.axis.Axes.get_window_extent
/Users/apricewhelan/projects/astropy/build/lib.macosx-10.7-x86_64-3.7/astropy/visualization/wcsaxes/core.py:docstring of astropy.visualization.wcsaxes.WCSAxes.get_tightbbox:44: WARNING: py:obj reference target not found: matplotlib.spines.get_window_extent
/Users/apricewhelan/projects/astropy/docs/index.rst:: WARNING: toctree contains reference to nonexisting document 'api/astropy.units.function.logarithmic.m_bol'
/Users/apricewhelan/projects/astropy/docs/units/index.rst:397:<autosummary>:1: WARNING: py:obj reference target not found: astropy.units.function.logarithmic.m_bol
/Users/apricewhelan/projects/astropy/docs/units/index.rst:397:<autosummary>:: WARNING: toctree contains reference to nonexisting document 'api/astropy.units.function.logarithmic.m_bol'
```
cc @pllim

**Comment by pllim** [comment]
@adrn , on Slack, did you mean you fixed these as well in #9035 ?

**Comment by adrn** [comment]
Nope. But it sounds like the ones about `m_bol` are a case-insensitivity issue. The two `astropy.visualization` ones look like the only remaining problems

**Comment by bsipocz** [comment]
The visualization ones are upstream, and will be fixed with the next mpl bugfix release (thus we pin the version in our CI).

**Comment by bsipocz** [comment]
Not sure whether we can do anything with the case sensitivity, it very much looks like an addition to the "known problems" page, users are not normally building the docs themselves anyway, and us devs can live with the warning and messed up links locally.

**Comment by bsipocz** [comment]
Closing this now as upstream https://github.com/matplotlib/matplotlib/issues/14551 was fixed (and will be available in mpl 3.1.2)

**Comment by mhvk** [comment]
Strange about `m_bol` - that unit does exist and seems linked fine on `readthdocs`: http://docs.astropy.org/en/latest/units/index.html#variables

**Comment by bsipocz** [comment]
@mhvk - RTD is linux based, so the case insensitive confusion doesn't come up between `M_bol` and `m_bol`
