### ISSUE TITLE
Add example of reading a FITS image using `CCDData` to the FITS documentation 

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#9043]
I do not think we currently mention `CCDData.read` in the documentation for `io.fits` even though there several advantages to opening images that way.

At a minimum inserting an example at https://astropy.readthedocs.io/en/stable/io/fits/index.html#working-with-image-data would be helpful, along with a brief explanation of when to use the lower-level `fits.io` and when to use `CCDData`.

**Comment by mtanvi19** [comment]
Is the issue still open?

**Comment by neutrinoceros** [comment]
Yes, it is still relevant.

**Comment by mtanvi19** [comment]
I would like to work on this. Could it be assigned to me (if issues are assigned to contributors)?

**Comment by neutrinoceros** [comment]
We usually don't assign issues, but a pull request would be most welcome !
