### ISSUE TITLE
Make a pretty printer for OrderedDict

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#905]
`OrderedDict` is used in many places within astropy, but printing an OrderedDict object gives an ugly and difficult-to-read output.  `pprint` is no better.  Some quick googling led to some stackoverflow answers but nothing really helpful.

Having a readable representation of these objects would be useful.  One idea is to customize `pprint.pformat` to work with OrderedDict, then use that as `__repr__` or `__str__` in astropy the OrderDict class.

If someone is bored maybe this would be a good little project...

**Comment by astrofrog** [comment]
@taldcroft - I'd forgotten about this - how do we want to proceed given that we've now removed the ``OrderedDict`` sub-class? My suggestion would be to close this and submit a patch to Python itself if we think it's important enough (incidentally, Python will be developed on GitHub soon, so that should be easy)

**Comment by taldcroft** [comment]
I think a patch to Python would be a great idea but likely to be a very steep hill to climb.  I was thinking just now about monkey-patching the `__repr__` for relevant *instances* (e.g. meta objects in particular).  For some reason it does not work as expected.  Ideas?
```
In [1]: from collections import OrderedDict

In [2]: OrderedDict??
...
    @_recursive_repr()
    def __repr__(self):
        'od.__repr__() <==> repr(od)'
        if not self:
            return '%s()' % (self.__class__.__name__,)
        return '%s(%r)' % (self.__class__.__name__, list(self.items()))
...

In [3]: a = OrderedDict([(1, 2)])

In [4]: import types

In [5]: def myrepr(self):
    print('hello')
    return super(self.__class__, self).__repr__()
   ...: 

In [7]: a.myrepr = types.MethodType(myrepr, a)

In [8]: a.myrepr()
hello
Out[8]: '{1: 2}'

In [9]: repr(a)
Out[9]: 'OrderedDict([(1, 2)])'

In [10]: a.__repr__ = types.MethodType(myrepr, a)

In [11]: a
Out[11]: OrderedDict([(1, 2)])

In [12]: repr(a)
Out[12]: 'OrderedDict([(1, 2)])'
```

**Comment by taldcroft** [comment]
So I still think this is a worthwhile thing to do if we can define a technically simple solution.

**Comment by embray** [comment]
@taldcroft Your example above won't work because `__repr__` is a type slot, and can't be overridden on a per-instance basis.  Google Armin Ronacher's rant about slots for more info.  

Remind me again why we don't just use a subclass of `OrderedDict`?

**Comment by taldcroft** [comment]
@embray - that just got a bit harder after #4466.  :stuck_out_tongue_closed_eyes:  I actually forgot about this issue in reviewing that one...

**Comment by embray** [comment]
We could still implement our own BetterOrderedDict in astropy.utils and say something in the developer docs that its use should be preferred, at least in cases where users will interact with it.  But I agree, it's a pain :\

**Comment by bsipocz** [comment]
Since we have deprecated ``utils.compat.odict.OrderDict`` I propose to close this and direct improvement efforts upstream.

If you think otherwise please feel free to reopen.
