### ISSUE TITLE
TST: CircleCI 32-bit tests broken with Numpy 1.17.0

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9059]
**UPDATE:** Remember to undo #9076 when fixing this.

CircleCI 32-bit tests broken on `master` when it started picking up Numpy 1.17 instead of 1.16.

Used to pass: https://circleci.com/gh/astropy/astropy/38530

Started failing (and still failing): https://circleci.com/gh/astropy/astropy/38549

```
_______________________ test_roundtrip_sky_rotaion[inp0] _______________________
[gw0] linux -- Python 3.6.8 /opt/python/cp36-cp36m/bin/python

inp = (0, 0)

    @pytest.mark.parametrize(('inp'), [(0, 0), (40, -20.56), (21.5, 45.9)])
    def test_roundtrip_sky_rotaion(inp):
        lon, lat, lon_pole = 42, 43, 44
        n2c = models.RotateNative2Celestial(lon, lat, lon_pole)
        c2n = models.RotateCelestial2Native(lon, lat, lon_pole)
        assert_allclose(n2c.inverse(*n2c(*inp)), inp, atol=1e-13)
>       assert_allclose(c2n.inverse(*c2n(*inp)), inp, atol=1e-13)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=1e-13
E       
E       Mismatch: 50%
E       Max absolute difference: 360.
E       Max relative difference: inf
E        x: array([3.600000e+02, 7.083257e-15])
E        y: array([0, 0])

astropy/modeling/tests/test_rotations.py:45: AssertionError
_______ [doctest] astropy.stats.info_theory.bayesian_info_criterion_lsq ________
[gw2] linux -- Python 3.6.8 /opt/python/cp36-cp36m/bin/python
171     >>> g_init = models.Gaussian1D(amplitude=1., mean=0, stddev=1.)
172     >>> fit_g = fitting.LevMarLSQFitter()
173     >>> g = fit_g(g_init, x, y)
174     >>> # Compute the mean squared errors
175     >>> ssr_t = np.sum((t(x) - y)*(t(x) - y))
176     >>> ssr_g = np.sum((g(x) - y)*(g(x) - y))
177     >>> # Compute the bics
178     >>> bic_t = bayesian_info_criterion_lsq(ssr_t, 4, x.shape[0])
179     >>> bic_g = bayesian_info_criterion_lsq(ssr_g, 3, x.shape[0])
180     >>> bic_t - bic_g # doctest: +FLOAT_CMP
Expected:
    30.644474706065466
Got:
    31.11155402550662

/tmp/astropy-test-pu67bw6x/lib/python3.6/site-packages/astropy/stats/info_theory.py:180: DocTestFailure
```

cc @mhvk (in case you know what in Numpy might have caused regression in 32-bit)

**Comment by bsipocz** [comment]
Some of the diff are quite puzzling, maybe @mhvk can comment?

**Comment by mhvk** [comment]
I'm pretty sure numpy tests with 32 bit, so it would be good to get to the bottom of this (at least find a more minimal example). I'm on vacation so won't get to this until end of August....

**Comment by pllim** [comment]
Numpy was pinned for 32-bit in #9076 but I cannot find that pin anymore after #9726 . So is it still pinned or can we close this?

**Comment by bsipocz** [comment]
I think we can close this, numpy doesn't seemed to be pinned any more.

**Comment by astrofrog** [comment]
I still seem to need to pin Numpy in the v4.0.x branch 🤔

**Comment by embray** [comment]
I'm not sure if this is still needed...?

We're running the 32-bit tests with GH Actions now, not CircleCI.  In Actions we are still pinning the 32-bit tests to use Numpy 1.16, but only on the LTS branch.  But do we think this is particularly important to fix for the LTS branch?

**Comment by pllim** [comment]
LTS is changing in a few months, so I am okay to close.
