### ISSUE TITLE
TST: Appveyor build failing on master

### ISSUE THREAD

**Issue by tomdonaldson** [astropy/astropy#9061]
The Appveyor build failed on my PR (https://github.com/astropy/astropy/pull/9057) after rebasing.  

The Appveyor build showed successful after the last commit on master 3 days ago.  When I triggered a new build Appveyor build on master, and it failed in the same way as on my PR. The failure comes quite early in the environment setup process.

The build log is here:  https://ci.appveyor.com/project/Astropy/astropy/builds/26318884

**Comment by pllim** [comment]
The timing is suspicious as it coincide with #9059 and #9060 . @bsipocz , is there something that needs to be done on `ci-helpers` side?
