### ISSUE TITLE
Modeling documentation enhancement

### ISSUE THREAD

**Issue by karllark** [astropy/astropy#9069]
The idea is to add more examples and made them easier to find/navigate.

Main page:
One, very simple example

Short(!) paragraph of the goal of modeling package

link to page with concise listing of options for models (explain terminology)
  compound models, model sets, bounding boxes

Then, a list of examples illustrating all the great capabilities (separate page each)

- [ ] fitting with masks
- [ ] fitting with uncertainties
- [ ] fitting with constraints
- [ ] fitting with priors
- [ ] fitting with units
- [ ] defining 1d model
- [ ] defining 2d model
- [ ] fitting 2d model
- [ ] defining and using a WCS/gWCS model
- [ ] defining and using a Tabular1D model
- [ ] statistics functions and how to make your own
- [ ] compound models
- [ ] model sets w/ fitting

Would be great to have gallery of plots showing the different existing models

Useful to have a listing (in gallery) of which models support units and describe that compound models with units are possibly slow

Needed is a list of topic pages. These are pages that explain various aspects of modeling (with links to examples in the above list for illustration). These pages are intended to be fairly comprehensive, but none in particular should be very long (i.e., should be split into separate pages if they become long).

- [ ] Basic Modeling
- [ ] Defining new models not present in existing packages
- [ ] Basics of combining models
- [ ] Advanced model combining
- [ ] Parameters and how they are used in models
- [ ] Using units in models
- [ ] Basic Fitting
- [ ] Fitting with constraints
- [ ] Fitting with units
- [ ] Fitting with different or custom statistics functions
- [ ] Estimation of fitting errors
- [ ] Adding a new fitter
- [ ] Using models with Bayesian tools
- [ ] Model bounds
- [ ] Model sets
- [ ] Performance tips (how to not to be slow)

**Comment by pllim** [comment]
Not so sure about the gallery, decision pending at #7242.

**Comment by karllark** [comment]
Maybe a gallery is not the right word.  Just a matrix of figures with labels that are links.  Maybe easier for users to see what is possible.

**Comment by karllark** [comment]
See #PR 9078 and the comment by @perrygreenfield about a possible improvement to the organization on the main page.

**Comment by karllark** [comment]
Not sure having a large issue like this makes the most sense.  Might be better to generate a series of issues that break the work into small pieces.

**Comment by karllark** [comment]
Work separated into multiple issues to make it easier to track and different people to work on.  See #9127, #9128, #9129, #9130, #9131, #9132, #9133, and #9134.

Closing this issue as a result.
