### ISSUE TITLE
Add inverse to Tabular1D model

### ISSUE THREAD

**Issue by nden** [astropy/astropy#9070]

**Comment by pllim** [comment]
What does this mean? If I have `points=[1, 2, 3]` and `lookup_table=[4, 5, 6]`, will this do one of the following? Which one?

(a) `points=[1, 2, 3]; lookup_table=[6, 5, 4]`

(b) `points=[1, 2, 3]; lookup_table=[1/4, 1/5, 1/6]`

**Comment by jdavies-st** [comment]
It is roughly
```
points = [4, 5, 6]
lookup_table = [1, 2, 3]
```

**Comment by pllim** [comment]
Well, for 2D, you need to know which axis, right? It gets complicated.
