### ISSUE TITLE
Provide a way to retrieve a conversion function for units without ever initializing Quantity

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9080]
*This came out of a discussion with @yalsayyad at #pyastro19*

As demonstrated in https://github.com/astropy/astropy/issues/8273, unit conversion with small arrays/scalars can be slow. One solution for most unit conversions is to compute a scale and then apply the scale to values:

```python
In [4]: scale = u.cm.to(u.m)                                                                                                                           

In [5]: %timeit 100 * scale                                                                                                                            
54.3 ns ± 1.51 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

instead of:

```python
In [3]: %timeit (100 * u.cm).to(u.m)                                                                                                                   
28.4 µs ± 525 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

However, this doesn't work for more complex unit conversions such as magnitudes to fluxes since these are not simple scalings (as a side note, ``u.ABmag.to(u.Jy)`` actually returns a value when it should probably fail, but I'll open a separate issue for that). So our idea what that instead we could either make it so that one can get a conversion function for units that applies on scalars/arrays and returns scalars/arrays:

```python
In [7]: converter = u.ABmag.to_value_converter(u.Jy)                                                                                                          

In [9]: converter(100)                                                                                                                                 
Out[9]: 3.63078055e-37
```

Alternatively, we could provide a simple function that takes values to convert, units before, and units after:

```python
In [10]: from astropy.units import convert_values                                                                                                      

In [11]: convert_values(100, from=u.ABmag, to=u.Jy)
Out[11]: 3.63078055e-37
```

We could then make sure that these conversions are as optimized as possible and don't result in any ``Quantity`` class being initialized. In general I'm not a fan of having two different APIs to do things, but I think the performance issue comes up so often that I think it would be really worthwhile considering something like this.

@adrn @mhvk - what do you think?

**Comment by mhvk** [comment]
@astrofrog - we can make public (again) `UnitBase._get_converter`, which would give you the desired conversion function. Note, though, that your example is rather unfair: you are not just converting a quantity, but also initializing them. 

It would also be good to consider more realistic use cases; my own sense is that something like #7368 may be a more useful tool.

**Comment by astrofrog** [comment]
> Note, though, that your example is rather unfair: you are not just converting a quantity, but also initializing them.

It is a fair comparison for cases where people just want to go from scalars to scalars - the point here is that in some cases, we should allow users to bypass any quantity initialization since the quantity initialization otherwise dominates the time.

**Comment by astrofrog** [comment]
@mhvk - regarding the use case, this request comes from LSST, and is described here: https://github.com/astropy/astropy/issues/8273 - basically I think they want to replace some code that converts arrays to arrays but don't need the quantity class, but still want to benefit from the conversion.

**Comment by astrofrog** [comment]
As a side note, my understanding of https://github.com/astropy/astropy/issues/7368 is that it still requires initialization of Quantity.

**Comment by parejkoj** [comment]
@astrofrog : your understanding of LSST's use case is exactly correct. Convert values to values, without needing a Quantity at all.

That said, it would be nice to speed up Quantity initialization per #8273, but I didn't get very far when I tried to profile/line_profile things in there.

**Comment by mhvk** [comment]
For just converting, `unit.to(new_unit, value)` does always work.  This does not assume it is just a scaling (if you don't use `value`, you get 1, so get the scale factor out - *if* it is a scaling).

On #7368, the case there is for wanting fast functions that work in known units but take quantity input that has compatible units. This would seem typical for wrapping old code.
