### ISSUE TITLE
LTS and v3.2.x is incompatible with np 1.17 docs

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#9088]
`MaskedColumn.data` docstring, that is inherited from upstream numpy has been changes and now includes a reference to 
>:attr:`baseclass` which is not resolved in our API docs, resulting a broken link: https://39384-2081289-gh.circle-artifacts.com/0/home/circleci/project/docs/_build/html/api/astropy.table.MaskedColumn.html#astropy.table.MaskedColumn.data

This is not an issue in master, but then most of the Masked column handling has changed for 4.0.

So I suggest we just simply limit the numpy version for the docs build for those CIs as a broken API link doesn't pose a threat to the functionality.

**Comment by bsipocz** [comment]
If you're happy with the version limiting workaround, done in the linked PRs, please close this.

**Comment by pllim** [comment]
Yup, I am happy with the PRs.
