### ISSUE TITLE
TableReplaceWarning better message or addition to docs

### ISSUE THREAD

**Issue by nluetzge** [astropy/astropy#9103]
I have a suggestion to the TableReplaceWarning that was implemented in 1.3. It took me a while to figure out how to change my code to make this warning go away. I did find it in the docs eventually but I don't think its clearly marked. I would recommend to either state this in the warning itself (Seomthing like "Try using `t[colname][:] = value` instead") or write the warning in the docs so that it pops up when googling it. I in general have problems finding the right documentation for Tables when I search, but I think this might help in this case.

**Comment by pllim** [comment]
Hard to control what pops up in Google Search, but adding the suggestion to warning message seems reasonable. @nluetzge , are you interested to submit a PR? :smile:

**Comment by nluetzge** [comment]
Sure. We could do both. I don't think it hurts to actually but the name "TableReplaceWarning" into the docs.

**Comment by SiddharthaAnand** [comment]
If no one is working on this, Can I take this up?

**Comment by nluetzge** [comment]
@SiddharthaAnand I put in a PR see above but it has not been merged because things changed in the mean time.
