### ISSUE TITLE
Section/headers level hierarchy mixup (?) in docs (main index in particular)

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#9112]
I noted some oddities in appearance of `index.rst` - the `Developer Documentation` "section" looks somewhat stitched to the end of the `User Documentation` chapter and has no TOC entry. Although it _appears_ to be marked as section according to the Python [devguide](https://devguide.python.org/documenting/#sections) recommendations
> Normally, there are no heading levels assigned to certain characters as the structure is determined from the succession of headings. However, for the Python documentation, here is a suggested convention:
```
# with overline, for parts
* with overline, for chapters
=, for sections
-, for subsections
```
it looks like here the markers are indeed assigned in the order they appear: `# * - =`
i.e. the `====` heading is demoted to level 4 and thus below `:tocdepth: 3`.
I haven't found a way to force the levels to some other order if the first intended `subsection` entry just happens to occur before the first `section`...
Might make more sense here to mark `Developer Documentation` as a chapter, on the same level as `Project details`.

**Comment by pllim** [comment]
Just to be clear. Are you talking about http://docs.astropy.org/en/latest/development/workflow/development_workflow.html ?

**Comment by dhomeier** [comment]
No, here it's actually about the [main index](http://docs.astropy.org/en/latest/index.html). `index.rst` has header entries like
```
******************
User Documentation
******************

Data structures and transformations
-----------------------------------
```
and then
```
=======================
Developer Documentation
=======================
```
so from the devguide examples I would expect the `Developer Documentation` to have a TOC entry at the `section` level, above the `Data structures` one. But Sphinx, I think, classifies the latter as `section` since it encounters it first, and then the former becomes a `subsection` (I can get `Developer Documentation` into the TOC by setting `:tocdepth: 4`, but then it shows up as sub-entry to `Nuts and bolts`).

**Comment by pllim** [comment]
Ah, good catch, @dhomeier ! I agree that "Developer Documentation" should be at the same level as "User Documentation". I think this might be a case of #6057 and #6051 interfering with each other. Do you want to file a PR to fix it? :smile:

**Comment by dhomeier** [comment]
Looks like after #6057 almost everything was marked at the `section` (`===`) instead of `chapter` (`***`) level - so possibly "Developer Documentation" was just left behind at a later point when the rest was promoted to `chapter`.
In that case the fix is trivial.
