### ISSUE TITLE
Add a more helpful error message when pytest-astropy is not installed

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9115]
If I create an environment that has all the normal dev reqs for astropy but does *not* have `pytest-astropy` (or at least its deps), the resulting error message is a rather ambiguous traceback that not very understandable where the problem lies.  (If #9111 is merged it changes that, but to a *different* ambiguous error.)  It would be useful if this was not the case, and running `py.test` instead yielded an error along the lines of "py.test on astropy requires pytest-astropy to be installed".

Note this might belong better in either https://github.com/astropy/pytest-astropy or the package-template... But as part of the "get rid of helpers" goal, I think this might catch some people who would otherwise be tripped up on transitioning to the `py.test` way of invoking tests.

(Prompted by testing of #9111.)

cc @astrofrog @bsipocz @Cadair

**Comment by eteq** [comment]
Oh, and as an example of the precedent I'm thinking about: if you try to build the docs without sphinx-astropy, you get an `ImportError("sphinx-astropy needs to be installed to build the documentation.")`

**Comment by pllim** [comment]
These are declared dependencies (albeit optional) and in the dev docs, we tell people how to install them. No one else complained about this, so I think we can let this one go.
