### ISSUE TITLE
eigvals is not know to astropy Quantity

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#9121]
I'm just following orders. 

This came out during building photutil's  docs (with numpy-dev and astropy-dev). Haven't yet follow-ed up what triggered it exactly:
```
WARNING: function 'eigvals' is not known to astropy's Quantity. Will run it anyway, hoping it will treat ndarray subclasses correctly. Please raise an issue at https://github.com/astropy/astropy/issues.  [astropy.units.quantity]
```

**Comment by mhvk** [comment]
Thanks! Numpy modules like `linalg` are not yet covered (I ran out of steam...). Fixing this is part of #8825.

**Comment by bsipocz** [comment]
oh, fair enough, in that case this is a clear duplicate. Sorry for the noise, should have looked around more carefully 😅
