### ISSUE TITLE
Improve documentaiton on astropy.modeling.Parameter

### ISSUE THREAD

**Issue by nden** [astropy/astropy#9129]
A description of the attributes of a `Parameter`, including constraints.

**Comment by karllark** [comment]
Possible sections of such docs (from PR comment by @perrygreenfield):

Basics
Constraints

**Comment by cdeil** [comment]
Currently there is this heading https://docs.astropy.org/en/latest/modeling/parameters.html#parameter-constraints
But then the rest of the page doesn't mention parameter constraints.

There is some info on parameter constraints here:
https://docs.astropy.org/en/latest/modeling/example-fitting-constraints.html

@nden - Maybe move something around, or just add a link from that one section to the other as a quick fix?

**Comment by nden** [comment]
@cdeil  We were focusing on code changes so far. This week we'll be working on documentation updates for the release.
