### ISSUE TITLE
Constants cannot be pickled

### ISSUE THREAD

**Issue by Juanlu001** [astropy/astropy#9139]
```
$ python
Python 3.7.3 (default, Jun 20 2019, 09:05:27) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> astropy.__version__
'3.2.1'
>>> from astropy.constants import GM_sun
>>> import pickle
>>> pickle.loads(pickle.dumps(GM_sun))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/.pyenv/versions/poliastro37/lib/python3.7/site-packages/astropy/constants/constant.py", line 37, in wrapper
    name_lower = self.name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by Juanlu001** [comment]
It's interesting though that, if the constant is part of another object, everything works fine...

```
>>> class Foo:
...   c = GM_sun
... 
>>> import pickle
>>> f = Foo()
>>> pickle.loads(pickle.dumps(f))
<__main__.Foo object at 0x7fa68cf66b00>
>>> f.c
<<class 'astropy.constants.iau2015.IAU2015'> name='Nominal solar mass parameter' value=1.3271244e+20 uncertainty=0.0 unit='m3 / s2' reference='IAU 2015 Resolution B 3'>
```

(perhaps it's only "interesting" to me because I don't know enough about how pickle works)

**Comment by pllim** [comment]
Can you please try the dev version? `constants` was refactored for 4.0 to better support the different versions of constants (irony?).

**Comment by Juanlu001** [comment]
Sorry, should have tried this before. Same result:

```
Python 3.7.4 (default, Jul 14 2019, 11:11:55) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
WARNING: You appear to be trying to import astropy from within a source checkout without building the extension modules first.  Attempting to (re)build extension modules: [astropy]
Rebuilding extension modules [Done]
>>> astropy.__version__
'4.0.dev25566'
>>> from astropy.constants import GM_sun
>>> import pickle
>>> pickle.loads(pickle.dumps(GM_sun))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/Development/Astropy/astropy/astropy/constants/constant.py", line 36, in wrapper
    name_lower = self.name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by pllim** [comment]
@stargaser , any idea?

**Comment by stargaser** [comment]
All I can say for right now is that #5719 notes that all the pickle tests on constants are set to xfail and that this is something we should investigate. At least that tells us that the inability to pickle constants is not a new thing. I am unsure whether this should be considered a bug or a feature.

**Comment by stargaser** [comment]
Somehow `Quantity.__setstate__` is failing when trying to unpickle the constant. The `.name` property is None when trying to wrap `Quantity.__setstate__`.

Interestingly, making a Quantity out of the unit works:

```
>>> var = 1.0*GM_sun
>>> pickle.loads(pickle.dumps(var))
<Quantity 1.3271244e+20 m3 / s2>
```

**Comment by bsipocz** [comment]
I would suggest to label either this one or the other issue as a duplicate and close. Afaik that investigation hasn't been done yet, and naively it's difficult to see how could the the non-pickeable nature of constants be a feature rather than a bug/missing feature.

**Comment by stargaser** [comment]
I think this is more of a missing feature than a bug. afaik we have not been advertising that constants can be pickled. That is an important distinction, because if we treat this as a missing feature, I would milestone it for v4.0, while as a bug it would be something to try to backport.

Before doing anything -- is everyone okay with closing this one, and milestoning #5719 for v4.0?

**Comment by bsipocz** [comment]
> and milestoning #5719 for v4.0

please only milestone issue if that indeed has a reasonable priority and chance to get done by the release

**Comment by Juanlu001** [comment]
> is everyone okay with closing this one

Sure, I agree with going on with the conversation on the original one
