### ISSUE TITLE
JPL Ephemeris query for Vesta, Ceres, etc.

### ISSUE THREAD

**Issue by shbhuk** [astropy/astropy#9158]
Hi,
I want to use get_body_barycentric_posvel() for querying the ephemeris for Vesta, Ceres, and some other asteroids. 
Do I understand correct, that right now it can only be used for bodies listed by 
`solar_system_ephemeris.bodies`?

**Comment by bsipocz** [comment]
To query ephemeris for arbitrary solar system objects I would suggest to use the `jplhorizons` module in astroquery. There are several examples in the following doc page:

https://astroquery.readthedocs.io/en/latest/jplhorizons/jplhorizons.html

**Comment by shbhuk** [comment]
Which ephemerides file does this default to?

**Comment by pllim** [comment]
Does this answer your question?

https://astropy.readthedocs.io/en/stable/api/astropy.coordinates.solar_system_ephemeris.html#astropy.coordinates.solar_system_ephemeris
