### ISSUE TITLE
AttributeError: 'HorizonsClass' object has no attribute 'uri'

### ISSUE THREAD

**Issue by shbhuk** [astropy/astropy#9164]
This error displays when I run the `Horizons` class within the  `jplhorizons` submodule.

```
from astroquery.jplhorizons import Horizons
obj = Horizons(id='Ceres', location='568', epochs=2458133.33546)
print(obj.uri)
```

OUTPUT:
`AttributeError: 'HorizonsClass' object has no attribute 'uri' `

Astropy Version Number 3.2.1

**Comment by shbhuk** [comment]
Based on - https://astroquery.readthedocs.io/en/latest/jplhorizons/jplhorizons.html

**Comment by pllim** [comment]
Please open this issue over at https://github.com/astropy/astroquery/issues . This repository is only for the `astropy` package. Thank you.

**Comment by pllim** [comment]
p.s. Looks like what you need was added in `astroquery` 0.3.9. Check your `astroquery` version. xref astropy/astroquery#1207
