### ISSUE TITLE
When an NDData is passed to Cutout2D, it should use the wcs

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9173]
The `Cutout2D` class requires the following odd invokation if you want to use sky coordinates for anything with an nddata: ``Cutout2D(image, wcs=image.wcs, ...)``.  That seems like unnecessary repetition. Can't we get away with ``Cutout2D(image, ...)`` if wcs is None, and have it automatically use `wcs` if one is present on the input image?

(I can make a PR for this if it's agreed that it's reasonable, but just want to make sure I didn't miss some obvious reason why it was desirable to *not* do this @mwcraig @crawfordsm )

**Comment by astrofrog** [comment]
I ran into this too. I would actually class this as a bug since we show in the documentation an NDData object being passed to ``Cutout2D``:

http://docs.astropy.org/en/stable/nddata/index.html#image-utilities

so I think users would reasonably expect it to work seamlessly (I certainly did!)

**Comment by mwcraig** [comment]
It seems like decorating with `@support_nddata` ought to be all that is needed....

**Comment by mwcraig** [comment]
Switching the label to bug; should I try to get this in for 4.0? At best 50% chance I get to it today...

**Comment by astrofrog** [comment]
Since we are treating it as a bug, yes we can get it in for 4.0. It would be great if you could indeed open a PR!
