### ISSUE TITLE
DOC: doctest-requires ignored in plot directive

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9174]
In this documentation snippet, it seems to me that the following plot directive should be skipped too if `skimage` is not present, but that is currently not the case.
```rst
.. doctest-requires:: skimage

    >>> from astropy.nddata import block_reduce, block_replicate
    >>> smaller = block_reduce(ccd, 4)
    >>> smaller
    array(...)
    >>> plt.imshow(smaller, origin='lower')  # doctest: +SKIP

.. plot::

    import numpy as np
    import matplotlib.pyplot as plt
    from astropy.modeling.models import Gaussian2D
    from astropy.nddata import block_reduce, block_replicate
    from astropy.nddata import CCDData, Cutout2D
```
Ref: https://github.com/astropy/astropy/blame/master/docs/nddata/index.rst#L337-L351

As a result, I see this traceback in the doc build when I build it without `skimage` installed:
```
.../docs/nddata/index.rst:345: WARNING: Exception occurred in plotting index-4
 from .../docs/nddata/index.rst:
Traceback (most recent call last):
  File ".../matplotlib/sphinxext/plot_directive.py", line 515, in run_code
    exec(code, ns)
  File "<string>", line 20, in <module>
  File ".../astropy/nddata/decorators.py", line 246, in wrapper
    result = func(data, *args, **kwargs)
  File ".../astropy/nddata/utils.py", line 371, in block_reduce
    from skimage.measure import block_reduce
ModuleNotFoundError: No module named 'skimage'
```

**Comment by bsipocz** [comment]
I don't think we can do much about it, there are examples when the same happens with matplotlib (but then of course matplotlib is required for the ``.. plot::`` to make any sense).

In fact scikit-image is listed in docs part of extras-require in `setup.cfg`, so I suggest to close this issue.
