### ISSUE TITLE
pytest-astropy requirement: recommended development workflow does not work

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#9178]
If a user attempts to follow the "How to make a code contribution" at http://docs.astropy.org/en/stable/development/workflow/development_workflow.html#install-your-branch they run into trouble because they haven't installed pytest-astropy. Can it be made a dependency for development? Or installation even?

If I try `python setup.py test` it runs but I get failures in all doctests in rst files. If I try `astropy.test()` it raises an exception and tells me to install `pytest-astropy`. Presumably you-all know that end users can no longer run `astropy.test()` without installing an additional package, but it would be good to let developers know they need it without relying on them using `astropy.test()` rather than `python setup.py test`. Perhaps even have `python setup.py test` also report the need for pytest-astropy?

```
$ pip list
Package       Version     
------------- ------------
astropy       4.0.dev25616
numpy         1.17.1      
pip           19.2.3      
pkg-resources 0.0.0       
setuptools    41.2.0      
wheel         0.33.6      
```

**Comment by aarchiba** [comment]
Correction: `python setup.py test` failures are actually #9179 . It still doesn't raise an exception or tell me to install `pytest-astropy`, and in fact appears to work (that is, run and produce roughly the same set of failures) without the additional package. Sorry for mixing two orthogonal issues. This issue is summarized as:

- `astropy.test()` needs `pytest-astropy` but this is not documented in the contribution guidelines, and
- `python setup.py test` appears to run fine without `pytest-astropy` - is it actually working?

**Comment by dhomeier** [comment]
> * `python setup.py test` appears to run fine without `pytest-astropy` - is it actually working?

Are you sure it is running without `pytest-astropy` and not simply installing it automatically (reporting something like `installing in .eggs/pytest_astropy-0.5.0-py3.7.egg` before the actual test session starts)?
I agree this could be better documented.

**Comment by pllim** [comment]
Instructions on `stable` are outdated. You still have problem with
http://docs.astropy.org/en/latest/development/workflow/development_workflow.html#install-your-branch ?

**Comment by aarchiba** [comment]
> Instructions on `stable` ~are~ might be outdated. You still have problem with
> http://docs.astropy.org/en/latest/development/workflow/development_workflow.html#install-your-branch ?

Yes. I make an empty virtualenv and run `pip install -e .` and all that gets installed is numpy and astropy:
```
Package       Version      Location                                             
------------- ------------ -----------------------------------------------------
astropy       4.0.dev25616 /home/archibald/projects/astropy/install-test/astropy
numpy         1.17.1       
pip           19.2.3       
pkg-resources 0.0.0        
setuptools    41.2.0       
wheel         0.33.6       
```
And then:
```
$ python -c "import astropy; astropy.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/archibald/projects/astropy/install-test/astropy/astropy/tests/runner.py", line 261, in test
    return runner.run_tests(**kwargs)
  File "/home/archibald/projects/astropy/install-test/astropy/astropy/tests/runner.py", line 606, in run_tests
    return super().run_tests(**kwargs)
  File "/home/archibald/projects/astropy/install-test/astropy/astropy/tests/runner.py", line 203, in run_tests
    self._has_test_dependencies()  # pragma: no cover
  File "/home/archibald/projects/astropy/install-test/astropy/astropy/tests/runner.py", line 183, in _has_test_dependencies
    raise RuntimeError(cls._missing_dependancy_error)
RuntimeError: Test dependencies are missing. You should install the 'pytest-astropy' package.
```

**Comment by pllim** [comment]
Hmm, perhaps in the dev instructions, we should just ask people to install all the optional dependencies? 🤔

**Comment by pllim** [comment]
We have since switched to recommending `tox`. Is this still an issue?

**Comment by dhomeier** [comment]
Is `tox` working reliably enough in general then? I had to change the `tox_pypi_filter/plugin.py` where it was trying to do a `sock.bind(('localhost', 0))` to `'127.0.0.1'` since OS X 10.12 throws a
`socket.gaierror: [Errno 8] nodename nor servname provided, or not known`
on the former address.
Also I occasionally get more or less mysterious errors running the suite, but those might be due to my poor network connection.
Maybe people just could use some warning in the test guide that hiccups can occur when `tox` is trying to install all required dependencies on its own, other than that it "can also be the slowest" option.

**Comment by pllim** [comment]
At this point, if the workflow can be improved, a PR is more useful than an issue.
