### ISSUE TITLE
ModuleNotFoundError: No module named 'astropy.extern'

### ISSUE THREAD

**Issue by chris-revell** [astropy/astropy#9200]
My code has suddenly stopped working. The above error is produced in response to `import astropy`. Could this be due to an update or something?

**Comment by pllim** [comment]
`extern` is still there. How did you install `astropy`? What is your OS? Numpy version?

**Comment by chris-revell** [comment]
macOS 10.14.6, Numpy 1.16.2, astropy installed with conda. It's very odd because it was working before today and I'm not sure what changed.

**Comment by MSeifert04** [comment]
Do you have an `astropy.py` file or `astropy` folder inside the current working directory?

**Comment by MSeifert04** [comment]
The full traceback, the astropy version, and the conda channel you used for installing astropy might be important as well (at least if it's not the problem I mentioned in the post above).

**Comment by chris-revell** [comment]
```Traceback (most recent call last):
  File "CharacteriseShape.py", line 9, in <module>
    from astropy import modeling
  File "/usr/local/lib/python3.7/site-packages/astropy/__init__.py", line 125, in <module>
    from . import config as _config
  File "/usr/local/lib/python3.7/site-packages/astropy/config/__init__.py", line 10, in <module>
    from .configuration import *
  File "/usr/local/lib/python3.7/site-packages/astropy/config/configuration.py", line 19, in <module>
    from astropy.extern.configobj import configobj, validate
ModuleNotFoundError: No module named 'astropy.extern'```

**Comment by chris-revell** [comment]
```import astropy; print(astropy.__file__)                                                                                                           
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-49c7882ca2cf> in <module>
----> 1 import astropy; print(astropy.__file__)

/usr/local/lib/python3.7/site-packages/astropy/__init__.py in <module>
    123 
    124 
--> 125 from . import config as _config
    126 
    127 

/usr/local/lib/python3.7/site-packages/astropy/config/__init__.py in <module>
      8 
      9 from .paths import *
---> 10 from .configuration import *
     11 from .affiliated import *

/usr/local/lib/python3.7/site-packages/astropy/config/configuration.py in <module>
     17 from warnings import warn
     18 
---> 19 from astropy.extern.configobj import configobj, validate
     20 from astropy.utils.exceptions import AstropyWarning, AstropyDeprecationWarning
     21 from astropy.utils import find_current_module

ModuleNotFoundError: No module named 'astropy.extern'```

**Comment by MSeifert04** [comment]
Hm, `usr/local/lib` doesn't look like a conda-installation, are you sure you installed astropy via conda?

But the version and/or channel (pip or conda) could be helpful.

**Comment by pllim** [comment]
Try also:
```
conda list astropy
```

**Comment by chris-revell** [comment]
Good point. I may also have a version from pip, but I thought I was using the conda version. 
`conda list astropy` returns the following:
```
# packages in environment at /Users/christopher/anaconda3/envs/shape-env:
#
# Name                    Version                   Build  Channel
astropy                   3.0.4            py35h1de35cc_0
pytest-astropy            0.4.0                    py35_0
```

**Comment by pllim** [comment]
So you installed `astropy` from `conda` into `/Users/christopher/anaconda3/envs/shape-env` but somehow using some other "astropy" from `/usr/local/lib/python3.7/site-packages/`? Something is not right. If you have modified your `PYTHONPATH`, you need to revisit it.

**Comment by chris-revell** [comment]
I certainly have not changed the `PYTHONPATH` since the code was working.

**Comment by chris-revell** [comment]
For what it's worth, I seem to have fixed this now by uninstalling and reinstalling astropy through pip. Somehow the extern directory within that installation had disappeared. However, this was not the installation I thought I was calling, which suggests I need to be more careful with my environment.

**Comment by pllim** [comment]
Great it is working for you now. `conda` keeps changing its behavior on us, it is hard to keep track what is what anymore. :grimacing:
