### ISSUE TITLE
Incomplete loading of IERS B data into IERS_Auto

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#9206]
When new IERS A data is available, the columns dX_2000A_B and dY_2000A_B are not loaded in from the (potentially new) IERS B data that is available, unlike UT1_UTC_B, PM_X_B, and PM_Y_B.

This is demonstrated in PR #9204 .

**Comment by pllim** [comment]
cc @taldcroft and @mhvk

**Comment by bsipocz** [comment]
#9237 has fixed this.
