### ISSUE TITLE
Move flake8 test to circleCI

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#9215]
As they should never be skipped. Maybe add them as the first step in the docs testing job? I suppose that job will be the one run most frequently as the only way to skip it is with `[skip ci]`, while in the current setup the flake8 tests don't run with `[skip travis]` or with `[docs only]`.

(e.g. to avoid failures like the ones in https://github.com/astropy/astropy/pull/9177 that also sneaked into the backport branch).

**Comment by pllim** [comment]
Do you think... maybe this is our gateway to Azure Pipelines? :thinking:

**Comment by mhvk** [comment]
The advantage of the current setup is that if there are PEP 8 issues, travis doesn't run all the remaining tests. Could we keep that by changing how the `[skip ..]` items are interpreted?

More generally, it would be nice if those initial travis tests (or something else) served as a gatekeeper for all the other tests...

**Comment by pllim** [comment]
But... should PEP 8 violation really skip tests? Extra blank line doesn't mean the code won't run. And author can fix just PEP 8 with `[skip travis]` like this.

**Comment by mhvk** [comment]
Agreed, I'd like a situation where PEP8 always runs but possibly nothing else. My only issue with @bsipocz's suggestion is that if we move the PEP8 test out of travis, then all travis tests will run by default even for code where it is already clear another run will be necessary (I'm assuming most people do not remember the `[skip ...]` commands, so am trying to optimize for that case...).

**Comment by bsipocz** [comment]
> But... should PEP 8 violation really skip tests? Extra blank line doesn't mean the code won't run. And author can fix just PEP 8 with [skip travis] like this.

Yes, but then someone needs to step in and clean up anyway, and promoting best practices for the community is not a bad thing to do. 

Otherwise @mhvk you have a good point. Maybe keep it both in travis and in the docs building circleCI? The latter wouldn't take up much CPU time as we would just reuse the VM to run another  command.

**Comment by mhvk** [comment]
Indeed, if we run it together with the docs, it wouldn't be much time. Indeed, I wonder if we could do the same on travis (presumably, after running the tests themselves).

**Comment by bsipocz** [comment]
>  Indeed, I wonder if we could do the same on travis (presumably, after running the tests themselves).

Yes, I suppose we can do that, too, but originally kept is separate so it's super clear why a CI is failing. 
Also, once we have actions we can opt in an app to do the flake8, but then again we can't cancel CI based on the status of that action (as far as I understand actions atm). Actually it would be nice to be able to run actions conditionally.

**Comment by bsipocz** [comment]
(Oh, never mind me, it seems that while I was soaking in cold rain and wind away from the keyboard, we got actions enabled.)
