### ISSUE TITLE
Request: enable random access to compressed FITS arrays

### ISSUE THREAD

**Issue by stsci-hack** [astropy/astropy#9221]
STScI will, in the coming months, start generating new products to be stored in its archive which will be larger than most (all?) current products and, in most cases, will contain a significant fraction of blank pixels.  Storing, accessing, and working with these large (0.1 degrees on a side) products will benefit in many ways from compression.  However, the services for working with these new products will often only need to access portions of each product.  

The current io.fits interface would uncompress the entire image just to access a small portion of it that is being requested.  The CFITSIO library, on the other hand, already supports random access of compressed arrays without uncompressing the entire array up front through use of the Tiled-image Compression interface.  We would like to request that support for this capability of CFITSIO, as described in [Section 5.6 of the CFITSIO Reference Guide](https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node41.html), be integrated into the io.fits access of data arrays as well.

**Comment by MSeifert04** [comment]
Thanks for the issue @stsci-hack - is it possible to access such a file - it doesn't have to contain real data, just something that has the same structure header/extensions/compression-algorithm+parameter and size as the to-be-expected files?

Just to get a rough idea of the dimensions and to confirm that any potential solution would work.

**Comment by saimn** [comment]
This probably requires a significant amount of work. It is mentioned in #3895, which also suggests that "Tile compression should be implemented natively in Python".
