### ISSUE TITLE
CircleCI: HTML Documentation slow because it's uploading thousands of files sequentially

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#9235]
Currently it takes *very long* to upload the artifacts mostly because there are thousands of files to store. CircleCI seems to allow uploading the artifacts as compressed file, that they recommend if one is uploading *hundreds* of files (https://circleci.com/docs/2.0/artifacts/#uploading-artifacts).

Would uploading a compressed file be an option?

**Comment by bsipocz** [comment]
This would be awesome to be fixed. Would you care to do a bit of experimenting with the compressed upload? I suppose the file can be uncompressed at the other end then?

cc @Cadair

**Comment by Cadair** [comment]
If we compress and upload them as one artifact then we wont be able to view the HTML docs in the same way we can at the moment, we could just download the whole tarball.

**Comment by bsipocz** [comment]
I'm super naive this morning: can't we upload as a tarball and untar on the other end?

**Comment by Cadair** [comment]
From a quick read of their docs, that does not seem to be something they suggest is possible.

**Comment by pllim** [comment]
This will be a non-issue once RTD approves the core for their new "PR build" feature. :smile:

**Comment by pllim** [comment]
We no longer use CircleCI to build docs.
