### ISSUE TITLE
TST: Tests failures in coordinates caused by IndexError in IERS with numpy-dev

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9240]
A blame on the LOC pointed to #9226 though the PR itself was green. :woman_shrugging: 

@mhvk , any idea?

Example log: https://travis-ci.org/astropy/astropy/jobs/585668145

**UPDATE**

Looks like numpy-dev job did pass in https://travis-ci.org/astropy/astropy/builds/585637569 ("about 2 hours ago" at the time of writing this with `numpy 1.18.0.dev0+07a7eb5`) but failed in https://travis-ci.org/astropy/astropy/jobs/585641053 (also "about 2 hours ago" with `1.18.0.dev0+07a7eb5`). The PR merged seems unrelated to IERS nor coordinates. And no changes were merged into numpy-dev since 8 hours ago. Then, more tests failed on our end in the next run (https://travis-ci.org/astropy/astropy/jobs/585668145). Did IERS data server change something?

**Comment by pllim** [comment]
I restarted https://travis-ci.org/astropy/astropy/jobs/585668145 to see if it was transient server problem. I cannot reproduce the failures locally.

**Comment by mhvk** [comment]
It repeated so does look like a real bug. Strange that it only turns up in doctests!

**Comment by mhvk** [comment]
I also cannot seem to reproduce either (tried both latest numpy-dev (1.18.0.dev0+6e75b9a) and the one used by travis (1.18.0.dev0+07a7eb5)...

**Comment by pllim** [comment]
Hang on... I am going to try clear Travis CI cache and rerun it again... :crossed_fingers:

**Comment by pllim** [comment]
Looks like some sort of corrupted cache. It is green now. Sorry for the noise!

**Comment by mhvk** [comment]
Fortunately, I had started on something else... But while testing that, I found a similar issues, which resulted from the IERS-A table not downloading completely. I think we do need to circumvent that by having a cached version or so...

**Comment by pllim** [comment]
@mhvk , Travis CI is already doing some caching. But if you are talking about the other IERS issues, then I don't have anything useful to contribute. LoL...

**Comment by mhvk** [comment]
Ah, that means it might have been the same problem: for me, it seems the `finals2000A` file was downloaded only partially and it was quite hard to remove it and retry. Maybe something similar happened for travis. In any case, that would seem part of #9182 - so, for once no need to raise a new issue!

**Comment by pllim** [comment]
Yes, I do suspect that Travis CI cached a corrupted IERS table.
