### ISSUE TITLE
DOC: Remove convert issue to PR section

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9243]
As suggested by @bsipocz over at https://github.com/astropy/astropy/pull/9175#discussion_r324767546 .

*I think converting issues to PRs is not a thing we should encourage (and indeed we hardly ever do it), so I suppose this part can be removed altogether.*

**Comment by mhvk** [comment]
I used to quite like it, but can definitely see the point that it is bad practice. Also, at least my version of the script has long stopped working. So, :+1: to removing it.

**Comment by bsipocz** [comment]
> I used to quite like it, but can definitely see the point that it is bad practice. Also, at least my version of the script has long stopped working. So, 👍 to removing it.

it can only be done by people with commit rights, so I don't think it's fair to promote something that then cannot be done by contributors (as well as github context (in cross references, etc) can be rather confusing when something was an issue and now suddenly it becomes a PR). So while I like the feature in smaller repos, would be in favour of not encouraging the practice in astropy core.

**Comment by pllim** [comment]
@mhvk , the script not working should be an issue over at `astropy-procedures`. FYI.
