### ISSUE TITLE
Document or remove 'single' method for LS FAP

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#9247]
It's not exactly clear whether the 'single' method is meant to be a public functionality, as it's not documented at all (https://github.com/astropy/astropy/blob/master/astropy/timeseries/periodograms/lombscargle/_statistics.py#L379)
I would suggest to either include it in the doc/docstrings or make it more internal, private helper functionality.

What do you think @jakevdp?

**Comment by jakevdp** [comment]
I think it's useful to have available in the public API, because people might want to use it as part of their calculations. But I didn't document it because it's generally the wrong thing to use unless you know exactly what you're doing (in which case I hope the docstring is sufficient).
