### ISSUE TITLE
Allow an array (instead of singular) of obstimes for a SkyCoord object

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#9256]
Currently `SkyCoord` only allows a single `obstime` to be specified per object. Whilst I understand this from an observing point of view, I would like to represent the trajectory of a spacecraft as a function of time using the astropy coordinate framework. This requires that each individual coordinate within the object should have an individual `obstime` associated with it.

**Comment by pllim** [comment]
cc @Juanlu001

**Comment by dstansby** [comment]
Ach, seems like this is a `sunpy` issue that I thought was an astropy one - the following works fine:
```python
from astropy.coordinates import SkyCoord  # High-level coordinates
from astropy.coordinates import ICRS, Galactic, FK4, FK5  # Low-level frames
from astropy.coordinates import Angle, Latitude, Longitude  # Angles
import astropy.units as u

coords = ["1:12:43.2 +1:12:43", "1 12 43.2 +1 12 43"]
obstimes = ['J1992.21', 'J1993.21']
c = SkyCoord(coords, frame=FK4, unit=(u.deg, u.hourangle), obstime=obstimes)
print(c.obstime)
```
I think at least the docs should be updated to imply that multiple obstimes are in theory possible: http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html I'm happy to give this a go.

**Comment by pllim** [comment]
@dstansby , if you have ideas on how to improve the docs, feel free to submit a PR. Thanks!

**Comment by ayshih** [comment]
@dstansby Can you create an issue for SunPy with the issue you're encountering?  I routinely check and test to make sure that array obstimes are supported, but I certainly could have missed something.

**Comment by dstansby** [comment]
It turns out there was never a problem, but pytest was erroring when a warning was thrown (so I should have done more checks before opening the issue!). I've made a small PR to improve the docs.
