### ISSUE TITLE
Inconsistent units when evaluating quantities with powers and then inverting

### ISSUE THREAD

**Issue by watsonjj** [astropy/astropy#9258]
macOS Mojave 10.14.5, python 3.7.2, astropy 3.2.1, numpy 1.16.3.

When applying a power to a quantity and then inverting that power, I get inconsistent results depending on the power index:

```python
In [2]: from astropy import units as u

In [3]: (1 * u.TeV ** -1.2) ** (1/-1.2)
Out[3]: <Quantity 1. TeV>

In [4]: (1 * u.TeV ** -2.2) ** (1/-2.2)
Out[4]: <Quantity 1. TeV(90071992547409917/90071992547409920)>

In [5]: (1 * u.TeV ** np.pi) ** (1/np.pi)
Out[5]: <Quantity 1. TeV>
```

Is there some way to ensure a consistent unit without first changing the value to a scalar, and then reattaching the units afterwards? Or some way to evaluate the exponent`<Quantity 1. TeV(90071992547409917/90071992547409920)>` to some significant number of figures?

**Comment by mhvk** [comment]
Thanks for reporting. In principle, we have a function [`is_effectively_unity`](https://github.com/astropy/astropy/blob/master/astropy/units/utils.py#L163), which should address this. Oddly,
```
from astropy.units.utils import is_effectively_unity
q = (1 * u.TeV ** -2.2) ** (1/-2.2)
q.unit
# Unit("TeV(90071992547409917/90071992547409920)")
is_effectively_unity(q.unit.scale)
# True
```
so it seems the function did not get called or used. Seems like a bug!

**Comment by mhvk** [comment]
#9267 is an attempt to fix this.
