### ISSUE TITLE
Code warnings during docs build

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#9268]
While building documentation, I get the warnings below, at least some of which suggest documentation is out of date. Generally, I don't think any code we include should generate warnings, so it would be good to fix this. More generally, perhaps we should start failing on any warning from the docs build?

```
/usr/lib/python3/dist-packages/numpy/lib/function_base.py:3405: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
WARNING: Input data contains invalid values (NaNs or infs), which were automatically clipped. [astropy.stats.sigma_clipping]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically clipped. [astropy.stats.sigma_clipping]
/data/mhvk/packages/astropy/build/lib.linux-x86_64-3.7/astropy/timeseries/downsample.py:28: RuntimeWarning: Mean of empty slice
  result.append(function(array[indices[i]:indices[i+1]]))
/data/mhvk/packages/astropy/build/lib.linux-x86_64-3.7/astropy/timeseries/downsample.py:29: RuntimeWarning: Mean of empty slice
  result.append(function(array[indices[-1]:]))
WARNING: ErfaWarning: ERFA function "utctai" yielded 1 of "dubious year (Note 3)" [astropy._erfa.core]
/usr/lib/python3/dist-packages/matplotlib/figure.py:98: MatplotlibDeprecationWarning: 
Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  "Adding an axes using the same arguments as a previous axes "
WARNING: AstropyDeprecationWarning: Importing LombScargle from astropy.stats has been deprecated and will no longer be supported in future. Please import this class from the astropy.timeseries module instead [astropy.stats.lombscargle]
WARNING: AstropyDeprecationWarning: Importing BoxLeastSquares from astropy.stats has been deprecated and will no longer be supported in future. Please import this class from the astropy.timeseries module instead [astropy.stats.bls]
```

**Comment by pllim** [comment]
If these are generated by the same examples that get doctest-ed, they would eventually be solved as part of efforts for #7928 . They annoy me too but never high priority enough for me to track down.

**Comment by MSeifert04** [comment]
I think the deprecation warning from matplotlib should be taken seriously.

**Comment by pllim** [comment]
Re: matplotlib --- "Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance." -- Probably not that criticial? :woman_shrugging:  I think it is in `visualization.wcsaxes` somewhere.

**Comment by mhvk** [comment]
The warnings about `LombScargle` suggests the examples import it from the old, deprecated location - that seems rather silly too, though probably just an oversight by @astrofrog (in #8591)

**Comment by bsipocz** [comment]
That periodogram warning might coming from a what's new site, I'll try to track it down.

**Comment by bsipocz** [comment]
A more serious comment: recently we started to include plots on the what's new side, but rather than as an image they are rendered during docs build. Now, if there is any API changes along the road they will stop working, e.g. as they do now. We can keep patching them, but then those won't work with the version the what's new page is about.

What shall we do? Render the plots, or update the source code for the plots?

**Comment by pllim** [comment]
Hmm... I prefer updating a code with a note that says code has been updated or something like that. I don't see the point of showing dead code for historical reasons.

**Comment by mhvk** [comment]
Agreed with @pllim: quite important that any code shown works.

**Comment by bsipocz** [comment]
Well, we don't doctest any of the code examples in the what's news 🤷‍♀

**Comment by bsipocz** [comment]
(And indeed all but one what's new are failing. Should we fix all of them?)

**Comment by mhvk** [comment]
Ouch. Yes, I think we should fix them! How many are there? Perhaps best for now just make it a new issue?

**Comment by bsipocz** [comment]
8 files. It's a trivial job once there is a decision.

E.g. I'm still not sure it's the right thing to do. E.g, this is now, but the output was valid when it was released (e.g. these pages are pretty difficult to dig up from the current docs, while have been linked in announcements etc)

```
114     >>> from astropy import constants as const
115     >>> with const.set_enabled_constants('astropyconst13'):
116     ...     print(const.h)
117       Name   = Planck constant
118       Value  = 6.62606957e-34
119       Uncertainty  = 2.9e-41
120       Unit  = J s
121       Reference = CODATA 2010
122     >>> print(const.h)
Differences (unified diff with -expected +actual):
    @@ -1,5 +1,5 @@
       Name   = Planck constant
    -  Value  = 6.62607004e-34
    -  Uncertainty  = 8.1e-42
    +  Value  = 6.62607015e-34
    +  Uncertainty  = 0.0
       Unit  = J s
    -  Reference = CODATA 2014
    +  Reference = CODATA 2018
```

**Comment by mhvk** [comment]
Hmm, that example indeed shows the risk of just pasting in new text; in this particular case, a `# doctest: +SKIP` seems reasonable...

**Comment by bsipocz** [comment]
Yes, but most of them are in this category (or e.g. the usual numpy repr changes, but then, the latest numpy version when  those were released was older).

E.g. importing the periodograms from stats is totally legit imo in a docs that details that they have been just added to astropy.stats.

**Comment by mhvk** [comment]
Hmm, maybe the conclusion then is that we should continue not to doctest what's new, but also ensure we avoid/silence sphinx warnings? The problem with letting won't-fix warnings through is that they start to obscure the real warnings.

Alternatively, should we just *remove* what's new for older versions? They are, after all, inside the docs of those older versions...

**Comment by bsipocz** [comment]
My preference is still to leave them as is (with `doctest-skip-all`), and change the plots to be a png ones rather than generated on the fly. 
But as I said before, if there is a clear preference I'm happy to follow-through with it and update the files accordingly.

**Comment by mhvk** [comment]
I think your examples suggest that it is better to leave things as they are - which means making `.png`s. Since we don't link to the old what's new pages (or at least not obviously so), the risk of outdated code being copy-pasted seems quite small.

**Comment by pllim** [comment]
@mhvk , with #9271 merged, is this now resolved?

**Comment by mhvk** [comment]
Definitely, some have disappeared, but:
```
/usr/lib/python3/dist-packages/numpy/lib/function_base.py:3405: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
WARNING: Input data contains invalid values (NaNs or infs), which were automatically clipped. [astropy.stats.sigma_clipping]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically clipped. [astropy.stats.sigma_clipping]
...
/data/mhvk/packages/astropy/docs/index.rst:101: WARNING: toctree contains reference to nonexisting document 'visualization/index'
/data/mhvk/packages/astropy/docs/stats/index.rst:77: WARNING: toctree contains reference to nonexisting document 'visualization/histogram'

../CHANGES.rst:5875: WARNING: undefined label: plotting-quantities (if the link has no caption the label must precede a section header)
/data/mhvk/packages/astropy/docs/development/testguide.rst:745: WARNING: undefined label: wcsaxes (if the link has no caption the label must precede a section header)
/data/mhvk/packages/astropy/docs/install.rst:61: WARNING: py:obj reference target not found: astropy.visualization
/data/mhvk/packages/astropy/docs/io/fits/index.rst:876: WARNING: undefined label: fits2bitmap (if the link has no caption the label must precede a section header)
/data/mhvk/packages/astropy/docs/stats/index.rst:135: WARNING: py:func reference target not found: astropy.visualization.hist
/data/mhvk/packages/astropy/docs/stats/index.rst:132: WARNING: py:func reference target not found: astropy.visualization.hist
/data/mhvk/packages/astropy/docs/stats/index.rst:132: WARNING: undefined label: astropy-visualization-hist (if the link has no caption the label must precede a section header)
/data/mhvk/packages/astropy/docs/units/quantity.rst:119: WARNING: undefined label: plotting-quantities (if the link has no caption the label must precede a section header)
/data/mhvk/packages/astropy/docs/wcs/index.rst:233: WARNING: undefined label: wcsaxes (if the link has no caption the label must precede a section header)
/data/mhvk/packages/astropy/docs/wcs/index.rst:233: WARNING: undefined label: wcsaxes (if the link has no caption the label must precede a section header)
```

**Comment by pllim** [comment]
Ugh... Maybe it is time to trim the change log too. It takes so much time to render as it is...

**Comment by mhvk** [comment]
Closing since I've not seen extraneous warnings for a while.
