### ISSUE TITLE
Potential trap with the accuracy of velocity correction

### ISSUE THREAD

**Issue by VoronkovMA** [astropy/astropy#9269]
Hello!

I came across this issue in my science work where I tried to use the Doppler correction model implemented in astropy (radial_velocity_correction method of SkyCoord class) instead of a build-in model in an unrelated software for radio-interferometry data reduction in order to improve the accuracy of measured radial velocities. I believe the current description of the radial_velocity_correction method may be misleading and can result (well, in fact resulted in my project) in an error well above the claimed 1 mm/s accuracy (assuming correct application procedure is followed to account for multiplicative nature of the correction).  Here is the description of what I think is going on:

1. Wright & Eastman (2014) treatment of the barycentric correction is expressed in terms of the redshift, rather than the radial velocity returned by the method in question (this is kind of makes sense as some corrections, e.g. gravitational, are not strictly speaking the velocity effects).
2. The radial_velocity_correction method returns z_b * c, which is only the first order approximation. One has to use c * ((z_b+1)^2 - 1) / ((z_b+1)^2 + 1) to avoid making an approximation and get true velocity. Failure to do so introduces a sine wave residual with half a year period and amplitude up to 0.75 m/s (i.e. a quadratic term). 
3. The application formula given in the example in the method description, 
rv = rv + vcorr + rv * vcorr / consts.c, is strictly speaking valid only in the first order approximation v = z * c (e.g. compare with equation (11) of Wright & Eastman). Otherwise, one has to deal with redshifts directly (as per eq. 11 of Wright & Eastman) and then use the full relativistic formula shown above to get the final velocity. My reading of Wright & Eastman paper is that they used z * c formula for simplicity when considered residual terms or physical sense, although it wasn't articulated very clearly.

So, the issue is related to definitions and is not necessarily a bug as such. Although personally I'd prefer no implicit approximations at the library level (e.g. the method returning z_b itself or the velocity calculated using full relativistic formula), I see that the current interface may have some advantages for other users. In addition, changing the output now would potentially introduce bugs. Perhaps, it is better to just add a comment/warning to the help of the radial_velocity_correction method and state clearly that it returns z_b of Wright & Eastman (2014) multiplied by the speed of light.

Cheers,
              Max

**Comment by pllim** [comment]
@VoronkovMA , we apologize for any inconvenience caused in the confusion. Would you be interested in submitting a pull request to adjust the documentation as you suggested above?

ref: https://docs.astropy.org/en/latest/development/workflow/development_workflow.html

**Comment by mhvk** [comment]
cc also @StuartLittlefair, who added much of this code in #6861. One comment: I'm a bit confused about your third point, the idea of giving this extra equation was that it "undoes" the first-order approximation made.  As you write, we return `vcorr=c * zcorr`, and presuming that one similarly has `rv = c* zmeas`, then the equation given is consistent with eq. 10 of Wright & Eastman.

Of course, this confusion itself is a reason to clarify the documentation!

p.s. I am actually curious if we get consistent result if we use the coordinate transformation machinery, i.e., go from the relevant `AltAz` or `GCRS` including radial velocity to a `IRCS`.

**Comment by VoronkovMA** [comment]
I can give it a try updating the documentation myself (when this discussion is settled).

On my third point in the ticket description after some further thought. There is no problem with rv = rv + vcorr + rv * vcorr / consts.c equation as long as all velocities have the same z*c definition (which is also called the optical velocity approximation; it is also possible that this approximation was used without further clarification at various places of Wright & Eastman because the paper was largely intended for the optical community). This application formula is not intended to undo the effects of the approximation, i.e. the resulting rv would also be the optical velocity. The problems appear when the resulting velocities are passed to another software which expects a different definition. In radio astronomy it is common to work with the radio velocity approximation v=c*z/(z+1) which gives the spectral channels equally spaced in frequency rather than the wavelength, or with full relativistic velocity without any approximation. In my particular problem, the data reduction software assumed the full relativistic velocity - I rechecked the formulas to ensure it applies barycentric correction using the right equations and these turned out to be  right for the full relativistic velocity as the input. Somehow I thought that astropy's method gives that (as it was validated against TEMPO2 and pulsar work was unlikely to work with optical velocity). Anyway, mentioning optical velocity approximation v = z* c in the documentation is all that is needed. 

I didn't use the conversion from AltAz explicitly - in my application the input is in equatorial coordinates. However, it must be used somewhere behind the scene to get contributions of  the diurnal rotation right. And I can confirm that it wasn't too far off - I can clearly see the residual in my data if I shift the observatory position by 10-20 km from the actual position.

**Comment by mhvk** [comment]
@VoronkovMA - I think you are right, that use of the optical velocity approximation is implicit. It would be good to mention both this, and the fully relativistic way to handle this. The different frames are also in what probably is an unexpected place, http://docs.astropy.org/en/latest/units/equivalencies.html#spectral-doppler-equivalencies - for now, it might still make sense to refer to that.
