### ISSUE TITLE
Inaccurate coordinates from SkyCoord.from_name('HD....')

### ISSUE THREAD

**Issue by pmaxted** [astropy/astropy#9272]
Coordinates returned by SkyCoord.from_name for HD identifiers are almost  1 arcminute from the actual position, e.g., HD97658 = HIP 54906
```python
>>> c_from_hd = SkyCoord.from_name('HD97658')
>>> c_from_hd.to_string(style='hmsdms')
'11h14m32.976s +25d43m19.56s'
>>> c_from_simbad = SkyCoord('11 14 33.161', '+25 42 37.39', unit='hour,degree')
>>> c_from_hd.separation(c_from_simbad).to_string()
'0d00m42.244s'
>>> c_from_hip = SkyCoord.from_name('HIP 54906')
>>> c_from_hip.to_string(style='hmsdms')
'11h14m33.1619s +25d42m37.3902s'
>>> c_from_hd.separation(c_from_hip).to_string()
'0d00m42.2446s'
>>> c_from_hip.separation(c_from_simbad).to_string()
'0d00m00.012s'
```

EDIT: Code formatting

**Comment by mhvk** [comment]
Strange, it seems the coordinates are not gotten from the right database. Inside `name_resolve.py`, the URL requested is `http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/A?HD97658`, which returns the response below. Possibly, we should not just ask for `all` databases?
```
# HD97658	#Q34074740
#=Vl=VizieR (local):    1     0ms (from cache)
%J 168.6374 +25.7221 = 11:14:33.0  +25:43:20  
%I.0 {HD} 97658


#=Su=Simbad (via url):    1     0ms (from cache)
%@ 1784736
%I.0 HD 97658
%C.0 PM*
%C.N0 14.07.00.00
%J 168.63817223451960 +25.71038664224055 = 11:14:33.16 +25:42:37.3
%J.E [0.0470 0.0449 90] A 2018yCat.1345....0G
%P -107.534 48.662 [0.091 0.090 90] A 2018yCat.1345....0G
%X 46.3494 [0.0541] A 2018yCat.1345....0G
%V v -1.39 ~ [0.35] A 2018yCat.1345....0G
%S K1V =0.0001FE00.0030.0000000000000000 C 2010MNRAS.403.1949K
%#B 117



#====Done (2019-Sep-21,22:19:44z)====
```

**Comment by mhvk** [comment]
Indeed, if I set the database to simbad, it does work:
```
from astropy.coordinates.name_resolve import sesame_database
sesame_database.set('simbad')
SkyCoord.from_name('HD97658')
# <SkyCoord (ICRS): (ra, dec) in deg
#   (168.63817223, 25.71038664)>
```

**Comment by pllim** [comment]
cc @eteq or @adrn

**Comment by tboch** [comment]
It seems the issue is due to very inaccurate positions of Draper catalogue, used by the VizieR resolver. I'll forward this to my CDS colleagues.

**Comment by tboch** [comment]
I have more information to share:
when querying Sesame asking for all resolvers (`A` flag), you can have indeed have multiple resolvers giving a coordinate. In such a case, it is advised to give priority to Simbad coordinates (the section starting with `#=S`) if it is present.
We can provide with a PR if that helps.
cc @bmatthieu3

**Comment by mhvk** [comment]
@tboch - thanks so much for the further information. If you could provide a PR, that would be great!
