### ISSUE TITLE
"per square arcsecond" units render wrong in latex/notebook

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9284]
This bug appears most clearly in the following clip from a Jupyter notebook:

![image](https://user-images.githubusercontent.com/346587/65572200-51ca8b80-df35-11e9-8e37-df8e60261fa6.png)

And the underlying cause is apparent from looking at what the latex being rendered is:
```
>>> (u.arcsec**-1)._repr_latex_()
'$\\mathrm{\\frac{1}{{}^{\\prime\\prime}}}$'
>>> (u.arcsec**-2)._repr_latex_()
'$\\mathrm{\\frac{1}{{}^{\\prime\\prime}^{2}}}$'
```
The problem is that arcseconds are rendered as nothing to a power, so when you put *that* to a power, things go wrong.

The question is: what is the *right* answer?  should it render as the arcsecond symbol with a 2 next to it?  Or do we think it's wrong that the symbol is in superscript in the first place? (I.e., instead of ``{}^{\\prime\\prime}`` it could be ``{\\prime\\prime}``...)

(This may seem obscure, but actually it comes up surprisingly often when working with surface brightnesses, since they are traditionally something-per-square-arcsec)

**Comment by mhvk** [comment]
@eteq - I *think* we fixed this in #9218 - could you try on current master? (it should just become "arcsec")

**Comment by pllim** [comment]
In 4.0.dev25735, I get this:
```python
>>> (u.arcsec**-1)._repr_latex_()                                           
'$\\mathrm{\\frac{1}{{}^{\\prime\\prime}}}$'
>>> (u.arcsec**-2)._repr_latex_()                                           
'$\\mathrm{\\frac{1}{arcsec^{2}}}$'
```

**Comment by mhvk** [comment]
I guess the question here is whether we should catch `1/"` as well - looking back at #9218, I see that we discussed it but decided to punt on it, for now only removing double superscripts.

**Comment by mhvk** [comment]
@eteq - what do you think about it, `1/''` or `1/arcsec`?
