### ISSUE TITLE
Include Rankine in imperial units and equivalencies

### ISSUE THREAD

**Issue by simpsonchristo** [astropy/astropy#9286]
This is a feature request for the addition of Rankine to temperature units. It is more useful than Fahrenheit in some cases because it is an absolute scale. The conversion between deg_F and degrees Rankine is adding 459.67.  See: [Rankine Scale](https://en.wikipedia.org/wiki/Rankine_scale)

Proposed change in equivalencies (assuming deg_R is Rankine):
```python
def temperature():
    """Convert between Kelvin, Celsius, and Fahrenheit here because
    Unit and CompositeUnit cannot do addition or subtraction properly.
    """
    from .imperial import deg_F
    return Equivalency([
        (si.K, si.deg_C, lambda x: x - 273.15, lambda x: x + 273.15),
        (si.deg_C, deg_F, lambda x: x * 1.8 + 32.0, lambda x: (x - 32.0) / 1.8),
        (si.K, deg_F, lambda x: (x - 273.15) * 1.8 + 32.0,
         lambda x: ((x - 32.0) / 1.8) + 273.15),
        (deg_R, deg_F, lambda x: x + 459.67, lambda x: x + 459.67),
        (deg_R, si.deg_C, lambda x: (x * 1.8) + 491.67, lambda x: ((x-491.67)/1.8),
        (deg_R, si.K, lambda x: x, lambda x: x)], "temperature")
```

**Comment by mhvk** [comment]
@simpsonchristo - I think it would indeed not be difficult to add, but will there really be anyone using it?

**Comment by simpsonchristo** [comment]
Rankine is still used in some atmospheric standards (see US MIL-STD-210A). I can't speak to others but in my use case, comparing atmospheric values, it would make life easier. I made a "work-around" of defining it as new unit from Kelvin. I just had to be careful about not using Celsius or Fahrenheit for anything.

**Comment by mhvk** [comment]
OK, if it is still used, I don't see a reason not to support it. Would you be willing to give it a try? It should be fairly straightforward - what you suggested on top should do most of the trick.

**Comment by simpsonchristo** [comment]
Yeah, I'd love to give it a try! It's on my to-do list for next week. @mhvk

**Comment by DShivansh** [comment]
@mhvk can I work on this feature request?

**Comment by mhvk** [comment]
@DShivansh - sure!
