### ISSUE TITLE
Cache uses insecure hash MD5

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#9303]
The files in the download cache are de-duplicated using the cryptographic hash MD5. Unfortunately this hash function is so broken collisions can be constructed for less than a dollar of compute time ( https://natmchugh.blogspot.com/2015/02/create-your-own-md5-collisions.html ). Since many of astropy's downloaded files come from non-SSL connections, a malevolent entity could substitute a wrong object with a matching hash. It's not a crucial security vulnerability, but it is an attack surface.

Switching hash functions poses no difficulty if the new hash function has a different length hash, and almost none if the lengths are the same; the only thing lost is deduplication between objects stored with different hash functions. Existing file names are stored in the index, so changing hash functions does not impact their accessibility. So I suggest making the name of the hash function a configuration variable; the default value can be discussed, but this lets users choose a secure one or a compatible one as their caution dictates.

**Comment by MSeifert04** [comment]
Interesting because lots of services where you can download executables still provide the md5 sum to checksum the file. (Even CPython does that https://www.python.org/downloads/release/python-374/ and also conda-forge: https://github.com/conda-forge/staged-recipes#2-how-do-i-populate-the-hash-field).

In our case we're not downloading executables (are we?) and we're not verifying the integrity using that hash (just deduplication) so there's essentially no risk. MD5 is just considered broken as cryptographic hash, it's still a valid choice for checksums and such like.

On the other hand I wouldn't mind switching the hash-function - if easily possible. I guess that would be SHA256, right?

**Comment by aarchiba** [comment]
Yes, the risk for us is very slight. In the absence of malevolent file contents the chance of a collision remains minuscule. I mention this chiefly because the cost of changing is also very slight. I'd go with SHA256, but really, the hash function constructor in hashlib just takes a string name, so adding this name as a config option is very simple. (And hash functions seem to get broken at a disturbing rate.)

**Comment by pllim** [comment]
Just curious, why not SHA512?

**Comment by pllim** [comment]
@aarchiba , making things more secure doesn't hurt! Do you plan to attach this to your existing PR over at #9182 or do you plan to do this as a standalone PR later?

**Comment by aarchiba** [comment]
It's a few-line change, I'm happy doing either, but as it's not urgent it's probably easiest to just put it into #9182 . I started with an issue because I wasn't sure how people would feel about such a low-grade security issue.

**Comment by aarchiba** [comment]
The length of the hash increases the length of the file names and the size of the cache index, but really, only very slightly. The time to compute any of these hashes shortly can't compare to the time to download the corresponding file, and that's basically the only time the hash is computed.

**Comment by MSeifert04** [comment]
> low-grade security issue.

Again, this isn't about security at-all. If someone intercepts the traffic (which seems to be the threat) then it makes no difference which algorithm is used to calculate the checksum to determine if the file was already downloaded.

Using another checksum (or making it configurable) for the duplication-checking is simply a new feature.

However after thinking about it some more: I don't see much point in adding it and even less for making it configurable. If we can change it internally and keep backwards-compatibility then it might be an option but it probably shouldn't be exposed to users.

**Comment by aarchiba** [comment]
Quietly changing the hash function causes no problems; I found longer hashes made for (even more) cumbersome file names, so SHA224 is probably a good choice. It could be made "internally configurable", that is, set in a private variable in astropy/utils/data.py, so that future changes would be source code changes but easy ones. 

(If we don't care about deduplication we could just replace hashes with strings from os.urandom or uuids or just increasing numbers; the function of using hashes and an index at all is to avoid worry about encoding URLs into filenames - they can be quoted but could become too long for the OS.) 

The most probable "attack" I can see is someone (on public Wi-Fi say) spoofing an unencrypted DNS request and responding to the unencrypted HTTP request with a bogus file that has the same hash as the real one. Later requests to the real server for the real file won't overwrite the existing bogus one because they have the same hash, until such time as the real server changes the contents. Making the hash collision-resistant doesn't stop the initial bogus data injection (HTTPS would) but it does mean the file will be replaced the next time the server is checked for updates, without the user needing to notice and use clear_download_cache. Not much of a threat, really, I know. But the point of using a cryptographic hash rather than something like python's builtin hash is to not have to think about what happens if there is a collision.

**Comment by MSeifert04** [comment]
In case we don't want the deduplication there's the [`uuid`](https://docs.python.org/3/library/uuid.html) module.

Regarding the collisions: I think it's pointless to change anything here. There's no real motivation for sending corrupted files with the same hash (because they are generally not executed) and the probability for accidental collisions is virtually non-existent. There's probably no harm in changing the internal algorithm but I also don't see any benefit. I'll let someone else decide.

**Comment by pllim** [comment]
I wonder if this has to wait till v5.0. Or maybe we can ship it in v4.1 but not make it default until v5.0. :thinking:

**Comment by aarchiba** [comment]
The code to make it happen and test it would take me maybe twenty minutes to pull out of my git history. I let this go because there was opposition to fixing this, and it didn't seem too important. It still bothers me but it's probably appropriate to close the bug report.

**Comment by pllim** [comment]
Okay, I am tagging this for the bot to auto-close after a while then. But feel free to let me know if you change your mind. Thanks!
