### ISSUE TITLE
Initializing an EarthLocation now causes a TypeError about casting

### ISSUE THREAD

**Issue by paulray** [astropy/astropy#9306]
### Description

After updating numpy and astropy, I get a TypeError when initializing an EarthLocation object.

### Expected behavior

This previously worked just fine.

### Actual behavior

TypeError raised.

### Steps to Reproduce

```ipython
Python 3.6.9 (default, Sep  7 2019, 20:24:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [3]: import astropy.coordinates                                                                                                                                                             

In [4]: import astropy.units as u                                                                                                                                                              

In [5]: astropy.coordinates.EarthLocation.from_geocentric(23.0,55.0,-10.0,unit=u.m)                                                                                                            
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-502c18d74f82> in <module>
----> 1 astropy.coordinates.EarthLocation.from_geocentric(23.0,55.0,-10.0,unit=u.m)

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/coordinates/earth.py in from_geocentric(cls, x, y, z, unit)
    251         struc = np.empty(x.shape, cls._location_dtype)
    252         struc['x'], struc['y'], struc['z'] = x, y, z
--> 253         return super().__new__(cls, struc, unit, copy=False)
    254 
    255     @classmethod

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/units/quantity.py in __new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    377         if dtype is None and (not np.can_cast(np.float32, value.dtype)
    378                               or value.dtype.kind == 'O'):
--> 379             value = value.astype(float)
    380 
    381         value = value.view(cls)

TypeError: Cannot cast array from dtype([('x', '<f8'), ('y', '<f8'), ('z', '<f8')]) to dtype('float64') according to the rule 'unsafe'

```

### System Details

Versions:

Darwin-15.6.0-x86_64-i386-64bit
Python 3.6.9 (default, Sep  7 2019, 20:24:16) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
Numpy 1.17.2
Scipy 1.3.1
astropy 3.1

**Comment by pllim** [comment]
Pretty sure this was fixed. I cannot reproduce it with 4.0dev. Can you please try with the dev version?

**Comment by paulray** [comment]
Indeed, I don't get the Exception under 4.0.dev25832

My software relies on this code, so what versions of astropy should I exclude from the requirements.txt to keep from hitting this?

**Comment by paulray** [comment]
Also, will the fix be backported to 3.1.x?

**Comment by pllim** [comment]
I don't remember, probably not 3.1.x(?), but you can try installing from the 3.2.x branch and see.

**Comment by aarchiba** [comment]
Works for me on astropy 3.2.1.

**Comment by mhvk** [comment]
Sorry that this hit you, @paulray, but at least the later versions are OK. I'll close now...

**Comment by lacfry** [comment]
I have encountered this exact issue using astropy 2.0.9. (My job requires me to use Python 2.7.)
However, if I am using numpy 1.16.2 - I don't get it. If I use numpy 1.16.5 - I do. So, I suspect the issue is in line 387 in astropy.units.quantity.py: value = value.astype(np.float) when the np.float is accessed. Can someone verify that it is fixed in later version of numpy please? (not that I am able to use them...)

**Comment by bsipocz** [comment]
@lacfry - As the discussion above concludes the issue is not present on for the later version. However those are not compatible with python2.7.

The latest release on the 2.0.x series is 2.0.16,  I suggest try to upgrade to that version as many bug fixes has been backported into those LTS releases. If that still doesn't work, your best chance option is to downgrade numpy to 1.16.2

**Comment by lacfry** [comment]
Thank you so much for your response - I also wanted the original author to be aware of the possible numpy dependency.
