### ISSUE TITLE
wcs.to_header() function giving mixed up header keywords

### ISSUE THREAD

**Issue by benw1** [astropy/astropy#9311]
### Description

There are three ways to specify the rotation/scale information. The two can
be combined into one matrix (CD1_1 through CD2_2) or the rotation matrix
can be given as PC1_1 through PC2_2 and the pixel scale as CDELT1/CDELT2.
The third way is to give CDELT1/CDELT2 and a rotation angle as CROTA2.

What wcs.to_header() outputs looks like the second but the values of the PC matrix are
actually what should be in a CD matrix and the CDELT value are nonsensical
(1x1 degree pixels).

Here are the adjustments that need to be made to the headers to make them work properly:
```python
fname, extension = os.path.splitext(file)
fits.delval(file, 'CDELT1')
fits.delval(file, 'CDELT2')
pc1_1 = fits.getval(file, 'PC1_1')
pc1_2 = fits.getval(file, 'PC1_2')
pc2_1 = fits.getval(file, 'PC2_1')
pc2_2 = fits.getval(file, 'PC2_2')
fits.setval(file, 'CD2_2', value=pc2_2, after='CRPIX2')
fits.setval(file, 'CD2_1', value=pc2_1, after='CRPIX2')
fits.setval(file, 'CD1_2', value=pc1_2, after='CRPIX2')
fits.setval(file, 'CD1_1', value=pc1_1, after='CRPIX2')
fits.delval(file, 'PC1_1')
fits.delval(file, 'PC1_2')
fits.delval(file, 'PC2_1')
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by pllim** [comment]
@benw1 , thanks for the report. Can you please share the `file` header that is relevant to the issue so the problem can be reproduced? Also, what `astropy`, Numpy, and Python versions are you using?

**Comment by benw1** [comment]
Thanks for the quick response!
The header is:
SIMPLE  =                    T / Standard FITS format
BITPIX  =                  -32 / Data type
NAXIS   =                    2 / Number of axes
NAXIS1  =                 4096 /
NAXIS2  =                 4096 /
EXTEND  =                    F / There are no standard extensions
BSCALE  =             1.000000 / Image scale
BZERO   =             0.000000 / Image zero
CD1_1   =  1.6191977518236E-05                                                  
CD2_2   =  1.6191977518236E-05                                                  
CD1_2   =                    0                                                  
CD2_1   =                    0                                                  
                                                                                
GCOUNT  =                    1 / number of groups                               
WCSAXES =                    2 / Number of coordinate axes                      
CRPIX1  =               2048.0 / Pixel coordinate of reference point            
CRPIX2  =               2048.0 / Pixel coordinate of reference point            
PC1_1   =  1.6191977518236E-05 / Coordinate transformation matrix element       
PC1_2   = -2.5912580715891E-05 / Coordinate transformation matrix element       
PC2_1   =  2.5912580715891E-05 / Coordinate transformation matrix element       
PC2_2   =  1.6191977518236E-05 / Coordinate transformation matrix element       
CDELT1  =                  1.0 / [deg] Coordinate increment at reference point  
CDELT2  =                  1.0 / [deg] Coordinate increment at reference point  
CUNIT1  = 'deg'                / Units of coordinate increment and value        
CUNIT2  = 'deg'                / Units of coordinate increment and value        
CTYPE1  = 'RA---TAN'           / Right ascension, gnomonic projection           
CTYPE2  = 'DEC--TAN'           / Declination, gnomonic projection               
CRVAL1  =      10.952327482074 / [deg] Coordinate value at reference point      
CRVAL2  =      41.335562257773 / [deg] Coordinate value at reference point      
LONPOLE =                180.0 / [deg] Native longitude of celestial pole       
LATPOLE =      41.335562257773 / [deg] Native latitude of celestial pole        
RADESYS = 'ICRS'               / Equatorial coordinate system                   
EXTNAME = 'WFIRST-WFI'         / extension name                                 
DETECTOR= 'WFIRST-WFI'                                                          
FILTER  = 'Z087    '                                                            
DATE-OBS= '2019-09-06'                                                          
TIME-OBS= 'Sep:09:1567777960'                                                   
EQUINOX =               2000.0                                                  
PA_APER =    58.00000000000156                                                  
VAFACTOR=                  0.0                                                  
ORIENTAT=    58.00000000000156                                                  
RA_APER =     10.9523274820736                                                  
DEC_APER=     41.3355622577725                                                  
EXPTIME =          1800.000000 / Exposure time (s)                              
HISTORY Initialized  Detector WFIRST-WFI, filter Z087                           
HISTORY Adding Cosmic Ray residual with mean 1.608844 and standard deviation 8.2
HISTORY 978303719456 counts/s/oversampled pixel)                                
HISTORY Convolving with file WFI Z087 PSF                                       
HISTORY n 43.58136749267578                                                     
HISTORY 0677                                                                    
HISTORY 62417                                                                   
GAIN    =             1.000000 / Gain (electrons/ADU)                           
RDNOISE =            41.730000 / Read noise (electrons)                         
BADPIX  = -1.0000000150475E+29 / Low bad data value (DN)                        
SATURATE=  1.0000000150475E+30 / High bad data value (DN)                       
MJD-OBS =             0.000000 / Epoch (MJD)                                    
AIRMASS =             0.000000 / Air mass                                       
EXPTIME0=          1800.000000 / Single image exposure time (s)                 

The astropy version is:
>>> print(astropy.__version__) 
3.0.5
>>> 

The problem seems to be that astropy accepts the user building a WCS with a CD matrix, but then only supports turning it into a FITS header with a PC matrix, without transforming the CD matrix internally (it sets CDELT to 1.0 and just uses the CD matrix as its PC matrix).

**Comment by pllim** [comment]
Can you please try with latest release of `astropy`? Or even better, the dev version?

**Comment by nden** [comment]
@benw1 Yes, that is correct. astropy.wcs (and actually wcslib) internally works with the PC matrix.
In this case it's, of course, equivalent to the CD matrix and the computation is correct. If you have to use a CD matrix in general code you may detect that a CD matrix was in the input using `wcs.wcs.has_cd()`  and rename the keywords. Currently there's no function in astropy that would do this, although there was discussion in the past about it. I have to find it to remind myself about all the arguments.

**Comment by saimn** [comment]
The discussion in question is probably #1084.

**Comment by pllim** [comment]
Ah, should I mark this as duplicate issue then?

**Comment by nden** [comment]
@pllim I'm not sure we should do anything about it. IIRC CD matrix was invented by STScI. HST data use it. We deal with the conversion in our internal software instead of changing the library.

**Comment by benw1** [comment]
I have verified that this same CDELT issue occurs in astropy version 3.2.1.
