### ISSUE TITLE
TST: Run test suite twice in a row without cleaning build in the same session

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9318]
### Description

Modify one of the existing CI jobs to run the whole test suite twice in a row in the same session without cleaning anything in between. Maybe it is even better if we can do this on the remote data job, but not sure about the network hit limits.

The motivation for this is to make sure that anyone who runs `astropy.test()` and then use `astropy` in the same Python session will not experience any surprising behaviors. Running the tests should not change the state of the entire module permanently.

### Additional context

See discussions in #5120 and https://github.com/astropy/astropy/pull/9278#discussion_r331582167 .

cc @astrofrog

**Comment by bsipocz** [comment]
Given that the tests run for a long time, I think this one should only run infrequently, e.g. only in weekly crons. Or if we get that azure pipeline with the release steps.
Or just see whether rerunning only parts of the tests would be sufficient enough.

**Comment by pllim** [comment]
👍 to cron
