### ISSUE TITLE
Provide normalized phase and phase doubling in TimeSeries.fold()

### ISSUE THREAD

**Issue by ebellm** [astropy/astropy#9331]
### Description

The current `TimeSeries.fold()` method provides an output TimeSeries with the time axis providing a delta time around a midpoint epoch.  While appropriate for transits, this approach is unconventional for periodic variable stars (e.g., RR Lyrae).  There it is typical to plot the normalized phase (0-1) after providing a reference time for the zero phase.

It is also frequently useful to plot two phases consecutively (i.e. to duplicate the data values with phases incremented by 1.0) in order to show structures that would otherwise be hidden by the plot edges.

### Additional context
[An example phased lightcurve from ASAS-SN with two phases plotted](https://asas-sn.osu.edu/variables/AP18201061)
[Example phased lightcurves, plotted over 1.5 phases](https://www.cosmos.esa.int/web/hipparcos/examples-part-a)

**Comment by bsipocz** [comment]
👍 these phase plots makes much more sense for most use cases.

@astrofrog - I think there is room to extend the current API with new keywords without adding new methods.
E.g. add a bool `phase` and `phase_nums` or similar with a default to `2`, or even `phase` could be a float.
I would then suggest to rename `midpoint_epoch` to `epoch`, so for phase plots that would be the epoch at `phase=0`.
