### ISSUE TITLE
BUG: LTS docs page opening page doesn't have the astropy logo

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#9336]
<img width="993" alt="Screen Shot 2019-10-07 at 19 47 49" src="https://user-images.githubusercontent.com/6788290/66363506-5fbbdb80-e93b-11e9-9fa5-5219f2286e87.png">

**Comment by pllim** [comment]
Why does that look so familiar...

**Comment by pllim** [comment]
Maybe #8278 needs to be backported?

**Comment by bsipocz** [comment]
circleci/giles, but there it's the case for all the builds

**Comment by bsipocz** [comment]
It wasn't an issue on LTS at the time of that PR (according to the comments)

**Comment by pllim** [comment]
Maybe now it is picking up whatever it wasn't picking up back then... 🤷‍♀

**Comment by bsipocz** [comment]
ok, I'll try to backport it, push that to the branch, and if it works we retag LTS (without doing another release)

**Comment by bsipocz** [comment]
https://readthedocs.org/projects/astropy/builds/9768705/

**Comment by bsipocz** [comment]
OK, the backport worked.

**Comment by bsipocz** [comment]
OK, the trick worked. Closing this now.
