### ISSUE TITLE
Time formats mjd_long, mjd_string, and mjd_decimal

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#9358]
Astropy Time objects are designed to have more available precision than python floats. But it can be very cumbersome to read and write values with this extra precision, particularly in the format (MJD) that is customary in pulsar astronomy (which actually needs the extra precision). The easiest way to manipulate these is to use time format "mjd" which converts to and from python floats. I suggest adding formats "mjd_long" and "mjd_decimal" which use higher-precision numbers to represent these quantities, and "mjd_string" to allow conversion to and from string representations without precision loss.

For a demonstration that this can be done see: https://github.com/nanograv/PINT/pull/549 Note that much but not all of the complexity there is either to work around astropy bug #9327 or to deal with the awkward way pulsar astronomy instruments handle UTC MJDs (as opposed to the awkward way astropy's Time objects handle UTC MJDs; the difference is in the handling of leap second days, of using a timescale with jumps versus a linear "leap smear"). 

Concerns:

- Do we want the jd_ versions too? These have even worse precision problems (and thus would benefit even more from such methods).
- We presumably want corresponding TimeDeltaFormats as well.

**Comment by mhvk** [comment]
I like this but worry a bit about an explosion of formats which deal with the same kinds of input and representation. Of course, at some level we already do this (with `[bj]year` and `[bj]year_str`, so perhaps it is OK to have `mjd_str` and `jd_str` versions. Then, again, unlike the other string formats, these would not be unique.

At least for `long` and `Decimal`, I think another possibility might be just to recognize and use those on input (as we already do for `Quantity` with time-like units) and then use `out_subfmt` for selecting what is returned with `.value`. In principle, it might in fact be possible to do the same with string representations. And of course if one wanted to be sure about input one could then use `in_subfmt`.

@taldcroft - what do you think?

**Comment by aarchiba** [comment]
Let's keep some use cases in mind. For example:

- I have a Time object and I want to produce a string representation to write to a file.
- I am reading a field from a file and want to produce Time objects.
- I have some Time objects and I want to put them into some formula (say a Taylor series) that needs more than double precision, then I want to stick the output back into a Time object.

So with this proposal I can do t.mjd_string, Time(s, format="mjd_string"), dt = (t2-t1).mjd_long, calculate with dt, t3 = t1+TimeDelta(dt_out, format="mjd_long"). What would these look like with subformats?

Can an input format even accept multiple input types without replicating all sorts of conversion and validation code from within astropy/time/core.py? How much code would be shared between mjd_string, mjd_long, and mjd_decimal if instead they were made subformats?

**Comment by mhvk** [comment]
Have a look at #9361 - not necessarily sure this is the best route; one can likely do much of this with sub-classing too. But I like that with the subformats `Time(..., format='mjd')` will just accept string or `Decimal`.

**Comment by astrofrog** [comment]
Just out of curiosity, is there any reason to not implement a ``to_string`` method as for other objects? I was teaching astropy.time as part of a workshop and participants were confused as to why Time did not have ``to_string`` when e.g. ``SkyCoord`` and ``Quantity`` do, and in particular why the ``precision`` for the string representation was stateful. I know we can't easily change the existing API, but when considering new advanced functionality like that being discussed here it might be worth considering whether a method would be better than an explosion in the number of available format attributes.

**Comment by taldcroft** [comment]
> Edit: re-reading this I realize that this is also about parsing. But for this, why is Time(s, format="mjd_string") needed? Can't we just make Time(s, format="mjd") recognize whether the input is float, long, or string automatically?

Automatic parsing is indeed the current implementation in #9361, and the `'mjd_string'` syntax is gone in favor of a less magical `.to_value('mjd', 'str')`.

> Just out of curiosity, is there any reason to not implement a to_string method as for other objects?

@mhvk can answer as well, but I think that `to_string` has gotten stalled on details of how to actually implement that, like whether there is a Time-specific format language and/or use of `__format__` etc.  This is re-opened in #9421, but I recall many years ago proposing a time format mini-language and getting shut down, so nothing happened.  (An example of "perfect is the enemy of good" IMHO, but so it goes).

**Comment by mhvk** [comment]
@astrofrog - indeed, see #9421. And my suggestion definitely is first to have a `to_string()` method, which can be fairly specific to `Time`, and then think again about `__format__` - for which consistency across at least astropy would be more important.  E.g., one would want to use the same "type-code" to indicate number of fractional seconds in times and (hour)angles.

**Comment by mhvk** [comment]
fixed by #9361
