### ISSUE TITLE
Make EquivalentUnitsList have notebook-friendly output

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9381]
It would be nice if ``EquivalentUnitsList`` could implement ``_repr_html_`` to have nicer output in Jupyter notebooks. Currently this looks like:

<img width="871" alt="Screenshot 2019-10-16 at 16 54 12" src="https://user-images.githubusercontent.com/314716/66936536-c88b0e00-f035-11e9-8b7e-58959cde9f44.png">

but I think it would be nice to use a proper HTML table.

**Comment by sadielbartholomew** [comment]
Hi, please can I take this Issue on for Hacktoberfest?

**Comment by bsipocz** [comment]
Yes, please go ahead with a PR.

**Comment by sadielbartholomew** [comment]
Great, thanks. I hope to put one up sometime in the next few days.
