### ISSUE TITLE
Feature Request: Raise red flag when PR is not against master

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9385]
### Description

As suggested by @astrofrog , there can be a check that will fail if a pull request is opened against something that is not the `master` branch. I feel like this can be done by GitHub Actions.

That said, we also need a way for core maintainer to dismiss it because occasionally (but rarely) we purposely open a PR for direct backport.

### Additional context

This is needed because it is currently not possible to get rid of "On GitHub -> Edit" feature in ReadTheDocs, which makes it very easy to mistakenly open a PR against, say, `stable` branch. And also, we cannot easily fix that "Edit" link on all the versions without rebuilding them.

cc @bsipocz

**Comment by bsipocz** [comment]
Either actions or Baldrick :)

**Comment by pllim** [comment]
Either way, it is a cunning plan. :wink:

**Comment by bsipocz** [comment]
😏

**Comment by pllim** [comment]
Turns out I can do this faster in `baldrick` than with Actions. Also Actions is in beta and has a big "subject to change" disclaimer. Let's move this over to OpenAstronomy/baldrick#92
