### ISSUE TITLE
Build manylinux 2010 wheels

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#9391]
As it is not possible to build manylinux1 wheels for python 3.7 because of openssl,
it would be really great if you could build manylinux2010 wheels for python 3.7.

**Comment by astrofrog** [comment]
@MaxNoe - we do have manylinux1 wheels for Python 3.7 (just uploaded a few hours ago). Do they not work correctly? (we haven't run into ssl issues)

**Comment by MaxNoe** [comment]
Okay, I thought that was tue issue, it was when python 3.7 came first out.

I just realized that a ci build yesterday downloaded the sdist for 3.7 but a wheel for 3.6
