### ISSUE TITLE
_check_numpy gives misleading error message if numpy is not installed at all

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#9398]
### Description

`astropy.__init__._check_numpy()` is supposed to check for a compatible version of numpy, but it gives a misleading error message if numpy isn't installed at all.  This is not impossible: it can happen that numpy & astropy are installed, then numpy is removed.

### Expected behavior

I would expect `_check_numpy()` to actually raise the `ImportError`  from `import numpy` instead of `pass`ing on that error and raising a message that the *version* is incompatible.

### Actual behavior

`raise ImportError("Numpy version {} or later must be installed to use "
               "Astropy".format(__minimum_numpy_version__)`

### Steps to Reproduce

Very recent versions of conda fail can't find a compatible version of numpy and astropy on Python 3.5, for example, with NUMPY_VERSION=1.16.5, and ASTROPY_VERSION=lts.  Conda falls back to pip, which then uninstalls numpy after astropy is installed.

See https://travis-ci.org/desihub/desisim/jobs/599392753

### System Details

Python=3.5.6
Numpy=1.16.5
Scipy=1.1.0
Astropy=2.0.15

**Comment by pllim** [comment]
I would disagree that `ImportError: Numpy version 1.9.0 or later must be installed to use Astropy` is misleading, as that sentence still makes sense to me in the event that Numpy is **not** installed. How can we make that sentence clearer?

Also, we no longer push fixes to 2.x or 3.x unless it is absolutely necessary. FYI.

**Comment by weaverba137** [comment]
It is misleading if you *think* you have it installed but don't.  It causes you to waste time trying to figure out why you're getting this error message, when it would be just as easy to say, "No version of numpy could be found at all."

**Comment by pllim** [comment]
@weaverba137 , since you have a clear solution presented, do you wish to open a PR to address this?

**Comment by weaverba137** [comment]
Will do!
