### ISSUE TITLE
Add easy way to set WCSAxes 1:1 aspect ratio in world coordinates

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#9399]
### Description
Plotting a figure to a WCSAxes when `CDELT1` != `CDELT2` results in a 1:1 aspect ratio for the pixes, but *not* a 1:1 aspect ratio in 'coordinate space'. I think it should by default set a 1:1 aspect ratio in coordinate space (ie. stretch the pixels in one direction), or at least it should be documented how to achieve this effect.

### Actual behavior
The second image with the code below (with `CDELT1` = 2`CDELT2`) is shown here. Note that the axes labels are correct, but the aspect ratio is no longer 1:1, as 30' on the x-axis is the same distance as 15' on the y-axis.
![Unknown-2](https://user-images.githubusercontent.com/6197628/67082215-917d3f80-f190-11e9-9bc8-a358ee71ee0c.png)

### Steps to Reproduce

```python
import matplotlib.pyplot as plt

from astropy.wcs import WCS
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename

filename = get_pkg_data_filename('galactic_center/gc_msx_e.fits')

hdu = fits.open(filename)[0]
header = hdu.header
wcs = WCS(header)

plt.figure()
plt.subplot(projection=wcs)
plt.imshow(hdu.data, vmin=-2.e-5, vmax=2.e-4, origin='lower')

# Scale one of the axes by a factor of 2
header['CDELT1'] = header['CDELT1'] * 2
wcs = WCS(header)
plt.figure()
plt.subplot(projection=wcs)
plt.imshow(hdu.data, vmin=-2.e-5, vmax=2.e-4, origin='lower')

```

### System Details
```python
>>> import platform; print(platform.platform())
Darwin-18.7.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.17.2
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.3.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 3.2.2
```

**Comment by Cadair** [comment]
WCSAxes always draws in pixel space, so the pixels are always square. You will notice the ticks are not equally spaced in world coordinates.

**Comment by dstansby** [comment]
Is there an easy way to set the aspect ratio to be 1:1 in world co-ordinates?

**Comment by dstansby** [comment]
A bit of playing around and `ax.set_aspect(np.abs(wcs.wcs.cdelt[1] / wcs.wcs.cdelt[0]))` does the trick - maybe it would be nice to add a helper method (WCSAxes.set_equal_world_aspect()`?) to do this.

**Comment by pllim** [comment]
Thanks for reporting this in such details and provide a solution too, @dstansby ! Feel free to open a PR, if nothing else, you get credit towards Hacktoberfest this month. 😉

**Comment by dstansby** [comment]
Closing as per https://github.com/astropy/astropy/pull/9410#issuecomment-638370142
