### ISSUE TITLE
MNT: _parameter_units_for_data_units in models does not need OrderedDict

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9403]
### Description

At the time of writing, http://docs.astropy.org/en/latest/modeling/add-units.html#fitting and the actual implementations of `_parameter_units_for_data_units` all use `OrderedDict`. Example from `Gaussian1D`:
```python
def _parameter_units_for_data_units(self, inputs_unit, outputs_unit):
    return OrderedDict([('mean', inputs_unit['x']),
                        ('stddev', inputs_unit['x']),
                        ('amplitude', outputs_unit['y'])])
```

Since Python 3.6, `dict` is already insertion-ordered. In addition, I don't see how the order could/should affect the results.

Furthermore, if your model only has one parameter anyway, you definitely don't need `OrderedDict`, as the ordered and unordered results would be the same.

### Additional context

I asked about this on Slack and @nden seemed to agree but @astrofrog did not have time to investigate. So I decided to open an issue so we can revisit this in the future.

**Comment by nden** [comment]
Or better if you have time, change all `OrderedDict` to dict and run the tests.
