### ISSUE TITLE
Inconsistent keyword names for binom_conf_interval and poisson_conf_interval

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9406]
The functions ``binom_conf_interval`` and ``poisson_conf_interval`` in astropy.stats both have a keyword argument for the confidence level, but one is called ``conf`` and the other one ``conflevel``. Can we consider renaming the most recent one via a deprecation phase, or have both functions been around for too long?

**Comment by bsipocz** [comment]
I would think a renaming with deprecations in 4.0 is reasonable, and then in 5.0 we can re-evaluate whether it was long enough in deprecation.

**Comment by pllim** [comment]
See #9408
