### ISSUE TITLE
Cutout2D does not work correctly with NDData objects

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9412]
The ``Cutout2D`` class can't be initialized with an ``NDData`` object if ``position`` is a ``SkyCoord`` since ``wcs`` is not set - however, we should be able to extract the ``wcs`` from the ``NDData``? Should we just add ``@support_nddata`` to the initializer of ``Cutout2D``?

I'm marking this as a bug because the front page of the NDData docs show an NDData object being used as input: http://docs.astropy.org/en/stable/nddata/index.html#image-utilities

**Comment by bsipocz** [comment]
Isn't this a duplicate of https://github.com/astropy/astropy/issues/9173?

**Comment by astrofrog** [comment]
It is a duplicate. I'll comment there on bug vs feature.
