### ISSUE TITLE
Incorrect WCS example in NDData docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9417]
The NDData docs [here](http://docs.astropy.org/en/stable/nddata/index.html#nddata) incorrectly show a SkyCoord being passed to the ``wcs`` of an NDData object. This should be fixed to show an actual WCS object being passed in.

![Screenshot from 2019-10-20 13-30-22](https://user-images.githubusercontent.com/314716/67159544-e7431a80-f33d-11e9-9f18-19149f2c6264.png)

**Comment by MSeifert04** [comment]
Not really a bug at the moment, because currently NDData allows anything as WCS. However that particular example will (probably) be fixed in #9067.

**Comment by bsipocz** [comment]
#9067 has updated the example
