### ISSUE TITLE
Keep constants for old Numpy version checks?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9419]
I just noticed that e.g. specutils relies on ``NUMPY_LT_1_14`` from astropy core, and this is now broken:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-fe00de7d5332> in <module>
----> 1 from specutils.spectra.spectral_coordinate import SpectralCoord

~/Code/specutils/specutils/spectra/spectral_coordinate.py in <module>
      7 from astropy.coordinates import SkyCoord, ICRS, Distance, GCRS
      8 from astropy.coordinates.baseframe import BaseCoordinateFrame, FrameMeta
----> 9 from astropy.utils.compat import NUMPY_LT_1_14
     10 from astropy.utils.exceptions import AstropyUserWarning
     11 

ImportError: cannot import name 'NUMPY_LT_1_14' from 'astropy.utils.compat' (/home/tom/Code/astropy/astropy/utils/compat/__init__.py)
```

It might make sense to keep these constants around for a little while even if we don't use them in core?

cc @mhvk @bsipocz

**Comment by MSeifert04** [comment]
That raises the question if `astropy.utils` is meant as public API or as private? The documentation puts it in the "Nuts and bolts" as "Astropy Core Package Utilities (astropy.utils)" which indicates it's private but I haven't seen an explicit mention either way. 

I don't want to say that I'm against adding the constants again, I'm just curious.

**Comment by astrofrog** [comment]
> which indicates it's private

I think if it's in the API docs, to me that makes it public (and especially if there is a section in the docs) - and more generally if it's accessible through tab completion, it's public? (that is, e.g. ``astropy._erfa`` is private?)

**Comment by MSeifert04** [comment]
> I think if it's in the API docs, to me that makes it public

That makes sense - I just wasn't sure if it's "documentation for astropy contributors" instead of "documentation for astropy users".

**Comment by mhvk** [comment]
Hmm, `astropy.utils.compat` is explicitly excluded from the documentation and the astropy version will refuse to start if that constant were true, so I don't really see the point of keeping it around. Might be good to advertise `minversion` a bit more, though.

p.s. On `_erfa` - that is explicitly prefixed with an underscore, so private. We do at some point need to decide whether to make it public or push the python interface to `liberfa` and start to depend on it.

**Comment by astrofrog** [comment]
I wonder if we should keep these constants in a private module then? (With a _). As mentioned above, other packages like specutils rely on this and are broken as a result. I would assume underscores, not presence in the docs, is the main indication of private ca public?

**Comment by mhvk** [comment]
@astrofrog - Indeed, a private module `_compat` seems reasonable. Alternatively, we could decide to follow the precedent of the other modules and make everything inside `utils` effectively private - though that seems too much (`utils.data` and `utils.data_info` are definitely meant to be public).

I should add, though, that I do not feel super-strongly. It is more that `utils.compat` really seemed meant to be a set of hacks that we use internally, not something we'd want to support indefinitely. But something intermediate, like only cleaning this out for LTS or so, would be fine too.

**Comment by bsipocz** [comment]
I'm 👎 on keeping those around. Downstream packages better keep their compatibility checks within themselves, or keep up with the same version supports astropy does.

As mentioned above the utils compat module is deliberately kept out of the docs. I don't feel that cleaning that module out in prep for a new LTS should be blocked by misusage downstream (e.g. photutils does the right thing of defining its own `NUMPY_LT_1_14`)

**Comment by astrofrog** [comment]
If the intent is that ``compat`` be used only by core, I'm definitely 👍 to changing it to astropy.utils._compat. You might not believe it but some people just rely on tab completion and don't read the docs 😆

**Comment by bsipocz** [comment]
> You might not believe it but some people just rely on tab completion and don't read the docs

and that is fine, but then we're not to blame 🤷‍♀ , especially if it's in a coordinated package...

**Comment by mhvk** [comment]
I'm not very keen on the underscore for a module - we've not used that at all except for `_erfa` (which is a special case). But I'd be happy with moving things to a more general `utils.private` module or so.

Though my tendency would be just to update `astropy.utils.__init__.__docstring__` (plus `compat.__init__.py` and the docs) to state that `compat` will only contain strictly what is needed for astropy itself.

**Comment by pllim** [comment]
👎 on keeping it. Also don't feel so much like renaming the module... but I guess that is the only thing we can do if people blindly using tab-complete... 🤷‍♀

**Comment by bsipocz** [comment]
I agree with @mhvk  that it should be enough to put it in the docs. No one should really lurking around in `utils` blindly, it's not like tab completing on a  user facing class like `Quantity`.

**Comment by amillsytla** [comment]
Hi, I know I'm not an astropy developer, but I am getting this error just from trying to import Time, could this be related?
from astropy.time import Time
~/anaconda3/lib/python3.9/site-packages/astropy/units/quantity.py in <module>
     19 # LOCAL
     20 from astropy import config as _config
---> 21 from astropy.utils.compat import NUMPY_LT_1_20, NUMPY_LT_1_22
     22 from astropy.utils.compat.misc import override__dir__
     23 from astropy.utils.data_info import ParentDtypeInfo

ImportError: cannot import name 'NUMPY_LT_1_22' from 'astropy.utils.compat' (/home/amills/anaconda3/lib/python3.9/site-packages/astropy/utils/compat/__init__.py)
Thanks,
Adam

**Comment by eerovaher** [comment]
The line that tries to import `NUMPY_LT_1_22` is present in the different releases of `astropy` 5, but so is the line that defines the constant. Furthermore, if just importing `Time` would cause an error then the CI tests would have revealed it. Most likely there is something wrong with your installation of `astropy`. Is this something that could happen if `pip` is used in a `conda` environment? The solution to your problem would be to install `astropy` properly, and there is no indication that this is a bug in `astropy` itself.

**Comment by amillsytla** [comment]
HI Eero,
Thank you so much for your reply! The issue was occurring in Jupyter
Notebook. I ran the code as a normal python program from a terminal and it
worked. So then I restarted the kernel in Jupyter Notebook and that fixed
the issue.
Thanks,
Adam
