### ISSUE TITLE
AssertionError in the test_quantity_ufuncs

### ISSUE THREAD

**Issue by MohsenQazi** [astropy/astropy#9422]
Following instructions in [Try the development version](http://docs.astropy.org/en/stable/development/workflow/get_devel_version.html), I've got one failure after `python setup.py test` at the shell prompt:
```
self = <astropy.units.tests.test_quantity_ufuncs.TestUfuncHelpers object at >

    def test_coverage(self):
        """Test that we cover all ufunc's"""    
        all_np_ufuncs = set([ufunc for ufunc in np.core.umath.__dict__.values()
                             if isinstance(ufunc, np.ufunc)])
    
        all_q_ufuncs = (qh.UNSUPPORTED_UFUNCS |
                        set(qh.UFUNC_HELPERS.keys()))
        # Check that every numpy ufunc is covered.
    --> assert all_np_ufuncs - all_q_ufuncs == set()
E       AssertionError: assert {<ufunc 'erf'>} == set()
E         Extra items in the left set:
E         <ufunc 'erf'>
E         Use -v to get the full diff

astropy/units/tests/test_quantity_ufuncs.py:69: AssertionError
```
![Screenshot_20191021_101816](https://user-images.githubusercontent.com/55282885/67188300-e3280300-f3f8-11e9-9bc7-4ad724b33f06.png)

Linux-4.19.0-6-amd64-x86_64-with-debian-10.1
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
Numpy 1.16.4
Scipy 1.3.0
astropy 4.0.dev26155

EDIT: Formatting.

**Comment by pllim** [comment]
How did you install it? Do you still have the test header?

**Comment by MohsenQazi** [comment]
Python, Numpy and Scipy are installed via `Anaconda3-5.0.1-Linux-x86_64.sh`, and I copy Astropy to my system by `git`.
How can I find if there is the test header?!

**Comment by pllim** [comment]
The test header is the stuff just above what your screenshot shows. Look for `========== test session starts =========` and copy everything under it.

**Comment by pllim** [comment]
Might also be helpful to tell us the command you use to build/install `astropy` after you cloned it with `git`.

**Comment by MohsenQazi** [comment]
> Might also be helpful to tell us the command you use to build/install `astropy` after you cloned it with `git`.

@pllim - I just followed [this instructions](http://docs.astropy.org/en/stable/development/workflow/get_devel_version.html):
`pip install -e .`

**Comment by MohsenQazi** [comment]
@pllim - Complete output of `python setup.py test`:
[test session starts.txt](https://github.com/astropy/astropy/files/3761605/test.session.starts.txt)

**Comment by pllim** [comment]
Interesting... Nothing unusual popped up for me. And it seemed that @adrn ran into the same error independently as well. @mhvk , any idea?

**Comment by mhvk** [comment]
@MohsenQazi - this is a problem with some intel versions of numpy, which add an `erf` ufunc even though numpy itself doesn't ship with one. I thought we had this covered, though... I think something may have gotten removed by accident...

**Comment by mhvk** [comment]
See #9460. @MohsenQazi - it would be great if you could check whether this resolves your issue - our CI doesn't run with intel-provided numpy (and I don't think we should start to), so it will not provide anything useful.
