### ISSUE TITLE
USNO IERS services going down for 6 months

### ISSUE THREAD

**Issue by bhazelton** [astropy/astropy#9427]
There's a big red warning on both http://maia.usno.navy.mil/ and http://toshi.nofs.navy.mil/ saying that they will be down for maintenance from Oct. 24 2019 until April 30 2020 (6 months!).

I'm not sure if there are other sites that will serve the files astropy relies on, but I believe that these two are the only ones astropy currently looks at.

The astropy functionality that depends on the availability of these IERS tables is mission critical for several telescopes so I think we need some ways to handle this.

**Comment by bsipocz** [comment]
@eteq @astrofrog  - this seems to be critical enough to warrant a v2.0.16 (and maybe even a 3.2.3, too) once the solution is in

**Comment by bmorris3** [comment]
Just in case it changes, here's what the webpage warning says right now: 

```
Notice of Pending Shutdown

The U.S. Naval Observatory's Rapid/Service Prediction web/FTP sites (maia.usno.navy.mil and toshi.nofs.navy.mil) must undergo modernization and will be offline starting sometime Thursday, 24 October 2019. The expected completion of work and return of service is estimated as 30 April 2020.

Please visit https://www.usno.navy.mil and submit a Requirements Form to the USNO Public Affairs Official (PAO) if the information you are seeking is not accessible via another means. If the Requirements Form is not available, please directly contact the PAO Geoff Chester at email address geoff.chester@navy.mil or phone number 1-202-762-1438.
```

**Comment by pllim** [comment]
We also need to be prepared for the possibility that the maintenance get prolonged beyond *April 30 2020* into forever, ever, and ever...

**Comment by pllim** [comment]
From @eteq on Slack:

*It looks like we may want to use these as mirrors while IERS is offline:*

* https://datacenter.iers.org/eop.php
* ftp://cddis.gsfc.nasa.gov/pub/products/iers

**Comment by loxlig** [comment]
What is the workaround for prevent scripts depending on astropy iers.py from failing when the IERS mirror is unavailable? What should happen if/when there are no IERS mirrors available but scripts absolutely must run. Perhaps there could be other reasons for an IERS mirror from being available not including a failure of the mirror. This seems like a potentially serious point of failure in order to satisfy only the dependency of accurate IERS data when there are many more parts to a script that must also be satisified.

**Comment by pllim** [comment]
@loxlig , we changed the URLs to mirrors. If you update astropy to the latest releases, it should still work unless your firewall setting also blocks the mirrors.

For a more robust solution, a better caching mechanism in 4.0 would hopefully take care of offline use.

**Comment by eteq** [comment]
To add one more note here for those who might come across this issue - there's a workaround that will work in older versions of astropy:
```
from astropy.utils import iers
iers.Conf.iers_auto_url.set('ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all')
```
(or substitute in whatever other URL is the default in future Astropy versions if there's another change to what IERS/USNO recommend...)

**Comment by pllim** [comment]
A note from USNO:

**The USNO websites aa.usno.navy.mil, ad.usno.navy.mil, aristarchus.usno.navy.mil, maia.usno.navy.mil, rorf.usno.navy.mil, and toshi.usno.navy.mil are undergoing modernization efforts. The expected completion of the work and return of service is estimated as 30 April 2020. Please submit a [requirements form](https://www.usno.navy.mil/USNO/astrometry/optical-IR-prod/icas/help/requirements-form) to the USNOPAO if the information you are seeking is not accessible via other means.**

If you are inconvenienced by this, use that form to let them know. They are trying to see the extend of the impact of these modernization efforts.

**Comment by pllim** [comment]
USNO form has been moved to https://www.usno.navy.mil/USNO/help/requirements-form -- FYI
