### ISSUE TITLE
Update galactocentric parameters to be "latest"

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9430]
#9346 implemented a way to set the default parameters for the `Galactocentric` class.  It also introduced a warning about how the values will change in the future.  The plan worked out there is to have the warning for 4.0, and then drop this warning in 4.1 and replace with just defaulting to the "latest" values.  This issue's purpose is to remind us to do that for 4.1 (but *not* for 4.0)

cc @adrn

**Comment by bsipocz** [comment]
@eteq @adrn - is this still in the plans for 4.1?

**Comment by adrn** [comment]
Doh, yes...
