### ISSUE TITLE
MNT: Remove deprecated blackbody module and documentation

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9434]
### Description

Remove deprecated `blackbody` module (deprecated in 4.0) and all references to it in the documentation.

### Additional context

Expanded from what @bsipocz said in https://github.com/astropy/astropy/pull/9282#issuecomment-543966891

**Comment by bsipocz** [comment]
We might want to remove the docs sooner, but either case it's super useful to have a reminder about it. 

I also wonder whether it may be even more useful to have a tracking issue for all the deprecations, like e.g. https://github.com/numpy/numpy/issues/11521? I found your warnings issue/pseudo PR super useful with the tickboxes, but maybe it's not that useful for a longer term tracker?

**Comment by pllim** [comment]
Sometimes I regret making that issue with a lot of tickboxes, because things get out of sync over time. I actually need to remind myself to revisit that issue and check that the boxes are ticked/unticked correctly. I thought about a project board, but that get out of sync too. I haven't found a perfect solution yet.

**Comment by bsipocz** [comment]
Yes, it definitely needs some meta managing to make sure box are ticked, but I think we're doing quite OK with it. Also your https://github.com/astropy/astropy/issues/8888 is super useful (at least for me :) )

**Comment by pllim** [comment]
I have #10972 as PR to implement this, so tracking the milestone there and removing milestone from this issue. FYI.
