### ISSUE TITLE
SkyCoord.shape returns emtpy tuple for SkyCoord with a single entry

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#9446]
### Description
Trying to get the `.shape` of a single entry `SkyCoord` object returns an empty tuple. Naïevley I expect this to return (1,), but a bit of digging leads this behavior back to
```python
>>> np.array(1).shape
()
```

So this is mimicking numpy behaviour, but I expected it to return (1,) since there's one data point in the SkyCoord object. Maybe this should stay as it is since it's just imitating numpy behavior.

### Steps to Reproduce

1. Run the code below:

```python
from astropy import units as u
from astropy.coordinates import SkyCoord
c = SkyCoord(ra=10.625*u.degree, dec=41.2*u.degree, frame='icrs')
print(c.shape)
```
Prints `()`. I would expect it to print `(1,)`, but not to be an emtpy tuple.

### System Details

```python
>>> import sys; print("Python", sys.version)
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.17.2
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.3.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 3.2.2
```

**Comment by adrn** [comment]
Hey @dstansby. There is a little ambiguity here, but this is the intended behavior. `SkyCoord.shape` returns the shape of the data objects that make up individual components. Here, those components are scalars (in a numpy sense), as you found in your first example with `np.array(1).shape`. The [documentation about this attribute is a little confusing](http://docs.astropy.org/en/latest/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord.shape) -- is there anything you think we should change about the wording to clarify this?

**Comment by dstansby** [comment]
Yes, that makes sense, sorry for the noise here!

Maybe changing "The shape of the instance and underlying arrays." to "The shape of the underlying data array" would make more sense to me. I'm happy to open a PR for that.

**Comment by adrn** [comment]
That would be great, please do!
