### ISSUE TITLE
Distribution.pdf_* methods should be functions, not properties

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#9447]
@eteq - while looking at the code again, I noticed that things like `.pdf_mean` are properties, not methods. I think this is a mistake, as it is too different from `.mean()` and `.std()`, etc. In general, I'd use methods if real calculations are being done, and in this case I also wonder if we shouldn't be a bit more future-proof by at least in principle allowing extension with arguments (even if just an `out` argument, or for `pdf_std` to pass on `ddof` to the underlying `ndarray` method).

My sense is that we should still change this - since `uncertainty` is not used that much yet, it is probably the last change we have...

**Comment by mhvk** [comment]
@eteq - what do you think about properties vs functions for `Distribution.pdf_*` - to me, it would seem best to change - `.pdf_std` possibly needing `ddof` being my prime argument.

**Comment by mhvk** [comment]
Running into the deadline is one way of deciding the issue, but probably better to spend a bit of thought... How will one do `pdf_std` without using the (usually incorrect) default `ddof=0`? I keep thinking that given that `uncertainties` has been experimental, we can still change it.

**Comment by bsipocz** [comment]
Any chance to pull this off for 4.0? In either case I'm removing the milestone for now.

**Comment by mhvk** [comment]
I'm very happy to do a quick PR, but don't want to waste time if @eteq thinks it is not an issue/good idea.

**Comment by eteq** [comment]
(To not duplicate the thread, I have a comment https://github.com/astropy/astropy/pull/9613#issuecomment-555140309 that would have gone in this issue if I had noticed it before #9613)
