### ISSUE TITLE
Support VOTable 1.4

### ISSUE THREAD

**Issue by tomdonaldson** [astropy/astropy#9474]
### Description

VOTable version 1.4 is now an official IVOA recommendation.  The main difference from version 1.3 is that a new element, TIMESYS, is supported.  That element allows defining of metadata for temporal coordinates much like COOSYS defines metadata for celestial coordinates.

This issue is to ensure that VOTable 1.4 can be parsed and written while retaining the TIMESYS information.  Further use of TIMESYS can be handled with issue #8724.

### Additional context

VOTable 1.4 specifcation is [here](http://www.ivoa.net/documents/VOTable/20191021/).

**Comment by pllim** [comment]
The PR is already milestoned, so I am removing milestone from the issue. FYI.
