### ISSUE TITLE
MNT: Clean pytest-astropy-header install in CircleCI before 4.0 release

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9476]
### Description

Back out `pip install pytest-astropy-header --upgrade --no-deps` commands in CircleCI YAML file when `pytest-astropy` has been updated and available. See https://github.com/astropy/astropy/pull/9214#discussion_r339146578 for more details.

### Additional context

This is a follow-up of #9214 .

**Comment by astrofrog** [comment]
I'll need to update the docker images, will try and do that early next week
