### ISSUE TITLE
Fix bug in failed configuration file generation warning

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#950]
@mdboom - commit fcc2d63df086c7b834867bce44dd70a348b745d1 introduced an issue with Python 3 when the warning is emitted:

```
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by MjdMahasneh** [comment]
@embray Hello! am having the same issue and i have seen your comment about  using _ASTROPY_SETUP_ instead of _PACKAGE_SETUP_ however i dont know how to change the template package settings to start using _ASTROPY_SETUP_.  please advice.

**Comment by pllim** [comment]
@MjdMahasneh , if you have problem with the package template, please open an issue at https://github.com/astropy/package-template . Also, the template now uses `cookiecutter`.
