### ISSUE TITLE
Reconstruction of signal analyzed with LombScargle

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [astropy/astropy#9502]
### Description

I'd like to reconstruct a signal for which I have some data and used LombScargle to obtain it's frequency components.

My data is in addition as the following:

```
r = np.array([119.75024144, 119.77177673, 119.79671626, 119.81566188,
       119.81291201, 119.71610143, 119.24156708, 117.66932347,
       114.22145178, 109.27266933, 104.57675147, 101.63381325,
       100.42623807, 100.09436745, 100.02798438, 100.02696846,
       100.05422613, 100.12216521, 100.27569606, 100.60962812,
       101.32023289, 102.71102637, 105.01826819, 108.17052642,
       111.67848758, 114.78442424, 116.95337537, 118.19437002,
       118.84307457, 119.19571404, 119.40326818, 119.53101551,
       119.61170874, 119.66610072, 119.68315253, 119.53757829,
       118.83748609, 116.90425868, 113.32095843, 108.72465638,
       104.58292906, 101.93316248, 100.68856962, 100.22523098,
       100.08558767, 100.07194691, 100.11193397, 100.19142891,
       100.33208922, 100.5849306 , 101.04224415, 101.87565882,
       103.33985519, 105.63631456, 108.64972952, 111.86837667,
       114.67115037, 116.69548163, 117.96207449, 118.69589499,
       119.11781077, 119.36770681, 119.51566311, 119.59301667])

z = np.array ([-422.05230434, -408.98182253, -395.78387843, -382.43143962,
       -368.92341485, -355.26851343, -341.47780372, -327.56493425,
       -313.54536462, -299.43740189, -285.26768576, -271.07676026,
       -256.92098157, -242.86416227, -228.95449427, -215.207069  ,
       -201.61590575, -188.17719265, -174.89201262, -161.75452196,
       -148.74812279, -135.85126854, -123.04093538, -110.29151714,
        -97.57502515,  -84.86119278,  -72.1145478 ,  -59.2947726 ,
        -46.36450604,  -33.29821629,  -20.08471733,   -6.72030326,
          6.80047849,   20.48309726,   34.32320864,   48.30267819,
         62.393214  ,   76.56022602,   90.76260159,  104.94787451,
        119.04731699,  132.98616969,  146.71491239,  160.23436159,
        173.58582543,  186.81849059,  199.96724955,  213.05229133,
        226.08870416,  239.09310452,  252.08377421,  265.0769367 ,
        278.08234368,  291.10215472,  304.13509998,  317.18351924,
        330.25976991,  343.38777732,  356.59626164,  369.90725571,
        383.33109354,  396.87227086,  410.5309987 ,  424.2899438])
plt.plot(z,r, label='data');plt.legend()
```
![image](https://user-images.githubusercontent.com/43846417/67760248-4214fa00-fa41-11e9-8c7d-5ed3513bdd0c.png)

### Expected behavior

Afterwards, I use the LobmbScargle on this data:
```
f, a = LombScargle(z, r).autopower()
plt.plot(f, a, label='frequency components');plt.legend()

```
![image](https://user-images.githubusercontent.com/43846417/67760433-9d46ec80-fa41-11e9-836e-e9c1a820a2d2.png)

Similar to a Fourier series, I would like to reconstruct the signal by a sum of sines or cosines.
![image](https://user-images.githubusercontent.com/43846417/67761316-56f28d00-fa43-11e9-82de-a9e157601dc8.png)
Where I am mainly interested in finding a_i and w_i values.
 
Which I do like the following but my reconstruction does not look like the signal for which I had data.

```
s = 0
for i in range(f.shape[0]):
    s += a[i]*np.sin(f[i]*z)
plt.plot(z, s, label='reconstructed signal');plt.legend()
```

### Actual behavior

![image](https://user-images.githubusercontent.com/43846417/67760793-41c92e80-fa42-11e9-90d0-4951975ded21.png)

There should be a mistake in the way I am using LombScargle or the signal reconstruction but I haven't figured out what it is.

### System Details

Linux-5.0.0-31-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Numpy 1.17.0
Scipy 1.3.1
astropy 3.2.3

**Comment by adrn** [comment]
The "power" returned by `LombScargle` (e.g., from `.autopower()` or `.power()`) is not the same as the fourier amplitudes: It is a measure of the likelihood of a sinusoid at a given period or frequency. If you want to reconstruct a time series, you instead have to explicitly fit for the parameters of the sinusoidal expansion of your time series (e.g., [see this docs section](http://docs.astropy.org/en/latest/timeseries/lombscargle.html#the-lomb-scargle-model)).

You probably want to do something like:
```python
ls = LombScargle(z, r)
freq, power = ls.autopower()

# Find the frequency at the highest power
best_freq = freq[power.argmax()]

# Determine the linear model parameters at this frequency
theta = ls.model_parameters(best_freq)

# Construct a design matrix for the time series
design_matrix = ls.design_matrix(best_freq, z)

# Compute the L-S model 
model_r = ls.offset() + design_matrix.dot(theta)

plt.plot(z, r, marker='o')
plt.plot(z, model_r, marker='')
plt.title(f'nterms = {ls.nterms}')
```
![image](https://user-images.githubusercontent.com/583379/67782367-11cc5c00-fa3f-11e9-86c0-9eea6a2b225a.png)


Note that, since your time series is clearly not perfectly sinusoidal, you may want to try with including more terms in the expansion by using, e.g.,
```python
ls = LombScargle(z, r, nterms=5)
```
![image](https://user-images.githubusercontent.com/583379/67782449-2b6da380-fa3f-11e9-9f25-5ff2d355657e.png)

**Comment by a-z-e-r-i-l-a** [comment]
@adrn 

Thanks. Do you know how we can get the a_i and w_i noted in the equation from the design_matrix or theta?
