### ISSUE TITLE
MNT: Rename Planck 2018 when paper is accepted

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9515]
### Description

A direct follow-up of #8111. 

I am tentatively milestoning this to 4.1 so we remember to revisit this in the next release after 4.0. If necessary, please adjust the milestone.

### Additional context

Also see #8006

**Comment by bsipocz** [comment]
Here is the list for the papers. It's still not accepted, so most probably this needs to be pushed to 4.2 (but can wait until the release candidate happens).

https://www.cosmos.esa.int/web/planck/publications

and the arxiv link: https://arxiv.org/abs/1807.06209v2

**Comment by aconley** [comment]
Yeah, I've been checking once a week or so.  I really wish I still had contacts on Planck to ask what in the world is going on!

**Comment by aconley** [comment]
It has been accepted!

However, it doesn't have a journal or page number yet, so at this point I think we should just wait until those are available.  Doesn't look like any changes relative to the preliminary version.

Received: 20 July 2018 / Accepted: 20 March 2020

**Comment by pllim** [comment]
Thanks for the update, @aconley ! Please let us know when we can proceed.

**Comment by pllim** [comment]
@aconley , shall we move the milestone again?

**Comment by bsipocz** [comment]
The papers are now out, so this could go in.

**Comment by aconley** [comment]
Really?  That is exciting.

I wonder if we will ever know what happened there.  As far as I can tell nothing changed...

I will get an update ready.
