### ISSUE TITLE
Provide a way to view pairs of columns in a table as coordinates (or other types)

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#953]
Given a table with columns `ra` and `dec`, it should be possible to get a "virtual" column that views those two columns as `Coordinates`.  This somewhat came out of the discussion about vaopy and also out of the discussion in #945 (#945 talks about using coordinates as `input` to a conesearch -- if we're going to do that, we should also provide an interface to get coordinates as `output` of a conesearch).

**Comment by taldcroft** [comment]
Should be possible with #3011.

**Comment by astrofrog** [comment]
I'm going to close this - as @taldcroft mentioned this is now possible with the mix-in columns!
