### ISSUE TITLE
codecov Github API forbidden

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#9540]
I get an error "GitHub API: Forbidden" if I try to look at the coverage for some file on codecov.io.

The error message mentions that possibly "path fixes in your configuration" are needed.

Example: https://codecov.io/gh/astropy/astropy/src/master/astropy/coordinates/angle_utilities.py

Screenshot:
![Screenshot 2019-11-06 at 11 25 12](https://user-images.githubusercontent.com/852409/68290477-4ddb6e80-0088-11ea-8a5b-694a89da7b62.png)

**Comment by pllim** [comment]
Weird, I don't see what you see. Did you try refresh, just in case?

![Screenshot from 2019-11-06 10-03-21](https://user-images.githubusercontent.com/2090236/68309659-bde3f780-007c-11ea-8ae7-03a4f6526578.png)

**Comment by cdeil** [comment]
Hä? It now works for me, too.

I'm setting up `codecov.io` for Gammapy just now, so I made an account.
Still, I see the Astropy results though whether I'm logged in or not.
Earlier, it wasn't a matter of browser refresh.

Closing this issue. Possibly a temp issue on their side (see https://twitter.com/codecov/status/1191779759706918912) affecting some requests.
