### ISSUE TITLE
Decide if it's acceptable to add the User-Agent:astropy and Accept:*/* headers into file download functions

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9560]
This is a follow-on from #9508, with more details in: https://github.com/astropy/astropy/pull/9508#discussion_r343211648 and https://github.com/astropy/astropy/pull/9508#pullrequestreview-311403515

Short version: we should decide if we want to have `User-Agent:astropy` and `Accept:*/*` in the request headers for *all* uses of `download_file`/`get_readable_fileobj`, or just the IERS (where it is known to be necessary). As of #9508, no change is necessary for the "all" case, so we can close this without PR if agreement is to stick with that.

Relevant text from the HTTP/1.1 spec: is here: https://tools.ietf.org/html/rfc2616#section-14.43 - "User agents SHOULD include this field with requests." The example shown includes a string "libwww" that suggests to me that it is reasonable practice for this header to include "library" information in the header.  So I conclude from this that it the spec is recommending we do things as-is.

cc @pllim @aarchiba @adrn

**Comment by pllim** [comment]
To re-iterate my concern from #9508 , let's say `astroquery` uses `download_file` but didn't customize the HTTP header (either because it is an older release version or it just doesn't care to), the it would be telling the service provider that "user agent" is "astropy" although technically it is really "astroquery". Before the patch, it would be left blank, so it is clear that someone didn't set it.

HTTP spec aside, what is the behavior that *we* want as a core library?

**Comment by adrn** [comment]
We could allow setting this via a config item, and make the default "blank".

**Comment by saimn** [comment]
> Before the patch, it would be left blank

Actually not, it was urllib's user agent.
```
In [23]: with get_readable_fileobj('https://httpbin.org/headers') as f: 
    ...:     print(f.read()) 
Downloading https://httpbin.org/headers
|=========================================================| 125 /125  (100.00%)         0s
{
  "headers": {
    "Accept-Encoding": "identity", 
    "Host": "httpbin.org", 
    "User-Agent": "Python-urllib/3.7"
  }
}
```
And for reference this is with requests:
```
In [25]: print(requests.get('https://httpbin.org/headers').text)                               
{
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.22.0"
  }
}
```

**Comment by saimn** [comment]
So I think it's fine to have "User-Agent:astropy" by default, and even better if it can be customized with a config item or similar. And it should also probably include the version string.

**Comment by bsipocz** [comment]
> And it should also probably include the version string.

yes. and in that case it would be super easy for CI to distinguish itself, e.g. add a `testrun` element for the version string (e.g. that's what we do in astroquery)

**Comment by pllim** [comment]
I started #9564 to implement the config item idea and plan to complete it after #9508 is merged.
