### ISSUE TITLE
Use sources keyword of download_file in IERS

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9561]
I'm not entirely sure if this should be milestoned 4.0, but since it came out of #9508 I thought that was a safer bet.

The gist is: #9508 was merged (or hopefully will be soon...) without using the ``sources`` keyword introduced in #9182, to get master working again.  But the IERS machinery should be re-worked to use ``sources`` since that should be more robust.

cc @pllim @aarchiba @adrn

**Comment by bsipocz** [comment]
I'm removing the milestone as it's not a blocker for the RC.
