### ISSUE TITLE
Change table.cstack to table.dstack before 4.0?

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#9565]
`Table.cstack()` is short for depth-wise stacking, by analogy to `vstack` and `hstack`.  I don't quite remember why it got named `cstack` instead of `dstack`.  I think that `table.cstack` is conceptually similar to `np.dstack` : "Stack arrays in sequence depth wise (along third axis)."

Before the 4.0 release can we just change this?

**Comment by hamogu** [comment]
yes.
