### ISSUE TITLE
No way to silence Bayesian Blocks warning when computing histogram

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9568]
There is no way to silence the following warning (without just filtering it with the warnings module):

```
In [4]: from astropy.stats import histogram                                                                    

In [5]: histogram([1, 2, 3], bins='blocks')                                                                    
WARNING: p0 does not seem to accurately represent the false positive rate for event data. It is highly recommended that you run random trials on signal-free noise to calibrate ncp_prior to achieve a desired false positive rate. [astropy.stats.bayesian_blocks]
Out[5]: (array([3]), array([1., 3.]))
```

This warning is due to the following code in the bayesian blocks implementation:

```
    def __init__(self, p0=0.05, gamma=None, ncp_prior=None):
        if p0 is not None and gamma is None and ncp_prior is None:
            warnings.warn('p0 does not seem to accurately represent the false '
                          'positive rate for event data. It is highly '
                          'recommended that you run random trials on signal-'
                          'free noise to calibrate ncp_prior to achieve a '
                          'desired false positive rate.', AstropyUserWarning)
        super().__init__(p0, gamma, ncp_prior)
```

By default p0 is set and if p0 is set and the other arguments aren't, the warning is emitted. The ``histogram`` function provides no way to set these parameters, resulting in the warning.

In https://github.com/astropy/astropy/issues/4927#issuecomment-311650474, @jakevdp mentioned it might make sense to just remove the warning and describe this in the docs instead. I'm going to also cc @Quantum-cross as the original author of this warning (https://github.com/astropy/astropy/commit/969446239709f539ce878e6e9e5be5a4ad3c03c8). Any suggestions on the best way to proceed?

**Comment by astrofrog** [comment]
For the record, https://github.com/astropy/astropy/pull/9567 is adding a couple of warning filters in some tests for this warning, and these should be removed once this issue is addressed.

**Comment by jakevdp** [comment]
There was another issue about this with a lengthy discussion, which I think resulted in a decision to remove the warning. I can't find it right now...

**Comment by jakevdp** [comment]
OK, here it is: https://github.com/astropy/astropy/issues/4927

My opinion is that this warning should be removed entirely. It is not actionable, and not all that helpful.

**Comment by astrofrog** [comment]
Ok thanks! I'll remove it in #9567

**Comment by bsipocz** [comment]
This has been addressed.
