### ISSUE TITLE
pep8 line length

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#9574]
The *recommended* line length in pep8 (https://pep8.org/#maximum-line-length) of 79 characters is not respected consistently in Astropy, depending on the sub-packages and their original authors. This is slightly annoying when using flake8 in your preferred editor.

The trendy formatting tool *Black* defaults to 88 characters per line, and I was curious to see how many of the flake8 errors it would solve in Astropy. (https://github.com/psf/black#line-length)
Having used Black for some time, increasing the line length from 80 to 88 is often a good way to avoid splitting lines, and is also a good compromise to not have too long lines.

So I made this ([code](https://gist.github.com/saimn/4c4018e1b11ae913d5e4195cdba1d6d0)):
![Figure_1](https://user-images.githubusercontent.com/311639/68521227-bccde880-027d-11ea-93d7-c2888db6ac78.png)

Increasing to 88 chars would remove 72% of the flake8 errors, and would then make it possible to fix the other lines to respect this rule and have a more consistent coding style :).

**Comment by pllim** [comment]
88 means nothing to me unless expressed in miles per hour.

**Comment by bsipocz** [comment]
Yes, please do not do 88 but something that's sensible. Some modules already have 80/100/120, choose one from those.

E.g. we can easily add 120 in the setup.cfg, that would silence flake8, but then the subpackages can still stick to their preference of shorter lines (I would prefer sorter lines as it makes reviewing and coding so much easier).

**Comment by taldcroft** [comment]
I'm certainly one of the most guilty when it comes to longer lines, and the 3 subpackages I maintain all use up to 100 characters.  My rule is to generally try to use lines shorter than 80-85 characters, but there are definitely times when going longer makes the code easier to read IMO.  By the time you are in an `if` block within a class method you are down to 68 available characters. E.g.
```
        column_cls = self.parent_table.Column if (self.parent_table is not None) else Column
```
or
```
        if isinstance(data, MaskedColumn) and np.any(data.mask):
            raise TypeError("Cannot convert a MaskedColumn with masked value to a Column")
```
So I set my flake8 and editor line width at 100 with a soft limit around 80-85.

**Comment by pllim** [comment]
I do almost the opposite of what @taldcroft does. I keep the 79 length limit and insert `# noqa` when I want that line to exceed the limit. I am probably in the minority... 😬

**Comment by taldcroft** [comment]
That's a solution but then the line is 8 characters longer! 😀

**Comment by saimn** [comment]
88 is perfectly sensible, as explained in https://github.com/psf/black#line-length, and also because many people actually try to respect the 80 characters but *sometimes* need a little more. 

But my point is not to discuss about everyone's personal preference, the idea was to see if there is really a need for longer lines based on the current code base. Astropy has ~150'000 lines of code, and the result here is that ~1'500 lines are actually longer than 88 chars (and ~5'500 longer than 80). That's not so much :)

And then, I think this kind of discussion (line length, formatting styles and tools) is useful for a big project like astropy, because consistency helps a lot in understanding code and in minimizing PR diff.
Having formatting changes in a PR is annoying, and having flake8 warnings and errors in the editor is also very annoying for contributors, and blaming contributors with a failing flake8 build is not great either. 
We already started to use isort, I think that it is time to consider yapf or black ;).

**Comment by saimn** [comment]
And I will close since this is not a real issue and will probably not find an agreement here.

**Comment by bsipocz** [comment]
> We already started to use isort, I think that it is time to consider yapf or black ;).

And there  was no agreement on isort either. 
I'm all against black and based on discussions in the past weeks I'm not at all alone with this sentiment amongst maintainers. Sure, let's set up an autopep8 using the same set of error codes we're failing with, etc. but black is anything but constructive for a library.

> blaming contributors with a failing flake8 build is not great either.

we don't blame anyone for long lines, in fact we're way too relaxed with style checks. And to make life easier for casual contributors, I long advocated for using a bot like pep8speak in the core repo. I think that's a nice middle ground, and we indeed use it e.g. astroquery successfully. Setting up something like that for the core however is historically difficult as there are n+1 opinions and preferences about bots commenting, etc.
