### ISSUE TITLE
UnitsError while running tests in dev version 4.x

### ISSUE THREAD

**Issue by tcassanelli** [astropy/astropy#9584]
### Description

While running tests in Travis CI I noticed that the developer version of Astropy fails in a test that previously didn't. The issue appeared while debugging other problem in the developer version using the [astropy-package-template](https://github.com/astropy/package-template/issues/435). The problem raises the exception `UnitsError`, and complains about two sets of `numpy.ndarray` that *should* have the same units, but for some reason in the developer version they don't.

There are three scripts that fail in those tests, for example while running [`test_aperture.py`](https://github.com/tcassanelli/pyoof/blob/master/pyoof/aperture/tests/test_aperture.py):

```python
import pytest
import numpy as np
from astropy import units as apu
from astropy.units import Quantity
from astropy.tests.helper import assert_quantity_allclose
from astropy.utils.data import get_pkg_data_filename
from astropy.utils.misc import NumpyRNGContext
from numpy.testing import assert_allclose
import pyoof

.
.
.

def test_radiation_pattern():

    _u, _v, _radiation_pattern = pyoof.aperture.radiation_pattern(
        K_coeff=K_coeff,
        I_coeff=I_coeff,
        d_z=d_z,
        wavel=wavel,
        illum_func=pyoof.aperture.illum_pedestal,
        telgeo=telgeo,
        resolution=2 ** 8,
        box_factor=5
        )

    data_radiation_pattern = np.load(
        get_pkg_data_filename('data/radiation_pattern.npz')
        )
    u_true = data_radiation_pattern['u']
    v_true = data_radiation_pattern['v']
    radiation_pattern_true = data_radiation_pattern['F']

    assert_allclose(_radiation_pattern, radiation_pattern_true)
    assert_quantity_allclose(_u, Quantity(u_true, apu.rad))
    assert_quantity_allclose(_v, Quantity(v_true, apu.rad))
```
Then the output of running that test returns

```
======================================================= FAILURES ========================================================
________________________________________________ test_radiation_pattern _________________________________________________

actual = <Quantity [-2.38897115e-03, -2.37030731e-03, -2.35164348e-03,
           -2.33297964e-03, -2.31431580e-03, -2.29565196...03,  2.29565196e-03,
            2.31431580e-03,  2.33297964e-03,  2.35164348e-03,
            2.37030731e-03] rad / m>
desired = <Quantity [-2.38897115e-03, -2.37030731e-03, -2.35164348e-03,
           -2.33297964e-03, -2.31431580e-03, -2.29565196...13e-03,  2.29565196e-03,
            2.31431580e-03,  2.33297964e-03,  2.35164348e-03,
            2.37030731e-03] rad>
rtol = 1e-07, atol = None
```
which is a `UnitsError `, but `_u` and `_v` outputs from `pyoof.aperture.radiation_pattern ` should have changed units only to radians. Again, this seems to work fine under older Astropy versions but now it fails.

### Steps to Reproduce

To reproduce the error that I saw on Travis CI, I installed the developer version of astropy in a `conda` environment. Both of them, Travis and under cloning the astropy dev version fail.
* For Travis CI you can see the error [here](https://travis-ci.org/tcassanelli/pyoof/jobs/609290259)
* Installing source [`pyoof`](https://github.com/tcassanelli/pyoof), clone the master branch and install in the same environment the Astropy version 4.x (developer version). 

```bash
git clone https://github.com/tcassanelli/pyoof
python setup.py install
```
if `install` doesn't work try the flag `--user`. Then simply run the tests
```bash
python setup.py test
```
or in particular the `test_aperture.py` file,
```bash
python setup.py test -t pyoof/aperture/tests/test_aperture.py
```

### System Details

```python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Darwin-18.7.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.17.3
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.3.2
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.0.dev0
```

**Comment by pllim** [comment]
> `pyoof.aperture.radiation_pattern` should have changed units only to radians

Shouldn't this be an issue over at `pyoof`?

**Comment by pllim** [comment]
Probably due to how `pyoof` is handling units here:

https://github.com/tcassanelli/pyoof/blob/becb434c8a754feb20294881bae55d94acc1b4c5/pyoof/aperture/aperture.py#L515-L521

**Comment by pllim** [comment]
My suspicion is that `np.fft.fftshift(u)` now has the unit of `1 / Angstrom`, resulting in your result having an extra `1/m` that you didn't expect before. You need to handle this downstream in `pyoof`, it seems. Hope this clarifies the matter!

**Comment by tcassanelli** [comment]
Thank you @pllim, I think I understand more the issue now. This happens when using `np.fft.fftshift`, for previous Astropy versions this functions removes entirely the `Quantity`, but now it preserves it. I will make a workaround for newer Astropy versions in pyoof.
