### ISSUE TITLE
Warning in Time.argsort when scale='utc'

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9587]
In #9545 I fixed a warning that occurred when calling ``argsort`` on ``Time`` objects, and this fixed the warnings for all scales except ``utc``:

```
In [1]: from astropy.time import Time                                                                                

In [2]: t = Time([1, 2, 3], format='mjd')                                                                            

In [3]: t.argsort()                                                                                                  
WARNING: ErfaWarning: ERFA function "utctai" yielded 3 of "dubious year (Note 3)" [astropy._erfa.core]
Out[3]: array([0, 1, 2])
```

In a recent PR, I expanded the test in astropy.time and marked the above case as xfail:

https://github.com/astropy/astropy/commit/845651caf743f5686f951c9e5f3e596c1705783c#diff-4ef257cd7d0e1ebe9915d2c99d8074b5R387

@mhvk - any ideas how to fix this one?

**Comment by mhvk** [comment]
These are dubious years!  Just just `Time(50000, [1, 2, 3], format='mjd')` and it should all work.

**Comment by astrofrog** [comment]
@mhvk - I agree that they are dubious to some extent, but shouldn't sorting work anyway?

In general, I think we should also make an effort to improve these error messages. First, what is a range of non-dubious years? Then what does dubious mean? It'd be much better if there was a warning along the lines of 'The utc time scale is not well defined before ... and after ... due to the lack of leap second information' or something like that?

**Comment by mhvk** [comment]
Yes, very true - it is one thing for the creation to possibly raise an error, but a bit strange for sorting to do so - it is unambiguous after all! Though the code may get less clean...  Anyway, good to have this issue to remind us to find a better solution.

**Comment by bsipocz** [comment]
I don't see this warning anymore, so closing the issue. Do reopen if you still run into it.
