### ISSUE TITLE
Distance issues a warning when input contains NaN

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#9597]
### Description
Supplying `astropy.coordinates.distance.Distance` with a NaN value raises a warning, but I don't think it should since having a NaN value is perfectly reasonable.

### Expected behavior
No warning.

### Actual behavior
```python
/miniconda3/lib/python3.7/site-packages/astropy/coordinates/distances.py:181: RuntimeWarning: invalid value encountered in less
  if not allow_negative and np.any(distance.value < 0):
```

### Steps to Reproduce

```python
from astropy.coordinates.distances import Distance
import numpy as np
import astropy.units as u

data = [0, np.nan, 1] * u.m
Distance(data)
```

### System Details

Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.5 (default, Oct 25 2019, 10:52:18) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.17.3
Scipy 1.3.1
astropy 3.2.3

**Comment by adrn** [comment]
Thank you for providing a copy-pasteable example! 🙏 

Out of curiosity, what is the argument for permanently silencing the warning (in #9598) as opposed to doing, e.g.:
```python
with np.errstate(invalid='ignore'):
    d = Distance(data)
```
?

**Comment by dstansby** [comment]
I think having a NaN distance is a perfectly reasonable thing to do, so a user shouldn't have to continually catch the warning themselves in their own code (similarly I think it's reasonable to have a NaN in a `Quantity`, and that doesn't emit a warning).

**Comment by eteq** [comment]
I'm 👍 to fixing this now that you pointed it out @dstansby.  Particularly sensible in the context of #7988 since there we explicitly opted-in to using NaN distances for negative parallax.
