### ISSUE TITLE
Unleash the walrus when Python minversion is 3.8

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9606]
### Description

Take advantage of the `:=` (walrus) operator when our minversion of Python is 3.8. 

### Additional context

https://www.python.org/dev/peps/pep-0572/

https://www.youtube.com/watch?v=6uAvHOKofws

p.s. Khoo khoo kachu!

**Comment by bsipocz** [comment]
Too bad we don't have adequate emoji, these are the only sea mammals I found: 🐳 🐋

**Comment by shbhuk** [comment]
Please don't!

**Comment by pllim** [comment]
@shbhuk , can you please elaborate?

**Comment by taldcroft** [comment]
I can't wait, this will be almost as good as f-strings. The lack of walrus was the second thing I missed when I was transitioning from perl (after inline string formatting, which we now have and better!).

**Comment by pllim** [comment]
I don't remember what this issue was for anymore. Now that I re-read this, it is way too vague... 😅 

And seems like walrus is moving in naturally, as #12147 shows, so let's close this.
