### ISSUE TITLE
cache issue: dbm.error: db type is dbm.gnu, but the module is not available

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9607]
I switched from one Python environment to another (pip-based to conda-based) and ended up with the following error when trying to run a script:

```
WARNING: /home/tom/Code/astropy/examples/io/fits-tables.py failed to execute correctly: Traceback (most recent call last):                                                                             
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/home/tom/Code/astropy/examples/io/fits-tables.py", line 35, in <module>
    event_filename = get_pkg_data_filename('tutorials/FITS-tables/chandra_events.fits')
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/astropy/utils/data.py", line 627, in get_pkg_data_filename
    conf.dataurl_mirror + data_name])
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/astropy/utils/data.py", line 1186, in download_file
    pkgname=pkgname)
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/astropy/utils/data.py", line 1819, in import_file_to_cache
    with _cache(pkgname, write=True) as (dldir, url2hash):
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/astropy/utils/data.py", line 1642, in _cache
    shelve.open(urlmapfn, flag="c") as url2hash:
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
```

I wonder if this should just be a warning and result in the file being re-downloaded rather than have a hard failure like this? I don't think the average user would realize the best fix is to remove the cache.

cc @aarchiba

**Comment by pllim** [comment]
xref #9182 and maybe #9594

**Comment by aarchiba** [comment]
You're absolutely right and it should just be a warning. In fact I thought it would already do just what you suggest; thank you for demonstrating that it doesn't. I'll take a look at why not and see if I can fix it. I'd like to make the warning message more explicit - suggest that the user zap the cache and start over, or use export/import - but it's quite awkward as the dbm module collapses all exceptions down to a single type. I'll see what I can do.

**Comment by pllim** [comment]
@aarchiba , if modifying the warning message is too complicated, another option is to add an entry about this in https://github.com/astropy/astropy/blob/master/docs/known_issues.rst . FYI.

**Comment by bmorris3** [comment]
This is a problem for an astroplan user in astropy/astroplan#432 – am I interpreting the thread above correctly that the solution might be to run
```python
from astropy.utils.data import clear_download_cache
clear_download_cache()
```
? Thanks.

**Comment by aarchiba** [comment]
Yes, running astropy.utils.data.clear_download_cache() will remove the entire cache, and as the new cache is used it will be reconstructed using whatever libraries are available to the user's current installation of astropy.

**Comment by ZacharyJennings** [comment]
I have recently deleted my anaconda files with the intent to re-download anaconda because my old one wasn't downloading anything properly. It would sit in the "solving environment" stance for hours. 
Long story short, I now get this same error message in a number of my scripts. Using the fix above has worked, but I wonder, does this mean I am now going to have to include that line in every code?

**Comment by pllim** [comment]
> does this mean I am now going to have to include that line in every code?

Hello. We apologize for any inconvenience caused. Resetting the cache should be a one-time thing, but if you find otherwise, please open a new issue and provide all the information asked for in the bug report template. Thanks!

**Comment by ZacharyJennings** [comment]
Hi,

If it was supposed to be a one-time thing then that is fine. I have done it once and things seem to be going fine.

Out of interest, including the reset cache line in my code has caused it to speed up and therefore, do you recommend against resetting the cache every time I run a code or should this be fine?

Cheers,
Zac
________________________________

**Comment by pllim** [comment]
@ZacharyJennings , resetting cache making it faster is counter-intuitive for me, as cache is supposed to prevent download of the same file over and over again, hence speeding it up. Personally, I wouldn't recommend you clear your cache every run. If you wish to discuss this further, please open a new issue explaining your particular use case (HPC or not, OS, etc etc).

**Comment by ZacharyJennings** [comment]
Ok, I will take note,
Thank you for your reply.
________________________________
