### ISSUE TITLE
FITS header "CONTINUE" keyword is now part of the FITS standard

### ISSUE THREAD

**Issue by demitri** [astropy/astropy#9610]
### Description

In the documentation [here](https://docs.astropy.org/en/stable/io/fits/usage/headers.html#continue-cards) it notes that `CONTINUE` keywords are not part of the FITS specification, but are supported by Astropy. This is no longer true; the proposal is now officially part of the 4.0 standard. For details, see Section 4.2.1.2 of [the specification](https://fits.gsfc.nasa.gov/fits_standard.html).

As noted in the docs, the convention is supported in Astropy, but it would be nice to update them to reflect that it is part of the format.

I also recently encountered a `fits.VerifyError` warning, saying that the`CONTINUE` keyword is invalid and it was inserting a missing "=" character (which is not present with the `CONTINUE` keyword), but I can't find it in the source so maybe that has been removed.

**Comment by msrdinesh** [comment]
Hey, I am a student and would to contribute to the project. I have created a pull request for the issue, please look at it. [9751](https://github.com/astropy/astropy/pull/9751)

**Comment by pllim** [comment]
Update: Documentation is clarified in #9475 

However, the report on `VerifyError` might need a standalone code snippet so others can attempt to reproduce the problem.

**Comment by saimn** [comment]
With #9751 merged, addressing the documentation issue, I would be tempted to close this. We can address the `VerifyError` in another ticket if you have a way to reproduce @demitri ?
