### ISSUE TITLE
Incorrect 'Daylight Saving Time' change for Kitt Peak Observatories

### ISSUE THREAD

**Issue by shbhuk** [astropy/astropy#9618]
### Description
Kitt Peak National Observatory in Arizona is on Mountain Standard Time. However, unlike the standard US convention, it does not follow Daylight Savings Time. Therefore, the UTC Offset for the observatory remains constant at -7 hours throughout the year, and it does not oscillate back and forth twice a year due to  historical idiosyncrasies. 

### Expected behavior
The UTC offset is -7 throughout the year, therefore it is Mountain Standard Time in the winter months, and on Pacific Time in the summer.

### Steps to Reproduce

```python
from astropy.coordinates import EarthLocation
from astropy.time import Time
import datetime
import pytz

location = EarthLocation.of_site('KPNO')
timezone = location.info.meta['timezone'] # The output of this is 'US/Mountain' which is technically correct, if not for the fact that there is this sub-zone of regions within this timezone which remains fixed w.r.t to UTC and does not follow the Daylight Saving sham. 

print('December offset = {}'.format(pytz.timezone(timezone).localize(Time('2019-12-1').datetime).strftime('%z'))) #This outputs -7 hrs which is correct
print('April offset = {}'.format(pytz.timezone(timezone).localize(Time('2020-04-1').datetime).strftime('%z'))) #This outputs -6 hrs which is incorrect
```

### System Details

Windows-10-10.0.17763-SP0
Python 3.5.2 |Enthought, Inc. (x86_64)| (default, Mar  2 2017, 16:37:47) [MSC v.1900 64 bit (AMD64)]
Numpy 1.17.3
Scipy 1.0.0
astropy 3.2.3
pytz 2019.3

**Comment by pllim** [comment]
Not sure if there is anything this repo can do about it. The timezone is set in https://github.com/astropy/astropy-data/blob/8609ae3d670c2fc52c65f65ea1300af766559dbe/coordinates/sites.json#L337 and you appear to be using `pytz` software that is not part of this repo.

I did find someone compiled a list of `pytz` timezone strings at https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568 . Maybe @eteq or @adrn can clarify.

**Comment by shbhuk** [comment]
Hi @pllim ,
You are correct. The Time zone entry is correct in principle for the observatory. Perhaps an if statement is required somewhere to toggle back and forth? 

Not sure what's the best way to fix it. In the least could we add a warning statement so that this is something that users are aware of.

**Comment by shbhuk** [comment]
Changing the time zone for KPNO to 'US/Arizona' will also work. This timezone does not change its UTC offset

**Comment by pllim** [comment]
@shbhuk , changing the timezone value would be cleaner, IMHO. Do you want to propose the change as a pull request over at https://github.com/astropy/astropy-data ? Thank you for bringing this to our attention!

**Comment by shbhuk** [comment]
The same change should be made in https://github.com/astropy/astropy-data/pull/56

**Comment by bsipocz** [comment]
The astropy-data PR has been merged, so I'm closing this issue now.

Thanks @shbhuk!

**Comment by shbhuk** [comment]
Should I submit a new pull request to add the WIYN telescope, and the Hobby Eberly Telescope at McDonald Observatory?
