### ISSUE TITLE
Incorrect derivative in Defining New Model Classes documentation

### ISSUE THREAD

**Issue by Richardjmorton** [astropy/astropy#9630]
Hi, maybe I am missing something, but I believe the 'Defining New Model Classes' example (https://docs.astropy.org/en/stable/modeling/new.html) in the documentation has the incorrect derivatives for the 1DGaussian function. This comes under the section 'A step by step definition of a 1-D Gaussian model'.

 For the Gaussian defined as:

amplitude * np.exp((-(1 / (2. * stddev**2)) * (x - mean)**2))

The derivatives should be:

d_amplitude = np.exp((-(1 / (2.*****stddev**2)) * (x - mean)**2))
d_mean = (amplitude *
              np.exp((-(1 / (2.*stddev**2)) * (x - mean)**2)) *
              (x - mean) / (stddev**2))
d_stddev = (amplitude *
                np.exp((-(1 / (2.* stddev**2)) * (x - mean)**2)) *
                ((x - mean)**2) / (stddev**3))

In the online example, the factor of 2 multiplying stddev inside the exponential is missing - for all derivatives. And the factor of two multiplying the amplitude (in d_mean and d_stddev) should not be there. Online version is:

d_amplitude = np.exp((-(1 / (stddev**2)) * (x - mean)**2))

d_mean = (2 * amplitude *
              np.exp((-(1 / (stddev**2)) * (x - mean)**2)) *
              (x - mean) / (stddev**2))

d_stddev = (2 * amplitude *
                np.exp((-(1 / (stddev**2)) * (x - mean)**2)) *
                ((x - mean)**2) / (stddev**3))

**Comment by nden** [comment]
Thanks for pointing this out. It appears the actual code in `functional_models.py` is correct but the example here is wrong. Will fix it shortly.
