### ISSUE TITLE
radial_velocity_correction fails for a SkyCoord with differentials

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9645]
If I run the following snippet:
```python
from astropy import units as u
from astropy.coordinates import SkyCoord, EarthLocation
from astropy.time import Time

sc = SkyCoord(10*u.deg, 20*u.deg, distance=5*u.pc, 
              pm_ra_cosdec=0*u.mas/u.yr, pm_dec=0*u.mas/u.yr, radial_velocity=0*u.km/u.s)
sc.radial_velocity_correction(obstime=Time.now(), location=EarthLocation.of_site('example_site'))
```
The result is this error:
```
TypeError: Operation 'sub' is not supported when differentials are attached to a CartesianRepresentation.
```
Probably there just needs to be a without_differentials somewhere, but reporting it now in case I can't get to it soon.

**Comment by eteq** [comment]
(cc @nmearl as it turned up while working on astropy/specutils#524)

**Comment by shreyasbapat** [comment]
Hi @eteq , I would like to work on this :D

**Comment by shreyasbapat** [comment]
This is the line which causes the error: 

```
self._raise_if_has_differentials(op.__name__)
```

I tried to remove this line, and I had success, do you think this is the right thing t do?

**Comment by StuartLittlefair** [comment]
This is something I've wanted to fix for a while now, but the answer is not to drop the differentials, since the star's own motion has a (tiny) effect on the desired correction...
