### ISSUE TITLE
Option to show table column descriptions in show_in_notebook()

### ISSUE THREAD

**Issue by hcferguson** [astropy/astropy#9660]
### Description

It would be nice to have the ability to reveal the column descriptions in the table headers if they are there. I'd probably put this as the default, but if not, it would be good to at least include it as an option.

### Additional context

As far as I can tell the only way to see the column descriptions is with table.info() or by introspecting or saving to a format that saves the metadata. At least one of the print options ought to have the ability to put the descriptions in the header. `show_in_notebook` and even `show_in_browser` seem like the simplest solution, since it could be implemented as a keyword option.

**Comment by taldcroft** [comment]
My main concern on this is that in my experience the "description" tends to be on the long side and so putting it into the table header will generally make the plaintext render of the table useless.  However, for HTML-based output, one could imagine having a hover-over on the column name that provides the description if available.

FYI, the following location is where one might go to add an option to show description in the header:

https://github.com/astropy/astropy/blob/918abcd480acdf824c5e5d856daf0573811d9b3c/astropy/table/pprint.py#L364

**Comment by hcferguson** [comment]
I like the idea of a hover option.
