### ISSUE TITLE
DOC: Require PR author to add What's New entry

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9676]
### Description

Going forward (v4.1 and beyond), it is proposed that PR authors should add their own What's New entries as part of the original PRs. This is because having to compile the What's New entries right before a release adds a lot of unnecessary overhead, plus stress of unable to have the original authors add the entries in time.

### Additional context

xref #9581

cc @astropy/coordinators , @bsipocz

**Comment by astrofrog** [comment]
I would like to see this happen 👍 (I'm not sure what the right place to document this is)

**Comment by pllim** [comment]
I am thinking contributor guideline, and maybe have bot logic to check for what's new when we add a "what's new needed" label on the PR?

**Comment by bsipocz** [comment]
The only downside I see (well, there are tons of advantages) is that sometimes we weed out excess labels close to release, when we see what are the actual major new points in a release. However, what's news are not that long, we can easily remove the superfluous sections before releasing.

**Comment by mhvk** [comment]
Should it be the PR author, or the reviewer? Advantage of the latter is that it has a more objective view.

Note that in principle the changelog entry itself should suffice - we could just ask for a longer one for things that are particularly interesting and then auto-collate them.

**Comment by bsipocz** [comment]
I don't think a changelog would be enough, that would be nicer to keep that in a "telegram style" e.g  "new timeseries class is added" versus a half a page summary of the new functionality showcasing the highlights from the docs.

**Comment by eteq** [comment]
We should finalize this by the 4.1 feature freeze if we can so that it will apply to the 4.2 release cycle (can't post-apply it to things going into the 4.1 release)

**Comment by eteq** [comment]
Some discussion from the dev telecon on 4/1/20: Instead of requiring it at merge-time, we say what's new entries are part of "features" and therefore the feature freeze deadline will apply for that.

**Comment by eteq** [comment]
Since the 4.1 feature freeze is turning out to be a two-stage freeze (regular freeze for PRs, following week for reviews), I'd say the comment from https://github.com/astropy/astropy/issues/9676#issuecomment-607482741 applies to the *second* stage, since What's new entries might depend on the result of reviews.

**Comment by astrofrog** [comment]
> Should it be the PR author, or the reviewer? Advantage of the latter is that it has a more objective view.

The author IMHO - if I know I'm going to have to write a what's new entry for a PR, it might make me think twice about reviewing it! But the reviewer can take a careful look at it?

**Comment by pllim** [comment]
I don't think https://github.com/astropy/astropy/issues/9676#issuecomment-619188118 worked. We need to do a post-release post-mortem.

**Comment by pllim** [comment]
How are we going to do this for 4.2?

**Comment by bsipocz** [comment]
I don't see it's happening, so I'm removing the milestone.

**Comment by astrofrog** [comment]
I still feel strongly that for obvious major new features the what's new entry should be added during the PR. Maybe this could just be a new checkbox in the PR checklist as well as an email to astropy-dev so that all devs/maintainers are on the same page. There's really no reason to delay it - we require docs and tests and changelog entries so this is just one other thing to require - no reason to procrastinate :smile:

**Comment by pllim** [comment]
Does  #12813 kinda resolve this issue?

**Comment by hamogu** [comment]
I agree. I just did not get around to open the issues about bots, but I see the @nstarman has done that in the meantime, so closing this issue. We don't want multiple issues open for the same idea.
