### ISSUE TITLE
TST: Dangling file pointer in wcsaxes tests

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9686]
### Description

Is there a way to fetch HDU for `wcsaxes` tests without keeping the file pointer open?

https://github.com/astropy/astropy/blob/2c8d84e1745ee2068a47d92c4de8b45704ba9914/astropy/visualization/wcsaxes/tests/datasets.py#L16-L21

### Additional context

I see `ResourceWarning: unclosed file` when I run `visualization.wcsaxes` tests.

**Comment by saimn** [comment]
From all those function in `datasets.py` I see only two uses of `fetch_msx_hdu` (which is a bit surprising), and only for `.data` is used. So it would be easy to replace this with a function that returns the data array with `fits.getdata`.
```
❯ rg "fetch_.*_hdu" astropy/visualization/       
astropy/visualization/wcsaxes/tests/test_images.py
109:        hdu_msx = datasets.fetch_msx_hdu()
140:        hdu_msx = datasets.fetch_msx_hdu()

astropy/visualization/wcsaxes/tests/datasets.py
8:__all__ = ['fetch_msx_hdu',
9:           'fetch_rosat_hdu',
10:           'fetch_twoMASS_k_hdu',
11:           'fetch_l1448_co_hdu',
12:           'fetch_bolocam_hdu',
24:def fetch_msx_hdu():
35:def fetch_rosat_hdu():
39:def fetch_twoMASS_k_hdu():
43:def fetch_l1448_co_hdu():
47:def fetch_bolocam_hdu():
```

**Comment by pllim** [comment]
Not sure what the original intention was. Seems like it was ported from existing code even back in #5496 . Do you remember, @astrofrog ?

**Comment by astrofrog** [comment]
Yeah this could be simplified, I think it dates back to before wcsaxes was in the core package and when the remote data was not hosted on the astropy server.
