### ISSUE TITLE
Make table's `Row` a mapping?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#9687]
Right now, `Row` is registered as a `collections.abc.Sequence`, but arguably it makes more sense as a `Mapping`, since the way `__getitem__` is implemented is much more like a `dict`. Indeed, `Row` could gain `keys()`, `items()`, and `.values()` methods which would make it very similar to a `dict` (and allow "splatting" with `**row`). The only inconsistency might be in `Row.__iter__`, which currently iterates over values rather than keys.

**Comment by cdeil** [comment]
In Gammapy we defined a helper function `table_row_to_dict`:

https://github.com/gammapy/gammapy/blob/0299a71a955b07f7d00407263dd6541d77a8512b/gammapy/utils/table.py#L46-L67

Probably any change you make to `Row` itself will be a no-go or heavily opposed for backward compat reasons. But adding a helper method, or at least docs, for this, I think would be wonderful.

**Comment by mhvk** [comment]
@cdeil - good points.  I'm not sure that anybody is actually using the iteration over values - but agree about the worry about back compatibility. And perhaps it is possible for `**row` and iteration by value to work both...  Anyway, as you say, the minimum would be to at least be able to create a dict from a row. cc @taldcroft

**Comment by saimn** [comment]
I think there was this idea with the "iterrows" method (#8969), which could have a keyword to specify if it should return a tuple of values (like now) or a dict or something else.

**Comment by mhvk** [comment]
Indeed, and `itercolumns()` was implemented. I should be clearer that what I'd really like to work here is `**row`. I think I should just look at what that would take and how, if anything, would actually break.

**Comment by taldcroft** [comment]
Sounds like a good idea, in principle, but as said we need to be careful about breakage and making assumptions about how people use the Row object.  I would be quite surprised if there is no code out there like:
```
>>> t = simple_table()
>>> tuple(t[0])
(1, 1.0, 'c')
```
But simply adding dict-like methods seems beneficial and wouldn't break anything.

**Comment by taldcroft** [comment]
What's actually required for `**row` to work?  Does it need to be a Mapping or just have `.items()`?

**Comment by mhvk** [comment]
Actually, it looks like all that is needed is to add a `keys()` method! And no tests fail if I add that. I'll make a quick trial PR.

**Comment by mhvk** [comment]
See #9712
