### ISSUE TITLE
visualization's norms should ignore nan by default

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#9689]
astropy.visualization's norm operations break when given any NaN input by default.  It would be much more reasonable to have them ignore NaNs by default.

example:
```
x = np.random.randn(5,5)
x[2,2] = np.nan
logn = visualization.ImageNormalize(stretch=visualization.LogStretch(), interval=visualization.PercentileInterval(99.95))
bad = logn(x) # logn now has vmin, vmax = nan
```
The right approach would have vmin, vmax be determined using, e.g., `nanpercentile` instead of `percentile` under the hood.  Presumably this affects some (but I haven't checked if it hits all) interval & stretch measurers.  

This could be a lot of work and could have performance implications, but usually with visualization tools the stats aren't the bottleneck.

Up to someone else to evaluate whether this is a feature request or a bug report.  I suspect this should be a pretty easy fix, but I'd like to see discussion here about whether there are good reasons to avoid the `np.nan<stat>` methods.

**Comment by pllim** [comment]
@keflavich , to go with the "Effort-low" label, please also add whether the effort was estimated for "novice", "intermediate", or "expert". This is because an issue that may take very little effort from an expert will not be so for someone new to `astropy` code base. Thank you.

**Comment by keflavich** [comment]
:+1: good call.  If I understand the problem correctly, it's well suited to a novice.

**Comment by astrofrog** [comment]
I thought I recalled @larrybradley fixing something like this. Just to check is this with master?

**Comment by pllim** [comment]
I see this with 4.0rc1

```python
In [6]: bad
Out[6]:
masked_array(
  data=[[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=1e+20)
```

**Comment by pllim** [comment]
@astrofrog , if you are thinking of #9480, looks like it only handles `inf`.

**Comment by keflavich** [comment]
Thanks for checking @pllim. Indeed, I didn't check against master, only against the latest conda build.  I need some help getting my mac to compile astropy again after a malicious mac os update... I'll ask in Socorro if I don't find a fix by then.

**Comment by pllim** [comment]
Just for completeness, same with astropy 4.1.dev27042

```python
masked_array(
  data=[[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=1e+20)
```

**Comment by astrofrog** [comment]
#9480 was supposed to handle NaNs too:

https://github.com/astropy/astropy/pull/9480/files#diff-80a82776aca2a864d58a160c7e2bb880R107

(at least it was just adding filtering of inf and keeping filtering of nan). But there must be some missing cases it seems.
