### ISSUE TITLE
4.0 rc1: Can't disable deprecation errors

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#9690]
On the Debian build, I want/need to disable the interpretation of deprecation warnings as error. This is required, since currently some modules issue deprecation warnings with Python 3.8, and generally they are too strict to have them as failures since they then prevent upgrading some packages.
I currently disable the deprecation warnings with a [small patch](https://salsa.debian.org/debian-astro-team/astropy/blob/0c0dc533b9307d51379668c1a4aa71c680708224/debian/patches/Ignore-deprecation-failures-in-test.patch) which removes these lines: 
https://github.com/astropy/astropy/blob/aad16d652d8d3897e7f51dc54590e2974df35564/astropy/conftest.py#L25-L30

This however seems not to disable everything; even with this patch I can't run the tests (during build time):
```
I: pybuild base:217: cd '/build/astropy-4.0~rc1/.pybuild/cpython3_3.8/build'; python3.8 -m pytest 
============================= test session starts ==============================
platform linux -- Python 3.8.0+, pytest-4.6.6, py-1.8.0, pluggy-0.13.0
Matplotlib: 3.0.2
Freetype: 2.10.1
rootdir: /build/astropy-4.0~rc1, inifile: setup.cfg
plugins: arraydiff-0.3, remotedata-0.3.2, astropy-header-0.1.1, mpl-0.10, openfiles-0.4.0, doctestplus-0.5.0
collected 0 items / 1 errors

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/lib/python3/dist-packages/_pytest/config/__init__.py:440: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('/build/astropy-4.0~rc1/.pybuild/cpython3_3.8/build/astropy/conftest.py')

During handling of the above exception, another exception occurred:
/usr/lib/python3/dist-packages/py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
/usr/lib/python3/dist-packages/py/_path/common.py:418: in gen
    dirs = self.optsort([p for p in entries
/usr/lib/python3/dist-packages/py/_path/common.py:419: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
/usr/lib/python3/dist-packages/_pytest/main.py:667: in _recurse
    ihook = self.gethookproxy(dirpath)
/usr/lib/python3/dist-packages/_pytest/main.py:482: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
/usr/lib/python3/dist-packages/_pytest/config/__init__.py:424: in _getconftestmodules
    mod = self._importconftest(conftestpath.realpath())
/usr/lib/python3/dist-packages/_pytest/config/__init__.py:474: in _importconftest
    self.consider_conftest(mod)
/usr/lib/python3/dist-packages/_pytest/config/__init__.py:527: in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
/usr/lib/python3/dist-packages/_pytest/config/__init__.py:321: in register
    ret = super(PytestPluginManager, self).register(plugin, name)
/usr/lib/python3/dist-packages/pluggy/manager.py:126: in register
    hook._maybe_apply_history(hookimpl)
/usr/lib/python3/dist-packages/pluggy/hooks.py:333: in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:92: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:83: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
astropy/conftest.py:35: in pytest_configure
    matplotlibrc_cache.update(matplotlib.rcParams)
/usr/lib/python3/dist-packages/matplotlib/__init__.py:886: in __getitem__
    cbook.warn_deprecated(
/usr/lib/python3/dist-packages/matplotlib/cbook/deprecation.py:112: in warn_deprecated
    warnings.warn(message, category, stacklevel=2)
E   matplotlib.cbook.deprecation.MatplotlibDeprecationWarning: 
E   examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.20 seconds ============================
E: pybuild pybuild:341: test: plugin distutils failed with: exit code=2: cd '/build/astropy-4.0~rc1/.pybuild/cpython3_3.8/build'; python3.8 -m pytest 
dh_auto_test: pybuild --test --test-pytest -i python{version} -p "3.8 3.7" returned exit code 13
```
I am not sure whether I did something wrong; however I don't see how I could disable them otherwise. I also must admit that I don't understand the warning. I also don't understand the key error on top.
Matplotlib version is 3.0.2, built for both Python 3.8 and 3.7.

**Comment by mhvk** [comment]
It may be that the defaults changed as we turned on exceptions for warnings in `pytest`; you could try to remove the `error` line in `setup.cfg` under `filterwarnings` in the `[tool:pytest]` section. Or add deprecation warnings there.

But I must admit I am guessing, so cc @astrofrog and @pllim.

**Comment by pllim** [comment]
Interesting. In CI and on my machine, I see that warning but it does not trigger an error in collection with the current set up. If you add
```
    ignore:examples.directory is deprecated
```
under
https://github.com/astropy/astropy/blob/aad16d652d8d3897e7f51dc54590e2974df35564/setup.cfg#L107

does it fix the problem?

**Comment by pllim** [comment]
As for the warning, I reported it at https://github.com/matplotlib/matplotlib/pull/12658#issuecomment-497013309 but I haven't seen any resolution yet.

**Comment by astrofrog** [comment]
For that particular warning I think we should just catch it in ``conftest.py`` with a ``with warnings.catch_warnings...``

**Comment by olebole** [comment]
Adding `ignore:examples.directory is deprecated` to `filterwarnings` didn't help; it still stopped on the same place. With the removal of the `error` line, it worked.

**Comment by mhvk** [comment]
@astrofrog, @pllim - bit off-topic, but now that we normally error on all warnings, should we remove the `enable_deprecations_as_exceptions` stanza? Presumably we can do that with `filterwarnings` directly (at least for ourselves!). It removes one more item from `astropy_helpers`...

**Comment by astrofrog** [comment]
@mhvk - yes we can remove it for the core package but this functionality is still imported by other packages so we can't really remove it yet. I'd like to see other packages also define the warning/error behavior in setup.cfg like we do for the core package now, but we'll need a while to transition.

**Comment by mhvk** [comment]
:+1: - though this suggests perhaps we need a "what's new for affiliated packages" page? Maybe good to do with the move away from `astropy_helpers`.. Is there a tracking issue for that?

**Comment by olebole** [comment]
Just deprecate it? Is there a  policy on that? (like: for the next major version)

**Comment by mhvk** [comment]
Yes, we do have a policy (some APE...) - ideally we deprecate in LTS and then remove in the next major version.

Which brings up the more immediate question: should we remove `enable_deprecations_as_exceptions` in current astropy's `conftest.py`? There would seem to be nothing from stopping us, or am I mistaken?

**Comment by pllim** [comment]
@mhvk , if you mean putting it into 4.0, I am afraid it is too late. Is 4.1 possible? If not, maybe 5.0? It is indeed widely used as it is in the template, so it will take some time.

**Comment by pllim** [comment]
> Is there a tracking issue for that?

Not that I can find for deprecating `enable_deprecations_as_exceptions`. Do any of you want to open one? 😄 

There is one for `catch_warnings` though at #6761

**Comment by mhvk** [comment]
I meant just for astropy itself, to remove the `enable_deprecations_as_exceptions` line in `conftest.py`.

**Comment by pllim** [comment]
I would still prefer to wait till 4.1.

**Comment by pllim** [comment]
Back to the matplotlib warning, see https://github.com/matplotlib/matplotlib/issues/15781#issuecomment-559403039

*The problem doesn't exist in master anymore because examples.directory has been removed, but for future reference, you can use rcParams.copy() to turn the rcParams into a plain dict that doesnt warn on access. Alternatively, I would say the "correct" way to do the manipulation you do in pytest_{,un}configure is to use rc_context() (which also suppresses the warnings, and is faster when restoring the previous settings because it knows it doesn't need to revalidate them), but that's admittedly a but annoying because pytest_{,un}configure is split over two functions (probably something doable with ExitStack, yada yada).
I'm not really sure there's a way around this problem given that we want to warn when people use deprecated rcs, so I think this is closer to a feature than a bug... (the fact that copy() has an "escape latch" could in fact nearly be considered a bug)*

cc @astrofrog

**Comment by pllim** [comment]
p.s. I cannot test the proposed solution above because I can't see that warning on my local machines anymore!

**Comment by bsipocz** [comment]
> @mhvk , if you mean putting it into 4.0, I am afraid it is too late. Is 4.1 possible? If not, maybe 5.0? It is indeed widely used as it is in the template, so it will take some time.

I totally missed this discussion. I suppose we can still push a deprecation warning for it into 4.0.rc2, assuming that it won't mess itself up. And then remove it in 5.0. 

But as I said in the issue, it's used in a zillion downstream packages, so we need a long deprecation with updated template etc. probably even batchPRed fixes opened.

**Comment by mhvk** [comment]
@bsipocz - I think we should not worry about this for 4.0. In a way, this is really not the standard astropy deprecation case, but rather one where we are slowly changing a bit of infrastructure - and a pretty nice part of making ourselves less dependent on in-house hacks. So, I think it is totally fine to put off even the deprecation warning to 4.1 - perhaps at the same time as we are transitioning away from astropy-helpers.

**Comment by bsipocz** [comment]
Yes, the difference is though that it will affect most downstream that use the package template. So the removal of it will be more like the removal of the bundled six. Makes sense, but causes pain downstream. That being said, if we do a batchPR it doesn't matter that much whether we deprecate it in 4.0 or later. Maybe add a PendingDeprecationWarning, now?

**Comment by bsipocz** [comment]
This is not release blocker, so I'm removing the milestone now.
