### ISSUE TITLE
Header.set can create empty valued keywords

### ISSUE THREAD

**Issue by sergiopasra** [astropy/astropy#9696]
I don't know if this is a bug or is expected, but in astropy 3.0 this:

```python
from astropy.io import fits
hdr = fits.header()
hdr.set('A')
print(hdr)
```
gets you this

```
A = ' '
END
```
but in 3.2 you get this
```
A = 
END
```
with no value. Is this valid FITS?

EDIT: Fixed code

**Comment by pllim** [comment]
Hmm... I see that in 4.1dev too. Do you want to `git bisect` and see which commit was the culprit?

**Comment by saimn** [comment]
Yes, this is valid FITS, it creates an undefined card : #8572

**Comment by sergiopasra** [comment]
Yes, the commit is 545f488cbb4a5ccca908bffeb90bc29ad41bd9c1 
I see that before this commit a value of `None` in this function was mapped to `' '` 
It's my understanding that this is the intended behavior, so this can be closed.
