### ISSUE TITLE
Is change in behavior of quantity.value for scalars deliberate?

### ISSUE THREAD

**Issue by timj** [astropy/astropy#9697]
## Description

There is a change in behavior between Astropy 3.2 and Astropy 4.0 that is breaking some of our code. I'm flagging this in case it wasn't deliberate:

### Astropy 3:

```
>>> import astropy.units as u
>>> import numpy
>>> a = 5 * u.s
>>> type(a.value)
<class 'float'>
```

### Astropy 4

```
>>> import astropy.units as u
>>> import numpy
>>> a = 5 * u.s
>>> type(a.value)
<class 'numpy.float64'>
```

So for scalar quantities the type has changed from standard float to numpy float. 

It's entirely possible that this is deliberate so that array values and scalar values have the same type.  I was asked to file this on Slack just in case it was a side effect of something.

The impact for us is that something which serialized to YAML without any issue now breaks because YAML does not understand what to do with a numpy object. We can of course fix our code to trap this case.

cc/ @mhvk

**Comment by pllim** [comment]
I thought maybe it was #6603 but that is the astropy 3.0 behavior that you are seeing. Lemme dig a bit more.

**Comment by pllim** [comment]
Could this be #8876 ?

**Comment by mhvk** [comment]
Indeed, that was done in #8876 - and it was a deliberate change, partially since it helped solve annoying problems with float dtype of different precision (i.e., increase in precision for `float32`, loss of precision for `longdouble`).

I still think it is the right thing to do, but am sorry about the annoyance!

**Comment by timj** [comment]
Thanks for the clarification. We'll work around it in our code.
