### ISSUE TITLE
ENH: raise consistent exceptions on missing bz2/lzma modules

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#9713]
### Description
#9652 has introduced a more concise `ModuleNotFoundError` for `io.fits` if bzip2 is not available. For consistency, `get_readable_fileobj` should raise the same exception, analogously for missing `lzma` support (this had already been changed, but reverted in 7795c8d in order not  to change the API in a bugfix PR). It should be reintroduced on an appropriate deprecation scheme.

**Comment by saimn** [comment]
The change concern `get_readable_fileobj` so I'm changing the labels.

**Comment by pllim** [comment]
@dhomeier , since you already did the work, do you have plans to submit a PR for this?
