### ISSUE TITLE
Deprecate enable_deprecations_as_exceptions

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9718]
### Description

As proposed by @mhvk in https://github.com/astropy/astropy/issues/9690#issuecomment-559154730 . The reasoning is that we can use `pytest`'s `filterwarnings` in `setup.cfg` instead.

### Additional context

This will affect all the other packages that use this feature as well, especially if they were created from our package template.

Once deprecation is in, a follow up issue needs to be opened for its complete removal after a deprecation period.

**Comment by bsipocz** [comment]
😱 - it's used downstream a lot, so it needs to be a long deprecation and/or batchPR-ed.

**Comment by astrofrog** [comment]
We could stop using it in the core package immediately though, long before we deprecate/remove it.

**Comment by pllim** [comment]
First stage: #10503

**Comment by pllim** [comment]
Already happened in https://github.com/astropy/astropy/pull/12633 and follow-up issue is https://github.com/astropy/astropy/issues/12679
