### ISSUE TITLE
Add .items() to Table and Row?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#9732]
`Table` has `.keys()` and `.values()` which work like expected, producing results similar to what a `dict` would. So far, though, it does not also have `.items()`, which probably make sense if only for completeness. If we do this, we should be sure to also add it to `Row`.

A related question (though one that doesn't have to be solved at the same time), is whether this also makes `Table` compatible with a mapping - the answer for `Table` is arguably "no", since, e.g., its length is the number of rows, not the number of entries returned by `.keys()` or `.values()`. For `Row`, though, it arguably is a mapping.

**Comment by Jaisu-1** [comment]
I'll take this up, if it's okay

**Comment by mhvk** [comment]
Sure!

**Comment by Jaisu-1** [comment]
Thanks, on it

**Comment by Jaisu-1** [comment]
Can you assign it to me?

**Comment by mhvk** [comment]
We usually do not assign issues until there is a PR, and rely on anybody who sees an issue like this, where someone has said they will tackle it, to first ping.

**Comment by saimn** [comment]
`Table` does not have `.values()`, so I'm a bit confused by what `.values` and  `.items` should do for `Table` ?

**Comment by mhvk** [comment]
Hmm, just goes to show how carefully I look! It is `TableColumns` that has the `.values()` attribute. Still, given that `.keys()` is just `self.columns.keys()`, I guess it is not illogical to think one would similarly have `.values()` (and `.items()`).

**Comment by saimn** [comment]
Yes but `TableColumns.values()` gives columns, I'm not quite sure what `Table.values()` should return, rows or columns ?

**Comment by Jaisu-1** [comment]
I think rows? That makes sense right?

**Comment by Jaisu-1** [comment]
Because there's already tablecolumns to return columns and table is not similar to mapping

**Comment by mhvk** [comment]
Since `.keys()` gives the column names, surely `.values()` should give the columns themselves. Indeed, even now `dict(**table)` gives a dict with columns as the values.

**Comment by DShivansh** [comment]
Hi I am a bit confused here do we have to implement the Table.values() or table.items()
and can you please explain with the example of what kind of output each of the functions should return.

**Comment by mhvk** [comment]
Both - and they should be similar to what a `dict` returns.  See #9712 for `.values()` for `Row`.

Note though that @Jaisu-1 was already planning to tackle this!

**Comment by DShivansh** [comment]
I think that Table.values() should return a list which will contain a list which will consist of the value of each column
Table.items() should return a dictionary.
right?

**Comment by DShivansh** [comment]
@mhvk can you please tell me why the 4 test fail and what does "no flag found" error stand for.

**Comment by sashank27** [comment]
@DShivansh since you have created a new functionality, you have to add tests for the same. Also, there is no changelog entry present. You can wait until a reviewer reviews your PR, assigns a milestone, and decides whether a changelog entry is needed or not. Then you can add the entry in the `CHANGES.rst`

**Comment by mhvk** [comment]
Sorry for the brevity: `.items()` should be like `dict.items()`
