### ISSUE TITLE
Have a counter in SkyCoord initializations and raise a warning in the event of a lot of scalar initializations

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9744]
Idea from @astrofrog from the 2019 coordination meeting: have a "counter" in `SkyCoord` that keeps track of how many times a scalar SkyCoord it's initialized and raises a warning along the lines of "Are you doing scalar initialization of SkyCoord in for loops? Maybe you should use vectors - see LINK".

Suggestion from @perrygreenfield  - is it really a "rate" (initializations / time) vs "total count" that we care about?

cc @adrn @taldcroft @perrygreenfield

**Comment by perrygreenfield** [comment]
To expand on the rate issue a bit, initializing a scalar on a very lengthy loop probably is of little consequence, but on a tight loop it is. So when the counter is initialized, perhaps a time of start can be included and when the count threshold is reached, the time difference checked (and reset to the current time). Only if the time interval is small enough for the count threshold would a warning be issued.

**Comment by perrygreenfield** [comment]
Would it be much faster to reuse a scalar SkyCoord instance in those cases where a vector isn't feasible?

**Comment by astrofrog** [comment]
In terms of rate vs abs number, I'd say just number. However you are doing, if you are initializing 10^6 SkyCoord there's probably something wrong!

**Comment by taldcroft** [comment]
> Would it be much faster to reuse a scalar SkyCoord instance in those cases where a vector isn't feasible?

Yes, and IIRC this is done with ginga.  That capability was needed and ended up in this back-door to SkyCoord mutability: https://docs.astropy.org/en/stable/coordinates/inplace.html

**Comment by taldcroft** [comment]
I think that rate and count are both important.  About rate, what you want to avoid is the case where the time spent in coordinate initialization is actually less than ~30% of the total: here the user sees the warning, spends a bunch of time refactoring the code (possibly making it less readable), and gets no appreciable performance gain.  We all know the lesson: profile first!

About total count - if it is just 100 iterations in a tight loop, then who cares, and code simplicity rules.  (Plain loops are often simpler to write and read).

**Comment by astrofrog** [comment]
I had a discussion today with someone who made me realize that a valid use case for initializing ``SkyCoord`` many times with scalars was for example if running a long running script dealing with real-time data/calculations (e.g. telescope pointing over time). So if we do do anything, rate is indeed important.

As the person who originally suggested this half in jest, I'm actually not sure if we would actually want to do this...

**Comment by taldcroft** [comment]
One certain outcome of doing this idea would be to make initializing SkyCoord a little bit slower...

**Comment by astrofrog** [comment]
Indeed. Shall we just close this?

**Comment by adrn** [comment]
@astrofrog I made #9764 because I had a stale version of this open and didn't see the recent comments - oops!

But, I kind of disagree. If we make it easy to disable, can't the person who needs to initialize many skycoords just disable this? I still think it could help many other users...

**Comment by pllim** [comment]
How do you disable it in a way that won't affect performance? There will still be some `if` statements.

**Comment by astrofrog** [comment]
> But, I kind of disagree. If we make it easy to disable, can't the person who needs to initialize many skycoords just disable this? I still think it could help many other users...

I'm worried about the case where someone has a long running script that starts raising warnings after a month unexpectadly

**Comment by adrn** [comment]
> How do you disable it in a way that won't affect performance? There will still be some `if` statements.

Given what else is in the SkyCoord initializer, I don't think this will ever be a noticeable perturbation...but point taken!

> I'm worried about the case where someone has a long running script that starts raising warnings after a month unexpectadly

This sounds to me like a case of blocking a useful feature that could benefit users we do know on behalf of a hypothetical user; if you have someone or something specific in mind @astrofrog, could you share that here for completeness? I personally think it's worth thinking more about the cost/benefit here. But if consensus has already determined that the cost outweighs the benefit, fine by me to close this!

**Comment by adrn** [comment]
Maybe we need to consider having different Astropy user modes: 'observatory/quiet', 'expert', 'user' that modify the behavior of things like this.
```astropy.mode('user')```
'user' mode could make errors/warnings more friendly and look out for "teachable moments" 😉
