### ISSUE TITLE
Add a section in the modeling docs on how to implement serialization to asdf

### ISSUE THREAD

**Issue by nden** [astropy/astropy#9746]
from @jehturner : Regarding completing the serialization of models, I suppose the ideal thing would be if people contributing any new models in future can also provide the corresponding serialization. Would it be worth adding a section to "Defining New Model Classes" in modeling with links to "Writing ASDF extensions" in the ASDF docs (since it's not trivial, with definitions in various places)?

**Comment by perrygreenfield** [comment]
Yes

**Comment by pllim** [comment]
No longer relevant here. It is `asdf-astropy` now.
