### ISSUE TITLE
Update documentation of astropy.wcs

### ISSUE THREAD

**Issue by nden** [astropy/astropy#9748]
The `astropy.wcs` documentation has not been updated for a while.
I'm opening this issue to serve as a place holder for tasks to do related to improving the documentation in 4.1.

[ ] Write examples using the WCS API.

**Comment by kakirastern** [comment]
I would like help out with this task if possible...

**Comment by nden** [comment]
@kakirastern This is great! I'll contact you on slack to discuss this.
