### ISSUE TITLE
TST: CI job frequently fails with cache damaged error

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9765]
### Description

After the series of cache refactoring PRs, starting with #9182 , the Windows job in CI often fails with an error that reports damaged cache, but often times it is unrelated to the affected PR. The current workaround is for someone with enough Travis CI admin access to go in and delete the cache for the PR, and then rerun the job. However, this is not a feasible solution for the long run.

@aarchiba , is there a way to mitigate this situation? Thanks!

**Comment by bsipocz** [comment]
Not just the windows build, but I just needed to clear the cache for the remote-data/numpy-dev job on the 4.0.x branch as it was failing with various cache related issues even after restarting the job 3 times.

**Comment by pllim** [comment]
Example logs:

* Linux:  https://travis-ci.org/astropy/astropy/jobs/624647696
* Windows: https://travis-ci.org/astropy/astropy/jobs/624644947

**Comment by aarchiba** [comment]
There is definitely something wrong but I don't know what yet. I haven't seen it locally yet, which doesn't help debugging, but I haven't had a chance to sit down and hammer at it.

**Comment by pllim** [comment]
The stop gap plan is to skip that flaky test so release can proceed. After that, I will open a follow-up PR to undo it and hopefully find the real cause. Stay tuned!

**Comment by aarchiba** [comment]
I wonder if maybe this is the result of the temporary-directory pytest fixture not always giving different temporary directories? Perhaps I can switch to a test fixture I trust and see if it fixes this - though as an erratic failure it's not going to be easy to tell. Perhaps I can replicate it locally with a looping parallel tox run?

**Comment by pllim** [comment]
Haven't seen this in a while.
