### ISSUE TITLE
For 3D FITS files written by astropy, the WCS cannot display in DS9

### ISSUE THREAD

**Issue by kxxdhdn** [astropy/astropy#9769]
### Description

I have a 3D FITS file with a 3rd spectral dimension of 2D image. It was written by IDL and the WCS information can display correctly in DS9.
When I used the astropy to read and rewrite it with the same data and header, I opened the output FITS file which was supposed to be the same as the original one in DS9. This time the WCS information cannot display. The 'WCS' options are not available except the 'WCS Parameters'. So I checked it, all the parameters are totally the same with the original file. 
(Bonus: for the original FITS file whose WCS can display, if you click 'Apply' button, the WCS will not display only after clicking 'Reset' or reopening it. )

### Steps to Reproduce

1. [First Step]
Read and rewrite a 3D FITS file with the following script: 

```python
from astropy.io import fits

# read
with fits.open('original.fits') as hdul:
  hdr = hdul[0].header
  data = hdul[0].data
  wave = hdul[1].data[0][0][:,0] # CUBISM

# write
primary_hdu = fits.PrimaryHDU(header=hdr,data=data)
hdul = fits.HDUList(primary_hdu)
hdu = fits.ImageHDU(data=wave)
hdul.append(hdu)
hdul.writeto('rewritten.fits')
```

2. [Second Step]
Open 'original.fits' in DS9. The WCS info can display;
Open 'rewritten.fits' in DS9. The WCS info cannot display. The 'WCS' options are not available.

### System Details

macOS Catalina 10.15.1
python 3.6.8 (Anaconda env)
astropy 3.1.2
DS9 Version 8.1rc (Oct 31, 2019) - macOS Catalina 10.15
[original.fits.zip](https://github.com/astropy/astropy/files/3961067/original.fits.zip)

**Comment by nden** [comment]
Could you post the output of

`fits.info("original.fits")` and `fits.info("rewritten.fits")`

Which extension has the WCS info? If the WCS is in the header of the first extension then you are not passing that info to `rewritten.fits`. The command `hdu = fits.ImageHDU(data=wave)` creates a generic `ImageHDU` header without a WCS.

**Comment by kxxdhdn** [comment]
> Could you post the output of
> 
> `fits.info("original.fits")` and `fits.info("rewritten.fits")`
> 
> Which extension has the WCS info? If the WCS is in the header of the first extension then you are not passing that info to `rewritten.fits`. The command `hdu = fits.ImageHDU(data=wave)` creates a generic `ImageHDU` header without a WCS.

Thank you for the quick reply. The outputs you asked are

Filename: original.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     225   (163, 89, 100)   float32
  1  WCS-TAB       1 BinTableHDU     13   1R x 1C   [100E]

Filename: rewritten.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     225   (163, 89, 100)   float32
  1                1 ImageHDU         6   (100,)   float32

As you said, they are not exactly the same...so I changed my script so that I could get the same WCS info...

```python
from astropy.io import fits

# read
with fits.open('original.fits') as hdul:
  hdr = hdul[0].header
  data = hdul[0].data
  wave = hdul[1].data # MODIFIED HERE

# write
primary_hdu = fits.PrimaryHDU(header=hdr,data=data)
hdul = fits.HDUList(primary_hdu)
hdu = fits.BinTableHDU(data=wave, name='WCS-TAB') # MODIFIED HERE
hdul.append(hdu)
hdul.writeto('rewritten.fits', overwrite=True)
```

However I doubt that the generic ImageHDU header cannot deliver WCS info since I have other FITS files with WCS info like

No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      22   (99, 45, 344)   float64
  1  WAVELENGTH    1 ImageHDU         7   (344,)   float32

which can display WCS in DS9.

**Comment by kxxdhdn** [comment]
> You are right, in general `ImageHDU` can deliver WCS info _if the necessary keywords are there._
> 
> I see that the first extension is WCS-TAB. This means the entire first extension holds the WCS info for the data in the primary HDU. By saving it as an ImageHDU (i.e. an array) the WCS info cannot be understood and is essentially lost.
> 
> What are you trying to accomplish? Perhaps there's another way to do it?

Actually I wanted to figure out the minimum set of keywords that DS9 needs to display WCS, in other words what are lost with this way of writing FITS file, since it works well for other data. 

As far as I understand, this issue does not lead to obvious trouble in my code of WCS (re)projection because all the keywords astropy uses present. It is just about the convenience of visualising outputs in DS9 (e.g. lock frames with WCS), which seems to me a bit bizarre. 

Further more, this interest for header keywords can also refer to #9641 for example. When using `w = WCS(header, naxis=2)`, I did following modification since actual astropy.wcs does not support 3D cube with -TAB (if I understood...)

```python
header = hdr.copy()
if header['NAXIS']==3:
	for kw in hdr.keys():
		if '3' in kw:
			del header[kw]
	header['NAXIS'] = 2
```

**Comment by nden** [comment]
The set of keywords are described in the WCS papers https://fits.gsfc.nasa.gov/fits_wcs.html.

And yes, `wcs-tab` is a WIP in astropy. The `WCS-TAB` convention is in paper III.

**Comment by pllim** [comment]
xref #9641 cc @mcara

**Comment by kxxdhdn** [comment]
```python
from astropy.io import fits
from astropy.table import Table

# read
with fits.open('M83_LL1.fits') as hdul:
hdr = hdul[0].header
data = hdul[0].data
wave = hdul[1].data[0][0][:,0]
wave = wave.reshape((100,1))
wave = fits.Column(array=[wave], name='WAVELENGTH', format='100E', u
     ...: nit='um', dim='(1,100)')
     ...:
     ...:   print(wave)
     ...:
     ...: # write
     ...: primary_hdu = fits.PrimaryHDU(header=hdr,data=data)
     ...: hdul = fits.HDUList(primary_hdu)
     ...: hdu = fits.BinTableHDU.from_columns([wave], name='WCS-TAB')
     ...: hdul.append(hdu)
     ...: hdul.writeto('rewritten.fits', overwrite=True)

**Comment by kxxdhdn** [comment]
I took some time to convert numpy ndarray to the table data of `original.fits`. Finally the WCS can display correctly in DS9. Note that the PrimaryHDU (which has all necessary keywords) is never affected. So I think it is the way DS9 uses lookup table (data format/header keywords) when reading WCS info who causes the problem. (I don't know whether astropy will use a similar way to implement `WCS-TAB` support...)

Attached my code: 

```python
from astropy.io import fits

# read
with fits.open('original.fits') as hdul:
  hdr = hdul[0].header
  data = hdul[0].data
  wave = hdul[1].data[0][0][:,0] # numpy ndarray

# write
primary_hdu = fits.PrimaryHDU(header=hdr, data=data)
hdul = fits.HDUList(primary_hdu)
# recover hdul[1] of original.fits
wave = wave.reshape((100,1))
wave = fits.Column(array=[wave], name='WAVELENGTH', format='100E', unit='um', dim='(1,100)')
hdu = fits.BinTableHDU.from_columns([wave], name='WCS-TAB')
hdul.append(hdu)
hdul.writeto('rewritten.fits', overwrite=True)
```

and the table header:

```
XTENSION= 'BINTABLE'           / binary table extension
BITPIX  =                    8 / array data type
NAXIS   =                    2 / number of array dimensions
NAXIS1  =                  400 / length of dimension 1
NAXIS2  =                    1 / length of dimension 2
PCOUNT  =                    0 / number of group parameters
GCOUNT  =                    1 / number of groups
TFIELDS =                    1 / number of table fields
TTYPE1  = 'WAVELENGTH'
TFORM1  = '100E    '
TUNIT1  = 'um      '
TDIM1   = '(1,100) '
EXTNAME = 'WCS-TAB '           / extension name
```

**Comment by kxxdhdn** [comment]
I just reviewed this issue, it seems that with the actual astropy 4.0.2 it is no longer a problem. 
So I am closing it leaving the following note in case: 
I've integrated this issue in my code [laputan](https://github.com/kxxdhdn/LAPUTAN) with the keyword `wmod` of the functions `read_fits` and `write_fits`. This package is available on PyPI, you can use it by
```bash
pip install laputan
```
```python
from laputan.inout import read_fits, write_fits
```
