### ISSUE TITLE
VOTABLE namespace attributes incorrect on write.

### ISSUE THREAD

**Issue by tomdonaldson** [astropy/astropy#9773]
### Description

When writing out a VOTable, the VOTABLE element attributes are incorrect with respect to namespace.

### Expected behavior

The correct namespace for VOTable 1.4 is `"http://www.ivoa.net/xml/VOTable/v1.3"`.  The schema location is optional, and if specified can be either `http://www.ivoa.net/xml/VOTable/VOTable-1.4.xsd` or `http://www.ivoa.net/xml/VOTable/v1.3`.  The former will always point to the VOTable 1.4 standard, whereas the latter will resolve to the backward-compatible schema for VOTable 1.5(+) when/if they are approved as standards.

So these are all legal VOTABLE elements:
```xml
<VOTABLE version="1.4" xmlns="http://www.ivoa.net/xml/VOTable/v1.3">
```
```xml
<VOTABLE version="1.4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns="http://www.ivoa.net/xml/VOTable/v1.3" 
xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.3 http://www.ivoa.net/xml/VOTable/VOTable-1.4.xsd">
```
```xml
<VOTABLE version="1.4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns="http://www.ivoa.net/xml/VOTable/v1.3" 
xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.3 http://www.ivoa.net/xml/VOTable/v1.3">
```
### Actual behavior

Instead, the VOTABLE element looks like this:
```xml
<VOTABLE version="1.4" xmlns="http://www.ivoa.net/xml/VOTable/v1.4"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.ivoa.net/xml/VOTable/v1.4">
```

### Steps to Reproduce

1. Run the code below
2. View the VOTABLE element in bad_votable_element.xml

```python
from astropy.table import Table

little_table = Table(rows=[(1, 2)], names=('col1', 'col2'))
little_table.write('bad_votable_element.xml', format='votable')
```

### System Details

Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.17.4
astropy 4.0.dev26663

**Comment by pllim** [comment]
http://www.ivoa.net/xml/VOTable/v1.3 pointing to 1.4 and eventually 1.5+ isn't very intuitive but okay...
