### ISSUE TITLE
astropy.time.Time object is not JSON serializable.

### ISSUE THREAD

**Issue by SimonKrughoff** [astropy/astropy#9774]
### Description
I have looked in the issues and don't see this issue reported, but please correct me if I've missed something.

The specific issue I am seeing is that I can't use `bokeh` to plot a `pandas.DataFrame` when I have used an `astropy.time.Time` object as the index.  The underlying problem is that the `Time` object is not serializable to JSON, which `bokeh` assumes.

It would be nice for `Time` to be serializable even if it is just a call to `__str__` or `__repr__`.

### Expected behavior
I expect `json.dumps(Time.now())` to return a useful string representation of the `Time` object.

### Actual behavior
Doing `json.dumps(Time.now())` raises a `TypeError`.

### Steps to Reproduce
```python
from astropy.time import Time
import json
start = Time.now()
json.dumps(start)
```
Exception is:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-cfb98fe340fe> in <module>
      2 import json
      3 start = Time.now()
----> 4 json.dumps(start)

/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    229         cls is None and indent is None and separators is None and
    230         default is None and not sort_keys and not kw):
--> 231         return _default_encoder.encode(obj)
    232     if cls is None:
    233         cls = JSONEncoder

/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/json/encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
    180                         f'is not JSON serializable')
    181 

TypeError: Object of type Time is not JSON serializable
```

### System Details

Linux-3.10.0-1062.1.2.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
Numpy 1.16.2
Scipy 1.2.1
astropy 4.1.dev27191

**Comment by SimonKrughoff** [comment]
As a follow up, @pllim pointed me at `astropy.utils.misc.JsonCustomEncoder`.  Unfortunately, that doesn't seem to help:
```python
from astropy.utils.misc import JsonCustomEncoder
json.dumps(start, cls=JsonCustomEncoder)
```
The above snippet produces the same trace as originally reported.

**Comment by pllim** [comment]
cc @taldcroft and @mhvk

**Comment by SimonKrughoff** [comment]
Musing on this a little more with @cbanek, it seems more and more like this may not be an `astropy` issue.  It turns out that none of the common date-like objects are natively JSON serializable.  I called `json.dumps` on both `pandas.Timestamp` and `datetime.datetime` and both throw the same `TypeError` I see with the `astropy.time.Time` object.

This shows up when trying to plot with `bokeh` and it turns out that the custom `bokehJSONEncoder` is special-casing for time like objects and simply doesn't have `astropy.time.Time` in the list of time-like objects it knows about.

I'm uncomfortable pushing information into `bokeh`, but since the community has essentially taken the stance that time-like objects need not be JSON serializable, I'm equally uncomfortable mandating that the astropy time-like types serialize to JSON natively (I don't know how to push a custom JSONEncoder down into the `bokeh` plotting routines).

Thoughts?

**Comment by taldcroft** [comment]
There was a fair bit of discussion in the past about serializing to JSON, with the upshot being that astropy core decided to not support JSON in favor of YAML:
```
>>> from astropy.io.misc import yaml
>>> t = Time.now()
>>> yaml.dump(t)
"!astropy.time.Time {format: datetime, in_subfmt: '*', jd1: 2458831.0, jd2: 0.34005127362268517,\n  out_subfmt: '*', precision: 3, scale: utc}\n"
```
YAML serialization allows convenient lossless round-trip of a `Time` object.

The issue we ran into for JSON is that one naturally would want this to work:
```
t = Time.now()
t2 = json.loads(json.dumps(t))
assert t == t2
```
That turns out to be much more difficult with JSON than YAML because of the metadata that is not captured in a single string.   The standard Python `json` library does not provide a clean mechanism for serializing complex objects in an extensible / pluggable way like `pyyaml`.

**Comment by taldcroft** [comment]
> special-casing for time like objects and simply doesn't have astropy.time.Time in the list of time-like objects it knows about.

That's exactly what I was alluding to about there not being a clean and extensible way.

**Comment by taldcroft** [comment]
For the purposes of plotting can you convert to a time object that it knows about, e.g. np.datetime64 (which is conveniently available as a `Time` formate `datetime64`)?

**Comment by SimonKrughoff** [comment]
Oh, excellent.  Thanks for the pointer to datetime64.  If that solves my problem, I'll close this.
