### ISSUE TITLE
WCSAxes tick labels not drawn for zoomed out Carrington projection

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#9784]
### Description
When plotting a Carrington projection using WCSAxes, then zooming out so that the image is smaller than the axes, results in the tick labels disappearing.

Downstream issue at https://github.com/sunpy/sunpy/issues/3611, but I can reproduce using pure astropy (see below).

### Expected behavior
Tick labels remain when zooming out, as in this zoomed in version:

![Figure_1](https://user-images.githubusercontent.com/6197628/70935928-343f2680-2039-11ea-8083-d55dc974c544.png)

### Actual behavior
Tick labels disappear

![Figure_1](https://user-images.githubusercontent.com/6197628/70935848-08bc3c00-2039-11ea-8327-1de69cbac7fb.png)

### Steps to Reproduce

```python
import matplotlib.pyplot as plt
from astropy.wcs import WCS
import numpy as np

header = {'wcsaxes': 2, 'crpix1': 18.5, 'crpix2': 9.5,
          'cdelt1': 10.0, 'cdelt2': 10.0, 'cunit1': 'deg', 'cunit2': 'deg',
          'ctype1': 'CRLN-CAR', 'ctype2': 'CRLT-CAR', 'crval1': 0.0,
          'crval2': 0.0, 'lonpole': 0.0, 'latpole': 90.0,
          'date-obs': '2000-01-01T00:00:00.000'}
wcs = WCS(header)
data = np.random.rand(*(18, 36))

plt.subplot(projection=wcs)
plt.imshow(data, origin='lower')
plt.xlim(-1, 36)
plt.ylim(-1, 18)
plt.show()
```

### System Details

Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.5 (default, Oct 25 2019, 10:52:18) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.17.4
Scipy 1.3.1
astropy 4.1.dev27205

**Comment by dstansby** [comment]
A bit of digging (this is a fun bug!), reveals that the issue is at https://github.com/astropy/astropy/blob/efa27f063a0f33e7bd5be00cc434eec9ad45e8ea/astropy/visualization/wcsaxes/frame.py#L48

This computes the coordinates along the spine, however if one of the y-limits is out of bounds (e.g. 91 degrees in the above example), even if x-limits are valid (ie. between 0, 360 in the above example) the spine coordinates as a whole are outside the WCS transformation domain, and therefore return `NaN`s. This then cascades into no ticks being located.

**Comment by Cadair** [comment]
This is not just the labels, but the actual ticks, and also is reproducible with any projection where it runs off the edge or close to in some way.

I am curious as to why it's drawing out of bounds for the y axis at all? is it just because that's where the spine is? i.e. max(y)+~1pix ?

**Comment by dstansby** [comment]
Yes, the spine (in pixel space) is outside the pixels, so the coordinates of the spine are outside the valid bounds of the pixel_to_world transformation.

I think this has to be the case for when the x/y directions are not independent, but if there's a way to check whether the axes are independent (ie. pixel_to_world([i, j]) returns the same longitude for all values of i at a given j), then we can special case the tick determination.

**Comment by dstansby** [comment]
Looks like checking [`axis_correlation_matrx`](https://docs.astropy.org/en/stable/api/astropy.wcs.WCS.html#astropy.wcs.WCS.axis_correlation_matrix) could do the trick.

**Comment by Cadair** [comment]
I think that wont actually fix it for you here, as these two axes are correlated (they are still spatial axes).

One thing I can think of is adding a `ax.zoom_to_wcs()` or something which zooms into the bounding box of the WCS.

**Comment by Cadair** [comment]
> I think that wont actually fix it for you here, as these two axes are correlated

It is `CAR` though so maybe not?

**Comment by dstansby** [comment]
They *shouldn't* be correlated though, so I think astropy is just falling back on it's default output because something is missing from the header.

**Comment by Cadair** [comment]
No, they are correlated because they go through wcslib, they are only uncorrelated because the rotation matrix is identity. The transform maths probably still requires them to be correlated.

**Comment by Cadair** [comment]
hmmm, to be fair `world_axis_correlation_matrix` defaults to `True` because they are celestial axes, it might actually be lying.

**Comment by dstansby** [comment]
Yes, the logic is that celestial axes are always correlated, however for a `CAR` projection this isn't true (ie. moving by x-pixel in this case only changes the longitude and not the latitude).

**Comment by Cadair** [comment]
We should probably move the `axis_correlation_matrix` thing elsewhere, I think it's somewhat orthogonal as this can happen just as well with projections which are mathematically correlated, or even if this one had a slight rotation (not sure why you would want that tho lol).

I would like to have some kind of solution for this that applies generally either way.
