### ISSUE TITLE
Store fitter object in model object

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#979]
In `models`, `Fitters` and their `Model`s are separate classes.  In the current version, if a `Fitter` is applied to a model, the `Model`'s parameters are updated, but after that (I _think_), the `Fitter` is not referenced from the `Model`. It might be good for the `Model` to store a reference to the most recently-used `Fitter` so that a user can later go back and figure out how that `Model` got its parameters set to what they are.  This might also involve storing the data used by the `Fitter`.

@nden, what do you think?

(This refers to the `models` subpackage that will be in astropy when #493 is merged. The intent is to merge that without significant design changes, and address proposed updates through additional issues/PRs like this one)

**Comment by astrofrog** [comment]
Removing the 1.0 milestone since I don't think this is critical

**Comment by nden** [comment]
This issue refers to the old implementation of models. After some discussion at PIA hack day, I am going to close it. If someone feels strongly about this please open a new issue.
