### ISSUE TITLE
python setup.py test --coverage broken by coverage 5.0 released December 14

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#9792]
### Description
The release of coverage 5.0 on December 14 broke `python setup.py test --coverage` for Astropy affiliated packages.

### Expected behavior
Tests succeed with coverage output.

### Actual behavior
```
$ python setup.py test --coverage
...
============================= test session starts ==============================
...
======================== 79 passed, 2 skipped in 2.21s =========================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/astropy/tests/helper.py", line 74, in _save_coverage
    lines = cov.data._lines
AttributeError: 'Coverage' object has no attribute 'data'
```

### Steps to Reproduce
Run unit tests for any Astropy affiliated package with coverage 5.0 installed. The astropy-healpix package, for example, reproduces this error.

### System Details
```pycon
>>> import platform; print(platform.platform())
macOS-10.14.6-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.8.0 (default, Dec 11 2019, 00:27:39) 
[Clang 10.0.1 (clang-1001.0.46.4)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.17.4
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.3.3
>>> import astropy; print("astropy", astropy.__version__)
astropy 3.2.3
```

**Comment by Cadair** [comment]
Oh this is going to be really ugly to fix. We do a lot of nasty private API patching of coverage to make this work. I would recommend pinning coverage to 4.0 and forgetting all about it once #9726 is merged.

**Comment by lpsinger** [comment]
I am using the Astropy package template. Where do I pin that?

**Comment by Cadair** [comment]
This might have also have broken the `astropy.test()` function with coverage as well. I do wonder if we need to continue to support coverage etc through that function though.

**Comment by pllim** [comment]
@lpsinger , I think you can pin in your `.travis.yml` but have to look at your repo to be sure.

**Comment by lpsinger** [comment]
I'm using GitLab CI, not Travis, but I was able to work around this (see [commit](https://git.ligo.org/lscsoft/ligo.skymap/commit/cc2934e3282669ac3fbc706bc59458726188afbb)).

**Comment by bsipocz** [comment]
I've opened a PR to limit the coverage version in ci-helpers, that will patch it over for all packages using the template and the astropy test runner.
