### ISSUE TITLE
erfa.aper13 fails in astropy 4.0

### ISSUE THREAD

**Issue by widmannf** [astropy/astropy#9799]
### Description

The function erfa.aper13 from astropy._erfa fails when given arrays as input. There was a significant change between astropy 3.0 (where everything works fine and a specific array transfomration was implemented) and astropy 3.2 and higher, where the function is just a c wrapper and fails with:

```python
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    erfa.aper13(ut11, ut12, astrom0)
  File "[...]/python3.6/site-packages/astropy/_erfa/core.py", line 2112, in aper13
    astrom = ufunc.aper13(ut11, ut12, astrom, astrom)
TypeError: return arrays must be of ArrayType
```

I am using the ouput of erfa.apco13 and erfa.utcut1 as input, so I would expect that it should work without any array transformation...

### Steps to Reproduce

```python
import astropy._erfa as erfa
import numpy as np
MJD = np.array([58827.15925499, 58827.15925499, 58827.15925499, 58827.15925499, 58827.15925499])
N = len(MJD)
UTC2MJD = 2400000.5
paranal_long = -1.228798
paranal_lat = -0.42982
paranal_height = 2669.
apco_param = [UTC2MJD, MJD[N//2], 0.0, paranal_long, paranal_lat, paranal_height, 0.0, 0.0, 0.0, 0.0, 0.0, 2.5]
astrom0, eo0 = erfa.apco13(*apco_param)
UT1, UT2 = erfa.utcut1(UTC2MJD, MJD, 0.0)
astrom = erfa.aper13(UT1, UT2, astrom0)
```

### System Details

Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0]
Numpy 1.17.4
Scipy 1.3.1
astropy 4.1.dev27210

**Comment by mhvk** [comment]
Thanks very much for reporting. I at least narrowed down the issue: `astrom0` is a void, which cannot be written too, and hence internally it should not be specified as an output.
...
Fix in the works...

**Comment by mhvk** [comment]
Separately: is there a specific reason for calling the `_erfa` routines directly?  Ie., do astropy time and coordinates miss something that they should have?

**Comment by mhvk** [comment]
p.s. Fix a bit trickier than thought (though definitely possible) - clearly in none of code we call this routine directly. Sigh.

**Comment by mhvk** [comment]
@widmannf - see #9804 for a fix. I used your example for a test case, so it should be OK!

**Comment by widmannf** [comment]
@mhvk thank you for the fast response! Am I correct that I cannot test it as long as the compiling in [#9804](https://github.com/astropy/astropy/pull/9804) is not done?

**Comment by mhvk** [comment]
True, for #9804 one needs to test as a developer, i.e., compile from source. But given that your example is now a test case, I'm fairly confident it will work!
