### ISSUE TITLE
Split out ERFA Python wrappers from core package

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9802]
This is related to https://github.com/astropy/astropy/issues/7660 but is a more specific/achievable goal. As discussed at various times at the coordination meeting, now that use cases have come up for using the ERFA Python wrappers directly (e.g. @Cadair) and given that there are cases in the 'wild' of importing ``astropy._erfa`` which highlights this need, it makes sense to split out the Python ERFA wrappers into a standalone package. This will have immediate benefits for the core package since it will result in reduced build times for everyone.

@bsipocz checked with the Continuum folks, who confirmed they would be happy to include such a package as a dependency for astropy.

I think everyone I talked to in Socorro was on board with this, and @eteq even suggested a punny package name: perfect (Python ERFa something something). I think we might want to go with something more boring like pyerfa, since perfect is already taken on PyPI :crying_cat_face:

**Comment by mhvk** [comment]
Yes, very much in favour. Where do you think it should live? Probably makes most sense in `liberfa`, right? (i.e, `liberfa/pyerfa`).

**Comment by bsipocz** [comment]
> @bsipocz checked with the Continuum folks, who confirmed they would be happy to include such a package as a dependency for astropy.

bottom line here that we need to make a feedstock on conda-forge first.

**Comment by astrofrog** [comment]
I think that ``liberfa/pyerfa`` is the natural location.

The most important aspect here though is to determine who will be responsible for maintaining this, especially if it lives outside of the astropy organization. I wonder if we want to potentially create a role for maintaining ERFA generally? (even if it lives in a separate org on GitHub).

**Comment by mhvk** [comment]
@eteq made me and @sergiopasra co-maintainers of `liberfa` - it probably makes sense to have us all listed as having this role on the astropy side.

**Comment by bsipocz** [comment]
is erfa an astropy project?

**Comment by pllim** [comment]
I don't think so? https://github.com/liberfa

**Comment by mhvk** [comment]
Not specifically, but we're definitely the main consumer, and I think it is helpful to know who to ask. Maybe the roles could be under "interaction with our dependencies" or something like that (which could then also list numpy, and possibly even some of the non-required ones).

**Comment by astrofrog** [comment]
Maybe astropy/pyerfa would make out responsibility clearer in this case?

**Comment by mhvk** [comment]
Logically, though, the python bindings do belong with `liberfa`, as they are not astropy-dependent.

**Comment by pllim** [comment]
Hmm... In practice, the ERFA software is already a coordinated package out of necessity, right?

**Comment by olebole** [comment]
Just to give my 2¢ as well: I'd also be happy to have such a package as a dependency in Debian. While I don't have the problem of compilation times (since in Debian, liberfa is separate anyway), I'd appreciate the modularization.

**Comment by sergiopasra** [comment]
With my Fedora packager hat on, I think that the split makes sense, much more if people is importing `astropy._erfa`.  As `erfa` comaintainer, `liberfa` seems the natural place.

**Comment by avalentino** [comment]
Hi, I'm very interested in having a stand-alone `erfa` package so I set-up a possible implementation in https://github.com/avalentino/pyerfa.

Of course I just moved the existing code in astropy/_erfa and made some necessary changes.

The package may need some more tweaks, e.g. collapsing erfa/utils sub-package into a single module, but I preferred to not change to much in order to have a clear mapping between code in the stand-alone `erfa` package and the original code in astropy.

I hope that my small experiment can help a little bit.

Please let me know your comments.

**Comment by mhvk** [comment]
@avalentino - thanks so much! From a quick look, I think this looks great! My sense would be that the best way to proceed would be that we (finally) set up `liberfa/pyerfa`, with an initially empty repository that you can then make a PR to with your work. We can then add CI for starters, and after that documentation, etc., all the way up to a first release.

@astrofrog - I checked and it doesn't seem I have the right permissions to add a repository under `liberfa`. Could you do that? (Or grant me permission?)

@avalentino - note that we are in the last week before astropy feature freeze, so we may not be super-fast right now.

**Comment by bsipocz** [comment]
@mhvk @avalentino - IMO any factoring out should start with keep the commit history, similarly as we do/did with other similar cases.

**Comment by mhvk** [comment]
@bsipocz - good point. Do you happen to have a link on how to do that? Most comments in `_erfa` will have been stand-alone, but not all. (If not, we'll google...)

**Comment by bsipocz** [comment]
@astrofrog  is the expert for this (using `git filter-branch`), I'm still in the middle of the first case I'm doing. He has some examples here: https://github.com/astrofrog/git-workflows

Also, I believe @eteq is the one holding the admin keys for the liberfa org.

**Comment by avalentino** [comment]
OK, I can try to setup some scripts based on https://github.com/astrofrog/git-workflows to import the astropy/_erfa sub-package history.

I'm not an expert with this kind of stuff so it may take some time.

I have few questions:
* importing/moving astropy/_erfa should be quite simple but what about extra files imported from astropy/utils? Do you want to preserve their history as well? 
* if so, I doubt the imported code will be working until we apply patches to fix imports and remove unnecessary stuffs. How do you suggest to proceed in this case?
* do you want the `cextern/erfa` folder to be imported as well?

**Comment by mhvk** [comment]
@avalentino - my sense is that we only need to track the history of `astropy/_erfa` - for the utilities, I see that `check_broadcast` in `core.py.templ` is not actually used any more, so that gets rid of `misc.py`. What is in `exceptions.py` is super-erfa specific and trivial, so I think those can just be merged in to `core.py.templ`; similarly, I'd merge `classproperty` into `helpers.py` (it is not completely clear we wouldn't want to move to a singleton eventually, but for now better not to change code!).

No need to import `cextern/erfa` - that is just a copy of `liberfa/liberfa` bundled with astropy. We'd want to be sure that our new `pyerfa` could still work with a system-installed erfa library.

**Comment by astrofrog** [comment]
@avalentino - feel free to ping me on Slack if you have issues with git-workflows!

**Comment by Cadair** [comment]
I very successfully used [filter-repo](https://github.com/newren/git-filter-repo) to do a very similar thing on another project today. This is now the tool that is recommended by the git devs (`git filter-branch` throws a warning telling you to use this instead).

**Comment by avalentino** [comment]
I think I was able to make the requested history import using @astrofrog scripts as base.
@astrofrog I can make a PR to https://github.com/astrofrog/git-workflows if you want.
@Cadair thank you very much for the link, it is indeed very interesting and I will surely use it in the future.

I have completed the history import (just need some final check) and I think I will be able to make available the repository with the stand-alone `erfa` module by the next week-end.

**Comment by avalentino** [comment]
Dear all, the repository [avalentino/pyerfa](/avalentino/pyerfa) has been updated as requested to include the history of the `erfa` package imported form Astropy:

* the [master](/avalentino/pyerfa/tree/master) branch includes only the imported history
* the [pyerfa-standalone](/avalentino/pyerfa/tree/pyerfa-standalone) also includes all changes necessary to make the package work stand-alone

Details on the import procedure are described in [README_REPO_IMPORT.rst](/avalentino/pyerfa/blob/pyerfa-standalone/README_REPO_IMPORT.rst).

The CI stuff is still missing.

Please let me know if you have additional comments.

**Comment by bsipocz** [comment]
I'm no erfa expert, but let me say that this looks very nice indeed. 

As for sorting out the branches, I suppose we now really need to set up the final destination of the package, and then you can push your current `pyerfa-standalone` to the master branch there.

**Comment by mhvk** [comment]
Sounds wonderful - happy to look more next week (after astropy feature freeze...)

**Comment by mhvk** [comment]
Now had a bit more of a look. Agreed with @bsipocz  that the next step is create `liberfa/pyerfa`, though perhaps I'd push your master to it and then do a PR with `pyerfa-standalone`, just to have a place to discuss the changes. But that's a detail, first we need to get going! @eteq - could you create `liberfa/pyerfa` or give me the permission to do so?

**Comment by astrofrog** [comment]
@avalentino - thanks for your work on splitting out the code! Not really critical, but I noticed that somehow for some of the recent commits (after Oct 2019), the history didn't preserve the PR merge commits (but it did for older commits). Any idea what could have caused that?

**Comment by avalentino** [comment]
@astrofrog AFAIK merge commits are pruned by `git-filter-repo` if they are empty.
Do you have a pointer to a merge commit not preserved?

**Comment by astrofrog** [comment]
@avalentino - only a couple of merge commits are missing, for example some commits from https://github.com/astropy/astropy/pull/9804 are included, but not the merge commit from that PR. Again, this is not really a big deal, but am more curious whether there is an issue in the approach I've been using in git-workflows.

**Comment by avalentino** [comment]
Dear @astrofrog please note that contrarily to what I said in one of my previous comments I used [git-filter-repo](newren/git-filter-repo) in the end.
After a first attempt with [git-workflows](astrofrog/git-workflows) I realized I made a typo in the string used for commit message rewrite, so I decided switch to [git-filter-repo](newren/git-filter-repo) which is actually a lot faster (minutes vs hours on my laptop).
If you are interested I included the script in [README_REPO_IMPORT.rst](/avalentino/pyerfa/blob/pyerfa-standalone/README_REPO_IMPORT.rst).

Regarding #9804 it seems to me that the merge commit (df4b2995c) and all ancestors on one side (60b38d9be, ...) up to the branch point are empty merge commits. I'm not 100% sure because there are a lot of merges and the history is not easy for follow.

**Comment by mhvk** [comment]
@avelentino - thanks for all the useful information!  Your import script definitely will have to live in `liberfa/pyerfa` as well - which I hope soon to have created so we can get going!

**Comment by eteq** [comment]
I agree this all most logically lives in `liberfa/pyerfa` - I'll go ahead and create that shortly! (And to echo the others, this looks great at a quick glance, @avalentino !  will try to look more closely soon.)

**Comment by eteq** [comment]
@avalentino - Alright, I created https://github.com/liberfa/pyerfa and populated it with your branch, as well as inviting you to be a mainiainer there.  I propose we continue detailed discussions of pyerfa there, and then once there's a release we use this issue to track actions needed in Astropy (i.e. switching it to a dependency or extern package)

**Comment by avalentino** [comment]
Thank you all.

**Comment by pllim** [comment]
@mhvk , this was done, right?

**Comment by mhvk** [comment]
Yes, indeed!
