### ISSUE TITLE
Add astronomy-specific models

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#981]
Currently the models in `models` are generally-used mathematical functions like polynomials and gaussians.  It would make sense to expand this to include more domain-specific  "astronomy" models like Sersic functions (a commonly-used galaxy surface brightness profile), NFW models (used for modeling LCDM dark matter mass profiles) and similar. The suggestion from #980 might make this quite a bit easier/more readable.

(This refers to the `models` subpackage that will be in astropy when #493 is merged. The intent is to merge that without significant design changes, and address proposed updates through additional issues/PRs like this one)

**Comment by nden** [comment]
Here's an updated [wiki list of models](https://github.com/astropy/astropy/wiki/additional_core_models#update---models-not-implemented-as-of-july-2017) with models not implemented in modeling yet. Feel free to update the list with models you think should go in the next version of astropy. Please include references if possible.

@hcferguson @eteq

**Comment by bsipocz** [comment]
@nden - does it mean this issues can/should be added to the "3.0 feature planning" project board?

**Comment by nden** [comment]
@bsipocz This is really only scoping out possible work. Most likely some form of this will get done but it's too early to say what exactly that will be. Good point though - I wasn't aware there is a project board for 3.0 planning. I'll update when it's a bit more clear how much of this will get done (I'm not doing the work).

**Comment by bsipocz** [comment]
Are there models still missing? If yes, do they have a specific issue for them?
As the comment above says the most useful way forward is to open issues for each and every model. 

With that in mind I suggest to close this very generic issue.
