### ISSUE TITLE
Quantity Support in Matplotlib can cause unit conversion exception

### ISSUE THREAD

**Issue by timj** [astropy/astropy#9841]
### Description

Exception raised when adding a second plot with unit conversion where the data to plot has no values.

### Expected behavior

An empty plot not an exception.

### Actual behavior

```
Traceback (most recent call last):
  File "/Users/timj/work/lsst/tmp/lsstsw/miniconda/envs/lsst-scipipe/lib/python3.7/site-packages/matplotlib/axis.py", line 1550, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/Users/timj/work/lsst/tmp/lsstsw/miniconda/envs/lsst-scipipe/lib/python3.7/site-packages/astropy/visualization/units.py", line 101, in convert
    elif isinstance(val, list) and isinstance(val[0], u.Quantity):
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "break.py", line 17, in <module>
    ax.hist(empty, bins=100, range=(0, 500))
  File "/Users/timj/work/lsst/tmp/lsstsw/miniconda/envs/lsst-scipipe/lib/python3.7/site-packages/matplotlib/__init__.py", line 1601, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/timj/work/lsst/tmp/lsstsw/miniconda/envs/lsst-scipipe/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6694, in hist
    x = [self.convert_xunits(xi) for xi in x]
  File "/Users/timj/work/lsst/tmp/lsstsw/miniconda/envs/lsst-scipipe/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6694, in <listcomp>
    x = [self.convert_xunits(xi) for xi in x]
  File "/Users/timj/work/lsst/tmp/lsstsw/miniconda/envs/lsst-scipipe/lib/python3.7/site-packages/matplotlib/artist.py", line 180, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "/Users/timj/work/lsst/tmp/lsstsw/miniconda/envs/lsst-scipipe/lib/python3.7/site-packages/matplotlib/axis.py", line 1553, in convert_units
    f'units: {x!r}') from e
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: []
```

### Steps to Reproduce

```python
import matplotlib.pylab as plt
import astropy.units as u
import numpy as np
from astropy.visualization import quantity_support

quantity_support()

filled = np.array([1, 2, 3, 4, 5]) * u.mmag
empty = np.array([]) * u.mmag

fig, ax = plt.subplots(ncols=1, nrows=1, figsize=(18, 12))

ax.hist(filled, bins=100, range=(0, 500))
ax.hist(empty, bins=100, range=(0, 500))
```

Commenting out the first `ax.hist` leads to the code running without complaint.

The fix seems to be something like:
```python
 elif isinstance(val, list) and len(val) and isinstance(val[0], u.Quantity):
```
although I'm not sure if matplotlib wants a `None` returned for an empty list.

### System Details

Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.5 (default, Oct 25 2019, 10:52:18) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.17.4
Scipy 1.3.1
astropy 4.0
matplotlib 3.1.1

The script runs fine on:

Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.16.2
Scipy 1.2.1
astropy 3.2.3
matplotlib 3.0.3

**Comment by mhvk** [comment]
Oops. Suggested fix looks good to me, but let me cc @astrofrog

**Comment by astrofrog** [comment]
I think this makes sense

**Comment by pllim** [comment]
@timj , thanks for reporting this! Would you be interested to open a pull request with your suggested fix above?

**Comment by dan-rds** [comment]
If you are looking for help, I could take a stab...

**Comment by timj** [comment]
@dan-rds even with the matplotlib version I am using? I think the patch to check the length is non-zero before accessing the value is still a safe approach.  I will do a quick PR.

**Comment by timj** [comment]
I tracked down the problem that triggered this and it's because of a change in the `hist` implementation in matplotlib. In 3.0.3 the input validation code looks like:

```python
        # basic input validation
        input_empty = np.size(x) == 0
        # Massage 'x' for processing.
        if input_empty:
            x = [np.array([])]
        else:
            x = cbook._reshape_2D(x, 'x')
        nx = len(x)  # number of datasets
```
but in 3.1.1 it looks like:
```python
        # basic input validation
        input_empty = np.size(x) == 0
        # Massage 'x' for processing.
        x = cbook._reshape_2D(x, 'x')
        nx = len(x)  # number of datasets
```
so in the older code you got an empty numpy array, but in the new code you get wht `cbook._reshape_2D` returns which happens to be an empty list inside a list instead. This leads to the convert function getting an empty list which it was not expecting.
