### ISSUE TITLE
Order of configuration import

### ISSUE THREAD

**Issue by maciekgroch** [astropy/astropy#9844]
Hey, 

I have been (successfully)  using `astropy` in multiple projects of mine. Lately, I have used it for the first time on Windows where I encountered really strange issues when importing the package: 
```
In [1]: %time import astropy  
Wall time: 4min 13s     
```
IT TAKES **4 MINUTES** JUST TO IMPORT THE PACKAGE!!! 

I started investigating the issue: it seems it is about system variables (I will simply copy part of  astropy.config.paths.py (38 - 52)): 
```
    elif os.name == 'nt':  # This is for all modern Windows (NT or after)
        if 'MSYSTEM' in os.environ and os.environ.get('HOME'):
            # Likely using an msys shell; use whatever it is using for its
            # $HOME directory
            homedir = os.environ['HOME']
        # Next try for a network home
        elif 'HOMESHARE' in os.environ:
            homedir = os.environ['HOMESHARE']
        # See if there's a local home
        elif 'HOMEDRIVE' in os.environ and 'HOMEPATH' in os.environ:
            homedir = os.path.join(os.environ['HOMEDRIVE'],
                                   os.environ['HOMEPATH'])
        # Maybe a user profile?
        elif 'USERPROFILE' in os.environ:
            homedir = os.path.join(os.environ['USERPROFILE'])
```
I am using Windows so I fall inside the if statement.  My suggestion here is to move the `'HOMESHARE'` to the end so that it is checked as the last one. Setting the network drive as `homedir` will make everything superslow. Is there any reason why it is the second?

Thanks for help!

**Comment by pllim** [comment]
@maciekgroch , are you hoping it would hit the HOMEDRIVE or USERPROFILE for your use case? I feel like it makes sense to move HOMESHARE between HOMEDRIVE and USERPROFILE, but that will not fix your problem if you are going for USERPROFILE.

@MSeifert04 , you are another Windows user, what do you think?

**Comment by pllim** [comment]
p.s. This logic has not been changed pretty much since the start of the project, so I am a little surprised that this is only an issue now.

https://github.com/astropy/astropy/blob/2bc4ad7b65b4146915d5442a6aaa7a82d3b24608/astropy/config/paths.py#L38-L67

**Comment by maciekgroch** [comment]
Thanks for a fast replay! 

Well is there any specific reason for the order: `'HOME'` -> `'HOMESHARE'` -> `'HOMEDRIVE'` -> '`USERPROFILE'`?

I do in fact fall in '`USERPROFILE'`... The problem can be easily worked around by exporting environmental variables or simply overwriting `os.environ` at the start of each run of the program/script. 

The problem is: how do I persuade my colleagues to do so without endlessly complaining about complexity of that operation 😈

**Comment by pllim** [comment]
> Well is there any specific reason for the order

If there was a reason, it is probably lost with time, as the original developer who wrote that had left the project some time ago.

> how do I persuade my colleagues

Unfortunately, I don't have an easy answer for this. While setting up env var is not very user-friendly on Windows, it is a one-time setup, so hopefully not impossible?

**Comment by maciekgroch** [comment]
Hey, 
Thanks for help. I will try to work it around.

**Comment by pllim** [comment]
If you think code change on `astropy` library side is no longer necessary, please close this issue. Thanks!
