### ISSUE TITLE
CHECK WCSLIB WCS-TAB memory corruption bug fixes once a new WCSLIB release available

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#9846]
Undo https://github.com/astropy/astropy/pull/9845 once a new WCSLIB release with needed bug fixes is ported to `astropy`.

CC: @MSeifert04 @nden

**Comment by nden** [comment]
Technically a new release will overwrite this patch, so no need to remove it. But if a new release comes out without the needed changes we'll need to apply the patch again. This ticket is a reminder to check.

**Comment by pllim** [comment]
Do you happen to know which WCSLIB release number will have this fix?

**Comment by mcara** [comment]
`> 7.1`. The version 7.1 released on 01/01/2020 - see https://www.atnf.csiro.au/people/mcalabre/WCS/CHANGES does not include a bug fix.
