### ISSUE TITLE
rounding a Table or QTable in astropy to a specified number of significant digits

### ISSUE THREAD

**Issue by awa5114** [astropy/astropy#9853]
### Description
Is it currently possible to round an entire astropy `Table` or `QTable` to a certain number of significant digits?

### Additional context
In pandas a simple `df.round` will achieve this:

```
import pandas as pd
df = pd.DataFrame({'a':[1.11, 2.22, 3.33, 5.55, 6.66], 'b':[9.99, 8.88, 7.77, 6.66, 5.55]})
df.round(1)
```
I have already tried this in astropy with a QTable but get an error:

> AttributeError: 'QTable' object has no attribute 'round'

I have also tried:

`my_qtable.info.format='0.1f'`

But this does not seem to help. Is there a way to do this? If not would it be easy to implement?

**Comment by taldcroft** [comment]
There is currently no corresponding functionality in astropy Table.  This can be done with these three lines for a table `t`:
```
In [9]: for col in t.itercols():
   ...:     if col.info.dtype.kind == 'f':        
   ...:         np.around(col, decimals=1, out=col)
```

You could alternatively retain the intrinsic full-resolution in the table data but just change the output representation formatting with:
```
In [10]: for col in t.itercols():
   ...:     if col.info.dtype.kind == 'f':        
   ...:         col.info.format = '.1f'
```

**Comment by pllim** [comment]
@taldcroft , thanks for the quick response! Should this be kept open for future implementation, or closed as "won't fix"?

**Comment by taldcroft** [comment]
Let's keep it.  If pandas thinks a `round()` method is worth it then we can have one.  I have tagged this accordingly.
