### ISSUE TITLE
Properly support different electromagnetic unit systems.

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#9858]
## Description

Currently, astropy does not really handle different electromagnetic unit systems.
There are definitions for units in different cgs systems and natural constants 
have properties to access them.

But e.g. the Gauss does not decompose into cgs bases, because it is only defined as
1e-4 Tesla, see #9830.

There are probably other cases I don't yet know about the require different decompositions depending on the unit system.

Many papers in astronomy still use gaussian cgs units.

I think it is desirable, to have a nice top level API to switch between unit systems.
E.g. deciding whether `u.Gauss` decomposes into `u.Tesla` or the cgs base units.

E.g.

```python
import astropy.units as u

u.use_system('gauss')
```

Or 

```python
with u.system('gauss'):
    # do stuff

```

### Additional context
Problems relating to the cgs units occured in #5879 and #5736.

**Comment by pllim** [comment]
I have a feeling that the machinery needed for this would also be the same one that handles #703.

**Comment by DShivansh** [comment]
@MaxNoe can you please share some sources that discuss briefly about different electromagnetic systems and conversions between them.

**Comment by bsipocz** [comment]
And maybe https://github.com/astropy/astropy/issues/4359 is also related (and a whole cascade of other issues). It would be indeed super nice to get this addressed. 
@MaxNoe - would you be interested in working on this?

**Comment by mhvk** [comment]
Yes, this would be wonderful to have, and, indeed, #4359 is the relevant issue. So, let's move discussion there! (closing this now, sorry!)
