### ISSUE TITLE
Deprecate imshow_only_kwargs in imshow_norm

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9861]
As discussed in #9851, in Matplotlib 3.2, passing ``vmin/vmax`` to ``imshow_only_kwargs`` in ``imshow_norm`` is deprecated since Matplotlib no longer allows ``norm`` and ``vmin/vmax`` to be set. I don't think there are other useful kwargs that could be passed to ``imshow_only_kwargs`` so we should probably deprecate it?

**Comment by pllim** [comment]
cc @larrybradley

**Comment by larrybradley** [comment]
Yes, we should deprecate it.  I'll submit a PR.
