### ISSUE TITLE
__len__ of compound models return _n_models and not n_submodels

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#9885]
### Description
The length of a compound model, i.e., the number of models contained in it, is always 1.

### Expected behavior
To get the real number of contained models.

### Actual behavior
Always returns 1.

### Steps to Reproduce
```python
>>> from astropy.modeling.models import Scale
>>> s1 = Scale(1, name='first')
>>> s2 = Scale(2, name='second')
>>> c = s1 | s2
>>> len(c)
1
>>>
```

### System Details
```python
>>> import platform; print(platform.platform())
Darwin-17.7.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.17.3
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.1.dev27296
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.3.2
```

CC: @perrygreenfield

**Comment by pllim** [comment]
Maybe there is a misunderstanding? The implementation shows that it returns `c._n_models` and not `c.n_submodels`

https://github.com/astropy/astropy/blob/0d833cc472e8112c61ab53b15902ea2e80372662/astropy/modeling/core.py#L2492-L2493

```python
>>> c.n_submodels
2
>>> c._n_models
1
```

To illustrate further:

```python
>>> s1 = Scale([1, 2, 3], name='first', n_models=3)
>>> s2 = Scale([2, 4, 6], name='second', n_models=3)
>>> c = s1 | s2
>>> len(c)
3
>>> c.n_submodels
2
```

**Comment by mcara** [comment]
If this is _intentional_, then I think it is confusing: `n_models` (in s set), `n_submodels` ("pure" models in a _compound_ model), ...

**Comment by pllim** [comment]
I'll defer to @perrygreenfield and @nden on how best to clear this up.

**Comment by nden** [comment]
`len` returns the number of models in a model set. Please use `CompoundModel.n_submodels` for the number of models in a compound model. This interface has been in place and used by other packages for a very long time. It's not justified to change it now.
