### ISSUE TITLE
Add __contains__ method to models

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#9887]
### Description
It would be helpful if one could test if a specific model is used (included) in a compound model by a class (type) or model name.

Currently, the default behavior is as follows:
```python
>>> from astropy.modeling.models import Scale, Shift
>>> s1 = Scale(1, name='first')
>>> s2 = Scale(2, name='second')
>>> s3 = Scale(2, name='third')
>>> c = s1 | s2
>>> s1 in c
True
>>> s3 in c
False
```

I think it would be more helpful if the following kinds of tests would work:
```python
>>> 'first' in c
True
>>>'third' in c
False
>>> Scale in c
True
>>> Shift in c
False
```

CC: @perrygreenfield, @nden

**Comment by pllim** [comment]
I don't know how I feel about overloading the `in` API like that. The implementation can get complicated (and slower?) to check for so many different possibilities. How about new methods like `c.has_model_name('first')` or `c.has_model_class(Scale)`?

**Comment by mcara** [comment]
I doubt there will be any penalty for overloading `in`. Why would the be a penalty? This method does not appear to be used anywhere in Models.

**Comment by pllim** [comment]
If you have hundreds of submodels, checking for the object, then for the names, and then for the class names, that's 3x the run time. They might add up to be noticeable. But I'll defer to `modeling` maintainers to decide. I was just thinking aloud.

**Comment by nden** [comment]
> I think it would be more helpful if the following kinds of tests would work:

>>> 'first' in c
True
>>>'third' in c
False
>>> Scale in c
True
>>> Shift in c
False

@mcara Isn't this sufficient:
```
'first' in c.submodel_names                                                                                                                     
Out[15]: True
'third' in c.submodel_names                                                                                                                     
Out[16]: False
Scale in [k.__class__ for k in c]                                                                                                               
Out[18]: True
Shift in [k.__class__ for k in c]                                                                                                               
Out[19]: False

```

**Comment by mcara** [comment]
l think the workaround is fibe.
