### ISSUE TITLE
fitting fails when model supports units and has custom inputs/outputs labels

### ISSUE THREAD

**Issue by shannnnnyyy** [astropy/astropy#9889]
When trying to define a custom Fittable1DModel with custom labels for inputs/outputs that also supports units/quantities, the fitting fails. 

I am writing a fittable model for which I would like the inputs/outputs labels to be something other than x and y. I would also like this model to support units. As a simplified version of the issue I'm encountering, here is a simple model called 'CustomModel' that is fittable and supports units. The input/output units are called 'inn' and 'out' (rather than x & y).

```
from astropy.modeling.core import Fittable1DModel, Parameter
from astropy.modeling import fitting
from astropy import units as u
import numpy as np

class CustomModel(Fittable1DModel):
    
    a = Parameter(default=1.0)
    b = Parameter(default=1.0)
    
    def __init__(self, a=a, b=b):
        super().__init__(a=a, b=b)
        
        self.inputs = ('inn',)
        self.outputs = ('out',)
        
    @staticmethod
    def evaluate(inn, a, b):
        return a*inn + b
    
    @property
    def input_units(self):
        if self.a.unit is None and self.b.unit is None:
            return None
        else:
            return {'inn': self.b.unit / self.a.unit}

    def _parameter_units_for_data_units(self, inputs_unit, outputs_unit):
        return {'a': outputs_unit['out'],
                'b': outputs_unit['out'] / inputs_unit['inn']}

```

This model can be evaluated successfully:

```
>>>modd = CustomModel(a=1*u.m/u.s, b=2*u.m)
>>>modd(10 * u.s)
12m
```
However, fitting fails. Here I pass in some perfectly linear data hoping to get slope and intercept 10.5 and 7.2 back in the fit: 

```
>>>fitter = fitting.LevMarLSQFitter()
>>>x = np.linspace(0, 10, 100) * u.m
>>>y = 10.5*x + 7.2*u.m
>>>fit_custom_model = fitter(m, x, y)

-------------------------------------------------------------------
KeyError                          Traceback (most recent call last)
<ipython-input-12-81aa8227aaed> in <module>
----> 1 fit_custom_model = fitter(m, x, y)

~/packages/astropy/astropy/modeling/fitting.py in wrapper(self, model, x, y, z, **kwargs)
    123                 if model.input_units is not None:
    124                     if isinstance(x, Quantity):
--> 125                         x = x.to(model.input_units['x'], equivalencies=input_units_equivalencies['x'])
    126                     if isinstance(y, Quantity) and z is not None:
    127                         y = y.to(model.input_units['y'], equivalencies=input_units_equivalencies['y'])

KeyError: 'x'
```

When I try the above steps but omit the step where I rename inputs and outputs, everything works as expected. Similarly, when the input/output units are renamed but the units support is removed, everything works. 

It looks like this issue is stemming from the fact that when unit support is enabled, fitting works internally with 'x' and 'y' and expects them to be named exactly that. 

The simple solution would be to just work internally with x & y, and rename the inputs/outputs at the end or just document what they should be - this is my solution for the time being. However, there are several existing non-fittable models (i.e those in rotations) that rename the inputs/outputs right away and work internally with those units, so I think it makes more sense to expect the same functionality here. I can work on a fix for this if it truly is a bug.

**Comment by pllim** [comment]
Hello. Can you please state the version info as asked by the bug report template? Thanks!

**Comment by shannnnnyyy** [comment]
The version is listed as '4.1.dev27344'
