### ISSUE TITLE
Testing in venv with --system-site-packages

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#9897]
Mostly in case it is easy to solve: I generally create my virtual environments with something like
```
python3 -m venv --clear --system-site-packages astropy-dev
```
since it seems a bit senseless to install copies of numpy, etc., for every environment. But if in such an environment, I try to run tests with `pytest` it fails:
```
pip install -e .[test]
pytest astropy/coordinates/tests/test_angles.py
ImportError while loading conftest '/data/mhvk/packages/astropy/astropy/conftest.py'.
py._path.local.LocalPath.ImportMismatchError: ('astropy.conftest', '/usr/lib/python3/dist-packages/astropy/conftest.py', local('/data/mhvk/packages/astropy/astropy/conftest.py'))
```
It looks like the version of astropy from the system is now seen in this testing environment (I'm executing this from `/data/mhvk/packages/astropy`).

p.s. not sure whether to label this a bug or a feature request, but this used to work fine before, with `./setup test -t <filename>`.  cc @astrofrog

**Comment by larrybradley** [comment]
I also get this same error now when I try to run `pytest` directly on any of the test files. :(

**Comment by pllim** [comment]
I cannot replicate this error with `pip install -e .` and then running `pytest astropy/coordinates/tests/test_angles.py`. I am using Miniconda on Linux.

**Comment by larrybradley** [comment]
The issue seems to be that I had done an editable install `pip install -e .` in a virtualenv, but that virtualenv was not activated.  The `conftest` mismatch was coming from my system-wide (non-virtualenv) install of `astropy` and the source-checkout version.  Once I activated the virtualenv, I can run `pytest` again.

**Comment by mhvk** [comment]
I can run things fine if I have a virtual environment without system packages (which is the default); only when I allow `--system-site-packages` do I get an error.  This used to work and I would like to continue to avoid installing lots of package that I have available already, but, as I noted above, it is a bit of a corner case so not that important.

**Comment by pllim** [comment]
Is there a reason why you cannot uninstall the system copy of `astropy`? If you allow site packages and have `astropy` installed in two different places, it is the same problem as `conda` getting confused and falling back to grabbing from `base`, which is usually undesirable.

**Comment by mhvk** [comment]
I use the system copy in my daily work, so that is not an option! But, as noted, work-arounds are easy, just don't use the system files. The issue is really just that it did work before and perhaps it is a trivial change somewhere -- clearly `./setup.py install` did something right that `pip install .` does not.

**Comment by larrybradley** [comment]
Another simple example (without venv):

```
$ git clone git@github.com:astropy/astropy.git
$ pytest astropy/astropy/visualization/tests/test_interval.py
ImportError while loading conftest '/Users/lbradley/Desktop/astropy/astropy/conftest.py'.
py._path.local.LocalPath.ImportMismatchError: ('astropy.conftest', '/usr/local/lib/python3.7/site-packages/astropy/conftest.py', local('/Users/lbradley/Desktop/astropy/astropy/conftest.py'))
```

It appears that the source checkout *must* be installed and be the active version for `pytest` to work now.  That's new.  If it finds another `astropy` version first, then this error is raised.

Is this due to some absolute import of `astropy.conftest`?

**Comment by mhvk** [comment]
Closing since we now have tests with `--system-site-packages`
