### ISSUE TITLE
Undeclared (?) limitation of FITS ASCII table integer field width

### ISSUE THREAD

**Issue by msbentley** [astropy/astropy#9899]
### Description
According to the FITS standard (section 7.2.5):

"This Standard does not impose an upper limit on the number of digits of precision, nor any limit
on the range of numeric values. Software packages that read or write data according to this Standard could be limited, however, in the range of values and exponents that are supported (e.g.,
to the range that can be represented by 32-bit or 64-bit binary numbers)."

My expectation was that AstroPy would choose an underlying data-type suitable for the range of values being read, but that appears not to be the case. This file:

[i10_test.zip](https://github.com/astropy/astropy/files/4122596/i10_test.zip)

for example reads fine with the FITS reference software (fv, fitsverify, fdump etc.) but in AstroPy the values of 4294967295 are read incorrectly as -1. It looks like integer values in ASCII tables are constrained to be 32-bit signed integers - is this correct? I understand I can use offsets etc. but I couldn't see this limitation written down, so wanted to confirm.

### Expected behavior
Valid FITS files to be read as expected.

### Actual behavior
Values outside of the range of a 32-bit signed integer are incorrectly read.

### System Details
Linux-4.18.0-18-lowlatency-x86_64-with-debian-buster-sid
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
[GCC 7.3.0]
Numpy 1.17.5
astropy 4.0
Scipy 1.4.1

**Comment by dhomeier** [comment]
Looks like a bug really. `io.fits.column` has this definition
```
# mapping from TFORM data type to numpy data type (code)
# L: Logical (Boolean)
# B: Unsigned Byte
# I: 16-bit Integer
# J: 32-bit Integer
# K: 64-bit Integer
# E: Single-precision Floating Point
# D: Double-precision Floating Point
# C: Single-precision Complex
# M: Double-precision Complex
# A: Character
```
which actually looks more like Fortran formatting specifiers; `_parse_ascii_tformat` in fact accepts the `I` and `J` identifiers, but not `K`.
It ends up using `i4` as default for `I`, which is truncated to `i2` for `I4` and shorter formats, but does not take care of the cases with 10 digits or more. Should be straightforward to add the latter case to `_convert_ascii_format`, but so far `io.fits` seems to be outsmarting me be resetting the `dtype` to `i4` at some later point...

A workaround for the time being would be to use the nonstandard `J10` `TFORM`, which contrary to the definition above sets the default format to 64-bit, but a proper fix will be more satisfactory.

**Comment by msbentley** [comment]
I think the above mapping is for binary tables, though - e.g. `J` is not an allowed format in ASCII tables, and `I` is used for all decimal integers..?

**Comment by saimn** [comment]
The ASCII related definitions are below in this file:
https://github.com/astropy/astropy/blob/1cb6c81e874a785e2d7a3075a75a372188b0d844/astropy/io/fits/column.py#L63-L79
It seems to support J for int64 mentioning this is non-standard, so it probably dates back to an older version of the standard. Not sure if/when something was changed, I will have to read the ASCII section again ;).

**Comment by dhomeier** [comment]
The ones that are actually used are taken from
`ASCII2NUMPY = {'A': 'a', 'I': 'i4', 'J': 'i8', 'F': 'f8', 'E': 'f8', 'D': 'f8'}`

**Comment by dhomeier** [comment]
> It seems to support J for int64 mentioning this is non-standard, so it probably dates back to an older version of the standard. Not sure if/when something was changed, I will have to read the ASCII section again ;).

I rather think it's from an old non-standard extension, but unfortunately there seems to be no reference for it. Anyway not much harm in accepting `J` (though we should perhaps check if it is accepted with `strict=True`), but the `I` format needs to be more flexible.

**Comment by msbentley** [comment]
OK, thanks. I have to say I haven't followed the standard evolution, but from the [current standard](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf) I see this table:

![image](https://user-images.githubusercontent.com/1671065/73360395-19e8a180-42a3-11ea-8d36-620050fd00bd.png)

and the following statements:

"TFORMn keywords. The TFORMn keywords must be present for all values n = 1, . . . , TFIELDS and for no other values of n. The value field of this indexed keyword shall contain a character string describing the format in which Field n is encoded. Only the formats in Table 15, interpreted as Fortran (ISO 2004) input formats and discussed in more detail in Sect. 7.2.5, are permitted for encoding. Format codes must be specified in upper case. Other format editing codes common to Fortran such as repetition, positional editing, scaling, and field termination are not permitted. All values in numeric fields have a number base of ten (i.e., they are decimal); binary, octal, hexadecimal, and other
representations are not permitted. The TDISPn keyword, defined in Sect. 7.2.2, may be used to recommend that a decimal integer value in an ASCII table be displayed as the equivalent binary,
octal, or hexadecimal value."

and later

"7.2.5. Entries
All data in an ASCII-table extension field shall be ASCII text in a format that conforms to the rules for fixed field input in Fortran (ISO 2004) format, as described below. The only possible formats shall be those specified in Table 15. If values of −0 and +0 need to be distinguished, then the sign character should appear in a separate field in character format. TNULLn keywords may be used to specify a character string that represents an undefined value in each field. The characters representing an undefined value may differ from field to field but must be the same within a field. Writers of ASCII tables should select a format for each field that is appropriate to the form, range of values, and
accuracy of the data in that field. This Standard does not impose an upper limit on the number of digits of precision, nor any limit on the range of numeric values. Software packages that read or
write data according to this Standard could be limited, however, in the range of values and exponents that are supported (e.g., to the range that can be represented by 32-bit or 64-bit binary numbers)."

and finally

"Integer fields. The value of an integer-formatted (Iw) field is a signed decimal integer contained in Columns TBCOLn through TBCOLn+ w − 1 consisting of a single optional sign (’+’ or ’-’) followed by one or more decimal digits (’0’ through ’9’). Nonsignificant space characters may precede and/or follow the integer value within the field. A blank field has value 0. All characters other than leading and trailing spaces, a contiguous string of decimal digits, and a single leading sign character are forbidden."

Thanks for looking into this!

**Comment by dhomeier** [comment]
Made a PR to enable `np.int64` for columns wider than `I9`; this does not make any changes to `J` `TFORM`s.
