### ISSUE TITLE
Model composition by operators not working

### ISSUE THREAD

**Issue by ronpandolfi** [astropy/astropy#9902]
### Description
In astropy 4.x, composing compound models by operands now raises a `TypeError`. 

### Expected behavior
A compound model is composed

### Actual behavior
A `TypeError` exception is raised

### Steps to Reproduce

```python
In[1]: from astropy.modeling.models import Gaussian1D, Shift
In[2]: ShiftedGaussian1D = Gaussian1D + Shift
Traceback (most recent call last):
  File "/home/rp/PycharmProjects/xi-cam2/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-a11b5bac4d52>", line 1, in <module>
    ShiftedGaussian1D = Gaussian1D + Shift
  File "/home/rp/PycharmProjects/xi-cam2/venv/lib/python3.8/site-packages/astropy/modeling/core.py", line 59, in <lambda>
    return lambda left, right: CompoundModel(oper, left, right, **kwargs)
  File "/home/rp/PycharmProjects/xi-cam2/venv/lib/python3.8/site-packages/astropy/modeling/core.py", line 2357, in __init__
    if op != 'fix_inputs' and len(left) != len(right):
TypeError: object of type '_ModelMeta' has no len()
```

### System Details

Linux-4.19.98-1-MANJARO-x86_64-with-glibc2.2.5
Python 3.8.1 (default, Jan  8 2020, 23:09:20) 
[GCC 9.2.0]
Numpy 1.18.1
astropy 4.0
Scipy 1.4.1

(also tested on current git master; same result)

**Comment by pllim** [comment]
This usage is disallowed now, I think. Please see http://docs.astropy.org/en/stable/modeling/changes_for_4.html#modeling-major-changes-for-4-0

**Comment by perrygreenfield** [comment]
Yes, the capability to combine model classes (instead of instances) was deprecated in Astropy 3.
and removed in Astropy 4.0. It was not considered an essential capability and it greatly complicated the implementation.
