### ISSUE TITLE
Astropy version no longer has major, minor attributes

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#9907]
Not 100% sure this needs to be fixed, but in my baseband package I had an astropy version test that used `astropy.version.major, astropy.version.minor`. With the APE 17 changes, those attributes no longer exist.

I've adjusted my package, but it means that already installed versions will fail to work with newest astropy.

cc @astrofrog

**Comment by pllim** [comment]
Workaround?

```python
from distutils.version import LooseVersion

v = LooseVersion(yourpackage.__version__)
v_tuple = v1.version
v_major = v_tuple[0]
v_minor = v_tuple[1]
v_bugfix = v_tuple[2]
```

p.s. Maybe there is a nicer way to do this...

**Comment by mhvk** [comment]
Yes, that would work (I'm blunter and just do `__version__[:3] < '3.2'`...); main question is whether we want to still have those attributes in `astropy.version` (and, if so, propagate them to the package template...)

**Comment by pllim** [comment]
Personally, I never used the `.major` etc attributes, especially given that we have [minversion](https://docs.astropy.org/en/stable/api/astropy.utils.introspection.minversion.html#astropy.utils.introspection.minversion) helper function.

**Comment by eteq** [comment]
Hmm, this is nominally an API breakage.  So at the very least we have to document it as such, and following normal policy I guess we should have at least one version of deprecation error.

I guess I'm inclined towards just putting this back in, though.  Will make a PR to try this based on @pllim's trick above.
