### ISSUE TITLE
TST: Update mpldev truth image to fix failure

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9909]
This failure is hitting `master` and all PRs.
```
_________________________ TestBasic.test_latex_labels __________________________
Error: Image files did not match.
  RMS Value: 6.9784398128967355
  Expected:  
    /root/project/results/tmplss20n11/baseline-test_latex_labels.png
  Actual:    
    /root/project/results/tmplss20n11/test_latex_labels.png
  Difference:
    /root/project/results/tmplss20n11/test_latex_labels-failed-diff.png
  Tolerance: 
    0
```

Suspected upstream change is matplotlib/matplotlib#16366 , which means the "truth" needs to be updated.

**Comment by astrofrog** [comment]
For small changes like this, anyone can update the reference images as CicleCI serves up the images as artifacts. Here's what I did:

* Go to a recent mpldev build on CircleCI on master (e.g. https://circleci.com/gh/astropy/astropy/59263)
* Go to the artifacts tab and expand the results directory shown
* Download ``test_latex_labels.png``
* Clone the https://github.com/astropy/astropy-data repo locally
* Go inside ``testing/astropy/2019-08-02T11:38:58.288466/3.3.x`` (latest date and MPL version)
* Copy the ``test_latex_labels.png`` file into this directory
* Commit and open a PR: https://github.com/astropy/astropy-data/compare/gh-pages...astrofrog:update-latex-labels?expand=1 - and check the differences in the diff to make sure they make sense

**Comment by bsipocz** [comment]
I'm copying this recipe to `astropy-procedures` for future reference.

**Comment by pllim** [comment]
Thanks, all!
