### ISSUE TITLE
quantity_input fails  on Enum arguments

### ISSUE THREAD

**Issue by Goobley** [astropy/astropy#9932]
### Description

I am trying to use quantity_support on the `__init__` of a class which takes an Enum as an argument. If it's annotated something in the type resolution explodes. 

### Expected behavior

Enums should be supported like any other class, or with a special case to ignore them in the worst case. Mypy seems to handle them fine.

### Steps to Reproduce

Running the following code produces the error below. If the Enum annotation is removed, it seems to work fine.

```python
import astropy.units as u
from enum import Enum, auto

class BasicEnum(Enum):
    AThing = auto()
    AnotherThing = auto()

class UnitsTest:
    @u.quantity_input
    def __init__(self, e: BasicEnum, x: u.m):
        self.e = e
        self.x = x


u = UnitsTest(BasicEnum.AThing, 1 << u.m)
```

Error message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Lightweaver/lightweaver/units_test.py in <module>
     13 
     14 
---> 15 u = UnitsTest(BasicEnum.AThing, 1 << u.m)

/local0/scratch/cmo/miniconda3/envs/LightweaverDev/lib/python3.8/site-packages/astropy/units/decorators.py in wrapper(*func_args, **func_kwargs)
    211                 # Check for None in the supplied list of allowed units and, if
    212                 #   present and the passed value is also None, ignore.
--> 213                 elif None in targets:
    214                     if arg is None:
    215                         continue

/local0/scratch/cmo/miniconda3/envs/LightweaverDev/lib/python3.8/enum.py in __contains__(cls, member)
    308     def __contains__(cls, member):
    309         if not isinstance(member, Enum):
--> 310             raise TypeError(
    311                 "unsupported operand type(s) for 'in': '%s' and '%s'" % (
    312                     type(member).__qualname__, cls.__class__.__qualname__))

TypeError: unsupported operand type(s) for 'in': 'NoneType' and 'EnumMeta'

```
So, a workaround for now is to not annotate the argument, but it would be nice to not need to do this long term.

### System Details

Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-glibc2.10
Python 3.8.1 | packaged by conda-forge | (default, Jan 29 2020, 14:55:04) 
[GCC 7.3.0]
Numpy 1.18.1
astropy 4.0
Scipy 1.4.1

**Comment by DShivansh** [comment]
@Goobley I tried producing the same error but it ran perfectly fine without throwing any error on my machine.
my astropy version is **4.1.dev508+g4f09c1fef**.

**Comment by bsipocz** [comment]
Thank you @Goobley for the report, I can confirm the failure using python 3.8.0, while the snippet works with the 3.7.5 and 3.6.9.

I haven't digged into the CPython changelog yet to find the cause.

**Comment by pllim** [comment]
FWIW I cannot find any mention of "enum" in the user-facing change log. I wonder if [enum.py history](https://github.com/python/cpython/commits/0b41a922f95f62b620d5a197b9f2ed8e4bb70730/Lib/enum.py) would give a clue. Probably quite impossible to bisect CPython itself...

**Comment by pllim** [comment]
p.s. Could also be a change in typing? https://docs.python.org/3/whatsnew/3.8.html#typing

**Comment by DShivansh** [comment]
sorry I tried producing the error on python 3.7 I forgot to see the system details given below.

**Comment by bsipocz** [comment]
@DShivansh - no worries. The tracelog gives you the clue, that it's likely python version related, thus I kept trying different versions after it originally worked in my default env.

**Comment by Goobley** [comment]
Thanks for looking into this. Inspired by the fact this is fine on 3.7 I tested `None in BasicEnum` in 3.7. This gives the following DeprecationWarning: `/local0/scratch/cmo/miniconda3/envs/LightweaverDev37/bin/ipython:1: DeprecationWarning: using non-Enums in containment checks will raise TypeError in Python 3.8`

Now, it seems to me (without intimate knowledge of the actual system implemented here), that                 the `isiterable` check on [here](https://github.com/astropy/astropy/blob/6a231eaaa9d4aad529f554cf95cc5ad6b372798b/astropy/units/decorators.py#L207) isn't quite the right check -- a `dict` is iterable, but should it be accepted as a vehicle for supplying a range of types? Wouldn't requiring a type to implement something like `Sequence` perhaps be a more practical option?

**Comment by pllim** [comment]
That line of code is 3 years old now, so if you know how to patch it up, PR is welcome!
