### ISSUE TITLE
modeling.Polynomial1D domain is not documented

### ISSUE THREAD

**Issue by parejkoj** [astropy/astropy#9942]
The `domain` parameter to the Polynomial1D model is not documented. I had a few guesses as to what this was for, but they were all wrong, which resulted in me creating models that did not behave correctly.

https://docs.astropy.org/en/stable/api/astropy.modeling.polynomial.Polynomial1D.html

Please document that `domain` is used to rescale the input to `[-1,1]` (at least, I think that's what it does).

**Comment by pllim** [comment]
Is this related to #9809 ?

**Comment by parejkoj** [comment]
@pllim I don't think so? I just what `domain` to have a descriptive docstring!

**Comment by bsipocz** [comment]
could you open a PR  with the wording that you were expected? (I suppose you already looked into the code to check what it does)

**Comment by parejkoj** [comment]
I did not look into the code; we discovered that we were not getting the results we expected given a set of parameters, and realized the problem was that we had specified `domain`. I don't know what it is supposed to do.

**Comment by pllim** [comment]
I think @nden said over at #9809 that it is basically the same as what is in Numpy -- https://numpy.org/doc/1.18/reference/routines.polynomials.classes.html#basics

**Comment by nden** [comment]
This is being worked on in #9941

**Comment by jehturner** [comment]
Has #9956 taken care of this now? Some further explanation was finally added there rather than in #9941 and it has been merged into `master` and `4.0.x`.

**Comment by nden** [comment]
Thanks @jehturner. Yes, fixed in #9956
