### ISSUE TITLE
TST: html-docs job fails with mysterious 403 HTTP error

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9947]
### Description

Recently, the `html-doc` job on CircleCI started to fail. This prevents proper documentation review for open PRs.

### Expected behavior

Successful if there is no actual documentation rendering error in the PR.

### Actual behavior

Example log on `master`: https://circleci.com/gh/astropy/astropy/59676
```
Warning, treated as error:
The following HTTP Error has occurred fetching https://numpy.org/doc/1.18/: 403 (Forbidden)
```

### Mystery

1. There is no direct hardcoding of https://numpy.org/doc/1.18/ in `astropy` nor `sphinx-astropy`'s `conf.py`. I cannot tell if this came from somewhere in `intersphinx` or `sphinx-gallery` machinery.
2. Going to https://numpy.org/doc/1.18/ on a local browser works fine.

Should we ask Numpy people to whitelist our CircleCI or something?

**Comment by saimn** [comment]
That's the same issue as https://github.com/astropy/astropy/issues/8990, their doc is now hosted on Github Pages it seems, with Cloudflare filtering urllib's User Agent:
```
❯ curl -I https://numpy.org/doc/1.18/
HTTP/1.1 200 OK
Date: Thu, 13 Feb 2020 17:49:45 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=da57c8ef5d451a4daba468c5ce459426b1581616184; expires=Sat, 14-Mar-20 17:49:44 GMT; path=/; domain=.numpy.org; HttpOnly; SameSite=Lax; Secure
Last-Modified: Wed, 05 Feb 2020 21:56:26 GMT
Access-Control-Allow-Origin: *
Expires: Thu, 13 Feb 2020 17:49:18 GMT
Cache-Control: max-age=600
X-Proxy-Cache: MISS
X-GitHub-Request-Id: AC74:24E2:CE60E:ECD81:5E4589C6
Via: 1.1 varnish
Age: 472
X-Served-By: cache-scl19422-SCL
X-Cache: HIT
X-Cache-Hits: 2
X-Timer: S1581616185.037618,VS0,VE0
Vary: Accept-Encoding
X-Fastly-Request-ID: b202db743a733fc73cce6f6f08ec0c708ef5143a
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5648a4030bfafded-SCL
```
Changing the User Agent as in https://github.com/astropy/astropy/issues/8990#issuecomment-513386127 fixes the issue.

**Comment by pllim** [comment]
But change it where? What is redirecting to it?

**Comment by saimn** [comment]
> intersphinx inventory has moved: https://docs.scipy.org/doc/numpy/objects.inv -> https://numpy.org/doc/1.18/objects.inv

**Comment by pllim** [comment]
How do you put User Agent into intersphinx?

**Comment by pllim** [comment]
Ah, maybe https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-user_agent !

**Comment by saimn** [comment]
Interesting, though "_Default is "Sphinx/X.Y.Z requests/X.Y.Z python/X.Y.Z"_" which is not the default urllib User Agent...

**Comment by pllim** [comment]
FWIW, I have package that uses intersphinx from `sphinx-astropy` (where the Numpy intersphinx is defined) and have a doc build test on RTD PR builder. It passed. Does that mean GitHub is blocking CircleCI?

**Comment by saimn** [comment]
Indeed Travis seems not affected. I don't know who filter who, but it is a pretty recent change on Numpy side (https://github.com/numpy/numpy/issues/15540), maybe worth reporting?

**Comment by pllim** [comment]
Numpy temporarily reverted the re-direct, so `html-docs` *should* pass again. If you see it passes, please close this. If this comes back in the future, we might need to pin Sphinx and not use the latest version, according to Numpy developer.

**Comment by bsipocz** [comment]
> we might need to pin Sphinx and not use the latest version, according to Numpy developer.

that is not a road I want to go down on, our sphinx compatibility should not be limited by upstream compatibilities, I would rather use our stashed version of their intersphinx then to pick up the most recent one with the cost of pinning the sphinx version.

**Comment by rgommers** [comment]
I wasn't saying you need to do that because of what NumPy does. It's just that Sphinx is really bad at backwards compat, so if you install the very latest, you'll see breakage first. This is why we pin Sphinx in NumPy and SciPy doc builds.

Of course someone needs to go first, so thanks for doing that:)

**Comment by bsipocz** [comment]
@pllim - I can confirm that the html build now passes. Haven't restarted all of the build for the PRs, as we can just ignore the status, or there'll be modifications to the PRs to trigger a rebuild anyway.

@rgommers - sorry, I misunderstood it then. Yes, sphinx, and pytest and setuptools are notoriously flaky (though all got better in the past half a year or year). We can pin them if needed in ci-helpers, but happy to do other workarounds if it only affects one package, like here it was an issue only for astropy and on circleCI.

**Comment by bsipocz** [comment]
(also, I used to go into the weeds of sphinx and look into pytest for our extensions, so happy to try to help numpy in case I can, so feel free to ping me on issue, maybe I'll be in need of excuses for procrastination)
