### ISSUE TITLE
SLSQP should be spelt out in SLSQPLSQFitter docstring

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#9949]
The docstring for https://docs.astropy.org/en/stable/api/astropy.modeling.fitting.SLSQPLSQFitter.html currently says 'SLSQP optimization algorithm and least squares statistic' - but we should explicitly spell out SLSQP for anyone not familiar with it and preferably also link to some resources to explain more about it.

**Comment by Harshil-C** [comment]
@astrofrog  can we link to the SLQP  docstring (https://docs.astropy.org/en/stable/api/astropy.modeling.optimizers.SLSQP.html) in  optimizer .In there even though there is no  webpage linked there is a file t look upon even though it is complicated for users to read .

**Comment by astrofrog** [comment]
It would indeed be good to link to the optimizer, but in addition it would still be good to spell out SLSQP in the docstring.

**Comment by Harshil-C** [comment]
@astrofrog can you give a feedback on this commit or do i have to open up a pr

**Comment by kakirastern** [comment]
@Harshil-C You better open a PR for your work, so that someone can be assigned to review your PR.

**Comment by allardbrain** [comment]
Hi @Harshil-C are you still working on this? I can either help you open a PR for the work you've done or I can take this over.

**Comment by Harshil-C** [comment]
@allardbrain i did some commits which solves the issue ,if you think you have to add more  explanation go ahead .i didnt open a pr as it was a small change  @allardbrain  you can open a pr if you like and takeover this issue.

**Comment by allardbrain** [comment]
Hi @Harshil-C, no problem. Here's the text I would use. The acronym ("SLSQP") should appear after the phrase is spelled out. Feel free to put this in your PR if you like.

```
Sequential Least Squares Programming (SLSQP) optimization algorithm and least squares statistic.
See https://docs.astropy.org/en/stable/api/astropy.modeling.optimizers.SLSQP.html
```

**Comment by bsipocz** [comment]
@allardbrain - Thank you for your interest in contributing, also feel free to pick other issues to address, we have plenty of them.

**Comment by allardbrain** [comment]
Thanks for the welcome, @bsipocz :-) I will poke around and see what else I can find!

**Comment by allardbrain** [comment]
I went ahead and submitted a PR for this since there hasn't been any activity in a few weeks. I hope that's OK.
