### ISSUE TITLE
Cannot create new FITS files with astropy

### ISSUE THREAD

**Issue by RhysyT** [astropy/astropy#9954]
I was asked to submit this issue by @embray after a discussion on StackOverflow.

When I try to write a new FITS file, Python crashes to the terminal with no error messages. Minimal working example : 
```
import numpy
from astropy.io import fits as pyfits
image = numpy.zeros((100,100,100))
pyfits.writeto('FitsFile.fits',image,header=None)
```
A very small FITS file is written (few kb size) containing the basic header, but no image data.

I'm using Windows 10 (1903), Python 3.5.3, numpy version 1.17.3, and astropy version 3.2.3. : 
```
>>> import platform; print(platform.platform())
Windows-10-10.0.18362-SP0
>>> import sys; print("Python", sys.version)
Python 3.5.3 (default, May 20 2017, 19:10:40) [MSC v.1800 64 bit (AMD64)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.17.3
>>> import astropy; print("astropy", astropy.__version__)
astropy 3.2.3
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.3.1
```
The exact same code under Python 2.6, numpy 1.7.0 and pyfits runs successfully with no errors.

Thanks for any help !

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by pllim** [comment]
Using Windows 10, Python 3.7.4, Numpy 1.17.4, and `astropy` 4.1.dev, I cannot reproduce your problem. The code works fine for me.

If you also have PyFITS installed in your path, it is not advisable to do `from astropy.io import fits as pyfits` as it might result in namespace conflict between the two packages.

The file that I get:
```
$ fitsinfo FitsFile.fits
Filename: FitsFile.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       7   (100, 100, 100)   float64
```

**Comment by saimn** [comment]
What do you mean by "crashes to the terminal with no error messages", does it segfault ? Can you run the script with `python -X faulthandler` to see if there is more information ? How did you install astropy, from source, conda, something else ? Can you try to update to the latest version (4.1) ?

**Comment by RhysyT** [comment]
Many thanks for the responses.

I get no error messages of any kind. Python simply crashes and sends me back to the prompt. Same if I use -X faulthandler.

Pyfits is installed only under Python 2.6. With Python 3.5 I use astropy. I installed astropy via pip. Pip does not seem to want to let me upgrade to a newer version, will keep trying.

**Comment by pllim** [comment]
First, you need a clean Python environment that is Python 3.6 or later, then only you can install Astropy 4.0. Please do not install PyFITS in it, as PyFITS is no longer supported.

**Comment by RhysyT** [comment]
Ah, then upgrading isn't really an option. I'm using the Python provided via Blender 2.79, and upgrading the Python version is not possible. So I'm stuck with Python 3.5 and therefore astropy 3.2. Downgrading to astropy 3.1 or 3.0 has no effect, the same problem persists.

**Comment by pllim** [comment]
Python 3.5 is approaching its [end of life](https://devguide.python.org/#status-of-python-branches) in Sep 2020 (in 7 months). Perhaps you can ask Blender to support Python 3.6 or later? I am not sure if there is much we can do as 4.0 is our new LTS release and it only supports Python 3.6+.

**Comment by RhysyT** [comment]
Heh, I still use Python 2 routinely, though I'm trying not to. :)

I believe I can confirm that this is some peculiarity of my Blender install, not astropy. The latest version of Blender (2.82) uses Python 3.7.4, and even it installs astropy 3.2 (I think pip has found the existing version rather than doing a proper fresh install for some reason), the above script works as expected : the FITS file is written correctly. At least that gives me a viable workaround when I absolutely need to write new FITS files.

**Comment by pllim** [comment]
@RhysyT , I am glad you figured out a workaround that works for you! Thank you for letting us know. :smile:
