### ISSUE TITLE
Switch default IERS to use a supported CDDIS access mechanism

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9963]
Continuing the never-ending saga of IERS file availability... I got the following notice as part of a question to CDDIS (the IERS mirror server) today:

>  FTP access is being phased out over the next few months. CDDIS is STRONGLY recommending all users begin to transition to use https (https://cddis.nasa.gov/archive) as the preferred method of access to the CDDIS archive. Download procedures can be found at: https://cddis.nasa.gov/About/CDDIS_File_Download_Documentation.html, along with a Frequently Asked Questions (FAQ) link and links of how to use cURL, wget and Python (https://cddis.nasa.gov/Data_and_Derived_Products/CDDIS_Archive_Access.html)
> 
> CDDIS has also made available ftp-ssl (gdc.cddis.eosdis.nasa.gov) as a secondary method to access the archive. In some cases the use of ftp-ssl may make the conversion of existing scripts easier than using https. Examples of how to use ftp-ssl are listed at: https://cddis.nasa.gov/Data_and_Derived_Products/CDDIS_Archive_Access.html.

This *might* be ignorable if  #9453 can be fixed in time but we probably shouldn't count on it...

I looked a bit at both of these options - the https solution won't work because it requires a username and password. ftp-ssl seems likely to be the better bet, as it allows anonymous access. I'm going to try to whip up a PR to get this working, but figured I'd better log the issue first in case my PR is not successful.

cc @pllim @mhvk

**Comment by bsipocz** [comment]
@eteq - any solution for this should be on the bugfix branch

**Comment by pllim** [comment]
USNO supposedly back online in April and the FTP discontinuation not till October. So, if USNO still offline in April, at least we have 6 more months to freak out before FTP is gone. :crossed_fingers:

**Comment by bsipocz** [comment]
No point in dragging this through the milestones.

**Comment by pllim** [comment]
I don't think this is relevant anymore.
