### ISSUE TITLE
RTD version number for the dev docs is wrong

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#9967]
It appears that something in the `setuptools_scm` machinery is going wrong and rendering the version number of the devdocs incorrectly.  To see this have a look at devdocs.astropy.org / https://astropy.readthedocs.io/en/latest/ and you get this:
![image](https://user-images.githubusercontent.com/346587/74908553-f5945800-536a-11ea-80b0-045e37e3e1de.png)
Whereas it should be 4.1.devXXXXX

**Comment by eteq** [comment]
(Not clear to me if this is absolutely critical for the devdocs, but it could be a warning sign of more serious issues when an actual release is made with the new machinery?)

**Comment by bsipocz** [comment]
interesting, the circleCI build looks right: https://59958-2081289-gh.circle-artifacts.com/0/docs/_build/html/index.html

**Comment by Cadair** [comment]
You need to ask RTD to do a full clone i.e. https://github.com/readthedocs/readthedocs.org/issues/5648

**Comment by pllim** [comment]
Has someone brought this to RTD yet?

**Comment by pllim** [comment]
Hey, wait a minute. Is this already fixed? I see v4.1.dev...

**Comment by bsipocz** [comment]
Indeed, has been fixed! Thanks all for the very quick reporting and turnaround.
