### ISSUE TITLE
MAST: No explanation for table cross-match

### ISSUE THREAD

**Issue by odysseus9672** [astropy/astropy#9974]
### Description

Right now the [documentation](https://astroquery.readthedocs.io/en/latest/mast/mast.html) for AstroQuery's MAST api doesn't mention the capability to upload a table for bulk cross-matching of sources. This is a feature provided by the AstroQuery's [VizieR API](https://astroquery.readthedocs.io/en/latest/vizier/vizier.html#query-with-table), and is supported by [MAST's API](https://catalogs.mast.stsci.edu/docs/panstarrs.html#crossmatch), so it seems like a good idea for the MAST API to do the same.

I title this to be about the AstroQuery documentation, because I assume that the feature already exists, but I there's no explanation for how to query with a table in MAST's `Catalogs`. I tried to construct a table in the same fashion as for VizieR, with columns named "name", "_RAJ2000", and "_DEJ2000", but got `TypeError: Argument cannot be parsed as a coordinate`.

**Comment by pllim** [comment]
I think you got to the wrong repo. Please open an issue over at https://github.com/astropy/astroquery/issues instead. We apologize for any inconvenience caused.

cc @ceb8

**Comment by ceb8** [comment]
@odysseus9672 astroquery.mast does not currently support crossmatch.
