### ISSUE TITLE
Move multiband LombScargle from gatspy

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#9982]
Almost all of the the LS functionality has been moved to astropy from astroML and gatspy. The exception is the multiband version.

The multiple location and versions of the implementation cause some confusing amongst users, some of which I hear about, but my current response is somewhat not ideal: "always use the astropy version, as it's the same one used to be in astroML/gatspy with some extra, but if you have multiband data, well, then stick with the gatspy version"

To resolve this, I propose to do the move it here, upstream.

cc @astrofrog  as the other astropy.timeseries maintainer; and @mwcraig and @mhvk who did most of the review of the original big PR.

https://github.com/astroML/gatspy/issues/38

**Comment by pllim** [comment]
This would be a nice addition for v4.1 if it can be done soon. :wink:

**Comment by bsipocz** [comment]
Yes, 4.1 would be my target 😄

**Comment by dougbrn** [comment]
Hi there @bsipocz @pllim , the LINCC Frameworks team with the Rubin Observatory has been interested in potentially porting the gatspy multiband implementations to Astropy. Since it looks like this was being worked on a few years ago, I wanted to ask if there were any current plans to port multiband? Don't want to step on anyone's toes in case there was 😄 .

**Comment by pllim** [comment]
I am not aware of any PR or any plan wrt this issue, but maybe @bsipocz can provide an update.

**Comment by mwcraig** [comment]
I didn't see any in-progress PRs; it would be really nice to have this ported over. If you open a PR feel free to ping me for a review, especially of the documentation.  My recollection from using multiband last year was that the current documentation was not quite specific enough to be easy to start to use.
