### ISSUE TITLE
Default FITS WCS has CRPIX set to 0

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#9989]
### Description

This is not really a bug nor can I call it a feature request. It is about the default value of `CRPIX` of a `WCS` object just constructed with default parameters `WCS()`.

While `CRPIX` is a 1-based pixel position, the default constructor create a WCS with `CRPIX1` and `CRPIX2` set to 0.0.

```python
In [1]: from astropy.wcs import WCS
   ...: w = WCS()

In [2]: w
Out[2]:
WCS Keywords

Number of WCS axes: 2
CTYPE : ''  ''
CRVAL : 0.0  0.0
CRPIX : 0.0  0.0
PC1_1 PC1_2  : 1.0  0.0
PC2_1 PC2_2  : 0.0  1.0
CDELT : 1.0  1.0
NAXIS : 0  0
```

This is _strange_ because if I wanted to compute world coordinates at the `CRPIX` location I would have to do:

```python
In [3]: w.wcs_pix2world(0, 0, 1)
Out[3]: [array(0.), array(0.)]

In [4]: w.wcs_pix2world(-1, -1, 0)
Out[4]: [array(0.), array(0.)]
```
Image pixel at `-1, -1`???

### Expected behavior
```python
In [5]: WCS()
Out[5]:
WCS Keywords

Number of WCS axes: 2
CTYPE : ''  ''
CRVAL : 0.0  0.0
CRPIX : 1.0  1.0
PC1_1 PC1_2  : 1.0  0.0
PC2_1 PC2_2  : 0.0  1.0
CDELT : 1.0  1.0
NAXIS : 0  0
```

This is not really a bug. But I think it would be more valuable from the didactic point of view to have `CRPIX` set to `(1, 1)` to re-iterate that `CRPIX` is 1-based.

**Comment by nden** [comment]
The current behavior looks correct to me. And the defaults are defined in the first WCS paper

https://www.aanda.org/articles/aa/pdf/2002/45/aah3859.pdf

**Comment by mcara** [comment]
Weird defaults but you are right: it is in the paper.
