### ISSUE TITLE
TimeDelta.to_value does not seem to exist?

### ISSUE THREAD

**Issue by 4ks1** [astropy/astropy#9990]
I am trying to return the difference of two Time objects in seconds:
```python
delta_t = ETT[i]-ETT[i-1] # delta_t is of type TimeDelta
print(str(delta_t.to_value(format='sec')))
```
... raises an `AttributeError: 'TimeDelta' object has no attribute 'to_value'`
I can do 
```python
print(str(delta_t.to(unit='s')))
```
but then I get a quantity with an associated unit, not a scaler as to_value should provide.
Can it be the astropy documentation is ahead of its code base? I just cannot get `TimeDelta.to_value` to work.
Thanks for any advise.

EDIT: Formatting

**Comment by mhvk** [comment]
What astropy version are you using? `TimeDelta.to_value` is new in astropy 4.0, and for me things work fine:
```
import astropy
astropy.__version__
# '4.0'
from astropy.time import Time
td = Time.now()-Time.now()  
td.to_value(format='sec')
# -0.0005779999902699728
td.to_value(u.s)                                                                              
# -0.0005779999902699728
```
