### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by accismus** [astropy/astropy#9997]
Hi all,

I'm a technical writer, and I'm working on a new open source technical documentation framework called Accismus. I'm trying to gauge what the interest in something like that might be. I'm planning the framework so no knowledge of HTML is necessary, you can do everything in plain text, and the resulting pages meet accessibility standards. Would this be something BioJava could use?

To be clear, I am NOT asking for money. I do plan to launch a Kickstarter campaign eventually, but for now, I just want to know if the whole thing would actually help anybody. There's no reason to try and build something that won't be of any use, after all.

I'd appreciate any opinions you might have; thanks!

**Comment by accismus** [comment]
My apologies, I realized after posting this that it might be considered soliciting. That was not my intention; I was just trying to gauge interest. Please disregard this post.

**Comment by pllim** [comment]
Hello, @accismus ! Thank you for reaching out. You could try posting to other channel(s) of communications that might be more appropriate for such topic (please see https://www.astropy.org/help.html for options involving the Astropy project).

In addition, you might also be interested in https://developers.google.com/season-of-docs (not affiliated with Astropy).
